### ISSUE TITLE
DataExporter for TreeTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#10]
Currently DataExporter only supports DataTable, add ability to export TreeTable as well.

**Comment by NaveenGoyal95** [comment]
Please add this feature

**Comment by rengar-zz** [comment]
Please add this feature

**Comment by melloware** [comment]
Now that the DataExporter refactoring has been completed thanks to @ravihariharan  this ticket is now possible to implement  if someone wants to submit a PR.
