### ISSUE TITLE
TreeTable: NodeSelectEvent.isContextMenu is always false

### ISSUE THREAD

**Issue by HenrikRueping** [primefaces/primefaces#10001]
### Describe the bug

Opening a contextMenu on a TreeTable with an ajax-Event-Listener for the NodeSelectEvent fires an Event where isContextMenu is set to false. It seems like the wrong constructor of NodeSelectEvent is used in TreeTable.java. There is another one, where isContextMenu can be set. 

[Link to related forum post](https://forum.primefaces.org/viewtopic.php?f=3&t=79960).

### Reproducer

Xhtml
```xhtml
<h:form id="form">
<p:treeTable id="treetable" value="#{myBean.getNode()}" var = "document" selectionMode="single" selection="#{myBean.selectedNode}">
  <p:ajax event="select" listener="#{myBean.onNodeSelect}"/>
  <p:column headerText="Name">
    <h:outputText value="#{document}"/>
  </p:column>
</p:treeTable>
<p:contextMenu for="treetable">
  <p:menuitem value="View" action="#{myBean.doNothing()}" />
</p:contextMenu>
</h:form>
```

Bean
```java
@Named
@ApplicationScoped
public class MyBean {

	DefaultTreeNode<String> node;
	DefaultTreeNode<String> selectedNode;
	
	public MyBean() {
		node= new DefaultTreeNode<>("root",null);
		new DefaultTreeNode<>("child1",node);
		new DefaultTreeNode<>("child2",node);
		new DefaultTreeNode<>("child3",node);
	}

	public final DefaultTreeNode<String> getNode() {
		return node;
	}
	
	public void doNothing() {
		
	}
	
	public final DefaultTreeNode<String> getSelectedNode() {
		return selectedNode;
	}

	public final void setSelectedNode(DefaultTreeNode<String> selectedNode) {
		this.selectedNode = selectedNode;
	}

	public void onNodeSelect(NodeSelectEvent e) {
		PrimeFaces.current().dialog().showMessageDynamic(new FacesMessage(FacesMessage.SEVERITY_INFO, "Title", "ContextMenu is "+e.isContextMenu()));
	}
}
```

### Expected behavior

The fired NodeSelectEvent should have isContextMenu set to true.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.2

### Java version

11

**Comment by HenrikRueping** [comment]
It seems like the proposed fix does not fix the issue fully. I started Jboss in debug-mode and even when I do a right click on a treeTable, the value of the local variable eventName in TreeTable.queueEvent is "select" and not "contextMenu". 

So the requestParameterMap gets the entry Constants.RequestParams.PARTIAL_BEHAVIOR_EVENT_PARAM="select" somewhere. I dont  know exactly where and why things work fine for the component "Tree".

**Comment by melloware** [comment]
OK it might be a bug in the treetable.js where its firing `select` when you right click on the row.  I think datatable has already handled this situation so maybe compare what datatable.js is doing vs treetable.js.

**Comment by melloware** [comment]
Thanks for your work. I fixed the JS issue by not calling the 'select' event when a 'contextMenu` event is happening which is what datatable does.

**Comment by HenrikRueping** [comment]
For the same of completeness I verified that this fully fixed the issue above. Now:
1) In the case of a right-click the ajax-event select is not fired.
2) The selected node gets updated in the bean.
3) If we have an ajax-event "contextMenu", this one is fired (so if we wanted to execute some code in the case of e.isContextMenu()=true, we can do it here.

Thanks a lot.
