### ISSUE TITLE
RemoteCommand: support of Dialog Framework

### ISSUE THREAD

**Issue by astappiev** [primefaces/primefaces#10017]
### Description

I would like to use dialog framework from a remote command and receive a result from it.

E.g.:
```html
<p:remoteCommand name="test" actionListener="${bean.openDialog}">
    <p:ajax event="dialogReturn" listener="#{neam.onDialogResult}" />
</p:remoteCommand>
```

### Describe the solution you would like

Now the example above throws an error : `<p:ajax> Unable to attach behavior to non-ClientBehaviorHolder parent`.

Perhaps, it should implement `ClientBehaviorHolder` :)

**Comment by melloware** [comment]
@astappiev did you want to test it out and submit a PR?

**Comment by astappiev** [comment]
Here is my attempt to extend RemoteCommand and implement the interface (mostly by coping required methods from menuItem)
https://github.com/astappiev/primefaces-test/commit/863aa02dfaba828cf3107f98a3fa1ae485341df2

Somehow it doesn't work, also, in my project, it actually threw an error on page load, but in the `primefaces-test`, it doesn't for some reason. Maybe because of different error handling.

Please, point me out if I miss something I must implement to make it work.

**Comment by Rapster** [comment]
I think @melloware is the simplest way to go about it, otherwise it involves too many changes for something that can easily worked-around

**Comment by astappiev** [comment]
That is exactly how I overcome it, however, it would be nice to have some cleaner solution.

That was first time I used the dialog framework, and except this there are other limitations that I met.

I will continue tomorrow and see if I can find any better solution and sure, will post some new issues :)

**Comment by Rapster** [comment]
Sounds good, we love issues 😉

**Comment by astappiev** [comment]
A harmless one: every time we close dialog first time (from a button, nothing unexpected), a JS error is logged in a browser: `Widget for var 'frmTest_j_id_b_dlgwidget' not available!`
Can be reproduced in https://github.com/astappiev/primefaces-test/commit/e77a21ce8dbbc9f09a05fc1f4ca3defebe71c224

**Comment by Rapster** [comment]
One issue per ticket please

**Comment by melloware** [comment]
Going to close this for now as the workaround works and the changes are too drastic for the value they return.

**Comment by melloware** [comment]
Of course can re-open if solution is presented. And @astappiev if you find other DF issue just open new tickets for each issue please!
