### ISSUE TITLE
Not possible to intercept Dialog Close Event to prohibit windows closure

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#1001]
How to intercept CLOSE event (clicking on X button in titlebar of a dialog) to display a ConfirmDialog Box and to allow user to stop closing of dialog. 
Exemple: think about Word (or LibreOffice), when user click on close button before saving his work.
In this situation, Word notify user about this situation and porpose some alternative.

I'm migrating a .Net application that displays a ConfirmDialogBox when user closes a Window.
This DialogBox informs user that he has changed some fields and that his work is not saved.

The user has 3 possibilities.
1. save his change and close Window
2. don't save his change and close Window
3. save nothing, but Window is not closed.

On .Net platform, we can do that (Point 3) in intercepting FormClosing event and changing CANCEL Property to TRUE.

I will do the same on Primefaces 5.3, but this seems not working because this interesting functionnality is missing.

The actual only possiblity is to hide the Dialog Close Button and to use a p:commandButton !!!

I think that it will be interesting to add a event "beforeClosing" to p:dialog that is called before "close" event and that allows to stop the closing of dialog !
The top solution will be to add this property in actual Dialog Close Event !

When this Change Request is accepted, I would this same improvement on DialogFramework !

**Comment by kukel** [comment]
Panel or Dialog? Or both?

**Comment by schlebe** [comment]
My proposition is for p:dialog
I have changed my comment and the title.

**Comment by schlebe** [comment]
this message to reopen this Change Request

**Comment by schlebe** [comment]
this feature doesn't work in PrimeFaces 6.0.
... no chance

**Comment by cnsgithub** [comment]
@schlebe As another workaround, just in case you further want to use the close button, you could override the button's click event handler.

E.g. on https://primefaces.org/showcase/ui/overlay/dialog/basic.xhtml to change the behavior when closing basic dialog, just do this:
```javascript
PF('dlg1').closeIcon.off('click'); 
PF('dlg1').closeIcon.click(function() { if(confirm('Close?')) PF('dlg1').hide(); });
```

**Comment by schlebe** [comment]
@cnsgithub: that is very interesting because that answers to another response that I have just posted on [https://github.com/primefaces/primefaces/issues/3373](issue-3373) !

The "closeIcon" solution for this issue can be used for DialogFramework and with closeIcon, the Confirmation dialog is displayed before DialogFramework is hidden !!! Super

I propose to continue our discussion on 3373 issue.

I close this issue, because your response is the best that I have received.

Thanks

**Comment by cnsgithub** [comment]
@schlebe You're welcome. The correct link to the issue is https://github.com/primefaces/primefaces/issues/3373. I just mention this in order to get correctly referenced by GitHub.

**Comment by jithin1612** [comment]
@cnsgithub.....Thankyou very much for the alternative solution.
