### ISSUE TITLE
DataTable: Row Expansion + nested dataTable hide headers

### ISSUE THREAD

**Issue by ericacoss** [primefaces/primefaces#10018]
### Describe the bug

p:column headers inside a p:dataTable in  a rowExpansion column no longer show headerTitle elements in Primefaces12.  Primefaces11 is ok.
![sub](https://user-images.githubusercontent.com/107699484/231838996-40da9344-d30f-4290-bf03-7653313022ce.png)

### Reproducer

Upon toggle via <p:rowToggler/>,  the table inside the rowExpansion should display its headers.
![GITISSUERES](https://user-images.githubusercontent.com/107699484/231841731-3f5f77bb-5348-4f67-86b2-c156a1d7f5ec.PNG)

### Expected behavior

headerText values of tables inside the rowExpansion columns should display. Currently the css attribute upon inspection is display:none. If I modify the DOM via Developers tools and change the value to block, the titles display correctly.
![dispnone](https://user-images.githubusercontent.com/107699484/231842454-49d46ca2-da86-4141-abfe-f31a43470b55.PNG)

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

chrome

**Comment by jepsar** [comment]
Please test with 13. If you can reproduce it, please provide a runnable reproducer https://github.com/primefaces/primefaces-test. For me it's working with PF13.

**Comment by melloware** [comment]
Your issue is `reflow="true"` its not designed to work with Row Expansions.
