### ISSUE TITLE
Clock: add missing attributes in taglib XML

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#10021]
### Description

Noticed that `p:clock` does not declare a `widgetVar` attribute despite having a client-side API.
OK, you can do:
```javascript
let clockWidget = PrimeFaces.getWidgetById("pClock");
let date = clockWidget.current;
```
but would be nice to have it the usual way,
```javascript
let clockWidget = PF("clockWidgetVar");
```

### Describe the solution you would like

```xml
        <attribute>
            <description>
                <![CDATA[Name of the client side widget.]]>
            </description>
            <name>widgetVar</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
```

**Comment by Rapster** [comment]
Clock implements Widget, so you can use PF('clock') already. I just tried on the showcase... From what you described, the problem is just that widgetVar attribute doesn't show on the IDE autocomple list no?

**Comment by tandraschko** [comment]
id/rendered/binding is also missing, will add them

**Comment by fcorneli** [comment]
mmm... I've been playing around with a JSF component to test other JSF components:
https://demo.e-contract.be/ejsf-demo/test-component.xhtml
For the moment it's limited towards testing plain String attributes for XSS vulnerabilities.
Could be interesting to add a test for such missing attributes as well? Would allow us to scan the entire PF tag set in an automated fashion.

**Comment by Rapster** [comment]
Yeah, I had that idea in the past as well, I don't think it should be too hard to implement. You can create a new issue for that 😉
