### ISSUE TITLE
Menubar: NullPointerException in MenubarRenderer when using dynamic model

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#10030]
### Describe the bug

When using a menubar with a dynamic model and using elements without setting an ID like in the docs (https://primefaces.github.io/primefaces/12_0_0/#/components/menu?id=dynamic-menus), the following exception occurs:
```
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because the return value of "org.primefaces.model.menu.Submenu.getId()" is null
    at org.primefaces.component.menubar.MenubarRenderer.encodeSubmenuIcon (MenubarRenderer.java:68)
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeSubmenu (TieredMenuRenderer.java:189)
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements (TieredMenuRenderer.java:142)
    at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeMenu (TieredMenuRenderer.java:91)
```

Example XHTML:
```
<p:menubar model="#{testView.model}">
```

Example Model:
```
public MenuModel getModel() {
    DefaultMenuModel menuModel = new DefaultMenuModel();

    DefaultSubMenu subMenu = DefaultSubMenu.builder()
            .label("SubMenu")
            .build();

    DefaultMenuItem menuItem = DefaultMenuItem.builder()
            .value("MenuItem")
            .build();

    subMenu.getElements().add(menuItem);

    menuModel.getElements().add(subMenu);

    return menuModel;
}
```

### Reproducer

You can find the reproducer here: https://github.com/mkomko/primefaces-test/tree/dynamic-menu-error
Just running it will produce the exception.

### Expected behavior

No exception occurs and the menubar is rendered correctly using dynamic IDs.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.1

### JSF implementation

All

### JSF version

4.0

### Java version

17.0.5

**Comment by tandraschko** [comment]
PF sets the ID on the MenuModel
but if you regenerate your model each time in the getter, the id is lost of course

so you need to store it in a var instead of always create a new model in the getter

**Comment by mkomko** [comment]
@tandraschko Thank you very much! I did that independently and I was indeed able to delete the ID assignments now. I just had to store my MenuModel in a Map in a RequestScoped class to reflect the dynamic nature of my page. Thanks!
