### ISSUE TITLE
TreeTable: add selection to MVS

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10040]
Currently MVS is implemented in TreeTable but it seems that selection implementation of DataTable and TreeTables is quite different

DataTable was refactored several times, TreeTable not

Therefor its quite a big task

**Comment by melloware** [comment]
Isn't this already tracked in #8756 ?

**Comment by tandraschko** [comment]
Yes
Maybe we should add a list there, what needs to be implemented as MVS already exists in TreeTable

**Comment by melloware** [comment]
Yep will do!
