### ISSUE TITLE
TreeTable/DataTable: Wrong default sortMode in taglib

### ISSUE THREAD

**Issue by l-uuz** [primefaces/primefaces#10045]
### Describe the bug

The taglib.xml contains a wrong default value for TreeTable/DataTable `sortMode`. According to the [Documentation](https://github.com/search?q=repo%3Aprimefaces%2Fprimefaces+%22defines+sorting+mode%2C+valid+values+are%22&type=code), the default values for these attributes are `multiple`. The taglib contains the following definitions:

```xml
        <attribute>
            <description>
                <![CDATA[Defines sorting mode, valid values are "single" (default) and "multiple".]]>
            </description>
            <name>sortMode</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
```

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by Rapster** [comment]
True, I think it's been there since 10.0.0
