### ISSUE TITLE
Panel: MVS broken with p:panel inside ui:repeat

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#10047]
### Describe the bug

Collapsing a `p:panel` inside of a `ui:repeat` causes all panels after it to be collapsed as well

### Reproducer

see `testMultiViewStateUiRepeat` in https://github.com/jungm/primefaces/commit/6894445b4c5c5a98e9a0998cb5a93d7c5e541994

### Expected behavior

Panels with MVS in `ui:repeat` work like panels with MVS that aren't in a `ui:repeat`

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

**Comment by jungm** [comment]
tested a bit more and tbh I think this might be a bug in MultiViewState in general? Same behaviour can be reproduced with:
```
            <ui:repeat id="repeat" value="#{panel002.headings}" var="heading">
                <p:tabView multiViewState="true">
                    <p:tab title="first"/>
                    <p:tab title="second"/>
                    <p:tab title="third"/>
                </p:tabView>
            </ui:repeat>
```

and

```
            <ui:repeat id="repeat" value="#{panel002.headings}" var="heading">
                <p:accordionPanel multiViewState="true" multiple="true">
                    <p:tab title="first"/>
                    <p:tab title="second"/>
                    <p:tab title="third"/>
                </p:accordionPanel>
            </ui:repeat>
```

**Comment by tandraschko** [comment]
exactly for this case rowStatePreseved was added in UIData but it seems it was not ported to ui:repeat: https://github.com/jakartaee/faces/issues/1263

Hope to get it soon into Faces specs
