### ISSUE TITLE
outputPanel: Conditionally render the component on toggleSwitch's change event

### ISSUE THREAD

**Issue by SoozaV** [primefaces/primefaces#10042]
### Describe the bug

I have a toggleSwitch component and an outputPanel component, I want to conditionally render the outputPanel based on the toggleSwitch value but it doesn't seem to work. I've verified that the toggleswitch value updates correctly, but it still doesn't seem to affect the outputPanel component.

The reproducer works fine when I conditionally render single components like `<h:outputText />` but not when I wanna render nested components like:

```
<p:outputPanel>
   more code...
</p:outputPanel>
```

Regards!

### Reproducer

```
// mode code...
<h:form>
    <p:panel>
        <div class="grid">    
                <div class="col">
                    <p:outputLabel value="Show outputPanel section"/>
                    <div class="flex align-items-center mt-3">
                        <p:outputLabel value="No" />
                            <p:toggleSwitch id="toggleTest" value="#{bean.showPanel}">
                                <p:ajax event="change" update="panelTest" />
                            </p:toggleSwitch>
                        <p:outputLabel value="Yes" />
                    </div>
                </div>
        </div>
        <p:outputPanel id="panelTest" rendered="#{bean.showPanel}">
            <div class="col-4">
                more code...
            </div>
            <div class="col-4">
                more code...
            </div>
            <div class="col-4">
                more code...
            </div>
        </p:outputPanel>
    </p:panel>
</h:form>
// mode code...
```

### Expected behavior

Show the outputPanel component when the toggleSwitch value is true and hide it when the value is false.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### Theme

Olympos

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

8.0

**Comment by jepsar** [comment]
Please use the forum or StackOverflow to ask questions.

https://stackoverflow.com/questions/14790014/ajax-update-render-does-not-work-on-a-component-which-has-rendered-attribute
