### ISSUE TITLE
Datatable Select All Checkbox

### ISSUE THREAD

**Issue by ivancsl** [primefaces/primefaces#10056]
### Describe the bug

We are experiencing a bug where the select all checkbox doesn't work after datable has filtered a column. Steps to reproduce:

1. Filter datatable in a column
2. Tick select all checkbox of datatable
3. Execute action button on this datatable

Result: No record has been executed. It's like no records where selected at all even though we ticked select all on the datatable and see the filtered records are ticked.

### PrimeFaces edition

None

### PrimeFaces version

5

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

1.6

**Comment by melloware** [comment]
PF 5 is quite old. Have you tried it on 12?

I am sure it is fixed by now and I don't think anyone in the community will invest any time investigating an issue in PF 5

**Comment by jepsar** [comment]
Please try with PrimeFaces 13. Version 5 is years old.
