### ISSUE TITLE
PanelGrid: With layout=grid, with child <p:row> and without columnClasses attribute throw java.lang.ArithmeticException

### ISSUE THREAD

**Issue by raul810y** [primefaces/primefaces#10058]
### Describe the bug

In PanelGrid component, if layout=grid, and I put inside <p:row> and without columnClasses attribute throw java.lang.ArithmeticException. 

If I add columnClasses attribute the problem is resolved 'cause length > 0:
<img width="901" alt="Captura de Pantalla 2023-04-23 a la(s) 1 51 28" src="https://user-images.githubusercontent.com/30551904/233827153-b566d394-fc03-46f3-8a61-ffb25ca70900.png">

### Reproducer

1. In Primefaces Showcase demo, in the last example of p:panelGrid (Responsive Grid), if I delete columnClasses attribute  obtain   ArithmeticException:

`Caused by: java.lang.ArithmeticException: / by zero
	at deployment.archetype.ear.archetype-web.war//org.primefaces.component.panelgrid.PanelGridRenderer.encodeGridBody(PanelGridRenderer.java:315)
	at deployment.archetype.ear.archetype-web.war//org.primefaces.component.panelgrid.PanelGridRenderer.encodeGridLayout(PanelGridRenderer.java:113)
	at deployment.archetype.ear.archetype-web.war//org.primefaces.component.panelgrid.PanelGridRenderer.encodeEnd(PanelGridRenderer.java:56)
	at jakarta.faces.api//jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:586)`

2. Or just try this:
`<p:panelGrid layout="grid" columns="1">
    		<p:row>
    			<p:inputText id="input1"/>
    		</p:row> 
		<p:inputText id="input1"/>
		<p:inputText id="input2"/>		
</p:panelGrid> `

### Expected behavior

The columnClasses attribute in p:panelGrid should not be mandatory

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

8 and later

### Browser(s)

Chrome Versión 111.0.5563.64 (Build oficial) (x86_64) macOS

**Comment by melloware** [comment]
@raul810y this is already fixed in 13.0.0-SNAPSHOT.  Try this reproducer by running `mvn clean jetty:run`.
[pf-10058.zip](https://github.com/primefaces/primefaces/files/11303750/pf-10058.zip)
