### ISSUE TITLE
New component "Floating Action Button"

### ISSUE THREAD

**Issue by ybendek** [primefaces/primefaces#1006]
I would like to propose the creation of a new component similar as the "Floating Action Button" defined in Material Design by google, commonly used in android apps and very helpfull to use from small devices.

http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-large-screens

It could be and awesome component to have with PrimeFaces

**Comment by kukel** [comment]
can this not be done by using css?

**Comment by sudheerj** [comment]
Some of the new Primefaces premium themes uses google material design.You might check there for its availability.

**Comment by ybendek** [comment]
not, it cannot be done with a simple css... this component is not just a button on the bottom of the screen, if you see the googel reference, this component includes lot of interesting features mainly in behavior (http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior) and transitions (http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions), for example the speed dial feature or the toolbar.

not this component is not included with others premium themes like Rio, theme based in google material design.

**Comment by kukel** [comment]
`<rant>`Hmmm and all this from the company that changed the UI of their maps app more in the last two years then M$ did with their office apps in a decade...`</rant>`

So effectively it is a combination of dock, toolbar and splitbutton on steroids (morphing/transition capable). In my opinion there is much more relevant work to do on PrimeFaces than adding a button like this (the non-steroid version can be achieved with some small amount of creativity). But if PrimeFaces opens up their 'participate-in-code'  some more, I have no objection the core team works on this.

**Comment by khanasad** [comment]
FAB would be the perfect ui component for Primefaces.

**Comment by melloware** [comment]
Duplicate: #3491

**Comment by jepsar** [comment]
@ybendek Can't you use https://www.primefaces.org/showcase/ui/menu/stack.xhtml with some custom styling?

**Comment by melloware** [comment]
Finally Arrived in PFE 7.0.1: https://www.primefaces.org/showcase-ext/views/fab.jsf

**Comment by ybendek** [comment]
@melloware  Awesome, it looks great

**Comment by melloware** [comment]
@jepsar did all the hard work!

**Comment by ybendek** [comment]
@jepsar thanks...this will be very usefull  :)
