### ISSUE TITLE
Unable to Hide Boarders in Table Component

### ISSUE THREAD

**Issue by 00002911** [primefaces/primefaces#10061]
### Describe the bug

The border of the table that was added into a template cannot be hidden. The size of the table border is set to 0. However, even after saving the modified settings, the template's table border is still visible.

### Expected behavior

The editor-inserted table's borders should be able to be hidden by the user.

### PrimeFaces edition

None

### PrimeFaces version

6.2

### JSF implementation

All

### JSF version

2.2

### Java version

1.8

**Comment by jepsar** [comment]
PrimeFaces 6.2 is an old version. Please try with 12 and use the showGridlines attribute. See https://primefaces.github.io/primefaces/12_0_0/#/components/datatable
