### ISSUE TITLE
DataTable: Clicking label of a SelectOneMenu inside of a DataTable changes selection

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#10072]
### Describe the bug

Clicking the label (`.ui-selectonemenu-label`) part of a SelectOneMenu inside of a DataTable changes the DataTable selection, causing behavior the user probably doesn't expect (interacting with an input vs selecting something in the table)

Clicking the Icon (`.ui-selectonemenu-trigger`) right next to the label does work as I'd expect. It just opens the SelectOneMenu without selecting the row

### Reproducer

Modified example from PF Showcase:

```xhtml
            <p:dataTable id="radioDT" var="product" value="#{dtSelectionView.products5}"
                         selection="#{dtSelectionView.selectedProduct}" rowKey="#{product.id}">
                <p:ajax event="rowSelect" process="@this" update="radioDT"/>

                <p:column selectionMode="single" style="width:16px;text-align:center"/>
                <p:column headerText="Code">
                    <h:outputText value="#{product.code}" />
                </p:column>

                <p:column headerText="Name">
                    <h:outputText value="#{product.name}" />
                </p:column>

                <p:column headerText="Category">
                    <h:outputText value="#{product.category}" />
                </p:column>

                <p:column headerText="Quantity">
                    <h:outputText value="#{product.quantity}" />
                </p:column>

                <p:column headerText="Inventory Status">
                    <p:selectOneMenu value="#{product.inventoryStatus}">
                        <p:ajax process="@this" update="@this"/>

                        <f:selectItem itemLabel="In Stock" itemValue="INSTOCK"/>
                        <f:selectItem itemLabel="Out of Stock" itemValue="OUTOFSTOCK"/>
                        <f:selectItem itemLabel="Low Stock" itemValue="LOWSTOCK"/>
                    </p:selectOneMenu>
                </p:column>

                <f:facet name="footer">
                    <p:commandButton process="radioDT" update="@form" icon="pi pi-search" value="View"
                                     oncomplete="PF('productDialog').show()"/>
                </f:facet>
            </p:dataTable>
```

Steps to reproduce
- click on the label of the SelectOneMenus

 I've added a p:ajax bound to the rowSelect event that updates the table to make the behavior i'm describing more visible. This setup makes it impossible to open the SelectOneMenu by clicking the label

Full example project: 
[dt-with-selectonemenu.zip](https://github.com/primefaces/primefaces/files/11350481/dt-with-selectonemenu.zip)

### Expected behavior

No row selection is being made when interacting with a SelectOneMenu in a DataTable

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Good reproducer!  PR submitted.
