### ISSUE TITLE
IT: Nightly UpdateForm001Test failure

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#10074]
On the overnight full tests getting..

`UpdateForm001Test.testUpdateForm:44 » Timeout Timeout while waiting for AJAX complete!`

**Comment by christophs78** [comment]
Probably related to https://github.com/primefaces/primefaces/commit/8c33ded0e440bfd9d277a19bb429e5602d16667e.
We may have to modify this IT. But crazy why it depends on CSP on or off.

**Comment by christophs78** [comment]
And - hold my beer - this is also related to InputNumber007Test#testNoValueChangeEventAfterUpdate.
With CSP on this test fail´s local too.

**Comment by melloware** [comment]
YEAH ok let me investigate.  I was running with CSP off

**Comment by melloware** [comment]
OK so with CSP on its a timing issue because `PrimeFaces.csp.register` is registering the change event on AJAX update AFTER this code executes.  so its adding an extra change event
