### ISSUE TITLE
upgrade jQuery to 1.12.4

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#1007]
http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
http://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/
http://blog.jquery.com/2016/03/17/jquery-1-12-2-and-2-2-2-released/
http://blog.jquery.com/2016/04/05/jquery-1-12-3-and-2-2-3-released/
http://blog.jquery.com/2016/05/20/jquery-1-12-4-and-2-2-4-released/

**Comment by tandraschko** [comment]
Note for PF team:
- they renamed the AJAX "complete" callback to "always" (https://github.com/jquery/jquery/commit/fd80f5970f38ff12c7fa2caa8c1de955301a6979) - this will break our oncomplete

**Comment by sudheerj** [comment]
'complete' is better than 'always'.Because onstart and onalways callback combination doesn't sounds good that much :)

**Comment by tandraschko** [comment]
what do you mean?
We must not change anything but we must align jquery bridge to use always instead complete.

**Comment by kukel** [comment]
Since they already announced jQuery 3.0, maybe it is time to move on to 2.2 (maybe with some partial backwards compatibility plugin)? Anyone seriously still developing for IE8 is either working for a large insurance company, a government, multinational or just a lunatic.The former 3 should be able to pay large amounts of support to PF for a custom jQuery version :-)

**Comment by tandraschko** [comment]
"Anyone seriously still developing for IE8" - here! ;)
I would still wait 0,5 - 1 year as older IE support was cancelled some weeks ago?

**Comment by erickdeoliveiraleal** [comment]
now 1.12.1 http://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/

**Comment by kukel** [comment]
@erickdeoliveiraleal : you can edit the title I think...

**Comment by erickdeoliveiraleal** [comment]
https://github.com/jquery/jquery/compare/1.12.1...1.12.2

**Comment by erickdeoliveiraleal** [comment]
http://blog.jquery.com/2016/04/05/jquery-1-12-3-and-2-2-3-released/

**Comment by erickdeoliveiraleal** [comment]
this can be closed, since there is this commit: https://github.com/primefaces/primefaces/commit/8bf78c56742ed023388bed342de54c80c957f5cc

**Comment by erickdeoliveiraleal** [comment]
Since https://github.com/primefaces/primefaces/commit/8bf78c56742ed023388bed342de54c80c957f5cc was reverterted, this can be reopened

**Comment by erickdeoliveiraleal** [comment]
#2204

**Comment by tandraschko** [comment]
Created a new issue for both upgraded jquery + jquery ui -> #2233
