### ISSUE TITLE
Overlay Panel: Closed on scrolling

### ISSUE THREAD

**Issue by l-uuz** [primefaces/primefaces#10085]
### Describe the bug

The Overlay Panel closes when you scroll. Even if the cursor is in the panel.

### Reproducer

1. Open https://www.primefaces.org/showcase/ui/overlay/overlayPanel.xhtml on a Desktop PC
2. Click one of the buttons to open the panel
3. Turn the scroll wheel

The panel closes.

### Expected behavior

The panel should not close. In [8.0](https://www.primefaces.org/showcase-v8/ui/overlay/overlayPanel.xhtml), it does not close.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox

**Comment by melloware** [comment]
See #8726 this was intentional.

**Comment by jepsar** [comment]
This behavior is now hardcoded. Maybe add an attribute to toggle it?

**Comment by melloware** [comment]
I think the reason it is done this way is there are so many scenarios that people report with scrolling with an overlay open that closing the overlay when you scroll is the best UX experience. If the user is scrolling the background browser window then the foreground windows should be closed in my opinion as you are not scrolling the current element.

**Comment by melloware** [comment]
@jepsar maybe just for overlaypanel we can add this option since its a custom overlay for people to use.  I think all other use cases like SelectOneMenu etc are all doing the right thing by closing on Scroll.

**Comment by jepsar** [comment]
Alright. And you can probably work around this with a monkey patch.

**Comment by melloware** [comment]
@l-uuz I forgot we already added this for 13.0.0 you can globally control this with a single javascript variable by setting.

```js
PrimeFaces.hideOverlaysOnViewportChange = false;
```

That will disable the default behavior. To use this right now on OverlayPanel just add this MonkeyPatch:

```js
if (PrimeFaces.widget.OverlayPanel) {
    PrimeFaces.widget.OverlayPanel.prototype.handleViewportChange = function() {
        if (PrimeFaces.env.mobile || PrimeFaces.hideOverlaysOnViewportChange === false) {
            this.align(this.target);
        } else {
            this.hide();
        }
    }
}
```


Or use this MonkeyPatch just to make your OverlayPanel's always behave like this and you don't care about the setting.

```js
if (PrimeFaces.widget.OverlayPanel) {
    PrimeFaces.widget.OverlayPanel.prototype.handleViewportChange = function() {
        this.align(this.target);
    }
}
```

**Comment by arunvc** [comment]
check megamenu  http://www.primefaces.org/showcase/ui/menu/megaMenu.xhtml
here we can open and scroll 
on clicking outside megamenu closes the megamenu

where as PrimeFaces.hideOverlaysOnViewportChange = false; 
clicking outside the overlay does not close the overlay
