### ISSUE TITLE
DataScroller: Loader feature breaks component when used with AutoUpdate

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#10084]
### Describe the bug

The problem appears when using a DataScroller component inside another component "autoupdated" using the `<p:autoUpdate />` tag. 
When the number of datas exceed the "chunkSize" attribute, and you use the "loader" facet with a "more" commandButton inside, after click the DataScroller is misregenerated. Only the new `<li>` markups are shown, the `<ul>` and the loader `<button>` are not there.

Add the `ignoteAutoUpdate="true"` on `<p:commandButton />` has no effect here.

### Reproducer

[pf-datascroller-autoupdate.zip](https://github.com/primefaces/primefaces/files/11383136/pf-datascroller-autoupdate.zip)

Click on the "more" button and see the HTML result.

Before It looks like this : 
![datascroller_autoupdate_1](https://user-images.githubusercontent.com/26894018/235942704-e4e3a699-b8fe-4467-93b3-5ef564d301f7.png)

After like this : 
![datascroller_autoupdate_2](https://user-images.githubusercontent.com/26894018/235942803-57bc13da-8715-4f1d-b200-03aaba5e83a5.png)

I think it can also be reproduced with the showcase example when adding the `<p:autoUpdate />` tag inside the form.

### Expected behavior

Show the DataScroller with all expected datas when used inside an autoupdated component.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.3 and 13.0.0-SNAPSHOT

### Theme

All

### JSF implementation

Mojarra

### JSF version

2.3 and 4.0

### Java version

11

### Browser(s)

All

**Comment by melloware** [comment]
Confirmed.  Made the same fix that AutoComplete and some other components have that do this lazy loading.

**Comment by melloware** [comment]
MonkeyPatch:

```js
if (PrimeFaces.widget.DataScroller) {
    PrimeFaces.widget.DataScroller.prototype.load = function() {
        this.loading = true;
        this.cfg.offset += (this.cfg.chunkSize * (this.cfg.startAtBottom ? -1 : 1));

        this.loadStatus.appendTo(this.loaderContainer);
        if (this.loadTrigger) {
            this.loadTrigger.hide();
        }

        var $this = this,
            options = {
                source: this.id,
                process: this.id,
                update: this.id,
                global: false,
                ignoreAutoUpdate: true,
                params: [{
                    name: this.id + '_load',
                    value: true
                }, {
                    name: this.id + '_offset',
                    value: this.cfg.offset
                }],
                onsuccess: function(responseXML, status, xhr) {
                    PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
                        widget: $this,
                        handle: function(content) {
                            this.updateData(content, false, $this.cfg.startAtBottom);
                        }
                    });

                    return true;
                },
                oncomplete: function() {
                    if ($this.cfg.offset < 0) {
                        $this.cfg.offset = 0;
                    }

                    $this.loading = false;
                    $this.allLoaded = ($this.cfg.startAtBottom) ? $this.cfg.offset == 0 : ($this.cfg.offset + $this.cfg.chunkSize) >= $this.cfg.totalSize;

                    $this.loadStatus.remove();

                    if ($this.loadTrigger && !$this.allLoaded) {
                        $this.loadTrigger.show();
                    }
                }
            };

        if (this.hasBehavior('load')) {
            this.callBehavior('load', options);
        } else {
            PrimeFaces.ajax.Request.handle(options);
        }
    }
}
```

**Comment by brivalin** [comment]
I added your patch and It works like a charm. Thank you !
