### ISSUE TITLE
Timeline: Request clustering of items 

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#10083]
### Description

I'd like to be able to use timeline clustering like vis.js timeline can 

example https://codepen.io/philhendry/pen/qBJVOwa

### Describe the solution you would like

to be able to turn clustering on and set which groups it should apply to or not apply to

**Comment by melloware** [comment]
For now you can use the Extender functionality to add clustering to your current timeline: https://primefaces.github.io/primefaces/12_0_0/#/components/timeline?id=extender

**Comment by philpil** [comment]
Hi Melloware, 

the workaround is working, is there a way to only cluster in a select group and not all groups?

regards,
Phil

**Comment by melloware** [comment]
I would check the vis timeline docs.  I am not sure it's possible.

**Comment by melloware** [comment]
I am going to close this issue as it doesn't seem worth trying to make this JSF properties when its really custom Extender functionality
