### ISSUE TITLE
DataTable: with selection multiple and filtered

### ISSUE THREAD

**Issue by ivasanpag** [primefaces/primefaces#10091]
### Describe the bug

I have a data table with selection multiple (including a column with selectionMode="multiple") and filtering. I have detected that if I filter the rows from the data table and use the checkbox from the column header to select all the current filtered data, the data table is selecting all the data (filtered and not)

### Reproducer

[pf-datatable-filteredselectionissue.zip](https://github.com/primefaces/primefaces/files/11418852/pf-datatable-filteredselectionissue.zip)

### Expected behavior

I think that the expected behavior would be that the data table selects only the filtered data.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

8

**Comment by Rapster** [comment]
Did you try with the latest snapshot? I believe we have ITs that cover that scenario

**Comment by melloware** [comment]
OK this is still an issue in 13.0.0-SNAPSHOT

**Comment by Rapster** [comment]
Ok, I set the milestone for 13.0.0 , it's important to have this fixed

**Comment by ivasanpag** [comment]
Sorry for the late response. I reproduced the issue with 11.0.0, 12.0.0 and 13.0.0-SNAPSHOT. 
The reproducer attached to the ticket has been tested with the 13.0.0-SNAPSHOT

**Comment by melloware** [comment]
@Rapster does this go back to the ordering of the features getting applied?

**Comment by Rapster** [comment]
It crossed my mind, but did we have that in the past?

**Comment by melloware** [comment]
Yes I think in the past the features were store in a list and executed in order they were in the list and I think the list order had meaning if I remember?

**Comment by Rapster** [comment]
That's good to know, then I might have created a regression 😅 But that's not the reason of this issue 😉

**Comment by melloware** [comment]
OK! I would say fix it the right way we should not try and count on order anyway.

**Comment by Rapster** [comment]
I had a closer look at few ITs, and based on coments "selection must not be lost after filter and update" and  current impl of `SelectionFeature#decode`: it seems that current behavior is by design: selection ignores filter. This is not very intuitive tbh.. But it seems users have been happy with this for a long time, there are three ways to go about this:
- change the current behavior?  Don't think it's the right approach
- introducing a new attribute?
- users override the SelectionFeature with something like https://github.com/Rapster/primefaces/commit/ae367ea2ea6415342b0f3820d6455b4c57ee80d1

**Comment by melloware** [comment]
I would say leave the current behavior it's been the default for years but maybe a new attribute that does the new behavior?

**Comment by Rapster** [comment]
I introduced a new attribute: `toggleSelectFilteredOnly`. I wasn't very inspired for the name, so if you have better suggestions I'm all ears 😄

**Comment by melloware** [comment]
@Rapster so it lines up with other selection related attributes how about `selectionFilteredOnly` that way it is similar to `selectionPageOnly` ?

**Comment by Rapster** [comment]
I thought about it too, but it's really about toggleSelect... If I don't mention toggle it can be confusing, `selectionToggleFilteredOnly ` isn't really great either, is it?

**Comment by stolp** [comment]
`selectFilteredOnlyToggle` is clearer I think. Even `selectFilteredOnly` may be enough, as the boolean type implies a toggle.

**Comment by tandraschko** [comment]
+1 for selectFilteredOnly
Exact, short and clear

**Comment by Rapster** [comment]
My last suggestion, what about `selectAllFilteredOnly`? (The joy of naming things...)
