### ISSUE TITLE
TabView: dynamic="true" child rendered twice

### ISSUE THREAD

**Issue by bjornerikolsen** [primefaces/primefaces#10099]
### Describe the bug

In TabView when setting dynamic="true" child is rendered twice. So tab content is rendered twice. This is causing performance issue with tabs.
Issue introduced with :
https://github.com/primefaces/primefaces/issues/9168

org.primefaces.component.api.UITabPanel#visitTree doesnt handle VisitResult.REJECT in the !isRepeating() case
similar issue fixed for UIData

https://github.com/primefaces/primefaces/issues/9171

https://github.com/primefaces/primefaces/pull/9361
https://github.com/primefaces/primefaces/pull/9191

### Reproducer

<p:tabView id="tabPanel"  dynamic="true" >

### Expected behavior

Tab content to be renderend once.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
@bjornerikolsen  a PR would be welcome!

**Comment by melloware** [comment]
@bjornerikolsen any update on this? I would like to get this into 13.0 final release.

**Comment by bjornerikolsen** [comment]
I have not been able to create a reproducer yet. If anyone else would have a look please do.

**Comment by melloware** [comment]
@tandraschko since this fix is just like how we use it other places in the code and the PR makes sense should we merge it or no for 13.0.0?

**Comment by tandraschko** [comment]
I would like to have a reproducer for it and then we should add a Integration test based on it
Do we already have other tabview Tests?

**Comment by melloware** [comment]
We do have  TabView IT's but I don't understand how he is detected "child is rendered twice" unless he has debug logs in his code that gets called when the Tabview is called? Or how to check for it being called twice in an IT?

**Comment by melloware** [comment]
Attaching this because i need a place to put it: 
[jakarta-tabchange.zip](https://github.com/primefaces/primefaces/files/11653003/jakarta-tabchange.zip)


Going to put https://forum.primefaces.org/viewtopic.php?p=210241#p210241 to rest once and for all.

**Comment by tandraschko** [comment]
you wont rest it :D
he doesnt read his logs, doesnt understand the errors/ear and he will blame PF again soon.
