### ISSUE TITLE
Cannot display faces messages bound to iterated elements with p:dataTable

### ISSUE THREAD

**Issue by kalgon** [primefaces/primefaces#1010]
When using a `p:dataTable` (PF 5.3) like this:

```
<p:dataTable values="..." var="..." id="current">
    ...
    <h:messages for="current" />
```

No messages will be displayed for `current` although I do have faces messages attached to client ids (current:0, current:1...). However, messages for sub-components (current:0:property) can be displayed.

When rewriting the same example with `h:dataTable` or `ui:repeat`, all messages can be displayed.

More details on [stackoverflow](http://stackoverflow.com/questions/34681454/displaying-faces-messages-bound-to-elements-being-iterated-by-pdatatable).

If needed, I can provide a complete example.

**Comment by kukel** [comment]
please do create an ['mcve'](http://stackoverflow.com/help/mcve) according to StackOverflow guidelines

**Comment by kalgon** [comment]
there you are: [primefaces-issue-1010.zip](https://github.com/primefaces/primefaces/files/85756/primefaces-issue-1010.zip) (just run mvn to start a tomcat7)

**Comment by kukel** [comment]
This is **not** an mcve... 4 classes? A composite component? Are they all needed to reproduce the problem?

**Comment by kalgon** [comment]
Sorry, I just wanted to demonstrate that displaying error messages was working at every level excepted on the iterated element in `p:dataTable`, I've stripped down my example to the bare minimum but it's less obvious to see what's wrong: [primefaces-issue-1010.2.zip](https://github.com/primefaces/primefaces/files/88543/primefaces-issue-1010.2.zip)

**Comment by kalgon** [comment]
I am also trying to edit each row by opening a `<p:dialog>`. When I click save in my dialog, I close the dialog and try to re-render the original row in my table (`<f:ajax ... render=":myform:lines:#{myBean.selectedIndex}" />`) but that does not work. I can however re-render, the whole table (myform:lines) or subcomponents (myform:lines:#{myBean.selectedIndex}:myproperty). Do you think it is related to the same problem? I think that, while iterating on a dataTable, no component with client id 'currentVar:{index}' is being created. That would explain why I can't display error messages bound to that client id and why I can't re-render a specific row.

**Comment by tandraschko** [comment]
Thats actually expected.
messages are attached to components and a datatable:0 is not an component.

in PrimeFaces we enhanced this that it's possible to attach messages to someRandomStringKey. However this does only work for p:messages, not p:message.

This will work for you case:
`        <p:dataTable value="#{myBean.items}" var="item" id="items" rowIndexVar="index">
            <p:column>
                There should be an error message here: <p:messages for="items:#{index}" forType="key"  />
            </p:column>
        </p:dataTable>`
