### ISSUE TITLE
graphicImage: Resource ELResolver creates wrong path in Jakarta version

### ISSUE THREAD

**Issue by jthalmai** [primefaces/primefaces#10104]
### Describe the bug

We recently upgraded Wildfly from 26 to 28 and with it to Jakarta EE 10 and for this also switched to the jakarta jar of PrimeFaces.
There is an issue when using the Resource ElResolver in the value of a p:graphicImage, e.g.:

`<p:graphicImage value="#{resource['my_icon.png']}"/>`

In the old non-jakarta version this would create an img like:

`<img id="j_idt5:j_idt10" src="/ws/javax.faces.resource/my_icon.png.xhtml?pfdrid_c=true" alt="">`

But the jakarta version creates the 'src' path wrong:

`/ws/ws/jakarta.faces.resource/my_icon.png.xhtml?pfdrid_c=true`

The context path is added twice (/ws in this case) and so the result does not work.
With an h:graphicImage it works in both cases, so probably not an issue of JSF.

### Expected behavior

The context path should not be added twice.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.10-jakarta

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by tandraschko** [comment]
Can you try a snapshot from master?
We fixed similar tickets: https://github.com/primefaces/primefaces/issues/9452

otherwise we need a reproducer (primefaces-test)

**Comment by jthalmai** [comment]
Thanks for the quick answer. Yes, that seems to be the same issue.
