### ISSUE TITLE
Timeline: tooltipDelay - not applying delay on first call

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#10103]
### Describe the bug

tooltipDelay works for every item hovered after the first item.

However when hovering over an item for the first time the delay is ignored and tooltip displays instantly

### Expected behavior

delay works as specified all times

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
@philpil can you please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

Is this a PF tooltip?  Is this a Timeline only issue?   We need to see your code to see exactly whose problem it might be.

**Comment by melloware** [comment]
oh most likely its a Vis Timeline issue and not a PF issue.

I would open a ticket with a simple timeline reproducer here: https://github.com/visjs/vis-timeline/issues
