### ISSUE TITLE
Tree drag drop not working correctly in IE-11 and Edge (v5.3.4)

### ISSUE THREAD

**Issue by cchet** [primefaces/primefaces#1011]
A tree node can only be dropped as a neighbor and not as a child no matter which value the dropRestrict attribute has. This occurs in IE-11 and Edge. The strange thing is that the showcase example works. So I have implemented an maven based example web app eclipse project which runs on tomcat with myfaces-2.1.17 and primefaces-5.3.4 which should be the same as the showcase regarding the version 

displayed on the page end. 
This example implements the showcase example.

We got this version from our primefaces PRO account.

**I tried to attach the sample as a zip but seems not work. It tells me always that file type is not allowed. So please tell me how I'm able to provide this sample.**
_Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP._

I tried to login on Jira with our PRO account which we use to download the PRO releases, but it didn't work. Maybe I'm missing something?

**Comment by cchet** [comment]
The related primefaces forum post
http://forum.primefaces.org/viewtopic.php?f=3&t=44202&p=0&e=0&sid=34fc1976b00f505485553ce34e45e6e4

**Comment by kukel** [comment]
Create a an [mcve](http://stackoverflow.com/help/mcve) and post that in the **forum**. For an mcve see also [this](http://www.stackoverflow.com/tags/jsf/info). Please delete this 'issue' then.

**Comment by cchet** [comment]
Sorry my mistake.
Its just an Elite account not a PRO.
Haven't had problems for a while :)

I don't see any possibility to upload the sample app in the forum.

**Comment by cchet** [comment]
Here a link to a sample app hosted by github.
https://github.com/Curecomp/primefaces-issues/tree/master/5.4.3/tree_drag_drop_ie

Have just tested it with primeface-5.4.5 and got the same result, so still not working.

**Comment by cchet** [comment]
Has anyone tried the sample ?

**Comment by melloware** [comment]
@cchet safe to close this ticket as this issue appears to be fixed in PF 6.0 or higher?

**Comment by cchet** [comment]
Yes, I think can be closed
