### ISSUE TITLE
InputNumber: change event not working in combination with slider

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#10122]
### Describe the bug

Using a slider to manipulate an InputNumber doesn't fire a change event anymore. Note that this only applies to dragging the slider, clicking the slider works

Bisected this and the bad commit appears to be https://github.com/primefaces/primefaces/commit/8c33ded0e440bfd9d277a19bb429e5602d16667e, reverting it makes InputNumbers work with sliders again

### Reproducer

```xhtml
            <p:slider for="num" minValue="1" maxValue="10"/>
            <p:inputNumber id="num" value="#{testController.value}">
                <p:ajax update="output"/>
            </p:inputNumber>

            <h:outputText id="output" value="Value is: #{testController.value}"/>
```

Full reproducer:
[pf-inputnumber-slider.zip](https://github.com/primefaces/primefaces/files/11463826/pf-inputnumber-slider.zip)

Steps to reproduce
- Simply drag the slider around

### Expected behavior

When the slider is let go InputNumber's change event gets fired

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Yep but that fix was needed for: https://github.com/primefaces/primefaces/issues/10046

Can you debug?  Basically the only change there is checking old value and new value and not firing the change event.  So that tells me they are still identical or its a timing issue?

**Comment by melloware** [comment]
The slider.js has this code it it to notify the InputNumber.

```js
if (this.input.parent().hasClass('ui-inputnumber')) {
            this.input.parent().find('input:hidden').off('input.slider').on('input.slider', function() {
                $this.setValue($(this).val());
            });
        }
```

**Comment by melloware** [comment]
I have a PR with a fix that is working but letting the IT tests run now.

**Comment by jungm** [comment]
Thanks a lot for the fix @melloware, confirmed it works on both my reproducer and in our real app

**Comment by melloware** [comment]
Thanks for confirming!
