### ISSUE TITLE
Clientside logging: Log all levels to console

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#10136]
### Description

currently only `PrimeFaces.warn(log)` and `PrimeFaces.error(log)` log the messages to the console, `PrimeFaces.info(log)` and `PrimeFaces.debug(log)` do not

### Describe the solution you would like

all levels should log the console when ProjectStage=Development

### Additional context

imho it'd make it easier to understand what is going on without needing a `p:log` component for debugging

or am I missing something here that'd make logging `info` and `debug` levels to console a bad idea?

**Comment by melloware** [comment]
Nope feel free to submit a PR.  I personally don;t see why in Development we wouldn't log all console levels.

**Comment by tandraschko** [comment]
+1

**Comment by melloware** [comment]
I submitted a PR it was easy.
