### ISSUE TITLE
SplitButton: RowSelect of TreeTable is triggered

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#10157]
### Describe the bug

`SplitButtonRenderer#encodeMenuIcon` [has hardcoded style classes](https://github.com/primefaces/primefaces/blob/e95160b1ae8f55c61d41da32c6aadad0e687ef60/primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java#L204) for the menu icon which is missing `ui-c`.

I did not find any reference on why this marker style class was introduced, but it seems to be used by the tree table to exclude `span` elements from triggering the row selection feature.

Maybe use `HTML.BUTTON_LEFT_ICON_CLASS`?

### PrimeFaces edition

Community

### PrimeFaces version

master

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

**Comment by melloware** [comment]
Yep agreed!
