### ISSUE TITLE
DatePicker: change event called twice with mask="true"

### ISSUE THREAD

**Issue by pm2013** [primefaces/primefaces#10155]
### Describe the bug

It happens only at first click on callendar.

First event is called with null value.
Second with entered value.
At first call listener get the wrong null value.

`<p:datePicker id="test_date" mask="true" pattern = "MM/dd/yy">
                <p:ajax event="change"/>
</p:datePicker>`

In listener method, the value is set in second call.
Result from p:log

19.05.2023, 17:14:05 : Initiating ajax request.
19.05.2023, 17:14:05 : Form to post test_form.
19.05.2023, 17:14:05 : URL to post /Alarms24/new_document.xhtml.
19.05.2023, 17:14:05 : Post Data:javax.faces.partial.ajax=true&javax.faces.source=test_form%3Atest_date&javax.faces.partial.execute=test_form%3Atest_date&javax.faces.behavior.event=change&javax.faces.partial.event=change&test_form%3Atest_date_input=&javax.faces.ViewState=M0JFMUUyRUM5OTYzMTRBRTAwMDAwMDI2
19.05.2023, 17:14:05 : Response received successfully.
19.05.2023, 17:14:05 : DOM is updated.
19.05.2023, 17:14:05 : Response completed.
19.05.2023, 17:14:05 : Initiating ajax request.
19.05.2023, 17:14:05 : Form to post test_form.
19.05.2023, 17:14:05 : URL to post /Alarms24/new_document.xhtml.
19.05.2023, 17:14:05 : Post Data:javax.faces.partial.ajax=true&javax.faces.source=test_form%3Atest_date&javax.faces.partial.execute=test_form%3Atest_date&javax.faces.behavior.event=change&javax.faces.partial.event=change&test_form%3Atest_date_input=05%2F31%2F23&javax.faces.ViewState=M0JFMUUyRUM5OTYzMTRBRTAwMDAwMDI2
19.05.2023, 17:14:05 : Response received successfully.
19.05.2023, 17:14:05 : DOM is updated.
19.05.2023, 17:14:05 : Response completed.

How the listener can realize, that first the event is wrong?

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4

### Theme

Serenity

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

Open JDK 18.9

### Browser(s)

Firefox, Safari

**Comment by melloware** [comment]
Did you try 13.0.0-SNAPSHOT I believe this is already fixed with this fix: https://github.com/primefaces/primefaces/issues/9259

**Comment by melloware** [comment]
There is also a workaround in that ticket for 12.0.4 if you follow that thread I provided a working MonkeyPatch.
