### ISSUE TITLE
HeadRenderer: Client side localization fails for missing localization

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#10150]
### Describe the bug

Exception is thrown by [encodeJS](https://github.com/primefaces/primefaces/blob/10b13d49a1e79f9ea53124839c324ce8499f58cc/primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java#L175) when a localization resource is missing.

### Reproducer

Set a locale that is not provided. See [META-INF/resources/primefaces/locales](https://github.com/primefaces/primefaces/tree/10b13d49a1e79f9ea53124839c324ce8499f58cc/primefaces/src/main/resources/META-INF/resources/primefaces/locales)

### Expected behavior

Maybe [encodeBegin](https://github.com/primefaces/primefaces/blob/10b13d49a1e79f9ea53124839c324ce8499f58cc/primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java#L130) should retry with a default locale. Or skip throwing the exception if a default locale is already provided in JavaScript.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

11

**Comment by melloware** [comment]
Hmmm but why are you passing it a locale you don't have?  I think this is the correct Exception to be thrown if a requested resource is not found?

EncodeJS won't know a Locale JS is already set when this code executes.

it only fires if ClientSideLocalization is enabled.

```java
if (applicationContext.getConfig().isClientSideLocalizationEnabled()) {
            Locale locale = LocaleUtils.getCurrentLocale(context);
            encodeJS(context, LIBRARY, "locales/locale-" + locale.getLanguage() + ".js");
        }
```

So don't enable that if you know someone is using a locale that does not have a client side locale.  Just set.

```xml
<context-param>
    <param-name>primefaces.CLIENT_SIDE_LOCALISATION</param-name>
    <param-value>false</param-value>
</context-param>
```

**Comment by melloware** [comment]
Also as a side note which locale are you using that is missing and can we add it?

**Comment by mihaiDumea** [comment]
If I want switch between several locales, do I have the option to use the provided/embedded locales and to add/link only the missing ones? Seems like not. Either I have to provide all the used locales or used the embedded ones. But I cant merge them. I can still overwrite the embedded ones.
I doesn't have yet the translated locale.

**Comment by melloware** [comment]
you should be able to.  So say you have a custom locale called "locale-zz.js"  If you put it in your WAR file in this location...

`\src\main\webapp\resources\primefaces\locales\locale-zz.js`

That will resolve it like it came from the PrimeFaces location and just work.

**Comment by mihaiDumea** [comment]
It's a fine workaround, thanks! But if it needs to be fixed, a proper solution is needed.

**Comment by melloware** [comment]
your proper solution is this.

```xml
<context-param>
    <param-name>primefaces.CLIENT_SIDE_LOCALISATION</param-name>
    <param-value>false</param-value>
</context-param>
```

Don't use this feature and just control the language yourself in the template.

```xml
<h:outputScript name="locales/locale-#{app.locale.language}.js" library="primefaces"/>
```

**Comment by melloware** [comment]
OK decided just to log a warning and move on.  It will not try any fallback as English is already the fallback.

**Comment by mihaiDumea** [comment]
Indeed! Much appreciated!
