### ISSUE TITLE
SelectManyCheckbox : checkbox not refreshes after spacebar select

### ISSUE THREAD

**Issue by BasakDm** [primefaces/primefaces#10166]
### Describe the bug

When you move through the boxes using the keyboard and check the checkbox with the space bar, it does not updates. 
You can easily reproduce it here:

http://www.primefaces.org:8080/showcase/ui/input/manyCheckbox.xhtml?jfwid=66c8c

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

17

**Comment by jepsar** [comment]
What happend with this milestone? Should it be 13 RC2?

**Comment by melloware** [comment]
I updated.  I took a look at this one and it is quite confusing.  The spacebar triggers the checkbox to be activated but its just not styled that way.  When I tried to add a keyboard handler to add the styling on SPACE it then was making the checkbox display the opposite of its state so checked meant unchekced etc.  It is really bizarre.  Maybe you can take a look?

**Comment by melloware** [comment]
OK was able to get to the bottom of it an fix it.
