### ISSUE TITLE
DataTable stickyHeader not refreshing when sorting or filtering

### ISSUE THREAD

**Issue by lwojtysiak** [primefaces/primefaces#1016]
When p:dataTable with stickyHeader="true" is sorted of filtered by the user, the sticky header is not refreshed properly.

It shows new sorting column, but still shows old column as "active" and with one arrow (not two). 
In the same time original header looses all information about sorting (all columns aren't 'active', all has two arrows).

**Comment by kukel** [comment]
PF version? Example in mcve format?

**Comment by alexandru-bitlan** [comment]
I have the same issue in my web application.
In the end I threw stickyHeader="true" away.

Primefaces 5.3 in my case.

**Comment by mertsincan** [comment]
Please try with 5.2.19+, 5.3.6+ or 6.0.
Issue: #1070
