### ISSUE TITLE
SplitButton: Improve position of menu panel

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#10167]
### Description

If `collision: 'flipfit'` kicks in, the position of the menu panel is not correct, in my opinion.
![Screenshot](https://github.com/primefaces/primefaces/assets/3531183/a96feca2-fcda-4ccb-aa2a-b622c6987fe4)

### Describe the solution you would like

The relative element is set to [`of: this.button`](https://github.com/primefaces/primefaces/blob/4f73029e898ff15401cbd7c583be1ae3b7bd6a6a/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js#LL581C27-L581C33), which is the main action of the split button. Better would be `of: this.jq` which then should align the menu panel correctly on the left (on collision: on the right) side of the whole split button.

WDYT?

**Comment by melloware** [comment]
As long as it looks good in the normal use case like on the showcase in the middle of a page I am OK with this change.

**Comment by melloware** [comment]
@jepsar any thoughts on this?

**Comment by jepsar** [comment]
I would need to check if that will work with the OverlayPanel that was added.

**Comment by fanste** [comment]
I've preparend a commit on my fork which I can PR anytime: https://github.com/fanste/primefaces/tree/patch-10167

**Comment by fanste** [comment]
I currently do not have the possibility to build the latest SNAPSHOT to test that feature. It's a bit time consuming on this infrastructure, to get it working...

But from the [javascript code of OverlayPanel](https://github.com/primefaces/primefaces/commit/7132c154dc53ae6cab94410888a7fa55b2170b37#diff-934808a3e04660414627bdf8551237fd0481990d398599a398601d5b6053794fR409): The problem should not exist, as the parent of `.ui-splitbutton-menubutton` is `.ui-splitbutton` which equals `this.jq`.


But I'm a bit confused about the [java code](https://github.com/primefaces/primefaces/commit/7132c154dc53ae6cab94410888a7fa55b2170b37#diff-f936b5ccffcadda5170b09e6fb2e93fccfd902e398c024782dbed31be2853525R110-R117): This renderes the menu of the split button itself (potentially just an empty panel) AND the overlay panel. Do I miss something?

**Comment by melloware** [comment]
Tested it in all scenarios and it works great.
