### ISSUE TITLE
DatePicker: incorrect month selection from Navigator popup

### ISSUE THREAD

**Issue by radinovic** [primefaces/primefaces#10172]
Description:

Wrong month is selected when originally set date has month with 31st day set, and after initial selection next selected month in single-select list has less than 31 days.

Steps for reproduction of the issue with incorrect month selection are following:

- Select/set date 31st day of some month in navigator popup (31.12.2023 for instance).
- Click on Calendar button and within the calendar select month which doesn't have 31 days (February, April, June, September or November) in single-select list control for month selection.
- Instead of selected month, month which comes after selected month is selected in Calendar control. For example, if you select April, May will be selected. If you repeat selection, everything works as expected.

PrimeFaces version: any.

## Reproducer
[pf-10172.zip](https://github.com/primefaces/primefaces/files/11574926/pf-10172.zip)

**Comment by melloware** [comment]
I was able to reproduce in 13.x and attached a reproducer to the ticket.

**Comment by melloware** [comment]
Here is a MonkeyPatch you can add that fixes it right now.

```js
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.onMonthDropdownChange = function(event) {
        var newViewDate = new Date(this.viewDate.getTime());
        newViewDate.setDate(1); //always set to first of month
        newViewDate.setMonth(parseInt(event.target.value, 10));

        if (this.options.onMonthChange) {
            this.options.onMonthChange.call(this, newViewDate.getMonth() + 1, newViewDate.getFullYear());
        }
        this.updateViewDate(event, newViewDate);
    };
};
```
