### ISSUE TITLE
FileUpload: not compatible with jakarta and commons-fileupload

### ISSUE THREAD

**Issue by jramirezviera** [primefaces/primefaces#10177]
### Describe the bug

the package for jakarta (use jakarta package instead of javax) still depends on commons-fileupload, an ther is no version for commons-fileupload which use jakarta packages.

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

jakarta.faces/4.0

### Java version

>11

**Comment by Rapster** [comment]
>  an ther is no version for commons-fileupload which use jakarta packages.

Then it's not a PF issue

Besides that, not sure why you still want to use commons-fileupload in faces 4.0

**Comment by melloware** [comment]
Yes for Jakarta you should be using Native uploading and not using Commons at all. It's only needed really for JSF 2.2 and lower that did not support Native uploading.

**Comment by Rapster** [comment]
Didn't we consider to deprecate the usage of commons-upload somewhere?

**Comment by melloware** [comment]
I think as long as we support JSF 2.2 still we need it. I would love to make 14.0.0 JSF 2.3+.   But that is just my two cents.

**Comment by Rapster** [comment]
Indeed that would be great

**Comment by tandraschko** [comment]
In general native upload should not depend on JSF version, only on Servet version.

And still supporting JSF 2.2 is zero effort. I would do only a cut when we fully switch to Jakarta in the future.

**Comment by lagar84** [comment]
I don't know if commons-fileupload is needed on different scenarios, but JSF 2.2 has `h:inputFile`  (indeed, it was introduced in 2.2) : https://arjan-tijms.omnifaces.org/p/jsf-22.html#802

**Comment by melloware** [comment]
I think the only issue we can't fix by staying on 2.2 is this one: https://github.com/primefaces/primefaces/issues/9518

**Comment by jramirezviera** [comment]
Sorry for the delay in answering. 

I've been analizing the code an I still think that the dependency is mandatory. In PF12 code there is a dependency in FileUploadFilter, the "createFileItemFactory" method instantiate a DiskFileItemFactory (org.apache.commons.fileupload.FileItemFactory)

![imagen](https://github.com/primefaces/primefaces/assets/134746154/39089935-35aa-45a1-b696-0588532a2bee)

this are the import:
![imagen](https://github.com/primefaces/primefaces/assets/134746154/ccbb01f9-ae17-4942-9dd8-af4cb57f184f)


So, you must have this classes, althoug you have configure the filter as "native".  If I ommimt the dependecy mi jetty server chash on startup because it doesn't find the class

**Comment by melloware** [comment]
@jramirezviera but that class should not EVEN be loaded at all unless you still have it configured accidentally in your web.xml ??

See:  https://primefaces.github.io/primefaces/12_0_0/#/components/fileupload?id=filter-configuration

Jetty should NOT be loading `org.primefaces.webapp.filter.FileUploadFilter` at all unless its declared in your `web.xml` no?

**Comment by melloware** [comment]
Nice!!!
