### ISSUE TITLE
UltimaMenu: Doesn't set the active menuitem properly

### ISSUE THREAD

**Issue by KonradEichstaedt** [primefaces/primefaces#10197]
### Describe the bug

Iam using Primefaces 12.0.3 and Ultima Theme 5.0.0. I integrated an pu:menu und p:menuitems like this: 

`<pu:menu widgetVar="mainmenuwidget" id="maninnavigationmenu" stateful="true">
                        <ui:param name="currentAction"
                                  value="/dashboard.xhtml"/>
                        <p:menuitem immediate="true" id="menuitemdashboard" value="#{msg.nav_dashboard}" icon="pi pi-home"
                                    disabled="#{not currentRight}"
                                    styleClass="active"
                                    outcome="#{kODRechte.getAllowedAction(currentAction, currentRight)}"/>`

But the state of the active isn't not visible on the page. I can't find any state information within the cookie local browser storage. Can you please help and let me know how I can set the active menu item? 

Many Thanks, 

### PrimeFaces edition

Community

### PrimeFaces version

12.0.3

### Theme

Ultima

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

### Browser(s)

Chrome

**Comment by tandraschko** [comment]
pu:menu is from ultima?
then please use the ultima forum, this issue tracker is just for primefaces core

**Comment by jepsar** [comment]
Yes, please use https://forum.primefaces.org/viewforum.php?f=42
