### ISSUE TITLE
Menu: toggleable=true is not expanded by default since 13.0.0-RC1

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#10199]
### Describe the bug

<p:menu toggleable="true"> submenus appears as non expanded by default, which is a breaking change from 12.0.0 (submenus are expanded by default).

I don't think this is really intended, but it could be. Seems related to https://github.com/primefaces/primefaces/commit/81869b646e7d117277ecc8ce9dcf9d260e100c3f and https://github.com/primefaces/primefaces/commit/6fa85ef8a3cc63e3d8a147e740bbb347b04a1855

To get the same behaviour in 13.0.0-RC1 expanded=true should be included in all submenus

### Reproducer

        <p:menu toggleable="false">
            <p:submenu label="Options" >
                <p:menuitem value="Save (Non-Ajax)" ajax="false"
                            icon="pi pi-save"/>
                <p:menuitem value="Update"  icon="pi pi-refresh"/>
                <p:menuitem value="Delete"  icon="pi pi-times"/>
            </p:submenu>
            <p:submenu label="Navigations">
                <p:menuitem value="Website" url="http://www.primefaces.org" icon="pi pi-external-link"/>
                <p:menuitem value="Internal" icon="pi pi-upload"/>
            </p:submenu>
        </p:menu>

### Expected behavior

Submenus are expanded by default, as in 12.0.0

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC1

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

17

**Comment by tandraschko** [comment]
expanded=false is the default since ever of p:submenu

p:menu just ignored always, thats what i fixed

so either we make expanded=true as default for all submenus of all menus, or we leave it as it is and add it to the migrationguide

**Comment by tandraschko** [comment]
ok, works as expected for me.
If you set toggleable=false, submenus cant' be expanded, so the are expanded per default
If you set toggleable=true, submenus can be expanded and p:sebmenu has expanded=false as default since ever, they are not expanded

i will add it to the migration guide
