### ISSUE TITLE
p:inputNumber with minValue resets when switching between tabs.

### ISSUE THREAD

**Issue by ashishreddy123** [primefaces/primefaces#1019]
I have a `<p:tabView>` on my screen where one of the tabs(`<p:tab>`) has several `<p:inputNumber>` elements with minimum value set to -9999999999.99. When I enter a value like -5643.76 or 5643.76 and switch between the tabs, the input resets to its initial value whereas if the `<p:inputNumber>` doesn't have the 'minValue' attribute set, it retains/doesn't reset the value even if I switch between the tabs.

I'm using jsf 2.1.9 and primefaces 5.3.4. My code for tabs is as shown below :

```
<p:tabView id="sections" style="width:inherit;background-color: #F0F0F0;">
    <p:ajax event="tabChange" listener="#{tabbedViewManagedBean.onTabChange}" />
    <p:ajax event="tabClose" listener="#{tabbedViewManagedBean.onTabClose}" />
    <p:tab title="First Tab" id="firsttab">
        <ui:include src="firsttab.xhtml" />
    </p:tab>
    <p:tab title="Second Tab" id="secondtab">
        <ui:include src="secondtab.xhtml" />
    </p:tab>
 </p:tabView>
```

The tabbed view managed bean gets data for that tab when switching between the tabs. Each tab has its own session scoped managed beans.

The code for secondtab.xhtml is :

```
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jstl/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions">

  <h:outputText value="Net Loss :" />
    <p:inputNumber value="#{secondTabMB.netLoss}" 
       symbol="$ " minValue="-99999999999999.99"/>
</ui:composition>
```

Update : I just noticed that it's not just this component but all the components other than inputText/outputText like the selectOneMenu, selectManyMenu, calendar don't trigger an onchange event that updates the attribute value in backing bean when value is changed in the field. So if i try something like this it works :

```
<p:inputNumber value="#{secondTabMB.netLoss}" 
       symbol="$ " minValue="-99999999999999.99">
   <p:ajax update="@this" />
</p:inputNumber>
```

**Comment by tandraschko** [comment]
Can't replicate with your example, sorry.
