### ISSUE TITLE
DataTable disabled selection can be bypassed with ShiftKey

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#102]
A datatable using the p:column selectionMode="multiple" and disabledSelection attribute has an issue where a row can be selected even though it is disabled. 

For example, I have a table that lists the administrative users of an application. I don't want a user to delete their own account so their row is disabled from selection. If you click on the select all checkbox it does not select the row that is disabled (as desired). If you click the individual row it does not select it (as desired). But if you press the Shift key and select rows it can be bypassed and the disabled row(s) are now selected.

We use this datatable setup on many pages for various reasons. Although adding server side validation to prevent actions solves the security issues, it would be nice if the Shift key selection respected the disabled rows.

**Comment by sudheerj** [comment]
I can't replicate the issue with latest PF 5.3 SNAPSHOT release

**Comment by cagataycivici** [comment]
Closing then.

**Comment by Charriu83** [comment]
Sorry to bring this old issue back, but I can reproduce this issue with Primefaces 6.0.x and 6.1.x. You can easily override *disabledSelection* with the SHIFT key.
