### ISSUE TITLE
BlockUI slows down the application

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#10207]
### Describe the bug

We noticed that our JSF application has become slower and slower while working with it. We found out that the problem lies in the processing of the 'alignOverlay' for BlockUI. Since PF12, BlockUI has been subscribed to all DOM update events so that it can be resized even if another DOM element has changed.

However, each time we update the component, the BlockUI is subscribed again, causing it to be processed by 'alignOverlay'. Our application performs much better with the old version of 'bindResizer', the one before [this fix](https://github.com/primefaces/primefaces/pull/9159/files).

### Reproducer

[primefaces-test-blockui-events.zip](https://github.com/primefaces/primefaces/files/11660741/primefaces-test-blockui-events.zip)
[blockui_test_case_github.patch](https://github.com/primefaces/primefaces/files/11660745/blockui_test_case_github.patch)

### Expected behavior

In the console we see each time we click the "reset" button a listener is added and there are more and more alignOverlay logs. Ths is, of course, not a problem for a simple small example, but it became relevant for complex applications.

### PrimeFaces edition

Community

### PrimeFaces version

since 12.0.0

### Theme

Babylon

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11-17

**Comment by melloware** [comment]
Great reproducer.  Can you try this one I monkeypatched your JS.
[pf-10207.zip](https://github.com/primefaces/primefaces/files/11664335/pf-10207.zip)

Can you let me know if this improves your performance?
