### ISSUE TITLE
DataTable: Filter usage modify the value object type

### ISSUE THREAD

**Issue by rsi21** [primefaces/primefaces#10209]
### Describe the bug

When using Datatable with the filter feature and using a ListDataModel for the datatable value, the value object is updated with a simple List<>.

A sample project as been created here to ilustrate the case:
https://github.com/rsi21/primefaces-test/tree/datatable_with_filter

The project displays only a simple datatable with sort on columns and a filter on a first column.
On each sort or filter the value type is displayed/updated using the binding feature of the datatable.

In resume, if you use sort feature, we can see that the value object type is not modified.
If we use the filter feature, then it is modified by a simple List<> object.

For information, also some exchanges has been made around the issue in the forum here:
https://forum.primefaces.org/viewtopic.php?f=3&t=81036

### Reproducer

https://github.com/rsi21/primefaces-test/tree/datatable_with_filter

### Expected behavior

Keep always the original object type in the datatable value.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.4

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by rsi21** [comment]
Hi,

For info i also make a test with release 13.0.0-RC1.
The problem is present but more weird:
- on first filter model is kept
- on second filter (changing the value of the filter loaded) then the value type is changed to array

And like in 12.0.4, if we remove the value of the filter, value type is restored.

Hope it helps.

**Comment by melloware** [comment]
Thanks for the reproducer.
