### ISSUE TITLE
Spinner: display initially as Button

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#10205]
### Description

Doing research for our ecommerce website we found a great looking combination of a button and spinner for the "add to cart" functionality at this german shop. 

**Button**

Initially when count is zero / item is not in cart it shows a button with a hover effect that changes the icon.
On click the item is added with quantity 1 to the cart, the button animates (slides) and it shows a spinner instead.

**Spinner**

When quantity is 1 the decrement icon changes to a trash can to remove it again and go back to displaying the initial button. Larger quantities show a minus sign. 
The plus is shown as green highlight and increments it as usual. Further the spinner has a tooltip after each action. 

With current _p:spinner_ the different class for up and on ajax update the icon change to a trash can is already possible.

**Live demo**

https://shop.rewe.de/p/coca-cola-12x1l/8002614

**Screenshots**

![spinnerbutton](https://github.com/primefaces/primefaces/assets/5265550/1f790700-7e10-43ef-aa60-0f575990e421)

### Describe the solution you would like

Not sure anymore (after writing this) if a primefaces feature is needed but wanted to share the concept.
I will try to rebuild it with _p:commandButton_ and _p:spinner_ and see how it works in our website.

**Comment by Rapster** [comment]
That sounds very specific, why not simply playing around with button and spinner rendered attributes using composite/facelet tag? Both are completely 2 different components so I don't see the point...

**Comment by jepsar** [comment]
I think you might even be able to create this with custom CSS.

**Comment by djmj** [comment]
Yes you guys are right its too specific. I will try it out.

**Comment by tandraschko** [comment]
+1
perfect case for a composite
