### ISSUE TITLE
DatePicker: showMonthAfterYear option does'nt working.

### ISSUE THREAD

**Issue by hirorisoon** [primefaces/primefaces#10222]
### Describe the bug

It happened when migrated from PF6.0.2 to PF10.0.0. 
We rewrote the p:calendar to p:datePicker, but the datePicker header was rendered month + year.
The locales option 'showMonthAfterYear' does not working.

<img width="330" alt="image" src="https://github.com/primefaces/primefaces/assets/48387691/e75000ce-afe7-4d8d-b9bc-ef1fea747a43">

I don't think this part is good (0-datePicker.js, line at 1421-) 
```js 
renderTitle: function (monthMetadata) { 
    var month = this.renderTitleMonthElement(monthMetadata.month, monthMetadata.index)
    , year = this.renderTitleYearElement(monthMetadata.year, monthMetadata.index); 
    return ( '<div class="ui-datepicker-title">' + month + year + '</div>' ); 
}, 
``` 

### Reproducer

Reproducer: https://github.com/hirorisoon/primefaces-test.git

1. Launch the above primefaces-test.
2. Check the datePicker behavior per language(selection).
   This page is not patched.
   In all language, the datePicker header is rendered 'month + year'.
4. Go to the patched page by link (to test2).
5. Check the datePicker behavior per language(selection).
   In 'ja' case only, the datePicker header is rendered 'year + month'.

<img width="332" alt="image" src="https://github.com/primefaces/primefaces/assets/48387691/27ed0a63-3686-41fa-9b5e-04b60c2bff5d">

### Expected behavior

When we set `showMonthAfterYear: true,`, the datePicker header is rendering year + month. 

I made a patch for our project: 
```js 
if (PrimeFaces.widget.DatePicker) { 
    $.prime.datePicker.prototype.renderTitle = function(monthMetadata) { 
        const month = this.renderTitleMonthElement(monthMetadata.month, monthMetadata.index); 
        const year = this.renderTitleYearElement(monthMetadata.year, monthMetadata.index); 
        let locale = PrimeFaces.settings.locale; 
        if (!locale) { 
            locale = 'ja'; 
        } 
        let ret = '<div class="ui-datepicker-title">'; 
        if (PrimeFaces.locales[locale].showMonthAfterYear) { 
            ret += year + month; 
        } else { 
            ret += month + year; 
        } 
        ret += '</div>'; 
        return ret; 
    } 
} 
```

I hope you to patch it in a style suitable for this project.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

Mojarra 2.2.x. 

### Java version

19.0.1

### Browser(s)

All

**Comment by melloware** [comment]
Thanks for the report I will look at this one.
