### ISSUE TITLE
SelectOneRadio: remove `plain` attribute

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#10227]
Introduced in: https://code.google.com/archive/p/primefaces/issues/4760

But I don't see the point. No other components have such an attribute and it makes code harder to maintain (for example #9857). Without plain, the component still is accessible (if not we can / should improve that), and it is fully styleable.

Maybe we can deprecate it in 13 and remove in 14? WDYT?

**Comment by melloware** [comment]
So my two cents...

1. This was added in 2012 probably because someone 11 years ago had this use case but to me this is not worth it now in 2023.
2. NONE of the other prime libraries allow this "plain" style.
3. I did not know of this feature until yesterday and I have been using PF since 2012.

My vote is to remove this feature.  If people want a plain unstyled radio button they can just use `<h:selectOneRadio` no?

**Comment by jepsar** [comment]
So, shall we deprecate in 13?

**Comment by melloware** [comment]
Lets get @tandraschko and @Rapster to weigh in.  Right now the votes are...

Mello +1
Stolp +1
Jepsar +1
Thomas ???
Rapster ???

**Comment by Rapster** [comment]
+1

**Comment by melloware** [comment]
@jepsar may as well put a PR in to remove it entirely so we can review?  If you are short on time I can do it if you need me to. Just let me know

**Comment by jepsar** [comment]
Sure, I can remove it (basically revert yesterdays PR, remove the attribute and mention in the migration guide). I can do it this evening.

**Comment by tandraschko** [comment]
Guys thats not cool
We agreed on deprecate first, even we are already in RC

We should revert it

**Comment by melloware** [comment]
Are you sure this is a feature that I can't imagine anyone uses and it actually causes us to have more code to maintain and the other Prime Libraries do not support this functionality NOR do any other PF components support "plain" mode.  This is specifically for radiobutton and users can just use `<h:selectOneRadio>` so to me this is a completely useless feature that should never have been in PF to begin with?

**Comment by jepsar** [comment]
I would be happy either way. Deprecating first seems more reasonable though. Let me know what to do.

**Comment by tandraschko** [comment]
i know at least one application is using it in the past

anyway: removing features should never happen in RC phase

**Comment by melloware** [comment]
Yep we did.  But will be removed in 14.0.0.  A lot of this from 2012 was probably to work around IE6 issues.   I feel like whenever we can't explain why something was done the answer is always "because of IE6".
