### ISSUE TITLE
DataExporter: new attribute to set BOM when uses type CSV and encoding UTF-8

### ISSUE THREAD

**Issue by raul810y** [primefaces/primefaces#10226]
### Description

When you export a CSV-file using the Datatable component and DataExporter, the resulting file is encoded with UTF-8 without a BOM and there's no way to change this, causing encoding issues with latin language (For example with characteres á, é, í, ó ú)

This is an encoding problem for example when users open CSV File with Excel (The most common alternative to open this kind of files).

Note: Other types of encoding do not solve the problem ()

Related posts: 
https://github.com/primefaces/primeng/issues/9172
https://mkyong.com/java/java-how-to-add-and-remove-bom-from-utf-8-file/

### Describe the solution you would like

Just exporting using UTF-8 is not enough. Users should be able to either change the encoding of the generated file or to add the BOM so the resulting CSV file is fully compatible with excel.

Something like this in DataTableCSVExporter class:

`
           
	        	
           @Override
	    public void doExport(FacesContext context, DataTable table, ExportConfiguration exportConfiguration, int index) throws IOException {
	        try (OutputStreamWriter osw = new OutputStreamWriter(getOutputStream(), exportConfiguration.getEncodingType());
	            PrintWriter writer = new PrintWriter(osw);) {                       
                    if (exportConfiguration.isBomRequired()) { // Add new attribute bomRequired
	        	      writer.write('\ufeff'); //write the UTF-8 BOM to make Excel able to detect UTF-8 encoding
                      }
     
                      ...
                      ...
                      ...
`

**Comment by melloware** [comment]
Thanks for the report.  Please review my PR.
