### ISSUE TITLE
Sticky: style broken after scrolling

### ISSUE THREAD

**Issue by mrclBIE** [primefaces/primefaces#1023]
Hey,

today i updates my primefaces version from 5.2 on 5.3. After a while I noticed, that my sticky panel has a problem. After I scroll down and up again, the sticky component was some pixels wider than before. I downgraded to 5.2 and it works correctly again.

I compare the html and css and saw the difference:
5.2: panel width is 320px before and same after scrolling
5.3: panel width is 320px before and auto after scrolling, so it fills my parent div.

So it seems like a bug for me...

Regards,
Marcel

**Comment by kukel** [comment]
Does not happen in the showcase... with toolbar, so please create an [mcve](http://stackoverflow.com/help/mcve)

**Comment by mrclBIE** [comment]
``` xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    lang="en">
<h:head>
    <title>PF 5.3 sticky Panel Test</title>

    <style>
        html, body {
            height: 100%;
        }
    </style>

</h:head>
<h:body style="margin:0;">

    <div style="position: relative; height: 100%; min-height: 100%; display:table; width: 100%;">
        <div style="height:100px;margin-bottom: 5px;"></div>

        <div style="display:table-row;height: 100%; ">
            <div style="position: relative;float: left;width: 325px;">
                <p:panel id="nav" header="Header" style="width: 320px;border:none;padding:0px;height:250px;">
                </p:panel>

                <p:sticky target="nav" margin="5" />
            </div>

            <div style="margin-left: 325px;position: relative;">
                <div style="width:100%;background:lightblue;height:1200px;"></div>
            </div>
        </div>
    </div>

</h:body>
</html>
```

**Comment by mrclBIE** [comment]
I hope this helps...
Tested with Chrome 47.0.2526.111 and 48.0.2564.82 , Firefox 43.0.4 and IE 11.0.9600.18163.

Regards,
Marcel

**Comment by mrclBIE** [comment]
Hey. Any news about it?

**Comment by abelet** [comment]
broken with 6.2 also

**Comment by melloware** [comment]
Looks like its this block of code in sticky.js that is setting the AUTO if its fixed.

```javascript
    restore: function() {
        if(this.fixed) {
            this.target.css({
                position: 'static',
                top: 'auto',
                width: 'auto'
            })
            .removeClass('ui-shadow ui-sticky');

            this.ghost.remove();
            this.fixed = false;
        }
    }
```

**Comment by abelet** [comment]
Is it possible to add a fix to a primefaces public release somehow? Sticky.js exist only in the sources, and I would not like to patch the components.js (which is located in primefaces.jar) to corret the bugs in this component.

**Comment by open-gdsn** [comment]
https://stackoverflow.com/questions/39639532/override-a-method-from-a-primefaces-specific-widget

 and 

https://stackoverflow.com/questions/36594082/monkeypatching-primefaces-widgets-extend-override 

and

https://stackoverflow.com/questions/27551493/how-do-i-find-and-or-override-javascript-in-primefaces-component-based-on-widget/27564325

**Comment by abelet** [comment]
In my case when the component became fixed on the top, it also became wider. It became as wide as its parent. After scrolling up, when the component has been restored, it remained wider.
Using one of the suggested methods above, this modification solved the problem for me :

```javascript
  if(PrimeFaces.widget.Sticky)
  {
    PrimeFaces.widget.Sticky = PrimeFaces.widget.Sticky.extend(
      {
        fix: function(force) {
          if(!this.fixed || force) {
            var win = $(window),
              winScrollTop = win.scrollTop();
  
  
            this.target.css({
              'position': 'fixed',
              'top': this.cfg.margin,
              'z-index': ++PrimeFaces.zindex
            })
            .addClass('ui-shadow ui-sticky');
  
            this.ghost = $('<div class="ui-sticky-ghost"></div>')
              .height(this.target.outerHeight())
              .width(this.target.outerWidth())
              .insertBefore(this.target);
            this.fixed = true;
            win.scrollTop(winScrollTop);
          }
        },
  
        restore: function() {
          if(this.fixed) {
            this.target.css({
              position: 'static',
              top: 'auto'
            })
            .removeClass('ui-shadow ui-sticky');
  
            this.ghost.remove();
            this.fixed = false;
          }
        }
      }
    );
  };
```

**Comment by melloware** [comment]
Here is a reproducible test case: 
[pf-1023.zip](https://github.com/primefaces/primefaces/files/3363602/pf-1023.zip)
