### ISSUE TITLE
Component: Title pTooltip not working with version 16.0.0

### ISSUE THREAD

**Issue by Valera1980** [primefaces/primefaces#10244]
### Describe the bug

There is not any tooltip when directive "pTooltip" is added. You can see the error in console - Uncaught Cannot append null to [object HTMLDivElement]

### Reproducer

This is demo 
[https://codesandbox.io/s/rykwlw?file=/package.json:1854-1861](url)

### Expected behavior

There is tooltip when the directive "pTooltip" is added

### PrimeFaces edition

Community

### PrimeFaces version

16.0.0

### Theme

saga-blue

### JSF implementation

Mojarra

### JSF version

19.0.2

### Java version

19.0.2

### Browser(s)

Version 114.0.5735.134 (Official Build) (64-bit)

**Comment by melloware** [comment]
Wrong issue list you want PrimeNG:  https://github.com/primefaces/primeng/issues
