### ISSUE TITLE
DataTable: sorting is not working

### ISSUE THREAD

**Issue by lahari1294** [primefaces/primefaces#10248]
### Describe the bug

DataTable sorting is not working in primefaces 12.0.2 version

### Reproducer

```xml
<p:panel id="searchResultPnl" visible="#{!commonPageLayout.fromMenu}" header="#{msg['title.searchResult']}" >
<p:dataTable id="searchEmailMonitoringResults" lazy="true"
		value="#{viewSearchEmailMonitoringBean.emailMonitoringList}" var="emailMonitoring"
		paginator="true" rows="#{msgApplication['dataTable.navigation.rows']}"
		rowsPerPageTemplate="#{msgApplication['dataTable.navigation.rowsPerPageTemplate']}"
		paginatorTemplate="#{msgApplication['dataTable.navigation.paginatorTemplate']}"
		rowStyleClass="even,odd"
		emptyMessage="#{msg['msg.no.matching.records']}" sortMode="single" >
		<p:column headerText="#{msgCsiEmailmonitoringEmailMonitoring['label.emailMonitoring.application']}" 
					style="width:9%" sortBy="#{emailMonitoring.application}">
			<h:outputText id="application" value="#
{viewSearchEmailMonitoringBean.getCodeDesc(emailMonitoring.application)}" />
</p:column>
</p:dataTable>
</p:panel>
```

### PrimeFaces edition

None

### PrimeFaces version

12.0.2

### JSF implementation

MyFaces

### JSF version

2.0

### Java version

1.8

### Browser(s)

All browsers

**Comment by tandraschko** [comment]
please provide a reproducer and try 13.0.0-RC1

**Comment by Rapster** [comment]
You enabled lazy feature and yet seems like you're using a List as input...

**Comment by lahari1294** [comment]
The variable name is list..but it is not of list type. It is of LazyDataModel.

 public void setEmailMonitoringList(LazyDataModel<EmailMonitoring> emailMonitoringList) {
        this.emailMonitoringList = emailMonitoringList;
    }

**Comment by jepsar** [comment]
Please provide a runnable reproducer. See https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment]
@lahari1294 are you using Payara by any chance and PrimeFaces Extensions as well?

**Comment by melloware** [comment]
Closing this until a reproducer is provided
