### ISSUE TITLE
CommandButton/etc: ajaxLoadingIndicator should have a minimum display time

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10258]
Currently if you click on it, and the request e.g. just takes 50ms, you just see a weird flickering

what about setting a minimum display like 500ms?

- [ ] Minimum display so it shows either for the minimum duration or the full duration if it is longer than the minimum
- [ ] Delay duration where say a 100ms delay is set it won't show the spinner until 100ms and checks if `AjaxQueue.isEmpty() to see if the AJAX already finished to prevent short displays or flickering.

**Comment by jepsar** [comment]
Didn't we talked about this before? Don't remember what came out of that, but I think that would be a great feature. Maybe change from a boolean to an integer to set the delay?

**Comment by tandraschko** [comment]
TBH i cant remember, just tested my customers application and the behavior isnt nice / to much flickering

**Comment by melloware** [comment]
I like the idea of a global minimum delay idea

**Comment by Rapster** [comment]
Not that easy... You'll have the same weird flickering if your task takes 501ms (as it will show at 500ms and disappear at 501ms).

**Comment by tandraschko** [comment]
I would do it different: it will show from 1ms to 500+x, not from 500 to x

**Comment by Rapster** [comment]
yes sounds better

**Comment by jepsar** [comment]
A `delay` attribute would be confusing as `p:ajax` (which can be omitted with `p:commandButton`, as the functionality is offered directly) also has a `delay` attribute.

I haven't looked into it yet, but I would prefer to fix this with CSS.

**Comment by jepsar** [comment]
I was thinking to do something like this:

<img width="922" alt="Screenshot 2023-12-17 at 11 17 43" src="https://github.com/primefaces/primefaces/assets/7500178/2d5eb072-f645-445d-982f-f12c7ad0e6f4">

I took 5 seconds for testing. This number should be a smaller default and go somewhere global with an option to set or override it.

**Comment by melloware** [comment]
I like it.
