### ISSUE TITLE
SelectOneMenu: Label for is pointed at wrong element

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#10254]
@christophs78 Testing with PF 13 getting these warnings in Chrome...

![image](https://github.com/primefaces/primefaces/assets/4399574/c6648ccb-9199-4aef-b1dd-4b96a825823e)

![image](https://github.com/primefaces/primefaces/assets/4399574/957309a6-aa6e-4689-bc13-46512cc8b149)

Can you look?  It looks like the label is pointed at the wrong element?

Reproducer:

```xml
<p:outputLabel for="@next" value="Basic"/>
<p:selectOneMenu id="option" value="#{selectOneMenuView.selectedOption}">
```

**Comment by melloware** [comment]
It looks like the issue may be in the OutputLabelRenderer when it evaluates the for.

```java
UIComponent forComponent = SearchExpressionFacade.resolveComponent(context, label, _for);
```

**Comment by tandraschko** [comment]
TBH it looks fine for me, not sure why chrome throws this error:

Check the showcase:
```
<label id="j_id_8y:j_id_90" class="ui-outputlabel ui-widget" for="j_id_8y:option_label">
.....

<span id="j_id_8y:option_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all" tabindex="0....
```

**Comment by tandraschko** [comment]
maybe because its a span and not a input like mentioned in the msg?

**Comment by melloware** [comment]
Yep the for needs to point to Input.

**Comment by christophs78** [comment]
> maybe because its a span and not a input like mentioned in the msg?

I think so too. Before this accessibility refactoring we had an hidden input.
(`<input id="j_idt343:option_focus" name="j_idt343:option_focus" type="text" autocomplete="off" aria-labelledby="j_idt343:j_idt345">`)

And we had `div id="j_idt343:option" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" aria-owns="j_idt343:option_panel" role="combobox"`

This caused confusion to my disabled colleagues and other people like https://github.com/primefaces/primefaces/issues/9279.
I´ll try to look one more time at https://primevue.org/dropdown/ to get ideas how to solve this issue.

**Comment by christophs78** [comment]
https://primevue.org/dropdown/#floatlabel
![image](https://github.com/primefaces/primefaces/assets/10461942/6f75f2b3-0bf5-401e-95e5-89b875058b24)

They did not solve this for PrimeVue....
![image](https://github.com/primefaces/primefaces/assets/10461942/ffd53331-3ba2-449d-a0e5-cc6ee32f6a8c)

**Comment by christophs78** [comment]
https://material.angular.io/components/select/overview
Even they have this issue ...

![image](https://github.com/primefaces/primefaces/assets/10461942/1c873a72-a9d6-4c6e-94a6-86fd8bc82c82)

**Comment by melloware** [comment]
Maybe we just chalk it over to an overly aggressive Google warning and ignore it for now?

**Comment by melloware** [comment]
To me as long as ARIA is working and every other lib is doing this we should close this ticket as WontFix?
