### ISSUE TITLE
DataView: grid items could not expand width to 100% in a row

### ISSUE THREAD

**Issue by dengbingaliyun** [primefaces/primefaces#10266]
### Describe the bug

Component dataView grid items could not expend width to 100% in a row. 

I have tested in primefaces 12, style is fine.

### Reproducer

```xml
<p:dataView id="dataView" value="#{lineAction.mainlines}" var="line" rows="20" emptyMessage="查无记录"
                                    paginatorPosition="bottom" layout="grid" paginator="true" gridIcon="pi pi-th-large">
       <p:dataViewGridItem columns="3"></p:dataViewGridItem>
</p:dataView>
```

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by tandraschko** [comment]
can you describe your problem a bit better?
a primefaces-test reproducer will up to fix it

**Comment by melloware** [comment]
Yes I am testing 13.0.0-RC2 in Dataview responsive mode and it looks and its working fine.

**Comment by dengbingaliyun** [comment]
Take apollo theme for instance , and modify the primefaces to version 13.0.0-RC2.
`<dependency>
<groupId>org.primefaces</groupId>
<artifactId>primefaces</artifactId>
<classifier>jakarta</classifier>
<version>13.0.0-RC2</version>
</dependency>`

and visit: http://localhost:8080/list.xhtml you will see the difference.
![primefaces 13](https://github.com/primefaces/primefaces/assets/11456193/37830e95-650d-434f-a82d-f8ad144ae186)

primefaces 12 should by looks like below:
![primefaces 12](https://github.com/primefaces/primefaces/assets/11456193/9dcf555d-8fac-4a1c-8d9c-62cdf8a06714)

**Comment by jepsar** [comment]
@dengbingaliyun This is the community issue tracker. We do not have access to the premium Apollo template (per se). Please create a runnable reproducer using https://github.com/primefaces/primefaces-test
