### ISSUE TITLE
documentation PF 13 - layout="grid" is now the default

### ISSUE THREAD

**Issue by LouisCollet** [primefaces/primefaces#10261]
### Describe the bug

In the Primefaces 13 documentation, panelGrid Attributes, the default layout mentioned is tabular.
The migration guide 12-->13 says that  layout="grid" now is the default
I thing the migration guide is right
Have a nice day !
Louis

### PrimeFaces edition

None

### PrimeFaces version

13.0-RC1

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

20

**Comment by jthalmai** [comment]
The second column still mentions 'tabular' as default.

**Comment by melloware** [comment]
What does second column mean?

**Comment by jthalmai** [comment]
The line you fixed is a row in a table and the second column of that table also contains the default value.

**Comment by jepsar** [comment]
Fixed
