### ISSUE TITLE
DatePicker: popup behaves incorrectly when minDate is set to the first or second day of next month

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#10269]
### Describe the bug

We have observed an unusual behavior with the DatePicker component in PrimeFaces when setting the minDate attribute to the first or second day of the next month. The DatePicker popup exhibits problematic behavior, particularly when opening for the second time without a prefilled value. If a value is pre-filled, the issue manifests at the first attempt.

### Reproducer

1-Set mindate to the first or second day of next month.
2-Attempt to open the DatePicker popup without a prefilled value. The issue occurs upon the second opening.
3-When a prefilled value is provided, the issue arises on the first attempt.

### Expected behavior

DatePicker popup should open correctly and display the dates as per the set minDate.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11.0.18

**Comment by jepsar** [comment]
Can you please test with 13.0.0-RC2?

**Comment by jepsar** [comment]
Might be related to https://github.com/primefaces/primefaces/issues/9052

**Comment by Olguorsbasak** [comment]
Thank you Jepsar,  I will look into the relevant issue.

**Comment by melloware** [comment]
@Olguorsbasak yes please try 13.0.0-RC2 as we have made a lot of DatePicker fixes since PF11.

**Comment by melloware** [comment]
I can't make it happen.
[pf-10269.zip](https://github.com/primefaces/primefaces/files/11886724/pf-10269.zip)

Unzip my reproducer and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/ it seems to be working fine for me?

**Comment by Olguorsbasak** [comment]
Hello @melloware  and @jepsar ,
Thank you very much for your help and support. Yes, when I ran the test file you sent and tried it externally with 13.0.0-RC2, I didn't get an error. I also tried it myself and confirmed that it works correctly. Thank you again.
