### ISSUE TITLE
Exporter: Custom registration issue

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#10264]
CC @Rapster this is based on the refactoring done in #9969

We have a custom DataTable like this..

```java
public class MellowareDataTable extends DataTable {
```

When we go to Export in 13.0 we get this error...

```
java.lang.UnsupportedOperationException: 
Component class com.melloware.MellowareDataTable not supported. Use DataExporter#register()
```

The reason is before PF 13 the code was lazy and registered like this assuming it was a Datatable if not a TreeTable...

```java
if (targetClass != null && TreeTable.class.isAssignableFrom(targetClass)) {
            return TreeTableExporterFactory.getExporter(exportAs, exporterOptions);
}

return DataTableExporterFactory.getExporter(exportAs, exporterOptions);
```

But now everything is stored in a map by class and since it does `map.get(Datatable.class)` our custom instance is not found.  I can try and work around this by doing the following...

```java
DataExporters.register(MellowareDataTable.class, DataTablePDFExporter.class, "pdf");
DataExporters.register(MellowareDataTable.class, DataTableCSVExporter.class, "csv");
DataExporters.register(MellowareDataTable.class, DataTableXMLExporter.class, "xml");
DataExporters.register(MellowareDataTable.class, DataTableExcelXExporter.class, "xlsx");
DataExporters.register(MellowareDataTable.class, DataTableExcelXStreamExporter.class, "xlsxstream");
DataExporters.register(MellowareDataTable.class, DataTableCSVExporter.class, "csv");
```

However that fails because the generics are assuming a class with a "custom" exporter for that class.  What I want is to register a new class `MellowareDataTable.class` to an existing exporter `DataTableCSVExporter.class` and it will not allow it.

So there two possible ways to fix this:

1. Fix the generics?
2. When registering the Exporters when checking for an exporter type check the class then walk it's super classes checking for a match until NONE is found.  

Not sure what is the better way to fix it?

**Comment by melloware** [comment]
This would fix the generics but obviously this could lead to mismatched exporter for a class.

```java
public static <T extends UIComponent, E extends Exporter<? extends UIComponent>> void register
```

**Comment by Rapster** [comment]
I was expected this to happen, let me check what I can do
