### ISSUE TITLE
Datatable: Issue with scrollable + rowexpander

### ISSUE THREAD

**Issue by kneringerjohann** [primefaces/primefaces#10263]
### Describe the bug

While using a scrollable datatable with a rowexpander, the rowexpansion is not visible if there are only a few items in the datatable availble.

-Click on Rowexpander
-no output is seen
-scroll down
-output in rowexpander is seen.

![Bildschirmfoto 2023-06-23 um 08 13 01](https://github.com/primefaces/primefaces/assets/9606575/6e20a57f-04e0-4cd7-90e4-05fdef45c639)

![Bildschirmfoto 2023-06-23 um 08 13 19](https://github.com/primefaces/primefaces/assets/9606575/2b8bb414-31bb-4df0-a099-9a125da06511)

### Reproducer

https://github.com/kneringerjohann/primefaces-test/tree/scrollable-datatable-rowexpander

### Expected behavior

I would expect to see the datatable in rowexpander...but its not visible and hidden by scrollpanel

### PrimeFaces edition

Community

### PrimeFaces version

12.0

### JSF implementation

Mojarra

### JSF version

4.0.2

### Java version

17

### Browser(s)

112.0.5615.137

**Comment by melloware** [comment]
Not every feature of datatable is meant to be used with every other feature.  You cannot mix virtual scrolling with Row Expansion.  If you remove `virtualScroll="true"` your example works fine.

**Comment by melloware** [comment]
For virtual scrolling to work it requires FIXED height rows and as you know that is what is causing your row expander to be trapped inside that 66px.

![image](https://github.com/primefaces/primefaces/assets/4399574/27c99416-9bad-463f-bf9f-145a8232b1d3)

**Comment by kneringerjohann** [comment]
So you cannot mix a lazy datatable with row expansion? I do need virtualscroll for lazy loading...

**Comment by melloware** [comment]
You don't need virtual scroll with lazy just u  use pagination if you need row expansion

**Comment by kneringerjohann** [comment]
hm, this is true...but i don't want to use a paginator, as its a different view for our users which is not implemented yet...anyways...thanks for you help!

**Comment by jepsar** [comment]
Note that paginators are more memory friendly (both on the backend and the frontend).
