### ISSUE TITLE
Growl: Duplicate messages

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#10279]
### Describe the bug

Discovered while testing Quarkus with 13.0.0-RC2: https://github.com/melloware/quarkus-faces/issues/291

```xml
<p:growl id="growl" showDetail="true" />
```

While debugging I noticed that `Messages` component does NOT have this issue.  I narrowed this issue down to this line of code in GrowlRendered.

```java
messages = growl.isGlobalOnly() ? context.getMessages(null) : context.getMessages();
```

`context.getMessages(null)` - only 1 message comes out which is correct
`context.getMessages();` - 2 duplicate messages come out.

I noticed MessageRenderer never uses the empty `context.getMessages();`` and thus does not display the issue.

### Reproducer

Running mvn quarkus:dev and hitting the Showcase ToggleSwitch for example click on the "Remote" demo and you will see two AJAX events fired every time. Same thing with the ColorPicker event demo.

![image](https://github.com/melloware/quarkus-faces/assets/4399574/69586157-5114-42de-a780-38e477a81d91)

### Expected behavior

Only 1 Growl message

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC2

### JSF implementation

MyFaces

### JSF version

4.0.1

### Java version

17

### Browser(s)

ALL

**Comment by tandraschko** [comment]
why does context.getMessages() deliver 2 messages? for me its sounds like there is another bug if you really call #addMessage only once

**Comment by melloware** [comment]
I am positive I call it only once and I can verify that the context.getMessages() has 2 messages but `context.getMessages(null)` only has 1 message.

Quarkus 3.2.0 with MyFaces 4.0.1 is where I see the issue.
Jetty with MyFaces 4.0.1 with the exact same reproducer I don't see the issue.  

In myfaces the only different I see is this..

```java
_messages = new LinkedHashMap<>(5, 1f);
_orderedMessages = new ArrayList<>();

List<FacesMessage> lst = _messages.computeIfAbsent(clientId, k -> new ArrayList<>(3));         
lst.add(message);

_orderedMessages.add(message);
```

The one that works is using the LinkedHashMap does a `computIfAbsent` while the ordered just adds the message no matter what.  So possibly some weird race condition?

**Comment by tandraschko** [comment]
No idea, i think we need to find the root problem and not just fix it in PF

can you try to debug with quarkus?

**Comment by melloware** [comment]
Will do.  The reason I submitted this is becaue Messages does NOT have this issue the way it asks for FacesMessages so I just aligned how they were asking for messages.

I will debug a little more in Quarkus and let you know.

**Comment by melloware** [comment]
When I debug in Quarkus in the `GrowlRenderer` when I call the FacesMessages add

```java
public void addMessage(FacesMessage.Severity severity, String summary, String detail) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(severity, summary, detail));

        List<FacesMessage> list1 = context.getMessageList();
        List<FacesMessage> list2 = context.getMessageList(null);

        System.out.println("context.getMessageList().size() = " + list1.size());
        System.out.println("context.getMessageList(null).size() = " + list2.size());
```

It prints out..

```
context.getMessageList().size() = 1
context.getMessageList(null).size() = 1
```



But when I hit the Growl Renderer in RENDER_RESPONSE phase it mysteriously there are two duplicate entries in ordered list but only 1 entry in the Map.  They all point to the same FacesMessage ID too 15804

![image](https://github.com/primefaces/primefaces/assets/4399574/39380752-51b0-401b-94f5-eba30611fce5)

**Comment by melloware** [comment]
OK more info I put a breakpoint in MyFaces on `_messages.add()` and I can see it being added twice. Once in INVOKE_APPLICATION and next in RENDER_RESPONSE

INVOKE_APPLICATION:
![image](https://github.com/primefaces/primefaces/assets/4399574/e3a20e10-9de4-455c-adb8-4b2dc4099ece)

RENDER_RESPONSE:
![image](https://github.com/primefaces/primefaces/assets/4399574/30a0e971-ecee-4894-a76c-71c142f57461)

**Comment by melloware** [comment]
I also opened: https://issues.apache.org/jira/browse/MYFACES-4612

**Comment by melloware** [comment]
OK running Jetty with MyFaces 4.0.1 only the INVOKE_APPLICATION phase receives the call to `addMessage`.  So now i need to figure out why in Quarkus is RENDER_RESPONSE receiving the `addMessage` call.

**Comment by tandraschko** [comment]
yep
please try to find out the different phase
but even calling the method in the different phases should be the same result?!

**Comment by melloware** [comment]
Yep I think I found the issue

**Comment by tandraschko** [comment]
what was the issue now?

**Comment by melloware** [comment]
The problem is this code: https://github.com/melloware/quarkus-faces/blob/main/src/main/java/org/primefaces/showcase/util/MultiPageMessagesSupport.java

It used to always work  but now I am seeing this duplicate messages issue as it adds new Messages to the RENDER_RESPONSE phase but those messages are already there.

It was originally written in PrettyFaces: https://www.ocpsoft.org/docs/prettyfaces/3.2.0/en-US/html_single/#navigation.faces_messages

But now I think there is something weird with it.

**Comment by melloware** [comment]
I know why because the code does this...

```java
        for (Iterator<FacesMessage> iter = facesContext.getMessages(null); iter.hasNext(); ) {
            messages.add(iter.next());
            iter.remove();
        }
```

It has no idea that MyFaces stores in 2 different collections so this code works in Mojarra but not in MyFaces.

**Comment by tandraschko** [comment]
so you mean iter.remove works in mojarra but not in myfaces?

**Comment by melloware** [comment]
Correct. For example.

`iter.remove();`

**Mojarra:**
```java
facesContext.getMessages(null); // 0 items
facesContext.getMessages(); // 0 items
```

**MyFaces:**
```java
facesContext.getMessages(null); // 0 items
facesContext.getMessages(); // 1 item !!!!!
```

**Comment by tandraschko** [comment]
Ok, then we need to fix it like your MyFaces PR
