### ISSUE TITLE
Core JS: scrollTo add way to set animation duration

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#10275]
### Description

As stated on Discord, I noticed that scrolling took way longer after upgrading from 11 to 12.

https://discord.com/channels/787967399105134612/787967662293909524/1121754430551904356

Currently there is no way to set the animation duration.

### Describe the solution you would like

A global setting, and/or an extra parameter in scrollTo to set the duration.

### Additional context

As a workaround, I patched the function with the time I liked:
```js
PrimeFaces.scrollTo = function (id) {
  var offset = $(PrimeFaces.escapeClientId(id)).offset();
  var scrollBehavior = 'scroll-behavior';
  var target = $('html,body');
  var sbValue = target.css(scrollBehavior);
  target.css(scrollBehavior, 'auto');
  target.animate(
    {scrollTop: offset.top, scrollLeft: offset.left},
    250,
    'easeInCirc',
    function () {
      target.css(scrollBehavior, sbValue)
    }
  );
}
```

**Comment by melloware** [comment]
Couldn't you safely do this...

```js
PrimeFaces.scrollTo = function (id, duration) {
  var offset = $(PrimeFaces.escapeClientId(id)).offset();
  var scrollBehavior = 'scroll-behavior';
  var target = $('html,body');
  var sbValue = target.css(scrollBehavior);
  target.css(scrollBehavior, 'auto');
  target.animate(
    {scrollTop: offset.top, scrollLeft: offset.left},
    duration || 250,
    'easeInCirc',
    function () {
      target.css(scrollBehavior, sbValue)
    }
  );
}
```

**Comment by jepsar** [comment]
Sure. But I'm happy with my static override (for now). I think we should solve this in PF 14 though.

**Comment by melloware** [comment]
Oh yeah I am saying the new method should be what I posted above. So it defaults to 250 but gives the user the option to add that second optional param.

**Comment by jepsar** [comment]
I'm just not sure about the 250. Shouldn't we create a context parameter or something for that?

**Comment by melloware** [comment]
yeah we could add a new context param I guess but in Jquery world for animations they have two defaults "fast" = 200ms and "slow" =600ms.  So the old 1000ms seemed way to long to me to begin with?

**Comment by jepsar** [comment]
We could default to 400 in that case.

**Comment by melloware** [comment]
400 seems totally reasonable.
