### ISSUE TITLE
 Dialog: hiding dialog does not restore focus on the button that invoked it 

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#10270]
### Describe the bug

When navigating the [Confirm Dialog showcase ]
[](https://www.primefaces.org/showcase/ui/overlay/confirmDialog.xhtml?jfwid=99d70) using only the keyboard, after selecting the 'Yes' button, the focus does not return to the 'Confirm' button. This poses an accessibility issue for keyboard-only users.

### Reproducer

1. Go to the [Confirm Dialog [](showcase](https://www.primefaces.org/showcase/ui/overlay/confirmDialog.xhtml?jfwid=99d70).)
2. Use the 'Tab' key to navigate to the 'Confirm' button.
3. Activate the 'Confirm' button (usually using the 'Enter' key).
4. Use the 'Tab' key again to navigate to the 'Yes' button in the confirmation dialog.
5. Select the 'Yes' button (usually using the 'Enter' key).
6. Notice that the focus does not return to the 'Confirm' button.

### Expected behavior

After the 'Yes' button is selected, the focus should return to the 'Confirm' button.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11.0.18

**Comment by melloware** [comment]
A similar request was also made at PrimeReact so I think this is something we should try and put on our radar.  
See: https://github.com/primefaces/primereact/issues/4158

**Comment by melloware** [comment]
Found this: https://allyjs.io/tutorials/accessible-dialog.html#restoring-focus-upon-closing-the-dialog
