### ISSUE TITLE
p:clientValidation works with p:message but not with p:messages

### ISSUE THREAD

**Issue by emkatz** [primefaces/primefaces#1027]
There may be client side validation messages _and_ backend data depending faults that cannot be detected in javascript as the full backend data model is not accessable there. 

Example usage is an unique value  e.g. username -> fault would be something like 'value already in use' . Showing only the first fault is mostly bad design.

**Comment by kukel** [comment]
Read this and please post code... http://stackoverflow.com/help/mcve and version info

**Comment by tandraschko** [comment]
Works for me.
If the issue is still there in 6.1 or 6.2-SNAPSHOT, please create new issue with all informations requested by our issue template.
