### ISSUE TITLE
PanelGrid: Layout tabular is not creating columns

### ISSUE THREAD

**Issue by SirError** [primefaces/primefaces#10273]
### Describe the bug

I have a panelGrid with tabular layout.
Inside it I have a row with many columns, but Primefaces is creating only one column instead

So a simple code as:

```
<h:form id="frmTest">
    <p:panelGrid layout="tabular">
        <p:row>
        	<p:column>
			<p:spinner/>        				
        	</p:column>
        	<p:column>
			<p:spinner/>        				
        	</p:column>
        </p:row>
     </p:panelGrid>
 </h:form>
```
should create two columns, but instead it creates one column with both spinners inside it.

You can see that with this reproducer:

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/11895048/primefaces-test-master.zip)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

11

**Comment by melloware** [comment]
Did you see the migration guide: https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/13_0_0?id=deprecated

> PanelGrid tabular layout in favor of responsive layout layout="grid" now the default. To fall back to legacy behavior set layout="tabular" columns="0"

**Comment by SirError** [comment]
> Did you see the migration guide: https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/13_0_0?id=deprecated
> 
> > PanelGrid tabular layout in favor of responsive layout layout="grid" now the default. To fall back to legacy behavior set layout="tabular" columns="0"

You're right Melloware, I saw that I had to use tabular, but skipped the columns=0 part

I guess my eyes need some rest ^^'

sorry for disturbing.
