### ISSUE TITLE
KeyFilter: regression in PF 13.0.0-RC2

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#10285]
### Describe the bug

Something changed with keyFilter, I don't think this is intended behaviour. I tried to find where it started, but I can't see anything.

I have this jsf page:

```
    <h:form>
        <p:inputText required="true" styleClass="some-input">
            <p:keyFilter preventPaste="false" testFunction="return !c.match(/[\d\u0300-\uFFFF]/);"/>
        </p:inputText>
    </h:form>
```

In a selenium test:

```
    @Test
    public void ads() {
        open("http://localhost:8080/primefaces-test/");
        $(".some-input").getWrappedElement().sendKeys("ج");
        $(".some-input").shouldBe(Condition.empty);
    }
```

(it's selenide, but it doesn't matter).

This test does not work with 13.0.0-RC2 and does work with 12.0.0

The problem is that the keyFilter is not applied with PF 13.0.0-RC2. If I type ج with an arabic keyboard I can see that the keyFilter is applied but not with the selenium sendKeys, which is kind of odd.

There is a reproducer in https://github.com/cocorossello/primefaces-test

Run 
`mvn clean jetty:run -Pmyfaces23next 
`
And then execute the selenium test in SeleniumTest.keyFilterTest

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC-2

### JSF implementation

MyFaces

### JSF version

2.3-next-M7

### Java version

17

**Comment by melloware** [comment]
@cocorossello not sure what Selenide is doing but we dropped support for IE8 and KeyBoardEvent.which.

See: https://github.com/primefaces/primefaces/issues/9650

I have a feeling SelenIde might not be setting event.key properly?

here is how we detect is a key is pressed to check for filtering.

```js
            var key = event.key;
            var isPrintableKey = key.length === 1 || key === 'Unidentified';
            if (!isPrintableKey) {
                return;
            }
```

**Comment by cocorossello** [comment]
I have removed selenide from the equation.

You can see now that with selenium and PF 12 sendKeys("ج") does not do anything (keyfilter is applied) but with selenium and PF 13.0.0-RC2 sendKeys("ج") is typed (keyfilter is not applied)

**Comment by cocorossello** [comment]
There is something very weird. 

If I put:

```
        <p:inputText required="true" styleClass="some-input">
            <p:keyFilter preventPaste="false" testFunction="console.log(c);return false;"/>
        </p:inputText>
```

And the test:

    @Test
    public void keyFilterTest() {
        WebDriverManager.chromedriver().setup();
        var driver = new ChromeDriver();
        driver.get("http://localhost:8080/primefaces-test/");
        driver.findElement(By.cssSelector(".some-input")).sendKeys("someج");
        driver.findElement(By.cssSelector(".some-input")).sendKeys("جtext");
        System.out.printf(driver.findElement(By.cssSelector(".some-input")).getAttribute("value"));
    }


PF 13:
Only arabic characters are printed in System.out.
Arabic chacters are not present in console log.

PF 12:
No characters in system.out.
All characters are present in console log

I'll try to see what the PR does, there is a change that affects selenium.

**Comment by cocorossello** [comment]
So the problem is with this isPrintable function:

`<p:inputText required="true" styleClass="some-input" onkeypress="console.log(PrimeFaces.utils.isPrintableKey(event))"/>
`

`        driver.findElement(By.cssSelector(".some-input")).sendKeys("someج");
`

Prints 4 true and 1 false

**Comment by melloware** [comment]
Can you go here: https://w3c.github.io/uievents/tools/key-event-viewer.html

And type in `ج` and see what that keyboard event viewer reports for that key.  Paste the screenshot here.

**Comment by cocorossello** [comment]
The problem is somehow related to selenium:

 ```
   @Test
    public void keyFilterTest() {
        WebDriverManager.chromedriver().setup();
        var driver = new ChromeDriver();
        driver.get("https://w3c.github.io/uievents/tools/key-event-viewer.html");
        driver.executeScript("""
                       document.querySelector("input").addEventListener('keydown', function(e) {
                            console.log("e.key.length:" + e.key.length)
                        });
                        return true;""");
        driver.findElement(By.id("input")).sendKeys("ث");
    }
```
![image](https://github.com/primefaces/primefaces/assets/3096556/02d601b9-fe48-487a-a6c3-4b3849511e60)

If I type with the screen keyboard I can see that e.key.length === 1

![image](https://github.com/primefaces/primefaces/assets/3096556/2bfa7899-323f-4ffa-8e85-46f868644f81)

**Comment by melloware** [comment]
Yep I thought this was a Selenium issue.  Our code in my opinion is doing the correct thing for modern browsers and since we no longer support IE all we care about is modern browsers.  Feels like a Selenium bug to report.

**Comment by cocorossello** [comment]
I can workaround with:

  ```
      new Actions(driver)
                .moveToElement(element)
                .sendKeys(value)
                .build()
                .perform();
```
