### ISSUE TITLE
DataTable: tabView ajax events not rendered in p:rowExpansion

### ISSUE THREAD

**Issue by cyanotyp** [primefaces/primefaces#10283]
### Describe the bug

I'm currently evaluating PF13-RC2 and think I found a bug in datatable / rowexpansion feature:
If I open any toggle row, the further ajax events inside the p:rowexpansion are not rendered / ignored.
In my case, I have a tabview inside the togglerow. 
Instead of switching tabs in the tabview inside the togglerow, the IDs are added to the current URL in the browser,
and the Firefox debugger console shows there are no events (like click,focus,keydown) attached to the rendered <div> 
The same code works great with PF12 (or our outdated PF7) 
A very simple example is attached as reproducer (non-lazy table with 1 column and rowexpansion)

### Reproducer

```
<p:dataTable id="simpleeinheitenDebug" value="#{einheitenBean.listeHisEinheiten}"var="einheit" lazy="false" rowKey="#{einheit.ehtId}">
    <p:column>
        <p:rowToggler/>
    </p:column>
    <p:column headerText="EHT_ID"> <h:outputText value="#{einheit.ehtId}"/></p:column>
    <p:rowExpansion>
        <p:tabView>
            <p:ajax event="tabChange" listener="#{targetEcuBean.onTabChange}"/>
            <p:tab title="Details-1">
                <h:outputText value="Tab 1"/>
            </p:tab>
            <p:tab title="Details-2">
                <h:outputText value="Tab 2"/>
            </p:tab>
        </p:tabView>
    </p:rowExpansion>
</p:dataTable>

```

### Expected behavior

in the html code which is rendered (see EDITED output below)
" <div id="simpleeinheitenDebug:0:j_idt286" ", which is the first line in the table,
as well as all <li class="ui-tabs-header ui-state-default which are the 2 tabs inside the rowexpansion show they have a "event" assigned( click,rowtoggle etc) in firefox debugger with PF12 or 7.
They are not shown and the tab switch is not working in PF13 RC2.

```
<tbody id="simpleeinheitenDebug_data" class="ui-datatable-data ui-widget-content">
<tr data-ri="0" data-rk="101601" class="ui-widget-content ui-datatable-even ui-expanded-row"></tr>
<tr class="ui-expanded-row-content ui-widget-content">
    <td colspan="2">
<div id="simpleeinheitenDebug:0:j_idt286"
             class="ui-tabs ui-widget ui-widget-content ui-corner-all ui-hidden-container ui-tabs-top"
             data-widget="widget_simpleeinheitenDebug_0_j_idt286">
            <ul class="ui-tabs-nav ui-helper-reset ui-widget-header ui-corner-all" role="tablist">
                <li class="ui-tabs-header ui-state-default ui-corner-top ui-tabs-selected ui-state-active"
                    role="tab" aria-expanded="true" aria-selected="true" data-index="0" tabindex="0"><a
                        href="#simpleeinheitenDebug:0:j_idt286:j_idt287" tabindex="-1">Details-1</a></li>
                <li class="ui-tabs-header ui-state-default ui-corner-top" role="tab" aria-expanded="false"
                    aria-selected="false" data-index="1" tabindex="0"><a
                        href="#simpleeinheitenDebug:0:j_idt286:j_idt289" tabindex="-1">Details-2</a></li>
            </ul>
            <div class="ui-tabs-panels">
                <div id="simpleeinheitenDebug:0:j_idt286:j_idt287"
                     class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel"
                     aria-hidden="false" data-index="0" style="">Tab 1
                </div>



```

### PrimeFaces edition

Community

### PrimeFaces version

13 RC2

### Theme

saga

### JSF implementation

Mojarra

### JSF version

3.0

### Java version

11, 17

### Browser(s)

Firefox 102 ESR

**Comment by tandraschko** [comment]
Can you please provide a reproducer?

**Comment by cyanotyp** [comment]
see "reproducer" ? add a tabview in a rowexpansion of a simple datatable.
please be more specific what I shall provide :)

**Comment by tandraschko** [comment]
A sample project / see the primefaces-test sample project

**Comment by cocorossello** [comment]
I was having the same problem and I made a reproducer:

https://github.com/cocorossello/primefaces-test

Run mvn clean jetty:run -Pmyfaces23next and then go to http://localhost:8080/primefaces-test/

You can see how the button in the row works, but the button in the rowExpansion does nothing

**Comment by melloware** [comment]
Thanks for testing!  I know the issue will submit a fix.

**Comment by melloware** [comment]
@cocorossello I think your issue is different.  Your Confirm button doesn't work in 12.0.0 either for me.  So I think your issue is unrelated to AJAX events in TabView like the original poster mentioned in a Row Expansion?

**Comment by melloware** [comment]
Here is a reproducer for just the TabView and the AJAX events not firing confirmed.
[pf-10283.zip](https://github.com/primefaces/primefaces/files/11937903/pf-10283.zip)

**Comment by cocorossello** [comment]
> 

Somehow I have this working in my project working, but you are right, in the reproducer it doesn't work in 12 nor 13....

**Comment by melloware** [comment]
IT looks like its something with that global p:confirm it doesn't like it inside the row expanders.

**Comment by melloware** [comment]
@cyanotyp confirmed your use case is working with my fix

**Comment by cocorossello** [comment]
I've tried the latest snapshot (primefaces-13.0.0-20230705.132626-2.jar) and the ajax actions don't work. Should I open a issue?

**Comment by melloware** [comment]
try to use this snapshot...

```xml
<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshot Repository</name>
    <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>13.0.0-SNAPSHOT</version>
</dependency>
```

**Comment by cocorossello** [comment]
Yes, that is the one I'm using. It's using the snapshot from today. I can see that the commandButton with confirm in the rowexpansion does not work.
