### ISSUE TITLE
Browser caching of resources

### ISSUE THREAD

**Issue by gbrinkmann** [primefaces/primefaces#10293]
### Description

The URL for a custom theme is delivered as for example

`.../faces/jakarta.faces.resource/theme.css?ln=primefaces-mytheme&v=12.0.4`

and together with default http header cache settings a custom theme is browser cached for this version and for 7 days.

The only way to handle this seems to be setting the web.xml context-param com.sun.faces.defaultResourceMaxAge with 0 to override the default 604800000, since trying to modify Cache-Control via WebFilter had no effect.

### Describe the solution you would like

Since this theme caching behaviour only makes sense for themes shipped with a Primefaces version:

There is already a parameter primefaces.THEME, where for example "mytheme" corresponds to the library name "primefaces-mytheme" by default.

PrimeResource.getRequestPath could add

`"&ts=" + System.currentTimeMillis()`

to resource URLs for this library name.

Since this would effect any theme, another new parameter primefaces.EXTERNAL_THEME=true could be used to not modify the URL for themes shipped with a Primefaces version.
Or maybe Primefaces already knows when a library name is a shipped theme.

**Comment by tandraschko** [comment]
You can simple add such a parameter by yourself for your own resources

There is no difference how e.g. components.css or theme.css is handled in PF

**Comment by gbrinkmann** [comment]
> There is no difference how e.g. components.css or theme.css is handled in PF

Wouldn't you consider it as erroneous by design, when external themes (not shipped with a PF version) are browser cached by default, even when they contain changes, because their content doesn't depend on a PF version?

Shouldn't PF handle this by for example adding a timestamp to URLs for a library name?

Feel free to close this when apps need to handle this themselves, although I still consider it as erroneous by design.

**Comment by melloware** [comment]
@gbrinkmann this has already been solved by the wonderful OmniFaces library.  

1. Turn off PF adding v=12.0.4

```xml
<context-param>
    <param-name>primefaces.HIDE_RESOURCE_VERSION</param-name>
    <param-value>true</param-value>
</context-param>
```
2. Use OmniFaces Versioned Resource Handler.

https://github.com/omnifaces/omnifaces/blob/4.x/src/main/java/org/omnifaces/resourcehandler/VersionedResourceHandler.java

**Comment by gbrinkmann** [comment]
Thank you but - yes, there are ways for apps to handle this.

So PF won't handle this in a future version?

OK, then feel free to close.

**Comment by melloware** [comment]
Yep to me there are so many ways to solve this problem and Premium Themes are not a community concern so I am  inclined to close it

**Comment by stolp** [comment]
Maybe the information about using the omnifaces handler could be added to the documentation of the HIDE_RESOURCE_VERSION attribute? This may help people find this solution more easily.

**Comment by gbrinkmann** [comment]
I'm still OK with closing, just a quick note regarding
> Premium Themes are not a community concern
this affects any theme that is not shipped as part of a PF version, not just PF elite versions or designer themes (active company license here).

**Comment by melloware** [comment]
I understand but this is the community tracker.  If you have an issue you think is regarding other PrimeTek products like premium themes or theme designer simply open the request through your PRO account. 

See: https://github.com/primefaces/primefaces#community--elite--pro

**Comment by melloware** [comment]
Here is a list of the shipped themes with PF: https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/resources/META-INF/resources

**Comment by gbrinkmann** [comment]
Yes, I meant if community can use other themes than the shipped ones, those other themes would also be affected (when they are not Omega or Elite or Pro oder Designer with their own supports).

I'm still OK with closing, just wanted to clarify if community is not affected, meaning community can only use shipped themes (or paid themes with own support).
