### ISSUE TITLE
Poll: ajax after setting window.location= causes ViewExpiredException

### ISSUE THREAD

**Issue by skybber** [primefaces/primefaces#10299]
If Primefaces is used together with Omnifaces, then OF send unload request on window "unload" event. This request destroys Myfaces/Mojarra view state. If a p:poll is on the page, then p:poll can send events after an OF unload request and cause a ViewExpiredException. 

### PrimeFaces version

12.0

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11, 17

### Browser(s)

Firefox, Opera

**Comment by melloware** [comment]
Can you add this JS code to your app and see if it fixes your issue?  If so it will help me determine a possible fix.

```js
if (PrimeFaces.widget.Poll) {
    var unloadEvent = ("onpagehide" in window) ? "pagehide" : "unload";
    $(window).on(unloadEvent, function() {
        for (item in PrimeFaces.widgets) {
            widget = PrimeFaces.widgets[item];
            if (widget instanceof PrimeFaces.widget.Poll) {
                widget.stop();
            }
        }
    });
};
```

**Comment by melloware** [comment]
Someting doesn't sound right because OF called unload using the same event.

```js
var unloadEvent = ("onpagehide" in window) ? "pagehide" : "unload";
				$(window).on(unloadEvent, function() {
```

So it should be firing both events and unsubscribing pollers.

**Comment by melloware** [comment]
Can you provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project showing the issue?  I would need to see this myself not working.

**Comment by skybber** [comment]
I'm sending an example project:

https://github.com/skybber/primefaces-poll-problem

There is screenshot, what I see in FF:

https://github.com/skybber/primefaces-poll-problem/blob/master/Screenshot_20230705_222936.png

The selected POST request is the invalid one (after GET) in the screenshot.

Notes:
- please use as a start page URL the `test.xhtml`
- Poll is triggered each 5s
- if you click link `Goto Second Page` within 4-5s after last poll request, you should most likely see the invalid POLL request
- there is race condition between OF unload request and invalid POLL request, sometimes the OF is fast enough and destroys view state before invalid POLL => ViewExpiredException in POLL request
- tested on java17/Tomcat9.

thanks!

**Comment by melloware** [comment]
OK try this version:
[pf-10299.zip](https://github.com/primefaces/primefaces/files/11962166/pf-10299.zip)

Turns out OmniFaces uses `beforeunload` event not `unload`.

**Comment by skybber** [comment]
It is working now. Btw.  correct event in `unload.js` is:

```
  var unloadEvent = ("onpagehide" in window) ? "pagehide" : ("onbeforeunload" in window && !window.onbeforeunload) ? "beforeunload" : "unload";
```

Is the OF unload request synchronized with the previous (last) poll request?

**Comment by melloware** [comment]
Good call!

**Comment by melloware** [comment]
@skybber so does that mean this works?

```js
if (PrimeFaces.widget.Poll) {
   var unloadEvent = ("onpagehide" in window) ? "pagehide" : ("onbeforeunload" in window && !window.onbeforeunload) ? "beforeunload" : "unload";
    $(window).on(unloadEvent, function() {
        for (item in PrimeFaces.widgets) {
            widget = PrimeFaces.widgets[item];
            if (widget instanceof PrimeFaces.widget.Poll) {
                widget.stop();
            }
        }
    });
};
```

or does it have to remain `beforeunload` like in my reproducer?

**Comment by skybber** [comment]
Your reproducer finally helps.

**Comment by skybber** [comment]
There is similar problem with `<p:outputPanel deferred="true">`, it sends POSTs after OF POST + GET caused by `window.location=`  in onload script or Deltaspike initial redirect on page.

**Comment by melloware** [comment]
Can you open a new ticket with reproducer?

**Comment by melloware** [comment]
Can you try this script.

```js
if (PrimeFaces.widget.Poll || PrimeFaces.widget.OutputPanel) {
    var unloadEvent = "beforeunload";
    $(window).on(unloadEvent, function() {
        // abort all AJAX requests
        PrimeFaces.ajax.Queue.abortAll();

        // stop all pollers and idle monitors
        for (item in PrimeFaces.widgets) {
            widget = PrimeFaces.widgets[item];
            if (widget instanceof PrimeFaces.widget.Poll) {
                console.log("Stopping poller");
                widget.stop();
            }
            if (widget instanceof PrimeFaces.widget.IdleMonitor) {
                console.log("Stopping idle");
                widget.pause();
            }
        }
    });
};
```

I want to see if that stops your deferred outputPanel issue?

**Comment by skybber** [comment]
It works, in my case I had to use this code to fix the `WindowIdHtmlRenderer` from DeltaSpike because there is an initial redirection problem in DS that is not related to this problem.
