### ISSUE TITLE
ColorPicker: delivers # prefix together with the 6 digit code

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#10291]
### Describe the bug

Something must have been changed in the color picker component. Picking the color now delivers the 6 digits together with the # prefix. 

![image](https://github.com/primefaces/primefaces/assets/10051373/f181eff9-fe98-44d6-af02-43d4505b24ff)

All our color codes are stored so far as 6 digits strings in the database, e.g.,

```
   @NotBlank 
    @Size(max = 6)
    private String color = "000000";
```

Is this change intended? If yes, does the component allows to get the hex code without the hashtag prefix, e.g., by setting a corresponding attribute?

Thanks in advance for your help. 

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by tuerker** [comment]
I see in the migration guide that is was actually changed. Would be great if there would be the possibility, e.g., by setting an attribute, to have the "old" behavior.

**Comment by melloware** [comment]
Yep its in migration guide: https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/13_0_0?id=color-picker

However yeah I can see some people wanting this behavior I will add another attribute to allow it to not have the "#"

**Comment by tuerker** [comment]
> Yep its in migration guide: https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/13_0_0?id=color-picker
> 
> However yeah I can see some people wanting this behavior I will add another attribute to allow it to not have the "#"

Yes, it would good. Thanks. Changing the varchar(6) in Java as well SQL would be not a big issue is many cases. But in some, where you have several dependent views it gets ugly when you have drop all the dependent views in the reverse order todo this tiny migration.

**Comment by tuerker** [comment]
dear @melloware look at this:

![image](https://github.com/primefaces/primefaces/assets/10051373/207493c7-1287-4ec7-a77d-2fbb8a8e164e)

i would have expected that the selected color is used as the color of the  button on the right hand side instead of this dark gray. is this indented or an issue?

**Comment by melloware** [comment]
Can you provide a PF Test reproducer?  I can't reproduce your issue its working fine for me.

![image](https://github.com/primefaces/primefaces/assets/4399574/1e2c6842-2aae-460d-86e5-165b2c34bf55)

**Comment by melloware** [comment]
I know why because you are using the gradient slider that slider requires 8 digits not 6 color.  This is the correct value.  So you need to disable the gradient.

![image](https://github.com/primefaces/primefaces/assets/4399574/7bc7b3ff-14db-4de7-9efc-afa98bf7ce37)

**Comment by jepsar** [comment]
I don't like adding an attribute to return the old value. People will need to change their code to set that attribute, so why not let them add a simple converter instead?

**Comment by tuerker** [comment]
> I know why because you are using the gradient slider and that slider requires 8 digits not 6 digits color. This is the correct value. So you need to disable the gradient. so set `alpha="false"` if you don't want gradient slider which adds the extra 2 digits.
> 
> i am guessing you have a hard coded 6 digit max length on that text field so its messing it up.

Actually, it is due to our css where button color is generally overwritten. With the change of colorpicker component, where the color is now shown as button, this button takes this in the css defined "dark grey" color. I have revised and fixed this, and just wanted to mention it, in case somebody else falls over this issue, too.

**Comment by tuerker** [comment]
> I don't like adding an attribute to return the old value. People will need to change their code to set that attribute, so why not let them add a simple converter instead?

this colorpicker revision is a "breaking" change and thus requires some migration. it should be mentioned accordingly in the migration guidelines. there one could also provide such a simple converter code fragment.

i have now fully revised all color attributes and changed the size of the strings from 6 to 9 to be capable to store also the color code with the gradient codes.

**Comment by tuerker** [comment]
thanks for all your comments.

**Comment by melloware** [comment]
@jepsar true and also because this new color picker supports many new formats so it can return "rgb" and "hsla" values and not just "#color" i would hate to treat the hex code specially. I am going to change this to a documentation ticket and add a Converter in the docs showing how to strip the `#`

**Comment by melloware** [comment]
Docs updated:

```java
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.inject.Named;

import org.primefaces.util.LangUtils;


@Named
@FacesConverter(value = "hexColorConverter", managed = true)
public class HexColorConverter implements Converter<String> {

    @Override
    public String getAsObject(FacesContext context, UIComponent component, String value) {
        if (LangUtils.isBlank(value)) {
            return null;
        }

        return value.startsWith("#") ? value.substring(1) : value;
    }

    @Override
    public String getAsString(FacesContext context, UIComponent component, String value) {
        if (LangUtils.isBlank(value)) {
            return null;
        }

        return value.startsWith("#") ? value : "#" + value;
    }
}
```
