### ISSUE TITLE
BlockUI: doesn't hide when removing last element in datatable

### ISSUE THREAD

**Issue by cagliotto** [primefaces/primefaces#10309]
### Describe the bug

blockUI doesn't hide when removing last element in datatable.
Previous elements work fine.

### Reproducer

I have a bean generating two rows and the datatable only has a button to remove them.
The button has a styleClass that triggers the blockUI.

XHTML

```
 <h:form id="listForm" >
    <p:dataTable id="dtList" var="row" rowKey="#{row}" value="#{testcase.objectList}" >
      <p:column>#{row}</p:column>
      <p:column>
         <p:commandButton title="Remove" actionListener="#{testcase.remove(row)}" update="dtList" styleClass="blockui-event" />
      </p:column>
     </p:dataTable>
               
     <p:blockUI block="listForm"  trigger="@(.blockui-event)" />
</h:form>
```

BEAN

```
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class Testcase implements Serializable {
    
    private static final long serialVersionUID = 1L;
    private List<String> objectList;
    
    public Testcase() {
        objectList = new ArrayList<>();
        objectList.add("First row");
        objectList.add("Second row");
    }
    
    public void remove(String toRemove) {
        objectList.remove(toRemove);
    }

    /**
     * @return the objectList
     */
    public List<String> getObjectList() {
        return objectList;
    }

    /**
     * @param objectList the objectList to set
     */
    public void setObjectList(List<String> objectList) {
        this.objectList = objectList;
    }
}
```

### Expected behavior

The blockUI should hide when the last element is removed

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.2

### Theme

Mirage

### JSF implementation

Mojarra

### JSF version

2.3.18

### Java version

1.8.0

**Comment by melloware** [comment]
Can you provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It saves developers time reproducing your problem.

**Comment by cagliotto** [comment]
Yes, I'm sorry...I didn't mind to attach a reproducer since the issue was very easy to reproduce.
Here it is

[reproducer.zip](https://github.com/primefaces/primefaces/files/11979492/reproducer.zip)

**Comment by melloware** [comment]
No problem here is a fixed version of your reproducer: 
[pf-10309.zip](https://github.com/primefaces/primefaces/files/11981350/pf-10309.zip)

It includes this MonkeyPatch:

```js
if (PrimeFaces.widget.BlockUI) {
    PrimeFaces.widget.BlockUI.prototype.isXhrSourceATrigger = function(settings) {
        var sourceId = PrimeFaces.ajax.Utils.getSourceId(settings);
        if (!sourceId) {
            return false;
        }
        // we must evaluate it each time as the DOM might has been changed
        var triggers = PrimeFaces.expressions.SearchExpressionFacade.resolveComponents(this.cfg.triggers);

        // if trigger is null it has been removed from DOM so we need to hide the block UI
        if (!triggers || triggers.length === 0) {
            return true;
        }
        return $.inArray(sourceId, triggers) !== -1;
    }
}
```

**Comment by cagliotto** [comment]
Hi, I've tried the reproducer you attached in the previous message but the problem is still present.
I saw you've included that patch in the test.js file but it seem it's not having the expected result.
Thanks

**Comment by melloware** [comment]
Did you press CTRL+F5 in your browser to force JS reloading?  Its working for me.

**Comment by cagliotto** [comment]
Yes I did and I tried with 3 different browsers.
What I've noticed is that if I remove the first element and the second one everything works (before it didn't) but if I remove the last element before removing the first one, the behaviour is still faulty.

**Comment by melloware** [comment]
OK that helps I was doing it in the order that works. 😄

**Comment by melloware** [comment]
I see the issue:

![image](https://github.com/primefaces/primefaces/assets/4399574/21f9a149-5cfe-4bcf-b0a4-785b52992b9f)

Basically you have two rows as ID 0 and ID 1.

When you delete the second row `ID1` when the table re-renders it is now `ID0` basically the first row but the Block UI says is this the item that triggered the block UI and the answer is NO its not ID1 triggered it.

I don't know how to solve this one easily.

**Comment by melloware** [comment]
Well at least I fixed PART of another problem if an item is completely removed from the DOM.  Thanks for your report!

**Comment by cagliotto** [comment]
You are welcome
