### ISSUE TITLE
SelectCheckboxMenu: Having a custom label for when 1 or more checkboxes are selected

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#10305]
### Description

when i have items selected i want an option other than the selected items names or just a static name, especially to work with the emptylabel=""

### Describe the solution you would like

the emptyLabel="" works perfectly, but it would be useful to have a notEmptyLabel="" to say selections made ... for eample

**Comment by melloware** [comment]
I do this in my apps.  Just add this JS to your application JS.

```js
/**
 * Override PF SelectCheckboxMenu to show All, Multiple, or single value
 */
if (PrimeFaces.widget.SelectCheckboxMenu) {
    PrimeFaces.widget.SelectCheckboxMenu.prototype.updateLabel = function() {
        var checkedItems = this.jq.find(':checked'),
            labelText = '';

        if (checkedItems && checkedItems.length) {
            if (checkedItems.length > 1) {
                labelText = 'Multiple';
            } else {
                labelText = $(checkedItems[0]).next().text();
                labelText = labelText.substr(0, 11) + (labelText.length > 12 ? '...' : '');
            }
        } else {
            labelText = this.defaultLabel;
        }

        this.label.text(labelText);
        this.labelContainer.attr('title', labelText);
    };
}
```

**Comment by philpil** [comment]
glad to see their is a workaround, but seen as you are using it and i'm going to use it, can we get it added as a paramater to save future peoples time ?

**Comment by melloware** [comment]
Yep as you can see I also wanted to customize it so if there was only one label it was trimmed with "..." at 12 chars because I am using this in a Datatable filter where I only have so much room to display! 😄

**Comment by melloware** [comment]
Decided on `selectedLabel` as the name of the new attribute
