### ISSUE TITLE
CheckboxTreeNode: Exception with sorting of TreeTable columns

### ISSUE THREAD

**Issue by fabian-weg** [primefaces/primefaces#10303]
### Describe the bug

When using a `TreeTable` with `CheckboxTreeNodes` and the `sortBy` attribute on at least one column, you get an NPE when sorting.

The bug seems to stem from the fact that `CheckboxTreeNodeChildren.set(int index, TreeNode node)` sets the parent of the previous node at `index` to `null` (line 145 in v12.0.0). Standard `TreeNodeChildren` does not do this. In `SortFeature:sortNode` on the other hand, the above set-method is used to replace the nodes with the sorted ones. At some point during this procedure, the parent of nodes that get a lower index than before is consequently set to null, resulting in an NPE on later calls to `getParent()...` of those nodes.

### Reproducer

XHTML
```xhtml
<h:form>
    <p:treeTable value="#{testView.checkboxRootNode}"
                         var="data"
                         selection="#{testView.selectedNodes}"
                         tableStyleClass="table"
                         selectionMode="checkbox">
        <p:column headerText="Column 1"
                          sortBy="#{data}"
                          sortOrder="asc">
                #{data}
        </p:column>
    </p:treeTable>
</h:form>
```
BEAN
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private CheckboxTreeNode<String> checkboxRootNode = buildTree();
    private TreeNode<String>[] selectedNodes;

    private CheckboxTreeNode<String> buildTree() {
        checkboxRootNode = new CheckboxTreeNode<>(null, null);
        CheckboxTreeNode<String> child1 = new CheckboxTreeNode<>("Z", checkboxRootNode);
        CheckboxTreeNode<String> child2 = new CheckboxTreeNode<>("A", checkboxRootNode);
        return checkboxRootNode;
    }

    public CheckboxTreeNode<String> getCheckboxRootNode() {
        return checkboxRootNode;
    }

    public void setCheckboxRootNode(CheckboxTreeNode<String> checkboxRootNode) {
        this.checkboxRootNode = checkboxRootNode;
    }

    public TreeNode<String>[] getSelectedNodes() {
        return selectedNodes;
    }

    public void setSelectedNodes(TreeNode<String>[] selectedNodes) {
        this.selectedNodes = selectedNodes;
    }
}
```
### Expected behavior

sorting is possible, no NPE

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
PR is welcome @fabian-weg  !

**Comment by fabian-weg** [comment]
ok I've created a PR. Thanks for the hint!

**Comment by melloware** [comment]
Thank you!  Running the build now.
