### ISSUE TITLE
Galleria: reloading and caption

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#10300]
### Describe the bug

When (re)loading
https://www.primefaces.org/showcase/ui/multimedia/galleria/caption.xhtml
for a fraction of a second you see all the image captions at the bottom of the screen.
The issue is more noticeable for galleria with a ton of images.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by melloware** [comment]
Can you review my PR?  Basically I hide the caption until it needs to be shown it was doing the inverse of that and showing it and then hiding it if it didn't need to be shown.

**Comment by melloware** [comment]
I think this MonkeyPatch does the same as my fix.

```js
if (PrimeFaces.widget.Galleria) {
    $.prime.galleria.prototype._create = function() {
        this.container = this.element;
        this.content = this.container.children('.ui-galleria-content');
        this.itemsContainer = this.content.children('.ui-galleria-items');
        this.captionContainer = this.content.children('.ui-galleria-caption-items');
        this.thumbnailContainer = this.content.children('.ui-galleria-thumbnail-items');
        this.items = this.itemsContainer.children('.ui-galleria-item');

        if (this.options.fullScreen) {
            this.container.css('display', 'none');
        }

        if (this.options.showCaption) {
            // hide the caption until rendering is complete
            this.captionContainer.hide();
        }

        if (this.items.length > 0) {
            this._setInitValues();
            this._render();

            this.mask = this.container.parent('.ui-galleria-mask');
            this.itemWidget = this.itemsContainer.data('prime-galleriaItem');
            this.thumbnailWidget = this.thumbnailContainer.data('prime-galleriaThumbnail');

            this.transition = PrimeFaces.utils.registerCSSTransition(this.container, 'ui-galleria');

            this._bindEvents();
            this.mounted();
        }
    };
    $.prime.galleriaItem.prototype._renderCaption: function() {
        if (this.options.showCaption) {
            this.captionContainer.show();
        }

        return this.captionContainer;
    };
};
```

**Comment by fcorneli** [comment]
Tried out your PF10300 branch against our application. Problem still remains. Probably because the JS that hides the `captionContainer` takes a while to get executed.

**Comment by melloware** [comment]
ahhh i wonder if it should be done on the server side and just set the default to display:none; when its sent to the browser  originally?

**Comment by fcorneli** [comment]
well, am also looking in this direction.

**Comment by fcorneli** [comment]
Doing `display:none;` on `.ui-galleria-caption-items` prevents the issue, but due to the missing `display:flex;` the captions are foobar on show of course.

**Comment by melloware** [comment]
i am looking too

**Comment by melloware** [comment]
OK I just updated my PR.  This is looking good for me but I only have the showcase to go by?
