### ISSUE TITLE
Upgrade to jqplot 1.0.9

### ISSUE THREAD

**Issue by EugenFischer** [primefaces/primefaces#1030]
# Please provide canvas in high resolution.
## Problem

Using primefaces graph component for any charts does looks blurred on retina display, because the canvas get interpolated for the resolution. 
## Proposal

see http://stackoverflow.com/questions/20221461/hidpi-retina-plot-drawing. 
I've already try and verify the solution, described there by extend the function in charts.js 

best regards,
Eugen Fischer

**Comment by kukel** [comment]
PF **uses**, not develops jqplot, so should it not be a 'fix' over there? Maintaining patches within PF is not what should be done...

**Comment by cagataycivici** [comment]
This is related to jqplot.

**Comment by cagataycivici** [comment]
Maybe we can do the change on our side by changing jqplot.

**Comment by EugenFischer** [comment]
Hi, 
i've also add change request for jqpot. ( https://github.com/jqPlot/jqPlot/issues/51 )

Primefaces wraps jqplot with own javascript (charts.js) so adapt / change jqplot it's not enough for me.

**Comment by EugenFischer** [comment]
jqPlot has already released new 1.0.9 Release

**Comment by mtbadi39** [comment]
What about [Elycharts](https://github.com/voidlabs/elycharts) ?

**Comment by tandraschko** [comment]
We already tried to upgrade to 1.0.9 but one chart type was broken, we should check that again in the future.

**Comment by melloware** [comment]
I am not suggesting anyone tackle this now as its a huge undertaking but I am wondering if for PF 7.0 rewriting the charts for ChartsJS http://www.chartjs.org/ instead of jqPlot might be the best idea.  JqPlot seems to be adbandoned by the developer and chartjs seems quite active and popular.
