### ISSUE TITLE
DatePicker: AJAX blur, update=this with showIcon=true prevents tabbing off field

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#10301]
### Describe the bug

In the showcase, modify `datePickerJava8.xhtml` :  add a blur event and update the datePicker like this : 

```
<p:datePicker id="button" value="#{calendarJava8View.date7}" showIcon="true">
    <p:ajax event="blur" update="@this" />
</p:datePicker>
```

Problems : 

- You can't go to the next field with the tabulation key
- You can't enter a date with the dialog

The reason I want to update the datePicker is that I'd like to enable "fast input". For example, the user enters 31122023 and it displays 31/12/2023 and I still want the button to appear.

### Expected behavior

Updating the datePicker should not block the tabulation. The popup should work as usual.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by jepsar** [comment]
Off topic: why not use a mask? Then you don't need to update the component.

**Comment by ritonglue** [comment]
If the user enters 31122023, my converter is able to understand this localDate but I still want to display 31/12/2023. That's why I need to update the datePicker.

**Comment by jepsar** [comment]
@ritonglue with a mask there is no need for a converter and an Ajax update and you are still able to enter the date without the separators.

**Comment by ritonglue** [comment]
@jepsar You are right 'mask="true' allows fast input by the user. Thanks I didn't know this feature.
@melloware As the mask feature does what I want, I don't need my converter anymore.

But still If you modify the showcase as I mentionned, the tabulation gets stuck.

**Comment by melloware** [comment]
Looks like its a combo of `blur=this` AND showIcon="true"  If the button is NOT there it works fine.  So its something with tabbing to the button.

**Comment by melloware** [comment]
Just going to mark this as WontFix as this is just how AJAX + Update works.
