### ISSUE TITLE
SelectOneRadio: with flex layout - align of radio and label with longer texts

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#10318]
### Describe the bug

Hi,
we are trying new PF 13.0.0-RC2 with PrimeFlex layout for p:selectOneRadio. When labels contain longer texts the whole label is placed below the radio.

![obrazek](https://github.com/primefaces/primefaces/assets/22746146/0a84f505-4889-4988-9419-9afe99003077)

This doesn't look very good.

### Reproducer

```
<p:selectOneRadio id="second" value="#{testView.string}" columns="3" flex="true" layout="responsive">
      <f:selectItem itemLabel="Some longer text to demonstrate  1" itemValue="1"/>
      <f:selectItem itemLabel="Some longer text to demonstrate  2" itemValue="2"/>
      <f:selectItem itemLabel="Some longer text to demonstrate  3" itemValue="3"/>
      <f:selectItem itemLabel="Some longer text to demonstrate  4" itemValue="4"/>
      <f:selectItem itemLabel="Some longer text to demonstrate  5" itemValue="5"/>
      <f:selectItem itemLabel="Some longer text to demonstrate  4" itemValue="6"/>
      <f:selectItem itemLabel="Some longer text to demonstrate  7" itemValue="7"/>
      <f:selectItem itemLabel="Some longer text to demonstrate  8" itemValue="8"/>
</p:selectOneRadio>
```

And add PrimeFlex css into project.

### Expected behavior

I would expect the labels to be placed next to the radios and to wrap and the end of available space.

I am no expert in css, but disabling rule display:inline-block

```
.ui-selectoneradio label {
    cursor: pointer;
    /* display:inline-block; */
    margin: 0 16px 0 8px;
    vertical-align: middle
}
```

looks like it helps with final look:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/3154126f-559e-4841-a181-b30a6251eaef)

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

17

**Comment by melloware** [comment]
Good catch!

**Comment by martin654** [comment]
Thank you for quick fix!

**Comment by melloware** [comment]
Thanks for testing 13.0.0-RC2 we have been looking for good feedback before releasing 13.0.0 final!
