### ISSUE TITLE
SelectOneRadio: Add `columnClasses` attribute

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#10319]
### Description

Hi,
when using p:selectOneRadio with responsive / flex layout, only predefined responsive classes can be used.

from org.primefaces.util.GridLayoutUtils:
```
private static final Map<Integer, String> FLEX_COLUMN_MAP = MapBuilder.<Integer, String>builder()
        .put(1, "col-12 md:col-12")
        .put(2, "col-12 md:col-6")
        .put(3, "col-12 md:col-4")
        .put(4, "col-12 md:col-3")
        .put(6, "col-12 md:col-2")
        .put(12, "col-12 md:col-1")
        .build();
```

we would like to use full possibilities of responsive classes so the generated markup would look for example like this:
```
<div id="frmTest:first" role="radiogroup" class="ui-grid-responsive ui-selectoneradio ui-widget">
    <div class="grid">
        <div class="col-12 md:col-6 lg:col-4 xl:col-3" role="radio" aria-checked="false">
            ...
        </div>
        <div class="col-12 md:col-6 lg:col-4 xl:col-3" role="radio" aria-checked="false">
            ...
        </div>
        <div class="col-12 md:col-6 lg:col-4 xl:col-3" role="radio" aria-checked="false">
            ...
        </div>
        <div class="col-12 md:col-6 lg:col-4 xl:col-3" role="radio" aria-checked="false">
          ...
        </div>
    </div>
</div>
```

### Describe the solution you would like

There are several possibilities:

1. PF user could re-define the map with custom map with css classes. That would be applicable accross whole app without need to specify something special per single component.
2. selectOneRadio component could have columnStyleClass attribute (or some other name) where we could specify our css like this:  columnStyleClass="col-12 md:col-6 lg:col-4 xl:col-3". And the column attribute containing columns number could be ommited in this scenario?
3. some other idea?

**Comment by melloware** [comment]
I believe the intention of this feature was to provide smart defaults and get away from Table `<tr><td>` layouts which are from Web 1.0 days.

If you need total control isn't that what "layout=custom" is for: http://localhost:8080/showcase/ui/input/oneRadio.xhtml ???
