### ISSUE TITLE
DataExporter: fails on export columnGroup with type="header"

### ISSUE THREAD

**Issue by mnyakushev** [primefaces/primefaces#10314]
### Describe the bug

I have table with columnGroup. Header in browser looks  like this 
```
----------------------------
| Movie                    |
----------------------------
| Name | Artist | Released |
----------------------------
```

But when I export my table in xlsx header in LibreOffice.Calc looks like this
```
-------------
| Movie | | |
-------------
| Name      |
-------------
```

### Reproducer

[export-to-excel.zip](https://github.com/primefaces/primefaces/files/11980369/export-to-excel.zip)

1. Start application
2. Go to test page
3. Press xlsx button

Export works fine on 12.0.0
Export fails on 13.0.0-RC2 and latest master-SNAPSHOT

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by melloware** [comment]
Confirmed.  Assigning to @Rapster as it used to Merge these cells.

**Comment by melloware** [comment]
I just pushed a SNAPSHOT build @mnyakushev if you want to give it another test.

```xml
<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshot Repository</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>13.0.0-SNAPSHOT</version>
</dependency>
```
