### ISSUE TITLE
Datepicker: change event is not triggered with mask=true when leaving input

### ISSUE THREAD

**Issue by mnyakushev** [primefaces/primefaces#10311]
### Describe the bug

Change event is not triggered when I click outside of datePicker after value edit. 
Maybe because of changes from issue [#9259](https://github.com/primefaces/primefaces/issues/9259)
Change event triggered as expected when I remove line `this.input.off("blur.inputmask"); // GitHub #9259` from  file [1-datepicker.js](https://github.com/primefaces/primefaces/blob/a6aa61c2a35c80ef4b41f85e23f4621f0dc2ded2/primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js) 

### Reproducer

https://github.com/mnyakushev/primefaces-test

1. Start application
2. Go to test view in web-browser
3. Open developer tools in web-browser, and go to 'Network' tab
4. Click into datePicker
5. Input valid value (for example 01.01.2000)
6. Click outside of datePicker

### Expected behavior

I'm expecting to see a request to the server in the "Network" tab in the browser's developer tools. But the request doesn't happen.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by melloware** [comment]
But do you get the change event now firing when NO changes are made?  Like jiust focus the DatePicker and leave the field does the change event fire?

**Comment by mnyakushev** [comment]
> But do you get the change event now firing when NO changes are made? Like jiust focus the DatePicker and leave the field does the change event fire?

No, I don't see unnecessary change events.

I have overridden DatePicker widget in test.js file of my primefaces-test project. The only change I made was to remove the line `this.input.off("blur.inputmask"); // GitHub #9259` from method `applyMask`. After this 'change' event triggered on blur when I change input value, and not triggered on blur when walue is unchanged.

**Comment by melloware** [comment]
Yep it was fixed in Core InputMask: https://github.com/RobinHerbots/Inputmask/issues/2691
