### ISSUE TITLE
Datepicker: Mask dd.mm.yyyy can't enter a day greater than the 9

### ISSUE THREAD

**Issue by mnyakushev** [primefaces/primefaces#10312]
### Describe the bug

Can't enter a day greater than the 9.

### Reproducer

https://github.com/mnyakushev/primefaces-test

1. Start application
2. Go to test view
3. Open datePicker popup by clicking on button
4. Select 5th day of any month in any year
5. Click into input field
6. Put the caret at the very beginning of the input field
7. Press 3 (nothing will happen).
8. Enter 21 (day will be 2)

### Expected behavior

It should be possible to enter any day of any month from the keyboard. Now I can't enter day from 10 to 31.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by melloware** [comment]
Just confirming. This works fine on 12.0.0?

**Comment by mnyakushev** [comment]
> Just confirming. This works fine on 12.0.0?

Yes

**Comment by melloware** [comment]
I reported it on their page: https://github.com/RobinHerbots/Inputmask/issues/2723

**Comment by melloware** [comment]
Going to close this for now I will monitor the third party ticket.
