### ISSUE TITLE
DataExporter: problems with xlsx export and ui:repeat inside columnGroup

### ISSUE THREAD

**Issue by mnyakushev** [primefaces/primefaces#10325]
### Describe the bug

I tried dataExporter on table with ui:repeat inside columnGroup. Header doesn't export to xlsx at all.
Seems like problem in method ColumnAware::forEachColumnGroupRow.

I overridden the method forEachColumnGroupRow in class MyDataTable.
You can uncomment lines in faces-config.xml to start using this overriden method.
With this changes header exports to xlsx more or less ok.

### Reproducer

[export-to-excel-repeat.zip](https://github.com/primefaces/primefaces/files/11992380/export-to-excel-repeat.zip)

1. Start application
2. Go to test page
3. Press xlsx button

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by Rapster** [comment]
Good analysis @mnyakushev, don't hesitate to make a PR next time 😉

**Comment by Rapster** [comment]
Is that code you would use in production? Because I'm thinking how to support this use case with the new approach and not gonna lie, it's gonna be really tough

**Comment by mnyakushev** [comment]
> Is that code you would use in production? Because I'm thinking how to support this use case with the new approach and not gonna lie, it's gonna be really tough

Looks like I don't need to use ui:repeat with your new approach (without colspan and rowspan). I used ui:repeat beacause I have common logic for colspan and rowspan calculation.



> Good analysis @mnyakushev, don't hesitate to make a PR next time 😉

Ok I will try.

> [dea98d6](https://github.com/Rapster/primefaces/commit/dea98d62e42e7a4f13a6f64447460dcaeb704686)

I noticed couple of things. Maybe it's not a problem, but I want you to look at them.
1. VisitContext created always with hint `ComponentUtils.VISIT_HINTS_SKIP_UNRENDERED`. Without regard to the variable `skipUnrendered`
2. If there will be another components after ui:repeat they will not be processed. 
Because of this line `return child.visitTree(visitContext, (ctx, target) -> {`
Looks like there must be something like this 
```
boolean completed = child.visitTree(visitContext, (ctx, target) -> {
        if (target.getClass().getName().endsWith("UIRepeat")) {
            return VisitResult.ACCEPT;
        }
        
        if (target instanceof Row) {
            Row row = (Row) target;
            if (!callback.test(row)) {
                return VisitResult.COMPLETE;
            }
        }
        
        return VisitResult.REJECT;
});

if (completed) {
    //  completed == true if method callback.test returned false for some row
    return false;
}

```

Example
```
<p:columnGroup>
    <ui:repeat>
        <p:row>
            ...
        </p:row>
    </ui:repeat>
    <p:row>
        ...
    </p:row>
<p:columnGroup>
```

And about pull requests. I see you used `(target.getClass().getName().endsWith("UIRepeat")` insted of `instanceof`. Why you do that? Is there a list of rules in addition to [contributing guidelines](https://github.com/primefaces/primefaces/blob/40de5b76e6334d47bd57f5cdb0dffcc5406f09ed/CONTRIBUTING.md) where will be described what I can use in code?

**Comment by melloware** [comment]
I can answer why `UIRepeat` did not use instanceof is because its not a core JSF interface or class.  

MyFaces: org.apache.myfaces.view.facelets.component.UIRepeat
Mojarra: com.sun.faces.facelets.component.UIRepeat

And we don't want to pollute PF code with custom implementations or import statements.

**Comment by mnyakushev** [comment]
> I can answer why `UIRepeat` did not use instanceof is because its not a core JSF interface or class.
> 
> **MyFaces:** org.apache.myfaces.view.facelets.component.UIRepeat **Mojarra:** com.sun.faces.facelets.component.UIRepeat
> 
> And we don't want to pollute PF code with custom implementations or import statements.

Thank you for the explanation.

**Comment by Rapster** [comment]
>I noticed couple of things. Maybe it's not a problem, but I want you to look at them.

> VisitContext created always with hint ComponentUtils.VISIT_HINTS_SKIP_UNRENDERED. Without regard to the variable skipUnrendered
If there will be another components after ui:repeat they will not be processed.
Because of this line return child.visitTree(visitContext, (ctx, target) -> {
Looks like there must be something like this

Regarding your first statement, it's a tricky use case, one one hand you need to visit rendered repeat but not unrendered rows, so yeah even though skipUnrendered is set to false, it will visit it... I don't think it worth putting too much of thoughts in this... 99% of the time we enable skipUnRendered, in forEachColumnGroupRow is only used once for exporter and skipUnRendered is set to true. I could make few changes, but most of those methods will be removed once I'm done with my dev regarding colgroup.

I fixed according to your second statement

**Comment by melloware** [comment]
@mnyakushev SNAPSHOT pushed if you want to test all the latest changes.

```xml
<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshot Repository</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>13.0.0-SNAPSHOT</version>
</dependency>
```
