### ISSUE TITLE
DataExporter: problems with xlsx export and columnGroup

### ISSUE THREAD

**Issue by mnyakushev** [primefaces/primefaces#10323]
### Describe the bug

I have table with complicated header.
Structure of header successfully exports to xlsx. But text of header cells exports wrong.
Wrong text in cells E3 and F3 of generated xlsx file.

I'm using latest primefaces version with changes from [#10320](https://github.com/primefaces/primefaces/pull/10322)

### Reproducer

[export-to-excel.zip](https://github.com/primefaces/primefaces/files/11991028/export-to-excel.zip)

1. Start application
2. Go to test page
3. Press xlsx button

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by Rapster** [comment]
You didn't mention the problem, so just to be sure...  Problem is right here right?

![image](https://github.com/primefaces/primefaces/assets/7521311/8d9feaba-42dc-44c5-94fc-0b0166bcf505)

**Comment by mnyakushev** [comment]
> Just to be sure... Problem is right here right?
> 
> ![image](https://user-images.githubusercontent.com/7521311/252013305-8d9feaba-42dc-44c5-94fc-0b0166bcf505.png)

Yes in cells E3 and F3.
In E3 must be 'Name' and in F3 mus be 'Artist'

**Comment by Rapster** [comment]
Did it work in 12?

**Comment by Rapster** [comment]
Nvm, got my answer, it didn't

**Comment by melloware** [comment]
It probably never worked in PF Extensions where this code originally came from.

**Comment by Rapster** [comment]
Thank your for providing a sample of "complicated" usage of colgroup, allows me to test this way of handling colgroup see #6409

**Comment by Rapster** [comment]
Off topic, but here is how you'll be able to write it (in near future, not so complicated isn't it? 😄 ):

```xml
<p:dataTable id="tbl" value="#{testView.list}" var="movie" columnGroupLegacyEnabled="false">
  <p:columnGroup headerText="Movie">
      <p:columnGroup headerText="Info">
          <p:column headerText="Name" field="name" />
          <p:column headerText="Artist" field="artist"/>
      </p:columnGroup>
  
      <p:column headerText="Released" field="released" />
  </p:columnGroup>
  
  <p:column headerText="Info">
      #{movie.name} #{movie.released}
  </p:column>
  
  <p:columnGroup headerText="Movie">
      <p:columnGroup headerText="Info">
          <p:column headerText="Name"  field="name" />
          <p:column headerText="Artist" field="artist"/>
      </p:columnGroup>
  
      <p:column headerText="Released" field="released" />
  </p:columnGroup>
</p:dataTable>
```

**Comment by mnyakushev** [comment]
> Off topic, but here is how you'll be able to write it (in near future, not so complicated isn't it? 😄 ):
> 
> ```
> <p:dataTable id="tbl" value="#{testView.list}" var="movie" columnGroupLegacyEnabled="false">
>   <p:columnGroup headerText="Movie">
>       <p:columnGroup headerText="Info">
>           <p:column headerText="Name" field="name" />
>           <p:column headerText="Artist" field="artist"/>
>       </p:columnGroup>
>   
>       <p:column headerText="Released" field="released" />
>   </p:columnGroup>
>   
>   <p:column headerText="Info">
>       #{movie.name} #{movie.released}
>   </p:column>
>   
>   <p:columnGroup headerText="Movie">
>       <p:columnGroup headerText="Info">
>           <p:column headerText="Name"  field="name" />
>           <p:column headerText="Artist" field="artist"/>
>       </p:columnGroup>
>   
>       <p:column headerText="Released" field="released" />
>   </p:columnGroup>
> </p:dataTable>
> ```

The new structure looks more comfortable and logical than the old one for me.

> Thank your for providing a sample of "complicated" usage of colgroup, allows me to test this way of handling colgroup see #6409

I also tried dataExporter on table with ui:repeat inside columnGroup. Header doesn't export to xlsx at all. 
Seems like problem in method ColumnAware::forEachColumnGroupRow.

[export-to-excel-repeat.zip](https://github.com/primefaces/primefaces/files/11992313/export-to-excel-repeat.zip)

I overridden the method forEachColumnGroupRow in class MyDataTable. 
You can uncomment lines in faces-config.xml to start using this overriden method.
With this changes header exports to xlsx more or less ok.

Can the original method (ColumnAware::forEachColumnGroupRow) be fixed? 
If so, should I write a separate issue for this problem?

**Comment by Rapster** [comment]
I can have a look, but yeah please open a new issue
