### ISSUE TITLE
DataTable: dynamic columns have wrong order after sorting

### ISSUE THREAD

**Issue by gunnarschmid** [primefaces/primefaces#10334]
### Describe the bug

When you use a p:dataTable with dynamic, sortable, draggable columns (p:columns) the ordering gets lost:
- change order of columns by dragging
- click on a column header to sort
Result: the headers are still in the manually changed order, but the data is in the original order

This occurs (at least) since PF 10.0.

### Reproducer

This can be reproduced with the showcase project:
- edit src/main/webapp/ui/data/datatable/columns.xhtml: add draggableColumns="true"
- execute the steps described above

### Expected behavior

Expected result: column data should be in the manually changed order (aligned with the column headers)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

17

**Comment by firsthour** [comment]
This is still broken for me in the current master branch of 14.0.0 on Wildfly 26.1.2.

**Comment by melloware** [comment]
@firsthour can you create an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project?

**Comment by firsthour** [comment]
@melloware I was building one based off the dynamic columns showcase and noticed we weren't calling `UITable.resetColumns()`, this plus the PR for this seems to have fixed it in the master branch and also backporting the PR to 13.0.4. Thanks!
