### ISSUE TITLE
Unify and fix row hover on selectable datatable

### ISSUE THREAD

**Issue by giorgioprimefaces** [primefaces/primefaces#1033]
if I set rowSelectMode="checkbox" row highlight on mouse over stops to work, here is the code of my datatable, anyone has the same problem? any workaround??
running on PF 5.3.5 , jsf 2.2.5
[test.zip](https://github.com/primefaces/primefaces/files/92111/test.zip)

**Comment by sudheerj** [comment]
Pull requested created is #1043 

If you add rowHover="true" for the datatable then it adds row hover.By default rowHover is false.

**Comment by giorgioprimefaces** [comment]
No it doesn't work, either using  rowHover="true" or not, rowhover starts to work if I do not use  rowSelectMode="checkbox", I'm having the same problem with PF 5.3.6
hope you will close #1043 soon

**Comment by arunvc1** [comment]
the mouse hover style doesn't work rowSelectMode="checkbox" and  rowHover="true"

**Comment by tandraschko** [comment]
@cagataycivici currently it doesn't look like an bug if i check our code? IMO if selection is available, hover should be available for all modes.

**Comment by maasvdberg** [comment]
Fixed through #4925 ... please close
