### ISSUE TITLE
Badge: add icon support

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#10345]
### Description

I am trying to use the badge to display a plus icon instead of a number. That is no problem since + is a normal character but it would look better if i could use the prime or font awesome plus icon which is larger and bold and would be more flexible in other use cases.

![grafik](https://github.com/primefaces/primefaces/assets/5265550/ea084dd2-f855-42b3-9268-29063fc88a75)

### Describe the solution you would like

Similar to button _icon_ attribute could be added alongside text _value_. Maybe enhance it with _iconPos_ aswell.

**Comment by melloware** [comment]
![image](https://github.com/primefaces/primefaces/assets/4399574/649b2875-b483-45ce-9f85-5c0d510695a3)

**Comment by djmj** [comment]
Looks great! Dont forget to vertically align to center the icon and text. Maybe with "vertical-align: middle;"

**Comment by melloware** [comment]
Looks like the browser says no because the parent is `inline-block` and not `inline`

![image](https://github.com/primefaces/primefaces/assets/4399574/0cd9086d-b339-47f4-a08d-7ae210c81daf)

**Comment by djmj** [comment]
I tested a little within browser tools and pf showcase and dont ask me why, but this gave me decent results regardless of badge size:


```
<span class="ui-badge ui-widget ui-badge-no-gutter ui-badge-xl ui-badge-success">
  <span>9</span>
  <span style="margin-left: 0.1em; font-size: 0.75em; class="pi pi-plus ml-1"></span>
</span>
```

Its a little tricky otherwise, even with vertical-align middle on the inner spans it gets problematic cause of the line height.

**Comment by djmj** [comment]
Great thanks for the fix.
