### ISSUE TITLE
MegaMenu: CSP on - Refused to run the JavaScript

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#10340]
### Describe the bug

Chrome reports:
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-ZjQ0MTJjYjQtNTMxOS00ZmZjLTlmOGMtYzRjMWMwZmM1ZmQ5'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

I think that problem is with href="javascript:void(0)" on menu items

### Reproducer

Turn on CSP using ContextParam 
primefaces.CSP true
and use megaMenu component. For example the one from PF showcase: http://www.primefaces.org:8080/showcase/ui/menu/megaMenu.xhtml

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

17

**Comment by melloware** [comment]
Yes it absolutely is.  Fixing it.

**Comment by melloware** [comment]
OK it was caused by this great new feature: https://github.com/primefaces/primefaces/issues/4068

Let me test if putting `href="#"` allows it to still work or not.

**Comment by martin654** [comment]
Do we want to scroll to top of the page?

**Comment by melloware** [comment]
OK just tried it as `href=""` and it still seems to be working the same way.

**Comment by martin654** [comment]
I just changed href in DOM in browser to href="#" and it seems to work, but it scrolls to top of the page

When I tried href="" as well and it reloads whole page...

![obrazek](https://github.com/primefaces/primefaces/assets/22746146/8b609992-bb1f-465d-b666-c5680bc85788)

**Comment by melloware** [comment]
Don't use that as an example because all of those menu options are not mapped to anything so the browser is doing what it is supposed to do.  A better example is here: https://www.primefaces.org/showcase/ui/menu/menu.xhtml?jfwid=d3a32

Those actually do AJAX things and navigations.

**Comment by melloware** [comment]
I pushed a SNAPSHOT if you want to test it in your apps: https://github.com/primefaces/primefaces#snapshot

**Comment by martin654** [comment]
@melloware Hi, i tried the SNAPSHOT and it doesn't work for us. With empty href it just reloads current page.

Our menu item links markup looks like this:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/f07df071-e775-47c5-885c-7a239cd58bf3)

**Comment by martin654** [comment]
Found this topic on stackoverflow https://stackoverflow.com/questions/5637969/is-an-empty-href-valid, it confirms that href="" reloads the page. 
I wonder if the JS could be changed in a way that CSP would be ok with it?

**Comment by melloware** [comment]
In the past it was always  href="#".  What browser are you using?

Also it looks like you are using p:confirm?

Can you paste your XHTML snippet here please?

**Comment by martin654** [comment]
Yes, we use p:confirm as well. I would have to create reproducer outside our prod app to demonstrate this, not sure i can do it today.

My prefernence is to change to "#", that will work for us. Scrolling to top would happen only in edge case scenarios.

**Comment by melloware** [comment]
Ok let me test with p:confirm today and fix. All other menu scenarios are working for me but it looks like confirm scenario is slightly different. I will let you know.

**Comment by melloware** [comment]
I pushed another SNAPSHOT with `#` if you want to test please.

**Comment by chaloma1** [comment]
Hi, I am @martin654 colleague. I did test your latest snapshot with "#" and it seems to work. Thanks.

**Comment by melloware** [comment]
@chaloma1 excellent!  And 13.0.0 went final and is in Maven Central now if you want to upgrade to that from a SNAPSHOT.
