### ISSUE TITLE
SelectOneMenu: Click chevron icon blocks searching by text

### ISSUE THREAD

**Issue by tarapeti** [primefaces/primefaces#10355]
### Describe the bug

I'm using version 13 the showcase site uses 12.

I've noticed the html elements differ between the version when inspection a selectOneMenu.
The input are in 13 is a `<span>` but in 12 is a `<label>`

Furter more in 13 when clicking the triangle icon to trigger the dropdown the search doesn't work.
If I click in the input are it works as expected but it doesnt when I click the icon. Clicking the icon doesnt set the focus or applies the css class.

### Reproducer

I copied the code from the showcase site to my local code.

### Expected behavior

Clicking the icon should set the focus, apply the css class and the search should work.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

Default

### JSF implementation

Mojarra

### JSF version

2.0, 3.0

### Java version

17

### Browser(s)

chrome, firefox

**Comment by melloware** [comment]
13.0.0 SelectOne has been upgraded due to this ticket: https://github.com/primefaces/primefaces/issues/9279

When you say you can't click the triangle you mean this right?

![image](https://github.com/primefaces/primefaces/assets/4399574/7d357737-45ab-4fd9-8cac-bb5a61ceb51f)

**Comment by tarapeti** [comment]
by triangle yes, but it's clickable also shows the dropdown for the options but when clicking it and searching for an option (typing anything) the search doesn't work

**Comment by melloware** [comment]
I see clicking the chevron and then you type a letter like "G" its not taking you to "Germany" but if you click the input box and type "G" it does.

**Comment by tarapeti** [comment]
wow thanks for the solution!

**Comment by melloware** [comment]
Awesome thanks for testing!
