### ISSUE TITLE
New inplace component

### ISSUE THREAD

**Issue by productys** [primefaces/primefaces#1035]
Upgrade actual inplace component with this one: https://vitalets.github.io/x-editable/

**Comment by kukel** [comment]
PF uses its own compoents in the edit mode, so it would be way, way way to complex to integrate this component. If you see specific features that are not patented, feel free to create individual issues here

**Comment by cagataycivici** [comment]
I don't see a good reason to use that plugin instead of our own implementation optimized for JSF.
