### ISSUE TITLE
SelectCheckboxMenu: unable to partial search for an option without following value order

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#10353]
### Describe the bug

This also doesn't work for the showcase;

When using selectCheckboxMenu with options like "London City", "Leeds City", "Manchester City" "Manchester United" . 

when using the search feature of selectcheckboxmenu, I can't just type City and filter the options that way, I currently have to start at the beginning of the value/string like "Manchester" which would show Manchester city and Manchester United.

### Reproducer

can be checked using the primefaces showcase, if you wanted to look for Miami but typed iami you dont get any result 

### Expected behavior

the search should filter the list based on any matched letters within the values

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.1

### Java version

19

**Comment by stolp** [comment]
The showcase uses `filterMatchMode="startsWith"` for the example you are referring to, so the behavior seems correct.

If you use `filterMatchMode="contains"` the component behaves like you expect.

**Comment by philpil** [comment]
filterMatchMode="contains" this worked
