### ISSUE TITLE
Improve SelectOneMenuRenderer for String objects (List<String> etc.)

### ISSUE THREAD

**Issue by fatdevelops** [primefaces/primefaces#1036]
Please make the `SelectOneMenuRenderer` work for a collection of `String` objects to make it work for custom content.

Please see: http://stackoverflow.com/questions/34656127/primefaces-selectonemenu-with-fontawesome-icons-custom-fselectitems/34813602?noredirect=1#comment57372040_34813602 
http://stackoverflow.com/questions/32735770/pselectonemenu-doesnt-render-custom-content-via-pcolumn-on-liststring

This can be achieved by introducing another attribute `customContent="true|false"` on the <p:selectOneMenu> and by getting rid of the `instanceOf` comparison in the `encodePanel(...)` method in the `SelectOneMenuRenderer` class. If `customContent` is set to true, the `encodeOptionsAsTable(...)` method will call `renderChildren(...)` for every `<p:column>` no matter if the `SelectItem` is an `instanceOf` `String` or not.

See also: https://github.com/primefaces/primefaces/blob/5_3/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L208
https://github.com/primefaces/primefaces/blob/5_3/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L249
https://github.com/primefaces/primefaces/blob/5_3/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L272

**Comment by ckirbas** [comment]
I second that. We need to add custom contents for itemLabels.

**Comment by tandraschko** [comment]
Could someone provide a PR?

**Comment by melloware** [comment]
I can take this one @tandraschko

**Comment by tandraschko** [comment]
Could we improve this by removing the attribute and looking for p:column as child?

if (menu.isCustomContent()) -> if (menu.getColumns().size() > 0) ?

**Comment by tandraschko** [comment]
Ok, i'm a little bit confused as we had 2 customContent variables, with a different meaning.
Will check it again.

**Comment by tandraschko** [comment]
@melloware 
Currently i think we have 3 hints for the same meaning:
var attribute used -> custom content
    which means the same as p:columns are available as content
    which means the same as customContent=true ?

There is only custom content, which means that var and columns need to be defined. Everything else means no custom content?!

**Comment by tandraschko** [comment]
I also wonder if the following combinations can be used correctly:
1) var == null, columns == 0
2) var != null, columns > 0

i think it's only valid when var and columns are used.

**Comment by tandraschko** [comment]
Removed the attribute again, i think it's ok as var+columns represents custom-content.

**Comment by melloware** [comment]
Ahhh I like your solution better.  Nice work.
