### ISSUE TITLE
ImageCropper: originalFilename does not match the name attribute of DefaultStreamedContent

### ISSUE THREAD

**Issue by seinecle** [primefaces/primefaces#10365]
### Describe the bug

`CroppedImage `object has an `originalFilename` attribute which is the name of the image that has been cropped.

If one is cropping an image which is obtained via a `StreamContent` rather than a static file, then there is no filename as such. Conveniently, a name can still be set to the `StreamContent`:

`StreamedContent imageAsStream = DefaultStreamedContent.builder()**.name("example")**.contentType("image/png").stream(() -> stream).build();`

yet, when one calls the method `getOriginalFileName `on the `CroppedImage`, it produces a `String `which is the result of the `toString()` method of the original `StreamContent`, instead of returning the `name` attribute that had been set in the builder.

Use case: I need to match the original pic with the cropped pic, and it would make my life easier if I could just use their names to match them.

### Reproducer

This case is deeply embedded in an app, can't create a reproducer.

### Expected behavior

The `originalFilename `attribute of `CroppedImage `should match the `name `attribute of the image that was cropped and which originated from a `DefaultStreamContent`.

### PrimeFaces edition

Community

### PrimeFaces version

12.0

### Theme

default theme

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
OK I see the issue.  PR submitted.

**Comment by seinecle** [comment]
Hello,

Thanks for the fix! Looking at the class `DefaultStreamContent`, it seems that there is no guarantee that its `getName` method returns a `String `value - it will return `null `if the value was not set.

That might come as a suprises to devs:

- they will always get a `String `value when they call `getOriginalFileName` on `CroppedImage `when the original image is a static file
- if and when they switch the original image to a `StreamedContent`, `getOriginalFileName` will return a `null `value if they didn't optionally set the name on `DefaultStream`.

In this case, wouldn't it be good to:

- add a comment in the javadoc of `getOriginalFileName` mentionning this behavior?
- or to modify the `getName` method of `DefaultStreamContent`, so that if `name` value is `null`, it returns the value returned by the `toString()` method instead? (this second option seems least preferable).

**Comment by melloware** [comment]
@seinecle see my latest PR: https://github.com/primefaces/primefaces/pull/10370
