### ISSUE TITLE
Colspan problem on Datatable with hidden columns and rowExpansion

### ISSUE THREAD

**Issue by hinneLinks** [primefaces/primefaces#1037]
I have a table with invisible columns, i use those to Export Data, i don't want to show in the UI.
The UI and the Export look fine, the UI dosn't have the ID-Table, the Excel-File shows it:
![Table Layout fine](http://up.picr.de/24320019ls.jpg)

If i expand the Table-Rows, the Expansion causing layout problems, since it uses colspan and count all rows, not just the visible ones:
![Table Layout broken](http://up.picr.de/24320020yk.jpg)

I attached a sample app with Maven/Jetty (the p:dataTable  in the file src\main\webapp\index.xhtml)

[primefaces-rowExpansion-invisibleColumns.zip](https://github.com/primefaces/primefaces/files/94135/primefaces-rowExpansion-invisibleColumns.zip)

**Comment by mertsincan** [comment]
Thanks for the sample. I will work on it and get back to you.

**Comment by sweetcard** [comment]
@mertsincan 
This feature can't support dynamic columns. Any plan please.
This is my code to support dynamic columns.

 public int getColumnsCount ()
    {
        int columnsCount = 0;

```
    for (UIComponent kid : getChildren ())
    {
        if (kid.isRendered ())
        {
            if (kid instanceof Columns)
            {
                int dynamicColumnsCount = ((Columns) kid).getRowCount ();
                //if visible=false, don't count
                for (int i = 0; i < dynamicColumnsCount; i++)
                {
                    DynamicColumn column = ((Columns) kid).getDynamicColumns ().get (
                            i);
                    if (column.isVisible ())
                    {
                        columnsCount++;
                    }
                }
            } else if (kid instanceof Column)
            {
                if (((UIColumn) kid).isVisible ())
                {
                    columnsCount++;
                }
            } else if (kid instanceof SubTable)
            {
                SubTable subTable = (SubTable) kid;
                for (UIComponent subTableKid : subTable.getChildren ())
                {
                    if (subTableKid.isRendered () && subTableKid instanceof Column)
                    {
                        columnsCount++;
                    }
                }
            }
        }
    }

    return columnsCount;
}
```
