### ISSUE TITLE
selectOneMenu: label not associated with select

### ISSUE THREAD

**Issue by timdoering** [primefaces/primefaces#10380]
### Describe the bug

A label for a selectonemenu gets associated with a label within the selectonemenu, but not with the select itself

### Reproducer

```
            <p:outputLabel for="@next" value="#{cc.attrs.label}:"/>
            <p:selectOneMenu ...
```

### Expected behavior

For accessibility reasons the select needs to have a label, so the associated label should target the select

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.x

### Java version

11

**Comment by tandraschko** [comment]
i'm sure this worked in the past
@christophs78 something for you?

**Comment by melloware** [comment]
Isn't this #10254 which we determined was a false positive?

**Comment by christophs78** [comment]
> Isn't this #10254 which we determined was a false positive?

yep (currently just too busy to write long explanations)
