### ISSUE TITLE
Wrong year in calendar popup when used with German locale and EEE pattern

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1038]
Hi,

I am not sure if this bug is related to PrimeFaces (I am using 5.3.5) or jQuery's datepicker widget. However, this simple jsfiddle does work correctly: https://jsfiddle.net/2Ly6jfwg/2/

Initially the calendar's date is set to now. If you then click to open the popup, you'll see the year getting adjusted to '2021' for example.

XHTML:

```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">  
    <h:head />  
    <h:body>
        #{calView.localeEN} (right):
        <p:calendar value="#{calView.date}" pattern="EEE, yyyy-MM-dd" locale="#{calView.localeEN}" /><br />
        #{calView.localeDE} (wrong):
        <p:calendar value="#{calView.date}" pattern="EEE, yyyy-MM-dd" locale="#{calView.localeDE}" />
    </h:body>  
</html>  
```

JSF bean:

```
@ManagedBean(name = "calView")
@SessionScoped
public class CalendarView implements Serializable {

    private Date date;
    private Locale localeEN;
    private Locale localeDE;

    @PostConstruct
    public void init() {
        date = new Date();
        localeEN = Locale.ENGLISH;
        localeDE = Locale.GERMAN;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Locale getLocaleEN() {
        return localeEN;
    }

    public void setLocaleEN(Locale localeEN) {
        this.localeEN = localeEN;
    }

    public Locale getLocaleDE() {
        return localeDE;
    }

    public void setLocaleDE(Locale localeDE) {
        this.localeDE = localeDE;
    }

}
```

The java date pattern 'EEE, yyyy-MM-dd' gets correctly converted to jQuery's 'D, yy-mm-dd'...

Thanks for fixing this

**Comment by cnsgithub** [comment]
Including the appropriate script from https://code.google.com/p/primefaces/wiki/PrimeFacesLocales like mentioned in your documentation solved this issue. However, I just wonder if missing locales should lead to wrong functionality, that's still weird...

**Comment by melloware** [comment]
@cnsgithub why does including the German locale solve the issue?   https://github.com/primefaces/primefaces/wiki/Locales

**Comment by guilhermeribeirodev** [comment]
Same problem here with French. You change the pattern prop and things mess around. I changed from EEE to EEEE to fix Spanish wrong year shown but still fails with French. Have locale resources for both.  This is related with the way JS parses date back from input. Is quite bad implemented.

**Comment by melloware** [comment]
I was looking at this and I think we need a better JavaScript -> Java date format converter.  I might look into using this...

https://github.com/MadMG/moment-jdateformatparser

It uses moment.js which Primefaces already includes and it handles converting to and from the Java Date Format.

**Comment by melloware** [comment]
Here is another one we should consider...

https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/utils/LocaleUtils.java

**Comment by melloware** [comment]
Closing for now as it was a missing locale which is covered in the documentation.
