### ISSUE TITLE
TextEditor: cannot combine underline and smal/huge size of font

### ISSUE THREAD

**Issue by artragis** [primefaces/primefaces#10385]
### Describe the bug

When you are using a p:textEditor you cannot set the "huge" size then underline the text, only underline will be taken into account.

### Reproducer

1. Go to https://www.primefaces.org/showcase/ui/input/textEditor.xhtml?jfwid=c7208
2. Enter any text
3. Select the text
4. Select "huge" size
5. Select the text
6. Select "underline"
7. Click on save (it will trigger the behaviour)
8. Résult: 
![text is not huge](https://github.com/primefaces/primefaces/assets/1523653/af4c6991-ed2f-453e-919b-81b89b293fe0)

### Expected behavior

The text must be huge (the same way it is before you click on save) : 
![image](https://github.com/primefaces/primefaces/assets/1523653/91ea593b-0211-498b-9afc-1dcb498d5c7e)

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Appolo

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by jepsar** [comment]
Can you please try with `secure="false"`?

**Comment by artragis** [comment]
With this parameter, the issue does not appear. But putting "secure=false" is not a good solution for our software.

**Comment by artragis** [comment]
I think I've found the issue : in the sanitizer,the "u" mark does not have the right you have the class attribute. Do you want me to create a PR?

**Comment by melloware** [comment]
Yes please create a PR!

**Comment by artragis** [comment]
Here it is https://github.com/primefaces/primefaces/pull/10386

**Comment by jepsar** [comment]
@melloware  I think we should have a service as we do with virus scanning which can be used to easily create your own sanitizer. New issue BTW. WDYT?

**Comment by melloware** [comment]
Or we need to move this to PF: https://www.primefaces.org/showcase-ext/sections/converters/sanitizingConverter.jsf

**Comment by melloware** [comment]
13.0.1-SNAPSHOT is available with your fix if you want to test: https://github.com/primefaces/primefaces#snapshot
