### ISSUE TITLE
AutoComplete: generates invalid html within suggestion box

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10397]
### Describe the bug

A `p:column` within a `p:autoComplete` has the following content:

```
<p:column width="80px">
    <span>
        <span>#{user.name}/#{user.msg}</span>
    </span>
</p:column>
```

When `p:autoComplete` shows suggestions (within its suggestion box) while "input" is being typed, it generates **invalid html** and the invalid html is also visible in the suggestion box:

// snippet copied from generated html:

```
<td>
    <span>
        <sp<span class="ui-autocomplete-query">an&gt;
        <span class="ui-autocomplete-query">U</span>ser_0/hello how are yo/
        <span class="ui-autocomplete-query">U</span>ser_1/hello how are yo/</sp
        <span>an&gt;
    </span>
</td>
```

As you can see, Primefaces didn't inject `<span class="ui-autocomplete-query">` correctly because it destroys the earlier span element (`<sp..</sp`) and incorrectly wraps its HTML. 

### Reproducer

[primefaces-test-jakarta.zip](https://github.com/primefaces/primefaces/files/12183852/primefaces-test-jakarta.zip)

### Expected behavior

The generated html should be valid, e.g.:

```
<td>
    <span>
        <span class="ui-autocomplete-query">U</span>ser_0/hello how are yo/
        <span class="ui-autocomplete-query">U</span>ser_1/hello how are yo/</sp
    </span>
</td>
```

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

jakarta faces api 4.0.1

### Java version

17

### Browser(s)

Firefox 115.0.2

**Comment by melloware** [comment]
We have a Jakarta PrimeFaces Test project if you think its Jakarta related?

Its right here: https://github.com/primefaces/primefaces-test/tree/jakarta

Its the same as the normal reproducer but using Jakarta.

**Comment by melloware** [comment]
The issue is here in `autocomplete.js`

```js
//highlight query string
            if (query.length > 0) {
                var cleanedQuery = query.trim().replaceAll(/(\s+)/g, ' ');
                if (cleanedQuery.length > 0) {
                    var queryParts = cleanedQuery.split(' ');
                    for (var i = 0; i < queryParts.length; i++) {
                        queryParts[i] = PrimeFaces.escapeRegExp(queryParts[i]);
                    }
                    var re = new RegExp('(' + queryParts.join('|') + ')', 'gi');
                    var isCustomContent = this.panel.children().is('table');
                    var queryResults = isCustomContent ? this.panel.children().find('span') : this.items;
                    queryResults.filter(':not(.ui-autocomplete-moretext)').each(function() {
                        var item = $(this);
                        var text = $this.cfg.escape ? item.html() : item.text();
                        item.html(text.replace(re, '<span class="ui-autocomplete-query">$&</span>'));
                    });
                }
            }
```

**Comment by melloware** [comment]
Its definitely these lines.

```js
 var text = $this.cfg.escape ? item.html() : item.text();
item.html(text.replace(re, '<span class="ui-autocomplete-query">$&</span>'));
```

if you type in `sp` its searching and replacing `sp` inside your text and since you have `<span>` inside its replacing.  Not sure how to fix this one.

**Comment by melloware** [comment]
@nimo23 can you explain this line

```js
/${escape(text)}/g
```

What is "escape"  Do you mean to use `PrimeFaces.escapeRegExp` ?

**Comment by melloware** [comment]
OK I fixed it to be `/${PrimeFaces.escapeHTML(text)}/g
