### ISSUE TITLE
Dialog Framework: focus property not working

### ISSUE THREAD

**Issue by Sun8642** [primefaces/primefaces#10394]
### Describe the bug

When you open a new dialog using the component Dialog Framework, the focus is automatically set on the close button.

### Reproducer

Go to https://www.primefaces.org/showcase/ui/df/basic.xhtml
Click on the responsive button to open a new dialog with some inputs

### Expected behavior

The first input should be focused (the 'Firstname' input in this case).

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

All

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Chrome

**Comment by melloware** [comment]
As a note the documentation has a `focus` property for the Dialog Framework but it appears not to be working either.

https://primefaces.github.io/primefaces/13_0_0/#/core/dialogframework?id=dialog-configuration

<html>
<body>


focus | null | String | Defines which component to apply focus by search expression.
-- | -- | -- | --



</body>
</html>

**Comment by tandraschko** [comment]
can we even support his in a iframe? If not, we can just remove from docs and close as wont fix
