### ISSUE TITLE
DataTable with bound AutoComplete

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10407]
### Description

Actually, the user cannot add data to a `p:dataTable` simply by selecting data from a list of selectables. (Currently, the user can only _filter_ data of a `p:dataTable`. )

### Describe the solution you would like

To have an ordinary `p:dataTable` with a global `p:autoComplete`-box above all the rows of this datatable. The global `p:autoComplete` -box is the **inverse** of a global `p:filter` (showed in https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml?jfwid=73970). **Inverse** means, instead of filtering the results, it **adds** the results into the datatable based on the selection of the `autoComplete`-box.

### Additional context

I think, this would also fix issues https://github.com/primefaces/primefaces/issues/9542 and https://github.com/primefaces/primefaces/issues/1903 _indirectly_, because with the feature described in this issue, the other issues can be achieved by using a `p:dataTable` with its **bound** `p:autoComplete`, which is a more versatile approach for wider use.

**Comment by melloware** [comment]
I am not sure I understand the issue you are describing?

**Comment by melloware** [comment]
This feels like a really specific use case.  I guess I don't understand what you can't accomplish now with proper AJAX calls and some clever facet `header` rendering?
