### ISSUE TITLE
Switch to JSF 2.3 as minimal requirement

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10434]

**Comment by fcorneli** [comment]
Why Java 11? JSF 2.3 is part of Java EE 8, for which Java 8 is sufficient.

**Comment by tandraschko** [comment]
actually EOL
but it seems amazon e.g. extend further 2 years

**Comment by fcorneli** [comment]
JSF 2.3 only is indeed probably safer. Forcing Java 11 could impact a lot of (PrimeTek paying) customers' runtimes.

**Comment by NicolaIsotta** [comment]
Maybe `isAtLeastServlet30` can be removed too? If I'm not wrong JSF 2.3 requires Servlet 4.0

**Comment by tandraschko** [comment]
tomcat 8.5 is servlet 3.1, so still supported widely
