### ISSUE TITLE
JSF 2.2 removal: use client-window-factory

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10444]
in the past we used lifecyclefactory to have JSF 2.2 compatiblity, now we can use client-window-factory directly
it seems it doesnt work at least in Mojarra 2.3, Myfaces 2.3 works fine

@melloware are you interessted to check that?

simple add a PrimeClientWindowFactory and return new PrimeClientWindow + register it in faces-config

**Comment by melloware** [comment]
i will check it out.

**Comment by melloware** [comment]
Hmmm Our showcase uses `PrimeClientWindowLifecycleFactory` and I just ran it with MyFaces 2.3 and Mojarra 2.3 and everything seems to be working?  Is there something specific that is not working?

**Comment by melloware** [comment]
OK found the Mojarra issue. They required the `web.xml` param or they never turn on the Client Window.

**Comment by melloware** [comment]
I opened a Mojarra ticket: https://github.com/eclipse-ee4j/mojarra/issues/5297

**Comment by melloware** [comment]
Mojarra closed my 2.3 ticket as not supported so I opened a new one for 4.0.4: https://github.com/eclipse-ee4j/mojarra/issues/5316
