### ISSUE TITLE
RequestContext.update() after upgrade PF to 5.3

### ISSUE THREAD

**Issue by DovahSnow** [primefaces/primefaces#1044]
After I update PF, the RequestContext.update() not work (in 5.2 works). This problem looks like to 
https://github.com/primefaces/primefaces/issues/819

The id component exists, but the method cannot find it. I get the component ID by javascript method: "PrimeFaces.widgets[message].id".

Regards.

**Comment by tandraschko** [comment]
You cant use the generated client for #findComponent. Just search how to use findComponent.
The expression likely starts with ":", and the clientId doesnt.
Use the forum for such questions next tome.

**Comment by DovahSnow** [comment]
I don't use #findComponent. I need RequestContext.update() method, to refresh a component from a backingbean, like http://www.primefaces.org/showcase/ui/misc/requestContext.xhtml.

This is my code, in Primefaces 5.2 works.

```
        function handleMessage(message) {
           refreshWidget(PrimeFaces.widgets[message].id);
        }


        <pe:remoteCommand id="refreshWidgetCommand" name="refreshWidget" process="@this"
                          actionListener="#{controller.refresh}">
            <pe:methodSignature parameters="java.lang.String"/>
            <pe:methodParam name="id"/>
        </pe:remoteCommand>


       public void refresh(final String id) {
                RequestContext context = RequestContext.getCurrentInstance();
                context.update(id);
       }
```

Regards.

**Comment by tandraschko** [comment]
Yeah, but internally to validate if the component exists. It was also a step to allow SEF to use by #update.
So try to prepend ":"
