### ISSUE TITLE
Locales: Accents are misgenerated at build time

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#10460]
### Describe the bug

Hello,
Checking JS french locale file, It looks like accents are misgenerated at build time for 13.0.0 version and the current one.

### Reproducer

[pf-locales-build.zip](https://github.com/primefaces/primefaces/files/12289101/pf-locales-build.zip)

Reproducer shows a DatePicker using a french locale.

![image](https://github.com/primefaces/primefaces/assets/26894018/48e89c5f-706c-4ba7-b15b-e26442a85d7d)

### Expected behavior

Accents should be correctly generated during compilation.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.0 and 14.0.0-SNAPSHOT

### Theme

All

### JSF implementation

All

### JSF version

4.0

### Java version

11

### Browser(s)

All

**Comment by brivalin** [comment]
After more analysis, the problem is due to the Maven AppendingTransformer.
Commenting this line seems to solve the problem : 
```
<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
    <resource>META-INF/resources/primefaces/locales/locale-fr.js</resource>
</transformer>
```

**Comment by melloware** [comment]
Thanks for reporting I will take a look at this. Just to confirm this is the Jakarta version of the JAR?

**Comment by jepsar** [comment]
It's JSF version 4, so I guess Jakarta.

**Comment by melloware** [comment]
Yep confirmed its OK in JSF2.3 but broken with the Jakarta JAR. Going to see if there is a clever way to handle it.

**Comment by brivalin** [comment]
> Thanks for reporting I will take a look at this. Just to confirm this is the Jakarta version of the JAR?

Yes it's only with the Jakarta version.

**Comment by melloware** [comment]
Also your solution means that things like...

```
"javax.faces.component.UIInput.CONVERSION": "{0} : une erreur de conversion s'est produite.",
```

Won't be converted to

```
"jakarta.faces.component.UIInput.CONVERSION": "{0} : une erreur de conversion s'est produite.",
```

So we have to find the root cause of this conversion issue

**Comment by tandraschko** [comment]
propably just wrong enconding somewhere in shading/AppendingTransformer

**Comment by brivalin** [comment]
As a workaround, accents may be replaced by unicode characters to avoid this encoding problem.

**Comment by melloware** [comment]
So i cracked open both JARS and both files are encoded UTF-8.  I think Thomas is right one of the transformer's is munging the bytes.

![image](https://github.com/primefaces/primefaces/assets/4399574/1fb55fa3-3dc1-44c5-a472-a0afaf4cfd63)

**Comment by melloware** [comment]
OK found a fix to make it bulletproof for both JARS and going forward.
