### ISSUE TITLE
Exporter: Wrong value in XLS export for Date / Calender

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#10464]
### Describe the bug

Exporting a datatable column with a Date field results in a wrong value in XLS when using convertDateTime with pattern "dd.MM.yyyy"
```
<p:column headerText="Date">
    <h:outputText value="#{product.created.time}">
        <f:convertDateTime pattern="dd.MM.yyyy"/>
    </h:outputText>
</p:column>
```

PDF and CSV export works as expected.

XLS Export works as expected when using pattern "yyyy-MM-dd"

Here the exported documents:
[products.csv](https://github.com/primefaces/primefaces/files/12292164/products.csv)
[products.pdf](https://github.com/primefaces/primefaces/files/12292165/products.pdf)
[products.xls](https://github.com/primefaces/primefaces/files/12292166/products.xls)

Issue also appears in PF 13.0.0

### Reproducer

Here is the reproducer using PF 12.0.4
[primefaces-test-export.zip](https://github.com/primefaces/primefaces/files/12292168/primefaces-test-export.zip)

### Expected behavior

XLS export should also show correct value for Date column.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
@jasonex7 is this related to https://github.com/primefaces/primefaces/issues/10404 where it was using the default Excel format?

**Comment by melloware** [comment]
PF 10 was just printing the output string I believe not trying to map it to a real Excel date value. If you don't want this behavior simply disabled `stronglyTypedCells`  see: https://primefaces.github.io/primefaces/13_0_0/#/components/dataexporter?id=customization

Just set ` excelOpt.setStronglyTypedCells(false);` and it will work like PF 10.0.0

**Comment by jasonex7** [comment]
> @jasonex7 is this related to #10404 where it was using the default Excel format?

Yes, it is related to #10404, because stronglyTypedCell see the dd.MM.yyyy format string as a number.

**Comment by melloware** [comment]
@rho66 see my solution above i told you how to fix it with 1 line.

**Comment by rho66** [comment]
@melloware Fixed it like you told:

export.xhtml:
```
<p:commandButton value="XLS" styleClass="mr-2 mb-2">
    <p:dataExporter type="xls" target="products" fileName="products" visibleOnly="true" options="#{exportView.excelOptions}"/>
</p:commandButton>
```

ExportView.java:
```
public ExcelOptions getExcelOptions() {
    ExcelOptions excelOptions = new ExcelOptions();
    excelOptions.setStronglyTypedCells(false);
}
```
