### ISSUE TITLE
AccordionPanel: focus on clicked tab should be the default

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10476]
### Description

The issue I have is also described in https://forum.primefaces.org/viewtopic.php?t=40788.

Actually, PF does not care of focusing a tab which was clicked by the user. That's not good because it's really not user friendly.

### Describe the solution you would like

It should be the default to focus the tab when the user clicks a tab. PF should take care of displaying that element into the view (by auto-focusing). Otherwise **it is not user friendly and against accessibility**.

### Additional context
It's not really a new feature. In my opinion this issue is more of a **bug** because if a user clicks on a tab and the tab doesn't appear in the viewport because it wasn't focused when clicked, the user isn't able to do anything with the content of the clicked tab and needs to focus manually. So this is 2 clicks instead of one (more precisely: one click and one scroll). When a user clicks/activates a tab, he also expects that the activated tab is within his focus.

**Comment by jepsar** [comment]
I just went to [the showcase](https://www.primefaces.org/showcase/ui/panel/accordionPanel.xhtml) clicked a tab and it received focus. Are you asking to scroll the tab contents of the visible tab into view on change?

**Comment by melloware** [comment]
MonkeyPatch:

```js
if (PrimeFaces.widget.AccordionPanel) {
    PrimeFaces.widget.AccordionPanel.prototype.bindEvents = function() {
        var $this = this;

        this.headers.on("mouseover", function() {
            var element = $(this);
            if (!element.hasClass('ui-state-active') && !element.hasClass('ui-state-disabled')) {
                element.addClass('ui-state-hover');
            }
        }).on("mouseout", function() {
            var element = $(this);
            if (!element.hasClass('ui-state-active') && !element.hasClass('ui-state-disabled')) {
                element.removeClass('ui-state-hover');
            }
        }).on("click", function(e) {
            var header = $(this);
            if (!header.hasClass('ui-state-disabled')) {
                var tabIndex = $this.headers.index(element);

                if (header.hasClass('ui-state-active')) {
                    $this.unselect(tabIndex);
                } else {
                    $this.select(tabIndex);
                    header.trigger('focus.accordion');
                    this.scrollIntoView({
                        behavior: "smooth",
                        block: "center",
                        inline: "center"
                    });
                }
            }

            e.preventDefault();
        });

        this.bindKeyEvents();
    }
};
```

**Comment by melloware** [comment]
I actually just made one more fix to the MonkeyPatch if you try it @nimo23 and let me know how you like the behavior.  It scrolls to center of the viewport.

**Comment by melloware** [comment]
Yep I fixed it.

**Comment by melloware** [comment]
Can you try it as I edited above with `nearest` instead of `center` to see if you like that better?
