### ISSUE TITLE
Unsuspecting behavior for unselecting all items of a multiple p:autoComplete

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#1048]
When using a `p:autoComplete` with `multiple="true"`, unselecting the last selected item sets the value to `null` where one would rather suspect an empty list to replace tedious `null` checks with `isEmpty()` checks on lists.

A possible solution would be to replace the beginning of  `AutoCompleteRenderer#getConvertedValue`

``` java
        if(submittedValue == null || submittedValue.equals("")) {
            return null;
        }

        AutoComplete ac = (AutoComplete) component;
```

with the following code

``` java
        final AutoComplete ac = (AutoComplete) component;
        final boolean multiple = ac.isMultiple();

        if (submittedValue == null || submittedValue.equals("")) {
            if (multiple) {
                return new ArrayList();
            } else {
                return null;
            }
        }
```

**Comment by melloware** [comment]
I agree with this change since a few lines later it initializes the list if there was something there.

https://github.com/primefaces/primefaces/blob/c058d0c3729cc9e035ad129e3a74b826137a670b/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java#L719-L721

**Comment by Rapster** [comment]
On a general note, should we return a new instance of ArrayList or use `Collections.emptyList()`?

Lately I took the habit to use the second option

**Comment by ghost** [comment]
@Rapster I don't know the current Primefaces stance towards Java 7+ but the time I created the issue most Primefaces components didn't even use Generics but raw collections instead.
