### ISSUE TITLE
TabView: add `hideable` to hide tab content if its tab is clicked

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10487]
### Description

Actually, we can have a toggleable `p:panel`, which **hides/unhides** the content of the panel:

```
<p:panel header="Header" toggleable="true" widgetVar="panel">
.. 
```

If the panel content is already visible, then the toggle-button **hides** its content after the toggle-button is clicked. If the panel content is hidden, clicking the toggle-button **shows** its content.

Unfortunately we can't add multiple panel contents and bind the content to a toggle id. For such cases, `p:tabView` can be used. Unfortunately, if you click the tab again after viewing its contents, the contents of `p:tabView` cannot be hidden.

### Describe the solution you would like

It would be nice to provide a new property `hideable`, which hides/unhides a tab content after clicking the corresponding tab-button twice, i.e. it behaves the same like a toggable `panel`: If the tab content is already visible, then its tab-button **hides** its content after it is clicked (e.g. by removing the css properties, such as `.ui-tabs-selected .ui-state-active` of the corresponding tab which the hides the tab content) . If the tab content is hidden, clicking the tab-button **shows** its content (by adding its css `.ui-tabs-selected .ui-state-active`). 

	<p:tabView hideable="true">
		<f:facet name="actions">
		    Global actions
		</f:facet>
                <!- when Tab 1 is activated, then it hides Tab 1 after clicking Tab 1 again- ->
		<p:tab title="Tab 1" class="ui-tabs-selected ui-state-active">
		    <p class="m-0">content of Tab 1</p>
		</p:tab>
		<p:tab title="Tab 2">
		    <p class="m-0">content of Tab 2</p>
		</p:tab>
	</p:tabView>

### Additional context

A hideable "tabView" function brings the benefits of a toggable panel to the "tabView" (benefits: reducing information overload, free up space, especially on smaller screens, sensitive tab content can be hidden, etc.).

**Comment by melloware** [comment]
so it hides the whole tab?  How does the user get it back again if they hide the tab?

**Comment by melloware** [comment]
also from a UI/UX point of view I have never seen a TabView act this way so it violates the https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by melloware** [comment]
I will leave it up to other core devs but I am a -1 on this feature for the reason given above.
