### ISSUE TITLE
commandButton: ajax status indicator changes position during rotation

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10483]
### Describe the bug

The ajax status (while activated and visible) is slightly moving its position during its rotation (spinning).

### Reproducer

Look at http://www.primefaces.org:8080/showcase/ui/button/commandButton.xhtml?jfwid=3fdb6 and click (for example) in `"Ajax Disabling and Status Icon"` the button `Keep enabled`

### Expected behavior

Ajax status indicator should not move its position while spinning.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

Firefox 115.0.2

**Comment by stolp** [comment]
I tried to replicate this and can not confirm that there is a problem visible for me.

Can you please retry in a Private Window and reload the page via Ctrl-F5? I suspect there is a browser cache problem involved here.
