### ISSUE TITLE
BlockUI: with `delay` will be activated even after ajax request was finished

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10484]
### Describe the bug

Using a 

`<p:blockUI delay="2000" ..`

works in most cases. However, in relation with a `p:dataTable `and `<p:ajax event="rowSelect"` is does not work as expected, because the `blockUI` is activated even when a row was already selected (i.e. the ajax request completed successfully).

### Reproducer

[primefaces-test-jakarta.zip](https://github.com/primefaces/primefaces/files/12329257/primefaces-test-jakarta.zip)

### Expected behavior

The `blockUI` should **not** be activated if the ajax request was done before the `delay` of the `blockUI`.

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

Firefox 115.0.2

**Comment by melloware** [comment]
Good catch!  Try this patch: 
[pf-10484.zip](https://github.com/primefaces/primefaces/files/12329493/pf-10484.zip)

```js
if (PrimeFaces.widget.BlockUI) {
    PrimeFaces.widget.BlockUI.prototype.show = function(duration) {
        var $this = this;
        if (this.isBlocking()) {
            return;
        }

        var delay = this.cfg.delay || 0;
        this.timeout = setTimeout(function() {
            // #10484: if delayed and AJAX event already finished
            if ($this.cfg.triggers && PrimeFaces.ajax.Queue.isEmpty()) {
                PrimeFaces.warn("BlockUI AJAX event completed before showing the block.");
                return;
            }
            $this.alignOverlay();

            var animated = $this.cfg.animate;
            if (animated)
                $this.blocker.fadeIn(duration);
            else
                $this.blocker.show(duration);

            if ($this.hasContent()) {
                if (animated)
                    $this.content.fadeIn(duration);
                else
                    $this.content.show(duration);
            }

            $this.target.attr('aria-busy', true);
        }, delay);
    }
};
```
