### ISSUE TITLE
AutoComplete: Enable styling of the selected items by a delimiter

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10489]
### Description

I find a good (client side) solution to enable the styling of the selected items in `AutoComplete`.  

If the autoComplete `itemLabel` contains a line break (= `/\n`), then it will be replaced by a `span`-element so that the user is able to style each token within the selected item. For example: `itemLabel="a /\n b /\n c"` will be replaced by 

```
<span class="ui-autocomplete-token-label-1">a</span>
<span class="ui-autocomplete-token-label-2">b</span>
<span class="ui-autocomplete-token-label-3">c</span>
```

I extend `PrimeFaces.widget.AutoComplete.prototype.addItem` to make these changes (look into the reproducer (`webapp/resources/test.js`). 

**Look at the reproducer:**

[primefaces-test-jakarta.zip](https://github.com/primefaces/primefaces/files/12333896/primefaces-test-jakarta.zip)

### Additional context

After this issue is resolved, I will provide a PR so that we can style the selected items by simply putting line break (e.g. "/\n") as a delimiter. This PR will also solve:

- https://github.com/primefaces/primefaces/issues/10470
- https://github.com/primefaces/primefaces/issues/10411
- https://github.com/primefaces/primefaces/issues/1903

since the user is now able to style the selectable elements based on their `span` elements.

**Comment by melloware** [comment]
Chips has a separator character: https://primefaces.github.io/primefaces/13_0_0/#/components/chips?id=chips

I htink it should not be `\n` but more like pipe `|` or semicolon `;` etc.

**Comment by melloware** [comment]
Wait the component already has `ui-autocomplete-token-label` why are you trying to split 1 value into 3?  Just send 3 separate values?

**Comment by melloware** [comment]
Yeah this feels like a hack.

**Comment by melloware** [comment]
Yep I don't like it. Feels like a hack. Feel free to just customize your widget in your project this way but this does not belong in Core PF.

**Comment by jepsar** [comment]
The description of this issue starts with a solution instead of a problem. Can you please explain what it is what you want? The separator thing doesn't look very clean to me.

**Comment by jepsar** [comment]
I don't see an `itemLabel` in PrimeReact, only an `itemTemplate` which is the equivalent of PrimeFaces' custom content via `p:column`.

**Comment by tandraschko** [comment]
i really dont understand it

do we talk about a single autocomplete or multiple?

**Comment by tandraschko** [comment]
ok, just to be sure:
1) the selectable item, in the dropdown, can be configured for custom html content by providing `p:columns` like in the example
2) the selected item, rendered in the input, can NOT contain custom content for now as we just have the `itemLabel` attr

right?
independent if we can this can be implemented easily or not ->
Could we just provide a itemLabel facette, so a user can render custom content there?

**Comment by tandraschko** [comment]
Not an easy task doesnt mean thats impossible, will come back in the other ticket

i will close this ticket with an _BIG_ -1 as we should avoid hacky alternative solutions in frameworks just because noone has enough time/spirit to do
