### ISSUE TITLE
OverlayPanel: autoHide behaves the opposite way

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10495]
### Describe the bug

p:overlayPanel autoHide behaves the oppostive way. For true, it does not autoHide, for false it does. 

### Reproducer

See demo https://www.primefaces.org/showcase/ui/overlay/overlayPanel.xhtml?jfwid=82747

### Expected behavior

It must be the oppostive. For true, it should autoHide, for false it should not. 

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

Firefox 115.0.2

**Comment by melloware** [comment]
Look at #8546

AutoHide false disables the default behavior.

**Comment by melloware** [comment]
Also it has a suite of passing integration tests.  I think it is your misunderstanding of the use case

**Comment by melloware** [comment]
I just tested it. It is working exactly as designed and exactly as described in the ticket.  

Please reread the ticket and it's objective. It also works identical to PrimeReact and PrimeVue feature AutoHide.  

I am not sure what you are not understanding??

**Comment by melloware** [comment]
@nimo23 your understanding is **incorrect**.

PrimeReact has a bug that has been fixed but showcase not updated yet: https://github.com/primefaces/primereact/issues/4604

I can confirm the following: (but first let's get some terminology straight).

**trigger** - This is what triggers the overlay to open on mouseenter and mouseleave.  In this example it is the Input TextBox
**pverlay** - The overlay panel displayed when the `trigger` is entered and left

Now that we have the terminology correct let me update your statements

- If `AutoHide` is **TRUE** and the `trigger` is focused then the overlay is opened, the overlay will be automatically hidden when the focus is outside of the ~~overlay~~ `trigger` !!!  So even if the `overlay` is focused it still CLOSES.
- If `AutoHide` is **FALSE** and the `trigger` is focused then the overlay is opened, the overlay will NOT be hidden ~~and will remain open even when the focus is outside the overlay~~ if the `trigger` or the `overlay` has focus.  If the mouse leaves either the `trigger` or the `overlay` then the overlay is hidden..
