### ISSUE TITLE
ClamDaemonClient.getSocket implementation ignores custom timeout settings

### ISSUE THREAD

**Issue by claudioweiler** [primefaces/primefaces#10492]
### Describe the bug

ClamDaemonClient.getSocket implementation ignores timeout defined through primefaces.virusscan.CLAMAV_TIMEOUT.

https://github.com/primefaces/primefaces/blob/5c854f8f3f5467ad4686e2df836f83fa4f6fa2c9/primefaces/src/main/java/org/primefaces/virusscan/impl/ClamDaemonClient.java#L181C8-L181C8

`new Socket(host, port) ` implementation will try a connect with a default timeout, to use a different timeout, this implementation can be used:

```
protected Socket getSocket() throws IOException {
    Socket socket =  new Socket();
    socket.setSoTimeout(timeout);
    socket.connect(new InetSocketAddress(hostName, port), timeout);
}
```

With this implementation latter calls to `setSoTimeout` can be removed. Or just don't put this call on `getSocket` method.

Obs. This implementation use same timeout on connect and read, but I think that could be a good choice to use a different, smaller, timeout to connect.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
I thought this was fixed for PF 13.0.0 with this ticket: https://github.com/primefaces/primefaces/pull/9438

**Comment by melloware** [comment]
Oh I see it doesn't ignore them it sets them in the read and write operations?

https://github.com/primefaces/primefaces/blob/5c854f8f3f5467ad4686e2df836f83fa4f6fa2c9/primefaces/src/main/java/org/primefaces/virusscan/impl/ClamDaemonClient.java#L131

I am not sure what is not working exactly?

**Comment by melloware** [comment]
Oh I see you are saying connect timeout the read timeouts are working.

**Comment by claudioweiler** [comment]
Exactly @melloware , just connect timeout.
It was to fast!!!

**Comment by melloware** [comment]
got it!  I will put this in 13.0.1
