### ISSUE TITLE
Media component with HTML5 Player

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#105]
Consider using HTML5 player with Media component

**Comment by justin-wesley** [comment]
I would consider raising the priority on this since most modern browsers support this and with the security concerns surrounding Flash, more organizations are dumping the use of Flash.

**Comment by markusg80** [comment]
In my opinion use of flash is death and if you add html5 media support Primefaces will be unbeatable framework also for the future! See also my request #1193

**Comment by tandraschko** [comment]
@Rapster "object" has been chosen as "video" was likely not available at this time. The component is quite old and never got a facelift.
So if you have ideas and time to work on, feel free.

**Comment by Rapster** [comment]
We should discuss what media should support, same as today (audio, video and PDF)? Is it some sort of delegator, encoding the right HTML5 component depending the input?

See https://www.w3schools.com/html/html_media.asp

**Comment by tandraschko** [comment]
I think we just should decide somewhere if object or video is rendered. Maybe it can be handled via type or we need a new flag.

**Comment by melloware** [comment]
@tandraschko @Rapster i think with the recent spat of problems both reported and in the forums with the Media player I think we should create two new components `p:audio` and `p:video` that do the equivalent of each HTML5 tag and that way its not 1 component trying to do everything.  The `<audio>` and `<video>` tags have different properties anyway so i doesn't make sense to mix them.

Then the old PDF functionality doesn't even seems like it works anymore anyway.  Thoughts?

**Comment by markusg80** [comment]
+1

**Comment by tandraschko** [comment]
+1
