### ISSUE TITLE
Datatable Column Filter: Initial value set in view is overwritten

### ISSUE THREAD

**Issue by raphisuter** [primefaces/primefaces#10504]
### Describe the bug

We switched from PF10 to PF12 and found a bug in the datatable column filter using selectOneButton component for filtering.

We set the default value of the filter in the view, but when the selectOneButton component is renderd, the value is overwritten with 'null'. As soon as the filter has been clicked on, it works as intended.

I also tested it in PF13 and there it seems to work again as expected.

### Reproducer

Open start page of primefaces-test repo forked here https://github.com/raphisuter/primefaces-test-datatable-filter using mvn clean jetty:run -Pmyfaces22

### Expected behavior

Default value set in view is applied to component and filter is active on page visit

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

1.8

### Browser(s)

chrome, firefox, edge

**Comment by melloware** [comment]
As you stated it's fixed in 13.0.0 so there is nothing for the community to do here.  You can upgrade to 13 or if you are a PRO subscriber request it for 12.0.x elite release.  It's up to you!

**Comment by raphisuter** [comment]
Hi @melloware 
Thank you for explaining. We had a paid version of PrimeFaces on PF10 but not on PF12 at this point. As we are in the process of upgrading to Jakarta anyway we will consinder updating PrimeFaces to 13 (maybe 14 if released till then).
