### ISSUE TITLE
AutoComplete: child commandLink doesn't invoke action

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#10506]
### Describe the bug

Hi,
I found a bug in PF 13.0.0. It worked with 13.0.0-RC2 but doesn't with final.

We use p:autocomplete component with commandLinks as result items. Those command links doesn't invoke action anymore.

See reproducer below.

DOM in browser with PF 13.0.0-RC2 looks like this:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/7076113e-b47c-4fd0-b0cd-8bbe99fd2402)

DOM in browser with PF 13.0.0 looks like this:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/527b662e-7c7c-4140-8e67-3833f1517f77)

### Reproducer

XHTML:
```
<h:form id="frmTest">
    <p:autoComplete id="autocomplete" var="_resultItem"
                    widgetVar="searchAutocompleteWidgetVar"
                    completeMethod="#{testView.trxSearchAutocomplete}">
      <p:column>
        <p:commandLink action="#{testView.foo()}">
          <h:outputText value="#{_resultItem.name}"/>
        </p:commandLink>
      </p:column>
    </p:autoComplete>
  </h:form>
```

TestView:
```
    private List<TestObject> list;

    @PostConstruct  
    public void init() {
        list = new ArrayList<>(Arrays.asList(
                new TestObject("Thriller", "Michael Jackson", 1982),
                new TestObject("Back in Black", "AC/DC", 1980),
                new TestObject("The Bodyguard", "Whitney Houston", 1992),
                new TestObject("The Dark Side of the Moon", "Pink Floyd", 1973)
        ));
    }

    public List<TestObject> trxSearchAutocomplete(String query) {
        // mock impl
        return list;
    }

    public void foo(){
        System.out.println("Test method invoked");
    }
```

### Expected behavior

I would expect the command link to invoke action as in version 13.0.0-RC2 and versions prior to this.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

8

**Comment by melloware** [comment]
I will investigate

**Comment by melloware** [comment]
Hmmm I am using RC2 and its still not working for me?

Can you try my reproducer: 
[pf-10506.zip](https://github.com/primefaces/primefaces/files/12370858/pf-10506.zip)

**Comment by martin654** [comment]
Hi, I tried your reproducer. I run it using "clean jetty:run -Pmojarra23" and it works without any changes. I can see "Test method invoked" in server log.

Then I changed PF version from PF '13.0.0-RC2' to '13.0.0' and it stops invoking foo() method.

**Comment by martin654** [comment]
Possibly related to https://github.com/primefaces/primefaces/issues/10308 ?

**Comment by melloware** [comment]
It is let me look again I think I know the issue I just couldn't get your reproducer working locally. I will let you know what I find out.

**Comment by melloware** [comment]
I found the issue and will fix it in 13.0.1

**Comment by melloware** [comment]
@martin654 can you try 13.0.1-SNAPSHOT and make sure your issue is fixed.

```xml
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>13.0.1-SNAPSHOT</version>
</dependency>

<repositories>
  <repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshot Repository</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by martin654** [comment]
@melloware Hi, it works with 13.0.1-SNAPSHOT. Thank you!
