### ISSUE TITLE
TreeTable: different behavior of contextMenu with dataTable and treeTable

### ISSUE THREAD

**Issue by mnyakushev** [primefaces/primefaces#10507]
### Describe the bug

I have context menu on dataTable and treeTable.
And I'm want to update context menu content from server before showing. 

Context menu on dataTable works as I expected:
 - user right click on row
 - 'contextMenu' request sent to server
 - response received from server
 - content of context menu updated
 - context menu with new content showed to user

But the behavior of treeTable is different from dataTable:
 - user right click on row
 - context menu with old content showed to user
 - 'contextMenu' request sent to server
 - response received from server
 - content of context menu updated and menu hidden

:exclamation: I added file `my-tree-table.js` with possible solution of this problem to reproducer. You need to uncomment line `<h:outputScript name="my-tree-table.js"/>` in file `test.xhtml` to apply that fix.
All changes in `my-tree-table.js` I copied from [datatable.js](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js)

### Reproducer

[context-menu.zip](https://github.com/primefaces/primefaces/files/12378436/context-menu.zip)

1. Run reproducer and go to test page
2. Open browser console
3. Right click on any row in dataTable. 
You will see updated context menu with one item. Text of that item will be the same as text in table row.
You will see In browser console:
```
start
complete
beforeShow
```
5. Right click on any row in treeTable. 
You will see NOT updated context menu. After a little delay menu will be hidden.
You will see In browser console:
```
beforeShow
start
complete
```

### Expected behavior

It would be great if the behavior of context menu on dataTable and treeTable will be the same.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
@mnyakushev great work!  Yes they should absolutely behave the same way.

**Comment by melloware** [comment]
I will port this fix to 13.0.1
