### ISSUE TITLE
dataTable column sorting sorts another table !

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#1051]
I have written a complex program with 2 ui:repeat embedded.

In deeper ui:repeat, I have a table with some columns sortable.

When I click on column header to sort a specific column, Primefaces sorts and display the rows of first table. The second table has disappears !!!

After a lot of research and debug, I have finally found that this error is linked to Primefaces.

I have also written a very little example to explain this case.

The XTHML file is like this (where PAYS = COUNTRY in french)

``` xhtml
<ui:repeat value="#{testViewController.getPaysList()}" var="oPays" >
    <h:outputText value="#{oPays.getPaysName()}"/>

    <p:panel id="panelPays">

        <ui:repeat value="#{oPays.getCityList()}" var="oCity" >
            <h:outputText value="#{oCity.getCityName()}"/>

            <p:panel id="panelCity">

                <p:dataTable 
                    var="street"
                    value="#{oCity.getStreetList()}"
                    >

                    <p:column headerText="STREET" sortBy="#{street.getStreetName()}">
                        <h:outputText value="#{street.getStreetName()}"/>
                    </p:column>

                </p:dataTable>
            </p:panel>    
        </ui:repeat>    
    </p:panel>    
</ui:repeat>    
```

and here is the Controller code

``` java
package com.mycompany.tlga.web.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import com.mycompany.tlga.postLabelling.dto.City;
import com.mycompany.tlga.postLabelling.dto.Pays;
import com.mycompany.tlga.postLabelling.dto.Street;

@ManagedBean
@ViewScoped
public class TestViewController 
    {
    List<Pays> oPaysList = new ArrayList<Pays>();
    public List<Pays> getPaysList() { return oPaysList; }

    public Street oStreet;
    public Street getStreet() { return oStreet; }
    public void setStreet(Street o) { oStreet = o; }

    @PostConstruct
    public void init()
        {
        Pays oPays;
        City oCity;

        oPaysList.add(new Pays("BELGIQUE"));
        oPays = oPaysList.get(oPaysList.size()-1);

        oPays.getCityList().add(new City("BRUXELLES"));
        oCity = oPays.getCityList().get(oPays.getCityList().size()-1);
        oCity.getStreetList().add(new Street("RUE NEUVE"));
        oCity.getStreetList().add(new Street("PLACE ROGIER"));

        oPaysList.add(new Pays("FRANCE"));
        oPays = oPaysList.get(oPaysList.size()-1);

        oPays.getCityList().add(new City("PARIS"));
        oCity = oPays.getCityList().get(oPays.getCityList().size()-1);
        oCity.getStreetList().add(new Street("RUE DE LA LIBERTE"));
        oCity.getStreetList().add(new Street("AVENUE DES CHAMPS-ELYSEES"));
        oCity.getStreetList().add(new Street("AVENUE MONTAIGNE"));
        oCity.getStreetList().add(new Street("PLACE DE LA CONCORDE"));
        oCity.getStreetList().add(new Street("PLACE VENDOME"));
        oCity.getStreetList().add(new Street("RUE DE RIVOLI"));
        oCity.getStreetList().add(new Street("QUAI D'ORSAY"));
        oCity.getStreetList().add(new Street("CHAMP DE MARS"));
        }

    } // END-OF-CLASS
```

When I click on STREET column on last table that contains 8 rows, Primefaces sorts and displays the 2 rows of first table !!!

I have also try to add h:form tag to contain STREET table but that doesn't correct anything.

I have attached all interesting file to this post. 

I use PrimeFaces 5.3.0 and Mojarra 2.0.0 (Glassfish 3.0).

I think that the problem is in PrimeFaces because the display of HTML page works well before I click on column's header !

[Sort.DataTable.UI.zip](https://github.com/primefaces/primefaces/files/99200/Sort.DataTable.UI.zip)

**Comment by cnsgithub** [comment]
I have noticed many problems while using ui:repeat as well. (And also the new p:repeat). When UI repeat causes trouble i usually use jstl tags, which is evaluated at build time. It may be worth a try for you..

```
.. xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"  ....

<c:forEach items="#{bean.collection}" var="tab">

</c:forEach>
```

**Comment by schlebe** [comment]
Thanks for your help, but I'm actually in Mojara 2.0.2 and there is a big error with c:forEach et c:if tag that prevent me to do the test you propose.

I have also replaced all c:foreach by ui:repeat to allow my program to work fine.
And it is what it is doing since I have no problem to display my page.

The problem is only linked to sorting column. It is why I think that the problem is linked to PrimeFaces that take the bad rows to sort the dataTable.

When I have some times, I will migrate to Glassfish 4.1 to test like you propose.

**Comment by kukel** [comment]
The problem is not only releated to sorting. And did you read about  `p:repeat`? It was mentioned (and several related issues) before you posted this. Please do a little searching upfront

**Comment by schlebe** [comment]
For me the problem is only related to sorting. 
The display of all components is perfect.
I have no crash on sorting column.

I have searched upfront like you propose and I have found nothing !!!

I have searched p:repeat in 5.3 documentation and I have found only 8 ui:repeat 1 no-repeat and nothing about p:repeat !!! This tag doesn't exists ! Where can I find documentation on it ?

AND this is not because problems with ui-repeat are related in others issues that this is not a bug.

For me, this a big SERIOUS bug.

**Comment by cghislai** [comment]
You should inspect your ajax request to make sure the execute and update clientIds point to the correct components. To make sure it works correctly, put an ID manually in all your namingConainers, possibly using the varStatus parameter of your ui:reapeat tags, or using your entities ids. Then make sure to provide an absolute ID for your ajax call:
`<p: ajax process=":myForm:pays_#{oPays.id}:city_#{oCity.id}:dataTable" update=":myForm:pays_#{oPays.id}:city_#{oCity.id}:dataTable"/>`

**Comment by kukel** [comment]
@Schelebe: Following the blog helps... http://blog.primefaces.org/?p=3737. Most of the ui:repeat related issues ARE RELATED... And I nowhere stated it was not a 'bug'. 

Luckily it is finally acknowledged that ui:repeat has issues in general with some PF components (and to an extend it is ui:repeat's fault. Searching should sometimes be done more general, to see if there are 'similar' but not fully identical issues. Identifying patterns, relations and all is what helps things getting priority.

**Comment by schlebe** [comment]
For your information, this bug can be closed ... I think it is linked to Mojarra 2.0.2.
We have migrated from Glassfish 3.0 (Mojarra 2.0.2) to Glassfish 4.1 (Mojarra 2.2.7) and the problem has suddently :-) disappears.

Personnaly, I recommand to PrimeFaces team to write in documentation or Release notes for all 5.x versions in which it is writen that Mojarra 2.2.x is a pre-requisite for PrimeFaces 5.x.

**Comment by kukel** [comment]
2.2.x is not a prerequisite, but if things do not work in a certain mojarra/myfaces version, it is never wrong to update that
