### ISSUE TITLE
The button in not getting populated on click of Add button Edit and cancel buttons are not getting visible

### ISSUE THREAD

**Issue by Prashant-Raghuvanshi** [primefaces/primefaces#10520]
### Describe the bug

On click of Add button Edit and Cancel buttons were populating earlier but after upgrading to primefaces 7 from 6 its not loading

### PrimeFaces edition

None

### PrimeFaces version

7

### JSF implementation

Mojarra

### JSF version

2.1.14

### Java version

11

### Browser(s)

chrome

**Comment by tandraschko** [comment]
we dont support version 6 or 7 anymore
try with 13, if it still doesnt work, please provider a forked primefaces-test reproducer
i will close this issue for now
