### ISSUE TITLE
DataTable: Support p:rowToggle in selenium component

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#10526]
### Description

I have the need to be able to toggle DataTable rows for ITs in our app, currently that's not possible and only [implemented for TreeTables](https://github.com/primefaces/primefaces/blob/68c32573ae2a22e7c0088576798c05119f70eb9f/primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/model/treetable/Row.java#L45)

### Describe the solution you would like

Implement row toggling for DataTables as well and reuse that implementation for TreeTable (TreeTable already inherits from DataTable anyways in selenium components)

### Additional context

I'm already working on implementing this, just opening this issue to document and for reference later on when I'm ready to PR

**Comment by melloware** [comment]
I submitted a PR if you want to review?

**Comment by jungm** [comment]
@melloware I already implemented this myself (but wasn't 100% ready to PR yet) and also added a simple IT to test `p:rowExpansion` in combination with `p:rowToggler`. I've opened my [own PR](https://github.com/primefaces/primefaces/pull/10530) now
