### ISSUE TITLE
With Prime faces 6.2 unable to run with Jakarta EE 9 compatible server (TomEE 9.0.1)

### ISSUE THREAD

**Issue by SangeethaVeeraiyah** [primefaces/primefaces#10524]
### Describe the bug

I tried to use primefaces 6.2 with jarkarta ee 9 compatiable server Apache Tomee 9.1.0 and got the org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.apache.myfaces.webapp.StartupServletContextListener] java.lang.NoClassDefFoundError: javax/faces/application/ResourceHandlerWrapper

With Jakarta EE 9, the namespaces is changed from javax to jakarta. from which version we will have a support for Jakarta EE?

And is primefaces 6.2 compatible with Jakarta Server Faces 3.0? if not is there any workaround to make it support?

### Expected behavior

Prime faces 6.2 should support Jakarta EE version..

### PrimeFaces edition

None

### PrimeFaces version

6.2

### Theme

saga

### JSF implementation

MyFaces

### JSF version

2.0

### Java version

17

### Browser(s)

Chrome

**Comment by melloware** [comment]
6.2 is not compatible with Jakarta  you will need to start with 11.0.0 or higher like..

```xml
