### ISSUE TITLE
FileUpload: sonar vulnerabilities

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10522]
https://sonarcloud.io/project/issues?resolved=false&types=VULNERABILITY&id=org.primefaces%3Aprimefaces&open=AYnBpWp7DdSniu8YOW-R

@Rapster Can you check it it pls?

**Comment by melloware** [comment]
Going to leave this open to check after it runs.  I think it might be false positives as we are defending against it but Sonar can't tell!

**Comment by melloware** [comment]
@Rapster can you check now?  It is saying we are not cleansing `webkitRelativePath` now.  Also the other issue is about the `Socket` I think we can mark that as a false positive as it is only being used in a try with resources.

**Comment by brivalin** [comment]
Any idea about which PF version this vulnerability appeared ?

**Comment by melloware** [comment]
@brivalin Oh no these are brand new in 14.0.0-SNAPSHOT so 13.0.0 is not vulnerable.  It had all the defensive checks these are just sonar warnings.  This is a new WebKitDirectory path which is a special chrome feature for uploading a whole directory but there is no PF public version that has this yet so nothing to worry about.

**Comment by jepsar** [comment]
Looks like it was introduced with https://github.com/primefaces/primefaces/issues/5547

I would not go on whether Sonar did not find it in a previous release as the Sonar rules keep changing over time.

**Comment by melloware** [comment]
@jepsar we fixed it in 13.0.0: https://github.com/primefaces/primefaces/issues/9379

Its just that Sonar can't tell because we do that check in 1 spot in the code way down so its in one unified Spot but Sonar can't detect that so its alerting that it may be a problem but its not.

**Comment by Rapster** [comment]
@melloware I left a comment for you my latest PR. Also not sure how to deal with `FileUploadUtils#getWebKitRelativePath` since it comes from File API and used more as a metadata than a file path...

**Comment by melloware** [comment]
I think we should mark it with the ignore. Because later it is actually handled when you construct the full File() correct?  I think its juts Sonar can't tell that.

**Comment by melloware** [comment]
OK the full Sonar report ran and its still reporting 2 issues which  i don't think are issues. They are false positives because it can't tell they are handled.

**Comment by melloware** [comment]
It looks like all quality gates are passing now: https://sonarcloud.io/summary/new_code?id=org.primefaces%3Aprimefaces
