### ISSUE TITLE
After upgrading to PrimeFaces version 7 from 6 

### ISSUE THREAD

**Issue by Prashant-Raghuvanshi** [primefaces/primefaces#10521]
### Describe the bug

There is a blank space coming above the table after upgrading the primefaces version cant fix it

### PrimeFaces edition

None

### PrimeFaces version

7

### JSF implementation

Mojarra

### JSF version

2.1

### Java version

11

**Comment by tandraschko** [comment]
we dont support version 6 or 7 anymore
try with 13, if it still doesnt work, please provider a forked primefaces-test reproducer
i will close this issue for now
