### ISSUE TITLE
Calendar: Issue with show calendar weeks

### ISSUE THREAD

**Issue by ova2** [primefaces/primefaces#1052]
In the attachment are two files with the displayed calendar weeks. One calendar shows the weeks in the locale "de" (German). Everything is ok. Another calendar shows the weeks in the locale "en" (English). The weeks are not correct. I know, there is a small difference in the weeks for different locales. See the good explanation here: http://www.calendar-week.org/ But the weeks in "en" (also "en_US", "en_UK") are shown wrong.
![kalenderwochen_de](https://cloud.githubusercontent.com/assets/767334/12497466/432b02aa-c09c-11e5-8c1d-73be1a9bfe34.png)
![kalenderwochen_en](https://cloud.githubusercontent.com/assets/767334/12497467/432b9b0c-c09c-11e5-81d0-3131e73e9cf7.png)

**Comment by tandraschko** [comment]
Hi Oleg,
would be great if you could provide a PR!

**Comment by ova2** [comment]
Hi Thomas,

I think this is a problem of jQuery Calendar Widget. Not sure, I can fix this :-). I just created an issue if somebody has the same problem and knows the solution.

**Comment by ova2** [comment]
is an jQuery Calendar bug https://bugs.jqueryui.com/ticket/14907

**Comment by melloware** [comment]
From that ticket:

> This isn't so much a problem with the way iso8601Week calculates dates as it is the way the week number is displayed in its own column on the left side of the calendar when firstDay is set to 0 for Sunday. The ISO 8601 spec says that week numbers start on Monday, so the first day of week 1 in 2016 is Monday the 4th. But there's no good way to display Sunday the 3rd as week 53 and Monday the 4th as week 1, both on the same row. Maybe the showWeek option should be disabled when firstDay is set to 0, or maybe the week number should be displayed in each Monday cell, as Google Calendar does it, instead of in a separate column for the whole row.

**Comment by melloware** [comment]
The fix is going into DatePicker so if you need this feature please use DatePicker and not the JQuery Calendar component.
