### ISSUE TITLE
Switch to Java11 as minimal requirement

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10532]
The EOL of Java8 is already reached but most of the JDK's provide still further support.

The sad thing is that Webdriver-Manager and Selenium forces us to use Java11:
https://www.selenium.dev/blog/2023/java-8-support/

This means we have to upgrade to Java11.

**Comment by tandraschko** [comment]
also see: https://github.com/primefaces/primefaces/issues/10531

**Comment by melloware** [comment]
+1 from me as Checkstyle and Optimizer plug-in are also stuck on their Java8 versions.

**Comment by melloware** [comment]
@tandraschko looks like WebDriver jus treleasted a Java 8 version under pressure from users!

https://github.com/primefaces/primefaces/pull/10540

Should we just stay on 8?

**Comment by tandraschko** [comment]
Selenium will still switch
