### ISSUE TITLE
BlockUI: text input event change and button click in single interaction

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#10533]
### Describe the bug

Hi,
we are using p:blockUI in combination with p:ajaxStatus to fulfill these requirements:
1) show animation (spinning wheel) on each ajax request to the user so he knows that he must wait.
2) block whole page until each ajax request completed so the user cannot interact with the page

Simplified code looks like this:
```
<h:body id="body">
    <p:ajaxStatus onstart="PF('blockOver').show()" oncomplete="PF('blockOver').hide()"/>
    <p:blockUI id="clickShield" styleClass="whole-page-block" block=":body" widgetVar="blockOver" animate="false"/>

    <h:form>
        <p:inputText value="#{testView.string}" >
            <p:ajax event="change" process="@form" update="@form" listener="#{testView.change()}" />
        </p:inputText>
        <p:commandButton process="@form" update="@form" action="#{testView.button()}"/>
    </h:form>
</h:body>
```

```
private String string;

public void change(){
    System.out.println("text change event");
}

public void button(){
    System.out.println("button event");
}
```

**Scenario looks like this:**
User types text into inputText component and then uses mouse to click the button.

**Problem:** 
Only change event is triggered. Button action is not invoked.

**Observation:**
When we use this code instead of combination of ajaxStatus and blockUI, it triggers both actions (change on inputText and action on button):
`<p:ajaxStatus onstart="console.log('blocking starts');" oncomplete="console.log('blocking ends')"/>`
writes this output to console:
```
blocking starts
blocking ends
blocking starts
blocking ends
```
so it can be done without blockUI and works correctly - both actions are invoked.

**2nd observation:**
When user presses enter in the inputText, the default button in form is invoked, which in this case is the same button as button mouse-clicked before and BOTH actions are invoked. Even with blockUI.

I believe that from a user's perspective, it's equivalent whether they press Enter in the input field or click the (default) button with the mouse.
Upon pressing Enter, the change event should be triggered, followed by the button's action in the form (which could be the only button or a defined default command button). This currently works fine, as described in Observation 2.
When clicking the button, the same should happen – first the change event, then the button's action (this is the problematic case which is not correct from our perspective).
As a user, I would expect the same behavior...

Yes, there's a potential issue with updating the button during the processing of the first request (change event of the text input).
In an extreme case, the change event might completely hide the button (setting rendered to false). However, in my opinion, this is a concern for the developer of the specific form.
Nevertheless, this is not a typical use case for reacting to the change event on text input. Furthermore, the same problem exists in both cases (for Enter and button click).

### Reproducer

Code snippets above. Full primefaces reproducer:

[ajaxstatus_vs_onchange_and_button.zip](https://github.com/primefaces/primefaces/files/12405503/ajaxstatus_vs_onchange_and_button.zip)

### Expected behavior

I would expect both events to be triggered. Change event on inputText and action on button.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4 and 13.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

8

**Comment by melloware** [comment]
So to summarize.... when you leave the input text to push the button the blockUI triggers thus blocking the click on the button?

I think this is expected behavior as the behavior and order of events is different.

**Using the mouse to click the button:**
1. Input `change` event fires triggering the BlockUI.
2. Your mouse click on button is intercepted and discarded.

**Using the keyboard to press `ENTER` in the InputText:**
1. Pressing ENTER in Input you have NOT left the field yet I think it clicks the Submit Button triggering the blockUI.
2. Input `change` event is fired.

So I think its actually two different interactions with different behavior.  Is what I have summarized correct?

**Comment by martin654** [comment]
Hi, 

It is more complicated...

### Case A:Without blockUI

**Using the mouse to click the button:**
This is wierd. My observation is that when server freshly restarted it behaves like this.
1. InputText's change event is triggered
2. Button action is triggered
BUT when I add another character in inputText and press button again, only inputText's change event is triggered, button action not. Full page refresh doesn't make it work again.
BUT it is reproduceable again when server restarted. Again, change event on input followed by button action.

I tried this several times to be sure... please try yourself...

**Using the keyboard to press ENTER in the InputText:**
1. Fist, inputText's change event is triggered
4. Button action is triggered


### Case B: WITH blockUI

**Using the mouse to click the button:**
1. inputText's change event is triggered
2. button action NOT triggered

**Using the keyboard to press ENTER in the InputText:**
1. Fist, inputText's change event is triggered
4. Button action is triggered

### Case C: WITH blockUI with altered update in p:ajax
To make it a bit more complicated, try changing p:ajax 'update' to expression that doesn't contain the button:
```
        <p:ajaxStatus onstart="PF('blockOver').show()" oncomplete="PF('blockOver').hide()"/>
        <p:blockUI id="clickShield" styleClass="whole-page-block" block=":body" widgetVar="blockOver" animate="false"/>

        <h:form>
            <p:inputText value="#{testView.string}" id="inputTextId">
                <p:ajax event="change" process="@this" update="@this" listener="#{testView.change()}"/>
            </p:inputText>
            <p:commandButton process="@form" update="@form" action="#{testView.button()}" id="buttonId"/>
        </h:form>
```

**Using the mouse to click the button:**
1. inputText's change event is triggered
2. button action IS triggered

**Using the keyboard to press ENTER in the InputText:**
1. inputText's change event is triggered
2. button action IS triggered


I run the app using clean jetty:run -Pmojarra23

**Comment by melloware** [comment]
I see `update="@form"` is firing the InputTExt change which is wiping out the button from underneath the current execution because its being replaced with a NEW button in the DOM.

**Comment by martin654** [comment]
It doesn't have to be whole form, I think that the problem occurs when button is in the updated scope... It can be just a p:panel with several inputs and a "search" button for example. 
Or there can be cases where you need to update the button (color, text, etc.) on text change.

And then there is the "Enter" scenario which beahves OK. Our customer doesn't see much difference between ENTER and button click. They expect both scenarios to work the same.

The problem is that the developer of the form have to know about this issue and think about it when writing p:ajax for inpuText - no button nearby can be in the update attribute...

**Another scenario**

There is another example, the scenario is similar to the one described above: fill some text and click on one of the radios (selectOneRadio also with ajax):
```
    <h:body id="body">
        <p:ajaxStatus onstart="PF('blockOver').show()" oncomplete="PF('blockOver').hide()"/>
        <p:blockUI id="clickShield" styleClass="whole-page-block" block=":body" widgetVar="blockOver" animate="false"/>

        <h:form>
            <p:inputText value="#{testView.string}" id="inputTextId">
                <p:ajax event="change" process="@this" update="@this" listener="#{testView.change()}"/>
            </p:inputText>
            <p:selectOneRadio value="#{testView.radio}">
                <p:ajax event="change" process="@this" update="@this" listener="#{testView.changeRadio()}"/>
                <f:selectItem itemValue="fooo" itemLabel="fooo"/>
                <f:selectItem itemValue="baar" itemLabel="baar"/>
            </p:selectOneRadio>
            <p:commandButton process="@form" update="@form" action="#{testView.button()}" id="buttonId"/>
        </h:form>
    </h:body>
```

```
@Data
@Named
@ViewScoped
public class TestView implements Serializable {

    private String string;

    private String radio;

    public void change(){
        System.out.println("text change event");
    }

    public void changeRadio(){
        System.out.println("radio change event");
    }

    public void button(){
        System.out.println("button event");
    }
}
```

This time FIRST attempt after server restart is that only inputText change is invoked. Any other attemt results into two requests (inputText change and selectOneRadio change). This can be reproduced after server restart. Tested in chrome and firefox.
This seems related with scenario described above "A:Without blockUI - Using the keyboard to press ENTER in the InputText" but somehow 'reversed'.

**Comment by melloware** [comment]
Yep it wasn't just `@form` it was anything that updates the `button`.

**Comment by melloware** [comment]
Definitely agree this is some weird race condition involving the BlockUI.

**Comment by melloware** [comment]
@martin654 can you try this MonkeyPatched version:

[pf-10533.zip](https://github.com/primefaces/primefaces/files/12409704/pf-10533.zip)

**Comment by martin654** [comment]
@melloware I don't see any difference

**Comment by melloware** [comment]
Hmm it's working for me.  Maybe your machine is a little slower than mine can you make delay="250" on the BlockUi. I set it to 100 which might not be long enough.

**Comment by martin654** [comment]
Interesting... Tried 250 and 1000 and still getting the warn. By the way there was no delay in original example (and in our PROD code). One of the reasons why to use blockUI is to prevent user's double clicks, so we want to block the user immedeately after first clicks.

**Comment by martin654** [comment]
I understand that. But I don't want any delay :). And I tried the delay to give feedback how it works with it...

**Comment by melloware** [comment]
Basically I don't think there is anything PrimeFaces can do to fix your issue the way you are using it.  

The Block UI blocks the button click while it is displayed.  The ENTER key is making it fast enough because its not a two Step mouse interaction where its two distinct actions.

The other thing you can do is turn `global` to false on the `change` event that would also fix your issue. as it would not cause the block UI on change of your input text but only on your button click.

```xml
<p:ajax event="change" process="@this" update="@this" listener="#{testView.change()}" global="false"/>
```
