### ISSUE TITLE
DataTable: Optionally get the SortMeta of sortFunction

### ISSUE THREAD

**Issue by stonewoodman** [primefaces/primefaces#10545]
### Description

I need in sortFunction the info if asc or desc ordering.

### Describe the solution you would like

```
<p:column headerText="Name" 
          sortable="true" 
          sortBy="#{row.name}" 
          sortFunction="#{indexController.onSortValue}">
    <h:outputLabel value="#{row.name}"/>
</p:column>
```

in most cases is this enough
```
    public int onSortValue(Object o1, Object o2) {
        // impl
    }
```

but i have a case, where i need the info if asc or desc
```
    public int onSortValue(Object o1, Object o2, SortMeta sortMeta) {
        // impl
    }
```
example: i want empty (null) values always on top (or bottom), no matter if sorted by asc or desc

**Comment by stonewoodman** [comment]
In my case this line is executed:
`result = (Integer) sortMeta.getFunction().invoke(context.getELContext(), new Object[]{value1, value2});`

i need an custom sort impl, but i don't have the info at that line

**Comment by melloware** [comment]
Ahhh yep I see.  I need to ask @tandraschko how not to make this a breaking change?

**Current:**
```java
 result = (Integer) sortMeta.getFunction().invoke(context.getELContext(), new Object[]{value1, value2});
```

**To:**
```java
 result = (Integer) sortMeta.getFunction().invoke(context.getELContext(), new Object[]{value1, value2, sortMeta});
```

I think anyone using the old `(value1, value2)` signature EL would report method NOT found because there is no match right?   Is there a clever way in EL to try the old way (2 param signature) or the new way (3 param signature)?

**Comment by Rapster** [comment]
You can use `DataTable#getSortByAsMap` and you'll find the corresponding SortMeta
