### ISSUE TITLE
Rating: clear does not work correctly

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#10557]
### Describe the bug

![image](https://github.com/primefaces/primefaces/assets/10051373/d49f3ea9-2909-40fb-9469-ac6e5c5eeca0)

Pressing on the clear icon clears the rating but only on the widget (exactly as on the https://www.primefaces.org/showcase/ui/input/rating.xhtml?jfwid=55d47)

![image](https://github.com/primefaces/primefaces/assets/10051373/672df739-788f-4399-8600-88a1f46299b3)

While in the GUI it looks cleared, the value in the bean stays unchanged.

![image](https://github.com/primefaces/primefaces/assets/10051373/26924d59-0ad0-4bf5-991d-493d44d6647b)

Adding <p:ajax> does not help either. In any case, the corresponding set attribute method of the bean is not invoked when the rating value is cleared.

Thanks in advance for looking into this issue. 

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
Have you tried the `cancel` event.  According to the docs that is what is called when the stars are cleared: https://primefaces.github.io/primefaces/13_0_0/#/components/rating?id=ajax-behavior-events

```xml
 <p:ajax event="cancel" listener="#{ratingBean.handleCancel}" update="msgs" />
```

**Comment by melloware** [comment]
Also as seen on the "Remote" example on the showcase: https://www.primefaces.org/showcase/ui/input/rating.xhtml?jfwid=f3e91

**Comment by melloware** [comment]
I can't reproduce.  Can you provide a primefaces test reproducer?  Your error is not happening for me?

**Comment by tuerker** [comment]
@melloware attached a repoducer which show that the rating component is. i slightly adapted demo example. 

[p-rating.zip](https://github.com/primefaces/primefaces/files/12497505/p-rating.zip)

1) rate first, e.g give 4 stars. 
2) press then on the clear icon. you will see that ratings are cleared on the gui but not in the backing bean. 
3) when you then press on the save button, you would expect that the cleared value is sent to the backing bean, which is not the case. 

So this is really a bug and therefore the issue should be reopened. Of course, you can workaround this bug by placing setRating(null) into the cancel method (just comment out the corresponding line).

The other CSP problem is caused by the context-params:

  <context-param>
    <param-name>primefaces.CSP</param-name>
    <param-value>true</param-value>
  </context-param>
  <context-param>
    <param-name>primefaces.CSP_POLICY</param-name>
    <param-value>worker-src 'self' blob:; frame-ancestors 'none'; script-src 'self' https: *.googleapis.com</param-value>
  </context-param>

When i comment out thse two params, the nonce problem disappears. Unfortunately, i could not reproduce this within the reporducer. So, there must something more in combination which creates this problem.

**Comment by melloware** [comment]
This one is weird.  When I press cancel I can see the value in F12 Network Traffic is "0".

![image](https://github.com/primefaces/primefaces/assets/4399574/18fe9b2c-ec03-4794-8ae7-9aff8aa2d236)

I can then in the debugger see this in RatingRenderer:

```java
        String submittedValue = context.getExternalContext().getRequestParameterMap().get(clientId + "_input");

        if (LangUtils.isNotEmpty(submittedValue)) {
            int submittedStars = Integer.parseInt(submittedValue);
            if (submittedStars == 0) {
                submittedValue = null;
            }
            else if (submittedStars < 1 || submittedStars > rating.getStars()) {
                return;
            }
        }

        rating.setSubmittedValue(submittedValue);
```

I can see == 0 and it getting set to `NULL`.   So up to that point it all looks correct but you are right the value is not being set to NULL it stays its current number.
