### ISSUE TITLE
Ribbon: not assignable to UIComponent exception

### ISSUE THREAD

**Issue by kamel2005** [primefaces/primefaces#10553]
### Describe the bug

Exception Details:
  Location:
    org/primefaces/component/ribbon/RibbonRenderer.encodeTabContent(Ljavax/faces/context/FacesContext;Lorg/primefaces/component/ribbon/Ribbon;Lorg/primefaces/component/tabview/Tab;Z)V @31: invokevirtual
  Reason:
    Type 'org/primefaces/component/ribbon/Ribbon' (current frame, stack[2]) is not assignable to 'javax/faces/component/UIComponent'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'org/primefaces/component/ribbon/RibbonRenderer', 'javax/faces/context/FacesContext', 'org/primefaces/component/ribbon/Ribbon', 'org/primefaces/component/tabview/Tab', integer, 'javax/faces/context/ResponseWriter', 'java/lang/String', integer }
    stack: { 'javax/faces/context/ResponseWriter', 'java/lang/String', 'org/primefaces/component/ribbon/Ribbon' }
  Bytecode:
    0000000: 2bb6 0049 3a05 1504 9900 0812 cfa7 0005
    0000010: 12d1 3a06 2db6 00d2 3607 1905 1263 2cb6
    0000020: 0067 1905 1269 2d2b b600 b601 b600 6d19
    0000030: 0512 6f19 0601 b600 6d15 079e 005d 1905
    0000040: 1288 2cb6 0067 1905 126f 12d4 01b6 006d
    0000050: 2db6 00d5 3a08 0336 0915 0915 07a2 0034
    0000060: 1908 1509 b900 9802 00c0 009a 3a0a 190a
    0000070: c100 d799 0018 190a b600 a099 0010 190a
    0000080: c000 d73a 0b19 0b2b b600 db84 0901 a7ff
    0000090: cb19 0512 88b6 007d 1905 1263 b600 7db1
    00000a0:                                        
  Stackmap Table:
    append_frame(@16,Object[#83])
    same_locals_1_stack_item_frame(@18,Object[#85])
    full_frame(@89,{Object[#2],Object[#69],Object[#27],Object[#156],Integer,Object[#83],Object[#85],Integer,Object[#148],Integer},{})
    same_frame(@139)
    chop_frame(@145,1)
    chop_frame(@152,1)

    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/primefaces/component/ribbon/RibbonRenderer.encodeTabContent(Ljavax/faces/context/FacesContext;Lorg/primefaces/component/ribbon/Ribbon;Lorg/primefaces/component/tabview/Tab;Z)V @31: invokevirtual
  Reason:
    Type 'org/primefaces/component/ribbon/Ribbon' (current frame, stack[2]) is not assignable to 'javax/faces/component/UIComponent'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'org/primefaces/component/ribbon/RibbonRenderer', 'javax/faces/context/FacesContext', 'org/primefaces/component/ribbon/Ribbon', 'org/primefaces/component/tabview/Tab', integer, 'javax/faces/context/ResponseWriter', 'java/lang/String', integer }
    stack: { 'javax/faces/context/ResponseWriter', 'java/lang/String', 'org/primefaces/component/ribbon/Ribbon' }
  Bytecode:
    0000000: 2bb6 0049 3a05 1504 9900 0812 cfa7 0005
    0000010: 12d1 3a06 2db6 00d2 3607 1905 1263 2cb6
    0000020: 0067 1905 1269 2d2b b600 b601 b600 6d19
    0000030: 0512 6f19 0601 b600 6d15 079e 005d 1905
    0000040: 1288 2cb6 0067 1905 126f 12d4 01b6 006d
    0000050: 2db6 00d5 3a08 0336 0915 0915 07a2 0034
    0000060: 1908 1509 b900 9802 00c0 009a 3a0a 190a
    0000070: c100 d799 0018 190a b600 a099 0010 190a
    0000080: c000 d73a 0b19 0b2b b600 db84 0901 a7ff
    0000090: cb19 0512 88b6 007d 1905 1263 b600 7db1
    00000a0:                                        
  Stackmap Table:
    append_frame(@16,Object[#83])
    same_locals_1_stack_item_frame(@18,Object[#85])
    full_frame(@89,{Object[#2],Object[#69],Object[#27],Object[#156],Integer,Object[#83],Object[#85],Integer,Object[#148],Integer},{})
    same_frame(@139)
    chop_frame(@145,1)
    chop_frame(@152,1)

    Caused by: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/primefaces/component/ribbon/RibbonRenderer.encodeTabContent(Ljavax/faces/context/FacesContext;Lorg/primefaces/component/ribbon/Ribbon;Lorg/primefaces/component/tabview/Tab;Z)V @31: invokevirtual
  Reason:
    Type 'org/primefaces/component/ribbon/Ribbon' (current frame, stack[2]) is not assignable to 'javax/faces/component/UIComponent'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'org/primefaces/component/ribbon/RibbonRenderer', 'javax/faces/context/FacesContext', 'org/primefaces/component/ribbon/Ribbon', 'org/primefaces/component/tabview/Tab', integer, 'javax/faces/context/ResponseWriter', 'java/lang/String', integer }
    stack: { 'javax/faces/context/ResponseWriter', 'java/lang/String', 'org/primefaces/component/ribbon/Ribbon' }
  Bytecode:
    0000000: 2bb6 0049 3a05 1504 9900 0812 cfa7 0005
    0000010: 12d1 3a06 2db6 00d2 3607 1905 1263 2cb6
    0000020: 0067 1905 1269 2d2b b600 b601 b600 6d19
    0000030: 0512 6f19 0601 b600 6d15 079e 005d 1905
    0000040: 1288 2cb6 0067 1905 126f 12d4 01b6 006d
    0000050: 2db6 00d5 3a08 0336 0915 0915 07a2 0034
    0000060: 1908 1509 b900 9802 00c0 009a 3a0a 190a
    0000070: c100 d799 0018 190a b600 a099 0010 190a
    0000080: c000 d73a 0b19 0b2b b600 db84 0901 a7ff
    0000090: cb19 0512 88b6 007d 1905 1263 b600 7db1
    00000a0:                                        
  Stackmap Table:
    append_frame(@16,Object[#83])
    same_locals_1_stack_item_frame(@18,Object[#85])
    full_frame(@89,{Object[#2],Object[#69],Object[#27],Object[#156],Integer,Object[#83],Object[#85],Integer,Object[#148],Integer},{})
    same_frame(@139)
    chop_frame(@145,1)
    chop_frame(@152,1)

    Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/primefaces/component/ribbon/RibbonRenderer.encodeTabContent(Ljavax/faces/context/FacesContext;Lorg/primefaces/component/ribbon/Ribbon;Lorg/primefaces/component/tabview/Tab;Z)V @31: invokevirtual
  Reason:
    Type 'org/primefaces/component/ribbon/Ribbon' (current frame, stack[2]) is not assignable to 'javax/faces/component/UIComponent'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'org/primefaces/component/ribbon/RibbonRenderer', 'javax/faces/context/FacesContext', 'org/primefaces/component/ribbon/Ribbon', 'org/primefaces/component/tabview/Tab', integer, 'javax/faces/context/ResponseWriter', 'java/lang/String', integer }
    stack: { 'javax/faces/context/ResponseWriter', 'java/lang/String', 'org/primefaces/component/ribbon/Ribbon' }
  Bytecode:
    0000000: 2bb6 0049 3a05 1504 9900 0812 cfa7 0005
    0000010: 12d1 3a06 2db6 00d2 3607 1905 1263 2cb6
    0000020: 0067 1905 1269 2d2b b600 b601 b600 6d19
    0000030: 0512 6f19 0601 b600 6d15 079e 005d 1905
    0000040: 1288 2cb6 0067 1905 126f 12d4 01b6 006d
    0000050: 2db6 00d5 3a08 0336 0915 0915 07a2 0034
    0000060: 1908 1509 b900 9802 00c0 009a 3a0a 190a
    0000070: c100 d799 0018 190a b600 a099 0010 190a
    0000080: c000 d73a 0b19 0b2b b600 db84 0901 a7ff
    0000090: cb19 0512 88b6 007d 1905 1263 b600 7db1
    00000a0:                                        
  Stackmap Table:
    append_frame(@16,Object[#83])
    same_locals_1_stack_item_frame(@18,Object[#85])
    full_frame(@89,{Object[#2],Object[#69],Object[#27],Object[#156],Integer,Object[#83],Object[#85],Integer,Object[#148],Integer},{})
    same_frame(@139)
    chop_frame(@145,1)
    chop_frame(@152,1)
"}}}}

### PrimeFaces edition

None

### PrimeFaces version

13.0

### Theme

aya

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

17

### Browser(s)

edge

**Comment by Rapster** [comment]
Little effort on format would have been appreciated... Ribbon has been removed in 11.0.0. See https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/11_0_0
