### ISSUE TITLE
Dialog: ui-state-error is not added on inputtext

### ISSUE THREAD

**Issue by kurtomerfaruk** [primefaces/primefaces#10559]
### Describe the bug

Although I add required property to the inputtext in the dialog, it does not add ui-state-error. I did not have such a problem before PrimeFaces 12 and PrimeFaces 13. How should I follow a path about this. When I use it as a Composite Component, it does not add ui-state-error, but when I use it normally in a dialog, ui-state-error is added

### Reproducer

#
[Project](https://github.com/kurtomerfaruk/PrimeFaces-Test)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4.0.3

### Java version

11

### Browser(s)

Chrome 116.0.5845.97

**Comment by melloware** [comment]
Closing in favor of https://github.com/primefaces/primefaces/issues/10552.  Read the issue there
