### ISSUE TITLE
Charts: Configure bar border radius with server API 

### ISSUE THREAD

**Issue by artragis** [primefaces/primefaces#10573]
### Description

Currently (primefaces 13.0.0), when we want to create a `BarChartDataset or `HorizontalBarChartDataset` and want to customize the border radius of bars, we need to create an extender to call the `dataset.borderRadius` attribute of the charts API https://www.chartjs.org/docs/3.9.1/charts/bar.html#borderradius

The goal of this feature proposal is to add the backend API to configure this attribute in Java.
 

### Describe the solution you would like

I would like to be able to do 

```java
BarChartDataSet set = new BarChartDataSet();
set.setBorderRadius(3); // or a list for border radiuses following the chartJS API
```

### Additional context

I will create the PR, you will decide of the desirability of this feature on the basecode. As I said, we have a workaround through the extender function.

**Comment by melloware** [comment]
Thanks for the report and the PR!
