### ISSUE TITLE
Effects not working on calendar date selection

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1057]
Hi,

It seems impossible to show an effect on date selection in p:calendar - could you please check this:

```
<p:calendar value="#{...}">
   <p:effect event="dateSelect" type="pulsate" for="..." />
</p:calendar>
```

`event='click'` fires too early on click at calendar's input field...

Kind regards

**Comment by sudheerj** [comment]
For p:effect compopnent event should be DOM events like click,mouseover etc.dateSelect is just an ajax event from PrimeFaces so it won't work with 'dateSelect' event.

Also this effect will be applied only to the calendar input but not calendar popup.You can't define 'for' attribute for generated popup which doesn't exist as JSF component.

So in this case you can do this,

```
<p:calendar id="event" value="#{calendarView.date}" >
                    <p:ajax event="dateSelect" onstart="$( '#ui-datepicker-div' ).toggle( 'fadeout' );"/>
  </p:calendar>
```

**Comment by cnsgithub** [comment]
Thanks for pointing this out.

Final solution:

```
<p:calendar value="#{...}">
   <p:ajax event="dateSelect" onstart="$(element).stop(true, true).effect('pulsate',{times:2},3000);" />                        </p:calendar>
```

Feel free to close this issue.

**Comment by sudheerj** [comment]
You are welcome.Yes that is pure jquery UI effects with possible options.

**Comment by melloware** [comment]
@Rapster @tandraschko  @cnsgithub mentioned it was safe to close this issue.

**Comment by tandraschko** [comment]
hm? can't remember :D

**Comment by melloware** [comment]
The comment two above @cnsgithub says "Feel free to close this issue.".
