### ISSUE TITLE
Menu : MenuItem oncomplete script is not called if no action is specified

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#10575]
### Describe the bug

Hi !
Since the Primefaces 13 release, if you define a menu with a menuitem with an `oncomplete` script and you don't define a bean `action` method, the `oncomplete` script is not called.

### Reproducer

```
<p:menu>  
    <p:menuitem value="Without action" oncomplete="console.log('Oncomplete not called')" />  
    <p:menuitem value="With action" action="#{testView.init()}" oncomplete="console.log('Oncomplete called')" />  
</p:menu>
```

### Expected behavior

The oncomplete script should be called independently of the action method.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.0 and 14.0.0-SNAPSHOT

### JSF implementation

All

### JSF version

4.0

### Java version

11

### Browser(s)

All

**Comment by tandraschko** [comment]
thats by design
oncomplete only works if the menuItems is submitting (either action or actionListener is defined) and when ajax=true (default)

**Comment by brivalin** [comment]
Doing the same with a commandButton or commandLink for example is already working in PF 13. I think menuitem has a different behaviour now.

We can also imagine some cases where `oncomplete ` is combined with `resetValues` to open a dialog containing a form, only after form has been reset.

**Comment by tandraschko** [comment]
command* is always submitting; menuItems is either command* or just a simple link.

**Comment by melloware** [comment]
I know the issue it's related to being able to open menu item links in a new tab.  

I will find the ticket but it looks like we need to check for more props than just action and listener.

**Comment by tandraschko** [comment]
IMO we should remove all AJAX stuff from menuItem and let allow attaching just p:ajax
SO we have 3 modes:
1) link mode
2) command mode (action or actionListener), always non-ajax
3) ajax mode when f:ajax/p:ajax is attached

everything else is just weird magic

**Comment by melloware** [comment]
It's this one: https://github.com/primefaces/primefaces/issues/4068

**Comment by brivalin** [comment]
A menuitem with the `resetValues` property might be considered as command ?

**Comment by jepsar** [comment]
> It's this one: #4068

But that change is not causing this, right? We just prefixed the onclick there.

**Comment by melloware** [comment]
@jepsar yes I think its this commit: https://github.com/primefaces/primefaces/commit/9d16e0fd0b01257101a0f73297ea3b6abc4a83f2

specifically..

```java
boolean isLink = LangUtils.isNotBlank(menuitem.getUrl()) || LangUtils.isNotBlank(menuitem.getOutcome());
boolean isCommand = LangUtils.isNotBlank(menuitem.getCommand());
if (!isCommand && menuitem instanceof UIMenuItem) {
       UIMenuItem uim = (UIMenuItem) menuitem;
        isCommand = uim.getActionExpression() != null || uim.getActionListeners().length > 0;
}
```

**Comment by melloware** [comment]
@brivalin The workaround for now is to use `listener="#{controller.noop()}"` like you have done.

**Comment by tandraschko** [comment]
decided to close the PR as its currently by design
and we decided in the past to not log warnings for each of those nonsense-combinations

nevertheless i enhanced the code/"submitting" detection a bit

**Comment by melloware** [comment]
Awesome but I didn't see any commit from you?

**Comment by tandraschko** [comment]
here it is :D

**Comment by melloware** [comment]
Fantastic!

**Comment by unkle-jb** [comment]
Just checking, but does this means that now, a menuItem with ajax=true and process=":something" (with no action or listner, but an onClick dialog, for instance) should be ajaxified ? 
That would be nice :)

**Comment by tandraschko** [comment]
yes

**Comment by unkle-jb** [comment]
And available in 13.0.2. Excellent !
Thanks Tandraschko (and Melloware for backport)

**Comment by firsthour** [comment]
I think `DefaultMenuItem.setOncomplete` not firing without an action anymore should be added to the 12 to 13 migration docs (and to use `Onclick` instead). I'm currently updating from 11 to 13 and finding lots of little bits like this that just stop working silently.

Another was `disableOnAjax="false"` is now required on `p:commandButton` where you do something like `onclick="PF('loginButton').disable()"`.

**Comment by melloware** [comment]
@firsthour feel free to submit a PR to update the PF13 migration guide: https://github.com/primefaces/primefaces/blob/master/docs/migrationguide/13_0_0.md

**Comment by melloware** [comment]
Also shouldn't `onclick="PF('loginButton').disable()"` not be an AJAX button it should be `type="button"` so you don't need `disableOnAjax`?  If you are using onClick i don't think you want  it to fire AJAX at all?

**Comment by firsthour** [comment]
> Also shouldn't `onclick="PF('loginButton').disable()"` not be an AJAX button it should be `type="button"` so you don't need `disableOnAjax`? If you are using onClick i don't think you want it to fire AJAX at all?

It looks like this now:

```
<p:commandButton
	id="loginButton"
	value="Log In"
	widgetVar="loginButton"
	onclick="$('.loginButton .ui-button-text').text('Logging in...'); PF('loginButton').disable()"
	actionListener="#{authorizationController.login}"
	update=":loginForm :global:growl"
	styleClass="loginButton globalButton"
	type="submit"
	disableOnAjax="false" />
```

If I change it to `type="button"` it doesn't submit anymore.

**Comment by melloware** [comment]
Ahhh OK yes i thought you were using only `onClick`. Shouldn't you use `onStart` instead of `onClick` ?

**Comment by firsthour** [comment]
Yep that's a little smoother, thanks for the tip.

I'm collecting everything I'm changing for our 11 -> 13 upgrade and will try to make a PR for the docs when it's finished.

Just an aside but changing the default layout of `panelGrid` is causing widespread changes. I ended up creating a facelet tag like below to then swap `p:panelGrid` for our custom `tag:panelGrid`. Though I'm seeing warnings about how that layout is deprecated so we're going to have to figure something out. Maybe this will help someone though:

```
<ui:composition
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:o="http://omnifaces.org/ui">
	
	<o:tagAttribute name="id" />
	
	<p:panelGrid
		id="#{id}"
		layout="tabular"
		columns="#{empty columns ? 0 : columns}"
		style="#{style}"
		styleClass="#{styleClass}">
		
		<ui:insert />
	</p:panelGrid>
</ui:composition>

```

**Comment by melloware** [comment]
I have removed that warning in 13.0.4

**Comment by melloware** [comment]
Actually in 13.0.3: https://github.com/primefaces/primefaces/pull/10911

**Comment by firsthour** [comment]
We're on 13.0.3 and I realized it's actually coming from dataGrid, are these three still planning to be deprecated? They don't affect us personally as much that I know of:

![image](https://github.com/primefaces/primefaces/assets/12001281/d40b8a9b-e91a-4726-97c6-ad7aa0ca3866)

**Comment by melloware** [comment]
Yes only PanelGrid we are leaving as its so widely used but DataGrid and DataView etc you should swithc to a responsive layout!  It actually works better than the TR/TD layout that is deprecated.
