### ISSUE TITLE
CommandButton (and few others). XSS attack via title attribute.

### ISSUE THREAD

**Issue by rabiter** [primefaces/primefaces#10578]
### Describe the bug

Potential for XSS attack via the tooltip of the p:commandButton component. When the button value is empty (for example, when the button only has an icon and a tooltip without text), the following renderer code is used staring from PF13 (CommandButtonRenderer):
```
        if (value == null) {
            //For ScreenReader
            writer.write(getIconOnlyButtonText(title, button.getAriaLabel()));
        }
```

Variable 'title' is not escaped properly and rendered on the page as is. As result having a title set to "<script>alert('XSS')</script>" will execute this script on the page
As a possible fix:
```
        if (value == null) {
            //For ScreenReader
            writer.writeText(getIconOnlyButtonText(title, button.getAriaLabel()), "title");
        }
```

The following components have this issue:

- ButtonRenderer.java
- CommandButtonRenderer.java
- LinkButtonRenderer.java
- MenuButtonRenderer.java
- SelectBooleanButtonRenderer.java
- SpeedDialRenderer.java
- SplitButtonRenderer.java

Reproducer:
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/12498927/primefaces-test-master.zip)

And also, it's strange to declare the getIconOnlyButtonText method in CoreRenderer (though this is not related to the bug, just thinking out loud)

### Reproducer

Just open the page, the JS alert will appear (<p:button title="#{testView.title}" icon="pi pi-check"/>)

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

not relevent

### Java version

not relevant

### Browser(s)

not relevant

**Comment by melloware** [comment]
Excellent. marked this for 13.0.1 and security. Fixing now.

**Comment by melloware** [comment]
PR Submitted.
