### ISSUE TITLE
DataTable: custom filter does not work when set first

### ISSUE THREAD

**Issue by rabiter** [primefaces/primefaces#10584]
### Describe the bug

Reproducible in showcase (starting from PF13):
https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml

Rearrange the columns so that the column with the custom filter is first in the list:
"status name country date activity"

![image](https://github.com/primefaces/primefaces/assets/218450/b75e1681-dc64-4870-8c1f-4ce33f050a37)

The filter for the STATUS column is not working

In short, any custom filter doesn't work if it's in the first column.

UITable#updateFilterByValuesWithFilterRequest:
```
            if (hasCustomFilter) {
                filterValue = ((ValueHolder) filterFacet).getLocalValue(); // returns NULL!!!
            }
```

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

all

**Comment by Rapster** [comment]
It works with first column, but not with a selectOneMenu (I'm actually surprised it works at all the very first time...)

**Comment by melloware** [comment]
Confirmed this was fixed with https://github.com/primefaces/primefaces/pull/10596
