### ISSUE TITLE
Accessibility problem selectCheckboxMenu 

### ISSUE THREAD

**Issue by pedrodelgado81** [primefaces/primefaces#10595]
### Describe the bug

**Primefaces version:** Primefaces 8
**Component:** selectCheckboxMenu 

The accessibility problems occurs when there isn't any element selected. The HTML generated is
`<ul label="selector" class="ui-selectcheckboxmenu-multiple-container ui-widget ui-inputfield ui-state-default ui-corner-all"></ul>`

The accessibility problem indicates that
_"Unordered lists must be identified by the UL element and each of its elements. through LI elements, which **must always appear**.
UL listed items that lack elements should not be used. If at a given time a list is missing elements, so instead of displaying as a list with no children (without LI elements) should be removed from the page."_

### Reproducer

Display a selectCheckboxMenu  without any element selected

### Expected behavior

No create an empty <ul> selector

### PrimeFaces edition

Community

### PrimeFaces version

8.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

### Browser(s)

Chrome, Firefox, Opera, Brave...

**Comment by melloware** [comment]
You can see on the Showcase for 13 it always generates at least 1 `<li>`

```xml
<ul data-label="Please select..." class="ui-selectcheckboxmenu-multiple-container ui-widget ui-inputfield ui-state-default ui-corner-all">
   <li class="ui-selectcheckboxmenu-emptylabel">Please select...</li>
</ul>
```

**Comment by pedrodelgado81** [comment]
Thanks
