### ISSUE TITLE
selectOneMenu: hide no select option not working on first instance

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#10592]
### Describe the bug

https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml?jfwid=95060

the Hide NoSelection Option example 
the drop down in meant to not show the select one option and if you link one of the options and then another eventally the select one option does start to hide but it doesnt hide at first

I've copied the code to my project and i'm seeing the same issue, so if there is a fix then please let me know

### Reproducer

you can see it on the showcase for v13.0.0

### Expected behavior

the select one option to not appear in the drop down at all 

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

All

### JSF version

2.1

### Java version

19

**Comment by melloware** [comment]
The showcase is working correctly.  In that example it dynamically checks and only hides the option once an option is selected.  `hideNoSelectionOption="#{not empty selectOneMenuView.hideNoSelectOption}"`

Just don't do that and say `hideNoSelectionOptions="true"` if you want it always hidden?

**Comment by philpil** [comment]
> The showcase is working correctly. In that example it dynamically checks and only hides the option once an option is selected. `hideNoSelectionOption="#{not empty selectOneMenuView.hideNoSelectOption}"`
> 
> Just don't do that and say `hideNoSelectionOptions="true"` if you want it always hidden?
> 
> Or is there some scenario I am not seeing here that you feel there is a bug?

I removed the hideNoSelectionOption="#{etc}" but kept the hidenoSelectionOptions="true" but my "Select Option" is still showing in the drop down

**Comment by melloware** [comment]
Ok I will check. This sounds like a bug
