### ISSUE TITLE
SEF: implement expression to find components by their id ignoring naming containers

### ISSUE THREAD

**Issue by hurrrrricaaaaane** [primefaces/primefaces#1059]
# {p:component()} loops the tree to find a component with the given id.

Thats a different algorithm then using UIComponent.findComponent which is just searching for the id inside the current UINamingContainer (or using a absolute id).
This allows to update a component without knowing the complete path to the component:
Example:
update="myInput"
instead update=":form:composite1:myInput"

**Comment by tandraschko** [comment]
Hmmm, should be possible easily via custom keyword:
update="@id(myInput)"

But this won't work if a single component is expected (like p:outputLabel "for") as it might return multiple components.
Will think about it.

**Comment by tandraschko** [comment]
I'm not sure if i would use it my application but the implementation was very simple.
Please test it.

Example:
<h:inputText id="myInput"/>
<h:form>
     <h:inputText id="myInput"/>
</h:form>

@id(myInput) will find both inputs.

Note: @id() searches relative to the current component. If you would like to start the search from the root, you can use @root:@id(myInput)
