### ISSUE TITLE
ColorPicker: Submitted value set to converted value.

### ISSUE THREAD

**Issue by jankosd** [primefaces/primefaces#10609]
### Describe the bug

ColorPickerRenderer.decode() sets submitted value to converted value:
`colorPicker.setSubmittedValue(ComponentUtils.getConvertedValue(context, component, submittedValue))`

This causes problems when using a converter: getAsObject() is called twice, first time with correct (submitted) value and second time with already converted value.

Obviously, converter can be made to work around this, but I doubt this is expected behaviour.

### Reproducer

https://github.com/primefaces/primefaces/files/12552676/pf-10609.zip

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4.0.3

### Java version

17

**Comment by melloware** [comment]
I have confirmed this with this reproducer:
[pf-10609.zip](https://github.com/primefaces/primefaces/files/12552676/pf-10609.zip)
