### ISSUE TITLE
InputNumber: Does not work correctly when minValue>0 or maxValue<0

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#10607]
### Describe the bug

Whenever you use two positive (or negative) numbers for minValue and maxValue, then the inputNumber component does not work correctly anymore. 

![image](https://github.com/primefaces/primefaces/assets/10051373/f2fdb4e4-60bd-4e4d-bd84-2a4f5a2937c8)

Here is a reproducer:

[p-inputNumber-3.zip](https://github.com/primefaces/primefaces/files/12538767/p-inputNumber-3.zip)

Some while ago, I created an issue on that topic in a little different context (see https://github.com/primefaces/primefaces/issues/9732). Since i had already forgotten that, I was fallen over it again.

Would be great if this problem could be fixed. 

PF should at least clearly document this problem here: https://primefaces.github.io/primefaces/13_0_0/#/components/inputnumber. There only the working case is shown.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by jepsar** [comment]
Isn't this a locale issue?

**Comment by tuerker** [comment]
i improved the reproducer such that it is obvious that the problem occurs whenever minValue>0 or maxValue<0.

![image](https://github.com/primefaces/primefaces/assets/10051373/43f3c066-5e8f-4193-b0ae-61fae85791d0)

[p-inputNumber-3.zip](https://github.com/primefaces/primefaces/files/12539048/p-inputNumber-3.zip)

**Comment by tuerker** [comment]
> Isn't this a locale issue?

@jepsar i don't think so but what you are targeting at?

**Comment by tuerker** [comment]
> > Isn't this a locale issue?
> 
> @jepsar i don't think so but what you are targeting at?

@jepsar would be great if you can run the reproducer and verify this issue. thanks in advance.

**Comment by melloware** [comment]
@tuerker isn't this the Autonumeric limitation with minValue>0 that has been discussed many times in the past: https://github.com/primefaces/primefaces/issues/8125

autoNumeric issue with minValue>0: https://github.com/autoNumeric/autoNumeric/issues/543

**Comment by melloware** [comment]
Its hard for AutoNumeric to solve as you have seen. If you really want this buggy behavior you can simply turn off the invalid.  See if you like what happens without this any better.  Most users don't because it won't let them delete "1".

Running example: 
[pf-10607.zip](https://github.com/primefaces/primefaces/files/12542356/pf-10607.zip)

MonkeyPatch:
```js
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        this.input = $(this.jqId + '_input');
        this.hiddenInput = $(this.jqId + '_hinput');
        this.plugOptArray = cfg.pluginOptions;
        this.initialValue = cfg.valueToRender;
        this.disabled = cfg.disabled;


        //bind events if not disabled
        if (this.disabled) {
            this.input.attr("disabled", "disabled");
            this.input.addClass("ui-state-disabled");
            this.hiddenInput.attr("disabled", "disabled");
        }

        //Visual effects
        PrimeFaces.skinInput(this.input);

        this.autonumeric = new AutoNumeric(this.jqId + '_input', this.cfg);

        if (this.initialValue !== "") {
            //set the value to the input the plugin will format it.
            this.autonumeric.set(this.initialValue);
            // GitHub #6940 blur firing too many change events
            this.autonumeric.rawValueOnFocus = this.initialValue;
        }

        this.setValueToHiddenInput(this.getValue());

        //pfs metadata
        this.input.data(PrimeFaces.CLIENT_ID_DATA, this.id);
        this.hiddenInput.data(PrimeFaces.CLIENT_ID_DATA, this.id);

        // GitHub #10046 delay registering events until CSP has registered
        var $this = this;
        PrimeFaces.queueTask(function() {
            $this.wrapEvents();
        });
    }
}
```

**Comment by tuerker** [comment]
@melloware many thanks for your response. I agree that this buggy behavior is not the goal at all. You should be able to enter all valid numbers but when you have eventually fully entered an invalid number, which is currently not prevented by autonumeric, then it should at least provide a warning that the entered number is invalid.

I am aware of the problem autonumeric faces. In the described scenarios (minValue>0 or maxValue<0) you cannot immediately decide whether the entered number will finally lead to a valid or invalid number. Entering another digit could make a currently invalid number a valid one. Actually, you can only provide a conclusive statement on the validity when it is clear that the number entered so far cannot get invalid anymore by entering any further digits. Consequently, in certain cases, you can only decide when the entire number has been entered. So autonumeric must detect (assume) when the number entering is done. 

A possible solution could look as follows: The inputNumber gets an additional attribute "keyPressTimeout (default=2 seconds for instance)" to "assume" when the number is fully entered. When keyPressTimeout, then an extended validity check is triggered. In case an invalid number is detected, there are different options how to continue with the entered number: 

1) clear -> default case; maybe even the only option which is done by default

2) set to maxValue

3) set to minValue

In any case, these options should ideally be combined with a message that the entered number was invalid and thus cleared/settomax/settomin.

What do you think?

**Comment by tandraschko** [comment]
why not just use f:validateNumber or CSV?

**Comment by tandraschko** [comment]
i dont think we should workaround autonumeric here

**Comment by tuerker** [comment]
> f:validateNumber

I am aware of f:convertNumber but there is no f:validateNumber.

**Comment by tandraschko** [comment]
f:validateLength

**Comment by tuerker** [comment]
> i dont think we should workaround autonumeric here

when i look into PF code, there is already a workaround to fix certain issues:

agreed but autonumeric should fix this, i.e., provide a mean to correctly in principle agreed. we should document first

> f:validateLength

will not be sufficient to validate min/max values.

**Comment by tandraschko** [comment]
then take DoubleRangeValidator ;)

**Comment by tuerker** [comment]
> i dont think we should workaround autonumeric here

when i look into PF code, there is already a workaround to fix certain issues, e.g.:

```
        // GitHub #8125 minValue>0 shows js warning and quirky behavior
        if (this.cfg.minimumValue > 0.0000001 || this.cfg.maximumValue < 0) {
            this.cfg.overrideMinMaxLimits = 'invalid';
        }

```

**Comment by tandraschko** [comment]
yeah, that was a fail to workaround this, it would be better to remove min/max completely
every user is just confused as it doesnt work as expected

validation in PF/JSF is done in a completely different way, which just works fine on server and client

**Comment by tuerker** [comment]
As said before, PF should at least document the inputNumber component in more detail such that every user knows how the component is actually working. It must be clear that the entering of invalid values are not prevented when minValue>0 or maxValue<0 is used. Then, everybody can implement on top validators as needed.

**Comment by melloware** [comment]
I use inputnumber and min and max work great except THIS specific scenario of min=1.  I don't want to pull the functionality out becuase its great UI/UX for users to not be able to enter a number they shouldn't enter without CSV or AJAX call to tell them that.

I think I will add warnings to the docs.

Remember also when submitting the number it is also defended in the `decode`.

```java
try {
            if (LangUtils.isBlank(submittedValue)) {
                Class<?> type = getTypeFromValueExpression(context, inputNumber);
                if (type != null && type.isPrimitive() && LangUtils.isNotBlank(inputNumber.getMinValue())) {
                    // avoid coercion of null or empty string to 0 which may be out of [minValue, maxValue] range
                    submittedValue = String.valueOf(new BigDecimal(inputNumber.getMinValue()).doubleValue());
                }
                else if (type != null && type.isPrimitive() && LangUtils.isNotBlank(inputNumber.getMaxValue())) {
                    // avoid coercion of null or empty string to 0 which may be out of [minValue, maxValue] range
                    submittedValue = String.valueOf(new BigDecimal(inputNumber.getMaxValue()).doubleValue());
                }
            }
            else {
                // Coerce submittedValue to (effective) range of [minValue, maxValue]
                BigDecimal value = new BigDecimal(submittedValue);
                submittedValue = coerceValueInRange(value, inputNumber).toString();
            }
        }
        catch (NumberFormatException ex) {
            throw new FacesException("Invalid number", ex);
        }
```

So there is NO way you are getting an invalid number in your system when using `min` or `max`.

**Comment by tuerker** [comment]
@melloware i am fully inline with you. the functionality is great. one has just to be aware of its limits.

@tandraschko 
> then take DoubleRangeValidator ;) it jsut doesnt matter, you can create your own converter in 2 min anyway.

as usual, none of these things are such short min issues. in my case i added the following to the inputNumber component (this addition can actually be done 2 min):
 
`      <f:validateDoubleRange minimum="#{entity.question.feedbackQuestionType.minValue}" maximum="#{entity.question.feedbackQuestionType.maxValue}" />`

but now the trouble begins. validateDoubleRange does set the min/max correctly (see also here: https://stackoverflow.com/questions/7445417/why-does-fvalidatedoublerange-only-work-for-sessionscoped). they are simply set to 0. so, in this case, it is not a helpful solution.

**Comment by tandraschko** [comment]
yeah, dynamic values are a problem: https://github.com/jakartaee/faces/issues/1499

**Comment by tuerker** [comment]
> yeah, dynamic values are a problem: [jakartaee/faces#1499](https://github.com/jakartaee/faces/issues/1499) OmniFaces has a workaround for this: https://showcase.omnifaces.org/taghandlers/validator

@tandraschko many thanks for the hint to this useful feature of omnifaces.

**Comment by melloware** [comment]
![image](https://github.com/primefaces/primefaces/assets/4399574/2e71ffcc-a020-43da-ac6f-07d94e855443)

Warning banner in the docs now.
