### ISSUE TITLE
PanelGrid: 5 columns not allowed

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#10603]
### Describe the bug

Hi, 
we used to use p:panelGrid with 5 colums with PF 12. It doesn't work with version 13 anymore because of this check: https://github.com/primefaces/primefaces/issues/9817

We have ~15 occurences in our PROD app.

### Reproducer

<p:panelGrid columns="5" layout="flex"columnClasses="col-12 lg:col-6 xl:col-4, col-12 lg:col-4 xl:col-2, col-12 lg:col-4 xl:col-2, col-12 lg:col-4 xl:col-2, col-12 lg:col-4 xl:col-2">
   ...
</p:panelGrid>

### Expected behavior

I think that it should allow 5 columns with use defined columnClasses, especially when there are 5 items in columnClasses attribute.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

17

**Comment by jepsar** [comment]
layout="grid" or "layout="flex" require columns to be a number that factors into 12. For example: 1,2,3,4,6,12

See https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/13_0_0?id=panelgrid
