### ISSUE TITLE
DataExporter: RowToggler exported to xlsx

### ISSUE THREAD

**Issue by mnyakushev** [primefaces/primefaces#10615]
### Describe the bug

All elements inside p:column exported in xlsx. RowToggler in xlsx file looks bad.

I noticed that after exporting dataTable to xlsx, some elements in the downloaded file look bad.
1. RowToggler exported as output of `Object::toString` method
2. Comment exported as is
3. UIInstructions exported as html tags
4. PassthroughElement exported as output of `Object::toString` method

I can delete comments from columns.
I can replace UIInstructions and PassthroughElements with custom components that implemets ValueHolder.
But I can't fix RowToggler export without overriding primefaces classes.

I suggest export empty string for RowToggler. 
This can be achieved by adding logic for RowToggler to the method `getComponentValue` of class `org.primefaces.component.export.ExporterUtils`

Something like this 
```
else if (component instanceof RowToggler) {
    return Constants.EMPTY_STRING;
}
```

### Reproducer

[export-to-excel-row-toggler.zip](https://github.com/primefaces/primefaces/files/12557927/export-to-excel-row-toggler.zip)

1. Open test app
2. Press XLSX button

### Expected behavior

Xlsx file should not contain strings like 'org.primefaces.component.rowtoggler.RowToggler@6644e325'

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
I usually just do 

```xml
<p:rowToggler exportable="false" />
```

**Comment by mnyakushev** [comment]
In production I have RowToggler and text content in one column. And I have borders around table cells. Because of this I can't use exportable="false" on column. I can probably use exportFunction but ignoring RowToggler will be better in my opinion.

**Comment by mnyakushev** [comment]
I can make pull request if you agree with my changes

**Comment by melloware** [comment]
Yes please submit a PR!
