### ISSUE TITLE
Messages: design error on close button

### ISSUE THREAD

**Issue by wbss1** [primefaces/primefaces#10636]
### Describe the bug

Hello, I noticed that with all the free themes with PrimeOne design, there is a visual error with the component messages. Setting closable="true" and using different FacesMessage.SEVERITY creates problems with the desgin of close button. It's drawn only on the first message.
The problem is in this css line:
```
body .ui-messages .ui-messages-close {
position: absolute
}
```

### Reproducer

[pf-test.zip](https://github.com/primefaces/primefaces/files/12576492/pf-test.zip)
![Screenshot_2](https://github.com/primefaces/primefaces/assets/100421074/507269a7-b806-4ba2-80ee-e925456abd0f)
![Screenshot_3](https://github.com/primefaces/primefaces/assets/100421074/54a72f83-221b-47b8-9dae-19a6ad174a83)

### Expected behavior

Close button on each message

### PrimeFaces edition

Elite

### PrimeFaces version

10.0.0 and later

### Theme

All PrimeOne theme since 10.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All browser

**Comment by melloware** [comment]
added theme issue: https://github.com/primefaces/primefaces-sass-theme/issues/20
