### ISSUE TITLE
DataView: Data view not loading in tabview under tabs , when there is <p:dataViewListItem> element available

### ISSUE THREAD

**Issue by yussufsharief** [primefaces/primefaces#10631]
### Describe the bug

I am using primefaces 8.0, I need to have dataview component in the tabview under each tab, when I place dataview component under tabs, it only loads in the first tab, and I am not seeing anything on other tabs.

my findings are 
1. Dataview has 2 elements <p:dataViewGridItem>,<p:dataViewListItem>, now When I remove the <p:dataViewListItem> element from the dataview, I am able to see the dataview in all the tabs. I have also used the style that is provided in the demo but nothing happens.
2. When both elements  <p:dataViewGridItem>,<p:dataViewListItem> are present in the xhtml the tabs are not rendering the dataview component correctly, in the ui it will build a **ui-tabs-panel** tag under that it should have individual elements for respective tabs. But in the attached image you can see the second element which belongs to the second tab was squashed under the first tab element.

For now, I am using the grid layout instead of the List layout. I need a solution for this, please help me out.

![image](https://github.com/primefaces/primefaces/assets/22252036/82f43f53-bdae-4ea1-9bab-cc93c9323872)

### PrimeFaces edition

Community

### PrimeFaces version

8.0

### Theme

eucador

### JSF implementation

All

### JSF version

2.2

### Java version

17

**Comment by tandraschko** [comment]
Does it work on 13?
Otherwise pls provide a reproducer

**Comment by yussufsharief** [comment]
Yes, it is working on Primefaces 13 and also for 8, I am working on the lowcode platform(Skyve) and it is offering primefaces v8.0. I created the sample projects for the 13 and 8 versions locally using spring-boot, jsf,  and I am able to see the dataview correctly in the tabs, i should have done this first. Anyway, while testing I didn't integrate the Ecuador theme in my local. I think the problem is with my low code platform.
