### ISSUE TITLE
DatePicker: cannot have preset dates in the value list if selectionMode=multiple

### ISSUE THREAD

**Issue by fed-dessi** [primefaces/primefaces#10645]
### Describe the bug

Hello,
I'm currently migrating from Primefaces 12 to Primefaces 13 and the datepickers in my web app are now not working.
I currently populate the datepickers with preset multiple dates in a p:datepicker with selectionMode=multiple based on various factors but while in PF12 this was fine and worked in PF13 it's giving javascript errors.

While debugging the javascript code for datepicker.js I've noticed that in the _setInitValues function the value for this.options.viewDate is already set for PF13 which makes the ternary operator logic in the method evaluate the first method and assigning an array value to this.viewDate instead of a Date object. The method then returns an error because it tries to call Date methods on an array and breaks the web app.
In PF12 the value of this.options.viewDate was set to null when the _setInitValues function was called and thus the ternary operator correctly evaluated the variable as an array and assigned a[0] to this.viewDate.

I've tried reproducing the error with the test project by simply adding a datepicker with selectionMode=multiple and connecting it with a List<Date> variable in the bean. 

The issue presents it self even if the list only has 1 date instead of 1+.

### Reproducer

[primefaces-test-13.0.0.zip](https://github.com/primefaces/primefaces/files/12585758/primefaces-test-13.0.0.zip)

### Expected behavior

The _setInitValues function in datepicker.js should correctly pick the first value of an array if the connected bean list value is already populated.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

**Comment by melloware** [comment]
Thanks for the reproducer. I see the error and I am investigating.

**Comment by melloware** [comment]
Here is a monkeypatched version if you want to try it: 
[pf-10645.zip](https://github.com/primefaces/primefaces/files/12586232/pf-10645.zip)


```js
/* Place any Javascript here you want loaded in test.xhtml */
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype._setInitValues = function() {
        if (this.options.userLocale && typeof this.options.userLocale === 'object') {
            $.extend(this.options.locale, this.options.userLocale);
        }

        if (this.options.showWeek && !this.options.weekCalculator) {
            this.options.weekCalculator = this.calculateWeekNumber.bind(this);

            // initialize the potentially missing firstDayWeekOffset option
            // based on the firstDay(OfWeek) option:
            //  - firstDay = saturday => firstDayWeekOffset = 12
            //  - firstDay = sunday => firstDayWeekOffset = 6
            //  - firstDay = monday (ISO8601) => firstDayWeekOffset = 4
            //
            // those defaults are based on the locales on the library
            // moment.js and won't be correct for _all_ locales.
            var sundayIndex = this.getSundayIndex();
            if (this.options.locale.firstDayWeekOffset === undefined) {
                if (sundayIndex == 0) {
                    this.options.locale.firstDayWeekOffset = 6;
                } else if (sundayIndex == 1) {
                    this.options.locale.firstDayWeekOffset = 12;
                } else if (sundayIndex == 6) {
                    this.options.locale.firstDayWeekOffset = 4;
                } else {
                    this.options.showWeek = false;
                }
            }
        }

        var parsedDefaultDate = this.parseValue(this.options.defaultDate);

        var viewDateDefaultsToNow = false;

        this.value = parsedDefaultDate;
        if (this.options.viewDate) {
            this.viewDate = this.parseValue(this.options.viewDate);
            if (!this.viewDate) {
                this.viewDate = new Date();
            }
        } else {
            if ((this.isMultipleSelection() || this.isRangeSelection()) && parsedDefaultDate instanceof Array) {
                this.viewDate = parsedDefaultDate[0];
            } else {
                this.viewDate = parsedDefaultDate;
            }
            if (this.viewDate === null) {
                this.viewDate = new Date();
                if (!this.options.showSeconds && !this.options.showMilliseconds) {
                    this.viewDate.setSeconds(0);
                }
                if (!this.options.showMilliseconds) {
                    this.viewDate.setMilliseconds(0);
                }
                viewDateDefaultsToNow = true;
            }
        }

        // #6047 round to nearest stepMinute on even if editing using keyboard
        this.viewDate = this.isDate(this.viewDate) ? new Date(this.viewDate) : new Date();
        this.viewDate.setMinutes(this.stepMinute(this.viewDate.getMinutes()));
        if (!this.options.viewDate) {
            this.options.viewDate = this.viewDate;
        }

        this.options.minDate = this.parseMinMaxValue(this.options.minDate);
        this.options.maxDate = this.parseMinMaxValue(this.options.maxDate);
        this.ticksTo1970 = (((1970 - 1) * 365 + Math.floor(1970 / 4) - Math.floor(1970 / 100) + Math.floor(1970 / 400)) * 24 * 60 * 60 * 10000000);

        if (viewDateDefaultsToNow) {
            if (this.options.minDate) {
                if (this.viewDate < this.options.minDate) {
                    this.viewDate = new Date(this.options.minDate.getTime());
                }
            }
            if (this.options.maxDate) {
                if (this.viewDate > this.options.maxDate) {
                    this.viewDate = new Date(this.options.maxDate.getTime());
                }
            }
        }

        this.hasCustomYearRange = this.options.yearRange !== null;
        this.updateYearNavigator();

        if (this.options.disabledDates) {
            for (var i = 0; i < this.options.disabledDates.length; i++) {
                this.options.disabledDates[i] = this.parseOptionValue(this.options.disabledDates[i]);
            }
        }
        this.bindResponsiveResizeListener();
    };
};
```

**Comment by fed-dessi** [comment]
@melloware I've tried the code you've sent and it does work but with this fix you lose the information already present in the array.
What about adding a check for the type of instance of "parsedDefaultDate" in the following if:

`
    this.value = parsedDefaultDate;
    if (this.options.viewDate && !(parsedDefaultDate instanceof Array)) {
        this.viewDate = this.parseValue(this.options.viewDate);
        if (!this.viewDate) {
            this.viewDate = new Date();
        }
    }
` 

We know that the values of parsedDefaultState can be one of null, a String containing a formatted date or an array of Strings of formatted dates. I've tested it out and this way we don't lose the information already placed inside the array if for example the first date is a date different than the current day

**Comment by melloware** [comment]
OK see the PR: https://github.com/primefaces/primefaces/pull/10651
