### ISSUE TITLE
Picklist: Localized component is not testable

### ISSUE THREAD

**Issue by Charriu83** [primefaces/primefaces#10646]
### Describe the bug

We want to test a view with two p:pickList components on it with the primefaces-selenium library. Sadly the functions _pick()_, _pickAll()_, _remove()_ and _removeAll()_ failing with an error message:

`No such element found for button[title='Add']`

This obviously work for the show case project, where the buttons were not localized and are named like 'All', 'Add all', and so on. But localized buttons are not found. For localization we used the p:pickList parameters _addLabel_, _addAllLabel_, _removeLabel_ and _removeAllLabel_.

The buttons have already a unique styleclass, which will be much more suitable to find the buttons, even when localized.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

**Comment by melloware** [comment]
Looks like there is not much to work with currently as all 4 of those buttons are the same minus their icons and their text.

![image](https://github.com/primefaces/primefaces/assets/4399574/af974073-36b9-402c-ab83-87dec30faa41)

**Comment by melloware** [comment]
Actually it looks like we should be able to use the UI Class `ui-picklist-button-add` for example.

**Comment by melloware** [comment]
I can only control 13.X as this is the community tracker to request it for 12.X you can do so through your PRO account if you have one.
