### ISSUE TITLE
ImportEnum: with underscores not working

### ISSUE THREAD

**Issue by horstLei** [primefaces/primefaces#10642]
### Describe the bug

Current a enum with underscores in it will be scrambled to a part of it example: detail TestEnum has a constant TEST_A. which is afterwards requested on the enumhashmap with A only which clearly is not found...
[reproducer
](https://github.com/horstLei/primefaces-test.git)

### Reproducer

clone the test project
change to prime faces-test
mvn clean jetty:run -Pmojarra23 
open page: http://localhost:8080/primefaces-test/
you will get an error with Class org.primefaces.test.TestEnum does not contain the enum A
look inside org.primefaces.test.TestEnum which contains
public enum TestEnum {
    TEST_A,
    TEST_B,
    TEST_C;
}

### Expected behavior

the enum should be found (as defined in the specs of java with:  _ uppercase / lowercase letters)
needed for p:importEnum with object.enum eq TestEnum.TEST_A checks... 

Constants of java
The names of variables declared class constants and of ANSI constants should be all uppercase with words separated by underscores ("_"). (ANSI constants should be avoided, for ease of debugging.)

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

no matter which one

**Comment by melloware** [comment]
IF I change your code to this it works.

```xml
<h:form id="frmTest">
            #{TestEnum} / #{testView.myEnum eq TestEnum.TEST_A} / #{testView.myEnum eq TestEnum.TEST_B}
        </h:form>
```

Where did you see you could use `TestEnum.A` instead of the proper `TestEnum.TEST_A` ???

**Comment by horstLei** [comment]
What the hell … my fault 

Ok than its clear / then I have to debug the big project I’m working on there it is not working we have also underscores and the eq evaluation is not returning anything also the values

Sorry for inconvenience


Br horst
