### ISSUE TITLE
DataExporter: OOM error as it's trying to load everything at once

### ISSUE THREAD

**Issue by jasonex7** [primefaces/primefaces#10656]
### Description

LazyDataModel allows a DataExporter or another external component could request to load all rows in memory which could lead to `java.lang.OutOfMemoryError: Java heap space`. I think the spirit of using LazyDataModel is to avoid load all rows in memory in first place, so it should be a mechanism to limit the rows could be loaded into memory. 

### Describe the solution you would like

Add a private field to LazyDataModel class to limit the number of rows could be loaded into memory. Maybe set a default value and allow the user could change if needed. I'm going to submit a PR for this.

**Comment by Rapster** [comment]
I never had this issue before, your problem might be somewhere else

**Comment by melloware** [comment]
I have not either do you have a use case for us to look at?

**Comment by Rapster** [comment]
And tbh, what you're looking for is basically `DataTable#rows`

**Comment by jasonex7** [comment]
I attach a simple reproducer. In DataTable the pagination goes normal as expected only load 10 rows at a time, but when exporting to excel, DataTableExporter loads all rows (50,000 in the reproducer) and could lead to OOME.

![lazydatamodel_overflow_dataexporter](https://github.com/primefaces/primefaces/assets/16229253/9804c3e0-540e-41f9-a860-dd4069fee555)


[primefaces-test.zip](https://github.com/primefaces/primefaces/files/12591472/primefaces-test.zip)

**Comment by Rapster** [comment]
I guess some profiling is required to see where it comes from exactly then

**Comment by jasonex7** [comment]
Sure, I've already do the profiling and then I realize that DataTableExporter loads all rows in memory and cause OOME in some of my apps.

**Comment by melloware** [comment]
I thought XlSXstream only
Loaded and discarded 3 rows at a time.

**Comment by Rapster** [comment]
Ok got it, the issue is there in DataExporter:

```java
if (rowCount > 0) {
     table.setFirst(0);
     table.setRows(rowCount);
     table.loadLazyDataIfEnabled();
}
```

Therefore, your sample tries to load 50000 items at once... Not sure why it's been implemented this way, instead of loading chunk of "rows" items

**Comment by Rapster** [comment]
I made a PR to give you an idea what it should look like

**Comment by Rapster** [comment]
Feel free to try with the latest snapshot 😉

**Comment by jasonex7** [comment]
Hi @Rapster. I've tested with the latest snapshot but the export repeat the rows. I've attached the reproducer so you could test.

![image](https://github.com/primefaces/primefaces/assets/16229253/355d0b46-365e-4c1c-98d8-792868997c41)


[primefaces-test-withfix.zip](https://github.com/primefaces/primefaces/files/12629160/primefaces-test-withfix.zip)
