### ISSUE TITLE
TextEditor: Link toolbar button not working

### ISSUE THREAD

**Issue by giorgianaciobanu-etu** [primefaces/primefaces#10665]
### Describe the bug

Considering a p:texEditor inside a p:dialog, when I click the hyperlink icon from the texteditor's toolbar and I try to edit the link then nothing happens, it looks like not editable.

If the texteditor is placed outside the dialog then it works well, I mean the hyperlinks can be edited and saved. So the issue is happening only when my texteditor is inside the dialog.

### Reproducer

1. Click "Open the dialog"
2. Click  inside the texteditor and select one word
3. Click the hyperlink icon from the texteditor toolbar
4. try to edit in the opened input text

```xml
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:p="http://primefaces.org/ui"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>

<p:commandLink title="Open the dialog"
								   action="#"
								   onclick="PF('dialogWithTextEditorWdg').show();" />

<p:dialog header="Texteditor inside dialog" modal="true" draggable="true"
showHeader="true" resizable="true" closeOnEscape="true" responsive="true" width="92%"
id="dialogWithTextEditor" widgetVar="dialogWithTextEditorWdg" blockScroll="false">

<h:form id="levelForm" prependId="false">

<p:inplace id="st" editor="true" >
<p:ajax event="save" listener="#{modelBean.saveModel}" update="@this growl"/>

<f:facet name="input">

<p:textEditor id="pStatementText" value="This is my text and I want a link here." widgetVar="pStatementTextWdg">
<f:facet name="toolbar">
<span class="ql-formats">
<button class="ql-bold"></button>
<button class="ql-italic"></button>
<button class="ql-underline"></button>
<button class="ql-clean"></button>
<button class="ql-list" value="bullet"></button>
<button class="ql-list" value="ordered"></button>
<button class="ql-align" value=""></button>
<button class="ql-align" value="center"></button>
<button class="ql-align" value="right"></button>
<button class="ql-link"></button>
</span>
</f:facet>
</p:textEditor>

</f:facet>
</p:inplace>

</h:form>
</p:dialog>

</h:body>
</html>

```

### Expected behavior

Be able to create an hyperlink or to edit the URL of an existing hyperlink.

### PrimeFaces edition

None

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3.18

### Java version

11 and 17

### Browser(s)

Chrome

**Comment by melloware** [comment]
I don't think its dialog related if you go to the showcase it doesn't work in a non-dialog: https://www.primefaces.org/showcase/ui/input/textEditor.xhtml

**Comment by melloware** [comment]
@giorgianaciobanu-etu  Here is my reproducer it looks like the Link is working inside a dialog?

[pf-10665.zip](https://github.com/primefaces/primefaces/files/12600130/pf-10665.zip)

run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

**Comment by giorgianaciobanu-etu** [comment]
> @giorgianaciobanu-etu Here is my reproducer it looks like the Link is working inside a dialog?
> 
> [pf-10665.zip](https://github.com/primefaces/primefaces/files/12601070/pf-10665.zip)
> 
> run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

@melloware thanks for your quick answer! you are right it works in your example. I see you used Primefaces 13, I changed it to Primefaces 12 and still working fine. 

It seems it's rather something from my application that blocks the edition. I only sent a very simplified version of what I have in the application. So now I go back to my endless debugging :)

I will close this as it is not a Primefaces issue.

**Comment by melloware** [comment]
Yep It might be some weird z-Index issue with your CSS or something in your template causing that link popup to not show up above the dialog?

**Comment by giorgianaciobanu-etu** [comment]
yeah, I'll check again all those styles with more attention, most probably I missed something there... Thanks again!
