### ISSUE TITLE
Dialog position is not saved after dragging

### ISSUE THREAD

**Issue by Just-Dominic** [primefaces/primefaces#10663]
### Describe the bug

After dragging a dialog the coordinates are changed but they get reset when the user scrolls down. The dialog jumps to its original position (center of the screen).

### Reproducer

1. Check out the Primefaces showcase at: https://www.primefaces.org/showcase/ui/overlay/dialog.xhtml?jfwid=6bc18
2. Open a dialog and drag it
3. Scroll down

### Expected behavior

The dialog should remain in the same place.

### PrimeFaces edition

Community

### PrimeFaces version

13

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

Chrome

**Comment by melloware** [comment]
Definitely a bug.  Thanks for the report!

**Comment by Just-Dominic** [comment]
You're welcome. I am looking for a work-around but i'am struggling to find one.

**Comment by melloware** [comment]
I will have one for you I hope. Debugging it soon

**Comment by Just-Dominic** [comment]
When I add responsive="false" as atrr it seems to work alright. Maybe it helps.

**Comment by melloware** [comment]
Yep in responsive we have to respond to all screen size changes and reposition.   Still looking into it.

**Comment by melloware** [comment]
@Just-Dominic because this is expected behavior in responsive mode you can do this following either.

A) set `responsive="false"`
B) use this MonkeyPatch if you want to keep responsive settings but not listen to window scrolling.

```js
if (PrimeFaces.widget.Dialog) {
    PrimeFaces.widget.Dialog.prototype.bindResizeListener = function() {
        var $this = this;

        PrimeFaces.utils.registerResizeHandler(this, 'resize.' + this.id + '_align', null, function() {
            if ($this.cfg.fitViewport) {
                $this.fitViewport();
            }

            if ($this.isVisible()) {
                // instant reinit position
                $this.initPosition();
            } else {
                // reset, so the dialog will be positioned again when showing the dialog next time
                $this.positionInitialized = false;
            }
        });
    }
};
```
