### ISSUE TITLE
Timeline: Loss of nested timeline state (open and closed children) after timeline update

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#10667]
### Describe the bug

When the timeline is updated if certain nested groups were expanded or collapsed or if items were zoomed to fit , all those options are reset after the update

### Expected behavior

the groups or items that should be added or deleted to update but the options of which nested groups are expanded or not are left as they were

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.1

### Java version

19

**Comment by melloware** [comment]
I assume the timeline it is just re-rendering what is in your backing bean model?  So those states would need to be in your model?  As the JS has no idea what happended on a re-render right? It wouldn't know what was open or closed or moved unless the backing bean model represented that?

Also please provide a reproducer with instructions on reproducing.

**Comment by melloware** [comment]
Will close for now.
