### ISSUE TITLE
Docs: Please add a reference to FlowLogix JPA LazyDataModel to docs

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#10677]
### Description

Hi,

I do believe that https://docs.flowlogix.com/#section-jpa-lazymodel is the best and simplest implementation of JPA LazyDataModel. I request it be added to the docs and showcase. Thank you

### Describe the solution you would like

Please add https://docs.flowlogix.com/#section-jpa-lazymodel to docs and showcase

**Comment by Rapster** [comment]
I don't see the added-value to pin-point every PF customization of every libraries depending on PF. If we start doing that, it'll create more noise for most users than anything else. If you're a user of FlowLogix, it's FlowLogix job to properly document this customization (which they very well did)

That's my opinion, @melloware @jepsar ?

**Comment by tandraschko** [comment]
IMO it would be a better way if you could give is some hints, what exactly is easier and better and improvide our JPALazyDataModel, instead of creating a additional lib

**Comment by melloware** [comment]
Yep I will review flowlogic code and submit a PR. I was also going to ask that developer why they are writing their own library instead of submitting PR to enhance PrimeFaces and OmniFaces?

**Comment by lprimak** [comment]
Hi,

Many projects highlight their ecosystems in their documentation. Examples: https://shiro.apache.org/integration.html and https://jakarta.ee/compatibility/ and it would be great if PrimeFaces would do the same. It's good for the whole ecosystem.

The big advantage of injection is that there is no configuration needed at all, just a one-liner to use the model. No need to specify entity type, entity manager, etc. when creating the model.
Other two "killer" features are no-inheritance model, which really reduces cognitive load and eases usage, as well as ability to use it in clustered sessions (no serialization issues)

It would be much easier to add a link in the documentation. However, if you want to incorporate the functionality, feel free to do so (it's Apache licensed) but some acknowledgement would be appreciated. Perhaps a link as stated above :)

**Comment by lprimak** [comment]
> I was also going to ask that developer why they are writing their own library instead of submitting PR to enhance PrimeFaces and OmniFaces?

I have submitted (and OmniFaces has incorporated) many features of what I developed in FlowLogix umbrella already (Thanks @BalusC)
I also have tried to submit JPALazyDataModel to PF over 6 years ago, well before PF implementation, but there were some technical and design hurdles that prevented it at the time, I do not remember which ones, but they still may exist today.

**Comment by melloware** [comment]
@lprimak thanks!  Yeah the hurdles are you implementation is all tied to CDI and custom Entity DAO stuff.  The PF one has to remain as flexible as possible.  I did implement your case sensitive feature though thanks!

**Comment by fcorneli** [comment]
Constructing -let's call it- CDI enabled JSF tag libraries is possible, although care must be taken to have it also working within the context of multi-WAR EAR deployments. See also section 2.17 CDI enabled JSF tag libraries, page 115 of:
https://github.com/e-Contract/enterprise-jsf/releases/download/enterprise-jsf-1.11.0/enterprise-jsf.pdf
I've tried this within the `ejsf-taglib` and it seems to work. However, serving `javax` and `jakarta` at the same time also poses a challenge:
https://github.com/e-Contract/enterprise-jsf/commit/c912cd7d9cf8d83cfe99539cc3e79c6ebd84fdb4

> it requires CDI; JSF still can be used with other IOCs

Well, if you limit the actual JSF library to EL lookups, you could also have -for example- a Spring-flavored version next to your CDI stuff.

As for `JpaLazyDataModel` however I see little added value of dragging in CDI here.
However, something that I stumbled upon is that `JpaLazyDataModel` sits somehow in the wrong place. I don't want to implement this within my WARs, but within the EJB/CDI JAR of my EAR where my model lives. My WARs should not be dealing with loading JPA entities themselves. But here you find `JpaLazyDataModel` sitting within the PF JAR and thus within the WARs, unaccessible by the EJB/CDI model JAR. Maybe `JpaLazyDataModel` should live outside the PF JAR, and thus be JSF API agnostic?

**Comment by tandraschko** [comment]
LazyDataModel is in PF and based on PF and JSF API, so JpaLazyDataModel is actually in the completely right place

**Comment by tandraschko** [comment]
| The big advantage of injection is that there is no configuration needed at all, just a one-liner to use the model.

The same with PF; easiest case, without additional configuration:
PF:
```
private JpaLazyDataModel model = new JpaLazyDataModel<>(MyEntity.class, () -> CDI.current().select(EntityManager.class).get());
```

FlowLogix:
```
@Inject private JPALazyDataModel<UserEntity, Long> lazyModel;
```


| No need to specify entity type, entity manager, etc. when creating the model.

The entity type is defined in both places, generic vs constructor param.

The EntityManager selection is different but ours is just plain CDI, without passing some EM qualifiers to the model etc.
I like ours more as aligned with CDI, maybe just matter of taste. I dont like abstraction over already existing specs.
You can simply do something like:
```
@Inject @MyQualifier EntityManager em;
```

| Other two "killer" features are no-inheritance model, which really reduces cognitive load and eases usage, as well as ability to use it in clustered sessions (no serialization issues)

PF JPALazyDataModel works also fine in clustered sessions, no serialization issues.

The only thing its really worth to talk about IMO is "no-inheritance model" as you can define default filter/sorts via lambdas. That what we dont have.

**Comment by fcorneli** [comment]
> > implement this within my WARs
> 
> FYI: FlowLogix JPALazyDataModel works just fine in EJB-jars `lib/` directory

Which is indeed the place where it belongs. A WAR should not be doing data loading as its job is not to enforce business rules. This belongs to the model.

**Comment by tandraschko** [comment]
Our JpaLazyDataModel also works fine in ear/lib - there is no difference ;)

**Comment by fcorneli** [comment]
OK, but then you extend the JSF API towards "EAR scope", right?

**Comment by tandraschko** [comment]
yeah sure

**Comment by lprimak** [comment]
> The same with PF; easiest case, without additional configuration

You are using raw types in the declaration, so it's not *quite* as easy as that :)

I am not saying that FlowLogix JPALazyDataModel does something that PF one doesn't, what I am saying that it's orders of magnitude easier to implement with FlowLogix model.

> PF JPALazyDataModel works also fine in clustered sessions, no serialization issues.

Well, sort-of. Inheritance is required in all but the simplest cases. Since inheriting class will inevitably have some sort of additional state, much care must be taken to preserve serialization by the user.
Not a trivial task and errors will occur at runtime in clustered environments only (not on developer's machine)
FlowLogix JPALazyDataModel avoids this issue completely since the lambas provided do not need to be serializable.

**Comment by fcorneli** [comment]
@tandraschko  Let me try this out. As far as I can remember you cannot move JSF libraries from WAR level to EAR level without wonderful class loading errors.

**Comment by lprimak** [comment]
Hi,

I did not open this issue to argue features / functions / design of PF JPALazyDataModel vs. FlowLogix JPALazyDataModel vs. something else.

This is not the point.

The point is that there is an ecosystem and it should be featured in PrimeFaces documentation. This is good for the whole ecosystem, shows vitality and helps everybody.

Thank you

**Comment by lprimak** [comment]
> Let me try this out. As far as I can remember you cannot move JSF libraries from WAR level to EAR level without wonderful class loading errors.

Works with Payara last time I tried it. But please do try to see if it works with the latest

**Comment by lprimak** [comment]
@melloware @tandraschko I see there are already many changes to PF JPALazyDataModel inspired from what I have develop. Some attribution would definitely be in order.

Thank you

**Comment by fcorneli** [comment]
https://github.com/e-Contract/enterprise-jsf/tree/master/examples/helloworld-ear
With the following patch:
```patch
diff --git a/examples/helloworld-ear/ear/pom.xml b/examples/helloworld-ear/ear/pom.xml
index 53640e2..99c6fb1 100644
--- a/examples/helloworld-ear/ear/pom.xml
+++ b/examples/helloworld-ear/ear/pom.xml
@@ -40,5 +40,10 @@
             <version>1.0.0-SNAPSHOT</version>
             <type>war</type>
         </dependency>
+        <dependency>
+            <groupId>be.e-contract.enterprise-jsf.helloworld-ear</groupId>
+            <artifactId>taglib</artifactId>
+            <version>1.0.0-SNAPSHOT</version>
+        </dependency>
     </dependencies>
 </project>
diff --git a/examples/helloworld-ear/war/pom.xml b/examples/helloworld-ear/war/pom.xml
index 78328f3..6925c8d 100644
--- a/examples/helloworld-ear/war/pom.xml
+++ b/examples/helloworld-ear/war/pom.xml
@@ -17,6 +17,7 @@
             <groupId>be.e-contract.enterprise-jsf.helloworld-ear</groupId>
             <artifactId>taglib</artifactId>
             <version>1.0.0-SNAPSHOT</version>
+            <scope>provided</scope>
         </dependency>
     </dependencies>
 </project>
```
So moving the JSF taglib from WAR to EAR.
Deploy on WildFly 26.1.2, navigate to:
http://localhost:8080/helloworld-ear/validation.xhtml
and you get the lovely:
```
18:20:37,813 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-1) JSF1005: Cannot instantiate validator of type ejsf.exampleValidator
18:20:37,823 FATAL [javax.enterprise.resource.webcontainer.jsf.context] (default task-1) JSF1073: javax.faces.FacesException caught during processing of RENDER_RESPONSE 6 : UIComponent-ClientId=, Message=Expression Error: Named Object: ejsf.exampleValidator not found.
18:20:37,823 FATAL [javax.enterprise.resource.webcontainer.jsf.context] (default task-1) Expression Error: Named Object: ejsf.exampleValidator not found.: javax.faces.FacesException: Expression Error: Named Object: ejsf.exampleValidator not found.
	at com.sun.jsf-impl@2.3.17.SP01//com.sun.faces.util.Util.notNullNamedObject(Util.java:479)
	at com.sun.jsf-impl@2.3.17.SP01//com.sun.faces.application.applicationimpl.InstanceFactory.createValidator(InstanceFactory.java:587)
	at com.sun.jsf-impl@2.3.17.SP01//com.sun.faces.application.ApplicationImpl.createValidator(ApplicationImpl.java:542)
	at javax.faces.api@3.1.0.SP01//javax.faces.application.ApplicationWrapper.createValidator(ApplicationWrapper.java:546)
```
Computer says no.

**Comment by fcorneli** [comment]
> Maybe there is some circular dependency here that can be untangled?

Even if you could find a work-around for WildFly/JBoss (with some `jboss-deployment-structure.xml` magic), are we going to untangle this for every Java EE application server out there?
No. If a JSF library wants to offer some "non JSF functionality" like JPA enhancements, this should get isolated in a separate JAR in order to have a solution that works on all Java EE application servers or other runtimes.

**Comment by melloware** [comment]
I guess I am confused because this model is supporting a UI component so it should never be in the common ear/lib right? It is JSF technology not "non JSF Functionality".  Meaning this code serves NO purpose outside of PrimeFaces right?

**Comment by fcorneli** [comment]
Maybe there is some terminology confusion here. For me model is where the JPA entities live, where the business model (hence the name) EJB/CDI beans live. What PF refers to as model is for me just a PF API, let me refer to this as PF model.
So imagine we have an application with the following EJB/CDI model:
A JPA entity named `MyEntity`. An EJB/CDI business model bean `MyBusinessBean` holding the access control logic (RBAC, ABAC, you name it) towards `MyEntity`.
Next to this you can have different "front-ends": JSF based WAR, JAX-RS based WAR, JAX-WS based WAR.
All these front-ends have to use `MyBusinessBean` to get access to `MyEntity` as we always want to enforce the business rules here.
I hope we all agree that this is a sound architecture for an application?
Notice here that our business model is "front-end technology agnostic", i.e., it should not know about JSF API and such, but it knows about JPA.

So let's start with a JSF based WAR where we use PF to visualize `MyEntity` within a PF table.
In case we don't use lazy loading, the `@Named` CDI controller will load the entities via `MyBusinessBean` to have it visualized via a PF table. So we nicely passed `MyBusinessBean` to ensure all business rules have been enforced.

Now we want to add lazy loading to our PF table because the number of entries is getting to large to load in one go.
Here the front-end developer has to implement the PF model class `org.primefaces.model.LazyDataModel`.
In doing so, the `MyBusinessBean` needs to offer a corresponding API. And this is where the fun begins.
The `MyBusinessBean` has to replicate a large part of this PF model API in order to be able to serve the implementation of `LazyDataModel` within the front-end controller.
The business model has no access to `JPALazyDataModel` which it is largely replicating. This is what I mean when I state that "`JPALazyDataModel` sits in the wrong place".
Next to that `JPALazyDataModel` -as far as I know, it's evolving fast- does not leave room for easy adding "business filtering", e.g., injecting for example:
```
WHERE entity.user = :currentUser AND ... the usual JPALazyDataModel stuff here ...
```
and things like that.
You could have an implementation of `JPALazyDataModel` in your front-end CDI controller of course, but then the front-end developer is basically directly using `EntityManager` and is bypassing your business rules. We don't want this, right?

**Comment by tandraschko** [comment]
> Well, sort-of. Inheritance is required in all but the simplest cases. Since inheriting class will inevitably have some sort of additional state, much care must be taken to preserve serialization by the user. Not a trivial task and errors will occur at runtime in clustered environments only (not on developer's machine) FlowLogix JPALazyDataModel avoids this issue completely since the lambas provided do not need to be serializable

I'm not sure in which scope your model is produced, but if it's @Dependend and you store the lambdas inside your serializable JPALazyDataModel, your lambdas need to be serializable and will be serialized.
So there is no difference here, our current anonymous classes approach is serializable too.

but nevermind, it's matter of taste and most java develoeprs uses lambdas these days for such features.

**Comment by tandraschko** [comment]
@fcorneli your are right of course, that it is a bit weird from a layer seperation view, and that queries belongs more to some core/data/whatever layer.

But this actually just doesnt matter for us as we are a UI lib, no deltaspike or whatever. Our goal was to provide a easy way to convert the DataTable UI state to a JPA query, and luckily JPA provides enough abstraction to do this.
We could in theory move this "converter" logic to a own class and reuse it in JpaLazyDataModel but that wont help you either.
It will propably not cover all complex cases or will be perfect from the layer seperation but that was not our goal.

And "business filtering" is possible, currently with inheritance, maybe later with lambda but the question is, where do you place filtering logic and where does the EM comes from?

You can still move your own logic to your Repository and do something like this:

```
@Inject private MyEntityRepository repository;
private JpaLazyDataModel model;

@PostConstruct void init() {
    new JpaLazyDataModel<>(repository.getEntityClass(), () -> repository.getEntityManager()) {
        @Override
        protected void applyGlobalFilters(CriteriaBuilder cb, CriteriaQuery<?> cq, Root<MyEntity> root, List<Predicate> predicates) {
            repository.applyYourBusinessFiltering(....);
        }
    };
}
```

**Comment by fcorneli** [comment]
@tandraschko OK, brain waives finally synced. :)

As for the `JpaLazyDataModel` let me call it lambda-parametrization. I see three things here:
* indeed, `() -> repository.getEntityManager()` as you need to feed it an `EntityManager`.
* something like `applyGlobalFilters` to enrich `CriteriaQuery`.
* but then also maybe something where you can enrich `Query` itself with, for example, `query.setParameter("currentUser", ...)`.

**Comment by lprimak** [comment]
> I'm not sure in which scope your model is produced, but if it's @Dependend and you store the lambdas inside your serializable JPALazyDataModel, your lambdas need to be serializable and will be serialized.

Nope. This brings me back way into the past when I had to deal with this problem.
Lambdas do not need to be serializable, only the builder, which is much easier not to keep serializable by he user

**Comment by lprimak** [comment]
This ticket / discussion really went off-topic. I am going to close it and open another one.

@fcorneli Please feel free to open your own ticket if you need to, and /or please feel free to add URL to your project as a community contribution to the PF ecosystem.

**Comment by rudi1602** [comment]
> Maybe there is some terminology confusion here. For me model is where the JPA entities live, where the business model (hence the name) EJB/CDI beans live. What PF refers to as model is for me just a PF API, let me refer to this as PF model. So imagine we have an application with the following EJB/CDI model: A JPA entity named `MyEntity`. An EJB/CDI business model bean `MyBusinessBean` holding the access control logic (RBAC, ABAC, you name it) towards `MyEntity`. Next to this you can have different "front-ends": JSF based WAR, JAX-RS based WAR, JAX-WS based WAR. All these front-ends have to use `MyBusinessBean` to get access to `MyEntity` as we always want to enforce the business rules here. I hope we all agree that this is a sound architecture for an application? Notice here that our business model is "front-end technology agnostic", i.e., it should not know about JSF API and such, but it knows about JPA.
> 
> So let's start with a JSF based WAR where we use PF to visualize `MyEntity` within a PF table. In case we don't use lazy loading, the `@Named` CDI controller will load the entities via `MyBusinessBean` to have it visualized via a PF table. So we nicely passed `MyBusinessBean` to ensure all business rules have been enforced.
> 
> Now we want to add lazy loading to our PF table because the number of entries is getting to large to load in one go. Here the front-end developer has to implement the PF model class `org.primefaces.model.LazyDataModel`. In doing so, the `MyBusinessBean` needs to offer a corresponding API. And this is where the fun begins. The `MyBusinessBean` has to replicate a large part of this PF model API in order to be able to serve the implementation of `LazyDataModel` within the front-end controller. The business model has no access to `JPALazyDataModel` which it is largely replicating. This is what I mean when I state that "`JPALazyDataModel` sits in the wrong place". Next to that `JPALazyDataModel` -as far as I know, it's evolving fast- does not leave room for easy adding "business filtering", e.g., injecting for example:
> 
> ```
> WHERE entity.user = :currentUser AND ... the usual JPALazyDataModel stuff here ...
> ```
> 
> and things like that (relates to [#10682](https://github.com/primefaces/primefaces/issues/10682)). You could have an implementation of `JPALazyDataModel` in your front-end CDI controller of course, but then the front-end developer is basically directly using `EntityManager` and is bypassing your business rules. We don't want this, right?
> 
> Don't get me wrong. `JPALazyDataModel` is something very powerful, but it is completely entangled with the PF/JSF API. If you could "cut it out of PF" and make it generic (could also be used within the context of PrimeReact apps for example) you would really hit the nail.

I agree. I implemented my own LazyDataModel which doesn't use any PrimeFaces packages but is very inspired by PrimeFaces default JPALazyDataModel.
FlowLogix has keyset pagination but arguments remain.

Right now I weigh
'a not perfect layer system with FlowLogix and PrimeFaces default LazyModel but much OOTB stuff like filtering'
against
'own layer based implementations with a lot of reinventing the wheel' by the help of the mentioned libraries.

Thanks to every contributor and your awesome work.
