### ISSUE TITLE
JpaLazyDataModel: allow global/predfined filtering and sorting via lambda

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10682]
global filters are currently possible by inherit the JpaLazyDataModel and overwrite applyGlobalFilters.

Currently predefined sorting can be done via the attributes on p:column, however not for not-displayed columns.

Both could be easily done via lambdas.

**Comment by lprimak** [comment]
As this is already implemented in https://docs.flowlogix.com/#section-jpa-lazymodel
Please consider making the APIs and functionality at least somewhat compatible.
Keeping in mind that the implementation lambdas shouldn't need to be serializable.

**Comment by tandraschko** [comment]
@melloware i need some ideas about naming

`JpaLazyDataModel.builder().filter((filterBy, cb, cq, root, predicates) -> predicates.add(...))`

similar to #applyGlobalFilters, this is just a callback to add a predicate to a list
should we then name it `filter` actually? i would expect i could directly filter via javacode instead of add some jpa predicates

**Comment by melloware** [comment]
Interesting. So is your thought we could filter like it was a `stream` and use Java code to filter the list after it is query and another one that i overloaded to add JPA filters to the query?

**Comment by tandraschko** [comment]
i dont think we should allow filtering via javacode, that should be done via query
but not sure if we should name it "filtering" because its just adding/manipulating predicates

**Comment by melloware** [comment]
Got it so your concern is `filter` and `sort` may be misleading.

Some ideas:
`filterClause` and `sortClause`
'whereClause` and `sortBy`
`where` and `sortBy` 

???

**Comment by tandraschko** [comment]
yep exactly

also thought about "filterEnricher" / "sortEnricher"
so we could rename "enricher" to "queryEnricher"

**Comment by melloware** [comment]
not bad because you really are enriching the underlying query.
