### ISSUE TITLE
Organigram: Drag´n´Drop-issues with zoom-out

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#10689]
### Describe the bug

When using zoom out selecting the target node does not work correct.

### Reproducer

1. Go to https://primefaces.org/showcase/ui/data/organigram.xhtm
2. Activate zoom
3. "Zoom out" a few times (eg 4 times)
4. Move eg "Lisa Boehm" over somewhere between "Backend" and "Android"
![image](https://github.com/primefaces/primefaces/assets/10461942/8768c6fd-ca68-4b55-9fac-94e0132fb8c7)
5. You see both ("Backend" and "Android") get highlighted. 
Also two drag´n´drop-AJAX events are triggered. One for each target.
![image](https://github.com/primefaces/primefaces/assets/10461942/869f046d-718f-4cd5-971a-bd7ce6cea6a5)

### Expected behavior

Same behaviour as with 100% (default) zoom. Just select one target node, fire one drag´n´drop- AJAX-event.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by christophs78** [comment]
Organigram seems to be based on JQuery UI Droppable Widget.
I already tried some hacking with https://api.jqueryui.com/droppable/#option-tolerance. Does not improve the behaviour.
My feeling tells me this is somehow related to the way Organigram does it´s zoom. (via CSS-transform/scale)
![image](https://github.com/primefaces/primefaces/assets/10461942/bce0da0b-aa6e-4879-b3af-f16ed0d189b5)
This may not play well together with the aged JQuery UI Droppable Widget.

**Comment by melloware** [comment]
I think you might be right. I use Droppable in a few apps without issue but that transform must be throwing off the hit logic or something.

**Comment by christophs78** [comment]
Yep, sound similar. SO-article uses CSS-zoom, PF-organigram uses CSS-transform/scale, but probably the same root cause.

**Comment by melloware** [comment]
@christophs78 even more interesting it looks like PF already tries to handle zooming but this logic must be slightly off.

```js
            // overwrite start/drag to support browser scaling/zooming
            start: function(event) {
                initialDragPosition.x = event.clientX;
                initialDragPosition.y = event.clientY;
            },
            drag: function(event, ui) {
                var original = ui.originalPosition;
                var zoomFactor = 1.0;
                if (widget.zoomFactor) {
                    zoomFactor = widget.zoomFactor;
                }
                ui.position = {
                    left: (event.clientX - initialDragPosition.x + original.left) / zoomFactor,
                    top:  (event.clientY - initialDragPosition.y + original.top ) / zoomFactor
                };
            }
```
