### ISSUE TITLE
PrimeFaces 11, InputNumber IE 11 Compatibility

### ISSUE THREAD

**Issue by RobiVeho** [primefaces/primefaces#10690]
### Discussed in https://github.com/orgs/primefaces/discussions/76

<div type='discussions-op-text'>

<sup>Originally posted by **RobiVeho** September 20, 2023</sup>
In one of our projects we are using PF 11. Unfortunately, we have many users who were still using IE 11. According to the documentation, Primefaces should be compatible with IE 11.

We noticed a problem using the InputNumber component in IE11. It seems that there is an issue when converting NodeList to Array. In InputNumber.js we can find the following code:

  ```
 "./src/AutoNumericHelper.js":
         /*!****************************************!*\
     !*** ./src/AutoNumericHelper.js ***!
     \************************************/
         /*! exports provided: default */
         function (c, i, e) {
             e.r(i);
             e.d(i, "default", function () {
                 return t;
             });
             var a = e("./src/AutoNumericEnum.js");
             function g(u) {
                 return o(u) || r(u) || k(u) || b();
             }
         
             function b() {
                 throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
             }
             function r(u) {
                 if (typeof Symbol !== "undefined" && Symbol.iterator in Object(u)) {
                     return Array.from(u);
                 }
             }
             function o(u) {
                 if (Array.isArray(u)) {
                     return s(u);
                 }
             }
```

In  IE 11, the b method is always triggered, since o(u), r(u) and k(u) can't convert Nodelist into Array. 
We suggest the following fix:

```


   var a = e("./src/AutoNumericEnum.js");
             function g(u) {
                 return o(u) || r(u) || k(u) || ie11(u) || b();
             }
             function ie11(u) {
                 return Array.prototype.slice.call(u);
             }
             function b() {
                 throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
             }
```

Is it possible to expect that this issue will be fixed in one of the next versions? And generally how long can we expect compatibilty with IE 11?

Robert
</div>

**Comment by melloware** [comment]
**Autonumeric dropped IE11 support:** https://github.com/autoNumeric/autoNumeric/issues/764

**Microsoft Dropped IE support:** https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/

PrimeFaces has dropped IE support but if you are on 11 you can make a request through your PRO account.
