### ISSUE TITLE
JpaLazyDataModel: add lambda for enriching the query

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10692]
like mentioned in #10677:

> ...but then also maybe something where you can enrich Query itself with, for example, query.setParameter("currentUser", ...).

**Comment by lprimak** [comment]
As this is already implemented in https://docs.flowlogix.com/#section-jpa-lazymodel
Please consider making the APIs and functionality at least somewhat compatible.
Keeping in mind that the implementation lambdas shouldn't need to be serializable.

**Comment by melloware** [comment]
Fixed.
