### ISSUE TITLE
Splitter: initial size flashing on render

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#10694]
### Describe the bug

The initial size of the splitterPanels is not that one specified in the "size" property. The splitter adjust himself, causing a resizing and an annoying flashing effect. In the small example below the effect is not so bad, but if you load a lot of dynamic content it's really annoying.

### Reproducer

    <p:splitter style="height: 100%; width: 100%">
        <p:splitterPanel size="20" style="overflow: auto">
            <div style="width: 4000px;height: 1000px; background: yellow"></div>
        </p:splitterPanel>

        <p:splitterPanel size="80" style="overflow: auto">
            TEST
                <div style="width: 1000px;height: 1000px; background: red"></div>
        </p:splitterPanel>
    </p:splitter>

### Expected behavior

I would expect that the left / right panes of the splitter have the right size from the beginning (20%, 80%), avoiding the resize.
![screenshot2](https://github.com/primefaces/primefaces/assets/13310149/80dfa73e-f83d-4a15-a60c-20cc8b4423ac)
![screenshot1](https://github.com/primefaces/primefaces/assets/13310149/9d86a65d-7793-4be3-9567-3d84eac02942)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11.0.16

**Comment by melloware** [comment]
Splitter is doing the correct thing. See my reproducer:
[pf-10694.zip](https://github.com/primefaces/primefaces/files/12700826/pf-10694.zip)

The Splitter calculated its sizes at 21% and 79% to fill the width of the browser.  Then inside those panels you for some reason were declaring width 1000px and 4000px.  IF I remove those two hardcoded sizes:

![image](https://github.com/primefaces/primefaces/assets/4399574/3eb45a17-c910-46ac-9a63-aa1e6fce49f6)

**Comment by crocimi** [comment]
ok. But what if I have a content that is bigger than the splitterPanels' size? This is the reason I have set "overflow: auto" and added two "dummy" big divs....

**Comment by melloware** [comment]
I am not sure what you are trying to accomplish?

**Comment by crocimi** [comment]
I would like that the left and right pane are scrollable (horizontal). 

If I put a div inside each splitterPanel with "width: 100; height: 100; overflow: auto" I get the wrong sizes. Therefore I used "overflow: auto" directly on the splitterPanel.

**Comment by melloware** [comment]
OK I see.

**Comment by melloware** [comment]
I am not sure you will be able to achieve what you want since the splitter is flex based in its panels you are sizing things inside the panel expecting it to have scrollbars but your internal elements are actually remaining the size they are.

**Comment by crocimi** [comment]
actually, it works well (you can test it with the code above), the only unattractive effect is the initial resize.

**Comment by melloware** [comment]
Can you try this version:
[pf-10694.zip](https://github.com/primefaces/primefaces/files/12727288/pf-10694.zip)

Don't forget to press CTRL+F5 to reload JS.  I tried to prevent the flicker you are referring to.
