### ISSUE TITLE
Ajax request should provide information if response was a redirect

### ISSUE THREAD

**Issue by weissreto** [primefaces/primefaces#10699]
### Description

In our product if a user clicks on a button to close a dialog and navigate to the next dialog the button will send an Ajax request and we will close the dialog instance and send a redirect that will open the next dialog. This works well so far.
If the redirect request to open the next dialog last long the Ajax status disappears and the user is able to click on the buttons and links of the initial Dialog which causes problems in our product because the dialog is already closed.

Example:
See [Example](https://github.com/axonivy/primefaces-example) (Branch `master`):
1. On the first page there is a "Redirect to second page (ajax loader)" button. If you press it the `ajaxstatus ` shows a "Ajax ..." message.
2. The operation that is triggered (`MainBean#redirect`) closes the `MainBean`, then blocks for 10s, and then sends the redirect to the second page.
3. On the UI the "Ajax ..." message is displayed as long as the redirect method is running. After the redirect is received the "Ajax ..." message disappears.
4. The browser now requests the second page but the rendering of the page is postponed for 10s because of the `preRenderView ` listener `SecondBean#initialize`.
5. On the browser the UI of the old page is still visible and the User can press on the 'Action' button. The method `MainBean#doAction` will throw an Exception because the `MainBean `is already closed.
6. On the browser the Error Dialog is displayed and the user will press the "Back to Main page" button because she thinks everything is broken. If she would wait 10s the second page would be displayed. But most of the time the user is faster by clicking on the Button.

Solution/Workaround:
We found the following solutions or workarounds. See Branch `ajaxstatus_solution `and `ajaxstatus_solution2`.
In both solutions, we use a listener on the `pfAjaxComplete `event and check if the response is a redirect or not. In case it is a redirect we do not hide the "Ajax ..." message so that the user does not come to the idea to press another button.
In solution2 we also abort all other AJAX requests and block the UI with a modal dialog so that it is not possible for the user to click on any button during the redirect.

Improvements:
What is not so nice about our solution is that we need to parse the AJAX response content to check if we received a redirect or not. This is highly dependent on Primefaces implementation internals.

Do you have any suggestions, on how we can improve our solution to be less dependent on Primefaces internals or how Primefaces can provide more information about the AJAX response type?

### Describe the solution you would like

It would be nice if Primefaces could provide some information about the received AJAX response. E.g., some kind of status that we can check if the response was a redirect or not. Either in the ajaxstatus component or in the pfAjaxComplete event. 

### Additional context

This is a followup issues as suggested by Mert Sincan here https://pro.primefaces.org/browse/AXONIVY-32.
He has also suggested a solution with <p:blockUI> component. But this does also not work see Branch `uiblock_solution `

**Comment by tandraschko** [comment]
can you post the response?
does it contain the JSF XML with the `redirect` xml tag?

**Comment by weissreto** [comment]
Yes. JSF XML with redirect XML tag.
My code works correct. See here:
see https://github.com/axonivy/primefaces-example/blob/ajaxstatus_solution/src/main/webapp/first.xhtml#L45
What I don't like is that I need to check the response content (JSF XML) which may change in the future. 
I would like Primefaces to provide a receivedRedirect flag that I can use to check if the response was a redirect or not instead of checking the whole response content which is highly Primefaces implementation specific and not an API.

**Comment by tandraschko** [comment]
The response markup is JSF API, we wont and cant change that.

**Comment by tandraschko** [comment]
Also we cant provide easily this information as we parse the XML once and do instant redirect.

**Comment by weissreto** [comment]
> The response markup is JSF API, we wont and cant change that.

Ok, interesting. I didn't know that. So we are save with our implementation.

**Comment by weissreto** [comment]
> Also we cant provide easily this information as we parse the XML once and do instant redirect.

I don't understand why it should not be possible. Can you elaborate on the reasons?

Thanks for your patience

**Comment by tandraschko** [comment]
i commited something:
```
p:ajaxStatus oncomplete="console.log(args.redirect);" onsucess="console.log(args.redirect);"
```

is now defined && true if its a redirect

**Comment by tandraschko** [comment]
@melloware @jepsar do you think we should reuse this as our default for ajaxStatus? please see the example provided by the reporter

**Comment by melloware** [comment]
Yes I think we should.  This is a good change that makes the code more flexible for future changes.

**Comment by tandraschko** [comment]
i will close this for now and create a new feature request

**Comment by melloware** [comment]
@weissreto and @tandraschko this fix has reintroduced this issue: https://github.com/primefaces/primefaces/issues/11824

**Comment by Farewell-angular2-select** [comment]
> Yes I think we should. This is a good change that makes the code more flexible for future changes.





https://advisor54.github.io/l1SLxC8YD7TY1IJBXp3k88PMzgJieyGVrgexzgZ5j9oa5jN/
