### ISSUE TITLE
CI currently failing

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10697]
The archive file /home/runner/.m2/repository/com/github/eirslett/node/18.8.0/node-18.8.0-linux-x64.tar.gz is corrupted and will be deleted. Please try the build again.
 
 could someone check?

**Comment by melloware** [comment]
Yeah its an annoying issue: https://github.com/eirslett/frontend-maven-plugin/issues/882

It has been open for a while.  It looks like it has gotten worse recently.
