### ISSUE TITLE
Docs: add reference to FlowLogix JPA LazyDataModel

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#10691]
### Description

Hi,

I do believe that https://docs.flowlogix.com/#section-jpa-lazymodel is the best and simplest implementation of JPA LazyDataModel. I request it be added to the docs and showcase. Thank you

### Describe the solution you would like

Please add https://docs.flowlogix.com/#section-jpa-lazymodel to docs and showcase

### Additional context

Many ecosystem projects such as PrimeFaces support their community by listing projects that use and enhance the main product.
PrimeFaces can do the same.

**Comment by Rapster** [comment]
I stopped following this conversation, but a good start for you would be to make a PR 😉

**Comment by melloware** [comment]
@lprimak I don't mind if you add to the datatable.md docs adding a link your code but we won't be adding to the showcase it would require use including your JAR and instructions etc.

**Comment by lprimak** [comment]
What about creating community page?  I don’t think that exists yet?

**Comment by melloware** [comment]
Feel free to add a community page we could add blurbs and links for PrimeFaces Extensions, FlowLogix, @fcorneli if you want your project linked.  Basically projects enhancing the PF community.

**Comment by lprimak** [comment]
Looking for the docs to modify, I cannot find the source for the web pages on primefaces.org.
All I could find is:
- https://github.com/primefaces/primefaces/tree/master/docs (looks like API docs only)
- https://github.com/primefaces/primefaces.github.io (really old and out-of-date)

Can you show me the way please?
Thank you!

**Comment by melloware** [comment]
@lprimak the docs are all right here for 14.0.0: https://github.com/primefaces/primefaces/tree/master/docs/14_0_0

When we merge a PR the docs site for 14.0.0 automaitcally gets generated and pushed to: https://primefaces.github.io/primefaces/14_0_0/#/

**Comment by lprimak** [comment]
Thanks! I thought all that was auto-generated. Will look into that.
