### ISSUE TITLE
AjaxStatus: skip hide start-facet on redirect

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10708]
Based on #10699

In case when a AJAX request leads to an redirect, we should actually not hide the ajaxStatus facet.
When a user has a oncomplete callback, can now decide by 'args.redirect' to hide or not.

Should we implement this or maybe introduce a new attribute like 'showOncompleteFacadeOnRedirect'?

**Comment by melloware** [comment]
I feel like we should implement it as the default as to me this would be the expected reasonable behavior?

**Comment by tandraschko** [comment]
could anyone explain me this? :D

```
        if (event !== 'complete' || this.jq.children().filter(this.toFacetId('complete')).length) {
            this.jq.children().hide().filter(this.toFacetId(event)).show();
        }
```

**Comment by tandraschko** [comment]
refactored for better readability but still dont unterstand it:

```
        if (event !== 'complete' || this.jq.children().filter(this.toFacetId('complete')).length) {
            var facets = this.jq.children();
            facets.hide(); // hide all other facets first
            facets.filter(this.toFacetId(event)).show();
        }
```

**Comment by melloware** [comment]
Original issue: https://github.com/primefaces/primefaces/issues/3625

PR: https://github.com/primefaces/primefaces/pull/3653

**Comment by tandraschko** [comment]
We have 4 events:
- start
- error/success
- complete

was the change that, if no complete-facet is defined, error/success should not be hidden, right?

**Comment by melloware** [comment]
Yes I think so or he is saying the `complete` facet always wiped out the success or error facet?
