### ISSUE TITLE
SelectOneRadio: flex layout - multiple grids

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#10712]
### Describe the bug

Hi,
I tried new feature introduced in https://github.com/primefaces/primefaces/issues/10319 and there is an issue with it. Let me explain:

Consided selectOneRadio defined 'responsive' like this:

```
<p:selectOneRadio value="#{testView.value}" flex="true" columns="3"
   columnClasses="col-12 md:col-6 lg:col-4, col-12 md:col-6 lg:col-4, col-12 md:col-6 lg:col-4">
        ... items... 
</p:selectOneRadio>
```

In 'large' screen it looks ok, grid seems to be used well:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/8f659793-c128-4b6f-b05f-71b5a40643ee)

But on 'medium' sized screen it doesn't look good:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/9c3e2253-c9e3-4c68-b331-833c9a671ea2)

**Problem is in multiple grids - single grid for each row.** 

This blocks us in extended usage of columnClasses attribute.

### Expected behavior

All items in selectOneRadio would be in single multiline grid that would behave much better than multiple grid sollution.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.1

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

17

**Comment by melloware** [comment]
Can you provide a PrimeFaces Test reproducer?

Also why not just use `layout="lineDirection"` and let it flow and be responsive?

**Comment by martin654** [comment]
Hi,
yes, I can. Please see attached file.

In the example I use line directino next to flex layout with custom style classes. Line direction doesn't suit us because our business wants radio items aligned into grid. I used it in example just to visually compare the two approaches.
The flex layout looks good on wide screen, but not on medium size, because there are multiple grids. If there was a single grid, it would be perfectly OK. 
What is the reason for multiple grids? It is one component with set of radios, why not to use single grid for them?

First example with wide screen:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/ba49d3e2-22a1-4edd-a5b7-f57113ce0b23)

Second example with medium:
![obrazek](https://github.com/primefaces/primefaces/assets/22746146/7a4bf118-5061-4976-8ebf-94ce09c5cec8)

Reproducer .zip project:
[pf-10712.zip](https://github.com/primefaces/primefaces/files/12735193/pf-10712.zip)

Best regards,
Martin

**Comment by melloware** [comment]
I see what you mean I think it was done was on purpose for default responsiveness not thinking people would override the column classes in responive mode. The defaults were trying to be smart and do this in large screen. So if I remove your `columnClasses` I see this...

![image](https://github.com/primefaces/primefaces/assets/4399574/674eba68-eb6f-43cb-a386-56939f63d77f)


And then in small screen it all snaps to `col-12`

![image](https://github.com/primefaces/primefaces/assets/4399574/211bf4b2-7220-4903-a5fe-18ddfeb5f58e)

Because you said `columns=3` its breaking the divs apart every 3 columns.

```java
if (!lineDirection && colMod == 0) {
                    writer.endElement("div");
}
```

But it looks like you want it to be `md:col-6` on medium size screens and go to 2 columns instead of right to 1 column correct?

**Comment by martin654** [comment]
Yes, defaults are nice but we wanted to have more freedom in responsiveness... to use more than small / medium (col-12 md:col-6. And this would be possible if everything was rendered in single grid. User could define his own column class / column classes if more fine grained responsiveness needed.

By the way:
Columns count doesn't have much sence in this case. ColumnClass attribute would be probably enough.

**Comment by melloware** [comment]
Yeah I think it was because it has to meet multiple use cases in `line`, `page`, `columns` etc all in one block of code.

A PR is welcome if you want to investigate. its all in `SelectOneRadioRenderer.java` in the `encodeResponsiveLayout` method.

**Comment by mertsincan** [comment]
Hi,

The `flex='true'` property is used to make the component responsive at a basic level. You can examine in the showcase how the SelectOneRadio and SelectManyCheckbox components are specifically designed for complex structures. My suggestion is to use their custom design structure with flexbox or grid. This allows you to customize it really easily.
https://primeflex.org/flex
https://primeflex.org/gridsystem

Best Regards,
