### ISSUE TITLE
DatePicker: There is no Now button and Today does not set time

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#10725]
### Describe the bug

After migrating from PF 7 version I can or should no longer use _Calendar_. Instead PF offers _DatePicker_. But when I set  _showButtonBar_ to true all I can see are Today and Clear buttons. And when input is set to date with time, _Today_ button only sets date and no time. In _Calendar_ there was a _Now_ button that did set date with time.

### Expected behavior

Today should be changed to Now and set date with time like in Calendar

### PrimeFaces edition

Community

### PrimeFaces version

12

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by melloware** [comment]
@majkers can you try this MonkeyPatch:

```js
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.onTodayButtonClick = function(event) {
        var today = new Date(),
            dateMeta = {
                day: today.getDate(),
                month: today.getMonth(),
                year: today.getFullYear(),
                today: true,
                selectable: true
            };

        this.updateViewDate(event, today);
        this.updateTime(event, today, today.getMinutes(), today.getSeconds(), today.getMilliseconds());
        this.onDateSelect(event, dateMeta);

        if (this.options.onTodayButtonClick) {
            this.options.onTodayButtonClick.call(this, event);
        }
    };
};
```

**Comment by majkers** [comment]
Yes I can but I think that there should be check of _showTime_ param or something because when there is no time and just date to select, it is not required.

**Comment by majkers** [comment]
It is not workig because datePicker is loaded on demand when there is a need of it. I addes it to head section but still no luck

**Comment by melloware** [comment]
You are loading it wrong then as MonkeyPatches should always be loaded  as the last JS so it overrides PF JS.  here is updated MonkeyPatch checking for `showTime`

```js
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.onTodayButtonClick = function(event) {
        var today = new Date(),
            dateMeta = {
                day: today.getDate(),
                month: today.getMonth(),
                year: today.getFullYear(),
                today: true,
                selectable: true
            };

        this.updateViewDate(event, today);
        if (this.options.showTime) {
                this.updateTime(event, today, today.getMinutes(), today.getSeconds(), today.getMilliseconds());
        }
        this.onDateSelect(event, dateMeta);

        if (this.options.onTodayButtonClick) {
            this.options.onTodayButtonClick.call(this, event);
        }
    };
};
```

**Comment by majkers** [comment]
Yes I know but since I am using tabs and datepicker is not on my first tab, it is loaded dynamically when need on other tabs.

![image](https://github.com/primefaces/primefaces/assets/21099773/ca796664-7b84-4504-a8e9-59eb815587ce)

**Comment by melloware** [comment]
right but I don't see your `application.js` or whatever your custom JS file is being loaded there so it should go in your custom JS file and loaded last.  It should not matter if the tab is dynamic or not...

**Comment by majkers** [comment]
Yes. Still missing the pint though :( I just showed You a part that is being loaded dynamically when I open a tab with datePicker my application.js is loaded at the start of the application but like I said before. My start page does not have datePicker so it is no loaded. Anyway. It works :)
