### ISSUE TITLE
DataTable: filterMatchMode in does not work correctly with enums

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10730]
Currently checking DataTable002 because of #8395, a bit modified but just using a `List<ProgrammingLanguage>` and filtering by type doesnt work.

See:

```
                <p:column field="type" filterMatchMode="exact">
                    <f:facet name="filter">
                        <p:selectCheckboxMenu id="filterType" onchange="PF('datatable').filter()" multiple="true" updateLabel="true">
                            <f:selectItems value="#{dataTable002.types}"/>
                        </p:selectCheckboxMenu>
                    </f:facet>
                </p:column>
```

@Rapster WDYT?

**Comment by melloware** [comment]
we use it in our apps let me get an example.

**Comment by melloware** [comment]
```xml
<p:column id="colTemplateKey" headerText="#{appmsg['column.emailtemplate.templateKey']}"
						sortBy="#{row.emailTemplateKey.text}" filterBy="#{row.templateKey.text}" filterMatchMode="in"
						styleClass="col-left" width="180" sortPriority="1" sortOrder="asc">
	<f:facet name="filter">
		<p:selectCheckboxMenu id="chkTemplateKeyFilter" label="#{appmsg['label.all']}" filter="true"
								filterMatchMode="startsWith" updateLabel="true">
			<p:ajax event="change" process="@this" oncomplete="PF('tableEntity').filter();" />
			<p:ajax event="toggleSelect" process="@this" oncomplete="PF('tableEntity').filter();" />
			<f:selectItems value="#{emailTemplateKeyFilterOptions}" />
		</p:selectCheckboxMenu>
	</f:facet>
	<h:outputText value="#{row.emailTemplateKey.displayText}" />
</p:column>
```

**Comment by tandraschko** [comment]
yep, i was debugging currently
seems like filterMatchMode must be "in", so your test is wrong

**Comment by tandraschko** [comment]
still the same problem
InFilterConstraint receives the string value as value but and the filter array contains the value as enum

**Comment by FlipWarthog** [comment]
> still the same problem InFilterConstraint receives the value as enum but and the filter array contains the value as string
 
@melloware I think we ran into this and in what you posted it's being handled by `filterBy="#{row.templateKey.text}"`. Our Enums have a `getText()` method:
```java
   public String getText() {
      return this.name();
   }
```
And the `SelectItem`s value is also the enum's `getText()`:
```java
         emailTemplateKeyOptions = FilterUtils.getFilterOptions(FilterUtils.getEnumList(getEmailTemplateKeys()),
                  "displayText", "text", false);
```

**Comment by Rapster** [comment]
There is no issue here, the only thing missing is the converter 😉

**Comment by tandraschko** [comment]
The problem in this case, is that the value of the filter input is a string but the value is enum and not comparable.

Normally JSF 2.3 should convert it automatically but it doesnt work as no `value` attribute is set on the `selectCheckboxMenu`.

In theory you can attach the converter via `p:column converter="javax.faces.Enum"` but JSF will throw a exception as no enum-class can be provided this way
The second way is to attach it to the selectManyMenu but its the same problem.

so there are currently only 3 solutions:
- the small enhancement in PF
- inherit a EnumConverter for each Enum and use it either on p:column or p:selectCheckboxMenu
- use GenericEnumConverter on p:selectCheckboxMenu - also wont work on p:column

**Comment by tandraschko** [comment]
in general it would be great if there would be something like `f:convertEnum type=de.MyEnum` in the specs
