### ISSUE TITLE
DatePicker: There is no Now button and Today does not set time when timeOnly and showButtonBar set to true

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#10739]
### Describe the bug

This is continuation of https://github.com/primefaces/primefaces/issues/10725. After https://github.com/primefaces/primefaces/pull/10728/files# Today button sets time when _showTime_ option is set to true, but when it is set to false but _timeOnly_ option together with _showButtonBar_ are set to true it is not working.

@melloware sorry for not letting you know for the first time :(

This is not helping:

![image](https://github.com/primefaces/primefaces/assets/21099773/5b8a994a-0c81-46c9-9120-ee4e651ea487)

because
` this.onDateSelect(event, dateMeta); -> this.selectDate(event, dateMeta)
`is messing things up because it checks only showTime option :(

IMHO it should be like thias:

![image](https://github.com/primefaces/primefaces/assets/21099773/cc7d465d-065f-4589-b6f0-a09d2adf439d)

Moreover there are more places that only _showTime_ option is being checked without _timeOnly_ eg. parseDateTime function etc.

### Expected behavior

Today should be changed to Now and set date with time like in Calendar

### PrimeFaces edition

None

### PrimeFaces version

12

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by melloware** [comment]
Let me look I still think its weird that its possible to have `timeOnly` but have `showTime=false` that makes no sense right?
