### ISSUE TITLE
FileDownload: Docs code sample contains mismatched constructor

### ISSUE THREAD

**Issue by riyadomf** [primefaces/primefaces#10733]
The documentation page for [FileDownload](https://primefaces.github.io/primefaces/12_0_0/#/components/filedownload) contains a code sample that appears to have a discrepancy between the class name and the constructor name. In the code sample provided, the class is named FileBean, but the constructor is named FileDownloadController. This inconsistency in naming may cause confusion for users trying to implement this feature. Here's the specific code snippet with the discrepancy:

```
public class FileBean {
    private StreamedContent file;

    public FileDownloadController() {
        // ...
    }

    // ...
}
```
I suggest updating the constructor name to match, ensuring consistency and clarity in the documentation.

**Comment by melloware** [comment]
Thanks for reporting.  I will fix it.
