### ISSUE TITLE
DatePicker: When showButtonbar set to true and minDate is after currentDate, Today button is visible and when clicked it sets minDate rather thant current

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#10757]
### Describe the bug

Warning: The same for maxDate!

When showButtonbar set to true and minDate is after currentDate, Today button is visible and when clicked it sets minDate rather thant current. This is confusing and behaves differently that in Calendar control.

### Reproducer

All can be seen in demo

### Expected behavior

Today button should be hidden when current date is before minDate or is after maxDate set to datePicker

### PrimeFaces edition

None

### PrimeFaces version

12

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by melloware** [comment]
OK review PR please I fixed both issues.
