### ISSUE TITLE
DatePicker. When showButtonBar and timeOnly/showTime are set to true, Today button should have 'Now' label

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#10754]
### Describe the bug

Just like it was with Calendar, when we use time in selecting date. With _timeOnly_ set to true to select only time, or when _showTime_ is set to true to set time with date, IMHO _Today_ label on button should be changed to _Now_ to make it clear what user is selecting. This would require extending of locales:

![image](https://github.com/primefaces/primefaces/assets/21099773/b06c8c32-3dfe-4119-9b7f-c7863849bb92)

and use it in _renderButtonBar_ function.

### Reproducer

Alle can be seen in PF demo page

### Expected behavior

Add _Now_ label to button when selecting time or date with time.

### PrimeFaces edition

None

### PrimeFaces version

12

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by melloware** [comment]
These originate from PrimeLocale: https://github.com/primefaces/primelocale

They are shared across all 4 prime libs so i am not inclined to make the "Now" change.   Since it is a label you are more than welcome to set it in your project to be "Now" but I think i will leave PrimeFaces in line with the other libraries.

**Comment by majkers** [comment]
Yeah I might do that, but sometimes (without time) it should stay as Today. Since I am using both in my project, I cant' do that wrokaround....

**Comment by melloware** [comment]
Then change it to something generic like "Current" which could mean Today or Now...

**Comment by majkers** [comment]
In my native language there is no proper generic for both unfortunatelly.... Only working solution is to create monkeyPatch like this:
```

$.prime.datePicker.prototype.renderButtonBar = function () {
        var todayLabel = (this.options.showTime || this.options.timeOnly) ? 'Teraz' : this.options.locale.today;
        return '<div class="ui-datepicker-buttonbar ui-widget-header">' +
            '<div class="ui-g">' +
            '<div class="ui-g-6">' +
            '<button type="button" class="ui-today-button ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ' + this.options.todayButtonStyleClass + '"><span class="ui-button-text">' + todayLabel + '</span></button>' +
            '</div>' +
            '<div class="ui-g-6">' +
            '<button type="button" class="ui-clear-button ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ' + this.options.clearButtonStyleClass + '"><span class="ui-button-text">' + this.options.locale.clear + '</span></button>' +
            '</div>' +
            '</div>' +
            '</div>';
    }
```

**Comment by majkers** [comment]
One more stupid IMHO thing about Today button. It is always visible even min date set to datePicker is after current date and when clicked it sets this minial date rather than current date. Is it a bug? Should I create an issue for that?

**Comment by melloware** [comment]
Yes please open a new ticket!
