### ISSUE TITLE
TreeTable: Filtering with CustomNode and cloneOnFilter does not work

### ISSUE THREAD

**Issue by Maverick-501** [primefaces/primefaces#10763]
### Describe the bug

The filtering on a TreeTable with cloneOnFilter="true" and custom TreeNodes does not work.
We have a simple p:treeTable
```
<p:treeTable id="treeTable"
                     value="#{testView.customTree}"
                     nodeVar="node"
                     var="data"
                     cloneOnFilter="true"
                     selectionMode="single"
                     emptyMessage="empty">

                <p:column headerText="Name"
                     filterMatchMode="contains"
                     filterBy="#{data}">
                     #{data}
                </p:column>   

</p:treeTable>
```
            
with a CustomNode type which extends DefaultTreeNode and implements the copy constructor required by cloneOnFilter="true"
```
public class CustomNode<T> extends org.primefaces.model.DefaultTreeNode<T>
{
    public CustomNode(String type, T data, TreeNode parent)
    {
        super(type, data, parent);
    }

    public CustomNode(CustomNode<T> other)
    {
        super(other.getType(), other.getData(), other.getParent());
    }
}
```

The filterMatchMode is contains which means it should show one column when searching for "X" but it shows an empty tree.
![image](https://github.com/primefaces/primefaces/assets/122038645/f2f90880-4b36-4140-b362-3736c04115a6)
![image](https://github.com/primefaces/primefaces/assets/122038645/11589195-8813-47ed-a8ae-e189f97721b3)

I think the problem is that in org.primefaces.component.treetable.feature.FilterFeature in the method protected TreeNode cloneTreeNode(TreeTable tt, TreeNode<?> node, TreeNode<?> parent) the newly cloned root is not set as parent of the cloned child nodes. Therefore all the nodes get cloned but set in the original treeRoot and not in the clonedTreeRoot, which is why the TreeTable is empty after filtering since the newly cloned root will be shown but it has no children.
```
...
            else {
                try {
                    Constructor<? extends TreeNode> ctor = node.getClass().getConstructor(node.getClass());
                    clone = ctor.newInstance(node); // <- copy constructor argument is oldChild which has the oldRoot, setParent(parent) is needed here
                }
                catch (NoSuchMethodException e) {
                    // ignore
                }
...
```

### Reproducer

I have used the primefaces-test jakarta version from here https://github.com/primefaces/primefaces-test/tree/jakarta
To start: mvn clean jetty:run -Pmyfaces40

[primefaces-test-jakarta.zip](https://github.com/primefaces/primefaces/files/12793477/primefaces-test-jakarta.zip)

The filterMatchMode is contains which means it should show one column when searching for "X" but it shows an empty tree.
![image](https://github.com/primefaces/primefaces/assets/122038645/f2f90880-4b36-4140-b362-3736c04115a6)
![image](https://github.com/primefaces/primefaces/assets/122038645/11589195-8813-47ed-a8ae-e189f97721b3)

### Expected behavior

It should show one row with "NameX" when the filter value is "X" or in other words filtering with custom treeNodes and cloneOnFilter should work

### PrimeFaces edition

None

### PrimeFaces version

13.0.1

### JSF implementation

MyFaces

### JSF version

4.0

### Java version

11

**Comment by melloware** [comment]
@Maverick-501 PR is welcome?

**Comment by Maverick-501** [comment]
https://github.com/primefaces/primefaces/pull/10769

**Comment by Rapster** [comment]
This one is tricky, beside the 3 arg ctor... If 
- copy ctor: if dev implement a custom node like this:
 ```java
public CustomNode(CustomNode<T> other)
    {
        super(other.getType(), other.getData(), other.getParent());
    }
```
the cloned node gets added to the old parent. I didn't test much, but doesn't seem to be a problem for now. 
- cloneable: this issue will also happen
 
I think we should add a section in doc for custom nodes, and advise to use ctor with 3 arguments
