### ISSUE TITLE
TreeTable: Broken SortFunction

### ISSUE THREAD

**Issue by stonewoodman** [primefaces/primefaces#10767]
### Describe the bug

The SortFunction is Broken because of #10545
I already fixed this bug, i will create a pr

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-SNAPSHOT

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Let me know if you want me to backport to 13.0.2.

**Comment by melloware** [comment]
Nevermind this is the new function I broke in 14.0.0 😀
