### ISSUE TITLE
Chronoline: Inherit UIData

### ISSUE THREAD

**Issue by astappiev** [primefaces/primefaces#10762]
### Describe the bug

In the following example:
```xhtml
<p:chronoline value="#{searchChatBean.conversations}" var="conv">
    <p:commandLink action="#{searchChatBean.switchConversation(conv)}" update=":chat" process="@this">
          <h6 class="mb-0">#{conv.title}</h6>
    </p:commandLink>
</p:chronoline>
```

When `searchChatBean.switchConversation(conv)`  called `conv` is always `null`. However, replacing `p:chronoline` with `ui:repeat` fixes the issue.

### Expected behavior

Item iteration works in the same way as in `ui:repeat`.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### JSF implementation

MyFaces

### JSF version

4.0.1

### Java version

17

**Comment by melloware** [comment]
Weird the code looks like its doing the right thing.

```java
if (value != null) {
            Map<String, Object> requestMap = context.getExternalContext().getRequestMap();
            String var = chronoline.getVar();

            for (Iterator<?> it = value.iterator(); it.hasNext(); ) {
                requestMap.put(var, it.next());

                writer.startElement("div", null);
                writer.writeAttribute("class", Chronoline.EVENT_CLASS, null);

                encodeOppositeContent(context, chronoline);
                encodeSeparator(context, chronoline, !it.hasNext());
                encodeContent(context, chronoline);

                writer.endElement("div");
            }

            requestMap.remove(var);
        }
```

**Comment by FlipWarthog** [comment]
I set up a reproducer that shows the issue exists, even checked with 14.0.0-SNAPSHOT (which is what this is set up with), side-by-side with the working ui:repeat.
[primefaces-test-PF10762.zip](https://github.com/primefaces/primefaces/files/12795501/primefaces-test-PF10762.zip)

**Comment by FlipWarthog** [comment]
@melloware I did some digging and I think the root issue is that the children of Chronoline don't have unique IDs. The issue is also present in [the showcase](https://primefaces.org/showcase/ui/data/chronoline.xhtml?jfwid=64a23), the Customized has `p:commandButton`s in it and if you click one they all activate (you can inspect in Chrome F12 and see they've all got the same ID). Could be the missing `implements NamingContainer, UniqueIdVendor` on ChronolineBase.java and some other stuff too.

**Comment by tandraschko** [comment]
yeah
it was never designed to work like this, just for simple markup
so its a new feature which requires some hours works propably

**Comment by FlipWarthog** [comment]
@tandraschko I think @melloware is going to take a pass at it to see what he comes up with, but if nothing happens it might be worth updating the docs to call out the limitation (and update the showcase demo to remove those p:commandButtons since they don't work).

**Comment by tandraschko** [comment]
yeah sure
at least we can update the docs now and see if someone will implement this feature
chronoline would need to inherit from UIData then

**Comment by IgorPROliveira** [comment]
Hello, I would like to know if there is a scheduled date for version 12.0.8. I need this change in Chronoline

**Comment by melloware** [comment]
@IgorPROliveira i would ping PrimeTek through your PRO account.  The community has no control over 12.X branch.
