### ISSUE TITLE
ContextMenu (DataTable): Detail dialog does not open

### ISSUE THREAD

**Issue by jansohn** [primefaces/primefaces#10774]
### Describe the bug

Showcase for context menu (data table) seems to be broken as it does not show the details dialog.

We experience the same behavior in our web application using the latest PrimeFaces version 13.0.1. We found a workaround: If we add an empty `actionListener` to the `p:menuitem` tag then the dialog does open.

### Reproducer

https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

Right-click on first data table row and click 'View'. Dialog does not open.

### Expected behavior

Dialog opens with detail view even if no `action` or `actionListener` is defined.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

JDK11

**Comment by melloware** [comment]
Yep will backport!

**Comment by jansohn** [comment]
Thanks for the quick fix/backport. Just curious, what's the schedule on releasing minor versions at the moment?

**Comment by melloware** [comment]
We haven't solidified it yet but our internal discussions the though was around once a month (30 days) if enough issues were fixed.  13.0.1 was 3 weeks ago so expect 13.0.2 very soon!
