### ISSUE TITLE
New FileUpload mode: simple with autoUpload and ajax

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#1077]
It's a really nice feature to provide a autoUpload with ajax for the simple mode.

**Comment by tandraschko** [comment]
If someone wants to implement, please do :D
i currently dont have that time

**Comment by melloware** [comment]
excellent!

**Comment by Rapster** [comment]
Good job! Shouldn't be `addFormDataFromInput` instead of `PrimeFaces.ajax.Request.addFromDataFromInput` though?

**Comment by tandraschko** [comment]
You mean "from" vs "form? Would be great If you can fix it, should be "FormData" of corse
