### ISSUE TITLE
Documentation: Incorrect code in tree - Getting started

### ISSUE THREAD

**Issue by rdebusscher** [primefaces/primefaces#1079]
The documentation (PDF) has an error in the _getting started_ code example (3.141 in latest available PDF) of Tree component.

```
public TreeBean() {
             root = new TreeNode("Root", null);
           ...
```

But Treenode is (now) an interface and can't be instantiated. It must be changed to **DefaultTreeNode** probably.

**Comment by sudheerj** [comment]
All the examples of Tree component need to be modified with DefaultTreeNode.
