### ISSUE TITLE
DataTable: Initialized filteredValue collection leads to problems

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#10793]
### Describe the bug

When initializing the `filteredValue` attribute with an empty list, the `DataTable` displays all values of the value list, but any actions in the displayed rows do not work.

I can understand a bit how initializing the `filteredValue` attribute with an empty list might be a problem. If no code-based fix is possible, maybe you could add a prominent hint in the documentation and the attribute description?

A reproducer is attached.
[primefaces-test-datatable-filteredvalue-nonnull.zip](https://github.com/primefaces/primefaces/files/12856309/primefaces-test-datatable-filteredvalue-nonnull.zip)

### Reproducer

1. Open the "Select Action" MenuButton of any row.
2. Click on "Show Message"

### Expected behavior

The `FacesMessage` added in the action method should be displayed by the `p:growl` component.

### PrimeFaces edition

None

### PrimeFaces version

13.0.1

### JSF implementation

All

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
This one is really bizarre @Rapster I can confirm if you simply change..

```java
private List<TestObject> filteredList = new ArrayList<>();
```

To 
```java
private List<TestObject> filteredList;
```

it all works?

**Comment by tandraschko** [comment]
Currently its expected: https://github.com/primefaces/primefaces/blob/a2f99a9433b07172307640f7001b9116e2bbd45e/primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java#L285

not sure if we can fix it; filteredValue is just a bit weird
