### ISSUE TITLE
MOVE_SCRIPTS_TO_BOTTOM breaks with facelets

### ISSUE THREAD

**Issue by adam-waldenberg** [primefaces/primefaces#10790]
### Describe the bug

Using a `ui:composition` together with a `ui:decorate` or `ui:include` on the same page causes PrimeFaces to initialize multiple times when used in combination with `primefaces.MOVE_SCRIPTS_TO_BOTTOM`, causing the behavior of the components to break.

Inspecting the raw HTML, it's evident the same block of code is being run twice.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

11

### Browser(s)

Chrome 117

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

I use MOVE_SCRIPTS_TO_BOTTOM in all my projects with complex Facelets and I have never run into this.  So a reproducer to see the actual issue so we can debug would be great!

**Comment by adam-waldenberg** [comment]
This consistently breaks. For now, running with `MOVE_SCRIPTS_TO_BOTTOM` disabled solves the issue.

## edit.xhtml
```
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
	<ui:composition template="/template/common.xhtml">
		<ui:param name="title" value="Some title" />
		<ui:define name="content">
                        <!-- other code -->
			<ui:decorate template="/template/project-form.xhtml" />
		</ui:define>
	</ui:composition>
</html>
```

## WEB-INF/template/project-form.xhtml
```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
	<h:form enctype="multipart/form-data">
            <!-- components here will break -->
	</h:form>
</html>
```

## WEB-INF/template/common.xhtml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui">
	<h:head>
		<!-- some random stuff -->
		<f:metadata>
			<o:enableRestorableView />
		</f:metadata>
	</h:head>
	<h:body>
		<ui:insert name="content" />
	</h:body>
</html>
``

**Comment by melloware** [comment]
OK I have your use case but its working for me:
[pf-10790.zip](https://github.com/primefaces/primefaces/files/12850421/pf-10790.zip)

Unzip and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

**Comment by adam-waldenberg** [comment]
Looks like `p:spinner` doesn't really care... However, inspecting the page I can see the duplication:

```
pf.cw("Spinner","widget_j_idt6_j_idt7",{id:"j_idt6:j_idt7",thousandSeparator:" ",decimalSeparator:","});document.getElementById('7f60bc4d-438b-48f1-bf2a-a452a3ab20ae').remove();
pf.cw("Spinner","widget_j_idt6_j_idt7",{id:"j_idt6:j_idt7",thousandSeparator:" ",decimalSeparator:","});document.getElementById('415cff03-bb17-46d6-be8e-23f0809093f5').remove();
```

Digging around with your test I managed to get it working by removing the `html` tag inside `project-form.xhtml`. Replacing it with `div` (or anything else for that matter) fixes it and I now get only a single entry when inspecting the HTML code:

```
pf.cw("Spinner","widget_j_idt6_j_idt7",{id:"j_idt6:j_idt7",thousandSeparator:" ",decimalSeparator:","});document.getElementById('af27e95d-acdb-4927-84dd-d00cbd3f089c').remove();
```

I can confirm that it also fixes the original example with a much more complex page.

**Comment by melloware** [comment]
Ahh yes only one html, head, and body should be in your whole page.

**Comment by adam-waldenberg** [comment]
Indeed. It happens very easily with templating... So not really a bug... And actually `p:log` was giving me the following hint;

![image](https://github.com/primefaces/primefaces/assets/1555683/54a204c1-4672-482f-99ac-774760b0b4ad)

Which really should have pointed me in the right direction faster. Maybe this debug message could be expanded with some extra tips.

**Comment by melloware** [comment]
I am wondering if JSF itself should log a warning in dev mode like it does with nested Forms?

**Comment by tandraschko** [comment]
maybe talk with omnifaces guys to implement it like nested forms detection? they can later port it to faces specs.

**Comment by melloware** [comment]
OK opened OmniFaces ticket and PR here.
