### ISSUE TITLE
DataTable: Sort is lost after data refresh when using dynamic columns

### ISSUE THREAD

**Issue by gunnarschmid** [primefaces/primefaces#10797]
### Describe the bug

Use a p:dataTable with dynamic columns (p:columns), sort data by a column, refresh underlying data: sort order is lost.

(See also https://github.com/primefaces/primefaces/issues/7951)

### Reproducer

https://github.com/gunnarschmid/primefaces-test

Call http://localhost:8080/primefaces-test/columns.xhtml, sort by any column, hit "Update" button.

### Expected behavior

The sort order shall be kept, and the visual indication of the sorted column shall be kept, too.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

All

### JSF version

2.2

### Java version

17

**Comment by melloware** [comment]
here is a packaged one and i moved eveyrthing to our test.xhtml page but the instructions are the same as above.
[pf-10793.zip](https://github.com/primefaces/primefaces/files/12857396/pf-10793.zip)

**Comment by Rapster** [comment]
You call `DataTable#resetColumns`, which reset every info related to columns. The behavior you're describing is therefore normal
