### ISSUE TITLE
p:selectOneMenu: not responding keyboard input after button is clicked

### ISSUE THREAD

**Issue by jmasinter** [primefaces/primefaces#10792]
### Describe the bug

To recreate:

https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

Click the down arrow next to Basic, Lazy or Long Item Label

Try using keyboard input to make a selection, does not select anything.
This behavior will work properly if the click to open is made anywhere else on the menu besides the button. 

### Expected behavior

When clicking the down-arrow button to open the select menu, focus should be moved to the list component so that keyboard input can select one of the items in the dropdown.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### JSF implementation

Mojarra

### JSF version

2.3.14.SP04

### Java version

11

**Comment by FlipWarthog** [comment]
I think this is already fixed if it's the same as https://github.com/primefaces/primefaces/issues/10355

**Comment by jmasinter** [comment]
Yup looks like the same issue-  I was mistaken and was using 13.0.0 not 13.0.1, looks like it is fixed there.
Thank you so much!
