### ISSUE TITLE
TabView: reverting selected tab after activeIndex updating server side

### ISSUE THREAD

**Issue by jmasinter** [primefaces/primefaces#10804]
### Describe the bug

Updating p:tabView activeIndex via server-side method seems to cause the tabView to revert to its previous tab after it is re-rendered.

This issue only arose when updating from 13.0.0 to 13.0.1

`			<h:form>
			
			<h:panelGroup  id="tabViewTest">
			#{bean.selectedTabIndex}
			
				<p:tabView activeIndex="#{bean.selectedTabIndex}"> 

					<p:tab title="1">tab1</p:tab>
					<p:tab title="2">tab2</p:tab>

				</p:tabView>
			</h:panelGroup>

				<p:commandButton value="Select tab 1" update="tabViewTest"
					action="#{bean.setSelectedTabIndex(1)}" />
				<p:commandButton value="Select tab 2"  update="tabViewTest"
					action="#{bean.setSelectedTabIndex(2)}" />
			</h:form>`

### Expected behavior

When activeIndex is modified via the server-side method the tabView should be re-rendered with the new tab.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### JSF implementation

Mojarra

### JSF version

2.3.14.SP04

### Java version

11

**Comment by FlipWarthog** [comment]
@jmasinter Can you add a reproducer using the [primefaces-test project](https://github.com/primefaces/primefaces-test)?

**Comment by melloware** [comment]
Interesting as these two minor fixes were all that was added in 13.0.1: https://github.com/primefaces/primefaces/issues?q=is%3Aclosed+milestone%3A13.0.1+Tabview

**Comment by jmasinter** [comment]
OK I see, looks like this is just the "focusOnLastActiveTab" doing its thing
Setting this new parameter to false fixes the issue.   Maybe the default value ought to be false for future versions?

**Comment by melloware** [comment]
Hmm its always been true since it was implemented?

```java
    public boolean isFocusOnLastActiveTab() {
        return (Boolean) getStateHelper().eval(PropertyKeys.focusOnLastActiveTab, true);
    }
```

**Comment by jmasinter** [comment]
I believe the param is new for 13.0.1?
Not sure what the use case for the focusOnLastActiveTab was but I do think a more common case would be to want the tab change to stick when altered server-side (this was the behavior prior to 13.0.1)

Thanks, I will create a reproducer next time :)

**Comment by FlipWarthog** [comment]
Looks like it's new for 13.0.0 if you compare the 12.0.0 docs with 13.0.0:
https://primefaces.github.io/primefaces/12_0_0/#/components/tabview
https://primefaces.github.io/primefaces/13_0_0/#/components/tabview

**Comment by DazzlingBob** [comment]
Just came across this too when migrating from 12.0.5 to 13.0.1.
Tabs are in a dialog and are conditional with "rendered" tag.
My code reopens the same dialog with changed tab conditions.

If the tabview component had more rendered tabs than the current conditions and for example the last was selected
the component wants to select the tab which is currently not rendered because of the tab conditions.
So no tab is selected. ActiveIndex is however correctly set to the first tab (0).

Adding focusOnLastActiveTab="false" to <p:tabView> fixed it!
The default value of focusOnLastActiveTab="true" seems kind of odd to me.

**Comment by melloware** [comment]
I think you are right I will switch it to false.  @nimo23 lots of complaints about TRUE being the default.

Original ticket and conversation: https://github.com/primefaces/primefaces/issues/9517
