### ISSUE TITLE
TextEditor: has functionality to embed videos, but always sanitizes iframe tags

### ISSUE THREAD

**Issue by adam-waldenberg** [primefaces/primefaces#10805]
### Describe the bug

I can embed videos via the `p:textEditor` component. However, with OWASP enabled, the iframe tag for the embedded video is always stripped and there is no visible way to control it.

The HTMLSanitizer should probably be extended, with a `allowIFrame` or `allowEmbed` attribute allowing us to enable/disable this feature (like for the other tag types).

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

11

**Comment by melloware** [comment]
Nice we had just done the same thing for PF SunEditor: https://www.primefaces.org/showcase-ext/sections/sunEditor/basicUsage.jsf
