### ISSUE TITLE
Docs: Wizard docs reference incorrect FlowEvent method names

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#10802]
### Describe the bug

https://primefaces.github.io/primefaces/13_0_0/#/components/wizard

```java
public String handleFlow(FlowEvent event) {
    String currentStepId = event.getCurrentStep();
    String stepToGo = event.getNextStep();
    if(skip)
        return "confirm";
    else
        return event.getNextStep();
}
```

should be

```java
public String handleFlow(FlowEvent event) {
    String currentStepId = event.getOldStep();
    String stepToGo = event.getNewStep();
    if(skip)
        return "confirm";
    else
        return event.getNewStep();
}
```

### Reproducer

https://primefaces.github.io/primefaces/13_0_0/#/components/wizard

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

All

### JSF version

N/A

### Java version

N/A

**Comment by melloware** [comment]
You might want to check its probably wrong in 12.0.0 and 11.0.0 etc too?

**Comment by FlipWarthog** [comment]
Got em all updated, it's been wrong since at least v7.
