### ISSUE TITLE
DatePicker: When date is set via server side, component does not switch to it on picker overlay

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#10817]
### Describe the bug

When I set a date via datePicker I can see that value is set in input and it is selected in picker's overlay. But when I select a date from server side, only input has a correct value but picker's overlay is set to the previous date.

Lets assume this:

1. I select 13.10.2023 in control and I see it like this:
![image](https://github.com/primefaces/primefaces/assets/21099773/7f0ce3d1-6d05-4497-ae61-ff6a488bfaf6)
2. Now by any server side action I set a date to eg. 01.01.2016 and update/reset datePicker value
3. This is what I see in view when I open a picker:
![image](https://github.com/primefaces/primefaces/assets/21099773/2fa3248a-87b2-43ca-a966-cbf178345368)

IMHO _updateViewDate_ should be called on beforeShow event of datePicker

### Expected behavior

When date is selected in server side, both value in input and in picker's overlay should be the same

![image](https://github.com/primefaces/primefaces/assets/21099773/6926b56a-1351-48c7-87c1-227897cfe1e5)

IMHO _updateViewDate_ should be called on beforeShow event of datePicker

### PrimeFaces edition

None

### PrimeFaces version

12

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by melloware** [comment]
We have LOTS of Integration tests for DatePicker so this would surprise me. 
 
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by majkers** [comment]
This component is really buggy. You fixed at least 5 in 13.0.2 version that were issed by me. I know about a few more...so these tests do not convince me... sorry :( I am quite annoyed with this

**Comment by majkers** [comment]
My workaround for this is something like this but it has its cons:
```
<p:datePicker widgetVar="dPwW" onclick="updateCalculatorDate()"... />

<script>
	function updateCalculatorDate() {
		var date = PF('dPwW').getDate();
		if (!date) {
			date = new Date();
		}
		PF('dPwW').jq.datePicker('updateViewDate',null,date);
	}
</script>
```

**Comment by melloware** [comment]
Please provide a reproducer. I can't reproduce your issue in 13.0.2

**Comment by majkers** [comment]
It is a matter of opinion weather You call it a bug or an enhancement. My test teamt called them a bug...

As for this one. Just like I said it is not working in 12 PF version

![image](https://github.com/primefaces/primefaces/assets/21099773/d999f3fd-1300-4bab-b9c8-c73272227945)

**Comment by majkers** [comment]
Reproducer:

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/12893518/primefaces-test-master.zip)

**Comment by melloware** [comment]
Thanks let me test and get back to you

**Comment by melloware** [comment]
ok sorry @majkers if this sound snippy but now its my time to be "annoyed".

1. As stated originally our integration test suite has this test and it works fine and is PASSING.

2. Your code doesn't work in 12.0.0 but does in 13.0.2.

![image](https://github.com/primefaces/primefaces/assets/4399574/37a7807e-01df-49fc-a7d3-9b7e40de50c9)


3. Which means **you did not read** this: https://github.com/primefaces/primefaces#community--elite--pro  and you reported a bug against 12.0.0 without reading that or testing against the latest version.

4. Since you are so "annoyed" i have to assume you pay for PrimeTek PRO Support?  So you should have no problem requesting this through your PRO account.   The community can only fix bugs on the latest version.

But of course thanks for your time to report this issue

**Comment by majkers** [comment]
No I don't have pro account. It is really bad that users that can't migrate to latest version are left with some bugs... OK lets leave it for now.

**Comment by jepsar** [comment]
> It is really bad that users that can't migrate to latest version are left with some bugs...

That's not true. You can use Elite or LTS versions.

**Comment by majkers** [comment]
I will as soon as you pay for it :)
