### ISSUE TITLE
FontAwesome - PRO 

### ISSUE THREAD

**Issue by ekitm** [primefaces/primefaces#10818]
### Describe the bug

How can i integrate Fontawesome - PRO.
I dont have a jar from fontawesome to include this in pom.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.2

### Theme

Omega

### JSF implementation

MyFaces

### JSF version

2.3.16

### Java version

7

**Comment by ekitm** [comment]
With:
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>font-awesome</artifactId>
    <version>6.4.2</version>
</dependency>

i include the free-version

**Comment by jepsar** [comment]
Please use discussions for questions.
