### ISSUE TITLE
Core: Drop Hazelcast

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#10822]
For discussion I have a CaffeineCache provider which uses the awesome Caffeine library.  Now that we are on Java 11 we can use it for 14.0.0+ forward.

HazelCast we can keep but as you can see again today another CVE reported against HazelCast failing our builds.

I would love to swap the two and just we can provide the source code for the HazelCastCache as its not that complex?

**Comment by tandraschko** [comment]
TBH - just get rid of Hazelcast and also dont add Caffeine
we can simply document how a user can use our SPI to add Hazelcast or Caffeine in like 50 lines of code

**Comment by melloware** [comment]
OK great idea. PR submitted I just documented HazelCast and Caffeine in the docs and remove the dependency.
