### ISSUE TITLE
Got 'HTTP Status 404 - Not Found' when try to upload file

### ISSUE THREAD

**Issue by hhallenyang** [primefaces/primefaces#10833]
### Describe the bug

I can upload a PDF file successfully with PrimeFaces 10.0.0 and Primefaces-extensions-6.1.1 on Glassfish 4.1.2 server on Java EE 8 framework. I am now migrating to Glassfish 7.0.9 server on Jakarta EE 10 framework with PrimeFaces 12.0.0 Jakarta version and PrimeFaces-extensions-10.0.0 Jakarta version, then I tried to upload a PDF file. I got the 'HTTP Status 404 - Not Found' error message instead of the PDF page. I traced my code and found out that the PrimeFaces FileUpload listener still received the event with the uploaded file correctly.

### Reproducer

<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html     xmlns="http://www.w3.org/1999/xhtml"
          xmlns:ui="http://java.sun.com/jsf/facelets"
          xmlns:h="http://java.sun.com/jsf/html"
          xmlns:p="http://primefaces.org/ui">

    <h:body>
        <ui:composition>
            <h:panelGroup>
                <p:fileUpload listener="#{myBean.listener()}" 
                              style="width: 845px !important" styleClass="nbwom" 
                              disabled="false" mode="advanced" 
                              auto="true" allowTypes="/(\.|\/)(png|jpe?g|jpeg|jpg)$/" />
                <div style="height: 20px" />
            </h:panelGroup>
        </ui:composition>
    </h:body>
</html>

### Expected behavior

Should upload the file and display the content of the PDF file. 

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0 Jakarta edition

### Theme

default theme

### JSF implementation

All

### JSF version

4.0

### Java version

17  (Glassfish 7.0.9 server on Jakarta EE 10)

**Comment by melloware** [comment]
Can you please try with 13.0.2 and report if it is still an issue?  

If it is still an issue in 13.0.2  please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  There is a Jakarta branch of that Test project all set up for you to reproduce: https://github.com/primefaces/primefaces-test/tree/jakarta

**Comment by hhallenyang** [comment]
Thanks for the quick response. I did change my PrimeFaces version to 13.0.2 and tried the file upload again with the snippet show below. 

<h:body>
        <ui:composition>
            <h:panelGroup>
                <t:generic_file_max_size allowedFileType="JPEG, JPG, PDF, PNG"/>
                <p:fileUpload listener="#{ctrl[method]}" 
                              style="width: 845px !important" styleClass="nbwom" 
                              disabled="#{disabled}"
                              mode="advanced" sizeLimit="#{generic_ctrl.maxImageSize}" 
                              auto="true" allowTypes="/(\.|\/)(pdf|png|jpe?g|jpeg|jpg)$/" 
                              update="#{updates}" />
                <div style="height: 20px" />
            </h:panelGroup>
        </ui:composition>
    </h:body>

I can now upload the jpeg, jpg and png files successfully but still could not upload the PDF file. I still get 'HTTP Status 404 - Not Found' error message when I try to upload the PDF file. I am sure I included the 'pdf' as one of the allowTypes. I also tried to create the sample project but it was too difficult for me. Sorry.

**Comment by tandraschko** [comment]
sorry but this is a issue tracker, no support forum. We need a reproducer to check your code or try to fix a PF bug but this is impossible without reproducer.

creating a sample project is easy when you just fork our project template. everything is in the link melloware posted.

feel free to come back if you have a reproducer.
