### ISSUE TITLE
Wizard: Add `disableOnAjax` attribute for Next/Back navigation

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#10831]
### Description

Similar to Ajax enabled buttons, add attribute to Wizard that will disable Next/Back navigation buttons while Ajax is processing.

### Describe the solution you would like

Similar to `disableOnAjax` on, e.g., CommandButton that applies to the Next/Back navigation buttons of Wizard.

**Comment by melloware** [comment]
@FlipWarthog want me to assign this to you?
