### ISSUE TITLE
MOVE_SCRIPTS_TO_BOTTOM creates invalid JSON

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#10845]
### Describe the bug

Enabling the flag _MOVE_SCRIPTS_TO_BOTTOM_ merges _<script>_ tags with json data into a single script tag which produces invalid JSON since only a single root element is allowed.

JSON data provides important structured data for crawlers like search engines. Also important when using _<p:breadcrumb seo="true">_. 

For all our product pages we lost seo friendly breadcrumb display in google SERPs after moving scripts to bottom.

**Production test 1: single json script tag**

https://search.google.com/test/rich-results/result?id=xW-CNQLnYTbomKc1gvFWzA&hl=de

This product parent page only has a single breadcrumb json and google detects it correctly.

**Production test 2: multiple json script tag**

https://search.google.com/test/rich-results/result?id=762CAHA0q60RGp-ln7Frng&hl=de

This product page has JSON data for its product definition aswell for the breadcrumb. Google only detects the first product json data and breadcrumb json definition is lost.

### Expected behavior

Dont merge script tags with type _"application/ld+json"_ into a single tag. 

Just move them to bottom, but keep them separated.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.2

### JSF implementation

Mojarra

### JSF version

2.3.18

### Java version

8

**Comment by melloware** [comment]
Do you have a simple PF Test reproducer so I can take a look?  I think this one might have to just ignore JSON type scripts we have seen this for another type of script in the past. Let me know.

**Comment by djmj** [comment]
Sorry i dont have a local setup with current PF code base for a reproducer.

**Comment by melloware** [comment]
It should be really easy to reproduce with https://github.com/primefaces/primefaces-test

**Comment by djmj** [comment]
I will have a look and ask my working student to set it up after his current task is finished.

**Comment by melloware** [comment]
@djmj we already fixed this?  See: https://github.com/primefaces/primefaces/issues/3854

We don't touch scripts that are not `application/javascript` type scripts.

**Comment by melloware** [comment]
I am thinking it should only minify and merge application/javascript and all other scripts should be ignored and left inline ?

**Comment by melloware** [comment]
OK I created a reproducer:
[pf-10845.zip](https://github.com/primefaces/primefaces/files/13032769/pf-10845.zip)

**Comment by djmj** [comment]
> I am thinking it should only minify and merge `application/javascript` and all other scripts should be ignored and left inline ?

Thats what i would to to be on the safe side and much thanks for the quick solution. 

Any chance to get this in a 12.0.x elite release after merging?

**Comment by melloware** [comment]
Sorry I can only control 13.0.3 and 14.0.0 branches.
