### ISSUE TITLE
Non-standard "zoom" feature. Problem fixed in Firefox. The problem persists in Chrome.

### ISSUE THREAD

**Issue by vitext** [primefaces/primefaces#10846]
### Describe the bug

On the website (IS Linux, Ubuntu) I did not see the .svg icons.
After adding to css - cascading style:
wonder.{
  zoom: 0.5;
}
wonder.{
  transform:scale(0.5);
  transform-origin: 0 0;
}
... problem solved.
But it doesn't work in Chrome/Chromium. 
Please experience, solution. 
Thank you!

### Reproducer

`html {
    font-size: 10px;
    -webkit-tap-highlight-color: transparent
}
normal {
  zoom: normal;
}

div.{
  zoom: 0.5;
}
div.{
  transform:scale(0.5);
  transform-origin: 0 0;
}

body {
    margin: 0;
    font-family: "Source Sans Pro", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #fff;/*#c8c8c8;bílo šedá barva*/
    background-color: #6f2a6f; /*světle fialová, barva srdečnosti,spyrituality*/
}`

### PrimeFaces edition

Community

### PrimeFaces version

Ubuntu, CMS phpfusion

### Theme

Darkcore

### JSF implementation

MyFaces

### JSF version

6.5

### Java version

6.4

### Browser(s)

Chrome

**Comment by tandraschko** [comment]
this is the issue tracker of PrimeFaces for JavaServerFaces
your issue seems unrelated.
