### ISSUE TITLE
Layout improvment of rowToggler of dataTable in reflow mode needed

### ISSUE THREAD

**Issue by EugenFischer** [primefaces/primefaces#10859]
### Describe the bug

the rowToggler of dataTable in reflow mode is hardly to found.
![Toggler](https://github.com/primefaces/primefaces/assets/13999463/2adc25ce-9e97-47c8-8546-a512f9d4360c)

### Reproducer

1. adapt showcase/ui/data/datatable/expansion.xhtml
```
<p:dataTable var="product" reflow="true" value="#{dtBasicView.products}" rowKey="#{product.id}">
```
2. enforce table to switch in reflow mode (viewport smaller tahn 640 px)

### Expected behavior

row toggler is visable complete

### PrimeFaces edition

None

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3.16

### Java version

17

### Browser(s)

Chrome (116)

**Comment by melloware** [comment]
Got it most likely needs a CSS tweak.

**Comment by melloware** [comment]
CSS workaround can you try...

```css
body .ui-datatable .ui-datatable-data > tr .ui-row-toggler {
  width: unset;
  height: unset;
}
```

**Comment by EugenFischer** [comment]
@melloware thx for the hint
