### ISSUE TITLE
DatePicker: multiple deselect does not fire dateSelect event

### ISSUE THREAD

**Issue by jmasinter** [primefaces/primefaces#10850]
### Describe the bug

In the specific configuration, with selectionMode="multiple" and inline="true", the datePicker does not fire any events when a date is removed.

Selecting a date works fine and triggers the event, but removing the date does not. 

### Reproducer

			<p:datePicker inline="true" selectionMode="multiple" value="#{bean.dateList}">
					<p:ajax event="dateSelect" listener="#{bean.dateSelect}" />
			</p:datePicker>

### Expected behavior

Clicking a selected date to remove it on the inline, multiple selection datePicker should fire the "dateSelect" event.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3.14.SP0

### Java version

11

**Comment by melloware** [comment]
I will investigate

**Comment by melloware** [comment]
Inline doesn't matter it doesn't fire in Popup mode either in MulitSelect mode i think because you are not selecting a date your are de-selecting a date and it looks like this was never handled or requested.

**Comment by jmasinter** [comment]
Probably, the non-inline multiple datePicker doesn't need to fire an event on de-select, because the "close" event will fire and update the value at that time.  In the case of a single date the Clear button typically handles this.  The single valued inline version doesn't allow de-select actually.  

So, seems like a new feature more than a defect, but it does seem that the inline multiple value datePicker should fire an event on de-select to properly enable ajax behavior.

**Comment by melloware** [comment]
Agreed I wonder if we should introduce a `dateUnselect` event like other components have a `itemSelect` and `itemUnselect`?

**Comment by jmasinter** [comment]
The "Clear" button (showButtonBar=true) uses the dateSelect event, so for consistency at least within the scope of the datePicker, maybe it's best to use the same, representing that the multiple date values have changed somehow.

**Comment by melloware** [comment]
Yeah it does because it fires a change event but I was thinking more for multi select not single select

**Comment by melloware** [comment]
@jmasinter here is a MonkeyPatch that will fire `dateSelect` on unselect of items.

```js
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.onDateSelect = function(event, dateMeta) {
        if (this.options.disabled || !dateMeta.selectable) {
            if (event) {
                event.preventDefault();
            }
            return;
        }

        var $this = this;

        if (this.isMultipleSelection()) {
            if (this.isSelected(dateMeta)) {
                var value = this.value.filter(function(date, i) {
                    return !$this.isDateEquals(date, dateMeta);
                });
                this.updateModel(event, value);

                // #10850 notify unselect
                if (this.options.onSelect) {
                    this.options.onSelect.call(this, event, value);
                }
            } else if (!this.options.maxDateCount || !this.value || this.options.maxDateCount > this.value.length) {
                this.selectDate(event, dateMeta);
            }
        } else {
            this.selectDate(event, dateMeta);
        }

        if (!this.options.inline && this.isSingleSelection() && (!this.options.showTime || this.options.hideOnDateTimeSelect)) {
            PrimeFaces.queueTask(function() {
                $this.hideOverlay();
            }, 100);

            if (this.mask) {
                this.disableModality();
            }
        }

        if (event) {
            event.preventDefault();
        }
    };
};
```
