### ISSUE TITLE
DataExporter: PDF Option FontName results in non-bold column header

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#10863]
### Describe the bug

When setting a font-name in PDFOptions for p:dataExporter, the column header text in the exported PDF is not bold for all columns.

This is the result of the PDF Exporter: [products.pdf](https://github.com/primefaces/primefaces/files/13052256/products.pdf)

This relates to https://github.com/primefaces/primefaces/issues/2363

### Expected behavior

All column headers in exported PDF should be bold.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

Rain

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

[primefaces-test-export.zip](https://github.com/primefaces/primefaces/files/13052247/primefaces-test-export.zip)

**Comment by rho66** [comment]
Exporting as XLS, opening with LibreOffice and exporting from LibreOffice as PDF works as expected - see attachments. 
[products.pdf](https://github.com/primefaces/primefaces/files/13066294/products.pdf)
[products.xls](https://github.com/primefaces/primefaces/files/13066295/products.xls)

**Comment by rho66** [comment]
It seems also that not all fonts are applied to the PDF!

`pdfOptions.setFontName("Comic Sans MS");`

resulting PDF attached.
[products (5).pdf](https://github.com/primefaces/primefaces/files/13066332/products.5.pdf)

**Comment by stolp** [comment]
Did you check if  your font has been registered with your com.lowagie.text.FontFactory ?

**Comment by rho66** [comment]
Why? I am using a dependency for OpenPDF as recommended [here](https://primefaces.github.io/primefaces/12_0_0/#/components/dataexporter)

**Comment by stolp** [comment]
OpenPDF is based on a fork of iText. Thus the class names will be identical to iText classes.

The default font registry does not include "Comic Sans MS", so you will have to manually add it before you can use it.

**Comment by rho66** [comment]
How can I check this? No idea where to set a breakpoint therefore!

**Comment by stolp** [comment]
Have a look at the OpenPDF Sources here:

https://github.com/LibrePDF/OpenPDF/blob/master/pdf-toolbox/src/test/java/com/lowagie/examples/fonts/getting/RegisterFont.java

**Comment by melloware** [comment]
@rho66 A couple of things.

1) I have confirmed PF is setting the Font and sending it to iText.  Its not being rendered in Bold because the font "Arial" must not support bold of those special characters.

2) That means you have to choose a font that DOES support it.

3) PF only passes the font name you give it to iText but if iText has not registered that font YOU need to register it like @stolp said. https://stackoverflow.com/questions/31746950/how-to-load-custom-font-in-fontfactory-register-in-itext

**Comment by rho66** [comment]
What have I done so far:

- download Comic_Sans_MS_Bold.ttf and added to the resources/fonts folder
- registered font
- set font in PDF Options

Results in:

- Exported column header are now using "Comic Sans MS" font
- special characters still not in PDF
- but special characters are shown in UI column headers

Find attached my reproducer and the resulting PDF
 
[primefaces-test-export.zip](https://github.com/primefaces/primefaces/file
[products.pdf](https://github.com/primefaces/primefaces/files/13111311/products.pdf)
s/13111307/primefaces-test-export.zip)

**Comment by melloware** [comment]
I get this:
![image](https://github.com/primefaces/primefaces/assets/4399574/22f20bd6-d058-40d4-a365-4f44e087d16e)

When I run this standalone JAva program:

```java
package org.primefaces.test;

import java.io.FileOutputStream;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfWriter;

public class SimpleITextPDF {
    public static void main(String[] args) {
        // Step 1: Create a new document
        Document document = new Document();

        try {
            // Step 2: Create a PdfWriter and specify the output file
            PdfWriter.getInstance(document, new FileOutputStream("SimpleITextPDF.pdf"));

            // Step 3: Open the document for writing
            document.open();

            // Step 4: Load a custom font
            BaseFont customFont = BaseFont.createFont("C:\\Windows\\Fonts\\consola.ttf", BaseFont.IDENTITY_H,
                    BaseFont.EMBEDDED);
            BaseFont orangeJuice = BaseFont.createFont("C:\\temp\\primefaces\\pf-10863\\orange juice 2.0.ttf",
                    BaseFont.IDENTITY_H, BaseFont.EMBEDDED);

            // Step 5: Create a Font object with the custom font and set it to bold
            Font boldFont = new Font(customFont, 12, Font.BOLD);
            Font boldOjFont = new Font(orangeJuice, 12, Font.BOLD);
            Font normalFont = new Font(customFont, 12, Font.NORMAL);
            Font normalOjFont = new Font(orangeJuice, 12, Font.NORMAL);

            // Step 6: Add bold content to the document
            Paragraph customBold = new Paragraph("This is a bold text: Total-∑ [€]", boldFont);
            document.add(customBold);
            Paragraph ojBold = new Paragraph("This is a bold Orange Juice text: Total-∑ [€]", boldOjFont);
            document.add(ojBold);

            // Step 7: Add plain content to the document
            Paragraph customPlain = new Paragraph("This is a plain text: Total-∑ [€]", normalFont);
            document.add(customPlain);
            Paragraph ojPlain = new Paragraph("This is a plain Orange Juice text: Total-∑ [€]", normalOjFont);
            document.add(ojPlain);

            // Step 8: Close the document
            document.close();

            System.out.println("PDF created successfully.");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

**Comment by melloware** [comment]
@rho66 got it working:
[pf-10863.zip](https://github.com/primefaces/primefaces/files/13125306/pf-10863.zip)

You were missing this `encoding` piece:
```xml
<p:dataExporter type="pdf" target="products" fileName="products" pageOnly="true" visibleOnly="true" encoding="Identity-H"
                            options="#{exportView.pdfOptions}" />
```

I am going to make it the default for PDF.

**Comment by rho66** [comment]
Using `encoding="Identity-H"` works in your example where you have registered `consola.ttf`as bold font.

Using PDFOptions without `pdfOptions.setFontName("my_bold_font");` results in
`ExceptionConverter: java.io.UnsupportedEncodingException: Identity-H`

Using PDFOptions with `pdfOptions.setFontName("Arial");` still results in non-bold column header but with special characters:

[products.pdf](https://github.com/primefaces/primefaces/files/13161567/products.pdf)

The challenge for me is now, to find a way, where I find the `consola.ttf` Font on non-Windows systems, because we are running our production environment under Linux while development is under Windows!

**Comment by rho66** [comment]
I am also using different mime type mappings in my `web.xml` !

```
    <mime-mapping>
        <extension>ttf</extension>
        <mime-type>application/font-sfnt</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>woff</extension>
        <mime-type>application/font-woff</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>woff2</extension>
        <mime-type>application/font-woff2</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>eot</extension>
        <mime-type>application/vnd.ms-fontobject</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>eot?#iefix</extension>
        <mime-type>application/vnd.ms-fontobject</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>svg</extension>
        <mime-type>image/svg+xml</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>svg#exosemibold</extension>
        <mime-type>image/svg+xml</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>svg#exobolditalic</extension>
        <mime-type>image/svg+xml</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>svg#exomedium</extension>
        <mime-type>image/svg+xml</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>svg#exoregular</extension>
        <mime-type>image/svg+xml</mime-type>
    </mime-mapping>
    <mime-mapping>
        <extension>svg#fontawesomeregular</extension>
        <mime-type>image/svg+xml</mime-type>
    </mime-mapping>

```

**Comment by melloware** [comment]
OK I have both Windows and Linux.

On **Windows** if I leave `encoding="Identity-H"` and set `pdfOptions.setFontName("Consolas");` it works as Consolas has bold for special characters.  You can see all Windows Fonts here: https://learn.microsoft.com/en-us/typography/fonts/windows_10_font_list

On **Linux** you have to do a few things.

1. Find out what fonts you have by running `$ fc-list`  That will list all the fonts registered.

2. In your code your need to register all fonts in Unix in my case in `/usr/share/fonts` because I am on Ubuntu 22.0.4

```java
    private void initFonts() {
        try {
            FontFactory.registerDirectory("/usr/share/fonts", true);
            for (String fontName : FontFactory.getRegisteredFonts()) {
                LOGGER.info(fontName);
            }
        } catch (Throwable ex) {
            throw new RuntimeException(ex);
        }
    }
```

3. Pick a font that supports bold in my case I picked Ubuntu Mono font  

```java
pdfOptions.setFontName("ubuntu mono");
```

4. Voila it works fine.

![image](https://github.com/primefaces/primefaces/assets/4399574/2d6e797c-4d72-4b6d-abdc-1b9c36489db5)

**Comment by stolp** [comment]
It is usually not a good solution to rely on locally installed fonts.

If you are not hindered by copyright restrictions, it is the best solution to add the fonts to your web application.

**Comment by melloware** [comment]
Totally agree @stolp I am just trying to prove to @rho66  this is NOT a PrimeFaces issues its an iText issue and understanding how iText works.

**Comment by rho66** [comment]
Thnx to @melloware  and @stolp 

I solved it by adding the font to my web application and everything works fine!

Could be closed from my perspective ;-)

**Comment by melloware** [comment]
Nice!
