### ISSUE TITLE
SelectOneMenu: Float Label does not work with selecItem value=null

### ISSUE THREAD

**Issue by danteCarvalho** [primefaces/primefaces#10866]
### Describe the bug

 Float Label does not work with p:selectOneMenu when there is a converter.
Even if there is no value selected, the ui-inputwrapper-filled class is always present.

### Reproducer

```html
<div class="field">
<span class="ui-float-label">
	<p:selectOneMenu
		converter="#{produtoConverter}"
	>
		<f:selectItem   />
	</p:selectOneMenu>
	<p:outputLabel
		for="@previous"
		value="AAAAA"
	>
	</p:outputLabel>
</span>
</div>
```

### Expected behavior

The floating label should appear inside the selectOneMenu when there is nothing selected.
The  ui-inputwrapper-filled class shoud be set only when a value is selected.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### Theme

default

### JSF implementation

Mojarra

### JSF version

JavaServer(TM) Faces 2.2 API

### Java version

8

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

I can't reproduce so I have a feeling its something your converter is returning? So a reproducer will help us debug your issue.

**Comment by danteCarvalho** [comment]
[primefaces-test-jpa.zip](https://github.com/primefaces/primefaces/files/13061200/primefaces-test-jpa.zip)
 
Here, as  i said its not working as it should, the ui-inputwrapper-filled  class is already set when the page is rendered.
Making the floating label go above the input when it should be inside.

Well, maybe the problem is me and i don't know how to implement a converter =p

**Comment by melloware** [comment]
Thanks for the reproducer let us investigate!

**Comment by FlipWarthog** [comment]
@danteCarvalho The `getAsString` impl in your converter is returning null if `value` is null.

The docs for `getAsString` specify:

> Returns
>   a zero-length String if value is null, otherwise the result of the conversion

So if you change that method to:
```java
@Override
public String getAsString(FacesContext arg0, UIComponent arg1, Object value) {
	System.out.println("getAsString " + value);
	return value == null ? "" : ((TestJpa) value).getId().toString();
}
```
it resolves the issue.

@melloware it looks like it propagates up as a nbsp in the select>option, so `updateFloatLabel` in core.util.js things it has a value.

**Comment by melloware** [comment]
That all sounds correct thanks @FlipWarthog

**Comment by danteCarvalho** [comment]
Thanks it worked!! I've been using it the wrong way for like 10 years.
Before creating the issue i have looked at the converters on the primefaces github and they have null too, i guess you should update.

**Comment by melloware** [comment]
Yep it should let me fix.

**Comment by tandraschko** [comment]
For me it looks like we can easily support both; there should be no different between empty string or not existing value attr in our js

**Comment by melloware** [comment]
If I remember I have to look through the commits but there was definitely a reason they were treated differently.

**Comment by tandraschko** [comment]
TBH i dont think there is a difference.

I checked both MF and PF code and we do this:
```java
String value = converter.getAsString(...);
if (value != null) {
     writer.writeAttr('value', value);
}
```

so the difference is a empty value attr or not-existing value attr.
on a normal inputText, there is absolutely no difference when. Both results in a empty string in the POST.

Therefore i dont think we should make a difference in the float label

**Comment by melloware** [comment]
OK I think the issue is specifically for SelectOne and how it renders labels with all the different possible combinations of escaped, custom label, etc.

**Comment by tandraschko** [comment]
just think about that something like that should work; just the idea, not tested yet.  chips must just pass the hinput instead input and we can rid of the that werid .ui-chips-token IF.

```
        updateFloatLabel: function(element, input, hasFloatLabel) {
            if (!element || !input || !hasFloatLabel) {
                return;
            }

            var isEmpty;
            if (input.is(':input')) {
                var inputVal = input.attr('val');
                isEmpty = inputVal === null || inputVal === '';
            }
            else {
                isEmpty = input.find('option:selected').length === 0;
            }

            if (isEmpty) {
                element.removeClass('ui-inputwrapper-filled');
            }
            else {
                element.addClass('ui-inputwrapper-filled');
            }
        },
```

**Comment by melloware** [comment]
Sounds good to me I always thought it was a little funky!

**Comment by tandraschko** [comment]
ok, selectOneMenu always has a selected item, therefore selectOneMenu/single selection needs a special handling.
this works for me:


```xml
        updateFloatLabel: function(element, input, hasFloatLabel) {
            if (!element || !input || !hasFloatLabel) {
                return;
            }

            var isEmpty;
            if (input.is('select')) {
                if (input.attr('multiple')) {
                    isEmpty = input.find('option:selected').length === 0;
                }
                else {
                    var value = input.find('option:selected').attr('value');
                    isEmpty = value === null || value === '';
                }
            }
            else {
                isEmpty = input.val();
            }

            if (isEmpty) {
                element.removeClass('ui-inputwrapper-filled');
            }
            else {
                element.addClass('ui-inputwrapper-filled');
            }
        },
```

would you like to retest? chips just need to pass the hinput instead input; can create a PR tomorrow
 everything on http://localhost:8080/showcase/ui/misc/floatLabel.xhtml seems to work
