### ISSUE TITLE
DataTable: Copy incoming list instead of using original. Sorting fails with immutable list

### ISSUE THREAD

**Issue by arnis87** [primefaces/primefaces#10862]
### Description

With introduction to newer java versions the IDE suggest to switch from using `stream.collect(Collectors.toList())` to `stream.toList()` but this changes the behavior - 
`toList()` constructs unmodifiable list when `collect(toList)` is modifiable.

I think this conversion makes a lot sense when there is dataset that is not supposed to change after creation but when it is thrown into sortable `DataTable` it starts to fail with unsupported exception. For `DataTable.filter` function this is not issue  - I would assume it is because it performs its operations on copy to keep track of the original. 

Would it be possible to introduce similar behaviour for sort functionality? To copy the incoming list instead of processing the original?

### Describe the solution you would like

Implement support for immutable/unmodifiable list for sortable `DataTable`.

### Additional context

PF 12, JSF 2.3

**Comment by melloware** [comment]
@arnis87 i just looked through the whole PrimeFaces codebase and we always do `.collect(Collectors.toList())` . So what is your issue?

**Comment by FlipWarthog** [comment]
I think they're saying they switched to `stream.toList()` (based on IDE suggestion) in their app and it's causing errors in sort. But the same doesn't happen with filter, so it's not consistent behavior. Filter must be copying the list to a modifiable one whereas sort is using the passed in list, as-is.

**Comment by jepsar** [comment]
I guess it's about the data passed in the value attribute.

**Comment by FlipWarthog** [comment]
I'll wait for @arnis87 to confirm, but I agree with @jepsar . I think this is an app impl change, not a PF change.

Which IDE are you using? I think its suggestion is only half baked.. 

`Collectors#toList` javadoc:
> Returns a Collector that accumulates the input elements into a new List. _There are no guarantees on the type, mutability, serializability, or thread-safety of the List returned; if more control over the returned List is required, use toCollection(Supplier)._

.. this would, in general, imply that switching to the new `Stream#toList` is the way to go:

`Stream#toList` javadoc:
> The returned List is unmodifiable; calls to any mutator method will always cause UnsupportedOperationException to be thrown. _There are no guarantees on the implementation type or serializability of the returned List._

But I think in this case, the alternative in the `Collectors#toList` doc is actually better:

Old:
```java
// Accumulate names into a (potentially) unmodifiable List
List<String> list = people.stream()
  .map(Person::getName)
  .collect(Collectors.toList());
```

IDE suggestion:
```java
// Accumulate names into a (definitely) unmodifiable List
List<String> list = people.stream()
  .map(Person::getName)
  .toList();
```

Better suggestion, in this case:
```java
// Accumulate names into a (definitely) modifiable List
List<String> list = people.stream()
  .map(Person::getName)
  .collect(Collectors.toCollection(ArrayList::new));
```

**Comment by arnis87** [comment]
> I think they're saying they switched to `stream.toList()` (based on IDE suggestion) in their app and it's causing errors in sort. But the same doesn't happen with filter, so it's not consistent behavior. Filter must be copying the list to a modifiable one whereas sort is using the passed in list, as-is.

That is exactly what I meant. This is about the list that is passed as value attribute for `DataTable`. When the `DataTable `is sortable the list that is used cannot be unmodifiable/immutable or the the `DataTable `code will throw exception when user tries to sort. This implies that GUI will modify the underlying data when users sorts, to me this is kind of unexpected behaviour. When user filters on the table this is not an issue, the original list is not altered based on the filter. 
I agree that this could solved by simply passing in mutable list or making the copy in my code but if possible I would very much like to avoid this extra code in each of such situation. I would also like to avoid giving permission to mutate data outside current scope.
It was just a suggestion/something to consider, if you do not agree I can solve this on my own.

**Comment by melloware** [comment]
I will leave this up to @Rapster and @tandraschko do decide as I am indifferent on this.

**Comment by tandraschko** [comment]
IMO its not worth to change something here. WDYT @Rapster ?

**Comment by Rapster** [comment]
Same
