### ISSUE TITLE
GMap geocode event listener are invoked only when result is not empty

### ISSUE THREAD

**Issue by miron4dev** [primefaces/primefaces#1086]
1. Use the example from http://www.primefaces.org/showcase/ui/data/gmap/geocode.xhtml
2. Type some nonexistent location 
3. onGeocode method will not be invoked.

**Comment by melloware** [comment]
This is as designed.  Your JS console will display "Geocode was not found" if google reports it as a failure. There is no data from google to then forward to the GeoCode event.  

https://github.com/primefaces/primefaces/blob/92ac4a87a74766a1ae4c9c934a163deb18011f43/src/main/resources/META-INF/resources/primefaces/gmap/gmap.js#L133-L159
