### ISSUE TITLE
DataTable: Virtualscroll=true messing up data and button actions

### ISSUE THREAD

**Issue by AlessandroBori** [primefaces/primefaces#10875]
Environment: PF 13.0.2 /mojarra23

Datat table with virtual scroll enabled and fetching 40 rows per time

Three issues:

rowexpansion :
  1. Command buttons placed into rowexpansion never fires its Action function
  2. After load the second chunk of data and then returning to the first one, data shown into rowexpansion refers to wrong values

Command buttons

3. After load the second chunk of data, command buttons placed in columns don't work anymore

Test attached for further investigations

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13068148/primefaces-test-master.zip)

**Comment by AlessandroBori** [comment]
More info: 
 
- first two issues were already present in 12.X releases
- third issue popped up in 13.x release

**Comment by melloware** [comment]
I don't think Virtual Scrolling and Row Expansion are features meant to be used together.   Not all datatable features are compatible with each other.

**Comment by melloware** [comment]
See this issue: https://github.com/primefaces/primefaces/issues/10263

**Comment by melloware** [comment]
If you have Virtual Scrolling issues when NOT using the RowExpansion feel free to open another ticket.

**Comment by AlessandroBori** [comment]
> I don't think Virtual Scrolling and Row Expansion are features meant to be used together. Not all datatable features are compatible with each other.

It will be a nice feature indeed. If i have time i'm look at it





> If you have Virtual Scrolling issues when NOT using the RowExpansion feel free to open another ticket.

3rd point isn't about Row Expansion

**Comment by melloware** [comment]
Yes but your reproducer has a RowExpansion.  Can you create a reproducer that doesn't use Row Expansion that shows your 3rd issue?

**Comment by melloware** [comment]
@AlessandroBori i think this is your issue: https://github.com/primefaces/primefaces/issues/10902 ???

**Comment by AlessandroBori** [comment]
yes, someone has been faster than me in reporting
