### ISSUE TITLE
InputTextarea: Autocomplete overlay panel is behind dialog

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#10876]
### Describe the bug

If the inputtextarea with active autocomplete is used in the dialog, then the autocomplete overlay panel is displayed behind dialog after clicking into inputtexarea element.

![image](https://github.com/primefaces/primefaces/assets/13416467/f3e9cde2-b491-4f3a-b780-487e510f220f)

Could you fixed it the same way like in forms.selectcheckboxmenu, please? using triggers?
```
    init: function(cfg) {
        this.triggers = this.jq;
    }

    _render: function() {
        this.triggers.data('primefaces-overlay-target', true);
    }
```

### Reproducer

1. make inputtextarea in dialog with active autocomplete
2. enter some text
3. autocomplete overlay panel with suggestions is displayed
4. click intu inputtextarea element
5. autocomplete overlay panel is behind dialog

### Expected behavior

The autocomplete overlay is visible when clicking into inputtextarea element.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### JSF implementation

Mojarra

### JSF version

2.3.20

### Java version

11

**Comment by melloware** [comment]
@vonnai care to submit a PR?

**Comment by vonnai** [comment]
I'll try. Just give me a time.

**Comment by melloware** [comment]
I will backport it to 13.0.3 when you submit.

**Comment by vonnai** [comment]
it's there, please, check it.

**Comment by vonnai** [comment]
The PR is created, but it's not joined with this issue, what's wrong?
