### ISSUE TITLE
InputSwitch: Deprecate in 14 remove in 15

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#10874]
### Describe the bug

First time I open a dialog with some p:inputSwitch component, and I try to switch it, it automatically flips back. See screenshot movie:

https://github.com/primefaces/primefaces/assets/771606/b4a92335-bf27-411e-9904-aa83d182485f

Second time that I open the dialog, the p:inputSwitch component behaves as expected.

### PrimeFaces edition

None

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by melloware** [comment]
That is unexpected.  Can you put together a PrimeFaces Test reproducer?

**Comment by fcorneli** [comment]
Cannot replicate it via `primefaces-test`. Have to dig into my app to see exactly why this happens...

**Comment by melloware** [comment]
OK let us know.  I was hoping you would say that.

**Comment by fcorneli** [comment]
lol... it's for sure the better option for you. :)

**Comment by fcorneli** [comment]
[10874.zip](https://github.com/primefaces/primefaces/files/13074052/10874.zip)

Now tell me @melloware, what is going on here? After 200 pages Enterprise JSF seems like I still don't get it... :)

**Comment by melloware** [comment]
Try this:
[pf-10874.zip](https://github.com/primefaces/primefaces/files/13074239/pf-10874.zip)

InputSwitch is deprecated and isn't even on the Showcase anymore PrimeTek wanted you to switch to ToggleSwitch since 6.2.

**Comment by fcorneli** [comment]
`dynamic="true"` solves the issue, but why?

**Comment by fcorneli** [comment]
ok ok ok... a big "DEPRECATED" in the taglib description wouldn't hurt I guess.
<img width="521" alt="input-switch-tag-doc" src="https://github.com/primefaces/primefaces/assets/771606/ecb64711-1dc7-4665-be59-12910dcfe900">
Anyway, thanks.

**Comment by melloware** [comment]
Yep going to update the stuff right now. It should have been removed.   But I will mark it deprecated in 14.0.0 and marked for removal in 15.0.0
