### ISSUE TITLE
SelectOneMenu: leaving the overlay refocus the input again?

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10880]
Currently i'm here: http://localhost:8080/showcase/ui/misc/floatLabel.xhtml

if you click the dropdown, the overlays opens
if you click outside the overlay, somewhere in the page, the float label flickers as the dropdown gets focused again (but without opening the overlay)

seems like a weird refocus?

**Comment by melloware** [comment]
Agreed that is not good.

**Comment by melloware** [comment]
I think its related to this: https://github.com/primefaces/primefaces/issues/10721

**Comment by tandraschko** [comment]
can you please check it?
dont like to just revert it but dont have to much time.

**Comment by melloware** [comment]
Yes I will look today
