### ISSUE TITLE
Primefaces Editor p:editor not displayed in Firefox / IE, when inside dialog iframe

### ISSUE THREAD

**Issue by regenduft** [primefaces/primefaces#1088]
I am opening a dialog inside my bean with

RequestContext.getCurrentInstance().openDialog("emailComposerDialog", options, params);

Thus, the email composer is displayed by primefaces inside an iframe.

But the p:editor component (inside this dialog) is NOT displayed anymore, after we upgraded to primefaces elite 5.3.6
It was still working fine with the version primefaces elite 5.3.5

It still works in chrome, and it also works if the dialog is opened directly, not inside an iframe.
It does not work in Microsoft Internet Explorer 11 and not in Firefox. We didn't test Safari yet.

**Comment by mertsincan** [comment]
Can you please attach sample codes for us to replicate?
