### ISSUE TITLE
Remove Code in 15.0.0 Reminder

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#10909]
- [x] Remove Apache Commons FileUpload stuff (https://github.com/primefaces/primefaces/issues/10751)
- [x] Remove InputSwitch (https://github.com/primefaces/primefaces/issues/10874)
- [x] Remove legacy Chart.JS components and all PF models (https://github.com/primefaces/primefaces/issues/10870)
- [x] Remove `@Deprecated` legacy "table" layouts
- [x] Remove `@Deprecated` FileUpload properties
- [x] Remove `@Deprecated` DataExporter code

**Comment by Rapster** [comment]
I saw this also https://github.com/primefaces/primefaces/issues/9282#issuecomment-1409158158 ?

**Comment by melloware** [comment]
Yep I removed all the tabular's except for PanelGrid as we decided its so popular!

**Comment by melloware** [comment]
@Rapster if you don't mind looking at DataExporter though I didn't want to touch that one.

**Comment by Rapster** [comment]
> Yep I removed all the tabular's except for PanelGrid as we decided its so popular!

So we keep supporting that one "Grouping (deprecated)" in https://www.primefaces.org/showcase/ui/panel/panelGrid.xhtml ?

> @Rapster if you don't mind looking at DataExporter though I didn't want to touch that one.

I will

**Comment by melloware** [comment]
Yes I should remove the "Deprecated" from that Showcase panelgrid :)

**Comment by melloware** [comment]
@Rapster all that is left is DataExporter on this ticket. Any chance you could remove the deprecated stuff?
