### ISSUE TITLE
DatePicker: Today button does not set time

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#10901]
### Describe the bug

A click to DatePicker `Today` button does only set the date part to the current date. The time part is unchanged.

When click on Calendar components `Current Date` button, date is set to current date and time.

### Reproducer

[primefaces-test-datepicker.zip](https://github.com/primefaces/primefaces/files/13164359/primefaces-test-datepicker.zip)

### Expected behavior

A click to DatePicker `Today` button should set date to current date and time.

Or is there a way to achieve the same behavior than Calendar does.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.4, 13.0.0

### Theme

Rain

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Already fixed in 13.0.2: https://github.com/primefaces/primefaces/issues/10725
