### ISSUE TITLE
DataTable: Placeholder for column filter input

### ISSUE THREAD

**Issue by DerIngo** [primefaces/primefaces#10918]
### Description

It would be useful to be able to set a placeholder for the filter input of a column.
Maybe something like this:

`<p:column filterBy="#{item.name}" filterPlaceholder="John Doe">`

This addon was implemented for primeng in 2016 by @Mrtcndkn, see [here](https://github.com/primefaces/primeng/issues/1218).

### Describe the solution you would like

The solution I would like would be the additional 'filterPlaceholder' attribute for the p:column tag.

### Additional context

The **workaround** I found is the p:watermark-tag with **styleClass**-selector:
`<p:column filterBy="#{item.name}" styleClass="filterPlaceholder">`
`  <p:watermark value="John Doe" for="@(.filterPlaceholder)" />`
`</p:column>`

**Comment by melloware** [comment]
@Rapster @tandraschko I know we were trying to reduce props but this is a good argument and all the other Prime libs do have this feature.  

Just for that reason I am ok adding it?

**Comment by Rapster** [comment]
Can pt attributes be used for this?

**Comment by melloware** [comment]
hmmm i would think on a column the PT would be applied to the Column itself and not the Filter input?

**Comment by Rapster** [comment]
Yeah true... 😅

**Comment by tandraschko** [comment]
I think PT are attached to the column but its up to you, where you render it
