### ISSUE TITLE
Focus: Anchors get focused when no input enabled

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#10913]
### Describe the bug

Because of a fix https://github.com/primefaces/primefaces/issues/10115 when we have a page without any focusable inputs and with some anchors. First of them will be focused. According to docs. Focus by default selets input elements. I do not know weather it is good to select anchors when not on dialog.

Here is my reproducer
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13176041/primefaces-test-master.zip)

### Expected behavior

Anchors only in dialogs should be focused and docs should tell users about it

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.2

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by majkers** [comment]
Only a change in documentation? Did you see my reproducer? You really think it is expected behaviuor when not in dialog to select anchors on page? IMHO dialog selector should be added to a:first.

**Comment by melloware** [comment]
For someone who doesn't pay for support you expect an awful lot from an Open Source project?

**Comment by majkers** [comment]
I do not. I do expect from a developer who prepares a fix to bare in mind that it is sometimes a global change and it might affect other parts of application. If you fixed https://github.com/primefaces/primefaces/issues/10115 for dialogs, you should be aware that you can break some other things. That's all

**Comment by majkers** [comment]
This won't help:

![image](https://github.com/primefaces/primefaces/assets/21099773/f66ce85d-2bee-4917-8b61-ba12e445824b)

In my reproducer You can see that I do not use dialog and use context

**Comment by majkers** [comment]
To make it clear:

![image](https://github.com/primefaces/primefaces/assets/21099773/4bb5a2a9-e144-4350-b6b8-aef43c5220c0)

**Comment by melloware** [comment]
Your selector does not work.

**Comment by majkers** [comment]
Yes it does. Here is my previous reproducer with monkey patch.
First check main pange then dialog. You can see that main page has no focused element and in dialog X button is focused because all inputs are disabled. Then change disabled to false and you will see first input focused both on main page and in dialog.
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13185614/primefaces-test-master.zip)
