### ISSUE TITLE
Badge: add onclick or delegate click to child

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#10921]
### Description

Badge on buttons / menu have a usability problem since it reduces the clickable area of the button.

On mobile and a icon-only button with a large badge this is more present since the badge may cover 10% of the button area.

Then it sometimes happens the user tries to tap the button and hits the badge instead with the finger and wonders why the button is not clicked. 

![253756992-ea084dd2-f855-42b3-9268-29063fc88a75](https://github.com/primefaces/primefaces/assets/5265550/452157f5-2cee-4ff1-8d20-723fe8c7b13f)

This can be seen on showcase.

### Describe the solution you would like

Somehow the click event of badge should be delegated to its underlying button. Could this be done automatic or do we need a onclick client attribute instead and handle it ourselves?

This would also increase the clickable area of the button making a button with badge even more user friendly to click.

**Comment by melloware** [comment]
Hmmm this is a good idea but I can see some people wanting to delegate the click and others who want it to possibly do something different on its click.  

Maybe it should delegate the click but if an onClick is on the badge do not delegate and just do the onClick.

**Comment by djmj** [comment]
That would be even better,
