### ISSUE TITLE
Spinner: Gets the min value when the prefix is defined

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#10922]
### Describe the bug

1. Set the value, min, max and the prefix
2. Click the up or down button
3. Input takes the min value

Without prefix there is no problem. I did not provide any test code since it can be seen from the showcase after changing the code as below.

### Reproducer

```xhtml
<p:spinner id="prefix" value="15" prefix="$" min="10" max="50"/>
<p:spinner id="prefix" value="15.20" prefix="$" min="10" max="50" stepFactor="0.1" decimalPlaces="2"/>
```

### Expected behavior

up/down: 15 to 16/14 (not 15 to 10)
up/down: 15.20 to 15.30/15.10 (not 15.20 to 10.00)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

17

### Browser(s)

Safari 17.0, Firefox 119.0

**Comment by melloware** [comment]
Confirmed and submitted PR.
