### ISSUE TITLE
Active menuitem issue on MegaMenu

### ISSUE THREAD

**Issue by chuckumi** [primefaces/primefaces#1093]
Hi,
I am using PrimeFaces 5.3 (from maven) and I've realized that **ui-state-active** in megamenu is not working. ui-state-active always stay on first menu item.

Here is a code snippet:
`<h:form>
<p:megaMenu orientation="horizontal" activeIndex="#{menuTop.selectedPage}" styleClass="menu_top" id="menu_top">
                        <p:menuitem value="overview" outcome="/admin/index" icon="fa fa-th" iconPos="top">
                            <f:param name="selectedPage" value="overview" />
                        </p:menuitem>        
                        <p:menuitem value="contacts" outcome="/admin/contacts" icon="fa fa-send" iconPos="top">
                            <f:param name="selectedPage" value="contacts" />
                        </p:menuitem> 
<p:megaMenu>
</h:form>`

Thx for advice

**Comment by cagataycivici** [comment]
I've seen the issue.

**Comment by chuckumi** [comment]
Do you know how to solve it? I can do it by javascript, but i think this is primefaces bug

**Comment by cagataycivici** [comment]
@mertsincan , Please look into this.

**Comment by mertsincan** [comment]
Remove ui-state-active. We add ui-state-hover class for active menuitem.

**Comment by chuckumi** [comment]
Hmm, but this ui-state-hover class is not there. Which version do you use?

**Comment by tonybanks** [comment]
ahhhhhhhhhhhhhhh....................it seems this has no solution
