### ISSUE TITLE
Locales: Locales are always rendered but core.js not, which leads to a JS exception

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10930]
our locales looks like:
```
/** German */
PrimeFaces.locales["de"] = {

}
```

but needs to be:

our locales looks like:
```
if (window.PrimeFaces) {
   /** German */
   PrimeFaces.locales["de"] = {
   
   }
}
```

**Comment by tandraschko** [comment]
in theory it would be easy to check of core.js is included in the current view and then skip rendering the JS include BUT i think omnifaces manipulates this heavily, so better include the small IF in each locales

**Comment by melloware** [comment]
I will add it. No problem.

**Comment by tandraschko** [comment]
already there

also removed unused ResourceInfo, we had it because of pre JSF 2.3 support
