### ISSUE TITLE
ToggleSwitch: After validation fails it toggles its value in the view

### ISSUE THREAD

**Issue by BryanV91** [primefaces/primefaces#10932]
### Describe the bug

When you click in the `ToggleSwitch ` and validation fails, the value changes in the view. The value remains the same in the backend, however this is showing inconsistent values. 

It is also happening for `SelectBooleanCheckbox ` and it might be happening to other components as well.

### Reproducer

1. Go to `test.xhtml`
2. Click on the `ToggleSwitch `
3. See validation error message and how it toggles the value

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13220556/primefaces-test-master.zip)

### Expected behavior

Value should remain the same after validation fails.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

### Browser(s)

Chrome

**Comment by melloware** [comment]
As answered on Discord I believe this is working as intended.

**Comment by BryanV91** [comment]
If this is the expected behavior, I was thinking on implementing a local solution:


```
-- Using oncomplete(xhr, status, args)

if(args.validationFailed){
    // return toggleSwitch to previous status
}
```

However, since I have the AJAX call in the toggle component, I have to click once to go to the previous value and then click again to send a new request (this doesn't feel user friendly).

**Comment by BryanV91** [comment]
Thanks to @melloware and @FlipWarthog for the solution:

```
<p:toggleSwitch id="toggle" widgetVar="toggleSelect" value="#{testView.myValue}">
    <p:ajax listener="#{testView.myFunction()}" process="@this text" update="@form"
        oncomplete="if (args.validationFailed) PF('toggleSelect').uncheck(true)" />
</p:toggleSwitch>
```
