### ISSUE TITLE
DatePicker: Wrong init of viewDate

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#10945]
### Describe the bug

When we use datepicker (with time to see it more clearly) without initial date set in server we can notice that view date is changing between first and second showing of overlay when no date is selected from datePicker.
1. I run mu reproducer and without touching anything I run this js line from developer tools:
![image](https://github.com/primefaces/primefaces/assets/21099773/6e5dc63d-3c9c-4167-858a-4b41d760441f)
2. Now I click in time input and this is what I see in overlay

![image](https://github.com/primefaces/primefaces/assets/21099773/34487de2-0b79-4808-8c40-9c4f6dc8ff5d)
3. Now I hide it without selecting any date and run js code:
![image](https://github.com/primefaces/primefaces/assets/21099773/ed50f905-c8f9-43b1-bc48-3c6455e2b3ac)

4. I once again click in time input and now I see different time:
![image](https://github.com/primefaces/primefaces/assets/21099773/427cbbbf-4548-401d-a201-46c0aea98e48)

This is because I have a min date that is set as:

![image](https://github.com/primefaces/primefaces/assets/21099773/dfba4ccb-7d9a-4321-ad6d-eefe7d43b47b)

but the same goes if I had max date.

and I see an error in __setInitValues_ function. Those lines:
![image](https://github.com/primefaces/primefaces/assets/21099773/8892c6b5-fe71-4a0f-bace-f00ce9a11025)

should be called after those:

![image](https://github.com/primefaces/primefaces/assets/21099773/d25a539e-a4d9-4656-b880-b9358246c39c)

because when you hide overlay you call this:
![image](https://github.com/primefaces/primefaces/assets/21099773/2d3211de-3d23-4ed9-8630-a64f475ea106)

You can't change viewDate after You set options.viewDate that You reset to in OnExited

My reproducer:
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13263957/primefaces-test-master.zip)

### Expected behavior

The one I described in description. Date should statu the same between first and second show of datepicker's overlay

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by melloware** [comment]
I submitted a PR if you want to review.

**Comment by melloware** [comment]
I switched it to you and will include this in 13.0.3

**Comment by majkers** [comment]
When are you planning to release 13.0.3 version?
