### ISSUE TITLE
PrimeFX with PrimeOne for JavaFX FXML

### ISSUE THREAD

**Issue by rrangelo** [primefaces/primefaces#10944]
### Description

Hi! Have you ever think create PrimeFX with PrimeOne for a JavaFX FXML?

### Describe the solution you would like

Make a port of PrimeFaces for JavaFX FXML enabling PrimeOne.

**Comment by tandraschko** [comment]
No plans actually

Maybe better use GitHub discussions, its not a PrimeFaces issue

**Comment by rrangelo** [comment]
Thank you! I created the discussion [PrimeFX with PrimeOne for JavaFX FXML](https://github.com/orgs/primefaces/discussions/388) in PrimeFaces
