### ISSUE TITLE
Layout/spacing fall all elements much more spacing.

### ISSUE THREAD

**Issue by jrgamber** [primefaces/primefaces#10942]
### Describe the bug

In pf 12 our pages look same as they did for many releases.
In pf 13 there is a lot of space between elements and the UI is much more spread out.

![v12 layout](https://github.com/primefaces/primefaces/assets/15164224/cfdda1a4-2c01-4811-a751-9b41229f7c9f)
![page v13](https://github.com/primefaces/primefaces/assets/15164224/da824c79-8622-473a-b834-139812d5c91b) 

[JPFormProfile.txt](https://github.com/primefaces/primefaces/files/13258747/JPFormProfile.txt)

### Expected behavior

excepted v13 to look same as v12

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

same on all browsers

**Comment by melloware** [comment]
@jrgamber are they PanelGrid's by any chance?  If so check out the Migration Guide: https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0?id=panelgrid

**Comment by jrgamber** [comment]
That fixed it... adding  

layout="tabular"

not sure why v13 didn't leave the default the way the prior version and all the tons of existing panel grids were created.

and h:panelgrid seems to also have the prior tabular layout, so now v13 is different from that.

**Comment by melloware** [comment]
As mentioned in the ticket using Table, TR, and TD is HTML4 way of formatting.  The HTML5 way is to use Divs with responsive CSS that is why "tabular" is no longer the default.
