### ISSUE TITLE
CSP: add noonce only to JSF forms

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#10946]
Nonce input is added to all forms, in some cases this may not be desirable. How about adding an attribute like ignore-primefaces-none to a form as attribute, if that exists the nonce is not attached dynamically.

**Comment by tandraschko** [comment]
Arent they just added to jsf forms anyway?

**Comment by tandraschko** [comment]
We currently it append it to every form

i think we should just append it to JSF forms, which is required if you activated CSP in PF

so we should just check for the viewstate hidden input here https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js#L37
and we are fine

**Comment by melloware** [comment]
@cagataycivici let me know if you need this backported to 13 if this was a PRO request?

**Comment by mertsincan** [comment]
@melloware There is currently a request for this from a user. Can you port this to PF13.x? Thanks a lot ;)

**Comment by melloware** [comment]
Sure thing @mertsincan i will put it in 13.0.8

**Comment by martin654** [comment]
Hi, I am testing PF 13.0.8 with Jakarta qualifier and I run into a issue with this. The added condition checks Primefaces.VIEW_STATE constant: VIEW_STATE : "javax.faces.ViewState" but in our case the hidden input is named "jakarta.faces.ViewState"...

**Comment by melloware** [comment]
OK let me check.  Our Shade JAR should replace javax. in all JSF files

**Comment by martin654** [comment]
Could you please check that new JS code is evaulated correctly in some app with PF 13.0.8? It fails to find element which would pass added condition (if (child instanceof HTMLInputElement && child.name && child.name.includes(PrimeFaces.VIEW_STATE)) in our production app, but I clearly see such element in DOM.

![obrazek](https://github.com/primefaces/primefaces/assets/22746146/ed7cae19-80ba-4823-8136-6b2aedf0b983)

**Comment by melloware** [comment]
When I run this in my browser running my app

```
var forms = document.getElementsByTagName("form");
for (var i = 0; i < forms.length; i++) {
    var form = forms[i];
    for (let child of form.children) {
        if (child instanceof HTMLInputElement && child.name && child.name.includes(PrimeFaces.VIEW_STATE)) {
            console.warn('Found Form!', form.getAttribute('id'));
        }
    }
}
```

it prints out

![image](https://github.com/primefaces/primefaces/assets/4399574/67110d05-c644-4ccd-845f-33d1aa5cfad4)

Can you try it?

**Comment by martin654** [comment]
Hi, 
in browser I see this JS code from core.js:
```
PrimeFaces.csp || (PrimeFaces.csp = {
    NONCE_INPUT: "primefaces.nonce",
    NONCE_VALUE: "",
    EVENT_REGISTRY: new Map,
    init: function(a) {
        PrimeFaces.csp.NONCE_VALUE = a;
        for (var c = document.getElementsByTagName("form"), b = 0; b < c.length; b++) {
            var d = c[b];
            if (PrimeFaces.csp.isFacesForm(d)) {
                var e = d.elements[PrimeFaces.csp.NONCE_INPUT];
                e || (e = document.createElement("input"),
                e.setAttribute("name", PrimeFaces.csp.NONCE_INPUT),
                e.setAttribute("type", "hidden"),
                d.appendChild(e));
                e.setAttribute("value", a)
            }
        }
    },
    isFacesForm: function(a) {
        if ("post" === a.method)
            for (child in a.children)
                if (child instanceof HTMLInputElement && child.name && child.name.includes(PrimeFaces.VIEW_STATE))
                    return !0;
        return !1
    },
```

Yesterday I tried to execute this code from console:
```
for (var c = document.getElementsByTagName("form"), b = 0; b < c.length; b++) {
            var form = c[b];

           if ("post" === form.method) {
            for (child in form.children){
                if (child instanceof HTMLInputElement && child.name && child.name.includes(PrimeFaces.VIEW_STATE)) {
                    console.info('Found', form.getAttribute('id'));
                }
            }
           }
        }
```

which prints "undefined".

Today I tried your snippet
```
var forms = document.getElementsByTagName("form");
for (var i = 0; i < forms.length; i++) {
    var form = forms[i];
    for (let child of form.children) {
        if (child instanceof HTMLInputElement && child.name && child.name.includes(PrimeFaces.VIEW_STATE)) {
            console.warn('Found Form!', form.getAttribute('id'));
        }
    }
}
```
and it works and prints all forms in page.

The difference that makes it work in my case is changing the for 
from:
for (child in form.children){
to
for (let child of form.children) {

**Comment by melloware** [comment]
I think I know what is going on.  Let me look.

**Comment by melloware** [comment]
OK the code in 13.0.8 is missing the `let`.   For now you should just be able to add this MonkeyPatch to your code to fix it.

```js
PrimeFaces.csp.isFacesForm = function(form) {
    if (form.method === 'post') {
        for (let child of form.children) {
            if (child instanceof HTMLInputElement && child.name && child.name.includes(PrimeFaces.VIEW_STATE)) {
                return true;
            }
        }
    }
    return false;
};
```

**Comment by martin654** [comment]
Thank you for the fix!

**Comment by martin654** [comment]
Works great in PF 13.0.9. Thanks

**Comment by melloware** [comment]
Thanks for reporting back!
