### ISSUE TITLE
p:autoComplete does not pass custom attributes to completeMethod

### ISSUE THREAD

**Issue by jmasinter** [primefaces/primefaces#10955]
### Describe the bug

In previous versions the p:autocomplete would pass parameters specified by <f:attribute> to the completeMethod to allow additional customization of the completion function.  However in the latest version (not sure when this happened) the attributes are not populated on the component.

e.g. https://stackoverflow.com/questions/6567002/fparam-or-fattribute-support-on-primefaces-autocomplete

```xml
<p:autoComplete
    completeMethod="#{bean.completeMethod}">
    <f:attribute name="additionalParam1" value="testparam" />
</p:autoComplete>
```

```java
public List<String> completeMethod(String partial) {
    String additionalParam1 = (String) UIComponent.getCurrentComponent(FacesContext.getCurrentInstance()).getAttributes().get("additionalParam1");
    ...
}
```

### Expected behavior

<f:attribute> values should be available to the completeMethod server side function

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3.14.SP04

### Java version

11

**Comment by melloware** [comment]
I just tested it using the showcase and it works fine.

```xml
<p:autoComplete id="acSimple" value="#{autoCompleteView.txt1}"
                                        completeMethod="#{autoCompleteView.completeText}" scrollHeight="250">
          <f:attribute name="filter" value="Test" />
</p:autoComplete>
```

```java
    public List<String> completeText(String query) {
        String filterValue = (String) UIComponent.getCurrentComponent(FacesContext.getCurrentInstance()).getAttributes().get("filter");
        System.out.println(filterValue);
        String queryLowerCase = query.toLowerCase();
        List<String> countryList = new ArrayList<>();
        List<Country> countries = countryService.getCountries();
        for (Country country : countries) {
            countryList.add(country.getName());
        }

        return countryList.stream().filter(t -> t.toLowerCase().startsWith(queryLowerCase)).collect(Collectors.toList());
    }
```

Prints out:

```
Test
```
on the command line.

**Comment by melloware** [comment]
Tested in Mojarra 2.3.21

**Comment by jmasinter** [comment]
And now it is magically working for me as well :)    Not sure what was up!  thank you
