### ISSUE TITLE
FileUpload: custom validation messages formatted incorrectly

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#10950]
### Describe the bug

FacesMessage is formatted incorrectly when the `invalidFileMessage` attribute on `p:fileUpload` is used, a colon gets appended to the end of the message:
![Screenshot_20231106_152001](https://github.com/primefaces/primefaces/assets/54570207/99cdb6a5-bd47-4525-9c51-3c5a7cda0c27)

### Reproducer

[fileupload-invalidFileMessage.zip](https://github.com/primefaces/primefaces/files/13267741/fileupload-invalidFileMessage.zip)

or basically:
```xhtml
        <p:messages id="msgs"/>

        <p:fileUpload label="Upload XML here" listener="#{testView.handleFileUpload}"
                      accept="text/xml" validateContentType="true" invalidFileMessage="Invalid file uploaded!"
                      process="@this" update="msgs"/>
```

### Expected behavior

There is no colon appended at the end of the message

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-SNAPSHOT

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
I think because its a ValidatorMessage associated to the component.

```java
throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_ERROR, fileUpload.getInvalidFileMessage(), ""));
```

**Comment by jungm** [comment]
From what I can tell the colon gets added somewhere between creating the ValidatorException and invoking #getMessage() on it later on

it looks like this is caused in myfaces somewhere, running my reproducer with mojarra works as expected

**Comment by jungm** [comment]
[This](https://github.com/apache/myfaces/blob/2.3.x/api/src/main/java/javax/faces/validator/ValidatorException.java#L109) is the root cause, MF builds a string that looks like `$summary: $detail` [while mojarra just keeps the summary](https://github.com/eclipse-ee4j/mojarra/blob/2.3/impl/src/main/java/javax/faces/validator/ValidatorException.java#L43)

**Comment by jungm** [comment]
Have to reopen this: Passing `null` as the detail does not seem to be a suitable workaround for this as `FacesMessage#getDetail()` now [returns the summary](https://github.com/apache/myfaces/blob/2.3.x/api/src/main/java/javax/faces/application/FacesMessage.java#L220)

I think the easiest way to solve this is to just check if the exception thrown was a `ValidatorException` and then adding the message returned by `ValidatorException#getFacesMessage()` instead of creating a new one:
```java
                context.addMessage(getClientId(), e instanceof ValidatorException
                        ? ((ValidatorException) e).getFacesMessage()
                        : new FacesMessage(FacesMessage.SEVERITY_ERROR, e.getMessage(), null));
```

**Comment by melloware** [comment]
Should we update MyFaces to align with mojarra?

**Comment by jungm** [comment]
Absolutely, at least how the `FacesMessage` is turned into a string in `ValidatorException`

Returning the detail string when there's no summary is 100% fine as it's according to JSF spec: https://jakarta.ee/specifications/faces/2.3/apidocs/javax/faces/application/facesmessage#getDetail--

**Comment by tandraschko** [comment]
@jungm can you please create a MF issue, to enhance ValidatorException, to ignore a empty-string detail when building the msg?

**Comment by jungm** [comment]
Related MF issue: https://issues.apache.org/jira/browse/MYFACES-4646
