### ISSUE TITLE
Modify SelectCheckBoxMenu to Allow an Unlimited Number of Items

### ISSUE THREAD

**Issue by Dario-EDP** [primefaces/primefaces#10966]
### Description

Currently, the SelectCheckBoxMenu component does not impose a limit on the maximum number of selectable items. However, such a limitation could be beneficial for improving usability and the user experience.

### Describe the solution you would like

The goal of this issue is to discuss and ultimately implement a limitation on the maximum number of selectable items in the SelectCheckBoxMenu component. This would help to address performance and usability issues when working with large data sets.

**Comment by melloware** [comment]
Not sure about this one.  If you have that many items them the SelectCheckBoxMenu is not the correct UI component if you need to limit them.

**Comment by tandraschko** [comment]
yeah
and you can limit the selectItems by yourself anyway

**Comment by jepsar** [comment]
If you are working with large datasets consider using AutoComplete instead.

**Comment by Kirito078** [comment]
Okey thanks all
