### ISSUE TITLE
Datatable: header filters do not render custom components

### ISSUE THREAD

**Issue by ehelfrichaffirmx** [primefaces/primefaces#10967]
### Description

I am using Primefaces 13.01 and I am attempting to put a slider to do range filtering on a column in a datatable similar to the way that the datepicker component can be used to filter a date range. The output text renders but the slider does not.  I can see the controller filter function being called on page load  but the slider isn't rendered. Here is the the code snippet:

```xml
<p:column field="activityRating" headerText="Activity Rating" filterMatchMode="between"  filterFunction="#{controller.filterByRating}">
    <f:facet name="filter">
        <h:outputText id="displayRange" value="Between #{controller.filterMin} and #{controller.filterMax}" />
        <p:slider for="min,max" display="displayRange" minValue="1f" maxValue="5f" step=".1" style="width: 100px" range="true" displayTemplate="Between {min} and {max}" converter="javax.faces.Float" />
        <h:inputHidden id="min" value="#{controller.filterMin}" />
        <h:inputHidden id="max" value="#{controller.filterMax}" />
    </f:facet>
</p:column>
```

### Describe the solution you would like

Unless I am doing something wrong, and that is entirely possible, I think being able to use custom components like datepicker to filter would be a good enhancement

**Comment by tandraschko** [comment]
can you please provide a primefaces-test reproducer?

**Comment by Rapster** [comment]
`UIColumn#getFilterComponent` returns the first valueholder. It has been done this way for #7469, maybe this should be done only for dynamic columns...

**Comment by tandraschko** [comment]
should it maybe just check for EditableValueHolder?
