### ISSUE TITLE
Dashboard: Responsive - Once a widget is deleted, the remaining widgets cannot be aligned

### ISSUE THREAD

**Issue by RegiK123** [primefaces/primefaces#10965]
### Describe the bug

Once a widget is deleted, the remaining widgets cannot be aligned.

### Reproducer

Steps:
1. Opne the demo: https://www.primefaces.org/showcase/ui/panel/dashboard.xhtml?jfwid=48472
2. Remove Stacked widget
3. Try to move the Donut widget next to the Bar widget 
4. Remove Cartesian widget
5. Try aligning the Donut widget with the Bar widget.

https://github.com/primefaces/primefaces/assets/26834946/45b420d0-405b-4c41-9fff-9e2cd3d8b1eb

### Expected behavior

Once a widget is deleted, the remaining widgets should be aligned

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### Theme

all

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

Chrome

**Comment by melloware** [comment]
@RegiK123 that is "as designed" in that demo.  The code in the demo simply swaps two widgets places if you drop over an existing widget.  In your case you are dropping into "whitespace" so there is no dropzone.  But all of that can be deal with JavaScrript if you need that behavior as you can look at the widget drag and drop code.

So for resizing you can easily do that all the widgets just respect their responsive size so in your `reorder` method you can do whatever you want.

```xml
<p:ajax event="reorder" listener="#{dashboardView.handleReorder}" />
```

Simply in the reorder method set responsive sizes and resize your widgets however you want.
