### ISSUE TITLE
TabView: Add badge support to tabs

### ISSUE THREAD

**Issue by wbss1** [primefaces/primefaces#10973]
### Description

I would like to be able to use a badge on a specific tab of a tabView

### Describe the solution you would like

Same feature of menus

**Comment by melloware** [comment]
I just recently asked about this too. It works on TabMenu but was not implemented on TabView.  We will see what we can do.

**Comment by melloware** [comment]
@wbss1 you can actually do this right now with a `facet`

```xml
<p:tab>
                        <f:facet name="actions">
                            Options II
                        </f:facet>
                        <f:facet name="title">
                            <span>Header II</span> <p:badge value="3" severity="danger" class="ml-1"></p:badge>
                        </f:facet>
                        <p class="m-0">
                            Stuff
                        </p>
                    </p:tab>
```

Looks like...

![image](https://github.com/primefaces/primefaces/assets/4399574/5af9d474-2545-4435-a0ac-38974c6f6e0b)
