### ISSUE TITLE
TextEditor: Blur event called before input value is applyed

### ISSUE THREAD

**Issue by hfluz** [primefaces/primefaces#10976]
### Describe the bug

I have a TextEditor in my form. The field is required, however, even if the input is filled, after losing the focus, the blur event triggers the Value is required validation error. Debugging it, it seems the validator/listener always get the previous instead of the current value of the input.

Reproducer: 
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/13334154/primefaces-test.zip)

Short video:
[Screencast from 2023-11-10 10-18-49.webm](https://github.com/primefaces/primefaces/assets/832674/1207db11-7ba9-4269-87ac-2d7576e82a2f)

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/13334154/primefaces-test.zip)

### Expected behavior

Value is required should only be triggered if the input is null/empty.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

11.0.20

**Comment by melloware** [comment]
If I change `blur` to `change` your example works fine.
[pf-10976.zip](https://github.com/primefaces/primefaces/files/13335058/pf-10976.zip)

**Comment by hfluz** [comment]
I don't know why TextEditor was using blur event, but it was a legacy code that was working since PF8, I think. Your suggestion did work, thanks.

**Comment by melloware** [comment]
Excellent!  Yeah a lot has changed between PF and even QuillJs itself.
