### ISSUE TITLE
OutputPanel: blockUI shouldn't be triggered

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#10970]
### Describe the bug

We're migrating our projects from PF 12 to 13, but I think I discovered a bug when in the same page there are a deferred outputPanel and a blockUI. Basically, when the page loads, the blockUI gets triggered (even if it shouldn't) and it never hides, even when the loading is complete.

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/13320466/primefaces-test.zip)
mvn jetty:run the navigate to localhost:8080/primefaces-test

### Expected behavior

the blockUI shouldn't be triggered

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

openjdk version "11.0.17" 2022-10-18

**Comment by NicolaIsotta** [comment]
Funny thing: if the button is removed, the blockui hides when the deferred loading completes.
Moving the blockUI element at the end of the body, instead, prevents the triggering of blockUI at all

**Comment by melloware** [comment]
Can you try this one:
[pf-10970.zip](https://github.com/primefaces/primefaces/files/13320772/pf-10970.zip)

Does it work as you expect?

**Comment by NicolaIsotta** [comment]
Yeah, moving the blockUI after the outputPanel seems to fix the issue.
I tried to debug the JS but I still haven't figured out the reason.

**Comment by melloware** [comment]
@NicolaIsotta let me know if you are going to investigate this?

**Comment by NicolaIsotta** [comment]
No luck so far, I'll try again next week

**Comment by melloware** [comment]
@NicolaIsotta its because of this code in BlockUI:

```js
//listen global ajax send and complete callbacks
        $(document).on('pfAjaxSend.' + this.id, function(e, xhr, settings) {
            if (!$this.cfg.blocked && $this.isXhrSourceATrigger(settings)) {
                $this.show();
            }
```

When the page loads an AJAX event is immediately fired by your Panel and since the BlockUI exists its triggered.

**Comment by NicolaIsotta** [comment]
Yep, tested the fix and it works.
