### ISSUE TITLE
Allow customization of CommandButton loading icon

### ISSUE THREAD

**Issue by commodis** [primefaces/primefaces#10975]
### Description

PrimeFaces added a loading icon to the command button.
This is a super neat feature - thanks for that!

Currently, it is hard-coded to the `primeicons` `pi-spinner`.

https://github.com/primefaces/primefaces/blob/2ecac876adb8b21fe2cbbf2402c2de33b8a47a6a/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandbutton.js#L56C21-L56C30

### Describe the solution you would like

I would not mind this as the default, but I would like to overwrite it with other animations and/or icons.

**Comment by melloware** [comment]
I think it's just CSS you can override `ui-state-loading` and make it any icon you want.

**Comment by melloware** [comment]
Documented right here: https://primefaces.github.io/primefaces/13_0_0/#/components/commandbutton?id=ajax-loading-indicator-icon

**Comment by commodis** [comment]
The documentation just states how to suppress the default styling. Not sure if it is easy to rewrite the CSS for a new animation.

**Comment by jepsar** [comment]
There is an example in the showcase https://www.primefaces.org/showcase/ui/button/commandButton.xhtml

See "Ajax Disabling and Status Icon > Custom"
