### ISSUE TITLE
DataTable: improve handling with null rowKey

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10981]
probably just a "follow-up" bug but we can improve it and avoid weird behaviors

**Comment by Rapster** [comment]
Is there a good reason to be able to set a null rowkey? If you enable a feature requiring a rowkey, and it's null and you simply bypass it then you'll end up with weird behavior. I prefer to fail fast in such scenario (instead of digging for the reason as for why it's not working...)

**Comment by tandraschko** [comment]
Nope there isnt but the bug follow up bug is not understandable as "null" string is rendered on _selection hidden input and fails with a weird exception on postback while process the DT

**Comment by Rapster** [comment]
Ok so sounds like a "“Fix the cause, not the symptom.”" kinda thing then... I would simply throw an exception if rowKey is resolve to null
