### ISSUE TITLE
StaticMessage: Add closable attribute

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#10988]
### Description

I have a static message taking up screen estate. When a user has read it, there is now no way to dismiss it.

### Describe the solution you would like

Add `closable` attribute (and `onClose` event) to close (hide) the message.

**Comment by tandraschko** [comment]
what should haben when you close and its updated via AJAX? maybe you need to sync it and skip rendering

**Comment by jepsar** [comment]
> what should haben when you close and its updated via AJAX? maybe you need to sync it and skip rendering

I was thinking to leave that up to the user using the rendered attribute.

**Comment by tandraschko** [comment]
then we should at least allow a close behavior
