### ISSUE TITLE
Simple FileUpload: add property to hide filename (especially for basic & auto mode)

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#10992]
https://www.primefaces.org/showcase/ui/file/upload/basicAuto.xhtml?jfwid=3b1c7

in this case the file is automatically uploaded after selecting the file. in normal cases, the uploaded file name is displayed right after the button but only for a very short time.

IMO we can completely skip rendering the uploaded file name in basic+auto mode. Or should we make it configurable?

CC @melloware

**Comment by Rapster** [comment]
what about big files? in additon to have an ajax status like we have for some component (e.g autocomplete), I think it'll look quite nice

**Comment by tandraschko** [comment]
Big files are indeed a problem
Therefore i thought about making it configurable. Maybe even with a threshold.
Something like
showFilename=true,false,auto
And auto only shows it when the file is bigger then 1mb?
Not sure


And good idea with the Ajax Status, will create a seperate ticket

**Comment by Rapster** [comment]
Not sure... I don't think it worth to put effort in this. Though having ajax loader is worth it, it's basically same as https://github.com/primefaces/primefaces/issues/10258

**Comment by tandraschko** [comment]
what about the name?
its actually .ui-fileupload-filename but it also displays validation messages and so and its only rendered in simple mode.
display|displayFeedback|feedback = true|false ?

IMO some day we should splitup simple and advanced fileupload in 2 seperate tags. Some options are for single only, some are for advanced only.

**Comment by melloware** [comment]
Agreed and I like `displayFeedback`
