### ISSUE TITLE
SelectOneMenu: dynamic=true add LoadingIndicator during first adding elements to DOM

### ISSUE THREAD

**Issue by AlessandroBori** [primefaces/primefaces#10998]
### Description

Hi all,
it'll be nice having, like commandbutton,  a LoadingIndicator rotating after the first click on a SelectOneMenu with dynamic=true, just for notify a "load in progress" status tu the final user.

### Describe the solution you would like

A LoadingIndicator  in the text field will be perfect

top tier: show an empty panel of the selectOneMenu with a bigger LoadingIndicator  inside and then (after loading) hiding it and showing the list

God Tier: both

**Comment by melloware** [comment]
The AutoComplete `lazy` example already does this.  Don't you want an AutoComplete and not a SelectOne?

**Comment by tandraschko** [comment]
would be still a nice feature for selectOneMenu

**Comment by melloware** [comment]
OK PR submitted and tested in regular and RTL mode.
