### ISSUE TITLE
Simple FileUpload: refactor client side validation

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11001]
Currently Simple-FileUpload displays some basic validation errors inside the span '.ui-fileupload-filename', which is quite weird.
We should check if we can implement it this with real PrimeFaces CSV to also enabled usage of p:message(s) and p:growl

**Comment by tandraschko** [comment]
im currently unhappy how validation is implemented on both client and server side.
normally validation is done via validator tags, currently its not used on both sides.

Currently i could fake the ClientValidator and render the validation metadata in the FileUploadRenderer, if CSV enabled.
On client side, i can skip the "internal fileupload" validation if CSV enabled. This would be a breaking change as validation is now just skipped on client side if the form hasnt a enabled CSV.
For me its ok, we just need to add it to the migration guide.

The question is however, should we completely remove the internal validation and say: if you would like to validate on client side, please use CSV.
Overall my change will currently only touch Simple mode. 

i wont touch server side validation for now.
Later we would propably need to introduce a `p:validateFile allowTypes, sizeLimit and fileLimit` and remove this attr frome fileupload + server side validation in side FileUpload component itself. Then we could also remove the small fake-ClientValidator from FileUploadRenderer again.

**Comment by melloware** [comment]
@tandraschko I see what you mean.  This component grew over time and we added more and more features but its a little disjointed now.

**Comment by tandraschko** [comment]
Yeah... i believe we should do the following:
1) migrate to CSV for SimpleFileUpload
    - render CSV metadata with a fake-ClientValidator (allowTypes,sizeLimit and fileLimit)
    - implement a new ClientValidator js to validate
    - remove internal validation of SimpleFileUpload
    - add migration guide
2) new ticket: evaluate a p:validateFile tag and move FileUpload#validateValue to it
3) remove `allowTypes,sizeLimit,fileLimit` attributes on FileUpload and extract them for AdvancadedFileUpload and passtrough JS

later we can decide if we would like to touch AdvancadedFileUpload

**Comment by tandraschko** [comment]
PR provided, just tests need to adjusted. i will do this when all is fine.
