### ISSUE TITLE
fileDownload: Cannot download file names containing single quotes  when ajax=true

### ISSUE THREAD

**Issue by enunu** [primefaces/primefaces#11005]
### Describe the bug

Cannot download file names containing single quotes when ajax=true
Single quotation marks are not escaped when downloading files

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13440809/primefaces-test-master.zip)

1. Click on 'Ajax Download Button'
2. See error log in the browser's developer tools 

### Expected behavior

File names containing single quotes should also be downloadable

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Interesting I assume the file name must need to be escaped somehow.

**Comment by melloware** [comment]
Thanks for the report. Will be fixed for 13.0.4
