### ISSUE TITLE
DataScroller: with lazyloading only load one time

### ISSUE THREAD

**Issue by Samuel-StO** [primefaces/primefaces#11019]
### Describe the bug

When I try to use a dataScroller with lazy loading, the data load only once.  

### Reproducer

I've made a reproducer : https://github.com/Samuel-StO/primefaces-datascroller-issue

In the reproducer, I have a list of 100 cities that I'm trying to display in a lazy loading datascroller. 
I've set the number of elements per chunk to 25. 

The behavior I'm observing is that at first there are 25 elements, then if I scroll it loads the next 25. But if you keep scrolling, it won't load the next 25. 
In fact, it isn't capable of loading more data than once, even if there's more data to load. 

The video shows problematic behavior :
https://github.com/primefaces/primefaces/assets/86346301/c9a18e2c-85b3-4355-80a5-d9b90c44c515

### Expected behavior

The desired behavior is for the datascroller to continue loading data when you scroll.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by Samuel-StO** [comment]
I investigated further, and when I looked with the debugger, it appeared that the datascroller's totalSize is always set to 0 with lazyloading. 

In the Load function, we have this condition which lets us know if everything is loaded: 
`a.cfg.offset + a.cfg.chunkSize >= a.cfg.totalSize`

Because totalSize is always set to 0, the allLoaded flag is set to true and then no more data can be loaded.

**Comment by melloware** [comment]
@Samuel-StO interested in debugging and submitting a PR?

**Comment by melloware** [comment]
I think your issue is similar to this one: https://github.com/primefaces/primefaces/issues/6087

**Comment by Samuel-StO** [comment]
Yes I can try to debug and submit a PR. There is a Starter Guide to contribute ?

**Comment by Samuel-StO** [comment]
I made a PR to solve the problem. I don't know Primefaces well enough to be sure of the side effect of the correction.
