### ISSUE TITLE
Spinner: Backspace not working anymore

### ISSUE THREAD

**Issue by danteCarvalho** [primefaces/primefaces#11029]
### Describe the bug

The backspace buttom used to work to delete the numbers on the spinner, but its does nothing now.
You can see it on the showcase https://www.primefaces.org/showcase/ui/input/spinner.xhtml

### Expected behavior

When the backspace is pressed the numbers on the spinner should be deleted.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### Theme

default

### JSF implementation

Mojarra

### JSF version

JavaServer(TM) Faces 2.2 API

### Java version

8

**Comment by melloware** [comment]
@danteCarvalho can you tell me what version backspace used to work?

**Comment by melloware** [comment]
Nevermind I see it.

**Comment by danteCarvalho** [comment]
Thanks for the fast fix =]
