### ISSUE TITLE
CSV: enable (command-)button only after client side validation passes

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#11036]
### Description

Modern JS clients often enable save - buttons only after all necessary information is provided by the user. We may provide similar functionality for PF-CSV.

### Describe the solution you would like

validation.common.js already contains validate-function which is currently called by clicking (command-)buttons with `validateClient="true"`.
We may provide a new attribute like `enabledByValidateClient="true"` which enables the buttons after CSV is passed successful.
We´ll need to find the right events to trigger this ongoing background-validation which enables / disables the (command-)button.
( Or a bit on the ugly side we´ll need to do the validation based on something like https://developer.mozilla.org/en-US/docs/Web/API/setInterval.)
What are your thoughts?

**Comment by tandraschko** [comment]
+1 in general

we may also refactor this slightly after this new feature: #11040

**Comment by tandraschko** [comment]
Basically the whole thing should be easy to implement
The user must attach p:clientValidator to each input and we have 99% of the whole mechanism: https://www.primefaces.org/showcase/ui/csv/event.xhtml

we only attach the validation state to the parent form ($form.data('p-validationfailed', true))
p:clientValidator can then also jquery events and p:commandButton can listen on it


the big question is: 
can we make it easier for the user, like attaching a p:clientValidator to the form isntead of each input?

**Comment by christophs78** [comment]
> we only need to attach the validation state to the parent form ($form.data('p-validationfailed', true))
> p:clientValidator can then also fire jquery events and the p:commandButton can listen on it

Think this is a bit more complicated. IMO we have to look at process-attribute of the button because not always the whole form is submittet.

And we may need some kind of initialization after initial page-load and partial ajax-updates. (Some good idea´s where/how we can add this?)

Just to get some feeling how large the "iceberg" before jumping into this adventure.
