### ISSUE TITLE
AJAX: args.redirect can be undefined when request will be cancelled during window unload

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11047]

**Comment by erickdeoliveiraleal** [comment]
@tandraschko can you tell me when this bug was introduced? and if it affects some version 10? We use primefaces-10.0.19. Is there any kind of test I can do?

**Comment by erickdeoliveiraleal** [comment]
because in [blog post](https://www.primefaces.org/primefaces-11-0-14-released/)  is written "new update to 10.0.x, 11.0.x and 12.0.x branches."

**Comment by tandraschko** [comment]
Sorry, i dont know this
