### ISSUE TITLE
DataTable: Ajax update on LiveScroll DataTable causes the current page to become the first page

### ISSUE THREAD

**Issue by Vikkear** [primefaces/primefaces#11045]
### Describe the bug

If I have a DataTable with lazy="true" and liveScroll="true" and I scroll down until the second page is loaded. 

Whenever an Ajax update is done on the table, then the first page disappears and my second page becomes the "first" page of the Table so when I scroll down, then the third page is loaded. Same logic applies if I have loaded the 5th page, then after an Ajax the 5th page becomes the first page of the table and so on.

### Reproducer

(https://github.com/Vikkear/primefaces-test-datatable-ajax-bug/tree/jpa-datatable-lazy-livescroll-ajax-bug)
1. Scroll down until second or third page is loaded
2. Press the button to start an Ajax update on the table
3. Now page 2 or 3 is the first loaded page in the DataTable

### Expected behavior

Whenever the Ajax update is done, then the first page should still be loaded in the datatable.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.3

### Theme

nova-light

### JSF implementation

MyFaces

### JSF version

5.1.2

### Java version

17.0.6

### Browser(s)

Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
@Rapster I think this issue is related to #10902

**Comment by Vikkear** [comment]
Hi! I noticed the 14.0.0 milestone on the issue and just had some questions since this issue is very important for the application that I'm working on:

- Is there any sort of ETA for when 14.0.0 is going to be released? 
- Is there any workaround that I can use while waiting for 14.0.0 to be released?

**Comment by melloware** [comment]
There is no ETA on 14.0.0 or this fix.  If you need immediate support I would look into PRO support:
https://github.com/primefaces/primefaces?tab=readme-ov-file#community--elite--pro

**Comment by Rapster** [comment]
I think I spotted the issue, but before doing anything I was wondering if @mertsincan @cagataycivici had any plan to align the scolling strategy of with any of the oher libs (they don't share the same properties, so I believe the scrolling strategy is different)  ?

**Comment by melloware** [comment]
I am not positive @Rapster but I doubt it because the PF Dom structure is very different than the other Prime libs.

**Comment by Rapster** [comment]
It's more about the scrolling algorithm itself rather than the table structure, by algorithm/strategy I mean, when a page should be loaded, how many should be loaded etc. Again, even if the tech behind it is different, I don't see any reason as of why the algorithm should be

**Comment by melloware** [comment]
I see.  Well if PrimeTek does I can't imagine it will be anytime soon?

**Comment by Rapster** [comment]
That's what I'm afraid of, I'm actually quite tempted to refactor a few things _(come to realize we starting to have more bugs about this feature lately...)_ but I'm not a master of this feature either, I left a few coments in the past on top of my head https://github.com/primefaces/primefaces/pull/9809

**Comment by melloware** [comment]
Yep lots of virtual scroll live scroll bugs. I don't see any reason why not to refactor if it gets rid of bugs and makes it easier to maintain!  Just my two cents.
