### ISSUE TITLE
DataTable: RowEditor used with reflow="true" is replicating column headers

### ISSUE THREAD

**Issue by lzzgabriel** [primefaces/primefaces#11078]
### Describe the bug

When using the RowEditor in the DataTable, as you click to edit and then cancel of a row when in mobile resolution (tested in chrome and opera), the header label of the other rows is replicated.

### Reproducer

Issue was found in personal project, using Jetty 11 Maven Plugin, Mojarra 4.0.1, Primefaces 13.0.3 and Java 17.
Tested with a clone of the [primefaces-test](https://github.com/primefaces/primefaces-test.git), running with no profiles, just a direct `mvn jetty:run`:

text.xhtml
    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

    <h:head>
	<title>PrimeFaces Test</title>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<h:outputScript name="test.js" />
	<h:outputStylesheet name="test.css" />
    </h:head>
    <h:body>

	<h1>#{testView.string}</h1>
	<h:form id="frmTest">

		<p:dataTable reflow="true" editable="true" value="#{testView.list}"
			var="obj">

			<p:column headerText="name">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{obj.name}"/>
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{obj.name}" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			<p:column headerText="artist">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{obj.artist}"/>
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{obj.artist}" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			<p:column headerText="released">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{obj.released}"/>
					</f:facet>
					<f:facet name="input">
						<p:inputNumber value="#{obj.released}" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			<p:column>
			<p:rowEditor></p:rowEditor>
			</p:column>

		</p:dataTable>

	</h:form>

    </h:body>
    </html>

Other files not changed

### Expected behavior

It was expected to not replicate the column header labels, but to enable edit and then restore the preexistent ones.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by melloware** [comment]
I am pretty sure Editable and Reflow were not designed to work together so this probably won't be fixed.

**Comment by melloware** [comment]
Working reproducer:
[pf-11078.zip](https://github.com/primefaces/primefaces/files/13588273/pf-11078.zip)

MonkeyPatch:
```js
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.initReflow = function() {
        var headerColumns = this.thead.find('> tr > th');

        for(var i = 0; i < headerColumns.length; i++) {
            var headerColumn = headerColumns.eq(i),
            reflowHeaderText = headerColumn.find('.ui-reflow-headertext:first').text(),
            colTitleEl = headerColumn.children('.ui-column-title'),
            title = (reflowHeaderText && reflowHeaderText.length) ? reflowHeaderText : colTitleEl.text();
            column = this.tbody.find('> tr:not(.ui-datatable-empty-message,.ui-datatable-summaryrow) > td:nth-child(' + (i + 1) + ')'),
            column.find(".ui-column-title").remove();
            column.prepend('<span class="ui-column-title">' + PrimeFaces.escapeHTML(title) + '</span>');
        }
    }
}
```
