### ISSUE TITLE
vertical carousel broke after rewrite in version 5.2.8 and 5.3

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#1107]
I believe vertical carousel broke after the rewrite: http://blog.primefaces.org/?p=3569

A vertical carousel is working as expected with version 5.2.7.

`<p:carousel id="availableCars" value="#{InboxDataTable.items}" vertical="true" headerText="Inbox" var="inbox" itemStyle="height:300px;width:300pxtext-align:center" numVisible="5" style="width:300px" >
   <h:panelGrid cellpadding="5" columns="1">
      <p:graphicImage cache="false" value="/image?id=#{inbox.id}" />
   </h:panelGrid>
</p:carousel>`

After upgrading to 5.3.6 vertical acts like a horizontal carousel.

See also: http://forum.primefaces.org/viewtopic.php?f=3&t=44377

**Comment by mertsincan** [comment]
Thanks for the sample. I will work on it and get back to you.

**Comment by tandraschko** [comment]
Works fine - added a example to the facelift showcase
