### ISSUE TITLE
Better spanish translation

### ISSUE THREAD

**Issue by JuanMiguelBG** [primefaces/primefaces#11071]
### Describe the bug

I attach the files of the Spanish version of both Java and Javascript with a better translation.
[primefaces-13.0.3-spanish_locale.zip](https://github.com/primefaces/primefaces/files/13557843/primefaces-13.0.3-spanish_locale.zip)

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

**Comment by jepsar** [comment]
Are you able to create a pull request?

**Comment by JuanMiguelBG** [comment]
Yes, to 13.x branch?

**Comment by melloware** [comment]
@JuanMiguelBG also check Master has much newer translations that the ones you attached
