### ISSUE TITLE
BlockUI + DataTable + ContextMenu: invalid triggering of BlockUI

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#11073]
### Describe the bug

Possibly related to #10970
Using a combination of DataTable, ContextMenu and BlockUI, when the ContextMenu is shown the UI gets blocked indefinitely

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/13560091/primefaces-test.zip)
mvn jetty:run
navigate to http://localhost:8080/primefaces-test
right click a table row

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-SNAPSHOT and 13.0.4-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

Eclipse Adoptium 11.0.14.1+1

### Browser(s)

all

**Comment by melloware** [comment]
Good catch it was a side effect of #10309 which I have now handled better

**Comment by NicolaIsotta** [comment]
Thanks for te quick fix!
