### ISSUE TITLE
SelectOneRadio: Issue #10319 breaks the predefined Grid CSS columns

### ISSUE THREAD

**Issue by JuanMiguelBG-Ticarum** [primefaces/primefaces#11082]
### Describe the bug

Before the resolution of the issue #10319.
To configure de responsive layout, the method `encodeResponsiveLayout()` of the class `SelectOneRadioRenderer`, calls to `GridLayoutUtils.getColumnClass(flex, columns)` to calculate the column style classes.

That method check if flex is activate. if Flex is disable, return the CSS Grid column style classes.

After the resolution of the issue #10319, the code always calls to `GridLayoutUtils.getFlexColumnClass(columns)`, that always return de Flex column style clases, although Flex is disabled, breaking the Grid CSS configuration.

### Reproducer

PrimeFaces Showcase loads PrimeFaces v13.0.0 and works as expected, returning Grid CSS column style classes with Flex disabled.

### Expected behavior

With responsive design configured on the SelectOneRadio component. If Flex is disabled, the columns should have the Grid CSS column classes defined.

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

**Comment by melloware** [comment]
Yes please created a separate PR for the 13.X branch that way I will include it in 13.0.4
