### ISSUE TITLE
DataTable rowToggler: how to Close expanded rows on some button click

### ISSUE THREAD

**Issue by vitsin** [primefaces/primefaces#11094]
### Describe the bug

hello,

highly appreciate any tips to get the following functionality:
Now, how can I have a button(w/o reloading entire page) CLOSING all expanded previously rows on same table ?

We have a datatable with rowToggler that works great on expanding table's rows.

regards,
--vs

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.7

### Theme

Sapphire

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

17

### Browser(s)

Firefox

**Comment by melloware** [comment]
```js
PF('yourTableWidget').collapseAllRows();
```

**Comment by vitsin** [comment]
Hmm, looks like I'm missing something, so far no luck.
Here I've simplified the code:

```
<h:form>
<p:commandButton id="tmRefresh" 
	action="#{some backend reloading lazy dataTable}" 
	value="Reload Table" 
	update=":viewForm:viewFormPanel"
	process=":viewForm:viewFormPanel"
	onclick="PF(':viewForm:viewFormPanel:viewTable').collapseAllRows();"/>
</h:form>
<div class="card">		
	<h:form id="viewForm">
		<h:panelGroup id="viewFormPanel" name="viewFormPanel">
		<p:dataTable id="viewTable"
			widgetVar="viewTable"
			lazy="true"
			... 
		>
		
			<p:column style="width:2%;">  
				<p:rowToggler/>
			</p:column>		
		
			some other columns here
		</p:dataTable>
	</h:form>
</div>	
```

appreciate the help
--vs

**Comment by melloware** [comment]
Switch `onclick` to `oncomplete` since you are using an AJAX button.

**Comment by vitsin** [comment]
With "oncomplete" the button is gred out w/o any text and has a spinning circle in it forever.
Is it still a valid project to re-create [test-project](https://github.com/primefaces/primefaces-test) ?

**Comment by melloware** [comment]
Sure but let me save you the trouble.

Go here: https://www.primefaces.org/showcase/ui/data/datatable/expansion.xhtml?jfwid=881ab

Expand some rows.

Press F12 to bring up the JS console and type:

```js
PrimeFaces.widgets.widget_j_idt286_j_idt287.collapseAllRows();
```

Press ENTER and watch the magic.  So your issue is with your code.

**Comment by vitsin** [comment]
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13621433/primefaces-test-master.zip)
Expected to work: "Collapse All" button close all expanded rows.
Actually: nothing collapsed.

This structure a bit more complicated than PF Showcase: p:dataTable->p:rowExpansion->p:dataTable
I've uploaded a simple ZIP file of entire project where it could be re-produced.

appreciate the help,
--vs

**Comment by melloware** [comment]
As I thought you were "wrapped around the axel".  I fixed it: 
[pf-11094.zip](https://github.com/primefaces/primefaces/files/13621523/pf-11094.zip)

```xml

<p:commandButton id="reload" 
action="#{testView.getAlbums()}" 
value="Collapse All" 
immediate="true" 
update=":viewForm:viewTable" 
process=":viewForm:viewTable" 
oncomplete="PF('myViewTable').collapseAllRows();"/>

```

**Comment by vitsin** [comment]
Finally, thank you!!!
