### ISSUE TITLE
Editor: Upgrade QuillJS 2.0

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11096]
After 5+ years it looks like QuillJS may finally be releasing a 2.0 version.

https://github.com/quilljs/quill/releases/tag/v2.0.0

Marking this for PF 15.0 to keep it on the radar

**Comment by kiilivi** [comment]
QuillJS 2.0.0 is out.
https://github.com/quilljs/quill/releases/tag/v2.0.0

**Comment by melloware** [comment]
@kiilivi yep this is actually an easy upgrade I will see if anyone mind if it goes in 14.0.0

**Comment by stolp** [comment]
I no longer use p:editor but I have stong reservations about updating to an x.0.0 version in a late release candidate without testing.

**Comment by melloware** [comment]
yep i can leave it 15.0.0 but Quill made a VERY concerted effort to be backward compatible
