### ISSUE TITLE
CellEditor: Composite component not working in input facet

### ISSUE THREAD

**Issue by enunu** [primefaces/primefaces#11092]
### Describe the bug

Composite component not working in cellEditor of DataTable 

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13614548/primefaces-test-master.zip)

1. Edit a cell in a text column
2. See error

### Expected behavior

Composite components should be able to edit cells without errors.

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by fcorneli** [comment]
Had a quick look at your composite component. Try within your `cc:implementation` the following:
```xml
<div id="#{cc.clientId}">
    <h:outputLabel id="lbl" for="@next" value="composit component" />
    <h:inputText id="text" value="#{cc.attrs.value}" />
</div>
```

**Comment by enunu** [comment]
Thanks for the advice. However, the error message does not seem to change.
```
12月 08, 2023 11:05:07 午後 com.sun.faces.context.PartialViewContextImpl processPartial
情報: java.lang.ClassCastException: class javax.faces.component.UINamingContainer cannot be cast to class javax.faces.component.ValueHolder (javax.faces.component.UINamingContainer and javax.faces.component.ValueHolder are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @3a38e4dc)
```

**Comment by fcorneli** [comment]
So your composite component needs to become a value holder.
See:
https://github.com/e-Contract/enterprise-jsf/releases/download/enterprise-jsf-1.12.3/enterprise-jsf.pdf
Section 2.9.1 Backing Component page 87.

**Comment by tandraschko** [comment]
implement ValueHolder or use `<composite:editableValueHolder name="text"/>`
the second works with my upcoming PR
