### ISSUE TITLE
filter in smartphone with Firefox Browser for selectOneMenu

### ISSUE THREAD

**Issue by enricodevita** [primefaces/primefaces#111]
Hi 
there is a bug 
in smartphone with Firefox Browser for filter in 
<p:selectOneMenu  ... ...   filter="true" filterMatchMode="startsWith">
if i write something in search input field 
no items is selected
let me know

**Comment by kukel** [comment]
What version.... (both PF and FF) and does it work in other browsers? (and please use the forum first)

**Comment by cagataycivici** [comment]
Please use forum first.
