### ISSUE TITLE
SelectCheckboxMenu: has un-clickable dead space when not popped-up

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#11101]
### Describe the bug

When trying to click to pop up the menu, there is a lot of "dead space" i.e. space when clicking in, nothing happens.
This is not the case with the "advanced" popup menus, only with "basic" one
You can even see that the box isn't highlighted when the mouse in the dead space.

See https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml in the showcase.

### Reproducer

Reproduced in the Showcase

### Expected behavior

Menu pops up wen clicked anywhere within the menu region

### PrimeFaces edition

Community

### PrimeFaces version

12

### Theme

Any

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

### Browser(s)

Safari, Chrome

**Comment by melloware** [comment]
Can you make a video or something?  I have no idea what you mean by "dead space" ?

**Comment by lprimak** [comment]
YouTube video link: https://youtu.be/HsWjDJ47Ecg

Thanks @melloware

**Comment by melloware** [comment]
This looks like it was intentional and the trigger is declared as.

```js
this.triggers = this.jq.find('.ui-selectcheckboxmenu-trigger, .ui-selectcheckboxmenu-label');
```

So those items live inside the outer DIV.  I would have to research but it looks like this was intentional as in multiple mode it becomes this.

```js
if (this.cfg.multiple) {
                this.triggers = this.jq.find('.ui-selectcheckboxmenu-trigger, .ui-selectcheckboxmenu-multiple-container');
            }
```

That explains that slight dead space.

**Comment by lprimak** [comment]
Feels like some outdated artifact to me. Dead space is surely unintentional :)

**Comment by melloware** [comment]
Sorry i didn't mean dead space was unintentional...the side effect was unintentional but these specific selectors look very intentional.  I would have to research why it was done this way and not on the whole DIV.

**Comment by melloware** [comment]
OK it seems to work fine with my changes and all integration tests pass.

**Comment by lprimak** [comment]
Awesome!  Thank you!
