### ISSUE TITLE
SelectOneMenu (Advanced): Tab switch shortcut not working properly

### ISSUE THREAD

**Issue by jjlange** [primefaces/primefaces#11104]
### Describe the bug

Activating the tab switch shortcut while selecting an option in the SelectOneMenu does not function as intended. Instead of navigating to the next element in the form, it unintentionally jumps outside the website to a browser navigation element.

### Reproducer

Go to the Primefaces 13 Showcase example: [SelectOneMenu examples](http://www.primefaces.org:8080/showcase/ui/input/oneMenu.xhtml?jfwid=fa49b)

1. Click on 'Advanced' example
2. Go down to an option using the arrow keys
3. Don't press enter, instead use the tab key to go to the next element
4. See incorrect behaviour

### Expected behavior

Pressing the tab key should focus the input to the next available element in the form.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Version 116.0.5845.141 (Official Build) (64-Bit) (Windows)

**Comment by melloware** [comment]
Hmmm I am not seeing that locally.  When I press TAB it focuses the next Checkbox in the popup?

**Comment by melloware** [comment]
I think its related to: https://github.com/primefaces/primefaces/pull/10794

**Comment by jjlange** [comment]
Appreciate the quick fix. Works perfectly!

**Comment by melloware** [comment]
These fixes will be included in 13.0.4
