### ISSUE TITLE
Issue #6354 breaks the predefined Grid CSS columns style classes

### ISSUE THREAD

**Issue by JuanMiguelBG-Ticarum** [primefaces/primefaces#11102]
### Describe the bug

On the next components: DataGridRenderer and DataViewRenderer.

This issue #6354 breaks the Grid CSS columns styleclasses, because use a method of the class `StyleClassBuilder` that evaluate a condition to add the style classes. It isn't needed because the call to GridLayoutUtils.getColumnClass(flex, columns), returns the appropiate classes.

### Reproducer

Test the showcase with primeFaces v13.0.3.

### Expected behavior

The showcase with primeFaces v13.0.0 works successfully.

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

**Comment by melloware** [comment]
@JuanMiguelBG-Ticarum can you submit a PR for review?

**Comment by JuanMiguelBG-Ticarum** [comment]
The pull request was created for both master and 13.X branch.

Sorry for the delay, I wanted to be sure of the change.

**Comment by JuanMiguelBG-Ticarum** [comment]
The main problem is that without this change, the basic configuration doesn't honored de columns property of the grid layout.
