### ISSUE TITLE
"Select all" checkbox of table is triggered twice on Firefox

### ISSUE THREAD

**Issue by tgenevie** [primefaces/primefaces#11110]
### Describe the bug

Random issue only on firefox (no issue with chrome or edge) while clicking on the select all checkbox of a table : action is triggered twice, so we can not select all the data. Select by row  (one by one) works perfect. Only in firefox. It happens randomly, but when it appears, the issue stays in the view until we exit firefox. When the bug appears the component is triggered twice as we can see it in firefox's debugger. When no issue, it's triggered only once.

### Reproducer

It happened ramdomly only on firefox ...

### Expected behavior

Select all of table is triggered only once

### PrimeFaces edition

Community

### PrimeFaces version

6.2.0

### Theme

none

### JSF implementation

Mojarra

### JSF version

2.3.2

### Java version

8

### Browser(s)

Firefox

**Comment by jepsar** [comment]
The community does not support elite versions. Please read https://github.com/primefaces/primefaces#community--elite--pro and provide a [PrimeFaces Test](https://github.com/primefaces/primefaces-test) reproducer.

**Comment by melloware** [comment]
Closing with no response from OP
