### ISSUE TITLE
SelectManyMenu: filtering causes the items to appear with a huge distance to checkbox

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1111]
Hi, If the width of the component is set manually (for example if you want it to match a different input component, the checkbox colums has a huge distance. 

I know it can be fixed by overriding the CSS (Almost 300 lines of CSS workarounds already) - but please fix it in the component code, as i think the checkbox column should be fixed by default, it makes no sense having it grow like that.

It can be easily reproduced in showcase. Using Version 5.3.6 Elite

![PF-Bug-SMM](https://abload.de/img/pfbug2zxxsh.png)

**Comment by kukel** [comment]
300 lines of CSS workarounds is quite a few, but maybe you have specific requirements. We only needed less than 100... And those were no workarounds, just things done differently

**Comment by melloware** [comment]
Possible related to #2297

**Comment by tandraschko** [comment]
If i set a width of the of ui-selectManyMenu to e.g. 300px and filter in the showcase (https://www.primefaces.org/showcase/ui/input/manymenu/basic.xhtml), the size wont change.
@melloware would you like to have a look, to?

**Comment by melloware** [comment]
I can reproduce by making the current showcase `style="width:800px"`.

![image](https://user-images.githubusercontent.com/4399574/103546408-f04fd700-4e70-11eb-873e-090413b680f4.png)

Seeing if there is an easy fix
