### ISSUE TITLE
Datepicker: hide() doesn't call disableModality when touchUI = true

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#11115]
### Describe the bug

When calling `hide()` from JavaScript on a date picker, it works find on the desktop.
However, on mobile when `touchUI = true`, `hide()` leaves a gray screen (modality still on).

I believe that `hide()` should call `disableModality()` automatically to match both mobile and desktop functionality.

This is related to #9260 and the same reproducer applies.

### Expected behavior

Mobile and Desktop `hide()` should behave the same.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

### Browser(s)

Any

**Comment by melloware** [comment]
I will fix this for 13.0.4

**Comment by lprimak** [comment]
Fantastic! Thank you!
