### ISSUE TITLE
textEditor does not render the html page correctly

### ISSUE THREAD

**Issue by mciumac** [primefaces/primefaces#11122]
### Describe the bug

I am using the textEditor and its value is html string (page). The textEditor does not style the html page correctly does not recognizes the table columns and the styling. Please let me know if I have to configure anything else to solve this issue or this is a defect? It was working in editor that was deprecated and removed.

### PrimeFaces edition

None

### PrimeFaces version

11.0.0

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

8

### Browser(s)

Chrome

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
Closing with no response from OP. Will reopen if they provide the reproducer.
