### ISSUE TITLE
FileUpload: tests fail when path contains a empty space

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11134]
Windows 10, FileUploadUtilsTest#requireValidFilePath_AbsoluteFile:

Expected :Invalid directory, name does not match the canonical path.
Actual   :Invalid path: /D:/Development/OS%20Projects/primefaces/primefaces/target/test-classes/test.png

**Comment by tandraschko** [comment]
would be great if anyone could check it, i dont have much time the next weeks

**Comment by melloware** [comment]
I can fix this.

**Comment by tandraschko** [comment]
works fine, thank you!
