### ISSUE TITLE
Selecting Outputlink within a datatable column - triggers a POST call before the GET call to the link

### ISSUE THREAD

**Issue by darrynhall** [primefaces/primefaces#11133]
### Describe the bug

Selecting an outputlink within a datatable column - triggers a POST call to the datatable's page  before triggering the GET call to the link.

### Reproducer

Selecting the href link triggers a GET to the resource.  Selecting the outputLink triggers a POST to the parent page, and then a GET call to the resource.

```xml
<p:column id="reportNumber" 
		sortBy="#{submissionRecord.id}" 
		filterBy="#{submissionRecord.reportNumber}"
		filterStyle="width: 100px;" exportable="false"
		style="width: 120px; white-space: nowrap; text-align: center; vertical-align: top;">
	<f:facet name="header">
		<h:outputText value="Report Number" />
	</f:facet>
	<h:outputLink target="_blank" value="#{pageContext.request.contextPath}#{foreignTravelReportListController.urlLinkView}#{submissionRecord.id}">
		<h:outputText value="#{submissionRecord.reportNumber}"styleClass="underLineLink" />
	</h:outputLink>
	<a href="#{pageContext.request.contextPath}#{foreignTravelReportListController.urlLinkView}#{submissionRecord.id}">#{submissionRecord.id}</a>
</p:column>

```

### Expected behavior

Expect selection of the outputLink to trigger a GET call to the linked resource.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

All

### JSF version

4.0.1 (jakarta.faces)

### Java version

Java 17

### Browser(s)

Chrome 120.0.6099.72 (Official Build) (64-bit)

**Comment by melloware** [comment]
Have you tried 13.0.3?

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
