### ISSUE TITLE
DatePicker: Month navigator's back/previous button disabled incorrectly

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#11140]
### Describe the bug

When I have two datepicker in relation "Date from - Date To" period without range selection there is a scenario that incorrectly disables Date Picker's previous month in "To date" component.

Reproducer:
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/13701363/primefaces-test.zip)

### Reproducer

1. Select date in "From" datepicker in next month. Eg. If You test it in december, select some date in next year's january with help of month navigator, eg 15th of january
2. Select date in "From" datepicker in current month. Eg. If You test it in december, select some date in december with help of month navigator, eg 15th of december
3. Click in "To" datepicker in order to show it. If You test it in december, it will show december
4. Click "Next month" in month navigator. If you test it in december it will go to next year's january
5. Now Try to go back to previous month using month navigator to go back to december
6. You can't because it is disabled

### Expected behavior

Month navigator should be enabled in that scenario because minDate allows it

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

All

**Comment by majkers** [comment]
Maybe it was caused by a fix for https://github.com/primefaces/primefaces/issues/10819 ?

**Comment by melloware** [comment]
Patched Version:
[pf-11140.zip](https://github.com/primefaces/primefaces/files/13704353/pf-11140.zip)

**Comment by majkers** [comment]
Thanks!
