### ISSUE TITLE
InputNumber issue on keyup/down event

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1114]
Reported by Pro User;
We are using <p:inputNumber../> in our application. We noticed that on key event the value entered in the <p:inputNumber../> field does not get processed for the first time. We get null.
On the corresponding key events the old value (value entered on the previous key event) is being processed.
Please find the sample code below:

```
<p:inputNumber value="#{dataObject.numberValue}" maxValue="100" minValue="0.00">
      <p:ajax event="keyup" listener="#{eventHandler.calculateAmount()}" />
 </p:inputNumber>
```

**Comment by tandraschko** [comment]
I think your commit breaks the complete inputnumber.
It's currently built with a input and a hidden input.
The valid and cleaned value (without any prefix und suffix!) will be posted to the server and used for further processing.

**Comment by tandraschko** [comment]
To fix the keyup or any other event, you must do something similiar to:
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/inputnumber/2-inputnumber.js#L46

copyValueToHiddenInput must be executed to fill the hidden input before executing any ajax request.

So please revert and fix it the correct way.

**Comment by mertsincan** [comment]
Thanks a lot,Thomas.
