### ISSUE TITLE
p:panelGrid columns="8" not supported in PF 13.0.*

### ISSUE THREAD

**Issue by SimonePadovan** [primefaces/primefaces#11147]
### Describe the bug

When i try to use tag p:panelGrid with columns=8 using PF 13.0.0-13.0.4, this error is displayed:

`PanelGrid` "xxx" columns must be a number that factors into 12. For example: `1,2,3,4,6,12`

With PF 12 it has always worked well
It should work wth columns= 5,7,9,10 and 11 as well

### PrimeFaces edition

None

### PrimeFaces version

13.0.4

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

11

**Comment by jepsar** [comment]
That's by design. See also the migration guide:

> PanelGrid tabular layout in favor of responsive layout layout="grid" now the default. To fall back to legacy behavior set layout="tabular" columns="0"

https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/13_0_0?id=deprecated

**Comment by SimonePadovan** [comment]
ok thanks
