### ISSUE TITLE
PrimeExceptionHandler fails if response has been committed

### ISSUE THREAD

**Issue by erik-wramner** [primefaces/primefaces#1115]
If an exception occurs during the rendering phase and the response has been committed the PrimeExceptionHandler still calls redirect. That leads to an IllegalStateException and a partial page is rendered. It would be nice if the exception handler could check for a committed non-ajax request and at least attempt to salvage the situation. I will add a pull request shortly.

**Comment by tandraschko** [comment]
Looks good, thanks for the PR.
