### ISSUE TITLE
SelectOneMenu: Default value issue with Google page translator

### ISSUE THREAD

**Issue by Teutron-flo** [primefaces/primefaces#11154]
### Describe the bug

With 13.0.X it looks like the SelectOneMenu component has issues with the Google page translator.
![screenshot](https://github.com/primefaces/primefaces/assets/80260448/f409813f-7b6d-4623-8d47-1105793bd07e)

The page translator display instead of the "Select one" label, some font html tags and then the label value.
<font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Select One</font></font>

The same works perfect with 12.0.0.

### Reproducer

1. Open https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml with Chrome
2. Right click -> translate Page into any language or with the Option menu from Chrome
3. At "Hide NoSelection Option" or "Grouping" play around with the no selection / select one option
4. Instead of the value html code will be displayed

### Expected behavior

The correct value should be displayed with out plain html code in front. 
Like it is today for the 12.0.0 build.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.X

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

Chrome 119.0.6045.200

**Comment by melloware** [comment]
Confirmed.

**Comment by melloware** [comment]
OK I fixed it with a workaround using `escape="false"` to let the item render as HTML.

```xml
<f:selectItem itemLabel="Select One" itemValue="" escape="false"/>
```

**Comment by melloware** [comment]
Closing as a workaround is provided and it's really a Google implementation issue.
