### ISSUE TITLE
Showcase: GMap not working 

### ISSUE THREAD

**Issue by ZeroBrushV2** [primefaces/primefaces#11188]
The GMap showcase doesn't work showing this error:

![image](https://github.com/primefaces/primefaces/assets/123548294/6c6d4279-e052-40a9-8f43-4495a7712f11)

Checking on the console shows up this error:
```
js?sensor=true:135  Google Maps JavaScript API error: InvalidKeyMapError
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error
```
Happens in showcase: https://www.primefaces.org/showcase/ui/data/gmap/basic.xhtml?jfwid=16324

**Comment by jepsar** [comment]
See also https://github.com/primefaces/primefaces/issues/8957

**Comment by melloware** [comment]
it looks like because the showcase does not use an API Key.

```js
<script src="https://maps.google.com/maps/api/js?sensor=false"></script>
```

I think Google recently switched to requiring an API key no matter what where the old way it would show you the map with "Demo" watermark or something?

**Comment by jepsar** [comment]
I've asked PrimeTek for an API key.
