### ISSUE TITLE
Unexpected Behavior with InputNumber's MinValue and MaxValue Constraints

### ISSUE THREAD

**Issue by sbenhadja** [primefaces/primefaces#11195]
### Describe the bug

I've encountered a peculiar behavior with the InputNumber component when setting the MinValue and MaxValue attributes. When specifying MinValue="-1" and MaxValue="10", the component restricts the input within this range, which functions as expected.

However, when adjusting the values to MinValue="1" and MaxValue="10", an issue arises where the input allows values beyond the specified range, such as 11 or 100. These values are invalid for my use case. Additionally, upon submitting with AJAX disabled (ajax="false") in the submit button, the invalid message box appears under the InputNumber if a number outside the specified interval is entered.

This behavior is inconsistent and does not adhere to the defined constraints, causing incorrect data entry, automatic adjustment without proper validation, and unexpected error messages in the UI.

### Reproducer

1. Set the InputNumber component's MinValue to 1 and MaxValue to 10.
2. Disable AJAX (ajax="false") in the submit button.
3. Try entering a value greater than 10 or less than 1 in the InputNumber.
4. Note that the input accepts values beyond the specified range and triggers an invalid message box under the InputNumber.
5. 
[inputNumber.txt](https://github.com/primefaces/primefaces/files/13794549/inputNumber.txt)

### Expected behavior

The InputNumber should strictly adhere to the specified MinValue and MaxValue constraints, preventing entry of values beyond the defined range, regardless of AJAX settings in the submit button. Any input outside this range should trigger an error or should not be accepted without proper validation.

This issue impacts the accuracy of data entry, UI consistency, and requires resolution to ensure the InputNumber component functions correctly within the specified constraints, regardless of AJAX settings in the submit button.

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
@sbenhadja you can read all about it in detail here as its an AutoNumeric issue: https://github.com/primefaces/primefaces/issues/10607
