### ISSUE TITLE
IT: Tree flickering test

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11203]
This test fails intermittently on the nightly IT.

variants:
```
Tree003Test.tabbing:72->AbstractPrimePageTest.assertDisplayed:88 Element should be displayed!
Tree003Test.tabbing:70->AbstractPrimePageTest.assertDisplayed:88 Element should be displayed!
Tree003Test.tabbing:70 expected: <true> but was: <false>
```

**Comment by melloware** [comment]
@christophs78 still see this one intermittently but I am stuck on what the issue could be?

**Comment by christophs78** [comment]
Side-notes:

- not new (allso happend with Chrome 119, currently 120)
- local not reproduceable even with @RepeatedTest(200) - happens maybe only under heavy overall system load

**Comment by melloware** [comment]
Yes I think its when the GitHub Actions server its running on is under heavier load.

**Comment by christophs78** [comment]
NOK:
![image](https://github.com/primefaces/primefaces/assets/10461942/5edd67e2-4c45-4237-94f5-298622d68ed6)
![image](https://github.com/primefaces/primefaces/assets/10461942/beade957-2efd-4a77-b896-3ce917e17d9b)

No HTML-difference between OK and NOK.
```HTML
<!-- NOK -->
<div class="ui-treenode-content ui-treenode-droppable ui-draggable ui-draggable-handle ui-droppable" role="treeitem"
     tabindex="-1" aria-label="" aria-expanded="false" aria-selected="false"><span class="ui-treenode-leaf-icon"></span><span></span><span
        class="ui-treenode-label ui-corner-all">Meeting</span></div>
<ul class="ui-treenode-children" role="group" style="display:none"></ul>

<!-- OK -->
<div class="ui-treenode-content ui-treenode-droppable ui-draggable ui-draggable-handle ui-droppable" role="treeitem"
     tabindex="-1" aria-label="" aria-expanded="false" aria-selected="false"><span class="ui-treenode-leaf-icon"></span><span></span><span
        class="ui-treenode-label ui-corner-all">Meeting</span></div>
<ul class="ui-treenode-children" role="group" style="display:none"></ul>
```

Some scroll-postition-thing or ...?

**Comment by melloware** [comment]
It has to be the Selenium driver or browser for `isDisplayed` thinks its off screen somehow?

**Comment by christophs78** [comment]
Yep, think so too.
Just added a few more System.out - statements to diagnose this. At least kind of reproduceable on Github Actions with `@RepeatedTest(200)`.

**Comment by christophs78** [comment]
My current idea is to take screenshots whenever we run into this issue. (Because it´s still not clear to me what´s going on.)
Taking screenshots with selenium should be easy. (https://stackoverflow.com/questions/3422262/how-to-take-a-screenshot-with-selenium-webdriver)
Part 2 would be to make them accessible. First write dem into Linux-Filesystem, second https://github.com/actions/upload-artifact?tab=readme-ov-file#upload-an-entire-directory.

**Comment by melloware** [comment]
Great job!
