### ISSUE TITLE
enable CLIENT_SIDE_LOCALISATION per default

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11211]
I think it would be a good default behavior to add it

users with custom i18n JS can still deactive it

**Comment by melloware** [comment]
I am totally OK with that.

**Comment by melloware** [comment]
We will have to deactivate it for our showcase web.xml as well since the locale switching is handled there and we have a few showcase examples showing localization already that will be broken.

**Comment by tandraschko** [comment]
hmmm
doesnt our LocaleUtils respect the ViewRoot locale or why it can be switched anymore?

**Comment by melloware** [comment]
oh maybe you are right i think this will work let me test it some more.

**Comment by melloware** [comment]
OK removed that from Showcase it is working fine.
