### ISSUE TITLE
Overlay Panel: Does not work when in a Dialog and contains Inputs with p:ajax

### ISSUE THREAD

**Issue by DaniEll-AT** [primefaces/primefaces#11229]
### Describe the bug

When there are Inputs with p:ajax in an OverlayPanel, the p:ajax is not working as expected when the whole form is in a Dialog.

The Component Hierarchy is: Dialog - Form - OutputPanel - Input with p:ajax
Screencap of what is happening: ![pf-overlay-in-dialog](https://github.com/primefaces/primefaces/assets/22881943/7afa06f9-cc16-41f4-8f00-a910f44e17a1)

When the same Code is used outside of a Dialog (Form - OutputPanel - Input with p:ajax), everything works as expected.

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13827519/primefaces-test-master.zip)

### Expected behavior

OverlayPanel "works" inside a Dialog like outside of Dialogs.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.4

### JSF implementation

All

### JSF version

2.2

### Java version

17

**Comment by melloware** [comment]
Weird.  Whatever is going on here I tested your reproducer in 12.0.0 it was broken there also.

**Comment by melloware** [comment]
Fixed it.  Because its inside a dialog but the Overlay is in the Document.Body it is outside the `<h:form>`

Simply change to `appendTo="@(parent)"` like this and it works...

```
<p:overlayPanel for="btn-test-dlg" appendTo="@(parent)">
```

**Comment by tandraschko** [comment]
Is '@(parent)' a valid PFS or you you mean '@parent'?

**Comment by melloware** [comment]
weird `@(parent)` totally works. it puts it inside the dialog.

**Comment by melloware** [comment]
and `@parent` also works.

**Comment by melloware** [comment]
@DaniEll-AT you are right.  I must have been testing with 12.0.0 and it was working but 13.0.4 does not.

[pf-11229.zip](https://github.com/primefaces/primefaces/files/13860130/pf-11229.zip)

**Comment by melloware** [comment]
OK the issue is the AJAX submission.  

12.0.0

```
javax.faces.partial.ajax	"true"
javax.faces.source	"frmDialog:j_idt9"
javax.faces.partial.execute	"frmDialog:j_idt9"
javax.faces.partial.render	"frmDialog:j_idt9+frmDialog:output-container-dlg"
javax.faces.behavior.event	"valueChange"
javax.faces.partial.event	"change"
frmDialog	"frmDialog"
frmDialog:j_idt9_focus	""
frmDialog:j_idt9_input	"2"
```

14.0.0

```
javax.faces.partial.ajax	"true"
javax.faces.source	"frmDialog:j_idt9"
javax.faces.partial.execute	"frmDialog:j_idt9"
javax.faces.partial.render	"frmDialog:j_idt9+frmDialog:output-container-dlg"
javax.faces.behavior.event	"valueChange"
javax.faces.partial.event	"change"
frmDialog	"frmDialog"
```

The value `frmDialog:j_idt9_input	"2"` is not included in the request

**Comment by melloware** [comment]
Issue was introduced with this ticket: https://github.com/primefaces/primefaces/pull/9316

There is 1 very subtle difference between the resolveAppendTo in core utils and in the overlaypanel.

**Comment by melloware** [comment]
Working reproducer:
[pf-11229.zip](https://github.com/primefaces/primefaces/files/13891316/pf-11229.zip)


MonkeyPatch:

```js
PrimeFaces.utils.resolveAppendTo = function(widget, target, overlay) {
    if (widget && target && target[0]) {
        var dialog = target[0].closest('.ui-dialog');

        if (dialog && overlay && overlay.length) {
            var $dialog = $(dialog);

            //set position as fixed to scroll with dialog
            if ($dialog.css('position') === 'fixed') {
                overlay.css('position', 'fixed');
            }

            //append to body if not already appended by user choice
            if (!widget.cfg.appendTo) {
                widget.cfg.appendTo = "@(body)";
                return widget.cfg.appendTo;
            }
        }

        return widget.cfg.appendTo;
    }

    return null;
};
```
