### ISSUE TITLE
@form not evaluated correclty since using SearchExpressions of JSF 2.3

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11231]
The issue was detected in #11146

PF SearchExpressions resolves `@form` on the server side and renders the clientId
JSF 2.3 SearchExpressions doesn't resolve `@form` at the server and just passthrough `@form` to the client

this is actually no problem if the component doenst use appendTo
in the linked issue, the menubutton is moved outside the form and `@form` isn't resolveable anymore

**Comment by tandraschko** [comment]
anyway, client side should log a error that `@form` cant be resolved

**Comment by melloware** [comment]
I like option 3 as option 2 sounds like it would be a messier and buggier potential fix?   as for 1 you are right no way spec is getting changed that fast.
