### ISSUE TITLE
jQuery.remove(selector) behaviour / DataTable: RowReorder - Dragged row is shown as empty

### ISSUE THREAD

**Issue by Krzysztof-13** [primefaces/primefaces#11245]
### Describe the bug

Hi,

I found a that bug while using DataTable.
After research it appears that it is connected to jQuery.remove method that changes its behaviour.

```javascript
//(from datatable.js)
                for(var i = 0; i < helperCells.length; i++) {
                    var helperCell = helperCells.eq(i);
                    helperCell.width(cells.eq(i).width());
                    // #5584 reflow must remove column title span
                    helperCell.children().remove('.ui-column-title');
                }
```
That line `helperCell.children().remove('.ui-column-title');` removes all cell children, skips filtering by selector.
It could be changed to `helperCell.children().find('.ui-column-title').remove(;` and it will work fine, but still the jQuery.remove function behaviour is different. Before using PrimeFaces components it works as expected.

Real cause is inside file `jquery/jquery.ui.pfextensions.js`.
So importing jquery/jquery-plugins.js by any PrimeFaces component, for example p:chips or p:dataTable, cause remove function to skip argument.

```javascript
//(from jquery/jquery.ui.pfextensions.js)
// GitHub #9941 tooltip removal fix
(function() {
    var ev = new $.Event('remove'),
        orig = $.fn.remove;
    $.fn.remove = function() {        
        $(this).trigger(ev);
        return orig.apply(this, arguments);
    };
})();
```

Triggering remove event on element removes it, without checking the selector provided in arguments.
So as a fix we could check if arguments is empty, and only then trigger event.

### Reproducer

**Reproducer of jQuery.remove problem**
1. Create simple .xhtml page with content as follows:
```html
    <button onclick="$('.parentDiv').children().remove('.elementToRemove')"></button>

    <div class="parentDiv">
        <div class="elementToRemove">
            Element to remove
        </div>
        
        <div class="element">
            Element 1 to NOT REMOVE
        </div>
        
        <div class="element">
            Element 2 to NOT REMOVE
        </div>
    </div>
```

2. Click on button. Only one element has been removed. Thats correct.

3. Change xhtml page. Add any PF component that imports jquery-plugins.js (p:chips or p:dataTable or another one).

```html
<p:chips></p:chips>
```
5. Click on button. ALL elements have been removed! Thats incorrect!

**Reproducer of DataTable problem**:

1. Create simple DataTable with rowReorder enabled, and with columns with some elements inside them (span, div).          
```html
            <p:dataTable id="table" value="#{simpleView.rows}" var="row" 
                         draggableRows="true" 
                         selectionMode="multiple"
                         rowKey="#{row}">
                <p:column>
                        THIS TEXT WILL BE VISIBLE
                    <div>
                        #{row}
                        THIS TEXT WILL BE INVISIBLE!
                    </div>
                </p:column>
            </p:dataTable>
```

2. Initialize DataTable with some rows.
```java

@Named
@ViewScoped
public class SimpleView implements Serializable {

    private List<String> rows = new ArrayList<>();

    @PostConstruct
    public void init() {
        for (int i = 0; i < 1000; i++) {
            rows.add("Row #" + i);
        }
    }

    public List<String> getRows() {
        return rows;
    }

}
```

3. Drag any row (only part of column is visible).

### Expected behavior

**JQuery.remove problem**
I expected that jQuery.remove behaviour will be not changed.

**DataTable problem**
I expected to see whole row content that is being dragged, even if it consists of some other elements (div, spans or others).
On PF 13.0.4 only direct content is preserved.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.4

### Theme

Saga (not connected to theme)

### JSF implementation

Mojarra

### JSF version

2.2 / 2.3

### Java version

1.8

**Comment by melloware** [comment]
Yes good call.  We should fix this...

```java
(function() {
    var ev = new $.Event('remove'),
        orig = $.fn.remove;
    $.fn.remove = function() {        
        $(this).trigger(ev);
        return orig.apply(this, arguments);
    };
})();
```

The only run if the arguments are empty and no selector is applied.

**Comment by melloware** [comment]
@Krzysztof-13 are you going to submit a PR?

**Comment by Krzysztof-13** [comment]
@melloware Yes, I will submit PR for this one.

**Comment by Krzysztof-13** [comment]
I hope I have done it right :) Please do review.

**Comment by melloware** [comment]
Looks good Integration Tests running now!

**Comment by melloware** [comment]
I will backport to 13.0.5
