### ISSUE TITLE
Tree: multipleDrag is not working correctly

### ISSUE THREAD

**Issue by Krzysztof-13** [primefaces/primefaces#11252]
### Describe the bug

When you create a tree, and enable `multipleDrag` option it still works as single drag.  I also noticed that sometimes there are errors in Java console with NumberFormatException (cannot convert '' to number).

On earlier PF versions it worked, but there were bug with dragging more than 10 nodes at once. We fixed it by monkeypatch, because there is incorrect parent / child generated nodeKey checking. Code assumes that Node 1 and Node 11 are parent and child.

I will create PR with a fix to review.

### Reproducer

1. Create tree and enable multipleDrag, selectionMode=multiple.
```html
            <p:tree 
                id="tree"
                value="#{testView.root}" 
                var="object" 
                nodeVar="node"
                datakey="#{object}"
                selectionMode="multiple" 
                selection="#{testView.selectedNodes}"
                draggable="true" 
                droppable="true" 
                dragdropScope="demo"
                dynamic="true"
                cache="true"
                multipleDrag="true"
                >

                <p:ajax event="select" update="tree" />
                <p:ajax event="unselect" update="tree" />
                <p:ajax event="dragdrop" update="tree" />

                <p:treeNode type="default">
                    <div>
                        <span>#{object}</span>
                    </div>
                </p:treeNode>
            </p:tree>
```

3. Create more than 10 tree nodes.
4. Select multiple nodes and change their positions.
5. Only one node changed its position, not all of them.

### Expected behavior

I expected that with multipleDrag all selected treeNodes will move.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.4

### JSF implementation

Mojarra

### JSF version

2.2 / 2.3

### Java version

1.8

**Comment by Krzysztof-13** [comment]
PR: https://github.com/primefaces/primefaces/pull/11253

**Comment by melloware** [comment]
Thank you for the PR. I will review tomorrow and backport to 13.0.5!

**Comment by melloware** [comment]
13.0.5 is out with all your fixes. Thank you!
