### ISSUE TITLE
Enter does not submit form if a selectOneMenu is focused

### ISSUE THREAD

**Issue by BrianSiimAndersen** [primefaces/primefaces#1127]
When pressing Enter in a form where the focus is in a selectOneMenu nothing happens. The same behavior can be seen in the PrimeFaces ShowCase: http://www.primefaces.org/showcase/ui/ajax/dropdown.xhtml

I would like the Enter to submit the form unless the use has opened the menu. When the menu is open Enter is used to select a value in the list.

**Comment by kukel** [comment]
Please post your patch here…  or better yet, make a real pull request

**Comment by BrianSiimAndersen** [comment]
I'm not familiar with Git, so I don't know how to make a pull request. But this is what I did to make it work:

```
PrimeFaces.widget.SelectOneMenu.prototype.handleEnterKey = function(event) {
    if (this.panel.is(':visible')) {
        this.selectItem(this.getActiveItem());
        event.preventDefault();
        event.stopPropagation();
    }
}
```

**Comment by cagataycivici** [comment]
How does h:selectOneMenu behave?

**Comment by BrianSiimAndersen** [comment]
Apparently it depends on the browser when using h:selectOneMenu. In Safari the form gets submitted, in Firefox it doesn't.

**Comment by cagataycivici** [comment]
So what should we do at p:selectOneMenu side, normalize it or delegate to browser?

**Comment by kukel** [comment]
Normalize... See also http://stackoverflow.com/questions/2968693/why-doesnt-hitting-enter-when-a-select-is-focused-submit-the-form (so as expected it is plain html related). Behaviour like FF is has my preference.

**Comment by melloware** [comment]
@kukel this sounds like its expected behavior is it safe to close this ticket?

**Comment by melloware** [comment]
I am going to close as WontFix since this is the default HTML5 behavior for this component.
