### ISSUE TITLE
DatePicker: Button bar option with LocalDateTime value changes button "Today" to "Now"

### ISSUE THREAD

**Issue by chaloma1** [primefaces/primefaces#11279]
### Describe the bug

I have used a DatePicker komponent with showButtonBar option = true. If i am using LocalDateTime instead of just LocalDate value, the "today" button is replaced with "now" button. Haven't found any documentation how to change the button text or add it into our locale script. Tried adding "now" key into locale and it works. Can you please consider updating your documentation / showcase? Thank you.

```
PrimeFaces.locales['en'] = {
      currentText: 'Current date',
      today: 'Current date',
      now: 'Current date and time'
    };
```

### Reproducer

[primefaces-test-git.zip](https://github.com/primefaces/primefaces/files/13916157/primefaces-test-git.zip)

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.4

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

**Comment by melloware** [comment]
This was added in 13.0.2: https://github.com/primefaces/primefaces/issues/10754  Showcase is still 13.0.0 but i will check the 13.0.0 docs to see if this was updated. it definitely was in 14.0.0 docs
