### ISSUE TITLE
SelectOneMenu: Placeholder text disappears

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#11282]
### Describe the bug

The placeholder text on SelectOneMenu disappears when switching values.

### Reproducer

1. Start the reproducer [primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13939760/primefaces-test-master.zip)
2. Click on the SelectOneMenu
3. The placeholder text disappears
4. Select the value "Text1"
5. Select the empty value
6. The placeholder text still is not present

### Expected behavior

When the empty value is selected with placeholder, the placeholder text should always be visible.

### PrimeFaces edition

Elite, Community

### PrimeFaces version

13.0.4, 14.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

**Comment by pfumi** [comment]
In the code here 
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L1136 and 
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L1155
the no-break space "&nbsp;" HTML entity is compared. But when switching off values and switching back to the empty value, then the input is the non-breaking space character "\xa0". So the comparison isn't working anymore.

I think the solution is to also add \xa0. in the comparison.

MonkeyPatch:
```
if (PrimeFaces.widget.SelectOneMenu) {
	PrimeFaces.widget.SelectOneMenu.prototype.setLabel = function(value) {
		var displayedLabel = this.getLabelToDisplay(value);
		var valueEmpty = value === '&nbsp;' || value === '\xa0';
		if (this.cfg.editable) {
			if (valueEmpty)
				this.label.val('');
			else
				this.label.val(displayedLabel);

			var hasPlaceholder = this.label[0].hasAttribute('placeholder');
			this.updatePlaceholderClass((hasPlaceholder && valueEmpty));
		}
		else if (this.cfg.alwaysDisplayLabel && this.cfg.label) {
			this.label.text(this.cfg.label);
		}
		else {
			var labelText = this.label.data('placeholder');
			if (labelText == null || labelText == "") {
				labelText = '&nbsp;';
			}

			this.updatePlaceholderClass((valueEmpty && labelText !== '&nbsp;'));

			if (valueEmpty) {
				if (labelText != '&nbsp;') {
				this.label.text(labelText);
				} else {
					this.label.html(labelText);
				}
			}
			else {
				this.label.removeClass('ui-state-disabled');

				var option = null;
				if(this.items) {
					var selectedItem = this.items.filter('[data-label="' + $.escapeSelector(value) + '"]');
					option = this.options.eq(this.resolveItemIndex(selectedItem));
				}
				else {
					option = this.options.filter(':selected');
				}

				if (option && option.data('escape') === false) {
					this.label.html(displayedLabel);
				} else {
					this.label.text(displayedLabel);
				}
			}
		}
	}
}
```

**Comment by pfumi** [comment]
@melloware I can't submit immediately right now, But I will do.
Just another thing about placeholder, the styling can also be improved.
When you look here https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L1608, the `ui-selectonemenu-label-placeholder` is applied, but I can't find any CSS rule within the themes.

I think we could apply following here https://github.com/primefaces/primefaces-sass-theme/blob/67b4832593fddd9437392f6be831903605ef9c22/theme-base/components/input/_selectonemenu.scss#L11:

```
.ui-selectonemenu-label {
   ...
   &.ui-selectonemenu-label-placeholder {
      color:  $inputPlaceholderTextColor;
   }
   ...
}

I can submit a PR for this too.

**Comment by melloware** [comment]
Perfect!

**Comment by melloware** [comment]
I took care of the theme change for you.

**Comment by pfumi** [comment]
Perfect thanks!

**Comment by melloware** [comment]
@pfumi i will take care of this one.

**Comment by pfumi** [comment]
Thank you! I was just to slow
