### ISSUE TITLE
dialogReturn not work with commandLink

### ISSUE THREAD

**Issue by huygun** [primefaces/primefaces#1128]
DialogReturn event is not working  with commandLink in  6.0-SNAPSHOT.

Can be reproduce with changing showcase sample data.xhtml from 

`
<p:commandButton value="Select Car" icon="ui-icon-extlink" actionListener="#{dfView.chooseCar}">
   <p:ajax event="dialogReturn" listener="#{dfView.onCarChosen}" update="growl" />
</p:commandButton>
`
to 
`
<p:commandLink value="Select Car" icon="ui-icon-extlink" actionListener="#{dfView.chooseCar}">
      <p:ajax event="dialogReturn" listener="#{dfView.onCarChosen}" update="growl" />
</p:commandLink>
`

**Comment by mertsincan** [comment]
Similar issue #1202
