### ISSUE TITLE
LinkButton: value _must_ be of type String

### ISSUE THREAD

**Issue by commodis** [primefaces/primefaces#11285]
### Describe the bug

The [documentation for the linkbutton](https://primefaces.github.io/primefaces/13_0_0/#/components/linkbutton) states, that the value of a link-button can be of type `Object`.
Thus it should allow types like `Long`.

The [current implementation of the renderer](https://github.com/primefaces/primefaces/blob/1866844d7262d75e76a78a0baeaa15397686b086/primefaces/src/main/java/org/primefaces/component/linkbutton/LinkButtonRenderer.java#L52) (and few [others](https://github.com/primefaces/primefaces/blob/1866844d7262d75e76a78a0baeaa15397686b086/primefaces/src/main/java/org/primefaces/component/button/ButtonRenderer.java)) cast to `String` resulting in exceptions when applied to other types like `Long`:

```bash
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
```

The highlighted line

> boolean hasValue = LangUtils.isNotBlank((String) linkButton.getValue()) || linkButton.hasDisplayedChildren();

could be rewritten to mitigate that short-coming like this

```java
String value = linkButton.getValue().toString();
boolean hasValue = LangUtils.isNotBlank(value) || linkButton.hasDisplayedChildren();
```

where `linkButton.getValue()` might be `null`.

### Reproducer

```xml
<p:linkButton value="#{bean.longValue}" />
```

```java
class Bean {
     Long longValue;

     public Long getLongValue() {
         return longValue;
     }
}
```

### Expected behavior

showing the long value as the button text

### PrimeFaces edition

None

### PrimeFaces version

13.0.4

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by tandraschko** [comment]
we should just reuse CoreRenderer#renderButtonValue

**Comment by melloware** [comment]
I will look at it now.
