### ISSUE TITLE
Button: value must be of type String

### ISSUE THREAD

**Issue by commodis** [primefaces/primefaces#11296]
### Describe the bug

Similar to https://github.com/primefaces/primefaces/issues/11285#issue-2082258159 the [documentation for the button](https://primefaces.github.io/primefaces/13_0_0/#/components/button) states, that the value of a button can be of type `Object`.
Thus it should allow types like `Long`.

The [current implementation of the renderer](https://github.com/primefaces/primefaces/blob/264840fcd5bce0be47d0bacb5d9c704bec60b073/primefaces/src/main/java/org/primefaces/component/button/ButtonRenderer.java#L53) cast to `String` resulting in exceptions when applied to other types like `Long`:

```bash
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
```

The highlighted line

> String value = (String) button.getValue();

could be rewritten to mitigate that short-coming like this

```java
Object value = button.getValue();
```

or like this

```java
renderButtonValue(writer, button.isEscape(), button.getValue(), title, button.getAriaLabel());
```

### Reproducer

```xml
<p:button value="#{bean.longValue}" />
```

```java
@Named
class Bean {
     Long longValue;

     public Long getLongValue() {
         return longValue;
     }
}
```

### Expected behavior

showing the long value as the button text

### PrimeFaces edition

None

### PrimeFaces version

13.0.4

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by commodis** [comment]
I would like to use the same methodology as @melloware and provide my first PR!

https://github.com/primefaces/primefaces/pull/11297

I hope the PR was not premature

**Comment by commodis** [comment]
As a side information - I checked all other button renderers and I have found no further String castings

**Comment by melloware** [comment]
Excellent I will test your PR today.
