### ISSUE TITLE
Ajax parameters are not passed to Global Callbacks

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#113]
When using ajaxStatus callbacks such as oncomplete and onerror, parameters like xhr are not passed. However in 5.2, they are available.

**Comment by LZaruba** [comment]
Hi, is there any resolution to this issue or any "official" workaround to it? Parameters are still not available as of 5.3.

Thanks

LZ

**Comment by ivy-rew** [comment]
PrimeFaces API exists to consume the XHR context that was recently executed: see PrimeFaces.ajax.Queue.xhrs[0]
![thereIsAGeneralException_contextInformation](https://user-images.githubusercontent.com/15085693/58103376-26304100-7be3-11e9-924e-b3e6f9686a18.png)
