### ISSUE TITLE
Proposal list associated to AutoComplete is proposed when input is Empty

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#1130]
This error is reproductible on PrimeFaces DEMO.

You type e0 on first autocomplete widget named SIMPLE.

Then you type QUICKLY (it is important) 2 times on BACKSPACE key and the widget display the same Porposal List Box.

If you click SLOWLY, the widget is cleared without displaying the Proposal List Box.

it is not normal that the input's speed has an inlfuence on widget's behavior !

**Comment by tandraschko** [comment]
can't replicate it when running PF showcase trunk.
Please create a new issue with all infos if it's still replicatable for you with trunk.

**Comment by schlebe** [comment]
This issue seems to be corrected in issue [#2769](https://github.com/primefaces/primefaces/issues/2769)
