### ISSUE TITLE
CSP: Default command pointing ajax="false" does nothing

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#11301]
### Describe the bug

Hi, 
in our app we use p:defaultCommand quite a lot, sometimes pointing to ajax="false" commandButton and sometimes to ajax="true".

We found out that when CSP is turned ON, the ajax="false" commandButton is not invoked when user presses ENTER in input field. 

Please see attached reproducer .zip.

I tried PF versions 13.0.2 and 13.0.4, both not working.

### Reproducer

See attached .zip file with primefaces-test reproducer: 
[defaultcommand_vs_ajaxfalse.zip](https://github.com/primefaces/primefaces/files/13975272/defaultcommand_vs_ajaxfalse.zip)

Snippet from reproducer:
```
<h:form id="frmTest">
            value:
            <br/>

            <p:inputText id="inputValueId" value="#{testView.inputValue}"/>

            <br/><br/>

            <p:commandButton id="cb_next_ajax_true" value="next with attribute ajax true" action="step2" ajax="true"/>
            <br/>
            <p:commandButton id="cb_next_ajax_false" value="next with attribute ajax false" action="#{testView.next()}"
                             process="@form" update="@form" ajax="false"/>

          <!-- With ajax it works great WITH and WITHOUT CSP -->
<!--            <p:defaultCommand target="cb_next_ajax_true"/>-->

          <!-- NON AJAX works only when CSP disabled -->
            <p:defaultCommand target="cb_next_ajax_false"/>
            
        </h:form>
```

### Expected behavior

I expect that the  defaultCommand pointing to ajax="false" commandButton would invoke the button both when CSP ON and OFF.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

17

### Browser(s)

Chrome

**Comment by melloware** [comment]
I will take a look.

**Comment by melloware** [comment]
OK its caused by this issue and fix: https://github.com/primefaces/primefaces/issues/5790

**Comment by melloware** [comment]
OK I have a fix.  I need to check if the button is AJAX or not whether to prevent the click.

**Comment by martin654** [comment]
@melloware Hi, thanks for the fix and 13.0.5 release. It looks good!

**Comment by melloware** [comment]
Thanks for reporting and confirming!

**Comment by martin654** [comment]
@melloware  Hi, I tried PF 15.0.0-RC2 recently and found that this issue is back. It works with PF 14.0.10 and with PF 13.0.10 though. Could you please check it? Thanks

**Comment by melloware** [comment]
@martin654 i can reproducer it using the same reproducer above?

**Comment by martin654** [comment]
@melloware yes, just change the PF version to 15.0.0-RC2

**Comment by melloware** [comment]
thanks let me investigate

**Comment by melloware** [comment]
@martin654 can you open a new issue you can just copy and paste your entire description from above.

**Comment by martin654** [comment]
@melloware  created new issue: https://github.com/primefaces/primefaces/issues/13283

Thanks for the effort.
