### ISSUE TITLE
Locale: Aria missing key default

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#11314]
### Describe the bug

After migrating the codes from LazyDataModel to JPALazyDataModel, I got this defect for the all listing pages.
DataTable rows are available, but they are not shown on the page although they are seen in the code. I share some screen captures below. I will try to create and share the reproducer soon.

This is the javascript error.

<img width="1379" alt="Screenshot 2024-01-20 at 12 24 56" src="https://github.com/primefaces/primefaces/assets/9448030/6a88d4e3-2141-4583-9bec-b62bed784d8c">

This is how I create DataTable.

<img width="1054" alt="Screenshot 2024-01-20 at 12 26 20" src="https://github.com/primefaces/primefaces/assets/9448030/78a323b9-1b4a-4c48-b2db-bed4bb6cac24">

Building JPALazyDataModel (no filters or restrictions)

<img width="446" alt="Screenshot 2024-01-20 at 12 27 49" src="https://github.com/primefaces/primefaces/assets/9448030/29b3b6ff-4d72-4fcb-9d20-f265b1d8e66e">

And the result. As it can be seen rows are available inside HTML code, but not shown on the page.

<img width="1680" alt="Screenshot 2024-01-20 at 14 32 31" src="https://github.com/primefaces/primefaces/assets/9448030/69b57173-26a8-43a0-ad55-309959699c56">

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-SNAPSHOT

### Theme

Avalon

### JSF implementation

Mojarra

### JSF version

4.0.5

### Java version

17.0.10

### Browser(s)

Chrome 17.3, Firefox 121.0.1

**Comment by melloware** [comment]
Please use the JPA Lazy Tester to reproducer your issue.  We use it in Production without issue. We have a JPA LazyTable branch already for use: https://github.com/primefaces/primefaces-test/tree/jpa

**Comment by aripddev** [comment]
I could not reproduce the problem using the primefaces-test:jpa. I wonder if there might be a problem with the template.

**Comment by melloware** [comment]
Yeah could it be a CSS issue?  But without a reproducer there is not much the community can do.  Have you updated your Avalon theme to the latest?

**Comment by melloware** [comment]
Oh no i think i might see the issue.

**Comment by melloware** [comment]
What language are you using?  The error is because the IL8N ariaPageLabel is NULL.

```js
this.ariaPageLabel = PrimeFaces.getAriaLabel('pageLabel');
```

**Comment by melloware** [comment]
If you open up a console in your app and type `PrimeFaces.getAriaLabel('pageLabel');` you should get something like below...

![image](https://github.com/primefaces/primefaces/assets/4399574/bd49bb72-8f54-452d-a7ad-0b0f5e74a7dd)

**Comment by aripddev** [comment]
It is "undefined"

<img width="488" alt="Screenshot 2024-01-20 at 15 58 14" src="https://github.com/primefaces/primefaces/assets/9448030/b24372ec-160d-4e52-bd6f-70a729f42da4">

**Comment by aripddev** [comment]
> What language are you using? The error is because the IL8N ariaPageLabel is NULL.
> 
> ```js
> this.ariaPageLabel = PrimeFaces.getAriaLabel('pageLabel');
> ```

It is multi-language. We have 20 languages in total. So we have `i18n.js` file for PrimeFaces translations.

**Comment by aripddev** [comment]
Let me check the latest translations. It is because of missing labels as I understand.

**Comment by melloware** [comment]
AHHH its a new label. 14.0.0 adds TONS of new labels.

https://github.com/primefaces/primefaces/blob/3ab54cf5439cfea5b539789242e7c9677e205b3d/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js#L93

And `PrimeFaces.getAriaLabel('pageLabel');` falls back to `en_US` if it can't find a label but you must be overriding `en_US` ?

**Comment by melloware** [comment]
I just added a fix for 14.0.0 to display `???pageLabel???` when a key is missing instead of undefined in case anyone else has a similar setup to you.

**Comment by melloware** [comment]
Yes PF has added tons of new languages and translations for 14.0.0
