### ISSUE TITLE
DatePicker: enabledDates - allows the user to select only dates from the provided list

### ISSUE THREAD

**Issue by milansie** [primefaces/primefaces#11322]
### Description

In the old p:calendar component, we had a feature that allowed the user to select a date from just a few dates in the history (imagine the use case that you want to allow the user to select the days when a diary is written) - for this we used the `beforeShowDate` function with additional javascript function.

The new p:datePicker component doesn't have this feature, but it does have a function for specifying `disabledDates` - which is unfortunately unusable for this use case - you can't insert all but a few dates in the history into the List.

What do you think about a similar feature - the `enabledDates` DatePicker property, which could be used to specify only those dates that can be selected in the component - the others will be disabled.

### Describe the solution you would like

After a quick look at the code, I think it's not that hard to implement - just create the opposite function to `disableDates`. If you think this function could be useful, let me know - I could prepare a PR for you.  If not, just close the issue :)

Thanks 
Milan

**Comment by melloware** [comment]
Totally reasonable PrimeReact has this already called `enabledDates` : https://primereact.org/calendar/#api.Calendar.props.enabledDates

**Comment by melloware** [comment]
I assigned this to you.
