### ISSUE TITLE
SelectOneMenu: TabIndex is not used when SelectOneMenu is not editable

### ISSUE THREAD

**Issue by ra-ke** [primefaces/primefaces#11325]
### Describe the bug

When using the SelectOneMenu with the attribute `editable="false"` (the default setting) the rendered value for tab index is always 0 no matter which value is set in the xhtml.
With `editable="true"` the given value for tab index is used.

### Expected behavior

The given tab index value should be rendered when SelectOneMenu is used with `editable="false"`.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.4

### JSF implementation

Mojarra

### JSF version

3.0

### Java version

1.8

**Comment by melloware** [comment]
Yep this is a bug.
