### ISSUE TITLE
security vulnerability

### ISSUE THREAD

**Issue by martinopiniator** [primefaces/primefaces#11345]
### Describe the bug

[com.googlecode.owasp-java-html-sanitizer](https://mvnrepository.com/artifact/com.googlecode.owasp-java-html-sanitizer) » [owasp-java-html-sanitizer](https://mvnrepository.com/artifact/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer)1 vulnerability

https://mvnrepository.com/artifact/org.primefaces/primefaces/13.0.5

### PrimeFaces edition

None

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

**Comment by melloware** [comment]
It's not accurate for 2 reasons and you have nothing to worry about:

1. You can see in the Pom.xml it is marked `<scope>provided</scope>` which means it's an optional NOT a required dependency.

2. PF 13.0.5 is on the latest version of the affected JAR and awaiting a release of the non vulnerable version.
