### ISSUE TITLE
FileUpload does not delete files after confirming upload

### ISSUE THREAD

**Issue by romulometaprime** [primefaces/primefaces#11342]
### Describe the bug

I use the Payara 6 full application server, but when I upload a file using FileUpload it always creates a tmp file, however, it never deletes it. By default, such files in payara are created within the /payara/glassfish/domain/"mydomain"/generated/jsfp/"aplicationname"/ directory.

### Reproducer

            <p:fileUpload id="arqAnexo"
                          immediate="true"
                          listener="#{pessoaController.enviarAnexo}"
                          allowTypes="/(\.|\/)(gif|jpg|jpeg|png|pdf|xls|ods|odt|docx|xlsx|txt|rar|tar|gz|zip|xml|tiff|cdr)$/"
                          mode="advanced"
                          multiple="true"
                          sizeLimit="10000000" 
                          process="@this"
                          invalidFileMessage="Tipo de arquivo inválido, tipos permitidos (gif|jpg|jpeg|png|pdf|xls|ods|odt|docx|xlsx|txt|rar|tar|gz|zip|xml|tiff|cdr)"
                          invalidSizeMessage="Tamanho do arquivo maior que o permitido Máximo: 10 MB"
                          update=":messagePanel :formPessoaEdit:tabPessoaEdit:tabelaDocumentosAnexos :formPessoaEdit:tabPessoaEdit:panelDocumentosAnexos"
                          cancelLabel="Cancelar"
                          uploadLabel="Enviar"
                          label="Procurar"/>

### Expected behavior

Whenever the tmp is generated for each uploaded file, at the end of each confirmation it must be deleted, just as it was before in previous versions. In my case I was using primefaces 11, but with jsf 2.3, payara 5.2022. Now I migrated to payara 6.2023.12, jsf 4 and primefaces 13.0.5.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0.5

### Java version

17.0.8

### Browser(s)

Chrome Versão 120.0.6099.224 (Versão oficial) 64 bits

**Comment by tandraschko** [comment]
Isnt this something that payara should do?

**Comment by melloware** [comment]
Agreed with Thomas if you are using the `native` uploader this is a Payara bug as that is deferred to the Servlet code.

**Comment by romulometaprime** [comment]
Project follows:

[Primefaces-teste](https://github.com/rat/primefaces-test)

**Comment by romulometaprime** [comment]
Below is an example project with payara server:

[Primefaces-payara_test](https://github.com/romulometaprime/primefaces_teste_payara)

Here's a video of the problem.

https://github.com/primefaces/primefaces/assets/90965078/a662b92c-d3f0-4ad9-99b7-dc39799854c8

**Comment by melloware** [comment]
Jakarta 4 version outside of Payara working fine: 
[pf-11342.zip](https://github.com/primefaces/primefaces/files/14089095/pf-11342.zip)

No temp files left so please report the issue to Payara.
