### ISSUE TITLE
MenuItem: invoke pushComponentToEL/popComponentFromEL 

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#11358]
See https://stackoverflow.com/questions/77912348/primefaces-menuitem-component

`#{component}` is not working from menu items.

**Comment by melloware** [comment]
I think this was reported a long time ago: https://github.com/primefaces/primefaces/issues/1244 and we never got to the bottom of it.

**Comment by tandraschko** [comment]
yeah
should be quite a easy fix actually

**Comment by melloware** [comment]
@tandraschko can i assign this to you?  I took a look and couldn't quite figure out where the push and pop belongs?

**Comment by tandraschko** [comment]
i dont have time for it but wait 1 min, i can provide you a draft PR and someone can finish it

**Comment by melloware** [comment]
OK i will take a look and test it.
