### ISSUE TITLE
p:schedule: moment.js is missing

### ISSUE THREAD

**Issue by cghislai** [primefaces/primefaces#1135]
When using p:schedule with PF 5.2 or 5.3, I get 'moment is not defined' errors in console.
This prevent the select events to work properly.

Injecting the moment.js file manually solves this issue.

**Comment by sudheerj** [comment]
It is a part of schedule resources.It might be a corrupted jar so it won't be an issue.

**Comment by tandraschko** [comment]
Yup - already included.
