### ISSUE TITLE
Selenium: cannot set Firefox options through system settings

### ISSUE THREAD

**Issue by bvfalcon** [primefaces/primefaces#11354]
### Describe the bug

In PrimeFaces 12.0.0 Selenium [was updated](https://github.com/primefaces/primefaces/commit/bbd83b581704a0d59476765c6f7d4f9a77bf7f50) from version 3 to 4.
Selenium 4, between others, has one [important change for Firefox](https://github.com/SeleniumHQ/selenium/commit/ebd6bd7b4e3b64e8cad34038ef6380b19f340bcf): some options (browser path and profile to use) in previous version were set in constructor, but now must be set externally. During migration PF-code was not adapted to this special feature. For this reason in some cases (f.e. firefox.exe is not in PATH, non-standard profile must be used) usage of Firefox for testing can be impossible

### Expected behavior

[Additionally call](https://github.com/SeleniumHQ/selenium/blob/ebd6bd7b4e3b64e8cad34038ef6380b19f340bcf/java/client/test/org/openqa/selenium/firefox/FirefoxOptionsTest.java#L231) configureFromEnv() for FirefoxOptions()

### PrimeFaces edition

Community

### PrimeFaces version

 12.0.0

### JSF implementation

Mojarra

### JSF version

 2.2

### Java version

1.8

### Browser(s)

Firefox

**Comment by melloware** [comment]
I will put this in 13.0.6 as well
