### ISSUE TITLE
FileUpload: german umlauts not supported in filename

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11352]
```
    @Test
    void requireValidFilename_GermanUmlauts() {
        assertDoesNotThrow(() -> FileUploadUtils.requireValidFilename("someFileWithUmlautsßöäü.txt"));
    }
```

@melloware do you have any idea where "#FileUploadUtils#containsUnprintableCharacters" comes from?

**Comment by melloware** [comment]
I thought we already fixed this: https://github.com/primefaces/primefaces/issues/10436

**Comment by tandraschko** [comment]
Nope, FileUploadUtils#containsUnprintableCharacters allows not special characters / umlauts but its actually allowed

**Comment by tandraschko** [comment]
it was introduced by: https://github.com/primefaces/primefaces/commit/d9c939db9b1b020306a3f3a65291249ffe192660

**Comment by melloware** [comment]
Oh it was from the old OWASP `SafeFile` class.  That is what OWASP was recommending but it clearly is not right?

**Comment by melloware** [comment]
In 14 we removed SafeFile and just moved the checks but here is the old PF 13 SafeFile from OWASP: https://github.com/primefaces/primefaces/blob/13.X/primefaces/src/main/java/org/primefaces/shaded/owasp/SafeFile.java

**Comment by tandraschko** [comment]
its still there: 
https://github.com/vishank848/owasp-esapi-java/blob/master/src/main/java/org/owasp/esapi/SafeFile.java#L80

i have no idea why they do this

**Comment by tandraschko** [comment]
ok
when we upload a file, we validate for invalid chars for the OS, where the application is hosted (different regex for linux and windows) and we also check for URL encoded characters (PERCENTS_PAT ?)

so why we need to filter the ASCII table? also e.g. japanese kanjis or german umlauts are not supported with this check but they are in UTF8.

**Comment by melloware** [comment]
yeah let's pull it out then?  Really it seems to be not well thought our or they only cared about USA 😄

**Comment by tandraschko** [comment]
yeah
also #requireValidFilePath doesnt seem complete? it allows invalid characters where requireValidFileName doesnt

**Comment by melloware** [comment]
i think its because paths have more characters allowed than Filenames?   like `:` is allowed in a path like `C:\Personal` but a colon is not allowed in a file name right?

**Comment by tandraschko** [comment]
@melloware do you have time to have a look for the tests and #requireValidFilePath?

for me its not understandable what exactly should be tested? 
e.g. if (!file.getCanonicalFile().toPath().startsWith(parentFile.getCanonicalFile().toPath())) 

is the method there to validate a realtive or absolute path? AbstractUploadedFile can be used with both, ImageCropper the same?

i really dont understand what should the method do TBH

**Comment by melloware** [comment]
Agreed there were a few issues in the past:

https://github.com/primefaces/primefaces/issues/3268

And the `canonicalFile` check is this issue: https://github.com/primefaces/primefaces/pull/9376

**Comment by tandraschko** [comment]
i dont have time to work on it, so here is another ticket: #11360

my PR doesnt introduce this, i just fixed the test for windows and it breaks now
