### ISSUE TITLE
FileUpload/ImageCropper: path validation incomplete / not well documented / erroneous tests

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11360]
Discussed in #11352

both tests and code are not well documentation, what actually should be validated

i disabled one test (it fails in windows) as it fails by design: it tries to validate that a path cant be absolute, but it doesnt fail
also it doesnt make sense to fail it as its completely valid to use `AbstractUploadedFile#write(D:/myFile.txt)`

See:
https://github.com/primefaces/primefaces/issues/3268
https://github.com/primefaces/primefaces/pull/9376
https://github.com/primefaces/primefaces/issues/11134

**Comment by melloware** [comment]
Add this issue as well which was the Windows `%20` issue: https://github.com/primefaces/primefaces/issues/11134
