### ISSUE TITLE
Showcase: CSV/Basic; number-example is broken

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#11363]
### Describe the bug

https://primefaces.org/showcase/ui/csv/basic.xhtml

Click "Non-Ajax" before any input
![image](https://github.com/primefaces/primefaces/assets/10461942/93d805b2-928b-4eb0-b6f3-5dbcf103c3bd)

Click "Non-Ajax" after typing eg 10 into "number"
![image](https://github.com/primefaces/primefaces/assets/10461942/22bd9544-3d04-42f2-9b31-a864a63a97db)

### PrimeFaces version

13.0.5 and master

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Edge 121

**Comment by melloware** [comment]
Why is there an underscore in the number is it using a Mask?

**Comment by melloware** [comment]
Fixed it the mask was wrong `"9[99]` when it should have just been `[99]`
