### ISSUE TITLE
Poll: adding `onactivated ` and `ondeactivated`

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#11372]
### Description

It would be very useful to be able to call JS functions or remoteCommand's the once when a poll is started or ended 

### Describe the solution you would like

adding onpollstart and onpollend parameters to p:poll to work just like oncomplete or onstart do

**Comment by melloware** [comment]
I think this should be easy to add let me look.

**Comment by tandraschko** [comment]
actually onStart / onComplete?

**Comment by melloware** [comment]
yeah but that fires on every POLL.  He wants a JS callback when the poller is started and when its stopped not for each individual Poll call.

**Comment by tandraschko** [comment]
i would then not call it start/end, better enabled/disabled or activated/deactivated

**Comment by melloware** [comment]
`onactivated` and `ondeactivated` I like.
