### ISSUE TITLE
StaticMessage: support severity "success"

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#11375]
### Description

It now shows the component unstyled.

### Describe the solution you would like

Show in green with checkmark icon.

### Additional context

Maybe throw an exception if the severity is not supported.

**Comment by tandraschko** [comment]
currently there is no success severity in JSF

**Comment by tandraschko** [comment]
see https://github.com/jakartaee/faces/issues/1592

**Comment by jepsar** [comment]
Yeah, but you can use any string in this component. It's not restricted to FacesMessages.

**Comment by melloware** [comment]
we could add it just for static message since its just a string. Plus I can update the themes with the success colors from PrimeReact as it does have Success style.

**Comment by tandraschko** [comment]
+1 to update the theme

propably we will support SUCCESS quite early for other components, when 5.0 is on the road
