### ISSUE TITLE
ImmutableSaveState missing in 13.0.x

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11383]
its a API (org.primefaces.components.api) and one of my customer uses it
it was available in 13.0.0 but not in 13.0.x anymore, we have to reintroduce it in 13.0.x and add it to the changelog for 14.x

**Comment by melloware** [comment]
Sorry about that I will add it back in 13.0.6

**Comment by tandraschko** [comment]
no problem :) we just need to be a bit more carefully in future

**Comment by melloware** [comment]
I added a 14.0.0 Migration guide note about the removal and a link to where to copy the code from as well.
