### ISSUE TITLE
OverlayPanel: Infinite loop on AJAX update

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#11385]
### Describe the bug

When setting `unselectable="false"` for a `SelectOneButton`, it is no longer possible to select any value other than the initial one. This problem occurred with PF 13.0.4.

HINT:
Originally, I noticed a problem in a customer's application after updating to PF13.0.5 (to fix a `DatePicker` issue). When I clicked on a `SelectOneButton` to switch from a content with an `OverlayPanel` to a different content, the following JavaScript error popped up:

```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at I (jquery.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:2:7521)
    at I.matches (jquery.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:2:11218)
    at ce.filter (jquery.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:2:21673)
    at ce.fn.<computed> [as children] (jquery.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:2:24687)
    at Object.removeModal (core.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:81:254)
    at d.destroy (core.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:102:404)
    at d.destroy (core.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:96:383)
    at d.destroy (components.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:673:357)
    at d.destroy (core.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:96:383)
```

After stripping down the code, I found that the (dynamic) `OverlayPanel` was causing the problems. However, I had no idea where to search for the source of this bug. Therefore, I created this reproducer to ask for help. I then noticed that the `SelectOneButton` also does not work in the reproducer. I switched back to PF13.0.3, which I had also used in the customer's application before, and everything works as expected.

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/14154531/primefaces-test-master.zip)

### Expected behavior

Switching from 'A' to 'B' and back should work, and the content should be updated accordingly.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8.0_202-b08

### Browser(s)

Chromium 121.0.6167.85, Firefox 115.7.0esr

**Comment by melloware** [comment]
I will take a look but my only thought is it might be this: https://github.com/primefaces/primefaces/issues/5710

So you are saying 13.0.4 doesn't work but 13.0.3 does?  Or is it 13.0.5 and you went back to 13.0.3?  Just trying to narrow down when the issue exactly started.

**Comment by melloware** [comment]
Ok looking at 13.0.4 release notes there is not a lot there related to overlaypanel or selectonebutton. I will investigate with your reproducer.

**Comment by ltlBeBoy** [comment]
> So you are saying 13.0.4 doesn't work but 13.0.3 does? Or is it 13.0.5 and you went back to 13.0.3? Just trying to narrow down when the issue exactly started.

13.0.3 works, 13.0.4 and 13.0.5 not.

**Comment by melloware** [comment]
Ok thanks will let you know what I find out.

**Comment by melloware** [comment]
OK I got to the bottom of it.

13.0.3 = works
13.0.4 = works
13.0.5 = fails!

It was issue https://github.com/primefaces/primefaces/issues/5710 that causes this error and it is because in your scenario unlike all the others i tested you nested your `OverlayPanel` inside its target DOM.

```xml
 <h:panelGroup id="bbPnl">
    <p:overlayPanel cache="false"  dynamic="true" for="bbPnl">
           <i>Hint</i>
    </p:overlayPanel>
</h:panelGroup>
```

All of my use cases were the overlayPanel was outside of its Target DOM.

```xml
 <h:panelGroup id="bbPnl">

</h:panelGroup>

<p:overlayPanel cache="false"  dynamic="true" for="bbPnl">
       <i>Hint</i>
</p:overlayPanel>
```

So when the `target` was removed from the DOM i was detroying the overlay panel not checking whether the overlaypanel already resided inside its target to be destroyed.

MonkeyPatch:
```js
if (PrimeFaces.widget.OverlayPanel) {
    PrimeFaces.widget.OverlayPanel.prototype.bindTargetEvents = function() {
        var $this = this;

        //mark target and descandants of target as a trigger for a primefaces overlay
        this.target.data('primefaces-overlay-target', this.id).find('*').data('primefaces-overlay-target', this.id);

        //show and hide events for target
        if (this.cfg.showEvent === this.cfg.hideEvent) {
            var event = this.cfg.showEvent;

            this.target.on(event, function(e) {
                $this.toggle();
            });
        } else {
            var showEvent = this.cfg.showEvent + '.ui-overlaypanel',
                hideEvent = this.cfg.hideEvent + '.ui-overlaypanel';

            this.target.off(showEvent + ' ' + hideEvent).on(showEvent, function(e) {
                    if (!$this.isVisible()) {
                        $this.show();
                        if (showEvent === 'contextmenu.ui-overlaypanel') {
                            e.preventDefault();
                        }
                    }
                })
                .on(hideEvent, function(e) {
                    clearTimeout($this.showTimeout);
                    if ($this.isVisible()) {
                        // GitHub #8546
                        if (!$this.isAutoHide() && $(e.relatedTarget).is('div.ui-overlaypanel-content')) {
                            $this.allowHide = false;
                            return;
                        }

                        $this.hide();
                    }
                });
        }

        $this.target.off('keydown.ui-overlaypanel keyup.ui-overlaypanel')
            .on('keydown.ui-overlaypanel', PrimeFaces.utils.blockEnterKey)
            .on('keyup.ui-overlaypanel', function(e) {
                if (e.key === 'Enter') {
                    $this.toggle();
                    e.preventDefault();
                }
            });

        this.bindAutoHide();

        // GitHub #5710 Helper to destroy overlay if its target is destroyed
        $this.target.off('remove.overlay').on('remove.overlay', function() {
            // only destroy the overlay if it lives outside of the target
            if (!$.contains($this.target[0], $this.jq[0])) {
                $this.destroy();
            }
        });
    }
};
```

**Comment by ltlBeBoy** [comment]
Great news, thank you very much! I will test tomorrow morning.
But you had no problems with the `SelectOneButton`? It did not work for me with 13.0.4 and 13.0.5 in this reproducer.

**Comment by melloware** [comment]
Hmm no I had no issue with your reproducer.

**Comment by ltlBeBoy** [comment]
I can confirm that the monkey patch fixes the problem with the `OverlayPanel` in PF version 13.0.5. Thanks a lot for that fast support! It helps me greatly in meeting the timeline.

Regarding the reproducer:
I started the default environment via `mvn jetty:run` and used PF version 13.0.5. I can confirm that there is no issue with the `SelectOneButton` when using the _Chromium_ browser. However, when I open it with _Firefox_, it does not work with either PF version 13.0.5 or 13.0.4. It only works with _Firefox_ when I set the PF version to 13.0.3.

**Comment by ltlBeBoy** [comment]
OK, looks like only _Firefox_ version 115.7.0esr on Debian Linux 12.5 has a problem. On Windows 10 with _Firefox_ version 122.0 the `SelectOneButton` works fine with all PF versions.
Also working with _Firefox_ version 122.0.1 on Android 12.

**Comment by melloware** [comment]
I tested on Chrome and Firefox in Windows 11 without issue so it must be isolated to that Linux Firefox.  Have you tried updating to the latest Firefox i see you are on 115?
