### ISSUE TITLE
DataView: hide DataView header when only <p:dataViewGridItem/> or <p:dataViewListItem/> is defined

### ISSUE THREAD

**Issue by Sun8642** [primefaces/primefaces#11389]
### Description

The DataView component always displays buttons allowing the user to display data in list or grid form, but if data can only be displayed in list or grid form, a button remains displayed (which is useless).

### Describe the solution you would like

Either hide the DataView header when only <p:dataViewGridItem/> or <p:dataViewListItem/> is defined, or add an option to the component to hide the buttons/header.

**Comment by melloware** [comment]
I made this a bug.  The logic was already there is was just incorrect.
