### ISSUE TITLE
Internationalization for "Today" button in datePicker not working

### ISSUE THREAD

**Issue by piotrstawinski** [primefaces/primefaces#11393]
### Describe the bug

Internationalization does not work for the current date button in the datePicker component. Other lables defined in java script in PrimeFaces.locales section work correctly. 

### Reproducer

1. In the PrimeFaces.locales section for internationalization change property 'today' and 'currentText' to any value e.g. 'ABC'. 
2. Refresh your application
3. In the button bar of the datePicker component should be a button with label 'ABC', but there is a button with 'Now' label. 

### Expected behavior

In the button bar of the datePicker component should be a button with label 'ABC'. 

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8_381

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/issues/11279

**Comment by piotrstawinski** [comment]
Thanks, it's working :)

**Comment by melloware** [comment]
No problem!
