### ISSUE TITLE
Column: rendered attribute not working

### ISSUE THREAD

**Issue by piotrstawinski** [primefaces/primefaces#11399]
### Describe the bug

I have the following code: 

```html
<p:panelGrid>
	<p:row>
		<p:column rendered="false" style="border: 1px solid red">AAA</p:column>
		<p:column style="border: 1px solid red">BBB</p:column>
		<p:column style="border: 1px solid red">CCC</p:column>
	</p:row>
</p:panelGrid>
``` 
Unfortunately, the first column with the word 'AAA' is still visible. The 'AAA' text is hidden, but the column is not. In PF 12.0.5 the column was also hidden.

### Reproducer

1. Paste the following code: 
```html
<p:panelGrid>
	<p:row>
		<p:column rendered="false" style="border: 1px solid red">AAA</p:column>
		<p:column style="border: 1px solid red">BBB</p:column>
		<p:column style="border: 1px solid red">CCC</p:column>
	</p:row>
</p:panelGrid>
``` 
2. Watch that first column is still visible (text is hidden). 

### Expected behavior

Element p:column with attribute rendered="false" sholud be hidden. 

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8_381

**Comment by melloware** [comment]
I can't reproduce.

```xml
<p:panelGrid columns="0" layout="tabular">
	<p:row>
		<p:column rendered="false" style="border: 1px solid red">AAA</p:column>
		<p:column style="border: 1px solid red">BBB</p:column>
		<p:column style="border: 1px solid red">CCC</p:column>
	</p:row>
</p:panelGrid>
```

Works fine for me and the first column is NOT rendered. Reproducer: 
[pf-11399.zip](https://github.com/primefaces/primefaces/files/14194442/pf-11399.zip)

Run `mvn clean jetty:run`

**Comment by piotrstawinski** [comment]
Thank you very much for solution
That was very important: <p:panelGrid **columns="0" layout="tabular"**>
