### ISSUE TITLE
SelectOneMenu support for Alt-gr, Caps-Lock and Windows Keys

### ISSUE THREAD

**Issue by zszepe** [primefaces/primefaces#114]
According to the original issue on Google Code, this bug is still present:
https://code.google.com/p/primefaces/issues/detail?id=7892

"SHIFT, ALT and CTRL are good now: No reaction in selectOneMenu
The selectOneMenu still reacts falsely to "Alt-Gr" and "CAPS-LOCK" and the "WINDOWS/Super". Maybe this can be reopened and fixed once for all."

**Comment by cagataycivici** [comment]
What is super key? I'm a Mac user :)

**Comment by zsoltii** [comment]
Windows key on the keyboard :)

Same effect when you press function keys (F1, F2, etc..). You can test it on showcase: http://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

**Comment by cagataycivici** [comment]
@mertsincan You've worked on this before, can you comment?
