### ISSUE TITLE
OverlayPanel won't show when attached to a CommandButton

### ISSUE THREAD

**Issue by sehaas** [primefaces/primefaces#11409]
### Describe the bug

The fix in #11244 causes problems with an OverlayPanel attached to a CommandButton. The panel will be destroyed and isn't rendered any more, resulting in a JS error like: `Widget for 'xxxx' not available!`

The fix in #11387 does not fix this behavior.

### Reproducer

Not working examples:
```xml
<p:commandButton id="btn" value="Open" />
<p:overlayPanel for="btn" dynamic="true">
  <i>Hint</i>
</p:overlayPanel>
```
```xml
<h:panelGroup id="grp">
  <p:commandButton id="btn" value="Open" />
  <p:overlayPanel for="grp" dynamic="true">
    <i>Hint</i>
  </p:overlayPanel>
</h:panelGroup>
```
Partially working example:
```xml
<h:panelGroup id="grp">
  Working on Text
  <p:commandButton id="btn" value="Not working on button" />
  <p:overlayPanel for="grp" dynamic="true">
    <i>Hint</i>
  </p:overlayPanel>
</h:panelGroup>
```

Workaround, updating the wrapper:
```xml
<h:panelGroup id="wrp">
  <p:commandButton id="btn" value="Open" update="wrp"/>
  <p:overlayPanel for="btn" dynamic="true">
    <i>Hint</i>
  </p:overlayPanel>
</h:panelGroup>
```

### Expected behavior

The minimal example was working in 13.0.4 and should work again.
```xml
<p:commandButton id="btn" value="Open" />
<p:overlayPanel for="btn" dynamic="true">
  <i>Hint</i>
</p:overlayPanel>
```

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

All

### JSF version

2.3.21

### Java version

17.0.10

**Comment by sehaas** [comment]
Works for me.

While refactoring our code for the workaround I discovered another fix/workaround:
If the CommandButton has the attribute `type="button"` the overlay still works.

**Comment by melloware** [comment]
OK for 14.0.0 I added a new property and for 13.0.6 i will remove this entirely and just leave it with the the way it always worked even with the bug.

**Comment by melloware** [comment]
Original behavior has been restored.
