### ISSUE TITLE
panelMenu: when the panelMenu is create programmatically expand status of the menu items are not saved if statefulGlobal is set to true

### ISSUE THREAD

**Issue by Suli-88** [primefaces/primefaces#11403]
### Describe the bug

After migrating our code from Primefaces 8 to Primefaces 13 we have the issue that the sub menus do not keep the expand status that is produced by the user. When the user wants to have a sub menu expanded,  which is initially not expanded, this sub menu will collapse after clicking on any item in the menu. We set the property statefulGlobal to true, but this did not help.

We create the panelMenu programmatically. 

statefulGlobal works as expected fine if the menu items are created in xhtml file.

### Reproducer

1. use the following code
`<p:panelMenu id="client-menu" model="#{clientMenu.mainMenu}" statefulGlobal="true" toggleable="true"/>`

```
@ManagedBean(name = "clientMenu")
@ViewScoped
public class ClientMenu{
    private MenuModel mainMenu;
    @PostConstruct
    public void init() {
      mainMenu = new DefaultMenuModel();
      addMenuGroup(); 
    }

    private void addMenuGroup() {
        final DefaultSubMenu subMenu1= DefaultSubMenu.builder().expanded(true).label("label1").build();
        final DefaultMenuItem newChildElement1 =
                DefaultMenuItem.builder().outcome(MenuEntries.FIRST_SUB_MENU_PAGE).value("menuChild1").build();
        subMenu1.getElements().add(newChildElement1);
        mainMenu.getElements().add(subMenu1);

       final DefaultSubMenu subMenu2= DefaultSubMenu.builder().expanded(false).label("label2").build();
        final DefaultMenuItem newChildElement2=
                DefaultMenuItem.builder().outcome(MenuEntries.SECOND_SUB_MENU_PAGE).value("menuChild2").build();
        subMenu2.getElements().add(newChildElement2);
        mainMenu.getElements().add(subMenu2);     
    }

    public MenuModel getMainMenu() {
        return mainMenu;
    }
}
```
2. collapse the first sub menu (subMenu1)
3. expand the second sub menu (subMenu2)
4. click on the child of  the second sub menu

### Expected behavior

expand state is saved: subMenu1 is not expanded.

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

All

### JSF version

2.2

### Java version

8

**Comment by melloware** [comment]
Here is a fixed reproducer:
[pf-11403.zip](https://github.com/primefaces/primefaces/files/14215142/pf-11403.zip)

We changed it to autogenerate unique id's now where in PF8 it did not so every time you refresh your page you are getting unique ids.

To fix it simply give your MenuItem's proper Id's instead of auto-generating.

```java
    private void addMenuGroup() {
        final DefaultSubMenu subMenu1 = DefaultSubMenu.builder().expanded(true).label("label1").id("submenu1").build();
        final DefaultMenuItem newChildElement1 = DefaultMenuItem.builder()
                .id("menu1")
                .url("https://github.com/primefaces/primefaces/issues/")
                .value("GitHub").build();
        subMenu1.getElements().add(newChildElement1);
        mainMenu.getElements().add(subMenu1);

        final DefaultSubMenu subMenu2 = DefaultSubMenu.builder().expanded(false).label("label2").id("submenu2").build();
        final DefaultMenuItem newChildElement2 = DefaultMenuItem.builder()
                .id("menu1")
                .url("http://www.primefaces.org/showcase/")
                .value("Showcase").build();
        subMenu2.getElements().add(newChildElement2);
        mainMenu.getElements().add(subMenu2);
    }
```
