### ISSUE TITLE
ProgressBar: Support severities

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#11404]
### Description

I started using ProgressBar in a new project and the client came up with the idea of different colors depending on the ProgressBar value.

### Describe the solution you would like

Possible mockup:
![image](https://github.com/primefaces/primefaces/assets/18428155/9ad07f28-5ca7-4597-9efa-8cac40928c8f)

Example usage:
```xhtml
<p:progressBar value="#{bean.value}" severity="#{bean.value eq 100 ? 'success' : 'warning'}"/>
```

**Comment by NicolaIsotta** [comment]
I saw [Tag](https://www.primefaces.org/showcase/ui/misc/tag.xhtml) and [Badge](https://www.primefaces.org/showcase/ui/misc/badge.xhtml) are using `severity` as well

**Comment by melloware** [comment]
So I agree with @tandraschko that it can easily be done with StyleClass but I do like the consistency of Tag and Badge with severities and I have needed similar functionality with ProgressBar in the past where if its if its a certain percentage is "success" color but below a certain percentage its "error" color progressbar.    

That way its consistent with the colors of your Theme without me writing custom `style=""` code to grab the right color for the theme for those severities?

@NicolaIsotta were you interested in us doing a PR to review?

**Comment by NicolaIsotta** [comment]
Yes. I can work on this, too.

**Comment by tandraschko** [comment]
if badge also supports, then +1 to support this here too
