### ISSUE TITLE
Chips: Paste (Comma separated) is not working.

### ISSUE THREAD

**Issue by HSnicolascerrejon** [primefaces/primefaces#11407]
### Describe the bug

Chips Paste (Comma separated) is not working. You can check it in the showcase.

### Reproducer

Paste
`a,b,c`
only one element is added: "a,b,c"

### Expected behavior

Three elements are added: "a","b","c"

### PrimeFaces edition

Community

### PrimeFaces version

13.0.4

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

-

### Java version

17

**Comment by melloware** [comment]
Thanks for reporting it broke with this ticket: #9615

**Comment by HSnicolascerrejon** [comment]
Hi! I've integrated 14.0.0-RC2 and the bug still persists. Will the fix be added to the final release?

Thxs a lot, regards!

**Comment by melloware** [comment]
@HSnicolascerrejon are you sure this fix was in 14.0.0-RC2.  
Can you provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project showing it is not working?

**Comment by HSnicolascerrejon** [comment]
Hi again,

I have not been able to reproduce the problem using the Test. It's a bit strange, I have two web applications, which are practically the same, and in one it does not have the expected behavior, but in the other it does ¯\_(ツ)_/¯ . I haven't been able to find out why. At least where I really need it is where it is working.

On the other hand, I attach the Test project with a couple of "defects" that I have seen. The first is that if you do not explicitly put the 'separator=","' it does not take it (when according to the Tag documentation, it is the default value), it has no major importance, it is specified and it already works.

It also happens that if you add Listeners, they are called once for each element added, and the first call only carries the first element and the rest all. This has given me problems and I have had to add a 'delay="100"' to avoid the problem. It can be seen in the console:

[a]
[a, b, c, d, e, f, g, h]
[a, b, c, d, e, f, g, h]
[a, b, c, d, e, f, g, h]
[a, b, c, d, e, f, g, h]
[a, b, c, d, e, f, g, h]
[a, b, c, d, e, f, g, h]
[a, b, c, d, e, f, g, h]

I have put the latest to test 14.0.0-RC3

Thank you so much!!

[primefaces-test-master-chips.zip](https://github.com/primefaces/primefaces/files/15033259/primefaces-test-master-chips.zip)

**Comment by melloware** [comment]
@HSnicolascerrejon can you open a new issue please so we don't pollute this one.
