### ISSUE TITLE
PanelGrid - wrong default column size

### ISSUE THREAD

**Issue by piotrstawinski** [primefaces/primefaces#11400]
### Describe the bug

I have the following code: 
```html
<p:panelGrid columns="2">
     <h:outputText value="short left" />
     <h:outputText value="short right" />

     <h:outputText value="loooooooooooooooooooooooooooooooong left" />
     <h:outputText value="loooooooooooooooooooooooooooooooong right" />

     <h:outputText value="meeeeeeeeedium left" />
     <h:outputText value="meeeeeeeeedium right" />
 </p:panelGrid>
``` 

The width of the left column of the panelGrid component is approximately 50% of the screen width. In PF 12.0.5 and earlier versions, in the panelGrid component, the left column width was always automatically set to the longest text in the left column.
Setting a static width for the left column is not sufficient, because the values appearing there can be dynamic.

### Reproducer

1. Past the following code: 
```html
<p:panelGrid columns="2">
     <h:outputText value="short left" />
     <h:outputText value="short right" />

     <h:outputText value="loooooooooooooooooooooooooooooooong left" />
     <h:outputText value="loooooooooooooooooooooooooooooooong right" />

     <h:outputText value="meeeeeeeeedium left" />
     <h:outputText value="meeeeeeeeedium right" />
 </p:panelGrid>
``` 

2. Watch, that c has approximately 50% of the screen width

### Expected behavior

The width of the left column in panelGrid should be determined automatically based on the longest string in this column.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8_381

**Comment by stolp** [comment]
Please have a look at the [Migration Guide](https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0).

The default behavior for `p:panelGrid` has changed in V13. To fall back to legacy behavior set ` layout="tabular"`.

**Comment by piotrstawinski** [comment]
Thank you very much for help :)
