### ISSUE TITLE
selectOneMenu: filter option breaks the component when screen width is too small and option too long

### ISSUE THREAD

**Issue by Sun8642** [primefaces/primefaces#11414]
### Describe the bug

When you are using a selectOneMen, having the option 'filter="true"', having a text too long in a selectItem(s) and when the screen width is too small (smaller than the text of the longest text option of your items),  if you click on the selctOneMenu, the menu will open and then close instantly.

### Reproducer

1. Go to http://localhost:8080/primefaces-test/
2. Set the dimension of your browser to iphone SE dimensions (375 x 667)
3. Click on the second selectOneMenu (first selectOneMenu doesn't use the filter option and has no problem)

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/14222595/primefaces-test.zip)

### Expected behavior

The selectOneMenu should not close instantly when you click on it.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17.0.6

### Browser(s)

All

**Comment by melloware** [comment]
From your post on Discord is your issue fixed if you use `ui-fluid`?

**Comment by Sun8642** [comment]
No, it doesn't change anything.

**Comment by melloware** [comment]
Hmmm I am testing on 14.0.0-SNAPSHOT and the panel does not close it works fine?

![image](https://github.com/primefaces/primefaces/assets/4399574/dd4510c4-6146-43d2-9524-8382b1e226da)

You are saying yours closes instantly?

**Comment by melloware** [comment]
Try this reproducer:
[pf-11414.zip](https://github.com/primefaces/primefaces/files/14224270/pf-11414.zip)

We already have a hook to disable this behavior if you don't want it.

```xml
<script>PrimeFaces.hideOverlaysOnViewportChange = false;</script>
```

**Comment by melloware** [comment]
@Sun8642 did you get a chance to try this?

**Comment by Sun8642** [comment]
Not yet, I'm ill, I'll try as soon as possible

**Comment by Sun8642** [comment]
I tried it, it works fine, thank you.

**Comment by brunoroland** [comment]
This workaround causes another problem.

In the PrimeFaces showcase, when I click on the SelectOneMenu, I see the list of items.
If I then click outside of this list, the list disappears (which is the expected behavior).

However, when I do the same thing in my application (where i use the script `<script>PrimeFaces.hideOverlaysOnViewportChange = false;</script>`) , clicking outside of the SelectOneMenu does not close the list — it remains visible. I have to click again on the SelectOneMenu to make it disappear!

**Comment by melloware** [comment]
@brunoroland try this reproducer with 15.0.13.

[pf-11414.zip](https://github.com/user-attachments/files/25769443/pf-11414.zip)

unzip and run `mvn clean jetty:run`.  I can see that I can click outside the selectone and it closes it.

**Comment by brunoroland** [comment]
Yes, it's fixed in PF v. 15.0.13 (i was in v. 15.0.8)
