### ISSUE TITLE
FavIcon Issue: if we route to /store, it is showing react fav Icon

### ISSUE THREAD

**Issue by sivareddyuppathi** [primefaces/primefaces#11418]
### Describe the bug

<img width="641" alt="Screenshot 2024-02-10 180300" src="https://github.com/primefaces/primefaces/assets/43075243/1e36868f-71b9-434f-8f8f-4b895efb4933">

https://www.primefaces.org/store/

If we observre active tab favicon it is showing react favicon

it should be prime faces default facicon

**I'm very much intrested in opensource, help me in fixing the bug**

Please assign this to me 

I traied but unable to figure out where to fix. Please help me to fix this.

### Reproducer

https://www.primefaces.org/store/

### Expected behavior

it should be prime faces default facicon

### PrimeFaces edition

None

### PrimeFaces version

13.0.5

### JSF implementation

MyFaces

### JSF version

1,2

### Java version

1.8

### Browser(s)

Chrome

**Comment by melloware** [comment]
@sivareddyuppathi the PrimeStore is a private website maintained by PrimeTek.  This is the Open Source Community tracker for PrimeFaces so there is no code you can fix. you can try reporting it to PrimeTek on Discord channel or in discussions: https://github.com/orgs/primefaces/discussions
