### ISSUE TITLE
NPE for some properties if set via UIComponentBase#getAttributes()#set()

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#1141]
As the title already says, some properties of PrimeFaces components throw an NPE if the property is set using the AttributesMap instead of directly using the setter. The problem occurs if the property has a primitive type and the getter uses `null` as its default value (the AttributeMap will always invoke the getter. Otherwise it can't return the old value, as required by the Map interface).

**Example**

```
// RadioButton.java
public int getItemIndex() {
    return (java.lang.Integer) getStateHelper().eval(PropertyKeys.itemIndex, null); // NPE
}
public void setItemIndex(int _itemIndex) {
    getStateHelper().put(PropertyKeys.itemIndex, _itemIndex);
}
```

**Comment by tandraschko** [comment]
would be great if you could post all affected properties.
