### ISSUE TITLE
Message: tooltip is not shown in 14.0.0-RC1

### ISSUE THREAD

**Issue by js361014** [primefaces/primefaces#11429]
### Describe the bug

Message in tooltip display mode is not shown.

### Reproducer

1.Run 
```
wget https://github.com/primefaces/primefaces/archive/refs/tags/14.0.0-RC1.tar.gz -O- | tar -x -z -C /tmp/ 
cd /tmp/primefaces-14.0.0-RC1/
mvn clean install 
cd primefaces-showcase
mvn -Ddev
```
2.Open http://localhost:8080/showcase/ui/message/messages.xhtml
3.Click Submit button

### Expected behavior

Tooltip should be shown - it works on https://www.primefaces.org/showcase/ui/message/messages.xhtml

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-RC1

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
it might be fixed.  I just tried 14.0.0 in master and it looks like it is working..

![image](https://github.com/primefaces/primefaces/assets/4399574/340b956c-5d74-4672-a7c3-2f75ed6b0a77)

**Comment by melloware** [comment]
You mean your screenshot does not match mine above?

**Comment by js361014** [comment]
> You mean your screenshot does not match mine above?

Yes. Moreover, I tried to debug it and I see that the problem is that message is rendered into
```
<div id="j_id_7r:j_id_85" role="alert" aria-atomic="true" aria-live="polite" data-display="tooltip" data-target="j_id_7r:tt" data-redisplay="true" class="ui-message ui-helper-hidden ui-message-error ui-widget ui-corner-all"><div><span class="ui-message-error-icon"></span><span class="ui-message-error-summary" id="j_id_7r:j_id_85_error-summary">Tooltip: Validation Error: Value is required.</span></div></div>
```
but should be 
```
<div id="j_id_7r:j_id_85" role="alert" aria-atomic="true" aria-live="polite" data-display="tooltip" data-target="j_id_7r:tt" data-redisplay="true" class="ui-message ui-helper-hidden ui-message-error ui-widget ui-corner-all"><div><span class="ui-message-error-icon"></span><span class="ui-message-error-detail" id="j_id_7r:j_id_85_error-detail">Tooltip: Validation Error: Value is required.</span></div></div>
``` 
**error-summary** should be **error-detail** - it is used here https://github.com/primefaces/primefaces/blob/5b4ead8cc379ac86e982fbe6c6246e92640b0a8b/primefaces/src/main/resources/META-INF/resources/primefaces/message/message.js#L23

**Comment by melloware** [comment]
Why is it showing up for me?

**Comment by melloware** [comment]
@js361014 did you want to submit a PR?

**Comment by melloware** [comment]
OK yep I see if now. I think i needed to CTRL+F5 my browser cache for the JS when switching back and forth between 13 and 14.

**Comment by jepsar** [comment]
Isn't the version suffixed to the resource URL?

**Comment by melloware** [comment]
@jepsar yeah I don't know what was going on but it was like it was cached.   Also @js361014 i think it might be something else because the message.js code has not changed since 2021.

**Comment by melloware** [comment]
OK PR submitted.

My only thought was this behavior changed with this fix: https://github.com/primefaces/primefaces/issues/10281

I am looking through other 14.0.0 message related changes and nothing stands out

**Comment by js361014** [comment]
@melloware Maybe it was changed in https://github.com/primefaces/primefaces/pull/11157/. Are you sure the change should be done in  `message.js` but not in `MessageRenderer.java`?

**Comment by melloware** [comment]
@js361014 i am looking at that PR but from eyeballing it i don't see where its sending the summary instead of the detail?

**Comment by js361014** [comment]
> @js361014 i am looking at that PR but from eyeballing it i don't see where its sending the summary instead of the detail?

I just guessed that I may be done here but I didn't dig into it.
