### ISSUE TITLE
New Primefaces 12 upgrade caused menu panel to disappear quickly 

### ISSUE THREAD

**Issue by JotaLFC** [primefaces/primefaces#11425]
### Describe the bug

 After menu item of the Action menu panel was clicked, it opened a dialog. After closing out of a dialog and clicking on the Action link to open the menu panel again, the menu panel disappeared quickly after the first click. After the second click then it stayed open. Is anybody else having this issue?

### Reproducer

 <p:menuitem        icon="fas fa-save"
                                actionListener="#{someClass.method}"
                                process="@this"
                                update="@none"
                                onstart="PF('uiBlocker').show()"
                                oncomplete="PF('uiBlocker').hide()"                               
                                ajax="true" />

### Expected behavior

After clicking on Action link to open up an action menu panel again, the panel should not disappear right away but stay open.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Sentinel

### JSF implementation

All

### JSF version

2.3

### Java version

8

### Browser(s)

Chrome

**Comment by melloware** [comment]
If you are referring to `Sentinel` specifically type Menu Item then this is the community tracker and not for Premium related issues.  That is what the Templates Discussion is for: https://github.com/orgs/primefaces/discussions/categories/primefaces-templates
