### ISSUE TITLE
DatePicker: add hideOnRangeSelection property

### ISSUE THREAD

**Issue by DerIngo** [primefaces/primefaces#11424]
### Description

It determines whether Calendar/DatePicker is closed after selecting dates in rangeSelection mode.

This addon was implemented for primue calendar in 2022 by @tugcekucukoglu, see https://github.com/primefaces/primevue/issues/2684.

### Describe the solution you would like

The solution I would like would be the additional 'hideOnRangeSelection' attribute for the p:datePicker tag.

**Comment by melloware** [comment]
There is this request too around Range Selection: https://github.com/primefaces/primefaces/issues/10230

**Comment by melloware** [comment]
I will take this one.
