### ISSUE TITLE
Spring: support CRSF

### ISSUE THREAD

**Issue by amateurproof** [primefaces/primefaces#11426]
### Describe the bug

I have a demo application consisting of one form (dashboard.xhtml) which allows user to select a file and then add a row to a table. For this purpose, the form has two Primefaces File upload buttons, the first uses simple mode to load files, the second uses advanced mode.

![image](https://github.com/primefaces/primefaces/assets/159808928/4c1cbd83-6f88-42f3-ae6d-c34dcb4f6aca)

![image](https://github.com/primefaces/primefaces/assets/159808928/b3c54685-21ed-4238-9fee-e724a9060af7)

When CSRF (Cross-site request forgery) protection (http.csrf().disable(); in WebSecurityConfigurer) is disabled, both buttons work fine, but as soon as we Enable CSRF protection (by commenting out the line http.csrf().disable(); ) the simple mode button stops working, while advanced mode is still working correctly. I tried the native JSF file upload button, is working fine but I'm not able to customize it to looks and behave like primefaces button. I don't know if somebody can help me to finish my demo app.

This application is built with Maven and  JSF 2.3.14, Spring 5.3.27 and Primefaces 12.0.0. The source code is attached;

[UploadCsrf.zip](https://github.com/primefaces/primefaces/files/14241505/UploadCsrf.zip)

![image](https://github.com/primefaces/primefaces/assets/159808928/b4704a9f-a1fd-4ed4-b0a4-ecba2c42ce45)

![image](https://github.com/primefaces/primefaces/assets/159808928/06e649e1-d088-444c-b69f-dea3faca04c7)

![image](https://github.com/primefaces/primefaces/assets/159808928/14dc7d5e-8fe6-4031-a42e-4752c0266bd9)

### Expected behavior

What I need is to make simple mode buttons work  with and without CSRF as it is the case for advanced mode.

### PrimeFaces edition

None

### PrimeFaces version

12 and 13

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

1.8

**Comment by melloware** [comment]
I didn't look but is this code runnable?  Are there instructions for how to run it?

**Comment by amateurproof** [comment]
I don't know if this is enough, 
but As you can see below, application is a maven project built with Apache NetBeans IDE 18 and 
deployed on apache-tomcat-9.0.73.
![image](https://github.com/primefaces/primefaces/assets/159808928/efa8e1c2-52e6-4fdc-9139-42fc55c878e1)

From Netbeans, you just need to right click on the project and select “Run”.
![image](https://github.com/primefaces/primefaces/assets/159808928/cef0644f-3eeb-4a19-812c-ddb1a0b46d02)

![image](https://github.com/primefaces/primefaces/assets/159808928/cab582de-3c81-46c8-952c-66e3ce697f36)

To enable the CSRF, you have to comment the line “http.csrf().disable();” in com.demo.common.security. WebSecurityConfigurer
![image](https://github.com/primefaces/primefaces/assets/159808928/f4e558fe-c534-4475-a5cf-1c8d93d6169f)

The FormRenderer  “com.demo.common.security.FormWithCSRFRenderer” is used to add the _csrf token to each form. However, event without the renderer, the simple mode file upload button is not working once Spring CSRF is enable.

**Comment by tandraschko** [comment]
we always use some embedded maven servers, so we can just run without local tomcat installation e.g.

i commited a PR, this should work as long you dont rename the param in spring

**Comment by tandraschko** [comment]
please give the snapshot a try

**Comment by amateurproof** [comment]
Good evening,
please is Primefaces 13.0.6 fix the issue? if yes, how can I reference it in my Maven POM ?

**Comment by melloware** [comment]
you can try `13.0.6-SNAPSHOT` if you follow these instructions: https://github.com/primefaces/primefaces?tab=readme-ov-file#snapshot

**Comment by amateurproof** [comment]
thank you very much. it fix the issue

**Comment by melloware** [comment]
@tandraschko = 🦸🏻 👍🏻
