### ISSUE TITLE
inputTextarea: maxrows and maxcols

### ISSUE THREAD

**Issue by DerIngo** [primefaces/primefaces#11423]
### Description

In my application I have an inputTextarea to enter some data, that will be printed out on a piece of paper.
There is limited space on the paper, therefore I want to limit the inputTextarea to a specific amount of rows and cols, for example maximum 25 chars/cols and 5 lines/rows.

Currently you can set rows, cols and maxlength like this:
```
<p:inputTextarea rows="5" cols="25" maxlength="125" />
```
But this is just like an 'initial' value for the display size of the inputTextarea.
For example I could enter 125 rows with only one letter in it, or one row with 125 letters.

### Describe the solution you would like

The solution I would like would be additional 'maxrows' and 'maxcols' attributes for the p:inputTextarea tag, like the existing 'maxlenght' attribute.

**Comment by jepsar** [comment]
You can easily create your own validator taking care of this edge case.

**Comment by melloware** [comment]
Don't you just want `autoResize="false"` if you don't want the area to grow?

**Comment by DerIngo** [comment]
I guess, `autoResize="false"` would also be suitable.
