### ISSUE TITLE
SelectCheckboxMenu: Custom rendering broken when used as `DataTable` filter in a `ColumnGroup`

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#11421]
### Describe the bug

When a `SelectCheckboxMenu` with custom rendering is used as a `DataTable` filter, and the header of the table is specified within a `ColumnGroup`, then the rendering of the `SelectCheckboxMenu` is broken. The column with the selection labels is empty, and an additional column, which contains the value of the header facet, is rendered for each selection item.

![SelectCheckboxMenu-broken](https://github.com/primefaces/primefaces/assets/20644759/6f3eb020-b04d-4378-b4e7-14d72c7944e8)

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/14233689/primefaces-test-master.zip)

### Expected behavior

There should be just one column with the selection labels.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8.0_202-b08

### Browser(s)

Chromium 121.0.6167.85, Firefox 115.7.0esr

**Comment by melloware** [comment]
I think we have seen other issues like this in the past with rows and columns or TR TDs conflicting.

**Comment by melloware** [comment]
@ltlBeBoy are you debugging this?

**Comment by ltlBeBoy** [comment]
@melloware Yes, I will take a look. I have an idea...But I'm at the client's today and tomorrow to install a new software version.

**Comment by melloware** [comment]
Any update @ltlBeBoy  ?

**Comment by ltlBeBoy** [comment]
@melloware I found the source of the problem, but I have no clue how to fix it. The rendering mistake occurs while encoding the column of the `SelectCheckboxMenu` at `org.primefaces.component.column.ColumnRenderer#encodeEnd(FacesContext, UIComponent)`:

```
    public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
        Column column = (Column) component;
        String helperKey = (String) context.getAttributes().get(Constants.HELPER_RENDERER);

        if (helperKey != null) {
            HelperColumnRenderer renderer = RENDERERS.get(helperKey);

            if (renderer != null) {
                renderer.encode(context, column);
            }
        }
        else {
            renderChildren(context, column);
        }
    }
```

If the `SelectCheckboxMenu` is placed standalone in a form, then the `helperKey` is `null`, which is correct.
However, when it is included within  a `p:dataTable` that utilizes a `p:columnGroup` with `type="header"` for rendering the header, the `helperKey` is assigned `columnGroup`. Consequently, the column renderer incorrectly assumes it is rendering the column header of the data table.
Do you have an idea how to fix this issue?

**Comment by melloware** [comment]
@ltlBeBoy i have to research this. I just looked and that Helper Renderer code has been in there since 2014!

**Comment by melloware** [comment]
OK I figured it out.  2 PR's coming so the team can discuss.

**Comment by melloware** [comment]
Awesome I am just waiting on a response from the team on which solution they want me to implement then i will backport to 13.0.9
