### ISSUE TITLE
Support Spring CSRF?

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11422]
https://stackoverflow.com/questions/77981280/make-primefaces-file-upload-button-to-work-in-a-primefaces-spring-website-whe

Im not sure how spring exactly handles this but actually spring must add some hidden input to forms and we must collect it, same like viewStateId or clientWindowId.

maybe a spring user could check it, what exactly spring adds to the generated html?

**Comment by tandraschko** [comment]
propably the hidden input is called "_csrf": https://github.com/spring-projects/spring-security/blob/26372aaad11e35f98e9240e6b8b683b8caebc25c/web/src/main/java/org/springframework/security/web/reactive/result/view/CsrfRequestDataValueProcessor.java#L37

but i even wonder how they add it automatically? do they have a JSF module?

we would really need a sample project and/or rendered HTML

**Comment by melloware** [comment]
Knowing SPring Framework I am sure its all done with a Servlet Filter.  They do most things with Filters.

**Comment by melloware** [comment]
I will close this one the user posted their code in another ticket.
