### ISSUE TITLE
Showcase: move to JakartaEE (10)

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#11433]
### Description

Time has moved on. JakartaEE 9 was released back in 2020, 10 in 2022.
Showcase should present up-2-date examples. (A bit relative on the JSF-side of things, but nonetheless.)

### Describe the solution you would like

- [x] replace javax-packages with jakarta-packages (java-classes)
- [x] use new namespace (xhtml-files, faces-config.xml, ...)
- [x] use Mojarra 4 / MyFaces 4
- [x] Jetty
- [x] some more 3rd party dependencies

I´ll hope most of our work is done by https://www.jetbrains.com/guide/java/tutorials/migrating-javax-jakarta/use-migration-tool/.

**Comment by tandraschko** [comment]
+1

**Comment by melloware** [comment]
I did this for Quarkus Faces using OpenRewrite and it did 99% of the work in migrating!

**Comment by tandraschko** [comment]
we should also migrate docs then
