### ISSUE TITLE
MeterGauge: Update Migration Guide

### ISSUE THREAD

**Issue by amateurproof** [primefaces/primefaces#11436]
### Describe the bug

Good evening dear all,
While going through version 13 of PF, I'm not able to find the metergauge in the new Charts library indicated in the migration guide "[Migration guide 12.0.0 -> 13.0.0](https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0?id=migration-guide-1200-gt-1300)", I do not know if it was deliberately removed or it was placed elsewhere. and if it was deliberately removed, is there another alternative?

### PrimeFaces edition

None

### PrimeFaces version

13

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

1.8

**Comment by melloware** [comment]
Its there but needs to be more clear: https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0?id=deleted

basically jQuery Charts were removed https://github.com/primefaces/primefaces/issues/8773

**Comment by melloware** [comment]
I am updating the guide to say...

`Chart` (jqPlot) in favor of `Charts` (Chart.js). Legacy jqPlot charts such as `MeterGauge` were abandoned by the upstream project.

**Comment by amateurproof** [comment]
Thank you for your feedback and really impressed by your responsiveness
