### ISSUE TITLE
Additional text added to selectOneMenu ID within cellEditor in dataTable

### ISSUE THREAD

**Issue by fx89** [primefaces/primefaces#1143]
When using a selectOneMenu within the output facet of a cell editor in an editable data table with editMode="cell", an additional "_input" is added to the id of the generated "select" element. 

This may seem like a minor issue, but for those of us who are actually using these IDs in our application workflows it's a bit of a headache when it comes to debugging it. After all, the reason why we bother giving ids to these controls is so that we may use them whenever we can't use widget vars. 

Also, a little consistency would be nice :) 

I've prepared a sample project to demonstrate this behavior and I've uploaded it here:
https://app.box.com/s/sa4cqm8qbiynt9hid6k9ls81hzvsmq5f

See the attached picture "jsf-view.png":
![jsf-view](https://cloud.githubusercontent.com/assets/16502403/13012448/ea0ff08a-d1b3-11e5-865f-50b1b63ac177.png)

And also "html-result.png": 
![html-result](https://cloud.githubusercontent.com/assets/16502403/13012453/f57ab95a-d1b3-11e5-8ff3-01dd4a1f87ed.png)

Note the discrepancy between the IDs of the inputText and the selectOneMenu in the HTML result. Note that this discrepancy does not exist in the XHTML file.

**Comment by melloware** [comment]
This is intentional:
https://github.com/primefaces/primefaces/blob/2e846f7d4d2e6e0d94d4db6978f70a7326071ae1/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L186

Closing.
