### ISSUE TITLE
Client Validation: hidden inputs

### ISSUE THREAD

**Issue by AlessandroBori** [primefaces/primefaces#11449]
Hi everyone
i was peeking into client side validation functions about the way inputs are listed for validation if they are not visible.
following this function line

https://github.com/primefaces/primefaces/blob/1c1d516a3dd4daa72e86c79adf567e771b837524/primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js#L186

I assume input type hidden are always listed.
Is this correct or is it better to never consider these fields? p:InputNumber renders (for example) in two separate inputs, one of them is hidden

regards

**Comment by melloware** [comment]
Good point i notice the showcase example does not use any `<p:inputNumber>`

**Comment by melloware** [comment]
I just tested with InputNumber and CSV works fine.

```xml
                    <p:outputLabel for="number" value="Number:"/>
                    <p:inputNumber id="number" value="#{validationView.integer}">
                        <f:validateLength minimum="2" maximum="3"/>
                    </p:inputNumber>
                    <p:message for="number"/>
                    <h:outputText value="#{validationView.integer}"/>
```

![image](https://github.com/primefaces/primefaces/assets/4399574/4ce87fdf-66c0-4a69-93c0-b2265504666a)

**Comment by christophs78** [comment]
We also have a integration test for p:inputNumber:
https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/main/webapp/csv/csv001.xhtml#L49
https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/csv/Csv001Test.java#L74

What´s the reason for your question?
