### ISSUE TITLE
Docs: chart.md needs to be updated

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#11444]
### Describe the bug

In the migration doc for PF 14 (14_0_0.md), the following is stated:

## Deprecated
...
  * `<p:barChart>` is deprecated in favor of new `<p:chart>` component and will be removed in 15.0.0
  * `<p:pieChart>` is deprecated in favor of new `<p:chart>` component and will be removed in 15.0.0
  * `<p:radarChart>` is deprecated in favor of new `<p:chart>` component and will be removed in 15.0.0
  * `<p:lineChart>` is deprecated in favor of new `<p:chart>` component and will be removed in 15.0.0
  * `<p:donutChart>` is deprecated in favor of new `<p:chart>` component and will be removed in 15.0.0
  * `<p:polarAreaChart>` is deprecated in favor of new `<p:chart>` component and will be removed in 15.0.0
  * `<p:scatterChart>` is deprecated in favor of new `<p:chart>` component and will be removed in 15.0.0

but in the corresponding doc of the chart component (chart.md) only the deprecated usage is described. Would be great if this doc could be updated, too.

Many thanks in advance.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

3

### Java version

11

**Comment by melloware** [comment]
Maybe you are looking at the wrong chart.md here is what I see: https://primefaces.github.io/primefaces/14_0_0/#/components/chart?id=chart

**Comment by tuerker** [comment]
@melloware thanks for the hint. actually, i was looking at charts.md. 
https://primefaces.github.io/primefaces/14_0_0/#/components/charts
sorry for the confusing.
