### ISSUE TITLE
Dashboard: with dynamic panels

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#11447]
### Description

I would like to have a dynamic p:dashboard.

Without `p:dashboard` I have this code:
  ```
 <ui:repeat
            value="#{dashboardWidgetByDashboardNotLazyController.myList}"
             var="dashboardWidget" >

                          <p:panel header="#{dashboardWidget.headline}" closable="true" styleClass="#{dashboardWidget.styleClass}" rendered="# 
                                  {dashboardWidget.uniqueName == 'test'}">
                               // Content
                         </panel>
      
                        <p:panel header="#{dashboardWidget.headline}" closable="true" styleClass="{dashboardWidget.styleClass}" rendered="# 
                              {dashboardWidget.uniqueName == 'test2'}">
                            // Content
                       </panel>
      </ui:repeat>
```

At the end I got a nice dashboard with custom headline, custom color etc.
But I have not the possibility like in `p:dashboard` to drag and drop the widget etc.

### Describe the solution you would like

I´m not sure if this is the right approach to do this. My idea would be:

Add `var` property to `DashboardWidget` like:
`private Object object;`

Afterwards you can use like this:

```
 <p:dashboard
            value="#{myBean.myDashboardModel}"
             var="dashboardWidget" >
```

**Comment by melloware** [comment]
@rider87 we do this exact thing at our client for dynamic dashboards with `ui:repeat`.  What doesn't work for you?

**Comment by rider87** [comment]
I would like to use `p:dashboard` to reorder etc. like in the showcase... Currently I´m using only `ui:repeat` but without the the `p:dashboard` component

**Comment by melloware** [comment]
ok i think i understand the requirement.

**Comment by melloware** [comment]
If you need a workaround to your current solution you can add the draggable and droppable to what you have now with...

// create the panels in a `ui:repeat`
```xml
<ui:repeat value="#{myDataviewerController.dashboardPanels}" var="dashboard">
	<div class="#{dashboard.cssClass}">
		<p:panel id="pnlDashboard" styleClass="dashboard-panel" closable="true" closeTitle="Remove panel" menuTitle="Change panel size">

```

Then add drag and drop to all panels....

```xml
<p:draggable for="pnlDashboard" handle=".ui-panel-titlebar" opacity="0.7" zindex="9999" revert="true"
		scope="dashboard" />

<p:droppable for="pnlDashboard" tolerance="pointer" activeStyleClass="droppable-active" hoverStyleClass="droppable-hover" 
		scope="dashboard">
		<p:ajax listener="#{myDataviewerController.onDashboardDrop}" update=":frmDashboardPanels" oncomplete="reloadCharts(true);" />
</p:droppable>
```

**Comment by melloware** [comment]
I have added `Object value` to DashboardWidget and now allow a `var` attribute which will place that value in the request context.

**Comment by rider87** [comment]
Thanks a lot - that are great news.
Thanks again.
