### ISSUE TITLE
SelectOneMenu: label of SelectItem should be used instead of value

### ISSUE THREAD

**Issue by Weavelor** [primefaces/primefaces#11442]
### Describe the bug

I want to use the `SelectOneMenu` with the `var` attribute and want to use the value of it in an `outputText` inside a `column` (exactly like the advanced `SelectOneMenu` in the Primefaces Showcase):

Currently when you use a `SelectOneMenu` with the attribute `var`, the value of the `SelectItem` gets put into the requestMap together with var.

relevant code snippet in `SelectOneMenuRenderer::encodeOptionsAsTable`:
```java
 ResponseWriter writer = context.getResponseWriter();
        String var = menu.getVar();
        ValueExpression value = menu.getValueExpression("value");
        Class<?> valueType = value == null ? null : value.getType(context.getELContext());

        for (int i = 0; i < selectItems.size(); i++) {
            SelectItem selectItem = selectItems.get(i);
            Object itemValue = selectItem.getValue();
            String itemLabel = getOptionLabel(selectItem);

            String itemStyleClass = SelectOneMenu.ROW_CLASS;
            if (selectItem.isNoSelectionOption()) {
                itemStyleClass += " ui-noselection-option";
            }
            if (selectItem.isDisabled()) {
                itemStyleClass += " ui-state-disabled";
            }

            context.getExternalContext().getRequestMap().put(var, itemValue);
```

### Expected behavior

At my company we use the label for translations and we expected the label to be displayed in the menu. We worked around this by overriding the aforementioned method and by providing an altered list as a parameter, so this is not an issue for us, but we were wondering, why the value is used and not the label? Is this a bug or are we having wrong expectations?

My suggestion would be to either put the label (if set) or the whole SelectItem-Object in the requestMap.

Any help or clarification is much appreciated.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

MyFaces

### JSF version

4.0

### Java version

jdk-17.0.9+9

**Comment by melloware** [comment]
@Weavelor great question.   I looked in Git History and its been like that since the original commit in 2011.

![image](https://github.com/primefaces/primefaces/assets/4399574/eccd35d4-f297-427e-8f61-08fb6216fde1)

I have no idea why but i would think it should be the whole `item` and not the value only.  @tandraschko ?

**Comment by melloware** [comment]
It looks like `CascadeSelectRenderer` and `SelectOneListBoxRenderer` does the same thing but in other places in the code the whole `SelectItem` is put in the `var`.

**Comment by tandraschko** [comment]
TBH i dont know, advanced SelectOneMenu is quite special, just see:

```
                <p:selectOneMenu id="advanced" value="#{selectOneMenuView.country}" converter="#{countryConverter}"
                                panelStyle="width:180px" var="c"
                                filter="true" filterMatchMode="startsWith" filterNormalize="true">

                    <f:selectItems value="#{selectOneMenuView.countries}" var="country"
                                itemLabel="#{country.name}" itemValue="#{country}"/>

                    <p:column style="width:10%">
                        <span class="flag flag-#{c.code}" style="width: 30px; height: 20px"/>
                    </p:column>

                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Name"/>
                        </f:facet>
                        <h:outputText value="#{c.name}"/>
                    </p:column>

                    <f:facet name="footer">
                        <h:outputText value="#{selectOneMenuView.countries.size()} countries"
                                    style="font-weight:bold;" styleClass="py-1 block"/>
                    </f:facet>
                </p:selectOneMenu>
```

so it actually pushes `#{country}` to `#{c}`

Other components which implements the `var` loops a list of pojos and pushes each value into `var`.
At least this is implemented the same here actually, also the case is quite special.

**Comment by tandraschko** [comment]
IMO your usecase is valid, i'm just not sure if we should change this and break existing applications for your case.

Just put your label into the value OR do something like this:
`<h:outputText value="#{myController.translate(c)}"/>`

**Comment by Weavelor** [comment]
Thank you two for getting back to me so quickly. I totally understand that this would be a breaking change and it wouldn't be worth the hassle. @tandraschko thanks for your suggestions, but unfortunately this would be a breaking change on our side. FYI I solved it by overriding the method like this:

```java
public class MySelectOneMenuRenderer extends SelectOneMenuRenderer {

   @Override
   protected void encodeOptionsAsTable(FacesContext context,
                                       SelectOneMenu menu,
                                       List<SelectItem> selectItems,
                                       List<Column> columns) throws IOException {

      List<SelectItem> alteredSelectItems = new ArrayList<>();
      for (SelectItem selectItem : selectItems) {
         alteredSelectItems.add(new SelectItem(selectItem.getLabel(), selectItem.getLabel()));
      }
      super.encodeOptionsAsTable(context, menu, alteredSelectItems, columns);
   }
}
```
Not super elegant, but it gets the job done and doesn't break anything. 
I'm totally fine with you not changing anything. I just wanted to touch on the subject and wanted your opinion so thank you for your input.
