### ISSUE TITLE
Tree: Drag&Drop Capabilities Lost after Filter Event

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#11459]
### Describe the bug

Whenever a tree  component uses both features "drag&drop" and "filter", after filtering the drag&drop capability is lost.

### Reproducer

```
<p:tree value="#{controller.treeRoot}" var="node"
        draggable="true"
        filterBy="#{node.title}" filterMatchMode="contains"
>
```

### Expected behavior

Drag&Drop should be available after the filter was applied.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.4

### Theme

-

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

all

**Comment by melloware** [comment]
Thank you very much @RohdeSchwarz-SDC !!!  13.0.6 is released if you want to test it out.
