### ISSUE TITLE
SQL Injection may be possible on Primefaces 13

### ISSUE THREAD

**Issue by amateurproof** [primefaces/primefaces#11475]
### Describe the bug

I have a demo application consisting of one form (dashboard.xhtml) which allows user to select a file and then add a row to a datatable and there is no database associated to this application. However, when I run ZAP vulnerability assessment on this basic application, I have a result suggesting that SQL Injection may be possible on it as you can see below. So I want to know which kind of action should I take to fixe it, knowing that there is no sql statement to review?

URL : http://localhost:8080/uploadCsrf/javax.faces.resource/components.js.xhtml?ln=case+randomblob%28100000%29+when+not+null+then+1+else+1+end+&v=13.0.6-SNAPSHOT

Zed Attack Proxy (ZAP) screen
![image](https://github.com/primefaces/primefaces/assets/159808928/a5ba0996-4166-4100-b6ca-281431d745e5)

source code of the app
[UploadCsrf.zip](https://github.com/primefaces/primefaces/files/14343582/UploadCsrf.zip)

### PrimeFaces edition

None

### PrimeFaces version

12 and 13

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

1.8

**Comment by jepsar** [comment]
Looks like a false positive.

**Comment by tandraschko** [comment]
yeah, false positiv and nothing we can change
