### ISSUE TITLE
File Upload: Question regarding deprecated attributes

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#11473]
### Describe the bug

In PF 14 it is stated:

* `invalidSizeMessage`, `invalidFileMessage`, `fileLimitMessage` are deprecated and will be removed in 15.0.0. PF i18n will be used for it.

How should this work if i want to have a specific invalidSizeMessage/invalidFileMessage for each usage, e.g., to translate the allowTypes and sizeLimit values into a human-readable text, as demonstrated in the current fileupload.xhtml file.

```
                <p:fileUpload mode="advanced"
                              multiple="false"
                              sizeLimit="102400" allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
                              invalidSizeMessage="Maximum file size allowed is 100 KB"
                              invalidFileMessage="only gif | jpg | jpeg | png is allowed"
                              update="messages cropperPanel"
                              listener="#{cropUploaderBean.handleFileUpload}"/>

```

Would appreciate a hint how to handle this without the deprecated attributes. Many thanks in advance.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

All

### JSF version

3

### Java version

11

**Comment by tuerker** [comment]
The generic messages without their _detail variants are of limited use since you as a user get the info that something was wrong without any clear instruction how to fix it.

Maybe I have missed something or some needed migration steps are not documented in the migration guide:

* Without adding an explicit p:message element (which was formerly implicitly available with the file upload component), no file validation error is printed at all. 
* When and how the _detail variant of the corresponding message is shown? Do i have to add/specify here something since i only get the generic variant printed?
* The value of the attribute messageTemplate is not printed anymore. 
* The show case does not have any examples using the messageTemplate attribute. 
* The show case (fileupload.xhtml) still shows the old (deprecated) usage.
* The migration guide has two subsections "File Upload" -> should be consolidated to one.
* What does "Please make sure to enable CSV to use it." actually means: how and where should CSV enabled?

Many thanks in advance for looking into this issue.

**Comment by tandraschko** [comment]
1) yes, expected
2) p:message showDetail=true
3) should still be used; issue + reproducer plz
4) PR plz
5) PR plz
6) PR plz
7) we have a documentation for CSV, not sure if this is a problem

**Comment by tuerker** [comment]
1. needs to be explicitly mentioned in the migration document
2. thanks for the hint. In case of allowType, the resulting message does not look nice due to the repetition, see:
![image](https://github.com/primefaces/primefaces/assets/10051373/d7958ea2-98f0-4e6f-9f03-6455402ade80)
This could be fixed by some rephrasing. Besides, it would be good to print at least the value of the attribute allowTypes to give the user at least abstract idea what is expected.
3. i was wondering whether the function of this attribute was checked at all since it it not part of any show case example. 
4.-5. should this not be the task of the person who did the revision because this person knows best what has changed.
6. quickly done. PR submitted
7. ok without further looking into it, i had no idea what was meant by CSV. I see it is refering to client-side validation. surely, this is not the problem.

**Comment by tandraschko** [comment]
2) feel free to create a new issue and PR here, we may also improve other fileupload related messages
3) i dont think so TBH if we dont have tests for it
4) adding a showcase example and test it can be done by everyone

**Comment by tuerker** [comment]
i did now 5. migrated the deprecated attributes of the file upload component in the showcase. 

also extended the invalid file type message such that now the alloed types are printed, too.

i am not seeing that the messageTemplate is used. Somebody being deeper into this issue should have a look at it, too.

**Comment by tandraschko** [comment]
its at least used in code
i think it should not to hard to add a showcase example and test it

**Comment by tuerker** [comment]
I have now extended the primefaces.FileValidator.ALLOW_TYPES_detail message by printing allowed types value. So, the corresponding messages look as follows:

primefaces.FileValidator.FILE_LIMIT = Maximum number of files exceeded.
primefaces.FileValidator.FILE_LIMIT_detail = Maximum number: {0}.
primefaces.FileValidator.ALLOW_TYPES = Invalid file type.
primefaces.FileValidator.ALLOW_TYPES_detail = Invalid file type: ''{0}''. Allowed types: ''{1}''.
primefaces.FileValidator.SIZE_LIMIT = Invalid file size.
primefaces.FileValidator.SIZE_LIMIT_detail = File ''{0}'' must not be larger than {1}.

Note that these message entries are missing for most languages except English. Within the PR https://github.com/primefaces/primefaces/pull/11482, I have added the German and Turkish cases.

Would it be good to create an issue for the remaining languages or do you usually let the people translate whenever there is an actual need?

I would also suggest to create an issue for migrating the previous invalidFileMessage to the validateFile component since the generic print of the allowed type pattern is not really human-readable.

@tandraschko What do you think?

**Comment by tuerker** [comment]
I have now further improved the invalidType message print such that the pattern is "more human-radable".

![image](https://github.com/primefaces/primefaces/assets/10051373/3184b5d9-4fbf-4d5f-bc44-929ab8a2c415)

This issue can be closed when https://github.com/primefaces/primefaces/pull/11482 is merged.
