### ISSUE TITLE
p:diagram -> p:menuButton is not opening the p:menuitem

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#11478]
### Describe the bug

If I add inside the p:diagram a p:panel with p:menuButton, I´m not able to open the p:menuitem from p:menuButton:
<img width="946" alt="image" src="https://github.com/primefaces/primefaces/assets/9787533/b2504ca0-ea71-4790-9f74-16bde1e14bab">

Reproducer:
[pf-diagram-menu-issue.zip](https://github.com/primefaces/primefaces/files/14345645/pf-diagram-menu-issue.zip)

### Expected behavior

p:menuButton will open to see all p:menuitem

### PrimeFaces edition

None

### PrimeFaces version

13.0.6

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

11

**Comment by melloware** [comment]
Yep with that latest fix you can't put complex items in the facet.

**Comment by rider87** [comment]
ok, what does this mean? any chance to fix this?

**Comment by melloware** [comment]
nope i will have to revert the fix for https://github.com/primefaces/primefaces/pull/11456

**Comment by melloware** [comment]
Reverted.

**Comment by rider87** [comment]
If I remember correctly, than the `p:menuButton` will work and open to show up the p:menu. 
But it´s still an issue, because the `p:menuButton` will have not a uniqueId. This means you have e.g. 10 p:panel with 10x p:menu, but each p:menu has the same id.
