### ISSUE TITLE
Dialog: Resizing UI issue (jQuery UI Resizable)

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#11476]
### Describe the bug

When resizing a dialog with a scrollbar in Chromium, the dialog content becomes smaller than it should. It seems to work fine in Firefox. Example:

Start:
![image](https://github.com/primefaces/primefaces/assets/8350714/2b8cca4e-a764-48fb-ad7c-6416512d2265)

After multiple horizontal resizes:
![image](https://github.com/primefaces/primefaces/assets/8350714/a59b3bba-e9ab-4ac2-9600-ae9cbf11601c)

Working fine in Firefox:
![image](https://github.com/primefaces/primefaces/assets/8350714/4efeb9b0-fa0a-420f-aa4c-9d13cddeafd3)

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/14345186/primefaces-test.zip)

1. Click on the right border and drag the right border so the dialog becomes just a bit smaller.
2. Repeat for x times

### Expected behavior

The dialog content fills the whole width of the dialog.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.6

### JSF implementation

All

### JSF version

4.0

### Java version

17

### Browser(s)

Version 121.0.6167.185 (Official Build) (64-bit)

**Comment by melloware** [comment]
Sounds like this issue again: https://github.com/primefaces/primefaces/issues/8989

**Comment by melloware** [comment]
Maybe something with jQuery changed again...

**Comment by melloware** [comment]
Hmmm I am trying your reproducer in Chrome and mine is fine?

**Comment by mkomko** [comment]
Hmm. Did you run it with a "4.0" profile? Are you on Windows or another OS (we are on Windows)?

**Comment by melloware** [comment]
Windows 11 Chrome 121.  Using your exact reproducer on 4.0.  So in Chrome you just keep resizing the dialog right?

**Comment by melloware** [comment]
OK  iwas able to reproduce now!  Had to drag slower....

**Comment by melloware** [comment]
@mkomko i tried this patch here: https://github.com/jquery/jquery-ui/commit/62f2ccc5678a8b09df85afd006eb623ac38af189

Locally and it still doesn't fix this Chrome issue.  Everything works in Firefox.  This is definitely a Jquery UI resizable bug.

**Comment by melloware** [comment]
@mkomko i just submitted a PR with jqueyr 1.13.3 and the behavior is not totally fixed but its much better.  This is the worst I can make it now.  Not great but better than before.

![image](https://github.com/primefaces/primefaces/assets/4399574/ccd69b23-5e7c-4eee-8c0c-cfbf4895a769)

**Comment by melloware** [comment]
See: https://github.com/jquery/jquery-ui/issues/2277

**Comment by melloware** [comment]
some dude just submitted a PR: https://github.com/jquery/jquery-ui/pull/2281

**Comment by melloware** [comment]
His patch was accepted by Jquery UI so this will be in 15.0.0
