### ISSUE TITLE
InputMask:  fixed characters

### ISSUE THREAD

**Issue by amran-bd** [primefaces/primefaces#11497]
### Describe the bug

I use PF 13, JSF latest version, Jakarta-10, Java 21. I tried using <p:inputMask> to fix 2 characters of the mask. All characters are working combination but SA is not working. I feel that this is a bug. Could u please check?

### Reproducer

<p:inputMask  id="ipanNo2" dir="ltr" mask="SA99" value="#{beanView.test}"/>

### Expected behavior

SA should be shown in the inputMask after page load.

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### Theme

poseidon

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
I think your expectation of how mask works is incorrect. See the docs: https://robinherbots.github.io/Inputmask/#/documentation
