### ISSUE TITLE
Showcase template: wrong {#resource} expression

### ISSUE THREAD

**Issue by pnavato** [primefaces/primefaces#11498]
### Describe the bug

The file `template.xhtml` of the Showcase contains the following lines:

    <link href="#{resource['showcase/images/favicon-32x32.png']}" rel="icon" type="image/png" sizes="32x32"/>
    <link href="#{resource['showcase/images/favicon-16x16.png']}" rel="icon" type="image/png" sizes="16x16"/>

they should be rewritten as:

    <link href="#{resource['showcase:images/favicon-32x32.png']}" rel="icon" type="image/png" sizes="32x32"/>
    <link href="#{resource['showcase:images/favicon-16x16.png']}" rel="icon" type="image/png" sizes="16x16"/>

with a colon instead of a slash after the library name because in this way they work even if the library is versioned (i.e. if the effective path is like `showcase/1_0/images/favicon-32x32.png`).

I know that this is a very small defect but consider that the showcase can be used as a guideline for writing new applications and a defect in it can cause problems just like a defect in the library (it just happened to me).  The defect is both in master and 13.x branch.

### PrimeFaces edition

None

### PrimeFaces version

13.x

### JSF implementation

All

### JSF version

latest

### Java version

17

**Comment by melloware** [comment]
@pnavato thanks for the report!
