### ISSUE TITLE
DataTable: Header does not scroll horizontally

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#11491]
### Describe the bug

When scrolling horizontally in a datatable, the data scrolls, but not the header.
This worked in 13.0.5, but no longer in 13.0.6

I suppose this problem will appear in the PF-demo as well as soon as it used 13.0.6

### Reproducer

[reproducer.zip](https://github.com/primefaces/primefaces/files/14360378/reproducer.zip)

### Expected behavior

Scroll horizontally in both tables. Only the data will move not the header.

![image](https://github.com/primefaces/primefaces/assets/47218021/6d074699-49ac-410f-8a8b-8b6bf6ad58d7)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.6

### JSF implementation

Mojarra

### JSF version

4.0.4

### Java version

17

### Browser(s)

EDGE, Firefox, Chrome

**Comment by melloware** [comment]
@wlhUser some analysis on which issue you think causes it would be great.  Here is what was fixed in 13.0.6: https://github.com/primefaces/primefaces/issues?q=is%3Aclosed+milestone%3A13.0.6

My first thought is this one?  https://github.com/primefaces/primefaces/pull/11336

**Comment by wlhUser** [comment]
Yes I also think its #11336.
I suppose RTL and non-RTL are mixed up.
I compared datatable.js and datatable.frozen.js
See screenshot
![image](https://github.com/primefaces/primefaces/assets/47218021/1656cddc-d8d0-4783-ae70-28dd5fe508a9)

**Comment by melloware** [comment]
Yep @bvfalcon this broke normal LTR the column headers don't move.  I am going to revert part of your change now.

**Comment by melloware** [comment]
yep i will leave my PR open until i hear from you.

**Comment by wlhUser** [comment]
@melloware After this one is fixed, maybe its worth thinking about an earlier 13.0.7

**Comment by bvfalcon** [comment]
> yep i will leave my PR open until i hear from you.

I have made an [additional change](https://github.com/primefaces/primefaces/pull/11494#issuecomment-1957844688) to your commit.
Unfortunately, it is very difficult to do horizontal scrolling for RTL too

**Comment by melloware** [comment]
I will test this change in the morning
