### ISSUE TITLE
Perf: Don't render class and style if blank

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11508]
I found a few places where we are unnecessarily sending attributes to the browser empty taking up network resources like..

```xml
<td role="gridcell" class="">
```

the `class=""` is unnecessary and in a Table there could be hundreds of these.

**Comment by jepsar** [comment]
I was about to report that. +1

**Comment by melloware** [comment]
@jepsar let me know if you found any others I saw in DataTable and PanelGrid were a few of the offenders with repeating elements i was worried about.
