### ISSUE TITLE
SEF: implement @dialog

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#1150]
It's a common case that only the dialog content should be updated if you currently work in the dialog.
Currently you must always use udpate="myUsecaseADialog" but that's very annoying.

**Comment by kukel** [comment]
So @dialog updates just the content or the dialog? Hmmm @dialog vs @dialogContent...

**Comment by tandraschko** [comment]
Actually updating the dialog is easier as updating the content but updating the content should be enough.
Maybe it's better to update the whole dialog.

**Comment by kukel** [comment]
I've seen cases (don't have examples at hand) where updating the dialog did not always behave as expected. But that might be older versions related or cornercases. So updating the dialog would be ok I guess

**Comment by tandraschko** [comment]
hmm you are right
when you open a dialog via js (instead the visible attribute), you will unintentionally close it when you update=@dialog.

**Comment by kukel** [comment]
yep that was one of them.... phew... no korsakov or alzheimer yet here :-)

**Comment by tandraschko** [comment]
Will close it for now - don't need it anymore and there is no perfect solution.
