### ISSUE TITLE
FileUpload: attribute messageTemplate has no effect anymore

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#11505]
### Describe the bug

Using the attribute messageTemplate in the fileUpload component does not change the way the added file message is formatted.

For instance, using 

```
    <p:fileUpload mode="advanced"
                  multiple="false"
                  messageTemplate="__{size} {name}__"
                  update="messages"
                  listener="#{testView.handleFileUpload}" />

```

i would expect that the resulting message prints the size and the name of the uploaded file enclosed by two underscores. Currently, is has no effect:

![image](https://github.com/primefaces/primefaces/assets/10051373/451fa19c-7d21-4ba1-b4bc-3130ea4de2d5)

### Reproducer

Here is the repoducer:  [p-fileUpload.zip](https://github.com/primefaces/primefaces/files/14376252/p-fileUpload.zip)

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-RC1

### JSF implementation

Mojarra

### JSF version

3

### Java version

11

**Comment by tuerker** [comment]
> @tuerker are you sure you know what `messageTemplate` does? I just backed your reproducer up to 13.x and it has the exact same behavior as 14.X
> 
> [pf-11505.zip](https://github.com/primefaces/primefaces/files/14379009/pf-11505.zip)
> 
> `MessageTemplate` looks like it hsa only ever been used to show error messages...
> 
> It even says so in the JS doc `@prop {string} cfg.messageTemplate Message template to use when displaying file validation errors.`
> 
> In Fact 12.0.0 behaves the same exact way. What gave you the impression that is what `messageTemplate` was supposed to do?

till PF14 the messagesTemplate was used for formatting validation error messages. I am heavily using it in many places of my code. when i looked into PF 14 i saw that the file upload component was significantly revised such that the invalidSizeMessage, invalidFileMessage, fileLimitMessage are not working anymore as before and are on deprecation list for PF15.

therefore i opened the other issue https://github.com/primefaces/primefaces/issues/11473. maybe yoiu can have a detailed view on the communication there. to make it short: the revised file upload component some documentation and extension which i provided with PR https://github.com/primefaces/primefaces/pull/11482. please also have a detailed view on the long communication there. 

i told tandrasko that the messageTemplate attribute is not used anymore after the revision of January 24. He stated that using this attribute for validation error purposes was a misuse but should be there for formatting the messages after the upload of the files. Therefore, i created this issue here to point out that currently this messageTemplate attribute has no effect. If this attribute should be there to give the user the option to individually format the file upload message, which i i would highly appreciate, then this attribute should work. If not, then this attribute should better be eliminated completely.

**Comment by melloware** [comment]
the message template is used here:

https://github.com/primefaces/primefaces/blob/8584a91898528bfa14d8b29c91eea5ce98c190d6/primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js#L767-L776

What I am "confused" about your reproducer above was your "expected outcome"   Your expected outcome doesn't work in 12.0, 13.0 or 14.0.  

So you say the behavior has changed but that is not what I am seeing from your reproducer?  Can you update your reproducer to actually show `messageTemplate` working in PF12 or 13?

**Comment by tuerker** [comment]
Formerly messageTemplate was fine working to format the validation error message. After the revision it is not used anymore for this purpose. 

The reproducer shows that the attribute messageTemplate has also no effect on the uploaded file message. I am fully aware of that it had also no effect on the uploaded file message before. but tansdrasko claimed that this attribute is still needed for formatting the uploaded file message. 

The showMessage function you mentioned above would actually make use of this attribute but currently the code does not reach that point anymore due to the revision of January:

```
// we need to pass the real invisible input, which contains the filelist
                    var validationResult = PrimeFaces.validation.validate($this.jq, data.fileInput, update, true, true, true, true);
                    if (!validationResult.valid) {
                        for (let clientId in validationResult.messages) {
                            var msgs = validationResult.messages[clientId];
                            for (let msg of msgs) {
                                if (!msg.rendered) {
                                    $this.showMessage({
                                        summary: msg.summary,
                                        filename: file.name,
                                        filesize: file.size
                                    });
                                }
                            }
                        }
```

this new validation function does the rendering of the message such that the if always false and thus the showMessage function is not invoked. therefore, I asked tansdrasko to have a look into this issue since he did that revision in January and should best know how fix it.

**Comment by melloware** [comment]
Got it.  Yeah all that code should be ripped out if its no longer being used I agree.

**Comment by tuerker** [comment]
so, actually this issue is more feature revision issue instead of bug report.
