### ISSUE TITLE
DataExporter calls load method twice on lazy DataTables

### ISSUE THREAD

**Issue by jrodalo** [primefaces/primefaces#1151]
I'm using a DataTable with `lazy="true"` to paginate a big datasource. It works perfect, but, if you include a `<p:dataExporter>` for that table, the query is executed twice while exporting the data (without pagination).

You can test it with the lastest version of the Showcase, just include a dataExporter on \src\main\webapp\ui\data\datatable\lazy.xhtml

``` xml
<p:dataTable var="car" value="#{dtLazyView.lazyModel}" paginator="true" rows="10" id="carTable" lazy="true">
    <p:column headerText="Id" sortBy="#{car.id}" filterBy="#{car.id}">
        <h:outputText value="#{car.id}" />
    </p:column>
    <p:column headerText="Brand" sortBy="#{car.brand}" filterBy="#{car.brand}">
        <h:outputText value="#{car.brand}" />
    </p:column>
</p:dataTable>

<h:commandLink value="Export">
    <p:dataExporter type="xls" target="carTable" fileName="test" />
</h:commandLink>
```

In this case, `LazyCarDataModel.load` is called twice (iterating 200 cars each time).

Related to issue #763 
## 

Primefaces 5.3

**Comment by mateofacu** [comment]
I run into the same issue but exploring source code I realized that the second call is not the same.

Second loadlazydatamodel call is used to restore table state with the original set of data and paging state.

Any way I think the implementation of the exporter could use another lazydatamodel instance to avoid the restore phase. I had problems because of bug #763

**Comment by christophs78** [comment]
`org.primefaces.component.datatable.export.DataTableExporter`

```
protected void exportAll(FacesContext context, DataTable table, Object document) {
	int first = table.getFirst();
	int rowCount = table.getRowCount();
	int rows = table.getRows();
	boolean lazy = table.isLazy();

	if (lazy) {
		if (rowCount > 0) {
			table.setFirst(0);
			table.setRows(rowCount);
			table.clearLazyCache();
			table.loadLazyData();
		}

		for (int rowIndex = 0; rowIndex < rowCount; rowIndex++) {
			exportRow(table, document, rowIndex);
		}

		//restore
		table.setFirst(first);
		table.setRows(rows);
		table.setRowIndex(-1);
		table.clearLazyCache();
		table.loadLazyData();
	}
```

call 1:
![grafik](https://user-images.githubusercontent.com/10461942/71557779-377bde80-2a4b-11ea-835e-55d58a171c9a.png)

call 2:
![grafik](https://user-images.githubusercontent.com/10461942/71557681-a6f0ce80-2a49-11ea-88a2-a8e91528f91d.png)

**Comment by Rapster** [comment]
Why don't we just save wrappeddata from lazydatamodel on the side, and set it back after export?
