### ISSUE TITLE
Tree: Drag&Drop Misbehaviour after Fix #11514

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#11520]
### Describe the bug

The bugfix for issue #11513 solved some issues when reordering sibling tree nodes (great work!).

We tested some scenarios using a flat structure (root > item a, ..., item c) 

However, if we add a parent node (root > folder 1 > item a ...) the drag&drop behaves incorrectly.

```
a) Drag 'B', drop above 'A'................. => Does not trigger ajax event
b) Drag 'B', drop between 'B/C'............. => Does trigger ajax event (shouldn't)
c) Drag 'C', drop between 'A/B' or above 'A' => Does not drop at all
```

### Reproducer

[Reproducer-11520.zip](https://github.com/primefaces/primefaces/files/14402510/Reproducer-11520.zip)

### Expected behavior

It should work ;-)

### PrimeFaces edition

None

### PrimeFaces version

13

### Theme

irrelevant

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

irrelevant

**Comment by melloware** [comment]
Thanks for the reproducer

**Comment by melloware** [comment]
OK can you test this patched version.
[pf-11520.zip](https://github.com/primefaces/primefaces/files/14404806/pf-11520.zip)

**Comment by RohdeSchwarz-SDC** [comment]
Nice, this solution is almost perfect.

One last aspect is missing yet:

- Remove the drop-restriction `onDrop="#{treeBean.dropRestrictSameLevel}"`
- Add `folder2` in StdOut 
- Drop Leaf `F` and drop between `A/B` -> Missing Ajax event

[Reproducer-11520-b.zip](https://github.com/primefaces/primefaces/files/14405363/Reproducer-11520-b.zip)

**Comment by RohdeSchwarz-SDC** [comment]
Seems as if `E` (dndIndex=1) and Position between `A/B` (dndIndex=1) are regarded as equal and therefore no ajax is triggered.
But here the parents are different.

**Comment by melloware** [comment]
Yep that is what I was hoping you would say.  Drop Restrict doesn't mean within a node it just means any node at the same level. I wasn't sure about that but now i know let me send you another version.

**Comment by melloware** [comment]
Try this version please:
[pf-11520-2.zip](https://github.com/primefaces/primefaces/files/14405714/pf-11520-2.zip)

**Comment by RohdeSchwarz-SDC** [comment]
Thanks for this second fix, but I think it breaks the scenario when we drop `C` between `A/B`, can you check that?

**Comment by melloware** [comment]
Checking

**Comment by melloware** [comment]
One more time...
[pf-11520-3.zip](https://github.com/primefaces/primefaces/files/14405975/pf-11520-3.zip)

**Comment by RohdeSchwarz-SDC** [comment]
I hope you haven't gotten tired 😉

The reversed case move `A` between `B/C`  should be considered, too.

**Comment by RohdeSchwarz-SDC** [comment]
Oh I see the difference.

As soon as I add the `onDrop="#{treeBean.dropRestrictSameLevel}"` restriction, everything is right.

I removed the `onDrop` in my second reproducer ([Reproducer-11520-b.zip](https://github.com/primefaces/primefaces/files/14405363/Reproducer-11520-b.zip))

**Comment by melloware** [comment]
OK I see the issue.  When you use `onDrop1 the indexes are difference.

Why aren't you using `dropRestrict="sibling"` when you want to only allow same level?  See: https://primefaces.github.io/primefaces/13_0_0/#/components/tree?id=attributes

I think we are working around a problem that is not a problem?

**Comment by melloware** [comment]
Here is your original bug all I did was add `dropRestrict="sibling"` and it was all working.

[pf-11513.zip](https://github.com/primefaces/primefaces/files/14406510/pf-11513.zip)

**Comment by RohdeSchwarz-SDC** [comment]
My scenario in production is to move items (leafs) into other folders on different levels.

This includes both:
- Move between siblings (A -> B/C)
- Move elsewhere (D -> E/F) or (D -> B/C)

I'm very grateful for your fixes as it now works for my use cases.

The only question is, if primefaces should be able to handle all kinds of custom `onDrop` functions while returning the correct dropIndex via `dragdrop` event. It's up to you to decide :-)

**Comment by melloware** [comment]
OK I think its much simpler then try this one...

[pf-11520-4.zip](https://github.com/primefaces/primefaces/files/14406725/pf-11520-4.zip)


baiscally 

```js
                if ($this.cfg.controlled) {
                    dndIndex = dndIndex - 1;
                }
```

**Comment by melloware** [comment]
Yeah i think because you are controlled the onDrop that is called `controlled` mode. and it looks like in Controlled mode the AJAX is always fired for you to decide what to do with it?

```js
        if(this.cfg.controlled) {
            options.oncomplete = function(xhr, status, args, data) {
                if(args.access) {
                    for(var i = 0; i < $this.droppedNodeParams.length; i++) {
                        var params = $this.droppedNodeParams[i];
                        if(params.dropPoint)
                            $this.onDropPoint(params.ui, params.dragSource, params.dragNode, params.targetDragNode, params.dropPoint, params.dropNode, params.transfer);
                        else
                            $this.onDropNode(params.ui, params.dragSource, params.dragNode, params.targetDragNode, params.droppable, params.dropNode, params.transfer);
                    }
                }
            };
        }
```

**Comment by RohdeSchwarz-SDC** [comment]
You are a wizard 🪄
