### ISSUE TITLE
SelectOneMenu: tabindex not working as expected since 13

### ISSUE THREAD

**Issue by DadApple9** [primefaces/primefaces#11527]
### Describe the bug

In older versions of PrimeFaces <p:selectOneMenu> was renderd in HTML as **select**-Tag. The tabindex-attribute of <p:selectOneMenu> was added to the **select**-Tag with the value that was specified in <p:selectOneMenu>.

In PrimeFaces 13 <p:selectOneMenu> is rendered as **span**. The tabindex-attribute of <p:selectOneMenu> is NOT added to the **span**-Element with the specified value. Instead every <p:selectOneMenu> is rendered as <span tabindex="0" ...>.

Is this wanted? If yes, how can I implement a working tabindex?

### Reproducer

					<div class="container row nomb clwdt">
						<section class="one-fourth column">
							<h:outputLabel
								value="#{msgs['config.product']}"
								for="Config_Product" />
						</section>
						<section
							class="three-fourth column #{messageBean.cssClass('Config_Product')}">
							<p:selectOneMenu id="Config_Product"
								value="#{config.product}"
								tabindex="25">
								<f:selectItems
									value="#{config.product.listOfProducts}" var="entry"
									itemValue="#{entry.value}" itemLabel="#{entry.label}" />
							</p:selectOneMenu>
						</section>
					</div>

### Expected behavior

I would expect, that the tabindex would renderd in HTML as tabindex="25". Instead it is always rendered as tabindex="0" for all <p:selectOneMenu>-components on my page.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### JSF implementation

MyFaces

### JSF version

4.0.2

### Java version

17

**Comment by melloware** [comment]
Isn't that already fixed in 13.0.6 here: https://github.com/primefaces/primefaces/issues/11325

**Comment by DadApple9** [comment]
@melloware Thank you very much! I updated PrimeFaces to 13.0.6 and it worked as expected. :-)

**Comment by melloware** [comment]
Nice I will close this ticket.
