### ISSUE TITLE
DataTable: Paginator After upgrade to 13.0.6  always uses first=0 in .load() method

### ISSUE THREAD

**Issue by AndrewG10i** [primefaces/primefaces#11521]
### Describe the bug

Upgraded PrimeFaces from 13.0.5 to 13.0.6 and noticed that DataTable with LazyDataModel stopped paginating properly. Investigation revealed that `.load()` method always called with `first=0` on pagination to other pages. Reverting back to 13.0.5 resolves the issue without any other code changes.

I am running Payara 6.2024.2 and PF with Jakarta classifier.

### PrimeFaces edition

None

### PrimeFaces version

13.0.6

### JSF implementation

Mojarra

### JSF version

3.0.2

### Java version

17

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/pull/11377

It's only for virtual scroll and live scroll. So it should not affect paginator at all.

**Comment by AndrewG10i** [comment]
This is the code (DataTable declaration) I have:
```
<p:dataTable id="usersTable" value="#{dirCntroller.usersLazyDS}" lazy="true" var="rowData" rowIndexVar="rowIndex"
             paginator="true" rows="25" rowsPerPageTemplate="25,50,100" paginatorPosition="top" paginatorAlwaysVisible="true"
             paginatorTemplate="{CurrentPageReport} {JumpToPageDropdown} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
             reflow="true" emptyMessage="#{labels['general.dataTable.noRecordsFound']}" filterDelay="800" styleClass="usersTable" widgetVar="usersTableWV">
```

I will try to prepare reproducer. Meanwhile decided to report the issue so in case someone else have it they can confirm as well.

**Comment by melloware** [comment]
We have tons of integrations tests that test pagination and datatable that all passed so if this is a bug it means there is a gap in the integration tests.

**Comment by AndrewG10i** [comment]
Okay, so far cannot reproduce this issue, reproducer works fine. Will investigate further what exactly triggers issue in my app and in case issue found in the PF lib - will reopen this ticket again. But for now closing it. Thanks!

**Comment by melloware** [comment]
Thanks yes please let me know what you find out!

**Comment by AndrewG10i** [comment]
Okay, after spending several hours on this, I finally found root cause. ;))
So look, this particular project uses PF since version 11.x I think, and it was working fine until v13.0.5 (inclusive). But since v13.0.6 - behavior of paginator in DataTable with LazyDataModel has changed.

So basically the root cause is related to the [Issue 8062](https://github.com/primefaces/primefaces/issues/8062). As discussed in that issue - we also require to use one single API call for retrieving data from the DB, and result returns two values pair: data subset and count of the whole data set.

As such, `LazyDataModel.count()` method returns `0` only, and the respective handling is implemented in the `LazyDataModel.load()` method.
**And this causes the issue with pagination.**

So once I change `LazyDataModel.count()` from `return 0;` to return actual count - it fixes behavior of paginator in v13.0.6 as well.

Could you please reopen this issue and provide your feedback? Also please let me know if you would like me to post a reproducer as well. Thank you!

**Comment by melloware** [comment]
@Rapster thoughts here?

**Comment by melloware** [comment]
@AndrewG10i i am pretty sure based on the migration guide for 11.0.0 you should not have been returning count 0 even then bsaed on this migration note: https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/11_0_0?id=datatable-dataview-datagrid-datalist

**Comment by tandraschko** [comment]
we must support cases like seen here: https://github.com/primefaces/primefaces/issues/8062#issuecomment-965076823
a reproducer would be great

@melloware can you check what did we change DataTable related in 13.0.6? also if we have similar integration tests?

**Comment by melloware** [comment]
@tandraschko we have tons of integration tests and the only change was to fix LiveScroll and Virtual Scroll.  Regular pagination was not touched.

See: https://github.com/primefaces/primefaces/pull/11377

**Comment by AndrewG10i** [comment]
> @AndrewG10i i am pretty sure based on the migration guide for 11.0.0 you should not have been returning count 0 even then based on this migration note: https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/11_0_0?id=datatable-dataview-datagrid-datalist

Thanks for pointing to that note. But seems the project still in compliance with it. :)
Under the item "see [DataTable](https://primefaces.github.io/primefaces/13_0_0/#/components/datatable?id=lazy-loading) for details how to avoid a separate count-statement against your datasource" it basically shows the implementation as per [8062](https://github.com/primefaces/primefaces/issues/8062).

Let me post reproducer shortly...

**Comment by tandraschko** [comment]
@melloware we dont have a testcase for this - we should just copy DataTable037 and implement rowCount return0

**Comment by tandraschko** [comment]
see https://github.com/tandraschko/primefaces/commit/cf3f9978d94bd640955591cb0a19e73c8adc5189

it fails currently

**Comment by melloware** [comment]
OK good thanks for adding a test case.  Let me look and see if I can debug.

**Comment by melloware** [comment]
@tandraschko @AndrewG10i @jungm I got to the bottom of it and its this fix: https://github.com/primefaces/primefaces/pull/11402

It also came with an integration test so we have conflicting issues both with integration tests proving something is wrong.
