### ISSUE TITLE
DefaultCommand: triggered on filter event

### ISSUE THREAD

**Issue by haraleib** [primefaces/primefaces#11537]
### First case
**Condition**
If I have a

- table with a filterable column
- commandButton
- defaultCommand pointing to the commandButton

**Action**
If I type something in the filtersection in the column header and press enter

**Behaviour**
The first request is the request from the commandButton (triggered by defaultCommand)
The second request is the filter request

**Expected Behaviour**
The commandButton should **not** be triggered in this case

In the screenshot you can see in the right section that the first request after pressing enter in the filter section triggers a request from the commandButton

_1 Request defaultCommand_
![image](https://github.com/primefaces/primefaces/assets/19574757/e3dc2b48-b22e-4c90-8b90-ad28833bd8a5) 

_2 Request dataTable_
![image](https://github.com/primefaces/primefaces/assets/19574757/112f68a7-6336-48da-8e0d-ff75161da398)

### Second case
If I have a

- p:inputText with p:ajax event="blur"
- commandButton
- defaultCommand pointing to the commandButton

**Action**
If I type something in the inputText and press enter

**Behaviour**
The commandButton is triggered

**Expected Behaviour**
Don't really know. But maybe first losing focus of the inputText to trigger the blur event and then trigger the defaultCommand?

Tested with PF 10 and PF 11.0.8

### Reproducer

[playground-primefaces.zip](https://github.com/primefaces/primefaces/files/14451240/playground-primefaces.zip)

### PrimeFaces edition

None

### PrimeFaces version

10.0.0

### JSF implementation

MyFaces

### JSF version

2.3.6

### Java version

11

**Comment by melloware** [comment]
This is a bug the ENTER on filter event should `preventDefault()`

**Comment by melloware** [comment]
Wow this code has been like this since 2012!!!

![image](https://github.com/primefaces/primefaces/assets/4399574/afba8d1a-a55e-4341-9cf6-5adffd141eeb)

**Comment by melloware** [comment]
@haraleib can you add this MonkeyPatch to your code. 

```js
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.bindEnterKeyFilter = function(filter) {
        var $this = this;

        filter.off('keydown').on('keydown', function(e) {
            if (e.key === 'Enter') {
                $this.filter();

                e.preventDefault();
                e.stopPropagation();
            }
        });
    }
};
```

That should fix it where the filter blocks the ENTER key from propagating up which was the original intent of that ticket in 2012 it was just not implemented correctly.

**Comment by haraleib** [comment]
@melloware thanks for your quick respond. I will try it tomorrow.
Do you have an opinion on the second case I mentioned with p:inputText and event="blur"?

**Comment by melloware** [comment]
Don't use `blur` use `change` blur happens AFTER you leave the field.

**Comment by haraleib** [comment]
@melloware thank you very much for the workaround for case 1, it is working as expected !!

Case 2 is also not working with change event. That leads to unwanted behaviour. 
I could imagine that the expected behaviour should be, that the execution order is the same like when the button is clicked with the mouse. 

I think this would lead to something like:
- Enter ist pressed
- Button gets focus??
- The event of the source is triggered
- The event of the commandButton is triggered

Currently it is:
- Type something in inputText with event="blur/change"
- Press enter
- Only the event from the commandButton is triggered

Currently with mouse click:
- Type something in inputText with event="blur/change"
- Press commandButton with mouse click
Event from inputText followed by the event of the commandButton is triggered


What is your opinion on that?

**Comment by melloware** [comment]
Can you open a separate ticket for this blur event issue as its really a separate issue from the DataTable Filter event ENTER issue.

**Comment by haraleib** [comment]
@melloware 
I found a little bug now. I also tested it with filterEvent="keydown" in my dataTable. If I put something in the filter field in the column header and then press enter, the default command is triggered.
I think the default command should never be triggered in a column header filter input field.
Do you have a fix/workaround for this?

**Comment by melloware** [comment]
yes please open a new ticket.
