### ISSUE TITLE
p:inputText attribute for trim trailing whitespace

### ISSUE THREAD

**Issue by haraleib** [primefaces/primefaces#11538]
### Description

- As a user, trailing whitespace in inputFields, which typically happens by accident is relatively useless. (Leading whitespace maybe happens by accident with copy & paste ?)
- As a programmer I want an easy and convenient way to trim trailing whitespaces on each p:inputText, without attaching a custom FacesConverter all the time.

### Describe the solution you would like

- New Attribute trimWhitespace on p:inputText with options leading, trailing, both, default=none or null?
- context-param in web.xml which does this by default for all p:inputText.
```
<context-param>
		<param-name>primefaces.TRIM_WHITESPACE</param-name>
		<param-value>none</param-value>
</context-param>
```

**Comment by melloware** [comment]
No need you can do this already in JSF with 1 class...

```java
@FacesConverter(forClass = String.class)
public class StringTrimmerConverter implements Converter<String> {

    @Override
    public String getAsObject(final FacesContext context, final UIComponent component, final String value) {
        return StringUtils.trimToNull(value);
    }

    @Override
    public String getAsString(final FacesContext context, final UIComponent component, final String value) {
        return value;
    }

}
```

That trims all strings on all forms.

**Comment by tandraschko** [comment]
+1 for the converter, no need to add it in PF

**Comment by haraleib** [comment]
@melloware thank you for the answer. Perfect, I think that is what I need 👍
