### ISSUE TITLE
DataTable: header fixed when scrolling horizontally since 13.0.6

### ISSUE THREAD

**Issue by DadApple9** [primefaces/primefaces#11544]
### Describe the bug

After upgrading PrimeFaces from 13.0.5 to 13.0.6, if you scroll horizontally in a dataTable the header stays fixed. In older PrimeFaces versions it worked.

### Reproducer

<p:dataTable id="tblAddresses" 
	widgetVar="wvtblAddresses"
	var="record" 
	rowIndexVar="index" 
	sortMode="single"
	value="#{listAddresses.listAddresses}"
	rows="#{listAddresses.tableControllerAddresses.currentRowCount}"
	paginator="true"
	paginatorTemplate="#{listAddresses.paginatorTemplate}"
	paginatorPosition="bottom" 
	pageLinks="5" 
	scrollable="true"
	scrollWidth="100%" 
	first="#{listAddresses.first}"
	styleClass="white-footer dstable without-checkbox">

### Expected behavior

If scrolling horizontally in a dataTable the header should scroll too.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.6

### JSF implementation

MyFaces

### JSF version

4.0.2

### Java version

17

**Comment by wlhUser** [comment]
See #11491

**Comment by melloware** [comment]
I will try and release 13.0.7 today with this fix and some others.

**Comment by DadApple9** [comment]
Top! Thank you

**Comment by melloware** [comment]
13.0.7 is in Maven Central now if you want to update and try it.

**Comment by DadApple9** [comment]
Thank you. It works. :-)
