### ISSUE TITLE
DatePicker's time falls into an infinitive loop

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#11545]
### Describe the bug

It is possible to fall into an infinitive loop of time change event when you press a mouse button on one of time picker's buttons and without releasing it after some time mouse leave a cursor out of it and then release mouse button. Details are on the movie I added
Movie:
[PrimeFaces.zip](https://github.com/primefaces/primefaces/files/14461163/PrimeFaces.zip)

I know that it is a bug for latest Firefox. Don't know about other browsers

**EDIT**: Seems cross browser bug. I have just reproduced it on Chrome 122.0.6261.69

### Reproducer
[PrimeFaces.zip](https://github.com/primefaces/primefaces/files/14461337/PrimeFaces.zip)

### Expected behavior

There shouldn't be any loop

### PrimeFaces edition

Community

### PrimeFaces version

13.0.6

### Theme

any

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

Firefox 123.0 64bit, Chrome

**Comment by melloware** [comment]
Confirmed.  in Chrome and Firefox as well.  Let me look.

**Comment by melloware** [comment]
@majkers can you test this version and see if you can make it happen?
[pf-11545.zip](https://github.com/primefaces/primefaces/files/14462333/pf-11545.zip)

It is already monkeypatched in test.js and it seems I couldn't make it happen but would like a second set of testing.

**Comment by majkers** [comment]
Unfortunatelly still exists...

[test2.zip](https://github.com/primefaces/primefaces/files/14462434/test2.zip)

**Comment by majkers** [comment]
Unfortunatelly still exists. I will try to record screen for you

**Comment by melloware** [comment]
ok i made the change from mouseleave to mouseout.

which I did not really understand the different until i saw this example:
https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_event_mouseleave_mouseout#:~:text=float%3Aright%22%3E-,The%20mouseout%20event%20triggers%20when%20the%20mouse%20pointer%20leaves%20any,pointer%20leaves%20the%20selected%20element.

What I think was happening was depending on WHERE you clicked in the button and left the `mouseleave` was not always firing but the `mouseout` seems to always fire for me.

**Comment by melloware** [comment]
if you want to add some `console.log` to debug the code is here in that monkeypatch.

```js
                .on('mouseout.datePicker-time', timeSelector, null, function (event) {
                    if ($this.timePickerTimer) {
                        $this.onTimePickerElementMouseUp(event);
                    }
                })
```

**Comment by majkers** [comment]
[Test2.zip](https://github.com/primefaces/primefaces/files/14462499/Test2.zip)

**Comment by majkers** [comment]
I've just uploaded video with monkeypatch from your post :(

**Comment by melloware** [comment]
ok can you add some console.log in the monkeypatch and see why the `mouseout` is not firing?

**Comment by majkers** [comment]
OK

**Comment by melloware** [comment]
I also noticed in your video it took a LOT of tries to make it happen now with `mouseout` is that correct?

**Comment by majkers** [comment]
Yes because I don't know exactly how to reproduce it step by step

**Comment by majkers** [comment]
[test3.zip](https://github.com/primefaces/primefaces/files/14462567/test3.zip)

Added logging in mouseout

**Comment by melloware** [comment]
I am not sure if we can make it much better than `mouseout` as i don't know what else we could do to tell that. It seems to be counting on the browser events to properly fire and its clearly not?

**Comment by melloware** [comment]
I submitted a PR but i am all ears on how to make it bulletproof....

**Comment by majkers** [comment]
ok. In case of any updates let me know here

**Comment by majkers** [comment]
@melloware actually I am not 100% satisfied with you closing this issue without a proper fix... The issue still exists. I upoloaded a video prooving it. Maybe it is not an event issue but the timer's? Since there is a if statement in event listener? Maybe timer is not being created somewhere before?

**Comment by melloware** [comment]
@majker the code is right there for you to debug. It does mouse enter and mouse out. There is no other code?  What else can we do besides mouse out?  I am more than happy for your to debug and provide a PR

**Comment by melloware** [comment]
I will reopen if you provide a fix but honestly this bug is difficult to reproduce. I see it in your video but I tried 100 times in a row and could not reproduce it.
