### ISSUE TITLE
TabView/AccordionPanel: Introduce TabEvent#index

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11553]
### Discussed in https://github.com/orgs/primefaces/discussions/1320

<div type='discussions-op-text'>

<sup>Originally posted by **DaBe1812** February 28, 2024</sup>
I have a dynamic TabView getting it's content from a List<>.
Opening new tabs works just fine, switching between those tabs updates the ActiveIndex correctly.
Let's pretend I have 6 open tabs, so the last index ist 5. When I close tab no 2 then the last index stays 5 switching the tabs skips TabIndex 1. When I want to clear my List by closing tabs this is a problem becase the indexes in the list differ from the indexes of the tabs.
Is there a way to update the tab indexes or a workaround for this issue?</div>

Workaround from Raptser:

```java
public void onTabClose(TabCloseEvent<?> event) {
      TabView tv = (TabView) event.getComponent();
      int activeIndex = Integer.parseInt(event.getFacesContext().getExternalContext().getRequestParameterMap().get(tv.getClientId() + "_tabindex"));

      FacesMessage msg = new FacesMessage("Closed", "Closed Tab. Active Tab " + activeIndex);
      FacesContext.getCurrentInstance().addMessage(null, msg);
}

```

**Comment by melloware** [comment]
it looks like AccordionPanel and TabView share similar code around how it handles this TabClose event so the bug is probably in both.

**Comment by jepsar** [comment]
Index is not great to indicate a tab when the are dynamic. Using an ID would be better.

**Comment by melloware** [comment]
@Rapster where did we end up on this?

**Comment by Rapster** [comment]
Oh I thought it's been merged but turns out, I deleted it instead (whenever I cleaned up all my local branches)

**Comment by melloware** [comment]
Ok I was wondering why you deleted it. Thanks for fixing.
