### ISSUE TITLE
DefaultCommand: ajax event from source not triggered on blur

### ISSUE THREAD

**Issue by haraleib** [primefaces/primefaces#11551]
### Describe the bug

Already described in https://github.com/primefaces/primefaces/issues/11537 in _Case 2_

- If there is a p:inputText with p:ajax event="blur" or "change"
- a commandButton
- a defaultCommand pointing to the commandButton Action
- and if you type something in the inputText and press enter

### Behaviour
The commandButton is triggered. The event from the inputText is not triggered.

### Reproducer

[playground-primefaces.zip](https://github.com/primefaces/primefaces/files/14451240/playground-primefaces.zip)

### Expected behavior

I could imagine that the expected behaviour would be, that the execution order is the same like when the button is clicked with the mouse.

I think this would lead to something like:
- Enter ist pressed
- Button gets focus??
- The event of the inputText is triggered
- The event of the commandButton is triggered

### PrimeFaces edition

None

### PrimeFaces version

10.0.0

### JSF implementation

MyFaces

### JSF version

2.3.6

### Java version

11

**Comment by melloware** [comment]
Try this version:
[pf-11551.zip](https://github.com/primefaces/primefaces/files/14465551/pf-11551.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

**Comment by melloware** [comment]
That makes sense. Just remove that re focus line...

**Comment by haraleib** [comment]
Thank you it is working.

**Comment by melloware** [comment]
Awesome I updated my PR to remove that line as well.
