### ISSUE TITLE
DataTable: Frozen Col with virtualscroll does not scroll any longer since 13.0.7

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#11555]
### Describe the bug

Scrolling vertically in a data table with virtualscroll and frozen columns, lets the frozen col disappear.

Reproducer:
[reproducer_20240304.zip](https://github.com/primefaces/primefaces/files/14478235/reproducer_20240304.zip)

Take the upper table in the reproducer.
- Scroll down until a virtual load is performed
- Afterwards the frozen col is gone

![grafik](https://github.com/primefaces/primefaces/assets/47218021/35033208-bcc7-4726-9b5e-f8160be4465f)

The reason i s probably #11491 File datatable.frozen.js. I suppose the line 'scrollTop=$this.scrollBody.scrollTop();' is missing, which leads later to frozenBody.scrollTop bein set to 'undefined'.

![grafik](https://github.com/primefaces/primefaces/assets/47218021/859438ef-8ddc-4487-b0e5-7927a205b54b)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.7

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

All

**Comment by melloware** [comment]
PR submitted.
