### ISSUE TITLE
Provide a JS util to overwrite a local specific setting like firstDayOfWeek for all locales on the current view

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11569]
one of my customers have a production line in a specific country and they have the requiremenent to set the firstDayOfWeek for all locales, indepedent of the current browser locale

in theory they could overwrite all via:
```
PrimeFaces.locales["en"].firstDayOfWeek = 0
PrimeFaces.locales["de"].firstDayOfWeek = 0
PrimeFaces.locales["fr"].firstDayOfWeek = 0
....
```

but thats just to much overhead

i will introduce a util method like:
```
PrimeFaces.overwriteAllLocalesValue('firstDayOfWeek', 0);
```

this will loop all PrimeFaces.locales and overwrite the value in the current view.

any idea for a better method name?

**Comment by melloware** [comment]
Sounds good to me the only other name u can think of if "forceLocaleValue" but not sure it's any better

**Comment by jepsar** [comment]
`setGlobalLocaleValue`?
