### ISSUE TITLE
DefaultCommand: dataTable with filterEvent="keydown" triggers defaultCommand on enter

### ISSUE THREAD

**Issue by haraleib** [primefaces/primefaces#11561]
### Describe the bug

Already mentioned here https://github.com/primefaces/primefaces/issues/11537#issuecomment-1976438209
Despite the fix of https://github.com/primefaces/primefaces/issues/11537, there is furthermore the problem that if,

- I have a dataTable with filterEvent="keydown"
- There is a defaultCommand pointing to a commandButton
- I type something in the column header filter
- I press enter
... The defaultCommand and triggered

Just for completeness, another related issue is https://github.com/primefaces/primefaces/issues/11551#issuecomment-1976255661

### Expected behavior

I think the defaultCommand should never be triggered within a dataTable filter field

### PrimeFaces edition

None

### PrimeFaces version

10.0.0

### JSF implementation

Mojarra

### JSF version

2.3.6

### Java version

11

**Comment by melloware** [comment]
Thanks I will take a look today.

**Comment by haraleib** [comment]
Many thanks!

**Comment by melloware** [comment]
OK try this MonkeyPatch...

```js
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.bindFilterEvent: function(filter) {
        var $this = this;
        var filterEventName = this.cfg.filterEvent + '.dataTable';

        filter.on(filterEventName, function(e) {
            if (e.key && PrimeFaces.utils.ignoreFilterKey(e)) {
                return;
            }

            //prevent form submit on enter key
            if (e.key === 'Enter') {
                e.preventDefault();
                e.stopPropagation();
            }

            if ($this.filterTimeout) {
                clearTimeout($this.filterTimeout);
            }

            $this.filterTimeout = setTimeout(function() {
                    $this.filter();
                    $this.filterTimeout = null;
                },
                $this.cfg.filterDelay);
        });
    }
};
```

**Comment by haraleib** [comment]
The fix seems not to work. The defaultCommand is triggered.
Tried it for dataTable and a little bit adapted with treeTable.
Adaption for treeTable:  `var filterEventName = this.cfg.filterEvent + '.treeTable';`
Both not working.

**Comment by haraleib** [comment]
Tested it for p:dataTable at seems to work. Thank you @melloware !

**Comment by haraleib** [comment]
> The fix seems not to work. The defaultCommand is triggered. Tried it for dataTable and a little bit adapted with treeTable. Adaption for treeTable: `var filterEventName = this.cfg.filterEvent + '.treeTable';` Both not working.

Have to clarify this. Not the defaultCommand, but the command from the source is triggered. But nevertheless, it works now.
