### ISSUE TITLE
refactor to using jQuery .noConflict() 

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#1157]
I'm curious if PrimeFaces is interested in switching to using jQuery in a noConflict way. Afaik, the $ will still be available if not defined before by another framework. I'm creating an issue for this so it is either done or when not done, it is 'for the record'.

**Comment by tandraschko** [comment]
@cagataycivici  AFAIR we decided some years ago to NOT using jQuery instead $, right?

**Comment by kukel** [comment]
Oh, could also be a 'pfJQ'... ;-)
