### ISSUE TITLE
Dialog: Dialog extends beyond viewport after resizing due to AJAX update

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#11578]
### Describe the bug

* Dialog is open
* Dialog is completely inside viewport
* AJAX update happens
* More components are rendered, dialog does not fit anymore
* The lower bound of the dialog including the lower end of the scrollbar is outside of the viewport and cannot be reached

I hope it's not related to https://github.com/primefaces/primefaces/issues/11476.

### Reproducer

Here is a reproducer, just click the button to see the problem: 
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/14510192/primefaces-test.zip)

I also tested using 14.0.0-SNAPSHOT, same behavior.

### Expected behavior

The dialog remains inside of the viewport and can be scrolled normally.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.7

### JSF implementation

All

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
@mkomko it is because this is a floating dialog it is not triggering a browser `resize` or `scroll`.  I fixed your example with 
 `oncomplete="$(window).trigger('resize')"`


```xml
<p:commandButton value="Toggle Textarea" action="#{testView.toggleInputTextareaRendered}"
                             update="@(.update-class)" oncomplete="$(window).trigger('resize')"/>
```

**Comment by mkomko** [comment]
@melloware Thank you! Can it be fixed in PrimeFaces? Because we'd have to add that to A LOT of `p:ajax` tags.

**Comment by melloware** [comment]
From looking i am not sure if there is an elegant place to do this.  Right now we call `fitViewPort` only when the viewport hsa changed aka Window resized.  Your code is juts resizing the dialog not the viewport but let me look.

**Comment by melloware** [comment]
MonkeyPatched version:
[pf-11578.zip](https://github.com/primefaces/primefaces/files/14512691/pf-11578.zip)

Give it a shot.

**Comment by melloware** [comment]
@mkomko get a chance to test this MonkeyPatch?

**Comment by melloware** [comment]
weird OK let me know what you find out but basically that ResizeObserver watches the size of the dialog DIV so if that DIV changes size it should trigger the call.

**Comment by mkomko** [comment]
@melloware I figured out why your MonkeyPatch doesn't work in our application: We have the following in our CSS, because we don't like the look of dialogs touching the edges of the viewport:
```css
body .ui-dialog {
    max-height: 95vh !important;
    max-width: 95vw !important;
}
```

What do you think? 😉

**Comment by melloware** [comment]
@mkomko if I add this CSS to my reproducer will it cause it not to work?

**Comment by mkomko** [comment]
Yes.

**Comment by melloware** [comment]
Maybe I am doing something wrong but its still working for me...
[pf-11578-3.zip](https://github.com/primefaces/primefaces/files/14760036/pf-11578-3.zip)

**Comment by mkomko** [comment]
When you scroll down the bottom of the scrollbar is missing:
![image](https://github.com/primefaces/primefaces/assets/8350714/cb05d176-9223-4191-99df-abf351146706)

**Comment by melloware** [comment]
Oh your original issue here was the dialog was not re-centering itself when switching with AJAX and just updating the guts.  This other issue sounds like a different issue because for me the dialog is now centering itself on each change no?

**Comment by melloware** [comment]
also in Firefox the scrollbar is still there for me...

![image](https://github.com/primefaces/primefaces/assets/4399574/ac2231e1-99df-486e-86f0-fa9689e7c92c)

**Comment by melloware** [comment]
Actually working for me in Chrome and Firefox just fine and scrollbar is there...

**Comment by mkomko** [comment]
Our problem is that the dialog content expands dynamically and the bottom part of the content is not visible in the dialog and cannot be scrolled to, even when resizing the dialog.

Why do your scrollbars look different, are you on Linux? I am on the latest versions of Chrome and Firefox for Windows and the top part of the dialog looks like this:

![image](https://github.com/primefaces/primefaces/assets/8350714/f99f363a-a4cd-4391-a3ff-c802bf67f20c)

And the bottom part looks like this:

![image](https://github.com/primefaces/primefaces/assets/8350714/f540424c-d696-419d-9eaa-f98b40d62106)

I'm just running the reproducer you just posted and clicking the toggle button.

**Comment by melloware** [comment]
Windows 11 latest Chrome latest Firefox

![image](https://github.com/primefaces/primefaces/assets/4399574/e37c8701-0672-495b-a2d5-4ac75141121b)

**Comment by melloware** [comment]
Oh so the down arrow missing is your issue?

**Comment by melloware** [comment]
Its because the dialog-content gets a max-height.

![image](https://github.com/primefaces/primefaces/assets/4399574/e3754817-0287-48e3-b2b8-3abb84ecc135)

So you have your `dialog` itself constrained to 95vh but the component controls the max height in pixels of the dialog content and these two numbers appear to be causing your issue.

**Comment by mkomko** [comment]
Here's a screenshot from our actual application:
![image](https://github.com/primefaces/primefaces/assets/8350714/6f8c896b-ee79-4d72-9315-b76b15da402f)
The user basically doesn't know if there's anything relevant missing or not.

**Comment by melloware** [comment]
You have conflicting max heights of the dialog and the content....

**Comment by mkomko** [comment]
Ah, that's the problem. Makes sense!
But the max-height of the content is calculated by PF? Can we influence it?

**Comment by melloware** [comment]
see..

```js
fitViewport: function() {
        var windowHeight = $(window).height();

        var margin = this.jq.outerHeight(true) - this.jq.outerHeight();
        var headerHeight = this.titlebar.outerHeight(true);
        var contentPadding = this.content.innerHeight() - this.content.height();
        var footerHeight = this.footer.outerHeight(true) || 0;

        var maxHeight = windowHeight - (margin + headerHeight + contentPadding + footerHeight);

        this.content.css('max-height', maxHeight + 'px');

        if(this.cfg.hasIframe) {
            this.content.children('iframe').css('max-height', maxHeight + 'px');
        }
    },
```

That is the code doing it in dialog.js

**Comment by mkomko** [comment]
So we could maybe overwrite this function and take 95% of the viewport height instead of the windowHeight? Would we overwrite it like this?
```javascript
if (PrimeFaces.widget.Dialog) {
    PrimeFaces.widget.Dialog.prototype.fitViewport= function () {
```

**Comment by melloware** [comment]
Yep try this monkeypatch: 

```js
	PrimeFaces.widget.Dialog.prototype.fitViewport = function() {
        var windowHeight = $(window).height() * 0.95;
        var margin = this.jq.outerHeight(true) - this.jq.outerHeight();
        var headerHeight = this.titlebar.outerHeight(true);
        var contentPadding = this.content.innerHeight() - this.content.height();
        var footerHeight = this.footer.outerHeight(true) || 0;

        var maxHeight = windowHeight - (margin + headerHeight + contentPadding + footerHeight);

        this.content.css('max-height', maxHeight + 'px');

        if(this.cfg.hasIframe) {
            this.content.children('iframe').css('max-height', maxHeight + 'px');
        }
    }
```

I patched the whole zip if you want to try it...

[pf-11578-4.zip](https://github.com/primefaces/primefaces/files/14760918/pf-11578-4.zip)

**Comment by mkomko** [comment]
Yep, that fixes it! Beautiful!
Now I feel really bad that this issue turned into a support thread because of our customization. I apologize and once again marvel at your helpfulness.

Thank you so much!

I don't know if your PR is still relevant/an improvement?

**Comment by melloware** [comment]
well the PR still needs to fix your original issue where if it the dialog is resized internally it was not fitting to viewport so yeah i think the PR is still valid.

**Comment by melloware** [comment]
@mkomko saw this too which jQuery UI says they probably won't fix: https://github.com/jquery/jquery-ui/issues/2277
