### ISSUE TITLE
Primefaces 5.3: update on rowEdit from dataTable nested within p:tab within p:accordionPanel mangles dataTable

### ISSUE THREAD

**Issue by webelcomau** [primefaces/primefaces#1158]
Platform: Primefaces 5.3 (community edition); Mojarra: 2.2.7; Glassfish4.1; NetBeans8.1beta; JDK1.7

Browser: have reproduced the problem in both Safari and Chrome on Mac OS X

<img width="500" alt="greensoft-bug-node-4207-primefaces-datatable-within-tab-accordion-before" src="https://cloud.githubusercontent.com/assets/7203231/13101614/27c8106a-d59c-11e5-82c6-0cef35ab90a5.png">

<img width="500" alt="greensoft-bug-node-4207-primefaces-datatable-within-tab-accordion-after" src="https://cloud.githubusercontent.com/assets/7203231/13101616/2f0b571a-d59c-11e5-9c32-b0ee7f31ab89.png">

The aim is for values from an expert system to propagate back up a tree of nested p:accordion/p:tab combinations, with the results of expert system calculations performed over data in an enclosed/nested p:dataTable to be shown in the title (either using 'title' attribute or a title facet) of each p:tab.

When a dataTable rowEdit is performed on some values of an (in the demo below fake) entity, and the parent (or any ancestor) p:accordionPanel is updated, the nested p:dataTable is mangled until another p:tab within a p:accordionPanel is selected, and then the original p:tab (with the p:dataTable) is selected again.

Note I have  p:accordionPanel with dynamic="true" and cache="false".

```
<p:accordionPanel id="accordionOuter" cache="false" dynamic="true">
  <p:tab id="option1and2">
    <f:facet name="title" id="option1and2_title">
      Outer: <h:outputText value="Option1 and Option2: #{options.option1and2}"/>; <h:outputText value="Sum of integer values from entities: #{viewBean.sumValInt}"/> 
    </f:facet>
      <p:accordionPanel id="accordionInner" cache="false" dynamic="true"  activeIndex="null">
        <p:tab title="Inner: Option1: #{options.option1}">
           ...
      </p:tab >
       <p:tab title="Inner: Option2: #{options.option2}">
           ...
      <p:tab title="DataTable with row edit: Sum of integer values from entities: #{viewBean.sumValInt}">
         <h:panelGrid columns="1">                                
                            <h:outputText 
                                id="echo_sum_ints"
                                value="Sum of ints: #{viewBean.sumValInt}"/>

                            <p:dataTable 
                                id="dataTable" var="e" value="#{viewBean.entities}" editable="true">
                                <p:ajax
                                    event="rowEdit" 
                                    listener="#{viewBean.updateRow}" 
                                    update=":form:accordionOuter"
                                    />
                                <p:column headerText="Name">
                                    <h:outputText value="#{e.name}"/>
                                </p:column>
                                <p:column headerText="ValInt">
                                    <p:cellEditor>
                                        <f:facet name="output">
                                            <h:outputText value="#{e.valInt}"/>
                                        </f:facet>
                                        <f:facet name="input">
                                            <p:inputText value="#{e.valInt}"/>
                                        </f:facet>
                                    </p:cellEditor>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        EDIT !
                                    </f:facet>
                                    <p:rowEditor/>                
                                </p:column>
                            </p:dataTable>
                        </h:panelGrid>
                    </p:tab>
                </p:accordionPanel>
            </p:tab>
        </p:accordionPanel>
```

**Comment by cagataycivici** [comment]
It is not possible to update a container that contains the datatable at rowEdit as custom output is generated in row edit, this is also same with page, sort. Well known workaround is doing a remote command.

```
<p:remoteCommand name="updateAccordion()" update="update="accordionOuter"" />

<p:accordion
  <p:dataTable
      <p:ajax
                                    event="rowEdit" 
                                    listener="#{viewBean.updateRow}" 
                                    oncomplete="updateAccordion()"
                                    />
```

**Comment by webelcomau** [comment]
@cagataycivici  Sorry I missed your reply, by chance I already found a similar workaround using p:remoteCommand (and p:outputPanel) on Stackoverflow at http://stackoverflow.com/questions/19548838/updating-entire-pdatatable-on-complete-of-pajax-event-celledit

But it only works (the dataTable is no longer mangled on save of a rowEdit) when validation succeeds, otherwise the dataTable mangling still happens, and it is difficult to recover (without clicking on a parent accordionPanel tab header); after the dataTable is mangled, clicking on the rowEdit 'x' for example does not take.

I appreciate your feedback and workaround in this case, but it is not a completely satisfactory workaround. 

I noticed you've marked in as wontfix; so does that mean I should simply discard the otherwise extremely useful strategy of using editable dataTables inside a p:accordionPanel and p:tab ?

**Comment by webelcomau** [comment]
I wrote yesterday:

>  But it only works (the dataTable is no longer mangled on save of a rowEdit) when validation succeeds, otherwise the dataTable mangling still happens ...

The mangling on failed validation only happens if there is an update in both the p:ajax within the p:dataTable and the p:remoteCommand (see also [this Primefaces community forum example](http://forum.primefaces.org/viewtopic.php?f=3&t=44490)).

If the update is removed from the p:ajax (and one relies only on the p:remoteCommand to update the parent accordionPanel) then the rowEdit save works as desired when validation fails too.

I now agree that the p:remoteCommand workaround is sufficient.

_BTW I don't find the label 'wontfix' very clear for such cases; there is definitely a design problem (it is moot whether one calls it an actual bug), it would be handy to have a label 'workaround exists' or similar._

**Comment by webelcomau** [comment]
May I suggest that if a p:remoteCommand update is needed as a workaround to make row editing of a p:dataTable within a p:accordionPanel and p:tab usable (work as expected without mangling) that an example of this be provided in the main Primefaces Guide/Manual, or at least that an example be provided on the Primefaces showcase.
