### ISSUE TITLE
Timeline: some items are hidden in some usecases

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#11599]
### Describe the bug

In some usecases timeline-items are not show until zooming out.

Look at the screen-recording:
https://github.com/primefaces/primefaces/assets/10461942/14c2bb17-ec86-4291-94f3-6fa09adf1aa4

Checking one of both checkboxes still works. After checking both Max 1 and Max 2 are missing until you scroll out.
From my feeling this may be a bug within https://visjs.github.io/vis-timeline/docs/timeline/.

### Reproducer

https://github.com/christophs78/primefaces-test/tree/timeline_missing_entries

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-RC1

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Edge/Chrome

**Comment by melloware** [comment]
There are a bunch of open PR's https://github.com/visjs/vis-timeline/pulls

The developer apologizes but he said he basically has no time for VisTimeline so not sure when any of those patches will be applied.  Might be worth applying some of them to see if it fixes your issues.

**Comment by christophs78** [comment]
I looked through the vis-timeline pulls. Nothing seem´s to fit to this issue.
There´s a small chance to find some point in the future where i´m realy motiviated to dig into there code-base. Otherwise (most probably) this will be a "won´t fix".

**Comment by melloware** [comment]
Going to close this for now as it's a third party issue!
