### ISSUE TITLE
InputMask: Problem escaping characters and validateMask

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#11590]
### Describe the bug

The next example is not working if validateMask is true:
```xml
<p:inputMask value="#{bean.value}" mask="\9.99" validateMask="true" required="true"/>
```
The submitted value is set to empty because the server side validation doesn't support escaping:
https://github.com/primefaces/primefaces/blob/d678b4ce99a6a8f67b340297ac81b1b40c1fb2bf/primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java#L102

To escape a character is supported by the plugin: https://github.com/RobinHerbots/Inputmask/issues/2601

### Reproducer

[primefaces-escape-character-inputmask.zip](https://github.com/primefaces/primefaces/files/14525122/primefaces-escape-character-inputmask.zip)

1. Run the project `mvn clean jetty:run -Pmojarra23`
2. Open http://localhost:8080/primefaces-test/
3. Enter a value and click first button, value is submitted without error when validateMask is false.
4. Enter a value and click second button, validation on server side fails if validateMask is true.

### Expected behavior

The entered value shouldn't fail the validation on server side.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.7

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
Good catch and test case!
