### ISSUE TITLE
DataTable: Add column visible flag information to FilterMeta

### ISSUE THREAD

**Issue by weissreto** [primefaces/primefaces#11606]
### Description

It would be nice to have the information if a column is visible on the FilterMeta in the LazyDataModel of the DataTable component. 
Sometimes the visible information influences the database query needed to load the data for the data table. E.g. the data of the column is read by an additional join to a foreign table. If the column is not visible the join is not needed leading to a better query performance. Also, fewer rows may need to be loaded because if the column is not visible, rows that only differ in the invisible column can be merged.

### Describe the solution you would like

Add a new method to FilterMeta called isVisible():boolean

### Additional context

We have a lot of data tables with business information that have a lot of columns. The information in some columns is only interesting for some users. Therefore some columns are not visible for most users.

**Comment by melloware** [comment]
I changed this to Discussion label.  I am not sure visible belongs in the Filter Meta as it has nothing to do with filtering.  If it does go in FilterMeta then it would also have to go in SortMeta but to me that doesn't make any sense.

My guess is you care about the visibility so you can not sort if its `visible="false"`???

**Comment by jepsar** [comment]
Can't you just read the column info from the data table component?

**Comment by melloware** [comment]
Correct.

**Comment by weissreto** [comment]
I can confirm that the workaround above works. 
However, we would appreciate a more convenient method. E.g., 
`load(int first, int pageSize, List<ColumnMeta> columns);`
and
ColumnMeta.getField() : String
ColumnMeta.isVisible() : boolean
ColumnMeta.getSortMeta() : SortMeta
ColumnMeta.getFilterMeta() : FilterMeta

**Comment by Rapster** [comment]
I understand the reason for it but as mentionned here https://github.com/primefaces/primefaces/issues/11606#issuecomment-1988315909) it feels out of place and the "workaround" given here https://github.com/primefaces/primefaces/issues/11606#issuecomment-1988470180 is IMO the way to go for now

Tough, I did consider in the the past something like you mentionned here https://github.com/primefaces/primefaces/issues/11606#issuecomment-1991465914, that would save us some code duplication, ColumnMeta would serve a better purpose and would solve issues like this one. I have to think about it, 

But for now, -1 for this

**Comment by melloware** [comment]
My -1 for now as well. I do think that using ColumnMeta would be cool but not anytime soon as we have refactored lazy datatable recently and breaking the API again is going to just frustrate upgraders.

**Comment by Rapster** [comment]
Also very true

**Comment by weissreto** [comment]
> My -1 for now as well. I do think that using ColumnMeta would be cool but not anytime soon as we have refactored lazy datatable recently and breaking the API again is going to just frustrate upgraders.

I can understand that. We also suffered from the API change during our last PF upgrade. 
I'm fine with this decision, since we have a solution to our problem.

Thanks for the discussion and the hint about the solution,
