### ISSUE TITLE
Deselection issue in p:selectManyButton

### ISSUE THREAD

**Issue by pranav-malanthra** [primefaces/primefaces#1163]
In 5.3 i am not able to deselect p:selectManyButton using p:ajax event="change". But using keyboard tab key (and enter key) is working fine. 
sample code:
    `<p:selectManyButton value="#{testBean.selectedOptions}" >
    <f:selectItem itemLabel="b" itemValue="b" />
            <f:selectItem itemLabel="u" itemValue="u" />
            <f:selectItem itemLabel="i" itemValue="i" />
            <p:ajax event="change" update="@this"/>
    </p:selectManyButton>
    <p:commandButton value="Submit" update="display"/>
    <p:dataList id="display" value="#{testBean.selectedOptions}" var="font" emptyMessage="No fonts selected">
            <h:outputText value="#{font}" style="font-weight: bold" />
        </p:dataList>`

**Comment by pranav-malanthra** [comment]
#771

**Comment by kukel** [comment]
Next time please format your code AND search the issuelist: https://github.com/primefaces/primefaces/issues/790. Already FIXED in 5.3.1

**Comment by sudheerj** [comment]
Try with elite 5.3.x releases as it already fixed in 5.3.1.
