### ISSUE TITLE
DatePicker: disable dates when lazy model is used on Ajax

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#11644]
### Description

We have a lazy model where we set which dates should be disabled. This takes a short amount of time to load. During load the new month is immediately shown and all dates are enabled.

### Describe the solution you would like

I would prefer to show them all disabled until the model was loaded. Not sure if this should be the default on the lazy model though.

**Comment by melloware** [comment]
I feel like for lazy mode you are right dates should be disabled until we are told they are enabled. It should be the default.

**Comment by jepsar** [comment]
This one is tricky. I would like to avoid touching `0-datepicker.js` if possible. I think it will be easier to have a blockUI like div to show during loading.

**Comment by melloware** [comment]
@jepsar why not just wrap the panel in `ui-state-disabled` until the first lazy is returned and then remove that class?

**Comment by melloware** [comment]
I put this in 14.0.0 its small enough change
