### ISSUE TITLE
Schedule: AllDay showing wrong end date

### ISSUE THREAD

**Issue by Grwld** [primefaces/primefaces#1164]
Adding an entry with start date e.g. 07/02/2016 00:00 and end date 08/02/2016 23:59 and setting the All Day checkbox the entry is shown only for 07/02/2016 on the month overview.
If the All Day checkbox is unchecked, both days are shown.
![schedule](https://cloud.githubusercontent.com/assets/17312261/13143791/9aa76d06-d646-11e5-98d5-5e67788d54dc.png)

Can be seen at Primefaces Showcase
I'm using
PF: 5.3.7
MyFaces: 2.2.9

**Comment by kukel** [comment]
check what happens with plain jquery fullcalendar. Might be a bug in there...OR it might be as designed...

**Comment by Grwld** [comment]
I don't think it is as designed. It was working in PF 4.0.
On http://fullcalendar.io I can't see any input to generate or edit entries, just drag-n-drop

**Comment by Grwld** [comment]
Just checked it with fullcalendar alone. Seems to be a bug in there:
                {
                    title: 'All Day Event 1',
                    start: '2016-01-01',
                },
                {
                    title: 'All Day Event 2 ',
                    start: '2016-01-01',
                    end: '2016-01-01',
                },
                {
                    title: 'All Day Event 3',
                    start: '2016-01-01',
                    end: '2016-01-02',
                }
are all the same 1-Day events, when not setting a time.
But it worked in PF4. Is there a way to use the version of fullcalendar that PF4 used?

**Comment by kukel** [comment]
not easily... no...

**Comment by tandraschko** [comment]
@OBreidenbach something you would like to check?:)

**Comment by OBreidenbach** [comment]
It is the way the [FullCalendar](https://fullcalendar.io) is handling allDay events. It just ignores the time part of the event. 
There is already a ticket for this, https://github.com/fullcalendar/fullcalendar/issues/2985.
Unfortunately it is still open. Maybe visiting and voting :+1: for it helps to get more attention to it.

As a workaround you can set the end time to 0:00 of the next day or do not declare it as allDay event.

**Comment by melloware** [comment]
Since this is a FullCalendar issue that is open an @OBreidenbach has provided a workaround by setting end time to `00:00` there is nothing for PF to do here...
