### ISSUE TITLE
UIData: split in 2 classes and rename as PrimeUIData

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#11640]
### Description

Current `UIData` is a mix bag of Mojarra, MyFaces and PF impl. It gets tough to follow how PF impl is different from JSF impl and why... 

### Describe the solution you would like

Split UIData into 2 classes and rename UIData as PrimeUIData

### Additional context

Also this might help to port fixes from Mojarra

**Comment by melloware** [comment]
I like this idea.
