### ISSUE TITLE
Tabview scroll changes tab in mobile mode

### ISSUE THREAD

**Issue by omerogrek** [primefaces/primefaces#11642]
### Describe the bug

When there is implemented tabview with more than two tabs, scrolling inside a tab to see right side of tab changes selected tab.  

### Reproducer

https://www.primefaces.org/showcase/ui/panel/tabView.xhtml?jfwid=b95aa you can check the demo page of primefaces. When scrolling from tab1 to tab2, it changes the selected tab. 

### Expected behavior

Scrolling to tab to see right side of the tab should allowed and not change the tab itself.

### PrimeFaces edition

None

### PrimeFaces version

12.0.3

### JSF implementation

All

### JSF version

2.2.11

### Java version

8

**Comment by melloware** [comment]
This is a feature on mobile mode that "swipe" is detected to switch tabs.  If you don't want this behavior simply disable it with `touchable="false"`

See the docs: https://primefaces.github.io/primefaces/14_0_0/#/components/tabview?id=tabview
