### ISSUE TITLE
ColorPicker Arrows Not Moving to Selected Color 

### ISSUE THREAD

**Issue by bengisubilgin** [primefaces/primefaces#11643]
### Describe the bug

When attempting to select a color using the ColorPicker component in PrimeFaces, the arrows indicating the selected color's position do not move to the selected color. Although it is possible to choose a color, the arrows remain static and do not reflect the chosen color's position accurately.

### Reproducer

https://www.primefaces.org/showcase-v8/ui/input/colorPicker.xhtml

### Expected behavior

Upon selecting a color from the ColorPicker, the arrows should dynamically move to indicate the selected color's position within the color spectrum. This behavior ensures users can visually confirm their chosen color selection accurately.

### PrimeFaces edition

None

### PrimeFaces version

12.0.4

### JSF implementation

All

### JSF version

2.2.11

### Java version

8

**Comment by jepsar** [comment]
That's the legacy color picker which is not supported by the community. See https://github.com/primefaces/primefaces?tab=readme-ov-file#community--elite--pro

**Comment by melloware** [comment]
Agree with @jepsar the new color picker in 13 is fully A11y and ARIA compliant.
