### ISSUE TITLE
Core: ErrorPages of different web.xml locations and programmatically added ErrorPages

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#11641]
Reported By PRO User;
> Primefaces does not respect ErrorPages of different web.xml locations and programmatically added ErrorPages in AjaxRequest when no p:ajaxExpetionHanlder is defined

> This is because Primefaces assumes that the web.xml is at a specific place here:
org.primefaces.config.WebXmlParser.getErrorPages(FacesContext)

>Called from here:
org.primefaces.config.PrimeConfiguration.PrimeConfiguration(FacesContext, PrimeEnvironment)

>E.g. in our Tomcat we add programmatically ErrorPages to the web application context. We also have a global web.xml which serves multiple web applications.

**Comment by tandraschko** [comment]
we need a sample project here
im not sure there is a API in servlet to receive error pages, therefore we parse the xml

**Comment by melloware** [comment]
Agreed and I don't think OmniFaces handles this scenario either.

**Comment by melloware** [comment]
I totally agree @BalusC we use web fragment JAR of re-usable components and pages this is the correct solution to the problem @mertsincan .
