### ISSUE TITLE
DataTable: Dragged column to the right cannot be resized

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#11650]
### Describe the bug

Hi, a dragged column to the right should display the column resizer only if not the last one, but the code does the opposite. The column resizer is hidden on the dragged column if there exists right sibling.

```
datatable.js
4594                //drop right
4595                if(dropLocation > 0) {
4596                    if($this.cfg.resizableColumns) {
4597                        if(droppedColumnHeader.next().length) { // THIS CONDITION SHOULD BE NEGATED, after that it means the dragged column is the last, than column resizer should be hidden
4598                            droppedColumnHeader.children('span.ui-column-resizer').show();
4599                            draggedColumnHeader.children('span.ui-column-resizer').hide();
4600                        }
4601                    }
```

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.5

### JSF implementation

Mojarra

### JSF version

2.3.20

### Java version

11

**Comment by melloware** [comment]
@vonnai is this in RTL or LTR mode?  It is odd its doin `next()` when in RTL mode it should be `prev()` right?

**Comment by melloware** [comment]
@vonnai can you review my PR.  Also it seems dropping left was never accounted for.

**Comment by vonnai** [comment]
@melloware I don't think, that the left should be accounted for. The resizer is displayed only on the right side of the column.

**Comment by melloware** [comment]
OK PR updated.

**Comment by vonnai** [comment]
as I see in the code, there is nothing about LTR, RTL modes in setupResizableColumns method. I'm not sure that the behavior should respect these modes, i'm not a UIX specialist. Your PR is right. Thanks.
