### ISSUE TITLE
DataTable: selection is not rendered

### ISSUE THREAD

**Issue by hgfrey** [primefaces/primefaces#11659]
### Describe the bug

In 14.0.0-RC2 selections as column are not longer available.
Prviously:
![image](https://github.com/primefaces/primefaces/assets/33621098/91472f53-69f8-4072-9e5e-8a752d154de9)

Now: 
![image](https://github.com/primefaces/primefaces/assets/33621098/4d1405f2-3c47-4805-be94-6297ed5b8fbf)

### Reproducer

Neither single nor multiple selections ae rendered in data table

### Expected behavior

selections are rendered.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-RC

### JSF implementation

Mojarra

### JSF version

2.3.9

### Java version

11

### Browser(s)

Firefox 15.5.0

**Comment by Rapster** [comment]
Please provide at least your xhtml code... And also, have a look at https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/14_0_0?id=datatable-selection ?

**Comment by melloware** [comment]
Yep I am running 14.0.0-RC2 showcase and it works fine:
![image](https://github.com/primefaces/primefaces/assets/4399574/aa78c5ad-f646-4f74-9f8f-406519c2f469)

**Comment by hgfrey** [comment]
Please have a look at the attached promefaces-tester

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/14667214/primefaces-test-master.zip)


It looks like thi:
![image](https://github.com/primefaces/primefaces/assets/33621098/44b3d10d-c575-46f4-8bd1-7d39e8130116)

**Comment by Rapster** [comment]
> And also, have a look at https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/14_0_0?id=datatable-selection and https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

😉
