### ISSUE TITLE
InputNumber: reverts to old value on blur after cutting

### ISSUE THREAD

**Issue by jonnieZG** [primefaces/primefaces#11652]
### Describe the bug

Reproducible in v8, also in v13 in the showcase page [https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml):

1. Go to the first field "No Configuration" in the showcase page, double-click the field to select current value of "0.00"
2. Press CTRL+X (now the field is empty)
3. Fast, within the same second press TAB (the value of the "No Configuration" field gets restored to "0.00")

**Expected behavior:** The field "No Configuration" should remain empty.

- It works fine if you press DEL, seems to be occurring only with Ctrl+X
- The same behavior is in Chrome, Edge and Firefox latest versions on the date of reporting the issue.

### Reproducer

- [https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml)
- [https://www.primefaces.org/showcase-v8/ui/input/inputNumber.xhtml](https://www.primefaces.org/showcase-v8/ui/input/inputNumber.xhtml)

### Expected behavior

The field where the Ctrl+X is pressed should remain empty.

### PrimeFaces edition

None

### PrimeFaces version

8.0.0

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

Any

**Comment by melloware** [comment]
I can't reproduce on the showcase in Google Chrome latest or Firefox latest...

@jepsar or anyone else can you reproduce the behavior?

**Comment by melloware** [comment]
![inputnumber](https://github.com/primefaces/primefaces/assets/4399574/5bfeaeb2-b10a-47f3-a550-77e37fe19dd4)

**Comment by jonnieZG** [comment]
The reproducer *is* the showcase page. It has been reproduced on several computers. It does not occur in 100% attempts, but if you do as described fast enough (Select value -> Ctrl+X -> TAB (within the same second, preferably faster) - you will see the behavior.

**Comment by melloware** [comment]
let me grab a video of mine.

**Comment by melloware** [comment]
![in](https://github.com/primefaces/primefaces/assets/4399574/0c31e2da-5e19-4c7c-9b40-1c3e1b7e4925)

**Comment by melloware** [comment]
I highlight the field press CTRL+X then Tab real fast.  Using Windows 11, Chrome latest, Firefox latest.

**Comment by jonnieZG** [comment]
![ezgif-4-c66d60e6bf](https://github.com/primefaces/primefaces/assets/8830300/88732d53-9c5f-4054-a8a1-5d6359e13823)
- Chrome Version 122.0.6261.129 (Official Build) (64-bit) 
- Windows 11 Version 22H2 (OS Build 22621.1485)

Confirmed also with:
- Firefox 123.0.1 (64-bit)
- Edge 122.0.2365.92 (Official build) (64-bit)

**Comment by jepsar** [comment]
I can reproduce it. Don't need to be fast. Using click to blur has the same effect.

**Comment by melloware** [comment]
Weird I have tried everything and can't reproduce it.

Windows 11 Pro 23H2
Chrome Version 122.0.6261.129 (Official Build) (64-bit)

**Comment by htonkov** [comment]
Hello!
Here here is also a video of reproduction, it seems that it is related to page load, i.e. when page is loaded - it either happens or not

In video: 
I first enter value 777, exit the field, enter the field, make a selection, CUT, and TAB.


Chrome is up to date
Version 122.0.6261.129 (Official Build) (64-bit)
Windows 11

https://github.com/primefaces/primefaces/assets/16700622/6e6933ed-ec24-47bd-8f28-bcd53e4f4f58

**Comment by melloware** [comment]
MonkeyPatch:

```js
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.wrapEvents = function() {
        var $this = this;

        // get the current attached events if using CSP
        var events = this.input[0] ? $._data(this.input[0], "events") : null;

        // use DOM if non-CSP and JQ event if CSP
        var originalOnkeyup = this.input.prop('onkeyup');
        if (!originalOnkeyup && events && events.keyup) {
            originalOnkeyup = events.keyup[0].handler;
        }
        this.input.prop('onkeyup', null).off('keyup').on('keyup.inputnumber', function(e) {

            var oldValue;
            var key = e.key;

            // #11652 Check if Cut/Copy/Paste
            var cutCopyPaste = (e.ctrlKey && ['KeyX', 'KeyC', 'KeyV'].includes(e.code));
            if (cutCopyPaste || ['Backspace', 'Enter', 'Delete'].includes(key) || PrimeFaces.utils.isPrintableKey(e)) {
                oldValue = $this.copyValueToHiddenInput();
            }

            if (originalOnkeyup && originalOnkeyup.call(this, e) === false) {
                if (oldValue) {
                    $this.setValueToHiddenInput(oldValue);
                }
                return false;
            }
        });

        // use DOM if non-CSP and JQ event if CSP
        var originalOnchange = this.input.prop('onchange');
        if (!originalOnchange && events && events.change) {
            originalOnchange = events.change[0].handler;
        }
        this.input.prop('onchange', null).off('change').on('change.inputnumber', function(e) {

            var newValue = $this.copyValueToHiddenInput();
            // #10046 do not call on Change if the value has not changed
            if (newValue === $this.initialValue ||
                ($this.initialValue !== '' && newValue !== '' && Number(newValue) === Number($this.initialValue))) {
                return false;
            }
            if (originalOnchange && originalOnchange.call(this, e) === false) {
                $this.setValueToHiddenInput(newValue);
                return false;
            }
            $this.initialValue = newValue;
        });

        // use DOM if non-CSP and JQ event if CSP 
        var originalOnkeydown = this.input.prop('onkeydown');
        if (!originalOnkeydown && events && events.keydown) {
            originalOnkeydown = events.keydown[0].handler;
        }
        this.input.prop('onkeydown', null).off('keydown').on('keydown.inputnumber', function(e) {

            var oldValue = $this.copyValueToHiddenInput();
            if (originalOnkeydown && originalOnkeydown.call(this, e) === false) {
                $this.setValueToHiddenInput(oldValue);
                return false;
            }
        });

        this.bindInputEvents();
    }
};
```

**Comment by jonnieZG** [comment]
> MonkeyPatch:
> 
> ```js
> if (PrimeFaces.widget.InputNumber) {
>     PrimeFaces.widget.InputNumber.prototype.wrapEvents = function() {
> ...[snip]...

Thanks, we have added this as a patch-11652.js to be loaded and run after the main primefaces.js and for now seems to have solved the issue!

Compliments, that was **fast**!

**Comment by melloware** [comment]
I will add this in PF 13.0.8 thanks for reporting @jonnieZG

**Comment by jonnieZG** [comment]
@melloware could you, please, make a similar hotfix for v8.0 (until we migrate completely to v13), as in v8 it throws a _TypeError: this.bindInputEvents is not a function_? Thanks!

**Comment by jonnieZG** [comment]
> Try this for V8:
> 
> ```js
> if (PrimeFaces.widget.InputNumber) {
> ...[snip]...
> ```

Thanks! It works great!

**Comment by melloware** [comment]
Nice!  Thanks again for the report!
