### ISSUE TITLE
TextEditor: Add spell checker

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#11658]
### Description

It would be great to have spell checker builtin function. 

### Describe the solution you would like

adding spellchecker=true/false would be great.

**Comment by jepsar** [comment]
I use Chrome and get spell checking out of the box.

**Comment by melloware** [comment]
@anuragnz yes and it looks like its ON by default in QuillJS: https://github.com/quilljs/quill/issues/2225

**Comment by melloware** [comment]
Also I just went to the showcase and spelled a word wrong and its working fine:

![image](https://github.com/primefaces/primefaces/assets/4399574/e95001fe-7229-49e8-bcb1-e0ecf362233a)
