### ISSUE TITLE
Spinner: MAX value dont work up to 1000 when ROUND is true

### ISSUE THREAD

**Issue by hectorsalasvillasur** [primefaces/primefaces#11660]
### Describe the bug

When I use **Spinner** with **round="true"**      the value of **max** becomes always 1000
And if you pulse increment (+) beyond 1000, the value becomes 1, 2, 3, and then blocks the component

### Reproducer

 <p:spinner min="0" max="3000"  round="true"/>

Dont work beyond 1000

### Expected behavior

 <p:spinner min="0" max="3000"  round="true"/>

Dont work beyond 1000

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### Theme

saga

### JSF implementation

Mojarra

### JSF version

10.0.0

### Java version

20.0.1

**Comment by melloware** [comment]
Reproducer: 
[pf-11660.zip](https://github.com/primefaces/primefaces/files/14668242/pf-11660.zip)

**Comment by melloware** [comment]
MonkeyPatch:

```js
if (PrimeFaces.widget.Spinner) {
    PrimeFaces.widget.Spinner.prototype.roundStep = function(value) {
        if (!this.cfg.round) {
            return value;
        }
        var numericValue = parseFloat(typeof value === 'string' ? value.replace(this.cfg.thousandSeparator, '') : value);
        return +(Math.ceil(numericValue / this.cfg.step) * this.cfg.step).toFixed(this.cfg.precision);
    }
}
```
