### ISSUE TITLE
addRow() method to DataTable()

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#1169]
This is useful when a new data needs to be added to the datatable, instead of updating the whole table to show it, just call addRow() and it will append the tr element only.

``` xml
<h:form>
            <p:dataTable var="car" value="#{dtBasicView.cars}" widgetVar="dt">
                <p:column headerText="Id">
                    <h:inputText value="#{car.id}" />
                </p:column>

                <p:column headerText="Year">
                    <h:inputText value="#{car.year}" />
                </p:column>

                <p:column headerText="Brand">
                    <h:inputText value="#{car.brand}" />
                </p:column>

                <p:column headerText="Color">
                    <h:inputText value="#{car.color}" />
                </p:column>
            </p:dataTable>
            <p:commandButton value="Add" actionListener="#{dtBasicView.addCar}" oncomplete="PF('dt').addRow()" process="@this"/>
        </h:form>
```

``` java
@ManagedBean(name="dtBasicView")
@ViewScoped
public class BasicView implements Serializable {

    private List<Car> cars;

    @ManagedProperty("#{carService}")
    private CarService service;

    @PostConstruct
    public void init() {
        cars = service.createCars(10);
    }

    public List<Car> getCars() {
        return cars;
    }

    public void setService(CarService service) {
        this.service = service;
    }

    public void addCar() {
        this.cars.add(new Car());
    }
}

```

**Comment by kukel** [comment]
WOW!!!! YES, great... now the same thing for TabViews...(and delete of course for both, or at least the tabView)... This really is a great addition!!!

I've looked at the patch, but immediately are wondering if the partial-response 'insert' functionality is used here?

**Comment by foobarops** [comment]
Not working properly: new row is created, but values displayed are not from the new row - they are from one of rows already loaded to UI.

**Comment by dkokkal** [comment]
I have the same problem as andreas-bochkov, is there any work around?

**Comment by jxmai** [comment]
@andreas-bochkov,  @dkokkal Is it still a problem :thinking: ?  I was evaluating this feature and did not experience any issue so far.

Here is the test code I used:

```xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<h:body>
	<h:form>
		<p:dataTable value="#{testBean.people}" var="person"
			widgetVar="tableWidget">
			<p:column headerText="Name">
				<h:inputText value="#{person.name}" />
			</p:column>
			<p:column headerText="Description">
				<h:inputText value="#{person.description}" />
			</p:column>
		</p:dataTable>
		<p:commandButton value="Add" actionListener="#{testBean.addPerson()}"
			oncomplete="PF('tableWidget').addRow()" update="@this"></p:commandButton>
	</h:form>
</h:body>
</html>
```

---

```java
package test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testBean")
@ViewScoped
public class TestBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9110143420906726458L;

	private List<Person> people;

	@PostConstruct
	public void init() {
		people = new ArrayList<Person>();
		Person person1 = new Person("Alice", "This is Alice");
		Person person2 = new Person("Bob", "this is bob");
		people.add(person1);
		people.add(person2);
	}

	public List<Person> getPeople() {
		return people;
	}

	public void setPeople(List<Person> people) {
		this.people = people;
	}

	public void addPerson() {
		this.people.add(new Person("Eve", "this is eve"));
	}
}

```
```java
package test;

import java.io.Serializable;

public class Person implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2450924260546503870L;

	private String name;

	private String description;

	public Person() {
		super();
	}

	public Person(String name, String description) {
		super();
		this.name = name;
		this.description = description;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}

```


before adding:

![snapshot1](https://user-images.githubusercontent.com/10467831/32422014-1c21471c-c263-11e7-8a6a-1457d798168e.png)


after adding:


![snapshot1](https://user-images.githubusercontent.com/10467831/32422018-2b997b2e-c263-11e7-9356-8ebe05a20693.png)

**Comment by melloware** [comment]
@jxmai I was able to reproduce this issue using lazy.  created an reproducible test case in this ticket.  https://github.com/primefaces/primefaces/issues/3901

**Comment by jxmai** [comment]
I could replicate the same behaviour using the provided sample, but it looks like there is workaround available :thinking:  (https://github.com/primefaces/primefaces/issues/3901#issuecomment-407725818). Is it documented anywhere else ?

**Comment by melloware** [comment]
Not documented that I know of, I got that working fix from Mert but I would have had no idea that was how to make it work.

**Comment by jxmai** [comment]
Alright, thanks for the info :+1: . Yes, TBH without looking into the implementation,  at first glance I had no idea how that two lines of code could be related to the issue :smiley:  
> lazyModel.setRowCount(lazyModel.datasource.size());
        lazyModel.setWrappedData(lazyModel.datasource);

but it looks like lazyModel needs to be manually updated to reflect the latest data.

I don't really use lazy model that much but we may need to review a bit later. Good to know there is a  known solution by the way.

**Comment by hAzUpL8** [comment]
Hi @jxmai I still have a problem with adding new row. I always got last row and not the new one. In your example I got :

![image](https://user-images.githubusercontent.com/33866210/67387977-279dd500-f598-11e9-8760-5fbfb23db2a1.png)

I don't have lazy loading enabled. I have
<p:commandButton id="btnAdd"  value="Add" icon="fa fa-plus" actionListener="#{beanVSB.onDvdRowAdd}" oncomplete="PF('wvDt').addRow();" process="@this" styleClass="btns ui-priority-primary"/>
...
<p:dataTable id="dt" widgetVar="wvDt" value="#{beanVSB.postavkeDdv}" var="record" rowIndexVar="rowIndex"
                            multiViewState="true" selectionMode="single" selection="#{beanVSB.selectedPostavkaDdv}" rowKey="#{record.postavkaId}.#{record.position}"
                            style="width: 600px" editable="true">
...
...
**and in bean**
public void onDvdRowAdd() {
    PostavkeDdv newRow = new PostavkeDdv();
    newRow.setPostavkaId(1); // this is not a constant, it is masted table id!
    getPostavkeDdv().add(newRow);
}

Any suggestions?

**Comment by melloware** [comment]
@hAzUpL8 See this issue instead: https://github.com/primefaces/primefaces/issues/3901

**Comment by hAzUpL8** [comment]
@melloware , I've looked at this before, but I don't have any lazyModel... In my case I don't use any lazy loading.

**Comment by melloware** [comment]
What version of PrimeFaces?

**Comment by hAzUpL8** [comment]
Primefaces version 7.0, but the application is portlet and is running on IBM Websphere portal 8.5
.
.
.
During this time, I found a solution. The problem was with ViewScoped ManagedBean on the portal. When I changed to SessionScoped everything started working normally!

**Comment by melloware** [comment]
Interesting.   I wonder if it is portal related but glad you got it resolved.

**Comment by jxmai** [comment]
@hAzUpL8 Just noticed you pinged me some time ago. Good to know you found the solution :). Although I am not sure your explanation "changing from session scope to viewscope works" which does not make sense to me (Warning: There is a high chance it just works by accident). Be careful of the differences between session scope and viewscope though

**Comment by hAzUpL8** [comment]
Almost certainly the problem is the portal. You never know what's going on in those PortletBridges. I've noticed that quite a few PF components on Websphere Porat are not working properly, so I don't use them....
