### ISSUE TITLE
Memory: update="@form" causes DOM Leak

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11702]
This was actually been around since 2013 I found this forum post: https://forum.primefaces.org/viewtopic.php?p=112616&sid=bc050d696d9491eda81c886c272f705b#p112616

**Simple example:**
```xml
    <h:form id="frmSimple">
        <p:selectBooleanCheckbox value="#{simpleView.rendered}" itemLabel="Show/Hide">
            <p:ajax update="@form" />
        </p:selectBooleanCheckbox>
        <p></p>
        <div jsf:id="inputs">
            <p:inputText id="input" widgetVar="wgtInput" value="#{simpleView.text}" rendered="#{simpleView.rendered}">
                <p:ajax event="keyup" update="display2" process="@this" />
            </p:inputText>
            <p></p>
            <h:outputText id="display2" value="#{simpleView.text}" rendered="#{simpleView.rendered}" />
        </div>
    </h:form>
```

Every time you AJAX update `@form` or `:formSimple` or any variation you will see leaked DOM elements because the old form has jQuery handlers on it.

![image](https://github.com/primefaces/primefaces/assets/4399574/b885692e-0256-4c62-a66a-9d0311d74696)

**Comment by tandraschko** [comment]
Can you explain a bit more what exactly leaks here and why?

Same like the Ajax Case
Widget gets destroyed, the Widget and jquery vars are unused, why cant it be garbage collected?

**Comment by melloware** [comment]
i will put together a small test case for you.
