### ISSUE TITLE
Color picker not working

### ISSUE THREAD

**Issue by pm2013** [primefaces/primefaces#11711]
### Describe the bug

In place of color picker there is only the text with color.

The console shows error:
Uncaught TypeError: $jscomp.arrayFromIterable is not a function
    fa (...)javax.faces.resource/colorpicker/colorpicker.js.xhtml?ln=primefaces&v=13.0.5&e=13.0.5:35

Even if I copy-paste the whole example of color picker, the result is the same.

I use MyFaces 2.3.10

<img width="1463" alt="Zrzut ekranu 2024-04-2 o 14 22 15" src="https://github.com/primefaces/primefaces/assets/13569972/10ddf539-7580-4145-bda4-d55dc1d96e45">

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.5

### Theme

Serenity

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

JDK 1.8

### Browser(s)

Firefox, Chrome, Safari

**Comment by melloware** [comment]
Can't reproduce:
[pf-11711.zip](https://github.com/primefaces/primefaces/files/14836921/pf-11711.zip)

Unzip and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

![image](https://github.com/primefaces/primefaces/assets/4399574/fb9611c4-0a29-4253-82a3-1bdb2e551381)
