### ISSUE TITLE
SQL Injection may be possible on Primefaces 13 (may be false positive)

### ISSUE THREAD

**Issue by danieldi96** [primefaces/primefaces#11725]
### Describe the bug

I have encountered the same issue mentioned here:
https://github.com/primefaces/primefaces/issues/11475

As the comments suggest, this SQL Injection might be a false positive. I assume this is because it doesn't generate a complete SQL statement on its own.
Does anyone know if it is 100% accurate or have more information regarding it?

Thank you!

### PrimeFaces edition

Elite

### PrimeFaces version

8.0.25

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

8

**Comment by melloware** [comment]
False positive see: https://github.com/primefaces/primefaces/issues/11475
