### ISSUE TITLE
DataTable: inconsistent behavior of selection

### ISSUE THREAD

**Issue by JiriKrizek** [primefaces/primefaces#1172]
**How to reproduce:**
- Open Primefaces Showcase http://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml
- Click on the line in "RadioButton" datatable (anywhere except radiobutton itself)

**Expected** same behavior like in the other Datatables on showcase page.
- On mouse over: line is visually different. 
- On click: Current line is selected, after click anywhere on the line, radiobutton is selected.

Selecting line on datatable is functional only when user clicks inside radio button. Selection does not work, when user clicks anywhere else on the table line. This behavior is inconsistent with other variants of "selectable datatable", for example in Checkbox variant.

Primefaces version: 5.3
Thank you

**Comment by erickdeoliveiraleal** [comment]
With checkbox style is also broken, if a user click over some text all other selected get disabled.
This is very bad since the user already selected thousand of information and by accident he click over the column text and all work is lost)
