### ISSUE TITLE
Dialog scroll issue

### ISSUE THREAD

**Issue by fx89** [primefaces/primefaces#1173]
There are a couple of issues involving a modal dialog appearing over a scrollable page.
1. When the scroll content covers more than two window heights, the dialog doesn't appear at all
2. If the dialog has selectOneMenu's or autocomplete's or any other control which requires overlays for selecting options, scrolling the page (i.e. using the mouse wheel) also scrolls the overlays along with the page content residing under the modal dialog

I have added the project in which I have replicated the issue to GitHub: [https://github.com/fx89/primefaces-issues-demo/tree/master/modal-dialog-scroll-issue](https://github.com/fx89/primefaces-issues-demo/tree/master/modal-dialog-scroll-issue)

Steps to reproduce: 
- Create a page with a lot of content
- Add a modal dialog which contains a selectOneMenu or an autoComplete menu
- Start the app, push the button to show the dialog
- Notice that the dialog will not appear anywhere on the page (you may also scroll down trying to look for it but it will not be there - may have something to do with the fixed position of the dialog)
- Add javascript code to the "onclick" event of the button to set the top position of the dialog and try again
- Attempt to fill in the control so that the options overlay appears
- Do not choose any option. Instead, scroll the page using the mouse wheel

Relevant screen shots from the demo project:

![page1](https://cloud.githubusercontent.com/assets/16502403/13202547/73196c5e-d8a7-11e5-82f2-ffd4a108ade9.png)

![page2](https://cloud.githubusercontent.com/assets/16502403/13202635/ffb318f2-d8a9-11e5-8a5b-a35cfade7867.png)

![page3](https://cloud.githubusercontent.com/assets/16502403/13202645/8ce24608-d8aa-11e5-95cd-89d9e6dac753.png)

PS: Didn't try it but I believe the same behaviour may be observed with non-modal dialogs

**Comment by kukel** [comment]
Known issue in PrimeFaces 0.9.6.

**Comment by jxmai** [comment]
Try to add an attribute appendTo="@this" inside the p:selectOneMenu to see if it helps.

**Comment by fx89** [comment]
Thanks for the help. 

Just tried appendTo="@this". The list of values no longer scrolls with the page. Instead, it is contained within the dialog's content div. When the list of values appears, a vertical scroll bar appears on the dialog's content div because the list of values extends the content further than the height of the div. 

See the pitcutre: 

![page4](https://cloud.githubusercontent.com/assets/16502403/13504782/a2855c5c-e17e-11e5-9f57-034cc5452193.png)

Though this can be solved by placing the selectOneMenu as high as possible in the dialog, there's still the issue of the dialog not appearing without the JavaScript workaround.

**Comment by jxmai** [comment]
I get your point. The only workaround without any trick I can think of is by reducing the menu height or by increasing the dialog height, but that's not a final solution as you already described.

Let's wait and see how Primefaces team will response to this issue then.

**Comment by mertsincan** [comment]
Can you please try this Js code?

```
<script type="text/javascript">
//<![CDATA[
    $( window ).scroll(function() {
        var isActive = $(".MyOneMenuPanel").is(':visible');
        if(isActive) {
            $(".MyOneMenuPanel").position({
                my: "left top",
                at: "left bottom",
                of: $(".MyOneMenu")
            });
        }
    });
//]]>
</script>

//xhtml
<p:dialog ..>
    <p:selectOneMenu styleClass="MyOneMenu" panelStyleClass="MyOneMenuPanel" >
                        //<f:selectItem or <f:selectItems
    </p:selectOneMenu>
</p:dialog>
```

**Comment by jxmai** [comment]
Thanks for the reply. I tried the js code. It is working.

This is a simple complete testing code

``` xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:p="http://primefaces.org/ui"
  >
<h:head>
    <script type="text/javascript">
        //<![CDATA[
            $( window ).scroll(function() {
                var isActive = $(".MyOneMenuPanel").is(':visible');
                if(isActive) {
                    $(".MyOneMenuPanel").position({
                        my: "left top",
                        at: "left bottom",
                        of: $(".MyOneMenu")
                    });
                }
            });
        //]]>
    </script>

</h:head>

<p:dialog widgetVar="testDialog">
    <h:form>
        <p:outputPanel>
            <p:selectOneMenu panelStyleClass="MyOneMenuPanel" styleClass="MyOneMenu">
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
            </p:selectOneMenu>
        </p:outputPanel>
    </h:form>
</p:dialog>


<h:body style="padding:10px 10px 10px 10px; border-style:solid;">

    <h:form id="mainForm" enctype="multipart/form-data">
        <p:growl id="messages" showDetail="true" />

        <div class="ui-grid ui-grid-responsive">
            <div class="ui-grid-row">
                <div class="ui-grid-col-12">
                    <p:commandButton value="test"
                                     oncomplete="PF('testDialog').show();"
                    >
                    </p:commandButton>
                </div>
            </div>
            <p:spacer height="10000"></p:spacer>
        </div>
    </h:form>
</h:body>
</html>
```

Before scroll:
![screenshot](https://cloud.githubusercontent.com/assets/10467831/13660598/3030bed0-e651-11e5-8cfe-43da8bf00068.png)

After scroll:

![screenshot](https://cloud.githubusercontent.com/assets/10467831/13660625/60d33964-e651-11e5-90d7-996155413d18.png)

**_But going back to the issue, do we have to use javascript to deal with this issue?  Will Primefaces  add native support to fix this issue in the future release ?**_

**Comment by cagataycivici** [comment]
Why not remove overflow from ui-dialog-content and use appendTo="@this" on selectOneMenu.

**Comment by jxmai** [comment]
Thanks for the reply. I tried to remove the overflow from the dialog. It does not work for me. 

Here is the simple complete testing code:

``` xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:p="http://primefaces.org/ui"
  >
<h:head>
    <style>
        .disable-scroll .ui-dialog-content {
              overflow: hidden !important;
            }
    </style>
</h:head>

<p:dialog widgetVar="testDialog" styleClass="disable-scroll">
    <h:form>
        <p:outputPanel>
            <p:selectOneMenu appendTo="@this">
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
                <f:selectItem itemValue="" itemLabel="dummy"/>
            </p:selectOneMenu>
        </p:outputPanel>
    </h:form>
</p:dialog>


<h:body style="padding:10px 10px 10px 10px; border-style:solid;">

    <h:form id="mainForm" enctype="multipart/form-data">
        <p:growl id="messages" showDetail="true" />

        <div class="ui-grid ui-grid-responsive">
            <div class="ui-grid-row">
                <div class="ui-grid-col-12">
                    <p:commandButton value="test"
                                     oncomplete="PF('testDialog').show();"
                    >
                    </p:commandButton>
                </div>
            </div>
            <p:spacer height="10000"></p:spacer>
        </div>
    </h:form>
</h:body>

</html>

```

This is the result:

![screenshot](https://cloud.githubusercontent.com/assets/10467831/13720488/d076f9e8-e7cf-11e5-9369-adda0b520e7a.png)

**_The scrollbar disappears but the selectOneMenu appears in the dialog's content div.**_

**Comment by andyba** [comment]
This is an issue for us with PrimeFaces 6.0.9 and is not easily fixed as shown here because we have a -lot- of SelectOneMenu components in dialogs.
