### ISSUE TITLE
Input width inconsistency

### ISSUE THREAD

**Issue by fx89** [primefaces/primefaces#1174]
There are inconsistencies between the implementation of the "style" attribute of various PF components. These inconsistencies are most notable (and frustrating) when attempting to set the widths of the fields of a form. For instance:
- inputText with style="width:800px" renders as an input control with width = 800px, which is about right
- selectOneMenu with style="width:800px" renders as an input control with width = 800px followed by a combo button with width = whatever the theme says. This is quite a problem since one might actually want to switch to a new theme at some point, in which case, if one needs all the fields in the form to have the exact same width (and that's including the combo button), one would have to revise all of the forms in the application.
- Then there's the autocomplete. It does not apply the style to the input control but rather to the surrounding span. Even though the theme can be modified or overwritten with "i-forgot-class > input {width: 100%}", it is still annoying. 
- The calendar control behaves in a strange way. For example: <p:calendar style="border: 1px solid #000; width:800px" /> displays the solid black border, but seems to ignore the width attrbute. 

I've discovered this while switching a bunch of selectOneMenu's for autocomplete's in one of my forms, hence the name of the demo project: [https://github.com/fx89/primefaces-issues-demo/tree/master/autocomplete-width-issue](https://github.com/fx89/primefaces-issues-demo/tree/master/autocomplete-width-issue)

And the relevant screen shot:
![page1](https://cloud.githubusercontent.com/assets/16502403/13202684/c9cb66ac-d8ab-11e5-96f3-d93d5a2c0719.png)

**Comment by kukel** [comment]
known issue in PrimeFaces 0.9.6

**Comment by cagataycivici** [comment]
style and styleClass always apply to the outmost container of component, some components haver inputStyle and inputStyleClass, if you'd like to purse please create issues for the ones that miss it. So for example, use inputStyle in autocomplete instead of style.
