### ISSUE TITLE
DataExporter: Make the ExporterUtils.getColumnValue method overridable

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#11748]
### Description

I do not like the fact, that calls to static methods like `ExporterUtils.getComponentValue()` and friends are still hardwired in the exporter framework and not overwritable by the user.

We have columns containing components that are not in the covered list of that implementation (e.g. pe:timeAgo). So instead of overriding a method there, we have to clone `TableExporter.addCells()`, `TableExporter.addColumnFacets()`, `TableExporter.addColumnGroupFacets()` and `TableExporter.addTableFacets()` in each of our three custom exporters.

In addition the `cellJoinComponents` field in the `TableExporter` class should be accessible via a protected getter method to derived classes, as this is used heavily in the beforementioned addXXX methods.

### Describe the solution you would like

The user should be able to overwrite the implementation of ExporterUtils methods.

**Comment by stolp** [comment]
I also have this issue with DataTableExporter:

```
    protected void exportRow(FacesContext context, DataTable table, int rowIndex) {
        if (rowIndex != NO_ROW_INDEX_REQUIRED) {
            table.setRowIndex(rowIndex);
            if (!table.isRowAvailable()) {
                return;
            }
        }

        super.addCells(context, table);
    }

```

This should be `addCells(context, table);` at the end of the method instead, to make this method overwritable.

**Comment by Rapster** [comment]
I'll most probably deprecate ExporterUtils and put everything back in TableExporter

**Comment by Rapster** [comment]
They're all public or protected, what am I missing?

**Comment by stolp** [comment]
Right. My excuses, I was apparently overthinking this.

It is good enough as it is I guess.
