### ISSUE TITLE
Paginator: Custom facet in paginatorTemplate doesn't work because of surrounding {}

### ISSUE THREAD

**Issue by Anodarai** [primefaces/primefaces#11752]
### Describe the bug

There is undocumented support for including a facet in paginatorTemplate, however, this does not work because the string passed to getFacet is surrounded with "{" "}".

https://github.com/primefaces/primefaces/blob/35eb74096630a28dc354fa1bb690668c309ae771/primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java#L121-L125

The starting and ending { } should be removed before passing it to pageable.getFacet

### PrimeFaces edition

Community

### PrimeFaces version

13.0.8

### JSF implementation

Mojarra

### JSF version

4.0.4

### Java version

17

**Comment by Rapster** [comment]
I understand it might look odd, but how is that an issue? You just have to put {} in your facet name no?

**Comment by Anodarai** [comment]
Sorry, that's true, not sure how I just didn't think about it. I guess this could be enhanced by not having to put { in facet name, but it's not a big issue
