### ISSUE TITLE
[BUG] Assigning null value to datatable filteredValue has no effect

### ISSUE THREAD

**Issue by dmitsuo** [primefaces/primefaces#1175]
I have a **datatable** with filters enabled and **filteredValue** property associated with a managed bean field (view scoped).

```
<p:dataTable id="dtPlayers" value="#{filterFailJsfBean.players}" var="p" filterEvent="enter"
             filteredValue="#{filterFailJsfBean.filteredPlayers}">
    <p:column headerText="Pos." filterBy="#{p.id}" filterMatchMode="contains" 
              style="text-align: center">
        <h:outputText value="#{p.id}"/>  
    </p:column>
    <p:column headerText="Name" filterBy="#{p.name}" filterMatchMode="contains">
        <h:outputText value="#{p.name}"/>  
    </p:column>
    <p:column headerText="Country" filterBy="#{p.country}" filterMatchMode="contains">
        <h:outputText value="#{p.country}"/>  
    </p:column>                
</p:dataTable>
```

I also have a managed bean method to clear filters by assigning null value to the managed bean field associated with the filteredValue datatable property.

```
public void clearFilters() {
    timesFired = timesFired + 1;

    // Try to clear the datatable filters
    this.filteredPlayers = null;

    FacesContext.getCurrentInstance().addMessage(null, 
        new FacesMessage(String.format("Clear filters button fired %s time(s)!", timesFired)));
}
```

If I do some filter on datatable and, after that, call the managed bean method to clear filters, **nothing happens. The datatable still appears with filtered values. Only after the second call to managed bean method the datatable becomes unfiltered.**

Below more details and complete code to reproduce this bug (I provide a link to a complete test case also).

**Primefaces 5.0 does not show this misbehavior**. Only 5.1 onward.

Component: **PrimeFaces Datatable** 

Version: **PrimeFaces 5.1 and later**

Complete Test Case source code project: https://github.com/dmitsuo/datatable-clear-filter-fail

Steps to reproduce:

**1.** Define the following XHTML page, managed bean and POJO:
### XHTML

```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Clear datatable filter fail</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:form>
            <h2>Greatest Football Legends of All Time</h2>
            <p:messages id="messages"/>
            <p:commandButton value="Clear filters" action="#{filterFailJsfBean.clearFilters}" process="@this" update="dtPlayers messages"/>
            <p:dataTable id="dtPlayers" value="#{filterFailJsfBean.players}" filteredValue="#{filterFailJsfBean.filteredPlayers}" var="p" filterEvent="enter">
                <p:column headerText="Pos." filterBy="#{p.id}" filterMatchMode="contains" style="text-align: center">
                    <h:outputText value="#{p.id}"/>  
                </p:column>
                <p:column headerText="Name" filterBy="#{p.name}" filterMatchMode="contains">
                    <h:outputText value="#{p.name}"/>  
                </p:column>
                <p:column headerText="Country" filterBy="#{p.country}" filterMatchMode="contains">
                    <h:outputText value="#{p.country}"/>  
                </p:column>                
            </p:dataTable>
        </h:form>
    </h:body>
</html>
```
### JSF Managed bean

```
package com.acme;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

@ManagedBean
@ViewScoped
public class FilterFailJsfBean implements Serializable {
    private List<Player> players;
    private List<Player> filteredPlayers;
    private int timesFired;
    public FilterFailJsfBean() {
    }    
    @PostConstruct
    public void init() {
        timesFired = 0;
        players = new ArrayList<Player>();
        players.add(new Player(1, "Zico", "Brazil"));
        players.add(new Player(2, "Pelé", "Brazil"));
        players.add(new Player(3, "Garrincha", "Brazil"));
        players.add(new Player(4, "Romário", "Brazil"));
        players.add(new Player(5, "Ronaldo", "Brazil"));
        players.add(new Player(6, "Alex", "Brazil"));
        players.add(new Player(7, "Ronaldinho", "Brazil"));        
        players.add(new Player(8, "Maradona", "Argentina"));
        players.add(new Player(9, "Zidane", "France"));
        players.add(new Player(10, "Messi", "Argentina"));
    }
    public List<Player> getFilteredPlayers() {
        return filteredPlayers;
    }
    public void setFilteredPlayers(List<Player> filteredPlayers) {
        this.filteredPlayers = filteredPlayers;
    }
    public List<Player> getPlayers() {
        return players;
    }
    public void setPlayers(List<Player> players) {
        this.players = players;
    }    
    public void clearFilters() {
        timesFired = timesFired + 1;

        // Try to clear the datatable filters
        this.filteredPlayers = null;        

        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(String.format("Clear filters button fired %s time(s)!", timesFired)));
    }    
}
```
### POJO

```
package com.acme;
import java.io.Serializable;
/**
 *
 * @author Davi
 */
public class Player implements Serializable {
    private Integer id;
    private String name;
    private String country;
    public Player() {
    }
    public Player(Integer id, String name, String country) {
        this.id = id;
        this.name = name;
        this.country = country;
    }
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getCountry() {
        return country;
    }
    public void setCountry(String country) {
        this.country = country;
    }
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Player other = (Player) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }
    @Override
    public String toString() {
        return String.format("%s - %s (%s)", id, name, country);
    }    
}
```

**2.** Access the page, type something on any filter field of the datatable and press Enter key to filter the results.

**3.** Click on the "Clear filters" button only once.

**Actual Result:** The datatable will not get filters cleared. If we click the button for the second time then the datatable get the filters cleared.

**Expected result:** The datatable should get the filters cleared when we click the button for the first time.

**Workaround:** Bind the datatable to a variable on the managed bean and, inside the managed bean method to clear filters, call the following code

```
myDatatable.updateValue(this.players);
myDatatable.setFilteredValue(null);
```

Related Forum post URL: http://forum.primefaces.org/viewtopic.php?f=3&t=44524

Some screenshots showing this misbehavior:

![001](https://cloud.githubusercontent.com/assets/1348764/13209718/fbe65db8-d905-11e5-9e68-5adc8e8ab876.png)

![002](https://cloud.githubusercontent.com/assets/1348764/13209727/1b2f6fde-d906-11e5-8d9a-3e8264cacdf5.png)

![003](https://cloud.githubusercontent.com/assets/1348764/13209730/20f8da86-d906-11e5-8ce6-f74ec1545e23.png)

![004](https://cloud.githubusercontent.com/assets/1348764/13209734/2a58ade0-d906-11e5-9dae-9a50014e4693.png)

**Comment by dasmanu** [comment]
What about Lothar Matthäus?

**Comment by kukel** [comment]
And Cruijff and van Basten, and Gullit 

http://stackoverflow.com/questions/23797476/datatable-clearfilter-not-working-properly

**Comment by dmitsuo** [comment]
I know about the client side alternative **`PF('myDatatable').clearFilters()`** , but I have some use cases where I need clean up filters at the server side, before hit the client. 

What bothers me is that before Primefaces 5.1, I could do just **`this.filteredPlayers = null;`** on the managed bean and it was fine, but now it doesn't work at the first time called.

I suspect that is related with the system events that was introduced with PF 5.1+.

The Datatable method below, I guess, is related with this problem

```
public void processEvent(ComponentSystemEvent event) throws AbortProcessingException {
    super.processEvent(event);
    if(!this.isLazy() && event instanceof PostRestoreStateEvent && (this == event.getComponent())) {
        Object filteredValue = this.getFilteredValue();
        if(filteredValue != null) {
            this.updateValue(filteredValue);
        }
    }
}
```

This code is executed before any phase of the JSF lifecycle and get the old value for **filteredValue**, which is updated only in the Update Model phase.

Am I wrong or missing something ?

**Comment by cagataycivici** [comment]
I guess trick is clearing the value as well, as filteredData becomes the value of datatable.

``` java
public void clearFilters() {
    timesFired = timesFired + 1;

    // Try to clear the datatable filters
    this.filteredPlayers = null;

   //DataTable tbl = //getDatatable instance with findComponent
   tbl.setValue(null); //force refresh to original value

    FacesContext.getCurrentInstance().addMessage(null, 
        new FacesMessage(String.format("Clear filters button fired %s time(s)!", timesFired)));
}
```

**Comment by dmitsuo** [comment]
First of all, thank you @cagataycivici for your great and extraordinary work on Primefaces!

About your solution, I consider it as a workaroud, because before PF 5.1+ I didn't need to clear the value of the datatable itself.

Should I expect a definitive solution or I have to work like that from now on?

But again, thank you for all the time and effort you have put into Primefaces!

Davi.

**Comment by neXus1987** [comment]
Hi all,

in my point of view i think also there is a bug. I can confirm this behavior and to find the datatable component is just a workaround, the main problem is that the real data from the filteredValue is not applied.  

In our applications we have massively problems with that. For example in a master-detail view our detail is not updatet when there is something filtered.

Thanks
Phil

**Comment by jxmai** [comment]
I guess this issue is somewhat related to #1715 (defect)

> the filter input isn't rendered on a ajax update
the data is internally filtered but the user doesn't see if the data is filtered

**Comment by neXus1987** [comment]
Yes exactly! Thanks!!!!

**Comment by adlerpoland** [comment]
Bug still exists on 6.1. No idea how about 6.2
Pretty annoying but thanks to @cagataycivici solution you can pretty easy fix it.
