### ISSUE TITLE
InterceptingResolver does not delegate convertToType

### ISSUE THREAD

**Issue by Wonkglorg** [primefaces/primefaces#11759]
### Describe the bug

Boolean EL expressions including `not`, `and`, `or` resolve to null if already resolved. This is caused by missing delegation of `convertToType` method in [ `org.primefaces.el.InterceptingResolver`](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/el/InterceptingResolver.java).

Used versions:
Primefaces: 13.0.8
Tomcat-Embed-EL: 10.1.19 (via Springboot 3.2.4)
Mojarra: 4.0.6

### Expected behavior

Using the delegate for proper resolving.

### PrimeFaces edition

None

### PrimeFaces version

13.0.8

### JSF implementation

Mojarra

### JSF version

4.0.0

### Java version

17

**Comment by Rapster** [comment]
Any chance to provide a reproducer? At least a sample...

**Comment by melloware** [comment]
ConvertToType looks like new in EL 3.0.

```java
/**
     * Converts the given object to the given type. This default implementation
     * always returns <code>null</code>.
     *
     * @param context The EL context for this evaluation
     * @param obj     The object to convert
     * @param type    The type to which the object should be converted
     *
     * @return Always <code>null</code>
     *
     * @since EL 3.0
     */
    public Object convertToType(ELContext context, Object obj, Class<?> type) {
        context.setPropertyResolved(false);
        return null;
    }
```

**Comment by melloware** [comment]
JSF 2.3 supports EL 5.0 so this should be fine to add its the only missing method.
