### ISSUE TITLE
FileDownload: cannot download file with http connection on firefox 125+

### ISSUE THREAD

**Issue by wbss1** [primefaces/primefaces#11766]
### Describe the bug

Hello, it's no longer possible to download files using an http connection with the new download protection on firefox (version 125+). The files are downloaded, but they are not complete. This problems affect all version of primefaces.

Here it's the log error
[error download file.txt](https://github.com/primefaces/primefaces/files/15008485/error.download.file.txt)

### Reproducer

Firefox Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1894667

### Expected behavior

Correct download of file

### PrimeFaces edition

None

### PrimeFaces version

all

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

Firefox 125.0.1

**Comment by jepsar** [comment]
Are you using Ajax or non-Ajax downloading? Please include a reproducer.

**Comment by wbss1** [comment]
Here it's the reproducer.
For the test you need to not use localhost, you must use the ip
[pf-test-download.zip](https://github.com/primefaces/primefaces/files/15009008/pf-test-download.zip)

**Comment by jepsar** [comment]
Shouldn't you just run your site using SSL?

Also, it just allows me to download it after pressing a button.

<img width="502" alt="Screenshot 2024-04-17 at 11 58 46" src="https://github.com/primefaces/primefaces/assets/7500178/c75896d4-27e7-4c67-9db4-6196386e5d27">

<img width="503" alt="Screenshot 2024-04-17 at 11 58 59" src="https://github.com/primefaces/primefaces/assets/7500178/2af06cd8-0620-4c2b-bd0c-7d9a3c29878d">

**Comment by jepsar** [comment]
Hmm.. it is broken after download though. I guess it's a FF issue.

**Comment by wbss1** [comment]
Yes it is almost always in ssl, but if the application is only used on the local network it is not. Example: private server for internal use.
If you click on allow the download and open the file, you will see that it is damaged

**Comment by melloware** [comment]
@wbss1 i would start scanning the Mozilla bug list to see if this has been reported...

**Comment by melloware** [comment]
Found this bug from 11 years ago it was the same issue with Virus Scanner in their downloads corrupting Firefox files: https://support.mozilla.org/en-US/questions/893054

**Comment by melloware** [comment]
OK type `about:config` in your browser bar and disabled these settings and downloads work.  Its definitely a Firefox bug.

![image](https://github.com/primefaces/primefaces/assets/4399574/9afc824e-4c33-4536-8769-97acc52cf331)

**Comment by wbss1** [comment]
Seems like that disable dom.block_download_insecure it's enough.
I will try to report it with bugzilla

**Comment by melloware** [comment]
Yep it looks like it!

**Comment by wbss1** [comment]
I reported it on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1892115

**Comment by melloware** [comment]
Firefox 126.0 is out can someone test it to see if its fixed?

**Comment by wbss1** [comment]
In Firefox 125.0.2 they disable the HTTP download protection mechanism and they are working for fix the bug (https:///bugzilla.mozilla.org/show_bug.cgi"id=1894667).

I hope they will follow this comment and implement a solution like Google Chrome "Would it be possible to keep the response/content in a temporary location? Then if the user accepts the download the answer can be saved, otherwise it is deleted.

I’m not familiar with the implementation, but Firefox already writes a temporary . part file while downloading, so maybe this could be used, and is renamed only when the user accepts the download, and deleted otherwise."
but seems that they want to block the request and re-submit it again later when the user accept the download. Obviously the POST requests are not idempotent, so they are working on it.

**Comment by melloware** [comment]
OK @wbss1 i will close for now as nothing PF can do for this issue.
