### ISSUE TITLE
JPALazyDataModel: add resultEnricher callback 

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#11767]
### Description

Since the Constructor has been removed in PF14 R3 (https://github.com/primefaces/primefaces/pull/11754), the Post Process is not working anymore.

Can you add the possibility to add e.g. a function which allows to "manipulate" the results from the Lazy Loading result afterwards (e.g. fill some addiotional columns etc.)

Please see also discussion in Discord:
https://discord.com/channels/787967399105134612/787967662293909524/1230050675757547562

### Describe the solution you would like

To have a function for Post Progress...

**Comment by kuhhpid** [comment]
Great response time :-) thx
