### ISSUE TITLE
Remaining character counter counts \r\n as one character

### ISSUE THREAD

**Issue by 0xbs** [primefaces/primefaces#1176]
The remaining character counter does not work correctly on windows with newlines (aka \r\n).

Environment:
Chrome 48 on Windows 8.1

Steps to reproduce the problem:
1. Go to http://www.primefaces.org/showcase/ui/input/inputTextarea.xhtml
2. Enter the following characters in the remaining chars textarea: <kbd>1</kbd> <kbd>Enter</kbd> <kbd>2</kbd> <kbd>Enter</kbd> <kbd>3</kbd> <kbd>Enter</kbd> <kbd>4</kbd>
3. You cannot press enter after the 4 and cannot enter more characters, but the text below still states "3 characters remaining."

The problem seems to be that \r\n is counted as one character.

**Comment by sudheerj** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/768

**Comment by 0xbs** [comment]
Duplicate of #537

**Comment by mertsincan** [comment]
Fixed for 5.3.10 and 6.0. Duplicate of #768
