### ISSUE TITLE
DataTable: New Entry after Filtering not showing

### ISSUE THREAD

**Issue by MarcelKlein1** [primefaces/primefaces#11765]
### Describe the bug

If you filter your list in a DataTable and want to add new entries to the original list afterwards those new entries won't show up.
![datatableAddEntry](https://github.com/primefaces/primefaces/assets/104059766/35eb0130-5a9b-402f-b4d0-b593fb4edf75)

### Reproducer

[dataTable-test.zip](https://github.com/primefaces/primefaces/files/15007312/dataTable-test.zip)

### Expected behavior

New entries that get added to the original list after filtering should show up in the DataTable. This behaviour was like that with Versions 12.0.0 and lower.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.8

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

11

**Comment by melloware** [comment]
@Rapster i could be wrong but i think this issue is actually related to this right: https://github.com/primefaces/primefaces/issues/10516

**Comment by Rapster** [comment]
Seems to be working in PF 14

**Comment by melloware** [comment]
@MarcelKlein1 can you try with 14.0.0-RC3 and let us know so we can mark this ticket as fixed in 14.0.0?

**Comment by tandraschko** [comment]
@melloware as 14.0 is around the corner, i will close it for now. please reopen if you wanna invest time here for 13.x
