### ISSUE TITLE
DataTable: Header/Footer not updated by sort/filter 

### ISSUE THREAD

**Issue by xKopax** [primefaces/primefaces#1178]
Today when we filter the datatable 
`PF('table').filter()`
the datatable's footer is not updated automatically. However the footer usually holds summarized values of the columns. It'd be nice a easier way to acomplish this task.

Thanks!

**Comment by sudheerj** [comment]
As of now you can update footer values with the help of p:remoteCommand

http://stackoverflow.com/questions/24452834/how-to-ajax-update-an-item-in-the-footer-of-a-primefaces-datatable

**Comment by kukel** [comment]
@sudheerj: as of now? That is a two year old workaround...

**Comment by jansohn** [comment]
+1 for this. Having to add a separate `p:remoteCommand` is cumbersome...

**Comment by SharpShooter17** [comment]
I have the same problem. Is there any good solution?

**Comment by marcelocaser** [comment]
Yes, this is very important for us!

**Comment by marcelocaser** [comment]
> I have the same problem. Is there any good solution?

per hour, did I use this solution? https://stackoverflow.com/questions/24452834/how-to-ajax-update-an-item-in-the-footer-of-a-primefaces-datatable

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primefaces/issues/7165. Please use partialUpdate="false" for this issue.
