### ISSUE TITLE
Add slider captcha

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#11788]
### Description

ReCaptcha is blocked in some countries and it requires users to select multiple pictures and/or go through multiple steps. Slider captcha is simpler and users just need to slide a button to match images.

### Describe the solution you would like

example: https://github.com/adrsch/slider-captcha

**Comment by Rapster** [comment]
Would be great if you can find a still-maintained plugin (the one you mention is no longer maintained)

**Comment by melloware** [comment]
as a note PrimeFaces 15.0 is adding support for hCaptcha: https://github.com/primefaces/primefaces/pull/11576

See: https://www.hcaptcha.com/

![image](https://github.com/primefaces/primefaces/assets/4399574/d0eb75b1-a335-425c-88f1-fd8e20c2a956)

**Comment by javaone199** [comment]
any real-world sites using hcaptcha? Like to see some examples.

**Comment by melloware** [comment]
@javaone199 yep: https://www.wappalyzer.com/technologies/security/hcaptcha/
