### ISSUE TITLE
DataTable: Method is called multiple times inside of p:columns

### ISSUE THREAD

**Issue by BryanV91** [primefaces/primefaces#11799]
### Describe the bug

When I click any button inside of `p:columns`, method is called multiple times.

### Reproducer

1. Go to test.xhtml
2. Click on any button (for OmniFaces download, make sure to change the path to any local file in your computer in this function `Faces.sendFile(new File("change me"), false);)`
3. See console

[primefaces-test-jakarta.zip](https://github.com/primefaces/primefaces/files/15083300/primefaces-test-jakarta.zip)

### Expected behavior

All actions should be called once.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.8 Jakarta

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

17

### Browser(s)

All browsers

**Comment by BryanV91** [comment]
Feedback here:

https://github.com/omnifaces/omnifaces/issues/801

**Comment by Rapster** [comment]
Did you try with 14 RC3 ?

**Comment by Rapster** [comment]
I have a feeling it's because of this https://github.com/primefaces/primefaces/issues/11685 :(

**Comment by BryanV91** [comment]
I will report back in a few hours with PF14.

**Comment by Rapster** [comment]
same bug in PF 14

**Comment by Rapster** [comment]
@melloware we might have to revert fix https://github.com/primefaces/primefaces/pull/11686... The workaround (and the right way is to not use dynamic rendered with columns)

**Comment by melloware** [comment]
@BryanV91 does this work on PF 13.0.6. Just seeing if this fix is the issue or whether it's always been broken?

**Comment by BryanV91** [comment]
If I remember correctly it will work if I don't use conditional rendering (just rendered=true or filtering the cols to be shown in the backing bean).

**Comment by Rapster** [comment]
I provided a fix, so let's see

**Comment by Rapster** [comment]
Looks good (to be merged in master and 13.0.x)

**Comment by melloware** [comment]
I will backport to 13.x
