### ISSUE TITLE
Tree: Clearing Selection in Backend broken | SingleSelectionMode results in MultiSelectionMode

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#11813]
### Describe the bug

This bug occurs, when performing some UI events in a sequence. See reproducer.

![PrimeFaces-Issue-11813-Reproducer-Screenshot](https://github.com/primefaces/primefaces/assets/107993283/64abd48e-a45c-4666-88b2-91f2237ad0b0)

### Reproducer

[PrimeFaces-Issue-11813-Reproducer.zip](https://github.com/primefaces/primefaces/files/15112109/PrimeFaces-Issue-11813-Reproducer.zip)

### Expected behavior

(see above)

### PrimeFaces edition

Community

### PrimeFaces version

13

### Theme

irrelevant

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

irrelevant

**Comment by melloware** [comment]
This one I am not sure about.  With no `<p:ajax>` AJAX event why should the component send an AJAX request?  And if you want the behavior why not just add `<p:ajax event="select">`?

**Comment by FlipWarthog** [comment]
Agree with @melloware . The selection with no explicit AJAX is normal and this information can alternatively be sent to the server via form submit.

**Comment by RohdeSchwarz-SDC** [comment]
> This one I am not sure about. With no `<p:ajax>` AJAX event why should the component send an AJAX request? And if you want the behavior why not just add `<p:ajax event="select">`?

Because the tree property `selection` is set, which implies an automatic ajax event, doesn't is?

**Comment by RohdeSchwarz-SDC** [comment]
But the real issue is the scenario described (sequence of selection steps)

**Comment by melloware** [comment]
@RohdeSchwarz-SDC i fixed your reproducer:
[pf-11813.zip](https://github.com/primefaces/primefaces/files/15131954/pf-11813.zip)

basically all i added was this

```java
	public void onToggleSwitch() {
		System.out.println("tree.onToggleSwitch -> " + (switchFlag ? "on" : "off"));
		selection = null;	// reset selection;

		// because you are using ViewScoped the `selected` flag is actually inside your TreeNodes
		// you need to update the selection in the treenodes which is how the Tree is rendering
		root.getChildren().forEach(node -> {
			node.setSelected(false);
		});
	}
```

**Comment by RohdeSchwarz-SDC** [comment]
Great, this is a good solution 👍

So you would classify this issue as "wrong use of framework" or is it still a bug and an improvement worth?
