### ISSUE TITLE
Docs: Update SearchExpressions Docs

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11812]
@tandraschko there is no mention of SearchExpression removal in the Migration Guide.

Also this document now seems inaccurate in 14.0.0: https://primefaces.github.io/primefaces/14_0_0/#/core/searchexpression?id=search-expression-framework

For example we just had a project that was doing `@form:dlgCycleStageEditDuration:cycleStageDialogWrapper` which was working in PF 13.0.0 but in 14.0.0 it failed until we modified it to be just `@form:cycleStageDialogWrapper` 

So is the Composite Expressions still valid: https://primefaces.github.io/primefaces/14_0_0/#/core/searchexpression?id=composite-expressions ???

so I think a review of that page making sure everything on there is still correct?

cc @stolp @jepsar @FlipWarthog

**Comment by tandraschko** [comment]
its still valid actually
migration guide is misssing
not sure about your case, would need a example to check if its a bug in the JSF impls or by design

**Comment by melloware** [comment]
I can update the migration guide.

**Comment by melloware** [comment]
OK MIgration Guide updated for Search Expressions: https://github.com/primefaces/primefaces/blob/master/docs/migrationguide/14_0_0.md

> In the past, PrimeFaces used shims to support JSF 2.2 and earlier versions for SearchExpressions. However, with PF 14.0.0 onwards only supporting JSF 2.3+, the handling of Search Expressions now delegates to the core Faces implementation. This shift may lead to errors with SearchExpressions that were functional in PF 13.0.0 but are now failing. It is important to update your SearchExpressions to conform to valid Faces 2.3+ expressions.

**Comment by tandraschko** [comment]
sounds good
