### ISSUE TITLE
AjaxStatus: Not returning to default when located outside the ajax partial submit update scope 

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#11824]
### Describe the bug

I found this as a regression from PF 12.0.7:

When the `p:ajaxStatus` is not contained in the form that is refreshed, completing the action does not reset the status field to the default state.

The `p:ajaxStatus` should be updated in any case.

### Reproducer

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

    <h:head>
      <title>PrimeFaces Test</title>
      <h:outputScript name="test.js" />
      <h:outputStylesheet name="test.css" />
    </h:head>

    <h:body>

      <p:ajaxStatus id="busyStatus" style="display:block; padding: 0">
           
        <f:facet name="default">
        </f:facet>
  
        <f:facet name="start">
          <i class="pi pi-spin pi-spinner"
            style="font-size: 18px; margin-left: 2px margin-top: 2px"></i>
        </f:facet>
     
      </p:ajaxStatus>

      <h:form id="frmTest">

        <p:commandButton value="Submit" action="#{testView.action}" partialSubmit="true" update="@form" />
      </h:form>

    </h:body>
</html>

```

```
package org.primefaces.test;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

import lombok.Data;

@Data
@Named
@ViewScoped
public class TestView implements Serializable {

    public void action() {

        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

```

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-RC3

### JSF implementation

All

### JSF version

2.3

### Java version

21

**Comment by melloware** [comment]
Thanks for the reproducer let me investigate.

**Comment by melloware** [comment]
Confirmed this is working in 13.0.8 but not working in 14.0.0-SNAPSHOT.
[pf-11824.zip](https://github.com/primefaces/primefaces/files/15131366/pf-11824.zip)

**Comment by melloware** [comment]
@tandraschko you got your answers to all your questions you asked in this ticket: https://github.com/primefaces/primefaces/issues/10708

This test case shows the issue.

**Comment by melloware** [comment]
@tandraschko i am submitting a PR I see the issue.

**Comment by melloware** [comment]
@stolp monkeypatched version here:
[pf-11824.zip](https://github.com/primefaces/primefaces/files/15131801/pf-11824.zip)

**Comment by stolp** [comment]
@melloware: Thank you! I tried the monkeypatch and it is working perfectly over here.
