### ISSUE TITLE
Dialog: Position is being reset on scroll

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#11835]
### Describe the bug

When opening a `p:dialog` the position is immediately being reset on scroll, this is happening [here](https://github.com/primefaces/primefaces/blob/92fc32b48268146b75a645af0732121e02237b9c/primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L872) because `responsive` defaults to `true`

### Reproducer

```xhtml
        <h:form id="frmTest">
            <div style="height: 200vh;"/> <!-- Simulate loong content the user can scroll -->

            <p:dialog visible="true">
                Hello world
            </p:dialog>
        </h:form>
```

[pf-11835.zip](https://github.com/primefaces/primefaces/files/15176889/pf-11835.zip)

Drag dialog to other position and scroll

### Expected behavior

Position is not being reset on scroll

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0-SNAPSHOT

### JSF implementation

All

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
@jungm does it work with `responsive="false".` ??

**Comment by jungm** [comment]
@melloware yeah it does, but that also disables resetting the dialogs position when the window is resized.

IMO I'd like to see both work:
- Position is not reset on scroll
- Position is reset when window is resized

**Comment by melloware** [comment]
Ok so I think you are saying you want to separate scrollable and resizable from Responsive?

**Comment by melloware** [comment]
So i looked we do this because when scrolling down the page it forces the dialog to stay centered and scroll down the page.  Is your real issue that you don't want the page to scroll?  You could use `blockScroll="true"` to stop the browser scrollbar while the dialog is displayed?

**Comment by melloware** [comment]
actually does ` positionType="absolute"` fix it to how you want it?

```xml
<p:dialog visible="true" positionType="absolute">
```

**Comment by jungm** [comment]
> So i looked we do this because when scrolling down the page it forces the dialog to stay centered and scroll down the page.

Exactly this is what felt odd to me, I don't want to block scrolling or switch it to absolute positioning. Just that it stays where I left on my screen as I scroll the rest of the page and does not jump back to the original position

**Comment by jungm** [comment]
Actually I just found this https://github.com/primefaces/primefaces/issues/10663
Was in a bit of a rush yesterday and didn't check, this issue is probably a duplicate 🙂 

I'm okay with closing if this is done by design. Still a bit confusing though that the position is reset on scroll IMO but there's probably some edge case this covers I'm not aware of right now

**Comment by melloware** [comment]
OK yeah I will mark by design!
