### ISSUE TITLE
AutoComplete no empty message if forceSelection is false or introduce a new attribute showEmptyMessage

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#11831]
### Description

**Solution 1:**
do not show the emptyMessage if `forceSelection="false"`

**Solution 2:**
introduce a new attribute `showEmptyMessage`

### Describe the solution you would like

If the selection of a suggested element is not mandatory, 
and there are no result from the `completeMethod`, 
usually I'm just writing a new value and 
I'm not interested if the are no suggested values...

**Comment by melloware** [comment]
@pizzi80 can you be a little more clear on your scenario? Maybe a reproducer showing the issue. 
 [PrimeFaces Test](https://github.com/primefaces/primefaces-test)

**Comment by pizzi80** [comment]
if the user is not forced to select an item from the suggested list of values
the empty message only brings confusion, for example

If your type something in the first input in the autocomple showcase, 
the emptyMessage it's not what an user expect ...

https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml?jfwid=d1c1b

![Schermata del 2024-04-29 17-18-27](https://github.com/primefaces/primefaces/assets/17908214/965c0b84-f870-4c47-b6de-029dd9759b62)

**Comment by pizzi80** [comment]
I've found that if you set 
`emptyMessage="#{null}"` or `emptyMessage=""`

the emptyMessage is not displayed

**Comment by melloware** [comment]
Yep i was going to say that but in PF14 this will be different.

**Comment by pizzi80** [comment]
only as a reminder ... the `emptyMessage` attribute it's not documented at all

https://primefaces.github.io/primefaces/13_0_0/#/components/autocomplete?id=autocomplete

**Comment by melloware** [comment]
Yep i was going to say that but in PF14 this will be different as we removed the EmptyMesage property as labels got moved to the client side from the server side.  So in 14 this would be either

MonkeyPatch:
```js
if (PrimeFaces.widget.AutoComplete) {
    PrimeFaces.widget.AutoComplete.prototype.configureLocale = function() {
        this.emptyMessage = '';
        this.resultsMessage = PrimeFaces.getLocaleLabel('searchMessage');
        if (this.dropdown) {
            this.dropdown.attr('aria-label', PrimeFaces.getLocaleLabel('choose'));
        }
    }
};
```

Or change your local to have an empty search label ` this.emptyMessage = PrimeFaces.getLocaleLabel('emptySearchMessage');`

**Comment by melloware** [comment]
i think for 14.0 we need to add `showEmptyMessage` like PrimeReact has https://primereact.org/autocomplete/#api.AutoComplete.props.showEmptyMessage

**Comment by pizzi80** [comment]
probably it's better, in this way you'll cover all the situations ;)

**Comment by gino0631** [comment]
While the `emptyMessage` attribute was not documented, it was working before PF14, and the documentation still has a tip "Use emptyMessage option to provide feedback to the users (...)" (also `emptyMessageSelect` event is documented referring to `emptyMessage`), which is confusing.
It would be useful if the ways to customise the message shown when there are no results were clearly documented.

**Comment by melloware** [comment]
@gino0631 let me update the docs...

**Comment by melloware** [comment]
@gino0631 see: https://primefaces.github.io/primefaces/14_0_0/#/components/autocomplete?id=empty-message
