### ISSUE TITLE
Captcha: command button not working with p:captcha

### ISSUE THREAD

**Issue by Milano337** [primefaces/primefaces#11869]
### Describe the bug

If I use p:captcha, then the submit button of the form is not working. It is just refreshing my captcha. In the backend, the submit button is not hitting my controller and method.
```
<p:captcha label="Captcha" />
```

### Reproducer

xhtml snippet of captcha
```
<div class="form-group">
        <ui:decorate template="/formControl.xhtml">
	        <ui:define name="item-control">
		        <p:captcha label="Captcha" />
	        </ui:define>
        </ui:decorate>
</div>	
```
submit button:
```
 <p:commandButton type="submit" 
        value="Submit" update="@form"
        process="@form"
        id="register-button" escape="false"
        actionListener="#{signupCntl.processDetails}" />
```
Bean:
```
@SessionScope
public class SignUpCntl {
        public void processDetails() {
                // code...
                // Captcha validation
            String gRecaptchaResponse = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("g-recaptcha-response");
            boolean captchaValidated = validateCaptcha(gRecaptchaResponse);
            if (!captchaValidated) {
            	addErrorMessage("Captcha not validated");
                return;
            }
        }
        // code...
}
```

I set a debugger at above if statement, but its not hit. If I remove <p:captcha> then it is hitting the above if statement.

I followed [this](https://zenidas.wordpress.com/recipes/dynamic-recaptcha-api-keys-in-primefaces/) process to fetch the credentials from properties file. 

### Expected behavior

I want the captcha in my form. It should be validated when I submit the form. With above code, it is not calling my submit method, instead it is refreshing the captcha.

### PrimeFaces edition

None

### PrimeFaces version

13.0.4

### JSF implementation

MyFaces

### JSF version

4.0.1

### Java version

17

### Browser(s)

Chrome

**Comment by melloware** [comment]
Do you need type="submit" ?   What happens if you remove that?  I feel like you might be getting a validation error?

**Comment by Milano337** [comment]
> Do you need type="submit" ? What happens if you remove that? I feel like you might be getting a validation error?

No, its not working. Its not showing any error anywhere.

**Comment by Milano337** [comment]
Found a way. I had to do ``` ajax="false" ``` in my command button.

Hence, closing this issue.

**Comment by melloware** [comment]
Thanks for reporting back!
