### ISSUE TITLE
SONAR: Fix JS issues

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#11863]
### Description

see https://sonarcloud.io/project/issues?languages=js&resolved=false&id=org.primefaces%3Aprimefaces

### Describe the solution you would like

less issues

**Comment by tandraschko** [comment]
before you working on a PR, we should first check some rules if they make really sense

**Comment by Rapster** [comment]
Sure, I don't necessarly plan to work on this (tough I could...) but at first glance, all issues seem valid to me
