### ISSUE TITLE
JDK8: `org.json` dependency causes java version mistatch

### ISSUE THREAD

**Issue by hasanyildiz** [primefaces/primefaces#11870]
### Describe the bug

i am using primefaces with running on jdk 8 wtih this dependency of

`
<dependency>
<groupId>org.primefaces</groupId>
<artifactId>primefaces</artifactId>
<version>13.0.8</version>
</dependency>
`

which contains a dependency of
`
 <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <optional>true</optional>
        </dependency>
`.

this org.json dependency has this code block

`
<execution>
                        <id>add-module-infos</id>
                        <phase>package</phase>
                        <goals>
                            <goal>add-module-info</goal>
                        </goals>
                        <configuration>
                            <jvmVersion>9</jvmVersion>
                            <module>
                                <moduleInfoSource>
                                    module org.json {
                                        exports org.json;
                                    }
                                </moduleInfoSource>
                            </module>
                        </configuration>
                    </execution>
`

which causes my application to run on jdk 8 which causes
`java.lang.UnsupportedClassVersionError: Failed to link META-INF/versions/9/module-info (Module "deployment.app.war" from Service Module Loader): META-INF/versions/9/module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only `
exception.

this is not happening when using version 13.0.7.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.8

### JSF implementation

All

### JSF version

2.2

### Java version

1.8

**Comment by melloware** [comment]
We must keep JDK8 compatability for 13.x and I opened a ticket at `org.json` here: https://github.com/stleary/JSON-java/issues/892

I have an easy workaronud that when we shade the JAR i have to remove that `META-INF/versions/` folder.

**Comment by GedMarc** [comment]
Jdk8 isn't aware of meta-inf/versions, I do not think that would be the issue, 

Hmm, it only makes sense if org.json ri is compiled in jdk9 or higher, 

Pity about backwards compatibility,  when is support for eol jdk8 to end?

**Comment by melloware** [comment]
@GedMarc PrimeFaces 14.0.0 is out and its JDK11 only and JSF 2.3+ only however PF 13 is the last version to support JDK and JSF less than 2.3.  So I have a feeling the 13.X version will be used for a long time until people can upgrade.

**Comment by melloware** [comment]
13.0.10 deployed to Maven Central.
