### ISSUE TITLE
FileUpload (advanced): DragAndDrop not working, javascript error

### ISSUE THREAD

**Issue by albfernandez** [primefaces/primefaces#11879]
### Describe the bug

If you drop a file into a fileupload with dragDropSupport="true" or a custom zone dropZone="customDropZone", then a javascript error is logged to the console and the file is not uploaded

### Reproducer

To reproduce the error you can use the Primefaces showcase.
In the showcase, navigate to ```/showcase/ui/file/upload/dnd.xhtml```
Then drag a supported file (jpeg, gif or png file of max size 100kb) from the file explorer to the fileupload component or the associated drop zone.
An error is logged to the javascript console and the file is not processed/uploaded.

Currently (2024-05-06), the showcase at Primefaces [http://www.primefaces.org/showcase/ui/file/upload/dnd.xhtml?](http://www.primefaces.org/showcase/ui/file/upload/dnd.xhtml) uses Primefaces version 13.0.9 and it works as expected.

If you build and run the showcase for 14.0.0 or the latest 15.0.0-SNAPSHOT in your computer it fails.

This javascript error is logged to the console (Chrome)
```
jQuery.Deferred exception: Cannot read properties of undefined (reading 'data') TypeError: Cannot read properties of undefined (reading 'data')
    at HTMLDivElement.add (http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:2035:48)
    at $.<computed>.<computed>._trigger (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=14.0.0:717:13)
    at File.<anonymous> (http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:1375:23)
    at Function.each (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:3129)
    at $.<computed>.<computed>._onAdd (http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:1368:9)
    at $.<computed>.<computed>._onAdd (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=14.0.0:143:25)
    at http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:1629:18
    at c (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:25304)
    at fireWith (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:26053)
    at e (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:27300) undefined
```

### Expected behavior

A message confirming the file have been uploaded

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

Tested in Chrome and Firefox

**Comment by melloware** [comment]
PR submitted. Thanks for the report!

**Comment by christophs78** [comment]
Related issues which triggered refactorings for 14.0.0: https://github.com/primefaces/primefaces/issues/11001, https://github.com/primefaces/primefaces/issues/11043, https://github.com/primefaces/primefaces/issues/11044

We may have to look into the assigned commits.

Up to 13.0.x following JS was rendered:

```js
pf.cw("FileUpload","widget_j_idt342_j_idt344",{id:"j_idt342:j_idt344",resumeContextPath:"\/showcase\/file\/resume\/",mode:"advanced",update:"j_idt342:messages",maxFileSize:100000.0,allowTypes:/(\.\|\/)(gif\|jpe?g\|png)$/});
```

Starting with 14.0.x maxFileSize is rendered into HTML:
```html
<input type="file" id="j_idt247:j_idt249_input" name="j_idt247:j_idt249_input" aria-hidden="true" tabindex="-1" data-p-label="Choose" data-p-sizelimit="100000" data-p-allowtypes="/(\.|\/)(gif|jpeg|jpg|png)$/" data-p-val="primefaces.File" />
```
```js
pf.cw("FileUpload","widget_j_idt247_j_idt249",{id:"j_idt247:j_idt249",mode:"advanced",update:"j_idt247:messages"});
```

The missing link is to find a way to access data-p-sizelimit also during drag´n´drop.

**Comment by christophs78** [comment]
Idea 1:
![image](https://github.com/primefaces/primefaces/assets/10461942/ee9ba16e-1d58-4fbf-a787-5789c0aa128a)

**Comment by christophs78** [comment]
Ok - now i understand why @melloware gave up on this ...

Doing following is only a small part of the solution:
```js
var dataFileInput = data.fileInput ? data.fileInput : $('#' + $.escapeSelector(data.paramName + '_input'));
```

The other issue is following:
![image](https://github.com/primefaces/primefaces/assets/10461942/e18a759a-60bc-4184-9f00-d9fafa769d82)

![image](https://github.com/primefaces/primefaces/assets/10461942/d093de35-7daf-4cb8-83d1-87f3a28eaeb9)

At this point any quick solution seems to be out of scope. At least for now. p:FileUpload Drag´n´Drop - support is gone for now.

**Comment by christophs78** [comment]
Added a commit with part of a possible solution.

But it still fails for more than one file because of:
![image](https://github.com/primefaces/primefaces/assets/10461942/d7019efa-5f4e-4ad5-8c0e-cf9f83da6a07)

Maybe someone else can come up with further ideas.

**Comment by melloware** [comment]
@christophs78 you have come to a similar place where I landed so I just fixed the NPE to at least restore the drag and drop functionality.
