### ISSUE TITLE
Integration-tests: move to JakartaEE (10)

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#11877]
### Description

Similar to #11433. 
And kick out primefaces-integration-tests-jakarta which are a small subset of our whole test-suite.

Maybe provide a small set of IT´s which run against JSF 2.3 / JavaEE.

**Comment by tandraschko** [comment]
hmmm
im a bit unsure about this
as long we have javax users, we are more safe with the current approach

**Comment by melloware** [comment]
If anyone is interested I can use OpenRewrite and convert all the Javax tests into the Jakarta test so we run the same test suite on both?  yes it is duplicating code and we have to update tests in 2 places but with the popularity of Faces 4.0 picking up maybe its worth it to have both full test suites?

**Comment by tandraschko** [comment]
i would not duplicate for now and leave as it is, until we remove javax support
i dont think its worth to do something now

**Comment by melloware** [comment]
ok

**Comment by melloware** [comment]
I think we have decided that this is a no for now?

**Comment by tandraschko** [comment]
yeah, i would not change anything until 15.0 is released

i think we need to discuss first, when we drop javax support in general?
When we drop it soon, we can simple remove all javax stuff.
Otherwise i wouldnt change anything for now.
