### ISSUE TITLE
Charts axis ticks are not completely visible

### ISSUE THREAD

**Issue by imrankhurram-checkit** [primefaces/primefaces#11886]
### Describe the bug

Charts axis ticks are not completely visible as something is drawn on the canvas over the ticks. It looks like this is a bug in Primefaces 12 but is there any workaround? Below are samples:

![image](https://github.com/primefaces/primefaces/assets/64078961/c0a5910b-0de5-4ee3-bfed-cf2f7f4de789)
Here you can see most of the x-axis ticks are not visible completely

![image (2)](https://github.com/primefaces/primefaces/assets/64078961/aafaaab5-50f8-4928-b28f-0bd2a56a252a)
Here you can see the second and third x-axis ticks are not visible completely.

### Expected behavior

Ticks should be readable.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

10

### Java version

21

### Browser(s)

Chrome and all others

**Comment by jepsar** [comment]
Can you please try with version 14? 12 is not supported by the community.

**Comment by imrankhurram-checkit** [comment]
The trouble is I cannot update the complete app with version 14 at the moment. May be in the future I can push that but I have to provide this fix ASAP

**Comment by jepsar** [comment]
Again, 12 is not supported by the community. We cannot merge pull requests to 12. See https://github.com/primefaces/primefaces?tab=readme-ov-file#community--elite--pro

You can alway use https://github.com/primefaces/primefaces-test to create a reproducer. No need to migrate your application.

**Comment by jepsar** [comment]
Also, if this concerns the old charts, they have been removed in 13. https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0

**Comment by imrankhurram-checkit** [comment]
as I have mentioned its Primefaces 12 so yes it is using Jqplot. Why you are asking me to create reproducer in new version if I don't want to migrate? if the new version is not having the issue, I am still in trouble as I have to use this same version. Please provide me a workaround in the same 12 version. You don't need to merge pull requests, just tell me what is the fix?

**Comment by jepsar** [comment]
> as I have mentioned its Primefaces 12 so yes it is using Jqplot

FYI it supports both jqPlot and Chart.js

**Comment by melloware** [comment]
Your best best as mentioned is to get away from JqPlot as it has not had a commit in 6 years
