### ISSUE TITLE
DataTable: Select/unselect all with selectionPageOnly="false" does not work properly

### ISSUE THREAD

**Issue by chaloma1** [primefaces/primefaces#11885]
### Describe the bug

Having a dataTable with selectionPageOnly="false" and paginator so i could select/unselect all items in a table. If i select all items in column header checkbox, it works fine, then i press button which processes whole form. After that i press the same checkbox to unselect all, but only single page is unselected. 

Whole functionality works badly, for example if i select all and unselect all right after, it works.. but if i press the button between those steps or sometimes even just changing page, it does not unselect for all pages.

### Reproducer

[datatableUnselectAll.zip](https://github.com/primefaces/primefaces/files/15234012/datatableUnselectAll.zip)

### Expected behavior

When selectionPageOnly="false" is set, i would expect it to work also for unselecting all items across all pages.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.9

### JSF implementation

Mojarra

### JSF version

4.0.6

### Java version

17

**Comment by tandraschko** [comment]
Can you please try 14.0?

**Comment by chaloma1** [comment]
Tried with PrimeFaces 14.0.0, had to replace selection column parameter selectionMode="multiple" for selectionBox="true".

Bug still exists.

**Comment by melloware** [comment]
I think it might be related to this: https://github.com/primefaces/primefaces/issues/11556

**Comment by chaloma1** [comment]
When i look at the 15.0.0 milestone label. I would appreciate, if this fix could be also pushed into 13.11 elite version. I will not be able to update 2 major versions in near future. Thank you.

**Comment by melloware** [comment]
@chaloma1 it will have to go in 14.0.1 as once we are on a new major release the community is only supposed to update 1 version back.

**Comment by martin654** [comment]
@melloware  Hi, this was marked as "Elite" so it would be fixed in 13.x.x version. Should we create ticket in PRO Jira for this?

**Comment by melloware** [comment]
@martin654 Yes please open a PRO JIRA to have this backported to 13.x.x
