### ISSUE TITLE
BooleanCheckbox: duplicates ui-state-disabled

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#11889]
### Describe the bug

When setting `disabled="true"` for an `<p:outputLabel>`, the resulting html element does not contain a `ui-state-disabled` class

### Reproducer

```
<!DOCTYPE html>
<h:html lang="en"
   xmlns="http://www.w3.org/1999/xhtml"
   xmlns:h="http://xmlns.jcp.org/jsf/html"
   xmlns:p="http://primefaces.org/ui">
   <h:head>
      <title>Test</title>
   </h:head>
   <h:body>
      <h:outputStylesheet>
         .ui-selectbooleanbutton.ui-button.ui-widget {width:1.5em; height:1.5em; position:relative; top:0.5em}
         .ui-outputlabel {margin-left:0.5em}
         .ui-state-disabled {opacity:0.3 !important}   /* reduce opacity to demonstrate the effect more clearly */            
      </h:outputStylesheet>
      
      <p:selectBooleanButton value="#{bean.option1}" onIcon="pi pi-check" offIcon="pi pi-times" disabled="true"/>
      <p:outputLabel for="@previous" value="First Option" disabled="true" />
      
      <p:divider/>
      
      <p:selectBooleanCheckbox itemLabel="Second Option" value="#{bean.option2}" disabled="true" />
   
   </h:body>
</h:html>
```
![Issue-11889-Behaviour-Actual](https://github.com/primefaces/primefaces/assets/107993283/7bc0f94c-e2fa-476f-9f79-734e085b993c)

### Expected behavior

The disabled label "First Option" should have the `ui-state-disabled` css class thus appearing grey.

![Issue-11889-Behaviour-Expected](https://github.com/primefaces/primefaces/assets/107993283/7fce6ec0-98d5-4a5a-935d-6226dbd29121)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.9

### Theme

default

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

irrelevant

**Comment by RohdeSchwarz-SDC** [comment]
**Side Note:**

Why does the `ui-state-disabled` class appear twice in this element?

![Issue-11889-SideNote-Duplicate-CssClass](https://github.com/primefaces/primefaces/assets/107993283/dce5d707-5fde-4f1f-a00b-aed08cf48bf5)

**Comment by melloware** [comment]
Let me check on both...

**Comment by melloware** [comment]
@RohdeSchwarz-SDC I am fixing the duplicate `ui-state-disabled` However for OutputLabel as @tandraschko mentioned simply use `styleClass="ui-state-disabled"` as Labels in HTML cannot be disabled.
