### ISSUE TITLE
Datatable: Values in editable fields not changing after removing rows

### ISSUE THREAD

**Issue by Vikkear** [primefaces/primefaces#11893]
### Describe the bug

I have some issues with Datatables with editable fields when rows are getting removed.

When I remove a row from a datatable, it looks like the editable fields stays in the same spot even though rows are changed.

For instance, if my second row value is "Los Angeles" and I remove that row. Then the "Los Angeles" value is still in the second row even though I just deleted the row. It looks like readonly fields such as p:outputLabel looks correct though so this probably only applies to editable fields.

I have also tested the same in PrimeFaces 14.0.0 and it looks like the issue is there as well

### Reproducer

https://github.com/Vikkear/primefaces-test-datatable-ajax-bug/tree/datatable-removal-textfield-bug

1. Go to page
2. Press the "Remove" button on the "Los Angeles" row
3. A row is removed but the "String col" column is still "Los Angeles" and all of the readonly fields looks correct

It looks like the values in the String column has been shifted down one step:
Before:
![image](https://github.com/primefaces/primefaces/assets/13707452/082b6f6a-cb25-40b0-b2c8-eab2b85e7ce8)

After pressing remove on id 2 (Los Angeles):
![image](https://github.com/primefaces/primefaces/assets/13707452/f8df969a-8247-4b83-b89a-4b5b8d354239)

### Expected behavior

In the example above, the String column on the second row should be "Philadelphia" after the removal of row 2

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.9

### Theme

nova-light

### JSF implementation

Mojarra

### JSF version

5.1.2

### Java version

17.0.6

### Browser(s)

Version 124.0.6367.119 (Official Build) (64-bit)

**Comment by Vikkear** [comment]
To add a bit to this. The PrimeFaces version that I've used before is 6.1 and there it works as I've described in "Expected behaviour". Yes I realize that it's quite a big version leap :)

**Comment by melloware** [comment]
That is a big leap 😄 from 6-14.  But no doubt the DataTable has undergone massive improvements and refactoring in that time.

**Comment by Rapster** [comment]
You need to do a full update request of the datatable before filtering, e.g:

```xml
<p:column field="decimalCol">
    <p:commandButton value="Remove" action="#{testView.removeTestJpa(row)}" update="tblJpa" oncomplete="PF('jpaTable').filter();"/>
</p:column>
```

More details here: https://stackoverflow.com/a/20146879
