### ISSUE TITLE
PFExtensions Migration: Timeline

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1189]

**Comment by tandraschko** [comment]
Just 2 cents from my side:
1) i would move TimelineEventComparator to the event.timeline package instead util, as it's not generic.
2) i would try to use the WidgetBuilder if possible but this must be evaluated before.

**Comment by ova2** [comment]
Another 2 cents from my side:

I don't know if you know or not, but there is a new library for the used native timeline script: http://visjs.org/ It should be compatible with the old script, it just fixes some limitations and adds new feature. But be aware - some feature in the Timeline component were implemented by me and are not available in the native script. These are e.g. lazy loading of events and drag-&-drop.

**Comment by mertsincan** [comment]
Thank you very much, @tandraschko and @ova2. I'll work on your suggestions.

**Comment by ova2** [comment]
I have seen that currently only one basic example is implemented in the Showcase. Do you plan to add all other use cases too?
