### ISSUE TITLE
Watermark and InputMask causes conflict on Internet Explorer 11

### ISSUE THREAD

**Issue by MohamedKhorshid** [primefaces/primefaces#119]
I'm using primefaces 3.5, I've got a wierd behavior when the client upgraded on IE 11. The page used many input masks with watermark attribute within.

This is the page I used to test it

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head></h:head>
    <p:inputMask mask="999999" id="m">
        <p:watermark value="123456" for="m" />
    </p:inputMask>
    <p:inputMask mask="999999" id="n">
        <p:watermark value="123456" for="n" />
    </p:inputMask>
</ui:composition>
```

The browser keep jumping the cursor between the 2 fields continuously till I navigate to another window and revert back to IE again.

**Comment by tandraschko** [comment]
does it work with 5.2?
It would be sooo much easier if users would test on the newest version before creating a issue.

**Comment by cagataycivici** [comment]
Try with 5.2 please. 3 and 4 are not supported anymore.

**Comment by kukel** [comment]
and use the forum first next time plese...

**Comment by kukel** [comment]
And to prevent issues like these becomming 'waste' like in the google issue list, maybe they should be closed directly..

**Comment by cagataycivici** [comment]
Yes, we've a fresh start for issues in GitHub and we'll make sure it doesn't end up as waste this time.
