### ISSUE TITLE
FileUpload (advanced): Multiple FileUpload - regressions when some files do not meet the limits

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#11900]
#### Uploading following files
![image](https://github.com/primefaces/primefaces/assets/10461942/590be54d-0ad5-4b55-94c7-7018b5c27d52)

#### 13.0.x
![image](https://github.com/primefaces/primefaces/assets/10461942/4ed9e774-b69d-4b0d-bd28-9458a53d9865)

#### 14.0.0
![image](https://github.com/primefaces/primefaces/assets/10461942/a981ba23-dad0-4989-a85c-d3905def3a5c)

#### Regressions
- only one error is shown
- after one error no further files are processed

Related to refactorings done for 14.0.0 as part of https://github.com/primefaces/primefaces/issues/11001, https://github.com/primefaces/primefaces/issues/11043, https://github.com/primefaces/primefaces/issues/11044

### Reproducer

https://primefaces.org/showcase/ui/file/upload/multiple.xhtml
Select multiple files. Some within the size-limit. Some to big ones.

**Comment by christophs78** [comment]
Did some analysis....

Why do we get only one validation-error?
![image](https://github.com/primefaces/primefaces/assets/10461942/47a95004-65b0-47e9-a099-13e173cede84)

And - once there is any validation error nothing is uploaded any more:
![image](https://github.com/primefaces/primefaces/assets/10461942/48f375d5-0721-4973-bcd2-40624e687e3a)

So IMO a good amount of refactorings is required to restore the behaviour we had up to 13.0.x.
(Show a message for each file which does not meet´s the requirements. Allow to upload that part of files which meet the requirements.)

All of this is independent of (explicit) using CSV or using drag´n´drop - feature.

@tandraschko : I think we need at least your thoughts about this.

**Comment by tandraschko** [comment]
yeah, seems that the FileValidator would need to throw a array of msgs
this is a bigger refactoring

**Comment by christophs78** [comment]
I´ll try to look at the one message per invalid file. Maybe this is something we can fix for 14.0.x too.
