### ISSUE TITLE
WIKI: clean up

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#11912]
### Description

Wiki pages are bit of a mess:

- [x] the index page is empty
- [x] contributing redirect to the contributing.md
- [x] locales redirects to another page

We should get rid of those last two. The index page could contain the building from source page, maybe more, also some indication per IDE (import settings for intellij, eclipse, vscode) etc.

### Describe the solution you would like

something awesome

**Comment by melloware** [comment]
OK changes made check it out!  I also cleaned up and updated the building from Source instructions to use better Markdown formatting.

**Comment by Rapster** [comment]
@melloware don't you think it could be also the right place to display these https://web.archive.org/web/20230606161941/https://jsf.zeef.com/bauke.scholtz# ?

**Comment by melloware** [comment]
Absolutely.  That would be awesome.  If we could get the real URLs we could do it the Wayback seems to have messed up some of the URLs?  Cc @FlipWarthog

**Comment by Rapster** [comment]
Found this one as an alternative: https://archive.md/20160628025243/https://jsf.zeef.com/bauke.scholtz

**Comment by melloware** [comment]
Awesome. Yep I will work on that this week!

**Comment by melloware** [comment]
@FlipWarthog @Rapster heard back from BalusC he had already recreated it here: https://balusc.omnifaces.org/2024/03/jsfzeefcom-is-down.html

**Comment by FlipWarthog** [comment]
What kind of IDE info are you thinking? I can start working on a VS Code set up guide.

**Comment by Rapster** [comment]
> @FlipWarthog @Rapster heard back from BalusC he had already recreated it here: https://balusc.omnifaces.org/2024/03/jsfzeefcom-is-down.html

Perfect!

> What kind of IDE info are you thinking? I can start working on a VS Code set up guide.

Something even as a committer I still stuggle with, which is code format... We have checkstyle for eclipse, nothing concrete for Intellij, yet I think it's possible to import eclipse checkstyle in Intellij, I can figure this last one out. No idea about vscode

**Comment by FlipWarthog** [comment]
Okay, got it. I do have checkstyle working with vscode so I'll throw together a quick setup guide

**Comment by FlipWarthog** [comment]
Here's what I came up with; most of the heavy lifting was already done in the primefaces-test guide... I realized while I was putting this together that I don't have formatting right for Java files (@melloware I might bug you about this)


# Visual Studio Code

## Prerequisites (Basic setup)

1. Complete [Buliding Primefaces Snapshots](https://github.com/primefaces/primefaces/wiki#building-primefaces-snapshots)
2. Complete [primefaces-test Visual Studio Code Quickstart](https://github.com/primefaces/primefaces-test/blob/master/vscode-quickstart.md)

## Checkstyle

1. Download latest [Checkstyle jar](https://github.com/checkstyle/checkstyle/releases/)
   - Path to the JAR will be used later; it's recommended that you move it into your Visual Studio Code directory
   - Note: this is not the same checkstyle JAR that will be in your .m2 repository after building PrimeFaces
2. Install [Checkstyle](https://marketplace.visualstudio.com/items?itemName=rianadon.vscode-java-checkstyle) extension in Visual Studio Code
3. Enable Checkstyle extension by configuring the following settings:
```json
    "checkstyle.checkstylePath": "C:\\path\\to\\checkstyle-10.16.0-all.jar",
    "checkstyle.configurationPath": "C:\\path\\to\\primefaces-checkout\\primefaces\\conf\\checkstyle.xml",
```

**Comment by Rapster** [comment]
Looks good, I added a new page (to complete)

**Comment by Rapster** [comment]
@melloware I know we discussed imports in the past, each IDE has their own order... which one should we use? From what I can see, the trend today is either intellij or vscode but I also wonder, regarding the PF community only, what do we use as commiters?

**Comment by melloware** [comment]
@Rapster my personal preference is this order but I can be convinced otherwise

```
java.*

javax.* or jakarta.*

com.*

org. *

```

**Comment by Rapster** [comment]
My preference is what my IDE does 😅  (I personnaly don't care what the order is...)

IntelliJ looks like this

```
java.*

javax.* or jakarta.*

OTHERS
OTHER STATIC IMPORTS
```

**Comment by melloware** [comment]
We could use https://code.revelc.net/impsort-maven-plugin/ and take the decision out of everyone's hands?

**Comment by melloware** [comment]
@Rapster either way if you document it we can all just set our IDE's the same way but at least we will have documented it :)

**Comment by melloware** [comment]
I just updated the VS code wiki and I am finding VSCode so nice and fast for doing PF development!   I posted my tweaks to make sure everything is working as expected.  Still working out how to do the more than 5 imports switch to a `.*` as i had in Eclipse but can't find anything similar yet in VSCode.

**Comment by tandraschko** [comment]
TBH we should add a checkstyle for imports
almost all PRs contains useless reorders or star order changes

**Comment by tandraschko** [comment]
and IMO we should also avoid star imports and static imports as it causes conflicts when you upgrade libs and just makes everything more explicit
thats how we configured it all the apache libs im working on

**Comment by tandraschko** [comment]
```
        <module name="AvoidStarImport">
            <property name="excludes" value="org.primefaces.*"/>
        </module>
        <module name="AvoidStaticImport" />
        <module name="ImportOrder">
            <property name="groups" value="/^org\.primefaces/,java\./,javax,jakarta"/>
            <property name="separated" value="true"/>
        </module>
```

**Comment by tandraschko** [comment]
that is by the way the default checkstyle order:

- STATIC has top priority
- SAME_PACKAGE has second priority
- STANDARD_JAVA_PACKAGE and SPECIAL_IMPORTS will compete using "best match" rule: longer matching substring wins; in case of the same length, lower position of matching substring wins; if position is the same, order of rules in configuration solves the puzzle.
- THIRD_PARTY has the least priority

which is the same as the groups above

**Comment by melloware** [comment]
@tandraschko i like this idea so we fix it once and for all. The Quarkus team uses Impsort plugin: https://code.revelc.net/impsort-maven-plugin/index.html which fixes the imports automatically on any compile before check-in?

**Comment by tandraschko** [comment]
i dont like plugins which modify sources TBH
and if we added the check, nothing will happen in future anymore
so we dont need it actually

**Comment by melloware** [comment]
ok i like it want me to submit a PR with the checkstyle update?

**Comment by tandraschko** [comment]
i will take care of this one

**Comment by tandraschko** [comment]
should we close this issue @melloware?

**Comment by melloware** [comment]
Yep I have updated VSCode pretty thoroughly not sure and we have refactored it so i will close.

**Comment by tandraschko** [comment]
i dont think you can, thats the directory intellij directlry reads the config
and .run folder brings a benefit, intellij users dont need to add run configs after each checkout

**Comment by Rapster** [comment]
You can import these settings, and you only have to create that runconfig, I would agree if you were referring to primefaces-test which I already commit, but ideally no IDE stuff in repo (or in a separate folder for a clean structure)

**Comment by tandraschko** [comment]
Run config isnt that important for me but its much better to automatically have the Codestyle in .idea,
compared to manually import from a config directory.

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/pull/12662
