### ISSUE TITLE
Core: Support URN and URI Namespaces?

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11914]
To catch up Faces itself, migrate XML namespaces as well:

`http://primefaces.org/ui --> primefaces.ui`

### Current:
```xml
xmlns:p="http://primefaces.org/ui"
```

### To:
```xml
xmlns:p="primefaces"
```

Hopefully there is a clever way to support both?

**Comment by tandraschko** [comment]
+1 if we can simply support it
not sure if possible, i think you need to check the impl code or my commits, how i implement it in myfaces
