### ISSUE TITLE
Can we remove p:resetInput?

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#11916]
It was actually built before JSF 2.2 or 2.3 introduced resetValues attribute. 
Not sure if there are cases where resetValues is not enough or available?

in theory the difference is that p:resetInput could target any component, however resetValues only targets all components in the update/render attr.
But if you dont update the component, a reset is useless anyway?!

**Comment by tandraschko** [comment]
in your case you can just remove p:resetInput and add resetValues=true, should work

**Comment by DazzlingBob** [comment]
What about a programmatically reset like "PrimeFaces.current().resetInputs("form:panel")"?
Very unfortunate if that is not possible anymore.

**Comment by melloware** [comment]
> What about a programmatically reset like "PrimeFaces.current().resetInputs("form:panel")"? Very unfortunate if that is not possible anymore.

@DazzlingBob no i think its just removing the tag `<p:resetInput>` all else would remain i believe.

**Comment by tandraschko** [comment]
Yeah
Only the tag

**Comment by DazzlingBob** [comment]
I'm not in favor of removing p:resetInput.
The following construction is used a lot in our projects :

```
<p:commandLink title="Title"
  action="#{bean.doAction(data)}"
  update=":mainform:tabContainer:container :mainform:containerA :mainform:containerB :mainform:containerC"
  rendered="#{not empty data.id}"
  process="@this">
  <p:resetInput target=":mainform:tabContainer:container" />
</p:commandLink>
```

Only inputs in :mainform:tabContainer:container are reset.
Other containers like :mainform:containerA keep there input values, in our case often input search criteria with the search result as text. The search result can change though database transactions/bean.doAction.

The official JSF 2.2 definition of resetValues="true" is: "JSF resets all input components specified in the render attribute."
For example: <f:ajax render="field1" resetValues="true"/>

So:
```
<p:commandLink title="Title"
  action="#{bean.doAction(data)}"
  update=":mainform:tabContainer:container :mainform:containerA :mainform:containerB :mainform:containerC"
  rendered="#{not empty data.id}"
  process="@this"
  resetValues="true">
</p:commandLink>
```

Means all inputs of containers mentioned in "update" (in JSF: the render tag) will reset.
What is not correct in this situation.

When the tag p:resetInput is removed the only solution is to add in method bean.doAction:

`PrimeFaces.current().resetInputs(":mainform:tabContainer:container");
`

Which is correct, but is less semantic/visible then a p:resetInput tag.
