### ISSUE TITLE
Add an Excel exporter which takes advantage of the new Apache Poi Streaming API

### ISSUE THREAD

**Issue by ivolucas** [primefaces/primefaces#1192]
Add an Excel exporter which takes advantage of the new Apache Poi Streaming API.

> SXSSF (package: org.apache.poi.xssf.streaming) is an API-compatible streaming extension of XSSF to be used when very large spreadsheets have to be produced, and heap space is limited. SXSSF achieves its low memory footprint by limiting access to the rows that are within a sliding window.
#1191

**Comment by tandraschko** [comment]
Applied the PR - thanks!
