### ISSUE TITLE
TreeTable: After quick select deselect the checkboxes of the subtree are still selected

### ISSUE THREAD

**Issue by aklein2024** [primefaces/primefaces#11934]
### Describe the bug

In a TreeTable a check boxes can have three different statuses.

- The checkbox should be blank if a node and all sub nodes off this node has not been selected.
- The checkbox should contain a hyphen if a least one sub node has been selected and one sub node has not.
- The checkbox should be checked if all sub nodes has been checked, the checkbox self has been checked or the parent checkbox has been checked

![image](https://github.com/primefaces/primefaces/assets/158480838/74ed21a9-5034-4d64-90b2-e296e791e71c)

When all check boxes has been deselected and the user makes a quick select and deselect of a checkbox, the statuses of the actual node and there sub nodes get corrupted.

Instead of all nodes being deselected, all sub nodes are selected. In addition, the statuses of the nodes are no longer displayed correctly.

![image](https://github.com/primefaces/primefaces/assets/158480838/29f31f46-ecb5-4663-9fc4-cb07708e726a)

### Reproducer

1. git clone https://github.com/primefaces/primefaces.git
2. cd primefaces
3. checkout version 13.0.10
4. mvn clean install 
5. cd primefaces-showcase
6. mvn -Ddev
7. open the URL http://localhost:8080/showcase/ui/data/treetable/selection.xhtml?jfwid=4b74d in the browser
8. Scoll down to the TreeTable Checkbox Selection showcase
9. Make sure that all check boxes are deselected
10. Make a quick select and deselect on the **Documents** checkbox
11. Now the **Documents** Checkbox is deselected and the check boxes of all sub nodes are selected.

### Expected behavior

I would expect that after a quick select and deselect the check boxes of all sub nodes are deselected.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.10

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

JDK 11

### Browser(s)

FireFox 125.0.3 (64-bit)

**Comment by melloware** [comment]
I think this is sort of already reported in these two tickets:

https://github.com/primefaces/primefaces/issues/10217

https://github.com/primefaces/primefaces/issues/9925

**Comment by melloware** [comment]
@aklein2024 i can't reproduce: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/treetable/selection.xhtml?jfwid=acc74

I am clicking as fast as I can?

**Comment by melloware** [comment]
![treetable](https://github.com/primefaces/primefaces/assets/4399574/e1ca6fe0-c46d-47f7-bbec-7117f4e0936c)

**Comment by melloware** [comment]
See my recording above...  Clicking as fast as I can.

**Comment by melloware** [comment]
@FlipWarthog @jepsar can either of you reproduce this?

**Comment by aklein2024** [comment]
I can not find a tool to record my screen. How did you do it?

**Comment by melloware** [comment]
I used Screen2Gif open source tool.

**Comment by aklein2024** [comment]
![reproduction](https://github.com/primefaces/primefaces/assets/158480838/943149b0-e8dd-495c-bd3f-3754ec591a4d)

**Comment by melloware** [comment]
OK that helps.  Its Firefox only...I can't reproduce on Chrome or Edge.

**Comment by aklein2024** [comment]
I can reproduce it on chrome too.
For any reason the selection of check boxes produces a request to the backend and the deselection is handled totally in the client.
I have the feeling that if the user clicks quickly enough, the processing of the deselecting is already completed before the response to the deselecting request has been processed in the client.

**Comment by melloware** [comment]
Yep definitely a timing issue and i bet the network response time from where you are is slower than mine which is why you see if more obviously.

**Comment by melloware** [comment]
@aklein2024 can you try this MonkeyPatch...

```js
if (PrimeFaces.widget.TreeTable) {
    PrimeFaces.widget.TreeTable.prototype.fireSelectNodeEvent = function(nodeKey) {
        if (this.isCheckboxSelection()) {
            var $this = this,
                options = {
                    source: this.id,
                    process: this.id
                };

            options.params = [{
                name: this.id + '_instantSelection',
                value: nodeKey
            }];

            var checkboxSelector = this.cfg.nativeElements ? '> tr.ui-treetable-selectable-node > td:first-child :checkbox' :
                '> tr.ui-treetable-selectable-node > td:first-child div.ui-chkbox-box';
            this.tbody.find(checkboxSelector).addClass('ui-state-disabled');

            options.oncomplete = function(xhr, status, args, data) {
                if (args.descendantRowKeys && args.descendantRowKeys !== '') {
                    var rowKeys = args.descendantRowKeys.split(',');
                    for (var i = 0; i < rowKeys.length; i++) {
                        $this.addToSelection(rowKeys[i]);
                    }
                    $this.writeSelections();
                }

                $this.tbody.find(checkboxSelector).removeClass('ui-state-disabled');
            }

            if (this.hasBehavior('select')) {
                this.callBehavior('select', options);
            } else {
                PrimeFaces.ajax.Request.handle(options);
            }
        } else {
            this.fireSelectEvent(nodeKey, 'select');
        }
    }
}
```

**Comment by aklein2024** [comment]
I will try that tomorrow morning CEST when you give me a hint where to put this piece of code.

**Comment by melloware** [comment]
i also deployed the patch out here too: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/treetable/selection.xhtml?jfwid=04870

You can test it on my showcase but in your own project you just need to load that script in any JS file that loads after PrimeFaces.

**Comment by aklein2024** [comment]
I tested it in your showcase and in our project.
It now feels a little bit strange when you try to deselect all subnodes with two quick clicks, as the second click is ignored.
But it is good that it is now no longer possible to select nodes without being noticed.
Thank you very much for your effort.

**Comment by melloware** [comment]
Yes this is similar to how we block CommandButton until the AJAX is returned so you don't submit the CommandButton twice with a double click!  @aklein2024 I can backport to 14.0.1 but the community is only supposed to support the current version 14.x and now 13.X is in LTS so it would have to be requested through your PRO account to be backported (I think).
