### ISSUE TITLE
Float Label: Label Doesn't stay Above Field for DatePicker When Left Click Held on a Value

### ISSUE THREAD

**Issue by TheMightyE** [primefaces/primefaces#11936]
### Describe the bug

![image](https://github.com/primefaces/primefaces/assets/18034577/f6f20b26-11ee-4aa2-844b-1dec66ef97fe)
When using `FloatLabel` with the `DatePicker`, if the user left clicks a date for about half a second (hold left click on a date for longer to easily recreate the issue) then the float label goes back as the placeholder with the selected value. This can consistently be recreated on the [showcase](https://www.primefaces.org/showcase/ui/misc/floatLabel.xhtml?jfwid=e7c54).

As a little extra bit of info, on the same showcase page's `Dropdown` component (below the Datepicker), when left click is held on a value, the label comes back as a placeholder, but when the click is released, the label goes above the field. This is the expected behavior for the Datepicker Float Label as well.
 
I did come across [this](https://github.com/primefaces/primefaces/issues/9084) fix, however I am able to recreate the issue on PrimeFaces v13.0.8 and the showcase which is v13.0.10-SNAPSHOT at this time.

### PrimeFaces edition

Community

### PrimeFaces version

 13.0.10-SNAPSHOT

### JSF implementation

MyFaces

### JSF version

4.0.2

### Java version

17.0.7

### Browser(s)

Edge

**Comment by melloware** [comment]
@TheMightyE can you try and reproduce it here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/misc/floatLabel.xhtml?jfwid=0e7df

That is the latest DatePicker on PF 14.0.0 just want to see if it is still happening?

**Comment by melloware** [comment]
OK fixed in PF 14.0.0 then!

**Comment by TheMightyE** [comment]
Wonderful. Thanks as usual!
