### ISSUE TITLE
org.primefaces.component.remotecommand.*: Wrong component-type and render-type path

### ISSUE THREAD

**Issue by brzfelixbrz** [primefaces/primefaces#11930]
### Describe the bug

primefaces-p.taglib.xml has wrong component-type and render-type path at tag-name=remoteCommand:
should be org.primefaces.component.remotecommand.RemoteCommand and vice versa

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by brzfelixbrz** [comment]
jakarta edition

**Comment by Rapster** [comment]
What makes you think "it should be"? Here is a good read: https://stackoverflow.com/a/8079296/4605161

**Comment by brzfelixbrz** [comment]
well, i think because it is just referencing to a RemoteCommand, which simply does not exist in that package under that specific path. But i guess it shouldnt then

**Comment by Rapster** [comment]
Ok, so you can have a look at the link I attached above, and you'll also realize that particular "problem" you mentionned is everywhere in the taglib, don't mix up type and class (I know it's very confusing...) The info that you're looking for is in the taglib, that's where the component type is bound to the class

**Comment by melloware** [comment]
@Rapster is correct the taglib.xml is fine.  @brzfelixbrz what issue were you having that led you to this conclusion?

**Comment by brzfelixbrz** [comment]
just issues in my brain. thank you!
