### ISSUE TITLE
Media tag with html5 video supoort

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#1193]
For me it would be a good feature to implement html5 video player to primefaces media tag becsuse flash is dead

**Comment by Rapster** [comment]
It is supported actually, see http://www.primefaces.org/showcase/ui/multimedia/media.xhtml which generates `object` html5 tag

**Comment by markusg80** [comment]
Ok maybe i not explained well and i appologies for that. What i need is a html5 video tag so i dont need a plugin to play video files. Flash, Quicktime and so on are really out of date and i will not develop any page with need of one of those plugins. And i believe this is not only my opinion.

**Comment by Rapster** [comment]
I see but I think `object` should do the trick. There is probably a reason why `object`  has been chosen over `video`. WDYT @cagataycivici ?

**Comment by Rapster** [comment]
See #105

**Comment by tandraschko** [comment]
Duplicate
