### ISSUE TITLE
Dialog Framework: XSS vulnerability 

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1194]
`DialogNavigationHandler` lacks in escaping user-supplied input for use in generated JS code:

```
sb.append("PrimeFaces.openDialog({url:'").append(url).append("',pfdlgcid:'").append(pfdlgcid)
   .append("',sourceComponentId:'").append(sourceComponentId).append("'");
```

Values of variables `url` and `pfdlgcid` are user-supplied (URL + request parameter) and therefore must be escaped properly.

May be reproduced in your showcase:
1. Open http://www.primefaces.org/showcase/ui/df/basic.xhtml?pfdlgcid=viewCars%27,sourceComponentId:document.title,options:[]});%2Balert(document.cookie);%2F%2F
2. Click at _View_ button
3. Cookie will be shown in alert box

**Comment by cnsgithub** [comment]
I tried to fix this issue but unfortunately didn't find any appropriate JS escaping utility in your code.

It seems that you're using `ComponentUtils.escapeText` in different locations where JS escaping is necessarily required, e.g. in `BarRenderer.encodeOptions`. However, according to the method's commentary `ComponentUtils.escapeText` is just for escaping JSON. 

The payload from the reproduction scenario mentioned above should look like this if properly escaped for JS contexts:
`pfdlgcid\x3dviewCars\x27,sourceComponentId\x3adocument.title,options\x3a\x5b\x5d\x7d\x29\x3b alert\x28document.cookie\x29\x3b\x2f\x2f`

At least escaping it with `ComponentUtils.escapeText` is not sufficient:
`pfdlgcid=viewCars',sourceComponentId:document.title,options:[]}); alert(document.cookie);\/\/`

Please also double-check various locations where it is used for JS output and consult OWASP papers if you are not sure as there seem to be many injection vulnerabilities remaining in PrimeFaces.

Also a security scanner like LAPSE+ may help you to find vulnerability sources and sinks.

**Comment by cagataycivici** [comment]
@tandraschko What do you think?

**Comment by dasmanu** [comment]
We recently migrated from RichFaces to PrimeFaces and since then I'm a follower of the github discussions. I feel a little nervous about serious security issues which were detected within few weeks (e.g. #1152). Still wonder why our OWASP check shows green for PrimeFaces.
Pls consider security issues on highest priority and provide fixes for community editions backwards.

**Comment by kukel** [comment]
@dasmanu: Maby there were to little serious RF users to have these things detected. Keep in mind: _absence of proof is not proof of absence_

**Comment by tandraschko** [comment]
@cagataycivici not sure actually, i'm not aware of any JS escaping in PF for now. AFAICS escapeText is really just for JSON escaping or our widgets.

**Comment by cnsgithub** [comment]
Before reinventing the wheel, please have a look at https://github.com/OWASP/owasp-java-encoder/.

**Comment by fcorneli** [comment]
To allow for a systematic handling of such security issues, it might be interesting to introduce a Java-annotation like

```
@SecurityReviewed(contact="whoever@company.com",
    jsInjections=true, anotherAttackSurface=false, ...)
```

and mark every reviewed class with this.
You could even provide a Maven plugin that checks whether every JSF Renderer has been reviewed or not and let it generate some simple report on the review status.

In your CoreRenderer you could provided safe function for outputting/inputting. Maybe even block direct usage of some sensitive default functions by CoreRenderer implementations.

**Comment by cnsgithub** [comment]
I am not totally sure because I don't know when it gets called, but probably `pfdlgcid` should be escaped here as well: `DefaultRequestContext:closeDialog`. Could you please check this?

![image](https://user-images.githubusercontent.com/13161711/35510822-f579ab8e-04f9-11e8-8b6b-227cb2cb528c.png)

**Comment by melloware** [comment]
@cnsgithub I think you are right.  I will submit a PR.

**Comment by cnsgithub** [comment]
There is some code duplication in `PrimeFaces:closeDynamic` (you changed it there) and `DefaultRequestContext:closeDialog` (you didn't change it there).

In addition, I am not sure if `ComponentUtils:escapeEcmaScriptText `is correct here (I also stumbled upon this misleading method name a few days ago).

Please try `42'});alert('oops');//` as input string and see if it is sufficient. If not, `ComponentUtils:escapeText` should be used instead.
