### ISSUE TITLE
Wrong Javadoc for InputMaskRenderer#translateMaskIntoRegex()

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#11940]
### Describe the bug

Javadoc tells that `? - Makes the following input optional` but migration guide 8.0 -> 10.0.0 tells, that `optional section of mask no longer starts with ? but must be wrapped in [ and ]`.

### Reproducer

see https://javadoc.io/doc/org.primefaces/primefaces/latest/org/primefaces/component/inputmask/InputMaskRenderer.html

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Good catch!  PR submitted.

**Comment by rho66** [comment]
Would be great to show this info also in the online documentation!

Freundliche Grüße,
Rainer Hochreiter
--
Rainer Hochreiter     | E-mail: ***@***.***
***@***.***>
Am Teich 30/15/3      | Web:    www.hochreiter.at
A-3161 St.Veit/Gölsen | Mobile: +43 664 2812175


Am Mi., 15. Mai 2024 um 14:20 Uhr schrieb Melloware <
***@***.***>:

**Comment by melloware** [comment]
@rho66 where do you mean like on this page: https://primefaces.github.io/primefaces/15_0_0/#/components/inputmask?id=inputmask ???

**Comment by rho66** [comment]
Yes - and also on
https://primefaces.github.io/primefaces/13_0_0/#/components/inputmask which
is the page shown when click on "SERVER API" on page
https://primefaces.org/showcase/ui/input/inputMask.xhtml

Freundliche Grüße,
Rainer Hochreiter
--
Rainer Hochreiter     | E-mail: ***@***.***
***@***.***>
Am Teich 30/15/3      | Web:    www.hochreiter.at
A-3161 St.Veit/Gölsen | Mobile: +43 664 2812175


Am Do., 16. Mai 2024 um 13:17 Uhr schrieb Melloware <
***@***.***>:

**Comment by rho66** [comment]
Thnx!

Freundliche Grüße,
Rainer Hochreiter
--
Rainer Hochreiter     | E-mail: ***@***.***
***@***.***>
Am Teich 30/15/3      | Web:    www.hochreiter.at
A-3161 St.Veit/Gölsen | Mobile: +43 664 2812175


Am Do., 16. Mai 2024 um 14:56 Uhr schrieb Melloware <
***@***.***>:
