### ISSUE TITLE
InputMask: slotChar as optional

### ISSUE THREAD

**Issue by cfortes** [primefaces/primefaces#11958]
### Description

Considering that any value can be assigned to the slotChar attribute, it would be interesting to have an attribute within InputMask component to submit/decode and keep the optional slot value.  Since  #6471 it is no longer possible. 

### Describe the solution you would like

Imaginary code:

```
<p:inputMask 
    value="#{exampleController.value}"
    mask="999-999-999-999-999"
    autoClear="false"
    slotChar="0" 
    keepSlotChar="true">
</p:inputMask>
```

- `keepSlotChar`: Its default value would be false, and it would be overridden when necessary. This attribute signalises to the decoder to keep and to do not replace the slotChar values within the value for empty Strings.

### Additional context

For instance, in the example above, the value input for the user would be `030-090-120-000-000` and the unmasked persisted value would be `030090120000000`, which is expected. Currently, the component sends `3912` to the server as value which is completely wrong and hard to find a work around.
In previous versions (6.1) it was possible to use InputMask this way, but since we updated the project to 13.0.8 its no longer possible.

**Comment by melloware** [comment]
In PrimeFacess 6.1 it used the dead and deprecated `jquery.mask.js` plugin.  It was upgraded to the modern InputMask plugin with this one: https://github.com/primefaces/primefaces/pull/6062

The newer InputMask is kept up to date, had way more features and bugfixes as you can see that PR closed 4 previous issues.

But let me revisit this to see what can be done as you have seen from this issue which is why we strip the optional "slotChar" https://github.com/primefaces/primefaces/issues/6469

**Comment by melloware** [comment]
Cc @tuerker who originally requested the fix that you mentioned above.

**Comment by cfortes** [comment]
Awesome, thank you! I can see many scenarios where removing the slotChar from the incomplete masked input value would be the right move and why it was implemented this way. But as I mentioned there are some cases where keeping the optional slotChar had some usefulness. Thats why I suggested that it should be interesting to have an option for both solutions.

**Comment by melloware** [comment]
@cfortes thanks for the report.  Also do you need a workaround for 13.x to get this working the way it was?  I can provide one if you don't have one you are already using?

**Comment by cfortes** [comment]
Yes I'd like a workaround! I've been trying to find one but nothing really works

**Comment by melloware** [comment]
Ok I will post here tomorrow how you can make it work.

**Comment by melloware** [comment]
@cfortes give this a try just unzip and run `mvn clean jetty:run` and go to http://localhost:8080/
[pf-11958.zip](https://github.com/primefaces/primefaces/files/15347904/pf-11958.zip)

basically i override the renderer to only strip out the slotChar IF you are using an "optional" mask.

```java
public class SlotCharInputMaskRenderer extends InputMaskRenderer {

    @Override
    public void decode(FacesContext context, UIComponent component) {
        InputMask inputMask = (InputMask) component;

        if (!shouldDecode(inputMask)) {
            return;
        }

        decodeBehaviors(context, inputMask);

        String clientId = inputMask.getClientId(context);
        String submittedValue = context.getExternalContext().getRequestParameterMap().get(clientId);

        if (submittedValue != null) {
            // strip mask characters in case of optional values
            String mask = inputMask.getMask();
            if (mask.contains("[") || mask.contains("]")) {
                submittedValue = submittedValue.replace(inputMask.getSlotChar(), Constants.EMPTY_STRING);
            }
            
            if (inputMask.isValidateMask() && !LangUtils.isEmpty(submittedValue) && LangUtils.isNotBlank(mask)) {
                Pattern pattern = translateMaskIntoRegex(context, mask);
                if (!pattern.matcher(submittedValue).matches()) {
                    submittedValue = Constants.EMPTY_STRING;
                }
            }

            inputMask.setSubmittedValue(submittedValue);
        }
    }
    
}

```

**Comment by cfortes** [comment]
@melloware thank you it worked! 
I only have one question, is it ok to force `autoClear = false` when there is optional mask? #11959 
I'm asking because isn't there a possibility of the user input an invalid value and it won't be cleared when the mask is optional?

**Comment by melloware** [comment]
So in the renderer we do this...

```java
// autoclear must be false when using optional mask
            boolean autoClear = inputMask.isAutoClear();
            if (mask.contains("[") || mask.contains("]")) {
                autoClear = false;
            }
```

Basically if you are using optional mask it automatically sets AutoClear="false".

Do you think that is still OK?

**Comment by melloware** [comment]
did you try it with `validateMask="false"`?  The optionals make server side prevention tough.  In 6.1 we were not defending the security of someone just doing a FORM POST and sending you an invalid value for a mask so we prevent invalid submissions.

**Comment by melloware** [comment]
Also I just tested and mine is not keeping the incorrect version on the screen?

[pf-11958-2.zip](https://github.com/primefaces/primefaces/files/15353772/pf-11958-2.zip)

**Comment by cfortes** [comment]
@melloware oh yes this version I also tested and it is working fine!
