### ISSUE TITLE
Decouple AJAX and PFS from the big monolith primefaces.js

### ISSUE THREAD

**Issue by ova2** [primefaces/primefaces#1195]
We have got new HTML templates from one UX company and would like to develop with pass-through elements as described here in your blog: http://blog.primefaces.org/?p=3035 We would like only use p:ajax in XHTML (instead of f:ajax) due to useful PF selectors. No PrimeFaces component are planned to be used (at least for now).

The problem is, that AjaxBehavior includes primefaces.js.

``` javascript
@ResourceDependencies({
    @ResourceDependency(library="primefaces", name="jquery/jquery.js"),
    @ResourceDependency(library="primefaces", name="jquery/jquery-plugins.js"),
    @ResourceDependency(library="primefaces", name="primefaces.js")
})
```

This is a big file which contains 100+ components (performance for mobile is important). We don't need them and only need the AJAX functionality. p:remoteCommand will be used too. But it has exactly the mentioned AJAX functionality.

Can you not separate AJAX core from the primefaces.js? The idea is to separate AJAX and PFS in one separate module (file). What do you think, can we modularize the PrimeFaces?

**Comment by tandraschko** [comment]
+1 to split it up in primefaces-core.js and primefaces.js.

**Comment by ova2** [comment]
That's also consequentially.

`primefaces-core.js` - AJAX, PFS, Utility, no components
`primefaces.js` - components
`validation.js / beanvalidation.js` - CSV stuff

Looks good for me. Again, the goal is that `p:ajax` and `p:remoteCommand` don't include `primefaces.js` AND `jquery-plugins.js`.

**Comment by tandraschko** [comment]
+1 yep
core.js and components.js would be even better.

**Comment by ova2** [comment]
Exactly :-). **pf-core.js** and **pf-components.js**

By the way, if you look all modern JavaScript frameworks, there are small modules for JS and CSS. Released via npm or however. If I need e.g. DataTable widget, I can only import the module for DataTable and maybe core. But why I have to import other dozens modules? That will not understand an JavaScript developer.

The JSF world is a little bit more complex. The reason for one big file is that you can not bundle small files by dynamically included components at project build time (well, probably with OmniFaces CombinedResourceHandler). In the JavaScript world you can easy define and import needed separate files and bundle them with a bundler while project build time. In PrimeFaces we could take a middle way and define 3-4 separate files, so that the resources load time and the modules principle would be ok.

**Comment by cagataycivici** [comment]
Sounds good, so what should pf-core.js include?

```
core.js
core.env.js
core.ajax.js
core.expressions.js
core.widget.js
```

How about core.dialog.js?

p:ajax then depends on jquery.js and pf-core.js. We need to watch out if pf-core.js has a dependency on jquery-plugins.js.

All component metadata.xml files need to change by the way.

**Comment by tandraschko** [comment]
Exactly - every core.*.js but not core.dialog.js as it contains code for a component which requires CSS.

I think we must reference jquery-plugins as the refocus handling after ajax updates requires a plugin.

We should do the same for p:remoteCommand, too. It also doesn't require UI stuff.

**Comment by ova2** [comment]
Thanks Thomas for the clarification!

**Comment by ova2** [comment]
We have identified two components more which we would need - `p:focus` and `p:defaultCommand`. `Focus` has

``` javascript
@ResourceDependencies({
    @ResourceDependency(library="primefaces", name="jquery/jquery.js"),
    @ResourceDependency(library="primefaces", name="primefaces.js")
})
```

But it is not a visible component and should not have the dependency to `primefaces.js`.

The `DefaultCommand` has

``` javascript
@ResourceDependencies({
    @ResourceDependency(library="primefaces", name="jquery/jquery.js"),
    @ResourceDependency(library="primefaces", name="jquery/jquery-plugins.js"),
    @ResourceDependency(library="primefaces", name="primefaces.js")
})
```

This is not a visible component too. These both components are more or less **utilities** (pure JS based). `Watermark` is the utility too. My suggestion would be to move such components into a file `core.util.js` and merge all `core.*` (except `core.dialog.js`) to the one `pf-core.js` at build time. Component classes has then as dependency `pf-core.js`.

**Comment by tandraschko** [comment]
Also applied for
poll
keyfilter
hotkey
ajaxstatus
ajaxExceptionHandler

**Comment by ova2** [comment]
Hi Thomas. Many thanks. Just a question: Can we use `p:ajax`, `p:remoteCommand`, `p:focus` and `p:defaultCommand` in 6.0 without a big primefaces.js? Are they included into the core JS file too?

**Comment by tandraschko** [comment]
yup, just check my commits :)
