### ISSUE TITLE
jakarta and facelet-taglib version

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#11969]
### Describe the bug

The PrimeFaces jakarta flavored JAR still has:
```xml
<facelet-taglib xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-facelettaglibrary_2_0.xsd" 
    version="2.0">
```
within its `META-INF/primefaces-p.taglib.xml`. Hence some tools might confuse it for a JSF 2.1/2.3 library instead of a JSF 4.0 library.

### PrimeFaces edition

Community

### PrimeFaces version

13/14

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

11

**Comment by Rapster** [comment]
In addition to Thomas coment, not sure if there is a way to fix easily but at best, we should use jcp namespace and also, we should rename the taglib into primefaces.xml (the -p was relevant when we had primefaces mobile -pm)

**Comment by fcorneli** [comment]
@tandraschko Well, with older versions of NetBeans I had strange namespace errors, dunno if it was related to this. The thing got stuck in "JSF 2.3 mode" while using the jakarta flavor.
Fixing this would required a custom Maven Shade Plugin resource transformer I guess.

**Comment by melloware** [comment]
I can fix this.
