### ISSUE TITLE
DataModel must implement org.primefaces.model.SelectableData where rowKey is used

### ISSUE THREAD

**Issue by bjorntj** [primefaces/primefaces#1196]
A sample project can be found here:
http://www.havleik.no/DatatableTest.tar.bz2

The project can be unpacked and run using "gradle bootRun"

To see the problem, write 18 in the regdate filter and press Enter. The table shows one row found, 18.02.2016. Then delete 18 from the filter and press Enter, the table shows the first 10 rows again. Then choose page 2 and then the exception occurs.
The Tomcat is running on port 8081.

**Comment by tandraschko** [comment]
As the PrimeFaces team is using maven, it would be great if you could provide a maven project.

**Comment by bjorntj** [comment]
Sorry but I do not use maven. But I guess you use IntelliJ IDEA? Then you can just choose Import project and point to the build.gradle file...

**Comment by tandraschko** [comment]
We use netbeans and maven :)

**Comment by bjorntj** [comment]
You really should be using IntellI IDEA... ;)
Doesn't Netbeans have support for Gradle?
But it is quite easy to install the gradle distribution also... :)

**Comment by bjorntj** [comment]
Found a gradle plugin that converts a gradle project to maven, you can find it here:

http://www.havleik.no/DTTest2.tar.bz2

It has a pom file inside build/poms

**Comment by bjorntj** [comment]
Just wondering if anyone has had any chance to look at this?

**Comment by tandraschko** [comment]
had no time, sorry.

**Comment by tandraschko** [comment]
Your project is way to complex - please provide a small sample project (a maven web project with no spring boot or something - mvn package should just create a war which runs fine on tomcat or something) with only small sample code and nothing else.

**Comment by bjorntj** [comment]
Not sure if I agree that my project is too complex. This is the kind of project that has this problem, I am not even sure if I can replicate this problem in a smaller project....
(I have many similar project but this is the only one with this kind of problem, that's why I think that this is the project that needs to be investigated...)

**Comment by tandraschko** [comment]
the problem is that i don't have much time and i just try to help your with your bug in my personal free time.
I would need to re-create the project as the delivered pom e.g. doesn't contain all dependencies and i don't know how to use spring boot.
Therefore its to much effort for me till i can check your problem.

**Comment by bjorntj** [comment]
Would it make any difference if I try to create a working pom file for the same project?

**Comment by tandraschko** [comment]
i think i would still need to install spring boot?
A simple servlet application would be much better.

**Comment by bjorntj** [comment]
No, you do not need to install anything, Everything you need is in the project and the pom...

**Comment by tandraschko** [comment]
ok, if you provide a fully working pom and a maven cmdline, i will take a look at it ;)

**Comment by bjorntj** [comment]
Thx! :)

**Comment by bjorntj** [comment]
Ok, I have uploaded a working maven project here: http://www.havleik.no/DTTest2.tar

The project can be unpacked and run using "mvn spring-boot:run" Before running there is one local jar file that needs to be put in the local maven repository, just run the .sh file under libs.

To see the problem, write 18 in the regdate filter and press Enter. The table shows one row found, 18.02.2016. Then delete 18 from the filter and press Enter, the table shows the first 10 rows again. Then choose page 2 and then the exception occurs.
The Tomcat is running on port 8080.

You might see some IO exception because of some missing css resources but that you can just ignore.. They appeared in the maven project but didn't spend any time tracking it down...

**Comment by tandraschko** [comment]
It works fine if you let Translog implement Serializable ;)

**Comment by tandraschko** [comment]
Reason:
ViewScoped beans are serialized and as Translog isn't serializable, somehow the rowKey and regDate in this case is really null. If it's serializable, the variables are not null and it's working fine.

Not sure why it works for filtering...

The exception is thrown because we have a fallback if the rowKey is null, to ask the DataModel.
As you don't use a custom datamodule here, the exception is actually correct.

**Comment by bjorntj** [comment]
Hmmmm... I knew it had to be something simple but not that simple... Guess I also was a bit fooled by the exception, didn't occur to me to check for that...
But thx! :)

**Comment by tandraschko** [comment]
hehe - at the first look it was really not simple, it took me over 30 mins :)
NP!
