### ISSUE TITLE
Confirm: message facet

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#11962]
### Description

The `p:confirm` `message` attribute is quite limited to express formatted content.
Hence we add support for the following construct:
```xml
<p:commandButton ...>
    <p:confirm header="title"/>
    <f:facet name="confirmMessage">
        fancy content here...
    </f:facet>
</p:commandButton>
```

### Describe the solution you would like

`p:confirm` uses the `confirmMessage` facet of its parent to yield the message content.

**Comment by melloware** [comment]
how about just `<f:facet name="message">` so it matches the `message` property but facet will always take precedence?

**Comment by fcorneli** [comment]
As @tandraschko mentioned on the Discord, `message` would be nice if the facet could live directly under `p:confirm`. Since this apparently is not possible, he suggested doing the `confirmMessage` "confirm prefix naming". Not that we will ever run into naming conflicts here I suppose, but maybe it's cleaner with `confirmMessage`. Dunno... your call here.

**Comment by fcorneli** [comment]
Working on this at https://github.com/e-Contract/primefaces/tree/11962

**Comment by melloware** [comment]
Understood.

**Comment by fcorneli** [comment]
See https://github.com/primefaces/primefaces/pull/11964
