### ISSUE TITLE
Possible memory leak in v5.3 PrimeFacesContext with Faces 2.2

### ISSUE THREAD

**Issue by hmatsuzaka** [primefaces/primefaces#1197]
Dear team,

I tried to integrate v5.3 with Faces 2.2/Spring Webflow 2.4.2 under tomcat 8.0.32.
While undeploying a war, tomcat logs possible ThreadLocal memory leak.

`   public PrimeFacesContext(FacesContext wrapped) {
        this.wrapped = wrapped;

```
    RequestContext.setCurrentInstance(new DefaultRequestContext(wrapped), wrapped);
    **setCurrentInstance(this);** /* <--  This line may be required */ 
}
```

`

Best Regards,
Matsuzaka

**Comment by tandraschko** [comment]
if you check PrimeFacesContext, the RequestContext will be released in #release.
If #release of the FacesContext is not called, i think it's up to Spring WebFlow as it works fine with plain Mojarra and MyFaces.

**Comment by tandraschko** [comment]
Please come back if you analyzed the bug or created an issue on Spring side but i don't think that we can do something here as it works fine without Spring WebFlow.
