### ISSUE TITLE
Sticky: Filtering column in p:dataTable/p:column, using sticky feature, do not allow user input. Must use scrolling to activate

### ISSUE THREAD

**Issue by uvula** [primefaces/primefaces#11988]
### Describe the bug

Hello developers (in Discord chat 23.05.2024 / 07:55)
I asked for a fix about:
Sticky: MenuBar sticky should always show on top · Issue #11598

Using PF 13.0.06 or higher
I observed a problem since #11598
If p:dataTable -> p:column using filterBy, you can NOT click/insert values the column header field 
to receive user input for filtering. You first must use e.g the mouse wheel and do some scrolling.
After scrolling you can click and start typing.
Any idea? Demo zip uploaded in Discord with my account. 

Answer: 
Verified already be @melloware
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/15416535/primefaces-test.zip)

### Reproducer

Instruction itself are describe in demo, show on web-pages (what to do)

### Expected behavior

The column header fields, using for filtering, should accept user input without using mouse wheel or scrolling.
It was working before fix #11598 in version 13.0.5. In demo you can also go back to 13.0.5, here it is "working"

### PrimeFaces edition

Community

### PrimeFaces version

13.0.6 or higher

### JSF implementation

Mojarra

### JSF version

2.0.27 ? from demo case (default)

### Java version

11

### Browser(s)

Firefox 126.0 (64bit)

**Comment by melloware** [comment]
@uvula here is your reproducer with a patch included to make it work in `test.js`

[pf-11988.zip](https://github.com/primefaces/primefaces/files/15443590/pf-11988.zip)

**Comment by uvula** [comment]
Sorry, not working for me.
Download ZIP pf-11988.zip, Browser cache cleaned. I need to use mouse wheel or scrolling to activate this field.
Also embeeded to primefaces-test project, override test.js and added <h:outputScript name="test.js" /> to my main.xhtm. Not fixed.
Both with PF 14.0.0

**Comment by melloware** [comment]
@uvula when I run the reproducer above which includes test.js here is my result:

![datatable-sticky](https://github.com/primefaces/primefaces/assets/4399574/06839982-42da-4a61-a56e-ab7a37c87edd)

**Comment by uvula** [comment]
Without do some scrolling, I can't insert into the field (FF 126.00 64-bit - german, Edge 125.0.2535.51 (Offizielles Build) (64-Bit), german). 
- When I use "tab" key as long as I reach the field, I can insert now a value.
- Mouse wheel one movement -> I can click and insert.
- Browser scroll bar, one click, then I can click and insert.

When cleaning the browser cache, I see "test.js" is loaded with 4.13kB (size) and status 200

**Comment by uvula** [comment]
PF13.0.5
When I enter the view (load the page), I hover over the field "Name". The field get a thin blue frame, but the cursor is not blinking within the field. 
I can click the field: thin blue frame, cursor is in the field and blinking. Field receives input -> filtering

PF14.0.0 (pf-11988.zip extracted)
When I enter the view (load the page), I hover over the field "Name": nothing happens, no blue frame, no cursor.
I click as next action into the field "Name", nothing happens. Field is not getting active, I can't insert/typing any value into the field. The field don't get a thin blue frame. I don't get a cursor.
When I (next) use mouse wheel, one rotation step: I hover -> blue frame, clicking -> blue frame, cursor blinking. I can enter value -> filtering is working.

Maybe the ZIP you send is not last version?
certutil -hashfile test.css
  SHA1-Hash von test.css:
  86e1b254e0ca26d1b46943803d7cb02cd20692d0
certutil -hashfile test.js
  SHA1-Hash von test.js:
  2c8c517bc549266234b92179c90653e322e3b2d3

To see, some changed happens on the page itself, I put into node.xhtml more text (paragraph) and see my new text after redeploy to jetty (stopping/starting). When jetty is started, I see either PF 13.0.5 or PF 14.0.0 in the console output.

Strange.

**Comment by uvula** [comment]
Test above was done at work in business environment and using a RDP session.
I have done the same test (pf-11988.zip) with my private system, without RDP session. Same behavior above described. No frame, no cursor.
FF + Chrome
Both Windows 10 systems.

**Comment by melloware** [comment]
Can you try this version:
[pf-11988-2.zip](https://github.com/primefaces/primefaces/files/15469836/pf-11988-2.zip)

**Comment by melloware** [comment]
This will be in 14.0.1
