### ISSUE TITLE
Message: tooltip doesn't work correctly if title is used

### ISSUE THREAD

**Issue by CSchulz** [primefaces/primefaces#1198]
Consider following code, if you moving your cursor over the input it shows a tooltip with "An input".

```
<p:tooltip />
<p:inputText id="input" value="..." title="An input" />
<p:message for="input" display="tooltip" />
```

Add a validation to the input field and try it with wrong values. I expect to see the error message in the tooltip, but it keeps the title value. Removing the title attribute it works like expected.

![input](https://cloud.githubusercontent.com/assets/1520593/13490992/1434d1ce-e130-11e5-80cf-f580d0176535.png)

**Comment by kukel** [comment]
PF version? And please create an [mcve]

**Comment by husnutapan** [comment]
Maybe you forgot to panelGrid attribute if you use this code more pleasant to the eye.

`<h:form id="form1">
            <p:panelGrid columns="4">
                <h:outputText value="Input :" />
                <h:inputText id="track" required="true"/>
                <p:tooltip id="toolTipTrack" for="track" value="when click on the button validate in inputtext" trackMouse="true" />   
                <p:message for="track"/>
            </p:panelGrid>
            <p:commandButton id="submitButton" value="Submit" update="form1" />
        </h:form>`

**Comment by tandraschko** [comment]
AFAICS with your PR, the original title attribute will be removed forever, also if the input is valid again.
Could you please provide a simple example with validation and bean etc.?

**Comment by jepsar** [comment]
So, what should happen in this case? IMO this is a won't fix.

**Comment by melloware** [comment]
I think ideally it should.

1. Put the current `title` to the side.
2. Update the `title` and show the tooltip
3. When valid again restores the original `title`.

So we probably just need to store in another `data-` element and put it back. That would be my guess

**Comment by melloware** [comment]
But I can also live with WONTFIX.

**Comment by melloware** [comment]
No response here from a 7 year old ticket marking as WontFix
