### ISSUE TITLE
Showcase: Error when running locally after a few minutes

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#11989]
### Describe the bug

Run the showcase locally with `mvn -Ddev`.   After a few minutes try and hit a page you will see this error.

```
INFO: Running on PrimeFaces 15.0.0-SNAPSHOT
[WARNING] Failed startup of context oeje10mp.MavenWebAppContext@5b6428b3{/showcase,/showcase,b=[file:///C:/dev/primetek/primefaces/primefaces-showcase/src/main/webapp/, jar:file:///C:/Users/melloware/.m2/repository/org/primefaces/primefaces/15.0.0-SNAPSHOT/primefaces-15.0.0-SNAPSHOT-jakarta.jar!/META-INF/resources/, jar:file:///C:/Users/melloware/.m2/repository/org/apache/myfaces/core/myfaces-api/4.0.2/myfaces-api-4.0.2.jar!/META-INF/resources/, jar:file:///C:/Users/melloware/.m2/repository/org/apache/myfaces/core/myfaces-impl/4.0.2/myfaces-impl-4.0.2.jar!/META-INF/resources/],a=AVAILABLE,h=oeje10s.SessionHandler@487612cc{STARTED}}{file:///C:/dev/primetek/primefaces/primefaces-showcase/src/main/webapp/}
java.lang.Error: Unresolved compilation problem:
        The method register(Class<T>, Class<E>, String) in the type DataExporters is not applicable for the arguments (Class<DataTable>, Class<TextExporter>, String)

    at org.primefaces.showcase.util.ShowcaseSystemEventListener.processEvent (ShowcaseSystemEventListener.java:39)
    at jakarta.faces.event.SystemEvent.processListener (SystemEvent.java:49)
    at org.apache.myfaces.application.ApplicationImplEventManager.processGlobalListeners (ApplicationImplEventManager.java:373)
```

### Reproducer

`mvn -Ddev` on showcase

### Expected behavior

No errors and the showcase remains running

### PrimeFaces edition

Community

### PrimeFaces version

15.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

17

**Comment by melloware** [comment]
@Rapster @christophs78 need your help on this one not sure if its something new with Jetty 12 and Mojarra 4.0 with the showcase or what?

**Comment by christophs78** [comment]
You had this issue with MyFaces (because `org.apache.myfaces.application ...`)?
Did it also happen with Mojarra?
(I can look into this issue on the upcomming weekend.)

**Comment by melloware** [comment]
it doesn't look like it happens with Mojarra that I can tell.

**Comment by tandraschko** [comment]
can't replicate

windows11, JDK21, CMD without IDE

**Comment by melloware** [comment]
Without IDE

### Environment
```
C:\dev\primetek\primefaces\primefaces-showcase>mvn --version
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: C:\tools\apache-maven-3.9.5
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

I will try and come up with exact steps.  It seems to be random.

**Comment by Rapster** [comment]
The problem looks more something related to compilation than JSF impl. Something must have gone wrong when you compiled PF?

**Comment by Rapster** [comment]
change in showcase code or PF code?

**Comment by melloware** [comment]
I think its when I change anything in Eclipse?  But not always.  But that stack trace is always the same.

**Comment by melloware** [comment]
Ahh there is is just edit any showcase XHTML file you will see it happen.

**Comment by Rapster** [comment]
Not sure I follow, but since Eclipse has his own compiler, could it be the cause? see also https://stackoverflow.com/a/1124806

I don't reproduce the issue running `mvn -Ddev`  on showcase with IntelliJ

**Comment by melloware** [comment]
And you can edit a showcase XHTML file?

**Comment by melloware** [comment]
OK now i see a message with `[INFO] Automatic redeployment disabled, see 'mvn jetty:help' for more redeployment options`

But our PrimeFaces Test project has this...

```xml
<scan>5</scan>
```

so i had that in the showcase.  if I remove that I now see  `[INFO] Automatic redeployment disabled, see 'mvn jetty:help' for more redeployment options` but I can still edit XHTML pages.

**Comment by Rapster** [comment]
I have that warning without changing anything... And yes I can edit a showcase XHTML file
