### ISSUE TITLE
TreeTable sort event

### ISSUE THREAD

**Issue by vanjalee** [primefaces/primefaces#1199]
TreeTable does not support the sort event. This would be useful for sort listener operations triggered by ajax, such as saving the sort column and sort order parameters in session without the need to bind the TreeTable to a bean variable. With normal DataTables, one can freely use 
`<p:ajax event="sort" listener="..." />`,
inside the DataTable tags. With TreeTable, same code throws TaxException, saying "Event:sort is not supported".

My System and Web App Specifics:
- ver 3.0
- jsf 2.1.28
- primefaces 5.2
- primefaces-extensions 3.1.0
- JavaEE EAP 6.4
- JBoss Developer Studio 9.0.0.GA

Best Regards,
Vanja

**Comment by sudheerj** [comment]
Why you want to store sort column and sort order parameters in session and how you do that with listener method?

**Comment by vanjalee** [comment]
I need to save the current sort settings in the session. However, I can only use ViewScoped beans, so component binding is not an option. Also, LazyTableModel is not an option.
To achieve this with normal tables, "onSort" I pass the SortEvent as a listener parameter, and then determine the current sorting column and sort order. These two are saved as the session variables in JSF (two unique variables per table). If one changes views, next time one comes back, PostConstruct on the Bean will again be executed. At this point however, I check for those variables in session, and if they are set, I manually fill and call the sorting javascript function inside bean.
This approach does not cover multisorting, but I have seen that there are already fair share of issues for that.
