### ISSUE TITLE
ImageCropper: Dynamic content support

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#12]
ImageCropper currently only works with static images, enable support for dynamic content via StreamedContent.

**Comment by kahlon1005** [comment]
When is the target release for this issue?

**Comment by cagataycivici** [comment]
Not being planned yet due to issues with higher priorities. You may consider PRO or CASE Support to speed it up.

**Comment by nelsongraca** [comment]
This would be indeed great if it was supported.

**Comment by dugenci** [comment]
It would be very great if this option is supported but still seems that issue has low priority after all these years.

**Comment by tandraschko** [comment]
Yup
But if you would like to see it, you can still sponsor it via PrimeFaces PRO or develop it by yourself and provide a PR ;)
