### ISSUE TITLE
ImportConstants/ImportEnum: Preserve order of constants

### ISSUE THREAD

**Issue by jbrower2** [primefaces/primefaces#12001]
### Describe the bug

In the `ConstantsHashMap` and `EnumHashMap` classes, a base class of `HashMap` is used, which will not preserve the order of values added to the map. This will result in enum members being returned out of order for example in a `<f:selectItems value="#{SomeEnum}" />`. This can be fixed by changing the base class to `LinkedHashMap`, which is a thin wrapper over `HashMap` that maintains insertion order. This is how OmniFaces handles these values ([source](https://github.com/omnifaces/omnifaces/blob/4.x/src/main/java/org/omnifaces/taghandler/ImportConstants.java#L160)).

(note: I'll be opening a PR for this fix shortly)

### Expected behavior

The order of constants/enum members should be preserved from how they are defined in the corresponding class.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment]
if you wanna merge to 14.0.x1 @melloware, feel free
i merged it for now
