### ISSUE TITLE
CascadeSelect: unable to scroll with large number of items

### ISSUE THREAD

**Issue by sebsoftware** [primefaces/primefaces#12008]
### Describe the bug

If you use cascadeSelect with a large data set, drop down expands to full set and the document expands that scrolling is activated, but cascadeSelect immediately closes, when touching the scroll bar (Safari / macOS).

I've tried setting a max height to the popover, but than child opening fails. A max height or rows setting for the selection popover would be useful. At least it should fit to the visible screen.

It seems that this was also in primereact sometimes ([#2229](https://github.com/primefaces/primereact/issues/2229))

### Reproducer

Use attached test project
[cascade-test.zip](https://github.com/primefaces/primefaces/files/15438827/cascade-test.zip)

### Expected behavior

maxheight and scrolling behavior

### PrimeFaces edition

Community

### PrimeFaces version

13.0.10

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Safari

**Comment by melloware** [comment]
@sebsoftware feel like helping on this one?  I compared that PrimeReact fix and I see most of our CSS styles match theirs exactly.   it looks like for Submenu's they introduce one more DIV wrapper but its not immediately clear to me how that helps.    Any thoughts or investigation would be great!

**Comment by KiraYoushikage** [comment]
Hi, this is my solution:
I found out the event listener via chrome dev tool. I managed to edit source code and i disable the scroll event so that while i can scroll down, cascadeSelect would not immediately closes.


```
PrimeFaces.widget.CascadeSelect.prototype.bindPanelEvents=function() {
    var a = this;
    this.hideOverlayHandler = PrimeFaces.utils.registerHideOverlayHandler(this, "mousedown." + this.id + "_hide", this.panel, function() {
        return a.triggers
    }, function(b, c) {
        a.panel.is(c) || 0 < a.panel.has(c).length || a.hide()
    });
    this.resizeHandler = PrimeFaces.utils.registerResizeHandler(this, "resize." + this.id + "_hide", this.panel, function() {
        a.handleViewportChange()
    });
    // to stop CascadeSelect immediately disappear while scrolling.
    // this.scrollHandler = PrimeFaces.utils.registerConnectedOverlayScrollHandler(this, "scroll." + this.id + "_hide", this.jq, function() {
    //     a.handleViewportChange()
    // })
}

```

**Comment by melloware** [comment]
Good debugging that code hits when the outer browser scrollbar is scrolled closing the panel that you are no longer interacting with.  However because this list is SOOO long its triggering the browser scrollbar not by human events.

Let me see if there is anything to be done.

**Comment by melloware** [comment]
Hey guys I tried to add a `max-height` and `overflow: scroll` so the panel would scroll but it then breaks the submenu rendering. This component would need to be changed significantly so for now I am doing what SelectCheckBoxMenu does...

https://github.com/primefaces/primefaces/blob/08d5fe0d93e7ad1c068b7a848f8bbb017542823f/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js#L220-L222

If there are more than 10 items I will disable this scroll handler automatically.
