### ISSUE TITLE
Primefaces V14 - p:fileUpload drag/drop no triggers listener

### ISSUE THREAD

**Issue by aboslund** [primefaces/primefaces#12007]
### Describe the bug

Noticed when attempting an upgrade from code using primeface 13.0.10 to PF V14 that the p:fileUpload drag/drop no longer triggers the listener.  Clicking choose and selecting a file to upload does trigger the listener.  Have verified this difference in behavior on mac OS Sonoma 14.5 with Firefox, Chrome, and Safari.  V14 Drag/drop does show the "+" when dragging the file over the drop area, but dropping has no effect.

### Reproducer

<ui:composition lang="en" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/layouts/empty.xhtml">
  <ui:define name="body">
    <h:form>
      <p:fileUpload listener="#{test.handleFileUpload}" mode="advanced" dragDropSupport="true"
                    update="messages" />
      <p:growl id="messages" showDetail="true" />
      <h3>Maximum size: 1 MB</h3>
    </h:form>
  </ui:define>

</ui:composition>

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.file.UploadedFile;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import java.io.Serializable;

@Named("test")
@RequestScoped
public class Test implements Serializable {

  public void handleFileUpload(FileUploadEvent event) {

    UploadedFile uploadedFile = event.getFile();
    if (uploadedFile == null) {
      System.out.println("uploadedFile is null");
      return;
    }

    System.out.println("filename = " + uploadedFile.getFileName());

  }

}

### Expected behavior

Drag drop in primefaces v14 should trigger the listener as it does with previous versions

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Firefox, Chrome, Safari on mac os sonoma 14.5

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/issues/11879
