### ISSUE TITLE
Barcode: default QR code size

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#12004]
### Description

Like other barcode types, barcode for QR code should have a default scannable size.  Currently its width is 100%. On the showcase page, its width and height are set to 125, which can be its default size. 

### Describe the solution you would like

change QR default size to 125 x 125.

**Comment by tandraschko** [comment]
shouldnt all other be 100%? fixed size isnt that nice...

**Comment by javaone199** [comment]
100% is not scannable if its container is very big.  For a specific barcode, component users do not know how wide it should be to be scannable. All barcodes should have a nice default size to be scanned by device.

**Comment by jepsar** [comment]
@javaone199 you could set your default using https://primefaces.github.io/primefaces/14_0_0/#/core/globalattributes

**Comment by melloware** [comment]
So for all other barcodes Barcode4J generates an image that is sized correctly for the barcode.  For QR code that is a different library and as mentioned QR code should have a width and height.

So I think all we need to do is.

1. mention this in the docs.
2. Log a warning if width and heighth are not set on QR Code?

**Comment by tandraschko** [comment]
i would do nothing here

its just a different lib used here and both are generating SVG

it seems that qrcode generated it with relative sizes, the other lib with absolute

we should maybe better search a way that the other lib also generates relative sizes

**Comment by tandraschko** [comment]
we should avoid absolute sizes in general
users can set it in the user application or just by give the parent a size

**Comment by tandraschko** [comment]
feel free to create a new issue to try to make other barcodes relative sizes
