### ISSUE TITLE
IT: Nightly Build DatePicker012Test failing Chrome

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12009]
@christophs78 

DatePicker012 runs for me locally but it looks like in the nightly IT its failing on Chrome only?  I am running locally with Chrome CSP and non-CSP and I can't get it to fail.

https://github.com/primefaces/primefaces/actions/runs/9233425137

I have this TODO in `0-datepicker.js` because in lazy mode i am seeing it trigger a browser resize in the automation tests which closes the panel.

```js
            $(window).on('resize.' + $this.options.id, function() {
                // TODO: lazy model for some reason triggers a windows resize
                if (!$this.options.lazyModel) {
                    $this.hideOverlay();
                }
            });
```

Everything is working when I run manually in the showcase with animations disables so there is something weird that I can figure out going on here.

**Comment by christophs78** [comment]
```
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at org.primefaces.selenium.component.DatePicker.click(DatePicker.java:53)
	at org.primefaces.integrationtests.datepicker.DatePicker012Test.refreshLazyModel(DatePicker012Test.java:68)
```

![20240525_062118_d383a0c4-2087-4ebf-b76a-793bb38678a5](https://github.com/primefaces/primefaces/assets/10461942/ce1710e9-853b-4507-933f-a6e40f77ac67)

**Comment by christophs78** [comment]
- I can reproduce this issue on my dev-notebook.
- Github-CI: CI - OK, IT - NOK --> what´s the difference?

**Comment by christophs78** [comment]
The test is flaky:
![image](https://github.com/primefaces/primefaces/assets/10461942/e898c6f0-7711-4990-8f44-7b2b461e849c)
