### ISSUE TITLE
The MetadataTransformer always calls backing code even when a component should be lazily rendered

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#1201]
The full discussion is at:
http://forum.primefaces.org/viewtopic.php?f=3&t=44653&p=139694

Substantially, even if my dialog is dynamic="true", the backing bean getters that should be triggered only when the dialog is shown, are always called even when the dialog is hidden, due to the fact that MetadataTransformer is executed when a component is added to the view, rather than before rendering.

This vanishes most of the benefits of lazy loading/rendering of some components.

**Comment by tandraschko** [comment]
pls test ;)

**Comment by mauromol** [comment]
Thank you Thomas! Is there an easy way to get an early access build of PF 6.0 via Gradle/Maven?

**Comment by tandraschko** [comment]
Nope, you need to build it by source.
