### ISSUE TITLE
Showcase: v8 errors on all pages

### ISSUE THREAD

**Issue by F1shZ** [primefaces/primefaces#12019]
### Describe the bug

The pages are all returning errors, could you please check? Thank you!
https://www.primefaces.org/showcase-v8/ui/ajax/listener.xhtml
⬇️
https://www.primefaces.org/showcase-v8/error.xhtml

### PrimeFaces edition

None

### PrimeFaces version

8.0.2

### JSF implementation

All

### JSF version

2.2

### Java version

11

### Browser(s)

Chrome

**Comment by Rapster** [comment]
Don't think v8 is relevant anymore, but we can always show the LTS version ? (13 as of today)

**Comment by tandraschko** [comment]
Also we dont have any access to servers.
Can you please ping primetek and Close? @melloware

**Comment by cagataycivici** [comment]
I took it down, it was not supposed to be up.

**Comment by martin654** [comment]
There is a link from current version (14) that now goes to HTTP 404 page

![obrazek](https://github.com/primefaces/primefaces/assets/22746146/b6d7c5fd-2980-4fdc-a213-fd8e0fedcfed)

**Comment by paveljakov** [comment]
Can I run showcase locally somehow? We are still using primefaces 8 on a legacy project and we use showcase as very good source of documentation.

**Comment by melloware** [comment]
@paveljakov yes here is the zip file you can download and run yourself: https://github.com/primefaces/primefaces-showcase-legacy/pull/96#issuecomment-1195450914
