### ISSUE TITLE
Rating: required="true" not working

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12024]
### Describe the bug

Reported by @jepsar on Discord

`required="true"` not working for Rating.

### Reproducer

```xml
<p:rating id="rating4" value="#{ratingView.rating4}" required="true" requiredMessage="Please rate us!" />
<p:commandButton value="Rate" action="#{ratingView.onSubmit}" update="messages" process="@this rating4" />
```

### Expected behavior

Required message is displayed

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

ALL

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by Rapster** [comment]
The issue seems to be there https://github.com/primefaces/primefaces/blob/be66036c31c574f266d4d143218562bc16851815/primefaces/src/main/java/org/primefaces/component/rating/RatingRenderer.java#L53

submittedValue should be set to `""` instead of null

**Comment by melloware** [comment]
Nice!   Updating PR.  that was it.  I was staring at this code for like an hour.

**Comment by melloware** [comment]
In case you wanted to see it in action: http://20.161.11.140/showcase/ui/input/rating.xhtml

**Comment by Rapster** [comment]
Is it normal it goes back to 3 after submitting several times?

**Comment by Rapster** [comment]
Also @melloware does it 20.161.11.140 belong to you?

**Comment by melloware** [comment]
yeah its just an Azure VM i have so i can deploy changes to show a client progress on accessibility changes they asked for.

**Comment by melloware** [comment]
> Is it normal it goes back to 3 after submitting several times?

That is really strange why it goes to 3.

**Comment by melloware** [comment]
I can even see in the network traffic its sending "3" but the component input has `value="0"`.  Let me debug this.

**Comment by melloware** [comment]
OK fixed in another PR along with keyboard bugs i found
