### ISSUE TITLE
BlockUI: Interferes with the CSS position of target elements

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#12034]
### Describe the bug

[hide](https://github.com/primefaces/primefaces/blob/8ea7fc27b0749135e5be4a33b0f10e1a33b18fdb/primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js#L186) clears the position of target elements. And if this had been documented, we would still consider it a shortcoming

### PrimeFaces edition

Community

### PrimeFaces version

14

### JSF implementation

Mojarra

### JSF version

any

### Java version

any

**Comment by melloware** [comment]
@mihaiDumea it was done intentionally as part of this ticket: https://github.com/primefaces/primefaces/issues/4393

Here is the commit: https://github.com/primefaces/primefaces/commit/4b460b663308cb2517c2d4e49cf732cfca198279

**Comment by melloware** [comment]
I wonder if the correct thing to do is "restore" the position it had and not just clear it out?

**Comment by melloware** [comment]
I submitted a PR for review

**Comment by mihaiDumea** [comment]
> I wonder if the correct thing to do is "restore" the position it had and not just clear it out?

It will be better, more time limited I would say. It's not perfect, but we don't have a better solution for #4393.
Please improve the PR as per inline review comment, and will fix my test case (target with position: absolute).

**Comment by melloware** [comment]
Yep PR updated please review

**Comment by mihaiDumea** [comment]
Looks good! Thanks!

**Comment by melloware** [comment]
OK this will be in 14.0.1 thanks for the bug report!

**Comment by mihaiDumea** [comment]
> I wonder if the correct thing to do is "restore" the position it had and not just clear it out?

Maybe another idea is that BlockUI should not try to cover all edge cases, but only do the basic and allow the target to handle auxiliary needs. BlockUI can check if target can handle the blocking and transfer responsibility to it, or do the basic itself.

**Comment by melloware** [comment]
@mihaiDumea yep but so many corner cases have been reported and fixed over the years that reverting to the component to be "simpler" will only break existing Elite fixes etc.

**Comment by mihaiDumea** [comment]
Okay, got it.
