### ISSUE TITLE
DataTable: p:link does not work when used in a p:column

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#12049]
### Describe the bug

It is a 15.0.0-SNAPSHOT problem. I tried primefaces-test:jpa repository and changed the below line in test.xhtml. The link appears and seems clickable however it does not work.

```xhtml
<p:column field="stringCol">
  <p:link outcome="/test" value="Test"/>
</p:column>
```

### PrimeFaces edition

None

### PrimeFaces version

15.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

17

**Comment by Rapster** [comment]
Might be related to #11975 

cc @melloware I believe this line  prevents the redirection

https://github.com/melloware/primefaces/blob/e7509d95b53c22c7ee1976a83231c8773a40d921/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L831

**Comment by melloware** [comment]
@Rapster thanks let me investigate!

**Comment by melloware** [comment]
Thanks @aripddev PR submitted.

**Comment by melloware** [comment]
@aripddev can you pull the latest 15.0.0-SNAPSHOT and test again please.

**Comment by aripddev** [comment]
@melloware It works fine, thanks.

**Comment by melloware** [comment]
thanks for reporting and testing!
