### ISSUE TITLE
monitorDownload: not working in Chrome with ajax=false and non-secure Cookies, due to SameSite=None

### ISSUE THREAD

**Issue by metaxmx** [primefaces/primefaces#12045]
### Describe the bug

Since PrimeFaces 14, the `PrimeFaces.monitorDownload()` function does not complete after the download, if the download is performed without AJAX and without secure Cookies.

Apparently the sending of Cookies has changed in the following PR: #11774
Now, the Cookie property "SameSite=None" is always set, when a Cookie is NOT secure (and JSF >= 4.0 is used):
```
        if (isSecure) {
            properties.put("secure", true);
            if (isJsf40OrHigher) {
                properties.put("SameSite", applicationContext.getConfig().getCookiesSameSite());
            }
        }
        else if (isJsf40OrHigher) {
            properties.put("SameSite", "None");
        }
```

This is however against the Spec (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#none), which states:

> SameSite=None
> Means that the browser sends the cookie with both cross-site and same-site requests. 
> **The Secure attribute must also be set when setting this value, like so SameSite=None; Secure. If Secure is missing an error will be logged**:
>
> Cookie "myCookie" rejected because it has the "SameSite=None" attribute but is missing the "secure" attribute.
> 
> This Set-Cookie was blocked because it had the "SameSite=None" attribute but did not have the "Secure" attribute, which is 
> required in order to use "SameSite=None".

In my current Firefox Version, the Cookie is still accepted, but there is a warning printed in the console (the same warning, which was originally reported in #11774 and should be mitigated by the change).

In Chrome, the cookie is rejected alltogether due to this "SameSite=None" attribute, which breaks at least the  `PrimeFaces.monitorDownload()` function, and perhaps any other Cookie-related functionality.

Please consider removing the "SameSite=None" attribute again for Non-Secure Cookies, or setting it to "Lax" instead (which seems to be the default behaviour, when the attribute is not provided, according to the documentation).

### Reproducer

See reproducer: https://github.com/metaxmx/primefaces-test/tree/jakarta (Commit 9dadf0e92acaaef795310d3972927da329a6dd23)

```
<script type="text/javascript">
    function showStatus() {
        PF('statusDialog').show();
    }
    function hideStatus() {
        PF('statusDialog').hide();
    }
</script>

<p:dialog modal="true" widgetVar="statusDialog" header="Status" draggable="false" closable="false">
   Download Running. Please Wait ...
</p:dialog>

<p:commandButton value="Download" onclick="PrimeFaces.monitorDownload(showStatus, hideStatus)" ajax="false">
    <p:fileDownload value="#{fileBean.file}" contentDisposition="attachment"/>
</p:commandButton>
```

Step to reproduce:
1. run the example locally (with Mojarra 4.0 profile)
2. open the page with the newest Chrome (stable) version
3. click the download button
4. the Status-Dialog opens after the download started
6. when the download finished, **the dialog does NOT close again**

### Expected behavior

The status dialog should close, after the download finished

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

Chrome 125.0.6422.142 (Windows 11)

**Comment by melloware** [comment]
Good catch!

**Comment by melloware** [comment]
I will fix this in 14.0.1

**Comment by melloware** [comment]
PR submitted.  Please review.

**Comment by metaxmx** [comment]
Thank you a lot, for the fast reply and PR.

I tested your Change (on the 14.x Branch), and now it works again in Chrome (and also still in Firefox)!

---

However, the message in Firefox still remains. But I think, I also found the root cause of this message: it seems, that it was not triggered by the returned Cookie from the response, but from the cookie in the request:

`core.js`
```
setCookie : function(name, value, cfg) {
    if (location.protocol === 'https:' && PrimeFaces.settings.cookiesSecure) {
        cfg.secure = true;

        if (PrimeFaces.settings.cookiesSameSite) {
            cfg.sameSite = PrimeFaces.settings.cookiesSameSite;
        }
    }
    Cookies.set(name, value, cfg);
},
```

I believe, Firefox is warning against setting a cookie withourt proper SameSite attribute here.

I changed the code on my local install to the following, and I would no longer see the message in firefox:
```
setCookie : function(name, value, cfg) {
    if (location.protocol === 'https:' && PrimeFaces.settings.cookiesSecure) {
        cfg.secure = true;

        if (PrimeFaces.settings.cookiesSameSite) {
            cfg.sameSite = PrimeFaces.settings.cookiesSameSite;
        }
    } else {
        cfg.sameSite = "Lax"
    }
    Cookies.set(name, value, cfg);
},
```

**Comment by melloware** [comment]
OK PR updated i agree about setting the cookiesSameSite if its set.

**Comment by melloware** [comment]
I actually improved it a little further

```js
        /**
         * Sets the value of a specified cookie with additional security configurations.
         * If the page is served over HTTPS and cookies are configured to be secure in the settings,
         * the secure flag will be set. The SameSite attribute is set based on the settings or defaults to 'Lax'.
         * @param {string} name The name of the cookie.
         * @param {string} value The value to set for the cookie.
         * @param {Partial<Cookies.CookieAttributes>} [cfg] Configuration for this cookie: when it expires, its
         * paths and domain and whether it is secure cookie.
         */
        setCookie : function(name, value, cfg) {
            cfg.secure = location.protocol === 'https:' && PrimeFaces.settings.cookiesSecure;
            cfg.sameSite = PrimeFaces.settings.cookiesSameSite || "Lax";
            Cookies.set(name, value, cfg);
        }
```
