### ISSUE TITLE
SelectOneMenu: Please add a “clear” Ajax Behavior in editable mode

### ISSUE THREAD

**Issue by EugenFischer** [primefaces/primefaces#12067]
### Description

If the component p:selectOneMenu is switched to editable mode, 
there is no dedicated event if the previously selected value was changed or deleted via the keyboard.
Only a blur event triggers a change event.

### Describe the solution you would like

It will be nice if on clear the change event get also triggert. 
Or a dedicated "clear" Ajax Behavior could be registered.

### Additional context

My dirty "monkey patch"

```
PrimeFaces.widget.SelectOneMenu

...
bindEvents {
...
       //onchange handler for editable input
        if (this.cfg.editable) {
            this.label.on('change', function (e) {
                $this.triggerChange(true);
                $this.callHandleMethod($this.handleLabelChange, e);
            });
           // trigger change on input event
            this.label.on('input', function (e) {
                $this.triggerChange(true);
                $this.callHandleMethod($this.handleLabelChange, e);
            });
        }
...
}
```

**Comment by melloware** [comment]
couldn't this just be...

```js
if (this.cfg.editable) {
            this.label.on('change input', function (e) {
                $this.triggerChange(true);
                $this.callHandleMethod($this.handleLabelChange, e);
            });
        }
```

**Comment by EugenFischer** [comment]
sure, but **input** event get fired on each entered or deleted character. 
may you have an better idea how to "collect" such changes for real "clear"

**Comment by melloware** [comment]
I think I have an idea

**Comment by tandraschko** [comment]
can i ask you why exactly do you need this functionality?

**Comment by melloware** [comment]
it matches the `clear` ajax event we have on AutoComplete.

**Comment by EugenFischer** [comment]
@melloware well done!
could have thought of it myself.
Would it be possible to make this feature available for version 13 / 14 as well?

**Comment by melloware** [comment]
@EugenFischer because this is not a bug....only bugs get backported.  If you need this in 14.0.1 or 13.0.11 you would need to make the request through your PRO account if you have one.
