### ISSUE TITLE
[Documentation] Showcase v.8

### ISSUE THREAD

**Issue by diogo-cvs** [primefaces/primefaces#12069]
### Describe the bug

The documentation (showcase) for version 8.0 is inaccessible https://www.primefaces.org/showcase-v8/

### PrimeFaces edition

None

### PrimeFaces version

8.0

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/12019

**Comment by melloware** [comment]
@diogo-cvs see this for a solution: https://github.com/orgs/primefaces/discussions/2031
