### ISSUE TITLE
DataTable Excel Exporter tableExport method is called twice

### ISSUE THREAD

**Issue by hasanyildiz** [primefaces/primefaces#12063]
### Describe the bug

hi,
i have a datatable and dataExporter that exports data to excel file using type xlsx(xlsxstream also same result).
The problem is that after export excel process is finished, file download starts but immediately after that, export operation is called again(ie. DataTableExcelExporter.exportTable method is called again). For big amount of columns and rows, this causes a big problem.

i have attached a test projest that reproduces the problem, 

it happens when profile mojarra22 is selected. Also in my own project, the same dependency exists.

[primefaces-test-13.0.9_excel-export.zip](https://github.com/user-attachments/files/15537046/primefaces-test-13.0.9_excel-export.zip)

### PrimeFaces edition

None

### PrimeFaces version

13.0.9

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

**Comment by melloware** [comment]
Looks like a Mojarra bug in 2.2.  You should upgrade as Mojarra has stopped supporting 2.2 so don't expect any fixes.

Mojarra 2.2 = **FAILS**
Mojarra 2.3 = **PASSES**
MyFaces 2.2 = **PASSES**
MyFaces 2.3 = **PASSES**

So not a PrimeFaces bug.

**Comment by melloware** [comment]
In fact last Mojarra 2.2 release is 2.20 and it was released 5 years ago

![image](https://github.com/primefaces/primefaces/assets/4399574/66775ada-acb7-4136-94b2-e26964b97a1c)
