### ISSUE TITLE
Chart: XDev model should be identified corresponding chart model

### ISSUE THREAD

**Issue by dengbingaliyun** [primefaces/primefaces#12074]
### Description

I am trying to update my project from  primefaces v13 to new version v14. But I've encountered some problem on updating to p:chart.So that I couldn't update to v14 successfully.
I think the new component p:chart mainly focus on how to display chart by specifying the chartjs json tring value only,but it missing on how to bind corresponding model.
Take ItemSelectEvent in version 13 for example, it's easy to fetch the data (x value and y value) of the selected point by code :

```
    public void nodeSelect(ItemSelectEvent event) {

        LineChart source = (LineChart) event.getSource();
        List<ChartDataSet> dataSets = source.getModel().getData().getDataSet();
        var dataSet =  dataSets.get(0);
        this.point = dataSet.getData().get(event.getItemIndex());
        this.label = dataSet.getLabel();

    }
```
In version 14, I could not find any way to locate the selected point data from ItemSelectedEvent.

### Describe the solution you would like

Please add model attribute in <p:chart/> to support XDEV chartjs-model .

**Comment by melloware** [comment]
Isn't that this exact example: https://www.primefaces.org/showcase/ui/chart/bar.xhtml?jfwid=6120c

It uses XDeV model and AJAX item select?

Or do I not understand what you are trying to do?

**Comment by Rapster** [comment]
I believe he wants the underlying XDev model. Basically, keep on the side a BarChart attribute for instance, and then do something like this:

```java
    public void itemSelect(ItemSelectEvent event) {
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Item selected",
                "Value: " + event.getData()
                + ", Item Index: " + event.getItemIndex()
                + ", DataSet Index:" + event.getDataSetIndex());

        Object barDataset = barChart.getData().getDatasets().get(event.getDataSetIndex()).getData().get(event.getItemIndex());
        // do something with it
    }
```

**Comment by melloware** [comment]
@dengbingaliyun i see now yes because the component doesn't have your XDev model only a copy of the String JSON you would need to hold your model value in your bean as @Rapster suggested.

**Comment by melloware** [comment]
[primfaces14-chart.zip](https://github.com/user-attachments/files/15794833/primfaces14-chart.zip)
