### ISSUE TITLE
Documentation: Missing / Outdated

### ISSUE THREAD

**Issue by hink084** [primefaces/primefaces#12079]
### Describe the bug

VDL documentation is missing for PrimeFaces v10 - v14.

The latest VDL documentation I could find is from v8.
https://www.primefaces.org/docs/vdl/8.0/

These links are outdated at the bottom of the documentation page:
https://www.primefaces.org/documentation/

![VDL](https://github.com/primefaces/primefaces/assets/5665720/3e5f193c-ce6e-453b-858d-d5bb9d1e7896)

I believe the Wiki hyperlink should be updated to:
https://github.com/primefaces/primefaces/wiki

API's are now located on javdoc.io:
https://javadoc.io/doc/org.primefaces/primefaces/latest/index.html

There should also be a hyperlink to the v14 User Guide from the documentation page as well.
https://primefaces.github.io/primefaces/14_0_0

![UG](https://github.com/primefaces/primefaces/assets/5665720/498da20e-4763-489f-889a-76dee82c2b4f)

### PrimeFaces edition

Community

### PrimeFaces version

10 - 14

### JSF implementation

All

### JSF version

N/A

### Java version

N/A

**Comment by melloware** [comment]
i will take a look at generating the VDL and putting it in our /docs/ folder for publishing

**Comment by melloware** [comment]
@hink084 new permanent home of up to date VDL docs: https://primefaces.github.io/primefaces/vdldoc/
