### ISSUE TITLE
DataTable scroll with lazy loading and filtering doesn't work

### ISSUE THREAD

**Issue by CSchulz** [primefaces/primefaces#1207]
Consider the following datatable:

```
<p:dataTable var="data" value="#{controller.lazyDataModel}" lazy="true"
    sortBy="#{data.id}" rowKey="#{data.id}" scrollable="true" liveScroll="true" scrollRows="50"
```

Works fine, but if you are using the _FilterFeature_. It seems that there is missing the check for **liveScroll**. It tries to load the data via normal lazy data, which requires the **rows** attribute and therefor it assume 0 rows.

I am using version 5.3.

DataTable preRender:

```
    protected void preRender(FacesContext context, DataTable table) {
        if(table.isLazy()) {
            if(table.isLiveScroll())
                table.loadLazyScrollData(0, table.getScrollRows());
            else
                table.loadLazyData();
        }
```

vs FilterFeature encode:

```
        if(table.isLazy()) {
            table.loadLazyData();
        }
```

**Comment by cagataycivici** [comment]
Ok got it, thank you.

**Comment by CSchulz** [comment]
You need to fix the SortFeature, too. It haves the same check.

Furthermore it seems that there is something "wrong" with the reset when changing the filter. It seems that the new method doesn't trigger the reset of the scrollstate and this causes wrong offset request to the server, resulting in displaying nothing more after loading.

To fix it, I need on client side following code:

```
    datatable.clearScrollState();
    datatable.restoreScrollState();
    datatable.setupScrolling();
```

Perhaps it is the wrong place to start with the fix?

**Comment by mertsincan** [comment]
Please create a new issue.
