### ISSUE TITLE
FileUpload: No error message on allowTypes mismatch after component update

### ISSUE THREAD

**Issue by mstichweh** [primefaces/primefaces#12075]
### Describe the bug

When the fileUpload component is used with the new `p:validateFile` child tag to specify the `allowTypes`, the component does not show an error for an invalid file type after the component has been updated by ajax and the `allowTypes` value has changed. Just a warning message is shown in server log: `The uploaded filename ... does not match the specified regex ...`  
Also the `onvalidationfailure` JavaScript code is not executed.

To reproduces the error, the provided reproducer code can be used:  
1. Change the type selection from "PDF" to "PNG"
2. This updates the fileUpload component and changes the `allowTypes` attribute value
3. Select a PDF file to upload
4. No error is shown to the user and the `onvalidationfailure` JavaScript code is not executed

If instead the old deprecated `allowTypes` attribute of the fileUpload component is used, everything works fine.

### Reproducer

XHTML:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="jakarta.faces.html"
      xmlns:f="jakarta.faces.core"
      xmlns:p="http://primefaces.org/ui">
    
    <h:form>
            <p:selectOneMenu value="#{testView.allowTypes}">
                <f:selectItem itemLabel="PDF" itemValue="/\.pdf$/" />
                <f:selectItem itemLabel="PNG" itemValue="/\.png$/" />
                <p:ajax process="@this" update="testUpload" />
            </p:selectOneMenu>

            <p:fileUpload id="testUpload" mode="advanced"
                          multiple="true" auto="true" onvalidationfailure="alert('ERROR');">
                <p:validateFile allowTypes="#{testView.allowTypes}" />
            </p:fileUpload>
        </h:form>
</html>
```

Bean:

```
import jakarta.faces.view.ViewScoped;
import jakarta.inject.Named;

import java.io.Serializable;

@Named
@ViewScoped
public class TestView implements Serializable
{
	private String allowTypes = "/\\.pdf$/";


	public String getAllowTypes()
	{
		return allowTypes;
	}


	public void setAllowTypes( String allowTypes )
	{
		this.allowTypes = allowTypes;
	}
}
```

### Expected behavior

The error message about invalid file type should be shown and the `onvalidationfailure` JavaScript code should be executed if an invalid file type is uploaded after the `allowTypes` value of the `validateFile` child component has been changed via ajax.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

21

**Comment by tandraschko** [comment]
copied the example to a fresh primefaces-test and
1) added h:head
2) activated CSV via web.xml
3) added apache poi (because of the stringutils bug already fixed in master)

-> works fine for me

**Comment by tandraschko** [comment]
also adjusted the migration guide that CSV needs to be enabled
