### ISSUE TITLE
DatePicker: add Week Picker, similar to Month Picker

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12089]
### Description

current DatePicker provides a Month picker, but a not a week picker

### Describe the solution you would like

view=week

**Comment by melloware** [comment]
Did you envision enabling the week picker like in the screenshot and if you clicked on a week it would select the whole week?

![image](https://github.com/primefaces/primefaces/assets/4399574/81acd3c7-4bf3-412c-af04-b47eae0c5c71)

Or were you thinking you click on a month like June and it displayed 22, 23, 24, 25, 26, 27 for the weeks of the year?

**Comment by tandraschko** [comment]
i just thought about the default view like in the example above, just that the CW is clickable and all days looks selected maybe?

**Comment by melloware** [comment]
yeah i think that could work.
