### ISSUE TITLE
Separator: Deprecate

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#12080]
### Describe the bug

If you try to search separator nothing comes out.
If you scroll down up to the "Misc" group, you can't find "separator".

But I found it !
https://www.primefaces.org/showcase/ui/misc/separator.xhtml? 

### Reproducer

Just try to search the separator in the showcase.

### Expected behavior

After typing "separator" in the search field, it must come out.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-SNAPSHOT

### JSF implementation

All

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Separator was replaced by Divider: https://www.primefaces.org/showcase/ui/panel/divider.xhtml?jfwid=92c05

It was left in for backwards compatability for those still using it but the showcase example removed from the menu so people would stop using it.

**Comment by ritonglue** [comment]
I see. It would be interesting to make it appear just like "bar", with a "Deprecated" label :
https://www.primefaces.org/showcase/ui/chartjs/bar/bar.xhtml

**Comment by melloware** [comment]
Yep I can do that too.

**Comment by melloware** [comment]
![image](https://github.com/primefaces/primefaces/assets/4399574/ac142a89-a4bb-4185-a778-528764ec0d5e)

**Comment by ritonglue** [comment]
Nice
