### ISSUE TITLE
[Version 7.0] Paginator TreeTable column having SelectOneMenu does not render or loss the default/selected value from the managed bean on navigating to another paginator page tabs.

### ISSUE THREAD

**Issue by Kapil-Gureja** [primefaces/primefaces#12087]
There appears to be some issue with the rendering on using selectonemenu inside paginator treetable. The column showing selectonemenu linked with the managed bean field value shows the correct value only on page1. On all other pages of the treetable, it does not show the correct value as already selected or as default value for the selectonemenu. Instead it shows as if there is no value being returned by the managed bean, selectonemenu with no value selected. Also on navigating back to page 1, again it does not show the selected value for the menu which was there initially on page 1.

`<p:treeTable value="#{createController.relationsModel.relationsRoot}"
var="node" paginator="true" rows="10"
selectionMode="checkbox" id="resultRelations"
styleClass="ui-treetable-resultRelations hide-sel-chkbox"
selection="#{createController.relationsModel.relationSelectedInRelationsTable}"
resizableColumns="true">
<p:column style="width:10%">
<h:outputText value="#{node.code}" rendered="true" />
</p:column>

<p:column
rendered="#{createController.relationsModel.displayCategory}"
style="width:10%">
			<h:outputText value="#{appCSMQBean.interpretCqtBaseCategory(node.category)}"
                rendered="#{node.readOnlyCategory and not node.hideCategory}" style="word-wrap: break-word;" />
			<p:selectOneMenu id="soc2" value="#{node.category}" 
			        rendered="#{not node.readOnlyCategory}"
					autoWidth="false" style="width:75%" disabled="#{createController.readOnlyState}">
				<f:selectItem itemLabel="" itemValue="" noSelectionOption="true"/>
				<f:selectItems var="s" value="#{appCSMQBean.cqtBaseCategoriesWithInactiveSelected(node.category)}"
					itemValue="#{s.value}" itemLabel="#{s.value}" />
					<p:ajax event="change"
					listener="#{createController.notifyCategoryChange()}" update="@form:resultRelations"/>
			</p:selectOneMenu>
            
		</p:column>`

The issue is only with the column having selectonemenu, not with the columns having outputText. Please advise if there is any bug with this? Thanks
<img width="918" alt="SS1" src="https://github.com/primefaces/primefaces/assets/14810186/6783ab11-f577-4d63-bb03-fad98cc084e0">
<img width="920" alt="SS2" src="https://github.com/primefaces/primefaces/assets/14810186/8d8a812e-2dfd-457d-8586-cad5a9023f78">
<img width="940" alt="SS3" src="https://github.com/primefaces/primefaces/assets/14810186/517a3122-deed-4a5e-8663-3b3b13db60cb">

**Comment by Rapster** [comment]
1. We maintain an issue template for a reason...
2.  Format your code!
3. Provide a reproducer
4.  Even though there is an issue, don't expect to be fixed in 7.0 (at least try with 13.0.x)

**Comment by tandraschko** [comment]
will close it until we have a primefaces-test reproducer, which shows a bug in 14.0.0.
