### ISSUE TITLE
Taglib: Components missing descriptions

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12083]
looking at the VDL doc we have some components missing descriptions.

https://primefaces.github.io/primefaces/vdldoc/

![image](https://github.com/primefaces/primefaces/assets/4399574/d592bf83-9ab8-4db6-89e9-5e3eda88d3f4)

**Comment by tandraschko** [comment]
in general we could improve it
"Wizard provides an ajax enhanced UI".... everything in PrimeFaces is ajaxified

**Comment by melloware** [comment]
Yeah i will review all the descriptions and add the missing ones and regenerate the VDL.
