### ISSUE TITLE
DatePicker: weird closing behavior / multiple ajax requests

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12088]
[primefaces-test-master.zip](https://github.com/user-attachments/files/15747692/primefaces-test-master.zip)

when you select a date, or just close or play a bit with it, the datepicker flickers and many ajax requests are sent.

im using firefox

**Comment by melloware** [comment]
I am testing with Firefox.  I see that if I just open the panel and then close it by clicking anywhere else in the browser I see two AJAX "close" events fired.  I will fix that.

But I am not seeing any flickering of AJAX requests when selecting a date?

**Comment by tandraschko** [comment]
It occurs in different ways like selecting a date then clicking outside to trigger close

**Comment by melloware** [comment]
@tandraschko are you still having the issue with 14.0.1?

**Comment by tandraschko** [comment]
looks good for me
could it be that the older version didnt close the overlay when selecting a date?
at least the weird behavior is gone

**Comment by melloware** [comment]
Yes it was calling `close` too many times if `hideOverlay` triggering too many AJAX requests.  I will close for now and mark it as fixed in 14.0.1.
