### ISSUE TITLE
p:datatable resizableColumns="true" not works

### ISSUE THREAD

**Issue by projectsforce** [primefaces/primefaces#1209]
If there is filter option, column resizing works only for these with filtering option

**Comment by kukel** [comment]
Badly formulated issue. Version info missing, example missing etc... And please use the forum first

**Comment by cagataycivici** [comment]
I think this is related to #1224, the resizer is too small for columns with no filter so you think they are not working, they are at top right corner. #1224 fixes this though.

**Comment by projectsforce** [comment]
solved in 5.2.9
