### ISSUE TITLE
p:autoComplete: emptyMessage tag does not exist anymore in PF v14.0.0

### ISSUE THREAD

**Issue by martingLab** [primefaces/primefaces#12093]
### Describe the bug

The `emptyMessage` tag does not exist anymore in PF 14, although the `showEmptyMessage` tag still exist. I assume the tag was removed by mistake.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by Rapster** [comment]
https://primefaces.github.io/primefaces/14_0_0/#/../migrationguide/14_0_0

**Comment by melloware** [comment]
@martingLab see this thread for how you can set it if you don't want to use the IL8N locale value: https://github.com/orgs/primefaces/discussions/2093
