### ISSUE TITLE
Tooltip: autoHide="false" does not work

### ISSUE THREAD

**Issue by redddcyclone** [primefaces/primefaces#12098]
### Describe the bug

Hello all.

Tooltip's autoHide="false" is not working. If I move the mouse over the tooltip's content, it disappears whether autoHide is set as "true" or "false". Last version I remember it worked was 13.

This was tested on Edge, Chrome and Firefox.

### Reproducer

This happens even in the [showcase](https://www.primefaces.org/showcase/ui/overlay/tooltip/tooltipOptions.xhtml).

### Expected behavior

Tooltip should stay on place when hovered on so I can select it's contents.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
If you want to verify the fix its deployed here: http://20.161.11.140/showcase/ui/overlay/tooltip/tooltipOptions.xhtml?jfwid=dcbcd

**Comment by redddcyclone** [comment]
Hi @melloware 

It did work, but only up to a certain mouse speed. If I move the mouse a bit fast, the tooltip disappears...

**Comment by melloware** [comment]
the mouse HAS to cross into the tooltip.  If you touch any other part outside the button with your mouse it dissappears you have to cross "where the arrow is".

**Comment by melloware** [comment]
it should behave the same as here: https://primereact.org/tooltip/#autohide

**Comment by redddcyclone** [comment]
@melloware indeed, if I cross the mouse outside of the arrow (which is very easy to happen as the arrow is a bit small), the tooltip disappears, but this does not happen in the PrimeReact example you mentioned. In this example, I can move the mouse to the tooltip without having it exactly over the arrow.
Having to cross exactly on the arrow wasn't the behavior before this bug happened, as I remember setting tooltips to huge blocks of text and being able to move the mouse to the tooltip from every part of the text, as long as I didn't get out of the tooltip's boundaries.

**Comment by melloware** [comment]
So here is the code on "mouseout" of the button.

```js
this.allowHide = !(mouseTarget.is(this.target) || 
                               mouseTarget.hasClass('ui-tooltip-arrow') ||
                               mouseTarget.attr('aria-describedby') === this.id || 
                               mouseTarget.parent().attr('aria-describedby') === this.id);
```

Basically if the target of the mouseout is either the button itself, the arrow, or the tooltip it remains open.  ANY other element that is the target of the mouse out will close the tooltip.

for example in the showcase I can see the `e.relatedTarget` is "div.card" when you mouse out of the button and closes the tooltip because it doesn't meet any of the above criteria.

I can change it where the tooltip is sticky and the ONLY way it gets hidden is if you enter the tooltip and then leave it?

**Comment by melloware** [comment]
i will see if I can improve the behavior.

**Comment by redddcyclone** [comment]
Shouldn't ```mouseTarget.hasClass('ui-tooltip-arrow')``` be ```mouseTarget.hasClass('ui-tooltip')``` instead? The ```ui-tooltip-arrow``` element is really small. I think that the target should be the entire tooltip div (I don't know if it works like this, but well...)

**Comment by melloware** [comment]
That is just for the arrow the tooltip itself is handled by this...

```js
mouseTarget.attr('aria-describedby') === this.id || mouseTarget.parent().attr('aria-describedby') === this.id)
```

**Comment by redddcyclone** [comment]
@melloware I tried editing this part of the source I mentioned via the browser devtools, added ```mouseTarget.hasClass('ui-tooltip') ``` along with the check present for ```ui-tooltip-arrow``` and it did work like it should. 

Also, I think the code you mentioned is check if the ```aria-describedby```attribute is present *on the tooltip* instead of on the button. I tried adding this attribute to the tooltip div mentioning it's own ```id``` attribute and it worked that way too.

**Comment by melloware** [comment]
@redddcyclone did you want to submit a PR?

**Comment by redddcyclone** [comment]
OK, I'm working on it

**Comment by redddcyclone** [comment]
@melloware I submitted a PR with a fix for this, please comment if anything's wrong. I'm not that much used to GitHub yet.

**Comment by melloware** [comment]
Looks great thanks for the fix and testing!

**Comment by redddcyclone** [comment]
Thanks a lot!

**Comment by redddcyclone** [comment]
@melloware 

I detected a new bug on 14.0.1 related to the code I committed. The tooltip gets stuck if the components' ID have a colon or any other characters that should be escaped in a selector. I missed adding a ```$.escapeSelector``` to ```this.id``` on the ```mouseTarget.closest``` function. Should I open a new issue to post a new PR?

**Comment by melloware** [comment]
Yes open a new issue please.
