### ISSUE TITLE
FileUpload error

### ISSUE THREAD

**Issue by OBUTTERLIN** [primefaces/primefaces#12090]
### Describe the bug

I'm testing Primefaces 14 on Wildfly 31 and at this time I have detected a problem with the fileUpload component.
When I submit the form, I got this error :

2024-06-08 16:55:08,343 SEVERE [jakarta.enterprise.resource.webcontainer.faces.context] (default task-1) jakarta.servlet.ServletException: UT010016: Not a multi part request: jakarta.servlet.ServletException: UT010016: Not a multi part request

Is there anything I can do to avoid this error?

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4

### Java version

21

**Comment by Rapster** [comment]
```xml
<h:form enctype="multipart/form-data" >
...
</h:form>
```

**Comment by melloware** [comment]
@Rapster @OBUTTERLIN is saying on Discord his exact code works in 13.0.0 but in 14.0.0 he has to add enctype="multipart/form-data" now.  We don't have anything in the migration guide about this so i am wondering what change it was?

**Comment by tandraschko** [comment]
Isn't it fixed in trunk? It was the missing return statement

**Comment by melloware** [comment]
Oh is it this issue fixed in the upcoming 14.0.1: https://github.com/primefaces/primefaces/issues/11806
