### ISSUE TITLE
DataTable: Handling of Columns in column group differs from body

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#12099]
### Describe the bug

```xhtml
<p:dataTable>
    <p:columnGroup type="header">
        <p:row>
            <p:columns value="#{myBean.columnList}" var="c" rendered="#{c ne null}" headerText="#{c.name}" />
        </p:row>
    </p:columnGroup>


    <p:columns value="#{myBean.columnList}" var="c" rendered="#{c ne null}">
        <h:outputText value="#{c.name}" />
    </p:columns>
</p:dataTable>
```

The above code snippet demonstrates, that `p:columns#rendered` does not work inside the `p:columnGroup` but it does work in the header. Reason is the specialized logic to render the column group which first checks, if the [`p:row`'s children is renderable](https://github.com/primefaces/primefaces/blob/8a659235f064a27b306888c1c295d248ff36a377/primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java#L957C29-L957C63) and then applies the state to `p:columns`. While the body first applies the state and then [checks for renderable](https://github.com/primefaces/primefaces/blob/8a659235f064a27b306888c1c295d248ff36a377/primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java#L1231).

This should be aligned to be the same logic - first apply, then check.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0, 15.0.0-SNAPSHOT (master)

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

8u3xx

**Comment by melloware** [comment]
@fanste do you have a PR?

**Comment by fanste** [comment]
Not yet. If there is time tomorrow, I will try to create one.

**Comment by Rapster** [comment]
Avoid using `p:columns` with `rendered` attribute, specially when the condition is based on `var` value. Instead, filter your `columnList` first (probably we should update the doc, not the first time I'm giving that advice...)

**Comment by fanste** [comment]
> Avoid using `p:columns` with `rendered` attribute, specially when the condition is based on `var` value. Instead, filter your `columnList` first (probably we should update the doc, not the first time I'm giving that advice...)

This is known. We just stumpeled upon this in a q'n'd feature mockup, before it will be implemented properly.

**Comment by fanste** [comment]
Internal test is currently in progress, then I will submit the PR.

**Comment by fanste** [comment]
PR is ready: #12109
