### ISSUE TITLE
p:dataTable pagination buttons are not rendered according to filteredValue at page refresh

### ISSUE THREAD

**Issue by ridvan70** [primefaces/primefaces#1212]
- The pagination buttons are **not** rendered according to the size of **filteredValue** when the page is refreshed from browser. 
- The count of the pagination buttons is calculated acccording to the **value** property instead of filteredValue which has more rows than the filteredValue property.
- The pagination buttons are rendered correctly, after a refiltering.

Environment info:
- GlassFish 4.1.1 (Java EE 7 Web)
- JSF 2.2
- jdk1.7.0_75
- Maven: 
  
  ```
        <dependency>
             <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
             <version>5.3</version>
         </dependency>
         <dependency>
             <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
             <version>7.0</version>
             <scope>provided</scope>
         </dependency>
  ```

**Comment by ridvan70** [comment]
Any progress in this issue?
Any further input needed?

**Comment by ridvan70** [comment]
`rowCount` property of **paginator** is set to `uidata.getRowCount()`, in `org.primefaces.renderkit.DataRenderer` at line 116:
![bildschirmfoto 2016-09-14 um 12 33 33](https://cloud.githubusercontent.com/assets/3897819/18509250/f3261f24-7a77-11e6-9b47-5c5d9a3cb017.png)

Is this a good place to ask for the existence of `filteredValue.size()` - if and only if it exists- instead of `uidata.getRowCount()`?

**Comment by ridvan70** [comment]
What about overwriting the methods `getRowCount` and `getValue` in `org.primefaces.component.datatable.DataTable` as follows?

``` java
    @Override
    public int getRowCount() {
        if (getFilteredValue() == null) {
            return super.getRowCount();
        } else {
            return getFilteredValue().size();
        }
    }

    @Override
    public Object getValue() {
        if (getFilteredValue() == null) {
            return super.getValue();
        } else {
            return getFilteredValue();
        }
    }
```

I've added the above in to `DataTableTemplate` and it seems to work, but needs to be reviewed by devs.

**Comment by melloware** [comment]
Closing ticket as it does not include a reproducer.  will re-open if reproducer is provided using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
