### ISSUE TITLE
Media: Navigating to a given page number in a multi-page PDF file

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#12127]
When viewing a multi-page PDF file, is it possible to make it go to a page we want instead of the first page?
I tried something similar to the following to open page 14 directly in a 30-page pdf file, but it doesn't work. Is there a feature similar to this?

```xhtml
<p:media value="#{pdfView.streamedContent}" player="pdf">
  <f:param name="id" value="#{pdfView.id}" />
  <f:param name="page" value="14" />
</p:media>
```

**Comment by Rapster** [comment]
Use discussions next time, this is an issue tracker. Have a look at https://www.primefaces.org/showcase-ext/sections/documentviewer/advanced.jsf
