### ISSUE TITLE
JavaEE JAR contains JakartaEE URN taglib

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12138]
i think it should only be in the jakarta shade

**Comment by melloware** [comment]
yes it should only be in the shaded JAR let me look at when that code executes.

**Comment by melloware** [comment]
cc @FranzHagel from discussion: https://github.com/orgs/primefaces/discussions/2307

**Comment by tandraschko** [comment]
should we just close it as wont fix for now? i dont know any fix and we remove javax support next year anyway.

**Comment by melloware** [comment]
Agreed. closing.
