### ISSUE TITLE
CommandLink: Tabindex gets removed

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#12130]
### Describe the bug

If `tabindex` is defined on the CommandLink component, the tabindex gets removed when clicking on the link.

Reproducer: [primefaces-test-jakarta-m6ppdbjay7rrtxktxnunxemhoh.zip](https://github.com/user-attachments/files/15866014/primefaces-test-jakarta-m6ppdbjay7rrtxktxnunxemhoh.zip)

### Reproducer

1. Go to http://localhost:8080/test.xhtml
2. Click on the link "Link Tabindex 5"
3. Tabindex is not set anymore

### Expected behavior

If a tabindex is defined, the tabindex should be preserved and not removed.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

MyFaces

### JSF version

4.0

### Java version

21

**Comment by pfumi** [comment]
Possible solution: 

Add attribute to [CommandLinkRenderer#encodeScript](https://github.com/primefaces/primefaces/blob/501eac9504c96f8b30384f440d548438add15ae7/primefaces/src/main/java/org/primefaces/component/commandlink/CommandLinkRenderer.java#L163)
`.attr("tabindex", link.getTabindex(), null);`

[forms.commandlink#enable](https://github.com/primefaces/primefaces/blob/501eac9504c96f8b30384f440d548438add15ae7/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandlink.js#L103)
readd tabindex

```
    enable: function() {
        this.jq.removeClass('ui-state-disabled');
        this.cfg.tabindex ? this.jq.attr("tabindex", this.cfg.tabindex) : this.jq.removeAttr('tabindex');     
    }
```

**Comment by melloware** [comment]
Did you research WHY it gets removed in the first place?

**Comment by pfumi** [comment]
The reason is that on AJAX the link gets disabled, therefore the tabindex is set on -1, and when enabled gets removed.
It was changed from https://github.com/primefaces/primefaces/issues/9384

**Comment by melloware** [comment]
Agreed this is a bug.
