### ISSUE TITLE
Picklist: "An error occurred when processing your submitted information"

### ISSUE THREAD

**Issue by maqjav** [primefaces/primefaces#12139]
### Describe the bug

This error has appeared with 14.0.1, not with 14.0.0.

I have updated to 14.0.1 and picklists that were working with 14.0.0 now they throw this error **when trying to submit a form that contains them** "An error occurred when processing your submitted information".

### Reproducer

This is my code:

**XHTML:**
`<p:pickList id="mypick" value="#{bean.mypick}" var="item" itemValue="#{item}" itemLabel="#{item.name}" converter="#{itemConverter}"/>`

**Bean:**
`this.mypick = new DualListModel<>(dao.getAvailableItems(), dao.getNotAvailableItems());`

**Converter:**
```
@Override
public Item getAsObject(FacesContext context, UIComponent component, String value) {
	if (StringUtils.isNumeric(value)) {
                return dao.getItemById(Long.valueOf(value);
	}

	return null;
}

@Override
public String getAsString(FacesContext context, UIComponent component, Item value) {
	if (value != null) {
		return value.getId().toString();
	}

	return null;
}
```

### Expected behavior

Not throwing the error.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

Mojarra

### JSF version

4.1

### Java version

17

**Comment by melloware** [comment]
@maqjav its because of this closed security issue: https://github.com/primefaces/primefaces/issues/12059

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by tandraschko** [comment]
thats why we should be careful adding something to a bugfix branch, it was expected actually that our tests didnt catch all cases

but lets see with the reproducer

**Comment by melloware** [comment]
Agreed @tandraschko but security flaws should never be treated lightly as they get picked up by all the major Security reporters and then PF gets listed as having a CVE.

**Comment by melloware** [comment]
I have a theory just from looking at the code that the users POJO `item` does not have a proper `equals() and hashcode()` method to properly identify it so when we check `list.contains(item)` its reporting `false`.

**Comment by melloware** [comment]
I will update the migration guide but waiting for @maqjav to confirm that is the issue.

**Comment by maqjav** [comment]
@melloware I don't have those methods, however it works with 14.0.0, so what should I add them with 14.0.1?

**Comment by melloware** [comment]
yes so what happens is say you have a POJO called `Player`.  If you don't have an `equals()` and `hashcode()` in your POJO tellin it what makes a player "unique" it can't be identified in lists and sets.   So it just uses the generic Object Identifier which changes on every created.  So if your Player has say an `id` field you equals and hashcode should be the ID field so it can be the same every time.

It is best practice with POJOs and should fix your issue with 14.0.1.   Here is a great explanation: https://stackoverflow.com/a/2265637/502366

**Comment by melloware** [comment]
For example look at the PrimeFaces showcase Customer POJO: https://github.com/primefaces/primefaces/blob/master/primefaces-showcase/src/main/java/org/primefaces/showcase/domain/Customer.java

**Comment by maqjav** [comment]
@melloware thanks, I will add them then so we can update.

**Comment by melloware** [comment]
I added this to the 14 migration guide

> If you are using a POJO with a converter your POJO must implement equals() and hashcode() properly to ensure submission decode can correctly detect the POJO
