### ISSUE TITLE
TextEditor doesn't detect change of contents

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#12131]
Reported by PRO User;
> The goal : If a machine.domain.tld is inserted into the TextEditor without a "https://" prefix, automatically insert one.
After having used the Quill editor API to modify a Delta containing the text, the <a> tag's href shows the updated value. However, if the page is saved, the valueChangeListener can be used to view the TextEditor's before and after values. They are the same.
The attached .xhtml has a JS function replaceLink( url ) the updates the editor's Deltas.
Set a breakpoint in the attached controller's onHTMLChanged( ValueChangeEvent vce ) method. ...

**Comment by melloware** [comment]
@mertsincan this is causing two integration tests to fail. I am investigating.

**Comment by melloware** [comment]
@mertsincan just submitted this PR: https://github.com/primefaces/primefaces/pull/12135

I don't have their original test case but i am pretty sure `source === 'api'` so right now on every keystroke of a user the `change` is firing which is too much.   So this changes it to only fire if its a NON user input
