### ISSUE TITLE
Knob component's JavaScript class doesn't define functions on the prototype

### ISSUE THREAD

**Issue by kito99** [primefaces/primefaces#1214]
PrimeFaces JavaScript widgets usually define functions on the prototype, which I believe is the correct approach, and makes them easy to override. The Knob component defiens them on the object itself inside of the init() method:

``` javascript
        this.setValue = function(value){
            this.input.val(value);
            this.jq.val(value).trigger('change');
        };
```

This should be defined on the object's prototype outside of the init() method:

``` javascript
setValue: function(value) {
...
}
```

**Comment by mertsincan** [comment]
Thank you very much, Kito :+1:
