### ISSUE TITLE
CSP: primefaces.nonce from request not validated

### ISSUE THREAD

**Issue by danieldi96** [primefaces/primefaces#12140]
### Describe the bug

Hello,
I'm using JSF with Primefaces 8.0.25, spring-framework 5.3.34 and spring-security 5.8.12. 
Primefaces creates a hidden input inside a form with a "primefaces.nonce" but using a tool to test vulnerabilities, I get this error:

"
Identification
PROOF
The scanner submitted the form with a bad CSRF token value and got the same response from the web application.
OUTPUT
The scanner was able to detect that the form `id:j_idt30` has a CSRF token named `primefaces.nonce` which is not
verified by the target web application.
"

Is it a bug and i have to update to PF10 or so on, or I'm missing something? 

### PrimeFaces edition

Elite

### PrimeFaces version

8.0.25

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

8

**Comment by melloware** [comment]
I think you need to upgrade to PF 13.0.6 or higher see this ticket: https://github.com/primefaces/primefaces/issues/11426

**Comment by danieldi96** [comment]
I did it. I saw  https://github.com/primefaces/primefaces/issues/11426 but didn't work. You think will fix it by upgrading it?

**Comment by melloware** [comment]
When you say it didn't work that means you upgraded to 13.0.6 and tested it?  I don't see how it "didn't work" if you are asking if you should upgrade.  PrimeFaces had to make a code fix to support Spring.

**Comment by melloware** [comment]
It could also be a "false positive" by your testing tool.

**Comment by tandraschko** [comment]
in general we only support the newest versions here; see https://github.com/primefaces/primefaces?tab=readme-ov-file#community--elite--pro

please try 14.0 if the same occurs, then we need more explantation from your tool
but likely a false positive or something we cant fix anyway

**Comment by danieldi96** [comment]
I tried to implement the same behaviour of that ticket in my project and the vulnerability still appeared. 
Also, I have SecurityFilterChain which executes a CRSFFilter and theoretically, it adds a _csrf to a HTTP request:
![Untitled](https://github.com/primefaces/primefaces/assets/36486186/7c565ced-648b-415d-ac34-d992c5145b4e)

Vulnerability is still there

**Comment by melloware** [comment]
most likely false positive from whatever tool you are using.

**Comment by tandraschko** [comment]
primefaces.none doest have any relation to spring CSRF

its there to validate CSP and right, its not validated on server side yet
maybe we can add it, not sure if there is a possibility that there is a real security problem when you change nonce value in the fo

**Comment by melloware** [comment]
but primefaces.nonce is NOT a CSRF token its a NONCE for CSP.  That is why this makes no sense. The security tool THINKS its a CRSF and sees it didn't change between two requests and is reporting is as a problem.  

To me that is why I think this is a false positive.

**Comment by tandraschko** [comment]
so what happens:
1) you open a view, we generate a nonce, add it to http header and scripts
2) on a ajax request, we post the nonce (as we cant save it in viewstate in all cases), add it to the http header and render all scripts with this nonce

could a hacker modify the nonce in the form, to execute external JS somehow? not sure?!

we could at least compare the posted nonce with the nonce in the viewstate if available and throw a exception. but that doesnt work for stateless views.

**Comment by melloware** [comment]
We could but ViewState is the CRSF in JSF right?  the nonce is just something we use for CSP unrelated to CRSF?

**Comment by melloware** [comment]
@danieldi96 can you tell us what scan tool you are using.  I have had multiple professional pentration tests done on my apps and multiple security firms have not cited the issue above as an issue or attack vector.

**Comment by tandraschko** [comment]
i dont say that CSP is a CSRF here
i just thought about that report and that it could be still a security flaw, and that modifing the nonce could be somehow allow to execute other scripts (not sure however, we just dont validate, thats all the report says)

**Comment by melloware** [comment]
Oh sorry!  I thought you were saying his CRSF issue is valid.  I see now what you are saying.

**Comment by melloware** [comment]
@tandraschko i thought we fixed this already: https://github.com/primefaces/primefaces/issues/9461

**Comment by danieldi96** [comment]
> @danieldi96 can you tell us what scan tool you are using. I have had multiple professional pentration tests done on my apps and multiple security firms have not cited the issue above as an issue or attack vector.

I'm using Tenable: https://www.tenable.com/
It's another professional penetration tool. Really weird if it detects a false positive but it could be...

**Comment by tandraschko** [comment]
that is different:
if you post the form, the nonce is recevied from viewstate
if the posted nonce is different than that from viewstate, someone is manipulating and we can throw a exception

however, we can only validate in statefull mode

**Comment by melloware** [comment]
@danieldi96 i recommend since you pay for Tenable to open a ticket with them asking them for clarity.

**Comment by tandraschko** [comment]
we should do at least in CSPState#getNonce:

```
            if (context.isPostback() || context.getPartialViewContext().isAjaxRequest()) {
                String nonceRequest = context.getExternalContext().getRequestParameterMap().get(Constants.RequestParams.NONCE_PARAM);

                String nonceViewState;
                Map<String, Object> viewMap = context.getViewRoot().getViewMap(false);
                if (viewMap != null) {
                      nonceViewState = (String) viewMap.get(Constants.RequestParams.NONCE_PARAM);
                      if (context.isPostback()) {
                          if (!nonceViewState.equals(nonceRequest)) {... throw new ...}
                      }
                }

               nonce = isNotBlank(nonceViewState) ? nonceViewState : nonceRequest;

                validate(nonce);
            }
    
```

**Comment by tandraschko** [comment]
just so show you my idea, not developed well or tested ;D

**Comment by melloware** [comment]
Adding @NicolaIsotta since he last worked on https://github.com/primefaces/primefaces/issues/9461 for his thoughts too.  @tandraschko i like your ideas

**Comment by NicolaIsotta** [comment]
I guess that validating the sumbitted nonce against the viewstate one is possible (I mean, there's no chanche that they can be different unless tampered, right?).

For stateless view I think that there's nothing else that we can do, the only possibility is encrypting/decripting.

**Comment by melloware** [comment]
I can make a PR and we can watch the Integration test suite run to see if it doesn't like it. 😄

**Comment by tandraschko** [comment]
yep exactly
for me its ok to only add it for statefull views for now

**Comment by JuanMiguelBG-Ticarum** [comment]
Hi !!!
Do you consider make a backport to the 13.x branch?

**Comment by melloware** [comment]
Getting backport request for LTS 8.0 as well: https://github.com/primefaces/primefaces/issues/14004
