### ISSUE TITLE
MenuButton: not disappearing after clicking in PF 14.0.1

### ISSUE THREAD

**Issue by eftewuer** [primefaces/primefaces#12143]
### Describe the bug

Between PF 14.0.0 and 14.0.1 the behavior of menuItem inside menuButton changed. In 14.0.0 clicking a menuItem makes the menu disappear. In PF 14.0.1 the menu stays open and you have to click somewhere outside the menu (so it looses focus) to make it disappear.

Example xhtml pasted below. Please run the file in any browser (tested on firefox, opera and chromium on Kubuntu 24.04 and Windows 10) in PF 14.0.0 and 14.0.1 to see the difference in menu behavior.

You can also run attached Spring Boot project (pf-demo.zip) and go to localhost:8080/menu.xhtml

### Reproducer

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-us"
      xmlns:h="jakarta.faces.html"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>.:: Primefaces with JoinFaces Example ::.</title>
    <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
</h:head>

<h:body>
    <h:form>
        <p:menuButton id="helpButton" value="Help button" title="Help">
            <p:menuitem value="Help1" title="Help F1" target="_blank">

            </p:menuitem>
            <p:menuitem value="Help2" title="Help2" target="_blank">

            </p:menuitem>
        </p:menuButton>
    </h:form>
</h:body>

</html>
```
[pf-demo.zip](https://github.com/user-attachments/files/15902831/pf-demo.zip)

### Expected behavior

Clicking a menuItem should make the menu disappear.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

Mojarra

### JSF version

4.0 (not sure what PF and JoinFaces use in Spring Boot project)

### Java version

17.0.11

**Comment by melloware** [comment]
@eftewuer here i MenuButton on the latest code and you can see it closes the menu?

https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/menu/menuButton.xhtml?jfwid=7e241

**Comment by melloware** [comment]
Oh got it you just have a link not AJAX.

**Comment by melloware** [comment]
@eftewuer here is a MonkeyPatch 

```js
if (PrimeFaces.widget.MenuButton) {
    PrimeFaces.widget.MenuButton.prototype.bindPanelEvents = function() {
        var $this = this;

        if (!$this.cfg.disabled) {
            this.hideOverlayHandler = PrimeFaces.utils.registerHideOverlayHandler(this, 'mousedown.' + this.id + '_hide', this.menu,
                function() {
                    return $this.trigger;
                },
                function(e, eventTarget) {
                    if (e && !($this.menu.is(eventTarget) || $this.menu.has(eventTarget).length > 0)) {
                        $this.trigger.removeClass('ui-state-focus ui-state-hover');
                        $this.hide();
                    }
                });
        }

        this.resizeHandler = PrimeFaces.utils.registerResizeHandler(this, 'resize.' + this.id + '_align', this.menu, function() {
            $this.handleOverlayViewportChange();
        });

        this.scrollHandler = PrimeFaces.utils.registerConnectedOverlayScrollHandler(this, 'scroll.' + this.id + '_hide', this.jq, function() {
            $this.handleOverlayViewportChange();
        });
    },
}
```
