### ISSUE TITLE
Sticky effect: problem when combine with menu/datatable and dialog

### ISSUE THREAD

**Issue by uvula** [primefaces/primefaces#12154]
### Describe the bug

Sorry sorry sorry
![sticky-menu-behind](https://github.com/primefaces/primefaces/assets/1205197/94e78eb7-5051-41f3-a080-429da5592540)
![sticky-dialog-behind](https://github.com/primefaces/primefaces/assets/1205197/8d946437-b229-4834-98d8-40aa7bd59985)
, in issue 12151 I uploaded a old reproducer ZIP because Eclipse/Git not putting the project to standard workspace, so I zipped old problem again. Now I it should be correct. Sorry.
[primefaces-test.zip](https://github.com/user-attachments/files/15905746/primefaces-test.zip)

A view is combine menu, datatable with sticky effect and also having a dialog, the "z-index" is not handled correct.
Required steps are described in the Reproducer pages itself.

Checked with firefox/chrome/edge. Same problem

### Reproducer

Reproducer added

### Expected behavior

I'd like to have menu on top
Datatable is configured to bounce below the menu.
A dialog is below the datatable header and not visible at all until doing some scrolling/mouse wheel

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
why did you create another ticket when the other one is still open?
