### ISSUE TITLE
DatePicker: Add `defaults` to match legacy Calendar

### ISSUE THREAD

**Issue by jfermat** [primefaces/primefaces#12157]
### Description

I am unable to migrate component **Calendar** to **DatePicker**. 

In **Calendar** I have the attributes **defaultHour, defaultMinute, defaultSecond, defaultMillise** that in case I don't have any value it sets the default time according to its values. 

In **DatePicker** these attributes do not exist and it sets the current time.

### Describe the solution you would like

Add **defaultHour, defaultMinute, defaultSecond, defaultMillisec** attributes to **DatePicker** to perform the same functionality as the **Calendar** component.

**Comment by melloware** [comment]
This was also recently requested on Discussions: https://github.com/orgs/primefaces/discussions/2137

In PrimeReact this property is called `viewDate` see: https://primereact.org/calendar/#api.Calendar.props.viewDate

i think we should call it `viewDate` to be consistent.

**Comment by jfermat** [comment]
The `viewDate` attribute would not be useful to solve the reported problem.

According to the migration from Primefaces 8.0.0 to 10.0.0 it is recommended to change the `Calendar` to `DatePicker` because the `Calendar` was deprecated.

The `Calendar` has the attributes to initialize the time in case the value is null.
https://primefaces.github.io/primefaces/14_0_0/#/components/calendar

Example:
`<p:calendar value="#{calendarView.date}" defaultHour="23" defaultMinute="59" defaultSecond="59" />`

![calendar-defaultTime-withoutValue](https://github.com/primefaces/primefaces/assets/33716069/0c1fd4cf-a1ec-48d6-a6d6-31513553439c)

However,`DatePickers` do not have them and I would need this functionality.
https://primefaces.github.io/primefaces/14_0_0/#/components/datepicker

**Comment by tandraschko** [comment]
would be great ticket for sponsoring
