### ISSUE TITLE
Menu: Enhance Submenu to support navigation

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1216]
In many applications a submenu itself can redirect to a summary page for example or simply to its home.

This may be in conflict in case submenu only shows on click but if it expands on hover it should not be a problem.

We also need this for adamantium menu.

**Comment by djmj** [comment]
We decided to add an "info / overview" item as first child for each submenu programmatically which will target the summary / category page this submenu item represents.

On mobile there could also be conflict with open a submenu "on click" and actually wanting to navigate there.

**Comment by melloware** [comment]
@djmj you can already do this.  See the TieredMenu "Quit" button is a top level menu item that can do navigation.  It is a regular MenuItem mixed with SubmenuItem so don't use a SubMenuItem.  See: https://www.primefaces.org/showcase/ui/menu/tieredMenu.xhtml?jfwid=31c54

If you mean this for the Adamantium menu then that is a premium issue not for the Community.
