### ISSUE TITLE
Showcase: CRUD page can't create new product

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#12164]
### Describe the bug

go to
https://www.primefaces.org/showcase/ui/data/datatable/crud.xhtml
Hit the "New" button : it blows.

I tried to reproduce the error with the 15.0.0-SNAPSHOT but I didn't succeeded deploying to wildfly-25.0.1-Final.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
It must be fixed because here is Showcase 14.0.1: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/crud.xhtml?jfwid=b73b1

**Comment by ritonglue** [comment]
Thanks melloware for the quick answer.
