### ISSUE TITLE
SelectOneButton: badges to work and have icon/iconPos parameters for each item

### ISSUE THREAD

**Issue by philpil** [primefaces/primefaces#12162]
### Description

It would be good if badges could work with selectOneButton items and if those items could have the icon/iconPos parameters so they work and feel more like Buttons

### Describe the solution you would like

to allow something like 
<p:selectOneButton value="#{selectOneButtonView.option}">
            <p:badge value="8" severity="danger">
              <f:selectItem itemLabel="Option1" iconPos="left" icon="pi pi-check" itemValue="Option1"/>
            </p:badge>
            <f:selectItem itemLabel="Option2" itemValue="Option2"/>
            <f:selectItem itemLabel="Option3" itemValue="Option3"/>
        </p:selectOneButton>

**Comment by melloware** [comment]
@jepsar i feel like this is not possible

**Comment by philpil** [comment]
even if the selectItem had parameters like badgeSeverity, badgeValue and badgeIcon, badgeSize, badgePosition?

**Comment by melloware** [comment]
same explanation i gave here: https://github.com/primefaces/primefaces/issues/10706

**Comment by philpil** [comment]
i guess can we see if these options are available?

maybe a p:selectItem would be best options 

https://github.com/primefaces/primefaces/issues/10706#issuecomment-1733638848

**Comment by melloware** [comment]
yeah most likely would have to be financially sponsored to happen...

**Comment by melloware** [comment]
I just combined the ticket so I will close this one.
