### ISSUE TITLE
Charts: new Model options `responsive` and `maintainAspectRatio` are active by default

### ISSUE THREAD

**Issue by Del-Tab** [primefaces/primefaces#12173]
### Describe the bug

Maybe not a bug but more of a missing entry from the migration guide.
The What's new page [here ](https://primefaces.github.io/primefaces/13_0_0/#/gettingstarted/whatsnew) states :
![image](https://github.com/primefaces/primefaces/assets/34426732/d4718b63-11d1-463f-9772-88dd5703e60b)
The 2 first options, `responsive` and `maintainAspectRatio`, are active by default since primefaces 13.X

It breaks page placement.
dev stuff : 
new options appeared  since git revision ff2fa9dd5900c97b0900015b8e45e2218fedc1ba (on 2023-01-31 evening) for 13.X+

### Reproducer

The display is changed potentially for every ChartOption 
Reproduced with donutChart 
```
<h:panelGroup layout="block" >
  <p:donutChart model="#{adapter.myDonut}"/>
</h:panelGroup>
```
and the getMyDonut method being : 
```
public DonutChartModel getMyDonut() {
    DonutChartModel donutModel = new DonutChartModel();
    DonutChartOptions chartOptions = new DonutChartOptions();
    // customize chartOptions
    donutModel.setOptions(chartOptions);
    ChartData data = new ChartData();
    // set dataSet and labels inside data
    donutModel.setData(data);
}
```

Notice that between primefaces 12.X and 13.X the display is different (especially the placement of the donut): 
in 12.0.8
![image](https://github.com/primefaces/primefaces/assets/34426732/70aab10d-3812-449d-b457-b66009ceeefb)
in 13.0.10 
![image](https://github.com/primefaces/primefaces/assets/34426732/ee4a5155-4f3c-4a9a-ad4f-ac0da85f2a64)

From the code sample above a workaround would be to add `chartOptions.setMaintainAspectRatio(false)` to get the same display as before migration from 12.0.8 to 13.0.10.

### Expected behavior

Either the option is disabled by default (maybe its a bad idea, too hard to digest for any client using 13.0.10 already and having set up their css to fit this behavior)
Or the [Migration guide 12.0.0 -> 13.0.0](https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0?id=migration-guide-1200-gt-1300) explains that all/some of the classes extending ChartOptions now set MaintainAspectRatio by default and that we must call `setMaintainAspectRatio(false)` to get the `12.0.0` display.
I'd provide a PR for this but I'm not well trained in wording technical official Primefaces documentation (also I only noticed a difference with donutCharts for now) :) 

### PrimeFaces edition

None

### PrimeFaces version

13.X up to 13.0.10

### JSF implementation

MyFaces

### JSF version

3.0.0

### Java version

11

**Comment by melloware** [comment]
@Del-Tab can you submit a PR to update the migration guide?

**Comment by Del-Tab** [comment]
> @Del-Tab can you submit a PR to update the migration guide?

Hello @melloware , I'm on my client environment right now and I can't test that what I write is displayed correctly. I can do a blind coding though, through the github web interface :)
I'll set the master branch as a target, is this ok ? 
I noticed that on [official page](https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0), there is an alignment issue with the `Menu` chapter and I don't see the reason in the master branch, maybe you'll have to cherry pick this fix to the branch which is in the delivery process for the web page

**Comment by melloware** [comment]
No worries i can make the fix.  I do see those formatting issues in the Doc website but I can't tell why either the Markdown looks fine.

**Comment by Del-Tab** [comment]
@melloware
I wrote https://github.com/primefaces/primefaces/pull/12174
 can you confirm that concerned classes are all the classes whose name end by `ChartOptions` ? Is this an enforced name convention ?

**Comment by melloware** [comment]
Confirmed.  That looks good.
