### ISSUE TITLE
DatePicker: multiple Android issues

### ISSUE THREAD

**Issue by zeppelinux** [primefaces/primefaces#12172]
### Describe the bug

Looks like the on-screen keyboard popping up is triggering the dialog to hide.

### Reproducer

1. Use Android phone and go to https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml
1. Click on DatePicker input field  (Basic, or Popup, Month Picker, time only, ... anything besides Multiple selection and Range)
2. See the popup briefly appears, keyboard shows and popup disappears.

### Expected behavior

Pupup stays

### PrimeFaces edition

Community

### PrimeFaces version

14

### JSF implementation

MyFaces

### JSF version

2.2+

### Java version

21

**Comment by melloware** [comment]
@FlipWarthog and I will work on this. I am pretty sure I know how to fix it based on PrimeReact fixes I have made before.

**Comment by melloware** [comment]
@zeppelinux can you try this MonkeyPatch:

```js
PrimeFaces.utils.registerResizeHandler = function(widget, resizeNamespace, element, resizeCallback, params) {

    const unbindResizeHandler = function() {
        $(window).off(resizeNamespace);
    };

    if (PrimeFaces.env.isTouchable(widget.cfg)) {
        return {
            unbind: unbindResizeHandler
        };
    }

    widget.addDestroyListener(unbindResizeHandler);
    widget.addRefreshListener(unbindResizeHandler);

    $(window).off(resizeNamespace).on(resizeNamespace, params || null, function(e) {
        if (element && (element.is(":hidden") || element.css('visibility') === 'hidden')) {
            return;
        }

        resizeCallback(e);
    });

    return {
        unbind: unbindResizeHandler
    };
};
```

**Comment by melloware** [comment]
@FlipWarthog i also deployed here if you want to try from your Android: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/input/datepicker/datePickerJava8.xhtml

**Comment by zeppelinux** [comment]
@melloware tried the link, didn't work for me

**Comment by melloware** [comment]
I know why the DatePicker has its own resize handler.  Let me push another change.

**Comment by melloware** [comment]
OK can you refresh your cache and try again?  same link.

**Comment by zeppelinux** [comment]
Doesn't work very reliably for me (sometimes it blinks and popup doesn't stay) and the fact that keyboard 'jumps' from the bottom of the screen and slides back is very annoying. Not sure if if it's possible to get rid of this keyboard action altogether (as is the case for multiselect or range datepicker right now - all is smooth), but I would choose that if there is a choice.

**Comment by melloware** [comment]
i wonder if a scroll event is being triggered as well as a resize event.  This is why I hate Android.  iPhones don't have this issue 😄

**Comment by zeppelinux** [comment]
Not sure if this is scroll though, looks more like - 'show keyboard because user tapped in the input field' event... but I'm not entirely sure.

**Comment by melloware** [comment]
@zeppelinux ok i just tested with @FlipWarthog  So some observations:

1. Its fixed the behavior is now correct.
2. What you are seeing is because the input gets focus and `showOnFocus="true"` it pops up the keyboard but then immediately focuses the popup due to ARIA Accessibility requirements. If you don't want that use `showOnFocus="false"`
3. See the "Button" example here which has `showOnFocus="false"` https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/input/datepicker/datePickerJava8.xhtml

So currently we are meeting ARIA accessibility guidelines and it seems the Android issues are fixed.  The only real issue is the "flashing" keyboard with Android and the only way to remember that is "showOnFocus="false".

**Comment by zeppelinux** [comment]
WooHooo! Thanks a lot!

**Comment by melloware** [comment]
@zeppelinux i pushed 14.0.2 and Quarkus PF 3.14.2 if you want to deploy and test your Android code with DatePicker.
