### ISSUE TITLE
stickyheader into a tabview doesn't work

### ISSUE THREAD

**Issue by shinteck** [primefaces/primefaces#1218]
Hi,

like the title suggests I have tried to use the stickyheader feature for a datatable into a tabview, but it doesn't work because it appears twice in the view.

I think it is a wrong calculation of initial fixed position, if I scroll the view it renders with correct positions.

I'm using primefaces 5.3.8 but it is a problem that I have seen also in the latest releases.

Here an example code build by primefaces stickyheader showcase 

`<p:tabView>
    <p:tab title="hjdjkashjahsdhasdasdjkhjkadhsjk">
      <p:dataTable var="car" value="#{dtStickyView.cars}" stickyHeader="true">
        <p:column headerText="Id">
          <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Year">
          <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Brand">
          <h:outputText value="#{car.brand}" />
        </p:column>
        <p:column headerText="Color">
          <h:outputText value="#{car.color}" />
        </p:column>
      </p:dataTable>
    </p:tab>
  </p:tabView>
`

I think there is a bug which calculate in wrong manner the absolute position if it is inner a tabview.

For better understanding you can see rendered code

![schermata 2016-03-09 alle 13 21 48](https://cloud.githubusercontent.com/assets/17744536/13636607/09bc8bd8-e603-11e5-9fee-4cdef1f25ccc.png)

Thanks, Carlo

**Comment by mertsincan** [comment]
Hi,
Please try with;

```
//CSS
.myTabview.ui-tabs {
     position: static;
}

//xhtml
<p:tabView styleClass="myTabview" .. />
```

**Comment by shinteck** [comment]
Hi,

wow it seems to work !!! But it is a fix planned for early releases or I have to fix on my css ?

Thanks, Carlo
