### ISSUE TITLE
Primefaces 8 showcase is down

### ISSUE THREAD

**Issue by pedrodelgado81** [primefaces/primefaces#12183]
### Describe the bug

Primefaces (JSF) showcase is on v14 by default, but if I change to v8 I've got a 404 Not Found
![image](https://github.com/primefaces/primefaces/assets/11388200/8b0c8089-a37c-4dd0-b6f9-c84c3890d51b)
![image](https://github.com/primefaces/primefaces/assets/11388200/a6a6eb11-6611-4636-8647-1d55ff3b9f1b)

### Reproducer

Access to JSF showcase and then change to v8

### Expected behavior

Redirecto to Primefaces (JSF) showcase v8

### PrimeFaces edition

None

### PrimeFaces version

8.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

### Browser(s)

Chrome, Firefox and Opera

**Comment by tandraschko** [comment]
Please use the search before creating a issue: https://github.com/primefaces/primefaces/issues/12019#issuecomment-2136170367

**Comment by pedrodelgado81** [comment]
Ok, I already used search but it seems that not as good as it could, sorry.

**Comment by melloware** [comment]
@pedrodelgado81 also see: https://github.com/orgs/primefaces/discussions/2031
