### ISSUE TITLE
Datatable: Row Edit bug editing 2 rows at the same time

### ISSUE THREAD

**Issue by YexeY** [primefaces/primefaces#12184]
### Describe the bug

Datatable row editing ceases to function when multiple rows are being edited. 

### Reproducer

1. Start editing mode for more than 1 row
2. Save 1 row
3. Other rows dont work anymore 

![image](https://github.com/primefaces/primefaces/assets/62472265/7c5b61f8-4e6a-4b5f-bbeb-c82ab1e6dc1e)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

All

### JSF version

--

### Java version

18

**Comment by YexeY** [comment]
Hello and thank you for your quick reply! 

We recently upgraded from Primefaces version 12 to 14 and according to my colleague it worked before. 

Yes, that use case does exist, but i get your sentiment. 
However, i think it should either not be possible to start editing multiple rows at once or not break when doing so.
I personally would be fine with both solutions.

**Comment by melloware** [comment]
ok if it used to work in 12 then its a bug.

**Comment by melloware** [comment]
OK I think I know why we made a huge performance improvement with this ticket: https://github.com/primefaces/primefaces/issues/2008

So I think when editing one row from an accessibility point of view other row editors should not be opened until you have acted upon the row you are editing.

**Comment by YexeY** [comment]
A sensible solution, thank you for your time!

**Comment by melloware** [comment]
thanks for the report @YexeY i will put this in 14.0.2
