### ISSUE TITLE
menuitem: JavaScript Error on Hover

### ISSUE THREAD

**Issue by timdoering** [primefaces/primefaces#12190]
### Describe the bug

Hovering over a p:menuitem causes a Javascript error in the console:

> Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at F (jquery.js.xhtml?ln=primefaces&v=14.0.1:2:29760)

### Reproducer

Reproducing is possible with any <p:menuitem> inside of a <p:menu>
`        <p:menu>
            <p:menuitem value="test" />
        </p:menu>`

### Expected behavior

This error does not occur in other PrimeFaces Versions (i tested 14.0.1 vs 12.0.7), so this should not happen i guess

### PrimeFaces edition

None

### PrimeFaces version

14.0.1

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment]
Already reported multiple times, please use the search before: https://github.com/primefaces/primefaces/issues/12136

**Comment by melloware** [comment]
Workaround provided: https://github.com/primefaces/primefaces/issues/12117
