### ISSUE TITLE
Tree: make treenode label selectable/copyable

### ISSUE THREAD

**Issue by f1nnk** [primefaces/primefaces#12197]
### Description

The label of tree nodes is not selectable/copyable. Is there a reason for this?

### Describe the solution you would like

I would like to be able to select and copy the label of the tree nodes just like in the PrimeReact Showcase - https://primereact.org/tree

**Comment by f1nnk** [comment]
Thank you 😄 since our tree is a bit more customized i only got it to work the way i wanted like this:

`if (PrimeFaces.widget.VerticalTree) {
  PrimeFaces.widget.VerticalTree = PrimeFaces.widget.VerticalTree.extend({
	bindKeyEvents: function() {
	  this._super();
	  this.jq.off('mousedown.tree');
	}
  });
}`

Could this cause problems or is it fine to leave it like that?

**Comment by melloware** [comment]
Well that is personal preference but it looks like Primetek had intended the mouse down to be ignored only if you were click into an Input element.

```js
if ($(e.target).is(':not(:input:enabled):not(.ui-treenode-label)')) {
          e.preventDefault();
        }
```

I am not sure why though as that commit was over 10 years ago.
