### ISSUE TITLE
Data Table: cell navigation fix for row selection

### ISSUE THREAD

**Issue by Rene-Stoeckel** [primefaces/primefaces#12198]
### Describe the bug

We are using our data tables with the new state of the art cell navigation. On data tables which utilize row selection (e.g. multiple) the row selection key combinations are not yet working quite right. This is the observation when we activated cell navigation with row selection (multiple).

working:
SPACE: clear selection and select current row (it should set also the selection range start, but its unknown if ths works)

not working:
CTRL-SPACE: it should toggle selection status of current row (between selected/unselected), but it just clears the selected rows
SHIFT-SPACE: it should clear the selection and select all rows between selection range start (set by SPACE) and current row, but it just selects the row under cursor

Mouse functionality is not affected and is fully working.

![image](https://github.com/primefaces/primefaces/assets/102955224/06bb8c35-7c55-4607-ad10-5d556892b7d3)

### Reproducer

I can distill a reproducer out of our application if required. Maybe the effect is visible on the row selection data table demo.

### Expected behavior

Presumable in our investigation the legacy keyboard handler of the data table is active when cell navigation is activated as well, which is no longer required. So, maybe this legacy keyboard handler can be deactivated with active cell navigation and the row selection key combinations can integrate with cell navigation key handlers.

However, the expected behaviour  of the row selection key combination is:

SPACE: clear selection and select row under cursor and set row selection range start
CTRL-SPACE: toggle selection status of current row
SHIFT-SPACE: clear selection, select all rows between and including the row selection range start and the row under cursor

We need to consider also, that when the cursor is on a row expansion trigger (<p:rowToggler/>), then SPACE should expand the row (should override row selection keys).

![image](https://github.com/primefaces/primefaces/assets/102955224/6122637f-12d9-47b4-bf0a-dacbf888cdbc)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

21

### Browser(s)

Chrome Version 126.0.6478.127 (Offizieller Build) (64-Bit), Microsoft Edge Version 126.0.2592.68 (Offizielles Build) (64-Bit)

**Comment by melloware** [comment]
I marked this an enhancement only because I intentionally disabled cell navigation for row selection only because row selection has its own keyboard handling as you have seen.  Not sure how easy it will be to make them both play nicely!

**Comment by Rene-Stoeckel** [comment]
Yes, I see, it takes some more experiments to come up with a solution concept. CellNavigation should use onRowClick() as well, but there should only be one master of selection, depending on the cfg.cellNavigation setting. There is also a risk to break the checkbox selection.

**Comment by melloware** [comment]
Yeah Checkbox Selection, Radio Selection, and Row Selection all have handling.

**Comment by melloware** [comment]
@Rene-Stoeckel you were right this was not so bad. Tested all your scenarios and everything is working as expected.

**Comment by Rene-Stoeckel** [comment]
I have tested this with V14.0.3. It's working nicely. Excellent! Thank you very very much!

**Comment by melloware** [comment]
Great to hear!
