### ISSUE TITLE
Fileupload: Advanced + drag&drop will resend binary on every ajax in form when form has enctype="multipart/form-data"

### ISSUE THREAD

**Issue by YexeY** [primefaces/primefaces#12207]
### Describe the bug

Hallo, and thank you for your time. 

With the fix to drag and drop for advanced file upload we started to experience another problem. 
After having uploaded multiple files and then doing sth else, the site would crash/stop  or at the very least be extremely slow. 

After investigating i noticed that on every ajax call (example: on a datatable cell edit in an datatable in the same form), the binary of the fileupload_input would be send again to the server (at once). 

As a wokaroung we added partialsubmit and process="@this ..." to most ajax calls. 
After a few days i sat down an looked at the issue a bit more and noticed that the problem occures only when using drag and drop. 

My Fileupload component: 

```xml
 <p:fileUpload
                                            id="manualFileUpload"
                                            styleClass="upload-field w-11 mb-4"
                                            widgetVar="fileUploadWidget"
                                            mode="advanced"
                                            auto="true"
                                            dragDropSupport="true"
                                            multiple="true"
                                            label=""
                                            chooseIcon="pi pi-upload"
                                            maxChunkSize="#{uploadService.maxChunkSize}"
                                            accept="#{uploadService.allowedContentTypesString}"
                                            validateContentType="true"
                                            virusScan="true"
                                            disabled="#{backingBean.isUploadDisabled()}"
                                            listener="#{backingBean.uploadListener}"
                                            update=":messages, manualUploadButton, table">
                                        <p:validateFile sizeLimit="#{uploadService.maxFileSizeInBytes}"
                                                        fileLimit="#{uploadService.maxFilesPerUpload}"
                                                        allowTypes="#{uploadService.allowedFileExtensionsRegex}"
                                        />
                                        <f:validator binding="#{myValidator}"/>
</p:fileUpload>
```

I assume this issue hat to do with:
Fix https://github.com/primefaces/primefaces/issues/11879: 14.0.1 FileUpload (advanced): DragAndDrop not working, javascript error by @melloware in **https://github.com/primefaces/primefaces/pull/11905**

### Reproducer

1. Upload mutliple files via drag and drop
2. Trigger ajax call (example selectOneMenu, Button, CellEdit, Pagination)
3. Ajax will send file manualFileUpload_input; (Binary) again

### Expected behavior

That the binary does not get send again. That is also how it works when using upload via fileselector. 

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

Mojarra

### JSF version

4.1

### Java version

18

**Comment by melloware** [comment]
@christophs78 i think it is because now the value `dataFileInput = $('#' + $.escapeSelector(data.paramName + '_input'));` must be cleared or destroyed after the AJAX is successfully sent?

**Comment by christophs78** [comment]
I´ll try to debug this during weekend. Have to debug both code paths to understand this in-depth and their differences. (classic upload vs drag´n´drop)
Basically the idea of cleanup after upload sounds proper.

**Comment by christophs78** [comment]
@YexeY Can´t reproduce this with 15.0.0-SNAPSHOT.

XHTML
```xhtml
<h:form>
	<p:outputPanel>
		#{fileUploadView.now()}
	</p:outputPanel>

	<p:fileUpload listener="#{fileUploadView.handleFileUpload}" mode="advanced" dragDropSupport="true"
				  update="messages @this" auto="true">
		<p:validateFile sizeLimit="100000" allowTypes="/(\.|\/)(gif|jpeg|jpg|png)$/" />
	</p:fileUpload>

	<p:growl id="messages" showDetail="true"/>

	<p:inputText value="#{fileUploadView.someInput}" />

	<p:commandButton value="update form" update="@form" process="@form" action="#{fileUploadView.showSomeMessage()}" />
</h:form>
```

Short video-recording:
https://github.com/primefaces/primefaces/assets/10461942/d80462dc-aeeb-4fcd-83e8-0ae3ad1ba99d

Can you please provide a bare minimum reproducer based on 15.0.0-SNAPSHOT using https://github.com/primefaces/primefaces-test?

**Comment by YexeY** [comment]
Thank you for your time!

May i ask which browser you used for testing?

**Comment by melloware** [comment]
i would assume latest Chrome and Firefox @YexeY

**Comment by YexeY** [comment]
Hello, you not being able to reproduce the bug made me curious. 
so I decided to investigate my code further. I iteratively removed parts of it until the bug no longer appeared, focusing on the parts where your and my code diverged. 

Although this is not a complete reproducer, it represents the minimal page where the error still occurs:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h:head>
    </h:head>
    <h:body>
        <h:form enctype="multipart/form-data">
            <p:fileUpload
                    mode="advanced"
                    auto="true"
                    dragDropSupport="true"
                    multiple="true"
                    listener="#{settlementDocumentsManualUpload.uploadListener}"
                    update="button list">
            </p:fileUpload>
            <p:dataList id="list" value="#{settlementDocumentsManualUpload.dataUploadList}" var="file" >
                <h:outputText value="#{file.name}"></h:outputText>
            </p:dataList>
            <p:commandButton id="button"
                             ajax="true"
                             process="@form"/>
        </h:form>
    </h:body>
</f:view>
</html>

```

Interestingly, if I either remove the enctype="multipart/form-data" attribute or adjust the update attribute from update="button list" to update="button list @this" or update="@form", the bug ceases to occur.

I hope to find time in the coming weeks to provide a full reproducer for you.

**Comment by YexeY** [comment]
Now, as i know that updating the fileupload itself fixed the bug...
i have a prod to fix!

**Comment by christophs78** [comment]
I´m able to confirm adding enctype="multipart/form-data" to h:form (together with drag&drop) triggers this issue.
Is there a good reason to use this enctype?

**Comment by melloware** [comment]
Yes @YexeY that encType is for SimpleMode.  All of our Advanced Examples don't use it: https://www.primefaces.org/showcase/ui/file/upload/dnd.xhtml

**Comment by tandraschko** [comment]
IMO it should still work correctly

**Comment by melloware** [comment]
Ok reopened.
