### ISSUE TITLE
Tree always visits every node with wrong context

### ISSUE THREAD

**Issue by bodabela** [primefaces/primefaces#1220]
You may consider this patch to provide the proper node type implementation.

I had a problem in case of the rendered attribute relayed on an attribute that was present only in the data bean for the specific node type:

```
<p:treeNode id="model-tree-#{node.id}" type="component">
    <h:outputText value="#{node.name}" />
    <h:outputText value=" - ##{node.id}" rendered="#{node.id!=null}" />
    <h:inputHidden value="#{node.id}" rendered="#{node.id!=null}" />
</p:treeNode>
<p:treeNode type="componentAttribute">
    <h:outputText value="#{node.name} : #{node.value}" />
</p:treeNode>

```

[0001-nodeType-support-for-treeNode.zip](https://github.com/primefaces/primefaces/files/166010/0001-nodeType-support-for-treeNode.zip)

Cheers

**Comment by bodabela** [comment]
Of corse the problematic attribute is the "id" in this case. The componentAttribute data bean has no "id" attribute.

**Comment by cagataycivici** [comment]
Send a pull request please instead of a zip.

**Comment by tandraschko** [comment]
I can't see how your PR is related to fix this issue.
Please provide more descirption and a complete example (xhtml + bean).

**Comment by bodabela** [comment]
It is not visiting the  child tree unless it has the matching nodeType.
If you visit a certain node content that has an EL content that is not matching the actual bean instance (e.g. has no attribute) you find the EL expression fail.
