### ISSUE TITLE
PropertyNotWritableException: Illegal set operation issue

### ISSUE THREAD

**Issue by chandru-kumar** [primefaces/primefaces#12206]
### Describe the bug

Evaluating expression in value attribute throws PropertyNotWritableException: Illegal set operation issue.

Code: 
`<p:inputText id="colId42"  value="#{dataBean.changeBy == EnumValues.NEUTRAL) ? '' : dataBean.changeBy}">
<p:ajax event="change" process="@this" update="colId42"/>
</p:inputText>`

It works fine without any evaluations:

`<p:inputText id="colId42"  value="#{dataBean.changeBy}">
<p:ajax event="change" process="@this" update="colId42"/>
</p:inputText>`

### PrimeFaces edition

Community

### PrimeFaces version

13.0.10

### JSF implementation

Mojarra

### JSF version

3.0.5

### Java version

17

**Comment by tandraschko** [comment]
Value binding must be writable, thats by design
