### ISSUE TITLE
DataTable: Row Expansion and expandedRow rendered issue

### ISSUE THREAD

**Issue by JONYR15** [primefaces/primefaces#12214]
### Describe the bug

I am having an issue with a datatable that uses rowExpansion in PrimeFaces. I have configured expandedRow="true" on the datatable, but it fails when it retrieves records that do not have content to display in rowExpansion, as there is not always something to show.

### Reproducer
[primefaces-test-master-row-expansion.zip](https://github.com/user-attachments/files/16033522/primefaces-test-master-row-expansion.zip)

  - Change expandedRow:
    - If it is true: it causes an exception.
    - If it is false: it works correctly, except that rowExpansion does not expand unless I remove the rendered attribute.
    - In previous versions of PrimeFaces, this worked correctly.

```html
<p:dataTable value="#{testView.list}"
             var="testLine"
             rowKey="#{testLine.id}"
             expandedRow="true"
             lazy="false">
    <f:facet name="header">
        Expand rows to see detailed information
    </f:facet>
    <p:column style="width:2rem" ariaHeaderText="Row Toggler">
        <p:rowToggler rendered="#{testLine.testChild.size() > 0}"/>
    </p:column>

    <p:column headerText="Name">
        <h:outputText value="#{testLine.name}"/>
    </p:column>

    <p:column headerText="Artist">
        <h:outputText value="#{testLine.artist}"/>
    </p:column>

    <p:column headerText="Released">
        <h:outputText value="#{testLine.released}"/>
    </p:column>

    <p:rowExpansion rendered="#{testLine.testChild.size() > 0}">
        <h2>Data Expanded</h2>
        <p:dataTable value="#{testLine.testChild}" var="testChildLine" rowKey="#{testChildLine.id}" lazy="false">
            <p:column headerText="Name">
                <h:outputText value="#{testChildLine.name}"/>
            </p:column>

            <p:column headerText="Artist">
                <h:outputText value="#{testChildLine.artist}"/>
            </p:column>

            <p:column headerText="Released">
                <h:outputText value="#{testChildLine.released}"/>
            </p:column>
        </p:dataTable>
    </p:rowExpansion>
</p:dataTable>

```

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### Theme

Freya

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

**Comment by melloware** [comment]
Thanks I attached your reproducer zip as well.

**Comment by JONYR15** [comment]
[primefaces-test-master-row-expansion.zip](https://github.com/user-attachments/files/16033657/primefaces-test-master-row-expansion.zip)
