### ISSUE TITLE
DataTable: column width autoAdjust feature should ignore expanded Rows

### ISSUE THREAD

**Issue by Rene-Stoeckel** [primefaces/primefaces#12222]
### Description

Currently cell navigation is not active together with row expansion, but In order to provide a more general support for the cellNavigation in the dataTable in long term the feature #11918 should ignore expanded rows. 

Currently it would consider the width of the expanded rows (class= ui-expanded-row-content) in the selector cellsInSameColumn in autosizeColumnWidth() so that the new calculated width is not as expected when there are tables under the expanded rows.

![image](https://github.com/primefaces/primefaces/assets/102955224/ff1a69cd-3a0b-4fbc-be2b-fcd1c9c8e38c)

### Describe the solution you would like

autosizeColumnWidth() should ignore expanded row content rows when calculating the new column width for column width auto adjustment.

**Comment by melloware** [comment]
I think this slight fix will do it.

```js
var cellsInSameColumn = this.tbody.find("tr:not(.ui-expanded-row-content) td:nth-child(" + (columnIndex + 1) + ")");
```

**Comment by Rene-Stoeckel** [comment]
I tried the seelctor, and it seems not to wotk. I assume it selects also the "not expanded rows" of tables in the expansion content.  I had more luck with tr as direct childs of tbody. note the ">":

`var cellsInSameColumn = this.tbody.find("> tr:not(.ui-expanded-row-content) td:nth-child(" + (columnIndex + 1) + ")");`

**Comment by Rene-Stoeckel** [comment]
Works with commit 6432d/41f12.
