### ISSUE TITLE
ConfirmDialog: not showing

### ISSUE THREAD

**Issue by Raffine64** [primefaces/primefaces#12227]
### Describe the bug

confirm dialog doesn't show up anymore, in the console:

No global confirmation dialog available.

Same issue when copying the simple example from the showcase.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by Raffine64** [comment]
I also have those in the console logs:

jquery.js.xhtml?ln=primefaces&v=14.0.1&e=14.0.1:2  jQuery.Deferred exception: Cannot read properties of undefined (reading 'close') TypeError: Cannot read properties of undefined (reading 'close')
    at Object.getAriaLabel (
...
jquery.js.xhtml?ln=primefaces&v=14.0.1&e=14.0.1:2  Uncaught TypeError: Cannot read properties of undefined (reading 'close')


It seems to work with a simpler page though.

**Comment by Raffine64** [comment]
debugging it further, it seems to be caused by our calendar_locale.js, when I remove it, it works.

**Comment by melloware** [comment]
@Raffine64 it works fine: https://www.primefaces.org/showcase/ui/overlay/confirmDialog.xhtml?jfwid=5e4f5

Yeah you are missing Locale labels see the complete locales in PF14 here: https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales

All the locales are much more complete and more languages supported.

**Comment by Raffine64** [comment]
many thanks for the quick answer !
