### ISSUE TITLE
DataTable: improvement autosizeColumnWidth for data tables with attribute scrollable=true

### ISSUE THREAD

**Issue by Rene-Stoeckel** [primefaces/primefaces#12226]
### Description

When the scrollable=true option is used on data tables, for some reason the data table is split into two tables. One with the header cells and one with data cells. When ALT-W on such a table is used then only the header cell of the column (first table) gets adjusted, but not the data cells (in second table). 
![image](https://github.com/primefaces/primefaces/assets/102955224/fc0f71b3-754c-4a91-932d-b6eefe70998f)

### Describe the solution you would like

The feature #11918 should adjust all cells in the datatable(s) also when the data table attribute scrollable=true, not only the header cell. It's probably something for version 14.0.3 to avoid delays on 14.0.2?

**Comment by melloware** [comment]
i will look.  Yeah the scrollable table is actually two different tables.

**Comment by Rene-Stoeckel** [comment]
Tested in 14.0.3-SNAPSHOT. Works great!
