### ISSUE TITLE
SelectBooleanCheckbox and SelectManyButton throw JS error in IE 11

### ISSUE THREAD

**Issue by jirkis** [primefaces/primefaces#1222]
Hello,

when accessing [showcase page](http://www.primefaces.org/showcase/ui/input/booleanCheckbox.xhtml) of SelectBooleanCheckbox in IE 11,
there is an error in JS console stating that **isLtIE property or function cannot be found**.
Line of code affected looks like this:
**PrimeFaces.env.browser.msie&&PrimeFaces.isLtIE(9)**
Probable fix could look like this:
**PrimeFaces.env.browser.msie&&PrimeFaces.env.isLtIE(9)**

Thanks for fixing this.

**Comment by mertsincan** [comment]
Thanks for your fix. :+1:
