### ISSUE TITLE
Incorrect html transformation according to WAI

### ISSUE THREAD

**Issue by WAIcare** [primefaces/primefaces#1223]
Used Release: Primefaces 5.3. Community

1) `<p:selectBooleanCheckbox ...>` generates `<input type="checkbox" autocomplete="off" ...>`
WAI Error: Attribute autocomplete is only allowed when the input type is color, date, datetime, datetime-local, email, month, number, password, range, search, tel, text, time, url, or week.
Note: the same states for inputs of type="hidden"

2) `<p:selectManyCheckbox ...>` generates `<div ...><div ...><div ...><td>...</td> ...`
but no table or tr is opened for the usage of td!
(compare to `<h:selectManyCheckbox>` which generates`<table ...><tr><td>...</td>...)`
WAI Error 1: Stray start tag td
WAI Error 2: Stray end tag td.

3) The "rowsPerPageTemplate" attribute in `<p:dataTable>` generates a `<select ...>` with the attribute autocomplete="off".
WAI Error:  Attribute autocomplete not allowed on element select at this point.

4) The "rowsPerPageTemplate" attribute in `<p:dataTable>` generates one element in the header and one element in the footer with the respective dropdown list of visible rows. However, both dropdown lists hold the exact same ID.
WAI Error:  Duplicate ID `j_idt15:<tablename>_rppDD.`

**Comment by cagataycivici** [comment]
Number is fixed at #972

We need to keep autocomplete on hidden elements as it causes issues on firefox when page is refreshed as it keeps old values like datatable selection.

**Comment by mertsincan** [comment]
I tested with Firefox after removing autocomplete attribute of select tag and input tag. This change has caused some bug. Therefore, I removed autocomplete="off" fixes. 

Only the 4. issue is fixed for 5.3.9 and 6.0.

**Comment by cagataycivici** [comment]
Yes, removing autocomplete="off" breaks a lot of things in firefox, tests fail so that part is reverted.
