### ISSUE TITLE
Galleria: cannot constrain height

### ISSUE THREAD

**Issue by samdonato** [primefaces/primefaces#12239]
### Describe the bug

Using the Galleria component, I cannot constrain the viewport based on height. If I am using only square or landscape images, it works ok, but if I add a portrait (tall) image, it makes the entire galleria the height of the tall image leaving whitespace around the other images and stretching the galleria. Looking at the demo, the galleria has the style="max-width: 640px;" to constrain the width, but if you add "max-**height**: 640px;", or height:500px;, it seems to break the galleria and displays it as if it were absolutely positioned. 

### Reproducer

The last graphicImage is tall. Comment the last image out to see normal behavior and then enable it to see a tall image mixed in.
```
<p:galleria style="max-width: 640px; " showIndicators="true">
	<p:graphicImage style="width: 100%; display: block"
		value="https://www.primefaces.org/showcase/javax.faces.resource/demo/images/galleria/galleria9.jpg.xhtml" />
	<p:graphicImage style="width: 100%; display: block"
		value="https://www.primefaces.org/showcase/javax.faces.resource/demo/images/galleria/galleria10.jpg.xhtml" />
	<p:graphicImage style="width: 100%; display: block"
		value="https://www.primefaces.org/showcase/javax.faces.resource/demo/images/galleria/galleria8.jpg.xhtml" />
	<p:graphicImage style="width: 100%; display: block"
		value="https://www.primefaces.org/showcase/javax.faces.resource/images/nature/nature4.jpg.xhtml?ln=demo" />
	<p:graphicImage style="width: 100%; display: block"
		value="https://cdn.pixabay.com/photo/2023/05/02/14/15/british-shorthair-7965411_1280.jpg" />
</p:galleria>
```

### Expected behavior

The galleria should be able to constrain based on height and width. If an image is tall, it should limit the height. If the image is wide, we should limit the width. This way, we can allow different sized uploads and trust the galleria won't go past where we set it.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

Poseidon

### JSF implementation

All

### JSF version

3.0.1

### Java version

17

### Browser(s)

chrome 125.0.6422.142 (Official Build) (arm64)

**Comment by samdonato** [comment]
[primefaces-test-master.zip](https://github.com/user-attachments/files/16085590/primefaces-test-master.zip)

just run text.xhtml. There are three test cases on that one page. 1) all images are wide 2) one tall image added 3) specified height to constrain the allowable height.

**Comment by melloware** [comment]
thanks that will help.

**Comment by melloware** [comment]
Try this one:
[pf-12239.zip](https://github.com/user-attachments/files/16088341/pf-12239.zip)

you need to set the scale of your images and not the container.

**Comment by samdonato** [comment]
Thank you. I'm not sure if you noticed, but the wide images are stretched and the tall images are squashed. It's due to the fixed height:640px and variable width of 100%. If you remove the width:100%, the images don't show in the viewport any longer. Take a look at the updated reproducer and run "sized-image.xhtml"
[stretched_images.zip](https://github.com/user-attachments/files/16089137/stretched_images.zip)

**Comment by melloware** [comment]
yes that is the only way to solve it.  The Galleria can't size your tall images with scaling you have to scale each image manually.  I just set them all to 640px to show you.

**Comment by melloware** [comment]
you can also do this to force a size

```css
body .ui-galleria-item-container {
  height: 640px !important;
}
```

but that won't scale your tall image it will simply cut it off but give you a symmetric size

**Comment by melloware** [comment]
and instead of CSS styles you can use the `height` and `width` properties on the graphic image.

https://primefaces.github.io/primefaces/vdldoc/p/graphicImage.html#height

https://primefaces.github.io/primefaces/vdldoc/p/graphicImage.html#width

**Comment by samdonato** [comment]
Thank you Melloware. I'm going to have users uploading photos from their phone so they are probably going to be 9:16 and 16:9. The images are going to have very different aspect ratios. I tried really hard to get it working, but I don't think this component is going to be a good fit. Thank you for your help.
