### ISSUE TITLE
Core: jQuery animation scrollTop not working on PF14

### ISSUE THREAD

**Issue by SimonePadovan** [primefaces/primefaces#12233]
### Describe the bug

With PF 14.0.2 scrolltop doesn't work anymore. It works ok with PF 14.0.0.

`PrimeFaces.current().executeScript("$('html, body').animate({ scrollTop: 0 }, 'fast')");`

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

**Comment by jepsar** [comment]
Do you have any errors in the console log in the browser?

**Comment by melloware** [comment]
`"$('html, body').animate({ scrollTop: 0 }, 'fast')"` is not a PrimeFaces function that is a jQuery function?

I also just tested it here on 14.0.2: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/crud.xhtml?jfwid=d89c2

Scroll to the bottom of the page hit F12 and run `$('html, body').animate({ scrollTop: 0 }, 'fast');` it works fine.

I have a feeling you have your OS set to no animations. See this fix in PF14 for accessibility if the OS says no animations then PF respects it and all animations are disabled.

https://github.com/primefaces/primefaces/issues/11130

**Comment by SimonePadovan** [comment]
i'll investigate the problem better
