### ISSUE TITLE
DatePicker: LocalDateTime conversion error when used inside ui:repeat

### ISSUE THREAD

**Issue by martingLab** [primefaces/primefaces#12234]
### Describe the bug

When p:datePicker is used for LocalDateTime and is placed inside ui:repeat, then a strange conversion error is raised. This does not happen for LocalDate and LocalTime.

### Reproducer

Here's the code to reproduce:

**xhtml:**

```xml
 <h:form>
                 <p:messages closable="true"/>  <br/>
                 <ui:repeat value="#{datePickerBacking.testStrList}" var="rep" >
                     <h:panelGroup id="pgDateTime" >
                         <p:outputLabel value="#{rep}" for="dateTimeField" class="Fs12" style="padding-left: 5px;"/> <br/>
                         <p:datePicker id="dateTimeField" value="#{datePickerBacking.dateTime}" />
                         <p:commandButton value="search" actionListener="#{datePickerBacking.doSomething()}" process="`@form`" update="`@form`" /> <br/>
                     </h:panelGroup>
                 </ui:repeat>
             </h:form>
```

**Backing bean:**

```java
 @ViewScoped
 @Named
 public class DatePickerBacking implements Serializable {
     private List<String> testStrList;
     private LocalDateTime dateTime;
     
     public DatePickerBacking() {
         testStrList = List.of("TestLabel 1", "TestLabel 2");
     }
     
     public void doSomething(){
         // do something
     }
 
     public LocalDateTime getDateTime() {
         return dateTime;
     }
 
     public void setDateTime(LocalDateTime dateTime) {
         this.dateTime = dateTime;
     }
 
     public List<String> getTestStrList() {
         return testStrList;
     }
 
     public void setTestStrList(List<String> testStrList) {
         this.testStrList = testStrList;
     }
```

**Steps to trigger error:**
1. Select date and time in one of the two input fields
2. Click 'search' button

### PrimeFaces edition

Community

### PrimeFaces version

13.0.10

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
Might be a Mojarra bug.

`mvn clean jetty:run -Pmojarra23` FAILS

`mvn clean jetty:run -Pmyfaces23` WORKS

**Comment by melloware** [comment]
Actually it doesn't Myfaces doesn't throw an error but sets all dates to NOW.

**Comment by melloware** [comment]
Actually no it does work in MyFaces. It looks like its setting the second value only because you are using the same variable for both dates.  Definitely looks like a Mojarra issue.

Reproducer:
[pf-12234.zip](https://github.com/user-attachments/files/16072052/pf-12234.zip)

**Comment by martingLab** [comment]
I tested it with Mojarra and without Primefaces, so I replaced datePicker with:

> <h:inputText value="#{testDateTimeBacking.dateTimeValues[repStatus.index]}" >
                                <f:convertDateTime type="localDateTime" pattern="dd.MM.yyyy HH:mm" />
                            </h:inputText>

It works. I assume it's a Primefaces bug. When looking at the error message you see that it's a conversion error when trying to convert to Date. This does not happen in plain Faces / Mojarra as you define the data type via the `type="localDateTime"` attribute of `f:convertDateTime`. Primefaces apparently does not recognize that a LocalDateTime object is used - and you cannot explicitly define the data type in p:datePicker.

As a workaround I now defined a custom converter and assigned it to `p:datePicker` via the `converter` attribute - that works.

**Comment by melloware** [comment]
That is a good workaround but its strange that it works fine in MyFaces. So it might be related to the `ui:repeat` ?

**Comment by martingLab** [comment]
Yes agree, strange that it works in MyFaces. But on the other hand it works in plain Faces / Mojarra within `ui:repeat`. So it's hard to raise an issue at the Mojarra project.
I think it must have something to do with the logic to implicitly identify the relevant DateTime data type in Primefaces / p:datePicker.

**Comment by melloware** [comment]
OK debugged it.  You could also have fixed it by setting `showTime="true"` on the DatePicker.  I am submitting a PR.

**Comment by tandraschko** [comment]
did you try to debug, why are value type recognition is not working?

**Comment by melloware** [comment]
Yes I debugged and the issue is here:

```java
protected Temporal convertToJava8DateTimeAPI(FacesContext context, UICalendar calendar, Class<?> type, String submittedValue) {
        if (type == LocalDate.class || type == YearMonth.class || (type == LocalDateTime.class && !calendar.hasTime())) {
```

the value of `calendar.hasTime()` is `false` inside the Mojarra UI Repeat . Has Time for DatePicker is actually this.

```java
@Override
    public boolean hasTime() {
        return this.isShowTime() || this.isTimeOnly();
    }
```

The value of `this.isShowTime()` is false when it should be true.

So for @martingLab that is why i said if on his DatePicker he set `showTime="true"` it would work as the value would always evlaute to true.

But in our DatePicker we try and dynamically determine if `showTime="true"`

```java
 if (datePicker.isShowTimeWithoutDefault() == null) {
            Class<?> type = datePicker.getValueType();

            if (type != null) {
                datePicker.setShowTime(LocalDateTime.class.isAssignableFrom(type));
            }
            else {
                datePicker.setShowTime(CalendarUtils.hasTime(pattern));
            }
        }
```

That is done on the EncodeEnd. But for some reason in the `ui:repeat` of mojarra this value of showtime is still `false` even though it was set in EncodeEnd. 

So the fix was to just also check this code in `decode` to make sure the values are set correctly upon decode.
