### ISSUE TITLE
Autoupdate on growl doesn't work anymore

### ISSUE THREAD

**Issue by AlessandroBori** [primefaces/primefaces#12247]
### Describe the bug

Discussion: https://github.com/orgs/primefaces/discussions/2253

After upgrading from 12.0.5 to 14.0.2, following guidelines, if on a page the view has attached an event (like postaddtoview or prerendercomponent, it's the same) with a listener, autoupdating on growl messages works fine on the first ajax call then stops.

It worked until PF 14.0.0 RC1 version

### Reproducer

In this reproducer just keep clicking test button

[primefaces-test-master.zip](https://github.com/user-attachments/files/16098786/primefaces-test-master.zip)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

11

**Comment by melloware** [comment]
@tandraschko i have confirmed this issue and the only change I see is this one: https://github.com/primefaces/primefaces/issues/11408

**Comment by tandraschko** [comment]
in general i dont if our PF impl is 100% correct
however, its weird that mojarra is working in general, it just breaks when you add
`<f:event type="preRenderComponent" listener="#{testView.onEventPostAddToView}" />`

i think therfore its a mojarra bug as its working fine in myfaces

**Comment by AlessandroBori** [comment]
just for clarification
it breaks even if  the event is <f:event type="postAddToView" listener="#{testView.onEventPostAddToView}" />
I don't understand why this change [#11408](https://github.com/primefaces/primefaces/issues/11408) could be so defective
btw i was using mojarra 2.3.21 on previous version of PF

**Comment by tandraschko** [comment]
at least your code breaks mojarra, myfaces works
you should change your code or create a issue at mojarra

**Comment by AlessandroBori** [comment]
testView.onEventPostAddToView has no code on purpose, just the existence of this line 
`<f:event type="preRenderComponent" listener="#{testView.onEventPostAddToView}" />`
makes a mess
 i'll dig more

**Comment by tandraschko** [comment]
as i said, dont attach those f:event to f:view, its not correct

put it into a real rendered component
will close it for now
