### ISSUE TITLE
Primefaces 11 with Embedded Tomcat in Springboot application

### ISSUE THREAD

**Issue by pradipt1505** [primefaces/primefaces#12243]
Hi Team,

We are trying to run primefaces (jakarta) 11 with Embedded tomcat in Springboot application. We are able to start the application but the servlet is not getting registered due to which our page is not loading properly. Can you please guide us on how to configure the application correctly with Embedded tomcat?

Thanks,
Pradipt

**Comment by melloware** [comment]
This is not a forum its a bugtracker.  Please ask your question here: https://github.com/orgs/primefaces/discussions/categories/primefaces

But really what you want is JoinFaces if you are using Spring Boot: https://github.com/joinfaces/joinfaces
