### ISSUE TITLE
CommandButton: Resetting Inputs is broken for resetValues="true"

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12241]
### Discussed in https://github.com/orgs/primefaces/discussions/2200

<div type='discussions-op-text'>

<sup>Originally posted by **hangrybear666** June 25, 2024</sup>
In my entire Application, `resetValues="true"` Flags on `<p:commandButton/>` Elements have no effect since upgrading from PrimeFaces 10. 
I have to manually call `PrimeFaces.current().resetInputs(resetInputId);` in my models and pass the IDs I want to update to the model as well to achieve the desired result.

The `resetValues` Flag in the following code has no effect:
```
<p:commandButton global="false" class="generic-btn-cancel"
        value="#{commonRes.common_cancel}" icon="pi pi-undo"
        actionListener="#{exampleModel.cancelEditOrInsert}"
        update="resetInputId"
        immediate="true" resetValues="true"/>
```

@tandraschko I've created a primefaces-test project that is self-explanatory.

**MP4 Screen Capture displaying workflow:**
https://github.com/primefaces/community/assets/85507965/a8045e9c-3993-4a89-9fab-da53c5fb9ab4

**Reproducer Primfaces v14 Test Archive**
[primefaces-test-commandbutton-resetValues.zip](https://github.com/user-attachments/files/16071343/primefaces-test-commandbutton-resetValues.zip)

P.S. ignore the src\main\webapp\effectiveDataTable.xhtml file, it's for another test project I'm making</div>

**Comment by melloware** [comment]
@tandraschko confirmed this works in PF 13.0.10 but not in 14.0.X

**Comment by tandraschko** [comment]
it seems that our old resetValues was implemented different as JSF internal UIViewRoot#resetValues

i just debugged MF 2.3-next and it seems that ResetValuesCallback#visit should be called for each child component of the form but it isnt.

Can you debug Mojarra?

i just dont have enough time to work on that stuff, have to much customers right now.

**Comment by melloware** [comment]
Mojarra just does this...

```java
public void resetValues(FacesContext context, Collection<String> clientIds) {
        visitTree(VisitContext.createVisitContext(context, clientIds, null), new DoResetValues());
    }

    private static class DoResetValues implements VisitCallback {
        @Override
        public VisitResult visit(VisitContext context, UIComponent target) {
            if (target instanceof EditableValueHolder) {
                ((EditableValueHolder) target).resetValue();
            }
            return VisitResult.ACCEPT;
        }
    }
```

Looks like its also not recursively visiting children like our old implementation was.

**Comment by tandraschko** [comment]
but shouldnt visitTree with VisitResult.Accept visit all children?

**Comment by melloware** [comment]
I mean i put a breakpoint on it and the first element in the component is `HtmlForm`. It evaluates its not an InputHolder so it doesn't call resetValues and that's it.  Not recursive as far as the debugger is showing me.

**Comment by melloware** [comment]
If I change the `update` from

`update="frmTest"

to 

`update="frmTest itStoreManagerCommission"`

then it finds the InputNumber `itStoreManagerCommission` and resets it.

**Comment by melloware** [comment]
Not sure what the JSF spec says about this but should I open a Faces ticket asking?

**Comment by melloware** [comment]
Oh I found your ticket: https://github.com/jakartaee/faces/issues/1883  not sure if its related.

**Comment by tandraschko** [comment]
No
VisitTree is built to loop through children actually, not sure why its not working there

**Comment by melloware** [comment]
Want me to open Mojarra or MyFaces tickets?   Put our old logic back for 14.0.3 until this is resolved?

**Comment by tandraschko** [comment]
please create a spec issue first, both are the same basically:

```
    public void resetValues(FacesContext context, java.util.Collection<java.lang.String> clientIds)    
    {
        VisitContext visitContext = VisitContext.createVisitContext(context, clientIds, null);
        this.visitTree(visitContext, new VisitCallback {
                @Override
                public VisitResult visit(VisitContext context, UIComponent target)
                {
                    if (target instanceof EditableValueHolder)
                    {
                        ((EditableValueHolder)target).resetValue();
                    }
                    return VisitResult.ACCEPT;
                }
            }
    }
```

`resetValues(context, Arrays.asList("form"))` must actually reset all child inputs
we have to clarify that

**Comment by melloware** [comment]
Faces Spec Issue: https://github.com/jakartaee/faces/issues/1936
