### ISSUE TITLE
shop icon is not showing

### ISSUE THREAD

**Issue by AlperGuven** [primefaces/primefaces#12258]
### Describe the bug

When I want to use pi-shop even though it appears among the icons, the html renders empty space. I think there is a problem with pi-shop. Need a fix for this for everyone.

### Expected behavior

<i class="pi pi-shop" /> usage should be render as a shop icon as defined primevue icons page

### PrimeFaces edition

Community

### PrimeFaces version

7.0.0

### Theme

soho-light

### JSF implementation

Mojarra

### JSF version

-

### Java version

-

**Comment by tandraschko** [comment]
this is primefaces, not primevue.

**Comment by AlperGuven** [comment]
sorry my bad, have a good day
