### ISSUE TITLE
AutoComplete in DataTable filter style issue

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#12257]
### Describe the bug

If I´m using p:autoComplete in p:datatable (resizableColumns="false") I´m getting this issue:

<img width="1375" alt="image" src="https://github.com/primefaces/primefaces/assets/9787533/69a05b58-0240-4365-aa95-b4905d70f5b8">

```xml
<f:facet name="filter">
            <p:autoComplete placeholder="Suche..."
                  onchange="PF('jobSharingApplicationTable').filter()"
                  onkeyup="PF('jobSharingApplicationTable').filter()"
                 dropdown="true" var="jobSharingPartner"
                  itemLabel="#{jobSharingPartner.jobSharingCompanyPartner.name}"
                 itemValue="#{jobSharingPartner.jobSharingCompanyPartner.name}"
                 lazyModel="#{jobSharingPartnerRequestNotLazyForAutocompleteController.lazyModel}"
                lazyField="jobSharingCompanyPartner.name"
                forceSelection="true" maxResults="10">
           </p:autoComplete>
```

and with resizableColumns="true" it´s like this:
<img width="711" alt="image" src="https://github.com/primefaces/primefaces/assets/9787533/b886168e-a379-4aac-a72c-f4402b96d538">

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### Theme

Rain

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment]
reproducer plz
