### ISSUE TITLE
Core: Minify XML files in JAR

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12264]
Currently our Taglib.xml is quite large and should be whitespace minified in the JAR file.

**Comment by tandraschko** [comment]
What does it safe?

**Comment by melloware** [comment]
Before:
faces-config.xml 87 KB
primefaces.taglib.xml 1,352 KB

After:
faces-config.xml 79 KB
primefaces.taglib.xml 979 KB

**Comment by fcorneli** [comment]
```
-rw-r--r--   1 fcorneli  staff   4,9M 18 mei 16:05 primefaces-15.0.0-SNAPSHOT.jar
```
:rofl:
