### ISSUE TITLE
Datatable empty message issue

### ISSUE THREAD

**Issue by bjorntj** [primefaces/primefaces#1226]
The emptyMessage is prefixed with the name of header of the first column when the table is empty.
Switching to PF v5.3.7 removes the prefix and displays the emptyMessage as expected.

**Comment by mertsincan** [comment]
I couldn't replicate this issue. Can you please attach a screenshot and sample code for us to replicate?

My test code;

```
<p:dataTable var="car" value="#{null}" emptyMessage="TESTTT">
```

**Comment by mertsincan** [comment]
Sample code;

```
<p:dataTable var="car" value="#{null}" reflow="true" ...>
  // p:columns with header Texts
</p:dataTable>
```
