### ISSUE TITLE
PickList: Attribute extension selectionRowMode

### ISSUE THREAD

**Issue by jheidrich-gip** [primefaces/primefaces#12267]
### Description

It would be nice if the selection behaviour of the picklist could be controlled via the selectionRowMode attribute. This should work in the same way as with the tables.

### Describe the solution you would like

The attribute indicates how items of a picklist may be selected, when clicking on the item / li / row itself (not on the checkbox).

Attribute values:

new / default : 
The current behaviour corresponds to the attribute value "New". When clicking on a item, all other items are deselected. 

add:
Retains the currently selected items when a item is clicked.

none:
the item selection is deactivated.

### Additional context

The initial situation is as follows:
We are working with a picklist similar to the advanced example from the showcase. In short: Checkbox and columns in the PickList list. If I make a slightly larger selection in the source via the checkboxes and now accidentally click next to the checkbox to select another element, my entire selection is gone.

The users don't seem to like working with the CTRL multi-selection. Therefore the question whether the picklist could be extended by something similar to the selectionRowMode attribute in the tables.

**Comment by tandraschko** [comment]
providing a PR or sponsoring would be great

**Comment by melloware** [comment]
@jheidrich-gip i have moved your ticket to the Sponsoring Wishlist of Picklist here: https://github.com/primefaces/primefaces/issues/11249
