### ISSUE TITLE
Datatable: Filter + Celleditor -> doesnt work after first edit to cell

### ISSUE THREAD

**Issue by YexeY** [primefaces/primefaces#12274]
### Describe the bug

Here is the reproducer:
[primefaces-reproducer.zip](https://github.com/user-attachments/files/16141429/primefaces-reproducer.zip)

I already made a ticket like this, but when creating a reproducer thought that the error was fixed with 14.0.2. 
But i noticed now, that in my testing, i forgot to remove a update="@form" which made the tests redundant. 

### Reproducer

1. Filter by Code (example: nvklal433)
2. Edit any cell (Name or S3) once
3. Edit the same Cell again

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

4.1

### Java version

18

**Comment by melloware** [comment]
I think its similar or same to this issue: https://github.com/primefaces/primefaces/issues/12262

I see the `update` has the products datatable in it in the AJAX request:

![image](https://github.com/primefaces/primefaces/assets/4399574/ee8511af-db60-4828-85ad-e11ce01e74b3)

However the Response does not contain the table so its not updating and your filtered table is in a weird state.  Only the Messages comes back in the partial update.

```xml
<?xml version='1.0' encoding='utf-8'?>
<partial-response>
	<changes>
		<update id="form:msgs"><![CDATA[<span id="form:msgs"></span><script id="form:msgs_s" type="text/javascript">PrimeFaces.cw("Growl","widget_form_msgs",{id:"form:msgs",sticky:false,life:6000,escape:true,keepAlive:false,msgs:[{summary:"Cell Changed",detail:"Old: Black Watch2, New:Black Watch4",severity:'info'}]});</script>]]></update>
		<update id="form:products2"><![CDATA[Black Watch4]]></update>
		<update id="j_id1:javax.faces.ViewState:0"><![CDATA[-6607234172170725603:-3538837519212455929]]></update>
	</changes>
</partial-response>
``

**Comment by melloware** [comment]
in fact it is the same look at the response:

```xml
<update id="form:products2"><![CDATA[Black Watch4]]></update>
```

What it thinks is Datatable is got my submit value inside the CDATA.

**Comment by YexeY** [comment]
Hello, i wanted to ask what the next steps would be,
as this ticket is quite important to us.

What would be required to get this ticket to be implemented?

As always, thank you for your time.

**Comment by melloware** [comment]
@YexeY your options.

1. Debug and and provide a PR (of course).
2. Wait for another community member to debug or fix the issue.
3. Financially Sponsor the fix through either PrimeFaces PRO or one time consulting request https://www.primefaces.org/showcase/support.xhtml

**Comment by Rapster** [comment]
> doesnt work after first edit to cell 

> I already made a ticket like this, but when creating a reproducer thought that the error was fixed with 14.0.2.
But i noticed now, that in my testing, i forgot to remove a update="@Form" which made the tests redundant.

I must have missed a few episodes, but I don't see anywhere a clear description of the problem... All I see is that after a cell has been edited, I can't edited it once again as the input is disabled...

**Comment by melloware** [comment]
To boil it down edit a cell and look at the ajax update. The id says it's updating the table but the data inside that update is "black watch" not the full datatable DOM element it should be

**Comment by YexeY** [comment]
I pulled the primefaces and tested the versions a bit.
The commit that caused this bug is:

Fix #3571: Datatable improve cell editing performance (#11160) Melloware <mellowaredev@gmail.com> e8e80f467a8ac74d5d79dc14b81e29af7d57f0fe 24.12.2023 13:31:18

I will try to fix this, but i honestly am probably way out of my depth since this is my first contact with the actual code. Will try anyways

**Comment by YexeY** [comment]
> I pulled the primefaces and tested the versions a bit. The commit that caused this bug is:
> 
> Fix #3571: Datatable improve cell editing performance (#11160) Melloware [mellowaredev@gmail.com](mailto:mellowaredev@gmail.com) [e8e80f4](https://github.com/primefaces/primefaces/commit/e8e80f467a8ac74d5d79dc14b81e29af7d57f0fe) 24.12.2023 13:31:18
> 
> I will try to fix this, but i honestly am probably way out of my depth since this is my first contact with the actual code. Will try anyways

I tested it by just changing the showcase to fit my case: 

modified filter.xhtml:
`<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">

    <ui:define name="head">
        <style>
            .ui-filter-column .ui-column-customfilter .custom-filter {
                width: 100%;
                box-sizing: border-box;
            }
        </style>
    </ui:define>

    <ui:define name="title">
        DataTable <span class="subitem">Filter</span>
    </ui:define>

    <ui:define name="description">
        Filtering updates the data based on the constraints.
    </ui:define>

    <ui:param name="documentationLink" value="/components/datatable"/>
    <ui:param name="widgetLink" value="DataTable-1"/>

    <ui:define name="implementation">
        <div class="card">
            <h5>Column Filtering</h5>
            <h:form>
                <p:dataTable var="customer" value="#{dtFilterView.customers1}" widgetVar="customersTable"
                    emptyMessage="No customers found with given criteria"
                    filteredValue="#{dtFilterView.filteredCustomers1}"
                             editable="true"
                             editMode="cell"
                    globalFilterOnly="#{dtFilterView.globalFilterOnly}">

                    <f:facet name="header">
                        <div class="flex align-items-center justify-content-between">
                            <span>List of Customers</span>
                            <div>
                            <p:inputText id="globalFilter" onkeyup="PF('customersTable').filter()" style="width:10rem"
                                         placeholder="Enter keyword" />
                            <p:commandButton value="Global Filter Only" update="@form" styleClass="ml-2"
                                             action="#{dtFilterView.toggleGlobalFilter()}"/>
                            </div>
                        </div>

                    </f:facet>

                    <p:column headerText="Name" sortBy="#{customer.name}" filterBy="#{customer.name}" filterMatchMode="contains" filterPlaceholder="Filter By Name">
                        <p:cellEditor>
                            <f:facet name="output">
                                <h:outputText value="#{customer.name}" />
                            </f:facet>
                            <f:facet name="input">
                                <h:inputText value="#{customer.name}" style="width: 100%;"/>
                            </f:facet>
                        </p:cellEditor>
                    </p:column>

                    <p:column headerText="Country" sortBy="#{customer.country.name}" filterBy="#{customer.country.name}">
                        <span class="flag flag-#{customer.country.code}" style="width: 30px; height: 20px" />
                        <h:outputText style="vertical-align: middle; margin-left: .5rem" value="#{customer.country.name}" />
                    </p:column>

                    <p:column field="representative" headerText="Representative" filterMatchMode="exact"
                        sortBy="#{customer.representative.name}">
                        <f:facet name="filter">
                            <p:selectOneMenu onchange="PF('customersTable').filter()" styleClass="ui-custom-filter">
                                <f:selectItem itemLabel="All" itemValue="#{null}" noSelectionOption="true" />
                                <f:selectItems value="#{dtFilterView.representatives}" />
                            </p:selectOneMenu>
                        </f:facet>

                        <p:graphicImage name="images/avatar/#{customer.representative.image}" library="demo" width="32"
                            style="vertical-align: middle" />
                        <h:outputText style="vertical-align: middle; margin-left: .5rem" value="#{customer.representative.name}" />
                    </p:column>

                    <p:column field="date" headerText="Join Date" filterMatchMode="between">
                        <f:facet name="filter">
                            <p:datePicker selectionMode="range" onchange="PF('customersTable').filter()" converter="javax.faces.DateTime" />
                        </f:facet>
                    </p:column>

                    <p:column field="status" headerText="Status" filterMatchMode="exact">
                        <f:facet name="filter">
                            <p:selectOneMenu onchange="PF('customersTable').filter()" styleClass="ui-custom-filter">
                                <f:selectItem itemLabel="All" itemValue="#{null}" noSelectionOption="true" />
                                <f:selectItems value="#{dtFilterView.customerStatus}" />
                            </p:selectOneMenu>
                        </f:facet>

                        <span class="customer-badge status-#{customer.status.name().toLowerCase()}">#{customer.status.toString()}</span>
                    </p:column>

                    <p:column field="activity" headerText="Activity" sortBy="#{customer.activity}" filterMatchMode="gt"
                              converter="javax.faces.Integer">
                        <p:progressBar value="#{customer.activity}" displayOnly="true" style="height: .5rem" />
                    </p:column>

                </p:dataTable>
            </h:form>
        </div>
        <div class="card">
            <h5>Default Filter</h5>
            <h:form>
                <p:dataTable var="customer" value="#{dtFilterView.customers2}" widgetVar="customersTable2"
                    emptyMessage="No customers found with given criteria"
                    filteredValue="#{dtFilterView.filteredCustomers2}" filterBy="#{dtFilterView.filterBy}">

                    <f:facet name="header">
                        <span>List of Customers</span>
                    </f:facet>

                    <p:column headerText="Name" sortBy="#{customer.name}" filterBy="#{customer.name}">
                        <h:outputText value="#{customer.name}" />
                    </p:column>

                    <p:column headerText="Country" sortBy="#{customer.country.name}" filterBy="#{customer.country.name}">
                        <span class="flag flag-#{customer.country.code}" style="width: 30px; height: 20px" />
                        <h:outputText style="vertical-align: middle; margin-left: .5rem" value="#{customer.country.name}" />
                    </p:column>

                    <p:column field="representative" headerText="Representative" filterMatchMode="exact"
                              sortBy="#{customer.representative.name}">
                        <f:facet name="filter">
                            <p:selectOneMenu onchange="PF('customersTable2').filter()" styleClass="custom-filter">
                                <f:selectItem itemLabel="All" itemValue="#{null}" noSelectionOption="true" />
                                <f:selectItems value="#{dtFilterView.representatives}" />
                            </p:selectOneMenu>
                        </f:facet>

                        <p:graphicImage name="images/avatar/#{customer.representative.image}" library="demo" width="32"
                                        style="vertical-align: middle" />
                        <h:outputText style="vertical-align: middle; margin-left: .5rem" value="#{customer.representative.name}" />
                    </p:column>

                    <p:column field="date" headerText="Join Date" filterMatchMode="between">
                        <f:facet name="filter">
                            <p:datePicker selectionMode="range" onchange="PF('customersTable2').filter()" styleClass="ui-custom-filter"/>
                        </f:facet>
                    </p:column>

                    <p:column field="status" headerText="Status" filterMatchMode="exact">
                        <f:facet name="filter">
                            <p:selectOneMenu onchange="PF('customersTable2').filter()" styleClass="ui-custom-filter">
                                <f:selectItem itemLabel="All" itemValue="#{null}" noSelectionOption="true" />
                                <f:selectItems value="#{dtFilterView.customerStatus}" />
                            </p:selectOneMenu>
                        </f:facet>

                        <span class="customer-badge status-#{customer.status.name().toLowerCase()}">#{customer.status.toString()}</span>
                    </p:column>

                    <p:column field="activity" headerText="Activity" sortBy="#{customer.activity}"
                              converter="javax.faces.Integer">
                        <p:progressBar value="#{customer.activity}" displayOnly="true" style="height: .5rem" />
                    </p:column>
                </p:dataTable>
            </h:form>
        </div>
        <div class="card">
            <h5>Global Filter Function</h5>
            <h:form>
                <p:dataTable var="customer" value="#{dtFilterView.customers3}" widgetVar="customersTable3"
                             emptyMessage="No customers found with given criteria"
                             filteredValue="#{dtFilterView.filteredCustomers3}"
                             globalFilterFunction="#{dtFilterView.globalFilterFunction}">

                    <f:facet name="header">
                        <div class="flex justify-content-end">
                            <p:inputText id="globalFilter" onkeyup="PF('customersTable3').filter()" style="width:300px"
                                         placeholder="Search all fields using global function" />
                        </div>
                    </f:facet>

                    <p:column field="name" filterable="false"/>

                    <p:column headerText="Country" sortBy="#{customer.country.name}" >
                        <span class="flag flag-#{customer.country.code}" style="width: 30px; height: 20px" />
                        <h:outputText style="vertical-align: middle; margin-left: .5rem" value="#{customer.country.name}" />
                    </p:column>

                    <p:column field="representative" headerText="Representative" filterable="false">
                        <p:graphicImage name="images/avatar/#{customer.representative.image}" library="demo" width="32"
                                        style="vertical-align: middle" />
                        <h:outputText style="vertical-align: middle; margin-left: .5rem" value="#{customer.representative.name}" />
                    </p:column>

                    <p:column field="date" filterable="false"/>

                    <p:column field="status" filterable="false">
                        <span class="customer-badge status-#{customer.status.name().toLowerCase()}">#{customer.status.toString()}</span>
                    </p:column>

                    <p:column headerText="Activity" sortBy="#{customer.activity}">
                        <p:progressBar value="#{customer.activity}" displayOnly="true" style="height: .5rem" />
                    </p:column>
                </p:dataTable>
            </h:form>
        </div>
    </ui:define>

</ui:composition>
`

**Comment by melloware** [comment]
@YexeY thanks for the hint I know the issue now.  I think I can fix it.

**Comment by melloware** [comment]
@YexeY i monkey patched your original reproducer.  Try this version:
[pf-12274.zip](https://github.com/user-attachments/files/16824527/pf-12274.zip)

```js
if (PrimeFaces.widget.DataTable) {
  PrimeFaces.widget.DataTable.prototype.postUpdateData = function() {
    if (this.cfg.editable) {
      this.bindEditEvents();
    }

    if (this.cfg.draggableRows) {
      this.makeRowsDraggable();
    }

    if (this.cfg.reflow) {
      this.initReflow();
    }

    if (this.cfg.groupColumnIndexes) {
      this.groupRows();
      this.bindToggleRowGroupEvents();
    }

    if (this.cfg.expansion) {
      this.initRowExpansion();
    }

    if (this.cfg.cellNavigation) {
      this.setupNavigableCells();
    }
  };
}
```

**Comment by YexeY** [comment]
It worked, thank you very much!

**Comment by melloware** [comment]
Thanks for testing!  This will be in 14.0.5
