### ISSUE TITLE
DataTable: Align frozen columns right

### ISSUE THREAD

**Issue by tvazquez-dev** [primefaces/primefaces#12273]
### Description

Hello PrimeFaces Community,

I am proposing a new feature to enhance the PrimeFaces DataTable component by allowing the option to align frozen columns on the right side.

#### Key Points for Discussion:

- **Behavior**: How to determine which columns should be frozen.
- **Control**: How users can configure the alignment of frozen columns.

#### Current Progress:
I have successfully implemented a working demo for version 13.X and have written unit tests to ensure functionality. The implementation appears to be working well.

#### Next Steps:
I am considering opening a pull request. Before doing so, I would like to gather feedback on the following:

- The proposed behavior for determining and configuring frozen columns.
- Any additional considerations or potential improvements.

#### Control Mechanism:
To enable this feature, I have introduced a new attribute to the DataTable component: `alignFrozenColumnsRight`, which is a boolean value. When set to `true`, this attribute will align the frozen columns on the right side. When set to `false` (the default value), the columns will be aligned on the left side.

#### Behavior:

- **Left Aligned Frozen Columns:** The default behavior aligns the specified number of columns from the start of the column definition on the left side.
- **Right Aligned Frozen Columns:** With the `alignFrozenColumnsRight` attribute set to `true`, the specified number of columns will be aligned from the end of the column definition on the right side.

**Comment by melloware** [comment]
@tvazquez-dev please submit a PR so we can review.

**Comment by tvazquez-dev** [comment]
> @tvazquez-dev please submit a PR so we can review.

@melloware created one. Please let me know what you think :D

**Comment by tandraschko** [comment]
can i ask you, why you need this?
normally i would say it should be always left BUT always right when you activate primefaces.RTL

**Comment by melloware** [comment]
@tandraschko i thought the same thing about RTL but i think in this case there are some times like a total column on the Far right that you want Frozen while you scroll through all the values on the left.    I wouldn't want to force that with RTL or not.

**Comment by tvazquez-dev** [comment]
@tandraschko Melloware got it :D. I need to display an amount column and it just looks better on the right side.

**Comment by melloware** [comment]
@tvazquez-dev i reverted your commit against 13.X and made it against main 15.X.

**Comment by tvazquez-dev** [comment]
@melloware Alright, thank you.
