### ISSUE TITLE
Documentation: jQuery version matrix

### ISSUE THREAD

**Issue by O-Jason** [primefaces/primefaces#12279]
### Description

Hello,

I looked for jQuery version for some version of Primefaces. A.I. told me nothing right and even documentation of Primefaces seems wrong. For example, i looked for Primefaces 5.1 and found this documentation : https://www.primefaces.org/docs/guide/primefaces_user_guide_5_1.pdf. It says page 516 

> PrimeFaces renders unobstrusive javascript which cleanly separates behavior from the html. Client
side engine **is powered by jQuery version 1.8.1** which is the latest at the time of the writing.

Problem is repository told me that jQuery is version 1.11.0 : https://github.com/primefaces/primefaces/blob/5_1/src/main/resources/META-INF/resources/primefaces/jquery/jquery.js

jQuery version 1.8.1 was two years ago (primefaces 3.4) : https://github.com/primefaces/primefaces/blob/3_4/src/main/resources/META-INF/resources/primefaces/jquery/jquery.js

I didn't find any information on the documentation for Primefaces 7.0 related to jQuery version but i could find this information in the repository : https://github.com/primefaces/primefaces/blob/7.0/src/main/resources/META-INF/resources/primefaces/jquery/jquery.js (jQuery 3.3.1). 

### Describe the solution you would like

Ideally, i would like to have this information right on each documentation version but for the oldest one are in PDF format so it would be complicated i suppose. What i suggest is to have a matrix between jQuery and Primefaces version in the wiki of GitHub or maybe on the website.

**Comment by tandraschko** [comment]
we wont do something, sorry
in theory we would need such a matrix for each dependency and we have like 30 of them
for newer versions we have this table: https://primefaces.github.io/primefaces/14_0_0/#/core/thirdpartylibs

**Comment by melloware** [comment]
@O-Jason what is your goal?  

A few notes...

You can always type `PrimeFaces.version()` into the browser starting with i think PF10 and we show you jQuery and UI version.

![image](https://github.com/primefaces/primefaces/assets/4399574/5a36e30f-412b-4e16-8c5b-1e06a0781758)

AS @tandraschko mentioned it is documented in the `thirdpartylibs.md`

15.0: https://primefaces.github.io/primefaces/15_0_0/#/core/thirdpartylibs
14.0: https://primefaces.github.io/primefaces/14_0_0/#/core/thirdpartylibs
13.0: https://primefaces.github.io/primefaces/13_0_0/#/core/thirdpartylibs
12.0: https://primefaces.github.io/primefaces/12_0_0/#/core/thirdpartylibs
11.0: https://primefaces.github.io/primefaces/11_0_0/#/core/thirdpartylibs
10.0: https://primefaces.github.io/primefaces/10_0_0/#/core/thirdpartylibs
8.0: https://primefaces.github.io/primefaces/8_0/#/core/thirdpartylibs


So I guess I am back to what is your goal with knowing about PF5 or way old versions you shouldn't be using anyway?

**Comment by O-Jason** [comment]
@melloware : i've got issue activating "Content-Security-Policy" with the jQuery version embedded in Primefaces 5.1. It seems to be fixed in jQuery 3.3 but couldn't figure out the version of Primefaces i should target at least. I understand that these version are way too old but it's an heavy upgrade (2 majors versions) for my project. Moreover, project targets Primefaces 7.0 for critical vulnerabilities issues.

**Comment by melloware** [comment]
@O-Jason ok then it doesn't matter.  You can't use Content-Security-Policy with PF 5.1  There were core PF changes made in PF 8.0 to allow Content-Security-Policy and its built into PF.

See the docs: https://primefaces.github.io/primefaces/8_0/#/core/contentsecuritypolicy
