### ISSUE TITLE
MenuButton: buttons inside the menuButton are not updated anymore

### ISSUE THREAD

**Issue by Sun8642** [primefaces/primefaces#12286]
### Describe the bug

The buttons inside a menuButton are not updated anymore when using the update attribute. (FYI: this worked perfectly in PF 13.0.8)

### Reproducer

[Reproducer](https://github.com/user-attachments/files/16235798/primefaces-test.zip)
1. Go to http://localhost:8080/
2. Click on the plus to see that the buttons are disabled (they should be enabled when an item is selected)
3. Select a row (you can see that the buttons outside the menuButton are updated correctly)
4. Click on the plus to see that the buttons inside the menuButton are not updated

### Expected behavior

The buttons inside the menuButton should be updated

### PrimeFaces edition

None

### PrimeFaces version

14.0.2

### JSF implementation

All

### JSF version

2.3

### Java version

17.0.6

### Browser(s)

All

**Comment by melloware** [comment]
Fixed reproducer:
[pf-12286.zip](https://github.com/user-attachments/files/16237867/pf-12286.zip)

MonkeyPatch:

```js
if(PrimeFaces.widget.MenuButton) {
    PrimeFaces.widget.MenuButton.prototype.init = function(cfg) {
        PrimeFaces.widget.TieredMenu.prototype.init.call(this, cfg);

        this.trigger = this.jq.children('button');
        this.menu = null;
        this.cfg.disabled = this.trigger.is(':disabled');
        this.cfg.overlay = true;
		this.cfg.appendTo = PrimeFaces.escapeClientId(this.trigger.attr("id"));

        this.bindButtonEvents();
        PrimeFaces.utils.registerDynamicOverlay(this, this.getMenuElement(), this.id + '_menu');
        this.transition = PrimeFaces.utils.registerCSSTransition(this.getMenuElement(), 'ui-connected-overlay');
    }
}
```

**Comment by melloware** [comment]
cc @vonnai
