### ISSUE TITLE
ValidateFile: with variable in sizeLimit not working

### ISSUE THREAD

**Issue by SimonePadovan** [primefaces/primefaces#12283]
### Describe the bug

If i use p:valiadteFile with a variable in sizeLimit (fileUploadView.size) it doesn't consider it at runtime.

```xml
 <h:form id="frmTest">

			<p:growl id="growl" sticky="true" showDetail="true"/>

			<p:inputText value="#{fileUploadView.size}" >
				<p:ajax update="xx,input20" />
			</p:inputText>
			<h:outputText id="xx" value="#{fileUploadView.size}" />

			<p:fileUpload id="input20" update="growl" 
					  listener="#{fileUploadView.handleFileUpload}"
					  mode="advanced" dragDropSupport="true" auto="true" >
				<p:validateFile sizeLimit="#{fileUploadView.getSizeLimit(fileUploadView.size)}" allowTypes="/(\.|\/)(gif|jpeg|jpg|png)$/" />
			</p:fileUpload>

        </h:form>
```

```java
@Named
@RequestScoped
public class FileUploadView {

	private UploadedFile file;
	private String size;

	public void upload() {
		if (file != null) {
			FacesMessage message = new FacesMessage("Successful", file.getFileName() + " is uploaded.");
			FacesContext.getCurrentInstance().addMessage(null, message);
		}
	}

	public void handleFileUpload(FileUploadEvent event) {
		FacesMessage message = new FacesMessage("Successful", event.getFile().getFileName() + " is uploaded.");
		FacesContext.getCurrentInstance().addMessage(null, message);
	}

	public UploadedFile getFile() {
		return file;
	}

	public void setFile(UploadedFile file) {
		this.file = file;
	}


	public String getSizeLimit(String limit) {
		if (limit != null) {
			return limit;
		}
		return "100000";
	}

	@PostConstruct
	public void init() {
		setSize("70000");
	}

	public String getSize() {
		return size;
	}

	public void setSize(String size) {
		this.size = size;
	}

}
```

### PrimeFaces edition

None

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
If I had to guess its because the validateFile is loaded only when the component first renders.  I feel like this was asked before also but can't find the ticket or community post.

**Comment by melloware** [comment]
@SimonePadovan can you put together a reproducer.  I know you posted code above but it saves us Devs time if we have a runnable reproducer rather than us have to spend the time to build one.

**Comment by tandraschko** [comment]
Basically: https://github.com/jakartaee/faces/issues/1499

**Comment by SimonePadovan** [comment]
I think you are right: the problem is the validator which is loaded only once when the component is rendered.
I have a project which uses the fileUpload tag and the sizeLimit is a property loaded from a runtime configuration. It has always worked good but the decision to move this parameter from tag to validator breaks the funcionality.
How can i use new fileValidator with property loaded ad runtime ? Am i forced to deal with it in the listener of fileupload ?
thanks

**Comment by SimonePadovan** [comment]
[primefaces-test-jakarta.zip](https://github.com/user-attachments/files/16194677/primefaces-test-jakarta.zip)

**Comment by melloware** [comment]
Yep looks like its a Faces spec issue as @tandraschko pointed out.  Thanks for the reproducer.

**Comment by fcorneli** [comment]
This could easily be implemented by accompanying the validator with a custom `TagHandler` I guess.
Within the `TagHandler` one can pass certain attributes as a `ValueExpression` towards the actual `Validator` instance.
Example:
https://github.com/e-Contract/enterprise-jsf/blob/master/ejsf-taglib/src/main/java/be/e_contract/ejsf/validator/ratelimiter/RateLimiterValidatorTagHandler.java

**Comment by tandraschko** [comment]
@jungm wanna contribute the ValidatorBase?

**Comment by fcorneli** [comment]
@tandraschko  An abstract and state-holding `ValidatorBase` with corresponding `TagHandler` that is capable of injecting attributes as `ValueExpression`?

**Comment by tandraschko** [comment]
Yup

**Comment by fcorneli** [comment]
Nice! 😄

**Comment by fcorneli** [comment]
Seems like OmniFaces already offers something similar:
https://showcase.omnifaces.org/taghandlers/validator

**Comment by tandraschko** [comment]
IMO validator needs support for StateHelper like Components, thats whats missing in specs

We implemented it, @jungm could provide and we can migrate to it

**Comment by jungm** [comment]
Will look into it tomorrow, merging it into PF should be pretty straightforward I think. Just need to test if it works with mojarra too as we never used mojarra 😉

**Comment by tandraschko** [comment]
btw we did the same for behaviors: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/behavior/base/AbstractBehavior.java

please make sure we align both impls, code should be very similar

**Comment by tandraschko** [comment]
not sure but the code in the behavior implements full-state saving, seems we didnt implement delta state here like MF does

maybe we should create a second issue about it
