### ISSUE TITLE
DataTable: Row stops rendering data after CommandLink/CommandButton

### ISSUE THREAD

**Issue by FriedhelmKuehn** [primefaces/primefaces#12285]
### Describe the bug

Environment: Win10, Tomcat 10.1.26, PrimeFaces 14.0.2 ...  (application ran under Tomat 8.5/Mojarra 2.4 and PrimeFaces 8 for years)
Komplex DataTables do work - this simple one does not - Data from Java-logic are in the Browser - **but do not show**! 

Please take a look at the PDF attached - Thanks in advance!

[20240715_PrimeFacesIssue.pdf](https://github.com/user-attachments/files/16235181/20240715_PrimeFacesIssue.pdf)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### Theme

Default

### JSF implementation

Mojarra

### JSF version

Jakarta Faces 4.1

### Java version

JDK 17

### Browser(s)

FireFox and Chrome

**Comment by melloware** [comment]
@FriedhelmKuehn we have a Jakarta 4.0 branch of that test project you can use.

**Comment by FriedhelmKuehn** [comment]
Hi there, 

 

this is an application with 5 Mio LOC (java and Xhtml, ajax …) … it would take me at least 

one week to provide an ‘example – runnable for you’.

 

Please simply have a short look at the Screenshots in my PDF-Attachment – they are from 

the ‘running application’ and obviously SHOW THE PROBLEM – thank you for your patience 

and understanding!

 

If more info is required … I can surely deliver these by debugging the Java-Code in Eclipse 

or the User Interface in the Browser … 

 

Best regards

Friedhelm

 

Von: github-actions[bot] ***@***.*** 
Gesendet: Montag, 15. Juli 2024 15:35
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Author ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

Please provide an executable example using the PrimeFaces Test <https://github.com/primefaces/primefaces-test>  project. This issue will be closed if no activities in 20 days.

**Comment by FriedhelmKuehn** [comment]
Hi there,

 

these are ‘Kids examples’ – let me show you a ‘real world application’ (please see below)!

 

If I would try to deliver a such simple one to you … all influences from the surroundings … especially cascading 

down from the surrounding TabView Pages … would disappear.

 

I myself developed that application in the last 12 years or so – it ran stable for years under Tomcat 8.5 with PF 8 

… so please believe me , I know enough about the PF product – … and please help!

 

Best regards

Friedhelm

 

The real-world application:

That’s our application under Tomcat 8.5 with Primefaces 8



 

And this is ‘your running sample under Tomcat 10.1.26’ (Jakarta ….)

(this time with PrimeFaces 14.0.2 and the Aristo-Theme from PrimeFaces 8 – but I reproduced the error with 

the ‘Default’ theme and  the Browser cache cleared before)

 



 

The ‘Problem Help Page’



 

 

Von: Melloware ***@***.*** 
Gesendet: Montag, 15. Juli 2024 15:58
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

screenshots are not a reproducer though. See the PF showcsae is working fine in Basic mode: https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml?jfwid=48421

That is Basic as a Datatable gets so without a reproducer what can we debug?

**Comment by tandraschko** [comment]
Did you check all migration guides? We are not full backward compatible to 8.0.

**Comment by FriedhelmKuehn** [comment]
Hi Thomas, 

 

thank you for your (the first) serious question …

 

The solution for the problem may be …

 

With a composition-surrounding like … it does work ‘somehow’, 

but not well.



 

With the (original) composition-surrounding like … it looks better – I will 

have to investigate further …



 

I’ll keep you informed.

 

Best regards,

Friedhelm

 

Von: Thomas Andraschko ***@***.*** 
Gesendet: Montag, 15. Juli 2024 16:46
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

Did you check all migration guides? We are not full backward compatible to 8.0.

**Comment by tandraschko** [comment]
Well, thats the only question we can ask (and to check docs and Showcase) 😅 everything else is propably a bug and we need a reproducer, so we can double check it and create a Integration test.

**Comment by melloware** [comment]
> Hi Thomas, thank you for your (the first) serious question … 

First serious question?  @FriedhelmKuehn don't forget we don't work for you. we are open source contributors.  So asking for a reproducer showing us the issue is the least you can do to try and help us

**Comment by FriedhelmKuehn** [comment]
Hi Melloware (?),

 

sorry, if my reaction was a bit too frustrated … 

 

… I had some bad weeks with ‘buggy versions for different products’ (not PF!) 

in the last weeks.

 

@Thomas:

It seems to work now with:



 

Thanks to both of you – please close this incident!

 

Best regards,

Friedhelm

Von: Melloware ***@***.*** 
Gesendet: Montag, 15. Juli 2024 18:27
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

Hi Thomas, thank you for your (the first) serious question …

First serious question? @FriedhelmKuehn <https://github.com/FriedhelmKuehn>  don't forget we don't work for you. we are open source contributors. So asking for a reproducer showing us the issue is the least you can do to try and help us debug your issue.

**Comment by FriedhelmKuehn** [comment]
Hi Thomas,

 

why ‚Closed … as not planned‘? 

 

If you are interested to investigate this situation more deeply, I can assist (f.e. by reproducing 

this error and providing other/more information) – but I surely will not be able to provide/deliver 

a ‘Simple Example’ … 

 

Best Regards

Friedhelm

 

Von: Thomas Andraschko ***@***.*** 
Gesendet: Montag, 15. Juli 2024 23:36
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

Closed #12285 <https://github.com/primefaces/primefaces/issues/12285>  as not planned.

**Comment by tandraschko** [comment]
Because of your statement: Thanks to both of you – please close this incident

We can just reopen If you have a reproducer also.

**Comment by FriedhelmKuehn** [comment]
Hi Thomas,

 

just to make clear: 

-          for me this problem is solved – and this incident can be kept closed

 

If you have further interest to ‘analyse’ … I would try to assist/help, because I 

can ‘reproduce and debug’ this (but, as I said, I cannot deliver a ‘Simple Sample’ 

– and I think you really do not want to get a .zip of a 150MB Tomcat_10.1.26 

with the .war deployed in it)

 

Looks like ‘ui:composition’ is not handled ‘fully correct’,  if  the ‘xmlns-Property’ 

has some ‘unexpected (?)’ value (maybe a CSS-Style ‘hide’ is cascading from outside 

over the ‘ui:composition’ and into ‘h:outputText’).

 

I personally would prefer the software to

-          either ‘do nothing’ or ‘do it fully correct’

-          but not ‘do it partially’

and/or

-          to get any Error-/Info-Message …

.

 

I don’t believe this is a PrimeFaces-Problem (alone) – since handling of ‘ui:composition’ 

should not be ‘your job’ – but I don’t know exactly.

 

Best Regards 

Friedhelm

Von: Thomas Andraschko ***@***.*** 
Gesendet: Dienstag, 16. Juli 2024 07:57
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

Because of your statement: Thanks to both of you – please close this incident

We can just reopen If you have a reproducer also.

**Comment by tandraschko** [comment]
We could try to debug on your machine and so on but thats more professional support then just fixing a issue.
You must know that we do this all in our spare time here.
And even if we could fix something, we should create a integration test to make sure that we wont break again in future. And this requires a isolated reproducer, not a full blown 150mb application.

there is just no other or better way for us, to ask people to create reproducers, which can be then reused as a integration test.

**Comment by melloware** [comment]
And to add to that. It's not an issue with PrimeFaces code unless you can "prove" it's an issue with a reproducer. Which you say you can't do. So as far as we are concerned there is no bug only a mistake in your code.

**Comment by FriedhelmKuehn** [comment]
Hi Thomas,

 

the Timestamps from your mails

-          Yesterday : 23.36 at night

-          Today: 7:57   in the morning

where very convincing for me!

 

Hope the attachment helps – have a nice and successful ‘try’!

 

Best Regards

Friedhelm

 

----------------------------------------------------------------------------------------------------

Please find attached something like a ‚sample’, consisting of File-Structures I got 

by ‘save page as’ in the Browser (see below).

 

-          _pf contains an adaption of your ‘Basic DataTable Sample’  

-          In query you find only the Main Page of a Query

-          In resulthelp you find only the ‘help-Page’ for that query …. with your ‘Basic-DataTable’



If you open … Xcmr_Host_Show.html … you should see the data

If you open … Xcmr_Host_NoShow.html … you should not see the data

 

The Only difference is:

-          Either one of the ‘ui:composition’entries  in the resulthelp\... is activated (here: NoShow is active)



Von: Thomas Andraschko ***@***.*** 
Gesendet: Dienstag, 16. Juli 2024 09:49
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

We could try to debug on your machine and so on but thats more professional support then just fixing a issue.
You must know that we do this all in our spare time here.
And even if we could fix something, we should create a integration test to make sure that we wont break again in future. And this requires a isolated reproducer, not a full blown 150mb application.

there is just no other or better way for us, to ask people to create reproducers, which can be then reused as a integration test.

**Comment by tandraschko** [comment]
Please use GitHub for the attachments, i cant see any 😅

**Comment by FriedhelmKuehn** [comment]
Hope it works this time - and helps!

[demo.zip](https://github.com/user-attachments/files/16247148/demo.zip)

**Comment by tandraschko** [comment]
sorry, i dont have that time to convert it to a primefaces-test reproducer

**Comment by melloware** [comment]
As stated before @FriedhelmKuehn what you sent is a "mess" and not obvious at all.  

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by FriedhelmKuehn** [comment]
Hi Melloware,

 

just to make it clear to you:

-          Since yesterday in the afternoon this is not OUR/my problem – it is 

yours (PrimeFaces, etc.)

 

This behaviour (parts of the data are accidentially lost in the User-Interface without any 

Error-Message) - cannot stay as it is.

 

My company has had a ‘Maintenance Service Contract’ with PrimeFaces for some years in 2010-201x, 

and since we ‘propagated’ few errors in that time, maybe Cagatay Civici is willing to ‘risk some time’ 

to look at it himself.

 

Best Regards

Friedhelm

Von: Melloware ***@***.*** 
Gesendet: Dienstag, 16. Juli 2024 16:19
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Simple Datatable (HelpTable) dows not show the Data (Issue #12285)

 

As stated before @FriedhelmKuehn <https://github.com/FriedhelmKuehn>  what you sent is a "mess" and not obvious at all.

Please provide an executable example using the PrimeFaces Test <https://github.com/primefaces/primefaces-test>  project. It is the only way developers can debug your problem to help.

**Comment by jepsar** [comment]
@FriedhelmKuehn again, this issue tracker and its version of PrimeFaces is maintained by the community, so non-PrimeTek employees in their spare time. Please read https://github.com/primefaces/primefaces?tab=readme-ov-file#community--elite--pro

**Comment by melloware** [comment]
@FriedhelmKuehn i think i got to the bottom of it in my case. Read this thread: https://github.com/orgs/primefaces/discussions/2350

**Comment by melloware** [comment]
@FriedhelmKuehn is there any chance you can create an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project?  I doubt PrimeTek will help without a reproducer as well even with a PRO account.

**Comment by FriedhelmKuehn** [comment]
Hi Melloware,

 

I have emailed him this morning (with attachments) – this time successfully.

 

I’ll keep you informed when/what I get as reply!

 

Best regards,

Friedhelm

 

Friedhelm Kühn

Geschäftsführer

 

CMS IT-Services GmbH

Elsterweg 9
D - 55232 Alzey 

  

Mobil:    +49 - (0)151 - 58744336 

Telefon: +49 - (0)6731 - 471397-1
Telefax: +49 - (0)6731 - 471397-4 

E-Mail:   ***@***.*** ***@***.***> 

Web:      www.codemining.de 

 

Registergericht  : Amtsgericht Mainz 

                            HRB 42599 

UST-IdNr:            DE270212347 

Von: Melloware ***@***.*** 
Gesendet: Donnerstag, 1. August 2024 14:01
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Row stops rendering data after CommandLink/CommandButton (Issue #12285)

 

@FriedhelmKuehn <https://github.com/FriedhelmKuehn>  is there any chance you can create an executable example using the PrimeFaces Test <https://github.com/primefaces/primefaces-test>  project? I doubt PrimeTek will help without a reproducer as well even with a PRO account.

**Comment by melloware** [comment]
@FriedhelmKuehn if you are not a PRO subscriber you will not get a reply...

**Comment by FriedhelmKuehn** [comment]
Hi Melloware,

 

I’m the owner of a company that had a maintenance-contract with his company 

some years ago  …

 

… and if I don’t get an answer, 

it is

-          his decision

-          his problem 

-          concerning his product

-          and is related to the future of his company.

 

I have currently no problem related to the PrimeFaces product,

and I have to run my own company now.

 

Best regards,

Friedhelm

 

Friedhelm Kühn

Geschäftsführer

 

CMS IT-Services GmbH

Elsterweg 9
D - 55232 Alzey 

  

Mobil:    +49 - (0)151 - 58744336 

Telefon: +49 - (0)6731 - 471397-1
Telefax: +49 - (0)6731 - 471397-4 

E-Mail:   ***@***.*** ***@***.***> 

Web:      www.codemining.de 

 

Registergericht  : Amtsgericht Mainz 

                            HRB 42599 

UST-IdNr:            DE270212347 

Von: Melloware ***@***.*** 
Gesendet: Donnerstag, 1. August 2024 16:02
An: primefaces/primefaces ***@***.***>
Cc: FriedhelmKuehn ***@***.***>; Mention ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Row stops rendering data after CommandLink/CommandButton (Issue #12285)

 

@FriedhelmKuehn <https://github.com/FriedhelmKuehn>  if you are not a PRO subscriber you will not get a reply...
