### ISSUE TITLE
SelectOneMenu with 3 level chained/depdendent drop downs

### ISSUE THREAD

**Issue by DVenkatesh** [primefaces/primefaces#1228]
We have JSF form. In the form we have 3 levels of chained/dependent drop downs (Country, State, City) using SelectOneMenu of PrimeFaces.
We select a country from the first drop down. This triggers PrimeFaces ajax event and populates State drop down.
We navigate away from the current page/form, this triggers "Leave the current page, Do you want to stay or leave" browser popup. We select "Stay on this page".
Then try to select the State from the second drop down.
This will not trigger the ajax event to get list of Cities for the third drop down.

Please suggest a solution for this issue.

Thanks in advance

**Comment by kukel** [comment]
Use the forum for this... and https://www.google.com/search?q=mcve+format+code and version info

**Comment by sudheerj** [comment]
Use forum for the questions please.
