### ISSUE TITLE
Context Path not Working after updating primefaces version to 10.0.0

### ISSUE THREAD

**Issue by redz09123** [primefaces/primefaces#12282]
![image](https://github.com/user-attachments/assets/52b2bf5d-8d70-4e04-a1f6-f84acfaf5325)
I converted my primefaces version from 6.2 to 10.0.0 but suddenly after changing the depreciated codes to new ones I tried to run my webapp and it displays the index just fine but when I navigated to my nav menu and open a page the context path is not working 

this is the sample path  that should be correctly showing up
http://localhost:8080/uberConsole/faces/pages/competition/eventProcessor.xhtml

but this is the path I am getting
http://localhost:8080/faces/pages/competition/eventProicess.xhtml

and it throws a 404 error because the path is unreachable

i already declared /uberConsole in my context path inside my context.xml but its still not working

**Comment by jepsar** [comment]
10 is not supported by the community. Please try with 14 and follow the issue form which asks you to add a reproducer.

**Comment by redz09123** [comment]
> 10 is not supported by the community. Please try with 14 and follow the issue form which asks you to add a reproducer.

okay thanks for the info

**Comment by melloware** [comment]
@redz09123 you should ask these questions here: https://github.com/orgs/primefaces/discussions/categories/primefaces

From looking above I really don't think this is a PrimeFaces issue as it doesn't control the context path i would think you upgraded other things in your infrastructure as well?  JSF version?  Server?
