### ISSUE TITLE
Prime Faces Designer Stuck on Setting Up

### ISSUE THREAD

**Issue by redz09123** [primefaces/primefaces#12298]
I am planning to customize a theme for the web app I am currently working on, but whenever I open the designer and pick the base theme, it gets stuck on 'setting up.' Is there currently a problem with the Prime Faces designer?
![image](https://github.com/user-attachments/assets/23a6c3ff-d6c5-4a2f-b598-cb4e2f6fed03)

**Comment by tandraschko** [comment]
There is already a discussion: https://github.com/orgs/primefaces/discussions/2323

The Community cant fix this, will close it.
CC @mertsincan @cagataycivici
