### ISSUE TITLE
DataTable: Problems with sticky header and the z-index of modal dialogs

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#12293]
### Describe the bug

A dialog becomes unclickable because of problems with the z-index if a DataTable with stickyHeader is updated by an AJAX call.

Prerequisites:
- DataTable with stickyHeader="true"
- Two modal dialogs
- When closing the first dialog, a second dialog is opened and the DataTable is updated by the AJAX call
- Upon the first click on the page, the "ui-dialog-mask" becomes the frontmost DOM element and nothing is clickable anymore

### Reproducer

[sticky-header-modal-dialogs-z-index.zip](https://github.com/user-attachments/files/16250399/sticky-header-modal-dialogs-z-index.zip)

1. Click on "Open Dialog 1"
2. Click on "Close" in Dialog 1
3. Try to click on "Close" in Dialog 2

### Expected behavior

The second dialog can be interacted with normally.

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.2

### Theme

Rain

### JSF implementation

All

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
Caused by: https://github.com/primefaces/primefaces/issues/12151

**Comment by melloware** [comment]
MonkeyPatch: 

```js
PrimeFaces.utils.nextStickyZindex = function() {
            // Get the z-index of the highest visible sticky, or use PrimeFaces.nextZindex() + 1 if none found
            var zIndex = $('.ui-sticky:visible').last().zIndex() || PrimeFaces.nextZindex() + 1;
            

            // GitHub #9295 Adjust z-index based on overlays
            var overlays = $('.ui-widget-overlay:visible');
            if (overlays.length) {
                overlays.each(function() {
                    var currentZIndex = $(this).zIndex() - 1;
                    zIndex = Math.min(currentZIndex, zIndex);
                });
            }

            // Decrease zIndex by 1 and return
            return zIndex - 1;
        };
```

**Comment by mkomko** [comment]
@melloware Thank you for the quick MonkeyPatch! It works perfectly for the use cases I tested:
- Hiding a dialog while displaying another
- Displaying multiple dialogs over each other

Thank you!

**Comment by melloware** [comment]
I am going to see if I can fix this AND the original issue that broke it.  If I can't then I am just leaving this fix.

**Comment by mkomko** [comment]
I don't envy you for having to battle with z-index and JS, thank you very much!

**Comment by melloware** [comment]
@mkomko can you try this version I tested against both your reproducer and 12151 and everything seems to be working.

```js
PrimeFaces.utils.nextStickyZindex = function() {
  var highestStickyZIndex = parseInt($('.ui-sticky:visible').last().zIndex()) || parseInt(PrimeFaces.nextZindex()) + 1;

  var overlays = $('.ui-widget-overlay:visible');
  if (overlays.length) {
    overlays.each(function() {
      var overlayZIndex = parseInt($(this).zIndex()) - 1;
      highestStickyZIndex = Math.min(overlayZIndex, highestStickyZIndex);
    });
  } else {
    PrimeFaces.zindex = highestStickyZIndex - 1;
  }

  return highestStickyZIndex - 1;
};
```

**Comment by mkomko** [comment]
> @mkomko can you try this version I tested against both your reproducer and 12151 and everything seems to be working.

I can confirm that our use cases work perfectly with this new MonkeyPatch. Nice job, thank you!

**Comment by melloware** [comment]
thanks for testing!
