### ISSUE TITLE
SelectCheckboxMenu options not reflecting after selection   

### ISSUE THREAD

**Issue by DVenkatesh** [primefaces/primefaces#1229]
We have JSF form. Form has few SelectCheckboxMenu. If user selects the options, the values reflect in the corresponding menu input box.

If the user navigates away from the form, this triggers "Leave the current page, Do you want to stay or leave" browser popup. User selects "Stay on this page".
1. Now, if the user select any option from the SelectCheckboxMenu menu items, then the newly selected options wont reflect in the corresponding menu input box.
2. Further to this, if we try to save/submit the form the form fails to submit.

Please suggest a solution for these issues.

Thanks in advance

**Comment by kukel** [comment]
Use the forum first and for the rest the same comments as in the other 'issue'
