### ISSUE TITLE
Core: Add validation.js to core.js since its always included now

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#12297]
### Describe the bug

I'm trying to migrate to PF 14 but a new `validation.js` is always added and I don't need it...

Also If I defer the loading with OmniFaces `o:deferredScript` it will be added twice!

I've tried to disable the CSV from web.xml but `validation.js` is always added

```
<context-param>
    <param-name>primefaces.CLIENT_SIDE_VALIDATION</param-name>
    <param-value>false</param-value>
</context-param>

<context-param>
    <param-name>primefaces.CLIENT_SIDE_LOCALISATION</param-name>
    <param-value>false</param-value>
</context-param>

<context-param>
    <param-name>primefaces.INTERPOLATE_CLIENT_SIDE_VALIDATION_MESSAGES</param-name>
    <param-value>true</param-value>
</context-param>
```

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

4

### Java version

21

**Comment by melloware** [comment]
@pizzi80 it was added by default because now File Upload requires it. https://github.com/primefaces/primefaces/issues/11044

i am wondering whether it should just be rolled into core.js

**Comment by tandraschko** [comment]
Yeah
Thought the same

**Comment by melloware** [comment]
OK i will update this.
