### ISSUE TITLE
Datatable reset Scroll state after click outside of Browser

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#1230]
Steps to reproduce the issue:

Create scrollable datatable with selection enabled and add ajax event for rowSeclect. Scroll down to position outside of initial viewport (for example in the middle). Select a row. Take a click outside of the browser and again click inside the table.

Result:
The datatable change scrollposition to top and first row get hover color. the selected row keep selected but is outside of viewport.

Same effect is also on the Showcase

**Comment by kukel** [comment]
what showcase example? I don't see an example with this combination

**Comment by markusg80** [comment]
Ok i correct my statement. You can modify the select events showcase example with adding scrollable="true" scrollHeight="150" and then look to create enough cars (for example 100).

```
<p:dataTable id="singleDT" var="car" value="#{dtSelectionView.cars2}" selectionMode="single"  selection="#{dtSelectionView.selectedCar}" rowKey="#{car.id}"
  scrollable="true" scrollHeight="150">
    <f:facet name="header">
        Single with Row Click
    </f:facet>
    <p:column headerText="Id">
        <h:outputText value="#{car.id}" />
    </p:column>
    <p:column headerText="Year">
        <h:outputText value="#{car.year}" />
    </p:column>
    <p:column headerText="Brand">
        <h:outputText value="#{car.brand}" />
    </p:column>
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
    <f:facet name="footer">
        <p:commandButton process="singleDT" update=":form:carDetail" icon="ui-icon-search" value="View" oncomplete="PF('carDialog').show()" />
    </f:facet>
</p:dataTable>
```

**Comment by frkmed** [comment]
Hello markusg80, any solution for that issue

**Comment by markusg80** [comment]
At the moment i doesn't see a solution because until now i not do debuging inside primefaces. Maybe when i find time i can try to find the reason of the issue

**Comment by michael-las** [comment]
provided PR #1512
