### ISSUE TITLE
DataTable ContextMenu: Shift+F10 open browser default contextMenu (not contextMenu from Primefaces)

### ISSUE THREAD

**Issue by Attila101498** [primefaces/primefaces#12302]
### Describe the bug

When I try to open the context menu in the DataTable component by pressing Shift+F10, the context menu created by Primefaces is not displayed, but the browser's default context menu. This feature can also be reproduced on the Primefaces Showcase page: https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

### Expected behavior

The expected functionality would be to work in the same way as the Tree ContextMenu. Here I can also open the context menu with Shift+F10: https://www.primefaces.org/showcase/ui/data/tree/contextMenu.xhtml

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
i will check its also possible this is not possible to intercept the browser handling with Hotkeys.

**Comment by melloware** [comment]
@Attila101498 can you try this monkeypatch.  I looked at what Tree is doing and it has to catch all contextMenuevents on the tree container. For the Datatable for me to do the same it works but the Context Menu appears in the left hand side of the Datatable because its on the whole container.

```js
if (PrimeFaces.widget.DataTable) {
  PrimeFaces.widget.DataTable.prototype.bindContextMenu = function(menuWidget, targetWidget, targetId, cfg) {
    var $this = this;
    var targetSelector = targetId + ' tbody.ui-datatable-data > tr.ui-widget-content';
    var targetEvent = cfg.event + '.row' + this.id;
    var containerEvent = cfg.event + '.datatable' + this.id;
    this.contextMenuWidget = menuWidget;

    $(document).off(targetEvent, targetSelector).on(targetEvent, targetSelector, null, function(e) {
      var row = $(this);

      if (targetWidget.cfg.selectionMode && row.hasClass('ui-datatable-selectable')) {
        var isContextMenuDelayed = targetWidget.onRowRightClick(e, this, cfg.selectionMode, function() {
          $this.contextMenuWidget.show(e);
        });
        targetWidget.updateContextMenuCell(e, targetWidget);

        if (isContextMenuDelayed) {
          e.preventDefault();
          e.stopPropagation();
        }
      } else if (targetWidget.cfg.editMode === 'cell') {
        targetWidget.updateContextMenuCell(e, targetWidget);
        $this.contextMenuWidget.show(e);
      } else if (row.hasClass('ui-datatable-empty-message') && !$this.cfg.disableContextMenuIfEmpty) {
        $this.contextMenuWidget.show(e);
      }
    });
    $(document).off(containerEvent, this.jqTargetId).on(containerEvent, this.jqTargetId, null, function(e) {
      if (e.target.id == targetWidget.id + '_data') {
        $this.contextMenuWidget.show(e);
      }
    });
    this.addDestroyListener(function() {
      $(document).off(targetEvent + ' ' + containerEvent);
    });

    if (this.cfg.scrollable && this.scrollBody) {
      this.scrollBody.off('scroll.dataTable-contextmenu').on('scroll.dataTable-contextmenu', function() {
        if ($this.contextMenuWidget.jq.is(':visible')) {
          $this.contextMenuWidget.hide();
        }
      });
    }
  }
}
```

**Comment by Attila101498** [comment]
@melloware: Thank you very much for your help, the monkeypatch works, so I can invoke the Primefaces context menu by pressing Shift+F10.

**Comment by melloware** [comment]
Nice thanks for testing @Attila101498 !
