### ISSUE TITLE
selectCheckboxMenu: Validation error message use component id instead of label

### ISSUE THREAD

**Issue by Sun8642** [primefaces/primefaces#12314]
### Describe the bug

When there is a validation error (e.g.: required is true, but nothing was checked), the start of the error message will display the selectCheckboxMenu identifier instead of using the label of another component referring to the selectCheckboxMenu.

E.g.:
<p:outputLabel value="Cities:" for="@next"/>
<p:selectCheckboxMenu id="multiple" required="true" ..../>

When validation fails, the message displayed is: 
form:multiple: Validation Error: Value is required.

Instead of: 
Cities: Validation Error: Value is required.

### Reproducer

[primefaces-test.zip](https://github.com/user-attachments/files/16309444/primefaces-test.zip)
1. Go to http://localhost:8080/
2. Click on the save button

You can see that the error message of the selectCheckboxMenu is using the id instead of the label

### Expected behavior

The label is used instead of the id

### PrimeFaces edition

None

### PrimeFaces version

14.0.2

### JSF implementation

All

### JSF version

2.3

### Java version

17.0.6

**Comment by melloware** [comment]
Thanks for the reproducer i will investigate!

**Comment by melloware** [comment]
OK caused by: https://github.com/primefaces/primefaces/issues/9403

I am working on fix to make sure this use case and 9403 still work.
