### ISSUE TITLE
Remember to update Vdldoc to version 2.x when PrimeFaces moves to Java EE 7 / JSF 2.2

### ISSUE THREAD

**Issue by BalusC** [primefaces/primefaces#1231]
Currently PrimeFaces still uses [Vdldoc](http://vdldoc.omnifaces.org) 1.1 to generate [tag documentation](http://www.primefaces.org/docs/vdl/). Vdldoc 1.x is not compatible with `xmlns.jcp.org` namespaces of Java EE 7 / JSF 2.2. In case PrimeFaces advances to Java EE 7 / JSF 2.2, it's necessary to upgrade Vdldoc to at least version 2.0 (current latest version is 2.1).

Just in case, Vdldoc 2.x is still backwards compatible with older `java.sun.com` namespaces. So updating in advance won't harm.

**Comment by tandraschko** [comment]
I think we have to support JavaEE6 for the next years.
But as you said, we should be able to upgrade it without destroying something?

**Comment by BalusC** [comment]
Yes, it is backwards compatible. It won't touch tagfiles anyway, just read and parse them.

**Comment by tandraschko** [comment]
@cagataycivici how we generate the vdldoc? I can't see the dependency in the pom.

**Comment by Rapster** [comment]
Using CLI?

**Comment by melloware** [comment]
@mertsincan @tandraschko I think we should make this vdldoc change for 7.0.  I would say JSF 2.2 and 2.3 are becoming more prevalent than 2.0/2.1 and BalusC says this is backward compatible.  I can see in the Elite releases the VDLDOC is being generated I just don't see how.  It must be something internal @mertsincan does with his build script?

**Comment by mertsincan** [comment]
> @cagataycivici how we generate the vdldoc? I can't see the dependency in the pom.

> It must be something internal @mertsincan does with his build script?
- Yes, I wrote a build script to provide elite-release.zip. Please see vdldoc commands used for 6.2.x;
```
   echo VDL for Core
   call java -jar vdldoc-2.1.jar primefaces-p.taglib.xml
   rename vdldoc core
	   
   echo VDL for Mobile
   call java -jar vdldoc-2.1.jar primefaces-pm.taglib.xml
   rename vdldoc mobile
   
   mkdir vdldocs
   move core vdldocs
   move mobile vdldocs
```
