### ISSUE TITLE
p:resetInput the same as f:resetValues?!

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12324]
if yes, we can remove p:resetInput

**Comment by melloware** [comment]
Interesting: https://docs.oracle.com/javaee/7/javaserver-faces-2-2/vdldocs-facelets/f/resetValues.html

it specifically calls out that it doesn't walk into children which is exaclty the bug

> Evaluates to Collection<String>. The clientIds of components that will be passed to UIViewRoot.resetValues(). The identifiers must be space delimited. Note: do not use any of the @ keywords such as @form or @this with this tag because UIViewRoot.resetValues() does not descend into the children of the listed components.

**Comment by jepsar** [comment]
Hmm.. we are on JSF 2.3 and it's not offered in the code completion nor recognized. This might be a NetBeans thing though.

<img width="690" alt="Screenshot 2024-07-26 at 15 24 12" src="https://github.com/user-attachments/assets/ce08dda8-8138-47df-ab1a-276d7bbc1b0c">

**Comment by jepsar** [comment]
I just tried (ignoring NetBean's warning) and it gave me:

ERROR: Cannot invoke "javax.faces.view.facelets.TagAttribute.getObject(javax.faces.view.facelets.FaceletContext, java.lang.Class)" because "this.render" is null

**Comment by tandraschko** [comment]
you need to declare render attr

**Comment by DazzlingBob** [comment]
I always thought that <f:ajax> does not fully support Content Security Policy but <p:ajax> does. Therefore i always avoid the use of <f:ajax>. So using f:resetValues instead of p:resetInput could give CSP problems (maybe depending on the Faces implementation).

**Comment by tandraschko** [comment]
Thats actually completely unrelated, there is no client side code for p/f:resetValues

**Comment by DazzlingBob** [comment]
> Thats actually completely unrelated, there is no client side code for p/f:resetValues

Ok, CSP should be fine then! Changed one xhtml file from <p:resetInput target="myForm" /> to <f:resetValues render="myForm" /> in a project which uses mojarra-2.3.18 and the change works fine. Will do some more testing.

BTW: f:resetValues is not recognized by eclipse IDE.

**Comment by melloware** [comment]
`f:resetValues` must be missing from the taglib or Eclipse must not pick it up for some reason.  I have seen that before.

**Comment by tandraschko** [comment]
AFAIR we fixed this it in the specs that all child components will be visited in 4.0+
so we can actually remove p:resetInput after whe completely moved to jakarta

**Comment by tandraschko** [comment]
added it to: https://github.com/primefaces/primefaces/issues/11915

**Comment by DazzlingBob** [comment]
Just want to add to the discussion, i recently found that:
  
```
  <!-- does reset on validation error -->
  <p:commandButton value="Reset form PF1" process="@this" update="@form" action="#{testView.clean()}" immediate="true">
  <p:resetInput target="@form"/>
  </p:commandButton>
```
  
```
  <!-- does not reset on validation error (maybe depending on JSF implementation and version) -->
  <p:commandButton value="Reset form PF2" process="@this" update="@form" action="#{testView.clean()}" immediate="true">
  <f:resetValues render="@form" />
  </p:commandButton>
```
  
  So do not remove <p:resetInput>
