### ISSUE TITLE
Paginator PageLinks broken in Dialog Framework

### ISSUE THREAD

**Issue by Harwkx** [primefaces/primefaces#1232]
# Summary

A `p:dataTable` in a dialog Framework window doesn't display `{PageLinks}`. It doenst matter if you try it with `reflow` or the `paginatorTemplate` to get the element displayed.
## Example

Append a `reflow` or `paginatorTemplate` to the `p:dataTable` in `selectCar.xhtml` from [Primefaces Showcase Dialog Framework - Data](http://www.primefaces.org/showcase/ui/df/data.xhtml).
## Testing

Breaks in primefaces-5.3
Works in primefaces-5.2

**Comment by mertsincan** [comment]
Thanks for the detailed description. I'll review and get back to you.

**Comment by mertsincan** [comment]
We've added this css for responsive paginator;

```
/* Responsive */
@media (max-width: 640px) {
    .ui-paginator .ui-paginator-pages {
        display: none;
    }
}
```

it's by design. Therefore, I think you can change this css;

```
@media (max-width: 640px) {
        .test .ui-paginator .ui-paginator-pages {
               display: inline-block;
        }
}

<p:dataTable styleClass="test" ../>
```
