### ISSUE TITLE
U+FFFE and U+FFFF characters can block JSF applications by rendered as ajax response

### ISSUE THREAD

**Issue by halcsi19790320** [primefaces/primefaces#12331]
### Describe the bug

Theese characters are valid UTF-8 characters, but can cause error, if server send this value to browser as ajax response.
Browser's cannot parse theese characters.

Remove non-xml character from Request with converter, or default validator with RenderResponse patch?

[stackowerflow link](https://stackoverflow.com/questions/78770904/browsers-behavior-utf-8-page-with-extra-character-like-ufffe-error-by-ajax-x/78797369#78797369)

### Reproducer

```java
import java.io.Serializable;

import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;

@SessionScoped
@Named
public class Hello implements Serializable {

    private static final long serialVersionUID = -7474352426867236016L;
    
	private String property;

	public String getProperty() {
		return property;
	}

	public void setProperty(String property) {
		this.property = property;
	}
    
	public void ajax() {
		System.out.println("Property:" + property);
	}


}
```

```xml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    accept-charset="utf-8">
<h:head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</h:head>
<h:body>
    <h:form id="form1">
    <p:messages id="messages" showDetail="true" closable="true"></p:messages>
    <p:inputText id="propertyInput" label="Property" value="#{hello.property}" required="true" />

	<p:commandButton process="@form" update="@form" action="#{hello.ajax}"
                value="Click" />
	</h:form>
</h:body>
</html>
```

### Expected behavior

No error, if I paste any char to inputText and click ajax button.

### PrimeFaces edition

None

### PrimeFaces version

14

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

17

**Comment by BalusC** [comment]
Hold on. This might be a bug in Mojarra. It isn't reproducible when MyFaces is used in combination with PrimeFaces.

**Comment by halcsi19790320** [comment]
https://github.com/eclipse-ee4j/mojarra/issues/5463

**Comment by BalusC** [comment]
I fixed it in Mojarra side https://github.com/eclipse-ee4j/mojarra/pull/5465/files

**Comment by melloware** [comment]
Thanks!
