### ISSUE TITLE
TreeTable: Column with menuButton menuItem rendered not working

### ISSUE THREAD

**Issue by Maverick-501** [primefaces/primefaces#12330]
### Describe the bug

The p:menuButton column of a TreeTable doesnt get correctly updated based on the TreeNode data.

We want to rendered a menuItem option based on the data of the treeNode. In my repoducer I created a simplified version of this scenario where the TreeNode data is a boolean and the menuItem gehts rendered based on that boolean TreeNode data

```
<p:treeTable id="myTreeTable"
             value="#{testView.tree}"
             var="nodeData"
             nodeVar="node">
                <p:column id="nodeDataColumn"
                          headerText="Node data">
                    #{nodeData}       <- show the node data
                </p:column>
                <p:column id="actionColumn">
                    <p:menuButton id="menubutton">
                        <p:menuitem value="myMenuItem"
                                    rendered="#{nodeData}"/>     <- render menuitem based on node data
                    </p:menuButton>
                </p:column>
</p:treeTable>
```

With a simply commandButton I create a new Tree and flip the boolean in the single row.
```
public void test(){
        tree = new DefaultTreeNode<>();
        state = !state;
        var node = new DefaultTreeNode<>(state, tree);
}
```

### Reproducer

Go to the test page.
Observe that the "Node data" column shows **true** and the menuItem "myMenuItem" is shown when clicking on the menuButton.
Click the "Test" button.
Observe that the "Node data" column shows **false** and the menuItem "myMenuItem" is **still** shown when clicking on the menuButton.

14.0.2 repoducer where the issue is present
[primefaces-test-jakarta-14-0-2.zip](https://github.com/user-attachments/files/16390441/primefaces-test-jakarta-14-0-2.zip)
14.0.1 repoducer where the issue is **not** present
[primefaces-test-jakarta-14-0-1.zip](https://github.com/user-attachments/files/16390481/primefaces-test-jakarta-14-0-1.zip)

### Expected behavior

menuItem rendered according to nodeData boolean value after update.

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.2

### JSF implementation

MyFaces

### JSF version

4.0.2

### Java version

17

**Comment by melloware** [comment]
I think it's a duplicate. 

It's already fixed for upcoming 14.0.3.  Check the closed tickets for MenuButton.

**Comment by Maverick-501** [comment]
Oh sry, yes its the same. Tested it with the monkeypatch and it worked

**Comment by melloware** [comment]
Nice!  14.0.3 will be out by Monday.
