### ISSUE TITLE
TabView: add selection feature

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1233]
Since TabView supports DataModel add attribute `selection` to it similiar to `DataTable`.

This would make it easier to preselect the tab and reducing boiler-plate code.

For instance if selection is retrieved from a view-parameter via conversion we need additional we need now getter and setter for `activeIndex`.

Following is much more clean and reduces the need of primefaces specific code in bean:

```
<o:viewParam value="#{bean.selEntity}" converter="#{bean.entityConverter}"/>
<p:TabView selection="#{bean.selEntity}" var="varEntity" value="#{bean.entities}/>
```

My current workaround is:

```
<p:TabView activeIndex="#{bean.activeIndex}" var="varEntity" value="#{bean.entities}/>

public int getActiveIndex()
{
    return this.entities.indexOf(this.selEntity);
}

public void setActiveIndex(final int activeIndex) { }
```

**Comment by kukel** [comment]
I retrieve activeIndex from a view-parameter and it works great, for our usecases. Yes, yours is different and we have one like that to. This small 'small' one time workaround in my opinion does not outweigh the _addition_ of this making the component more complex AND make it more difficult for the normal usecase. Certainly not since you can just put this in a base class

**Comment by djmj** [comment]
Having activeIndex directly as view-param is good for intern or admin portals. But nothing for front-end user websites where SEO friendly URL's are required.

Its not really a problem but just a simplification for us developers. I either need a base class or have 4-5 places in our current app where i need those empty getter/setter combination. Even with a base class often not all cases are covered.

With `selection` attribute this would not be required and its more object oriented.
`Selection` and `activeIndex` just need to be mutual exclusive.

Its similar to this issue i posted: https://github.com/primefaces/primefaces/issues/462

Small changes which have potential to remove unnecessary java bean code for all primefaces developers and customers.

**Comment by melloware** [comment]
I believe this latest TabView fix to add MultiViewState solves the above issue: https://github.com/primefaces/primefaces/issues/5987

See PR: https://github.com/primefaces/primefaces/commit/1edbb201b3af20eaa12cdf20a0459076053511e1
