### ISSUE TITLE
Datatable: Keyboard accessibility 

### ISSUE THREAD

**Issue by rastislavvocko** [primefaces/primefaces#12336]
### Describe the bug

If I use in datatable atrributes  scrollable="true" or scrollWidth="{someNumber}%", then I can not with tab button jump on sort or filter items in table. But without these attributes it is working correctly. Please can you help me?

### Reproducer

1. open page where is datatable
2. start pressing tab button and watch how it is jumping in table's column header

### Expected behavior

When you jump in table with tab button, you should be navigate to sort and filter item for each column.
![Screenshot 2024-07-29 at 13 53 49](https://github.com/user-attachments/assets/3b3b2fea-fe71-4555-864c-91b51190dd86)
![Screenshot 2024-07-29 at 13 54 10](https://github.com/user-attachments/assets/2c731815-c066-4d66-af4f-49a2c9d964c1)

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.4

### Theme

Freya

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

17.0.7

**Comment by melloware** [comment]
@rastislavvocko is your PF version correct 11.0.4?   If so have you tried 14.0.3?

**Comment by melloware** [comment]
Actually @rastislavvocko its been like this for 9 years.

![image](https://github.com/user-attachments/assets/28f262e6-c28f-425a-9c86-18215a039163)

Its because your columns are `sortable` they get a tabindex="0" so they can be sorted with the keyboard.

**Comment by rastislavvocko** [comment]
Thank you for response. I tried to use sortable attribute and it is working, but filter columns still have tabindex="-1" and I can not jump there with keyboard. Thank you

**Comment by melloware** [comment]
Yes filter only get `tabindex="-1"` but tabbing should work between the filter inputs as they have tabindexes no?

**Comment by rastislavvocko** [comment]
No, it is not working for me, I can not get in filter with tab.

**Comment by melloware** [comment]
@rastislavvocko see my example here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/filter.xhtml

Its working fine you can TAB and SHIFT+TAB through the filters.
