### ISSUE TITLE
MenuButton placed in wrong position after 14.0.3 release

### ISSUE THREAD

**Issue by AlessandroBori** [primefaces/primefaces#12349]
### Describe the bug

After fixing issue n. #12286: MenuButton menu should be attached to trigger not body

if a menu button is placed into a small scrollable container (in my example an accordion panel) the menu lays in the wrong position

### Reproducer

[primefaces-test-master.zip](https://github.com/user-attachments/files/16423663/primefaces-test-master.zip)

### Expected behavior

Until 14.0.2 the menu was attached to body, so its absolute position was really absolute. Now if the container has a relative position it does not pop up in the right way. 
MenuButton has an appendTo attribute and it seems being ignored to me, but the actual default behaviour broke some common use cases.

Probably use position fixed + the right calculation for top and an accurate recalculation in case of scrolling (top - offset) can be the right way...
 

### PrimeFaces edition

Community

### PrimeFaces version

14.0.3

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

11

**Comment by melloware** [comment]
@AlessandroBori thanks for reporting you are right.  I missed this and now I have tested your scenario with `appendTo="@(body)"` and the previous ticket https://github.com/primefaces/primefaces/issues/12286 and both are working with my PR.

**Comment by mkomko** [comment]
@melloware Is a MonkeyPatch possible for this issue? Looking at the PR I'm not sure. Should we revert to 14.0.2 for the time being?

**Comment by melloware** [comment]
Yep no simple MonkeyPatch.

**Comment by mkomko** [comment]
@melloware I don't think this is fixed. I just tried the current 14.0.4-SNAPSHOT (locally built) with our application and with this reproducer, and the MenuButton popup is still not visible.

The same thing happens when using 14.0.2 and adding the MonkeyPatch to fix this issue: https://github.com/primefaces/primefaces/issues/12286

**Comment by AlessandroBori** [comment]
@mkomko i think we should use appendTo="@(body)" attribute, by default is changed the default element where menu is attached.
The patch is correct (it was ignoring that attribute) but maybe switching from position: absolute to position: fixed in CSS will make the parent element irrelevant (in the UI scenario of course)

**Comment by melloware** [comment]
let me test again I tested against both reproducers the other day.

**Comment by melloware** [comment]
@AlessandroBori with your reproducer and `appendTo="@(body)"` it looks like this.

![image](https://github.com/user-attachments/assets/010f9730-2c1e-402d-8509-311322c28e4b)

**Comment by melloware** [comment]
@mkomko i also tested #12286 and its also working.  So can one of you put together a reproducer showing me what is wrong because both test cases i have are working?

**Comment by AlessandroBori** [comment]
i think the point is we all need to specify _appendTo="@(body)"_ wherever we found the misplacement

**Comment by melloware** [comment]
Let me do some more research and see what I can do.

**Comment by mkomko** [comment]
> i think the point is we all need to specify _appendTo="@(body)"_ wherever we found the misplacement

Yes that works, thank you! I didn't expect a breaking change like this in a minor release though.

**Comment by melloware** [comment]
OK I fixed it and tested all regression scenarios: https://github.com/primefaces/primefaces/pull/12386   Body is now the default.
