### ISSUE TITLE
Chart: Update showcase examples to chartjs-java-model 2.0.1

### ISSUE THREAD

**Issue by persapiens** [primefaces/primefaces#12341]
### Describe the bug

[Chart Page of PrimeFaces Showcase ](https://www.primefaces.org/showcase/ui/chart/bar.xhtml) uses chartjs-java-model library 1.5.0.

Please update the ChatView.java example to use [chartjs-java-model 2.0.1](https://github.com/xdev-software/chartjs-java-model/releases/tag/v2.0.1).

The main changes will be related to scales at ChartView.java.

### Reproducer

If you use chartjs-java-model library 2.0.1, ChartView.java of chart showcase example does not compile.

For example, BarScale class does not exist anymore. Line 168 of ChartView.java uses it.

### Expected behavior

ChartView.java example should work with latest stable chartjs-java-model 2.0.1.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
Its done in `main` but not deployed ye but you can see it in action here alreayd updated with my Quarkus Faces showcase which uses 2.0.1: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/chart/bar.xhtml

**Comment by persapiens** [comment]
Super fast response!!!
Thanks again @melloware
