### ISSUE TITLE
TabView: allow anchor in title

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1234]
For SEO and user enhancement I want an anchor tag `<h:link>` within facet `title` in a `TabView` which is not really supported. 

I don't need to switch tabs with javascript, a GET request is more SEO-friendly and better bookmarkable for users.

```
<p:tabView var="varEntity" value="#{bean.entities}" activeIndex="#{bean.activeIndex}">
    <p:tab>
        <f:facet name="title">
            <h:link value="#{varEntity.name}" outcome="#{view.viewId}">
                <f:param name="foo" value="#{varEntity}" />
            </h:link>
        </f:facet>
```

This results in nested anchors since TabView itself renders an anchor by default.

```
<a tabindex="-1"><a href="...">name</a></a>
```

Since nested anchors are not allowed modern browsers just show both anchors side by side (see Firebug) which leads to large empty space the empty anchor occupies which does not looks good.

```
<a tabindex="-1"></a>
<a href="...">name</a>
```

My current workaround is:

```
.hide-first-anchor a:first-child { display: none; }
<p:tab titleStyleClass="hide-first-anchor">
```

**Comment by melloware** [comment]
@djmj So you are using TabView not as an AJAX tabview but to navigate to different outcomes?  Why not use TabMenu as that is what its for?  I guess I don't understand the use case here?

**Comment by melloware** [comment]
To me since this use case doesn't really make sense for the AJAX tabview and a workaround was provided I can't see a lot of users wanting this functionality. Closing this ticket.

**Comment by djmj** [comment]
@melloware Because _p:tabMenu_ does not has an optional child panel and i want to keep a consistent style between _p:panel_ and _p:tabView_ in our websites which _p:tabMenu_ does not allow. So we only render the content of the currently active tab if we are using GET requests. Further we either render a panel or a tabView depending on dynamic content (tabs). 

Yes the workaround is working but looks more like a hack since implementation specific and depends on browser handling invalid html. A real solution could be an _outcome_ attribute.


**Example:**

- News / Blog page at: https://www.deloma.de/Agentur/news 
- Shop category page, here we either render panel or tabView in case additional content is available - https://www.getraenkelieferant-duesseldorf.de/c/Wasser-Schorlen

**Use cases / requirements:**

- tabView that renders as a panel aslong there is only a single tab _(workaround: renders a panel or a tabView depending on content using a wrapper composite)_
- tabView with - SEO friendly GET links _(either use above workaround or we render some duplicate GET links at the bottom of the first page for google crawler)_


**Alternate solution**

Allow a simple optional container content to use it as a _panel / facet_ for _p:tabMenu_

**Comment by melloware** [comment]
If I understand you correctly and from your examples you wants Tabs but you want the panel underneath it to look like the Panel is attached to the tab the way TabView does.

We have this exactly your same scenario and we use TabMenu and a little CSS to draw the TabMenu and panel to make it look like the panel is attached to the Tab.  So really all you need is a little bit of CSS and not all these hacks with TabView using it the way it's not meant to be used.

**Comment by djmj** [comment]
Thanks for your comment and i will have a look at it. Next year we will modernize our shops with a new template of yours anyway so i will keep this in mind.
