### ISSUE TITLE
DataTable: Paginator RowsPerPageDropdown not working in Safari 16.5

### ISSUE THREAD

**Issue by D2-C2** [primefaces/primefaces#12359]
### Describe the bug

The Rows per page drop down isn't working/updating properly when using Safari 16.5 (macOs Ventura).  When the value is changed, the number of rows in the table doesn't change.  The paginator template is updated except for the rowsPerPageDropdown at the bottom.  Noticed this behaviour while testing datatables using Primefaces 13.0.5 but it's also happening in the PrimeFaces showcase as well.
![primefaces1](https://github.com/user-attachments/assets/a784ada2-026b-4062-9a49-874538e35fa8)

### Reproducer

1. In Safari 16.5, go to https://www.primefaces.org/showcase/ui/data/datatable/paginator.xhtml
2. Change Drop down value from 10 to 5.

### Expected behavior

Rows would be reduced to 5 and both the top and bottom Rows per page drop down would be updated to 5.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

### Browser(s)

Safari 16.5 (macOS Ventura)

**Comment by D2-C2** [comment]
Yes, after the drop down is clicked I see the following errors:
[Error] Origin http://primefaces.org is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] XMLHttpRequest cannot load https://primefaces.org/showcase/ui/data/datatable/paginator.xhtml?jfwid=0297d due to access control checks.
[Error] Failed to load resource: Origin http://primefaces.org is not allowed by Access-Control-Allow-Origin. Status code: 200 (paginator.xhtml, line 0)

**Comment by melloware** [comment]
interesting it seems like some kind of stricter Safari checking that Chrome/Firefox must not be doing?    do you get the same error with your local setup of 13.0.5?

**Comment by melloware** [comment]
@D2-C2 i had a friend try and he said he got the issue too but then did a Hard refresh of his page and now its working for him in Safari 16.5

**Comment by melloware** [comment]
Sorry he does get this on first page load:

![image](https://github.com/user-attachments/assets/209ccfb0-8c5f-4a74-b10e-1fbff5192cbb)

**Comment by melloware** [comment]
@D2-C2 can you try this URL from Safari and see if it has the same issue: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/paginator.xhtml

???

**Comment by D2-C2** [comment]
I tried the link you provided and I don't see any errors in the javascript console and the number of rows in the datatable is adjusted properly.  The only remaining problem is the number displayed in the other drop down. For example, I changed the default value of 10 to 5 in the top paginator but the bottom paginator still shows 10.
![image](https://github.com/user-attachments/assets/2ad8f261-7570-4ac3-8782-f7baa23d843b)

If I click the bottom dropdown (incorrectly showing 10) to show the values, it is set to the proper value of 5.
![image](https://github.com/user-attachments/assets/3798f213-acec-402c-9df5-092c0153dedf)

**Comment by melloware** [comment]
OK so that is good.  SO my showcase is running the same code but on a different network.  I think the issue is with Safari and how it evaluates CORS headers and the PrimeFaces showcase is probably through a Proxy with subdomains or something that Safari doesn't like.

**Comment by melloware** [comment]
@D2-C2 from another user who just tested it

> I'm not seeing what he is seeing. Both my combos update properly. It could be a timing/network loading thing on his side depending on where he is located and hitting your site. I saw a quick instance where I selected a value but the page didn't update right away, then did after a second or two.

**Comment by D2-C2** [comment]
Interesting.  I've tried a bunch more times and it's usually not updating the second dropdown.  It did work on one try.

**Comment by melloware** [comment]
He is also on Safari 17.5 on a nice machine if that makes a difference.

**Comment by D2-C2** [comment]
I tried Safari 17.3 using BrowserStack and both dropdowns get updated properly.  So, correct me if I'm wrong, this is caused by a problem with how Safari 16.5 is handling CORS headers, and there is nothing wrong and no way to fix it on PrimeFaces side?

**Comment by melloware** [comment]
Correct there is nothing for PrimeFaces to fix.    This is a Safari "bug".  I have tested on Chrome and Firefox without issue on Ubuntu and Windows as well.

**Comment by D2-C2** [comment]
Thank you.

**Comment by goldyrishi** [comment]
We are also facing the  similar issue. Issue apears in Chrome, Edge and fIreFox browsers as well. I think the issue is not related to browser.
I am using Apache MyFaces 2.2, Primefaces 13.10.10 application is deployed on WAS 8.5

I have also raised below issue in GitHub community:
https://github.com/primefaces/primefaces/issues/12396

**Comment by melloware** [comment]
@goldyrishi i cannot reproduce the issue as you have seen in the thread above and in both PF showcase and QuarkusFaces showcases i can't reproduce in any browser.
