### ISSUE TITLE
SelectOneMenu: Add official API for manipulating selectOneMenu on client side

### ISSUE THREAD

**Issue by musttafayildirim** [primefaces/primefaces#12364]
### Describe the bug

When we intervene in the SelectOneMenu component on the client side and then init the component, the panel side opens and then closes immediately. The relevant test project has been added. This process was working properly in PrimeFaces version 8, but it stopped working properly with PrimeFaces 10.

### Reproducer

Go to localhost:8080
Click on SelectOneMenu
See error

[PrimeFacesTest.zip](https://github.com/user-attachments/files/16452830/PrimeFacesTest.zip)

### Expected behavior

When SelectOneMenu is initialized after manual manipulation, the panel opens, the user selects the desired item, and then the panel closes.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.3

### JSF implementation

Mojarra

### JSF version

2.3.21

### Java version

11

### Browser(s)

Chrome

**Comment by melloware** [comment]
Thanks for creating a reproducer. That should help.

**Comment by melloware** [comment]
@musttafayildirim can you try mine I think I fixed your reproducer.

[pf-12364.zip](https://github.com/user-attachments/files/16459973/pf-12364.zip)

**Comment by musttafayildirim** [comment]
Thank you so much @melloware, solved my problem.
