### ISSUE TITLE
Menu Item: Double state ui-state-hover and ui-state-active | v14.0.1+

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#12378]
### Describe the bug

Breaking change from PrimeFaces 14.0.0 to 14.0.1

A menu item has both css classes at the same time: `ui-state-hover` and `ui-state-active`

### Reproducer

See PrimeFaces Showcase

![grafik](https://github.com/user-attachments/assets/9164a8b6-0949-4535-9b35-70431186d7d2)

### Expected behavior

There should be only a `ui-state-hover` css class

### PrimeFaces edition

None

### PrimeFaces version

14.0.1

### Theme

irrelevant

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

all

**Comment by melloware** [comment]
Let me look at this.  This was related to Accessibility and keyboard access of menus.

**Comment by melloware** [comment]
@RohdeSchwarz-SDC in your screenshot of the Menu being displayed from a button the behavior of having both hover and active is NOW correct based on ARIA specs.

See: https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-links/

The spec says the first element of the popup must get focus and be active as for visually impaired its the currently selected item which gets read by the screen reader.  Then as you navigate with arrow keys it follows.

so theoretically it is the `ui-state-active` menu item.

**Comment by melloware** [comment]
I did submit a PR to only add `ui-state-hover` when hovering with the mouse but the point above still stands as far as popup modal menus go.

**Comment by RohdeSchwarz-SDC** [comment]
This is a useful improvement, thanks 👍
