### ISSUE TITLE
p:chart documentation and showcase need update for 14

### ISSUE THREAD

**Issue by BalusC** [primefaces/primefaces#12377]
### Describe the bug

Trying to use the new charts in PrimeFaces 14, however having a hard time to get started.

http://www.primefaces.org/showcase/ui/chart/pie.xhtml -- code doesn't compile, PieChart is the wrong class and PieData and PieDataset cannot be found, no imports in code snippet,  unclear what the correct replacement is

https://primefaces.github.io/primefaces/14_0_0/#/components/charts -- contains deprecated code as examples

I can eventually figure out it but I imagine this is inconvenient for starters.

### PrimeFaces edition

None

### PrimeFaces version

14.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Great minds think alike: https://github.com/primefaces/primefaces/issues/12341

I have a fully working version running here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/chart/bar.xhtml aginst XDEV 2.0.1

**Comment by BalusC** [comment]
Right, it's compilable after adding
```xml
        <dependency>
            <groupId>software.xdev</groupId>
            <artifactId>chartjs-java-model</artifactId>
            <version>2.0.1</version>
        </dependency>
```
this wasn't terribly clear from showcase.

**Comment by melloware** [comment]
Got it!  also all our links point here to chart now and not chart(s) https://primefaces.github.io/primefaces/14_0_0/#/components/chart

**Comment by BalusC** [comment]
Thanks :)

**Comment by melloware** [comment]
also in our next version the showcase shows the imports as well..

![image](https://github.com/user-attachments/assets/d25183fc-896a-4d4e-b68e-5d3049853472)
