### ISSUE TITLE
DatePicker: define readonly handling

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12385]
Currently if the datepicker is marked as readonly=true, you can still open the popup and choose a date
i dont think a popup should be shown?

@melloware wanna take care of this?

**Comment by melloware** [comment]
Yep I will do this one.

**Comment by tandraschko** [comment]
currently it also triggers a ajax request on selection, seems like readonly isnt implemented really

**Comment by melloware** [comment]
agreed. Looking at it now.

**Comment by melloware** [comment]
OK got to the bottom of this.  There are two properties `readOnly` and `readOnlyInput`.  These are implemented in legacy jQuery calendar.  `readOnlyInput` means you can use the keyboard to enter dates but can still use the popup to select dates.  `readonly` truly means readonly and works in jQuery Calendar and was just never implemented in DatePicker!

So I am submitting a PR to respect `readonly="true"`
