### ISSUE TITLE
Datatable: RowExpansion collapsed by default, set all attributes to null when submitting the complete form.

### ISSUE THREAD

**Issue by nokiajavi** [primefaces/primefaces#12393]
### Describe the bug

Datatable: RowExpansion collapsed by default, set all attributes to null when submitting the complete form.

When I have a datatable with a column p:rowToggler and a rowexpansion collapse by default and inside it I have some editable form elements such as a selectonemenu or input text, all the elements are nullified when submitting the form without having expanded the rows. 

That is, even if the values of the inputsText, seleccOneMenu etc, are set on the server (they are not null when the screen is loaded), if the table rows are not expanded, when the form is submitted with the collapsed table rows, all elements of all inputText, seleccOneMenu etc, are set to NULL, despite including the processing of the entire form or the table partially.

Instead, as soon as the row is expanded, the values are already set correctly on the server when the form is submitted.

In this animated gif, I show how when I load the app, without expanding the rows and submit the form, on the server the values are set to ‘empty string’, despite being set when loading the screen, then I refresh the screen to reset the view and expand the rows and submit the form to the server and it is verified that in that case the data is submitted correctly.

![BugPrimefaces](https://github.com/user-attachments/assets/b845d513-d599-4269-968e-f385ef99b241)

Example code:
[primefaces-test-7.0.zip](https://github.com/user-attachments/files/16475610/primefaces-test-7.0.zip)

### Reproducer

1. Create a list of one object with a couple of fields of any type, String for example.
2. Initialise the list with at least 1 value with those fields filled in.
3. Create a p:dataTable with a rowTogler and a rowExpansion columns.
4. Put a selectOneMenu with several values, one of them must correspond to one of the attributes that have been created in the class.
5. Put a commanButton that sends the complete form.
6. Without expanding the table, press the button and send the form.
7. The preset values in the attributes of the list object have been set to NULL or ‘empty string’, depending on the configuration in web.xml.
8. Repeat the process, but this time expand the rows before submitting the form.
9. The values that previously existed when the screen was loaded are maintained.

### Expected behavior

When processing the form or table, the contents of the rowexpansion should also be processed even if they are not in order not to set the values to null on the server.

I imagine that for performance or another reason, data is not preloaded and causes them to be set to null, it is not exactly the treatment of tabviews with dynamic tabs, but something similar.

Thank you very much for all your work and help.

### PrimeFaces edition

Community

### PrimeFaces version

7.0

### Theme

Default

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

17

### Browser(s)

All browser

**Comment by melloware** [comment]
Thanks for reporting but I don't think this is a valid use case for row expansion.  The row expansion is dynamic for performance so if you have 1000 rows we don't render 1000 row expansions we only render the ones you have open.  I don't think it is a good Ui/UX for data entry and would not recommend this. 

@Rapster @tandraschko @jepsar feel free to disagree but this doesn't feel like something PF should fix. 

@nokiajavi i think you might want to rethink your UI instead.

**Comment by nokiajavi** [comment]
Thank you very much, I already imagined that it would be due to performance, without problems, I totally agree with you, I will leave everything expanded again, because for my cases on the web I only have 3 rows maximum in the table, and I do not It affects performance or else I will change the interface to another component with p:panel or tabview.

Thank you very much for everything as always @melloware

**Comment by melloware** [comment]
No problem i updated the ticket labels!  Good luck!
