### ISSUE TITLE
Add smooth rendererOption to LineChartSeries

### ISSUE THREAD

**Issue by ivolucas** [primefaces/primefaces#1239]
The lib jqplot has an option to generate chart lines with smooth lines. The graphics produced in this way are aesthetically more pleasant most of the time.

LineChartSeries may be slightly changed to support this option.

[Example](http://www.jqplot.com/deploy/dist/examples/smoothedLine.html)

**Comment by tandraschko** [comment]
Why not just use the extender?
If you provide a PR, please don't destory the formating like in your commit.

**Comment by ivolucas** [comment]
The problem with the formatting was due to file have the line termination with \n while all the others I had seen so far be \r\n

Sorry about that.

**Comment by christophenoel** [comment]
There is a mistake in the fix (see line from the github). Smooth should be true if smoothLine is true.
Note in many scientific domains, smooth is an undesired feature.

```
 if(showLine){
            writer.write(",rendererOptions:{smooth: true }");
        }
```

**Comment by tandraschko** [comment]
nope, it's fine in our github: https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/model/chart/LineChartSeries.java

**Comment by christophenoel** [comment]
I don't know what you mean by it's fine.
The line should be replaced by:

```
 if(showLine){
             writer.write(",rendererOptions:{smooth: "+this.isSmoothLine()+" }");
         }
```

but sorry my previous comment was not clear.

**Comment by tandraschko** [comment]
check the link i posted, the logic is correct there.

**Comment by christophenoel** [comment]
I'm very sorry. I indeed looked at an older version. Please apologize !

**Comment by tandraschko** [comment]
np :) but it's always better to check the current git master before (also when creating issues)
