### ISSUE TITLE
FileUpload: Parallel upload `sequential=false` not working within ui:repeat

### ISSUE THREAD

**Issue by mstichweh** [primefaces/primefaces#12404]
### Describe the bug

When the fileUpload component is used in multiple mode with sequential = false within ui:repeat, the handler is called multiple times for the same file.

If for example the following files were selected for upload:
- file1
- file2
- file3
- file4
- file5

The handler method is called for example as follows:
- file3
- file3
- file3
- file5
- file5

So the quantity is correct, but some files are not uploaded and others are uploded multiple times.

If the ui:repeat around the uploader is removed, everything works fine.

### Reproducer

HTML:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h:form id="frmTest">
		<ui:repeat value="#{testView.documentTypes}" var="documentType">
			<h1>#{documentType}</h1>
			<p:fileUpload listener="#{testView.handleFileUpload}" mode="advanced"
				      multiple="true" dragDropSupport="true" auto="true" sequential="false"
				      process="@this" update="@none" />
		</ui:repeat>
	</h:form>

    </h:body>
</html>
```

Handler Bean:

```
@Data
@Named
@RequestScoped
public class TestView implements Serializable
{
    public String[] getDocumentTypes()
    {
        return new String[] { "Type1", "Type2" };
    }

    public void handleFileUpload( FileUploadEvent event )
    {
        System.out.println( "Handle uploaded file:" + event.getFile().getFileName() );
    }
}
```

### Expected behavior

The upload handler should be called for each selected file, also if the component is embedded into ui:repeat.

### PrimeFaces edition

None

### PrimeFaces version

14.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

**Comment by melloware** [comment]
Maybe I am doing something wrong but I can't reproduce:
[pf-12404.zip](https://github.com/user-attachments/files/16513440/pf-12404.zip)

`mvn clean jetty:run` and navigate to http://localhost:8080/

I grabbed multiple files and uploaded and both files came through not duplicated or anything.

```
Handle uploaded file:quarkus-faces-quarkus-faces_2024-08-05T11_59_19.564Z.txt
Handle uploaded file:74460259961__2D96ADA8-7A44-46EE-91A9-38081554C921.heic
```

What am I doing wrong?

**Comment by mstichweh** [comment]
Tried it with your zip and `mvn clean jetty:run`, still the same problem. I clicked on the "Choose" button and selected two files. The handler was called two times but for the same file.

I'm using `openjdk-21.0.2_macos-x64` on a Mac and tested with Chrome and Firefox.

**Comment by melloware** [comment]
weird my setup is as follows.  I upload 2-3 files and they are uploaded in proper order

```
Apache Maven 3.9.7 (8b094c9513efc1b9ce2d952b3b9c8eaedaf8cbf0)
Maven home: C:\tools\apache-maven-3.9.7
Java version: 17.0.11, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12800HX
    Memory: 12.62 GB / 31.70 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

**Comment by melloware** [comment]
OK tested again with Chrome it happens and I get the same file name with Firefox it works.

```
Firefox 128.0.3
Chrome 127.0.2651.74
```

**Comment by melloware** [comment]
weird now its working for me in Chrome and Firefox.  I have only seen it happen once with Chrome.

**Comment by mstichweh** [comment]
With `sequential="true"` it always works fine

**Comment by melloware** [comment]
OK so at least you have a workaround.  I assume this is somehow mult-thread related to async AJAX requests when sequential="false".

**Comment by melloware** [comment]
OK here is the original ticket explaining why sequential="false" is dangerous: https://github.com/primefaces/primefaces/issues/66

**Comment by melloware** [comment]
also when it does happen if I look at the AJAX requests they are sending the correct data.  So something is getting mixed up on the server side.

**Comment by melloware** [comment]
@mstichweh do me a favor try this version but start it with `mvn clean jetty:run -Pmyfaces23`

[pf-12404.zip](https://github.com/user-attachments/files/16514941/pf-12404.zip)

Can you make it happen there?

**Comment by mstichweh** [comment]
It works for every test, the handler was called correctly for all files

**Comment by melloware** [comment]
ok then its a Mojarra bug with UI:Repeat I feel.  Feel fee to open a Mojarra Ticket and attach the reproducer provided here: https://github.com/eclipse-ee4j/mojarra/issues
