### ISSUE TITLE
All-themes 1.0.10 no longer available (Maven)

### ISSUE THREAD

**Issue by janus141** [primefaces/primefaces#12405]
### Describe the bug

This dependency
 ```
		<dependency>
			<groupId>org.primefaces.themes</groupId>
			<artifactId>all-themes</artifactId>
			<version>1.0.10</version>
		</dependency>
```
suddenly results in a 
`[ERROR] Failed to execute goal on project XYZ: Could not resolve dependencies for project org.XYZ:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.primefaces.themes:all-themes:jar:1.0.10: Failed to read artifact descriptor for org.primefaces.themes:all-themes:jar:1.0.10: Failure to find org.primefaces.themes:themes-project:pom:1.0.10 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

The new version `1.0.11` works fine. I noticed this behavior today, after returning from vacation. Could this be related to the apparent changes in the folder structure that took place on 2024-07-24 20:22? (See time stamps on https://repo.maven.apache.org/maven2/org/primefaces/themes/all-themes/)

### PrimeFaces edition

Community

### PrimeFaces version

10.0.0

### JSF implementation

Mojarra

### JSF version

2.4

### Java version

1.8

**Comment by melloware** [comment]
@janus141 no you can read all about it here: https://github.com/orgs/primefaces/discussions/2382

Basically PrimeFaces Repository was taken down so now you need to use Maven Central.  I took the last known version from the retired `legacy-themes` project and pushed them to Maven Central as 1.0.11 so they are available to everyone without needing a custom PrimeFaces repo.

You should remove this from your `pom.xml` as its no longer needed.

```xml
<repositories>
        <repository>
            <id>primefaces</id>
            <name>PrimeFaces Maven Repository</name>
            <url>http://repository.primefaces.org</url>
            <layout>default</layout>
        </repository>
</repositories>
```
