### ISSUE TITLE
DatePicker: mask can lead to too much recursion and unexpected mask behaviour

### ISSUE THREAD

**Issue by raphisuter** [primefaces/primefaces#12428]
### Describe the bug

We discovered a bug that will lead to unexpected behavior with the datepicker component with a mask active and errors in the web developer console coming from inputmask.js

See the datepicker below:
`<p:datePicker id="cldDate" value="#{testView.localDate}" pattern="dd.MM.yyyy" mask="true" placeholder="dd.mm.yyyy" showIcon="true" showOnFocus="false" autocomplete="off" />`

Bean
`@Getter
@Setter
private LocalDate localDate;
`

We still have PF 13.0.8, I updated to 13.0.10 and the errors still occurred as well as in the primefaces-test project (branch jakarta -> mvn clean jetty:run -Pmyfaces30)

### Reproducer

[pf-12428.zip](https://github.com/user-attachments/files/16547836/pf-12428.zip)
[pf-12428-2.zip](https://github.com/user-attachments/files/16549323/pf-12428-2.zip)

**Error 1 (Uncaught InternalError: too much recursion)**
1. Click into datePicker input field
2. write 20.11.2024
3. lose focus by clicking anywhere else
4. Point the cursor to the start of the input field
5. type 1
6. after some seconds, the input changes to 12.01.1202 and there is an error in the web developer console 
![grafik](https://github.com/user-attachments/assets/7b88299d-6a49-4ae4-914f-a8f5a022ff96)

**Error 2 (mask error)**

1. Click into datePicker input field
2. write 20.10.2024
3. Mark day part with mouse
4. Write 1
5. Observe the result -> sometimes it writes 01 directly in the day part, leading to the user continuing to write and putting in an invalid date, sometimes it writes 1 and shifts all other characters to the left, resulting in 11.02.024_

**following errors**
After error 1 occurred, the mask behaves weird and unpredictable, but this seems to be a follow up issue of the mask being corrupted I guess.

### Expected behavior

the mask to behave as intended

### PrimeFaces edition

None

### PrimeFaces version

13.0.10

### JSF implementation

MyFaces

### JSF version

3.0.2

### Java version

JDK 11

**Comment by tandraschko** [comment]
can you try 14.x? we dont support 13.x anymore in the community.

**Comment by raphisuter** [comment]
hi @tandraschko 

I updated the primefaces-test project locally to PF 14.0.4 and the errors still exists.
![grafik](https://github.com/user-attachments/assets/1b21dc1a-44d0-4217-a84a-f81232fab256)

for us to update to PF 14 will not be possible in the next weeks, therefore we would really appreciate a monkeypatch (if it is easely backward compatible).

**Comment by melloware** [comment]
I will take a look.

**Comment by melloware** [comment]
Runnable Reproducer: [pf-12428.zip](https://github.com/user-attachments/files/16547836/pf-12428.zip)

**Comment by melloware** [comment]
I reported your Error 2 to InputMask here: https://github.com/RobinHerbots/Inputmask/issues/2813

Go upvote that ticket please.  It was easily reproducible with a simple CodePen: https://codepen.io/melloware/pen/zYVddzY

Error 1 I am still investigating.

**Comment by melloware** [comment]
All I know for Error 1 its this InputMask `blur` event causing the issue:

![image](https://github.com/user-attachments/assets/fffd826d-80cb-4ee5-ba84-df272f263db8)

If you delete that BlurEvent in the console and run your use case it works fine.

**Comment by melloware** [comment]
MonkeyPatch for Error 1:

```js
if (PrimeFaces.widget.DatePicker) {
  PrimeFaces.widget.DatePicker.prototype.applyMask = function() {
    if (this.cfg.inline || this.input.is('[readonly]') || this.input.is(':disabled')) {
      return;
    }
    var $this = this;
    if (this.cfg.mask) {
      var isAutoClear = (this.cfg.maskAutoClear === undefined) ? true : this.cfg.maskAutoClear;
      var maskCfg = {
        placeholder: this.cfg.maskSlotChar || '_',
        clearMaskOnLostFocus: isAutoClear,
        clearIncomplete: isAutoClear,
        autoUnmask: false,
        showMaskOnHover: false,
        onBeforePaste: function(pastedValue, opts) {
          // GitHub #8319 issue with pasting mask
          // TODO: Remove if InputMask 5.0.8+ fixes the issue
          setTimeout(function() {
            $this.input.trigger("input")
          }, 20);
          return pastedValue;
        }
      };
      var pattern = /[mdyhs]/i;
      var isAlias = pattern.test(this.cfg.mask);
      if (isAlias) {
        maskCfg.alias = 'datetime';
        maskCfg.inputFormat = this.cfg.mask;
      } else {
        maskCfg.mask = this.cfg.mask;
      }
      this.input.inputmask('remove').inputmask(maskCfg);
      this.input.off("blur"); // GitHub #9259/#12428
    }
  }
}
```

**Comment by raphisuter** [comment]
Hi @melloware 
Thank you for your help, as always super fast🚀 
I tested the monkeypatch and was still able to get the stacktrace in the console from error 1.

xhtml
`<p:focus />
<p:datePicker id="cldStartDate" value="#{testView.localDate}" pattern="dd.MM.yyyy" mask="true" styleClass="cal"
                        placeholder="dd.mm.yyyy" showIcon="true" showOnFocus="false" autocomplete="off" />`
bean
`@Getter
	@Setter
	private LocalDate localDate = LocalDate.of(2018,3,11);`
Steps to reproduce:

1. start to write 20.11.2024(first 1 will be substituted for a `.`
2. cursor will land befor year part and not jump over `.` (don't have to change the year)
3. navigating with arrow keys to front
4. press `1`
5. stack trace in the console

kind regards

**Comment by melloware** [comment]
Yep can repoduce with a CodePen: https://codepen.io/melloware/pen/bGProzd

Not a PF issue please report to InputMask team by creating a new issue

**Comment by raphisuter** [comment]
thank you

**Comment by melloware** [comment]
@raphisuter you and you company might want to consider clicking on his Donate button to offer financial incentive for him to investigate your issues...

![image](https://github.com/user-attachments/assets/4cec6fea-82ad-4b56-977b-1a74f6e7d957)

**Comment by raphisuter** [comment]
@melloware yeah sure, just sent the dev some love
