### ISSUE TITLE
ColorPicker: Required validation sets color back to previous value

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#12420]
### Describe the bug

If you use the colorPicker with required=true and provoke a validation error, the user will be informed that the value cannot be empty while a value is set in the component. In other components like inputText the value stays empty.

### Reproducer

[reproducer_1.zip](https://github.com/user-attachments/files/16521245/reproducer_1.zip)

1. Open the colorPicker
2. Press the Reset Button
3. Press the Button "Update"
4. Error Message gets shown, Value of the component gets reset to "#fafafa"
5. Clear the inputText below
6. Press the Button "Update"
7. Error Message gets shown, Value of inputText stays empty (expected behaviour)

### Expected behavior

As shown in the reproducer I think the colorPicker should stay empty after provoking the required=true just like the inputText.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### JSF implementation

MyFaces

### JSF version

2.3.10

### Java version

11

**Comment by melloware** [comment]
Thanks for reporting I will fix this as I know what the issue is.
