### ISSUE TITLE
InputNumber: Duplicate input occurs when pressing the Enter key after entering IME full-width characters

### ISSUE THREAD

**Issue by kazunori-iwasaki-0227** [primefaces/primefaces#12427]
### Describe the bug

If you enter a number with the IME mode set to full-width, change it to half-width using the F10 key, and then press the Enter key, duplicate input will occur.

### Reproducer

1. Go to https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml?jfwid=23111
2. Focus on “Positive”
3. Change IME mode to full-width
4. Enter "1111" in full-width numbers.
5. Press the F10 key to change to half-width numbers (at this point, a comma is displayed and the input appears to be completed, "1,111")
6. Press the Enter key and the entered content will be added again "1,111 → 11,111,111"

![Animation](https://github.com/user-attachments/assets/8f50e2c4-c85d-41eb-bdb9-db65701c2d5d)

### PrimeFaces edition

Community

### PrimeFaces version

v14.0

### JSF implementation

Mojarra

### JSF version

unknown

### Java version

unknown

### Browser(s)

Chrome Version: 127.0.6533.89（Official Build） （64 bit）

**Comment by melloware** [comment]
It's a bug in Autonumeric plugin: https://github.com/autoNumeric/autoNumeric/issues/673

Please subscribe to and update that issue it has to be fixed there.

**Comment by kazunori-iwasaki-0227** [comment]
> It's a bug in Autonumeric plugin: [autoNumeric/autoNumeric#673](https://github.com/autoNumeric/autoNumeric/issues/673)
> 
> Please subscribe to and update that issue it has to be fixed there.

thank you. I will check the link you provided.
