### ISSUE TITLE
p:imageCropper block the UI on mobile

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#1243]
If you try the demo online with an Android phone or tablet 

http://www.primefaces.org/showcase/ui/multimedia/cropper.xhtml

the cropper handles are working but the UI is freezed (menu, scroll, etc...)
( maybe some JS error is blocking )

**Comment by tandraschko** [comment]
Would be great if you could provide a PR.

**Comment by pizzi80** [comment]
Hi tandraschko,
I tryed also Osx has the same problem.

What do you mean for P.R. ? Possible resolution?

The strange thing is that the original jcrop seems working 
with any platform: 

http://deepliquid.com/projects/Jcrop/demos.php?demo=live_crop

Cheers,
Paolo

**Comment by tandraschko** [comment]
Pull Request :)
I think we just use a very very old JCrop version.

**Comment by pizzi80** [comment]
Ok tnx,

I tried to simply put the new jcrop 2.0.4 JS inside the primefaces jar but the component
doesn't work anymore, maybe some adaptation is needed ... ?

**Comment by tandraschko** [comment]
probably yes.

**Comment by tandraschko** [comment]
Updaded the script, should be fixed now.

**Comment by pizzi80** [comment]
Hi tandraschko,

thanks a lot, when do you think that will be ported on 5.3.x?
Actually it is not included in 5.3.10 

Bye,
Paolo
