### ISSUE TITLE
BooleanCheckbox: Client API disable() does not work after form submit

### ISSUE THREAD

**Issue by neun24** [primefaces/primefaces#12438]
### Describe the bug

After submitting a form to itself the client API call disable() does not work anymore for selectBooleanCheckbox. I created a reproducer XHTML and bean. If you're wondering why I disable by client API and not via an ajax call: The real world example is somewhat different and more complicated aka using a very complex plain vanilla form in combination with <f:viewParam> and <f:viewAction>. Nevertheless the behavior exists in this example as well.

Not sure if this description is sufficient. Please ask for more information.

### Reproducer

[pf-12438.zip](https://github.com/user-attachments/files/16551059/pf-12438.zip)

```xml
<!DOCTYPE html>
<h:html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<h:head>
  <title>selectBooleanCheckbox disabled Test</title>
</h:head>

<h:body>

  <h:form id="disabledTestForm">
    <p:inputText value="#{checkBacking.text}" widgetVar="inputText"
      disabled="#{checkBacking.disableEverything}" />

    <p:selectBooleanCheckbox widgetVar="checkBox" value="#{checkBacking.checkBox}"
      itemLabel="checkbox" disabled="#{checkBacking.disableEverything}" />

    <p:selectBooleanCheckbox id="globaldisable" value="#{checkBacking.disableEverything}"
      onchange="toggleInputs()" itemLabel="Disable Everything" />

    <p:commandButton value="Submit" action="#{checkBacking.submit()}" update="@form" />

  </h:form>

  <script>
      function toggleInputs() {
          const widgetVars = [
              'inputText',
              'checkBox',
          ];
          
          const checkbox = document.getElementById('disabledTestForm:globaldisable_input');
          
          widgetVars.forEach(function(widgetVar) {
            if (checkbox.checked) {
                if (PF(widgetVar) &amp;&amp; typeof PF(widgetVar).disable === 'function') {
                    PF(widgetVar).disable();
                }
            } else {
                if (PF(widgetVar) &amp;&amp; typeof PF(widgetVar).enable === 'function') {
                    PF(widgetVar).enable();
                }
            }
          });
      }
  </script>

</h:body>
</h:html>
```

```java
@Data
@Named
@RequestScoped
public class TestView implements Serializable {
    
    private String text;
    private boolean checkBox;
    private boolean disableEverything;
    
    @PostConstruct  
    public void init() {
        
    }

public void submit()
  {
  }
}
```

### Expected behavior

1. Clicking "Disable everything" disables all input elements on the form via client api.
2. Submitting the form submits the value "disableEverything" to the bean.
3. Rerendering the form shows all inputs disabled
4. Unchecking "Disable everything" should re-enable everything.
5. This works for the inputText but not for the selectBooleanCheckbox. (btw: the internal hidden HTML checkbox is enabled correctly)
6. selectBooleanCheckBox should be enabled as well.

Even if I remove the CSS classes ui-state-disabled through JS myself I cannot check it again.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Yep this is a bug.
[pf-12438.zip](https://github.com/user-attachments/files/16551059/pf-12438.zip)
