### ISSUE TITLE
MenuItem: using #{component} in menuItem still references the parent component

### ISSUE THREAD

**Issue by rion18** [primefaces/primefaces#1244]
When calling _#{component}_ inside _p:menuitem_ within a _p:menu_, we get a reference to _p:menu_. Ideally, _#{component}_ should reference _p:menuitem_.

**Comment by tandraschko** [comment]
Would be great if you could provide a PR.

**Comment by melloware** [comment]
MenuIten is a UICommand and not a UIComponent so I don't think this feature can be implemented.  I am not sure it's even worth trying to change MenuIten for this.  Going to close for now.
