### ISSUE TITLE
DatePicker: Remove 10-year default date "hard limit" in the year selector

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#12454]
### Describe the bug

This issue is with Datepicker that has a year selection, such as "multiple months" example in PF Showcase https://primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml

I am not able to either directly enter a year that's earlier than 2014, nor am I able to use "up/down" arrows to select any year earlier than 2014.

The 10-year default should be removed as it's a holdover from where it was a pull-down, not an entry field.
The 10-year default limit no longer makes sense.

### Reproducer

https://primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml "multiple months" date picker

### Expected behavior

Able to select date in year 2010, for example, or year 2000

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### Theme

Default

### JSF implementation

Mojarra

### JSF version

4

### Java version

22

### Browser(s)

Safari

**Comment by melloware** [comment]
Yes just set yearRange property. It defaults to +/- 10 years if you don't set anything.

**Comment by melloware** [comment]
I wonder if we should change the defaults to +\- 100 years...

**Comment by lprimak** [comment]
Hmmm... ok. Why have a default range limit if nothing is set? That seems to be counter-intuitive.
If it's set, of course limit should be enforced.
However, by default, there should be no "hard limit" to what the year can be set to.

**Comment by melloware** [comment]
Yeah it's a holdover from when it was a dropdown to limit the choices in the dropdown.

**Comment by lprimak** [comment]
Oh I get it now :)
I think default range should definitely be removed then... thank you!

**Comment by lprimak** [comment]
Looks like we settled on 1000 years at the end. LGTM, thanks!
