### ISSUE TITLE
DatePicker: Safari issue with a year selection "up/down" arrows

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#12455]
### Describe the bug

This issue is with Datepicker that has a year selection, such as "multiple months" example in PF Showcase https://primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml

When clicking around on the year selection "up/down" arrows, they don't always work.
Sometimes they decrease / increase the year, but most of the time they do not.

### Reproducer

https://primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml "multiple months" date picker

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### Theme

Default

### JSF implementation

Mojarra

### JSF version

4

### Java version

22

### Browser(s)

Safari

**Comment by lprimak** [comment]
Maybe related to #12097

**Comment by melloware** [comment]
I will look it should work fine. As mentioned it only sets it for +/- 10 years unless you use year range.  But the arrows should always work if they don't something is wrong.

**Comment by melloware** [comment]
Is it safari only?  Does it work in Chrome?

**Comment by lprimak** [comment]
Indeed, it's Safari-specific. Works in Firefox and Chrome correctly

**Comment by melloware** [comment]
Ok let me look into it and see if there is anything Safari specific that can be done or whether it's a Safari bug.

**Comment by tmulle** [comment]
@melloware @lprimak I just tested this on  Safari 17.5 with Sonoma and that example works fine for me.
I was able to use the mouse to click around the months, change the days, click the arrows to change months/years, etc.

I was even able to use the keyboard arrow keys and pageup/pagedown to navigate and everything went fine.

**Comment by tmulle** [comment]
@melloware @lprimak Ok I see what  you see now when changing the date with the spinner arrows. I click the first time on the arrow up or down and it changes. But subsequent clicks on the arrows don't work until I click out and then  back into the component

**Comment by melloware** [comment]
Safari === the new Internet Explorer 😄

**Comment by lprimak** [comment]
@tmulle You got it. This is the exact behavior I am talking about :)

**Comment by lprimak** [comment]
> Safari === the new Internet Explorer

haha maybe maybe not... maybe Safari is the only correct one and found yet-another-javascript bug  :)

**Comment by melloware** [comment]
Agreed this looks like a Safari "feature".  When i did searched it seems like Safari has struggled with input type="number" for years from reading all the bug tickets.

**Comment by melloware** [comment]
@lprimak just go here and see this is just Raw HTML version:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

Does it happen with your Safari?

**Comment by lprimak** [comment]
Ha! No it does **not** :) :)

JavaScript magic stries again :)

**Comment by lprimak** [comment]
Looks like something is "eating" mousdown event unless it's followed by a mousemotion event

**Comment by lprimak** [comment]
@jepsar I think you are a bit too early closing this :)

**Comment by melloware** [comment]
it has `change and keydown` events but **NO** mouse events are attached...

```
.on('change.datePicker-yearnav', yearNavigatorSelector, null, this.onYearInputChange.bind($this))
.on('keydown.datePicker-yearnav', yearNavigatorSelector, null, function(event) {$this.onTimeInputKeyDown(event);});
```

**Comment by melloware** [comment]
p.s. I don't have Safari so as far as I am concerned its a Safari bug as its perfectly valid what we are doing so I won't spend any time on this...

**Comment by melloware** [comment]
Found this really old blog post which looks like it might be the issue and has been with Safari and IOS since 2007.

https://blog.johnmckerrell.com/2007/03/07/problems-with-safari-and-innerhtml/

**Comment by lprimak** [comment]
So maybe there is a workaround?

**Comment by melloware** [comment]
yeah let me send you some MonkeyPatches to try since you have Safari.  Working on one....

**Comment by lprimak** [comment]
oh you are the best!

**Comment by melloware** [comment]
here is the first one...not sure it will work but it adds a 50ms UI delay to the update which is what that blog post says he does.

```js
if (PrimeFaces.widget.DatePicker) {
  $.prime.datePicker.prototype.onYearInputChange = function(event) {
    var newViewDate = new Date(this.viewDate.getTime());
    newViewDate.setFullYear(parseInt(event.target.value, 10));

    if (this.options.onYearChange) {
      this.options.onYearChange.call(this, newViewDate.getMonth(), newViewDate.getFullYear());
    }

    var $this = this;
    setTimeout(function() {
      $this.updateViewDate(event, newViewDate);
    }, 50);
  }
}
```

**Comment by lprimak** [comment]
Silly questions... how would I apply that patch?
Shows you I am not a JS guy :)

**Comment by melloware** [comment]
you have to put that script somewhere after PrimeFaces loads on your page.  Hang on let me create a runnable test case for you.

**Comment by lprimak** [comment]
I just tried that... didn't work :(

**Comment by melloware** [comment]
here you go try this unzip and run `mvn clean jetty:run`

[pf-12455.zip](https://github.com/user-attachments/files/16617677/pf-12455.zip)

**Comment by melloware** [comment]
And here is a second attempt make sure to CTRL+F5 to reload JS in your browser or whatever the Safari equivalent of that is.
[pf-12455-2.zip](https://github.com/user-attachments/files/16617889/pf-12455-2.zip)

**Comment by lprimak** [comment]
Nope... sorry. same behavior as before

**Comment by melloware** [comment]
in the last one i tried to not use `innerHTML` as and use `replaceChildren` recommend by a few people saying it fixes Safari issues but alas it does not work.

```js
// re-render the panels contents
    var elementsHtml = this.renderPanelElements();
    var tempContainer = document.createElement('div');
    tempContainer.innerHTML = elementsHtml;

    const panelElement = this.panel.get(0);
    panelElement.replaceChildren(...Array.from(tempContainer.childNodes));
```

**Comment by lprimak** [comment]
Let me try that one please :)

**Comment by melloware** [comment]
Both of those are the widely common hacks around Safari people suggest and you said neither worked. 

I am back to thinking this is Safari bug in perfectly acceptable code.

**Comment by lprimak** [comment]
Oh, I only tried `-2` lemme try the original

**Comment by lprimak** [comment]
yes neither works unfortunately

**Comment by melloware** [comment]
[pf-12455-3.zip](https://github.com/user-attachments/files/16624800/pf-12455-3.zip)

here is a 3rd attempt not sure it will work either.

**Comment by lprimak** [comment]
No luck on the last one either :(

**Comment by lprimak** [comment]
lol... That's frustrating

**Comment by melloware** [comment]
I reopened: https://github.com/primefaces/primefaces/issues/12097  I think for 15.0.0 we will give people the option.
