### ISSUE TITLE
org/primefaces/util/SerializableSupplier is missing in primefaces 14 when using DefaultStreamContent to build PDF content

### ISSUE THREAD

**Issue by cidylong** [primefaces/primefaces#12464]
### Describe the bug

When tried to produce pdf content by using DefaultStreamedContent in Primefaces 14.0.4.

code as:

    StreamedContent pdfContent = DefaultStreamedContent.builder().contentType(pdf.getPdfType()).name(pdf.getPdfName()).stream(() -> new ByteArrayInputStream(pdf.getPdfData())).build();

Application throws:

jakarta.el.ELException: /payments/paymentViewPlain.xhtml @16,144 outcome="#{paymentOPSWController.viewPaymentPdf()}": java.lang.NoClassDefFoundError: org/primefaces/util/SerializableSupplier

Check with emacs by open downloaded [primefaces-14.0.4.jar](https://repo1.maven.org/maven2/org/primefaces/primefaces/14.0.4/primefaces-14.0.4.jar).

And found, there is no such file in the jar.

This is output from emacs

![Screenshot 2024-08-13 at 9 20 49 PM](https://github.com/user-attachments/assets/04b8d096-cd5e-4a4b-9485-fc3ee2d744c7)

Tried to open https://repo1.maven.org/maven2/org/primefaces/primefaces/13.0.5/primefaces-13.0.5.jar

Result as:

![Screenshot 2024-08-13 at 9 24 36 PM](https://github.com/user-attachments/assets/37df8549-cfd8-4ae7-9a0f-b4fc238c05a5)

org/primefaces/util/SerializableSupplier is here.

### Reproducer

As bug description.

### Expected behavior

DefaultStreamedContent should be able to  build streamedContent as previous version/

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### JSF implementation

Mojarra

### JSF version

3.0

### Java version

Oracle JDK 17.0.3

### Browser(s)

Safari 17.5

**Comment by tandraschko** [comment]
yeah, we moved the class
sounds like duplicate PF jars or incompatible PF ext version

**Comment by cidylong** [comment]
My question is, in 14.0.4. if there is no org/primefaces/util/SerializableSupplier exist. How to build StreamedContent by using DefaultStreamedContent, if any one can share me an example code other than my code as above described, lots of appreciation.

**Comment by cidylong** [comment]
I mean I have contentType, name and ByteArray data ready. How I can build StreamedContent?

**Comment by tandraschko** [comment]
your code is ok
is just here now: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/util/Callbacks.java

**Comment by melloware** [comment]
@cidylong as @tandraschko mentionde you either have two PrimeFaces JARS in your classpath or a bad server cache or something.

**Comment by cidylong** [comment]
@melloware , Let me check it.

**Comment by cidylong** [comment]
@melloware ,thank you for your advice. I checked my server, there are two version of PF exist, I removed the old one, re-compile the application and  restart server, it works fine.

Thank you every one!
