### ISSUE TITLE
DatePicker: TimeZone does not work

### ISSUE THREAD

**Issue by mstichweh** [primefaces/primefaces#12465]
### Describe the bug

If datePicker is used with any `timeZone` value in a german environment, the day and month values are swapped.
If the datePicker value is empty and the popup is opened up, the current date should be visible. But for August the 12th it shows December the 8th as current date. And for August the 13th the picker shows "undefined" for month, year and time and does not show any days.

Removing the `timeZone` attribute everything works fine, but only with the system default time zone. 

### Reproducer

HTML:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	  xmlns:jsf="http://xmlns.jcp.org/jsf"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:p="http://primefaces.org/ui">

	<h:head>
		<title>PrimeFaces Test</title>
		<h:outputScript name="test.js" />
		<h:outputStylesheet name="test.css" />
	</h:head>
	<h:body>

		<h:form id="frmTest">
			<div class="card">
				<h5>DateTime</h5>
				<div class="ui-fluid grid formgrid">
					<div class="field col-12 md:col-4">
						<p:outputLabel for="time2" value="Time (Timezone GMT+8)" />
						<p:datePicker id="time2" locale="de" value="#{testView.localDateTime}" timeZone="GMT+8" />
					</div>
				</div>
			</div>
		</h:form>

	</h:body>
</html>

```

Bean:

```
package org.primefaces.test;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import lombok.Data;

@Data
@Named
@ViewScoped
public class TestView implements Serializable
{
	private LocalDateTime localDateTime;

	public LocalDateTime getLocalDateTime()
	{
		return localDateTime;
	}


	public void setLocalDateTime( LocalDateTime localDateTime )
	{
		this.localDateTime = localDateTime;
	}
}
```

### Expected behavior

The `timeZone` attribiute should work in all locale environments.

### PrimeFaces edition

None

### PrimeFaces version

14.0.4

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

**Comment by melloware** [comment]
Related to this change: https://github.com/primefaces/primefaces/issues/12307

**Comment by melloware** [comment]
I htink this issue is that its getting NOW in that timezone using your browsers locale.

```js
/**
         * Gets the current date and time. If a time zone is specified in the options, 
         * it returns the current date and time adjusted to that time zone.
         * 
         * @returns {Date} The current date and time.
         */
        getNow: function() {
            var now = new Date();
            if (this.options.timeZone) {
                var jsTimezone = this.convertTimeZone(this.options.timeZone);
                now = new Date(now.toLocaleString(undefined, { timeZone: jsTimezone }));
            }
            return now;
        },
```

**Comment by mstichweh** [comment]
Unfortunately this patch does not work. First of all the `this.options.userLocale` is an object of translated labels, so the `jsLocale` is still `undefined`. But even with a fixed `jsLocale` it does not work because the Date contructor does not accept the `toLocaleString` output and returns an invalid Date. 

This version works for me, could you give it a try?

```
if (PrimeFaces.widget.DatePicker) {
	$.prime.datePicker.prototype.getNow = function() {
		var now = new Date();
		if (this.options.timeZone) {
			var jsTimezone = this.convertTimeZone(this.options.timeZone);
			var localString = now.toLocaleString('en-GB', {
				year: "numeric",
				month: "long",
				day: "numeric",
				hour: "numeric",
				minute: "numeric",
				second: "numeric",
				timeZone: jsTimezone
			}).replace(' at ', ', ');
			now = new Date(localString);
		}
		return now;
	}
}
```

**Comment by mstichweh** [comment]
Yes its hardcoded to "en-GB", because I expect that the Date contructor does not understand the german format

**Comment by melloware** [comment]
![image](https://github.com/user-attachments/assets/bf9c891c-a456-4643-8d11-0c93c32348ca)

With `de` instead of `en-GB`

**Comment by mstichweh** [comment]
I tryed it with "de" and get the error again. This is also my experience with Date, it doesn't like non-English formats.

**Comment by melloware** [comment]
Ahhh I see the `new Date()` constructor doesn't like it...
