### ISSUE TITLE
TreeTable: <p:columns> inside of TreeTable custom filter facet doesn't work

### ISSUE THREAD

**Issue by KursatErenColak** [primefaces/primefaces#12474]
### Describe the bug

When I use custom filter facet in columns of treeTable all filter functions doesn't work

XHTML;
![image](https://github.com/user-attachments/assets/f4df7f31-8acf-4660-861a-9b6b5e043a87)

There is no error in browser console or IDE output.

When I add one more dummy <p:column> in same treeTable and applying same custom filter it works.

Is not available that add custom <f:facet> to columns in treeTable ?

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### Theme

Poseidon

### JSF implementation

Mojarra

### JSF version

4.0.5

### Java version

21

### Browser(s)

Chrome Version 127.0.6533.100

**Comment by melloware** [comment]
@Rapster i forget i know there are some things that don't work with `<p:columns>` i don't remember if filter facet is one of them

**Comment by Rapster** [comment]
I'm pretty sure it works with dataTable, that enhancement has probably not been ported to treeTable

**Comment by melloware** [comment]
@KursatErenColak can you verify this same thing works with a Datatable?

**Comment by KursatErenColak** [comment]
@melloware  Yes its works with DataTable almost same situation (dynamic columns / <f:facet> )

**Comment by melloware** [comment]
OK then this is a new feature for TreeTable and if you want to provide a PR that would be great.  But for now I am moving this ticket to the "Finacial Sponsoring Required" ticket here: https://github.com/primefaces/primefaces/issues/11250

**Comment by KursatErenColak** [comment]
@melloware, I noticed that it doesn't work with dataTable. If <f:facet> is used in DataTable or TreeTable, only custom filters work.

**Comment by melloware** [comment]
when you say only custom filters work what do you mean?  @Rapster ?

**Comment by KursatErenColak** [comment]
I added some SelectOneMenu for 2 columns inside the DataTable. After, other inputs are not working except selectonemenus in <f:facet>.

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by KursatErenColak** [comment]
![image](https://github.com/user-attachments/assets/74b68075-fe4f-43df-acdc-ce1637ae1431)
Not work

![image](https://github.com/user-attachments/assets/0638ddc9-2326-43f6-8d81-5e0f616c43ef)
Works fine for custom filter

I solve that problem like that ;

`<f:facet name="filter">
<p:inputText styleClass="w-full"
								rendered="#{column.type ne 'boolean' and column.type ne 'enum'}">
								<p:ajax event="keyup" partialSubmit="true"
									oncomplete="PF('notificationListWidget').filter()"/>
							</p:inputText>
						</f:facet>`

**Comment by KursatErenColak** [comment]
@melloware You can check the problem in showcase [PrimeFaces DataTable filter with custom filter component](https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml?jfwid=0aba3) when using dropdown it works fine but inputText doesn't work and also datePicker is custom component but I think it isn't work maybe it because of another reason.

**Comment by melloware** [comment]
it might be the SelectOne looks like it is working:

**Comment by melloware** [comment]
you can open a new ticket for DataTable as a bug.

**Comment by KursatErenColak** [comment]
Also TreeTable has same bug will I write both in the same ticket ?

**Comment by Rapster** [comment]
1 bug = 1 ticket

**Comment by melloware** [comment]
@KursatErenColak we have added fixes for 14.0.5 for Datatable and TreeTable.
