### ISSUE TITLE
DataExporter: Example not complete

### ISSUE THREAD

**Issue by DerIngo** [primefaces/primefaces#12479]
### Describe the bug

I tried to implement the (Custom) TextDataExporter from the [Showcase](http://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml).
It was not working, error message was: ``Exporter for org.primefaces.component.datatable.DataTable of type 'txt' is not supported. Use DataExporters#register()``.

I could fix it in my TextExporter class:
``` 
public class TextExporter extends DataTableExporter<PrintWriter, ExporterOptions> {

    static {
        DataExporters.register(DataTable.class, TextExporter.class, "txt");
    }
    
    public TextExporter() {
        super(null, Collections.emptySet(), false);
    }
```

The example in the showcase is working, so **I guess it is only missing in the documentation** (TextExporter.java - Tab) on the page.

PS: I could not find any sources of the showcase. Aren't they public available any more?

### Expected behavior

``DataExporters.register`` should be documented in the [Showcase](http://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### JSF implementation

Mojarra

### JSF version

4

### Java version

21

**Comment by melloware** [comment]
Thanks for reporting this is a bug with the showcase.  For now its all documented here: https://primefaces.github.io/primefaces/15_0_0/#/components/dataexporter?id=custom-export

**Comment by melloware** [comment]
Its fixed in master the old showcase is still deployed but here is an updated version showing the TextExporter.java: 

https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/dataexporter/basic.xhtml
