### ISSUE TITLE
PickList: transfer event is not firing

### ISSUE THREAD

**Issue by ToFe19** [primefaces/primefaces#12483]
### Describe the bug

I use pickList in my application. In version 13.0.7 and 13.0.10 the transfer event was fired when moving items from left to right and from left to left. In version 14.0.3 and 14.0.4 the event is only fired when moving items from right to left.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.3

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

17

### Browser(s)

Chrome 127.0.6533.120 (Official Build) (64-bit)

**Comment by melloware** [comment]
Seems to work fine here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/pickList.xhtml  See the Advanced example the Transfer is firing in either direction.

**Comment by ToFe19** [comment]
Is there a difference in PickList from 14.0.3 to 14.0.4? I've seen, that I'm using 14.0.3....

**Comment by melloware** [comment]
https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/14_0_0?id=picklist

Yes right there in the migration make sure to look at the 3rd bullet. I bet your equals and hash code methods are not correct on your POJO

**Comment by ToFe19** [comment]
hmm, I don't use a converter and what do you mean with POJO? Is it the value passed to itemValue?

Here my markup:

<p:pickList value="#{groupDetail.assignedRoles}" sourceListWidth="140px" targetListWidth="140px"
								var="role" itemLabel="#{role.roleId}" itemValue="#{role.pk}"
>
						<p:ajax event="transfer" listener="#{groupDetail.pickListListener}"/>
</p:pickList>

**Comment by melloware** [comment]
OK then please create an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by berger-devel** [comment]
> ### Describe the bug

We were able to reproduce the issue, please see the linked repo. We use Spring for Bean creation, which could be related. After the page is loaded, an error message "Error j_idt8:pojoPickList: An error occurred when processing your submitted information. j_idt8:pojoPickList: An error occurred when processing your submitted information." appears when an item is moved from the left column of the PickList to the right column. The same error occurs with any subsequent items moved from left to right. The error also occures when moving a single item back to the left column, except for the last item in the right column. In fact, from the point when moving the only item or all items from the right column to the left the expected growl message is displayed.

However, we encountered other issues. When reloading the page after seeing the expected growl a HTTP error 500 occurs with the message 
> jakarta.servlet.ServletException: java.io.IOException: jakarta.servlet.ServletException: /test.xhtml @23,80 itemLabel="#{country.name}": The class 'java.lang.String' does not have the property 'name'.

Also, when uncommenting lines 90-93 in `PickListView.java` a ClassCastException is thrown with the message
> class java.lang.String cannot be cast to class org.primefaces.showcase.domain.Country (java.lang.String is in module java.base of loader 'bootstrap'; org.primefaces.showcase.domain.Country is in unnamed module of loader org.eclipse.jetty.ee10.webapp.WebAppClassLoader @5e777b0)

Original Description: 
> I use pickList in my application. In version 13.0.7 and 13.0.10 the transfer event was fired when moving items from left to right and from left to left. In version 14.0.3 and 14.0.4 the event is only fired when moving items from right to left.
> 
> ### Reproducer
> https://github.com/berger-devel/primefaces-issue-12483
> 
> ### Expected behavior
> A growl reading "Items Transferred" appears
> 
> ### PrimeFaces edition
> Community
> 
> ### PrimeFaces version
> 14.0.4
> 
> ### Theme
> Saga
> 
> ### JSF implementation
> Mojarra
> 
> ### JSF version
> 4.0.1
> 
> ### Java version
> 17
> 
> ### Browser(s)
> Chrome 127.0.6533.120 (Official Build) (64-bit)
> Microsoft Edge for Business Version 128.0.2739.42 (Official build) (64-bit)

**Comment by melloware** [comment]
@berger-devel all fixed:
[pf-12483.zip](https://github.com/user-attachments/files/16798126/pf-12483.zip)

Run `mvn clean jetty:run`.  You were missing a converter to convert Country to String and String to Country object.

**Comment by berger-devel** [comment]
Thank you very much!

**Comment by ToFe19** [comment]
Is a converter needed in any case using primefaces above version 14? The code was working without a converter with version 13.0.7 and 13.0.10

**Comment by melloware** [comment]
Converter is not necessary if you are using a  `String` but if using POJO's like the the example with `Country` yes a converter is needed to convert Country -> String and String -> Country. That has always been the case.
