### ISSUE TITLE
Tree: Not possible to make tree nodes collapsed after deleting the filter

### ISSUE THREAD

**Issue by eftewuer** [primefaces/primefaces#12481]
### Describe the bug

This bug report is a result of this discussion:
https://github.com/orgs/primefaces/discussions/2513

Summary of the problem:
1. enter filter text matching any tree node(s)
2. the tree correctly shows only the nodes matching the filter
3. delete the filter text - all the nodes are expanded.

Problem: it is not possible to make the tree to display all the nodes being collapsed after deleting the filter.
Why is this a problem: imagine a tree with big number of subnodes having big number of subnodes. Showing the tree all expanded make a mess on the screen and takes time to show it in a browser.

It should be possible to show the tree with all nodes collapsed after deleting the filter text.

The PF Showcase can be used to check default Tree behavior:
http://www.primefaces.org/showcase/ui/data/tree/filter.xhtml?jfwid=e9d99

### Reproducer

https://github.com/eftewuer/primefaces-test-unfiltered-tree-expanded

1. run the project with "mvn jetty:run"
2. in your browser go to http://localhost:8080
3. paste "John" as filter text and press Enter - filtered nodes are correctly displayed
4. delete filter text and press Enter - the tree is displayed with all nodes expanded.

5. in /src/main/java/org/primefaces/test/TestView.java uncomment the line 115 in method filterComplete()
6. rebuild the project and run it. 
7. go through steps 2-4: it looks this way I can make the tree to work this way that after removing filter text and pressing Enter the tree is displayed with all nodes collapsed but:
- the tree expands itself anyway first
- and then the refresh command in filterComplete() method makes it blink for a moment and then it gets collapsed.

### Expected behavior

It should be possible to have the tree with all nodes collapsed when deleting the filter text.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### JSF implementation

Mojarra

### JSF version

I don't know, whatever the primefaces-test project provides.

### Java version

17.0.11

**Comment by melloware** [comment]
@RohdeSchwarz-SDC @OBUTTERLIN you guys have recently use the Tree with filtering do you agree with the bug above.  It does seem odd behavior to me.

**Comment by OBUTTERLIN** [comment]
If we refer to the showcase, there is indeed a problem.
The first time the view is displayed, the nodes are closed.
We do a "re" search -> it displays the result correctly.
We remove the "re" filter -> nodes are opened in an incomprehensible way

**Comment by melloware** [comment]
@OBUTTERLIN yes the nodes are all expanded when you remove "re" from the search filter is the issue. Do you see the same issue in your local apps?  I am surprised no one else has complained about this until now?

**Comment by melloware** [comment]
The issue is here in TreeRenderer.java

https://github.com/primefaces/primefaces/blob/53ef762fc45865c67bd16847b4e9bf7479fab63c/primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java#L672-L693

When you filter it sets `node.expanded(true)` so when filter its sets the nodes expanded so you can see them match your filter text.  Now that is the state of the `node` so when you unfilter its still `expanded = true` which explains the behavior.

**Comment by melloware** [comment]
PR submitted so now you can properly use the AJAX filter event to reset node state.

```xml
<p:ajax event="filter" listener="#{testView.onFilter}" />
```

```java
public void onFilter(AjaxBehaviorEvent e) {
        FacesContext context = e.getFacesContext();
        String clientId = e.getComponent().getClientId();

        Map<String, String> params = context.getExternalContext().getRequestParameterMap();
        String filteredValue = params.get(clientId + "_filter");

	if(!(filteredValue!= null && !filteredValue.isEmpty())) {
            List<TreeNode<String>> children = root.getChildren();
            children.forEach(child -> {
                child.setExpanded(false);
            });
        }
    }
```

**Comment by OBUTTERLIN** [comment]
I only use a Tree component for a Menu so it doesn't matter to me.
One solution would be to save the state of the nodes when the filter is first searched and restore that state when the filter is removed.
Personally I don't mind the state changing after a filter action as long as we implicitly requested an action on the nodes through a search.

**Comment by eftewuer** [comment]
> PR submitted so now you can properly use the AJAX filter event to reset node state.
> 
> ```
> <p:ajax event="filter" listener="#{testView.onFilter}" />
> ```
> 
> ```java
> public void onFilter(AjaxBehaviorEvent e) {
>         FacesContext context = e.getFacesContext();
>         String clientId = e.getComponent().getClientId();
> 
>         Map<String, String> params = context.getExternalContext().getRequestParameterMap();
>         String filteredValue = params.get(clientId + "_filter");
> 
> 	if(!(filteredValue!= null && !filteredValue.isEmpty())) {
>             List<TreeNode<String>> children = root.getChildren();
>             children.forEach(child -> {
>                 child.setExpanded(false);
>             });
>         }
>     }
> ```

Is it possible to check how it works in my sample project? Can I just change the PF version in my pom.xml to use some snapshot version or is it still in some separate branch?
