### ISSUE TITLE
LinkButton: ariaLabel attribute not working

### ISSUE THREAD

**Issue by hamsterbacke81** [primefaces/primefaces#12506]
### Describe the bug

We are using primefaces 13. According to the documentation, the linkButton component supports "ariaLabel"-attribute. But this is not actually showing in the HTML code

### Reproducer

`<p:linkButton id="contact_button_phone"
							  ariaLabel="some label"
							  value="Number"
							  href="tel:12345678"
							  icon="ui-icon rol-call"
				/>`

### Expected behavior

the HTML code should contain `arial-label="some label"`

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

All

### JSF version

4.0

### Java version

21

**Comment by jepsar** [comment]
Can't this attribute be added using passthrough?

**Comment by melloware** [comment]
I do see the docs and the taglib have the code we should check why it's not being rendered.

**Comment by melloware** [comment]
@hamsterbacke81 this is by design the ARIA Label is only necessary when the button is in "iconOnly" mode.  If you have button text you don't need aria-Label the screen reader reads the button text.

```
/**
     * Renders a button value or label for screen readers if no value is present or icon only button.
     *
     * @param writer The response writer
     * @param escaped is the button escaped?
     * @param value the value for the button
     * @param title the title for the button
     * @param arialLabel the aria label for the button
     * @throws IOException if any error occurs
     */
    protected void renderButtonValue(ResponseWriter writer, boolean escaped, Object value, String title, String arialLabel) throws IOException {
        if (value == null) {
            //For ScreenReader
            String label = getIconOnlyButtonText(title, arialLabel);
            if (escaped) {
                writer.writeText(label, null);
            }
            else {
                writer.write(label);
            }
        }
        else {
            if (escaped) {
                writer.writeText(value, "value");
            }
            else {
                writer.write(value.toString());
            }
        }
    }
```

**Comment by melloware** [comment]
I submitted a PR to update the docs to signal ariaLabel is only used when button is in Icon Only mode.

**Comment by hamsterbacke81** [comment]
okay thanks, the updated documentation should prevent confusion in the future.

**Comment by melloware** [comment]
Thanks for reporting!
