### ISSUE TITLE
DataTable: Filter isn't working when <f:facet> is added

### ISSUE THREAD

**Issue by KursatErenColak** [primefaces/primefaces#12507]
### Describe the bug

When <f:facet name="filter"> added to DataTable or TreeTable filter isn't working for default filter inputs. #12474 
You can see in [Primefaces Showcase](https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml?jfwid=b09b2) dropdown filter works but inputText ones aren't working also DatePicker filter is not work correctly.

### Expected behavior

Prime faces filter should works.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### Theme

Poseidon

### JSF implementation

Mojarra

### JSF version

4.0.5

### Java version

21

### Browser(s)

Chrome Version 127.0.6533.120

**Comment by melloware** [comment]
Looks like this introduced: https://github.com/primefaces/primefaces/issues/12744
