### ISSUE TITLE
p:imageCropper showcase example code will fail in portlets

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#1251]
The [`p:imageCropper`](http://www.primefaces.org/showcase/ui/multimedia/cropper.xhtml) example code relies on the `ServletContext`, so it will not work in portlets where `externalContext.getContext()` returns a `PortletContext`.

```
ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
String newFileName = servletContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" +
    File.separator + "images" + File.separator + "crop" + File.separator + getNewImageName() + ".jpg";
```

To avoid relying on the `ServletContext`, the above code can call `externalContext.getRealPath("")` instead of `servletContext.getRealPath("")`:

```
ExternalContext externalContext = (ExternalContext) FacesContext.getCurrentInstance().getExternalContext();
String newFileName = externalContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" +
    File.separator + "images" + File.separator + "crop" + File.separator + getNewImageName() + ".jpg";
```

**Comment by tandraschko** [comment]
Would be great if you could provide a PR.
We already did many portlet fixes in the past.

**Comment by tandraschko** [comment]
Nevermind, there already is one! :D

**Comment by stiemannkj1** [comment]
@tandraschko actually I didn't send a PR for this one since it is a simple documentation bug, and I didn't think the showcase code was on Github. I did send PR #1250 to fix issue #1248 which causes `p:imageCropper` not to work in portlets though. If you could point me to the source of Primefaces showcase, I would be happy to fix it for you though.

**Comment by stiemannkj1** [comment]
@tandraschko never mind, I found the [showcase](https://github.com/primefaces/showcase) I will close this issue and copy this issue to that repo.

**Comment by stiemannkj1** [comment]
I've moved this issue over to the showcase repo: https://github.com/primefaces/showcase/issues/13
