### ISSUE TITLE
DataTable/TreeTable: New `filterNormalize` attribute

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#12511]
### Description

Firstly I really appreciate the new `filterNormalize="true"` attribute, available in components like `<p:selectCheckboxMenu/>`
 
 **I was wondering if it is possible to have the same behaviour in _<p:datatable columns_ /> as well.** E.g.:
`<p:column   filterBy="#{op.name}"   filterMatchMode="contains"  **filterNormalize="true"**   .../> `

BTW, I'm actually using a custom filter method in Bean and using it like that: `filterFunction="#{utilBean.filterContainsWithoutAccents}"` and it works fine when user filter using the Column Header Filter Box, but fails when user use the main global filter box like:
` <h:inputText id="globalFilter"  onkeydown="if (event.keyCode == 13) { return  PF('tableWdg').filter(); }"        />` which not calls ServerSide Bean method` public boolean filterContainsWithoutAccents(Object value, Object filter, Locale locale) {.`.. anymore.

Regards 

### Describe the solution you would like

For me, the cleanest solution would be  to have  `filterNormalize=""` attribute like we have now in components like `<p:selectCheckboxMenu/>` to filtering for column data, escaping accented characters.

As a workaround I'm using a server side custom filter method called in: `filterFunction="#{utilBean.filterContainsWithoutAccents}"`  but apparently it just work   when called by the 'Column Header Filter Box', and it's not   called   by global filter `PF('tableWdg').filter();`,  there is a way to call all declared columns `filterFunction=""` in that context as well?

Thanks in advance.

**Comment by melloware** [comment]
@edudoda can you post your server side Java code you are using so I can see it?

**Comment by edudoda** [comment]
> @edudoda can you post your server side Java code you are using so I can see it?

Thank you @melloware for consider my suggestion.  As a new feature request, java code is really needed?

**Comment by melloware** [comment]
well the reason i say that is it might be easier to plug this in the Datatable on the serve when its processing its filters vs trying to do it in the Javascript because you control the filters.  for example....

```xml
<f:facet name="filter">
                    <p:selectOneMenu onchange="PF('customersTable').filter()" styleClass="ui-custom-filter">
                        <f:selectItem itemLabel="All" itemValue="#{null}" noSelectionOption="true" />
                        <f:selectItems value="#{dtFilterView.representatives}" />
                    </p:selectOneMenu>
                </f:facet>
```

We have no idea what people are doing with their filters or the global filter but we DO know on the server side there is 1 spot where filters are processed and it might be easier to change that than to try and fix it all in the Javascript code which may not catch every case.

**Comment by melloware** [comment]
@edudoda submitted PR for what I was thinking: https://github.com/primefaces/primefaces/pull/12549  this way it handles all filters including the global filter.
