### ISSUE TITLE
DF Cann't be used in iframe

### ISSUE THREAD

**Issue by zsuiqiang** [primefaces/primefaces#1253]
`<iframe src="data.jsf" style="width: 100%;height: 600px;" name="workspace" scrolling="auto"/>`

data.xhtml is as same as in showcase.

**Comment by tandraschko** [comment]
A PR would be great.

**Comment by zsuiqiang** [comment]
The problem exist from 5.3.6 to 5.3.11, why not fix?

**Comment by tandraschko** [comment]
why not provide a PR?
Is there a JS error?

**Comment by zsuiqiang** [comment]
http://forum.primefaces.org/viewtopic.php?f=3&t=45274

**Comment by zsuiqiang** [comment]
Is this issue confirmed? When to solve?

**Comment by ndrikdarto** [comment]
@tandraschko 
I think, there is a JS error.
The method RequestContext.getCurrentInstance().closeDialog(Object) won't close the dialog and the dialogReturn method is not invoked. In Firebugs console give a JS error.

![pf fd error js](https://user-images.githubusercontent.com/29494455/27248942-17cafcf0-5335-11e7-849c-4096c255d2a9.PNG)

I tried this with Primefaces 6.1 community library. When I changed back to 5.3 community library, this bugs was not appear.

Could someone please check this issue?

**Comment by tandraschko** [comment]
duplicate of #1403

**Comment by dani7120** [comment]
Hi, this issue was solved and released?

**Comment by melloware** [comment]
@dani7120 Yes it was fixed in PF 6.2 or higher: https://github.com/primefaces/primefaces/issues/1403
