### ISSUE TITLE
serenity theme: material icon font no longer showing up in p:menuitem

### ISSUE THREAD

**Issue by MP2E** [primefaces/primefaces#12537]
### Describe the bug

Example of one of the menu items XHTML:
<p:menuitem id="sr_lnk103" value="Services" icon="&#xE871;" outcome="/content/services.xhtml" />

When the left nav is minimized, the icon is supposed to appear but doesn't. When the left nav is not minimized, the menus look correct except the drop down materials icon is not showing for submenus.

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.3

### Theme

Serenity

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

17

### Browser(s)

Safari

**Comment by melloware** [comment]
Your post in the commmunity forums was the correct spot. This issue tracker is only for the open source library not for any premium PrimeTek support

**Comment by MP2E** [comment]
Sorry about that, I saw the discussion forums after posting this issue. Thanks

**Comment by melloware** [comment]
No problem I responded on the community.
