### ISSUE TITLE
p:media for PDF does not work on mobile Safari

### ISSUE THREAD

**Issue by kojotak** [primefaces/primefaces#12550]
### Describe the bug

Can not display PDF using `p:media` tag on mobile Safari browser. Should I use the extensions instead? 

### Reproducer

Open Primefaces showcase in mobile Safari (ipad, iphone), find and open Media component page.
![IMG_20240902_154839781](https://github.com/user-attachments/assets/60bbbcf8-7c0e-4221-9361-6dfa62544323)

### Expected behavior

PDF document is displayed as in other (desktop) browser like Chrome.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4.0.6

### Java version

17.0.0

### Browser(s)

iPadOS 17.5.1, AppleWebKit/605.1.15

**Comment by melloware** [comment]
Looks like this might be the issue: https://stackoverflow.com/questions/72183251/html-pdf-not-showing-in-safari

**Comment by melloware** [comment]
It seems like this is a common Mobile Safari issue with PDF's.

You might want to switch to PrimeFaces Extensions PDF Viewer: https://www.primefaces.org/showcase-ext/sections/documentviewer/basic.jsf

**Comment by kojotak** [comment]
Thanks, the `DocumentViewer` from PrimeFaces extension is working.

**Comment by melloware** [comment]
@kojotak excellent!

**Comment by melloware** [comment]
@kojotak this belongs over at PFE. Howevre PFE 13.0.11 uses the latest PDF.JS you can see in this ticket: https://github.com/primefaces-extensions/primefaces-extensions/issues/1569

So you must be using an older PFE.

**Comment by kojotak** [comment]
Oh, you are right, @melloware, I was using 13.0.10, thanks. The latest version of PE fixed my issue with more complex document. 👍

**Comment by melloware** [comment]
nice yeah you might want to use 13.0.13 which is the latest PFE release.
