### ISSUE TITLE
FileUpload: restricting file names (allowTypes ) of uploaded files not double-checked at server side

### ISSUE THREAD

**Issue by DerIngo** [primefaces/primefaces#12559]
### Describe the bug

We had a pentest of our application and it was possible to upload not allowed files.
For example we only allowed only gif and pdf, but they were able to upload .js-files, .exe-files etc.

### Reproducer

I have not reproduced by myself, but pentest report mentions "Burp Suite Professional, Google Chrome Browser" as tools.

### Expected behavior

Files with types that are not in the "allowTypes"-list must not be uploaded.

(this is also [documentated](https://primefaces.github.io/primefaces/13_0_0/#/components/fileupload): "As of PrimeFaces 7.0 this will be double-checked at server side as well")

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### JSF implementation

Mojarra

### JSF version

4.1.0

### Java version

21

**Comment by tandraschko** [comment]
Try to debug, it should be: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/validate/FileValidator.java#L137

**Comment by melloware** [comment]
@DerIngo at least if you can find out what was the `allowTypes=` set to and what did they change to make it pass on the server side would be a good start!

**Comment by tandraschko** [comment]
and also check the migration guide to use p:validateFile

**Comment by DerIngo** [comment]
I tried to reproduce it today. But now I have the problem the other way around:
I could select every filetype in the upload dialog in my browser and then on the server side it was validated and rejected.
I do not know, what I had changed meanwhile. So I thought, I just go on to complete the migration (as suggested from @tandraschko: use p:validateFile). The missing cliend side validation is reproducable.

Executable example: [cloned PrimeFaces Test](https://github.com/DerIngo/primefaces-test) project.
Just click the "Datei hinzufügen"-button and you can upload any type of file, not only allowTypes="/(\.|\/)(gif|jpeg|jpg|png)$/". The upload will not complete, because it is blocked on the server side.

**Comment by tandraschko** [comment]
You need to activate CSV as stated in the Migration Guide.

**Comment by melloware** [comment]
@DerIngo when I run your example it works for me.  I can upload only images but another other file type is blocked.

![image](https://github.com/user-attachments/assets/62130497-832b-42e0-a1aa-26a2a57d385c)

**Comment by melloware** [comment]
Oh I see you don't think those files should be selectable in the open dialog. Try it with CSV enabled.

**Comment by melloware** [comment]
Confirmed adding...

```xml
    <context-param>
        <param-name>primefaces.CLIENT_SIDE_VALIDATION</param-name>
        <param-value>true</param-value>
    </context-param>
```

Does this...

![image](https://github.com/user-attachments/assets/b6710237-5c92-44c1-8056-f4bd62681908)
