### ISSUE TITLE
Google Maps: Warning popup in showcase

### ISSUE THREAD

**Issue by matsandreassen-triona** [primefaces/primefaces#12555]
### Describe the bug

The popup says: "This page can't load Google Maps properly".

It still doesn't work on our test production server which uses a properly secured API token.

![image](https://github.com/user-attachments/assets/029d4e54-bb27-457a-9bc5-9e799f08430a)

I'm encountering this in my application and I see it in the showcase itself.

### Reproducer

https://www.primefaces.org/showcase/ui/data/gmap/basic.xhtml

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.4

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

21

### Browser(s)

Firefox and Chrome

**Comment by melloware** [comment]
it looks like PrimeTek doesn't have billing enabled or paid the bill?

![image](https://github.com/user-attachments/assets/d71b5fa5-8f06-4c0c-b45b-c847e73a8e27)

**Comment by melloware** [comment]
@matsandreassen-triona take a look in the console and see what your error is from google maps. Its possible you only enabled its access from your main URL (aka Production) and maybe Localhost but disabled it from being used on any other URL.

**Comment by matsandreassen-triona** [comment]
I think I just got confused. My key was already whitelisted for the domain in question. Sorry to waste your time.

**Comment by matsandreassen-triona** [comment]
I think I just got confused. My key was already whitelisted for the domain in question. Sorry to waste your time.
