### ISSUE TITLE
Calendar: Broken popup positioning

### ISSUE THREAD

**Issue by guewin** [primefaces/primefaces#12564]
### Describe the bug

When using p:calendar in popup mode, the overlay is incorrectly placed at the end of the page.
The css positioning values are set but removed immediately afterwards. Some flickering can be observed.

It seems like #8910 / 174bb780 was the breaking change, when `jquery-plugins.js` was removed resp. replaced with `calendar/calendar.js`. Including `jquery-plugins.js` manually resolves the problem.

### Reproducer

[primefaces-test-calendar.zip]()

### Expected behavior

The popup overlay is placed correctly underneath the input component.

### PrimeFaces edition

Community

### PrimeFaces version

12+

### Theme

None

### JSF implementation

All

### JSF version

4.0.2 (myfaces), 4.0.7 (mojarra)

### Java version

17

### Browser(s)

Firefox, Chrome

**Comment by tandraschko** [comment]
Just use p:datePicker, calendar is deprecated

**Comment by melloware** [comment]
@tandraschko i submitted a minor fix for 14.0.5 which probably should have been there from the beginning.
