### ISSUE TITLE
Chart: Cannot Be Responsive

### ISSUE THREAD

**Issue by SkylerMime** [primefaces/primefaces#12572]
In order for a Chart.js element to be responsive [it must be the only child of a div element that is relatively positioned](https://www.chartjs.org/docs/latest/configuration/responsive.html#important-note).

However, the PrimeFaces p:chart element renders without the style 'position: relative', and so it cannot be responsive.

The style props should be passed to the div instead, with new canvasStyle and canvasStyleClass props for the inner canvas element.

This source code:
```xhtml
<p:chart style="position: relative; height:40vh; width:80vw" />
```
Renders as:
```html
<div id="j_idt5" class="ui-chart">
  <canvas id="j_idt5_canvas" role="img" style="position: relative; height: 114px; width: 430px; display: block; box-sizing: border-box; touch-action: auto; user-select: none;" width="430" height="114"></canvas>
</div>
```
It would need to render something like this in order to be responsive:
```html
<div class="chart-container" style="position: relative; height:40vh; width:80vw">
  <canvas id="chart"></canvas>
</div>
```
### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

2.0

### Java version

Java 11

**Comment by melloware** [comment]
14.0.5 is released please test

**Comment by SkylerMime** [comment]
Works now and looks good! Thanks!

**Comment by melloware** [comment]
Excellent!  Thanks for reporting.
