### ISSUE TITLE
Hosting namespaces on https

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#12576]
### Describe the bug

Primefaces name spaces are hosted on http://primefaces.org/ui. Is it feasible to move these to https://primefaces.org/ui to prevent redirection ?

IDE used :- Netbeans 19 now upgraded to 22.
Server : Wildfly 30
Browsers : Firefox Chrome and Safari

### Reproducer

- Used Netbeans 22 to generate a new jakarta ee 10 project.
- Updated all the links from http to https. 
- Added Primefaces to the project.
- Created a sample login form which is linked to bean that prints the id and password.
- The name spaces added to support primefaces component is xmlns:p="http://primefaces.org/ui". This is as per the guidelines set in [Get Started](http://www.primefaces.org/showcase/getstarted.xhtml?jfwid=7bff3).
- The application runs well. Displays the two input box with submit button.
- When you change the namespace from http://primefaces.org/ui to https://primefaces.org/ui, Netbeans gives an error - "No library found for namespace https://primefaces.org/ui". The program still compiles and runs, but it does not show the components. 
<img width="602" alt="Successful" src="https://github.com/user-attachments/assets/bf6619bc-26fc-46c2-8b88-0d5e631eecd4">

<img width="540" alt="Fails when upgraded from http to https" src="https://github.com/user-attachments/assets/3a4fd804-9a05-4758-a7da-10f04071826c">

[PF1.zip](https://github.com/user-attachments/files/16933987/PF1.zip)

### Expected behavior

Everyone is expected to use a secure connection and prevent unnecessary redirection in our application. Thus, i hope you can move the library from http to https.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

JDK 17

**Comment by melloware** [comment]
you are using Faces 4 so change your namespaces to not be URNs.

```xml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="jakarta.faces.facelets"
      xmlns:f="jakarta.faces.core"
      xmlns:h="jakarta.faces.html"
      xmlns:p="primefaces">
```

**Comment by ict-singapore** [comment]
I am currently using URNs for other namespaces and I am glad primefaces have adopted this approach. Your recommendation has resolved my issue.

Thank you for the swift response.

**Comment by melloware** [comment]
Excellent!
