### ISSUE TITLE
InputNumber: update `padControl` attribute to allow more flexibility

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#12570]
### Description

In case you want to enter a number with unknown number of fraction digits, you can use padControl="false" with a large decimalPlaces. Unfortunately, it doesn't look nice with prices. It would be interesting to add a "minFractionDigits" parameter to control this behaviour. For consistency, the parameter maxFractionDigits might be added.

### Describe the solution you would like

It should look like this:
```
<p:inputNumber id="input2" value="#{inputNumberView.input2}" padControl="false" decimalPlaces="10" minFractionDigits="3"
 />
```
This should print something like this:
1.000
1.123
1.100
1.0123456

**Comment by melloware** [comment]
@ritonglue i think you need to ask for this at AutoNumberic as I don't see any option for `minFractionDigits.

See: https://autonumeric.org/configurator

Issues: https://github.com/autoNumeric/autoNumeric/issues

**Comment by melloware** [comment]
Hmm it might be the `allowDecimalPadding` option and instead of being a true/false it looks like it can also take a number (for number of places)

> Allow padding the decimal places with zeros. If set to 'floats', padding is only done when there are some decimals (up to the number of decimal places from the decimalPlaces variable). If set to an integer, padding will use that number for adding the zeros. If set to true it will always pad the decimal places with zeroes, and never if set to false.

**Comment by ritonglue** [comment]
Yes `allowDecimalPadding` set with a number does the trick ! Too bad that the autonumeric playground doesn't allow to test it with a number.

The option `padControl` already uses `allowDecimalPadding` so a solution would be to change the class `org.primefaces.component.inputnumber.InputNumberBase` and allow padControl to return a String instead of a Boolean.

**Comment by melloware** [comment]
Yep it's on my list to fix!

**Comment by melloware** [comment]
PR submitted.
