### ISSUE TITLE
Datatable reflow mode displayed incorrect if column has style width

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1258]
I have a simple table where two columns have restricted width:

```
<p:column headerText="Art.-Nr." style="width: 5em;">
<p:column headerText="Name">
<p:column headerText="Barcode" style="width: 8em;">
```

This produces incorrect results when reflow mode is activated on resize. See image.

![pf-reflow-width-bug-1](https://cloud.githubusercontent.com/assets/5265550/13974790/32801a10-f0af-11e5-97ca-b729c6015868.jpg)

**Mobile fix:**

	@media (max-width: 35em) 
	{
		.ui-table-reflow.ui-responsive td, .ui-table-reflow.ui-responsive th 
		{
		    max-width: 100% !important;
		    min-width: 100% !important;
		    width: 100% !important;
		}
	}

**Desktop fix**

_i am not 100% sure about the max-width, maybe theme dependent_

	@media (max-width: 45em) 
	{
		.ui-datatable-reflow .ui-datatable-data td[role="gridcell"]
		{
		    max-width: 100% !important;
		    min-width: 100% !important;
		    width: 100% !important;
		}
	}

**Comment by melloware** [comment]
Thank you for the CSS workaround.  I don't see PF core fixing this issue and since its easily fixed with CSS going to close the issue.
