### ISSUE TITLE
DataTable: Border is removed on focus for all elements within a DataTable

### ISSUE THREAD

**Issue by mstichweh** [primefaces/primefaces#12597]
### Describe the bug

There is a new styling rule for the DataTable component which removes the border for each element of a cell:
```
.ui-datatable-data td[role="gridcell"]:focus, .ui-datatable-data td[role="gridcell"] *:focus, .ui-datatable-data td[role="grid"] [tabindex="0"]:focus {
	outline: var(--primary-color,#90caf9);
	outline-style: solid;
	outline-width: 2px;
	border: 0;
}
```

This is a problem when buttons are used within a DataTable cell, for example. Because the border is removed on button click which will change the size and styling until the button will loose the focus again.  
There is no easy way to overwrite this rule, so it would be nice, if this rule (`.ui-datatable-data td[role="gridcell"] *:focus`) could be assigned to PrimeFaces component classes or just be removed.

### Reproducer

The rule can be seen in the showcase (http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml) for the cell edit buttons, if `:focus` is enabled within the development tools element inspector.

### Expected behavior

PrimeFaces styles should not style arbitrary elements they should be limited to PrimeFaces components.

### PrimeFaces edition

None

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
You are right and i don't think that selector even needs to be there.

**Comment by melloware** [comment]
Others have mentioned this too: https://github.com/orgs/primefaces/discussions/2500
