### ISSUE TITLE
p:media cann't display pdf when use streamcontent features

### ISSUE THREAD

**Issue by buleseli** [primefaces/primefaces#12590]
### Describe the bug

cann't show pdf document when use streamcontent

### Reproducer

[primefaces-test-8.0.zip](https://github.com/user-attachments/files/16992194/primefaces-test-8.0.zip)

### Expected behavior

show the right pdf! 

### PrimeFaces edition

None

### PrimeFaces version

8.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

### Browser(s)

Google Chrome 109.0.5414.75

**Comment by tandraschko** [comment]
Primefaces 8 is not supported anymore since years.

**Comment by buleseli** [comment]
i will try  it in PF14 later

**Comment by melloware** [comment]
Reproducer showing it works fine in PF14: 
[pf-12590.zip](https://github.com/user-attachments/files/16993119/pf-12590.zip)

**Comment by melloware** [comment]
Yep 8.0 is out of date at this point i highly recommend you upgrade.

**Comment by buleseli** [comment]
a lot of things  i have  to do if  plan upgrade  to 13 or 14. i will try my best to  persuade  my boss ！tks for  providing   so nice  jsf ui suits
