### ISSUE TITLE
h:link in menuitem of panelmenu causes "ghost" links

### ISSUE THREAD

**Issue by dpassler** [primefaces/primefaces#1259]
When i have <p:panelMenu> and inside this panelMenu i have any <p:menuItem> and inside the menuItem i have <h:link> then it causes rendering of "ghost" menu links (with no text and link href "#")

**Comment by tandraschko** [comment]
Will close it for now as there is no information how the reproduce it.
If the issue is still there in 6.1 or 6.2-SNAPSHOT, please create new issue with all informations requested by our issue template.
