### ISSUE TITLE
Html5FacesContextResponseWriter: Reduce instantiation

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#12591]
Looking at:
https://github.com/primefaces/primefaces/blob/6e479dd2666eadcfef77edc4fc0e21829a41735d/primefaces/src/main/java/org/primefaces/application/factory/Html5FacesContext.java#L44
a new `Html5FacesContextResponseWriter` instance is being created each time `setResponseWriter` gets invoked.
Maybe check whether the `responseWriter` was already an instance of `Html5FacesContextResponseWriter` before creating a new one?
Some components play with `setResponseWriter` to temporarily change its behavior. This would trigger unnecessary additional wrappers each time.

**Comment by melloware** [comment]
PR submitted if you want to review!

**Comment by fcorneli** [comment]
See comments on the PR.

**Comment by melloware** [comment]
OK thanks for the tip I updated the PR and did a slightly optimized version of what you sent me do you mind testing it?
