### ISSUE TITLE
boxWidth and boxHeight for ImageCropper

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#126]
The ImageCropper component lacks an option to set the displayed image size. In the current state I don't see a way to limit the maximum size when using images with higher resolution without any preprocessing.
The underlying JavaScript library JCrop supports this feature by using the the boxWidth and boxHeight parameters.
Simply adding these attributes to the renderer code seems to be enough to enable this feature in the ImageCropper component.

**Comment by cagataycivici** [comment]
Reverted as values should be 0 as integer by default.

**Comment by neXus1987** [comment]
in Primefaces 7.0 the ImageCropper boxWidth and boxHeight won´t work as aspected.  The image is smaller, but the selection area is too big. As i googled, there is something with trueSize for jCrop, maybe this will help!?
