### ISSUE TITLE
Datatable CellEdit cannot get focus in EditMode after Tab.

### ISSUE THREAD

**Issue by YogeshMKumbhar** [primefaces/primefaces#12600]
### Describe the bug

This feature was already present in Primefaces 12. If dataTable is in cellEdit mode, on pressing tab button after editing first cell, focus was shifting to next editable cell with active focus. However, from Primefaces 13 onwards, if you press tab, then cell opens in edit mode, but, focus is somewhere else. I have to again press tab key to make it focusable. The same problem occurs when using a phone(andriod). Here I have to tap twice to get the same effect.

### Reproducer

Create a `DataTable` make it `editable=true` `editMode=cell`.
Start editing cell after editing press `Tab` key next cell will be in edit mode but focus is elsewhere.

### Expected behavior

After pressing `Tab` key next editable cell should be in active focus.

### PrimeFaces edition

Community

### PrimeFaces version

13.0

### Theme

saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

Chrome, Firefox, Edge

**Comment by melloware** [comment]
Thanks working on this!

**Comment by melloware** [comment]
@YogeshMKumbhar you can test my changes here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/edit.xhtml TAB key between cell editors should work.

**Comment by YogeshMKumbhar** [comment]
Yes checked now its working. Really appreciate your response time. Thanks a lot.

**Comment by melloware** [comment]
Here is a MonkeyPatch you can use right now.

```js
if (PrimeFaces.widget.DataTable) {

  PrimeFaces.widget.DataTable.prototype.tabCell = function(cell, forward) {
        var targetCell = forward ? cell.nextAll('td.ui-editable-column:first') : cell.prevAll('td.ui-editable-column:first');
        if(targetCell.length == 0) {
            var tabRow = forward ? cell.parent().next() : cell.parent().prev();
            targetCell = forward ? tabRow.children('td.ui-editable-column:first') : tabRow.children('td.ui-editable-column:last');
        }

        var cellEditor = targetCell.children('div.ui-cell-editor'),
        inputContainer = cellEditor.children('div.ui-cell-editor-input');

        if(inputContainer.length) {
            var inputs = inputContainer.find(':input[type!=hidden]'),
            disabledInputs = inputs.filter(':disabled:not([data-disabled-by-editor="true"])');

            if(inputs.length === disabledInputs.length) {
                this.tabCell(targetCell, forward);
                return;
            }
        }

        this.showCellEditor(targetCell);
    };
};
```
