### ISSUE TITLE
PanelGrid: Wrong position of inner menuButton, when embedded in dialog

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#12609]
### Describe the bug

![Dialog-PanelGrid-MenuButton-WrongPosition](https://github.com/user-attachments/assets/6f93b1db-5d15-4fe6-ad49-31ce1276543a)

### Reproducer

```
    <p:panelGrid style="width:20em" columns="0" layout="tabular">
        <f:facet name="header">
            <p:row>
                <p:column>
                    <p:menuButton value="Options">
                        <p:menuitem value="Option 1" />
                        <p:menuitem value="Option 2"/>
                        <p:menuitem value="..."/>
                    </p:menuButton>
                </p:column>
                <p:column>Col B</p:column>
                <p:column>Col C</p:column>
            </p:row>
        </f:facet>
    [...]
    </p:panelGrid>
```
[reproducer-12609.zip](https://github.com/user-attachments/files/17047734/reproducer-12609.zip)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### Theme

irrelevant

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

irrelevant

**Comment by RohdeSchwarz-SDC** [comment]
Note: This bug did not occur in version 13.x

**Comment by melloware** [comment]
here is your reproducer:
[pf-12609.zip](https://github.com/user-attachments/files/17048687/pf-12609.zip)

For me it looks OK?

![image](https://github.com/user-attachments/assets/48452121-47de-4b65-87b6-39fe251abfd5)

**Comment by RohdeSchwarz-SDC** [comment]
Thanks for your investigation.

It looks like something else in my configuration causes the wrong menuButton's position. I will dig deeper...

**Comment by melloware** [comment]
also i am using 14.0.5 in my demo i don't know if that is different than your 14.0.4?

**Comment by melloware** [comment]
I actually think it was this fix in 14.0.5 that fixed it: https://github.com/primefaces/primefaces/pull/12476

**Comment by RohdeSchwarz-SDC** [comment]
After updating to version 14.0.5 eyerything looks correct ✅

**Comment by melloware** [comment]
Excellent!
