### ISSUE TITLE
ColumnToggler: not using column visibility from bean property

### ISSUE THREAD

**Issue by hg-schneider-gl** [primefaces/primefaces#12601]
### Describe the bug

The reproducer contains a DataTable with a ColumnToggler. The initial visibility value of each column is read from the bean. All but the first coIumn are initially visible.
There is a button "Reset" which sets the visibility for all columns, including the first, to true in the bean. 
The button updates "@form".
When I press the button nothing happens using version 10.0.0, 11.0.0, 12.0.0, 13.0.10 or 14.0.5
When I press the button the columns appears using version 6.2, 7.0 or 8.0
In Version 14.0.5, after pressing "Reset", I can see that the new values for visibility are fetched from the bean but, as mentioned above, the column does not appear.

### Reproducer

[primefaces-column-toggler-issue.zip](https://github.com/user-attachments/files/17039917/primefaces-column-toggler-issue.zip)

1. Press "Reset" button
2. Column does not appear
3. Remove the ColumnToggler and restart
4. Press "Reset" button
5. Column appears
6. Add ColumnToggler back again
7. Set Primefaces version in pom.xml to 8.0 and restart
8. Press "Reset" button
9. Column appears

### Expected behavior

The column should appear when pressing "Reset".

### PrimeFaces edition

Community

### PrimeFaces version

13.0.10

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
@hg-schneider-gl 

The issue is that a fix made a long time ago requested by users to send the current UI state to the backing bean.

![image](https://github.com/user-attachments/assets/68d2dc6e-c193-4d3f-80cf-cf447e257ff2)


So in your reproducer i simple changed the Reset button NOT to submit the whole form with `process="@this"`.

```xml
<p:commandButton value="Reset" action="#{testView.resetVisibility()}" update="@form" process="@this"/>
```

**Comment by hg-schneider-gl** [comment]
@melloware 
I changed my project the same way and this fixed my issue.
Thank you for your support!
