### ISSUE TITLE
JPALazyDataModel: Case insentive with Numeric column error

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12604]
### Describe the bug

Based on https://github.com/primefaces/primefaces-test/issues/430 from @SkylerMime and @FlipWarthog 

If you use `caseInsenstive` queries it should NOT try and do an `UPPER()` function on numeric columns.

Error:

```
org.hibernate.exception.SQLGrammarException: 
could not prepare statement [incompatible data type in operation in statement [select count(tj1_0.id) from TestJpa tj1_0 where upper(tj1_0.decimalCol) like ?]] [select count(tj1_0.id) from TestJpa tj1_0 where upper(tj1_0.decimalCol) like ?]
```

### Reproducer

See: https://github.com/primefaces/primefaces-test/issues/430

### Expected behavior

it should not build an invalid query

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### Theme

ALL

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

ALL

**Comment by tandraschko** [comment]
IMO we should try to throw a exception like: caseInsensitiv does Not make Sense with numbers

**Comment by melloware** [comment]
Well CaseInsensitive is set on the whole table not per column so I was going to disable it on Numeric columns?

**Comment by FlipWarthog** [comment]
And it's only the caseSensitive setting that's an issue? None of this fails for numeric columns?
https://github.com/primefaces/primefaces/blob/d3f318b8d69aa74c482959dd914e03614a4456fb/primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java#L180-L199

**Comment by melloware** [comment]
Testing so far that all works the with thee JPA tester now.    I guess maybe we can check and ONLY if the type is `String.class` allow Case Sensitivity?

**Comment by FlipWarthog** [comment]
Makes sense to me.

**Comment by tandraschko** [comment]
What about char?

**Comment by melloware** [comment]
How about this `boolean isCaseSensitive = caseSensitive || !(CharSequence.class.isAssignableFrom(pd.getPropertyType()) || pd.getPropertyType() == char.class);`

That gets all `String, CharSequence, char` values.

**Comment by tandraschko** [comment]
+1
