### ISSUE TITLE
AutoComplete dding Watermark with scrollable Dropdown is hiding the options on IE11

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primefaces#1260]
Consider an Auto Complete with dropdown and has Watermark for it:

```
<p:autoComplete id="dd" dropdown="true" scrollHeight="200" value="#{autoCompleteView.txt6}" completeMethod="#{autoCompleteView.completeText}" />
<p:watermark for="dd" value="Search with a keyword" id="watermark" />
```

On IE 11 the options panel (scrollable) will disappear on clicking of scroll bar.
This does not happen for first time, here is the scenario steps:
- Type a search text [Example: Hello].
- Option panel shows up with suggestions, select one.
- Remove the selected test completely from text box, by pressing backspace.  
- Now click on dropdown button or search for a text by typing.
- Next time the options panel shows up. It will disappear  when user click on scroll bar.

This issue is occurring only in versions Primefaces 5.2 and above, Primefaces 5.1 will work just fine.

Here is the screen record video of issue: [https://youtu.be/ivBNuDc9_Xo](https://youtu.be/ivBNuDc9_Xo)

**Comment by tandraschko** [comment]
Does it work when you use placeholder instead of p:watermark?

**Comment by melloware** [comment]
Yes for IE11 no need to use p:watermark simply use placeholder like..
```xml
<p:autoComplete  value="#{autoCompleteView.txt1}" placeholder="test"/>
```
Tested and working fine.  Closing as WontFix.
