### ISSUE TITLE
Native tooltip [title] does not change for FileUpload component in advanced mode

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primefaces#1261]
By default native HTML `input type="file"` will have a tolltip specific to browser.
On Firefox its: _No file selected._
On chrome its: _No file chosen_
After a file has been selected by user, the tolltip will change to selected file name.

On Primefaces FileUpload with Basic mode this works just as expected.
But when used as Advanced mode the tooltip will never change, it will always be same.

Apart from this issue, it would be good to have tooltip attribute for Fileupload component.

**Comment by sudheerj** [comment]
The issue is replicated with advanced file upload component.We will get back to you soon with more information.

**Comment by Miraje** [comment]
Hi @sudheerj do you have any news on this subject?

Any help on this subject would be very appreciated! thanks in advance!

**Comment by maxicoof** [comment]
<script type="text/javascript">
                    $(document).ready(function () {
                       
                        $('#uploadF_input').prop("title", "Select xyz");
                    });

**Comment by melloware** [comment]
@doleron this one may be related to the ticket you are fixing?

**Comment by doleron** [comment]
@melloware I think so. Including `title='my custom title'` has no effect in either advanced or simple mode. Advanced mode has custom titles for each button now. May I add a `title` attribute to work just for simple mode?

**Comment by melloware** [comment]
Sure I don’t see why not
