### ISSUE TITLE
DataTable: wrong initial column header width when using tableStyle="width:auto"

### ISSUE THREAD

**Issue by Rene-Stoeckel** [primefaces/primefaces#12621]
### Describe the bug

We plan to use the setting tableStyle="width:auto" for our DataTables. On first attempt we noticed that when using tableStyle="width:auto" the initial column header with of a column does not align to the auto sized column width.

See screenshot.
![ScreenShot908](https://github.com/user-attachments/assets/00a0062c-f039-497e-95db-4c523f4074dc)

The column width can be adjusted however, also the new key combination ALT-W does fix the misalignment of the column header width.
We are using cellNavigation=true.

### Reproducer

We are just using dataTable with tableStyle="width:auto" and cellNavigation=true.

```xml
<p:dataTable id="table" tableStyle="width:auto" widgetVar="table" var="role" 
	value="#{tool.roles}" selection="#{tool.selectedRoles}" 
	rowKey="#{role.ID}" size="small" selectionMode="multiple"
    sortMode="single" resizableColumns="true" 
	liveResize="true" scrollable="true" rows="#{tool.rows}" paginator="true" paginatorPosition="bottom"
    paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
    currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords} items" 
	rowsPerPageTemplate="#{tool.rowsPerPageTemplate}" rowIndexVar="row_index" 
	cellNavigation="true">
```

### Expected behavior

It would be nice to have the width of a column and its column header set to the same width initially when using tableStyle="width:auto".

### PrimeFaces edition

Community

### PrimeFaces version

14.0.3

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

21

### Browser(s)

Chrome Version 126.0.6478.127 (Offizieller Build) (64-Bit), Microsoft Edge Version 126.0.2592.68 (Offizielles Build) (64-Bit)

**Comment by melloware** [comment]
See this ancient ticket: https://github.com/primefaces/primefaces/issues/2788

**Comment by Rene-Stoeckel** [comment]
Ah, I see. Thank you for the quick response. We'll try this workaround. Thank you.

**Comment by melloware** [comment]
Let me know how it goes.

**Comment by Rene-Stoeckel** [comment]
I tried to put it under a <p:ajax event="page" oncomplete="const columns ..."> tag under the <p:datatable but now it is only triggered, when the pagination page is changed which makes sense though. What would be the correct way to trigger it initially on datatable load?

**Comment by melloware** [comment]
in a JS script you include on the page it will run when Jquery knows the document has finished loading.

```js
$(document).ready(function() {
    const columns = PF('table').getThead().find('tr > th.ui-resizable-column');
            
  columns.each(function() {
      PF('table').autosizeColumnWidth($(this));
  });
});

**Comment by Rene-Stoeckel** [comment]
Ah, I was wrong here. I just had to put it to the command button oncomplete that triggers the filling of the table, my bad. 
It's fine for us this way now. Many thanks!
