### ISSUE TITLE
TreeTable: poor performance in paginated treeTable with large number of nodes

### ISSUE THREAD

**Issue by skybber** [primefaces/primefaces#12625]
### Describe the bug

The **treeTable** component experiences significant performance degradation with large datasets when pagination is enabled. This is caused by an unbounded iteration of root nodes in the `processNode` method, which processes all nodes instead of restricting to nodes on the current page.

### PrimeFaces edition

None

### PrimeFaces version

13.0

### JSF implementation

MyFaces

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
@skybber do you have a proposed fix?  I assumed it always walks all the records.  I would assume the Datatable does the same thing?

**Comment by skybber** [comment]
The DataTable currently iterates from `first()` to `last()`. I have  a fix that resolves the issue, but I’m unsure if it might cause issues elsewhere. I could create a PR.

**Comment by melloware** [comment]
Please create a PR so we can review.
