### ISSUE TITLE
p:chart rendered as small size and missing the responsive ability when update from previous version to new 14.0.5

### ISSUE THREAD

**Issue by dengbingaliyun** [primefaces/primefaces#12624]
### Describe the bug

I updated my project's primefaces to new version 14.0.5. And then the charts were rendered as small size and missing the responsive ability.

code:
`<p:chart id="chart" value="#{view.json}" style="width: 100%; height: 250px;"/>`
previous rendered as:
``` 
<div id="form:chart" class="ui-chart">
<canvas id="form:chart_canvas" role="img" style="width: 100%; height: 250px; display: block; box-sizing: border-box; touch-action: none; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);" width="1364" height="250"></canvas>
</div>
```
![image](https://github.com/user-attachments/assets/a250047c-801a-4893-9855-c0719aad3e10)

version 14.0.5 rendered as:
```
<canvas id="form:chart_canvas" role="img" width="300" height="150" style="display: block; box-sizing: border-box; touch-action: none; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); height: 150px; width: 300px;"></canvas>
```

![image](https://github.com/user-attachments/assets/4706528d-191d-4f8a-9b02-0ef4e5ed5c5b)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

21

### Browser(s)

chrome

**Comment by melloware** [comment]
@dengbingaliyun see: https://github.com/primefaces/primefaces/issues/12572

There are two new properties `canvasStyle` and `canvasStyleClass` and the main `style` and `styleClass` now go on the outer DIV to make it responsive properly.
