### ISSUE TITLE
Chart: Chart widget and Client API documentation broken?

### ISSUE THREAD

**Issue by tpfeil** [primefaces/primefaces#12633]
### Describe the bug

While updating to PrimeFaces 14.0.5 and integrating Chart.js along with the [chartjs-chart-matrix](https://chartjs-chart-matrix.pages.dev/) plugin, I encountered some chart-related issues. After browsing the showcase and documentation, a few additional problems surfaced.

The **PrimeFaces.widget.Chart** object is no longer available, making it impossible to extend the Chart widget as before.

Additionally, the Client API Documentation returns a 404 error when accessing the following URL: https://github.com/primefaces/primefaces/blob/master/docs/14_0_0/jsdocs/classes/src_PrimeFaces.PrimeFaces.widget.Chart.html

### PrimeFaces edition

None

### PrimeFaces version

14.0.5

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by tpfeil** [comment]
Manually adding **PF's chart/chart.js** as a **@ResourceDependency** fixed the issue for my custom chart component.

`@ResourceDependency(library = "primefaces", name = "chart/chart.js")
`

However, the documentation still seems broken.

**Comment by melloware** [comment]
Yep the real link is here: https://primefaces.github.io/primefaces/jsdocs/classes/src_PrimeFaces.PrimeFaces.widget.Chart-1.html

I will fix it.
