### ISSUE TITLE
Tooltip: Arrow position wrong using `my` and `at` custom positioning

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12636]
### Describe the bug

For the following:

```xml
<p:tooltip for="custom" value="Enter your username" my="left top" at="left bottom"/>
```

it produces:
![image](https://github.com/user-attachments/assets/f57eaa46-1a7d-4749-a446-4a2a77d8d272)

### Reproducer

See above

### Expected behavior

The arrow should be correct based on position

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### Theme

ALL

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

ALL

**Comment by majkers** [comment]
@melloware there is something wrong with this in 15.06. Have a look at showcase:

<img width="392" height="113" alt="Image" src="https://github.com/user-attachments/assets/1f473912-ffab-4b70-94e8-fbde9e8255b8" />

**Comment by melloware** [comment]
@majkers yep something must have changed this does not look right.  Please open a new ticket.
