### ISSUE TITLE
The roles in the table rows/headers can be customized

### ISSUE THREAD

**Issue by watermelon-pan** [primefaces/primefaces#12644]
### Describe the bug

```
<th class="p-element p-sortable-column ng-star-inserted" ng-reflect-field="Email" tabindex="0" role="columnheader" aria-sort="none"></th>
```
When sorting is enabled, "role=columnheader" might cause screen readers (NVDA) to misunderstand. It is hoped that the role can be customized.

### PrimeFaces edition

None

### PrimeFaces version

15.0.0

### Theme

accessibility

### JSF implementation

Mojarra

### JSF version

1.8

### Java version

1.8.0_301

**Comment by melloware** [comment]
@watermelon-pan you want the PrimeNG issues not PrimeFaces JSF.
