### ISSUE TITLE
TabView: Dynamic Tabs in will cause "id has already been found in the view."

### ISSUE THREAD

**Issue by cidylong** [primefaces/primefaces#12658]
### Describe the bug

When try to generate a set of Tabs under TabView UIComponents by given Java Objects conditional with ui:include, server throws 
    "Error Rendering View[/contracts/contractTabViewEdit.xhtml]
    java.lang.IllegalStateException: Component ID j_idt117:id has already been found in the view.",  

 tried JSF(xhtml) and Java program, get the same result.

### Reproducer

Create a simple multiple Tabs under one TabView UIComponent.

Try JSF first:

    <p:tabView id="contract_tabview">
                    <p:ajax event="tabChange" listener="#{contractOPStaffWebController.onTabChange}" update="@parent"/>
                    <p:tab title="Contract Details">
                        <c:if test="#{contractOPStaffWebController.isContractEditMode_edit()}">
                            <ui:include src="contractEdit.xhtml" />
                        </c:if>
                        <c:if test="#{not contractOPStaffWebController.isContractEditMode_edit()}">
                            <ui:include src="contractView.xhtml" />
                        </c:if>
                        <ui:include src="contractEdit.xhtml"/>
                    </p:tab>
                    <p:tab title="Contracted Items">
                        <ui:include src="contractItemList.xhtml"/>
                    </p:tab>
                    <p:tab title="Contract Item Details">
                        <c:if test="#{contractOPStaffWebController.isContractEditMode_edit()}">
                            <ui:include src="contractItemEdit.xhtml"/>
                        </c:if>
                        <c:if test="#{not contractOPStaffWebController.isItemEditMode_edit()}">
                            <ui:include src="contractItemView.xhtml"/>
                        </c:if>
                    </p:tab>
                </p:tabView>

or use UIComponent to generate TabView UIComponent from back end.

    public class ContractTabComp implements Serializable {
    private static final String CONTRACT_EDIT = "contractEdit.xhtml";
    private static final String CONTRACT_VIEW = "contractView.xhtml";
    private static final String CONTRACT_ITEM_LIST = "contractItemList.xhtml";
    private static final String ITEM_EDIT = "contractItemEdit.xhtml";
    private static final String ITEM_VIEW ="contractItemView.xhtml";
    private TabView tv;
    private int tabIndex;
    private Tab currentTab;

    public TabView getTv() {return tv;}
    public int getTabIndex() {return tabIndex;}
    public Tab getCurrentTab() {return currentTab;}

    public ContractTabComp() {
        init();
    }
    protected void init() {
        tv = new TabView();
        tv.setId("contract_tab_view");
        tv.setDynamic(true);
        tv.setOnTabChange("contractOPStaffWebController.onTabChange");
    }
    public void popupTabviewContext(ContractPack pack, ContractOPStaffWebController.ContractEditView contractEditView, ContractOPStaffWebController.ContractItemEditView contractItemEditView){
        if(pack.getContract() != null){
            Tab contractTab = new Tab();
            contractTab.setId("contract_tab");
            switch (contractEditView){
                case Edit -> {
                    contractTab.setTitle("Contract Tab - Edit");
                    FaceletContext faceletContext = (FaceletContext) FacesContext.getCurrentInstance().getAttributes().get(FaceletContext.FACELET_CONTEXT_KEY);
                    try {
                        faceletContext.includeFacelet(contractTab, CONTRACT_EDIT);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
                case View -> {
                    contractTab.setTitle("Contract Tab - View");
                    FaceletContext faceletContext = (FaceletContext) FacesContext.getCurrentInstance().getAttributes().get(FaceletContext.FACELET_CONTEXT_KEY);
                    try {
                        faceletContext.includeFacelet(contractTab, CONTRACT_VIEW);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
            }
            tv.getChildren().add(contractTab);
        }
        if(!pack.getContractitemSet().isEmpty()){
            Tab itemListTab = new Tab();
            itemListTab.setId("contract_item_list_tab");
            itemListTab.setTitle("Item List");
            FaceletContext faceletContext = (FaceletContext) FacesContext.getCurrentInstance().getAttributes().get(FaceletContext.FACELET_CONTEXT_KEY);
            try {
                faceletContext.includeFacelet(itemListTab, CONTRACT_ITEM_LIST);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            tv.getChildren().add(itemListTab);
        }
        if(pack.getCurrentItem() != null){
            Tab itemTab = new Tab();
            itemTab.setId("contract_item_tab");
            switch (contractItemEditView){
                case Edit -> {
                    itemTab.setTitle("Contract Item - Edit");
                    FaceletContext faceletContext = (FaceletContext) FacesContext.getCurrentInstance().getAttributes().get(FaceletContext.FACELET_CONTEXT_KEY);
                    try {
                        faceletContext.includeFacelet(itemTab, ITEM_EDIT);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
                case View -> {
                    itemTab.setTitle("Contract Item - View");
                    FaceletContext faceletContext = (FaceletContext) FacesContext.getCurrentInstance().getAttributes().get(FaceletContext.FACELET_CONTEXT_KEY);
                    try {
                        faceletContext.includeFacelet(itemTab, ITEM_VIEW);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
            }
            tv.getChildren().add(itemTab);
        }
    }
    }

Plus ui binging as :

    <p:tabView binding="#{contractOPStaffWebController.contractTabComp.tv}"/>

All failed. result as:
![Screenshot 2024-10-01 at 10 47 28 pm](https://github.com/user-attachments/assets/0f3ab941-317a-4647-9903-2b6c6298e7f6)

Any possible solution or work around?

Please advise!

### Expected behavior

Should be able to render different TaView with dynamic Tabs that depend on ContractPack structure in need of.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### Theme

default

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

JDK 17.0.3

### Browser(s)

Safari 18, Chrome 129.0

**Comment by tandraschko** [comment]
I think you should use the DataModel example of http://www.primefaces.org/showcase/ui/panel/tabView.xhtml

you use a very error prone mix of JSTL, dynamic component creating, dynamic includes. This is more a user error as a bug in PrimeFaces.
