### ISSUE TITLE
DataTable/TreeTable: allow horizontal scrollbar to the top

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12651]
### Description

Request from a client and also found past requests on the PF Forum.

https://stackoverflow.com/questions/33565238/move-scrollbar-to-top-in-datatable-primefaces

### Describe the solution you would like

A new `scrollBarPosition="top"` attribute to change from the default `"bottom"`

### Additional context

![image](https://github.com/user-attachments/assets/7afa73ea-9567-41f0-8157-2f523fce31d9)

**Comment by fcorneli** [comment]
How about also allowing "both"?

**Comment by melloware** [comment]
I don't think its possible to have "both" with CSS only.

**Comment by fcorneli** [comment]
Indeed not possible... checked the code... rotate 180 and 180... lovely CSS. :)

**Comment by tandraschko** [comment]
JFYI i dont wanna block this features
thats nice IMO
but touching 14 files and many lines of code instead of 2-3 lines CSS is not the right way
