### ISSUE TITLE
Datatable: filtering with BigDecimal

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#12666]
### Describe the bug

If  a column in a dataTable is of type BigDecimal, you can't filter it easily because you have to type the exact number of decimals. One should use `compareTo` instead of `equals` with BigDecimal.

### Reproducer

To test it you can use the showcase:

Add a property to `org.primefaces.showcase.domain.Customer` such as:
`private BigDecimal price = new BigDecimal("4.00")`.

In `ui/data/datatable/filter.xhtml` add the column:
```
<p:column field="price" filterMatchMode="exact">
     <h:outputText value="#{customer.price}" >
           <f:convertNumber minFractionDigits="0" maxFractionDigits="2"/>
      </h:outputText>
</p:column>
```

### Expected behavior

If I type 4, the rows with price 4 should appear.

### PrimeFaces edition

None

### PrimeFaces version

15.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
I could be wrong but it looks like all filters convert the raw value to String for comparison and the exact filter constraint does this..

```java
public class ExactFilterConstraint extends StringFilterConstraint {

    private static final long serialVersionUID = 1L;

    @Override
    protected BiPredicate<String, String> getPredicate() {
        return String::equalsIgnoreCase;
    }
}
```

**Comment by melloware** [comment]
@Rapster should `equals` do ignorecase and `exact` be case sensitive.  It seems backwards to me?

**Comment by FlipWarthog** [comment]
@melloware I think there's a couple things going on here that might need looking at:
1. Both of `ExactFilterConstraint` and `EqualsFilterConstraint` extend `StringFilterConstraint`, but shouldn't `EqualsFilterConstraint` extend `ComparableFilterConstraint` with:
```java
    @Override
    protected BiPredicate<Comparable, Comparable> getPredicate() {
        return (o1, o2) -> o1.compareTo(o2) == 0;
    }
```
2. `StringFilterConstraint`'s `toString` method is already `toLowerCase`ing the value/filter, so `String::equals` vs `String::equalsIgnoreCase` shouldn't make a difference.

Context: from the `compareTo` javadocs on `BigDecimal`:
> ... Two BigDecimal objects that are equal in value but have a different scale (like 2.0 and 2.00) are considered equal by this method. ...

**Comment by melloware** [comment]
@FlipWarthog agreed the things you pointed out are wonky.
