### ISSUE TITLE
CSP violation with JQuery JS file bundled in Primefaces 13.0.10 JAR

### ISSUE THREAD

**Issue by gchakilam** [primefaces/primefaces#12669]
I am using PF 13.0.10 JAR and turned on PrimeFaces.CSP to true in my web.xml file.. Below is CSP policy config from web.xml.
It is creating nonce and all my custom JS files has in them when defined in XHTML files including jquery.js files that are part of PF Jar.
All looking but I get stuck with below error in JQuery js file.

jquery.js.xhtml?ln=primefaces&v=13.0.10&v=13.0.10:2 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' *.googleapis.com *.google-analytics.com *.google.com *.gstatic.com 'nonce-YjMxMDFlNzYtMDQ1ZC00MDIxLWEzMjktZmJlYjcxNTYyMzhl'". Either the 'unsafe-inline' keyword, a hash ('sha256-XSwPJLFPIrY0arrFNzkbsviBtASy6R4f6Lp9fQ1YZV0='), or a nonce ('nonce-...') is required to enable inline execution.

function m(e, t, n) {
        var r, i, o = (n = n || C).createElement("script");
        if (o.text = e,
        t)
            for (r in u)
                (i = t[r] || t.getAttribute && t.getAttribute(r)) && o.setAttribute(r, i);
        **n.head.appendChild(o).parentNode.removeChild(o)**
    }

Violation occurs on line- n.head.appendChild(o).parentNode.removeChild(o)

JQuery version is 3.7.0 (Bundled with PF 13.0.10 JAR)

I am running  with Java 8 on GF 5.1. Not sure PF14 has fix for this but I can't migrate to it because of Java version upgrade limitation on my side. Looking for some help here, Please advise.

<context-param>
		<param-name>primefaces.CSP</param-name>
		<param-value>true</param-value>
	</context-param>
		<context-param>
		<param-name>primefaces.CSP_POLICY</param-name>
		<param-value>script-src 'self' *.googleapis.com *.google-analytics.com *.google.com *.gstatic.com</param-value>
	</context-param>	
	<context-param>
		<param-name>primefaces.CSP_POLICY</param-name>
		<param-value>object-src 'none'</param-value>
	</context-param>
	<context-param>
		<param-name>primefaces.CSP_POLICY</param-name>
		<param-value>img-src 'self'</param-value>
	</context-param>		
		<context-param>
		<param-name>primefaces.CSP_POLICY</param-name>
		<param-value>style-src 'self'</param-value>
	</context-param>

**Comment by melloware** [comment]
I have a feeling it might be non-PF code as we use CSP just fine in 13.0.10?  Can you create a reproducible test case?
