### ISSUE TITLE
Datatable: Blue selection around cells

### ISSUE THREAD

**Issue by Raffine64** [primefaces/primefaces#12671]
### Describe the bug

now when I click in a cell on a basic datatable, I get the cell border in blue.
It was not the case in previous PF versions (before 14).

![image](https://github.com/user-attachments/assets/efe70cbf-8760-4926-ab97-71481e5862bb)
![image](https://github.com/user-attachments/assets/b6c82734-cf5e-4aa6-966a-8626c6827ddb)

### Expected behavior

no blue border

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Chrome Version 129.0.6668.60 (Official Build) (64-bit) Windows 10

**Comment by melloware** [comment]
@Raffine64 that is the new keyboard support for using arrow keys to navigate cells: https://github.com/primefaces/primefaces/pull/11975

If you don't want that behavior simply turn it off on your datatable with `cellNavigation="false"`
