### ISSUE TITLE
Schedule - tooltip transparent

### ISSUE THREAD

**Issue by danillotparreira** [primefaces/primefaces#12677]
Tooltip with transparent background in schedule

https://github.com/primefaces/primefaces/blob/ddf353948a25bea0fe1fcbe6853c331c4f769328/primefaces/src/main/resources/META-INF/resources/primefaces/schedule/build/src/main.css#L8

![image](https://github.com/user-attachments/assets/c15a99b0-c6f7-4c1c-966f-63e134605d2d)
![image](https://github.com/user-attachments/assets/38767184-188b-4df8-912c-706b6b0b6b69)
![image](https://github.com/user-attachments/assets/224c863d-124c-40a9-a06a-ba9398fee40d)
Solution: Remove single quotes

**Comment by melloware** [comment]
Fixing for 14.0.6

**Comment by danillotparreira** [comment]
Still have this error
