### ISSUE TITLE
Cannot highlight textbox or textarea value and loss focus automatically if the textbox is inside in p:datatable after upgrade primefaces 14.xx

### ISSUE THREAD

**Issue by henryhwk531** [primefaces/primefaces#12680]
### Describe the bug

Cannot highlight textbox or textarea value and loss focus automatically if the textbox (h:inputtext or h:inputTextarea) is inside in p:datatable after upgrade primefaces 14.xx

![image](https://github.com/user-attachments/assets/22d59768-be08-4d16-92a2-131b9ca8eb05)
But auto loss focus as follow:
![image](https://github.com/user-attachments/assets/5f5a93ed-c26f-49ba-9031-a734cba3dbd9)

But highlight textbox or textarea value is normal if the textbox is inside in p:datatable after upgrade primefaces 13.xx
![image](https://github.com/user-attachments/assets/a07e39db-8a31-4943-8c10-d9fb36e6ff13)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### Theme

none

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

openjdk 17

### Browser(s)

Chrome 128.0.6613.138

**Comment by melloware** [comment]
Did you try `cellNavigation="false"` on the Datatable?

**Comment by henryhwk531** [comment]
I try to add cellNavigation="false" has been fixed.
Thank You
