### ISSUE TITLE
rowEditor: add name property

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#12683]
### Description

According to https://primefaces.github.io/primefaces/14_0_0/#/components/roweditor, there is no property to add text besides the icon, e.g. `<p:rowEditor name="Edit"/>`

Especially for users with disabilities, it would be good to have text next to the icon.

### Describe the solution you would like

Add a property called `name` or `text` to `p:rowEditor`.

**Comment by melloware** [comment]
@nimo23 its alreayd handled. The code does this.

```js
this.tbody.find('a.ui-row-editor-pencil').attr('aria-label', PrimeFaces.getAriaLabel('editRow'));
this.tbody.find('a.ui-row-editor-check').attr('aria-label', PrimeFaces.getAriaLabel('saveEdit'));
this.tbody.find('a.ui-row-editor-close').attr('aria-label', PrimeFaces.getAriaLabel('cancelEdit'));
```

The ARIA values are already translated into over 30 languages for example:

https://github.com/primefaces/primefaces/blob/86a4f1835da024d3cd68df7a431fb8831f07311f/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js#L78

https://github.com/primefaces/primefaces/blob/86a4f1835da024d3cd68df7a431fb8831f07311f/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js#L112

https://github.com/primefaces/primefaces/blob/86a4f1835da024d3cd68df7a431fb8831f07311f/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js#L74

And the languages are loaded automatically based on your JSF locale.

**Comment by melloware** [comment]
Do you mean  tooltip or full text button. Full text button would be a terrible UI.  

The Aria label is for screenreaders of course

**Comment by melloware** [comment]
Hmmm i don't really agree with this suggestion but i will let other chime in.  It doesn't work this way in any of the other PrimeTek libraries either and I think most users know a Pencil means edit as well as the ScreenReader reads out "Edit Row" to the user.
