### ISSUE TITLE
outputLabel: Float won't return to field if field has a symbol

### ISSUE THREAD

**Issue by SkylerMime** [primefaces/primefaces#12682]
### Describe the bug

The float feature of inputLabel should return to the field if it is empty when it loses focus, [as shown in the showcase](http://www.primefaces.org/showcase/ui/misc/floatLabel.xhtml?jfwid=c3a02). However, if the field (specifically inputNumber) has a symbol that appears on hover, the symbol will stay outside the field even after the user navigates away.

### Reproducer

Reproducer:

https://github.com/SkylerMime/primefaces-test

### Expected behavior

I expect the label to return to the field after focus is lost as long as the field is empty, even if it technically has a symbol inside (which can be seen if the user hovers over the field).

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### Theme

Diamond

### JSF implementation

Mojarra

### JSF version

6.1.0

### Java version

11

### Browser(s)

Firefox

**Comment by melloware** [comment]
I will look at this.

**Comment by melloware** [comment]
@SkylerMime try this version:
[pf-12682.zip](https://github.com/user-attachments/files/17278138/pf-12682.zip)

**Comment by SkylerMime** [comment]
Just tried it out, looks great!

**Comment by melloware** [comment]
Thanks will be in 14.0.6

**Comment by SkylerMime** [comment]
I noticed the only change you made was to add a delay -- is that so the symbol has time to go away?

**Comment by melloware** [comment]
yeah its teh same issue the DatePicker has so InputNumbe `%` symbol is still there onBlur so we have to give AutoNumeric its turn to remove the `%` before we check for `isFilled`
