### ISSUE TITLE
Remove LEGACY_WIDGET_NAMESPACE

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12692]
long long time ago we introduced `PF('...').method()` as API as pushing the widgetVar into global namespace had some issues in IE.
Therefor LEGACY_WIDGET_NAMESPACE was introduced for backward compatibility.
Years later we should finally remove it.

**Comment by tandraschko** [comment]
sorry, i used the wrong dir on my computer and did direct commit

**Comment by fcorneli** [comment]
Just to be clear on this: PF("blablabla") remains the default way to address widgets right?

**Comment by melloware** [comment]
Correct!
