### ISSUE TITLE
SelectOneMenu: ajaxStatus does not go back to status "complete"

### ISSUE THREAD

**Issue by Vraken** [primefaces/primefaces#12694]
### Describe the bug

Hi, 
Within a form containing a selectOneMenu with a listener on ajax event "change", when an item is selected in the select menu,  component p:ajaxStatus switches to state "start" but never finishes to the state "complete".
In my case, the spinner displayed by p:ajaxStatus does not disappear, even though it should after an item is selected from selectOneMenu 

### Reproducer

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="jakarta.faces.html"
      xmlns:f="jakarta.faces.core"
      xmlns:p="http://primefaces.org/ui">
<h:head/>

<h:body styleClass="main-body">
        <p:ajaxStatus styleClass="block mb-4">
            <f:facet name="default">
                <h:outputText value="Status: StandBy"/>
            </f:facet>

            <f:facet name="start">
                <i class="pi pi-spin pi-spinner loading-icon" aria-hidden="true"></i>
            </f:facet>

            <f:facet name="complete">
                <h:outputText value="Status: Completed"/>
            </f:facet>
        </p:ajaxStatus>

        <h:form id="simpleForm">

            <p:selectOneMenu value="#{myForm.valueHolder}">
                <f:selectItem itemLabel="label1" itemValue="value1"/>
                <f:selectItem itemLabel="label2" itemValue="value2"/>
                <f:ajax event="itemSelect"
                        listener="#{myForm.onChange()}"
                        render=":simpleForm"/>
            </p:selectOneMenu>
        </h:form>
</h:body>
</html>

```

### PrimeFaces edition

None

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

**Comment by melloware** [comment]
You issue is this...

```xml
<f:ajax event="itemSelect"
                        listener="#{myForm.onChange()}"
                        render=":simpleForm"/>
```

That is not correct for PrimeFaces it would be

```xml
<p:ajax event="itemSelect"  listener="#{myForm.onChange()}" update=":simpleForm" />
```

**Comment by tandraschko** [comment]
Actually we have a bridge for f:ajax 
Check ajaxstatus.js

**Comment by melloware** [comment]
Oh wow I have been doing this for years and did not know that!  Let me dig deeper on this one.

**Comment by melloware** [comment]
OK can confirm with reproducer `p:ajax` works and `f:ajax` does not.

[pf-12694.zip](https://github.com/user-attachments/files/17297794/pf-12694.zip)

Let me investigate why.  Clearly the `onComplete` is not firing the `pfAjaxCompleted` is my guess...

**Comment by melloware** [comment]
@tandraschko got to the bottom of it and PR submitted

**Comment by Vraken** [comment]
> Your issue is this...
> 
> ```
> <f:ajax event="itemSelect" listener="#{myForm.onChange()}" render=":simpleForm"/>
> ```
> 
> That is not correct for PrimeFaces it would be `p:ajax` with `update` not `render`
> 
> ```
> <p:ajax event="itemSelect"  listener="#{myForm.onChange()}" update=":simpleForm" />
> ```

Thank you, this fixed my issue
