### ISSUE TITLE
Datatable's rendering slowly

### ISSUE THREAD

**Issue by JorgDna** [primefaces/primefaces#1269]
Hi,

I have a trouble, I am implementing a Datatable with 30 columns and many rows, I am using a filter to fetch data, When I select a filter from selectonemenu, the filter and JPQL is faster, But when returns the data the datatable is rendering slowly, it takes 2 seconds to render, it's slowly for me. I need it takes less 1 second. I have looked all ways to implement and have a solution, but it's not successfull. I looked for lazydatamodel but it takes 2 seconds too. 

Please help me how to implement faster datatable. or What do you suggest me?.

Thank you

**Comment by tandraschko** [comment]
Use the forum, its up to your code.
