### ISSUE TITLE
Showcase: source should be included in the WAR file

### ISSUE THREAD

**Issue by kito99** [primefaces/primefaces#1270]

**Comment by kukel** [comment]
+1

**Comment by melloware** [comment]
Why? When it is available on GitHub including it in the WAR is just bloat.  If you need to code get it from here and just run "mvn jetty:run"

https://github.com/primefaces/showcase

**Comment by tandraschko** [comment]
Yep, the tags are available in github.
AFAIR we didn't create tags for the showcase in old google code.
