### ISSUE TITLE
DataTable: 

### ISSUE THREAD

**Issue by rmalavazigalli** [primefaces/primefaces#12709]
.

**Comment by melloware** [comment]
@rmalavazigalli i don't understand are you using Row Editing?  Cell Editing?  So you want when you press Enter it closes the editor of the first row and opens the editor of a second row?

**Comment by melloware** [comment]
@rmalavazigalli i don't think we will add this feature at this time as I think its actually confusing to a user. You have your MonkeyPatch so you aren't stuck waiting on this to be delivered.  Thanks!
