### ISSUE TITLE
selectCheckboxMenu: selectedLabel works but it's shown and "attribute not defined" inside NetBeans 23 with PF 14.0.5

### ISSUE THREAD

**Issue by crick77** [primefaces/primefaces#12708]
### Describe the bug

When project runs it works perfectly but netbeans reports "selectedLabel" attribute as missing for the component. I've had a look inside the taglib.xml and it is effectively missing so netbeans' xml processor complains about this. This is the only one I've found so far. Screenshot attached. 

I know it's not a "real bug" but it's annoying that the IDE reports errors in pages when there aren't.

Thank you.

![Screenshot 2024-10-11 105059](https://github.com/user-attachments/assets/1fae4833-6099-4b3f-9b04-80206bc353d7)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### Theme

Verona

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17.0.2 LTS

**Comment by melloware** [comment]
@crick77 you are right its missing!  I will fix it for 14.0.6
