### ISSUE TITLE
In version 13.0.0, p:confirm and ajax=false cannot be used simultaneously

### ISSUE THREAD

**Issue by private-main** [primefaces/primefaces#12718]
### Describe the bug

The OK button on the pop-up window is invalid when pressed

### Reproducer

                            <p:commandButton   value="test" action="test.test()" ajax="false"
                                <p:confirm message="test" icon="ui-icon-alert" />
                            </p:commandButton>

### PrimeFaces edition

None

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

all

### Java version

11

**Comment by melloware** [comment]
Yes this was added in PF 14.0.0 so please update to PF 14.0.5: https://github.com/primefaces/primefaces/issues/99
