### ISSUE TITLE
resetValues="true" not working after form validation errors

### ISSUE THREAD

**Issue by maqjav** [primefaces/primefaces#12710]
### Describe the bug

Follow these steps with the reproducer code to see the behaviour:
1. Type something in the first inputtext.
2. Click on "Save" (the message indicating that the string2 is required will be shown).
3. Click on "Clean" **(it won't work and it won't clean the values)**
4. Type something in the second inputtext.
5. Click on "Save".
6. Click on "Clean" (now it will work and both boxes will be cleared).

I'm testing the same behaviour in an application with primefaces 10 and it works great, I cannot tell in what version of Primefaces/JSF this got broken.

### Reproducer

XHTML:

```
<h:form>
    <p:inputText value="#{bean.string1}" required="true"/>
    <p:inputText value="#{bean.string2}" required="true"/>

    <h:commandButton value="Save">
	<p:ajax process="@form" update="@form" listener="#{bean.save}" />
    </h:commandButton>
    <h:commandButton value="Clean">
	<p:ajax update="@form" listener="#{bean.clean}" resetValues="true"/>
    </h:commandButton>
</h:form>
```

BEAN:

```
private String string1;
private String string2;

public void save() { }

public void clean() {
	this.string1 = null;
	this.string2 = null;
}

public String getString1() {
	return this.string1;
}

public void setString1(String string1) {
	this.string1 = string1;
}

public String getString2() {
	return this.string2;
}

public void setString2(String string2) {
	this.string2 = string2;
}
```

### Expected behavior

The button "Clean" should always work.

### PrimeFaces edition

None

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

4.1.0

### Java version

17

### Browser(s)

Chrome 129

**Comment by tandraschko** [comment]
Did you try to set process @this?

**Comment by tandraschko** [comment]
Should BE the same as: https://github.com/primefaces/primefaces/issues/12241

**Comment by maqjav** [comment]
> Did you try to set process @this?

Isn't process="@this" the default value if you don't set that attribute? Anyway I tried and the error persists.

**Comment by maqjav** [comment]
> Should BE the same as: #12241

I saw that ticket, it could be related. If I don't misunderstand in that ticket resetValues wasn't working at all, now it does, but only if there aren't validation errors.

**Comment by tandraschko** [comment]
try to debug here: https://github.com/primefaces/primefaces/blob/360c7ca435312919ce83ca53b8edda527797bbe6/primefaces/src/main/java/org/primefaces/context/PrimePartialViewContext.java#L53

**Comment by maqjav** [comment]
> try to debug here:
> 
> https://github.com/primefaces/primefaces/blob/360c7ca435312919ce83ca53b8edda527797bbe6/primefaces/src/main/java/org/primefaces/context/PrimePartialViewContext.java#L53

These are the phaseIds received when clicking on "Clean".

```
APPLY_REQUEST_VALUES 2
PROCESS_VALIDATIONS 3
UPDATE_MODEL_VALUES 4
RENDER_RESPONSE 6
```

I'm using JSF 4.1, so `environment.isAtLeastJsf40() = true`

**Comment by tandraschko** [comment]
you need to debug into resetValue, thats were the magic happens

**Comment by maqjav** [comment]
Here you have an executable with this example: [primefaces-test-master.zip](https://github.com/user-attachments/files/17350913/primefaces-test-master.zip)

I will try to debug it on monday.

**Comment by maqjav** [comment]
> you need to debug into resetValue, thats were the magic happens

As I'm using JSF 4.1, and the flag `environment.isAtLeastJsf40()` returns true, it never calls `resetValues`.
https://github.com/primefaces/primefaces/blob/360c7ca435312919ce83ca53b8edda527797bbe6/primefaces/src/main/java/org/primefaces/context/PrimePartialViewContext.java#L56

If I modify the method to remove that condition, then it calls `resetValues` and it works as it should.

**Comment by tandraschko** [comment]
I see
then you have to wait for the newest Mojarra release or check if its already released
see: https://github.com/jakartaee/faces/issues/1936

we alinged to fix it for 4.0, 4.1 and 5.0
MyFaces also has this changed, just not released yet

**Comment by maqjav** [comment]
I see the merge in the 5.0 branch, but nothing in the 4.0.x (https://github.com/jakartaee/faces/commit/8a1d8c4b84719300126c996dd767314994f317ae)

In fact based on the comment added in that modification, it seems they are going to add it only in 5.0, are you sure this will come to 4.0+? If it doesn't I think primefaces should take it into account, otherwise it will never work.

**Comment by tandraschko** [comment]
just read the comments here and ask the mojarra guys: https://github.com/jakartaee/faces/issues/1936

wie aligned to do it, you might check commits or create a issue there

**Comment by maqjav** [comment]
> just read the comments here and ask the mojarra guys: [jakartaee/faces#1936 (comment)](https://github.com/jakartaee/faces/issues/1936#issuecomment-2242799213)
> 
> wie aligned to do it, you might check commits or create a issue there

Ok, thanks.

**Comment by tandraschko** [comment]
and if you create a issue, please not in the faces spec repo, you need to use mojarra repo: https://github.com/eclipse-ee4j/mojarra/issues

**Comment by maqjav** [comment]
> we alinged to fix it for 4.0, 4.1 and 5.0 MyFaces also has this changed, just not released yet

A silly question, if this change hasn't been released in MyFaces, and neither in Mojarra, shouldn't Primefaces wait until they release their change first? We all know that myfaces and mojarra don't release new versions that often, so it could take months or even years to be released, and in this period of time this functionality will be broken while using JSF 4+.

What is the worst scenario, that they release the change and while Primefaces doesn't remove it, it is executed twice?, isn't that better than not working at all? (assuming that executing the code twice won't break something else of course).

**Comment by tandraschko** [comment]
we changed to that API some months ago but a user detected the bug in the JSF impls some months after that.
As its a bug in the JSF impl, we decided to fix it there. As you said, it would be implemented twice and we in PF dont want to check for minor versions, which rely on the spec version where it should work.

You can user overwrite the PrimePartialViewContext in your project, to always execute until its fixed. Maybe we can add this to the migration guide.

**Comment by melloware** [comment]
If I remember you can also switch temporarily to use `<p:resetInput>` which does not have the issue.

**Comment by spadovan** [comment]
Hi i'm using mojarra 4.0.5 with PF 14.0.6 and the problem still exixts.
Ho can i solve it ? thanks

**Comment by tandraschko** [comment]
i would ask mojarra for a 4.0.6 release with this fix

**Comment by melloware** [comment]
Also Mojarra is on 4.0.9

**Comment by melloware** [comment]
Actually already fixed in 4.0.9: https://github.com/eclipse-ee4j/mojarra/issues/5513

**Comment by spadovan** [comment]
you were talking about class override....how cold i do it ? thanks

**Comment by tandraschko** [comment]
TBH just upgrade to 4.0.9, everything else is dirty

**Comment by spadovan** [comment]
ok thanks...sorry but where can i dowblioad it ? thanks

**Comment by tandraschko** [comment]
check the readme here: https://github.com/eclipse-ee4j/mojarra

**Comment by spadovan** [comment]
I've tried to use mojarra 4.0.9 but the problem persists

**Comment by melloware** [comment]
Can you provide a reproducer?

**Comment by spadovan** [comment]
yes the first post on this issue
