### ISSUE TITLE
DataTable: excel-like filters

### ISSUE THREAD

**Issue by crick77** [primefaces/primefaces#12727]
### Description

In many of my projects customers asks for excel-like filters on tables...that is something like "greater than" or "greater than or equal and less than" or to choose values from a predefined list (can be for example a list of "product types" or country list, etc.).

Thank you.

### Describe the solution you would like

Essentially there are 3 types of data to handle: 

* numerical and dates - with equal, not equal, gt, gte, lt, lte or between
* text - starts with, ends with, exact or contains
* collections - choose one or more to match (with select-all)

the filter can be a popup with a button with specific fields given the type, something like:

`<p:column filter="advanced" columnType="numeric/date/text/collection" ... />`

Given the columnType the most appropriate popup will show. 

I know it's a bit of work but it would be a great add-on to a great library.

**Comment by tandraschko** [comment]
dont we have this functionality actually, not just a built-in UI which covers to switch the matchMode? https://primefaces.github.io/primefaces/14_0_0/#/components/datatable?id=constraints

**Comment by melloware** [comment]
@crick77 wants this https://github.com/primefaces/primefaces/issues/7427

Which is already marked financial sponsoring required.

**Comment by crick77** [comment]
Simply switching matchMode is not a proper solution because if you need to filter only gte a value you need only one textfield by between requires two. So a bit more complex UI is required...something like 

**<selectone>** with values _">", ">=", "=", "!="_ **<textfield> <selectone>** with values "<", "<=", etc. **<textfield>**

The excel picture (sorry for the italian language) explains it all

![image](https://github.com/user-attachments/assets/43688b4b-f19b-4760-9667-e1a47cd7f82a)

so you can filter by values in any combination or choose one or more to show (this is applied only on specific type of column eg "collection" types, where between or lte filter have no meaning at all.

**Comment by crick77** [comment]
A better image

![image](https://github.com/user-attachments/assets/02cd16fd-b140-4f3a-882d-9cd5231be808)

**Comment by tandraschko** [comment]
yeah
this a huge amount of work
without sponsoring i think its not realistic that someone implements this

**Comment by melloware** [comment]
@crick77 PrimeReact has this if you look at the advanced filters option and it's a massive feature. It's what you want basically. It lets you add AND and OR criteria to each column has all the features you are asking for. 

But it's a huge requirement and it would need to be financially sponsored. 

I am in favor of closing this as the other ticket it already in the sponsoring wishlist ticket.

**Comment by melloware** [comment]
@crick77 you want something like this right?

![image](https://github.com/user-attachments/assets/b61604f6-2936-4d4e-8341-a70796264884)

**Comment by crick77** [comment]
Yeah. For some filter like this (but waaaayy much simpler) my xhtml page is a beast! :)
