### ISSUE TITLE
FileUpload: always try to use messages used in update attr first to display errors

### ISSUE THREAD

**Issue by Vraken** [primefaces/primefaces#12722]
### Describe the bug

Hi, 
With a fileUpload configured like this : 

> <p:growl id="messages" showDetail="true"/>
>     <h:form enctype="multipart/form-data">
>         <p:fileUpload value="#{testView.files}"
>                       mode="advanced"
>                       skinSimple="true"
>                       multiple="true"
>                       update="messages">
>             <p:validateFile fileLimit="2"/>
>         </p:fileUpload>
>     </h:form>

When I try to upload 3 files at the same time, I correctly get an error message in a growl message like this : 
![2024-10-15_11h26_18](https://github.com/user-attachments/assets/0867cd12-9374-4411-8d1e-1e4a8cf1b6bc)

However, when I try to upload 2 files and then a third file, the error message appears inside my form, and not in a growl as I expected : 
![2024-10-15_11h26_42](https://github.com/user-attachments/assets/ef2c6976-1b36-42ed-a85a-ee9d2e5ac3ec)

### Reproducer

[pf-test-fileupload-growl.zip](https://github.com/user-attachments/files/17376118/pf-test-fileupload-growl.zip)

Select 3 files but one at a time

### Expected behavior

Growl message is updated non regarding how users select files 

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

**Comment by melloware** [comment]
Thanks for the reproducer.

**Comment by melloware** [comment]
OK it looks like 1 is a client side message and 1 is a server side message

Client in locale_en.json: `"primefaces.FileValidator.FILE_LIMIT": "Maximum number of files exceeded.",`

Server in Messages_en.properties: `primefaces.FileValidator.FILE_LIMIT = Maximum number of files exceeded.`

So it looks like one of them is being done on the server and not the client.

**Comment by tandraschko** [comment]
the reason is: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js#L202

**Comment by tandraschko** [comment]
the example is not valid anyway
advanced multiple fileupload does not allow a value binding, see: https://primefaces.github.io/primefaces/14_0_0/#/components/fileupload?id=multiple-1
