### ISSUE TITLE
DataTable: use p:selectOneMenu for rowsPerPageTemplate

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#12734]
### Describe the bug

The generated selectonemenu for rowsPerPageTemplate in the DataTable component looks as follows, for instance to be seen in the show case https://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml?jfwid=7b2ad:
![image](https://github.com/user-attachments/assets/ddbd9a48-e962-4248-9769-59bba46d57c1)
To be consistent, the generated selectonemenu however should look as the ones in https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml?jfwid=7b2ad:
![image](https://github.com/user-attachments/assets/8e92fc4a-e409-4947-b4a9-4df476832a0e)

### PrimeFaces edition

None

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

**Comment by tandraschko** [comment]
thats by design since ages

**Comment by melloware** [comment]
I am pretty sure @jepsar amd I fixed the styling of this for 15.0 to look like a normal selectone.

**Comment by jepsar** [comment]
> I am pretty sure @jepsar and I fixed the styling of this for 15.0 to look like a normal selectone.

It's not the same, but very close. The chevron is different for example I believe.

**Comment by tandraschko** [comment]
in theory we could switch just to our selectOneMenu completely but thats effort

**Comment by melloware** [comment]
here is what it looks like in 15.0

![image](https://github.com/user-attachments/assets/48903145-4c2f-4f65-8b09-4e1279358b50)

**Comment by tuerker** [comment]
that looks fine. thanks.

**Comment by melloware** [comment]
@tuerker here is the sass code if you want to add it to your theme yourself right now

https://github.com/primefaces/primefaces/pull/12358

**Comment by tuerker** [comment]
> @tuerker here is the sass code if you want to add it to your theme yourself right now
> 
> #12358

great. many thanks.
