### ISSUE TITLE
Dynamic draggable columns with data exporter question

### ISSUE THREAD

**Issue by hodlonaut** [primefaces/primefaces#12731]
### Describe the bug

hello, I cloned the repository and checked out version 14.0.5 of primefaces, built it as well as primefaces-showcase.
I subsequently edited the src/main/webapp/ui/data/datatable/columns.xhtml file under the primefaces-showcase, and added p:command button for doing CSV export pointing to the table, and also added draggableColumns="true" to the p:table definition.

After running recompiled showcase, I dragged some columns around to change the column ordering from default, then pressed my exporter button and downloaded a file that had columns in their original order, not in updated one.

Can you please advise as to what is the recommended course of action if i want the column order to be preserved as it is on the screen for this scenario? thank you kindly. Attaching modified file for reference.

### Reproducer

[columns.xhtml.zip](https://github.com/user-attachments/files/17405975/columns.xhtml.zip)

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
OK let me look because  this was fixed here in 11.0.0: https://github.com/primefaces/primefaces/issues/7200 so something must have broken it.

**Comment by hodlonaut** [comment]
Thank you, appreciate a quick fix.

**Comment by melloware** [comment]
@hodlonaut this will be included in 14.0.7! Thanks for the report.
