### ISSUE TITLE
Cleanup duplicate themes

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12746]
arya = arya-blue
saga = saga-blue
vela = vela-vlue

we should remove arya/saga/vela and map arya e.g. to arya-blue in the HeadRenderer

this will also reduce jar size

**Comment by fcorneli** [comment]
Why not have one default theme in the PrimeFaces JAR and externalize all the others? No need to drag all these themes within the vanilla JAR no?

**Comment by melloware** [comment]
its always been like this these are free themes from PrimeTek.

**Comment by tandraschko** [comment]
and some hundreds kb jar size doesnt make any difference today
