### ISSUE TITLE
AbstractMenu: "renderEmptyContainer" option to prevent empty menus from being rendered

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#12743]
### Description

I often encounter cases were I use some kind of menu/container component (MenuButton,  Menubar, Toolbar, ...) with a list of menu items that are either rendered or not depending on the current rights of the user. In cases where the current user has none of the required rights the menuButton is still rendered and can be clicked but an empty popup is shown.

E.g "Action" MenuButton with Menu Items for "Edit", "Delete", "Print" each having its own rendered definition
`
<p:menuButton value="actions">
   <p:menuitem value="Edit" rendered="#{checkRequirementsRights('edit')}">
   <p:menuitem value="Delete" rendered="#{checkRequirementsRights('delete')}">
   <p:menuitem value="Print" rendered="#{checkRequirementsRights('print')}">
</p:menuButton>
`

I could also add a rendered to the menuButton and combine any checks with OR but depending on the number of items this soon becomes anoying. For my toolbar this is not possible because here I define the toolbar itself in a pageTemplate and each subPage defines it's unique actions for it.

Adding a "renderEmptyContainer" (default true for backward compatibility) with a check wether any children are rendered and if not not rendering the whole component could solve this issue.

Is this something that could be added as a feature or can anyone come up with a different solution?
If yes I could provide a PR for some components where I already fixed it via an extension.

### Describe the solution you would like

Components that act as some kind of container for other items (Toolbar, MenuButton, Menubar, ...) should have an option to not being rendered at all if no real children ( e.g ignore separaors) are present/rendered.

An alternative solution could be to render the component as usual but add some kind of empty marker via a css style class to the container ("ui-widget-empty" or something like that). If somebody want's to hide these components a simple .ui-widget-empty {display:none} rule would suffice. For this solution no additional attribute would be necessary since always adding the marker class should do no harm if no css rule is defined.

**Comment by melloware** [comment]
@gako i like this idea i think we have discussed it before or maybe i have seen it on StackOverflow.  Are you submitting a PR?

Also @jepsar @tandraschko i would think the default should be to NOT render an empty container?  Maybe we don't even need a setting?

**Comment by jepsar** [comment]
I usually add a rendered check on (in my case) the sub menu to prevent that from happening. I also have a utility function for it in an application scoped bean:
```java
  public boolean hasRenderedChildren(String clientId) {
    return Components.findComponent(clientId)
            .getChildren()
            .stream()
            .anyMatch(UIComponent::isRendered);
  }
```
I'm not sure if it should be the default to not render it or if we should throw an exception. Not rendering it could lead to unexpected results (in the UI, possibly confusing your users) without knowing it. I mean, I would prefer to explicitly not render the button / sub menu / xxx.

**Comment by gako** [comment]
yes jespar's solution is similar too what I'm currently using as well. Not sure how much impact it would have performance wise since if I recall correctly isRendered function is called quite often, but I think unless the page is huge that can be neglected.

I just stumbled over something similiar in the datatable "renderEmptyFacets". Here the default behaviour is to not render the header/footer at all if all children are not rendered. If you replace facet with the main component it's the same for this feature except the default behaviour is currently inverted.

**Comment by tandraschko** [comment]
Our code would do similar things compared to jespars code or buffering
I dont like both that much

**Comment by gako** [comment]
I added an initial draft PR. Currently only the rendered check is present and "empty" containers are never rendered.
At the moment it is implemented for all AbstractMenu Components, not sure if it makes sense for all of them but if we decide on a solution like this I can check if it works/makes sense for all of them.

Whether an additional attribute to configure the behaviour is desired or not is up to you also what the default value should be.

**Comment by fcorneli** [comment]
mmm... what if the container is initially empty, and then later on an AJAX update makes it to have some content, then the AJAX update will not get executed at the client-side I'm afraid.

**Comment by melloware** [comment]
it was in the PR he renders and `empty` DIV so ajax updates can take place...
