### ISSUE TITLE
PrimeFaces Download page not found

### ISSUE THREAD

**Issue by Kodai-Nakayama** [primefaces/primefaces#12753]
### Describe the bug

https://www.primefaces.org/downloads
"page not found"

We are using primefaces12 .
I would like to download the showcase and documentation for this, but I can't find the page.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

e.g.

**Comment by tandraschko** [comment]
@melloware should we add showcase download to github here? we dont have access to PF homepage

**Comment by tandraschko** [comment]
Added it here: https://github.com/primefaces/primefaces?tab=readme-ov-file#versions

we dont have access to the download page, i will remove the link for now.

**Comment by tandraschko** [comment]
we switched to markdown some years ago and we dont have a converter for PDF
online is our choosed solution

you might google for markdown to pdf converter or something.

**Comment by Kodai-Nakayama** [comment]
Oh I see.
Thanks, I'll give it a try.
