### ISSUE TITLE
TreeTable: missing dynamic property like in p:tree

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#12750]
### Description

The `p:tree` has a property called `dynamic`:

> Specifies the ajax/client toggleMode

When setting to `false`, ajax toggling is disabled.

### Describe the solution you would like

The `p:treeTable` also requires the `dynamic` property. It is actually missing and therefore a toggle always generates an Ajax call, which is not always necessary.

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/2124 which is already on the financial sponsoring wishlist.
