### ISSUE TITLE
Rethink TabChange/Close event deprecation

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12758]
It's completely fine that we have a "more implemented" TabEvent now but currently its a good design pattern that the event is typed and contains the "action", not just the component name.
Thats what we have for almost every event class currently.

Just look e.g. at NodeCollapse, NodeExpand, NodeSelect event -> they all contains the action which is nice.
We could just create a NodeEvent but IMO not a good idea.

**Comment by Rapster** [comment]
It's actually an anti-pattern. But for homogeneity, I would say let's undeprecate them

**Comment by tandraschko** [comment]
that depends on the POV, in the JSF/PF world is currently a pattern and for me its always homogenity over everything else
