### ISSUE TITLE
Rethink how we package themes

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12764]
Currently we have

```
primefaces-arya-blue
primefaces-bootstrap4-blue-dark
primefaces-bootstrap4-blue-light
primefaces-bootstrap4-dark-common
primefaces-bootstrap4-light-common
primefaces-bootstrap4-purple-dark
primefaces-bootstrap4-purple-light
primefaces-luna-amber
primefaces-luna-blue
primefaces-luna-common
primefaces-luna-green
primefaces-luna-pink
primefaces-material-compact-deeppurple-dark
primefaces-material-compact-deeppurple-light
primefaces-material-compact-indigo-dark
primefaces-material-compact-indigo-light
primefaces-material-dark-common
primefaces-material-deeppurple-dark
primefaces-material-deeppurple-light
primefaces-material-indigo-dark
primefaces-material-indigo-light
primefaces-material-light-common
primefaces-mytheme
primefaces-nova-colored
primefaces-nova-common
primefaces-nova-dark
primefaces-nova-light
primefaces-saga-blue
primefaces-vela-blue
```

50% are delivered in primefaces.jar, 50% are just copied to the showcase and are not really useable by users.

I would suggest the following:
1) only copy saga-blue to primefaces.jar as default theme
2) remove all other themes from primefaces.jar and showcase
3) use primefaces-themes.jar to use the other themes

**Comment by melloware** [comment]
I am OK with this.  lightens the load of the jar

**Comment by tandraschko** [comment]
im doing a PR

i think its a very good way to split this, remove complexity from build and make everything more clear

**Comment by melloware** [comment]
totally agree

**Comment by mthmulders** [comment]
I came here after investigating why the look and feel of my Primefaces app has disappeared after upgrading to 15.0.0. I think it would've been great if this could've been mentioned as a breaking change on the [release page](https://github.com/primefaces/primefaces/releases/tag/15.0.0). It would've been even better if that page had instructions on what to do if you use any other theme than _saga_ (such as _vela_ or _arya_).

Is it possible to add such information to the release page, please?

**Comment by melloware** [comment]
@mthmulders let me update the docs.

**Comment by melloware** [comment]
@mthmulders added to Breaking Changes in release notes and add to migration guide: https://primefaces.github.io/primefaces/15_0_0/#/../migrationguide/15_0_0?id=themes

**Comment by mthmulders** [comment]
Thank you @melloware!
