### ISSUE TITLE
W3C error in p:selectBooleanCheckbox (5.3 and 6.0)

### ISSUE THREAD

**Issue by jrry** [primefaces/primefaces#1277]
> Attribute autocomplete is only allowed when the input type is color, date, datetime, datetime-local, email, month, number, password, range, search, tel, text, time, url, or week.

p:selectBooleanCheckbox generates this code:

`<input id="emp:j_idt44_input" name="emp:j_idt44_input" type="checkbox" autocomplete="off" aria-checked="false" data-p-con="javax.faces.Boolean" data-p-hl="booleanchkbox" />`

**Comment by sudheerj** [comment]
You are right.We don't need autocomplete attribute for checkbox.

The below line need to be removed.

writer.writeAttribute("autocomplete", "off", null);

**Comment by sudheerj** [comment]
But as discussed in the issue https://github.com/primefaces/primefaces/issues/1223 it breaks lots of things in firefox. Hence it is not going be removed.
