### ISSUE TITLE
InputMask: Errors when entering a day from the keyboard in DatePicker and Calendar components

### ISSUE THREAD

**Issue by jfermat** [primefaces/primefaces#12770]
### Describe the bug

In the DatePicker and Calendar components, when you have a date value, with mask, with the pattern "dd/MM/yyyy HH:mm:ss" and locale "es", when you go to write a new one, these two errors occur.

1. If you do not select the day, a console error appears.
2. If you select the day and you want to enter the 12th day. Enter the 1st of February.

[primefaces-test.zip](https://github.com/user-attachments/files/17502310/primefaces-test.zip)

### Reproducer

1. If you do not select the day, a console error appears.

https://github.com/user-attachments/assets/280a43cd-bc5c-45f7-b8a9-0a914eb11fd1

[localhost-datepicker-1729749705699.log](https://github.com/user-attachments/files/17502333/localhost-datepicker-1729749705699.log)

https://github.com/user-attachments/assets/4a09ea05-f7e9-48af-b51d-34811ca7b3d6

[localhost-calendar-1729750211579.log](https://github.com/user-attachments/files/17502338/localhost-calendar-1729750211579.log)

2. If you select the day and you want to enter the 12th day. Enter the 1st of February.

https://github.com/user-attachments/assets/2f856910-82af-482a-8caf-04224e303d96

### Expected behavior

When entering e.g. day 12 on the keyboard, you should overwrite the previous value by day 12.

### PrimeFaces edition

None

### PrimeFaces version

13.0.7

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

All

**Comment by melloware** [comment]
@jfermat both issues are input mask issues.  I reproduced with just a Code Sandbox..

https://codepen.io/melloware/pen/GRVOERo

Similar to this InputMask issue: https://github.com/RobinHerbots/Inputmask/issues/2813 you should report this there with the code sandbox i provided in that format that I show there.

**Comment by melloware** [comment]
OK reported go upvote that ticket: https://github.com/RobinHerbots/Inputmask/issues/2825
