### ISSUE TITLE
Please implement ComboTree component

### ISSUE THREAD

**Issue by zsuiqiang** [primefaces/primefaces#1278]
jquery easyUI ComboTree is very usefull,I strongly recommended implement it in PF.

**Comment by cagataycivici** [comment]
Can you provide us a link please?

**Comment by kukel** [comment]
I personally think that paging and filtering (with a lazyDataModel) added to the treeTable is way more useful ;-)

**Comment by zsuiqiang** [comment]
http://www.jeasyui.com/demo/main/index.php?plugin=ComboTree&theme=default&dir=ltr

**Comment by zsuiqiang** [comment]
http://www.jeasyui.com/documentation/combotree.php

**Comment by zsuiqiang** [comment]
Is there any plan?

**Comment by tandraschko** [comment]
It's already available: http://primefaces.org/showcase/ui/data/tree/selection.xhtml
