### ISSUE TITLE
GMap: Polygon not displaying InfoWindow before Marker selection

### ISSUE THREAD

**Issue by twuillemin** [primefaces/primefaces#12809]
### Describe the bug

On a GMap component:
- with only Polygons, a click on a polygon throws, as expected, the OverlaySelectEvent event. However the related InfoWindow is not displayed.
- with only Markers, a click on a marker throws, as expected, the OverlaySelectEvent event and the  InfoWindow is displayed.

To be able to display to display an InfoWindow for a Polygon, the user must first display an InfoWindow for a Marker.

### Reproducer

A forked primefaces-test is given at: [https://github.com/twuillemin/primefaces-test-gmap-polygon-selection](https://github.com/twuillemin/primefaces-test-gmap-polygon-selection)

The test project display three maps:
- The first one has only polygons and therefore no InfoWindow is displayed
- The second one has only markers and InfoWindow are working well
- The third one has a mix of markers and polygons and the InfoWindow for the polygons are displayed only after the user has displayed the InfoWindow for a Marker

### Expected behavior

A click on a polygon should display the InfoWindow

### PrimeFaces edition

Community

### PrimeFaces version

14.0.6

### JSF implementation

Mojarra

### JSF version

4.0.8

### Java version

21.0.5

### Browser(s)

Reproduced on Edge 130.0.2849.56 and Firefox 131.0.3, Linux

**Comment by melloware** [comment]
@twuillemin the GMap code has not changed in a long time.  Have you investigated it?

**Comment by melloware** [comment]
I will look too but I suspected it might be a Google bug as well.

**Comment by melloware** [comment]
OK looking at PrimeFaces code the Polygons and Markers do the exact same thing so I am suspecting this is a Google Maps bug.

**Comment by melloware** [comment]
here are some of the InfoWindow open bugs: https://issuetracker.google.com/issues?q=infowindow%20only%20appears%20on%20marker 

Its probably somewhere in there already.

**Comment by melloware** [comment]
i will close for now as I am pretty sure its a GMap bug but please report back if they fix it or your find the root cause.

**Comment by twuillemin** [comment]
I agree with your diagnostic. I will try to search  bit more or wait if any update from Google. Issue can be safely closed at this point for PF.

Thanks again fro your help.
