### ISSUE TITLE
tabClose method is not called for the first tab from tabview

### ISSUE THREAD

**Issue by idomiralin** [primefaces/primefaces#1280]
I use primefaces 5.3 and jsf 2.2.6.

I implemented a tabClose ajax event for a tabview, but the problem is that for the first tab, the tabClose event isn't triggered and the method remove isn't called, for all the other tabs, it is and it works and I can't understand why. Additionally, if I try to close the first tab, all the tabs are closed.

The reason why I used c:foreach is this:
[http://stackoverflow.com/questions/20111010/jsf-dynamically-include-src-in-uiinclude-src-bean-pagepath](url)

The code looks like this:
`<p:tabView` id="tabs" activeIndex="#{mainPage.index}">
        <p:ajax event="tabClose" listener="#{mainPage.remove}" update="formTabs" />
        <p:ajax event="tabChange" listener="#{mainPage.changeTab}" update="formTabs" />

```
<c:forEach items="#{mainPage.tabs}" var="tab" varStatus="loop">
    <p:tab title="#{tab.title}" closable="true">
        <f:subview id="tab#{loop.index}">
        <ui:include src="#{tab.url}">
                 <ui:param name="focusedTab" value="#{tab.id}" />
       </ui:include>
        </f:subview>
     </p:tab>
 </c:forEach>
 </p:tabView>`
```

**Comment by kukel** [comment]
Please don't create 'issues' AND post in the forum AND in stackoverflow. And if you do, please include version info. http://forum.primefaces.org/viewtopic.php?f=3&t=44985&p=140737#p140737

**Comment by tandraschko** [comment]
Please reopen if it's still not not working with a current version. We did some fixes in the last versions.
NOTE: please provide also a bean code then.
