### ISSUE TITLE
DataTable: When inside a AccordionPanel sticky header stays in wrong position

### ISSUE THREAD

**Issue by ra-ke** [primefaces/primefaces#12802]
### Describe the bug

When a data table with `stickyHeader="true"` is placed within the second tab of an accordion panel (with the `multiple` option enabled), collapsing the first tab causes the sticky header in the second tab to become misaligned.

a demonstrator can be found [here](https://github.com/ra-ke/primefaces-datatable-accordion-demo)

### Reproducer

1. Expand the second tab of the accordion panel
2. Collapse the first tab of the accordion panel
3. see the sticky header stay in ints position

### Expected behavior

the sticky header moves upwards with the rest of the table

### PrimeFaces edition

Community

### PrimeFaces version

14.0.6

### JSF implementation

All

### JSF version

2.3

### Java version

17

### Browser(s)

Chrome and Firefox

**Comment by melloware** [comment]
@ra-ke I don't ever recommend doing what you are doing with a Sticky inside another moving container I was able to "fix" your reproducer.
[pf-12802.zip](https://github.com/user-attachments/files/17556653/pf-12802.zip)

Basically after opening or closing tabs you have to tell the browser it "scrolled" so the sticky moves.

```xml
<p:ajax event="tabClose" process="@this" oncomplete="PrimeFaces.queueTask(function() {window.dispatchEvent(new Event('scroll'))}, 400)" />
<p:ajax event="tabChange" process="@this" oncomplete="PrimeFaces.queueTask(function() {window.dispatchEvent(new Event('scroll'))}, 400)" />
```

This is not something PrimeFaces will fix as we can't know every scenario and like I said I don't recommend this UI/UX paradigm anyway.
