### ISSUE TITLE
DataTable: cellNavigation primeone themes

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#12819]
### Describe the bug

New in primefaces 14 is DataTable cellNavigation and it is on (true) by default (which is not mentioned in the Migration guide 13.0.0 -> 14.0.0). Because of cellNavigation some visual issues (because of custom css) arose when migrating to primefaces 14.
Apparently the default theme saga also has issues.

1 Environment
PrimeFaces version: 14.0.6

2 Expected behavior
Primefaces primeone themes must have same borders for cellNavigation around every cell.

3 Actual behavior
The uttermost left and right cells are missing the left/right border.
The bottom cells have no/smaller bottom-border.

4 Steps to reproduce

See showcase: https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml
Mouse click a cell and navigate with the cursor keys.

Or download [primefaces-test-cellnavi.zip](https://github.com/user-attachments/files/17598950/primefaces-test-cellnavi.zip), run "mvn clean jetty:run -Pmojarra40" and click button "Click random issue cell".

### PrimeFaces edition

Community

### PrimeFaces version

14.0.6

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

17

**Comment by melloware** [comment]
I will update the migration guide

I will look but I think the issue is the outer table border has higher precedence in cSS order. I was hesitant to try and make the focused highlight border have a higher precedence.

**Comment by melloware** [comment]
To put it in pictures.

![image](https://github.com/user-attachments/assets/4a937f5f-5695-45e5-bb0b-f13bdfc78ec1)


![image](https://github.com/user-attachments/assets/99e69bf3-4452-4931-b174-02dfd61e2497)

**Comment by melloware** [comment]
OK @DazzlingBob its comin from primefaces core they `collapse` the borders. If you add this style it fixes it

```css
body .ui-datatable table {
    border-collapse: inherit; 
}
```

Also the note was in the WhatsNew not the Migration Guide: https://primefaces.github.io/primefaces/14_0_0/#/gettingstarted/whatsnew

But i will add to migration guide also

**Comment by melloware** [comment]
@DazzlingBob have to revert this and you will have to override the CSS in your project.

**Comment by melloware** [comment]
Found the proper fix!

**Comment by morvael** [comment]
So what do I do to keep the old looks?
