### ISSUE TITLE
Add javascript 'responsiveness' function to read media size

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#1281]
In more than one situation (like https://github.com/primefaces/primefaces/issues/394), but also for  , it is very useful to be able to access the 'media size' in javascript. 

Adding the following script to the new primefaces-core.js.

```
getMediaSize : function() {
    var size;
    if (window.matchMedia('(min-width: 960px) and (max-width:1200px)').matches) {
        /* Intermediate sized desktop */
        size = 5;
    } else if (window.matchMedia('(min-width: 960px)').matches) {
        /* Large desktop */   
       size = 4;
    } else if (window.matchMedia('(min-width: 640px) and (max-width: 960px)').matches) {   
        /* Portrait tablet to landscape <???> and small desktop */
        size = 3
    } else if (window.matchMedia('(min-width:480px) and (max-width: 640px)').matches) {   
        /* Landscape phone to portrait tablet */
        size = 2;
    } else  if (window.matchMedia('(min-width:320px) and (max-width: 480px)').matches) {
        /* Portrait phones and down */
        size = 1;
    } else {
        alert('Are you seriously using this?');
        size = 0;
    }
    return size;
},
```

Keeping this 'in sync' with the css might be 'work' but the advantage imo outweighs that.

It might also be possible have this achieved automagically by settting [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and [reading those in javascript](https://www.broken-links.com/2014/08/28/css-variables-updating-custom-properties-javascript/)

**Comment by melloware** [comment]
I agree this function is very useful.  I have added it to the PrimeFaces.env package since its environment related. It can be used like...

```javascript
var mediaSize = PrimeFaces.env.getMediaSize();
```
