### ISSUE TITLE
IntegrationTests: SCREENSHOT_DIRECTORY not set when running on local

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12815]
@christophs78 can you have a look?

when running on localhost, `${SCREENSHOT_DIRECTORY}....` files are directly created in the project and git wanna commit it

**Comment by christophs78** [comment]
We may set java-temp-directory as default.

**Comment by christophs78** [comment]
> We may set java-temp-directory as default.

Changed my mind. :-) Just an additional clause to an existing if.
