### ISSUE TITLE
Schedule: Incorrect documentation since version 8.0

### ISSUE THREAD

**Issue by kamilkrzywanski** [primefaces/primefaces#12810]
### Describe the bug

With version 8.0, FullCalendar was updated to version 4: https://fullcalendar.io/docs/v4/upgrading-from-v3

> Instead of accepting (event, el, view), it now accepts an object. Here’s an example:
> var calendar = new Calendar(calendarEl, {
>   eventRender: function(info) {
>     console.log(info.event.title);
>     console.log(info.el);
>     console.log(info.view);
>     console.log(info.isStart);
>     console.log(info.isEnd);
>     console.log(info.isMirror);
>   }
> });

From version 10.0, FullCalendar is at version 5, where eventRender is removed: https://fullcalendar.io/docs/v5/upgrading-from-v4

In FullCalendar 5, alternatives like eventDidMount and eventContent should be used. The documentation should be updated—I’ve spent a lot of time due to the lack of documentation. I’ll contribute to it! :)

### PrimeFaces edition

None

### PrimeFaces version

8.0

### JSF implementation

All

### JSF version

ALL

### Java version

ALL

### Browser(s)

ALL

**Comment by melloware** [comment]
@kamilkrzywanski i assigned it to you. Thanks for updating the docs!

**Comment by kamilkrzywanski** [comment]
@melloware can I Include some basic case in showcase? 
primefaces/primefaces-showcase/src/main/webapp/ui/data/schedule/extender.xhtml

**Comment by melloware** [comment]
Showcase examples and improvements are always welcome!

**Comment by kamilkrzywanski** [comment]
Added documentation and a simple example for the current and updated migration guides for versions 8 and 10. Mentioned these functions and included URLs for the migration guides for versions 4 and 5.

**Comment by melloware** [comment]
Thank you!
