### ISSUE TITLE
CSP: policyProvided functionality unclear

### ISSUE THREAD

**Issue by dspx-sha** [primefaces/primefaces#12812]
### Describe the bug

 I am working on project where platform hosting the PrimeFaces needs to provide or manage the CSP headers and nonce on scripts.For example application which has mix of different components coexisting with prime faces components.

I was trying to use the same policy provided options as described in the  https://primefaces.gthub.io/primefaces/12_0_0/#/core/contentsecuritypolicy

I providing the nonce in my template file.

 I am using Facelets template file. 

The nonce addition works for inline script but does not work with following components

- <p:ajaxstatus>
- <p:remotecommand>
- <p:dialog>
-

For example :

![NonceProject](https://github.com/user-attachments/assets/47bba979-991e-456d-8b45-47a28d31a8c1)

### Expected behavior

Provided nonce to be added 

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

Java 8 

### Browser(s)

Chrome

**Comment by melloware** [comment]
I don't think this will work PrimeFaces HAS to control the NONCE.  You can control everything else but PF has to be in charge of the NONCE as it changes on every AJAX request

**Comment by tandraschko** [comment]
still the documentation is very unclear what this does:
```
<context-param>
    <param-name>primefaces.CSP</param-name>
    <param-value>policyProvided</param-value>
</context-param>
```

**Comment by melloware** [comment]
@MijnRVO-general  can you clarify how this is used?  Its not making sense to any of us?

**Comment by dspx-sha** [comment]
Actually it will be useful to know how portlet scenario uses it. As it will be great help, as we have the same scenarios like where we need to provide nonce to other component's which are non prime faces custom components. So if we enable the Prime Faces policy. It ends up duplicating the csp policy.
<context-param>
    <param-name>primefaces.CSP</param-name>
    <param-value>policyProvided</param-value>
</context-param>

**Comment by tandraschko** [comment]
@dspx-sha we would also need a sample project from your side, what you are trying to archive.

**Comment by dspx-sha** [comment]
Yes thanks I will provide an example as early as possible.

**Comment by MijnRVO-general** [comment]
> @MijnRVO-general can you clarify how this is used? Its not making sense to any of us?

Sorry for the late response, got a little lost in the inbox. 

We co-developed a module for Liferay which manages CSP for the entire site (which is now coming available in the latest release of Liferay I believe). So it manages the nonce/CSP stuff for Liferay itself, our own theme for Liferay, and the components supplied by Primefaces.

As we've implemented this a few years back I have to look into this again for the specifics. It's on my todo list, but it may take some time.

**Comment by MijnRVO-general** [comment]
The "policyProvided" setting is needed for use with Liferay 7.1 and later versions, at least up to 7.4. They do not support CSP.

Luckily we were able to replace almost all inline styling, but removing inline javascript was not possible. So we needed to work with nonces for that.

One of the Liferay developers helped us with creating a module that adds two filters.

1. CSPPageFilter, which processes each request to add nonces where needed (inline javascripts, forms etc.). It skips on non-page requests (images, javascript files, etc.) and some others (it's own management pages for instance). It also accepts nonces from a request-parameter and uses that in the filter. This is needed for ajax-requests that supply HTML to the client, as these need the same nonce as the page it is called from.
2. CSPSubstitutionFilter, which replaces some non-compliant content we could not replace ourselves with CSP-compliant code.

As Primefaces is only used for parts of some pages in the site, and only one nonce is possible in the CSP-headers, Primefaces should not generate it's own nonce. This is what is also described in the Primefaces docs https://github.com/primefaces/primefaces/blob/master/docs/15_0_0/core/contentsecuritypolicy.md with the value "policyProvided".

You can see this in action at https://mijn.rvo.nl/. Please be gentle.

**Comment by melloware** [comment]
OK I am updating the docs. I moved this section to the bottom of the doc so people don't think its a widely supported feature and called out its Liferay specific. I can't see how this would be useful in any actual JSF environment.
