### ISSUE TITLE
Dashboard: Scope of jquery drag and drop should be configurable

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#12825]
### Description

At the moment the scope of draggable droppable is hardcoded to "dashboard" which is fine as long as only one dashboard is used per page. I have a scenario where I have three different sections each containing a dashboard with items. To prevent the items from one section to be draggable to a different section i need a different scope in the jquery config.

### Describe the solution you would like

_Scope_ should be configurable in the dashboard tag and then passed forward to the jquery draggable/droppable part.

**Comment by melloware** [comment]
Excellent addition I must have never figured someone would have more than 1 dashboard that was my bad vision!
