### ISSUE TITLE
TreeTable:DataExporter csv column headers are not exported.

### ISSUE THREAD

**Issue by KursatErenColak** [primefaces/primefaces#12824]
### Describe the bug

When export CSV with TreeTable Column headers are not exported to excel file.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.6

### Theme

Poseidon

### JSF implementation

Mojarra

### JSF version

4.0.5

### Java version

21

### Browser(s)

Chrome Version 127.0.6533.120

**Comment by melloware** [comment]
OK i can reproduce it, its weird its just the CSV export the other exports all have the headers.

**Comment by KursatErenColak** [comment]
> OK i can reproduce it, its weird its just the CSV export the other exports all have the headers.

Yes, others are eorking normaly. Thanks gor support @melloware

**Comment by melloware** [comment]
Yep will be fixed for 14.0.7
