### ISSUE TITLE
RemoteCommand: Nested in IFrames

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#12838]
### Describe the bug

I'm trying to add a workaround to have the sorely missing ability to react to a dynamically opened child dialog closing via X button. My solution (providing remoteCommand call that goes into onHide) works with page launching a dialog, but not with 2+ levels of nested dialogs like page (A) launching a dialog (B) launching a dialog (C). Each level has its own uniquely named remoteCommand, but only the main level one is visible and called. Closing dialog B always calls remote command from page A. If I do not use unique names, closing dialog C calls remoteCommand from page A. If I use unique names, closing dialog C doesn't call anything. Is this a PF limitation, JSF limitation, HTML limitation or am I missing something that would allow me to realize this workaround?

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.5

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

21

**Comment by tandraschko** [comment]
Please provide a primefaces-test reproducer, otherwise its to difficult to understand.

**Comment by morvael** [comment]
Don't think so, names match, everything is correct. It just doesn't see script inside iframe. Besides it was extremely confusing to find out that onHide is called for top/parent window, not the dialog window/iframe. I think it's never mentioned in the docs that it works like this.

Will try to make the reproducer.

**Comment by morvael** [comment]
[primefaces-test-dialogs.tar.gz](https://github.com/user-attachments/files/17635460/primefaces-test-dialogs.tar.gz)

**Comment by morvael** [comment]
Start the reproducer, use "Open next" to get to level 4 dialog. Start closing via "Close me" buttons. You should see in the log:
```
INFO: L1.init
INFO: L1.openNext
INFO: L2.init
INFO: L2.openNext
INFO: L3.init
INFO: L3.openNext
INFO: L4.init
INFO: L4.closeMe
INFO: L3.onDialogReturn
INFO: L3.closeMe
INFO: L2.onDialogReturn
INFO: L2.closeMe
INFO: L1.onDialogReturn
INFO: L1.onHideCommand
```
Each level properly got onDialogReturn, L1 in addition got onHideCommand.

**Comment by morvael** [comment]
Now let's change
`id="#{testView.getUniqueId('rc')}" name="#{testView.getUniqueId('rc')}"` to `id="rc" name="rc"` (in XHTML) and `getUniqueId("rc")` to `"rc"` (in Java), and do 2nd scenario:
```
INFO: L1.init
INFO: L1.openNext
INFO: L2.init
INFO: L2.openNext
INFO: L3.init
INFO: L3.openNext
INFO: L4.init
INFO: L1.onHideCommand
INFO: L1.onHideCommand
INFO: L1.onHideCommand
```
As you can see all calls to remoteCommand went to level 1. So the higher levels are able to call remote command, just not the one with "their" name.

**Comment by morvael** [comment]
Of course what I want to get in scenario 1:
```
INFO: L1.init
INFO: L1.openNext
INFO: L2.init
INFO: L2.openNext
INFO: L3.init
INFO: L3.openNext
INFO: L4.init
INFO: L4.closeMe
INFO: L3.onDialogReturn
INFO: L3.onHideCommand
INFO: L3.closeMe
INFO: L2.onDialogReturn
INFO: L2.onHideCommand
INFO: L2.closeMe
INFO: L1.onDialogReturn
INFO: L1.onHideCommand
```
and in scenario 2:
```
INFO: L1.init
INFO: L1.openNext
INFO: L2.init
INFO: L2.openNext
INFO: L3.init
INFO: L3.openNext
INFO: L4.init
INFO: L3.onHideCommand
INFO: L2.onHideCommand
INFO: L1.onHideCommand
```

**Comment by tandraschko** [comment]
it works fine without dialog framework?
i wont invest time in this sorry. maybe someone else can, dialog framework mostly makes everything worse.

**Comment by morvael** [comment]
I don't know what you mean? First you want reproducer, then you say you won't invest time in this. Then why I did invest mine in reproducer? :) Anyway, this can't be done without dialog framework, as this is my requirement - to use this within dialog framework.

**Comment by morvael** [comment]
In essence dialog framework (or whatever) sees the command only in the top window, not in the iframes. Maybe it's PF limitation, maybe JSF one, maybe HTML one. Not an expert here. If it can't be done, it can't be done. But maybe it's easy to "dig" into iframes and find named function there?

**Comment by tandraschko** [comment]
yeah
in general we mostly need a reproducer, it doesnt mean that i invest time instantly ;D

https://stackoverflow.com/questions/13757943/access-a-variable-of-iframe-from-parent
you can access variables of iframes, we just wont add this automagically to PF, you have to do it by your own.

**Comment by morvael** [comment]
This is just workaround anyway for not being able to hook custom code into X button, about which you were pestered since 2017 at least 😀

And since I have entire framework built around this (a very flexible JSON-configured web page does everything and can call other variants of itself in dialogs), it's quite limiting not to be able to hook into close and replace default process (or at least be notified its closing).

I will explore looking for nested function.

**Comment by melloware** [comment]
@morvael nothing stopping you from a submitting a PR for the feature you need.

**Comment by morvael** [comment]
Well, it wasn't my request in the past. And library/engine creators always overestimate the ability of library/engine users to add something to library/engine. It's like an order of magnitude more difficult 😀

**Comment by melloware** [comment]
I fixed your reproducer: 
[pf-12838.zip](https://github.com/user-attachments/files/17636535/pf-12838.zip)

As @tandraschko you have to understand how iFrames work in the browser.

**Comment by morvael** [comment]
Thanks, I guess I'll have to do some more complicated digging when there are no numbered levels like in the reproducer.

**Comment by melloware** [comment]
what you can do...

is loop over `window.frames` collection and test if your RC function you are looking for exists and call it.

**Comment by morvael** [comment]
Yes, something like this. Thanks again!

**Comment by morvael** [comment]
If someone will look at this thread in years to come. Sources:

- https://stackoverflow.com/questions/31510642/display-all-frames-list-for-any-webpage
- https://stackoverflow.com/questions/1042138/how-to-check-if-function-exists-in-javascript
- https://stackoverflow.com/questions/359788/how-to-execute-a-javascript-function-when-i-have-its-name-as-a-string

Code:
```
function getAllFrames(frame, allFrameArray) {
    allFrameArray.push(frame.frames);
    for (var i = 0; i < frame.frames.length; i++) {
        getAllFrames(frame.frames[i], allFrameArray);
    }
    return allFrameArray;
}

function callCorrectRemoteCommand(fName) {
    var allFramesArray = getAllFrames(window, new Array());
    for (var i = 0; i < allFramesArray.length; i++) {
        var f = allFramesArray[i];
        if (typeof f[fName] === "function") {
            f[fName]();
        }
    }
}
```
and
```
PrimeFaces.current().dialog().openDynamic("test", DialogFrameworkOptions.builder().modal(true).onHide(String.format("callCorrectRemoteCommand('%s');", getUniqueId("rc"))).build(), params);
```

**Comment by melloware** [comment]
Nice work @morvael !
