### ISSUE TITLE
SelectOneMenu: Filtering not triggered on paste

### ISSUE THREAD

**Issue by crcatedr** [primefaces/primefaces#12834]
### Describe the bug

In Chrome, filtering is not triggered in the SelectOneMenu if the search value is pasted. 

### Reproducer

https://github.com/orgs/primefaces/discussions/2946

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

17

### Browser(s)

Chrome 130.0.6723.92

**Comment by melloware** [comment]
PR submitted for 14.0.7 i fixed it for Firefox and Chrome.
