### ISSUE TITLE
TabMenu: Scrollbar below TabMenu on Google Chrome

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#12845]
### Describe the bug

If you open http://www.primefaces.org/showcase/ui/menu/tabMenu.xhtml in latest google chrome version you will always see a scrollbar below tabmenu due to `overflow-x:scroll` rule on `.ui-tabmenu-nav`.  `auto` would probably be the better behaviour.

### Reproducer

Open http://www.primefaces.org/showcase/ui/menu/tabMenu.xhtml in Google Chrome

### Expected behavior

Scrollbar should only be visible if number of tabs exceeds screenwidth

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### Theme

Saga,Arya, all based on ThemeBase

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

### Browser(s)

Chrome Version 130.0.6723.117 (Offizieller Build) (64-Bit)

**Comment by tandraschko** [comment]
@melloware if you wanna merge to 14.x, feel free
but remember to copy all themes.css to pf and showcase

**Comment by melloware** [comment]
got it
