### ISSUE TITLE
TieredMenu: ShowDelay should use delayed hover effect if toggleEvent is hover

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#12841]
### Description

At the moment the showDelay only delays the showing of the submenu by X ms, but it has no effect at whether the event is fired at all or not. Meaning the submenu of a e.g menubar or tieredmenu will be shown even if I hover of the item for less than showDelay ms.

To reproduce this behavior set a relative high showDelay (1sec) and quickly move over the items of a menubar. The submenu will popup long after you left the item.

Also if I leave a TieredMenu the last active submenu stays open if hideDelay = 0, I think it should be closed immediatly.

### Describe the solution you would like

A submenu should should only be shown if the mouse hovers over the desired element for longer than `showDelay`.
That way accidental hovers won't trigger a submenu display.

**Comment by melloware** [comment]
Agreed
