### ISSUE TITLE
moment.js gets loaded twice when client side validation is enabled

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#12855]
PrimeFaces version: 15.0.0-SNAPSHOT

**Issue**

`moment.js` gets loaded twice when client side validation is enabled.

Start the showcase and go to e.g. `http://localhost:8080/showcase/ui/chart/bubble.xhtml`. Check the network tab, `moment.js` is loaded twice. 

This happens since #11943.  `moment.js` is included as a `ResourceDependency` on the `Chart` component, and again in the `HeadRenderer`:

https://github.com/primefaces/primefaces/blob/0d7b7b84ad436cf91cb97e7fa7560e88ae3170c3/primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java#L141

The downsides are that (a) more code than necessary is loaded, and (b) there are now 2 instances of `moment.js` co-existing and any setup like `moment.defineLocale` won't affect the other instance. Especially with the refactor from #12717, the first instance of `moment.js`  can be captured by some code before the other instance is loaded.

**Possible solution**

The `HeadRenderer` always inserts `<script>` element with moment.js, without regard for whether that resource is already included. [OmniFaces has a addScriptResource](https://omnifaces.org/docs/javadoc/current/org.omnifaces/org/omnifaces/util/Components.html#addScriptResource(java.lang.String,java.lang.String)) utility function that takes care of this. We don't use OmniFaces, but I saw there's a `org.primefaces.util.ResourceUtils` with a `addComponentResource` method, though that might need some additions such as the [ResourceHandler.isResourceRendered check from OmniFaces](https://github.com/omnifaces/omnifaces/blob/372a78d66ec8b460066ca7e6d56c96c1bccc6dd0/src/main/java/org/omnifaces/util/ComponentsLocal.java#L316) .

Perhaps just adding the `ResourceHandler.isResourceRendered` is also enough already.

![image](https://github.com/user-attachments/assets/c70b6784-ce7e-4f24-a434-899c234855b3)

**Comment by melloware** [comment]
Yes we need to do something.  PFE has that special handler to work with OmniFaces and @BalusC just asked this the other day about getting rid of the PF HeadRenderer: https://github.com/omnifaces/omnifaces/issues/876#issuecomment-2453088059

**Comment by tandraschko** [comment]
AFAIR in the past we had something like uiViewRoot#addComponentResource but it didnt work in all cases
the current approach was safe
but it might has been changed already, maybe we can put into a PhaseListener

**Comment by melloware** [comment]
PR Submitted if you want to test if that fixes it.  It definitely can't hurt to check for an already rendered resource?

**Comment by blutorange** [comment]
> PR Submitted if you want to test if that fixes it. It definitely can't hurt to check for an already rendered resource?

I would agree, it definitely helps to prevent some cases, even though it can still happen with JSTL tags.

**Comment by melloware** [comment]
I asked BalusC how we could get rid of HeadRenderer and his suggestion..

> Replace by SystemEventListener and drop support for first/middle/last facets. If these are however mandatory for the user base then keep the HeadRenderer but it must obviously not anymore add hardcoded resources and wrap the original HeadRenderer rather than replacing it altogether (this is possible via a renderkit factory).
