### ISSUE TITLE
Datatable: Toggler to show/hide filter input components

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#12853]
### Description

During my migration of our primefaces project I'm going through our extensions/enhancements and try to mainstream/baseline them as much as possible. One of our extensions is a javascript toggler to show/hide (fade in/ fade out) filter components in a datatable.
For pages where filtering is the exception and not the regular case we tend to keep the initial ui as clean and simple as possible.
Meaning all the filter fields are hidden, but can be shown by clicking on a toggle.

### Describe the solution you would like

The whole logic happens only via js/css. So the fields will be rendered as usually. Default filters are still taken into account, they are just not visible.

See video for actual behaviour:
https://github.com/user-attachments/assets/4f74caa9-eebb-43c6-9cd9-d784caf5382f

The toggle buttons can either be bound via a trigger attribute in the datatable itself or  called manually on any component via a Javascript Widget method.

Is this something you might want to add to PF? If yes I can provide a PR with the changes.

**Comment by melloware** [comment]
is this just a widget method? Or does it require Java changes as well?

**Comment by gako** [comment]
Some java changes to find the clientid of the trigger button and an additional css class to hide the input fields for convenience

**Comment by melloware** [comment]
well in theory if you could do it all in 1 Widget method `toggleFilters()` with the CSS needed then you could wire up any button our UI to it wiht `onclick="PF('dt').toggleFilters();` to make it more flexible to users rather than built in button or UI?

**Comment by gako** [comment]
The logic to show hide the components is all in a toggleFilters() and yes you can fire it like you mentioned. The trigger part is just another way of binding it to a button, similiar to columnToggle but not necessary. All that's additionally needed is a special css class to initially hide all input components e.g. `ui-filter-togglable` in the datatable. That class could also be added manually via datatable `styleClass`. So with these two manual steps it could be a javascript only addition.

Full blown java & js version can be seen here: 
https://github.com/primefaces/primefaces/compare/master...gako:primefaces:DatatableFilterToggle

**Comment by melloware** [comment]
hmmm its definitely not bad i am just not sure about adding the HTML when someone can just do this...

```xml
<f:facet name="header">
            <p:toggleSwitch id="manualToggle" onchange="PF('customersTable4').toggleFilter()" onIcon="pi pi-filter" offIcon="pi pi-filter-slash"/>
</f:facet>
```

with no changes to the Java?  We could just add the showcase example in the Filter showcase and show people how to use it?

**Comment by gako** [comment]
java is optional  and usually not necessary, I agree. What needs to be added is an additional css class to initially hide the filters `ui-filter-togglable`. This then has to be set manually via 
`<datatable styleClass="ui-filter-toggleable" ...`

I'll adjust the branch to represent this version

**Comment by melloware** [comment]
Awesome!

**Comment by tandraschko** [comment]
providing it as base API is great BUT
i wonder if this we should render the toggler in the header somehow in PF itself and a introduce a new attribute "togglableFilters" or similar?

**Comment by melloware** [comment]
@tandraschko he had it that way originally and I asked him to take it out. Sorry @gako !

**Comment by tandraschko** [comment]
then we should talk a bit about it before applying something

**Comment by melloware** [comment]
@tandraschko i am ok if you want to go that way my thought it was more like ColumnToggler: https://www.primefaces.org/showcase/ui/data/datatable/columnToggler.xhtml?jfwid=ab16b allowing a user to use it how they want an in this case put a Toggle Button anywhere on the screen and use the JS?

**Comment by melloware** [comment]
@gako @tandraschko what did we decide here?  Personally I like the widget method and showcase example as is but @tandraschko you were advocating for rendering the toggle in the table header?

**Comment by tandraschko** [comment]
i need time here
propably RC2, lets see how much time i have left after resolving my fileupload tasks
