### ISSUE TITLE
OverlayPanel: will be visible even if showEvent is set to none

### ISSUE THREAD

**Issue by Leviathan133** [primefaces/primefaces#12870]
### Describe the bug

p:overlayPanel is visible even its showEvent is set to none.
This happen cause i hit enter inside an Input in this case an p:autoComplete.

i would like to show the OverlayPanel only if a condition is met with primefaces.executeScript("PF('overlay').show()").

### Reproducer

Just type something inside the autocomplete and press enter on your keyboard.
This will make the overlayPanel  visible.

[primefaces-test-master.zip](https://github.com/user-attachments/files/17707029/primefaces-test-master.zip)

### Expected behavior

If the showEvent of an overlayPanel is set to none i would expect that it will be never visible.
Or only, if i call via JS PF('overlayPanel').show();

### PrimeFaces edition

None

### PrimeFaces version

14.0.0

### JSF implementation

All

### JSF version

latest

### Java version

17

**Comment by melloware** [comment]
@StealthCore1 yep let me look.

**Comment by melloware** [comment]
ok issue is because when you press ENTER on target it toggles the Overlay.

```js
    $this.target.off('keyup.ui-overlaypanel').on('keyup.ui-overlaypanel', function(e) {
      if (PrimeFaces.utils.blockEnterKey(e)) {
        $this.toggle();
      }
    });
```

to remove that here is a MonkeyPatch:

```js
if (PrimeFaces.widget.OverlayPanel) {
  PrimeFaces.widget.OverlayPanel.prototype.bindTargetEvents = function() {
    var $this = this;

    //mark target and descandants of target as a trigger for a primefaces overlay
    this.target.data('primefaces-overlay-target', this.id).find('*').data('primefaces-overlay-target', this.id);

    //show and hide events for target
    if (this.cfg.showEvent === this.cfg.hideEvent) {
      var event = this.cfg.showEvent;

      this.target.on(event, function(e) {
        $this.toggle();
      });
    } else {
      var showEvent = this.cfg.showEvent + '.ui-overlaypanel',
        hideEvent = this.cfg.hideEvent + '.ui-overlaypanel';

      this.target.off(showEvent + ' ' + hideEvent).on(showEvent, function(e) {
          if (!$this.isVisible()) {
            $this.show();
            if (showEvent === 'contextmenu.ui-overlaypanel') {
              e.preventDefault();
            }
          }
        })
        .on(hideEvent, function(e) {
          clearTimeout($this.showTimeout);
          if ($this.isVisible()) {
            // GitHub #8546
            if (!$this.isAutoHide() && $(e.relatedTarget).is('div.ui-overlaypanel-content')) {
              $this.allowHide = false;
              return;
            }

            $this.hide();
          }
        });
    }



    this.bindAutoHide();
  },
};
```
