### ISSUE TITLE
Terminal - add async support

### ISSUE THREAD

**Issue by spauny** [primefaces/primefaces#1287]
As a quick fix we can enable async by default for Terminal... 
Can't really think of an example where this is a bad idea. 

I will try to create a pull request these days if you guys think it's a welcomed improvement.

**Comment by tandraschko** [comment]
what exactly do you mean?

If you mean the ajax async flag, we should introduce a behavior for it, so we can set every ajax setting to p:ajax.

**Comment by spauny** [comment]
Enable ajax async request.
At the moment, the terminal's processCommand javascript function calls PrimeFaces.ajax.Request.handle: 

`processCommand: function() {

```
    var $this = this,
    options = {
        source : this.id,
        update: this.id,
        process: this.id,
        params: [
            {name: this.id + '_command', value: true}
        ],
        onsuccess: function(responseXML, status, xhr) {
            PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
                    widget: $this,
                    handle: function(content) {

                    }
                });

            return true;
        }
    };

    PrimeFaces.ajax.Request.handle(options);
}`
```

The Request.handle function checks if the options(cfg) object has async set to true and fires an ajax request if it does. Otherwise it will just add the request into Queue: 

`Request: {

```
    handle: function(cfg, ext) {
        cfg.ext = ext;

        if(cfg.async) {
            PrimeFaces.ajax.Request.send(cfg);
        }
        else {
            PrimeFaces.ajax.Queue.offer(cfg);
        }
    }`
```

All we need to do is add the async attribute to the Terminal's options. And set this to true when we want the Terminal's command to be processed right away instead of waiting in the queue until the other ajax requests are done.

**Comment by tandraschko** [comment]
Yep, so it's better to introduce a behavior event.
