### ISSUE TITLE
Invalid PrimeFaces namespace url

### ISSUE THREAD

**Issue by js361014** [primefaces/primefaces#12906]
### Describe the bug

http://primefaces.org/ui namespace url is invalid - no xml schema found, it redirects to https://www.primefaces.org/uikit/licenses

### Reproducer

Just follow instructions from https://www.primefaces.org/gettingstarted/

### Expected behavior

http://primefaces.org/ui should lead to xml schema.

### PrimeFaces edition

None

### PrimeFaces version

14.0.7

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
@js361014 that is not how JSF works.  That is just a namespace to match up to found `taglib.xml` in a tag library.

In Faces 4.0 that is renamed from a URL to a URN so in Faces 4.0 its `xmlns:p="primefaces"` to get rid of this misleading use of namespace.

**Comment by melloware** [comment]
See the Faces spec change here: https://github.com/jakartaee/faces/issues/1553

**Comment by js361014** [comment]
> See the Faces spec change here: [jakartaee/faces#1553](https://github.com/jakartaee/faces/issues/1553)

Thank you.
