### ISSUE TITLE
dialog framework dialogs without height not centered by default

### ISSUE THREAD

**Issue by agoetze** [primefaces/primefaces#1290]
As the title says. You can easily verify this problem by looking at the current show case:
http://www.primefaces.org/showcase/ui/df/basic.xhtml

Button "View": no height set -> dialog not centered (vertically)
Button "Options": height set to 640 -> dialog centered (vertically)

Tested with Firefox 45 under Ubuntu and with Internet Explorer 11 under Windows 7.

Expected default behaviour: Dialog centered (horizontally and vertically)

**Comment by sergi-mm** [comment]
We also experiment the same issue using Primefaces 5.3.14 (latest version of 5.3 at the moment of writting).

**Comment by jaymesanches** [comment]
Is it not working in primefaces 6.0 yet?

**Comment by smckeetx** [comment]
Using PF 6.1 the dialog is centered horizontally but not vertically. This is a problem.

**Comment by Maikel-Nait** [comment]
BTW, I fixed it myself by overriding the original PrimeFaces.dialog.DialogHandler.

The original code in PF 6.1 has these two lines of code BEFORE a block that starts with the comment //adjust height

`dialogFrame.data('initialized', true);`
`rootWindow.PF(dialogWidgetVar).show();`
`//adjust height`

By just swapping these two lines AFTER the code that adjusts the height, the dialogs can be centered both horizontally and vertically as expected:


`//adjust height`
`var frameHeight = null;`
`if(cfg.options.contentHeight)`
`         frameHeight = cfg.options.contentHeight;`
`else`
`         frameHeight = $frame.get(0).contentWindow.document.body.scrollHeight + `
`                                  (PrimeFaces.env.browser.webkit ? 5 : 25);`
`$frame.css('height', frameHeight);`

Moved lines to the end of this code block:

`dialogFrame.data('initialized', true);`
`rootWindow.PF(dialogWidgetVar).show();`

So far it works fine in Chrome, Firefox and IE11 .... maybe this could be an easy fix for this problem ??

**Comment by Rapster** [comment]
You can write a PR so @tandraschko or @mertsincan  can have a look and merge into PF master branch

**Comment by Maikel-Nait** [comment]
Done. Created PR here:  [https://github.com/primefaces/primefaces/pull/2463](https://github.com/primefaces/primefaces/pull/2463)
