### ISSUE TITLE
DataTable: double header

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#12908]
### Describe the bug

Using data table with p:columns, header facets and scrollable I get double column header (one fixed, one scrollable):
![Screenshot 2024-11-19 at 09-14-35 PrimeFaces Test](https://github.com/user-attachments/assets/cb0f6bc5-0f98-4f15-9ff7-310f4ded96ce)

### Reproducer

Reproducer:
[primefaces-test-columns.tar.gz](https://github.com/user-attachments/files/17811782/primefaces-test-columns.tar.gz)

### Expected behavior

I would like to see only the fixed header, and not the scrollable one.

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.7

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21.0.5+11

**Comment by morvael** [comment]
There's also this ugly bug where input editors in the last column stay when you use mouse to click other cell:
![Screenshot 2024-11-19 at 09-19-52 PrimeFaces Test](https://github.com/user-attachments/assets/7aa740a6-852d-4ba8-aa92-0654c9c86764)
(input editor keeps new value, output label keeps old value, and you can use Tab through that bad cell to make the input editor disappear, but this is all messed up).

**Comment by melloware** [comment]
@morvael to get rid of the double headers...

```css
.ui-datatable-scrollable-theadclone th.ui-state-default {
   height: 0 !important;
}
```

**Comment by morvael** [comment]
Will be reporting another one using similar reproducer - big table of this style (no cell editing just inputs) loads in 9 seconds in Firefox, while it takes 2-6 minutes on Edge :(
