### ISSUE TITLE
Line chart doesn't work with String X values

### ISSUE THREAD

**Issue by guibamp** [primefaces/primefaces#1291]
I'm using PrimeFaces 5.3.
This simple example should result in a chart containing a single dot in the middle of the chart panel.

xhtml:
`<p:chart type="line" model="#{myBean.sampleChart}" />`

bean:

```
    private LineChartModel sampleChart;

    @PostConstruct
    public void postConstruct(){
        sampleChart = new LineChartModel();
        sampleChart.setTitle("Monthly performance");
        sampleChart.setExtender("extLegend");
        sampleChart.setAnimate(true);
        sampleChart.getAxis(AxisType.Y).setLabel("% achievement");
        sampleChart.getAxis(AxisType.Y).setMin(0);
        sampleChart.getAxis(AxisType.Y).setMax(100);
        LineChartSeries series = new LineChartSeries();
        series.setLabel("Running");
        series.set("3/2016", 40D);
        sampleChart.addSeries(series);
    }
```

See how I'm using "3/2016" as X value? The chart dots and line are not showing up using such String. If I use only number Strings, or numbers, such as "3" or 3L, then the chart works properly.

This was working fine with PrimeFaces 4 (p:lineChart & CartesianChartModel).

**Comment by halisyilboga** [comment]
It must be related to jqplot library since rendered output is correct. But the jqplot  could not plot the lines according to unraleted strings. By the way I have exactly same problem. 
`$(function(){PrimeFaces.cw('Chart','chartLine',{id:'reportForm:reportTabView:j_idt255',type:'line',data:[[["Boş",3779],["Türkçe",659],["İngilizce",31],["Osmanlı Türkçesi",24],["Fransızca",20],["Diğer",12],["Çince",9],["Urdu",8],["Bilinmiyor",4],["İspanyolca",3],["Almanca",2],["Hırvatça",2],["Kazakça",2],["Arapça",2],["Hindi",1],["Macarca",1],["Yunanca",1],["Sırpça",1],["Portekizce",1],["Romence",1],["Kırgızca",1],["Arnavutça",1],["Makedonca",1],["Çekce",1],["Rusça",1],["Kürtçe",1],["İtalyanca",1],["Azerice",1],["Moldovca",1],["Türkmence",1],["Özbekçe",1],["Bulgarca",1],["Ermenice",1],["Lehçe (Polonyaca)",1],["Japonca",1]]`

**Comment by guibamp** [comment]
For this specific case I was able to use `DateAxis` setting the `tickFormat` as `"%#m/%Y"`, because after all my X axis is about months. But I have other charts where, the same way you do, my X axis is about **unrelated** words. Not sure how to proceed then...

**Comment by halisyilboga** [comment]
it is interestingly working when choosing bar chart and line series instead of LineChartModel. I think it works as in combined version of primefaces charts. Below code resolved my issue. 

`
<p:chart type="bar" widgetVar="chartLine" style="width:99%; height:700px"
                model="#{dashboardController.lineChartModel}"/>
`

Bean part is below

```
 public BarChartModel getLineChartModel() {
        final LineChartSeries series1 = new LineChartSeries();   
            this.lineChartModel = new BarChartModel();
           final String sql = this.prepareSqlQuery();
            final List<Object[]> list = this.dashboardFacade.getObjectList(sql);
            for (final Object[] chartObject : list) {
                if (chartObject[0] != null) {
                    series1.set(String.valueOf(chartObject[0]), Integer.valueOf((String.valueOf(chartObject[1]))));
                }
            }
            this.lineChartModel.setTitle(this.selectedMetadata.getName());
            this.lineChartModel.addSeries(series1);
            this.logModel.setAnimate(true);
            this.logModel.setDatatipFormat(this.getDatatipFormat());
            this.logModel.setLegendPosition("e");

        }

        return this.lineChartModel;
    }
```

**Comment by cagataycivici** [comment]
You need to use a CategoryAxis for the axis that has the string values as in;

http://www.primefaces.org/showcase/ui/chart/line.xhtml

**Comment by halisyilboga** [comment]
This Doesn't work string any more. like @gbmpereira  said it can be used for time series but with some tweaks but can't for string like language list that I've been shared above. But this is not related to primefaces. "jqplot" library removed that capability. I think they thought it is not logical to use string indexes in line charts. Using bar is more logical.
