### ISSUE TITLE
DataTable: slow loading times on Edge

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#12912]
### Describe the bug

I have a data table with p:columns for content that can have up to ~100 rows and up to ~256 columns. While I know it will run not so fast, the loading times on Edge are counted in minutes (depending on client machine speed), while on Firefox in seconds. So it's related to some problems Edge has (was unable to test on Chrome).

When running the reproducer you may wish to use `mvn clean jetty:run -Pmojarra40 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=10000000 -Dorg.eclipse.jetty.server.Request.maxFormKeys=30000` so the server won't complain there are so many fields in the form.

### Reproducer

[primefaces-test-columns.tar.gz](https://github.com/user-attachments/files/17815656/primefaces-test-columns.tar.gz)

### Expected behavior

Similar load times on Edge (and Chrome) as on Firefox.

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.7

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21.0.5+11

### Browser(s)

Edge 131.0.2903.51 64-bit official

**Comment by melloware** [comment]
as expected Chrome and Edge perform the same as they are both Chromium. Firefox loads in 5 seconds.  Its 18.71 MB worth of data its trying to render.

**Comment by melloware** [comment]
@morvael this the exact reason we wrote Sheet for our client: https://www.primefaces.org/showcase-ext/views/sheet.jsf

When you cell edit it only sends 1 cell at a time not submit 30,000 cells etc.

**Comment by morvael** [comment]
Hmm, I'll have to run it differently, as "dynamic" columns via `<c:forEach` will not work for me, I need them added/removed by the user on the fly (but I can work around this by always showing max columns which is 256 right now).

**Comment by melloware** [comment]
yeah its NOT perfect but it solved my clients needs of needing Excel like editing of lots of DATA.
