### ISSUE TITLE
FileUpload: Uncaught TypeError: PrimeFaces.validation is undefined

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#12923]
### Describe the bug

Upon uploading a file the following error occurs in the Browser console:

`Uncaught TypeError: PrimeFaces.validation is undefined`

This seems only be the case when adding the PrimeFaces Extensions `PrimeFacesScriptProcessor` / `PrimeFacesResourceProcessor` to the OmniFaces `CombinedResourceHandler` in `faces-config.xml`.

It is suspected, that this regression was introduced in 14.0.6 via the following change: https://github.com/primefaces/primefaces/issues/12855

### Reproducer

https://github.com/stolp/primefaces-test/tree/pf-12923

### PrimeFaces edition

Community

### PrimeFaces version

14.0.7

### JSF implementation

MyFaces

### JSF version

2.3-next

### Java version

21

**Comment by melloware** [comment]
Ahh this belongs over at PrimeFaces Extensions repo.  I don't think this is related to PF itself but I will check.

**Comment by melloware** [comment]
Fixed over at Extensions: https://github.com/primefaces-extensions/primefaces-extensions/pull/1770

**Comment by melloware** [comment]
@stolp got to the bottom of the real issue/ PFE was loading validation.js BEFORE PF core.js so it would do `if (window.PrimFaces){` and it was false and it would bail out!
