### ISSUE TITLE
Tree: do not update aria-expanded attribute 

### ISSUE THREAD

**Issue by EugenFischer** [primefaces/primefaces#12929]
### Describe the bug

the **aria-expanded** attribute of the node does not get updated when that get expanded or collapsed.

follow quickfix solve the problem
```
if (PrimeFaces.widget.VerticalTree) {
  const primeFacesWidgetVerticalTreeExpandNodeOriginal = PrimeFaces.widget.VerticalTree.prototype.expandNode;
  PrimeFaces.widget.VerticalTree.prototype.expandNode = function(node) {
    primeFacesWidgetVerticalTreeExpandNodeOriginal.apply(this, arguments);
    $(node).children().first().attr('aria-expanded', 'true');
  };

  const primeFacesWidgetVerticalTreeCollapseNodeOriginal = PrimeFaces.widget.VerticalTree.prototype.collapseNode;
  PrimeFaces.widget.VerticalTree.prototype.collapseNode = function(node) {
    primeFacesWidgetVerticalTreeCollapseNodeOriginal.apply(this, arguments);
    $(node).children().first().attr('aria-expanded', 'false');
  };
}
```

### Reproducer

1. go to  http://www.primefaces.org/showcase/ui/data/tree/contextMenu.xhtml
2. verify on dev tools the html structure > aria-expanded of an element which get expanded or collapsed

### Expected behavior

attribute aria-expanded get updated 

### PrimeFaces edition

Community

### PrimeFaces version

13.0.10, 14.0.6

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

17

### Browser(s)

Any browser

**Comment by melloware** [comment]
@EugenFischer 14.0.8 is released if you want to test these changes. 

It's deployed here if you want to inspect the HTML or screen reader https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/tree/basic.xhtml?jfwid=490b9
