### ISSUE TITLE
UploadedFile#write broken

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#12933]
the param is currently called filePath, but its actually the directory. If yes we should return the whole filepath then and rename the param to directory.
we should also check docs

**Comment by tandraschko** [comment]
anyone interessted?

**Comment by melloware** [comment]
i can take this one.

**Comment by tandraschko** [comment]
i think even the whole method is broken....

```
    @Override
    public void write(String filePath) throws Exception {
        File file = new File(filePath, filename);
        FileUploadUtils.requireValidFilePath(file.getCanonicalPath(), true);
        write(file);
    }
```

if i do:
```
                    String tempDirectory = System.getProperty("java.io.tmpdir");
                    String filePath = tempDirectory + "/" + event.getFile().getFileName();

                    event.getFile().write(tempDirectory);
```

i get:
`java.lang.RuntimeException: jakarta.faces.validator.ValidatorException: File Error: Invalid file, "C:\Users\tandraschko\AppData\Local\Temp\PHOTO-2024-06-29-23-30-07-9.jpg" does not exist.`

it should actually validate the directory exists, not the whole file itself.
