### ISSUE TITLE
HeadRenderer: Prevent duplicates 

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#12949]
### Description

HeadRenderer has been in PF since the beginning and it actually quite clever to support `facets` to allow loading order.  Its also vital to ensure scripts are loaded properly in order so PrimeFaces does not break.

**Issues with current implementation:**
- https://github.com/primefaces/primefaces/issues/12855 scripts are loaded as `links` and not `resources` so duplicates are being added to the DOM in some scenarios
- Because they are not resources they are not picked up by OmniFaces CombinedResourceHandler.  BalusC wrote about this years ago: https://github.com/omnifaces/omnifaces/wiki/Combine-hardcoded-PrimeFaces-resources-using-CombinedResourceHandler
- PFE added the code based on BalusC article to make it work but its a HACK!: https://www.primefaces.org/showcase-ext/sections/utils/combinedResourceHandler.jsf

cc @stolp @blutorange 

### Describe the solution you would like

Currently here is the ordered output of PrimeFaces and has been for years with a mixture of `link` and `resource` dependencies.  The links were used to ensure the proper order in the `<head>` .

**DatePicker Example from Showcase:**
```
link: theme.css
link: primeicons/primeicons.css
resource: css/primeflex3.css
resource: css/flags/flags.css
resource: components.css
resource: jquery/jquery.js
resource: jquery/jquery-plugins.js
resource: core.js
resource: components.js
resource: inputmask/inputmask.js
resource: datepicker/datepicker.js
resource: touch/touchswipe.js
resource: css/layout/layout.css
link: moment/moment.js
link: validation/validation.bv.js
link: locales/locale-en.js
```

I would like the HeadRenderer to render `resource` not `links` to allow OmniFaces to work properly as well as follow Faces standards.

**Expected Outcome:**
```
resource: theme.css
resource: primeicons/primeicons.css
resource: css/primeflex3.css
resource: css/flags/flags.css
resource: components.css
resource: jquery/jquery.js
resource: jquery/jquery-plugins.js
resource: core.js
resource: components.js
resource: inputmask/inputmask.js
resource: datepicker/datepicker.js
resource: touch/touchswipe.js
resource: css/layout/layout.css
resource: moment/moment.js
resource: validation/validation.bv.js
resource: locales/locale-en.js
```

**Comment by melloware** [comment]
OK I can't get it working with OmniFaces CombinedResourceHanlder but I did prevent duplicates in @blutorange scenario

**Comment by tandraschko** [comment]
Should we apply it then?

**Comment by melloware** [comment]
Yep let me merge

**Comment by tandraschko** [comment]
But why? Whats better then when it doesnt work with omnifaces?

**Comment by melloware** [comment]
It's fixed BlutOrange scenario of duplicate moment.js.  Because it was using a link and not a source so when the component gets added to the tree it was adding moment.js again. I have an integration test for it.

**Comment by melloware** [comment]
If you look at CoreHead003Test it adds a Chart dynamically after initial page load and ensures only chart.js is added and not moment.js again.

**Comment by tandraschko** [comment]
But wasnt it fixes before with isResourceRendered?

**Comment by melloware** [comment]
Scenario 2 was fixed but not scenario 3.
