### ISSUE TITLE
NullPointerException when no selection is supplied in selection mode multi (DataTable)

### ISSUE THREAD

**Issue by Tires** [primefaces/primefaces#1294]
In Class org.primefaces.component.datatable.feature.SelectionFeature.class (primefaces 5.3.5) line 63 the code is:
`
Class<?> clazz = table.getValueExpression("selection").getType(context.getELContext());
`

Would be a good idea to add table.getValueExpression("selection") != null.

**Comment by sudheerj** [comment]
Can you please create PR for this.

**Comment by sudheerj** [comment]
PR created at #1351

**Comment by tandraschko** [comment]
Thanks sudheer!
