### ISSUE TITLE
auto attibute doesn't work in mode="simple" for p:fileUpload

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1295]
I have a p:fileUpload which I want simple mode and auto upload.

I used following libraries:
primefaces-5.3.jar
jsf-api-2.2.10.jar
jsf-impl-2.2.10.jar
JDK 1.8

<p:fileUpload ... mode="simple" skinSimple="true" auto="true" />

**Comment by tandraschko** [comment]
use the search next time, it's a duplicate of #1077

**Comment by JaviRpo** [comment]
sorry, i will search next time
