### ISSUE TITLE
ColorPicker: is not working with p:sidebar

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#12958]
### Describe the bug

Hi, 

as mentioned in the Discord channel, p:sidebar is not working in p:colorPicker.
The Pop Up is not showing correctly.

```
<p:sidebar>
                <p:colorPicker value="#{myBean.color} />
</p:sidebar>
```

The <p:colorPicker is behind the <p:sidebar:

<img width="493" alt="image" src="https://github.com/user-attachments/assets/906ef1c9-d084-4c94-afec-81cc3942a1c9">

It should work like p:dialog

### Expected behavior

Pop Up from color picker is working and showing as expected

### PrimeFaces edition

Community

### PrimeFaces version

14.0.8

### JSF implementation

Mojarra

### JSF version

2.4

### Java version

11

**Comment by melloware** [comment]
Here is a MonkeyPatch if you need this fix now

```js
if (PrimeFaces.widget.ColorPicker) {
  PrimeFaces.widget.ColorPicker.prototyoe.setupDialogSupport = function() {
    var dialog = this.input[0].closest('.ui-dialog, .ui-sidebar');
    if (dialog) {
      this.cfg.parent = PrimeFaces.escapeClientId(dialog.id);
    }
  }
}
```

**Comment by rider87** [comment]
Thanks - I can wait for it.
Will it be deployed in 14.0.9 ?

**Comment by melloware** [comment]
Yep will be in 14.0.9
