### ISSUE TITLE
DatePicker: Introduce a function that allows shortNames to be switched to longNames

### ISSUE THREAD

**Issue by EugenFischer** [primefaces/primefaces#12969]
### Description

There are currently two types of month names (monthNames, monthNamesShort). 
datePicker uses for month selection field and in ‘monthPicker’ mode the monthNamesShort variant by default.

### Describe the solution you would like

it would be nice to have a way to control this behaviour. so that the long texts are used for the month selection and ‘monthPicker’ mode.
![grafik](https://github.com/user-attachments/assets/c70082ca-4594-4c1c-aba7-9e1be225d7d1)
![grafik](https://github.com/user-attachments/assets/6d582188-39a1-40bb-a148-16ffae5e84c5)

**Comment by melloware** [comment]
![image](https://github.com/user-attachments/assets/dd46bf24-2f93-4b89-8cb0-e34c38d31aec)

![image](https://github.com/user-attachments/assets/095bf76c-fa2b-462e-a733-b8886f12b7fb)

Attribute is `showLongMonthNames="true"`
