### ISSUE TITLE
ProgressBar: Align Label Consistently Across PrimeFaces, PrimeNG, and PrimeVue

### ISSUE THREAD

**Issue by mrcasio** [primefaces/primefaces#12963]
### Description

In PrimeFaces, the ProgressBar component currently renders its label outside the ui-progressbar-value container, resulting in a misaligned label. This differs from the behavior in PrimeNG and PrimeVue, where the label is positioned correctly within the progress bar and aligned with the progress value.

This inconsistency leads to visual and functional differences across frameworks and impacts developers working on applications that use multiple Prime products.

### Describe the solution you would like

To achieve alignment with PrimeNG and PrimeVue, render the ui-progressbar-label element within the ui-progressbar-value container in the DOM. This structural change will ensure the label is displayed consistently across all Prime frameworks, centered within the progress bar and aligned with the progress value.

### Additional context

The current behavior of PrimeFaces places the ui-progressbar-label outside the ui-progressbar-value container, as shown in the attached screenshots. The desired behavior can be achieved by rendering the label as a child element of ui-progressbar-value.

Attached are:

Screenshots of the current implementation in PrimeFaces.
A reference screenshot of the desired implementation in PrimeNG/PrimeVue.
The DOM structure showing how the label can be rendered correctly.

![image](https://github.com/user-attachments/assets/1217c3d9-818d-400c-8289-25922f14db8b)

![image](https://github.com/user-attachments/assets/1fae6ba5-30b1-4436-aeac-151d55c5d7b5)

![image](https://github.com/user-attachments/assets/277e102d-c9b1-41b6-8fc1-96ceaf83af3f)

**Comment by melloware** [comment]
I agree we should try and be consistent.

**Comment by melloware** [comment]
![image](https://github.com/user-attachments/assets/a2e7b2e6-4856-4086-ab11-6874b0ee6b5a)

**Comment by kguelzau** [comment]
Any idea how to show 0% on a static progress bar?
Showcase is still a V14? At least the structure is still "old".

**Comment by melloware** [comment]
you can always go here to see the latest 15.0.X showcase: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/misc/progressBar.xhtml

@kguelzau can you open a new ticket I fixed something similar for PrimeReact: https://github.com/primefaces/primereact/pull/4385
