### ISSUE TITLE
TextEditor: has mutation event 'DOMNodeInserted' error when running on Chromium browsers

### ISSUE THREAD

**Issue by mnhnam-axonivy** [primefaces/primefaces#12962]
### Describe the bug

The TextEditor has Javascript error on Chrome  browser when using the mutation event 'DOMNodeInserted'
This JS error appears on Primefaces version 13.0.14 and on your showcase website 14.0.6-SNAPSHOT 

**Reason**
Chromium deprecated mutation events and will remove them
https://developer.chrome.com/blog/mutation-events-deprecation?hl=en

### Reproducer

- Open the [TextEditor showcase](http://www.primefaces.org/showcase/ui/input/textEditor.xhtml?jfwid=70349) with latest Chrome or Edge
- Open the browser's Developer Tool

-> The JS errors appear in the Console
![image](https://github.com/user-attachments/assets/df643b50-ed87-407a-aba9-68b817f137a5)

### Expected behavior

No Javascript error appear

### PrimeFaces edition

Community

### PrimeFaces version

13.0.14, 14.0.6-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

21

### Browser(s)

Chrome 131.0.6778.86 (Official Build) (64-bit), Edge 131.0.2903.70 (Official build) (64-bit)

**Comment by melloware** [comment]
Fixed in 15.0.0 with this upgrade: https://github.com/primefaces/primefaces/issues/11096

This is a bug in QuillJS and only upgrading to the major version fixes it but we don't want to do that on an existing 13 or 14 release so it went into 15.0.0.    If you are a PRO user you can request it backported through your PRO account.

**Comment by mnhnam-axonivy** [comment]
Hi @melloware ,
I reported with the PRO account. We are using PF 13.0.14

**Comment by melloware** [comment]
Excellent!
