### ISSUE TITLE
icon attribute for p:fileUpload

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1296]
it would be good if the component p:fileUpload had the icon attribute, so we can change the default icon in 3 differents button in the component
![image](https://cloud.githubusercontent.com/assets/8562436/14307312/9eb7e124-fb93-11e5-8ee0-c1f289775b82.png)

**Comment by sudheerj** [comment]
You can just override fileupload button style classes.However team will confirm whether it is really needed to implement icon attributes for all buttons.

**Comment by JaviRpo** [comment]
Any solutions about this issue?

**Comment by Rapster** [comment]
Feel free to provide a PR. It's quite simple actually (will involve to update documentation though), but as said @sudheerj, just override style classes

**Comment by Rapster** [comment]
Fixed by this commit d3642cb4616b2c2cfc020b2e67fab279a8bb25a5 but it's only available for advanced mode while it should be possible to do the same with skinSimple
