### ISSUE TITLE
Avoid label "Choose" when we don't define the attribute for p:fileUpload

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1297]
Don't put default label "Choose" when we don't define the attribute for p:fileUpload

If i put the attribute without value, the draw button doesn't have height

![image](https://cloud.githubusercontent.com/assets/8562436/14293746/7e73332e-fb33-11e5-8cf2-a4f5123ddc45.png)

In the imagen there are a button (left) with a fileUpload (right)

**Comment by tandraschko** [comment]
Hmm, what do you mean?

**Comment by JaviRpo** [comment]
p:fileUpload is similar to p:commandButton ( visually ), the difference is in functionality.

In this case, i want to put a p:fileUpload only with a icon without label and I hope that the visual appearance of the 2 components are the same.

So, when i try to put the p:fileUpload component without the label attribute the component draws with a default label "Choose"
![image](https://cloud.githubusercontent.com/assets/8562436/14302217/33e87720-fb64-11e5-9145-391c3f562bba.png)
![image](https://cloud.githubusercontent.com/assets/8562436/14302220/38ee8d90-fb64-11e5-8bd8-c88902a03771.png)
(this is a comparation between a p:commandButton (left) and p:fileUpload (right)

and when i put the attribute label with empty value, the component p:fileUpload draws smaller than p:commandButton
![image](https://cloud.githubusercontent.com/assets/8562436/14302261/99c48584-fb64-11e5-842f-cb5041938ee1.png)
![image](https://cloud.githubusercontent.com/assets/8562436/14302246/7afd3844-fb64-11e5-8fa5-2dd184d212cf.png)

it the same when i use the component in advanced mode for the 3 buttons
![image](https://cloud.githubusercontent.com/assets/8562436/14307340/d2b76c38-fb93-11e5-9f9b-f79b790fe459.png)

**Comment by sudheerj** [comment]
We should have default labels for fileupload component.So if label,uploadLabel,cancelLabel are empty then we should add icon only setting similar to button components.

**Comment by Rapster** [comment]
PR is here #1471

**Comment by subzro** [comment]
There is still a small bug in the choose button.
No matter if the label is null or set by custom value, the upload component will always look like this:
![pf-upload-label-bug](https://cloud.githubusercontent.com/assets/20240792/16518573/e0c1678c-3f83-11e6-870f-696b12fd4c00.png)

I think its because of the wrong styleclass implemented for the fix #1297 in method FileUploadRenderer.encodeChooseButton(..)
`
String buttonClass = isValueBlank(label) ? HTML.BUTTON_ICON_ONLY_BUTTON_CLASS : HTML. BUTTON_LEFT_ICON_CLASS;
`
Fix:
`
String buttonClass = isValueBlank(label) ? HTML.BUTTON_ICON_ONLY_BUTTON_CLASS : HTML.BUTTON_TEXT_ICON_LEFT_BUTTON_CLASS;
`

**Comment by Rapster** [comment]
Not exactly, but I'll fix it for single mode as it is fixed for multiple mode ;)

**Comment by mertsincan** [comment]
Hi @Rapster,
Thanks for the PRs,but, we have some problem with them on Premium Layouts. Please see; http://forum.primefaces.org/viewtopic.php?f=42&t=49470

Therefore, I made some changes on your PR. Thanks again for your PRs.

**Comment by Rapster** [comment]
I made two PRs for this, this one should be enough https://github.com/primefaces/primefaces/pull/1571 I tested it recently and worked fine
