### ISSUE TITLE
primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js missing comma in version 13.0.X

### ISSUE THREAD

**Issue by chadouhoney** [primefaces/primefaces#12977]
### Describe the bug

The locale-el.js file is missing a comma character before the 'messages' declaration. As a result, the file cannot be read properly. 

### PrimeFaces edition

Community

### PrimeFaces version

13.0.x

### JSF implementation

Mojarra

### JSF version

2.0

### Java version

8

**Comment by jepsar** [comment]
If it's only in 13 we cannot do anything about it. Please read https://github.com/primefaces/primefaces?tab=readme-ov-file#community--lts--pro
