### ISSUE TITLE
DataTable: Editable cell with p:selectonemenu not moving focus properly with tab key

### ISSUE THREAD

**Issue by crcatedr** [primefaces/primefaces#12989]
### Describe the bug

When pressing the 'tab' key in an editable datatable, focus is not moving to the next column properly on tab out if the cell contains a `p:selectOneMenu`.

### Expected behavior

Focus will move to the next column when tabbing out of an editable cell containing a `p:selectOneMenu`

### PrimeFaces edition

Community

### PrimeFaces version

14.0.7

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

17

**Comment by melloware** [comment]
Thanks fixing for 14.0.9!
