### ISSUE TITLE
PrimeNG: DataTable scrollable breaks column templates and sortable

### ISSUE THREAD

**Issue by gatapia** [primefaces/primefaces#1298]
If a p-dataTable has scrollable+scrollHeight property then sorting breaks.

If a p-dataTable has scrollable+scrollHeight property then custom templates do not show.

**Comment by sudheerj** [comment]
You have to create primeng issues in primeng project https://github.com/primefaces/primeng/issues

**Comment by mertsincan** [comment]
I think this issue is fixed; https://github.com/primefaces/primeng/issues/162
Next time, please use  https://github.com/primefaces/primeng/issues for primeng issue.
