### ISSUE TITLE
New Signature Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#13]
Create a new component to allow signatures in a form.

**Comment by srbala** [comment]
This is great news...!

Is this component is mobile optimized and can be used under mobile view?

**Comment by cagataycivici** [comment]
Yes

![signature](https://cloud.githubusercontent.com/assets/686247/8992428/148973e2-3707-11e5-8f47-2b611837b16d.jpg)

**Comment by smithh032772** [comment]
Wow wee! :)
