### ISSUE TITLE
Widgets: Dashes instead of underscores in IDs seem to be a breaking change

### ISSUE THREAD

**Issue by Anders142536** [primefaces/primefaces#13001]
### Describe the bug

When upgrading from PrimeFaces 14.0.5 to 14.0.7 our application breaks due to the ID generation now using dashes sometimes instead of underscores.

14.0.5:
![ids with 14 0 5](https://github.com/user-attachments/assets/ff58d347-eb71-4316-94da-7a8e402b02b2)

14.0.7:
![ids with 14 0 7](https://github.com/user-attachments/assets/1fcbc048-56ad-4896-abd6-2972fb081b03)

Every part in our code that tries to select a node based on an ID or css that uses the ID in a selector is now broken.

I believe it was this issue/commit that causes this change: #12768 

I don't really know if this is technically a breaking change on PrimeFace's side or simply a weird way of us using it. Adjusting our codebase to this change is a non trivial migration. Maybe others have the same issue? What was the specific reason for this change?

### PrimeFaces edition

Community

### PrimeFaces version

14.0.7

### JSF implementation

Mojarra

### JSF version

4.0.1

### Java version

17

**Comment by melloware** [comment]
@Anders142536 can you provide a reproducer?  See this ticket: https://github.com/primefaces/primefaces/issues/12765

We discussed this was legacy widget behavior and thought it should not be needed anymore?

**Comment by melloware** [comment]
I would like to understand how this is possible and so we can write an Integration test for it.

**Comment by melloware** [comment]
cc @clx-cruis can you comment on this?

**Comment by tandraschko** [comment]
it think it occurs now if you use dashes in the ID like: my-dialog

for users relying on the old way, this is a breaking change

**Comment by tandraschko** [comment]
at least the commit in Widget.java but not in the expression stuff: https://github.com/melloware/primefaces/commit/c3551a1c5995ab1fd2d09ff71396070b325f70e0

**Comment by Anders142536** [comment]
Sorry I couldn't provide a reproducer, there was no time for it at work.

Thanks a lot for fixing this! ❤️

**Comment by melloware** [comment]
14.0.10 is in Maven Central
