### ISSUE TITLE
Build: primefaces-themes does not create sources jar

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#13003]
We've built a custom primefaces theme based on the sass theme internally (just copy everything and modify as we need) and I would like to easily be able to update the base theme, e.g. when we want to use new features/components. I think I could build a somewhat elegant solution if there was a sources .jar published as well.

Right now the source plugin is just getting skipped because `primefaces-themes` is not using a standard maven layout (`src/main/resources`) nor defining a source resources directory:
```
[INFO] --- source:3.3.1:jar-no-fork (attach-sources) @ primefaces-themes ---
[INFO] No sources in project. Archive not created
```

**Comment by melloware** [comment]
Good idea!  I am fixing this now.

**Comment by jungm** [comment]
FYI https://github.com/jungm/primefaces-theme-template

Not really battle tested yet, but something like this is what I had in mind

**Comment by melloware** [comment]
nice!
