### ISSUE TITLE
DataExporter: UINamingContainer not supported

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#13002]
### Describe the bug

`dataExporter` throws the following error when trying to export dataTable rows inside a composite component.

```
jakarta.servlet.ServletException: Component jakarta.faces.component.UINamingContainer not supported. Use DataExporters#register()
```

Please find the reproducer
[primefaces-test.zip](https://github.com/user-attachments/files/18022109/primefaces-test.zip)

I couldn't find much information about `DataExporter` except these two. So I am not sure whether it is a missing feature and I need to write a custom exporter or not.

- https://github.com/primefaces/primefaces/issues/10264
- http://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml

### PrimeFaces edition

Community

### PrimeFaces version

15.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

21

**Comment by aripddev** [comment]
Ok, found it. When using a composite component, the `id` of components inside it is prefixed with the composite component's ID. So, the fully qualified client ID is going to be `sameTable:dataTable1`.

Corrected reproducer
[primefaces-test.zip](https://github.com/user-attachments/files/18022710/primefaces-test.zip)

**Comment by melloware** [comment]
@aripddev is this an issue i see you closed it?

**Comment by aripddev** [comment]
@melloware My mistake. I thought it is a bug or missing feature, but solved it.
