### ISSUE TITLE
FilterMeta: filterValue is ignored in equals/hashcode

### ISSUE THREAD

**Issue by bvfalcon** [primefaces/primefaces#13013]
### Describe the bug

Code change for issue #6219 [excluded](https://github.com/primefaces/primefaces/pull/6223/files#diff-23729d17e405f6d0d1b1474e76789f78f44ea7fd0a7fea532d97a900adee5881) filterValue from FilterMeta.equals and FilterMeta.hashcode. filterValue is an important part of FilterMeta object state and FilterMeta class is a part of API and can be used externally. Client code will be unpleasantly surprised to find, that FilterMeta with different filterValue are equals and have the same hashcode.

Example of such surprise is this [demo project](https://github.com/bvfalcon/PrimeFaces-FilterMeta-test). 

### PrimeFaces edition

None

### PrimeFaces version

8.0.4 and later

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment]
I think in case of PF only the filterValue can change during requests, everything else is "static". Therefor its propbaly correct from our view.

**Comment by bvfalcon** [comment]
> in case of PF only the filterValue can change

Yes, this is so. But FilterMeta is a part of API and (as demo project is shown) can be read (without fields modification) by client code. For client code [incorrect](https://ahdak.github.io/blog/effective-java-part-2/) implementation can be a problem.

**Comment by tandraschko** [comment]
yeah but you should not blindly use such a internal API
i fear we break internals when we change this

@Rapster WDYT?

**Comment by bvfalcon** [comment]
This API is [not internal](https://github.com/primefaces/primefaces/blob/e5a76b508d0df8a7d31a6390a364ced74461e9a7/primefaces/src/main/resources/META-INF/primefaces.taglib.xml#L9021-L9027). And that does mean blindly use equals? I don't understant, how two objects FilterMeta[filterValue="one value"] and FilterMeta[filterValue="another value"] can be equal? Something wrong with such equals.

**Comment by tandraschko** [comment]
i depends on the view
if you implement equals in entities, mostly only the ID is compared
this case is similar

**Comment by melloware** [comment]
I can definitely see the argument both ways?  I will submit a draft PR just so we can see if any Integration Tests break.  Not necessarily going to make the fix but just so we have more info.

**Comment by jansohn** [comment]
I also got bitten by this when I tried to implement a caching JPA lazy data model.

Reproducer: https://github.com/jansohn/primefaces-test/tree/caching-jpa-lazy

1. Clone reproducer
2. Checkout branch caching-jpa-lazy
3. Run with `mvn clean jetty:run`
4. Open http://localhost:8080/ in browser
5. Filter "String Col" with value "New"
6. Continue filter value with "New O"
7. Filtered objects stay the same as the FilterMeta.equals method returns `true` because it ignores the `filterValue`

To fix this I would need to implement my own equals method for `filterBy`, e.g. something like this:
```java
    private boolean equalsFilterBy(Map<String, FilterMeta> filterByA, Map<String, FilterMeta> filterByB) {
        if (filterByA == filterByB) { return true; }

        if (filterByA.size() != filterByB.size()) { return false; }

        try {
            for (Entry<String, FilterMeta> e : filterByA.entrySet()) {
                String key = e.getKey();
                FilterMeta value = e.getValue();
                if (value == null) {
                    if (!(filterByB.get(key) == null && filterByB.containsKey(key))) { return false; }
                } else {
                    FilterMeta otherValue = filterByB.get(key);
                    if (!value.equals(otherValue)) { return false; }

                    // FilterMeta currently does not check filterValue in its equals method...
                    if (!Objects.equals(value.getFilterValue(), otherValue.getFilterValue())) { return false; }
                }
            }
        } catch (ClassCastException | NullPointerException unused) {
            return false;
        }

        return true;
    }
```
