### ISSUE TITLE
Datepicker: Ajax is not fired on blur

### ISSUE THREAD

**Issue by AntiBastiPasti** [primefaces/primefaces#13012]
### Describe the bug

To reproduce the bug, use the testapp and enter a date and exit the input field.  

### Reproducer

[Archive.zip](https://github.com/user-attachments/files/18034490/Archive.zip)

### Expected behavior

Normally, after leaving the input field, the values should be processed and a message should be displayed.

### PrimeFaces edition

Community

### PrimeFaces version

15.0.0-RC1

### JSF implementation

All

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
`dateSelect` is only when you pick a value you from the popup.  You want the `change` event.

```xml
<p:ajax event="change" update="msgs"/>
```

Now it works as you expect.

**Comment by AntiBastiPasti** [comment]
@melloware Sorry, I was in a hurry, my example was wrong. I checked your solution in my project and I still have the problem. Seems like its related to the mask attribute in the datepicker component. We use it like this: 

```
            <p:datePicker id="event" value="#{testView.date}"
                          mask="99.99.9999" 
                          pattern="dd.MM.yyyy">
                <p:ajax event="change" update="msgs"/>
            </p:datePicker>
```

The "blur" event is not handled anymore...

**Comment by melloware** [comment]
Yep in your example you were not using Mask.  See this for a workaround and a cause of your issue: https://github.com/primefaces/primefaces/issues/12754

**Comment by melloware** [comment]
PR submitted...Finally got to the bottom of this. We need to Apply Mask and remove its "blur" before we call `Primefaces.skinInput` which adds the proper blur.

**Comment by melloware** [comment]
14.0.10 is out so you should be able to remove your MonkeyPatch
