### ISSUE TITLE
Showcase: CRUD Demo filtering and deleting many lines doesn't work

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#13026]
### Describe the bug

Go to https://www.primefaces.org/showcase/ui/data/datatable/crud.xhtml

- Filter the list : select "Gaming Set" for example. There must be many lines in the selection. Otherwise use a different filter.

- Select all the lines : the delete button displays : "1 product selected". This is wrong.

- Click on the delete button : only 1 row disappears

Other problem appears if you activate the selection with checkboxes  with :
`<p:column selectionBox="true" selectionMode="multiple" exportable="false">`

- Filter the list with some name
- Click the checkbox to selected all the lines : the delete button displays "100 products selected". (If you click the button all the rows disappear)

### Expected behavior

One must be able to delete only the lines that match some criteria.

### PrimeFaces edition

None

### PrimeFaces version

14.0.6-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Was just a bad rowKey was `rowKey="#{product.id}"` should have been `rowKey="#{product.code}"

**Comment by ritonglue** [comment]
I see Product#equals was based on the field "code".
They are other places that might need to be fixed:

- selection.xhtml
- expansion.xhtml
- contextMenu.xhtml

**Comment by melloware** [comment]
i will check. If you want to see a working version: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/crud.xhtml

**Comment by melloware** [comment]
Looks like its only that one because it uses getClonedProducts which changes its code to be unique.

```
public List<Product> getClonedProducts(int size) {
        List<Product> results = new ArrayList<>();
        List<Product> originals = getProducts(size);
        for (Product original : originals) {
            results.add(original.clone());
        }

        // make sure to have unique codes
        for (Product product : results) {
            product.setCode(UUID.randomUUID().toString().replace("-", "").substring(0, 8));
        }

        return results;
    }
```

**Comment by melloware** [comment]
I made the fixes in the others anyway even though the ID was ok to use in those examples may as well make it consistent
