### ISSUE TITLE
Improve label text on selectCheckboxMenu

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1302]
When user selects two or more items, they are displayed on label of selectCheckboxMenu.

Exp;

```
<p:selectCheckboxMenu style="max-width:200px;" .. />
```

Screenshot;
![test](https://cloud.githubusercontent.com/assets/11868120/14318751/0da79e20-fc17-11e5-9264-fd0a4c47859e.PNG)

**Comment by cnsgithub** [comment]
Hi, Can this be disabled to get the old behaviour back / disable this by a property?. When selecting big (and many items) it messes up the layout.

An further example when this is not desired would be when the selection are just numbers or values, you have multiple of them, then it's no longer possible to see what selection it is for

**Comment by mertsincan** [comment]
Thanks for the comment. Fixed for 5.3.12 and 6.0; https://github.com/primefaces/primefaces/issues/1356
