### ISSUE TITLE
oncomplete not fired closing dialog when using p:commandLink

### ISSUE THREAD

**Issue by alberto-marin-garcia** [primefaces/primefaces#1304]
JBoss EAP 6.4.5 using primefaces 5.3.9 / 5.3.10

when closing dialog a javascript error is fired and the functions in "oncomplete" are NOT executed in xhtml page :

```
<ui:define name="jsFunc">
/* <![CDATA[ */
function hideTableHeader(){
$("#form\\:dataTableA_head").hide();
$("#form\\:dataTableB_head").hide();
}
/* ]]> */
</ui:define>

<p:commandLink actionListener="#{managedBean.editExpedition()}" >
<p:ajax
event="dialogReturn"
update=":form:dataTableB,:form:dataTableA"
listener="#{managedBean.reloadExpedition()}"
oncomplete="alert('do something');hideTableHeader();" />
</p:commandLink >
```

inside managedBean :

public void editExpedition()
{
//put params needed for opening dialog
RequestContext.getCurrentInstance().openDialog(......);
}

public void reloadExpedition()
{
//reload some data related to Expedition
}

when closing the modal dialog the alert is shown but hideTableHeader javascript function is NOT found the javascript error is "Uncaught ReferenceError: hideTableHeader is not defined"

inside primefaces.js there is a call complete: function(w, i) {
if (e.oncomplete) {
e.oncomplete.call(this, w, i, w.pfArgs)
}

(function(ext) {
this.PrimeFaces.ab({
s: "form:dataTableA:0:j_idt682",
e: "dialogReturn",
p: "form:dataTableA:0:j_idt682",
u: "form:dataTableB form:dataTableA",
onco: function(xhr, status, args) {
alert('do something');
hideTableHeader();
;
}
}, ext);
;
}

if <p:commandLink is changed with <p:commandButton then on complete javascript functions are called as expected ( in this case the alert is shown an hideTableHeader javascript funciton is executed )

**Comment by mertsincan** [comment]
I'll review and get back to you.
