### ISSUE TITLE
Forum down / offline

### ISSUE THREAD

**Issue by jansohn** [primefaces/primefaces#13048]
Just wanted to ask real quick what happened to the PrimeFaces forum as I'm getting 404 when accessing it: https://forum.primefaces.org/

**Comment by melloware** [comment]
@jansohn PrimeTek has been under DDOS attacks recently and has been shutting down old servers.

**Comment by melloware** [comment]
You should use the new GitHub Forums if you have questions: https://github.com/orgs/primefaces/discussions/categories/primefaces

**Comment by jansohn** [comment]
So all the information from the forum is lost?

**Comment by melloware** [comment]
i would email PrimeTek. I am sure all the info is there in a MySQL database its just the forum has been shut down for now.

**Comment by stolp** [comment]
I can only hope, that PrimeTek will be restoring the forum. It would be a crying shame if all this information would be lost.
