### ISSUE TITLE
DatePicker: Floating Label issue

### ISSUE THREAD

**Issue by Teutron-flo** [primefaces/primefaces#13059]
### Describe the bug

Hi all,

I performed some tests with the latest showcase version runing on 15.0.0-RC1.

The following combination of field and options, doesn't work:

`<div class="field">
	<span class="ui-float-label">
		<p:datePicker mask="true"
		pattern="dd.MM.yyyy" showIcon="true" showOnFocus="false" />
		<p:outputLabel for="@previous" value="Datepicker" />
	</span>
</div>`

First issue:
1. Fresh page, click into the input field
![image](https://github.com/user-attachments/assets/78cada8d-dc36-4512-8306-10f5cd98af9f)

2. Fill in your date
![image](https://github.com/user-attachments/assets/07126fc5-a52e-40ac-be5a-94934a42d8b4)

3. Click outside

4. Label goes back into the field
![image](https://github.com/user-attachments/assets/ccf9f350-c2d9-4ee0-8857-0fe494d6e2a9)

Secound issue:
1. Fresh page, click into the input field
![image](https://github.com/user-attachments/assets/78cada8d-dc36-4512-8306-10f5cd98af9f)

2. Click outside

3. Mask value still visiable + Label goes back into the field
![image](https://github.com/user-attachments/assets/b337c6c9-7917-490b-9c11-49260a2a92bf)

BR
Florian

### PrimeFaces edition

None

### PrimeFaces version

15.0.0-RC1

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
i don't think its designed to work with `mask="true"` with float label because InputMask is controlling the text.  Does it work without `mask`?

**Comment by Teutron-flo** [comment]
@melloware, this secenario is working fine with primeface V13. Thats why I'm testing it here, as part the regression test for my application. 

But, back to your question with mask="false" it works

**Comment by melloware** [comment]
good catch

**Comment by melloware** [comment]
if you want to see both in action: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/misc/floatLabel.xhtml

**Comment by Teutron-flo** [comment]
many thanks for the quick fix here! I want to test in the next days some other major topics for my application with 15.0 on the showcase. Lets see if I have more findings :)

**Comment by melloware** [comment]
Yes please report any other 15.0.0 findings!
