### ISSUE TITLE
PrimeFaces Showcase DragDrop DataView

### ISSUE THREAD

**Issue by tedkspradley** [primefaces/primefaces#13057]
### Describe the bug

Re: PrimeFaces Showcase DragDrop DataView at https://www.primefaces.org/showcase/ui/dnd/dataView.xhtml 

Attempt to drag 
<p:draggable for="pnl" revert="true" handle=".ui-panel-titlebar" stack=".ui-panel"/> item to 

<p:droppable for="selectedProducts" tolerance="pointer" activeStyleClass="ui-state-highlight"
                     datasource="availableProducts" onDrop="handleDrop">
            <p:ajax listener="#{dndProductsView.onProductDrop}" update="dropArea availableProducts"/>
</p:droppable>

does not result in the <p:outputPanel id="dropArea"> being re-rendered with 

<p:dataTable id="selectedProductsTable" var="product" value="#{dndProductsView.droppedProducts}" >

containing the list of products. 

Attempted with Chrome, Firefox, Safari browsers.

### PrimeFaces edition

None

### PrimeFaces version

v14.0.6-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
i just tested it it works fine for me?

**Comment by tedkspradley** [comment]
Hmm. I checked again on all three browsers. Same non-functionality. I'm happy to record my screen? It's certainly possible I'm doing something wrong but I've used Primefaces for years and am fairly familiar.

**Comment by tedkspradley** [comment]
https://github.com/user-attachments/assets/fc39c9ad-8661-4d2b-aa08-a2e59334070f

Chrome Screen recording

**Comment by melloware** [comment]
your grabbing the image you have to grab the header because `handle=".ui-panel-titlebar"`

**Comment by tedkspradley** [comment]
SMH ... Thank you for the quick response. Apologies for the unnecessary report. Although learned a valuable lesson about what my user's expectation may be. Thanks again.
