### ISSUE TITLE
p:editor behavior is different in IE 11 and chrome when removing content

### ISSUE THREAD

**Issue by vasudevtyagi** [primefaces/primefaces#1305]
Hi,

I am using Primefaces 5.2.5. I am using p:editor in datatable. It is having a mandatory validation requirement and required flag is set as true. But we are facing a problem in IE 11 in specific scenario.
Once user has entered text in the editor and the entered text is removed using backspace, in IE 11 following source is still available "p br p" due to which required vaildation fails and required message does not appears. Please see the images for source below.
But when same is tried in chrome it was working fine.
Please suggest how to resolve this.
Thanks in Advance
Vasu Tyagi
![image](https://cloud.githubusercontent.com/assets/18325359/14346113/4ef6a620-fcce-11e5-9fb6-2d9fac8e22b1.png)

**Comment by tandraschko** [comment]
Does the same occur in the native CLEditor? If yes, please create a issue on their side.

**Comment by vasudevtyagi** [comment]
Yes, the behavior is same in http://premiumsoftware.net/cleditor/.

**Comment by tandraschko** [comment]
So please create a issue on their side if they can fix it.

**Comment by tandraschko** [comment]
Will close it for now. We have a new editor and this is something, that should be fixed directly by CLEditor.
