### ISSUE TITLE
SelectOneMenu: Empty value is displayed with &nbsp;

### ISSUE THREAD

**Issue by Teutron-flo** [primefaces/primefaces#13058]
### Describe the bug

Hi all,

I performed some tests with the latest showcase version runing on 15.0.0-RC1 and found an display issue inside the SelectOneMenu element in combination with the floating label:

http://localhost:8080/showcase/ui/misc/floatLabel.xhtml

![image](https://github.com/user-attachments/assets/93540e3f-ccee-4d2c-8555-ac02ef4486e2)

The empty / null value is correct display when selected (the label moves into the field)
but inside the drop down menu it is displayed as "&nbsp;".

BR
Florian

### PrimeFaces edition

None

### PrimeFaces version

15.0.0-RC1

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
good catch
