### ISSUE TITLE
Picklist: source data with html characters

### ISSUE THREAD

**Issue by YogeshMKumbhar** [primefaces/primefaces#13061]
### Describe the bug

In `PickList` source has certain html charachers such as & / \ when transfering from source to target it gives error
`j_idt235:pickList: An error occurred when processing your submitted information`.
This error is even before `p:ajax event="transfer"` event called. In my code I've formatted target string within transfer event.
This error is in version 14.0.6 and not in version 12.0.

### Reproducer

Add `Picklist` , `p:growl` in form 
source string must contain charachers / or \ or &
Try to shift from source to target
It will throw exception which will update `p:growl`

### Expected behavior

either data should be transfered as it is including escaped charachters as present in source or it must not throw and exception.
you can check/compare with version 12.0.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.6

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21.0

### Browser(s)

chrome, firefox

**Comment by melloware** [comment]
@YogeshMKumbhar its working for me with `&`..

![image](https://github.com/user-attachments/assets/90f6332f-9205-4239-bd5c-05fe72bb5122)

**Comment by melloware** [comment]
its even working on the PF showcase if you pick "Antigua & Barbuda"

**Comment by YogeshMKumbhar** [comment]
My html file
`<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:form>
            <p:growl id="messages" />
            <p:pickList value="#{pickListCDI.prizeAcNos}" var="data"
                        itemLabel="#{data}" itemValue="#{data}" >
                <p:ajax event="transfer" update="messages" />
            </p:pickList>
        </h:form>
    </h:body>
</html>`

my CDI bean
`@Named(value = "pickListCDI")
@ViewScoped
public class PickListCDI implements Serializable {

    private DualListModel<String> PrizeAcNos;

    /**
     * Creates a new instance of PickListCDI
     */
    public PickListCDI() {
    }

    @PostConstruct
    public void init() {
        ArrayList<String> source = new ArrayList<>();
        source.add("28 - सौ शोभना इंगळे\n"
                + "'श्री साई छाया' गणेश नगर,\n"
                + "44 / 5, नवसह्याद्री सोसायटी,\n"
                + "कर्वे नगर, पुणे 411 005. ");

        PrizeAcNos = new DualListModel<>();
        PrizeAcNos.getSource().addAll(source);
    }

    /**
     * @return the PrizeAcNos
     */
    public DualListModel<String> getPrizeAcNos() {
        return PrizeAcNos;
    }

    /**
     * @param PrizeAcNos the PrizeAcNos to set
     */
    public void setPrizeAcNos(DualListModel<String> PrizeAcNos) {
        this.PrizeAcNos = PrizeAcNos;
    }
`

**Comment by tandraschko** [comment]
please provide a primefaces-test project

**Comment by YogeshMKumbhar** [comment]
[https://github.com/YogeshMKumbhar/PickList](url)

**Comment by tandraschko** [comment]
the link doesnt exist

**Comment by YogeshMKumbhar** [comment]
https://github.com/YogeshMKumbhar/PickList
this link is working

**Comment by melloware** [comment]
OK here is a runnable reproducer:
[pf-13061.zip](https://github.com/user-attachments/files/18126796/pf-13061.zip)

**Comment by melloware** [comment]
Its definitely an encoding issue. When I add debug.

```java
 // Check if target item exists in source list
            if (!oldSource.contains(targetItem) && !oldTarget.contains(targetItem)) {
                System.out.println("targetItem: " + targetItem);
                System.out.println("oldSource: " + oldSource);
                System.out.println("oldTarget: " + oldTarget);
                FacesMessage message = MessageFactory.getFacesMessage(facesContext, UPDATE_MESSAGE_ID, FacesMessage.SEVERITY_ERROR, label);
                facesContext.addMessage(clientId, message);
                setValid(false);
                break;
            }
```

I get this result:

```
targetItem: 28 - ?? ????? ?????&#39;???? ??? ????&#39; ???? ???,44 &#x2F; 5, ??????????? ???????,????? ???, ???? 411 005.
oldSource: [28 - ?? ????? ?????'???? ??? ????' ???? ???,44 / 5, ??????????? ???????,????? ???, ???? 411 005. ]
oldTarget: []
```

you can see the item submitted is different than what is stored in the server side source.

**Comment by YogeshMKumbhar** [comment]
But It works fine if I use Primefaces 12.0.

**Comment by melloware** [comment]
ok from the documentation: https://primefaces.github.io/primefaces/14_0_0/#/components/picklist?id=attributes

We close a security hole with HTML entities.

> escapeValue | true | Boolean | Defines if values of the component are escaped or not.

So if you add `escapeValue="false"` to your picklist it works and escapes the HTML but as with all JSF entities should not be escaped unless user specifies so.

I don't know how this was working in 12.0 for you as this property has been there since 8.0: https://github.com/primefaces/primefaces/issues/4807
