### ISSUE TITLE
p:media not working when using StreamedContent

### ISSUE THREAD

**Issue by Koeppes** [primefaces/primefaces#13063]
### Describe the bug

I am trying to use Primefaces p:media component in Version 13.0.5 to display pdf´s loaded from database.

This is my BackingBean-getter and it´s definetly being invoked and building the StreamedContent with the provided byte[] from the database:

public StreamedContent getMedia() {
    StreamedContent result;
    if (this.selectedRow == null) {
        return null;
    }
    result = DefaultStreamedContent.builder()
            .contentType("application/pdf")
            .stream(() -> {
                try {
                    return new ByteArrayInputStream(this.getSelectedDokument().getDocumentAsByte());
                } catch (Exception e) {
                    e.printStackTrace();
                    return null;
                }
            })
            .build();
    return result;
}

XHML:

         <p:media value="#{controller.getMedia()}" width="100%" height="590px" id="media" cache="false"
           player="pdf"/>

Bean is SessionScoped.

When using a static path to the pdf-File it´s working fine.
Any ideas?

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### Theme

Avalon

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

All

**Comment by tandraschko** [comment]
added a sample -> works fine

if you dont provide a failing primefaces-test reproducer, we cant help.
