### ISSUE TITLE
TextEditor: Font Size Dropdown not language-aware

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#13074]
### Description

![grafik](https://github.com/user-attachments/assets/ef34e0ae-20bd-48d4-8e70-1449d7a95d8d)

The font size dropdown has only english size options (small, normal, large, huge).

### Describe the solution you would like

It would be useful if the component was language-aware

(Or is there already a way to customise the label text which we don't know yet?)

**Comment by melloware** [comment]
it looks like Localization is a huge miss in QuillJS: https://quilljs.com/docs/configuration

See: https://github.com/slab/quill/issues/4331

**Comment by melloware** [comment]
Going to close this here please go upvote the ticket at QuillJS.

You could also switch to PFE SunEditor: https://www.primefaces.org/showcase-ext/sections/sunEditor/basicUsage.jsf which is locale aware

**Comment by RohdeSchwarz-SDC** [comment]
Thanks for this advice!
