### ISSUE TITLE
Core: Validation error in primefaces.taglib.xml

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#13078]
### Describe the bug

The primefaces.taglib.xml in the 15.0.0-SNAPSHOT contains a small validation error starting in line 113:

Instead of:

    <tag>
        <tag-name>validateFile</tag-name>
        <description>
            <![CDATA[p:validateFile is a validator which can be used to validate single and mulitple files, either of p:fileUpload or h:inputFile.]]>
        </description>

it should read:

    <tag>
        <description>
            <![CDATA[p:validateFile is a validator which can be used to validate single and mulitple files, either of p:fileUpload or h:inputFile.]]>
        </description>
        <tag-name>validateFile</tag-name>

(put description before tag). 

### PrimeFaces edition

Community

### PrimeFaces version

15.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3-next

### Java version

21

**Comment by melloware** [comment]
Thanks!
