### ISSUE TITLE
Schedule: Cannot read properties of undefined with 15.0.0-RC1

### ISSUE THREAD

**Issue by LouisCollet** [primefaces/primefaces#13075]
### Describe the bug

It's working with version 14.0.9
platform : windows 11, wildfly34, JDK 23
I get following error : 
![image](https://github.com/user-attachments/assets/b2de1673-b7e8-479f-9fbf-8281deb30a34)  
Uncaught TypeError: Cannot read properties of undefined (reading 'previous')
    at d.configureLocale (schedule.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:18:31)
    at d.init (schedule.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:16:65)
    at d.init (core.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:118:383)
    at new d (core.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:118:157)
    at Object.createWidget (core.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:27:402)
    at Object.cw (core.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:27:25)
    at HTMLDocument.<anonymous> (schedule_pro.xhtml:72:486)
    at l (jquery.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:2:24969)
    at c (jquery.js.xhtml?ln=primefaces&v=15.0.0-RC1&e=15.0.0-RC1:2:25288)

any idee of the root cause ?
Thanks and have a nice day !

### Reproducer

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<ui:composition
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="jakarta.faces.core"
      xmlns:h="jakarta.faces.html"
      xmlns:ui="jakarta.faces.facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:of="http://omnifaces.org/functions"
      xmlns:c="jakarta.tags.core"
      template="templates/masterTemplate.xhtml">

 <div class="card">
<ui:define name="title">Schedule Pro Page</ui:define>
<ui:define name="content">
<h:graphicImage name="images/tarif1.jpg" alt="image missing :tarif1.jpg" style="float: left;"></h:graphicImage>
<h:graphicImage name="images/tarif2.jpg" alt="image missing :tarif2.jpg" style="float: right;"></h:graphicImage>

 
<h:form id="schedule_form" >
<ui:include src="include/include_summary_pro.xhtml"/>

<p:panel id="panelId"
         header="Settings"
         footer="settings footer" >
    <f:facet name="header">
        <h1>#{msg['message.lesson']} </h1>
    </f:facet>
    <c:set var="idplayer" value="#{courseC.player.idplayer}"/>
    <p:outputPanel id="schedulePanel"
                   
                   style="font-size:0.8rem;">
        <p:schedule id="schedule"
                    value="#{schedulerC.scheduleModel}"
                    widgetVar="myschedule"
                    locale="#{languageC.locale}"
                    timeFormat="HH:mm"
                    height="auto"
                    slotDuration="00:30:00"
                    slotLabelInterval="01:00"
                    tooltip="this is the tooltip, Louis"
                    minTime="09:00:00"
                    maxTime="19:00:00"
                    styleClass="ui-custompanelgrid"
                    view="timeGridWeek"
                    extender="initSchedule"
                    clientTimeZone="Europe/Brussels"
                    timeZone="Europe/Brussels" >
            <p:ajax event="dateSelect" 
                    listener="#{schedulerC.dateSelect}"
                    update=":schedule_form:panelId,growl-msg,messages, panelId"
                    oncomplete="PF('eventDialog').show();"/>
            <p:ajax event="eventSelect" 
                    listener="#{schedulerC.eventSelect}"
                    update=":schedule_form:panelId,growl-msg,messages,panelId"
                    oncomplete="PF('eventDialog').show();"/>
            <p:ajax event="eventMove"
                    listener="#{schedulerC.moveLesson}"
                    update=":schedule_form:panelId,growl-msg,messages,panelId"/>
  
        </p:schedule>
    </p:outputPanel>

 <script type="text/javascript">
function initSchedule() {
        this.cfg.options.buttonText = { today : 'Current Date'};
 } // endInitSchedule

</script>

  <p:staticMessage severity="info" summary="Summary INFO" detail="staticMessage detail Content" style="width: 100%"/>
  
        <p:dialog id="dialog1"
                  widgetVar="eventDialog" 
                  header="Lesson Details"
                  footer="footer text"
                  width="80%"
                  modal="true"
                  minimizable="true"
                  maximizable="true"
                  showEffect="fade" 
                  responsive="true"
                  hideEffect="fade"  >
        <p:panelGrid id="eventDetails"
                     layout="flex"
                     columns="2"
                     columnClasses="col1Flex, col2Flex"
                     style="font-size:0.8rem; width:50%" >
                <p:outputLabel for="@next" value="Title" styleClass="p-text-bold"/>
                <p:inputText id="titleEvent" 
                             value="#{schedulerC.scheduleEvent.title}"
                             required="true"
                             placeholder="Please complete the title" />
                <p:outputLabel for="@next" value="Description" styleClass="p-text-bold"/>
                <h:outputText id="descriptionEvent" 
                              value="#{schedulerC.scheduleEvent.description}"/>
                
                <p:outputLabel for="@next" value="From" styleClass="p-text-bold"/>
                <p:datePicker id="dateStart"
                              value="#{schedulerC.scheduleEvent.startDate}"
                              pattern="dd/MM/yyyy"
                              showTime="true"
                              appendTo="@(body)"
                              mindate="#{utilsC.localTime(9,00)}"
                              maxdate="#{utilsC.localTime(18,30)}" 
                              timeInput="false"
                              stepMinute="30" />

                <p:outputLabel for="@next" value="To" styleClass="p-text-bold"/>
                <p:datePicker id="dateEnd"
                              value="#{schedulerC.scheduleEvent.endDate}"
                              pattern="dd/MM/yyyy"
                              showTime="true"
                              appendTo="@(body)"
                              mindate="#{utilsC.localTime(9,30)}"
                              maxdate="#{utilsC.localTime(19,00)}" 
                              timeInput="false"
                              stepMinute="30" />

                <p:outputLabel for="@next" value="All Day" styleClass="p-text-bold" />
                <h:selectBooleanCheckbox id="allDay"
                                         value="#{schedulerC.scheduleEvent.allDay}"
                                         disabled="#{schedulerC.isNotProfessional()}"/>
        </p:panelGrid>
            

            
            
             <f:facet name="footer"> 
                <p:commandButton id="createButton" 
                                 icon="pi pi-check"
                                 value="Réservation Leçon" 
                                 process="@form"
                                 action="#{schedulerC.createLesson()}"
                                 update="panelId,growl-msg,messages"
                                 immediate="false"
                                 ajax="false"
                                 style="float: left;"
                                 oncomplete="PF('myschedule').update();PF('eventDialog').hide();"/>
                <p:commandButton id="deleteButton"
                                 icon="pi pi-times"
                                 value="Annulation leçon"
                                 action="#{schedulerC.deleteLesson(idplayer)}"
                                 update="panelId,growl-msg,messages"
                                 style="float: right;"
                                 ajax="false"
                                 oncomplete="PF('myschedule').update();PF('eventDialog').hide();"/>
              </f:facet>
             <p:contextMenu for="schedule">
               <p:menuitem value="Annuler cette leçon"
                           update="messages, growl-msg"
                           action="#{schedulerC.deleteLesson(idplayer)}"
                           oncomplete="PF('myschedule').update();PF('eventDialog').hide();"/>
            </p:contextMenu>
        </p:dialog>
  
      <f:facet name="footer">
           <p:commandButton value="#{msg['payment.selected']}"
                         id="commandButtonPayment"
                         ajax="false"
                         update="growl-msg"
                         immediate="false"
                         style="float: right;"
                         icon="pi pi-credit-card"
                         action="#{courseC.manageLesson()}" >
           </p:commandButton>
    </f:facet>
  </p:panel>
</h:form>
</ui:define>
 </div>
</ui:composition>

### PrimeFaces edition

Community

### PrimeFaces version

15.0.0-RC1

### Theme

own theme.css based on arya

### JSF implementation

Mojarra

### JSF version

4.0.7

### Java version

JDK23

**Comment by melloware** [comment]
Thanks for reporting I will take a look.

**Comment by melloware** [comment]
Hmm its working here in 15.0.0: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/schedule/localization.xhtml?jfwid=1d1d9

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
@LouisCollet it looks like you are using an older locale which is missing labels?

**Comment by melloware** [comment]
HEre are the locale labels schedule uses: https://github.com/primefaces/primefaces/blob/45df324306577bdea1fc94dc401e6bcc275b2db2/primefaces/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L104-L129

And here is an example locale file complete:
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js

**Comment by melloware** [comment]
you can go here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/schedule/basic.xhtml?jfwid=8ce93

Switch locales to see it in Action:

![image](https://github.com/user-attachments/assets/1b94a75e-5bc3-4b9d-bc6e-822713247e6d)

**Comment by LouisCollet** [comment]
Thanks !

I will have a try and will keep you informed

**Comment by LouisCollet** [comment]
Dear,

You are a genius : it’s working like a charm !

Should I close the issue ?

Kind regards,

Louis

**Comment by melloware** [comment]
Closed!
