### ISSUE TITLE
Dynamic content streaming fails inside composite and JSTL c:set

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#13086]
https://github.com/Koeppes/primefaces-test/

```
        <h:form id="frmTest">
            <p:commandButton value="Show Print Dialog Dynamic"
                             action="#{testView.showPrintDialogDynamic}" update="@form"></p:commandButton>
            <div class="card">
                <pgrid:dialogPrintDokumentDynamic widgetVar="calendarPrintDialogDynamicWV"
                                                  printBean="#{testView}"
                                                  id="calendarPrintDialogDynamic"/>
            </div>
        </h:form>
```

```
    <composite:interface>
        <composite:attribute name="printBean" required="true"/>
        <composite:attribute name="widgetVar" required="true" />
    </composite:interface>
    <composite:implementation>
        <c:set var="printer" value="#{printerBean}"/>
        <p:dialog header="Print" id="printDlg" widgetVar="#{cc.attrs.widgetVar}"dynamic="true">
            <p:media value="#{printerBean.getGraphicText()}" width="100%" height="590px" id="media" cache="false"
                     player="pdf"/>
        </p:dialog>
    </composite:implementation>
```

**Comment by tandraschko** [comment]
CC @Koeppes

**Comment by tandraschko** [comment]
there are actually 2 things we just are not supported and never will:
1) using JSTL (c:set)
2) using a method-expression 

so actually after chance `#{printerBean.getGraphicText()}` to `#{cc.attrs.printBean.graphicText}` - it should actually work in a first view

**Comment by tandraschko** [comment]
the following works:

```
                <pgrid:dialogPrintDokumentDynamic widgetVar="calendarPrintDialogDynamicWV"
                                                  id="calendarPrintDialogDynamic"
                                                  streamedContent="#{testView.graphicText}"/>```

```
    <composite:interface>
        <composite:attribute name="widgetVar" required="true" />
        <composite:attribute name="streamedContent" required="true" type="org.primefaces.model.StreamedContent" />
    </composite:interface>
    <composite:implementation>
        <p:dialog header="Print" id="printDlg" widgetVar="#{cc.attrs.widgetVar}" dynamic="true">
            <p:media value="#{cc.attrs.streamedContent}" width="100%" height="590px" id="media" cache="false"
                     player="pdf"/>
        </p:dialog>
    </composite:implementation>
```

so only the combination by passing a partial-expression is broken

**Comment by Koeppes** [comment]
ok, thank you very much!

**Comment by tandraschko** [comment]
Adjusted the documentation: https://primefaces.github.io/primefaces/15_0_0/#/core/dynamiccontent
