### ISSUE TITLE
Picklist: Mobile support

### ISSUE THREAD

**Issue by renanceratto** [primefaces/primefaces#1308]
It's not possible to scroll down the items of a picklist on mobile devices (even with responsive property)
The item's touch event triggers drag event

**Comment by mertsincan** [comment]
I think you can use the following css for mobile devices;

```
.ui-picklist .ui-picklist-list li {
        width: 90%;
}
```

**Comment by renanceratto** [comment]
Hello Mertsincan

The problem isn't layout.
The problem is: It is impossible to scroll down the items inside a picklist on mobile devices because when I touch one element of this picklist, it is dragged.

**Touch event of picklist on mobile devices should be disabled, but I don't know how it could be done.**

**Comment by melloware** [comment]
I have verified this issue using IOS 12.1.

**Comment by ybendek** [comment]
Any progress in this one?  I have the same issue and the scrollbar is not render in apple devices, even if you try the primefaces's showcase

**Comment by melloware** [comment]
No progress on this.  this component needs a good bit of work to be mobile ready.

**Comment by ybendek** [comment]
> No progress on this. this component needs a good bit of work to be mobile ready.

Ouch :( Or any workaround while it's officially fixed?

**Comment by melloware** [comment]
Not that I am aware of.

**Comment by melloware** [comment]
Also linking this ticket: https://github.com/primefaces/primefaces/issues/1927

Forum Post: http://forum.primefaces.org/viewtopic.php?f=26&t=44044

Generalized this ticket to PickList needs mobile support

**Comment by melloware** [comment]
Replaced by https://github.com/primefaces/primefaces/issues/11249
