### ISSUE TITLE
Primefaces upgrade to 14 : DefaultCommand with same scope and target.

### ISSUE THREAD

**Issue by pradipt1505** [primefaces/primefaces#13085]
### Describe the bug

Hi Team,

We are working on migrating PrimeFaces 11(jakarta) to PrimeFaces 14(jakarta). In our project, we are using multiple defaultCommand in the same form. This works completely fine in PrimeFaces 11. But after migration, we are observing following error:
![image](https://github.com/user-attachments/assets/c4c75ba0-7c9d-403c-aec6-39f35133de9c)

On further analysis we observed that it is happening when scope and target value is same for defaultCommand. The same logic works properly with Primefaces 11. 

On checking the changes done from PrimeFaces 11 to PrimeFaces 14, we observed that there was change done 7 months ago in the same line. In the above case, this.jqTarget[0] is undefined due to which we are getting error.

![image](https://github.com/user-attachments/assets/1a8cee88-07be-4357-9a06-7ac0a87bb73a)

Can you please review and provide your feedback?

### PrimeFaces edition

Community

### PrimeFaces version

14.0.9

### JSF implementation

Mojarra

### JSF version

4.0.7.redhat-00001

### Java version

21

**Comment by pradipt1505** [comment]
Apologies, had to to open discussion, instead opened Defect. Closing this for now.

**Comment by melloware** [comment]
Reproducer:
[pf-13085.zip](https://github.com/user-attachments/files/18165395/pf-13085.zip)
