### ISSUE TITLE
DataTable: Datatable: Row edit with validation results in disabled inputfields (>= Primefaces 14.0.6)

### ISSUE THREAD

**Issue by AndrewChurchill1970** [primefaces/primefaces#13091]
### Describe the bug

We have a validation check on editable mandatory row. If inputfield results in validation error (ui-state-error) the inputfield gets automatically disabled and can't be edited anymore. The inputfields which are in edit mode get automatically the attributes disabled="disabled" and data-disabled-by-editor="true". Why and how to avoid that? it should be able to enter valid input after validation error. Now all columns are disabled.

### Reproducer

<input id="baseForm:dataTable:0:id2" name="baseForm:dataTable:0:id2" type="text" value="" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-error mandatory percent_98 ui-state-focus" aria-required="true" aria-invalid="true" maxlength="50" placeholder="" **disabled="disabled" data-disabled-by-editor="true"**>

### PrimeFaces edition

None

### PrimeFaces version

14.0.6

### Theme

bootstrap

### JSF implementation

All

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 128.5.1esr (64-Bit)

**Comment by eduarddrenth** [comment]
Good to read this has been solved!

**Comment by eduarddrenth** [comment]
Though I am a bit worried, because also without validation errors and with versions prior to 14.0.6 all the inputs in cellEditors are disabled

**Comment by melloware** [comment]
i can do a release soon if you need it ?

**Comment by AndrewChurchill1970** [comment]
Good morning. A new Version  would be great. Thanks a lot for help.

Freundliche Grüße
Andreas Kircher


***@***.***<https://www.gesundheitskasse.at/>
Andreas Kircher
HEMA-CC
Softwareentwicklung & Applikationsmanagement
Fachbereich IT Management und IT Organisation
Kempfstraße 8, 9021 Klagenfurt am Wörthersee
Tel. +43 5 0766-162632
***@***.******@***.***>
www.gesundheitskasse.at<https://www.gesundheitskasse.at>

Informationen nach Art. 13 und 14 Datenschutz-Grundverordnung betreffend die Verarbeitung Ihrer personenbezogenen Daten finden Sie auf unserer Website unter www.gesundheitskasse.at/datenschutz<http://www.gesundheitskasse.at/datenschutz>
Von: Melloware ***@***.***>
Gesendet: Dienstag, 7. Jänner 2025 22:28
An: primefaces/primefaces ***@***.***>
Cc: Kircher Andreas ***@***.***>; Author ***@***.***>
Betreff: Re: [primefaces/primefaces] DataTable: Datatable: Row edit with validation results in disabled inputfields (>= Primefaces 14.0.6) (Issue #13091)


i can do a release soon if you need it ?

**Comment by melloware** [comment]
14.0.10 is in Maven Central

**Comment by eduarddrenth** [comment]
Just tested, all my inputs in all cellEditors in all datatables are disabled. I followed carefully the migration from 13 to 14.

**Comment by melloware** [comment]
@eduarddrenth i just deployed here and made the first column required="true"

![image](https://github.com/user-attachments/assets/72701529-3f74-4f09-b26a-dc9a30871279)


And you can cancel or keep editing and the fields are still editable not disabled

**Comment by eduarddrenth** [comment]
I'll try to make a rep.

**Comment by melloware** [comment]
sorry i forgot the link: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/edit.xhtml?jfwid=977a1

**Comment by eduarddrenth** [comment]
Thanks, one difference is that I use `editingRow`, could that be the cause?

**Comment by melloware** [comment]
can you elaborate what `editingRow`?  Is that an AJAX event?

**Comment by eduarddrenth** [comment]
![afbeelding](https://github.com/user-attachments/assets/87796174-ede8-45b7-b680-0d39f8f11e58)

**Comment by eduarddrenth** [comment]
played around with editingRow, that's not the cause.

What I see is that the table loads ok and then, in less than a second, fields become disable client side.

This is my table-header

```xml
 <p:dataTable allowUnsorting="true" filterEvent="change" id="datalist" value="#{ctrl.lazyModel}" var="item"
             selection="#{ctrl.selected}" sortMode="multiple" selectionMode="single"
             paginator="true" editable="#{sessionBean.mayEdit()}" editingRow="#{sessionBean.mayEdit()}"
             rowKey="#{ctrl.getRowKey(item.id)}" filteredValue="#{lazyParadigma.filtered}"
             rows="#{settings.rowsInTable}" lazy="true" draggableColumns="true" resizableColumns="true" liveResize="true" widgetVar="datalist"
             rowsPerPageTemplate="10,20,30,40,50" multiViewState="#{ctrl.rememberTableState}"
             currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords}"
             paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                                 >
```

**Comment by melloware** [comment]
hmmm nothing stands out there can you try and reproduce with  [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.

**Comment by AndrewChurchill1970** [comment]
14.0.10. tested successfully. BUG FIXED! Thank you.

**Comment by eduarddrenth** [comment]
In contradiction to what I said before, the problem is `editingRow="true"`. If I remove that as the only change editing works.
I'll make a reproducer and a new issue.

**Comment by AndrewChurchill1970** [comment]
@eduarddrenth try editable="true"

**Comment by eduarddrenth** [comment]
Thanks, I am aware, it is true depending on role access

**Comment by melloware** [comment]
@eduarddrenth good you narrowed it down can you open a new issue please
