### ISSUE TITLE
DatePicker: year input on Android

### ISSUE THREAD

**Issue by jacekzwroclawia** [primefaces/primefaces#13096]
### Describe the bug

I would like to report a few observations regarding the usability of the date picker on both desktop and mobile devices.

We have input: **birthdate**. In previous implementation of datepicker in PF 13 we had 100 position in year selector: 1924, 1925, ...., 2024. It wasn't the best solution however scroll worked very fast so it was easy to find a year. I understand that now it changed, because of accessibility, however look at current implementation of default `input type="date"` in HTML5: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_date . In both browser year is a select not input:

Chrome:
![image](https://github.com/user-attachments/assets/879d6167-632e-498a-ab1c-d631b2d644f3)

FF:
![image](https://github.com/user-attachments/assets/6f474856-e97d-47c9-ae77-82a79743d954)

Appropriate Primefaces datepicker type suitable for entering a date of birth is `navigator`.

Some problems:
1. When I enter valid date on desktop/mobile, then I click monthdate, but after that click months just refreshed so I need to choose day again.

![image](https://github.com/user-attachments/assets/56bcd2e0-878e-4ab5-8566-fd7baadcef20){ width=300 }

2. On Android (Chrome) I can enter any number in year input:
![image](https://github.com/user-attachments/assets/74b28f5d-8a0f-4b85-9d6d-04b76a4d7a74)

and when I made mistake, there is problem like this:
![image](https://github.com/user-attachments/assets/c079666f-efe9-4167-b7b4-9694f8df8dc7)

also on Android I can enter any date I want, however date that don't respect my range will be disabled, but it is still some UX problem.

3. In some birthdate inputs, we require users to input only children aged 0-18 years (for some tax relief). It was much easier to select one year from 18 possibilities than it is now – to manually enter the year and still face validation issues, not knowing whether the given year is still valid or already outside the range.

4. Maybe you can enable possibility to have year as select not number input - maybe this could be configurable with some flag?

### PrimeFaces edition

Community

### PrimeFaces version

14.0.9

### Theme

none

### JSF implementation

Mojarra

### JSF version

4.0.0

### Java version

21

**Comment by melloware** [comment]
Are you using Android.  Mostly likely because Android keyboard is a MESS the normal 4 digit code stuff is not working.  Does it work on Desktop properly to only allow 4 digits and withing the year range?

**Comment by melloware** [comment]
Also there is nothing stopping you from using `<p:inputText type="date" />` right?

**Comment by jacekzwroclawia** [comment]
Yes, I am using Android 13. That plain input `type="date"`  is better and better but it still looks and behaves different on a different browsers so it is not easy to have same look&feel on all devices and in mobile chrome version I don't think it is intuitive to click on the year in the top left cornerto change year - I'm afraiud users will rather click with left arrows hundrends time to go to 1950 year ;)
![image](https://github.com/user-attachments/assets/b95333a6-5079-40da-affd-b647e89e30c5)
![image](https://github.com/user-attachments/assets/e2adfe1b-d2c2-406b-bae6-98ca98752d1d)


But you are right, `<p:inputText type="date" />` is still an option + some custom validator for server side validation of min/max date.

**Comment by melloware** [comment]
Android == total nightmare cc @FlipWarthog 

Its because Android is the only browser that doesn't treat the keyboard as "keyboard input". and so all of the `keydown` stuff we do in PrimeFaces is useless on Android.

See this thread: https://stackoverflow.com/questions/36753548/keycode-on-android-is-always-229

**Comment by melloware** [comment]
@jacekzwroclawia I reopened: https://github.com/primefaces/primefaces/issues/12097  I think for 15.0.0 we will give people the option to to choose whether you want the dropdown picker or keyboard entry
