### ISSUE TITLE
AJAX in mobile showcase error

### ISSUE THREAD

**Issue by mdalboni** [primefaces/primefaces#1309]
http://www.primefaces.org/showcase/mobile/ajax.xhtml
I was looking for an ajax example for my learning and none of them were working.
When I cheked the showcase I got the same error as my application.

**Comment by sudheerj** [comment]
I didn't find any error in the above showcase example.What error you observed in the page.

**Comment by mdalboni** [comment]
The ajax isn't working and the left example loses the CSS.
I tried on Chrome, IE, Edge and Firefox..

![screenshot](https://cloud.githubusercontent.com/assets/11359687/14426379/f5bdcde6-ffc4-11e5-97cd-36b257cbb765.png)

**Comment by sudheerj** [comment]
It is not an issue actually.The example demonstrates how PFM supports AJAX and compared with plain JSF AJAX components.You can observe ajax loader for PrimeFaces button.The left example provided with plain html so it won't be same PFM one.You can find the code in ajax.xhtml as well.

**Comment by mdalboni** [comment]
Hmm now I get it.
I understood wrong the showcase example.

Thanks :D
