### ISSUE TITLE
p:messages may duplicate messages

### ISSUE THREAD

**Issue by german1410** [primefaces/primefaces#131]
I've upgraded from 3.5 to 5.0, previously I used the id attribute on the p:message component to be the same as the for attribute in order to target messages for that component, after the upgrade I notice messages where being duplicated. Event setting redisplay property to false did not work.

I think the problem is related to:

 if(_for != null) {
            // key case
            messages = context.getMessages(_for);

```
        // clientId / SearchExpression case
        UIComponent forComponent = SearchExpressionFacade.resolveComponent(
                context, uiMessages, _for, SearchExpressionFacade.Options.IGNORE_NO_RESULT);
        if (forComponent != null) {
            Iterator<FacesMessage> temp = context.getMessages(forComponent.getClientId(context));
            if (temp != null && temp.hasNext()) {
                messages = new IteratorChain(messages, temp);
            }
        }
    }
```

The workaround is easy, just use a key that does not match the messages component id.

PrimeFaces 5.2 (Can also be reproduced on 5.0)
Mojara 2.1.20-05 (Can also be reproduced 2.2.9)
Tomcat 7.0.55

**Comment by bgonzalez2** [comment]
I hope this gets fixed soon because we have a lot of pages where id and for attributes are the same.  FYI... this defect does not exist on v 5.1.13.  It only appeared when I upgraded to 5.2.  For now, I am rolling back to 5.1.13.

**Comment by tandraschko** [comment]
I will do it when my freetime allows it ;)
JFYI: It was introduced because of possible missing messages.
