### ISSUE TITLE
Autocomplete: Dropdown with LazyDataModel not working any more

### ISSUE THREAD

**Issue by kneringerjohann** [primefaces/primefaces#13100]
### Describe the bug

Since Primefaces 13 the Dropdown from Autocomplete-Component does not work anymore.
When Clicking the dropdown, the empty-message is displayed

### Reproducer

https://github.com/kneringerjohann/primefaces-test/tree/bug-autocomplete-lazy-dropdown

Here you find 2 Autocomplete Components, first without lazy datamodel and a working dropdown, second-one lazy with a non-working dropdown.

### Expected behavior

Autocomplete should display a list when clicking on the dropdown-button.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.9

### JSF implementation

Mojarra

### JSF version

4.0.9

### Java version

11

### Browser(s)

Chrome Version 131.0.6778.140

**Comment by melloware** [comment]
@kneringerjohann i just ran your example and its working for me.  I typed" Back" and it found "Back In Black" because you said `lazyField="name"` ???

![image](https://github.com/user-attachments/assets/7a372f25-3a74-40b7-a728-9c165ac8128d)

**Comment by kneringerjohann** [comment]
> @kneringerjohann i just ran your example and its working for me. I typed" Back" and it found "Back In Black" because you said `lazyField="name"` ???
> 
> ![image](https://private-user-images.githubusercontent.com/4399574/396925450-7a372f25-3a74-40b7-a728-9c165ac8128d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjkyOTUsIm5iZiI6MTczNDUyODk5NSwicGF0aCI6Ii80Mzk5NTc0LzM5NjkyNTQ1MC03YTM3MmYyNS0zYTc0LTQwYjctYTcyOC05YzE2NWFjODEyOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMTMzNjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YyYTljNDJkOTk5MmU2MWY1MjRkMWY4NjQ0NWEzODNkYzc2OGI5OGY2ZmVkYzI0MTQ4M2M3OTI1NTA5M2U3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CrkKYMcwFfE0uwyo81AoCXOHGxatazuGZoT9KNMLvRw)

Sorry, Maybe i was not precise enough, my issue is, that the dropdown-selection is not working:

![Bildschirmfoto 2024-12-18 um 14 38 11](https://github.com/user-attachments/assets/90a77b4a-5952-4ca7-a937-23b663a2cbae)

**Comment by melloware** [comment]
I still can't replicate I can select Back In Black or Thriller.

![image](https://github.com/user-attachments/assets/3bf1edb2-772e-47a8-81b5-8f617caaa7e9)

**Comment by kneringerjohann** [comment]
@melloware its not about selecting data bye typing text in the autocomplete but by using the dropdown feature. (dropdown="true")

I've added a small screencast to clarify.

https://github.com/user-attachments/assets/81e823de-c1eb-4740-b55d-6dc8173067cd

**Comment by melloware** [comment]
OK when I run your reproducer it send the query `""` and returns no results.  Can you update your reproducer to reproduce the issue exactly?

**Comment by melloware** [comment]
@kneringerjohann here is a runnable example working fine:
[pf-13100.zip](https://github.com/user-attachments/files/18188531/pf-13100.zip)

**Comment by kneringerjohann** [comment]
thank you @melloware , i see, so I might be lucky in the versions before that this worked out for me.

**Comment by melloware** [comment]
Yes all i added was..

```java
if (filterValue == null) {
				return true;
			}
```

My guess is an old PF had `filterValue=""` instead of NULL and the constraint contains was doing `"Thriller".contains("") == true` and now is doing `"Thriller".contains(null) == false"` but some bug for filtering we fixed a while ago.
