### ISSUE TITLE
Schedule: Uncaught TypeError: n.aria is undefined

### ISSUE THREAD

**Issue by schoeso** [primefaces/primefaces#13118]
### Describe the bug

After updating to PF 14 I get the error "Uncaught TypeError: n.aria is undefined" while rendering a xhtml Page with "schedule" a Lazy Data-Model. schedule is not rendered on the page and loadEvents is not called.

schedule.js.xhtml:18:24 with PF 14.0.9

Uncaught TypeError: n.aria is undefined
    configureLocale http://127.0.0.1:8080/homeServer/jakarta.faces.resource/schedule/schedule.js.xhtml?ln=primefaces&v=14.0.0:18
    init http://127.0.0.1:8080/homeServer/jakarta.faces.resource/schedule/schedule.js.xhtml?ln=primefaces&v=14.0.0:16
    Class.extend/f[g]< http://127.0.0.1:8080/homeServer/jakarta.faces.resource/core.js.xhtml?ln=primefaces&v=14.0.0:114
    d http://127.0.0.1:8080/homeServer/jakarta.faces.resource/core.js.xhtml?ln=primefaces&v=14.0.0:114
    createWidget http://127.0.0.1:8080/homeServer/jakarta.faces.resource/core.js.xhtml?ln=primefaces&v=14.0.0:26
    cw http://127.0.0.1:8080/homeServer/jakarta.faces.resource/core.js.xhtml?ln=primefaces&v=14.0.0:26
    <anonymous> http://127.0.0.1:8080/homeServer/pages/dayToDay/schedulerInput.xhtml?jfwid=aad8c61a-e9bb-4d59-9b97-925382bd7328:1:229

Tested with 14.0.0, 14.0.8 and 14.0.9

Worked fine with PF 13.x

Browser is Firefox 133.03

### Reproducer

<p:schedule value="#{schedulerInputVB.scheduleModel}"/>

### Expected behavior

Rendered schedule

### PrimeFaces edition

Community

### PrimeFaces version

14.0.9

### Theme

saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

OpenJDK 21.0.4+7

### Browser(s)

Firefox 133.0.3 (64-Bit)

**Comment by melloware** [comment]
Duplicate of:  https://github.com/primefaces/primefaces/issues/13075

You need to use a proper `locale.js` language

**Comment by melloware** [comment]
@schoeso if for some reason it doesn't work when you add proper Locale values....
then please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by schoeso** [comment]
It works. Thank you!!
