### ISSUE TITLE
Download of files with Non-ASCII characters in file names

### ISSUE THREAD

**Issue by GithubJohn3031** [primefaces/primefaces#1312]
The file names with Non-ASCII characters are shown not correctly during download.

The simple fix in FileDownloadActionListener.processAction(). It was tested with IE8, IE11, Chrome, Firefox. For file names with spaces the "+" is changed to "%20". See also: [Omnifaces.sendFile()](https://github.com/omnifaces/omnifaces/blob/master/src/main/java/org/omnifaces/util/FacesLocal.java#L1475) and [Change '+' to spaces in file name during file download](https://github.com/omnifaces/omnifaces/issues/237)

``` java
            String contentDispositionHeader = String.format("%s;filename=\"%2$s\"; filename*=UTF-8''%2$s",
                    contentDispositionValue, URLEncoderWrapper.encode(content.getName()).replace("+", "%20"));
            externalContext.setResponseHeader("Content-Disposition", contentDispositionHeader);
```

**Comment by tandraschko** [comment]
Coudln't we just use java's URLEncoder for the filename?

**Comment by GithubJohn3031** [comment]
URLEncoder doesnt encode all characters for file download correctly. For example spaces are not encoded correctly.

Please see the complete solution in OF, Utils.encodeURI(): https://github.com/omnifaces/omnifaces/commit/bba09d3915576d58101cc3bb7cc9d4c35b1652f9

Comment to Utils.encodeURI();

>  URI-encode the given string using UTF-8. URIs (paths and filenames) have different encoding rules as compared to
>  URLs. {@link URLEncoder} is actually only for www (HTML) form based query string parameter values. URI encoding
>   has a lot in common with URL encoding, but the space has to be %20 and some chars doesn't necessarily need to be
>  encoded.
>  @param string The string to be URI-encoded using UTF-8.
>  @return The given string, URI-encoded using UTF-8, or <code>null</code> if <code>null</code> was given.
>  @throws UnsupportedOperationException When this platform does not support UTF-8.
>  @since 2.4

**Comment by melloware** [comment]
@GithubJohn3031 I just submitted a PR with your suggestions and a unit test if you want to review.  I fixed it in all the PF code I found using attachments.
