### ISSUE TITLE
Primefaces 5.3: ajax event is undefined

### ISSUE THREAD

**Issue by andriyboychenko** [primefaces/primefaces#1313]
I'm trying to implement a function in javascript, that will restore tab scroll position after closing it. I defined an ajax, which will be called on tabClose event:

```
    <p:ajax event="tabClose" listener="#{addViewMenuBean.onTabClose}" update=":tabView" 
           onstart="saveScrollPosition(event);" oncomplete="restoreScrollPostion();"/>
```

and the javascript to save scroll position is defined as following:

```
    function saveScrollPosition(event){
        var closedTabWidth = $(event.target).parent().outerWidth();
        ...
    }
```

My problem is in the first line of javascript. The event is null. Do you know the reason why I can't obtain the closing event target?

**Comment by tandraschko** [comment]
Thats not a issue, use the forum next time.
onStart just provides a js param called "cfg". "event" is not available.
it should be possible to obtain the target via the cfg obj - do a console.log(cfg) and you should see everything ;)
