### ISSUE TITLE
Selection loss on DataTable submit

### ISSUE THREAD

**Issue by Tires** [primefaces/primefaces#1314]
Shouldn't the DataTable keep the selection on submit (with process) and update?

In DataTable.processUpdates:721 (primefaces 5.3), the submitted selection is applied:

`selectionVE.setValue(context.getELContext(), this.getLocalSelection());`

But after storing, it's directly overridden with null with:

`this.setSelection(null);`

This method calls:

`getStateHelper().put(PropertyKeys.selection, _selection);`

which effectively calls setValue on the EL-Expression. I would suggest to replace both calls with:

`this.setSelection(_selection)`

But I don't have the complete overview, thus it's up to you.

**Comment by tandraschko** [comment]
Could give us an example based on the showcase?

**Comment by cagataycivici** [comment]
This is by design of JSF, at update model, local value is passed to the model and local value is cleared afterwards. So datatable behaves like a regular input and considers the model value when rendering itself. This has been like this for the past 5 years and change will break a lot of apps.

**Comment by Tires** [comment]
I'm sorry, that I couldn't answer before. Probably the code change is not appropriate, but I think successful submitting, including validation should result in state keeping. I've discovered, that embedding the <p:dataTable> version 5.3 inside ui:repeat shows this behavior, while inside <c:forEach> it keeps state properly.
