### ISSUE TITLE
Context Menu Initilization Error

### ISSUE THREAD

**Issue by halisyilboga** [primefaces/primefaces#1315]
Context Menu should be initialized on domready instead of  initWithWindowLoad event. Since context menu is not initilized on ajax calls. Actually this change reversed in last commit on this file. I don't know why @tandraschko did something like that. 

the code should be fixed as 

`wb.initWithWindowLoad("ContextMenu", menu.resolveWidgetVar(), clientId);`
replaced with 
`wb.initWithDomReady("ContextMenu", menu.resolveWidgetVar(), clientId);`

**Comment by tandraschko** [comment]
i did it because we must be sure that the target widget is already available, not sure how we can fix both cases.

**Comment by halisyilboga** [comment]
How can this will help you, domready always works after load.
