### ISSUE TITLE
BlockUI: block keyboard in blocked area

### ISSUE THREAD

**Issue by NF117** [primefaces/primefaces#1325]
Primefaces 5.3
JBoss EAP 6.4

If you block a form with p:blockUI you can navigate with the keyboard to a button and press it with enter. I think this should not be possible. 
Same Issue has report in google Issue Tracker but not moved.
http://forum.primefaces.org/viewtopic.php?f=3&t=24329

XHTML:

```
<p:commandButton value="Block" update=":dialog"
    oncomplete="if(!args.validationFailed)PF('dialog_wv').show()" />

<p:dialog id="dialog" widgetVar="dialog_wv" modal="true"
    appendTo="@(body)" closable="false">
    <h:form id="form">
        <p:commandButton id="yes" value="yes"
            action="#{testController.test()}"
            oncomplete="PF('dialog_wv').hide()" />
        <p:commandButton id="no" value="no"
            oncomplete="PF('dialog_wv').hide()" />
    </h:form>

    <p:blockUI block="form" trigger="form:yes">
        <br />blockUI aktiv
        <br />
    </p:blockUI>
</p:dialog>
```

Controller:

@Named
@SessionScoped
public class TestController {
   public void test() throws ParseException, InterruptedException {
   System.out.println("test");
    Thread.sleep(5000);
  }
}

**Comment by sudheerj** [comment]
Even in the following jquery plugin demonstration we can see that it allows accessing page elements through keyboard.

[(http://malsup.com/jquery/block/)]

**Comment by NF117** [comment]
Issu is cloased :-1:  https://github.com/malsup/blockui/issues/57
trejder recommends:

> Instead of using global-blocking approach (jQuery(document).ajaxStart), try to block particular >object (dropdown), as in this example and add additional line of $('#object-you-re-blocking').attr('disabled', 'disabled');.
> 
> Then, after unblocking that object, try to use $('#object-you-re-blocking').attr('disabled', '');. Should work.

**Comment by geocode** [comment]
Please fix this issue.  This made the blockUI unusable for us.  There is a primefaces extension blockUI that works entirely differently -- we have started working with it, but it has created so many new problems.  Can we please fix this?

**Comment by Rapster** [comment]
Feel free to provide a PR. Primefaces is an open-source project ;)

**Comment by tandraschko** [comment]
refactored many things the last days, we can easily apply it now.

**Comment by tandraschko** [comment]
Ok, little bit different case. We could simple apply it if you block the whole document but not if you block single elements. Still needs effort. PR or sponsoring via PrimeFaces PRO welcome.

**Comment by melloware** [comment]
Reproducer: 
[pf-1325.zip](https://github.com/primefaces/primefaces/files/4671945/pf-1325.zip)
