### ISSUE TITLE
Enabe Ajax behaviour on "push" buttons

### ISSUE THREAD

**Issue by jessepeng** [primefaces/primefaces#1340]
The current implementation of a `CommandButton` does not allow Ajax behaviour on buttons that have the `type` attribute set to `button`. However, this can be useful in some cases, for example when one wants to have multiple `CommandButton` elements inside a single form element. The way the current implementation works, this would let to multiple `button` elements with type `submit` being rendered, which can be highly undesired (for example when considering what happens when the user hits the enter key).

[This thread in the PrimeFaces forum](http://forum.primefaces.org/viewtopic.php?f=3&t=45076) goes into a little more detail on how a solution of this could be easily achieved.

I would like to open this issue for discussion and would be willing to provide a pull request if there is demand for this.

**Comment by kukel** [comment]
if you have multiple commandButtons, you can assign a default button. I fail to see the need for adding ajax to type="button", it only complicates things

**Comment by melloware** [comment]
it has been 3 years since this ticket and there has not been a demand for this feature so closing this ticket for now.  It can always be re-opened if there is demand for this feature but to me this does not seem like a valid use case.
