### ISSUE TITLE
Omega Theme Calendar  ui-datepicker-calendar object is shown in half of calendar.

### ISSUE THREAD

**Issue by ihsanyapicioglu** [primefaces/primefaces#1341]
Omega Theme Calendar  ui-datepicker-calendar object is shown in half of calendar.

![pfbug](https://cloud.githubusercontent.com/assets/4387316/14790888/07de146a-0b1c-11e6-858b-e3c2795c6e3f.png)

**Comment by tandraschko** [comment]
Please provide steps to replicate, it works fine in the showcase.

**Comment by ihsanyapicioglu** [comment]
Hi,
When I use the calendar in a page that includes a template, it looks like above, but when I use it without template, it works fine.

I just created a page includes a template and added the calendar in a normal way like this,
`<p:calendar showOn="button" />`

**Comment by cagataycivici** [comment]
Ihsan, please try with 6.0.RC2.

**Comment by ihsanyapicioglu** [comment]
I created a new web project. I applied dependencies then I created a template page. I included an xhtml page into the layoutUnit. When I use include tag, problem goes on, but if I remove include tag, works fine. In the index.xhtml file, I have a calendar component.

You can see the complete code of my template.xhtml page below,

`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
<h:head>
    <title></title>
</h:head>
<h:body>
    <p:layout fullPage="true">
        <p:layoutUnit position="north">
        </p:layoutUnit>
        <p:layoutUnit position="west">
            <h:form>
                <ui:include src="menu.xhtml" />
            </h:form>
        </p:layoutUnit>
        <p:layoutUnit position="south">
        </p:layoutUnit>
        <p:layoutUnit position="center">
            <ui:insert name="content" />
        </p:layoutUnit>
    </p:layout>
</h:body>
</html>`

**Comment by mertsincan** [comment]
Hi Ihsan, 
Thanks for the sample. Fixed on 6.0.RC3.
