### ISSUE TITLE
Parsing exception in new 6.0.RC1 release

### ISSUE THREAD

**Issue by maol74** [primefaces/primefaces#1343]
I have developed 4 apps in primefaces 5.3 that works great for a customer, now when I try to upgrade to the new 6.0.RC1 release, more or les nothing works. I see when the ajax calls get invoked there are a parse error that I have not seen with the 5.3 release, se ajax xml below in this gist https://gist.github.com/maol74/af0c5aa97b502b236a20ab0bc0cb6d1a

**Comment by maol74** [comment]
I also receives a lot of "JSF1007: Duplicate component ID xxx found in view." that I did not get in the 5.3 release, please can you find any plausible explanation why this occurs?

**Comment by cagataycivici** [comment]
@tandraschko What do you think? Any idea, why this could happen?

@maol74 Can you send us a simple test case that we can run and replicate?

**Comment by maol74** [comment]
@cagataycivici I will try to submit a simple test case, tomorrow, what is the easiest way "zip an example up" or as a git repo?

**Comment by tandraschko** [comment]
Could be relatetd to #1360
But if nonone provides a example, i can't check it.

**Comment by tandraschko** [comment]
Could you please try with building from source? it COULD be fixed but i can't check it without a sample.

**Comment by tandraschko** [comment]
Any news?

**Comment by maol74** [comment]
@tandraschko - I have testet my app against 6.0.RC3 and the error that I described above are now gone!
Thanks for the quick reply and attention on this!

**Comment by maol74** [comment]
I have though another problem with 6.0.RC3 but i report a new issue on that since it´s not related to this defect
