### ISSUE TITLE
StyleSheets in last facets are being ignored

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#1344]
In my current applications I'm still adding my custom stylesheets in a facet to make sure, they override the ones from PF:

```
<h:head>
...
</h:head>
<f:view encoding="UTF-8" contentType="text/html">
    <h:body>
        <f:facet name="last">
            <h:outputStylesheet library="css" name="mycss.css" />
        </f:facet>
   ...
   </h:body>
</f:view>
```

However since 6.0 the StyleSheets in those facets (I only tested `last` yet) are not rendered anymore. Has this behaviour changed somehow, or was it deprecated?

If I add those sheets in the body, outside the facet, everything works as normal, so I'm not sure if doing that was needed in the first place.

**Comment by tandraschko** [comment]
we don't overwrite the body renderer for that purpose, the "last" facade is only supported from our side in h:head.

**Comment by zhedar** [comment]
I see, thanks for the heads up. I should have probably looked that up again.
It's just, that the "last" facade inside `h:body` was working until version 5.3 and just stopped working with 6.0, that's why I asked.

Also probably more people will have this problem once 6.0 is final and this is an undocumented change. For example the [first quick google search](https://www.google.de/#q=jsf+facet+last+primefaces&gfe_rd=cr) leads to http://www.mkyong.com/jsf2/primefaces/resource-ordering-in-primefaces/ (first hit for me, but may be personalized) which suggests to add it to the body. So I guess that's why this wrong usage (which functioned before) may be used in some code bases.

**Comment by tandraschko** [comment]
We never statet somewhere that this should work.
Also we didn't changed to BodyRenderer since 2 years -> https://github.com/primefaces/primefaces/commits/master/src/main/java/org/primefaces/renderkit/BodyRenderer.java

**Comment by zhedar** [comment]
I get it was somehow undocumented behaviour, but I was curious enough to check what caused this to change.
If you are as well, I tracked down the commit that affected this: 1398f1dfc5b9314f056df0d8e3c46f87d627fd32 for #1201 (so 34136ff6ec32181b57d8adab4b77cb8f8ff3b008 was the last one to reproduce the old behaviour), so this was a rather recent change. 

However, I don't really want to bring that behaviour back. I just think that mentioning it in the migration guide to 6.0 may be worth it though.

**Comment by tandraschko** [comment]
added it in the migration guide: https://github.com/primefaces/primefaces/wiki/Migration-Guide
