### ISSUE TITLE
target attr for p:menuItem is not work

### ISSUE THREAD

**Issue by zsuiqiang** [primefaces/primefaces#1345]
`<p:menuitem url="www.baidu.com" target="workspace"/>`

page is always opened in same window.

**Comment by sudheerj** [comment]
Is it issue with framename target only?How it works with all possible values

`<a target="_blank|_self|_parent|_top|framename">`

**Comment by zsuiqiang** [comment]
No,it works same  with all possible values.

**Comment by tandraschko** [comment]
works fine for me.
