### ISSUE TITLE
primefaces.js not found on 6.0.RC2

### ISSUE THREAD

**Issue by andrei-ivanov** [primefaces/primefaces#1348]
Hi,
Trying to upgrade to 6.0.RC2 (using the Flick theme), I now get this:

> 26-Apr-2016 09:40:36.125 WARNING [http-apr-8443-exec-1] com.sun.faces.application.resource.ResourceHandlerImpl.logMissingResource JSF1064: Unable to find or
> serve resource, primefaces.js, from library, primefaces.

Seems this is gone in 6.0 but PF still tries to include it.
As far as I see, I don't include it manually.

**Comment by tandraschko** [comment]
Works fine in the showcase. If you don't provide a example application, i will close it.

**Comment by andrei-ivanov** [comment]
Hmm,
Wonder if the primefaces extensions has anything to do with it.
I think for PF it was merged so I have to exclude it, right?

**Comment by tandraschko** [comment]
There is currently no released version of extensions which is 100% compatible with 6.0. You can build it from source.

**Comment by andrei-ivanov** [comment]
I can confirm that excluding the extensions made this error go away.
