### ISSUE TITLE
DashBoard: Responsive support

### ISSUE THREAD

**Issue by josebm0920** [primefaces/primefaces#1350]
The current implementation of `DashBoard` does not allow to resize panels and `colspan` the dashboard columns. I think that this is very important feature to develop, this is common in another dashboard with other technologies. 
I would like to open this issue to primefaces developers.

**Comment by melloware** [comment]
![dashboard](https://user-images.githubusercontent.com/4399574/216385279-b29c115b-5310-469f-8568-f81913a869f9.gif)
