### ISSUE TITLE
p:colorPicker does not support passtrough

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1352]
Hi, Since #56 and #730 are still not possible yet (both 5.x ELITE and 6.0 RC2) i wanted to implement a custom way to fix the issues myself, however for the sake of simplicity id like to put it into the componend. I noticed that passtrough does not work for the colorpicker. 

I expected i could add a "onchange" manually to the input tag of p:colorPicker like it is possible with other components. But here it does not work. 

<p:colorPicker value="#ff00ff" pt:onchange="alert('test');"/>

Thanks. Please note that the colorPicker is very limited as it is now.

**Comment by tandraschko** [comment]
on which element should it render the passthrough attributes? on the input?

**Comment by cnsgithub** [comment]
Yes, i guess that would make most sense. Thanks

**Comment by tandraschko** [comment]
Fixed ;)
