### ISSUE TITLE
p:lightbox triggers Uncaught Type error Touches

### ISSUE THREAD

**Issue by rrdlpl** [primefaces/primefaces#1357]
I have a lightbox on my main page that is displayed automatically when the user logs in for the first time, but when the page is loaded a weird javascript error appears in the console which makes that everything related to Primefaces stop working. This is the code of my lightbox:

```
<p:lightBox styleClass="imagebox" id="lightbox1" visible="true" 
            rendered="#{dashboardBean.firstTimeLoggedIn}" widgetVar="lightbox1"
            onHide="hideInstructions()">
            <h:outputLink 
                value="#{request.contextPath}/resources/images/instructions/instructions-1.gif"
                title="Step 1"/>           

            <h:outputLink
                value="#{request.contextPath}/resources/images/instructions/instructions-2.gif"
                title="Step 2" />            
            <h:outputLink
                value="#{request.contextPath}/resources/images/instructions/instructions-3.gif"
                title="Step 3" />            
</p:lightBox>
<h:form  rendered="#{dashboardBean.firstTimeLoggedIn}">
            <p:remoteCommand name="hideInstructions"
                action="#{sessionBean.hideInstructions}" />
 </h:form>

```

This is the error that appears in the console of chrome:

![](http://i.stack.imgur.com/NVRE3.png)

Note: I'm not including any jQuery library.
PrimeFaces version: 5.3

**Comment by rrdlpl** [comment]
II think that the error is coming from this [file](https://github.com/primefaces/primefaces/blob/87bb7b52060be59497dc166531f9f435b07d8879/src/main/resources/META-INF/resources/primefaces/lightbox/lightbox.js) Line 274.

```
 if(e.originalEvent.touches) {
                pageX = e.originalEvent.touches[0].pageX;
                pageY = e.originalEvent.touches[0].pageY;
   } else {
                pageX = e.pageX;
                pageY = e.pageY;
  }
```

is it possible that e.originalEvent is undefined at the beginning when the page is loading?

**Comment by tandraschko** [comment]
Please try with trunk.

**Comment by rrdlpl** [comment]
@tandraschko  I dont understand your comment. What do you mean with trunk?

**Comment by tandraschko** [comment]
That i fixed it in trunk/master.
