### ISSUE TITLE
New component: jsfinspector

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1358]
Would be awesome to have an easy-to-use component which display component tree/lifecycle detail such as http://tasel.github.io/jsfinspector/

**Comment by tandraschko** [comment]
Why not just this component?

**Comment by Rapster** [comment]
Well, first you have to know it uses a web servlet named jsfinpector with jQuery.get function to display results asynchronously. I was thinking, Primefaces team could use a better approach, like writing results by using java component renderer and not jquery function.

**Comment by tandraschko** [comment]
Not sure but you are able to provide ideas and prototypes ;)

**Comment by kukel** [comment]
Maybe this would be a better component for OmniFaces

**Comment by sudheerj** [comment]
I tried to use this component in PrimeFaces showcase application but due to some issue I was not able to see all the features of it https://github.com/tasel/jsfinspector/issues/6. Anyway it would be good for JSF development and to see the internals.In my opinion it will be well suited for utility library such as OmniFaces.Ofcourse if required it can be added to PrimeFaces also as utility component.

**Comment by tandraschko** [comment]
IMO providing the lifecycle timings is easy and very useful. Not sure about the component tree infos.

**Comment by Rapster** [comment]
@sudheerj I answered to your problem

@tandraschko Component tree infos is very useful! Actually in our project, our component tree is 100000 (big right? :) ), but since we're using `DynaForm`, we see a lot of improvements, specially rearding memory. In any case, it does not cost a thing to display those information, although I do agree displaying components name is not very usefull, but again, in development mode, we need as much information as we need. As I was saying to @sudheerj, I have made some changes by myself that I did not push yet, I will probably fork jsfinpector to make them available (such as display phases name, not displayin all components name).

**Comment by tandraschko** [comment]
Shoudln't ui:debug provide the component tree infos already?

**Comment by Rapster** [comment]
`ui:debug` displays the state of the component tree and the application’s scoped variables. Not very informative in my case

**Comment by zhedar** [comment]
@Rapster I think reviving that project may be a better (and also great) choice. It may be helpful for many projects and the general idea doesn't sound like a job for a component framework.

**Comment by Rapster** [comment]
I think @tandraschko is working on something regarding lifecyle :+1: 
Do you plan to do anything about components count @tandraschko ?

**Comment by tandraschko** [comment]
Currently not

**Comment by tandraschko** [comment]
Feel free to provide a prototype, i can help with polishing then.
I currently don't have any intentions to implement such a component.

**Comment by tandraschko** [comment]
@Rapster I think a good way to provide such a component, is to do it in extensions first (so please, do ;))
So will close it for now.
