### ISSUE TITLE
page navigation not working

### ISSUE THREAD

**Issue by gpetrarca** [primefaces/primefaces#1359]
Preface: I'm using explicit navigation and no annotations, i.e. the navigation is controlled via faces-config.xml.
I have an example application with login page and home page (normally accessed upon correct login).
Each page contains a theme switcher, too.
The navigation is ok when using primefaces 5.3, whilst I don't access the home page when using primefaces 6.0.RC2 .

**Comment by tandraschko** [comment]
please provide a simple maven app with e.g. jetty plugin for testing. navigation is working fine in my applications and showcase.

**Comment by gpetrarca** [comment]
[ExampleServerOAM.zip](https://github.com/primefaces/primefaces/files/240617/ExampleServerOAM.zip)
This is a minimal WildFly 8.2 application with the login page and the home page. To login, set username to "admin" . 
If I switch primefaces jar (from 5.3 to 6.0.RC2) I'm not able to enter the home page

**Comment by tandraschko** [comment]
please provide a maven example - the PrimeFaces team is working with maven only.

**Comment by gpetrarca** [comment]
sorry, i'm not used to bare maven projects. Might you provide a basic (Eclipse) PF maven project? In this case I'd be able to include the logic of my project.

**Comment by tandraschko** [comment]
Check out the showcase, it's a maven project.

**Comment by gpetrarca** [comment]
[ExampleMavenServerOAM.zip](https://github.com/primefaces/primefaces/files/243553/ExampleMavenServerOAM.zip)
Here is the maven project.

**Comment by tandraschko** [comment]
Thanks for the example, i fixed it.

**Comment by gpetrarca** [comment]
Great!
