### ISSUE TITLE
Duplicate resources when h:outputScript is within composite component

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#1360]
I've just tested PF 6.0.RC2 but it has an error in it's resource handling.

I've some composite components which are used to create a multi-level menu structure based on ul/li. The top-level CC contains a `h:outputScript` declaration which includes the required javascript file for that menu.
On (AJAX) postback I get an exception which reports a duplicate client ID. That client ID points to the outputScript. As soon as I move that declaration out of the CC everything works as expected.

In PF 5.3 everything was okay, but I can't detect any commit that may be responsible for this behavior.

**Comment by tandraschko** [comment]
please provide a complete example maven application.

**Comment by fanste** [comment]
I've overseen a new class that was added some in april 2016. The bug is caused by `DynamicResourcesPhaseListener`. As soon as I remove it from the `faces-config.xml` it is working again.

I will try to package one if I find some time...

**Comment by tandraschko** [comment]
Please try again with building from source - could be fixed now.

**Comment by fanste** [comment]
I've just tried to modify the showcase as an example - but as often in the past, you are very fast :)

I can confirm that this error is fixed.
