### ISSUE TITLE
PF 6.0 - Problem with Ressource-Loading of scritps/css

### ISSUE THREAD

**Issue by hinneLinks** [primefaces/primefaces#1361]
I have two Issues with Resource-Loading, i believe they might be related.
1. With Primefaces 5.3 it was possible to have a `<f:facet name="last"><h:outputStylesheet library="css" name="some-css.css" /></f:facet>` somewhere in the site, the Ressources would then end up in the `head` tag. With 6.0.RC2 those Ressources wont be loaded anymore. See `facet-first-middle-last-loading.xhtml` of the example.
2. My App uses [Delataspike](https://deltaspike.apache.org/index.html). Deltaspike has a tag `<ds:windowId/>` which will add some javascripts. Again, with 5.3 the Scripts end up in  the `head` tag, with 6.0.RC2 they are missing. See `deltaspike.xhtml` of the example.

I've added a maven example. Since Deltaspike needs CDI, i used wildfly instead of jetty (i couldn't get jetty to work).

[primefaces-ressource-loading-bug-wildfly.zip](https://github.com/primefaces/primefaces/files/240619/primefaces-ressource-loading-bug-wildfly.zip)

Usage of maven-wildfly plugin:
- start with goal wildfly:run
- stop with goal wildfly:shutdown
- redeploy with wildfly:deploy

see readme.txt, too!

might be related to #1360 and #1343

**Comment by tandraschko** [comment]
1) this was never designed that way and there is no way to fix it. It was a random feature. The last facet only works in the h:head tag, as it should be - as the facet applies to the parent component.
2) will check it

**Comment by tandraschko** [comment]
Both should be fixed by #1364
But remember, facets are bound to the parent. so 1) is really just a random feature and could simple break again in the future.
