### ISSUE TITLE
Composite components not able to add resources to head in 6.0.RC2

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#1363]
**Note:** This issue does not appear in Primefaces 5.3.

Steps to reproduce:
1. Create the following script resource as **`resources/example/head.js`**:

```
var parentTagName = document.currentScript.parentNode.tagName;
if (parentTagName === "HEAD") {
    alert('This target="head" script is correctly rendered as a child of the <head> element');
}
else {
    alert('This target="head" script is incorrectly rendered as a child of the <body> element');
}
```
1. Create the following composite component as **`resources/ex/headScript`**:

```
<ui:component xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:cc="http://xmlns.jcp.org/jsf/composite"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3.org/1999/xhtml http://www.w3.org/2002/08/xhtml/xhtml1-transitional.xsd">

    <cc:interface>
    </cc:interface>

    <cc:implementation>
        <h:outputScript library="example" name="head.js" target="head" />
    </cc:implementation>

</ui:component>
```
1. Add `ex:headScript` to a page as a child of `<h:body>`:

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ex="http://xmlns.jcp.org/jsf/composite/ex"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
    </h:head>

    <h:body>
        <ex:headScript />
    </h:body>
</html>
```
1. Navigate to the page.

If the bug still exists, the alert will show:

> This target="head" script is incorrectly rendered as a child of the <body> element

If the bug is fixed, the alert will show:

> This target="head" script is correctly rendered as a child of the <head> element

The issue is caused by [Primefaces wrapping all renderers with `PrimeRendererWrapper`](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/renderkit/PrimeRenderKitWrapper.java#L34) which does not implement `ComponentSystemEventListener` like [`ScriptStyleRendererBase` does](https://github.com/javaserverfaces/mojarra/blob/2.2.13/jsf-ri/src/main/java/com/sun/faces/renderkit/html_basic/ScriptStyleBaseRenderer.java#L68-L108). However, I'm not sure how best to fix it since there are many [`ComponentSystemEvent`s that can be listened for](https://docs.oracle.com/cd/E17802_01/j2ee/javaee/javaserverfaces/2.0/docs/api/javax/faces/event/ComponentSystemEvent.html). Simply listening for `@ListenerFor(systemEventClass=PostAddToViewEvent.class)` and calling the wrapped method [(like we do in Liferay Faces)](https://github.com/liferay/liferay-faces-bridge-impl/blob/master/bridge-impl/src/main/java/com/liferay/faces/bridge/renderkit/html_basic/internal/ResourceRendererBridgeImpl.java#L48-L49) will only fix this particular issue. But other components that listen to other events will still be broken.

**Comment by tandraschko** [comment]
Fixed by #1364
