### ISSUE TITLE
Cannot read property 'ajax' of null with Omnifaces FullAjaxExceptionHandler

### ISSUE THREAD

**Issue by gpoluch** [primefaces/primefaces#1367]
With Primefaces 6.0 sources (to commit a0fa648) and Omnifaces FullAjaxExceptionHandler i noticed error in javascript. Redirect to error page on ajax requests works well but error shown in console is like this:

![error](https://cloud.githubusercontent.com/assets/10855110/14941852/02596ace-0fab-11e6-8f66-3727ea8fbad8.PNG)

I thing it is newly introduced bug because on version 5.3 everything works without any warnings or errors.

**Comment by tandraschko** [comment]
Please try with a current source build - i fixed a similar bug today.
Or provide a full working maven jetty example app ;)

**Comment by gpoluch** [comment]
I reported this bug on current source - latest commit is a0fa648.

**Comment by tandraschko** [comment]
So please provide a full working example.

**Comment by tandraschko** [comment]
Any news?
