### ISSUE TITLE
PrimeFaces dialog framework not working on 6.0 RC_2 dialog not closing

### ISSUE THREAD

**Issue by DariusBaniunas** [primefaces/primefaces#1370]
![capture](https://cloud.githubusercontent.com/assets/5983133/14955412/60e24a3e-1082-11e6-86a3-e8e788570274.PNG)

Was working on 5.3

Now when PrimeFaces.closeDialog is called I get a JavaScript error and dialog stays open (screen attached)

**Comment by tandraschko** [comment]
Is primefaces' core.js included in the current view?

**Comment by cnsgithub** [comment]
Is this really the recommended way to do this? 
Wouldnt  PF('widgetVar').hide()   be much easier?

**Comment by DariusBaniunas** [comment]
We didn't explicitly include core.js, it was not needed in PrimeFaces 5.3
Why is it necessary to include it?

**Comment by tandraschko** [comment]
please just provide a simple maven jetty webapp, it's much easier for us.

**Comment by DariusBaniunas** [comment]
The problem still exists but now I have done more debugging and found a very interesting situation

The problem is not in the dialog itself but one element in it

I open dialog:
public String externalProcessOrderDialog(Long partId) {
        log.debug("external sale order dialog=" + partId);
        RequestContext.getCurrentInstance().openDialog("viewExternalProcessOrder", getDialogOptions(), getDialogParamPartId(partId));
        return null;
    }

Code of the dialog itself:

[viewExternalProcessOrder.txt](https://github.com/primefaces/primefaces/files/307401/viewExternalProcessOrder.txt)

If it is opened like this we get errors:

![image](https://cloud.githubusercontent.com/assets/5983133/15937648/66f10708-2e78-11e6-919f-47854ba7f227.png)

But if in the dialog we remove element p:inputTextarea or replace it to something else like p:inputText
Everything works like a charm - my assumption is that the only problem is this element and only in dialog framework, because everywhere else in the project this element causes no errors like that

Now we are using Primefaces 6.0 version running on Glassfish 4.1.152.1 / Mojarra 2.2.10

**Comment by Karolis92** [comment]
as @tandraschko said - try including `core.js` into the view.
As you can see here: https://github.com/primefaces/primefaces/wiki/Migration-Guide js libraries have changed since 5.3

**Comment by Karolis92** [comment]
as @tandraschko said - try include core.js into the view.
As you can see here: https://github.com/primefaces/primefaces/wiki/Migration-Guide js libraries have changed since 5.3
