### ISSUE TITLE
Upgrade to Timepicker 1.6.3

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1371]

**Comment by jxmai** [comment]
Causing regression: #2811

**Comment by jxmai** [comment]
regression: #3054

**Comment by jxmai** [comment]
@mertsincan Please review this upgrade when you are available. melloware and I had spent some effort trying to address this regression previously, but there is no feedback so far. Please take a look at https://github.com/primefaces/primefaces/pull/2839. Currently the `onchange` client side callback is broken.

**Comment by mertsincan** [comment]
Hi @jxmai,

Issue #2811 is fixed by @melloware. I think issue #3054 is not related to this upgrade.
