### ISSUE TITLE
SelectOneMenu lost width style after 6.0 RC2

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#1372]
Version 5.3 looks like this
![5.3](https://cloud.githubusercontent.com/assets/3578953/14957870/1b2a2eae-105e-11e6-9f81-b387b52344d5.png)

Version 6.0 RC2
![6.0 RC2](https://cloud.githubusercontent.com/assets/3578953/14957853/f602fa84-105d-11e6-8b5f-5dcbe2f0b52d.png)

**Comment by mertsincan** [comment]
#244 
We'll work on this issue and get back to you.

**Comment by erickdeoliveiraleal** [comment]
Thank you. For now I'm using CSS provided by @cnsgithub  https://github.com/primefaces/primefaces/issues/244#issuecomment-214228742

**Comment by cagataycivici** [comment]
Let's track at 244
