### ISSUE TITLE
ArrayIndexOutOfBoundsException on JBoss EAP 6.4

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1375]
Reported by PRO User;
When Primefaces 5.3.1 is deployed on JBoss 6.4 an ArrayIndexOutOfBoundsException is thrown in AjaxBehaviorListenerImpl.java in processAjaxBehavior method.
AjaxBehaviorListenerImpl.java

```
public void processAjaxBehavior(AjaxBehaviorEvent event) throws AbortProcessingException {
        FacesContext context = FacesContext.getCurrentInstance();
        ELContext elContext = context.getELContext();
        if(LOG.isLoggable(Level.FINE)) {
            LOG.fine("Try to invoke listener: " + this.listener.getExpressionString());
        }

        try {
            this.listener.invoke(elContext, new Object[0]);
        } catch (MethodNotFoundException var5) {
            this.processArgListener(context, elContext, event);
        } catch (IllegalArgumentException var6) {
            this.processArgListener(context, elContext, event);
        }

    }
```

**Comment by tandraschko** [comment]
Could you please post a stacktrace? the might not be correct as a ArrayIndexOutOfBoundsException might also be thrown the be the listener method itself.

**Comment by mertsincan** [comment]
Hi Thomas,
I don't have a stack trace. This issue is reported by Pro User. He send this fix and Çağatay said to me that I could add to it into 5.3.x and 6.0.
