### ISSUE TITLE
 Cannot read property 'ajax' of null

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#1376]
Hi,

since version 6.0.RC2 I am getting error in a  <p:commandButton with ajax action, when inside a p:confirmDialog modal. In previous versions was working. ..

My code

```
 <p:confirmDialog   id="alertDialog"    header="Atenção" 
                                                        severity="alert" 
                                                        width="620"  
                                                        widgetVar="modalAlerta" 
                                                        closable="true"  
                                                        style="z-index: 10030 !important;"  >   

<p:commandButton id="buttonConfirmaCadastro"  
                                            value="#{msg.button_sim}"  
                                            action="#{parceiroBean.cadastrarParceiro}"  
                                            styleClass="margemEsq margemDir has-spinner"
                                            rendered="#{not parceiroBean.modoEdicao and not parceiroBean.fromModal}"
                                            oncomplete="PF('modalAlerta').hide(); $('#myModalIncluirParceiro').modal('hide');"
                                            update=":globalMessages">

 </p:commandButton>         
  </p:confirmDialog> 
```

`

Error: 
`Uncaught TypeError: Cannot read property 'ajax' of null >  core.js.html?ln=primefaces&v=6.0.RC2:3

PrimeFaces.ajax.Utils.updateElement @ core.js.html?ln=primefaces&v=6.0.RC2:3PrimeFaces.ajax.ResponseProcessor.doUpdate @ core.js.html?ln=primefaces&v=6.0.RC2:3PrimeFaces.ajax.Response.handle @ core.js.html?ln=primefaces&v=6.0.RC2:3r.success @ core.js.html?ln=primefaces&v=6.0.RC2:3i @ jquery.js.html?ln=primefaces&v=6.0.RC2:25cc.fireWith @ jquery.js.html?ln=primefaces&v=6.0.RC2:25cf @ jquery.js.html?ln=primefaces&v=6.0.RC2:25i @ jquery.js.html?ln=primefaces&v=6.0.RC2:25`

**Comment by tandraschko** [comment]
Please provide a complete simple maven jetty example. 
When i copy your example in the showcase and remove the beans stuff etc., it works fine for me.

**Comment by cagataycivici** [comment]
tandraschko There seems to be a common problem with ajax in 6.0.x, let's keep an eye on this.

Only part that has ajax property is $.ajax in getScript, if jquery is in global scope, it should work. Still not sure why getScript is called though here.

**Comment by edudoda** [comment]
Cool... will wait for the final version of 6.0, if error persists I'll  submit the complete code example. Thanks...

**Comment by tandraschko** [comment]
Thats not an good way as we will release the next version a half year later.... If you provide a example now, it will be fixed for final.

**Comment by edudoda** [comment]
@tandraschko, how can I elaborate it more, or even debug it precisely? I don't use Maven/jetty.

**Comment by tandraschko** [comment]
To be honest, i don't know where i would start to search the bug. I just need a example to replicate.

Maybe you should just take a look at our showcase.
Install maven, checkout the showcase and run via: mvn clean package jetty:run
So maybe you can apply same changes to the showcase to replicate the error.

However, i just need a small sample to replicate it which is based on maven and in the best case jetty.
