### ISSUE TITLE
JSF update to 2.2.13

### ISSUE THREAD

**Issue by SantoshCCS** [primefaces/primefaces#1378]
JSF update to 2.2.13 in milestone 6.0

**Comment by tandraschko** [comment]
because?

**Comment by tandraschko** [comment]
Do you mean in the showcase? there is no need to upgrade the dependency in the primefaces pom as it's only a "provided" depdendency.

**Comment by SantoshCCS** [comment]
i can use jsf 2.2.13 or not in our project with primefaces 5.3

**Comment by tandraschko** [comment]
PrimeFaces is compatible with JSF 2.0,2.1 and 2.2.
