### ISSUE TITLE
Clarify if we should update h:head

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#1379]
Currently mojarra doesn't replace the h:head content when updating the ViewRoot via @all or updating the h:head directly:
https://github.com/javaeekickoff/mojarra/blob/master/jsf-api/src/main/resources/jsf.js#L1389

We implemented this as new feature and works actually fine.
However a user mentioned that he don't like the flickering that occurs while reloading the h:head content.
If we remove this feature, weird bugs might occur as some scripts might not be available. So actually our handling is correct.
Maybe we should make it configurable.

**Comment by gpetrarca** [comment]
Note: the flickering in Wildfly 8 is acceptable, whilst it is quite annoying in Wildfly 10

**Comment by tandraschko** [comment]
will close it, not updating the head is no solution as not loaded resources or other bugs will occur.
