### ISSUE TITLE
DataTable: Range filter

### ISSUE THREAD

**Issue by SantoshCCS** [primefaces/primefaces#1380]
Range filter in Datatable

**Comment by cagataycivici** [comment]
Please provide more description.

**Comment by SantoshCCS** [comment]
Datatable contains 10 row. One column  contains 1 to 10 int  value i wanna record from 2 to 5

**Comment by manojkumar-1** [comment]
Is there any update on this. I have similar requirement.

**Comment by manojkumar-1** [comment]
Looking for range filter for number and date data types

**Comment by melloware** [comment]
Example on how to do Range Filter in Datatable provided: https://stackoverflow.com/questions/23791039/primefaces-datatable-date-range-filter-with-filterfunction

**Comment by tandraschko** [comment]
Could we add the sample to the Showcase?
