### ISSUE TITLE
Datatable reset selection state after click outside of Browser

### ISSUE THREAD

**Issue by frkmed** [primefaces/primefaces#1381]
After selected a row in the datatable and when i click outside of the browser or change the tab of browser the selected row reseted to the first row : you can see this if you navigate to http://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml  and go to secend example "Single with Row Click" and select the third row than click outside of Browser and return you will see that the row was reseted. thank's.

**Comment by tandraschko** [comment]
Works fine for me in FF.

**Comment by frkmed** [comment]
not working for me in FF

**Comment by tandraschko** [comment]
@cagataycivici @mertsincan  does it work for you?

**Comment by frkmed** [comment]
my problem is like @markusg80  with issue #1230

**Comment by kukel** [comment]
Works for me in FireFox (45.0.2)

**Comment by markusg80** [comment]
It does not work also in Firefox 46.0.1. When u follow the description of @frkmed above inside the Showcase, after you click again inside the "Single with Row" example you will notice that the first row changes the color. If you take this example with more rows, scrolling enabled, selection event and you scroll down and select a row at the end and click outside browser and again in the table then the scrollposition jumps to top and first row change color. Go and modify the showcase example like like in my example in issue #1230. If you not try it you'll not find the bug. Good Luck

**Comment by cagataycivici** [comment]
Works for me on FF 46.0.1.

**Comment by frkmed** [comment]
I have tested this issue in many browser and also in  FF 46.0.1. but the probleme persist please can you give me a solution.

**Comment by markusg80** [comment]
Problem persist for me too. Should i create a example project for you?

**Comment by mtbadi39** [comment]
Works for me without problems on : 
FF 46.0.1
Chrome 50.0.2661.102

**Comment by markusg80** [comment]
Steps to reproduce better:

Take the Single with Row Click example and modify it to load more cars (for example 100) and enable scrolling. Scroll down so long the first visible rows disappears and then select one random row. After this click on Taskbar and then click back to datatable. then the table scrolls to top and first row get hover color. And now another row is selected because selection event is fired after scroll to top is complete. I can add a screencast
