### ISSUE TITLE
Autocomplete with ampersand suggestion returns escaped markup

### ISSUE THREAD

**Issue by EugenFischer** [primefaces/primefaces#1385]
![autocomplete](https://cloud.githubusercontent.com/assets/13999463/15014167/b3e4c77e-1204-11e6-98cf-256501f7b3f4.png)

Happen only if i using *_itemLabel *_ directly.

On the workaround to put is in separate "custom" column
`
<p:column>
        <h:outputText value="#{specialty.label}"/>
</p:column>
`
the highlight functionality get lost.

Used prime-faces version 5.3.5

**Comment by tandraschko** [comment]
Works fine in 6.2-SNAPSHOT
If the issue is still there in 6.1 or 6.2-SNAPSHOT, please create new issue with all informations requested by our issue template.
