### ISSUE TITLE
DataTable: Filter getFilteredValue out of sync

### ISSUE THREAD

**Issue by andyfinch** [primefaces/primefaces#1390]
I'm in the the process of updating an old 3.1 Primefaces app.  In this app we make use of the datatable filter ajax event and call a listener to update some backingbean properties.  I've noticed a change of behaviour in this listener.  Previously when this listener ran, either the filieredValue defined list would be updated or the filteredValue from the FilterEvent>getSource would be current.  It would appear now that these are still the old values.  These are effectively 1 step behind the displayed values. 

So we had this nested in a standard filterable datatable

`<p:ajax event="filter" listener="#{MyBackingBean.onFilter}" process="@this" update="@this"/>`

This calls the following method:

```
public void onFilter(FilterEvent filterEvent) {
        List filteredList = ((DataTable)filterEvent.getSource()).getFilteredValue();`
    }
```

On first filter this list will be null.  On second filter it will show the results of the 1st filter and so on.  I have tried this on 5.2._, 5.3._ and 6.0RC3. 

I've also noticed that elements included in the filter update which are placed before the datatable have their getters called prior to the FilterFeature Encode call.  Elements after the datatable have the getters called after the encode.  This doesn't seem correct to me.  I would assume all getters be called after the filter has completed.

**Comment by Nikoas83** [comment]
It seems its the same issue explained in this post : http://forum.primefaces.org/viewtopic.php?f=3&t=44524.

**Comment by andyfinch** [comment]
Problem stems from: 

```
public void processEvent(ComponentSystemEvent event) throws AbortProcessingException {
        super.processEvent(event);
        if (!this.isLazy() && event instanceof PostRestoreStateEvent && (this == event.getComponent()))
        {
            Object filteredValue = this.getFilteredValue();
            if (filteredValue != null)
            {
                this.updateValue(filteredValue);
            }
        }
    }
```

If you remove everything bar the super call then the issue is resolved.  Although what issues this causes I don't know.

**Comment by jxmai** [comment]
Reproduced on the Primefaces 6.x. The filtered values are always a step behind. The `event="filter"` seems like the event before filtering, but there is no `after filtered event`. As a result, doing any business logic on the server side regarding to the filtered List on filter event becomes impossible...

Full sample to reproduce:

**table.xhtml**

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head>
</h:head>

<h:body>
        <h:form>
            <p:commandButton actionListener="#{tableBean.init()}" update=":tableForm" value="reload" oncomplete="PF('tableWidget').filter();"></p:commandButton>
        </h:form>

        <h:form id="tableForm">
            <p:dataTable value="#{tableBean.persons}" 
                        id="persons"
                        widgetVar="tableWidget"
                        filteredValue="#{tableBean.filterPersons}"
                        var="person">
                        
                <p:ajax event="filter" listener="#{tableBean.filterListener}"></p:ajax>
                
                <f:facet name="header">
                        Bug Report 
                </f:facet>

                <p:column headerText="Name" filterBy="#{person.name}" filterMatchMode="contains" footerText="contains">
                    <h:outputText value="#{person.name}" />
                </p:column>
            </p:dataTable>
        </h:form>

</h:body>
</html>
```

**tableBean.java**

```java
package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.component.datatable.DataTable;
import org.primefaces.event.data.FilterEvent;

@ManagedBean(name = "tableBean")
@ViewScoped
public class TableBean implements Serializable {

    private List<Person> persons = new ArrayList<Person>();

    private List<Person> filterPersons;

    private static final long serialVersionUID = -2848956414992723911L;

    @PostConstruct
    public void init() {
        persons.clear();

        Person person1;
        Person person2;
        Person person3;
        person1 = new Person("Person 1");
        person2 = new Person("Person 2");
        person3 = new Person("Person 3");

        this.getPersons().add(person1);
        this.getPersons().add(person2);
        this.getPersons().add(person3);
    }

    public void filterListener(FilterEvent filterEvent) {
        DataTable dataTable = (DataTable) filterEvent.getSource();
        dataTable.getFilteredValue();
    }

    public List<Person> getPersons() {
        return persons;
    }

    public void setPersons(List<Person> persons) {
        this.persons = persons;
    }

    public List<Person> getFilterPersons() {
        return filterPersons;
    }

    public void setFilterPersons(List<Person> filterPersons) {
        this.filterPersons = filterPersons;
    }

}
```

**Person.java**

```java
package org.primefaces.test;
import java.io.Serializable;

public class Person implements Serializable {

    private static final long serialVersionUID = 8742265431595759127L;

    private String name;

    public Person() {
        super();
    }

    public Person(String name) {
        super();
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
```

---

Steps to reproduce:

Initial Screenshot

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/22074995/ea31a4fa-dd6f-11e6-8dcd-d80731ef9161.png)



1. Put a break point on `dataTable.getFilteredValue();` within `filterListener(FilterEvent filterEvent)`

2. Type `1` in the filter under `Name` header

an AJAX Form request has been made observed by browser:

```
javax.faces.partial.ajax:true
javax.faces.source:tableForm:persons
javax.faces.partial.execute:tableForm:persons
javax.faces.partial.render:tableForm:persons
javax.faces.behavior.event:filter
javax.faces.partial.event:filter
tableForm:persons_filtering:true
tableForm:persons_encodeFeature:true
tableForm:tableForm
tableForm:persons:j_idt7:filter:1
javax.faces.ViewState:4889762899525618755:8975864767729689253
```


The Breakpoint gets triggered, `dataTable.getFilteredValue() = null`

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/22075194/a2a3e8fe-dd70-11e6-85e2-85067ad98ca4.png)

3. Let the code continue to run:

AJAX Response (The list after filtered):

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1">
	<changes>
		<update id="tableForm:persons"><![CDATA[
			<tr class="ui-widget-content ui-datatable-even" data-ri="0" role="row">
				<td role="gridcell">Person 1</td></tr>]]></update>
		<update id="j_id1:javax.faces.ViewState:0"><![CDATA[4889762899525618755:8975864767729689253]]></update>
	</changes>
</partial-response>
```

**We cannot obtain the listed after filtered although the ajax response is correct.**

Is it a bug or the expected behavior ? 

1. If it is the expected behavior, would it be nice to add a `event=afterFiltered` callback ?
2. If it is a bug, it is a showstopper since filteredValue cannot be obtained in time.

**Comment by nirodg** [comment]
I ran into the same issue and I got it running with the next workaround


```xhtml
<p:remoteCommand name="updateFilteredValue" update="dataTable:resultCount"/>		

<p:dataTable 
	id="dataTable" 
	value="#{myBean.values}"
	filteredValue="#{myBean.filtered}">

	<p:ajax event="filter" oncomplete="updateFilteredValue();" />

	<f:facet name="header">
		<h:outputText id="resultCount" value="#{myBean.filtered.size()} / #{myBean.values.size()} " />
	</f:facet>

	<!-- here my columns -->

</p:dataTable>
```

**Comment by jhalskov** [comment]
Fantastic! This problem really bothered me for a long time. This solution works!

**Comment by ptaucher** [comment]
Adding a custom filtering mechanism using the event="filter" is then not possible it seems, as the component internal filter will be applied after the 'filter' event. So like jxmai already said earlie: Another event 'afterFiltered' would be great. Currently that's some kind of show stopper.

**Comment by melloware** [comment]
A PR to fix the issue or add the new afterFilter event would be great!

**Comment by gbrinkmann** [comment]
> 
> 
> Fantastic! This problem really bothered me for a long time. This solution works!

Same goes for me, now I can update a details panel AFTER filtering.
One [select drink] for @nirodg please.

**Comment by christophs78** [comment]
Created a integration - test for this. Think this our only chance to get quality-issues under control. Reproducer-ZIPs attached to issues are nice but are only limited useful for avoiding regressions.

**Comment by Rapster** [comment]
I'll work on this, I think I have a few clues of what's going on. Meantime, I think #5481 and #6296 can be closed (it's more or less related to this)

**Comment by Rapster** [comment]
I made a PR (still a draft, requires a bit more testing) but removing `Datatable#processEvent` method didn't help. I think this issue has been there for a while... FYI, same issue with sort event being out of sync

**Comment by melloware** [comment]
I just uncommented the integration test for this and running it now:
https://github.com/primefaces-extensions/primefaces-integration-tests/commit/11b9b9ad6e43529fe9a5a7587d98e8485e74e94f

**Comment by melloware** [comment]
All tests passing!  great job @Rapster @christophs78 

https://github.com/primefaces-extensions/primefaces-integration-tests/actions/runs/402897263

**Comment by Rapster** [comment]
Thanks everyone!
