### ISSUE TITLE
Form submit causes ReferenceError: Can't find variable: PrimeFaces

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#1391]
With 6.0.RC3 I cannot submit a rather dynamic form (a lot of `ui:include`s) without getting the javascript error `ReferenceError: Can't find variable: PrimeFaces` after the submit anymore. I just tested a more static one, which worked. The result is, that the components don't function anymore, e.g. checkboxes won't check. The error is triggered by `components.js` and additionally `inputnumber.js`, if there is a `p:inputNumber`, but the source probably lies elsewhere.

I currently haven't got the time to narrow it down and produce a minimal example, but I will try after monday the coming week.
**This doesn't happen in RC2**, if I downgrade, everything works as intended.

**Comment by tandraschko** [comment]
Please provide a simple maven/jetty application, can't replicate it.

**Comment by zhedar** [comment]
Will try do deliver, the part that broke is overly complex and dependent, so I'm trying to simplify it.
In the meantime I narrowed the source down to dd008bf9b68b81300337f1ea41d1eaf6b848b2d1. That's the change that broke the behaviour.

**Comment by tandraschko** [comment]
Did you also active the METADATA_TRANSFORMER in the web.xml?

**Comment by zhedar** [comment]
No, I haven't changed the web.xml since. I couldn't find a discussion mentioning that, anything I should try?

**Comment by zhedar** [comment]
I still don't know why it happened in specific cases only, but I had `<h:outputScript library="javax.faces" name="jsf.js" target="head" />` included in my `<h:body`>, that somehow broke it. I thought, I would need that for the Ajax Status, but it seems to work without (should be included automatically, but back then I probably had problems with that).

Removing that include seems to solve the problem for now.

**Comment by tandraschko** [comment]
So please reopen if you can provbide a example.
