### ISSUE TITLE
p:rating doesn't align to its parent if not placed inside h:panelGrid

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#1392]
I noticed, that `p:rating` is not fitting into its parent, if the parent is something else than a `h:panelGrid`. `p:panelGrid` doesn't work as well, it won't render the rating inside the `table`. Atleast it doesn't in the bootstrap theme (haven't tried other themes yet).

I think this worked in 5.3 and stopped with 6.0, but I'm actually not 100% sure about that anymore.

Preview:
![bildschirmfoto 2016-05-08 um 16 17 56](https://cloud.githubusercontent.com/assets/6633403/15098278/897d3dee-1539-11e6-9d3e-70e9ec7b8a12.png)

Example code:

```
<p:panel header="This is in a panel">
    <p:rating id="rating" value="#{value}" label="#{name}"/>
</p:panel>

<p:panel header="h:Panelgrid">
     <h:panelGrid>
        <p:rating id="rating" value="#{value}" label="#{name}"/>
     </h:panelGrid>
</p:panel>
<p:panel header="p:Panelgrid">
    <p:panelGrid>
        <p:rating id="rating" value="#{value}" label="#{name}"/>
    </p:panelGrid>
</p:panel>
```

**Comment by husnutapan** [comment]
maybe you can use to panel style attribute use as
`<p:panel header="This is in a panel" style="height: 100px;">
                <p:rating id="rating1" value="3" label="aa"/>
            </p:panel>
`
and you can view

http://stackoverflow.com/questions/16807107/how-to-center-align-prating

**Comment by michael-las** [comment]
Seems to work, if the stars are styled as non-floating inline-blocks. PR is here #1532.
