### ISSUE TITLE
DataTable: rows per page dropdown doesn't validate submitted value

### ISSUE THREAD

**Issue by BalusC** [primefaces/primefaces#1394]
An attacker could this way submit an arbitrary large value such as 1000000 and cause the server to run out of memory when executed on a paginated lazy data table with a big database.

**Comment by tandraschko** [comment]
@BalusC Could you please provide a patch or PR?

**Comment by melloware** [comment]
Closing as this was fixed with this ticket: https://github.com/primefaces/primefaces/issues/3519
