### ISSUE TITLE
p:notificationbar show/hide delegates false options to JQuery functions.

### ISSUE THREAD

**Issue by mdaehnert** [primefaces/primefaces#1395]
Hi there,

I wanted to inform you, that the following functions of notificationbar.js:
- show
- hide

delegates to JQuery functions:
- slideDown
- fadeIn
- slideUp
- fadeOut

with arguments like:
- slide
- fade

But all of the named JQuery functions use their first parameter for other functionality (mostly duration).
E.g. @see http://api.jquery.com/slidedown/

**Comment by tandraschko** [comment]
Whats the exact issue?
#show is only called in #toggle and without parameters.

**Comment by mdaehnert** [comment]
I'm sorry; I addressed two issues in one cryptic post. Let me be more concrete:
1. There are wrong parameters for calls of jQueries methods #slideDown, #fadeIn, #show as well as #slideUp, #fadeOut and #hide
2. PrimeFaces methods #toggle, #show and #hide can be enhanced with jQueries used parameters.

**# 1.**
I created a pull request for fixing the issue, that PrimeFaces gives jQuery an unused parameter.
Like this: `$(this.jq).slideDown(this.cfg.effect);`
In this case PrimeFacees holds the value `this.cfg.effect="slide"`, which isn't interpreted by jQuery.

Please look at these three docs for further informations on possible jQuery parameters:
- http://api.jquery.com/slidedown/
- http://api.jquery.com/fadein/
- http://api.jquery.com/show/

Currently my pull request only updates the #show method with these parameters.

**# 2.**
On the other hand, you're right. Atm #toggle can't be called with arguments too. Therefore I would recommend to have all three methods #show, #hide and #toggle with the three optional jQuery parameters.

Let me know, if you're interested in having these three PrimeFaces methods extended with three optional jQuery parameters to allow a more specific experience on showing and hiding the notificationbar.
