### ISSUE TITLE
What taglib should I use?

### ISSUE THREAD

**Issue by douglasjunior** [primefaces/primefaces#14]
I am getting the message:

** Warning: This page calls for XML namespace http://primefaces.org/ui declared with prefix p but no taglibrary exists for that namespace.

**Comment by brunolmfg** [comment]
The taglib namespace is correct, it's the same of official distribution. Maybe you've a problem with your JSF version or you made a mistake with your namespace definitions and the global namespace, if you use. See [this stackoverflow question](http://stackoverflow.com/questions/5177964/warning-this-page-calls-for-xml-namespace-declared-with-prefix-tagname-but-no).

**Comment by douglasjunior** [comment]
I am using the official version 5.1, and the taglib was suggested by Netbeans. Works perfectly.

But when I add the unofficial version 5.1.3, I get this error.

**Comment by brunolmfg** [comment]
The showcase is working fine with 5.1.3-UR and I checked several components. All of my projects are working fine too. I can't help you without more details.

**Comment by douglasjunior** [comment]
Ok, thank you.

Just curious, how would reference the unofficial version 5.1.3 with Maven?

For now I gave up using version 5.1.3. My intention is to use <p: column visible = "false">.

**Comment by brunolmfg** [comment]
Add the unofficial repository in your project repositories:

```xml
<repository>
    <id>prime-github-repo</id>
    <name>Unofficial PrimeFaces Maven Repository</name>
    <url>http://primefaces.github.io/repository</url>
    <layout>default</layout>
</repository>
```
And add the dependency:

```xml
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>5.1.3-UR</version>
</dependency>
```

The version has the suffix `-UR` for don't collide with the officials artifacts, if you acquire the license Elite someday.

With this additional question I need to ask you. You checked if the dependency is resolved correctly? Maybe the dependency is not present in the classpath, for some reason like the incorrect version. ;-)

**Comment by douglasjunior** [comment]
I had installed the jar manually. I will test the way you suggested.

**Comment by douglasjunior** [comment]
Now worked perfectly. Thanks for your help. Congratulations on your initiative.

**Comment by brunolmfg** [comment]
You're welcome!
