### ISSUE TITLE
Sticky header is broken when used with scrollable data

### ISSUE THREAD

**Issue by spauny** [primefaces/primefaces#1400]
Sticky header is broken when used with scrollable data: stickyHeader="true" and scrollable="true"
As you can see below, the header is broken even before scrolling down. 

![screen shot 2016-05-10 at 10 46 09](https://cloud.githubusercontent.com/assets/6390470/15142371/9e7eda18-169c-11e6-97fc-8b00ed3fef1c.png)
![screen shot 2016-05-10 at 10 44 47](https://cloud.githubusercontent.com/assets/6390470/15142372/9e814d34-169c-11e6-9c09-d1c188651805.png)

**Comment by spauny** [comment]
Also, when stickyHeader and scrollable are true, it would be nice to have the fixed header still follow the vertical scroll.

**Comment by melloware** [comment]
I had reported this as a PRO user and this is the answer I got back from PrimeFaces:  "Scrolling and StickyHeader are not supported since you can enable scrollHeight to get fixed headers. Since functionality is similar, we don't sticky header on scrollable tables."
