### ISSUE TITLE
Memory leak in the p:timeline component

### ISSUE THREAD

**Issue by Fr3eZer** [primefaces/primefaces#1406]
We encountered some memory issues when using the p:timeline component in our web application (dashboard). The memory usage of the browser keeps growing until after a while, the browser of our client crashes. 

We did some testing and it appears that this only happens when updating the timeline periodically on the client-side. Every update the memory usage grows, and even if we manually activate garbage-collects it does not ever shrink.

To simply reproduce the problem we can take the timeline example in the ShowCase and make the following changes:

**Create a big amount of data, so we don't have to wait too long. Replace the PostConstruct of the example in the showcase with the following code:**

```
@PostConstruct
protected void initialize() {
    model = new TimelineModel();

    Calendar cal = Calendar.getInstance();
    for (int i = 1; i < 1000; i++) {
        int randomMonth = (int)(Math.random() * 12);
        int randomDay = 1 + (int)(Math.random() * 28);
        int randomHourOfDay = 1 + (int)(Math.random() * 20);
        cal.set(2016, randomMonth, randomDay, randomHourOfDay, 0, 0);
        model.add(new TimelineEvent(randomMonth + "-" + randomDay + "-" + randomHourOfDay, cal.getTime()));
     }
 }
```

**Add a poll to the .xhtml page, it updates the timeline every second (again, we set this relatively fast so we don't have to wait too long**

```
<h:form>
    <p:poll interval="1"  update="timeline" />
</h:form>
```

After a couple of minutes my "about:memory" page in FireFox says the page the timeline is on uses 10+ GB of memory

**Comment by mertsincan** [comment]
Thanks for your sample codes. I'll check it and get back to you.

**Comment by sergi-mm** [comment]
We experience the same issue using timeline component. When lots of events are loaded in timeline, the browser crashes with a javascript error.

![javascript_error](https://cloud.githubusercontent.com/assets/9212820/18505037/938fa8d0-7a65-11e6-827b-ea1e03d017eb.png)

This error is more likely to occurs when using Firefox browser. It seems that Chrome browser supports better lots of javascript objects.

**Comment by sergi-mm** [comment]
Hi @mertsincan, I've added a pull request to fix this issue just now. Please take a look at Pull Request #2255 . 

Thanks.
