### ISSUE TITLE
Photocam ERROR 

### ISSUE THREAD

**Issue by JorgJimz** [primefaces/primefaces#1408]
Hi everyone,

I've got a problem with primefaces's photocam plugin, I'm using Primefaces 5.0 and Javax.faces 2.2.6, It takes a photo but when I have to update to show the taken picture, in the console appears this message:

**Uncaught TypeError: Cannot read property 'call' of undefined**

![image](https://cloud.githubusercontent.com/assets/3695179/15188418/51b23354-176b-11e6-8c7c-f736b0a40578.png)

What am I doing wrong?

Greetings.

**Comment by JorgJimz** [comment]
The taken picture is saved correctly. But can't show in a Graphic-Image tag.

**Comment by tandraschko** [comment]
Try 6.0.RC4

**Comment by JorgJimz** [comment]
I'm new at using Primefaces ... I understand that you refer to Primefaces version 6.0 RC4 ... but I think that version is for PRO User and I'm not. Another solution or maybe I'm still wrong?

**Comment by tandraschko** [comment]
no, it's not for PRO users, it's just the RC for the upcoming community version. See: http://repository.primefaces.org/

**Comment by JorgJimz** [comment]
Thanks, @tandraschko ... Your answer fixed my problem. It was about the version of Primefaces I had to have the last version of it. 

Thanks again,
Greeting from Perú.

**Comment by tandraschko** [comment]
Great!
