### ISSUE TITLE
p:inputNumber and accesskey doesn't work as expected

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#1409]
Normal behaviour of browser when jumping into an input field via accesskey (or tab key) is to select the current input so that the user can replace it by new input by just typing, and p:inputNumber should behave in the same way, but it doesn't.

I have an XHTML file where I use p:outputLabel and p:inputNumber together and the p:outputLabel defines the accesskey for the inputNumber field:

&lt;p:outputLabel for="in1" value="..." accesskey="I"/&gt;
&lt;p:inputNumber id="in1" value="..."/&gt;

When I hit the access key 'I' the focus is set to the inputNumber (as expected) and for a very short time the current value of the inputNumber field is selected (as expected too) but this selection of the characters of the inputNumber is lost after some milliseconds.

I have searched for the reason and found following code in inputnumber.js (which comes from autoNumeric.js) which causes this loosing of the text selection:

formatQuick: function () {
   ...
   this.that.value = value;
   this.setPosition(position);
   this.formatted = true;
}

A solution might be to check if the new value is the same as the current value and to omit this assignment in that case. I have tested following fix:

```
if (this.that.value !== value) {
    this.that.value = value;
    this.setPosition(position);
}
this.formatted = true;
```

and it solved this issue.

Would it be possible to include a patch for it into the upcoming PrimeFaces 6.0?

**Comment by tandraschko** [comment]
AFAICS the bug is directly in autonumeric?

**Comment by movalz** [comment]
Yes, it is directly autonumeric. I have updated the description above: I have tested a fix: putting the two statements which causes loosing the selection into an if statement and that seems to work. What is the best way to get this fix into autonumeric and then into PrimeFaces?

**Comment by tandraschko** [comment]
Please create a issue on autonumeric side. If they release a new version, we can update it.

**Comment by tandraschko** [comment]
Feel free to come back if they fixed and released it.
