### ISSUE TITLE
Attribute "maxlength" not working for inputtext of type="number"

### ISSUE THREAD

**Issue by leolux** [primefaces/primefaces#1410]
The attribute maxlength seems to work only for inputtext fields of default type. The following inputtext is of type "number" and does not work as expected:

<p:inputText type="number" maxlength="3" id="mynumber" value="#{someBean.mynumber}" />

I am using the current community version 5.3 from the download section.

**Comment by leolux** [comment]
I just saw that that version 5.3.4 introduces InputNumber which is made especially for numbers. Do you think that the issue within InputText of type="number" is still relevant as long as the community can only download version 5.3?

**Comment by tandraschko** [comment]
Not related to PF: http://stackoverflow.com/questions/34150134/maxlength-is-not-working-with-input-type-number-in-html-textbox

**Comment by leolux** [comment]
Well, the primefaces documentation does not state that the attribute "maxlength" does not work for input type number. The fact that HTML does not know about this attribute has nothing todo with the attribute itself because it is a attribute defined by primefaces and specified as follows:
"Maximum number of characters that may be entered in this field."

So if you say this attribute works as expected then the issue is the documentation.
