### ISSUE TITLE
Problem with new contribution

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1411]
Hello,
I'm new to this community and I want to contribute with my knowledge of GoogleMaps to improve this tool, but I find the problem that some classes to which I have access in the jar downloaded from maven (PrimeFaces-5.3.jar) and these are not in this repository GitHub, so I can not change. An example of the classes to which I refer are GMap.java, AjaxStatus.java, etc.

Where are these classes?

**Comment by tandraschko** [comment]
That's not an issue, use the forum.
They are auto generated and the templates are in /src/main/java-templates

**Comment by tandraschko** [comment]
That's not an issue, use the forum.
They are auto generated and the templates are in /src/main/java-templates
