### ISSUE TITLE
p:message style and styleClass ignored

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#1414]
PF 5.3
The attributes style and styleClass are ignored by the p:message renderer.
To reproduce I simply added style and styleClass attributes to one of the p:message in the Messages page of the showcase. Neither style nor styleClass are present in the generated xhtml. Instead p:messages behaves correctly.
I investigated and the attributes are not rendered because they are simply not read in org.primefaces.component.message.MessageRenderer

**Comment by tandraschko** [comment]
would be great if you could provide a PR

**Comment by NicolaIsotta** [comment]
Created: #1423

**Comment by tandraschko** [comment]
Merged! Thanks!
