### ISSUE TITLE
activePageIndex for dataTable

### ISSUE THREAD

**Issue by gbrinkmann** [primefaces/primefaces#1415]
An attribute "activePageIndex" for "dataTable" (like "activeTabIndex" for tabView) would be nice, for example (my case) to restore a dataTable page when returning to the browser page that contains the dataTable.

And - just in case nobody mentioned it so far - primefaces rocks :-)

**Comment by cnsgithub** [comment]
Hi, this would be a really useful addition. Until this is implemented i solved this by using JS.

`
PF('dataTableWidgetVar').getPaginator().setPage(#{bean.pageToShow});
`

**Comment by michael-las** [comment]
What's wrong with attribute 'first' of p:dataTable?

**Comment by cnsgithub** [comment]
the first attribute doesn't specify the page, but the first row i think, so some calculations have to be done to determine the page, also i think it had some problems with filtering and if the filterValue is "remembered" it doesnt work in combination with it. (e.g. user had filtered for "smith" then clicks on page4), you restore it with first + filterValue from bean -> it doesnt work / isnt in sync

**Comment by michael-las** [comment]
Yes, according to the documentation, 'first' is the index of the first row to be displayed. From what I've seen, the component automatically displays the corresponding page. Since the row index is more accurate than the page index, it gives greater flexibility, e. g. one can use 'first' with tables having no paginator. Having both, 'first' and 'activePageIx' attributes, is not a good idea since they depend on each other. Otherwise one could do things like 'first="0" activePageIx="10"' which could lead to unpredictable results. Also, I don't think that existing problems can be solved by adding a new attribute which functionally depends on an existing one.

**Comment by gbrinkmann** [comment]
Ok, for me the topic is just an "automatic restauration of the current dataTable page".

So for me it is not relevant if this could result in an "activePageIndex" or an "activeFirstIndex" or an "activeRowIndex".

The behaviour should just be like when using "activeTabIndex" for tabView: You return to a dataTable browser page and your (correctly scoped) bean member defines the page to be shown without having to do anything else manually.

Can I and should I edit this issue and it's title?

**Comment by michael-las** [comment]
Try the following:
1. introduce a rowIndex property (int) in your bean.
2. include a viewParam in your page, e. g.
  `<f:metadata><f:viewParam name="ix" value="#{bean.rowIndex}" /></f:metadata>`
3. use the first parameter in your dataTable and set the number of rows per page to 10, e. g.
`<p:dataTable rows="10" first="#{bean.rowIndex}" ... />`
4. open your page with query parameter ?ix=20
5. dataTable should show page number 3.

**Comment by gbrinkmann** [comment]
Ok, thank you very much for a smart workaround, I'll test it.
On the other hand an automatic handling just like "activeTabIndex" would be nice, wouldn't it? :-)

**Comment by michael-las** [comment]
It's like activeTabIndex: activeTabIndex="#{bean.tabIndex}" vs. first="#{bean.rowIndex}". No difference, here. I included the viewParam above only to be able to open the page with parameter "ix=". You don't need to use a viewParam at all.

**Comment by cnsgithub** [comment]
Anyway a possibility to restore the datatable to it's exact stage including:  filterBy values, sortBy order, and page is very desirable. And it should work after ajax request & update on table too.

**Comment by michael-las** [comment]
Absolutely.

**Comment by gbrinkmann** [comment]
Ok, thank you both.
Strange thing: The workaround doesn't work for me.
No urgent need to fix it, no showstopper, just in case you're interested:
I'm passing the member as a composite parameter and use it as "first="#{cc.attrs.first}"" (3 tabs in a tabview each contain a dataTable from a custom xhtml composite, separate form per dataTable). The bean is session scoped and holds the 3 "first" members.
The problem:
The member is not updated when I click another page in the paginator, the initial zero value doesn't change.

**Comment by michael-las** [comment]
I've attached an archive that contains one Java file and one XHTML file. Could you please try it with them?

[dttest.zip](https://github.com/primefaces/primefaces/files/293618/dttest.zip)

**Comment by gbrinkmann** [comment]
Thank you, it works and I've identified my coding mistake (resetting the member value).

**Comment by michael-las** [comment]
Fine.

**Comment by Rapster** [comment]
Fixed by a41cdcebcc53551a258cefa50858006febc43f8b

**Comment by erickdeoliveiraleal** [comment]
if it is fixed should be closed, no?
