### ISSUE TITLE
DataTable: changes mouse cursor on selected rows even when rowSelectMode="checkbox"

### ISSUE THREAD

**Issue by rripley** [primefaces/primefaces#1417]
In `p:dataTable`, when `rowSelectMode="checkbox"`, the mouse cursor changes to pointer on selected rows, because of `.ui-datatable tr.ui-state-highlight{cursor:pointer;}` in components.css.  The expectation would be that the mouse cursor would remain unchanged because clicking the row has no action when rowSelectMode is checkbox.  I am using 6.0.RC3.

**Comment by melloware** [comment]
This now properly selects the checkbox when you click on a row as of PF 7.0 so this was fixed a while ago.
