### ISSUE TITLE
DataTable: responsive - weird displaying of sortBy

### ISSUE THREAD

**Issue by nasir-imtiaz** [primefaces/primefaces#1422]
I am using a very basic example of responsive data table as follows:

```
<p:dataTable value="#{personManagedBean.personList}" var="person" reflow="true">
  <p:column sortBy="#{person.firstName}" headerText="First Name">
    #{person.firstName}
  </p:column>
  <p:column sortBy="#{person.lastName}" headerText="Last Name">
    #{person.lastName}
  </p:column>
</p:dataTable>
```

The issue is that, once i make a column sortable by using the sortBy attribute, an extra drop down starts appearing on top of the data table for the respective column (as shown in the attached image).

![image](https://cloud.githubusercontent.com/assets/19385959/15285648/386b83b0-1b61-11e6-8d98-3c69cd8b6018.png)

I realize that this behavior is coming because i have made the data table responsive, but ideally it should appear only when the screen size is minimized enough that the responsiveness of the UI is active i.e. when the layout of data table's columns changes and becomes stacked. It should not appear in all cases.

Please suggest if there is a way to achieve the required behavior. Thanks.

P.S. I have tried it with bare minimum in an empty page with only p:dataTable component inside it. Also, checked the css and no css changes noticed while squeezing the screen to and fro.

**Environment:**
Primefaces version: 5.3.11
JSF version: 2.2
Browser: Firefox 45.0.2, Chrome 50.0.2661.94 m

**Comment by tandraschko** [comment]
Works fine for me in trunk
