### ISSUE TITLE
Empty parameter value rendering

### ISSUE THREAD

**Issue by aleskurlovich** [primefaces/primefaces#1424]
Hello. I found problem with empty f:param value rendering. For example, next code will initiate HTTP request with additional form data.

Code:
`<p:commandLink...> <f:param name="param" value="#{null}"/> </p:commandLink>`

Request data:
`param: null`

But I guess "param" value should be empty at least.

Possible fix: #1419

**Comment by tandraschko** [comment]
Thanks!
