### ISSUE TITLE
p:selectOneRadio and an accesskey defined via a p:outputLabel doesn't work as expected

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#1430]
I have a p:outputLabel with an accesskey defined. The label belongs to a p:selectOneRadio (via a for="..."). When I hit the accesskey of the label I would expect that the currently selected option of the selectOneRadio would get focus, so that I can switch between the options with the cursor keys (like I can do when focussing the selectOneRadio via Tab key). But what happens is that the currently focussed element looses its focus but the p:selectOneRadio doesn't get the focus. I have tested both options for attribute `plain`(true/false) with the same result. Attribute `layout`is set to 'lineDirection'.

Inspecting the rendered HTML output shows the reason: the label has following HTML code:

`<label class="ui-outputlabel ui-widget" id="label_phoneType" accesskey="T" for="ctrl_phoneType"><span class="iplAccessKey">T</span>ype</label>`

and the p:selectOneRadio creates following HTML code:

```
<table class="ui-selectoneradio ui-selectoneradio-native ui-widget" id="ctrl_phoneType" role="presentation">
  <tbody>
    <tr>
      <td>
        ...
      </td>
    </tr>
  </tbody>
</table>
```

So the `for` attribute of the label points to the `table` element and not to an input field.

Solution might be to render a hidden input field with an id used by the p:outputLabel's `for` attribute which has an onfocus handler which gives the currently selected option the focus.

I have tested it with IE11, Firefox and Chrome. I'm using PrimeFaces 6.0-RC3

**Comment by Rapster** [comment]
Your use case scenario is not valid, it does not work that way. First, it's by cliking on the radio label that associated radio button get set and has focus. It works correctly in the showcase. Secondly, in pure HTML, you'd have to define an accessKey for each button radio so you can get the behavior that I've just described. It means, `javax.faces.model.SelectItem` should support `accessKey` which does not :/

**Comment by Rapster** [comment]
What do you think @tandraschko? Does it require to open a ticket in Mojarra issue tracker like you did for #1493 ?

**Comment by movalz** [comment]
you are right, it would be fine if javax.faces.model.SelectItem would have accessKey support. But often you don't want to define an accessKey for every single item of the radio button group but it would be nice to define a single accessKey for the whole group which behaves like I have described above. Wouldn't my suggested solution be a good approach to make this possible?

**Comment by tandraschko** [comment]
I like the idea of @movalz - just have not much time to think about an implementation.

**Comment by tandraschko** [comment]
passthrough attributes should work here: https://stackoverflow.com/questions/29671305/using-fselectitems-var-in-passtrough-attribute
