### ISSUE TITLE
LayoutUnit - update a single layoutunit doesn't work

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#1434]
I have the following situation

```
 <p:layout fullPage="true">
                <p:layoutUnit position="north" size="100">
                    ...
                </p:layoutUnit>

                <p:layoutUnit position="center" id="mainUnit">
                    <ui:include src="#{myBean.myView}"/>
                </p:layoutUnit>
            </p:layout>
```

myView is an xhtml page (view1.xhtml, view2.xhtml,....). In view1.xhtml I have another layout:

```
                    <p:layout>
                        <p:layoutUnit position="west" size="200">
                            ...
                        </p:layoutUnit>

                        <p:layoutUnit position="center">
                            ...
                        </p:layoutUnit>
                    </p:layout>
```

If I "switch" from view1.xhtml to view2.xhtml (using an actionlistener of a button), and than I do an ajax update of the layoutUnit "mainUnit" this doesn't work correctly (the layout is "out-of-phase"). If I do a page refresh everything is ok.

If I put the nested layout in a panel it is not correctly visualized.

**Comment by tandraschko** [comment]
Please try the rendered attribute instead c:if.
JSTL doesn't work in every case.

**Comment by crocimi** [comment]
Thx 4 the answer, I have updated the issue because my situation was a little different (sorry for that)

**Comment by tandraschko** [comment]
Confirmed - workaround here: https://stackoverflow.com/questions/18913547/how-to-update-a-layoutunit-in-primefaces

**Comment by tandraschko** [comment]
This won't work as the layout script needs to be executed to realign the units.
Will close it as won'tfix for now. It think the workaround is quite good.
