### ISSUE TITLE
Inplace: default mode support 

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1437]
It should be possible to indicate in which "mode" inplace component should be displayed first. There would be two mode so far: input or output. AFAIK, "output" mode is displayed first, but what if user want it to display in "input" (editing) mode first? Inplace is more than just a fancy way to edit value, technically, it allows to associate a display and an editing mode in a very fancy way. In a dyna form, it would write:

```
<p:inplace mode="#{!formField.readonly ? 'input' : 'output'} disabled="#{formField.readonly}">
    <f:facet name="output">
        Yes or No
    </f:facet>
    <f:facet name="input">
        <h:selectBooleanCheckbox />
    </f:facet>
</p:inplace>
```

I can provide a fix if you're okay with that

**Comment by tandraschko** [comment]
+1

**Comment by tandraschko** [comment]
PR or not interested anymore?

**Comment by Rapster** [comment]
Don't have time for this one

**Comment by Rapster** [comment]
@tandraschko I might need to work on this one actually. But I can't figure out what's the attribute name should be actually. There is two use case so far as I can see...:

Basic mode:
```
<p:inplace id="basic">
    <p:inputText value="Edit Me" />
</p:inplace>
```

Facet mode:
```
<p:inplace id="facet" effect="none">
    <f:facet name="output">
         Yes or No
    </f:facet>
    <f:facet name="input">
         <h:selectBooleanCheckbox />
    </f:facet>
</p:inplace>
```

I'd like to cover those 2 use case scenario with one attribute... With facets, it's easy (e.g `mode="input|output"`), but should I use `content` and `display` as keyword for basic scenario (`display` being default value) or reuse `input|output`? I thought about `content` and `display` because of this use case where there is no input
```
<p:inplace id="image" label="Show" effect="slide">
    <p:graphicImage name="/demo/images/nature/nature3.jpg" />
</p:inplace>

```
Let me know what you think

**Comment by Rapster** [comment]
I realized `input` and `ouptut` facet are predefined name... So `output `= `display `and `input `= `content`. I think I should reuse `content` and `display` as keyword

**Comment by tandraschko** [comment]
I think we should implement like the activeIndex in the accordion. If the clientSide switches the mode and p:ajax is registered, the mode will be written back to the "mode" expression. If it's updated on the ajax, the mode will be the same again as in the bean. With this option you could also set an initial mode.

**Comment by tandraschko** [comment]
I don't have time for it, too as there are issues with much more prio for me.

I would call the attribute "mode", which represents an ValueExpression.
On rendering we should get the value there and decide if input or output is the first facet to show.
When switching the mode, i would fire an ajax request (only if there is a behavior registered for and "mode" is defined) and write the new mode back to the "mode".
So the "mode" value-expression always synchronizes with the client state.

**Comment by melloware** [comment]
@rapster you never submitted this PR but you still have an open branch. Still interested in submitting it?

**Comment by tandraschko** [comment]
commited a simple version without "mode" event and write back to VE. I think thats ok for now.

@melloware please review and maybe you can add a showcase example with validation failed.

**Comment by melloware** [comment]
I will add a showcase example now.

**Comment by Rapster** [comment]
Turns out my fix was good enough back then 😅

**Comment by melloware** [comment]
@tandraschko I see you already added a Showcase example.  Great work!

**Comment by tandraschko** [comment]
yep but not for the "validation failed" example

yeah, i just wanted to have it better but i would like to have less open tickets
we can enhance it later if someone would like to send the mode back to the server
