### ISSUE TITLE
Captcha: Allow multiple captcha on same page

### ISSUE THREAD

**Issue by wodarski** [primefaces/primefaces#1438]
Improve p:captcha to allow multiple components on same page.

Acording to [1], multiple recatpchas on same page is supported in Recaptcha Version 2.0

[1] http://stackoverflow.com/questions/1241947/how-do-i-show-multiple-recaptchas-on-a-single-page

**Comment by tandraschko** [comment]
Feel free to provide a pull request.

**Comment by tandraschko** [comment]
We are on V2 - please gie it a try. If it doesn't work, please create a new issue with all informations requested by the issue template.
