### ISSUE TITLE
Bad encoding Rectangles Map

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1440]
In class GMapRenderer the attribute bound in renctagle component is wrong

![image](https://cloud.githubusercontent.com/assets/8562436/15414724/ec6ba3e2-1e02-11e6-8a47-efcb64449a59.png)

And in the Google Maps documentation [https://developers.google.com/maps/documentation/javascript/3.exp/reference?hl=es#LatLngBounds] is first  the value sw and then ne

![image](https://cloud.githubusercontent.com/assets/8562436/15414754/20bb5dae-1e03-11e6-8062-612a5e32adcc.png)

**Comment by JaviRpo** [comment]
#1441

**Comment by tandraschko** [comment]
good catch, thanks!
Will also add it to the migration as it breaks old applications
