### ISSUE TITLE
InputNumber throws JavaScript error when special values like Double.NaN are used

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#1444]
When I switched from PrimeFaces Extensions to PF6's InputNumber I recognized, that a page containing  a `p:inputNumber` stopped working, because of an autonumeric error:
`Error: The value (�) being 'set' is not numeric and has caused a error to be thrown`

The workaround for this issue seems to be not using such values, in my case [JSONObject.optDouble](http://www.docjar.com/docs/api/org/json/JSONObject.html#optDouble%28String%29) opted to `Double.NaN`.

Maybe it would be sensible to handle these special values, so this won't happen that often. But I guess, it may apply to `Float.NaN` and others as well.
I would assume, this problem wasn't present in PF Extensions, but I'm not 100% sure about that and didn't check yet.

**Comment by tandraschko** [comment]
Please provide an example. Even better a pull request to fix the problem.

**Comment by zhedar** [comment]
I pushed my minimal example to https://github.com/zhedar/pfissues . It's a bit sloppy and Eclipse didn't like it, but the maven build worked. However, the built war is in there as well, as I haven't bothered to add a real gitignore.

I thought about fixing this as well, but should have a look into the implementation of the inputnumber component first. Handling special cases like this may introduce some ugly code though :/
The second thing I wasn't sure about was the way, how these cases should be handled. More specifically, which values should be the default instead, I currently worked around this by using `BigDecimal` and initializing it with `null`.

**Comment by tandraschko** [comment]
It's just not designed for NaN.
The DoubleConverter returns "NaN" as string and no number.
Will close it as not supported.

**Comment by tandraschko** [comment]
You can however provide an own double converter which converts NaN to a number instead "NaN" as string.
