### ISSUE TITLE
Lazy data components ajax load event

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1447]
In many applications a client callback is required to rebind javascript components or invoke other AJAX requests after a lazy data component load method was called and content was updated.

What about an 'load' ajax event?

```
<p:dataTable>
    <p:ajax event="load" oncomplete="rebindMyStuff();" update=":myId"/>

</p:dataTable>
```

**Use cases:**
- reload other components after lazy load operation
- invoke javascript code after load
- load dynamic resources

Those examples are explained in more detail in post: http://forum.primefaces.org/viewtopic.php?f=3&t=45095#p141153

Current workaround require a second ajax request to update other components.

**Comment by cnsgithub** [comment]
You're right this is something which would ease a lot of things. Currently I'm doing it in the following way: 

<p:ajaxStatus oncomplete="onAjaxComplete();" />

The both methods will check for custom data attribute on components which need an ajax callback, and execute it's value as js by using Function.call

A 'native' Primefaces solution would be a big improvement though

**Comment by tandraschko** [comment]
We can of course introduce a new event BUT catchting this with p:ajax is not good idea as there would be 2 ajax requests.
So i don't like your idea that much.

**Comment by djmj** [comment]
I dont see it as a second `new` event. More like a hook into the lazy load event so that we can use `update` or `oncomplete` or other ajax functionality.

**Comment by tandraschko** [comment]
I can't follow you.
"Lazy load" is probably called by multiple events like filter, sort,page. So "load" is NOT a client behavior, where as filter,sort,page is a client behavior. (Client behavior are events that can be catched with f/p:ajax).

**Comment by djmj** [comment]
It is just an idea. A different description:

_We need `update`, `oncomplete` for the internal lazy load event to update other DOM._

`<p:ajax event="load"` was just an idea on how to solve it. Preferrable with a single ajax request.
`<p:table loadUpdate=":myComponent" loadOncomplete="rebind();">` is also an idea.

The p:ajax, as an idea is just more flexible since it could allow to invoke other bean methods in parallel to the invoke of the lazy load method.

**Comment by tandraschko** [comment]
But you know that filter,sort,page calls "lazy load". So whats the problem to define those 3 events?
If you don't like it, you can still use an composite to wrap the dataTable.

**Comment by djmj** [comment]
Hmm, i must check this 👍

**Comment by tandraschko** [comment]
All right. Will close it for now ;)

**Comment by avinashmoram** [comment]
@djmj  @tandraschko I had similar problem. We call web services from the load method and when the web services returns error messages, they do not get displayed at the top of the page where we show all p:messages. Is there a way to update that p:messages id. Because the existing page event update did not update my p:messages.

**Comment by tandraschko** [comment]
Should work if you define it in the update attribute - but thats something for the forum ;)

**Comment by avinashmoram** [comment]
I posted in the forum, the suggestions didn't help fix the issue.
https://forum.primefaces.org/viewtopic.php?f=3&t=52219
For now I ended up placing my p:messages below p:dataTable which shows me the messages. Looks like the ajax event cannot update any components above it, but can update the components below it.
