### ISSUE TITLE
SelectOneMenu: keyword fast selection with android device (tablet)

### ISSUE THREAD

**Issue by patr-76** [primefaces/primefaces#1448]
With 5.3 version, when we try to selection with keyword letters for a fast selection, the selectOneMenu component  doesn't work correctly in basic example (http://www.primefaces.org/showcase/ui/input/oneMenu.xhtml).

We use a tablet with android os (version lollipop) and Chrome browser.
Otherwise, with a normal pc all right.

Back to 5.1 version all it works correctly.

Thank a lot.

**Comment by tandraschko** [comment]
Could you try it again in the current showcase?

**Comment by melloware** [comment]
It has been a couple of years.  Is this still an issue on the latest showcase and Android versions?

**Comment by melloware** [comment]
@tandraschko @Rapster no response on this ticket, its a few years old and reporting on an old version of Android . I recommend closing it.
