### ISSUE TITLE
Is IterationStatus really necessary to be added?

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1449]
I have an error with eclipse saying that `IterationStatus` is msilocated, it's actually true, the package is set to `com.sun.faces.facelets.tag` while it is in `org.primefaces.component.repeat`. I'm wondering why this file has been added since it's an exact copy of `IterationStatus` in javax.faces. Has it been added for MyFaces? Even though, it does not explain why it has the same package name

**Comment by tandraschko** [comment]
p:repeat has been added because of a bug in mojarra's ui:repeat. MyFaces is working fine.

**Comment by Rapster** [comment]
But still, why add it while it's present in `javax.faces-2.2.0.jar` dependency, it's not possible to use the same?

**Comment by tandraschko** [comment]
1) i can't see a IterationStatus in javax.faces
2) we must also support 2.0 and 2.1

it wasn't my decision to add p:repeat, imo it should be fixed in mojarra since it works in myfaces.

**Comment by Rapster** [comment]
I don't wanna take too much time of you for this, but I'm still curious. If it has to be support in 2.0 and 2.1, why this dependency:

```
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.faces</artifactId>
    <version>2.2.0</version>
    <scope>provided</scope>
</dependency>
```

And this [link](http://www.grepcode.com/file/repo1.maven.org/maven2/org.glassfish/javax.faces/2.2.0/com/sun/faces/facelets/tag/IterationStatus.java/) shows `IterationsStatus` is present in `javax.faces-2.2.0.jar`

**Comment by tandraschko** [comment]
Check the package. It's still "com.sun.faces." and not javax.faces.
So it's only available in the mojarra jsf-api jar.
