### ISSUE TITLE
Checkbox tree node javascript issue

### ISSUE THREAD

**Issue by gcretrogress** [primefaces/primefaces#1452]
I have a check box tree node, when a user selects a particular node, I prompt them with a confirmation dialog with Yes/Cancel buttons. When user submits cancel button I have an action listener in the managed bean that does node.setSelected(false). The tree gets refreshed correctly after the listener completes the action. However when I select some other node on the tree, the first/unselected node from the first step is again selected. I am pretty sure the javascript or primefaces code associated with the event has a bug, it is not able to remove the node that was unselected earlier, somehow it is keeping an older list and passing it back to the managed bean.

**Comment by tandraschko** [comment]
We require more informations to check that issue.
We also introduced a issue template with all required informations. If the issue still persists in the newest version, please create new issue and respect our template.
