### ISSUE TITLE
Calendar should support converters

### ISSUE THREAD

**Issue by andrei-ivanov** [primefaces/primefaces#1453]
We're using Joda time in our app (we're also planning to switch to JSR 310 sometime soon), but the calendar renderer only accepts String or java.util.Date for date the attributes.

javax.faces.FacesException: Value could be either String or java.util.Date   at org.primefaces.component.calendar.CalendarUtils.getValueAsString(CalendarUtils.java:80)   at org.primefaces.component.calendar.CalendarRenderer.encodeScript(CalendarRenderer.java:164) at org.primefaces.component.calendar.CalendarRenderer.encodeEnd(CalendarRenderer.java:64)

Maybe standard JSF converters could be applied for these values?
Otherwise `CalendarUtils.getValueAsString` should be updated to handle these types too.

**Comment by andrei-ivanov** [comment]
Will this also end up in 6.0.3?

**Comment by tandraschko** [comment]
not from my side, i just do it open source.
@mertsincan would you like to merge it?

**Comment by andrei-ivanov** [comment]
@mertsincan Would you? Please? :)

**Comment by mertsincan** [comment]
Ok, I'll add this fix to 6.0.3.
