### ISSUE TITLE
Documentation: Change p:clientBehavior to p:clientValidator

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1458]
Let me quote this _(section 7.3 of Primefaces documentation 5.3)_:

> CSV provides a behavior called p:clientBehavior to do instant validation in case you do not want to
> wait for the users to fill in the form and hit commandButton/commandLink

First, I think it is `p:clientValidator` instead of `p:clientBehavior`. Secondly, if I understand correctly the definition, and if I take [this example](http://www.primefaces.org/showcase/ui/csv/event.xhtml), since then I type one character, validation should occured and error appears, right? Well, in this example, validation does not occured: misunderstanding or bug?

**Comment by tandraschko** [comment]
The example works fine for me, the only weird thing is that there is no message

**Comment by tandraschko** [comment]
It's an bug probably as the there is a default message evaluation on the client side. Will fix it:
https://github.com/primefaces/primefaces/issues/1465

**Comment by Rapster** [comment]
What about the error description I've made? Validation is done only once "onblur" event occured. While I'm expecting "instant" validation, like it is done in the same example with "Integer (Key up)". So, if I put only one character, validation should fail since there is a `<f:validateLength minimum="2" maximum="5" />` no?

**Comment by tandraschko** [comment]
Our event is rendered with onchange. it's something related to the browser. Onchange is fired if you change the text and leave the input.

**Comment by Rapster** [comment]
Thank you @tandraschko for your explanation, it's not actually a bug, it does behave in the same way on all web browser and it's normal. Let me quote [from this](http://www.w3schools.com/jsref/event_onchange.asp): 

> Tip: This event (onchange) is similar to the oninput event. The difference is that the oninput event occurs immediately after the value of an element has changed, while onchange occurs when the element loses focus, after the content has been changed. The other difference is that the onchange event also works on keygen and select elements. 

Well, if you'd like to be compliant to the definition you gave to CSV. `oninput` should be used instead of `onchange`. In case, you do not agree with this, it still would be a good idea to have this behavior over `oninput` event instead of using key up event

**Comment by tandraschko** [comment]
You can use another event, it's up to you. The default is onchange.

**Comment by Rapster** [comment]
where can I change that?

**Comment by tandraschko** [comment]
check the example, there are 2 cases with different events.

**Comment by Rapster** [comment]
I can't get it working by doing this `<p:clientValidator event="oninput"/>` or `<p:clientValidator event="input"/>`. I can see clearly that "oninput" html attribute is not generated

**Comment by tandraschko** [comment]
feel free to create a feature request ;)

**Comment by Rapster** [comment]
I'll make a PR ;)

**Comment by cagataycivici** [comment]
Doc fixed.
