### ISSUE TITLE
icon attribute for p:menuButton

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1459]
it would be good if the component p:menuButton had the icon attribute, so we can change the default icon and create it without label, only with icon

**Comment by Rapster** [comment]
I'll make a PR for this

**Comment by Rapster** [comment]
PR is here #1471

**Comment by JaviRpo** [comment]
with this change, is it possible create the component  without label ?

**Comment by Rapster** [comment]
It's another problem that I just fixed #1471

**Comment by JaviRpo** [comment]
i had opened the issue #1516 because i had understood that the only icon functionality has not been resolved, and i didn't see that in the code but it was my mistake

**Comment by brunoaandrade** [comment]
If i add a custom icon to p:menuButton i lose the chevron. Is not supposed to keep both, like in p:menubar.
