### ISSUE TITLE
paginator issue when updating lazy data table on filter event 

### ISSUE THREAD

**Issue by michael-las** [primefaces/primefaces#1463]
In PrimeFaces 5.1/5.3:

``` html
  <h:form id="form">
    <p:dataTable var="item" value="#{dtFilterView.cars}"
                 filteredValue="#{dtFilterView.filteredCars}"
                 paginator="true" rows="5" id="otherTable">

        <p:ajax event="filter" update=":form:table" />

        <p:column headerText="Id">
            <h:outputText value="#{item.id}" />
        </p:column> 
        <p:column headerText="Brand" filterBy="#{item.brand}" >
            <h:outputText value="#{item.brand}" />
        </p:column>
    </p:dataTable>

    <p:dataTable var="car" value="#{dtLazyView.lazyModel}" 
                 lazy="true" rows="5" id="table" paginator="true"
                 paginatorPosition="bottom">
        <p:column filterBy="#{car.id}" headerText="Id" filterMatchMode="contains">
            <h:outputText value="#{car.id}" />
        </p:column> 
        <p:column filterBy="#{car.brand}" headerText="Brand" filterMatchMode="contains">
            <h:outputText value="#{car.brand}" />
        </p:column>
    </p:dataTable>
  </h:form>
```
# Steps to reproduce
1. Open page 
2. Filter 'otherTable' by brand
3. Paginator of 'otherTable' is identical to the paginator of 'table'

In this example it seems that the paginator just didn't update. If one uses different models, one can proof that statement 3 is correct. [UPDATE: One can proof it also by first setting a filter on 'table' and afterwards filter 'otherTable']

I guess, this has to do with the callback parameter 'totalRecords'.

**Comment by tandraschko** [comment]
Can you try 6.0 RC4?

**Comment by michael-las** [comment]
Done, affects 6.0 RC4, too.

**Comment by tandraschko** [comment]
Not sure if it's the right way to fix it actually.
Does both tables add "totalRecords" via RequestContext or what happens? I believe the client side should be correct, just the second table shoudln't add "setTotalRecords" as it isn't the request source.

**Comment by tandraschko** [comment]
Yup, that was the issue.
Fixed the same for DataGrid and DataList. This will probably fix other issues related to paginator.
