### ISSUE TITLE
WidgetVar for p:panelMenu not available ! (PrimeFaces 6.0)

### ISSUE THREAD

**Issue by mtbadi39** [primefaces/primefaces#1464]
```
/* xhtml */
<p:panelMenu widgetVar="myPanelMenu">
...
</p:panelMenu>

/* javascript */
PF('myPanelMenu').headers.click(function () {
...
});
```

With PrimeFaces 5.3 it works.
With PrimeFaces 6.0 doesn't work  :
In the console : 

```
Widget for var 'myPanelMenu' not available!
at http://localhost:8080/javax.faces.resource/core.js.xhtml?ln=primefaces&amp;v=6.0.RC4" :1:3127
```

tested with RC 1, 2,3 and 4.

**Comment by tandraschko** [comment]
`<p:panelMenu widgetVar="myPanelMenu">    
            <p:submenu label="Ajax Menuitems">    
                <p:menuitem value="Save" actionListener="#{menuView.save}" icon="ui-icon-disk" />    
                <p:menuitem value="Update" actionListener="#{menuView.update}"  icon="ui-icon-arrowrefresh-1-w" />    
            </p:submenu>    
        </p:panelMenu>    
        <script>    
            $(function() {    
                PF('myPanelMenu').headers.click(function () {    
                    console.log('test');    
                });    
            });    
        </script>`

works fine for me

**Comment by mtbadi39** [comment]
its works when i add

```
$(function(){
...
});
```

and stop working when i omit it. 
is it JQuery related behavior ?

**Comment by tandraschko** [comment]
yep, as our widgets are initialized with document.ready, you also have to use it.
