### ISSUE TITLE
Theme of equal chart PrimeNG

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primefaces#1466]
[http://www.primefaces.org/primeng/#/doughnutchart](http://www.primefaces.org/primeng/#/doughnutchart)

**Comment by Rapster** [comment]
If you're expecting an answer, please make your title and description more understandable.

**Comment by diegoarantes** [comment]
Leave the same Chars of the PrimeNG

**Comment by sudheerj** [comment]
Please raise any issue related to PrimeNG in its own project

**Comment by cagataycivici** [comment]
I don't understand the issue here.

**Comment by Rapster** [comment]
I think he wants to replace actual primefaces (jqplot) charts with chart.js

**Comment by diegoarantes** [comment]
Yes correct!

**Comment by cagataycivici** [comment]
But all the chart models have been written for jqplot. This will break backward compatibility. We've already rewritten them and would like to avoid rewrite everytime a new charting lib comes out.

**Comment by Rapster** [comment]
I do understand the request as chart.js looks way more fancy, and I do understand your point @cagataycivici. I don't know much about these two projects, but it seems that chart.js is getting more attention than jplot. Perhaps today, it's not necessary to migrate to jqplot, but in the future, probably worth to think of it
