### ISSUE TITLE
Terminal input does not get focus in IE11 after command submission

### ISSUE THREAD

**Issue by hatspencer** [primefaces/primefaces#1470]
Open [PrimeFaces ShowCase - Terminal](http://www.primefaces.org/showcase/ui/misc/terminal.xhtml) in IE11 and submit a command. The component loses focus. This works as intended in Firefox 46 and Chrome 50.

**Comment by tandraschko** [comment]
Feel free to provide a PR.

**Comment by hatspencer** [comment]
To summarize, I've created PR #1600 which fixes this, and also fixed it in PR #1467.
