### ISSUE TITLE
bug on ie 11 not execute ajax request 

### ISSUE THREAD

**Issue by pablosborges** [primefaces/primefaces#1474]
<p:commandButton id="btnAtualizarNoticia" value="Atualizar" 
                    actionListener="#{portalBean.consultarNoticiasPorDia()}" 
                    update=":formNoticias:noticias" process="@this" partialSubmit="true"
                    onerror="alert('oi');"
                    />

bug by pressing the button on console ie.
lock the flap and to return to work have to restart the browser or open a new tab

see error on console ie developer tools

SCRIPT7002: XMLHttpRequest: Network Error 0x2ee1, Could not complete the operation. Error: 00002ee1.

I am using internet explorer 11, primefaces-5.3.13, wildfly 9.0.2

**Comment by tandraschko** [comment]
Does it work fine e.g. in the showcase? If yes, please provide a sample maven / jetty application.

**Comment by pablosborges** [comment]
**_see the code snippet to display the error_**

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>ERROR</title>
    </h:head>
    <h:body>
        <p:layout fullPage="true">
            <p:layoutUnit position="north" size="0" resizable="false" closable="false" collapsible="false" gutter="0">
                <p:menubar id="menuTop" model="#{myBean.myMenuBar}" autoDisplay="false">
                     <f:facet name="options">
                         <h:form id="formMenu">
                               <p:commandButton value="SAIR" icon="ui-icon-extlink" action="#{myBean.logout}" immediate="true"/>
                             </h:form>
                     </f:facet>
                </p:menubar>
            </p:layoutUnit>
            <p:layoutUnit position="south" size="90" resizable="false" closable="false" collapsible="false" gutter="0">
                <ui:insert name="r"></ui:insert>
            </p:layoutUnit>
            <p:layoutUnit position="west" size="260" gutter="0" collapsible="false">
                 <h:form id="formError">
                    <p:carousel id="not" value="#{myBean1.lstNews}" var="news" headerText="News" numVisible="1" autoPlayInterval="60000" vertical="true"> 
                        <h:panelGrid columns="2">
                            <f:facet name="header">
                            </f:facet>
                            <h:outputText value="#{news.msg}" escape="false"/>
                            <f:facet name="footer">
                            </f:facet>
                        </h:panelGrid>
                    </p:carousel> 
                    <p:commandButton id="btnRefresh" value="Refresh" actionListener="#{myBean1.refreshNews()}" update="formError:not"/>
                </h:form>
            </p:layoutUnit>
            <p:layoutUnit position="center" size="0">
                <ui:insert name="f"></ui:insert>
            </p:layoutUnit>
        </p:layout>
        <p:ajaxStatus style="width:32px;height:32px;position:fixed;top:50%;left:50%;display:block;"
            onstart="PF('statusDialog').show()" onsuccess="PF('statusDialog').hide()" onerror="PF('statusDialog').hide()">
        </p:ajaxStatus>
        <p:dialog widgetVar="statusDialog" modal="true" draggable="false" closable="false" resizable="false" showHeader="false">
            <b>Processing ... wait</b>
            <p:graphicImage name="ajax-loader.gif" library="images"/>
        </p:dialog>
        <p:log rendered="true"/>
    </h:body>
</html>
```

```
@SessionScoped
public class MyBean implements Serializable {
     private MenuModel myMenuBar;
    // get and set

  public String logout() {
        try {
            FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
            return "/login.xhtml?faces-redirect=true";
        } catch (Exception e) {
     }
        return "";
  }

@SessionScoped
public class MyBean1 implements Serializable {

    private List<News> lstNews = null;
    // get and set

    public void refreshNews() {
        try {
                     setLstNews(new ArrayList<News>());
        } catch (Exception e) {
       }
    }
}
```

the menu is dynamically loaded.

my menu has many items and internet explorer it takes a while to load.

if I take the menu of code works correctly.

otherwise, the following error and issued in the browser internet explorer the component log Primefaces

01/06/2016 08: 59: 47: Post Data:javax.faces.partial.ajax=true&javax.faces.source=formError%3AbtnRefresh&javax.faces.partial.execute=%40all&javax.faces.partial.render=formError%3Anot&formError%3AbtnRefresh=formError%3AbtnRefresh&formError=formError&formError%3Anot_page=0&javax.faces.ViewState=-1862779060462001008%3A-6807836087478061778.

01/06/2016 08: 59: 47: Request return with error: error ..

01/06/2016 08: 59: 47: Response completed ..

in developing the utility tool appears the error message on the console

SCRIPT7002: XMLHttpRequest: Network Error 0x2ee1, Could not complete the operation. Error: 00002ee1.

I'm using internet explorer browser version 11.0.9600.18282

**Comment by cnsgithub** [comment]
FYI: your code isn't complete / doesn't compile.

**Comment by pablosborges** [comment]
cnsgithub add the get and set methods and imports

**Comment by cnsgithub** [comment]
News class and a method is missing. If you want others to help you don't make them do work. Examples should be really only copy+paste ;-)

**Comment by pablosborges** [comment]
I'm sorry, what's missing for you to perform?

**Comment by tandraschko** [comment]
News class is missing etc. Will close it as invalid.
If the bug is still present in the newest version, please create a new issue and respect our issue template.
