### ISSUE TITLE
multiple autoComplete resets to values from model after validation failure

### ISSUE THREAD

**Issue by Karolis92** [primefaces/primefaces#1476]
if `<p:autoComplete...>` is used with attributes `multiple="true"` and `required="true"` and user submits form after emptying this field (values was already populated then bean was initialized) - it shows required message as expected, but also reset's to old values from model (other fields if required stays empty)

```
<p:autoComplete id="#{fieldInfo.formField.name}" value="#{backingBean.attributes[fieldInfo.formField.name]}" completeMethod="#{backingBean.complete}"
     multiple="true" forceSelection="true" required="#{fieldInfo.formFieldEntry.mandatory}"
     var="n" itemValue="#{n}" itemLabel="#{n.valueForUser}">
     <f:converter binding="#{gsConverter}" />
</p:autoComplete>
```

JSF 2.2.13
PrimeFaces 5.3 (also reproduces on 6.0.RC4)
javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL = false (this property set to true sometimes causes this type of issues)

**Comment by Karolis92** [comment]
OK, so done same more tests and problem seems to be not only required, but all validation cases.
If any validation fails - values are set back to last correct  values.

Simple test code:
- validator:

```
@FacesValidator
public class TestValidator implements Validator {
    @Override
    public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
        FacesMessage msg = new FacesMessage("test validation failed");
        msg.setSeverity(FacesMessage.SEVERITY_ERROR);
        throw new ValidatorException(msg);
    }
}
```
- bean snippet:

```
private List<String> strLi = Arrays.asList("one", "two");
public List<String> completeText(String query) {
    List<String> results = new ArrayList<String>();
    for(int i = 0; i < 10; i++) {
        results.add(query + i);
    }
    return results;
}
// getters and setters
```
- xhtml snippet:

```
<p:autoComplete id="testAC" value="#{backingBean.strLi}" completeMethod="#{backingBean.completeText}"
    forceSelection="true" multiple="true">
    <f:validator validatorId="testValidator" />
</p:autoComplete>
```

Problem seems to be code in `AutoCompleteRenderer` class `encodeMultipleMarkup` method:

```
List values = (List) ac.getValue();
```

it doesn't even try to get submitted values, it directly calls `getValue`

**Comment by Karolis92** [comment]
Tried to get and convert submitted value in `encodeMultipleMarkup` to Objects for redrawing, but it was `null`...
Before this, in `decodeMultiple`, submitted values are set ant they are not `null`, don't know where they disappear

**Comment by Karolis92** [comment]
tried to fix the problem in PR #1486, now it redraws input from submitted value if validation failed and values are not set to the component and backing bean

**Comment by tandraschko** [comment]
Could you please recheck it with the current source? I applied a patch for a bug which also occured with multiple and validation.
Also the PR has conflicts.

If it doesn't work, please provide a new PR + a complete sample bean + small xhtml snippet.

**Comment by tandraschko** [comment]
No feedback, will close it for now
