### ISSUE TITLE
Sort and Filter does not work when lazy=true is used for p:datatable

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1477]
The control is there, but nothing happens if pressed on it. 

I dont know how this should be solved, as full sorting is not possible if data is fetched lazily. 

Ideas/Possible solutions: 
- remove sorting/filtering when lazy is used (don't render the control even if specified)
- sort only the currently visible datasets
- if sorting is used, all data is fetched on backend to provide a server side way to sort the rows

**Comment by michael-las** [comment]
> if sorting is used, all data is fetched on backend to provide a server side way to sort the rows

Do you mean something other than LazyDataModel already provides?

**Comment by kukel** [comment]
Please use the forum first. This is not something for the issue list. And create a GOOD question (like with code, version info etc)

**Comment by cnsgithub** [comment]
Sorry but this IS an issue. It happens with latest ELITE and PF6 Final. There is virtually no other code needed, as soon as lazy="true" is used, sortBy and filterBy for any columns do not work at all. This is very confusing for the end user and shouldn't stay like that for ever. I'm not saying its urgent, but its not expected behavior.

At least sorting/filtering the currently visible (loaded) rows would be the minimal solution which should apply here.

**Comment by michael-las** [comment]
As soon as lazy="true" a LazyDataModel must be used.

**Comment by Serkan80** [comment]
I'm having a similar problem. When lazy=true (and I use a LazyDataModel implementation), cell editing and commandButtons don't work in the datatable. I verified this by adding a 'cellEdit' event and the new and old values of the cell are both null.

When I disable it, everything works fine.

Currently this is a huge showstopper for me.

And I have to say that paging and sorting works fine, only cellEditing and commandButtons don't work for me. I've tested this on version 5.3 and 6.0.

**Comment by michael-las** [comment]
@Serkan80 Your problem seems not to be related to this issue. If you think you've found a bug, please file a new issue that contains a simple example which is good enough to reproduce the bug. Nobody knows, what one did exactly just by reading 'lazy=true -> nothing works'. In this context, also see the answer of @kukel.

**Comment by melloware** [comment]
I use lazy=true in production all over the place and have no issues with sorting and filtering.  @cnsgithub please close this ticket.

**Comment by cnsgithub** [comment]
It fails if you have a Collection datasource. If it is supported only when using LazyDataModel, i guess this can be closed. 

However it would be good if it would not fail silently, while still working partly. Also it would be nice to have a way to add lazy-loading to datatables using collection datasource, for having a simpler way.. 

Overall i think PF does not inform the developer about many things in runtime. While some "misconfiguration" lead to exceptions (so the developer can figure out what's wrong) some do not ;)
