### ISSUE TITLE
multiple autoComplete with dropdown display bug

### ISSUE THREAD

**Issue by Karolis92** [primefaces/primefaces#1478]
Then `<p:autoComplete...>` is used with `multiple="true"` and `dropdown="true"`, dropdown button is displayed below input field, not by side:
![dd_bug](https://cloud.githubusercontent.com/assets/19680461/15699804/96ffce76-27d8-11e6-883a-539ac5393457.JPG)
![dd_bug_2](https://cloud.githubusercontent.com/assets/19680461/15699932/7aa9f804-27d9-11e6-9e93-53b04c1a576f.JPG)

Reproduced on:
- JSF 2.2.13
- PrimeFaces 6.0.RC4
- Firefox 46.0.1, Chrome 50.0.2661.102, IE 11

**Comment by Rapster** [comment]
I'd recommend to check your own css style, and see what "class selector" might do this

**Comment by tandraschko** [comment]
It also occurs in the showcase if you set dropdown=true to the multiple example. 
Feel free to provide a PR.

**Comment by Rapster** [comment]
I think it's due to `.ui-autocomplete-multiple-container` which has a `width: 400px`

**Comment by Karolis92** [comment]
floating `ui-autocomplete-multiple-container` to the left puts button inline, but than messages and other stuff to the right of the autocomplete becomes hidden under the button.

**Comment by Karolis92** [comment]
floating `ui-autocomplete-multiple-container` to the left puts button inline, but on top of input field, so sometimes there is no way to pres `x` to remove element

**Comment by Karolis92** [comment]
PR is here #1480
