### ISSUE TITLE
Migrate TriStateCheckbox component to PrimeFaces

### ISSUE THREAD

**Issue by xKopax** [primefaces/primefaces#1482]
This component from PrimeExtension is very usefull, it'd be nice to have it on the main Prime. 
http://www.primefaces.org/showcase-ext/views/triStateCheckbox.jsf;jsessionid=gu1adcu06srum8z07meuf48

**Comment by tandraschko** [comment]
Will close it for now, we already discuss it internally when which component will be migrated.

**Comment by xKopax** [comment]
oh, sorry xD

do you have a roadmap for the migration?

thanks for the amazing work on Prime =)
