### ISSUE TITLE
Is that the themes can not download from maven ?

### ISSUE THREAD

**Issue by smarkm** [primefaces/primefaces#1483]
Is that the themes can not download from maven ?

**Comment by Rapster** [comment]
There you go: http://www.mkyong.com/jsf2/primefaces/changing-theme-in-primefaces/

**Comment by smarkm** [comment]
thanks @Rapster

**Comment by Karolis92** [comment]
also: http://www.primefaces.org/themes
Scroll down to "Installation" part

mkyong's approach seems strange because he uses `prime-repo`

**Comment by smarkm** [comment]
@Karolis92  yes. but the "[http://www.primefaces.org/themes](http://www.primefaces.org/themes)" info rmation is invalid [http://mvnrepository.com/search?q=primefaces](http://mvnrepository.com/search?q=primefaces) ,extensions themes can used only version 1.0.8

**Comment by tandraschko** [comment]
next time use the forum, here is the issue tracker which is not for questions.

**Comment by mtbadi39** [comment]
To your **pom** add : 
1) PrimeFaces Maven Repository :

```
        <repository>  
            <id>primefaces-maven-repository</id>  
            <name>PrimeFaces Maven Repository</name>  
            <url>http://repository.primefaces.org</url>
        </repository>
```

2) Themes jar as dependency 

```
        <dependency>
            <groupId>org.primefaces.themes</groupId>
            <artifactId>all-themes</artifactId>
            <version>1.0.10</version>
        </dependency>
```

2) Activate the desired theme in your web.xml : 

```
        <context-param>
             <param-name>primefaces.THEME</param-name>
             <param-value>redmond</param-value>
        </context-param>
```

@tandraschko :+1: your are right !
