### ISSUE TITLE
any active tab for p:accordionPanel

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1484]
it would be good if the component p:accordionPanel had no active tabs after creation.

Exist the attribute activeIndex for indicate tabs active when the component was created, but not some attribute for indicate there is no active tabs

**Comment by smarkm** [comment]
you may set activeIndex="-1"

**Comment by smarkm** [comment]
@JaviRpo you may set activeIndex="-1"

**Comment by JaviRpo** [comment]
thanks it works perfectly
