### ISSUE TITLE
Replace all icons for Font Awesome

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primefaces#1488]
Replace all of the default theme icons for Font Awesome. Like the PrimeNG.

**PrimeFaces (No Font Awesome icons)**
![capturar1](https://cloud.githubusercontent.com/assets/5193643/15762777/10cd8a54-28f6-11e6-911b-a0b1d8dfc415.PNG)
**PrimeNG (Font Awesome icons)**
![capturar2](https://cloud.githubusercontent.com/assets/5193643/15762792/2402ef2e-28f6-11e6-9d95-5c2620e30723.PNG)

**Comment by cagataycivici** [comment]
I wish but we rather not as it is a core change and will be break things due to backward compatibility. Premium themes override them with svg icons by the way.
