### ISSUE TITLE
Incorrect behavior of accordion's activeIndex in multiple mode

### ISSUE THREAD

**Issue by michael-las** [primefaces/primefaces#1490]
This is an extended version of #639 and related to #1484.

Affected version: Primefaces 6.0 SNAPSHOT
### Overall description

According to the documentation, a comma separated list of indices of the (currently) active tabs is expected to be available by attribute 'activeIndex' when multiple mode is on. This holds true only under certain conditions. 
### Steps to reproduce
1. Open the view given by the example below. 
2. Select first tab of first accordion. 
3. Close first tab of first accordion. 
4. Select first tab of second accordion. 
5. Close second tab of second accordion.
6. Close first tab of second accordion. 
7. Select first tab of third accordion. 
8. Close first tab of third accordion. 
### Expected and actual behavior

After step 2. Expected behavior: index0 changes from "" to "0". Actual behavior: index0 changes to "NaN,0".
After step 3. Expected behavior: index0 changes back to "". Actual behavior: index0 changes to "NaN".
After step 6. Expected behavior: index1 changes to "". Actual behavior: index1 changes to "0".
After step 7. Expected behavior: index2 changes to "0". Actual behavior: index2 changes to "-1,0".
After step 8. Expected behavior: index2 changes to "". Actual behavior: index2 changes to "-1".
### Consequences and workarounds

activeIndex contains either
1. non-numeric tab-indices (NaN)
2. non-existing tab-indices (-1)
3. indices of inactive tabs (see step 6 above)

One can work around the first two by making sure that the list of indices, which is used to initialize activeIndex, solely consists of one or more existing tab indices. In that case, you'll be faced with consequence 3.

On the other hand, one can work around 3 by initializing activeIndex to a comma separated list of indices containing "-1".
### Example

Slightly modified version of the example given by @cnsgithub in #639.
index.xhtml:

``` html
<h:form id="form">
    <h1>Initialized activeIndex to ""</h1>
    <p:accordionPanel multiple="true" activeIndex="#{primefacesStateBean.activeIndex0}">
        <p:ajax event="tabChange" listener="#{primefacesStateBean.onChange}" global="false" update=":form:text0"/>
        <p:ajax event="tabClose" listener="#{primefacesStateBean.onClose}" global="false" update=":form:text0"/>

        <p:tab title="tab0.0">

        </p:tab>
        <p:tab title="tab0.1">

        </p:tab>
    </p:accordionPanel>
    activeIndex: <h:outputText id="text0" value="#{primefacesStateBean.activeIndex0}" />

    <h1>Initialized activeIndex to "1"</h1>
    <p:accordionPanel multiple="true" activeIndex="#{primefacesStateBean.activeIndex1}">
        <p:ajax event="tabChange" listener="#{primefacesStateBean.onChange}" global="false" update=":form:text1"/>
        <p:ajax event="tabClose" listener="#{primefacesStateBean.onClose}" global="false" update=":form:text1"/>

        <p:tab title="tab1.0">

        </p:tab>
        <p:tab title="tab1.1">

        </p:tab>
    </p:accordionPanel>
    activeIndex: <h:outputText id="text1" value="#{primefacesStateBean.activeIndex1}" />

    <h1>Initialized activeIndex to "-1"</h1>
    <p:accordionPanel multiple="true" activeIndex="#{primefacesStateBean.activeIndex2}">
        <p:ajax event="tabChange" listener="#{primefacesStateBean.onChange}" global="false" update=":form:text2"/>
        <p:ajax event="tabClose" listener="#{primefacesStateBean.onClose}" global="false" update=":form:text2"/>

        <p:tab title="tab2.0">

        </p:tab>
        <p:tab title="tab2.1">

        </p:tab>
    </p:accordionPanel>
    activeIndex: <h:outputText id="text2" value="#{primefacesStateBean.activeIndex2}" />

  </h:form>
```

PrimeFacesStateBean.java:

``` java
import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.primefaces.component.tabview.Tab;
import org.primefaces.event.TabChangeEvent;
import org.primefaces.event.TabCloseEvent;

@Named("primefacesStateBean")
@ViewScoped
public class PrimeFacesStateBean implements Serializable {
    private String index0 = "";
    private String index1 = "1";
    private String index2 = "-1";

    public String getActiveIndex0(){
         return index0;
    }
    public void setActiveIndex0(String value) {
         System.out.println("index0: " + index0 + " -> " + value);
         index0 = value;
    }
    public String getActiveIndex1(){
         return index1;
    }
    public void setActiveIndex1(String value) {
         System.out.println("index1: " + index1 + " -> " + value);
         index1 = value;
    }
    public String getActiveIndex2(){
         return index2;
    }
    public void setActiveIndex2(String value) {
         System.out.println("index2: " + index2 + " -> " + value);
         index2 = value;
    }

    public void onChange(TabChangeEvent event) {
        Tab activeTab = event.getTab();

        System.out.println("onChange: " + activeTab.getTitle());
    }
    public void onClose(TabCloseEvent event) {
        Tab activeTab = event.getTab();

        System.out.println("onClose: " + activeTab.getTitle());
    }
}
```

**Comment by michael-las** [comment]
Could provide a fix for this issue but need to know if the documentation shall be taken literally. That is, if 'activeIndex' is intended to be an empty string (empty list) when all tabs are closed, or a list that consists of a single "-1".

**Comment by tandraschko** [comment]
Works fine for me now.
