### ISSUE TITLE
Allow custom icon in fieldset

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1491]
When fieldset is not toggleable, allow custom icon in fieldset. It is nice to use a icon to visualize the content.

Like using a map-marker when content of field set shows address.

**Comment by sudheerj** [comment]
Actually when the fieldset is not toggleable I didn't see the advantage of having custom icon for field set.May be few example sites will give the clarification.

**Comment by djmj** [comment]
Its just for styling purpose. Example: http://fs5.directupload.net/images/160606/xk4cjucf.jpg

**Comment by michael-las** [comment]
Just use the legend facet, e. g.

``` html
  <p:fieldset>
    <f:facet name="legend">
      <img src="http://icons.iconarchive.com/icons/icons-land/vista-map-markers/24/Map-Marker-Ball-Left-Pink-icon.png" style="margin-right:.1em;vertical-align:middle;" /><h:outputText value=" Adresse" />
    </f:facet>
  </p:fieldset>
```

**Comment by tandraschko** [comment]
It's really easy with the facet, i will close it.

**Comment by djmj** [comment]
Yes it is easy to do but adds a lot of unnecessary markup to an application which just bloats the markup. 4 lines just for an icon.

Especially if PF invests so much into their custom themes.

	<f:facet name="legend">
		<h:panelGroup styleClass="fa fa-user" style="vertical-align: middle; margin-right: 0.25em; font-size: 1.25em;"/>
		<h:outputText value="User" style="vertical-align: middle;"/>
	</f:facet>
