### ISSUE TITLE
ClientValidator should support "oninput" event and probably many other

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1493]
I wrote a fix for that. The issue comes from `HtmlInputText.getEventNames()` which does not include `input` event name, it does not support much actually... I had to override `InputText.getEventNames` to fix this issue. I really like this feature as it's really reactive and know client asking for instant validation.

Here is the list of event names supported: http://www.w3schools.com/tags/ref_eventattributes.asp Not all of them are for input, but some :)

As I think it's a problem from mojarra and not Primefaces, I don't know what to do :/

**Comment by tandraschko** [comment]
We might fix it but it would be the best if you create a spec issue and ping them via mailing list. It should go in 2.3.

**Comment by tandraschko** [comment]
For the spec: https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1419

**Comment by Rapster** [comment]
Thank you @tandraschko I guess it's gonna take some time before we see that feature coming. I would've put this link http://www.w3schools.com/tags/ref_eventattributes.asp as it looks more complete and "formal"

**Comment by tandraschko** [comment]
Would be great if you could ping them on the mailing list, it's a quite important feature regaring HTML5 compatibility.

**Comment by Rapster** [comment]
What do you mean by pinging them? It's not surprising that JSF or JEE loosing popularity (https://javaee-guardians.io/lack-of-java-ee-8-progress/). We were talking about this with my colleagues due to recent Oracle announcement. Go to some oracle website or this one https://javaserverfaces-spec-public.java.net/ and look how corporate it is. People don't feel confortable about this as it looks deprecated or event abandonned website... All of this said to say: they are still using mailing list!?

**Comment by tandraschko** [comment]
pinging them = writing on the mailing list that it's important for you.
Yes, the whole apache and many other open source projects uses mailing lists and there is nothing wrong about it.

**Comment by tandraschko** [comment]
Could you please create a list, which components needs which new events?

**Comment by Rapster** [comment]
Well, the link I gave it to you targeting at least 3 kind of components: body, form elements and media:

Missing events for:

# 1.  HTML.BODY_ATTRS (BodyRenderer)

- onafterprint
- onbeforeprint
- onbeforeunload
- onerror
- onhashchange
- onmessage
- onoffline
- ononline
- onpagehide
- onpageshow
- onpopstate
- onresize
- onstorage
- onunload

# 2.  HTML.CHANGE_SELECT_EVENTS (All UIInput)

- oninput
- oninvalid

## 2.1 HTML.CLICK_EVENTS

- oncontextmenu (need support of `contextmenu` attribute)
- onreset

## 2.2. HTML.COMMON_EVENTS_WITHOUT_CLICK
- onwheel
- ondrag
- ondragend
- ondragenter
- ondragleave
- ondragover
- ondragstart
- ondrop
- onscroll

# 3. p:media _(does not support events so far)_

- onabort
- oncanplay
- oncanplaythrough
- oncuechange
- ondurationchange
- onemptied
- onended
- onerror
- onloadeddata
- onloadedmetadata
- onloadstart
- onpause
- onplay
- onplaying
- onprogress
- onratechange
- onseeked
- onseeking
- onstalled
- onsuspend
- ontimeupdate
- onvolumechange
- onwaiting

**Comment by tandraschko** [comment]
As JSF 2.3 doesn't contain those changes, we should take care of it.
Could you share your solution how you did it?

**Comment by Rapster** [comment]
I didn't implement anything actually... I guess [HTML util class](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/util/HTML.java) should be completed with the above values

**Comment by tandraschko** [comment]
Not sure, i believe that we must also overwrite the getEventNames in all our input components.

**Comment by melloware** [comment]
I am going to take a crack at trying to implement this since it didn't make JSF 2.3. I will ask for reviews of PR once made.

**Comment by tandraschko** [comment]
+1
would be great

**Comment by tandraschko** [comment]
@melloware @Rapster can you review? https://github.com/eclipse-ee4j/faces-api/issues/1507
