### ISSUE TITLE
Add unique attribute to p:autocomplete

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1495]
When an item is already selected in p:autocomplete, it would be very good if the result query search remove/omit these values

![image](https://cloud.githubusercontent.com/assets/8562436/15838041/bddf3a4a-2c01-11e6-8090-f246b7b73049.png)

the idea is not to have repeated values

![image](https://cloud.githubusercontent.com/assets/8562436/15838078/dc0de23c-2c01-11e6-919d-5d83fe4d15cb.png)

**Comment by Rapster** [comment]
Make sense :+1:

**Comment by Rapster** [comment]
I do agree with this, in this example https://select2.github.io/examples.html#disabled, selecting the same element will remove it from the input

**Comment by JaviRpo** [comment]
it would be nice

**Comment by ghost** [comment]
Any solutions about this issue? It's really annoying...

**Comment by Rapster** [comment]
Not sure if we should introduce a new attribute like "unique" or simply modify the current behavior

**Comment by JaviRpo** [comment]
An unique attribute would be fine, i guess

**Comment by JaviRpo** [comment]
Any update about this issue?

**Comment by Rapster** [comment]
I'm not part of PF team, @tandraschko might have an opinion on this

**Comment by tandraschko** [comment]
If nobody comments on the issue or somethings changes in the issue status -> no update

**Comment by Rapster** [comment]
Too bad, I think this feature is relevant _(and should be the default behavior actually).

**Comment by tandraschko** [comment]
i'm sure about 50% of the 500 issues are relevant ;)

**Comment by Rapster** [comment]
:)
