### ISSUE TITLE
Tree: dynamic tree in external xhtml does not expand nodes

### ISSUE THREAD

**Issue by szym1991** [primefaces/primefaces#1496]
I have problem with Tree component. I want to use it by call includeFacelet method from FaceletContext and put external xhtml file with tree. Tree is loading properly but when I click no node o expand i doesn't work.

It's fully example of code:
index.xhtml:

``` html
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<f:view contentType="text/html">
    <h:head>
        <!-- head stuff -->
    </h:head>
    <h:body>
        <h:form>
            <div id="content-container" class="container">
                <!-- command button to dynamically add TreeComponent in treeContent -->
                <p:commandButton action="#{exampleBean.callTree()}" value="test"/>
            </div>`
        </h:form>
        <h:panelGroup layout="block" id="treeContent">
        </h:panelGroup>
        <hr/>
    </h:body>
</f:view>
</html>
```

Example backend bean:

``` java
@ManagedBean(name = "exampleBean")
@ViewScoped
public class ExampleBean implements Serializable {
    @Getter
    private TreeNode treeRoot;
    public MasterPageBean() {
    }
    @PostConstruct
    public void initialize() {
        addPanelGroup();
    }

// add panelGroup 'test' as child of treeContent panelGroup
    protected void addPanelGroup() {
        UIComponent component = FacesContext.getCurrentInstance().getViewRoot().findComponent("treeContent");
        if (component != null) {
            String divId = "test";
            UIComponent popupPanelGroup = FacesContext.getCurrentInstance().getViewRoot().findComponent(divId);
            if (popupPanelGroup == null) {
                HtmlPanelGroup panelGroup = new HtmlPanelGroup();
                panelGroup.setId(divId);
                panelGroup.setLayout("block");
                component.getChildren().add(panelGroup);
            }
            RequestContext rc = RequestContext.getCurrentInstance();
            // call js function to atach div on page
            rc.execute("attachGroup(\"" + divId + "\")");
        }
    }

    public void callTree() {
        treeRoot = new DefaultTreeNode("Root", null);
        // (...) generate treeRoot...

        String divId = "test";
        RequestContext requestContext = RequestContext.getCurrentInstance();
        FaceletContext faceletContext = (FaceletContext) FacesContext.getCurrentInstance().getAttributes().get(FaceletContext.FACELET_CONTEXT_KEY);
        UIComponent component = FacesContext.getCurrentInstance().getViewRoot().findComponent(divId);
        try {
            // put external xhtml in 'test' panelGroup
            faceletContext.includeFacelet(component, "test.xhtml");
        } catch (IOException ex) {
            // logger
        }
        // update 'test' panelGroup
        requestContext.update(divId);
    }
}
```

test.xhtml:

``` html
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <h:form>
        <p:tree id="treeTest" value="#{exampleBean.treeRoot}" var="node" dynamic="true">
            <p:treeNode>
                <h:outputText value="#{node}"/>
            </p:treeNode>
        </p:tree>
    </h:form>
</ui:composition>
```

After click to expand any node this error is occured:

> ERROR j.e.r.webcontainer.jsf.context - javax.faces.FacesException: Unsupported tree node type:default
>    at org.primefaces.component.tree.Tree.getUITreeNodeByType(Tree.java:256)
>    at org.primefaces.component.tree.TreeRenderer.encodeTreeNode(TreeRenderer.java:492)
>    at org.primefaces.component.tree.TreeRenderer.encodeTreeNodeChildren(TreeRenderer.java:599)
>    at org.primefaces.component.tree.TreeRenderer.encodeEnd(TreeRenderer.java:180)
>    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
>    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
>    at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582)
>    at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
>    at org.primefaces.component.api.UITree.visitTree(UITree.java:738)
>    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
>    at javax.faces.component.UIForm.visitTree(UIForm.java:371)
>    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
>    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
>    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
>    at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
>    at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
>    at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322)
>    at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
>    at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004)
>    at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
>    at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:432)
>    at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
>    at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)

When Tree Component has no set property 'dynamic' everything is ok.
I use this mechanism to add other primefaces dynamic components and they works fine.

I tested in on Primefaces 5.3 and 60. RC4

**Comment by tandraschko** [comment]
Example isn't fully runnable, attachGroup js missing and therefore a exception will be thrown in the client.

If the problem still persists with the current trunk version, please create new issue with a fully runnable and small sample bean+xhtml.
