### ISSUE TITLE
DataTable: Support custom p:column ordering

### ISSUE THREAD

**Issue by wfsaxton** [primefaces/primefaces#1501]
p:dataTable displays p:column's in the order in which they are placed within the Facelets file.  I'm requesting that p:dataTable be enhanced to support custom ordering, similar to ICEfaces ace:dataTable, columnOrdering attribute.

http://res.icesoft.org/docs/v4_latest/ace/tld/ace/dataTable.html

Each p:column in the dataTable has a column index corresponding to the order in which it appears in the facelets page:

myBean.xhtml

```
<!-- columns listed in order foo, bar, and bam -->
<ace:dataTable columnOrdering="#{myBean.columnOrdering}" ...

    <ace:column id="foo" ... <!-- column index 0 -->

    <ace:column id="bar" ... <!-- column index 1 -->

    <ace:column id="bam" ... <!-- column index 2 -->
```

MyBean.java

```
@Named
@ViewScoped
public class MyBean {

    private List<Integer> columnOrdering = new ArrayList<>();

    @PostConstruct
    public void init {

        // We want columns to be displayed in order bam, bar, foo
        columnOrdering.add(2);
        columnOrdering.add(1);
        columnOrdering.add(0);
    }
```

p:columns will NOT work for use-cases where the columns all require separate display/sorting/filtering functionality.  This is why I'm requesting this for the p:dataTable/p:column usage.

**Comment by tandraschko** [comment]
@Rapster we simple could sort columns based on the priority attribute? we will also reuse this in ColumnMeta for reordering then.

**Comment by Rapster** [comment]
> p:columns will NOT work for use-cases where the columns all require separate display/sorting/filtering functionality. This is why I'm requesting this for the p:dataTable/p:column usage.

There is your issue, not the other way around @wfsaxton :smile: I don't like reusing attribute which were meant for another purpose (sorting in that case, and they are two very different things). But in this ticket, the problem comes from `p:columns` which doesn't give a lot of options in terms of rendering, but that may be solved using `FilterMeta#builder` and `SortMeta#builder`, and using switch in facet filter, but I don't think we have a facet for column content. Maybe something like DynaForm from PE would be great

**Comment by tandraschko** [comment]
we definitily need a order/priority in ColumnMeta for reordering, so for me it makes sense to also have the same ability as attr and in the ColumnMetaBuilder for the user.

**Comment by Rapster** [comment]
Yes, introducing a displayOrder is a better idea than using sortPriority

**Comment by tandraschko** [comment]
i dont mean "sortPriority", we also have a "priority" attr :D

**Comment by Rapster** [comment]
Ah yes indeed, for responsivity right? Probably do some renaming in here as it gets confusing but yeah indeed for this ticket, reusing "priority" (displayPriority?) sounds good

**Comment by tandraschko** [comment]
Will work on it after #6689

**Comment by tandraschko** [comment]
Introduced "displayPriority" on p:column/columns now
basic work done, need to marry it with draggable columns now.

I also think about renaming the "priority" to "responsivePriority" or "reflowPriority"

**Comment by melloware** [comment]
I like `responsivePriority`
