### ISSUE TITLE
Primefaces 6 Calendar Bug

### ISSUE THREAD

**Issue by DogukanZengin** [primefaces/primefaces#1506]
```
<p:calendar placeholder="Date" id="mask" pattern="dd-MM-yyyy"
               mask="true" locale="tr" navigator="true" yearRange="c-100:c"/>
```

Calendar with these attributes is throwing javascript error :

> Uncaught TypeError: Cannot read property 'paginator.PAGE' of undefined

**Comment by mertsincan** [comment]
I couldn't replicate this issue. Can you please attach a sample maven project or xhtml page with your locale values for us to replicate?
Primefaces Locales; 
https://github.com/primefaces/primefaces/wiki/Locales

My Screenshot;
![calendartest](https://cloud.githubusercontent.com/assets/11868120/15890899/983b8fa8-2d7a-11e6-9d74-c26e391aff65.PNG)

**Comment by DogukanZengin** [comment]
I replicated the issue with a sample maven project. But I need to mention that we are using Spark theme for the application and it seems this is a theme based issue. Do you want me to upload the proect anyway, I asked because spark is a licensed theme.

And I think it is not calendar causing that issue. Calendar is throwing another error. You need to put `showOn="button"` attribute to replicate the error

> Uncaught TypeError: Cannot read property 'calendar.BUTTON' of undefined

Datatable is throwing

> Uncaught TypeError: Cannot read property 'paginator.PAGE' of undefined

Thanks.

**Comment by mertsincan** [comment]
Did you try without Spark theme? Because, we have some fixes for backward compatibility on all Premium Layouts and Themes;
https://github.com/primefaces/layouts/issues/87

**Comment by DogukanZengin** [comment]
There is no problem with the default theme. But when Spark is applied, the issue comes up again. It seems we'll have to wait for the next release to migrate to version 6.0. 

Thanks

**Comment by mertsincan** [comment]
Thanks for your understanding! I think this issue is resolved on next release.

**Comment by lalib** [comment]
Hi there,

We're having the same issue in the company. When will you release next version?

**Comment by mertsincan** [comment]
Next week.

**Comment by tandraschko** [comment]
I assume that its already fixed. Please reopen if not.

**Comment by TCM5** [comment]
Hi there,

This still happens in the version 6.2. Do you guys find out any workaround until fixing properly? 

![pf_bug](https://user-images.githubusercontent.com/9709208/38868441-ed14b61e-423e-11e8-8ed5-5a3f44d40815.PNG)

BTW, In my case, the issue only occurs if i set the locale for 'en_US', otherwise the issue won't occurs and it works fine with all the other custom locales (like 'pt', 'pt-BR', 'uk','ge', and so on...)
