### ISSUE TITLE
[primefaces 5.3] Selection row in datatable is deleted after returning from search filtering

### ISSUE THREAD

**Issue by devPro231014M2S1PJ** [primefaces/primefaces#1508]
[primefaces 5.3] Selection row in datatable is deleted after returning from search filtering

**Comment by xKopax** [comment]
Are you using lazyload?

**Comment by kukel** [comment]
And please create an [mcve] so others can try to replicate with little effort

**Comment by jxmai** [comment]
Works OK using 6.x.
