### ISSUE TITLE
PrimeFaces 6.0 Modena Bug: primefaces.css/js not found

### ISSUE THREAD

**Issue by krazun** [primefaces/primefaces#1509]
With PrimeFaces 6.0 there seems to be a problem with the Modena Layout:

`Unable to find resource primefaces, primefaces.css
Unable to find resource primefaces, primefaces.js`

The problem only appears when using the modena menu component

**Comment by mertsincan** [comment]
Fixed for next releases. Github issue; https://github.com/primefaces/layouts/issues/87
