### ISSUE TITLE
Enable the use of p:ajax for the p:ribbon component

### ISSUE THREAD

**Issue by alarive** [primefaces/primefaces#1514]
p:ribbon does not allow the use of p:ajax because it does not implement ClientBehaviorHolder. It is a bit strange because p:ribbon seems to share a lot of functionnality with p:tabView, and p:tabView allows p:ajax

**Comment by alarive** [comment]
Any idea when you plan to implement this ?

**Comment by tandraschko** [comment]
No plans currently, but you can provide a PR

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/2185
