### ISSUE TITLE
Counter actual characters in p:inputTextarea

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1517]
Counter actual characters in p:inputTextarea similar to remaining characters but this count actual characters in component

**Comment by michael-las** [comment]
The commit introduces another parameter for counterTemplate, so that the current character count may be referenced by {1}, e. g

``` html
<p:inputTextarea maxlength="50" counter="display" counterTemplate="{1} of 50, {0} remaining" />
<h:outputText id="display" />
```

Is this approach OK? If so, I'd provide a PR.

**Comment by JaviRpo** [comment]
That looks excellent.

Could this work without the parameter maxlength and {1} parameter in template? Only for progressive counting without remaining counting

**Comment by michael-las** [comment]
The commit should do it; additionally, {2} now references a given maxlength (produces 0 if none is given).

**Comment by melloware** [comment]
Is this related to #2338 ?

**Comment by tandraschko** [comment]
Looks like the same issue. Will close it.

**Comment by JaviRpo** [comment]
you should close the other issue because this is an old issue
