### ISSUE TITLE
Primeface v6.0 seems to missing primeface.js and primeface.csss

### ISSUE THREAD

**Issue by rajsinhak** [primefaces/primefaces#1523]
I just upgraded the primeface version from v5.0.3 to v6.0 , but it through an warning stating that 
Warning:   JSF1064: Unable to find or serve resource, primefaces.css, from library, primefaces.
Warning:   JSF1064: Unable to find or serve resource, primefaces.js, from library, primefaces.

Since i have growl to display message, these warning comes up on the page which is not good. i also tried to add 
<h:outputStylesheet library="primefaces" name="primefaces.css" />
<h:outputScript library="primefaces" name="primefaces.js" />

But it's still not working!!

**Comment by Karolis92** [comment]
There is no primefaces.js anymore.
Read "5.3 to 6.0" on https://github.com/primefaces/primefaces/wiki/Migration-Guide

**Comment by rajsinhak** [comment]
Thanks Karolis . 
 Although i was not importing the primeface.js and primeface.css into the application, it still gives the warning . Actually i missed to upgrade the primeface extension version and do the necessary component migration from extension to core library .
