### ISSUE TITLE
TreeTable column alignment problem

### ISSUE THREAD

**Issue by donfebi** [primefaces/primefaces#1524]
I have used primefaces 3.2 in my project. Lately I found a bug in treetable. Data column in treetable is not in line with its column header.  Please can you fix the bug. Since I am not a pro member, please tell me if there is a cost to fix this problem.

Thanks...
# Ahmad Hazairin

![treetable_pf_3 2](https://cloud.githubusercontent.com/assets/19932506/16047488/6b45973c-327a-11e6-9c9b-68c710907805.jpg)

**Comment by tandraschko** [comment]
Please try 6.0 or contact primetek via mail for a custom bugfix for this very very old version.

**Comment by donfebi** [comment]
I have contacted primetek via mail and told me to create a file in github. I don't know exactly what is "open a file in github".

I can not use higher versin such as 6.0 because I have to translate thousands line of codes in my projects.

Thanks for you reply.

**Comment by tandraschko** [comment]
Maybe you should exactly state this problem in your mail that you can't upgrade and you need a payed bugfix for a old version.
We don't do 3.2.x releases anymore.

**Comment by donfebi** [comment]
okey, I will send an email again. Thanks.

just for information, even in version 6.0, this bug is still exist.
I send the attached image that I get from showcase 6.0
![treetable_pf_6](https://cloud.githubusercontent.com/assets/19932506/16048001/9e36bae8-327c-11e6-8208-61ab040b2000.jpg)

**Comment by kukel** [comment]
please remove '3.2' from the title.

**Comment by cagataycivici** [comment]
@mertsincan Can you please review?

**Comment by melloware** [comment]
This is not happening in the latest showcase so this bug was fixed along the way.
