### ISSUE TITLE
FileUpload: auto upload bug

### ISSUE THREAD

**Issue by Karolis92** [primefaces/primefaces#1529]
If user selects many files to upload and during upload process presses `x` to remove file while it's not uploaded yet - any files after it are not uploaded and javascript errors occurre:

```
TypeError: g.row is null            fileupload.js.xhtml:1:24907
TypeError: a is null            fileupload.js.xhtml:1:29116
```

After this error upload doesn't work anymore.

I noticed, then auto upload is off - `x` buttons are disabled when upload begins, but not in auto upload mode.

`auto="false"`:
![auto-false](https://cloud.githubusercontent.com/assets/19680461/16116809/a1b290c8-33d7-11e6-948c-4e8a7957e451.JPG)
`auto="true"`:
![auto-true](https://cloud.githubusercontent.com/assets/19680461/16116810/a1ddd2d8-33d7-11e6-82fb-fe726eab9de1.JPG)

**Comment by Nikoas83** [comment]
i have the same issue !!! Its really simple to reproduce, juste create fileUpload with multiple and auto options enabled, upload files and cancel one with X button : you can see in console js browser multiple errors and the real issue that is the upload continue in background.... Test on FF and CHROME last version and Primefaces 5.3

`<h:form enctype="multipart/form-data" >
                    <p:fileUpload id="fileUploaderId" fileUploadListener="#{actionManagerBean.uploadFile}"  mode="advanced" multiple="true" auto="true" previewWidth="40"
 /></h:form>`

Errors in console : 
TypeError: g.row is null                                      fileupl...s&v=5.3 (ligne 1, col. 24948)
TypeError: a.row is null                                      fileupl...s&v=5.3 (ligne 1, col. 29157)

**Comment by kukel** [comment]
Tried PF 6 to?

**Comment by Nikoas83** [comment]
Yes. You can test on showcase, in auto mode (this is just a little difficult cause file is limit to 100ko but after many attempts...) to reproduce bug.

**Comment by Rapster** [comment]
Related to #844
