### ISSUE TITLE
ContextMenu on Datatable doesn't work anymore as expected

### ISSUE THREAD

**Issue by FuturesTr4der** [primefaces/primefaces#1530]
Hi all,

if you make a right-click on a datatable with a context-menu the underlying row is not selected anymore (in Primefaces 6). The selection works in previous versions (5.x).

For an example see showcase demo: http://primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

**Comment by tandraschko** [comment]
Probably a showcase error - the contextMenu should be placed after the datatable. Will take a look at it later.

**Comment by tandraschko** [comment]
fixed the example and added it to the migration guide.
