### ISSUE TITLE
p:editor bug on android devices

### ISSUE THREAD

**Issue by diogo-cvs** [primefaces/primefaces#1531]
I loved the component. very simple to use.
The component loses focus when selected on a android device.
Any suggestion? I'm using Primefaces-6.0 with modena theme 2.1.1 and layout.

**Comment by tandraschko** [comment]
p:editor uses cleditor under the hood which is not maintained since years. 
I would suggest to use PrimeFaces Extensions CKEditor or the new p:textEditor (which doesn't work on all browsers).
