### ISSUE TITLE
Wrong height for SelectOneMenu with SelectItemGroups

### ISSUE THREAD

**Issue by Rawi01** [primefaces/primefaces#1534]
**Problem**
The height of the SelectOneMenu is wrong if it contains less than 10 SelectItemGroups. It only counts the root elements and not the childs.

**Possible fix:**
Add something like the following method to [SelectOneMenuRenderer](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java)

``` java
private int getSize(List<SelectItem> items) {
    int sum = 0;
    for (SelectItem item : items) {
        if(item instanceof SelectItemGroup) {
            SelectItemGroup selectItemGroup = (SelectItemGroup) item;
            sum += selectItemGroup.getSelectItems().length; //Childs
        }
        sum++; //Add a direct child or the group header
    }
    return sum;
}
```

Change [line 235](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L235) to 

``` java
writer.writeAttribute("style", "height:" + calculateWrapperHeight(menu, getSize(selectItems), null);
```

Thanks

**Comment by tandraschko** [comment]
Fixed by https://github.com/primefaces/primefaces/issues/2029
