### ISSUE TITLE
Datatable core.js paginator.PAGE undefined

### ISSUE THREAD

**Issue by chuckumi** [primefaces/primefaces#1536]
Hi,
after update from version 5.3 to 6.0 I cannot load page, where is a datatable. When I inspect page I see this javascript issue:
**core.js.xhtml?ln=primefaces&v=6.0:1 Uncaught TypeError: Cannot read property 'paginator.PAGE' of undefined**

I am using **non** english chrome and issue is related with **Primefaces.locales** which is not a part of primefaces 5.3
`

**Comment by kukel** [comment]
so it works if you use an English version? And do you use a custom (other language) PrimeFaces locale file?

**Comment by chuckumi** [comment]
Aha,
after deleting my own Primefaces.locales file everything works fine :). Thx

**Comment by chuckumi** [comment]
Ok,
but now I am not able to use locales file, it is possible to download some other one?

**Comment by tandraschko** [comment]
#1506
