### ISSUE TITLE
p:outputLabel indicateRequired not showing in first page load in PF 6.0

### ISSUE THREAD

**Issue by julianomqs** [primefaces/primefaces#1539]
http://forum.primefaces.org/viewtopic.php?f=3&t=45968

@tandraschko 

I use PrimeFaces TRANSFORM_METADATA feature and BeanValidation annotations, usually @NotNull and @Size.

In PrimeFaces 5.3, when the page is loaded, the indicateRequired of outputLabel (the *) is shown, and the input has the maxlength attribute. That's the correct behavior.

But in PrimeFaces 6.0, the indicateRequired from outputLabel does not show for the first load (full load) of the page.
If the outputLabel is re-rendered with Ajax, the indicateRequired sign shows correctly.

If I reload the page, this behavior repeats.

P.S: Test case here: https://github.com/julianomqs/primefaces-bug
Just change PrimeFaces version in pom.xml to see the difference.

**Comment by CSchulz** [comment]
@tandraschko Is the feature completly removed in PF6?

**Comment by tandraschko** [comment]
No, just a bug.

**Comment by CSchulz** [comment]
Hum, I was asking because I have seen the removal of the feature in 4f0cc9254fcb544495bae7f0892ec155037b2b61.

**Comment by tandraschko** [comment]
Nope, i just removed code that doesnt work anymore
