### ISSUE TITLE
p:selectOneMenu - bug by pressing keybord button 'pause', 'scroll' or 'print'

### ISSUE THREAD

**Issue by fbberger** [primefaces/primefaces#1540]
We are using Primefaces 5.2 and have Problem with the selectOneMenu. We select an item on it and press the 'pause', 'scroll' or 'print' key. A request with an empty selection of the element will be submitted and the selected item is not longer selected.

Info: The problem is also on your showcase (http://www.primefaces.org/showcase/ui/input/oneMenu.xhtml)  

Best reqards,
Frank

**Comment by peterremec** [comment]
I just noticed this bug, too. I get the same result by using 'PrtScr', 'Insert', 'Caps Lock', 'Num Lock', 'Scroll Lock', function keys and maybe some more.  

+1 vote for this issue.

**Comment by 1451678** [comment]
+1

**Comment by erdeisz** [comment]
+1
 I get the same result with PF 6.0.13.

**Comment by melloware** [comment]
I just submitted a PR but note that PrintScreen is not gauranteed to be code 44 in all browsers!

http://stackoverflow.com/questions/31835095/keycode-for-print-screen-44-is-not-working
