### ISSUE TITLE
[Primefaces 6] Right click cannot select row in DataTable where selection and contextMenu is enabled

### ISSUE THREAD

**Issue by lumionx** [primefaces/primefaces#1543]
Right click cannot select row in DataTable where selection and contextMenu is enabled in Primefaces 6. While this issue does not exist in 5.3

**Comment by Rapster** [comment]
Duplicate #1530 ?

**Comment by cahendi** [comment]
How if I do an update on treetable context menu . when I tried to do it , the context menu doesn't show. different if I did update the context menu in the tree , it was a success .
i try it on primefaces 6.

thank before...
