### ISSUE TITLE
Caret is invisible when clicking on a second p:editor widget

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#1544]
A user has notify to me that sometimes the cursor (or caret of cursor) doesn't display in p:editor widget.

I have tested on my page that contains 3 p:editor widget.

This error occurs when widget is empty.

I click on the first p:editor that is not empty and the caret is correctly displayed.
Then I click on the second p:editor widget that is empty and the caret is not visible !!!

When I type some text, the text appear correctly in the second p:editor and then the caret is correclty displayed.

When then, I delete the typed text and try again.

The caret, this time, is correctly displayed in second empty p:editor when I click on FiRST line.
If I click on second line (or a little below the first line), the caret is again not visible.

I use Chrome Version 51.0.2704.103 m and Primefaces 6.0 and Glassfish 4.1.

**Comment by melloware** [comment]
Editor is Deprecated use p:textEditor now instead.
