### ISSUE TITLE
Datatable with toggler and sort

### ISSUE THREAD

**Issue by tiagovanderlinde** [primefaces/primefaces#1548]
If the user using the toggler hides columns in a dataTable, after to sort any column, all the hidden columns are shown up again.

dataTable example:

```
<p:dataTable`` id="cars" var="car" value="#{dtBasicView.cars}">
    <f:facet name="header">
        List of Cars

        <p:commandButton id="toggler" type="button" value="Columns" style="float:right" icon="ui-icon-calculator" />
        <p:columnToggler datasource="cars" trigger="toggler" />
    </f:facet>

    <p:column headerText="Id" sortBy="#{car.id}">
        <h:outputText value="#{car.id}" />
    </p:column>

    <p:column headerText="Year" sortBy="#{car.year}">
        <h:outputText value="#{car.year}" />
    </p:column>
</p:dataTable>
```

**Comment by jxmai** [comment]
Hi, this is not a bug from Primefaces. I also raised a similar issue (Issue #1678), but it was a duplicate issue that already has a known solution using **Stateful Column Toggler**.

The original issue: https://github.com/primefaces/primefaces/issues/96

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17873356/c7e837f6-688a-11e6-86c8-9e648f6a0aee.png)

The blog post: http://blog.primefaces.org/?p=3341

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17873390/078baa50-688b-11e6-9ee3-7261fdaa2c6e.png)
