### ISSUE TITLE
MegaMenu: activeIndex issue

### ISSUE THREAD

**Issue by chuckumi** [primefaces/primefaces#1549]
Hi,
after updating to primefaces 6.0 activeIndex stop works? Is it bug? Here is a snippet of my code

`<p:megaMenu orientation="horizontal" activeIndex="#{param.i}" styleClass="menu_top" id="menu_top">
    <p:menuitem value="CAMPAIGNS" outcome="/admin/index">
          <f:param name="i" value="0" />
     </p:menuitem>        
     <p:menuitem value="CONTACTS" outcome="/admin/contacts">
          <f:param name="i" value="1" />
     </p:menuitem> 
</p:megaMenu>`

**Comment by chuckumi** [comment]
No one has the same problem?

**Comment by tandraschko** [comment]
Would be great if you could check the problem and provide a PR to fix it!

**Comment by melloware** [comment]
I can't reproduce this using the showcase.  I set the activeIndex=2 and then proper menu option was highlighted.  Recommend marking closed or invalid.
