### ISSUE TITLE
Improve Galleria animation sync with caption text

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#155]
A minor thing, but it's annoying when you spot it.
When you have a Galleria with a longer effectSpeed you can see that the caption text changes when the fade down starts.

```
        <p:galleria value="#{MyController.banners}" var="b"
                    panelWidth="800" panelHeight="450"
                    showCaption="true"
                    showFilmstrip="false"
                    autoPlay="true"
                    effect="slide" effectSpeed="1000" transitionInterval="10000">
```

Delaying the caption change by the effectSpeed is enough to fix this in galleria.js line 201 looks like this:

```
        //caption
        if(this.cfg.showCaption) {
            this.showCaption(newPanel);
        }
```

Please can it get change to do something like this?

```
        //caption
        if(this.cfg.showCaption) {
            var _self = this;
            setTimeout(function() {_self.showCaption(newPanel);},this.cfg.effectSpeed);
        }
```

**Comment by minlwin** [comment]
<img width="1280" alt="screen shot 2015-10-09 at 10 48 23 pm" src="https://cloud.githubusercontent.com/assets/1300121/10399102/b07c2d6a-6ed6-11e5-9772-30ae3ff527d7.png">

I use galleria in a dialog, galleria filmstrip-wrapper has been shown twice. 
I use primefaces 5.2, is it a bug?
How do I solve this problem? Please help me.

**Comment by OldIMP** [comment]
> <img alt="screen shot 2015-10-09 at 10 48 23 pm" width="1280" src="https://cloud.githubusercontent.com/assets/1300121/10399102/b07c2d6a-6ed6-11e5-9772-30ae3ff527d7.png">
> 
> I use galleria in a dialog, galleria filmstrip-wrapper has been shown twice.
> I use primefaces 5.2, is it a bug?
> How do I solve this problem? Please help me.

Same problem in 6.2. See my workaround at [Stackoverflow](https://stackoverflow.com/a/55902179/5044174):
```html
<p:commandLink onclick="PF('popup').show();" update="galleria"/>
<p:dialog id="popup">
    <p:galleria id="galleria"/>
</p:dialog>
```
Is there an own issue for this problem?

**Comment by melloware** [comment]
I submitted a PR for the original issue in this ticket however @minlwin @OldIMP it sounds like your issue is different than the one described in this ticket so you should open a new ticket.
