### ISSUE TITLE
Watermark for non-editable selectOneMenu is not showing

### ISSUE THREAD

**Issue by alexey-anufriev** [primefaces/primefaces#1551]
**Preconditions**
- `selectOneMenu` with watermark
- Text input is not allowed (`editable="false"`)

**Expected behavior**
Watermark is visible

**Actual behavior**
Watermark is **not** visible

**Reason**
`selectoneMenu` with `editable="false"` uses `<label>` tag to display selected item or initial item. At the same time it uses `<input>` tag with `editable="true"`.

**Environment**
1) Primefaces 5.3.7 / JSF 2.1.28
2) Server: JBoss EAP 6

Related Primefaces forum thread:
http://forum.primefaces.org/viewtopic.php?f=3&t=45427

**Comment by alexeev** [comment]
Any news on this one?

**Comment by melloware** [comment]
Submitted PR which solves this a slightly different way if you are using an HTML5 browser. #2191
