### ISSUE TITLE
 Schedule FullCalendar API attributes needed

### ISSUE THREAD

**Issue by jorgellenes** [primefaces/primefaces#1553]
Hi,

Is there a posibility to include in Scheduler component attributes eventOrder, slotEventOverlap and eventRender from the fullCalendar API? We have overriden PF scheduler.js to achieve this by setting slotEventOverlap to false, commenting out the sorting function and changing the function from eventRender to escape HTML, but this is a nasty hack.

Thanks!

**Comment by tandraschko** [comment]
Feel free to provide a PR

**Comment by melloware** [comment]
slotEventOverlap in PF 6.2 = https://github.com/primefaces/primefaces/issues/2386

**Comment by melloware** [comment]
The rest can be done with the extender pretty easily.

```xml
<p:schedule value="#{myBean.eventModel}" ... extender="cfgSchedule"/>
        <script type="text/javascript">
          function cfgSchedule() {
            this.cfg.eventRender = function(event, element) {
                element.attr('title', event.description);
            };
          }
        </script>
```

The full calendar API is very large and Pf doesn't want to have a property for every option so that is why the extender is there.

**Comment by tandraschko** [comment]
lets reuse the extender instead of introducing 1000 attributes.
