### ISSUE TITLE
Datatable drag & drop fail on Firefox

### ISSUE THREAD

**Issue by fernandobsilva** [primefaces/primefaces#1558]
Rows gets stuck floating over the datatable if the mouse pointer passes outside the browser window.

I've observed it only on Firefox.

Is there any option or configuration to prevent this behaviour?

**Comment by tandraschko** [comment]
Feel free to fix the issue and provide a PR

**Comment by tandraschko** [comment]
Not sure but it looks fine for me.
Feel free to reopen with a more detailed description + screenshots.
