### ISSUE TITLE
Form is not submitted when press enter on non text input component

### ISSUE THREAD

**Issue by ppandey01** [primefaces/primefaces#1559]
**Problem Statement**

[The HTML5 forms specification section 4.10.22.2](https://www.w3.org/TR/html5/forms.html#implicit-submission) basically specifies that the first occuring input submit element in the "tree order" in same form as the current input element in the HTML DOM tree will be invoked on enter press.

However currently if user press enter while having focus on any non text input component (e.g. selectOneMenu, selectBooleanCheckbox etc ) then first submit button will not be invoked i.e. form will not be submitted. 
On the other side , if user press enter on any text input component (e.g. inputText, inputmask) then form is submitted. 

**Actual behavior**
Form is not submitted if user press enter while having focus on any non text  input component (e.g. select components)

**Expected behavior**
Form should be submitted when user press enter while having focus on any non text input component (e.g. select components)

**Environment**
1) Primefaces 5.3.7 / JSF 2.1.28
2) Server: JBoss EAP 6

**Sample XHTML code**
[sample](https://github.com/primefaces/primefaces/files/336569/sample_xhtml_code.txt)

**Comment by alexeev** [comment]
Any feedback from engineering after half a year?

**Comment by alexey-anufriev** [comment]
Works fine in PF 6.1.3.
Please check and close this bug.

**Comment by tandraschko** [comment]
Thanks for testing!
