### ISSUE TITLE
Clock: Value binding custom time

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#156]
I like <p:clock> to bind value to server side variable, not necessarily system clock. The clock time can be defined by application. The use case is application demo, the clock can be sometime in the future, for example, 02/15/2050.

**Comment by dmaidaniuk** [comment]
It will be quite useful feature. Currently we need such functionality and forked Clock Widget to realize it for us.

**Comment by ckirbas** [comment]
Hi,
Is this going to be available?

**Comment by melloware** [comment]
@dmaidaniuk do you have your example changes you made available for us to review?   We are considering implementing this feature.

**Comment by dmaidaniuk** [comment]
Hi @melloware ,

Unfortunately I don't have some complete implementation. As I remember we wanted such functionality in case if on server we have different from system time, forced timezone comparing to client and other similar situations.

Regards,
Dmytro
