### ISSUE TITLE
DataTable: add total row support

### ISSUE THREAD

**Issue by vanuatoo** [primefaces/primefaces#1560]
Current approach is only usable when used with grouping.

Would be nice to define which columns are "total able" and based on it the system would add total row automatically at the header or footer level or both.

To generalize this issue, aggregate type should be customizable: max, min, avg seem to be logical candidates.

Total part of the DataTable should consist of Title row and totals row

**Comment by melloware** [comment]
This is exactly what SummaryRow does: https://www.primefaces.org/showcase/ui/data/datatable/summaryRow.xhtml
