### ISSUE TITLE
Add clientCache to data components

### ISSUE THREAD

**Issue by lcanalesmayo** [primefaces/primefaces#1562]
In https://github.com/primefaces/primefaces/issues/1535 "clientCache" attribute was added to "dataTable".

Could you add this attribute in all data components that support lazy loading?

Thanks in advance,
Luis.

**Comment by tandraschko** [comment]
As the effort is quite high and it has not the a high prio for us, it would be great if you could sponsor it via PrimeFaces PRO.

**Comment by tandraschko** [comment]
Will close it for now.
We should add least create a ticket for each component itself.

Lets wait if someone needs that.
