### ISSUE TITLE
Error with PrimeExceptionHandler and error pages

### ISSUE THREAD

**Issue by rvillablanca** [primefaces/primefaces#1564]
I have several error pages located at /WEB-INF/error folder but they are not correctly found by PrimeExceptionHandler because it assumes that the page is located the root of context path.

![1](https://cloud.githubusercontent.com/assets/1508272/16452103/25ea05d8-3ddd-11e6-97c6-2c3a5a6e6e2b.png)

Then an 404 error is thrown out.
I am using Primefaces 6.0

**Comment by tandraschko** [comment]
error pages in web-inf are not supported as we need to redirect to them - we can't use a forward in every case.
As files in web-inf can't be accessed via url, it won't work.

**Comment by rho66** [comment]
Is there a chance to support error pages under /WEB-INF, because Omnifaces supports this?!

**Comment by tandraschko** [comment]
no, sorry
we just call the servlet-api to redirect/forward to this page
and serving content in WEB-INF is just not possible

We won't introduce some wrapper-hacks to support this.
