### ISSUE TITLE
p:graphicImage + CSS Image Sprites

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primefaces#1567]
eg:
`<p:graphicImage library="imagens" name="image.png" position-x="0" position-y="-416" />`

Ref: [http://www.w3schools.com/css/css_image_sprites.asp](http://www.w3schools.com/css/css_image_sprites.asp)

**Comment by tandraschko** [comment]
you can use style + background-position

**Comment by tandraschko** [comment]
Easily possible with style attribute:
<p:graphicImage ... style="width: 200px; object-fit:none; object-position: -200px -200px" />
