### ISSUE TITLE
DataTable: reflow not working correctly on IOS

### ISSUE THREAD

**Issue by darkomega9408** [primefaces/primefaces#1568]
My project is using reflow datatable to have responsive looking on mobilephone. But it is not working correctly on IPhone, although Android works fine. I have try Iphones 4 and 6 and both does not working, so I think it is IOS
-related only. Here is the screenshot on IPhone:

![img_0010 1](https://cloud.githubusercontent.com/assets/16800895/16514188/815a327c-3f94-11e6-96cd-562c5af3b363.PNG)

Here is the screenshot that working fine on Android:
![image](https://cloud.githubusercontent.com/assets/16800895/16514259/f01030d6-3f94-11e6-90c3-a2b48365f866.png)

**Comment by mertsincan** [comment]
I checked this issue on Iphone 6 and 6+. it works fine for me. 

![iphone 6_test](https://cloud.githubusercontent.com/assets/11868120/17100746/215f7574-5279-11e6-9abd-b4123b0cc0e8.jpg)

**Comment by mertsincan** [comment]
Maybe, you can try it with the following css code;

```
<p:datatable styleClass="myTable" ../>

@media (max-width: 640px) { /* you can change the value of media query. */
   .myTable.ui-datatable-reflow .ui-datatable-data td[role="gridcell"] {
       border: 0 none;
       box-sizing: border-box;
       clear: left;
       display: block;  /* or display: block !important; */
       float: left; /* or float: left !important; */
       text-align: left;
       width: 100%;
   }
}
```

**Comment by kukel** [comment]
So you add custom css, that strongly influences the positioning and flow and then say the reflow is wrong??? Maybe this css is just not triggered on Android and hence it has no problem. What if you remove the `@media` part? Does it fail on android to then?

**Comment by anuragnz** [comment]
Is there any update or workaround on this issue with iphone DataTable reflow not working?

**Comment by melloware** [comment]
@anuragnz I have never gotten it working correctly on iPhone. Haven't checked the latest 11.0-SNAPSHOT but something tells me something specific needs to be added for IOS to work.

**Comment by anuragnz** [comment]
Hi @melloware,
 
I have checked with latest build but still the same issue that DataTable is not responsive on iOS but works fine on Android.
Could you please see what could be workaround or the solution?

**Comment by melloware** [comment]
I don't work for PrimeTek but if you need this fix your could request it through PRO support or "Case Quote" on their Support page.

**Comment by melloware** [comment]
OK I just tested the Showcase Reflow on IOS 14 and its working fine. I am going to close this ticket.
