### ISSUE TITLE
ValueChangeEvent not triggered for Picklist

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1569]
Reported by PRO User;

> We are using <p:picklist .../> in our application. We noticed that ValueChangeEvent is not triggered when there is change in values (drag & drop / re-shuffle).
> This is happening from 5.3.11 update.

**Comment by marc-bouvier-dav** [comment]
Hello, is this also fixed in any future Elite 5.3.X release?

**Comment by tandraschko** [comment]
check the labels on the right side, the versions numbers are always the elite version numbers.

**Comment by marc-bouvier-dav** [comment]
Thank you, I am very new with GitHub.
