### ISSUE TITLE
Datatable paginatorAlwaysVisible="false" problem changing datasource

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1574]
When paginator is not always visible sometimes a bug occurs where the paginator is not rendered anymore when updating the datasource. 

I saw this issue before in our application but still cannot say when it will occur precisely but it is reproducable with following example:
1. Set _paginatorAlwaysVisible="false"_ and _rows="12"_ without lazy loading and load a single row of data on init
2. Press button A and load 5 rows and update table
3. Press button B and load 20 rows **paginator is not visible**
4. Press button C and load 40 rows **paginator is visible again**
5. Go back to step 3. **paginator is now visible**!

Here an image of our application where sales can be grouped by year/month/shop which clearly shows that there is more data available but paginator not rendered. (The problem is between step 2. and 3.)

http://fs5.directupload.net/images/160704/pkds73nl.jpg

**Workaround**

Set _paginatorAlwaysVisible_ to _true_.

**Comment by michael-las** [comment]
Tried to reproduce the bug without success. Which PF version is affected? Have you tried it with a reduced example (simple table, no groupings etc.)? Different browsers? Could you provide some code?

**Comment by djmj** [comment]
I will try to create a reduced example at the weekend.

**Comment by tandraschko** [comment]
Example still missing after 1,5 years. As it's a mandatory info now, i will close it.

**Comment by jepsar** [comment]
Isn't this #1715?
