### ISSUE TITLE
Regression p:inputNumber - always displays in US locale

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1575]
Updating to PF 6.0 i realized that numbers are not displayed using view locale on _p:inputNumber_.

PrimeFaces extension used view locale if no other locale was provided by default. 

Curious is also that when i enter commata _,_ as decimal separator it still recognizes it as decimal separator by rendering a US format _._ dot. Functionality is preserved but its just irritating and may have conflicts with thousand separators.

Trying to override conversion using _<f:convertNumber locale="#{view.locale}"/>_ is not working.

**Comment by tandraschko** [comment]
Please check both sources and if possible provide a PR, i think the code was just copied.

**Comment by djmj** [comment]
The minimum reproducer is just an empty _p:inputNumber_ and setting view locale to german for example.

```
        #{view.locale} <!-- prints de -->
        <p:inputNumber/>
        <p:inputNumber>
            <f:convertNumber/>
        </p:inputNumber>
        <p:inputNumber>
            <f:convertNumber locale="#{view.locale}"/>
        </p:inputNumber>
```

You should enhance your showcase using a locale aware example without specifying _decimalSeparator_.

http://www.primefaces.org/showcase/ui/input/inputNumber.xhtml

**Comment by tandraschko** [comment]
you could just compare both sources of PF and PFE and check where is the difference

**Comment by michael-las** [comment]
PR is here #1578
