### ISSUE TITLE
Datatable looses text selection with active selectionMode

### ISSUE THREAD

**Issue by nicymike** [primefaces/primefaces#1576]
When you select text inside a cell on a datatable with active selectionMode (eg. single), the selection is cleared after releasing the mouse button. This happens whether the row is already selected or not.

This issue occurs even in primefaces showcase (http://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml) on second example ("Single with Row Click").

As a workaround:
To select a text, start selecting it and then move the mouse slightly outside the cell across the border. Now the selection stays.

This problem occurs in newest Chrome, Firefox and Internet Explorer.

**Comment by mertsincan** [comment]
Please use disabledTextSelection="false" attribute on datatable.

**Comment by nicymike** [comment]
Oh! I see, it's a feature. Sorry for the bug report and thank you for the information.

**Comment by mertsincan** [comment]
No problem ;) thanks for the update!
