### ISSUE TITLE
Growl: Add client side api

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#1579]
Hi,
we use `primefaces push` to push message to client(s) in our application. I modify growl.js to : 
- add a message to `cfg.msgs`
- refresh message with `cfg.msgs` (i just call `refresh(msgs)` here)
- remove the message from the array when the message is close.

Are you interest for this feature ?

**Comment by tandraschko** [comment]
you can render new messages via:
#renderMessage

you can remove all growls and display new ones via
#show

not sure whats the difference to your features but there are some helper method available.

**Comment by Julienng** [comment]
For some treatment, I receive like 2 - 3 messages (for now) with some time between each. I don't want to erase the previous message before his timeout and don't want to redisplay message after his timeout. So I have to handle add / remove into msgs.

**Comment by tandraschko** [comment]
I see. Feel free to provide a PR.

**Comment by Julienng** [comment]
I will, I just not have time to do it right now

**Comment by tandraschko** [comment]
I added at least a new #add and #addAll method, to append messages to the current displayed messges
