### ISSUE TITLE
tabView with  activeIndex="-1" dynamic="true" cache="true"

### ISSUE THREAD

**Issue by svrolanski** [primefaces/primefaces#158]
I'm using a tabView declared as:

```
<p:tabView widgetVar="tviewAgVirtual" activeIndex="-1" dynamic="true" cache="true">
</p:tabView>
```

This way it dynamically load the tab the user chooses by clicking it.
The problem is that the last declared <p:tab> doesn't appear correctly, it is empty.

**Comment by svrolanski** [comment]
To workaround the problem, add a dummy tab before you close the tabView tag:

```
<p:tabView widgetVar="tview" activeIndex="-1" dynamic="true" cache="true">
   .... other tabs ...
  <p:tab id="dummyTab" title="dummy tab" transient="true"/>
</p:tabView>
```

With the following javascript, need to change widgetvar to suit your needs:

```
<script type="text/javascript">
  // Primefaces bug workaround
  PF('tview').remove(PF('tview').getLength() - 1);
</script>
```

**Comment by cagataycivici** [comment]
activeIndex must be 0 or greater for tabview.

**Comment by svrolanski** [comment]
I use this because it doesn't load the (first or any) tab until the user clicks on it.
Being zero or greater makes loading the first tab mandatory, so first tab is never dynamically.

**Comment by cagataycivici** [comment]
I know, this is by design. At least one tab is eagerly loaded.
