### ISSUE TITLE
Tooltip points to the wrong field when positioning is limited by space.

### ISSUE THREAD

**Issue by mrswadge** [primefaces/primefaces#1585]
Hi Primefaces team,

When the tooltip re-positions it's self from it's normal position the tooltip does not change it's styling to point correctly at the field which triggered the display of the tooltip.

An example:
A tooltip that shows by default on the right of a field tends to have the style ui-tooltip-right to give the arrow on the left of the tooltip. When there isn't enough room to display the tooltip on the right, the tooltip is clever enough to display on the left of the field. However, the tooltip arrow still points to the left.

Examples of similar issues can be seen by resizing the window for the showcase (http://www.primefaces.org/showcase/ui/overlay/tooltip/tooltipOptions.xhtml).

**Normal Behaviour:**
![image](https://cloud.githubusercontent.com/assets/6681203/16614823/30d33d78-436b-11e6-97b3-8d1df511e01e.png)

![image](https://cloud.githubusercontent.com/assets/6681203/16614845/53f00b42-436b-11e6-9b45-445fd22ca072.png)

**Incorrect Behaviour:**
![image](https://cloud.githubusercontent.com/assets/6681203/16614834/3c8b8760-436b-11e6-90c5-da17bcfdaab6.png)

![image](https://cloud.githubusercontent.com/assets/6681203/16614840/4d525ce0-436b-11e6-9956-319eadd4d54d.png)

When the position of the tooltip does the opposite to the default positioning, I feel the tooltip style ui-tooltip-left/right/top/bottom ought to be adjusted too.

Thanks,
Stuart

**Comment by mrswadge** [comment]
This fixes the issue. It appears to be up to the task and should cover all avenues that I can think of.

```
PrimeFaces.widget.Tooltip.prototype.alignUsing = function(position,feedback) {
  this.jq.removeClass('ui-tooltip-left ui-tooltip-right ui-tooltip-top ui-tooltip-bottom');
  switch (this.cfg.position) {
  case "right":
  case "left":
    this.jq.addClass('ui-tooltip-'+(feedback['horizontal']=='left'?'right':'left'));
    break;
  case "top":
  case "bottom":
    this.jq.addClass('ui-tooltip-'+(feedback['vertical']=='top'?'bottom':'top'));
    break;
  }
  this.jq.css({
    left: position['left'],
    top: position['top']
  });  
};

PrimeFaces.widget.Tooltip.prototype.align = function(align) {
  return function() {
    var that = this;
    this.jq.css({
      left: "",
      top: "",
      "z-index": ++PrimeFaces.zindex
    });
    if (this.cfg.trackMouse && this.mouseEvent) {
      this.jq.position({
        my: "left top+15",
        at: "right bottom",
        of: this.mouseEvent,
        collision: "flipfit",
        using: function(p,f) {
          that.alignUsing.call(that,p,f);
        }
      });
      this.mouseEvent = null
    } else {
      var a, b;
      switch (this.cfg.position) {
      case "right":
        a = "left center";
        b = "right center";
        break;
      case "left":
        a = "right center";
        b = "left center";
        break;
      case "top":
        a = "center bottom";
        b = "center top";
        break;
      case "bottom":
        a = "center top";
        b = "center bottom";
        break
      }
      this.jq.position({
        my: a,
        at: b,
        of: this.target,
        collision: "flipfit",
        using: function(p,f) {
          that.alignUsing.call(that,p,f);
        }
      })
    }
  };
}(PrimeFaces.widget.Tooltip.prototype.align);
```

Key parts are `var that = this;` near the top to give access to the primefaces widget config and the `using: function(p,f)` method (including the body) that is provided to the `this.jq.position` method (in two places).

**Comment by mrswadge** [comment]
Updated comment above to remove duplicate code by adding new method alignUsing to the Tooltip prototype.

Tested OK in IE11 and Chrome.

![image](https://cloud.githubusercontent.com/assets/6681203/16626279/1cc4d000-43a0-11e6-8b70-3a0c3597cfb6.png)

![image](https://cloud.githubusercontent.com/assets/6681203/16626299/2e18fe1c-43a0-11e6-92b7-6b839c6549f0.png)

**Comment by michael-las** [comment]
PR is here #1587
