### ISSUE TITLE
Components are duplicating style attribute randomly

### ISSUE THREAD

**Issue by dsu** [primefaces/primefaces#1589]
Sometimes users "Attribute style redefined" error that aborts rendering the page by browser.

for exmaple

`<h:panelGroup layout="tabular" style="display:inline;padding: 10px;position: relative;top: -6px;">`

Can generate:

```
<span style="display:inline;padding: 10px;position: relative;top: -6px;"
style="display:inline;padding: 10px;position: relative;top: -6px;">
```

**Comment by tandraschko** [comment]
h:panelGroup isn't from PrimeFaces
