### ISSUE TITLE
Label escape issue on LineChartSeries

### ISSUE THREAD

**Issue by mquasten** [primefaces/primefaces#1590]
final LineChartSeries series = new LineChartSeries();
series.setLabel(/_timeCourse.get().share().name().replaceAll("'", "")_/ "can't get you out of my head");

Firebug: 
SyntaxError: missing } after property list
bad java script code is created: 
... series:[{label:'can't get you out of my head',renderer: $.jqplot.LineRenderer, ....

The chart of the share McDonald's Corp. makes trouble ( the ' in the name )

**Comment by michael-las** [comment]
@tandraschko @cagataycivici This makes it possible to inject arbitrary JavaScript code. Multiple, if not all, chart types are affected. The chart renderers write labels etc. unescaped to the output.
