### ISSUE TITLE
PrimeFaces Extensions Migration: DynaForm

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1591]
Very useful component: [see showcase](http://www.primefaces.org/showcase-ext/views/dynaForm.jsf), maybe it should be reimplemented using UIData?

**Comment by Rapster** [comment]
@ova2 says

> Normally we can build a form quite straightforward by h:panelGrid oder p:panelGrid if the count of rows / columns, positions of elements, etc. are known. That's true for static forms. But it's not possible to use h:panelGrid oder p:panelGrid if a form is described dynamically, at runtime. E.g. if the entire form's definition is placed in a database or a XML file.
> DynaForm makes possible to build a dynamic form with labels, inputs, selects and any other elements by model. There aren't limitations.

It's actually much more powerfull. No matter form is described dynamically, because DynaForm allows you to

-  Make your pages uniform. Create one DynaForm containing all your display possibilities and use it as a composite, and no matter what your change is, it'be spread all over your pages.

- Stop using JSTL or rendered attribute if you have some UI rendering logic. Your model is built with Java, it's easier, more readable and performance are better (JSF Tree won't be overloaded by unrendered component if JSTL used) as shown in the snapshot above. It shows JSF Component Tree before and after we decided to use DynaForm.

![components-jsf-spark-blur](https://cloud.githubusercontent.com/assets/7521311/20515961/48e19ce8-b094-11e6-9ca7-fff934b29f03.jpg)

It seems obvious to me that DynaForm should be part of the Primefaces Core

**Comment by tandraschko** [comment]
I will close it for now. It's fine for now in PFE and i think we have other important stuff to work on instead of migrate/partially reimplement such ac omponent.

**Comment by Rapster** [comment]
Agreed. Thomas, it's not the first time you're mentionning there are more important stuff to work on, it'd be nice to list them, why not using board of github? https://help.github.com/articles/about-project-boards/

**Comment by tandraschko** [comment]
It's not that i talk about specific issues - but our bug reports are growing and growing :/
I think the last really big change for 6.3 from the community are the OWASP thing and maybe CSP if it's ready. 
6.3 is planned for Q4 and i'm away the whole september (holiday in japan).

My goal, before 6.2 last year, was to get below 500 issues in github :D

**Comment by melloware** [comment]
@tandraschko A month in Japan!   This place will fall apart without you!

My thoughts:

1. CSP integration is a good thing and since its configurable with a web.xml Context Param people don't have to use it if they don't want to but i think it makes PF more secure.

2. Our bug list needs a good review.  Of the 600+ items I would say easily 150-200 are for the Datatable or just flat out no example, old, or invalid.  Some are users not having enough info, or "forum post" like issues of "my sorting and filtering doesn't work".

**Comment by Rapster** [comment]
Ah I see, I think if developers was more willing to fix their own bug (and I think they'd able to do it). We'd have less than 500 issues. But I don't think they are aware that we're only ~5 people working on our free time... Maybe they knew this, they'll make an effort :wink: Let's write a blog post! :yum: 

Enjoy Japan, it's a beautiful country and very interesting culture

**Comment by tandraschko** [comment]
Thanks :)

Yep, ~200 issues are DataTable
Probably 100-200 without good example - but sometimes it's a hard decision to close them as they are "easy" to replicate, also without full example.
But feel to review them and close them :)
