### ISSUE TITLE
ColumnToggler items are polluted with text from controls and even java script code

### ISSUE THREAD

**Issue by Treppenhouse** [primefaces/primefaces#1592]
When adding more complex controls than just `h:outputText` to the header of a column, all the text that can be found within those controls is added to the label of the columntoggler-item in the column toggler for the respective column.

For instance, when having a `SelectOneMenu` control in the column header, all values to chose from are concatenated and added to the columntoggler-item label.
Additionally, any JavaScript code that corresponds to each value is added as well. (This affects tooltips as well for example)

It would be cool to at least be able to specify the 'label'  manually in case that it is too difficult to differentiate between the text in the column that is actually visible (or let's say 'meaningful' as a label for the column toggler item) and all the text that can be found within the html element subtree.

**Comment by kukel** [comment]
which version? small example?

**Comment by Treppenhouse** [comment]
Sorry for the late response but here is one now.

I am using PrimeFaces Community version 6.0.

This is the .xhtml code:

```
<p:dataTable id="testTable">
            <f:facet name="header">
                <p:commandButton id="toggler" type="button" value="Toggle columns" icon="ui-icon-calculator" />
                <p:columnToggler datasource="testTable" trigger="toggler" />
            </f:facet>
            <p:column >
                <f:facet name="header">
                    <h:outputText id="text_id" value="Column 1">
                        <p:tooltip for="text_id">
                            <h:outputText value="Don't show me" />
                        </p:tooltip>
                    </h:outputText>
                </f:facet>
            </p:column>
            <p:column headerText="Column 2" />
</p:dataTable>

```

When clicking on the column toggler, the menu should offer two entries: Column 1 and Column 2. Instead it shows this:
![primefacesbug](https://cloud.githubusercontent.com/assets/19527944/21386358/b95f840e-c772-11e6-921e-a8c91e6be9d7.png)

**Comment by kukel** [comment]
You nest a tooltip INSIDE an outputText... That is not very common and can lead to unexpected behaviour. Does it fail if it is outside the outputText to? And what if you put the tooltips even outside the datatable?

**Comment by Treppenhouse** [comment]
~~Great this works!~~
Argh, it still does not work.

When the tooltip is put outside the f:facet (outside the h:outputText is not enough) but inside the table (putting it outside the p:dataTable does not work as the id can't be found in that case) the text in the column toggler is presented nicely. However, the tooltip does not work anymore, it is not shown! Try it out with the code below. The text in the column toggler is now as expected but the tooltip won't show up anymore:

```
 <p:dataTable id="testTable">
                    <f:facet name="header">
                        <p:commandButton id="toggler" type="button" value="Toggle columns" icon="ui-icon-calculator" />
                        <p:columnToggler datasource="testTable" trigger="toggler" />
                    </f:facet>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText id="text_id" value="Column 1">
                            </h:outputText>
                        </f:facet>
                        <p:tooltip for="text_id">
                            <h:outputText value="Don't show me" />
                        </p:tooltip>
                    </p:column>
                    <p:column headerText="Column 2" />
</p:dataTable>

```

**Comment by sarvigalava** [comment]
This is the fix I used (columntoggler.js): 

children = column.children('.ui-column-title'); var columnTitle; if (children.children('.ui-custom-title').length !== 0) { columnTitle = children.children('.ui-custom-title').text(); } else { columnTitle = children.text(); }

**Comment by sarvigalava** [comment]
And use like this: <h:outputLabel for="details" value="#{msg.details}" styleClass="ui-custom-title" /> inside header facet

**Comment by sarvigalava** [comment]
[aaa.txt](https://github.com/primefaces/primefaces/files/2256784/aaa.txt)

**Comment by melloware** [comment]
I chose a slightly different path for fixing it by simply searching for the first "label" inside the facet so if you have a <h:outputText> or <p:outputLabel> it would use that text.  While still being backwards compatible for headerText="xxx".

**Comment by ravihariharan** [comment]
Refer Documentation : ColumnToggler: Label Issue on ColumnToggler (#5062)
