### ISSUE TITLE
disable() is not working on widget returned by PrimeFaces.getWidgetById()

### ISSUE THREAD

**Issue by orange-buffalo** [primefaces/primefaces#1593]
Please consider the simple case from [this gist](https://gist.github.com/orange-buffalo/82b196daae26c997de317fd9e3ba2785). It is expected that `PrimeFaces.getWidgetById('tstForm:tstBtn').disable()` will disable the button, but this does not happen (actually, nothing happens). If `update` attribute is removed from `Show dialog` button, everything is working fine. It looks like after updating the element on ajax call widget registry contains invalid object. 

Version 5.3.14

**Comment by tandraschko** [comment]
workaround: remove appendTo

**Comment by orange-buffalo** [comment]
@tandraschko Thanks for workaround. Unfortunately, for our case it is not applicable, as with complex layout and templating confirmation dialog appears under the backdrop overlay, which makes it inaccessible.

Is there any chance to backport this fix to 5.3 ?

**Comment by tandraschko** [comment]
I'm sorry but i don't have any time to provide my bugfixes in elite currently. As you may know, i just do it in my freetime.

**Comment by orange-buffalo** [comment]
Yes, sure. Thank you for help!

**Comment by mertsincan** [comment]
Added to 5.3.15 and 6.0.2. Thanks @tandraschko.

**Comment by orange-buffalo** [comment]
Great news, thanks!
