### ISSUE TITLE
JQPlot Charts: Problem with IL8N

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#1597]
Charts with xAxis as dateAxis does't localize days and months. E.g. the date Jan 5, 2016 is always showed in English.

In Primefaces 5.3.11 charts i18 was fine.

Thanks
Luca

**Comment by kukel** [comment]
In what version does it fail?

**Comment by ghost** [comment]
We’re using primefaces 6.0.

Thanks
Luca
