### ISSUE TITLE
http://primefaces.github.com still shows the 'unofficial' primefaces releases

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#16]
Should be corrected I think ;-)

**Comment by srbala** [comment]
Cagatay needs to create a repository named 'primefaces.github.io', create gh-pages branch (online seettings interface would help) and push a index page redirects to primefaces.org

**Comment by brunolmfg** [comment]
Almost that. In an user or organization site should be used the **master** branch to publish the pages. The **gh-pages** branch is only for project sites hosting the pages in the same repository.

But what is the problem of keeping the unofficial site active for a few weeks?

**Comment by kukel** [comment]
No problem at all, but maybe an explicit referal then that in the not to distant future they will be reachable via a different url would even be better. And @brunolmfg, thanks, compliments for your actions. And maybe the UR will get more attention (unfortunately I cannot participate since I have access to the Elite versions...)

**Comment by cagataycivici** [comment]
Fixed now, redirects to primefaces.org, thanks.
