### ISSUE TITLE
Dialog Framework: JSF 2.2 FlowScope support

### ISSUE THREAD

**Issue by ciukstar** [primefaces/primefaces#1601]
In my current project I use a lot of DialogFramework. Nested Dialogs are great (I used pe:masterDetail). Thanks guys! It will be nice and more effective to make use of JSF 2.2 Flow Scope. I performed some tests and it seems that upon action="#{myBean.openDialog('outcomeToSomeFlowId')}" there is no flowScope. That is, from a view that is outside of any flow, I cannot 'enter' a flow by openning a dialog with DialogFramework. Thanks.

**Comment by tandraschko** [comment]
Feel free to provide a PR which implements this feature

**Comment by ciukstar** [comment]
What is a PR?

**Comment by Rapster** [comment]
Pull Request: https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/

**Comment by ciukstar** [comment]
Stale
