### ISSUE TITLE
export component UTF-8 file name support

### ISSUE THREAD

**Issue by JasonQuan** [primefaces/primefaces#1603]
PF version 6.0
org.primefaces.component.export.ExcelExporter.java

protected String getContentDisposition(String filename){
       return "attachment;filename="+URLEncoder.encode(filename,"UTF-8")+".xls";
}

**Comment by GithubJohn3031** [comment]
This solution doesn't work correctly if filename contains spaces or some other characters.  Please see: https://github.com/primefaces/primefaces/issues/1312
