### ISSUE TITLE
autocomplete does not work in IE11

### ISSUE THREAD

**Issue by antEatOaktree** [primefaces/primefaces#1605]
My web application is using primeface 4.0.  I develop the application on my local computer (windows 7), then move it into windows2012 testing server.  Both are running the same war file in same version of tomcat. 
 When I open two tabs in the IE 11 browser, the first tab URL points to local server (win7), the 2nd tab URL points to remote win2012 server.  The autocomplete works in the first tab, but not work in 2nd tab.  And all the input on the page in the 2nd tab looks very sharp , losing its radius. 

By the way, autocomplete in my app works fine in Firefox and Chrome

**Comment by tandraschko** [comment]
does it work with 6.0 in the showcase?

**Comment by antEatOaktree** [comment]
yes.  autocomplete in showcase6.0 works in the same IE browser

**Comment by antEatOaktree** [comment]
code is simple:

   <p:autoComplete id="pid"  value="#{requestBean.requestInfo.coa}" completeMethod="#{configBean.completeSpeedkey}"
                              var="coa" itemLabel="#{coa.speedkey}" itemValue="#{coa}"   converter="coaConverter"     >
                 <p:column>
                  <h:outputText value="#{coa.speedkey}" />
                 </p:column>
 
                <p:column>
                    <h:outputText value="#{coa.description}" />
                </p:column>
        </p:autoComplete>

**Comment by antEatOaktree** [comment]
` <p:autoComplete id="pid"  value="#{requestBean.requestInfo.coa}" completeMethod="#{configBean.completeSpeedkey}"
                              var="coa" itemLabel="#{coa.speedkey}" itemValue="#{coa}"   converter="coaConverter">
                 <p:column>
                  <h:outputText value="#{coa.speedkey}" />
                 </p:column>
 
                <p:column>
                    <h:outputText value="#{coa.description}" />
                </p:column>
        </p:autoComplete>`

**Comment by antEatOaktree** [comment]
<p:autoComplete id="pid"  value="#{requestBean.requestInfo.coa}" completeMethod="#{configBean.completeSpeedkey}"  var="coa" itemLabel="#{coa.speedkey}" itemValue="#{coa}"   converter="coaConverter">
                 <p:column>
                  <h:outputText value="#{coa.speedkey}" />
                 </p:column>
                 <p:column>
                    <h:outputText value="#{coa.description}" />
                </p:column>
        </p:autoComplete>

**Comment by tandraschko** [comment]
so why do open this issue? upgrade PF and should likely work in your application, too

**Comment by antEatOaktree** [comment]
oh, I did not deploy showcase war on my win2012 server to test if autocomplete work. I only know showcase on your web site works.  I  can not think of any possible cause that the IE tab pointing win7 works but the tab pointing to win2012 does not.   Could you please give me some hint?  It's the same tomcat , the same application war file.

**Comment by tandraschko** [comment]
try the showcase on your server but i'm sure this is not related to PrimeFaces.
maybe there some resource requests fails? check out firebug.
Nevertheless, it's more a forum topic then a issue. I will close it for now.
