### ISSUE TITLE
Connect between category and subcategory in jsf

### ISSUE THREAD

**Issue by Rapter1990** [primefaces/primefaces#1609]
I devised a sample category with subcategory module in jsf by eclipse. I made an adding category module without any issue but I couldn't make an adding subcategory under related category . How do I solve the issue. Here the code below.

Suncategory .xhtml

<h:form>

```
<p:panelGrid columns="2">

    <h:outputLabel value="Category Name></h:outputLabel>

    <p:selectOneMenu value="#{subCategoryMB.categoryName}">
        <f:selectItem itemLabel="Select Category" itemValue=""></f:selectItem>
        <f:selectItems value="#{subCategoryMB.categorylist}" />
    </p:selectOneMenu>

    <h:outputLabel value="Category Name"></h:outputLabel>
    <p:inputText value="#{subCategoryMB.subcategory.subName}"></p:inputText>

    <h:outputLabel value="Category Description"></h:outputLabel>
    <p:inputText value="#{subCategoryMB.subcategory.subNameDes}"></p:inputText>

    <h:commandButton value="Add Subcategory" action="#{subCategoryMB.addSubCategory()}"></h:commandButton>


</p:panelGrid>
```

/h:form
</h:body

Category Dao

public List getAllcategoriesbyName(String name) {
// TODO Auto-generated method stub
Session session = HibernateUtil.getSessionFactory().openSession();

```
try {

    List<Category> liste = session.createQuery("SELECT c FROM Category C where lower(name)='"+name+"'").list();
    liste.toString();
    return liste;


} catch (Exception e) {
    e.printStackTrace();

}finally {

    session.close();

}
return null;
```

}
SubCategoryMB

public class SubCategoryMB {

SubCategory subcategory = new SubCategory();

private String categoryName;
private List<Category> categorylist;
private List<SubCategory> subCategoryList;
private Category category= new Category();

public SubCategoryMB() {
    // TODO Auto-generated constructor stub
}

public SubCategory getSubcategory() {
    return subcategory;
}

public void setSubcategory(SubCategory subcategory) {
    this.subcategory = subcategory;
}

public List<Category> getCategorylist() {
    CategoryDAO cDao = new CategoryDAO();
    this.categorylist= cDao.getAllcategoriesSelectItemName();
    return categorylist;
}

public void setCategorylist(List<Category> categorylist) {
    this.categorylist = categorylist;
}

public String getCategoryName() {
    return categoryName;
}

public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
}

public Category getCategory() {
    return category;
}

public void setCategory(Category category) {
    this.category = category;
}

public List<SubCategory> getSubCategoryList() {
    SubCategoryDAO subDao = new SubCategoryDAO();
    this.subCategoryList= subDao.getAllSubcategories();
    return subCategoryList;
}

public void addSubCategory(){

```
       // ISSUE
categorylist= new CategoryDAO().getAllcategoriesbyName(categoryName);
System.out.println(categorylist.get(0));
//category.setId(categorylist.get(0).getId());  
//subcategory.setCategory(category);
//subcategory.setSubName(subcategory.getSubName());
//subcategory.setSubNameDes(subcategory.getSubNameDes());
//new SubCategoryDAO().addSubCategory(subcategory);
```

}
}

**Comment by Rapster** [comment]
First, I don't understand what the problem is as it's not clear... Secondly, I don't think it is related to Primefaces

**Comment by Rapter1990** [comment]
I just said that I couldn't add subcategory under its category.  How I can devise addSubcategory() function in SubCategory which is my issue.

**Comment by Rapster** [comment]
Again, it's not a Primefaces issue. Use forum for this

**Comment by tandraschko** [comment]
use the forum for questsions.
