### ISSUE TITLE
PrimeFaces 6.0 Calendar JS Console Error Messages

### ISSUE THREAD

**Issue by julianomqs** [primefaces/primefaces#1610]
Hello,

When I enter a date in the p:calendar with mask via keyboard, some JS messages pop in browser console.

```
Error parsing the date string: Extra/unparsed characters found in date: ___
date string = 15-07-2___
date format = dd-mm-yy
jquery-plugins.js.xhtml?ln=primefaces&v=6.0.1:317 Error parsing the date string: Extra/unparsed characters found in date: ___
date string = 15-07-2___
date format = dd-mm-yy
jquery-plugins.js.xhtml?ln=primefaces&v=6.0.1:317 Error parsing the date string: Extra/unparsed characters found in date: __
date string = 15-07-20__
date format = dd-mm-yy
jquery-plugins.js.xhtml?ln=primefaces&v=6.0.1:317 Error parsing the date string: Extra/unparsed characters found in date: __
date string = 15-07-20__
date format = dd-mm-yy
jquery-plugins.js.xhtml?ln=primefaces&v=6.0.1:317 Error parsing the date string: Extra/unparsed characters found in date: _
date string = 15-07-201_
date format = dd-mm-yy
jquery-plugins.js.xhtml?ln=primefaces&v=6.0.1:317 Error parsing the date string: Extra/unparsed characters found in date: _
date string = 15-07-201_
date format = dd-mm-yy
```

More info:

PrimeFaces version:
6.0 (I only tested in this version)

Browsers:
Chrome 51.0.2704.103 m
Firefox 47.0.1

How to reproduce:
Enter date via keyboard in a p:calendar with mask

This error can be reproduced in showcase:
http://primefaces.org/showcase/ui/input/calendar.xhtml

Enter a date in the "Mask" field.

Problems:
Even with these JS error messages, the p:calendar component seems to be working normally (the dates are correctly submitted).

P.S.: I dunno if this situation was reported already, but I searched in the Github issues and PrimeFaces forum, and I could find anything about it, so I'm reporting.

**Comment by tandraschko** [comment]
I can't reproduce it with mask however the same appears if you type in the "Datetime" example. This comes from jquery datepicker, see: https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/643

Maybe you can state the steps to reproduce your error, it works fine for me.

**Comment by luiscardozo** [comment]
I can reproduce it, as @julianomqs said, with a p:calendar on PrimeFaces 6.0, and even in the showcase.

**Steps to reproduce:**
1) Go to the PrimeFaces Calendar [Showcase](http://primefaces.org/showcase/ui/input/calendar.xhtml)
2) Open the JavaScript console (Ctrl+Shift+J)
3) Go down to the "Mask:" input field and type a date.
4) There is no problem when typing month and day. But the warning appears when you start typing the year:

> Error parsing the date string: Extra/unparsed characters found in date: ___
> date string = 01-01-2___
> date format = dd-mm-yy

I can reproduce the errors with
* Chrome 54.0.2840.100
* Firefox 47.0
* Firefox Developer Edition 52.0a2
All of them on an Ubuntu Linux 14.04, 64 bits.

As I understand, it could be a problem in the way that PrimeFaces uses the jquery datepicker

**Comment by sudheerj** [comment]
I can able to replicate the issue.The same issue occurs in PrimeNG schedule too.

**Comment by tandraschko** [comment]
As we upgraded jquery, which seems to be related as stated here: trentrichardson/jQuery-Timepicker-Addon#643, could someone retest it with trunk?

**Comment by amenegotto** [comment]
Hello,
I tested with 6.2-SNAPSHOT cloned right now and the problem does not reproduce anymore.

I was planning a migration from 5.3 to 6.1 but now I will wait until 6.2.
