### ISSUE TITLE
FileUpload advanced multiple mode don't open selection file pop up On fireforx 17.0.7 esr with specific css

### ISSUE THREAD

**Issue by JjBenoit** [primefaces/primefaces#1612]
you can show that bug directly on the primefaces showcase

FileUpload advanced multiple mode :
 with the bootstrap css the pop up opens 
with sunny css pop up don't

**Comment by tandraschko** [comment]
firefox 17 is outdated and it works fine in a newer version

Does it work for the newest 17 version?

**Comment by JjBenoit** [comment]
yes of course is out dated bu some compagnies must deal with it .
the trouble is the font 'Segoe UI' in   :

  .ui-widget input,
 .ui-widget select,
 .ui-widget textarea,
 .ui-widget button {
    font-family: Segoe UI,Arial,sans-serif;
    font-size: 1em;

**Comment by tandraschko** [comment]
but whats the problem with it?
you could try that:
font-family: 'Segoe UI',Arial,sans-serif;

**Comment by JjBenoit** [comment]
not work 

just delete that font solve the problem
font-family: ,Arial,sans-serif;

that font name Segoe UI is present  in certain themes of  'all-themes-1.0.10.jar'

**Comment by JjBenoit** [comment]
Bug 835204 - "Segoe UI Light" not recognized as a font-family name (was: Font will not display)
https://bugzilla.mozilla.org/show_bug.cgi?id=835204
