### ISSUE TITLE
SelectEvent in timeline not triggered!

### ISSUE THREAD

**Issue by pjomcsJAVA** [primefaces/primefaces#1613]
<fieldset class="scheduler-border">
    <legend class="scheduler-border">#{msg['tp_list']}</legend>
            <p:timeline id="timeline" value="#{nav.model}" height="450px" selectable="#{nav.selectable}" zoomable="#{nav.zoomable}" moveable="#{nav.moveable}" stackEvents="#{nav.stackEvents}" axisOnTop="#{nav.axisOnTop}" eventStyle="#{nav.eventStyle}" showCurrentTime="#{nav.showCurrentTime}" showNavigation="#{nav.showNavigation}">

        <p:ajax event="select" listener="#{nav.onSelect}" />
        </p:timeline>
</fieldset>

The select ajax event os never called! :( Can anyone help please!

**Comment by Rapster** [comment]
Use forum for this, and other thing, give more detail/code in your post

**Comment by tandraschko** [comment]
Exactly
