### ISSUE TITLE
TreeTable selection: option to disable selection to propagate up

### ISSUE THREAD

**Issue by bgonzalez2** [primefaces/primefaces#162]
Please add an option to disable the propagation of a selection upwards on the tree table.

**Comment by bgonzalez2** [comment]
This function will be similar to the propagateSelectionUp attribute on the Tree component.

**Comment by sudheerj** [comment]
This issue can be changed to cover both propagateSelectionUp and propagateSelectionDown attributes for TreeTable component similar to Tree component.

**Comment by bgonzalez2** [comment]
You can simply override their javascript code in your system.  Just add the following lines of code at javascript and it will take care of the checkbox propagation.  

//--------Override Primefaces JS
PrimeFaces.widget.TreeTable.prototype.propagateUp = function(node) {
       //do nothing
}
//--------Override Primefaces JS
PrimeFaces.widget.TreeTable.prototype.propagateDown = function(node) {
       //do nothing
}

**Comment by JHookDev** [comment]
@bgonzalez2 What version of Primefaces did the javascript override work in for preventing TreeTable checkbox selection propagation? Specifically for the propagateDown override. The propagateUp override works in Primefaces 6.1, but there is no propagateDown function to override.

**Comment by bgonzalez2** [comment]
I am still on 5.2.  I can't upgrade due to issue 244.

**Comment by valentinlourteau** [comment]
@JHookDev A bit late, but if ever someones ends up here :
Primefaces has removed propagateDown from API, you may replace it by the function getDescendants :

PrimeFaces.widget.TreeTable.prototype.getDescendants = function(node) {
    emptyNodes= [];
    return emptyNodes;
}
