### ISSUE TITLE
XSS via "legend" attribute in p:fieldset

### ISSUE THREAD

**Issue by vbrandl** [primefaces/primefaces#1623]
Values submitted via the "legend" tag in p:fieldset aren't escaped and open a possibility for XSS attacks.
Example code:

``` html
<p:dataScroller value="#{someBean.someListOfObjects}" var="obj">         
    <p:fieldset toggleable="true" toggleSpeed="500" legend="#{obj.attribute1}">
        <p:outputLabel value="#{obj.attribute2}" />
    </p:fieldset>
</p:dataScroller>
```

Where obj.attribute1 is

``` javascript
<script>alert(1);</script>
```

The JS code gets executed which leads to a XSS.
A simple fix would be using f:facet instead of the legend attribute

``` html
<p:dataScroller value="#{someBean.someListOfObjects}" var="obj">         
    <p:fieldset toggleable="true" toggleSpeed="500" legend="#{obj.attribute1}">
        <f:facet name="legend">
            <p:outputLabel value="#{obj.attribute1}" />
        </f:facet>
        <p:outputLabel value="#{obj.attribute2}" />
    </p:fieldset>
</p:dataScroller>
```

But I think the behaviour should be the same when using f:facet or the attribute. 
If it is intended for "legend" not to be escaped, this "feature" should be documented anywhere.

**Comment by mertsincan** [comment]
Added escape attribute to Fieldset component. Default value is "true".
