### ISSUE TITLE
Default sorting for data table is ignored when sort mode "multiple" is set.

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#1626]
### Description:

A data table with a lazy data model should sort the rows by default by a certain column. Also the attribute "sortMode" is set to "multiple".
### Problem:

The rows of the data table are not sorted by default. But it works if attribute "sortMode" is set to "single".

**Comment by kukel** [comment]
What version of PF are you using?

**Comment by ltlBeBoy** [comment]
I use PF 6.0. But PF 5.3 has the same problem.

It's quite interesting:
In my project I use a _LazyDataModel_. On debugging I can see that the _SortMeta_ is _null_ on initial page call. Now I created a sample project with the backing bean and service from the [Primefaces showcase](http://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml). I modified the facelet like this:

``` html
       <p:dataTable sortBy="#{car.brand}" sortMode="simple"
                     value="#{dtBasicView.cars}" var="car">
            <p:column headerText="Id"
                      sortBy="#{car.id}">
                <h:outputText value="#{car.id}" />
            </p:column>

            <p:column headerText="Year"
                      sortBy="#{car.year}">
                <h:outputText value="#{car.year}" />
            </p:column>

            <p:column headerText="Brand"
                      sortBy="#{car.brand}">
                <h:outputText value="#{car.brand}" />
            </p:column>

            <p:column headerText="Color"
                      sortBy="#{car.color}">
                <h:outputText value="#{car.color}" />
            </p:column>
        </p:dataTable>
```

When I change _sortMode_ to _multiple_ I get a _NullPointerExcpetion_ because in PF method _org.primefaces.component.datatable.feature.SortFeature#multiSort(FacesContext, DataTable)_ the _SortMeta_ is also _null_.

**Comment by cagataycivici** [comment]
You need to provide a list of sort meta in multiple mode.
