### ISSUE TITLE
p:repeat should not require the attributes: varStatus, offset, step, size

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#1627]
In the taglib description the attributes for p:repeat varStatus, offset, step, size are marked as required. 
The should not be required as in ui:repeat.

**Comment by tandraschko** [comment]
Please provide a PR

**Comment by OBreidenbach** [comment]
PR: https://github.com/primefaces/primefaces/pull/1714

**Comment by tandraschko** [comment]
Applied, thanks
