### ISSUE TITLE
Implement  'use uncompressed resources' like in PFE

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#1628]
The 

```
 <context-param>
   <param-name>org.primefaces.extensions.DELIVER_UNCOMPRESSED_RESOURCES</param-name>
   <param-value>true</param-value>
 </context-param>
```

Can be very useful for people trying to find/fix/override things in the JS without the need to fully download the source and build a version with uncompressed resources. The amount of data in the jar should not be an issue, it is not that much). It could even be deduced or always active if the app is running in JSF Development Mode.

**Comment by tandraschko** [comment]
we discussed it several times in the past and we decided to not do it as it blows up the jar.
if you need to debug, you can still build PF by source as it will only be compressed with the release mvn profile.

**Comment by tandraschko** [comment]
we discussed it several times in the past and we decided to not do it as it blows up the jar. (me was the +1 ;))
if you need to debug, you can still build PF by source as it will only be compressed with the release mvn profile.

**Comment by kukel** [comment]
'blows up the jar'... Then please explain why there is compressed components.js AND each individual compressed js file of each component is also there. If you replace the latter with the uncompressed versions, the jar size changes from 3.9 to 4.2 MB... If that is 'blowing up' then shoot me...  (the -1 is me ;-)) 

p.s. I should have added this to the initial post since I already investigated this...

**Comment by tandraschko** [comment]
that may be a bug and should be remove of course :P

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/issues/1641

**Comment by kukel** [comment]
A bug that existed in 5.3, 5.2, 5.1, 5.0 (did not check older versions) and obviously nobody thought the jar was bloated. Why not just replace it... Everybody happy... PF with a new feature etc... Then things like http://showcase.omnifaces.org/resourcehandlers/CombinedResourceHandler become easier... Or http://showcase.omnifaces.org/resourcehandlers/CDNResourceHandler

**Comment by tandraschko** [comment]
it was not my decision - if you would also copy all uncompressed resources to the jar, the jar size would be increased around 1-1,5 MB.

**Comment by kukel** [comment]
I know it was not your decision... and yes it would grow, but not compared to how it 'was' the last few years... only <400k... Well... I would be so useful if on e.g. stackoverflow I could say: set this parameter in your web.xml set a breakpoint in such and so js file and 'debug'....

**Comment by tandraschko** [comment]
why 400k?
its actually around 1500kb

**Comment by kukel** [comment]
Compared to the current jar (3.9MB with both the 'compressed components.js' and each compressed individual component .js file (e.g. dialog.js) the increase when the latter are removed and replaced by the uncompressed individual ones, the increase of the zipped jar is around 400k, I tried.

So compared to the jars of the last 2.5 years, it will only grow with this amount. Compared to the one you are about to create without all the individiual compressed .js files, yes, it will grow with about 1.5-2 MB

**Comment by tandraschko** [comment]
not sure if i understand you but currently we have jar with compressed and aggregated resources only
i don't compare to the jar we build yesterday, today we the aggregation source files

if we would build the jar now from source, with both compressed+aggregated and uncompressed+aggregated, the jar will grow around 1-1,5mb compared to trunk now
