### ISSUE TITLE
Tabview in Omega theme don´t show focus state in "right" way

### ISSUE THREAD

**Issue by maol74** [primefaces/primefaces#1629]
se http://www.primefaces.org/omega/panel.xhtml image below

![image](https://cloud.githubusercontent.com/assets/1272327/17157707/7171f622-5391-11e6-92d9-fa90d8af0b3b.png)

**Comment by maol74** [comment]
One way to fix this is to add the following css to the a-tag **only** if the tab is closeable

```
margin-right: -20px;
padding-right: 25px;
```

**Comment by tandraschko** [comment]
There border should not be there, it's the deafult chrome outline. We removed it.
