### ISSUE TITLE
p:password throws NullPointerException when rendered attribute is active

### ISSUE THREAD

**Issue by f4bi0luciano** [primefaces/primefaces#1631]
When I use some expression in the rendered attribute, the component is leaving the field value to null.

Example: (its work)
`<p:outputLabel value="Senha de Acesso:" for="senha1" />
                <p:password id="senha1" label="Senha de Acesso:"
                    value="#{cadastroUsuarioBean.usuario.senha}"
                    feedback="true"
                    promptLabel="A senha deve possuir pelo menos 8 dígitos. Contendo pelo menos duas letras e dois números."
                    weakLabel="Fraca" goodLabel="Média" strongLabel="Forte"/>`

Does not work
`<p:outputLabel value="Senha de Acesso:" for="senha1" />
                <p:password id="senha1" label="Senha de Acesso:"
                    value="#{cadastroUsuarioBean.usuario.senha}"
                    feedback="true"
                    promptLabel="A senha deve possuir pelo menos 8 dígitos. Contendo pelo menos duas letras e dois números."
                    weakLabel="Fraca" goodLabel="Média" strongLabel="Forte"
                    rendered="#{cadastroUsuarioBean.usuario.novo}"/>`
Using this way the value for the field is null.

Function that validate if or not to render the component
`@Transient
    public boolean isNovo() {
        return getMatricula() == null;
    }`

**Comment by hatspencer** [comment]
Are you 110% sure that `#{cadastroUsuarioBean.usuario}` is not null?

**Comment by tandraschko** [comment]
And please provide a working example based on the showcase

**Comment by f4bi0luciano** [comment]
@hatspencer I believe so, because only when I put this attribute "rendered" with the same expression the error happens. I made the change to see if it had to do with my expression, putting the readonly attribute with the same expression when the situation is reached (editing) the field is locked for editing (goal).

@tandraschko I'll try to see if I can play the same situation in a separate project.

**Comment by lcanalesmayo** [comment]
What version of Primefaces are you using?

I have PF 5.3.15 in my project and I'm not getting NPE. I've tried both with and without "rendered" attribute.

Could you provide your cadastroUsuarioBean.usuario bean's class?

**Comment by kukel** [comment]
And please use the forum first for things like this
