### ISSUE TITLE
OutputLabel does not support composite component

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1633]
In a very simple way, here is a composite:

```
<ui:component 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:cc="http://xmlns.jcp.org/jsf/composite"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:p="http://primefaces.org/ui"
>
    <cc:interface>
        <cc:attribute name="value" />
        <cc:attribute name="required" />
        <cc:editableValueHolder name="calendar" />
    </cc:interface>

    <cc:implementation>
        <p:calendar id="calendar" value="#{cc.attrs.value}" required="#{cc.attrs.required}" showOn="button"/>  
    </cc:implementation>
</ui:component>
```

Here how I use it:

```
<p:outputLabel for="rat:calendar" value="Hello" />
<my:calendar id="rat" required="true"/>
```

A mandatory icon should be displayed but it does not. In `OutputLabelRenderer` everything looks fine, except in line 118, `input.isRequired()` returns false while I explicitly set true.

**Comment by Rapster** [comment]
Enhancement or bug?

**Comment by tandraschko** [comment]
enhancement as it was never implemented to support this.

**Comment by Rapster** [comment]
Using `for="rat:calendar"` works though: it returns the `Calendar` component

**Comment by tandraschko** [comment]
whats the difference between #1632 and this?

**Comment by Rapster** [comment]
Let's picture this:

```
Composite_A.xhtml (editableValueHolder = B)
 `-- Composite_B.xhtml (editableValueHolder = C)
 |   `--Composite_C.xhtml (editableValueHolder = input)
     |   `-- h:inputText (id="input")
```

Using editableValueHolder on this every composite will help quickly and easily to retrieve the input from composite A _(using method such as `ComponentUtils.deepestEditableValueHolderTarget()` of PE)_. Doing this, You can write:

```
<p:outputLabel for="composite_a" value="Birthday" />
<my:compositeA id="composite_a" value="#{bean.property}" />
```

Reason I create #1632 is to make `OutputLabelRenderer` support `editableValueHolder`, in addition of `target = SearchExpressionFacade.resolveComponent(context, label, _for);` I'd call `UIComponent valueHolder = ComponentUtils.deepestEditableValueHolderTarget(target);` as it had been done for PE in `DynaFormRenderer`

Otherwise, you'd have to explicitly write the path to access the input, meaning:

```
<p:outputLabel for="composite_a:composite_b:composite_c:input" value="Birthday" />
<my:compositeA id="composite_a" value="#{bean.property}" />
```

Which is not clean and fragile as you might want to change ids name. But I give you that: it works approximately. 

Reason I create #1633, indicating the full path works, the target/input is correctly retrieved but as stated,  in OutputLabelRenderer everything looks fine, except in line 118, input.isRequired() returns false while it should return true

**Comment by tandraschko** [comment]
i see but PF is not responsible to resolve isRequired internally correctly. Thats up to the JSF impl.
Could you try it with MyFaces?

**Comment by Rapster** [comment]
Already did, not working either :(

**Comment by tandraschko** [comment]
hmm, then i think it would be the best to create a example (without PF) and ask the guys from the JSF impl.

**Comment by Rapster** [comment]
I "reproduced" with `h:outputLabel`  by debuging :/

**Comment by tandraschko** [comment]
So please ping the jsf impl guys.
Will close it for now, please reopen if there is a way that we can fix it.

**Comment by Rapster** [comment]
Mojarra ticket: https://java.net/jira/browse/JAVASERVERFACES-4172
MyFaces ticket: https://issues.apache.org/jira/browse/MYFACES-4059

**Comment by Rapster** [comment]
Answer has been provided by Myfaces team. It seems a Primefaces issue actually. @tandraschko could you reopen it please?

**Comment by tandraschko** [comment]
Not sure if we will fix this, Leo says that we must do a invokeOnComponent every time. This could be related to every component reference in PF. And therefore we must look at performance.

Does it work just with #1632? (for=composite instead for=composite:input)

**Comment by tandraschko** [comment]
As Leo says:

From spec perspective there is nothing to do. First of all, JSF 2
composite component aims to encapsulate everything inside a composite
component, so the call is invalid from the beginning, because it is
assumed something from inside the composite content.

For me it means that we won't reopen this ticket but we should try to get the required functionality working withing #1632

**Comment by Rapster** [comment]
I guess the problem will be the same with #1632 since in both cases, we're trying to evaluate el expression from `outputLabel`` and not from the composite itself. Let me try something, if it works, I will show you the fix, and you'll let me know what you think

**Comment by tandraschko** [comment]
Yep, but in #1632 we know that we have a composite available. So we could use invokeOnComponent only in this special case.

**Comment by mustafacataltepe** [comment]
this fix is not present in 6.0.7 release, will it be merged into any elite releases or scheduled for 6.1 milestone only?

**Comment by tandraschko** [comment]
Its even not fixed for 100% now. There is still an open PR.

**Comment by mustafacataltepe** [comment]
thanks saw the PR now. We currently have bunch of composites like this and labels adressing inputs in those composites in our project. It used to work before even its not intended to work like that. Hope it's going to be fixed in an elite/milestone release or we ll have quite some rework to be done :)

**Comment by Rapster** [comment]
If it's urgent, nothing prevents you to build from source and then cherry pick this PR

**Comment by Rapster** [comment]
@tandraschko I had a look at what you did (at a glance), don't see much difference with my PR. But I don't like this new API very much, looks too complicated to me (IMO). I'm wondering about performance now... Anyway, what you did should be done for all components having a `getFor` method (like tooltip)

**Comment by tandraschko** [comment]
the API follows the way of the JSF 2.3 search expressions. You need to pass a ContextCallback, to work on the component in the correct context. Of course we could add a layer between the OutputLabel and the handling but not sure. What should be done when a component is found, is mostly different for each component.
About performance: you can try both solutions but the main difference is 1 more object instance.

Other components, other tickets / new features :P

**Comment by Rapster** [comment]
I had a look at a glance in Mojarra implementation of `UIComponent.invokeOnComponent`. I don't even see how the composite could be pushed into the EL:

```java
public boolean invokeOnComponent(FacesContext context, String clientId,
            ContextCallback callback) throws FacesException {
        if (null == context || null == clientId || null == callback) {
            throw new NullPointerException();
        }

        boolean found = false;
        if (clientId.equals(this.getClientId(context))) {
            try {
                this.pushComponentToEL(context, this);
                callback.invokeContextCallback(context, this);
                return true;
            } catch (Exception e) {
                throw new FacesException(e);
            } finally {
                this.popComponentFromEL(context);
            }
        } else {
            Iterator<UIComponent> itr = this.getFacetsAndChildren();

            while (itr.hasNext() && !found) {
                found = itr.next().invokeOnComponent(context, clientId,
                        callback);
            }
        }
        return found;
    }
```

Calling `invokeOnComponent` this way will never put the composite in EL context (only the targeted component):

```java
ComponentTraversalUtils.closestNamingContainer(composite)
                        .invokeOnComponent(context, children.getClientId(context), callback);
```

This would explain why it fails to resolve the "cc.*".

Being said, I remember I tricked this in my PR to ensure composite will be pushed. (See https://github.com/primefaces/primefaces/pull/1815/files in EditableValueHolderState) While in MyFaces, the first thing done is to push the composite into the EL context:

```java
    public boolean invokeOnComponent(FacesContext context, String clientId, ContextCallback callback)
            throws FacesException
    {
        // java.lang.NullPointerException - if any of the arguments are null
        if (context == null || clientId == null || callback == null)
        {
            throw new NullPointerException();
        }

        pushComponentToEL(context, this);
        try
        {
            // searching for this component?
            boolean found = clientId.equals(this.getClientId(context));
            if (found)
            {
                try
                {
                    callback.invokeContextCallback(context, this);
                }
                catch (Exception e)
                {
                    throw new FacesException(e);
                }
                return found;
            }
            // Searching for this component's children/facets
            // [perf] Use getFacetsAndChildren() is nicer but this one prevents
            // create 1 iterator per component class that does not have
            // facets attached, which is a common case. 
            if (this.getFacetCount() > 0)
            {
                for (Iterator<UIComponent> it = this.getFacets().values().iterator(); !found && it.hasNext(); )
                {
                    found = it.next().invokeOnComponent(context, clientId, callback);
                }                
            }
            if (this.getChildCount() > 0)
            {
                for (int i = 0, childCount = getChildCount(); !found && (i < childCount); i++)
                {
                    UIComponent child = getChildren().get(i);
                    found = child.invokeOnComponent(context, clientId, callback);
                }
            }
            return found;
        }
        finally
        {
            //all components must call popComponentFromEl after visiting is finished
            popComponentFromEL(context);
        }
    }
```

**Comment by Rapster** [comment]
What do you think?

**Comment by tandraschko** [comment]
No idea, how did it work with your solution?

**Comment by Rapster** [comment]
As I said, I knew this problem and I used a trick:

```java
EditableValueHolderState eval(FacesContext context) {
	if (CompositeUtils.isCompositeComponent(parent)) {
		// parent is used as the caller and the target, so it can be pushed into EL contex. See Mojarra impl
		parent.invokeOnComponent(context, parent.getClientId(context), new InputValueHolderContextCallback());
	} else if (target != null) {
		evalAttrs(context, target);
	}
	return this;
}

private void evalAttrs(FacesContext context, UIComponent target) {
	clientId = (target instanceof InputHolder) ? ((InputHolder) target).getInputClientId() : target.getClientId(context);
	valid = target instanceof EditableValueHolder ? ((EditableValueHolder) target).isValid() : true;
	required = (target instanceof UIInput) ? ((UIInput) target).isRequired() : false;
}

private class InputValueHolderContextCallback implements ContextCallback {

	@Override
	public void invokeContextCallback(FacesContext context, UIComponent target) {
		// At this point, target is the composite but I don't care about it, as I want to eval attributes from EditableValueHolderState.this.target
		evalAttrs(context, EditableValueHolderState.this.target);
	}
}
```

Another reason I'd rather use this API is that, I used callback only if necessary, and the client using this API won't have to bother creating a callback (like I would do in PE for DynaFormRenderer). For example:

```java
EditableValueHolderState valueHolder = CompositeUtils.lastEditableValueHolder(target, fc);
if (valueHolder.getTarget() == null) {
	LOGGER.warning("Cannot find editableValueHolder referenced by '" + cell.getFor() + "' inside UIDynaFormControl");

	continue;
}

dynaFormLabel.setTargetClientId(valueHolder.getClientId());
dynaFormLabel.setTargetValid(valueHolder.isValid());
dynaFormLabel.setTargetRequired(valueHolder.isRequired());

if (dynaFormLabel.getValue() != null) {
	valueHolder.getTarget().getAttributes().put("label", dynaFormLabel.getValue());
}
```

**Comment by tandraschko** [comment]
So the difference is that you do a invokeOnComponent on the CC itself instead the parent namingcontainer?

**Comment by Rapster** [comment]
Not only,

To make it simple I do this: `composite.invokeOnComponent(context, composite, callback);`
But once `callback.invokeContextCallback` is called, it does this `callback.invokeContextCallback(context, target)`

**Comment by tandraschko** [comment]
don't understand your second hint but the first just would mean the following to replace

                ComponentTraversalUtils.closestNamingContainer(composite)
                        .invokeOnComponent(context, children.getClientId(context), callback);

with

                composite.invokeOnComponent(context, children.getClientId(context), callback);

**Comment by Rapster** [comment]
Second hint, I'm talking about this:
```java
private class InputValueHolderContextCallback implements ContextCallback {

	@Override
	public void invokeContextCallback(FacesContext context, UIComponent target) {
		// At this point, target is the composite but I don't care about it, as I want to eval attributes from EditableValueHolderState.this.target
		evalAttrs(context, EditableValueHolderState.this.target);
	}
}
```

Regarding what you said, what you wrote is fine _(although if you know it's a composite, I don't think it is necessary to use ComponentTraversalUtils.closestNamingContainer())_ To me, there is something strange with Mojarra impl (I don't understand the purpose of this method the way it is written) while MyFaces makes sense (as Leo explained)

**Comment by tandraschko** [comment]
what i understand, your code is doing the following:

- search the EditableValueHolder
- invokeOnComponent from the composite and target the composite
- inside the ContextCallback, evaluate the the attributes from the EditableValueHolder

What my code is doing currently:

- search the EditableValueHolder
- invokeOnComponent on the composite's parent NamingContainer and target the editableValueHolder
- inside the ContextCallback, evaluate the the attributes from the EditableValueHolder

AFAICS thats the main difference.
Will the first approach also work fine in MyFaces?

**Comment by Rapster** [comment]
It should. I have to test this PR on MyFaces again (I did this few months ago and I don't remember if it worked on MyFaces), but as long as composite is pushed in EL, it will read the cc attributes

**Comment by Rapster** [comment]
Just tried my solution, works fine wih MyFaces

**Comment by tandraschko** [comment]
fixed it, but thanks to mojarra, we ne a second new object instance

**Comment by Rapster** [comment]
Three instances of ContextCallback? That's a hell of a lot...

**Comment by tandraschko** [comment]
I don't think you can meassure a difference :P

But yes, we have 2 optimizations we/you can do:
1) introduce a new layer which builds the EditableValueHolderState and remove the contextCallback in OutputLabelRenderer
2) looking for another mojarra fix

**Comment by tandraschko** [comment]
i think i can delete one of them, will play a little bit with it now.

**Comment by tandraschko** [comment]
done, the code looks even easier now ;)

**Comment by Rapster** [comment]
> introduce a new layer which builds the EditableValueHolderState and remove the contextCallback in OutputLabelRenderer

It's exactly what my PR is doing

**Comment by tandraschko** [comment]
Yep but for me it was important to separate the EditableValueHolderState from the CompositeUtils. Adding a util for resolving the "for" attribute for multiple components (focus, outputLabel etc.) and constructing a EditableValueHolderState is a different topic.
