### ISSUE TITLE
Insufficient ajax support for p:catpcha

### ISSUE THREAD

**Issue by msgeissler** [primefaces/primefaces#1639]
Hi,

I noticed a shortcoming in the provided ajax support for p:captcha.
To allow the use of ajax with p:captcha you use
`RequestContext requestContext = RequestContext.getCurrentInstance();
        if(requestContext.isAjaxRequest()) {
            requestContext.execute("grecaptcha.reset()");
        }`
at the end of the validateValue-Method in org.primefaces.component.captcha.Captcha.

The problem here lies in the Google siteverify call at the beginning of the method.
If, for example, the captcha was clicked and the user waited for more than 2 minutes (that is the session timeout for a single reCaptcha-verification) until the form submit (or whatever triggers the validation), the siteverifly call will fail.
This will cause an exception and thus throw a FacesException. This will prevent the `grecaptcha.reset()` call  at the end from being executed and the captcha gets stuck in an unusable state (a reCaptcha-token can only be used once).

The solution would be to reset the grecaptcha for ajax calls for basically every exception that can happen during validation.

Either add the ajax check and reset call to the siteverify-catch-clause or try-catch the whole method and add the ajax check and reset call as a final block.

I would like to provide a pull request with a possible solution, but as embarrassing as it may sound, I can't find the class in your git repository (only the CaptchaRenderer).

**Comment by tandraschko** [comment]
Feel free to provide a PR which a good description.
The class (Captcha) is automatically generated, check "CaptchaTemplate.java"
