### ISSUE TITLE
Different date format for the same locale

### ISSUE THREAD

**Issue by vbrandl** [primefaces/primefaces#1642]
When setting the Java locale to Locale.GERMANY

``` Java
Locale.setDefault(Locale.GERMANY);
```

and the JSF locale to "de"

``` XML
<locale-config>
        <default-locale>de</default-locale>
</locale-config>
```

some date components still behave differently.
E.g. p:calendar shows dates as `dd.MM.yy` while f:convertDateTime formats to `dd.MM.yyyy`.
Also when showing dates in datatables, and formating the output like this:

``` XHTML
<p:column ...>
<h:outputText value="#{someItem.someDate}">
        <f:convertDateTime />
</h:outputText>
</p:column>
```

the date gets shown as `dd.MM.yyyy`, but when adding a filter, it is filtering for `dd.MM.yy`.
Assuming the value is shown as `01.01.2016`, when filtering for `01.01.2016`, there is no result. But when filtering for `01.01.16` it works as intended.
Is there a way to unify this behaviour?

**Comment by tandraschko** [comment]
Feel free to analyze the problem and provide possible solutions here.

**Comment by melloware** [comment]
No response from OP in 4 years. closing ticket.
