### ISSUE TITLE
Spinner and mousewheel: display updated but change event not triggered

### ISSUE THREAD

**Issue by nikospara** [primefaces/primefaces#1643]
The `<p:spinner>` control allows several methods to change its value. When using the mouse wheel, the change event is not triggered, unlike when using the up/down buttons, editting the number directly or using the up/down keys from the keyboard.

To replicate the problem:
- Go to the [spinner showcase](http://www.primefaces.org/showcase/ui/input/spinner.xhtml)
- With the "Ajax Spinner" spinner focused:
  - Press the up arrow: the display gets updated, the value on the right of the spinner follows
  - Enter a number using the keyboard and leave the control (make it loose focus): the display gets updated, the value on the right of the spinner follows
  - Press the up arrow in the keyboard (the spinner needs to be focused): the display gets updated, the value on the right of the spinner follows
  - **Use the mouse wheel, roll up or down: the display gets updated, the value on the right does NOT follow**

Using PrimeFaces 5.3.

---

A solution that seems to work for me is to trigger the `'change'` event when detecting an appropriate mouse wheel event. In the [spinner.js](https://github.com/primefaces/primefaces/blob/5_3/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js), replace the mouse wheel event handler on [line 107](https://github.com/primefaces/primefaces/blob/5_3/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js#L107) with the following:

``` javascript
        .on('mousewheel.spinner', function(event, delta) {
            if($this.input.is(':focus')) {
                if(delta > 0) {
                    $this.spin(1);
                    $this.input.trigger('change');
                }
                else {
                    $this.spin(-1);
                    $this.input.trigger('change');
                }

                return false;
            }
        });
```

**Comment by melloware** [comment]
PR Submitted.

**Comment by awenger63** [comment]
Hi, just test on showcase (PrimeFaces-7.1-SNAPSHOT) in Ajax spinner and not work ! What is wrong ?

**Comment by melloware** [comment]
It's definitely fixed but it looks like the showcase has not been deployed since this fix was made.  I can tell by debugging the JS the showcase definitely does not have this code yet but I can confirm its working fine when I run the showcase locally.

**Comment by awenger63** [comment]
@melloware Thanks for this check
