### ISSUE TITLE
Update FontAwesome from 4.6.1 to 4.6.3

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#1649]
https://github.com/FortAwesome/Font-Awesome/compare/v4.6.1...v4.6.3

**Comment by kukel** [comment]
PrimeFaces should stop including FontAwesome like this and just 'depend' on the webjar version.  http://stackoverflow.com/questions/18891768/how-to-use-font-awesome-3-2-1-from-webjars-org-with-jsf#28652968

**Comment by tandraschko** [comment]
we could probably add the dependency and include automatically the css from the original jar if our PF context param is set.
We will talk with cagatay about that.

**Comment by mertsincan** [comment]
For now, I updated it from 4.6.1 to 4.6.3
