### ISSUE TITLE
Edit-aware dialogs

### ISSUE THREAD

**Issue by iozee** [primefaces/primefaces#165]
It would be really great if there was some dialog attribute like editAware="true" which could track changes made to the containing inputs.
So that when user closes the dialog (or calls PF(widget).hide();) the confirmDialog would appear.
I'm trying to implement it by myself but I think it would be a really nice feature.

**Comment by ova2** [comment]
Some solutions can be found on Google if you search with "jquery detect changes in form". I think it would be useful for any kind of panels.

**Comment by kukel** [comment]
or even a full page...
