### ISSUE TITLE
Connection between category and subcategory

### ISSUE THREAD

**Issue by Rapter1990** [primefaces/primefaces#1652]
I devised a sample category with subcategory module in jsf by eclipse. I made an adding category module without any issue but I couldn't make an adding subcategory under related category . How do I solve the issue. Here the code below.

exception 

WARNING: #{subCategoryMB.addSubCategory()}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
javax.faces.FacesException: #{subCategoryMB.addSubCategory()}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

`
<h:body>

   <h:form>

```
  <p:panelGrid columns="2">

     <p:outputLabel value="Caetgory Name"></p:outputLabel>

     <p:selectOneMenu value="#{subCategoryMB.categoryName}">
        <f:selectItem itemLabel="Select Category" itemValue=""></f:selectItem>
        <f:selectItems value="#{subCategoryMB.categorylist}" />
     </p:selectOneMenu>

     <p:outputLabel value="Sub Category Name"></p:outputLabel>
     <p:inputText value="#{subCategoryMB.subcategory.subName}"></p:inputText>

     <p:outputLabel value="Sub Category Description"></p:outputLabel>
     <p:inputText value="#{subCategoryMB.subcategory.subNameDes}"></p:inputText>

     <p:commandButton value="Alt Kategori Ekle" action="#{subCategoryMB.addSubCategory()}"></p:commandButton>   <!--  ISSUE -->


  </p:panelGrid>
```

   /h:form

`

CategoryDao 
`
public List<Category> getAllcategoriesbyName(String name) {
      // TODO Auto-generated method stub
      Session session = HibernateUtil.getSessionFactory().openSession();

```
  try {

     List<Category> liste = session.createQuery("select C from Category C where C.name='"+name+"'").list();

     return liste;


  } catch (Exception e) {
     e.printStackTrace();

  }finally {

     session.close();

  }
  return null;
```

   }

```
     public List getAllcategoriesSelectItemName() {
  // TODO Auto-generated method stub
  Session session = HibernateUtil.getSessionFactory().openSession();

  try {
     // category olacak
     List liste = session.createQuery("select C.name from Category C").list();
     return liste;


  } catch (Exception e) {
     e.printStackTrace();

  }finally {

     session.close();

  }
  return null;
```

   }

`

SubCategoryMB

`

public class SubCategoryMB {

   SubCategory subcategory = new SubCategory();

   private String categoryName;
   private List<Category> categorylist = new ArrayList<Category>();
   private List<Category> categorylistbySubCategory = new ArrayList<Category>();
   private List<SubCategory> subCategoryList =new ArrayList<SubCategory>();
   private Category category= new Category();

   public SubCategoryMB() {
      // TODO Auto-generated constructor stub
   }

   public SubCategory getSubcategory() {
      return subcategory;
   }

   public void setSubcategory(SubCategory subcategory) {
      this.subcategory = subcategory;
   }

   public void setCategorylist(List<Category> categorylist) {
      this.categorylist = categorylist;
   }

   public String getCategoryName() {
      return categoryName;
   }

   public void setCategoryName(String categoryName) {
      this.categoryName = categoryName;
   }

   public Category getCategory() {
      return category;
   }

   public void setCategory(Category category) {
      this.category = category;
   }

   public List<SubCategory> getSubCategoryList() {
      SubCategoryDAO subDao = new SubCategoryDAO();
      this.subCategoryList= subDao.getAllSubcategories();
      return subCategoryList;
   }

   public void addSubCategory(){

```
  categorylistbySubCategory= new CategoryDAO().getAllcategoriesbyName(categoryName);
  subcategory.setCategory(categorylistbySubCategory.get(0));   /// THERE IS A ISSUE HERE
  subcategory.setSubName(subcategory.getSubName());
  subcategory.setSubNameDes(subcategory.getSubNameDes());
  new SubCategoryDAO().addSubCategory(subcategory);
```

   }

   public List<SelectItem> getCategorylist(){

```
  List<SelectItem> catname = new CategoryDAO().getAllcategoriesSelectItemName();
  return catname;
```

   }

`

**Comment by Rapster** [comment]
Really? #1609 Use http://stackoverflow.com/, you'll find all the help you need

**Comment by tandraschko** [comment]
use the forum, it's a question
