### ISSUE TITLE
the latest primefaces themes [1.0.10] not published on Maven Central

### ISSUE THREAD

**Issue by mtbadi39** [primefaces/primefaces#1653]
It seems that the version published to [Maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.primefaces.extensions%22%20AND%20a%3A%22all-themes%22) was not the latest.

**Comment by tandraschko** [comment]
This was a primefaces-extensions feature (as you can see in the group-id)
as it this feature was migrated to primefaces, it's now in the primefaces repo: http://repository.primefaces.org/org/primefaces/themes/all-themes/

**Comment by mtbadi39** [comment]
>  this feature was migrated to primefaces

I know

> it's now in the primefaces repo

why not in Maven Central ??

**Comment by tandraschko** [comment]
don't know, primetek only publish the primefaces artifact to central. Even normal themes are not in central or the maven plugin.
