### ISSUE TITLE
Dynamic ui:include + UIData (with rowStatePreserved) rendering problem

### ISSUE THREAD

**Issue by slovi** [primefaces/primefaces#1654]
There is a situation where UIData with rowStatePreserved is not rendered. NullPointer exception is thrown in this case.

The example of such situation is:
- we have index.xhtml with ui:include with src attribute as expression

```
        <h:form>
            <h:panelGrid columns="1" bodyrows="3">
                <p:commandLink action="#{mainFrameBean.setMenu('iframe1.xhtml')}" process="@this" update=":mainframe">Frame 1</p:commandLink>
                <p:commandLink action="#{mainFrameBean.setMenu('iframe2.xhtml')}" process="@this" update=":mainframe">Frame 2</p:commandLink>
                <p:commandLink action="#{mainFrameBean.setMenu('iframe3.xhtml')}" process="@this" update=":mainframe">Frame 3</p:commandLink>
            </h:panelGrid>
        </h:form>

        <p:outputPanel id="mainframe">
            <ui:include src="/frames/#{mainFrameBean.menuValue}" />
        </p:outputPanel>

```
- we have datagrid coded in iframe2.xhtml

```
<p:dataGrid var="car" value="#{dataGridView.cars}" columns="3" layout="grid"
        rows="12" paginator="true" id="cars" rowStatePreserved="true"
        paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
        rowsPerPageTemplate="6,12,16">

        <f:facet name="header">
            Cars for Sale
        </f:facet>

        <p:panel header="#{car.id}" style="text-align:center">
            <h:outputText value="#{car.year}" />
        </p:panel>

    </p:dataGrid>
```

Then if you click "Frame 2" commandlink you get nullpointer returned in the partial response XML.

The problem is UIData incorrectly handles initial descendant state during the render response phase.

The problem is also in the reference JSF 2.2.0 implementation. Myfaces 2.2.10 is OK. I've created pull request for primefaces UIData.

Jiri

**Comment by kukel** [comment]
PF version affected? Did you try latest Mojarra? (2.2.12 I think)

**Comment by slovi** [comment]
Affected versions of primefaces are 5.2, 5.3, 6.0, 6.1 (SNAPSHOT) ...

The incorrect method is org.primefaces.component.api.UIData.saveDescendantInitialComponentStates

Primefaces imlementation is duplicated from the mojarra's api (javax.faces.component.UIData).

The only correct implementation of this method is in myfaces 2.2.10. 

(I had a look into the latest mojarra - 2.2.13 - and saw incorrect implementation as well).

**Comment by slovi** [comment]
FYI, I requested the pull solving this issue https://github.com/primefaces/primefaces/pull/1655.

**Comment by kukel** [comment]
maybe better to create an issue in Mojarra as well?

**Comment by slovi** [comment]
done https://java.net/jira/browse/JAVASERVERFACES-4174

**Comment by tandraschko** [comment]
JFYI: will wait till mojarra fixes the issue, the likely know it better how to fix "their" code :)

**Comment by slovi** [comment]
OK, just suggested the same solution as is done in myfaces ... but of course, it's up to you.

Anyway, thanks for the information.

**Comment by tandraschko** [comment]
JFYI: The mojarra team asked for a example

**Comment by tandraschko** [comment]
@slovi ping :)

**Comment by slovi** [comment]
Hi @tandraschko, sorry for not responding, I was busy. I prepared [testapp](https://github.com/slovi/myfaces_primefaces_uidata_issue) and found out the problem is in myfaces implementation. I created the issue in their bugtrack system https://issues.apache.org/jira/browse/MYFACES-4074. Very probably, fix of this issue will not have any impact to primefaces code. I think you can close the issue for now.

Jiri

**Comment by slovi** [comment]
You can decline this pull request #1655 

Jiri

**Comment by tandraschko** [comment]
all right, thank you :)

**Comment by slovi** [comment]
Hi @tandraschko, I created bug in myfaces and this is the result:

https://issues.apache.org/jira/browse/MYFACES-4074

They said, it should be fixed in primefaces.

So pull request #1655 is relevant now.

**Comment by tandraschko** [comment]
So feel free to provide a PR ;)

**Comment by slovi** [comment]
OK, I reopened this pull request #1655

**Comment by tandraschko** [comment]
Applied it, hopefully it doesn't brake anyting ;)
