### ISSUE TITLE
A filesize attribute at StreamedContent for the FileDownload component would be nice

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#1656]
A optional filesize attribute at StreamedContent would be nice. With that, the browser can show how long the download will take.
Also a convenient constructor at DefaultStreamedContent taking a byte array and setting the stream and filesize attribute would be nice. 
Similar to: org.omnifaces.util.Faces#sendFile((byte[] content, String filename, ...)

**Comment by tandraschko** [comment]
Duplicate  #279
