### ISSUE TITLE
datatable paginator links & rows per page doesn't work inside a span 

### ISSUE THREAD

**Issue by arunvc1** [primefaces/primefaces#1657]
RowsPerPageDropdown and paginator links doesn't work inside a span or div tag

`paginatorTemplate="&lt;span style='float:right'&gt; {RowsPerPageDropdown}  &lt;/span&gt; "
`

I was trying to align the paginator links to left and rows per page drop down to right.

PF 6.0

**Comment by kukel** [comment]
'does not work' meaning?

**Comment by arunvc1** [comment]
click on pagination links stays on the same page, no request is send to server

**Comment by melloware** [comment]
Marking this as invalid as you are trying to embed HTML in the template which we escape anyway to prevent XSS.
