### ISSUE TITLE
p:panelMenu javascript access broken

### ISSUE THREAD

**Issue by Harwkx** [primefaces/primefaces#1658]
# Issue

I used to implement a custom script to collapse other open `p:panelmenu` entries if anotherone was clicked with primefaces 5.3. Since primefaces 6.0, the code is not getting executed properly. The javascript gets executed and stopped when in `PF('pmenu').headers.each(...)`. A simple `try/catch`resolves to `null` as exception.
## Tested Versions
- working in `primefaces-5.3.jar`
- broken in `primefaces-6.0.jar`
## Sample Code

sample.xhtml

``` xhtml
<p:panelMenu widgetVar="pmenu" >
  <p:submenu label="Sample 1">
    <p:menuitem value="Item 1" outcome="out1" />
  </p:submenu>
  <p:submenu label="Sample 2">
    <p:menuitem value="Item 1" outcome="out2" />
  </p:submenu>
</p:panelMenu>
```

menu.js

``` javascript
jQuery(document).ready(function()
{
  PF('pmenu').headers.each(function() //breaks here
  {
    //code here
  })
});
```
## Current Workaround

menu.js

``` javascript
jQuery(document).ready(setTimeout(function()
{
  PF('pmenu').headers.each(function() //works now
  {
    //code here
  })
}, 500));
```

I somehow figured it out, that the javascript gets properly executed after a small delay like seen above. I have no real clue what is causing the problem. Maybe some sort of unfinished rendering. Can someone maybe clarify what causes this?

**Comment by tandraschko** [comment]
You use a internally API which might get changed if you upgrade.
You need to check the sources again. If you need help you can try the forum/stackoverflow.

**Comment by Harwkx** [comment]
I'll just reference the forum post from other authors here that are using the same functionality as i do, in case they running into this migration stopper.
http://forum.primefaces.org/viewtopic.php?f=3&t=27483

**Comment by sakkie6yster** [comment]
I have exactly the same issue. What do you mean with "internally API" tandraschko? We have a thread on the primefaces forum with regards to adding accordion behaviour to the panelMenu, all of a sudden our JavaScript is not working anymore. How would you suggest we go about implementing this behaviour so that it does not break every time there is a new release?

**Comment by tandraschko** [comment]
Feel free to provide a new Ticket with your requirements, so we can Talk about it
