### ISSUE TITLE
Calculate maximum height of dialog

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#166]
Currently it's possible that the dialog is bigger as the screen and and therefore some content is hidden cause it doesn't have a scrollbar per default.
The scrollbar will be visible if we set the max-height to the screen size.

We currently have this workaround in all ours apps:

```
    $('.ui-dialog').each(function() {
        var $this = $(this);
        var $header = $this.children('.ui-dialog-titlebar');
        var $content = $this.children('.ui-dialog-content');

        var maxHeight = $(window).height() - $header.outerHeight() - 30;

        if ($content.height() >= maxHeight)
        {
            $content.css('height', '');
        }

        $content.css('max-height', maxHeight + 'px');
    });
```

WDYT @cagataycivici ?

**Comment by cagataycivici** [comment]
I'm not sure if I get this, so dialogs are maximized and take full space in window but scrollbar doesn't appear?

**Comment by tandraschko** [comment]
Will provide a example the next weeks.
