### ISSUE TITLE
Focus changing between components is slow

### ISSUE THREAD

**Issue by csaszika** [primefaces/primefaces#1660]
Project's request is that the user can change focus between components (inputTexts, selectOneMenus...etc) with a button (enter) but not with tab.
My solution:
`<p:inputText id="id" value="#{bean.name}" 
onkeypress="if (event.keyCode == 13) {
                                         somethingToDo();
                                         return false;}"
                         onfocus="this.select()">
</p:inputText>`

This works fine but too slow. I can push ENTER then another value and then this value will belong to the previous focus component. I tried it with javascript too but it was slow too.
Is there a faster solution for that or just why is it slow?

**Comment by kukel** [comment]
uhhmmmm what you have in there IS javascript. And what does `somethingToDo()` do? 'sleep' for several seconds?

**Comment by csaszika** [comment]
So for clarification, somethingToDo => primefaces:remoteCommand, this command change the focus to the next component (for example to an inputText). In javascript I tried the same. Here is the code:
`function focusTo(event, id) {
    if (event.keyCode == 13) {
        document.getElementById(id).focus();
    }
}`
And this focus change takes more time than I use just TAB button. Sorry for insufficient drafting.

**Comment by tandraschko** [comment]
use the forum for such things please (and provide a full example there).
