### ISSUE TITLE
Datatable lose rowKey when use filter and move next step in wizard

### ISSUE THREAD

**Issue by MiguelAngelLV** [primefaces/primefaces#1663]
I have a wizard with dataTables with selection mode.

If I add filter to dataTable and use it, when I back to previous step throw `DataModel must implement org.primefaces.model.SelectableDataModel when selection is enabled`

I use rowKey and it works fine if I don't use the filter. I debug and I saw that rowKey return null when back to previous step.

I use Primefaces 6.0

**Comment by kukel** [comment]
Please add an [mcve](http://stackoverflow.com/help/mcve) to your issue

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
