### ISSUE TITLE
Can not buy venture theme from primestore at Turkey location

### ISSUE THREAD

**Issue by anadollu** [primefaces/primefaces#1664]
Hi,

We have tried to buy venture theme on primestore many times. Every time we encountered the same issue by using different credit cards on payment step. Is there any other method to buy it.

Best.

**Comment by mertsincan** [comment]
Please contact us; contact@primetek.com.tr

**Comment by anadollu** [comment]
I did already, but this email does not work. I am getting error reply message when i send an email. Be sure,  tried with all my email accounts.

**Comment by tandraschko** [comment]
please use the forum or email; this is the issue tracker
