### ISSUE TITLE
SelectBooleanCheckbox in editable DataTable doesn't change

### ISSUE THREAD

**Issue by xfersys** [primefaces/primefaces#1669]
I have a dataTable that is editable (editMode = "cell").
when I try to edit checkbox selection, the data is not actualized after the change was made.

`<p:dataTable id="submodels" var="submodel" value="#{projectMB.submodels}" 
             editable="true" editMode="cell" widgetVar="cellSubmodels">
  <p:column headerText="Mapping file">
    <p:cellEditor>
      <f:facet name="output">
        <h:selectBooleanCheckbox value="#{submodel.mapping}" onclick="return false;"
           style="width:96%" label="Root model" readonly="true"/>
      </f:facet>
      <f:facet name="input">
        <h:selectBooleanCheckbox value="#{submodel.mapping}" style="width:96%" 
           label="Root model"/>
      </f:facet>
    </p:cellEditor>
  </p:column>
</p:dataTable>`

Can you point out what I have done wrong?
I'm using Primefaces version 6.0

Best Regards.

**Comment by kukel** [comment]
please use the forum for questions like this.
