### ISSUE TITLE
Ajax refresh destroys overlayPanel with dynamic="true" property

### ISSUE THREAD

**Issue by FuturesTr4der** [primefaces/primefaces#1671]
If you open a primefaces overlayPanel (with dynamic="true"), it works as long as you execute a ajax refresh. (PF 6.0)
See the following the example and screenshots:

`<p:panel id="panel">`
`<p:commandLink id="openOverlay" value="Open Overlay" />`
`<p:overlayPanel for="openOverlay" dynamic="true">`
`Content...`
`</p:overlayPanel>`
`<p:spacer width="100" height="10" />`
`<p:commandLink value="Ajax Refresh" update="panel" />`
`</p:panel>`

Overlaypanel works:
![image](https://cloud.githubusercontent.com/assets/15264266/17428667/732314e6-5aea-11e6-8bc7-361cb9989fd5.png)

After ajax refresh, there is no content:
![image](https://cloud.githubusercontent.com/assets/15264266/17428683/9dbbd0da-5aea-11e6-950a-a5893db0ed75.png)

**Comment by kukel** [comment]
update the content INSIDE the overlayPanel then. And please...please...please... post version info

**Comment by FuturesTr4der** [comment]
Sorry, i added the version info.
What do you mean with the "content update"? It doesn't work also if i update a panel, which is inside the overlayPanel.

**Comment by FuturesTr4der** [comment]
Any news about the defect of the overlayPanel?

**Comment by tandraschko** [comment]
No but feel free to fix the problem and provide a PR!

**Comment by tandraschko** [comment]
It's really better to update the content for dynamic overlays.
Update the content means that:

<p:panel id="panel">
<p:commandLink id="openOverlay" value="Open Overlay" />
<p:overlayPanel for="openOverlay" dynamic="true">
    <p:panel id="openOverlayContent">
Content...
    </p:panel>
</p:overlayPanel>
<p:spacer width="100" height="10" />
<p:commandLink value="Ajax Refresh" update="openOverlayContent" />
</p:panel>

This will also prevent some flickering or other unexpected behaviors.

**Comment by webyildirim** [comment]
What if overlay component is in ui:repeat, how can we access its id to update ?

**Comment by s-buchner** [comment]
Also a problem in p:dataTable.
Workaround does not work for me.
Had to use dynamic="false" - but that increases the size.

**Comment by crocimi** [comment]
> What if overlay component is in ui:repeat, how can we access its id to update ?

Any idea for this question?
