### ISSUE TITLE
Problem in dataexporter header with facet

### ISSUE THREAD

**Issue by jbbjunior** [primefaces/primefaces#1682]
I have problems in PDF header when facet use in component dataExporter in datatable

The header appears javax.faces.component.UIPanel instead of appearing "Severity"

This happens only when we have something more than the tag outputText inside facet header

You can fix this in the next version?

[Code]
<p:dataTable id="DataTableId" widgetVar="tableId" rowKey="#{alert.entity}" var="alert" filterMap="#{alertMBean.filterMap}"
value="#{alertMBean.lazyModel}" paginator="true"    lazy="true"
paginatorTemplate="{ExportersFile} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
selectionMode="multiple" selection="#{alertMBean.selectedAlerts}"
paginatorPosition="top" rowsPerPageTemplate="15,50,100,250,500"
first="#{alertMBean.currentPage}" 
rows="#{alertMBean.rows}">

<f:facet name="{ExportersFile}">

<h:commandLink styleClass="linkExportaGrid" title="#{res.button_export_PDF}">
<img src="#{dashMBean.getCurrentContext()}/image/icone_PDF.png" width="24" />
<p:dataExporter type="pdf" target="DataTableId" fileName="#{res.form_alerts}" pageOnly="true" />
/h:commandLink
/f:facet  

<p:column>
<f:facet name="header">
<h:outputText value="Severity"/>
<br />
<p:commandButton id="showSeverityDlgBt" 
update=":severitySelectionForm" 
oncomplete="PF('severitySelectionDlg').show();" icon="ui-icon-search" />

/f:facet
<h:outputText value="#{alert.severityStr}" />
/p:column
/p:dataTable
[/ Code]

**Comment by tandraschko** [comment]
Duplicate: #1708
