### ISSUE TITLE
inputNumber doesn't work with "," as decimalSeparator and "." as thousandSeparator

### ISSUE THREAD

**Issue by henriquecoutobsb** [primefaces/primefaces#1685]
The code:
`<p:inputNumber decimalSeparator="," thousandSeparator="." />`

The JavaScript error:

> primefaces inputnumber autoNumeric will not function properly when the decimal character aDec: '.' and thousand separator aSep: '.' are the same character

It seems it successfully sets the thousandSeparator, but skips the decimalSeparator.
The error happens with PrimeFaces 6.0 Community.

**Comment by henriquecoutobsb** [comment]
The problem only happens when you have only the thousandSeparator attribute with the "." value.
Even if you don't need decimal places, you must set the decimalSeparator to ",".

**Comment by upDiogoSaraiva** [comment]
Thank you @henriquecoutobsb this really helped me as i didn't know that you had to have both separators if you already had one.
