### ISSUE TITLE
Tree: expand event is not triggered with dynamic="true"

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#1686]
`expand` only works without `dynamic="true"`, `collapse` works both with and without `dynamic="true"`.

I'm on PF 6.0.

**Comment by marcos-simoes** [comment]
Is not triggered with resizableColumns="true" too

@Primefaces 6.0

**Comment by tandraschko** [comment]
See https://github.com/primefaces/primefaces/issues/3668

in 6.3, we will have:
expand and collapse events will be fired always, doesn't matter if dynamic true or false
BUT
expand and collapse will both NOT be fired when cache=true; expand will just be fired for the initial request to get the sub-nodes to cache

NOTE: cache=true is the default
