### ISSUE TITLE
Primefaces showcase - dialogs - can be dragged out of screen through top / bottom

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#1688]
http://www.primefaces.org/showcase/ui/overlay/dialog/basic.xhtml and

http://www.primefaces.org/showcase/ui/overlay/dialog/loginDemo.xhtml

The dialog can always be dragged out through the bottom of the screen:

![selection_003](https://cloud.githubusercontent.com/assets/10467831/17612475/d718beec-6017-11e6-94d0-beba2d9ea110.png)

And by some chances, the dialog can be dragged out through the top of the screen (Not always reproducible but it will definitely show up after a couple trails).

![selection_002](https://cloud.githubusercontent.com/assets/10467831/17612465/be82f1f4-6017-11e6-9581-7bcd2a357b6a.png)

**User cannot do anything with it unless refresh the page.**

**Suggest to make it work like: http://www.primefaces.org/showcase/ui/df/basic.xhtml**

Tested by lastest Chrome & Firefox
Machine: linux, mac, windows

**Comment by jxmai** [comment]
In addition, when the dialog has been dragged out of the top boundary. You will see some unexpected behaviours when you try to resize the dialog.

**Comment by jxmai** [comment]
The same issue exists on mobile devices, modal or not does not matter.

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17629159/a27a7380-607e-11e6-9262-29e69b1b551a.png)

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17629119/6e348408-607e-11e6-8ddb-2063a9d2e29c.png)

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17629084/39e1bc5c-607e-11e6-8b5e-dc07bb425837.png)

**Comment by PlassJ** [comment]
Confirmed!

**Comment by jxmai** [comment]
This issue was fixed via #2056. Closing.
