### ISSUE TITLE
widgetVar does not work for steps component

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#1690]
I'm on PF 6.0.

When I use `widgetVar="stepsVar"` on the `steps` component, the widget is unknown (JavaScript console):

```
> PF('stepsVar')
Widget for var 'stepsVar' not available!
```

**Comment by tandraschko** [comment]
Thats because there is currently no javascript for steps required.

**Comment by jepsar** [comment]
In that case, why is the `widgetVar` attribute offered? It's misleading to say the least.
