### ISSUE TITLE
Primefaces showcase not running on latest PF version and latest Mojarra version

### ISSUE THREAD

**Issue by maol74** [primefaces/primefaces#1693]
http://www.primefaces.org/showcase is "still" running on PrimeFaces-6.0.RC4 on Mojarra-2.2.8, is there any reason for that? 

Should be nice to see the latest greatest version of Primefaces?

Also would be nice to have it running on latest mojarra 2.2.x version, i.e Mojarra 2.2.13. Are there any reason it´s still running on Mojarra 2.2.8?

**Comment by tandraschko** [comment]
there is no reason for the mojarra version, we could also run on MyFaces 2.2.x. It just doesn't matter.

the showcase actually runs in 6.0.1 if you check the resources, not sure why the version in the footer is not up to date.
We will update it for the next release.
