### ISSUE TITLE
Menubar and MenuButton Not Being Read by JAWS Reader - Section 508

### ISSUE THREAD

**Issue by ginknee** [primefaces/primefaces#1694]
The menubar component is keyboard navigable until you turn on JAWS (using version 17).  But this and the menubutton are not articulated nor navigable by JAWS. I am using Primefaces 6.0. Can you please help with this?

**Comment by tandraschko** [comment]
Can you try the online showcase again and create a new issue + a little analysis plz.
The roles are set correctly AFAICS, so i think it should work.
