### ISSUE TITLE
Delta Theme TabView CSS broken

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1695]
Go to ShowCase and select TabView and delta Theme.

http://www.primefaces.org/showcase/ui/panel/tabView.xhtml 

You can see the content of tab is not displayed as block. I could not find the difference to other themes but i was able to fix it with a quick hack:

```
.ui-tabs-nav{height:2.4em;}
```

**Comment by tandraschko** [comment]
Please try a trunk build, we fixed some things regarding tabview.
Otherwise, i can't see anything wrong with your description ;)

**Comment by tandraschko** [comment]
will close it for now
