### ISSUE TITLE
Ajax keyup event not always fired

### ISSUE THREAD

**Issue by alexsoyes** [primefaces/primefaces#1696]
I just found that on **PrimeFaces 6.0**, `p:ajax event="keyup"` is not always fired.

Here's a sample for testing.

```
<p:inputText value="#{controllerView.currentTestValue}">
     <p:ajax event="keyup" 
                    update="idTesting"
                     listener="#{controllerView.listener()}" />
 </p:inputText>

<h:panelGroup id="idTesting">
     <h:outputText value="#{controllerView.currentTestedValue}"  />
</h:panelGroup>
```

Works perfectly on **PrimeFaces 5.3**. The listener contains just a simple log writer.

`System.out.println("Keyup event invoked : " + getCurrentTestValue());`
## Reproduce the bug
1. On the input, type your text, whatever it is.
2. Go in the input, type `CTRL+A` to get whole text inside, then push `DELETE`.

Listener is not invoked... it is also right when you select with the mouse and cut it.

Thank you again.

PS: I asked the ajax event to update a div, but I am pretty sure you do not need it to reproduce.

**Comment by tandraschko** [comment]
Feel free to fix the issue and provide a PR

**Comment by jxmai** [comment]
OK, I did some debugging for this ticket, and **I cannot replicate this issue using the latest SNAPSHOT.**

First of all, the sample code is incorrect / incomplete:

```js
listener="#{controllerView.listener()}"
```

~~There shouldn't be any bracket in the function call for AJAX events.~~

Second, the sample code does not have a form as the parent, the AJAX request cannot reach server without form.

---

Here is my test code based on the sample:

controllerView:


```java
import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ViewScoped
@ManagedBean(name = "controllerView")
public class ControllerView implements Serializable {

    private static final long serialVersionUID = 5938912961827491176L;

    private String currentTestValue = "Test";

    private String currentTestedValue = "BeforeFire";

    public void listener() {
	currentTestedValue = "Tested";
	System.out.println("Fired");
    }

    public String getCurrentTestValue() {
	return currentTestValue;
    }

    public void setCurrentTestValue(String currentTestValue) {
	this.currentTestValue = currentTestValue;
    }

    public String getCurrentTestedValue() {
	return currentTestedValue;
    }

    public void setCurrentTestedValue(String currentTestedValue) {
	this.currentTestedValue = currentTestedValue;
    }

}
```

xhtml

```html
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
<ui:composition>

	<h:head>
	</h:head>

	<h:body>
		<h:form>
			<p:inputText value="#{controllerView.currentTestValue}">
				<p:ajax event="keyup" update="idTesting"
					listener="#{controllerView.listener}" />
			</p:inputText>
		</h:form>

		<h:panelGroup id="idTesting">
			<h:outputText value="#{controllerView.currentTestedValue}" />
		</h:panelGroup>
	</h:body>

</ui:composition>
</html>

```

Replicate Time:

As soon as type CTRL + A, the ajax fired and the server starts to decode


![image](https://cloud.githubusercontent.com/assets/10467831/26022194/bdd048dc-3763-11e7-9ad5-ad3587b31506.png)

After done, the output shows in the console:

![image](https://cloud.githubusercontent.com/assets/10467831/26022202/16a61d7e-3764-11e7-9f0d-e1ad75cb871d.png)


For the deletion, the ajax can fire as well

![image](https://cloud.githubusercontent.com/assets/10467831/26022214/7b36dc24-3764-11e7-95c5-4462a14a4dcb.png)

**Comment by melloware** [comment]
Nice work @jxmai !  I agree this ticket should be closed.

**Comment by tandraschko** [comment]
@jxmai Thanks for testing. Will close it as can't replicate.
JFYI: using brackets for method-exressions is indeed valid if you don't you parameters.

**Comment by jxmai** [comment]
> JFYI: using brackets for method-exressions is indeed valid if you don't you parameters.

 Thanks for letting me know :) Corrected the comment to avoid confusing others.
