### ISSUE TITLE
FilterBy attribute of <p:columns> crashs when valueExpression is not an indexed value

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#1699]
The following HTML <p:columns> code crashs

```
<p:columns
    value="#{controller.getRegulationGradeList()}"
    var="grade"
    headerText="#{grade.getRegulationPerformanceName()}"
    filterBy="#{ctc.getPerformanceCellValue(grade.getRegulationPerformanceName())}" 
    >
```

because the valueExpression of filterBy attribute doen't contain an indexed value (= value with [ and ] characters) !

This is working very well on Primefaces 5.3 and has stopped to work since I use Primefaces 6.0 !

I have already posted a PullRequest on this issue.

The problem is that the function 
`public String resolveDynamicField(ValueExpression expression)`
in  resolveDynamicField() function of DataTableTemplate.java file
is waiting [ and ] characters in valueExpression and that my expression doesn't contain these characters.

The following code correct the problem !

```
public String resolveDynamicField(ValueExpression expression)
    {
    if(expression != null)
        {
        String expressionString = expression.getExpressionString();
        int iOpen = expressionString.indexOf("[");
        if (iOpen >= 0)
            {   
            int iClose = expressionString.indexOf("]");
            expressionString = expressionString.substring(iOpen + 1, iClose);            
            expressionString = "#{" + expressionString + "}";
            }
    ... like before
    }      

```

I hope only that my explanations are now clear enough for Primefaces acceptation :-)

**Comment by tandraschko** [comment]
Thats what i thought, it's a different example now :P

**Comment by tandraschko** [comment]
should work now ;)
