### ISSUE TITLE
LazyDataModel filtering on DataTable too slow with PF6

### ISSUE THREAD

**Issue by fer-marino** [primefaces/primefaces#1705]
Dear PF team,
I have a datatable with a lazydatamodel that supports filtering and sorting. Everything was running fine with PF 5.3, but when I've updated to 6.0 now every time I want to apply filters it take ages only to reach the load method of the lazydatamodel. My table has 9 columns and only one is filterable. 

I'm running it on wildfly 9, but the issue is present also with wildfly 8.2

The table I'm using is the following:

`<h:form id="table-form">
                    <p:dataTable var="kpi" value="#{kpiFaces.volumePerOrbitAggregate}" paginator="true" rows="30" resizableColumns="true" resizeMode="expand" filterDelay="2000"
                                 paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {PageLinks} {NextPageLink} {LastPageLink}       {Exporters}"
                                 rowsPerPageTemplate="30,40,50,60,70"  id="orbit" lazy="true">
                        <f:facet name="{Exporters}">
                            <h:commandLink>
                                <p:commandButton icon="fa fa-file-excel-o" title="Export as Excel file" global="false"/>
                                <p:dataExporter type="xls" target="orbit" fileName="report-volume-agg" />
                            /h:commandLink
                            <h:commandLink>
                                <p:commandButton icon="fa fa-file-text-o" title="Export as CSV file" global="false"/>
                                <p:dataExporter type="csv" target="orbit" fileName="report-volume-agg" />
                            /h:commandLink
                            <h:commandLink>
                                <p:commandButton icon="fa fa-code" title="Export as XML file"  global="false"/>
                                <p:dataExporter type="xml" target="orbit" fileName="report-volume-agg" />
                            /h:commandLink
                        /f:facet
                        <p:column style="width:16px" exportable="false">
                            <p:rowToggler />
                        /p:column
                        <p:column headerText="Absolute Orbit" width="100" filterBy="#{kpi.absolute_orbit_start}" filterMatchMode="exact">
                            <h:outputText value="#{kpi.absolute_orbit_start}" />
                        /p:column
                        <p:column headerText="ANX Time" width="100">
                            <h:outputText value="#{kpi.anx}">
                                <f:convertDateTime pattern="yyyy-MM-dd'T'HH:mm:ss" />
                            /h:outputText
                        /p:column
                        <p:column headerText="Total Size" width="100">
                            <h:outputText value="#{jsfUtils.humanReadableByteCount( kpi.total_size, false) }" />
                        /p:column
                        <p:column headerText="Total Products" width="100">
                            <h:outputText value="#{kpi.total_products}" />
                        /p:column
                        <p:column headerText="L0 Size " width="100">
                            <h:outputText value="#{jsfUtils.humanReadableByteCount( kpi.l0_size, false) }" />
                        /p:column
                        <p:column headerText="L0 Products" width="100">
                            <h:outputText value="#{kpi.l0}" />
                        /p:column
                        <p:column headerText="L1 Size" width="100">
                            <h:outputText value="#{jsfUtils.humanReadableByteCount(kpi.l1_size, false) }" />
                        /p:column
                        <p:column headerText="L1 Products" width="100">
                            <h:outputText value="#{kpi.l1}" />
                        /p:column

```
                    <p:column headerText="L2 Size" width="100">
                        <h:outputText value="#{jsfUtils.humanReadableByteCount( kpi.l2_size, false) }" />
                    </p:column>
                    <p:column headerText="L2 Products" width="100">
                        <h:outputText value="#{kpi.l2}" />
                    </p:column>

                    <p:column headerText="Downlink Start" width="130">
                        <h:outputText value="#{kpi.downlink_start}" >
                            <f:convertDateTime pattern="yyyy-MM-dd'T'HH:mm:ss" />
                        </h:outputText>
                    </p:column>
                    <p:column headerText="Downlink Stop" width="130">
                        <h:outputText value="#{kpi.downlink_stop}" >
                            <f:convertDateTime pattern="yyyy-MM-dd'T'HH:mm:ss" />
                        </h:outputText>
                    </p:column>
                    <p:column headerText="Downloaded Size" width="100">
                        <h:outputText value="#{jsfUtils.humanReadableByteCount(kpi.downloaded_size, false)}" rendered="#{not empty kpi.downloaded_size}" />
                    </p:column>

                    <p:rowExpansion>
                        <p:dataTable var="kkpi" value="#{kpiFaces.getOrbitDetail(kpi.absolute_orbit_start)}"
                                     resizableColumns="true" >
                            <p:column headerText="Product Type" width="100">
                                <h:outputText value="#{kkpi.product_type}" />
                            </p:column>
                            <p:column headerText="# CGS" width="80">
                                <h:outputText value="#{kkpi.count_nr_cgs}" />
                            </p:column>
                            <p:column headerText="Total Sensing CGS">
                                <h:outputText value="#{jsfUtils.stripInterval( kkpi.sensing_nr_cgs )}" />
                            </p:column>
                            <p:column headerText="# OLCI" width="80">
                                <h:outputText value="#{kkpi.count_nt_olci}" />
                            </p:column>
                            <p:column headerText="Total Sensing NT OLCI">
                                <h:outputText value="#{jsfUtils.stripInterval( kkpi.sensing_nt_olci )}" />
                            </p:column>
                            <p:column headerText="# NT STM" width="80">
                                <h:outputText value="#{kkpi.count_nt_stm}" />
                            </p:column>
                            <p:column headerText="Total Sensing NT STM">
                                <h:outputText value="#{jsfUtils.stripInterval( kkpi.sensing_nt_stm )}" />
                            </p:column>
                            <p:column headerText="# ST STM" width="80">
                                <h:outputText value="#{kkpi.count_st_stm}" />
                            </p:column>
                            <p:column headerText="Total Sensing ST STM">
                                <h:outputText value="#{jsfUtils.stripInterval( kkpi.sensing_st_stm )}" />
                            </p:column>
                            <p:column headerText="# NT SLT" width="80">
                                <h:outputText value="#{kkpi.count_nt_slt}" />
                            </p:column>
                            <p:column headerText="Total Sensing NT SLT">
                                <h:outputText value="#{jsfUtils.stripInterval( kkpi.sensing_nt_slt )}" />
                            </p:column>
                            <p:column headerText="Size" width="100">
                                <h:outputText value="#{jsfUtils.humanReadableByteCount( kkpi.size, false )}" />
                            </p:column>
                            <p:column headerText="Expectd Size" width="100">
                                <h:outputText value="#{jsfUtils.humanReadableByteCount(kkpi.expected_size, false)}" rendered="#{not empty kkpi.expected_size}"/>
                                <h:outputText value="n/a" rendered="#{empty kkpi.expected_size}"/>
                            </p:column>
                            <p:column headerText="Bitrate" width="100">
                                <h:outputText value="#{jsfUtils.humanReadableByteCount(kkpi.bitrate, false)}/s"/>
                            </p:column>
                            <p:column headerText="Expected Bitrate" width="100">
                                <h:outputText value="#{jsfUtils.humanReadableByteCount(kkpi.expected_bitrate, false)}/s" rendered="#{not empty kkpi.expected_bitrate and kkpi.expected_bitrate ne 0}"/>
                                <h:outputText value="n/a" rendered="#{empty kkpi.expected_bitrate or kkpi.expected_bitrate eq 0}"/>
                            </p:column>

                        </p:dataTable>
                    </p:rowExpansion>
                </p:dataTable>
        </h:form>`
```

thank you for your support.

**Comment by tandraschko** [comment]
Please provide a simple maven/jetty sample application, otherwise we can never replicate your problem.

**Comment by tandraschko** [comment]
Please reopen if you can provide a sample application, will close it for now.
