### ISSUE TITLE
Problem in rendering of tabView

### ISSUE THREAD

**Issue by madhu-singh** [primefaces/primefaces#1707]
Till now i was using primefaces 5.0 and tabView was working fine.
![screenshot from 2016-08-18 18 20 02](https://cloud.githubusercontent.com/assets/13217607/17774377/fb810b0a-6570-11e6-937f-73fb9cfb780c.png)

but after upgrading to 6.0 problem is there in tabview rendering. Data is comming after tabs..
![screenshot from 2016-08-18 18 26 01](https://cloud.githubusercontent.com/assets/13217607/17774447/540b1a7c-6571-11e6-9b78-33239b426731.png)

**Comment by tandraschko** [comment]
Already fixed in trunk
