### ISSUE TITLE
Problem in dataexporter header with facet

### ISSUE THREAD

**Issue by jbbjunior** [primefaces/primefaces#1708]
I have problem when exporting a datatable in pdf using ExportData component

If we add any tag or character inside the 
`<f: facet name = "header"> beyond <h: outputText value = "Severity" />`

the title of the column in pdf is the wrong name.

Below is the example of the code problem, note that add to <br/> tag, it generates PDF with the title of the wrong column

```
<p:dataTable widgetVar="tableId" var="alert"
    rowKey="#{alert.entity}" 
    filterMap="#{alertMBean.filterMap}"
    value="#{alertMBean.lazyModel}"
    paginator="true"
    lazy="true"
    paginatorTemplate="{ExportersFile} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
    first="#{alertMBean.currentPage}" rows="#{alertMBean.rows}">

    <f:facet name="{ExportersFile}">
        <h:commandLink title="Export in PDF">
            <img src="/image/icone_PDF.png"/>
            <p:dataExporter type="pdf" target="DataTableId" fileName="AlarmPDF" pageOnly="true" />
        </h:commandLink>
    </f:facet>  

    <p:column>
        <f:facet name="header">
            <h:outputText value="Severity"/>
            <br/> test<!-- Any character entered here, generates problems in PDF title exported -->
        </f:facet>

        <h:outputText value="#{alert.severityStr}" />
    </p:column>

</p:dataTable>
```

Datatable
![datatablealarmes](https://cloud.githubusercontent.com/assets/4489414/17775337/2b20c55a-652e-11e6-9736-6e8dd7826341.jpg)

Export Result:
![alarmespdfexported](https://cloud.githubusercontent.com/assets/4489414/17775428/95183b50-652e-11e6-8145-ceca86ee0bcf.jpg)

We are using:
Primefaces version 5.2.22
Java 1.7.0_79-b15
Jboss WildFly 9
Chrome 52.0.2743.116 m (64-bit)
Windows 7

**Comment by commandercool** [comment]
I have looked into this issue and it turned out that in jbbjunior's case facet component is actually of type `UIPanel` when it comes in `org.primefaces.component.export.Exporter` `exportValue` method.

And as it has no case where `component instanceof UIPanel`, we get facet's value from else clause as:

``` java
String value = component.toString();
```

One way to fix it is to add the above case to handle `UIPanel` components:

``` java
    ...
    }
        else if (component instanceof UIPanel) {
            StringBuilder valueBuilder = new StringBuilder();
            for (UIComponent panelChild : ((UIPanel)component).getChildren()) {
                valueBuilder.append(exportValue(context, panelChild));
            }
            return valueBuilder.toString();
    }
    ...
```

But this still will produce the following output:

![export](https://cloud.githubusercontent.com/assets/8863556/17834007/a146ad0c-6737-11e6-86c0-61f2305952f8.png)

because `<br/> test` has `UIInstructions` type.

**Comment by tandraschko** [comment]
@sudheerj does something similar work in the extensions exporter?

**Comment by mertsincan** [comment]
Please use exportHeaderValue; #3642
