### ISSUE TITLE
ohlc charts not working using dateaxis with date 

### ISSUE THREAD

**Issue by dcdh** [primefaces/primefaces#171]
Hello,

Primefaces use jqplot to display ohlccharts.

From examples available at this location: http://www.jqplot.com/tests/date-axes.php dates data are encapsulated by **simple quotes**.

``` javascript
$(document).ready(function(){
  var line1=[['2008-09-30 4:00PM',4], ['2008-10-30 4:00PM',6.5], ['2008-11-30 4:00PM',5.7], ['2008-12-30 4:00PM',9], ['2009-01-30 4:00PM',8.2]];
  var plot1 = $.jqplot('chart1', [line1], {
    title:'Default Date Axis',
    axes:{xaxis:{renderer:$.jqplot.DateAxisRenderer}},
    series:[{lineWidth:4, markerOptions:{style:'square'}}]
  });
});
```

It's not the case from javascript script generated by primefaces:

``` javascript
$(function(){PrimeFaces.cw('Chart','widget_j_idt357',{id:'j_idt357',type:'ohlc',data:[[[2015-04-23,30.0,120.0,12.0,110.0],[2015-04-24,90.0,102.0,10.0,110.0]]],title:"Evolution du cours",axes:{xaxis: {label:"Date",max:"2015-04-30",renderer:$.jqplot.DateAxisRenderer,tickOptions:{angle:"-50"}},yaxis: {label:"Valeur",renderer:$.jqplot.LinearAxisRenderer,tickOptions:{angle:"0"}}},datatip:true},'charts');});
```

I have lived executed the code in my firebug console with single quotes and it is working. 

Can you add quotes in the file OhlcRenderer line 39 (checked in Primefaces 5.1). This problem may affect other charts type.

Thanks by advance.

Regards,

Damien

**Comment by sorny** [comment]
I know its a late call but you have to set the AxisType to DateAxis:

e.g.: for the X-Axis where model is a OhlcChartModel:
`model.getAxes().put(AxisType.X, new DateAxis());`

**Comment by tandraschko** [comment]
So we can close this ticket?

**Comment by m-kuzmenko** [comment]
The ticket is relevant. See https://stackoverflow.com/q/30146546/6537500

**Comment by sorny** [comment]
Well, as a final remark: Be aware that you have to represent the date in milliseconds for OhlcChartSeries.value as the DateAxis will render it back to a human readable date.

Simply pushing the ate into OhlcChartSeries will cause problems since OhlcRenderer creates the javascript array by calling .toString() while not taking care of string representation.

We can close this ticket now 👍

**Comment by melloware** [comment]
Is this similar to this ticket too?

https://github.com/primefaces/primefaces/issues/95

**Comment by sorny** [comment]
Somehow yes, the series identifier handling in primefaces is not consistent. A line-chart is able to render a plain java.util.Date object while a ohlc-chart is not (based on the issue description, still got to retest the behaviour).

**Comment by melloware** [comment]
OK I will investigate and see if I can fix it.

**Comment by sorny** [comment]
Just had a look into the chart-renderer code. Looks like the encodeData implementations differ a lot. LineRenderer is able to handle a string, OhlcRenderer is not :/

**Comment by melloware** [comment]
I will review all the chart renderers and make them consistent if I can.

**Comment by melloware** [comment]
PR submitted if you want to review it.

**Comment by sorny** [comment]
Code looks good to me, but no unit tests?

**Comment by melloware** [comment]
As a general rule there is very little unit test code coverage of the entire PrimeFaces library.     Its on the long term goal list of the PF Team to add unit testing framework to make unit testing these components easier but its not there right now so unit testing component rendering is a pain.

I forgot to mention that I always test this stuff in the Showcase before committing so I tested all the charts in the showcase and all are working correctly and Dates are rendering with single quotes.

**Comment by sorny** [comment]
Oh, I didnt expect such a mature library to have so little code coverage. I just retested your code changes in my codebase, looks good. +1

**Comment by melloware** [comment]
Thanks for testing!   Yep Code Coverage is on the team's tech debt list.
