### ISSUE TITLE
Adamantium - no highlight on error field

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#1710]
```
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<h:body>
    <h:form>
        <p:outputLabel for="test" value="test"></p:outputLabel>
        <p:selectOneMenu id="test" required="true"></p:selectOneMenu>
        <p:commandButton update="@form" value="Submit"></p:commandButton>
    </h:form>
</h:body>
</html>
```

After clicking the button, there is no red bar under the dropdown menu.

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17823960/c54bdfa6-6624-11e6-9710-aa91cadc1d51.png)

Using other theme:

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17823995/eef01a84-6624-11e6-8987-21d0b5ca1f8b.png)

Ada theme v2.1
Primefaces v5.3.15

**Comment by tandraschko** [comment]
Please use the layouts project, not the PF core.

**Comment by jxmai** [comment]
Alright, Issue has been redirected to the layouts project: https://github.com/primefaces/layouts/issues/108
