### ISSUE TITLE
Send data to managed bean when p:picklist onTransfer done

### ISSUE THREAD

**Issue by sanjayitdesires** [primefaces/primefaces#1711]
I am using primefaces 6.0.3. Here is what I need to do,

I am using p:picklist, when I perform transferring item from source to target, an ajax transfer event will be fired and perform some tasks on managed bean. Let say I have a list of users in picklist source when I transfer a single entry into target then it will show complete details of that particular user below the picklist with a inputText to enter some important notes for that user. Everything works perfect except inputText field values are lost when I fetch on the managed bean.

Can anyone figure out what it the problem exactly and what I should change as well?

**Comment by tandraschko** [comment]
Questions -> Forum ;)
