### ISSUE TITLE
Calendar sets date on open with pattern

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1712]
Using a popup calendar without a pattern only _writes_ into the textbox when date is really selected.

When a pattern is provided, it sets the date when you click first time into the textbox just to open it. It should only set it on user selecting a date from the calendar.

**Observations:**

Clearing the textfield by hand, then clicking again into it does not sets the date! So its only on first click.

When this bug happens, a user may think the _now_ date is already selected. When you submit form, it still says field is not set! It seems its only set visual.

**Comment by tandraschko** [comment]
Does the same occur with plain jquery?

**Comment by tandraschko** [comment]
any news?

**Comment by melloware** [comment]
@djmj any news on this issue? I can't reproduce it but without a reproducible test case I can't tell.
