### ISSUE TITLE
p:selectOneMenu doesn't support "rendered" property with f:selectItem [5.2]

### ISSUE THREAD

**Issue by jabrware** [primefaces/primefaces#1713]
`<p:selectOneMenu value="#{bean.value}">
                <f:selectItem itemLabel="Hello"
                      rendered="false"/>
<f:selectItem itemLabel="Hello 2"
                      rendered="true"/>
</p:selectOneMenu>`

occurs with primefaces 5.2

**Comment by tandraschko** [comment]
1) issues against 5.2 are invalid
2) f:selectItem doesn't have a rendered property, you should use a better IDE. -> http://www.jsftoolbox.com/documentation/help/12-TagReference/core/f_selectItem.html
