### ISSUE TITLE
DataTable - Filtering doesn't rerender Paginator; therefore the Paginator disappears sometimes with paginatorAlwaysVisible=false

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#1715]
**filterTable.xhtml**

``` xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head>
</h:head>

<h:body>
        <h:form>
            <p:commandButton actionListener="#{tableBean.init()}" update=":tableForm" value="reload" oncomplete="PF('tableWidget').filter();"></p:commandButton>
        </h:form>

        <h:form id="tableForm">
            <p:dataTable value="#{tableBean.persons}" 
                        id="persons"
                        widgetVar="tableWidget"
                        paginator="true"
                        paginatorAlwaysVisible="false"
                        rows="2"
                        paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                        rowsPerPageTemplate="2"
                        filteredValue="#{tableBean.filterPersons}"
                        var="person">
                <f:facet name="header">
                        Bug Report 
                </f:facet>

                <p:column headerText="Name" filterBy="#{person.name}" filterMatchMode="contains" footerText="contains">
                    <h:outputText value="#{person.name}" />
                </p:column>
            </p:dataTable>
        </h:form>

</h:body>
</html>
```

**TableBean.java**

``` java

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "tableBean")
@ViewScoped
public class TableBean implements Serializable {

    private List<Person> persons = new ArrayList<Person>();

    private List<Person> filterPersons;

    private static final long serialVersionUID = -2848956414992723911L;

    @PostConstruct
    public void init() {
        persons.clear();

        Person person1;
        Person person2;
        Person person3;
        person1 = new Person("Person 1");
        person2 = new Person("Person 2");
        person3 = new Person("Person 3");

        this.getPersons().add(person1);
        this.getPersons().add(person2);
        this.getPersons().add(person3);
    }

    public List<Person> getPersons() {
        return persons;
    }

    public void setPersons(List<Person> persons) {
        this.persons = persons;
    }

    public List<Person> getFilterPersons() {
        return filterPersons;
    }

    public void setFilterPersons(List<Person> filterPersons) {
        this.filterPersons = filterPersons;
    }

}

```

**Person.java**

``` java

import java.io.Serializable;

public class Person implements Serializable {

    private static final long serialVersionUID = 8742265431595759127L;

    private String name;

    public Person() {
        super();
    }

    public Person(String name) {
        super();
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
```

Initial Screenshot:

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17865226/21fb298e-6867-11e6-83c8-226cfb6fab55.png)

Step 1: Filter out some records:

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17865259/53dffdee-6867-11e6-8871-d5cad6fb5399.png)

Step 2: Click reload button on the top left corner, and you will see **the paginator disppears**.

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17865300/83e9eb12-6867-11e6-952b-9abf8b44ec8e.png)

Step 3: Click the button the second time, and the paginato appears again.

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17865325/b28153f2-6867-11e6-8471-5d72447d0b73.png)

Running on:
Primefaces v5.3.15

**Comment by jxmai** [comment]
I also provided a sample using **maven / jetty** based on showcase's code base

[Issue_#1715.zip](https://github.com/primefaces/primefaces/files/431081/Issue_.1715.zip)

Run from terminal: 

```
mvn clean jetty:run  
```

```
http://localhost:8080/showcase/
```

or

```
http://localhost:8080/showcase/filterTable.xhtml
```

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/17870591/c8ade3fa-687d-11e6-8475-7f510eb04e22.png)

**Comment by tandraschko** [comment]
If i understand correctly:
1) filter with e.g. "1"
2) ajax update the component
3) the DataTableRenderer renders only "Person 1" as the data is still filtered internally - but the entered filter value isn't rendered and the paginator won't be rendered as paginatorAlwaysVisible is false (which is correct as only 1 page is available)
4) widget.filter filters the datatable with empty string and all entries will be rendered, but the paginator won't be rerendered

AFAICS we have 2 bugs here:
1) the filter input isn't rendered on a ajax update
    the data is internally filtered but the user doesn't see if the data is filtered
2) on filtering, the paginator should be rendered

**Comment by tandraschko** [comment]
not sure if we can fix it easily, i would use paginatorAlwaysVisible=true in your case. So you also won't have flickering.

**Comment by jxmai** [comment]
Quotes as a recap

> not sure if we can fix it easily, i would use paginatorAlwaysVisible=true in your case. So you also won't have flickering.

> AFAICS we have 2 bugs here:

>the filter input isn't rendered on a ajax update
>the data is internally filtered but the user doesn't see if the data is filtered
>on filtering, the paginator should be rendered

@tandraschko I have linked a couple other related issues to this one (They all pointed to the bug 1). Although the pagination can have a workaround such as setting paginator to `true` (does not look nice by the way :disappointed: ). The bug 1 seems to be a long-running bigger issue.

**Comment by neXus1987** [comment]
I think one problem could be that if a datatable is displayed the second time on a view with a viewscope bean, the filter should be applied during the jsf lifecycle and not on the clientside. This will mean that you will not control the filteredValue from backend and i think this the right way, because the filteredValue is just a result of the filtering happened on clientside. And when you want to clear your filter, you should set the filteredValue from the columns to null/"". So when the datatable is initially created the filter isn´t needed but when you go back in a viewscope view and show the datatabel again i think the filter should be applied because when you change the value of the value-attribute the new values should be also applied to the datatable fitleredValue.

**Comment by cnsgithub** [comment]
I think the question wether the paginator should be displayed or not should be done completely in client side to make things as simple as possible. As already stated in #1953 there is a way to do it with JS. However there was no actual implementation. So for those who need a working solution for this issue follow these steps:

1.  Set a widget Var for your table, and set  paginatorAlwaysVisible="true" (= we will manage the visibility with JS)
```
widgetVar="myWidgetVar"  paginatorAlwaysVisible="true" 
```
2. Add the JS function somewhere

```
function autoHidePaginatorForDataTable(widgetVar){
	
	var rows = PF(widgetVar).paginator.cfg.rows;
	var rowCount = PF(widgetVar).paginator.cfg.rowCount;
	
	if(rowCount <= rows){
		$(PF(widgetVar).paginator.jq[0]).hide();//top paginator
		$(PF(widgetVar).paginator.jq[1]).hide();//bottom paginator
	} else {
		$(PF(widgetVar).paginator.jq[0]).show();//top paginator
		$(PF(widgetVar).paginator.jq[1]).show();//bottom paginator
	}
	
}
```
3. bind it to the table's filter event
```
<p:ajax event="filter" oncomplete="autoHidePaginatorForDataTable('myWidgetVar');"/>
```

**Comment by jxmai** [comment]
Hi @cnsgithub , your workaround looks reasonable :+1: . I will give it a try later using the bug demo on the issue. If it works, I might raise a PR based on your idea since the information you provided can be accessed in `bindPaginator` which is called right after `update`.

![image](https://user-images.githubusercontent.com/10467831/27308485-652dd5ea-5514-11e7-959c-b07904c4239a.png)

**Comment by melloware** [comment]
@jxmai that sounds like a good plan.  Also do you mind checking out the Extensions forum somebody asked a CKEditor question and I am not sure I answered him correctly.

**Comment by jxmai** [comment]
> Also do you mind checking out the Extensions forum somebody asked a CKEditor question and I am not sure I answered him correctly.

@melloware No problem 😄  I believe you meant this: https://forum.primefaces.org/viewtopic.php?f=14&t=51402.  There should be an out-of the box solution by setting `language = "de"` in the attribute. I don't have a forum account yet so you can make a reply in the forum linked to this post.

For example,

```html
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
<ui:composition>

	<h:head>
	</h:head>

	<h:body>
		<h:form>
			<pe:ckEditor language="de"></pe:ckEditor>
		</h:form>
	</h:body>

</ui:composition>
</html>
```

can result in: 


![image](https://user-images.githubusercontent.com/10467831/27313478-a342a59e-5533-11e7-99f0-ec0128fdeede.png)

**Comment by jxmai** [comment]
> Also do you mind checking out the Extensions forum somebody asked a CKEditor question and I am not sure I answered him correctly.

@melloware No problem 😄  I believe you meant this: https://forum.primefaces.org/viewtopic.php?f=14&t=51402.  Yes, you can provide a custom config file to do some tweaks, but I am not sure whether this tweak is needed since there is not much difference to me during my testing. I don't have a forum account yet so you can make a reply in the forum linked to this post. 

For example,

```html
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
<ui:composition>

	<h:head>
	</h:head>

	<h:body>
		<h:form>
			<pe:ckEditor language="el"
						customConfig="#{request.contextPath}/resources/default/1_0/js/ckeditor.js"
			>
			
			</pe:ckEditor>
		</h:form>
	</h:body>

</ui:composition>
</html>
```

and the config:

```js
CKEDITOR.editorConfig = function( config ) {
	config.specialChars = config.specialChars.concat( [ '&alpha;'],
			[ '&beta;'],
			[ '&gamma;' ],
			[ '&delta;'],
			[ '&epsilon;'],
			[ '&zeta;'],
			[ '&eta;'],
			[ '&theta;' ],
			[ '&iota;'],
			[ '&kappa;'],
			[ '&lambda;'],
			[ '&mu;'],
			[ '&nu;'],
			[ '&xi;' ],
			[ '&omicron;'],
			[ '&pi;' ],
			[ '&rho;'],
			[ '&sigma;' ],
			[ '&sigma;'],
			[ '&tau;'],
			[ '&upsilon;' ],
			[ '&phi;'],
			[ '&chi;'],
			[ '&psi;'],
			[ '&omega;']); 
};
```

can result in: 

![image](https://user-images.githubusercontent.com/10467831/27314023-bff5c8da-5536-11e7-832b-657326e347d6.png)

**Comment by jxmai** [comment]
>  I will give it a try later using the bug demo on the issue. If it works, I might raise a PR based on your idea since the information you provided can be accessed in bindPaginator which is called right after update.

No, the workaround cannot be applied into the framework directly since the number of `row` is less than the `rowPerPage` during the paginator's render time.

**Comment by mauritz-lovgren** [comment]
As @jxmai stated, the proposed solution JS in this issue does not work, since `paginator.cfg.rows` and `paginator.cfg.rowCount` are not properly set at the time the oncomplete event is fired.

Our hack was to use a PostFilterEvent listener:

```
<f:event type="org.primefaces.event.data.PostFilterEvent" listener="#{datatableUtilBean.postFilterListener('datatableWidgetvarName')}"/>
```

The listener would call the JS that performed the showing / hiding of the paginator based on actual filtered rows. We put all this in a composite datatable component. This requires that an initial filter event is triggered onload as well, to make sure initial visible state is correct.
It's a dirty hack and causes flickering (as mentioned by @tandraschko) and it should preferably be solved by PrimeFaces internal paginator refresh code after filtering has occurred.

**Comment by jxmai** [comment]
To see if anything helpful after https://github.com/primefaces/primefaces/issues/2742 is fixed

**Comment by edudoda** [comment]
Same problem here. 
Recently we added a JS call: `onclick="if(PF('tabela')){ PF('tabela').clearFilters();}"` in a `<p:commandLink />` component to ensure new dataTable values displayed are not filtered with previously user values. But then,  if `paginatorAlwaysVisible="false" `, next times, when new dataTable registries should have paginator, none is displayed =/

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/1178
