### ISSUE TITLE
why rendered label for filter on column

### ISSUE THREAD

**Issue by SamanDev** [primefaces/primefaces#1717]
my project on primefaces 5.2 was working good but when upgrade to primefaces 6.03 in my datatable
header column has been problem and why rendered label for filter on column?

<label id="transForm:requestDL:j_idt647:filter_label" for="transForm:requestDL:j_idt647:filter" class="ui-helper-hidden">Filter by From</label>

**Comment by tandraschko** [comment]
no example, no detailed description, it's a question -> please use the forum

**Comment by marcelopio** [comment]
Hi, just for documentation:

His problem is that he is seeing the ariaMessage:

`//aria
            String ariaLabelId = filterId + "_label";
            String ariaHeaderLabel = getHeaderLabel(context, column);
            
            String ariaMessage = MessageFactory.getMessage(DataTable.ARIA_FILTER_BY, new Object[]{ariaHeaderLabel});

            writer.startElement("label", null);
            writer.writeAttribute("id", ariaLabelId, null);
            writer.writeAttribute("for", filterId, null);
            writer.writeAttribute("class", "ui-helper-hidden", null);
            writer.writeText(ariaMessage, null);
            writer.endElement("label");`

And the solution is that his CSS is probably wrong, and the display:none property of the label is overwritten.
