### ISSUE TITLE
AutoComplete: enhance usability with tabbing

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#1719]
When tabbing through Autocomplete with dropdown="true" user has to tab twice to get the focus on the next input. 

This issue is visible in http://www.primefaces.org/showcase/ui/input/autoComplete.xhtml
http://forum.primefaces.org/viewtopic.php?f=3&t=15101

**Comment by Rapster** [comment]
Does not seem a bug to me, dropdown button gets focus. Type "Enter" will expand it

**Comment by arunvc** [comment]
Its a usability problem...
try to place 4 to 5 autocomplete in a page with dropdown="true" 
using tab to navigate is annoying for user, cause they have to tab twice. 

better usability approach on tab change
1. if auto complete has some value the focus should go to the next input control,
2. if auto complete has no value then focus to the drop down button.  

Any way thank you.

**Comment by Rapster** [comment]
I don't see it as a usability problem, I like it actually :) What "bothers" me the most is once selected, press Tab goes back to the dropdown button, but I guess it's okay in case autocomplete is multiple. It's up to PF team :)

**Comment by melloware** [comment]
I agree with @Rapster  To me this is a focusable UI button and therefore must get tab press.  Fixing it to me would break 508 accessibility for visually impaired users.

**Comment by melloware** [comment]
By adding `dropdownTabindex="-1"` in PF 9.0 you will be able to solve this by making the drop down button not tabbable.
