### ISSUE TITLE
Missing resource version in some cases cause of missing #createResource implementation

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#172]
The **PrimeResourceHandler#createResource(resourceName, libraryName, contentType)** method should be implemented to add the version in PF resources. A Pull Request was submitted.

**Comment by cagataycivici** [comment]
Should we add this to Elite 5.1.x and 5.2.x as well?

**Comment by cagataycivici** [comment]
Merged to 5.2.2 and 5.1.17 as well.
