### ISSUE TITLE
Tab key in p:editor working different for Chrome and Firefox/IE/Opera

### ISSUE THREAD

**Issue by spio** [primefaces/primefaces#1724]
In the p:editor component, the tab key has a different behaviour in Chrome compared to other browsers. While in Firefox, IE and Opera the tab key produces the input to be transferred to the next ui component (blur), in Chrome sometimes it puts a tab-space in the text or even do nothing (depending on Chrome's version). 
I think that the correct behaviour is to transfer control to the next ui component, as that is the behaviour of all other ui components, and also that is what is recommended by accesibilty rules.

**Comment by tandraschko** [comment]
See https://github.com/primefaces/primefaces/issues/2168
