### ISSUE TITLE
Dialog Framework: openDialog not working properly within nested dialogs

### ISSUE THREAD

**Issue by jrcampins** [primefaces/primefaces#1725]
I’m using PrimeFaces 6.0 and I’ve found a problem using nested dialogs. **RequestContext.openDialog** is not working properly. It doesn’t throw any exception, but it doesn’t open the dialog.

I built 5 pages (P1 to P5) based on the same Full Page Layout. Each page contains a **p:dataTable**. The **p:dataTable** has a **p:column** with a **p:commandButton** to open the next page in a new (nested) dialog. I’ve found that on some of those pages one or more of the buttons don’t work. As I said before, **openDialog** doesn’t open the new dialog and it doesn’t throw any exception.

After performing several tests I concluded that the problem isn’t inherent to the row data. When the button of the first row fails, it fails regardless the row that is being showed there. Rows can be sorted in different ways (so the first one would vary) and the button of the first row will continue failing and the rest of the buttons will continue working. The problem isn’t inherent to the page either. All buttons work properly when the page is root (the one that opens the first dialog). I used P1 to P4 as root and then all their buttons worked. The problem only happens within a dialog.

**After some more tests I found a work around. I just gave the button a different id in each page and now all the buttons of all the pages work just fine.**

This is the button (of page P1, as its **id** suggests):

```
    <p:commandButton
        id=buttonOfPage1
        icon="fa fa-folder-open"
        action="#{ambientePrueba11.openDialog(currentRow)}"
        partialSubmit="true"
        process="@this"
        update="@none">
        <p:ajax
            event="dialogReturn"
            listener="#{ambientePrueba11.onDialogReturn}"
            update="dataTable"/>
    </p:commandButton>
```

This is the code in the backing bean (each of the 5 beans have a different outcome, but the rest of the code is the same):

```
    public String openDialog(AmbientePrueba row) {
        EventLogger.log(this, "openDialog", getDenominacion(row));
        Object identificacion = getIdentificacion(row);
        String key = "PaquetePrueba11";
        String outcome = FacesUtils.getPageKeyFacesOutcome(key);
        Map<String, Object> options = new HashMap<>();
        options.put("modal", true);
        options.put("resizable", true);
        options.put("draggable", true);
        options.put("width", 1260);
        options.put("height", 860);
        options.put("contentWidth", "100%");
        options.put("contentHeight", "100%");
        options.put("closable", true);
        options.put("includeViewParams", true);
        options.put("minimizable", true);
        options.put("maximizable", true);
        Map<String, List<String>> params = new HashMap<>();
        params.put(CPP.ID_RECURSO, toList(identificacion));
        params.put(CPP.ID_RECURSO_MAESTRO, toList(identificacion));
        params.put(Global.PARAMETRO_FRAMEWORK_SESION,
            toList(getSessionFrame()));
        params.put(Global.PARAMETRO_CONDICION_SESION, toList(MODAL));
        RequestContext.getCurrentInstance().openDialog(outcome,
            options, params);
        return null;
    }

    private List<String> toList(Object value) {
        List<String> paramValue = new ArrayList<>();
        paramValue.add(value + "");
        return paramValue;
    }

    public void onDialogReturn(SelectEvent event) {
        Object response = event.getObject();
        facesLogger.info(response + "");
    }
```

**Comment by jrcampins** [comment]
BTW, I tried to follow the code using the debugger but I couldn't because apparently RequestContext's source code isn't available (I'm using Maven to administer project dependencies and to download source and javadoc)

**Comment by tandraschko** [comment]
Could you please post a full runnable example? At best you can fork the primefaces-test project.
