### ISSUE TITLE
breadcrumb throws a NumberFormatException when its items have a command but not an id.

### ISSUE THREAD

**Issue by jrcampins** [primefaces/primefaces#1726]
I found the problem when I started setting the menu item’s **command** instead of its **URL** or **outcome** (it never happened when all the items had either URL or outcome).

I followed the code execution using the debugger and I realized that it was trying to get the item position within the breadcrumb converting its **id** to integer. So, to work around the problem I simply had to add the following line to the method I use to that add menu items to the breadcrumb's menu model elements list:

`item.setId(elements.size() + "");`

I found this problem when I was using PrimeFaces 5.3. I recently moved to 6.0 and haven't tested again. It might have been fixed already.

**Comment by tandraschko** [comment]
Please test first before you open a issue ;)
Feel free to reopen then.

**Comment by jrcampins** [comment]
This morning I tested it using PrimeFaces 6.0. The problem remains. I'll re-open the issue.

**Comment by tandraschko** [comment]
Don't forget the easy-as-possible example, otherwise "invalid" ;)

**Comment by jrcampins** [comment]
This time I included the stack trace. There you can see the item's id is been used to determine the item's index within the menu (in this case the breadcrumb's menu model). The strange part is that the problem doesn't happen if you set the item's URL or outcome. It only fails if I set command instead. The good part is that it fails consistently. So I guess you won't need an example and you should have no problem reproducing the problem.

**Comment by tandraschko** [comment]
a stacktrace is not enough, i need a exmaple

**Comment by jrcampins** [comment]
Dear Thomas, I am trying to help you improve PrimeFaces by reporting the problems I find and describing them the best way I can. In this particular case I also found a work around, so when I post the issue I am only thinking about the rest of the community. I don't know what kind of example you are asking for. My description of the problem is precise so I think you don't really need one. It is up to you now to try to determine the cause of the problem and a proper solution.

**Comment by tandraschko** [comment]
I just need a sample xhtml + bean, otherwise i must spend (many, maybe not in this case) time to generate a working example, to analyze the problem and fix it.
As i help here in my freetime (!), i would like to get an easy as possible example to generate an fast as possible bugfix ;)

**Comment by jrcampins** [comment]
Ok. Got it. I'll be sending you such an example shortly. 

Sent from Samsung Mobile.

<div>-------- Original message --------</div><div>From: Thomas Andraschko notifications@github.com </div><div>Date:29/08/2016  11:52 AM  (GMT-04:00) </div><div>To: primefaces/primefaces primefaces@noreply.github.com </div><div>Cc: Jorge Campins jrcampins@gmail.com, Author author@noreply.github.com </div><div>Subject: Re: [primefaces/primefaces] breadcrumb throws a NumberFormatException
  when its items have a command but not an id. (#1726) </div><div>
</div>I just need a sample xhtml + bean, otherwise i must spend (many, maybe not in this case) time to generate a working example, to analyze the problem and fix it.
As i help here in my freetime (!), i would like to get an easy as possible example to generate an fast as possible bugfix ;)

**Comment by jrcampins** [comment]
Thomas, I added the example to the open issue #1729
