### ISSUE TITLE
Dock: allow css styling via styleClass or passthrough attributes

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1727]
The <p:dock> component doesn't have styleClass, and neither does pt:class work for it. This is required to modify it's appearance individually

**Comment by tandraschko** [comment]
Feel free to provide a PR

**Comment by cnsgithub** [comment]
Maybe do it like here

https://github.com/primefaces/primefaces/commit/977a2965619a874368e31a660f4603d80550b3b6

**Comment by tandraschko** [comment]
Yup, why not. Try it and provide a PR.

**Comment by tandraschko** [comment]
Thanks!
