### ISSUE TITLE
Dock: animation does not work when page can be scrolled

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1728]
This might be a duplicate of this ( https://github.com/primefaces/primefaces/issues/226 ) but since it hasnt been fixed for over a year ill try to make a better explanation of it so you can understand what's going wrong

You can reproduce the issue in the Showcase:

http://www.primefaces.org/showcase/ui/menu/dock.xhtml

Now Use the Chrome inspector and set the <html tag's height to 2000px. 

Now when the page is scrolled up the icons are correctly animated when hovering, however if you scroll the page completely to the botton the animations stop working.

**Comment by melloware** [comment]
Found and applied this fix and verified it now works with your test case provided above!

http://www.monkey-business.biz/181/jquery-interfaces-fisheye-position-fixed-patch/#jquery-interfaces-fisheye-position-fixed-patch_english

**Comment by cnsgithub** [comment]
May i ask why this simple fix has not been merged into the elite jars? Don't get me wrong i understand that not everything can be backported, but this bug basically makes a whole component useless. (Since the whole point of it is to have that animation). So it would be good to have this in the next Elite *.jar. Unless 6.2 is almost to be released.. Thanks..

**Comment by melloware** [comment]
6.2 RC is coming out this week.
