### ISSUE TITLE
menuitem under p:contextMenu not works correctly when rendered param is evaluated

### ISSUE THREAD

**Issue by projectsforce** [primefaces/primefaces#174]
When I have rendered param in menuitem, which evaluates if item has to be rendered or not on base of user's rights / on base of node param, target action listener is not hit.
If rendered param is not used, everything is working.

Running on PrimeFaces 5.1.16 and Mojarra 2.1.7-jbossorg

**Comment by cagataycivici** [comment]
Please provide a sample test case we can use to replicate.

**Comment by projectsforce** [comment]
Hello,
yes, the code is in attachment - xhtml and dto object.
p:tree contains this dto objects.

When "rendered" param is used in p:menuitem,
listFilesBean.setParentDirIdForFolderFromNode() is not hit when I click to
this menuitem. But when I do not use ths param, it works.

p:menuitem value="#{messages.file_newdir}" icon="ui-icon-newwin"
ajax="true"
actionListener="#{listFilesBean.setParentDirIdForFolderFromNode}"
oncomplete="PF('newDirDlg').show()" update=":#{p:component('newdirGrid')}"
_rendered="#{node.canWrite}"_

Jiri

2015-04-27 13:55 GMT+02:00 Çağatay Çivici notifications@github.com:

**Comment by tandraschko** [comment]
No example, will close it as invalid for now.
You can still create a new issue and fill every info requested by our issue template.
