### ISSUE TITLE
update jqPlot to 1.0.9

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#1749]
https://github.com/jqPlot/jqPlot/compare/d873684c50b560c1600f09879f0cfce9f71e702f...d96a669fbb729f4f51e2214688e54320411219af

**Comment by tandraschko** [comment]
@mertsincan We did some fixes in the jqplot js. Did you create issues on jqplot side? We could also create PR's there ;)

**Comment by erickdeoliveiraleal** [comment]
I tried to indentify @mertsincan patches here: https://github.com/primefaces/primefaces/pull/1755

**Comment by mertsincan** [comment]
I'm sorry for the late reply. I was on holiday :) I'll check our jqplot fixes on 6.1.

**Comment by tandraschko** [comment]
They are already merged :) But we should really try to get the fixed directly into jqplot for further updates.

**Comment by tandraschko** [comment]
@erickdeoliveiraleal the upgrade of jqlpot destroyed following example "showcase/ui/chart/area.xhtml"
If you check it with firebug, following js error occurs: TypeError: this._barPoints is undefined

Please fix it or i need to revert your upgrade.

**Comment by tandraschko** [comment]
FYI: tried to fix it via also adding "&& this._barPoints" to the IF statement in 20771 but the result is that the points are not summed up like in the example on the current showcase.

**Comment by tandraschko** [comment]
@erickdeoliveiraleal ping ;)

**Comment by erickdeoliveiraleal** [comment]
I can't do it, because I don't know, sorry.

**Comment by tandraschko** [comment]
Revert as one chart type was broken.
