### ISSUE TITLE
Datatable with draggableColumns and Dynamic Columns won't update the column model list index

### ISSUE THREAD

**Issue by leohalmeida** [primefaces/primefaces#1758]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? no
- Application server + version: Wildfly 8.2.0.Final
- Affected browsers: tested on Firefox 48
## 2) Expected behavior

The expected behaviour is datatable to update the index of the columns list on the backing bean on 'colreorder' event, just like when you drag a row and its index is automatically updated on the list.
## 3) Actual behavior

The column reorder of dynamic columns works but doesn't updates the model list. Also, the colreorder event doesn't includes the indexes involved.
## 4) Steps to reproduce

Use a datatable with draggableColumns="true" and the <p:columns> component inside. Move one column.

**Comment by vlapra** [comment]
Something new about it?

**Comment by melloware** [comment]
This now works if you use MultiViewState it remembers the column order of your rearranged columns even in the `colreorder` event as its stored in MVS.

https://primefaces.github.io/primefaces/9_0/#/core/multiviewstate?id=multiviewstate
