### ISSUE TITLE
Unecessary non-mobile resources loaded when navigating to PrimeFaces mobile view via Ajax

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#1759]
## 1) Environment
- PrimeFaces version: **6.0**
- Does it work on the newest PrimeFaces version? **Yes**
- Application server + version: **All Servers** (but reproduced on Tomcat 8.0.32)
- Affected browsers: **All Browsers** (but dev tools like those of Firefox or Chrome are needed to actually show the issue)
## 2) Expected behavior

PrimeFaces should only load mobile resources when navigating to a PrimeFaces mobile view.
## 3) Actual behavior

PrimeFaces renders non-mobile resources such as **`components.js`** and **`components.css`** when navigating via ajax to a PrimeFaces mobile view. This bug only occurs when navigating from pages which do not contain **`components-mobile.js`** or **`components.js`** already. This bug causes JS errors in a portlet environment. This issue does not occur with PrimeFaces `5.3` and below.
## 4) Steps to reproduce
1. Clone the reproducer project:
   
   ```
   git clone https://github.com/stiemannkj1/primefaces-mobile-ajax-resources-issue-reproducer
   ```
2. Build the project with maven:
   
   ```
   cd primefaces-mobile-ajax-resources-issue-reproducer && mvn clean install
   ```
3. Deploy the project to tomcat:
   
   ```
   cp target/primefaces-mobile-ajax-resources-issue-reproducer*.war $TOMCAT_HOME/webapps/
   ```
4. Navigate to **`index.xhtml`** ([http://localhost:8080/primefaces-mobile-ajax-resources-issue-reproducer-1.0-SNAPSHOT/faces/index.xhtml](http://localhost:8080/primefaces-mobile-ajax-resources-issue-reproducer-1.0-SNAPSHOT/faces/index.xhtml)).
5. Right click on the page and select _Inspect Element_.
6. Click on the _Network_ tab to see what resources are loaded.
7. Click the _page2_ `h:commandButton`.

If the bug still exists, then **`components.js`** will be loaded via `GET`. If the bug is fixed, then **`components.js`** and all other non-mobile resources will not be loaded. **Note:** during a non-ajax request, non-mobile resources are suppressed by the [PrimeFaces mobile `HeadRenderer`](https://github.com/primefaces/primefaces/blob/6_0/src/main/java/org/primefaces/mobile/renderkit/HeadRenderer.java#L96-L104):

```
if(library != null && library.equals("primefaces")) {
    String resourceName = (String) attrs.get("name");
    if(resourceName.startsWith("jquery")
            || resourceName.startsWith("primefaces")
            || resourceName.startsWith("components")
            || resourceName.startsWith("core")) {
        shouldRender = false;
    }
}
```
## 5) Example Code (Reproducer)

As noted in the steps to reproduce, the code needed to reproduce this issue is available here: [https://github.com/stiemannkj1/primefaces-mobile-ajax-resources-issue-reproducer](https://github.com/stiemannkj1/primefaces-mobile-ajax-resources-issue-reproducer).
## 6) Workarounds

To workaround this issue, only use `p:commandButton` for ajax navigation.

**Comment by tandraschko** [comment]
PrimeFaces Mobile will be deprecated  in 6.2 and removed in 6.3 ( see https://www.primefaces.org/primefaces-6-2-roadmap/)
Therefor i will close this issue as won't fix. If you will provide a PR to fix this issue until 6.2 RC1, i can merge it.
