### ISSUE TITLE
Schedule's month view is missing a bottom border.

### ISSUE THREAD

**Issue by tryptichon** [primefaces/primefaces#176]
Since PrimeFaces 5.2, the month view of schedule is missing a bottom border, see showcase at http://www.primefaces.org/showcase/ui/data/schedule.xhtml. This is especially visible with other themes than the standard ("afterwork" for example):
![schedule_month_view_without_border_bottom](https://cloud.githubusercontent.com/assets/5908199/7345982/4ded0c74-ecda-11e4-9104-02da8fa8fd7c.jpg)

**Comment by mertsincan** [comment]
which browser are you using?

**Comment by tryptichon** [comment]
Silly me... it was Firefox 37.0.2.
Lemme check that in IE and Chrome as well.

...

Hm. Seems to be a problem with Firefox. Chrome  42.0.2311.90 m and IE 11.0.18 work as intended.

**Comment by cagataycivici** [comment]
Does this work fullcalendar's own demos?

**Comment by tryptichon** [comment]
Yes, the Firefox displays a bottom line on the calendar in http://fullcalendar.io/.

**Comment by cagataycivici** [comment]
Weird, so we have the old version of css?

**Comment by tandraschko** [comment]
Can't replicate - its fully in our showcase
