### ISSUE TITLE
Mobile: Add tooltip widget

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#1761]
Tooltip should also be supported on mobile renderkit. There is no mouse on mobile devices, but it  would be useful to have the possibility of showing a tooltip when needed. On the default renderkit this can be done by using PF('tooltipWidget1').show()

**Comment by tandraschko** [comment]
There is no tooltip renderer for mobile. So we only have 1 tooltip.

**Comment by tandraschko** [comment]
The problem is that there is currently no tooltip widget available for mobile.
So this is a feature request.

**Comment by tandraschko** [comment]
In 6.1 the mobile renderkit will be deprecated in favor of responsive features. So please provide a PR if would like to get this fixed.

Will close it for now and reopen if a PR is provided.

**Comment by cnsgithub** [comment]
Hi, question: Does it mean all "pm:" tags will be deprecated or just the renderkit (Components at: http://www.primefaces.org/showcase/mobile/index.xhtml) ? Would it be possible to "mix" them with 6.1 then?
