### ISSUE TITLE
add scrollbar component in the menu bar

### ISSUE THREAD

**Issue by pablosborges** [primefaces/primefaces#1762]
hello I am using the 5.3.16 version, I feel the lack of a feature in the menubar, as the items in my menu are many and just that the screen resolution must clearly the user to see all items. I have not found a way to reduce the spacing of a menu item.

**Comment by mertsincan** [comment]
I think you can try;

```
.ui-menubar .ui-menuitem-link {
   padding: 0.1em 0.3em /* you can change these values */
}
```

**Comment by melloware** [comment]
Solution provided...closing issue.
