### ISSUE TITLE
Timeline Component attribute showCurrentTime has no effect when value is fale

### ISSUE THREAD

**Issue by andyba** [primefaces/primefaces#1763]
## 1) Environment
- PrimeFaces version: 6.0.4
- Does it work with the curent PrimeFaces version: No
- Payara 4.1.1.163
- Affected browsers:
  All, Not dependent on browser version
## 2) Expected behavior

That setting showCurrentDate="false" results in the current date line not being rendered.
## 3) Actual behavior

Setting showCurrentDate="false" has no effect, the current date line is still rendered.
## 4) Steps to reproduce

Take the timeline showcase example and set showCurrentDate="false", the current time bar is still rendered.
## 5) Sample XHTML

See above
## 6) Sample bean

See above

**Comment by andyba** [comment]
Please see the following link, a fix has been proposed for the TimelineRenderer class: http://forum.primefaces.org/viewtopic.php?p=146194#p146194

**Comment by tandraschko** [comment]
Hey andy, would be great if you could provide a PR. I will merge ASAP then.

**Comment by andyba** [comment]
Unfortunately that is difficult as connection to GIT repositories is difficult from work.
Isn't the code in the original post enough to sort it out?

**Comment by tandraschko** [comment]
Maybe, just don't have that much time and accepting a PR is much easier for me.

**Comment by andyba** [comment]
I will see if I can get it done tonight, from home.

**Comment by andyba** [comment]
I wasn't able to get it done last night, time issues. I will see what can be done today.

**Comment by melloware** [comment]
I submitted a PR for this.
