### ISSUE TITLE
Ajax navigation with h:commandButton causes "malformedXML: PrimeFaces is not defined" error

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#1769]
## 1) Environment
- PrimeFaces version: **6.0** (This bug does not occur in 5.3 and below, because it is due to [PrimeFaces Dynamic Resource Dependency Loading](https://github.com/primefaces/primefaces/issues/1066) which was added in PrimeFaces 6.0)
- Does it work on the newest PrimeFaces version? **Yes**
- Application server + version: **All Servers**
- Affected browsers: **All Browsers**
## 2) Steps to reproduce
1. Navigate to **`index.xhtml`**.
2. Click the _view2_ button.
## 3) Expected behavior

The browser navigates to **`view2.xhtml`** without errors.
## 4) Actual behavior

The browser fails to navigate to **`view2.xhtml`** and throws the following error in an `alert()` dialog:

> malformedXML: PrimeFaces is not define
## 5) Sample XHTML

**`index.xhtml`:**

``` xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <h:commandButton action="view2.xhtml" value="view2">
                <f:ajax execute="@form" render="@form" />
            </h:commandButton>
        </h:form>
    </h:body>
</html>
```

**`view2.xhtml`:**

``` xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <p:calendar showOn="button" />
            <p:commandButton value="index" action="index.xhtml" />
        </h:form>
    </h:body>

</html>
```
## 6) Workarounds

To workaround this issue, use `p:commandButton` instead of `h:commandButton` for ajax navigation.

**Comment by stiemannkj1** [comment]
Since there is such a simple straightforward workaround, this issue should probably be low priority, but I wanted to document it in case anyone else runs into it.

**Comment by tandraschko** [comment]
Should be fixed, would be great if you could give it a try.

**Comment by stiemannkj1** [comment]
@tandraschko, Thanks! This works correctly, but there is still a weird issue (reproducible in webapps) where CSS files are not loaded. Using my example **`.xhtml`** files, you should be able to reproduce this.

**Comment by tandraschko** [comment]
Sorry to needle you instead trying the example :P (I currently @work, so i can't now)
I guess it will work fine when you use action="view2.xhtml?faces-redirect=true"?

The problem is that we can't execute our dynamic loading on the client when primefaces.js is NOT available on the view.
We also can't fix it that easily.
I guess it will also not load the styles/script with 5.3.

Workaround would be to include ANY primefaces component on index.xhtml or include primefaces.js.

**Comment by stiemannkj1** [comment]
> Sorry to needle you instead trying the example :P (I currently @work, so i can't now)
> I guess it will work fine when you use action="view2.xhtml?faces-redirect=true"?

Yep, `faces-redirect=true` works fine, but that isn't really related to this bug. That's another good workaround though.

> The problem is that we can't execute our dynamic loading on the client when primefaces.js is NOT available on the view.
> We also can't fix it that easily.
> I guess it will also not load the styles/script with 5.3.

I just tested this, and you are correct. Although it seems like the necessary CSS should be added to the `<head>` section (in the partial response), and everything should work. I'm not sure why it doesn't. It seems like **`theme.css`** is loaded, but I'm not sure why some of the other CSS isn't loaded.

> Workaround would be to include ANY primefaces component on index.xhtml or include primefaces.js.

Makes sense. As I said above, the workaround is so simple (and actually it is preferred to use PrimeFaces components in place of `h:` components if possible) that this really is a minor issue.

---

### `p:selectOneMenu`

I do have one more concern: when I add `<p:selectOneMenu>` to **`view2.xhtml`**, some JavaScript errors occur in the console. This is still an improvement over the previous behaviors because the Ajax navigation occurs correctly, but there are still JavaScript and CSS problems with navigating from a non-Primefaces view to a view with Primefaces components.

Updated **`view2.xhtml`**:

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <p:calendar showOn="button" />
            <p:commandButton value="index" action="index.xhtml" />
            <p:selectOneMenu>
                <f:selectItem itemLabel="qwer" itemValue="qwer" />
                <f:selectItem itemLabel="asdf" itemValue="asdf" />
            </p:selectOneMenu>
        </h:form>
    </h:body>

</html>
```

JavaScript errors:

```
undefined entity
ReferenceError: $ is not defined
ReferenceError: PrimeFaces is not defined
ReferenceError: $ is not defined
```

**Comment by stiemannkj1** [comment]
@tandraschko, do you think the new issues that I mentioned above should be considered to be a different bug (that happens to have the same workaround)?

**Comment by tandraschko** [comment]
Will check it again :)

**Comment by tandraschko** [comment]
It's a actually a bug or not implemented feature how mojarra handles the `<update id="javax.faces.ViewRoot">`
It works fine with myfaces.
Also its not reloaded to the dynamic resource loading as it isn't active in this case.

**Comment by stiemannkj1** [comment]
@tandraschko, got it. I will create a Mojarra issue for the CSS stuff not getting loaded. However, [what about the failures when `p:selectOneMenu` is included](https://github.com/primefaces/primefaces/issues/1769#issuecomment-255126215)? Are they related to this issue, or is it another bug?

**Comment by stiemannkj1** [comment]
@tandraschko, I created [JAVASERVERFACES-4195](https://java.net/jira/browse/JAVASERVERFACES-4195) to track the CSS issue we discovered with ajax navigation.

**Comment by tandraschko** [comment]
cool!
do you mean if p:selectOneMenu is included in the first page?
I guess this won't change anything as f:ajax is used and therefore the mojarra ajax client.

**Comment by stiemannkj1** [comment]
> do you mean if p:selectOneMenu is included in the first page?

No, I mean that if you put `p:selectOneMenu` on **`view2.xhtml`**, you will see errors when you navigate via ajax to **`view2.xhtml`**.

So basically, the problem I'm talking about has the same steps to reproduce and example code as [the original problem](https://github.com/primefaces/primefaces/issues/1769#issue-177881783) **except** **`view2.xhtml`**:

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <p:calendar showOn="button" />
            <p:commandButton value="index" action="index.xhtml" />
            <p:selectOneMenu>
                <f:selectItem itemLabel="qwer" itemValue="qwer" />
                <f:selectItem itemLabel="asdf" itemValue="asdf" />
            </p:selectOneMenu>
        </h:form>
    </h:body>

</html>
```

**Comment by tandraschko** [comment]
Yep, then it should be the same bug.

**Comment by stiemannkj1** [comment]
Okay, can you reopen this issue then?

**Comment by tandraschko** [comment]
I mean that it should be the same mojarra bug :)

**Comment by stiemannkj1** [comment]
@tandraschko, I just checked, and the `p:selectOneMenu` JavaScript errors occur in both myfaces and mojarra, so this is a bug in primefaces. Do you want me to open another issue, or do you want to reopen this one?

**Comment by tandraschko** [comment]
Would be great if you would create a new one with the 2 small sample xhtmls :)

**Comment by stiemannkj1** [comment]
Created new issue here: https://github.com/primefaces/primefaces/issues/1876
