### ISSUE TITLE
p:megaMenu - attribute autoDisplay="false" disables link-functionality

### ISSUE THREAD

**Issue by JanRR** [primefaces/primefaces#1770]
## 1) Environment
- PrimeFaces version: 6.0.1
- Application server + version: JBoss Wildfly 8.1
- Affected browsers: FF, Chrome.. etc
## 2) Expected behavior

MenuItem should link to the given "url"
## 3) Actual behavior

MenuItem doesnt link to the given "url"
..
## 4) Steps to reproduce

See the xhtml - that is all you need. The attribute autoDisplay="false" disables the link-functionality for menuitems which are direct children of the p:megaMenu. If you set autoDisplay="true" everything works as expected.
## 5) Sample XHTML

```
    <p:megaMenu autoDisplay="false">
         <p:menuitem value="Quit" url="http://www.primefaces.org" icon="ui-icon-close" />
    </p:megaMenu>
```

..
## 6) Sample bean

not necessary

**Comment by syboulenge** [comment]
Experiencing the same issue on PF 5.3.

Any workaround ?

**Comment by JanRR** [comment]
We use no workaround - currently we set autoDisplay="true".

**Comment by JanRR** [comment]
Well done! THX!
