### ISSUE TITLE
MenuButton Menu Is Not Keyboard Accessible

### ISSUE THREAD

**Issue by outlinedspider** [primefaces/primefaces#1786]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version: 6.0.4
- Does it work on the newest PrimeFaces version? No
- Application server + version: Glassfish 4.1.1
- Affected browsers: Firefox 48.0
## 2) Expected behavior

keyboarding to the button and clicking either spacebar or enter should open the menu.  Once the menu is open the item list should be accessible by keyboard either by using tab or the up/down arrow keys.
## 3) Actual behavior

The button highlights but will not open the menu.  Items on the menu are hidden and inaccessible by keyboard
## 4) Steps to reproduce

On the primefaces showroom, tab to the button.  Try clicking the spacebar or enter.  Nothing happens.
## 5) Sample XHTML

http://www.primefaces.org/showcase/ui/menu/menuButton.xhtml
## 6) Sample bean

http://www.primefaces.org/showcase/ui/menu/menuButton.xhtml

**Comment by outlinedspider** [comment]
I thought it was menubutton that we were using.  It's not, it's the overlay menu (http://www.primefaces.org/showcase/ui/menu/menu.xhtml) except somehow our developers have used a p:commandLink to open the menu instead of a p:commandButton.  Could you please take a look?  I posted the xhtml code below:

```
                   <p:commandButton id="newButton" type="image"
        alt="New Entry"
        title="Select from the list of entry types to create a new entry" 
        styleClass="blueImg newImg" />

                   <p:menu overlay="true" trigger="newButton" my="left top"
        at="left bottom" model="#{headerSearchController.newOptionsModel}" />
```

**Comment by mertsincan** [comment]
Thanks for the example. But, the keyboard issue of menubutton is fixed. Can you please create a new github issue for overlay menu?
