### ISSUE TITLE
CheckboxMenu Not Keyboard Accessible When Trying To Close or Exit the List

### ISSUE THREAD

**Issue by outlinedspider** [primefaces/primefaces#1787]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version:  6.0.4
- Does it work on the newest PrimeFaces version? No
- Application server + version:  Glassfish 4.1.1
- Affected browsers:  Firefox 48.0
## 2) Expected behavior

Esc will close a menu list.
## 3) Actual behavior

Esc has no effect on the menu list.
## 4) Steps to reproduce

tab to checkboxMenu and press spacebar.  Tab through the list and select an item. Press esc the menu list will not close.
## 5) Sample XHTML

Available on primeface showroom http://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml
## 6) Sample bean

Available on primeface showroom http://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml

**Comment by outlinedspider** [comment]
I can now access the checkboxMenu when using a keyboard to open the item list and un/select items in the list.  However, esc does not close the menu and so i must tab through each option until I reach the end of the list to move to the next input.  Can you make the item list close when the esc key is pressed?

Thank you!!!! :)

**Comment by mertsincan** [comment]
I think this issue is fixed. When you press esc key in the panel of checkbox menu, panel is closed every time.

**Comment by outlinedspider** [comment]
It won't close for me. Do you need to see our code?

Anna

On Oct 6, 2016, at 1:32 AM, mertsincan <notifications@github.com<mailto:notifications@github.com>> wrote:

I think this issue is fixed. When you press esc key in the panel of checkbox menu, panel is closed every time.

##

**Comment by mertsincan** [comment]
This issue is fixed for PF V6.0.6 and V6.1.  V6.0.6 will be release next week.

**Comment by outlinedspider** [comment]
Hmmmmm, unless there's another fix, pressing esc still doesn't work for us.  We've added the suggested fixes from github and closing the menu list isn't keyboard accessible.  If you need, I can send our xhtml and java files.

Thanks!!

Anna

Sent from Outlookhttp://aka.ms/weboutlook
