### ISSUE TITLE
Add a class attribute with value "pe-inputNumber" or similar to the component p:inputNumber like pe:inputNumber was

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1789]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version?
- Application server + version: All
- Affected browsers: All
## 2) Expected behavior

With "pe:inputNumber" i can difference input for numbers with the class value "pe-inputNumber" and i can manipulate easily with css selector, now the input generated by "p:inputNumber" i cannot differentiate with input generated by "p:inputText"
## 3) Actual behavior

The class value for input generate with p:inputNumber and p:inputText are similar, and I cannot diferentiate.

input by p:inputNumber
![image](https://cloud.githubusercontent.com/assets/8562436/18737328/8243228c-8055-11e6-9841-a5c17f862f12.png)

input by p:inputText
![image](https://cloud.githubusercontent.com/assets/8562436/18737341/a15470a4-8055-11e6-8db1-02a2892c3942.png)
## 4) Steps to reproduce

.. 
## 5) Sample XHTML

..
## 6) Sample bean

..

**Comment by tandraschko** [comment]
the outer span has a ui-inputnumber class ;)

**Comment by JaviRpo** [comment]
thanks, you are right
