### ISSUE TITLE
DataTable: Support for overriding paginator events

### ISSUE THREAD

**Issue by lcanalesmayo** [primefaces/primefaces#1793]
Hi,

Could you add support for overriding "onclick" pagination events in p:datatable component?

At this moment, they aren't customizable:

//First page link
        this.firstLink.click(function() {
            PrimeFaces.clearSelection();

```
        if(!$(this).hasClass("ui-state-disabled")){
            $this.setPage(0);
        }
    });

    //Prev page link
    this.prevLink.click(function() {
        PrimeFaces.clearSelection();

        if(!$(this).hasClass("ui-state-disabled")){
            $this.setPage($this.cfg.page - 1);
        }
    });

    //Next page link
    this.nextLink.click(function() {
        PrimeFaces.clearSelection();

        if(!$(this).hasClass("ui-state-disabled")){
            $this.setPage($this.cfg.page + 1);
        }
    });

    //Last page link
    this.endLink.click(function() {
        PrimeFaces.clearSelection();

        if(!$(this).hasClass("ui-state-disabled")){
            $this.setPage($this.cfg.pageCount - 1);
        }
    });
```

Thanks in advance.

**Comment by kukel** [comment]
why do you need overriding? What is the problem you have or what do you want to achieve?

**Comment by lcanalesmayo** [comment]
I need to override pagination events in order to go forward/backward X pages in one click, where X is obtained from an internal business logic method.

**Comment by paulspinelli** [comment]
I too would like this feature.

**Comment by melloware** [comment]
I am going to close this ticket as you can already do this.  For example to override the "onclick" method of the paginator firstLink for example....

```javascript
PF('myDataTableWidget').paginator.firstLink.off().click(function(e) {
            alert('First Link clicked!');
            e.preventDefault();
});
```

That will override firstLink click and display and Alert instead of performing the default code.
