### ISSUE TITLE
Font Awesome support in Ultima Layout

### ISSUE THREAD

**Issue by nooone** [primefaces/primefaces#1794]
## 1) Environment
- PrimeFaces version: 6.0
- **Premium Layout: Ultima 1.0.4**
- Does it work on the newest PrimeFaces version? No
- Application server + version: WildFly 10.1.0.Final
- Affected browsers: All browsers
## 2) Expected behavior

I expect that it's possible to use Font Awesome icons in a premium layout (Ultima), just like with other standard themes as well.
## 3) Actual behavior

It does not work because material icons are assumed everywhere.
## 4) Steps to reproduce

Try to use Font Awesome icons on `<p:commandButton>`, or especially `<p:menuItem>` or `<p:submenu>` within a **`<pu:menu>`**.
## 5) Sample XHTML

```
<pu:menu>
    <p:menuitem value="Dashboard" icon="fa fa-dashboard" />
    <p:submenu label="Settings" icon="fa fa-cogs">
        <p:menuitem value="Users" icon="fa fa-users" />
    </p:submenu>
</pu:menu>

<p:commandButton value="Login" icon="fa fa-sign-in" />
```
## 6) Sample bean

No beans involved.
## 7) Additional

Using the following CSS rule, I was able to easily work around the problem of using Font Awesome icons on buttons:

```
.fa {
    font-family: "FontAwesome" !important;
}
```

However, I could not find a workaround to use the FA icons in `<pu:menu>`. If there's an easy workaround like this for `<pu:menu>`, I'd close this issue.

**Comment by cagataycivici** [comment]
This is tracked at;

https://github.com/primefaces/layouts/issues/120

**Comment by nooone** [comment]
Quick update: I found a workaround that works for me. I replaced the default renderer with my own...

``` java
public class FontAwesomeUltimaMenuRenderer extends UltimaMenuRenderer {

    @Override
    protected void encodeItemIcon(FacesContext context, String icon) throws IOException {
        if (icon != null) {
            ResponseWriter writer = context.getResponseWriter();

            writer.startElement("i", null);
            writer.writeAttribute("class", icon, null);
            writer.endElement("i");
        }
    }
}
```

And registered it in my `faces-config.xml`:

```
<render-kit>
    <renderer>
        <component-family>org.primefaces.component</component-family>
        <renderer-type>org.primefaces.component.UltimaMenuRenderer</renderer-type>
        <renderer-class>org.primefaces.ultima.component.menu.FontAwesomeUltimaMenuRenderer</renderer-class>
    </renderer>
</render-kit>
```
