### ISSUE TITLE
Error in streaming dynamic resource

### ISSUE THREAD

**Issue by snagel86** [primefaces/primefaces#1806]
## 1) Environment
- PrimeFaces version: 6.0  
- Was working in 5.3
- Application server + version: WildFly 8.2 Final  
- Affected browsers: Chrome Version 53, IE 11  
## 2) Expected behavior

I like to play an audio mp3 which is loaded as byte [] from database.

`<p:media value="#{audioController.stream}" width="250" height="80"
        player="quicktime">
    <f:param name="autoPlay" value="false" />
 </p:media>`

`import java.io.ByteArrayInputStream;
import java.io.IOException;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import de.almost.magic.services.AudioServiceBean;

@ManagedBean (eager = true)
@SessionScoped
public class AudioController
{
    @EJB
    private AudioServiceBean service;

```
private StreamedContent media;

public AudioController ()
{

}

public StreamedContent getStream () throws IOException
{
    FacesContext context = FacesContext.getCurrentInstance ();
    if (context.getCurrentPhaseId () == PhaseId.RENDER_RESPONSE)
    {
        // So, we're rendering the view. Return a stub StreamedContent so
        // that it will generate right URL.
        return new DefaultStreamedContent ();
    }
    else
    {
        // So, browser is requesting the image. Return a real
        // StreamedContent with the image bytes.
        String id = context.getExternalContext ().getRequestParameterMap ().get ("id");
        return new DefaultStreamedContent (
                new ByteArrayInputStream (service.findAudio (Long.valueOf (id)).getValue ()), "audio/mp3");
    }
}
```

}
`
## 3) Actual behavior

The audio is not playing. It's crashed with message "Error in streaming dynamic resource" which is given by org.primefaces.application.resource.StreamedContentHandler 
## 4) Steps to reproduce

I was debugging in version 5.3, everything fine there (I saw comment // see #6448 too). But in primefaces version 6.0 it's crashing in 

`externalContext.getResponseOutputStream().write(buffer, 0, length);` from the StreamedContentHandler.

**Comment by kukel** [comment]
search stackoverflow also mentioned there

**Comment by snagel86** [comment]
nothing found, sorry.

**Comment by tandraschko** [comment]
I can't run your sample as i don't have the AudioServiceBean.
I think your stream is null or empty.
Debug please or reopen if you can provide a sample which i can run.

**Comment by snagel86** [comment]
I run this in a wildfly 8.2 connected with a derby database. I used that to save a mp3 file as byte [] in database. I already debugged. It is not empty or null. And as mentioned, it's running with primefaces verion 5.3, but not in 6.0. I just like to use some features from 6.0 

package de.almost.magic.services;

import java.io.Serializable;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.persistence.EntityManager;

import de.almost.magic.model.Audio;

@Stateless
@LocalBean
public class AudioServiceBean implements Serializable
{
    private static final long serialVersionUID = 6654495898506393427L;
    @Inject
    private EntityManager entityManager;

```
public Audio findAudio (Long id)
{
    return entityManager.find (Audio.class, id);
}
```

}
`

`package de.almost.magic.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.validation.constraints.NotNull;

@Entity
public class Audio implements Serializable
{
    private static final long serialVersionUID = -4844348574002687613L;

```
@Id
@GeneratedValue (strategy = GenerationType.IDENTITY)
private Long id;

private String name;

@NotNull
@Lob
private byte [] value;

public Audio ()
{

}

public Audio (String name, byte [] content)
{
    this.name = name;
    this.value = content;
}

public Long getId ()
{
    return id;
}

public void setId (Long id)
{
    this.id = id;
}

public byte [] getValue ()
{
    return value;
}

public void setValue (byte [] value)
{
    this.value = value;
}

public String getName ()
{
    return name;
}

public void setName (String name)
{
    this.name = name;
}
```

}
`

**Comment by tandraschko** [comment]
We can do it 2 ways:
- you provide a complete sample app (your code above contains entitymanagers etc. - i would need 1 hour to get a working example)
- debug and check which exceptions on which line occurs

otherwise i can't help you.

**Comment by snagel86** [comment]
class: org.primefaces.application.resource.StreamedContentHandler

while ((length = (inputStream.read(buffer))) >= 0) {
line 97 --->                externalContext.getResponseOutputStream().write(buffer, 0, length);
                    }

catch(Exception e) {
                logger.log(Level.SEVERE, "Error in streaming dynamic resource. {0}", new Object[]{e.getMessage()});
                throw new IOException(e);
            }

The exact message of the catched exception is
"java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen"

But because in primefaces version 5.3 it is working fine (no changes in my code), I can not see a reason why that established connection is closed by remote host. I am working on localhost. No firewall or something could be the problem.

Thank you for helping!

**Comment by snagel86** [comment]
I saw, that there is a re-implementaion in session handling between primefaces 5.3 and primefaces 6.0 in this class. There must be something wrong

**Comment by tandraschko** [comment]
Works actually fine.
We only changed one thing:
Pre 6.0:
the EL-ExpressionString is encryped and passed via the URL
6.0:
the EL-Expression string is stored into the session and a UUID is passed to the URL

Would be great if you could analyze it.

**Comment by marklcg** [comment]
I ran into this issue myself with PDF files.  Looking at the code, they added the token to 6.0 as @tandraschko  explained.  I suspect as a security enhancement?  Anyhow, the problem is when the resource is requested a second time because the key is removed the first time it is used.  Adobe plugin in IE results in a second request as does Chrome when you click download to download the PDF.  I suspect the media player may be doing the same thing in your case.  My fix was to enable caching on the p:media component: cache="true".  In this case, your browser will pull from it's cache.

**Comment by tandraschko** [comment]
Ohh, so IE doesn't reload the page but it does reload the images? Hmm, that could be really a problem in some cases.
cache=true isn't perfect for all cases.

**Comment by tandraschko** [comment]
And yes, it's a security enhancement.

**Comment by marklcg** [comment]
Yeah, I think it's the plug-in's causing the second request in the case of Adobe on IE or the video player the OP's case.  A simple case to demonstrate the issue is to use Chrome and stream a PDF.  It will render right, but if you click the download option in Chrome to save the PDF off, you'll see that the PDF is an empty file because the request was not filled.  I agree, cache=true is a workaround.

**Comment by tandraschko** [comment]
Please create a new issue for it. The discussion is unrelated to the original issue.

**Comment by marklcg** [comment]
Sure, I can do that, although the OP may find its the root of his issue.

**Comment by marklcg** [comment]
Issue #1858 created with example to reproduce.
