### ISSUE TITLE
Schedule: displays wrong endDate

### ISSUE THREAD

**Issue by tczu** [primefaces/primefaces#1807]
1) Environment
PrimeFaces version: 6.0 
Application server + version: Wildfly 10.0.10.Final 

2) Expected behavior
Schedule component that contain event (with some date range – StartDate differ from end EndDate) should display specified date range.

3) Actual behavior
When event dates (that are coming from database) are in YYYY/MM/DD format e.g: startDate: 2016-10-05, endDate 2016-10-10 than schedule show event that last one day less ( startDate: 2016-10-05, endDate 2016-10-09)

4) Steps to reproduce
Create an event that last more than one day and display on schedule.

5) Sample XHTML
<p:schedule id=”Schedule" value="#{model.eventModel}" widgetVar="taskSchedule"
            showHeader="true" showWeekends="true" view="month" locale="tr" timeFormat="HH:mm"
            draggable="false" axisFormat="HH:mm" slotMinutes="30" firstHour="10"
            defaultEventMinutes="120" timeZone="GMT+2" resizable="false" displayEventEnd="true">
    <p:ajax event="eventSelect" listener="#{eModel.onEventSelect}" update="taskDialog"
            oncomplete="PF('taskDialog').show();" />
/p:schedule

I really appreciate any help you can provide.

**Comment by tandraschko** [comment]
sample bean missing - will close it for now as invalid.
If the problem still persists, please create new issue with a fully runnable sample bean+xhtml.
