### ISSUE TITLE
Datatable reflow rendering/css issue

### ISSUE THREAD

**Issue by mbeedub** [primefaces/primefaces#181]
When datatable has reflow set it loses outer borders on viewport resize. This can be seen on the current showcase.

See http://forum.primefaces.org/viewtopic.php?f=3&t=41926&p=131963#p131963

**Comment by mertsincan** [comment]
Please try;

```
<style type="text/css">
   .ui-datatable-reflow .ui-datatable-tablewrapper table{
       border: 1px solid #a8a8a8;
   }
</style>
```

**Comment by cagataycivici** [comment]
I think we should fix it on our side as well.

**Comment by cagataycivici** [comment]
We can't use #a8a8a8 by the way as it is theme specific.

**Comment by mbeedub** [comment]
Thanks Cagatay - agreed.  The above CSS is an OK workaround for now but a fix in the product at some point would be good.

**Comment by mbeedub** [comment]
Thank you
