### ISSUE TITLE
Add options attribute to customize the exported PDF/Excel file on DataExporter

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1810]
Options;
- String facetFontStyle;
- String facetFontColor;
- String facetBgColor;
- String facetFontSize;
- String cellFontStyle;
- String cellFontColor;
- String cellFontSize;

Example;

```
bean.java

private ExcelOptions exOpt; /* getter; setter; */
private PDFOptions pdfOpt; /* getter; setter; */

@PostConstruct
public void init() {
        cars = service.createCars(100);
        exOpt = new ExcelOptions();
        exOpt.setFacetFontStyle("BOLD");
        pdfOpt = new PDFOptions();
        pdfOpt.setCellFontSize("20");
}

Xhtml

<p:dataExporter type="xls" target="tbl" fileName="cars" options="#{dataExporterView.exOpt}" />
...
<p:dataExporter type="pdf" target="tbl" fileName="cars" options="#{dataExporterView.pdfOpt}"/>
```

**Comment by andrei-ivanov** [comment]
I think the new `options` parameter is not used in `org.primefaces.component.export.ExcelExporter.export(FacesContext context, List<String> clientIds, String filename, boolean pageOnly, boolean selectionOnly, String encodingType, MethodExpression preProcessor, MethodExpression postProcessor, ExporterOptions options)`

**Comment by andrei-ivanov** [comment]
@mertsincan thoughts?
