### ISSUE TITLE
filtering datatable before render does not work

### ISSUE THREAD

**Issue by antidote2** [primefaces/primefaces#1812]
## 1) Environment
- PrimeFaces version: 5.3
- Does it work on the newest PrimeFaces version? no
- Application server + version: wildfly 8.1
- Affected browsers: any
## 2) Expected behavior

datatable filtered according to filteredValue property when first rendered
## 3) Actual behavior

datatable is not filtered (content of value property is displayed), but for example after sorting a column - datatable appears filtered
## 4) Steps to reproduce

create datatable with value = list of 5 items
call setFilteredValue with 4 of those items right in the value getter, so any getFilteredValue should return those 4 items.

**Comment by tandraschko** [comment]
No example -> invalid
Feel free to reopen if you have a sample
