### ISSUE TITLE
Tab navigation is lost after choosing a date 

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#1814]
## 1) Steps to reproduce

http://www.primefaces.org/showcase/ui/input/calendar.xhtml
1. use tab to navigate 
2. select a date using mouse click
3. tab navigation is lost and does not focus to next ui control
## 2) Environment
- PrimeFaces version: 6.0.4 on Mojarra-2.2.8.
- Does it work on the newest PrimeFaces version? Ni
- Application server + version: Tomcat 8.0.32
- Affected browsers: Chrome, Firefox

**Comment by mertsincan** [comment]
Can you please try this issue with jquery datepicker API?
Exp; https://jqueryui.com/datepicker/#date-formats

**Comment by arunvc** [comment]
yes it doesn't work either, so its a datepicker issue
In chrome it doesn't work, 

In firefox on date select focus is back to the date field and on next tab focus to next UI, which is some what acceptable behaviour.
https://jqueryui.com/datepicker/#alt-field

But  in firefox primefaces date control doesn't work the same way as in https://jqueryui.com/datepicker/#alt-field
