### ISSUE TITLE
Schedule: Update to new version of Fullcalendar (3.9.0)

### ISSUE THREAD

**Issue by luizphilipi** [primefaces/primefaces#1817]
In version [3.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.0) Fullcalendar has a new feature, List View. This will improve user experience a lot.

**Comment by erickdeoliveiraleal** [comment]
I think it will not be updated for now because FullCalendar uses jQuery 2 and PF uses 1.9, also FullCalendar 3 does not support IE 8, which is a requirement for now in PF.

**Comment by erickdeoliveiraleal** [comment]
https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.0

**Comment by tandraschko** [comment]
exactly! we can plan for the future.

**Comment by luizphilipi** [comment]
Ok, thanks for the quick response.

**Comment by luizphilipi** [comment]
Hi @tandraschko, now with jquery upgrade this issue turns viable, right?
FullCalendar needs jquery v2.0.0+, i just made some changes to schedule.js and everythings works right, now we use list view in our project.

**Comment by tandraschko** [comment]
Yep! If you would provide a PR, i can review and test it.

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primefaces/issues/2626

**Comment by mbeedub** [comment]
+1 for this

It would be a fantastic addition to PF and would pave the way potentially for the use of FullCalendar scheduler (even though that's a premium add-on)

**Comment by andreichiritescu** [comment]
any idea when this feature will be added?

**Comment by tandraschko** [comment]
Without milestone means no plan. But you can sponsor it or implement by yourself and provide a pull request.

**Comment by OBreidenbach** [comment]
PR https://github.com/primefaces/primefaces/pull/3739

**Comment by OBreidenbach** [comment]
I did add a new attribute for slotLabelFormat and deprecated the axisFormat attribute, because there were already some other deprecated attributes (for Instance: ignoreTimezone).
In my humble opinion all this deprecated attributes should be removed. They refer to FullCalendar attributes already removed. It is confusing if you look at the primefaces and the FullCalendar documentation.

**Comment by tandraschko** [comment]
@OBreidenbach 
Just for you info:
- I also created a issue for removing the depracted attributes after the next versio (6.4 or 7.0)
- I also created a issue for the documentation
- I also adjusted the migration guide

It's always more the like code changes.

**Comment by OBreidenbach** [comment]
@tandraschko 
Thank you for the info.
