### ISSUE TITLE
PanelGrid: support new grid classes (ui-g)

### ISSUE THREAD

**Issue by ModestinoAndre** [primefaces/primefaces#1820]
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version?  NO
- Application server + version: TomEE 7.0 Plus
- Affected browsers: ALL
  2) Expected behavior: Responsive Layout

p:panelGrid does not work with the new Grid CSS classes (ui-g-*), it only works with the old Grid CSS (ui-grid-col-*).

`E.g.:`

```
<p:panelGrid columns="4" styleClass="ui-g" columnClasses="ui-g-12 ui-md-1 ui-lg-1,
ui-g-12 ui-md-11 ui-lg-5,
ui-g-12 ui-md-1 ui-lg-1,
ui-g-12 ui-md-11 ui-lg-5" 
layout="grid" styleClass="ui-panelgrid-blank">

<p:outputLabel for="input" value="Input"/>
<p:inputText id="input"/>

<p:outputLabel for="area" value="Textarea"/>
<p:inputTextarea id="area"/>
</p:panelGrid>

```

**Comment by nalmeida84** [comment]
I'm facing some visual troubles due to this lack of feature too. :+1:

**Comment by melloware** [comment]
This was fixed in https://github.com/primefaces/primefaces/issues/2677
