### ISSUE TITLE
Combining operation between p:hotkey and p:commandButton - p:commandLink

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1821]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? new feature
- Application server + version: ALL
- Affected browsers: ALL
## 2) Expected behavior

I generally use a **p:commandButton**/**p:commandLink** and add an additional component **p:hotkey** to do the same action of the **p:commandButton**/**p:commandLink**, but this requires repeat functionality between these 2.

It would be very good if there were an attribute in the **p:hotkey** to associate the **p:commandButton**/**p:commandLink** and this run the **p:commandButton**/**p:commandLink** functionality or that there was also an attribute of the **p:commandButton**/**p:commandLink** hotkey for this function
## 3) Actual behavior

We need to add two components
## 4) Steps to reproduce

..
## 5) Sample XHTML

```
<p:commandButton actionListener="#{bean.create}" value="Create" process=" .. process components .." update=" .. update components .." oncomplete=" .. other actions .."  />
<p:hotkey bind="alt+n" actionListener="#{bean.create}" process=" .. process components .." update=" .. update components .." oncomplete=" .. other actions .." />
```
## 6) Sample bean

..

**Comment by tandraschko** [comment]
I think you can easily do it via 2 ways:

1) execute the button via JS from the hotkey
2) create a remoteCommand and call it from both commandButton and hotKey

Also your way would be a little bit nicer, i think we can close it for.
