### ISSUE TITLE
Dialog: Introduce new event to catch the dynamic contentLoad via p:ajax

### ISSUE THREAD

**Issue by ludekz** [primefaces/primefaces#1822]
Dynamic p:dialog (with dynamic="true") updates autoUpdate component. Some other components have attribute ignoreAutoUpdate, that prevents ajax request from updating autoUpdate,  It will be handy if p:dialog also has ignoreAutoUpdate attribute.

**Comment by ludekz** [comment]
Hello, I'm not sure that the new title addresses what I meant.  

I have global messages:
`<p:messages id="globalMessages" showDetail="true" autoUpdate="true" closable="true"  />`
and then dialog:
`<p:dialog id="helpdeskDlg" modal="true" resizable="false" fitViewport="true" dynamic="true" closeOnEscape="true" onHide="dialogClose()">...`

If there is a message shown and user open the dialog, the message disappears.

**Comment by tandraschko** [comment]
You would like to have a new attribute ignoreAutoUpdate.
We don't add such attributes directly on the component in normal case as it's possible via p:ajax.
So you can probably use something like this in the future:
`<p:dialog>
   <p:ajax event="loadContent" ignoreAutoUpdate="true" />
</p:dialog>`

**Comment by martin654** [comment]
There are 7 tickets including this one in OPEN state in PF 6.1 RC1 including this one. Will they be included in RC3?

**Comment by tandraschko** [comment]
Currently i don't have time, sorry.

**Comment by tandraschko** [comment]
But you can provide a PR for this feature, so i will merge it directly after the 6.1 release.
