### ISSUE TITLE
New TextEditor Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#1823]
Deprecate p:editor in favor of p:textEditor based on Quill

**Comment by tandraschko** [comment]
You know that quill is only compatible with IE11 and does not work with our license (AFAICS)?

**Comment by cagataycivici** [comment]
Quill works for me on chrome and ff as well, also license is bsd which is compatible with Apache.

**Comment by tandraschko** [comment]
Yeah thats true but does that mean, that we slightly drop older IE versions?
Oh, great that the license works!

**Comment by cagataycivici** [comment]
No but for editor we can make an exception I guess.

**Comment by tandraschko** [comment]
ok :)
Can i close all the editor ticket and comment that it's deprecated?

**Comment by tony-in-nz** [comment]
Just wondering about the doco.
The link from the showcase goes to editor and PDF does not have this listed.
Is there a place to download the 6.0.6 doco?

**Comment by ErickPezoa** [comment]
I am planning on paying the $99.00 for the PF Elite just for this feature but before I do, I have a question about the new textEditor. Let's say I write a paper on the editor and I add a lot of formatting (bullets, bold, headers, italics, etc.) and I submit the text to save it on the database. **When I come back to see the paper on the UI, will the textEditor remember all of the formatting?** _If not, is there a way to do that?_ This is important for what I am trying to do.
