### ISSUE TITLE
Security issue on ResourceHandler

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1826]

**Comment by cnsgithub** [comment]
Good to hear that this issue has been fixed. 

Just implemented two-factor authentication using QR code to share secret key. Attackers could have stolen all shared secrets by just repeatedly calling this URL remaining unchanged: 

http://<domain>/<path>/javax.faces.resource/dynamiccontent.properties.xhtml?ln=primefaces&v=6.0.5&pfdrid=<unchangedEncryrptedKey>&pfdrt=qr&gen=qr&fmt=svg&pfdrid_c=true&ori=0)

Puuhh...
