### ISSUE TITLE
Primefaces extension ckeditor throws error when clicking an ajax=false button after the editor was updated

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#1830]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
  ## 1) Environment
- PrimeFaces version: Primefaces 6.0.5
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat v8.0
- Affected browsers: Chrome v53.0.2785.143 (64-bit)
  ## 2) Expected behavior

No error should be shown
## 3) Actual behavior

An error was thrown
## 4) Steps to reproduce

**Pre: Make sure to open a browser console to observe the error**

Step 1: Click the **updateContent** button on the top left 
## Step 2: Click the **download** button at the bottom. (Please take a look at the console carefully, an error will be shown in this step)

During my debugging,

The error is :

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316115/d80c2b9e-9065-11e6-97a6-62636615fe1b.png)

Step 1: Click the updateContent. insertAfter will be called the first time

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316219/3b76fed4-9066-11e6-93cc-19d513ba83e4.png)

In Step 2: Click the download button.  The insertAfter function will be called the second time. The `a.$.nextSibling` is null

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316309/96467858-9066-11e6-944c-492e77a02672.png)
## 5) Sample XHTML

``` html
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions"
    xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:head>

    </h:head>

    <h:body>
        <h:form>
            <p:commandButton process="@this" update="editor" value="updateContent"></p:commandButton>
            <pe:ckEditor id="editor"></pe:ckEditor>

            <p:commandButton ajax="false" value="download">
                <!-- <p:fileDownload value=""></p:fileDownload> -->
            </p:commandButton>
        </h:form>

    </h:body>

</ui:composition>
```

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316406/e8a10f46-9066-11e6-87bf-d2a833e7dfeb.png)
## 6) Sample bean

N/A

**Comment by tandraschko** [comment]
Please use the PrimeFaces Extensions github.
Also note: PrimeFaces Extensions is a community based project, so please provide a PR to fix it, too.

**Comment by jxmai** [comment]
Thanks for the fast response. This issue has been redirected to https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/412. 

This issue was causing by a null pointer, but I have not figured out the cause of it. Will provide a PR if I figure it out :)
