### ISSUE TITLE
p:textEditor not compatible with ajax update and file download

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#1832]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version: Primefaces v6.0.6
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat v8.0
- Affected browsers: Chrome v 53.0.2785.143 (64-bit)
## 2) Expected behavior

upgrade from deprecated editor to quill editor should be smooth. 
## 3) Actual behavior

Issue 1: Ajax update populate some text out of the quill editor
Issue 2: download does not really work
## 4) Steps to reproduce

Step 1: Click updateContent button on the top left, you can see some text out of the text editor

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19326552/9c30ce42-9090-11e6-85f8-dbce59e39857.png)

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19326535/90159f0c-9090-11e6-9ea3-2f5d4e40defe.png)

Step 2: Click download Button at the bottom,  and **the html is empty**.
## 5) Sample XHTML

``` html
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions"
    xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:head>

    </h:head>

    <h:body>
        <h:form enctype="multipart/form-data">
            <p:commandButton process="@this" update="editor" value="updateContent" actionListener="#{test.viewData()}"></p:commandButton>
            <!-- <p:editor id="editor" value="#{test.data}"></p:editor> -->
            <p:textEditor id="editor" value="#{test.data}"></p:textEditor>

            <!-- <pe:ckEditor id="editor"/> -->


            <p:commandButton ajax="false" value="download">
                <p:fileDownload value="#{test.file}"></p:fileDownload>
            </p:commandButton>
        </h:form>

    </h:body>

</ui:composition>
```
## 6) Sample bean

``` java
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

@ViewScoped
@ManagedBean(name = "test")
public class Test implements Serializable {

    private static final long serialVersionUID = 8465294452198566201L;

    private String data;

    private transient StreamedContent file;

    public void viewData() {
        data = "<h1>Title <h1><table><tr><th>Col A</th><th>Col B</th><th>Col C</th><th>Col D</th><th>Col E</th></tr><tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td></tr></table>";
    }

    public StreamedContent getFile() {
        InputStream in = new ByteArrayInputStream(getData().getBytes());
        this.file = new DefaultStreamedContent(in, "text/html", "result.html");
        return file;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
```
## 7) Using ClEditor (The original behaviour)

Using The same java file, replace p:textEditor by p:editor

``` html
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions"
    xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:head>

    </h:head>

    <h:body>
        <h:form enctype="multipart/form-data">
            <p:commandButton process="@this" update="editor" value="updateContent" actionListener="#{test.viewData()}"></p:commandButton>
            <p:editor id="editor" value="#{test.data}"></p:editor>
            <!-- <p:textEditor id="editor" value="#{test.data}"></p:textEditor> -->

            <!-- <pe:ckEditor id="editor"/> -->


            <p:commandButton ajax="false" value="download">
                <p:fileDownload value="#{test.file}"></p:fileDownload>
            </p:commandButton>
        </h:form>

    </h:body>

</ui:composition>
```

Step 1: Update Content

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19326694/2a680f36-9091-11e6-9f59-70f21b5a3706.png)

Step 2: Download

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19326718/42c7a14a-9091-11e6-92cb-03aa4cf80989.png)

**Comment by fkjaekel** [comment]
I can confirm issue 1. I'm using Modena Theme + Layout.

**Comment by qstpss** [comment]
Yes. I noticed that toolbat of p:textEditor in dialog doesn't work after ajax update. But if we do a replace p:textEditor on p:editor everything works fine.  It seems that p:textEditor doesn't survive an update.

**Comment by tandraschko** [comment]
It would be great if anyone could provide a PR!

**Comment by fkjaekel** [comment]
Tested with 6.0.16 + default theme without problems. I guess it will work with Modena theme too.

**Comment by tandraschko** [comment]
The same example also with fileDownload?

**Comment by jxmai** [comment]
> Issue 1: Ajax update populate some text out of the quill editor







This issue seems to be fixed by #1857 via https://github.com/primefaces/primefaces/commit/674b310c74f48cad1c9b30c63057f82a26991bb9

> Issue 2: download does not really work

I tested again using Primefaces 6.0.15, and the download is working now.

---

There is a glitch in terms of the html it is generating however (This is quill editor's behaviour not primefaces's fault).

If the data is :

```html
<table><tr><th>Col A</th><th>Col B</th><th>Col C</th><th>Col D</th><th>Col E</th></tr><tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td></tr></table>
```

which essentially the same as :

```html
<table>
    <tr>
        <th>Col A</th>
        <th>Col B</th>
        <th>Col C</th>
        <th>Col D</th>
        <th>Col E</th>
    </tr>
    <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
    </tr>
</table>
```

but quill js will convert it into a `p` tag element instead of a table

![image](https://cloud.githubusercontent.com/assets/10467831/23859708/8c621692-07d2-11e7-8632-2d121256da15.png)

---

@tandraschko  Anyway, It is OK overall as far as this issue was concerned. :+1:

**Comment by tandraschko** [comment]
Great :)

**Comment by jxmai** [comment]
~~Wrong milestone :)  Should be `RC2`~~

Oh, since it was fixed before `RC1`... It is OK.
