### ISSUE TITLE
p:dialog bad renderer combined with p:blockUI

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1834]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version?
- Application server + version: All
- Affected browsers: All
## 2) Expected behavior

The p:dialog render normally combined with p:blockUI
...
## 3) Actual behavior

I want to block the p:dialog when a event of p:commandButton is present, but when i put a p:blockUI to block the p:dialog the dialog render bad.

**p:diaglog without p:blockUI**
![image](https://cloud.githubusercontent.com/assets/8562436/19414108/57c60b26-9308-11e6-8de1-28b5b33b6d7d.png)

**p:diaglog with p:blockUI**
![image](https://cloud.githubusercontent.com/assets/8562436/19414109/62decba6-9308-11e6-90a6-828c67e7cb5d.png)

..
## 4) Steps to reproduce

.. 
## 5) Sample XHTML

`<p:commandButton value="Open Dialog without p:blockUI" type="button" onclick="PF('dlgNoBlock').show()" />
  <p:dialog id="dlgNoBlock" widgetVar="dlgNoBlock" dynamic="true" header="Title" modal="true" showEffect="fade" hideEffect="fade" resizable="false"
    closeOnEscape="true">
    <p:commandButton id="btnNoBlock" value="Do Something and Not Block Dialog" />
  </p:dialog>
  <p:commandButton value="Open Dialog with p:blockUI" type="button" onclick="PF('dlgBlock').show()" />
  <p:dialog id="dlgBlock" widgetVar="dlgBlock" dynamic="true" header="Title" modal="true" showEffect="fade" hideEffect="fade" resizable="false"
    closeOnEscape="true">
    <p:commandButton id="btnBlock" value="Do Something and Block Dialog" />
    <p:blockUI block="dlgBlock" trigger="btnBlock" />
  </p:dialog>`
..
## 6) Sample bean

Not necessary
..

**Comment by tandraschko** [comment]
Not sure if it's valid. Dialog modal=true should do the same as blockUI and shoudln't be used together.

**Comment by tandraschko** [comment]
Will close it for now.

**Comment by JaviRpo** [comment]
The idea is block the p:dialog when the user do click in p:commandButton inside the p:dialog to prevent the user close it while the p:commandButton's action is process.

Can you thing about the validity of the issue?

**Comment by tandraschko** [comment]
Done. Feel free to provide a PR to fix the issue.

**Comment by mauromol** [comment]
I also found this problem and it's also documented at [StackOverflow](https://stackoverflow.com/questions/31275782/pdialog-appears-on-bottom-when-pblockui-targets-it). 
It's annoying because you can't block the whole dialog (close button included).

**Comment by vonnai** [comment]
Hi, I have similar problem. BlockUI set style css attribute position: relative to blocked component, which causes problem at dialog. The solution is to check component's position before and if there is set fixed or absolute, relative will not be set.

blockui.js (PrimeFaces 7.0.7)
change row 122
`this.block.css('position', 'relative').attr('aria-busy', this.cfg.blocked).append(this.blocker).append(this.content);`

to

`if (this.block.css("position") !== "fixed" && this.block.css("position") !== "absolute") {
     this.block.css('position', 'relative');
 }
 this.block.attr('aria-busy', this.cfg.blocked).append(this.blocker).append(this.content);`

Do you want still PR?

**Comment by melloware** [comment]
@vonnai yes please provide a PR so we can review. And I would put css into a variable like..

```javascript
var position = this.block.css("position");
if (position !== "fixed" && position  !== "absolute") { 
   this.block.css('position', 'relative'); 
} 
this.block.attr('aria-busy', this.cfg.blocked).append(this.blocker).append(this.content);
```

**Comment by vonnai** [comment]
@melloware I made PR.

**Comment by melloware** [comment]
Attached is a reproducer: 
[pf-1384.zip](https://github.com/primefaces/primefaces/files/4320336/pf-1384.zip)
