### ISSUE TITLE
Sticky: allow stacking of multiple sticky components

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1835]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version?
- Application server + version: Tomcat 8
- Affected browsers: All
## 2) Expected behavior

When i have tow or more p:sticky components these could be staked one after the other
...
## 3) Actual behavior

The second p:sticky component is placed above the first p:sticky component.
![image](https://cloud.githubusercontent.com/assets/8562436/19414294/9cfaa77e-930d-11e6-9b8e-87ab2600048d.png)

..
## 4) Steps to reproduce

.. 
## 5) Sample XHTML

`<p:outputPanel id="tb1">
    App
    <br />
    <br />
    Header
  </p:outputPanel>
  <div style="height: 800px">Any Content</div>
  <p:sticky target="tb1" />
  <p:toolbar id="tb2">
    <f:facet name="left">
      <p:commandButton type="button" value="New" icon="ui-icon-document" />
      <p:commandButton type="button" value="Open" icon="ui-icon-folder-open" />
    </f:facet>
    <f:facet name="right">
      <p:commandButton type="button" title="Save" icon="ui-icon-disk" />
      <p:commandButton type="button" title="Delete" icon="ui-icon-trash" />
      <p:commandButton type="button" title="Print" icon="ui-icon-print" />
    </f:facet>
  </p:toolbar>
  <div style="height: 800px">Any Content</div>
  <p:sticky target="tb2" />`
..
## 6) Sample bean

..

**Comment by melloware** [comment]
This can be done now with `margin="100"` option on the sticky where you can tell it where to stick.  Here is a reproducer of two stacked sticky.
[pf-1835.zip](https://github.com/primefaces/primefaces/files/9792136/pf-1835.zip)

```xml
<p:toolbar id="inner-toolbar">
                <f:facet name="left">
                    <p:commandButton value="Open Dialog" onclick="PF('testDG').show()"/>
                </f:facet>
            </p:toolbar>
            <p:sticky target="inner-toolbar"/>
			<p:toolbar id="inner-toolbar2">
                <f:facet name="left">
                    <p:commandButton value="Open Dialog" onclick="PF('testDG').show()"/>
                </f:facet>
            </p:toolbar>
            <p:sticky target="inner-toolbar2" margin="73"/>
```
