### ISSUE TITLE
Dialog: modal should block page scroll

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1836]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version?
- Application server + version: Tomcat 8
- Affected browsers: All
## 2) Expected behavior

When i open a p:dialog with modal="true" attribute the page scroll should be blocked
...
## 3) Actual behavior

Actually, when i open a p:dialog with modal="true" attribute i can scroll the page in background causing some problems with p:sticky component
..
## 4) Steps to reproduce

I have a p:sticky component:
![image](https://cloud.githubusercontent.com/assets/8562436/19421520/cd61a280-93c8-11e6-8fbf-df4470fd8e90.png)

When i open a p:dialog component this appears above the p:sticky component:
![image](https://cloud.githubusercontent.com/assets/8562436/19421531/09388abc-93c9-11e6-9db7-b23998d64269.png)

The page scroll is still active, when I scroll the page to the top the p:sticky component desappears:
![image](https://cloud.githubusercontent.com/assets/8562436/19421541/55f1dcf0-93c9-11e6-9248-fdce9cb9fc69.png)

But, if I scroll down the page, the p:sticky component appears again, this time above the p:dialog:
![image](https://cloud.githubusercontent.com/assets/8562436/19421561/b81f6938-93c9-11e6-8bd2-858a9d551509.png)

One solution for this is block the page scroll.
Other solution should be, when the p:stick component appears again, this do the p:dialog below.

.. 
## 5) Sample XHTML

`<p:toolbar id="tb2">
    <f:facet name="left">
      <p:commandButton type="button" value="Open Dialog" icon="ui-icon-document" onclick="PF('dlg').show()" />
    </f:facet>
  </p:toolbar>
  <p:sticky target="tb2" />
  <div style="height: 1000px; border: 1px solid;">Any Content</div>
  <p:dialog id="dlg" widgetVar="dlg" dynamic="true" header="Title" modal="true" showEffect="fade" hideEffect="fade" resizable="false" closeOnEscape="true">
    <div style="height: 1000px; border: 1px solid;">Some Content</div>
  </p:dialog>`
..
## 6) Sample bean

Not necessary
..

**Comment by tandraschko** [comment]
JFYI: https://github.com/primefaces/primefaces/issues/200

**Comment by tandraschko** [comment]
Possible via "blockScroll" now
