### ISSUE TITLE
p:panelGrid with layout="grid" attribute doesn't work with <p:row> and <p:column> tags

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1837]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version?
- Application server + version: Tomcat 8
- Affected browsers: All
## 2) Expected behavior

Have the same initial rendering with DIV as with TABLE. In other words, i want to have a responsive panel grid with different colspan.
...
## 3) Actual behavior

p:panelGrid without layout attribute:
![image](https://cloud.githubusercontent.com/assets/8562436/19422020/3a929562-93d3-11e6-825a-650ebf98effc.png)

p:panelGrid with layout="grid" attribute:
![image](https://cloud.githubusercontent.com/assets/8562436/19422037/8347d18c-93d3-11e6-8a47-7a218565d1e1.png)

..
## 4) Steps to reproduce

Not Necessary
.. 
## 5) Sample XHTML

`<p:panelGrid layout="grid" columns="6">
    <f:facet name="header">
        <p:row>
            <p:column colspan="6">Group 6 Columns</p:column>
        </p:row>
        <p:row>
            <p:column colspan="3">Group 3 Columns</p:column>
            <p:column colspan="2">Group 2 Columns</p:column>
            <p:column>No Group Column</p:column>
        </p:row>
    </f:facet>
    <p:row>
        <p:column>No Group Column</p:column>
        <p:column colspan="5">Group 5 Columns</p:column>
    </p:row>
    <p:row>
        <p:column colspan="2">Group 2 Columns</p:column>
        <p:column>No Group Column</p:column>
        <p:column colspan="2">Group 2 Columns</p:column>
        <p:column>No Group Column</p:column>
    </p:row>
    <p:row>
        <p:column>No Group Column</p:column>
        <p:column>No Group Column</p:column>
        <p:column>No Group Column</p:column>
        <p:column>No Group Column</p:column>
        <p:column>No Group Column</p:column>
        <p:column>No Group Column</p:column>
    </p:row>
    <p:row>
        <p:column colspan="3">Group 3 Columns</p:column>
        <p:column colspan="2">Group 2 Columns</p:column>
        <p:column>No Group Column</p:column>
    </p:row>
    <f:facet name="footer">
        <p:row>
            <p:column colspan="4">Group 4 Columns</p:column>
            <p:column colspan="2">Group 2 Columns</p:column>
        </p:row>
    </f:facet>
</p:panelGrid>`
..
## 6) Sample bean

Not Necessary
..

**Comment by melloware** [comment]
@JaviRpo I don't think it was designed to work this way.  Either you pick layout="grid" with columns="5" and let it be responsive or you manually control the layout with columns and rows.  You should check out Grid CSS seems more what you want...

https://www.primefaces.org/showcase/ui/panel/grid.xhtml

I recommend closing this ticket as PF team most likely will not address it.

**Comment by brunotacca** [comment]
I have the same problem, as for now, one can't merge columns (or rows) with a responsive panelGrid, which is unfortunate (_IMHO_), at least columns should have an option to be merged.

The primeface's showcase of responsive design states "In combination with Grid CSS, ui-fluid style class provides fluid width for efficient use of space in screen." (https://www.primefaces.org/showcase/ui/misc/responsive.xhtml)
However, the showcase of GridCSS (https://www.primefaces.org/showcase/ui/panel/grid.xhtml) mentioned, shows one example of a more complex layout (Sample Layout), with the possibility of having rows and/or columns merged, which is not the case of the panelGrid.

I think this is a work to do, having layout="grid" with the possibility of using <p:row> and <p:column> with colspan/rowspan to customize even more the panelGrid, it would increase significantly the flexibility and uses of p:panelGrid.
Thank you in advance.

**Comment by cleverpig** [comment]
mark
