### ISSUE TITLE
[OMEGA][StepsMenu] Label isn't visible on active step on stepmenu with the interactive mode

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#1839]
The color of font is `white` with omega when the css `.ui-steps .ui-state-highlight span` is set.
On interactive mode of `stepmenu`, the label is not visible because there is no background-color for `ui-steps-title`.

![image](https://cloud.githubusercontent.com/assets/8990614/19441355/c34ee286-9485-11e6-96b8-440b7c86cab8.png)

You can see the problem on the showcase : [stepMenu](http://www.primefaces.org/showcase/ui/menu/steps.xhtml)

**Comment by tandraschko** [comment]
Not a core bug, just a custom style bug in the showcase. Fixed it in the showcase -> https://github.com/primefaces/showcase/commit/7cfa75fc5dadbccb2f33de7659caa8ae361976e0
