### ISSUE TITLE
Encoding problem for the first request when using ajax="false" on p:commandButton

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#1843]
## 1) Environment
- PrimeFaces version: 6
- Does it work on the newest PrimeFaces version? Tested with version 6 provided by maven
- Application server + version: WildFly 10.1
- Affected browsers: Reproduced with Chrome 54.0.2840.59, Firefox 45.4.0, Internet Explorer 11
- Language setting: de_DE
- Operating systems tested: Windows 7 and Red Hat Enterprise Linux
## 2) Expected behavior

A form submitted by p:commandButton with the attribute "ajax" set to the value "false" is sent to the server. Multiple inputs are part of the request and were filled with special characters like umlauts.

The following behavior is expected:
- All submitted values are shown in a custom growl message using the correct encoding
- Updated fields are displayed using the correct encoding
## 3) Actual behavior

The values are misinterpreted on the first request. A garbled message will be displayed by growl and in the updated input fields, when the provided XHTML and bean files are used.
The error occurs only for the first request of the session when using PrimeFaces 6 and setting "ajax" to "false". The same files are working as expected when PrimeFaces 5.3 is being used.
## 4) Steps to reproduce

1) Open the provided example in your web browser
2) Type in "Üßer" as username and "Päß" as password (or any other text containing special characters)
3) Click on "Login" for the first request
4) Wrong behavior as shown in picture 1
5) Type in "Üßer" as username and "Päß" as password again
6) Click on "Login" for the second request
7) Correct behavior as shown in picture 2

Picture 1:
![error after first request](https://cloud.githubusercontent.com/assets/61095/19515319/34cb56de-95f7-11e6-995c-413bdd4913f2.png)
Picture 2:
![working after second request](https://cloud.githubusercontent.com/assets/61095/19515348/510aac8c-95f7-11e6-91ee-6369c83d9e04.png)
## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head />

<h:body>
    <h:form id="growlForm">
        <p:growl id="growl" globalOnly="false" life="5000" />
    </h:form>

    <p:panel header="Login">
        <h:form id="loginForm">
            <p:panelGrid columns="2">
                <p:outputLabel for="username" value="Username:" />
                <p:inputText id="username" value="#{exampleBean.username}" />

                <p:outputLabel for="password" value="Password:" />
                <p:password id="password" value="#{exampleBean.password}"
                    feedback="false" />
            </p:panelGrid>

            <p:commandButton value="Login" action="#{exampleBean.test()}"
                update=":loginForm, :growlForm" ajax="false" />
        </h:form>
    </p:panel>
</h:body>
</html>
```
## 6) Sample bean

```
import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class ExampleBean implements Serializable {
    private static final long serialVersionUID = 2151354111298072634L;

    private String username;
    private String password;

    public String test() {
        FacesContext.getCurrentInstance().addMessage(
                null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, String.format(
                        "Login not possible for %s with password %s", username,
                        password), null));

        return null;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String pUsername) {
        username = pUsername;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String pPassword) {
        password = pPassword;
    }


}
```

**Comment by tandraschko** [comment]
does it work with h:commandButton?

**Comment by ghost** [comment]
Hello @tandraschko,

thanks for the quick reply. h:commandButton does not work either.

**Comment by tandraschko** [comment]
Also not with h:commandButton and h:inputText?
I don't think this is an PF issue.
You just need to set the encoding stuff...

**Comment by tandraschko** [comment]
Never faced encoding problems, so will close it for now.

Things that i useually have in my applications:
- `<f:view contentType="text/html;charset=UTF-8" encoding="UTF-8">`
- `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`
- A Character Encoding Servlet Filter

**Comment by ghost** [comment]
Hallo @tandraschko,

thank you for all the information, but it does not work when using h:commandButton and h:inputText also. An encoding filter is not used, but all needed header values and meta tags are set.
I can reproduce the reported error for the "real" application only if version 6 of PF and PF extensions is used. The only difference in the application between correct and erronous behavior is the PrimeFaces related version change in the pom.xml.

 It seems that my provided example does not show exactly the same behavior as the real application. I'm sorry for that and will put my effort into the creation of a better example.

Thank you for the support and keep up the great work!

**Comment by tandraschko** [comment]
Your example works for me, therefore i closed it.
If you could provide a simple maven+jetty application which shows the behavior, also with the settings i mentioned above, please come back and reopen :)

**Comment by glauciosouthier** [comment]
the same problem occurs for me in primefaces 6.2 (charset ISO-8859-1).
only in the first submit of the p:commandButton with the ajax="false"  charset is wrong. 
the subsequent calls works fine.

**Comment by ruzsaz** [comment]
Same here, 7.0.

**Comment by utrucceh** [comment]
https://stackoverflow.com/questions/9634230/unicode-input-retrieved-via-primefaces-input-components-become-corrupted
