### ISSUE TITLE
textEditor does not work in IE11

### ISSUE THREAD

**Issue by ppalanisami** [primefaces/primefaces#1845]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version:6.0.6
- This is the latest version of Primefaces.
- Tomcat 8
- Affected browsers: IE 11
## 2) Expected behavior

The text editor should behave as same as in Chrome and Firefox.
## 3) Actual behavior

Text Editor is not displayed in IE 11.
## 4) Steps to reproduce

Open Primeface's Text Editor  showcase example in IE.
## 5) Sample XHTML

Open Primeface's Text Editor  showcase example in IE.
## 6) Sample bean

Open Primeface's Text Editor  showcase example in IE...

**Comment by mertsincan** [comment]
I tested it with IE11, but I didn't see a bug. Can you please try it with new versions like 6.0.10?

**Comment by tandraschko** [comment]
No response and can't replicate, will close it for now.
