### ISSUE TITLE
MenuItem: using p:confirm with fixed navigation outcome

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#1848]
## 1) Environment
- PrimeFaces version: 6.0
- Application server + version: Tomcat 8.0.14
- Affected browsers: Firefox 49.0.1
## 2) Expected behavior

Since PF 5.2 p:confirm is supported for p:menuItem as well.
I expect to be able to use it when the outcome is fixed, i. e. I provide a navigation outcome without any real action to perform. For example, just like I can do:

```
<p:commandButton id="save" value="Save" action="/main?faces-redirect=true">
    <p:confirm header="Warning" message="Are you sure?" />
</p:commandButton>
```

I would like to do:

```
<p:menuItem id="save" value="Save" action="/main?faces-redirect=true">
    <p:confirm header="Warning" message="Are you sure?" />
</p:menuItem>
```

or even::

```
<p:menuItem id="save" value="Save" outcome="/main?faces-redirect=true">
    <p:confirm header="Warning" message="Are you sure?" />
</p:menuItem>
```
## 3) Actual behavior

In the former case (with action="/main?faces-redirect=true") nothing happens when I confirm with the OK/Yes button (the confirm dialog is just dismissed, nothing more).
.In the latter case, the confirm dialog is not shown at all and the user gets redirected without any confirmation.
## 4) Steps to reproduce

See expected behaviour.
## 5) Sample XHTML

See expected behaviour.
## 6) Sample bean

Nothing really needed for this use case.

**Comment by kukel** [comment]
what is the difference between your last two code blocks

**Comment by melloware** [comment]
[pf-1848.zip](https://github.com/primefaces/primefaces/files/3843536/pf-1848.zip)
Attached is a test case showing the issue.

**Comment by jepsar** [comment]
Why would one want to confirm when navigating to a single menu item? I much more see the point of warning a user when navigating away from a changed form. See https://stackoverflow.com/questions/8259090/how-to-detect-unsaved-data-in-form-when-user-leaves-the-page

**Comment by melloware** [comment]
In 13.0 you can completely control the rendering of a MenuItem with the `<f:facet name="custom"/>` facet.

```xml
<p:menubar>
	<p:submenu label="Print Menu">
		<p:menuitem>
			<f:facet name="custom">
				<p:commandLink id="save" value="Save" action="/main?faces-redirect=true">
					 <p:confirm header="Warning" message="Are you sure?" />
				</p:commandLink>
			</f:facet>
		</p:menuitem>
	</p:submenu>
</p:menubar>
<h:outputText id="image" value="Test"></h:outputText>
```

**Comment by mauromol** [comment]
> In 13.0 you can completely control the rendering of a MenuItem with the `<f:facet name="custom"/>` facet.

So much verbose to obtain something that sounds quite natural, when you compare `p:menuitem` with `p:commandLink`/`p:commandButton`.

@jepsar: your example uses jQuery and JavaScript, so I still believe my original request to be a much more elegant and simple solution, which nicely fits with what is already in place for `p:commandLink`/`p:commandButton`.

**Comment by melloware** [comment]
@mauromol Are you willing to provide a PR?
