### ISSUE TITLE
Queued ajax requests processed on page navigation

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#1849]
Reported by PRO User; 

> We have a couple of ajax requests queued but before the requests are processed we are clicking a button (non-ajax) which will navigate to another page.
> We noticed that on click of the button, the queued ajax requests are also being pushed along with this non-ajax request. This is causing us some issues like blank screen, empty table.

**Comment by tandraschko** [comment]
@mertsincan To be honest, i don't like the fix at all as it just fixes our queue if primefaces non-ajax posts are done.
If the user uses another component (like h:commandButton, b:commandButton, ...), the queue won't be cancelled.
Can't we do it with "onbeforeunload"? Or is it to late?

**Comment by mertsincan** [comment]
@tandraschko,  I added the following event into core.ajax.js;

```
$(window).unload(function() {
    PrimeFaces.ajax.Queue.abortAll();
});
```

Cağatay said users can add "PrimeFaces.onPost();" method to other components(h:commandButton etc.)
