### ISSUE TITLE
Add ctrlKey and metaKey information to SelectEvent

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#185]
Pass these key information to the backend SelectEvent so that users can know more about how the event is performed. Also helps issues like #167.

**Comment by tryptichon** [comment]
May I suggest a more generic approach, that handles altKey and shiftKey as well. Pack it into a class ModifierKeyEvent, then let SelectEvent extend that class. This way we can easily implement more events that need the modifier keys tracked - see pull request https://github.com/primefaces/primefaces/pull/159 for instance. There's a SelectRangeEvent that might need those keys to be tracked as well, and I'm sure there are others, like ItemSelectEvent, NodeSelectEvent etc.
