### ISSUE TITLE
CellEditor Doesn't Update Model For SelectBooleanCheckbox and SelectOneRadio

### ISSUE THREAD

**Issue by rmoyersrfd** [primefaces/primefaces#1854]
Within a p:dataTable with pagination, p:cellEditor containing p:selectBooleanCheckbox and/or p:selectOneRadio, no update of the bound data happens if pagination controls are used.

Notice that p:inputText and p:selectOneMenu DO work properly if pagination controls are used.

This is 100% reproducible with PF 5.3.17 and PF 6.0.6

For example, using the sample XHTML below, check one or more of the checkboxes, then use a pagination control to move to another page. Return to the first page and see that none of the check boxes are still checked. By placing a logger message in the data model's setJobSelected method, we see that the 'setter' never gets called. Changing the p:selectBooleanCheckbox to a p:selectOneMenu, things work properly.

The problem seems to be org.primefaces.event.CellEditEvent, method resolveValue. This obtains the UIComponent within a CellEditor's 'input' facet, then uses the UIComponent 'getValue' method to obtain the component's value. However, for p:selectBooleanCheckbox and p:selectOneRadio, the getValue method always returns null.
## 1) Environment
- PrimeFaces version: 6.0.6
- Does it work on the newest PrimeFaces version? No
- Application server + version: JBoss EAP 6.4.0.GA (AS 7.5.0.Final-redhat-21)
- Affected browsers: Firefox 49.0.1, Chrome 53.0.2785.143 m
## 2) Expected behavior

We expect the bound 'setter' to be called regardless of the type of component wrapped within a CellEditor
## 3) Actual behavior

For components wrapped within a CellEditor, if a pagination control is used, the 'setter' bound to the wrapped component gets called for p:inputText and p:SelectOneMenu. The bound 'setter' does NOT get called for p:selectBooleanCheckbox and p:selectOneRadio
## 4) Steps to reproduce

Build and run the attached application
## 5) Sample XHTML

```
<p:dataTable id="jobUserTable" 
    widgetVar="jobUserTable"
    paginator="true" 
    paginatorPosition="bottom" 
    paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
    rows="5"
    rowsPerPageTemplate="1,2,3,4,5,10,15,20,25" 
    sortMode="multiple"
    var="jobUserPresentation" 
    value="#{jobUserBacking.jobUserPresentationList}"
    initMode="load"
    editable="true"
    editMode="cell"
    editingRow="false"
    saveOnCellBlur="true">

    <f:facet name="header">
        <p:commandButton id="returnToUserManagementButton" icon="ui-icon-circle-arrow-w" value="#{msg.buttonReturnToUserManagement}" action="#{userManagementBacking.doReturnToUserManagement}" ajax="false" />
        <p:spacer width="20" />
        <p:commandButton id="saveButton" icon="ui-icon-disk" value="#{msg.buttonSave}" action="#{jobUserBacking.doSave}" update="jobUserTable" />
    </f:facet>

    <p:column headerText="#{msg.headerJobSelected}">
        <p:cellEditor>
            <f:facet name="output">
                <h:outputText value="#{jobUserPresentation.jobSelected}" />
            </f:facet>
            <f:facet name="input">
                <p:selectBooleanCheckbox value="#{jobUserPresentation.jobSelected}" />
            </f:facet>
        </p:cellEditor>
        <h:inputHidden id="jobUserVersion" value="#{jobUserPresentation.jobUserVersion}" />
    </p:column>

    <p:column headerText="#{msg.headerJobDescription}">
        <h:outputText value="#{jobUserPresentation.jobInfoPresentation.jobDescription}" />
    </p:column>
</p:dataTable>

```
## 6) Sample bean

See the source code (ZIP below)

**Comment by jxmai** [comment]
Is it related to the following reference ? (reference: http://stackoverflow.com/questions/27862661/selectbooleancheckbox-in-editable-datatable-doesnt-change)

**Comment by rmoyersrfd** [comment]
I have solved this problem. The input controls need to have a `<p:ajax ... />` nested within them. For example:

```
<f:facet name="input">
                <p:selectBooleanCheckbox value="#{jobUserPresentation.jobSelected}" >
                   <p:ajax update="jobUserTable" listener="#{jobUserPresentation.someVoidMethod}" />
                </p:selectBooleanCheckbox>
  </f:facet>

```

If the page has multiple input controls, then ALL controls need the p:ajax

Furthermore, the p:cellEditor are not really needed. I think the page looks better without them. The code is certainly cleaner without the cellEditor. For example:

```
    <p:column headerText="#{msg.headerJobSelected}">
        <p:selectBooleanCheckbox value="#{jobUserPresentation.jobSelected}" >
              <p:ajax update="jobUserTable" listener="#{jobUserPresentation.someVoidMethod}" />
        </p:selectBooleanCheckbox>
        <h:inputHidden id="jobUserVersion" value="#{jobUserPresentation.jobUserVersion}" />
    </p:column>

```

That's just my taste, though.

**Comment by rmoyersrfd** [comment]
Here is the little test project I built for this.

[RFDPF1854.zip](https://github.com/primefaces/primefaces/files/543168/RFDPF1854.zip)

**Comment by Rapster** [comment]
Should be closed then

**Comment by melloware** [comment]
PR submitted to fix this issue. I don't have permission to reopen it.  https://github.com/primefaces/primefaces/pull/5095
