### ISSUE TITLE
Not possible to copy and paste image in Text Editor

### ISSUE THREAD

**Issue by ppalanisami** [primefaces/primefaces#1856]
# IMPORTANT

Unable to copy and paste the image on Text Editor.
## 1) Environment
- PrimeFaces version: 6.0.6
- Does it work on the newest PrimeFaces version? 6.0.6 is the new version.
- Application server + version: Tomcat 8
- Affected browsers: Chrome & Firefox
## 2) Expected behavior

When copy an image it should be possible to place directly on the text editor. 
## 3) Actual behavior

Currently, it is possible to insert the image using the Image icon.
## 4) Steps to reproduce

Use Text Editor on Primefaces showcase.
## 5) Sample XHTML

Use Text Editor on Primefaces showcase.
## 6) Sample bean

Use Text Editor on Primefaces showcase.

**Comment by Rapster** [comment]
Maybe related to #1186

**Comment by tandraschko** [comment]
I would suggest to use PrimeFaces Extensions CKEditor. p:Editor used cleditor under the hood, which is not maintained since years.

**Comment by ravihariharan** [comment]
@tandraschko  : Something interesting quill-image-drop-module
https://github.com/kensnyder/quill-image-drop-module

Demo : https://plnkr.co/edit/ubVmPkBjqQESsefM3JrT?p=preview
