### ISSUE TITLE
StreamedContent handler security fix in 6 breaks some media handling

### ISSUE THREAD

**Issue by marklcg** [primefaces/primefaces#1858]
## Environment
- PrimeFaces version: 6.0 (verified in 6.0.6 too)
- Does it work on the newest PrimeFaces version? No
- Application server + version: JBoss EAP 6.4
- Affected browsers: All
## Expected behavior

When streaming a PDF or other media, a second request for the same URL should produce the same streamed content.  Multiple requests occur when using standard browser plugins/features for media types such as PDF.
## Actual behavior

A second request for the same streamed media content fails as the security token has been removed from the user's session map.
## Steps to reproduce

Attached is an example.  To reproduce:
1. Run the application
2. Browse to the index page using Chrome or Firefox.
3. The PDF will appear correctly, however, click the download button in the PDF viewer to download the PDF.  A .xhtml file will be produced and it will be empty.

Alternatively, use IE with the Adobe PDF plugin which fails to render completely producing the error indicating that %PDF must be in the beginning of the file.  This is because the browser pulls the link, but the plugin pulls it again.

Samples attached.

[streamed-content-bug.zip](https://github.com/primefaces/primefaces/files/545838/streamed-content-bug.zip)

**Comment by cagataycivici** [comment]
I see but we should not keep it in session, @tandraschko @mertsincan what do you think? Right now we clear it after displaying the content which makes this work but link won't be bookmarkable to access again. Maybe we can add a configurable timer like after 10 minutes, they key gets removed.

**Comment by tandraschko** [comment]
i think the best way is to remove the "#remove" call and use a custom list implementation which removes the first entry, if the size is e.g. bigger as 250
They are just small expression strings, i think it should not harm to store some hundreds of them

**Comment by tandraschko** [comment]
Is the proposed fix ok for you @cagataycivici ?

**Comment by tandraschko** [comment]
Another solution:
We can set stream=false as default
So @ViewScoped will also work

it's just a little bit slower as a new browser request (AFAIK)

**Comment by tandraschko** [comment]
We could also do both
setting stream=false as default + store the value-expressions in a big list (as fallback if stream=true is used)

**Comment by cagataycivici** [comment]
What does stream="true|false" does?

**Comment by tandraschko** [comment]
stream=true is the current behavior and a url will be rendered -> the image will be requested in a extra http request

stream=false directly writes the byte array base64 encoded to the src attribute

**Comment by tandraschko** [comment]
Ok, this won't work in all cases... stupid IE8...

> IE8 can only do Base64 URI images up to 32kb in size. It's a marginally annoying limitation, but you can still get by with icons/etc. Keep in mind that Base64 encoded images are on average 33% more data sent down the pipe anyway, so it's... eh, y'know, use your judgement.

**Comment by kukel** [comment]
Time to drop IE8 support and move to jQuery 22 instead of 1.x ;-)

**Comment by tandraschko** [comment]
we still have customers with IE8.... :/

**Comment by tandraschko** [comment]
But created a feature request for it: https://github.com/primefaces/primefaces/issues/1894

**Comment by cagataycivici** [comment]
This change would be backward compatible right?

**Comment by tandraschko** [comment]
Yep. I would do it if we drop IE8 later.
Currently i would do this:
`i think the best way is to remove the "#remove" call and use a custom list implementation which removes the first entry, if the size is e.g. bigger as 250
They are just small expression strings, i think it should not harm to store some hundreds of them`

We would still have the problem if the user works e.g. 10 tabs (with over 25 images per view) and use the print function in the first, but i think we can ignore that.
