### ISSUE TITLE
c:forEach inside p:tab does not work

### ISSUE THREAD

**Issue by zeeshanrb** [primefaces/primefaces#1860]
I am using primefaces 6, JSf2.0, jstl 1.2 on Weblogic server. I have an xhtml page where i want to display panels dynamically inside a Tab. The panels should behave like a Dashboard, so i have put the panels inside a dashboard tag.

My problem is that c:forEach is not able to get values from the items I want to iterate. It is confirmed that my "items="${cg.charts}" is of List type and does have objects, but the panels dont appear in UI, as well as there are not exception raised. Any leads ?
## 1) Environment
- PrimeFaces version: 6
- Does it work on the newest PrimeFaces version? NO
- Application server + version: Weblogic 11g
- Affected browsers: IE,Chrome,Firefox
## 2) Expected behavior

There should be a way to create dynamic panels inside p:dashboard, which is inside p:tab
...
## 3) Actual behavior

if i use ui:repeat, instead of c:forEach, i get a ClassCastException , saying that UI repeat cannot be casted to Panel tag

..
## 4) Steps to reproduce

given above
.. 
## 5) Sample XHTML

```
<p:tabView  id="tabViewId"
value="#{userdashboard.chartGroupsList}" var="cg" onTabShow="reflowChart()" >

<p:tab title="#{cg.groupName}" >
    <p:dashboard model="#{userdashboard.model}" >
    <p:ajax event="reorder" listener="#{userdashboard.handleReorder}"  />
    <c:forEach var="c" items="${cg.charts}">

       <p:panel id="pnlDivId#{c.id}" header="#{c.name}">hello</p:panel>

    </c:forEach>

    </p:dashboard>
</p:tab>
</p:tabView>

```
## 6) Sample bean

my Mojarra version is 2.0.9-SNAPSHOT.
I have received some responses to this issue on the below primefaces forums.
http://forum.primefaces.org/viewtopic.php?f=3&t=46903
..

**Comment by tandraschko** [comment]
ui:repeat won't work by design and AFAIR jstl/mojarra integration was very bad in that old versions.
Would you please try a new mojarra version? 2.0.9 is very very old...

**Comment by kukel** [comment]
@tandraschko: no need to try for the OP. In a `c:foreach` you cannot iterate over a var of a tabView... Limitation of JSF, not PrimeFaces

**Comment by tandraschko** [comment]
Yep exactly. Thanks for the hint. I should check the issues more in detail...
