### ISSUE TITLE
Update attributes should skip unrendered components

### ISSUE THREAD

**Issue by cipriandobra** [primefaces/primefaces#1861]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? This is the latest public version
- Application server + version: Glassfish 4.1.1
- Affected browsers: Firefox (but is not browser related)
## 2) Expected behavior

In function `WidgetVarExpressionResolver.resolveComponent` I expect that the traversal of the view's component tree should skip the unrendered components.
## 3) Actual behavior

The traversal is done also in the un-rendered components.
## 4) Steps to reproduce

If the update target of an action is a nested expression starting with `@widgetVar` (see in the sample `@widgetVar(table):@row(1)`) the function `WidgetVarExpressionResolver.resolveComponent` will visit and render the entire component tree no matter if some components should be rendered or not.
## 5) Sample XHTML

In the sample below there is a dynamic tab view whose tabs are not rendered until clicked/showed. The first tab is empty. The second one contains a `p:dataTable` that takes its data from `mainView.values`. The third tab contains a second data table that takes its data from `mainView.randomValues` and a button that has as update target the second row of the table in this third view. The second row of the table is referred with `@widgetVar(table):row(1)`. The resolving of this target triggers the traversal of the entire component tree that will render the second tab (the function `MainView.getValues()` is called).

``` xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Main page</title>
    </h:head>
    <h:body>
        <h:form id="f">
            <p:tabView dynamic="true" cache="false" id="tabView">
                <p:tab title="Page 1" id="tab1">
                    Empty first tab
                </p:tab>
                <p:tab title="Page 2" id='tab2'>
                    <p:dataTable value="#{mainView.values}" var="v">
                        <p:column headerText="Value">#{v}</p:column>
                    </p:dataTable>
                </p:tab>
                <p:tab title="Page 3" id="tab3">
                    <p:dataTable id="dt" value="#{mainView.randomValues}" 
                                 var="v" rowIndexVar="ri" widgetVar="table">
                        <p:column headerText="No">#{ri+1}</p:column>
                        <p:column headerText="Value">#{v}</p:column>
                    </p:dataTable>

                    <p:commandButton
                        id="ub"
                        partialSubmit="true"
                        process="@this"
                        update="@widgetVar(table):@row(1)" 
                        actionListener="#{mainView.changeValue()}" 
                        value="Change value of row 2 to 0" />
                </p:tab>
            </p:tabView>
        </h:form>
    </h:body>
</html>
```
## 6) Sample bean

``` java
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

@Named(value = "mainView")
@ViewScoped
public class MainView implements Serializable {

    private static final long serialVersionUID = 824059173570744435L;

    private static final Logger LOGGER = Logger.getLogger( MainView.class.getName() );


    private List < String > values;

    private List < Double > randomValues;

    private int selectedTab;

    /**
     * Creates a new instance of MainView
     */
    public MainView() {
    }

    @PostConstruct
    private void init() {
        LOGGER.info( "MainView.getValues() initiated" );

        values = Arrays.asList( "Item 1", "Item 2", "Item 3" );

        randomValues = Arrays.asList( Math.random(), Math.random(), Math.random(), Math.random(), Math.random() );
    }

    public List<Double> getRandomValues() {
        return randomValues;
    }

    public void changeValue() {
        randomValues.set( 1, 0.0 );
    }

    public List<String> getValues() {

        LOGGER.info( "MainView.getValues() called" );

        return values;
    }
}
```

**Comment by tandraschko** [comment]
Should work now, please give it a try.

**Comment by cipriandobra** [comment]
I've rechecked the sample code from above and realized only now that just skipping the components that are not rendered could not solve the specific problem of the TabView since even if a tab is not rendered yet (because of a dynamic TabView) isRendered() will return true for it.
But this is an old problem related to TabView and how non-active tabs are visited and can be circumvented by a custom TabView extension.
