### ISSUE TITLE
Dialog with fitViewport = true, is not resized on windows resize

### ISSUE THREAD

**Issue by vbors** [primefaces/primefaces#1862]
## 1) Environment
- PrimeFaces version: 6.0
- Affected browsers: Chrome, Firefox (tested)
## 2) Expected behavior

If Dialog has attribute fitViewport  = true,
For After resize windows the dialog must be resized to fit height of new windows. 
...
## 3) Actual behavior
1. Now when resizing windows it  only adjusts the position
   `bindResizeListener: function () {
       var a = this;
       $(window).on(this.resizeNS, function () {
           a.initPosition()
       })
   }`
   ..

**Comment by melloware** [comment]
I think this is related to #899 and fixed by #2201

**Comment by vonnai** [comment]
The point 2. I don't think, that dialog should change size after update some component inside. Dialog should have fixed size to viewport and if a component overflows, scrollbar is the best practice.

**Comment by vbors** [comment]
Yes you are right, I expressed wrong. 
The problem is that now if you have a component with lazy loading, after loading component the dialog exceed the viewport.

**Comment by vbors** [comment]
I fixed this in my project with an css 'max-height' property.

**Comment by vbors** [comment]
this is my code from function fitViewport of my extended Dialog:

```
                var maxContentHeight = pageContentHeight - titleHeight - innerPadding;
                if (this.jq.innerHeight() > pageContentHeight) {
                    this.content.height(maxContentHeight);
                    if (this.cfg.width !== "auto") {
                        this.jq.width(parseInt(this.cfg.width, 10) + 15);//add scroll width
                    }
                }

                //for resizing on partial update
                var cssMaxHeight = this.content.css('max-height');
                if (!cssMaxHeight || cssMaxHeight === 'none') {
                    this.content.css('max-height', maxContentHeight)
                }
```

**Comment by melloware** [comment]
Can your PR accomodate both fixes?

**Comment by vonnai** [comment]
@vbors Did you try my fix? I think, it's not possible to exceed dialog viewport after lazy load.

**Comment by melloware** [comment]
My apologies I did not try the fix I was just asking if there was a clever way to fix all scenarios with your PR.  Like even adding a new property on dialog if someone does need this behavior.

**Comment by vonnai** [comment]
@melloware be cool, I think my PR fixes the point 1 of this issue.

**Comment by vbors** [comment]
@vonnai I have not tried your fix, When I get time, I'll do a test and let you know :)

**Comment by vbors** [comment]
I read your commit changes and there i have a question:
the documentation of PF 6.0 for fitViewport say :

> Dialog size might exceeed viewport if content **is bigger than viewpor**t in terms of height. fitViewport option 
> automatically adjusts height to fit dialog within the viewport.

on line 113 there are:

```
        if(this.jq.innerHeight() > winHeight) {
            this.content.height(winHeight - this.titlebar.innerHeight() - contentPadding);
        }
```
after this on line 140 you add
`        this.content.height(winHeight - dialogMargin - titlebarHeight - contentPadding - footerHeight);`

So, i see there you have not an condition for height, after your code it has always viewport height?

**Comment by vbors** [comment]
This aspect determined me to use CSS max-height

**Comment by vonnai** [comment]
Yes, it has always viewport height and responsive. If content is bigger than viewport, height is correctly computed and there is scrollbar on the right side of dialog. Entire dialog is always visible and for example buttons in footer part will be always visible too.

**Comment by vbors** [comment]
I think there we should not have dialog with the viewport's height if the dialog size not exceeed viewport.

**Comment by vonnai** [comment]
If you can suppose, that dialog height will not exceed, you don't need fitViewPort property. If you can suppose, that content can exceed the window height, why should dialog change his height dynamicaly? It's more user friendly dialog looks like the same all the time. User always knows, where is the cancel button for example. But you are right, in documentation is written as you say.

**Comment by vbors** [comment]
Because it must be responsive, depending on screen size.

**Comment by vonnai** [comment]
it's fully responsive

**Comment by tandraschko** [comment]
@vonnai 
AFAICS your PR works fine BUT it now the dialog is always as heigh as the window.
I don't think that is correct. I think it should work as "max-height" instead of "height"?!

**Comment by vonnai** [comment]
@tandraschko 
revert changes back, I was waiting for you comment several month, but now I don't have any time to fix PR, but I'll do it. We should discuss it. Should dialog change his position dynamicaly if content is changed? Eg. Window height is 1000px, dialog content height is 400px. If I will dynamically change content to 1200px dialog will show vertical scrollbar and his position will be reinitialized, it means dialog will be always centered if component attribute position = center. So If I update dialog content by p:ajax, height will be dynamicaly changed and user will have footer and topbar always in the other place in window, close button position will be changed. Is this expected behavior?

**Comment by tandraschko** [comment]
I did some improvements on the handling now.
IMO the only case which is not covered now, is if the dialog is visible and the dialog will be updated (the dynamic content change).
If the dialog is updated and is not visible yet, it should also work fine.

As changed to ticket to only cover the resize case (tickets should only target 1 issue). So please create a new issue if you look at it again or there is something missing.
