### ISSUE TITLE
p:messages in ui:repeat not updated correctly

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#1866]
## 1) Environment
- PrimeFaces version: 5.3, 6.0.6
- Does it work on the newest PrimeFaces version? no
- Application server + version: Tomcat 8.0
- Affected browsers: all

## 2) Expected behavior
**p:messages** with autoUpdate="true" in ui:repeat are updated on events

## 3) Actual behavior
p:messages placed in ui:repeat are not updated

## 4) Steps to reproduce
- When "Process input" button clicked, only p:messages NOT in ui:repeat are updated. (all p:messages with autoUpdate should be updated)

![process_input](https://cloud.githubusercontent.com/assets/22746146/19851027/1af00246-9f5c-11e6-8740-1421e9c444b9.PNG) 
- When "Process form" button clicked, everything works fine and error message is shown in all p:messages components in page including those in ui:repeat. 

![process_form](https://cloud.githubusercontent.com/assets/22746146/19851029/1af507b4-9f5c-11e6-827a-4e8c35bd94da.PNG)
- When "Process this" button clicked, only p:messages outside ui:repeat are updated and messages 
are hidden (all p:messages with autoUpdate should be updated)

![process_this](https://cloud.githubusercontent.com/assets/22746146/19851028/1af0b1f0-9f5c-11e6-90ea-aae01b22758f.PNG)

## 5) Sample XHTML
```
<h:form>

      <div class="Container ContainerIndent">
        <p:commandButton value="Process form" id="cb_submitForm" process="@form" update="@form" styleClass="BB" 
           />
      </div>
  
      <div class="Container50 Responsive100">
        <p:panel header="panel" styleClass="ContainerIndent">
          <p:inputText id="testId" required="true" label="text field"/>
          <p:commandButton value="Process input" process="@this testId" update="@this testId" />
          <p:commandButton value="Process this" process="@this" update="@this" immediate="true" />          
        </p:panel>
      </div>

      <div class="Container50 Responsive100">
        <p:panel header="Messages in ui:repeat" styleClass="ContainerIndent">
          <h:panelGroup id="messagesTestPanel">
            <p:outputLabel value="Plain messages:"/>

            <p:messages showDetail="true" autoUpdate="true" closable="true" styleClass="top-messages"/>

            <p:outputLabel value="Messages in ui:repeat:"/>
            <br/>
            <ui:repeat var="messagesRepeatVar" value="#{booleanSelectModel.messagesTestSomeList}" varStatus="messagesRepeatStatus">
              <p:outputLabel value="#{messagesRepeatVar}"/>
              <p:messages showDetail="true" autoUpdate="true" closable="true" styleClass="top-messages" />
            </ui:repeat>

          </h:panelGroup>

        </p:panel>
      </div>

    </h:form>
```
## 6) Sample bean
```
private List<String> messagesTestSomeList = Arrays.asList("first", "second", "third");
public List<String> getMessagesTestSomeList() {
  return messagesTestSomeList;
}
```

**Comment by tandraschko** [comment]
Does it work with MyFaces?
Also not sure if AutoUpdateable could work in ui:repeat correctly.

**Comment by martin654** [comment]
No, not working with MyFaces too.

**Comment by martin654** [comment]
The example I gave is simplified. The real world problem is that we have a composite component with dialog inside. In this dialog there is p:messages to display validation messages on dialog OK button. This composite is rendered on screen multiple times using ui:repeat.

**Comment by martin654** [comment]
Same problem was with the o:messages from omnifaces: 
https://github.com/omnifaces/omnifaces/issues/325
#325 - <o:messages> is now also supported in iterating components

**EDIT:** probably not related with omnifaces issue

**Comment by tandraschko** [comment]
Feel free to provide a PR  ;)

**Comment by martin654** [comment]
We invesitgated it a little bit more and found out that in org.primefaces.event.AutoUpdateComponentListener processEvent method the client ID of each p:messages "instance" is added into partial rendered IDs list. 

The problem is that for p:messages inside ui:repeat the clientId does not contain iteration index. This means that component is not found when component tree is processed.

For example:
created clientId: "myForm:j_idt272:dialogMessagesInRepeat"
but component tree contains in our case: "myForm:j_idt272:0:dialogMessagesInRepeat" and "myForm:j_idt272:1:dialogMessagesInRepeat"

If we add clientIds with iteration indexes in the partial rendered IDs list (debug hack), the components are updated correctly.

**Comment by tandraschko** [comment]
Yep. I don't think there is a easy way to make this work in render-time repeating tags. c:forEach would work.

Also i think using autoUpdate in repeating components is not a good design. I would just use it in very very global tags like a global error messages tag.

**Comment by martin654** [comment]
We would have to call visitTree (with root set to context.getViewRoot()) to determine correct clientId with iteration index for each p:messages. This means that for every p:messages we would visit tree, which is not efficient. It would be bettter to visitTree once for all p:messages after the tree is restored. I suppose that this would be too expensive to visit whole tree including iterations for this functionality in restore-view phase?

Edit: As you pointed out, with p:messages it may not be a good design. What about autoUpdatable p:outputPanel inside ui:repeat?

**Comment by tandraschko** [comment]
It's simply not possible to use visitTree in this case, without rethinking the complete autoUpdateable feature.
AutoUpdateComponentListener listens on PostAddToView, which happens only once for the component and not for each iteration.

autoUpdateable in general is not a good practice in repeat components. As i said, it should be used for something very global.

Will close the ticket for now.
