### ISSUE TITLE
JavaScript errors and failures when rendering view

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#1868]
## 1) Environment
- PrimeFaces version: `6.1-SNAPSHOT` ([commit `fabe6169`](https://github.com/primefaces/primefaces/commit/fabe616970d559e0dd89e1ea6cca023ab2c2d994) is the most recent commit which manifests this issue)
- Application server + version: Tomcat `8.0.32`
- Affected browsers: Firefox, Chrome

## 2) Expected behavior

View renders without JavaScript errors.

## 3) Actual behavior

View renders with JavaScript errors and nothing that requires JavaScript works.

Errors:

```
TypeError: $(...).unload is not a function core.js:1735:1
TypeError: PrimeFaces.widget is undefined components.js:220:1
TypeError: this.widget is undefined core.js:302:1
jQuery.Deferred exception: this.widget is undefined PrimeFaces.createWidget@http://localhost:8181/html5/faces/javax.faces.resource/core.js?ln=primefaces&v=6.1-SNAPSHOT:302:1
PrimeFaces.cw@http://localhost:8181/html5/faces/javax.faces.resource/core.js?ln=primefaces&v=6.1-SNAPSHOT:296:13
@http://localhost:8181/html5/faces/index.xhtml:1:14
resolve/</mightThrow@http://localhost:8181/html5/faces/javax.faces.resource/jquery/jquery.js?ln=primefaces&v=6.1-SNAPSHOT:3508:21
resolve/</process<@http://localhost:8181/html5/faces/javax.faces.resource/jquery/jquery.js?ln=primefaces&v=6.1-SNAPSHOT:3576:12
 undefinedjquery.js:3784:3
TypeError: this.widget is undefined 
```

## 4) Steps to reproduce

1. Build PrimeFaces from source:

        mvn clean install

2. Navigate to a view like the one below.

## 5) Sample XHTML

**`index.xhtml`**

```
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:p="http://primefaces.org/ui">

	<h:head>
	</h:head>

	<h:body>
		<h:form>
			<p:calendar showOn="button" />
			<p:commandButton value="submit" action="page2.xhtml" />
		</h:form>
	</h:body>

</html>
```

**Comment by tandraschko** [comment]
I think this is related to the upgraded jquery version for testing purpose. Will revert it the next days.

**Comment by tandraschko** [comment]
FIxed now
