### ISSUE TITLE
Fileupload should not store files using their original names (files with same name collide)

### ISSUE THREAD

**Issue by msgeissler** [primefaces/primefaces#1874]
## 1) Environment
- PrimeFaces version: 5.3
- Does it work on the newest PrimeFaces version? 6.0 no
- Application server + version: Tomcat 7.0.62
- Affected browsers: Server Side issue
- Additional environments: JSF 2.2.12, Liferay 6.2, Liferay Faces Bridge 4.2.5-ga6

## 2) Expected behavior
If multiple user upload different files with the same name at the same time I expect them to be handled as separate files without any error.

## 3) Actual behavior
After the upload has finished, the file is stored in a temp-directory (the same for all uploads) using the original file name. If multiple uploads occur within a short time span, this can cause the files to be overwritten. If the file is being used in a file upload handler it might be deleted from the temp-directory resulting in a loss of the file for the following requests.

## 4) Steps to reproduce
Simply upload two files with the same name at the same time (unlikely, but not impossible in a big multi-user environment) using different tabs. The uploads will overwrite each other. Accessing the file in file upload handler will cause NPEs as the file will be removed from temp after the first access.

## 5) Sample XHTML
Same as in showcase:
```
<h:form>
    <p:fileUpload fileUploadListener="#{fileUploadView.handleFileUpload}" mode="advanced"
                     update="messages" auto="true" sizeLimit="100000" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
 
    <p:growl id="messages" showDetail="true" />
</h:form>
```

## 6) Sample bean
A very simple test-code, mainly the same as the showcase. Thread.sleep will increase the chance of creating colliding file uploads when testing this alone. Math.random() is used to easily create distinct file names when writing them to another destination. Uploading multiple files with the same name will cause NPE when writing the UploadedFile content to another path.
```
package org.primefaces.showcase.view.file;
 
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
 
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
 
@ManagedBean
public class FileUploadView {
	public void handleFileUpload(FileUploadEvent event) {
        FacesMessage message = new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded.");
        try {
            Thread.sleep(3000);
            Files.write(Paths.get("D:/temp/" + Math.random() + FilenameUtils.getName(event.getFile().getFileName())), event.getFile().getContents());
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
}
```

**Comment by msgeissler** [comment]
Some further testing showed that the folder in the temp-directory seems to be related to the view-session, a new upload in a new browser results in a new folder.
So this should not really be affected by the amount of user currently using the system.

The severity of this problem is not as big as I initially thought, as it might only affect people working in multiple tabs and having a slow backend.

**Comment by melloware** [comment]
Going to close this for now as in 5 years no one else has reported issues with this exact problem so coding a workaround doesn't feel like a good idea.  Can always re-open if more people report or upvote.
