### ISSUE TITLE
cellEdit mode and selectionMode = single p:selectOneMenu can't select first value

### ISSUE THREAD

**Issue by vanuatoo** [primefaces/primefaces#1875]
1) Environment
- PrimeFaces version: 6.0.7
- Does it work on the newest PrimeFaces version? No
- Application server + version: Glassfish 4.1.1
- Affected browsers: Firefox

## 2) Expected behavior
When you have p:selectOneMenu as the editor in p:dataTable and have selectionMode="single" you cannot select first item of the drop down.
...

## 3) Actual behavior
You should be able to select the first item

..

## 4) Steps to reproduce
Please see attached NetBeans project that demonstrates the issue.

**Comment by vanuatoo** [comment]
[Bug.tar.gz](https://github.com/primefaces/primefaces/files/569703/Bug.tar.gz)

**Comment by melloware** [comment]
Attached is test case: 
[pf-1875.zip](https://github.com/primefaces/primefaces/files/3898772/pf-1875.zip)

I have verified this is no longer an issue in PF 8.0.
