### ISSUE TITLE
Ajax navigation with h:commandButton causes primefaces components to fail.

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#1876]
## 1) Environment
- PrimeFaces version: **6.1-SNAPSHOT** (This bug does not occur in 5.3 and below, because it is due to [PrimeFaces Dynamic Resource Dependency Loading](https://github.com/primefaces/primefaces/issues/1066) which was added in PrimeFaces 6.0) (This bug relies on the fact that #1769 is already fixed)
- Does it work on the newest PrimeFaces version? **Yes**
- Application server + version: **All Servers**
- Affected browsers: **All Browsers**
## 2) Steps to reproduce
1. Navigate to **`index.xhtml`**.
2. Click the _view2_ button.
## 3) Expected behavior

The browser navigates to **`view2.xhtml`** without errors.
## 4) Actual behavior

JavaScript components like `p:calendar`'s calendar and `p:selectOneMenu` fail, and the following JS errors appear in the browser logs:

```
undefined entity
ReferenceError: $ is not defined
ReferenceError: PrimeFaces is not defined
ReferenceError: $ is not defined
```

Different errors appear for myfaces and mojarra, but the result is the same.

## 5) Sample XHTML

**`index.xhtml`:**

``` xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <h:commandButton action="view2.xhtml" value="view2">
                <f:ajax execute="@form" render="@form" />
            </h:commandButton>
        </h:form>
    </h:body>
</html>
```

**`view2.xhtml`:**

``` xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <p:calendar showOn="button" />
            <p:commandButton value="index" action="index.xhtml" />
            <p:selectOneMenu>
                <f:selectItem itemLabel="qwer" itemValue="qwer" />
                <f:selectItem itemLabel="asdf" itemValue="asdf" />
            </p:selectOneMenu>
        </h:form>
    </h:body>

</html>
```
## 6) Workarounds

To workaround this issue, use `p:commandButton` instead of `h:commandButton` for ajax navigation.

**Comment by stiemannkj1** [comment]
Note that this issue should be low priority since the workaround is simply to use primefaces components instead of the default JSF components. Usually primefaces developers default to primefaces components anyway.

**Comment by tandraschko** [comment]
As i said, the example works fine with myfaces and is the same mojarra bug.
(Just be sure that the browser cache is cleaned)

**Comment by stiemannkj1** [comment]
Oops :flushed: I didn't even think of that! Sorry to waste your time :(
