### ISSUE TITLE
AjaxExceptionHandler ExceptionInfo in Bean is null or wrong object

### ISSUE THREAD

**Issue by Timaty** [primefaces/primefaces#1877]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: All Servers
- Affected browsers: All Browsers

## 2) Expected behavior

The ExceptionInfo which is shown in die Dialog should be the same if giving it to the Bean.

## 3) Actual behavior

If you use an error page for handling Exceptions showing the informations with the #{pfExceptionHandler} worked. Also you can call a bean method with this object via a commandButton on this page and there will be the right object with the shown informations to use.

If you use ajaxExceptionHandler than the informations in the dialog using the #{pfExceptionHandler} are right. But if you call a bean method with the same object via a commandButton in the dialog than the object in the Bean is null or it is the last object which was created in an error page.

## 4) Steps to reproduce

1. Click the Ajax-Button to trigger a Exception.
2. Dialog with informations about the Exception is shown. Click the commandButton in the Dialog to call a bean method with the object. (In Bean it will be null)
3. Click the Non-Ajax-Button to trigger an other Exception.
4. Error-Page with the informations about the Exception is shown. Click the commandButton on the page to call a bean Method with the object. (In Bean the object is the same as on the page.)
5. Navigate back to previous Page.
6. Click the Ajax-Button to trigger a Exception again.
7. Dialog with the informations of the second Exception of the Ajax-Button is shown with right informations of (second) call of the Ajax-Button. Click the commandButton in the Dialog to call a bean method with the object. (In Bean the object will be the same as the previous Exception of the Non-Ajax-Button which was shown on the error page.)

## 5) Sample XHTML

**index.xhtml**

```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
	<h:form>
		<p:commandButton
			actionListener="#{exceptionHandlerBean.throwNullPointerExceptionAjax}"
			ajax="true" value="Throw NullPointerException from Button Ajax!" />
		<p:commandButton
			actionListener="#{exceptionHandlerBean.throwNullPointerExceptionNoAjax}"
			ajax="false" value="Throw NullPointerException from Button No Ajax!" />

		<p:ajaxExceptionHandler type="java.lang.Throwable"
			update="exceptionDialog" onexception="PF('exceptionDialog').show();" />

		<p:dialog id="exceptionDialog"
			header="Unexpected Error: #{pfExceptionHandler.type}"
			widgetVar="exceptionDialog" height="500px">
			<b>Message:</b> #{pfExceptionHandler.message} <br />
			<b>Time:</b> #{pfExceptionHandler.formattedTimestamp} <br />
			<b>StackTrace:</b>
			<h:outputText value="#{pfExceptionHandler.formattedStackTrace}"
				escape="false" styleClass="textbox300px" />
			<br />
			<p:commandButton
				value="Send error to bean"
				ajax="true"
				actionListener="#{exceptionHandlerBean.sendExceptionViaMail(pfExceptionHandler)}"/>
		</p:dialog>
	</h:form>
</h:body>
</html>
```

**error.xhtml**
```

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
	<h:form>
		<b>Message:</b> #{pfExceptionHandler.message} <br />
		<b>Time:</b> #{pfExceptionHandler.formattedTimestamp} <br />
		<b>StackTrace:</b>
		<h:outputText value="#{pfExceptionHandler.formattedStackTrace}"
			escape="false" />
		<br />
		<p:commandButton
				value="Send error to bean"
				ajax="true"
				actionListener="#{exceptionHandlerBean.sendExceptionViaMail(pfExceptionHandler)}"/>
	</h:form>
</h:body>
</html>
```

**In web.xml**
```
	<error-page>
		<exception-type>java.lang.Throwable
		</exception-type>
		<location>/error.xhtml</location>
	</error-page>
```

## 6) Sample bean

**ExceptionHandlerBean**

```
@ManagedBean
@RequestScoped
public class ExceptionHandlerBean implements Serializable {

    private static final long serialVersionUID = 6749457252128036395L;

    public void throwNullPointerExceptionAjax() {
        throw new NullPointerException("A NullPointerException Ajax!");
    }

    public void throwNullPointerExceptionNoAjax() {
        throw new NullPointerException("A NullPointerException NoAjax!");
    }

    public void sendExceptionViaMail(ExceptionInfo info) {
        System.out.println("SEND MAIL TO ENTWICKLER: " + info);
        if (info != null) {
            System.out.println("Message: " + info.getMessage());
            System.out.println("Time: " + info.getFormattedTimestamp());
        }
    }

}
```

**Comment by tandraschko** [comment]
The problem probably is that the ExceptionInfo is only stored in the FacesContext. So in a new request, the info is lost.
We store in the session for redirects, maybe we should also always store in the session.
BUT, if the user uses multiple tabs and a exception might happen in another tab, the info object stored in the session might the right one.

**Comment by Timaty** [comment]
Okay, I understand.
Is there another option to get the ExceptionInfo in a bean method for ajaxExceptionHandler to send it via mail?

**Comment by tandraschko** [comment]
You could write an own ExceptionHandler.
As i said, i could fix it if you need it but it won't work for multi-tabs if a exceptions occurs in one or more tab probably.

Another solution would be that we store the exceptions in the session and pass the exception id via url param or something.
But the effor is quite high and you are the first user which needed it.
However, you can sponsor it if you like.

**Comment by thlinhit** [comment]
@Timaty You can get the Exception Info as follows:
1. Putting this below line inside your exceptionDialog.
 ```xml
<f:event listener="#{exceptionHandlerBean.storeExceptionInfo}" type="preRenderComponent" />
```
2. In the bean side, you create a value expression like:
```java
public void storeAjaxExceptionIfExist(PreRenderComponentEvent e) {
if (FacesContext.getCurrentInstance().isPostback()) {
			ELContext elContext = FacesContext.getCurrentInstance().getELContext();
			ValueExpression pfExceptionExpression = FacesContext
					.getCurrentInstance()
					.getApplication()
					.getExpressionFactory()
					.createValueExpression(elContext, "#{pfExceptionHandler}",Object.class);
			Object info = pfExceptionExpression.getValue(elContext);
			if (info instanceof ExceptionInfo) {
				ExceptionInfo exceptionInfo = (ExceptionInfo) info;
			}
		}
}

**Comment by LinhTH** [comment]
Hi @tandraschko 
Like @Timaty, I put a button inside the exception dialog to call the bean method for sending an email with the exception info attached. Currently I run into the problem that could be reproduced as following steps:

1. Given a sensitive bean method 
```java
  public void throwNullPointerExceptionAjax() {
        throw new NullPointerException("A NullPointerException Ajax!");
    }
```
and the method will be called by a **p:ajax**.
```xml
<p:tabView>
        <p:ajax event="tabChange" listener="#{bean.throwNullPointerExceptionAjax}" update=":form:msgs"/>
        \\bla bla
</p:tabView>
```
2.  Change the tab to trigger "tabChange" event to call the bean method
3. After the exception dialog appears,  click the send button. But, for an unknown reason,  the send button does not fire action => the "sendExceptionViaMail" method is not called.

However, in the case that the "throwNullPointerExceptionAjax" method is called by a commandButton type="ajax" instead of a p:ajax.  The exception dialog appears and then you click the send button; an email will be sent successfully.

Current I haven't found the reason why it works well with the commandButton type="ajax" but the p:ajax.

_My PrimeFaces version: 5.3_

**Comment by tandraschko** [comment]
I will close this as won't fix. The workaround provided here should be fine!
