### ISSUE TITLE
Gmap geocode not working in tabview

### ISSUE THREAD

**Issue by giorgioprimefaces** [primefaces/primefaces#1879]
1) Environment
Primefaces version 6.0.7 (wasn't working also in previous 6.0.5 not tested previous releases)
Apache tomcat 7
firefox and chrome (not tested other browsers)

2) Expected behavior & Actual behavior
if used outside a tabview (like in the showcase) it is working as expected, but if I try to put it inside a tabview js function geocode() stops to work with this error:

Uncaught TypeError: Cannot read property 'value' of null

        `function geocode() {
                    PF('geoMap').geocode(document.getElementById('address').value);
                }`

NB: referencing address field with tabview ( :tabview:address ) does not resolve the problem

**Comment by tandraschko** [comment]
Please provide a sample xhtml based on the showcase beans.

**Comment by giorgioprimefaces** [comment]
this is the working example:
`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui" >
    <h:head>
        <link href="resources/stylesheet.css?#{startup.time}"  rel="stylesheet"   type="text/css" />
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?key="></script>
        <script type="text/javascript">
            function geocode() {
                PF('geoMap').geocode(document.getElementById('address').value);
            }

            function reverseGeocode() {
                var lat = document.getElementById('lat').value,
                        lng = document.getElementById('lng').value;

                PF('revGeoMap').reverseGeocode(lat, lng);
            }
        </script>

        <title>Geocode Test</title>
    </h:head>
    <h:body>
        <h:form id="frmTab" prependId="false">
            <h3 style="margin-top:0">Geocode</h3>
            <h:panelGrid columns="3" style="margin-bottom:10px" cellpadding="5">
                <p:outputLabel for="address" value="Address:" />
                <p:inputText id="address" />
                <p:commandButton value="Geocode" icon="ui-icon-search" onclick="geocode()" type="button" />
            </h:panelGrid>

            <p:gmap id="geoGmap" widgetVar="geoMap" center="#{geocodeTst.centerGeoMap}" zoom="2" type="ROADMAP" model="#{geocodeTst.geoModel}" style="width:100%;height:400px">
                <p:ajax event="geocode" listener="#{geocodeTst.onGeocode}" update="@this" />
            </p:gmap> 

        </h:form>
    </h:body>
</html>

`

**Comment by giorgioprimefaces** [comment]
In the zip archive you'll find an example, I've used the same java code you can find in geocode demo in PF showcase,
thanks

[example.zip](https://github.com/primefaces/primefaces/files/574888/example.zip)

**Comment by federicomartinlara1976** [comment]
Try this:
- Declare a unique style class for the 'address' element, for example: address
- Access to it via jquery: $('.address').val()

**Comment by tandraschko** [comment]
Not related to PF. If you place components inside UINamingContainers like TabView, they get the inherit the id from the naming container. So this can't work.
Use the full client id or as @federicomartinlara1976 said a style class.

**Comment by giorgioprimefaces** [comment]
ok, thanks
