### ISSUE TITLE
DataExporter reloads the whole ManagedBean?

### ISSUE THREAD

**Issue by RomeoMikeFox** [primefaces/primefaces#188]
Hello,

I'm using PF5.1 in my project, and among others, I do use the DataExporter function for data tables.
I encountered an issue with this function, as it seems to reload the whole managed bean.

I did use the showcase data exporter to be sure, and it seems the issue is also present on PF5.2 showcase. If you export data from the cars data table, there is no correlation between displayed cars and the exported cars. So it seems that by clicking on the export data icon, the bean is reloaded, init() method is called, new random cars are generated and then, exported.

Here is a screen shot of the issue. I loaded the basic data exporter showcase page, clicked on PDF export, then clicked on Excel export, and put side by side the two exports and the showcase datatable.
![data_exporter_pf](https://cloud.githubusercontent.com/assets/12152362/7368690/d656f8b0-edaa-11e4-8b36-c7b073139caa.png)

Is it a PF issue, browser issue, Faces server issue?

Thank you.

**Comment by cagataycivici** [comment]
Please use forum for these types of questions first. Thank you.
