### ISSUE TITLE
Add data entry in datatable vertically

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#1880]
Currently the datatable adds entry as a new row, like:

name | number | color 
 ------  | ------ | ------
apple  | 1|    red |
banana  |      2  |     yellow 

instead, add new data entry as a new **column** what I want is this:

name | apple | banana 
 ------  | ------ | ------
number  | 1|    2 |
color  |      red  |     yellow 

Any ideas?
Thanks.

**Comment by tandraschko** [comment]
use the forum please.
