### ISSUE TITLE
Possible to access disabled tab in tabView.

### ISSUE THREAD

**Issue by karkok** [primefaces/primefaces#1882]
## 1) Environment
- 5.3.5.
- Tomcat 7.0.59
- IE 11, Chrome, FireFox

## 2) Expected behavior
You shouldn't be able to access disabled tab in tabView.

## 3) Actual behavior
You can access disabled tab in tabView.

## 4) Steps to reproduce
1. Go to the page where you have tabView with couple of tabs, where at least one is disabled.
2. Click left mouse button on the disabled tab and keep the button pressed + tap 'Enter' button on the keyboard. (or left mouse button + enter simultaneously.
3. Disabled tab is rendered.

## 5) Sample XHTML
    <p:tabView id="id1">
        <p:tab id="tab1">
              <p:panel id="panel1">
                        Hello.
              </p:panel>
        </p:tab>
        <p:tab id="tab2">
              <p:panel id="panel2" disabled="true">
                        Hello from disabled tab.
              </p:panel>
        </p:tab>
  </p:tabView>

## 6) Sample bean
Not needed.

**Comment by Rapster** [comment]
None of your tabs are disabled actually.... Is the sample correct?
