### ISSUE TITLE
v. 6.1-SNAPSHOT in sonatype is missing

### ISSUE THREAD

**Issue by sytolk** [primefaces/primefaces#1883]
According to this [issue](https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/421)
Can you upload the latest version of primefaces in sonatype
If I have [primefaces-extension v6.1.0](https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/primefaces-extensions/)
There is not dependent primefaces v6.1
`Failure to find org.primefaces:primefaces:jar:6.1-SNAPSHOT in https://oss.sonatype.org/content/groups/public/`

**Comment by tandraschko** [comment]
We don't deploy snapshots
you must build it from source.

**Comment by sytolk** [comment]
@melloware can you deploy primefaces 6.1.0 jar too ? It`s not so hard work to run maven deploy command :)

**Comment by tandraschko** [comment]
I assume he don't have the permissions to deploy primefaces.

**Comment by melloware** [comment]
That is correct I am only a committer and Sonatype authorized for PF Extensions.
