### ISSUE TITLE
Add unique support to AutoComplete

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1884]
A nice feature for AutoComplete would be a unique attribute / function, which enforces the uniqueness of the selected elements. Maybe allow _java.util.Set_ as value in case attribute unique is true.

 Visual effect: 

When a user enters a duplicate element the first occurence could flash with _ui-state-error_ for a second to give user feedback.

**Comment by kukel** [comment]
Feel free to provide a patch ;-)

**Comment by Rapster** [comment]
Duplicate #1495. IMO Autocomplete should be unique and not otherwise

**Comment by Rapster** [comment]
IMO Autocomplete should be unique and not otherwise
