### ISSUE TITLE
AutoComplete with multiple calls converter on ArrayList

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1885]
I have an autocomplete with option multiple set to true. This is bound to an ArrayList in the bean and has an entity converter assigned to it.

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? 
- Application server + version: Glassfish 4.1, JSF Mojarra 2.2.9
- Affected browsers: all

## 2) Expected behavior

Call the converter once for each element, with the element as argument. The converter is responsible for an individual element and not the arraylist. 

## 3) Actual behavior

In the back the _Converter.getAsString(...)_ method is called on the _ArrayList_ once for each element.
If there are 5 elements, the method is called 5 times with the list as argument.
This is unnecessary and calls the converter on the wrong data.

I realized it since i show FacesMessage for each conversion error. So with 5 elements i got 5 error messages.

## 4) Steps to reproduce

Create autocomplete with an converter bound to an arraylist. Log the calls of _Converter.getAsString()_ and the type of the object value passed to the converter.

**Comment by tandraschko** [comment]
Sorry can't follow you.
Quotes from you:

> Expected: ... Call the converter once for each element....
> Actual: .... method is called on the ArrayList once for each element. ...

is the same for me.

**Comment by djmj** [comment]
I will try it with an example:

**Bean**

```
private List<Foo> selectedFoos;
private Converter fooConverter;
public List<Foo> completeMethod(String query) { }
```

**Markup**

```
<p:autoComplete value="#{bean.selectedFoos}" converter="#{bean.fooConverter}" completeMethod="#{bean.completeMethod}" multiple="true"/>
```

**Converter**

```
public class FooConverter implements Converter
{
public String getAsString(final FacesContext context, final UIComponent component, final Object value)
{
    System.out.println(value.getClass().getSimpleName());
    return null;
}
}
```

**If we selected 3 elements, what should the console log be?**

_Foo
Foo
Foo_

**But it is:**

_Foo
Foo
Foo
ArrayList
ArrayList
ArrayList_

So the converter is invoked using the _ArrayList_ as an argument. Which is just unnecessary.

**Comment by Rapster** [comment]
Does this mean we should be able to reproduce it in the present showcase? I just tried quickly, I don't reproduce your problem with multiple theme autocomplete

**Comment by djmj** [comment]
Did you debug or log the value class like `System.out.println(value.getClass().getSimpleName());` in the converter method?

I could only test with PF 6.0.

**Comment by Rapster** [comment]
Debug, what's the difference?

**Comment by djmj** [comment]
Okay maybe it was fixed in a newer version.

**Comment by tandraschko** [comment]
> Okay maybe it was fixed in a newer version.

Will close it for now :)
