### ISSUE TITLE
TreeTable dynamic columngroup with dynamic columns - Header won't display

### ISSUE THREAD

**Issue by CloudStrife28492** [primefaces/primefaces#1886]
Hi there,

I'm trying to implement a treetable with dynamic columns and therefore dynamic headers as well.

So far everything works fine if I use it like this : 

`<p:treeTable value="#{auswahlBestehendeAuftraegeController.root}"`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`var="auftrag" id="treeTable" >`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<f:facet name="header">TreeTable</f:facet>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:columns var="col" value="#{auswahlBestehendeAuftraegeController.columns}" headerText="#{col.header}">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:outputLabel value="#{col.value}"</p:outputLabel>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</p:columns>`
`</p:treeTable>`

But now I want my headers to have different row- and colspans and therefore I thought I just use
the columngroup-tag from the datatable.

But when I try this, the header ist not displayed at all. Here's my actual code:

`<p:treeTable value="#{auswahlBestehendeAuftraegeController.root}" var="auftrag" id="treeTable" >`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<f:facet name="header">TreeTable</f:facet>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:columnGroup type="header">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:row>`
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<ui:repeat value="#{auswahlBestehendeAuftraegeController.createHeaders()}" var="headerText">`
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:column headerText="#{headerText}"></p:column>`
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</ui:repeat>`
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</p:row>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</p:columnGroup>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:columns var="col" value="#{auswahlBestehendeAuftraegeController.columns}" headerText="#{col.header}">`
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:outputLabel>#{col.value}</p:outputLabel>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</p:columns>`
`</p:treeTable>`

If I use a "static" column in the columngroup it gets displayed but not he dynamic ones.
And if I use (almost) the same code on a datatable everything works fine.

`<p:dataTable
        id="myTable" value="#{auswahlBestehendeAuftraegeController.listBestandauftrag}" var="auftrag">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<f:facet name="header">Datatable</f:facet>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:columnGroup type="header">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:row>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<ui:repeat value="#{auswahlBestehendeAuftraegeController.createHeaders()}" var="headerText">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:column headerText="#{headerText}"></p:column>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</ui:repeat>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</p:row>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</p:columnGroup>`
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<p:columns var="col"
          value="#{auswahlBestehendeAuftraegeController.columns}" headerText="#{col.header}">`
          `#{col.value}`
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</p:columns>`
      `</p:dataTable>`

Is this an actual bug or am I just to stupid to get this thing going.

**Comment by CloudStrife28492** [comment]
Yeah, I found the error.

Obviously treetable neither likes p:repeat nor ui:repeat. So I tried it using c:forEach and tadaaaaa it works like a charm. So to anyone who wants to use dynamic columns and dynamic columngroup on a treetable use c:forEach :)

**Comment by tandraschko** [comment]
All right, will close it ;)
Next time: please attach complete examples, otherwise your ticket could be closed as invalid.

**Comment by HariharaK23** [comment]
@CloudStrife28492 No where you have used rowspan or colspan attribute here in the code you have provided. Can you attach the complete example? I'm having the issue while using rowspan and colspan
