### ISSUE TITLE
SplitButton: adds horizontal scroll in RTL

### ISSUE THREAD

**Issue by mohsen** [primefaces/primefaces#1887]
Environment
- PF 6.0
- Latest Chrome and FF

`<p:splitButton>` ins buggy in RTL environment in all modern browsers. The issue is huge text indent (`text-indent: -9999999px;`) for this span in the result html:
`<span class="ui-button-text ui-c">ui-button</span>` 

The workaround is to add this rule in page CSS:
`.ui-button-icon-only .ui-button-text { overflow: hidden }`

**Comment by tandraschko** [comment]
I will close it for now, i have no idea how to replicate.
Feel free to create a new issue with all required informations next time.
