### ISSUE TITLE
p:calendar timeControlType="select" does not work with national time pattern

### ISSUE THREAD

**Issue by mauritz-lovgren** [primefaces/primefaces#1889]
## 1) Environment
- PrimeFaces version: 6.0.6
- Does it work on the newest PrimeFaces version? no
- Application server + version: JBoss EAP 7.0.3
- Affected browsers: All major.

## 2) Expected behavior

p:calendar should present time input select dropdowns for hour, minute (and second) when timeControlType ="select" (instead of default 'slider'), even when using national date time pattern, like the Norwegian pattern: 'dd.MM.yyyy HH.mm' (note the use of dot as hour.minute separator here which seems to confuse the time control renderer).

## 3) Actual behavior

p:calendar shows sliders for time input even though 'select' mode was used (the sliders works, but we really need the select dropdowns).

## 4) Steps to reproduce

Use a p:calendar with pattern="dd.MM.yyyy HH.mm" and timeControlType="select".

## 5) Sample XHTML

<p:calendar value="#{dateTimeInputBean.date}" pattern="dd.MM.yyyy HH.mm" timeControlType="select"/> 

## 6) Sample bean

@Model
public class DateTimeInputBean {
    private Date date;

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getDate() {
        return date;
    }
}

**Comment by FastainCS09** [comment]
The if (hasTime()) Condition in CalenderRenderer.java is buggy,it returns true only when the pattern is not  null or contains (":") ,so that's why no pattern runs except that contains separator (:).

`
  public boolean hasTime() { 
        String pattern = getPattern();
        return (pattern != null && pattern.indexOf(":") != -1);
    }
`
The work around is to comment the check and it will works for all the patterns.
