### ISSUE TITLE
Treetable misalignment in combination with scroll

### ISSUE THREAD

**Issue by filipinicolau** [primefaces/primefaces#189]
PF-Version: 5.2.1
App-Server: WildFly 8.1.0 Final 

When i use treetable in combination with scroll, columns lose alignment the corresponding column header.

This same problem happens in showcase using Chrome.

See screenshot.

![showcase1](https://cloud.githubusercontent.com/assets/12153389/7370037/855966ea-ed8d-11e4-9d3a-07a121d263c8.png)
![showcase](https://cloud.githubusercontent.com/assets/12153389/7370038/8b621f00-ed8d-11e4-8b49-112e71f4f0e9.png)

**Comment by cagataycivici** [comment]
So this happens only on vertical scrolling? Vertical+Horizontal is fine?

**Comment by filipinicolau** [comment]
Only vertical scrolling. Vertical + Horizontal scrolling is fine in showcase.

**Comment by cagataycivici** [comment]
I've replicated, thanks.

**Comment by filipinicolau** [comment]
Thank you

**Comment by Rafaelsk** [comment]
Was that Horizontal or Vertical? I'm also having the same issue with the vertical scrolling
