### ISSUE TITLE
First row in datatable always highlighted since PF 6

### ISSUE THREAD

**Issue by GianlucaD** [primefaces/primefaces#1891]
if u use a rowSelect Ajax-Event on a datatable, the first row is highlighted, instead of the selected row

<p:ajax event="rowSelect" update="@form"> changes the highlighted Row

## 1) Environment
- PrimeFaces version: 6.0.7
- Application server  Tomcat 8.0.17
- Affected browsers: all

## 2) Expected behavior
the highlighted row is the last selected row.
As in 5.3.1 or pre 6.0  
## 3) Actual behavior
actually the first row is highlighted which is false...

## 4) Steps to reproduce
Just add a datatable on your xhtml-page and add the ajax for RowSelect 

## 5) Sample XHTML
you can use the example of Primefaces Showcase:

```
<h:form id="form">
         <p:dataTable id="eventsDT" var="car" value="#{dtSelectionViewX.cars3}"  selectionMode="single" selection="#{dtSelectionViewX.selectedCar}" rowKey="#{car.id}">
              <f:facet name="header">
                  Select Events
              </f:facet>
              <p:ajax event="rowSelect" listener="#{dtSelectionViewX.onRowSelect}" update="@form" />
              <p:ajax event="rowUnselect" listener="#{dtSelectionViewX.onRowUnselect}" update="@form" />
              <p:column headerText="Id">
                  <h:outputText value="#{car.id}" />
              </p:column>
              <p:column headerText="Year">
                  <h:outputText value="#{car.year}" />
              </p:column>
              <p:column headerText="Brand">
                  <h:outputText value="#{car.brand}" />
              </p:column>
              <p:column headerText="Color">
                  <h:outputText value="#{car.color}" />
              </p:column>
          </p:dataTable>
      </h:form>
```

**Comment by tandraschko** [comment]
@mertsincan Feel free to port it to elite :)

**Comment by cagataycivici** [comment]
@aragorn please revert this, this can be solved with JavaScript. First row is not selected, it receives focus visuals for keyboard access.

**Comment by tandraschko** [comment]
Hey Cagatay, i fixed a real bug that the selection is thrown away - also if the selection VE contains a real value.
Therefore if you update the datatable, there will never be a selected row as DataTable#processUpdates always sets it to null.

**Comment by GianlucaD** [comment]
Something changed between 5.3.1 and 6.x Wouldn't it be better to revert these changes?

**Comment by mertsincan** [comment]
I added a new fix for this issue with JS code. PF6.1 already has this fix. Therefore, I added it to only PF6.0.9 elite release.
