### ISSUE TITLE
InputMask: incomplete submit value when mask contains '?' and a character at the end

### ISSUE THREAD

**Issue by gyan2** [primefaces/primefaces#1892]
## 1) Environment
- PrimeFaces version: 5.3 or 6.0
- Application wildfly-9.0.0
- Affected browsers: Firefox 49.0.2, Chrome 54.0.2840.71 m, Edge 38.14393.0.0

## 2) Expected behavior
<p:inputMask id="nss" value="#{myBean.number}" mask="9.99.999.?(99)">

with input '12345678' i expecting '1.23.456.78)'

## 3) Actual behavior
result is '1.23.456.(78', missing the **last character**

any combination with '?' and a character on the end of the mask. The last character will not be submited.

**Comment by melloware** [comment]
@gyan2 i would close this issue.   The ? is a special regex character you can read about here.

https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html

From looking at your example above it makes no sense when you say you were expecting '1.23.456.78)'.  Why would you expect the first parenthesis to not be displayed but the second one?  It looks like you are trying to do some kind of optional capture group?

**Comment by tandraschko** [comment]
@melloware Is the mask really used on the server side, too? AFAIR its only used on the client, you have the check the JS regex docu, not java's Pattern.

**Comment by cnsgithub** [comment]
@gyan2 I think it's just a typo, `1.23.456.(78)` should be expected instead.

> with input '12345678' i expecting '1.23.456.78)'

@tandraschko @melloware With #3237 the mask will be translated to regex on the server side. The mask itself is not a regex, it's specific to jquery.maskediput. Internally jquery.maskedinput uses JS regex. The bug lies there. However, since jquery.maskedinput is in archived state we have no chance to get it fixed from there (one more reason to switch to cleave.js as mentioned in #3240). In jquery.maskedinput.js, line 156, the last parenthesis gets trimmed.

**Comment by melloware** [comment]
@cnsgithub Great debugging!  Should we just fix the JS right now since the component is dead and move to cleave.js in 6.3?

**Comment by cnsgithub** [comment]
@melloware The jquery.maskedinput code is somewhat cryptic, so that I am not willing to try to fix it there. :-1: However, if you're crazy enough, feel free to give it a try. This is the 'simple' return statement:
```javascript
return allow ? writeBuffer() : partialPosition > lastMatch + 1 ? settings.autoclear || buffer.join("") === defaultBuffer ? (input.val() && input.val(""), clearBuffer(0, len)) : writeBuffer() : (writeBuffer(), input.val(input.val().substring(0, lastMatch + 1))), 
                    partialPosition ? i : firstNonMaskPos;
```

**Comment by melloware** [comment]
HA!  That is some terrible unreadable code right there.  OK let's definitely move to cleave.js in 6.3.
