### ISSUE TITLE
inputMask, cursor key not working in Firefox

### ISSUE THREAD

**Issue by gyan2** [primefaces/primefaces#1893]
## 1) Environment
- PrimeFaces version: 5.3 or 6.0
- Application wildfly-9.0.0
- Affected browsers: **Firefox 49.0.2**

## 2) Actual behavior

<p:inputMask id="name" value="#{myBean.name}" mask="*.**.***.****">

at editing a Field with inputMask, the **arrow keys**(left, right) not working in Firefox Browser.

in other Browser like Chrome 54.0.2840.71 m or Edge 38.14393.0.0 its do well.

sry i coudn't test it with PrimeFaces 6.0.6

**Comment by mertsincan** [comment]
I couldn't replicate this issue with inputMask demo in showcase on FF50.0.2.

**Comment by melloware** [comment]
@gyan2 I can't replicate this either.  I recommend closing the issue.

**Comment by gyan2** [comment]
me again,

problem solved with Version 6.1

may fixed with issue #1481
