### ISSUE TITLE
[Documentation] Add documentation for p:graphicImage stream=false benefits

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#1894]
see #1858

**Comment by tandraschko** [comment]
As there are also downsides, it's probably better to not do this change.

@cagataycivici @mertsincan 
WDYT about adding a BIG HINT to the userguide that stream=false directly renders the image as base64, therfore is sometimes faster and does support @ViewScoped?

**Comment by cagataycivici** [comment]
Decided not to do a change in docs
