### ISSUE TITLE
Chips: Paste delimited list to add multiple

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#1895]
Autocomplete is one of the best input component and i have a new idea to increase its usability.

**Feature**

Allow copy and pasting of a delimiter separated list into the textbox to quickly add multiple elements. It is an feature for advanced users to save much input time. 

**A)**

1. Activate _advanced mode_ clicking on an icon (similar to source mode of text-editor). 
2. A normal text input with a delimiter separated list is shown.
3. User can simply edit this list by hand.
4. User leaves _advanced mode_.

user can also reorder elements in this mode

**B)** 

https://select2.github.io/examples.html#tokenizer

**Example**

I have a string in my clipboard like _"test1, test2, test3"_ and an autocomplete with attributes _value="#{bean.list}" multiple="true" delimiter=","_. 

When i paste this string into the textbox the string gets split resulting in three elements.

_"test1"_
_"test2"_
_"test3"_

**Result**

Three new elements are in the final arraylist

**Workaround**

Use a dialog with an input field bound to the same value to allow mass input.

**Comment by melloware** [comment]
Relates to: https://github.com/primefaces/primefaces/issues/2481

**Comment by melloware** [comment]
I am not sure this feature makes any sense.  This would have to AutoComplete all 3 values pasted to make sure they are in the list?  This doesn't make a lot of sense to me for AutoComplete and would make more sense in the Chips component where free text entering of data is allowed.

**Comment by djmj** [comment]
The _value_ attribute of _AutoComplete_ does not requires data to be already persisted in the database or any other source. 

In my autocomplete i compare the input against the database in the converter and if its a new value i create a new _transient_ instance, so the converter never returns null or an empty list! Its a combination between autocomplete and chips with free input. Its basically a lazy-instant creation autocomplete and saves hours of data input. Additional we use a dialog to allow batch / mass data insert using a comma separated list, because often we can copy data from external datasources.

**Lazy creation**

While editing the user can add new items to the datasource. Else the user would need to go to a different page and add every new item manually.

This feature is very useful if ORM / Hibernate entities are directly used in UI and you have _cascade="create"_ option activated on the parent with the result of 0 code required at application layer.

**Batch insert**

We obtain our product data from external sources like vendor, brand PDF, Excel or websites and _often_ they are very good formatted as a comma separated list. So we batch insert them into our autocomplete _value_.

**Example**

Here our workflow with images in our product content management system. We added now 20k products with 70k product-details but only 3000 invididual properties as base of those details / autocomplete. 

In the image you see the product coca cola with a tree table to edit its ingredients and nutrition values.

![1-edit-childs-dialog](https://user-images.githubusercontent.com/5265550/102699331-1015b700-4244-11eb-9afe-df9e55b9138a.jpg)

1. we select _Zutaten / Ingredients_ to open a new dialog with an autocomplete with multiple option and a button for batch insert option.

![2-autocomplete-multiple-converter-transient-instance-plus](https://user-images.githubusercontent.com/5265550/102699332-10ae4d80-4244-11eb-810f-6156fe7ca84c.jpg)

2. we type in some letters and could not find a perfect match, so we show a small + sign to indicate to user its a new word if he selects it.

![3-workaround-batch-edit-comma-separated](https://user-images.githubusercontent.com/5265550/102699333-1146e400-4244-11eb-944b-a3977f743787.jpg)

3. we copy a comma separated list of values from an external PDF and mass insert them. A separate string to collection converter is used as a _preprocessor_ before manually invoking the autocomplete entity converter for each string.

![4-workaround-batche-edit-sync-autocomplete-value](https://user-images.githubusercontent.com/5265550/102699334-11df7a80-4244-11eb-8c8b-1c1fcfb5b36b.jpg)

4. final composition and each string in the comma separated input was matched against the converter and either obtained a persisted or new transient instance of our property entity class.


This combination **(autocomplete + lazy create + batch to autocomplete)** is the reason we are able to input so many data in a small time manually. I posted this feature issue because its a common problem in data input and can save many people alot of time.

The batch insert is also valid for chips or any other component with a collection as its value and maybe a generic solution could be possible like _<p:inputBatch for="autocomplete" discriminator="," converter="MyStringToCollectionConverter" value="#{bean.values}" update="autocomplete"/>_

**Comment by melloware** [comment]
I think I got it.    I think I will add this pasting to `Chips` and `AutoComplete` and have a `pasteDelimiter` attribute because some people might want to use comma , and some semicolor ;

I will see if I can fix this and get this into 9.0

**Comment by djmj** [comment]
Nice!

For our use case its even more complex since we need the input field being editable which chips does not support. https://github.com/primefaces/primefaces/issues/6691

We often get unwanted characters like ():; or number values we must remove manually before _"passing"_  the list  to the autocomplete, so we need the input editable. Sometimes they even mix delimiters or have no delimiter at all. With external sources we have seen everything :D

Example: _"test (5%),sugar: 10g,bar (child1, child2),foo,_ we manually convert to _"test,sugar,bar,foo"_ removing the numbers / units and child nodes _"(child1, child2)"_ that need to be added in a second step manually.

**Comment by melloware** [comment]
@djmj Converted this ticket to just chips for now. As AutoComplete is much trickier and would require some code rearranging.
