### ISSUE TITLE
DataTable: allow disable reorder columns to specific position

### ISSUE THREAD

**Issue by sergiyuvarov** [primefaces/primefaces#1899]
# IMPORTANT 
Please, add such functionality to datatable component: disable reorder columns to specific position.

**Comment by kukel** [comment]
Go ahead and create a pull request... (and using important in capitals and kind of bold without any real substantiation of your request has most likely the opposite effect, it gets ignored since it feels like shouting/begging)

**Comment by tandraschko** [comment]
Only 1 request in 4 years and even no idea how to implement it. Lets close it for now until another request shows up
