### ISSUE TITLE
p:link does not consider f:param tag

### ISSUE THREAD

**Issue by marembo2008** [primefaces/primefaces#19]
I have the following:

```
<p:column>
    <h:link outcome="some-outcome">
      <f:param name="someid" value="theid"/>
    </h:link>
</p:column>
```

and

```
<p:column>
    <p:link href="some-outcome">
      <f:param name="someid" value="theid"/>
    </p:link>
</p:column>
```
The default h:link correctly adds the f:param value as a query parameter to the request url, while the p:link does not.

Is there a reason why p:link does not support f:param or is this just a bug?

Caveat: The above code is within a p:datatable component.

**Comment by kukel** [comment]
PF Version?

**Comment by marembo2008** [comment]
PF Version 5.2

**Comment by kukel** [comment]
PF Version? And please still use the forums first. We do not want to get the issuelist cluttered up again like in google!

**Comment by jdesmet** [comment]
@marembo2008 suggests that this is fixed in PF Version 5.2, however PF 6.2 still shows the same issue.

**Comment by open-gdsn** [comment]
Still or again? Tried 5.2 to see if it is a regression? If so check 5.3, 6.0 and 6.1 please

**Comment by tandraschko** [comment]
it was implemented 2-3 months ago AFAIR ;)
