### ISSUE TITLE
schedule component: Support for displayEventEnd

### ISSUE THREAD

**Issue by aroeber** [primefaces/primefaces#190]
pls see http://forum.primefaces.org/viewtopic.php?f=3&t=41434

The new FullCalendar has introduced a new attribute:
displayEventEnd (http://fullcalendar.io/docs/text/displayEventEnd/)
This seems to be necessary to display the event end time with the new FullCalendar (for certain views).
Currently PF doesn't allow to set this attribute.

**Comment by tryptichon** [comment]
... and another occasion where it would be useful to be able to set the view parameters via a schedule-attribute. I suggested such a thing here (https://github.com/primefaces/primefaces/pull/138), but it got rejected. :(

@cagataycivici Maybe we could introduce viewFormat as an additional attribute nonetheless to give users access to all needed options of the fullcalendar.io-views?

**Comment by cagataycivici** [comment]
Do you mean extender as in chart components?

**Comment by tryptichon** [comment]
Ah, so that's the way it's done. That sounds like a good idea IMHO.

**Comment by cagataycivici** [comment]
Sure, feel free to create a separate request.

**Comment by cagataycivici** [comment]
Created #205

**Comment by jeeftor** [comment]
I'd love to see this fixed soon

**Comment by kukel** [comment]
There is extender functionality... You can always use that for now

**Comment by cagataycivici** [comment]
@jeeftor Do you mean displayEndEvent?

**Comment by aroeber** [comment]
As kukel mentioned it can be done via extender functionality as a work around:

```
<h:outputScript>
    function ext() {
        this.cfg.views = {
            month: { // name of view
            displayEventEnd: true
            }
        }
   }
</h:outputScript>

<p:schedule value="#{calView.eventModel}" timeFormat="HH:mm" extender="ext" />
```
