### ISSUE TITLE
p:remoteCommand destroys @ViewScoped managed bean

### ISSUE THREAD

**Issue by Berger1994** [primefaces/primefaces#1900]
If a remote command is invoked, which is not rendered in the actual dom tree, all beans with the "view scoped" annotation reinitialized.

It would be nice if this were handled with javascript ("PrimeFaces.ajax.Request.send").
Proposal for solution:
```javascript
PrimeFaces.ajax.Request.send = function(cfg) {
	sourceId = null;

	if (typeof (cfg.source) === 'string') {
		sourceId = cfg.source;
	} else {
		sourceId = $(cfg.source).attr('id');
	}

	if (!($(PrimeFaces.escapeClientId(sourceId)).length)) {
		//remove from queue
        	if(!cfg.async) {
            		PrimeFaces.ajax.Queue.poll();
	        }
		
		return false;
	}

	// ...
}
```
The only problem is that the RemoteCommandRender does not render the script tag in a extra container. For the solution above, this is required too.

```java
public class RemoteCommandRenderer extends org.primefaces.component.remotecommand.RemoteCommandRenderer {

	@Override
	public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
		ResponseWriter writer = context.getResponseWriter();
		RemoteCommand command = (RemoteCommand) component;
		String clientId = command.getClientId(context);
		String name = resolveName(command, context);
		UIComponent form = ComponentTraversalUtils.closestForm(context, command);
		if (form == null) {
			throw new FacesException("RemoteCommand '" + name + "'must be inside a form.");
		}

		writer.startElement("span", null);
		writer.writeAttribute("id", clientId, "id");
		writer.writeAttribute("class", "hidden", "class");

		super.encodeEnd(context, component);

		writer.endElement("span");
	}

}
```

## 1) Environment
- PrimeFaces version: 6.0.7
- Application server + version: GlassFish 4.1.1
- Affected browsers: all browsers

## 2) Expected behavior
The javascript function PrimeFaces.ajax.Request.send should check the source id. 

## 3) Actual behavior
All beans with the view scoped annotation reinitialized (@PostConstruct has been invoked)

## 4) Steps to reproduce
Execute a remoteCommand which is actual not rendered.

sample:
Click on the button "hide container" two times. 

## 5) Sample XHTML
```xml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:o="http://omnifaces.org/ui">
<h:head>
</h:head>

<h:body>
	<p:outputPanel id="formContainer">
		<p:outputPanel rendered="#{testPage.renderContainer}">
			<h:outputText value="Form Container" />
			<br />
			<h:form>
				<h:outputText value="Remote Command" />
				<p:remoteCommand name="hideContainer" action="#{testPage.hideContainer}" process="@this" update=":formContainer" />
			</h:form>
		</p:outputPanel>
	</p:outputPanel>
	
	<p:commandButton onclick="hideContainer(); return false;" value="hide container" />
</h:body>
</html>
```

## 6) Sample bean
```java
@Named
@ViewScoped
public class TestPage implements Serializable {
	private static final long serialVersionUID = 372367373223155571L;

	private boolean renderContainer = true;

	@PostConstruct
	public void postConstruct() {
		System.err.println("postConstruct has been invoked");
	}

	public String hideContainer() {
		renderContainer = false;
		return null;
	}

	public boolean isRenderContainer() {
		return renderContainer;
	}

	public void setRenderContainer(boolean renderContainer) {
		this.renderContainer = renderContainer;
	}
}
```

**Comment by tandraschko** [comment]
Not sure if PF is the problem.
Normally, for commandButtons or similar, the ajax request is still executed but the JSF impl doesn't execute the action/actionListener.
Could you check it with other jsf implementations/version and what happens with h:/p:commandButton?

**Comment by tandraschko** [comment]
EDIT:
checked your post again (i thought it isn't available in the server-side "DOM") and will fix it before 6.1.

**Comment by kukel** [comment]
Good catch. This explains the behaviour I saw in one of my test projects to.

**Comment by tandraschko** [comment]
Could you please provide a simple xhtml+bean to replicate the issue in the showcase?
I'm not sure if it's good to fix this. Maybe you should just also don't render the button (or something else) which triggers the remoteCommand.

**Comment by Berger1994** [comment]
Sorry for my late response.

I think with the example in my first post the problem should be replicatable in the showcase. In my project i don't use the button to execute the remotecommand.

I am using websocket, and the server sends me some remotecommand-ids to execute. I only check if the function is available in the current javascript cache and than i execute it.


The problem is not only with remotecommands. It seems that every ajax request with an unknown source (not available in the server side "DOM"), crashes all viewscoped beans.


---
When you execute an ajax request without primefaces (jsf.js) no request will be send, but the javascript console gets an error.

```
Uncaught TypeError: Cannot read property 'name' of null
    at Object.request (jsf.js.xhtml?ln=javax.faces:1)
```


This is caused by: jsf.js (source)

```
if (typeof source === "string") {
	element = document.getElementById(source)
} else {
	if (typeof source === "object") {
		element = source
	} else {
		throw new Error("jsf.request: source must be object or string")
	}
}

if (!element.name) {
	element.name = element.id
}
```


The element could not be found and so the id attribute could not be read.

I think primefaces should check that, and finally execute no ajax call too. (better log in the console too)

**Comment by tandraschko** [comment]
So you also manually invoked the PF ajax script? Could you please post the script?

The problem is, you are the first user since many many years which found this issue. We automatically remove the script tag of rendered widgets after the script has been executed. If we would like to fix this issue, we must NOT remove the script tag. As this is a behavior we have since ~5 years, i have to discuss this with Cagatay first.

**Comment by tandraschko** [comment]
Reverted this as will close it as won't fix. The JSF impls sometimes decides to not render the id of the components, so this will break existing functionality.

**Comment by Berger1994** [comment]
Oh.. i checked the problem again and now I think i found the right problem.

The sample is the same as in the first post. On the first click on the button there are 7 post params
```
javax.faces.partial.ajax:true
javax.faces.source:j_idt8:j_idt14
javax.faces.partial.execute:j_idt8:j_idt14
javax.faces.partial.render:formContainer
j_idt8:j_idt14:j_idt8:j_idt14
j_idt8:j_idt8
javax.faces.ViewState:5745528596111747358:4434500632200422253
```

On the second click I got only 5 post params
```
javax.faces.partial.ajax:true
javax.faces.source:j_idt8:j_idt14
javax.faces.partial.execute:j_idt8:j_idt14
javax.faces.partial.render:formContainer
j_idt8:j_idt14:j_idt8:j_idt14
```

Now I checked the file "core.ajax.js" again I found an interesting problem. In your send method you are trying to read the form element of the element. 

```
if (cfg.formId) {
	// Explicit form is defined
	form = PrimeFaces.expressions.SearchExpressionFacade.resolveComponentsAsSelector(cfg.formId);
}
else {
	// look for a parent of source
	form = $(PrimeFaces.escapeClientId(sourceId)).closest('form');

	// source has no parent form so use first form in document
	if (form.length === 0) {
		form = $('form').eq(0);
	}
}
```
The paramter cfg.formId is set but the method `PrimeFaces.expressions.SearchExpressionFacade.resolveComponentsAsSelector(cfg.formId);`
returns an undefined object. (because it dosnt exist in the client side dom tree anymore)

So it is possible to do following?
```
if (cfg.formId) {
	// Explicit form is defined
	form = PrimeFaces.expressions.SearchExpressionFacade.resolveComponentsAsSelector(cfg.formId);
}

if (form === null || form.length === 0) {
	// look for a parent of source
	form = $(PrimeFaces.escapeClientId(sourceId)).closest('form');

	// source has no parent form so use first form in document
	if (form.length === 0) {
		form = $('form').eq(0);
	}
}
```

With this code-change I always get 7 post params and the view scope will not be destroyed.

Sorry for my first idea to fix the problem.. I hope you will check this post.
BR
Lukas

**Comment by tandraschko** [comment]
It would be possible but it's just a dirty hack. 
That means that the rendered form of the initial view is not in the DOM anymore and the remoteCommand should not be executed.

**Comment by Berger1994** [comment]
Ok, thank you for your time and your fast response.

For the first solution, I will override your method in my project so that the problem is fixed for me. For a good solution, i will change my "update" structure with remote commands so that the problem should not occur.
