### ISSUE TITLE
Ajax events after dataExporter broken in 6.0.7

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#1906]
We're in the process of upgrading from Primefaces to 6.0.7 and ran into an issue with exporting datatables and then performing ajax requests afterwards.

I created a simple, reproduceable example below. In Primefaces 6.0.6 and earlier, exporting the datatable and then sorting works just fine.

In Primefaces 6.0.7, exporting the datatable and then sorting does not work.

I don't know for sure but I wonder if it's related to #1849.

Edit: Upon further investigation, changing the button to an h:commandButton makes it work just fine, which again seems to point to the discussion you guys had in #1849. Unfortunately in our actual application, we use a combination of p:splitButton and p:menuItem to provide a variety of different export options, so we don't have the option at the moment to use h:commandButton.

Here's the simple example:

```
<h:form>
	<p:commandButton value="Export" ajax="false">
		<p:dataExporter type="xlsx" target="testTable" fileName="test" />
	</p:commandButton>
	<p:dataTable id="testTable" var="row" value="#{testController.letters}">
		<p:column sortBy="#{row}">
			<h:outputText value="#{row}" />
		</p:column>
	</p:dataTable>
</h:form>
```

```
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

@ViewScoped
@Named
public class TestController implements Serializable {
	private static final long serialVersionUID = 1L;
	private List<String> letters = Arrays.asList("a", "b", "c");
	public List<String> getLetters() {
		return letters;
	}
}
```

**Comment by tandraschko** [comment]
@mertsincan do you have time to check this?
AFAICS this.nonAjaxPosted is NEVER set to false again. This breaks the whole ajax things?!

**Comment by tandraschko** [comment]
IMO i would remove the onPost js stuff, window unload SHOULD be enough. Not sure.
