### ISSUE TITLE
Menu item outcome link doesn't evaluate navigation rule parameter value

### ISSUE THREAD

**Issue by AndrewShwaika** [primefaces/primefaces#1915]
[OutcomeTargetRenderer.patch.txt](https://github.com/primefaces/primefaces/files/606266/OutcomeTargetRenderer.patch.txt)
## 1) Environment
- PrimeFaces version: 6.0.8
- Does it work on the newest PrimeFaces version? no
- Application server + version: Glassfish 4.1
- Affected browsers: all

## 2) Expected behavior

If navigation case in faces-config.xml has view-param value expression it should be evaluated

## 3) Actual behavior

Outputs as written

Class com.sun.faces.renderkit.html_basic.OutcomeTargetRenderer from org.glassfish/javax.faces-2.2.13 has method addNavigationParams with such evaluation, lines 218-230.

Supposed patch is attached

**Comment by Rapster** [comment]
Please provide a PR instead
