### ISSUE TITLE
Autocomplete on search sends the hole form

### ISSUE THREAD

**Issue by sergiyuvarov** [primefaces/primefaces#1918]
## 1) Environment
- PrimeFaces version: 6.0

## 2) Expected behavior
Autocomplete has to send only its parameters on search.

## 3) Actual behavior
Autocomplete sends all fields in the form.

## 4) Solution
Just add  "partialSubmit: true" to options in the PrimeFaces.widget.AutoComplete.search()

**Comment by tandraschko** [comment]
use p:ajax event="query" partialSubmit="true".

**Comment by sergiyuvarov** [comment]
Thanks for answer.
It can be used as a workaround but it seems that such behavior isn't looked as expected.

**Comment by kukel** [comment]
or configure to use `partialSubmit="true"` on a global level

**Comment by tandraschko** [comment]
sure, partialSubmit=true as default would be great but it would be great in general.
We just don't do this to be compatible with JSF API and to not introduce unexpected behaviors.
If you don't process other components, there is no real performance loss (just if you use edge mobile connection or something)
