### ISSUE TITLE
datatable: p:columns does not longer work with inline cell editor

### ISSUE THREAD

**Issue by regenduft** [primefaces/primefaces#1919]
# IMPORTANT 

This bug is obviously caused by the bad labeled change 
https://github.com/primefaces/primefaces/issues/1869
which adds LATE LOADING to the cell editor.

So this is a nice, desireable but large change - and the new behaviour of having late loading for ALL cell editors cannot be disabled.
(in opposite of all other late loading features in primefaces which can be diabled mostly with an attribute like dynamic="false")

The cell editor does now no longer work together with p:columns

## 1) Environment
working version: Primefaces 6.0.7

NOT Working anymore with Primefaces 6.0.8 and 6.0.9

## 2) Expected behavior

CellEditor with h:selectOneMenu inside p:columns (yes, p:columns with an s at the end):
Saving after selection in drop down should work

## 3) Actual behavior

After selection of any value in the drop down, the value NULL is saved

## 4) Steps to reproduce

Upgrade from Primefaces 6.0.7 to Primefaces 6.0.8

## 5) Sample XHTML
		  	<p:dataTable
		  		editable="true" editMode="cell" 
		  		id="dt_libraries_report" widgetVar="dt_#{tv_items}_edit"
		  		value="#{manageSubmissionsBean.editableLibraries}" 
		  		var="editableLibrary" rowKey="#{editableLibrary}" rowIndexVar="editRowIndex"
					paginator="true" 
		  		selection="#{manageSubmissionsBean.selectedEditableLibraries}" selectionMode="multiple" >

      	<p:columns value="#{manageSubmissionsBean.indexReadOrderNumbersNew}" var="indexReadOrderNumber" columnIndexVar="i"  selectRow="false" toggleable="false">
	        </f:facet>
			<p:cellEditor>
				<f:facet name="output">
							<h:outputText 
								rendered="#{not empty editableLibrary.indexes[i].identifier}"
								value="#{editableLibrary.indexes[i].identifier}: " />
				</f:facet>
				<f:facet name="input">
						<h:selectOneMenu value="#{editableLibrary.indexes[i]}" converter="#{indexConverter}"
							<f:selectItem itemValue="#{null}" itemLabel="[empty]"/>
							<f:selectItems value="#{manageSubmissionsBean.allIndexes}" var="o" itemLabel="#{o.identifier}" itemValue="#{o}" />
							<p:ajax partialSubmit="true" process="@this" async="true" update="@parent:@parent:@parent:@parent:indexTypePnl"/>
						</h:selectOneMenu>
				</f:facet>
			</p:cellEditor>
      	</p:columns>
	</p:datatable>

## 6) Sample bean

 class ManageSubmissionsBean{
   EditableLibrary[] editableLibraries = new EditableLibrary[]{new EditableLibrary()};
   Index[] allIndexes = new Index[]{new Index("a"), new Index("b"), new Index("c"};

   getIndexReadOrderNumbersNew(){ returns new Integer[] {1};}
   Index[] getAllIndexes() {
      return allIndexes;
   }
   EditableLibrary[] getEditableLibraries(){
      return editableLibrary;
   }
 }

 class EditableLibrary{
   Index[] indexes = new Index[]{new Index("d")};
   Index[] getIndexes() {
      return indexes;
   }
 }

 class Index{
   String identifier;
   public Index(String s) {
     this.identifier = s;
   }
   String getIdentifier(){
      return identifier;
   }
 }

**Comment by firsthour** [comment]
Can confirm we're having the same issue with the upgrade to 6.0.8. Ours is broken with a p:inputTextarea inside the input facet.

**Comment by regenduft** [comment]
Additionally, we are having the problem, that the first click into a cell editor does now take more than 1 second because lazy-loading the cell editor contents does take so long, as rendering the whole page.

Thus, we needed to rollback to 6.0.7. now, and can only go ahead when primefaces makes the lazy-loading of the cell editor disable-able.

**Comment by firsthour** [comment]
This is a showstopper for us and no comments from the devs worry me.

**Comment by mertsincan** [comment]
Fixed for next release. Default behavior is without lazy.
Added cellEditMode attribute to DataTable on 6.0.11. https://github.com/primefaces/primefaces/issues/1957
