### ISSUE TITLE
DataTable selection checkbox is not working without a theme

### ISSUE THREAD

**Issue by z3r9** [primefaces/primefaces#192]
Sorry for my english. I use primefaces without a theme.

In `web.xml`:

```
<context-param>
    <param-name>primefaces.THEME</param-name>
    <param-value>none</param-value>
</context-param>
```

And I use empty `primefaces.css`.

I use `dataTable` with `selectionMode`:

```
<h:form id="form">
    <p:dataTable id="testTableId" var="testTable" value="#{testMB.entityList}"
                 selection="#{testMB.selectedList}" rowKey="#{testTable.id}"
                 tableStyleClass="table table-hover table-bordered">

        <p:column selectionMode="multiple" style="width:16px;text-align:center"/>
        <p:column headerText="testName">
            #{testTable.name}
        </p:column>                            

        <f:facet name="footer">
            <p:commandButton process="testTableId" update="@form" icon="ui-icon-search" value="test"/>
        </f:facet>
    </p:dataTable>

    <ui:repeat value="#{testMB.selectedList}" var="selectedList" id="ddddddddddd">
        <h:outputText value="#{selectedList.id} - #{selectedList.name}"/>
    </ui:repeat>
</h:form>
```

I click on a `checkbox` and click on `commandButton` test. But it is not working. List `#{testMB.selectedList}` is empty.

But if I click on a row (not on the `checkbox`) and for multiple selection I use `ctrl` then it is working.

If I use default theme, then `checkbox` is working.

**Comment by cagataycivici** [comment]
What do you mean by I use empty primefaces.css?

**Comment by z3r9** [comment]
I created empty `primefaces.css` in  `\webapp\resources\primefaces\primefaces.css`. And primefaces is useing the file automaticly. I use the css file for integration with my theme.

**Comment by cagataycivici** [comment]
That will break the structural css of primefaces components and cause anomalities like this. Closing as I believe this is due to your modifications to core not considered as a bug from our side.
