### ISSUE TITLE
DataTable: lazy loading pagination error

### ISSUE THREAD

**Issue by sergi-mm** [primefaces/primefaces#1921]
I've detected an issue related to pagination when using lazy loading in datatable. The problem is the following: starting by the example of showcase: http://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml, if we add a button to delete the records one by one, if you are for instance in page 2, when all record of this page have been deleted, the pagination "brokes" and displays page 1 with empty data.

Assume that the button "Delete" calls a method called "deleteCar(Car car)" which deletes the car object from the list (or directly from database), and then update the datatable, firing again the load() method from LazyDatamodel.

```html
<p:dataTable var="car" value="#{dtLazyView.lazyModel}" paginator="true" rows="10"
                 paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                 rowsPerPageTemplate="5,10,15" selectionMode="single" selection="#{dtLazyView.selectedCar}" id="carTable" lazy="true">
        <p:ajax event="rowSelect" listener="#{dtLazyView.onRowSelect}" update=":form:carDetail" oncomplete="PF('carDialog').show()" />
        <p:column headerText="Id" sortBy="#{car.id}" filterBy="#{car.id}">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Year" sortBy="#{car.year}" filterBy="#{car.year}">
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Brand" sortBy="#{car.brand}" filterBy="#{car.brand}">
            <h:outputText value="#{car.brand}" />
        </p:column>
        <p:column headerText="Color" sortBy="#{car.color}" filterBy="#{car.color}">
            <h:outputText value="#{car.color}" />
        </p:column>
<p:column headerText="Color" sortBy="#{car.color}" filterBy="#{car.color}">
            <p:commandButton value="Delete" action="#{dtLazyView.deleteCar(car)}" update="carTable">
</p:commandButton>
        </p:column>
    </p:dataTable>
```

In the example, an IndexOutOfBoundsException will be also thrown, when deleting the last record of page 2, variable "first" will pass a value of 10 (assuming rows per page is 10) and a subList from 10 to 10-1...

**Comment by FastainCS09** [comment]
I tried the same code of as mentioned above and tries to delete all enteries from last page of the datatable,but there is neither a pagination break nor any exception error.

Version : Primefaces 6.0
Browser : Chrome latest.

**Comment by sergi-mm** [comment]
I've forked the Showcase project (https://github.com/sergi-mm/showcase) and made the changes I explained in the commit (https://github.com/sergi-mm/showcase/commit/9f48e7b2fd8653c061f52d0a71faa9d1488cac1f). 

Please @FastainCS09, download the code, go to Datatable - Lazy page and try to delete the last row of the last page (the 3rd), you will see that the paginator updates with page 2 of 2 but no rows are displayed. Certainly, the IndexOutOfBoundsException is thrown but then catched and then returns  a sublist `return data.subList(first, first + (dataSize % pageSize));`.

**Comment by FastainCS09** [comment]
Ok i will take a look into it,

Osama Nasir
Snr.Software Engineer
BS(CS),FAST-NU

**Comment by sergi-mm** [comment]
Hi @FastainCS09 , did you test the code? Could you reproduce the error?

**Comment by FastainCS09** [comment]
Sorry I runed it,and was able to produce that error but didn't have the
time to fix it becuase I was totally stuck at some work,so i was not able
to fix it.but i will try to fix it  this week and then get back to
you.Sorry again

Osama Nasir
Snr.Software Engineer
BS(CS),FAST-NU

**Comment by sergi-mm** [comment]
Hello, there ware any improvement with this issue? I wish I could help, but apart from the sample code, I don't know how to fix it.

**Comment by tandraschko** [comment]
Not sure if it fixes your problem but i always ´do something like this in my AbstractLazyDataModel:

```java
`    @Override
    public List<T> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters)
    {
        long rowCount = do your select count with filters included
        setRowCount(rowCount);
        
        if (rowCount  > 0 && first >= rowCount) {
            int numberOfPages = (int) Math.ceil(rowCount * 1d / pageSize);
            first = Math.max((numberOfPages - 1) * pageSize, 0);
        }

        .....
```

**Comment by sergi-mm** [comment]
Thanks @tandraschko, that works! But maybe it should be a good idea to perform this correction in the datatable paginator, to avoid each project that use Primefaces to copy-paste this code snippet.

What do you think?

**Comment by tandraschko** [comment]
Not sure, we always have something similar in UIData#calculateFirst. Try to analyze it why we need it a second time in the datamodel.

**Comment by Rapster** [comment]
I couldn't reproduce this issue (unless you have a reproducer so I can try, meanwhile I updated the LazyCarDataModel of the showcase) @tandraschko I'm actually surprised it's up to the user to call `setRowCount` while DataTable could easily take care of this?

**Comment by Rapster** [comment]
Ok I reproduced the issue in lazy mode (didn't try in default mode): delete all rows of the last page the paginator updates with page 19 of 19 but no rows are displayed.

**Comment by tandraschko** [comment]
@christophs78 @melloware anyone interessted in adding a integration test? i would fix the issue then

**Comment by christophs78** [comment]
I'll add a test later this week.

**Comment by christophs78** [comment]
Please look at https://github.com/primefaces/primefaces/pull/7672- maybe this issue was already fixed during some other refactoring.

**Comment by tandraschko** [comment]
@Rapster can you review if the tests cover this issue?

**Comment by christophs78** [comment]
Figured out how to break it. Integrationtest ist updated. Ready to get fixed. ;-)

**Comment by tandraschko** [comment]
i see
maybe the best idea is to add a new abstract method:

```int count(Map<String, FilterMeta> filterBy);```

which will be called before load:

```
int rowCount = lazyModel.count(getActiveFilterMeta());
lazyModel.setRowCount(rowCount);

calculateFirst();

.....

List<?> data = lazyModel.load(first, rows, getActiveSortMeta(), getActiveFilterMeta());
```

**Comment by tandraschko** [comment]
so load doesnt need to call setRowCount and no user has to fix "first" by the custom code above

**Comment by christophs78** [comment]
Yep. That's a technical clean solution. We just have to make a breaking  change to LazyDataModel one more time.
Other workarounds like calling #load a second time when it returns no rows and page>1 may be a compromise but not ideal.

**Comment by tandraschko** [comment]
@Rapster WDYT`?

**Comment by Rapster** [comment]
The idea of having another method is not that bad but forces the user to execute another request, while depending the framework (JPA, JOOQ, Spring etc.) or search engine (ES, ACS etc) you can have both information in one request. So -1 on my side for another method

Something I'm working on, is to introduce a new load method that would return a structure, explicit enough so the user knows what he has to do (and deprecate the other load method) e.g:

```java
// default impl. for backward compatibility
public Result<T> load(UIComponent comp, int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
    List<T> result = load(first, pageSize, sortBy, filterBy);
    return new Result<>(result, getRowCount());
}
```

**Comment by christophs78** [comment]
It's IMO more complicated.
71 rows, pagesize 10, active page 8
row 71 gets deleted
Data Table does not know this yet.
Calls load with something like first = 70 (or 71?)
So load returns no rows. That's our current issue.

**Comment by christophs78** [comment]
We made breaking changes to LazyDataModel with V8 and V10. At some point we should finally nail it. At least for some years.

**Comment by Rapster** [comment]
Yes I started to investigate, and figuring out a clean solution. ( What I just mentioned is a solution to a statement you mentioned... Somewhere 😅)

**Comment by tandraschko** [comment]
i think you need 2 selects
1) one count how much entities are available for the filters and apply it to rowCount (e.g. 71)
2) one which really selects the entities only the for the current page (first - pageSize) (e.g. 1 - 20)

and you need to calculate rowCount + first BEFORE call #load

and not sure if you can even combine both results in one query call with simple sql

**Comment by christophs78** [comment]
I agree to some degree to @Rapster argument. We use SpringData. In straight-forward usecases you call one SpringData-repository-method. And this does the count SQL-statement and the pagination SQL-statement. (Or maybe JPA does this for SpringData.)

**Comment by christophs78** [comment]
Added kind of hack to integrationtest-PR. (Can throw it out when we agree on some other solution.)
I´m myself also a bit of wonky between doing a technical clean solution introducing a performance-degredation for something like 99,8% of usecases and adding a hack.
(Apache Solr seems to be simlar to Elastic Search in terms of query handling. You request one page of results for some query statement. As result you get the requested page and the total count of hits.)

**Comment by tandraschko** [comment]
Feels dirty
I think a count select is a more clean solution

**Comment by christophs78** [comment]
Yep, is dirty.
Trade-off of technical clean count method is runtime performance as @Rapster noted.
Whatever tradeoff is the right one.

**Comment by Rapster** [comment]
The idea is there, but calling twice as you can imagine is a no go for me, unless we have no other options

@tandraschko Not sure where you're getting at. Basically, the datamodel "length" is modified outside of his scope, at this point  `DataTable#first` is no longer "synchronized" with the component. @christophs78 gives a good description in https://github.com/primefaces/primefaces/issues/1921#issuecomment-894673337

Being said, quick thought, what if LazyDataModel had a delete method that would return the number of elements deleted, we could automatically update `DataTable#first`? Would that be terrible to have such method in LazyDataModel? Following the same logic as this ticket, maybe we have the save problem with adding a new row no?

**Comment by christophs78** [comment]
There also may be other users modifiying data. (eg adding or removing rows to the DB behind)

**Comment by Rapster** [comment]
Good point, my last comment won't solve this problem

**Comment by Rapster** [comment]
I think I understand @tandraschko point now... Indeed we'll most probably need this new method actually 😉 What bothers me is that it'll be systematically called, maybe this method could be optional to impl. and return getRowCount() by default?

**Comment by tandraschko** [comment]
I think its quite mandatory to implement it, especially if filtering is used
For non-filtering a getRowCount impl would bei currently enough

also it makes completely sense to split up the current behavior (that ppl call setRowCount in #load), much cleaner and everyone knows that you need to implement this 2 methods

**Comment by Rapster** [comment]
Not mandatory but to avoid another long debate, just make it abstract, and i'll simply return getRowCount in our impls.

**Comment by tandraschko** [comment]
implemented it now, please review
i like the change but 2 things are still not perfect
1) count returns int, not long; but we cant change it as UIData is based on int
2) #count is not called for DataView etc. but this code is in general not aligned with DataTable

**Comment by christophs78** [comment]
We should align DataView and (when we dont remove them) DataList and DataGrid.
Think we had some integrationtests for DataList. I‘ll try to bring them back as DataView-tests.
