### ISSUE TITLE
UIRepeat wrong state restored for UIInput

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#1922]
PF 6.0

Already reported as JSF issue as the default UIRepeat is affected. Tested it with p:repeat and it has the same behavior:

https://java.net/jira/browse/JAVASERVERFACES-4202

**Comment by tandraschko** [comment]
Please ping us when it's fixed in Mojarra, we will port the fix then.

**Comment by fanste** [comment]
It seems to be fixed but I don't know where Mojarra has its code repository.

**Comment by erickdeoliveiraleal** [comment]
here: https://github.com/javaserverfaces/mojarra/commits/master ?

**Comment by erickdeoliveiraleal** [comment]
https://github.com/javaserverfaces/mojarra/issues/4206

**Comment by tandraschko** [comment]
The issue is still open, so it's not fixed?!

**Comment by fanste** [comment]
It was fixed in the JIRA on java.net.. They migrated to github without migrating the whole ticket (comments, state, etc) I don't know if it got fixed in MOJARRA_2_2X_ROLLING or MOJARRA_2_1X_ROLLING

**Comment by tandraschko** [comment]
i see
it would be great if you could provide a link to the commit somehow!

**Comment by fanste** [comment]
According to the commit history of UIRepeat.java it should be in MOJARRA_2_2X_ROLLING. But no guarantee, that it is really up to date. But the date and commiter looks reasonable.

https://github.com/javaserverfaces/mojarra/commit/c14d6179e73e0309f5407d37200259ce99f3eb24

**Comment by tandraschko** [comment]
bugfixing by deleting code is always great :D
Could you try those changes on PF and test it?

**Comment by fanste** [comment]
I've just stumbled over this error again and tested the latest Mojarra 2.2.18 on WildFly 10.1.0.Final. But the bug still seems to exist :(

Opened mojarra issue again: javaserverfaces/mojarra#4390

Maybe someone has an idea..

**Comment by lagar84** [comment]
@fanste : I am not 100% sure, but mojarra new home should be here: https://github.com/eclipse-ee4j/mojarra

**Comment by fanste** [comment]
Moved ticket to eclipse-ee4j/mojarra#4535

**Comment by tandraschko** [comment]
@fanste can you check if its fixed in 2.3.2 like mentioned by rapster in the linked issue? (and maybe provide a PR with the changes made to mojarra UIRepeat)

**Comment by tandraschko** [comment]
@Rapster said it's fixed in 2.3.2 and i updated to newest UIRepeat now. So i think it's fixed.
