### ISSUE TITLE
Galleria.js Uncaught TypeError: Cannot read property 'left' of undefined on empty image list

### ISSUE THREAD

**Issue by jlerbsc** [primefaces/primefaces#1924]
# IMPORTANT 
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.

## 1) Environment
- PrimeFaces version: 5.3
- Does it work on the newest PrimeFaces version? I don't know
- Application server + version: Tomcat8
- Affected browsers: Chrome 54.0

## 2) Expected behavior

No javascript error in JS console.

## 3) Actual behavior
When a galleria component contains no image, there is a Uncaught TypeError: Cannot read property 'left' of undefined
    at c.select (/javax.faces.resource/galleria/galleria.js?ln=primefaces&v=5.3:1:3826)
    at c.next (/javax.faces.resource/galleria/galleria.js?ln=primefaces&v=5.3:1:4580) in the navigator console
..

## 4) Steps to reproduce

Use showcase

## 5) Sample XHTML
..

## 6) Sample bean

Replace images list to empty list

@ManagedBean
public class ImagesView {

	private List<String> images;

	@PostConstruct
	public void init() {
		//		this.images = new ArrayList<String>();
		//		for (int i = 1; i <= 2; i++) {
		//			this.images.add("nature" + i + ".jpg");
		//		}
		this.images = Collections.EMPTY_LIST;
	}

	public List<String> getImages() {
		return this.images;
	}
}

..

**Comment by jlerbsc** [comment]
Could you fix it in version 5.3 please?

**Comment by mertsincan** [comment]
I can add it into 5.3.x version. (Next version -> 5.3.18)

**Comment by jlerbsc** [comment]
Ok Thanks. Can i download it through maven repository?

**Comment by tandraschko** [comment]
Elite versions are not available via maven and you need to purchase elite access.

**Comment by mertsincan** [comment]
Too fast :) Thomas 👍

**Comment by jlerbsc** [comment]
Ok thanks but it seems that primefaces elite download is limited to 5.3.14!!!

**Comment by jlerbsc** [comment]
Ok I will wait for the update  5.3.18

**Comment by kukel** [comment]
You can always apply the patch yourself
