### ISSUE TITLE
TreeTable sortBy attribute

### ISSUE THREAD

**Issue by vanjalee** [primefaces/primefaces#1926]
This is actually a change request, and not an issue.

## 1) Environment
- PrimeFaces version: 5.3.14
- Does it work on the newest PrimeFaces version? No
- Application server + version: JBoss EAP 6.4
- Affected browsers: All

## 2) Expected behavior and Actual behavior
Although the issue #1199 has been resolved, and the sort event can now be handled, there still exists an obstacle when one tries to save the table state in session. One still must denote that in this case, neither  @SessionScoped annotation is allowed, nor use of any LazyTableModels. If one tries to implement "default sorting" behavior in a TreeTable, there are "sortBy" and "sortOrder" attributes that can achieve this. However, the "sortBy" attribute works differently then the "sortBy" attribute in DataTable. 

In DataTable they accept SortMeta object(s), that can be prepared in advance (for example in @postConstruct annotated methods), and that can therefore be used to achieve both default sorting being triggered inside of the java bean, and sorting settings being saved in a session map, throughout the whole session, without using more then one @SessionScoped bean. 

In TreeTable, "sortBy" uses ValueExpression, and that can not be set on servers side: it depends solely on TreeTable variable. Because of this, it can only be set inside .xhtml file -> they are being handled in a different JSF lifecycle phases then DataTable attributes.

If one could use SortMeta objects for a "sortBy" TreeTable attribute, and if the TreeTableRenderer sorting functions would work the same way as the DataTableRenderer sorting functions, desired functionality could be achieved. This would also open a possibility of having multi-sorting features in TreeTables as well as in DataTables in the future.

## 4) Steps to reproduce
Problem can be reproduced in any test app having TreeTable, therefore no .xhtml or bean samples are needed.

Best Regards,
Vanja

**Comment by tandraschko** [comment]
A PR is very welcome here.

**Comment by tandraschko** [comment]
Will be handled in #6592
