### ISSUE TITLE
PickList: Drag&Drop issue on mobile devices

### ISSUE THREAD

**Issue by lanse011** [primefaces/primefaces#1927]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: Wildfly 10
- Affected browsers: All

## 2) Expected behavior
Drag&Drop Feature should be editable for p:picklist component.
...

## 3) Actual behavior
Drag&Drop Feature is always activated for p:picklist component.
..

## 4) Steps to reproduce
http://forum.primefaces.org/viewtopic.php?f=26&t=44044
.. 

## 5) Sample XHTML
http://forum.primefaces.org/viewtopic.php?f=26&t=44044
..

## 6) Sample bean
http://forum.primefaces.org/viewtopic.php?f=26&t=44044
..

**Comment by melloware** [comment]
Closing this as duplicate of https://github.com/primefaces/primefaces/issues/1308

Which calls for general mobile support of picklist
