### ISSUE TITLE
Filter TreeTable

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1929]
It would be nice to filter a treeTable like it's done for DataTable. Just to recall: http://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml

**Comment by kukel** [comment]
'should' be possible? Or 'would be nice if it was possible'? ;-)

**Comment by Rapster** [comment]
You're right ;)

**Comment by melloware** [comment]
Linking to https://github.com/primefaces/primefaces/issues/1377
