### ISSUE TITLE
PrimeFaces.createWidget() should not require repeating the widgetVar twice

### ISSUE THREAD

**Issue by kito99** [primefaces/primefaces#193]
This is the typical pattern for instantiating a PrimeFaces component in JS:

```
PrimeFaces.cw("InputText","widget_frmLogin_user_loginid_txt",{id:"frmLogin:user_loginid:txt",widgetVar:"widget_frmLogin_user_loginid_txt"});
```

Note that the widgetVar is repeated twice because PrimeFaces.createWidget() expects it as a parameter, but it's also included inside the cfg parameter. This adds a lot of unnecessary characters in larger pages. I'd like to see something like this:

```
PrimeFaces.cw("InputText",{id:"frmLogin:user_loginid:txt",widgetVar:"widget_frmLogin_user_loginid_txt"});
```

And just have createWidget() use cfg.widgetVar.

**Comment by cagataycivici** [comment]
Makes sense, will check Kito. Thanks.

**Comment by tandraschko** [comment]
Thanks for the hint. I invented the widgetVar in the cfg object cause of widget detaching logic on the client.
So we could remove the param from PrimeFaces.cw and take this from the cfg object.

**Comment by cagataycivici** [comment]
@tandraschko, We don't need to make so many changes, why not just just add the widgetVar add cw function.

``` javascript
PrimeFaces.cw("InputText","widget_frmLogin_user_loginid_txt",{id:"frmLogin:user_loginid:txt"});
```

``` javascript
createWidget : function(widgetConstructor, widgetVar, cfg, resource) { 
   cfg.widgetVar = widgetVar;
```

We just need to remove all widgetVar: '' from renderer classes.

**Comment by cagataycivici** [comment]
Review 008ba8a  please.

**Comment by tandraschko** [comment]
I'm sure the unit tests will fail now.
I also changed only 3 primary related files. Other changed files was the unit tests and the widget which still doesn't use the WidgetBuilder.

**Comment by cagataycivici** [comment]
Unit tests passed, I don't see any issues right now.

**Comment by tandraschko** [comment]
Already fixed it again :)

**Comment by cagataycivici** [comment]
Ah ok :)
