### ISSUE TITLE
DataExporter issue with filenames containing spaces on FireFox

### ISSUE THREAD

**Issue by rdebusscher** [primefaces/primefaces#1930]
Content-disposition : attachment;filename=some file name.xls

With Firefox it is downloaded as *some*

There should be " around the filename.

**Comment by tandraschko** [comment]
Would be great if you could provide a PR. Thanks.

**Comment by rdebusscher** [comment]
@tandraschko Code changes pushed. Added to 6.1 release

**Comment by tandraschko** [comment]
even better! :D
