### ISSUE TITLE
MultiViewState for DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#1931]
Implement MultiViewState feature so that DataTable can remember its state across views, initially support following for 6.0.10;

- Page
- Sort
- Filter
- Selection

On second version, consider;
- Column Reordering
- Column Resizing
- Row Expansion
- Column Visibility

**Comment by kukel** [comment]
Coooool great feature... What about column visibility? (column toggler)

**Comment by cagataycivici** [comment]
@kukel, that is also for round 2.

**Comment by kukel** [comment]
Great!!! Does it work with using the same page in multiple tabs?
