### ISSUE TITLE
Filtering DataTable on page load

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#1932]
Add filters and globalFilter attributes to datatable so that DT can use these information to display data as filtered. Filters should be a list of FilterState objects, each FilterState object keeps columnKey and filterValue. Note that page author does not need to use filterValue to display the filter values as they can be retrieved from filters.

**Comment by schlebe** [comment]
It would be interesting to have an example in DEMO section on Primefaces Web site !
