### ISSUE TITLE
Primefaces 5.3.17 problem with galleria when there is no image to display

### ISSUE THREAD

**Issue by jlerbsc** [primefaces/primefaces#1933]
## 1) Environment
- PrimeFaces version: 5.3.17
- Does it work on the newest PrimeFaces version? i don't know
- Application server + version: Tomcat 8
- Affected browsers: chrome

## 2) Expected behavior
When the images collection is empty, the galleria component must be displayed
...

## 3) Actual behavior
Nothing is displayed

Generated html looks like

    <div id="j_idt7" class="ui-galleria ui-widget ui-widget-content ui-corner-all">
        <ul class="ui-galleria-panel-wrapper"></ul>
    </div>
..

## 4) Steps to reproduce
Use galleria showcase and change imageGraphic from primefaces namespace to jsf/html namespace

    <p:galleria value="#{imagesView.images}" var="image" panelWidth="500"
		panelHeight="313" showCaption="true">
        
        <h:graphicImage value="demo/images/nature/#{image}" alt="Image Description for #{image}"
			title="#{image}" />
    </p:galleria>
.. 

## 5) Sample XHTML

..

## 6) Sample bean

    @ManagedBean
    public class ImagesView {

	private List<String> images;

	@PostConstruct
	public void init() {
		this.images = new ArrayList<String>();
		this.images = Collections.EMPTY_LIST;
	}

	public List<String> getImages() {
		return this.images;
	}
    }
..

**Comment by FastainCS09** [comment]
This thing doesn't occurs in primfaces 6.0 version latest.Even if the images are empty ,the component remains there.

**Comment by jlerbsc** [comment]
Thanks for your response this is a good news but I am using 5.3.17 :-(

**Comment by tandraschko** [comment]
@mertsincan is 5.3 elite still maintained? Otherwise i would close it as invalid.

**Comment by tandraschko** [comment]
@mertsincan will close it for now. Please reopen if you would like to fix this in the 5.3 branch.
