### ISSUE TITLE
TreeTable nodes does not work properly into a p:dialog

### ISSUE THREAD

**Issue by darayam2** [primefaces/primefaces#1934]
# IMPORTANT 
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.

## 1) Environment
- PrimeFaces version: **6.0x**
- Does it work on the newest PrimeFaces version?: **No**
- Application server + version: **GlassFish Server 4.1.1**
- Affected browsers: **Google Chrome Versión 54.0.2840.99 m, ;  Microsoft Edge 25.10586.0.0** 

## 2) Expected behavior
When click on the row toggler of the treetable node expand de child´s rows of the toggled row (that is a normal behaviour but does not work if use a treetable into a p:dialog)
...

## 3) Actual behavior
If a treeTable is into a p:dialog, and click on the rowToggler icon (similar to a triangle >) the row does not expand its child in any level
..

## 4) Steps to reproduce

1. Include an xhtml file before de </h:form> of the principal xhtml file where you can use a button or a commandlink to open a p:dialog in the same file or into another xhtml file. 

2. The treetable is into the p:dialog decribed in the first step 

3. When click on the row togglers of the table does not work the row expanssion

4. Use a bean to populate the primefaces component "treetable" with a method than pop up the p:dialog.

5. Is possible use the primefaces especification in:

http://www.primefaces.org/showcase/ui/data/treetable/basic.xhtml

but putting the treetable into a ***p:dialog***

.. 

## 5) Sample XHTML

**This is in a file called filePoppup.xhtml:**

***
```ruby
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<p:dialog  xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html" 
                id="popVista" widgetVar="popVista" header="Tree Table in a dialog"  closable="true" draggable="true" minimizable="true" closeOnEscape="true" maximizable="true" showEffect="pop" hideEffect="pop" width="1900" height="800" resizable="true" >
    <h:panelGrid columns="2" style="margin:10px 18px; font-size: 12px;">
        <p:commandButton id="toggler" type="button" value="Columnas Visibles" style="float:right; display:inline-block; width: 150px;"  icon="ui-icon-calculator" />
        <p:columnToggler datasource="table1" trigger="toggler" id="togCol" />
    </h:panelGrid>
    <p:treeTable id="table1" value="#{beanTable.root}" var="data1" styleClass="tableStyle" selectionMode="single" emptyMessage="No hay datos para mostrar" expandMode="row" >
            <f:facet name="header"  class="tableHeader">
                <h:outputText value="Detalle de transacciones"></h:outputText>
            </f:facet>
        <p:column rowspan="1" headerText="Concepto" style="width:100px"  >
            <h:outputText value="#{data1.concepto}" />
        </p:column>
        <p:column rowspan="1" headerText="Descripción Concepto" style="width:500px">
            <h:outputText value="#{data1.descripcion}" />
        </p:column>
        <p:column rowspan="1" headerText="Valor 1">
            <h:outputText value="#{data1.valor1}" />
        </p:column>
        <p:column rowspan="1" headerText="Valor 2">
            <h:outputText value="#{data1.valor2}" />
        </p:column>
        <p:column headerText="Valor 3">
            <h:outputText value="#{data1.valor3}" />
        </p:column>
        <p:column headerText="Valor 4">
            <h:outputText value="#{data1.valor4}" />
        </p:column>
        <p:column headerText="Valor 5">
            <h:outputText value="#{data1.valor5}" />
        </p:column>
        <p:column rowspan="1" headerText="Valor 6">
            <h:outputText value="#{data1.valor6}" />
        </p:column>
    </p:treeTable>
</p:dialog>
```
***
..

## 6) Sample bean

The file called filePopup.xhtml is pop up from the bean with this method:

***
```ruby
public void openTable(ActionEvent event)
    {
        RequestContext c = RequestContext.getCurrentInstance();
        root = fillTable();
        open=-1;
        c.update("formTable:popVista");
        c.execute("PF('popVista').show()");
    }
```
***
but the bean is on a principal xhtml file called ***index.xhtml*** with a datatable that has a final column with a commandlink with this code:

***
```ruby
<h:form id="formTable">
(...)
<p:commandLink title="Detail" styleClass="ui-icon ui-icon-search"  ajax="true" actionListener="#{beanTable.openTable}" process="formTable">
            <f:attribute name="aomarchivo" value="#{archivosAomEmpresa}" />
</p:commandLink>
(...)
      <ui:include src="archivo.xhtml" />
</h:form>   
```
***

When p:commandLink is clicked the popup opens and shows the table into the ***p:dialog***, but the table does not work.
..

**Comment by Rapster** [comment]
Please, make an effort on how you present your code https://help.github.com/articles/creating-and-highlighting-code-blocks

**Comment by darayam2** [comment]
Thank you Rapster i did the homework,

**Comment by Rapster** [comment]
I just test it: TreeTable works inside dialog. Don't you see any error in your browser console?

**Comment by kukel** [comment]
off-topic: you mix JSF 2.2 and pre 2.2 namespaces: 

    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"

Better to align them!

**Comment by darayam2** [comment]
kukel i have this

**http://www.primefaces.org/gettingStarted**

they put this:

```
xmlns:h="http://java.sun.com/jsf/html"  
xmlns:f="http://java.sun.com/jsf/core"  
xmlns:p="http://primefaces.org/ui
```
and delete xmlns:ui="http://java.sun.com/jsf/facelets"

**Comment by darayam2** [comment]
Rapster, thanks for your help, no, the browser console does not have errors

The problem is when you call the dialog from an external xhtml file using the tag 

`<ui:include src="archivo.xhtml" />`

and make into the bean a calling to that file using:

`RequestContext c = RequestContext.getCurrentInstance();`
` c.update("form:popXhtml");`
` c.execute("PF('popXhtml').show()");`

**Comment by Rapster** [comment]
Provide a sample (provided in #1943) please, so it can be assessed

**Comment by kukel** [comment]
@darayam2: yes, but you MIX xmlns:h="http://xmlns.jcp.org/jsf/html" (jsf 2.2) and xmlns:f="http://java.sun.com/jsf/core" (pre jsf 2.2)

**Comment by melloware** [comment]
Closing as OP was asked for a reproducible sample and did not provide it. 

Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
