### ISSUE TITLE
Dialog Framework support for PrimeFaces Mobile

### ISSUE THREAD

**Issue by cseabra** [primefaces/primefaces#194]
It doesn't works only on primefaces mobile. I didn't found any constraint in user guide about this particularity. Is there any example with pfmobile?

**Comment by cagataycivici** [comment]
It is not supported in mobile right now.

**Comment by melloware** [comment]
Primefaces has announced it is deprecating mobile in 6.2 and removing in 6.3 so this ticket should be closed as WontFix.

**Comment by tandraschko** [comment]
PrimeFaces Mobile will be deprecated  in 6.2 and removed in 6.3 ( see https://www.primefaces.org/primefaces-6-2-roadmap/)
Therefor i will close this issue as won't fix. If you will provide a PR to fix this issue until 6.2 RC1, i can merge it.
