### ISSUE TITLE
p:inputNumber doesn't work in conjunction with SeleniumIDE

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#1940]
## 1) Environment
- PrimeFaces version: 6.0.9
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat
- Affected browsers: FireFox with Selenium IDE 2.9.1

## 2) Expected behavior
When recording user actions on a page with SeleniumIDE Recorder and entering a value into a p:inputNumber field this typing should be registered and added to the Recorder's command list similar to 'type   myFieldId   myEnteredValue'. When replaying the recorded actions this command 'type ...' should put the reccorded value into the number field again.

## 3) Actual behavior
There are 2 issues:
1. the recording of the entered value doesn't function. This is an issue of used JS library autoNumeric which I have found there and have to be fixed there (see https://github.com/BobKnothe/autoNumeric/issues/199).

2. when I add the command 'type   myFieldId   myEnteredValue' by hand and replay it with SeleniumIDE it doesn't function: the value appears in the field but isn't copied to internal hidden input element of p:inputNumber ==> the value is lost when refreshing the page.
This is a PrimeFaces issue. Reason is a missing call of $this.copyValueToHiddenInput() in case of 'onchange' for the visible input field. I have temporarily fixed it for me by adding an onchange handler which does it explicitly:
```
        this.inputExternal.on('change', function(e) {
            if (window['_Selenium_IDE_Recorder']) {
            	$this.copyValueToHiddenInput();
            }});		
```
I'm not sure about potential side effects of this, so I do the copy action in case of running with SeleniumIDE Recorder only.

## 4) Steps to reproduce
See description above. 

## 5) Sample XHTML
arbitrary usage of p:inputNumber

## 6) Sample bean
arbitrary usage of p:inputNumber which stores it's value in a backing bean

**Comment by tandraschko** [comment]
The second issue should be fixed already - please give it a try.
As we can't fix the first issue, i will close it for now.
