### ISSUE TITLE
Provide built-in project bug template

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#1943]
@tandraschko You'll find attached a sample of what could be the future "bug web-app" so user can reproduce their problem, and so "we" can review it. This is a first draft, if you have anything you want to add, please share your thoughts.

Basically, it runs with jetty and contains an `index.html` and a managed-bean :) With time, we could provide some mocks, like dummy collection for testing datatable _(as used in showcase)_, it's a just a thought...

Let me know what you think (I wrote a README.md you'll find in the zip)

P.S: it's already configured for Eclipse (Neon) and IntelliJ (16.3)

[primefaces-bug-template.zip](https://github.com/primefaces/primefaces/files/625845/primefaces-bug-template.zip)

**Comment by mertsincan** [comment]
Thanks @Rapster. Added a sample project to github; https://github.com/primefaces/primefaces-test

**Comment by Rapster** [comment]
Please modify the ISSUE_TEMPLATE.md so people know about this

**Comment by tandraschko** [comment]
If you provide a PR, i will apply it

**Comment by Rapster** [comment]
PR provided #1972
