### ISSUE TITLE
Timeline lazyload not working since 6.0.8

### ISSUE THREAD

**Issue by PereBG** [primefaces/primefaces#1946]
Hello,

I'm using primefaces ELITE, and sice version 6.0.8 the lazyload event of timeline is not working, I have tested with versions 6.0.7, 6.0.8, 6.0.9 and 6.0.10. It works with 6.0.7 and older but not with the other ones, I have tested it with mozzilla firefox browser.

I'm firing the lazyload event from a remote command and the timeline is inside a pe:layoutPane, I'm using primefaces extension version 6.0.0

Sample code

```
	<pe:layoutPane position="center" id="centerPane" minHeight="570" >	
		                 ...	
				<p:timeline .... widgetVar="timelineJS"  >
				 
				    <p:ajax event="lazyload" update="@none" listener="#{timelineBean.onLazyLoad}" />
					<p:ajax event="rangechanged" listener="#{timelineBean.onRangeChanged}" update="@this"/>
					
	
				  ...
				 
				</p:timeline>			
				
				<p:remoteCommand process="@this" delay="800" name="loadEventsDelayed" oncomplete="PF('timelineJS').fireLazyLoading();"/>
</pe:layoutPane>
```
	

I'm calling the remoteCommand loadEventsDelayed() to trigger the ajax event, but the request never reaches the bean.

Thanks

**Comment by mertsincan** [comment]
I couldn't replicate this issue. Please attach a sample maven project or a runnable test case with; test.xhtml, TestBean.java. I did not see a difference between 6.0.7 and 6.0.10

**Comment by PereBG** [comment]
Hello @mertsincan ,

We have a debug pont at `timelineBean.onLazyLoad()` method of our bean, as you can see at the example above we call that method from the remoteCommand, the point is that if we call `PF('timelineJS').fireLazyLoading(); ` to make the ajax request to our bean, the request never reaches our bean and the debug point is never triggered. We invoke the remoteCommand by clicking on the zoom button. 
Those are the parameters that we inform in the timeline:

```
<p:timeline  var="vRregActDate"	editable="false" end="#{timelineBean.endDate}"	groupsChangeable="false" groupsOnRight="false" id="timeline" max="#{timelineBean.maxDate}" min="#{timelineBean.minDate}"
					minHeight="550" preloadFactor="0.2" selectable="true" showButtonNew="false" showNavigation="false" start="#{timelineBean.startDate}"
					timeZone="UTC" value="#{timelineBean.timeline}" widgetVar="timelineJS" zoomMax="#{timelineBean.zoomMax}" timeChangeable="false"
					zoomMin="#{timelineBean.zoomMin}" animate="false" animateZoom="false" zoomable="false" snapEvents="false" stackEvents="true" >
```

**Comment by mertsincan** [comment]
Hi @PereBG,

Thanks for the sample code. But, I still couldn't replicate this issue. Can you please attach a runnable maven project for us to replicate? 
Note: You can use this test project; https://github.com/mertsincan/test

**Comment by PereBG** [comment]
Hello @mertsincan,

I've forked your project and modified it to replicate the issue. It's at https://github.com/PereBG/test
If you change the primefaces version from 6.0.8 to 6.0.7 the timeline will display results.

Thanks in advance.

**Comment by Rapster** [comment]
@mertsincan Create a repository for #1943 is a good idea indeed...
