### ISSUE TITLE
SelectOneRadio: no selection when disabled

### ISSUE THREAD

**Issue by wernerchr** [primefaces/primefaces#195]
In v5.2.1 pre-selected items of selectOneRadio buttons will not be selected when they are disabled (disabled attribute is set at p:selectOneRadio / p:radioButton)

**Comment by cagataycivici** [comment]
Do you use custom layout? Does it work without custom layout? I'm trying to replicate.

**Comment by cagataycivici** [comment]
Replicated and fixed.
