### ISSUE TITLE
RowGrouping for DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#1950]
Introduce two ways for grouping;

- With row span on a grouping column
- With a separate row that acts as a subheader for the rows below

Deprecate subtable as it becomes unnecessary.

**Comment by fanste** [comment]
> Deprecate subtable as it becomes unnecessary.

I don't think, that subtables should be deprecated, as they are usefull when you already have pre-grouped data in you programm code. Instead I would suggest that a planned feature (6.0.12 when I'm right?) of row-grouping will be extended to subtables: toggleable grouping

The group-header is defined by p:columnGroup and all rows that have to be toggled are defined by the subtable.

**Comment by mohammedhassan01** [comment]
so i am having restriction on using PF Version 4 so , is there any work around to make this feature in PF 4

**Comment by jpangamarca** [comment]
Subtables should not be deprecated, there are many valid use cases that are not satisfied with the modeling that row grouping requires, e.g. when children objects in a list in the parent object don't have a reference to the parent. Creating flat lists duplicates information.
