### ISSUE TITLE
JQplot Chart: DateAxis automatically adjusts displayed time to local time

### ISSUE THREAD

**Issue by heapifyman** [primefaces/primefaces#1954]
# IMPORTANT 
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? no
- Application server + version: tomcat 8.5 (spring boot)
- Affected browsers: Chrome, Safari

## 2) Expected behavior
I would like the data axis in my line chart to display the UTC timestamps of my data points
...

## 3) Actual behavior
Primefaces / jqplot automatically adjusts timestamps to my browser's (OS') time zone. E.g. a data point's timestamp of 14:00 UTC will be displayed as 15:00 (UTC + 1), which is my local time zone.
When changing the computer's time zone, the displayed timestamps in the line chart get adjusted accordingly.
..

## 4) Steps to reproduce
1. Create a line chart with at least two data points, where each data point has a UTC timestamp and a double as y-value.
2. Use DateAxis as x-Axis
```
DateAxis dateAxis = new DateAxis();
dateAxis.setMin(minDate.toInstant().toEpochMilli());
dateAxis.setMax(maxDate.toInstant().toEpochMilli());
dateAxis.setTickFormat(""%d.%m.%Y %H:%M"");
return dateAxis;
```
.. 

## 5) Sample XHTML
```
<p:chart type="line" model="#{detailsController.temperatureModel}" responsive="true"/>
```
..

## 6) Sample bean
```
LineChartSeries lineChartSeries = new LineChartSeries();
points.forEach(point -> lineChartSeries.set(point.getFirst(), point.getSecond()));
LineChartModel lineChartModel = new LineChartModel();
lineChartModel.addSeries(lineChartSeries);
lineChartModel.setResetAxesOnResize(false);
lineChartModel.getAxes().put(AxisType.X, xAxis);
```
..

**Comment by kukel** [comment]
How does a plain jqplot behave? If the data in the page (use 'view source' is in UTC and it is actually displayed in local time, it is a jqplot issue and not a PF one

**Comment by heapifyman** [comment]
Hm, that seems to be the case. If I pass a formatted date string like `2016-12-09 00:15:00+00:00` to the `lineChartSeries` (instead of the milliseconds), the same string appears in view source. 

But on the page it is displayed as `2016-12-09 01:15` - so UTC + 1

**Comment by heapifyman** [comment]
However, these date strings are part of the `data` array, which is passed to `PrimeFaces.cw()` function. So could it be that the time is adjusted in there somehow?
example:
``` 
type="text/javascript">$(function(){PrimeFaces.cw('Chart','widget_j_idt96',{id:'j_idt96',type:'line',responsive:true,data:[[["2016-12-09 00:00:00+00:00",23.09],["2016-12-09 00:15:00+00:00",23.57],...
```

**Comment by heapifyman** [comment]
I have also reported this to jqplot https://github.com/jqPlot/jqPlot/issues/116
with little hope because almost none of the issues in the last few months has received any response. Is the project still alive?

**Comment by heapifyman** [comment]
Hello and a happy new year!
I still have not found any solution to this problem. Does anyone have a clue how to solve this issue?
Or can anyone confirm that it is indeed an issue with underlying jqplot?

**Comment by melloware** [comment]
Closing this issue as its tracked in the 3rd party library where the problem originates and we have the new Charts.js based charts which I don't think have this issue.
