### ISSUE TITLE
Support for Ehcache 3.x as Cache Provider

### ISSUE THREAD

**Issue by robert7k** [primefaces/primefaces#1958]
Currently, Primefaces 6 only supports the outdated 2.x versions of Ehcache. Support for Ehcache 3.x (see http://www.ehcache.org/) would be great.

**Comment by tandraschko** [comment]
Where is the pull request? :P

**Comment by tandraschko** [comment]
@robert7k ping!

**Comment by tandraschko** [comment]
org.primefaces.cache.EHCache3Provider
