### ISSUE TITLE
SelectManyMenu with filtering selects wrong items with shift key

### ISSUE THREAD

**Issue by jnr25** [primefaces/primefaces#197]
Open http://www.primefaces.org/showcase/ui/input/manyMenu.xhtml
1. try "ck" in advanced box. 
2. Select all three elements using SHIFT key
3. press "Submit"
4.  the result is not 3, but is 24 elements. Even the ones which has no "ck" in label.

Shouldn't it select only the visible items, not the ones which are in between visible?

if you use CTRL for selection, then the result is 3.

**Comment by cagataycivici** [comment]
Replicated and fixed.
