### ISSUE TITLE
InputTextarea: browser scrolling lags on iOS Google Chrome

### ISSUE THREAD

**Issue by wandyer** [primefaces/primefaces#1973]
# IMPORTANT 
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to get a solution to your problem.

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: 
- Affected browsers: Google Chrome

- iOS Version: 10.2
- Google Chrome Version: 55.0.2.2883.79

## 2) Expected behavior
The page should scroll smoothly and normally past the p:inputTextarea component.
...

## 3) Actual behavior
What actually happens is the page sort of "lags" while scrolling on a page that has any p:inputTextarea.
..

## 4) Steps to reproduce
The showcase of InputTextarea reproduces the issue: http://www.primefaces.org/showcase/ui/input/inputTextarea.xhtml

But only reproduces on iOS using Google Chrome.
.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by melloware** [comment]
@wandyer Is this still an issue now that IOS is up to 12.1?

**Comment by wandyer** [comment]
It seems to work fine now on iOS 12.0 and Google Chrome

**Comment by melloware** [comment]
Awesome thanks for checking and closing the ticket!
