### ISSUE TITLE
CSS alignment improvements for radio and checkbox

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#1975]
Apply vertical align middle to checkbox-radio and their labels.

**Comment by cnsgithub** [comment]
Since 6.0.12 the checkbox's itemLabel does render below the checkbox. Is this an intended change? In 6.0.11 it was aligned next to it. 

It looks awkward in my opinion

	<p:selectBooleanCheckbox value="true" itemLabel="Hello World!"></p:selectBooleanCheckbox>

Renders as:

[✓]
Hello World!

**Comment by mertsincan** [comment]
Fixed for 6.0.13.  #1989
