### ISSUE TITLE
SelectBooleanCheckbox: better selenium recording compatibility

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#1980]
## 1) Environment
- PrimeFaces version: 6.0.9
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat
- Affected browsers: FireFox with Selenium IDE 2.9.1

## 2) Expected behavior

When recording user actions on a page with SeleniumIDE Recorder and clicking a checkbox rendered via p:selectBooleanCheckbox to toggle the "checked" state this click should be registered and added to the Recorder's command list correctly. When replaying the recorded actions the toggling of the "checked" state should work correctly.

## 3) Actual behavior

The recording of the click event adds two click commands: one for the hidden input field and one for the span element with style class 'ui-chkbox-icon'. Example:
```
click id=ctrl_vip_input
click //div[@id='ctrl_vip']/div[2]/span

```
When replaying the commands the checkbox is toggled twice which ends in the same "checked" state as before running the commands.

## 4) Steps to reproduce

See description above.

## 5) Sample XHTML

arbitrary usage of p:selectBooleanCheckbox

## 6) Sample bean

arbitrary usage of p:selectBooleanCheckbox which stores it's value in a backing bean

## Temporary workaround

I have put following code in an overwritten version of SelectBooleanCheckbox.init (after calling the original init function) to have a workaround for this issue:

```
oriSelectBooleanCheckboxInit.call(this, cfg);
if (!this.disabled) {
	var $this = this;
	// PrimeFaces has installed an onclick handler in oriSelectBooleanCheckboxInit call
	var oriClickHandler = jQuery._data(this.box[0]).events['click'][0].handler;
	
	this.box.off('click.selectBooleanCheckbox').on('click.selectBooleanCheckbox', function(e) {
     		if (window['_Selenium_IDE_Recorder']) {
    			$this.toggle();
       		} else {
      			oriClickHandler.call(e);
       		}
	});
}
```

**Comment by melloware** [comment]
Using the latest SeleniumIDE Recorder this is no longer the case.  Now when you click this it records only one click..
```
click css=.ui-state-hover > .ui-chkbox-icon
```
![image](https://user-images.githubusercontent.com/4399574/86951161-21985600-c11f-11ea-976e-75e5d21116f9.png)
