### ISSUE TITLE
required attribute not working for p:fileUpload when mode="simple"

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#1981]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? Not with 6.0
- Application server + version: Tomcat 8
- Affected browsers: Firefox 50.0.2

## 2) Expected behavior
If my <p:fileUpload> has both mode="simple" and required="true", validation should fail and the form submit should not take place.

## 3) Actual behavior
The form submit is performed anyway, ignoring the required="true" attribute (and of course the requiredMessage attribute).

## 4) Steps to reproduce

Create a skinned simple and required fileUpload, then try to submit the form.

## 5) Sample XHTML

    <p:fileUpload id="registryUpload"
      value="#{bean.zipFile}"
      allowTypes="/(\.|\/)(zip)$/i" sizeLimit="524288000" mode="simple"
      skinSimple="true" invalidFileMessage="Invalid file type"
      messageTemplate="Can't upload file {name}. It must be a .zip file"
      required="true" requiredMessage="You must select the ZIP file to upload"
      update="registryUploadMessage" />
    <p:message id="registryUploadMessage" for="registryUpload" />

## 6) Sample bean

    public class MyBean {
      private UploadedFile zipFile;
    
      // getter/setter omitted
    }

**Comment by Rapster** [comment]
Reproduced on showcase 6.1-SNAPSHOT. Works with `<h:commandButton />` though. Could it be related to this #665?

**Comment by Rapster** [comment]
Conversion _(such as validation I guess)_ does not work either with `<p:commandButton />`

**Comment by Rapster** [comment]
Strangely, it works in my project ^^

**Comment by tandraschko** [comment]
Would you please provide a complete, stripped, xhtml with form and everything else?

**Comment by tandraschko** [comment]
Works fine - you just need to declare enctype="multipart/form-data" on the form.
