### ISSUE TITLE
Tree: The dragging of node to the right or down boundary of the page breaks content of the page

### ISSUE THREAD

**Issue by qstpss** [primefaces/primefaces#1983]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No.
- Application server + version: Tomcat 8.0
- Affected browsers: All

## 2) Expected behavior
The page should not to goes up (if we dragging the node to the down boundary of the page) and should not goes left  (if we dragging the node to the right boundary of the page) 

## 3) Actual behavior
 
The page goes up (if we dragging the node to the down boundary of the page) and goes left  (if we dragging the node to the right boundary of the page) 

## 4) Steps to reproduce

Just drag the node to the right or down boundary of the page from this [link ](http://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml)(showcase)

## 5) Sample XHTML
<p:tree id="tree1" value="#{treeDNDView.root1}" var="node" selectionMode="single" selection="#{treeDNDView.selectedNode1}"
                draggable="true" droppable="true" >
            <p:treeNode>
                <h:outputText value="#{node}" />
            </p:treeNode>
        </p:tree>

## 6) Sample bean

it's does not matter...

**Comment by kukel** [comment]
This is a low priority issue imo, since if the node is 'dropped' everything becomes normal again. It only happens during dragging

**Comment by qstpss** [comment]
Yes, but it is a bad behavior.

**Comment by jxmai** [comment]
PR: #2939

**Comment by tandraschko** [comment]
Thanks!
