### ISSUE TITLE
Child components of datatable are not correctly processed

### ISSUE THREAD

**Issue by cklaffke** [primefaces/primefaces#1984]
## 1) Environment
Primefaces 6.0
jsf-api 2.2.13
Wildfly 10
Chrome + Firefox

## 2) Description
I use an InputText in a Primefaces datatable. When I submit my data (POST) for the first time, everything works properly. But when I do another POST-request on the same view the data in the InputText is not updated.
I did a lot of debugging and found out that the problem lies in processing the children of the datatable. In the class UIData the children are obtained by "getIterableChildren" (Line 362) (By the way, the grandChildren are obtained by using "getChildren". Shouldn't children and grandchildren be obtained by the same method?).

```
protected void processChildren(FacesContext context, PhaseId phaseId) {
        int first = getFirst();
        int rows = getRows();
        int last = rows == 0 ? getRowCount() : (first + rows);
        
        for(int rowIndex = first; rowIndex < last; rowIndex++) {
            setRowIndex(rowIndex);

            if(!isRowAvailable()) {
                break;
            }
            
            for(UIComponent child : this.getIterableChildren()) {
                if(child.isRendered()) {
                    if(child instanceof Column) {
                        for(UIComponent grandkid : child.getChildren()) {
                            process(context, grandkid, phaseId);
                        }
                    }
                    else {
                        process(context, child, phaseId);
                    }
                }
            }            
        }
    }
```

In the dataTable class the attribute "iterableChildren" is filled with members of "getChildren", but only if it is null:

```
@Override
    protected List<UIComponent> getIterableChildren() {
        if(iterableChildren == null) {
            iterableChildren = new ArrayList<UIComponent>();
            for(UIComponent child : this.getChildren()) {
                if(!(child instanceof ColumnGroup)) {
                    iterableChildren.add(child);
                }
            }
        }
        
        return iterableChildren;
    }
```

In my opinion, the problem is that the attributes "iterableChildren" and "children" are not in sync at the second request. As a workaround i derived a custom class from dataTable and overwrote "getIterableChildren" as follows:

   ```
 @Override
    protected List<UIComponent> getIterableChildren() {
        return getChildren();
    }
```

As you can see i simply use getChildren instead and the InputText-fields are processed properly.

**Comment by Rapster** [comment]
Your forgot to post your XHTML... Do you use `ColumnGroup` in your example?

**Comment by cklaffke** [comment]
I created a small example to reproduce the behaviour.

XHTML:
```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
</h:head>

<h:body>
	<h:form>
		<p:dataTable
				binding="#{dtExampleBean}"
				rowIndexVar="index"
				var="x">
			<p:column headerText="Input">
				<h:inputText value="#{dtExampleBean.exampleInput[index]}"/>
			</p:column>
		</p:dataTable>
		<h:commandButton action="#{dtExampleBean.post()}" value="Send post request"></h:commandButton>

	</h:form>
</h:body>

</html>
```
Bean:

```
import org.primefaces.component.datatable.DataTable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by cklaffke on 26.12.2016.
 */
@ManagedBean
@ViewScoped
public class DtExampleBean extends DataTable{

    private String[] exampleInput;

    public String[] getExampleInput() {
        return exampleInput;
    }

    public void setExampleInput(String[] exampleInput) {
        this.exampleInput = exampleInput;
    }

    @PostConstruct
    public void init(){
        List dummyList = new ArrayList<>();
        dummyList.add(new String());
        this.setValue(dummyList);

        exampleInput = new String[1];
    }

    public void post(){
    }
}
```

There are two details that seemed to be important. First I made a binding of a derived datatable. Second the input field is not directly related to the collection inside the value of the datatable. Otherwise the problem did not occur.

Maybe you recognize that I introduce "var=x" in the XHTML and never use it. Without this definition I get an IllegalArgumentException, apprently when using "rowIndexVar". This also doesn't seem to be correct.

Best regards
Carsten

**Comment by cklaffke** [comment]
As an explanation on using my example:
Enter something and submit. The first request will update the input field. Then change the input and submit again. The changes will not be applied.

**Comment by tandraschko** [comment]
Please avoid binding. Binding in ViewScoped will always break something.
Also binding to the bean itself seams weird.
If you can reproduce this without binding or with another way of binding (to a member variable in a RequestScoped bean...)
