### ISSUE TITLE
Open table context menu on left click

### ISSUE THREAD

**Issue by ssachtleben** [primefaces/primefaces#1985]
See topic. Is it possible? 

We dont use  the selection, we just use the context menu but I dont think all people get that they have to right click, so I would like to open the context menu on left and right click.

**Comment by Rapster** [comment]
1. At least: RTFM and try to come up with a solution ;)
2. Use forum for this
3. Respect the template which has been set up

**Comment by tandraschko** [comment]
Questions -> Forum
