### ISSUE TITLE
java.lang.IllegalArgumentException thrown when adding a UIMenuItem to a dynamic menu

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#199]
If you create a dynamic menu with a UIMenuItem, the following exception is thrown:

> java.lang.IllegalArgumentException: 0
>   at javax.faces.component.UIComponentBase.validateId(UIComponentBase.java:586) ~[javax.faces-2.2.10.jar:2.2.10]
>   at javax.faces.component.UIComponentBase.setId(UIComponentBase.java:412) ~[javax.faces-2.2.10.jar:2.2.10]
>   at org.primefaces.model.menu.BaseMenuModel.generateUniqueIds(BaseMenuModel.java:56) ~[primefaces-5.2.jar:5.2]
>   at org.primefaces.model.menu.BaseMenuModel.generateUniqueIds(BaseMenuModel.java:44) ~[primefaces-5.2.jar:5.2]
>   at org.primefaces.model.menu.DefaultMenuModel.generateUniqueIds(DefaultMenuModel.java:28) ~[primefaces-5.2.jar:5.2]
>   at >org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:110) ~[primefaces-5.2.jar:5.2]

This is because `UIMenuItem` extends `UIComponentBase`, whose `setId` calls `validateId`, which fails because it doesn't like a number to be set as the first id character.
On the other hand, `org.primefaces.model.menu.BaseMenuModel.generateUniqueIds()` passes `null` as a seed to the overloaded `org.primefaces.model.menu.BaseMenuModel.generateUniqueIds(List<MenuElement>, String)`, so ids are generated as pure numbers. This causes the problem.

I'm trying to use a `UIMenuItem` instead of a `DefaultMenuItem` because I want to add a `FileDownloadActionListener`, but `DefaultMenuItem` doesn't have any `addActionListener` method.

**Comment by cagataycivici** [comment]
You can't add UIMenuItem to MenuModel as it does not belong to MenuModel and they can't be mixed. DefaultMenuItem must be used instead. Workaround is implementing custom file download functionality via command option of DefaultMenuItem. I know it is not the best solution but a valid one.

**Comment by mauromol** [comment]
Yes, but that workaround can become a real pain, because it's extremely limited (only accepts an EL expression string). Today I spent 4 hours to implement that on a use case that would have worked perfectly well in minutes if just `DefaultMenuItem` supported the `addActionListener` method... after all, if I'm programmatically building a dynamic menu it's likely that I also need to attach actions to it programmatically...

Anyway, thanks for the explanation.

**Comment by cagataycivici** [comment]
Another working is not using MenuModel and built the UI programmatically by only using components like UIMenuItem and Submenu. In that case you can add fileDownloadActionlistener.

**Comment by mauromol** [comment]
Tried that way too, but had unresolvable problems with iterating to build the menu items inside a data table cell. The data table cursor variable (specified with "var" attribute) was evaluating correctly when defining the menuButton or menu components, but then was resolving to null as soon as I started to iterate with either c:forEach or ui:repeat to build the nested menuItems/subMenus inside the menu/menuButton.
Very poor experience with this use case, as I said I lost half a work day to write a simple menu with items to start file downloads...

**Comment by cagataycivici** [comment]
Then I'd suggest using MenuModel and use setCommand("#{expr}") where expr does something like

http://grepcode.com/file/repository.primefaces.org/org.primefaces/primefaces/2.1/org/primefaces/component/filedownload/FileDownloadActionListener.java

It is a couple of lines to do export, you can also just create a file download servlet and use a get request with menuitem's url property.

**Comment by mauromol** [comment]
This is what I've done, thank you. The tedious part was to create a string-based mapping between menu items and the actual files they corresponded to, so that the method in #{expr} could find the right file to serve to the user. Such mapping was implicit at the menu model construction time, indeed.

So please, consider adding more power to `DefaultMenuItem` to handle these cases, if possible.

**Comment by cagataycivici** [comment]
We'll consider a  way to make it easier, thank you for the feedback.
