### ISSUE TITLE
Calendar: behind a modal dialog get focus and datepicker appears

### ISSUE THREAD

**Issue by maruTA-bis5** [primefaces/primefaces#1991]
## 1) Environment
- PrimeFaces version: 6.0 (Community)
- Does it work on the newest PrimeFaces version? yes
- Application server + version: GlassFish Community Edition 4.1.1
- Affected browsers: IE11, Edge, Firefox, Google Chrome (latest version)

## 2) Expected behavior
When the modal dialog is displayed, any field behind the dialog don't get focus.

## 3) Actual behavior
When the modal dialog is displayed, `<p:calendar>` get focus and datepicker will be displayed.
We can select a date and set selected date into `<p:calendar>` field.

### For Firefox & Chrome
1. Open modal dialog
2. Click brrowser's address bar
3. Press the tab key until datepicker appears
4. When select a date, selected date into calendar field

### For Firefox, Chrome, IE11, and Edge
1. Open modal dialog
2. Press Tab or Shift + Tab untill datepicker appears
3. When select a date, selected date into calendar field

## 5) Sample XHTML
- sandbox.xhtml
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
	<h:form>
		<p:calendar />
		<div>
		<p:commandButton value="Dialog Framework" icon="fa fa-apple"
			actionListener="#{sandbox.onClickButton}" />
		</div>
		
		<div>
			<p:commandButton value="&lt;p:dialog&gt;" type="button" onclick="PF('modalDlg').show()" />
			<p:dialog header="dialog" widgetVar="modalDlg" modal="true">
				<p:inputText value="hogehoge" />
				<h:outputLabel value="hogehogehogehoge" />
			</p:dialog>
		</div>
	</h:form>
</h:body>
</html>
```
- theDialog.xhtml
```xml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Dialog Framework</title>
</h:head>
<h:body>
	<h:form>
		<h:outputText value="Hello Dialog Framework!" />
		<p:commandButton value="Close" actionListener="#{sandbox.closeDF}" />
	</h:form>
</h:body>
</html>
```

## 6) Sample bean
```java
@ManagedBean
public class Sandbox {

    public void onClickButton() {
        Map<String, Object> options = new HashMap<>();
        options.put("modal", true);
        RequestContext.getCurrentInstance().openDialog("theDialog", options, null);
    }

    public void closeDF() {
        RequestContext.getCurrentInstance().closeDialog(null);
    }
}

```

**Comment by jxmai** [comment]
> PrimeFaces version: 6.0 (Community)
Does it work on the newest PrimeFaces version? yes

@maruTA-bis5 I tried to run your sample using 6.1 Snapshot and I can reproduce this bug. Please change your description to *No*.

---

In short, the modal dialog cannot prevent focus if user starts **tabbing from the browser's address bar**.

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/21524751/3cf28896-ccde-11e6-94f1-dcef03b4c645.png)

**Comment by geekdiv** [comment]
any solution for this prevent datepicker focus? I face same issue after update primeface.

**Comment by jxmai** [comment]
There is workaround available. Please try the following script.

```js
//<![CDATA[
$(':input:visible').last().on('keydown', function (e) {
    if (e.keyCode == 9 && e.shiftKey == false) {
        e.preventDefault();
    }
});
		
//]]>
```

Basically we only need to prevent tabbing from the address bar.

**Comment by geekdiv** [comment]
@jxmai I workaround focused on first inputtext like this ( it's work for my application. it's not general workaround ) ;)

`<p:focus for="name"/>`

**Comment by jxmai** [comment]
@geekdiv p:focus can only define the default focus field but it should not be able to prevent us tabbing from the address bar :confused: If it works for your app that's great for your purpose. The sample of this issue has a calendar as the first input field, so I don't think it is a general workaround. Correct me if I am wrong.

**Comment by geekdiv** [comment]
upps sorry @jxmai  it's work for my app. I edit  my comment :)

**Comment by Blindworks** [comment]
Any new solutions for this shit?
I have a Dialog and it only contains p:calendar elements.

One year and this issue is still open? Really?

**Comment by melloware** [comment]
Test case proving the issue: 
[pf-1991.zip](https://github.com/primefaces/primefaces/files/2721888/pf-1991.zip)

**Comment by christophs78** [comment]
@tandraschko: DatePicker (which replaces Calendar) has the same issue. I reproduced this with
https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml.
![grafik](https://user-images.githubusercontent.com/10461942/82723707-173a0e00-9cd1-11ea-9e6d-7fb6772e330f.png)

I´ll expect PrimeNG has the same issue, because you can do the "tab-thing" there too.
![grafik](https://user-images.githubusercontent.com/10461942/82723789-a9daad00-9cd1-11ea-9acc-231e0647de2d.png)

Maybe we should look wether we can fix this from the modal-dialog-side.

**Comment by christophs78** [comment]
https://getbootstrap.com/docs/4.5/components/modal/ does not have this issue:
![grafik](https://user-images.githubusercontent.com/10461942/82723892-28374f00-9cd2-11ea-97ca-8ecb2bc71267.png)

Maybe we can learn something from Bootstrap. :-)

**Comment by christophs78** [comment]
Maybe we should build a reproducer for PrimeNG/PrimeReact/PrimeVue and look what happens. :-)

**Comment by christophs78** [comment]
https://primefaces.org/primevue/showcase/#/dialog and https://primefaces.org/primereact/showcase/#/dialog do not seem to have this issue. How do they solve this?

**Comment by melloware** [comment]
@christophs78 Similar to this request too. https://github.com/primefaces/primefaces/issues/1325  Where a use wants everything behind the modal to be keyboard inaccessible.

**Comment by melloware** [comment]
So here is PF modal dialog mask:
```css
.ui-dialog-mask {
    position: fixed;
    width: 100%;
    height: 100%;
}
```

And here is Primereact:
```css
.p-dialog-mask {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: none;
    pointer-events: none;
}
```

Also found this: https://stackoverflow.com/a/51295654/502366

**Comment by melloware** [comment]
Here is an example of truly the only way to fix this issue and it can't be done by PF it has to involve the developer using a `<main>` in their HTML and including the dialog outside of it and a combination of JQuery.
Runnable: 
[modal-dialog.zip](https://github.com/primefaces/primefaces/files/5145640/modal-dialog.zip)

```xml
<h:body>
    <main>
        <h:form>
            <p:calendar />
            <div>
                <p:commandButton value="Open Dialog" type="button" onclick="PF('modalDlg').show()" />
            </div>
        </h:form>
    </main>
    <div>
        <h:form>
            <p:dialog header="dialog" widgetVar="modalDlg" modal="true" 
					onShow="$('main').attr('aria-hidden', true).css({'pointer-events': 'none'});$('main :focusable').addClass('modal-disabled').attr('tabindex', -1);" 
					onHide="$('main').removeAttr('aria-hidden').css({'pointer-events': 'auto'});$('.modal-disabled').removeClass('modal-disabled').attr('tabindex', 0);">
                <p:inputText value="hogehoge" />
                <h:outputLabel value="hogehogehogehoge" />
            </p:dialog>
        </h:form>
    </div>
</h:body>
```

**Comment by melloware** [comment]
Documentation has been updated with complete example: https://primefaces.github.io/primefaces/8_0/#/components/dialog?id=modal
