### ISSUE TITLE
Attribute converter is missing on outputLabel tag definition on taglib.xml

### ISSUE THREAD

**Issue by IvanCCruz** [primefaces/primefaces#1992]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: Do not apply
- Affected browsers: Do not apply
- Affected IDE: Netbeans 8.2

## 2) Expected behavior

On IDE xhtml editor attribute converter on tag outputLabel must not be flagged as an error.

## 3) Actual behavior

Any occurrence of attribute converter on a outputLabel tag is flagged as a error. Error message is "Attribute converter is not defined for component outputLabel" (translated back from Portuguese to English).

## 4) Steps to reproduce

On Netbeans 8.2 create a new web application.
Add a new xhtml file.
Insert a outputLabel with converter attribute.

## 5) Sample XHTML

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
....
    </h:head>

    <h:body>
...
                                <p:dataTable value="#{segundaViaPagadorBean.titulos}" var="titulo" paginator="true">

....
                                    <p:column headerText="Insc Beneficiario">
                                        <p:outputLabel value="#{titulo.inscricaoBeneficiario}" converter="formatadorCNPJCPF"/>
                                    </p:column>

....

                                </p:dataTable>
....

    </h:body>
</html>

## 6) Sample bean

Do not apply.

**Comment by tandraschko** [comment]
Please provide a PR.
