### ISSUE TITLE
Timeline events displayed on wrong group after zoom

### ISSUE THREAD

**Issue by PlassJ** [primefaces/primefaces#1995]
## 1) Environment
- PrimeFaces version: 6.0.13
- Does it work on the newest PrimeFaces version? No
- Application server + version: WildFly 10.1.0
- Affected browsers: all

## 2) Expected behavior
TimelineEvents should stay in there group after zoom.

## 3) Actual behavior
TimelineEvents move to an other group after zoom.

## 4) Steps to reproduce
Showcase -> timeline -> custom 
Point mouse cursor right bevor an event (User 2, red) zoom in. (img 1)
Zoom in until events "left" the viewport. (img 2)
After some zooming the event (from User 3) moves "up". (img 3)

## 5) Sample XHTML
See showcase.

## 6) Sample bean
See showcase.

![timeline1](https://cloud.githubusercontent.com/assets/13958943/21589469/5da03864-d0f2-11e6-9817-1096ad388876.png)
![timeline2](https://cloud.githubusercontent.com/assets/13958943/21589468/5da02856-d0f2-11e6-8a10-634ef73e3884.png)
![timeline3](https://cloud.githubusercontent.com/assets/13958943/21589467/5d9fe490-d0f2-11e6-8023-981458649ddb.png)

**Comment by PlassJ** [comment]
added possible fix  #2006

**Comment by mertsincan** [comment]
Thanks for your PR.
