### ISSUE TITLE
JSF 2.3: Parameter namespace prefix does not include the separator character

### ISSUE THREAD

**Issue by ngriffin7a** [primefaces/primefaces#1997]
Parameter namespace prefixing became a standard feature in JAVASERVERFACES_SPEC_PUBLIC-790. However, unlike the vendor-specific com.sun.faces.namespaceParameters feature, the parameter prefix now has the value of UINamingContainer.getSeparatorChar(FacesContext) appended to the namespace. Rather than parameters like "javax.faces.partial.ajax" being prefixed as "portletNamespacejavax.faces.partial.ajax", this new feature will cause the parameter to be prefixed like "portletNamespace:javax.faces.partial.ajax" in a portlet environment.

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat+Pluto bundle + Mojarra 2.3
- Affected browsers: All

## 2) Expected behavior

Form submission works correctly.

## 3) Actual behavior

Form submission does not work correctly.

## 4) Steps to reproduce

A. Download the Pluto 3.0 Tomcat bundle from https://portals.apache.org/pluto/ and unzip to ~/pluto

B. Build Mojarra 2.3 from the Mojarra master branch: https://github.com/javaserverfaces/mojarra
ant clean main mvn.deploy.snapshot.local

C. Copy $HOME/.m2/repository/org/glassfish/javax.faces/$2.3.0-SNAPSHOT/javax.faces-$2.3.0-SNAPSHOT.jar pluto/tomcat/lib

D. Extract the jar, remove the META-INF/services/javax.servlet.ServletContainerInitializer file, and re-zip the jar

E. Clone the Liferay Faces Bridge API and Impl repositories:
https://github.com/liferay/liferay-faces-bridge-api
https://github.com/liferay/liferay-faces-bridge-impl

F. Build each clone:

cd liferay-faces-bridge-api
mvn clean install
cd ../liferay-faces-bridge-impl
mvn clean install

G. Build the primefaces-applicant-portlet demo for use with Apache Pluto:

cd demo/primefaces-applicant-portlet
mvn -P pluto,mojarra,tomcat clean package

H. Deploy the resulting WAR to Pluto+Tomcat:

cp target/com.liferay.faces.demo.primefaces.applicant.portlet*.war ~/pluto/tomcat/webapps/com.liferay.faces.demo.primefaces.applicant.portlet.war

I. Add the primefaces-applicant-portlet to a Pluto portal page

J. Fill out the form and click Submit

**Comment by ngriffin7a** [comment]
Pull request will be coming soon.

**Comment by ngriffin7a** [comment]
PR https://github.com/primefaces/primefaces/pull/1999

**Comment by tandraschko** [comment]
@ngriffin7a I think our JS method "extractParameterNamespace" in core.ajax.js still works as expected?

**Comment by ngriffin7a** [comment]
@tandraschko I'm researching that and will get back to you with my findings.

**Comment by ngriffin7a** [comment]
I just tried setting a breakpoint in the `createPostData` JS function and the return value of calling `extractParameterNamespace` was correct. So all is well. :)
