### ISSUE TITLE
Modal dialog should prevent body scrolling

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#200]
e.g. with adding a class to the body:

$(document.body).addClass('ui-modal');

.ui-modal { position: fixed; }

Setting overflow:hidden doesn't work on ipad.

this will improve scrollability in dialogs on tablets!

**Comment by cagataycivici** [comment]
What is .ui-modal?

**Comment by tandraschko** [comment]
just a new class to mark the body as modal. We could rename it like whatever we want :)

We could also set directly position:fixed on the body but IMO it's better via a own class.

**Comment by tandraschko** [comment]
If you would like to test it, just use this hack:

var oldEnableModality = PrimeFaces.widget.Dialog.prototype.enableModality;
PrimeFaces.widget.Dialog.prototype.enableModality = function() {
    $(document.body).css('position', 'fixed');
    oldEnableModality.apply(this,arguments);
};

var oldDisableModality = PrimeFaces.widget.Dialog.prototype.disableModality;
PrimeFaces.widget.Dialog.prototype.disableModality = function() {
    $(document.body).css('position', '');
    oldDisableModality.apply(this,arguments);
};

**Comment by cagataycivici** [comment]
I'll check, thanks.

**Comment by tandraschko** [comment]
Here is the newest version.
The override of refresh() is required cause if you update the dialog and handle show/hide via the visible flag, it must release the body scrolling again.

function preventBodyScrolling() {
    if (PrimeFaces.env.ios) {
        $(document.body).css('position', 'fixed');
    }
    else {
        $(document.body).css('overflow', 'hidden');
    }
}

function allowBodyScrolling() {
    var overlays = $(document.body).children('.ui-widget-overlay').filter("div[id$='_modal']");
    if (overlays.length === 0) {
        if (PrimeFaces.env.ios) {
            $(document.body).css('position', '');
        }
        else {
            $(document.body).css('overflow', '');
        }
    }
}

var oldEnableModality = PrimeFaces.widget.Dialog.prototype.enableModality;
PrimeFaces.widget.Dialog.prototype.enableModality = function() {
    preventBodyScrolling();
    oldEnableModality.apply(this,arguments);
};

var oldDisableModality = PrimeFaces.widget.Dialog.prototype.disableModality;
PrimeFaces.widget.Dialog.prototype.disableModality = function() {
    oldDisableModality.apply(this,arguments);
    allowBodyScrolling();
};

var oldRefresh = PrimeFaces.widget.Dialog.prototype.refresh;
PrimeFaces.widget.Dialog.prototype.refresh = function() {
    oldRefresh.apply(this,arguments);
    allowBodyScrolling();
};

**Comment by cagataycivici** [comment]
What was the problem on ipad?

**Comment by tandraschko** [comment]
if the body is scrollable and the dialog is scrollable and maybe a scrollable datatable in the dialog, too.
If you would like to scroll the datatable in the dialog, 75% of the times you try to scroll the datatable or dialog content, the body scrolls.

**Comment by tandraschko** [comment]
Also FYI overflow:hidden doesn't work on ipad, therefore the position:fixed hack is required for IOS.

**Comment by tandraschko** [comment]
overall, it improves the scrolling in overlays via touch. Maybe we should also apply this to other overlays in the future.

**Comment by cagataycivici** [comment]
Still in my todo list, will get back to you this weekend.

**Comment by cagataycivici** [comment]
Just tried this on my ipad with a modal dialog where dialog itself overflows so it is scrollable. It worked just fine, I can scroll the dialog contents without scrolling the body.

**Comment by tandraschko** [comment]
Will close it as it's currently not required for my anymore. Lets see if a user will open a similar issue.

**Comment by mauritz-lovgren** [comment]
Struggling with this as well, use case:
- modal dialog having contents that exceeds viewport on iPhone when body also contains scrollable components (dataTable or similar). When trying to scroll the modal dialog on a small device (like iPhone 4), the background is scrolled instead of the dialog, making it impossible to navigate to the contents in the bottom of the dialog (typically save and cancel buttons...).

Have seen attempts on workarounds for this problem, like this one: http://stackoverflow.com/questions/24047376/locking-the-body-background-when-use-a-dialog-in-primefaces, but would really like to avoid it if possible...

**Comment by tandraschko** [comment]
Would you please create a new issue with an example app?

**Comment by melloware** [comment]
PR Submitted: https://github.com/primefaces/primefaces/pull/4346
