### ISSUE TITLE
Mobile: Add support for font awesome

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2002]
Add support for font awesome to mobile components. 

Using a font-awesome icon on a button for instance is not looking good.

**Comment by kukel** [comment]
'Is not looking good' is to vague. For me it looks fine... Please show code and a screenshot

**Comment by djmj** [comment]
Here is code and a screenshot. The icon is displayed along description and not in a grey circle at the left. The button also uses font-awesome font for text.



	<p:button icon="ui-icon-shop" value="Warenbestand"/>
	<p:button icon="fa fa-payment" value="Warenbestand"/>

![pf-mobile-font-awesome](https://cloud.githubusercontent.com/assets/5265550/22721671/79c2806a-edb2-11e6-8acb-891729e37346.jpg)

**Fix-DOM**

	<button type="button" class="ui-btn ui-shadow ui-corner-all ui-btn-icon-left">
		<span class="fa fa-list"></span>
		<span>Warenbestand</span>
	</button>


	/* settings work good with, fa-list, fa-shopping-bag, fa-table, fa-star ... */

	.ui-btn-icon-left .fa {
    		color: white;
    		font-size: 0.9em;
    		left: 1.15em;
    		margin-left: -0.225em;
    		margin-top: -0.5em;
    		position: absolute;
   		 text-shadow: none;
    		top: 50%;
    		z-index: 100;
	}

**Comment by tandraschko** [comment]
In 6.1 the mobile renderkit will be deprecated in favor of responsive features. So please provide a PR if would like to get this fixed.

Will close it for now and reopen if a PR is provided.
