### ISSUE TITLE
p:selectOneMenu display grouping

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#2005]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? no
- Application server + version: Wildfly-10.0.0.Final
- Affected browsers: Firefox, Chrome, IE

## 2) Expected behavior
The selectOneMenu should display a list with grouping, the same way as it does using a list without grouping.

## 3) Actual behavior
I have some problem with p:selectOneMenu. My selectOneMenu will populate a list with grouping. If the list is too long, the list get displayed upwards without any vertical scrollbar. It should display downwards with a vertical scrollbar.

If the selectOneMenu is populated with normal list without grouping, it works fine. List can display with a vertical scrollbar if its too long.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

<p:selectOneMenu id="cars" styleClass="selectOneMenu">
    <f:selectItems value="#{bean.carItems}" ></f:selectItems>
</p:selectOneMenu>

## 6) Sample bean

public List getCarItems() {

    List cars;

    SelectItemGroup g1 = new SelectItemGroup("German Cars");
    g1.setSelectItems(new SelectItem[] { 
            new SelectItem("BMW", "BMW"),
            new SelectItem("Mercedes", "Mercedes"),
            new SelectItem("Volkswagen", "Volkswagen"), 
            new SelectItem("Item 1", "Item 1"), 
            new SelectItem("Item 2", "Item 2"), 
            new SelectItem("Item 3", "Item 3"), 
            new SelectItem("Item 4", "Item 4"), 
            new SelectItem("Item 5", "Item 5"), 
            new SelectItem("Item 6", "Item 6"), 
            new SelectItem("Item 7", "Item 7"), 
            new SelectItem("Item 8", "Item 8"), 
            new SelectItem("Item 9", "Item 9"), 
            new SelectItem("Item 10", "Item 10"), 

    });

    SelectItemGroup g2 = new SelectItemGroup("American Cars");
    g2.setSelectItems(new SelectItem[] {
            new SelectItem("Chrysler", "Chrysler"),
            new SelectItem("GM", "GM"), 
            new SelectItem("Ford", "Ford"),
            new SelectItem("Item 21", "Item 21"), 
            new SelectItem("Item 22", "Item 22"), 
            new SelectItem("Item 23", "Item 23"), 
            new SelectItem("Item 24", "Item 24"), 
            new SelectItem("Item 25", "Item 25"), 
            new SelectItem("Item 26", "Item 26"), 
            new SelectItem("Item 27", "Item 27"), 
            new SelectItem("Item 28", "Item 28"), 
    });

    cars = new ArrayList();
    cars.add(g1);
    cars.add(g2);

    return cars;
}

**Comment by Rawi01** [comment]
I reported it some time ago (#1534) including a fix for it. No response so far...
As temporary workaround you could set CSS `max-height` to `200px` for `.ui-selectonemenu-panel`

**Comment by tandraschko** [comment]
Fixed by: https://github.com/primefaces/primefaces/issues/2029
