### ISSUE TITLE
PrimePartialResponseWriter#redirect must not generate an extension block or ajax-redirect won't work

### ISSUE THREAD

**Issue by NiasSt90** [primefaces/primefaces#2009]
## 1) Environment
- PrimeFaces version: 6.1-SNAPSHOT (HEAD)
- Does it work on the newest PrimeFaces version? no
- Application server + version: JBoss EAP 6.4.12
- Affected browsers: all

## 2) Expected behavior
redirect after ajax call
...

## 3) Actual behavior
no redirect occurs
..

## 4) Steps to reproduce
create an ajax-action which redirects in a portlet-jsf2 application.

The jsf2 ajax client side script will take the first child of the ajax partial-response xml like:
(jsf.js)
var responseType = xml.getElementsByTagName("partial-response")[0].firstChild;
a redirect occurs only if:
...
if (responseType.nodeName === "redirect") {
    window.location = responseType.getAttribute("url");
    return;
}

But the PrimePartialResponseWriter#redirect creates an extension element at first:

    public void redirect(String url) throws IOException {
        startMetadataIfNecessary(); // <--- BAD for redirect!
        wrapped.redirect(url);
    }

**Comment by tandraschko** [comment]
Where is it defined that the redirect must be the first element?

**Comment by NiasSt90** [comment]
in the jsf.js from mojarra-jsf-impl as shown in my snippet above.
i don't looked in the spec until now.

But if a redirect occurs, it's stupid to include the extension block (because it should load scripts/styles etc.pp. which is not necessary in case of a redirect).

**Comment by tandraschko** [comment]
It's not neccesarry in our case but it could still make sure to execute other eval tags before the redirect.

**Comment by NiasSt90** [comment]
i've take a look in the spec (partial-response-xsd). 
And as you can see below it's not allowed to have an extension element as the first child of partial-response.

    <xsd:element name = "partial-response" type="javaee:partial-responseType">
    	<xsd:annotation>
    		<xsd:documentation>
    			The "partial-response" element is the root of the partial
    			response information hierarchy, and contains nested elements for all
    			possible elements that can exist in the response.
    		</xsd:documentation>
    	</xsd:annotation>
    </xsd:element>
    <xsd:complexType name="partial-responseType">
    	<xsd:annotation>
    		<xsd:documentation>
    			The "partial-response" element is the root of thei partial
    			response information hierarchy, and contains nested elements for all
    			possible elements that can exist in the response.
    		</xsd:documentation>
    	</xsd:annotation>
    	<xsd:choice>
    		<xsd:element name="changes"
    					 type="javaee:partial-response-changesType"
    					 minOccurs="0"
    					 maxOccurs="1"/>
    		<xsd:element name="redirect"
    					 type="javaee:partial-response-redirectType"
    					 minOccurs="0"
    					 maxOccurs="1"/>
    		<xsd:element name="error"
    					 type="javaee:partial-response-errorType"
    					 minOccurs="0"
    					 maxOccurs="1"/>
    	</xsd:choice>
    </xsd:complexType>
