### ISSUE TITLE
FileUpload: converter support 

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2016]
## 1) Environment
- PrimeFaces version: 6-1-SNAPSHOT
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat 7
- Affected browsers: Chrome 55

## 2) Expected behavior

1. Upload a file
2. Submit form
3. I expect during `Apply Request Phase` custom converter be called so the uploaded file can be convert into String

## 3) Actual behavior
Custom converter not called

## 4) Steps to reproduce
Create a simple converter

## 5) Sample XHTML
```html
<p:fileUpload id="fp_vlt" mode="simple" rendered="#{!data.readonly}" converter="fileConverter" value="#{dbh[data.property]}" required="#{formField.mandatory}" />
```

## 6) Sample bean
None

## Analysis
From what I see, `FileUploadRenderer.getConvertedValue()` do his own stuff but does not call custom converters like it's done in `InputRenderer`. So far, I inherited from `FileUploadRenderer` and override `getConvertedValue()` so I can do this:

```java
    @Override
    public Object getConvertedValue(FacesContext context, UIComponent component, Object submittedValue) throws ConverterException {
        Object value = super.getConvertedValue(context, component, submittedValue);
        if (value != null) {
            Converter converter = ComponentUtils.getConverter(context, component);
            if (converter != null) {
                value = converter.getAsObject(context, component, null);
            }
        }
        return value;
    }
```

And my converter looks like this _(I retrieve the uploaded file using component)_:
```java
@FacesConverter(value = "fileConverter")
public class FileConverter implements Converter {

    @Override
    public Object getAsObject(FacesContext context, UIComponent component, String value) {
        if (component instanceof FileUpload) {
            UploadedFile file = (UploadedFile) ((FileUpload) component).getSubmittedValue();
            value = new String(file.getContents(), StandardCharsets.UTF_8);
        }

        return value;
    }

    @Override
    public String getAsString(FacesContext context, UIComponent component, Object value) {
        return null;
    }

}
```

What do you think?

**Comment by tandraschko** [comment]
Why do you need an own converter?

**Comment by Rapster** [comment]
I save file's content in database, to do so, I'm using a converter which is quite straightforward.

**Comment by Rapster** [comment]
The fact that `Converter.getAsObject`'s taking a `String` forces me to pass `null`. Too bad there is no `getAsObject(FacesContext context, UIComponent component, Object value)`... Trinidad seems to support Converter in `inputFile` https://myfaces.apache.org/trinidad/trinidad-api/tagdoc/tr_inputFile.html

**Comment by tandraschko** [comment]
Feel free to provide a PR.

**Comment by Rapster** [comment]
No problem. Although, I can't figure out what should be the String parameter, null?

**Comment by tandraschko** [comment]
Thats the reason that there is no converter support.
Converters are used to convert string inputs to pojos and vice versa.
For the FileUpload, the byte[] will automatically be converted to UploadedFile.

IMO there is no need to support converters.

**Comment by Rapster** [comment]
Not agree with you on this. I'd say it's a design problem. `Converter` has this method `getAsObject(FacesContext context, UIComponent component, String value)` because 99% of standard form ui element have a string input. But what about `inputFile` typically? I had a look on how other frameworks are doing:

- WPF: https://msdn.microsoft.com/fr-fr/library/system.windows.data.ivalueconverter(v=vs.110).aspx
- Vaadin: https://vaadin.com/api/com/vaadin/data/util/converter/Converter.html

**Comment by tandraschko** [comment]
Yep exactly. But as converters only supports String, i don't think we should do some weird workarounds here.
The right way is to create a spec ticket probably. The converter was already enhanced in JSF 2.3 to have a generic parameters for the outcoming value object.

**Comment by Rapster** [comment]
I added a comment to the ticket, don't know if I'll get any response... https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1355

**Comment by tandraschko** [comment]
I would create a new issue, with the whole description ;) I personally also don't like to answer new "questions" in already closed issues.

**Comment by Rapster** [comment]
Thanks @tandraschko I just created a new one https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1439 _(I can't delete my previous comment on 1355 :/ )_

**Comment by melloware** [comment]
I am going to close this since a spec issue was opened.
