### ISSUE TITLE
Fileupload - Basic: input type="file" class wrong font-size

### ISSUE THREAD

**Issue by PereBG** [primefaces/primefaces#202]
As you can see in the image below the font-size of the input type="file" is too big. 

![primefaces showcase - mozilla firefox_4](https://cloud.githubusercontent.com/assets/5645136/7394494/4126b164-ee94-11e4-943b-47c314e3768d.jpg)

When i click at the right of the fileupload button the event is triggered, in my app i have the following css to prevent this behavior

.ui-fileupload-simple input[type="file"]{
    font-size:0px;
}

**Comment by cagataycivici** [comment]
It is required for cross browser compatibility and trigger the browser dialog.
