### ISSUE TITLE
DataTable rowsPerPageLabel/aria message is hidden

### ISSUE THREAD

**Issue by andyfinch** [primefaces/primefaces#2020]
## 1) Environment
- PrimeFaces version: 6.0.13
- Does it work on the newest PrimeFaces version? No
- Application server + version: Weblogic 12.2.1.2 JSF 2.2.8-17
- Affected browsers: All

## 2) Expected behavior
Paginator rowsPerPage Label should be displayed

## 3) Actual behavior
Label is rendered but hidden.  This is caused by UIData.PAGINATOR_RPP_LABEL_CLASS having a value of "ui-paginator-rpp-label ui-helper-hidden"

(Current work round is to override css to force display:inline)

I believe this may be something to do with aria accessibility but label should be displayed. 

Also should attribute rowsPerPageLabel be depreciated? How would you use different message for different datatables?

## 4) Steps to reproduce
Create Datatable with Paginator.

## 5) Sample XHTML
```
<p:dataTable var="car" value="#{dtRowGroupView.cars}"  rowsPerPageTemplate="10,20,50,100" 
currentPageReportTemplate="Displaying results {startRecord} to {endRecord} of {totalRecords}, Page {currentPage} of {totalPages}" 
paginatorTemplate="{RowsPerPageDropdown}  {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
paginator="true" >
        <p:column headerText="Year">
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Color">
            <h:outputText value="#{car.color}" />
        </p:column>
        <p:column headerText="Id">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:summaryRow>
            <p:column colspan="2" style="text-align:right">
                <h:outputText value="Total:" />
            </p:column>
            <p:column>
                <h:outputText value="#{dtRowGroupView.randomPrice}">
                    <f:convertNumber type="currency" currencySymbol="$" />
                </h:outputText>
            </p:column>
        </p:summaryRow>
    </p:dataTable>
```

## 6) Sample bean
See showcase

**Comment by mertsincan** [comment]
Please see; https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/paginator/RowsPerPageDropdownRenderer.java#L43
For dynamic message, please see; https://www.mkyong.com/jsf2/jsf-2-0-and-resource-bundles-example/

**Comment by andyfinch** [comment]
Confused?  Firstly the issue still exists i.e. The html element is hidden by default.  This is surely not correct.  Secondly the mkyong link does nothing to explain different messages.  If the primefaces.paginator.aria.ROWS_PER_PAGE should be used in a ResourceBundle how do I switch messages for different datatables?  Multiple resourcebundles?  That would be overkill and less than desirable.
