### ISSUE TITLE
New Chips Component

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2024]
Chips is used to enter multiple values on an inputfield.

**Comment by kukel** [comment]
could have been added to the autocomplete component 'multiple' variant with small changes. See [stackoverflow for an answer](https://stackoverflow.com/questions/39635358/input-multiple-with-tags-without-autocompletion/39656447#39656447). Why the need for an new component?

**Comment by ErickPezoa** [comment]
How does chips work? The documentation on the PrimeFaces showcase is vague. For data type do I need to pass to value? Is it a list (array list?)?
