### ISSUE TITLE
Disabling ajax events on p:dataTable breaks p:cellEditor

### ISSUE THREAD

**Issue by ReedElliott** [primefaces/primefaces#2030]
## 1) Environment
- PrimeFaces version: 6.0.13
- Does it work on the newest PrimeFaces version? No
- Application server + version: GlassFish 4.1.1
- Affected browsers: Chrome

## 2) Expected behavior

CellEditor within a DataTable will move from input mode to output mode after user enters data an exits the field.

## 3) Actual behavior

CellEditor within a DataTable is stuck in input mode and entered data is not submitted to server.

## 4) Steps to reproduce

Disable cellEdit and cellEditCancel ajax events on DataTable as shown below.

`<p:dataTable
    id="telephones"
    value="#{personEditor.person.telephones}"
    var="telephone"
    editable="true"
    editMode="cell"
    reflow="true"
    widgetVar="widget-telephones">
    <p:ajax
        event="cellEdit"
        disabled="true" />
    <p:ajax
        event="cellEditCancel"
        disabled="true" />`

[See "How do you disable ajax events on a cell edit p:dataTable?" forum topic](http://forum.primefaces.org/viewtopic.php?f=3&t=49073)

## 5) Sample XHTML

`<p:dataTable 
    id="telephones"
    value="#{personEditor.person.telephones}"
    var="telephone"
    editable="true"
    editMode="cell"
    reflow="true"
    widgetVar="widget-telephones">
    <p:ajax
        event="cellEdit"
        disabled="true" />
    <p:ajax
        event="cellEditCancel"
        disabled="true" />`

## 6) Sample bean

..

**Comment by tandraschko** [comment]
This is expected.
Our datatable JS does the following:
if (behaviorDefined('rowEdit')) { use it } else { construct a new ajax script }

There is no reason to add a behavior and set disabled to true.
