### ISSUE TITLE
AutoComplete: add dynamic tooltip support

### ISSUE THREAD

**Issue by parlak1** [primefaces/primefaces#2033]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: Wildfly 10.0
- Affected browsers: Chrome 55.0.2883.87 m (64-bit)

## 2) Expected behavior
When <p:autoComplete multiple="true" var="item" title="#{item.description}"> i expect item specific dynamic tooltips on each hovered items.
...

## 3) Actual behavior
When i change title="BlueSky" it shows BlueSky on the first hovered item and stays there even though i hover on other items.
..

## 4) Steps to reproduce
In a multiple enabled AutoComplete add two items in the autoComplete input area
Hover on items with mouse and try to see the tooltip on each item
.. 

## 5) Sample XHTML
<p:autoComplete id="keywords"
				value="#{artifactController.keywords}"
				completeMethod="#{keywordController.filterByNameAsKeywordSelected}"
				var="item"
				multiple="true"
				itemValue="#{item}"
				itemLabel="#{item.title}"
				title="#{item.description}"
				dropdown="true"
				scrollHeight="250">
	<p:ajax event="itemSelect" />
	<p:ajax event="itemUnselect" />
	<p:column>
		<span class="dropdown-item-title">#{item.title}</span>
		<span class="dropdown-item-subtitle">#{item.description}</span>
	</p:column>
</p:autoComplete>
..

## 6) Sample bean
@Named
@ViewScoped
public class ArtifactController {
	private List<Keyword> keywords;
	// getters and setters .....
}

@Entity
@Table(name = "Keyword")
public class Keyword {
	private String title;
	private String description;
	// getters and setters .....
}
..

**Comment by melloware** [comment]
This is already possible using `itemTip` facet of AutoComplete.  See the docs here: https://primefaces.github.io/primefaces/8_0/#/components/autocomplete?id=itemtip
