### ISSUE TITLE
DataTable: columns with low reponsivePriority may be removed too late

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#2036]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? not with 6.0
- Application server + version: Tomcat 8.0x
- Affected browsers: Firefox 50.1.0, Chrome 55.0.2883.87

## 2) Expected behavior

When you have a dataTable with about 10-11 columns, most of which must always be visible (=> default priority = 1) and you start to give priority 2, 3 and 4 to three different columns, I would expect those columns to disappear one after the other (higher priority number first) as soon as I shrink the browser window and the other columns (with default priority = 1) start to be too large to fit horizontally into the window.
What I see, however, is that those "lower priority" columns start to disappear too late, after some of the columns with the default priority=1 have already overflown (and the horizontal scrollbar of the dataTable wrapper div is shown by the browser).
However, if I assign higher priority numbers (say, 4, 5 and 6) to the columns that should disappear, the situation is much better, so those columns seems to be hidden "more quickly".

I don't find this intuitive. I would expect priorities to be relative to one another.
Or, if they are in some way "absolute", then a range 1-6 is too small for me: in my example, I want those columns to disappear in the order "from the highest priority number to the lowest", but as quick as possible, in order to keep all the other columns fully visible (until this is possible, of course). But I can't assign priority 6 to all of them (otherwise they are removed simultaneously), while the columns with priority 5 and 4 are still removed a bit late.

To give you and idea, given the current behaviour, if I had, say, a range 1-100, I would probably assign priorities 97, 98 and 99 to those columns, to make them disappear as quick as possible.

## 3) Actual behavior

See expected behaviour..

## 4) Steps to reproduce

See expected behaviour.

## 5) Sample XHTML
    <p:dataTable value="#{myBean.invoices}" var="invoice"
    	tableStyle="table-layout: auto; margin-top: 1ex">
    	<p:column>
    		<div class="listItemActionRow">
    			<p:link outcome="/invoice/viewInvoice" title="View"
    				styleClass="fa fa-search iconListItemAction">
    				<f:param name="id" value="#{invoice.id}" />
    			</p:link>
    		</div>
    	</p:column>
    	<p:column headerText="Number">
    		<h:outputText value="&amp;nbsp;" escape="false"
    			styleClass="fa fa-upload" style="color: #aaaaaa" rendered="#{invoice.imported}"
    			title="Invoice imported from external system" />
    		<h:outputText value="#{invoice.number}" />
    	</p:column>
    	<p:column headerText="Date">
    		<h:outputText value="#{invoice.date}">
    			<f:convertDateTime	pattern="dd/MM/yyyy" />
    		</h:outputText>
    	</p:column>
    	<p:column headerText="Registry" priority="3">
    		<h:outputText value="#{invoice.registry}" />
    	</p:column>
    	<p:column headerText="Customer">
    		<h:outputText value="#{invoice.customer}" />
    	</p:column>
    	<p:column headerText="Office" priority="4">
    		<h:outputText value="#{invoice.officeCode}" />
    	</p:column>
    	<p:column headerText="Amount" style="white-space: nowrap">
    		<h:outputText value="#{invoice.amount}">
                          <f:convertNumber type="currency" />
                     </h:outputText>
    	</p:column>
    	<p:column priority="2">
    		<f:facet name="header">
    		       <h:outputText value="XML" title="XML file name" />
    		</f:facet>
    		<p:link outcome="/invoice/invoiceXslView" target="_blank"
    			value="#{invoice.xmlFileName}"
    			title="View">
    			<f:param name="id" value="#{invoice.id}" />
    		</p:link>
    	</p:column>
    	<p:column headerText="Status">
    		<h:outputText value="BLAH BLAH BLAH" />
    	</p:column>
    	<p:column>
    		<f:facet name="header">
    			<h:outputText value="Second status" />
    		</f:facet>
    		<h:outputText value="BLAH BLAH BLAH" />
    	</p:column>
    	<p:column>
    		<div class="listItemActionRow">
    			<p:link outcome="/invoice/editInvoice" title="Edit"
    				styleClass="fa fa-edit iconListItemAction">
    				<f:param name="id" value="#{invoice.id}" />
    			</p:link>
    			<p:commandLink title="Prepare"
    				styleClass="fa fa-suitcase iconListItemAction"
    				process="@this"
    				global="false" />
    		</div>
    		<div class="listItemActionRow">
    			<p:commandLink ajax="false"
    				styleClass="fa fa-download iconListItemAction"
    				title="Download"
                                    value=" bla bla"
    				process="@this">
    				<p:fileDownload value="#{bean.getFile()" contentDisposition="attachment" />
    			</p:commandLink>
    		</div>					
    		<div class="listItemActionRow">
    			<p:commandLink
    				styleClass="fa fa-upload iconListItemAction" 
    				title="Upload"
    				value=" bla bla"
    				process="@this"
    				global="false" />
    		</div>
    	</p:column>
    </p:dataTable>

## 6) Sample bean

In groovy

    class MyBean {
      Invoice[] invoices
    }

    class Invoice {
      Long id
      Integer number
      Date date
      String registry
      String customer
      String officeCode
      BigDecimal amount
    }

The situation is a bit better if you temove the table-layout styling, but just because columns are rendered evenly. However, the problem is not 100% solved by this change.

I hope this code snippet can help you to reproduce in some way. The actual code I'm using to test this is way more complex.

**Comment by p4w3l** [comment]
tableStyle="table-layout: auto;" improves the behaviour a little. Still with horz. scrollbar but without "delay"

**Comment by tandraschko** [comment]
@melloware would you like to reproduce this? maybe we can fix it easily with some CSS

**Comment by melloware** [comment]
@tandraschko as requested here is a reproducer with 10.0-SNAPSHOT.
[pf-2036.zip](https://github.com/primefaces/primefaces/files/5765133/pf-2036.zip)

**Comment by melloware** [comment]
Newer reproducer: 
[pf-2036.zip](https://github.com/primefaces/primefaces/files/13844988/pf-2036.zip)

**Comment by melloware** [comment]
i think this is juts a misunderstanding of the behavior and not a bug.  So if you give something `responsivePriority=3` it gets this CSS style.

```css
@media screen and (min-width: 40em) {
  th.ui-column-p-3, td.ui-column-p-3 {
    display: table-cell;
  }
}
```

That means when the min-width of the browser hits 40em then the column dissappears.  So when you say "too late" you are expecting it to dissappear as soon as some columns become crunched by the CSS for responsive is based on your browser size it has nothing to do with if other columns are "crunched".

**Comment by mauromol** [comment]
Responsive not based on browser window size is the expected behaviour? This really perplexes me...
What's the reason of using priorities if they are not priorities but aliases for some fixed minimum size?

**Comment by melloware** [comment]
@mauromol that is the way it always works responsive by definition means ["responsive design" ](https://en.wikipedia.org/wiki/Responsive_web_design) 

> Responsive web design (RWD) or responsive design is an approach to [web design](https://en.wikipedia.org/wiki/Web_design) that aims to make web pages render well on a variety of devices and window or screen sizes from minimum to maximum display size to ensure usability and satisfaction.

So responsive has always been based on the size of your browser window for determining what is display ala mobile 380px vs desktop 1290px etc.

**Comment by mauromol** [comment]
Indeed, you are saying instead that columns are given a minimum size, whatever is my browser size, and that it's ok that the result is not "so much responsive" by design...
