### ISSUE TITLE
<p:tab not working

### ISSUE THREAD

**Issue by kaushikmeduri** [primefaces/primefaces#2037]
We are using multiple tabs under <p:tabView
Code works fine in FireFox, Chrome.
It works well some of IE Users. Some in IE 11 complain they wont be able to navigate tabs except the first one which is default shown.
From logs it is verified that <p:ajax event="tabChange" works well. We are not able to reproduce in any of our Environments the specific problem . It could be User setting but we want to know root cause.

Users in our case do not have option to change IE Settings , Install Other Browsers due to Agency Level Settings. Some even have Internet Explorer browser / Select compatibility view settings ON.

Please find details In Line. 

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? 
Code works fine in FireFox, Chrome , Certain IE Browsers even with 6.0

- Application server + version:  Jboss 6.4 
- Affected browsers:
It works well some of Internet Explorer Users. Some in IE 11 complain they wont be able to navigate tabs except the first one which is default shown. 
## 2) Expected behavior
in all browsers user should be  able to navigate tabs . 
...

## 3) Actual behavior
It works well some of Internet Explorer Users. Some in IE 11 complain they wont be able to navigate tabs except the first one which is default shown. 
..

## 4) Steps to reproduce

Use http://www.primefaces.org/showcase/ui/panel/tabView.xhtml with IE Settings differently. 
Perhaps Some higher level settings blocking tab clicks.

## 5) Sample XHTML

..http://www.primefaces.org/showcase/ui/panel/tabView.xhtml

## 6) Sample bean
http://www.primefaces.org/showcase/ui/panel/tabView.xhtml
..

**Comment by tandraschko** [comment]
How can we replicate the problem?

**Comment by kaushikmeduri** [comment]
We are also not able to replicate problem.It only happens to Certain Government Users. This is Government  application which recently upgraded from primefaces-5.0.6 to primefaces-6.0.
Users did not have issue with older Jar file.
Please advise if there is any previous related issues with tabView not working related to Prime faces

**Comment by tandraschko** [comment]
Thats the problem. If you can't replicate it, how should i replicate it? I could invest many hours without any result.
So please come back if you are able to replicate it, otherwise i can't help you.

(Thats my opinion as developer which is just doing his open source work here. Maybe professional support like PrimeFaces PRO is better for such cases ;))

**Comment by kaushikmeduri** [comment]
Updating XHTML and BEAN for opinion. Logs do show onTabChange value printed successfully.
Not sure what causes Browser not to call p:tab function click.



XHTML


<p:tabView id="tabView" dynamic="false" cache="false">  
<p:ajax event="tabChange" listener="#{userData.onTabChange}" onstart="blockScreen();" oncomplete="unBlockScreen();"
update=":form:confirmationmsg"/>  
<p:tab id="Personal" title="Personal Information">
</p:tab>
<p:tab id="PasswordUpdate" title="Change Password">
</p:tab>
</p:tab>
<p:tab id="roledetails" title="Role Details">
</p:tab>			          
</p:tabView>



BEAN


public class UserData {

public void onTabChange(TabChangeEvent event) {
String selectedTab = event.getTab().getId();
log.info("Selected tab value " + selectedTab);
 
}

}

**Comment by tandraschko** [comment]
Will close it for now as even you can't replicate it.
Feel free to reopen if you have the steps to replicate. As you are also use some screen blocking, it might related to this.

**Comment by Llenobrac** [comment]
i am having the same problem, but the only  thing that i have seen is that <ul ... role="tablist"> not contain the class ui-helper-clearfix.

primefaces 5.2 (working)
![seleccion_110](https://cloud.githubusercontent.com/assets/10191133/24222850/8eefa7a2-0f21-11e7-9017-52a8074363ef.png)

primefaces 6.0 (not working)
![seleccion_109](https://cloud.githubusercontent.com/assets/10191133/24222859/99973f58-0f21-11e7-87ec-96e1085d7153.png)
