### ISSUE TITLE
Feature request: Clear icon inside inputText

### ISSUE THREAD

**Issue by dinhani** [primefaces/primefaces#204]
Some applications use a X icon inside an input so the user can easily clear the current value clicking on it.

 I think this can be added to input components.
`<p:inputText value="123" clearIcon="true" />`

![clear input](https://cloud.githubusercontent.com/assets/1139781/7397083/695e4cb8-ee7c-11e4-93a3-cf68f583d4ec.png)

**Comment by cagataycivici** [comment]
Why not type="search" on an input?

**Comment by dinhani** [comment]
Because type="search" only works in the most recent versions of Chrome and Safari.

**Comment by cagataycivici** [comment]
I think implementing this is too much work and already supported in modern browsers natively. IE also supports it for a long time as I remember.
