### ISSUE TITLE
calendar multi ajax events

### ISSUE THREAD

**Issue by mehmetbektas** [primefaces/primefaces#2040]
## 1) Environment
PrimeFaces version: 6.0 (Community)
Does it work on the newest PrimeFaces version? yes, i use latest version of primefaces.
Application server + version: Apache Tomcat 8.0.36
Affected browsers: Firefox, Google Chrome (latest version)

## 2) Expected behavior
I think, dateSelect event should not trigger 'blur' event

## 3) Actual behavior
'dateSelect' event triggers 'blur' event

## 4) Sample
Here is sample project: https://github.com/mehmetbektas/pf-calendar.git 
And I asked my problem in: http://stackoverflow.com/questions/41780824/primefaces-calendar-multi-events

**Comment by tandraschko** [comment]
Why do u use blur? I would take the change event.

**Comment by mehmetbektas** [comment]
I think 'change' event runs every change action. I can't use 'change' event instead of 'blur' event.

I want to select hour and minute after day selection, but dateSelect event triggers blur event and this triggered onselect method that in Index.java bean before the time I want. So, when calendar popup is active, i want the 'blur' event not to be triggered.

**Comment by tandraschko** [comment]
But why do you want to catch a blur event? for which purpose?

**Comment by tandraschko** [comment]
(also don't think that we can fix that, it's likely done by the jquery plugin)

**Comment by kukel** [comment]
It's even next to impossible to 'fix' even for the jquery plugin. How does it know the user finished selecting things? Delay is the only option I can think of but even that would not work great UIX wise

**Comment by tandraschko** [comment]
We don't have a special blur handling in our JS. So please check with native jquery datepicker and ask the datepicker dev's.
