### ISSUE TITLE
SelectOneMenu: minor style issue with editable="true"

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#2043]
## 1) Environment
- PrimeFaces version: 6.0.14

## 2) Expected behavior
The Fontsize of a selectOneMenu should always be the same no matter wether it is editable or not

## 3) Actual behavior
If a selectoneMenu is editable the InputField used is having a smaller fontsize than the rendered label if editable is false. 

## 4) Steps to reproduce
Just look at it in the Primefaces Showcase: http://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

The Editable InputField has a fontsize ofg 13.3333px, while the non editable has  14.4px (Firefox)

## FIX:
To fix this adding ui-widget to the editable input field as style class is enough. Since the regular Input Fields also have "ui-widget" in their style classes, I think it was just forgotten here for the input field.
``` 
Current way:
<input class="ui-selectonemenu-label ui-inputfield ui-corner-all" type="text">

Correct way:?!
<input class="ui-widget ui-selectonemenu-label ui-inputfield ui-corner-all" type="text">
```

**Comment by tandraschko** [comment]
See my comment in the PR

**Comment by melloware** [comment]
This is a theme related issue and can be fixed easily with CSS.  I am going to close this issue as it has not received any upvotes and no one else in 3 years has complained about it.

**Comment by humeyracal** [comment]
We still have this problem with PF 8.0.1

**Comment by melloware** [comment]
@humeyracal You can fix this with some CSS very easily.

**Comment by humeyracal** [comment]
I added styleClass="ui-widget" to SelectOneMenu since adding it to container didn't help, still doesnt work. Can you help? Thank you.

**Comment by melloware** [comment]
@humeyracal If you want to make the editor AND the Selctone labels the same size try adding this CSS.
```css
body .ui-selectonemenu .ui-selectonemenu-label{
  font-size: 12px;
}
```

Just set to whatever font size you want.
