### ISSUE TITLE
p:blockUI stops working after the component to be blocked has been update via AJAX

### ISSUE THREAD

**Issue by JensPiegsa** [primefaces/primefaces#2047]
Similar issues:

* http://stackoverflow.com/q/20028923/1725096
* http://stackoverflow.com/q/12390985/1725096

Currently the only solution seems to be a shift to *PrimeFaces Extensions* and use [`pe:blockUI`](http://www.primefaces.org/showcase-ext/sections/blockui/blockUIAjax.jsf) instead.

**Comment by tandraschko** [comment]
I think it's fixed now but i don't have time to try it. Could you please check it again with a build from trunk?

**Comment by JensPiegsa** [comment]
A quick test raises no more problems. Thanks!
