### ISSUE TITLE
Dialog: position wrong if scrolled before shown

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2062]
If you have a dialog with `position="50, 50"` and open the dialog everything is fine and style is `top: 50px;`.

If you reload the page, scroll down the page by 100 pixel and then open the dialog, the dialog is positioned wrong. Its header is not visible, because its style is `top: -50px;`.

This is wrong. It must remain `top: 50px;` instead. Dialog is unaware of scrolling.

The same applies to vertical scrolling.

**Comment by nivaldin** [comment]
Almost same problem here... If I change the number of rows shown in a DataTable paginated, then try to show a dialog, it calculates its top position so big that it's not show on the page.

**Comment by djmj** [comment]
Any change this fix will make it into 6.1, since it seems like a very small change?

**Comment by ghost** [comment]
I have similar issue. When I use a collapsible panel in combination with dialogs, it gives strange results. When I have multiple panels in the page which are all expanded, my dialogs are not visible anymore. When I have just a few, depending on the height of the panel, you can see the dialog is coming partially on the screen. This with default behaviour (no attributes configured). Also configuring attributes doesn't help. Sometimes using positionType absolute helps rendering on the screen, but alignment is not done. The only solution right now is to use position=top, which is the only way to force the dialog to be always on screen. Please fix.

**Comment by tandraschko** [comment]
Feel free to provide an PR - thats the easiest way to get it fixed.

**Comment by tandraschko** [comment]
Did you try positionType="absolute"?

**Comment by tandraschko** [comment]
It's not fixed by my commit - so please feel free to investigate.

**Comment by melloware** [comment]
Here is a test case showing the issue:  
[pf-2062.zip](https://github.com/primefaces/primefaces/files/2720865/pf-2062.zip)

The problem is with this code:
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L353-L362

**Comment by GedMarc** [comment]
@melloware 

```
 collision: “none” 
```
L:352
The recalc is sending it off on collision detection.

**Comment by melloware** [comment]
@GedMarc I tested it locally with my test case above and collision:none has no effect on this.  The bug still remains.

**Comment by GedMarc** [comment]
@melloware  Let me see if I can spot the difference between what I've got and the demo site :)

**Comment by melloware** [comment]
If you donwload this:  https://github.com/primefaces/primefaces/files/2720865/pf-2062.zip

You can just run "mvn clean jetty:run-epxloded" and navigate to http://localhost:8080/primefaces-test/test.xhtml to see it in action.  You may have to flip the pom.xml from 6.3-SNAPSHOT to 7.0.

**Comment by GedMarc** [comment]
@melloware  Ahh I did put in some customs 

I dodged it up, the refresh() method is broked, but this works fine with minimal performance hit, until jquery is pulled out completely ;) xD 

```
 $(window).scroll(function(){
     PF('spot').show();
});
```

![image](https://user-images.githubusercontent.com/5367513/55955007-8933cd00-5c60-11e9-8293-1d6ea55f7447.png)

**Comment by melloware** [comment]
Does that continually call Show() as the page is scrolled?

**Comment by GedMarc** [comment]
From what I can see, it's exactly what the refresh() does, but that method is breaking on ```this.cfg``` so it's not scrolling with it.

It does call it continually, but the method never recreates the DOM, it just repositions the left right top and bottom overlays, hence why I say "minimal performance hit".

JQuery 3 would be $(window).on('scroll',function(){};

On the PF showcase, this would be part of the handleform()?

**Comment by melloware** [comment]
I think we need to fix this in the core dialog.  Here is the refresh method I don't see it doing anything about reclaculating position or window scroll?

https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L63-L81

**Comment by GedMarc** [comment]
I went this route to finalize my impl without screwing on the show()
```
$(window).scroll(function(){
    if($('.ui-spotlight-top').is(":visible"))
         PF('spot').show();
    });
```

ref here (dialog doesn't take part here) : 
https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/spotlight/spotlight.js#L81

ACTUALLY --
in that spotlight you can just change the event name looking at that!
from resize.spotlight to on scroll xD

**Comment by GedMarc** [comment]
oh wait did I put this on the wrong issue again

**Comment by GedMarc** [comment]
EDIT : append to resize.spotlight event, removing the event breaks, well, the resizing.

Dialog fix : same shit different smell ,
https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L58

needs an on scroll then it works great.

**Comment by melloware** [comment]
So here is what bindResizeLisneter does.  All of the PrimeFaces overlays call PrimeFaces.utils.registerResizeHandler().

https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L571-L588

**Comment by melloware** [comment]
I think we are mixing issues between Spotlight and Dialog.

**Comment by GedMarc** [comment]
Yeah I think so, the spotlight issue is closed and links to this one (so I posted it here) (https://github.com/primefaces/primefaces/issues/4348)

But it is the same problem, scrolling is not considering that the resize event has to take place (which it does).
So for me, I would say, in addition to adding the registerResize, for dialog and spotlight, I would add that the resize event must fire on scroll as well. 

It looks like my hack and patch will do the trick for us on 6.2.18 - with the "if the overlay is visible clause", doesn't seem to be any whiplash that we've found just yet - dialogs and spotlights are moving and motioning nicely with p-grid layouts and mobile views.

**Comment by melloware** [comment]
ok can you send me the exact line to patch for spotlight and dialog and I can test it locally?

**Comment by GedMarc** [comment]
Spotlight (Add don't replace) :

https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/spotlight/spotlight.js#L81
```
var scrollFix = function recalcOnScroll(){
            $this.calculatePositions();
});
}
$(window).on('scroll', scrollFix );
```
https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/spotlight/spotlight.js#L91
```
        $(window).off('scroll',scrollFix);
```

**Comment by GedMarc** [comment]
dialog getting lagging scrolling --- give me 10 mins to see

**Comment by melloware** [comment]
Can you review my spotlight PR?  I think I simplified it.  https://github.com/primefaces/primefaces/pull/4731
