### ISSUE TITLE
Mobile: inputSwitch - showLabels not working

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2065]
I wanted to hide the labels on mobile inputSwitch, but labels are still shown even if set to ``showLabels="false"`.

**Comment by kukel** [comment]
Did you miss the "important" parts when you created the new issue? Lots of info missing....

**Comment by tandraschko** [comment]
In 6.1 the mobile renderkit will be deprecated in favor of responsive features. So please provide a PR if would like to get this fixed.

Will close it for now and reopen if a PR is provided.
