### ISSUE TITLE
Feature request : signature on images or pdf

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#2067]
Please add feature to enable signature on images or pdf

**Comment by kukel** [comment]
On PDF it can be done b y customizing the exporter. For Images use some java image library or the jdk... Should not be something PF provides

**Comment by tandraschko** [comment]
Yep, i think its a little bit out of scope. 
Extensions provides a PdfViewer based on pdf.js. Maybe its somehow possible with pdf.js.
