### ISSUE TITLE
Add multiple item support to label of SelectCheckboxMenu

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2069]
like multiple autocomplete
![multipleselectcheckboxmenu](https://cloud.githubusercontent.com/assets/11868120/22774881/c92aeda4-eeb1-11e6-9647-55255e95e450.PNG)

**Comment by andrei-ivanov** [comment]
btw, no release announcement for 6.0.15 on the blog?

**Comment by rho66** [comment]
I am using Primefaces 6.1 with Omega thema and my SelectCheckboxMenu looks like this with `multiple="true"`:

![selectcheckbox](https://cloud.githubusercontent.com/assets/25029017/26159806/ddfb060a-3b1f-11e7-981d-15b8d9caae19.png)

Is this a bug in Omega theme?!

**Comment by melloware** [comment]
PF showcase is on OMEGA as well and doesn't seem to have this issue...

https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml

Although if you are using the "professional" Omega theme my gut feels like the problem is there.

**Comment by rho66** [comment]
You are right - I'm using the professional Omega theme! I'll see how to contact them to get a fix!

**Comment by melloware** [comment]
I think here is where you want to report it...   https://forum.primefaces.org/viewforum.php?f=40

**Comment by rho66** [comment]
Thank you - I reported it as mentioned by you: https://forum.primefaces.org/viewtopic.php?f=40&t=50972

**Comment by rho66** [comment]
Fixed in next version of professional Omega layout!
