### ISSUE TITLE
Mobile - support for inplace

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2071]
It seems inplace is not supported for mobile devices but would be a useful feature.

http://forum.primefaces.org/viewtopic.php?f=8&t=38722

**Comment by kukel** [comment]
Did you miss the "important" parts when you created the new issue? Lots of info missing....

**Comment by tandraschko** [comment]
In 6.1 the mobile renderkit will be deprecated in favor of responsive features. So please provide a PR if would like to get this fixed.

Will close it for now and reopen if a PR is provided.
