### ISSUE TITLE
Mobile - Styling lost when updating p:inputNumber

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2072]
I have an _p:inputNumber_ within a _pm:field_ and want to update it via ajax.

After update the styling is lost. It seems the client component is not rebinded.
For testing purpose i also added a _p:inputText_ in my panel (myNumber). This works.

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? i dont know, do not have elite subscription
- Glassfish 4.1.1 mojarra 2.2.9
- firefox, IE

## 2) Expected behavior

Styling should be rebinded after ajax update.

## 3) Actual behavior

Styling is lost, functionality remains

## 4) Steps to reproduce

update a _p:inputNumber_ using ajax component

## 5) Sample XHTML

	<html lang="#{view.locale.language}"
		xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:p="http://primefaces.org/ui"
		xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
		<f:view renderKitId="PRIMEFACES_MOBILE" encoding="UTF-8">
			<h:head>
				<f:facet name="first">
					<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
				</f:facet>
			</h:head>
			<h:body>
				<h:form>
					<pm:field>
						<p:outputLabel for="myNumber" value="Number"/>
						<h:panelGroup id="pnlMyNumber">
							<p:inputNumber id="myNumber"/>
							<p:commandButton icon="ui-icon-edit" update="pnlMyNumber"/>
						</h:panelGroup>
					</pm:field>
				</h:form>
			</h:body>
		</f:view>
	</html>

## 6) Sample bean

	not required

**Comment by kukel** [comment]
Did you miss the "important" parts when you created the new issue? Lots of info missing....

**Comment by djmj** [comment]
I updated the issue.

**Comment by tandraschko** [comment]
In 6.1 the mobile renderkit will be deprecated in favor of responsive features. So please provide a PR if would like to get this fixed.

Will close it for now and reopen if a PR is provided.
