### ISSUE TITLE
Mobile - signature component not rendering on mobile renderkit

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2073]
I tried to use signature component on mobile renderkit, but it is not rendering. I thought it has mobile support.

Here a related forum thread.

http://forum.primefaces.org/viewtopic.php?t=45710&p=144390

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? i dont know
- Glassfish 4.1.1 mojarra 2.2.9
- firefox, IE

## 2) Expected behavior

Signature component should render

## 3) Actual behavior

Signature component does not render

## 4) Steps to reproduce

use _p:signature_ with mobile renderkit

## 5) Sample XHTML

	<html lang="#{view.locale.language}"
		xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:p="http://primefaces.org/ui"
		xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
		<f:view renderKitId="PRIMEFACES_MOBILE" encoding="UTF-8">
			<h:head>
				<f:facet name="first">
					<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
				</f:facet>
			</h:head>
			<h:body>
				<h:form>
					<p:signature value="#{testBean.signature}"/>
				</h:form>
			</h:body>
		</f:view>
	</html>

## 6) Sample bean

	@ManagedBean(name = "testBean")
	@ViewScoped
	public class TestBean implements Serializable
	{
		private static final long serialVersionUID = 6968768781965840118L;
	
		private String signature;

		public String getSignature()
		{
			return this.signature;
		}
	
		public void setSignature(final String signature)
		{
			this.signature = signature;
		}
	}

**Comment by kukel** [comment]
Did you miss the "important" parts when you created the new issue? Lots of info missing....

**Comment by djmj** [comment]
I updated the issue.

**Comment by tandraschko** [comment]
In 6.1 the mobile renderkit will be deprecated in favor of responsive features. So please provide a PR if would like to get this fixed.

Will close it for now and reopen if a PR is provided.

**Comment by djmj** [comment]
Just right after i send a quote request it gets deprecated. Will be interesting to see if the mobile specific features will still be supported, because mobile works well and is easy to develop with. 

If i know the application will be used 100% on a mobile device i always prefer primefaces mobile. But i stay tuned what you have in mind for us.
