### ISSUE TITLE
Internet Explorer 10 Issue

### ISSUE THREAD

**Issue by ahmedmaksoud** [primefaces/primefaces#2078]
## 1) Environment
- PrimeFaces version: 6
- Does it work on the newest PrimeFaces version?
- Application weblogic + 12c:
- Affected browsers: IE 10

## 2) Expected behavior
try to open http://www.primefaces.org/ultima/
with IE 10   10.0.92
...

## 3) Actual behavior

the page not rendered correctly and scroll appears at the butom  of the page

**Comment by tandraschko** [comment]
Use the ultima repository issue tracker, not the pf core.
