### ISSUE TITLE
SelectOneMenu with Filter and SHIFT Key

### ISSUE THREAD

**Issue by antarus** [primefaces/primefaces#208]
Hello.

In selectOneMenu component with a filter, if we press the SHIFT key when typing in the filter's input , then the filter function does not operate.

Reproduction: showcase Advanced: example
http://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

Thanks

**Comment by cagataycivici** [comment]
We'll check this for 5.2.3, thank you. I see what you mean.

**Comment by sudheerj** [comment]
This issue is fixed here #270

**Comment by cagataycivici** [comment]
See #270 please.
