### ISSUE TITLE
filtering and paginator can not be used together inside dialog tested on 6.0.13 and 6.0.15

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#2083]
## 1) Environment
- PrimeFaces version: 6.0.13 and 6.0.15
- Does it work on the newest PrimeFaces version? No
- Application server + version: jetty 8.1.1.v20120215
- Affected browsers: chrome

## 2) Expected behavior
After filtering the datatable - the row you clicked on should be selected

## 3) Actual behavior
After filtering the datatable - the FIRST row is selected

## 4) Steps to reproduce
Hosted: https://github.com/mores/maven-examples/tree/master/prime-filterPagination

 mvn jetty:run

## 5) Sample XHTML
https://github.com/mores/maven-examples/blob/master/prime-filterPagination/src/main/webapp/resources/components/x/select_modal.xhtml

## 6) Sample bean
https://github.com/mores/maven-examples/blob/master/prime-filterPagination/src/main/java/test/BackingBean.java

Forum thread: http://forum.primefaces.org/viewtopic.php?f=3&t=49121&p=151672#p151672

**Comment by jxmai** [comment]
Is this issue the same as #2137 ? but the version does not match up.

#2137 occurs during 6.0.16

This issue says 6.0.13 and 6.0.15 ...

**Comment by mertsincan** [comment]
Can you please try this issue without composite component?

**Comment by mores** [comment]
Also broken in primefaces 6.1

**Comment by mertsincan** [comment]
Can you please try this issue without composite component?

**Comment by jxmai** [comment]
@mores Can you replicate your code into this test project https://github.com/primefaces/primefaces-test and upload to here as a zip / tar.gz. Currently your sample project is sitting among of a lot of other folders so it is not convenient for others to grab your code and to replcate. Also I don't think we can run your project: https://github.com/mores/maven-examples/blob/master/prime-filterPagination/pom.xml#L88. Elite project is not hosted in maven, so you have a local jar that others don't have.

**Comment by mores** [comment]
The code has been replicated in a fork of that project: https://github.com/mores/primefaces-test/tree/issue-2083

**Comment by jxmai** [comment]
@mores Your code has too much unrelated logic like `composite components`, `setPropertyActionListener` that are hard for us to diagnose the issue ( we don't have the effort to tweak the sample to reorganize all the code since that's not the point ). Also, your sample won't work on 5.x last time I checked. But if you cannot provide a [mcve](https://stackoverflow.com/help/mcve), this issue probably won't be fixed.

**Comment by tandraschko** [comment]
A clean as possible example is really something required for us as many commiters here are just doing this in freetime.
