### ISSUE TITLE
Dialog Framework: dialogReturn is not called back in some case

### ISSUE THREAD

**Issue by zsuiqiang** [primefaces/primefaces#2086]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:6.0.15
- Does it work on the newest released PrimeFaces version? Version?No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Glassfish v4.1
- Affected browsers: Chrome or Edge

## 2) Expected behavior
"dialogReturn" callback correctly.

## 3) Actual behavior
    In some case,it work incorrectly (not callback).
## 4) Steps to reproduce
    If i open  host page Independently，all work correctly. But if i open host page in iframe, there are some problems.

- Case one:
     Open dialog by "openDlgLink" ,when i click "returnDlgBtn" in dialog page, method "createPlanFromStd" is invoked,but method "dialogReturn" is not called back.

- Case two:
     Open dialog by "openDlgBtn" ,when i click "returnDlgBtn" in dialog page, method "createPlanFromStd" is not invoked,and method "dialogReturn" is not called back.
In this case,i get error info: 
```
core.js.jsf?ln=primefaces&v=6.0.15:1  Widget for var 'openDlgBtn' not available!
components.js.jsf?ln=primefaces&v=6.0.15:1 

Uncaught TypeError: Cannot read property 'cfg' of undefined
    at Object.closeDialog (components.js.jsf?ln=primefaces&v=6.0.15:1)
    at Object.closeDialog (core.js.jsf?ln=primefaces&v=6.0.15:1)
    at eval (eval at <anonymous> (jquery.js.jsf?ln=primefaces&v=6.0.15:14), <anonymous>:1:12)
    at eval (<anonymous>)
    at jquery.js.jsf?ln=primefaces&v=6.0.15:14
    at Function.globalEval (jquery.js.jsf?ln=primefaces&v=6.0.15:14)
    at Object.doEval (core.js.jsf?ln=primefaces&v=6.0.15:3)
    at Object.handle (core.js.jsf?ln=primefaces&v=6.0.15:3)
    at Object.success (core.js.jsf?ln=primefaces&v=6.0.15:3)
    at i (jquery.js.jsf?ln=primefaces&v=6.0.15:25)
```
## 5) Sample XHTML
Host page:
```
<p:commandButton id="openDlgBtn" value="openDlgBtn" actionListener="#{maintainPlanManager.selectStd}">
    <p:ajax event="dialogReturn" listener="#{maintainPlanManager.createPlanFromStd}" process="@this" update="plans"/> 
</p:commandButton> 
<p:commandLink id="openDlgLink" actionListener="#{maintainPlanManager.selectStd}"> 
    <i class="fa fa-plus"/>openDlgLink
    <p:ajax event="dialogReturn" listener="#{maintainPlanManager.createPlanFromStd}" process="@this" update="plans"/> 
</p:commandLink>
```
Dialog page:
```
<p:commandButton id="returnDlgBtn" value="returnDlgBtn" actionListener="#{maintainStdManager.dialogReturn}" process="@this,stds"/>
```
## 6) Sample bean
Host Bean:
```
    public void selectStd(ActionEvent e) {
        Map<String, Object> options = new HashMap<>();
        options.put("contentWidth", 800);
        options.put("contentHeight", 400);
        options.put("resizable", true);
        options.put("draggable", true);
        options.put("maximizable", true);
        options.put("minimizable", true);
        options.put("modal", false);

        List<String> param = new ArrayList<>();
        param.add("DlgFrame");
        Map<String, List<String>> paramsMap = new HashMap<>();
        paramsMap.put("viewMode", param);
        RequestContext.getCurrentInstance().openDialog("/maintain/MaintainStdManager", options, paramsMap);
    }


    public void createPlanFromStd(SelectEvent e) {
        MaintainStd[] stds = (MaintainStd[]) e.getObject();
        if (stds == null || stds.length == 0) {
            return;
        }
        for (MaintainStd std : stds) {
            MaintainPlan plan = MaintainPlan.getInstance(std);
            plan.setLocation(location);
            service.create(plan);
            model.add(plan);
        }
    }
```
Dialog Bean
```
    public void dialogReturn(ActionEvent e) {
        RequestContext.getCurrentInstance().closeDialog(getSelections());
    }
```

**Comment by giorgioprimefaces** [comment]
zsuiqiang,
do you have your app working in an iframe? I'm having the same issue with an app working with iframes, if I try to execute it without iframe everything works great, but if I put inside an iframe dialogreturn stops to work

**Comment by erickdeoliveiraleal** [comment]
Try building primefaces yourself

**Comment by ndrikdarto** [comment]
Hi all,
i'm having the same issue. It seems to be an JS error.

![pf fd error js](https://user-images.githubusercontent.com/29494455/27248632-a978ba0c-5330-11e7-986b-79e3ddd897de.PNG)


I use Primefaces 6.1 community library.

has someone solved the issue?

**Comment by cljk** [comment]
I have the same problem.

Tried Primefaces 5.3 and 6.2 (community) on Wildfly 8.2 

I have on one JSF-View three `commandButton`s with dialogs and attached p:ajax "dialogReturn"-Elements. Two of the three are working - the last one NOT. 
It loads the areas which should be updated (see that in developer console of browser) but does not call the listener before or after that. 
I cross-/double checked all logic more than once - It´s really comparable/same. The only difference I can see is that the not-working `p:ajax` inside of a `commandButton` is inside a `p:subTable`.

No JavaScript error in my case - have no exception in the console.

**Comment by cljk** [comment]
"solved" that in a dirty way.
Calling with `p:ajax` a `p:remoteCommand` and calling there the actionListener. This "works"

**Comment by mstichweh** [comment]
And how could you receive the SelectEvent with the dialog return value then? The remoteCommand just calls the listener without any parameter.

I have the same issue each time a commandButton which opens the dailog is within a dataTable. Would be very nice, if this bug can be fixed soon. Currently I could not find any solution to process a dialog return value if it was opened from within a dataTable.

**Comment by cljk** [comment]
TBH I don´t remember. Possible that I didn´t need the return-value - just the action.

But a thinkable 2nd dirty hack could be using a session-scoped bean for that.
Or you try using the action-method with parameters.

**Comment by mstichweh** [comment]
Thanks for your answer! 
I have done it now with an invisible commandButton outside the table which is "clicked" by jQuery from the button inside the table. Not nice, but it works.

**Comment by cljk** [comment]
OMG ... "nice" "solution" ;-)

**Comment by mstichweh** [comment]
After some further debugging I could find the real problem. It was the rendered attribute of the commandButton. If this results to false after closing the dialog, the listener of the dialogReturn event is not called, even if the commandButton is not updated. 
Using css instead of the rendered attribute will work:

```
<p:commandButton actionListener="#{bean.showDialog}" ajax="true" process="@this" update="@none" value="Show dialog" style="#{bean.isButttonVisible()? '' : 'display:none;'}">
    <p:ajax event="dialogReturn" listener="#{bean.handleDialogReturn}" process="@this" update="@this" />
</p:commandButton>
```

**Comment by melloware** [comment]
We believe this issue will be fixed with this PR: https://github.com/primefaces/primefaces/pull/5204

**Comment by tandraschko** [comment]
Would Close it as duplicate
