### ISSUE TITLE
selectManyMenu: poor performance when selecting all elements

### ISSUE THREAD

**Issue by Mobe91** [primefaces/primefaces#2089]
In my view I have a single checkbox that triggers selectAll/unselectAll on a p:selectManyMenu. This is extremely slow for a large item set (~ 2000 elements).

Environment:
- PrimeFaces version: 6.0
Especially slow in Microsoft Edge

**Comment by tandraschko** [comment]
Did you try to optimize the old logic via plain JS methods instead jQuery? Not sure if cloning is the best way.

**Comment by Mobe91** [comment]
No I did not try this, I just took most of the code from the `init` method. However, I did run profiling in MS Edge and the problem is that layouting is performed for each changed item which is extremely costly in total. I prevented this by modifying the cloned version of the DOM and reattaching it once all modifications have been applied. This results in 1 instead of n layouting invocations.
Can you think of any other way to solve this issue without cloning the DOM?

**Comment by tandraschko** [comment]
Not sure - I mostly try to understand performance issues by myself but therefore i need a example like stated in the issue template ;)

**Comment by Mobe91** [comment]
Well then give me a couple of days and I will put together a sample project with lots of select items ;)

**Comment by Mobe91** [comment]
Attached the sample project:
[primefaces-test-project-2089.zip](https://github.com/primefaces/primefaces/files/779182/primefaces-test-project-2089.zip)

**Comment by Mobe91** [comment]
I discovered my approach to show a minor performance penalty in chrome (~20 ms) whereas MS Edge massively benefits from it.

**Comment by tandraschko** [comment]
Could you please provide the ms mesaurement for this cases:
- normal case, without changes
- replacing for example jQuery methods like each with plain JS (like done in this ticket: https://github.com/primefaces/primefaces/issues/2038)
- the very optimized version of the PR

**Comment by Mobe91** [comment]
I quickly ran the benchmarks for Edge/Chrome with/without optimization, here are the results:

- MS Edge (Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393)
    - Normal case, without changes:
        - Toggle: 36s
        - Untoggle: 5s
    - PR version
        - Toggle: 2s
        - Untoggle: 2.5s
- Chrome 59.0.3071.115
    - Normal case, without changes:
        - Toggle: 0.5s
        - Untoggle: 0.5s
    - PR version
        - Toggle: 0.5s
        - Untoggle: 0.5s

So it seems no performance hit in Chrome after all...
I don't have the time right now to try the plain JS modification though...

**Comment by tandraschko** [comment]
boah! thats crazy slow! :D

**Comment by jxmai** [comment]
Before addressing the performance issue, we should at least provide the `selectAll` api natively. 

---

native selectAll: https://github.com/primefaces/primefaces/pull/2896

**Comment by melloware** [comment]
Where did we end up on this fix?  @Mobe91 did you want to submit a PR?

**Comment by Mobe91** [comment]
I submitted a PR for this when I created the issue: https://github.com/primefaces/primefaces/pull/2090
According to the comments I need to rework it a bit - must have overlooked that. I will provide a new PR soon.

**Comment by tandraschko** [comment]
@Mobe91 @melloware I improvided it via the way i mentioned and its quite fast.
Can you try again?

**Comment by Mobe91** [comment]
@tandraschko Testing your commit a184e9d6fec080809c50367443c467c9cf359648, selectAll in MS Edge still takes ~20 seconds with my test project opposed to 2.5 seconds when using cloning.
