### ISSUE TITLE
p:selectOneButton onchange doesn't firing in filter facet

### ISSUE THREAD

**Issue by B-R-Bender** [primefaces/primefaces#2093]
Hello, could you, please, check p:selectOneButton behavior in filter facet, it seems like it doesn't firing onchange event.
I've replaced p:selectOneButton with p:selectOneMenu and it works as expected.

## 1) Environment
- PrimeFaces version: 6.0
- Application server + version: Tomcat 8.0.20
- Affected browsers: tested in google chrome

## 2) Expected behavior
onchange event firing like in p:selectOneMenu
[filterWorks1](http://puu.sh/u5PEU/324d582b36.png)
[filterWorks2](http://puu.sh/u5PK1/e62ef96c3e.png)
[filterWorks3](http://puu.sh/u5POp/5919ab8e6e.png)

## 3) Actual behavior
onchange event doesn't firing
[filterDosen'tWork1](http://puu.sh/u5PYO/a283f516f2.png)
[filterDosen'tWork2](http://puu.sh/u5PZO/63e6d2d7f6.png)
[filterDosen'tWork3](http://puu.sh/u5Q1f/39c33f3c11.png)

## 4) Steps to reproduce
add p:selectOneButton in dataTable filter facet
add onchange="PF('..').filter() to added p:selectOneButton
add selectItem
try to filter data in dataTable with selectOneButton 

## 5) Sample XHTML
```xhtml
<p:dataTable id="allocationResultTable"
                             widgetVar="allocationResultTable"
                             value="#{manualAllocation.result}"
                             filteredValue="#{manualAllocation.filteredResult}"
                             var="resultRecord"
                             rowIndexVar="recordIndex"
                             lazy="false"
                             emptyMessage="#{msg['alloc.dialogs.manualAllocationObjectsDialog.emptyList']}"
                             filterEvent="enter">
                    <p:ajax event="filter"
                            onstart="PF('manualAllocationObjectsMainPanelBlock').show()"
                            oncomplete="PF('manualAllocationObjectsMainPanelBlock').hide()"/>
                    <f:facet name="header">
                        <my:clearFilters widget="allocationResultTable"/>
                        <div class="clear"></div>
                    </f:facet>
                    <p:columns ...
                    </p:columns>
                    <p:column headerText="header"
                              rendered="#{manualAllocation.result.size() > 0}"
                              filterBy="#{resultRecord[6]}"
                              filterMatchMode="exact">
                        <f:facet name="filter">
                            <p:selectOneMenu onchange="PF('allocationResultTable').filter()">
                                <f:selectItem itemLabel="" itemValue="#{null}" noSelectionOption="true" />
                                <f:selectItem itemLabel="#{msg['common.yes']}" itemValue='1'/>
                                <f:selectItem itemLabel="#{msg['common.no']}" itemValue='0'/>
                            </p:selectOneMenu>
<!--
                            <p:selectOneButton onchange="PF('allocationResultTable').filter()">
                                <f:selectItem itemLabel="#{msg['common.yes']}" itemValue='1'/>
                                <f:selectItem itemLabel="#{msg['common.no']}" itemValue='0'/>
                            </p:selectOneButton>
-->
                        </f:facet>
                        <h:outputText value="#{resultRecord[6] == 1? msg['common.yes'] : msg['common.no']}"/>
                    </p:column>
                </p:dataTable>
```
Thank you.
p.s. primefaces is realy nice :)

**Comment by tandraschko** [comment]
Tested the following in a filter facet works fine for me in the current 6.1 snapshot:
                            <p:selectOneButton onchange="console.log('asdasd2');">
                                <f:selectItem itemLabel="Yes" itemValue='1'/>
                                <f:selectItem itemLabel="No" itemValue='0'/>
                            </p:selectOneButton>

As you didn't provide all information requested in the issue template, i will close this as invalid.
