### ISSUE TITLE
Image caching for p:graphicImage still not working in every case

### ISSUE THREAD

**Issue by appldo** [primefaces/primefaces#2097]
For Version: Master

We use the Icarus Layout. There is a picture for the personalrecord in the upper right corner of every page. The picture was created dynamic with  p:graphicImage and is not correctly cached. It is loaded on every page with a different viewid, because the viewid is encrypted in the url.

Before #1765 for each dynamic image a url parameter "pfdrid" with a random String was created. This crashed the browser caching. After #1765 the behaviour is improved by using an encrypted version of viewid and clientid. 

DynamicContentSrcBuilder:
```
  String resourceKey = RequestContext.getCurrentInstance().getEncrypter().encrypt(
                        context.getViewRoot().getViewId() + component.getClientId(context));
```

This helps to cache images on different pages, but cannot cache applicationwide images, because of the then different viewid.

## 1) Environment
- PrimeFaces version: 6 Master (December version of DynamicResourceBuilder), but after code review of the current version the problem persists

## 2) Possible Solution
We patched this by adding an additional attribute "cacheWithView" to the graphicImage, which is true by default.

```
 String resourceKey = RequestContext.getCurrentInstance().getEncrypter().encrypt(
                        (cacheWithView? context.getViewRoot().getViewId(): "") + component.getClientId(context));
```

**Comment by tandraschko** [comment]
Old behavior with security bug:
- put encryted EL expression to the URL
- decrypt EL expression on resource request and invoke it 

Old trunk behavior:
- generate a resourceKey based on view+clientId
- put the resourceKey to the url and remember resourceKey+elExpression in a session map
- on the resource request, get the EL expression via resourceKey and invoke it

behavior now:
- generated a resourceKey -> hash the EL expression with MD5
- put the resourceKey to the url and remember resourceKey+elExpression in a session map
- on the resource request, get the EL expression via resourceKey and invoke it
