### ISSUE TITLE
outputLabel support for p:chips.

### ISSUE THREAD

**Issue by ErickPezoa** [primefaces/primefaces#2099]
## 1) Environment
PrimeFaces version 6.0.15. Tomcat EE 8.5.6

## 2) Expected behavior
When I click on the corresponding chips label, the system should move to the chips component so that I can start typing.

## 3) Actual behavior
When I click on the corresponding chips label, the system doesn't put focus on the chips component.

## 4) Steps to reproduce
(See sample XHTML as reference)
1. Click on the label "CHIPS LABEL"
2. System should put focus on the chips component but it doesn't

## 5) Sample XHTML
<p:outputLabel for="chips" value="CHIPS LABEL:" />
<p:chips id="chips" value="#{testController.test}" />

**Comment by Rapster** [comment]
I plan to use this component as well, so I can take a look at it
