### ISSUE TITLE
Readonly attribute should not prevent decoding value

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2101]
So far, all the PF components (which have a readonly attribute) do not decode submitted value, they behave as they were disabled.
Example:

```java
@Override
    public void decode(FacesContext context, UIComponent component) {
        AutoComplete ac = (AutoComplete) component;
        String clientId = ac.getClientId(context);
        Map<String, String> params = context.getExternalContext().getRequestParameterMap();

        if(ac.isDisabled() || ac.isReadonly()) {
            return;
        }
        
        if(ac.isMultiple()) {
            decodeMultiple(context, ac);
        }
        else {
            decodeSingle(context, ac);
        }
        
        decodeBehaviors(context, ac);
        
        //AutoComplete event
        String query = params.get(clientId + "_query");
        if(query != null) {
            AutoCompleteEvent autoCompleteEvent = new AutoCompleteEvent(ac, query);
            autoCompleteEvent.setPhaseId(PhaseId.APPLY_REQUEST_VALUES);
            ac.queueEvent(autoCompleteEvent);
        }
    }
```

I was wondering what is the difference between readonly and disabled, I read this post: http://stackoverflow.com/questions/7730695/whats-the-difference-between-disabled-disabled-and-readonly-readonly-for-ht, and I realize the isReadOnly shoud not be part of the condition.

What do you think?

**Comment by tandraschko** [comment]
Sorry, don't have time to check that link but why should it make sense to decode a read-only value, if it can't be changed on the client?

**Comment by Rapster** [comment]
Well, I have this use case where the input is not a free text but has to be filled through the selection of an element in a table. You have to imagine that, this component is used everywhere in our app, and this input can be free text sometimes, So we decided to reuse the same component, and play with disabled/readonlu. If it's not possible I will override the renderer. I opened this ticket only to be compliant with the HTML spec _(and so I don't have to patch this myself :) )_.

**Comment by tandraschko** [comment]
Not sure as the input can be changed easily with firebug or something, so it might a security thing ;)

**Comment by Rapster** [comment]
Let's close it for now
