### ISSUE TITLE
Add PrimeFaces css to p:signature

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2102]
PrimeFaces version: 6.0.14 - see showcase

Instead of using the keith-wood simple css class _kbw-signature_ signature looks much better using PrimeFaces css classes _ui-inputfield ui-widget ui-state-default ui-corner-all_.

On readonly one could use _ui-widget ui-widget-content ui-corner-all_.

The _kbw-signature_ class is the single css rule in a separate css file. Unnecessary if using PrimeFaces classes.

You can see a (responsive )demo here: 

https://github.com/djmj/signature
http://htmlpreview.github.io/?https://github.com/djmj/signature/blob/master/test/index.html

**Comment by melloware** [comment]
If you already have a solution above why not propose a pull request?

**Comment by tandraschko** [comment]
Please provide a PR.
