### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by saurabhiitr** [primefaces/primefaces#2103]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

in autocomplete multiselect if dropdown=true dropdown button button is below the input area

## 3) Actual behavior

it should be alongside like as in autocomplete when multiselect is false and dropdown = true

## 4) Steps to reproduce

temporay changed it on autocomple.css file
 .ui-autocomplete .ui-autocomplete-dropdown {
    position: absolute;
    height: 27px;
    width: 2.4em;
    right: -32px;
	top: 0px;
}

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
#1478
next time use the search first.
Also the issue is invalid as you didn't answer the questions and didn't provide a example.
