### ISSUE TITLE
Class ui-widget on p:commandLink and p:link breaks Font Awesome

### ISSUE THREAD

**Issue by miguelkv** [primefaces/primefaces#2104]
The `p:commandLink` does not work with Font Awesome icons:

`<p:commandLink styleClass="fa fa-fw fa-search" />`

As verified by @djmj in #648, the reason for this is that PrimeFaces adds the `ui-widget` CSS class to the <a> tag, which have a different font ("`'titillium_webregular' !important`").

One workaround (or possible solution?):
`.ui-widget.ui-commandlink.fa{ font: normal normal normal 14px/1 FontAwesome !important; }`

This error can be seen at http://www.primefaces.org/eos/sentinel/forms.xhtml.

**Comment by melloware** [comment]
I would report this to the sentinel team to have them fix this in their CSS.  It seems to work fine with bare bones PF without a custom theme.  Report this issue to Sentinel here:

https://forum.primefaces.org/viewforum.php?f=23

**Comment by tandraschko** [comment]
Yep, or use the layouts issue tracker.
