### ISSUE TITLE
Building From Source - Missing Files

### ISSUE THREAD

**Issue by hinneLinks** [primefaces/primefaces#2108]
For a seperate Bug i've tried to test it with the newest sources from Github, as described here: https://github.com/primefaces/primefaces/wiki/Building-From-Source

I can clone it, but can't compile it, since a lot of Java-Classes are missing, e.g. org.primefaces.component.ajaxexceptionhandler.AjaxExceptionHandler

If i try to locate that file with the GitHub-Website, I can't find it either (https://github.com/primefaces/primefaces/tree/master/src/main/java/org/primefaces/component/ajaxexceptionhandler ).

Do I have to checkout a additional Repository to built the sources?

**Comment by tandraschko** [comment]
They are generated by maven.

**Comment by tandraschko** [comment]
Next time use the forum for questions.
