### ISSUE TITLE
PrimeExceptionHandler generates invalid partial response for namespaced applications

### ISSUE THREAD

**Issue by vsingleton** [primefaces/primefaces#211]
Steps to reproduce:
1.  follow the example given for [the ExceptionHandler](http://www.primefaces.org/showcase/ui/misc/exceptionHandler.xhtml)
2.  deploy your application to a portlet container

Expected results:
- same as when deploying on plain tomcat

Actual results:
- PrimeFaces.ajax.ResponseProcessor.doEval(currentChangeNode) is never called because the partial-response has an extra "changes" element written in by the PrimeExceptionHandler.

**Comment by vsingleton** [comment]
Please consider this fix for the issue:
https://github.com/primefaces/primefaces/pull/212

Thank you.

**Comment by cagataycivici** [comment]
Thank you Vernon, @tandraschko what do you think?

**Comment by tandraschko** [comment]
@cagataycivici will take care of it.

@vsingleton I actually not sure about this "hack". We completely reset the response to get complete control over the response. This is required because of mojarra. So why liferay always writes an "changes" node? So writer.startDocument() in liferay does more than a JSF impl.

**Comment by tandraschko** [comment]
The issue title also says that it's related to parameter namespacing. So i assume that it would work on liferay without parameter namespacing? e.g. on older versions?

**Comment by vsingleton** [comment]
Thomas, may be right.  My bad.  Diving deeper ...

**Comment by vsingleton** [comment]
Thanks for your quick response, it has stirred me to look deeper.

As tandraschko asked:

> So why liferay always writes an "changes" node?

I wish it were Liferay that was doing this, but unfortunately it is other impls in this case.  Basically, the current flow in PrimeFaces goes like this:
1. PrimeExceptionHandler [calls startDocument](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandler.java#L167) which is fine ...
2. but that is in PrimePartialResponseWriter, which [calls encodeCallbackParams](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/context/PrimePartialResponseWriter.java#L157) which itself [calls startExtension](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/context/PrimePartialResponseWriter.java#L51) (this will cause 'changes' to be written by [any](http://myfaces.apache.org/core22/myfaces-api/xref/javax/faces/context/PartialResponseWriter.html#193) [impl](https://github.com/ngriffin7a/mojarra-svn2git-2.2.x/blob/master/jsf-api/src/main/java/javax/faces/context/PartialResponseWriter.java#L327) following the spec, since 'extension' is a child of 'changes' ... see note below)
3. then the PrimeExceptionHandler [calls startElement("changes", null)](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandler.java#L168)

This is how we end up with an invalid partial-response that has 'changes' inside of 'changes' something like this: 

``` xml
<partial-response id="_my_favorite_namespace_">
    <changes>
        <extension ln="primefaces" type="args">{"parameterNamespace":"_my_favorite_namespace_"}</extension>
        <changes>
            <update id="_my_favorite_namespace_:j_idt42:exceptionDialog"><![CDATA[<div id="_my_favorite_namespace_:j_idt42:exceptionDialog" class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-hidden-container"> foo </div><script id="_my_favorite_namespace_:j_idt42:exceptionDialog_s" type="text/javascript">$(function(){PrimeFaces.cw("Dialog","exceptionDialog",{id:"_my_favorite_namespace_:j_idt42:exceptionDialog",widgetVar:"exceptionDialog",height:"500px"});});</script>]]></update>
            <eval><![CDATA[var hf=function(type,message,timestampp){PF('exceptionDialog').show();};hf.call(this,"javax.faces.application.ViewExpiredException","viewId:\/views\/index.xhtml - A ViewExpiredException!","2015-04-30 02:44:53");]]></eval>
        </changes>
    </changes>
</partial-response>
```

note: According to [the schema here](http://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/web-partialresponse_2_2.xsd): lines 150-201 only allow for 'extension' as a child of 'changes', but 'changes' are not allowed inside of 'changes'.  Since PrimePartialResponseWriter has [already called startExtension](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/context/PrimePartialResponseWriter.java#L51), the first 'changes' has already been written (by any implementation that is following the schema).  So your subsequent call to startElement("changes", null) makes the partial response invalid.

You may want to refactor the PrimeExceptionHandler another way ... maybe calling only startDocument, startExtension, startUpdate, startError, startEval, etc ...  trying never to break that pattern by calling startElement ... however you want to do this it's up to you, but calling startElement("changes", null) after calling startExtension is where the problem lies, as far as I can see.

Thanks again for taking time to consider this pull request.

**Comment by tandraschko** [comment]
Thanks for digging deeper and for providing an PR!
Just applied your PR + added a more detailed comment.
