### ISSUE TITLE
p:lifecycle has not set ignoreAutoUpdate=true

### ISSUE THREAD

**Issue by kapitanrum** [primefaces/primefaces#2112]
## 1) Environment
- PrimeFaces version: 6.0.15
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: Tomcat 8.0
- Affected browsers: All

## 2) Expected behavior
Do not refresh components with attribute autoupdate=true (p:messages, p:outputPanel, p:growl) for component p:lifecycle.

## 3) Actual behavior
Component p:lifecycle call ajax and for component <p:messages autoUpdate="true"> messages disappears.

## 4) Sample XHTML 
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h1>#{testView.testString}</h1>
        <p:messages autoUpdate="true" showDetail="true" />
        <h:form>
            <h:inputText required="true"/>
            <p:commandButton value="send" />
        </h:form>
        <p:lifecycle />
    </h:body>
</html>

## 5) Workaround
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h1>#{testView.testString}</h1>
        <p:messages autoUpdate="true" showDetail="true" />
        <h:form>
            <h:inputText required="true"/>
            <p:commandButton value="send" />
        </h:form>
        <p:lifecycle />
        
        
        <script type="text/javascript">
          PrimeFaces.widget.Lifecycle.prototype.update = function() {
                this.updating = true;
                var $this = this;
                var options = {
                    source: this.id,
                    process: this.id,
                    update: this.id,
                    ignoreAutoUpdate: true,
                    formId: this.cfg.formId,
                    params: [{ name: this.id + '_getlifecycleinfo', value: true }],
                    oncomplete: function(xhr, status, args) {
                        $this.updating = false;
                    }
                };
                PrimeFaces.ajax.Request.handle(options);
            }               
          </script>        
    </h:body>
</html>

**Comment by tandraschko** [comment]
Feel free to provide a PR.
