### ISSUE TITLE
The children of a deferred OutputPanel should use the same ViewScope

### ISSUE THREAD

**Issue by robertpanzer** [primefaces/primefaces#2114]
## 1) Environment
- PrimeFaces version: 6.0, 6.0.10 and 6.1-SNAPSHOT
- Application server + version: TomEE 7.0.2 with myfaces, but I've also seen this with Mojarra 2.2.13
- Affected browsers: Current version of Chrome and Safari on OS X

## 2) Expected behavior

When the content of a `<p:outputPanel deferred="true" deferredMode="load"/>` is rendered it should use the same ViewScope as used by the owning part.

I couldn't find any documentation saying what scope is supported, therefore I simply assumed that ViewScope should be supported.
If I'm wrong simply close this ticket.

## 3) Actual behavior

Two ManagedBeans are created, therefore rendering two different values.

## 4) Steps to reproduce

Clone the project https://github.com/robertpanzer/primefacestest and run the application as documented in the README:

```
mvn clean package tomee:run
```

## 5) Sample XHTML

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <f:facet name="first">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    </f:facet>
    <title>Test page</title>
</h:head>

<h:body styleClass="main-body">

    <p:outputPanel>
        <h1>Hello World</h1>

        <p>My sync ID is <h:outputText value="#{testController.id}"/></p>

        <p:outputPanel deferred="true" deferredMode="load">
            <p>My async ID is <h:outputText value="#{testController.id}"/></p>
        </p:outputPanel>

    </p:outputPanel>

</h:body>
</html>
```

## 6) Sample bean

```java
package foo.bar;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.UUID;

@ViewScoped
@ManagedBean
public class TestController implements Serializable {


  private String id;

  @PostConstruct
  public void init() {
    this.id = UUID.randomUUID().toString();
  }

  public String getId() {
    return id;
  }
}
```

**Comment by tandraschko** [comment]
No form -> no viewstate-id to post -> new view every post

**Comment by robertpanzer** [comment]
Thank you!

Sorry for spamming!
