### ISSUE TITLE
Ajax menu item no longer work

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2117]
## 1) Environment
- PrimeFaces version: 6.1-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? Yes
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Jetty
- Affected browsers: Chrome

## 2) Expected behavior
Action should be executed

## 3) Actual behavior
Nothing happens, except ajax status keeps loading 

## 4) Steps to reproduce
- Build the last source and go: http://localhost:9999/showcase/ui/menu/menuButton.xhtml
- Select Save
- Ajax status keeps loading

## 5) Sample XHTML
```xml
<h:form>
    <p:growl id="messages" showDetail="true"/>
 
    <p:menuButton value="Options">
        <p:menuitem value="Save" actionListener="#{menuView.save}" update="messages" icon="ui-icon-disk"/>
        <p:menuitem value="Update" actionListener="#{menuView.update}" update="messages" icon="ui-icon-arrowrefresh-1-w"/>
        <p:menuitem value="Delete" actionListener="#{menuView.delete}" ajax="false" icon="ui-icon-close"/>
        <p:separator />
        <p:menuitem value="Homepage" url="http://www.primefaces.org" icon="ui-icon-extlink"/>
    </p:menuButton>
</h:form>
```

## 6) Sample bean
Not important...

## 7) Analysis
I suspect this commit #1900 to be responsible of this regression, so I added `<p:log />`
 to the page, after clicking on "Save" the following error message appears:

> Skip AJAX request as the source element doesn't exist anymore. Id: j_idt87:j_idt89

Indeed, id is not written by `BaseMenuRenderer`, because `CoreRenderer.shouldWriteId` returns false:
```java
    protected boolean shouldWriteId(UIComponent component) {
        String id = component.getId();

        return (null != id) && (!id.startsWith(UIViewRoot.UNIQUE_ID_PREFIX) || ((component instanceof ClientBehaviorHolder) &&
                          ! ((ClientBehaviorHolder) component).getClientBehaviors().isEmpty()));
    }
```

Setting an id on menuitem will make it work

**Comment by tandraschko** [comment]
Would you like to check if mojarra and myfaces always writes the ID on p:ajax attachable components (h:commandButton/link and else)? Otherwise we have to revert this new feature. (Would be great if you could do it today, we will likely release a RC1 tomorrow)

**Comment by Rapster** [comment]
MyFaces does this:

```java
/**
     * Returns true if the component should render an ID.  Components
     * that deliver events should always return "true".
     * @todo Is this a bottleneck?  If so, optimize!
     */
    protected boolean shouldRenderId(
      FacesContext context,
      UIComponent  component)
    {
      String id = component.getId();

      // Otherwise, if ID isn't set, don't bother
      if (id == null)
        return false;

      // ... or if the ID was generated, don't bother
      if (id.startsWith(UIViewRoot.UNIQUE_ID_PREFIX))
        return false;

      return true;
    }
```

Mojarra does that:
```java
    /**
     * @param component the component of interest
     *
     * @return true if this renderer should render an id attribute.
     */
    protected boolean shouldWriteIdAttribute(UIComponent component) {

        // By default we only write the id attribute if:
        //
        // - We have a non-auto-generated id, or...
        // - We have client behaviors.
        //
        // We assume that if client behaviors are present, they
        // may need access to the id (AjaxBehavior certainly does).

        String id;
        return (null != (id = component.getId()) &&
                    (!id.startsWith(UIViewRoot.UNIQUE_ID_PREFIX) ||
                        ((component instanceof ClientBehaviorHolder) &&
                          !((ClientBehaviorHolder)component).getClientBehaviors().isEmpty())));
    }
```

Looks like we do like Mojarra

**Comment by tandraschko** [comment]
does that mean that no id is rendered (if not set as attribute) in MyFaces on a commandButton?

**Comment by Rapster** [comment]
I should've has indicate that MyFaces uses `HtmlRenderer` and Mojarra uses `HtmlBasicRenderer`. Primefaces uses his own renderer which his `CoreRenderer` as you know. Anyway, id is rendered every time in commandButton, there is no condition on this. I don't understand why sometime id is not rendered depdending the component

**Comment by Rapster** [comment]
I just have a deeper look on `OutcomeTargetButtonRenderer`, renderer used by `HtmlCommandButton` in Mojarra. id is not always rendered, while PF does. Is this correct? Looks like we should always call `shouldWriteId` before writing clientId

**Comment by tandraschko** [comment]
for me it makes sense to always render a clientId to a command/executing component.
I think it's micro-optimization in the JSF impls as a non-command-component mostly don't need a id in the markup.
