### ISSUE TITLE
PDF problem on Media component with IE

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2118]
Reported By PRO User;
> We have problem with the p:media component to show a pdf in Internet Explorer 11.
...

**Comment by tandraschko** [comment]
@mertsincan Could you please explain your fix? IMO you introduced a concurrency bug now.

**Comment by mertsincan** [comment]
Thanks @tandraschko , I made some changes on my fix.

**Comment by activey** [comment]
Ok folks, are you gonna introduce it in 6.0 version? We're using it here in our company and this is the version we pay license for ... What shall I do then? :P

**Comment by activey** [comment]
Guys, how about 6.0 version? Is there any chance to get this fix for this version as well?

**Comment by activey** [comment]
Ok, doesn't matter, I've done pretty much the same as you did here hehe, overrided class definition and it works ;>

**Comment by tandraschko** [comment]
I think it was merged to 6.0 branch but no garantue, i don't develop in elite branches ;)

**Comment by tandraschko** [comment]
Also you have to change your code if you use SessionScoped beans for this. See: https://github.com/primefaces/primefaces/issues/2141

**Comment by activey** [comment]
@tandraschko k thx ;)
