### ISSUE TITLE
JSF 2.3: p:fileUpload does not prepend the parameter namespace prefix 

### ISSUE THREAD

**Issue by ngriffin7a** [primefaces/primefaces#2121]
## 1) Environment
- PrimeFaces version: 6.1 master
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 8 / Pluto 3.0 / Liferay Faces Bridge 6.x
- Affected browsers: N/A

## 2) Expected behavior

Uploading file with p:fileUpload using the primefaces-applicant-portlet should cause the file to be uploaded.

## 3) Actual behavior

The file is not uploaded

## 4) Steps to reproduce

A. Download the Pluto 3.0 Tomcat bundle from https://portals.apache.org/pluto/ and unzip to ~/pluto

B. Build Mojarra 2.3 from the Mojarra master branch: https://github.com/javaserverfaces/mojarra
ant clean main mvn.deploy.snapshot.local

C. Copy $HOME/.m2/repository/org/glassfish/javax.faces/$2.3.0-SNAPSHOT/javax.faces-$2.3.0-SNAPSHOT.jar pluto/tomcat/lib

D. Extract the jar, remove the META-INF/services/javax.servlet.ServletContainerInitializer file, and re-zip the jar

E. Clone the Liferay Faces Bridge API and Impl repositories:
https://github.com/liferay/liferay-faces-bridge-api
https://github.com/liferay/liferay-faces-bridge-impl

F. Build each clone:

cd liferay-faces-bridge-api
mvn clean install
cd ../liferay-faces-bridge-impl
mvn clean install

G. Build the primefaces-applicant-portlet demo for use with Apache Pluto:

cd demo/primefaces-applicant-portlet
mvn -P pluto,mojarra,tomcat clean package

H. Deploy the resulting WAR to Pluto+Tomcat:

cp target/com.liferay.faces.demo.primefaces.applicant.portlet*.war ~/pluto/tomcat/webapps/com.liferay.faces.demo.primefaces.applicant.portlet.war

I. Add the primefaces-applicant-portlet to a Pluto portal page

J. Select a file and upload it

## 5) Sample XHTML

https://github.com/liferay/liferay-faces-bridge-impl/blob/master/demo/primefaces-applicant-portlet/src/main/webapp/WEB-INF/views/applicant.xhtml#L146

## 6) Sample bean

https://github.com/liferay/liferay-faces-bridge-impl/blob/master/demo/primefaces-applicant-portlet/src/main/java/com/liferay/faces/demos/bean/ApplicantBackingBean.java#L92

**Comment by ngriffin7a** [comment]
PR: https://github.com/primefaces/primefaces/pull/2122

**Comment by tandraschko** [comment]
@ngriffin7a thanks for the good patch! I just did a small refactoring on the fileupload script to reuse PrimeFaces.ajax. Would be great if you could give it a try :)

**Comment by ngriffin7a** [comment]
It works, thanks for the improvement! :)
