### ISSUE TITLE
p:confirmDialog shows grayed-out screen in a portlet environment

### ISSUE THREAD

**Issue by ngriffin7a** [primefaces/primefaces#2123]
## 1) Environment
- PrimeFaces version: 6.1 master (built *WITHOUT* the release profile)
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 8 / Pluto 3.0.0
- Affected browsers: N/A

## 2) Expected behavior

The primefaces-applicant renders correctly on the page and there are no JS console errors.

## 3) Actual behavior

The p:calendar component does not render its date picker button, and "Uncaught SyntaxError: Unexpected identifier" will appear in the JS console due to Line 6360 in core.js that contains an invalid "Â" character:

```
if(virtualScrollBody.scrollTop + viewportHeight > parseFloat($this.scrollBodyTable.css('top')) + tableHeight ||Â virtualScrollBody.scrollTop < parseFloat($this.scrollBodyTable.css('top'))) {
```

## 4) Steps to reproduce

A. Download the Pluto 3.0 Tomcat bundle from https://portals.apache.org/pluto/ and unzip to ~/pluto

B. Build Mojarra 2.3 from the Mojarra master branch: https://github.com/javaserverfaces/mojarra
ant clean main mvn.deploy.snapshot.local

C. Copy $HOME/.m2/repository/org/glassfish/javax.faces/$2.3.0-SNAPSHOT/javax.faces-$2.3.0-SNAPSHOT.jar pluto/tomcat/lib

D. Extract the jar, remove the META-INF/services/javax.servlet.ServletContainerInitializer file, and re-zip the jar

E. Clone the Liferay Faces Bridge API and Impl repositories:
https://github.com/liferay/liferay-faces-bridge-api
https://github.com/liferay/liferay-faces-bridge-impl

F. Build each clone:

cd liferay-faces-bridge-api
mvn clean install
cd ../liferay-faces-bridge-impl
mvn clean install

G. Build the primefaces-applicant-portlet demo for use with Apache Pluto:

cd demo/primefaces-applicant-portlet
mvn -P pluto,mojarra,tomcat clean package

H. Deploy the resulting WAR to Pluto+Tomcat:

cp target/com.liferay.faces.demo.primefaces.applicant.portlet*.war ~/pluto/tomcat/webapps/com.liferay.faces.demo.primefaces.applicant.portlet.war

I. Add the primefaces-applicant-portlet to a Pluto portal page

J. Reload the portal page

## 5) Sample XHTML

https://github.com/liferay/liferay-faces-bridge-impl/blob/master/demo/primefaces-applicant-portlet/src/main/webapp/WEB-INF/views/applicant.xhtml

## 6) Sample bean

N/A

**Comment by ngriffin7a** [comment]
Assign to @stiemannkj1

**Comment by ngriffin7a** [comment]
@stiemannkj1 I changed the title and description of this issue to "Invalid unicode character in uncompressed core.js" -- please try to reproduce. Thanks.

**Comment by ngriffin7a** [comment]
@stiemannkj1 No need for you to try and reproduce. I was able to reproduce it with the PrimeFaces Showcase in a plain webapp.

**Comment by ngriffin7a** [comment]
@tandraschko If you could take a look at this I would appreciate it. This is only a problem when components.js is *not* minified, meaning, when the "release" profile is *not* specified during the Maven build. If you deploy the PrimeFaces Showcase as tomcat/webapps/primefaces-showcase.war then you can use the Chrome "Inspect" tab to inspect the sources for this URL:
http://localhost:8080/primefaces-showcase/javax.faces.resource/components.js.xhtml?ln=primefaces&v=6.1.RC2-SNAPSHOT
If you right click on the URL in the "Sources" tab then you can do a "Save As" to save the file.
If you examine the file with an editor like vim and go to line 6360, the character at position 132 (just before `virtualScrollBody.scrollTop`) is not a space character.

**Comment by tandraschko** [comment]
Replaced it with a "new" space. Does it work now?

**Comment by ngriffin7a** [comment]
@tandraschko That fixed it, thanks!
