### ISSUE TITLE
TreeTable: add Lazy feature with pagination

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2124]
Just like http://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml

But it is more tricky to do it, as lazyness can be done on a node itself and on pagnination

**Comment by kukel** [comment]
and filtering ;-)  Will create a new feature request to for this.

(and still have to find out how the sorting actually works for other than first column does not always seem intuitive)

**Comment by Rapster** [comment]
Let's reuse this one #1929 (I created one ticket for two features, my bad...) But we can always rename #1929 and create a new one for TreeTable

**Comment by melloware** [comment]
Replaced by https://github.com/primefaces/primefaces/issues/11250
