### ISSUE TITLE
KeyFilter does not work for new component <p:chips>

### ISSUE THREAD

**Issue by amoralico** [primefaces/primefaces#2125]
1) Environment
Primefaces 6.1.RC1
- Tomcat 8
- Chrome, Firefox, all i guess

## 2) Expected behavior
Try to use <p:keyfilter for="chips" mask="pint"> associated with the new component <p:chips id="chips"> to restrict key entry only for digits.

## 3) Actual behavior
I can entry any character.

## 5) Sample XHTML
<p:chips id="chips">
...  
</p:chips> 
<p:keyfilter for="chips" mask="pint" />

I found a patch for this problem by overriding the keyfilter (javascript) widget. In the init function 
replace the jquery selector ':not(:submit):not(:button):input:visible:enabled:first' by ':not(:submit):not(:button):input:enabled:first'

**Comment by tandraschko** [comment]
Would you please try a trunk build? I modified the keyfilter java renderer, it might work now.
