### ISSUE TITLE
Layout Adamantium 2.1.3 css problem on 6.1.RC1

### ISSUE THREAD

**Issue by benoitbb** [primefaces/primefaces#2126]
## 1) Environment
- PrimeFaces version: 6.1.RC1
- Work well on 6.0 
- Jboss 6.4 eap : 
- Affected browsers: Firefox ESR (45.7.0) only (No problems on chrome for example)

This issue for 2 problems:
1) First one on a <p:calendar> input with "showOn" button activated when used in conjunction with a <p:sticky> component. The icon of the input calendar does not come back to its initial state.  

See the code in attachment.

2) Problem in  <p:selectCheckboxMenu>. The clickable arrow to drop down the menu is completely out of the component. I investigate with firebug and apparently a css rule has changed in component.css file.

I think the problem may come from a change in the css rule for this small part of code:

`<span class="ui-icon ui-icon-triangle-1-s"></span>`

In 6.0.0 it was :
`.ui-selectcheckboxmenu .ui-selectcheckboxmenu-trigger .ui-icon {
    margin-top: 3px;
}
`
In 6.1.RC1 it is:

`.ui-selectcheckboxmenu .ui-selectcheckboxmenu-trigger .ui-icon {
    position: relative;
    top: 50%;
    margin-top: -8px;
}`

Can you please have a look to these problems please ?

Thank you.
Regards,

![primefaces_select_menu_input_problem](https://cloud.githubusercontent.com/assets/9993790/23398686/c69a7b36-fd9d-11e6-8d52-89d172e6b46c.png)
![primefaces_calendar_input_problem](https://cloud.githubusercontent.com/assets/9993790/23398685/c6991386-fd9d-11e6-894e-fdbaf3c74c4d.png)

[primefaces_input_calendar_problem.txt](https://github.com/primefaces/primefaces/files/806194/primefaces_input_calendar_problem.txt)

**Comment by tandraschko** [comment]
@mertsincan is this something that should be fixed in the layouts or in PF core?

**Comment by benoitbb** [comment]
Hello,

I think 1 and 2 comes from Adamantium Layout. But I am not sure at 100 %.

Thank you.
Regards,

**Comment by mertsincan** [comment]
The first issue is fixed for 6.0.17; https://github.com/primefaces/primefaces/issues/2182

I couldn't replicate the second issue. I think it is a layout. Therefore, please use Adamantium forum;  https://forum.primefaces.org/viewforum.php?f=28
Please create a new topic in it and add a sample xhtml page to your topic.
