### ISSUE TITLE
Picklist: disabled items allow for client-side manipulation

### ISSUE THREAD

**Issue by DaHoC** [primefaces/primefaces#2127]
This may cause security issues in cases where people rely on the disabled items assignment not being able to be manipulated on the client-side.

## 1) Environment
- PrimeFaces version: 6.0 and 6.0.15 and newest
- Does it work on the newest released PrimeFaces version? Version?
- Application server + version: Apache Tomcat 8.5.11
- Affected browsers: All

## 2) Expected behavior
Disabled items cannot be transferred from source to target list or vice-versa.
Real behaviour: 

## 3) Actual behavior
Items can be transferred from source to target list or vice-versa by client-side manipulation, by removing the disabling CSS style class.

## 4) Steps to reproduce
I use a picklist with "itemDisabled" property.
The disabled entries can't be dragged or transferred from source list to target list and vice versa, as one would expect.

However, by simply removing the style class, e.g. via jQuery
`$('ul.ui-picklist-list > li.ui-state-disabled').removeClass('ui-state-disabled');`
I am able to swap items between the source and target lists.
These changes are then applied to the model (here: `personBean.personAssignment` DualListModel) upon submit, because a respective server-side check is missing.

## 5) Sample XHTML
```
<p:pickList id="personAssignment"
            value="#{personBean.personAssignment}"
            var="person"
            itemDisabled="true"
            itemLabel="#{person.toString()}"
            itemValue="#{person}"/>
```

## 6) Sample bean

```
public class PersonBean {
  private DualListModel<Object> personAssignment;

  public DualListModel<Object> getPersonAssignment() {
    if (personAssignment == null) {
        List<Object> source = Arrays.asList(new String[]{"One", "Two"});
        List<Object> target = Arrays.asList(new String[]{"A", "B"});
        personAssignment = new DualListModel<>(source, target);
    }
    return personAssignment;
  }

  public void setPersonSelection(DualListModel<Object> personAssignment) {
    this.personAssignment = personAssignment;
  }

}

```

**Comment by DaHoC** [comment]
Our current solution: Override component's "validateValue" function in the following fashion:

```
  @Override
  protected void validateValue(FacesContext facesContext, Object newValue)
  {
    super.validateValue(facesContext, newValue);

    final DualListModel<?> newModel = (DualListModel<?>) newValue;
    final DualListModel<?> oldModel = (DualListModel<?>) this.getValue();
    checkForClientSideManipulationDisabled(newModel.getSource(), oldModel.getSource());
    checkForClientSideManipulationDisabled(newModel.getTarget(), oldModel.getTarget());
  }

  /**
   * Prohibits client-side manipulation of disabled entries, when CSS style-class ui-state-disabled is removed.
   * See <a href="https://github.com/primefaces/primefaces/issues/2127">https://github.com/primefaces/primefaces/issues/2127</a>
   *
   * @param newEntries new/set entries of model source/target list
   * @param oldEntries old/former entries of model source/target list
   */
  private void checkForClientSideManipulationDisabled(final List<?> newEntries, final List<?> oldEntries)
  {
    final String varName = getVar();
    for (final Object item : newEntries)
    {
      // Set the current item in request map to get its properties via stateHelper().eval() call
      FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put(varName, item);
      boolean itemDisabled = isItemDisabled();
      // Check if disabled item has been moved from its former/original list
      if (itemDisabled && !oldEntries.contains(item))
      {
        setValid(false);
        // Show validation or error message
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, "text", "detail");
        FacesContext.getCurrentInstance().addMessage(this.getClientId(), message);
      }

    }
  }

```

**Comment by tandraschko** [comment]
Instead of overwriting a component method, i would try to attach a validator.

**Comment by DaHoC** [comment]
That would be a workaround.
But as it is the component's responsibility to validate the client-side input, I think it should be part of the component code, and not additional code I have to handle and think of myself - Even more so as it is not transparent to the developer that the component allows for such easy tampering/manipulation on the client-side

**Comment by melloware** [comment]
@DaHoC Please review my PR.  https://github.com/primefaces/primefaces/pull/3275  I made some slight changes to your code and chose a standard validation message.

**Comment by DaHoC** [comment]
@melloware Reviewed your PR, nice
