### ISSUE TITLE
moment.js warning in p:schedule

### ISSUE THREAD

**Issue by benoitbb** [primefaces/primefaces#2131]
Hello, I have problem with the schedule component in the last version 6.1.RC. Works perfectly on 6.0.0.

## 1) Environment
- PrimeFaces version: 6.1.RC
- Does it work on the newest released PrimeFaces version? Version? No
- Application server + version: jboss eap 6.4
- Affected browsers: chrome( 56.0.2924.87 (64-bit) ), firefox (45.7.0)

## 2) Expected behavior
I expect a working schedule component ;-)

## 3) Actual behavior
Not working : javascript error when using columnFormat options (see attachments)

## 4) Steps to reproduce
Just use a schedule with a columnFormat parameter

## 5) Sample XHTML
`
<p:schedule id="schedule" value="#{serviceEditionController.eventModel}"
      widgetVar="myschedule"
      showWeekNumbers="true"
      displayEventEnd="true"
      aspectRatio="2.2"
      timeZone="#{serviceEditionController.timeZone}"
      locale="#{serviceEditionController.locale}"
      showWeekends="true"
      slotDuration="60"
      view="month"
      rightHeaderTemplate="basicWeek,month"
      scrollTime="00:00:00"
      allDaySlot="false"
      timeFormat="DD/MM HH:mm"
      columnFormat="dd DD/MM"
      draggable="false"
      axisFormat="HH">
</p:schedule>
`

NB: When I remove this columnFormat option, the component is working but I have a "strange" warning (See attachments).

Can you have a look please ?

Thank you.

Best Regards,
Benoît

![warning_primefaces_scheduler](https://cloud.githubusercontent.com/assets/9993790/23501105/d1709b3a-ff32-11e6-9df8-3bdb73576744.png)
![error_primefaces_scheduler2](https://cloud.githubusercontent.com/assets/9993790/23501107/d1727324-ff32-11e6-86bf-c9a739242530.png)
![error_primefaces_scheduler1](https://cloud.githubusercontent.com/assets/9993790/23501106/d171b204-ff32-11e6-95b1-a39463f292a7.png)

**Comment by tandraschko** [comment]
AFAICS it should be used like here: https://github.com/primefaces/primefaces/issues/1472

So there is not bug, but the warning.

**Comment by benoitbb** [comment]
Sorry but have a look at the 2 last images. There is a bug with when using "columnFormat" parameter on the component schedule. The schedule does not work at all by using this parameter.

Thank you.

**Comment by tandraschko** [comment]
Sorry but have a look at the link that i posted :P columnFormnat shoudln't be used like in your example.

**Comment by benoitbb** [comment]
Yes sorry, I read your answer too fast. It is ok for me. Sorry again ;-).

I close the ticket.
