### ISSUE TITLE
captcha not evaluate public/private key param in web.xml

### ISSUE THREAD

**Issue by marcozanghi** [primefaces/primefaces#2133]
PrimeFaces version: "6.0"

I have defined an EL into web.xml to place the private/public key of the captcha but the captcha component not evaluate that expression.
```
  <context-param>
        <param-name>primefaces.PRIVATE_CAPTCHA_KEY</param-name>
        <param-value>#{configuration.privateCaptchaKey}</param-value>
    </context-param>
 <context-param>
        <param-name>primefaces.PUBLIC_CAPTCHA_KEY</param-name>
        <param-value>#{configuration.publicCaptchaKey}</param-value>
    </context-param>
```
It seems that the primefaces component don't calls evaluateExpressionGet() but the simple context.getExternalContext().getInitParameter().
```
@ManagedBean
@ApplicationScoped
public class Configuration {
 ...
```
(For the theme param it seems to work - http://forum.primefaces.org/viewtopic.php?f=3&t=49757) 

Any Suggestion?
Thanks.

**Comment by tandraschko** [comment]
Please provide a PR

**Comment by marcozanghi** [comment]
#2135

**Comment by erickdeoliveiraleal** [comment]
This commit caused an error on build `
![imagem 1](https://cloud.githubusercontent.com/assets/3578953/23553288/f19a30a2-fffe-11e6-89cb-6cc6fa5beb1d.png)

**Comment by marcozanghi** [comment]
I think that is the solution. I have tested and the building is ok. #2139
