### ISSUE TITLE
Problem with ajax page event

### ISSUE THREAD

**Issue by euvaldocp14** [primefaces/primefaces#2140]
## 1) Environment
-PrimeFaces version: 6.0
Its reproduce on the showcase (The latest version).
-Affected browsers: Chrome

## 2) Expected behavior
I'm having trouble giving an update to the form with the ajax "page" event that is inside the datatable.

## 3) Actual behavior
Deveria renderizar um botão que se localiza dentro do formulario que engloba tudo e o que esta acontecendo é um bug que desconfigura um datatable que tenho dentro do formulario.

## 4) Steps to reproduce
![erro](https://cloud.githubusercontent.com/assets/5545306/23561538/6b332ca2-001d-11e7-9c4c-7bd382c943e0.png)

**Comment by tandraschko** [comment]
You didn't answer all questsions, no example, no english -> invalid. sry.
