### ISSUE TITLE
 Media component error

### ISSUE THREAD

**Issue by psborges84** [primefaces/primefaces#2141]
I'm using the primefaces-6.0.16.jar version.

I am using the p: media component, but the pdf is not being displayed in the browser, I already tested it in several browsers ie, firefox, chrome.
The same code with version 5.3.17 works.
Follows the code snippet that does not work in version 6

```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.Serializable;

import javax.annotation.PostConstruct;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

@Controller
@Scope("session")
public class ViewFile implements Serializable {

  private StreamedContent file = null;

  @PostConstruct
  public void load() {
    String url =
        "C:\\apache-tomcat-7.0.70\\wtpwebapps\\app\\pdfs\\file.pdf";
    InputStream stream;
    try {
      stream = new FileInputStream(new File(url));
      file = new DefaultStreamedContent(stream, "application/pdf");
    } catch (FileNotFoundException erro) {
      erro.printStackTrace();
    }
  }

  public StreamedContent getFile() {
    return file;
  }

  public void setFile(StreamedContent file) {
    this.file = file;
  }
}
```

```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>view pdf</title>
</h:head>
<h:body>
	<p:media value="#{viewFile.file}" width="700px" height="700px" player="pdf" />
</h:body>
</html>
```

**Comment by tandraschko** [comment]
The usage is not correct!

The problem is the following:
- ViewFile initializes the StreamedContent once per session
- StreamedContentHandler will get the StreamedContent, stream it and closes the stream afterwards (this will happen for each request on the dynamic content!)
- As ViewFile initializes once, the stream is empty on the second stream try and nothing will be streamed

A better usage is the following:

`import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.Serializable;

import javax.annotation.PostConstruct;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

@Controller
@Scope("session")
public class ViewFile implements Serializable {

  private byte[] byteArray = null;

  @PostConstruct
  public void load() {
    String url =
        "C:\\apache-tomcat-7.0.70\\wtpwebapps\\app\\pdfs\\file.pdf";
    InputStream stream;
    try {
      FileInputStream stream = new FileInputStream(new File(url));
            byteArray = new byte[(int) file.length()];
            stream.read(byteArray);
            stream.close();
    } catch (FileNotFoundException erro) {
      erro.printStackTrace();
    }
  }

  public StreamedContent getFile() {
        FacesContext context = FacesContext.getCurrentInstance();

        // the if is just a optimization, see: http://stackoverflow.com/questions/8304967/how-to-use-pgraphicimage-with-streamedcontent-within-pdatatable
        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE)
        {
            return new DefaultStreamedContent();
        }
        else
        {
            return new DefaultStreamedContent(new ByteArrayInputStream(byteArray), "application/pdf", "Test Filename.pdf");
        }
  }

  public void setFile(StreamedContent file) {
    this.file = file;
  }
}`

**Comment by tandraschko** [comment]
also please use 6.1.RC1 - we fixed something related to streamedContent.

**Comment by pablosborges** [comment]
Does not work the code you posted.
I tested with the version of primefaces 6.0.16 and version 6.1.RC1.
With version 5.3.17 of primefaces works correctly.
Please test the code and do not close the ticket before testing.
thank you

```
@Controller
@Scope("view") --> view or session not work
public class ViewFile implements Serializable {

  private StreamedContent file = null;
  private byte[] byteArray = null;

  @PostConstruct
  public void load() {
    String url = "C:\apache-tomcat-7.0.70\wtpwebapps\app\pdfs\file.pdf";
    try {
      FileInputStream stream = new FileInputStream(new File(url));
      try {
        byteArray = getBytesFromInputStream(stream);
        stream.read(byteArray);
        stream.close();
      } catch (IOException erro1) {
        erro1.printStackTrace();
      }
    } catch (FileNotFoundException erro) {
      erro.printStackTrace();
    }
  }
  
  public static byte[] getBytesFromInputStream(InputStream is) throws IOException {
    try (ByteArrayOutputStream os = new ByteArrayOutputStream();) {
      byte[] buffer = new byte[0xFFFF];
      for (int len; (len = is.read(buffer)) != -1;)
        os.write(buffer, 0, len);
      os.flush();
      return os.toByteArray();
    }
  }

  public StreamedContent getFile() {
    FacesContext context = FacesContext.getCurrentInstance();
    // the if is just a optimization, see:
    // http://stackoverflow.com/questions/8304967/how-to-use-pgraphicimage-with-streamedcontent-within-pdatatable
    if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
      return new DefaultStreamedContent();
    } else {
      return new DefaultStreamedContent(new ByteArrayInputStream(byteArray), "application/pdf", "Test Filename.pdf");
    }
  }
  public void setFile(StreamedContent file) {
    this.file = file;
  }

<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>view pdf</title>
</h:head>
<h:body>
	<p:media value="#{viewFile.file}" width="700px" height="700px" player="pdf" />
</h:body>
</html>

```

**Comment by pablosborges** [comment]
Does not work open another ticket **#2142**
