### ISSUE TITLE
 Media component error again

### ISSUE THREAD

**Issue by pablosborges** [primefaces/primefaces#2142]
Relative **#2141**
Does not work the code you posted.
I tested with the version of primefaces 6.0.16 and version 6.1.RC1.
With version 5.3.17 of primefaces works correctly.
Please test the code and do not close the ticket before testing.
thank you

```
@Controller
@Scope("view") --> view or session not work
public class ViewFile implements Serializable {

  private StreamedContent file = null;
  private byte[] byteArray = null;

  @PostConstruct
  public void load() {
    String url = "C:\\apache-tomcat-7.0.70\\wtpwebapps\\app\\pdfs\\file.pdf";
    try {
      FileInputStream stream = new FileInputStream(new File(url));
      try {
        byteArray = getBytesFromInputStream(stream);
        stream.read(byteArray);
        stream.close();
      } catch (IOException erro1) {
        erro1.printStackTrace();
      }
    } catch (FileNotFoundException erro) {
      erro.printStackTrace();
    }
  }
  
  public static byte[] getBytesFromInputStream(InputStream is) throws IOException {
    try (ByteArrayOutputStream os = new ByteArrayOutputStream();) {
      byte[] buffer = new byte[0xFFFF];
      for (int len; (len = is.read(buffer)) != -1;)
        os.write(buffer, 0, len);
      os.flush();
      return os.toByteArray();
    }
  }

  public StreamedContent getFile() {
    FacesContext context = FacesContext.getCurrentInstance();
    // the if is just a optimization, see:
    // http://stackoverflow.com/questions/8304967/how-to-use-pgraphicimage-with-streamedcontent-within-pdatatable
    if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
      return new DefaultStreamedContent();
    } else {
      return new DefaultStreamedContent(new ByteArrayInputStream(byteArray), "application/pdf", "Test Filename.pdf");
    }
  }
  public void setFile(StreamedContent file) {
    this.file = file;
  }
```

```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>view pdf</title>
</h:head>
<h:body>
	<p:media value="#{viewFile.file}" width="700px" height="700px" player="pdf" />
</h:body>
</html>
```

**Comment by tandraschko** [comment]
viewscope will never work. The file is requested in a new request, which doesn't have a viewstate. So only request, app or session will work.

**Comment by tandraschko** [comment]
I dont use spring but the following works fine for me with JSF managed beans:
https://gist.github.com/tandraschko/49ad7d316eaf3a2f7af1aac4004feb75

**Comment by tandraschko** [comment]
So will close it as can't replicate.

**Comment by pablosborges** [comment]
It does not work, I just created a clean project with javax.faces-2.2.8-19.jar and primefaces-6.1.RC1.jar.

I'm using windows 7 with apache-tomcat-7.0.75

I would like to give you the clean design for you.

**Comment by pablosborges** [comment]
dont work.

2017-03-04 9:05 GMT-03:00 Thomas Andraschko <notifications@github.com>:

**Comment by tandraschko** [comment]
You can test in the showcase.
download it from github, change the version in the pom in line 220 to the RC1 and copy your xhtml and my java to it.
You can just run it via: mvn clean package jetty:run

**Comment by psborges84** [comment]
What jsf implementation are you using? Mojarra? Version? 
Post here your web.xml.

In my tests, the method below. Never falls into the else.

```
 if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
      return new DefaultStreamedContent();
    } else {
      return new DefaultStreamedContent(new ByteArrayInputStream(byteArray), "application/pdf",
          "oi.pdf");
    }
```

**Comment by psborges84** [comment]
I believe the error is related to dynamic loading. Because you rewrote the code for this part.

![erro1](https://cloud.githubusercontent.com/assets/6934092/23612021/6b3e2e6c-0258-11e7-8ca1-8bf49c30e0ec.jpg)
![erro](https://cloud.githubusercontent.com/assets/6934092/23612020/6b3dc256-0258-11e7-8391-4cba43303e95.jpg)

**Comment by psborges84** [comment]
I believe the error is related to dynamic loading. Because you rewrote the code for this part.

![erro](https://cloud.githubusercontent.com/assets/6934092/23612124/f333a202-0258-11e7-83d4-23fd7314716d.jpg)
![erro1](https://cloud.githubusercontent.com/assets/6934092/23612125/f335181c-0258-11e7-9d57-b63727d36d55.jpg)

**Comment by tandraschko** [comment]
As i said, i use the showcase which is available in github.
