### ISSUE TITLE
Comments "<!-- -->" in MenuBar are causing a javax.servlet.ClassCastException

### ISSUE THREAD

**Issue by preafos** [primefaces/primefaces#2143]
## 1) Environment
PrimeFaces version: 6.0 (Community-Downloads)
- It doesn't work on the newest Community-Release. I haven't tested it with the Elite Downloads
- Does it work on the newest sources in GitHub? I haven't tested it.
- Application server + version: Glassfish 4.0
- Affected browsers: Firefox (Not relevant)

## 2) Expected behavior
It should process the *.xhtml an display the page correctly.

## 3) Actual behavior
During processing a javax.servlet.ServletException is thrown. When you look into the server log, you'll finde the following trace stack:

[trace stack - comment issue.txt](https://github.com/primefaces/primefaces/files/818748/trace.stack.-.comment.issue.txt)

## 4) Steps to reproduce

Create an xhtml file an place a comment "" inside a <menubar> tag.

## 5) Sample XHTML

Use the following code snipped in an xhtml file. It worked on my side.

[comment issue - xhtml code snippet.txt](https://github.com/primefaces/primefaces/files/818754/comment.issue.-.xhtml.code.snippet.txt)

## 6) Sample bean
Is not needed.

**Comment by tandraschko** [comment]
Did you set javax.faces.FACELETS_SKIP_COMMENTS / facelets.SKIP_COMMENTS in web.xml to true?

**Comment by preafos** [comment]
I just tried to follow your advise to add:

	<context-param>
		<param-name>javax.faces.FACELETS_SKIP_COMMENTS</param-name>
		<param-value>facelets.SKIP_COMMENTS</param-value>
	</context-param> 

This suggested fix didn't work. The problem is still present. So please fix it in the next release, if you haven't done it already.

Anyway, it's not a good strategy to cover up an existing problem with the setting of a parameter value in a configuration file. In this case it doesn't even help. So please add a drop statement for comment-tags in your DOM processing unit.

**Comment by tandraschko** [comment]
you have to set javax.faces.FACELETS_SKIP_COMMENTS (JSF 2.2) to true and facelets.SKIP_COMMENTS (JSF < 2.2) to true.

PrimeFaces is just a component library, we don't parse the facelets file. This is up to the JSF impl.

**Comment by preafos** [comment]
Right, my mistake. Must be the slight hangover.

As I said before, there should be a drop statement in the DOM proccessing unit. It's should be an easy fix and increases your libraries usability immensely, which is great by the way.

**Comment by tandraschko** [comment]
As i already said, we don't have anything like a DOM processing unit. Thats all done by the JSF implementation, not by PrimeFaces.

**Comment by preafos** [comment]
When I'm looking into the TieredMenuRenderer.java from your repository, it's using a foreach-loop to iterate over a List<MenuElement>, which is causing this ClassCastException. So this can only mean one thing in my opinion, the List is not of type List<MenuElement> or wasn't at the beginning or somewhere in between. At some point someone casted a raw List type to List<MenuElement>.

The List<MenuElement> is retrieved from an interface type SubMenu via the method getElements(). This type is implemented by DefaultSubMenu an UISubMenu.
A look into DefaultSubMenu reveals nothing problematic, even though someone just could have set a raw List.
By reviewing UISubMenu you'll notice that the method getElements() returns a List instead of List<MenuElement>. This could cause the problem.

**Comment by preafos** [comment]
http://www.primefaces.org/docs/api/6.0/org/primefaces/component/submenu/UISubmenu.html

**Comment by tandraschko** [comment]
Yep, i know that we could do it safer in our code but IMO it's a good practice to set SKIP_COMMENTS as it will lead to unexpected situations in some other components, too.

**Comment by preafos** [comment]
oO OK, we both have different definitions on "good practice". You've a bug / error at hand because of using unsafe raw type List. I know you won't fix every thing right away, but you should work on it at some time and not turning a blind eye to the issue. It's the same as disabling the fire warning system because of wrong alerts until the big disaster happens.
This shouldn't ever be a "wontfix" tagged issue.

Thanks for the tip and help.
