### ISSUE TITLE
selectCheckboxMenu (multiple) bugs on version 6.1.RC1...

### ISSUE THREAD

**Issue by ModestinoAndre** [primefaces/primefaces#2144]
**Problem 01:**

When using [multiple="true"]:
After an ajax request/update (or when first loading the page with default itens already checked)
the selectCheckboxMenu does not show the itemLabel EL value, instead, it shows the object.toString().

In the below code, It should shows: u.loginName
but, It shows: u.toString()

Example:
Before Ajax update:
[https://drive.google.com/open?id=0Bw_c3JGGlIRDWFRBeWVPOVFyelE](url)

After ajax update:
[https://drive.google.com/open?id=0Bw_c3JGGlIRDbVdGVXVEWTlPLVk](url)

Exemple Code:
`<p:selectCheckboxMenu value="#{bean.selectedUsers}" label="XXXX" multiple="true" converter="#{entityConverter}"
                      filter="true" filterMatchMode="startsWith" panelStyle="width:250px" >`

`         <f:selectItems value="#{bean.users}" var="u" itemLabel="#{u.loginName}" itemValue="#{u}" />`

`</p:selectCheckboxMenu>`

**Problem 02:**

If the itemLabel value has a space character, the select-all and unselect-all does not work.
In the above example, if the user "JonhBlue" changes its login name to "Jonh Blue" the problem happens.

**Comment by tandraschko** [comment]
Please answer all questions like in the issue template - inclusive example xhtml and example java (the example must be complete an runnable).
Also -> 1 problem -> 1 issue in github. 
Will close this as invalid.
