### ISSUE TITLE
chips: does not escape characters by default

### ISSUE THREAD

**Issue by scnbk-software** [primefaces/primefaces#2145]
## 1) Environment
- PrimeFaces version: since 6.0.14 (tested with 6.1.0.RC1, 6.0.0)
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: NA
- Affected browsers: ALL

## 2) Expected behavior
p:chips component should escapse the input by default (like p:input,...).
Espacing should be only disabled when tab "escape=false" is choosen.

## 3) Actual behavior
p:chips component does not escapse by default. 
Entering javascript, html, ... in p:chips is therefore (at least as the example in the showcase) shown by default.
![](http://i.imgur.com/MxkIn3P.png)

All input components should escape these values by default due to security reaons (XSS, ...).

## 4) Steps to reproduce
Type in some html, javascript, ... in the p:chips component and hit enter. The non escaped value will be shown.

## 5) JSF Example
```xml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
	<p:chips />
</h:body>
</html>
```

**Comment by tandraschko** [comment]
Please provide a PR

**Comment by tandraschko** [comment]
@Rapster Would you like to do it? You are the "chips"-man ;)

**Comment by Rapster** [comment]
Sure, I can have a look at it ;)

**Comment by melloware** [comment]
I was looking at this one as well as I plan on using Chips in an upcoming project.    I had it down to 1 part on escaping the HTML I couldn't find a function for.  I see ComponentUtils.escapeText is for JSON encoding not for HTML encoding.  @Rapster I will be interested in seeing your fix!

**Comment by tandraschko** [comment]
Escaping is done via #writeText instead #write
I think there is a escaping on the client side missing, server side should be fine.

**Comment by melloware** [comment]
Understood.  I had looked at all the other renderers that had an escape= on them and saw the write() vs writeText() but this was already using writeText() which is why i was confused it wasn't working.

**Comment by tandraschko** [comment]
Yep, but i think the bug happens on client side. The server side is only active if you post the values and update the component.

**Comment by Rapster** [comment]
@melloware are you taking care of it then?

**Comment by melloware** [comment]
I will take a shot.

**Comment by melloware** [comment]
OK I created this PR.  https://github.com/primefaces/primefaces/pull/2176  

Please make fun of it if it is wrong.

**Comment by Rapster** [comment]
It looks to me, unless there is a good to reason on server side? @scnbk-software could you have a look?

**Comment by tandraschko** [comment]
The server side should already be escaped, so the current approach is required probably.

**Comment by scnbk-software** [comment]
Hi and sorry for the inactivity. 
I'm currently switching my appartment and had no internet (felt like an apocalypse).

I can have a look tomorrow.
