### ISSUE TITLE
InputNumber: submitted string value not localized

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2147]
## 1) Environment
- PrimeFaces version: 6.0 and 6.1 RC1
- Application server + version: Glassfish 4.1.1, mojarra 2.2.9
- Affected browsers: firefox tested

## 2) Expected behavior

Send locale aware string to model / converter. Default JSF behavior sends the raw input string to a converter and lets the converter do the conversion based on the view or converter provided locale.

## 3) Actual behavior

But inputNumber does conversion on client side and always uses US formatting for decimal numbers which creates a conflict. If the view has german locale (comma separator) the bound converter needs a german number.

## 4) Steps to reproduce

Create a german localized view. Add an p:inputNumber and bind a dummy converter that extends _NumberConverter_ to it. 

Enter a number with fractional part like **10,50**. The hidden input field of the widget will convert it to **10.50** which the converter will retrieve.

The converter uses the view locale "German" and tries to convert **10.50** to a german number. Which will be **105**.

## 5) Sample XHTML

	<h:form>
		<p:inputNumber symbol="€ " value="#{testBean.number}">
			<f:converter converterId="testNumberConverter"/>
		</p:inputNumber>
		<p:commandButton value="Save" update="@form"/>
	</h:form>

## 6) Sample bean

	@ManagedBean(name = "testBean")
	@ViewScoped
	public class TestBean implements Serializable
	{
		private BigDecimal number;

		public BigDecimal getNumber()
		{
			return this.number;
		}

		public void setNumber(final BigDecimal number)
		{
			this.number = number;
		}
	}

	import java.math.BigDecimal;
	
	import javax.faces.component.UIComponent;
	import javax.faces.context.FacesContext;
	import javax.faces.convert.FacesConverter;
	import javax.faces.convert.NumberConverter;
	
	@FacesConverter("testNumberConverter")
	public class TestNumberConverter extends NumberConverter
	{
		@Override
		public Object getAsObject(final FacesContext context, final UIComponent component, final String value)
		{
			// 10.50
			System.out.println(value);
	
			// 105
			final BigDecimal cost = (BigDecimal) super.getAsObject(context, component, value);
	
			System.out.println(cost);
	
			return cost;
		}
	
		@Override
		public String getAsString(final FacesContext context, final UIComponent component, final Object value)
		{
			System.out.println(value);
	
			final String strValue = super.getAsString(context, component, value);
	
			System.out.println(strValue);
	
			return strValue;
		}
	}

## 7) Workaround

Use _Locale.US_ explicitly for the converter. It has no visual affect and comma is still used, since it only affects the hidden input.

	<o:converter converterId="testNumberConverter" locale="#{Locale.ENGLISH}"/>

## 8) Solution

Put locale aware number into hidden input or use a second hidden input field that is submitted to model.

**Comment by tandraschko** [comment]
Why do you need a converter?

**Comment by djmj** [comment]
Cause converters can be used for any input and because of the business case. If you really want to know :)

In german beverage retail, the deposit is included with vat for private users, and excluded vat for commercial users (just one of the most stupid things). But 99% of people, even retailers themselves only know the private deposit value (0,25 € on a plastic bottle, 0,30 € for commercial users). 

So as a user-friendly application we let them input 8,40 € as their deposit-return which will be recalculated to 10,00 € for a commercial user using a converter. Our customers are happy with that simple solution. 

http://imgur.com/NncC9uT
http://imgur.com/kGRVDk6

**Comment by alexsuter** [comment]
Hello @djmj 
I have the same issue. Hopefully you can help me to understand the problem. Is it true that Primeface always sends the data already in US locale to the server? But JSF specifies/assumes that the value is in the current locale of the jsf context? Like for example `javax.faces.convert.NumberConverter` does?

**Comment by alexsuter** [comment]
Hello @tandraschko 
Should primeface not send the locale aware value to the JSF converter instead of the locale unaware number? I have issues if my database is `java.lang.Number`, JSF locale is set to _Germany_ and when I use the `javax.faces.convert.NumberConverter`.

I made more or less the same example like @dimj did here: https://github.com/alexsuter/primefaces-examples

Or maybe primeface should set `javax.faces.convert.NumberConverter.setLocale(Locale)` somehow?

**Comment by djmj** [comment]
@alexsuter I think i explicitly used the locale _<f:convertNumber locale="US"/> for inputNumber as a workaround.

**Comment by oacuna** [comment]
Hello everybody! The same localization problem for the 'inputNumber' component using the one corresponding to Paraguay (es_PY), where the dot (.) is the thousands separator and the comma (,) is the decimal separator. The currency symbol is G (guaraní).

I'm trying to write a value: G 350.000
The application turns it to: G 350 (error)

This is corrected if:
a) I use the property 'decimalPlaces'> 0 in the 'inputNumber' component. However, in the Paraguayan currency we do not have decimals places).
b) I set <default-locale> for the application to en_US. However, this represents a visual interpretation problem for users.

Sorry for my english xD

Greetings!

I am using:
PrimeFaces JSF v10.0.0

**Comment by melloware** [comment]
@oacuna can you see this ticket and see if it fixes your issue? https://github.com/primefaces/primefaces/issues/7271

**Comment by oacuna** [comment]
Thanks for the prompt response @melloware!

Unfortunately the suggested solution does not work (totally), because it keeps cutting units of a million (or greater). For example:

Case 1)
If I write the value: G 350.000
Correctly written: G 350.000 (corrected)

Case 2)
If I write the value: G 3.500.000
Incorrectly write: G 3.500 (error)

Case 3)
If I write the value: G 3.500.000.000
Correctly written: G 3.500.000.000 (corrected)

Thank you in advance for your help.

Greetings

**Comment by melloware** [comment]
Can you paste your exact `<p:inputNumber` here so I can debug with your exact settings?

**Comment by oacuna** [comment]
Yes of course @melloware  👍

<p:inputNumber decimalPlaces="0" decimalSeparator="," thousandSeparator="." dir="rtl" id="ecMonto" emptyValue="zero" required="true" requiredMessage="Debe especificar el monto del cheque" value="#{myBean.monto}" valueChangeListener="#{myBean.processValueChange}">
        <p:ajax process="@this" update="ecMontoPagar"/>
</p:inputNumber>

If you need something else, please do not hesitate to ask

**Comment by melloware** [comment]
OK I think I fixed it please try this instead. It has to be `replaceAll` and not `replace`
```javascript
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.bindInputEvents = function() {
        var $this = this;

        // GitHub #6447: browser auto fill fix
        this.input.off('blur.inputnumber').on('blur.inputnumber', function(e) {
            var element = AutoNumeric.getAutoNumericElement(this);
            if (element && this.value && this.value.length > 0) {
                var newValue = this.value;
                if ($this.cfg.digitGroupSeparator) {
                    newValue = newValue.replaceAll($this.cfg.digitGroupSeparator, '');
                }
                element.set(newValue, null, true);
            }
            $this.copyValueToHiddenInput();
        });
    }
}
```

**Comment by oacuna** [comment]
Excelent job @melloware 👍 💯 now my application it's writing/showing correctly the numbers (thousands and decimals).

Thanks a lot and greetings from Paraguay!

**Comment by melloware** [comment]
I am going to close this. I still don't understand the issue as it converts the backing bean to a BigDecimal.  It has nothing to do with locale. If someone creates a proper PrimeFaces Test reproducer showing the issue I will happily reopen
