### ISSUE TITLE
New textEditor is missing source view

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2148]
Since p:editor is marked as deprecated p:textEditor should be a valid substitution. But i am missing source view.

For rich content-management in combination with PrimeUI this is a must feature. For now we stay at old p:editor.

**Comment by tandraschko** [comment]
Is this possible in quilleditor? I didn't find anything about that.

(IMO the only replacement is ckeditor from extensions ;))

**Comment by kukel** [comment]
Correct, if @djmj would have searched a little, it would have become obvious very quickly that quilleditor does not support this. Whole discussion about it on their issuelist (in fact this issue is a duplicate here iirc)

**Comment by djmj** [comment]
I did searched at quill repo and in their issue it seems they showed a workaround but not sure if it would work. https://github.com/quilljs/quill/issues/128.
