### ISSUE TITLE
XLS data exporter ignores set data table filters

### ISSUE THREAD

**Issue by agoetze** [primefaces/primefaces#2151]
## 1) Environment
- PrimeFaces version: 6.0.16 (working fine in 6.0.15)
- Does it work on the newest released PrimeFaces version? Version? No.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) I do not know.
- Application server + version: Tomcat 7.0.72
- Affected browsers: Tested on Firefox 

## 2) Expected behavior

The data exporter exports only the filtered records in the data table.

## 3) Actual behavior

The data exporter ignores all filters and exports all records belonging to the data table.

## 4) Steps to reproduce

1. Open a filterable data table.
2. Use the filter of one or multiple columns.
3. Hit the data export button or link.
4. See that your filtering was ignored by the data exporter.

It is working as expected in PrimeFaces 6.0.15.

## 5) Sample XHTML

```
<p:dataTable 
	id="dt_my_submissions" widgetVar="dt_my_submissions_wv" 
	value="#{mySubmissionsBean.submissions}" var="submission" rowIndexVar="rowIndex"
	filteredValue="#{mySubmissionsBean.filteredSubmissions}"
	... >

	<f:facet name="header">
		<h:commandLink id="xls_submissions" >
			<h:graphicImage value="/resources/icons/xls-icon.gif" />
			<p:dataExporter type="xls" target="dt_my_submissions" fileName="submissions" />
		</h:commandLink>
	</f:facet>

	SOME FILTERABLE COLUMNS COLUMNS

</p:dataTable>
```

## 6) Sample bean

Not necessary.

**Comment by mertsincan** [comment]
I think this issue is fixed on 6.0.17 and 6.1; https://github.com/primefaces/primefaces/issues/2137
