### ISSUE TITLE
PhotoCam: add resolution selection

### ISSUE THREAD

**Issue by giorgioprimefaces** [primefaces/primefaces#2152]
This is a feature request,
It would be great to have resolution selection in future releases,
actually I can only get images 320x240px which is sooo small nowadays!

thanks in advance,
Giorgio

**Comment by tandraschko** [comment]
Does webcamJS support this?

**Comment by giorgioprimefaces** [comment]
if webcamJS is this one
[https://pixlcore.com/](url), it can take hd pictures and you can set many parameters:
Webcam.set({
    width: 320,
    height: 240,
    dest_width: 640,
    dest_height: 480,
    image_format: 'jpeg',
    jpeg_quality: 90,
    force_flash: false
});

**Comment by tandraschko** [comment]
https://github.com/jhuckaby/webcamjs

its this
we use this under the hood. As it's in maintenance mode, we should rewrite the component probably. Feel to give ideas or sponsor it.

**Comment by giorgioprimefaces** [comment]
thanks tandraschko, 
I've just discovered that p:upload used on mobile can use smartphone's camera and its options, so, for what I need it's more than enought.
I will not close this issue because I think it will be useful to improve options in p:photocam for desktop users...

Giorgio

**Comment by doleron** [comment]
Hi, 

Am I missing something or are `width` and `height` what are you looking for? From [docs](https://primefaces.github.io/primefaces/8_0/#/components/photocam): 

| Name | Default | Type | Description | 
| --- | --- | --- | --- |
id | null | String | Unique identifier of the component
width | 320 | Integer | Width of the camera viewport.
height | 240 | Integer | Height of the camera viewport.

They are passed to Webcam.js engine under the wood during the camera initialization:

```javascript
attach: function() {
        // ...
        Webcam.set({
            width: this.cfg.width,
            height: this.cfg.height,
```
In this example it is set up to 960x720:

```xhtml
<p:photoCam width="960" height="720"/>
```

![image](https://user-images.githubusercontent.com/9665358/84003802-f44e6180-a940-11ea-9940-4faa335976cf.png)

**Comment by melloware** [comment]
I think the only thing he mentions differently is 
```
dest_width: 640,
dest_height: 480,
```
Not sure from the webcam docs how the dest is different than the width and height.

**Comment by doleron** [comment]
Well, dest_width and dest_height can be set by photoWidth/photoHeight:

```xhtml
<p:photoCam width="960"height="720"photoWidth="96" photoHeight="72" />
````
They control the snap / captured image dimensions as seen below:

![image](https://user-images.githubusercontent.com/9665358/84052547-1d91e080-a987-11ea-8555-c98dedf52c7d.png)

| Name | Default | Type | Description | 
| --- | --- | --- | --- |
photoWidth | 320 | Integer | Width of the captured photo, defaults to width.
photoHeight | 240 | Integer | Height of the captured photo, defaults to height.

It seems the API provides the requested feature.

**Comment by melloware** [comment]
OK then i am closing this ticket as completed
