### ISSUE TITLE
Re-Add "*" and "All Rows" paginator options

### ISSUE THREAD

**Issue by daendoonge** [primefaces/primefaces#2153]
#1072 from sudheerj/ShowAllOption … was overriden by changes from #191 

Please bring back the option to show all rows from the table

**Comment by daendoonge** [comment]
` 
 +            int rows = 0;
 +            
              for( String option : options){
 -                int rows = Integer.parseInt(option);
 +            	if(option.equalsIgnoreCase("*")){
 +            		rows = uidata.getRowCount();
 +            	}else{
 +            		rows = Integer.parseInt(option);
 +            	}
                  writer.startElement("option", null);
                  writer.writeAttribute("value", rows, null);`

**Comment by daendoonge** [comment]
int rows = 0;

            for( String option : options){
            	if(option.equalsIgnoreCase("*")){
            		rows = uidata.getRowCount();
            	}else{
            		rows = Integer.parseInt(option);
            	}
                writer.startElement("option", null);
                writer.writeAttribute("value", rows, null);

                if(actualRows == rows){
                    writer.writeAttribute("selected", "selected", null);
                }

                writer.writeText(option, null);
                writer.endElement("option");
            }`

**Comment by Rapster** [comment]
It seems that you already had a look, might be a good idea that you provide a PR ;)

**Comment by daendoonge** [comment]
Lol I didnt know how to do it XD

**Comment by daendoonge** [comment]
I wouldn't mind if you guys used 'Show All' instead of * but * works too

**Comment by lagar84** [comment]
I created a PR for this:
https://github.com/primefaces/primefaces/pull/2393

It uses Integer.MAX_VALUE, but if there is some risk of overflow, just use a large integer, like 1_000_000_000 (one billion)

**Comment by akashbharati** [comment]
@tandraschko  how to show 'All' as an option in p-table which is using paginator. I could not understand

**Comment by mertsincan** [comment]
Please use PrimeNg github or forum for p-table(PrimeNg) issues. 

For p:dataTable(PrimeFaces), please see; https://github.com/primefaces/primefaces/issues/3833

Best Regards,
