### ISSUE TITLE
New p:chips componend should trigger forseeable ajax events on item addition and removal.

### ISSUE THREAD

**Issue by Selaron** [primefaces/primefaces#2156]
## 1) Environment
- PrimeFaces version: 
6.1.RC1

- Application server + version:
Apache Tomcat 8.5.8

- Affected browsers:
any

## 2) Expected behavior
The new p:chip component should trigger e.g. the "change" event, when user adds an item or removes it by clicking the close icon.

## 3) Actual behavior
When a user is adding some icons, you can only try to track this via "keyup" or "focus" event.
"change" or "valueChange" events do not get triggered. There's also no "itemAdded" event defined.

When the user removes an item by mouse click on its' close icon, none of the "mouse*" or "click" events is triggered. You can try and track this using the "focus" event.  There's also no "itemRemoved" event defined.

## 4) Steps to reproduce
Add p:ajax elements with events like change, valueChange, click, mousedown, mouseup to a p:chips component. Add and remove items using keyboard and mouse.
You'l see your actions won't get reliably tracked by ajax events.

## 5) Sample XHTML

> <p:chips value="#{viewScope.chips}">
> 	<p:ajax event="change" process="@this" update="chips" delay="300" />
> 	<p:ajax event="valueChange" process="@this" update="chips" delay="300" />
> 	<p:ajax event="click" process="@this" update="chips" delay="300" />
> 	<p:ajax event="mousedown" process="@this" update="chips" delay="300" />
> 	<p:ajax event="mouseup" process="@this" update="chips" delay="300" />
> </p:chips>
> <h:panelGroup id="chips">
> 	<h:outputText value="#{viewScope.chips}" />
> </h:panelGroup>

## Workaround
Add a `<p:ajax event="focus" process="@this" update="chips" delay="300" />` element with "focus" event to the component. This will surprisingly track all your add and removal activities.

**Comment by Rapster** [comment]
I'm working on it

**Comment by Rapster** [comment]
@tandraschko I made a PR for this in the showcase _(in case you didn't see it)_
