### ISSUE TITLE
Check selectionMode on contexMenu - is it really required?

### ISSUE THREAD

**Issue by gunnee** [primefaces/primefaces#2159]
## 1) Environment
- PrimeFaces version: 6.0.16
- Does it work on the newest released PrimeFaces version? No
- Application server + version: Tomcat v.8.0.36
- Affected browsers: Tested with IE 11, Firefox 51.0.1, Chrome 56...
- This bug does not exist in previous releases (e.g. 5.1.5).

## 2) Expected behavior
`p:datatable` in combination with `p:contextMenu` requires `selectionMode="single"` which only allows selecting one item at once.

## 3) Actual behavior
When using the context menu on a page for the first time, only one row can be selected (expected behavior). However, when selecting a row, navigating to another page, navigating back, the row is still selected (session scope bean). Now, other items can be selected aswell (rightclick) which results in none of the rows are set into the `selection` attribute.

Note: My pages are always refreshed via ajax calls, no full page refresh.

## 4) Steps to reproduce
Simply use the example from PF demo page but instead of opening a dialog, navigate to another page and then navigate back (no full page refresh in between).

## 5) Sample XHTML
**test.xhtml:**
```html
<h:form id="form">
  <p:dataTable id="cars" var="car" value="#{dtContextMenuView.cars}" rowKey="#{car.randomId}" selection="#{dtContextMenuView.selectedCar}"
    selectionMode="single">
    <p:column headerText="Id">
      <h:outputText value="#{car.randomId}" />
    </p:column>
    <p:column headerText="Year">
      <h:outputText value="#{car.randomYear}" />
    </p:column>
    <p:column headerText="Brand">
      <h:outputText value="#{car.randomBrand}" />
    </p:column>
    <p:column headerText="Color">
      <h:outputText value="#{car.randomColor}" />
    </p:column>
  </p:dataTable>

  <p:contextMenu for="cars">
    <p:menuitem value="View" icon="ui-icon-search" action="#{dtContextMenuView.navigateToTest2}" />
  </p:contextMenu>
</h:form>
```
**test2.xhtml:**
```html
<h:form id="form">
  <h:outputText value="#{dtContextMenuView.selectedCar.randomId}" />
  <p:commandButton value="Back" icon="ui-icon-plus" action="#{dtContextMenuView.navigateToTest}" />
</h:form>
```
## 6) Sample bean
Use the same Java classes as shown in the [PF showcase](https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml). I only modified class ContextMenuView (session scope bean) and added two methods:
```java
public String navigateToTest() {
  return "test.xhtml";
}

public String navigateToTest2() {
  return "test2.xhtml";
}
```

**Comment by gunnee** [comment]
To clarify: this is not a feature. It is a bug ;)

**Comment by tandraschko** [comment]
Yep! Would be great if you could provide a PR to fix it.

**Comment by gunnee** [comment]
Had a look into your code.. seems to be just a wrong reference. see my PR #2173

**Comment by tandraschko** [comment]
Thanks!

**Comment by gunnee** [comment]
No problem. However, I'm curious why there is an attribute "selectionMode" for context menus at all?
I think, it can be removed... just a suggestion.

**Comment by tandraschko** [comment]
Hmm, it may also be possible that we changed a working code ;)

**Comment by tandraschko** [comment]
I reverted your change, seems like it was designed to specify the selectionMode on the contextMenu.

Looks like you should set selectionMode=single on your contextMenu.

**Comment by gunnee** [comment]
In my opinion, the selectionMode on contextMenu is not necessary as it does not have any impact on the contextMenu itself. In addition, it only affects the selection behaviour for dataTables, components like treeTable or tree do not use the contextMenu's selectionMode attribute. That's confusing. Please also note: When using the contextMenu as shown in the [PF example](https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml), the attribute `selectionMode` is set to `single` (dataTable) and `multiple` (default setting for contextMenu) at the same time. 

For now, I will use your recommendation. If you like, I can provide another pull request which removes the selectionMode from contextMenu.

**Comment by tandraschko** [comment]
But it would fix your problem?

We cannot just remove it, it was introduced as a feature some time ago.

**Comment by gunnee** [comment]
I see your point. This change might be for major releases.. I was thinking for the collective good. ;)

**Comment by melloware** [comment]
Closing this issue as it currently works as intended.
