### ISSUE TITLE
selectOneMenu with filter: unmatched end tag in IE

### ISSUE THREAD

**Issue by mhrnr** [primefaces/primefaces#2160]
When using selectOneMenu with a filter, I always get a warning in Internet Explorer Developer Tools console: 

HTML1512: Unmatched end tag.

Environment: Windows 7, Internet Explorer 11.0.9600.1837, Primefaces 6.0.14. The warning also appears in showcase: http://www.primefaces.org/showcase/ui/input/oneMenu.xhtml.

**Comment by kukel** [comment]
Did you check if IE is right?

**Comment by tandraschko** [comment]
The warning is there but the rendered html looks ok and is xml conform (copied the html to my xml editor).

**Comment by melloware** [comment]
I agree I see the warning but there is nothing wrong with the generated HTML.  I feel like this is an IE false positive with its parser.
