### ISSUE TITLE
6.1.RC1

### ISSUE THREAD

**Issue by stakahop** [primefaces/primefaces#2162]
After adding 6.1.RC1 to my project I m waiting about one minute on server start after Initializing Mojarra with following INFO message:

[javax.enterprise.resource.webcontainer.jsf.config] Monitoring jndi:/default-host/{projectName}/WEB-INF/faces-config.xml for modifications

But everything works ok.

**Comment by tandraschko** [comment]
Works fine in our showcase and you miss a lot of infos from our issue template. Use a profiler and come back with the result.
