### ISSUE TITLE
PF 6.1 p:outputLabel does not work with custom component

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#2163]
1) Environment
- PrimeFaces version: 6.1.RC1
- Does it work on the newest released PrimeFaces version? Yes Version? 6.0
- Application server + version: Tomee 7.0.2, Myfaces 2.2.12

2) Expected behavior

Label should be rendered

3) Actual behavior

NullPointer is thrown

5) Sample XHTML

<p:outputLabel for="someId">Label</p:outputLabel/>
<my:custom-component id="someId" />

The error is:
java.lang.NullPointerException: null
	at org.primefaces.util.CompositeUtils.invokeOnEditableValueHolder(CompositeUtils.java:57)
	at org.primefaces.util.CompositeUtils.invokeOnDeepestEditableValueHolder(CompositeUtils.java:75)
	at org.primefaces.component.outputlabel.OutputLabelRenderer.encodeEnd(OutputLabelRenderer.java:125)

I think that the CompositeUtils.invokeOnEditableValueHolder should take into account that the attribute AttachedObjectTarget.ATTACHED_OBJECT_TARGETS_KEY can be null and in that case just use an empty list, altough I don't know what implications can have that.

**Comment by Rapster** [comment]
Indeed it should take account that there is no `cc:editableValueHolder`, but in the other hand, does it make sense to use `for` on a composite which does not have an input holder?

(In such kind of issue, don't forget to post composite code)

**Comment by tandraschko** [comment]
Yep, the fix is quite simple but i'm not sure if it makes sense to support this.

Quote from w3schools.com:
> The \<label\> tag defines a label for an \<input\> element.

So, if you don't add a cc:editableValueHolder, it will target a div or even a element with a id, which is not rendered (depends if your root element in your CC is e.g. \<div id=#{cc.clientId}\>)

**Comment by cocorossello** [comment]
The custom component is not properly implemented, of course. We will fix
that. But it was working (not throwing an error) with PF 6.0 and the
exception message is confusing. Maybe throw a proper message error instead
of just silencing it?

El 11 mar. 2017 12:26, "Sébastien Lepage" <notifications@github.com>
escribió:

Indeed it should take account that there is no cc:editableValueHolder, but
in the other hand, does it make sense to use for on a composite which does
not have an input holder?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/primefaces/primefaces/issues/2163#issuecomment-285860899>,
or mute the thread

**Comment by tandraschko** [comment]
Added it to the migration guide and will close it as won't fix. It will just blow up our code and the usage is invalid.

**Comment by appldo** [comment]
as a workaround you can add

`<composite:actionSource name="dummy" targets=""/>`

to your composite component
