### ISSUE TITLE
Use of target="_blank" with ajax="false" in menuitem messed up navigation

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2164]
## 1) Environment
- PrimeFaces version: 6.1-RC1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Jetty 8
- Affected browsers: Chrome

## 2) Expected behavior
Based on the showcase http://localhost:9999/showcase/ui/panel/toolbar.xhtml.
Replace

```xml
<p:menuitem value="Save" actionListener="#{toolbarView.save}" update="messages" icon="ui-icon-disk" />
```

By (I added `target="_blank" ajax="false"`)

```xml
<p:menuitem value="Save"actionListener="#{toolbarView.save}"  update="messages" icon="ui-icon-disk" target="_blank" ajax="false"/>
```

Clicking on this menuitem should open the page on a new tab.

## 3-4) Actual behavior
So far it works :) But once you click on this, go back to the original page, and click on another menuitem where ajax="false" _(like Delete item)_, it will also open a new page while I did not indicate to do so.

## 5) Sample XHTML
```xml
<f:facet name="right">
    <p:menuButton value="Options">
        <p:menuitem value="Save" actionListener="#{toolbarView.save}" update="messages" icon="ui-icon-disk" target="_blank" ajax="false" />
        <p:menuitem value="Update" actionListener="#{toolbarView.update}" update="messages" icon="ui-icon-arrowrefresh-1-w" />
        <p:menuitem value="Delete" actionListener="#{toolbarView.delete}" ajax="false" icon="ui-icon-close" />
        <p:menuitem value="Homepage" url="http://www.primefaces.org" icon="ui-icon-extlink" />
    </p:menuButton>
</f:facet>
```

**Comment by tandraschko** [comment]
Could be the same as: #514
Would be great if you would provide a fix.

**Comment by Rapster** [comment]
It looks definitely the same. I'm having a look but I can't guarantee anything about this, it is very low level

**Comment by Rapster** [comment]
I found something ;)

**Comment by Rapster** [comment]
It's because of this:

```javascript
/**
 * Submits a form and clears ui-submit-param after that to prevent dom caching issues
 */
submit: function(formId, target) {
    var form = $(this.escapeClientId(formId));
    if (target) {
        form.attr('target', target);
    }

    form.submit().children('input.ui-submit-param').remove();
}
```

First time, target equals `_blank` it's added to the form as attribute. Second time, `target="_blank"` is still present in form, while it shouldn't (target parameter is undefined at this point).

It's a very tricky case as we can't simply remove target attribute from form each time submit is called (just because target is an attribute of h:form)

**Comment by tandraschko** [comment]
What about this one:

`        submit : function(formId, target) {
            var form = $(this.escapeClientId(formId));
            
            var oldTarget;
            if(target) {
                oldTarget = form.attr('target');
                form.attr('target', target);
            }

            form.submit();
            
            form.children('input.ui-submit-param').remove();
            
            if (target) {
                form.attr('target', oldTarget);
            }
        }`

**Comment by Rapster** [comment]
This is exactly what I was thinking :) Although it's a bit different:
```javascript
        submit : function(formId, target) {
            var form = $(this.escapeClientId(formId));
            var prevTarget;
            
            if(target) {
            	prevTarget = form.attr('target');
                form.attr('target', target);
            }

            form.submit().children('input.ui-submit-param').remove();
            
            if (target) {
            	if (prevTarget !== undefined) {
            		form.attr('target', prevTarget);            		
            	} else {
            		form.removeAttr('target');
            	}
            }
        }
```

**Comment by tandraschko** [comment]
looks fine! if it works fine, please create a PR and i will merge it.

**Comment by Rapster** [comment]
Sure I'll do it ;)
