### ISSUE TITLE
Firefox Bug in InputNumber

### ISSUE THREAD

**Issue by Svhorsch** [primefaces/primefaces#2166]
## 1) Environment
- PrimeFaces version: 6.0
- Application server + version: wildfly 8.1.0
- Affected browsers: Firefox 51.0.1 (working on chrome)

## 2) Expected behavior
I have a TestController class which has two fields, a and b, both are of type int. On the UI i have two input fields, on of type inputNumber the other one of type inputText. There is also a commandButton, which just calls a "doWork" method on the TestController and afterwards updates the both inputs.
I would expect that after clicking on the button, both input fields keep the value they had before clicking the button.

## 3) Actual behavior
After clicking the button, both values are sent to the server, but only the inputText field is applied to the field. Therefefore after clicking the button and updating the inputs, only the inputText is updated correctly, the inputNumber is getting blank (In the DOM, there is a hidden input field created for the inputNumber, and both values, from the inputNumber and the hidden inputNumber are sent to the server, the hiddenNumber is ALWAYS 0), and i cant input any value which will be set in the TestController.

## 4) Steps to reproduce
In the appendix, you see all steps i did with the sout of the TestController.

## 5) Sample XHTML
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>

</h:head>
<h:body>
    <h:form>
        <p:inputNumber id="a" value="#{testController.a}"/>
        <p:inputText id="b" value="#{testController.b}"/>
        <p:commandButton value="Do stuff" action="#{testController.doStuff}" update="a,b"/>

    </h:form>
</h:body>
</html>
```
..

## 6) Sample bean
```java
public class TestController {

    private int a = 1;
    private int b = 2;

    public int getA() {
        return a;
    }

    public void setA(int a) {
        System.out.println("setA: " + a);
        this.a = a;
    }

    public int getB() {
        return b;
    }

    public void setB(int b) {
        System.out.println("setB: " + b);
        this.b = b;
    }

    public void doStuff() {
        System.out.println("do stuff");
    }
}
```

## 7) Documentation
Starting the server, i see this view:
![startup](https://cloud.githubusercontent.com/assets/26352415/23827625/abd37618-06b7-11e7-846e-a3f7b7bb07e3.png)

Then i click on submit, and the log of the server:
![submit_log](https://cloud.githubusercontent.com/assets/26352415/23827631/e2116e06-06b7-11e7-8ef6-b9320e0a1699.png)

after this, the view looks like:
![after_submit](https://cloud.githubusercontent.com/assets/26352415/23827635/f2a6ea84-06b7-11e7-83b3-829f6c4d98ea.png)

I change the field from 2 to 3
![2_to_3](https://cloud.githubusercontent.com/assets/26352415/23827641/0d76cef6-06b8-11e7-8033-76b91be3bcf3.png)
and submit it, then the log of the server is (hadn`t changed the number input):
![final_log](https://cloud.githubusercontent.com/assets/26352415/23827647/2e821d1c-06b8-11e7-87d7-e01e2b69314f.png)

**Comment by tandraschko** [comment]
A PR would be great, never had any issues with this component on FF.

**Comment by Svhorsch** [comment]
whats PR?

**Comment by tandraschko** [comment]
pull request / bugfix patch ;)

**Comment by karlkilden** [comment]
My problem is similar but with any browser. After the inputnumber is blank I can type anything into it as well...

**Comment by tandraschko** [comment]
Your sample is working for me on 52.0.1.
Just added @Named + @SessionScoped on your sample bean.
