### ISSUE TITLE
Remove p:editor, p:layout

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2168]
maybe in 7.x or something.
Currently it's only deprecated.

Its not maintained since years and has many bugs.
We should completely remove it as we now have the textEditor.

**Comment by cagataycivici** [comment]
7.x is fine, yes.

**Comment by pizzi80** [comment]
It would be nice to replace the <p:editor> with the PrimeFaces Extension CkEditor 4.6.x
which is very powerful and also can be extended for server-side file upload

https://www.primefaces.org/showcase-ext/views/ckEditor.jsf

**Comment by cagataycivici** [comment]
The one in extensions is too big to put in.

**Comment by tandraschko** [comment]
And it doesn't work as the license isnt compatible. Therefore its also in an extra module in extensions.

**Comment by djmj** [comment]
Just mention, p:textEditor has no source code functionality. How shall we use PrimeUI in CMS then ;)

**Comment by tandraschko** [comment]
Use CKEditor from PFE. CLEditor is not maintained since years.

**Comment by mdzaebel** [comment]
If CKEditor is too big and has licensing issues, PF won't have an editor with source tab, which can be used e.g. for CMS and many, other systems. What is the migration strategy for users, that depends on the feature?

**Comment by melloware** [comment]
I agree I would not remove p:editor because it still has some use until QuillJS resolves all of their issues.

**Comment by mauromol** [comment]
Before removing p:editor in favour of p:textEditor, please note that the latter is not currently generating portable HTML code by default! See https://github.com/primefaces/primefaces/issues/4489 (even if you closed it). I think it's a really serious problem.

**Comment by tandraschko** [comment]
p:editor is a serious problem as CLEditor is not maintained since years.
We have to remove it for sure.

Quill was the decision of PrimeTek.
I would use CKEditor and be Happy.
