### ISSUE TITLE
2 o more Dropdown no execute

### ISSUE THREAD

**Issue by Shadowxx1** [primefaces/primefaces#2169]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? Version? no
- Application server + version: glassfish 5.0
- Affected browsers: all

## 2) Expected behavior
In a form more than 1 dropdown to make the query for example fill Country, then fill Town, then fill Town. The call to the change method declared on the ajax tag should be made one by one selected Country, then selecting the City to finally populate the villages
...

## 3) Actual behavior
Within a single form alone execute the first ajax call from the first dropdown, the second dropdown that must refresh the next dropdown is not executed. It does not call the onChange method that is declared in the ajax tag. So susecibamente with the other drop down they are. Only ejaculate well the main second or third does not run.
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
        <h:form>
            <p:growl id="msgs" showDetail="true" />
            
            <p:panel header="Direccion" style="margin-bottom:10px;">
                <h:panelGrid columns="2" cellpadding="5">

                    <p:outputLabel for="pais" value="Pais: " />
                    <p:selectOneMenu id="pais" value="#{pruebaManagedBean.pais2}" style="width:150px">
                        <p:ajax event="change" listener="#{pruebaManagedBean.onPaisChange}" update="estado" />
                        <f:selectItem itemLabel="Seleccionar" itemValue="" noSelectionOption="true" />
                        <f:selectItems value="#{pruebaManagedBean.paises2}" />
                    </p:selectOneMenu>

                    <p:outputLabel for="estado" value="Estados " />
                    <p:selectOneMenu id="estado" value="#{pruebaManagedBean.estado2}" style="width:150px">
                        <p:ajax event="change" listener="#{pruebaManagedBean.onEstadoChange}" update="municipio"/>
                        <f:selectItem itemLabel="Seleccionar" itemValue="" noSelectionOption="true" />
                        <f:selectItems value="#{pruebaManagedBean.estados2}" />
                    </p:selectOneMenu>

                    <p:outputLabel for="municipio" value="Municipio " />
                    <p:selectOneMenu id="municipio" value="#{pruebaManagedBean.municipio2}" style="width:150px">
                        <f:selectItem itemLabel="Seleccionar" itemValue="" noSelectionOption="true" />
                        <f:selectItems value="#{pruebaManagedBean.municipios2}"/>
                    </p:selectOneMenu>                 

                </h:panelGrid>
            </p:panel>
        </h:form>
..

## 6) Sample bean
package vista;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.view.ViewScoped;
import modelo.entidades.personas.dominio.Ciudad;
import modelo.entidades.personas.dominio.Estado;
import modelo.entidades.personas.dominio.Municipio;
import modelo.entidades.personas.dominio.Pais;
import modelo.entidades.personas.dominio.Parroquia;
import org.apache.commons.lang3.math.NumberUtils;
import services.persona.dominio.ciudad.CiudadServiceRemote;
import services.persona.dominio.estado.EstadoServiceRemote;
import services.persona.dominio.municipio.MunicipioServiceRemote;
import services.persona.dominio.pais.PaisServiceRemote;
import services.persona.dominio.parroquia.ParroquiaServiceRemote;

/**
 *
 * @author NELSON
 */
@ManagedBean
@ViewScoped
public class PruebaManagedBean implements Serializable {
    
    @EJB
    private PaisServiceRemote paisService;
    
    @EJB
    private EstadoServiceRemote estadoService;
    
    @EJB
    private MunicipioServiceRemote municipioService;    
    
    @EJB
    private ParroquiaServiceRemote parroquiaService;
    
    @EJB
    private CiudadServiceRemote ciudadService;    

    private Pais pais=new Pais();
    
    private Estado estado= new Estado();
    
    private Municipio municipio=new Municipio();
    
    private Parroquia parroquia=new Parroquia();
    
    private Ciudad ciudad=new Ciudad();
    
    private List<Pais> paises=new ArrayList<>();;
    
    private List<Estado> estados=new ArrayList<>();
    
    private List<Municipio> municipios=new ArrayList<>();
    
    private List<Parroquia> parroquias=new ArrayList<>();
    
    private List<Ciudad> ciudades=new ArrayList<>();
    
    private String pais2;
    
    private String estado2;
    
    private String municipio2;
    
    private String parroquia2;
    
    private String ciudad2;
    
    private Map<String, String> paises2=new HashMap<>();
    
    private Map<String, String> estados2=new HashMap<>();
    
    private Map<String, String> municipios2=new HashMap<>();
    
    private Map<String, String> parroquias2=new HashMap<>();
    
    private Map<String, String> ciudades2=new HashMap<>();
    
    
    /**
     * Creates a new instance of PruebaManagedBean
     */
    public PruebaManagedBean() {

    }

    @PostConstruct
    public void init() {
        paises=paisService.getAll();
        
        for (Pais paise : paises) {
            paises2.put(paise.getNombreCorto(),paise.getId().toString());
        }
    }
    
    public void onPaisChange(final AjaxBehaviorEvent event){
        if(pais2!=null && pais2.length()>0 && NumberUtils.isNumber(pais2)){
            pais=new Pais();
            pais.setId(Long.valueOf(pais2));
            estados= estadoService.findByPais(pais);
            for (Estado estado1 : estados) {
                estados2.put(estado1.getNombre(), estado1.getId().toString());
            }
        }
//        if(pais!=null && pais.getNombreCorto()!=null){
//            estados= estadoService.findByPais(pais);
//        }
    }

    public void onEstadoChange(final AjaxBehaviorEvent event){
//        System.out.println("entro");
//        if(estado!=null && estado.getNombre()!=null){
//            municipios= municipioService.findByEstado(estado);
//            System.out.println("asdad: " +municipios.size());
//        }
        System.out.println("onEstadoChange: "+estado2);
        if(estado2!=null && estado2.length()>0 && NumberUtils.isNumber(estado2)){
            estado=new Estado();
            estado.setId(Long.valueOf(estado2));
            municipios= municipioService.findByEstado(estado);
            for (Municipio municipio1 : municipios) {
                municipios2.put(municipio1.getNombre(), municipio1.getId().toString());
            }
        }
    }
    
    public void onMunicipioChange(final AjaxBehaviorEvent event){
        if(municipio!=null && municipio.getNombre()!=null){
            parroquias= parroquiaService.findByMunicipio(municipio);            
        }
    }
    
    public void onParroquiaChange(final AjaxBehaviorEvent event){
        if(parroquia!=null && parroquia.getNombre()!=null){
            ciudades= ciudadService.findByParroquia(parroquia);
        }
    }

    public void mostrar() {
        FacesMessage msg;
        if(pais != null && estado != null)
            msg = new FacesMessage("Selected", pais.getNombreCorto() + " de " + estado.getNombre());
        else
            msg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid", "City is not selected."); 
             
        FacesContext.getCurrentInstance().addMessage(null, msg);  
    }
    
    public PaisServiceRemote getPaisService() {
        return paisService;
    }

    public void setPaisService(PaisServiceRemote paisService) {
        this.paisService = paisService;
    }

    public EstadoServiceRemote getEstadoService() {
        return estadoService;
    }

    public void setEstadoService(EstadoServiceRemote estadoService) {
        this.estadoService = estadoService;
    }

    public MunicipioServiceRemote getMunicipioService() {
        return municipioService;
    }

    public void setMunicipioService(MunicipioServiceRemote municipioService) {
        this.municipioService = municipioService;
    }

    public ParroquiaServiceRemote getParroquiaService() {
        return parroquiaService;
    }

    public void setParroquiaService(ParroquiaServiceRemote parroquiaService) {
        this.parroquiaService = parroquiaService;
    }

    public CiudadServiceRemote getCiudadService() {
        return ciudadService;
    }

    public void setCiudadService(CiudadServiceRemote ciudadService) {
        this.ciudadService = ciudadService;
    }

    public Pais getPais() {
        return pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }

    public Estado getEstado() {
        return estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    public Municipio getMunicipio() {
        return municipio;
    }

    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }

    public Parroquia getParroquia() {
        return parroquia;
    }

    public void setParroquia(Parroquia parroquia) {
        this.parroquia = parroquia;
    }

    public Ciudad getCiudad() {
        return ciudad;
    }

    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

    public List<Pais> getPaises() {
        return paises;
    }

    public void setPaises(List<Pais> paises2) {
        this.paises = paises2;
    }

    public List<Estado> getEstados() {
        return estados;
    }

    public void setEstados(List<Estado> estados2) {
        this.estados = estados2;
    }

    public List<Municipio> getMunicipios() {
        return municipios;
    }

    public void setMunicipios(List<Municipio> municipios) {
        this.municipios = municipios;
    }

    public List<Parroquia> getParroquias() {
        return parroquias;
    }

    public void setParroquias(List<Parroquia> parroquias) {
        this.parroquias = parroquias;
    }

    public List<Ciudad> getCiudades() {
        return ciudades;
    }

    public void setCiudades(List<Ciudad> ciudades) {
        this.ciudades = ciudades;
    }    

    public String getPais2() {
        return pais2;
    }

    public void setPais2(String pais2) {
        this.pais2 = pais2;
    }

    public String getEstado2() {
        return estado2;
    }

    public void setEstado2(String estado2) {
        this.estado2 = estado2;
    }

    public String getMunicipio2() {
        return municipio2;
    }

    public void setMunicipio2(String municipio2) {
        this.municipio2 = municipio2;
    }

    public String getParroquia2() {
        return parroquia2;
    }

    public void setParroquia2(String parroquia2) {
        this.parroquia2 = parroquia2;
    }

    public String getCiudad2() {
        return ciudad2;
    }

    public void setCiudad2(String ciudad2) {
        this.ciudad2 = ciudad2;
    }

    public Map<String, String> getPaises2() {
        return paises2;
    }

    public void setPaises2(Map<String, String> paises2) {
        this.paises2 = paises2;
    }

    public Map<String, String> getEstados2() {
        return estados2;
    }

    public void setEstados2(Map<String, String> estados2) {
        this.estados2 = estados2;
    }

    public Map<String, String> getMunicipios2() {
        return municipios2;
    }

    public void setMunicipios2(Map<String, String> municipios2) {
        this.municipios2 = municipios2;
    }

    public Map<String, String> getParroquias2() {
        return parroquias2;
    }

    public void setParroquias2(Map<String, String> parroquias2) {
        this.parroquias2 = parroquias2;
    }

    public Map<String, String> getCiudades2() {
        return ciudades2;
    }

    public void setCiudades2(Map<String, String> ciudades2) {
        this.ciudades2 = ciudades2;
    }

    
}
..

**Comment by tandraschko** [comment]
Please provide a java code as small and simple as possible. We can't just take it and try it. Otherwise it will be closed as invalid.

**Comment by Rapster** [comment]
Fork this https://github.com/primefaces/primefaces-test.git and try to reproduce your problem

**Comment by tandraschko** [comment]
Closed for now. Feel free to create a new issue with minimal as possible and working example.
