### ISSUE TITLE
localize am/pm text in schedule component

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#2170]
I am using schedule component and i found that the am/pm text is not localized, please add option to localize it, thanks.

**Comment by tandraschko** [comment]
Feel free to provide a PR.

**Comment by devmsaleh** [comment]
i am sorry what do you mean by PR ?

**Comment by tandraschko** [comment]
Pull Request which includes the changes in our code

**Comment by melloware** [comment]
From looking at this the AM/PM localization is not an option for FullCalendar:  https://fullcalendar.io/docs/text/locale/

**Comment by tandraschko** [comment]
then -> won't fix as long as not supported by fullcalendar
feel free to create a issue there
