### ISSUE TITLE
DataTable: add option to enable/disable contextMenu for a DataTable without records

### ISSUE THREAD

**Issue by Henny-cz** [primefaces/primefaces#2171]
## 1) Environment
- PrimeFaces version: 6.0.16
- Does it work on the newest released PrimeFaces version? -> No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Wildfly 10.1
- Affected browsers: Chrome, Firefox

## 2) Expected behavior

When empty dataTable is rightClicked, I expect normal browser context menu will show up.

## 3) Actual behavior

If dataTable is empty and is rightclicked, p:contextMenu with "for" attribute shows up and you can click on every menuItem which is rendered and not disabled.

## 4) Steps to reproduce

Create empty dataTable, create Context menu for that table -> run -> right click on datatable

## 5) Sample XHTML

(dynamically rendered)

## 6) Sample bean

...

## PS.: 
I found this piece of code in components.js:

...DataTable...
... bindContextMenu: function(e, f, b, a) {
......
   if (j.hasClass("ui-datatable-empty-message")) {
       e.show(i)
   }
....

When "e.show(i)" is commented, it seems to be fixed

**Comment by tandraschko** [comment]
It was a feature request: #1283

**Comment by tandraschko** [comment]
We could think about to introduce a new flag which disabled/enables this behavior.

**Comment by jxmai** [comment]
PR: #3038

**Comment by jxmai** [comment]
@tandraschko milestone is missing :checkered_flag:
