### ISSUE TITLE
SelectCheckboxMenu multiple mode different itemValue and itemLabel caused errors

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#2172]
## 1) Environment
- PrimeFaces version: 6.0.16
- Does it work on the newest released PrimeFaces version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Tomcat 7.70
- Affected browsers: ALL

## 2) Expected behavior
If I use inside <f:selectItem itemLabel="Test" itemValue="test"/> I expect, that I don't have to has item label and item value equals.

## 3) Actual behavior
The component doesn't work if itemLabel and itemValue are not equal. I expect, that data-item-value attribute on tag ul li.ui-selectcheckboxmenu-token has value from attribute itemValue and not from itemLabel.

## 4) Steps to reproduce

try this and check something, it throws jquery exception Syntax error, unrecognized expression: [data-item-value=Test] - it used description as value.

`<p:selectCheckboxMenu multiple="true" label="Components">
                                <f:selectItem itemValue="Test" itemDescription="test"/>
                                <f:selectItem itemValue="Test2" itemDescription="test2"/>
                                <f:selectItem itemValue="Test3" itemDescription="test3"/>
</p:selectCheckboxMenu>`
or
`
<p:selectCheckboxMenu multiple="true" label="Components">
                                <f:selectItem itemValue="Test"/>
                                <f:selectItem itemValue="Test2"/>
</p:selectCheckboxMenu>
`

PS:
The similary problems with attribute data-item-value I found in [#2157](https://github.com/primefaces/primefaces/issues/2157)

**Comment by tandraschko** [comment]
A PR to fix this would be great ;)
