### ISSUE TITLE
DataTable don't update paginator when no records found with given filter

### ISSUE THREAD

**Issue by Henny-cz** [primefaces/primefaces#2178]
You can test it right on this example
https://www.primefaces.org/showcase/ui/data/datatable/tableState.xhtml

At start, you have 5 pages of records.
In column filter "Id" type for example: "blabla"
... message "No cars found with given criteria" will appear in dataTable

But paginator still shows 1 of 5 pages and you can move to next pages which also breaks filter totally. (filled but not filtered by this value)

(Sorry for my bad english)

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/2217 which was already fixed.   Please close this ticket.

**Comment by Ulziimunkh** [comment]
www
