### ISSUE TITLE
Unable to build the project (SSL-Problem)

### ISSUE THREAD

**Issue by DominikLudwig1995** [primefaces/primefaces#2179]
`[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.1-SNAPSHOT: Failed to collect dependencies for [javax.servlet:servlet-api:jar:2.5 (provided), javax.servlet.jsp:jsp-api:jar:2.1 (provided), commons-logging:commons-logging:jar:1.1.1 (compile), commons-lang:commons-lang:jar:2.6 (compile), org.hibernate:hibernate-validator:jar:5.0.1.Final (compile), org.apache.poi:poi:jar:3.7 (compile), org.apache.poi:poi-ooxml:jar:3.7 (compile), com.lowagie:itext:jar:2.1.7 (compile), commons-fileupload:commons-fileupload:jar:1.3 (compile), commons-io:commons-io:jar:2.2 (compile), rome:rome:jar:1.0 (compile), org.twitter4j:twitter4j-core:jar:3.0.5 (compile), javax.inject:javax.inject:jar:1 (compile), org.slf4j:slf4j-simple:jar:1.6.1 (compile), org.primefaces.themes:all-themes:jar:1.0.10 (compile), net.sourceforge.barbecue:barbecue:jar:1.5-beta1 (compile), jfree:jfreechart:jar:1.0.0 (compile), net.glxn:qrgen:jar:1.4 (compile), net.sf.barcode4j:barcode4j-light:jar:2.1 (compile), org.primefaces:primefaces:jar:6.1.RC2-SNAPSHOT (compile), org.glassfish:javax.faces:jar:2.2.10 (compile), org.atmosphere:atmosphere-runtime:jar:2.4.6 (compile)]: Failed to read artifact descriptor for org.primefaces.themes:all-themes:jar:1.0.10: Could not transfer artifact org.primefaces.themes:all-themes:pom:1.0.10 from/to prime-repo (http://repository.primefaces.org): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]`

I get the Exception in the show-case too.

**Comment by Rapster** [comment]
Not a PF problem

**Comment by tandraschko** [comment]
yep, works fine on my 3 machines. Also weird that it tries to lookup certificate path for a http adresss.
Will close it as won't fix. If you have some idea how we can fix something, please come back.

**Comment by krandalf75** [comment]
There is an redirection on the repository. If you enter http://repository.primefaces.org/
you will be redirected to https://repository.primefaces.org/

HTTPS connection provides an certificate (Let'sEncryp) whose root certificate isn't reconized by Java. 
You must manually install it.

**Comment by mertergun** [comment]
I got the same issue today, after purging my local maven repository, mvn could not get the dependencies from prime repo with the same exception. For now the workaround is to download and install the jar manually.

**Comment by mudderman** [comment]
I hade the same issue on my machine (where I just now setup maven from scratch). I had to import the root ssl certificate from the primefaces repo url into my java cacerts file, after that running 

> mvn clean install

worked like a charm.

See http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html for a guide on how to imprt the cert.

On a mac, go to Keychain, Search for DST, Pick the DST Root CA X3 and press File > Export (export as .cer) and import that into the java cacerts as described in the guide above.

**Comment by pkphilip** [comment]
I had to follow the instructions given in Stackoverflow by MagGGG:
https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ
You need to make some changes in how you navigate within Firefox so that you export the certificate as the instructions given in stackoverflow may have been for an older version of Firefox.

1.  Go to URL in your firefox browser, click on HTTPS certificate chain (next to URL address). Click "more info" > "security" > "show certificate" > "details" > "export..". Pickup the name and choose file type example.der. Now you have file with keysotre and you have to add it to your JVM

2.  Determine location of cacerts files, eg. C:\Program Files (x86)\Java\jre1.6.0_22\lib\security\cacerts.

3. Next import the example.der file into cacerts in command line:

keytool -import -alias example -keystore  C:\Program Files (x86)\Java\jre1.6.0_22\lib\security\cacerts -file example.der

You will be asked for password which default is changeit

(I did not need to restart for this to work on Linux)

**Comment by rkrenn** [comment]
can confirm above steps work; although maven/java1.6 is then not yet capable of processing that 2048bit certificate.

hence i had to move to bouncycastle -> https://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception/6862383

is it possible to disable that redirect form http://repository.primefaces.org/ to https://repository.primefaces.org/ on the repository web server?

**Comment by ghost** [comment]
Ensure the `$JAVA_HOME` (or `%JAVA_HOME%` on Windows) environment variable points to a valid JDK installation, then:

1. Open Firefox
1. Visit http://repository.primefaces.org/
1. Click the lock security icon
1. Click the right arrow
1. Click **More Information**
1. Click **Security**
1. Click **View Certificate**
1. Click the **Details** tab
1. Click **Export**
1. Save as **primefaces.der**

Run the following command on Linux:

``` .bash
keytool -import -alias primefaces -keystore $JAVA_HOME/jre/lib/security/cacerts -file primefaces.der
```

Run the following command on Windows:

``` .bash
keytool -import -alias primefaces -keystore %JAVA_HOME%\jre\lib/\security\cacerts -file primefaces.der
```

When prompted:

1. Use the password `changeit`.
1. Set **Trust this certificate** to: `yes`

The certificate is imported.
