### ISSUE TITLE
Datatable sorting in PF 5.2 fails to mark a default sort column when NOT using EL for fieldname

### ISSUE THREAD

**Issue by akarpavicius** [primefaces/primefaces#218]
Primefaces 5.2 datatable
Sorting works fine when using EL expressions to specify column fields as in :
`<p:dataTable var="user" lazy="true" sortBy="#{user.userName}" ...>`
`<p:column headerText="Username" sortBy="#{user.userName}"...
`
However I can NOT use El expression for a field.
The only way I found sorting to work without EL expression for a column is:
`<p:dataTable  var="user" lazy="true".. sortField="userName">`
`<p:column headerText="Username" sortBy="#{null}" field="userName">`

The issue is that username column is not marked as sorted by default, although in sql query I see that sorting is done by username.

Any reason why you need to specify something in `<p:column sortBy` attribute for column to be sortable as   `<p:column  sortable="true" field="userName"` is not sufficient.

**Comment by kukel** [comment]
> Any reason why you need to specify something in `<p:column sortBy`  attribute for column to be sortable as `<p:column sortable="true" field="userName"` is not sufficient.

Historic, backwardscompatibility reasons and some more things... ;-)

And did you try something like `#{dummyNotExistingSomething.username}` ? Might do the 'trick' 

And please use the forum first to discuss things.

**Comment by cagataycivici** [comment]
@akarpavicius, specific field does not exist everytime, sortBy is generic and allows you to define an expression without requiring a field. It is the major advantage and an appreciated feature.

**Comment by cagataycivici** [comment]
You need to define sortBy at table level, it is required. sortField and field are used to pass parameters to lazy load method instead of trying to resolve it from the EL which cannot work in some situations like composite components.

Next time, please use forum for cases like these.

**Comment by akarpavicius** [comment]
> > And did you try something like  #{dummyNotExistingSomething.username}  ? Might do the 'trick' 

I have a framework of custom components and tags that wrap both p:datatable creation and p:column definition. I pass a fieldname of "default sorting field" to a component that wraps p:datatable  and a fieldname to a component that wraps p:colum. I can not create a entity.field EL expression when I receive a fieldname as composite component's or tags attribute.

However, as for sortBy expression - you are right, it can be any junk and column is marked as sorted when datatable's sortBy LITERALLY matches column sortBy value, even both are text. 

Here is a sample of what I end up using:

`<p:dataTable id="users" var="user" lazy="true" value="#{userListBean.lazyDataModel}" paginator="true" rows="10" sortBy="#{'userName'}" sortField="userName">`
 `<p:column headerText="Username" sortBy="#{'userName'}"  field="userName">...`
 `<p:column headerText="Email" sortBy="#{'email'}"  field="email">...`
