### ISSUE TITLE
Filmstrip issue on Galleria PF 5.3

### ISSUE THREAD

**Issue by jlerbsc** [primefaces/primefaces#2188]
## 1) Environment
- PrimeFaces version: 5.3
- Application server + version: Tomcat 8.5
- Affected browsers: Chrome
- Does it work on the newest released PrimeFaces version? Version? I don't know
- Does it work on the newest sources in GitHub? I don't know

If we use a parent node to images in galleria, the filmstrip is generated with undefined src.

    <img src="undefined" class="ui-galleria-frame-image" style="width:85px;height:85px;">

    <p:galleria value="#{cc.attrs.photos}" var="photo" >
        <h:outputLink value="#{request.contextPath}#{photo.url}">
            <h:graphicImage value="#{photo.url}" alt="#{cc.attrs.ad.title} "
							styleClass="frame main-picture" title="#{cc.attrs.ad.title}" />
        </h:outputLink>
    </p:galleria>

A solution is found in this topic perhaps it could help 
https://forum.primefaces.org/viewtopic.php?f=3&t=30989

..

## 2) Expected behavior
the filmstrip is generated with real src

...

## 3) Actual behavior
the filmstrip is generated with undefined src
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

 <p:galleria value="#{cc.attrs.photos}" var="photo" >
        <h:outputLink value="#{request.contextPath}#{photo.url}">
            <h:graphicImage value="#{photo.url}" alt="#{cc.attrs.ad.title} "
							styleClass="frame main-picture" title="#{cc.attrs.ad.title}" />
        </h:outputLink>
    </p:galleria>

..

**Comment by tandraschko** [comment]
Please provide a complete example and answer the questions in the issue template or it will be closed it as invalid.

**Comment by tandraschko** [comment]
Feel free to create a new issue with all informations + all sample codes.

**Comment by jlerbsc** [comment]
It does not matter if you do not want to consider this request, there are also other components available that will do the trick.
