### ISSUE TITLE
Panelgrid columns=2 & layout=grid breaks tabView

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#219]
Panelgrid columns=2 & layout=grid inside tabView breaks others tabs if the last element is not present in the last pair of elements in the actual tab. See the images. If I don't set layout=grid everything is fine.
![1-1](https://cloud.githubusercontent.com/assets/3578953/7445575/f6a6765c-f18f-11e4-86d5-92da3acc136e.jpg)
![1-2](https://cloud.githubusercontent.com/assets/3578953/7445576/f6c77780-f18f-11e4-8b63-f53de54ef5ad.jpg)
![2-1](https://cloud.githubusercontent.com/assets/3578953/7445578/f6ffc90a-f18f-11e4-8a99-8a4dc14a0468.jpg)
![2-2](https://cloud.githubusercontent.com/assets/3578953/7445577/f6ed5d06-f18f-11e4-8f51-0fc7510bb35e.jpg)

**Comment by RejDev** [comment]
Hello,
here is the cause of this problem:
https://github.com/primefaces/primefaces/issues/454
