### ISSUE TITLE
TimeLine: add RTL support

### ISSUE THREAD

**Issue by tzantw** [primefaces/primefaces#2193]
I am working on an arabic portal which makes use of primefaces timeline. Hence the date/year which appears on timeline should be in RTL(Right to left) fashion.
Currently the date/year appears on timeline axis as ...2000 2001 2002 2003...
But in arabic page it should appear from right to left as ...2003 2002 2001 2000...

The analysis are that primefaces have rtl support for tree and datatable. But there is no direct support for having rtl support in timeline.

So are there any possible solution to implement rtl support in primefaces timeline?

Please suggest.

**Comment by Rapster** [comment]
I suggest you to have a look to existing components supporting RTL, then have a try on TimeLine, and finally create a PR :)

**Comment by melloware** [comment]
@jasonex7 Can you add RTL to the new timeline in your PR.  Looks like its an option in vis.js!

https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options

> If true, the timeline will be right-to-left. Note: you can achieve rtl timeline by defining a parent node with dir="rtl". The timeline knows to take the nearest parent node direction and apply it. Notice that the timeline will prefer the option.rtl over any parent dir="rtl"

You can look at InputText as an example you have to implement "RTLAware" interface etc.

**Comment by jasonex7** [comment]
> @jasonex7 Can you add RTL to the new timeline in your PR. Looks like its an option in vis.js!
>
OK, I've just committed that new property. You can check.

**Comment by melloware** [comment]
Nice work!  Change looks good for RTL.
