### ISSUE TITLE
DataTable: .ui-sortable-column.ui-state-active does not recieve .ui-state-hover

### ISSUE THREAD

**Issue by JensPiegsa** [primefaces/primefaces#2195]
## 1) Environment

- PrimeFaces version: 6.0

## 2) Expected behavior

The `th` column header element of a sortable column (`.ui-sortable-column`) of a dataTable should recieve `.ui-state-hover` css class on mouse over even if it is active (`.ui-state-active`).

The `.ui-state-hover` style is neccesary to visually indicate the possibility to click on the column header for resorting.

## 3) Actual behavior

The presence of `.ui-state-active` seems to suppress the attachment of the `ui-state-hover` class on mouse over.
..

## 4) Steps to reproduce

1. implement a `p:dataTable` with enabled column sorting
2. press on a sortable column header once
3. hover the same column header again

**Comment by melloware** [comment]
This appears to be done on purpose that if it is active it does not add the hover although I am not sure why?

```javascript
        this.sortableColumns.on('mouseenter.dataTable', function() {
            var column = $(this);
            
            if(!column.hasClass('ui-state-active'))
                column.addClass('ui-state-hover');
        })
        .on('mouseleave.dataTable', function() {
            var column = $(this);
            
            if(!column.hasClass('ui-state-active'))
                column.removeClass('ui-state-hover');
        })
```

**Comment by JensPiegsa** [comment]
Thanks for looking into this. Maybe it is just copy-pasted from somewhere else, where it makes more sense, e.g. navigation, where interaction with the 'already active element' does not have a meaningful purpose.

**Comment by melloware** [comment]
@JensPiegsa Even if I update the code it will add `ui-state-hover` but it gets overridden by `ui-state-active` so there is no visual change anyway. Do you have a specific use case on why you need `ui-state-hover` when it has no visual effect? I will close this ticket for now unless you have a compelling use case for me to fix it.

![image](https://user-images.githubusercontent.com/4399574/99691971-c58ff780-2a57-11eb-8ec3-94844c6235fd.png)

**Comment by tandraschko** [comment]
not sure melloware
someone could style .ui-state-active.ui-state-hover

**Comment by melloware** [comment]
Yes they could so I really don't see any harm in this change.

**Comment by tandraschko** [comment]
yep
thats something i did years ago for inputs, too
there was the same code
