### ISSUE TITLE
Table not supported in Text Editor

### ISSUE THREAD

**Issue by madhu-singh** [primefaces/primefaces#2197]
1) Environment
- PrimeFaces version: 6.1.RC1
- No
- No
- Glassfish 3.1.2.2
- Mozilla Firefox

2) There should be option to insert table as it is present in CKEditor.
3) Insert table is not available in Text Editor
4) add text editor in any xhtml page and test.

5) <p:textEditor widgetVar="editor1" value="#{editorView.text}" height="300" style="margin-bottom:10px"/>

 6)package org.primefaces.showcase.view.input;
 
import javax.faces.bean.ManagedBean;
 
@ManagedBean
public class EditorView {
     
    private String text;
     
    private String text2;
 
    public String getText() {
        return text;
    }
 
    public void setText(String text) {
        this.text = text;
    }
 
    public String getText2() {
        return text2;
    }
 
    public void setText2(String text2) {
        this.text2 = text2;
    }
}

**Comment by tandraschko** [comment]
Its not available in the QuillEditor, so we cant fix this.
You can just use the PF Extensions CKEditor ;)

**Comment by hink084** [comment]
Update: CKEditor was removed in PFE 12.0.5 and replaced with SunEditor in PFE 12.0.6 due to licensing issues.

PFE Issue 1106: https://github.com/primefaces-extensions/primefaces-extensions/issues/1106

SunEditor Showcase: https://www.primefaces.org/showcase-ext/views/sunEditor.jsf
