### ISSUE TITLE
custom locales and i18n

### ISSUE THREAD

**Issue by albfan** [primefaces/primefaces#2198]
## 1) Environment
- PrimeFaces version: 5.2
- Application server + version: jboss EAP 6.2
- Affected browsers: All

## 2) Expected behavior

Installing https://github.com/javagalician you get "gl" Locale

Using FacesContext.getCurrentInstance().getViewRoot().setLocale() to change locale

Datatable columns with bigdecimal do nots follow the numericformat defined for Galician

1,234.56 = 1.234,56

## 3) Actual behavior

1,234.56 = 1,234.56

Seems it fall back to english locale.

This code get the correct symbols

java.text.NumberFormat.getInstance(new Locale("gl")); 

This one no:

new java.text.DecimalFormatSymbols(new Locale("gl"))

Where is the numericformatter retrieved on an outputText?

sample xhtml:

    <h:outputText value="#{item.number}">
        <f:convertNumber pattern="#,##0.00" />
    </h:outputText>

bean is:

    class Bean() {
        public BigDecimal number() {
            return number;
        }
    }

**Comment by tandraschko** [comment]
I can't see any PrimeFaces relation. Please use stackoverflow or the forum.

**Comment by albfan** [comment]
Yes. I realize after write it, thanks
