### ISSUE TITLE
SelectCheckboxMenu -  deselect all with required=true not calls valueChangeListener

### ISSUE THREAD

**Issue by ValerioEmanuele** [primefaces/primefaces#2199]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1.RC2
- Application server + version: Wildfly 9.0.2.
- Affected browsers: Chrome, Internet Explorer

## 2) Expected behavior
When the user click on the de-select all ckeckbox on the header of the SelectCheckboxMenu the valueChangeListener method should be called even if required=true
...

## 3) Actual behavior
The valueChangeListener is called only when the user select all the items.
..

## 4) Steps to reproduce
Define selectCheckBoxMenu with a required=true, updateLabel=true and a valueChangeListener, of course inside a <form/>, and a submit button.
Then select all checkboxes with the checkbox button on the header of the selectCheckBoxMenu, then submit the form.
Everything should work fine.
Now de-select all with the checkbox on the header of the selectCheckBoxMenu, you will notice that the valueChangeListener method is not called. Now click the submit button: the labels of the selectCheckBoxMenu will be populated with all the items even if those values are not submitted.

.. 

## 5) Sample XHTML
	<h:form id="mainForm">
	<p:selectCheckboxMenu id="gallerie"
					required="true"
					value="#{controller.selectedGalleria}" 
					label="#{msg.galleria}" 
					multiple="true"
					filter="true"
					filterMatchMode="contains"
					valueChangeListener="#{controller.galleriaSelectedListener}"
					updateLabel="true">
		<f:selectItems value="#{controller.gallerie}" var="g" itemLabel="#{g.descrizioneGalleria}" itemValue="#{g.codiceGalleria}" />
		<p:ajax update="contentSection msgGallerie @this"></p:ajax>
	</p:selectCheckboxMenu> 
	
	<p:commandButton value="#{msg.cerca}"
					 id="searchButton" 
					 icon="fa fa-search"
					 ajax="true"
					 partialSubmit="true"
					 process="@form"
					 validateClient="false"
					 update="centralContainer risultatoContainer"
					 actionListener="#{controller.searchListener}">
	
	</p:commandButton> </h:form>

## 6) Sample bean
```
public class Controller
{
	protected static Logger log = Logger.getLogger(VentilazioneController.class);
	
	protected LinkedHashMap<String, Galleria> gallerie;
	protected List<String> selectedGalleria;
	
	@PostConstruct
	public void mainInit(){
		selectedGalleria = new ArrayList<>();
		gallerie = new LinkedHashMap<>();
		for (Galleria g :galleriaService.getAllGallerieValide()){
			gallerie.put(g.getCodiceGalleria(), g);
		}
	}
	
	public void searchListener(ActionEvent actionEvent) {
		try{
			log.info("Galleria(e):" + selectedGalleria);
		}
		catch (Throwable e){
			log.error(e);
		}
	}
	
	public void galleriaSelectedListener(ValueChangeEvent e) {
		selectedGalleria = (List<String>) e.getNewValue();
	}
	
	public List<String> getSelectedGalleria() {
		return selectedGalleria;
	}

	public void setSelectedGalleria(List<String> selectedGalleria) {
		this.selectedGalleria = selectedGalleria;
	}
	
	public void setGallerie(LinkedHashMap<String, Galleria> gallerie) {
		this.gallerie = gallerie;
	}

	public List<String> getSelectedGalleria() {
		return selectedGalleria;
	}
}
```

```
public class Galleria implements Serializable {
	private String codiceGalleria;
	private String descrizioneGalleria;
	
	public String getDescrizioneGalleria() {
		return descrizioneGalleria;
	}
	public void setDescrizioneGalleria(String descrizioneGalleria) {
		this.descrizioneGalleria = descrizioneGalleria;
	}
	public String getCodiceGalleria() {
		return codiceGalleria;
	}
	public void setCodiceGalleria(String codiceGalleria) {
		this.codiceGalleria = codiceGalleria;
	}
}

```

**Comment by tandraschko** [comment]
Not sure about this.
If you deselect all, no value is selected -> required validation fails. Right?
If the validation failed, a valueChangeListener should never get invoked.

**Comment by ValerioEmanuele** [comment]
I agree with you, but the problem is that I deselect all and I am able to submit the form because I don't have enabled client side validation.
The result is that after the ajax view refresh I see the checkbox menu with all the labels inside it because it's value was not updated and this is wrong. Moreover this not happens if I do the same steps with a single checkbox.
I Hope that now my phrase was clear if not I am available ti vive you further information.

**Comment by tandraschko** [comment]
I dont talk about client side validation, its the same for server side validation!

**Comment by ValerioEmanuele** [comment]
Ok, I understand that is not a bug. Thanks for your answers.
