### ISSUE TITLE
Updates to Building-From-Source wiki page

### ISSUE THREAD

**Issue by srbala** [primefaces/primefaces#22]
Building-From-Source wiki page has been updated to follow git procedure, please review and approve.

https://github.com/primefaces/primefaces/wiki/Building-From-Source

**Comment by brunolmfg** [comment]
Fixed checkout of tags in git.

**Comment by srbala** [comment]
Good to know.

Thank you
Bala

**Comment by cagataycivici** [comment]
Looking good thanks.
