### ISSUE TITLE
Update fullcalendar to 2.3.2

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#220]
Update fullcalendar to 2.3.2 since it looks they are only correcting bugs. https://github.com/arshaw/fullcalendar/releases

**Comment by sudheerj** [comment]
The current latest version is 2.6.So this issue can be duplciate of #1029

**Comment by erickdeoliveiraleal** [comment]
2.7.1 https://github.com/fullcalendar/fullcalendar/releases

**Comment by tandraschko** [comment]
Duplicate of #1029
