### ISSUE TITLE
Calendar Date Range

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#2202]
Hi,

it would be nice to have the Date Range selection on <p:calendar> 
like the Range Slider in <p:slider>

I've found this jquery extension on github that may be useful
http://tamble.github.io/jquery-ui-daterangepicker/

Bye,
Paolo

**Comment by ravihariharan** [comment]
https://www.primefaces.org/showcase/ui/input/calendar.xhtml --> Multiple: can show you multiple months.

Are you referring to the 
- Today, 
- Yesterday
- Last 7 Days
- Last Week (Mo-Su)
- Month to Date
- Previous Month
- Year to Date

![image](https://cloud.githubusercontent.com/assets/15189434/24295495/592d839a-1071-11e7-9cd1-a38235036dd1.png)

**Comment by pizzi80** [comment]
Yes, but it can't bind to 2 different java.util.Date values

**Comment by kukel** [comment]
Already implemented on Prime-NG... https://github.com/primefaces/primeng/issues/3609  Is PrimeFaces now 'behind' (less important? ;-)) Can it be ported? Would that be difficult? Can I provide a pull request

**Comment by melloware** [comment]
@kukel I think a PR would be welcome!

**Comment by kukel** [comment]
I'll take a look at it over the holidays... Currently starting my own business, developing two applications for the retail business (both based on PF ofcourse). Might be that I'll provide PF support to in the Netherlands, to bridge the gap untill my applications are providing enough income.

**Comment by melloware** [comment]
This will be fixed with the new DatePicker being ported from PrimeNG in the next PF: https://www.primefaces.org/primeng/#/calendar

**Comment by melloware** [comment]
This feature is now available in DatePicker: https://github.com/primefaces/primefaces/issues/4360

@tandraschko this ticket can be closed.
