### ISSUE TITLE
Includes jQuery version (1.11.3) which has known XSS vulnerability

### ISSUE THREAD

**Issue by mauritz-lovgren** [primefaces/primefaces#2204]
## 1) Environment
- PrimeFaces version: 6.0.16
- Does it work on the newest released PrimeFaces version? No, but 6.0.17 includes same jQuery version.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No, latest source includes same JQuery version.
- Application server + version: all major, irrelevant
- Affected browsers: all

## 2) Expected behavior

Should not include 3rd party component with known XSS vulnerability.

## 3) Actual behavior

Includes jQuery version 1.11.3 which has XSS vulnerability: https://github.com/jquery/jquery/issues/2432

## 4) Steps to reproduce

Deploy a JSF application that uses PrimeFaces, analyse the web page using security check tool, such as http://retire.insecurity.today, which produces this output:

https://www.primefaces.org/showcase/index.xhtml
Detected libraries:
jquery - 1.11.3 : (active1) https://www.primefaces.org/showcase/javax.faces.resource/jquery/jquery.js.xhtml;jsessionid=node0h1mk27rrc45l1180zgbg7qi06335565.node0?ln=primefaces&v=6.0.16
Info: Severity: medium
https://github.com/jquery/jquery/issues/2432
http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
(active) - the library was also found to be active by running code

## 5) Sample XHTML

N/A

## 6) Sample bean

N/A

**Comment by tandraschko** [comment]
@cagataycivici @mertsincan should we upgrade to jquer 1.12 for the next RC?!

**Comment by cagataycivici** [comment]
Better to wait for 6.2 but since it is XSS, we should. @mertsincan please update jquery.

**Comment by lagar84** [comment]
jQuery reverted the change in 1.12.3 (and 1.12.4), so only versions that has the fix is jquery-1.12.0, jquery-1.12.1 and jquery-1.12.2

Source: https://github.com/jquery/jquery/issues/3011

**Comment by tandraschko** [comment]
Ok so we can update jquery but the issue of the reporter will not be fixed. Upgrading to a already outdated version doesnt make sense IMO.

**Comment by tandraschko** [comment]
Created a new issue for updating jquery+jquery UI after the release: #2233
