### ISSUE TITLE
SelectOneMenuRenderer - encodeOptionsAsTable ignores null for itemValue

### ISSUE THREAD

**Issue by oliverjstein** [primefaces/primefaces#2207]
I think it should be fixed if you change the condition in encodeOptionsAsTable from
`if(itemValue instanceof String)`
to 
`if(itemValue == null || itemValue instanceof String)`

## 1) Environment
- PrimeFaces version: 6.0.17

## 2) Expected behavior
selectOneMenu combined with columns: When setting itemValue to null the item should be displayed with provided label
<f:selectItem itemValue="#{null}" itemLabel="#{msg['general.selectItem.noSelectionOption']}"/>

## 3) Actual behavior
The itemLabel does not get rendered

## 4) Steps to reproduce
see xhtml

## 5) Sample XHTML

.<p:selectOneMenu id="unit" value="#{searchInfoPointController.unitToMatch}" converter="safeSelectItemsIndexConverter"
                                 var="u" filter="true" filterMatchMode="startsWith">
                    
                    <f:selectItem itemValue="" itemLabel="#{msg['general.selectItem.noSelectionOption']}"/>
                    <f:selectItems value="#{searchInfoPointController.units}" var="unit" itemLabel="#{unit.name}" itemValue="#{unit}"/>
                    <p:column>
                        <h:outputText value="#{u.name}"/>
                    </p:column>
                    <p:column>
                        <h:outputText value="#{u.measurand.name}"/>
                    </p:column>
                </p:selectOneMenu>.

**Comment by tandraschko** [comment]
The example misses searchInfoPointController.

**Comment by oliverjstein** [comment]
the controller is not necessary - you can use any collection for the selectItems

 The relevant part is that you have to set itemValue to an empty string:
<f:selectItem itemValue="" itemLabel="#{msg['general.selectItem.noSelectionOption']}"/>

**setting itemValue to null does NOT work:**

<f:selectItem itemValue="#{null}" itemLabel="#{msg['general.selectItem.noSelectionOption']}"/>

**Comment by melloware** [comment]
PR submitted!
