### ISSUE TITLE
Slider support for InputNumber

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2208]

**Comment by mertsincan** [comment]
Hi @tandraschko, 
We have an issue related to inputNumber and slider. Could you please check it?
You can see it on http://localhost:8080/showcase/ui/input/slider.xhtml (InputNumber Slider demo)
Test;
-  please slide p:slider component
-  enter a value to inputNumber(Exp: 12).
- then, please try to slide p:slider again. You'll see a JS error to console.

**Comment by tandraschko** [comment]
@mertsincan seems like i only tested one direction of the binding :D

**Comment by tandraschko** [comment]
fixed ;)

**Comment by mertsincan** [comment]
Thanks a lot, @tandraschko :) it works fine for me ;)
