### ISSUE TITLE
Datatable Column groupRow Row Spans Incorrect Column If More Than One Column Marked as Grouped

### ISSUE THREAD

**Issue by jschuck9** [primefaces/primefaces#2210]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:  **6.1RC2**
- Does it work on the newest released PrimeFaces version? Version?  **Yes**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)   **Yes**
- Application server + version:  **Glassfish 4.1.2**
- Affected browsers:  **All**

## 2) Expected behavior

When marking more than one column as row grouped, each subsequent column will be spanned when data matches.

e.g.

The below example illustrates the desired functionality.  In this example column 0 and 1 are marked as groupRow="true" however column2 is groupRow="false" sorted by columns 0 and 1.

Column 0 | Column1 | Column2
------------ | -----------  | ------------
<empty> | <empty> | XYZ
ABC | 1 | XYZ
<empty> | <empty> | WXY

...

## 3) Actual behavior

Any column marked as grouped after the first, e.g. column 1 will be skipped for row spanning, instead column 2 will be row spanned.

e.g.

The below example illustrates the actual functionality.  In this example column 0 and 1 are marked as groupRow="true" however column2 is groupRow="false" but is included in a row span incorrectly.

Column 0 | Column1 (should be spanned) | Column2 (should not be spanned)
------------ | --------------------------------------- | -------------------------------------------
<empty> | 1 | <empty>
ABC | 1 | XYZ
<empty> | 1 | WXY

..

## 4) Steps to reproduce

1. Create a datatable with more than one column

1.  Mark the first two columns as groupRow="true"
      * Leave all others as the default of groupRow="false"

1. Set column sort by the first two columns.

.. 

## 5) Sample XHTML

``` html
<p:dataTable var="car" value="#{dtRowGroupView.cars}">
    <p:column headerText="Brand" sortBy="#{car.brand}" groupRow="true">
         <h:outputText value="#{car.brand}" />
    </p:column>
    <p:column headerText="Year" sortBy="#{car.year}" groupRow="true">
        <h:outputText value="#{car.year}" />
    </p:column>
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
    <p:column headerText="Id">
        <h:outputText value="#{car.id}" />
    </p:column>
</p:dataTable>
```
..

## 6) Sample bean

Use showcase CarService and RowGroupView from [https://www.primefaces.org/showcase/ui/data/datatable/rowGroup.xhtml](url)

..

**Comment by jschuck9** [comment]
The actual error appears to be in datatable.js.  When grouped columns are setup for row spanning, the initial group column is removed from the column array.  This causes the index to be off by one.

The call ```this.groupRow(this.cfg.groupColumnIndexes[i]);``` appears to pass an incorrect column index to groupRow.

See lines:  3412 - 3440 in datatable.js

```javascript
    groupRows: function() {
        for(var i = 0; i < this.cfg.groupColumnIndexes.length; i++) {
            this.groupRow(this.cfg.groupColumnIndexes[i]);
        }
    },
    
    groupRow: function(colIndex) {
        var rows = this.tbody.children('tr');
        var groupStartIndex = null, rowGroupCellData = null, rowGroupCount = null;
        
        for(var i = 0; i < rows.length; i++) {
            var row = rows.eq(i);
            var column = row.children('td').eq(colIndex);
            var columnData = column.text();
            if(rowGroupCellData != columnData) {                    
                groupStartIndex = i;
                rowGroupCellData = columnData;
                rowGroupCount = 1;
            }
            else {
                column.remove();
                rowGroupCount++;
            }
            
            if(groupStartIndex != null && rowGroupCount > 1) {
                rows.eq(groupStartIndex).children('td').eq(colIndex).attr('rowspan', rowGroupCount);
            }
        }
},
```

**Comment by jschuck9** [comment]
Also, on livescroll with lazy data tables, appears to group the second column when the table reads more rows from the backing bean.

**Comment by jschuck9** [comment]
The fix for this is surprisingly simple.  Instead of calling `column.remove()` when a row is added to the group, call `column.hide()` instead.

The core issue occurs because once the column is removed, subsequent calls to get the column from each row by index is off by 1 because all rows > 0 are missing the group column.

NOTE:  Tested via primefaces-test

Fixed code below:
```
    groupRow: function(colIndex) {
        var rows = this.tbody.children('tr'); 
        var groupStartIndex = null, rowGroupCellData = null, rowGroupCount = null;
        
        for(var i = 0; i < rows.length; i++) {
            var row = rows.eq(i);
            var column = row.children('td').eq(colIndex);
            var columnData = column.text();

            if(rowGroupCellData != columnData) {                    
                groupStartIndex = i;
                rowGroupCellData = columnData;
                rowGroupCount = 1;
            }
            else {
                // Change from column.remove() to column.hide() to ensure column counts
                // match for each subsequent row
                column.hide();
                rowGroupCount++;
            }
            
            if(groupStartIndex != null && rowGroupCount > 1) {
                rows.eq(groupStartIndex).children('td').eq(colIndex).attr('rowspan', rowGroupCount);
            }
        }
    }
```

**Comment by jschuck9** [comment]
Test View:

```
package org.primefaces.test;

import java.io.Serializable;
import java.util.List;
import java.util.Arrays;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    private static final long serialVersionUID = 4124891683211838799L;
    
    private String testString;
    private List<Team> teams;
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
        teams = Arrays.asList(new Team[]{new Team("Rockies","NL West","National League",17,11),
                           new Team("Diamondbacks","NL West","National League",17,12),
                           new Team("Dodgers","NL West","National League",15,14),
                           new Team("Padres","NL West","National League",12,17),
                           new Team("Giants","NL West","National League",11,18),
                           new Team("Cubs","NL Central","National League",15,12),
                           new Team("Cardinals","NL Central","National League",13,13),
                           new Team("Brewers","NL Central","National League",14,14),
                           new Team("Reds","NL Central","National League",13,14),
                           new Team("Pirates","NL Central","National League",12,15),
                           new Team("Nationals","NL East","National League",18,9),
                           new Team("Marlins","NL East","National League",12,14),
                           new Team("Phillies","NL East","National League",12,14),
                           new Team("Mets","NL East","National League",12,15),
                           new Team("Braves","NL East","National League",11,15)});
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }  
    
    public List<Team> getTeams() {
        return this.teams;
    }
    
    // Inner-classes
    public final class Team implements Serializable {
        
        private static final long serialVersionUID = -1398368309948759392L;
        
        private String name;
        private String division;
        private String conference;
        private int wins = 0;
        private int losses = 0;
        
        public Team(String name,String division,String conference,int wins,int losses) {
            setName(name);
            setDivision(division);
            setConference(conference);
            setWins(wins);
            setLosses(losses);
        }
        
        public Team() {            
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        public String getName() {
            return this.name;
        }
        
        public void setDivision(String division) {
            this.division = division;
        }
        
        public String getDivision() {
            return this.division;
        }
        
        public void setConference(String conference) {
            this.conference = conference;
        }
        
        public String getConference() {
            return this.conference;
        }
        
        public void setWins(int wins) {
            this.wins = wins;
        }
        
        public int getWins() {
            return this.wins;
        }
        
        public void setLosses(int losses) {
            this.losses = losses;
        }
        
        public int getLosses() {
            return this.losses;
        }
    }
}
```

**Comment by jschuck9** [comment]
Test page:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        
        <h1>#{testView.testString}</h1>
        
        <h:form id="testForm">
            <p:dataTable id="teamTab"
                         value="#{testView.teams}"
                         var="team"
                         sortBy="#{team.conference}">
                <p:column id="conferenceCol" 
                          sortBy="#{team.conference}"
                          groupRow="true">
                    <f:facet name="header">
                        <h:outputText value="Conference" style="font-weight: bold;"/>
                    </f:facet>
                    <h:outputText value="#{team.conference}"/>
                </p:column>                
                <p:column id="divisionCol" 
                          sortBy="#{team.division}"
                          groupRow="true">
                    <f:facet name="header">
                        <h:outputText value="Division" style="font-weight: bold;"/>
                    </f:facet>
                    <h:outputText value="#{team.division}"/>
                </p:column>
                <p:column id="nameCol" 
                          sortBy="#{team.name}"
                          groupRow="false">
                    <f:facet name="header">
                        <h:outputText value="Team" style="font-weight: bold;"/>
                    </f:facet>
                    <h:outputText value="#{team.name}"/>
                </p:column>                
                <p:column id="winsCol" 
                          sortBy="#{team.wins}"
                          groupRow="true">
                    <f:facet name="header">
                        <h:outputText value="Wins" style="font-weight: bold;"/>
                    </f:facet>
                    <h:outputText value="#{team.wins}"/>
                </p:column>                
                <p:column id="lossesCol" 
                          sortBy="#{team.losses}"
                          groupRow="true">
                    <f:facet name="header">
                        <h:outputText value="Losses" style="font-weight: bold;"/>
                    </f:facet>
                    <h:outputText value="#{team.losses}"/>
                </p:column>                                
            </p:dataTable>
        </h:form>
        
    </h:body>
</html>
```

**Comment by jschuck9** [comment]
@cagataycivici Please review, I believe an appropriate fix has been identified above.

**Comment by mertsincan** [comment]
Thanks for the sample codes, I'll check and get back to you.

**Comment by tgutan** [comment]
Hi all,
There is still an issue with the grouping (groupRow), when the table has "rows" (with pagination).
Example:
data set: 
[["Audi", "red"], ["Audi", "blue"], ["Opel", "white"]]

**For**
<p:dataTable ...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; rows="2"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ...>
&nbsp;&nbsp;&nbsp;&nbsp;<p:column headerText="Maker" groupRow="true">...</p:column>
&nbsp;&nbsp;&nbsp;&nbsp;<p:column headerText="Color">...</p:column>
</p:dataTable>

**1. The expected result should look like:**

| Maker | Color |
|-------|-------|
| Audi  | red   |
|       | bue   |
| Opel  | White |

**2. Instead, it looks like:**

| Maker | Color |
|-------|-------|
| Audi  | red   |
|       | bue   |

Sorry for the bad formatting (I'm not an Markdown ace).
So, I think 1. is the right result, not as currently rendered - 2.
Is this really an issue, or am I wrong?

Thanks!

**Comment by jschuck9** [comment]
@tgutan in your example you set rows="2".  This means that a maximum of 2 rows will be displayed per page.  It looks like your rendered results (as shown in example 2) are correct.  If you want the results to show as in your first example, set rows="3".

**Comment by tgutan** [comment]
@jschuck9, thank you kindly for your response. Technically, you are correct. Those are, indeed, 3 rows. But, conceptually (the way I see it, and I don't intend to impose my vision as correct), when you group them, you actually say: I have 2 car rows, but each car might have a subset of data. 

Perhaps, I am seeing this from the perspective of the use case I have. If we are to go deeper into the concepts, then things might become more complex. Now, that I think of it, what I want to achieve is indeed an edge case that can not be easily generalized.

I understand I was not fully correct. If there are 2 groupRow columns, what would the rows attribute refer to?!

Thanks again for your time and support!

**Comment by jschuck9** [comment]
@tgutan no problem!  :)  In this case it doesn't work quite like that.  The grouping doesn't result in a tree structure as such, rather it orders by and then spans common elements n rows for display purposes.  I recommend that you investigate a tree table to do what you are describing in this scenario.

**Comment by tgutan** [comment]
@jschuck9  Thanks! Suggestion welcome and noted!
