### ISSUE TITLE
mobile - add onload event to pm:page

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2216]
Related to those forum threads a onload event to pm:page would be great to manually set focus on a new input element or to invoke other actions.

https://forum.primefaces.org/viewtopic.php?f=8&t=22097
https://forum.primefaces.org/viewtopic.php?f=8&t=41999

https://code.google.com/archive/p/primefaces/issues/4350

**Ugly Workaround**

Use a timeout and call method like _<script>pageOnLoad('myPageId')</script>_ in last statement before _</pm:content>_

	/*
	 * @pageId ID of page that is loaded
	 */
	function pageOnLoad(pageId)
	{
		window.setTimeout
		(
			function()
			{
				switch (pageId)
				{
					case "pageSearch":
						$(PrimeFaces.escapeClientId("pageSearch:formSearch:query_input")).focus();
						break;
				}
			},
			400
		)
	}

**Comment by djmj** [comment]
Oh i think its unnecessary since there is already:

	$(document).on('pageshow', '#pageStock', function(){
		$(PrimeFaces.escapeClientId("pageSearch:formSearch:query_input")).focus();
	});

**Comment by tandraschko** [comment]
Will close it for now as not required by the reporter. If you would provide a PR, we can still add the functionality.
