### ISSUE TITLE
Update jQuery UI to 1.11.4

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#222]
http://jqueryui.com/changelog/

**Comment by cagataycivici** [comment]
We have latest already.

**Comment by erickdeoliveiraleal** [comment]
No. https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/jquery/jquery-plugins.js and https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/jquery/ui/jquery-ui.css

**Comment by erickdeoliveiraleal** [comment]
This issue need to be reopened.
