### ISSUE TITLE
p:calendar timeOnly="true" doesn't work with Client Side Validation

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#2220]
1. Open [http://primefaces.org/showcase/ui/input/calendar.xhtml](http://primefaces.org/showcase/ui/input/calendar.xhtml) in a browser.
2. Adjust the value of the last field labeled "Time" to any value, except null/blank.
3. Click Submit button

Validation error message is reported: "Time: '00:00' could not be understood as a date. Time: '00:00' could not be understood as a date. Example: 3/30/17 20:37".

**Comment by ghost** [comment]
Furthermore, if `CalendarView.java` is modified so that the `date11` field is initialized with `new Date()` (or anything besides null), then the p:calendar's input field will be initially rendered with the date part (e.g. "3/30/2017 11:43AM"), even though it has `pattern="HH:mm"`.

Disabling the global `primefaces.CLIENT_SIDE_VALIDATION` context parameter solves these issues.

**Comment by melloware** [comment]
I wonder if this is related to this issue too #2013

**Comment by mertsincan** [comment]
Fixed for 6.1.Final and 6.0.19. https://github.com/primefaces/primefaces/issues/2280

**Comment by melloware** [comment]
@mertsincan I think you can close https://github.com/primefaces/primefaces/issues/2013 as well as its the same issue I believe.

**Comment by mertsincan** [comment]
Thanks @melloware :)
