### ISSUE TITLE
p:ajax does not work inside h:selectOneMenu. Uncaught ReferenceError: jsf is not defined.

### ISSUE THREAD

**Issue by itsmemarioss** [primefaces/primefaces#2221]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6
- Does it work on the newest released PrimeFaces version? Version? nops 
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: wildfly 10
- Affected browsers: chrome

## 2) Expected behavior
Hi guys, I'm keeping a system (not designed by me) and I decided to upgrade primefaces in this project (5.3 to 6)
I followed the migration guide, and I changed primefaces-extentions as well.

The client noticed that some selectOneMenu was not updating other fields when it was changed.
In this system it is used h: selectOneMenu and not p: selectOneMenu because some js scripts (but that is not the point)
In a few xhtml pages there are more than one call of p: ajax inside h: selectOneMenu, but it was working very well before I migrate prime.

I cloned primefaces-test project to try it out and I had the same outcome, p: ajax inside h: selectOneMenu didn't work
```
<h:selectOneMenu value="#{testView.value}">

	<f:selectItem itemLabel="Select" />
	<f:selectItems value="#{testView.strings}" />

	<p:ajax event="change" update="text1" listener="#{testView.listenerOne}" />
	<p:ajax event="change" listener="#{testView.listenerTwo}" update="text2" />

</h:selectOneMenu>
```

I noticed that when I changed the h:selectOneMenu the following error was printed out in browser console

**Uncaught ReferenceError: jsf is not defined**

so when I added 

`<f:ajax></f:ajax>`

everything worked out

I don't know if this is bug, and I've been away from primefaces until now.
There is a lot of pages in the system and I'm sure that there are more pages with the same issue.
So what should I do? Is it a real issue? 
...

## 3) Actual behavior
p:ajax does not work inside h:selectOneMenu in version 6 but it does in version 5.3
..

## 4) Steps to reproduce
put p:ajax inside h:selectOneMenu
.. 

## 5) Sample XHTML
```
<h:selectOneMenu value="#{testView.value}">

	<f:selectItem itemLabel="Select" />
	<f:selectItems value="#{testView.strings}" />

	<p:ajax event="change" update="text1" listener="#{testView.listenerOne}" />
	<p:ajax event="change" listener="#{testView.listenerTwo}" update="text2" />

</h:selectOneMenu>
```
..

## 6) Sample bean
really simple bean
..

**Comment by tandraschko** [comment]
As you added 2 behaviors (p:ajax) for 1 event, the JSF impl must render a "helper script" to execute the behaviors ony by one.
If you will check the generated JS, something like "jsf.util.chain" should be there.

We can't fix anything regarding this as this is up to the JSF impl but there is a simple workaround:
<h:outputScript name="jsf.js" library="javax.faces" target="head"/>

Also, if you add 2 p:ajax for the same event, 2 ajax requests will be fired! this is really bad for the performance.
I would just register 1 p:ajax call the 2 mehtods inside the listener method. This will also fix your problem ;)

**Comment by itsmemarioss** [comment]
Ok, thanks man. I really thought about call one method but as I said I don't know how many pages have the same issue. I appreciate your help.
