### ISSUE TITLE
Grouping for SelectCheckboxMenu not working

### ISSUE THREAD

**Issue by schmolleg** [primefaces/primefaces#2222]
Hello,

it seems that the issue:
https://github.com/primefaces/primefaces/issues/500

was not fixed for SelectCheckboxMenu. I use primfaces 6.0 but the component SelectCheckboxMenu does not work with ItemGroups. Example code an screenshots can be found in ticket #500.

**Comment by melloware** [comment]
PR submitted to fix this issue:  https://github.com/primefaces/primefaces/pull/2430

**Comment by schmolleg** [comment]
Thx for implementing !

**Comment by renatossalves** [comment]
I'm using primefaces 6.1, and SelectCheckboxMenu doesnt work with grouping yet!

**Comment by melloware** [comment]
Its fixed in Elite 6.1.6.
