### ISSUE TITLE
PhotoCam: improve error handling

### ISSUE THREAD

**Issue by marquem** [primefaces/primefaces#2223]
Hi,

It would be great to improve the photocam's error handling, similar to the discreet error messages provided by the fileUpload component. The problem I have with alerts is, they tend to be ugly, intrusive and aren't very user-friendly on mobile devices.

Thanks,
Michael

## Environment
- PrimeFaces version: 5.2, 6.0, 6.0.17
- Application server + version: JBoss EAP 6.4

**Comment by tandraschko** [comment]
A PR or technical ideas are welcome here ;)
