### ISSUE TITLE
SelectCheckboxMenu mode="multiple" Inability To Remove Item

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2229]
## 1) Environment
- PrimeFaces version: 6.0.17
- Does it work on the newest released PrimeFaces version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Jboss EAP 6.4.7
- Affected browsers: ALL

## 2) Expected behavior

When restoring the page with values the Multiple Items in the SelectMenuCheckbox should be removable by clicking the "x" icon in the label.

## 3) Actual behavior

Not able to remove them by pressing the "x".

## 4) Steps to reproduce

My SelectItems list is a list of POJO's with a valid @FacesConverter for converting values.  Initially the page works fine but once you submit values and update="@form" the "x" icons no longer work. 

Before submit:
```xml
<li class="ui-selectcheckboxmenu-token data-item-value="3">
```
After submit:
```xml
<li class="ui-selectcheckboxmenu-token  data-item-value="InterfacePoint[id=3,name=TST,description=Testing PF Issue,pointOfReceipt=true,pointOfDelivery=true]">
```

## 5) Sample XHTML
```xml
<p:selectCheckboxMenu id="selPor" value="#{atcPostingForm.queryCriteria.selectedPors}" 
                                        label="#{appmsg['label.all']}" updateLabel="true" multiple="true" filter="true"              filterMatchMode="startsWith">
	<f:selectItems value="#{pointOfReceiptSelectItems}" />
</p:selectCheckboxMenu>
```
## 6) Sample bean

Valid POJO and @FacesConverter for InterfacePoint objects.

PR coming next!

**Comment by mertsincan** [comment]
Thanks a lot for the PR !

**Comment by melloware** [comment]
@mertsincan No problem.  Can you look at this ticket too?  I think it can be closed as this feature is alreayd implemented.  https://github.com/primefaces/primefaces/issues/75
