### ISSUE TITLE
DataTable: discuss default rowKey mechanism / use JSF converter for rowKey and rowData

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#223]
What about enhancing this approach using a JSF converter since it follows the same conversion idea of JSF and its components and provides a clean reusable interface?

In my generic DAO's my overriden methods simply call the converter method.
A converter could also be passed to datatable attribute in markup as in any other component.

```
public class MyJsfGenericDAO <T extends Entity> extends LazyDataModel<T>
{
    private final Converter converter;

    public MyJsfGenericDAO(...)
    {
        this.converter = new MyEntityConverter(entities);
    }


   @Override
   public Object getRowKey(final T t)
   {
      return this.converter.getAsString(FacesContext.getCurrentInstance(), null, t);
   }

   @Override
   public T getRowData(final String rowKey)
   {
      return (T) this.converter.getAsObject(FacesContext.getCurrentInstance(), null, rowKey);
   }
}
```

http://forum.primefaces.org/viewtopic.php?f=3&t=41556&p=132065

Another idea is to add a default rowKey mechanism via Entity#hashCode.

Probably both makes sense.

**Comment by melloware** [comment]
No upvotes in 5 years and I don't see any real advantage of changing the code to support this.

**Comment by djmj** [comment]
I also dont see much advantage to it or it could even make smaller projects / tables more complicated then just using attribute _rowKey_ directly. 

The only positive thing i see is the JSF consistency across data conversions with an attribute like _converter_.

**Comment by Rapster** [comment]
Agreed, I'll coment later on this

**Comment by tandraschko** [comment]
we dont need to do it for 9.0 but i like the approach
often you already have a converter available for a Entity e.g. and this can just be reused (@FacesConverter(for = MyEntity.class))

**Comment by Rapster** [comment]
I'll assign it to you Thomas, as I don't see the added-value of this. I see why `Converter` comes in mind as it looks very similar to what we do with selection, but turns out, with multi-selection `LazyDataModel#getRowData` is not optimized at all, and in normal mode, `DataTable#rowKey` is good enough,

**Comment by tandraschko** [comment]
I dont plan to work on it for now

**Comment by tandraschko** [comment]
This can easily implemented via:

```
public abstract class LazyDataModel<T> extends ListDataModel<T> implements SelectableDataModel<T>, Serializable {

    private Converter converter;

    public LazyDataModel() {

    }

    public LazyDataModel(Class<T> modelClass) {
        FacesContext context = FacesContext.getCurrentInstance();
        this.converter = context.getApplication().createConverter(modelClass);
    }

    public LazyDataModel(Converter converter) {
        this.converter = converter;
    }

    @Override
    public T getRowData(String rowKey) {
        if (converter != null) {
            FacesContext context = FacesContext.getCurrentInstance();
            return (T) converter.getAsObject(context, UIComponent.getCurrentComponent(context), rowKey);
        }

        throw new UnsupportedOperationException(
                getMessage("getRowData(String rowKey) must be implemented by %s when basic rowKey algorithm is not used [component=%s,view=%s]."));
    }

    @Override
    public String getRowKey(T object) {
        if (converter != null) {
            FacesContext context = FacesContext.getCurrentInstance();
            return converter.getAsString(context, UIComponent.getCurrentComponent(context), object);
        }

        throw new UnsupportedOperationException(
                getMessage("getRowKey(T object) must be implemented by %s when basic rowKey algorithm is not used [component=%s,view=%s]."));
    }
}
```

**Comment by tandraschko** [comment]
is it worth to include those additional constructors?

**Comment by melloware** [comment]
Not sure I love those constructors but could we add a new class that was `LazySelectableDataModel` ??

The new class would prevent breaking backward compatibility.

**Comment by tandraschko** [comment]
TBH i dont like a new class
and the new constructors would just be optional

**Comment by melloware** [comment]
OK if they don't break backwards compatibility I am OK with it.

**Comment by tandraschko** [comment]
i will close it for now
i think it has no advantage for non-lazy mode but for lazy
and for this purpose someone can just call the converter manually in getRowData/getRowKey
