### ISSUE TITLE
Patch proposal: tabview.js#init   - explicitly hide non selected tabs (don't let browser decide)

### ISSUE THREAD

**Issue by alainpannetier** [primefaces/primefaces#2231]
This is a bug fix proposal

## 1) Environment
- PrimeFaces version: 6.1 - straight from git head
- Application server + version: irrelevant: client side JS stuff
- Affected browsers: Gecko, Blink, Webkit
- The important point is that large scale projects can have several copies of jquery-ui.css
- Browsers may have to chose between several possible CSS rules at execution time and are selecting the most specific but there can be ambiguity. 
- Primefaces usually does not have the latest jquery js, css

In TabView.js. at init time all tabs are visible if broswers don't make the right decision.
My proposal is to explicitely hide the non selected one at initialisation time (further manual select of tabs works OK).

## 2) Expected behavior
- all tabs should be hidden except tab 0 or selected one

## 3) Actual behavior
 - Depends on browser CSS rule priority logic and bundled copies of jquery-ui.css
 - In unfavourable situations, all tabs are visible at init time
 - further tab selection behaves as expected

## 4) Steps to reproduce
 - Add another jquery-ui.css
 - Standard <p:tabview><p:tab> snippet should do.

## 5) Environment
Proposed patch.  There might be more concised ways.
```

/**
 * PrimeFaces TabView Widget
 */
PrimeFaces.widget.TabView = PrimeFaces.widget.DeferredWidget.extend({

    init: function(cfg) {
        this._super(cfg);
[...]
        this.tabindex = this.cfg.tabindex||0;
[...]
        this.renderDeferred();

        /*
         * Start patch:
         * In some rare cases, when the browser does not make the 'right'
         * decision of CSS rules, 'ui-helper-hidden' is ignored.
         * Hiding of non-visible tabs must then be explicit.
         */
        var tabContents = this.panelContainer.children('.ui-tabs-panel:visible');
        for ( var i = 0; i < tabContents.length; i++) {
            if ( i != this.tabindex ) {
                $(tabContents[i]).hide() ;
                }
            }
        /*
         * End patch.
         */
    },

```

**Comment by tandraschko** [comment]
IMO we will likely not fix this as we also won't support jquery added by the user (instead using jquery provided by PF)
