### ISSUE TITLE
renderKitId with value null leads to NullPointerException in CalendarResourceListener

### ISSUE THREAD

**Issue by UlrichLohrmann** [primefaces/primefaces#2232]
Primefaces Version 6.1, RC1
running on WebSphere application Server 8.5.5 with ,myfaces 2.2.11.
Application also uses Spring Web flow 2.2.4

We have some JSF facelets with p:calendar components in a form . On form submit we face a NullPointerException in org.primefaces.mobile.event.system.CalendarResourceListener in method processEvent, line 36, within the following statement:

```
if(renderKitId.equals(Constants.MOBILE_RENDER_KIT_ID)) {
    view.addComponentResource(context, createResource(context, "mobile/widgets/datepicker.css", Constants.LIBRARY, "javax.faces.resource.Stylesheet"));
    view.addComponentResource(context, createResource(context, "mobile/widgets/datepicker.js", Constants.LIBRARY, "javax.faces.resource.Script"));
}

```
In case of NPE the local variable "renderKitId" ist null.

No idea whether renderKitId could be null here or not but the NPE could be prevented if the comparison would be changed to. 

`if(Constants.MOBILE_RENDER_KIT_ID.equals(renderKitId))
`
instead of

`if(renderKitId.equals(Constants.MOBILE_RENDER_KIT_ID))`

**Comment by tandraschko** [comment]
Its already there ;)

`        if(Constants.MOBILE_RENDER_KIT_ID.equals(renderKitId)) {
            ResourceUtils.addComponentResource(context, "mobile/widgets/datepicker.css", Constants.LIBRARY, "head");
            ResourceUtils.addComponentResource(context, "mobile/widgets/datepicker.js", Constants.LIBRARY, "head");
        }`
