### ISSUE TITLE
Issue With InputNumber  6.1.RC2

### ISSUE THREAD

**Issue by liams62217** [primefaces/primefaces#2235]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1.RC2
- Does it work on the newest released PrimeFaces version? Version? Yes  , 6.0 
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) 
- Application server + version:  WildFly 10
- Affected browsers: ALL

## 2) Expected behavior

validate the input value ,  

Version  6.0         ==> OK
Version  6.1.RC2 ==>  KO

## 3) Actual behavior

Validation error

## 5) Sample XHTML

<p:outputLabel for="montantPAE" value="Montant"       indicateRequired="true />
       <p:inputNumber widgetVar="montantPAE"
                required="true"
             id="montantPAE" symbol="€" thousandSeparator=" "
             decimalSeparator="," symbolPosition="s"
             value="#{bean.montant}"
             requiredMessage="Montant Obligatoire">
</p:inputNumber>
 
![image001](https://cloud.githubusercontent.com/assets/13629537/24608662/cecdead2-1877-11e7-8724-694c28c01db4.jpg)
## 6) Sample bean

private double montant;

**Comment by tandraschko** [comment]
Works fine for me in trunk/github master:

`
        <h:form>
            <p:messages />
            <p:outputLabel for="montantPAE" value="Montant" indicateRequired="true" />
            <p:inputNumber widgetVar="montantPAE"
                           required="true"
                           id="montantPAE" symbol="€" thousandSeparator=" "
                           decimalSeparator="," symbolPosition="s"
                           value="#{myBean.montant}"
                           requiredMessage="Montant Obligatoire">
            </p:inputNumber>
            <p:commandButton process="@form" update="@form" value="Post it!" />
        </h:form>
`


`
@ManagedBean("myBean")
@ViewScoped
public class MyBean implements Serializable
{
    private double montant;

    public double getMontant()
    {
        return montant;
    }

    public void setMontant(double montant)
    {
        this.montant = montant;
    }
}

`

**Comment by liams62217** [comment]
Thanks you @tandraschko ,
FYI  that Works using  6.1.RC2  when  : 
- I remove  :  symbol="€"
- I replace  : decimalSeparator=","  [comma] by decimalSeparator="." [point]
