### ISSUE TITLE
Column: New attribute exportValue for DataExporter (similar to exportFunction)

### ISSUE THREAD

**Issue by andyfinch** [primefaces/primefaces#2238]
## 1) Environment
- PrimeFaces version: 6.0.17
- Does it work on the newest released PrimeFaces version? New Feature 

## 2) Expected behavior
Currently the column's Exported cell Value is either the contents of the p:column or derived from the ExportFunction attribute which should resolve to a MethodExpression which resolves to a String.

## 3) Actual behavior
I propose a new attribute of ExporterValue for p:column which takes a standard valueExpression.  This will enable the exporter output to much easier resemble the screen output but allow for easy changes specific for the export output.

The background for this request is that we have some very complicated dataTables which need to be outputed via dataExporter.  What we found was that some combination of tags/nested tags are not handled by the dataExporter or our columns contain extra data specific to screen output.  We had issues trying to use ExportFunction attribute as it seems to require a new method implementation.  

## 4) Sample XHTML

`<p:column headerText="first" exporterValue="#{vo.firstName}">
                <h:panelGroup>
                    
                    <h:outputText value="#{vo.firstName}"/>
                    <h:outputText value="screen only"/>
                </h:panelGroup>
            </p:column>`

**Comment by tandraschko** [comment]
There already is "exportFunction".

**Comment by andyfinch** [comment]
You obviously didn't read what I put.  ExportFunction is heavyweight.  ExportValue would be fair simpler to use.

**Comment by tandraschko** [comment]
There is nothing heavyweight on exportFunction.
You can simple define a globalController which do a toString() ->

p:column exportFunction="#{exportUtil.toString(item.myValue}"

But i can leave your request open for the future ;)

**Comment by andyfinch** [comment]
Thank you tandraschko.  Yes by having to write a function we have already adding complexity.  The function will either have lots of if/else/switch in when working with multiple columns/values or you have to write multiple functions. Either way the potential for lots of code.  In my use case I have 1 column which I add hidden data on screen.  Currently this hidden data comes out on the exporter.  With ExportValue I can just give it the initial valueExpression used in the column minus the extra stuff.  I have several columns where the h:outputText is wrapped in a h:panelGroup.  Currently the exporter will output the toString() of the h:panelGroup.  Again I can just provide ExportValue with the same valueExpression as the nested h:outputText.  I have columns which show icons (e.g. tick/cross).  With ExportValue I can pass a simple ternary expression to output Y/N, Yes/No or any specific literal for the Exporter.

As you can see in my use case the ExportFunction becomes heavyweight.  Alternatively could ExportFunction be changed to take either MethodExpression or ValueExpression?

**Comment by tandraschko** [comment]
> he function will either have lots of if/else/switch in when working with multiple columns/values or you have to write multiple functions.

Yep exactly but the problem is that the most ValueExpressions are not a string, therefore we would probably neeed to attach converters or just call toString(). 


>  Alternatively could ExportFunction be changed to take either MethodExpression or ValueExpression?

maybe yes!

**Comment by andyfinch** [comment]
For info this is some code in 5.2.12 (my current production version) I've overridden to get this working for myself.

`public class CustomExcelExporter extends ExcelXExporter {

    @Override
    protected void exportCells(DataTable table, Object document) {
        Sheet sheet = (Sheet) document;
        int sheetRowIndex = sheet.getLastRowNum() + 1;
        Row row = sheet.createRow(sheetRowIndex);

        for (UIColumn col : table.getColumns())
        {
            if (col instanceof DynamicColumn)
            {
                ((DynamicColumn) col).applyStatelessModel();
            }

            if (col.isRendered() && col.isExportable())
            {
                if (col instanceof com.my.Column)
                {
                    if ( col.getValueExpression("exporterValue") != null)
                    {
                        addColumnValue(row, ((Column) col).getExporterValue());
                    }
                    else {
                        addColumnValue(row, col.getChildren());
                    }
                }
                else {
                    addColumnValue(row, col.getChildren());
                }

            }

        }
    }
    
}`

For this to work I already use a custom DataTable/Column implementation extending yours.  I added ExportValue to my column implementation.  I have then added my own DataExporterTagHandler (based on yours) which references my own DataExporter (based on yours) which then uses the CustomExcelExporter when the correct type is passed in. 

As an aside the reason I already have custom DataTable/Column was to add ColIndex attribute to my columns.  I then overrode DataTable.getColumns() and sort on ColIndex.  This allows me to have dynamic  columns but still be able to have all the benefits of statically defining a p:column rather than p:columns.

**Comment by melloware** [comment]
Not exactly what you wanted but I found a really cool way to do what I want generically.

**Custom Exporter:**
```java
@Named
@ApplicationScoped
public class PassthroughColumnExporter {

   public String export(final UIColumn column) {
      String value = StringUtils.EMPTY;
      for (final UIComponent child : column.getChildren()) {
         final Object exportValue = child.getAttributes().get("data-export");
         if (exportValue != null) {
            value = String.valueOf(exportValue);
            break;
         }
      }

      return value;
   }
}
````

Using it generically in any datatable column...
```xml
<p:column width="140" exportFunction="#{passthroughColumnExporter.export}">
    <h:outputText value="#{controller.abbreviate(row.parameters, 12)}" data-export="#{row.parameters}" />					
</p:column>
```

**Comment by awenger63** [comment]
@melloware 
Hi , your solution work fine for one colmun, but how is ti possible to use it only for some column, not for all whit a <p:columns .. ? You only declare one exportFunction for all columns !
Is it possible to call default sometime and passthrough for other ?
Thanks for your suggestion

**Comment by melloware** [comment]
Good question I never thought about p:columns and your right you can only declare one on the columns.  Can you give me your exact use case?

**Comment by awenger63** [comment]
@melloware
Example of implementation need

<p:colmuns> whit 3 columns but only one exportFunction ! :

    first : LABEL
    seconde : NAME
    third : DATE-TIME with f:converter (pattern="EEEEEEEE, MMM dd, yyyy")

Wanted in

    pdf : exactly what I see, than no exportFunction and no dataChange
    xls or cvs : in first colmun the CODE of the LABEL, second the NAME, and third the DATE-TIME in Date format UTC whitout converter

It makes sense ?

**Comment by melloware** [comment]
I see.  Not quite sure how my workaround can work for this.  I will have to think about it but not sure i have a clever workaround for you.

**Comment by awenger63** [comment]
@melloware Thanks for your reply.
On my side, 
First, I add property for define which export is, I set it on preProcessor
Seconde, I change scope as view for my new property
thant is it possible to test it on exportFunction to know if it's xls, pdf ... on the current form
Now, I look for call standard function when I don't want to custom the colmun data on export function and I can resolve my need ;-)
regards
