### ISSUE TITLE
calendar viewChange event bug

### ISSUE THREAD

**Issue by federicomartinlara1976** [primefaces/primefaces#2240]
## 1) Environment
- PrimeFaces version: 6.0 (Community)
- Application server + version: Tomcat 7.0 and Apache MyFaces 2.2.12
- Affected browsers: All browsers

## 2) Expected behavior
On push buttons next and prev, ajax event viewChange must change the month in calendar popup table

## 3) Actual behavior
ajax event viewChange hides and shows the same month in calendar popup table
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<p:calendar id="calendar"...>

            <p:ajax event="viewChange"
               listener="#{cc.monthYearChangeAction}"
                update="#{cc.clientId}:datos"
                process="@this"
                async="false" />

</p:calendar>

## 6) Sample bean

public void monthYearChangeAction(DateViewChangeEvent event) {
       ...
    }

**Comment by tandraschko** [comment]
Can't replicate. The month is is correct on the view and in the event class.

**Comment by tandraschko** [comment]
Also the exmaple is not valid and not fully runnable. So please provide a small xhtml + bean without any other dependencies (like a CC or something).
Will close it for now till updated with a better example.
