### ISSUE TITLE
Document TransferEvent

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#2244]
Please document `org.primefaces.event.TransferEvent` (see https://www.primefaces.org/docs/api/6.0/ for the empty Javadoc).

**Comment by tandraschko** [comment]
All of our events are undocumented and there is a small docu in the user guide.
So feel free to provide a PR or it will likely not happen ;)

**Comment by melloware** [comment]
Submitted PR

**Comment by tandraschko** [comment]
Closed for now, maybe we will do it in the future.
