### ISSUE TITLE
Feature requests for p:growl

### ISSUE THREAD

**Issue by thiotes** [primefaces/primefaces#2245]
Hi, i have some issues with the component (we are using version 6.0)

The first is that i cannot change the close icon behavior. I would like to always show the icon to close the message, but since it is a scripted to show and hide, that's a bit problematic. Was it not possible to use CSS for it?

The second is that i would like to automatically close (sticky=false) only messages of severity info, and close them even if messages of another severity exist as well (but not close those). (e.g. instead of just giving sticky a value of true or false, give it a list of severities for which it will be true)

**Comment by tandraschko** [comment]
Please don't create one issue for multiple stuff! 1 issue = 1 request!
Also the first is a question -> use the forum or create a feature request with exact description what you would like to change here.
