### ISSUE TITLE
Dialog Framework: Inner dialog with dialog status does not work correctly in Firefox 52.0

### ISSUE THREAD

**Issue by slovi** [primefaces/primefaces#2248]
## 1) Environment
- PrimeFaces version: 6.0, 6.1.RC1, 6.2.RC2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: tomcat 7
- Affected browsers: Firefox 52.0

## 2) Expected behavior
Inner dialog (dialog 2 in example) is opened for second try.
...

## 3) Actual behavior
Inner dialog (dialog 2 in example)is not opened for second try (does not work only in Firefox 52.0).
..

## 4) Steps to reproduce

- Create link which opens dialog (by dialog framework - requestcontext.openDialog)
- In dialog, create link which opens new dialog (by dialog framework - requestcontext.openDialog)
- Close inner dialog (requestcontext.closeDialog)
- try to open inner dialog again - it is not possible in Firefox 52.0

Check out this application as an example:
https://github.com/slovi/primefaces-bugs

- click bug2
- open dialog 1
- open dialog 2
- close dialog 2
- open dialog 2 -> javascript error NS_ERROR_NOT_AVAILBLE in FF 52.0

IF dialog2 does not contain ajaxstatus - it DOES work.

## 5) Sample XHTML

index.xhtml

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

	<h:head></h:head>
	
	<h:body>
		<p><h:outputLink value="#{request.contextPath}/index.xhtml">Back</h:outputLink></p>
		<h:form>
			<p:commandLink value="Show dialog 1" actionListener="#{dialogView.showDialog1}" />
		</h:form>
	</h:body>
	
</html>

dialog1.xhtml

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

	<h:head>
	
	</h:head>
	
	<h:body>

		<h:outputText value="Test dialog 1" />
		
		<h:form>
			<h:panelGrid columns="1">
				<p:commandLink value="Close dialog 1" actionListener="#{dialogView.closeCurrentDialog}" />		
				<p:commandLink value="Show dialog 2" actionListener="#{dialogView.showDialog2}" />
			</h:panelGrid>
		</h:form>
	
	</h:body>
</html>

dialog2.xhtml

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

	<h:head>
	
	</h:head>
	
	<h:body>

		<h:outputText value="Test dialog 2" />
		
		<h:form>
			<p:commandLink value="Close dialog 2" actionListener="#{dialogView.closeCurrentDialog}" />					
		</h:form>
		
		<p:ajaxStatus>
			<f:facet name="start">
				<p:dialog modal="false" draggable="false" closable="false" 
					resizable="false" visible="true" position="center" showHeader="false" 
					styleClass="pvng-dialog-backgroud-transparent" dynamic="false" showEffect="fade">
					<p:graphicImage value="#{resource['images:loading/ajaxloading.gif']}" />
				</p:dialog>
			</f:facet>
			<f:facet name="complete">
			</f:facet>
		</p:ajaxStatus>
	
	</h:body>
</html>

## 6) Sample bean

@ManagedBean
@ViewScoped
public class DialogView implements Serializable {

	private static final long serialVersionUID = 7123165280133112773L;

	public void showDialog1(ActionEvent e) {
		RequestContext.getCurrentInstance().openDialog("/bug2/test-dialog-1");
	}
	
	public void showDialog2(ActionEvent e) {
		RequestContext.getCurrentInstance().openDialog("/bug2/test-dialog-2");
	}
	
	public void closeCurrentDialog(ActionEvent e) {
		RequestContext.getCurrentInstance().closeDialog(null);
	}
}

**Comment by slovi** [comment]
Example app git repository changed to https://github.com/slovi/primefaces-bugs

**Comment by melloware** [comment]
@slovi Is this still true in the latest FireFox Quantum 62+ against PF 6.3-SNAPSHOT?

**Comment by melloware** [comment]
@slovi One more chance, have you tested this on newer PF and Firefox?

**Comment by melloware** [comment]
Closing with no response from OP.  If its still reproducible we can reopen the ticket.
