### ISSUE TITLE
p:chips style="width:100%" issue

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#2249]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1 RC1/RC2
- Does it work on the newest released PrimeFaces version? Version?No
- Does it work on the newest sources in GitHub? (Build by source -> No
https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Any
- Affected browsers: All

## 2) Expected behavior
What should be the expected behavior of  <p:chips style="width:100%" /> ?
I would think that the .ui-chips and .ui-chips-container  should be of width:100%.
...

## 3) Actual behavior
reference : http://stackoverflow.com/questions/43216268/primefaces-chips-web-component-properties/43217778#43217778

The width remains at default 400px.
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<h:body style="background-color:red">
    <h:form>
        <p:chips style="width:100%" />
    </h:form>
</h:body>
..

## 6) Sample bean

..

**Comment by melloware** [comment]
I see what you mean.   I think to be most flexible an inputStyle + inputStyleClass would need to be added as well as a chipStyle and chipStyleClass to custom style the chi labels themselves.

If you need to accomplish this right now you can do it pretty easily with CSS.

```css
<style>
.chip-width > .ui-chips-container {
   width: 800px;
}
</style>
```

And in your XHTML.
```xml
<p:chips id="chips" styleClass="chip-width"/>
```

**Comment by melloware** [comment]
I have added inputStyle and inputStyleClass to chips like...

```xml
<p:chips id="chips" inputStyle="width: 800px" inputStyleClass="myClass"/>
```

**Comment by 5hu6hamKadam** [comment]
Just Add p-fluid class to make it's width 100%.
`<p-chips id="chips" class="p-fluid"> </p-chips>`

**Comment by melloware** [comment]
@5hu6hamKadam This is for PrimeFaces JSF and your post above is for PrimeNG.
