### ISSUE TITLE
JSF1064: Unable to find or serve resource, messages/messages.png, from library, primefaces.

### ISSUE THREAD

**Issue by gulbinas** [primefaces/primefaces#2254]
## 1) Environment
- PrimeFaces version: RC_6.2
- Does it work on the newest released PrimeFaces version? Version? Yes. 6.0 was ok
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Payara 4.1.1.171
- Affected browsers: all

## 2) Expected behavior

No error

## 3) Actual behavior

```Unable to find or serve resource, messages/messages.png, from library, primefaces.```

**Comment by tandraschko** [comment]
No example, it works fine for us -> invalid.
