### ISSUE TITLE
Bug in calendar time in showcase of primefaces

### ISSUE THREAD

**Issue by SantoshCCS** [primefaces/primefaces#2260]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

...

## 3) Actual behavior

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..
![image](https://cloud.githubusercontent.com/assets/19163028/24862861/1142b59c-1e1c-11e7-8971-224bd115f0fc.png)

**Comment by tandraschko** [comment]
Duplicate: https://github.com/primefaces/primefaces/issues/2220
