### ISSUE TITLE
JSF 2.3 support for PF Elite

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2262]
Hi, it seems that p:inputText does not support pass-trough for data attributes. I think this was working in a previous primefaces version.

Possibly problematic line

`
renderPassThruAttributes(context, inputText, HTML.INPUT_TEXT_ATTRS_WITHOUT_EVENTS);
`

Version used: 6.0.17 Elite

In my opinion data-* attributes should always be allowed for passtrough, as it is allowed HTML5

Thanks

**Comment by tandraschko** [comment]
Please try 6.1.RC2
Also debug renderPassThruAttributes - you will see that there renderDynamicPassThruAttributes will be called if JSF 2.2 is used.

**Comment by cnsgithub** [comment]
I'm already using JSF 2.3. Could it be caused by this? Will try 6.1 RC thanks

**Comment by tandraschko** [comment]
Please debug and check the if statements!
Otherwise i can't help and just have to close this issue as you miss many informations.

**Comment by tandraschko** [comment]
It could also be a Mojarra 2.3 bug, so pls try 2.2 too ;)

**Comment by cnsgithub** [comment]
The reason seems to be that PF 6.0 just checks for (   return version.startsWith("2.2");  ) . So if PF 6.0 does not support JSF 2.3 it's fine. With PF 6.1 RC2 it works again

---

However if there's no reason to _not support_ a jsf 2.3 config on PF 6.0 , maybe it could be backported?
The method is named 'isAtLeastJSF22()'  -  and well JSF 2.3 is 'at least 2.2'

**Comment by tandraschko** [comment]
@mertsincan would you like to port everything? I wouldn't do it as there are more commits for it - also for dynamic resource loading, parameter namespacing and else...

**Comment by cnsgithub** [comment]
A simple solution probably could be to just assume JSF 2.3 is JSF 2.2 for PF 6.0 - as there should not be any drawbacks. Of course new features are not supported - but not necessary

**Comment by tandraschko** [comment]
Nope, it will lead to other errors, too.

**Comment by tandraschko** [comment]
As there are already community releases which are supporting JSF 2.3, it doesn't make sense to port this features as it's risky to just merge them.

@mertsincan please reopen if you would like to port it.
