### ISSUE TITLE
 p:dock with icons of Font Awesome

### ISSUE THREAD

**Issue by wernerchr** [primefaces/primefaces#227]
Add functionality to use icons of font awesome as dock icons.
Example:

``` HTML
<p:dock position="bottom">
      <p:menuitem value="Home" icon="fa fa-globe" url="#" />
</p:dock>
```

**Comment by tandraschko** [comment]
a PR would be great ;)

**Comment by melloware** [comment]
I looked into this and using FontAwesome in the Dock would not be possible.  The JavaScript is manipulating images only for its effects.  Closing for now.
