### ISSUE TITLE
Paginator Dropdowns Don't Match Theme

### ISSUE THREAD

**Issue by gmlongo1** [primefaces/primefaces#2270]
## 1) Environment
- PrimeFaces version: 5.3
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 8
- Affected browsers: All

## 2) Expected behavior
The RowsPerPageDropdown and the JumpToPageDropdown inside the Paginator should be rendered in the same style/theme as the Primefaces SelectOneMenu.

## 3) Actual behavior
The RowsPerPageDropdown and the JumpToPageDropdown in the Paginator are rendered as basic HTML selects and therefore do no match the PrimeFaces SelectOneMenus and are not themeable.

## 4) Steps to reproduce
Add a datatable to your JSF view with a corresponding Paginator.  Make sure the Paginator has the RowsPerPageDropdown or JumpToPageDropdown in the paginatorTemplate.

**Comment by melloware** [comment]
The Paginator is a normal HTML <select> option whereas the SelectOneMenu is a rendered <div> with multiple CSS stylings to make it look like a <select> box but really is not.

Maybe those stylings can be applied to the Paginator select but I am not that great at CSS to try and fix this one.

**Comment by gmlongo1** [comment]
Yes, I can style the control somewhat with CSS, but it would be nice if these select controls were rendered identically to the SelectOneMenu, so that the same theme styles can be applied consistently.

**Comment by melloware** [comment]
I would say if you can figure it out with CSS submit a PR!

**Comment by tandraschko** [comment]
Its not possible with plain CSS.
Also it must be configurable as many persons e.g. use h:selectOneMenu and not p:selectOneMenu.

**Comment by gmlongo1** [comment]
Good point Thomas about having a configuration option for using the native JSF selectOneMenu or the primefaces selectOneMenu.

**Comment by RaveKev** [comment]
I asked for that feature on facebook (this ticket is a result), because i styled the p:selectOneMenu-elements already and have a hard time, trying to style the<select>-elements the same way (also on the p:calendar).

It's not only the style of the box itself that couldn't be styled on each browser, but also the list of the selectable elements. p:selectOneMenu is a **huge** enrichment with its div-Elements.

Primefaces has some points where the default <select> is used, in example the already mentioned calendar, the p:dataTable inline edit and the paginator.

**Comment by kukel** [comment]
p:calendar is more problematic since it is an existing component (from outside PrimeFaces). but it would be a nice enhancement

**Comment by kukel** [comment]
can't the Prime-UI dropdown be 'applied' to this select?

**Comment by buunsal** [comment]
PrimeFaces 5.3 themes are no longer supported.
