### ISSUE TITLE
 Position issue on the panel of Calendar in Dialog

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2271]
Reported By PRO User;
> this happened between PF 6.0.15 and 6.0.18. If we revert to 6.0.15 the issue is not there.
> We have narrowed the problem down but let me explain the issue.
> 1. Using a p:calendar on a screen in a modal dialog.
> 2. Bring up the dialog and click the calendar it is fine. However if we click the "right arrow" to go to the next month in the Date Picker the whole Calendar jumps down the screen. I can see the "top" CSS value in Chrome go from top 314px to 778px or depending on where i am on the page that "top" value can jump increasingly.
> ...

**Comment by gollrich** [comment]
we are experiencing the same issue with 6.1.2,

**Comment by mertsincan** [comment]
Hi @gollrich,
I couldn't replicate it with 6.1.2. Could you please create a new Github issue for your issue? Also, please add a sample code into it to replicate for us.
