### ISSUE TITLE
primefaces-crud-generator-with-netbeans

### ISSUE THREAD

**Issue by andresgarcia0313** [primefaces/primefaces#2274]
Failed to install / Error al instalar 
https://www.primefaces.org/primefaces-crud-generator-with-netbeans/
What I can do?  PLEASE!!!  / Que puedo hacer? please andresgarcia0313@gmail.com

**Comment by tandraschko** [comment]
Its not maintained by us, use the project website to get in contact: https://sourceforge.net/projects/nbpfcrudgen/
