### ISSUE TITLE
PhotoCam: add auto detach when rendered=false

### ISSUE THREAD

**Issue by mayankX** [primefaces/primefaces#2275]
Need a way to stop/disable photocam, currently rendering photocam false, still doesn't disable browser photocam and also prevents photocam from working when rendering it back to true.

**Comment by melloware** [comment]
Can you elaborate more on what you are looking for?  Are you looking for a disabled="true" attribute on the Photocam?

Also have you tried just shutting it down with Javascript by calling PF('yourWidgetVar'). dettach(); ?? That resets the camera and unhooks it from the component.

**Comment by mayankX** [comment]
Hi @melloware thnx for information on the **dettach** function, I was unable to find it anywhere in the documentation. 

Also i am looking for this function to be called automatically whenever component is rendered **false** 

And a disabled true/false functionality would be nice as well.

**Comment by tandraschko** [comment]
it SHOULD work now. Please try.
