### ISSUE TITLE
BreadCrumb: add option to disable the last item by default

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#2276]
Allowing a h:outputText in p:breadCrumb would be nice, or a current / last item text attribute on p:breadCrumb.

**Comment by melloware** [comment]
Since Breadcrumb is a menu container I don't think they will modify it to take anything other than p:menuitem's.   

Can you elaborate on what you are trying to accomplish and maybe there is a way of doing it right now.  Such as styling your particilar menu item to look like text instead of a link and having the menu item url="#" so it does nothing.  You could event modify the style to remove the hand icon so someone doesn't even know its clickable.

**Comment by jepsar** [comment]
Thanks. I would prefer not to hack workarounds like this.

Maybe a facet is easier to add to a menu container?

**Comment by melloware** [comment]
A facet would be the right way to go for this feature.

**Comment by jepsar** [comment]
.. just checked the code, and there [already is a facet called `options`](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/breadcrumb/BreadCrumbRenderer.java#L86) to do so. This was also present in the documentation PDF (6.2), but this is not the first place where I would look (shame on me).

So, this issue might be closed as invalid or won't fix. However, I do think it would be an improvement to mention / use this facet in the [showcase](https://www.primefaces.org/showcase/ui/menu/breadcrumb.xhtml).

**Comment by melloware** [comment]
@jepsar Just submit that fix to the Showcase Facelift. https://github.com/primefaces/showcase-facelift  They usually accept PR's without having to create an issue first just reference this issue in your PR.

**Comment by jepsar** [comment]
Sorry, but the `options` facet is something different. This issue is still valid. I'll provide a PR for both PrimeFaces and the showcase.

**Comment by jepsar** [comment]
> Can you elaborate on what you are trying to accomplish and maybe there is a way of doing it right now. Such as styling your particular menu item to look like text instead of a link and having the menu item url="#" so it does nothing. You could event modify the style to remove the hand icon so someone doesn't even know its clickable.

I've been playing with this facet for a while and it would take some extra HTML (I would say a span will do), a extra CSS class and some extra rules to keep things consistent.

An other option I tried is just using a disabled menu item. This does not require any changes in the code and will not interfere with existing themes for sure. However, accessibilitywise / semanticswise, this is not the best option. But then, there is more in the breadcrumb which could be improved semanticswise.

What do you think? Add the facet anyway?

**Comment by melloware** [comment]
I say if you have this need then submit a PR and hope it gets accepted.  If it doesn't get accepted its still valuable because you can simply make your own custom component to make it work in your projects.
