### ISSUE TITLE
Datatable: reflow mode using columns incorrect sorting dropdown

### ISSUE THREAD

**Issue by vip30** [primefaces/primefaces#2286]
## 1) Environment
- PrimeFaces version: 6.0
- Application server + version: JBoss EAP 6.1
- Affected browsers: All

## 2) Expected behavior
Use columns in reflow datatable and display headertext for sorting
The responsive dropdown filter will display the headertext correctly

## 3) Actual behavior
The columns headertext disappear on the dropdown menu but can be shown in the tbody
The first of five columns are using dynamic column and the last two are using static content (So the headertext can be shown)
BTW, the seven columns' sorting function are ok
![issue](https://cloud.githubusercontent.com/assets/4260833/25137745/3bd86b42-248b-11e7-9e88-8de624924ff2.png)

## 4) Steps to reproduce
Use the below XHTML and resize your browser to be mobile width

## 5) Sample XHTML
```XML
<p:dataTable
						id="responseTable"
						widgetVar="responseTable#{form.formId}"
						value="#{getFormResponseList(form)}"
						var="responseForm"
						rowKey="#{responseForm.responseId}"
						reflow="true"
						>
    <p:columns value="#{getColumns()}" 
					    	var="column"
					    	headerText="#{column.header}"
					    	sortBy="#{responseForm[column.sortBy]}"
					    	>
        <h:outputText value="#{responseForm[column.property]}" />
    </p:columns>
</p:dataTable>
```

**Comment by vip30** [comment]
Any following action?

**Comment by melloware** [comment]
Related to #2360
