### ISSUE TITLE
Backport nested dialogs to version 5.2

### ISSUE THREAD

**Issue by albfan** [primefaces/primefaces#2287]
So many things changed from version 5.2 to 6.0 that is not possible to upgrade with much effort, so fixing nested dialog could be a great improvement

NOTE: I use a tabView inside first dialog, maybe it is related

## 1) Environment
- PrimeFaces version: 5.2
- Does it work on the newest released PrimeFaces version? Yes on primefaces 6.0 works
- Application server + version: Jboss EAP 6.2
- Affected browsers: All

## 2) Expected behavior

A nested modal dialog can be movable for all screen, and existing screen is grayed out
...

## 3) Actual behavior

Nested dialog opens inside iframe of former dialog and only closing with X icon works

Only body of former dialog is grayed out

## 4) Steps to reproduce

Create two dialogs one opened with other 

## 5) Sample XHTML

https://www.primefaces.org/showcase/ui/df/nested.xhtml

## 6) Sample bean

https://www.primefaces.org/showcase/ui/df/nested.xhtml

**Comment by tandraschko** [comment]
5.2 is not in development anymore - i would upgrade PF.
