### ISSUE TITLE
Add release tag to 6.1 commit

### ISSUE THREAD

**Issue by srbala** [primefaces/primefaces#2291]
Add release tag to 6.1 release commit 7daa01603e2e9b90aa7803b6c6498650de61d7c6 so that it will be available at release tab https://github.com/primefaces/primefaces/releases

Commit diff
https://github.com/primefaces/primefaces/commit/7daa01603e2e9b90aa7803b6c6498650de61d7c6

**Comment by tandraschko** [comment]
@cagataycivici Can you do this please?

**Comment by srbala** [comment]
Following command will do

```
git tag -a v6.1 7daa016 -m "6.1 Release"
git push origin v6.1
```

**Comment by cagataycivici** [comment]
Thanks!
