### ISSUE TITLE
p:tabView keeps data of old tab in DOM (6.1)

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2292]
Hi, would it be possible to remove the content of an old tab when using the following attribute combination:

cache = false  -> The Tabs should never cache something or keep old content in the DOM
dynamic = true -> Each time a Tab is clicked, the content should be fetched from server, and only the currently active Tab content should be in DOM

 ## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
Remove DOM tree of old Tab

## 3) Actual behavior
Both tabs are kept in DOM

## 5) Sample XHTML
<p:tabView scrollable="true" activeIndex="#{...}" cache="false" dynamic="true">
...
</p:tabView>

Additional question: Maybe it is possible to clear a tab via JS using onTabChange event? Any idea how to do that? 

Hope this is enough to reproduce, i will also try to make a better code example soon.

**Comment by tandraschko** [comment]
Will close it for now. No complete example, no complete describtion whats wrong, questions -> forum.
Feel free create a new issue if you have every information.
