### ISSUE TITLE
Datatable: Bug in the datatable component when it is the child of a column

### ISSUE THREAD

**Issue by gasparbarancelli** [primefaces/primefaces#2293]
**1) Environment**

PrimeFaces version: All version above 6.0.16
Application server + version: GlassFish Server Open Source Edition 4.1 (build 13) / Payara Server 4.1.1.163 #badassfish (build 215)
Affected browsers: All

**2) Expected behavior**

If the datatable is within a column, the columns of the datatable are not duplicated with empty columns.

**3) Actual behavior**

If the datatable is a child of a column of a panelgrid the columns inside the datatable are bugged, for each column added in the datatable it creates an empty one.

**4) Steps to reproduce**

```
<p:panelGrid>
        <p:row>
            <p:column>
                <p:dataTable value="#{myController.list}" var="item">
                    <p:column headerText="Text 1">
                        <h:outputText value="#{item.value1}"/>
                    </p:column>
                    <p:column headerText="Text 2">
                        <h:outputText value="#{item.value2}"/>
                    </p:column>
                    <p:column headerText="Text 3">
                        <h:outputText value="#{item.value3}"/>
                    </p:column>
                </p:dataTable>
            </p:column>
        </p:row>
    </p:panelGrid>
```

**Comment by brainlag** [comment]
Can confirm, we have the same problem.

**Comment by ghost** [comment]
Having the same issue after upgrading from 6.0.14 to 6.0.18.

**Comment by mbechler** [comment]
6.1, too. Reason is that HELPER_RENDERER is set and therefor both DataTableRenderer and ColumnRenderer.encodeEnd produce column output. Temporarily unsetting that in DataTableRenderer fixes the issue for us.

**Comment by gmlongo1** [comment]
I can confirm we have the same issue which is prohibiting us from upgrading to 6.1.  Worked fine in 5.3.

**Comment by auricgoldfinger** [comment]
I came here searching for the same issue, but a deeper search found #2337 which fixes the issue: fixed in 6.0.19 and 6.1.1 (which is not yet released)

**Comment by auricgoldfinger** [comment]
#2337

**Comment by auricgoldfinger** [comment]
#2337
