### ISSUE TITLE
OneRadio defaults to all items selected - PF 6.1

### ISSUE THREAD

**Issue by jonah-dawg** [primefaces/primefaces#2294]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 8 + Spring 4 + JSF 2.2.14
- Affected browsers:

## 2) Expected behavior
- OneRadio to function as usual
...

## 3) Actual behavior
- On page load, OneRadio components have all items selected with no ability to deselect
..

## 4) Steps to reproduce
- Create a OneRadio component under PF 6.1
.. 

## 5) Sample XHTML
` <div class="form-group">
                            <p:outputLabel for="maxMileage" value="Maximum service mileage"/>
                            <p:selectOneRadio id="maxMileage" columns="1" layout="responsive"
                                              styleClass="regularLabelsRadio" required="true"
                                              value="#{requestVMGController.selectedMaxServiceMileage }">
                                <f:selectItem itemLabel="Manufacturer Recommended"/>
                                <f:selectItem itemLabel="120,000 miles"/>
                                <f:selectItem itemLabel="150,000 miles"/>
                                <f:selectItem itemLabel="175,000 miles"/>
                                <f:selectItem itemLabel="Other"/>
                                <p:ajax render="otherMax"/>
                            </p:selectOneRadio>
                            <h:panelGroup id="otherMax">
                                <p:inputText size="20"/>
                            </h:panelGroup>
                        </div>`
..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
you miss the sample bean.

**Comment by melloware** [comment]
Hmmm can you try and figure out what is different in your example than in the Showcase?  https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml  The Showcase appears to not be defaulting all values to enabled?
