### ISSUE TITLE
Autocomplete multiple + readonly results into a crash

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2295]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 7
- Affected browsers: Chrome

## 2) Expected behavior
It should not be possible to focus the input

## 3) Actual behavior
It's possible to focus the input, and trying to search for a theme result into a crash

## 4) Steps to reproduce
See 3

## 5) Sample XHTML
```xml
<p:autoComplete id="themes" multiple="true" readonly="true" value="#{autoCompleteView.selectedThemes}" completeMethod="#{autoCompleteView.completeTheme}" />
```

## 7) Fix
In method `encodeMultipleMarkup`, add:

```java
        if(disabled) writer.writeAttribute("disabled", "disabled", "disabled");
        if(ac.isReadonly()) writer.writeAttribute("readonly", "readonly", null);
        if(ac.isRequired()) writer.writeAttribute("aria-required", "true", null); // optional
```

If the autocomplete is prefilled, it still possible to remove items. Don't know if it's a correct behavior...

**Comment by tandraschko** [comment]
If it's readonly, it should never be possible to remove items. Maybe there is another fix required.
Feel free to analyze it.

**Comment by melloware** [comment]
After looking at this I agree with @Rapster that you should not be able to remove items.  In encodeSingleMarkup it does this...
```java
        if(disabled) writer.writeAttribute("disabled", "disabled", null);
        if(ac.isReadonly()) writer.writeAttribute("readonly", "readonly", null);
        if(ac.isRequired()) writer.writeAttribute("aria-required", "true", null);
```
 But in encodeMultipleMarkup it only does this...
```java
        if(disabled) writer.writeAttribute("disabled", "disabled", "disabled");
```
So for the sake of consistency and correctness I think the fix is a simple one and a good one.
