### ISSUE TITLE
Schedule: Date Move, Day Delta Issue

### ISSUE THREAD

**Issue by mayankX** [primefaces/primefaces#2296]
Schedule Component is not calculating right Day Delta always.

I am using following configuration for my schedule

`<p:schedule value="#{schedule_setup.eventModel}" id="customSchedule" widgetVar="customSchedule"
                                timeZone="IST"
                                view="agendaWeek">
                        
                        
                        <p:ajax event="dateSelect" listener="#{schedule_setup.onDateSelect}"
                                update="schedule_detail_form"/>
                        <p:ajax event="eventSelect" listener="#{schedule_setup.onEventSelect}"
                                update="schedule_detail_form" process="@this"/>
                        <p:ajax event="eventMove" listener="#{schedule_setup.onEventMove}" update="customSchedule growl"/>
                        <p:ajax event="eventResize" listener="#{schedule_setup.onEventResize}" update="customSchedule growl"/>
                    </p:schedule>`

Here while moving schedule days in adjacent weekdays as shown in screenshot.
1) Initial State
![image](https://cloud.githubusercontent.com/assets/3822550/25251585/8e7c5996-2637-11e7-8b07-70e735ca63db.png)

2) Expected State before Drag-Drop ends
![image](https://cloud.githubusercontent.com/assets/3822550/25251617/a57f626e-2637-11e7-8ddf-5208474c51a4.png)

3) Actual State, Post Drag-Drop(Event Move)
![image](https://cloud.githubusercontent.com/assets/3822550/25251643/b59ef83a-2637-11e7-80a5-746dd2ad1ad5.png)

During debug, I found issue in Day Delta value as shown in below screenshot
![image](https://cloud.githubusercontent.com/assets/3822550/25251783/19eb7110-2638-11e7-9fb6-01a2a4696895.png)

**Comment by melloware** [comment]
Do you have a fix proposed?

**Comment by mbeedub** [comment]
+1 for this. 

It is still an issue.

**Comment by tandraschko** [comment]
Feel free to fix it an provide a PR ;)

**Comment by melloware** [comment]
Fixed with PR: https://github.com/primefaces/primefaces/pull/3991
