### ISSUE TITLE
p:selectManyMenu required="true" not working

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2298]
## 1) Environment
- PrimeFaces version: 6.1.
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Jboss EAP 6.4
- Affected browsers: ALL

## 2) Expected behavior

When selectManyMenu required="true" and no item selected that it prevents form submission.

## 3) Actual behavior

Currently required="true" has no effect other than to make the "*" next to the p:outputLabel.

## 4) Steps to reproduce

In ShowCase \src\main\webapp\ui\input\manyMenu.xhtml simply add the required and test it using the Submit button.

## 5) Sample XHTML

```xml
<p:selectManyMenu id="basic" value="#{selectManyView.selectedOptions}" required="true">
```

## 6) Sample bean

N/A

**Comment by Rapster** [comment]
Did it work with PF 6.0?

**Comment by melloware** [comment]
I tried with 6.0.18 and 6.1 but did not try with the old 6.0

**Comment by mertsincan** [comment]
I couldn't replicate this issue. Test code;
```
//XHTML
<h:form>
    <h:panelGrid id="panel" columns="2" style="margin-bottom:10px" cellpadding="5" columnClasses="label, value">
        <p:outputLabel for="basic" value="Basic:" />
        <p:selectManyMenu id="basic" value="#{selectManyView.selectedOptions}" required="true">
            <f:selectItem itemLabel="Option 1" itemValue="1" />
            <f:selectItem itemLabel="Option 2" itemValue="2" />
            <f:selectItem itemLabel="Option 3" itemValue="3" />
        </p:selectManyMenu>
    </h:panelGrid>


    <p:commandButton value="Submit" update="panel" actionListener="#{selectManyView.test}" icon="ui-icon-check" />
</h:form>

//SelectManyView.java
@ManagedBean
public class SelectManyView {
    ...

    public void test() {
        System.out.println("TEST TEST TEST");
    }
    
}
```

Test Video; https://www.dropbox.com/s/9m66akbyrcvb86l/selectManyMenu_required_test.mp4?dl=0

**Comment by melloware** [comment]
Closing as invalid.  There must be something going on with our specific code.
