### ISSUE TITLE
p:dataTable: 1st (only) rowEdit "tick save" invokes f:viewParam again (in addition to f:viewParam on @ViewScoped page)

### ISSUE THREAD

**Issue by webelcomau** [primefaces/primefaces#2299]
_There may be a good reason for the observed behavior in p:dataTable (it might not be an "issue", it is however a "concern" for me). I would appreciate any feedback or explanations._ 

I've made extremely easy for anybody to see what happens, see test app link below.

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No.
- Application server + version: Glassfish4.1.1 (includes Mojarra 2.2.12) as bundled with NetBeans IDE 8.2 (and also with Mojarra 2.3.0)
- Affected browsers: Chrome, Safari

## 2) Expected behavior

f:viewParam is only called on @ViewScoped page load, not also (again) on the first rowEdit and "tick save" of a row in a p:dataTable.

## 3) Actual behavior

f:viewParam is called both on the initial @ViewScoped page load, and on the first (only) rowEdit and "tick save" of  a given row in a row-editable p:dataTable, in which case the f:viewParam is invoked (again) before the rowEdit listener.

This can (depending on the web app) have unwanted side-effects, especially if entities are loaded within a setter for the value of a f:viewParam.

On any subsequent rowEdit and "tick save" f:viewParam is not invoked.

## 4) Steps to reproduce

There is a NetBeans IDE 8.2 mini test web app with a precise description and step-by-step instructions in a dedicated test page at:

https://github.com/webelcomau/Webel_PrimeFaces_test_p50445_dataTable_fviewParam

Please just download the [master ZIP-archive](https://github.com/webelcomau/Webel_PrimeFaces_test_p50445_dataTable_fviewParam/archive/master.zip) unzip it, and open it in NetBeans IDE 8.2.  Please ensure you have Glassfish-4.1.1 set as the server for the project. Clean and build, run, then open the clearly indicated test page from the link in the index page.

The issue expresses itself in the test app via a validation check in a row edit listener.

There is an "embedded" row-editable p:dataTable for a Link editor within a more general edit page form for an Element entity, where an Element carries one or more Link entities, and a Link has a name/title and a string for a URL.

It is seen clearly that by the time a 1st "tick save" of a row edit for a Link reaches the row edit listener that the Link URL has been over-written by reloading of its parent Element entity via `setId(Long)` because `<f:viewParam value="#{viewBean.id}"/>` has been invoked (before the row edit listener). This can be seen clearly from the glassfish server log through diagnostic logging.

A URL validator in the row edit listener also demonstrates it well. One can enter a nonsense/invalid URL string in the `p:dataTable` Link editor, and on "tick save" the first time, the validation passes, because in fact by the time the row edit listener is reached, setId(Long) via the f:viewParam has already reloaded the Link from the parent Element.

But if you edit the Link row again, a nonsense/invalid URL string is correctly caught in the row edit listener.

## 5) Sample XHTML

Please visit [/web/test_dataTable_p154868.xhtml](https://github.com/webelcomau/Webel_PrimeFaces_test_p50445_dataTable_fviewParam/blob/master/web/test/test_dataTable_p154868.xhtml)

## 6) Sample bean

Please visit [/src/java/com/webel/test/primefaces/ViewBean.java](https://github.com/webelcomau/Webel_PrimeFaces_test_p50445_dataTable_fviewParam/blob/master/src/java/com/webel/test/primefaces/ViewBean.java)

**Comment by tandraschko** [comment]
As i already stated in your forum post, we need a example to run with mvn jetty:run. I don't use NetBeans and also never install a whole GF.

**Comment by webelcomau** [comment]
Hi Thomas,

You wrote:

> As i already stated in your forum post, we need a example to run with mvn jetty:run.

I reply in awareness of your many contributions to both PrimeFaces Extensions and PrimeFaces from which I benefited, and am grateful, and also that this is the Community Issues system, not paid PRO system.

This insistence on `mvn jetty:run` is nothing short of ridiculous. The founder of PrimeFaces, Çağatay Çivici, has [previously personally congratulated me](https://github.com/primefaces/primefaces/issues/276) on preparing such convenient test cases in NetBeans, which I have done on numerous occasions over the years for both the PrimeFaces forums and these issue queues.

> I don't use NetBeans and also never install a whole GF.

Above you say "we" (meaning I presume the support team); here you say "I".

In the time it has taken you to insist you won't use it or install if you could have done it already.

I have used many IDEs and servers, I am not interested in IDE wars or web app server wars, but NetBeans IDE is the one used in the Java EE tutorials and Oracle JSF examples, and Glassfish is the reference web app implementation. 

Again: There is nothing extra TO install, [if you download the NetBeans IDE JavaEE](https://netbeans.org/downloads/) bundle it is already setup immediately to run with GlassFish ! It take up about 200M extra; I am assuming your machine has 200M space ?

And Jetty is an Eclipse community project, and for all of the wonders of Eclipse (which I also happily use for some projects), it is not even an Oracle project. Yet you are insisting on its use, and to my knowledge, it is a relatively new requirement.

I hope soon that the client for the main web app I am working on for which we uses PrimeFaces will become a paying PrimeFaces subscriber on the PrimeFaces PRO issues channel; **I can tell you straight up, being told that NetBeans IDE test projects - that would take one minute to test - are somehow not acceptable will not encourage us to become PrimeFaces PRO customers.**

In the mean-time, I might prepare a maven+jetty compatible version of my test template (with additional support beyond the official one).

I remain thankful for your work on PrimeFaces, but I think you are being simply professionally trite in this matter, and I am not convinced your assertions even reflect PrimeFaces policy.

Darren Kelly, Webel IT Australia

**Comment by webelcomau** [comment]
Click: download NetBeans JavaEE bundle.
Click: install NetBeans.
Click: download test archive bundle.
Click: unzip bundle.
Click: Open test project.
Click: Clean and Build.
Click: Run.

Now that was hard. I can see exactly why you would refuse to do it.

**Comment by tandraschko** [comment]
Use our official test-project: 1 click ;) https://github.com/primefaces/primefaces-test.git

**Comment by tandraschko** [comment]
I do not want to argue BUT
1) you dont respect our issue guidelines
2) you ignore our official test project
3) instead of helping us to improve our testproject, you completely made your own
4) jetty:run is easier as it works everywhere. You just need Maven + JDK. Thats it. No IDE, no ApplicationServer, nothing.
5) it's possible to switch JSF implementations and versions with a simple servlet container - which is required for beeing compatible (we can simple add some profiles in the test-project to support this out of the box)
6) **I** spend my freetime here. If you would like that **I** check your issues too, it's better to provide a sample based on our test project.

**Comment by webelcomau** [comment]
Firstly: I WILL develop a Maven+Jetty based version of my https://github.com/webelcomau/Webel_PrimeFaces_test_template_NetBeans_Ant test template,  one which is designed to download as an archive bundle from GitHub that is fully compliant with `mvn jetty:run` but not tonight.

You wrote:

> Use our official test-project:   https://github.com/primefaces/primefaces-test.git

What complete and utter nonsense. It does not do anything. If you had even vaguely bothered to even inspect my (currently) Ant-based test template project README, or bothered to install NetBeans and try it out, you would know the difference. 

https://github.com/webelcomau/Webel_PrimeFaces_test_template_NetBeans_Ant

Even if you bothered to try the test project with this issue you would too.

I am trying to contribute to the PrimeFaces community, but you are making it far harder than it need be. I know you are volunteering your time on this issue queue, but that does not make it ok to waste the time of other professionals, which is what you are doing.

All I wanted (on this issue queue and on the PrimeFaces forum) was a simple answer about why p:dataTable invokes f:viewParam on the first row edit.

Instead, I find myself pondering the answer to the question why somebody whose professional work I otherwise admire is acting like a complete baby, and not helping through mindless "Jetty/Eclipse facism" to encourage me to become a PrimeFace PRO customer.

**Comment by tandraschko** [comment]
I know that our sample contains pre-defined sample beans, i checked that when you posted it.
We just prepared a simple project template to provide examples in a generic way. We also had eclipse based project in the past. Not everyone is using Eclipse, or NetBeans, or Ant. Maven is the most generic way currently in the java world.

> I am trying to contribute to the PrimeFaces community, but you are making it far harder than it need be. I know you are volunteering your time on this issue queue, but that does not make it ok to waste the time of other professionals, which is what you are doing.

If you would use our guidelines (and therefore our template), then we wouldn't have a discussion now. So you are also wasting my time.

> All I wanted (on this issue queue and on the PrimeFaces forum) was a simple answer about why p:dataTable invokes f:viewParam on the first row edit.

Sorry but there is no simple answer. NOBODY knows it why something could happen without a example.

> Instead, I find myself pondering the answer to the question why somebody whose professional work I otherwise admire is acting like a complete baby, and not helping through mindless "Jetty/Eclipse facism" to encourage me to become a PrimeFace PRO customer.

It seems that you don't understand me. I'm trying to help you, to provide a example which is runnable by everyone, so that i (or other freetime developers like @melloware) are able to help you with low effort. 
We really thought about the guidelines, to solve tickets fast and easy as possible. 
I just have no time to always install other IDEs, AS, Ant and other stuff. Also it's unmaintanble to install the environment of every developer on my computer.
If i would do this for each ticket, i would solve 1/8 of the tickets...

But if you attack me like this, it would be great if you would become a PrimeFaces PRO customer.  I won't waste your time anymore and you won't waste my time anymore.
I won't comment this ticket anymore, maybe another developer will help you.
