### ISSUE TITLE
OverlayPanel: not showing if button is updated

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#2305]
## 1) Environment
- PrimeFaces version: PF6.0.18
- Does it work on the newest released PrimeFaces version? Version? No, 6.0.18
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: WF 10.0.0
- Affected browsers: All

## 2) Expected behavior
Clicking on the button should show the overly panel. the first time it is working as expected. After updating the button with an ajax request and clicking on the button again, the overlay Panel doesn't not show up.

## 3) Actual behavior
Nothing happens.

## 4) Steps to reproduce
Click on the button
(update the button with ajax)
click on the button again

## 5) Sample XHTML
<form id="myForm">
<p:commandLink id="myButton" update="myButton" >
<h:outputText value="Test me" />
<i class="icon-cmd"></i>
 </p:commandLink>

  <p:overlayPanel id="myOverlayPanel" dynamic="true" style="width:600px" widgetVar="myOverlayPanelVar" for="myButton">
               <h:outputText value="Some text here"/>
</p:overlayPanel>
</form>

**Comment by tandraschko** [comment]
Not sure if we can fix this. You have to update the overlayPanel, too.

**Comment by melloware** [comment]
as @tandraschko this is not easy to fix and its simply addressed by updating the overlay panel when you update the button.  Closing this for now unless someone submits a quality PR in the future we can re-open.
