### ISSUE TITLE
Duplicated validation message (JSF)

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#231]
Hello,
I noticed a strange bug, if one uses a level validation (EJB server) and the Client-side level, the two messages appear in the `<p:message >` , especially with `<f:validateLength >` !
Config:
- GlassFish 4.1
- Grizzly Framework 2.3.15
- Primefaces 5.2 / Primefaces 5.3-SNAPSHOT
- EclipseLink, 2.6.0.v20150309-bf26070
- Mojarra 2.2.10
- JEE 7

Schema:

```
EJB-Entity (JPA: [String] @Size(min = 1, max = 30) )
```

->

```
EJB-Session
```

->

```
ManagedBean ([ColorMB] @RequestScoped - CDI)
```

->
## JSF page with (example): 

```
<h:form>
<p:outputPanel id="global_pab">
       <p:outputLabel for="in" value="Name : " />
        <p:inputText id="in" value="#{colorMB.color.name}" required="true" validatorMessage="MessageAAAAA" >
                 <f:validateLength minimum="1" maximum="30" />
        </p:inputText>
        <p:message for="in" />
</p:outputPanel>

<p:commandButton value="OK"  ajax="true" validateClient="true"  actionListener="#{colorMB.addColor()}" id="submitbut" update="global_pab" />

</h:form>
```

---

Result : 

```
<p:message for="in" /> gives:
---------------
/!\ - MessageAAAAA
/!\ - MessageAAAAA
-------------
```

twice :/

Temporary solution: 
replace `<f:validateLength minimum="1" maximum="30" />` by `<f:validateRegex pattern=".{1,30}" />`
And result:
`/!\ - MessageAAAAA` ( Only one )

Note !
If we replace the EJB by a single Class without jpa , the bug no longer occurs .
AND:
If i  if delete `validatorMessage` from `<p:inputText>`, the messages by default give:

```
/!\ ### Message 'javax.validation.constraints.Size.message' not found ###
/!\ Name : Validation Error: Length is greater than allowable maximum of '30'
```

Web.xml contains:

```
<context-param>
        <param-name>primefaces.CLIENT_SIDE_VALIDATION</param-name>
        <param-value>true</param-value>
</context-param>
```

(Sorry for my bad English)
Thank you in advance for your reply.

**Comment by kukel** [comment]
Please use the forum first

**Comment by cagataycivici** [comment]
I couldn't understand much but you use bean validation and jsf validation at the same time, resulting in duplicate message. Please use forum first for these kinds of questions.

**Comment by RejDev** [comment]
You are right, there are two validations performed.
Thank you for your reply.
