### ISSUE TITLE
LineChart primefcaes 4.0

### ISSUE THREAD

**Issue by asmaEmad** [primefaces/primefaces#2312]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

...

## 3) Actual behavior

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by asmaEmad** [comment]
i was developing line chart using primefaces 4.0 that i checked each section of my code all are correct but the line didn't drawn in chart when i use primefaces 5.0 every thing is OK what is may problem is?

**Comment by tandraschko** [comment]
No example, It's a question -> invalid.
Use the forum for questions and provide a example there.
