### ISSUE TITLE
TextEditor: in p:inplace sets property null if form submitted when editor not visible

### ISSUE THREAD

**Issue by NagyGa1** [primefaces/primefaces#2313]
I suspect the value is still submitted despite it is not visible, and since it is not visible, the value is null.

## 1) Environment
- PrimeFaces version: 6.0.18, 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? Probably not
- Application server + version: Wildfly 10.1
- Affected browsers: All

## 2) Expected behavior

If the form is submitted while p:textEditor not visible, the field should retain its value.

## 3) Actual behavior

If the form is submitted while p:textEditor not visible, the field is set to null.

## 4) Steps to reproduce

Press button in below sample

## 5) Sample XHTML

```
<h:form>
  <p:inplace editor="true">
    <f:facet name="output">
      <h:outputText value="Some text to be able to toggle (other bug probably)" />
    </f:facet>
    <f:facet name="input">
      <p:textEditor value="#{backingBean.property}"/>
    </f:facet>
    <p:ajax event="save" listener="#{backingBean.save}"/>
  </p:inplace>

  <p:commandButton value="Press this to lose property value" action="#{backingBean.someaction}" />
</h:form>
```

Workaround: add process="@this" to the p:commandButton.

## 6) Sample bean

```java
@Named
@ViewScoped
public class BackingBean implements Serializable {

   private String property;
   // getter, setter

  public void save() {
  }

  public void someAction() {
    // here property is null if p:textEdit was not visible when button pressed
  }
}
```

**Comment by fkjaekel** [comment]
Sorry to "hijack" the issue, but I think it is related.

With PF 6.0.17 I'm facing the following situation:

If a textEditor is used inside a toggleable fieldset, when the fieldset is closed the textEditor value is set to null. Same thing happens when I use an accordion.

**Comment by Dragonsol** [comment]
I could be related to the issue I have reported previously as well: #2649 .

**Comment by jxmai** [comment]
@tandraschko This issue can be closed. It was the same bug as https://github.com/primefaces/primefaces/issues/2905

**Comment by fkjaekel** [comment]
Please backport this to 6.1 too

**Comment by jxmai** [comment]
I guess backporting to Elite version usually requires PRO user support, but it is up to PF team to decide :thinking: .

**Comment by tandraschko** [comment]
@mertsincan Would you like to backport?

**Comment by fkjaekel** [comment]
Considering that this issue was opened on April/2017 and PF 6.2 is not ready yet, could you please backport it 6.1?
