### ISSUE TITLE
SortMeta constructor fails to save value of sortFunction

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#2314]
## 1) Environment
- PrimeFaces version: 
6.1
- Does it work on the newest released PrimeFaces version? Version? 
no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
no
- Application server + version:
not relevant
- Affected browsers:
all

while browsing the source code of PF 6.1 I noticed that the constructor of the class SortMeta misses to save the value of the argument 'sortFunction' to the class member of the same name. It seems to me this might be an oversight/bug. Here is the constructor i'm talking about:

    public SortMeta(UIColumn column, String sortField, SortOrder sortOrder, MethodExpression sortFunction) {
        this.column = column;
        this.sortField = sortField;
        this.sortOrder = sortOrder;
    }

notice how the last argument is never used in the constructor anywhere

**Comment by tandraschko** [comment]
A PR would be great ;)

**Comment by melloware** [comment]
@maxdreamland please review my PR.

**Comment by ghost** [comment]
I'm sorry, but I don't know what the acronym "PR" stands for. could you elaborate on what you would like me to do?

**Comment by melloware** [comment]
Its a "Pull Request" or a patch I am submitting.  You can review it here: https://github.com/melloware/primefaces/commit/840c938ebf285f745ccb9dd01f02af8267da0860

**Comment by ghost** [comment]
looks good to me. toString() addition is a nice touch.
