### ISSUE TITLE
TreeTable: event 'page'

### ISSUE THREAD

**Issue by rengar-zz** [primefaces/primefaces#2318]
It would be nice to have event 'page' in treeTable like it's done for DataTable.

<p:ajax event="page" oncomplete="xxxxx" />

Already it exits 'sort' but don't exist 'page'

**Comment by tandraschko** [comment]
A PR would be great!

**Comment by Rapster** [comment]
From what I read "page" event is already supported in TreeTable, although the documentation is missing

**Comment by tandraschko** [comment]
Can't find it in TreeTable#BEHAVIOR_EVENT_MAPPING, so likely not implemented.

**Comment by Rapster** [comment]
Ah forgot about this, so I guess mapping and documentation are missing

**Comment by tandraschko** [comment]
Thanks ;)
