### ISSUE TITLE
Sticky toolbar with margin is fixed 'too late'

### ISSUE THREAD

**Issue by ohlsen3000** [primefaces/primefaces#2319]
## 1) Environment
- PrimeFaces version: 6.0
- Environment: Tomcat, Chrome | EDGE | IE | Firefox

## 2) Expected behavior
- Sticky panel with **a margin of n px with n > 0** is scrolled up
- The panel is expected to scroll up until its **top** hits the specified margin

## 3) Actual behavior
- Panel's top passes the specified margin, only after it reaches the top of the page it snaps to the specified margin. So for a short period the panel scrolls out of the viewport.

## 5) Sample XHTML
`<h:form id="detailForm" prependId="false">

        <div class="ui-g">
            <div class="ui-g-12 ui-md-12 ui-lg-12 ui-g-pad-top">
                something above the sticky toolbar
            </div>
        </div>

        <div class="ui-g-12 ui-md-12 ui-lg-12 ui-g-pad-top front">
            <h:panelGroup layout="block" id="stickyToolbar" style="background-color: cornsilk; height: 50px">
                my top should hit 50 px and stay there
            </h:panelGroup>
        </div>

        <div class="ui-g-12" style="height: 1000px">
            BODY goes here
        </div>

        <p:sticky target="stickyToolbar"  margin="50"/>

</h:form>`

## FIX
Line 36 of sticky.js should be like:
`if(win.scrollTop() > $this.initialState.top - $this.cfg.margin)`

**Comment by melloware** [comment]
Reviewed your fix looks good to me assuming that $this.cfg.margin is always 0 if it is not set and not "undefined".

**Comment by tandraschko** [comment]
Thanks for the PR.
