### ISSUE TITLE
TreeTable paginator don't have default currentPageReportTemplate value

### ISSUE THREAD

**Issue by vbors** [primefaces/primefaces#2323]
## 1) Environment
- PrimeFaces version: 6.1.0

## 2) Expected behavior
A treeTable with Paginator must have an default value for currentPageReportTemplate property.
In Primefaces User Guide 6.1 say:

> Also {CurrentPageReport} has it’s own template defined with currentPageReportTemplate option. 
You can use {currentPage},{totalPages},{totalRecords},{startRecord},{endRecord} keyword 
within currentPageReportTemplate. **Default is {currentPage} of{totalPages}.** Default UI is;

...

## 3) Actual behavior
Now it trow NullPointerEception if the paginatorTemplaate property contain `{CurrentPageReport}`

```
... Serious error happened!
java.lang.NullPointerException
	at org.primefaces.component.paginator.CurrentPageReportRenderer.render(CurrentPageReportRenderer.java:35)
	at org.primefaces.renderkit.DataRenderer.encodePaginatorMarkup(DataRenderer.java:93)
```
..

I think must be edited the method
`TreeTable.getCurrentPageReportTemplate()`
to be like on UIData:
```
	public java.lang.String getCurrentPageReportTemplate() {
		return (java.lang.String) getStateHelper().eval(PropertyKeys.currentPageReportTemplate, "({currentPage} of {totalPages})");
	}
```

**Comment by melloware** [comment]
I see the problem.  I will have to let @tandraschko weigh in on the fix since TreeTable is generated code from TreeTableTemplate it is not letting me override the "Pageable" interface for creating methods the way they need to be created are being autogenerated.  Not sure how to override or fix the autogeneration.

**Comment by melloware** [comment]
Looking more at this it is because it extends UITree and the others extend UIData which has the correct code.

**Comment by tandraschko** [comment]
Seems to be fixed
