### ISSUE TITLE
p:chips not respecting readOnly="true"

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2325]
Based on this forum post:  https://forum.primefaces.org/viewtopic.php?f=3&t=50659

Chips is not respecting readOnly="true" natively.   The component supports the property but was not using its values.

**Comment by matsandreassen** [comment]
Is it possible for this bugfix to be ported to 6.1?

**Comment by mertsincan** [comment]
I"ll add it to 6.1.x elite version.

**Comment by matsandreassen** [comment]
Looking forward to getting my hands on this fix. How come it's not marked as a defect?
