### ISSUE TITLE
p:chips converter is not used properly

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2326]
Based on this forum post: https://forum.primefaces.org/posting.php?mode=reply&f=3&t=50659

converter is not used properly:
"ChipsRenderer" class correctly calls the converter but then outputs the unconverted value, as string (method "encodeMarkup").
```java
...
 String tokenValue = converter != null ? converter.getAsString(context, chips, value) : String.valueOf(value);
...
 writer.writeText(String.valueOf(value), null);
...
 stringValues.add(tokenValue);
```

**Comment by matsandreassen** [comment]
Hi!

I'm attempting to use the chips component in 6.1.8 and I seem to have encountered this bug even though this issue was closed on May the 3rd.

I've looked in the code and it still seems to write the toString() value.

Was this forgotten for the 6.1-branch?

**Comment by tandraschko** [comment]
@mertsincan would you like to port this, too?

**Comment by matsandreassen** [comment]
@tandraschko Should not this be marked as a defect?
