### ISSUE TITLE
Fix for #211 no longer needed after commit e22e40a

### ISSUE THREAD

**Issue by vsingleton** [primefaces/primefaces#2332]
## 1) Environment
- PrimeFaces version:
commit e22e40a broke the PrimeExceptionHandler for portlets
5.3 was working, but 6.0+ no longer works in portlets.

- Does it work on the newest released PrimeFaces version? Version?
no.

- Does it work on the newest sources in GitHub? (Build by source -> 
https://github.com/primefaces/primefaces/wiki/Building-From-Source)
no.

- Application server + version:
Liferay 7

- Affected browsers:
all.

## 2) Expected behavior
ajax exception handling should allow partial response updates correctly.

## 3) Actual behavior
exceptions during an xhr do not result in a partial response which is parsable by core.js
so no updates to the DOM are working after commit e22e40a in portlets.

## 4) Steps to reproduce
You can follow the steps used here in this SO question:
http://stackoverflow.com/questions/43611456/primefaces-ajaxexceptionhandler-not-working-in-liferay-7
## 5) Sample XHTML
included in SO question
## 6) Sample bean
included in SO question

expect a PR in the comments, shortly.

**Comment by vsingleton** [comment]
https://github.com/primefaces/primefaces/pull/2333
This pull was tested on master (7d9dbebbd4286d473537295e0c87fed7b4459bbd).

**Comment by tandraschko** [comment]
thanks!

**Comment by vsingleton** [comment]
Thank you for all your great work on PF.
Hope you folks are doing well.
