### ISSUE TITLE
Enhancement: Terminal escape attribute needed ...

### ISSUE THREAD

**Issue by myset** [primefaces/primefaces#2334]
Hi,
Considering that new terminal component of PF 6.1 escape all tags, I propose you to introduce a new boolean attribute "escape" to the terminal with the same behavior like h:outputText escape attribute ...

Of course ... If you consider feasible.

Thank you

--
Mac OS X 10.12.4 (x86_64)
Java HotSpot(TM) 64-Bit Server VM 1.7.0_75 Oracle Corporation
Spring: 4.2.4.RELEASE
Java Servlet: 3.1
Java Server Faces: 2.2.12
PrimeFaces: 6.1
PrimeFaces Extensions: 6.1.0

**Comment by melloware** [comment]
@myset do you mind reviewing my PR for this?  https://github.com/primefaces/primefaces/pull/2342
