### ISSUE TITLE
Add 'used' and 'total' placeholders to inputTextarea

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#2338]
There have been several requests in StackOverflow for being able to display the used and total number of characters in an `p:inputTextarea` in addition to the 'remaining' characters. This is easily done by overriding a js function, but it might be worth to just add this to the component itself. 

```
PrimeFaces.widget.InputTextarea.prototype.updateCounter = function() {
    var value = this.normalizeNewlines(this.jq.val()),
    length = value.length;

    if(this.counter) {
        var remaining = this.cfg.maxlength - length;
        if(remaining < 0) {
            remaining = 0;
        }

        var remainingText = this.cfg.counterTemplate.replace('{0}', remaining).replace('{1}', length).replace('{2}', this.cfg.maxlength);

        this.counter.html(remainingText);
    }
} 
```

This would make it possible to use a counterTemplate like:

```
"This textArea has used {1} of {2} characters, so {0} are remaining"
```

**Comment by melloware** [comment]
Related to #1517 ??

**Comment by tandraschko** [comment]
Would be great if you could provide a PR!

**Comment by kukel** [comment]
Sorry, did not get any notification of this comment. Will create a pull request the coming days

**Comment by hAzUpL8** [comment]
Regards this enhencement. How to fix initial display of counter template. Now displaying "{1}/{2}" insted of "0/100" at beginig and only after typing into textArea it refreseh corectly?
