### ISSUE TITLE
p:submenu inside p:panelMenu - minor formatting issue when expanded="true"

### ISSUE THREAD

**Issue by jbrower2** [primefaces/primefaces#2339]
## 1) Environment
- PrimeFaces version: **6.1**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? **No**
- Application server + version: **All**
- Affected browsers: **All**

## 2) Expected behavior
The h3 element should have the class 'ui-corner-top', not 'ui-corner-all' when expanded="true".

## 3) Actual behavior
The h3 element has 'ui-corner-all' class regardless of the value of the 'expanded' attribute.

## 4) Steps to reproduce
Create a `<p:panelMenu/>` with a `<p:submenu expanded="true"/>` inside of it.

## 5) Sample XHTML
```xhtml
<p:panelMenu>
  <p:submenu expanded="true" label="Sub Menu">
    <p:menuitem value="Menu Item"/>
  </p:submenu>
</p:panelMenu>
```

## 6) Sample bean
Not needed for this example.

## 7) Recommended fix
In the file [PanelMenuTemplate.java on line 4](https://github.com/primefaces/primefaces/blob/master/src/main/java-templates/org/primefaces/component/panelmenu/PanelMenuTemplate.java#L4), change:
```java
public final static String ACTIVE_HEADER_CLASS = "... ui-corner-all";
```
to
```java
public final static String ACTIVE_HEADER_CLASS = "... ui-corner-top";
```

**Comment by melloware** [comment]
I will look into it and verify.

**Comment by melloware** [comment]
@mertsincan do you approve of this change?  Here in these images you can see the closed and expanded states and corner is rounded when closed but changes to square when expanded and does not return to rounded.

Initial:
![image](https://cloud.githubusercontent.com/assets/4399574/25711272/89aa84e4-30bc-11e7-8cd6-3a48dfc57a0e.png)

After expanding and closing:
![image](https://cloud.githubusercontent.com/assets/4399574/25711280/8f13c36e-30bc-11e7-8b52-de1e99bd006b.png)

**Comment by mertsincan** [comment]
Thanks a lot for your fix!

**Comment by jbrower2** [comment]
Sure thing; thanks a lot for your quick response!
