### ISSUE TITLE
MarkerClusterer in google maps

### ISSUE THREAD

**Issue by tfe2012** [primefaces/primefaces#2340]
How use MarkerClusterer on <p:gmap> ? 

I mean [this tool](https://github.com/googlemaps/js-marker-clusterer)

**Comment by tandraschko** [comment]
questions -> forum

**Comment by tfe2012** [comment]
You don't implement this function gmap in primefaces, 

It's a task to improve gmap

**Comment by mertsincan** [comment]
Please try the following sample project; 
https://www.dropbox.com/s/sneqx07rshsgavd/markerClusterer_test.rar?dl=0

Test Video;
https://www.dropbox.com/s/tkzomjitlpxhidd/markerClusterer_test_on_Gmap.mp4?dl=0

**Comment by tfe2012** [comment]
Thx a lot:)
