### ISSUE TITLE
Programmatic Menu (p:menu) java.lang.ClassCastException when toggleable=true

### ISSUE THREAD

**Issue by zortx233** [primefaces/primefaces#2344]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No. Works in 5.3.0
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
Menu should render
...

## 3) Actual behavior
Exception is thrown
```
java.lang.ClassCastException: org.primefaces.model.menu.DefaultMenuItem cannot be cast to javax.faces.component.UIComponent
	at org.primefaces.component.menu.MenuRenderer.encodeElements(MenuRenderer.java:93)
```

..

## 4) Steps to reproduce
Create a Programmatic menu using p:menu, set toggleable = true, and set model to a MenuModel defined in the controller
.. 

## 5) Sample XHTML
You can use PrimeFaces Showcase:
https://www.primefaces.org/showcase/ui/menu/menu.xhtml

But change line 36 from:
`<p:menu model="#{menuView.model}" />`
to
`<p:menu toggleable="true" model="#{menuView.model}" />`

..

## 6) Sample bean
Use PrimeFaces showcase MenuView.java
https://www.primefaces.org/showcase/ui/menu/menu.xhtml
..

The offending line in MenuRenderer is:
line 93:
`UIComponent parent = ((UIComponent)menuItem).getParent();`

From source history, it was introduced by issue 1485:
https://github.com/primefaces/primefaces/issues/1485

**Comment by melloware** [comment]
Line 92 robably needs to change to something like this so it only checks for submenu if it knows the parent is a UIComponent.
```java
if(toggleable && menuItem instanceof UIComponent) {
        ...
}
```

**Comment by zortx233** [comment]
Thanks. I was thinking the same thing for the fix.
