### ISSUE TITLE
Programmatic Menu - submenus don't expand and collapse when toggleable="true"

### ISSUE THREAD

**Issue by zortx233** [primefaces/primefaces#2351]
This is a continuation of the issue found in #2344. While the ClassCastException no longer occurs, the actual functionality of toggling a programmatic menu's submenu does not work.

## 1) Environment
- PrimeFaces version: latest - 6.1.x, after applying the fix in #2347 
- Does it work on the newest released PrimeFaces version? No. Version? Works in 5.3.0
- Does it work on the newest sources in GitHub? No (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
When toggling a submenu for a programmatic menu, the menu items should collapse and expand.
...

## 3) Actual behavior
MenuItems under a submenu do not toggle when using a menuModel
..

## 4) Steps to reproduce
Create a Programmatic menu using p:menu, set toggleable = true, and set model to a MenuModel defined in the controller
Also make sure you have the fix for issue #2344, #2347 loaded.
Then try toggling your menu.
Previously you would get a ClassCastException just loading the page, which commit #2347 fixed, however now the toggle doesn't work.

.. 

## 5) Sample XHTML
You can use PrimeFaces Showcase:
https://www.primefaces.org/showcase/ui/menu/menu.xhtml

But change line 36 from:
`<p:menu model="#{menuView.model}" />`
to
`<p:menu toggleable="true" model="#{menuView.model}" />`

..

## 6) Sample bean
Use PrimeFaces showcase MenuView.java
https://www.primefaces.org/showcase/ui/menu/menu.xhtml
..

## 7) More Investigation
I believe this is because in #1485, the menu.js was also modified to only hide or show elements with the .ui-submenu-child class.
Menu.js Line 779:  `items.filter('.ui-submenu-child').hide();`
Menu.js Line 793: `items.filter('.ui-submenu-child').show();`

Because the .ui-submenu-child is not being added to the menuItem when using a menu model, none of the menuItems are being found to show or hide.

I'm not familiar enough with PrimeFaces code to suggest a resolution that doesn't break the issue #1485 fixed, so I would welcome suggestions.

**Comment by radzionkow** [comment]
The problem is fix for issue #1485
`MenuItem` is not an instance of `UIComponent` so code:
```java
if(toggleable) {
    UIComponent parent = ((UIComponent)menuItem).getParent();`
    containerStyleClass = (parent instanceof Submenu) ? containerStyleClass + " " + Menu.SUBMENU_CHILD_CLASS: containerStyleClass;
}
```
wont work.

You can fix it by adding boolean parameter to `encodeElements` method

```java
protected void encodeElements(FacesContext context, Menu menu, List<MenuElement> elements, boolean sub) throws IOException {
...
    if (toggleable && sub) {
        containerStyleClass = containerStyleClass + " " + Menu.SUBMENU_CHILD_CLASS;
    }
...
```
and then:
1)  in `encodeMarkup` method:
```java
encodeElements(context, menu, submenu.getElements(), false);
```
2) in `encodeSubmenu`
```java
encodeElements(context, menu, submenu.getElements(), true);
```
That should fix the issue without breaking #1485.

**Comment by melloware** [comment]
Doesn't this fix already fix the issue?  https://github.com/primefaces/primefaces/issues/2344

Can you try this with 6.2-SNAPSHOT built from source?

**Comment by melloware** [comment]
Ahh I see.  Let me fix.

**Comment by melloware** [comment]
Submitted PR.  You are right this is the most bulletproof way to fix this issue for good.
