### ISSUE TITLE
TriStateCheckboxRenderer: missing styleClass "ui-state-error" for failed validation

### ISSUE THREAD

**Issue by 4a6f42** [primefaces/primefaces#2352]
## 1) Environment
- PrimeFaces version:
6.1

## 2) Expected behavior
TriStateCheckbox.setValid(false) results in class "ui-state-error" on rendered component

## 3) Actual behavior
valid flag is ignored

Comparing SelectBooleanCheckboxRenderer and TriStateCheckboxRenderer the latter is missing the line concerning the validation styleClass. There might be a reason for that, but I can only consider it a bug.

**Comment by melloware** [comment]
I agree and just submitted a PR if you want to review it.
