### ISSUE TITLE
PrimeFaces Community Downloads

### ISSUE THREAD

**Issue by ducky21** [primefaces/primefaces#2354]
## 1) Community Downloads
- PrimeFaces version: 6.1
- Download of primefaces-6.1-sources.jar goes to a dead link.

## 2) Expected behavior
Download start
...

## 3) Actual behavior
404 error
..

## 4) Steps to reproduce
Click the community downloads link to download primefaces-6.1-sources.jar
.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
@mertsincan The link is wrong, would you please fix it?

**Comment by onursenture** [comment]
Fixed.
