### ISSUE TITLE
Name of icon badly managed in  <p: ​​menuitem>  with <pa:menu> (Barcelona theme)

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#2355]
Hello dear community,

## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Payara Server 171.1
- Affected browsers : Firefox / Chrome
- Font : font-awesome-4.7.0
- theme : Barcelona

## 2) Expected behavior
   
  Have a single icon

## 3) Actual behavior

When I specify the icon "person-add" or "personadd"  in the <p: ​​menuitem> tag, it is considered as two icons. ( person + add )

This problem occurs only in <pa:menu> of Barcelona theme.

## 4) Sample XHTML
<pa:tab icon="people" title="People">
                    <pa:menu widgetVar="me2">
                        <p:menuitem id="adm_add_dist" value="New person" icon="person-add" outcome="/test.xhtml" />
                    </pa:menu>
 </pa:tab>

Thanks a lot for your help.

**Comment by tandraschko** [comment]
You example is invalid - please provide also your person-add css.

**Comment by RejDev** [comment]
@tandraschko : Thank you for taking the time to answer me.
"person-add" It is an icon in the list of icons proposed with the theme Barcelona
https://www.primefaces.org/barcelona/utils.xhtml

**Comment by RejDev** [comment]
This problem occurs only in <pa:menu> of Barcelona theme.
I found a temporary solution, It is necessary to use this "person_add " instead of "person-add", or the code "& #xE7FE;". 
Note, it is impossible to use the  font-awesome in <pa:menu>.

**Comment by melloware** [comment]
I would report this to the Barcelona team...

https://forum.primefaces.org/viewforum.php?f=53

And their GitHub issues page here:
https://github.com/primefaces/barcelona/issues/
