### ISSUE TITLE
SelectOneMenu: keyboard navigation not standard

### ISSUE THREAD

**Issue by Josh68** [primefaces/primefaces#2356]
## 1) Environment
- PrimeFaces version: **6.0**
- Does it work on the newest released PrimeFaces version? Version? **No, not in the demo**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **Have not tried**
- Application server + version: **Websphere 7 (latest)**
- Affected browsers: **All tested (Chrome, FF, IE11)**

## 2) Expected behavior
Each keypress of a letter should cycle through all the options that start with that letter. See native select menu behavior.

## 3) Actual behavior
One keypress of a letter goes to the first option that starts with that letter. Subsequent keypresses of the same letter do not cycle through all options that start with that letter.

## 4) Steps to reproduce
I have a select menu of state abbreviations, for example, and typing "O" just takes me to "OH," but not "OK" or "OR"

## 5) Sample XHTML
```
<p:selectOneMenu id="state#{locId}" value="#{searchbean.state}" autoWidth="false">
    <f:selectItem itemLabel="- State -" itemValue="" />
    <f:selectItems value="#{searchbean.medstates}" />
</p:selectOneMenu>
```

## 6) Sample bean
```
public List<SelectItem> getMedstates() {
        if (medicalstates.isEmpty()) {
            String[] med = {
                "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
                "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
                "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
                "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
                "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
            };
            for (String c : med) {
                medicalstates.add(new SelectItem(c, c));
            }
        }
        return medicalstates;
    }
```

**Comment by melloware** [comment]
I have observed the same behavior.  From first glance I don't see an easy fix but I am definitely not an expert in this component.

**Comment by avinashmoram** [comment]
Do we know when this will be fixed? This is an accessibility issue in our application now.

**Comment by avinashmoram** [comment]
It is interesting that this is marked as new feature, because the generic html_select already works; here is a [fiddle](https://jsfiddle.net/amoram/b2b740uk/1/)

**Comment by ianfranco** [comment]
I try the demo at http://primefaces.org/showcase/ui/input/oneMenu.xhtml in windows xp and in windows 7 and it works, but in windows 10 (any browser) it does not, so ...

**Comment by melloware** [comment]
Hmm I don’t know why it would be OS specific as the browser is all that should matter?

**Comment by ghost** [comment]
May I know the release plan for this enhancement because we are facing the same kind of the accessibility issue in many areas of our application?

**Comment by tandraschko** [comment]
There are currently no plans, otherwise we would asign a milestone here.
But you can always sponsor it via PrimeFaces PRO.

**Comment by Bill57** [comment]
I am surprised that it would be tagged an enhancement given that the feature used to work. Aside from paying money, how do you get a milestone assigned to an issue?

**Comment by tandraschko** [comment]
if you check all OS+all browsers, implement by yourself and provide a PR ;)

**Comment by melloware** [comment]
OK I submitted a PR that I have tested pretty thoroughly but wouldn't mind someone else checking it out and code reviewing or testing it.  https://github.com/primefaces/primefaces/pull/3318
