### ISSUE TITLE
Datatable: Sorting dropdown behaves wrong with unsortable columns

### ISSUE THREAD

**Issue by appldo** [primefaces/primefaces#2360]
## 1) Environment
Primefaces 6.1

## 2) Expected behavior
Datatable sorting works in reflow mode

## 3) Actual behavior
Datatable in mobile reflow mode. If the first column is not sortable the sort dropdown does not behave correctly. When you click on the last entry another one is selected 

..

## 4) Steps to reproduce
Execute the project below with mvn jetty:run

[primefaces-test-datatable-sort-reflow.zip](https://github.com/primefaces/primefaces/files/996800/primefaces-test-datatable-sort-reflow.zip)

## 5) Sample XHTML

...just the showcase sort demo with reflow and the first column unsortable.

   ```
 <p:dataTable var="car" value="#{dtSortView.cars1}" reflow="true"
                       >
            <f:facet name="header">
                Single Column Sort
            </f:facet>

            <p:column headerText="Id" sortable="false" >
                <h:outputText value="#{car.id}" />
            </p:column>

            <p:column headerText="Id2" sortBy="#{car.id}" sortable="true" >
                <h:outputText value="#{car.id}" />
            </p:column>

            <p:column headerText="Year" sortBy="#{car.year}" sortable="true">
                <h:outputText value="#{car.year}" />
            </p:column>

            <p:column headerText="Brand" sortBy="#{car.brand}" sortable="true">
                <h:outputText value="#{car.brand}" />
            </p:column>

            <p:column headerText="Color" sortBy="#{car.color}" sortable="true">
                <h:outputText value="#{car.color}" />
            </p:column>
        </p:dataTable>

```
## 6) Sample bean

see 4.)

..

**Comment by melloware** [comment]
Related to #2286

**Comment by pfumi** [comment]
This bug still exists with PrimeFaces 8.0.3. I fixed it in our project (we use PrimeFaces 8.0.3) with the following change in the updateReflowDD function:
```
updateReflowDD: function(columnHeader, sortOrder) {
        if(this.reflowDD && this.cfg.reflow) {
            var options = this.reflowDD.children('option'),
            orderIndex = sortOrder > 0 ? 0 : 1;

            options.filter(':selected').prop('selected', false);
            //options.filter('[value="' + $.escapeSelector(columnHeader.index() + '_' + orderIndex) + '"]').prop('selected', true);
            options.filter(':contains("' + $.escapeSelector(columnHeader.text()) + '")').filter('[value$="_' + orderIndex + '"]').prop("selected", true);
            
        }
}
```

The commented out line with columnHeader.index() has the wrong index (only if the table has columns that are not sortable). So our solution is to search by text and filter then by the order index.

**Comment by melloware** [comment]
@pfumi can you please leave the same comment in https://github.com/primefaces/primefaces/issues/2286 which is the open ticket tracking this issue.

**Comment by melloware** [comment]
@pfumi Thanks let me review what you did.

**Comment by melloware** [comment]
I have verified your fix works using the provided test project and submitted a PR.

**Comment by pfumi** [comment]
Sorry I have found an issue with this solution. If there is a similar column (just use the provided test and change "Brand" into "Brand Year") and then sort by Year or Brand Year. With ":contains" it would find both, and selection is again wrong.
This line for the last line should fix it
```
				options.filter(function(idx, element) {
					return element.text.startsWith($.escapeSelector(columnHeader.text())) && element.value.endsWith("_" + orderIndex);
				}).prop("selected", true);
```

**Comment by melloware** [comment]
Please review: https://github.com/primefaces/primefaces/pull/6193/files

**Comment by pfumi** [comment]
$.escapeSelector(columnHeader.text()) is missing, then it's fine. Is there a change to get this in PrimeFaces 8.0.4?
Thank you for the quick work! :)

**Comment by melloware** [comment]
OK pushed a new commit please review: https://github.com/primefaces/primefaces/pull/6193/files

**Comment by melloware** [comment]
You don't need to wait for 8.0.4 just add this to your application JS file which loads after PrimeFaces.
```javascript
PrimeFaces.widget.DataTable.prototype.updateReflowDD = function(columnHeader, sortOrder) {
    if (this.reflowDD && this.cfg.reflow) {
        var options = this.reflowDD.children('option'),
            orderIndex = sortOrder > 0 ? 0 : 1;

        options.filter(':selected').prop('selected', false);
        options.filter(function(idx, element) {
            var header = $.escapeSelector(columnHeader.text());
            return element.text.startsWith(header) && element.value.endsWith("_" + orderIndex);
        }).prop("selected", true);
    }
};
```

**Comment by pfumi** [comment]
I had to escape the element.text too. Last edit, sorry
```
            options.filter(function(idx, element) {
                var header = $.escapeSelector(columnHeader.text());
                return $.escapeSelector(element.text).startsWith(header) && element.value.endsWith("_" + orderIndex);
            }).prop("selected", true);
```
I know, just want to remove the code in our application if its fixed in 8.0.4 or future release

Or remove the escapes, if its not needed

**Comment by pfumi** [comment]
Works, thanks!

**Comment by melloware** [comment]
OK I pushed a commit escaping the element text too.

**Comment by melloware** [comment]
@pfumi I made even more changes to make it work with dynamic columns as well: https://github.com/primefaces/primefaces/pull/6202/files

**Comment by pfumi** [comment]
@melloware perfect thanks 👍 
Just a bit of refactoring, you could replace this
```
            options.filter(':selected').prop('selected', false);
            options.filter(function(idx, element) {
                var optionText = $.escapeSelector(element.text);
                return optionText.startsWith(header) && element.value.endsWith("_" + orderIndex);
            }).prop("selected", true);
```
with
```
        options.each(function() {
            var optionText = $.escapeSelector(this.text);
            this.selected = optionText.startsWith(header) && this.value.endsWith("_" + orderIndex);
        });
```
if you want :)

**Comment by melloware** [comment]
Interesting refactoring let me try that.
