### ISSUE TITLE
Input Number Validation Issue

### ISSUE THREAD

**Issue by mayankX** [primefaces/primefaces#2361]
<img width="623" alt="screen shot 2017-05-13 at 1 22 29 am" src="https://cloud.githubusercontent.com/assets/3822550/26014560/b5939360-377a-11e7-80f5-2e569d30b02a.png">

`<p:outputLabel value="Amount" for="payment_amount_textfield"/>
  <p:inputNumber decimalPlaces="0" symbol="₹ " id="payment_amount_textfield" inputStyle="width: 100%"
      required="true" requiredMessage="Amount is Required" label="Amount"
      value="#{create_admission.selectedChequeDetail.amount}">
       <p:ajax event="blur"/>
 </p:inputNumber>`

Primefaces Validation Fails for Valid case, in case of inputNumber.

**Comment by tandraschko** [comment]
You completely ignored our issue template and therefore many infos are missing -> invalid.
