### ISSUE TITLE
Dynamic overlaypanel display outside of viewport

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2364]
## 1) Environment
- Current Showcase: PrimeFaces-6.1-SNAPSHOT on Mojarra-2.2.8.

## 2) Expected behavior

Overlaypanel should always try to display itself in visible viewport. If above the element is enough space it shall use this space instead below the element.

## 3) Actual behavior

Dynamic overlaypanel does not displays itself in visible viewport. 

## 4) Steps to reproduce

Decrease viewport size in showcase and click at dynamic button

![overlaypanel-dynamic-outside](https://cloud.githubusercontent.com/assets/5265550/26054585/70b1fe9a-396d-11e7-90d9-3ef69cf697f1.jpg)

**Comment by tandraschko** [comment]
Would be great if you could provide a PR!

**Comment by mesche** [comment]
Please fix this bug/problem. It's a strange behavior for the user

**Comment by jxmai** [comment]
AFAIK,  I think we should at least check the height and width to make sure they don't go out of bound before showing the dialog, and recover the width and height when there is enough room in the viewport.

Let's say:

![image](https://user-images.githubusercontent.com/10467831/31915015-8cb193a2-b812-11e7-8737-9c34a7d4e58f.png)


and 


![image](https://user-images.githubusercontent.com/10467831/31915024-9548ee7a-b812-11e7-9cdf-556f34638a8e.png)

I thought I could make overlay panel responsive but that's not an easy thing to do, but at least this issue can be solved.

**Comment by melloware** [comment]
@tandraschko I believe you have fixed this. I just tested the example above in the showcase and it now works fine so I am closing this issue.
