### ISSUE TITLE
SelectOneMenu has ui-state-disabled css class(you can still select) when f:selectItem has empty label

### ISSUE THREAD

**Issue by fkocijan** [primefaces/primefaces#2366]
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: tomcat 8
- Affected browsers: all

## 2) Expected behavior
The selectOneMenu should not be gray as if it is disabled when selectItem has empty string as label
...

## 3) Actual behavior
The oneMenu has the ui-state-disabled css class added when label is empty
..

## 4) Steps to reproduce
just add <f:selectItem itemLabel="" itemValue=""/> as a child of selectOneMenu
.. 

## 5) Sample XHTML
<p:selectOneMenu>
<f:selectItem itemLabel="" itemValue=""/>
</p:selectOneMenu>
..

## 6) Sample bean
-
..

**Comment by melloware** [comment]
I think this was maybe introduced with #2191. @fkocijan  Can you review?

**Comment by fkocijan** [comment]
yep, that was my thought too, should be a bug then

**Comment by melloware** [comment]
A quick workaround is to add a label like "[Select One]".

<f:selectItem itemLabel="[Select One]" itemValue=""/>

**Comment by melloware** [comment]
@fkocijan  Sorry this took me so long was finally able to get a chance to look at it and fix it.

**Comment by alexeev** [comment]
Is there any chance to backport the fix to the 6.1 branch?

**Comment by melloware** [comment]
@mertsincan can you backport this to 6.1 Elite?

**Comment by jajajaja** [comment]
@melloware In which branch could I make a pull-request for 6.1?

**Comment by melloware** [comment]
You can’t. The 6.1 elite releases are controlled by @mertsincan so it’s as his discretion what gets merged or if you have a PRO account you can request it there.

**Comment by mertsincan** [comment]
Added to 6.1.10.
