### ISSUE TITLE
p:tooltip flickers if it covers the element spawning it

### ISSUE THREAD

**Issue by j-be** [primefaces/primefaces#2370]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) - **Not yet tested**
- Application server + version: Tomcat 8.5.11 with MyFaces 2.2.12 and PrimeFaces 6.1
- Affected browsers: manly Firefox 53, Chrome is better but not perfect either

## 2) Expected behavior

When an item (let's say an image) spawns a tooltip, and the tooltip is large enough to cover said icon, the tooltip stays on the screen until the mouse is moved away from the (covered, yet still present) icon.

## 3) Actual behavior

When an item (let's say an image) spawns a tooltip, and the tooltip is large enough to cover said item, the tooltip...:

- ... starts disappearing and reappearing in Firefox (basically the tooltip itself disables the "hover" property of the item, which let to the tooltip being there in the first place)
- ... appears and stays there until you move the mouse in Chrome. As long as you move the mouse the behavior is the same as described for Firefox.

## 4) Steps to reproduce

1. Go to https://www.primefaces.org/showcase/ui/overlay/tooltip/tooltipOptions.xhtml
1. Make your browser window as narrow (i.e. reduce width) as possible
1. Hover "Clip/Explode Effects"

## 5) Sample XHTML

https://www.primefaces.org/showcase/ui/overlay/tooltip/tooltipOptions.xhtml

## 6) Sample bean

Not needed.

## 7) Proposed fix

Add the following CSS porperty:
`.ui-tooltip {
    pointer-events: none;
}`

It fixes the problem on my side and seems to be widely supported (see https://caniuse.com/#search=pointer-events).

**Comment by melloware** [comment]
I have submitted a PR with your fix and I agree with it. @mertsincan do you want to weigh in on this CSS fix?
