### ISSUE TITLE
Deletion text by Delete buton in filter from advanced selectonemenu not working same as deletion by Backspace button

### ISSUE THREAD

**Issue by dE57R0YER** [primefaces/primefaces#2371]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: WebLogic 12c
- Affected browsers: Firefox and Chrome

## 2) Expected behavior
Deletion by button Delete causes the same behavior as button Backspace.

## 3) Actual behavior
Deletion any character of filter text content by Backspace button will get new refreshed dropdown. Also deletion of whole filter content by Backspace will take list in original state. But when you try to delete it by Delete button nothing happens. Deletion by Delete button not trigger, dropdown list just staying in last state which was taken before you press Delete. Blur or ItemSelect events can't reset selectonemenu to normal state. Only typing new query in filter or deleting current filter content by button Backspace are helpful.

## 4) Steps to reproduce
1. Type some text in filter.
2. Select the text and press Delete or try to delete several characters by repeatedly pressing Delete so that you are sure that you will get the dropdown list in the new state.
3. Nothing happens.

## 5) Sample XHTML
There is no sense to bringing code sample from my project when there is a good example from the site of the Primefaces. Look at advanced SelectOneMenu.
https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

## 6) Sample bean
Not needed.

**Comment by melloware** [comment]
I have verified the issue in the showcase and confirmed the PR fixes it.
