### ISSUE TITLE
InputTextarea + autocomplete + autoResize - does not resizes on selection

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2374]
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Glassfish 4.1.1. Mojarra 2.2.9
- Affected browsers: Firefox

## 2) Expected behavior

When selecting an item from the autocomplete menu and autoResize is enabled, the area should automatically resize.

## 3) Actual behavior

When selecting an item from the autocomplete menu and autoResize is enabled, the area is not resized.

## 4) Steps to reproduce

Create a inputTextarea with completeMethod and a single row. Add a suggestions that is 3 rows wide by clicking on it.

..

**Comment by tandraschko** [comment]
If you don't provide a example, it will be closed as invalid.
