### ISSUE TITLE
Upgrade jQuery to 2.2.4

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2375]

**Comment by melloware** [comment]
@mertsincan this Jquery Upgrade ticket from @tandraschko was already out there.  Can it be closed?   #2233

**Comment by erickdeoliveiraleal** [comment]
Note for PF team:

they renamed the AJAX "complete" callback to "always" (jquery/jquery@fd80f59) - this will break oncomplete

**Comment by mertsincan** [comment]
I couldn't replicate it. I tested showcase demo pages with Jquery 2.2.4. They work fine. Could you please attach a sample code for us to replicate?

**Comment by kukel** [comment]
I personally think  (as most likely do **all users of the community version**) this justifies a 6.1-SR (security release) or a 6.2 or some other solution. If not, PrimeFaces gives out a _**very bad**_ signal to these users.

**Comment by andrei-ivanov** [comment]
@kukel Responsible behavior is required only for the disclosure of security holes, not for providing the fix to the audience

**Comment by nicymike** [comment]
Has this change been made because of the "XSS vulnerability" in jQuery? Since this fix has been removed from 2.2.x, too: [jquery#2432 (comment)](https://github.com/jquery/jquery/issues/2432#issuecomment-199098662)
