### ISSUE TITLE
Scrollable TabView: scroll buttons not visible after page refresh

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#2376]
1) Environment

PrimeFaces version:primefaces-6.0.16
Does it work on the newest released PrimeFaces version? No
Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
Application server + version: Wildfly 10.0.0
Affected browsers: all
2) Expected behavior

Scroll buttons should be visible even after page refresh. 

3) Actual behavior

Scroll buttons not visible even after page refresh/reload.

4) Steps to reproduce

load page
reload/refresh page

Important: in order to reproduce the problem the space needed by tabs needs to exceed the window's width (but not must not bee "too much" width)

[tabView.zip](https://github.com/primefaces/primefaces/files/1008201/tabView.zip)

..

5) Sample XHTML

```
<h:form>
      <p:tabView value="#{tabbedView.cars}" var="item" scrollable="true" activeIndex="#{tabbedView.activeIndex}" dynamic="true">
       
          <p:tab title="#{item}" closable="true">

          </p:tab>
      </p:tabView>
</h:form>
```

6) Sample bean
```

@managedbean
@viewscoped
public class TabbedView {

private int activeIndex;

private List<String> cars;

@PostConstruct
public void init() {
    cars = new ArrayList<String>();
        cars.add("Fiat (some long description)");
        cars.add("BMW (some long description)");
        cars.add("Ford (some long description)");
        cars.add("Volvo (some long description)");
        cars.add("Jaguar (some long description)");

        cars.add("Another Fiat (some long description)");
        cars.add("Another BMW (some long description)");
        cars.add("Another Ford (some long description)");
        cars.add("Another Volvo (some long description)");
        cars.add("Another Jaguar (some long description)");
}


public int getActiveIndex() {
    return activeIndex;
}

public void setActiveIndex(int activeIndex) {
    this.activeIndex = activeIndex;
}

public List<String> getCars() {
    return cars;
}

public void setCars(List<String> cars) {
    this.cars = cars;
}
```

**Comment by cnsgithub** [comment]
I wasn't really able to reproduce it unfortunately. But i agree that this component doesn't react as it should in some other circumstances as well. Assume you load the browser with a large size. Now you resize the screen to a smaller one, and the tabs stay unscrollable even if the width is now less than the required one. So the scroll-buttons should display.

A workaround is to call this on resize / reload

```
$(".ui-tabs-navscroller-btn").show();
```

Or just overwrite the class to have them always visible

![scr2](https://cloud.githubusercontent.com/assets/13161711/26581189/b09fc774-453b-11e7-9dc8-32ce81b87dea.png)

**Comment by marroyons** [comment]
Good job cracks.

**Comment by tandraschko** [comment]
Added resize support, looks good for me now.
