### ISSUE TITLE
p:poll unexpected behaviour 

### ISSUE THREAD

**Issue by junaidbinsarfraz** [primefaces/primefaces#2380]
Read [this question and comments ](http://stackoverflow.com/questions/44066753/ppolls-instance-not-removed-after-server-stopped) first before proceed

Possible such behaviour appeared because poll continue sending ajax to server even if the server is down. After server back to production it detected incoming ajax requests, but it can't restore view with that component because of previous downtime. 

Don't you think that its a primefaces bug ? Like if server is stopped for maintenance then it is restarted. So the problem will be that unregistered clients/polls still sending the wrong requests to the server again and again. I think primefaces should assign unique ids to server and client sides' poll-instances so that if such case occurs then server and client stop communication rather keep the server busy !

**Comment by tandraschko** [comment]
-1
If the server is back, a ExceptionHandler will redirect to viewExpired.

**Comment by melloware** [comment]
Agreed and you can map your Ajax Exception Handler to do whatever you want.  Redirect to a Static page "site is down" for example.
