### ISSUE TITLE
p:textEditor does not support p:ajax

### ISSUE THREAD

**Issue by brainlag** [primefaces/primefaces#2383]
## 1) Environment
- PrimeFaces version: 
  6.1.0
- Does it work on the newest released PrimeFaces version? Version?  
  no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) 
  no
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
p:ajax inside p:textEditor works like p:inputTextarea

## 3) Actual behavior
page does not even render because javax.faces.component.behavior.ClientBehaviorHolder is not implemented

## 4) Steps to reproduce
Just add a p:ajax tag inside a p:textEditor tag

Since p:textEditor uses contenteditable instead of a input field there where some shortcuts made by not implementing p:ajax support. But nevertheless, people want to replace textareas with it and expect it to behave like a texarea (p:inputTextArea).

I tried to resolve this problem myself and send a PR but I don't know how to hook up the javascripts events with p:ajax. Some guidance would be required.

**Comment by tandraschko** [comment]
Just compare with p:editor. I think there is something like #encodeClientBehaviors available in the renderers.

**Comment by brainlag** [comment]
Nope. p:editor doesn't support p:ajax either.

**Comment by tandraschko** [comment]
then compare with inputText or something ;)

**Comment by Rapster** [comment]
@brainlag and feel free to provide a PR ;)
