### ISSUE TITLE
Sync source of jqplot

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#2384]
There is a source missmatch between charts.js and jqplot. In our case the EnhancedLegendRenderer produces wrong spacings in the legend table which do not occur with the official jqplot files (i went back till 2010 in the jqplot repository and I can't find that wrong line).

The wrong line is charts.js L14739. Maybe there are some more missmatches.

Please sync the charts.js with the working 1.0.8 (as 1.0.9 couldn't be used) release of jqplot.

**Comment by tandraschko** [comment]
Don't think we can just sync it - AFAIR mert applied some fixes in our version.

**Comment by tandraschko** [comment]
Will close it.
We should upgrade to 1.0.9 in future but someone needs to fix that bug that occured after the upgrade.
