### ISSUE TITLE
DataTable: Row of FROZEN and UNFROZEN columns are aligned until I select a row

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#2388]
I have defined 1 FROZEN column like described in issue [https://github.com/primefaces/primefaces/issues/1155](https://github.com/primefaces/primefaces/issues/1155)

This work fine until I click on a row WHEN LAST ROW is displayed. Under this condition the alignment between FROZEN rows and UNFRONZEN rows are not more respected.

If I click on a row when LAST ROW is not visible (the vertical scrollbar is not at bottom) I have no problem !

I think that the vertical shift of rows in frozen part corresponds to the height of horizontal scroll bar visible at bottom of DataTable !

1) Environment
- PrimeFaces version: 6.1.1
- Does it work on the newest released PrimeFaces version? NO 
- Affected browsers: CHROME

2) Expected behavior

I expect that when I click on a cell in UNFROZEN part the alignment is kept.

3) Actual behavior

Just after clicking on a cell inUNFROZEN part, the alignment is broken

4) Steps to reproduce

a. Create a table with FROZEN columns (only the first column is frozen)
b. put an image in a cell in UNFRONZEN part so that row's height is greater in UNFROZEN part.
c. use .ui-datatable-frozenlayout-left td (and right) to fix the same height for FROZEN and UNFROZEN parts.
d. display the page with the table
e. select a row when last row is visible

5) Sample

It was interesting to have a sample of this in Primefaces DateTable part in adding a submenu FROZEN !
If somebody of Primefaces to that, it would be interesting to have 2 distinct heights !

I have attached 2 PrintScreen, one just before clicking and the other just after having clicked.
![euc1 ctc list postlabelling -tire labelling grade assignment tlga - google _2017-05-24_15-36-32](https://cloud.githubusercontent.com/assets/16349543/26406001/4669deec-4097-11e7-9efc-6f77192d5709.png)
![euc1 ctc list postlabelling -tire labelling grade assignment tlga - google _2017-05-24_15-36-52](https://cloud.githubusercontent.com/assets/16349543/26406017/4f5dc9fa-4097-11e7-9e69-4aec3c5401c3.png)

**Comment by cnsgithub** [comment]
It is the third issue which basically describes the same thing: The frozen column feature is basically totally bugged. Misaligned header, misaligned rows.. 

Is there any hope that there might be a fix which doesn't rely on JS / CSS 'hacks'? Probably a PRO user might have to ask about this.. 

#1155
#644

I will again attach the test-code to reproduce _ALL_ issues related to this feature which can't be easily fixed by just applying CSS (at least as far as my knowledge goes). Of course by that i mean without hardcoding any heights/widths. Obviously this should be dynamic as the content might changed depending on the results from the bean.


This code can be run without any change with the Showcase classes  ScrollView.java and CarService.java. It clearly states all problems
```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>

	<style>
 
		.ui-datatable-frozenlayout-left {
			width: 150px;
		}
	 
</style>

</h:head>

<h:body>

	<h3>Frozen Columns Bugs Example</h3>

	<p:commandButton value="DoSomethingAndRefreshTable"
		update="frozencoltable" />
		
	<div style="height: 5px;"></div>	

	<p:dataTable id="frozencoltable" var="car" 
		paginator="true" paginatorPosition="both" scrollWidth="500px;" scrollHeight="500px;"
		rowsPerPageTemplate="5,10,15"
		paginatorTemplate="{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
		paginatorAlwaysVisible="true" rows="20" value="#{dtScrollView.cars5}"
		scrollable="true" frozenColumns="2">

		<p:column headerText="Id" footerText="Id" style="width: 150px;">
			<h:outputText value="#{car.id}" />
		</p:column>
		<p:column headerText="Year" footerText="Year" style="width: 150px;">
			<h:outputText value="#{car.year}" />
		</p:column>
		<p:column headerText="Brand" footerText="Brand" style="width: 150px;">
			<h:outputText value="#{car.brand}" />
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<h:outputText value="#{car.color}" />
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<f:facet name="header">
				<h:panelGroup>
					<h:outputText value="weight" />
					<br />
					<h:outputText value="in" />
					<br />
					<h:outputText value="[kg]" />
				</h:panelGroup>
			</f:facet>
			<h:outputText value="#{car.color}" />
		</p:column>
		<p:column headerText="Image" footerText="Image" style="width: 150px;">
			<img src="" height="100" width="100"/>
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<h:outputText value="#{car.color}" />
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<h:outputText value="#{car.color}" />
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<h:outputText value="#{car.color}" />
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<h:outputText value="#{car.color}" />
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<h:outputText value="#{car.color}" />
		</p:column>
		<p:column headerText="Color" footerText="Color" style="width: 150px;">
			<h:outputText value="#{car.color}" />
		</p:column>
	</p:dataTable>

</h:body>
</html>
 

```
![scr](https://cloud.githubusercontent.com/assets/13161711/26580647/545ad7b2-4539-11e7-8adc-ceed51f9c07c.png)

**Comment by cagataycivici** [comment]
Provide a plunkr please to help us replicate.

**Comment by melloware** [comment]
@cnsgithub When I ran into this issue they suggested I put a hidden image in the frozen column that is the same size as your image in the non-frozen part and that makes them line up.  It's hacky but it worked.  So I put a p:graphicImage with "style=display:none".  

I know that is not a great answer but it gets you around your problem temporarily.

**Comment by cnsgithub** [comment]
Yeah, as said, i think this would basically be the same as hardcoding the heights. The thing is, it can be that not all images are the same size, also it's not said that each cell is equally big. Merely a workaround. 

It should be possible to find a better solution (preferable ootb in the jar) in future. (the datatables.net table can do it, so why should primefaces not be able to auto-size all cells) ultimately its still an html table.

**Comment by schlebe** [comment]
@cnsgithub: thanks to defend developper (user that developp USING Primefaces) point of view :-)

FROZEN columns is buggy 

1. for alignment 
2. for alignment when clicking a row when last row is displayed
3. when sorting another column
4. when setting width using WIDTH attribute of p:column

... and certainly more that nobody discover because nobody use a buggy functionality !

**Comment by cagataycivici** [comment]
If we try to align the widths and heights, it will be a major performance penalty so that's why we haven't do it. Content is yours so better if you do align them manually e.g.

```
.ui-datatable .ui-datatable-thead > tr > th {
.ui-datatable .ui-datatable-body > tr > td {
    height: 50px;
}
```

If we try to find the longest or tallest cell and apply it to all with JS, it will kill the performance, better to do it with CSS on your side.

**Comment by schlebe** [comment]
@cagataycivici: 

I understand that computing maximum height for each rows is a time penalty. 

I think that if I will a quick workaround I must do it myself in explicitely setting row height for both tables.

I have already modifying the heights using following CSS directive

```
.ui-datatable-frozenlayout-left td
    {
    height: 24px;
    }

.ui-datatable-frozenlayout-right td
    {
    height: 24px;
    }
```
... and like said in my first post, this work well.

BUT, I don't see how your CSS code can resolve my display issue WHEN I click on a row when last row in table is displayed.

I think you have answered to cnsgithub consideration about FROZEN functionality but not to the first post !

Can you read it again ?

I think that there exists a problem in refreshing Datatable after clicking on a row when last row is displayed because refresh of Datatable don't take in consideration the fact that there exist a shape at bottom of Datatable that have the height of the horizontal bar of the UNFROZEN table.

Proposal: I think that adding (or activating) the horizontal scrollbar at bottom of FROZEN Datatable when UNFROZEN Datatable has a horizontal scrollbar, can solve the problem.

**Comment by Eachone1** [comment]
> @cnsgithub Cuando me encontré con este problema, me sugirieron que pusiera una imagen oculta en la columna congelada que sea del mismo tamaño que su imagen en la parte no congelada y que los alinee. Es hacky pero funcionó. Así que puse ap: graphicImage con "style = display: none".
> 
> Sé que esa no es una gran respuesta, pero te ayuda a resolver tu problema temporalmente.

No sirve, es solo ocultar una columna, y al ocultarse se desarma otra vez

**Comment by melloware** [comment]
English only please

**Comment by melloware** [comment]
As @cagataycivici said above this would be a performance hit and it can be done with CSS.
