### ISSUE TITLE
Register primeng.org and move all non PrimeFaces content over there

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#2390]
Apparently Angular/PrimeNG user have a difficult time understanding technology Many questions on stackoverflow that are about Angular/PrimeNG get tagged PrimeFaces to (and they even think that is valid) By creating a separate domain (shared landing page maybe) hopefully that wrong tagging can be reduced

**Comment by tandraschko** [comment]
WDYT @cagataycivici ?

**Comment by cagataycivici** [comment]
Makes sense but this should be a forum discussion.

**Comment by kukel** [comment]
Hmmm... mostly these kinds of posts do not attract very big crowds on the forum, and to keep track of it, an issue sounded 'better'. But ok... I'll wait the result (or do you guys expect me to still post on the forum)?

**Comment by kukel** [comment]
https://forum.primefaces.org/viewtopic.php?f=3&t=52352

**Comment by kukel** [comment]
12 days, no comment on the forum post... See that it does not help... I'm inclined to open a new identical issue. It is getting out of hand in Stackoverflow... please...

**Comment by kukel** [comment]
Almost 1 year and not forum reaction... Google searches for PrimeFaces questions get messed up now with PrimeNG stuff just because of the shared hostname.  PLEASE...

**Comment by Rapster** [comment]
Sorry @kukel I wasn't notified of your request. Could you please give me an example of what you mean by "questions get messes up". I never used other products of primetek so hard to tell... But I'd be happy to give my opinion regarding this issue. (I might close #4033 as duplicate and reopen this one. IMO, I'd rather talk about this on github rather than forum)

**Comment by Rapster** [comment]
So far, I would stop using primefaces.org and use primetek.com.tr instead (or prime something ui kit whatever, as long it's a different name). But I wonder about the value of primefaces.org over primetek.com.tr, the company website page already introduces all their products and can redirect to each showcase. Few thing missing might be the blog, store, docs.... That's all I can say for now, but basically I do agree to make a clear distinction :smile: Ultimately, I'd change also the name of the organization, as it's also confusing for people who work on primeng/prmereact to work on something like https://github.com/primefaces/primeng (but that's a major change)

**Comment by tandraschko** [comment]
Pinged PrimeTek about it. I will close the issue as it's not related to the PrimeFaces codebase and can't be changed by community.
