### ISSUE TITLE
JavaScript Errors and warnings in Firefox when reloading page containing PrimePush JavaScript

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#2394]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest sources in GitHub? Reproducible in the latest 6.2.0-SNAPSHOT.
- Application server + version: Tomcat 7, Jetty 8.1.9.v20130131
- Affected browsers: **Firefox Only** (although Chrome still has a warning about a deprecated synchronous XmlHttpRequest being used)

## 2) Steps to reproduce

1. [Deploy the PrimeFaces Showcase (`mvn jetty:run`).](https://github.com/primefaces/showcase#build-from-sources)
2. Navigate to the PrimePush *Counter* example: http://localhost:8080/showcase/push/counter.xhtml
3. Open the JavaScript console (**`Ctrl`** + **`Shift`** + **`I`**).
3. Click the button a few times to increase the counter.
4. Refresh the page (**`F5`**).

## 3) Actual behavior

If the bug still exists, the following error message will appear in the Firefox JavaScript console logs:

> Websocket closed, reason: The endpoint is going away, either because of a server failure or because the browser is navigating away from the page that opened the connection. - wasClean: true  push.js.xhtml:3257:21
> Tue May 30 2017 16:17:17 GMT-0400 (EDT) Atmosphere: unload event  push.js.xhtml:3257:21
XML Parsing Error: no root element found
> Location: http://127.0.0.1:8080/showcase/primepush/counter?X-Atmosphere-Transport=close&X-Atmosphere-tracking-id=11762df7-fd0a-419c-a8eb-fb9577cdec0f&_=1496175437801
Line Number 1, Column 1:  counter:1:1

## 4) Expected behavior

No error messages appear in the JavaScript console logs.

## 5) Sample XHTML

https://github.com/primefaces/showcase/blob/master/src/main/webapp/push/counter.xhtml

## 6) Sample bean

https://github.com/primefaces/showcase/blob/master/src/main/java/org/primefaces/showcase/push/counter/GlobalCounterView.java

**Comment by tandraschko** [comment]
Would be great if could provide a PR!

**Comment by stiemannkj1** [comment]
@tandraschko, I don't really have the time or expertise to work on this now, sorry. I would need to dig into the Atmosphere and PrimeFaces Push code before making any changes since I'm unfamiliar with them.

**Comment by tandraschko** [comment]
I upgraded the script. Could you try it again? There were some firefox fixes.
Atmosphere fails on chrome and firefox for me when running locally when jetty:run. no idea.

**Comment by stiemannkj1** [comment]
I can still reproduce the error in the PrimeFaces showcase with the latest PF build (and scripts).

**Comment by melloware** [comment]
OK I tested this in Firefo, Chrome, and IE.   All are working properly its just that Firefox reports this stuff in the console.   I believe this to be again just something weird Firefox is reporting or a "false positive".  For example Chrome reports this in the exact scenario:

":8080/showcase/javax.faces.resource/socket/socket.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:2167 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

So I think this is a non-issue unless @stiemannkj1 you are seeing an actual issue?

**Comment by stiemannkj1** [comment]
@tandraschko, no issue with the functionality, just an error in the logs as far as I remember.

**Comment by melloware** [comment]
OK I think its safe to close this ticket.

**Comment by tandraschko** [comment]
Thanks! Could someone create a ticket on athmosphere side? So we can simple upgrade it later.

**Comment by melloware** [comment]
I will take care of reporting it to them.

**Comment by melloware** [comment]
Reported https://github.com/Atmosphere/atmosphere-javascript/issues/226

**Comment by john182** [comment]
I have the same problem in version 7.0, but in version 6.2 I didn't have this problem using an autocomplete customization.


`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite"
      xmlns:p="http://primefaces.org/ui" xmlns:c="http://java.sun.com/jsp/jstl/core">

    
    <cc:interface>	
        <cc:attribute name="styleClass" />        
        <cc:attribute name="idComponente" required="true" />
        <cc:attribute name="label" required="true"/>
        <cc:attribute name="itemLabel" required="true"/>
        <cc:attribute name="completeMethod" required="true"/>
        <cc:attribute name="nomeAtributo" required="true"/>
        <cc:attribute name="requerido" default="true"/>       
        <cc:attribute name="controller" required="true"/>
        <cc:attribute name="tamanhoMinimo" default="3"/>
        <cc:attribute name="exibirInfo" default="#{false}"/>
        <cc:attribute name="drop" default="#{true}"/>
        <cc:attribute name="mensangemInfo"/>
        <cc:attribute name="emptyMessage" default="Nenhum registro encontrado"/>
        <cc:clientBehavior name="itemSelecionado" targets="#{cc.attrs.idComponente}" event="itemSelect" />

    </cc:interface>

    
    <cc:implementation>
        <div class="#{cc.attrs.styleClass}">
            <p:outputLabel value="#{cc.attrs.label}"
                           for="#{cc.attrs.idComponente}" />
            <c:if test="#{cc.attrs.exibirInfo}">
                <i class="glyphicon glyphicon-info-sign" style="margin-left: 5px" title="#{cc.attrs.mensangemInfo}"></i>
            </c:if>
            <br />

            <p:autoComplete id="#{cc.attrs.idComponente}"
                            value="#{cc.attrs.nomeAtributo}"
                            completeMethod="#{cc.attrs.controller[cc.attrs.completeMethod]}" var="objeto"
                            itemLabel="#{cc.attrs.itemLabel}" itemValue="#{objeto}"
                            queryDelay="500"
                            dropdown="#{cc.attrs.drop}"
                            style="width: 100%"
                            converter="defaultConverter" forceSelection="true"
                            scrollHeight="350"
                            minQueryLength="#{cc.attrs.tamanhoMinimo}" required="#{cc.attrs.requerido}"
                            emptyMessage="#{cc.attrs.emptyMessage}">

                <cc:insertChildren />

            </p:autoComplete>
        </div>
    </cc:implementation>
</html>`
