### ISSUE TITLE
p:outputLabel failed to find component in composite

### ISSUE THREAD

**Issue by AndrewShwaika** [primefaces/primefaces#2397]
# Failed to find EditableValueHolder in composite

CompositeUtils.invokeOnEditableValueHolder() method doesn't use value of 'targets' attribute of
editableValueHolder tag.

It should use AttachedObjectTarget.getTargets() method.

## 1) Environment
- PrimeFaces version: 6.1.1
- Application server + version: Glassfish 4.1.1, Payara 4.1.1-171
- Affected browsers: All

## 2) Expected behavior

outputLabel should find editable value holder in composite component

## 3) Actual behavior

FacesException: Cannot find editableValueHolder with name: "entry"  in composite component with id: "compositeId"

## 4) Steps to reproduce

Page with <p:outputLabel> with 'for' attribute pointed to composite

## 5) Sample XHTML
	  <p:outputLabel for="compositeEntry" value="#{msg.Label}"/>
	  <lib:entityEntry id="compositeEntry" ....

Composite:

	  <cc:interface>
	...
	    <cc:editableValueHolder name="entry" targets="ac"/>
	...
	  </cc:interface>
	  <cc:implementation>
	...
	      <p:autoComplete id="ac" ....
	...
	  <cc:implementation>

**Comment by tandraschko** [comment]
Does the following case still work:
https://github.com/primefaces/primefaces/issues/1633
? We need to support both cases, the user must NOT define a targets atribute.

**Comment by AndrewShwaika** [comment]
It should work.
Implementation of AttachedObjectTarget.getTargets() method in mojarra and myfaces handles both cases.

**Comment by tandraschko** [comment]
@Rapster Could you please check that, too?

I'm not sure if we should support it as "name" targets a single component and "targets" targets multiple components.
We can only support a single component.

**Comment by AndrewShwaika** [comment]
Mojarra 2.2.9
com.sun.faces.facelets.tag.composite.AttachedObjectTargetImpl.getTargets()
MyFaces 2.2.11
org.apache.myfaces.view.facelets.tag.composite.AttachedObjectTargetImpl.getTargets()

Both implementations first look at 'targets' and if it empty use 'name' for component lookup

**Comment by Rapster** [comment]
Here is description of `name` attribute:

> The value of this attribute maps back to the "for" attribute on an attachable object nested within a composite component. If the "targets" attribute is not specified, this value also represents the component ID of the target component within the that the <composite:implementation> ActionListener should be mapped to.

Which exactly fit our need. Plus, `targets` is not a required attribute and can have several component ids, how deal with that case? Using `targets` does not seem to be a good idea to me...

**Comment by AndrewShwaika** [comment]
The `getTargets()` provides unified method to lookup components in composite.
User **may** use `targets` and set an alias to the inner components.
With existing implementation if `CompositeUtils.invokeOnEditableValueHolder()` you just got FacesException on any attempt to use `targets` attribute with value that differs `name`.

More over `<cc:editableValueHolder>` can be used not only for p:outputLabel.for processing.

About several component: I think we should check all of them, because any of them can be `required` or in error state.

**Comment by tandraschko** [comment]
Thats not possible as a html label targets exactly ONE component. Therefor a outputLabel can never target multiple component.

**Comment by AndrewShwaika** [comment]
First component can be used for html label.
For `required` and error scan all.
Issue is in possibility of using `targets` for aliasing.

**Comment by tandraschko** [comment]
-1 from my side
its feels strange and incorrect that a label in html targets one input, but the server side checks multiple components.
I would suggest that you develop a own outputLabel.

**Comment by Rapster** [comment]
I agree, the VDL documentation should've been enough to answer to this.

**Comment by AndrewShwaika** [comment]
You just prohibit user to use `targets` in case of use p:outputLabel.for
I agree that should be only one component for reference from outputLabel.
My be just check for size of returned list that it should be exactly one?

**Comment by tandraschko** [comment]
Whats the benefit of using "targets" with 1 component instead of just using "name"?

**Comment by AndrewShwaika** [comment]
Just for alias.
We have a lot of composite components for entry different entities.
All of them use different inputs with different ids but binded to name `"entry"`
`<cc:editableValueHolder name="entry" targets="ac"/>`

When using such component we attach, for example, validator always on `"entry"`
`<f:validator ... for="entry"`

Issue arise only after upgrade to PF 6.1.1.

BTW Spec say as mentions above:

> If the "targets" attribute is not specified, this value also represents the component ID...

So if "targets" is specified it should be honoured

**Comment by tandraschko** [comment]
Yep, thats valid than. 
Fixed it in trunk, please give it a try.

**Comment by AndrewShwaika** [comment]
Thanks a lot!
It works perfectly for both cases.
