### ISSUE TITLE
Add leadingZero attribute to InputNumber

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2400]
Controls leading zero behavior
- leadingZero: 'allow', - allows leading zeros to be entered. Zeros will be truncated when entering additional digits. On focusout zeros will be deleted.
- leadingZero: 'deny', - allows only one leading zero on values less than one
- leadingZero: 'keep', - allows leading zeros to be entered. on fousout zeros will be retained.

**Comment by melloware** [comment]
@mertsincan @tandraschko I believe you can close this ticket as well as this exact feature was requested by another user here in #986

**Comment by tandraschko** [comment]
done, thanks!
