### ISSUE TITLE
<p:autoComplete> with is not preserved when MULTIPLE="true"

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#2401]
Hello,

I have found some strange things relatively to \p:autocomplete>

The WIDTH of an <p:autoComplete> is multiply by 2 when MULTIPLE attribute is set to "true".

## 1) Environment
- PrimeFaces version: 6.1.1
- Application server: Glassfish 4.1
- Affected browsers: Google Chrome

## 2) Expected behavior

I expect that WIDTH is preserved !

## 3) Actual behavior

real WIDTH of widget displayed on screen is multiplied by 2 !

## 4) Steps to reproduce

a. note the WIDTH of an <p:autoComplete> without MULTIPLE attribute 
b. add MULTIPLE="true"
c. load application
d. compare new displayed WIDTH with previous one.

## 5) Sample XHTML

```
<p:autoComplete id="SearchBrandName" 
    size="25"        
    immediate="true"
    value="#{viewController.postLabellingSearchCriteria.selectedBrandNameList}"
    completeMethod="#{viewController.searchFormBrandAutoCompleteItems}"
    minQueryLength="1"
    multiple="true"
    dropdown="true"
    dropdownMode="blank"
    widgetVar="SearchBrandName"
    />
```

Before beginning, can somebody reproduce this behavior.
I think that this difference can been observed on <p:autoComplete> widget on Demo page on Primefaces Web site. On this page, you can directly see that the with of MULTIPLE widget is longer without specifying any width !

**Comment by tandraschko** [comment]
viewController is missing to replicate it. Easiest way to provide examples is using the beans from the showcase.

**Comment by schlebe** [comment]
The SIZE attribute specify the number of characters used to determine the width
of the input element.

The computed WIDTH is distinct when multiple="true".

The fact that changing a functional parameter like MULTIPLE has an effect on a visual parameter like WIDTH is disturbing, ... but this is not a bug.

I close this issue.
