### ISSUE TITLE
<p:selectOneMenu> Selection of not escaped SelectItem shows the html-code

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#2402]
If the selectItem used for a selectOneMenu is set to not escape the labels, the options are shown fine. Formatted as expected.  But, after selecting such a selectItem, the entry is shown escaped.

## 1) Environment
- PrimeFaces version: 6.1.1 (some how, build from the github sources)
- Does it work on the newest released PrimeFaces version 6.1? no
- Does it work on the newest sources in GitHub? no
- Application server + version: wildfly 10.1
- Affected browsers: Chrome, Firefox, ..

## 2) Expected behavior

A selected, not escaped selectItem should be display, formatted, not escaped.

## 3) Actual behavior

A selected, not escaped selectItem is shown, escaped.

## 4) Steps to reproduce

Use selectOneMenu with not escaped SelectItems.

## 5) Sample XHTML
```
 <p:selectOneMenu>
     <f:selectItems value="#{controller.options}"/>
</p:selectOneMenu>
```
## 6) Sample bean

```java
public List<SelectItem> getOptions() {
    List<SelectItem> list = new ArrayList<>();
    list.add(new SelectItem("bold", "<b>bold</b>", null, false, false));
    list.add(new SelectItem("italic", "<i>italic</i>", null, false, false));
    return list;
}
```

**Comment by OBreidenbach** [comment]
Pull request provided: https://github.com/primefaces/primefaces/pull/2404

**Comment by tandraschko** [comment]
Thanks for the PR!

**Comment by pistamarti** [comment]
I just upgraded to Primefaces 6.2, but this is not working as expected:
The selected, not escaped selectItem is not displayed formatted.

**Comment by melloware** [comment]
paste example please.

**Comment by pistamarti** [comment]
I just used the showcase (with dependency to primefaces 6.2)  and added an additional example on oneMenu.xhtm:
```
<p:outputLabel value="Formatted" />
<p:selectOneMenu >
     <f:selectItems value="#{selectOneMenuView.formattedOptions}"/>
</p:selectOneMenu>
```
Additional method on SelectOneMenuView:
```
public List<SelectItem> getFormattedOptions() {
   List<SelectItem> list = new ArrayList<>();
   list.add(new SelectItem("bold", "<b>bold</b>", null, false, false));
   list.add(new SelectItem("italic", "<i>italic</i>", null, false, false));
   return list;
}
```
The options are formatted as expected, but the label is shown escaped:

![onemenu](https://user-images.githubusercontent.com/25150933/37087232-031f3c3c-21fa-11e8-91d2-f8190f0b76a0.JPG)

**Comment by melloware** [comment]
I think it is related to this.  https://github.com/primefaces/primefaces/issues/3326

The problem is the new jquery if it sees "<Select One>" it thinks select is a tag and tries to make it <select></select>.  We switched to use .text() instead of .html() for label but I think it is breaking this scenario.  So somehow the client side JS will have to be smarter and know whether to use .html() or .text() depending on the escape flag?

**Comment by pistamarti** [comment]
Maybe its also related to  [#3289]( https://github.com/primefaces/primefaces/issues/3289), but I'm sure you know this better than I do.

(I am just a happy user of primefaces, and looked at the commit-history of forms.selectonemenu.js)

**Comment by melloware** [comment]
Submitted and fixed: https://github.com/primefaces/primefaces/issues/3466
