### ISSUE TITLE
autocomplete attribute at some hidden inputs

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#2407]
The w3c recommendation says, that hidden input must not have the autocomplete attribute. 
[https://www.w3.org/TR/html5/forms.html#hidden-state-(type=hidden)](https://www.w3.org/TR/html5/forms.html#hidden-state-(type=hidden))
The following Components do use a hidden input and does render the autocomplete attribute. 

- Tree
- TabView
- AccordionPanel

We would like to remove the autocomplete attribute, because the w3c validator is not happy about it.
 But in all 3 cases the commit messages says, it is a bug fix. So maybe someone can explain, why it is needed. 
If it is not needed, we are happy to provide a pull request.

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? no, 6.1
- Does it work on the newest sources in GitHub? no
- Application server + version: wildfly 10.1
- Affected browsers: firefox, chrome, ...

## 2) Expected behavior

hidden inputs without autocomplete attribute

## 3) Actual behavior

hidden inputs with autocomplete attribute

## 4) Steps to reproduce

Looking at the show case:
https://www.primefaces.org/showcase/ui/panel/tabView.xhtml

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by OBreidenbach** [comment]
PR provided: https://github.com/primefaces/primefaces/pull/2408

**Comment by melloware** [comment]
Agreed. I am not sure exactly why autocomplete was set on these.   Maybe there was a reason at some point?

**Comment by mertsincan** [comment]
Thanks for the PR, but please see my comment; https://github.com/primefaces/primefaces/pull/2408
