### ISSUE TITLE
SelectCheckboxMenu doesn't support SelectItemGroup

### ISSUE THREAD

**Issue by ValerioEmanuele** [primefaces/primefaces#2416]
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Wildfly 9.0.2
- Affected browsers: Chrome 58, IE11

## 2) Expected behavior
Show an header for the select items group and many checkbox for select items
![desidered](https://cloud.githubusercontent.com/assets/10338843/26822064/0c126612-4aa9-11e7-9264-58a7eef7b1af.png)

## 3) Actual behavior
It shows one checkbox per select item group
![actual](https://cloud.githubusercontent.com/assets/10338843/26822996/45266cca-4aac-11e7-9cd3-cd35e06425de.png)

## 4) Steps to reproduce
Create a SelectCheckboxMenu with a list of SelectItem 

## 5) Sample XHTML
<p:selectCheckboxMenu id="multiple" value="#{checkboxView.selectedCars}" label="Cars" multiple="true">
            <f:selectItems value="#{checkboxView.cars}" />
        </p:selectCheckboxMenu>

## 6) Sample bean

@ManagedBean
public class CheckboxView {
 
    private List<SelectItem> cars;
    private String[] selectedCars;
 
    @PostConstruct
    public void init() {

        cars = new ArrayList<SelectItem>();
        SelectItemGroup germanCars = new SelectItemGroup("German Cars");
        germanCars.setSelectItems(new SelectItem[] {
            new SelectItem("BMW", "BMW"),
            new SelectItem("Mercedes", "Mercedes"),
            new SelectItem("Volkswagen", "Volkswagen")
        });
         
        SelectItemGroup americanCars = new SelectItemGroup("American Cars");
        americanCars.setSelectItems(new SelectItem[]{
            new SelectItem("Chrysler", "Chrysler"),
            new SelectItem("GM", "GM"),
            new SelectItem("Ford", "Ford")
        });
 
        cars.add(germanCars);
        cars.add(americanCars);
    }
 
    public List<SelectItem> getCars() {
        return cars;
    }
 
    public void setCars(List<SelectItem> cars) {
        this.cars = cars;
    }
 
    public String[] getSelectedCars() {
        return selectedCars;
    }
 
    public void setSelectedCars(String[] selectedCars) {
        this.selectedCars = selectedCars;
    }
}

**Comment by melloware** [comment]
Related to #500 and #2222

**Comment by tandraschko** [comment]
Please provide an PR. As melloware mentioned, you check those other changes.

**Comment by ValerioEmanuele** [comment]
@tandraschko @melloware 
I've created PR #2430 on primefaces and PR nr.[28](https://github.com/primefaces/showcase/pull/28) on showcase repository.

**Comment by melloware** [comment]
@KingDavid14 Nice work adding a showcase example too.   I reviewed your changes and they look good to me.

**Comment by melloware** [comment]
@tandraschko you can also close #2222 as well.

**Comment by melloware** [comment]
@KingDavid14 this fix is awesome but it broke #2724 Any chance you could investigate?
