### ISSUE TITLE
<p:autoComplete> renderes div inside a span

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#2419]
The w3c validator is complaining about a div element inside a span element rendered by the autoComplete tag. I suggest to use a span instead of div inside the surrounding span. PR will follow.

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? no, 6.1
- Does it work on the newest sources in GitHub? no
- Application server + version: wildfly 10.1
- Affected browsers: firefox, chrome, ...

## 2) Expected behavior

No div inside span.

## 3) Actual behavior

Div inside span.

## 4) Steps to reproduce

Look at the generated html source code of: https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

## 5) Sample XHTML

see showcase

## 6) Sample bean

see showcase

**Comment by OBreidenbach** [comment]
PR provided: https://github.com/primefaces/primefaces/pull/2420

**Comment by tandraschko** [comment]
For me it looks valid.
The "_panel" div is a dynamic overlay, which will be appended to the body. If you change this to span, it might break.

**Comment by OBreidenbach** [comment]
Unfortunately it does not look good for the w3c validator. The validator is working on the original html and not on the DOM after doing some javascript modifications.
So it is complaining about a block level element inside an inline element.
For use, nothing broke after changing the div to a span element.

**Comment by tandraschko** [comment]
Please provide steps to reproduce.
The code you changed was to render the "_panel" element as a span. But the "_panel" element is directly a child of the body, so no idea why we should change that.

**Comment by OBreidenbach** [comment]
Look at the html source code for autoComplete component in the showcase.
[autoComplete in showcase](https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml)
On line 393 you find the following:
```html
<td>
	<span id="j_idt88:acSimple" class="ui-autocomplete">
		<input id="j_idt88:acSimple_input" name="j_idt88:acSimple_input" type="text" class="ui-autocomplete-input ui-inputfield ui-widget ui-state-default ui-corner-all" autocomplete="off" aria-labelledby="j_idt88:j_idt90" data-p-label="Simple" />
		<div id="j_idt88:acSimple_panel" class="ui-autocomplete-panel ui-widget-content ui-corner-all ui-helper-hidden ui-shadow">
		</div>
	</span>
	<script id="j_idt88:acSimple_s" type="text/javascript">$(function(){PrimeFaces.cw("AutoComplete","widget_j_idt88_acSimple",{id:"j_idt88:acSimple",delay:300});});
	</script>
</td>
```
So there is a div element inside a span element. That reports the w3c validator as an error.
If you open the following link, a lot errors will be reported. The one I taking about is at line 393.
[w3c validator for autoComplete](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.primefaces.org%2Fshowcase%2Fui%2Finput%2FautoComplete.xhtml)

**Comment by tandraschko** [comment]
AFAICS it's just temporary there. If you type something, the panel will be appended to the body.

**Comment by OBreidenbach** [comment]
In Germany websites of public authorities have to be accessible by handicapped people. 
The accessibility is tested by a lot rules. One rule is, that the w3c validator has to run successful. The w3c validator is not very intelligent, it just takes the html as it is delivered. It does not help that it's just temporary there. It is there when the validator run.
I thought primefaces is interested in a good accesssibility: [https://www.primefaces.org/accessibility-enhancements/](https://www.primefaces.org/accessibility-enhancements/)
I provided the patch that some one else can benefit from it.
