### ISSUE TITLE
SplitButton: font-size dependent positioning

### ISSUE THREAD

**Issue by Mobe91** [primefaces/primefaces#2423]
## 1) Environment
- PrimeFaces version: **6.0.12**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**
- Application server + version: 
**WildFly 10.0.0**
- Affected browsers: **All**

## 2) Behavior
Currently, the positioning of the second button within the split button is done via the following CSS rule:
```css
.ui-splitbutton {
    position: relative;
    padding-right: 2em;
}
```
However, this solution makes the positioning dependent of the font-size. For small fonts, the right button will overlap the label in the left button. I used the following altered rule to work around this:

```css
.ui-splitbutton {
    position: relative;
    padding-right: 31px;
}
```

**Comment by melloware** [comment]
@mertsincan thoughts on this one?

**Comment by jxmai** [comment]
How to replicate the problem exactly ? What confuse me most is the following description:

> the positioning of the second button within the split button

Do you need a button within a split button ?

If we just place two buttons side by side with smaller font, it is working fine

![snapshot1](https://user-images.githubusercontent.com/10467831/31646428-6571ab88-b2c7-11e7-8910-5175c0aa62ef.png)

**Comment by Mobe91** [comment]
@jxmai 
> the positioning of the second button within the split button

A split button is composed of two "simple" buttons. Here I am referring to the button on the right side, i.e. the one that triggers the display of the drop down containing secondary actions.

**Comment by jxmai** [comment]
OK, I see. 

>  this solution makes the positioning dependent of the font-size. For small fonts, the right button will overlap the label in the left button

Although the description makes sense, the overlapping does not happen even I decrease the font size as you can see in the screenshot above. 

A small code snippet to replicate the issue will be nice to move this ticket forward.

**Comment by Mobe91** [comment]
Here you go:
[primefaces-2423.zip](https://github.com/primefaces/primefaces/files/1395778/primefaces-2423.zip)

**Comment by jxmai** [comment]
Due to some changes I did the other day for an issue, you need to include some menu to show the button currently.

So, here is the code:

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form>
		<p:splitButton value="Test12345" style="font-size: 12pt">
			<p:menu></p:menu>
		</p:splitButton>
        <p:splitButton value="Test12345" style="font-size: 10pt">
        	<p:menu></p:menu>
        </p:splitButton>
        <p:splitButton value="Test12345" style="font-size: 8pt">
        	<p:menu></p:menu>
        </p:splitButton>
        <p:splitButton value="Test12345" style="font-size: 6pt">
        	<p:menu></p:menu>
        </p:splitButton>
	</h:form>

</h:body>
</html>
```

![image](https://user-images.githubusercontent.com/10467831/31736903-9949ef7a-b40b-11e7-9dc9-a553e8904a47.png)


Looks OK to me so far ? (Except the last one, but that button is way too small to be practical  IMHO)

but I will take a look.

**Comment by jxmai** [comment]
I am going to propose a patch and the end result will look like this:

![image](https://user-images.githubusercontent.com/10467831/31737373-e48a0640-b40c-11e7-8902-f23e7c473b98.png)

Basically, we should not hard code the width for the second button

```css
.ui-splitbutton .ui-button.ui-splitbutton-menubutton {
    width: 32px; <!--remove this-->
    position: absolute;
    top: 0px;
    margin-left: -1px;
    right: 0px;
}
```

**Comment by Mobe91** [comment]
Looks good!

**Comment by melloware** [comment]
Thumbs up!

**Comment by tandraschko** [comment]
Thanks for the PR!
