### ISSUE TITLE
Timeline clientId generation broken

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#2425]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.0 / 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
p:timeline should work with a <p:ajax event="select" listener="#{basicTimelineView.onSelect}" /> within a form.
...

## 3) Actual behavior
p:ajax event="select"  does not work.
..

## 4) Steps to reproduce
run the timeline.xhtml
https://github.com/ravihariharan/primefaces-test/blob/master/src/main/webapp/timeline.xhtml
.. 

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form id="form">

		<p:growl id="growl" showSummary="true" showDetail="true"
			autoUpdate="true" />


		<p:timeline id="timeline" value="#{basicTimelineView.model}"
			height="250px" selectable="#{basicTimelineView.selectable}"
			zoomable="#{basicTimelineView.zoomable}"
			moveable="#{basicTimelineView.moveable}"
			stackEvents="#{basicTimelineView.stackEvents}"
			axisOnTop="#{basicTimelineView.axisOnTop}"
			eventStyle="#{basicTimelineView.eventStyle}"
			showCurrentTime="#{basicTimelineView.showCurrentTime}"
			showNavigation="#{basicTimelineView.showNavigation}">
			<p:ajax event="select" listener="#{basicTimelineView.onSelect}" />
		</p:timeline>
	</h:form>
</h:body>
</html>
```

The p:ajax event="select" only works if 
```
<h:form id="form"></h:form>
<p:grow ....
<p:timeline ....
```

..

## 6) Sample bean
Same as showcase /
https://github.com/ravihariharan/primefaces-test/blob/master/src/main/java/org/primefaces/showcase/view/BasicTimelineView.java
..

**Comment by ravihariharan** [comment]
I have seen this case even in chart also.  I am not sure if this is actually a bug or a general behavior which might be missing from documentation.

**Comment by tandraschko** [comment]
Thats not related to the form directly, just the overwritten special "getClientId" is broken....
If you check the dom, the client id of the timeline should be "form:timeline" not "timeline".

@mertsincan 
Why do we need the overwritten getClientId? Because sometimes the id was null in the taghandler, right?
Maybe we should try to get rid of the taghandler but overwriting getClientId will always lead to problems.
