### ISSUE TITLE
Header Titles aren't displayed on datatable inside rowexpansion

### ISSUE THREAD

**Issue by bjorntj** [primefaces/primefaces#243]
I have a datatable where I use rowexpansion. And inside the rowexpansion, I have another datatable. But in this table I get no title for the column headers. I can see the headers in the table but they contain no text...
I have narrowed it down to the following:

Inside the th tag, there is a span containing the header title, like this:
Code: Select all
<span class="ui-column-title">Name</span>

And that gives the following style:
Code: Select all
.ui-datatable-reflow .ui-datatable-data td .ui-column-title {
    display: none;
}

I see that if I remove the display style, every value is prefixed with the title so just removing it does not seem to work.

I am using reflow=true on both datatables, setting it to false on the datatable outside of the rowexpansion makes the headers display.

**Comment by kneringerjohann** [comment]
this is still a issue!
