### ISSUE TITLE
Enhance styling of SelectItemGroup

### ISSUE THREAD

**Issue by ValerioEmanuele** [primefaces/primefaces#2431]
## 1) Environment
PrimeFaces version: 6.2-Snapshot
Application server + version: Wildfly 9.0.2
Affected browsers: Chrome 58, IE11

## 2) Expected behavior
Add an header like style for select items group. Something like:
![scm-withstyle](https://user-images.githubusercontent.com/10338843/27043009-ff81eedc-4f98-11e7-832c-ea9d764acdef.png)

## 3) Actual behavior
![scm-withoutstyle](https://user-images.githubusercontent.com/10338843/27043090-4e73fac6-4f99-11e7-9588-a4944241a15e.png)

## 4) Steps to reproduce
[Primefaces code update to PR-2430](https://github.com/primefaces/primefaces/pull/2430)

Create a <p:selectCheckboxMenu /> with a collection of SelectItemGroup (See code below).

Add the following css:
```
.ui-selectcheckboxmenu-panel .ui-selectcheckboxmenu-group-item {
    margin:1px 0;
    padding:3px 5px;
    text-align:left;
    white-space: nowrap;
    font-weight:bold;
    border: 1px solid #d9d9d9;
    color: #1b1d1f;
    background: #f6f7f9 0 0 repeat-x;  /* Old browsers */
    background: -moz-linear-gradient(top, #f6f7f9 0%, #ebedf0 100%); /* FF3.6+ */
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f6f7f9), color-stop(100%,#ebedf0)); /* Chrome,Safari4+ */
    background: -webkit-linear-gradient(top, #f6f7f9 0%,#ebedf0 100%); /* Chrome10+,Safari5.1+ */
    background: -o-linear-gradient(top, #f6f7f9 0%,#ebedf0 100%); /* Opera11.10+ */
    background: -ms-linear-gradient(top, #f6f7f9 0%,#ebedf0 100%); /* IE10+ */
    background: linear-gradient(top, #f6f7f9 0%,#ebedf0 100%); /* W3C */
}
```

## 5) Sample XHTML
<p:selectCheckboxMenu id="multiple" value="#{checkboxView.selectedCars}" label="Cars" multiple="true">
<f:selectItems value="#{checkboxView.cars}" />
</p:selectCheckboxMenu>

## 6) Sample bean

```
@managedbean
public class CheckboxView {

private List<SelectItem> cars;
private String[] selectedCars;

@PostConstruct
public void init() {

    cars = new ArrayList<SelectItem>();
    SelectItemGroup germanCars = new SelectItemGroup("German Cars");
    germanCars.setSelectItems(new SelectItem[] {
        new SelectItem("BMW", "BMW"),
        new SelectItem("Mercedes", "Mercedes"),
        new SelectItem("Volkswagen", "Volkswagen")
    });
     
    SelectItemGroup americanCars = new SelectItemGroup("American Cars");
    americanCars.setSelectItems(new SelectItem[]{
        new SelectItem("Chrysler", "Chrysler"),
        new SelectItem("GM", "GM"),
        new SelectItem("Ford", "Ford")
    });

    cars.add(germanCars);
    cars.add(americanCars);
}

public List<SelectItem> getCars() {
    return cars;
}

public void setCars(List<SelectItem> cars) {
    this.cars = cars;
}

public String[] getSelectedCars() {
    return selectedCars;
}

public void setSelectedCars(String[] selectedCars) {
    this.selectedCars = selectedCars;
}
}
```

**Comment by tandraschko** [comment]
Instead of using your CSS, which should be actually in the theme, we could just add ui-widget-header to the item groups.

This is also the same for SelectOneMenu and SelectManyCheckbox and maybe others....

@mertsincan @cagataycivici WDYT?

**Comment by Rapster** [comment]
Shoud be closed then ;-)

**Comment by tandraschko** [comment]
Yep, i think thats up to the theme and not directly related to core.
You can easily add the style in your application - or creating a custom theme.
