### ISSUE TITLE
[CSS] Improve Selection arrow alignment of <p:selectOneMenu>

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2433]
You can easily see the problem here:

https://www.primefaces.org/showcase/ui/misc/themeSwitcher.xhtml

I think it should be avoided to hardcode the margin-top to 3px as it may be distorted with other themes and or different component heights

I don't know what the best approach would be - i've tried to set:

margin-top: 40% which seems to be better overall with various themes. See for yourself if that is good enough to commit and if there's a better way to have it always centered

Bad:
![badalign](https://user-images.githubusercontent.com/13161711/27120807-48d554f0-50e5-11e7-808b-f20b8f91a7f2.png)

Better:
![40per](https://user-images.githubusercontent.com/13161711/27120820-50630a0a-50e5-11e7-84d2-751af8b59fc7.png)

**Comment by tandraschko** [comment]
I think the only correct thing would be to move it into the themes itself, as only the theme knows the sizes.
As this would be a bigger effort, not sure if it's worth. We also have to check the premium themes then.

Also i think it's no problem to overwrite it in a custom theme, which is only perfect way for a perfect theme.

**Comment by cnsgithub** [comment]
Here is what you could also do. I have created this layout for custom SelectOne Menus which have special requirements which can't be done with PrimeFaces.

This solution uses only Unicode / Fontawesome for the Arrow.  In my opinion this is better than using an image at all, as it will scale without getting blurred, and the Color can be set by CSS without having to modify the image.

https://jsfiddle.net/nyqwbLhL/

**Comment by tandraschko** [comment]
AFAIK our new premium themes are also based on fonts.

**Comment by cnsgithub** [comment]
Well that may be, but i don't think this is something only paying users should have. 

Just a suggestion: Instead of having like 20 outdated free themes, why not select one of the "premium" ones to be the default one instead? Aristo (which is also the one bundled with the standard jar) has several CSS problems like this.

---

Anyway, It shouldn't be too hard to change this, so if you want to improve user-experience you should consider it
 
```
<div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div>
```
to
```
.ui-selectonemenu-trigger -> text-align: center;

<div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span style="font-family: FontAwesome; line-height: 20px;"></span></div>

```
Now:
![image](https://user-images.githubusercontent.com/13161711/31651311-80ebb8b4-b31b-11e7-82b8-715c978daecc.png)
Before:
![image](https://user-images.githubusercontent.com/13161711/31651327-8bef3d8a-b31b-11e7-8cb9-9a00cc48a4a4.png)

**Comment by tandraschko** [comment]
Omega is one of those premium themes, we merged to PrimeFaces core. But it's one of the oldest. Maybe we can do this with another, newer one in the next months.

**Comment by melloware** [comment]
It seems the old icon themes are not being updated at all and the new free themes like Omega, Luna, and Nova that come with PF all use icon fonts.  I am going to close this ticket for now.
