### ISSUE TITLE
Panel options menu not working anymore

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#2435]
## 1) Environment
- PrimeFaces version: 6.1.2
- Does it work on the newest released PrimeFaces version? Version? No, 6.1.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: WF 10.0.0
- Affected browsers: all

## 2) Expected behavior
Panel options menu should be visible

## 3) Actual behavior
Menu not shown

## 4) Steps to reproduce
Click on options menu

## 5) Sample XHTML

                <p:panel id="toggleable" header="Toggleable" toggleable="true" closable="true" toggleSpeed="500" closeSpeed="500" widgetVar="panel" style="margin-bottom:20px">

                    <h:panelGrid columns="2" cellpadding="10">
                        <p:graphicImage name="demo/images/godfather/godfather2.jpg" />
                        <h:outputText value="Francis Ford Coppola's legendary continuation..." />
                    </h:panelGrid>

                    <f:facet name="options">
                        <p:menu>
                            <p:submenu label="Settings">
                                <p:menuitem value="Toggle" url="#" icon="ui-icon-newwin" />
                                <p:menuitem value="Remove" url="#" icon="ui-icon-close"/>
                            </p:submenu>
                        </p:menu>
                    </f:facet>
                </p:panel>

**Comment by tandraschko** [comment]
It works fine in trunk, so this could be a elite only bug. @mertsincan would you like to check this?

**Comment by mertsincan** [comment]
Thanks @tandraschko , I'll check this issue on elite versions.

**Comment by msc1979** [comment]
Too bad this one is not fixed in 6.1.3

**Comment by melloware** [comment]
Has this been fixed since?  It's definitely working in the 6.2-SNAPSHOT trunk?

**Comment by davyrod** [comment]
On 6.1.9 and it appears to still not be fixed.  Any updates on this?

**Comment by melloware** [comment]
Just reported through my PRO account to get fixed for 6.1.10...
