### ISSUE TITLE
Organigram renders static content from nodes at the top

### ISSUE THREAD

**Issue by m-i-c-h-a-l** [primefaces/primefaces#2439]
Static texts and html tags (like `<br/>`) from nodes are rendered at the top of organigram. 

Sample XHTML:
```
<p:organigram value="#{testView.rootNode}" var="node">
      <p:organigramNode type="root">Node: #{node.data}</p:organigramNode>
      <p:organigramNode type="node"><p:outputLabel value="Node: #{node.data}"/></p:organigramNode>
</p:organigram>   
```  
Sample Bean:
```  
public class TestView { 
    public OrganigramNode getRootNode() {
        return new DefaultOrganigramNode("root", "TEST", null);
    }
}   
```  
Result:
![image](https://user-images.githubusercontent.com/13847409/27131586-955bc130-510b-11e7-8d4a-1b46eda23bd9.png)

Expected result:
![image](https://user-images.githubusercontent.com/13847409/27131413-e751d03e-510a-11e7-9832-0aad67f8c274.png)

Env: PrimeFaces 6.1, Tomcat 8.5.14, Spring Boot 1.5.3, JoinFaces 2.3.9, Chrome 58.0.3029.110 (64-bit)

**Comment by tandraschko** [comment]
Please provide a PR
