### ISSUE TITLE
p:fileUpload accepts false RegEx matches not specified in "allowTypes" and "accept"

### ISSUE THREAD

**Issue by MilosHavranek** [primefaces/primefaces#2441]
## 1) Environment
- version: **PrimeFaces maven latest 6.1.1**
- Javax.Faces version: **org.glassfish:javax.faces:2.3.1**
- Does not work since version: **5.3 first reported in 2015** (https://github.com/primefaces/primefaces/issues/982)
- Application server + version: **Tomcat 9.0.0.M21**
- Affected browsers: not bound to browsers (tested malfunction on latest firefox, latest chrome)

## 2) Expected behavior

**Accept any file that doesn't have extension, which means filename without "." dot as separator.**
Using 
```
p:fileUpload
allowTypes="/(^[^\\.]+$)/"
accept="/(^[^\\.]+$)/"
```

Accepted files for upload:
> 	1
> 	1 - +ěščřžýáíé - kopie
> 	xe

Rejected files for upload:
> 	.csv
> 	.txt
> 	1 - +ěščřžýáíé.txt
> 	1 - kopie.txt
> 	1.csv
> 	1.txt
> 	1kopie.txt
> 	111.csv
> 	1987.csv
> 	1987.csv.gzip
> 	1987.txt
> 	2002_MalformedInputException.txt
> 	11111 - kopie.csv
> 	a.sh
> 	Apache Tomcat_9.0.0.M8 - Error report.htm
> 	audit.log
> 	catalina_cut.out.txt
> 	catalina_master_deadlock_outofmemory.out
> 	cli_p.cfg
> 	clientAbortException.txt
> 	filtered_XE2.csv
> 	hovno.csv
> 	INSERT INTO ICA.validation_crl (vcrl_id,vcrl_issuer_dn_sha1,vcrl_issuer_skid,vcrl_valid_from,vcrl_valid_to,vcrl_x509,vcr.txt
> 	libNianticLabsPlugin.so
> 	log.cfg
> 	log4jshit.txt
> 	mark_reset_inputstream.txt
> 	messages.log
> 	output_sudoku_zadani.txt
> 	samovolne_vypnuti_serveru_mtd.txt
> 	unknownHostException_mtd.txt
> 	vm_error.txt
> 	XE.csv
> 	xe.dat
> 	XE2.csv
> 	xstej032.xlsx

## 3) Actual behavior
**Client side validation accepts:
files without extension OR (file having extension (".txt" OR ".htm"))**

Accepted files for upload:
> 	.txt
> 	1
> 	1 - +ěščřžýáíé - kopie
> 	1 - +ěščřžýáíé.txt
> 	1 - kopie.txt
> 	1.txt
> 	1kopie.txt
> 	1987.txt
> 	2002_MalformedInputException.txt
> 	Apache Tomcat_9.0.0.M8 - Error report.htm
> 	catalina_cut.out.txt
> 	clientAbortException.txt
> 	INSERT INTO ICA.validation_crl (vcrl_id,vcrl_issuer_dn_sha1,vcrl_issuer_skid,vcrl_valid_from,vcrl_valid_to,vcrl_x509,vcr.txt
> 	log4jshit.txt
> 	mark_reset_inputstream.txt
> 	output_sudoku_zadani.txt
> 	samovolne_vypnuti_serveru_mtd.txt
> 	unknownHostException_mtd.txt
> 	vm_error.txt
> 	xe

Rejected files for upload:
> 	.csv
> 	1.csv
> 	111.csv
> 	1987.csv
> 	1987.csv.gzip
> 	11111 - kopie.csv
> 	a.sh
> 	audit.log
> 	catalina_master_deadlock_outofmemory.out
> 	cli_p.cfg
> 	filtered_XE2.csv
> 	hovno.csv
> 	libNianticLabsPlugin.so
> 	log.cfg
> 	messages.log
> 	XE.csv
> 	xe.dat
> 	XE2.csv
> 	xstej032.xlsx

## 4) Steps to reproduce

**Create page that uses p:fileUpload with RegEx at allowTypes="/(^[^\\.]+$)/" or accept="/(^[^\\.]+$)/"
I also find out, that changing Quantifier in RegEx alternates the failure behavior.**

Malfunction Example 1 - using "**+**" Quantifier in **/(^[^\\.]+$)/**
Accepts:
> 	.txt
> 	1
> 	1 - +ěščřžýáíé - kopie
> 	1 - +ěščřžýáíé.txt
> 	1 - kopie.txt
> 	1.txt
> 	1kopie.txt
> 	1987.txt
> 	2002_MalformedInputException.txt
> 	Apache Tomcat_9.0.0.M8 - Error report.htm
> 	catalina_cut.out.txt
> 	clientAbortException.txt
> 	INSERT INTO ICA.validation_crl (vcrl_id,vcrl_issuer_dn_sha1,vcrl_issuer_skid,vcrl_valid_from,vcrl_valid_to,vcrl_x509,vcr.txt
> 	log4jshit.txt
> 	mark_reset_inputstream.txt
> 	output_sudoku_zadani.txt
> 	samovolne_vypnuti_serveru_mtd.txt
> 	unknownHostException_mtd.txt
> 	vm_error.txt
> 	xe

	

Rejects:
> 	.csv
> 	1.csv
> 	111.csv
> 	1987.csv
> 	1987.csv.gzip
> 	11111 - kopie.csv
> 	a.sh
> 	audit.log
> 	catalina_master_deadlock_outofmemory.out
> 	cli_p.cfg
> 	filtered_XE2.csv
> 	hovno.csv
> 	libNianticLabsPlugin.so
> 	log.cfg
> 	messages.log
> 	XE.csv
> 	xe.dat
> 	XE2.csv
> 	xstej032.xlsx

Malfunction Example 2 - using "*****" Quantifier  in **/(^[^\\.]*$)/**
Accepts:
> 	.csv
> 	.txt
> 	1
> 	1 - +ěščřžýáíé - kopie
> 	1 - +ěščřžýáíé.txt
> 	1 - kopie.txt
> 	1.csv
> 	1.txt
> 	1kopie.txt
> 	111.csv
> 	1987.csv
> 	1987.csv.gzip
> 	1987.txt
> 	2002_MalformedInputException.txt
> 	11111 - kopie.csv
> 	a.sh
> 	Apache Tomcat_9.0.0.M8 - Error report.htm
> 	audit.log
> 	catalina_cut.out.txt
> 	catalina_master_deadlock_outofmemory.out
> 	cli_p.cfg
> 	clientAbortException.txt
> 	filtered_XE2.csv
> 	hovno.csv
> 	INSERT INTO ICA.validation_crl (vcrl_id,vcrl_issuer_dn_sha1,vcrl_issuer_skid,vcrl_valid_from,vcrl_valid_to,vcrl_x509,vcr.txt
> 	libNianticLabsPlugin.so
> 	log.cfg
> 	log4jshit.txt
> 	mark_reset_inputstream.txt
> 	messages.log
> 	output_sudoku_zadani.txt
> 	samovolne_vypnuti_serveru_mtd.txt
> 	unknownHostException_mtd.txt
> 	vm_error.txt
> 	xe
> 	XE.csv
> 	xe.dat
> 	XE2.csv

Rejects:
> 	xstej032.xlsx

Malfunction Example 3 - using "**?**" Quantifier in **/(^[^\\.]?$)/**
Accepts:
> 	.csv
> 	1
> 	1 - +ěščřžýáíé - kopie
> 	1.csv
> 	111.csv
> 	1987.csv
> 	1987.csv.gzip
> 	11111 - kopie.csv
> 	a.sh
> 	audit.log
> 	catalina_master_deadlock_outofmemory.out
> 	cli_p.cfg
> 	filtered_XE2.csv
> 	hovno.csv
> 	libNianticLabsPlugin.so
> 	log.cfg
> 	messages.log
> 	xe
> 	XE.csv
> 	xe.dat
> 	XE2.csv

Rejects:
> 	.txt
> 	1 - +ěščřžýáíé.txt
> 	1 - kopie.txt
> 	1.txt
> 	1kopie.txt
> 	1987.txt
> 	2002_MalformedInputException.txt
> 	Apache Tomcat_9.0.0.M8 - Error report.htm
> 	catalina_cut.out.txt
> 	clientAbortException.txt
> 	INSERT INTO ICA.validation_crl (vcrl_id,vcrl_issuer_dn_sha1,vcrl_issuer_skid,vcrl_valid_from,vcrl_valid_to,vcrl_x509,vcr.txt
> 	log4jshit.txt
> 	mark_reset_inputstream.txt
> 	output_sudoku_zadani.txt
> 	samovolne_vypnuti_serveru_mtd.txt
> 	unknownHostException_mtd.txt
> 	vm_error.txt
> 	xstej032.xlsx

Malfunction Example 4 - using "" no Quantifier in **/(^[^\\.]$)/**
Accepts:
> 	.csv
> 	.txt
> 	1 - +ěščřžýáíé - kopie
> 	1 - +ěščřžýáíé.txt
> 	1 - kopie.txt
> 	1.csv
> 	1.txt
> 	1kopie.txt
> 	111.csv
> 	1987.csv
> 	1987.csv.gzip
> 	1987.txt
> 	2002_MalformedInputException.txt
> 	11111 - kopie.csv
> 	a.sh
> 	Apache Tomcat_9.0.0.M8 - Error report.htm
> 	audit.log
> 	catalina_cut.out.txt
> 	catalina_master_deadlock_outofmemory.out
> 	cli_p.cfg
> 	clientAbortException.txt
> 	filtered_XE2.csv
> 	hovno.csv
> 	INSERT INTO ICA.validation_crl (vcrl_id,vcrl_issuer_dn_sha1,vcrl_issuer_skid,vcrl_valid_from,vcrl_valid_to,vcrl_x509,vcr.txt
> 	libNianticLabsPlugin.so
> 	log.cfg
> 	log4jshit.txt
> 	mark_reset_inputstream.txt
> 	messages.log
> 	output_sudoku_zadani.txt
> 	samovolne_vypnuti_serveru_mtd.txt
> 	unknownHostException_mtd.txt
> 	vm_error.txt
> 	xe
> 	XE.csv
> 	xe.dat
> 	XE2.csv
> 	xstej032.xlsx

Rejects:
> 	1

## 5) Sample XHTML

```
<p:fileUpload fileUploadListener="#{uploadBean.handleFileUpload}"
						 disabled="#{not uploadBean.checkTags()}"
						 mode="advanced"
						 dragDropSupport="true"
						 allowTypes="/(^[^\\.]+$)/"
						 multiple="true"
						 label="#{txt.chooseFiles}"
						 cancelLabel="#{txt.actions_cancel}"
						 uploadLabel="#{txt.actions_upload}"
						 sequential="true"
						 accept="/(^[^\\.]+$)/"
						 invalidFileMessage="#{txt.invalid_fileType}"
						 binding="#{uploadBean.uploader}"/>
```

## 6) Sample bean
- not required, since it's client side validation malfunction

**Comment by melloware** [comment]
Similar to #982 ??

**Comment by MilosHavranek** [comment]
I was looking if the issue was already reported and found #982 which wasn't resolved/closed. I assume it can be the same issue but rather than worry about #982 i would be glad if someone looked into issue i face, but if #982 can help i will be glad. 👍

**Comment by tandraschko** [comment]
Feel free to provide a PR!
JFYI: "accept" just renders the html native accept attribute. allowTyped is for the JS plugin client side.

**Comment by melloware** [comment]
This can be closed as allowTypes is now checked on the server side as well with ticket https://github.com/primefaces/primefaces/issues/2791
