### ISSUE TITLE
ImageCropper renders transparent image as black

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2444]
![cropper](https://user-images.githubusercontent.com/13161711/27217674-1bd76c6c-527b-11e7-9494-cfeb6efdefc4.png)

See on Showcase (I just changed the img src to a transparent one to reproduce the image)

Either it's a bug - or i'm missing a way to configure it. Seems that JCrop supports it 

https://stackoverflow.com/questions/18319594/jcrop-turns-transparent-image-black

**Comment by tandraschko** [comment]
I think it's related how we crop the image on the server side with BufferedImage ;)
Feel free to provide a PR.

**Comment by cnsgithub** [comment]
I don't have a build environment for primefaces set-up right now to test it or to provide a PR. Please check the following potential problematic lines:

```
  a.Jcrop.defaults = {
        bgColor: "black",
```
```
@ImageCropperRenderer:
wb.attr("bgColor", cropper.getBackgroundColor(), null)
```
I've tried to set the bgColor default to '' (empty string) - then it works

https://stackoverflow.com/questions/18319594/jcrop-turns-transparent-image-black

**Comment by tandraschko** [comment]
Ahh ok, thats the default in JCrop. So you can just use the backgroundColor attribute on the jsf tag and every works fine?
If yes, we should close this as won't fix.

**Comment by cnsgithub** [comment]
I think passing null as defaultValue is not really the perfect solution, i'd change it to "transparent". Just because a third party lib chooses an awkward default it doesn't mean primefaces should too. 

But yeah, i just checked using backgroundColor will work, so ill keep it like that. And closed the issue as for me it's working now.  Thanks for the hint.

**Comment by erickdeoliveiraleal** [comment]
I defined in jsf tag backgroundColor="black" or transparent and the issue persists.
@cnsgithub how you solved this problem?
