### ISSUE TITLE
p:socket with transport="long-polling" causes XML Parsing Errors in Firefox

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#2447]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest sources in GitHub? Yes
- Application server + version: Jetty, Tomcat
- Affected browsers: **Firefox**

## 2) Steps to reproduce

1. Add the `transport="long-polling"` attribute to the `p:socket` in [PrimeFaces Showcase **`src/main/webapp/push/counter.xhtml`** (Line 43)](https://github.com/primefaces/showcase/blob/master/src/main/webapp/push/counter.xhtml#L43).
2. Deploy the showcase:

        mvn clean package && mvn jetty:run

3. Navigate to http://localhost:8080/showcase/push/counter.xhtml.
4. Right-click and click *Inspect Element*.
5. Click the *Click* button several times to increment the counter.

## 3) Expected behavior

No XML Parsing Errors appear in the browser logs.

## 4) Actual behavior

Several XML parsing errors like the following will appear in the browser logs:

> XML Parsing Error: syntax error
Location: http://127.0.0.1:8888/showcase/primepush/counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.3-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1497618505646
Line Number 2, Column 1:  counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf:2:1
>
> XML Parsing Error: syntax error
Location: http://127.0.0.1:8888/showcase/primepush/counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf?X-Atmosphere-tracking-id=b1934409-8836-424c-b8ab-1f7f35a420ad&X-Atmosphere-Framework=2.3.3-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1497618505684
Line Number 2, Column 1:  counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf:2:1
>
> XML Parsing Error: syntax error
Location: http://127.0.0.1:8888/showcase/primepush/counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf?X-Atmosphere-tracking-id=b1934409-8836-424c-b8ab-1f7f35a420ad&X-Atmosphere-Framework=2.3.3-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1497618635041
Line Number 2, Column 1:  counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf:2:1
>
> XML Parsing Error: syntax error
Location: http://127.0.0.1:8888/showcase/primepush/counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf?X-Atmosphere-tracking-id=b1934409-8836-424c-b8ab-1f7f35a420ad&X-Atmosphere-Framework=2.3.3-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1497618635183
Line Number 2, Column 1:  counter;jsessionid=1w4ywmgx9ch7bo5ki7ksosspf:2:1

## 5) Notes

This error appears to be benign as everything still works correctly with long-polling.

**Comment by melloware** [comment]
I have verified this in Firefox but as stated there is no issue.  I believe this to be a Firefox "false positive".   Chrome, IE, and Firefox all tested and working fine in the above scenario.  I recommend closing this ticket.

**Comment by tandraschko** [comment]
Could maybe create a issue on on athmosphere side? such a error/warning isn't nice.

**Comment by melloware** [comment]
Reported https://github.com/Atmosphere/atmosphere-javascript/issues/226
