### ISSUE TITLE
p:defaultCommand triggered by browser password managers due to missing keyCode.NUMPAD_ENTER declaration

### ISSUE THREAD

**Issue by mjiderhamn** [primefaces/primefaces#2448]
## 1) Environment
- PrimeFaces version: 5.0+
- Does it work on the newest released PrimeFaces version? No (determined from source code)
- Does it work on the newest sources in GitHub? No (5162cf1bf281cacebd665ae5922fc5a0b1469406)
- Application server + version: Resin (irrelevant)
- Affected browsers: Chrome 59, Safari 9

## 2) Expected behavior
`<p:defaultCommand />` is supposed to be triggered when the user presses Enter on their keyboard.

## 3) Actual behavior
As of Chrome 59 (59.0.3071.86) and Safari 9 (conditions for OS and SSL have not been thoroughly investigated), if the login credentials is stored in the browsers password manager, the `<p:defaultCommand />` is triggered as soon as the username has been filled - i.e. before the password has been filled. In a typical case this causes the login form to be posted resulting in a failed login attempt. In case the page with the failed login contains the username and password fields, this may - as in our case - cause the page to reload over and over and over, effectively hindering the user from login in until stored password is removed from browsers password manager.

## 4) Steps to reproduce
Create login page with `<p:defaultCommand />`
Using Chrome 59+, log in and accept suggestion to store password.
Log out and go to login page.

## 5) Sample XHTML
```xml
<p:inputText .../>
<p:password .../>
<p:defaultCommand .../>
```

## Cause
Upon investigation, it turns out that the cause of this is the fact that `$.ui.keyCode.NUMPAD_ENTER` is no longer defined. In 4.0 it was declared in [`jquery-plugins.js`](https://github.com/primefaces/primefaces/blob/4_0/src/main/resources/META-INF/resources/primefaces/jquery/jquery-plugins.js#L35).
`$.ui.keyCode.ENTER` is still declared in [`keyboard.js`](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/keyboard/keyboard.js#L87).

Now, when the browsers password manager of the above mentioned browsers fills the form, it seems to send a keydown event with `e.which` = `undefined`. And since `$.ui.keyCode.NUMPAD_ENTER` also is `undefined`, it means that any test checking for `e.which == keyCode.NUMPAD_ENTER` - such as [the one for defaultCommand](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/forms/forms.js#L3475) - results in true.

## Workaround
```javascript
$.extend( $.ui.keyCode, {
  NUMPAD_ENTER: 108
});
```

**Comment by melloware** [comment]
Very good debugging.    I will let @tandraschko weigh in but it sounds like your workaround to add NUMPAD_ENTER needs to be put somewhere in the PF default code since its removed from jquery-ui.

**Comment by melloware** [comment]
This is a bigger issue as NUMPAD_ENTER constant is used in all the following components.

accordion\accordion.js 
autocomplete\autocomplete.js 
columntoggler\columntoggler.js 
core\core.js 
datatable\datatable.js 
fieldset\fieldset.js 
fileupload\fileupload.js 
forms\forms.js 
menu\menu.js 
overlaypanel\overlaypanel.js 
paginator\paginator.js 
picklist\picklist.js 
spinner\spinner.js 
tabview\tabview.js 
terminal\terminal.js 
tree\tree.js 
treetable\treetable.js

**Comment by tandraschko** [comment]
Why has it been removed from jquery plugins? Where was it defined exactly? 
Would be great if you could investigate a little bit more ;)

**Comment by melloware** [comment]
@tandraschko It looks like NUMPAD_ENTER was defined in JQuery UI Plugins...

PF 4.0 used Jquery UI 1.10.3 = OK
PF 5.0 used Jquery UI 1.10.3 = OK
PF 6.0 used Jquery UI 1.11.0 = REMOVED
PF 6.1 used Jquery UI 1.11.3 = REMOVED

https://github.com/primefaces/primefaces/blob/4_0/src/main/resources/META-INF/resources/primefaces/jquery/jquery-plugins.js#L35

**Comment by mjiderhamn** [comment]
We're on PF 5.2 which uses jQuery 1.11.0 (i.e. removed). So This changed somewhere between 5.0 and 5.2.

**Comment by tandraschko** [comment]
why did jquery ui removed the code? Could you search for the root issue?

**Comment by melloware** [comment]
@tandraschko I have looked through their GitHub and I can see the code was removed between their 1.10.4 and 1.11.0 branches but I can't find any ticket on why they removed it.

**Comment by tandraschko** [comment]
https://bugs.jqueryui.com/ticket/9269

will think about it how i will solve it in a nice way.

**Comment by melloware** [comment]
Ahh I am looking at their github didn't realize they had their own bug tracking site sorry!

**Comment by melloware** [comment]
I am wondering if we can just do as suggested above and just add this somewhere in PF after jquery=ui loads.  I just don't know which PF script this should go in??

```javascript
$.extend( $.ui.keyCode, {
  NUMPAD_ENTER: 108
});
```

**Comment by tandraschko** [comment]
Will check it.
Could you please also check if we also other already removed keycodes?

**Comment by melloware** [comment]
I will investigate if we are using any of the others that were removed and report back.

**Comment by melloware** [comment]
I have confirmed of the keys removed only NUMPAD_ENTER is used in PF.

	        NUMPAD_ADD: 107,
		NUMPAD_DECIMAL: 110,
		NUMPAD_DIVIDE: 111,
		NUMPAD_ENTER: 108,
		NUMPAD_MULTIPLY: 106,
		NUMPAD_SUBTRACT: 109,

**Comment by tandraschko** [comment]
Added your snippet @melloware, please check if it's fixed.

**Comment by melloware** [comment]
It seems to be working for me after this commit.  I like that you rearranged those scripts I think it will make it easier to maintain going forward.

**Comment by tandraschko** [comment]
Great! Yep :)

**Comment by majkers** [comment]
Seems like it is again not working with PrimeFaces 7.0 and Chrome 73.0.3683.86

**Comment by melloware** [comment]
Yep Chrome just changed. See:  https://github.com/primefaces/primefaces/issues/4672

**Comment by melloware** [comment]
The code that used to make this work in 6.2 was removed because of this ticket: https://github.com/primefaces/primefaces/issues/3615   It seems like this is a country dependent solution?

To temporarily make this work again add this JavaScript somewhere on your page.

```javascript
(function () {
    $.extend($.ui.keyCode, {
        NUMPAD_ENTER: 108
    });
}); 
```

**Comment by majkers** [comment]
Not working....

**Comment by melloware** [comment]
You sure you included it correctly this user reported that fixed it for them:  https://github.com/primefaces/primefaces/issues/4672  Read that thread.

**Comment by majkers** [comment]
Yes. Checked it one more time. Not working

**Comment by melloware** [comment]
@majkers I just submitted this PR which I think will fix it: https://github.com/primefaces/primefaces/pull/4797

**Comment by majkers** [comment]
Looking forward to it :) Thanks

**Comment by melloware** [comment]
Hopefully we can get it into Elite 7.0.2.
