### ISSUE TITLE
Add stickyTopAt attribute to DataTable

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2449]
So far, a sticky always goes to the top the page, but I'd like to make it sticky relative to the header of my page (otherwise it does not look fancy at all). I'll show you an example with Barcelena layout (it's a mock)

![sticky](https://user-images.githubusercontent.com/7521311/27233917-7aa25e24-52bb-11e7-8d92-3ee0d63ee3fb.png)

It would be really fancy to have the columns sticky to the header of the page, what do you think?

**Comment by Rapster** [comment]
I was thinking about setting a priority, the component with a lower priority will be sticky to the component with a higher priority

**Comment by Rapster** [comment]
A workaround wrote by @mertsincan (thanks to him) proposed here: https://forum.primefaces.org/posting.php?mode=reply&f=53&t=52269

**Comment by Rapster** [comment]
To make it simple, a new attribute could be created `stickyRelativeTo` expecting a jquery selector (e.g `.topbar` or `#top_bar`)

**Comment by tandraschko** [comment]
Should be fixed by https://github.com/primefaces/primefaces/issues/834
Could you try?
We automatically check now for the scrollparent

**Comment by Rapster** [comment]
834 does not sound like a duplicate to me, it's a total different problem. This one is about making the sticky, no longer on the top of the page but relative to another element (e.g premium template have topbar, and sticky should be displayed right below it and not on the top of the page). I thought Mert would provide something... I can think about providing a fix

**Comment by tandraschko** [comment]
`This one is about making the sticky, no longer on the top of the page but relative to another element (e.g premium template have topbar, and sticky should be displayed right below it and not on the top of the page)`

Thats exact the problem in #834. Maybe it already works fine in the Premium Layouts.

**Comment by Rapster** [comment]
Thomas, as it is today, stickyHeader will be displayed on the top (which is normal, it's done by design). 384 is about an issue of stickyHeader when contained in a `p:layout`

**Comment by tandraschko** [comment]
Its not about p:Layout, its about every scollparent, when the scrollparent is not document itself.

**Comment by Rapster** [comment]
FYI, on Premium Layouts a tweak is used: https://forum.primefaces.org/viewtopic.php?f=53&t=52269

**Comment by Rapster** [comment]
In the showcase, a trick is used:

```xml
    <ui:define name="head">
        <style type="text/css">
            .ui-sticky {
                top: 70px !important;
                position: fixed !important;
            }
            @media (max-width: 960px) {
                .ui-sticky {
                    top: 110px !important;
                }
            }
        </style>
    </ui:define>
```

As it is common to have a topbar in website nowadays, I'd suggest to have this new attribute (`stickyAt`?)

**Comment by mertsincan** [comment]
In the showcase, I removed the above css. Please try;
```
<p:dataTable var="car" value="#{dtStickyView.cars}" stickyHeader="true" stickyTopAt=".layout-topbar">
            <p:column headerText="Id">
                <h:outputText value="#{car.id}" />
            </p:column>
            <p:column headerText="Year">
                <h:outputText value="#{car.year}" />
            </p:column>
            <p:column headerText="Brand">
                <h:outputText value="#{car.brand}" />
            </p:column>
            <p:column headerText="Color">
                <h:outputText value="#{car.color}" />
            </p:column>
        </p:dataTable>
```

On Barcelona Layout, you need to make the following change to re-calculate stickyHeader according to menu animation;
```
$(window).trigger('resize', {delay:350}); //line 52 and 101
```
