### ISSUE TITLE
Option to hide the Event time in p:schedule

### ISSUE THREAD

**Issue by aimad-majdou** [primefaces/primefaces#2451]
When you add a new `DefaultScheduleEvent` in the schedule the event is added with it's title concatenated with the time, like this :

![image](https://user-images.githubusercontent.com/16216620/27284198-3984302e-54e7-11e7-9682-24a24f51f26d.png)

in some cases I want this time to be hidden so it looks like this : 

![image](https://user-images.githubusercontent.com/16216620/27284252-65ed0366-54e7-11e7-9e3f-968cc50513f1.png)

In the javascript code an element with the class `fc-time` is added, and to hide it we can use : `.fc-time { display:hidden; }` but this will hide all the divs with `fc-time` class.

So when I add a new `DefaultScheduleEvent` like this : 

`defaultScheduleEvent = new DefaultScheduleEvent("F2", startPlanningDate, endPlanningDate, "formuleColor1");`

There should be some option to tell that I want to hide or show the event time beside the title.

**Comment by tandraschko** [comment]
A PR would be great.

**Comment by Fyotty** [comment]
da pra add uma imagem

**Comment by wal-jan** [comment]
@aimad-majdou you can achive hiding time of selected events by adding a style class (e.g. `hide-time`)
`new DefaultScheduleEvent("F2", start, end, "formuleColor1 hide-time");`
and style `.hide-time .fc-time { display:none; }`

**Comment by OBreidenbach** [comment]
This can easily be achieved by configure the underlying [fullCalendar ](https://fullcalendar.io) with the provided extender hook.
```
<p:schedule ... extender="initSchedule" ... />

function initSchedule() {
	// Configure fullCalendar
	this.cfg.views = {
		week: {
			displayEventTime: false
		},
		day: {
			displayEventTime: false
		}
	};
}
```
IMHO this ticket should be closed.

**Comment by tandraschko** [comment]
@OBreidenbach AFAICS the user would like to get a option to set the per item, not in generell

**Comment by OBreidenbach** [comment]
You are right. But there is still the option to add a style class. Like described by @wal-jan.
Or you can override the render method:
```
function initSchedule() {
	// Configure fullCalendar
	this.cfg.eventRender = function (event, element, view) {
                    // still needs to at a style class to the event as marker.
                    if (event.className.includes('do-not-show-time-class')) {
                        element.find('.fc-time').remove();
                    }
	};
}
```

**Comment by tandraschko** [comment]
ok, then lets close it.
