### ISSUE TITLE
p:panelGrid, header lacks padding when columns > 0

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#2452]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) NO
- Application server + version: Tomcat 7
- Affected browsers: All

## 2) Expected behavior
The header of the `p:panelGrid` should have proper padding, even if the `columns` attribute is provided.

## 3) Actual behavior
The header doesn't have the proper padding, becuase a css class is missing. Rendered output:
![panelgrid](https://user-images.githubusercontent.com/18428155/27285710-dab1a916-54fd-11e7-896c-233b2d46c7bd.jpg)

## 4) Steps to reproduce
Just open the provided xhtml.

## 5) Sample XHTML
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
		<p:panelGrid columns="1">
			<f:facet name="header">
				<h:outputText value="With columns"/>
			</f:facet>
			<h:outputText value="Content"/>
		</p:panelGrid>
		
		<p:spacer height="10"/>
		
		<p:panelGrid>
			<f:facet name="header">
				<p:row>
					<p:column>
						<h:outputText value="Without columns"/>
					</p:column>
				</p:row>
			</f:facet>
			<p:row>
				<p:column>
					<h:outputText value="Content"/>
				</p:column>
			</p:row>
		</p:panelGrid>
    </h:body>
</html>
```

## 6) Sample bean
Not needed

**Comment by NicolaIsotta** [comment]
The fix should be easy:
Add the line: `writer.writeAttribute("class", PanelGrid.CELL_CLASS + " ui-widget-header", null);`
in the [`PanelGridRenderer` class, line 270](https://github.com/primefaces/primefaces/blob/94b62d5dc9da7e1113fd6dbb03cf0099fa520cde/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java#L270).

**Comment by melloware** [comment]
I made a slight change to your suggestion and submitted a PR. I moved it up to line 264 to replace the "class" attribute that was being set there.

**Comment by NicolaIsotta** [comment]
Thanks @melloware .
Are you sure that the `PanelGrid.CELL_CLASS` class should be added to the `tr`? In the other "path", when  `columns > 0`, it's applied to the `td` element.

**Comment by melloware** [comment]
You are right.  I just fixed it back to your original suggestion if you want to review.

**Comment by NicolaIsotta** [comment]
I've tested the fix, it's working properly.

**Comment by tandraschko** [comment]
Thanks for the PR!
