### ISSUE TITLE
p:chips doesn't fire 'itemUnselect' ajax event when a chip deleted with backspace

### ISSUE THREAD

**Issue by mismanc** [primefaces/primefaces#2453]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not tested
- Application server + version: Wildfly 10.1
- Affected browsers: All

## 2) Expected behavior
When you delete a chip from p:chip element with backspace,  'itemUnselect' event should get fired,
as clicking 'x' icon on chimp

## 3) Actual behavior
When you delete a chip from p:chip element with backspace,  'itemUnselect' event doesn't triggered

## 4) Steps to reproduce
1-Enter some chips to primeface chip element
2-Delete one of them with backspace

## 5) Sample XHTML
```
<p:chips value="#{bean.chipSearchList}"  >
              <p:ajax event="itemSelect" listener="#{bean.chipsSelect}" update="datalist" />
              <p:ajax event="itemUnselect" listener="#{bean.chipsDeselect}" update="datalist" />
</p:chips>

```

## 6) Sample bean
```
public void chipsSelect() {
     System.out.println("SELECT WORK");
}
    
public void chipsDeselect() {
     System.out.println("DESELECT WORK");
}
```

**Comment by melloware** [comment]
I see the problem.  Working on a PR now.
