### ISSUE TITLE
core.js#calculateScrollbarWidth incorrect on IE 11 / misaligned datatable's header column with table body when scrollable

### ISSUE THREAD

**Issue by elfwine** [primefaces/primefaces#2462]
I have a dynamic p:datatable (with scrollable=true) inside of p:dialog that popout when the button is press from main page.
Whenever the table's data is longer than the dialog's height, the table's header width isn't adjusting.
I inspect through developers tool and found out that Primefaces.calculateScrollbarWidth() always return 0 on IE 11. Chrome and FF browsers have no problem. 
I checked core.js's calculateScrollbarWidth function and I think the logic to calculate scroll width when IE browser is only applicable to version lower than 11.

## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Tomcat 8.0.26
- Affected browsers: IE 11 (11.1358.14393.0)

## 2) Expected behavior
Primefaces.calculateScrollbarWidth() is not 0

## 3) Actual behavior
Primefaces.calculateScrollbarWidth() = 0

## 4) Steps to reproduce
1. Place a javascript code before </h:body> tag. 
2. Call the Primefaces.calculateScrollbarWidth();

## 5) Sample XHTML

```javascript
   <script type="text/javascript">
   	$(function(){
   		var scrollwidth = Primefaces.calculateScrollbarWidth();
   		console.log('Scroll width : ' + scrollwidth);
   	});
   </script>
```

**Comment by tandraschko** [comment]
A PR would be great

**Comment by tandraschko** [comment]
Works fine for me with trunk and the current IE11.
