### ISSUE TITLE
SelectOneRadio with custom layout and required="true" missing "ui-state-error" class

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#2464]
## 1) Environment
- PrimeFaces version: 6.1.2
- Does it work on the newest released PrimeFaces version? Version? No (6.1.2)
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Any
- Affected browsers: Any

## 2) Expected behavior
When used custom layout for selectOneRadio the radioButtons with for attribute set to the selectOneRadio should have styleClass 'ui-state-error' when selectOneRadio is set as required="true"

## 3) Actual behavior
There is no 'ui-state-error' class on radios

## 4) Steps to reproduce
Set required="true" to selectOneRadio with custom layout in showcase 

## 5) Sample XHTML
```
<p:selectOneRadio id="customRadio" value="#{radioView.color}" layout="custom" required="true">
  <f:selectItem itemLabel="Red" itemValue="Red" />
  <f:selectItem itemLabel="Green" itemValue="Green" />
  <f:selectItem itemLabel="Blue" itemValue="Blue" />
</p:selectOneRadio>
<h:panelGrid columns="3" cellpadding="5">
  <p:radioButton id="opt1" for="customRadio" itemIndex="0" />
  <h:outputLabel for="opt1" value="Red" />
  <p:spinner />
  <p:radioButton id="opt2" for="customRadio" itemIndex="1" />
  <h:outputLabel for="opt2" value="Green" />
  <p:inputText />
  <p:radioButton id="opt3" for="customRadio" itemIndex="2" />
  <h:outputLabel for="opt3" value="Blue" />
  <p:calendar />
</h:panelGrid>
```

## 6) Sample bean
Not needed

**Comment by martin654** [comment]
I suggest to refactor RadioButtonRenderer class a bit. The for attribute from p:radioButton is already evaluated to SelectOneRadio here, so we could take the required value from it and render the "ui-state-error" in encodeOptionOutput.

**Comment by martin654** [comment]
Sorry, my first time creating PR for Primefaces. Closed the first PR because it didn't contain both commits. Second PR should be OK.

**Comment by tandraschko** [comment]
Thanks!

**Comment by martin654** [comment]
Could you pleasae put it into one of 6.1.x versions? Thank you!

**Comment by tandraschko** [comment]
Thats up to @mertsincan ;)
