### ISSUE TITLE
fix JSF 2.0 incompatible use of enum in UIRepeat

### ISSUE THREAD

**Issue by sorontur** [primefaces/primefaces#2469]
1) Environment
- PrimeFaces version: 6.2.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Websphere 8.5.5.9
- Affected browsers: all (server side issue)

3) Actual behavior
There is an Error because of the missing EnumValue of VisitHint.SKIP_ITERATION in JSF 2.0 This was already solved in another Component.

4) PullRequest
I ported the Fix of UIData:
#2468

**Comment by tandraschko** [comment]
Thanks for the PR!
