### ISSUE TITLE
p:selectManyCheckbox with layout="custom" and required="true" missing "ui-state-error" class

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#2474]
## 1) Environment
- PrimeFaces version: 6.1.2
- Does it work on the newest released PrimeFaces version? Version? No (6.1.2)
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Any
- Affected browsers: Any

## 2) Expected behavior
When used custom layout for selectManyCheckbox, the checkboxes with for attribute set to the selectManyCheckbox should have styleClass 'ui-state-error' when selectManyCheckbox is set as required="true".

## 3) Actual behavior
There is no 'ui-state-error' class on rendered checkboxes

## 4) Steps to reproduce
Set required="true" to selectManyCheckbox with custom layout in showcase 

## 5) Sample XHTML
```
<p:selectManyCheckbox id="custom" value="#{checkboxView.selectedConsoles2}" layout="custom" required="true">
  <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
  <f:selectItem itemLabel="PS4" itemValue="PS4" />
  <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
</p:selectManyCheckbox>
<div class="ui-grid ui-grid-responsive">
  <div class="ui-grid-row">
    <div class="ui-grid-col-4" style="text-align:center">
      <h:outputLabel for="opt1" value="Xbox One" style="display:block;margin-bottom:8px"/>
      <p:checkbox id="opt1" for="custom" itemIndex="0" />
    </div>
    <div class="ui-grid-col-4" style="text-align:center">
      <h:outputLabel for="opt2" value="PS4" style="display:block;margin-bottom:8px"/>
      <p:checkbox id="opt2" for="custom" itemIndex="1" />
    </div>
    <div class="ui-grid-col-4" style="text-align:center">
      <h:outputLabel for="opt3" value="Wii U" style="display:block;margin-bottom:8px"/>
      <p:checkbox id="opt3" for="custom" itemIndex="2" />
    </div>
  </div>
</div>
```

## 6) Sample bean
Not needed

**Comment by martin654** [comment]
The problem is the same as in #2464. I will provide PR

**Comment by tandraschko** [comment]
Thanks!

**Comment by martin654** [comment]
Could you pleasae put it into one of 6.1.x versions? Thank you!

I guess its up to **@mertsincan**

**Comment by mertsincan** [comment]
Thanks @martin654 ;)
