### ISSUE TITLE
Select*: Add 'datalist' functionality to reduce DOM

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#2477]
This is an enhancement request for PrimeFaces `select*` components especially the `p:selectOneMenu` (but that is due to personal 'need'). 

We have an application where we have to enter a lot of fields in multiple languages and for some stupid reason we cannot use 'autoComplete' but need to have the full list. This list of languages is rather long and contains flags to. Having 25 fields in this form, all in 'datagrids' since multiple languages should be possible is a lot, lot of identical html. Being able to reference some 'datalist' like is possible in html https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist would reduce the amount of rendered html by about 80-90%!, speeding up page load, ajax updates and more. Especially if you use this in a datalist/table and need to update the list/table when adding additional rows. 

So I propose something like:

    <p:selectOneMenu value="#{myBean.field1}" optionList="idOfResuableOptionList" />

    <p:selectOneMenu value="#{myBean.field2}" optionList="idOfResuableOptionList" />

    <p:optionList id="idOfResuableOptionList" var="l">
            <f:selectItems value="#{myBean.languages}" var="laguage" itemLabel="#{language.displayName}" itemValue="#{language}" />
 
            <p:column style="width:10%">
                <h:outputText styleClass="ui-flag ui-flag-#{l.name}" />
            </p:column>
 
            <p:column>
                <h:outputText value="#{l.displayName}" />
            </p:column>
    </p:selectOneMenu>
    </p:optionList>

But something like 

    <p:selectOneMenu id="firstSelect" value="#{myBean.field1}" var="l">
            <f:selectItems value="#{myBean.languages}" var="laguage" itemLabel="#{language.displayName}" itemValue="#{language}" />
 
            <p:column style="width:10%">
                <h:outputText styleClass="ui-flag ui-flag-#{l.name}" />
            </p:column>
 
            <p:column>
                <h:outputText value="#{l.displayName}" />
            </p:column>
    </p:selectOneMenu>

    <p:selectOneMenu value="#{myBean.field2}" optionList="firstSelect" var="l" />

Where the second and other selects reference the first one would also work.

For this last solution I already created some patch some time ago and are more than happy to contribute the code.

**Comment by tandraschko** [comment]
I like the idea, i will also think about the best solution.

**Comment by djmj** [comment]
If p:cellEditor is used, this may be related to #362?

**Comment by tandraschko** [comment]
can we really use that or would be just a new component, a styled native html datalist?
If you check the p:selectOneMenu dropdown, everything is styled and custom content, that isnt possible if we use datalist i assume.

Actually a h:datalist would be perfect for it.

**Comment by jepsar** [comment]
Hi @kukel,

Not ideal, but this this could help:

1. Use `dynamic="true"` on your select
2. Don't use custom options, but instead use emoji flags

**Comment by melloware** [comment]
Going to close this as not planned.  Been 5 years and no easy way to add it to PF.  As @tandraschko suggested maybe an h:datalist in Faces core.
