### ISSUE TITLE
ColumnToggler: Pass specific column attribute in toggle event 

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2478]
If a new column attribute like `toggleId` is available it could be passed to the column toggler event.

It would make it more developer friendly in stateful mode since no visibility lookups would be required using the index. Keeping track of column-index is hard to maintain in big tables and results in problems in combination with _columnGroup_ and reorder mode.

A  new attribute `toggleId` would basically group the following two _year_ columns.

	<p:columnGroup>
		<p:row>
			<p:column headerText="Date" colspan="2" visible="#{bean.visibleMap.get('year') or bean.visibleMap.get('month') }"/>
		</p:row>
		<p:row>
			<p:column headerText="Year" toggleId="year" visible="#{bean.visibleMap.get('year')}"/>
		</p:row>
	</p:columnGroup>

	
	<p:column toggleId="year" visible="#{bean.visibleMap.get('year')}">
		#{car.year}
	</p:column>

	public void onToggle(final ToggleEvent e)
	{
		String toggleId = e.getToggleId(); // year
		visibleMap.put(toggleId , e.getVisibility() == Visibility.VISIBLE);
	}

**Comment by tandraschko** [comment]
So what should we do here? Putting the column in EL scope? If yes, it would be great if you could describe your issue like this and not doing it like a forum question ;)

**Comment by djmj** [comment]
I changed it :) also changed whole definition, since column-id would not be enough if used with column-groups. This would lead to duplicate id's.

**Comment by tandraschko** [comment]
I don't understand it anymore :/ where is "year" is defined?

**Comment by djmj** [comment]
Sorry i forgot to add `toggleId="year"` to `<p:column>`

**Comment by nirodg** [comment]
I'm facing something similar. 
The columnToggler calls the backend and gets the column's position.
```java
public void onToggle(ToggleEvent e) {
     Integer columnIdx = (Integer) e.getData();
}
```

And my column has has defined the visibility column like this (I have a custom component)
`visible="#{dataTableCompBean.getColumnVisibility(tableId, id)}"`
This will get the ID of my column, i.e. myUserId

Would be great to have `e.getClientId() ` so you can get directly the column's id

**Comment by sergi-mm** [comment]
Hello, I'm also interested on a clean solution, but meanwhile I did a workaround for getting the clientId of the toggled column in the toggle event:

```java
Map<String, Boolean> visibleColumns = new HashMap<String,Boolean>();

...

public void toggleColumn(ToggleEvent event){
	if(event.getData() == null || !(event.getData() instanceof Integer) || !(event.getComponent() instanceof ColumnToggler)){
		return;
	}
	Integer index = (Integer)event.getData();
	boolean visible = Visibility.VISIBLE.equals(event.getVisibility());
		
	//Store by name
	ColumnToggler toggler = ((ColumnToggler) event.getComponent());
	UIComponent component = ComponentTraversalUtils.firstWithId(toggler.getDatasource(), FacesContext.getCurrentInstance().getViewRoot());
	if(component == null || !(component instanceof DataTable)){
		return;
	}
	
	DataTable table = (DataTable) component;
	String columnFullId = index >= table.getColumns().size() ? null : table.getColumns().get(index).getClientId();
	if(columnFullId != null){
		String columnId = columnFullId.replace(table.getClientId(), "").replace(":", "");
		visibleColumns.put(columnId, visible);
	}
}
```

Hope this helps!

**Comment by nirodg** [comment]
@sergi-mm I just ended up on a really similar solution. Is not the best, but seems to do the work

**Comment by Rapster** [comment]
You can simply use `Column#field` no?

**Comment by djmj** [comment]
@Rapster That could work and i will give it a try next time. Much better then index for sure.

**Comment by Rapster** [comment]
The proper fix here is IMO to have a `ColumnToggleEvent` having a column attribute, this way users know exactly which column has been toggled

**Comment by melloware** [comment]
in 14.0.0 you will have access to UIColumn with a `ColumnToggleEvent`.

```java
    public void onToggle(ColumnToggleEvent e) {
        Integer index = (Integer) e.getData();
        UIColumn column = e.getColumn();
        Visibility visibility = e.getVisibility();
        String header = column.getAriaHeaderText() != null ? column.getAriaHeaderText() : column.getHeaderText();
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Column " + index + " toggled: " + header + " " + visibility, null);
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
```
