### ISSUE TITLE
ColumnToggler - add attribute to disable client javascript update

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2480]
Currently _ColumnToggler_ uses javascript to hide and show columns. 

If a statefull server side model is used to toggle visibility of columns using `onToggle` ajax event confusing updates can occur.

- First the client javascript updates the table
- Second the ajax request updates the table (which may invoke lazy load and take a second)

The user sees both updates if the server is not fast enough.

**Workaround**

	<script type="text/javascript">
	/*
	 * Disable javascript update in statefull mode by adding css-class 'server' to trigger element
	*/

        //<![CDATA[
        PrimeFaces.widget.ColumnToggler.prototype.check = function(c) 
        {   
			var clientMode = !$(this.trigger).hasClass('server');

            c.addClass("ui-state-active").removeClass("ui-state-hover").children(".ui-chkbox-icon").addClass("ui-icon-check").removeClass("ui-icon-blank");
            var b = $(document.getElementById(c.closest("li.ui-columntoggler-item").data("column"))).index() + 1,
                d = this.thead.children("tr").find("th:nth-child(" + b + ")"),
                a = c.prev().children("input");
            a.prop("checked", true).attr("aria-checked", true);
			
			if (clientMode)
			{
	            d.removeClass("ui-helper-hidden");
	            $(PrimeFaces.escapeClientId(d.attr("id") + "_clone")).removeClass("ui-helper-hidden");
	            this.tbody.children("tr").find("td:nth-child(" + b + ")").removeClass("ui-helper-hidden");
	            this.tfoot.children("tr").find("td:nth-child(" + b + ")").removeClass("ui-helper-hidden");
			}
			
            this.fireToggleEvent(true, (b - 1));

            if (clientMode)
            	this.updateColspan()
        }

        PrimeFaces.widget.ColumnToggler.prototype.uncheck = function(c) 
        {
			var clientMode = !$(this.trigger).hasClass('server');

            c.removeClass("ui-state-active").children(".ui-chkbox-icon").addClass("ui-icon-blank").removeClass("ui-icon-check");
            var b = $(document.getElementById(c.closest("li.ui-columntoggler-item").data("column"))).index() + 1,
                d = this.thead.children("tr").find("th:nth-child(" + b + ")"),
                a = c.prev().children("input");
            a.prop("checked", false).attr("aria-checked", false);

			if (clientMode)
			{
	            d.addClass("ui-helper-hidden");
	            $(PrimeFaces.escapeClientId(d.attr("id") + "_clone")).addClass("ui-helper-hidden");
	            this.tbody.children("tr").find("td:nth-child(" + b + ")").addClass("ui-helper-hidden");
	            this.tfoot.children("tr").find("td:nth-child(" + b + ")").addClass("ui-helper-hidden");
			}
		
            this.fireToggleEvent(false, (b - 1));

            if (clientMode)
            	this.updateColspan()
        }
        //]]>
	</script>

**Comment by tandraschko** [comment]
Please follow our rules and provide every info + samples ;)

**Comment by tandraschko** [comment]
Will close it for now. Please create a new one with all details and examples.

**Comment by djmj** [comment]
I am not sure what to explain here more. In current PF 6.1 there is no ability to disable column toggler client update in favor of own server-side control. I edited the question.
