### ISSUE TITLE
SelectOneButton: trigger change event also on unselect

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primefaces#2483]
**[Update]** My bad. This is about `SelectOneButton`. Sorry!

## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior

Firing an AJAX request upon button unselection.

## 3) Actual behavior

Nothing happens when an already selected button is unselected. I'd like an appropriate AJAX request to be fired as well.
My understanding is that `p:selectOneRadio` already supports the `click` event. Hence, it makes sense to support this functionality in `p:selectOneButton` as well.

**Comment by tandraschko** [comment]
can't you just use the change event?

**Comment by mossaab0** [comment]
I'd love to! But unselecting a button (by clicking on a selected button) fires nothing.

**Comment by tandraschko** [comment]
how can you even unselect it? tried in the showcase but i can't deselect a selected item.

**Comment by mossaab0** [comment]
[Here](https://www.primefaces.org/showcase/ui/input/oneButton.xhtml), I click on `PS4`, it becomes blue (i.e., selected). I click on it again, it becomes white (unselected).

**Comment by mossaab0** [comment]
My bad. This is about `SelectOneButton`. Sorry!

**Comment by tandraschko** [comment]
:D
so i think it would be enough if unselect would also trigger the change event.

**Comment by mossaab0** [comment]
Sure, that should work.

**Comment by jansohn** [comment]
Can this also be included in an elite release?

**Comment by mertsincan** [comment]
Added to elite versions. Thanks a lot!
