### ISSUE TITLE
Duplicates of menu overlay panels at the bottom of <body>

### ISSUE THREAD

**Issue by AndrewShwaika** [primefaces/primefaces#2484]
# Duplicates of menu overlay panels at the bottom of `<body>`

JQuery ID selector in menu.js and overlay.js  is used incorrectly for the removal of duplicates of overlay panels, because the expression $("#id") returns **zero or only one** element. [Spec]( http://api.jquery.com/id-selector/)

The expression **if(this.jq.length > 1)** will never be *true*.

## 1) Environment
- PrimeFaces version: 6.1.2
- Application server + version: Glassfish 4.1.2, Payara 4.1.2
- Affected browsers: All

## 2) Expected behaviour

After update of part of the page containing `<p:menu overlay="true" ...>` element, previous overlay DIV should be replaced by new one

## 3) Actual behaviour

After update of part of the page containing `<p:menu overlay="true" ...>` element, menu overlay panels at the bottom of `<body>` get multiplied.

**Comment by tandraschko** [comment]
Thanks!
