### ISSUE TITLE
ColumnToggler - add server mode

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2491]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version: No since its new feature
- Application server + version: Glassfish 4.1.1
- Affected browsers: All

## 2) Expected behavior

If we use server side visibility model (statefull) to toggle column visibilitly like _visible="#{testBean.isColumnVisible(1)}"_ the client javascript is not responsible anymore for visibility.

A new attribute shall disable client update:

	<p:columnToggler mode="server"/>

## 3) Actual behavior

If a statefull server side model is used to toggle visibility of columns using `onToggle` ajax event confusing updates can occur.

- First the client javascript updates the table immediately
- Second the ajax request updates the table

The user sees both updates if the server is not fast enough to update the table (if lazy load takes a second to load many data). Content of cells may also alter depending on other column visibility states.

## 4) Steps to reproduce

Create a table with stateful column toggler and a long lazy load operation.
Optional make column content dependent on visible columns to make it more visible. Like in below sample.

## 5) Sample XHTML

This markup removes the redundant brand name from the car name column.

	<p:column headerText="Brand" visible="#{bean.isColumnVisible(0)}">

		
		<h:outputText value="#{car.brand}" />

	</p:column>
			 
	<p:column headerText="Name" visible="#{bean.isColumnVisible(1)}">

		
		<h:outputText value="#{car.name}" rendered="#{not bean.isColumnVisible(0) or not car.name.startsWith(car.brand)"}/>

		
		<h:outputText value="#{car.name.replace(car.brand)}" rendered="#{bean.isColumnVisible(0) and car.name.startsWith(car.brand)}"/>

	</p:column>

## 7) Workaround

Use a css-marker class _server_ on trigger component and override javascript of widget.

	<p:commandButton id="btnColToggler" type="button" value="Columns" styleClass="server"/>
	<p:columnToggler datasource="tblCar" trigger="btnColToggler">

	<script type="text/javascript">

		/*
		 * Disable javascript update in statefull server column toggler.
		 */

		//<![CDATA[
		PrimeFaces.widget.ColumnToggler.prototype.check = function(c) 
		{   
			var clientMode = !$(this.trigger).hasClass('server');

			c.addClass("ui-state-active").removeClass("ui-state-hover").children(".ui-chkbox-icon").addClass("ui-icon-check").removeClass("ui-icon-blank");
			var b = $(document.getElementById(c.closest("li.ui-columntoggler-item").data("column"))).index() + 1,
				d = this.thead.children("tr").find("th:nth-child(" + b + ")"),
				a = c.prev().children("input");
			a.prop("checked", true).attr("aria-checked", true);
			
			if (clientMode)
			{
				d.removeClass("ui-helper-hidden");
				$(PrimeFaces.escapeClientId(d.attr("id") + "_clone")).removeClass("ui-helper-hidden");
				this.tbody.children("tr").find("td:nth-child(" + b + ")").removeClass("ui-helper-hidden");
				this.tfoot.children("tr").find("td:nth-child(" + b + ")").removeClass("ui-helper-hidden");
			}
			
			this.fireToggleEvent(true, (b - 1));

			if (clientMode)
				this.updateColspan()
		}

		PrimeFaces.widget.ColumnToggler.prototype.uncheck = function(c) 
		{
			var clientMode = !$(this.trigger).hasClass('server');

			c.removeClass("ui-state-active").children(".ui-chkbox-icon").addClass("ui-icon-blank").removeClass("ui-icon-check");
			var b = $(document.getElementById(c.closest("li.ui-columntoggler-item").data("column"))).index() + 1,
				d = this.thead.children("tr").find("th:nth-child(" + b + ")"),
				a = c.prev().children("input");
			a.prop("checked", false).attr("aria-checked", false);

			if (clientMode)
			{
				d.addClass("ui-helper-hidden");
				$(PrimeFaces.escapeClientId(d.attr("id") + "_clone")).addClass("ui-helper-hidden");
				this.tbody.children("tr").find("td:nth-child(" + b + ")").addClass("ui-helper-hidden");
				this.tfoot.children("tr").find("td:nth-child(" + b + ")").addClass("ui-helper-hidden");
			}
		
			this.fireToggleEvent(false, (b - 1));

			if (clientMode)
				this.updateColspan()
		}
		//]]>
	</script>

**Comment by NOTiFYcouk** [comment]
I believe I have a similar issue. Posted question with description on PF Forum []https://forum.primefaces.org/viewtopic.php?f=3&t=57978(url)

**Comment by melloware** [comment]
@tandraschko @Rapster  Isn't this available now that MVS has `visibleColumns` stored and restored with the MultiViewState?
