### ISSUE TITLE
Toggle all checkbox select hidden checkbox

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2496]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
"Toggle all" should only check visible checkboxes

## 3) Actual behavior
"Toggle all" check all checkboxed (hidden & visible)

## 4) Steps to reproduce
Using this css trick https://forum.primefaces.org/viewtopic.php?f=3&t=14029

## 5) Patch
```javascript
toggleCheckAll: function() {
    if(this.cfg.nativeElements) {
        var checkboxes = this.tbody.find('> tr.ui-datatable-selectable > td.ui-selection-column > :checkbox:visible'),
        // ...
    }
    else {
       var checkboxes = this.tbody.find('> tr.ui-datatable-selectable > td.ui-selection-column .ui-chkbox-box:visible'),
            // ...
    }
```

**Comment by tandraschko** [comment]
A PR would be great :)

**Comment by Rapster** [comment]
See #2501
