### ISSUE TITLE
DataTable: use max-height CSS attribute for scrollHeight

### ISSUE THREAD

**Issue by justin-wesley** [primefaces/primefaces#250]
Instead of using the 'height' CSS attribute for a data table which forces a fixed height, use the max-height attribute which will allow data tables with less data to not take up as much room on the page.

**Comment by kukel** [comment]
uhhh... max-height cannot make your datatable use less space with less rows compared more rows. Or do I miss something (and please use the forum first to discuss possible enhancements.)

**Comment by justin-wesley** [comment]
Here is a link to the [forum thread](http://forum.primefaces.org/viewtopic.php?f=3&t=42088).

**Comment by kukel** [comment]
Using this CSS way makes it possible to use 'vh' as a unit of measure too, beside 'px' and '%'
