### ISSUE TITLE
Suggestion - Add a way to consolidate locales or add the locales to the repo as a raw file

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2504]
Creating a locale js file with all locales currently is a bit complicated as it requires some copy & paste.

Am I missing a better way?

https://github.com/primefaces/primefaces/wiki/Locales

**Comment by tandraschko** [comment]
probably because it's not complete. We may think about it if it's complete. The most locales are missing the validation messages.

**Comment by cnsgithub** [comment]
Better than nothing? You still can omit the validation messages for the start, since probably no one will translate them all, as you can pass your custom validation and required messages anyway with the appropriate component properties (validatorMessage / requiredMessage).

But as for the calendar translations you cannot. So it would be good if that is already integrated into primefaces or there was an easy way to handle it.

It would also be enough to consolidate this wiki page to one single block for easy copy/paste

**Comment by melloware** [comment]
I have updated the en-us example to be a complete example and we can hopefully get others to contribute as well.  The PT-BR example also looks pretty complete.  I think its the best we can and should do for now...
