### ISSUE TITLE
Galleria misses components.css resource dependency

### ISSUE THREAD

**Issue by Mobe91** [primefaces/primefaces#2506]
## 1) Environment
- PrimeFaces version: **6.1**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**

## 2) Actual behavior

`primefaces/src/main/resources-maven-jsf/ui/galleria.xml` does not contain a resource dependency to `components.css`. This results in the `components.css` not being included when no other components are used on the same view that bring in this dependency. A missing components.css results in wrong rendering of the galleria since the `ui-helper-hidden` class is not available.

**Comment by tandraschko** [comment]
A PR would be great!
