### ISSUE TITLE
SelectOneButton: Improve styling

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2510]
Currently ui-state-active is removed on focus and hover - BUT its still active
we should NOT remove the active-state

**Comment by AskIng87** [comment]
Is there any progress with this problem?

If you choose unselectable="false" there is alwasy the problem, that the ui-state-active within the active item will replaced by an ui-state-focus. You have to click outside the element to get the ui-state-active back. Can u fix this problem? If an item is selected an the "unselectable=false" attribute is set, you should remove ui state-active.

**Comment by melloware** [comment]
This fix is included in the upcoming PF 6.2 release.
