### ISSUE TITLE
Checking empty and nullity for String attribute

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2513]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7
- Affected browsers:

## 2) Expected behavior
The need is: if selection attribute is explictally set in my composite, then the selectionMode must be set to 'checkbox'

Here is a sample:
```xml
<c:set name="selectionMode" value="#{not empty cc.getValueExpression('selection') ? 'checkbox' : null}" />
<p:dataTable id="table"
             selectionMode="#{selectionMode}">
</p:dataTable>
```

When the EL is processed `selectionMode="#{selectionMode}"`, even though selectionMode equals null, since `selectionMode` expects a String value, ELSupport.coerceType will transform into an empty string.

What brings me to that problem, SelectionFeature.shouldDecode is called and lead to an exception:
> Multiple selection reference must be an Array or a List for datatable

It tries to decode selection while there is none set. It tries because shouldDecode returns true and that because of `isRowSelectionEnabled()` condition:

```java
public boolean isRowSelectionEnabled() {
    return this.getSelectionMode() != null;
}
```

It should also check if empty (because of ELSupport coerce call) That way, SelectionFeature wont' be decoded. Call `ComponentUtils.isValueBlank`?

## 3) Actual behavior
Selection should not be decoded

**Comment by Rapster** [comment]
https://stackoverflow.com/questions/33334192/tomcat-8-coerce-behaviour-null-strings-are-incorrectly-set-as-empty-strings

**Comment by tandraschko** [comment]
So it's also not fixed in a newer tomcat version?
The problem is probably that it affects alsmost every attribute. So IMO adding the ELResolver to your application is the best way.

**Comment by Rapster** [comment]
I'm using Tomcat 7, custom EL resolver won't solve the problem

**Comment by tandraschko** [comment]
But there is still the coerce flag?

**Comment by tandraschko** [comment]
Jup, just look at the matrix here: http://balusc.omnifaces.org/2015/10/the-empty-string-madness.html

**Comment by Rapster** [comment]
Are talking about this flag: COERCE_TO_ZERO? Because I'm not sure it has an impact on my problem

**Comment by tandraschko** [comment]
Yep, If it's the same root problem
 org.apache.el.parser.COERCE_TO_ZERO
and
the custom ELResolver
should fix it.

**Comment by Rapster** [comment]
Implementation of ValueExpressionImpl of Tomcat 7:

```java
    @Override
    public Object getValue(ELContext context) throws PropertyNotFoundException,
            ELException {
        EvaluationContext ctx = new EvaluationContext(context, this.fnMapper,
                this.varMapper);
        Object value = this.getNode().getValue(ctx);
        if (this.expectedType != null) {
            return ELSupport.coerceToType(value, this.expectedType);
        }
        return value;
    }
```

COERCE_TO_ZERO or custom ELResolver won't do a thing, ELSupport  doesn't even considering `COERCE_TO_ZERO`, and as BalusC mentionned:

> Provide a custom EL resolver like below. Make sure that you use Tomcat 8.0.16 or newer

**Comment by tandraschko** [comment]
Not sure, the matrix says something different.
I didn't try those settings and ELResolvers yet. But i'm sure there is a workaround.

IMO we should not fix such weird bugs.
We must fix tons of places in your code to correctly handle this - just because the EL does something not expected, which is already fixed in the glassfish EL.

**Comment by Rapster** [comment]
I agree, but in the future, instead of only testing null, it would be better to test empty strings as well since the problem is known

**Comment by tandraschko** [comment]
yep but hopefully such problems won't occur in the future :D

**Comment by Rapster** [comment]
Not sure about that, even with the last implementation you still need to work around this problem. So I guess, it's still a problem Primefaces user might encouter again

**Comment by tandraschko** [comment]
Lets close it for now. We just have to keep that in mind.

**Comment by Rapster** [comment]
Mmmmh why not labelling it into `Enhancement`, I think from now on we have to stop doing nullity test with strings but use `LangUtils.isValueBlank()`. We are facing too many problems due to this

**Comment by tandraschko** [comment]
If you really work on this and do a mass-replace, we can leave it open. (but please after the release)
Otherwise it will stay open for ages probably and noone works on it.

**Comment by Rapster** [comment]
I'll have a look after release, too busy right now. You can leave it close, I'll open it once I'll work on it
