### ISSUE TITLE
DataTable: cellEditInit event - cellEditMode=lazy 

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#2514]
https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml shows correctly the old/new value for a cellEdit event in the second table. However, an additional `<p:ajax event="cellEditInit" listener="#{dtEditView.onCellEditInit}" />` does not activate *onCellEditInit*, while the User Guide simply says "when a cell edit begins" (first bug). After looking into sources, I discovered, that setting `cellEditMode="lazy"` causes *onCellEditInit* to be called. So second bug is, that this is not documented (but it shouldn't work like this either!). Unfortunately, the lazy mode changes *onCellEdit* to have same value for *event.getOldValue()* and *event.getNewValue()* (third bug). Is there any workaround that enables *init* and *edit* event?
## 1) Environment
PF 6.1, 6.2-SNAPSHOT 
## 2) Expected behavior
All three bugs should be fixed.
## 3) Actual behavior
Described above
## 4) Steps to reproduce
Described above
## 5) Sample XHTML
Referenced above
## 6) Sample bean
Add following method to EditView.java:
 `public void onCellEditInit(CellEditEvent event) { System.out.println("onCellEditInit"); }`

**Comment by melloware** [comment]
PR: https://github.com/primefaces/primefaces/pull/5120
