### ISSUE TITLE
Captcha not compatible with context param javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL

### ISSUE THREAD

**Issue by JohnSchneider** [primefaces/primefaces#2515]
## 1) Environment
- PrimeFaces version: 6.1.0, 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.  Tested with 6.2-SNAPSHOT as of 2017-07-08.
- Application server + version:  JBoss EAP 7.0.3 (based on Wildfly 10.0)
- Affected browsers: All

## 2) Expected behavior
When a user does not complete the reCAPTCHA, an error should be displayed, even if context param javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL is set to true.

## 3) Actual behavior
Please consider this an enhancement request and not a bug. My apps always use context param javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL.  This context param causes the "value" parameter of method org.primefaces.component.captcha.Captch.createPostParameters to be null instead of an empty string. Line 216 (below) then fails with a NullPointerException, as java.net.URLEncoder.encode doesn't support null values.
`postParams.append("&response=").append(URLEncoder.encode((String) value, "UTF-8"));`

## 4) Steps to reproduce
1. Deploy an app with context param javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL set to true
2. Submit a form with p:captcha without completing the reCaptcha

## 5) Sample XHTML
`<p:growl />
<p:captcha label="reCAPTCHA"/>
<p:commandButton value="Check" actionListener="#{captchaView.submit}" ajax="false" icon="ui-icon-check"/>`

## 6) Sample bean
`public class CaptchaView {
     
    public void submit() {
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Correct", "Correct");
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
}`

**Comment by tandraschko** [comment]
Thanks for the PR!
