### ISSUE TITLE
DataTable doesn't set selection to backend controller when clientCache=true

### ISSUE THREAD

**Issue by xtron** [primefaces/primefaces#2519]
`
<p:dataTable id="appUserTable" clientCache="true"
                         binding="#{appUserTable}"
                         var="user" 
                         value="#{appUserController.lazyItems}"
                         paginator="true" 
                         rows="10"
                         sortOrder="descending"
                         sortBy="#{user.id}"
                         rowKey="#{user.id}"
                         widgetVar="appUserTable"
                         emptyMessage="#{msg.EmptyMessage}"
                         paginatorTemplate="#{msg.PaginatorLazyTemplate}"
                         currentPageReportTemplate="#{msg.CurrentPageCommonTemplate}"
                         rowsPerPageTemplate="10,30,50"
                         selectionMode="single"
                         selection="#{appUserController.selected}"
                         lazy="true">
          <p:ajax event="rowSelect"  update=":tabs:AppUserListForm:control"/>
          <p:ajax event="rowUnselect" update=":tabs:AppUserListForm:control"/>
`

When i select row, rowSelect event fire, but in method appUserController.setSelected i got selected=null.
When clientCache="false" all is ok.
`
public void setSelected(E selected) {   //Here is selected=null when clientCache=true
        this.selected = selected;
}
`

**Comment by xtron** [comment]
PrimeFaces 6.1

**Comment by tandraschko** [comment]
Please follow our issue template next time if you open a issue.
Will close it as invalid as it misses many informations and code.
