### ISSUE TITLE
autoComplete show search result even if empty

### ISSUE THREAD

**Issue by sachafournier** [primefaces/primefaces#2520]
## 1) Environment
- PrimeFaces version: 6.0.19 (and above)
- Application server + version: JBoss AP6.1
- Affected browsers: Chrome

## 2) Expected behavior

Display nothing

## 3) Actual behavior

Display a list of items based on last deleted character

## 4) Steps to reproduce
Using latest Showcase (Autocomplete/Delay(1000))
- Enter some characters. Wait for result
- Backspace until all character deleted
- Even if all characters are deleted within 1000ms, a list of found items is shown using latest deleted char.

**Comment by tandraschko** [comment]
Would be great if you could provide a PR.
