### ISSUE TITLE
Prevent double click on UICommand components

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2521]
This topic is quite recurrent, would it be possible to integrate a solution in PF?

https://stackoverflow.com/questions/10756426/how-to-do-double-click-prevention-in-jsf-2
http://ovaraksin.blogspot.fr/2011/05/prevent-multiple-clicks-in-jsf.html

Components:
- CommandButton
- CommandLink
- MenuItem
- SplitButton
- HotKey

**Comment by melloware** [comment]
+1 for this.  We have struggled to prevent users from double clicking buttons and no solution has seemed quite right for us.  A native PF solution would be fantastic.  We have tried a few different things but they all have their quirks.  I may give the solution above a chance.

**Comment by tandraschko** [comment]
-1 as there are many solutions and none of them is easy or perfect
the easiest way is a ajaxStatus modal overlay, which prevents everything till the ajax request is finished

**Comment by cristiandean** [comment]
I used the BlockUI component to solve the problem ( #2039 )

Available at: https://www.primefaces.org/showcase/ui/misc/blockUI.xhtml

**Comment by Rapster** [comment]
@tandraschko I'm using ajaxStatus as well, but if there is a defaultCommand to it, it won't prevent the double submission

@cristiandean it means define a blockUI on each page...

**Comment by cristiandean** [comment]
@Rapster I actually define it in my template, to avoid repetition. It was the solution I found until the problem was fixed once and for all.

**Comment by Rapster** [comment]
@cristiandean how did you define trigger attribute then? Does it work for all the buttons you have in your app?

**Comment by cristiandean** [comment]
It's easy, just use a class on all the buttons you want to lock the screen.

`  <p:panel id="pnl" header="New User" style="margin-bottom:10px;">
            <p:blockUI block="pnl" trigger="@(.mybutton)"/>
            <p:commandButton id="saveBtn" styleClass="mybutton"
                             actionListener="#{indexController.methos()}"
                             icon="ui-icon-check"
                             value="Save"></p:commandButton>
            <p:commandButton id="saveBtn2" styleClass="mybutton"
                             actionListener="#{indexController.someMethod()}"
                             icon="ui-icon-check"
                             value="Save2"></p:commandButton>
        </p:panel>`

**Comment by Rapster** [comment]
Ah I see using SEF ;-)

**Comment by cristiandean** [comment]
It would be nice if a native solution were implemented, something like blockAfterClick or preventDoubleCkick in the commandButtons. I know this is not the ideal solution, but it was the most interesting I found. (:

**Comment by avinashmoram** [comment]
+1 A native PF solution would be helpful

**Comment by Rapster** [comment]
Might help http://deltaspike.apache.org/documentation/jsf.html#Double-SubmitPrevention

**Comment by tandraschko** [comment]
\<ds:preventDoubleSubmit/\> is something completely different.
Ajax requests are queued per default, but non-ajax are not queued.
So DS just "ignores" the second click and skips the JSF lifecycle. This also only works for non-ajax.

**Comment by tandraschko** [comment]
And yep, the docu is not quite big here. We added this some years ago just as a small helper, i'm even not sure if someone uses it. Also the most interaction nowadays is using ajax.

**Comment by milikicn** [comment]
+1

**Comment by ravihariharan** [comment]
@tandraschko  / @melloware  / @Rapster 

How about the solution from Jasper de Vries ?

https://stackoverflow.com/questions/6482443/how-to-avoid-repeatedly-click-a-button-in-a-form/57609865#57609865

**Comment by ravihariharan** [comment]
> ajaxStatus

We encountered an issue when a long running process was being processed in the application server and the HTTP server timeout.   This seemed to have caused the ajaxStatus  to stop thereby allowing the user to re-submit. We are still investigating the issue and trying to figure a solution one possible approach is to disable button on client.

**Comment by jepsar** [comment]
@ravihariharan please note that I've updated the SO answer with an `isConfirmation` check.

**Comment by melloware** [comment]
@jepsar Why not make that a PrimeFaces Extension?   Then if people want to use it all they have to do is...
```xml
<render-kit>
  <renderer>
    <component-family>org.primefaces.component</component-family>
    <renderer-type>org.primefaces.component.CommandButtonRenderer</renderer-type>
    <renderer-class>org.primefaces.extensions.CommandButtonSingleClickRenderer</renderer-class>
  </renderer>
</render-kit>
```

**Comment by jepsar** [comment]
@melloware great idea. I'll add it.

**Comment by melloware** [comment]
Probably can create a CommandLinkRenderer too!

**Comment by Rapster** [comment]
BTW, why putting that in PFE and not PF?

**Comment by melloware** [comment]
Well PFE we can control, PF not sure this is a feature PrimeTek would want in and Thomas didn't seem too impressed by this need.  So PFE is always a good place to sandbox things like this!

**Comment by Rapster** [comment]
Fair enough, makes sense then :wink: But ideally, PF would have been great

**Comment by melloware** [comment]
Closing this ticket for now as we are going to incubate the feature in PrimeFaces Extensions as mentioned above.  It if does well it can always be migrated to PF in the future.  Thanks for the contribution @jepsar

**Comment by jepsar** [comment]
Posting a link to the PFE showcase in cause someone stumbles upon this issue: https://www.primefaces.org/showcase-ext/sections/renderers/commandButtonSingleClick.jsf
