### ISSUE TITLE
Avoid unnecessarily computing fileUpload's allowTypes twice

### ISSUE THREAD

**Issue by brunoabdon** [primefaces/primefaces#2522]
Method `encodeScript()` on class `org.primefaces.component.fileupload.FileUploadRenderer` shouldn't call call `fileUpload.getAllowTypes()` twice. It could use a temporary variable.

Around line 100:

```
if (fileUpload.getAllowTypes() != null) {
       wb.append(",allowTypes:").append(fileUpload.getAllowTypes());
}
```
In my application, the database is queried to determine the "_allowed type_", what makes this double call a little cumbersome.
## 1) Environment
- PrimeFaces version: 6.0
- Application server + version: Any
- Affected browsers: Any
## 2) Expected behavior
The value of the expression for the "'allowTypes''" attribute of the '<p:fileUpload>' component 
should be computed only once per rendering.
...
## 3) Actual behavior
The value of the expression for the "'allowTypes''" attribute of the '<p:fileUpload>' component is computed twice.
..

## 4) Steps to reproduce
Render a page with a  '<p:fileUpload>' component.
.. 
## 5) Sample XHTML
```
<h:form enctype="multipart/form-data">
    <p:fileUpload value="#{fileUploadView.file}" allowTypes="#{fileUploadView.allowTypes}"/>
</h:form>
```
## 6) Sample bean
```
package org.primefaces.showcase.view.file;
 
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
 
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
 
@ManagedBean
public class FileUploadView {
     
    private UploadedFile file;
 
    public UploadedFile getFile() {
        return file;
    }
 
    public void setFile(UploadedFile file) {
        this.file = file;
    }
    public String getAllowTypes(){
         String allowTypes = "(txt|pdf)"//actually, do heavy computation / IO
         return allowTypes;
    }
}
```
..

**Comment by tandraschko** [comment]
JFYI: one of the best practices when using JSF is to avoid logic in getter and setter ;)

**Comment by brunoabdon** [comment]
> JFYI: one of the best practices when using JSF is to avoid logic in getter and setter ;)

Will carefully think about it. Fact is that, in my case, the "allowed type" varies accordingly with the logged in user's mutable, database stored, preferences. But this discussion better suits stackoverflow....
