### ISSUE TITLE
DefaultCommand not triggered if scope equals event.target

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#2536]
Tested with PrimeFaces 6.0 and 6.1.

Expected: 
Scope is set to inputText, Target is set to a commandLink. When I hit enter inside the inputText the commandLink should be executed.

Actual:
Nothing happens. I have to set the scope to the parent widget of the inputText (in my case a p:panel).

The root cause: 
Line 24 of forms.defaultcommand.js as it uses $.find to test if the event.target is a child of the scope. It never tests if event.target is the scope itself.

```($this.scope && $this.scope.find(e.target).length == 0)``` should be changed to something like ```($this.scope && $this.scope.find(e.target).length == 0 && this.scope.get(0) != e.target)```

**Comment by tandraschko** [comment]
Please provide the example like mentioned in the issue template ;)

**Comment by fanste** [comment]
<p:panel id="pnlSearch" header="Test">
        <p:inputText value="#{searchBean.query}" id="itSearch" required="true" />
        <p:commandLink id="lnkSearch" title="#{app['app.ext.solr.search']}"
            actionListener="#{searchBean.doPerformSearch}" process="@this itSearch"><i class="fa fa-search"></i></p:commandLink>
			
        <p:defaultCommand target="lnkSearch" scope="itSearch" />
    </p:panel>

**Comment by tandraschko** [comment]
Please provide a full example which is runnable by me (the Bean code and stuff like pnlSearchState is missing)

**Comment by fanste** [comment]
Sorry, but this is ridiculous. Neither the bean nor the other things have something to to with the problem. But here you go. 

    import javax.inject.Named;
    import javax.faces.view.ViewScoped;
    
    @Named
    @ViewScoped
    public void SearchBean implement Serializable {
        private String query;


        public void doPerformSearch() {
            System.out.println("Just a message, so you can see that there is nothing ;)");
        }

        public String getQuery() {
            return this.query;
        }

        public void setQuery(String query) {
            this.query = query;
        }
    }

But I won't provide a final WAR file as it is not required for a fix and I do not have the time to provide one during my working time (and I do not have the infrastructure at home). You know what and where the error is. And either the functionality should be as it is currently implemented or it is not working as it was intended.

Either fix it or close the issue. I can fix it myself for the projects.

**Comment by tandraschko** [comment]
Thanks for the example but thats not ridiculous ;)
We can't fix something without replecating it and testing it. Therefore we need a example.
Of course we could prepare a example by ourself but thats effort and you already have an example, where it doesn't work.
