### ISSUE TITLE
DialogFramework is locked when a widget is defined using required="true"

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#2538]
Hello,

I use a DialogFramework since more than 2 years, and since I have added a required="true" widget, this DialogFramework has stopped to work.

When DialogFramework is loaded and when I click a SAVE Button to save my work the program do NOTHING.

When required="false" the program work correctly.

This problem only occurs when input field is empty.

I think that when I press the SAVE Button, Primefaces Javascript detect the empty value and will display or display a warning message that I don't see.

I don't know if the message is displayed or not, I don't know if the message is behind my DialogFramework or not.

## 1) Environment
- PrimeFaces version: 6.1.1
- Affected browsers: Chrome

## 2) Expected behavior

I expect that the browser displays a warning message saying that the widget is empty.

## 3) Actual behavior

The browser display nothing !

## 4) Steps to reproduce

Define a required="true" widget in a DialogFramework, let it empty and press a SUBMIT button.
Normally, nothing is sent to server but no warning message are displayed on browser.

**Comment by tandraschko** [comment]
Probably the you don't have a messages tag in your dialog view.
But we can't help without any example.

**Comment by schlebe** [comment]
yes, you have right, all the forms in application have a &lt;growl&gt; widget but the DialogFramework have not this widget.
You have found the reason but, personnaly I have lost a lot of time to solve this problem and I think that it will be interesting to display an alert when this case occurs to advise user/tester of the problem !

I click on SAVE (SUBMIT) button and nothing happens, no message on server, no message on browser console and no message on screen. 
If nothing is done, another user will post the same question another day.

**Comment by tandraschko** [comment]
In MyFaces and in development stage, MyFaces logs something like "Hey Developer, there are unrendered messages. There must be something wrong in your code".

**Comment by schlebe** [comment]
I will not migrate from Primefaces to MyFaces but what you write about advising functionality of Myfaces is certainly what is missing to Primefaces !

When a Primefaces widget (required="true") and the value in it is empty it is a good thing to warn the user/developper about this problem.

In fact, when widget is empty, it must advise user about this problem and it must search another widget to display a warning message. If it found nothing, the user/developper must be alerted.

It is very simple to understand and certainly to implement.

Not defining a &lt;messages&gt; or &lt;growl&gt; is certainly a developper's bug. 
But not helping developper to find this bug before that an error occurs in production application is certainly a missing feature in the development tools.

Don't forget that if this feature is implemented it will also be used for other validation like verifying that an number is lower then 12 or greater than 0.

**Comment by tandraschko** [comment]
I would create a feature request in Mojarra. Maybe it's already available there, i didn't used it since years. NOTE: it would only show when ProjectStage=Development.
