### ISSUE TITLE
Not able to add more than 490 elemnst in <p:picklist>

### ISSUE THREAD

**Issue by mariaarora** [primefaces/primefaces#2543]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:Chrome and Mozilla

## 2) Expected behavior
<p:picklist> should accept all the elements
...

## 3) Actual behavior
<p:picklist> is not accepting more than 490 elements
..

## 4) Steps to reproduce
Add more than 490 elements to be added in <p:picklist>.
It will not accept it
.. 

## 5) Sample XHTML
<p:pickList id="pickList" value="#{pickListView.cities}" var="cities" itemLabel="#{cities}" itemValue="#{cities}" />
..

## 6) Sample bean
public class PickListView {
     
    @ManagedProperty("#{themeService}")
    private ThemeService service;
     
    private DualListModel<String> cities;
    private DualListModel<Theme> themes;
     
    @PostConstruct
    public void init() {
        //Cities
        List<String> citiesSource = new ArrayList<String>();
        List<String> citiesTarget = new ArrayList<String>();
         
        citiesSource.add("San Francisco");
        citiesSource.add("London");
        citiesSource.add("Paris");
        citiesSource.add("Istanbul");
        citiesSource.add("Berlin");
        citiesSource.add("Barcelona");
        citiesSource.add("Rome");
//add 490 elements
         
        cities = new DualListModel<String>(citiesSource, citiesTarget);
         
        //Themes
        List<Theme> themesSource = service.getThemes().subList(0, 5);
..

**Comment by tandraschko** [comment]
Works fine for me when running the showcase locally with:

`        for (int i = 0; i < 100; i++)
        {
            citiesSource.add("San Francisco " + i);
            citiesSource.add("London " + i);
            citiesSource.add("Paris " + i);
            citiesSource.add("Istanbul " + i);
            citiesSource.add("Berlin " + i);
            citiesSource.add("Barcelona " + i);
            citiesSource.add("Rome " + i);
        }`

**Comment by mariaarora** [comment]
did u try by adding exactly more than 490 elements??

**Comment by tandraschko** [comment]
The loop above results in 700 elements.
What doesn't work for you?

**Comment by mariaarora** [comment]
I tried the loop for 970 elements.
It is not working beyond that

xhtml:
   <p:pickList value="#{pickListView.deviceListSource}"
							var="picklist" itemLabel="#{picklist.displayName}"
							itemValue="#{picklist}" styleClass="Wid30"
							showSourceFilter="true" showTargetFilter="true"
							converter="entityConverter" id="picklistMonitor"
							filterMatchMode="contains">
			                              </p:pickList>

Bean Class:
for(int testdevice=1000;testdevice<=1970;testdevice++)
		{
			DeviceVO testobj=new DeviceVO();
			testobj.setDeviceid(testdevice);
			testobj.setEnterprise("airtel");
			testobj.setIpaddress("10.1.8.3");
			deviceListSource.add(testobj);
		}
