### ISSUE TITLE
<p:selectonemenu> auto alignment

### ISSUE THREAD

**Issue by mariaarora** [primefaces/primefaces#2544]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:6.1
- Does it work on the newest released PrimeFaces version? Version?No
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: chrome + Mozilla

## 2) Expected behavior
Primefaces <p:selectonemenu> width is not auto-aligned across entire application.
We have to add styleclass everywhere.
...

## 3) Actual behavior
Primefaces <p:selectonemenu> width should be auto-aligned across entire application
..

## 4) Steps to reproduce
Create a  <p:selectOneMenu>
Its width should be auto-aligned. 
.. 

## 5) Sample XHTML
    <p:selectOneMenu id="console" value=" " >
            <f:selectItem itemLabel="Select One" itemValue="" />
            <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
            <f:selectItem itemLabel="PS4" itemValue="PS4" />
            <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
        </p:selectOneMenu>
..

## 6) Sample bean
NA
..

**Comment by tandraschko** [comment]
autoWidth attribute of selectOneMenu is true per default. So i don't understand your issue.
You can also directly overwrite the ui-selectonemenu style instead of adding a styleClass to each one.
