### ISSUE TITLE
QuillJS 1.3.0

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#2548]
https://github.com/quilljs/quill/releases/tag/v1.3.0

**Comment by Rapster** [comment]
It looks like you're the QuillJS PF reporter, please provide a PR, I'm sure you'll see this issue soon if you do

**Comment by jxmai** [comment]
I am using quill too, so I can take a look at this one.

**Comment by tandraschko** [comment]
Thanks!

**Comment by jxmai** [comment]
Causing regression #2802
