### ISSUE TITLE
Upload button cannot be enabled due to  JS exception ($this.isCanvasSupported is not a function)

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#2552]
## 1) Environment
- PrimeFaces version: Primeface latest trunk (up to 4277d8111b46c7f07c80cf7146237450f4a7c893)
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 8.0.20
- Affected browsers: All

## 2) Expected behavior

File upload should work normally

## 3) Actual behavior

File upload is broken completely 

## 4) Steps to reproduce

Just choose any file but you won't be able to upload the file

## 5) Sample XHTML

```xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body>
	<h:form>
		<p:fileUpload fileUploadListener="#{fileUploadView.handleFileUpload}"
			mode="advanced" dragDropSupport="false" update="messages"
				fileLimit="3" />

		<p:growl id="messages" showDetail="true" />
	</h:form>
</h:body>

</html>

```

## 6) Sample bean

```java
package com.test;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;

import org.primefaces.event.FileUploadEvent;

@ManagedBean
public class FileUploadView {

    public void handleFileUpload(FileUploadEvent event) {
	FacesMessage message = new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded.");
	FacesContext.getCurrentInstance().addMessage(null, message);
    }
}
```

Browser stacktrace's screenshot:

![image](https://user-images.githubusercontent.com/10467831/28346258-655c9b12-6bf5-11e7-8b22-d557daba7c76.png)

## 6) My thought

I wonder if this issue might be related to `fileupload.js`, and I took a look at the history of that js file through this: https://github.com/primefaces/primefaces/commits/master/src/main/resources/META-INF/resources/primefaces/fileupload/fileupload.js

The most suspicious commit is https://github.com/primefaces/primefaces/commit/173154968bc98427a8d7a1296f55ef5705daf199#diff-4be31ec9a4643306b0b332f62a4fda77

and by looking at this line https://github.com/primefaces/primefaces/commit/173154968bc98427a8d7a1296f55ef5705daf199#diff-782473a356ee4ce112d5342c77c18ffbL20932

![image](https://user-images.githubusercontent.com/10467831/28346606-a97e9d20-6bf7-11e7-9e1e-9eb2ee80cf4e.png)

you can see `$this.isCanvasSupported` has been removed since then.

@tandraschko Please take a look :)

Maybe you should recover the following lines of code

![image](https://user-images.githubusercontent.com/10467831/28347418-8defe17c-6bfc-11e7-838b-6e575816ed8c.png)

**Comment by tandraschko** [comment]
As we don't support IE8 anymore, canvas should be supported on all browsers (hopefully :D), so i just removed the statement from the IF block.
