### ISSUE TITLE
NPE during export of empty cells to XML (FIX)

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#2554]
## 1) Environment
- PrimeFaces version: 6.1.3
- Application server + version: Glassfish 4.1.1
- Affected browsers: all

## 2) Expected behavior
Xml File is generated

## 3) Actual behavior
NullPointerException is thrown:

```
java.lang.NullPointerException
at java.io.PrintWriter.write(PrintWriter.java:473)
at org.primefaces.component.export.XMLExporter.addColumnValue(XMLExporter.java:135)
at org.primefaces.component.export.XMLExporter.exportCells(XMLExporter.java:94)
at org.primefaces.component.export.Exporter.exportRow(Exporter.java:265)
at org.primefaces.component.export.Exporter.exportAll(Exporter.java:239)
at org.primefaces.component.export.XMLExporter.export(XMLExporter.java:52)
at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:134)
```

..

## 4) Steps to reproduce
**Update:**
Create Datatable with an cell, that as a outputText with a converter that returns null as value. Export to XML.

Pseude code, but should explain the problem in the Exporter.exportValue Method the actual value to render is calculated. In most cases this returns an empty string if no value can be found, with the exception of a assigned custom Converter. If I define a converter that in some cases returns a null value this null value will be returned by the exportValue method with results in the according NPE later on. Since a null value is a valid result for a converter this should be fixed in the XMLExporter.

NullValueConverter is a CustomConverter that returns null in its getAsString (for the purpose of this pseudo example)
```
<p:column>
<h:outputText value#{item.value}" converter"NullValueConverter" />
</p:column>

```
Fix: Check for null value during export the same way the XLS and CSV Exporter do, they both work fine with the same data. See PullRequest: https://github.com/primefaces/primefaces/pull/2553 for easy fix.

**Comment by mertsincan** [comment]
I couldn't replicate this issue. I didn't see NPE error. Could you please attach a sample code for us to replicate?

**Comment by gako** [comment]
Ok it is a little bit more complicated to replicate but I was able to pinpoint the exact conditions for the null value. See description above.

**Comment by tandraschko** [comment]
IMO the null check also doesn't hurt. Will merge it.

**Comment by tandraschko** [comment]
@mertsincan if you would like to merge it to elite, freel free :)
