### ISSUE TITLE
SelectOneMenu not working after client side disable/enable

### ISSUE THREAD

**Issue by AlexR-dev** [primefaces/primefaces#2555]
## 1) Environment
PrimeFaces version: 6.1.2

## 2) Expected behavior
After disabling and enabling a SelectOneMenu on client side via JavaScript it should work as before.

## 3) Actual behavior
When disabling a SelectOneMenu via JavaScript and enabling it again, mouse events (mouse over, click) on the menu's item are not working anymore.

## 4) Sample XHTML
...
<p:selectOneMenu widgetVar="selectOneMenu" ...>
...
JavaScript:
PF('selectOneMenu').disable();
...
PF('selectOneMenu').enable();

## 5) Analyses
Binding of item's events has been moved out of the bindEvents method to a separate method bindItemEvents, but this isn't called in the enable method.

**Comment by tandraschko** [comment]
@mertsincan can you review please and port to elite?

**Comment by mertsincan** [comment]
Thanks a lot, @tandraschko ;)
