### ISSUE TITLE
How to change the currentPageReportTemplate= {startRecord} and {endRecord} data with comma separator (for e.g: 1000 into 1,000 or 1000000 to 1,000,000)

### ISSUE THREAD

**Issue by uditrpanchal** [primefaces/primefaces#2557]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

...  1 of 4,326

## 3) Actual behavior

..   1 of 4326

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..   currentPageReportTemplate=" {startRecord} - {endRecord}  of {totalRecords}

## 6) Sample bean

..

**Comment by tandraschko** [comment]
questions -> forum
