### ISSUE TITLE
PrimeFaces Mobile pm:page Life Cycle Events (Such as OnLoad)

### ISSUE THREAD

**Issue by kwrobel** [primefaces/primefaces#256]
Hi. I'd like to submit a feature request for adding life cycle events to PrimeFaces Mobile pm:page tag. It would be very beneficial if something like an "onload" or "ondisplay" event would be available on a PrimeFaces Mobile pm:page so that an application can do some processing before or after a page is being displayed. Maybe the timing could be sorted out as well so that something could happen "preload" or "postload", something along those lines.

Can it be done?

**Comment by tandraschko** [comment]
PrimeFaces Mobile will be deprecated  in 6.2 and removed in 6.3 ( see https://www.primefaces.org/primefaces-6-2-roadmap/)
Therefor i will close this issue as won't fix. If you will provide a PR to fix this issue until 6.2 RC1, i can merge it.
