### ISSUE TITLE
DataTable: Navigation using CommadButton in sorted and paginated DataTable causes page re-render

### ISSUE THREAD

**Issue by AlesHal** [primefaces/primefaces#2563]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? Yes
- Application server + version: IBM Websphere Portal Server 8.5 (resp. IBM Websphere Application Server 8.5)
- Affected browsers: All

## 2) Expected behavior
In datatable where pagination and sorting is used with commandLink or commandButton on each row, after clicking on the link (or button) to show detail of desired row (using action method in backing bean) user should be navigated to specified different page.

## 3) Actual behavior
After several specific steps (clicks) user is not navigated to detail page, but the current page (with datatable) is re-rendered. If user clicks the commandLink again after re-render, then he will be forwarded to detail page finally.

## 4) Steps to reproduce

- In the paginated datatable go to the second page.
- Sort the table by one of the columns - the first page of the table is shown
- Click the commandLink (commandButton) on one the rows - the page is re-rendered instead of forwarding to the detail page

## 5) Sample XHTML

```
<p:dataTable id="tablePersons" styleClass="dataTable" var="dto" rowIndexVar="rowIndex" value="#{listBean.model}"
	first="#{listBean.model.first}" rows="#{listBean.model.pageSize}" lazy="true" paginator="true" paginatorPosition="bottom"
	paginatorTemplate="{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {CurrentPageReport} {RowsPerPageDropdown}"
	multiViewState="false" emptyMessage="No records" reflow="true">

	<p:column headerText="#" styleClass="rightAlign">
		<h:outputText value="#{rowIndex + 1}."/>
	</p:column>

	<p:column headerText="Given name" sortBy="#{GIVEN_NAME}">
		<h:outputText value="#{dto.givenName}"/>
	</p:column>

	<p:column headerText="Family name" sortBy="#{FAMILY_NAME}">
		<h:outputText value="#{dto.familyName}"/>
	</p:column>

	<p:column headerText="E-mail">
		<h:outputText value="#{dto.email}"/>
	</p:column>

	<p:column headerText="Company">
		<h:outputText value="#{dto.company}" sortBy="#{COMPANY}">
	</p:column>

	<p:column>
		<p:commandButton title="Show detail" ajax="false" partialSubmit="true"
			value="Detail" action="#{listBean.showDetail}"/>
	</p:column>

</p:dataTable>
```

## 6) Sample bean

```
public class PersonListBean implements Serializable {

  private LazyDataModel<PersonListDTO> model;

  public LazyDataModel<PersonListDTO> getModel() {
    if (model == null) {
      model = new LazyDataModel<PersonListDTO>() {
          public List<PersonListDTO> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters) {
            // getting data using given arguments
          }
      };
    }
    return model;
  }

  public Datatable getTablePerson() {
    // getting datatable UI component
  }

  public PersonDetailBean getPersonDetailBean() {
    // getting backing Java bean of person detail page
  }

  public String showDetail() {
    PersonDetailBean detailBean = getPersonDetailBean();
    detailBean.reset();
    detailBean.setData(getTablePersons().getRowData());

    return "DETAIL";
  }

}
```

**Comment by tandraschko** [comment]
Please provide a runnable example, otherwise it will be closed as invalid.
You can easily reuse beans/models from the showcase.
