### ISSUE TITLE
DataTable: issue with editable paginated datatable

### ISSUE THREAD

**Issue by jeffcapo** [primefaces/primefaces#2565]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 5.1
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: chrome, firefox, ie

## 2) Expected behavior
When creating a datatable with paginator="true" you can initialize the number of rows with rows="5".  Then you can also edit cells in that table with cellEditor or just plain input text for any row.
...

## 3) Actual behavior
When you try to update a managed bean for a row in a dataTable if the rowIndex is greater than rows (for example, if rows="5" and you are editing row 6) it seems that ajax calls are not triggered.
..

## 4) Steps to reproduce
create a dataTable with paginator and rows attributes.  Make some cells filled with inputText elements.  You will see that the second page worth of rows cannot be changed.  However, once you remove the 'rows' attribute you can update any row.
.. 

## 5) Sample XHTML
	<p:dataTable id="elementTable"
						value="#{controller.elements}" widgetVar="elementTable"
						tableStyle="width:auto" 
						border="1" 
						var="e" 
						paginator="true"
						paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
						rowsPerPageTemplate=",5,10,25,50,100,200"
 						editable="true" 
 						editMode="cell"
 						rowIndexVar="rowIndex"
 						filteredValue="#{dafController.daf.filteredElements}">
						<p:column headerText="#">
							<h:outputText value="#{rowIndex+1}" />
						</p:column>
						<p:column headerText="Technical Element Name"
							sortBy="#{e.technichalElementName}"
							filterBy="#{e.technichalElementName}" filterMatchMode="contains">
							<p:inputText value="#{e.name}" />
						</p:column>
</p:dataTable>

..

## 6) Sample bean
@ManagedBean(eager = true)
@SessionScoped
@Controller
public class Controller implements Serializable, ApplicationContextAware{

private List<Element> elements;

public List<Element> getElements() {
		return elements;
	}

	public void setDafProjects(List<Element> elements) {
		this.elements= elements;
	}

..

**Comment by tandraschko** [comment]
Please provide a full runnable example - you can easily reuse the beans/models from the showcase. Otherwise it's hard to reproduce it.
