### ISSUE TITLE
Multiple ActionListeners For p:menuitem

### ISSUE THREAD

**Issue by kwrobel** [primefaces/primefaces#257]
I don't know if this is a defect or a feature request, but I'd like to be able to attach multiple action listeners to a p:menuitem. This is already possible with p:commandbutton, which I've tested in my application.

I'm imagining something like this:

```
<p:menuitem value="My Menu Item" icon="ui-icon-search" update=":MyTestEditPage:MyEditForm" action="#{someBean.outcome}">
    <f:actionListener binding="#{myViewScopedController.someActionListener}"/>
    <f:actionListener binding="#{mySessionScopedController.someOtherActionListener}"/>
</p:menuitem>
```

Can it be done?

**Comment by cagataycivici** [comment]
MenuItem extends from UICommand so why not. This is a better fit for a forum post.

**Comment by kwrobel** [comment]
Doesn't seem to work. I did post in forum, but it went unanswered. Even a single <f:actionListener> tag does not work. Only if I put the actionListener attribute inside the p:menuitem does the listener get called. Obvously that limits me to one listener.

**Comment by kwrobel** [comment]
Ok. It's not a defect but user error on my part. Sorry. p:menuitem does in fact support multiple action listeners. I now know why it didn't work for me. See [PrimeFaces Forum](http://forum.primefaces.org/viewtopic.php?f=8&t=42084).
