### ISSUE TITLE
Datatable: get/setWrappedData inconsistent code

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2570]
Having a look at LazyDataModel.java, I saw this:
```java
	public Object getWrappedData() {
		return data;
	}
	public void setWrappedData(Object list) {
		this.data = (List) list;
	}
```
Even though it inherits from `javax.faces.component.UIData.DataModel` , getWrappedData should return a List, and setWrappedData should have a List as parameter and not object.

But one day (let's hope so) PF will use at least java 1.6, and we may use annotation like `@Override` which will cause a problem at compile time for `public void setWrappedData(List list)`. 

Anyhow, `getWrappedData` should at least return a `List`, so I don't have to cast myself and get warnings...

**Comment by tandraschko** [comment]
Feel free to improve your PR ;) https://github.com/primefaces/primefaces/issues/2573

**Comment by Rapster** [comment]
I guess you can still merge the PR associated, upgrading into 1.6 should be done in  #2573
