### ISSUE TITLE
p:media is not working in case displaying PDF from stream

### ISSUE THREAD

**Issue by woody81** [primefaces/primefaces#2572]
## 1) Environment
PrimeFaces version: 6.1
Application server + version: Tomcat 7.0.62
Affected browsers: All

## 2) Actual behavior
We upgraded to the latest version of Primefaces from 6.0 and now we are facing an issue when we want to display PDF file via p:media component from stream and  "IllegalArgumentException: Invalid UUID string" is thrown. I tried to debug it and found out that class org.primefaces.application.resource.StreamedContentHandler checks validity of DYMANIC_CONTENT_PARAM: pdfrid parameter in URL and it fails. This param is generated correctly in version 6.0, but there is wrong format in version 6.1 IMO (e.g. c2c8378673b680fe01d0a1cec706216). When I downgrade the current version to 6.0 then it starts to work again.

## 3) Expected behavior
PDF file is displayed on page.

## 4) Steps to reproduce
Load a page with p:media component inside.

## 5.1) Sample XHTML
`<p:media value="#{taxAnnouncementPdfContentController.pdfFile}" cache="false" player="pdf" />`

## 5.2) Sample generated HTML
`<object type="application/pdf" data="https://localhost:443/group/portal/forest-property/tax-records/tax-forms/forest-tax-announcement?p_p_id=taxesannouncementportlet_WAR_emetsa&amp;p_p_lifecycle=2&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_cacheability=cacheLevelPage&amp;p_p_col_id=column-1&amp;p_p_col_count=2&amp;p_p_col_pos=1&amp;_taxesannouncementportlet_WAR_emetsa_javax.faces.resource=dynamiccontent.properties&amp;_taxesannouncementportlet_WAR_emetsa_ln=primefaces&amp;v=6.1&amp;pfdrid=c2c8378673b680fe01d0a1cec706216&amp;pfdrt=sc&amp;pfdrid_c=false&amp;uid=50eefd68-b5c6-4784-b8db-7d5d72037607" internalinstanceid="10"></object>`

## 6) Sample bean
```
@ManagedBean
@SessionScoped
public class TaxAnnouncementPdfContentController extends AbstractTaxPdfContentController implements
    Serializable {

  private static final long serialVersionUID = -5982013153237901708L;

  @Autowired
  private transient ForestTaxAnnouncementFacadeFactory taxAnnouncementFacadeFactory;

  @PostConstruct
  public void onInit() {
    SpringBeansDecorator.decorateWithSpring(this);
  }

  public StreamedContent getPdfFile() throws TaxFormConfigurationNotFoundException, IOException {
    return super.getPdfFile();
  }
}
```
```
public abstract class AbstractTaxPdfContentController {

  ....

  public StreamedContent getPdfFile()
      throws TaxFormConfigurationNotFoundException, IOException {
    preparePdfFile();
    return new DefaultStreamedContent(new ByteArrayInputStream(file), TaxDocumentType.CONTENT_TYPE);
  }
```

**Comment by tandraschko** [comment]
Please provide a full example (currently e.g. ForestTaxAnnouncementFacadeFactory is missing, i need a example to reproduce it) or a PR to fix it.

**Comment by woody81** [comment]
I prepared very simple example how to reproduce the issue. Pls use pdf of your choice.

```
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

@ManagedBean
@SessionScoped
public class TaxAnnouncementPdfContentController extends AbstractTaxPdfContentController
    implements Serializable {

  private static final long serialVersionUID = -5982013153237901708L;

  public StreamedContent getTempPdfFile() throws IOException {
    File testPdfFile = new File("src/main/resources/pdf/test.pdf");
    return new DefaultStreamedContent(new FileInputStream(testPdfFile), "application/pdf",
        "test.pdf");
  }
}
```

```
<?xml version="1.0"?>

<f:view xmlns="http://www.w3.org/1999/xhtml"
  xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:p="http://primefaces.org/ui"
  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  locale="#{facesContext.externalContext.requestLocale}">

  <h:head />

  <h:body>
      <section>
        <div>
          <p:media value="#{taxAnnouncementPdfContentController.tempPdfFile}"
            cache="false" player="pdf"/>
        </div>
      </section>

    </h:form>

  </h:body>
</f:view>
```

**Comment by tandraschko** [comment]
Works fine for me, when using this example in the showcase.

**Comment by tandraschko** [comment]
NOTE: i alread use trunk (6.2-SNAPSHOT)

**Comment by woody81** [comment]
How am I able to build 6.2-SNAPSHOT? Sorry for stupid question, but I didn't found any branch or tag with this name in your repository.

**Comment by tandraschko** [comment]
Check our wiki, there is something like "build from source"

**Comment by woody81** [comment]
Succesfully built but an Error identified on our side. Thx for your help.
