### ISSUE TITLE
Upgrade to Java 1.6

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2573]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

...

## 3) Actual behavior

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by Rapster** [comment]
Does it involve a complete review on each file? Eclipse has a nice tool that would allowed to have compliant  java 1.6 in one click, plus it will format all the java files as it is quite a mess today...

**Comment by tandraschko** [comment]
I didn't plan to review each line.
I think the biggest change will be @Override annoations.

**Comment by melloware** [comment]
Agreed with @Rapster.  Eclipse you can set on Save to do awesome things like automatically format the file, add @Override on any methods being overridden and much more including adding brackets around if statements if they are missing etc.

**Comment by tandraschko** [comment]
-1 for auto format, it's impossible to review and not sure if PrimeTeam will follow for 100%. We agreed on a guideline some years ago but sometims even the blank after keywords like "if" isn't used everywhere.

But what we should do:
1) PR for aligning tabs and spaces
    sometimes we use tabs, sometimes spaces. It depends wo did a PR e.g.
    we should use -> 1 tab = 4 blanks and only allow blanks
2) PR to add @Override

**Comment by Rapster** [comment]
I wouldn't say impossible, it's quite easy honestly... I just had a try, it looks very nice and simple to review. If it's only that, I can do it :D the auto-format will basically indent correctly with spaces or tabs, add override annotation, remove unused imports, the online "if statements + instructions"are not great and it can change that... Anyway there is a lot of options... Okay for two commits, one for formatting and the other one for 1.6 compliancy.

**Comment by Rapster** [comment]
maven-jsf-plugin needs to be changed as well to transform the \t into 4 spaces. Nice work by the way @tandraschko :-)

**Comment by tandraschko** [comment]
NOTE:
it's not possible to add @Override automatically in all cases... We currently compile against 2.2 but it still runs fine on 2.0
not sure if @Override will break some cases e.g. when running on JSF 2.0

**Comment by Rapster** [comment]
@tandraschko @melloware In Eclipse, you can simply do Right Click -> Source -> Format, it will format everything in one shot ;-)

**Comment by melloware** [comment]
@Rapster WOW I never realized your could format an entire source tree in one shot!

**Comment by tandraschko** [comment]
Its surely possible, in every IDE but for 50% it formats too much :D

I already did many formatting, and currently i'm configuring checkstyle.

**Comment by Rapster** [comment]
@tandraschko regarding @override annotations, as long you're compiling your sources in 1.6, it shouldn't break a thing... No matter what version of JSF you use or any librairies compiled in older version

**Comment by tandraschko** [comment]
So @Overide is only checked on compile time, not runtime?

**Comment by Rapster** [comment]
Exactly
