### ISSUE TITLE
[Documentation] Lifecycle documentation does not mention LifecyclePhaseListener

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2574]
It should at least mention that the user need to declare it in faces-config.xml

**Comment by cnsgithub** [comment]
May i ask why this has to be added in faces-config.xml ? I didn't have this up to now and never noticed any error related to the jsf lifecycle. Just looking at the code it seems that the phaseListener just writes some PhaseInfo object into the session store? Is this even needed for production use? So maybe the documentation should also explain what the puprpose is and that it might be optional.

**Comment by tandraschko** [comment]
It's a required thing for the "lifecycle" component ;)

**Comment by Rapster** [comment]
@cnsgithub Without this, lifecycle won't work for sure!

**Comment by cnsgithub** [comment]
Yea so this is basically a component which is useful for development purposes only. I think the documentation should then mention that it is only a requirement for the lifecycle component, and if you're running production use it might be reasonable to not use it as it would create some unneccessery overhead in that case.
