### ISSUE TITLE
<p:schedule> converts "locale" into lower case

### ISSUE THREAD

**Issue by lodgmar** [primefaces/primefaces#2576]
Primefaces 6.0, but I've not seen this issue reported, so I suppose it's still wrong.

This code:
```html
<p:calendar locale="es_ES">
<p:schedule locale="es_ES">
```
will be translated into JavaScript code, where the calendar will have "locale:es_ES" (correct) but schedule will have "locale:es_es". This implies wrong localization only for schedule, showed in English, while calendar will show in Spanish.

Meanwhile, I bypass this issue including this:
```html
<script>
    PrimeFaces.locales['es_ES'] = {/*....etc...*/};
    PrimeFaces.locales['es_es'] = PrimeFaces.locales['es_ES'];  // <--- this
</script>
```

**Comment by melloware** [comment]
I fixed this and tested it locally.  I had to switch to use the new LocaleUtils function which makes it consistent with the PrimeFaces Calendar component.
