### ISSUE TITLE
Reflow mode support for DataTable Editors

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#258]
Hello,
The reflow mode in DataTable with (editable="true" editingRow="false" editMode="row") does not support the modification (Cell/Row Editors).

1)
Display problem with `<p:cellEditor>`
it does not give this result:

```
id             45
```

but:

```
id
45 
```

Code: 

```
<p:column headerText="Id" >
       <p:cellEditor>
                 <f:facet name="output"><h:outputText value="#{color.id}" /></f:facet>
                 <f:facet name="input"><p:inputText value="#{color.id}" label="Id"/></f:facet>
       </p:cellEditor>
</p:column>
```

2) 
if you click on confirm or cancel in `<p:rowEditor />` , ALL "headerText" disappear in `p:column`S!

P.S:
check also `selectionMode="multiple"`
Thanks,

**Comment by mailtowim** [comment]
I found the following workaround for this issue:

```
<p:ajax event="rowEdit" oncomplete="PF('tableName').postUpdateData()"/>
 <p:ajax event="rowEditCancel" oncomplete="PF('tableName').postUpdateData()"/>
```
