### ISSUE TITLE
DataTable: Support seek pagination in LazyDataModel

### ISSUE THREAD

**Issue by yacota** [primefaces/primefaces#2581]
DataTable's paginator behaviour is based on offset pagination. Offset pagination is an easy way to accomplish rendering a subset of data without fetching it all,
but relational and non relational databases can not allebiate the problem that when applyied in a large dataset has an enormous performance cost, the main problem is that a database cursor needs to jump step by step from row0 to rowN in order to start fetching the data.
Instead of paginating by specifying the position of the first content and the number of them to retrieve (offset pagination) a new LazyDataModel could let developers specify which fields from the returned list of contents can be used to build the previous and next page's cursor of the current page. For instance

(Sample ordered by DATE and ID ASC with 5 elements per page)
Page0
	Content ( ...  DATE:2012/02/02 ID: 3)   -> previous page as we are ordering ASC would contain data with "DATE <= 2012/02/02 AND ID <= 3"
	Content ( ...  DATE:2012/02/03 ID: 1)
	Content ( ...  DATE:2012/03/03 ID: 4)
	Content ( ...  DATE:2012/03/03 ID: 5)
	Content (...  DATE:2013/03/03 ID: 2)   -> next page would contain data with "DATE >= 2013/03/03" AND ID >= 2"

Seek pagination does not let you know how many pages the dataset has ... BUT not even GOOGLE/GMAIL let you know how many mails you have in your inbox :) (just thousands). We just could provide links to previous page, next page, first page and last page(instead of ordering ASC we could order DESC. There is a problem with the first page when navigating backwards, as the first page could potentially have less than the number of desired elements, so this corner case should be taken into account and fetch the first page). 

Please check the following link in order to get a better understanding http://use-the-index-luke.com/no-offset (performance comparasion in slide 42)

**Comment by kukel** [comment]
Can't this already be implemented with the current lazyDataModel?

If you just 
 
 - Store the sort order fields
 - The page number

and from the resultset keep

 - the last  record
 - the first record

you can in a next request check if the sort order fields are the same as the previous request and if the pagenumer is higher or lower. You can then use this information to create a new query. Keeping the 'state' is the most important change going from 'offset' to seek if I read all correctly.

Not displaying the other pages in the paginator is not to difficult (some simple JS)
The corner case of going back to the first page could (should?) be taken into account too by the developer. 

This all could be 'delegated' to a new baseclass (which I do anyway) and maybe even added to https://github.com/omnifaces/optimusfaces (great work btw)

**Comment by melloware** [comment]
No upvotes in 3 years and can be accomplished in a few different ways as pointed out by @kukel. Closing ticket
