### ISSUE TITLE
picklist: using transfer button and then dragging the element messes up the lists

### ISSUE THREAD

**Issue by michalfotyga** [primefaces/primefaces#2584]
![picklist-item-drag-error](https://user-images.githubusercontent.com/5294702/28670678-0e11e240-72da-11e7-851a-cbcfafcbbe39.gif)

## 1) Environment
- PrimeFaces version: 6.1 (current showcase)
- Affected browsers: firefox + chrome, but probably all

## 2) Expected behavior

Clicking on the transfer button and then transferring the same element does not mess up the lists.

## 3) Actual behavior

Clicking in the described way creates an empty space in the lists. Also, after this situation happens, the lists cannot be reordered anymore, both by dragging and using the buttons.

## 4) Steps to reproduce

- go to https://www.primefaces.org/showcase/ui/data/pickList.xhtml
- scroll down to 'PickList on Steroids' example
- select an item on the source list
- click the -> button
- very fast, right after clicking the transfer button in the previous step, drag the same element into the target list

Doesn't always happen but if you're fast enough you will see the described problem.
It maybe easier to reproduce with changed `effectSpeed`.

**Comment by tandraschko** [comment]
A PR would be great!

**Comment by jxmai** [comment]
PR: #3031
