### ISSUE TITLE
Improve SelectCheckboxMenu performance

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2588]
Reported by PRO User;
> We are using <p:selectCheckboxMenu ../> component in our application.
We have noticed that when the option list in drop down increases by more than 2000 entries, dropdown takes long time to open the list.(approximately 3-5 secs) ..

**Comment by melloware** [comment]
@mertsincan is that similar to this one?   https://github.com/primefaces/primefaces/issues/2089
