### ISSUE TITLE
Add forType attribute to Messages component

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2591]
Type of the "for" attribute. Valid values are "key" and "expression".

**Comment by tandraschko** [comment]
@mertsincan The commit looks good but woudln't it be better to call it "component" instead of "expression"?
expression is to common and it actually referens components with component-search-expressions.

**Comment by Rapster** [comment]
I agree with Thomas, `expression` is quite confusing... Please update the documentation also @mertsincan
