### ISSUE TITLE
SelectOneRadio layout=custom not working in Primefaces Mobile

### ISSUE THREAD

**Issue by podaghub** [primefaces/primefaces#2593]
Hi, I am working on my first prime faces mobile application.  On one of my mobile page I am using SelectOneRadio with custom layout option -  f:view renderkit="PRIMEFACES_MOBILE". The issue is, two sets of radio buttons are displayed when page renders. I could able to recreate the issue with primfaces showcase example (selectOneRadio layout custom) in mobile environment. Same page on desktop works fine. When I looked into generated html source, the custom parameter missing for mobile page when compared to desktop page.  I am wondering, if there is issue with custom layout for mobile version.
I am using PrimeFaces 6.1 and Tomcat Server 8.0.

Appreciate any help !!! Thanks !

**Comment by tandraschko** [comment]
Please follow our issue template guidelines (including example), otherwise it will be closed as invalid.
