### ISSUE TITLE
 SelectOneRadio layout=custom not working in Primefaces Mobile 

### ISSUE THREAD

**Issue by podaghub** [primefaces/primefaces#2594]
Hi, On one of my mobile page (f:view renderkit="PRIMEFACES_MOBILE"), I am using SelectOneRadio with custom layout option. The issue is, two sets of radio buttons are rendered. I could able to recreate the issue with primfaces showcase example (selectOneRadio layout custom) in mobile environment. Same page on desktop works fine. When I looked into generated html source, the custom parameter missing for mobile page when compared to desktop page. I am wondering, if there is issue with custom layout for mobile version.

**1) Environment**
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat Server 8.0
- Affected browsers: Mobile Devices (IOS and Android)

2) Expected behavior
Should work same as desktop web page with custom layout option for SelectOneRadio.

3) Actual behavior
Two sets of radio buttons were rendered.

4) Steps to reproduce
Run Primefaces showcase example for selectOneRadio layout=custom with primefaces mobilekit (f:view renderkit="PRIMEFACES_MOBILE").

**5) Sample XHTML**

 ```
<h3>Custom Layout</h3>
    <p:outputPanel id="customPanel" style="margin-bottom:10px">
        <p:selectOneRadio id="customRadio" value="#{radioView.color}" layout="custom">
            <f:selectItem itemLabel="Red" itemValue="Red" />
            <f:selectItem itemLabel="Green" itemValue="Green" />
            <f:selectItem itemLabel="Blue" itemValue="Blue" />
        </p:selectOneRadio>
 
        <h:panelGrid columns="3" cellpadding="5">
            <p:radioButton id="opt1" for="customRadio" itemIndex="0" />
            <h:outputLabel for="opt1" value="Red" />
            <p:spinner />
 
            <p:radioButton id="opt2" for="customRadio" itemIndex="1" />
            <h:outputLabel for="opt2" value="Green" />
            <p:inputText />
 
            <p:radioButton id="opt3" for="customRadio" itemIndex="2" />
            <h:outputLabel for="opt3" value="Blue" />
            <p:calendar />
        </h:panelGrid>
    </p:outputPanel>
```

**6) Sample bean**
```
package org.primefaces.showcase.view.input;
 
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
 
@ManagedBean
public class RadioView {
     
    private String console;    
    private String city;
    private String city2;  
    private List<String> cities;  
    private String color;
     
    @PostConstruct
    public void init() {
        cities = new ArrayList<String>();
        cities.add("Miami");
        cities.add("London");
        cities.add("Paris");
        cities.add("Istanbul");
        cities.add("Berlin");
        cities.add("Barcelona");
        cities.add("Rome");
        cities.add("Brasilia");
        cities.add("Amsterdam");
    }
 
    public String getConsole() {
        return console;
    }
 
    public void setConsole(String console) {
        this.console = console;
    }
 
    public String getCity() {
        return city;
    }
 
    public void setCity(String city) {
        this.city = city;
    }
 
    public String getCity2() {
        return city2;
    }
 
    public void setCity2(String city2) {
        this.city2 = city2;
    }
 
    public String getColor() {
        return color;
    }
 
    public void setColor(String color) {
        this.color = color;
    }
 
    public List<String> getCities() {
        return cities;
    }
}
```

**Comment by tandraschko** [comment]
PrimeFaces Mobile will be deprecated  in 6.2 and removed in 6.3 ( see https://www.primefaces.org/primefaces-6-2-roadmap/)
Therefor i will close this issue as won't fix. If you will provide a PR to fix this issue until 6.2 RC1, i can merge it.
