### ISSUE TITLE
DataTable: rowGroup feature doesn't set even/odd colors properly

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#2599]
Hi, i noticed the rowGroup features doesn't set the colors of the table properly. You can see the issue on the showcase:

https://www.primefaces.org/showcase/ui/data/datatable/rowGroup.xhtml

I think it would look much better if the grouped rows also had their alternating colors

![image](https://user-images.githubusercontent.com/13161711/28912631-51f6f5e4-7835-11e7-975f-7694cbaf637b.png)

**Comment by tandraschko** [comment]
the second example in the showcase (Rowspan) looks exactly like this.

**Comment by tandraschko** [comment]
No response, will close it.
