### ISSUE TITLE
DataTable: Unable to update ContextMenu when right-clicking on unselected table row

### ISSUE THREAD

**Issue by anwuertz** [primefaces/primefaces#2604]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? 6.1, no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7
- Affected browsers: Internet Explorer 11, Firefox 54.0.1

## 2) Expected behavior
- Right-Click on unselected table row will select that row, then open an updated Context Menu with items and enabling according to new current selection. Updating the context menu in response to a contextMenu event should not close the menu.

## 3) Actual behavior
- Right-Click selects table row (but does not fire a rowSlected event).
- Updating the context menu in response to contextMenu event closes the context menu immediately
- Thus, by only right-clicking on table rows, the context menu is never updated according to the current selection.

## 4) Steps to reproduce
- Start sample app below and open context menu by only right-clicking on rows.
- Compare this to the result of left-then-right clicking

## 5) Sample XHTML
<p:dataTable id="persons" var="person"
	value="#{bean.persons}"
	selectionMode="single"
	selection="#{bean.selectedPerson}"
	rowKey="#{person.id}" scrollable="true">
	
	<p:ajax event="rowSelect" update="form:tabs:personmenu"/>
	
	
	<p:column headerText="ID">
		<h:inputText value="#{person.id}" disabled="true" />
	</p:column>
	<p:column headerText="Gender" width="80">
		<h:outputText value="#{person.gender}" />
	</p:column>
</p:dataTable>
<p:contextMenu widgetVar="personmenu" id="personmenu" for="persons">
	<p:menuitem id="spouse"
		value="#{bean.spouseName}"
		disabled="#{bean.spouseDisabled}" />
</p:contextMenu>

## 6) Sample bean

	public class Person {

		private final String id;
		private final String gender;

		public Person(String id, String gender) {
			this.id = id;
			this.gender = gender;
		}

		public String getId() {
			return id;
		}

		public String getGender() {
			return gender;
		}

	}

	public class PersonsModel extends ListDataModel<Person> implements SelectableDataModel<Person> {

		private List<Person> persons;

		public PersonsModel(List<Person> persons) {
			super();
			this.persons = persons;
			setWrappedData(persons);
		}

		@Override
		public Object getRowKey(Person object) {
			return object != null ? object.getId() : null;
		}

		@Override
		public Person getRowData(String rowKey) {
			if (rowKey != null) {
				for (Person p : persons) {
					if (rowKey.equals(p.getId())) {
						return p;
					}
				}
			}
			return null;
		}

	}

@ManagedBean(name = "bean")
@ViewScoped
public class Bean implements Serializable {

	private List<Person> persons = new ArrayList<Person>();

	private Person selectedPerson;

	@PostConstruct
	public void initialise() {
		persons.add(new Person("1", "FEMALE"));
		persons.add(new Person("2", "MALE"));
		persons.add(new Person("3", "FEMALE"));
		persons.add(new Person("4", "MALE"));
	}

	public SelectableDataModel<Person> getPersons() {
		return new PersonsModel(persons);
	}

	public boolean isSpouseDisabled() {
		return selectedPerson == null;
	}

	public String getSpouseName() {
		if (selectedPerson != null) {
			if ("MALE".equals(selectedPerson.getGender())) {
				return "Husband";
			}
			if ("FEMALE".equals(selectedPerson.getGender())) {
				return "Wife";
			}
		}
		return "Spouse";
	}

	public Person getSelectedPerson() {
		return selectedPerson;
	}

	public void setSelectedPerson(Person selectedPerson) {
		this.selectedPerson = selectedPerson;
	}

}

**Comment by kukel** [comment]
Same is true when there is no selection enabled at all. I want to have a contextMenu for the full datatable/treetable. That is my context (in a specific case) not a certain row. With this 'fix' I should enable selection on the tree/datatable and disable it on every row to get the behaviour I need.
