### ISSUE TITLE
FileUpload does not support default value

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2605]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat
- Affected browsers: Chrome

## 2) Expected behavior
Displaying fileUpload with  default value should display file name

## 3) Actual behavior
It does not display anything

## 4) Steps to reproduce
Set a default value, might be `StreamedContent`or a `UploadedFile`

**Comment by garcia-jj** [comment]
Its not possible due HTML security restrictions. Imagine you are visiting an website with this form:

```
<form name="foo" method="post" enctype="multipart/form-data">
    <input type="file" value="c:/passwords.txt" style="display: none;">
   <button type="submit" value="Click here" />
</form>
```

**Comment by tandraschko** [comment]
Yep, doesn't work for me with plain html, too.
