### ISSUE TITLE
Datatable: multiviewstate problem with sorting

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2613]
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Jetty
- Affected browsers: Chrome

## 2) Expected behavior
Multiviewstate+ lazy datatable + sorting should not result into a crash

## 3) Actual behavior

> java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> at org.primefaces.component.datatable.DataTable.getMultiSortMeta(DataTable.java:1703)
> at org.primefaces.component.datatable.feature.SortFeature.encode(SortFeature.java:156)
> at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:86)
> at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
> at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
> at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582)
> at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
> at org.primefaces.component.api.UIData.visitTree(UIData.java:837)
> at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
> at javax.faces.component.UIForm.visitTree(UIForm.java:371)
> at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
> at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
> at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
> 

## 4) Steps to reproduce

1. Use xhtml 5/ in showcase in lazy.xhtml 
2. Sort YEAR
3. Result into a crash

## 5) Sample XHTML
```xml
<p:dataTable var="car" value="#{dtLazyView.lazyModel}" paginator="true" rows="10"
                         paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                         rowsPerPageTemplate="5,10,15" selectionMode="single" selection="#{dtLazyView.selectedCar}" id="carTable" lazy="true" multiViewState="true">
               <p:ajax event="rowSelect" listener="#{dtLazyView.onRowSelect}" update=":form:carDetail" oncomplete="PF('carDialog').show()" />
               <p:columns value="#{dtColumnsView.columns}" var="column" columnIndexVar="colIndex" sortBy="#{column.property}" filterBy="#{car[column.property]}">
                    <f:facet name="header">
                        <h:outputText value="#{column.header}" />
                    </f:facet>
                    <h:outputText value="#{car[column.property]}" />
                </p:columns>
            </p:dataTable>
```

PR on his way ;-)

**Comment by tandraschko** [comment]
Thanks!
