### ISSUE TITLE
TreeTable: not fully responsive

### ISSUE THREAD

**Issue by NairiAndraste** [primefaces/primefaces#2615]
I'm currently using Primefaces 6.1.3 and wanted to implement a responsive TreeTable, but found out, that it was not implementated as stated earlier:

https://github.com/primefaces/primefaces/issues/518

Priority is implemented but not reflow. Is there any reason for it or was it simply forgotten?

**Comment by melloware** [comment]
PrimeTek has removed support for "responsive" mode in other Prime Libraries so i doubt this would be supported even with a PRO request. See: https://github.com/primefaces/primeng/issues/12047
