### ISSUE TITLE
PickListRenderer: multiple attribute value does not conform to w3c html standards

### ISSUE THREAD

**Issue by michaelGroe** [primefaces/primefaces#2619]
## 1) Environment
- PrimeFaces version: latest from master
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No

## 2) Expected behavior
pickList generates valid html code

## 3) Actual behavior
pickList does not generate valid html code
 
Instead of <select multiple="true"> the right way according to w3c would be <select multiple="multiple".

For more details see:

In XHTML, attribute minimization is forbidden, and the multiple attribute must be defined as <select multiple="multiple">.
https://www.w3schools.com/tags/att_select_multiple.asp

**Comment by michaelGroe** [comment]
Can be fixed by simple one line change in PickListRenderer.encodeListInput()

**Comment by Rapster** [comment]
Cool, so you can provide a PR then ;-)

**Comment by michaelGroe** [comment]
created pull request #2622

**Comment by tandraschko** [comment]
Thanks!
