### ISSUE TITLE
update fullcalendar to 3.6.2

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#2626]
Changes: 

https://github.com/fullcalendar/fullcalendar/compare/v2.9.1...v3.6.2

https://github.com/fullcalendar/fullcalendar/releases

Breaking Changes in 3.0:

IE8 support dropped
jQuery: minimum support raised to v2.0.0
MomentJS: minimum support raised to v2.9.0
lang option renamed to locale
dist files have been renamed to be more consistent with MomentJS:
lang/ -> locale/
lang-all.js -> locale-all.js
behavior of moment methods no longer affected by ambiguousness:
isSame
isBefore
isAfter
View-Option-Hashes no longer supported (deprecated in 2.2.4)
removed weekMode setting
removed axisFormat setting
DOM structure of month/basic-view day cell numbers changed

**Comment by tandraschko** [comment]
Duplicate
