### ISSUE TITLE
LifecyclePhaseListener store not serializable PhaseId to session

### ISSUE THREAD

**Issue by skybber** [primefaces/primefaces#2629]
PhaseId is stored in LifecyclePhaseListener.getPhaseInfo() causing session serialization problems on Tomcat at least:

    WARNING: Cannot serialize session attribute org.primefaces.component.lifecycle.LifecyclePhaseListener for session BC8EFF77ED3185E0F819EEA5FC834A50
java.io.NotSerializableException: javax.faces.event.PhaseId

**Comment by tandraschko** [comment]
Long time fixed.
