### ISSUE TITLE
p-datatable Row Group with Row expansion. Colspan for row expansion template

### ISSUE THREAD

**Issue by gopalakrishnach** [primefaces/primefaces#2630]
1) Environment
- PrimeFaces version: 4.1.3
- Does it work on the newest released PrimeFaces version? No

2) Expected behavior: When p-datatable has Row Group and Row Expansion the colspan of the row expansion template must be total number of visible columns - 1. Since the p-datatable has Row Group the first column is sortfield and in some rows the first column will span more than one row so you must not take this column into colspan of row expansion. We must have better way to set/determine colspan of row expansion template

3) Actual behavior: Row expansion colspan is taking all visible columns which is leading to expanded row to expand more than row width of p-datatable

4) Steps to reproduce. Below is my code
` <p-dataTable #contractsDT class='primeNGDataTable' [value]="contracts" [responsive]="true" rowGroupMode="rowspan" sortField="sector" expandableRows="true">
        <p-headerColumnGroup>
            <p-row>
                <p-column header="Name" rowspan="2" [style]="{'width':'110px'}"></p-column>
                <p-column header="Age" rowspan="2"></p-column>
                <p-column header="Address" [style]="{'width':'100px'}" rowspan="2"></p-column>
                <p-column header="Age" rowspan="2"></p-column>
                <p-column header="Father" colspan="2"></p-column>
                <p-column header="Mother" colspan="2"></p-column>
            </p-row>
            <p-row>
                <p-column header="First Name"></p-column>
                <p-column header="Last Name"></p-column>
               <p-column header="First Name"></p-column>
                <p-column header="Last Name"></p-column>
             </p-row>
        </p-headerColumnGroup>
        <p-column field="name" [style]="{'width':'110px'}"></p-column>
        <p-column field="age"></p-column>
        <p-column field="address"></p-column>
        <p-column [style]="{'width':'100px'}">
            <ng-template let-data="rowData" pTemplate="body">
                <span style="line-height:2;"> {{data.shortaddress}} </span>
                <a *ngIf="data.addresses!== null && data.addresses.length > 0" (click)="contractsDT.toggleRow(data)" style="float:right">
                    <i *ngIf="!contractsDT.isRowExpanded(data)" class="fa fa-chevron-circle-right"></i>
                    <i *ngIf="contractsDT.isRowExpanded(data)" class="fa fa-chevron-circle-down"></i>
                </a>
            </ng-template>
        </p-column>
        <p-column field="ffname"></p-column>
        <p-column field="flname"></p-column>
        <p-column field="mfname"></p-column>
        <p-column field="mlname"></p-column>     
        <ng-template let-data pTemplate="rowexpansion">
            <p-dataTable selectionMode="single" [value]="data.contractPositions">
                <p-column field="addrL1" header="Address Line 1" [style]="{'width': '30px'}"></p-column>
                <p-column field="addrL2" header="Address Line 2" [style]="{'width': '30px'}"> </p-column>
                <p-column field="city" header="City" [style]="{'width': '30px'}"></p-column>
                <p-column field="state" header="State" [style]="{'width': '30px'}"></p-column>
            </p-dataTable>
        </ng-template>
    </p-dataTable>
`
![capture2](https://user-images.githubusercontent.com/30936705/29227899-9f734b3a-7e8c-11e7-91ff-978ebb4a678e.PNG)

![capture](https://user-images.githubusercontent.com/30936705/29227860-6d08718e-7e8c-11e7-8a82-60bc574428f2.PNG)

**Comment by tandraschko** [comment]
Use the PrimeNG project.

**Comment by gopalakrishnach** [comment]
Sorry I didnot understand what you mean by use PrimeNG project. I found primefaces/primefaces. I would have appreciated a better response. Please let me know where to post this.

**Comment by tandraschko** [comment]
https://github.com/primefaces/primeng

**Comment by gopalakrishnach** [comment]
Thanks. Posted. https://github.com/primefaces/primeng/issues/3651
