### ISSUE TITLE
InputGroup breaks with InputNumber

### ISSUE THREAD

**Issue by garcia-jj** [primefaces/primefaces#2632]
The new feature InputGroup available in the latest version doesn't work with components like InputMask. This is caused because this kind of components create hidden HTML elements that breaks CSS styles.

This issue only occurs when the addon is before InputMask. Doesn't occurs when the addon is after InputMask.

![image](https://user-images.githubusercontent.com/140387/29259858-2bbea6c8-809c-11e7-84d9-50a8272b681e.png)

Generated HTML

```
<div class="ui-inputgroup">
    <span class="ui-inputgroup-addon"><i class="fa fa-dollar"></i></span>
    <span id="j_idt10" class="ui-inputnumber ui-widget">
        <input id="j_idt10_input" name="j_idt10_input" value="" placeholder="Number" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all" role="textbox" aria-disabled="false" aria-readonly="false" type="text">
        <input id="j_idt10_hinput" name="j_idt10_hinput" autocomplete="off" value="" type="hidden">
    </span>
</div>
```

Due generated InputMask output create a `span` tag, styles are not applied properly. In this case CSS will be applied to `span`, and not to `input` (this CSS caused the problem with left border, so the code below wont applied to `input text`). 

```
.ui-inputgroup .ui-inputtext:not(:first-child) {
    border-bottom-left-radius: 0;
    border-left: 0 none;
    border-top-left-radius: 0;
}
```

And since the `input text` is not the last element, right border will be applied only to `input hiden`, that is not visible.

```
.ui-inputgroup .ui-inputtext:not(:last-child) {
    border-bottom-right-radius: 0;
    border-right: 0 none;
    border-top-right-radius: 0;
}
```

## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? Not applied
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) This is a new feature available only in latest version
- Application server + version: Wildfly 10.1.
- Affected browsers: Tested on Firefox 54, but I think affect all browsers

## 2) Expected behavior

Input without left border and with right border rounded.

## 3) Actual behavior

Input with left border and no right border (see the image attached).

## 4) Steps to reproduce

Create a page with a simple InputMask component with a InputGroup as described in the next item. 

## 5) Sample XHTML

```
<div class="ui-g ui-fluid">
    <div class="ui-g-12 ui-md-4">
        <div class="ui-inputgroup">
            <span class="ui-inputgroup-addon"><i class="fa fa-dollar"></i></span>
            <p:inputNumber placeholder="Number" />
        </div>
    </div>
</div>
```

## 6) Sample bean

Not necessary

Thank you.

**Comment by tandraschko** [comment]
A PR would be great.
