### ISSUE TITLE
DataTable: Persisting object with rowExpansion using cellEdit event

### ISSUE THREAD

**Issue by Dragonsol** [primefaces/primefaces#2634]
## 1) Environment
- PrimeFaces version: PrimeFaces 6.2-SNAPSHOT (August 15, 2017)
- Application server + version: WildFly 10.1.0
- Other:  Hibernate 5
- Affected browsers: all

## 2) Expected behavior
Expected the "child" objects in the rowExpansion to be persisted, even if the rowExpansion was never toggled.

## 3) Actual behavior
cellEdit event handler contains null values for all elements / childred (e,g, LinkedList) that were never rendered in the rowExpansion.

The workaround is, to expand rowExpansion BEFORE editing any cells. This way, when cellEdit event is called, the listener has fully loaded object(s).

## 5) Sample XHTML
<h:form id="form">
            <p:dataTable id="table" value="#{requirementManagedBean.requirementList}" var="requirement"
                         editable="true" editMode="cell" 
                         paginator="true" rows="10"
                         rowExpandMode="single">

                <p:ajax event="cellEdit" listener="#{requirementManagedBean.onEdit(requirement)}" update="table, :messages"/>

                <p:column style="width:16px">
                    <p:rowToggler />
                </p:column>

                <p:column sortBy="#{requirement.requirementName}" filterBy="#{requirement.requirementName}" filterMatchMode="contains" headerText="Name" width="20%">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{requirement.requirementName}" />
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{requirement.requirementName}" style="width:98%" maxlength="1024"/>
                        </f:facet>
                    </p:cellEditor>
                    <f:facet name="footer">
                        <p:inputText value="#{requirementManagedBean.requirement.requirementName}" style="width:98%" maxlength="1024"/>
                    </f:facet>
                </p:column>

                <p:rowExpansion>
                    <p:panelGrid columns="2" style="width:98%">
                        <p:pickList value="#{requirement.subrequirementsDualList}" var="subrequirement" itemLabel="#{subrequirement.requirementName}" itemValue="#{subrequirement.id}">
                            <f:facet name="sourceCaption">Linked Sub-requirements</f:facet>  
                            <f:facet name="targetCaption">Unlinked Sub-requirements</f:facet>
                            <p:ajax event="transfer" listener="#{requirementManagedBean.handleTransfer(requirement)}" update="table"/>
                        </p:pickList>

                        <p:pickList value="#{requirement.testingProcedureDualList}" var="testingProcedure" itemLabel="#{testingProcedure.testingProcedureName}" itemValue="#{testingProcedure.id}">
                            <f:facet name="sourceCaption">Linked Testing Procedures</f:facet>  
                            <f:facet name="targetCaption">Unlinked Testing Procedures</f:facet>
                            <p:ajax event="transfer" listener="#{requirementManagedBean.handleTransfer(requirement)}"/>
                        </p:pickList>
                    </p:panelGrid>
                </p:rowExpansion>
            </p:dataTable>
        </h:form>

## 6) Sample Managed bean
// Requirement requirement is an @Entity
// RequirementController requirementController is @EJB that has EntityManager and facilitates access to/form database.

@ManagedBean
@ViewScoped
public class RequirementManagedBean implements java.io.Serializable {

    @javax.ejb.EJB
    private RequirementController requirementController;
    private Requirement requirement;
    private List<Requirement> requirementList;

    @javax.annotation.PostConstruct
    public void init() {
        this.requirementList = requirementController.getRequirementList(); // retrieves values from database
    }

    public RequirementManagedBean() {
        this.requirement = new Requirement();
    }

    public Requirement getRequirement() {
        return requirement;
    }

    public void setRequirement(Requirement r) {
        this.requirement = r;
    }

    public void onEdit(Requirement obj) {
        // persist the change and display a confirmation message.
        Requirement merged = (Requirement) requirementController.onEdit(obj);
        addMessage(String.format("%s was successfuly updated.", obj.getRequirementName()));

        // update locally cached list
        this.requirementList = requirementController.getRequirementList();
    }

    public void handleTransfer(Requirement obj) {
        // persist the change and display a confirmation message.
        Requirement merged = (Requirement) requirementController.onEdit(obj);
        addMessage(String.format("%s was successfuly updated.", obj.getRequirementName()));

        // update locally cached list
        this.requirementList.set(this.requirementList.indexOf(obj), merged);
    }

    public List<Requirement> getRequirementList() {
        return this.requirementList;
    }

**Comment by jxmai** [comment]
No need such workaround. RowExpansion can persist object natively in the upcoming PF6.2. See #942 .

**Comment by jxmai** [comment]
> PrimeFaces version: PrimeFaces 6.2-SNAPSHOT (August 15, 2017)

@Dragonsol The problem should be gone if you build again as of today.
