### ISSUE TITLE
AJAX request cannot reach bean if command link / button located in accordion

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#2638]
## 1) Environment
- PrimeFaces version: Latest Primefaces snapshot by the time of writing
- Does it work on the newest released PrimeFaces version? Version? work on 6.0, 6.1, but broke in 6.2 Snapshot
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 8.0.20
- Affected browsers: All

## 2) Expected behavior

AJAX request should reach bean

## 3) Actual behavior

AJAX request cannot reach bean

## 4) Steps to reproduce

Click on any  command button in the datalist, and there is no output in the console

## 5) Sample XHTML

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        
        <h1>#{testView.testString}</h1>
        
        <h:form>
        	<p:accordionPanel>
        		<p:tab title="Tab 1">
        			<p:dataList value="#{testView.testStrings}"
        						var="t"
        			>
        				<f:facet name="header">
        					Data List
        				</f:facet>
        				
        				<p:outputLabel value="#{t}">
        				
        				</p:outputLabel>
        				
        				<p:spacer width="10"></p:spacer>
        				
        				<p:commandButton value="Fire" actionListener="#{testView.fireActionListener(t)}"></p:commandButton>
        			
        			</p:dataList>
        		</p:tab>
        		
        		<p:tab title="Tab 2">
        			
        		</p:tab>
        	</p:accordionPanel>
        </h:form>
        
    </h:body>
</html>
```

## 6) Sample bean

```java
package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    private static final long serialVersionUID = 4124891683211838799L;

    private String testString;

    private List<String> testStrings = new ArrayList<String>();

    @PostConstruct
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
        testStrings.add("1");
        testStrings.add("2");
        testStrings.add("3");
    }

    public void fireActionListener(String str) {
        System.out.println(str);
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

    public List<String> getTestStrings() {
        return testStrings;
    }

    public void setTestStrings(List<String> testStrings) {
        this.testStrings = testStrings;
    }
}
```

![image](https://user-images.githubusercontent.com/10467831/29370731-ec4acb4e-826b-11e7-9363-1ad8c506a6d6.png)

## 6) Runnable Test Project

[primefaces-test.tar.gz](https://github.com/primefaces/primefaces/files/1228656/primefaces-test.tar.gz)

Usage: `mvn clean jetty:run` (Running on 6.2 Snapshot)

To adjust `pom.xml` to compare against 6.1 and 6.0

```xml
<dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <!--<version>6.2-SNAPSHOT</version>-->  <!--Failed-->
            <!--<version>6.1</version>-->  <!--Worked-->
            <!--<version>6.0</version>-->  <!--Worked-->
        </dependency>
```

**Comment by tandraschko** [comment]
patch or analysis is very welcome ;)

**Comment by jxmai** [comment]
I was bisecting this issue the other day but some of the commits in between cannot be compiled... such as https://github.com/primefaces/primefaces/commit/f1c095e9fed3628b5ac9ccd2688c284af07e09c6. This issue will be more of a problem when RC is released. To analyse later.

---

As a note:  bad commit: https://github.com/primefaces/primefaces/commit/09ff17ce55b0889b3650d871306611f75970cf34

good commit: https://github.com/primefaces/primefaces/commit/e74c543772bcde25a97abc9f897f1585b2c2e5b9

regression in between: https://github.com/primefaces/primefaces/compare/e74c543772bcde25a97abc9f897f1585b2c2e5b9...09ff17ce55b0889b3650d871306611f75970cf34

**Comment by jxmai** [comment]
@tandraschko  I found out the first bad commit: https://github.com/primefaces/primefaces/commit/3088e8bd40566e4cf28ade1979dc3d43ea0fc00e for issue #2525 

![image](https://user-images.githubusercontent.com/10467831/29390918-295076d6-82b9-11e7-9206-d49d44fff81c.png)


Please take a look. It looks like you skipped some children processes that should not be skipped.

**Comment by tandraschko** [comment]
Please give it a try, could be fixed ;)

**Comment by jxmai** [comment]
Alright, let me try it out before closing this ticket.

**Comment by jxmai** [comment]
@tandraschko It works :+1: This ticket can be closed now.

**Comment by lagar84** [comment]
Could this #2638 and #2525 backported to elite? I am facing an issue when changing tabs with ajax and lost tab content

**Comment by melloware** [comment]
Typically PF will only backport a fix to Elite if a PRO user requests the change.
