### ISSUE TITLE
p:calendar add missing close event to popup

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#2639]
## 1) Environment
- PrimeFaces version: 6.1.4
- Does it work on the newest released PrimeFaces version? Version? No, Version 6.1.4
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: Wildfly 10.1
- Affected browsers: All

## 2) Expected behavior

Listening to close event of the calendar popup.

## 3) Actual behavior

Close event is missing

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

PR: https://github.com/primefaces/primefaces/pull/2640

**Comment by tandraschko** [comment]
Thanks!
