### ISSUE TITLE
p:menuButton: add title attribute

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#2641]
## 1) Environment
- PrimeFaces version: 6.1.4
- Does it work on the newest released PrimeFaces version? Version? No, 6.1.4
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Wildfly 10.1
- Affected browsers: all

## 2) Expected behavior

Have the title attribute at the menuButton component to give an "Advisory tooltip information.".

PR: https://github.com/primefaces/primefaces/pull/2642

**Comment by tandraschko** [comment]
Thanks
