### ISSUE TITLE
 <p:outputLabel> overload the browse button title/label in <p:fileUpload>

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#265]
Hello,
This is not really a problem or bug, but i noticed that:
 `<p:outputLabel>` overload the browse button label in  `<p:fileUpload>`
Code:

```
<p:outputPanel>
       <p:outputLabel for="in_file" value="OVERLOAD"  />
       <p:fileUpload  id="in_file" label="SELECT FILE"  />
</p:outputPanel>
```

Result:

```
"OVERLOAD" not "SELECT FILE" in browse button.
```

Temporary solution:
remove  `for="in_file"` in  `<p:outputLabel>`.

Thanks.

**Comment by cagataycivici** [comment]
This is expected in advanced mode, not suggested to use outputLabel in advanced mode, if it happens in simple mode, let us know.
