### ISSUE TITLE
DataTable: duplicate cliend ids in custom facet paginator

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2650]
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
## 2) Expected behavior
As an example, menu button is used in facet, and as a result, menuButton should display menu items

## 3) Actual behavior
MenuButton is displayed, but does no show up menu items

## 4) Steps to reproduce

1. Using 5/ in showcase in http://localhost:8080/showcase/ui/data/datatable/paginator.xhtml
2. try to click on menu button
3. menu items does not show up

## 5) Sample XHTML
```xml
            <p:dataTable var="car" value="#{dtPaginatorView.cars}" rows="10" 
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} {Custom}"
                         rowsPerPageTemplate="5,10,15">

                 <f:facet name="{Custom}">
                    <p:menuButton value="Options">
                        <p:menuitem value="Save" actionListener="#{menuView.save}" icon="ui-icon-disk"/>
                        <p:menuitem value="Update" actionListener="#{menuView.update}" icon="ui-icon-arrowrefresh-1-w"/>
                        <p:menuitem value="Delete" actionListener="#{menuView.delete}" ajax="false" icon="ui-icon-close"/>
                        <p:separator />
                        <p:menuitem value="Homepage" url="http://www.primefaces.org" icon="ui-icon-extlink"/>
                    </p:menuButton>
                </f:facet>

                <p:column headerText="Id">
                    <h:outputText value="#{car.id}" />
                </p:column>

                <p:column headerText="Year">
                    <h:outputText value="#{car.year}" />
                </p:column>

                <p:column headerText="Brand">
                    <h:outputText value="#{car.brand}" />
                </p:column>

                <p:column headerText="Color">
                    <h:outputText value="#{car.color}" />
                </p:column>
            </p:dataTable>
```

## 6) Analysis
clientIds generated of both menubutton are the same... So I guess, the jQuery widget can't work properly...

**Comment by Rapster** [comment]
If facet contains `ui:include`, the id I set (in the fix) is not taken account... Don't know if it's my fix which is wrong or Mojarra's problem...

**Comment by Rapster** [comment]
If the facet contains more than one element, it won't work. 

If contains:
1. one element, the new id "xxx_facetname_top" is correctly set: it works
2. more than one element, the facet is a `UIPanel` type and the new id is not set to children: won't work

To reproduce, add another `menuButton` to the sample

**Comment by Rapster** [comment]
The id set to the parent shouldn't be propagated to the children @tandraschko?

**Comment by tandraschko** [comment]
Basically i would check the JSF specs in detail and otherwise ask the EG.

**Comment by Rapster** [comment]
EG? I wrote a post on stackoverflow https://stackoverflow.com/questions/46171478/children-component-does-not-contain-id-parent-in-facet hoping I could get a answer

**Comment by tandraschko** [comment]
JSF Expert Group - they know why it's no naming container. Also, i'm not sure if it would fix something as the component currently exists only 1 times and not multiple times.
maybe we also just missuse facets for this case and maybe need something new.

**Comment by Rapster** [comment]
FYI, problem reproduced here as well https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml

Although it looks like there is nothing wrong because it uses buttons

**Comment by tandraschko** [comment]
I think we should create 2 facets to overcome this problem

**Comment by Rapster** [comment]
2 facets? Could you explain please?

**Comment by Rapster** [comment]
I managed to make it work wrapping the whole think in a UINamingContainer (I created an empty composite inserting his children)

```xml
<f:facet name="{Custom}">
    <my:container>
        <div style="float: right">
            <p:menuButton value="Options">
                <p:menuitem value="Save" actionListener="#{menuView.save}" icon="ui-icon-disk"/>
                <p:menuitem value="Update" actionListener="#{menuView.update}" icon="ui-icon-arrowrefresh-1-w"/>
                <p:menuitem value="Delete" actionListener="#{menuView.delete}" ajax="false" icon="ui-icon-close"/>
                <p:separator />
                <p:menuitem value="Homepage" url="http://www.primefaces.org" icon="ui-icon-extlink"/>
            </p:menuButton>
        </div>
    </my:container>
</f:facet>
```

Of course, it needs my fix :-D (using Mojarra 2.2.15, not sure it could've work before...)

**Comment by rapster** [comment]
Creating a dummy composite works too

**Comment by Rapster** [comment]
I close this one (even though it's not fixed per say) although there is a workaround. See commit 11cc631
