### ISSUE TITLE
DataTable: Livescroll is breaking the rowGroup

### ISSUE THREAD

**Issue by vhcolombo** [primefaces/primefaces#2658]
The rowGroup is broken when use livescroll property

## 1) Environment
- PrimeFaces version: 
**6.1**

- Does it work on the newest released PrimeFaces version? Version?
**Doesn't work**

- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
**It doesn't work neither in the github version.**

- Application server + version: 
**All AS**

- Affected browsers: 
**All browser**

## 2) Expected behavior

**When Live scroll shows new rows, the rowGroup must be processed.**

## 3) Actual behavior

**Live scroll is broken the rowGroup, showing only the firsts ones loaded in the beginning.**

## 4) Steps to reproduce

**Alter the show case "DataTable - Row Grouping" to add these parâmeter to the dataTable:
expandableRowGroups="true" liveScroll="true" liveScrollBuffer="10" scrollRows="10" scrollable="true" scrollHeight="100"** 

## 5) Sample XHTML
        <h3 class="first">Header Row</h3>
        <h:form>
            <p:dataTable var="car" value="#{dtRowGroupView.cars}" sortBy="#{car.brand}" expandableRowGroups="true"
					liveScroll="true" liveScrollBuffer="10" scrollRows="10" scrollable="true" scrollHeight="100" >
                <p:headerRow>
                    <p:column colspan="3">
                        <h:outputText value="#{car.brand}" />
                    </p:column>
                </p:headerRow>
                <p:column headerText="Year">
                    <h:outputText value="#{car.year}" />
                </p:column>
                <p:column headerText="Color">
                    <h:outputText value="#{car.color}" />
                </p:column>
                <p:column headerText="Id">
                    <h:outputText value="#{car.id}" />
                </p:column>
                <p:summaryRow>
                    <p:column colspan="2" style="text-align:right">
                        <h:outputText value="Total:" />
                    </p:column>
                    <p:column>
                        <h:outputText value="#{dtRowGroupView.randomPrice}">
                            <f:convertNumber type="currency" currencySymbol="$" />
                        </h:outputText>
                    </p:column>
                </p:summaryRow>
            </p:dataTable>
        </h:form>

## 6) Sample bean

https://github.com/primefaces/showcase/blob/master/src/main/java/org/primefaces/showcase/view/data/datatable/RowGroupView.java

https://github.com/primefaces/showcase/blob/master/src/main/java/org/primefaces/showcase/service/CarService.java

**Comment by CristianZatt** [comment]
It also breaks the SummaryRow

**Comment by Iseur** [comment]
Hi, i'm currently with 7.0 PF and same issue, any news about this ?

**Comment by melloware** [comment]
I don't think row grouping was meant to be used with LiveScroll because the row groupings must be calculated up front to render the header rows but livescrolling is completely dynamic so it can't know the header rows and where to break.

**Comment by melloware** [comment]
Added documentation warning that RowGroup and Lazy are not compatible features:

> Row Grouping does not work with Lazy loading or LiveScroll as the grouping needs to know about all rows to properly 
> group the rows.

**Comment by Rapster** [comment]
You meant "Lazy loading AND LiveScroll" no? row grouping (headerRow/groupRow should work with classic lazy loading)

**Comment by melloware** [comment]
You are right it should be AND.  I will fix the docs.
