### ISSUE TITLE
Slider broken after update

### ISSUE THREAD

**Issue by heapifyman** [primefaces/primefaces#2661]
I have a page (form) with two sliders. The first is a range slider, the second one is a "normal" slider.

The values selected in the first slider determine the max allowed value for the second slider and the second slider should be "updated" when I move any of the knobs of the first slider.

Pleaser see my example project: example project https://github.com/heapifyman/primefaces-test

It appears that the second slider is "broken" once it has been updated by movement of the first slider. The displayed value of the second slider is not updated anymore when I move the second slider and also the "slideEnd" event handler is not fired any more.

Maybe I am doing something wrong here. If so I would appreciate any hints as to how to fix it.
Thanks in advance.

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) haven't tried
- Application server + version: Jetty 8.1.9.v20130131 (see primefaces-test project)
- Affected browsers: Chrome 60.0.3112.113, Safari 10.1.2

## 2) Expected behavior

Second slider should still work after having been updated.

## 3) Actual behavior

Second slider does not work after update. I can still drag the knob around but the displayed value is not updated and the "slideEnd" event is not fired.

## 4) Steps to reproduce

run example project: https://github.com/heapifyman/primefaces-test

## 5) Sample XHTML

see example project: https://github.com/heapifyman/primefaces-test

## 6) Sample bean

see example project: https://github.com/heapifyman/primefaces-test

**Comment by tandraschko** [comment]
Please check with a build from source, i fixed some slider bugs the lost months.

**Comment by heapifyman** [comment]
@tandraschko Hi, I just tried with build from source but did not notice any change in behaviour.

**Comment by tandraschko** [comment]
I see whats wrong.
Thats probably something wrong or not as expected specified in the JSF API.

Your update looks like:
temperatureNormalisation temperatureNormalisationValue temperatureNormalisationSlider

In that case, the partial-response xml should contain the nodes in the same order but that isn't the case.
If you check the response, the slider is the first updated component.

The problem now is:
- the slider is updated first and the script is executed
- the event binding targets the old hidden input
- after script initialization, the next update nodes are processed
- your hidden input will be updated and the bindet events are lost

I will check now how jsf.js processed the node, maybe they do it in reversed order.

If not, i will close this ticket as won't fix. In this case i would update a container (e.g. the p:panelGrid) instead of each single component.

**Comment by tandraschko** [comment]
Yep, i see. Thats expected: https://stackoverflow.com/questions/15488162/how-to-use-pajax-to-update-several-components-in-order
Check the first answer.

**Comment by tandraschko** [comment]
I wil also probably work if you move the hiddenInput before the slider in your xhtml.

**Comment by heapifyman** [comment]
@tandraschko Hi, thanks for the quick reply.

Unfortunately, the first three suggested solutions did not work.

1. moving `<h:inputHidden>` before the slider did not change the bahaviour
2. updating only `<p:panelGrid>` instead had the strange effect that for each update another slider was added to the page (instead of updating the existing one) - is this intended behaviour?
3. using chained calls of `<p:ajax>` and `<p:remoteCommand>` as suggested by the first stackoverflow answer also did not work as intended. The second slider was usable again, but the allowed maxValue was not updated

Only the [last answer](https://stackoverflow.com/a/21689096) seems to do the trick. Now I have 3 `<p:ajax>` elements which update the 3 components in order - see below and my example project. However, like the author already states, is is not a very elegant solution.

Any hope this can be fixed in some other way?

Also, maybe a note could be added to the `<p:slider>` documentation linking to this issue?

```
<p:slider for="temperatureMin, temperatureMax"
               display="temperatureRange"
               minValue="#{testView.minTemperature}"
               maxValue="#{testView.maxTemperature}"
               style="width: 500px;"
               range="true"
               displayTemplate="[{min}&#176;C, {max}&#176;C]">
    <p:ajax event="slideEnd"
                 process="temperatureMin temperatureMax"
                 update="temperatureNormalisationValue"/>
    <p:ajax event="slideEnd" update="temperatureNormalisation"/>
    <p:ajax event="slideEnd" update="temperatureNormalisationSlider"/>
</p:slider>
```

**Comment by tandraschko** [comment]
updating the panelGrid is somehow a bug in the panelGrid. If i replace this with p:outputPanel, it works fine.
