### ISSUE TITLE
Cannot insert text in Primefaces TextEditor with JavaScript.

### ISSUE THREAD

**Issue by UserPSPretoria** [primefaces/primefaces#2663]
PrimeFaces version: 6.1

I cannot do a text insert with JavaScript into the TextEditor PrimeFaces component.
 With the PrimeFaces extensions CKEditor we can do the following but not with the standard TextEditor:

        String command = "PF('editorWidgetVar').instance.insertText('" + newTemplate + "');";
        RequestContext.getCurrentInstance().execute(command);

With the following xhtml:

<pe:ckEditor escape="false" widgetVar="editorWidgetVar" id="editor" value="#{emailTemplateBean.template}">
                            <p:ajax event="save" listener="#{emailTemplateBean.saveTemplate()}" update=":growl"/>  
                        </pe:ckEditor>

But when we change it to use:

<p:textEditor widgetVar="editorWidgetVar" id="editor" value="#{emailTemplateBean.template}"/>

it doesn't work and it throws a javascript error:

Uncaught TypeError: Cannot read property 'insertText' of undefined
    at eval (eval at <anonymous> (jquery.js.xhtml:14), <anonymous>:1:31)
    at eval (<anonymous>)
    at jquery.js.xhtml:14
    at Function.globalEval (jquery.js.xhtml:14)
    at Object.doEval (core.js.xhtml:3)
    at Object.handle (core.js.xhtml:3)
    at Object.success (core.js.xhtml:3)
    at i (jquery.js.xhtml:25)
    at Object.fireWith [as resolveWith] (jquery.js.xhtml:25)
    at cf (jquery.js.xhtml:25)

**Comment by tandraschko** [comment]
Questions -> forum

however, you can probably get the editor instance via: PF('editorWidgetVar').editor and after that, you can check the QuillJS API ;)

**Comment by UserPSPretoria** [comment]
Yip, you are correct. I replaced .instance with .editor and now I can access the QuillJS API, and use methods like insertText() etc.

Thank you, appreciate.

And yes I will use the forum next time, sorry about that.
