### ISSUE TITLE
p:calendar with ajax "blur" triggers invalid submit on first request

### ISSUE THREAD

**Issue by Hint10** [primefaces/primefaces#2670]
## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
No "blur" event is submitted, only the "dateSelect" event is triggered with the clicked value

## 3) Actual behavior
Clicking a date in the navigator for the first time submits old value.

## 4) Steps to reproduce
1. Open calendar navigator 
2. Click any date 
3. Component is submitted with the old value, the clicked value is discarded

## 5) Sample XHTML
```
<p:calendar value="#{...}" navigator="true">
 <p:ajax event="blur">
 <p:ajax event="dateSelect">
</p:calendar>
```

**Comment by tandraschko** [comment]
Thats expected as blur is exected before dateSelect. I would use change instead of blur.
