### ISSUE TITLE
Set up Gitter

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2675]
Allows to have quick and reactive talk _(that not deserve a ticket or a post on a forum)_

See https://gitter.im/

**Comment by tandraschko** [comment]
We will probably open a slack channel. Will close this for now.

**Comment by Rapster** [comment]
I'm a big user of Slack and the integration with github is not that great, although Gitter is definitely meant for that

**Comment by tandraschko** [comment]
The PF is already using Slack for internal usage, so we probably won't create a second chat thing.

**Comment by Rapster** [comment]
Ah okay, makes sense 😉

**Comment by onursenture** [comment]
Our Gitter channel is available now. https://gitter.im/primefaces/primefaces
