### ISSUE TITLE
XML Exporter: Not Escaping Data

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2679]
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Jetty 9
- Affected browsers: All

## 2) Expected behavior

Using the XML DataExporter with a column value like "BMW & Ford" should print in the XML document "BMW & amp; Ford"

## 3) Actual behavior

Value is printed "BMW & Ford" making it invalid XML

## 4) Steps to reproduce

Edited showcase and changed CarService to "BMW & Ford" in the payload.

## 5) Sample XHTML

Showcase dataexporter.xhtml with the above Java change

## 6) Sample bean

Showcase CarService.java edited in Step #4

**Comment by melloware** [comment]
PR coming...

**Comment by tandraschko** [comment]
@melloware we have now 2 escapeXml methods. 1 in XmlUtils, 1 in ComponentUtils. Could you please check which can be removed?

**Comment by melloware** [comment]
My bad. I didn't realize their was one in Componentutils.  I would like to do the following:

1. Modify the one in ComponentUtils to the updated version I just added which adds unicode checks.

2. Move the XmlUtil.escapeTag to ComponentUtils as "escapeXmlTag" and remove the XmlUtil entirely.

Thoughts?

**Comment by melloware** [comment]
Nevermind I see why they split in into XML util because it uses XML Beans which requires POI dependency where Componentutils does not.  I think I will just update the method in ComponentUtils and remove the new one I added in XmlUtil.  I will submit a PR shortly.

**Comment by tandraschko** [comment]
Please note: ComponentUtils#escpeXML is used by our Ajax stuff. So please check first if we really need to escape every which is inside XMLUtils.

**Comment by melloware** [comment]
The only thing added that was not being escaped before was double quote.

case '\"':
       sb.append("&quot;");
        break;

I can't see how that would be valid XML with a double quote even for Ajax.  Should we leave both flavors of the util?

**Comment by tandraschko** [comment]
Not sure. Can you try if it breaks something? It's normally used for adding json to the ajax response via RequestContext.

**Comment by melloware** [comment]
I will do some experimenting and report back.

**Comment by melloware** [comment]
OK it is failing i unit test.  I closed my PR.  It seems for PrimePartialResponseWriter for sending JSON back it needs to leave the double quotes.   For now I think I need to leave everything the way it is and have the XmlUtil.escape for truly escaping only XML where the ComponentUtils method is for escaping anything used in the client or components.
