### ISSUE TITLE
Log: add hotkey

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2683]
Just like `ui:debug`, I don't wanna see that popup always open, but instead, use an hotkey to open it _(being said, it should be possible to close it)_

**Comment by tandraschko** [comment]
Why not just add a p:hotkey to your template?

**Comment by Rapster** [comment]
That should work, but... First I think it should be possible to close the dialog clicking on a cross icon, then have an attribute like "hotkey" to open it. If you want to close it, define your own hotkey yes.

**Comment by tandraschko** [comment]
So we just need to add a close icon?

**Comment by Rapster** [comment]
and hotkey attribute, because if we give the possibility to close it, we should provide an easy way to open it as well (without using explicitely another component like hotkey)

**Comment by melloware** [comment]
@Rapster I am going to close this for now as it can be accomplished with normal Hotkey.  If you feel strongly about it we can always re-open the ticket but trying to clean up this Issues board a little.
