### ISSUE TITLE
[Documentation] Dialog: appendToBody should be changed to appendTo

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2684]
The documentation still referencing appendToBody. 

> Use appendTo with care as the page definition and html dom would be different, for example if
> dialog is inside an h:form component and appendToBody is enabled

But in some description like dilaog and confimDialog, its says:

> Alternative to appendToBody. Appends the dialog to the given search expression.

I think it's better to no mention `appendToBody` at all

Just wondering but, overlaypanel has a appendToBody property, should it be appendTo?

**Comment by tandraschko** [comment]
Overlay panel needs a refactoring to appendTo probably buts thats another ticket ;)
