### ISSUE TITLE
DataTable contains empty header when header facet content is rendered=false

### ISSUE THREAD

**Issue by Mobe91** [primefaces/primefaces#2685]
## 1) Environment
- PrimeFaces version: 6.1

## 2) Problem

The `encodeFacet` method in `org.primefaces.component.datatable.DataTableRenderer` currently renders the header `div` even if the facet component is not rendered. This results in an empty bar being rendered above the data table. What do you think about adding a check to the renderer to only encode the header if its contents are indeed rendered? See the following modified version of `encodeFacet`. If you agree, I can provide a PR.

```java
protected void encodeFacet(FacesContext context, DataTable table, UIComponent facet, String styleClass) throws IOException {
        if (facet == null) {
            return;
        }

        if (facet.isRendered()) {
            ResponseWriter writer = context.getResponseWriter();

            writer.startElement("div", null);
            writer.writeAttribute("class", styleClass, null);

            facet.encodeAll(context);

            writer.endElement("div");
        }
}
```

**Comment by Rapster** [comment]
I think PF should provide a `headerText` attribute as well. In our case, we use this facet in a composite, if not set, it's still rendered. It would be a lot more easier if there was this new attribute, so in case the value is empty, it's not rendered

**Comment by Mobe91** [comment]
I do not think that a separate `headerText` is necessary. You can introduce a `headerText` attribute in your composite component and just have:

```xml
<p:dataTable>
    <f:facet name="header">
        <h:outputText rendered="#{not empty headerText}" value="#{headerText}"/>
    </f:facet>
</p:dataTable>
```
With my proposed fix in the renderer, this would result in no header row being rendered at all if `#{not empty headerText}` evaluates to `false`.

**Comment by Rapster** [comment]
Quite paintful to do that for every use of the composite... Plus, PF already already does that for some component (like panel for instance). I do agree your fix would work, but I prefer to use an attribute rather than defining a facet, specially if it contains only text...

**Comment by Mobe91** [comment]
It certainly would be more concise, I grant you that. I would be happy to include such an attribute in my PR if desired: @tandraschko  @cagataycivici

**Comment by Rapster** [comment]
I don't think your fix is enough actually, what if your facet contains two components, one rendered and the other not?

**Comment by Mobe91** [comment]
You are right. What is actually happening in case of multiple root components inside the `f:facet` tag is that they are getting wrapped in a `javax.faces.component.UIPanel` component. So the following does the trick:
```java
protected void encodeFacet(FacesContext context, DataTable table, UIComponent facet, String styleClass) throws IOException {
        if (facet == null) {
            return;
        }

        if (isFacetRendered(facet)) {
            ResponseWriter writer = context.getResponseWriter();

            writer.startElement("div", null);
            writer.writeAttribute("class", styleClass, null);

            facet.encodeAll(context);

            writer.endElement("div");
        }
}

private static boolean isFacetRendered(UIComponent facet) {
        boolean rootRendered = facet.isRendered();
        if (rootRendered && UIPanel.class.equals(facet.getClass()) {
            // may be a container panel, so check the children
            for (UIComponent child : facet.getChildren()) {
                if (child.isRendered()) {
                    return true;
                }
            }
            return false;
        } else {
            return rootRendered;
        }
    }
```

Tested this with Mojarra and MyFaces.

**Comment by tandraschko** [comment]
@rdebusscher Is is the same issue as yours today? Or another facet?

**Comment by rdebusscher** [comment]
Is the same. But my adjustments are active for header and footer of datatable so should be ok to close.

Funny, didn't know about this issue, I had the issue with my client yesterday.

**Comment by rdebusscher** [comment]
See also #2825

**Comment by melloware** [comment]
@rdebusscher I have gotten into the habit of looking for old defects that look and smell like something I just fixed.  A lot of times there are duplicate or similar tickets out there.  Nice job you closed 2 tickets with 1 fix!
