### ISSUE TITLE
Rowkey is null when celledit with LazyDataModel

### ISSUE THREAD

**Issue by RamiOthman** [primefaces/primefaces#2688]
## 1) Environment
- PrimeFaces 6.1
- Wildfly 10
- Browser : Firefox

## 2) Expected behavior
When updating a cell, the method onCellEdit is called, and  we can get the rowKey from the CellEditEvent object.
...

## 3) Actual behavior
rowKey is always null
..

## 4) Steps to reproduce
just edit a cell
.. 

## 5) Sample XHTML
  <p:dataTable emptyMessage="Nessun record trovato."
                                             style="margin-top: 50px" id="cars" var="produit"
                                             value="#{gecomparBean.lazyModel}"  
                                             editable="true" editMode="cell" widgetVar="carsTable"
                                             filteredValue="#{gecomparBean.filteredCars}" 
                                             rows="10"
                                             lazy="true"
                                             scrollRows="10"
                                             scrollable="true" liveScroll="true" scrollHeight="250"

                                             resizableColumns="true" resizeMode="expand"
                                             draggableColumns="true" 

                                             rowStyleClass="#{produit.id == gecomparBean.selectedObject.id ? 'selectedRow' : null}"
                                             >

                                    <p:ajax event="colReorder"
                                            listener="#{gecomparBean.onColumnReorder}" />
                                    <p:ajax event="cellEdit" listener="#{gecomparBean.onCellEdit}"  
                                            oncomplete="updateTable()"  update=":form:remote" />
..

## 6) Sample bean
public void onCellEdit(CellEditEvent event) throws RestRequestException {

        Object oldValue = event.getOldValue();
        Object newValue = event.getNewValue();
        UIColumn colonne = event.getColumn();
        DataTable s = (DataTable) event.getSource();
System.out.println("rowkey "+event.getRowKey());
}

## 6) LazyProductDataModel
public class LazyProductDataModel extends LazyDataModel<ProductSessionDTO> implements Serializable {

    private List<ProductSessionDTO> products;
    private ProductSearchWrapper wrapper;

    public LazyProductDataModel(ProductSearchWrapper wrapp) throws RestRequestException {
        super();
        wrapper = wrapp;

    }

    @Override
    public ProductSessionDTO getRowData(String rowKey) {
        for (ProductSessionDTO car : getProducts()) {
            if (car.getId() == (Long.parseLong(rowKey))) {
                return car;
            }
        }

        return null;
    }

    @Override
    public Object getRowKey(ProductSessionDTO car) {
        return car.getId();
    }

    @Override
    public List<ProductSessionDTO> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters) {
        List<ProductSessionDTO> data = new ArrayList<ProductSessionDTO>();
        try {
            System.out.println("First " + first + " Max " + pageSize);
            wrapper.setFirst(first);
            wrapper.setPageSize(pageSize);
            setProducts(ServiceUtils.getInstance().getProducts(wrapper));
            this.setWrappedData((List<ProductSessionDTO>) products);
            if (getProducts() != null) {

                Comparator<ProductSessionDTO> lengthComparator = new Comparator<ProductSessionDTO>() {
                    @Override
                    public int compare(ProductSessionDTO o1, ProductSessionDTO o2) {
                        return Long.compare(o1.getId(), o2.getId());
                    }
                };
                Collections.sort(getProducts(), lengthComparator);

            }
        } catch (RestRequestException ex) {
            Logger.getLogger(LazyProductDataModel.class.getName()).log(Level.SEVERE, null, ex);
        }

        data = products;

        //rowCount
        int dataSize = data.size();
        this.setRowCount(1000);

        //paginate
        if (dataSize > pageSize) {
            try {
                return data.subList(first, first + pageSize);
            } catch (IndexOutOfBoundsException e) {
                return data.subList(first, first + (dataSize % pageSize));
            }
        } else {
            return data;
        }
    }

    /**
     * @return the products
     */
    public List<ProductSessionDTO> getProducts() {
        return products;
    }

    /**
     * @param products the products to set
     */
    public void setProducts(List<ProductSessionDTO> products) {
        this.products = products;
    }

    @Override
    public Object getWrappedData() {
        // TODO Auto-generated method stub  

        return products;
    }

}

**Comment by tandraschko** [comment]
Could someone verify the ticket and maybe provide a PR?!

**Comment by jxmai** [comment]
@RamiOthman  The sample code looks like a part of a live system's codebase which is not runnable by others... Suggest to create a (MCVE) https://stackoverflow.com/help/mcve that can be run on https://github.com/primefaces/primefaces-test for the ease of verifying and debugging

**Comment by RamiOthman** [comment]
@jxmai I solved the problem by adding  selectionMode="single"  disabledSelection="true" in the definition of p:datatable. so I understood that rowkey is non null only when using selection, which is normally false, we can use this value in other contexts without using the selection

**Comment by jxmai** [comment]
@RamiOthman Sounds like a workaround since you were not intended to use selection but to get the rowkey only.  I use table feature heavily but I have not seen this issue before. Are you OK with your workaround or are you still planning to create a smaller sample ?

**Comment by jxmai** [comment]
> Could someone verify the ticket and maybe provide a PR?!

@tandraschko The reporter seems OK with the workaround and the sample is not runnable, so there is no point to leave this issue open.
