### ISSUE TITLE
SelectBooleanButton: if no labels set, the icon does not switch

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2697]
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
Clicking on button should switch icon
## 3) Actual behavior
The icon does not switch with the other one

## 4) Steps to reproduce
```xml
<p:selectBooleanButton id="value2" value="#{selectBooleanView.value2}" onLabel="" offLabel="" onIcon="ui-icon-check" offIcon="ui-icon-close" style="width:60px">
    <p:ajax update="msgs" listener="#{selectBooleanView.addMessage}" />
</p:selectBooleanButton>
```
## 5) Console error

> Uncaught TypeError: Cannot set property 'textContent' of undefined
>     at Class.PrimeFaces.widget.SelectBooleanButton.check (layout.js.jsf?ln=barcelona-layout:408)
>     at Class.toggle (components.js.jsf?ln=primefaces&v=6.0.1-SPARK:9582)
>     at HTMLDivElement.<anonymous> (components.js.jsf?ln=primefaces&v=6.0.1-SPARK:9547)
>     at HTMLDivElement.dispatch (jquery.js.jsf?ln=primefaces&v=6.0.1-SPARK:4670)
>     at HTMLDivElement.elemData.handle (jquery.js.jsf?ln=primefaces&v=6.0.1-SPARK:4338)

I'll try to provide a PR soon enough

**Comment by tandraschko** [comment]
Thanks. Just did a small perf enhancement ;)
