### ISSUE TITLE
Chart - Toggle off series and export as image

### ISSUE THREAD

**Issue by arnoldpettibone** [primefaces/primefaces#2699]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: WebLogic 12.1.3
- Affected browsers: IE, FF, Chrome

## 2) Expected behavior
1. The user hides a series on the chart by clicking on the corresponding legend item.
2. The user exports the chart as image
3. The image fully resembles the chart shown in the main page

## 3) Actual behavior
1. The user hides the orange series on the chart by clicking on the corresponding legend item.
2. The user exports the chart as image
3. The image is different from the source. The hidden orange series line is shown moved to the left, outside the chart grid (see image)
![1](https://user-images.githubusercontent.com/31761346/30211901-09b63a30-94a3-11e7-83a8-fe2d32e31d76.png)

## 4) Workaround
Set this option in the chart extender.

`this.cfg.legend.rendererOptions: { seriesToggleReplot: true }`

Even if the chart image is correct, the legend's voice for the hidden series is not strike through.

**Comment by tandraschko** [comment]
Is this a bug in our code or in jqplot?

**Comment by arnoldpettibone** [comment]
I think is in jqplot code. Maybe I should open the same issue on their github?

**Comment by tandraschko** [comment]
yep, please. Will close it for now, we can upgrade jqplot later.
