### ISSUE TITLE
Publish the rules and guidlines to create issues and pull requests

### ISSUE THREAD

**Issue by srbala** [primefaces/primefaces#27]
Please review/update and approve [wiki Contribution](https://github.com/primefaces/primefaces/wiki/Contributing-to-Primefaces) terms.

New [forum thread](http://forum.primefaces.org/viewtopic.php?f=3&t=41842) has been created to discuss this issue.

**Comment by cagataycivici** [comment]
Have you used a template for this wiki?

**Comment by srbala** [comment]
Yes I did. I have used another ASL 2.0 based [project contribution template](https://github.com/thymeleaf/thymeleaf/blob/2.1-dev/CONTRIBUTING.markdown). Another interesting point to note is that, this template was automatically shown to user/contributor when [new issue](https://github.com/thymeleaf/thymeleaf/issues/new) is created. I am not sure how to enable this, github team can help.

I have cloned the template and replaced the project name with Primefaces and fixed the links. I also removed the third para (from original) on "How will your relation" section since (co-author) it is purely Primefaces team decision. 

On second review of the I have fixed markdown issues on ordered list. This can be verified by [compare two revisions](https://github.com/primefaces/primefaces/wiki/Contributing-to-Primefaces/_compare/e2b2b270b8d8564e0a0833bb52672bd0579b974c...68185c3448b17559cd9700b83ae8c39815bb41f7).

Since you guys are doing great job with Primefaces library and busy with migration and cleaning issues in google code, I was just trying to help. Do the changes as necessary to the project/library, If my action was please let me know and remove the page.

**Comment by cagataycivici** [comment]
Cool, thank you very much.
