### ISSUE TITLE
Chart - Smooth line option not connected to the right class attribute

### ISSUE THREAD

**Issue by arnoldpettibone** [primefaces/primefaces#2700]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No

## 2) Expected behavior
The smooth line option activates when `org.primefaces.model.chart.LineChartSeries.smoothLine` is `true`.

## 3) Actual behavior
The smooth line option activates when `org.primefaces.model.chart.LineChartSeries.showLine` is `true`. This is the snipper from the LineChartSeries class (120).

`if(showLine){ writer.write(",rendererOptions:{smooth: true }"); }`

## 4) Solution
`if(smoothLine){ writer.write(",rendererOptions:{smooth: true }"); }`

**Comment by melloware** [comment]
Looks like this was already fixed in 6.1  See this in the source tree:

https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/model/chart/LineChartSeries.java#L123
