### ISSUE TITLE
Chart - Line break in title is ignored in exported image

### ISSUE THREAD

**Issue by arnoldpettibone** [primefaces/primefaces#2701]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No

## 2) Actual behavior
Exporting the chart as image, line breaks `<br/>` in the title are ignored. In the picture, the title is written on a single line.

**Comment by tandraschko** [comment]
Bug in PF or jqplot?

**Comment by arnoldpettibone** [comment]
I think is in jqplot code. Maybe I should open an issue on their github?

**Comment by tandraschko** [comment]
yep please, we can upgrade jqplot later.
