### ISSUE TITLE
TimelineGroup without events not shown

### ISSUE THREAD

**Issue by pavalasc** [primefaces/primefaces#2702]
Dear All
I'm using Timeline grouping example provided at http://snapshotshowcase-primeext.rhcloud.com/sections/timeline/grouping.jsf:
Trying to add a TimelineGroup without any event attached is not shown on timeline!
This is a perfect case in day to day reality, a truck without any order to carry out, or a resource without any task allocated...
## 1) Environment
- PrimeFaces version:6.1
- Application server + version: JBoss Wildfly 10
- Affected browsers: Safari 9.1.3 and Version 60.0.3112.113 

## 2) Expected behavior
Adding :
TimelineGroup group7 = new TimelineGroup("id7", new Truck("/resources/images/timeline/truck.png", "16"));
model.addGroup(group7);
Expecting: (a truck group without any event associated), like truck 16:
![screen shot 2017-09-08 at 5 16 50 pm](https://user-images.githubusercontent.com/11485685/30215817-d505d590-94b9-11e7-83ec-e959b97e7ccc.png)
## 3) Actual behavior
In fact, only group from 10..15 are visible, as shown below:
![screen shot 2017-09-08 at 5 20 19 pm](https://user-images.githubusercontent.com/11485685/30215925-22044c78-94ba-11e7-9990-68e3a231063a.png)

## 4) Steps to reproduce
create a new Timeline group:
TimelineGroup group7 = new TimelineGroup("id7", new Truck("/resources/images/timeline/truck.png", "16"));
add to model:
 model.addGroup(group7); 
nothing changing in iteration group.

## 5) Sample XHTML
Nothing changing in xhtml file.

## 6) Sample bean
package ro.procont.timeline.tst;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;
import java.util.TreeSet;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.omnifaces.util.Ajax;
import org.primefaces.component.timeline.TimelineUpdater;
import org.primefaces.context.RequestContext;
import org.primefaces.event.timeline.TimelineAddEvent;
import org.primefaces.event.timeline.TimelineDragDropEvent;
import org.primefaces.event.timeline.TimelineModificationEvent;
import org.primefaces.event.timeline.TimelineSelectEvent;
import org.primefaces.model.timeline.TimelineEvent;
import org.primefaces.model.timeline.TimelineGroup;
import org.primefaces.model.timeline.TimelineModel;

import ro.procont.timeline.data.AuditListProducer;
import ro.procont.timeline.data.AuditWorkerListProducer;
import ro.procont.timeline.data.WorkerListProducer;
import ro.procont.timeline.model.Audit;
import ro.procont.timeline.model.AuditWorker;
import ro.procont.timeline.model.Worker;
import ro.procont.timeline.service.AuditRegistration;

//@ManagedBean(name = "linkedTimelinesController")
//@ViewScoped
@Model
public class GroupingTimelineController implements Serializable {  
	  
    private TimelineModel model;  
    private TimelineEvent event; // current changed event  
    private List<TimelineEvent> overlappedOrders; // all overlapped orders (events) to the changed order (event)  
    private List<TimelineEvent> ordersToMerge; // selected orders (events) in the dialog which should be merged  
  
    @PostConstruct  
    protected void initialize() {  
        // create timeline model  
        model = new TimelineModel();  
  
        // create groups  
        TimelineGroup group1 = new TimelineGroup("id1", new Truck("/resources/images/timeline/truck.png", "10"));  
        TimelineGroup group2 = new TimelineGroup("id2", new Truck("/resources/images/timeline/truck.png", "11"));  
        TimelineGroup group3 = new TimelineGroup("id3", new Truck("/resources/images/timeline/truck.png", "12"));  
        TimelineGroup group4 = new TimelineGroup("id4", new Truck("/resources/images/timeline/truck.png", "13"));  
        TimelineGroup group5 = new TimelineGroup("id5", new Truck("/resources/images/timeline/truck.png", "14"));  
        TimelineGroup group6 = new TimelineGroup("id6", new Truck("/resources/images/timeline/truck.png", "15"));  
        TimelineGroup group7 = new TimelineGroup("id7", new Truck("/resources/images/timeline/truck.png", "16"));
        // add groups to the model  
        model.addGroup(group1);  
        model.addGroup(group2);  
        model.addGroup(group3);  
        model.addGroup(group4);  
        model.addGroup(group5);  
        model.addGroup(group6);
        model.addGroup(group7);  
        System.out.println("group1: " + group1);
        // Server-side dates should be in UTC. They will be converted to a local dates in UI according to provided TimeZone.  
        // Submitted local dates in UI are converted back to UTC, so that server receives all dates in UTC again.  
        Calendar cal = Calendar.getInstance(TimeZone.getTimeZone("UTC"));  
        cal.set(Calendar.MINUTE, 0);  
        cal.set(Calendar.SECOND, 0);  
        cal.set(Calendar.MILLISECOND, 0);  
          
        int orderNumber = 1;  
  
        // iterate over groups  
        for (int j = 1; j <= 6; j++) {  
            cal.set(2015, Calendar.DECEMBER, 14, 8, 0, 0);  
            // iterate over events in the same group  
            for (int i = 0; i < 6; i++) {  
                cal.set(Calendar.HOUR_OF_DAY, cal.get(Calendar.HOUR_OF_DAY) + 3 * (Math.random() < 0.2 ? 1 : 0));  
                Date startDate = cal.getTime();  
  
                cal.set(Calendar.HOUR_OF_DAY, cal.get(Calendar.HOUR_OF_DAY) + 2 + (int) Math.floor(Math.random() * 4));  
                Date endDate = cal.getTime();  
  
                String imagePath = null;  
                if (Math.random() < 0.25) {  
                    imagePath = "/resources/images/timeline/box.png";  
                }  
  
                Order order = new Order(orderNumber, imagePath);  
                String group = "id" + j;
                System.out.println("-->GroupingTimeline.initialize group:" + group);
                model.add(new TimelineEvent(order, startDate, endDate, true, group));  
                  
                orderNumber++;  
            }  
        }  
    }  
  
    public TimelineModel getModel() {  
        return model;  
    }  
  
    public void onChange(TimelineModificationEvent e) {  
        // get changed event and update the model  
        event = e.getTimelineEvent();  
        model.update(event);  
  
        // get overlapped events of the same group as for the changed event  
        TreeSet<TimelineEvent> overlappedEvents = model.getOverlappedEvents(event);  
  
        if (overlappedEvents == null) {  
            // nothing to merge  
            return;  
        }  
  
        // list of orders which can be merged in the dialog  
        overlappedOrders = new ArrayList<TimelineEvent>(overlappedEvents);  
  
        // no pre-selection  
        ordersToMerge = null;  
  
        // update the dialog's content and show the dialog  
        RequestContext requestContext = RequestContext.getCurrentInstance();  
        requestContext.update("overlappedOrdersInner");  
        requestContext.execute("PF('overlapEventsWdgt').show()");  
    }  
  
    public void onDelete(TimelineModificationEvent e) {  
        // keep the model up-to-date  
        model.delete(e.getTimelineEvent());  
    }  
  
    public void merge() {  
        // merge orders and update UI if the user selected some orders to be merged  
        if (ordersToMerge != null && !ordersToMerge.isEmpty()) {  
            model.merge(event, ordersToMerge, TimelineUpdater.getCurrentInstance(":mainForm:timeline"));  
        } else {  
            FacesMessage msg =  
                    new FacesMessage(FacesMessage.SEVERITY_INFO, "Nothing to merge, please choose orders to be merged", null);  
            FacesContext.getCurrentInstance().addMessage(null, msg);  
        }  
  
        overlappedOrders = null;  
        ordersToMerge = null;  
    }  
  
    public int getSelectedOrder() {  
        if (event == null) {  
            return 0;  
        }  
  
        return ((Order) event.getData()).getNumber();  
    }  
  
    public List<TimelineEvent> getOverlappedOrders() {  
        return overlappedOrders;  
    }  
  
    public List<TimelineEvent> getOrdersToMerge() {  
        return ordersToMerge;  
    }  
  
    public void setOrdersToMerge(List<TimelineEvent> ordersToMerge) {  
        this.ordersToMerge = ordersToMerge;  
    }  
}  

..

**Comment by tandraschko** [comment]
A PR is very welcome here.

**Comment by melloware** [comment]
The problem is right here the Timeline only adds groups for an event and most of the timeline is event based.    I don't see any immediate easy fix.

```java
        List<TimelineEvent> events = model.getEvents();
        int size = events != null ? events.size() : 0;
        for (int i = 0; i < size; i++) {
            // encode events
            writer.write(encodeEvent(context, fsw, fswHtml, timeline, browserTZ, targetTZ, groups, groupFacet, groupsContent,
                    events.get(i)));
            if (i + 1 < size) {
                writer.write(",");
            }
        }
```

**Comment by jasonex7** [comment]
I had the same problem now I'm working with timeline component. I solved it by creating a `TimeLineEvent` object without start nor end date (both nulls) and changing 1 line in `TimeLineRenderer` to allow null start dates. It works perfectly well for my requirements. I could make a PR with that change, but do you consider that approach a good solution for everyone?

**Comment by melloware** [comment]
I would submit the PR for review.  It sounds like an OK solution to me.
