### ISSUE TITLE
ComponentUtils.resolveLocale() from PF Extensions

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2703]
@tandraschko I wanted to add this method to PF ComponentUtils to get it out of PrimeFaces Extensions.

Basically it uses the existing locale util method and if not found defaults to the JSF default Locale.  It is used by...

- PFE TimePicker
- PFE DocumentViewer
- PFE Calculator

```java
/**
     * Gets a {@link Locale} instance by the value of the component attribute "locale" which can be String or {@link Locale} or null. It can be used in any web
     * projects as a helper method.
     *
     * @param locale given locale
     * @return resolved Locale
     */
    public static Locale resolveLocale(Object locale) {
        if (locale instanceof String) {
            locale = ComponentUtils.toLocale((String) locale);
        }

        if (locale == null) {
            locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();
        }

        return (Locale) locale;
    }
```

**Comment by tandraschko** [comment]
As long as it isn't used in PF, IMO we should not add it. Otherwise i could e.g. unintentionally remove it as it's unused.

**Comment by melloware** [comment]
Understood.  This method seems like a bulletproof way to get the correct Locale without an NPE.  I was wondering if anywhere in PF that is using the ComponentUtils.toLocale() should actually be using this new resolveLocale() method instead like we do in PFE?

For example its used in 3 spots in PF...

- CalendarTemplate
- DatatableTemplate
- TreeTableTemplate

And all 3 are doing this identical code...

```java
Object userLocale = getLocale();
			if(userLocale != null) {
				if(userLocale instanceof String) {
					calculatedLocale = ComponentUtils.toLocale((String) userLocale);
				}
				else if(userLocale instanceof java.util.Locale)
					calculatedLocale = (java.util.Locale) userLocale;
				else
					throw new IllegalArgumentException("Type:" + userLocale.getClass() + " is not a valid locale type for calendar:" + this.getClientId(facesContext));
			} else {
				calculatedLocale = facesContext.getViewRoot().getLocale();
			}
```

Which is essentially what the new ComponentUtils.resolveLocale() does.  So this would clean up 3 "cut and paste" blocks of code.

**Comment by tandraschko** [comment]
+1 to move this logic to a util, you can easily reuse it than in PFE.
Note that we have a additional statement in the PF core (instanceof Locale).

**Comment by melloware** [comment]
Got it i will create a LocaleUtil and add the exception handling like above.  I will submit a new PR.

**Comment by tandraschko** [comment]
+1
