### ISSUE TITLE
PF('table').clearFilters() doesn't work with selectCheckboxMenu

### ISSUE THREAD

**Issue by pedrodelgado81** [primefaces/primefaces#271]
Hi to all, I was working with a datatable with multiple columns filter and I have a button for clear all filters via javascript using clearFilters(). All works well except in selectCheckboxMenu component that doesn't be cleaned. The checked elements continued in check state and the content of datatable was filtered by them.

Here is the code:

```
<p:commandButton onclick="PF('titulaTable').clearFilters()" process="@this"/>
         <p:dataTable 
            id="titula_table_id"
            widgetVar="titulaTable"
.....
<p:column        width="10%"
                headerText="Tipo"
                filterBy="#{dato.var}"
                filterMatchMode="in">
                <f:facet name="filter">
                           <p:selectCheckboxMenu
                                      label="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
                            onchange="PF('titulaTable').filter()"
                            panelStyle="width:300px" scrollHeight="150">
                            <f:selectItems
                                value="#{titulacionesController.datos.categorias}"
                                var="cate"
                                itemLabel="#{cate.nombre} - #{cate.categoria}"
                                itemValue="#{cate.nombre}"/>
                        </p:selectCheckboxMenu>       
                 #{dato.tipo_titu_nombre}
             </p:column>
```

Thanks

**Comment by cagataycivici** [comment]
This is expected, clearFilters clear the default filters, if you use a custom filter then you need to clear it manually.

**Comment by sudheerj** [comment]
The datatable clearFilters function clears only the default filters.It might be difficult to clear each custom filter manually.

CustomFilters might be cleared something similar to like this

```
       this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter :input').val('');
```

**Comment by jastorgalj** [comment]
another option... dt is datatable.

```
 <p:commandButton value="Reset Filters" icon="fa fa-filter" 
     process="@form" update="dt" 
     oncomplete="PF('dt').clearFilters();">
     <p:resetInput target="dt" />
</p:commandButton>
```

**Comment by SuperMAB** [comment]
You should clear manually your costum filter fields using this JS function:
`PF('yourWidgetVar').unchekAll()`

**Comment by ebehmen** [comment]
After adding onchange="PF('datatabele').filter();" to p:selectCheckboxMenu, the uncheckAll() function does not work anymore.
