### ISSUE TITLE
primefaces-6.1.5.zip - pom.xml missing

### ISSUE THREAD

**Issue by pneumcke** [primefaces/primefaces#2715]
The newly released primefaces-6.1.5.zip differs to the previous versions in two aspects:
- additional directory 6_1_5 in the zip file
- missing directory tag with the pom.xml file

Was this done on purpose? At least the missing pom.xml makes the update in my environment much more difficult.

**Comment by mertsincan** [comment]
I'll check and get back to you.

**Comment by mertsincan** [comment]
Thanks a lot! Fixed now. 
Please try again.

**Comment by pneumcke** [comment]
Thanks, that was fast!
