### ISSUE TITLE
Ajax not called when unselect checkbox for remaining last checkbox field

### ISSUE THREAD

**Issue by deveshgangwar20** [primefaces/primefaces#2717]
Dear Team,
In primefaces,selectCheckboxMenu is having Ajax call.Ajax call is working fine for all checkbox selection and unselection except remaining one checkbox unselection.Please find below code for your reference.

	<p:selectCheckboxMenu value="#{fishSampMB.selectedLabs}"
						filterMatchMode="startsWith" label="select here" filter="true"
						required="true" requiredMessage="Lab is required" >
						<f:selectItems itemValue="#{list.pk}" itemLabel="#{list.labName}"
							var="list" value="#{fishSampMB.listOfLabs}" />
						<p:ajax listener="#{fishSampMB.getSelectedLabParameter()}"
							update="form:parametersgrid"></p:ajax>
	</p:selectCheckboxMenu>

Regards,
Devesh Kumar

**Comment by tandraschko** [comment]
You miss every information requested in our issue template -> invalid.
