### ISSUE TITLE
SelectCheckBoxMenu broken on DataTable Filter

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2724]
Reported By PRO User;
> Using the showcase run the following mvn command "mvn clean jetty:run -Pelite-dev"
> 1. Go to Datatable->Filter example here /showcase/ui/data/datatable/filter.xhtml
> 2. In the Color filter select "White".
> 3. In the Color filter select "Green".
> 4. In the Color filter unselect "Green".
> 5. In the Color filter unselect "White".
> 6. In the Color filter select "Orange".
> You will see the filtering is all messed up. Its like its holding on to the previous value. This all works fine in Elite 6.1.4.

**Comment by melloware** [comment]
@mertsincan while this fix works it now broke the original feature we wanted with grouping checkboxmenu items...

https://github.com/primefaces/primefaces/issues/2416

The grouping now no longer appears.

**Comment by mertsincan** [comment]
The PR on #2416 has some JS mistakes. Exp;
//check if inputs must be grouped
var grouped = this.inputs.find('input[group-label]'); /* need to be used filter('[group-label]') instead of find('input[group-label]') to find grouping input */

Fixed now. Thanks a lot!
