### ISSUE TITLE
Allow for plain checkboxes

### ISSUE THREAD

**Issue by trajano** [primefaces/primefaces#2727]
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: WebSphere 8.5.5.12
- Affected browsers: Internet Explorer/ Chrome/Firefox

## 2) Expected behavior

```
<p:selectBooleanCheckbox
  value="#{applicationBean.application.firstNation}"
itemLabel="foo"
plain="true" />
```

Should render a plain checkbox with no styling like `selectOneRadio`

## 3) Actual behavior

Has no effect

## 4) Steps to reproduce

```
<p:selectBooleanCheckbox
  value="#{applicationBean.application.firstNation}"
itemLabel="foo"
plain="true" />
```

## 5) Sample XHTML

```
<p:selectBooleanCheckbox
  value="#{applicationBean.application.firstNation}"
  itemLabel="First Nation" />
```

## 6) Sample bean

```
    Boolean firstNation;
    public Boolean getFirstNation() {
        return firstNation;
    }
    public void setFirstNation(final Boolean a) {
       firstNation = a;
    }
```

**Comment by tandraschko** [comment]
what about using the h:* component?

**Comment by trajano** [comment]
I lose the item label that the prime faces one provides

________________________________

**Comment by tandraschko** [comment]
You can just use a h:outputLabel/p:outputLabel for that.

**Comment by trajano** [comment]
That was what I wanted to avoid.
