### ISSUE TITLE
MultiViewState: Add RowExpansion state

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#2728]
Following #1931, this issue is about:

- [x] - Column Reordering
- [ ] - Row Expansion
- [x] - Column Visibility
- [x] - Column Resizing

**Comment by kukel** [comment]
If I may 'prioritize' I'd say

1. Column Visibility
3. Column Reordering
4. Row Expansion

That is at least what we experienced in feedback from our customers in several datatables

**Comment by Rapster** [comment]
Let's make sure part 1 works 100% there is still few issues about it

**Comment by melloware** [comment]
Looks like column resizing was added in #3046

**Comment by melloware** [comment]
Visibility, Width and Display Order was added in https://github.com/primefaces/primefaces/issues/6689

Changing the name of the issue to the one remaining MVS issue which is RowExpansion.

**Comment by melloware** [comment]
Not sure if remembering row expansion in MVS is the right thing as all the other MVS states are Column based states not ROW based states.

**Comment by Rapster** [comment]
selection is row based state

**Comment by melloware** [comment]
I think Selection is treated special and not part of MVS right?  its stores everything in a Selected Collection controlled by the user and it submits an array of all the selected rows every time a row is selected.

**Comment by Rapster** [comment]
No, it's also part of MVS

**Comment by melloware** [comment]
Ahhh yep I see it now in `DataTableState` I was looking in UiTableState. `private Set<String> selectedRowKeys;`
