### ISSUE TITLE
[Documentation] Document p:widgetVarFromContext

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#2729]
The useful EL function `p:widgetVarFromContext` already exists and works, but it's not documented in the User Guide (PF 6.1). I propose listing it in the 11.2 EL Functions section, so that it would be a part of the official API.

**Comment by Rapster** [comment]
Not only this one, there is plenty of functions contained in tag.xml that are not documented. Thanks for providing explanations and examples

**Comment by tandraschko** [comment]
It would also be usefull if you could prepare some text ;)

**Comment by VsevolodGolovanov** [comment]
> widgetVarFromContext('search_expression', component)
> Provides the widgetVar of a component in PF('') format; the component is found by a specified 'search_expression' string in the component (UIComponent) context .

Example.
```
<cc:interface>
	<cc:attribute name="for" type="java.lang.String" required="true"
		shortDescription="Search expression for an associated dialog" />
</cc:interface>
<cc:implementation>
	<script>
		// find the widget of an associated dialog
		// the `for` expression is evaluated in the naming container context above the current composite component,
		// which is what the user of this component would expect (as opposed to searching from the view root, or in the
		// current composite component's naming container)
		#{p:widgetVarFromContext(cc.attrs.for, cc.getParent().getNamingContainer())}.show();
	</script>
</cc:implementation>

```

**Comment by tandraschko** [comment]
Will close this as the method is deprecated in 6.2 and resolveWidgetVar should be used.
