### ISSUE TITLE
New folderUpload component

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#2730]
In time where all major browsers support entire folder upload, see
https://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree it would be nice to add this possibility also into PF (even with drag&drop). Especially for Intranet apps with controlled environment.

**Comment by tandraschko** [comment]
It would be great if you could sponsor this via PrimeFaces PRO.

**Comment by tandraschko** [comment]
Ah, and it's a duplicate of #2705
