### ISSUE TITLE
TreeTable JavaScript "TypeError" on Update

### ISSUE THREAD

**Issue by agoetze** [primefaces/primefaces#2732]
## 1) Environment
- PrimeFaces version: 6.0.23 and 6.1.5
- Does it work on the newest released PrimeFaces version? Version? No, but it works on 6.0.22 and 6.1.4.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not tested.
- Application server + version: Tomcat 7.0.72
- Affected browsers: Mozilla Firefox 55.0.3 and probably others as well

## 2) Expected behavior

Updating a tree table component (e.g. via a Command Button) with "scrollable= false" does not break the tree table. 

## 3) Actual behavior

Updating a tree table with _scrollable="false"_ throws the following javascript type error:

`TypeError: this.scrollStateHolder is undefined  components.js.jsf:41:570`

Collapsing/expanding a row etc. is not working any more after the tree table update.

The coordinates 41:50 in components.js refer to this command in the method "refresh":
`this.scrollStateVal=this.scrollStateHolder.val();`

I suppose it would be enough to test for `if(this.cfg.scrollable)` before executing the command above to solve the issue.

An update is working as expected with _scrollable="true"_. Probably because the faulty variable has been initialized in this case via _this.setupScrolling()_.

## 4) Steps to reproduce

1. Have a tree table.
2. Update the tree table.
3. Receive the error.
4. Try to expand/collapse a row.

## 5) Sample XHTML

This is a slightly modified version of [this](https://www.primefaces.org/showcase/ui/data/treetable/basic.xhtml) PrimeFaces ShowCase example:

```
<h:form id="form">

	<p:treeTable id="treeTable" scrollable="false" value="#{ttBasicView.root}" var="document">
		<f:facet name="header">
			Document Viewer
		</f:facet>
		<p:column headerText="Name">
			<h:outputText value="#{document.name}" />
		</p:column>
		<p:column headerText="Size">
			<h:outputText value="#{document.size}" />
		</p:column>
		<p:column headerText="Type">
			<h:outputText value="#{document.type}" />
		</p:column>
		<p:column style="width:24px">
			<p:commandLink update=":form:documentPanel" oncomplete="PF('documentDialog').show()" title="View Detail"
				styleClass="ui-icon ui-icon-search">
				<f:setPropertyActionListener value="#{document}" target="#{ttBasicView.selectedDocument}" />
			</p:commandLink>
		</p:column>
	</p:treeTable>

	<p:commandButton value="Update TreeTable" update="treeTable" />

	<p:dialog id="dialog" header="Document Detail" showEffect="fade" widgetVar="documentDialog" modal="true" resizable="false">
		<p:outputPanel id="documentPanel">
			<p:panelGrid columns="2" columnClasses="label,value" rendered="#{not empty ttBasicView.selectedDocument}">
				<h:outputLabel for="name" value="Name: " />
				<h:outputText id="name" value="#{ttBasicView.selectedDocument.name}" style="font-weight:bold" />

				<h:outputLabel for="size" value="Size: " />
				<h:outputText id="size" value="#{ttBasicView.selectedDocument.size}" style="font-weight:bold" />

				<h:outputLabel for="type" value="Type " />
				<h:outputText id="type" value="#{ttBasicView.selectedDocument.type}" style="font-weight:bold" />
			</p:panelGrid>
		</p:outputPanel>
	</p:dialog>

</h:form>
```

My modifications:
1. The tree table has an id and scrollable has been set explicitly to false.
2. There is a command button to update the tree table with the id "treeTable".

## 6) Sample bean

Not necessary. Hitting the command button in the sample XHTML is enough to break the tree table.

**Comment by mertsincan** [comment]
Fixed for 6.1.6, 6.0.24 and 6.2.
https://github.com/primefaces/primefaces/issues/2721
