### ISSUE TITLE
PanelGrid: Grouping Broken in 6.2.SNAPSHOT

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2735]
Run the showcase with "mvn clean jetty:run" to run against the latest PF 6.2.-SNAPSHOT.

Look at /showcase/ui/panel/panelGrid.xhtml and the Grouping example is not rendering correctly.

**Comment by tandraschko** [comment]
PR is welcome ;)

**Comment by melloware** [comment]
I have been trying to narrow it down.  It works in Elite 6.1.5 but is broken in 6.2-SNAPSHOT.  The only two commits I see are:
1. Formatting of the code for the new checkStyle standards.
2. Mert making minor changes for responsive from "ui-grid-row" to "ui-g" etc.  But those looks harmless to me.

**Comment by jxmai** [comment]
Here is the problem https://github.com/primefaces/primefaces/commit/226aa77ac2bc457d6108c1bb41102d47c3a05f8a, please fix it asap:

**Comment by jxmai** [comment]
This issue can be replicated in the showcase as mellowware mentioned. This ticket can break many applications as our user interfaces can be messed up completely.

http://localhost:8080/showcase/ui/panel/panelGrid.xhtml

![image](https://user-images.githubusercontent.com/10467831/30651885-8ec6c936-9dec-11e7-8125-585cea297cc7.png)

---

This ticket might be related to #2664 

cc: @Rapster

**Comment by melloware** [comment]
Ahh i didn't even think that would be the issue so I ignored @Rapster change because it seemed harmless.  But that is definitely causing the issue.

**Comment by Rapster** [comment]
Indeed the PR would only work for grid layout, not tabular :/ I guess this PR should be reverted?

**Comment by jxmai** [comment]
Actually I am not sure about the use case of https://github.com/primefaces/primefaces/commit/226aa77ac2bc457d6108c1bb41102d47c3a05f8a, but this issue is rather serious that brought me here...

**Comment by Rapster** [comment]
Use case is same as Mojarra or MyFaces :wink: 
@tandraschko I think the quickest fix would be to revert the PR, too bad we'll lose `h:panelGrid` compliancy

**Comment by melloware** [comment]
Could we do something clever that returned the column count this way if not in "grid" layout?

**Comment by tandraschko** [comment]
Reverted for now ;)
@melloware  +1 if possible

**Comment by melloware** [comment]
Attempted to fix with a PR.

**Comment by melloware** [comment]
hnmmm looks like my PR is not quite working. Need to dig deeper.
