### ISSUE TITLE
Mobile render kit passthrough attributes support for more components

### ISSUE THREAD

**Issue by JohnSchneider** [primefaces/primefaces#274]
With the mobile render kit, some components which have icons do not have PrimeFaces icon or iconPos attributes, and also do not support other JQuery Mobile passthrough attributes.

It seems as though some needed functionality such as changing icons and icon positions in JQuery Mobile components could be achieved simply by rendering passthrough attributes on more components, the same way some attributes such as data-filter and data-autodivider  are for p:dataList.

For example, to change the icon and/or icon position for a p:tab in p:accordionPanel, which has class ui-collapsible, one could specify pt:data-collapsed-icon="x" and/or pt:data-icon-pos="y".  However, these passthrough attributes are not currently rendered.

Can the mobile render kit be changed so that all passthrough attributes specified are rendered?  It's understood that data-icon and data-icon-pos overlap with PrimeFaces attributes icon and iconPos, so these two passthrough attributes would need to override the default value for PrimeFaces attributes.

**Comment by cagataycivici** [comment]
JSF implementation might do it for PF components as well, what is your JSF runtime?

**Comment by cagataycivici** [comment]
Still a good catch though, we should take care of it.

**Comment by JohnSchneider** [comment]
I'm using Mojarra JSF impl 2.2.6 bundled with Wildfly 8.1.  It does not render passthrough attributes for PF components.

My suggestion is to make the PF mobile render kit render any attribute with namespace http://xmlns.jcp.org/jsf/passthrough.

**Comment by JohnSchneider** [comment]
From http://jsfcorner.blogspot.com/2013/06/jsf-22-pass-through-attributes.html :
"Support in component libraries

For those that are writing component libraries them self (or a few components), it is easy to support those pass-through attributes on your component as well.

On the UIComponent class, they have introduced a new method getPassThroughAttributes(boolean) that you can use to retrieve the discovered attributes.

It returns the info as a Map and you can iterate over this collection and write the information on the response stream.

As this approach is generic, you can put the code in a utility class/method and call it for every component you like to have support for the pass-through components."

**Comment by cagataycivici** [comment]
I agree but please create specific issues for each component, this one is too general.

**Comment by cagataycivici** [comment]
We have a method in CoreRenderer that renders pass thru already.

**Comment by cagataycivici** [comment]
@mertsincan please also do the mobile renderers of standard components.

**Comment by JohnSchneider** [comment]
Thanks guys.
