### ISSUE TITLE
Fieldset: add title attribute

### ISSUE THREAD

**Issue by Quix0r** [primefaces/primefaces#2745]
Having `title` attribute (including `role` where applyable) will improve user experience as you can add small informations (longer text than what you have in `legend` tag) to your components giving the user a short description of what is done here.

I use this across my entire JSF/PF projects (all AGPLv3) and would like to switch to `p:fieldset` but I miss that attribute.

Or am I doing it wrong? Should I use some other PF tag to do the same, giving the user some longer hints what is expected in the form? I would recommend, if acceptable, `legendTitle` and `fieldsetTitle` for the new attribute names.

**Comment by Rapster** [comment]
One attribute `title` should be enough no? Passthrough attributes could be used, but the component does not support it so far.

**Comment by tandraschko** [comment]
+1 for reusing passtrough.

**Comment by Quix0r** [comment]
My point here is, that `legend` and `fieldset` tags can get a separate `title` tag (with their own text, of course).

**Comment by Rapster** [comment]
I don't see why HTML spec define `legend` as a node instead of an attribute of `fieldset`. Specially when the only use case of using `legend` is with `fieldset`... To me, they make one element, for this reason, one `title` should be enough. I don't think we would bother creating two new attributes for so little while passthrough attributes do the job

**Comment by Quix0r** [comment]
Makes sense, `legend` is only for `fieldset` around. Okay, `title` is enough. 👍 And thank you for explaining it.

**Comment by Rapster** [comment]
You can provide a PR ;-) It's quite easy really

**Comment by Quix0r** [comment]
No time for this, maybe.

**Comment by Rapster** [comment]
Too bad, I don't think you'll see this done anytime soon...

**Comment by jxmai** [comment]
PR: #2764

**Comment by Rapster** [comment]
Why not make it support passthrough attributes directly?

**Comment by jxmai** [comment]
I guess the `passthrough` attribute was mentioned in the following blog post: https://www.primefaces.org/jsf-2-2-pass-through-attributes/

but `title` seems really straightforward to use and easy to add :). Also, it is consistent with other components.

**Comment by jxmai** [comment]
IMHO, There is no harm to add `title` attribute to fieldset.

**Comment by Rapster** [comment]
Yes it's easy to add (it's actually way more easier to support passthrough attributes :wink:), but what if I want to support all the HTML5 attributes that `fieldset` has, add a new JSF attributes for each HTML attributes? That's a hell of a work. Regarding the consistent point, maybe those attributes were added before passthrough attributes came out (just a guess). Only limitation is passtrough attributes is JSF 2.2 (JEE 7 spec), and PF try to keep compatibility with JEE 6 even though it became EOL

**Comment by tandraschko** [comment]
As we already have "title" in my components, i think it's ok add to it for now. For other "rare" attributes, passthrough should be used.

**Comment by Quix0r** [comment]
Thank you, guys for adding it. 👍
