### ISSUE TITLE
${project.version} isn't replcaced in core.js

### ISSUE THREAD

**Issue by oliver303** [primefaces/primefaces#2747]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) N/A
- Application server + version: tomcat 8.5.16
- Affected browsers: all browsers

## 2) Expected behavior
the real version number is expected
...

## 3) Actual behavior
the substitution string ${project.version} is returned
..

## 4) Steps to reproduce
use PrimeFaces.VERSION in any javascript
.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by oliver303** [comment]
I can get the version by using an application scoped bean and getting the version number by java code. But that's a bit of overkill imho for page footer with version infos.

**Comment by tandraschko** [comment]
a PR would be great.

**Comment by oliver303** [comment]
Hi Thomas! Servus!

Sorry for the question, but how do i provide a problem report?

regards
Oliver

**Comment by tandraschko** [comment]
Servus :D
PR stands for Pull Request :)

**Comment by oliver303** [comment]
OK! I'll do it this weekend. I'm busy with other work.

**Comment by oliver303** [comment]
``` xml
<resources>
    <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
    </resource>
</resources>
```
Although a PR is requested the above mentioned change in `pom.xml` should do the trick. The tag `<filtering>true</filtering>` is necessary. The guys from PrimeFaces Extensions do the same. But, Thomas, if you still insist, i'll provide you with a PR.

**Comment by melloware** [comment]
I will test it and submit the PR.

**Comment by tandraschko** [comment]
Thanks!
