### ISSUE TITLE
p:button does not use nested f:param when using href attribute

### ISSUE THREAD

**Issue by eversnarf** [primefaces/primefaces#2749]
PrimeFaces version: 6.1.5
With `<p:button>` nested `<f:param>` elements are not passed as parameters to the url defined in `href ` attribute.

```
<p:button href="http://www.google.com">
    <f:param name="q" value="primefaces"/>
</p:button>
```
When clicking on the button, I would expect to go to http://www.google.com?q=primefaces
Instead, I go to http://www.google.com

Parameters are correctly taken into account when using the `outcome ` attribute instead of `href`.
I know I can directly put my parameters in the url in `href  `attribute (`href="http://www.google.com?q=primefaces"`), but passing them as nested `<f:param>` elements has several advantages:
- consistency (same behaviour as with `outcome` attribute)
- clarity (otherwise the `href ` can be very long and unreadable)
- possibility to use the disable attribute of `<f:param>`

**Comment by tandraschko** [comment]
Does it work with h:button?

**Comment by eversnarf** [comment]
AFAIK `h:button` does not have a `href` attribute

**Comment by tandraschko** [comment]
Feel free to provide a PR ;)

**Comment by tandraschko** [comment]
Just to make it sure: If you don't provie a PR, it will likely not happen in the near future.
