### ISSUE TITLE
Action method not working in p:menuitem in Sentinel leftmenu

### ISSUE THREAD

**Issue by banifou** [primefaces/primefaces#2750]
Action method is not fired in <p:menuitem> in leftmenu in Sentinel layout.
Example:
```
<ps:menu id="sm_leftmenu">
       <p:menuitem id="sm_promotion" value="Promotion Page" icon="icon-cube" outcome="promotion-page" action="#{myBean.testAction}" />
</ps:menu>
```
I've tested this with the last version of sentinel Layout and PrimeFaces version: 6.0.

**Comment by tandraschko** [comment]
Use the https://github.com/primefaces/layouts project for sentinel stuff. this is only for primefaces core.
