### ISSUE TITLE
Add NoBorder=true/false or Border=true/false attribute to all UI elements

### ISSUE THREAD

**Issue by Dragonsol** [primefaces/primefaces#2754]
It would be great if all UI elements will have an additional attribute to indicate if a border should be rendered. It is applicable to obvious elements such as p:dataTable or p:panelGrid, but also to elements such as p:textEditor that (for some unknown reason) has a border around it.

For example: 
```
<p:dataTable id="table" value="#{ManagedBean.getDomainsAsList()}" var="domain"  border="false">
...
</p:dataTable>
```
or 

`<p:textEditor value="#{domain.domainName}" readonly="true" toolbarVisible="false" border="false"/>`

**Comment by melloware** [comment]
You don't need to do that PF has a built in style called ui-noborder so just do...

```xml
<p:dataTable styleClass="ui-noborder" .../>
```

**Comment by Dragonsol** [comment]
I have tried it (PrimeFaces 6.2-snapshot) and it does absolutely nothing. Here is the full PF JSF:
 
```
<ui:composition template="template/commonLayout.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h:form>
            <p:dataTable id="table" value="#{frameworkManagedBean.framework.getDomainsAsList()}" var="domain" 
                         styleClass="ui-noborder">
                <f:facet name="header">  
                    <h:outputText value="#{frameworkManagedBean.framework.frameworkName}"/>
                </f:facet>
                <p:column headerText="Domain Name" width="10%">
                    <h:outputText value="#{domain.domainName}"/>
                </p:column>
                <p:column headerText="Requirements">
                    <p:dataTable id="requirements" value="#{domain.domainRequirementsFlatList}" var="requirement"
                                 sortBy="#{requirement.requirementName}"
                                 rendered="#{domain.hasRequirements()}"
                                 styleClass="ui-noborder">
                        <p:column headerText="Requirement Name" width="10%">
                            <h:outputText value="#{requirement.requirementName}" />
                        </p:column>
                        <p:column headerText="Requirement Description" width="20%">
                            <p:textEditor value="#{requirement.requirementDescription}" readonly="true" toolbarVisible="false"/>
                        </p:column>
                        <p:column headerText="Requirement Guidance" width="30%">
                            <p:textEditor value="#{requirement.requirementGuidance}" readonly="true" toolbarVisible="false"/>
                        </p:column>
                        <p:column headerText="Testing Procedures">
                            <p:dataTable id="testingProcedures" value="#{requirement.getTestingProceduresAsList()}" var="testingProcedure" 
                                         sortBy="#{testingProcedure.testingProcedureName}"
                                         rendered="#{requirement.hasTestingProcedures()}"
                                         styleClass="ui-noborder">
                                <p:column>
                                    <p:textEditor value="#{testingProcedure.testingProcedureName} #{testingProcedure.testingProcedureDescription}" readonly="true" toolbarVisible="false" />
                                </p:column>
                            </p:dataTable>
                        </p:column>
                    </p:dataTable>
                </p:column>
            </p:dataTable>
        </h:form>
    </ui:define>
</ui:composition>
```

The HTML source:

`
...
div id="j_idt34:table" class="ui-datatable ui-widget ui-noborder"><div class="ui-datatable-header ui-widget-header ui-corner-top"></div><div class="ui-datatable-tablewrapper"><table role="grid"><thead id="j_idt34:table_head"><tr role="row"><th id="j_idt34:
...
`

... and that is how it is rendered on the screen (Firefox 55.0.2):

![image](https://user-images.githubusercontent.com/8823006/30862989-cde1faea-a29d-11e7-940b-e6bdbdf4785d.png)

**Comment by melloware** [comment]
sorry ui-noborder only works on panels.  

https://stackoverflow.com/questions/10421581/how-to-remove-border-from-specific-primefaces-ppanelgrid

To do it for a datatable see BalusC's answer

https://stackoverflow.com/questions/18880208/remove-all-borders-on-a-specific-datatable

**Comment by tandraschko** [comment]
absolutely -1
If you don't like borders, use css overwrites or a custom theme.

**Comment by Dragonsol** [comment]
While I understand that it is possible to mock around with *custom* CSS to achieve everything and anything, I would suggest considering to have an additional attribute added to the base UI component (and then inherited by all other UI components) to control whether borders should be displayed or hidden.

It will introduce a consisted and controlled way to achieve this, rather than have multiple CSS for various UI components that will require separate maintenance.

**Comment by tandraschko** [comment]
PrimeFaces is a web framework and CSS is the way to go. Otherwise we would have to introduce many attributes for controlling UI rendering.

**Comment by melloware** [comment]
+1 @tandraschko this is what CSS is for an some themes actually turn off these borders by default.  So i wouldn't want it controlled by the component.

**Comment by kukel** [comment]
Definitely -1 here to (and +1 for Thomas' suggestion).

**Comment by Dragonsol** [comment]
@melloware  - fair enough, that is a valid point.

**Comment by Dragonsol** [comment]
For the record (in case, someone will be attempting to achieve the same) -
for the p:datatable, the CSS is based on BalusC's answer (https://stackoverflow.com/questions/18880208/remove-all-borders-on-a-specific-datatable):

```
.ui-datatable.borderless thead th,
.ui-datatable.borderless tbody,
.ui-datatable.borderless tbody tr,
.ui-datatable.borderless tbody td {
    border-style: none;
}
```

... and for the p:textEditor, I've used:
```
.ql-container.ql-snow {
  border: none;
}
```
to disable the border around the UI element.
