### ISSUE TITLE
SelectOneMenu Validation Error: value is not valid

### ISSUE THREAD

**Issue by DaniGalicia** [primefaces/primefaces#2756]
SelectOneMenu component fails when is used with an object type javax.persistence.Entity as value. I use a custom converter but sometimes can't convert value because the value object sended is not equals  anyone collection object.

Sometimes sends the righ Object type and another sends and HibernateProxy object.

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? NO
- Application server + version: Apache TomCat 8.0.27
- Affected browsers: All

## 2) Expected behavior
Succesfull Asigned Value.

## 3) Actual behavior

Validation Error: value is not valid

## 4) Steps to reproduce
     Add a SelectOneMenu component
     Put it a javax.persistence.Entity object as itemValue
     Run ....
    Choose an option and click submit. Validation error ocurrs.

## 5) Sample XHTML

    <p:selectOneMenu value="#{denunciaBean.provincia}" converter="genericPFConverter">
                                    <f:selectItems value="#{denunciaBean.provinciasItems}" var="obj" itemValue="#{obj}" itemLabel="#{obj.nombre}"/>
                                </p:selectOneMenu>

## 6) Sample bean
@ManagedBean
@ViewScoped
public class DenunciaBean implements Serializable{
    
    private Provincia provincia;
    private List<Provincia> provinciasItems;
            ...
 Getters and Setters
}

## 7 Sample javax.persistence.Entity Object

Provincia.java

Imports
....
@Entity
@Table(name = "provincias")
public class Provincia implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_provincia")
    private Integer idProvincia;
    @Column(name = "codigo")
    private String codigo;
    @Column(name = "nombre")
    private String nombre;
    @OneToMany(mappedBy = "provincia", fetch = FetchType.LAZY)
    private Set<Distrito> distritosSet;

    public Provincia() {
    }

   

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Provincia)) {
            return false;
        }
        Provincia other = (Provincia) object;
        if ((this.idProvincia == null && other.idProvincia != null) || (this.idProvincia != null && !this.idProvincia.equals(other.idProvincia))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "pa.gob.minsal.sicvicsta.util.Provincias[ idProvincia=" + idProvincia + " ]";
    }
 ....
//Getters and Setters   
}

## 7 Actual Solution
If i change the equals method like the following

@Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Provincia)) {
            return false;
        }
        Provincia other =null;
        
        if(object instanceof HibernateProxy){
        	 other = (Provincia) ((HibernateProxy)object).getHibernateLazyInitializer().getImplementation();
        	
        }else{
            other = (Provincia) object;
        	
        }
        if ((this.idProvincia == null && other.idProvincia != null) || (this.idProvincia != null && !this.idProvincia.equals(other.idProvincia))) {
            return false;
        }
        return true;
    }

It works

**Comment by tandraschko** [comment]
1) Objects or entities should not be used as value
2) Use converters
3) It's known that ORM frameworks generates proxies, nothing that we can change.

**Comment by zieshen** [comment]
Issue: Getting validation error 'Value is not valid'
JSF:
<h:selectOneMenu id="catId" value="#{adForm.catId}">
                        <f:selectItems value="#{adForm.categories}" var="cat" itemLabel="#{cat.label}" itemValue="#{cat.value}"></f:selectItems>
                    </h:selectOneMenu>
Bean:
List<SelectItem> getCategories(){
...
}

**Comment by DaniGalicia** [comment]
Do you speak english or spanish?

**Comment by zieshen** [comment]
English

**Comment by DaniGalicia** [comment]
Can you share the method getCategories definition and catid declaration

**Comment by zieshen** [comment]
List &lt;javax.faces.model.SelectItem&gt; getCategories(){
List &lt;javax.faces.model.SelectItem&gt; list = new ArrayList<>();
...
SelectItem item = new SelectItem(value.asJsonObject().getJsonNumber("catId"), value.asJsonObject().getString("title"));
            list.add(item);
return list;
}

Long catId;

**Comment by zieshen** [comment]
Dani, I found the issue, the problem was with 'value.asJsonObject().getJsonNumber("catId")' value, after converting into long it start working fine. 

Thanks for your prompt response and help.

**Comment by canerariik** [comment]
******WARNING: FacesMessage(s) have been enqueued, but may not have been displayed.
sourceId=j_idt22:j_idt33[severity=(ERROR 2), summary=(j_idt22:j_idt33: Validation Error: Value is not valid), detail=(j_idt22:j_idt33: Validation Error: Value is not valid)]|#]******

I using JSF and Glassfish. How can ı solve this? Pls help. And I used SelectManyMenu.

**Comment by melloware** [comment]
@swarley21 Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by canerariik** [comment]
@melloware Do you want me to commit my project? I don't quite understand what you want.

**Comment by melloware** [comment]
you can just put it somewhere we can see it to debug it
