### ISSUE TITLE
Double event change on InputNumber component with p:ajax

### ISSUE THREAD

**Issue by JoakinAA** [primefaces/primefaces#2757]
## 1) Environment
- PrimeFaces version: 6.1.4
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not tested
- Application server + version: Primefaces Showcase
- Affected browsers: Tested on Chrome, Firefox and IE v.11

## 2) Expected behavior

Fire one request for change event.

## 3) Actual behavior

Fire same two request for change event.

## 4) Steps to reproduce

Open: https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml
Open Development tools on your browser (press F12)
Go to Network tab and click only XHR request.
Enter some value in any InputNumber of the Showcase.
In Network tab you can notice that two same request appear for change event.

## 5) Sample XHTML

InputNumber Showcase 

## 6) Sample bean

InputNumber Showcase

**Comment by tandraschko** [comment]
@mertsincan 
it's already fixed in trunk: https://github.com/primefaces/primefaces/commit/a7c781329c3781134631db4545d716bc3f83365d
so feel free to merge it to elite.

**Comment by tandraschko** [comment]
Will close it for now as fixed in trunk and will re-ping mertsincan via slack ;)
