### ISSUE TITLE
InputGroup: use facet instead of plain CSS

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2758]
See this example: http://tobago-vm.apache.org/demo-5-snapshot/content/20-component/010-input/50-input-group/Group.xhtml?dswid=-6912

It involves to make it  as a pure JSF component

**Comment by tandraschko** [comment]
IMO the markup is very easy, so i would not create a JSF component for it.

**Comment by melloware** [comment]
The same input group CSS is used across PrimeTek libraries as well so no need to make this a component.  It can always be wrapped in a composite component if necessary.
