### ISSUE TITLE
RowEdit icon might not be rendered after row edit

### ISSUE THREAD

**Issue by webelcomau** [primefaces/primefaces#276]
Primefaces5.2
NetBeans8.0.2
Glassfish4
Mojarra 2.2.9

The problem reported here definitely does not occur with Primefaces3.5, it only happens with PF5.2.

With a @ViewScoped backing bean, if one or more p:column are not rendered during a row edit the rowEdit cell and icon does not show after save (and the table display is corrupt, with some cells missing).

_(BTW I appreciate that PrimeFaces p:dataTable has a separate facility for toggling display of selected columns, but that does not meet the requirements for my real-world app where selected sets of columns must be displayed or not displayed according to display switches in a very complex table.)_

I provide a NetBeans8.0.2 test project demonstrating this problem at:

http://www.webel.com.au/primefaces/PrimeFaces52_dataTable_bug.webel.2015-05-14.tgz

(The project also includes PrimeFaces3.5 as an optional library so one can compare and see that the problem is only in PrimeFace5.2.)

I also provide the code and images demonstrating the problem here.

A fake entity class for populating p:dataTable rows has an id, name, value1, value2, and value3 attributes. In the final JSF page the column for 'value2' column is by default not rendered, and there is a boolean switch for experimenting with that.

``` java
package com.webel.pf;

import java.io.Serializable;

public class FakeEntity implements Serializable {

    private Long id;

    private String name;

    private String value1 = "val1";

    private String value2 = "val2";

    private String value3 = "val3";

    // getters/setters omitted
}
```

Entity loading and database interaction is imitated thus:

``` java
package com.webel.pf;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FakeQuery {

    public FakeQuery() {
        initEntities();
    }

    static private Map<Long, FakeEntity> entities = new HashMap<>();

    /**
     * Fake detached query.
     */
    public List<FakeEntity> getEntities() {
        List<FakeEntity> l = new ArrayList<>();
        for (Long id : entities.keySet()) {
            l.add(entities.get(id));
        }
        return l;
    }

    static private Long id = 0L;

    public void persist(FakeEntity fe) {
        fe.setId(id++);
        entities.put(fe.getId(), fe);
    }

    private void initEntities() {

        if (entities.isEmpty()) {

            FakeEntity e1 = new FakeEntity();
            e1.setName("e1");
            e1.setValue1("val1.1");
            e1.setValue2("val2.1");
            e1.setValue3("val3.1");
            persist(e1);

            FakeEntity e2 = new FakeEntity();
            e2.setName("e2");
            e2.setValue1("val1.2");
            e2.setValue2("val2.2");
            e2.setValue3("val3.2");
            persist(e2);
        }
    }

    /**
     * Fake merge, simply overwrites entity with matching key.
     *
     * @param entity
     */
    public void merge(FakeEntity entity) {
        entities.put(entity.getId(), entity);
    }
}
```

Note that the following @ViewScoped backing bean is non-CDI style:  

```
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
```

Note also that it uses lazy loading of the queried entities with a reset() that will be called in an f:event in the JSF page. It has a 'newName' field and an addNewEntity() listener for creating new rows, and a 'showAllColumns' boolean field that will be used as a render switch for the 'value2' column:

``` java
package com.webel.pf;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import org.primefaces.event.RowEditEvent;

@ManagedBean
@ViewScoped
public class ViewBean implements Serializable {

    private static final Logger logger = Logger.getLogger(ViewBean.class.getName());

    public ViewBean() {
    }

    private boolean showAllColumns = false;

    public boolean isShowAllColumns() {
        return showAllColumns;
    }

    public void setShowAllColumns(boolean showAllColumns) {
        this.showAllColumns = showAllColumns;
    }

    private FakeQuery query = new FakeQuery();

    private List<FakeEntity> entities;

    public List<FakeEntity> getEntities() {
        if (entities==null) {
            entities = fetchEntities();
        }
        return entities;
    }

    private List<FakeEntity> fetchEntities() {
        return query.getEntities();
    }

    public void reset() {
        entities = null;
    }

    public void updateRow(RowEditEvent event) {
        FakeEntity e = (FakeEntity) event.getObject();
        query.merge(e);
        logger.info("updateRow: e.id: "+e.getId());
        reset(); //!
    }

    private String newName;

    public String getNewName() {
        return newName;
    }

    public void setNewName(String newName) {
        this.newName = newName;
    }

    public String addNewEntity() {        
        FakeEntity e = new FakeEntity();
        String name = getNewName() == null || getNewName().isEmpty() ? "[name]" : getNewName();
        e.setName(name);
        query.persist(e);
        logger.info("addNewEntity: e.id:" + e.getId());
        logger.info("addNewEntity: e.name:" + e.getName());
        return null;
    } 
}
```

The JSF page body. Note that the column for 'value2' is by default not rendered (unless one activates the switch):

``` xml
    <h:body>

        <f:view>
            <f:metadata>
                <f:event type="preRenderView" listener="#{viewBean.reset}"/>        
            </f:metadata>
        </f:view>

        <h2>2015-05-14: PrimeFaces5.2 dataTable bug: Webel IT Australia</h2>

        <p>Mojarra 2.2.9; Glassfish4; NetBeans8.0.2; JDK1.7</p>

        <p:panel>
            <p><em>Demonstrates a bug in Primefaces5.2 p:dataTable when
                    one or more columns are conditionally rendered
                    according to a column render state switch. (The problem
                    does NOT occur with Primefaces3.5.)</em>
            </p>
            <p>
                PROVOKE: With the render switch OFF, add a new named entity row, 
                then edit the row, then save (click the tick icon).
            </p>
            <p>
                RESULT: The rowEdit icon does not show at the end of the added row (until a page reload).
            </p>
        </p:panel>

        <h:form id="form">  

            <p:fieldset legend="Options" id="options" style="margin: 1ex;">
                <p:selectBooleanCheckbox 
                    value="#{viewBean.showAllColumns}"
                    id="showLastColumn"
                    itemLabel="Show (render) the Value2 column ?"
                    >
                    <p:ajax 
                        update=":form:dataTable"
                        onstart="document.body.style.cursor='wait'"
                        onsuccess="document.body.style.cursor='default'"
                        />
                </p:selectBooleanCheckbox>
            </p:fieldset>

            <p:dataTable id="dataTable" var="e" value="#{viewBean.entities}" editable="true">

                <p:ajax                         
                    event="rowEdit" 
                    listener="#{viewBean.updateRow}" 
                    />

                <p:column headerText="ID">
                    <h:outputText value="#{e.id}"/>
                </p:column>

                <p:column headerText="Name">
                    <h:outputText value="#{e.name}"/>
                </p:column>

                <p:column headerText="Value1">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{e.value1}"/>
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{e.value1}"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Value2" rendered="#{viewBean.showAllColumns}">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{e.value2}"/>
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{e.value2}"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Value3">
                    <p:cellEditor>
                        <f:facet name="output">
                            <h:outputText value="#{e.value3}"/>
                        </f:facet>
                        <f:facet name="input">
                            <p:inputText value="#{e.value3}"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>

                <p:column headerText="Edit">
                    <p:rowEditor/>
                </p:column>

            </p:dataTable>

            <p:fieldset legend="Actions" id="actions" style="margin: 1ex;">            
                <h:panelGroup style="margin-top: 2ex;">
                    <p:outputLabel value="New name:"/> 
                    <p:inputText value="#{viewBean.newName}"/>
                </h:panelGroup>
                <p:commandButton action="#{viewBean.addNewEntity()}" value="Create new fake entity" update=":form:dataTable"/>
            </p:fieldset>

        </h:form>      
    </h:body>
```

TO PROVOKE: With the render switch OFF, add a new named entity row, then edit the row, then save (click the tick icon).

RESULT: The rowEdit cell and icon does not show at the end of the added row (until a page reload), and depending on the configuration, in more complex tables, some columns cells at the end do not display, on the row that was added then edited.

These images demonstrate the sequence to provoke the problem:

![primefaces52-datatable-bug-0](https://cloud.githubusercontent.com/assets/7203231/7624786/7b4e3a30-fa31-11e4-9f32-fbf985a5152e.png)

![primefaces52-datatable-bug-1-add-new](https://cloud.githubusercontent.com/assets/7203231/7624789/844ebaba-fa31-11e4-8296-4a4b0650a9f8.png)

![primefaces52-datatable-bug-2-added](https://cloud.githubusercontent.com/assets/7203231/7624792/8b870986-fa31-11e4-8488-9066f0bb027e.png)

![primefaces52-datatable-bug-3-edit](https://cloud.githubusercontent.com/assets/7203231/7624794/957dc290-fa31-11e4-95f8-1686591ebe89.png)

![primefaces52-datatable-bug-4-saved](https://cloud.githubusercontent.com/assets/7203231/7624800/a07d1f9c-fa31-11e4-8510-9df7f12eaade.png)

![primefaces52-datatable-bug-5-compare-all](https://cloud.githubusercontent.com/assets/7203231/7624801/a8843af4-fa31-11e4-96f2-2a1a3efe4f65.png)

**Comment by cagataycivici** [comment]
Great issue post by the way, we'll honor your effort for sure on 5.2.4.

**Comment by cagataycivici** [comment]
I've reviewed this and cause is kinda expected. On row edit complete, new row is sent via ajax response and tr element is replaced. Since it has missing columns, table gets misaligned. Fixing this requires major changes, as your case is not common we'll leave it as it is. If there are more requests, we'll reopen.

**Comment by webelcomau** [comment]
Hi Primefaces,

Thanks for looking into this. You wrote:

> I've reviewed this and cause is kinda expected.

I don't know why you think it is expected or "not common"; The requirement (support for robust conditional rendering of columns while both viewing and row-editing a dataTable) seems to me a rather basic one, and it worked fine for Primefaces3.5.

For my real-world application I considered 2 workarounds:
1. Split a very large editable dataTable under column render display switch control into multiple regular dataTables without render conditions on editable columns. This had many other advantages, so I chose this.
2. Another approach would be to use CSS to mask some columns; not very elegant, and has the disadvantage that data is still sent from the server to the client (which might break security requirements for some cases).

Long term I would still appreciate this one being fixed, I do use this column display switch technique often for editable tables, and splitting them up is not always an option.

Thanks for your continued work on Primefaces.

Webel IT Australia

**Comment by cagataycivici** [comment]
Try hiding the content of columns not the columns themselves.

**Comment by webelcomau** [comment]
Primefaces wrote:

>  Try hiding the content of columns not the columns themselves.

It permits editing without the bug, but it does not seem to be possible to hide the column that way.

I tried targeted 'rendered' then eventually tried plastering it across every possible element (except p:column), the header and column always appear (even if empty).

```
<p:column>
  <f:facet name="header" rendered="#{viewBean.showAllColumns}">Value2</f:facet>
  <p:cellEditor  rendered="#{viewBean.showAllColumns}">
    <f:facet name="output" rendered="#{viewBean.showAllColumns}">
      <h:outputText value="#{e.value2}" rendered="#{viewBean.showAllColumns}"/>
    </f:facet>
    <f:facet name="input" rendered="#{viewBean.showAllColumns}">
      <p:inputText value="#{e.value2}" rendered="#{viewBean.showAllColumns}"/>
    </f:facet>
  </p:cellEditor>
</p:column>
```

Even if I don't include the header f:facet at all, the column still appears (with empty header).

There is a good discussion of this facet hiding problem at http://stackoverflow.com/questions/4369114/how-do-i-conditionally-render-an-ffacet

I really do consider the abilitity to rowEdit with a p:column under 'rendered' display control a basic requirement. What is the point of having 'rendered' on p:column if it does not work (anymore) during row editing ?

**Comment by axeffekt1** [comment]
The easiest way to solve this problem is to add emty column to table like: < p:column visible="false" / >
Then there is no problem with sending additional data and mentioned security issues. Yes I know, it is not the best solution, but you don't have to care about missing empty column. Nobody detect the column will gone because it will never be shown and table looks consistent for all lifecycle.

**Comment by nelsongraca** [comment]
We too have this problem, this should be supported.

**Comment by mahmedntg** [comment]
it resolved in primefaces 5.3 but how please write the changes ?

**Comment by ghost** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4274186/11393358/4551bae0-9385-11e5-80f4-7925373fc5db.png)

**Comment by mahmedntg** [comment]
thanks it's working and also visible on column but the last one does't hide the html source code when inspect column element .

**Comment by webelcomau** [comment]
@axeffekt1 

Thanks for your suggestion to use 'visible' on the relevant p:column(s), rather than 'rendered'. 

I tried it with PF5.2. From a purely user experience point of view it seems to work (one can add new rows and edit them ok without the originally reported error of missing cells and missing row edit icon). 

However if you look closely at the client side HTML you can see the data is in fact there, it's just masked in CSS using class="... ui-helper-hidden" in both the column headers and the column data. So this solution/workaround does not meet security requirements for some of my tasks, as data is still sent (just not shown) to the client side, it can't be used for strict data access restriction cases.

[EDIT: initial test with PF5.3 seems to have 'rendered' working as expected. thanks].

Thanks all for testing, suggestions, and input.

Webel IT Australia

**Comment by webelcomau** [comment]
Testing PF5.3 community edition in the test project. The 'rendered' now seems to work as expected.

Thanks for fixing.
