### ISSUE TITLE
Select All checkbox for selectManyCheckbox

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#277]
Since CheckBoxMenu looks like a ManyCheckBox, it would be great if we have the function "Select all" in ManyCheckBox, it could even be optional.

http://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml
http://www.primefaces.org/showcase/ui/input/manyCheckbox.xhtml

**Comment by sudheerj** [comment]
IMHO,both the components are not the same.The selectall option will be suitable for CheckboxMenu because it will display them in overlay menu but this is not the case with ManyCheckBox.Where we can add selectAll option.I feel it is good to use as composite component or custom script etc.

**Comment by erickdeoliveiraleal** [comment]
I saw a lot of people with this necessary extra script if you search Google

**Comment by erickdeoliveiraleal** [comment]
BalusC just answered me: http://stackoverflow.com/questions/30229959/select-all-items-in-multiple-selectmanycheckbox-with-dynamic-ids/30274241#30274241

**Comment by melloware** [comment]
@erickdeoliveiraleal  Can this be closed as SelectManyCheckbox does have a Select All checkbox option now?

**Comment by melloware** [comment]
To me this is a a very strange and non standard UI option for this component and no upvotes in 4 years I am going to close it.  This is achieved simply with a composite component or by simply adding a checkbox to your screen to Select All in the custom circumstances where you need it.
