### ISSUE TITLE
[perf] optimize selectOneMenu with customContent

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2775]
Currently we call menu#getColumns() 3 times and do a foreach loop each time ->
3 ArrayList instances
3 Iterator instances

we can simply optimize it down to
1 ArrayList instance
0 Iterator instances

means each selectOneMenu with customContent now saves 5 object instances.

**Comment by tandraschko** [comment]
@melloware would be great if you could review, i also removed an unrechable if statement. Not sure it worked before your PR.

**Comment by melloware** [comment]
+1 Nice optimization to only have getColumns() build the list once and pass it around.
