### ISSUE TITLE
BUG: Primefaces5.2 p:dataExporter selectionOnly=true: doesn't export selected data

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#278]
Primefaces 5.2

When I try to export data from p:dataTable to excel file with p:dataExporter selectionOnly=true the component is exporting the data related to the whole dataTable list object, not to the subset of selected objects.

The problem reported on this issue can be seen on exportSelectionOnly method on Export component, where code is acting over "table" and not over "table.getSelection()".

**Comment by sudheerj** [comment]
The same issue is already available https://github.com/primefaces/primefaces/issues/273.I will add pull request later

**Comment by cagataycivici** [comment]
See #273 please.
