### ISSUE TITLE
Primefaces is using uncompressed resources

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#2780]
Hello,

I analyzed my primefaces-site on the server to solve performance issues.
The first thing i am doing was to test it via the PageSpeed-Tool from Google which is available in Google-Chrome and so i find out the main "problems" which are coming from Primefaces:

1.) Most of the Stylesheet's and JavaScript's are not compressed or minified - coming from Primefaces.
So please minimize and compress the script's/stylesheet's (also the themes) or only output them as a minimized version when PROJECT_STAGE is set to Production !

2.) The order of Stylesheet's and JavaScript's are wrong, so they are very imperformant in every HTML-Site generated. What i mean ? The position of stylesheet's should always be the head (Head-Tag),
but the javascript's must be moved to the end of the HTML (In the Body-Tag).
This is at the moment the recommented way for HTML5, but not rendered in Primefaces.

Actually I have to use Omnifaces Resource Handler to redirect your uncompressed css/js-files to the manually compressed ones, which must be updated manually on every release of you !
To correct the second point i also add a filter which is able to optimize the include order of your css/js-files because that's at the moment the only way to "repair" the wrong order and increase the performance...

Please see this as an important step to improve the performance of websites in production...

Best regards,
Stefan S.

**Comment by tandraschko** [comment]
if you download the JAR there, i can't see any uncompressed resource:
http://repo1.maven.org/maven2/org/primefaces/primefaces/6.1/

**Comment by tandraschko** [comment]
And please -> 1 issue/enhancement request -> 1 ticket. The second point is a valid enhancement but it would need some hacking around the resource handling as it's not supported out of the box by JSF.

**Comment by ssibitz** [comment]
I am talking about primefaces-6.1.6.jar because i am using the latest one:

Here are the files which are not compressed or not minimized by default, but very big uncompressed
and so PageSpeed said the page is not performant:
\primefaces-6.1.6\META-INF\resources\primefaces\components.css
\primefaces-6.1.6\META-INF\resources\primefaces\components.js
\primefaces-6.1.6\META-INF\resources\primefaces\components-mobile.js

Best regards.

**Comment by tandraschko** [comment]
Seems like something related to elite only.... Will ping them.

**Comment by ssibitz** [comment]
For the second point i will make a new ticket.

I know, that the resource-handling in JSF is out of the box not the best,
but eventually with the Filter i already added could also be a performant solution for Primefaces...

**Comment by tandraschko** [comment]
+1
feel free to attach the sources, i will check them!

**Comment by ssibitz** [comment]
Are you also using the Resource-Optimizer
https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Maven-plugin-for-web-resource-optimization
for the Primefaces-Build ?

Because i can't see it in the pom.xml - File ?!
The output-files from the aggregations are combined, 
but not compressed/minimized , so they are very big ...

_From the pom.xml:_
```
<output>${project.build.directory}/classes/META-INF/resources/primefaces/components.css</output>
<output>${project.build.directory}/classes/META-INF/resources/primefaces/core.js</output>
<output>${project.build.directory}/classes/META-INF/resources/primefaces/components.js</output>

```... and so on ...

**Comment by tandraschko** [comment]
Nope, we still using the old plugin.

Compression only runs with -Prelease flag

**Comment by ssibitz** [comment]
Hmm - So how can i check it ?

Because this output - files are still uncompressed in the jar file(s) of primefaces...

**Comment by tandraschko** [comment]
What do you mean?
If you run build primefaces trunk with -Prelease, all files should be compressed. Not sure what you mean to "check it"?

**Comment by ssibitz** [comment]
ok, now i understand - you are using a maven - build - parameter.
That wasn't clear for me what you are mean with "Flag" ... 

I will try it ...
