### ISSUE TITLE
[perf] Collect scripts and render it before the body ends

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#2781]
The resource-order of Stylesheet's and JavaScript's are not "optimized", 
so they are very imperformant in every HTML-Site generated. 

What i mean ? The position of stylesheet's should always be the head (Head-Tag),
but the javascript's must be moved to the end of the HTML (In the Body-Tag).

This is at the moment the recommented way for HTML5, but not rendered in Primefaces.

Browser's can so render the page by using the stylesheet's first and then execute the javascript's.
This result's in a faster page loading as well.

At the moment i am using a JSF-Filter to re-sort the order of the stylesheet's/scripts and then compress them if they are not compressed. 
Eventually this could be a solution to restore the right order of stylesheets and script ?

I attached my current filter as example - it is working without any problems by now 
and also compress the xhtml-site as well.
It must be renamed to .java because only .txt is accepted for upload...

[CompressResponseFilter.txt](https://github.com/primefaces/primefaces/files/1358652/CompressResponseFilter.txt)
[CharResponseWrapper.txt](https://github.com/primefaces/primefaces/files/1358653/CharResponseWrapper.txt)

**Comment by melloware** [comment]
So I like the idea of this but I personally think this filter is doing too much.   I use PrimeFaces Extensions optimizer which compresses CSS and JS so its compressed once inside the WAR/JAR and not recompressed on the fly every time using CPU.  https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Maven-plugin-for-web-resource-optimization

But I think @tandraschko gets your point to move the JS to the bottom of the page.

I have used the OmniFaces DeferredScript component to load JS like Bootstrap in the past.  http://showcase.omnifaces.org/components/deferredScript

**Comment by tandraschko** [comment]
yup, this issue only about one thing: move all scripts tags dynmically to the bottom, before the body ends.

I think the best way is to do this via a custom responsewriter probably. We can there also merge the script contents.

**Comment by tandraschko** [comment]
I also played with this idea in the past, no idea why i never finished it. It should also be faster if 1 script tag contains 10x PrimeFaces.cw instead of 10 script tags with each a single PrimeFaces.cw call

**Comment by ssibitz** [comment]
The "compression" - part is only needed for compressing the whole xhtml-page, but not the resources - so it's not needed in primefaces and "optional" used by me in only special cases.
(It's only a modified source so you can read it !)

But the second part which optimizes the tag's dynamically will be the thing that could handle the resources for primeface...

I also use the omnifaces DeferredScript-Handler, but also this script's are not on the bottom by default !
The browser have to wait until all resources have been loaded instead of rendering the styles first and then process the script's (Also async loading of scripts doesn't work then...) ...

**Comment by tandraschko** [comment]
Got a 80% working solution now which just wraps the ResponseWriter.
Will share my solution later, not sure if i can do a 100% solution until RC1.

**Comment by tandraschko** [comment]
90%-100% - works fine for all cases now in MyFaces ;)

**Comment by melloware** [comment]
Excellent!

**Comment by ssibitz** [comment]
Perfect :-)

**Comment by tandraschko** [comment]
Some "chars" statistics from a "normal" sized view:
- script includes (script src="..."): 9
- script blocks (script with js content, like produced by WidgetBuilder): 26

all script blocks are now merged inside a single script block, which means we save here 25 script tags.
A script tag looks like: <script id="form:msgs_s" type="text/javascript">...</script>

So, for each script tag, we save around ~60 chars.
60x25 = 1500 chars which will be saved

additionally, we can e.g. replace "PrimeFaces" which "pf", which saves around 200 chars.

So it saves around 1700 chars, around ~2kb, which is quite a lot actually.

I will now add it to PrimeFaces, so you can play a little bit with it. It will be deactivated by default ofc.

Will commit it in this hour.
Would be great if someone could give it a try on Mojarra and maybe somehow could do a "benchmark" how much faster the page responds on the first visit.

**Comment by tandraschko** [comment]
Done! Also please try without omnifaces first, not sure what happens ;)

You can activate it via your faces-config in your application:

    <factory>
        <faces-context-factory>org.primefaces.application.resource.ScriptCollectingFacesContextFactory</faces-context-factory>
    </factory>

**Comment by melloware** [comment]
I will give it a shot and remove my Omnifaces optimizations.

**Comment by tandraschko** [comment]
What did you used from omnifaces exactly? For merging X files into 1?

**Comment by melloware** [comment]
http://showcase.omnifaces.org/resourcehandlers/CombinedResourceHandler

**Comment by melloware** [comment]
I tried running the Showcase with Mojarra with this factory enabled and nothing seems to work.  I get Console errors like the page is not loading properly.  Not sure if this is related...

```
Oct 05, 2017 4:25:16 PM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
SEVERE: null
java.lang.StackOverflowError
        at javax.faces.context.ResponseWriterWrapper.cloneWithWriter(ResponseWriterWrapper.java:367)
```

**Comment by ssibitz** [comment]
I am currently using Mojarra / Primefaces / Omnifaces / Bootstrap v4 (Beta) / SASS (As CSS-Framework, so i don't need to compress because it's done automatically at saving in IDE) in my project.

Are you using Omnifaces directly by including it or using only the code-parts as source for combining ?

This could be important for other user's if they don't need to include Omnifaces anymore...

**Comment by tandraschko** [comment]
Will check mojarra now

**Comment by tandraschko** [comment]
works in mojarra now but there are 2 JS errors in the showcase. Will check it later why it occurs.

**Comment by tandraschko** [comment]
Hmm not sure but it seems that the order is not not correct.
If i change
        <h:outputScript name="main/js/index.js" target="head" />
to target=body, it works

however, one small js error occurs about a missing ";"

**Comment by ssibitz** [comment]
Please do not forget that also all Stylesheets(CSS) should be merged into 1 file 
and add them to the head-tag. 
At the moment some stylesheets are in the body-tag which i also move to the head manually by using my filter as workaround...

**Comment by tandraschko** [comment]
It won't merge any files, you still have to use OmniFaces or other things. Merging everything into 1 file is also not the best solution.

**Comment by tandraschko** [comment]
@melloware should work in the showcase now ;)

**Comment by tandraschko** [comment]
Just to clarify:
This "extension" just moves all scripts to the bottom. Also it merges inline-scripts into one single tag. It won't merge included scripts (script src="...") into a single file.

**Comment by melloware** [comment]
@tandraschko 2 things...

1. This works awesome in Mojarra in the showcase.  I feel like the pages are loading way faster than before.  Really snappy response time.

2. I agree with your on merging into 1 script.  We have had issues on some of our projects where the merged file has the JS in the wrong order or causes issues.

+100 for this solution!

**Comment by tandraschko** [comment]
great :)

I think we already do it correct in PrimeFaces:
in general, we have grouped our JS in 3 big files (some special components require additional js but i skip it now...):

jquery.js
core.js
components.js

jquery.js can be used separately, also if you have pages without primefaces components. So it makes sense to leave it as it it.

core.js is really our very very core. In a modern application, which maybe uses bootstrap for styling, users might even only use p:ajax on basic input fields (input jsf:id="..."). So seperate this from components.js also makes sense

components.js is a pool all commons components.

I think it's ok to load 3 files from PF perspective.
If you include (lets say) 10 custom javascript in your application, it make sense the merge those 10 files into 1 big file. But this should be done at build time if possible.

**Comment by tandraschko** [comment]
and FYI: works in both myfaces and mojarra

**Comment by melloware** [comment]
i agree i wouldn't change anything else.  This is a huge optimization!

**Comment by tandraschko** [comment]
Great!
DOMContentLoaded without is around ~800ms for showcase/ui/misc/responsive.xhtml, with the optimization it's ~660ms.
Thats really cool.
We may just think about if we can so a similar thing for ajax requests.

**Comment by tandraschko** [comment]
Great!
DOMContentLoaded without is around ~800ms for showcase/ui/misc/responsive.xhtml, with the optimization it's ~660ms.
Thats really cool.

We be great if you could test it in a real work application (works fine in mine), to see if everytrhing is working.

**Comment by melloware** [comment]
I am going to to 2 things...

1. Test in the PFE showcase next.

2. See if I can get permission to test one of our production apps which is Jboss 6.4 EAP with real world scenario.

**Comment by ssibitz** [comment]
In which version do you plan this enhancement to be included ?
Are there any plan ?

**Comment by tandraschko** [comment]
6.2 - but currently i'm unsure if there is a any benefit.
I created a blog post today (not released yet) but i can't measure any difference in my real-world application. The DOMContentLoad performance is sometimes 1-3% faster. Most of the time it's exactly the same.

**Comment by tandraschko** [comment]
Hmm, it could also be that DOMContentLoad is fired after the script executing somehow.
Not sure how i can measure it feels really much faster in the showcase.
Do you guys have a idea how to measure the benefit? Would like to create a blog post, also the promote this feature.

**Comment by melloware** [comment]
@tandraschko I agree it definitely "feels" faster in both PF and PFE showcases.  I was trying to do the same thing you were with Chrome Tools but I can't trust how accurate those timings actually are.   

I think its worth leaving this code and since its turned on with faces-config you could always caveat it with "use at your own risk"?

**Comment by tandraschko** [comment]
yep
probably i will also add a context-param to avoid the faces-config
probably i also try to something for ajax-requests
i think it would also improve the rendering when all DOM elements are replaced first and after that, script tags are executed

**Comment by ssibitz** [comment]
What's about Google PageSpeed - Does it give bether "points" when using this new "feature" ?

**Comment by tandraschko** [comment]
No idea, google page speed can't be used for intranet applications. But you just try this feature and give us feedback ;)

**Comment by ssibitz** [comment]
OK, I will try it and give a feedback on my real application...

**Comment by ssibitz** [comment]
So, i now tested it with my Application on the server and making Screen-Shot's of the Performance Before/After that of Google's PageSpeed.

> In general it looks very good when you set the script-target to "body" to be sure that all "added" scripts are added last. Otherwise it does not work because of a wrong order. The Script Tag's also must be in the header otherwise if they are inserted in the body i lost the script's completly !
so e.g.:
```
...
<body>
<script src="test.js"></script>
</body
```
When you do that you will lose the test.js because only the script's in the header tag will be rendered -  
I am right with this ?

What i see is that the Omnifaces DeferedScript-Handler does not work anymore - 
I will analyze and Report what's the issue...
Also the JavaScript-TAG 
`/* <![CDATA[ */ and /* ]]> */ `
is loosing when using the new renderer, but it seems to work also without this tag...

Here are now the Performance-Screenshots from PageSpeed (Without using my compression algorithm):

_1.) PageSpeed Summary Before using optimizing (Primefaces 6.1.6)_
![pagespeed-requests-overview-before-optimize](https://user-images.githubusercontent.com/652355/31437073-4f005ddc-ae84-11e7-9696-83a8ec484bd7.png)

_2.) PageSpeed Detail - Parsing (Primefaces 6.1.6)_
![pagespeed-requests-defer_parsing_of_javascript-before-optimize](https://user-images.githubusercontent.com/652355/31437096-64ee46f4-ae84-11e7-93af-b511fa6a41d9.png)

_3.) PageSpeed Detail - Optimize the order... (Primefaces 6.1.6)_
![pagespeed-optimise_the_order_of_styles_and_scripts-optimize](https://user-images.githubusercontent.com/652355/31437131-84c766ea-ae84-11e7-9b13-2b3b23a3714c.png)

_4.) PageSpeed Summary After using optimizing (Primefaces 6.2 - Current Build from GitHub)_
![pagespeed-requests-overview-after-optimize](https://user-images.githubusercontent.com/652355/31437191-c26af458-ae84-11e7-9fe9-545ff3d7a14c.png)

_5.) PageSpeed Detail Optimize Images (Primefaces 6.2 - Current Build from GitHub)_
![pagespeed-optimise images-after-optimize](https://user-images.githubusercontent.com/652355/31437237-d9ac4db0-ae84-11e7-9c0e-6306030bac17.png)
By the way - is this image generated at runtime ?

**Comment by tandraschko** [comment]
Those images are not generated at runtime. Have a look at here: https://github.com/primefaces/themes

In overall, it looks great! I don't know what OmniFaces is doing exactly but also not sure if we can support every special case.

**Comment by ssibitz** [comment]
OK, i also can now see the problem with omnifaces in the Debugger:
It seems that's a very small bug, but in Omnifaces or in Primefaces ?!

In the Class ScriptCollectingResponseWriter when the String comes in the write(String str) function the high comma is losed in the string:

```
    @Override
    public void write(String str) throws IOException {
        if (inScript) {
            inline.append(str);
        }
        else {
            getWrapped().write(str);
        }

```

1. Call) write with String str = OmniFaces.DeferredScript.add(**'**
   inline = OmniFaces.DeferredScript.add('
2. Call) write with String str =  /EcoCalcDD4Web/javax.faces.resource/js/bootstrap.min.js.skf
  inline = OmniFaces.DeferredScript.add('/EcoCalcDD4Web/javax.faces.resource/js/bootstrap.min.js.skf
3. Call) write with String str = ); 
  inline = OmniFaces.DeferredScript.add('/EcoCalcDD4Web/javax.faces.resource/js/bootstrap.min.js.skf);

-> Here is the closing high comma (') missing, so the script is not working right.

In the "Original" version of primefaces-6.1.6 i am getting the following string:
OmniFaces.DeferredScript.add("EcoCalcDD4Web/javax.faces.resource/js/bootstrap.min.js.skf");

**Comment by tandraschko** [comment]
Not sure, here is the OmniFaces code: https://github.com/omnifaces/omnifaces/blob/develop/src/main/java/org/omnifaces/renderer/DeferredScriptRenderer.java#L66

**Comment by tandraschko** [comment]
I think we need to overwrite the #write(char) method

**Comment by tandraschko** [comment]
Commited it. Could you please give it a try?

**Comment by ssibitz** [comment]
So, now i know exactly what's the problem with the missing high-comma by 
debugging it into the omnifaces-sources and primefaces-sources:

The Class ScriptCollectingResponseWriter does not overwrite the write function 
for a single character, so you lose any single character which should be rendered:

So the solution is simple by adding the following function to the class 
and also omnifaces will work right now in my testcase ;-)

```
    @Override
    public void write(int c) throws IOException {
        if (inScript) {
            inline.append((char) c);
        }
        else {
            getWrapped().write((char)c);
        }
    }
```

**Comment by tandraschko** [comment]
Cool, thanks! Commited!

**Comment by ssibitz** [comment]
Now it work's right - Perfect !

The only thing which user's should know is that they append their own external JavaScript's in the head and setting the target to body - then all Script's are working right in combination with Primefaces !

**Comment by tandraschko** [comment]
Removed the FacesContext and added a context-param to enable it (primefaces.COLLECT_SCRIPTS).

Hmm, whats wrong with the order?
If you have a custom script (e.g. h:outputScript target=head), will it be rendered after the primefaces scripts currently? So the order, without my changes, is correct?

If the CollectScripts is activated, the order somehow is not correct anymore?

**Comment by melloware** [comment]
I am assuming lowercase "p" like in other PF context params?

```xml
    <!-- enable script collecting and moves all script to end of body -->
    <context-param>  
        <param-name>primeFaces.COLLECT_SCRIPTS</param-name>  
        <param-value>true</param-value>  
    </context-param>
```

**Comment by ssibitz** [comment]
Sorry, my mistake - Everything is working fine now :-)

The problem with the custom script target was also the missing character renderer which makes 
the problem (With the Omnifaces defferedScript and also h:outputScript). 

Now also this is working right in my application and all scripts are in the order as exepted...

**Comment by tandraschko** [comment]
Great! :)

@melloware yep, of course

**Comment by tandraschko** [comment]
Ajax seems to be more complex, will skip that case for now.

**Comment by ssibitz** [comment]
**At one thing i have a problem with the 6.2 - build,
so should i create a new ticket for that ?**

When i have a SelectOneMenu it's no longer possible for me 
to select an entry by using the keyboard (up-/down) .
(Only by clicking on the drop-down...)

I also tried to switching off the "Script Collector" but that does not change anything...

**Comment by melloware** [comment]
@ssibitz that is definitely a new bug as it doesn't relate to this script collector.

**Comment by tandraschko** [comment]
New problem -> new ticket ;)
It would be great if you could also analyze it as i assume it's still working with 6.1.6?

**Comment by tandraschko** [comment]
(And you need to provide a good and small example, the navigation with keyboard is working fine for me with arrow keys)

**Comment by ssibitz** [comment]
Yes, it's working right in Primefaces 6.1.6.

I switched to 6.2-SNAPSHOT only for Testing the "Script Collector" which works fine
and today i noticed that the SelectOneMenu has a problem in 6.2-SNAPSHOT "only" ...

**Comment by ssibitz** [comment]
So I created a new ticket for that:  #2807

**Comment by melloware** [comment]
@tandraschko Found an issue running the Showcase with CollectScript on for this page /showcase/ui/data/datatable/edit.xhtml   The page doesn't render.  When I remove CollectScripts it works fine.

**Comment by tandraschko** [comment]
Hmm, not idea so far.
I tried to remove the optimizations i did (minimizing the inline script) but still doesn't work.
Seems like there is an endless loop?

**Comment by tandraschko** [comment]
Did you also check all other views?
Would be a shame if we could not activate it because of one single view :D

**Comment by melloware** [comment]
I will keep checking other views but so far this was the only one I found with this issue.

**Comment by jxmai** [comment]
Actually, there are many more observed by just randomly clicking the showcase: http://localhost:8080/showcase/ui/ajax/partialSubmit.xhtml, http://localhost:8080/showcase/ui/ajax/search.xhtml...

So this feature is definitely not mature enough to put in real world use at the moment.

**Comment by tandraschko** [comment]
Its more mature as you think :P i already use it in production, but the code is very structured and new

**Comment by jxmai** [comment]
> i already use it in production

For experimental purposes, I just set the collect script on one of our real projects, and I can replicate the infinite loop. :D. so be cautious...

**Comment by jxmai** [comment]
@tandraschko @melloware Here is the analysis that could be helpful for you to fix the problem

There is clearly a logical flaw that is causing infinite recursive calls.

The infinite loop is located in the following method

https://github.com/primefaces/primefaces/blob/4d3a721097aaeb45ce9d11bdc5fbf43f73b27221/src/main/java/org/primefaces/application/resource/CollectScriptsResponseWriter.java#L137-L169

---


First, please take a look at the following for loop

```java
for (int i = 0; i < state.getIncludes().size(); i++) {
                String src = state.getIncludes().get(i);
                if (src != null && !src.isEmpty()) {
                    getWrapped().startElement("script", null);
                    getWrapped().writeAttribute("type", "text/javascript", null);
                    getWrapped().writeAttribute("src", src, null);
                    getWrapped().endElement("script");
                }
            }
```

`state.getIncludes().size()` is not a constant that is kept increasing by 


```java
state.addInclude(include);
```

in 

```java
if ("script".equals(name)) {
            inScript = false;

            state.addInline(inline);
            state.addInclude(include);

            include.setLength(0);
            inline.setLength(0);
        }
```

No matter how `i` increases, it can never catch up with `state.getInclude().size()` which always calls `getWrapped().endElement("script");` that can increase the size() by 1 via `state.addInclude(include);`.

Let's see with your own eyes:

![image](https://user-images.githubusercontent.com/10467831/32193201-8caec308-bd84-11e7-8cc1-b441c99da59e.png)

![image](https://user-images.githubusercontent.com/10467831/32193224-9bb796f4-bd84-11e7-8882-dd35347b1b8a.png)

**Comment by melloware** [comment]
Yep that for loop needs to use a constant value or iterator might do it.

**Comment by jxmai** [comment]
One step further, normally the `getWrapped().endElement("script");` should not call `public void endElement(String name)` itself, when it happens the loop will occur.

**Comment by jxmai** [comment]
~~I don't see how `getWrapped().endElement()` can actually call the `endElement()` method in `CollectScriptsResponseWriter`. :confused: but it is actually happening.~~

---

There are two `wrapped` (one in the parent and one in the sub class). The shadow technique should be avoided since it is hard to debug / easy to make mistakes.  PMD (https://pmd.github.io/) will give warning if we try to code like this.

So for some reason, the inner `getWrapped()` in the `getWrapped.endElement('script')` is coming from its parent class. Calling `endElement('script')` will trigger a polymorphic call back to its child which is the `endElement` in`CollectScriptsResponseWriter`

and then infinity loops will occur  :loop: :loop: :loop: ...

**Comment by tandraschko** [comment]
fixed ;)

**Comment by jxmai** [comment]
Working now :+1:

**Comment by tandraschko** [comment]
Thats really crazy how fast it seems for the human eye - there is actually no need for SPA...

**Comment by jxmai** [comment]
Maybe we can merge the showcase pull from melloware (https://github.com/primefaces/showcase/pull/40)  ? The showcase is working now

**Comment by tandraschko** [comment]
done!

**Comment by jxmai** [comment]
OK, that was fast :+1:

**Comment by tandraschko** [comment]
:D little bit funny :D
the last years i did sooo many micro optimizations in PF and MyFaces like reducing object instances to a minimum... the effect is quite small actually for single users but this change feels like you optimize the JSF rendering from 500ms to 50ms....

**Comment by jxmai** [comment]
the number of network resources requests is always the biggest bottleneck. Trading network time to cpu time is a very wise move :smile:

**Comment by tandraschko** [comment]
yep :D

**Comment by melloware** [comment]
This optimization is a huge one for PF.  I can’t wait to incorporate into my production apps when 6.2 goes final!

**Comment by jxmai** [comment]
Agreed 😄 . This optimization might be one of the best ever in Primefaces history 🔆 The page loading speed is insanely fast after setting up the flag.

**Comment by ssibitz** [comment]
It sounds very good and feels like "light speed" when i test it in real application on our Amazon-AWS-Server with much CPU-Power and a lot of RAM.

When i activate this enhancement and combine it with the Primefaces Cache for Menu/Sidebars and also "static" content it feels like using a locale application -

I think it was a good decision to implement this enhancement into Primefaces ;-)

**Comment by tandraschko** [comment]
Yep - also thanks to you @ssibitz! Finally someone give me the "push" to do this!

**Comment by wsaca** [comment]
Hi guys, I'm trying this new feature, but I there is a problem with BlockUI.

Try the showcase:
http://localhost:8080/showcase/ui/misc/blockUI.xhtml

The next error is displayed:
`TypeError: this.cfg is undefined`

**Comment by tandraschko** [comment]
I don't think that is releated to this change - BlockUI also crashed when the feature is disabled.

**Comment by tandraschko** [comment]
I fixed it but next time create a own issue please.

**Comment by wsaca** [comment]
I put this error here because in my project I'm getting the same problem only when I enable this feature. anyway, thank you.

**Comment by tandraschko** [comment]
FYI: will rename to setting to MOVE_SCRIPTS_TO_BOTTOM

**Comment by tandraschko** [comment]
Would someone write an small articel about the feature + some measurements? Maybe we can push it blog.primefaces.org
I think the feature is good enough to promote it with details.

**Comment by melloware** [comment]
I would love to write something up I am just having a hard time using the Chrome Tools quantifying the speed difference other than "my eyes can see the screen is faster with no flicker". :)

**Comment by ssibitz** [comment]
I think the best would be to make a simple screenshot from the current showcase / pagespeed:
First with the feature disabled and then same with the feature enabled.

Then you can see the difference which is a high rating from Google PageSpeed which
also means that an optimized site like this is "prefered" in search result's from Google !!

Is there a way to also bring a Primefaces 6.2 Release Candidate online with the MOVE_SCRIPTS_TO_BOTTOM disabled ?
Why ? 
Because then it's possible to run an advanced site analyzer over the public site
and this tool is able to generate a detailed performance analyzing !

**Comment by ssibitz** [comment]
I currently checked the Primefaces-Showcase by a Online WebSite Performance Checker
and the current Result is like from Google Pagespeed with 84% Performance Counter
with the MOVE_SCRIPTS_TO_BOTTOM Feature enabled as i can see as all script's are on the bottom:

So using https://www.primefaces.org/showcase/ on this site:
[https://gtmetrix.com/](https://gtmetrix.com/)

Result's in the following analyze result:
![2018-01-12 07_13_02-latest performance report for_ https___www primefaces org_showcase_ _ gtmetrix](https://user-images.githubusercontent.com/652355/34862138-fbc558d8-f768-11e7-957e-35f33b90337d.png)

As you can see on the image the highlighed lines are optimized by this feature
and i think also the the point **"Put CSS in the document head"** comes from here
because all Script's are moved to bottom so only stylesheets in header ;-)

**The "other" point's can also be optimized very simple:**

_Enable gzip compression_
This must be enabled on the Server or simple using Omnifaces for that:
http://showcase.omnifaces.org/filters/GzipResponseFilter

_Specify image dimensions_
The width/height tag's have to be added to any images

_Leverage browser caching_
Can also be activated by using Omnifaces:
http://showcase.omnifaces.org/filters/CacheControlFilter

_Minify JavaScript/CSS/HTML_
Using Primefaces-Extensions Resource Optimizer Plugin for static resources:
https://github.com/primefaces-extensions/resources-optimizer-maven-plugin
and a simple JSF-Filter using Google Closure Compiler and YUI Compressor for the dynamic (X)HTML

_Specify a Vary: Accept-Encoding header_
This must be enabled on the Server or simple using Omnifaces for that:
http://showcase.omnifaces.org/filters/GzipResponseFilter

_Remove query strings from static resources_
Use the Omnifaces Resource-Filter for that:
http://showcase.omnifaces.org/resourcehandlers/CDNResourceHandler
So you can also redirect all static resources (like FontAweSome) to an external 
CDN-Provider

**Comment by ssibitz** [comment]
So by the way a question:

Why not using OmniFaces as JSF utility library for the **showcase** to show what speed is possible ?
This could make the showcase as fast as possible with about nothing
more to do as configure Omnifaces in the maven-pom and configure the settings:

* GZip-Compression
* CacheControlFilter
* CDN-Resources Handler
* Combined-Resource Handler

**By the way:**
OmniFaces Showcase is using Primefaces for the DemoSite ;-)


**The only steps to do are:**

_1.) Update the Inline-Jetty-Server to latest Release-Version in pom.xml:_
```
			<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-maven-plugin -->
			<plugin>
			    <groupId>org.eclipse.jetty</groupId>
			    <artifactId>jetty-maven-plugin</artifactId>
			    <version>9.4.8.v20171121</version>
                <configuration>
                    <webAppConfig>
                        <contextPath>/showcase</contextPath>
                    </webAppConfig>
                    <scanIntervalSeconds>5</scanIntervalSeconds>
                </configuration>
			</plugin>

```

_2.) Add Omnifaces depency in pom.xml:_
```
		<!--  Omnifaces -->        
		<dependency>
		    <groupId>org.omnifaces</groupId>
		    <artifactId>omnifaces</artifactId>
		    <version>3.0</version>
		</dependency>  

```
_3.) Configure faces-config.xml:_

```
    <application>
        <action-listener>org.primefaces.application.DialogActionListener</action-listener>
        <navigation-handler>org.primefaces.application.DialogNavigationHandler</navigation-handler>
        <view-handler>org.primefaces.application.DialogViewHandler</view-handler>
        <navigation-handler>org.primefaces.mobile.application.MobileNavigationHandler</navigation-handler>
        <locale-config>
            <default-locale>en</default-locale>
        </locale-config>
        <el-resolver>org.primefaces.application.exceptionhandler.PrimeExceptionHandlerELResolver</el-resolver>
        <resource-bundle>
            <base-name>build</base-name>
            <var>build</var>
        </resource-bundle>
        
        <!-- Add Omnifaces Resource handler here in this order: -->
	    <resource-handler>org.omnifaces.resourcehandler.CDNResourceHandler</resource-handler>
	    <resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>
    </application>

```

_4.) Configure web.xml for using Omnifaces by adding this:_

```
    <!--  Optimizations by Omnifaces -->
	<filter>
	    <filter-name>cache2days</filter-name>
	    <filter-class>org.omnifaces.filter.CacheControlFilter</filter-class>
	    <init-param>
	        <param-name>expires</param-name>
	        <param-value>2d</param-value>
	    </init-param>
	</filter>    
	<filter-mapping>
	    <filter-name>cache2days</filter-name>
	    <url-pattern>*.css</url-pattern>
	    <url-pattern>*.js</url-pattern>
	    <url-pattern>*.jpg</url-pattern>
	    <url-pattern>*.gif</url-pattern>
	    <url-pattern>*.png</url-pattern>
	</filter-mapping>	
    
  <filter>
    <filter-name>gzipResponseFilter</filter-name>
    <filter-class>org.omnifaces.filter.GzipResponseFilter</filter-class>
    <init-param>
      <param-name>threshold</param-name>
      <param-value>100</param-value>
    </init-param>
    <init-param>
      <param-name>mimetypes</param-name>
      <param-value>
        text/plain, text/html, text/xml, text/css, text/javascript, text/csv, text/rtf,
        application/xml, application/xhtml+xml, application/javascript, application/json,
        image/svg+xml, image/jpeg, application/pdf
      </param-value>
    </init-param>
  </filter>
  <filter-mapping>
    <filter-name>gzipResponseFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>
  
	<context-param>
	    <param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS</param-name>
	    <param-value>
	        js/script1.js=http://cdn.example.com/js/script1.js,
	        somelib:js/script2.js=http://cdn.example.com/somelib/js/script2.js,
	        otherlib:style.css=http://cdn.example.com/otherlib/style.css,
	        somelib:images/logo.png=http://cdn.example.com/somelib/logo.png
	    </param-value>
	</context-param>  

```

Only the params for the CDN-Resource-Handler must be "adapted" 
for e.g. FontAwesome:
primefaces:/fa/font-awesome.css=https://use.fontawesome.com/releases/v5.0.4/css/all.css

That's all - but i can't test it at the moment because the latest showcase
does not work on my locale machine (With the latest jetty-server)...

**Comment by ssibitz** [comment]
I am also using this optimizes in my webproject (Primefaces+Omnifaces)
and so i am reaching nearly 100 percent of ranking from Google PageSpeed's ;-)

The only think which is also not optimal in my site is the point:
_"Specify image dimension"_
**@melloware :** 
This could be a new image-component which resizes images / losless optimized images
on the server - as an idea ?

**Comment by melloware** [comment]
@ssibitz To me that component would be no good as it would have to use CPU to optimize the image every time it was retrieved.  Most web guides suggest if you need a 100x100 image don't use a 500x500 an let the browser scale it, actually make a 100x100 version and use that.

See this suggestion from Browser Diet: https://browserdiet.com/#scale

**Comment by ssibitz** [comment]
Yes, that's in theory right to use images in the right size as suggestion.

But in practice with responsive design or a marketing which only want the biggest image on the start sceeen you don't always have a fix size of images or not the "best" size !
Also on other behavior's that it's very time intensive to re-scale all images to a special size
like in the Primefaces-Demo or in an application where the right size must be evaluated before 
and most then it's only set by image-size, but the images are not rescaled.

I dont't think to optimize an image every time, 
but once created in an special given folder from the parameters (web.xml)
makes it also possible to easily replace an image without re-deploying.

If the user want then a new image he have to be sure that the "image-caching-folder" is clean. 
Then the component will generate images in the given sizes and also generate the style-sheets
for it automatically.

So the component could look something like this:
`<pe:OptImage id="OptImage" name="LogonImage" library="images" width="1000" height="auto" minScreenWidth="800"/>
`
Which generates an image like this in a special folder **once** the image have to be shown:
`LogonImage_1000xauto.jpg`

An a stylesheet which hides the image if the screenwidth is smaller than 800px.

**Comment by ssibitz** [comment]
When you don't want't a component like this in PrimeFaces-Extensions build
i will build a specialized component outside the framework which exactly is doing this.

**Why I am needing this ?**
I need this in my production system to:
* Easily cache an image in a special folder
* Easily replace an image (e.g. background or logon image) by replacing a file and not doing a redeploy
* Easily replace product images of our articles if they are wrong or newer
* I also to generate different image sizes and automatically generate the responding css-styles with breakpoints
* I eventually need to generate Embedded SVG-Images from stored SVG-Images 
so that i can manipulate them by using e.g. D3.JS or  Raphaël.js
We have to enter dimensions on our product directly and that then can be done 
be using the SVG-Images. But currently no component can render SVG-Images in the right way so 
that they can be manipulated by SVG-Libraries...
* When Image size is given in percent then recalculate the pixels once and also store it on the special path...

And at last the performance that the browser then has no need to rescale any image
which also is if the user is working with percentage values.

**Comment by melloware** [comment]
if you are going to build it anyway on Github then we can always review with others to determine whether it should go in PFE.   I would have to see how the component worked and whether it was truly a need.  Rendering SVG is definitely understandable but it would be nice if you really need these features if you did them for p:graphicImage and submitted a PR.

**Comment by tandraschko** [comment]
Please move your discussion - this is unrelated to that feature ;)

**Comment by ssibitz** [comment]
I will create a new discussion thread in the Primefaces-Extensions Forum
and remove my discussion from here.
@melloware : Please also move your discussion-writings to here:

[https://forum.primefaces.org/viewtopic.php?f=14&t=53893](https://forum.primefaces.org/viewtopic.php?f=14&t=53893)
