### ISSUE TITLE
DataTable: rowExpansion treated as selectable row by range selection

### ISSUE THREAD

**Issue by 4a6f42** [primefaces/primefaces#2782]
## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
Holding shift to select a range of dataTable rows submits the accordings rowKeys of actually selectable rows. Either all rowExpansions in range are highlighted or none.

## 3) Actual behavior
rowKeys of rowExpansions are included in the list and empty, leading to a HTTP header like `table_selection=1,2,,3,4,`
A dataTable without a LazyDataModel would return null for rowKey "". If this is expected of LazyDataModel.getRowData(final String rowKey) a hint for that in the manual would be appreciated.

Open rowExpansions in range are highlighted, rowExpansion in range opened after the selection are not highlighted.

## 4) Comments
I think the issue is  in dataTable.js:
``
selectRowsInRange: function(row) {
        var rows = this.tbody.children(),
``
Sth. like
``
selectRowsInRange: function(row) {
        var rows = this.tbody.children('.ui-datatable-selectable'),
``
might be a good approach. But while this fixes both issues, it also leads to some confusion with the row index, increasing the range by the number of open rowExpansions ...
As I've adjusted my LazyDataModel the only real annoyance is the different highlighting.

**Comment by melloware** [comment]
I just tested this and in 9.0-SNAPSHOT this appears to be fixed and its selecting the correct rows and not the expansions.  We can always reopen if its still an issue but I cannot reproduce it.
