### ISSUE TITLE
Bootstrap theme, undesired data-table scrollbar

### ISSUE THREAD

**Issue by marcodelpercio** [primefaces/primefaces#2786]
Hi,

Initially we thought this was a bug introduced by our CSS code but actually the bug can be experienced in live showcase right now on the primefaces website:

Open: https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml 
and from PFThemes select the Bootstrap theme
you'll see that only in Chrome an horizontal scrollbar at the bottom appears

Environment
- PrimeFaces version: 6.1.4 (the version currently online)
- Does it work on the newest released PrimeFaces version? No 
- Does it work on the newest sources in GitHub? Not sure
- Affected browsers: Chrome only

**Comment by tandraschko** [comment]
A PR is very welcome.

**Comment by marcodelpercio** [comment]
Looks like this is a non-regression issue in Google Chrome. There's a jsbin that proves it on a plain table
[https://bugs.chromium.org/p/chromium/issues/detail?id=771143](url)

**Comment by tandraschko** [comment]
So can we close this here?

**Comment by jxmai** [comment]
> So can we close this here?

I have seen this issue before but there is nothing primefaces can do since it is a chrome bug. so this issue can be closed.

---

And here is the jsbin link: http://jsbin.com/vuniyof/edit?html,output that was mentioned above for verification purposes
