### ISSUE TITLE
Primefaces Diagram Javascript Error

### ISSUE THREAD

**Issue by salviof** [primefaces/primefaces#2787]
## 1) Environment
- PrimeFaces version: 6.1.0
- Mojarra 2.3.0
-Java 1.8
- Affected browsers: All Brownsers

## 3) Actual behavior
Using same Datamodel example in (https://www.primefaces.org/showcase/ui/data/diagram/flowchart.xhtml)

I Receve this javascript error, and conections are not showing
----->
**TypeError: Cannot read property 'parentNode' of null
    at r.endpointAdded (diagram.js.xhtml?ln=primefaces&v=6.1:1)**

## 4) Steps to reproduce
 Try reproduce that: (https://www.primefaces.org/showcase/ui/data/diagram/flowchart.xhtml).

## 5) Sample XHTML
(https://www.primefaces.org/showcase/ui/data/diagram/flowchart.xhtml).
..

## 6) Sample bean
(https://www.primefaces.org/showcase/ui/data/diagram/flowchart.xhtml).
..

**Comment by jxmai** [comment]
I don't see any error in the showcase using both Chrome and FF.

> I Receve this javascript error, and conections are not showing

The connections are working properly

![image](https://user-images.githubusercontent.com/10467831/31397880-c6df7500-adac-11e7-8bd3-98eecccef02b.png)

**Comment by tandraschko** [comment]
works also fine in trunk.
