### ISSUE TITLE
ContentLength for FileDownload

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#279]
Add contentLength option to StreamedContent and use it in FileDownload component.

**Comment by sergi-mm** [comment]
When this feature will be available?

**Comment by tandraschko** [comment]
No plans currently, but you can do a PR

**Comment by sergi-mm** [comment]
Hello @tandraschko, I've just created a pull request with this feature: https://github.com/primefaces/primefaces/pull/1618. 

Hope you can integrate with your code.

**Comment by tandraschko** [comment]
Applied, thanks for your PR!

**Comment by sergi-mm** [comment]
Hi @tandraschko, thanks for accepting my PR. Will be this feature released in any PF Elite before the 6.1 version release?

**Comment by tandraschko** [comment]
Don't know sorry. Usually i don't commit stuff to elite as i'm not a elite user.
