### ISSUE TITLE
FileUpload: check allowTypes on server side

### ISSUE THREAD

**Issue by rcroonenberghs** [primefaces/primefaces#2791]
## 1) Environment
- PrimeFaces version: 6
- Application server + version: wildfly-10.1.0.Final
- Affected browsers: All

## 2) Expected behavior

When uploading a file which is not in the allowedtypes, a error is shown on screen and upload is blocked. But if you tamper with the post, you can change a valid file to a file extension that would not be allowed. (tested via Burpsuite) Expected behaviour would be that on server side, the allowedtypes would be checked as well.

## 3) Actual behavior

The allowedtypes is not checked on server side.

## 4) Steps to reproduce

submit upload and tamper the post and change the file extension.

## 5) Sample XHTML
```xml
<p:fileUpload id="fileupload" fileUploadListener="#{documentlist.handleFileUpload}"
		            mode="advanced"
		          allowTypes="/(\.|\/)(gif|png|jpe?g)$/i"					            
		            />
```
## 6) 
public void handleFileUpload(FileUploadEvent event) {

**Comment by kukel** [comment]
checking  allowed *types* based on filename extensions (not on content) is confusing. It should in the documentation (and showcase) be explicitly stated that content is not checked! (allowed 'extensions' would have been a better 'name')

**Comment by melloware** [comment]
@tandraschko @cnsgithub Can you add the security label to this.  Our Pentration testers also reported this issue.

**Comment by cnsgithub** [comment]
@melloware Just for info, I am not allowed to add any labels. :wink: Btw, are you allowed to share what your penetration testers found besides this issue? I'd be glad having those vulnerabilities fixed.

Just checking the extensions will always be unsafe. However, I agree with @kukel that `allowTypes `should be renamed to clarify that we are not doing any content type checks. We could even use a more abstract attribute name like `allowFilenameRegex` (or something shorter), as the check is not limited to just the extensions. I also agree that this regex should be validated against at the backend side once again.

The more tricky part would be to introduce content type checking. We could use something like `java.nio.file.Files.probeContentType(Path) (`Java 7), however that would most probably not work without having installed additional `FileTypeDetectors`, e.g. Apache Tika.

Some further reading: https://www.owasp.org/index.php/Unrestricted_File_Upload

**Comment by melloware** [comment]
@cnsgithub  We pay a third party firm to penetration test our apps and we usually score very high mostly because of no SQL Injection, the JSF ViewState, CSRF, etc.   This was one of the only issues that was brought to my attention but I will look over the list and post anything else I found.

As for File Content detection not sure this is something that PF should add or not.  But I use [Apache Tika](https://tika.apache.org/) for mine and its AWESOME.  So if you upload a JPG and its actually an EXE you renamed to JPG it catches it.  Tika does most of its work using "magic bytes" detection and we have tried it with everything from PDF's, to GIF's etc and and it catches every one.   I do it using my custom EE Interceptor called @FileContentDetector so I use it like this...

```java
   @FileContentDetector
   public void importFile(final FileUploadEvent event) throws Exception {
```
I even have an option to scan a ZIP file and check every file in the ZIP to make sure its file type is correct.

```java
   @FileContentDetector(inspectZip=true)
   public void importFile(final FileUploadEvent event) throws Exception {
```

I am more than happy to share my code with you if you want?

**Comment by tandraschko** [comment]
what dependencies are required? tika-parsers?
i tried adding it to my application but this are ~60mb of required libs....

**Comment by cnsgithub** [comment]
> As for File Content detection not sure this is something that PF should add or not.

I am also not sure. However, I could imagine an opt-in attribute like `allowMimeTypes` (comma-separated or something like that). Then if any mime types have been specified we could leverage the `java.nio.file.Files.probeContentType(Path)` method to match the types and let it up to the user (somehow document it in the user guide) which `FileTypeDetector` service providers are picked up from the classpath. For example if Apache Tika is in place, [TikaFileTypeDetector](https://tika.apache.org/1.19.1/api/org/apache/tika/filetypedetector/TikaFileTypeDetector.html) would be used automatically.

**Comment by melloware** [comment]
The dependency I add is only...
```xml
<dependency>
  <groupId>org.apache.tika</groupId>
  <artifactId>tika-core</artifactId>
  <version>1.19.1</version>
</dependency>
```
I don't think my WAR's have grown that much adding this dependency.  Our WARS are about 25-35 MB total.

**Comment by cnsgithub** [comment]
> Tika does most of its work using "magic bytes" detection

Just wonder if it supports `0xCAFEBABE` as well? :wink:

**Comment by tandraschko** [comment]
@cnsgithub using Files#probeContentType/FileTypeDetector sounds good!

**Comment by melloware** [comment]
> Just wonder if it supports 0xCAFEBABE as well? 😉

HA!   I do like your idea though of if PF detects Tika on the classpath use its detector.  Kind of like how other PF dependencies are optional.

**Comment by tandraschko** [comment]
AFAICS Tika would be automatically used by Files#probeContentType?!

**Comment by cnsgithub** [comment]
> AFAICS Tika would be automatically used by Files#probeContentType?!

Yep, that would be the plan. See https://github.com/apache/tika/blob/master/tika-java7/src/main/resources/META-INF/services/java.nio.file.spi.FileTypeDetector :+1:

**Comment by tandraschko** [comment]
+1

if you provide a PR, please don't forget that we are still on java7 and we need a if (!java8) -> log.warn

**Comment by cnsgithub** [comment]
@tandraschko Why do we need a warning? `FileTypeDetector` is available since 1.7?

**Comment by cnsgithub** [comment]
So, let's derive steps that have to be done regarding this issue in detail and with consensus... 

What about my thoughts posted in https://github.com/primefaces/primefaces/issues/2791#issuecomment-438152568 about renaming, server side validation, etc.?

**Comment by tandraschko** [comment]
oh ok :D i thought its available since 1.8

**Comment by tandraschko** [comment]
allowTypes is currently only evaluated on the client.
Could we reuse the same regex on the server? (lets talk about the naming later)

Also, allowTypes is used by the advanced js-based upload.
There is also "accept", which is used by the simple, non js-based, upload

This new features would then validate the mimetypes?

**Comment by cnsgithub** [comment]
> Could we reuse the same regex on the server? (lets talk about the naming later)

Javascript and java regex should be the same and therefore be reusable at backend side, except for look-behinds, see https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines#Language_features.

**Comment by cnsgithub** [comment]
> There is also "accept", which is used by the simple, non js-based, upload

Okay, didn't know the `accept` attribute. It seems to be passed through to the HTML file input: `<input accept="file_extension|audio/*|video/*|image/*|media_type">`, see https://www.w3schools.com/tags/att_input_accept.asp for allowed values.

Maybe we could reuse the `accept` attribute as well at server side to perform the mime type checking.

**Comment by cnsgithub** [comment]
As far as I can see, the `accept `attribute is always passed through and used together with native file dialog. Can you confirm that?

**Comment by tandraschko** [comment]
Possible, cant remember

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/4242

**Comment by cnsgithub** [comment]
> > Could we reuse the same regex on the server? (lets talk about the naming later)
> 
> Javascript and java regex should be the same and therefore be reusable at backend side, except for look-behinds, see https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines#Language_features.

@tandraschko @melloware Against my expectations I got stuck here. Basically the regex syntax itself should be compatible (ignoring the look-behind support) between java and javascript. However, as javascript has built-in language support for regex literals, which java of course does not have (just strings), things get a bit complicated. What `allowTypes` expects is a valid javascript regex literal. Since this is not documented in PF user guide and it's presumably more difficult to convert javascript to java regex notation, I would suggest to switch to java regex notation for the `allowTypes` attribute which feels more intuitive since we're using the component in Java/JSF in the first place. We could bind the attribute's value to either `String `or even `Pattern`. What do you guys think? This would of course be a breaking change. (Btw, `p:keyFilter` also silently uses javascript regex notation.)

Edit: While in Java modes can be expressed inline with `(?i)` for example for case insensitivity, this is not supported in javascript. Valid java version: `(?i)\.(gif|png|jpe?g)$` vs. valid javascript version: `/\.(gif|png|jpe?g)$/i` As a consequence I would suggest to use hardcoded `Pattern.CASE_INSENSITIVE` in java and trailing `/i` in javascript and generally disallow modes by convention.

Edit 2: Alternatively, we could use a `ScriptEngine `inside java (rhino in java 7, nashorn afterwards) and evaluate the javascript regex to achieve the very same behavior. :wink: This might of course hurt performance... (unfortunately, `ScriptEngineFactory.getParameter("THREADING")` returns `null `what means that the engine cannot be reused by multiple threads) 
Example: `new ScriptEngineManager().getEngineByName("javascript").eval("/\\.(gif|png|jpe?g)$/i.test(\"test.PNG\")")`

**Comment by melloware** [comment]
Ughhh.  I was afraid of that.  I knew the Regex's were different I didn't know they were THAT different.

I personally for the least breaking change actually like the using the JS Engine to evaluate the regex.  While it might be a slight performance hit we are talking about File Uploads so its not like its happening hundreds per second and its worth the benefit of the server side security check.  Plus it makes the current allowTypes just work without a breaking change.

**Comment by cnsgithub** [comment]
@melloware I totally agree. @tandraschko suggested to make the content type checking an opt-in feature. We could introduce an `enableContentTypeChecking `attribute or something like that?

**Comment by melloware** [comment]
Also agree maybe "checkContentType=true" for the property?  Default it will be "false".

**Comment by cnsgithub** [comment]
Yep, I also agree with the default `false`. Let's wait for @tandraschko's opinion.

**Comment by tandraschko** [comment]
"checkContentType" with "false" as default -> +1

About the regex -> thats what i remember ;)
Could we reuse a java regex 1:1 in javascript?

**Comment by cnsgithub** [comment]
> Could we reuse a java regex 1:1 in javascript?

Nope, see first edit in https://github.com/primefaces/primefaces/issues/2791#issuecomment-438990409.

Just one more thing to keep in mind: as of java 11 nashorn built-in support has been deprecated: http://openjdk.java.net/jeps/335

**Comment by tandraschko** [comment]
Yep, therefore -1 for the ScriptEngine stuff.

We could also not convert it from js to java or vice versa?
Then we have 2 possible ways:
1) don't use on the server, it's also not very secure...
   -> the user must add tika and enable checkContentType to get a real validation
2) add a second attribute for java-style regex

**Comment by melloware** [comment]
Ughh I don't like it if they are removing it from the JDK I don't want to rely on it.  Can we compromise with maybe not a 100% solution but for convert the JS Regex to Java Regex using this guy's solution.

https://stackoverflow.com/questions/8754444/convert-javascript-regular-expression-to-java-syntax

It's not perfect but its also not the end of the world either as we are just trying to check file names?

**Comment by cnsgithub** [comment]
> Yep, therefore -1 for the ScriptEngine stuff.

Oops, just pushed another commit to the branch having the `ScriptEngine` stuff included. Personally, I'd like it if there wasn't the warning about the deprecation. But as the JEP says, the deprecation might also be reverted in a future release... Could you please rethink about it? In my opinion it would be the most reliable solution. And we could denote in the user guide that when `checkContentType `is turned on, nashorn must be in place and tika is recommended to be in place.

> add a second attribute for java-style regex

-1 as this would be even more confusing and is subject to misconfigurations.

**Comment by cnsgithub** [comment]
> Can we compromise with maybe not a 100% solution but for convert the JS Regex to Java Regex using this guy's solution.

Also stumbled upon this stackoverflow, however I don't think it's sufficient in the end. I don't really like to implement that stuff, sorry. But feel free to adopt and modify my PR.

**Comment by melloware** [comment]
No problem.  Just trying to find a good compromise.

**Comment by tandraschko** [comment]
1) isCheckContentType -> i would name it validateContentType
2) validateContentType is currently also used for validating the file name, i would split up
3) if we do 2), we could also disable the ScriptEngine stuff independently from 1), if it doesn't work for 100% in some environments

**Comment by cnsgithub** [comment]
> isCheckContentType -> i would name it validateContentType

Rename the attribute? You just agreed with it in https://github.com/primefaces/primefaces/issues/2791#issuecomment-439021390.

> if we do 2), we could also disable the ScriptEngine stuff independently from 1), if it doesn't work for 100% in some environments

Done.

**Comment by tandraschko** [comment]
i know sorry - but it is validation actually, so it's better to name it like this
even the utils method is called "isValidType"

**Comment by cnsgithub** [comment]
> i know sorry - but it is validation actually, so it's better to name it like this

Done.

**Comment by tandraschko** [comment]
@cnsgithub do we have to add additional code for tika now because it's not used automatically?

**Comment by tandraschko** [comment]
created a seperate issue for the validateContentType -> https://github.com/primefaces/primefaces/issues/4244

**Comment by cnsgithub** [comment]
> @cnsgithub do we have to add additional code for tika now because it's not used automatically?

@tandraschko Please see my continued PR #4249 that includes unit test cases that make use of Apache Tika. At least in the test environment it's picked up and used automatically (defined as test scoped dependency in pom.xml).

One tricky thing to note is a short circuit of Apache Tika's implementation, see https://github.com/apache/tika/blob/master/tika-java7/src/main/java/org/apache/tika/filetypedetector/TikaFileTypeDetector.java. To improve performance they first use the file extension only to detect the content type. This is of course not what we want. To force deep inspection of the file's content, I therefore changed the extension to `null` in PR #4249, to make Tika believe it's `application/octet-stream` and force it to do deeper analysis.
