### ISSUE TITLE
Schedule: description not shown as title

### ISSUE THREAD

**Issue by thomas-mc-work** [primefaces/primefaces#2795]
## Environment
- PrimeFaces version: 6.1
- Application server + version: payara 4.1.1.171
- Affected browsers: all (as it's not present in the html code)

## 2) Expected behavior

Like described in the documentation:

> description: Tooltip text to display on mouseover of an event.

## 3) Actual behavior

I create a `DefaultScheduleEvent` and set it's description to "something". I can see the event in the `Schedule` as expected

- the Java attribute `title` is correctly translated to the events body
- the Java attribute `description` is being ignored.

## 5) Sample XHTML

    <p:schedule value="#{myBean.eventModel}" view="agendaWeek"
                    weekNumberCalculation="ISO" locale="de_DE" timeZone="Europe/Berlin"
                    draggable="false" resizable="false" firstHour="7" showWeekNumbers="true"
                    rightHeaderTemplate="month, agendaWeek"
                    style="width: 100%" aspectRatio="1.57"/>

## 6) Sample bean

    final DefaultScheduleEvent event = new DefaultScheduleEvent("my body", new Date(), new Date());
    event.setDescription("anything");
    
    ScheduleModel eventModel = new DefaultScheduleModel();
    eventModel.addEvent(event);

**Comment by wal-jan** [comment]
[FullCalendar](https://fullcalendar.io/docs/event_data/Event_Object/)s doc states

> In addition [...] you may also include your own non-standard fields in each Event Object. FullCalendar will not modify or delete these fields. For example, developers often include a `description` field [...]

Using `p:schedule`s `extender` attribute one can (easily) add `event.description` as tooltip

            <p:schedule value="#{myBean.eventModel}" ... extender="cfgSchedule"/>
            <script type="text/javascript">
              function cfgSchedule() {
                this.cfg.eventRender = function(event, element) {
                    element.attr('title', event.description);
                };
              }
            </script>

Maybe this can be added to `p:schedule`s documentation.

**Comment by melloware** [comment]
PR submitted.  Thanks @wal-jan I now set the tooltip if you are not using Primefaces tooltips.  Please review.

**Comment by ravihariharan** [comment]
@tandraschko / @melloware 

i had the same issue and then found we need to set tooltip =true for p:schedule. 

USER GUIDE 6.2--> page 434
-->tooltip false Boolean Displays description of events on a tooltip

USER GUIDE 6.1 --> page 429
tooltip false Boolean Displays description of events on a tooltip.

USER GUIDE 6.0 --> page 417
tooltip false Boolean Displays description of events on a tooltip.
