### ISSUE TITLE
DataTable with lazy="true" and multiViewState="true" casues EL parse error during page reload

### ISSUE THREAD

**Issue by frevado** [primefaces/primefaces#2796]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No. Tried 6.1, 6.1.4, 6.1.5, 6.1.6.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: GlassFish 4.1.2
- Affected browsers: Probably all, seems unrelated to browser (tried Chromium and Firefox)

## 2) Expected behavior
When using a DataTable with lazy loading and multi view state, reloading the page should not generate any errors.

## 3) Actual behavior
The application server throws an exception when trying to parse an invalid EL expression:

> javax.el.ELException: Error Parsing: #{obj.#{'name'}}
> 	at com.sun.el.lang.ExpressionBuilder.createNodeInternal(ExpressionBuilder.java:213)
> 	at com.sun.el.lang.ExpressionBuilder.build(ExpressionBuilder.java:237)
> 	at com.sun.el.lang.ExpressionBuilder.createValueExpression(ExpressionBuilder.java:295)
> 	at com.sun.el.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:112)
> 	at org.jboss.weld.util.el.ForwardingExpressionFactory.createValueExpression(ForwardingExpressionFactory.java:53)
> 	at org.jboss.weld.el.WeldExpressionFactory.createValueExpression(WeldExpressionFactory.java:48)
> 	at org.primefaces.component.datatable.DataTableRenderer.encodeRows(DataTableRenderer.java:1124)
> 	at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:1077)
> 	at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:1026)
> 	at org.primefaces.component.datatable.DataTableRenderer.encodeRegularTable(DataTableRenderer.java:391)
> 	at org.primefaces.component.datatable.DataTableRenderer.encodeMarkup(DataTableRenderer.java:353)
> 	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:94)
> 	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
> 	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
> 	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
> 	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
> 	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
> 	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
> 	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
> 	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)
> 	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
> 	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
> 	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
> 	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
> 	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
> 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
> 	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
> 	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
> 	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
> 	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
> 	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
> 	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
> 	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
> 	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
> 	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
> 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
> 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
> 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
> 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
> 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
> 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
> 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
> 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: com.sun.el.parser.ParseException: Encountered "{" at line 1, column 8.

## 4) Steps to reproduce
1. Create a DataTable with `lazy="true"` and `multiViewState="true"`.
2. Add a column with the `field="xyz"` set and `sortable="true"`. In version 6.1.6 you also have to add something like `sortBy="#{dummy}"` to enable sorting controls for the column, which might be a separate issue.
3. Load the page in a browser.
4. Re-order the table using the sort controls of the column.
5. Reload the page in the browser. 

## 5) Sample XHTML
```
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui">
 <h:head>
  <title>Test</title>
 </h:head>
 <h:body>
  <h:form>
   <p:dataTable lazy="true" value="#{testModel}" var="obj" rows="10" paginator="true" multiViewState="true">
    <p:column headerText="ID" field="id" sortable="true" sortBy="#{dummy}">#{obj.id}</p:column>
    <p:column headerText="Name" field="name" sortable="true" sortBy="#{dummy}">#{obj.name}</p:column>
   </p:dataTable>
  </h:form>
 </h:body>
</html>
```

## 6) Sample bean
```
package test;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

@Named
@SessionScoped
public class TestModel extends LazyDataModel<TestObject> {
	private static final long serialVersionUID = 3020941375361089370L;

	private List<TestObject> objects;

	public TestModel() {
		objects = new ArrayList<TestObject>();
		objects.add(new TestObject(1, "abc"));
		objects.add(new TestObject(91, "fssa"));
		objects.add(new TestObject(88, "thrr"));
		objects.add(new TestObject(54, "vzxfwe"));
		objects.add(new TestObject(12, "gwer"));
		objects.add(new TestObject(7, "faasd"));
		objects.add(new TestObject(6, "jyrtte"));
		objects.add(new TestObject(87, "twevv"));
		objects.add(new TestObject(29, "jtyu"));
		objects.add(new TestObject(70, "kuyyj"));
		objects.add(new TestObject(65, "asde3r"));
		objects.add(new TestObject(92, "eqwecas"));
		objects.add(new TestObject(23, "nfgg"));
		objects.add(new TestObject(2, "zosjd"));
		objects.add(new TestObject(36, "sdewe"));
		objects.add(new TestObject(44, "kjwlfhf"));
	}

	public List<TestObject> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String,Object> filters) {
		List<TestObject> result = new ArrayList<TestObject>();

		// Filter.
		for (TestObject object : objects) {
			boolean isMatch = true;
			if (filters != null) {
				for (Map.Entry<String,Object> entry : filters.entrySet()) {
					System.out.println("XXX: key=" + entry.getKey() + ", value=" + entry.getValue());
					switch (entry.getKey()) {
					case "id":
						isMatch = String.valueOf(object.getId()).equalsIgnoreCase(entry.getValue().toString());
						break;
					case "name":
						isMatch = object.getName().equalsIgnoreCase(entry.getValue().toString());
						break;
					}
					if (!isMatch) {
						break;
					}
				}
			}
			if (isMatch) {
				result.add(object);
			}
		}
		setRowCount(result.size());
	
		// Sort.
		Comparator<TestObject> comparator;
		System.out.println("XXX: order by " + sortField + " " + sortOrder);
		if (sortField != null && sortOrder != null) {
			switch (sortOrder) {
			case ASCENDING:
				switch (sortField) {
				case "id":
					comparator = Comparator.comparing(TestObject::getId);
					break;
				case "name":
				default:
					comparator = Comparator.comparing(TestObject::getName);
					break;
				}
				break;
			case DESCENDING:
				switch (sortField) {
				case "id":
					comparator = Comparator.comparing(TestObject::getId).reversed();
					break;
				case "name":
				default:
					comparator = Comparator.comparing(TestObject::getName).reversed();
					break;
				}
				break;
			case UNSORTED:
			default:
				comparator = null;
				break;
			}
			if (comparator != null) {
				result.sort(comparator);
			}
		}

		// Return page.
		return new ArrayList<TestObject>(result.subList(first, Math.min(first + pageSize, result.size())));
	}

	@Override
	public TestObject getRowData(String rowKey) {
		for (TestObject object : objects) {
			if (String.valueOf(object.getId()).equals(rowKey)) {
				return object;
			}
		}
		return null;
	}

	@Override
	public Object getRowKey(TestObject item) {
		return String.valueOf(item.getId());
	}
}
```

**Comment by Rapster** [comment]
Duplicate #2631
