### ISSUE TITLE
Add delegate attribute to Tooltip

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2798]
Test code;
```
<h:form id="CONTENT">
    <p:poll id="poll" widgetVar="pollVar" autoStart="true" interval="5"
        global="false" update="CONTENT:aButton" partialSubmit="true">
    </p:poll>
    <p:button id="aButton">
    </p:button>
    <p:tooltip for="aButton" delegate="true">
        <h:outputText value="Come on Paris Saint Germain" />
    </p:tooltip>
</h:form>
```

**Comment by melloware** [comment]
I think its spelled wrong shouldn't "delegete" be "delegate"?

**Comment by tandraschko** [comment]
Yep! @mertsincan ?

**Comment by mertsincan** [comment]
Thanks @melloware :)

**Comment by kukel** [comment]
what does it do? No showcase or docs available...

**Comment by mertsincan** [comment]
Hi @kukel,

Please try the following code;
```
<h:form id="CONTENT">
    <p:poll id="poll" widgetVar="pollVar" autoStart="true" interval="5"
        global="false" update="CONTENT:aButton" partialSubmit="true">
    </p:poll>
    <p:button id="aButton">
    </p:button>
    <p:tooltip for="aButton">
        <h:outputText value="Come on Paris Saint Germain" />
    </p:tooltip>
</h:form>
```
When you just update button component with p:poll, tooltip's behaviour is losed due to its showEvent being dependent on button. First solution, you can update tooltip and button components with poll. Second solution, you can use delegate attribute on tooltip. With delegate attribute, tooltip's showEvent is connected to $(document). When you update button, tooltip is not affected.
