### ISSUE TITLE
Ability to turn off child processing in parent components

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#280]
In many cases, you don't want to process the children of a component. e.g. when you click on another Tab. You should be able to control this via an attribute on the <p:tab> tag or via p:ajax.

**Comment by tandraschko** [comment]
It's implement by p:ajax but e.g. tabView must still implement the check if skipChildren is used for the current request.

**Comment by tandraschko** [comment]
Will close it for now - i also implemented it on UITabPanel and therefor in TabView and Accordion.
