### ISSUE TITLE
TextEditor: Quill editor in accordion will be broken after performing update to its form

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#2802]
## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version? PF latest trunk
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 8.5
- Affected browsers: All

## 2) Expected behavior

Quill editor should work in accordion under any circumstances.

## 3) Actual behavior

Javascript was thrown, and UI was frozen.

## 4) Steps to reproduce

Using my sample,

1. Click `Click me first` button to update the form

2. expand tab 2

![image](https://user-images.githubusercontent.com/10467831/31453492-fb9c3118-ae77-11e7-8267-303276366f02.png)

![image](https://user-images.githubusercontent.com/10467831/31453506-03780ef2-ae78-11e7-822f-6d5de70679e3.png)

```js
texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7 Uncaught TypeError: Cannot read property 'innerHTML' of null
    at e.value (texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7)
    at new e (texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7)
    at texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7
    at Array.map (<anonymous>)
    at e.value (texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7)
    at e.value (texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7)
    at e.value (texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7)
    at texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7
    at Array.forEach (<anonymous>)
    at e.value (texteditor.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7)
```

## 5) Sample XHTML

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        
        <h1>#{testView.testString}</h1>
        
        <h:form id="testForm">
        	<p:commandButton update="@form" value="Click me first"></p:commandButton>
        	<p:accordionPanel>
        		<p:tab title="Tab1">
        			<p:textEditor></p:textEditor>
        		</p:tab>
        		<p:tab title="Tab2">
        			<p:textEditor></p:textEditor>
        		</p:tab>
        	</p:accordionPanel>
        </h:form>
        
        
    </h:body>
</html>
```

## 6) Sample bean

Not needed

## 7) Thoughts

I can confirm that this issue is a regression since it was working using the codebase up to commit: 1212413f4a554bcac2ac243fd20113e60a32e537

![image](https://user-images.githubusercontent.com/10467831/31453787-e2575876-ae78-11e7-8a94-58747a105e06.png)

**Comment by jxmai** [comment]
After some debugging, this issue is causing by upgrading quill editor since 1.3.0 even though currently we are using 1.3.1.

**Comment by jxmai** [comment]
I can confirm that this regression is actually triggered by https://github.com/quilljs/quill/pull/1576, after putting back `option.hasAttribute('selected')`, the editor will run normally in Primefaces.


![image](https://user-images.githubusercontent.com/10467831/31469000-b8784ff6-aea5-11e7-8066-c9549b01a888.png)


The motivation of the changes can be found in https://github.com/zenoamaro/react-quill/issues/226, but we have the opposite problem...

**Comment by jxmai** [comment]
Either revert the update back to 1.2.6 or patch it somehow ( I don't know yet since the changes were brought by other projects and this issue is not easily reproducible using quill js only, so I lean toward rolling back at least before PF 6.2), and we cannot left the regression to PF 6.2 as RC is approaching.

**Comment by tandraschko** [comment]
Not sure if we should rollback. The updates fixes quite a lot bugs.
The goal should be to get it running till 6.2.

**Comment by jxmai** [comment]
I need to raise a ticket in quill, and I will link the issue back to here.

![image](https://user-images.githubusercontent.com/10467831/31504529-396d3850-af38-11e7-8300-b4da4f489588.png)

Basically, `option.selected` is not exactly the same as `option.hasAttribute('selected')`


![image](https://user-images.githubusercontent.com/10467831/31504581-577d203a-af38-11e7-9a31-5a2d2ee9f7ac.png)

**Comment by jxmai** [comment]
Quill ticket: https://github.com/quilljs/quill/issues/1762

**Comment by jxmai** [comment]
> Not sure if we should rollback. The updates fixes quite a lot bugs.
The goal should be to get it running till 6.2.

@tandraschko I have done what I can do. If there is no answer from them or for whatever reason the patch cannot arrive before Primefaces 6.2, we need to rollback since `p:texteditor` currently is pretty much unusable.

---

The other solution is to override their library to revert https://github.com/quilljs/quill/pull/1576 ourselves since it is only one line diff. 

---

Anyway, I will let you make the judgement call.

**Comment by jxmai** [comment]
@tandraschko Not a good news as we probably cannot get the patch to quill before 6.2 (Please look at https://github.com/quilljs/quill/pull/1813). Melloware and I voted for custom patching. I can raise a PR for that but is it OK for you ?

This is a pretty nasty regression so user will definitely find out when  6.2 is released

**Comment by tandraschko** [comment]
It's ok for me to upgrade to the newest verison  + fix this bug dirty in our codebase for now.
But i would be great to get the fix in quill for the future.

**Comment by jxmai** [comment]
OK then :+1: . I will prepare a PR later. Sure it will be great to get the patch to quill in the future.

**Comment by tandraschko** [comment]
I just looked at the initial issue at quill and it was closed.
Couldn't we somehow solve it in our integration JS?

**Comment by jxmai** [comment]
it was closed not because it was fixed.   Quill maintainer tends to close an issue that is incomplete from his POV.  He was asking for more proof before making the decision although he knew it was a changing behaviour.

His comment: https://github.com/quilljs/quill/issues/1762#issuecomment-345070342

> I think the disconnect is what you think is a behavior I think is an implementation detail. In Alex's report he provided the user facing issue and connected the dots to implementation, which led to a merged PR. 

The sample usually requires `jsfiddle`, `codepen` links, but that's not easy for us to do since this regression needs to be triggered after view update (https://github.com/quilljs/quill/pull/1813#issuecomment-345079559).

---


> Couldn't we somehow solve it in our integration JS?

That's a good point, but the function is not easy to override externally based on my knowledge.


The js we would like to override is in this file: https://github.com/quilljs/quill/blob/develop/ui/picker.js

and we could see the last commit is the problem for us currently: https://github.com/quilljs/quill/commit/dbfb0af1300e901a00da2642cb748ee977654e17

https://github.com/quilljs/quill/blob/c6b54fafb18736fb134d19ecd638303fbba5193e/ui/picker.js#L46

Not sure if I understand correctly, but it seems like `picker.js` and other js files need to be complied through webpack in order to generate the js we are using.

**Comment by melloware** [comment]
This is an issue with Quill 1.3.7 also.  Submitting fix

**Comment by melloware** [comment]
Because we have been burned by this two times upgrading QuillJS I wrote an Integration Test so it will catch this if someone upgrades QuillJS in the future and doesn't apply this patch!

See: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/bc006410febbea49114f22309977e1a92b7c2d80
