### ISSUE TITLE
SelectOneMenu will not work with keyboard selection in 6.2-SNAPSHOT

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#2807]
It does not work in the latest 6.2-SNAPSHOT,
but already working in 6.1.6 - version.

**Preface:**
In my application the user need to select his location by choosing it from the 
SelectOneMenu after he entered his username/password.
In version 6.1.6 he can choose the location by pressing the up-/down- arrow key's 
(Keyboard) or use the mouse by clicking the dropdown-icon (Mouse or Touchscreen).

In the current 6.2-SNAPSHOT only clicking the dropdown-icon is supported,
the keyboard can't focus or choose an entry by pressing TAB or up-/down arrow key's...

The Simple Example from my logon-page :

```
<p:selectOneMenu id="Client" rendered="#{loginControl.currentStep==EnumStep.STEP_CLIENT}" value="#{loginControl.loginModel.client}" autoWidth="false" style="width: 100% !important;" styleClass="LogonInput" converter="omnifaces.SelectItemsIndexConverter" required="true" requiredMessage="#{tr.tr('Index.LocationRequired')}">
	<f:selectItem itemLabel="#{tr.tr('General.SelectOne')}" itemValue="#{null}" noSelectionOption="true"/>
	<f:selectItems value="#{loginControl.allClients}" var="client" itemLabel="#{client.label}" itemValue="#{client}"/>
</p:selectOneMenu>

```

I will try to render the "HTML-Output" in 6.2 and 6.1.6 to see if there are any differences 
and write the result's to here ...

**Comment by tandraschko** [comment]
As all users, you need to provide a example which can be used by us. We don't have a loginControl.
At best, try to run the the showcase from github with the last PF 6.2-SNAPSHOT. It works fine for me and there are already good sample xhtml + beans available in the showcase, to base your example on it.

**Comment by ssibitz** [comment]
It does not depend on my code, 
so as i tried by now the same issue on this "Simple" selectOneMenu from the showcase - but without using the value here:

I am not able to set the focus to the ComboBox / selectOneMenu 
or navigate via Tabulator and Cursor-Key's:

```
        <p:selectOneMenu id="console" style="width:125px">
            <f:selectItem itemLabel="Select One" itemValue="" />
            <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
            <f:selectItem itemLabel="PS4" itemValue="PS4" />
            <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
        </p:selectOneMenu>
```

The problem is that you can't set the focus to the element by using the keyboard 
anymore so also the up/down-key's will not work...

I will try to "render" the HTML-Part in 6.2 and 6.1.6 to see if there are any differences
and then post it to here...

**Comment by ssibitz** [comment]
In 6.1.6 the selectOneMenu will be rendered as:

```
<div id="console" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" style="width:125px">
    <div class="ui-helper-hidden-accessible">
        <input id="console_focus" name="console_focus" type="text" autocomplete="off" role="combobox" aria-haspopup="true" aria-expanded="false" aria-autocomplete="list" aria-owns="console_items" aria-activedescendant="console_0" aria-describedby="console_0" aria-disabled="false">
    </div>
    <div class="ui-helper-hidden-accessible">
        <select id="console_input" name="console_input" tabindex="-1" aria-hidden="true">
            <option value="">Select One</option>
            <option value="Xbox One">Xbox One</option>
            <option value="PS4">PS4</option>
            <option value="Wii U">Wii U</option>
        </select>
    </div>
    <label id="console_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">Select One</label>
    <div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div>
</div>
```

but in 6.2 it renderes this from the same source as commented before:
```
<div id="console" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" style="width:125px">
    <div class="ui-helper-hidden-accessible">
        <input id="console_focus" name="console_focus" type="text" autocomplete="off" hidden="hidden" role="combobox" aria-haspopup="true" aria-expanded="false" aria-autocomplete="list" aria-owns="console_items" aria-activedescendant="console_0" aria-describedby="console_0" aria-disabled="false">
    </div>
    <div class="ui-helper-hidden-accessible">
        <select id="console_input" name="console_input" tabindex="-1" aria-hidden="true">
            <option value="">Select One</option>
            <option value="Xbox One">Xbox One</option>
            <option value="PS4">PS4</option>
            <option value="Wii U">Wii U</option>
        </select>
    </div>
    <label id="console_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">Select One</label>
    <div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div>
</div>
```

The main difference at rendering which i can currently see is this :

`<input id="console_focus" hidden="hidden" ...  />
`

**Comment by ssibitz** [comment]
When i remove the 
`hidden="hidden"`
Tag by Using Google-Chrome-Tools direct in the Browser the selectOneMenu is now 
available again via TAB and Cursor Up/Down Key's ...

**Comment by tandraschko** [comment]
@mertsincan Could you please check that? Focusing the selectOneMenu in the showcase is broken :/

**Comment by melloware** [comment]
This is a side effect of this request:  https://github.com/primefaces/primefaces/issues/2720

**Comment by tandraschko** [comment]
Ok, reverted the change ;)

**Comment by ssibitz** [comment]
Ok, i take a look at the side-affected request...

But why setting the hidden-attribute -
Isn't it that the class-helper "ui-helper-hidden-accessible" is already used for that ?

**Comment by ssibitz** [comment]
OK - Reverted - alright ;-)

**Comment by ssibitz** [comment]
By the way - As the customer in the request #2720 says :

selectOneMenu

..will be rendered / handled correct in primefaces 6.1.6 in:
Google Chrome, Firefox & Internet Explorer / Edge

:-)

**Comment by ssibitz** [comment]
Now i see what the customer with #2720 means:

Not the "hidden" - tag 
but the tag for **screenreader's** should be hidden by setting this attribute:

`aria-hidden="true"`
