### ISSUE TITLE
PrimeFaces Mobile will be deprecated so why don't using Bootstrap 4 for Responsive Framework as "Feature" ?

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#2812]
I have seen in the Primefaces 6.2 Roadmap that
the PrimeFaces Mobile Renderkit will be deprecated.

So why don't include Bootstrap 4
instead of re-inventing the wheel by creating/using own stylesheet's and script's ?
I know that Bootstrap 4 is currently in Beta-State,
but it's stable enough to be used in a project as i have seen in 
my customer's Application.

I am currently using Bootstrap 4 in my project to build the site content
in combination with Primefaces 6.1.6 and already sucessfully overwrite 
some Primefaces-Styles to be conform with Bootstrap and so it's responsive
for our customers on Desktop, Tablet or Mobile Phone.

Another thing is that "including" Bootstrap 4 allowes the user to
use additional components which also can be adapted for using with Primefaces
(And currently not available in Primefaces):
Navbar, Badges, Card's, ...

**Comment by ssibitz** [comment]
By the way - is there an option 
in Primefaces to add my "Own" components to it ?

I have some ideas :-)

**Comment by tandraschko** [comment]
Questions -> Forum ;)
We don't need to bootstrap.
We have a grid since many years and the user can use what they wan't. We have have a simple class "ui-fluid" so make it fluid in EVERY grid.
For whole page layouts, we have our PrimeFaces Templates.
But PF as component library, with own components instead of bootstrap widgets, we are not bound to any layouting framework.

New components should go though PrimeFaces Extensions.

**Comment by tandraschko** [comment]
If you would like to use bootstrap, you should try bootsfaces or butterfaces.

**Comment by ssibitz** [comment]
No - Bootsfaces/Butterfaces is not an option for me cause Bootstrap "Alone" 
has too less components inside for real usage inside a customer project.

On the other side Bootsfaces/Butterfaces only used Bootstrap 3 ...

A combination of Bootstrap 4 and Primefaces would be great 
but i see i have to do it by my own ...

**Comment by melloware** [comment]
@ssibitz for custom components as was mentioned you can suggest or write new components for PrimeFaces Extensions Project:

https://www.primefaces.org/showcase-ext/views/home.jsf
