### ISSUE TITLE
cant build on localmachine

### ISSUE THREAD

**Issue by tecbea** [primefaces/primefaces#2814]
## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
Cant build the primefaces on localmachine

## 4) Steps to reproduce
```
git clone https://github.com/primefaces/primefaces.git
git checkout 6_1
cd primefaces
mvn clean compile
```

## 5) possible corrections

a) add the plugin repo on pom.xml
```
	<pluginRepositories>
	    	<pluginRepository>
        	<id>primeFaces_repository</id>
	        <url>http://repository.primefaces.org/</url>
	    </pluginRepository>
	</pluginRepositories>
```

b) maven-jsf-plugin:jar:1.3.3-SNAPSHOT does not exist in http://repository.primefaces.org/

c) using the version 1.3.2 that exist on http://repository.primefaces.org/ it gives an compilation error
`/DataTableRenderer.java:[451,74] org.primefaces.component.column.Column.PropertyKeys has protected access in org.primefaces.component.column.Column`

**Comment by jxmai** [comment]
This is not an issue. You need to build maven-jsf-plugin before building primefaces.

https://github.com/primefaces/primefaces/wiki/Building-From-Source

> Build and Install maven-jsf-plugin

If you already have maven-jsf-plugin in your local maven repository you can skip this step.

> git clone https://github.com/primefaces/maven-jsf-plugin.git

> cd to the maven-jsf-plugin directory

> cd maven-jsf-plugin

> mvn clean install

**Comment by tecbea** [comment]
Hi,
using the maven-jsf-plugin from github head did work
thanks for answer, and sorry i did not see that build from source

cheers
