### ISSUE TITLE
Wrong Date Format with "M/d/yy" pattern

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2822]
Reported By PRO User;
> I tried to make calendar input with format of "M/d/yy" but it gives me only one digit for month and one digit for day (I can't write manually 12/12/17, when I'm writing "1" it jumps to the next digit without giving an option to write 12).
What can I do?
(I know I can write MM/DD/YY but I need this format because I'm taking it from java method)
The code used is as follows:
<p:calendar id="startDate" required="true" mask="true"
pattern="M/d/yy"></p:calendar>

**Comment by melloware** [comment]
@mertsincan There are a few similar issues to this exact issue with Date formatting. Is it possible your fix might have fixed one or more of them?

https://github.com/primefaces/primefaces/issues/1754

https://github.com/primefaces/primefaces/issues/1038

https://github.com/primefaces/primefaces/issues/911

**Comment by mertsincan** [comment]
Hi @melloware,
I'll check them.

Thanks!

**Comment by tandraschko** [comment]
@mertsincan did you check them? Would be great if we could close them :D
