### ISSUE TITLE
<p:selectCheckboxMenu Selected Items not displayed

### ISSUE THREAD

**Issue by YahiaZZ** [primefaces/primefaces#2823]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- 6.0
- Application server + version: Tomcat7
- Affected browsers:All
## 2) Expected behavior
Selected Items displayed with "x" icon to deselect
...

## 3) Actual behavior
nothing displayed
..

## 4) Steps to reproduce
Normal
.. 

## 5) Sample XHTML

`<h:outputLabel for="multiple" value="Personnes affectés: " />
		               <p:selectCheckboxMenu id="multiple" value="#{missionView.selectedEmployee}" label="Choisir" multiple="true"
                              filter="true" filterMatchMode="startsWith" panelStyle="width:280px"  >
				            <f:selectItems value="#{missionView.list_employees}" />
				        </p:selectCheckboxMenu>`

## 6) Sample bean

..

**Comment by melloware** [comment]
works fine in the 6.1 Showcase so I don't think you will see your issue for 6.0 get fixed.  Have you tried 6.1 Community Edition?

https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml

**Comment by YahiaZZ** [comment]
Hi,
Even I try the 6.1 version, it's not working until adding updateLabel="true" to it but still not have the "x" icon to deselect an item
Thanks

**Comment by tandraschko** [comment]
Could you verify again @melloware ?

**Comment by melloware** [comment]
The "X" is only there if you use the attribute multiple="true".  If you are not doing multiple the "X" is not there because there is nothing to remove you are in single select mode.

**Comment by tandraschko** [comment]
but the example above has an multiple attr?

**Comment by melloware** [comment]
its  working fine for me in the 6.1.5 Showcase and 6.2.0-SNAPSHOT.  So its possible this was fixed past the 6.1 Community Edition?  I just know i can't get it to happen.

**Comment by tandraschko** [comment]
Ok, thanks.
So lets close it for now as can't replicate - also a complete example is missing.
