### ISSUE TITLE
Facets of datatable render a DIV, even when no components in the footer are rendered.

### ISSUE THREAD

**Issue by rdebusscher** [primefaces/primefaces#2825]
Following tags (where rendered attribute is, of course, EL based to make any sense :) )

```
<p:dataTable >
      <f:facet name="footer">
            <p:commandButton value="button 1" rendered="false"/>
            <p:commandButton value="button 2" rendered="false"/>
       </f:facet>
</p:dataTable>
```

Generates following HTML

```
<div id="j_idt17" class="ui-datatable ui-widget"><div class="ui-datatable-tablewrapper"><table role="grid"><thead id="j_idt17_head"><tr role="row"></tr></thead><tbody id="j_idt17_data" class="ui-datatable-data ui-widget-content"><tr class="ui-widget-content ui-datatable-empty-message"><td colspan="0">No records found.</td></tr></tbody></table></div><div class="ui-datatable-footer ui-widget-header ui-corner-bottom"></div></div>
```

Important here is that there is an empty div with some style classes.

```
<div class="ui-datatable-footer ui-widget-header ui-corner-bottom"></div>
```

Which results in some gray 'bar' due to the padding and background color.

**Expected**

When Datatable Renderer does not find any child of facet to be rendered, it should not render the div ui-datatable-footer.

**Comment by rdebusscher** [comment]
@tandraschko @cagataycivici 

Should this also be used in other components that uses facets (TreeTable, ... actually a lot of components uses this javax.faces.component.UIComponent#getFacet)

Let me know

**Comment by tandraschko** [comment]
We should in any case move this method to ComponentUtils or our BaseRenderer, to be reusable in the future.
Also some minor improvements:
1) call the method shouldRenderFacet
2) add a small javadoc that it checks the facet with rendered=true and the first level of the child components
3) we should use a index-loop to avoid the iterator instance

**Comment by tandraschko** [comment]
otherwise the change looks fine ofc :) and +1

**Comment by rdebusscher** [comment]
Moved to ComponentUtils.shouldRenderFacet

**Comment by melloware** [comment]
+1!  I agree we should look for other places using facets and do something similar using this new ComponentUtil optimization.

**Comment by tandraschko** [comment]
+1

Just my opinion:
As you already use "return ..." in the first if statement, i think its better to read if you do this:


`        
        for (int i = 0; i < facet.getChildren().size(); i++) {
            // Stop when a child who is rendered is found.
            if (facet.getChildren().get(i).isRendered()) {
               return true;
            }
        }

        return false;
    }`

**Comment by rdebusscher** [comment]
I don't like returning from within a loop, while, ...  It looks too much as procedural language.

A few years ago, I even only did a return at the end of the method and **never** somewhere in the middle. But due to pressure from my colleagues, I adapted already a bit :)

I'll adjust the return statement.

**Comment by tandraschko** [comment]
great!
Shouldn't it be 
if (!ComponentUtils.shouldRenderFacet(facet)) {
instead of
if (ComponentUtils.shouldRenderFacet(facet)) {
?

**Comment by rdebusscher** [comment]
Yes indeed.

I inversed meaning of the initial method and didn't check enough!

thx!

**Comment by Mobe91** [comment]
Are you sure that it is OK to never render the root component inside the facet if all children are not rendered, irrespective of the type of the root component? 
As I mentioned in #2685, the component used for auto-wrapping multiple roots in a facet is always UIPanel so it would be valid to restrict the checking of root component children to cases where the root component type equals UIPanel (as in my suggested method `isFacetRendered` in #2685) which would also be a minor performance enhancement.

**Comment by rdebusscher** [comment]
The wrapping is not always performed. When the footer contains only a panelGroup for example, no wrapping is done.

Within the spec (JSF 2.0, section 9.4.6) there is only a mentioning that there should be 1 component, a UIComponent descendent. So UIPanel is not mentioned and thus dangerous to limit the check to this type.

Since the method returns when it finds a rendered component, performance overhead should not be that large.

**Comment by tandraschko** [comment]
I think there is no reason from performance perspective, that we should change something here. The iterator has been removed, so i'm fine with it ;)

**Comment by erickdeoliveiraleal** [comment]
I built primefaces yesterday and after this commit series all my datatable's header has disappeared.

**Comment by tandraschko** [comment]
try to build today ;)
