### ISSUE TITLE
Bug icons Menu-MenuBar

### ISSUE THREAD

**Issue by sv3ntek** [primefaces/primefaces#2826]
Hello i found 1 error in primefaces SHOWCASE "Menu - Menubar"

The icons dont appear correctly. I'm using chrome browser.

![image](https://user-images.githubusercontent.com/32882769/31686022-a4f7a6ee-b34a-11e7-8e62-24172adaedeb.png)

**Comment by melloware** [comment]
Can you hit CTRL+F5 in your browser to reload CSS?  It looks fine in my Chrome?

**Comment by tandraschko** [comment]
Works also fine for me.
