### ISSUE TITLE
Dialog Framework: auto width ignored

### ISSUE THREAD

**Issue by culjar** [primefaces/primefaces#2831]
It's not possible to auto adjust the width to fit content of a Dialog Framework.

When I put the value of parameter "contentWidth" as "auto" it doesn't change and it is always 640, because this is the default value of property 'contentWidth'. In fact, inspecting the page at runtime it puts the iframe width value as "auto" literally, instead of translating it to the corresponding calculated value.

## 1) Environment
- PrimeFaces version: 6.1.7
- It does not work on the newest sources in GitHub
- Application server + version: Tomcat 8.0.27
- Affected browsers: All

## 2) Expected behavior
 Auto adjust the width to fit content of a Dialog Framework by setting "auto" value to "contentWidth" parameter.

## 3) Actual behavior
The "auto" value to "contentWidth" parameter is ignored.

## 4) Steps to reproduce
options.put("contentWidth", "auto");  

## 5) Sample XHTML
`<h:form>
    <p:commandButton value="Options" icon="ui-icon-extlink" actionListener="#{dfView.viewCarsCustomized}" />
</h:form>`

## 6) Sample bean
```
package org.primefaces.showcase.view.df;
 
import java.util.HashMap;
import java.util.Map;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;
import org.primefaces.showcase.domain.Car;
 
@ManagedBean(name = "dfView")
public class DFView {
     
     public void viewCarsCustomized() {
        Map<String,Object> options = new HashMap<String, Object>();
        options.put("modal", true);
        options.put("contentWidth", "auto");        
         
        RequestContext.getCurrentInstance().openDialog("viewCars", options, null);
    }
     
    public void chooseCar() {
        RequestContext.getCurrentInstance().openDialog("selectCar");
    }
     
    public void onCarChosen(SelectEvent event) {
        Car car = (Car) event.getObject();
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Car Selected", "Id:" + car.getId());
         
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
     
    public void showMessage() {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "What we do in life", "Echoes in eternity.");
         
        RequestContext.getCurrentInstance().showMessageInDialog(message);
    }
}
```

**Comment by culjar** [comment]
I have created a PR #2834 to fix this issue.

**Comment by melloware** [comment]
The crux of this issue is because its an IFrame when using the Dialog Framework there is no way to set `auto` width.

**Comment by tandraschko** [comment]
@melloware so lets close it and add a hint to the docs?

**Comment by melloware** [comment]
That is a great idea. I will update the docs and close this ticket once i have updated.
