### ISSUE TITLE
DataTable: improve filter look in narrow columns

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#2833]
## 1) Environment
- PrimeFaces version: SHOWCASE, all versions are affected
- Affected browsers: all

## 2) Expected behavior
Filter input doesn't overflow and it's always centered, even on narrow columns.

## 3) Actual behavior
![filter overflow](https://user-images.githubusercontent.com/18428155/31725631-1a14475e-b425-11e7-93ad-950f8974bcea.JPG)

## 4) Steps to reproduce
Go to https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml and narrow the page

## 5) Sample XHTML
Showcase

## 6) Sample bean
Not needed

## 7) Possible fix
I've tried to add `max-width: calc(100% - 10px)` to the `ui-datatable .ui-column-filter` CSS rule and it seems to work:
![filter with max width](https://user-images.githubusercontent.com/18428155/31726093-4e722416-b426-11e7-9c16-0bd724bfa0e7.JPG)

**Comment by melloware** [comment]
try this...

`<p:column filterStyle="width:20px"`

**Comment by NicolaIsotta** [comment]
Yep, I know I can force an inline style, but I'm already using the solution I've posted in my projects cause it's "automatic" and more responsive.

**Comment by melloware** [comment]
Ahh i see you are suggesting to fix it in all filters in PF by default with the max-width: calc(100% - 10px)  @mertsincan any thoughts?

**Comment by jxmai** [comment]
+1 up vote for improving the filter's default css rule. @melloware  Are you planning a PR for this ?

**Comment by melloware** [comment]
i was hoping @mertsincan would chime in but I will create a PR and let them decide whether to merge it or not.  To me this is a huge improvment.

**Comment by melloware** [comment]
PR submitted if you want to review.  I found the same thing in TreeTable.css so I added it there too.

**Comment by jxmai** [comment]
PR will get faster feedback IMO. This is also a big improvement to me since I have to overwrite the filter css rule every time in an application, so it can also benefit many others. :+1:

**Comment by tandraschko** [comment]
Thanks ;)
