### ISSUE TITLE
DataTable: Facets are no longer displayed in showcase

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2836]
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
Header should be visible in this example http://localhost:8080/showcase/ui/data/datatable/facets.xhtml

## 3) Actual behavior
Header is not displayed

## 4) Steps to reproduce
Navigate to the example

## 5) Sample XHTML
See example

## 6) Analysis
Regression caused by commits related to #2825. In this example, there is only one instruction, no component. 

```java
    public static boolean shouldRenderFacet(UIComponent facet) {
        if (!facet.isRendered()) {
            // For any future version of JSF where the f:facet gets a rendered attribute (https://github.com/javaserverfaces/mojarra/issues/4299)
            return false;
        }
        for (int i = 0; i < facet.getChildren().size(); i++) {
            // Stop when a child who is rendered is found.
            if (facet.getChildren().get(i).isRendered()) {
                return true;
            }
        }
        return false;
    }
```

facet is at this point a ` com.sun.faces.facelets.compiler.UIInstructions` so it can't have children, this method returns false then and makes the facet not displayed. I tried to figure something out to support this case by checking the type of the facet, but `UIInstructions`  is Mojarra impl, and I can't make the showcase working with MyFaces because of this:
> [ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.primefaces:showcase:6.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.primefaces.validate.ClientValidator

**Comment by jxmai** [comment]
@Rapster  Same time :+1: 

See

https://github.com/primefaces/primefaces/commit/daf45fd76cd2c6b3215502a19d5b649eacdbd57b#commitcomment-25065070

**Comment by Rapster** [comment]
Great minds think alike 😉

**Comment by tandraschko** [comment]
@rdebusscher Could you check that again? Otherwise we have to revert if we can't find a good solution.

**Comment by tandraschko** [comment]
@Rapster It's correct that we can't use the class itself but we already do something in ChildExpressionResolver:
`                if (!className.contains("UIInstructions") && !className.contains("UILeaf")) {
                    count++;
                }`

Works fine on both Mojarra and MyFaces

**Comment by rdebusscher** [comment]
I fixed it already this morning, see commit https://github.com/primefaces/primefaces/commit/f6b74fe392e9e281743b514305c425971c4b0b45

Based on feedback from jxmai https://github.com/primefaces/primefaces/commit/daf45fd76cd2c6b3215502a19d5b649eacdbd57b#commitcomment-25065070

**Comment by Rapster** [comment]
@rdebusscher what if it's a UIInstructions but rendered = false, your method will return true. This is why I mentionned testing the type of the facet, being said I think @tandraschko mentionned the solution to workaround the problem of JSF impl

@tandraschko we should create an util for this kind of testing, I know we're doing the same with UIRepeat

**Comment by rdebusscher** [comment]
@Rapster How can an UIInstruction be rendered false? 

Even this 
`<f:facet name="header"><!-- Comment --></f:facet>`
results in an UIInstructions which has rendered = true.

So we should look into the instructions property and look for LiteralCommentInstruction. But that is not possible since _UIInstructions_ is not in the spec and does not implement an interface which can be used to retrieve the individual instructions.

This corner case
`<f:facet name="header"><!-- Comment --></f:facet>`
is too my knowledge the only case which isn't working correctly for the moment.

**Comment by Rapster** [comment]
`<f:facet name="header"><!-- Comment --></f:facet>` rendered = true is normal, look at your generated html :wink: `ui:remove` should return rendered = false though.

How can UIInstructions be false? I honestly have no idea, but since it's a UIComponent I guess it can be not rendered :-D

**Comment by tandraschko** [comment]
So, is it fixed now? Then i would close it.

**Comment by Rapster** [comment]
IMO I don't like the fix very much. We should support UIInstructions just like you mentioned @tandraschko.

**Comment by tandraschko** [comment]
Yep, probably.
As users may also like to display plain html, which is wrapped by UIInstructions.
@rdebusscher Would you like to improve it?

**Comment by rdebusscher** [comment]
Plain text is working. If there is an issue with a certain construction,
please let me know.

The only issue which exists is when the developer puts an XML comment in
the facet, then the facet is always shown because the comment it is
identified as a UIComponent which is rendered.

**Comment by tandraschko** [comment]
Thats ok for me - IMO users should use javax.faces.FACELETS_SKIP_COMMENTS=true
