### ISSUE TITLE
Create p:autoUpdate

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2838]
Currently we only have 3 components which support autoUpdate=true
So if you would like to autoUpdate a component, you always have to wrap it with a p:outputPanel
It has some disadvantages:
1) additional markup in the browser
2) additional component in the JSF tree
3) additional tag in the xhtml, which is not very readable

We can do the following:
Introduce a new tag called p:autoUpdate, which can be attached to all components.

current:
`
<p:outputPanel autoUpdate=true>
<p:inputText ...>
</p:inputText>
</p:outputPanel>
`

new:
`
<p:inputText ...>
  <p:autoUpdate />
</p:inputText>
`

**Comment by tandraschko** [comment]
@melloware @jxmai @Rapster any comment? It's very similar to https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/358 but i don't think we currently need those additional features.

**Comment by melloware** [comment]
+1 for me.

**Comment by jxmai** [comment]
It is a nice feature :+1: . If I understand it correctly:

Current: 

1. Only three components can support `autoUpdate = true`

2. any other components need to have an output panel wrapper to make use of autoUpdate

---

Proposal:

any other component with `<p:autoUpdate /> `as a child can be searched and updated accordingly

**Comment by tandraschko** [comment]
exactly!

**Comment by Rapster** [comment]
Sounds nice! :wink:

**Comment by tandraschko** [comment]
Done!

**Comment by ghost** [comment]
Will `<p:autoUpdate />` have something like a 'disabled' attribute, so that it can be disabled for some conditions?

**Comment by tandraschko** [comment]
Did you checked it before asking? ;)

**Comment by ghost** [comment]
Oops, now that you're saying it, I notice the commit 
ee5cc12 (implemented disable attribute). ;-)

**Comment by jmorris1501** [comment]
tried using this with some autocomplete elements, causes the returned list to display like output text
![pf_1_expected](https://user-images.githubusercontent.com/13099697/37397494-6f4f72a2-2784-11e8-90f7-00c5ad832223.png)
![pf_2_actual](https://user-images.githubusercontent.com/13099697/37397496-6ff669b8-2784-11e8-8ebd-18804cc39334.png)

Attached pictures before and after clicking on the autocomplete.

<p:autoComplete id="regionDD" cache="true" dropdown="true" value="#{configBean.region}" scrollHeight="300" completeMethod="#{configBean.completeRegion}" var="region" itemLabel="#{region.reName}" itemValue="#{region}" converter="entityConverter" forceSelection="false"
                            size="35" required="true" disabled="#{not configBean.autoDefaults}">
                            <p:ajax event="itemSelect" listener="#{configBean.updateCustomers}" />
                            <p:autoUpdate />
                        </p:autoComplete>

page element above.

If anyone has encountered this, feedback or advice would be greatly appreciated

**Comment by elfwine** [comment]
What about those components that used autoUpdate attribute?
Like p:growl, the code will be like this?
before: <p:growl autoUpdate="true"/>
after:    <p:growl ><p:autoUpdate/></p:growl>

For me, it would be better to leave it as it is then just add p:autoUpdate as new feature. It will be also backward compatibles for older xhtml files.

just my 2 cents. ;)

**Comment by melloware** [comment]
@elfwine for consistency the autoUpdate="true" property was left in 6.2 but will be removed in 6.3.  It makes it confusing for future users to have two different ways to autoUpdate.

**Comment by tandraschko** [comment]
It's a step to a better API.
Like we made use of p:ajax in the past instead having (onSelectUpdate, onSelectProcess, onSelectListener...) for every event.
Removing attributes for a common global API is much better.

**Comment by elfwine** [comment]
Yes, I understand the concern for a better API.
My only concern is when a project developed prior to v6.2 and have to upgrade the primefaces jar library (e.g. for security reasons) in the future, xhtml files have to update too (which most of the time, we need to explain to clients why we have to touch xhtml files too).

**Comment by jxmai** [comment]
I guess 6.2 still remain `autoUpdate` attr (deprecated warning showing up on server console as a notice however), so you don't need to modify xhtml pages immediately giving you some time to verify if anything is broken on jar update.

**Comment by tandraschko** [comment]
you always have to ajdust something. PrimeFaces "lives" and is not in maintainence mode.
Therefore we have a migration guide.

If you just need to security fixes, use PrimeFaces Elite.

**Comment by kukel** [comment]
Does `p:autoUpdate` (or other components) still need some attention for this to fully work? `p:messages` seems to have a problem in relation to redirects/forward https://forum.primefaces.org/viewtopic.php?f=3&t=55471

**Comment by tandraschko** [comment]
Lets talk about it if we have a small as possible example, everything else is useless.

**Comment by Darlio** [comment]
I love this feature !!!! How do you add it to a UIComponent at run time ? Here is the "old" wayof doing it... How should I change it ?

> 	private void addGrowlToForm(UIComponent cForm) {
		Growl growl = new Growl();
		growl.setId("growlMessages_sticky");
		growl.setFor(aGrowlSticky);
		growl.setSticky(true);
		growl.setShowDetail(true);
		growl.setRedisplay(true);
		growl.setAutoUpdate(true);
		cForm.getChildren().add(growl);
	}

Of course, I could use an OutputLabel with escape ;-)... But probably better to create a component no?

Thanks for all... Best regards...

**Comment by tandraschko** [comment]
1) use the #createComponent API instead of new Growl
2) you have to do the same as in AutoUpdateTagHandler#apply

**Comment by Darlio** [comment]
This is great news !!! You are amizingly quick to answer... and very "straight to the point" !

 Thanks for the 
> #createComponent API instead of new

--> And for further people to read why (if I may add a link in this thread... remove it if it's not the case) : 
https://stackoverflow.com/questions/16610655/why-should-i-use-createcomponent-instead-of-creating-the-instance-myself

**Comment by Darlio** [comment]
Stuck at creation of AutoUpdateTagHandler :

Hello again, sorry to disturb, but I have been trying this the all night without success. Here is my code to now :

> 	private void addGrowlToForm(UIComponent cForm) {
		Growl aGrowl = (Growl) FacesContext.getCurrentInstance().getApplication().createComponent(Growl.COMPONENT_TYPE);
		aGrowl.setId("growlMessages_sticky");
		aGrowl.setFor(aGrowlSticky);
		aGrowl.setSticky(true);
		aGrowl.setShowDetail(true);
		aGrowl.setRedisplay(true);
		//--> DEPRECATED : aGrowl.setAutoUpdate(true);

		//--> Try 1 : Using #Apply directly

> 		FacesContext facesContext = FacesContext.getCurrentInstance();
>		FaceletContext faceletContext = (FaceletContext) facesContext.getAttributes().get(FaceletContext.FACELET_CONTEXT_KEY);
>		AutoUpdateTagHandler.apply(faceletContext, aGrowl);
>		// #Apply() is of course not STATIC in the Class, since it should attach the AUTOUPDATE component.

		//--> Try 2 : Creating a AutoUpdateTagHandler, but extends 'TagHandler' not UIComponent !!! 
>		AutoUpdateTagHandler aAutoUpdateTagHandler = (AutoUpdateTagHandler) FacesContext.getCurrentInstance().getApplication().createComponent(AutoUpdateTagHandler.COMPONENT_TYPE);
>		// 'COMPONENT_TYPE' Does not exist, of course

>cForm.getChildren().add(aGrowl);	
>	}

May I ask for some last hint ?

Thanks enourmesly ;-)

Regards,

Daric

**Comment by tandraschko** [comment]
Copy the code from the TagHandler#apply ;) This are only 2 subscribeToEvent calls.

**Comment by Darlio** [comment]
Amazing... Are you human ?

Thanks a lot !!! I'll chew that bone now...

Best of all days to you !

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/issues/4087

**Comment by Darlio** [comment]
SOLUTION (working & tested) :

> 	private void addGrowlToForm(UIComponent cForm) {
		Growl aGrowl = (Growl) FacesContext.getCurrentInstance().getApplication().createComponent(Growl.COMPONENT_TYPE);
		aGrowl.setId("growlMessages_sticky");
		aGrowl.setFor(aGrowlSticky);
		aGrowl.setSticky(true);
		aGrowl.setShowDetail(true);
		aGrowl.setRedisplay(true);
		//--> DEPRECATED : aGrowl.setAutoUpdate(true);
		//--> Copied from source code "https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/autoupdate/AutoUpdateTagHandler.java"
		aGrowl.subscribeToEvent(PostAddToViewEvent.class, new AutoUpdateListener(false));
		aGrowl.subscribeToEvent(PreRenderComponentEvent.class, new AutoUpdateListener(false));
		cForm.getChildren().add(aGrowl);	
	}

Great help and amazing answering - accurate - efficient - incredibly fast

Thanks again !

**Comment by tandraschko** [comment]
in 6.3 you can use:

AutoUpdateListener.subscribe(aGrowl, false);

**Comment by Darlio** [comment]
Hello again... back with some deep stuff : 

HOW TO change "disabled" of a component to whom was attached a AutoUpdate... DYNAMICALLY ?

Here are my investigation so far with a use case :

1. Context, goal :
I'm dividing a date in 3 InputMask to let user write down DAY, MONTH, YEAR in this specific order, but in a non-mandatory way. Here is the ClientSide representation :
![image](https://user-images.githubusercontent.com/32061339/46202817-198b6f80-c318-11e8-89bd-0c51ceb115cc.png)
My aim is to AUTO-FOCUS on the next InputMask. For example once the 2 characters are entered in the 'DAY' InputMask, the 'MONTH' is entered without any TAB key or ENTER key pressed.

2. Codes :
--> BEAN : Building of the InputMask 'dd' and 'MM' as example (code in picture for better reading):
![image](https://user-images.githubusercontent.com/32061339/46203573-8273e700-c31a-11e8-9325-59e5aa76f6d2.png)
--> BEAN : When KeyUp is done in the InputMask :
![image](https://user-images.githubusercontent.com/32061339/46203840-560c9a80-c31b-11e8-9954-f5fed17aff96.png)
--> XHTML :
![image](https://user-images.githubusercontent.com/32061339/46203917-9704af00-c31b-11e8-801d-ec1cf198d6cc.png)
(All is working accordingly and events are fired at the correct moment etc... no issues there)

3. The keypoint : is to be able to set the focus 'for' attribute with the correct ID, and update it at one specific moment : the 2nd character entered in the 'dd' InputMask (which is correctly identified).

4. Attempts :
![image](https://user-images.githubusercontent.com/32061339/46204851-f1533f00-c31e-11e8-9fbe-ca490d8094ef.png)

--> With AutoUpdate disable="false", the focus 'for' should then be manually managed! Since Null does not disable it.
--> With AutoUpdate disable="true", this attribute should be changed at run time. I tried to enable it but can't seem to get to it...

5. Suggestions :
An "easy" way to managed the 'disabled' property of the AutoUpdate tagHandeler

With my everlasting thanks, and sorry if my posts are long, hope it helps to clarify the needs ;-)

**Comment by tandraschko** [comment]
no time to check your post but if you want to disable/enable autoUpdate, you can pass it in the listener constructor.

**Comment by Rapster** [comment]
"How/Why" questions are supposed to be posted in the forum. Please don't use the issue tracker fo such questions

**Comment by Darlio** [comment]
Very sorry about this... Will transfer and not repeat !

**Comment by Darlio** [comment]
> no time to check your post but if you want to disable/enable autoUpdate, you can pass it in the listener constructor.

Is it suposed to be possible at run time ? It's not the case on my tests...

![image](https://user-images.githubusercontent.com/32061339/46207217-db497c80-c326-11e8-9313-6659920a83ed.png)

![image](https://user-images.githubusercontent.com/32061339/46207299-2d8a9d80-c327-11e8-8455-8c4d0bfb0610.png)

Best regards,

Daric

**Comment by tandraschko** [comment]
you may unsubscribeFromEvent the old listener first

**Comment by NEOMNI** [comment]
Is the "ignoreAutoUpdate=true" property also affected by this, as it can be set for the Button and Ajax components?

**Comment by tandraschko** [comment]
should work as before

**Comment by NEOMNI** [comment]
Thanks for the quick reaction!
