### ISSUE TITLE
PRIMEFACES SHOWCASE MENU-MENUBAR ERROR ICONS

### ISSUE THREAD

**Issue by sv3ntek** [primefaces/primefaces#2840]
I FOUND 1 ERROR, THE ICONS DONT SHOW CORRECTLY.
I'M USING CHROME WEB BROWSER.

![image](https://user-images.githubusercontent.com/32882769/31782922-2581806e-b4c2-11e7-8785-72ea47f1accb.png)

In my web project, I see it like this:
![image](https://user-images.githubusercontent.com/32882769/31783077-9de51fd4-b4c2-11e7-9843-45bb48ad0139.png)

in the mozilla browser, I see the icons correctly.
![image](https://user-images.githubusercontent.com/32882769/31783312-7162e30a-b4c3-11e7-9193-4a740fe3b653.png)

in other browsers I do not have this problem. Please help. Thanks.

**Comment by melloware** [comment]
Chrome 61 for me and works fine.

![image](https://user-images.githubusercontent.com/4399574/31783380-0b77389e-b4cc-11e7-92b0-28a683e0d8e5.png)

**Comment by jxmai** [comment]
This issue will likely be closed as https://github.com/primefaces/primefaces/issues/2826, but I suggest you to check your browser version, and open console to check if any error like GET failures

![image](https://user-images.githubusercontent.com/10467831/31783441-de722104-b4c3-11e7-94eb-bc8d6e8d89b8.png)

**Comment by sv3ntek** [comment]
this is my Chrome web browser version.

![image](https://user-images.githubusercontent.com/32882769/31784530-a38740d4-b4c7-11e7-901f-ccfa7262864b.png)


![image](https://user-images.githubusercontent.com/32882769/31785481-ec12c190-b4ca-11e7-908e-5dca53f5d4b3.png)


![image](https://user-images.githubusercontent.com/32882769/31785392-abf2e072-b4ca-11e7-8946-800f66832a22.png)


and I still do not find any mistake

**Comment by melloware** [comment]
Sorry I have tried it on 3 different computers with Chrome and all look fine.

**Comment by jxmai** [comment]
Clear cache or try incognito mode. It is likely that  one of the plugins was interfering. For example, Ad blocker:

> 
![image](https://user-images.githubusercontent.com/10467831/31790220-637bf8dc-b4da-11e7-9bca-2bfe8f764e42.png)

Took from your screenshot. Is it ad blocker ?



https://help.getadblock.com/support/solutions/articles/6000148708-adblock-blocks-font-awesome-social-media-icons

The last step is to check  whether the source exists, Let's say search `ui-menuitem-icon ui-icon ui-icon-pencil`

**Comment by sv3ntek** [comment]
@jxmai thanks a lot.

![image](https://user-images.githubusercontent.com/32882769/31791022-ea205584-b4dc-11e7-84ff-5f46fed2cfe3.png)


The problem was the blazemeter that was installed in the chrome browser.

**Comment by jxmai** [comment]
Plugin indeed :smiley:  Good to know the problem was solved :+1: .
