### ISSUE TITLE
<p:ajax event="blur"... can cause infinite loop of ajax calls

### ISSUE THREAD

**Issue by BarnT** [primefaces/primefaces#2842]
## Environment
- PrimeFaces version: 6.1.7
- Works in 4.0.13
- Application server + version: GlassFish 4.1.1
- Affected browsers: Chrome

## Sample XHTML

`<p:inputText value="#{someMB.whateverelse}" />
<p:inputText id="whatever" value="#{someMB.whatever}">
    <p:ajax event="blur" update="whatever"  />
</p:inputText>
`

## Steps to reproduce

In chrome, click into the whatever input, then push tab and then shift+tab to blur and focus the input. You have to do it quickly to get the the input element focused before the response (triggered by the blur event) arrives. Leave the focus in the field!
You can check the Network panel on Chrome's devToolbar: All ajax updates trigger a new ajax update, and it goes on infinitely. If you leave the "whatever" input (click somewhere else) then the infinite loop of ajax calls stops (right after it finishes all requests are already in the poll).

**Comment by tandraschko** [comment]
Also it might be a possible bug BUT i would really avoid ajax onblur, it's mostly unnecessary.

**Comment by BarnT** [comment]
Yes I know. I've chosen this example because this was the easiest way to define the problem, but the main reason behind it can cause problems in other situations too. 
For example if you have a custom JS module on the input that triggers 'change' on input's 'blur' event (based on some custom implementation), then even the p:ajax="change" can cause the same problem. 
I think the main reason is that the old html fragment's input fires the 'blur' event when it looses the focus while it is being replaced by the new html fragment.

**Comment by kaltuntas** [comment]
hi guys,
any update on this issue?

**Comment by tandraschko** [comment]
Nope but you can provide a PR or sponsor it via PrimeFaces PRO

**Comment by tandraschko** [comment]
You can probably avoid it when setting "PrimeFaces.customFocus=true;" in the onstart attribute. But note: if the input will be replaced by the ajax engine, it won't get refocused.

**Comment by tandraschko** [comment]
I will close the issue as it's a feature.
See my last comment for disable the feature.
