### ISSUE TITLE
Simplify RequestContext for Endusers / Splitup RequestContext for external and internal stuff

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2853]
Currently RequestContext is a pool of utilities like ComponentUtils, a Scoped object holder for internal stuff like AjaxRequestBuilder or WidgetBuilder and shortcut helpers for endusers.

What i would like todo, is to provide a new base for simple helpers for endusers.

Also, the naming of RequestContext and ApplicationContext sounds like JSF managed context or CDI managed contexts...

**Comment by tandraschko** [comment]
Currently RequestContext counts 30 methods:

    public static RequestContext getCurrentInstance() {
    public static RequestContext getCurrentInstance(FacesContext facesContext)
    public static void setCurrentInstance(RequestContext context, FacesContext facesContext)
    public abstract boolean isAjaxRequest();
    public abstract void addCallbackParam(String name, Object value);
    public abstract Map<String, Object> getCallbackParams();
    public abstract List<String> getScriptsToExecute();
    public abstract void execute(String script);
    public abstract void scrollTo(String clientId);
    public abstract void update(String name);
    public abstract void update(Collection<String> collection);
    public abstract void reset(String expressions);
    public abstract void reset(Collection<String> expressions);
    public abstract void reset(String... expressions);
    public abstract WidgetBuilder getWidgetBuilder();
    public abstract AjaxRequestBuilder getAjaxRequestBuilder();
    public abstract CSVBuilder getCSVBuilder();
    public abstract Map<Object, Object> getAttributes();
    public abstract void openDialog(String outcome);
    public abstract void openDialog(String outcome, Map<String, Object> options, Map<String, List<String>> params);
    public abstract void closeDialog(Object data);
    public abstract void showMessageInDialog(FacesMessage message);
    public abstract ApplicationContext getApplicationContext();
    public abstract StringEncrypter getEncrypter();
    public abstract void release();
    public abstract boolean isSecure();
    public abstract boolean isIgnoreAutoUpdate();
    public abstract boolean isRTL();
    public abstract void clearTableStates();
    public abstract void clearTableState(String clientId);

**Comment by tandraschko** [comment]
The following methods are really internal only:
public static void setCurrentInstance(RequestContext context, FacesContext facesContext)
public abstract WidgetBuilder getWidgetBuilder();
public abstract AjaxRequestBuilder getAjaxRequestBuilder();
public abstract CSVBuilder getCSVBuilder();
public abstract ApplicationContext getApplicationContext();
public abstract StringEncrypter getEncrypter();
public abstract void release();
public abstract boolean isIgnoreAutoUpdate();
public abstract boolean isRTL();

The following method can be removed as it's the same as FacesContext attributes, also it's same scoped:
public abstract Map<Object, Object> getAttributes();

**Comment by tandraschko** [comment]
I think the steps are the following: 

1) Provide a new enduser helper base (now)
2) Deprecate methods in RequestContext (now)
3) refactor RequestContext and ApplicationContext for internal usage (next version 6.3/7.0)
4) remove deprecated methods  (next version 6.3/7.0)

**Comment by tandraschko** [comment]
The method which should be in the new helperbase are:

public abstract boolean isAjaxRequest();
public abstract void addCallbackParam(String name, Object value);
public abstract Map<String, Object> getCallbackParams();
public abstract void execute(String script);
public abstract void scrollTo(String clientId);
public abstract void update(String name);
public abstract void update(Collection collection);
public abstract void reset(String expressions);
public abstract void reset(Collection expressions);
public abstract void reset(String... expressions);
public abstract void openDialog(String outcome);
public abstract void openDialog(String outcome, Map<String, Object> options, Map<String, List> params);
public abstract void closeDialog(Object data);
public abstract void showMessageInDialog(FacesMessage message);
public abstract void clearTableStates();
public abstract void clearTableState(String clientId);

**Comment by tandraschko** [comment]
I can imagine something like:

PrimeFaces.current().scrollTo(...);
PrimeFaces.current().resetInput(...);
PrimeFaces.current().executeScript(...);
PrimeFaces.current().ajax().addCallbackParam(...);
PrimeFaces.current().ajax().update(...);
PrimeFaces.current().dialog().open(...);
PrimeFaces.current().dialog().close(...);

It's little a bit like CDI.current() ;)
ajax() could also already throw a exception if the current request is a non-ajax request.

Also PrimeFaces is "very" stable and we always improve our widgets - but we should also always improve our core functionality.
RequestContext is there since version 1 or 2 and it really growed to a pool of everything :D

@mertsincan @melloware @rapster @jxmai any comments?

**Comment by jxmai** [comment]
I agree with providing a cleaner set of APIs than what RequestContext can do currently 👍 

From my understanding:

Current limitation / code smell of `RequestContext`:

1. expose some internal APIs such as `getWidgetBuilder()`, `getAjaxRequestBuilder()` to user space...

2. The naming of `RequestContext` is confusing

---

Proposal (the end result):

1. Request context will be optimized ***only for internal usage***. 

2. all user helper APIs will be moved to a new user Util class ***for external usage***.

3. to give a better name for the new Util class.

---

The idea is quite good actually, and deprecating the RequestContext first can remind user to transit to the new helper 😄 without breaking user's existing codebase initially.

**Comment by melloware** [comment]
@tandraschko I like it too.  We just have to make sure when deprecating RequestContext we leave good documentation on where the new replacement methods are.  The first thing I do when something is deprecated it look at the Javadoc to see what I should be using instead.

Other than that I 100% agree we should always be striving to improve the core codebase and not just the widgets.

**Comment by tandraschko** [comment]
commited something ;) Please review, we can still revert.
Also think we should rename Request/ApplicationContext to PrimeRequest/ApplicationContext in 6.3 or 7.0.

**Comment by jxmai** [comment]
I just gave the new helper a try from a user perspective.

Let's say if I have `RequestContext.getCurrentInstance().openDialog("theDialog", options, null);`

The java doc says:

```
The method openDialog(String, Map<String,Object>, Map<String,List<String>>) from the type RequestContext is deprecated
```

there is no recommended equivalent in docs.

and if I try to use `PrimeFaces.current()`

the only method I can find is `PrimeFaces.current().dialog()` which is different from`openDialog(String, Map<String,Object>, Map<String,List<String>>)`

**Comment by jxmai** [comment]
After taking a look at the code, then I know it should be `PrimeFaces.current().dialog().openDynamic(outcome, options, params);`. IMHO, documentation (especially java doc in detail for migration ) is really needed since user is not supposed to dig into the code to see what the equivalent method can be used. 

Please add something like

```
 @deprecated use {@link #new()} instead.  
```

to all deprecated methods.

**Comment by tandraschko** [comment]
should be better now.
WDYT about the naming openDynamic instead open? "openDialog" was confusing about the naming IMO.

**Comment by jxmai** [comment]
For some reason I still cannot see the alternative method in eclipse. Is it working for you ?

![image](https://user-images.githubusercontent.com/10467831/32004578-b94be83a-b967-11e7-9967-9013fc84fdb1.png)


----

>  "openDialog" was confusing about the naming IMO.

Why not just use 'open' instead of `openDynamic` ?

**Comment by tandraschko** [comment]
I don't use eclipse but seems like it says that you didn't have the javadocs - which are required for this comments.

because 'open' sounds like "open a normal dialog via PF('dlg').show()'" instead of opening it with the dialog framework.

**Comment by jxmai** [comment]
OK, thanks. Java doc was missing indeed. For instance,

![image](https://user-images.githubusercontent.com/10467831/32006214-bf34f0f8-b96b-11e7-9445-afae0f9c1a01.png)

---

> because 'open' sounds like "open a normal dialog via PF('dlg').show()'" instead of opening it with the dialog framework.

that's a point. show() and open() are indeed similar that might confuse user.

Overall is OK then AFAIK :+1:

**Comment by jxmai** [comment]
@tandraschko I think we should remove one of the duplicate deprecated comments.

![image](https://user-images.githubusercontent.com/10467831/32007577-8ddadbb8-b96f-11e7-8436-98a05d4dd9ca.png)

Usually the standard is to keep the one on the same line.

such as 

```
* @deprecated  reason this method is deprecated </br>
 *              {will be removed in ... version} </br>
 *              use {@link #new()} instead: 
 * 
```

---

For our case we just need to remove the previous one and add `instead` to the current one. Such as
```
**/**
       * Use PrimeFaces.ajax().update <!--Remove this
       * 
 +     * @deprecated Use PrimeFaces.ajax().update()  <--  add  "instead"
       */**
```
