### ISSUE TITLE
OutputLabel: add possiblity to always display the required indicator

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2854]
Currently we have an attribute called "indicateRequired".
True (default) means that the it's displayed when the component is required or @NotNull is present.
False means that it's never displayed.

The easiest way it the following now:
Auto (default) means that the it's displayed when the component is required or @NotNull is present.
true mean that it's always displayed
False means that it's never displayed.

**Comment by kukel** [comment]
Please add 'milestone' or version
