### ISSUE TITLE
PickList: Allow keeping moved items in original list

### ISSUE THREAD

**Issue by robertwenner** [primefaces/primefaces#2858]
I'd like to have a picklist where the moved items are not removed from their list, only added to the target list. That way I could add the same item multiple times.

For example, I could offer a list of cities to plan a trip. I could visit the same city multiple times. If my city list has Athens, Berlin, Copenhagen, I could make a trip from Berlin to Athens, back to Berlin, to Copenhagen.

Maybe this could be an attribute to the picklist tag?

**Comment by tandraschko** [comment]
It would be great if you could provide a PR or sponsor the feature via PrimeFaces PRO.

**Comment by melloware** [comment]
Closing this ticket as its superseded by #5309
