### ISSUE TITLE
pfRequired attribute is removed in PrimeFaces 6.1

### ISSUE THREAD

**Issue by mehdi-vaadin** [primefaces/primefaces#2860]
In PrimeFaces 6.0 there is an attribute named pfRequired that makes the associated label display an asterisk without having to make the UIInput required. But, it is removed in PrimeFaces 6.1. I would like to ask you to bring back pfRequired or add something similar to do the same functionality. A sample is shown below:

```
<p:outputLabel value="Name: " for="username" />
<p:inputText id="username" pfRequired="#{true}" />
```

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/issues/2854
pfRequired was a internal API and should never have been used by endusers.
