### ISSUE TITLE
Tree: filter on a property of node values

### ISSUE THREAD

**Issue by eversnarf** [primefaces/primefaces#2861]
## 1) Environment
- PrimeFaces version: 6.1.7
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 8.5.20
- Affected browsers: Firefox, Chrome, Edge

## 2) Expected behavior
When building a `<p:tree>` of nodes whose data is a bean, not a `String`, I expect to be able to apply filtering, say *startsWith*, on a property of these beans, as documented in the user manual:
```xml
<p:tree value="#{treeBean.root}" var="node" filterBy="#{node.name}">
    <p:treeNode>
        <h:outputText value="#{node}"/>
    </p:treeNode>
</p:tree>
```

## 3) Actual behavior
Filtering only works as expected when node values are `String`. When using a bean property, it returns no result.

## 4) Steps to reproduce
See example.

## 5) Sample XHTML
```xml
<p:tree value="#{treeBean.root}" var="node" filterBy="#{node.name}">
    <p:treeNode>
        <h:outputText value="#{node.name}"/>
    </p:treeNode>
</p:tree>
```

## 6) Sample bean
```java
public class TreeBean {

    private TreeNode root;

    public TreeBean() {
        this.root = new DefaultTreeNode();
        this.root.getChildren().add(new DefaultTreeNode(new Fruit("Lemon")));
        this.root.getChildren().add(new DefaultTreeNode(new Fruit("Apple")));
        this.root.getChildren().add(new DefaultTreeNode(new Fruit("Cherry")));
        this.root.getChildren().add(new DefaultTreeNode(new Fruit("Banana")));
    }

    public TreeNode getRoot() {
        return root;
    }

    public class Fruit {

        private String name;

        public Fruit(final String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

    }
}
```

## 7) Analysis
The expression passed in `filterBy` attribute seems to be ignored, or more precisely, it seems to be only used to trigger filtering or not, whatever the value of the expression is.
Then `org.primefaces.model.filter.StartsWithFilterConstraint.applies()` does an explicit `toString()` conversion of the node value before applying the filter (line 34):

```java
return value.toString().toLowerCase(locale).startsWith(filterText);
```
This is true for several implementations of `FilterConstraint`.

And indeed, if I add a custom `toString()` method to my `Fruit` class, it works as expected:
```java
        @Override
        public String toString() {
            return this.name;
        }
```

**Comment by melloware** [comment]
Yes everything is expected for filtering to be on Strings or Objects that implement a toString method.  How would you expect it to behave differently?  Or should I say what was your original expected result before you added the toString() method? 

Or are you saying that..
`filterBy="#{node.name}"`

Is actually only filtering on node and ignoring name like...
`filterBy="#{node}"`

**Comment by eversnarf** [comment]
I expect that it evaluates the expression passed in `filterBy` attribute and applies the filter on that value (by calling `toString()` on that value if necessary).

What happens is that the expression in `filterBy` is just ignored, only its presence is checked.
Whether I use `filterBy="#{node.name}"`, `filterBy="#{node}"`, `filterBy="#{primeFaces.rocks}"` or `filterBy="#{someRandomString}"`, I get the same result: the filter is applied on node data's `toString()` value (see `org.primefaces.component.tree.TreeRenderer.encodeFilteredNodes()`).

**Comment by melloware** [comment]
Understood. then I definitely agree that is a defect.

**Comment by zek72** [comment]
Hi, I am facing the same issue. May I learn what is the status of this issue?

**Comment by melloware** [comment]
It has been acknowledged as a defect but has not been fixed yet nor has any user submitted a PR to fix it yet.

**Comment by kukel** [comment]
@melloware: Same is true for datable afaik. And it was by design I think. Better ask @cagataycivici  since this has been changed a couple of times and it should **NOT** break backwards compatibility!!!

**Comment by Rapster** [comment]
@mertsincan is the author of that feature, he may have a clue :wink: (I'm facing the same problem actually)

**Comment by Rapster** [comment]
IMO, the problem is around here:
```java
protected void encodeFilteredNodes(FacesContext context, Tree tree, TreeNode node, String filteredValue, Locale filterLocale)
            throws IOException {
        
        int childCount = node.getChildCount();
        for (int i = 0; i < childCount; i++) {
            TreeNode childNode = node.getChildren().get(i);
            FilterConstraint filterConstraint = this.getFilterConstraint(tree);
            if (filterConstraint.applies(childNode.getData(), filteredValue, filterLocale)) {
                tree.getFilteredRowKeys().add(childNode.getRowKey());
            }
            encodeFilteredNodes(context, tree, childNode, filteredValue, filterLocale);
        }
    }
```

Instead of `childNode.getData()`, it should be the ValueExpression `filterBy` used for the filter constraint
