### ISSUE TITLE
InputTextRenderer doesn't pass the component to startElement() method

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2868]
Reported By PRO User;
> The renderer of the Primefaces inputText doesn't pass the component instance to writer.startElement() method as it should do. (This cause bugs in writers that have logic dependent on the component being written)

**Comment by tandraschko** [comment]
@mertsincan The fix is of course ok but could you please check if passthrough parameters aren't rendered two times now in JSF 2.2+? I faced something simliar in another component.

**Comment by mertsincan** [comment]
Ok, Thanks, @tandraschko ;) I'll check it. Also, I remember this issue; https://github.com/primefaces/primefaces/issues/274

**Comment by mertsincan** [comment]
I checked it and didn't see a problem. Test code;
```
<p:inputText pt:title="TEST" pt:readonly="readonly"/>

//DOM
<input id="j_idt112" name="j_idt112" type="text" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all" readonly="readonly" title="TEST" role="textbox" aria-disabled="false" aria-readonly="true">
```
