### ISSUE TITLE
SelectOneMenu: placeholder / watermark support for filter input

### ISSUE THREAD

**Issue by orange-buffalo** [primefaces/primefaces#2869]
Currently `SelectOneMenu` does not support a placeholder for the filter input. It would improve user experience if we could create `SelectOneMenu` components with menus like this:

![image](https://user-images.githubusercontent.com/4532247/32048340-76a2e686-ba49-11e7-90f0-dbc2169d3aac.png)

Probably it would also make sense to have `filterPlaceholder` for other components with `filter` support.

**Comment by tandraschko** [comment]
Did you try it? We already have a placeholder attribute

**Comment by orange-buffalo** [comment]
Yeap, the placeholder is applied to the control itself, i.e. "closed" state:

![image](https://user-images.githubusercontent.com/4532247/32050918-ed461ed0-ba52-11e7-8a05-903e1bece5b4.png)

But I couldn't find any attibute to set the filter input placeholder:

![image](https://user-images.githubusercontent.com/4532247/32050962-2296fb36-ba53-11e7-8522-25f319cb3612.png)

**Comment by melloware** [comment]
I will see if I can add this I am looking at selectOneMenu today anyway.

**Comment by tandraschko** [comment]
Thanks!

**Comment by orange-buffalo** [comment]
@melloware thanks a lot!

**Comment by melloware** [comment]
@orange-buffalo no problem!

**Comment by brivalin** [comment]
Hello there,
Has this feature been removed from Primefaces ? Can't find it in documentation for current version.
May have a new way to do it ?

**Comment by jepsar** [comment]
It's deprecated in 13:

https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/13_0_0

**Comment by melloware** [comment]
Wasn't there a filterPlaceholder property?

**Comment by brivalin** [comment]
My bad, it looks like it still exists in sources. 
But it may have been forgotten in the documentation : [https://primefaces.github.io/primefaces/12_0_0/#/components/selectonemenu](url)

**Comment by melloware** [comment]
Ahh OK let me fix the docs.
