### ISSUE TITLE
Support lazy live scroll in dataTable with unknown row count

### ISSUE THREAD

**Issue by erik-wramner** [primefaces/primefaces#287]
Issue #51 adds support for pagination with unknown row count. I would like to see the same support for the lazy-loaded live scroll in the data table. I have a working solution (will soon be available as a fork) that I would like to submit.

Support for an unknown row count is useful in many situations where counting the records would be expensive and where users typically browse through only a few pages, not all. This is even more natural with the live scroll feature than with standard paging, so it seems like a sensible thing to add.

**Comment by cagataycivici** [comment]
Review for 5.2.4.

**Comment by erik-wramner** [comment]
This was removed for 5.2.4 and now 5.2.6 is out. Is there anything I can do to help get this incorporated into a coming release? We are currently patching this into the released versions for our application, so it would be great to have it in the official code. The same goes for #51.

**Comment by cagataycivici** [comment]
We'll look into this for 5.3 but can't do it right now due to workload.

**Comment by mtrinidad** [comment]
This was added to 5.3 version ?

**Comment by erik-wramner** [comment]
No, we are still waiting. See #51. There should have been a review 8 days ago, but so far I haven't heard anything. Hopefully it will get accepted soon, I don't like using patched versions of the code.

**Comment by kukel** [comment]
does this also need a version? (and a 'new feature' tag)

**Comment by kukel** [comment]
@cagataycivici : this should get a milestone of 6.0 at least!
