### ISSUE TITLE
DataTables scroll bars bug when using scrollable="true" and selectionMode="multiple"

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2874]
Reported By PRO User;
> Hi,
We have DataTable and we use scrollable="true" & selectionMode="multiple" (both are required).
The problem occurs while we move the mouse across DataTables rows (hover) the scroll bars are appear & disappear.

**Comment by Adam-1** [comment]
@mertsincan 
Please note this issue doesn't show in newer chrome versions, maybe they fixed it for 62+ versions.
(Seems the width was also computing the box shadow)

**Comment by mertsincan** [comment]
Thanks @Adam-1 ;) I'll check it.

**Comment by mertsincan** [comment]
I'll revert my commit. Thanks again!
