### ISSUE TITLE
InputGroup: support icon-only button

### ISSUE THREAD

**Issue by garcia-jj** [primefaces/primefaces#2883]
InputGroup feature doesn't display properly buttons with no value. If the button have a value, the button are displayed properly.

I see this case in my app, and also occurs in Primefaces Showcase available here: https://www.primefaces.org/showcase/ui/input/inputGroup.xhtml.

This causes because of this css rule:

```
.ui-fluid .ui-inputgroup .ui-button {
    width: auto;
}
```

We need to add this rule to set minimal width when buttons hava no value:

```
.ui-fluid .ui-inputgroup .ui-button-icon-only {
	min-width: 2.3em;
}
```

Let me know if I can send a pull request with the fix.

## 1) Environment
- PrimeFaces version: latest build from source
- Does it work on the newest released PrimeFaces version? Version? N/A
- Does it work on the newest sources in GitHub? No
- Application server + version: Wildfly 10.1 patched to JSF 2.3
- Affected browsers: Firefox (Chrome are displayed properly)

## 2) Expected behavior

Button with the icon.

## 3) Actual behavior

Icon isn't displayed properly.

## 4) Steps to reproduce

Run code below.

## 5) Sample XHTML

```
<div class="ui-inputgroup">
    <p:commandButton icon="fa fa-check" styleClass="green-button"/> 
    <p:inputText placeholder="Vote" />
    <p:commandButton icon="fa fa-close" styleClass="red-button"/>     
</div>
```

## 6) Sample bean

Not necessary

**Comment by tandraschko** [comment]
did it with 2.2em!
