### ISSUE TITLE
Primefaces datatable component draggable and filter columns feature doesn't work together in ipad

### ISSUE THREAD

**Issue by prasannamadhavi** [primefaces/primefaces#2884]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: PrimeFaces Ultima theme [6.0]
- Does it work on the newest released PrimeFaces version? Version? working on Primefaces 6.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

...

## 3) Actual behavior

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by prasannamadhavi** [comment]
Need urgent and instant help. 

Any help is appreciated!

**Comment by tandraschko** [comment]
This is the community issue tracker and you didn't follow the required steps.
If you need urgent and instant help, it sound like you should use professional support: https://www.primefaces.org/support/
