### ISSUE TITLE
TimeLine: zoom issue

### ISSUE THREAD

**Issue by YahiaZZ** [primefaces/primefaces#2890]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- Primefaces 6.1
- PrimeFaces-extension-6.1.0
- Application server + version: Apache Tomcat7/8
- Affected browsers:
ALL
## 2) Expected behavior
When we zoom, it must be attached to task in left not moving
...

## 3) Actual behavior
When zoom, the event move from line to line and not corresponding to the task name in left
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
`<p:timeline id="timeline" value="#{missionView.model}"  editable="true" eventMargin="10" eventMarginAxis="0" showCurrentTime="true"
				start="#{missionView.start}"  end="#{missionView.end}" showNavigation="true" showButtonNew="true" var="ss"
				axisOnTop="true" stackEvents="true" zoomable="true"  widgetVar="timelineWdgt" eventStyle="box" >
				
				<p:ajax event="changed" update="@none" listener="#{missionView.onChange}"/>
				 
				<p:ajax event="edit"  update="frm:frmDl:detailsTacheInner"  listener="#{missionView.onEdit}"  /> 
            
				
         		
         		<p:ajax event="add"  update="frm:dialogAddTache"  listener="#{missionView.onAdd}" oncomplete="PF('dlgAddTache').show()"/>  
            
            	<p:ajax event="delete"  update="frm:deleteTacheDlg" listener="#{missionView.onDeleteTache}" onstart="PF('timelineWdgt').cancelDelete()"  oncomplete="PF('deleteTacheWdgt').show()"/>  
				
				<h:panelGrid columns="1" >  
			        <h:outputText value="#{ss.nom_tache}"/>  
			    </h:panelGrid> 
				
				</p:timeline>  `
..

## 6) Sample bean
When creating the event:
event = new TimelineEvent(list_taches_mission.get(j), start, end, true, (list_missions.get(i).getId_mission()+"/"+list_missions.get(i).getNom_mission()), availability.toLowerCase());
..
Thanks

**Comment by melloware** [comment]
Please create a reproducible test for us.

Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.

**Comment by YahiaZZ** [comment]
Hi melloware,
Thank you for your response,
I tried exactly the same code as shown in : 
https://www.primefaces.org/showcase-ext/sections/timeline/editServer.jsf;jsessionid=node0tmdix8ekp9cosozw68xtqy5d35498.node0

Thanks again

**Comment by YahiaZZ** [comment]
Hi, 
the same issue when I tried the primefaces extensions timeline example
Please could you help
Thanks

**Comment by melloware** [comment]
Is this similar to this issue which was fixed?  @PlassJ 

https://github.com/primefaces/primefaces/issues/1995

**Comment by PlassJ** [comment]
That may well be. But i didn't realy understand what is happening here.
@YahiaZZ can you reproduce this in the Primefaces showcase ?
And timeAxis on top or on bottom ? =)

**Comment by melloware** [comment]
@PlassJ yes i was having trouble understanding what the exact issue was too.

**Comment by melloware** [comment]
@YahiaZZ without more info or exact description of your issue we will most likely close this ticket.
