### ISSUE TITLE
VM513 core.js.xhtml? ln = primefaces & v = 6.0: 3

### ISSUE THREAD

**Issue by IngAlejandroSalazar** [primefaces/primefaces#2892]
hello helpme plesase, use primefaces 6.0, when entering my server it takes too long to load the pages, 17 seconds downloading (VM513 core.js.xhtml? ln = primefaces & v = 6.0: 3) how could this be solved?
LINK: https://ibb.co/ck7Law

**Comment by melloware** [comment]
It’s going to be impossible to diagnose just from looking at the network trace but I can tell you from looking at that screenshot your page has some crazy stuff going on there and it looks like it’s making Ajax calls on page load.  I would guess this looks like the “problem” but it’s only a symptom of whatever your inbox.xhtml page is doing...
