### ISSUE TITLE
SelectOneMenu: doesn't support string selectItem with combined customContent anymore

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#2893]
Hi, I'm testing the new COLLECT_SCRIPTS and I found the next problem.

## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version?
Yes, in version 6.1
- Application server + version: WildFly 10
- Affected browsers: Any browser

## 2) Expected behavior
**p:selectOneMenu** should work if **f:selectItem** is used and the attribute **var** is set.

## 3) Actual behavior
**p:selectOneMenu** throws this error:
javax.el.PropertyNotFoundException: The class 'java.lang.String' does not have the property 'xxxxx'.

## 4) Steps to reproduce
The next example taken of the showcase should reproduce it.

```
<p:selectOneMenu value="#{selectOneMenuView.theme}">
	<f:selectItem itemLabel="Select one..." itemValue="" />
	<f:selectItems value="#{selectOneMenuView.themes}" var="theme" itemLabel="#{theme.displayName}" itemValue="#{theme}" />
	<p:column>
		<h:outputText styleClass="ui-theme ui-theme-#{t.name}" />
	</p:column>
	<p:column>
		<h:outputText value="#{t.displayName}" />
	</p:column>
</p:selectOneMenu>
```

I think this problem was not introduced intentionally, the commit related is: https://github.com/primefaces/primefaces/commit/49c95a753328691ce07695315600ccb24bff4f8a

The lines (363 to 369) were removed:
https://github.com/primefaces/primefaces/blob/f83db0b51eb152f81ea10670689659f49f5be41e/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L362-L382

**Comment by melloware** [comment]
I think this commit is the one that lost it:  https://github.com/primefaces/primefaces/commit/49c95a753328691ce07695315600ccb24bff4f8a#diff-e4d3a342df3de892c8fd79acabe27e6b

**Comment by melloware** [comment]
I am running the showcase locally with the latest 6.2-SNAPSHOT and the advanced custom content example is working fine for me...

![image](https://user-images.githubusercontent.com/4399574/32296396-8a91cc42-bf22-11e7-914e-97e6b9cda2f6.png)

**Comment by wsaca** [comment]
The showcase works fine, you should add this line to test it:
<f:selectItem itemLabel="Select one..." itemValue="" />

**Comment by melloware** [comment]
Ahh  I think it was removed on purpose if you read through this original ticket.

https://github.com/primefaces/primefaces/issues/1036

The problem is trying to tell a <String> value from an empty no select item.

**Comment by tandraschko** [comment]
does the example miss the "var" attribute? The given example can't work actually as #{t} is not resolvable

**Comment by melloware** [comment]
If I do this I can verify its broken because its trying to convert the first "Select One" to a Theme object.

```xml
                <p:selectOneMenu id="advanced" value="#{selectOneMenuView.theme}" converter="themeConverter" panelStyle="width:180px"
                                 effect="fade" var="t" style="width:160px" filter="true" filterMatchMode="startsWith">
                    <f:selectItem itemLabel="Select One" itemValue="" />
                    <f:selectItems value="#{selectOneMenuView.themes}" var="theme" itemLabel="#{theme.displayName}" itemValue="#{theme}" />

                    <p:column style="width:10%">
                        <h:outputText styleClass="ui-theme ui-theme-#{t.name}" />
                    </p:column>

                    <p:column>
                        <h:outputText value="#{t.displayName}" />
                    </p:column>
                </p:selectOneMenu>
```

Fails with error:

> java.lang.ClassCastException: java.lang.String cannot be cast to org.primefaces.showcase.domain.Theme

**Comment by wsaca** [comment]
@melloware  if this was removed intentionally, then it should be included in the migration guide because will break the apps that use f:selectItem with the var attribute.

**Comment by melloware** [comment]
@Lynx12 no we need to fix it.  I meant intentionally as it was trying to solve the List<String> problem but inadvertently broke this scenario.   I think we need to fix it.

**Comment by tandraschko** [comment]
We should really think about it if it's valid....
the custom content can't work correctly in this case as the #{t} is just a string (if we would fix the cast exception)

**Comment by tandraschko** [comment]
Or we should just re-introduce the if statement we removed ;)

**Comment by tandraschko** [comment]
We had this statement:
if (itemValue == null || itemValue instanceof String) {

if we would correctly fix it, we have to replace "String" with the real value type... 

We can do the following:
1) if (itemValue == null) {
    this should normally work correctly (not sure about coercing...) but "itemValue=""" should be removed from the user completly

2) if (itemValue == null || itemValue instanceof "get the type from the value valueExpression) {

WDYT?

**Comment by wsaca** [comment]
You are right, the first option sounds good. What about the use of noSelectionOption?

**Comment by melloware** [comment]
@tandraschko I like the fix.
