### ISSUE TITLE
DialogFramework: Provide ability to set iframe 'title' attribute (like Lightbox provides)

### ISSUE THREAD

**Issue by paulspinelli** [primefaces/primefaces#2894]
PrimeFaces 6.0
The Dialog component constructs an iframe; however, the component does not provide a means to set the 'title' attribute of the resulting iframe. Due to Section 508 requirements, the iframe 'title' attribute must contain descriptive text. The Lightbox component does provide such an attribute (iframeTitle).

**Comment by melloware** [comment]
The section he is referring to is:  https://www.section508.va.gov/support/webdev/5_5a.asp

I can look at this one if you want @tandraschko ?

Also should there be a default title="" if no title is specified by the user.  Something like title="Dialog"?

**Comment by tandraschko** [comment]
Why not ;) I woudln't change the default for now
