### ISSUE TITLE
Improve DataTable LiveScroll Performance

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#29]
Window live scrolling, with specified number or rows N. It displays only the current N rows, where on scrolling down dataTable removes previous rows from view and load new ones and vice versa for scrolling up. 

Motivation:
dataTable with large number of rows produces large number of DOM elements on the page. Although, with live scrolling, this can be initially solver, after 10 scrolls down, the number of DOM elements is increasing rapidly, especially if you have a dataTable with significant number of columns (>=10). 
Users usually scroll down through dataTable (that's the purpose of scrollinhg) thus creating more and more DOM elements on page. If you breach some critical number of these on page, you are facing a serious problem of rerendering this page without reloading it. Therefore, I believe this would be an important innovative improvement on dataTable. 

Benefits:
1. Keeping the number of DOM elements low
2. Feeling of continuous result set and scrolling is kept

**Comment by Rapster** [comment]
If i'm not mistaken, that's exactly what virtual scrolling is suppose to do (which we already have)
