### ISSUE TITLE
Theme: DataTable scrollable - header above scrollbar wrong styling

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#2901]
Open showcase https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml and for example use theme blitzer. You will notice a red header above the scrollbar from the theme.

At header _ui-widget-header ui-datatable-scrollable-header_ just add _ui-state-default_. Same for footer.

![scrollable](https://user-images.githubusercontent.com/5265550/32436865-c08ef10a-c2e5-11e7-890e-67b1c24660f6.jpg)

**Comment by melloware** [comment]
@djmj please review my PR.

**Comment by melloware** [comment]
See the conversation in the PR.  Seems like this was intended styling it just looks goofy in some themes like Blitzer.  https://github.com/primefaces/primefaces/pull/2936

**Comment by melloware** [comment]
I think this is a theme specific issue that should be addressed per theme as none of the newer themes have this issue.  You can always open a new issue in the themes project: https://github.com/primefaces/themes/issues
