### ISSUE TITLE
AutoComplete: Accessibility of column

### ISSUE THREAD

**Issue by cklaffke** [primefaces/primefaces#2903]
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Wildfly 10
- Affected browsers: Chrome, IE, Firefox (all I tested)

## 2) Expected behavior
When using p:autocomplete with both attribute "itemLabel" and child "p:column", a screen reader should read the content of "p:column" when scrolling through search results and the content of "itemLabel" when an element is selected.

## 3) Actual behavior
In both cases - in selection mode and after selection - the content of "itemLabel" will be read.

## 4) Steps to reproduce
Use a screenreader, for example ChromeVox plugin in Chrome and start typing any character. Compare what is read when searching the items and what is read when one item is selected. It is "item label" in both cases. "item column" is never read.

## 5) Sample XHTML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head></h:head>
<h:body>

    <h:form>
        <h:panelGrid columns="2" cellpadding="5">
            <p:outputLabel value="Simple:" for="acSimple"/>
            <p:autoComplete id="acSimple"
                            value="#{autoCompleteView.txt1}"
                            var="item"
                            itemValue="#{item}"
                            itemLabel="test label"
                            completeMethod="#{autoCompleteView.completeText}">
                <p:column>
                    test column
                </p:column>
            </p:autoComplete>
        </h:panelGrid>
    </h:form>

</h:body>
</html>

## 6) Sample bean

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;

@ManagedBean
public class AutoCompleteView {

    private String txt1;

    public List<String> completeText(String query) {
        List<String> results = new ArrayList<String>();
        for(int i = 0; i < 10; i++) {
            results.add(query + i);
        }

        return results;
    }

    public String getTxt1() {
        return txt1;
    }

    public void setTxt1(String txt1) {
        this.txt1 = txt1;
    }

}

**Comment by melloware** [comment]
@MarkusChur another one to investigate. 😄

**Comment by melloware** [comment]
@cklaffke it looks like we are using `role="option"` which according to the ARIA spec is the correct role.  See: https://www.digitala11y.com/option-role/

Closing for now unless you have more info on why the screen reader is reading it this way or a suggestion for the correct ARIA attributes if you can figure them out.
