### ISSUE TITLE
Scrollable Tabview throws JS error with zero tabs

### ISSUE THREAD

**Issue by SavchenkoVV** [primefaces/primefaces#291]
If try to open dialog with Dynamic TabView:

Uncaught TypeError: Cannot read property 'left' of undefined
at
var overflown = ((this.lastTab.position().left + this.lastTab.width()) - this.firstTab.position().left) > this.navscroller.innerWidth();

of

initScrolling: function() {
        var overflown = ((this.lastTab.position().left + this.lastTab.width()) - this.firstTab.position().left) > this.navscroller.innerWidth();
        if(overflown) {
            this.navscroller.css('padding-left', '18px');
            this.navcrollerLeft.show();
            this.navcrollerRight.show();
            this.restoreScrollState();
        }
    }

this.lastTab.position() - undefined

After dialog closing, it cannot be opened again, until page will not be reloaded.

**Comment by cagataycivici** [comment]
Post your code please, you cannot/shouldn't put a dialog inside a tabview.

**Comment by SavchenkoVV** [comment]
TabView inside dialog. 

``` html
 <p:dialog id="documentsViewDialogID"
                  widgetVar="documentsViewDialog"
                  header="Documents"
                  resizable="false"
                  modal="true"
                  dynamic="true"
                  width="750"
                  height="550">

            <p:tabView style="min-height: 500px;">
                <p:tab title="Current">
                    <p:tabView value="#{contractDocumentsBean.getCurrentDocuments()}"
                               var="doc"
                               scrollable="true">

                        <p:tab title="#{doc.name}">
                            <h:form enctype="multipart/form-data">

                            </h:form>                            
                        </p:tab>
                    </p:tabView>
                </p:tab>
                <p:tab title="Others">
                    <p:tabView value="#{contractDocumentsBean.getOtherDocuments()}"
                               var="doc"
                               scrollable="true">

                        <p:tab title="#{doc.name}">
                            <h:form>

                            </h:form>
                        </p:tab>
                    </p:tabView>
                </p:tab>
            </p:tabView>
        </p:dialog>
```

Problem detected when contractDocumentsBean.getCurrentDocuments() or contractDocumentsBean.getOtherDocuments() return empty List.

**Comment by cagataycivici** [comment]
Actual problem was scrollable tabview without any tabs.

**Comment by SavchenkoVV** [comment]
Thanks
