### ISSUE TITLE
AutoComplete: forceselection="true" triggers multiple requests

### ISSUE THREAD

**Issue by giorgioprimefaces** [primefaces/primefaces#2910]
## 1) Environment

Defect on PF 6.1.7 and 6.1.8 (was working on PF 6.1.3 and previous) not tested 6.1.4, 6.1.5, 6.1.6
using Apache Tomcat 7.068

 ## 2) Expected behavior
listener called once

## 3) Actual behavior
 after item selection if I click anywhere outside the autocomplete listener is called one more time

## 4) Steps to reproduce

set forceSelection="true" using a converter

## 5) Sample XHTML
`<p:autoComplete     value="#{beanGiornalieroAttiv.spazioSel2}" completeMethod="#{beanGiornalieroAttiv.completeLuogo}"
var="luo" itemLabel="#{luo.luogoConPrincipale}" itemValue="#{luo.codSpazio}"
dropdown="false" size="80" maxResults="30"  minQueryLength="3"
converter="luogoCV" forceSelection="true"/>`

**Comment by jxmai** [comment]
It sounds like a regression, but your sample is not runnable. Please provide a sample based on https://github.com/primefaces/primefaces-test or  paste a fully runnable bean + xhtml

**Comment by tandraschko** [comment]
@mertsincan Can you check this? Not sure if broken in trunk but it seems that it broke between 6.1.3 and 6.1.7

**Comment by jxmai** [comment]
@mertsincan Just a guess, but it might be worth revisiting this ticket: https://github.com/primefaces/primefaces/issues/2733 and this commit: https://github.com/primefaces/primefaces/commit/711b002204aaf73cd1240470ab9ccfbf190132c2

**Comment by mertsincan** [comment]
I'll check it.
