### ISSUE TITLE
SplitButton: support dynamic model

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2913]
Just like components like MenuButton, Menu, etc. They support programmatic model. Would be awesome to do the same with SplitButton. Someone requested this feature some time ago https://forum.primefaces.org/viewtopic.php?p=70595

**Comment by melloware** [comment]
duplicate of https://github.com/primefaces/primefaces/issues/766

**Comment by Rapster** [comment]
My bad :(
