### ISSUE TITLE
Build source warning: *** must be private and have accessor methods.

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#2914]
## 1) Environment
- PrimeFaces version: PF 6.2 trunk
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

There should not be any warning during source audit

## 3) Actual behavior

There are some warnings during source audit

## 4) Steps to reproduce

https://travis-ci.org/primefaces/primefaces/jobs/299688642

```
[INFO] Starting audit...
/home/travis/build/primefaces/primefaces/src/main/java/org/primefaces/behavior/ajax/AjaxBehavior.java:63:31: warning: Variable 'expectedType' must be private and have accessor methods.
/home/travis/build/primefaces/primefaces/src/main/java/org/primefaces/behavior/confirm/ConfirmBehavior.java:36:31: warning: Variable 'expectedType' must be private and have accessor methods.
Audit done.
```

## 5) Code location

https://github.com/primefaces/primefaces/blob/88ab4bfbdaa6e0c1e38d288d434b1fb37f5090ec/src/main/java/org/primefaces/behavior/ajax/AjaxBehavior.java#L63

https://github.com/primefaces/primefaces/blob/88ab4bfbdaa6e0c1e38d288d434b1fb37f5090ec/src/main/java/org/primefaces/behavior/confirm/ConfirmBehavior.java#L36

**Comment by tandraschko** [comment]
-1 for changing something here ;)

**Comment by jxmai** [comment]
Just leave it as is ? :thinking:

**Comment by tandraschko** [comment]
Whats the problem with that code? Just check the usages, using getter would be not that nice

**Comment by jxmai** [comment]
OK, I see :) Not a problem really but the  compilation process always pop up some warning so I thought it might be worth taking a look.

**Comment by jxmai** [comment]
I checked the usage. `expectedType` is used by `AjaxBehaviorHandler` and `ConfirmBehaviorHandler`

https://github.com/primefaces/primefaces/blob/88ab4bfbdaa6e0c1e38d288d434b1fb37f5090ec/src/main/java/org/primefaces/behavior/ajax/AjaxBehaviorHandler.java#L79-L101


https://github.com/primefaces/primefaces/blob/88ab4bfbdaa6e0c1e38d288d434b1fb37f5090ec/src/main/java/org/primefaces/behavior/confirm/ConfirmBehaviorHandler.java#L41-L50
