### ISSUE TITLE
DataTable: Paginator JumpToPageDropdown slows dataTable update

### ISSUE THREAD

**Issue by mmariotti** [primefaces/primefaces#2933]
I found the issue using `{JumpToPageDropdown}` on a large dataset.
While server side took about 200ms to process the request and write the response, the browser took about 5s to update the UI.
The slow effect is emphasized using a <p:blockUI>.
Further investigation led to this piece of code:
```
PrimeFaces.widget.Paginator = PrimeFaces.widget.BaseWidget.extend({
	...
	updateUI: function() {
		...
		//jump to page dropdown
		if(this.jtpSelect.length > 0) {
			this.jtpSelect.children().remove();

			for(var i=0; i < this.cfg.pageCount; i++) {
				this.jtpSelect.append("<option value=" + i + ">" + (i + 1) + "</option>");
			}
			this.jtpSelect.children('option[value=' + (this.cfg.page) + ']').prop('selected','selected');
		}
		...
	}
```

There are two bottlenecks in this code:

1. rebuilds options when it's not necessary
2. appends options one by one

This should be updated with:

```
//jump to page dropdown
if(this.jtpSelect.length > 0) {
	if(this.jtpSelect[0].options.length != this.cfg.pageCount){
		var jtpOptions = '';
		for(var i = 0; i < this.cfg.pageCount; i++) {
			jtpOptions += '<option value="' + i + '">' + (i + 1) + '</option>';
		}

		this.jtpSelect.html(jtpOptions);
	}
	this.jtpSelect.children('option[value=' + (this.cfg.page) + ']').prop('selected','selected');
}
```

Anyway, even if this update gives a sensible performance boost, using JumpToPageDropdown still makes dataTable laggish and should be avoided for large datasets. 

## 1) Environment
- PrimeFaces version: 6.1.6
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Wildfly 10.1.0
- Affected browsers: All, worst on IE

## 2) Expected behavior
after dataTable page navigation, paginator updateUI() should render jtpSelect without slowing down

## 3) Actual behavior
after dataTable page navigation, paginator updateUI() takes too much time to build options for jtpSelect

## 4) Steps to reproduce
create a lazy DataTable with at least 200.000 pages (rpp is not important) and paginatorTemplate="{JumpToPageDropdown}".
Select any page from the dropdown to trigger the issue

## 5) Sample XHTML
```
<p:blockUI block="table" trigger="table">
	<div>loading...</div>
</p:blockUI>

<p:dataTable id="table" var="data" value="#{testPaginatorBean.model}" lazy="true" rows="5" paginator="true"
	paginatorAlwaysVisible="true"
	paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {JumpToPageDropdown} {NextPageLink} {LastPageLink}"
	currentPageReportTemplate="records: {totalRecords} - pages: {totalPages}">
	
	<p:column>#{data}</p:column>
</p:dataTable>
```
..

## 6) Sample bean
```
@ManagedBean
@ViewScoped
public class TestPaginatorBean implements Serializable
{
    private static final long serialVersionUID = 1L;

    private LazyDataModel<String> model = new LazyDataModel<String>()
    {
        private static final long serialVersionUID = 1L;

        @Override
        public List<String> load(int first, int pageSize, List<SortMeta> multiSortMeta, Map<String, Object> filters)
        {
            setRowCount(200000);

            return IntStream.range(first, first + pageSize)
                .mapToObj(x -> "row " + (x + 1))
                .collect(Collectors.toList());
        }

        @Override
        public List<String> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters)
        {
            return load(first, pageSize, null, null);
        }
    };

    public LazyDataModel<String> getModel()
    {
        return model;
    }
}
```

**Comment by melloware** [comment]
First, what you are seeing is a known problem in IE for many many years.  The larger your "options" list the worst the performance.  See the following:

https://stackoverflow.com/questions/26230200/slow-select-option-rendering-in-internet-explorer-with-large-number-of-items-c

https://github.com/primefaces/primefaces/issues/2089

Second, I agree with your optimization it will definitely help a little bit from re-rendering.

**Comment by mmariotti** [comment]
@melloware didn't know about this IE issue, good to know.
Thank you.
