### ISSUE TITLE
Datatable: Colspan problem with hidden columns and row expansion

### ISSUE THREAD

**Issue by ennerf** [primefaces/primefaces#2937]
The row expansion  is causing layout problems when the main table has hidden columns. The same issue was filed before in #1037 and was supposedly fixed in 6.0.

However, I'm still seeing the same behavior in 6.0 and 6.1.

The issue disappears after also adding **resizableColumns="true"**

**Comment by melloware** [comment]
This was fixed with #5211 calculating colspan correctly to include hidden columns.
