### ISSUE TITLE
selectOneMenu: with lazy="true" not rendered correctly after ajax update

### ISSUE THREAD

**Issue by koan00** [primefaces/primefaces#2938]
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT Git Hash: 72a25feaf374be910c1fab22662074e4763be8b8
- Does it work on the newest released PrimeFaces version? New Feature after 6.1, unavailable.
- Application server + version: Tomcat 7.0.82 / Mojarra 2.2.14
- Affected browsers: Firefox 57, IE 11, Chrome 62

## 2) Expected behavior

selectOneMenu selection options update to use latest values from backing bean

## 3) Actual behavior

selectOneMenu selection options list is empty

## 4) Steps to reproduce

1. Create 2 UI components inside a form, one of which is selectOneMenu with lazy="true".
2. Expand the selectOneMenu to see list of items
3. From the first UI component, trigger an ajax event which updates the backing data list for the selectOneMenu  selectItems
4. Expand the selectOneMenu a second time, to see list of items

Note: If step 2 is omitted, the list updates as expected.

## 5) Sample XHTML

` 
 <h:form>
    <h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5">
        
        <p:outputLabel for="trigger" value="Ajax trigger:" />
        <h:selectOneMenu id="trigger"  >
        	<f:selectItem itemLabel="Select One" itemValue="#{null}" />
			<f:selectItem itemLabel="valueX" itemValue="valueX"/>
			<f:selectItem itemLabel="valueY" itemValue="valueY"/>
			<p:ajax event="change" update="@form" listener="#{exampleBean.updateExampleValues()}" />
		</h:selectOneMenu>        
        
        <p:outputLabel for="notLazy" value="Not Lazy:" />
        <p:selectOneMenu id="notLazy" lazy="false" style="width:125px" >
            <f:selectItem itemLabel="Select One" itemValue="#{null}" />
            <f:selectItems value="#{exampleBean.exampleValues}" var="item" itemLabel="#{item}" itemValue="#{item}" />         
        </p:selectOneMenu>
        
        <p:outputLabel for="lazy" value="Lazy:" />
        <p:selectOneMenu id="lazy" lazy="true" style="width:125px" >
             <f:selectItem itemLabel="Select One" itemValue="#{null}" />
             <f:selectItems value="#{exampleBean.exampleValues}" var="item" itemLabel="#{item}" itemValue="#{item}" />
        </p:selectOneMenu>
    </h:panelGrid>
 </h:form>
`

## 6) Sample bean
`
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "exampleBean")
@ViewScoped
public class ExampleBean implements Serializable {

	private List<String> exampleValues;

	@PostConstruct
	public void init() {
		exampleValues = new ArrayList<String>();
		exampleValues.add("value1");
		exampleValues.add("value2");
		exampleValues.add("value3");
		exampleValues.add("value4");
	}

	public void updateExampleValues() {
		exampleValues.clear();
		exampleValues.add("value5");
		exampleValues.add("value6");
		exampleValues.add("value7");
		exampleValues.add("value8");
	}
	
	public List<String> getExampleValues() {
		return exampleValues;
	}

	public void setExampleValues(List<String> exampleValues) {
		this.exampleValues = exampleValues;
	}
}
`

**Comment by tandraschko** [comment]
PR is welcome

**Comment by Berger1994** [comment]
The problem is that the property "isLazyLoaded" of the javascript component SelectOneMenu is never set to false after the panel is opened.

My workaround for this bug is following javascript code:


```
PrimeFaces.widget.SelectOneMenu.prototype.init0 = PrimeFaces.widget.SelectOneMenu.prototype.init;
PrimeFaces.widget.SelectOneMenu.prototype.init = function(cfg) {
    this.init0(cfg);

    this.isLazyLoaded = false;
};
```

**Comment by melloware** [comment]
Please review my PR of your fix.  https://github.com/primefaces/primefaces/pull/2964

**Comment by koan00** [comment]
Works for me, thanks all.
