### ISSUE TITLE
SelectOneButton: unselectable=false, but the ui-state-active is replaced by an ui-state-focus on click instead of adding it.

### ISSUE THREAD

**Issue by AskIng87** [primefaces/primefaces#2943]
If you choose unselectable="false" there is alwasy the problem, that the ui-state-active within the active item will replaced by an ui-state-focus. You have to click outside the element to get the ui-state-active back. Can u fix this problem? If an item is selected an the "unselectable=false" attribute is set, you should remove ui state-active.

## 1) Environment
Primefaces 6.1.5

## 2) Expected behavior

The active item will hold the ui-state-active state and maybe get the other one added (ui-state-focus)

"ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right ui-state-active ui-state-focus"

## 3) Actual behavior
"ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right ui-state-focus"

or 

"ui-button ui-widget ui-state-default ui-button-text-only ui-corner-right ui-state-active "

## 4) Steps to reproduce

see below

## 5) Sample XHTML

<h:form>
    <h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5">
        <h:outputText value="Platform:" />
        <p:selectOneButton value="#{selectOneView.option}" **unselectable="false"**>
            <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
            <f:selectItem itemLabel="PS4" itemValue="PS4" />
            <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
        </p:selectOneButton>
 
        <p:commandButton value="Submit" update="display" icon="ui-icon-check" />
        <p:spacer />
 
        <h:outputText value="Selected:" />
        <h:outputText id="display" value="#{selectOneView.option}" style="font-weight: bold" />
    </h:panelGrid>
</h:form>

## 6) Sample bean

package org.primefaces.showcase.view.input;
 
import javax.faces.bean.ManagedBean;
 
@ManagedBean
public class SelectOneView {
     
    private String option;
     
    public String getOption() {
        return option;
    }
 
    public void setOption(String option) {
        this.option = option;
    }
}

**Comment by AskIng87** [comment]
See also https://github.com/primefaces/primefaces/issues/2510

**Comment by tandraschko** [comment]
Works fine for me in trunk. @mertsincan would be able to port my fixes into elite if required ;)
