### ISSUE TITLE
DataTable: more stateful behaviour for the expandedRowGroups

### ISSUE THREAD

**Issue by PlassJ** [primefaces/primefaces#2946]
Dear Primefaces community,

we are currently using the Datatable with the new expandableRowGroups feature.
Data in the Datatable is sorted by day. 
When we process and update the datatable all states of the expandableRowGroups get lost.
So as subtables are deprecated and a mix of accordionPanel and datatables did not feel very good, 
i would like to suggest something like this:

- add an attribute to datatable to render all headerRows as expanded or collapsed (expandedRowGroups = true/false)
- add an expanded attribute to "headerRow"
- add an event "onExpand" to "headerRow"
- add an event "onCollapse" to "headerRow"

Or maybe you have a better idea of changing the code to achieve a more stateful behaviour for the expandedRowGroups.

Environment

PrimeFaces version: 6.1.8
Does it work on the newest released PrimeFaces version? no
Does it work on the newest sources in GitHub? no
Application server + version: WildFly
Affected browsers: all

**Comment by melloware** [comment]
This is definitely an enhancement that is pretty significant. Probably need to be sponsored by a PRO account or submitted as a PR.

**Comment by melloware** [comment]
Fixed for 9.0: https://github.com/primefaces/primefaces/issues/6325
