### ISSUE TITLE
Bar Chart doesn't work when X axis values are same

### ISSUE THREAD

**Issue by subhojit11** [primefaces/primefaces#2948]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server: Tomcat
- Affected browsers: IE

## 2) Expected behavior

Should generate the chart as per the X axis values.

## 3) Actual behavior

Only one value in X axis shown. 

## 4) Steps to reproduce
Create a bar chart where X axis values are same.

## 5) Sample XHTML
<p:chart type="bar" model="#{chartView.barModel}" style="height:300px"/>

## 6) Sample bean

       BarChartModel model = new BarChartModel();
        ChartSeries boys = new ChartSeries();
        boys.setLabel("Boys");
        boys.set("2004", 120);
        boys.set("2004", 250);
        boys.set("2004", 75);
        model.addSeries(boys);

**Comment by melloware** [comment]
Is that right?  You have 3 values mapped to 2004 I am guessing only the last one wins?  You would have to create 3 separate Series and map each one to get its own bar right?

**Comment by melloware** [comment]
And when you say it doesn't work do you get an error?  If so please post error and screenshot.

**Comment by subhojit11** [comment]
You're correct. Idea came to my mind later, I need to create 3 separate series and to map each other. I believe it's not a bug.
