### ISSUE TITLE
Button: icon should have normal font-weight

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#2949]
## 1) Environment
- PrimeFaces version: 6.1 with Omega theme
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
Icon inside buttons/commandbuttons should have a normal font-weight.

## 3) Actual behavior
Icon has font-weight: bold. This worsens the look of some icons, especially on small buttons.

## 4) Steps to reproduce
See provided xhtml. The rendered result is:
![cattura](https://user-images.githubusercontent.com/18428155/32844074-bc79f63a-ca21-11e7-8e9d-8bba19ba6ce3.JPG)

## 5) Sample XHTML
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:p="http://primefaces.org/ui">
    <h:head id="head1">
		<title>Test</title>

		<style type="text/css">
			.normalWeight {
				font-weight: normal !important;
			}
		</style>
    </h:head>
    <h:body id="body1">

		<p:button icon="fa fa-trash-o"/>

		<p:button icon="fa fa-trash-o normalWeight"/>

	</h:body>
</html>
```

## 6) Sample bean
Not needed.

**Comment by melloware** [comment]
@mertsincan Thoughts?  To me these should not be bold?

**Comment by NicolaIsotta** [comment]
WIth Aristo the font-weight seems ok but the `overflow: hidden;` on `.ui-icon` cuts a part of the icon:
![cattura](https://user-images.githubusercontent.com/18428155/32845437-f821cc96-ca24-11e7-9064-13f5681adc3b.JPG)

**Comment by melloware** [comment]
I reported the Omega issue in the forum:  https://forum.primefaces.org/viewtopic.php?f=40&t=53236

**Comment by onursenture** [comment]
We reviewed the case as PrimeTek design team, and yes, these icons should definitely have standard font-weight, not bold. @mertsincan @melloware

**Comment by melloware** [comment]
PR submitted.
