### ISSUE TITLE
Pass rowKey in CellEditEvent

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#295]
CellEditEvent has the property rowIndex. 

Would it not be better to have a (additional) property getRowKey so that it can be used in the models getRowData(String rowKey) method.

Forum url: http://forum.primefaces.org/viewtopic.php?f=3&t=42051

Related post about converter in LazyDataModel / data components:

[url]http://forum.primefaces.org/viewtopic.php?f=3&t=42050[/url]

**Comment by cagataycivici** [comment]
Will reopen if more users demand it.

**Comment by elhaloui** [comment]
I have the same problem and i think it will be nice to have getRowKey  in CellEditEvent

**Comment by cagataycivici** [comment]
Ok, let's do it then.

**Comment by djmj** [comment]
Thank you :+1:
