### ISSUE TITLE
Add multipleDrag attribute to Tree

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#2950]
When enabled, the selected multiple nodes can be dragged from a tree to another tree.

**Comment by koan00** [comment]
Appears to break parsing in IE11
![line number](https://user-images.githubusercontent.com/7327133/32961467-a4338dc2-cb96-11e7-9415-ab047c931d43.gif)
![console](https://user-images.githubusercontent.com/7327133/32961468-a442eed4-cb96-11e7-964b-9e1a94480cca.gif)

. Chrome and Firefox work fine.

**Comment by mertsincan** [comment]
Thanks a lot! I'll fix it.

**Comment by koan00** [comment]
I'll submit a PR shortly if you don't mind? I need the practice :)

**Comment by mertsincan** [comment]
Thanks a lot, @koan00 ;)
