### ISSUE TITLE
UITree: add support for Pre and PostValidateEvent

### ISSUE THREAD

**Issue by mmariotti** [primefaces/primefaces#2956]
Hello,
I'm trying to listen to Pre/PostValidateEvent on UITree without success.
As you can see from the next snippet, events are not published by processValidators():

```
@Override
public void processValidators(FacesContext context) {
    if(!isRendered()) {
        return;
    }
    
    pushComponentToEL(context, this);
    processNodes(context, PhaseId.PROCESS_VALIDATIONS);
    validateSelection(context);
    popComponentFromEL(context);
}
```

Instead, this should be:

```
@Override
public void processValidators(FacesContext context) {
    if(!isRendered()) {
        return;
    }
    
    pushComponentToEL(context, this);
    
    Application application = context.getApplication();
    application.publishEvent(context, PreValidateEvent.class, this);
            
    processNodes(context, PhaseId.PROCESS_VALIDATIONS);
    validateSelection(context);
    
    application.publishEvent(context, PostValidateEvent.class, this);
    
    popComponentFromEL(context);
}
```

Thank you

## 1) Environment
- PrimeFaces version: 6.1.8
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: Wildfly 10.1.0
- Affected browsers: N/A

## 2) Expected behavior
UITree.processValidators should publish PreValidateEvent and PostValidateEvent

## 3) Actual behavior
UITree.processValidators doesn't publish PreValidateEvent and PostValidateEvent

## 4) Steps to reproduce
N/A

## 5) Sample XHTML
N/A

## 6) Sample bean
N/A

**Comment by tandraschko** [comment]
I don't think it was ever implemented in UITree ;) Feel free to provide a PR.

**Comment by melloware** [comment]
PR submitted.

**Comment by mmariotti** [comment]
I'm sorry, yesterday i had a meeting all day long. Next time I'll submit a PR myself, I promise :)
Thank you guys

**Comment by melloware** [comment]
No worries I appreciate at least you post a solution rather than just complaining something doesn't work!
