### ISSUE TITLE
SelectCheckboxMenu selected items not consistent with checkboxes in Firefox Quantum

### ISSUE THREAD

**Issue by xxiFear** [primefaces/primefaces#2959]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? 
->Does not work on Primefaces Showcase
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 8.5.23
- Affected browsers: Firefox Quantum

## 2) Expected behavior
Loading a page with a selectCheckboxMenu shows all items and - if selected items are prefilled - the checked checkbox.

## 3) Actual behavior
Prefilled selected items do get added as label to a "multi" checkboxMenu but regardless of the checkboxMenu mode (single, multi...) the checkboxes in the dropdown menu are not consistent. Instead, they show the last state before reloading the page. (Seems like they get chached somehow)

## 4) Steps to reproduce
1. Open CheckboxMenu ShowCase
2. Open Dropdown on Multiple checkboxMenu and select any item
3. Reload page and check selected items. The selected item is still selected but not consistent with the selectedItems list, which is emtpy

![showcase_checkboxmenu](https://user-images.githubusercontent.com/23106855/32898396-53625ecc-cae8-11e7-9f81-67195b168939.png)

## 5) Sample XHTML
_____

## 6) Sample bean
_____

**Comment by melloware** [comment]
Is this only in Firefox or does it happen in Chrome/IE/Edge?

**Comment by xxiFear** [comment]
Only in Firefox Quantum (57.x)
Just tried with Chrome, IE and Edge and it works there.

**Comment by jxmai** [comment]
Firefox cache the input by default for some reason so you probably need to set `Cache-Control: no-store` to avoid this problem.

If you press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> in Firefox quantum, the checkbox value won't persist.

**Comment by melloware** [comment]
I use OmniFaces cachcontrol filter...

http://omnifaces.org/

```xml
	<!-- No Cache Filter -->
	<filter>
		<filter-name>NoCacheFilter</filter-name>
		<filter-class>org.omnifaces.filter.CacheControlFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>NoCacheFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
```

**Comment by jxmai** [comment]
Good resources :+1: . I was always using a custom servlet response to write the flag back. Looks like omnifaces can do the job without any code overhead.

**Comment by tandraschko** [comment]
I just use this in my templates:

`        <h:head>
            <f:facet name="first">
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
                <meta http-equiv="pragma" content="no-cache"/>
                <meta http-equiv="cache-control" content="no-cache"/>
                <meta http-equiv="expires" content="0"/>
`

**Comment by melloware** [comment]
I actually use a bunch of Omnifaces filters that are awesome...

```xml
	<!-- UTF-8 Encoding filter over the default ISO-8859-1. -->
	<filter>
		<filter-name>CharacterEncodingFilter</filter-name>
		<filter-class>org.omnifaces.filter.CharacterEncodingFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>CharacterEncodingFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<!-- Apply GZIP compression on responses whenever applicable -->
	<filter>
		<filter-name>GzipResponseFilter</filter-name>
		<filter-class>org.omnifaces.filter.GzipResponseFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>GzipResponseFilter</filter-name>
		<servlet-name>Faces Servlet</servlet-name>
	</filter-mapping>

	<!-- No Cache Filter -->
	<filter>
		<filter-name>NoCacheFilter</filter-name>
		<filter-class>org.omnifaces.filter.CacheControlFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>NoCacheFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<!-- adds an exception handler to unwrap exceptions in EL and regular page requests -->
	<filter>
		<filter-name>FacesExceptionFilter</filter-name>
		<filter-class>org.omnifaces.filter.FacesExceptionFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>FacesExceptionFilter</filter-name>
		<servlet-name>Faces Servlet</servlet-name>
	</filter-mapping>
```

**Comment by tandraschko** [comment]
Just my thoughts:
- no-cache in the header performs a little bit better as there is no fitler required each request
- gzip is already available in all servers, no need to include extra code here

**Comment by jxmai** [comment]
So, this issue is on showcase for not setting the flag properly I guess. 

On the other hand, Firefox's caching system is a bit aggressive compared to other major browsers IMHO as they have been tried to do a lot of things to boost the performance in the latest release.

**Comment by melloware** [comment]
Yep @xxiFear  you can close this issue I have opened an issue on the Showcase to set the caching.

**Comment by xxiFear** [comment]
@melloware, @jxmai, @tandraschko Thank you very much for the help.

**Comment by xxiFear** [comment]
I just tried your suggestion @tandraschko and it somehow still does not work in Firefox. Apart from that, it says "wrong attribute value" on all three meta tags.

**Comment by tandraschko** [comment]
Yep, i see. Seems like these tags are not 100% safe to use and a fitler is the only 100% working approach.

**Comment by xxiFear** [comment]
@melloware You should change your showcase issue then.

**Comment by melloware** [comment]
Agreed. I will kill my PR and submit a different one.
