### ISSUE TITLE
Chips: Unselect Ajax Event Not Working

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#2962]
A regression was introduced with this commit: https://github.com/primefaces/primefaces/commit/4f10ef6a30bfbb2170f3dd2bd77933831778d5db#diff-755582cad94eb934a0081b32c52c848f

When the style was changed from "autocomplete" to "chips" it broke the unselect event.

Submitting a PR to fix.

**Comment by melloware** [comment]
PR submitted.

**Comment by matsandreassen** [comment]
Sweet! That was quick. Here's hoping it'll be included in 6.1.x.

**Comment by melloware** [comment]
@mertsincan can you backport this to Elite 6.1.9?

**Comment by mertsincan** [comment]
Of course! Thanks a lot @melloware;)
