### ISSUE TITLE
Datatable: Footer defined with footerText is not styled with Omega

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#2966]
## 1) Environment
- PrimeFaces version: Showcase
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
The footer created by `p:column footerText` should look like the header created by `p:column headerText`.

## 3) Actual behavior
If the theme is Omega, the footer defined with `p:column footerText` is not properly styled, the footer row looks just like a table row.

## 4) Steps to reproduce
Open https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml , choose Omega theme if it's not already active. Then try the other themes.

## 5) Sample XHTML
Showcase

## 6) Sample bean
Not needed

**Comment by NicolaIsotta** [comment]
I think adding the selector `.ui-datatable tfoot td.ui-state-default` to this css rule should fix the issue
https://github.com/primefaces/primefaces/blob/bd88ec91557ea573fbf345c86f2124d61ee3aa2b/src/main/resources/META-INF/resources/primefaces-omega/theme.css#L628-L631
Left is with the rule, right is without:
![cattura](https://user-images.githubusercontent.com/18428155/32953759-799f8afa-cbb1-11e7-9492-acd2f71910d0.JPG)

**Comment by melloware** [comment]
@NicolaIsotta can you review my PR?
