### ISSUE TITLE
Ensure correct resources ordering

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2975]
Following this discussion https://github.com/primefaces/primefaces/commit/9c65354cce5e22545d702f879f5f50cfb40a7d93#commitcomment-25488348

Basically, some components have `jquery-plugins` _(I'll abbreviate this by JQP)_ has a dependency and other don't. If the first non JQP component is loaded first, `jquery-plugins` will be loaded in last then, after core.js/component.js by the JQP components. The result of the html becomes like this:

![32989607-e693df62-cd19-11e7-87b5-4477ae509331](https://user-images.githubusercontent.com/7521311/33019625-6b89a710-cdfb-11e7-831f-e458d9e7c5a3.png)
 And as a consequence, javascript errors such as:

![image](https://user-images.githubusercontent.com/7521311/33043620-56ed5dba-ce46-11e7-9014-354a5fbcaff8.png)

Several solutions have been mentionned:
- Should we add jquery-plugins to every components?
  - Modifying xml component definition file?
  - Tweaking maven-jsf-plugin to make sure JQP is loaded right after `jquery.js`?

IMO, none of these are good enough. It looks like BootsFaces have faced this issue, and they create a listener for that: [AddResourcesListener](https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/listeners/AddResourcesListener.java)

I think we should do something similar, actually the idea is to make sure that `jquery-plugins` is loaded right after `jquery.js` and before `core/component.js`¨. Would it be a reasonable idea to sort resources in `HeadRenderer` right before they get encoded?

The problem can be easily reproduced:
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>

<h:body>
	<p:inputText />
	<p:selectOneMenu />
</h:body>
</html>
```

**Comment by melloware** [comment]
I like the ResourceListener option....

**Comment by Rapster** [comment]
I don't know, I have no preferences so far, but it looks like HeadRenderer manage the resources writing

**Comment by tandraschko** [comment]
I have wifi today, so i have some minutes for important stuff ;)
A big -1 for something like the addResourceListener
The only solution for me is this:
- All components, which uses core.js must also use jquery plugins. Otherwise the order is incorrect and actually core.js depends on some plugins like browser, caret, ..
- Lets also check if we can reduce the jquery plugins a little bit and move it to the used componets (if used by one specific component only)

**Comment by jxmai** [comment]
> All components, which uses core.js must also use jquery plugins. Otherwise the order is incorrect and actually core.js depends on some plugins like browser, caret, ..

Probably only need to scan through the xml files and add resources then

**Comment by jxmai** [comment]
I scanned through the entire repo to add jquery-plugin resoruces if `core.js` presents. We need to do this work anyway. PR: #2984

**Comment by cagataycivici** [comment]
Why in the following case, components.js is loaded after jquery-ui plugins then.

view-source:https://www.primefaces.org/showcase/ui/button/button.xhtml

**Comment by cagataycivici** [comment]
Also we need to make sure 6.2 does not break the premium templates.

**Comment by OBreidenbach** [comment]
Components.js is loaded after jquery-ui plugins because button.xhtml uses template.xhtml.
In template.xhtml <p:remoteCommand .../> is before the include which is used by button.xhtml.
As the definition for remoteComand is correct. Everything is working fine.

Just put any component with missing jquery-ui plugin before the remoteCommand and you will see the failure.

**Comment by Rapster** [comment]
Thanks @OBreidenbach I was wondering why JQP was loaded at all but you just gave the answer ;-)

**Comment by Rapster** [comment]
@cagataycivici PF 6.2 breaks Premium templates already, I created a ticket here https://github.com/primefaces/layouts/issues/150

**Comment by tandraschko** [comment]
Cagatay, the PR should fix it and is fine. Dont worry, will take care of it in 1,5 weeks.
