### ISSUE TITLE
[Regression] Tree: Context Menu select node is not working properly

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#2978]
## 1) Environment
- PrimeFaces version: 6.2 Snapshot
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Doesn't matter
- Affected browsers: all

## 2) Expected behavior

Using showcase, right click context menu and click delete node, the selected node should be deleted.

## 3) Actual behavior

**Null pointer exception** 

## 4) Steps to reproduce

1. Using the latest showcase, go to http://localhost:8080/showcase/ui/data/tree/contextMenu.xhtml 

2. Right click a node to pop up a context menu:

![snapshot1](https://user-images.githubusercontent.com/10467831/33055876-dd1cad7c-ce47-11e7-851b-fcfd72e4864b.png)

3. click delete

![snapshot1](https://user-images.githubusercontent.com/10467831/33055890-eeafff9e-ce47-11e7-8543-7e12852d45d4.png)

## 5) Sample XHTML

See showcase

## 6) Sample bean

See showcase

## 7) Thoughts

@mertsincan Please mark this issue as **high priority** as I noticed you did some changes to `tree.js` recently. We definitely don't want to see this regression included in PF 6.2 :) . 

https://github.com/primefaces/primefaces/commits/master/src/main/resources/META-INF/resources/primefaces/tree/tree.js

**Comment by mertsincan** [comment]
I've replicated it with 6.2-SNAPSHOT. it works fine for 6.1.x elite versions. Please see your PR; https://github.com/primefaces/primefaces/commit/cd8cccb30011459780918588327d64be8e595efc#diff-3cc01523b05bd1fb5ffa60e642384c14

When you add '> span:not(.ui-tree-toggler)', you need to change ```var nodeContent = $(this);```` . Please try this issue after removing your change.

**Comment by jxmai** [comment]
Alright, so my previous PR was working *by accident*... Thanks Mert for quickly addressing this problem. I can confirm this issue has gone.

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for the update!
