### ISSUE TITLE
SelectOneRadio: with custom layout ignores tag attribute "styleClass"

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#2981]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version?
No, Version: origin/master from 11/21/2017
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No, Version: origin/master from 11/21/2017
- Application server + version:
Tomcat 7
- Affected browsers:
All browsers

## 2) Expected behavior
When specifying tag attribute "styleClass" an p:selectOneRadio tag with layout="custom" the rendered DIV element with class "ui-helper-hidden" should should render the specified style class(es).

## 3) Actual behavior
DIV element has only style class "ui-helper-hidden" but not the specified style class(es)

## 4) Steps to reproduce
put a p:selectOneRadio with layout="custom" and styleClass="xxx" into your page

## 5) Sample XHTML
see 4.

## 6) Sample bean
no bean needed

**Comment by melloware** [comment]
Yep. I see it.  I will fix it.

**Comment by melloware** [comment]
I think you mean a SPAN not a DIV right?  Can you review this PR:  https://github.com/primefaces/primefaces/pull/2983
