### ISSUE TITLE
Timeline updater works only if widgetvar is set

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#2987]
## 1) Environment
- PrimeFaces version: 6.1.8
- Does it work on the newest released PrimeFaces version? Version? No, 6.1.8
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Payara 471
- Affected browsers: Chrome and Firefox tested

## 2) Expected behavior

Timeline updater update the timeline also if no widgetvar is set

## 3) Actual behavior

Timeline update works only if widgetvar is set

## 4) Steps to reproduce

it is already descripted in github by Primefaces Extensions:
[https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/359](url)

take also a look at the Stackoverflow article:
[https://stackoverflow.com/questions/32562998/jsf-primefaces-extensions-timeline-how-to-update-a-timeline-via-ajax](url)

## 5) Sample XHTML
This al is inside of tabview. Because of this i cannot set widgetvar because of other bug!

```xhtml
<p:timeline id="stampstimeline"
                        value="#{editIncidentBean.stampsTimelineModel}" var="se" 
                        height="250px"
                        zoomable="true"
                        showNavigation="true"
                        start="#{editIncidentBean.timeLineStart}"
                        end="#{editIncidentBean.timeLineEnd}"
                        timeZone="#{envBean.timeZoneString}"
                        dropActiveStyleClass="ui-state-highlight" 
                        dropHoverStyleClass="ui-state-hover"
                        editable="true"
                        >
                <p:panelGrid layout="grid" columns="1" styleClass="ui-noborder">
                    <p:outputLabel value="#{editIncidentBean.getTimeStampEventTitle(se)}" />
                    <p:outputLabel value="#{se.date}">
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
                    </p:outputLabel>
                </p:panelGrid>
                <p:ajax event="drop" listener="#{editIncidentBean.onTimestampDrop}" global="false" 
                        update="eventsList" />
            </p:timeline>
            <p:dataGrid id="eventsList" value="#{editIncidentBean.availableTimestamps}" 
                        var="ate" emptyMessage="Keine Events mehr verfügbar"
                        columns="2">
                <f:facet name="header">
                    Verfügbare Events
                </f:facet>
                <p:panel id="eventBox" style="z-index:9999; cursor:move;width: 200px;" 
                         styleClass="ui-state-default">
                    <p:outputLabel value="#{editIncidentBean.getTimeStampEventTitle(ate)}" style="color: white;" />
                </p:panel>
                <p:draggable for="eventBox" revert="true" helper="clone" cursor="move"
                             opacity="0.7"/>
            </p:dataGrid>
```

## 6) Sample bean
```java
public void onTimestampDrop(TimelineDragDropEvent e) {
        if (e != null && e.getData() instanceof TimestampEvent) {
            TimestampEvent tev = (TimestampEvent) e.getData();
            tev.setDate(e.getStartDate());
            
            this.availableTimestamps.removeIf(at -> at.getStampType() == tev.getStampType());
            
            TimelineEvent te = new TimelineEvent(tev, e.getStartDate());
            TimelineUpdater tu = TimelineUpdater.getCurrentInstance("editform:edittab:stampstimeline");
            
            // add a new event
            stampsTimelineModel.add(te, tu);
        }
        
    }
```

**Comment by melloware** [comment]
Original Ticket:  https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/359

From looking at the code at first glance there is nothing I can find obviously wrong so this must be a subtle bug.  

I don't understand why can't you set the widgetVar on the Timeline?

**Comment by markusg80** [comment]
Because the Timeline is inside a tabview.

See #1878 and #2278

#2278 is fixed for 6.2 but still not backportet to 6.1.9

**Comment by melloware** [comment]
Thanks. Those tickets help.

**Comment by markusg80** [comment]
And all this make also the Timeline Updater useless for me!

**Comment by jxmai** [comment]
I guess #2278 is missing the commit attached as Thomas forgot to put the `#` before the issue number . I just paste that patch commit here: https://github.com/primefaces/primefaces/commit/7b197a9275127ea58613cd131288dba9d92328a0

**Comment by melloware** [comment]
Yep so it seems like this issue is fixed in 6.2 and can be closed.  If you are a Pro or Elite member you can lobby @mertsincan to backport this whole thing to 6.1.10.

**Comment by markusg80** [comment]
@mertsincan i‘m Elite user and please backport #2278 for Version 6.1.10! Because Timeline has many bugs in 6.1

**Comment by markusg80** [comment]
@Melloware Bug #2278 is fixef, but im not sure if this bug is fixed too! Because there is still the need to set widgetvar for Timeline updater to get working

**Comment by melloware** [comment]
@markusg80 can you test with PF 6.2-SNAPSHOT that will tell us for sure whether the issue still exists or not?

**Comment by markusg80** [comment]
Ok! First time i compile primefaces from snapshot! I eill try now tomorrow if it works

**Comment by markusg80** [comment]
With 6.2 SNAPSHOT from yesterday i get in the browser console following error message and timeline not appears:
Uncaught TypeError: Cannot read property 'render' of undefined
    at Class.render (timeline.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7573)
    at core.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:1961
    at Object.invokeDeferredRenders (core.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:589)
    at Class.postShow (components.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7444)
    at HTMLDivElement.<anonymous> (components.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:7426)
    at done (jquery-plugins.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:10907)
    at HTMLDivElement.cleanup (jquery-plugins.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:10902)
    at HTMLDivElement.d.complete (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:3)
    at i (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:2)
    at Object.fireWith [as resolveWith] (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:2)

This is inside this function:
```javascript
/**
     * Force render the timeline component 
     * 
     * @param animate flag to animate the render action (optional)
     */
    render: function (animate) {
        this.instance.render({'animate': animate});
    },
```

**Comment by melloware** [comment]
Hmmm can you try this...
1. Check out the Showcase project https://github.com/primefaces/showcase

2. Run that project with "mvn clean jetty:run"

3. Navigate to http://localhost:8080/showcase/ui/data/timeline/basic.xhtml

For me the showcase running all the Timeline examples with 6.2 is working fine.  So maybe you could narrow the issue down further Can you create a small test sample reproducing your issue with the Test Git project?

Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem.

That will help us debug and fix your issue!

**Comment by markusg80** [comment]
Ok i will try this at my Weekend ;-)

**Comment by markusg80** [comment]
@melloware  
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/1503442/primefaces-test.zip)
So now i was able with showcase to narrow down the problem. The Problem with 6.2 SNAPSHOT release happens when the timeline is placed inside a dialog. So in the example project i take the dialog modal example and then  i placed the timeline inside of the modal dialog and the timeline no longer appears and in the browser the error message i wrote above 2 days ago. You can run the attached test project and then press the button for modal dialog and after you can see errors in the browser log.

Happy fixing :-)

**Comment by melloware** [comment]
Thanks for the test case, I fixed it with this PR and I think it is the correct fix but I will let the PF team review to see if it is correct.

**Comment by tandraschko** [comment]
I think it should be fixed - If everything works fine, its ok for me.
