### ISSUE TITLE
update="@form" with ajax sort and page event distorts the datatable

### ISSUE THREAD

**Issue by vinitkishore** [primefaces/primefaces#2999]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
datatable should retain the style after ajax update
...

## 3) Actual behavior
The datatable is distorted where all the applied style is missing
..

## 4) Steps to reproduce

1. Add following code to datatable
<p:ajax event="sort" update="@form"></p:ajax>
<p:ajax event="page" update="@form"></p:ajax>

2. Once data table is loaded, sort the datatable by clicking on any sortable column.

## 5) Sample XHTML
<p:ajax event="sort" update="@form"></p:ajax>
<p:ajax event="page" update="@form"></p:ajax>
..

## 6) Sample bean

..

**Comment by melloware** [comment]
Don't update update="@form".  why do you need to update the whole form on AJAX sort without even calling an ActionListener?  You are basically wiping the whole table out by repainting the entire form.  What exactly is your use case of the problem you are trying to solve.

Because right now PF is working correctly if you update="@form" you are destroying the entire form including the datatable.

**Comment by jxmai** [comment]
> datatable should retain the style after ajax update

Agree with melloware. If your style is somehow dynamically applied externally by js on page load, your expectation is invalid. What update does briefly  is to wipe the target element by one of the functions in `core.js` and recall widget init. If you need to retain the style, 1. you need to persist the style by renderer (can be achieved by styleclass=#{el}) 2. apply the style in js render function (extend widget function if you could do that. It may not success without tweaking PF codebase)

---

IMHO, your usage may be invalid in the first place. Anyway, this issue can be closed.
