### ISSUE TITLE
Primefaces roadmap

### ISSUE THREAD

**Issue by bernarddcosta** [primefaces/primefaces#3000]
Our team is evaluating the possibility to use primefaces .
However, we have seen that a similar framework Richfaces reached end of life in 2016.
We wanted to make an informed decision and hence this request to understand your future roadmap.

**Comment by tandraschko** [comment]
This is a issue tracker, not a forum ;)
However, we will maintain it the next years.
Not sure if there are already new features planned for the next version but you can e.g. sponsor new features all the time.
As you can see, we also added many features for 6.2.
Note: im not a member of PrimeTek, just doing it open source here. There are also issues trackers for PRO users.

**Comment by melloware** [comment]
I have been working with PF since 2012.  The library is actively maintained and constantly updated and I have over 20 in production applications using PF.  Plus they offer PRO support to guarantee if you have a bug you want fixed they respond within 24 hours.
