### ISSUE TITLE
DataTable:  Lazy+virtualScroll leads to duplicate first rows 

### ISSUE THREAD

**Issue by awenger63** [primefaces/primefaces#3002]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? No Version? 6.1
- Does it work on the newest sources in GitHub? no test today
- Application server + version: GlassfishServer 4.1 and Tomcat 8.0.27
- Affected browsers: Chrome, FireFox, IE

## 2) Expected behavior
No duplicate first row in first render (scrollRows="50" ==> 100 lines = 2 x 50 !)
...

## 3) Actual behavior
First scrollRows are duplicate in first render, after scrooling they disapear ...
..

## 4) Steps to reproduce
War file is not supported, hope this zip file contain what you need.

[primefaces-test-1.0-SNAPSHOT.zip](https://github.com/primefaces/primefaces/files/1505375/primefaces-test-1.0-SNAPSHOT.zip)

## 5) Sample XHTML

.. see zip file

## 6) Sample bean

.. see zip file

Thanks you for your analyse and suggest a solution.

**Comment by awenger63** [comment]
Hi, if zip file cannot be use to reproduce, you can use showcase lazy code [https://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml](url) and replace : 

`
<p:dataTable var="car" value="#{dtLazyView.lazyModel}" paginator="true" rows="10"                 paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"                 rowsPerPageTemplate="5,10,15" selectionMode="single" selection="#{dtLazyView.selectedCar}" id="carTable" lazy="true">
`

by something like this  ( Change paginator to virtualScrollable ) :

`<p:dataTable var="car" value="#{dtLazyView.lazyModel}"
                                          scrollable="true" scrollHeight="500" scrollWidth="100%" reflow="true" 
                                     sortMode="multiple" virtualScroll="true" scrollRows="50" lazy="true" liveScroll="true"
                                    selectionMode="single" selection="#{dtLazyView.selectedCar}" id="carTable" lazy="true">`

Hope this can help yout to reproduce.

**Comment by melloware** [comment]
I can't reproduce with the Lazy showcase running the latest 6.2-SNAPSHOT.

I used the exact syntax below the and first row is not duplicated for me?

```xml
<p:dataTable var="car"
 value="#{dtLazyView.lazyModel}" 
 virtualScroll="true" 
 liveScroll="true" 
 scrollRows="10"
 scrollable="true" 
 scrollHeight="500"
 scrollWidth="100%"
 selectionMode="single" 
 selection="#{dtLazyView.selectedCar}" 
 id="carTable" 
 lazy="true">
```

**Comment by awenger63** [comment]
And with the zip file project primefaces-test in 6.2 ?

**Comment by melloware** [comment]
I will try the zip next sorry.  I just did your showcase example because I had it open.

**Comment by melloware** [comment]
Hey in your zip you included only the compiled code.  I need the whole project so I can run "mvn clean jetty:run".   Include the pom.xml and the /src folder but do not include the /target folder.

**Comment by awenger63** [comment]
Sorry, it's the first time I post a project template. Your rigth, without source code it's could be difficult to analyse the issue ....
Look at this and tell me  : 
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/1517945/primefaces-test-master.zip)

**Comment by melloware** [comment]
OK tested on..

PF6.1 with Chrome 62, Firefox 67, MS Edge no issue with duplicate first row

PF6.2-SNAPSHOT with Chrome 62, Firefox 67, MS Edge no issue with duplicate first row

I can't reproduce your issue.  What browser are you using?  Have you hit CTRL+F5 to force Javascript and CSS reload?

**Comment by awenger63** [comment]
I tell information on header issue :
    PrimeFaces version: 6.1
    Affected browsers: Chrome , FireFox , IE

Version is Chrome 62.0.3202.94, FireFox Quantum 57
To see the issue, you must scroll slowly : you have the fisrt 50 rows and then you have another time the 50 first rows before load lazy data fire and after your have the 50 next (load fire). If you go back, every thing all right after. look at this screen shot :
![image](https://user-images.githubusercontent.com/16153617/33434377-654dc1ba-d5df-11e7-99c2-5c2365231c0a.png)

**Comment by melloware** [comment]
AHHH now I see it. Your description was confusing me what I was supposed to be looking for.   I can confirm your test zip shows this issue in 6.1 and 6.2-SNAPSHOT.

**Comment by JeeDevUser** [comment]
A detailed explanation of what causes the problem  (along with solution which I suggest) can be seen here:
https://github.com/primefaces/primefaces/issues/5230
At least,  additional verification must be done in the problematic if() statement, though I personally don't see any reason for it to be in the source code.

**Comment by mertsincan** [comment]
Hi @JeeDevUser,

Could you please create new ticket and attach a sample maven project for us to replicate?
