### ISSUE TITLE
ContextMenu: on DataTable not really selected row when right click

### ISSUE THREAD

**Issue by awenger63** [primefaces/primefaces#3003]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? no Version? 6.1
[https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml](url)

## 2) Expected behavior
Right click for contextMenu must change selected row to view correct data
...

## 3) Actual behavior
p:contextMenu not change selected row, in some case, data used are those of the previous row.
..

## 4) Steps to reproduce
go to show case : https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

-  selected one line (left click)
-  go to another on open context menu (right click) => it selected the new row
- press space bar => the row selected change !!!!
- select "view", you can see data NOT corresponding at the row where the menu is (KO ?)

.. 

## 5) Sample XHTML
https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

..

## 6) Sample bean
https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

..

**Comment by melloware** [comment]
I have replicated your issue but why are you pressing the SPACE BAR?   When you right click something that should be the action.  Once you have pressed SPACE BAR you are no longer in the Right Click context?

**Comment by jxmai** [comment]
Looks like a bad behavior from user POV. This is the default html behavior that space bar will retrigger click event as a result of recalling 

https://github.com/primefaces/primefaces/blob/f242f4bfbacca69c0afd80ef79764d30d3ae094b/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L1581


If you look at the spec: https://www.w3.org/TR/WCAG20-TECHS/SCR35

> The objective of this technique is to demonstrate how to invoke a scripting function in a way that is keyboard accessible by attaching it to a keyboard-accessible control. 

Also found some related post: 

https://stackoverflow.com/questions/27878940/spacebar-triggering-click-event-on-checkbox

---

Since the function named `onRowClick`, invoking the function on space bar pressed does not seem to make sense.


I am raising a patch that can address this problem. @melloware Please let me know what you think

**Comment by melloware** [comment]
Looks good to me i added one comment.  I just don't know if selecting rows by spacebar is also intentional for complete keyboard usage or accessibility?

**Comment by jxmai** [comment]
> complete keyboard usage or accessibility

That's a dilemma.  Indeed it could break the keyboard accessibility . I guess we have to do something more complex (check if user previously invoke context menu and decide the next step)

**Comment by awenger63** [comment]
@melloware, we use space bar like a 'preview' or preselect before choise a sub menu (it updated one panel), also is it possible to work quikly with two hand, one on the keyboard, one on the mouse ! => one click rigth, one space bar, one click left on the correct sub menu ;-)
@jxmai it's that, user invoke context menu before use space bar, but he use right clik to do that and not left click (see issues title, row is not selected by rigth click) if yes, the row will be selected before render context menu and every thing will be OK. In fact, it's what the user see => row's on selected color but not really selected ! I test different solution without succes : https://stackoverflow.com/questions/46948842/how-set-row-selected-with-pcontextmenu-on-pdatatable
Hope this can help you

**Comment by jxmai** [comment]
@melloware @awenger63   found out the root problem (The highlight does not actually focus a row on right click). Please review :)

**Comment by melloware** [comment]
I think this issue might be similar?  https://github.com/primefaces/primefaces/issues/2604

**Comment by jxmai** [comment]
They are related :+1: 

There is no `assignFocusesRow` on right click at the moment, so by

> Compare this to the result of left-then-right clicking

Without triggering `focus` by the function below


```js
assignFocusedRow: function(row) {
        this._super(row);

        if(!row.parent().attr('tabindex')) {
            this.frozenTbody.trigger('focus');
        }
    },
```

User will get faulty behavior.

**Comment by melloware** [comment]
Nice fixed 2 tickets with 1 fix.

**Comment by kukel** [comment]
@melloware: Please check the same for the treetable

**Comment by jxmai** [comment]
@kukel treetable does not support keyboard accessibility at the moment so there is no assign focus in treetable at all

To test it out, you can compare the following two pages: 

`treetable`:

 https://www.primefaces.org/showcase/ui/data/treetable/contextMenu.xhtml

`datatable`:

https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

and then follow the steps to replicate by awenger63

> selected one line (left click)

> go to another on open context menu (right click) => it selected the new row

> press space bar => the row selected change !!!!

> select "view", you can see data NOT corresponding at the row where the menu is (KO ?)

**Comment by mohdGitHub** [comment]
I have tried primefaces 6.2 but i found it's the same

**Comment by jxmai** [comment]
@mohdGitHub There is a subtle difference. If you go to https://www.primefaces.org/showcase/ui/data/treetable/contextMenu.xhtml, left click / right click and space, you will notice that the page scrolls since the focus is not on the treetable.
