### ISSUE TITLE
Add dropCopyNode attribute to Tree

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3004]
When enabled, the copy of the selected nodes can be dropped from a tree to another tree using Shift key.

**Comment by melloware** [comment]
@mertsincan the build is currently broken from this latest check in..

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project primefaces: Compilation failure
[ERROR] /C:/Dev/github/primefaces-melloware/src/main/java/org/primefaces/component/tree/TreeRenderer.java:[287,43] cannot find symbol
[ERROR]   symbol:   method getDropMode()
[ERROR]   location: variable tree of type org.primefaces.component.tree.Tree
```

**Comment by jxmai** [comment]
The original method was `dropMode`, but it changed to `dropCopyNode` during the refactoring process. If we clean up the leftover, the build will succeed. #3016

**Comment by mertsincan** [comment]
Thanks a lot for PR, @jxmai ;)
