### ISSUE TITLE
Inplace: emptyLabel useless with configured label

### ISSUE THREAD

**Issue by Hamsterbau** [primefaces/primefaces#3005]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

## 1) Environment
- PrimeFaces version: 6.1.8
- Application server + version: Wildfly 11.0.0 (also with 10.1.0)
- Affected browsers: All

## 2) Expected behavior
emptyLabel will be used, if value of the underlying input field is empty (no matter if label is configured or not).

## 3) Actual behavior
If label is configured, emptyLabel will be ignored (see InplaceRenderer.java):
`if(label != null) { return label; }`

See also the bugreport with attached patch from 2012:
https://code.google.com/archive/p/primefaces/issues/4317

## 4) Steps to reproduce
Just use an p:inplace and configure label as well as emptyLabel.

## 5) Sample XHTML
`<p:inplace
   widgetVar="aliasWidget"
   label="#{myBean.alias}"
   emptyLabel="#{myBean.value}"
   editor="true">
      <p:inputText
         id="alias"
         label="MY_ALIAS"
         value="#{myBean.alias}">
      </p:inputText>
</p:inplace>`

## 6) Sample bean
`import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class MyBean implements Serializable {
    private String alias;

    public String getAlias() {
        return alias;
    }
    public void setAlias(String alias) {
        this.alias = alias;
    }
}
`

**Comment by melloware** [comment]
Thanks for reporting. PR submitted.

**Comment by tandraschko** [comment]
Thanks for the many PR's @jxmai @melloware ;) will take some days and will only apply bug fixes and small improvement, i think we need to release RC1 soon.
