### ISSUE TITLE
Exception-Handling not working when view-expired-exception triggers a second exception

### ISSUE THREAD

**Issue by jmichler** [primefaces/primefaces#301]
Hi,

I consider what I described over there:
http://forum.primefaces.org/viewtopic.php?f=3&t=42120&p=132565#p132565

as a bug in Primefaces. I was able to reproduce it also with 5.2.3

BR
Johannes

**Comment by tandraschko** [comment]
Not sure if it's a PF bug, maybe just a bad/not defined constellation ;)
In Mojarra, when a ViewExpired occurs, the ViewRoot isn't null. So likely the View is restored but the viewAction isn't called again. If i workaround this via creating a new ViewRoot, the viewAction won't be called, too. Don't know if this is defined somewhere but actually it doesn't matter for me.
Also your xhtml is not valid as f:metadata must be a child of f:view.

Propably it will work with MyFaces, don't know.

Solutions:
1) Init your bean with @PostConstruct
2) I added a dirty handling which will still log a WARN message.

**Comment by jmichler** [comment]
Thanks for the quick fix. Is there a chance to get this into 5.2.4?

BR
Johannes

**Comment by tandraschko** [comment]
done ;)
