### ISSUE TITLE
treeTable: colResize ajax problem under firefox

### ISSUE THREAD

**Issue by herbu123** [primefaces/primefaces#3014]
## 1) Environment
- PrimeFaces version: 6.1

## 3) Actual behavior
Error:
 INFO: java.lang.NumberFormatException:

issue described at:
https://forum.primefaces.org/viewtopic.php?f=3&t=53351&e=1&view=unread#unread

Regards,
herbu

**Comment by melloware** [comment]
I have confirmed this issue with Firefox 57 and it definitely returns decimal numbers instead of integers.  I will fix.

Apparently Firefox has started given those values as doubles like 855.75.  So my fix simply turns it into an int like 855.

**Comment by kukel** [comment]
@melloware : Any other places/components this needs changing? Would be bad if  6.2 is released and this pops up in more places.

**Comment by melloware** [comment]
@kukel You are right I just pushed another commit that fixes Datatable the exact same way.
