### ISSUE TITLE
Add onDrop attribute to Tree

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3017]
It is a MethodExpression and users can add a condition to drop a node from a tree to another tree into it.
```
public boolean onDrop(TreeDragDropInfo info)
```

Exp;
```
//xhtml
...
   <p:tree id="tree1" onDrop="#{treeBean.onDrop}" .../>

   <p:tree id="tree2" onDrop="#{treeBean.onDrop}" .../>
...

//bean
public boolean onDrop(TreeDragDropInfo info) {
        TreeNode[] draggedNodesArr = (TreeNode[]) info.getDragNodes();
        
        for(int i = 0; i < draggedNodesArr.length; i++) {
            /* no drop nodes if the dragged nodes contain a node whose data has Tree[1] 0.0.1 */
            if(draggedNodesArr[i].getData().equals("Tree[1] 0.0.1")) {
                return false;
            }
        }
        
        return true;
}
```

**Comment by Rapster** [comment]
Is "onDrop" or "onDropStart" would be a better and simpler name? First, I don't like the use of "controller" here as it is a very common keyword used developing MVC apps, it might confuse developers. Second, `onDragController` does not sound like a method expression but more like a managed bean (e.g a controller :wink:).

**Comment by mertsincan** [comment]
Thanks a lot for the feedback! I'll change it.
