### ISSUE TITLE
Add isDroppedNodeCopy method to TreeDragDropEvent to check copy/cut operation 

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3018]

**Comment by jxmai** [comment]
will fail checkstyle by looking at this: https://github.com/primefaces/primefaces/commit/ec532e09316a56611a96df4418923ceeb0d9c203#diff-d53ae837661e9a4a098e5b28e45043baR43

**Comment by mertsincan** [comment]
Fixed now.
