### ISSUE TITLE
Calendar: make the defaults value for time configurable

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#3022]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1.9
- Does it work on the newest released PrimeFaces version? Version? No, 6.1.9
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Wildfly 10
- Affected browsers: Firefox, Chrome, IE

## 2) Expected behavior
It is possible to set the default value for the time slider in the calendar component.

## 3) Actual behavior
Default values always '0'.

PR with fix will follow.

**Comment by OBreidenbach** [comment]
PR: https://github.com/primefaces/primefaces/pull/3023

**Comment by tandraschko** [comment]
-1
The default should be set with the "value" attribute
Or should we also add defaultValue to all other input components?

**Comment by melloware** [comment]
@OBreidenbach what is your use case where just setting a value="" to a date set to the hours minutes and seconds already not accomplish?

**Comment by OBreidenbach** [comment]
I only want to set the default value for the time not for the date. If I use the value attribute I do set date and time. 
You know, the field is not required. But if the user uses the calendar, I want to be polit and set an appropriate time. And this time is not midnight (0:00).
By the way, the jQuery component does already have this attributes for configuration. Why do not use them?

**Comment by melloware** [comment]
@OBreidenbach I can see that, especially if the component supports it.

**Comment by tandraschko** [comment]
Please provide more details why it should not be possible via the value attribute.

**Comment by OBreidenbach** [comment]
I did describe my use case. 
I want to offer a default time, but I must not offer a default date. I do not know, how I can do this by using the value attribute.
But may be I am missing something. So how can I provide a default time without providing the date part with the value attribute?
For the screenshot I did use my added code. It is just taken after opening the popup. The default time is set to the time sliders.
![defaulttimeincalendar](https://user-images.githubusercontent.com/11403755/33819415-98432402-de4a-11e7-9a7e-cce7cd986212.png)
The calendar field is not required. But if the user is picking the date, we think it should have a certain time.
But if the user does not like it, he can change it.

**Comment by OBreidenbach** [comment]
@tandraschko, do you need more information to include this change? What can I do to get this change included?

**Comment by tandraschko** [comment]
We won't apply new features till 6.2. So i will check it the next months probably.

**Comment by OBreidenbach** [comment]
@tandraschko, could you please have a new look at this ticket?
I want to set a default value for the time portion but must not set a default value for the date portion. 
I did not find any way to do so. So I added this new feature.
It would be great, if you could merge my PR: #3023

**Comment by tandraschko** [comment]
I will check it before the next release, so we have some time ;)

**Comment by natalicontguard** [comment]
Did you manage to solve it? I have the same requirement.

**Comment by melloware** [comment]
@natalicontguard Its fixed in the source of GitHub so you can build 6.3-SNAPSHOT yourself if you need the fix.
