### ISSUE TITLE
Can not enter Number in InputNumber when only typing...

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#3025]
Hello,

In the current Primefaces Build 6.2-SNAPSHOT i can not enter a value in range when minValue is set.

I have the following example

**FrontEnd:**
```
                                                    <div class="ui-g">
                                                        <div class="ui-g-12">
                                                            <p:inputNumber id="NumberTest"
                                                                           value="#{testControl.value}"
                                                                           styleClass="form-control 100Percent"
                                                                           required="true"
                                                                           decimalSeparator="."
                                                                           decimalPlaces="2"
                                                                           minValue="4.00"
                                                                           maxValue="600.00"
                                                            >
                                                            </p:inputNumber>
                                                        </div>
                                                    </div>

```

On Backend only this lines:

```
@SessionScoped
@Named(value="testControl")
public class TestController implements Serializable 
{
	private static final long serialVersionUID = -664880345709266446L;
        private BigDecimal value = null;
    public BigDecimal getValue() {
        return value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }
}

```

When i now want to enter 100.00 it will be corrected to 4 while i am typing instead of checking 
on form sending or after changing.

So no way to enter 100.00 in this field but it should be a valid value...

**Comment by melloware** [comment]
I have seen this too its because as you type "1" for "100" it says 1 is less than 4.00 and won't let you enter any data.  I didn't know if this was intentional or a bug.

**Comment by ssibitz** [comment]
I also can not delete the min-value from the field to enter "another" value.
It seems to be a bug because a minValue of 4 includes also 100 ...

**Comment by tandraschko** [comment]
Autonumeric js behaves weird here but this is known and i would not use min or max... But @mertsincan also just something the last weeks....

**Comment by tandraschko** [comment]
*changed, not just

**Comment by ssibitz** [comment]
So don't use min/max Value at the Moment is the best ?

**Comment by melloware** [comment]
@ssibitz I used max to great effect but I have stopped using min.

**Comment by melloware** [comment]
@ssibitz Unfortunately I think you can close this.

From the Autonumeric guide: http://autonumeric.org/#/guide

> Warning: If minimumValue is superior to 0, then you'll effectively prevent your users to entirely delete the content of their AutoNumeric-managed element

All of their examples show minValue=0 or lower like minvalue=-276.  Basically they are saying we can't use a positive number.

**Comment by ssibitz** [comment]
So when its not working right  - please remove it from the attributes (or set it to deprecated).

I think in a case that the user (including me) want to use the minValue/maxValue attribute on
an InputNumber he only want to be sure that the user can not enter values outside the range he entered.
The check must not be executed at runtime when he enteres the value, 
so the minValue/maxValue can be replaced with the following working solution for user and InputField:

```
                                                        <p:inputNumber id="Test"
                                                                       value="#{value.value}"
                                                                       required="true"
                                                                       placeholder="Please enter a number from 4 to 600"
                                                                       validatorMessage="You entered a value outside the range 4 - 600"
                                                                       decimalSeparator="."
                                                                       decimalPlaces="3"
                                                                       emptyValue="emtpy">
                                                                <f:validateDoubleRange minimum="4" maximum="600"/>
                                                        </p:inputNumber>

```

So I think the minValue/maxValue should be replaced with the general check from the JSF-Core
( xmlns:f="http://java.sun.com/jsf/core" )
would be the better way instead of using the wrong functionality of Autonumeric in that case:

**<f:validateDoubleRange minimum="4" maximum="600"/>**

Then Autonumeric can be used for the "General" Check and when the user submit's the form he
will get the validatorMessage. 

I tested it and this work's right all the time !

**Comment by melloware** [comment]
@ssibitz that is what I do too for min but the min and maxvalue on the component still have value.  Your solution requires a network round trip for JSF to do the validation.   A lot of my inputNumber's I know i don't want a negative number so I will do minValue="0" to prevent user from typing in a negative number providing a better user experience WITHOUT a network round trip.

Same with maxValue="24" for hours so prevent them from even typing 25 rather than finding out after an AJAX submit.

**Comment by tandraschko** [comment]
Will close it for now, we already had a talk about that in the past.
