### ISSUE TITLE
Datatable sortBy and sortOrder - column header issue

### ISSUE THREAD

**Issue by JHookDev** [primefaces/primefaces#3026]
## 1) Environment
- PrimeFaces version: 6.1.9
- Does it work on the newest released PrimeFaces version? Version? No, 6.1.9
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 8.5
- Affected browsers: Chrome

## 2) Expected behavior
When page is rendered the column header for the column specified in sortBy attribute should be highlighted. In addition the either up or down sort arrow in the header should indicate the sort direction as indicated with the sortOrder attribute.

## 3) Actual behavior
Column header is not highlighted, in addition both the up and down sort arrows are rendered.

## 4) Steps to reproduce
This can be reproduced using the sample below and PrimeFaces 6.1.9. The expected behavior does work in the 6.1.8 release.

## 5) Sample XHTML
<html lang="en" 
     xmlns="http://www.w3.org/1999/xhtml"
     xmlns:c="http://java.sun.com/jsp/jstl/core"
     xmlns:f="http://java.sun.com/jsf/core"
     xmlns:h="http://java.sun.com/jsf/html"
     xmlns:p="http://primefaces.org/ui">

	<h:head>
		
	</h:head>
	
	<h:body>
		<f:view>
			<h:form id="defaultColumnSortForm">
				<p:dataTable id="defaultSortDatatable" value="#{datatableBean.cars}" var="datatableRow" sortBy="#{datatableRow.year}" sortOrder="DESCENDING">
					<p:column sortBy="#{datatableRow.id}" id="idColumn" headerText="Id">
						<h:outputText id="carId" value="#{datatableRow.id}" />
					</p:column>
					<p:column sortBy="#{datatableRow.year}" id="yearColumn" headerText="Year">
						<h:outputText id="year" value="#{datatableRow.year}" />
					</p:column>
					<p:column sortBy="#{datatableRow.brand}" id="brandColumn" headerText="Brand">
						<h:outputText id="brand" value="#{datatableRow.brand}" />
					</p:column>
					<p:column sortBy="#{datatableRow.color}" id="colorColumn" headerText="Color">
						<h:outputText id="colorId" value="#{datatableRow.color}" />
					</p:column>
				</p:dataTable>
			</h:form>
		</f:view>
	</h:body>
</html>

## 6) Sample bean
```
@ManagedBean(name="datatableBean")
@ViewScoped
public class DatatableBean {

	private List<Car> cars;

	@PostConstruct
	public void init() {
		cars = new ArrayList<Car>();
		cars.add(new Car(1, 2007, "Pontiac", "Black"));
		cars.add(new Car(2, 2015, "Jeep", "Grey"));
		cars.add(new Car(3, 2008, "Buick", "Silver"));
		cars.add(new Car(4, 2011, "Toyota", "Green"));
	}
	
	public List<Car> getCars() {
		
		return cars;
	}

	public void setCars(List<Car> cars) {
		this.cars = cars;
	}
}
```
```
public class Car {

	private int id;
	private int year;
	private String brand;
	private String color;
	
	public Car() {
		super();
	}

	public Car(int id, int year, String brand, String color) {
		super();
		this.id = id;
		this.year = year;
		this.brand = brand;
		this.color = color;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}
}
```

**Comment by melloware** [comment]
@mertsincan regression issue between Elite 6.1.8 and 6.1.9?

https://github.com/primefaces/primefaces/issues/2932
