### ISSUE TITLE
ContextMenu: support search expressions

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primefaces#303]
It is nice to have support PFS selectors to contextmenu similar to other components such as tooltip,watermark etc.Then we can also apply contextmenu for multiple components.

**Comment by tandraschko** [comment]
What about a PR sudheer?

**Comment by tandraschko** [comment]
Currently not possible as we need to get the server side component.
I think it's possible if we do some major refactoring but i'm not sure if someone needs to attach one contextMenu to multiple components.
I would close it for now till someone really needs it.
