### ISSUE TITLE
get the inputTextNumber Jquery

### ISSUE THREAD

**Issue by sagksam** [primefaces/primefaces#3030]
I can't get the value of my inputTextNumber in JQuery.
I've tried this way but nothing is returned.
Can anyone help me?

                         <p:inputNumber class="valorCusto" id="valorCusto" value="#{produtoBean.produto.valorVenda}" symbolPosition="s" emptyValue="" minValue="0.00"  required="true" requiredMessage="O campo Valor Custo é obrigatório">
                            <p:message for="valorCusto"/>
                        </p:inputNumber>

  function calculaValorFinal(){
      
      var c = $('.valorCusto').val();
      console.log(c);
  }

**Comment by tandraschko** [comment]
Questions -> forum

**Comment by melloware** [comment]
Forum: https://forum.primefaces.org/viewforum.php?f=3
