### ISSUE TITLE
FileUpload: Issue with filenames containing semicolon or double quotes

### ISSUE THREAD

**Issue by dmytrofer** [primefaces/primefaces#3034]
Method NativeUploadedFile.resolveFilename splits by ';' and replaces '"' in filename param. It leads to problems with getting name of uploaded file.

## 1) Environment
- PrimeFaces version: 6.1.6

## 2) Expected behavior
All file names are processed correctly

## 3) Actual behavior
* Name **'File;Import.xlsx'** is extracted as **'File'**
* Name **'File"Import.xlsx'** is extracted as **'FileImport.xlsx'**

## 4) Steps to reproduce
1. Create a fileUpload component.
1. Add fileUploadListener.
1. Try to get name of file from FileUploadEvent.

## 5) Sample XHTML
```
  <p:fileUpload fileUploadListener="#{fileHandler.handleFileUpload}"/>
```

## 6) Sample bean
```
public void handleFileUpload(FileUploadEvent event) throws IOException {
        UploadedFile uploadedFile = event.getFile();
        System.out.println(uploadedFile.getFileName());
}
```

**Comment by jxmai** [comment]
semicolon is legal, but double quote is reserved in NTFS file paths. Please see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

> Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:

```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

**Comment by orange-buffalo** [comment]
@jxmai could you please elaborate why file upload component is bound to the NTFS file system? Both client and server could run on OSes with other files systems, for instance in ext3/4 double quote is a perfectly legal character in the file name.

**Comment by jxmai** [comment]
@orange-buffalo  Nevermind. The culprit is not about the fileSystem. It is about the following method

https://github.com/primefaces/primefaces/blob/102b4b93e80546b8b70650820eeb9ef258a07d71/src/main/java/org/primefaces/model/NativeUploadedFile.java#L91-L97


Sample input:

```
form-data; name="j_idt43:j_idt44"; filename="Test;123.txt"
```

Indeed, as dmytrofer says

> Method NativeUploadedFile.resolveFilename splits by ';' and replaces '"' in filename param. It leads to problems with getting name of uploaded file.

---

Thinking we can probably use a regex that grab content like `filename=\"([^\"]*)\"` (not confirm yet)

If we need to support doublequote, we also need to make sure the pattern ends with the last quote (but it will break if the sample input is changed, for example

```
form-data; name="j_idt43:j_idt44"; filename="Test;123.txt" future attr="blath blah blah").
```

I would say the implementation detail was hacky in the first place... Any thoughts ?

**Comment by melloware** [comment]
relates to https://github.com/primefaces/primefaces/issues/506

**Comment by orange-buffalo** [comment]
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), for the multipart body the set of possible parameters is limited and, more interesting for us, every parameter value:
> use quoted-string syntax after the '=' sign

According to the [RFC2661](https://tools.ietf.org/html/rfc2616#section-2.2):
> quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
>  qdtext         = <any TEXT except <">>
>
>  The backslash character ("\\") MAY be used as a single-character
>  quoting mechanism only within quoted-string and comment constructs.
>
>  quoted-pair    = "\\" CHAR

If I understood this correctly, in case of the file name with double-quotes (`Test; "123.txt`), the header should look like:
```
form-data; name="j_idt43:j_idt44"; filename="Test; \"123.txt"
```

Not sure if all the cases could be covered by one regexp. I would suggest that parsing the header character-by-character based on what MDN and RFC state would be a bullet-proof solution. 

Btw, not sure if current implementation is case-sensitive, but MDN states that parameters are case-insensitive, I believe new implementation should take this into account.

**Comment by jxmai** [comment]
@orange-buffalo Maybe https://stackoverflow.com/questions/27226258/get-filename-from-content-disposition can help ?

**Comment by jxmai** [comment]
OK, I tested both cases and they all worked as expected. IMHO,  it should be a standard solution. PR will be coming shortly.

**Comment by orange-buffalo** [comment]
@jxmai, I've checked the input `form-data; name="j_idt43:j_idt44"; filename="Test; \"123.txt"` against this regexp, and it detects the filename as `Test; \` instead of `Test; "123.txt`.
Maybe providing a unit test for the parser could be a good option to ensure the expected result?

**Comment by melloware** [comment]
It seems like the only truly correct way to parse a Content-Disposition header is to parse it char by char.  See these two classes from javax.mail

http://grepcode.com/file_/repo1.maven.org/maven2/org.apache.geronimo.specs/geronimo-javamail_1.4_spec/1.1/javax/mail/internet/ContentDisposition.java/?av=f

http://grepcode.com/file/repo1.maven.org/maven2/org.apache.geronimo.specs/geronimo-javamail_1.4_spec/1.1/javax/mail/internet/HeaderTokenizer.java?av=f

Or this guy wrote a crazy one for Javascript that might be convertable to Java.  Looks like he handles lots of special cases?

https://github.com/jshttp/content-disposition/blob/master/index.js

**Comment by jxmai** [comment]
Note: The `getFileName` method we are currently using is exactly the same as the example in Oracle's official Java EE 6 tutorial (https://docs.oracle.com/javaee/6/tutorial/doc/glraq.html). Well, this problem might not be easy by nature...

---

It might be better to have a standard known solution that we can use directly. It is a little overwhelm if we choose to parse char by char like building a parsing library ourselves.

@orange-buffalo Adding unit test is a good suggestion :+1: , but looking at the resource links above, it seems to me that not a single regex can solve the problem by one shot (that PR might need to be closed unless we have a better solution).

**Comment by tandraschko** [comment]
+1 to change here something only with a good amount of unittests ;)

**Comment by melloware** [comment]
It doesn't look like Omnifaces does it correctly either.

https://github.com/omnifaces/omnifaces/blob/develop/src/main/java/org/omnifaces/util/Servlets.java#L405

**Comment by melloware** [comment]
OK can you guys test my PR: https://github.com/primefaces/primefaces/pull/3043

I have unit tests that test all the scenarios we have discussed so far and prove that it works.  I had to parse character by character but it wasn't so bad.  Uses only native java code and no libraries to perform the task.

**Comment by orange-buffalo** [comment]
@melloware Thanks for the PR! We will try to share our test results today or tomorrow.

**Comment by melloware** [comment]
Thanks @orange-buffalo definitely let me know how it goes or if I need to add any more test cases.

**Comment by orange-buffalo** [comment]
@melloware We have tested file upload in your branch, and it works fine with double quotes and semicolons. Thanks a lot! We are looking forward to getting the PF version with this fix.

**Comment by melloware** [comment]
Awesome!  Hopefully PF will approve this patch as it meets the following criteria:
- Fixes unix bugs
- pure java code (no libraries needed)
- doesn't break anything that used to work
