### ISSUE TITLE
Global tooltip is not styleable

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#304]
The component attributes `style` and `styleClass` are only considered when the tooltip is not global (resp. a target is given via `for`). The global tooltip is generated in javascript and doesn't know anything about those attributes.

**Comment by cagataycivici** [comment]
Why not just use .ui-tooltip-global?

**Comment by fanste** [comment]
That's what I'm currently doing, but normally we avoid style declarations outside of css files. As we require a different styling on some pages, this could be only archived by using different stylesheets. Quite a bit ugly if it's only because of a single declaration.

**Comment by cagataycivici** [comment]
It is a very rare case, global tooltip is global so same styling makes sense across pages. If more users request this, we'll reconsider. Thank you.
