### ISSUE TITLE
Dialog doesn't set focus on forms with only radio and checkboxes inside them.

### ISSUE THREAD

**Issue by qnox** [primefaces/primefaces#3045]
## 1) Environment
- PrimeFaces version: 
6.1
- Does it work on the newest released PrimeFaces version? Version?
No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No
- Application server + version:
JBoss EAP 7.0.8.GA
- Affected browsers:
Not depends on browser

## 2) Expected behavior
Form inside dialog with only radio or checkbox inputs is supposed to get focus on dialog open and p:defaultCommand for this form is supposed to work

## 3) Actual behavior
Focus stays outside dialog and p:defaultCommand doesn't work

## 4) Steps to reproduce
Create form inside dialog with only p:selectOneRadio or p:selectBooleanCheckbox inside. Add p:button and p:defaultCommand to it. Open dialog. Press enter 'Enter' .

## 5) Sample XHTML

      <p:commandButton value="Text Input" onclick="PF('textInputDlg').show();" type="button" />
      <p:commandButton value="Checkbox" onclick="PF('checkboxDlg').show();" type="button" />
      <p:commandButton value="Radio" onclick="PF('radioDlg').show();" type="button" />

      <p:dialog header="Text Input" widgetVar="textInputDlg">
        <h:form>
          <p:inputText />
          <p:button id="textInputClose" value="Close" onclick="PF('textInputDlg').hide();" />
          <p:defaultCommand target="textInputClose" />
        </h:form>
      </p:dialog>

      <p:dialog header="Checkbox" widgetVar="checkboxDlg">
        <h:form>
          <p:selectBooleanCheckbox />
          <p:button id="checkboxClose" value="Close" onclick="PF('checkboxDlg').hide();" />
          <p:defaultCommand target="checkboxClose" />
        </h:form>
      </p:dialog>

      <p:dialog header="Radio" widgetVar="radioDlg">
        <h:form>
          <p:selectOneRadio id="radioId">
            <f:selectItem itemLabel="One" itemValue="One"/>
            <f:selectItem itemLabel="Two" itemValue="Two"/>
          </p:selectOneRadio>
          <p:button id="radioClose" value="Close" onclick="PF('radioDlg').hide();" />
          <p:defaultCommand target="radioClose" />
        </h:form>
      </p:dialog>

## 6) Sample bean
None

**Comment by melloware** [comment]
Just for my knowlegde can you try two things.

1. Use a p:focus
```xml
  <p:dialog header="Checkbox" widgetVar="checkboxDlg">
    <h:form>
       <p:focus for="checkbox" />
      <p:selectBooleanCheckbox id="checkbox"/>
      <p:button id="checkboxClose" value="Close" onclick="PF('checkboxDlg').hide();" />
      <p:defaultCommand target="checkboxClose" />
    </h:form>
  </p:dialog>
```

2. Put the form outside the dialog.
```xml
  <h:form>
    <p:dialog header="Checkbox" widgetVar="checkboxDlg">
    
       <p:focus for="checkbox" />
      <p:selectBooleanCheckbox id="checkbox"/>
      <p:button id="checkboxClose" value="Close" onclick="PF('checkboxDlg').hide();" />
      <p:defaultCommand target="checkboxClose" />

     </p:dialog>
  </h:form>
```

**Comment by sentinalll** [comment]
Hi, I tried both cases and they are also not working.

**Comment by melloware** [comment]
OK thanks for testing it out.  I just wanted to rule some things out.

**Comment by melloware** [comment]
What about this?  It looks like the dialog has a focus property?

https://www.primefaces.org/showcase/ui/overlay/dialog/focus.xhtml

`<p:dialog header="Checkbox" widgetVar="checkboxDlg" focus="checkbox">`

**Comment by qnox** [comment]
Yes, I know about focus attribute, but I'm wondering why dialog default behavior is different in case of checkboxes and radio buttons? It requires additional effort to create such dialogs when in case of textboxes everything works right out of the box.

**Comment by melloware** [comment]
Agreed I am just asking if focus="" works?

**Comment by qnox** [comment]
Nope, It doesn't work in case of checkbox or combobox

**Comment by melloware** [comment]
That is what I suspected so it's all the same focus code that has the bug.

**Comment by melloware** [comment]
OK I can't explain why but it looks like radio and checkbox were excluded on purpose?

```javascript
this.jq.find(':not(:submit):not(:button):not(:radio):not(:checkbox):input:visible:enabled:first').focus();
```
Basically says don't focus on any Submit, Button, Radio, or Checkbox only a "visible" input field.

**Comment by melloware** [comment]
@jxmai I wonder if this should be using the focus updates you did https://github.com/primefaces/primefaces/pull/3037 and the reason they were not looking for checkbox or radio was that it may be invisible?

**Comment by jxmai** [comment]
@melloware Could you pull my branch and give it a try since you have all the setup ready (https://github.com/jxmai/primefaces/tree/PF_3029) ? I guess radio focus could be fixed but I am not so sure about the other components.

---

The feedback could be valuable since we may need to refactor the focus function further.

**Comment by jxmai** [comment]
No, #3037 is not related to this issue.

Please look at the following snippet

https://github.com/primefaces/primefaces/blob/481fdff1c23dfff61425afd2800d3d93d4c2c5c3/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L298-L303

and it was done by this commit:

https://github.com/primefaces/primefaces/commit/f3f835a433c27ac4f83c3f2c1454c82b2365f75c

I would suggest to let @mertsincan chime in since the commit says `bug fix` but we are not sure the bug specifically.

**Comment by melloware** [comment]
Yep I saw that too and couldn’t figure out what bug it fixed.  It definitely seemed intentional and hopefully Mert can explain why so we can fix it a different way.

**Comment by jxmai** [comment]
Continue the discussion from https://github.com/primefaces/primefaces/pull/3037#issuecomment-352413245:

>  this looks good. I wonder if that was the intent of #3045 by not selecting radio/checkbox in the dialog the real intent was don't focus "hidden" controls but that fix was quick and dirty to just never focus any radio or checkbox. We may be able to reuse this function to fix that dialog issue.

I see what you mean. It is very likely that was the real intent for not to focus hidden inputs.  https://github.com/primefaces/primefaces/commit/f3f835a433c27ac4f83c3f2c1454c82b2365f75c would be hacky in the first place if that was really the case.

---

CSS3 `not` only accept a **simple selector** at a time so that we cannot fix it in one line...

https://www.w3.org/TR/css3-selectors/#negation

If we can do `not (argument1 && argument 2)` that would be cool.

---

*(side note: just found out that the statement above belongs to one of the features in CSS4 http://css4.rocks/negation-pseudo-class.php)*

**Comment by orange-buffalo** [comment]
Hi @melloware, @jxmai, is there any news about this problem? Can we help here?

**Comment by melloware** [comment]
I think we need @mertsincan to chime in here why he added "not(:radio):not(:checkbox)" in that ticket and what problem it was trying to fix so we can come up with the correct fix.

**Comment by mertsincan** [comment]
@melloware, I do not remember it exactly, but it was reported by a PRO user. I think users can use ```focus``` attribute of dialog for such topics. We only support focusing on enabled/visible input by default. 
Also, could you please try the following code after removing :not(:radio):not(:checkbox)?
```
<p:commandButton value="Radio" onclick="PF('radioDlg').show();" type="button" />


  <p:dialog header="Radio" widgetVar="radioDlg">
    <h:form>
        <p:selectOneRadio id="radioId" value="Two">
        <f:selectItem itemLabel="One" itemValue="One"/>
        <f:selectItem itemLabel="Two" itemValue="Two"/>
      </p:selectOneRadio>
      <p:button id="radioClose" value="Close" onclick="PF('radioDlg').hide();" />
      <p:defaultCommand target="radioClose" />
    </h:form>
  </p:dialog>
```
- After you open the dialog, please press the 'Space' key. You'll see the problem.

@qnox, please try the following code;
```
 <p:commandButton value="Text Input" onclick="PF('textInputDlg').show();" type="button" />
  <p:commandButton value="Checkbox" onclick="PF('checkboxDlg').show();" type="button" />
  <p:commandButton value="Radio" onclick="PF('radioDlg').show();" type="button" />

  <p:dialog header="Text Input" widgetVar="textInputDlg">
    <h:form>
      <p:inputText />
      <p:button id="textInputClose" value="Close" onclick="PF('textInputDlg').hide();" />
      <p:defaultCommand target="textInputClose" />
    </h:form>
  </p:dialog>

  <p:dialog header="Checkbox" widgetVar="checkboxDlg" focus="@(.ui-selectbooleancheckbox input:checkbox)">
    <h:form>
      <p:selectBooleanCheckbox />
      <p:button id="checkboxClose" value="Close" onclick="PF('checkboxDlg').hide();" />
      <p:defaultCommand target="checkboxClose" />
    </h:form>
  </p:dialog>

  <p:dialog header="Radio" widgetVar="radioDlg" focus="@(.ui-selectoneradio input:radio:checked,input:radio:first)">
    <h:form>
        <p:selectOneRadio id="radioId" value="Two">
        <f:selectItem itemLabel="One" itemValue="One"/>
        <f:selectItem itemLabel="Two" itemValue="Two"/>
      </p:selectOneRadio>
      <p:button id="radioClose" value="Close" onclick="PF('radioDlg').hide();" />
      <p:defaultCommand target="radioClose" />
    </h:form>
  </p:dialog>
```

**Comment by VsevolodGolovanov** [comment]
The problem likely was that focusing the first radio item looks bad, if the selected item is different. So the focus function should take care to focus the selected radio item. I thought PrimeFaces.focus implemented this though (#3029)? Not sure why dialog still reinvents it...

**Comment by melloware** [comment]
@VsevolodGolovanov can you investigate and provide a PR if we have reusable code we are not reusing?  I agree I dont like reinventing the wheel.

**Comment by VsevolodGolovanov** [comment]
@melloware, there it is.

I checked that this fixes the cases provided by the OP.

Additionally checked that it focuses the selected radio item, if there is one:
```
  <p:commandButton value="Selected Radio" onclick="PF('selradioDlg').show();" type="button" />

  <p:dialog header="Selected Radio" widgetVar="selradioDlg">
    <h:form>
      <p:selectOneRadio id="radioId" value="Two">
        <f:selectItem itemLabel="One" itemValue="One"/>
        <f:selectItem itemLabel="Two" itemValue="Two"/>
      </p:selectOneRadio>
      <p:button id="radioClose" value="Close" onclick="PF('selradioDlg').hide();" />
      <p:defaultCommand target="radioClose" />
    </h:form>
  </p:dialog>
```
