### ISSUE TITLE
MultiViewState support to resizable DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3046]
<p:dataTable multiViewState="true" resizableColumns="true" .../>

Required;
- <p:ajax event=".." /> in datatable
- <h:form>

**Comment by Rapster** [comment]
@mertsincan Since you're working on MultiViewState, could you please have a look at this one #2631 I tried to analyse the problem but since I'm not very familiar with this feature i'm not sure what's going wrong

**Comment by mertsincan** [comment]
Thanks @Rapster ;) I'll check it after finishing multiViewState features.

**Comment by escay** [comment]
@mertsincan Is the event to be used colResize? As in:

`<p:ajax event="colResize" />`

I tested 
```

<p:dataTable id="carsResizableColumns" var="car" value="#{dtBasicView.cars}" resizableColumns="true" multiViewState="true">
    <p:ajax event="colResize" /> 
    <p:column headerText="Id" sortBy="#{car.id}"><h:outputText value="#{car.id}" /></p:column>
    <p:column headerText="Year" sortBy="#{car.year}"><h:outputText value="#{car.year}" /></p:column>
    <p:column headerText="Brand" sortBy="#{car.brand}" ><h:outputText value="#{car.brand}" /></p:column>
</p:dataTable>        
```

on 6.1.10 and it seems to work nicely. Thank you!

**Comment by mertsincan** [comment]
Yes, you need to use <p:ajax event="colResize" />
