### ISSUE TITLE
Export Page Data Only not working as expected.

### ISSUE THREAD

**Issue by vinodym** [primefaces/primefaces#305]
Export Page Data Only not working as expected.

in the Showcase

http://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml
1. when clicked on the icons below to "Export Page Data Only " 
   current data displayed in table is  not exported instead it displayed 10 random records.
2. when the lot size is 10 and only 3 rows are present , on click on "Export Page Data Only " 10 rows are displayed instead of 3 rows (3 rows will be multiplied)

**Comment by cagataycivici** [comment]
1) Expected as backing bean is RequestScoped
2) Can't replicate.

In future, please use forum first.

**Comment by vinodym** [comment]
we have fixed this issue in Exporter.java

please review this and let us know if this fix can be included as part of next release of primefaces.

steps to reproduce the issue.

pre requisits:
page size = 10;
actual rows displayed = 3;
then
1. download all records. ==> 3 rows will be download.
2. download page only records ==> 10 rows will be downloaded and result is the 3 actual rows repeated.

# 

the issue here is if we try to download the pageonly records. the records are less than page size , the down load will be duplicates of actual records till page size.

fix for that is 

# 

I have modified the code as below to fix the issue.
protected void exportPageOnly(FacesContext context, DataTable table, Object document) {
        int first = table.getFirst();
        int rows = 0;
        int totalRecord = table.getRowCount();
        int pageSize = table.getRows();
        if (totalRecord < pageSize) {
            rows = totalRecord;
        } else {
            rows = pageSize;
        }

```
    int rowsToExport = first + rows;

    for (int rowIndex = first; rowIndex < rowsToExport; rowIndex++) {
        exportRow(table, document, rowIndex);
    }
}
```

# 

code is present now prime faces is  as below.
protected void exportPageOnly(FacesContext context, DataTable table, Object document)
  {
    int first = table.getFirst();
    int rows = table.getRows();
    if (rows == 0) {
      rows = table.getRowCount();
    }

```
int rowsToExport = first + rows;

for (int rowIndex = first; rowIndex < rowsToExport; rowIndex++)
  exportRow(table, document, rowIndex);
```

  }

**Comment by vinodym** [comment]
please review this and let us know if this fix can be included as part of next release of primefaces.

**Comment by vinodym** [comment]
steps to reproduce the issue.

pre requisits:
page size = 10;
actual rows displayed = 3;
then 
1. download all records. ==> 3 rows will be download.
2. download page only records ==> 10 rows will be downloaded and result is the 3 actual rows repeated.
