### ISSUE TITLE
Dialog lose client state when updated

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3050]
Reported By PRO User;
> When a dialog is maximized, closed, re-rendered (via AJAX) and then shown again, it's displaying in a normal size but the maximized Boolean is still true so when toggling maximize nothing happen the first time

**Comment by tandraschko** [comment]
@mertsincan does it also fix #3039?

**Comment by mertsincan** [comment]
Thanks @tandraschko and @melloware ;)
