### ISSUE TITLE
Ultima theme not support Ribbon

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#3051]
The Ultima Theme not support the Ribbon component and i already talkt about in Forum with @Cagataycivici

https://forum.primefaces.org/viewtopic.php?f=42&t=53367

Please solve it for next Ultima Release

**Comment by Rapster** [comment]
Post here instead https://github.com/primefaces/layouts

**Comment by markusg80** [comment]
Ok i migrated it there

**Comment by Rapster** [comment]
You should be able to close this one then :wink:
