### ISSUE TITLE
Wizard: Support animation for changing steps

### ISSUE THREAD

**Issue by orange-buffalo** [primefaces/primefaces#3060]
Currently Wizard component simply [changes the content html when response is retrieved](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/wizard/wizard.js#L83):
```js
PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
    widget: $this,
    handle: function(content) {
        this.content.html(content);
    }
});
```

While this is working fine, the change is immediate, but sometimes UX requires smooth transitions between the wizard steps. For example, simple fade-in animation would greatly improve user experience.
```js
PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
  widget: $this,
  handle: function (content) {
    this.content.fadeTo(0, 0);
    this.content.html(content);
    this.content.fadeIn();
  }
});
``` 
Height could be easily added into the animation to make transition even smoother.

It would be great if PF supported the animation for content change in Wizard. This could be even completely delegated to users if they need it:
```js
PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
  widget: $this,
  handle: function (content) {
    if ($this.cfg.contentAnimation) {
      $this.cfg.contentAnimation(this.content, content);
    } else {
      this.content.html(content);
    }
  }
});

```

**Comment by melloware** [comment]
@orange-buffalo want to submit a PR?

**Comment by orange-buffalo** [comment]
@melloware, will not be able to work on this immediately, but in some time I think I can provide one.

**Comment by orange-buffalo** [comment]
@melloware, unfortunately I will not be able to work on this PR. My project is migrating away from JSF stack, and this topic is no longer relevant for us. We can close this request if community has no interest in this feature.

**Comment by melloware** [comment]
I will leave it open. It will be sad to see you go your contributions to the community have been much appreciated.
