### ISSUE TITLE
Dialog: Closing X in not modal dialog not in navigation flow

### ISSUE THREAD

**Issue by VSchlapa** [primefaces/primefaces#3069]
1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version?: NO
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source): NO
- Application server + version: 
- Affected browsers: Firefox 56, Chrome 63.03239, Microsoft Edge 40

2) Expected behavior
in basic dialog component with header set: Closing X should be the last element to be tabbed with the keyboard tabulator. Basic Dialog should be usable and closable with keyboard only.
(in a MODAL dialog it works fine. The x will be tabbed after the action buttons on the bottom)

3) Actual behavior
in basic dialog component with header set: You can tab trough all Elements inside the dialog except the closing x. The closing x in the header is not reachable for keyboard only users. 

4) Steps to reproduce
Open a basic dialog. 
Use the tabulator key to navigate through the elements of the dialog. 
Try to reach the closing x with keyboard usage only

5) Sample Code
<p:dialog draggable="false" header="Basic Dialog" minHeight="40" resizable="false" widgetVar="dlg1">

**Comment by humankey** [comment]
+1 definitely needed!

**Comment by melloware** [comment]
When I go to the showcase and click on the Basic dialog I can tab to the "X" and press Enter and close the dialog.  What am I missing?

https://www.primefaces.org/showcase/ui/overlay/dialog/basic.xhtml

**Comment by VSchlapa** [comment]
@melloware Sorry you're right, I updated the issue. Actually the effect occurs only when setting a headline for the basic dialog. The basic dialog in the showcase doesn't use a headline part, for that it is not reproducible there. I added a sample of the code we were using

**Comment by melloware** [comment]
Excellent thanks for adding the information.

**Comment by melloware** [comment]
I am using the 6.2-SNAPSHOT showcase and I just changed to this...

`<p:dialog draggable="false" header="Basic Dialog" minHeight="40" resizable="false" widgetVar="dlg1">`

And I can tab to it fine and click ENTER to close.  Are you sure this isn't fixed already in 6.2-SNAPSHOT?

**Comment by VSchlapa** [comment]
I just doublechecked with the community version 6.1, this is what we were using. There the problem still exists. I don't have any other access to the 6.2 SNAPSHOT than the showcase mentioned above and there the header part is not included ;(
By "latest version" I interpreted the latest community version. I'm sorry for my misinterpretation, this is the first issue I reported ever ;) Seems I've got a lot to learn

**Comment by melloware** [comment]
Hey no problem.  I typically test using the latest code so I am not chasing a bug that has already been fixed.  To build the 6.2-SNAPSHOT is not that hard. Just follow these instructions:  https://github.com/primefaces/primefaces/wiki/Building-From-Source

**Comment by VSchlapa** [comment]
@melloware thank you for your excellent support!
Am I right, that the 6.2-SNAPSHOT Version is a premium version and not yet available for community (free) users? In this case I will have to wait until it is released :(
Thanks to your help I know now, that this problem will be solved in the future builds ;)

**Comment by melloware** [comment]
No basically 6.2-SNAPSHOT will become the 6.2 Community Release. You can always build the code from source and its a 100% free and open license.

**Comment by VSchlapa** [comment]
Oh, this is good to know. Thank you so much! I learned a lot today, for I'm just the UX guy ;)

**Comment by jxmai** [comment]
This issue can be closed then.
