### ISSUE TITLE
Calendar: Support Java 8 Date API

### ISSUE THREAD

**Issue by xtron** [primefaces/primefaces#3072]
## 1) Environment
- PrimeFaces version: 6.1.9
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Wildlfy 10.0.1
- Affected browsers: all

## 2) Expected behavior

Support Java 8 Date API (LocalDate,ZonedDateTime etc) for p:calendar

## 3) Actual behavior

Don't support:
Caused by: java.lang.ClassCastException: java.util.Date cannot be cast to java.time.ZonedDateTime
..

## 4) Steps to reproduce
 Create xhtml, create bean with new date field.

.. 

## 5) Sample XHTML
 <p:calendar value="#{myBean.newDate} ...
..

## 6) Sample bean
 private ZonedDateTime newDate;
  ...
 getter and setter
..

**Comment by Rapster** [comment]
1. Primefaces is compatible with <= JDK 1.6
2. Next time, give more details about the stacktrace not only the first line

**Comment by tandraschko** [comment]
Can be simple done with a converter ;) Mabye we will do it in the future.

**Comment by tandraschko** [comment]
See: https://github.com/primefaces/primefaces/issues/4646
