### ISSUE TITLE
Dialog: showing dialog on complete after update does not work the first time on jQuery 3

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#3073]
## 1) Environment
- PrimeFaces version: PF latest snapshot
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Not relevant
- Affected browsers: not relevant

## 2) Expected behavior

Dialog should be shown right after button was clicked

## 3) Actual behavior

The screen splashes the first time 

## 4) Steps to reproduce

Clicking `modal2` 

![image](https://user-images.githubusercontent.com/10467831/33953157-afc805d8-dff9-11e7-933b-8a5c4b0f2c12.png)

## 5) Sample XHTML

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<f:view contentType="text/html">
	<h:head>
	</h:head>
	<h:body>

		<h:form id="mainForm">

			<p:commandButton value="Modal 2"
				oncomplete="PF('dlg2').show();" update="dialog2"/>
				
			<p:commandButton value="Modal 3"
				oncomplete="PF('dlg2').show();" update="dialog3"/>

			<p:dialog id="dialog2" header="Modal Dialog" widgetVar="dlg2"
				modal="true" minimizable="true" maximizable="true" height="100">
				<h:outputText value="This is a Modal Dialog." />
			</p:dialog>
			
			<p:dialog id="dialog3" header="Modal Dialog" widgetVar="dlg3"
				modal="true" minimizable="true" maximizable="true" height="100">
				<h:outputText value="This is a Modal Dialog." />
			</p:dialog>

		</h:form>

	</h:body>
</f:view>

</html>
```

## 6) Analysis

This regression is caused by https://github.com/primefaces/primefaces/commit/fc9eda2bdf7852523f553e26a52413f2d6c741b5 (https://github.com/primefaces/primefaces/issues/3062)

**Comment by mertsincan** [comment]
I'll check it.

**Comment by mertsincan** [comment]
It may be related to https://github.com/primefaces/primefaces/issues/3039

**Comment by jxmai** [comment]
To make sure: I also bisected this bug and the result showed me that fc9eda2bdf7852523f553e26a52413f2d6c741b5 `is the first bad commit
`

https://github.com/primefaces/primefaces/commit/e29396526d93f1e641654989f9cbb9717003576d was done 5 days ago and no problem so far until JQ3 upgrade, so it may not be related to #3039 

There is no log, no error, just splash screen.

**Comment by mertsincan** [comment]
I couldn't replicate it. My test video;
https://www.dropbox.com/s/2j4whh1yr2ovkb9/dialog_test.mp4?dl=0

**Comment by mertsincan** [comment]
Which browser are you using?

**Comment by tandraschko** [comment]
doesn't work for me in the current firefox, too.

**Comment by tandraschko** [comment]
also fails in chrome - i just copied the example above into the showcase.

**Comment by mertsincan** [comment]
Ok, thanks a lot! I'll check it again.

**Comment by jxmai** [comment]
@mertsincan I checked your screencast but I wasn't sure why you couldn't replicate the issue. The sample above can surely replicate the issue on different browsers / machines. In order to expose this issue in a cleaner way, I simplify the sample further and provide a zipped test project for you:

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">
	<h:head>
	</h:head>
	<h:body>
		<h:form id="mainForm">
			<p:commandButton value="Test"
				oncomplete="PF('dlg2').show();" update="dialog2"/>
				
			<p:dialog id="dialog2" header="Modal Dialog" widgetVar="dlg2"
				modal="true" minimizable="true" maximizable="true" height="100">
				<h:outputText value="This is a Modal Dialog." />
			</p:dialog>
		</h:form>

	</h:body>

</html>
```

[primefaces-test-3073.zip](https://github.com/primefaces/primefaces/files/1568477/primefaces-test-3073.zip)


```
mvn clean jetty:run
```

then go to: http://localhost:8080/primefaces-test/


![pf_3073_bug](https://user-images.githubusercontent.com/10467831/34131966-6e2f6670-e413-11e7-98c8-00a6a76adeda.gif)

**Comment by jxmai** [comment]
After some debugging, I noticed that Primefaces init function is called **after** dialog show since  JQ3. I did not figure out the root cause yet. You guys should have a better understanding of what's going on.

Normally, the first thing after clicking the button is to trigger core js update and recall init before showing the dialog

https://github.com/primefaces/primefaces/blob/99bbe57fe0c363b5344400a0c510760252871d2b/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L6

then 

https://github.com/primefaces/primefaces/blob/99bbe57fe0c363b5344400a0c510760252871d2b/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L206-L209

then we should have a working dialog at this point

https://github.com/primefaces/primefaces/blob/99bbe57fe0c363b5344400a0c510760252871d2b/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L245-L246

---

but now:

https://github.com/primefaces/primefaces/blob/99bbe57fe0c363b5344400a0c510760252871d2b/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L206-L209

then

https://github.com/primefaces/primefaces/blob/99bbe57fe0c363b5344400a0c510760252871d2b/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L245-L246

After going through the function above, nothing shows up since the dialog hasn't initialized yet.

finally

https://github.com/primefaces/primefaces/blob/99bbe57fe0c363b5344400a0c510760252871d2b/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L6

the following lines wipe off the modal so that the screen blinks

https://github.com/primefaces/primefaces/blob/99bbe57fe0c363b5344400a0c510760252871d2b/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L62-L65


**The key here is to figure out why the function call order has changed since JQ3 upgrade**

**Comment by mertsincan** [comment]
I'm testing my fix now. I changed our core.ajax.js. 
I think 'complete' = 'always().then()'

**Comment by jxmai** [comment]
Alright, if the execution order can flip back, this issue will be fixed.

**Comment by mertsincan** [comment]
Fixed now. Could you please test this fix? It works fine for me.

**Comment by jxmai** [comment]
Thanks :+1:  I tested. The fix works well.

**Comment by jasonex7** [comment]
I experience some issue related to this one. I think is the same case except that instead of execute `PF('dialog').show();` in the `oncomplete `property, I use an action method in Backing Bean that execute  `PrimeFaces.current().executeScript("PF('dialog').show();");`, also I use `update="dialog"` property in the `<p:commandButton>`. In this case the results are the same as the gif @jxmai posted.

> ![issue dialog](https://user-images.githubusercontent.com/10467831/34131966-6e2f6670-e413-11e7-98c8-00a6a76adeda.gif)

I'm using the last (to this date) commit of PrimeFaces:  0f2c8b5ec870f732abe2f5283539dc17c74f90cd

**Comment by jxmai** [comment]
@jasonex7 Good catch ! :+1:  I can replicate the issue based on your description.  

@mertsincan  Please review this issue since the fix cannot cover all the cases as jasonex7's description.

Sample:

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">
	<h:head>
	</h:head>
	<h:body>
		<h:form id="mainForm">
			<p:commandButton value="Test" actionListener="#{testView.openDialog()}" update="dialog2"/>
				
			<p:dialog id="dialog2" header="Modal Dialog" widgetVar="dlg2"
				modal="true" minimizable="true" maximizable="true" height="100">
				<h:outputText value="This is a Modal Dialog." />
			</p:dialog>
		</h:form>

	</h:body>

</html>
```


```java
package org.primefaces.test;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.PrimeFaces;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 4124891683211838799L;

    private String testString;

    public void openDialog() {
        PrimeFaces.current().executeScript("PF('dlg2').show()");
    }

    @PostConstruct
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }
}

```

[primefaces-test-3073-case2.zip](https://github.com/primefaces/primefaces/files/1583449/primefaces-test-3073-case2.zip)

```
mvn clean jetty:run
```

then go to 

http://localhost:8080/primefaces-test/

**Comment by tandraschko** [comment]
I think the last fix just worked randomly.
The ajax engine itself is fine, the only problem is that document.ready functions ($(function() {...})) are not executed async
so the widget init scripts are parsed after executing the oncomplete.

See: https://jquery.com/upgrade-guide/3.0/#breaking-change-document-ready-handlers-are-now-asynchronous

**Comment by tandraschko** [comment]
Should be fixed now
WidgetBuilder#initWithDomReady doesn't use domready anymore :D
We will need to refactor it.

**Comment by jxmai** [comment]
@tandraschko Important note. Please review the primefaces trunk. I noticed the build process is throwing null pointer exception currently and the cause may or may not be related the fix here (to be verified).


```
PM org.primefaces.config.PrimeConfiguration initBuildProperties
SEVERE: Could not load pom.properties
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at org.primefaces.config.PrimeConfiguration.initBuildProperties(PrimeConfiguration.java:191)
	at org.primefaces.config.PrimeConfiguration.<init>(PrimeConfiguration.java:85)
	at org.primefaces.util.WidgetBuilderTest.getWidgetBuilder(WidgetBuilderTest.java:33)
	at org.primefaces.util.WidgetBuilderTest.shouldBuildWithAttributes(WidgetBuilderTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

```

**Comment by tandraschko** [comment]
better now? ;)

**Comment by jxmai** [comment]
I don't see any new commit in trunk. Did you forget to push ?  By the way, 4cbc824a27570d208970b39406e2bdaef1c58118 is causing the null pointer, the problem is not about the fix in here.

---


update: I tried out the new commit and confirmed the null pointer has gone :+1:
