### ISSUE TITLE
Add swipe functionality to TabView

### ISSUE THREAD

**Issue by ReedElliott** [primefaces/primefaces#3078]
## 1) Environment
- PrimeFaces version: 6.1.10
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? 
- Application server + version:
- Affected browsers:

## 2) Expected behavior
When you swipe left on a TabView, the screen should move one tab to the right and when you swipe right the screen should move one tab to the left.

Note: the TabView menu should also scroll to the right or left so that the currently displayed tab is visible in the menu.

I documented how I added swipe to TabView in the following Forum entry.

https://forum.primefaces.org/viewtopic.php?f=3&t=53503

Note:  In my solution, the TabView menu does not scroll with the page swipe so if the entire menu is not visible you can display a page not visible/selectable on the menu. 

## 3) Actual behavior

At the moment, TabView does not support swipe left or swipe right.

## 4) Steps to reproduce

N/A

## 5) Sample XHTML

N/A

## 6) Sample bean

N/A

**Comment by melloware** [comment]
@ReedElliott  please review PR its based off your suggestion.

**Comment by Anacpsycho** [comment]
hi, i've update my software from primefaces 6.2 to 8.0 and i found this new feature... it's possible to disable swipe fuctionality for tabview ? 
there's any attribute to do this or any config key for web.xml? 

i find this row in the comit 
            excludedElements: "button, input, select, textarea, a, .noSwipe"
can i use .noSwipe class?

**Comment by melloware** [comment]
If you update to 10.0 there is a new property on TabView called `touchable` which you can set `touchable="false"` or if you want to disable touch entirely you can use web.xml

```xml
<context-param>
    <param-name>primefaces.TOUCHABLE</param-name>
    <param-value>false</param-value>
</context-param>
```

But for 8.0 you will have to override you need to use this MonkeyPatch JS to disable it....
```javascript
if (PrimeFaces.widget.TabView) {
   PrimeFaces.widget.TabView.prototype.bindSwipeEvents = function() {
       // do nothing
   }
}
```
