### ISSUE TITLE
DataTable: MultiViewState columnToggler and column sorting do not work together

### ISSUE THREAD

**Issue by escay** [primefaces/primefaces#3088]
## 1) Environment
- PrimeFaces version: 6.1.10
- Poseidon theme: 1.0.2
- Testing new enhancement #3044 in combination with column sorting
- Browser: Firefox 57.0.2

## 2) Expected behavior
Once a column is enabled via a columnToggler and you use column sorting all data should remain visible.

- Enable column 'car.brand' via the columnToggler. 
- Order the 'car.year' column by clicking on the Year header
- All data should stay visible

## 3) Actual behavior

After ordering on the 'car.year' the 'car.brand' column becomes empty and is not visible anymore

## 4) Steps to reproduce

- Enable column 'car.brand' via the columnToggler. 
- Order the 'car.year' column by clicking on the Year header
- Brand column is empty
- Leave page
- Go back to page
- Column toggler state is working, all data is rendered
- Order the 'car.year' column by clicking on the Year header
- Brand column is empty again

Note: if it is not the last column that is enabled or disabled, but for example the first column. Then all data moves. Example: disable the 'car.id' column, sort on the 'car.year' column: Year column contains the 'car.id' data and the 'car.brand' column contains the 'car.year' data. Once you go to another page and back to this page the data is rendered ok. Using a sorting on a header breaks it again.

## 5) Sample XHTML

```
<h:form id="form">
    <p:dataTable id="cars" var="car" value="#{dtBasicView.cars}" multiViewState="true">
        <f:facet name="header">
            List of Cars
            <p:commandButton id="toggler" type="button" value="Columns" style="float:right" icon="ui-icon-calculator" />
            <p:columnToggler datasource="cars" trigger="toggler">
                <p:ajax event="toggle" />
            </p:columnToggler>
        </f:facet>

        <p:column headerText="Id" sortBy="#{car.id}">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Year" sortBy="#{car.year}">
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Brand" sortBy="#{car.brand}" visible="false">
            <h:outputText value="#{car.brand}" />
        </p:column>
    </p:dataTable>
</h:form>
```

**Comment by leomekenkamp** [comment]
Just an idea: what about enhancing the [columnToggler to include state](https://stackoverflow.com/a/48822142/5153794), and then moving the multi view state handling to the columnToggler? The toggler could then have an implementation to store the multi view state in the browser, or provide the possibility to put it in a backing bean, or both.

**Comment by Quix0r** [comment]
6.2 is out, @escay can you please retry it with latest stable version?

**Comment by escay** [comment]
@Quix0r The issue is still marked as open, why would I test this? I would expect a note from @tandraschko if it was fixed in 6.2

**Comment by tandraschko** [comment]
I dont know all fixes and also dont comment all issues.

**Comment by escay** [comment]
Tested on 6.2.2, problem still exists:

- Enable column 'car.brand' via the columnToggler.
- Brand column is filled with brand data
- Order the 'car.year' column by clicking on the Year header
- Brand column is empty, data is lost

**Comment by mertsincan** [comment]
Could you please try the following code?
```
   <script type="text/javascript">
//<![CDATA[
/**
 * PrimeFaces DataTable Widget
 */
PrimeFaces.widget.DataTable.prototype.updateHiddenHeaders = function() {
    if(this.headers) {
        var $this = this;

        this.headers.each(function() {
            var header = $(this),
            col = $this.tbody.find('> tr > td:nth-child(' + (header.index() + 1) + ')');

            if(header.hasClass('ui-helper-hidden')) {
               col.addClass('ui-helper-hidden');
            }
            else {
                col.removeClass('ui-helper-hidden');
            }
        });
    }
}
//]]>
   </script>
```
