### ISSUE TITLE
Weird behavior menu + dataTable after upgrade

### ISSUE THREAD

**Issue by jnrbo** [primefaces/primefaces#3089]
Hi there!

I'm having a problem with Primefaces, after upgrading from Primefaces 3.4.1 to 6.1 and implemented Spring's transaction + Hibernate (with entityManager), I realized that one of my dataTables item edition (update or insert) stoped working. After some debug, I found that after I click in my submenu menuitem (actionPersist), the dataTable's selection is called before persist. This is the expected behavior?

(This happens in all my dataTables #tableMain)
(Both menuActions.xhtml, my dataTable and inputs (to edit) are inside a form #formMain)

**jobs.xhtml**

```
<ui:composition template="/include/xhtml/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<ui:define name="center">
    <p:panel id="pnMain" header="#{jobMB.currentTela.nome}">			
        <p:growl id="messages" autoUpdate="true" showDetail="true"/>
        <p:tabView id="tabView" activeIndex="#{jobMB.activeTab}" >
            <p:tab title="Serviço" >
                <ui:include src="tabJobs.xhtml"/>
            </p:tab>
         </p:tabView>			
     </p:panel>

    <p:spacer height="10px"/>

    <p:dataTable id="tableMain" value="#{jobMB.entityList}" var="s" rows="10" selection="#{jobMB.entitySelect}" selectionMode="single" rowKey="#{s}" >
        <p:ajax event="rowSelect" update=":formMain:pnMain,:formMain:menuReports" />

        <p:column headerText="Protocol" sortBy="#{s.protocol}" filterBy="#{s.protocol}" >  
            <h:outputText value="#{s.protocol}" />                 
        </p:column>

        <p:column headerText="Date Limit" sortBy="#{s.date}" filterBy="#{s.date}" > 
            <h:outputText value="#{s.date}">
                <f:convertDateTime pattern="dd/MM/yyyy"/>
            </h:outputText>
        </p:column>

    </p:dataTable>

</ui:define>
<ui:define name="layoutWest">   
    <ui:include src="/include/xhtml/menuActions.xhtml">
        <ui:param name="bean" value="#{jobMB}" />       
    </ui:include>
    
    <p:menu id="menuReports">  
        <p:submenu id="submenuReports" label="Print"> 
            <p:menuitem id="printLaudo" value="Laudo" icon="ui-icon-print" ajax="false"  disabled="#{jobMB.entity.laudo.codservico == null}">
                <p:fileDownload value="#{jobMB.reportLaudo}"  />
            </p:menuitem>
        </p:submenu>  
    </p:menu>
    
</ui:define>
</ui:composition>
```

**menuActions.xhtml**
```
<p:menu id="menuActions">  
    <p:submenu id="submenuOpcoes" label="Opções"> 
        <p:menuitem id="actionNew" value="Novo" actionListener="#{bean['actionNew']}" update=":formMain:pnMain,:formMain:tableMain" process="@this" immediate="true" />
        <p:menuitem id="actionPersist" value="Salvar" actionListener="#{bean['actionPersist']}" update=":formMain:pnMain,:formMain:tableMain" process="@form" />  
        <p:menuitem id="actionRemove" value="Excluir" actionListener="#{bean['actionRemove']}" update=":formMain:pnMain,:formMain:tableMain" process="@form" />
        <p:separator/>
        <p:menuitem id="actionClosePage" value="Fechar" actionListener="#{bean['actionClosePage']}" immediate="true" />  
    </p:submenu>  
</p:menu>
```

**tabJobs.xhtml**

```
<h:panelGrid columns="2" id="pnServico">
    <h:panelGrid columns="2">
        <h:outputLabel for="pontoAtend" value="(2) Ponto de Atend.:" />                
        <p:selectOneMenu id="pontoAtend" value="#{jobMB.entity.pontoAtend}" required="true" converter="convPontoAtend">
            <f:selectItem itemValue="#{null}" itemLabel="Selecione um Ponto de Atendimento" />
            <f:selectItems value="#{jobMB.pontosAtend}" var="p" itemLabel="#{p.pontoAtend}" itemValue="#{p}" />                 
            <p:ajax update=":formMain:tabView:pnServico" process="@this" listener="#{jobMB.onChangePontoAtend}"/>
        </p:selectOneMenu>
    </h:panelGrid>

    <h:panelGrid columns="2">
        <h:outputLabel for="obs" value="(13) Observação:" />
        <p:inputTextarea id="obs" rows="5" cols="73" value="#{jobMB.entity.obs}" />
    </h:panelGrid>
</h:panelGrid>
```

**template.xhtml**
```

<ui:insert name="pageBody">
    <h:form id="formMain">
        <p:layout id="layoutMain" fullPage="true">
                                            
            <!--  header -->
            <ui:insert name="header">
                <p:layoutUnit id="layoutHeader" position="north" size="50">
                    <ui:insert name="layoutNorth">
                        <p:menubar id="menuBar" model="#{sisMainMenuMB.mainMenu.menuModel}"></p:menubar>
                    </ui:insert>                        
                </p:layoutUnit>                 
            </ui:insert>
                    
            <!--  center -->
            <p:layoutUnit id="layoutCenter" position="center">                  
                <ui:insert name="center"></ui:insert>                   
            </p:layoutUnit>             
            
            <!--  footer -->
            <ui:insert name="footer">
                <p:layoutUnit id="layoutFooter" position="south" size="100" header="Bottom" resizable="true" closable="true" collapsible="true">
                    <ui:insert name="layoutSouth"></ui:insert>
                </p:layoutUnit>
            </ui:insert>
            
            <!--  left -->
            <ui:insert name="left">
                <p:layoutUnit id="layoutLeft" position="west" size="165" resizable="true" closable="true" collapsible="true">
                    <ui:insert name="layoutWest"></ui:insert>
                </p:layoutUnit>
            </ui:insert>
        </p:layout>
    </h:form> 
</ui:insert>
```

**JobMB.java**

 ```
@ManagedBean
@ViewScoped
public class JobMB {


    @Transactional
    public void actionPersist(ActionEvent event) {
         try {
            Integer currentId = getEntity().getCod();

            if (getbO().persist(getEntity())) {
                setEntityList(null);
                if (currentId == null) {
                    Job s = getbO().getByProtocol(getEntity().getProtocol());
                    setEntity(s);
                }
                addInfo("Saved", "");
            } else {
                addError("Error", "Fail!");
            }
        } catch (Exception e) {
            log.error("Erro no actionPersist", e);
        }
    }

    @Transactional
    @Override
    public void setEntitySelect(Job entitySelect) {
        if (entitySelect != null) {
            this.entity = entitySelect;
        }
        this.entitySelect = entitySelect;
    }

}
```

Another weird thing is that if I add immediate="true"  in #actionPersist, only itens that uses ajax to set my entity value are persisted. (almost all the other dataTables stop working (persisting))

##  Environment
- PrimeFaces version: 6.1
- JDK: 1.8.1
- Spring: 4.3.12
- Hibernate: 5.2.4
- javax.faces: 2.2.15

**Comment by jxmai** [comment]
@jnrbo Please provide a full sample. Based on the description above, I don't think we can replicate.

---

> (Both menuActions.xhtml, my dataTable and inputs (to edit) are inside a form #formMain)

First of all, menu is not part of a datatable. I thought you were mentioning https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml, but I don't think that's your use case after taking a look at the partial sample and the description your provided.

**Comment by jnrbo** [comment]
Done, I updated my post!

**Comment by jxmai** [comment]
Hmm, does the sample require Spring ? (I noticed the `@Transactional` annotation)  That would violate the minimal reproducible rule since we cannot run it easily. 

@jnrbo  Could you fork this project (https://github.com/primefaces/primefaces-test) and make your sample become runnable ?

**Comment by jnrbo** [comment]
Yes, I can, but i would take a few hours.

**Comment by melloware** [comment]
@jnrbo If you don't mind creating one that is the only way we can help debug.

**Comment by jnrbo** [comment]
Did it. The persist bug is not happening in this example (Don't know why yet) but it's loggin the weird behavior that I sad before - about selecting the item before is persisted!

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/1577868/primefaces-test.zip)

**Comment by jxmai** [comment]
>  I found that after I click in my submenu menuitem (actionPersist), the dataTable's selection is called before persist.

There is a modal block appears and disappears immediately after clicking through any buttons in the menu. Is that the `weird behavior` you mentioned earlier ? Aside from that, I don't see any printlin from the console (using jetty server as a quick run).

Based on your description, should we  expect to see something invokes the following method when we click the menu ?

```java
public void setEntitySelect(Job entitySelect) {
        System.out.println("\nSelecting: " + entitySelect);
        if (entitySelect != null) {
            this.entity = entitySelect;
        }
        this.entitySelect = entitySelect;
    }
```

@jnrbo Your sample is a bit large TBH (looks like some parts of a real app) that is not clear what to do / what to expect, but please give more details especially for the following statement

> but it's loggin the weird behavior that I sad before - about selecting the item before is persisted!

![snapshot1](https://user-images.githubusercontent.com/10467831/34240408-6ceb52ee-e5d3-11e7-805c-10ec885baf13.png)

**Comment by jxmai** [comment]
Actually your sample was throwing exception

```
com.sun.faces.lifecycle.InvokeApplicationPhase execute
WARNING: Method not found: org.primefaces.test.JobMB@6451d189.actionNew()
javax.el.MethodNotFoundException: Method not found: org.primefaces.test.JobMB@6451d189.actionNew()
	at org.apache.el.util.ReflectionUtil.getMethod(ReflectionUtil.java:268)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:240)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)

```

**Comment by jnrbo** [comment]
> Based on your description, should we expect to see something invoke the following method when I click the menu ?

Yes If you select any item from the list, edit and save it, the log is similar to it:

```
Loading...
4 prices laoded.
7 jobs laoded.

Selecting: Job [code=3, protocol=PROTOCOL_0_3, obs=null]
Price changed!

Selecting: Job [code=3, protocol=PROTOCOL_0_3, obs=]
Persisting: PROTOCOL_0_3, code: 3
Persisted: PROTOCOL_0_3, code: 3
```

In the example, What I did was:
- Selected item "PROTOCOL_0_3"
- Edit it's price to "Pro 3"
- Save

The weird behavior is:
And in the console output you can see that BEFORE persisting the update, (after "Price changed!") the item from the list is selected again. 

And yes, this exception is throwing because I added only persist method to test (new, remove and close are not implemented).

**Comment by jxmai** [comment]
@jnrbo I don't think this is an issue. I traced back to primefaces 5 and obversed the same behavior. Unfortuately I cannot build 3.4.1 for some reason. Anyway, you should use `process` (https://www.primefaces.org/showcase/ui/ajax/process.xhtml) to limit which part **actually needs to be processed** and this issue should be dealt by the business layer. Currently you simply put `process=@form` that will submit everything (your code below)

```xhtml
<h:form id="formMain">
			<p:layout id="layoutMain" fullPage="true">
												
				<!--  header -->
			    <ui:insert name="header">
			    	<p:layoutUnit id="layoutHeader" position="north" size="50">
			    		<ui:insert name="layoutNorth"></ui:insert>						
					</p:layoutUnit>					
			    </ui:insert>
						
				<!--  center -->
				<p:layoutUnit id="layoutCenter" position="center">					
					<ui:insert name="center"></ui:insert>					
			    </p:layoutUnit>			    
			    
			    <!--  left -->
			    <ui:insert name="left">
			    	<p:layoutUnit id="layoutLeft" position="west" size="165" resizable="true" closable="true" collapsible="true">
						<ui:insert name="layoutWest"></ui:insert>
					</p:layoutUnit>
			    </ui:insert>
			    
			</p:layout>
			</h:form> 
```

---

```xhtml
<p:menuitem id="actionPersist" value="Save" icon="ui-icon-disk" actionListener="#{bean['actionPersist']}" update=":formMain:pnMain,:formMain:tableMain" process="@form"  />
```
---

For more info, please see: https://stackoverflow.com/questions/7776204/cancel-button-call-setter-getter-method-in-jsf

**Comment by jxmai** [comment]
@tandraschko Finished reviewing. This issue can be closed.

**Comment by jnrbo** [comment]
@jxmai, @tandraschko 

I'm Sorry, but I still don't think that is this the expected behavior. There's something wrong about this lifecycle. 

I reseted my application back to it's old version, and upgraded only primefaces and javax.faces.

It keeps some of attributes values but others don't after auto selecting

**Comment by jxmai** [comment]
@jnrbo The bottom line is you cannot rely on putting business logic in getter and setter in JSF related app. PF3.4.1 is out of my range since  PF 5 is the version as far as I can reach/build and which has the same behavior as PF6 in this particular case.  

---

> but I still don't think that is this the expected behavior

I would suggest that you need to reduce the sample even further instead of a mini app with composite layout etc. I might be able to take a look in my own environment. Currently the app is too big so I can only did quick run through terminal (Personal suggestion since what I says doesn't stand for PF by any means ). 

---

Side note: You can always analyse the problem yourself or report issue to Primefaces PRO if you need faster reponse
