### ISSUE TITLE
Prime Calendar with Timer not have the close function 

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3090]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: Latest showcase
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: All

## 2) Expected behavior

...There should be one way to close the calandar popup by using button.

  Actually I am searching the equivalent Calender with apply button what have in rich faces in calendar

## 3) Actual behavior

In Primefaces showcase, Calendar section with Datetime not have the close functionality of calendar popup.
For close we need to click outside the calendar popup

## 4) Steps to reproduce

Open Prime showcase: https://www.primefaces.org/showcase/ui/input/calendar.xhtml
Open DateTime  calendar
and select time and date and try to close (It will close only clicking outside the calendar window)

## 5) Sample XHTML

..<p:calendar pattern="MM/dd/yyyy HH:mm:ss" showOn="button"  locale="de" navigator="true" />

## 6) Sample bean

..

**Comment by ankitacroit09** [comment]
![capture](https://user-images.githubusercontent.com/25894208/34146566-97e2fd6c-e4c0-11e7-8d1f-7a5aefce65ea.JPG)
In Prime-showcase 
https://www.primefaces.org/showcase/ui/input/calendar.xhtml

**Comment by ankitacroit09** [comment]
![capturerich](https://user-images.githubusercontent.com/25894208/34146662-e83e3c9a-e4c0-11e7-8d29-efb4c36415a3.JPG)

This is Richfaces Calendar the same functionality  I am searching in prime
http://showcase.richfaces.org/richfaces/component-sample.jsf?demo=calendar&skin=blueSky

**Comment by tandraschko** [comment]
Read the docu, we have a flag to display the buttons.

**Comment by tandraschko** [comment]
Next time -> please use the forum ;)

**Comment by ankitacroit09** [comment]
Thanks for reply  @tandraschko 
I will put the request in Forum
