### ISSUE TITLE
Improve column header text on Reflow Mode on DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3095]
On reflow mode, the header title of columns are very difficult to find in the nested structures/components in f:facet. Therefore, users can use ariaHeaderText attribute on p:column.

Test code;
```
<p:column ariaHeaderText="TEST TEST">
   <f:facet name="header">
         <h:panelGroup>
            <h:outputText value="TEST TEST"/>
         </h:panelGroup>
         <h:selectOneMenu>
            ...
          </h:selectOneMenu>
   </f:facet>
...
</p:column>
```

**Comment by kukel** [comment]
What is the improvement...? I took a quick look at the commit and (sort) of understand it. A little 'description' to this issue would be appreciated! ;-)
