### ISSUE TITLE
Idea: Optimize cache usage like Facebook did

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#3098]
Last night I was reading how Facebook optimized 'cache performance' in browsers. I thought it might be something for PrimeFaces too. They effectively remove many of the 'revalidate' requests. Not sure how this would impact PrimeFaces, just thought I add the idea as a 'feature request'

https://code.facebook.com/posts/557147474482256/this-browser-tweak-saved-60-of-requests-to-facebook/

**Comment by tandraschko** [comment]
Hm? I don't understand it what we should do here.
If you would like to modify headers, you can simple add a servlet filter.
The expiration currently handles the JSF impl. Even not sure what the impls set exactly.

**Comment by kukel** [comment]
It's not just that (I 'know' these things' ;-)) but I should have added a summary, sorry for that. 

They (FB)  'drop' the real file names and use a hash of the file as the name. And since this 'hash' only changes if the real content changes, they can

1. set the  'ttl' for these 'resources' to indefinite 
2. if a 'revalidate' request does come in, they serve a 304 from the very front end servers without ever checking the resource.

This reduced their load significantly. 

But now I think of it, it might be a little too complex to realize for PrimeFaces and might be more of a thing for the JSF implementations or OmniFaces.

**Comment by Quix0r** [comment]
I have heard that Primefaces want to introduce bundling resources, then you only have one JS and one CSS request. It can still be combined with your idea. Or alternatively do "cache-busting" by adding a `?v=1.2.3` to all your static resource (like JS/CSS/favicon are). Then, on next change, increase ("bump") the version number and the browser "sees" a new URL. Basically almost the same what he wants. Example is my employer's customer's website. [http://bcmacademy.mybreev.com/](http://example.com)

Just look in the HTML reply and then you see such "cache-busting" URLs.

**Comment by tandraschko** [comment]
what do you mean? We already bundle resources (not 1file but only a few files) and also already append the version.
Also we won't provide a way to bundle only 1js and 1css. Use OmniFaces for this.

**Comment by open-gdsn** [comment]
Thomas is right...

**Comment by Quix0r** [comment]
Okay, sorry. Misunderstanding on my side. Now I need to find out where to add `omnifaces-3.0.jar`, `~/personal_domain/lib/` is causing an exception and NetBeans doesn't "see" those namespaces in there ... Okay, other tracker. ;-)

**Comment by melloware** [comment]
I am not sure anything can be done about this request and if you use OmniFaces CombinedResourceHandler along with Primefaces MOVE_SCRIPTS_TO_BOTTOM its about as optimized as we can make the JS and CSS files.
