### ISSUE TITLE
Icons broken on chrome

### ISSUE THREAD

**Issue by albfan** [primefaces/primefaces#3100]
## 1) Environment
- PrimeFaces version: 5.2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: jboss EAP 6.2
- Affected browsers: Chrome

## 2) Expected behavior

Output on firefox 57.0

![image](https://user-images.githubusercontent.com/220968/34256986-36d2dbc0-e658-11e7-93c4-0353204ea7d3.png)

## 3) Actual behavior

Using chrome 63.0

![image](https://user-images.githubusercontent.com/220968/34256910-d343eaae-e657-11e7-875a-a3edfecf0a6f.png)

After navigate back and forth in datadable I see (notice the border)

![image](https://user-images.githubusercontent.com/220968/34256894-c222df32-e657-11e7-92e1-e7f12ad8478a.png)

## 4) Steps to reproduce

Seems related with new version of chrome, but not sure. like a month ago it works

## 5) Sample XHTML

    <p:graphicImage alt="edit"    styleClass="ui-icon ui-icon-pencil"  title="edit"  />
    <p:graphicImage alt="close"  styleClass="ui-icon ui-icon-close"   title="close" />
    <p:graphicImage alt="check" styleClass="ui-icon ui-icon-check"  title="check" />

## 6) Sample bean

Do not apply

**Comment by tandraschko** [comment]
i think ui-icon should be applied on a span.

**Comment by albfan** [comment]
Thanks @tandraschko that fixes the problem
