### ISSUE TITLE
Step: support VISITED_ITEM_CLASS in Readonly Mode

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#3101]
## 1) Environment
- PrimeFaces version: Any
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Bi
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior

The readonly defines whether items would be clickable or not. We would like to style the visited steps differently in readonly mode  without user having to option to click or see a hand cursor.

## 3) Actual behavior
supports only Steps.ACTIVE_ITEM_CLASS & Steps.INACTIVE_ITEM_CLASS in readonly mode

StepsRenderer - encodeItem

```java
if (steps.isReadonly()) {
            itemClass = (index == activeIndex) ? Steps.ACTIVE_ITEM_CLASS : Steps.INACTIVE_ITEM_CLASS;
        }
        else {
            if (index == activeIndex) {
                itemClass = Steps.ACTIVE_ITEM_CLASS;
            }
            else if (index < activeIndex) {
                itemClass = Steps.VISITED_ITEM_CLASS;
            }
            else {
                itemClass = Steps.INACTIVE_ITEM_CLASS;
            }
        }
```
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by melloware** [comment]
@ravihariharan I am confused on what you actually need done here?

**Comment by ravihariharan** [comment]
@melloware We have readonly step and I wanted to style the Steps.VISITED_ITEM_CLASS in  readonly case.

![image](https://user-images.githubusercontent.com/15189434/67098582-80c9cb00-f18a-11e9-95a7-d419a612c12c.png)

**Comment by tandraschko** [comment]
AFAICS it should be possible to style it?
Please provide a sample xhtml and explain what doesnt work to style exactly.

**Comment by melloware** [comment]
@ravihariharan Are you going to submit a PR or should I close this ticket?

**Comment by melloware** [comment]
Closing this ticket.  Can reopen if PR is provided.
