### ISSUE TITLE
Static resources in Primefaces 6.1.10 are not very performant !

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#3102]
Hello !

I am currently using the new Primefaces 6.1.10 and tested the current web-performance 
by simple using the Google Chrome's PageSpeed Analyzer.

_The analyzer gives me a bad result in the following things which could easily be solved:_
![pagespeed](https://user-images.githubusercontent.com/652355/34287737-7b709132-e6e9-11e7-93ae-b8149518e716.png)

You can also take the current Primefaces Showcase as Example for that 
which also shows me a very bad result for a demo site :
[https://www.primefaces.org/showcase/](https://www.primefaces.org/showcase/)

![pagespeed_primefaces](https://user-images.githubusercontent.com/652355/34288858-dac724f6-e6ef-11e7-9b65-b21883ca41d9.png)

**_To solve this performance problem's please do/check the following things:_**

**1.) Enable compression:** / **Minify JavaScript**
Please enable compress/minimize all your JavaScript/CSS-Stylesheets in the 
Elite/Pro Build because they are not compressed in the File 
**"primefaces-6.1.10.zip"** as Google PageSpeed right says:

- Compressing /javax.faces.resource/components.js?ln=primefaces&v=6.1.10 could save 311.2KiB (79% reduction).
- Compressing /javax.faces.resource/jquery/jquery-plugins.js?ln=primefaces&v=6.1.10 could save 176.4KiB (72% reduction).
- Compressing /javax.faces.resource/jquery/jquery.js?ln=primefaces&v=6.1.10 could save 54.5KiB (65% reduction).
- Compressing /javax.faces.resource/core.js?ln=primefaces&v=6.1.10 could save 20.9KiB (68% reduction).

A additional way could also be to use minimized/compressed resource files
if the project-state is set to Production:
```
  <context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Production</param-value>
  </context-param>
```
If the user set the production state to "Production" you can render using the minimized version
 ( **components.js.min** ) and otherwise the debuggeable version (**components.js**)

**2.) Defer parsing of JavaScript:** / **Optimise the order of styles and scripts**
I think we already solved that with the ticket: #2979 
Which will be solved with the coming Primefaces 6.2 version.

**3.) Remove query strings from static resources**
Please do not use query's for rendering static resources like script's/images/stylesheet's !
This is a bad practice because all proxy server's, browser's will not cache this resources 
but they should be cached as they are static !

![pagespeed_query](https://user-images.githubusercontent.com/652355/34288513-0356b6fe-e6ee-11e7-8b62-51f54696a180.png)

Instead of rendering a static resource(script's/images/stylesheet's) like that:
**/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.1.10**

you should render it like that if you really need the version numer as "parameter", but static:
**/javax.faces.resource/primefaces/6.1.10/core.js.xhtml**

or if you don't really need the version number you can generate the 
static version like that :
**/javax.faces.resource/primefaces/core.js.xhtml**

**Comment by tandraschko** [comment]
Please don't mix several issues in one ticket here ;)

1) it's only related to elite, it would be great if you could create a new issue here. Probably the build didn't minify correctly.
2) fixed
3) will not be fixed in the near future, please modify this issue to only match 3)

**Comment by Rapster** [comment]
FYI: Recently, I had to create a release version for my company using `mvn clean install -Prelease -Dmaven.javadoc.skip=true -Dgpg.skip=true`, the build results to an error due to yui plugin trying to minify the sources. Upgrading yui to 1.5.1 made it work

**Comment by ssibitz** [comment]
**For number 3.)** 
I currently use the Omnifaces CDNResourceHandler to redirect to the external CDN-server's or the static version on the own server of e.g. jquery.min.js
[http://showcase.omnifaces.org/resourcehandlers/CDNResourceHandler](http://showcase.omnifaces.org/resourcehandlers/CDNResourceHandler)

So when you will not change it i will let this CDN-Handler enabled in my project :-(


**So i think only the point 1.) is really relevant and should be fixed -** 
And please also don't include static images (like for buttons, background's,...)
in the build instead of using SVG-Graphics or Font's...
This is really a performance issue because our customer's not always having
a high speed internet where the first call takes time when unnessesarry data's are transfered...

**Comment by melloware** [comment]
I will open a PRO issue asking for the 6.1.11 Elite release be compressed.

**Comment by tandraschko** [comment]
Will close this issue now. As melloware will handle 1) via PRO, feel free to create a own issue for 3).

**Comment by ssibitz** [comment]
I have only an ELITE-account from my company,
so moving it to a PRO-account doesn't make sense for me 
as i have seen now the Issue with the uncompressed static resources are only
on the Primefaces-Project and not in the Primefaces-Extensions-Project.

So i will make a separate Ticket for handling the first point of this ticket !

**Comment by tandraschko** [comment]
i think melloware already openend a ticket with HIS PRO account ;)

**Comment by melloware** [comment]
Here was the answer I got on my PRO account 

> We always use "mvn clean install -P release" command to release PrimeFaces elite versions. I checked component.js, core.js etc. in version jars. They are as expected. I attached a screenshot.

So he seems to think they are compressed just like the Community releases but that is definitely not what I have seen all the time.
