### ISSUE TITLE
Rethink document.ready vs plain JS vs MOVE_SCRIPTS_TO_BOTTOM

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3109]
Successor ticket of #3073 and #3075

How are our components currently rendered:
> body

>> DOM component A

>>> DOM of childs
>>> script of childs

>> script component A

This actually means that the DOM is already ready when our script is executed. 
Some components use document.ready, some not.

So, what actually does document.ready? It moves the script initialization "emulated" to the end of the bottom.
It's the same effect like with MOVE_SCRIPTS_TO_BOTTOM, just that the scripts are really at the bottom and not "emulated".

So, the problem is that we have a mix of all...

- Some components uses widget inits WITHOUT document.ready
- Some components uses widget inits WITH document.ready
- MOVE_SCRIPTS_TO_BOTTOM can be used, so all scripts become native "document.ready"

**Comment by tandraschko** [comment]
WDYT @mertsincan @cagataycivici? @melloware @jxmai @Rapster?

Should we init our widget scripts always with document.ready or not?
I think there is no reason for doing is sometimes with and sometimes without, which is sadly the current state.
document.ready is more flawless and speeds up the visible page rendering. The small disadvantage could be a little bit of flickering like mentioned here #3075. But this must be fixed by the component itself.

MOVE_SCRIPTS_TO_BUTTOM is then actually just a improvement over the default behavior. It "converts" the virtually document.ready to a a real one. Also script includes are moved to the bottom and speed up a lot.

**Comment by melloware** [comment]
@tandraschko I support this.  I know I am newer to this but I have always been confused by why some widgets use initWithDomReady() and some widgets do not.  I would think we would want them all to behave the same way unless there was a reason a particular component should not.

**Comment by tandraschko** [comment]
we now always use $(function(){...});
