### ISSUE TITLE
Add path definition of localization javascript resource to web.xml

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#311]
When using primefaces localization through javascript files I have a few choices on how to include the javascript.
1. in template once - (unnecessary resource to load if no localized component is used)
2. on each page that uses a localized component such as `calendar`
3. whenever I use such a component and add `target="head"` to the resource
4. use JSF convenient local message lookup like: `<script type="text/javascript>#{msg.primefacesLocale}</script>`

What about a new feature of a locale dependent path as a `context-param` to the resource in `web.xml` so that primefaces can load this file just when it is needed.

Something similar to java local resource bundle loading.

**Web.xml**

```
<context-param>
    <param-name>primefaces.locale</param-name>
    <param-value>/resources/js/primefacesLocale.js</param-value>
</context-param>
```

**Folder**

`/resources/js/`
- `primeFacesLocale.js`
- `primeFacesLocale_en.js`
- `primeFacesLocale_de.js`

This solves the problem of unnecessary loading and is easier to maintain for developers.

**Comment by kukel** [comment]
Feel free to create a patch for this. I doubt that PF will provide a solution for this (and hope they will spend time on other issues). For the simple reason that your point 1 is for me a non-issue since this resource will be cached if loaded correctly. The solution you propose is therefor (imo) a premature optimization.

**Comment by cagataycivici** [comment]
We don't keep locales inside PrimeFaces and simple EL expression should do the trick in resource include. Also JSF APIs provide locale information from viewroot no need for a context param in the first place.
