### ISSUE TITLE
MoveScriptsToBottom: doesn't need to render document.ready handlers

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3110]

**Comment by tandraschko** [comment]
@ssibitz @melloware @jxmai Would you please give it a try in your applications?
Small enhancement - we don't need to render document.ready handlers when all scripts are already at the bottom...
and jfyi: i renamed to setting to MOVE_SCRIPTS_TO_BOTTOM

**Comment by melloware** [comment]
I will give this a shot and let you know.

**Comment by melloware** [comment]
@tandraschko  OK I tried this in the Extensions Showcase and now I am getting a JS error "Uncaught SyntaxError: Unexpected token }" on this line...

```javascript
pf.cw("ExtLayout","fullLayoutWidget",{id:"fpl",clientState:false,forTarget:"body",serverState:false,options:{"defaults":{"resizable":true,"closable":true,"resizeWhileDragging":true,"resizeWithWindow":false,"slidable":false},"north":{"size":60,"resizable":false,"closable":false,"spacing_open":0},"south":{"size":28,"resizable":false,"closable":false,"spacing_open":0},"west":{"size":210,"minSize":180,"maxSize":500},"east":{"size":448,"minSize":180,"maxSize":650,"children":{"south":{"size":"70%","minSize":60},"center":{"minHeight":60}}},"center":{"minHeight":60,"resizable":false,"closable":false,"resizeWhileDragging":false,"minWidth":200}},behaviors:{resize:function(ext,event) {}}},true);});
```

And I think the PF showcase Layout is having a similar issue:  https://www.primefaces.org/showcase/ui/panel/layout/element.xhtml

**Comment by jxmai** [comment]
I can confirm this issue (https://github.com/primefaces/primefaces/issues/3110#issuecomment-354179943) when I was testing an application. The whole page will be frozen when using primefaces extension layout.

![image](https://user-images.githubusercontent.com/10467831/34394521-652b7cf4-eb1f-11e7-8e54-ecd7dbce2a82.png)

**Comment by jxmai** [comment]
Furthermore, even when I turn off the `move_script_to_bottom` feature, some similar errors can still occur under certain circumstances.

```
VM4793:1 Uncaught SyntaxError: Unexpected token }
    at p (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:2)
    at Ja (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:3)
    at r.fn.init.replaceWith (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:3)
    at Object.updateElement (core.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:1021)
    at Object.doUpdate (core.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:1684)
    at Object.handle (core.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:1574)
    at Object.<anonymous> (core.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:1442)
    at i (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:2)
    at Object.fireWith [as resolveWith] (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:2)
    at A (jquery.js.xhtml?ln=primefaces&v=6.2-SNAPSHOT:4)
```

**Comment by tandraschko** [comment]
DOn't know about the PFE layout but PF layout but it's broken - also without this option because: $N.selector is undefined

**Comment by tandraschko** [comment]
and to be honest @melloware, i don't think that the PFE LayoutRenderer is using the WidgetBuilder correctly....
It uses the WB to initialize it but not for finish it.

**Comment by tandraschko** [comment]
Same for the Ext Tooltip....

**Comment by melloware** [comment]
@tandraschko the PFE Layout and Tooltip were both like that before I just converted them to using WidgetBuilder.  But I noticed teh WidgetBuilder.finish() does not close some scripts like ToolTip and Layout with...

`wb.append("},true);});");`

I assumed they were being closed like that with the "true" value for some reason but I can't find any explanation so I left them like that.  I can play around with it tomorrow to see if I can remove that last "true" but when I did before I swear the component broke.

**Comment by tandraschko** [comment]
I fixed both, please have a look
not sure if other components breaks, too but the reason is always to use the WB only for init but not for finish

**Comment by tandraschko** [comment]
Also NOTE: this would also break without MoveScriptsToBottom as we can't render the document.ready handler anymore on ajax requests as they now run async with jquery3 (which could also explain @jxmai behavior)

**Comment by ssibitz** [comment]
I will try the current primefaces 6.2-SNAPSHOT and give a feedback...

**Comment by melloware** [comment]
Great I am going to check it out and test ALL the PFE components today and let you know how it goes.

**Comment by melloware** [comment]
@tandraschko PFE fully tested and I had to fix BlockUI and FluidGrid the same way but I am happy to report the entire showcase an all functionality is 100% working!

**Comment by tandraschko** [comment]
Great! and great that would could the codebase in this way! ;)
