### ISSUE TITLE
Discuss jquery-plugins usage

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3113]
Currently we have a big JS file with much jquery plugins
some plugins are used by core.js (browser, cookie, ...) - some are (almost) used by every components (draggable, effects, ...)

We should evaluate the following:
1) in general, it would be a good step to just move plugins from jquery.ui to their PF components (like datepicker, slider). It's much cleaner.
2) if 1) is done - how big is the jquery-plugins file? Can we add it globally or even just merge it with core.js? It should just contain very global/core plugins anymore.
3) second approach would be to add core-plugins (browser, cookie) directly to core.js - components which requires jquery-ui or other plugins, can simple add the dependency to jquery-plugins.js

**Comment by melloware** [comment]
@tandraschko ..
1. I like this idea. Unless a JS is used by more than one component for example moment.js...it should be moved to its component (datepicker, timepicker etc).  It makes the code more organized IMHO.

2. This part I am not as sure about whether merging into core.js is a good idea.  It would be a good idea if like you said if it truly is used by a majority of components then I say its OK.

**Comment by tandraschko** [comment]
Lets close it for now. We didn't had time and calender.js is probably deprecated.
