### ISSUE TITLE
Datatable incell 'editingRow' shows 'output' facet after change

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#312]
Having a datatable with incell editing and forcing the displaying of the input components using `editingRow="true"` i encounter strange behavior.

After changing the value and losing focus of the component the `output` facet is displayed instead of the `input` facet. 

Updating the table using ajax all `input` facets are shown by default as intended.

```
<p:dataTable editMode="cell" editingRow="true">
    <p:cellEditor>
        <f:facet name="output">
            <h:outputText value="#{var.value}"/>
        </f:facet>
        <f:facet name="input">
            <h:inputText value="#{var.value}"/>
        </f:facet>
    </p:cellEditor>
</p:dataTable>
```

**Workaround:**

Duplicate markup of `input` in `output` facet.

**Comment by kukel** [comment]
PF version?

**Comment by djmj** [comment]
Community 5.2

**Comment by cagataycivici** [comment]
editingRow is used for editMode="row" not designed for cell editing. Also in your case, you can just put input components inside datatable if you are going to show all as editable. No need for cell editing feature in that case.
