### ISSUE TITLE
TabView: prevent TabChange event during onstart 

### ISSUE THREAD

**Issue by munnyhp** [primefaces/primefaces#3120]
The application has multiple tabs with the following requirement.
On Tab change -
1) Validate the tab. If there are any errors, show the validation messages.
2) If no validations, auto save the content.
3) Display new tab.

We have achieved this using primefaces 6.1 TabView.
For example, there are 3 tabs - Tab1, Tab2 , Tab3.
User is on Tab1 and clicks on Tab2, verifying if there are validations errors and returning false in tabchange onstart event. This will successfully cancel the tab change event and the user stays on Tab1.
Later after resolving validation errors, the user again tries to click on Tab2. This is where the issue is and Tab2 cannot be clicked. Nothing happens when it is clicked.
But we can click on Tab3 and navigate to it.

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: WebSphere Liberty Server + 16.0.0.4
- Affected browsers: IE 11, Firefox

## 2) Expected behavior

User should be able to re-click on Tab2 after tab change event is cancelled.

## 3) Actual behavior

Not able to click on Tab2 once the tabchange event is cancelled.

## 4) Steps to reproduce

1) Modify the data on Tab1.
2) Click on Tab2 - Tabchange event will be cancelled and stays on Tab1.
3) Resolve the validation issue.
4) Click on Tab2 again.

## 5) Sample XHTML
<ui:composition template="/templates/main.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <ui:define name="pageTitle">
        <h3 style="margin: 0">Welcome to  - Tabs Prototype</h3>
    </ui:define>
    <ui:define name="content">
        <h:form id="prototype" prependId="false" enctype="multipart/form-data">
			<p:panel id="tabsPanel1" styleClass="panelgrid-row approval-content-panel" >
				<p:tabView id="tabViewP" activeIndex="#{prototypeView.activeIndex}" 
					dynamic="true" cache="false"  widgetVar="tabView" >
					 <p:ajax event="tabChange" onstart="return testCancel();" 
						listener="#{prototypeView.tabInitMethod('')}" oncomplete=""/>
					<p:tab id="Tab1" title="Tab1" >
						<p:messages autoUpdate="true" globalOnly="true" showSummary="true" closable="true" />
						<p:panel id="Panel2" style="border:none;">
							<p:message for="description" />
							<input type="hidden" id="data_changed" name="data_changed" value="N"/>
							<p:row>
				                <p:column>
				                    <p:spacer width="25" />
				                </p:column>
				                <p:column colspan="1" style="text-align:right;">
				                    <p:outputLabel value="Description:" />
				                </p:column>
				                <p:column colspan="3">
				                    <p:inputTextarea id="description" rows="2" cols="73"
				                        maxlength="75" counter="remaining_chars"
				                        counterTemplate="{0} characters remaining."
				                        value="#{prototypeView.description}"
				                        onchange="document.getElementById('data_changed').value='Y';"
				                        required="true">
				                        <f:validateLength minimum="10"/>
				                     </p:inputTextarea>
				                    <h:outputText id="remaining_chars" />
				                </p:column>
				            </p:row>
						</p:panel>
						<p:panel id="Panel3" styleClass="text-align-center" style="border:none;">
							<p:commandButton type="submit" value="Save" widgetVar="saveTab1" 
											 actionListener="#{prototypeView.saveTab1}"
											 update="Panel2" />
							<p:remoteCommand name="submitJS" actionListener="#{prototypeView.saveTab1}"  update="Panel2" />
						</p:panel>
					</p:tab>
					<p:tab id="Tab2" title="Tab2" >
						<p:panel id="Panel4" style="border:none;">
							<p:outputLabel value="This is in Tab 2." />
						</p:panel>
					</p:tab>
					<p:tab title="Tab3" id="Tab3" >
						<p:panel id="Panel5" style="border:none;">
							<p:outputLabel value="This is in Tab 3." />
						</p:panel>
					</p:tab>
				</p:tabView>
			</p:panel>
		</h:form>
    </ui:define>

</ui:composition>

function testCancel() {

	if(document.getElementById('data_changed')!= null && document.getElementById('data_changed').value == "Y") {
		submitJS();
		return false;
	} else {
		return true;
	}
}

## 6) Sample bean
/**
 * 
 */
package gov.usps.efms.energy.bean;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.springframework.stereotype.Component;

import gov.usps.efms.energy.util.EFMSLogger;
import gov.usps.efms.util.scope.ViewScope;

@Component
@ViewScope
public class PrototypeView {

	private Long activeIndex;
	private String description;
	
	@PostConstruct
	public void init() {

		EFMSLogger.debug("In init");

	}
	
	public void tabInitMethod(String str) {

		switch (getActiveIndex().toString()) {
		// Energy Info Tab
			case "0": {
				EFMSLogger.debug("In Tab1.");
				break;
			}
			// Audit Tab
			case "1": {
				EFMSLogger.debug("In Tab2.");
				break;
			}
			// Opportunity Tab
			case "2": {
				EFMSLogger.debug("In Tab3.");
				break;
			}
		}

	}
	
	public void saveTab1() {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Tab1 saved", null));
	}
	public Long getActiveIndex() {
		return activeIndex;
	}

	public void setActiveIndex(Long activeIndex) {
		this.activeIndex = activeIndex;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}

**Comment by jxmai** [comment]
The sample is invalid. Please spend some effort on preparing a sample or you probably need to analyse the problem yourself. Please see https://stackoverflow.com/help/mcve

**Comment by tandraschko** [comment]
Please provide a small and simple as possible example. We don't have EFMSLogger or any spring stuff. The best is way is to clone the primefaces-test project like stated in the issue template.

**Comment by munnyhp** [comment]
I've removed code referring other frameworks.
Please try now.

# **Sample bean**
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

@SessionScoped
@ManagedBean
public class PrototypeView {

	private Long activeIndex;
	private String description;
	
	@PostConstruct
	public void init() {

		System.out.println("In init");

	}
	
	public void tabInitMethod() {

		switch (getActiveIndex().toString()) {
		// Energy Info Tab
			case "0": {
				System.out.println("In Tab1.");
				break;
			}
			// Audit Tab
			case "1": {
				System.out.println("In Tab2.");
				break;
			}
			// Opportunity Tab
			case "2": {
				System.out.println("In Tab3.");
				break;
			}
		}

	}
	
	public void saveTab1() {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Tab1 saved", null));
	}
	public Long getActiveIndex() {
		return activeIndex;
	}

	public void setActiveIndex(Long activeIndex) {
		this.activeIndex = activeIndex;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}

# **Sample XHTML**
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:b="http://bootsfaces.net/ui"      
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
      
<f:view contentType="text/html">

<h:head>
  <title><h:outputText value="Welcome to  - Tabs Prototype" escape="false"/></title>
  
<script type="text/javascript">
/*<![CDATA[*/
function testCancel() {
	
	if(document.getElementById('data_changed')!= null && document.getElementById('data_changed').value == "Y") {
		alert("data_changed " + document.getElementById('data_changed').value);
		submitJS();
		return false;
	} else {
		return true;
	}
}
/*]]>*/
</script>
</h:head>
<h:body>

        <h:form id="prototype" prependId="false" enctype="multipart/form-data">
			<p:panel id="tabsPanel1" styleClass="panelgrid-row approval-content-panel" >
				<p:tabView id="tabViewP" activeIndex="#{prototypeView.activeIndex}" 
					dynamic="true" cache="false" >
					 <p:ajax event="tabChange" onstart="return testCancel();" 
						listener="#{prototypeView.tabInitMethod()}" />
					<p:tab id="Tab1" title="Tab1" >
						<p:messages autoUpdate="true" globalOnly="true" showSummary="true" closable="true" />
						<p:panel id="Panel2" style="border:none;">
							<p:message for="description" />
							<input type="hidden" id="data_changed" name="data_changed" value="N"/>
							<p:row>
				                <p:column>
				                    <p:spacer width="25" />
				                </p:column>
				                <p:column colspan="1" style="text-align:right;">
				                    <p:outputLabel value="Description:" />
				                </p:column>
				                <p:column colspan="3">
				                    <p:inputTextarea id="description" rows="2" cols="73"
				                        maxlength="75" counter="remaining_chars"
				                        counterTemplate="{0} characters remaining."
				                        value="#{prototypeView.description}"
				                        onchange="document.getElementById('data_changed').value='Y';"
				                        required="true">
				                        <f:validateLength minimum="10"/>
				                     </p:inputTextarea>
				                    <h:outputText id="remaining_chars" />
				                </p:column>
				            </p:row>
						</p:panel>
						<p:panel id="Panel3" styleClass="text-align-center" style="border:none;">
							<p:commandButton type="submit" value="Save" widgetVar="saveTab1" 
											 actionListener="#{prototypeView.saveTab1}"
											 update="Panel2" />
							<p:remoteCommand name="submitJS" actionListener="#{prototypeView.saveTab1}"  update="Panel2" />
						</p:panel>
					</p:tab>
					<p:tab id="Tab2" title="Tab2" >
						<p:panel id="Panel4" style="border:none;">
							<p:outputLabel value="This is in Tab 2." />
						</p:panel>
					</p:tab>
					<p:tab title="Tab3" id="Tab3" >
						<p:panel id="Panel5" style="border:none;">
							<p:outputLabel value="This is in Tab 3." />
						</p:panel>
					</p:tab>
				</p:tabView>
			</p:panel>
		</h:form>

</h:body>
</f:view>
</html>

**Comment by munnyhp** [comment]
Hi Tandaraschko,

Can you pls suggest if there is any other way to prevent tab change on condition until this is fixed in Primefaces? And also, do you know if this will be fixed in next version release?

Thanks!

**Comment by tandraschko** [comment]
I didn't even checked the source of the problem here. NOTE: i just do this here in my free time and currently i have higher prioritized items on my list.
If you need help now, i would suggest you to create a support case (aka PrimeFaces PRO)

**Comment by melloware** [comment]
I think to boil this down if you `return false` from the TabChange `onstart` method you want the tab NOT to change.

**Comment by melloware** [comment]
You an already do this now.  Just move your JS code from the `onstart` of the AJAX call to the TabView client side if you want to prevent Tab Change before it changes the tab and fires the event.

```xml
<p:tabView onTabChange="return false;">
```

**Comment by zealoterrol** [comment]
@munnyhp https://stackdev.space/questions/validation-of-jsf-field-with-minimum-length-requirement
