### ISSUE TITLE
After clearing a p:inputText, the previous value is displayed

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#3124]
## 1) Environment
PrimeFaces version: 6.1.9
Does it work on the newest released PrimeFaces version? Version? No (checked with 6.1.9)
Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
Application server + version: WebLogic 12.2.1
Affected browsers: Chrome

## 2) Expected behavior
User removes value from p:inputText with required=true -> p:inputText is invalid and remains empty 

## 3) Actual behavior
User removes value from p:inputText with required=true -> p:inputText is invalid but is filled with previous value 

## 4) Steps to reproduce
a) set javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL=true in web.xml
b) create form with two p:inputText, both of them required=true
c) enter some text in first and second p:inputText and submit -> values are accepted, both p:inputText are valid
d) clear first p:inputText and submit -> first p:inputText stays empty and becomes invalid (so far so good)
e) keep first p:inputText empty and also clear second p:inputText and submit -> second p:inputText is reset to previous value and is invalid

## 5) Sample XHTML
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<head>
<title>Demo</title>
</head>
<body>
	<h:form id="myform">
		<p:inputText id="one"  value="#{demoBean.one}" required="true"/>
		<p:message for="one"/> 	
		<p:inputText id="two"  value="#{demoBean.two}" required="true"/>
		<p:message for="two"/>
		<p:commandButton value="submit" actionListener="#{demoBean.doSubmit()}" /> 		

	</h:form>
</body>
</html>

## 6) Sample bean
package local.jsfpfdemo;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.validation.constraints.Size;

import java.io.Serializable;

@Named
@ViewScoped
public class DemoBean implements Serializable {
	private static final long serialVersionUID = 1L;
	String one;	
	String two;
	public String getOne() {
		return one;
	}
	public void setOne(String one) {
		this.one = one;
	}
	public String getTwo() {
		return two;
	}
	public void setTwo(String two) {
		this.two = two;
	}	
        public void doSubmit() {
	}
}

**Comment by tandraschko** [comment]
Is it the same as #2821?

**Comment by ghost** [comment]
It it is a similar problem, but not the same. 

In have debugged the method org.primefaces.util.ComponentUtils.getValueToRender(FacesContext, UIComponent, Object). As far as I understand the following part that is responsible for keeping the empty field empty: 
...
                if (config.isInterpretEmptyStringAsNull()
                        && submittedValue == null
                        && !input.isLocalValueSet()
                        && context.isValidationFailed()
                        && !input.isValid()) {
                    return null;
                }
..

In step d) the method isLocalValueSet() returns false and therefore null is returned
In step e) the method isLocalValueSet() returns true and we continue to another part that returns the previous value.
I do not understand the different behaviour of isLocalValueSet.

**Comment by tandraschko** [comment]
Please see: https://github.com/primefaces/primefaces/issues/2821
In JSF 2.3 the value is always cleared, ignoring config.isInterpretEmptyStringAsNull().

I think we have to align our behavior here in 6.3.

**Comment by ghost** [comment]
Thank you for looking into this.

I guess your statement concerning JSF 2.3 is referring to the following change: https://github.com/javaserverfaces/mojarra/commit/0813ee1fdef418e47ef03ced7d57a1abe4c2bf54

That looks promising to me: Running this scenario in JSF 2.3 the method javax.faces.component.UIInput.getSubmittedValue() should return "" (instead of null) and then  org.primefaces.util.ComponentUtils.getValueToRender(FacesContext, UIComponent, Object) should also return "" (instead of the old local value), and that should solve the issue.
For this scenario, I do not see why primefaces must be changed, but there might be other scenarios to consider.

Unfortunately I cannot migrate to JSF 2.3 immediately. Instead I am considering a workaround (some listener that resets the local value on invalid fields) until we can migrate JSF 2.3 and/or Primefaces 6.3.

**Comment by tandraschko** [comment]
Yep, maybe we even don't have to change our code. I will check that after 6.2. As we release RC1 this week, we can't change such a behavior anymore.

**Comment by tandraschko** [comment]
I just tested PF with both Mojarra 2.3 and MyFaces 2.3 and the behavior is exactly the same when using a simple example (inputText with attached f:validateLength - also with avax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL true/false.

So will close this issue for now.
