### ISSUE TITLE
LineChartModel: weird visualization of negative values

### ISSUE THREAD

**Issue by thomas-mc-work** [primefaces/primefaces#3126]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? no
- Application server + version: payara 4.1.1.171
- Affected browsers: chromium, firefox

## 2) Expected behavior

The areas with negative values should be rooted at the x-Axis, not at the bottom of the canvas.
Bars show the same behavior.

My expectation:

![expectation](https://peltiertech.com/wp-content/img200806/InvertChart15.png)

## 3) Actual behavior

![screenshot_2018-01-03_14-12-26](https://user-images.githubusercontent.com/6542498/34521845-3a9ecf56-f090-11e7-9e6b-70c940514495.png)

## 4) Steps to reproduce

@see steps 5 & 6

## 5) Sample XHTML

    <?xml version='1.0' encoding='UTF-8' ?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:h="http://xmlns.jcp.org/jsf/html"
          xmlns:p="http://primefaces.org/ui">
        <h:head>
            <title>enterflix</title>
            <h:outputStylesheet name="app/style.css" />
            <h:outputScript name="app/script.js" />

            <link rel="shortcut icon" href="resources/favicon.ico" type="image/x-icon"/>
            <link rel="icon" href="resources/favicon.ico" type="image/x-icon"/>
            <link rel="icon" type="image/png" sizes="32x32" href="resources/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="96x96" href="resources/favicon-96x96.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="resources/favicon-16x16.png"/>
            <meta name="theme-color" content="#ffffff"/>
        </h:head>
        <h:body>
            <div>TODO write content</div>

            <p:chart type="line" model="#{chartView.areaModel}" style="height:300px" />

        </h:body>
    </html>

## 6) Sample bean

    import java.io.Serializable;
    import javax.annotation.PostConstruct;
    import javax.faces.bean.ManagedBean;
    import org.primefaces.model.chart.Axis;
    import org.primefaces.model.chart.AxisType;
    import org.primefaces.model.chart.CategoryAxis;
    import org.primefaces.model.chart.LineChartModel;
    import org.primefaces.model.chart.LineChartSeries;

    @ManagedBean
    public class ChartView implements Serializable {

        private LineChartModel areaModel;

        @PostConstruct
        public void init() {
            createAreaModel();
        }

        public LineChartModel getAreaModel() {
            return areaModel;
        }

        private void createAreaModel() {
            areaModel = new LineChartModel();

            LineChartSeries boys = new LineChartSeries();
            boys.setFill(true);
            boys.setLabel("Boys");
            boys.set("2004", 120);
            boys.set("2005", -100);
            boys.set("2006", -44);
            boys.set("2007", 150);
            boys.set("2008", 25);

            LineChartSeries girls = new LineChartSeries();
            girls.setFill(true);
            girls.setLabel("Girls");
            girls.set("2004", 52);
            girls.set("2005", -60);
            girls.set("2006", -110);
            girls.set("2007", 90);
            girls.set("2008", 120);

            areaModel.addSeries(boys);
            areaModel.addSeries(girls);

            areaModel.setTitle("Area Chart");
            areaModel.setLegendPosition("ne");
            areaModel.setStacked(true);
            areaModel.setShowPointLabels(true);

            Axis xAxis = new CategoryAxis("Years");
            areaModel.getAxes().put(AxisType.X, xAxis);
            Axis yAxis = areaModel.getAxis(AxisType.Y);
            yAxis.setLabel("Births");
            yAxis.setMin(-200);
            yAxis.setMax(300);
        }
    }

**Comment by dmatej** [comment]
Negative values also have color of positive values (I use line graph), maybe it is the same issue.

**Comment by melloware** [comment]
Please try and recreate with raw JqPlot.  http://www.jqplot.com/examples/line-charts.php

If you get the same behavior then its not a PF issue its a JqPlot issue.

**Comment by thomas-mc-work** [comment]
There is an attribute that can be set to achieve the behaviour: `fillToZero: true` (http://www.jqplot.com/examples/area.php)

I suggest to preset it to `true` per default. Everything else doesn't look very intuitive in my eyes.

At least adding a way to set it in the respective classes would be great (`LineChartSeries`, …). Is there a way to pass through an attribute? Like for custom HTML5 attributes that are unknown to JSF/Primefaces?

**Comment by thomas-mc-work** [comment]
Well, it seems like at the moment it's impossible to add this feature in a sane way since the classes are not very extensible/flexible. Here is a quick and dirty workaround for everyone who wants to have it now:

    import java.io.IOException;
    import java.io.StringWriter;
    import java.io.Writer;
    import org.primefaces.model.chart.LineChartSeries;

    public class LineChartSeriesZeroed extends LineChartSeries {

        @Override
        public void encode(Writer writer) throws IOException {
            final Writer childWriter = new StringWriter();
            super.encode(childWriter);

            final String jsonString = childWriter
                    .toString()
                    .replace("LineRenderer,fill:true,", "LineRenderer,fillToZero:true,fill:true,");

            writer.write(jsonString);
        }
    }

The `encode` method of the `LineChartSeries` class is simply overridden and the resulting json object config string will be extended by the required configuration attribute.

**Comment by tandraschko** [comment]
Isn't it possible via the extender functionality?

**Comment by melloware** [comment]
@thomas-mc-work yes use the Extender like this...

https://stackoverflow.com/questions/30644676/how-to-use-line-chart-extender-attribute-in-primefaces-5-2

That is the whole reason the Extender functionality exists.

**Comment by melloware** [comment]
@thomas-mc-work once you get your solution working with the Extender can you post it here and then close this ticket please?

**Comment by thomas-mc-work** [comment]
Thanks for that hint!

Finally the model definition is extended by an extender reference:

    final LineChartModel model = new LineChartModel();
    model.setExtender("chartExtender");
    …

And somewhere in my JavaScript I've defined the related function:

    function chartExtender() {
        // this way the existing config is extended instead of replacing it as seen in the documentation
        this.cfg.seriesDefaults.fillToZero = true;
    }

**Comment by melloware** [comment]
Thanks for posting your solution and closing the ticket.  Glad we could help.
