### ISSUE TITLE
SelectItem: Add passthrough support on f:selectItem and f:selectItems

### ISSUE THREAD

**Issue by Willyisback** [primefaces/primefaces#3132]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? not tested
- Application server + version: Jetty Server
- Affected browsers: Chrome, Firefox
- Tested with primefaces/primefaces-test

## 2) Expected behavior
- selectItem with passthrough attribute should be attached to list elements and/or options

## 3) Actual behavior
- no passthrough on list elements

## 4) Steps to reproduce
- @see steps 5

## 5) Sample XHTML
```xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
    <title>PrimeFaces Test</title>
</h:head>

<h:body>

    <h1>#{testView.testString}</h1>

    <p:selectOneMenu>
        <f:selectItem itemValue="1" itemLabel="1" pt:data-name="Test1"/>
        <f:selectItem itemValue="2" itemLabel="2" pt:data-name="Test2"/>
        <f:selectItem itemValue="3" itemLabel="3" pt:data-name="Test3"/>
        <f:selectItem itemValue="4" itemLabel="4" pt:data-name="Test4"/>
        <f:selectItem itemValue="5" itemLabel="5" pt:data-name="Test5"/>
    </p:selectOneMenu>

</h:body>
</html>
```

But works with h:selectOneMenu!

**Comment by tandraschko** [comment]
A PR would be great.

**Comment by cnsgithub** [comment]
I just tried to implement this, however it seems to be quite hard since the default JSF SelectItem does not offer additional values other than description, label and value. So getting the passtrough values at the interesting spot (SelectOneMenuRenderer, encodeItem) is not possible with the current implementation. Maybe a different approach would be to create new attributes for the <p:selectOneMenu> tag?

**Comment by melloware** [comment]
Here was the solution BootsFaces went with:

https://github.com/TheCoder4eu/BootsFaces-OSP/issues/667

https://github.com/TheCoder4eu/BootsFaces-OSP/commit/d29f815fbf5a8f50ffe261f3a89b6e18cd6897ac

**Comment by tandraschko** [comment]
It's think it's quite easy if we do bit refactoring and also remember the UISelectItems component instead only the SelectItems pojo.
