### ISSUE TITLE
Colspan of empty-row calculated incorrectly if p:columngroup used

### ISSUE THREAD

**Issue by duncan-rahman** [primefaces/primefaces#3137]
## 1) Environment
- PrimeFaces version: 6.1.7+
- Does it work on the newest released PrimeFaces version? Version? Yes
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Yes
- Application server + version: Payara 164
- Affected browsers: All

## 2) Expected behavior
Colspan of empty-row should be equal to number of actual columns
...

## 3) Actual behavior
Colspan is counting column header in 1st row of the columngroup as well as the sub-headers in the 2nd row
..

## 4) Steps to reproduce
Add p:datatable with p:columngroup and 2 p:rows, with 1 column having a rowspan of 1
.. 

## 5) Sample XHTML

<p:columnGroup type="header">
    <p:row>
      <p:column rowspan="2" headerText="First"/>
      <p:column rowspan="2" headerText="Second"/>
      <p:column rowspan="2" headerText="Third"/>
      <p:column colspan="4" headerText="Fourth"/>
    </p:row>
    <p:row>
      <p:column headerText="Fifth"/>
      <p:column headerText="Sixth"/>
      <p:column headerText="Seventh"/>
      <p:column headerText="Eighth"/>
    </p:row>
</p:columnGroup>

..

## 6) Sample bean
N/A

..

This issue was introduced in 6.1.7, probably due to the fix to #2766.

Example of behaviour after updating to 6.1.11
![incorrect colspan](https://user-images.githubusercontent.com/16843286/34674845-49c2918a-f4a9-11e7-8703-ce6beba2e8ea.png)

**Comment by jxmai** [comment]
> Colspan is counting column header in 1st row of the columngroup as well as the sub-headers in the 2nd row

The regression analysis seems valid. I don't think the newly added  `updateEmptyColspan` has taken the sub-headers into account although 
I am not an expert on dynamic columns impl (https://github.com/primefaces/primefaces/commit/7d55871402f023485ed57feebd9d58fd535bec8f).  I would suggest that this ticket be included in 6.2 milestone if possible. 
 
> This issue was introduced in 6.1.7, probably due to the fix to #2766.

@mertsincan would be nice if you can review this and #2766

**Comment by tandraschko** [comment]
@mertsincan  WOuld you like to fix that?

**Comment by duncan-rahman** [comment]
Any possibility of this in 6.2? Would like to be able to update my application, as I am currently stuck on 6.1.6

**Comment by melloware** [comment]
@duncan-rahman I just submitted this through my PRO account for @mertsincan to review.
