### ISSUE TITLE
Reintroduce PrimeFaces Push in showcase

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#3138]
I know Push is deprecated in 6.2 and will be removed in 6.3 (effectivcely forcing people on JSF 2.3 which might not be that easy in old school insurance companies et al). 

But this should not be a reason it is removed from from the showcase **now** and with such a major feature being removed I am of the opinion that an 'old, pre 6.3' showcase must be kept running for these older version... Just like I think a 'current' and 'snapshot' showcase should be running ;-)

Wdyt?

**Comment by Rapster** [comment]
I agree. IMO, there is no guarantee companies move to JSF 2.3 soon... Proof is, PF is still compliant JEE6 due to customers requirements _(being said, I must say it's kind of a strange initiative to remove Push from PF at all...)_

As long I don't find a migration guide to migrate JSF 2.2 to JSF 2.3, I don't think my company will take the risk to do the upgrade. _(I'm sure I'm not the only one in that case)_

**Comment by tandraschko** [comment]
Just my 2 cents:
Atmosphere isn't really 100% stable and quite hard to get it running on the some application servers. IMO i would never try to implement sockets without native html5 websockets (a impl is available in OmniFaces).
It was a PrimeTek internal decission (== without me) to remove it. It maybe be little bit early but i never used atmosphere in production and always had problems with it when running on different servers etc.

I migration guide from 2.2 to 2.3 in generell isn't required, it just works.

**Comment by kukel** [comment]
I don't mind PF removing Push from 6.3, but if it is deprecated in 6.2 (and lots of people are still on 6.0, 6.1) it should at least still be in the showcase and very explicitly marked as deprecated, not being removed from the showcase at all.

**Comment by melloware** [comment]
Another negative of Atmosphere is we have reported multiple bugs to their GitHub and there is zero movement on that project.  That is a very bad sign for an Open Source project.

https://github.com/Atmosphere/atmosphere-javascript/issues/226
https://github.com/Atmosphere/atmosphere/issues/2289

**Comment by kukel** [comment]
I'm not saying PF should not drop it...  not at all... just that the **showcase** should not be reduced

**Comment by tandraschko** [comment]
probably to avoid that users uses it anymore. Users can still download the old showcases.

**Comment by kukel** [comment]
@tandraschko: Yes, but that is (in my very humble opinion) not what 'the answer' should be. Then at least leave the showcase pages in, make them almost empty (not contain anything relevant regarding the deprecated PF push) but explicitly point to the alternatives (the migration guide is also not 'visible' or known to everyone.

**Comment by tandraschko** [comment]
Will close it for now as it also belongs to the showcase, not primefaces.
Also not sure why it was removed, it was a internal decision by PrimeTek.

**Comment by jfarcand** [comment]
@melloware Contribution welcomed for Atmosphere issue(s). That's not true about the zero movement..just do pull requests like others are doing :-)

**Comment by fkjaekel** [comment]
Push is actually broken on PF 6.2. The context path of the application is missing on the web socket urls that are generated, leading to 404 errors. User forum thread: https://forum.primefaces.org/viewtopic.php?f=3&t=54921&p=168078#p168078

I was aware of the discontinuation on 6.3, but this caught me by surprise. I need it working on 6.2 so I have time to plan how I'm going to replace it.

I also think that PrimeTek should provide a migration guide to another technology before discontinuing PrimeFaces Push...

**Comment by GedMarc** [comment]
It's an interesting turn of events, Atmosphere Push is kind of gone in in favor of the JDK built Web Sockets jdk.incubator.httpclient, So it's not PrimeFaces, but closer to not keeping up with the tech, the removal is **mandatory**. Any form of "keeping it" is incorrect either in your applications or in the base framework.

Atmosphere seems to have taken a "spring-boot" only option which kills pretty much everything, including micro profile (Bad choice much?)

Reality is in JDK 9 and up you should be using the stock sockets. You should be using event streams either way regardless, you should already have done the move to OSGi class path safety and type safed classes in JDK 7 and prepped for the switch to JDK 9 by using JDK 8 required service splits and updating your applications from being EE dependent (cause its obsolete and also dead, for damn good reason), so what's actually happened is you've fallen about 4-8 years behind, so PF has actually been pretty kind to you in that regard.

Regarding a migration guide - there should be none other than "Please keep up with the language or stop upgrading your JVM" - sorry if that sounds harsh but there's only so much backwards support one can ask for before instructing you to update your code base.

```
class EchoListener implements WebSocket.Listener {
    @Override
    public CompletionStage<?> onText(WebSocket webSocket,
                                     CharSequence message,
                                     WebSocket.MessagePart part) {
        // Gimme one more
        webSocket.request(1);

        // Print the message when it's available
        return CompletableFuture.completedFuture(message)
                                .thenAccept(System.out::println);
    }
}
WebSocket.newBuilder(new URI("ws://default.sockets/stocks"),
                     new EchoListener()).buildAsync().join();
```
