### ISSUE TITLE
Remove unused method parameter "rendererClass" in ComponentUtils.getUnwrappedRenderer

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3146]
Hint SONAR lint

2 possible fixes:
- Either remove this parameter
- Or use `rendererClass` to cast the renderer which has been found

Whatever the solution choosed, the result will be the same in case rendererClass does not match the renderer found: a ClassCastException

**Comment by melloware** [comment]
My guess was the intent was you can pass in a renderClass and if NULL it would not cast it but if it was not NULL attempt to cast as that class assuming you knew what you were doing.  Thoughts?
