### ISSUE TITLE
PrimeFaces Mobile JavaScript throws errors in 6.2.RC1

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#3151]
According to the [PrimeFaces 6.2 Roadmap](https://www.primefaces.org/primefaces-6-2-roadmap/), PrimeFaces Mobile is supposed to be deprecated in this release and removed in 6.3. However, the PrimeFaces Mobile JavaScript is completely broken in `6.2.RC1` and throws errors when the page is initially loaded.

## 1) Environment

- PrimeFaces version: **`6.2.RC1`**
- Is it reproducible with the last released version of PrimeFaces? **No, PrimeFaces Mobile JavaScript did not throw errors in `6.1`.**
- Is it reproducible with the latest sources? **Yes, in the latest version of PrimeFaces `6.2.RC2-SNAPSHOT`, the Mobile JavaScript still throws errors.**
- Application server + version: **Any supported server**
- Affected browsers: **Firefox, Chrome**

## 2) Steps to reproduce

1. Navigate to the xhtml below in Firefox or Chrome.
2. Open up the browser console.

## 3) Sample XHTML

```
<?xml version="1.0" encoding="UTF-8"?>
<f:view xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core"
		xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
		xmlns:p="http://primefaces.org/ui" xmlns:pm="http://primefaces.org/mobile"
		renderKitId="PRIMEFACES_MOBILE">

	<h:head>
	</h:head>
	<h:body>
		<pm:page>
			<pm:header title="Page Header">
				<h:outputText value="Page Header Text" />
			</pm:header>
			<pm:content>
				<h:form>
					<pm:field>
						<p:outputLabel for="text" value="Text:" />
						<p:inputText id="text" />
					</pm:field>
					<pm:field>
						<pm:switch id="switch" />
					</pm:field>
					<pm:field>
						<pm:rangeSlider>
							<pm:inputSlider id="slider1" />
							<pm:inputSlider id="slider2" />
						</pm:rangeSlider>
					</pm:field>
					<p:commandButton id="submit" value="Submit" update="@form" />
					<p:outputPanel>
						<p:outputLabel for="textOutput" value="Text Output:" />
						<h:outputText id="textOutput" />
					</p:outputPanel>
					<p:outputPanel>
						<p:outputLabel for="switchOutput" value="Switch Output:" />
						<h:outputText id="switchOutput" />
					</p:outputPanel>
					<p:outputPanel>
						<p:outputLabel for="slider1Output" value="Slider 1 Output:" />
						<h:outputText id="slider1Output" />
					</p:outputPanel>
					<p:outputPanel>
						<p:outputLabel for="slider2Output" value="Slider 2 Output:" />
						<h:outputText id="slider2Output" />
					</p:outputPanel>
				</h:form>
			</pm:content>
			<pm:footer title="Page Footer">
				<h:outputText value="Page Footer Text" />
			</pm:footer>
		</pm:page>
	</h:body>

</f:view>
```

## 4) Expected behavior

PrimeFaces Mobile JavaScript does not throw any errors on initial page render.

## 5) Actual behavior

PrimeFaces Mobile JavaScript throws the following errors on initial page render:

> Uncaught TypeError: Cannot read property 'concat' of undefined
>    at jquery-mobile.js.xhtml:44
>    at jquery-mobile.js.xhtml:44
>    at jquery-mobile.js.xhtml:11
>    at jquery-mobile.js.xhtml:11

> Uncaught TypeError: this.input.textinput is not a function
>    at c.init (http://localhost:8181/test-jsf/javax.faces.resource/components-mobile.js.xhtml?ln=primefaces&v=6.2.RC1:9:192)
>    at c.e.(anonymous function) [as init] (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:5:335)
>    at new c (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:5:437)
>    at Object.createWidget (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:1:4964)
>    at Object.cw (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:1:4785)
>    at http://localhost:8181/test-jsf/index.xhtml:5:541

> Uncaught TypeError: this.input.flipswitch is not a function
>    at c.init (http://localhost:8181/test-jsf/javax.faces.resource/components-mobile.js.xhtml?ln=primefaces&v=6.2.RC1:9:2241)
>    at c.e.(anonymous function) [as init] (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:5:335)
>    at new c (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:5:437)
>    at Object.createWidget (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:1:4964)
>    at Object.cw (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:1:4785)
>    at http://localhost:8181/test-jsf/index.xhtml:5:1080

> Uncaught TypeError: this.jq.rangeslider is not a function
>    at c.init (http://localhost:8181/test-jsf/javax.faces.resource/components-mobile.js.xhtml?ln=primefaces&v=6.2.RC1:9:2057)
>    at c.e.(anonymous function) [as init] (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:5:335)
>    at new c (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:5:437)
>    at Object.createWidget (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:1:4964)
>    at Object.cw (http://localhost:8181/test-jsf/javax.faces.resource/core.js.xhtml?ln=primefaces&v=6.2.RC1:1:4785)
>    at http://localhost:8181/test-jsf/index.xhtml:5:1553

> Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by tandraschko** [comment]
@mertsincan Could you check this? Seems like we would need to upgrade to jquery.mobile 1.5.0.alpha or something.

**Comment by stiemannkj1** [comment]
Just tested the fix and PrimeFaces Mobile works perfectly. Thanks @mertsincan and @tandraschko!
