### ISSUE TITLE
Autocomplete: forceSelection doesn't work after first selection

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#3152]
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: WF10
- Affected browsers: All

## 2) Expected behavior
IMHO, It should not be possible to enter "custom" text in autocomplete if forceSelection="true"

## 3) Actual behavior
After the first selection it is possible to edit an existing value

## 4) Steps to reproduce
Select a value from the Dropdown
Edit the value

## 5) Sample XHTML
```
<p:outputLabel value="Force Selection:" for="acForce" />
<p:autoComplete id="acForce" forceSelection="true" value="#{autoCompleteView.txt5}" completeMethod="#{autoCompleteView.completeText}" dropdown="true"/>
```
 
## 6) Sample bean

```
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
 
@ManagedBean
public class AutoCompleteView {
     
    private String txt5;
     
  public List<String> completeText(String query) {
        List<String> results = new ArrayList<String>();
        for(int i = 0; i < 10; i++) {
            results.add(query + i);
        }
        return results;
    }
     
    public String getTxt5() {
        return txt5;
    }
 
    public void setTxt5(String txt5) {
        this.txt5 = txt5;
    }
}

```

**Comment by melloware** [comment]
@Mich2424 Did you try this on the recently released 6.2RC1 to check if this was already fixed?

**Comment by tandraschko** [comment]
I dont understand the ticket.
It's possible that are multiple items with the same prefix (a1 and e.g. a1234), so the input must still be editable.

**Comment by tandraschko** [comment]
@melloware WDYT?

**Comment by melloware** [comment]
I say close it.  I do not understand this ticket either but I have feeling you are right.  I say close it and if they come back and provide more details great.  If not then it was probably your original idea of two like items?

**Comment by huseyinturkmenoglu** [comment]
Hi @Mich2424 , I try this code, it's working. 
`<p:autoComplete id="acForce" forceSelection="true" value="#{autoCompleteView.txt5}" completeMethod="#{autoCompleteView.completeText}" dropdown="true"  pt:readonly="#{autoCompleteView.txt5 == '5'}" />`

For using this code, you should add `xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"`

You should use the Pass Through Attribute : [https://docs.oracle.com/javaee/7/tutorial/jsf-facelets009.htm](url) 

And you should read this answer : [https://stackoverflow.com/questions/12436752/how-to-set-disable-readonly-of-pinputtext-on-change-of-hselectonemenu?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](url)

If the above explanation is not enough, would you send a better example and explanation?

**Comment by tandraschko** [comment]
will close it for now as 3 months without feedback.
