### ISSUE TITLE
Dock: problems when page has scrollbar

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3153]
Hi, I noticed some erroneous behaviour with the dock component on the latest 6.2 RC1

Problem 1:

When reloading the page, as scroll status is not the top (e.g. in the middle of the page) the dock does not animate correctly.

![image](https://user-images.githubusercontent.com/13161711/34867663-4a6d1b84-f781-11e7-8d83-5792f9465ad1.png)

Problem 2: 

When using halign="right" the dock moves into the scrollbar

![image](https://user-images.githubusercontent.com/13161711/34867615-197f4a24-f781-11e7-9701-d3a409c0e04f.png)

Code to reproduce:

```xml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
</h:head>
<h:body>
	<h:form>
		<div
			style="height: 20000px; background: #e0efe5; border: 1px solid teal;">
			Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
			nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
			erat, sed diam voluptua. At vero eos et accusam et justo duo dolores
			et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est
			Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur
			sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
			dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
			et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
			takimata sanctus est Lorem ipsum dolor sit amet.</div>

		<p:dock position="bottom">
			<p:menuitem value="123"
				icon="https://www.primefaces.org/showcase/resources/demo/images/dock/home.png"
				onclick="return false;" />
			<p:menuitem value="456"
				icon="https://www.primefaces.org/showcase/resources/demo/images/dock/home.png"
				onclick="return false;" />
			<p:menuitem value="789"
				icon="https://www.primefaces.org/showcase/resources/demo/images/dock/home.png"
				onclick="return false;" />
			<p:menuitem value="abc"
				icon="https://www.primefaces.org/showcase/resources/demo/images/dock/home.png"
				onclick="return false;" />
		</p:dock>
	</h:form>

</h:body>
</html>

```

**Comment by tandraschko** [comment]
@melloware Could you check that?

**Comment by melloware** [comment]
@cnsgithub I simply applied the patch from this blog post and verified your original ticket was fixed using the showcase and your example.

Original Ticket: https://github.com/primefaces/primefaces/issues/1728

Patch Blog Post: http://www.monkey-business.biz/181/jquery-interfaces-fisheye-position-fixed-patch/#jquery-interfaces-fisheye-position-fixed-patch_english

if that patch is causing side effects then I recommend we:
1. Revert the patch to make the Dock behave like 6.1
2. Reopen ticket #1728 
3. Close this ticket.

Thoughts?

**Comment by cnsgithub** [comment]
The old version was broken too, so a revert would not help much. My suggestion would be to ditch the current implementation of the dock based on ancient jquery fisheye, and use a different one. I found this for example which works with pure CSS.

https://zurb.com/playground/osx-dock

**Comment by melloware** [comment]
OK good so the original dock issue was fixed these are issues that have always been there.  That makes me feel better. :)

I agree this pure CSS dock is definitely pretty cool.

**Comment by Rapster** [comment]
I definitely like this new look! :wink:

**Comment by tandraschko** [comment]
Feel free to reimplement it for 6.3 ;)
