### ISSUE TITLE
Autocomplete: forceSelection chooses wrong item

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#3155]
## 1) Environment
- PrimeFaces version: 6.1.9
- Does it work on the newest released PrimeFaces version? Version? Does not work on 6.2RC2.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Wildfly 10.1
- Affected browsers: Firefox, Chrome, ...

## 2) Expected behavior
Typing in search pattern. "red"
Getting suggestions: "red" and "redmond".
Clicking on "redmond" will select "redmond".

## 3) Actual behavior
By clicking "redmond" the "red" item will selected. That's because of the changes from #2733. 
If the current value is equal to one of the items in the suggestions, this one will selected, whatever item you click on.
Using Enter to select the item will work fine.

## 4) Steps to reproduce
In the showcase ThemeService add an additional item:
`Line 75: themes.add(new Theme(39, "red", "red"));`

or add the current query to the results in AutoCompleteView:

    public List<String> completeText(String query) {
		List<String> results = new ArrayList<String>();
		results.add(query);// query as item, is always selected by click on any item
		for(int i = 0; i < 10; i++) {
			results.add(query + i);
		}		
		return results;
	}

## 5) Sample XHTML

Use the altered showcase example as described above.

## 6) Sample bean

Use the altered showcase example as described above.

**Comment by melloware** [comment]
Is this related to this one: https://github.com/primefaces/primefaces/issues/3152

**Comment by OBreidenbach** [comment]
I do not know if this is related to #3152. 
This one is about selecting the wrong item by clicking on a other one.
#3152 is about, that is possible to edit an item after selection (if multiple="false").

**Comment by melloware** [comment]
Got it.  Can you investigate and provide a PR if you discover what's broken?   This would be good to have fixed before 6.2 Final release.

**Comment by OBreidenbach** [comment]
I can explain the reason, but I do not have a solution for the problem.
In autocomplete.js in the function setupForceSelection at line 815 it detects that one value from the suggestions is equal to the insert value. 
https://github.com/primefaces/primefaces/blob/158909b6208290c71e11ea819be3146e0fc134c3/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js#L815-L818
Then in line 828 this found item is clicked.
https://github.com/primefaces/primefaces/blob/158909b6208290c71e11ea819be3146e0fc134c3/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js#L828-L833
So that must not happen if i clicked an item from the suggestions list.
