### ISSUE TITLE
Autocomplete: Disable autoselect for items which are equal to current input

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#3156]
With #2733 it was introduced that an item is selected if it is equal to the current input. We would like to disable this behavior for our use case.
We can provide a PR. We would add attribute to the autoComplete-Tag. Just let us know, how to name it.
Suggestion: disableAutoSelection

**Comment by melloware** [comment]
Definitely suggest a PR.  And the name maybe it should just be autoSelection="true" with true being the default and you can turn it off with autoSelection="false".

**Comment by OBreidenbach** [comment]
Added PR #3162
I would love to see it in the 6.2 release. For me, it would solve the problem with #3155
