### ISSUE TITLE
SelectOneMenu: Incorrect top position of expanded selectOneMenu when p:blockUI is present

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#3157]
## 1) Environment
Win 10, Tomcat 8.0, PF 6.1
Win 10, Tomcat 8.0, PF 6.2RC1
Chrome or Firefox
(works fine in IE 11 or Edge) 

## 2) Expected behavior
When combo is expanded, the top edge should be aligned to the bottom edge of the input box

## 3) Actual behavior
If there is any content before p:selectOneMenu, its height is added to the 'top' property of expanded list of items. But only when p:blockUI is present.
<kbd>
![image](https://user-images.githubusercontent.com/3907898/34880679-7f0ddca4-f7b1-11e7-9217-46d0ff29df21.png)
</kbd>
It gets fixed on window resize.

## 4) Steps to reproduce
Run the XHTML and select any item in the version combo. 

## 5) Sample XHTML
```html
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Test</title>
    </h:head>
    <h:body>
        <p style="height: 100px; margin: 0px">Spacer 100px</p>

        <h:form id="body">

            <p:blockUI block=":body" trigger=":body:version" />

            <h:panelGrid columns="2">

                Version
                <p:selectOneMenu id="version">
                    <f:selectItem itemLabel="1" itemValue="1"/>
                    <f:selectItem itemLabel="2" itemValue="2"/>
                    <p:ajax update="content"/>
                </p:selectOneMenu>

                Content
                <h:inputTextarea id="content" value="" style="width: 800px; height: 100px;"/>
            </h:panelGrid>
        </h:form>
    </h:body>
</html>
```

## 6) Sample bean
not necessary

**Comment by melloware** [comment]
Great example @jan-tosovsky-cz .  I have seen similar strangeness when using these in a dialog and then using the mouse-wheel to scroll the page and then clicking on the dropdown.  Your use case is a simpler example than mine.  Thanks you.

**Comment by melloware** [comment]
@jan-tosovsky-cz can you try again with my runnable sample attached.  It uses PF 6.3-SNAPSHOT and it seems to work fine in Chrome and Firefox now. Just run "mvn clean jetty:run-exploded".
[pf-3157.zip](https://github.com/primefaces/primefaces/files/2673890/pf-3157.zip)

**Comment by jan-tosovsky-cz** [comment]
I can't resolve PF 6.3-SNAPSHOT dependency.

**Comment by melloware** [comment]
@jan-tosovsky-cz simply do this to have PF 6.3-SNAPSHOT available for the test project.

```
git clone https://github.com/primefaces/primefaces.git
cd primefaces
mvn clean install
```

**Comment by jan-tosovsky-cz** [comment]
It seems to be really fixed in the snapshot version. Thanks!

**Comment by melloware** [comment]
OK then please close this ticket.  Thanks for testing!
