### ISSUE TITLE
When any ajax error happens, pfAjaxError will be triggered

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3164]
Reported By PRO User;
> We have used some of the components with global="false" in a page so that the page refresh is not 
> visible to users.
> 
> We also have other pages and components without global false for ajax events.
> 
> when any ajax error happens, is there any way to handle the error in a page or specific template level where global false is used? We know that we have to use onerror in each component.
> 
> See 2 samples
> 
> Global Level
> 
> <p:ajaxStatus onstart="onStartRequestHandler();" onerror="oneErrorAjaxErrorHandler();" oncomplete="onCompleteAjaxRequestHandler();"/>
> 
> pageLevel
> 
> <p:poll interval="#{appParams.autoSaveInterval}" onerror="oneErrorAjaxErrorHandler();" listener="#{familyOverviewBean.autoSaveFamilyOverview}" async="true" global="false" 
> widgetVar="pollElement" autoStart="false" update="assessmentForm:messages assessmentForm:editedByPanel" partialSubmit="true" 
> process="assessmentForm:asmIndicatorWriteSec assessmentForm:famHistWriteSection"/>
> 
> What we are looking is to move onerror="oneErrorAjaxErrorHandler();" on p:poll and other components to a common place.

**Comment by kukel** [comment]
Sounds interesting functionality... will this be documented somewhere? Showcase?

**Comment by tandraschko** [comment]
Don't think so but the functionality is there since years.
