### ISSUE TITLE
Spinner: not rotating the values

### ISSUE THREAD

**Issue by prabhu352** [primefaces/primefaces#3165]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:6.1
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
in inputspinner field , value has to be rotating(spinning). once the "max" value is reached after incrementing the value , the new value has to be updated to "min" , this is the actual defination of spinner. the values inside spinner should spin.
...

## 3) Actual behavior
once the value is reached to max, after incrementing the value , value is not reset to min.
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<p:spinner min="0" max="100" value="#{numberSpinnerBean.spinnerValue}"/>
..

## 6) Sample bean
private int spinnerValue;

	/**
	 * get spinner value
	 * @return int
	 */
	public int getSpinnerValue() {
		return spinnerValue;
	}

	/**
	 * set spinner value
	 * @param spinnerValue
	 */
	public void setSpinnerValue(int spinnerValue) {
		this.spinnerValue = spinnerValue;
	}	
	
..

**Comment by tandraschko** [comment]
Please describe a it a little better or provide links of examples which are doing it correctly.

**Comment by prabhu352** [comment]
here the issue is when we use "min" and "max" attributes, say min=1 and max =10,and when value in spinner is 10 then after pressing increment button, value remains same(i.e 10), but spinner should rotate the value to "0", is it possible to get this feature. otherwise user has to press decrement button 10 times to get value "0" .

**Comment by kukel** [comment]
'fix' is in stackoverflow already... Link will be added by OP

**Comment by prabhu352** [comment]
hi, 

i found the solution, no need of link. :)

Thanks

**Comment by prabhu352** [comment]
i just checked the spinner.js of primeface and override the javascript for spin function. as mentioned  below:
```javascript
(function() {
    PrimeFaces.widget.Spinner.prototype.spin = function(dir) {
    var step = this.cfg.step * dir,
    currentValue = this.value ? this.value : 0,
    newValue = null;

    if(this.cfg.precision)
        newValue = parseFloat(this.toFixed(currentValue + step, this.cfg.precision));
    else
        newValue = parseInt(currentValue + step);

    if(this.cfg.maxlength !== undefined && newValue.toString().length > this.cfg.maxlength) {
        newValue = currentValue;
    }

    if(this.cfg.min !== undefined && newValue < this.cfg.min) {
        newValue = this.cfg.max;
    }

    if(this.cfg.max !== undefined && newValue > this.cfg.max) {
        newValue = this.cfg.min;
    }

    this.value = newValue;
    this.format();
    this.input.attr('aria-valuenow', newValue);  
    }
})();
```

now rotation is happening properly.

**Comment by melloware** [comment]
@kukel @prabhu352 Are you guys saying that this should be the default behavior of the spinner and its a bug?  So the code above should be patched into the spinner?

**Comment by kukel** [comment]
No not for me as stated in the stackoverflow link that the OP die not post.
I would not mind thuis behaviour but no nerd to make IT default either

**Comment by melloware** [comment]
OK then @prabhu352 I would say close this ticket then.

**Comment by tandraschko** [comment]
Why closing it? Doesn't it make sense to add it as feature?

**Comment by kukel** [comment]
I agree with Thomas... sorry that I did not mention that previously... But https://github.com/primefaces/primefaces/issues/958 first ;-)

**Comment by melloware** [comment]
OK I misunderstood @kukel's answer.   He doesn't want it as "default" behavior but wouldn't mind it as an "option" to turn on.
