### ISSUE TITLE
Allow converter for itemLabel on selectItems

### ISSUE THREAD

**Issue by xqvier** [primefaces/primefaces#3166]
This is not a bug but a change request to use any application registered converter on the object returned by the itemLabel attribute of a selectItem(s).

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Any
- Affected browsers: Any

## 2) Expected behavior
Uses of the application registered converter for the object returned by the itemLabel attribute of a selectItem(s)

## 3) Actual behavior
A String.valueOf(myObj) is called to display the itemLabel which is often irrelevant on a custom object.

## 4) Steps to reproduce
Define a custom object 'myObj'
Define a converter for this object (the converter does not need to be bidirectionnal as it is only a matter of display - so only the getAsString() should do something).
use it as the attribute of a selectItem(s) itemLabel attribute.

## 5) Sample 
I forked the primefaces-test project to set a use case : 
https://github.com/xqvier/primefaces-test/commit/8686ebd3a3758a5357691c828bc2777e77b0a8c5

**Comment by xqvier** [comment]
I had make a pull request last summer (https://github.com/primefaces/primefaces/pull/2676).
There was a question to know if it was working like the "expected behavior" in the JSF impl and the answer is no.

As for the reviews on the code submitted i'll take care of these and make a new pull request if that's ok with you.

**Comment by tandraschko** [comment]
I'm not sure if we will apply this.
If you read the docu for f:selectItem, it clearly states that the itemLabel should be a String:

itemLabel | false | false | javax.el.ValueExpression (must evaluate to java.lang.String)
