### ISSUE TITLE
ContextMenu: ajax update on context menu is clonning the element

### ISSUE THREAD

**Issue by herbu123** [primefaces/primefaces#3167]
Hi,

issue described here: [https://forum.primefaces.org/viewtopic.php?p=163533#p163533](url)

## 1) Environment
- PrimeFaces version: **6.2 RC1** !!!
- Works fine on 6.0 and 6.1
- Affected browsers: firefox, chrome

## 3) Actual behavior
When I do the ajax-update on the element that contains context menu somehow the context menu element (div) is beeing cloned - with the same id (please see below)

## 4,5) Steps to reproduce & Sample

`	
<h:form id="test">

		<p:panel id="a">
			<p:commandButton type="submit" 
				update=":test:b"
				process="@this" /> 	
		</p:panel>		
		<p:panel id="b">
			<p:dataTable id="dTable" widgetVar="w_dTable">
			</p:dataTable> 
			<p:contextMenu id="cmTable" for="dTable">
			</p:contextMenu>
		</p:panel>
	</h:form>
`

Now, everytime I click the buton the context-menu element <div> is clonned under the "body" element (can't insert picture - one may see this is code inspector)
`<body>
	<form id="test" name="test" method="post" action="/asr/test.xhtml" enctype="application/x-www-form-urlencoded">
		<input name="test" value="test" type="hidden">
			<div id="test:a" class="ui-panel ui-widget ui-widget-content ui-corner-all" data-widget="widget_test_a">
				<div id="test:a_content" class="ui-panel-content ui-widget-content">

	</form>

	<div id="textarea_simulator" style="position: absolute; top: 0px; left: 0px; visibility: hidden;"></div>
	<div id="test:cmTable" class="ui-menu ui-menu-dynamic ui-contextmenu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix ui-shadow aqq" role="menubar">
		<div tabindex="0" class="ui-helper-hidden-accessible"></div>
		<ul class="ui-menu-list ui-helper-reset"></ul>
	</div>
	<div id="test:cmTable" class="ui-menu ui-menu-dynamic ui-contextmenu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix ui-shadow aqq" role="menubar">
		<div tabindex="0" class="ui-helper-hidden-accessible"></div>
		<ul class="ui-menu-list ui-helper-reset"></ul>
	</div>
	<div id="test:cmTable" class="ui-menu ui-menu-dynamic ui-contextmenu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix ui-shadow aqq" role="menubar">
		<div tabindex="0" class="ui-helper-hidden-accessible"></div>
		<ul class="ui-menu-list ui-helper-reset"></ul>
	</div>
	<div id="test:cmTable" class="ui-menu ui-menu-dynamic ui-contextmenu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix ui-shadow aqq" role="menubar">
		<div tabindex="0" class="ui-helper-hidden-accessible"></div>
		<ul class="ui-menu-list ui-helper-reset"></ul>
	</div>
	<div id="test:cmTable" class="ui-menu ui-menu-dynamic ui-contextmenu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix ui-shadow aqq" role="menubar">
		<div tabindex="0" class="ui-helper-hidden-accessible"></div>
		<ul class="ui-menu-list ui-helper-reset"></ul>
	</div>
</body>
`
pleaes notice that "test:cmTable" appears many times!

In my case I need to get to the context menu element from javascript (some magic on context menu's beforeshow) and getElemetByID is giving me the first one - when the last one is really shown.

Regards,
herbu

**Comment by tandraschko** [comment]
Can't replicate with the sample and steps your provided.

**Comment by herbu123** [comment]
Hi,

did you check in browser's (in my case firefox) code inspector ?

Please click the button a few times (force ajax update) and verify the changes in inspector - in my case each click adds a new div ....


Regards,
herbu

**Comment by tandraschko** [comment]
![3167](https://user-images.githubusercontent.com/2485545/35045903-a6a59f30-fb95-11e7-872f-a6bbb42898c4.png)

After multiple button clicks ;)

**Comment by herbu123** [comment]
Dear Thomas,

are you sure you have used 6.2 RC1 ??

Please verify my screen - in the script section I have primefaces v=6.2.RC1 whether in your case goes just primefaces v=null...

Could you please send me the link to the jar you use so  I can double check? (I am using maven)

![6_2_bug](https://user-images.githubusercontent.com/34067588/35087296-a799f188-fc27-11e7-9a7e-5818e91e7540.jpg)

Same result I get in chrome.

Regards,
herbu

**Comment by tandraschko** [comment]
the v=null happens when using having both PF and Showcase open in the same netbeans instance.
Could you try a source build? The guide is in the github wiki, how to build from source.

**Comment by herbu123** [comment]
Hi Thomas,

somehow the screenshot was not uploaded - please find it attached.
Unfortunately I am not able to test on source - using jar from:
https://repository.primefaces.org/org/primefaces/primefaces/6.2.RC1/

[image: Inline image 1]

Regards,
herbu

**Comment by tandraschko** [comment]
Not sure why i couldn't replicate @company but it failed @home :D
fixed!
