### ISSUE TITLE
jqplot breaks if first element of a series is NULL

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#3173]
- PrimeFaces version: 6.1, but also tested with chart.js from trunk

On 1 Feb 2014 (commit 7b7a16e) there was bugfix which affected the handling of y values which are NULL. The point highlight will be out of sync without this patch. Therefore it is required.

But this fix introduced another bug. If The first y-axis value of the first series is NULL, the whole chart breaks and won't be rendered. Look at this fiddle: https://jsfiddle.net/3yrrsqp1/3/

It will work, if the NULL is:
 - anywhere in a non-first series
 - not the first element of the first series ( https://jsfiddle.net/3yrrsqp1/4/ )

A valid fix would be a change of the method ``Axis.prototype.resetDataBounds`` around line 804  in charts.js.

**Old code**
```
if ((d[j][minyidx] != null && d[j][minyidx] < db.min) || db.min == null) {
    db.min = d[j][minyidx];
}
if ((d[j][maxyidx] != null && d[j][maxyidx] > db.max) || db.max == null) {
    db.max = d[j][maxyidx];
}
```

**New code**
```
if (d[j][minyidx] != '-' && ((d[j][minyidx] != null && d[j][minyidx] < db.min) || db.min == null)) {
	db.min = d[j][minyidx];
}
if (d[j][maxyidx] != '-' && ((d[j][maxyidx] != null && d[j][maxyidx] > db.max) || db.max == null)) {
	db.max = d[j][maxyidx];
}
```

Would be nice if it is included in final PF 6.2

**Comment by tandraschko** [comment]
Please provide a PR.

**Comment by fanste** [comment]
PR: #3174

**Comment by tandraschko** [comment]
Could someone test it with some combinations? Would be bad if something would break again.

**Comment by melloware** [comment]
I have messed around with this a little bit (not comprehensive) and this change appears to work find and not introduce any side effects.

**Comment by fanste** [comment]
My collegue also tested my change in an application that uses a lot of charts of different types. Everything seems to work.
