### ISSUE TITLE
InputMask: with ajax on change sends two requests when ctrl+v used

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3175]
## 1) Environment
- PrimeFaces version: 6.1.11
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Don´t know
- Application server + version: any
- Affected browsers: any

## 2) Expected behavior
Expected is that only single request is sent.

## 3) Actual behavior
Two requests are sent to server.

## 4) Steps to reproduce
1) Modify Showcase page inputMask's last example (Product key) as follows (onchange ajax added):
```
<p:inputMask id="key" value="#{maskView.productKey}" mask="a*-999-a999">
  <p:ajax event="change" process="@this" update="@this" />
</p:inputMask>

```
or use alternative like this, where we noticed the problem in the first place:
```
<p:inputMask label="rcMask"  mask="999999/999?9" value="#{maskView.rc}" required="true">
  <p:ajax event="change" process="@this" update="@this" />
</p:inputMask>

```
2) Run showcase app and paste into Product Key field using ctls+v valid test string like: 'aa-999-a999' and leave the input field.
3) Observe, that two requests to server are sent. For the first example with ProductKey the value from this field is identical in both requests. 
For the second provided example when input '123456/789' used, the first request contains wrong value '123456/789_' and the second request correct value '123456/789'. When full length '123456/7890' used, then both requests have identical value.

When value inserted using typing, than only single request is sent after input is left.
 
## 5) Sample XHTML
Use showcase InputMask page and alter it as above.

## 6) Sample bean
Use showcase InputMask bean and add String rc field for second provided example.

**Comment by tandraschko** [comment]
Does it work when removing the update=@this?

**Comment by martin654** [comment]
Hi, sorry for delay. I tried to remove update=@this (and also removed value of update in second attempt) as suggested, but it behaves the same.

**Comment by lagar84** [comment]
I am having this same bug and found this open issue.
To workaround it, I put a **delay="50"**. Like this:

<p:inputMask id="key" value="#{maskView.productKey}" mask="a*-999-a999">
          <p:ajax event="change" process="@this" update="@this" **delay="50"** />
</p:inputMask>

**Comment by martin654** [comment]
That workaround works as a temporary fix. Thanks!

**Comment by martin654** [comment]
Isn't this similar to https://github.com/primefaces/primefaces/issues/2757 ?

**Comment by tandraschko** [comment]
don't think so - inputNumber is quite special ;)

**Comment by lucasandradz** [comment]
Is there any news on this issue? I am facing this problem recently, just checking if it has been fixed in newer versions before considering using inputText with js mask as a workaround.
