### ISSUE TITLE
Calendar: Close button functionality 

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3179]
Environment
PrimeFaces version: 6.1
Does it work on the newest released PrimeFaces version? Version? No
Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
Application server + version:
Affected browsers: All

Calendar Cancel (Close) and Apply button functionality Changes

2) Expected Behavior:
     I want two button in calendar popup
     One is for Cancel the Calendar popup ( without saving the new date )
     Second is for Apply button

         Cancel Button :
                what it will do ?
                - If you select any date or time and click on Cancel button than it should revert
                  to the previous selected date.

        Apply Button :
                 what it will do ?
                 - If you select new date and click apply button than only it should apply then 
                  new date otherwise it should revert to the previous selected date

3) Actual behavior
The calendar popup close button functionality is not corrected.
It is closing the popup and not retain the previous date

4) Steps to reproduce
Set calendar as showButtonPanel="true" and showOn="both"Try to select the date and close the popupNext time again you open popup and select the new datethan How you will retain the previous date selection if you don't want to set new date and want the previous date..

5) Sample XHTML<p:calendar pattern="MM/dd/yyyy HH:mm" showButtonPanel="true" showOn="both" navigator="true">

**Comment by ankitacroit09** [comment]
Please Comment on this

**Comment by tandraschko** [comment]
Please edit your issue so everything can understand it. I don't understand it.

**Comment by ankitacroit09** [comment]
Expexted Behaviour:
 I want two button in calendar popup
 One is for Cancel the Calendar popup ( without saving the new date )
 Second is for Apply button

 Cancel Button :  
      what it will do ?
      - If you select any date or time and click on Cancel button than it should revert to the previous 
         selected date.

 Apply Button :
       what it will do ?
       -If you select new date and click apply button than only it should apply the new date otherwise it 
        should revert to the previous selected date
