### ISSUE TITLE
toggleSelect ignores immediate setting of SelectCheckboxMenu

### ISSUE THREAD

**Issue by ubench-tdv** [primefaces/primefaces#318]
In the SelectCheckboxMenu the custom Ajax event "toggleSelect" ignores the immediate attribute and always fires the listener in the first JSF phase.
This causes the listener always to be fired before any validation and before the values of the SelectCheckboxMenuhave been processed.

This can easily be fixed by changing the queueEvent method in the SelectCheckboxMenu class from the original:

@Override
public void queueEvent(FacesEvent event) {
    FacesContext context = getFacesContext();
    String eventName = context.getExternalContext().getRequestParameterMap().get(Constants.RequestParams.PARTIAL_BEHAVIOR_EVENT_PARAM);

```
if(event instanceof AjaxBehaviorEvent && eventName.equals("toggleSelect")) {
    Map<String,String> params = context.getExternalContext().getRequestParameterMap();
    String clientId = this.getClientId(context);
    boolean checked = Boolean.valueOf(params.get(clientId + "_checked"));

    super.queueEvent(new ToggleSelectEvent(this, ((AjaxBehaviorEvent) event).getBehavior(), checked));
}
else {
    super.queueEvent(event);
}
```

}

Into (for example):

@Override
public void queueEvent(FacesEvent event) {
    FacesContext context = getFacesContext();
    String eventName = context.getExternalContext().getRequestParameterMap().get(Constants.RequestParams.PARTIAL_BEHAVIOR_EVENT_PARAM);

```
if(event instanceof AjaxBehaviorEvent && eventName.equals("toggleSelect")) {
    Map<String,String> params = context.getExternalContext().getRequestParameterMap();
    String clientId = this.getClientId(context);
    boolean checked = Boolean.valueOf(params.get(clientId + "_checked"));

    ToggleSelectEvent toggleSelectEvent = new ToggleSelectEvent(this, ((AjaxBehaviorEvent) event).getBehavior(), checked);
    toggleSelectEvent.setPhaseId(event.getPhaseId());

    super.queueEvent(toggleSelectEvent);
}
else {
    super.queueEvent(event);
}
```

}

**Comment by sudheerj** [comment]
You are right.It might be missed somehow.You can create a pull request.

**Comment by cagataycivici** [comment]
Can you post your code as well?

**Comment by ubench-tdv** [comment]
(Sorry for update, it seems github screwed up the layout of my e-mail, hence manual editing)

Hi,

If you change the showcase example .XHTML with this:

``` html
<h:form>
    <h:panelGrid id="myPanelGrid" columns="3" cellpadding="5">
        <h:outputLabel for="menu" value="Location:" />
        <p:selectCheckboxMenu id="menu" value="#{checkboxView.selectedCities}" label="Cities" 
                              filter="true" filterMatchMode="startsWith" panelStyle="width:250px">
           <p:ajax event="toggleSelect" listener="#{checkboxView.handleSelection}" update="display" />
           <p:ajax event="change" listener="#{checkboxView.handleSelection}" update="display" />
           <f:selectItems value="#{checkboxView.cities}" />
        </p:selectCheckboxMenu>
        <p:commandLink value="Submit" update="display" />
        <p:inputText label="TEST" value="#{checkboxView.myField}" required="true"/>
    </h:panelGrid>

    <p:outputPanel id="display" style="width:250px;padding-left:5px;margin-top:10px">
        <p:dataList value="#{checkboxView.displaySelectedCities}" var="city" emptyMessage="No cities selected">
            #{city}
        </p:dataList>
    </p:outputPanel>
</h:form>
```

and add:

``` java
    private String[] displaySelectedCities;

    public void setDisplaySelectedCities(final String[] displaySelectedCities) {
        this.displaySelectedCities = displaySelectedCities;
    }

    public void handleSelection(final AjaxBehaviorEvent event) {
        if (selectedCities != null) {
           displaySelectedCities = selectedCities.clone();
       }
   }
```

to the bean.

You will see that clicking the "select all" button does not update the selected cities while selecting single items does behave correctly.

Further if you look at the source code. All child classes of UIComponentBase (e.g. SelectOneMenu) do the following stuff:

``` java
SelectEvent selectEvent = new SelectEvent(this, behaviorEvent.getBehavior(), item);
selectEvent.setPhaseId(event.getPhaseId());
```

but SelectCheckBoxMenu does not do this for which I don't see a reason.

As a result the ajax event toggleSelect is executed in Phase 2 instead of Phase 5.

**Comment by cagataycivici** [comment]
Can you use code formatter please?

**Comment by ubench-tdv** [comment]
Hi, I tried the markdown style and in the preview it looks well, however when I submit it seems to screw up the code. Sorry for that.

**Comment by cagataycivici** [comment]
Fix checked in.
