### ISSUE TITLE
TabMenu: throws an exception when an HTML comment is nested inside of it

### ISSUE THREAD

**Issue by kito99** [primefaces/primefaces#3186]
## 1) Environment
- PrimeFaces version: 6.1RC1
- Does it work on the newest released PrimeFaces version? Version? No. 6.1RC1. It does work in 3.5, though :-).
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: WebLogic 10.35
- Affected browsers: All

## 2) Expected behavior

HTML-style comments should be ignored

## 3) Actual behavior

When you use HTML comments inside of `p:tabMenu` it throws an exception:

```
com.sun.faces.facelets.compiler.UIInstructionsjava.lang.ClassCastException: com.sun.faces.facelets.compiler.UIInstructions
at org.primefaces.component.tabmenu.TabMenuRenderer.encodeMarkup(TabMenuRenderer.java:65)
at org.primefaces.component.menu.BaseMenuRenderer.encodeEnd(BaseMenuRenderer.java:117)
...
```

## 4) Steps to reproduce

See example.

## 5) Sample XHTML

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <title>TabMenu bug</title>
</h:head>
<h:body>
    <!-- This will not throw an exception -->
    
    <p:tabMenu>
    <!-- This will throw an exception -->
        <p:menuitem value="test" outcome="/ui/homeView">
        </p:menuitem>

    </p:tabMenu>

</h:body>
</html>
```

## 6) Sample bean
N/A

**Comment by tandraschko** [comment]
We can easily fix it but i always suggest to set the "facelets ignore comments" param

**Comment by kito99** [comment]
Thanks for fixing this so quickly. I ran into this while updating an old app from PrimeFaces 3.5; I changed to <ui:remove> to get around it, but I figure I would report it anyway, since people would expect it to work.
