### ISSUE TITLE
[perf] use index-loop when iterating children or ArrayLists

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3189]
The overall performance gain is not big compared to other changes BUT 
- each for-each loop creates a new iterator
- index-loop doesn't create the iterator and random-access is even a bit faster on ArrayLists

i already did this on multiple places in PF.

if every component is optimized, the performance gain should be measurable when using jmeter.

The difference isn't really big and i would never do it business-logic code in applications... but a framework should be fast as possible. 
We have some renders which creates multiple iterator instances per RENDER_RESPONSE - if you have ~200 PF components in the view, you will safe 200 iterator instances per request.

**Comment by cnsgithub** [comment]
Is there a checkstyle rule for that?

**Comment by tandraschko** [comment]
It doesnt make sense for every loop, therefore not possible

**Comment by tandraschko** [comment]
Very core is fine now + all common forms components.
Not sure if we should touch data components, too.

**Comment by tandraschko** [comment]
Will close it for now. It think it's worth to optimize UIData + DataTable in the future but all other i woudln't touch.

**Comment by Rapster** [comment]
Reading "Prefer for-each loops to traditional for loops" from Effective java by Joshua Bloch made me question about this issue. I quote:

> The for-each loop (officially known as the “enhanced for statement”) solves all of these problems. It gets rid of the clutter and the opportunity for error by hiding the iterator or index variable. [...]When you see the colon (:), read it as “in.” Thus, the loop above reads as “for each element e in elements.” There is no performance penalty for using for-each loops, even for arrays: the code they generate is essentially identical to the code you would write by hand. The advantages of the for-each loop over the traditional for loop are even greater when it comes to nested iteration. [...] In summary, the for-each loop provides compelling advantages over the traditional for loop in clarity, flexibility, and bug prevention, with no performance penalty. Use for-each loops in preference to for loops wherever you can.

By curiosity, I didn't find any benchmark regarding that topic on internet (considering warm up, forks, etc...) So I decided to run mine, and I was quite surprised by the result (higher is better):

```
Benchmark                  Mode  Cnt        Score       Error  Units
MyBenchmark.loopEnhanced  thrpt   10  2290432,822 ▒ 55702,689  ops/s
MyBenchmark.loopForIndex  thrpt   10  2191136,146 ▒  6015,211  ops/s
```

And here is the benchmark:
```java
public class MyBenchmark {

    @State(Scope.Benchmark)
    public static class LoopState {
        public List<Integer> list;

        @Setup
        public void initializeArray() {
            list = new ArrayList<>();
            for(int i = 0; i < 100; i++)
            {
                list.add(i);
            }
        }
    }

    @Benchmark
    @Fork(value = 2)
    public Long loopForIndex(LoopState state) {
        Long result = 0L;
        for(int i=0; i < state.list.size(); i++)
        {
            Integer var = state.list.get(i);
            result += var;
        }
        return result;
    }

    @Benchmark
    @Fork(value = 2)
    public Long loopEnhanced(LoopState state) {
        Long result = 0L;
        for(Integer var : state.list)
        {
            result += var;
        }
        return result;
    }
}
```

It looks like for at least two reasons, foreach sounds better than index loop. Here is the detail of the running benchmark [benchmark_for.txt](https://github.com/primefaces/primefaces/files/2324826/benchmark_for.txt)

**Comment by tandraschko** [comment]
it's not about the executing performance, there is no or nearly no performance gain.

The difference is the Iterator allocation.
It's a big difference if there are 100k iterator per request or below 1k. (just think about multiple requests)
Of course the benefit is bigger in the JSF impl as in PF -> https://issues.apache.org/jira/browse/MYFACES-3130

As i already posted somewhere, i would never use index-loops in my applications.

**Comment by Rapster** [comment]
Ah ok, you mention jmeter, faster, so I figured how rendering velocity could be speed up... 100k is a lot... Specially for one iterator per collection, I don't know how you can come up with that number

**Comment by tandraschko** [comment]
the performance boost comes from less GC if you use jmeter with paralell requests - i'm sure you can't see any difference from a single request when switching the loops.

100k is easily possible if you have a big view as loops are always used to traverse the component tree.
