### ISSUE TITLE
SelectOneMenu: disabled in some particular cases

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#3190]
In order to run into this bug 4 files is needed and it can be found here: https://gitlab.com/sesipedf/showcase-eclipse/commit/3106f21d341a8069854f8ba63b7732f5f8a2a3bf

Steps:
1-Click in "Localizar visitante" button
2-Click in the button inside the dialog
3-Try to select some item in "Sexo" selectOneMenu

This bug was introduced in 6.2 release

**Comment by tandraschko** [comment]
fixed it but we need to refactor all components a little bit - see #3178
