### ISSUE TITLE
DataTable: StringIndexOutOfBoundsException if using multiViewState="true" with javax.faces.SEPARATOR_CHAR

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#3191]
## 1) Environment
- PrimeFaces version: 6.1.12
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? Don't know
- Application server + version: Apache Tomcat/7.0.82
- Affected browsers: All

## 2) Expected behavior
When using a non-default javax.faces.SEPARATOR_CHAR, rendering of data tables with multiViewState="true" works. It worked in 6.1.9 (just upgraded to 6.1.12).

## 3) Actual behavior
When using a non-default javax.faces.SEPARATOR_CHAR, rendering of data tables with multiViewState="true" throws StringIndexOutOfBoundsException

## 4) Steps to reproduce
Use "-" instead of ":" as JSF separator char and a datatable with multiViewState="true".

## 5) Sample XHTML
a) web.xml that contains:
```
  <context-param>
    <param-name>javax.faces.SEPARATOR_CHAR</param-name>
    <param-value>-</param-value>
  </context-param>
```
b) xhtml that contains:
```
<p:datatable multiViewState="true" ...>
  <p:column ...>
</p:datatable>
```

## 6) Sample bean
Not relevant.

**My Analysis:**
The StringIndexOutOfBoundsException is caused because DataTableRenderer uses a hard-coded separator ":", see line 1239:
`String colHeaderClientId = clientId + colClientId.substring(colClientId.lastIndexOf(":"), colClientId.length());`

If I change it to:
`            String separatorChar = FacesContext.getCurrentInstance().getExternalContext().getInitParameter("javax.faces.SEPARATOR_CHAR");
            String colHeaderClientId = clientId + colClientId.substring(colClientId.lastIndexOf(separatorChar), colClientId.length());`
it works fine. I can provide a pull request if preferred.

**Comment by tandraschko** [comment]
@mertsincan fixed it - feel free to port it to elite
