### ISSUE TITLE
InputNumber: auto send request when focus out if use attribute symbol

### ISSUE THREAD

**Issue by trungdoviet** [primefaces/primefaces#3192]
# Usecase
I'm now using Primeface 6.1, as i know that Primefaces already moved some elements from Primefaces Extension to Primefaces and it include p:inputNumber.
Now i have the xhtml like this:
```xml
<p:inputNumber   value="#{myBean.amount}"
			minValue="0" decimalPlaces="0">
		 <p:ajax event="change" global="false" listener="#{myBean.doValueChangeEvent}"/>
</p:inputNumber>
```
It work fine, when i focus in then enter value and focus out, it will fire request to server.
But when i define the symbol for my value (because it's about currency), like this:
```xml
<p:inputNumber symbol=" CHF" symbolPosition="s"
 			  value="#{myBean.amount}"
			minValue="0" decimalPlaces="0">
		 <p:ajax event="change" global="false" listener="#{myBean.doValueChangeEvent}"/>
</p:inputNumber>
```
it mean it will show "CHF" as suffix of my value. When i only focus in and focus out, this element will fire event although i did not input any value (still empty).

## 1) Environment
- PrimeFaces version: 6.1
- It does not work on Primeface 6.2.RC1 as well
- Application server + version: Tomcat 8.5
- Affected browsers: IE 11

## 2) Expected behavior
Should not fire any request in case user does not enter value to inputNumber. 

## 3) Actual behavior
It fire request if i only focus in and focus out without changing value
..

## 4) Steps to reproduce
1. Focus in to InputNumber, the suffix will appear
2. Focus out then request is fired to server

## 5) Sample XHTML
```xml
<p:inputNumber symbol=" CHF" symbolPosition="s"
 			  value="#{myBean.amount}"
			minValue="0" decimalPlaces="0">
		 <p:ajax event="change" global="false" listener="#{myBean.doValueChangeEvent}"/>
</p:inputNumber>
```
Thanks

**Comment by tandraschko** [comment]
Sorry but it works fine i copy the code in the showcase with the current PF trunk version.

**Comment by Rawi01** [comment]
The current showcase shows exactly the described behaviour. Simply clear the second example input.

**Comment by melloware** [comment]
@Rawi01 Clearing the input is not the same as this ticket?  This ticket just says focus in and focus out of the element.  If you are clearing the value aren't you changing it?

**Comment by Rawi01** [comment]
I think I should be more specific :)
I said that you have to clear the field to get an empty input with a symbol as described in this issue.

Steps:
- Clear input
- Focus out (Change triggered, as it should)
- Focus in
- Focus out (Change triggered again, this is the issue described here)

**Comment by melloware** [comment]
Thank you for clarifying!

**Comment by melloware** [comment]
@tandraschko can you re-open this ticket. It is definitely a bug in AutoNumeric right here:

https://github.com/primefaces/primefaces/blob/fee777a68575062260c36e31b0a388f0fd29621f/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js#L1099-L1103

If you step through the debugger it is saying the values don't match because of the "CHF" suffix and firing the change event.

**Comment by Rawi01** [comment]
I just fixed it for my usecase by replacing these lines with
```js
$this.val(groupedValue);
if (groupedValue !== holder.inVal) {
    $this.change();
    delete holder.inVal;
}
```
The code in autoNumeric were added in this commit: https://github.com/autoNumeric/autoNumeric/commit/553812d6261ca2debec872e5d34850c66407caa7

**Comment by melloware** [comment]
I agree with your fix and submitted a PR.
