### ISSUE TITLE
[]Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by vicenthy** [primefaces/primefaces#3193]
when importing the project to eclipse I get this error in maven 
[]Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:xslt-maven-plugin:1.0
I just wanted to understand.
thanks.

**Comment by tandraschko** [comment]
Use the forum or stackoverflow, this is more question as a real issue.

**Comment by vicenthy** [comment]
Sorry, i got help  here 

http://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html
