### ISSUE TITLE
Growl: Pause Message Timeout on Mouse Hover

### ISSUE THREAD

**Issue by Dougnlizt** [primefaces/primefaces#3195]
Many users, when reading a 'growl' pop up message, will hover with the mouse to give it more time to read it.  The PF growl ignores the mouse, and continues the 'countdown' if the 'life' property is set (and it isn't sticky).

It appears this has been requested (and implemented?) for PrimeNG.  Could we get it in PF as well?  (see https://github.com/primefaces/primeng/issues/3965)

## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
Continue displaying the growl message when the mouse is hovering over the message, even if the 'life' property is set.

## 3) Actual behavior
Mouse hover over the growl message, the message disappears according to the 'life' property value.

## 4) Steps to reproduce
Set sticky to 'false' and life to some value.  Cause the growl message to appear, then mouse over.

## 5) Sample XHTML
```
<p:growl id="nonStickyLongMessages" life="6000" 
        showDetail="true" />
```

## 6) Recommendation
Re-write the setRemovalTimeout part of the Growl component (see below) to account for mouse hover:
```
,setRemovalTimeout:function(b){
	var a=this;
	var c=setTimeout(
		function(){
			a.removeMessage(b)
		}
		,this.cfg.life
	);
	b.data("timeout",c)
}
```
Maybe something that incorporates the following example (courtesy of https://stackoverflow.com/questions/3969475/javascript-pause-settimeout):

```
function Timer(callback, delay) {
    var timerId, start, remaining = delay;

    this.pause = function() {
        window.clearTimeout(timerId);
        remaining -= new Date() - start;
    };

    this.resume = function() {
        start = new Date();
        window.clearTimeout(timerId);
        timerId = window.setTimeout(callback, remaining);
    };

    this.resume();
}

var timer = new Timer(function() {
    alert("Done!");
}, 1000);

timer.pause();
// Do some stuff...
timer.resume();
```

**Comment by tandraschko** [comment]
@mertsincan Could you port that feature to PF? It's great actually
