### ISSUE TITLE
p:textEditor not formatting on 6.2RC1

### ISSUE THREAD

**Issue by ahmedelbadry3** [primefaces/primefaces#3197]
p:textEditor component dosent work on 6.2RC1.
in 6.1 it worked perfectly in terms of proper html formating of the string. It even behaves like that in the showcase.

Please help

**Comment by jxmai** [comment]
@ahmedelbadry3 Fixed recently https://github.com/primefaces/primefaces/commit/3785e37bae985bcf3b75b0b9b495d9903c348564. Please try to build from the latest source or to wait for RC2.

**Comment by tandraschko** [comment]
Duplicate
