### ISSUE TITLE
Datatable: Add functionaly to Paginator to manually enter the "jump to" page

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3198]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: latest
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: all

## 2) Expected behavior
Suppose I have 1000 lines data in table so the page will be 10 ( number of row per page 10)
And In pagonator I want to go directly to 8 number.
So instead of the page number can I have the text box in which I can enter the page number directly
...

## 3) Actual behavior
Not there

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
AFAIR we had a similar issue but can't find it.
Feel free to provide a PR or sponsor it via PrimeFaces PRO.

**Comment by tandraschko** [comment]
You can use {JumpToPageInput} now
