### ISSUE TITLE
Charts: Use Chart.js instead of jqPlot for charts

### ISSUE THREAD

**Issue by mafaul** [primefaces/primefaces#3201]
Please consider rewriting the Primefaces charts using Chart.js instead of jqPlot. 
JqPlot seems to be abandoned by the developer and chart.js seems quite active and popular.

https://github.com/chartjs/Chart.js
http://www.chartjs.org/

Created from popular comment on Issue https://github.com/primefaces/primefaces/issues/1030

> @melloware: I am not suggesting anyone tackle this now as its a huge undertaking but I am wondering if for PF 7.0 rewriting the charts for ChartsJS http://www.chartjs.org/ instead of jqPlot might be the best idea. JqPlot seems to be adbandoned by the developer and chartjs seems quite active and popular.

**Comment by melloware** [comment]
I recommended Charts.js because its popular and maintained unless anyone has any better suggestions.  

**Side Note:** I use HighCharts a lot which is awesome but its not an open source license like Chart.js is.   There is a HighFaces JSF though which I have not used I have just used JS to build my charts. http://www.highfaces.org/index.html

**Comment by mafaul** [comment]
Re: https://github.com/primefaces/primefaces/issues/1466
If it can't be backwards compatible, maybe we can create an entire new chart component set. Maybe `<p:canvasChart />` or something similar.

**Comment by melloware** [comment]
@mafaul I doubt it can be backward compatible as the current PF code was all custom code to support jqPlot and how it charts.

**Comment by tandraschko** [comment]
Just my 2 cents (I'm not working for PrimeTek):
Rewriting is high effort and i don't think it will be done without a PRO customer or some sponsoring.

I personally always use AnyChart in my JSF application. The model can be simple build with Java and serialized to JSON. I even don't have a custom widget or any additional logic for it. I'm very happy and i would never use anything else.

**Comment by melloware** [comment]
@tandraschko is right it would be a massive amount of work to replace jqPlot.

**Comment by tandraschko** [comment]
If anyone is interessted, i could share this small wrapper... It's very easy. But AnyChart isn't for free.

I think it's ok to buy a Chart library for a professional web application. For "fun" jqplot is actually enough.

**Comment by mydeadlyvenoms** [comment]
What about https://github.com/hatemalimam/ChartistJSF?
The project seems to be almost done, I always use it in my projects and it looks ways better then jqPlot.
Personally I think jqPlot looks like the last legacy component within PrimeFaces.

**Comment by markusg80** [comment]
I actualy got a new Project. And as like always i will do it with Primefaces! But with Primefaces chart its not possible to serve the requirements because they need grouped stacked barchart. And for me charts.js looks ways better. For me it would be great to have better charts component in Primefaces and it will make Primefaces a better framework. It will pay the effort

**Comment by mujdecisy** [comment]
adamsınız!

**Comment by cagataycivici** [comment]
PrimeNG and PrimeReact use chart.js but we should not break backward compatibility, new p:pieChart, p:lineChart components will be better.

**Comment by markusg80** [comment]
Very good decision to change charts to chart.js. Are you implementing those charts with the existing model classes to simplify transition? And are grouped stack bar charts also supported?

**Comment by Rapster** [comment]
@mertsincan What do you want to do with this issue?

**Comment by melloware** [comment]
My vote is to close this issue.

**Comment by Rapster** [comment]
See #4011 #4012 #4013 #4014 #4015 #4015 #4016 #4017

**Comment by marcelogore** [comment]
> If anyone is interessted, i could share this small wrapper... It's very easy. But AnyChart isn't for free.
> 
> I think it's ok to buy a Chart library for a professional web application. For "fun" jqplot is actually enough.

@tandraschko Actually, I'd be interested if you are still sharing.
