### ISSUE TITLE
Menu: add overlay timeout

### ISSUE THREAD

**Issue by Dougnlizt** [primefaces/primefaces#3209]
I see this might be getting added to primeng as an enhancement.  Could we also get it added to primefaces?

https://github.com/primefaces/primeng/issues/4828

## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
When mouse leaves the overlay menus, do not immediately hide the menu overlay but wait for a second. If user reenters, remove the timeout.  Or allow the 'fade' to be longer, prompting the user to re-position the mouse over the menu, at which point the timeout should be removed.

## 3) Actual behavior
When a user is using the mouse to read through a menu (especially a mega menu), if their mouse just barely goes outside of the bounds of the menu, then poof!  It's gone.  I've encountered this repeatedly in usability studies.

**Comment by melloware** [comment]
Going to close this one in favor of #9970
