### ISSUE TITLE
 $.jqplot and $.jqplot.CanvasManager.canvases  are undefined when using LineChartModel

### ISSUE THREAD

**Issue by djheroez** [primefaces/primefaces#321]
PF version: 5.1.4

When using a chart of type line:

``` html
<p:chart type="line"...>
```

I get the following javascript error:

``` javascript
   TypeError: $.jqplot is undefined
```

I workarounded this issue by manually adding the charts.js script and
the charts.css in my view, but when I do that it only works the first time I open my view. If I try to open my view again I get the following error:

``` javascript
TypeError: $.jqplot.CanvasManager.canvases is undefined
```

Notice that I'm loading the views using ajax, but if I reload the page and  open the affected view it works well again.

Taking a look at the **charts.js** script it seems that the problem is when calling `this.plot.destroy()` in the below function:

``` javascript
refresh: function(cfg) {
        if(this.plot) {
            this.plot.destroy();
        }

        this.init(cfg);
    },
```

Hope this helps.

**Comment by sudheerj** [comment]
Are you able to replicate the issue in showcase.Try to post your code as well.Use forum first.

**Comment by cagataycivici** [comment]
It is an issue on your end due to loading views with ajax, make sure chart resources are available on page already.
