### ISSUE TITLE
RestoreDynamicActions performance degradation with ProgressBar

### ISSUE THREAD

**Issue by iurii-nikolaev** [primefaces/primefaces#3211]
## 1) Environment
- PrimeFaces version: 5.3
- Application server + version: Wildfly 11 + Mojarra 2.2.16
- Affected browsers: Chrome 63

Primefacess progress bar with interval = 1000 and ajax = true.
![ic5k1](https://user-images.githubusercontent.com/6002995/35347788-3a2bdf24-0147-11e8-9ec3-1ac98f8f5af8.png)

**Comment by tandraschko** [comment]
Invalid - all infos missing.
Try MyFaces as Impl ;)
Also i think it's more related to the JSF impl instead of PF.
