### ISSUE TITLE
Widget Core: lifecycle events

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#3212]
This is a feature request for an upcoming PrimeFaces version (maybe already 6.2?). 

Currently you have to come up with an own logic on how to invoke some javascript function when a component is rendered / initialized / updated / destroyed / etc. This could be tricky if it is a DeferredWidget.

It would be a nice feature if all widget implement some kind of lifecycle callbacks so you only have to add the desired javascript function as an attribute to the widget. Possible callbacks could be: onInit, onRender, onUpdate, onRemove. Maybe the callbacks could even be split into _before_ and _after_ calls (onBeforeInit => at the start of init(); onAfterInit => at the end of init()).

**Comment by tandraschko** [comment]
first of all, 6.2 is alrady frozen for such features ;)
We already have callbacks:
init
refresh
destroy

and DefferedWidget provides the render callback.

**Comment by fanste** [comment]
I already thought that version 6.2 was frozen, but it was a try ;)

But those callbacks are not accessible from outside. Or did I miss something? 
As an example: I want todo something like:
```
<p:dataTable [...] onAfterRender="adjustDataTable">
   <p:column [...]>[...]</p:column>
   <p:column [...]>[...]</p:column>
</p:dataTable>
```
And my own javascript function `adjustDataTable` will be invoked with the instance of the widget right after the `render()` methods completes.

**Comment by tandraschko** [comment]
Do you need for a single dataTable or would actually execute this code application wide for each dataTable?

**Comment by fanste** [comment]
This would be for a specific dataTable.

**Comment by tandraschko** [comment]
I see.
I understand your point but the effort is quite to also provide those attributes for each widget.
Not sure if we will do this, we would need a much more global and easier solution.

**Comment by tandraschko** [comment]
@fanste do you still need it? If not, please close it.

**Comment by fanste** [comment]
It still would be a nice to have and may cleanup some of you hacky code. But yeah, I had no time to think about a good solution. As you said: introducing several hundreds of such event attributes is far too many work and not maintainable.

**Comment by tandraschko** [comment]
I think we can easily support 3 events:
postInit
postRefresh
preRestroy

as this is the same for every widget and inherited by core.widget.js

**Comment by melloware** [comment]
@tandraschko Not sure what you were thinking but we could do those in the widget as `callBehavior('postInit')` and then users could use `pe:javascriptBehavior` to attach if we didn't want to update the signature of every single widget in the taglib?

**Comment by tandraschko** [comment]
im thinking about something like:

```
<my:component>  
   <f:attribute name="widgetPostConstruct" value="blub();" />  
   <f:attribute name="widgetPostRefresh" value="blub();" />  
   <f:attribute name="widgetPreDestroy" value="blub();" />  
</my:component>
```

WDYT guys?

**Comment by melloware** [comment]
If you can add that generically to all components without intruding on components then I really like it

**Comment by tandraschko** [comment]
@melloware please review my commit. In general we only have to adjust all .init() calls now to pass the componet/widget and it should work for every component

**Comment by melloware** [comment]
Looks really good to me I like how clean this is to add this functionality.

**Comment by melloware** [comment]
Want me to update all the components?

**Comment by tandraschko** [comment]
please, yes
i commited it for one component now

**Comment by melloware** [comment]
OK i will add a showcase example too.

**Comment by tandraschko** [comment]
yeah, we also have to document in the core section somehow

**Comment by Rapster** [comment]
@melloware @tandraschko Remember this issue #3815? I remember you talking about JS lifecycle events to fix that issue. Only a workaround has been provided on this day, but maybe with your fix, it would be a better fix? I currently have issue with `p:outputPanel` since I need deferred loading on ajax request (e.g loading image on datatable pagination)...

**Comment by tandraschko** [comment]
i think this is another topic.
This issue here let you intercept a widget lifecycle with JS events

In #3815 i think it was talking about more global events like run deffered mode on "ajaxLifecycleFinished" instead instant.

**Comment by Rapster** [comment]
Ok, doesn't sound like an easy one...

Regarding the changes that has been made, we have both methods:
- `public WidgetBuilder init(String widgetClass, T widget);`
- `public WidgetBuilder init(String widgetClass, String widgetVar, String id);`

The first one (newly introduced) does `renderLifecycleCallbacks`, any reason the second init method doesn't? If it doesn't, we could replace every init call with the first one don't you think?

**Comment by tandraschko** [comment]
we can deprecate the old one, i just didnt remove it because of extensions like PFE which reuses our WidgetBuilder.

**Comment by melloware** [comment]
I aalready updated PFE for the new `init` so its safe to remove

**Comment by tandraschko** [comment]
PFE isnt the only extensions lib ;) I will deprecate it for now and remove in 11.0.

**Comment by melloware** [comment]
HA OK good call. Deprecate away.

**Comment by Rapster** [comment]
Ok, so we can migrate all our components with this new method, and deprecate the old one right?

**Comment by tandraschko** [comment]
its all migrated already

**Comment by Rapster** [comment]
Ah indeed my bad, I didn't realize that only PFE components were still using it, and my local repo has not been updated for a while, so all good :wink: I'll simply deprecate the old method then

**Comment by melloware** [comment]
I think Thomas just did and checked in in

**Comment by Rapster** [comment]
Yup unit tests have not been updated though

**Comment by melloware** [comment]
Just rebuilt PFE and can confirm we have no deprecation warnings so that is good.

**Comment by tandraschko** [comment]
yeah, will align the tests now

**Comment by Rapster** [comment]
I'm on it if you didn't start yet

**Comment by tandraschko** [comment]
all right :)
