### ISSUE TITLE
XSS vulnerability in ButtonRenderer

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3213]
## 1) Environment
- PrimeFaces version: primefaces-6.2.RC2-SNAPSHOT
- Application server + version: Wildfly 11
- Affected browsers: all

## 2) Expected behavior
`href ` and `target` attributes should be properly escaped in ButtonRenderer to prevent XSS when used in javascript context.

## 3) Actual behavior
XSS vulnerability

## 4) Steps to reproduce
Click at the button included in the sample. A alert box will appear.

## 5) Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">  
	<h:head>
		<title>XSS vulnerability in ButtonRenderer</title>
	</h:head>
	<h:form>
	    <p:button value="Do not click me!!!" href="mailto:contact@primetek.com.tr?subject=#{bean.userSuppliedInput}" />
	</h:form>
</html>  
```

## 6) Sample bean
```
package de.test.primefaces;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named("bean")
@SessionScoped
public class Bean implements Serializable {

	public String getUserSuppliedInput() {
		return "');alert('XSS vulnerability in ButtonRenderer');//";
	}

}
```

## 7) Mitigation
In ButtonRenderer properly escape strings that are used in JS context (`targetURL `and `button.getTarget()`):

![image](https://user-images.githubusercontent.com/13161711/35385480-be677416-01c8-11e8-804d-652974b12f21.png)

**Comment by tandraschko** [comment]
Yep, a good catch :D
JS is allowed in href actually but not in p:button as it's requires a window.open instead native href attribute.

**Comment by cnsgithub** [comment]
Please forget about the commit, automatic save actions in my IDE led to reformatting and wrong class import (AWT button ;-)), sorry... It has not yet been a pull request...

Anyways, the proposed fix using ComponentUtils.escapeEcmaScriptText seems to be insufficient, the method name was promising for me, however it's a bit misleading.

I recommend OWASP encoding (https://github.com/OWASP/owasp-java-encoder/) once again...

**Comment by melloware** [comment]
Did you try just regular ComponentUtils.escapeText() instead of EscapeEcmaScript.  They have different uses.
