### ISSUE TITLE
p:textEditor not rendered when there is a strange/bad character in the value

### ISSUE THREAD

**Issue by jllado** [primefaces/primefaces#3215]
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Tomee 7.0.4
- Affected browsers: all

## 2) Expected behavior
When there is a bad/strange character in the textEditor value, the renderer should show the component. Or skip that character. Or at least, show some feedback (maybe an error in logs).

## 3) Actual behavior
Currently when there is a strange/bad character in the textEditor value, the renderer skip the whole component.

## 4) Steps to reproduce
You can test it on your showcase site.

1. Go to https://www.primefaces.org/showcase/ui/input/textEditor.xhtml
2. You have to write a text with a bad/strange character. You can get it from this file:
https://gist.github.com/jllado/f894dfb8bc2438c62188b4e5ee8170d7 
3. Press Submit button

## 5) Sample XHTML
n/a

## 6) Sample bean
n/a

**Comment by jxmai** [comment]
I cannot replicate the bug on 6.2 snapshot

the sample content is the gist you provided: 

https://gist.github.com/jllado/f894dfb8bc2438c62188b4e5ee8170d7


![image](https://user-images.githubusercontent.com/10467831/35398934-bbb83e54-01b8-11e8-8311-e778e5d6539b.png)


![image](https://user-images.githubusercontent.com/10467831/35398947-c2efbddc-01b8-11e8-91f2-387ed1c26784.png)

**Comment by cnsgithub** [comment]
that "strange" character seems to be a Vertical-Tab. Maybe some Copy&Paste from MS Word? 

![image](https://user-images.githubusercontent.com/13161711/35436651-8af559be-028f-11e8-8696-4da208305580.png)
