### ISSUE TITLE
Messages does not escape non-unicode characters

### ISSUE THREAD

**Issue by samhalpa** [primefaces/primefaces#322]
This issue can be seen only in p:messages. it is perfectly working in p:growl. If we pass a string with non-unicode charaters to messages it wont display it, but in p:growl, it will clean the string using ComponentUtils.escapeText method before rendering the message.
Shouldn't p:messages be working as p:growl?
Following code segment should be modified of MessagesRenderer#encodeSeverityMessages.

``` java
String summary = msg.getSummary() != null ? msg.getSummary() : "";
String detail = msg.getDetail() != null ? msg.getDetail() : summary;
```

This is how it is implemented in GrowlRenderer

``` java
 String summary = escapeText(message.getSummary());
 String detail = escapeText(message.getDetail());
```

**Comment by cagataycivici** [comment]
Growl renders javascript, Messages render markup via ResponseWrite so for growl is a must. For messages we just use ResponseWrite.write apis just like regular JSF components.
