### ISSUE TITLE
Spinner: add input validation

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3223]
## 1) Environment
- PrimeFaces version: primefaces-6.2.RC2-SNAPSHOT
- Application server + version: WildFly 11
- Affected browsers: all

## 2) Expected behavior
It must be guaranteed, that the value of p:spinner is between min and max. Just doing client side validation is insufficient. The server also has to validate the submitted value.

## 3) Actual behavior
Range checks are performed on client side via JS only. So it's easily possible to bypass validation at all.

## 4) Steps to reproduce
In developer tools (F12) update the spinner's value in the DOM to an invalid, say negative value:
`$('.ui-spinner-input').val("-1")` Then submit the form by pressing the button.

## 5) Sample XHTML
```xml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">  
	<h:head>
		<title>Spinner test</title>
	</h:head>
	<h:form>
	    <p:spinner value="#{bean.value}" min="0" max="10" />
	    <input type="submit" value="Submit" />
	</h:form>
</html>  
```

## 6) Sample bean
```java
package de.test.primefaces;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named("bean")
@SessionScoped
public class Bean implements Serializable {

	private int value;
	
	public int getValue() {
		return value;
	}

	public void setValue(int value) {
		this.value = value;
	}
	
}
```

## 7) Mitigation
Just repeat the range checking in SpinnerRenderer. Reset the value to min if value<min, reset it to max if value>max. See https://www.owasp.org/index.php/Input_Validation_Cheat_Sheet#Client_Side_vs_Server_Side_Validation for further information and general guidelines.

**Comment by cnsgithub** [comment]
Sorry, this is not just an enhancement, it's rather a security issue...

**Comment by tandraschko** [comment]
it's a mix of both - you can also attach validators like with every components.
