### ISSUE TITLE
Datatable: add "show total number of rows" functionality

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3229]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
I want in datatable paginator should have totalrecords option 
To always show how many total recored we have in datatable.

## 3) Actual behavior
As of now I gone through the document at page 146 under heading "Custom Content in Paginator"
but its show how you can show new template but not show where you get the value of total recoreds,

In showcase this example is not there.

I seted that one also but not able to set the CSS for that because its internal part of the Prime.
 
## 4) Steps to reproduce

.. 

## 5) Sample XHTML

<p:dataTable var="car" value="#{dtFilterView.cars}" widgetVar="carsTable" paginator="true" rows="10"
  paginatorTemplate="{totalRecords} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
  rowsPerPageTemplate="5,10,15" >

<f:facet name="{totalRecords}">
			<h:outputText value="Total:">1000</h:outputText>
 </f:facet>

## 6) Sample bean

..

**Comment by cnsgithub** [comment]
I don't know if this should require a code-change as it is possible to get the total size quite easily by calling the appropriate method 

1.) if value it is a collection use #{value.size()}
2.) if value is a implementation of LazyDataModel probably just perform rowCount  * pageSize

**Comment by melloware** [comment]
This is already possible with currentPageReportTemplate {totalRecords}...
```
currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords}"
```
