### ISSUE TITLE
Calendar in disable mode not having Image Icon

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3232]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: Latest
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
When Calendar is disable the Image Icon should be show otherwise you not able to find is this a calendar input field or normal input field.

## 3) Actual behavior
When you make the calendar in disable mode its not having the Calendar Image ICON
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

<p:calendar id="calendar1" Pattern="dd/M/yy hh:mm a" disabled="true" showOn="both"/>

## 6) Sample bean

..

**Comment by tandraschko** [comment]
The icon is shown for me with current github master.
