### ISSUE TITLE
InputMask: lack of user input validation

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3234]
## 1) Environment
- PrimeFaces version: primefaces-6.2.RC2-SNAPSHOT
- Application server + version: WildFly 11
- Affected browsers: all

## 2) Expected behavior
It must be guaranteed, that the value of p:inputMask matches the pattern defined via `mask` attribute. Just doing client side validation is insufficient. The server also has to validate the submitted value.

## 3) Actual behavior
Validation of user input is performed on client side via JS only. So it's easily possible to bypass validation at all.

## 4) Steps to reproduce
In developer tools (F12) update the inputMask's value in the DOM to an invalid value:
`$(".ui-inputfield").val("DO NOT CALL ME");` Then submit the form by pressing the button.

## 5) Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">  
	<h:head>
		<title>inputMask test</title>
	</h:head>
	<h:form>
	    <p:inputMask value="#{bean.phone}" mask="(999) 999-9999? x99999" />
            <input type="submit" value="Submit" />
	</h:form>
</html> 
``` 

## 6) Sample bean
```
package de.test.primefaces;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named("bean")
@SessionScoped
public class Bean implements Serializable {
	private String phone;

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
}
```

## 7) Mitigation
Just repeat the input validation in InputMaskRenderer. Reject the value if it isn't conform with the specified mask. See https://www.owasp.org/index.php/Input_Validation_Cheat_Sheet#Client_Side_vs_Server_Side_Validation for further information and general guidelines.

**Comment by tandraschko** [comment]
Yep, good catch!
Workaround: attach a regex validator.

Also not sure if we can easily validate based on the mask in Java.

**Comment by cnsgithub** [comment]
jquery.maskedinput is used on the client side: https://github.com/digitalBush/jquery.maskedinput

Translating the mask into regex on the server side should be straightforward as long as own mask definitions are not supported by PrimeFaces. Do you support them?

**Comment by tandraschko** [comment]
What do you mean by own mask definitions?

**Comment by cnsgithub** [comment]
jquery.maskedinput lets you define your own rules aka mask definitions, e.g. ~ can be defined to be mapped to + or -. Example from https://github.com/digitalBush/jquery.maskedinput

```
jQuery(function($){
   $.mask.definitions['~']='[+-]';
   $("#eyescript").mask("~9.99 ~9.99 999");
});
```

However, PrimeFaces does not seem to implement this feature. So I ignored it in my commit.

**Comment by cnsgithub** [comment]
Pull request: https://github.com/primefaces/primefaces/pull/3237

**Comment by melloware** [comment]
@cnsgithub Apparently PrimeFaces did support the mask.definitions option.  A user on StackOverflow reported this regression issue here when he upgraded to PF 7.0.  
https://stackoverflow.com/questions/57523231/primefaces-inputmask-accept-only-hex

**Comment by mertsincan** [comment]
Added validateMask="true|false(default)" attribute. https://github.com/primefaces/primefaces/issues/5105
