### ISSUE TITLE
Calendar: input using mask can't be cleared

### ISSUE THREAD

**Issue by amayr666** [primefaces/primefaces#324]
Hello,
we're using Primefaces 5.2.3. Our component making problems is a calendar with a mask set. If it is filled with a value and we remove this and click out of the calendar, the value is automatically entered again. So we currently can't delete the values from the calender if it should be empty... The only workaround I found is using PF(...).setDate(null). But this is just ugly and doesn't work as expected. Is there any other solution?

**Comment by cagataycivici** [comment]
I can't replicate at;

http://www.primefaces.org/showcase/ui/input/calendar.xhtml

**Comment by amayr666** [comment]
it's added as 
    <p:calendar id="pickupToDate" pattern="dd.MM.yyyy HH:mm"  
    value="#{createOrder.pickupTimeTo}" mask="true"/>
in our xhtml. 

When I click in and remove the value 
![image](https://cloud.githubusercontent.com/assets/5585988/7766267/dc38e66a-0067-11e5-8990-48b1ab464f59.png)

it automatically sets back to what was entered after bluring out of the calendar
![image](https://cloud.githubusercontent.com/assets/5585988/7766280/f3469186-0067-11e5-94b7-7377b803fe53.png)

**Comment by cagataycivici** [comment]
So it happens when timepicker is enabled, would be great if you can provide a patch via pull request.

**Comment by amayr666** [comment]
I'd love to provide one, but I still haven't found the actual problem.

**Comment by cagataycivici** [comment]
It is probably timepicker as without it, no conflicts occur. Note that there are 3 plugins here;
- jQuery DatePicker
- jQuery TimePicker
- Masked Input

So I'm pretty sure timepicker is restoring the value.

**Comment by olpf** [comment]
I experienced something similar. If mask is set to true and the value is submitted with ajax event blur, I get a validation error message. If the same calendar is submitted with the form by a button click, it is possible to set the empty value without validation error.

```
<h:form id="form1">
    <p:messages autoUpdate="true"/>
    <p:calendar value="#{calendarBean.value}" pattern="dd/MM/yyyy" mask="true" />
    <p:commandButton process="@form" value="Submit" />
</h:form>

<h:form id="form2">
    <p:messages autoUpdate="true" redisplay="false"/>
    <p:calendar value="#{calendarBean.value}" pattern="dd/MM/yyyy" mask="true">
        <p:ajax event="blur" />
    </p:calendar>
</h:form>
```

Leaving field of form2 leads to validation/conversion error.
I am using PF 5.2.6.

**Comment by mp123456** [comment]
for anyone else who has come across this problem I found the solution:
set keepInvalid to true

**Comment by melloware** [comment]
@mp123456 I believe KeepInvalid is for DatePicker and not for Calendar which this issue is for?

**Comment by mp123456** [comment]
> @mp123456 I believe KeepInvalid is for DatePicker and not for Calendar which this issue is for?
it is for primeng calendar. see the documentation here :https://www.primefaces.org/primeng/#/calendar

**Comment by christophs78** [comment]
@tandraschko : DatePicker (which should replace Calendar) does not have mask - feature.
https://primefaces.org/primeng/showcase/#/calendar does not have a mask too. So nothing to backport from PrimeNG to PrimeFaces.

**Comment by christophs78** [comment]
https://github.com/primefaces/primefaces/issues/4546
