### ISSUE TITLE
Printer: replace JS plugin

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3242]
jqprint (used in printer.js) should be replaced by a newer library to make development of new features possible and to ensure compatibility with future jQuery versions

https://github.com/crabbly/print.js
http://printjs.crabbly.com/

**Comment by tandraschko** [comment]
If the implementation is done by the community and provides the same features -> +1 from my side.

**Comment by melloware** [comment]
Chose https://github.com/DoersGuild/jQuery.print because

1. It Jquery based so swapping out the old plugin was easy.
2. Its been updated for Jquery 3.X 
3. I tested on Chrome, IE, Firefox, and Edge and all working as expected.
4. Small size and decent features.

**Comment by melloware** [comment]
Updating to 1.6.2 now supports Canvas finally as well.
