### ISSUE TITLE
Clock/Mindmap: Update raphael.js

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3243]
raphael.js 2.1.0 is ~6yrs old.

Also latest version is 2yrs old: 
https://github.com/DmitryBaranovskiy/raphael/tree/v2.2.7

So it might be worth considering an an alternative or try to implement it without use of a third-party library (at least the clock should be easy to do) - as for the mindmap i'm not sure, but probably should be doable too

![image](https://user-images.githubusercontent.com/13161711/35513381-21601c70-0503-11e8-8974-3ff7118a24f9.png)

**Comment by tandraschko** [comment]
Updating for 6.3 should be no problem.

For the new implementation: If the implementation is done by the community and provides the same features -> +1 from my side.
Probably there are better plugins available now.
