### ISSUE TITLE
Watermark: deprecate it in favor of html placeholder

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3244]
Probably the whole watermark component can be removed, as stated in the showcase https://www.primefaces.org/showcase/ui/misc/watermark.xhtml it is only for compatibility reasons. However in the latest release jQuery 3.x made browsers like IE8 incompatible anyway.

Browsers without support for input place holder attribute 
https://caniuse.com/#search=input%20placeholder%20attribute
could use a polyfill for this. e.g. : https://github.com/ginader/HTML5-placeholder-polyfill/tree/v2.1.0

This would remove unneccesary 623+ lines of code from primefaces

**Comment by melloware** [comment]
I think the watermark is also used for people who can't use JSF passthrough attributes yet if they are on JSF 2.0 still. 

So maybe we deprecate it in 6.3 and remove it in 7.0?

**Comment by cnsgithub** [comment]
I think at least the *.js lib should be removed for 6.3. As for the JSF problem, the component itself could still exist, but instead of using the plugin js it would just render placeholder (so passtrough is not needed). And in the component description it should be noted that the a polyfill should be added if old browsers are targeted

**Comment by tandraschko** [comment]
Deprecate it in 6.3 and remove it in 7.0 sounds like a good agreement.

**Comment by tandraschko** [comment]
and: as jquery 3 doesn't support IE8, we can't support it anymore.

**Comment by tandraschko** [comment]
We can't remove it for now as IE9 doesn't support placeholder.
I would do the following:
remove the JS in 7.0 and replace it by a simple script which sets to placeholder attribute. So even JSF2.0 users can use it.

**Comment by melloware** [comment]
Excellent change.

**Comment by christophs78** [comment]
I think we finally can deprecate/remove this. 
All browsers since IE10 support placeholder. https://caniuse.com/input-placeholder
(Just talked to a colleague, which was mislead by this component.)

**Comment by tandraschko** [comment]
I didnt remove it because of JSF2 users. If you check the source, it just sets the placeholder attr

**Comment by tandraschko** [comment]
Updated the docs

**Comment by christophs78** [comment]
p:InputText even has dedicate placeholder-attribute:
https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/inputtext/InputTextBase.java#L38
So you even dont need passthrough attributes.

**Comment by tandraschko** [comment]
but not h:* components
