### ISSUE TITLE
Update Signature plugin for jQuery UI to v1.2.0

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3246]
PR incoming...
https://github.com/primefaces/primefaces/pull/3247

**Comment by melloware** [comment]
I was messing around with this before and I found one bug.  The Signature background for submitted version was not right.  It should look like this.  Can you confirm yours looks like this?  For me it did not look right on the grey "submitted" version.
  
![image](https://user-images.githubusercontent.com/4399574/35520625-8a32de40-04e5-11e8-81f9-2bce9ddea1a4.png)

**Comment by cnsgithub** [comment]
I tested it and it works without problems. The colors are not hardcoded (and they weren't before). So if you don't set a color it will always be with a white background and a black line when readonly is false. If read-only is true it will have an opacity of 0.35 as standard starting with V.1.2.0 The colors itself can be set via backgroundColor="#eaeaea" color="#03a9f4" just like in the showcase. 
If the opacity is not wanted, i can also remove the line causing it in kbw-signature-disabled (signature.css). 
 

![image](https://user-images.githubusercontent.com/13161711/35551702-9db1293a-0590-11e8-9e40-b5cb78143937.png)

**Comment by melloware** [comment]
Got it.  Nice work!
