### ISSUE TITLE
radion button column header name

### ISSUE THREAD

**Issue by nusivtech** [primefaces/primefaces#3248]
I am not finding anyway to give a custom header for the radio button column.

**Comment by tandraschko** [comment]
No examples -> invalid.
Also your text is not very detailed...
Maybe try the forum first ;)

**Comment by nusivtech** [comment]
Thanks for your response.
I have used (https://www.primefaces.org/primeng/#/datatable/selection)
on RadioButton the header name is blank. Please let me how can i can add header for Radio button column.
Attach for the reference.
![radiobutton_primeng](https://user-images.githubusercontent.com/15810812/35824046-2fa10aa0-0a77-11e8-9314-055a839d1a25.png)

**Comment by melloware** [comment]
@nusivtech You want the PrimeNG Issues list not the PrimeFaces issue list.  Go here instead: https://github.com/primefaces/primeng/issues
