### ISSUE TITLE
Enhance advanced p:fileUpload responsivity

### ISSUE THREAD

**Issue by michelrisucci** [primefaces/primefaces#325]
This issue is just to enhance this Primefaces component and make it more responsive.
When resizing it, I found this:
![pu](https://cloud.githubusercontent.com/assets/1094167/7757860/c13b1ea0-ffdb-11e4-882c-ca982af779e4.png)

**Comment by cagataycivici** [comment]
5.3 focuses on responsives so we'll check, thanks.

**Comment by tandraschko** [comment]
Does it still occur with a current version?

**Comment by melloware** [comment]
@tandraschko I believe this issue was fixed already with ticket https://github.com/primefaces/primefaces/issues/2226 and this can be closed.

**Comment by melloware** [comment]
@mertsincan and @tandraschko this defect should be closed as it is fixed by #2226
