### ISSUE TITLE
ImageCompare: migrate to newer JS plugin

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3251]
I've found this one which seems to be nice:

https://github.com/NUKnightLab/juxtapose
https://juxtapose.knightlab.com/

A PR will follow, where i have tested this, and it seems to work fine with the current features

This will open the possibility to add new features such as:

- Date of the picture 
- Credit of the picture
- Responsive design
- Animation
- Does not rely on bitmap images

**Comment by tandraschko** [comment]
2 things @cnsgithub:
1) Could you please check if the license is compatible? AFAIK it's no problem to reuse MIT or Apache licenses but not sure about MPL
2) and please update https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/NOTICE.txt

**Comment by cnsgithub** [comment]
I'm not a lawyer but i think it should be okay ? 

https://choosealicense.com/licenses/

**Comment by cnsgithub** [comment]
FYI: Just opened an issue since the Flickr API key is hardcoded in juxtapose and therefore shared amongst all users. See https://github.com/NUKnightLab/juxtapose/issues/139 for further information.
