### ISSUE TITLE
Calendar: does not have next and previous button for both Year and month

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3254]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: Latest 
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
 Using the calendar and able to change the next and previous month by using the button(next & previous) but for year change button its not there (next & Previous).

Note: I dont want to use navigator functionality

## 3) Actual behavior
in Calendar popup  year change button its not there (next & Previous type ).

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
Likely it's not available in the native jquery plugin.
So the only change could be to sponsor it via PrimeFaces PRO.

**Comment by cnsgithub** [comment]
Maybe a nicer calendar lib could be used as well in future

https://chmln.github.io/flatpickr/examples/

The current implementation has quite a few problems
https://github.com/primefaces/primefaces/issues?utf8=%E2%9C%93&q=calendar

@ankitacroit09 If you just need year back and forward, you might want to implement it via JS. If you use widgetVar you can access the calendar's dom and see the available functions. From there you should be able to create buttons which justchange the selected option of "ui-datepicker-year"

**Comment by tandraschko** [comment]
Most of the "issues" are actually feature requests:
https://github.com/primefaces/primefaces/issues?page=1&q=is%3Aopen+Calendar&utf8=%E2%9C%93

**Comment by kukel** [comment]
Plus that it is (via (imo) wrong reasoning)  a lot of work to theme it according to all the rest of the components in PrimeFaces that follow the jquery-ui theming since it has its own theming... 

Quote from their site
> Almost every large SPA or project involves date and time input. There are limited options, however, if you also prefer to keep your projects lean and consequently stay away from heavy frameworks such as jQuery, or even Bootstrap.
>
>Appalled at the fact that I have to load 300kb of jquery and jquery UI or hook up bootstrap just to use a calendar, I created this [date][time]picker that's powerful, easy to use, and looks good out of the box.
>
>Written in vanilla javascript, works with anything, anywhere.

And then also comparing apples and oranges (size-wise)... 

My suggestion: don't use it.

**Comment by cnsgithub** [comment]
Well arguing not to use a plugin/lib because it does not follow jquery-ui theming is funny. Did you see the list of other third party libs primefaces uses (#3256) which are not following jquery-ui theming ;) But ultimately it's the choice of the PF developers. My feeling just is that the jquery-ui date/time picker has a UX straight out of Year 2008~ Especially Year selection is annoying as it was already stated in some issues.

**Comment by Marlysson** [comment]
Guys, some new about this feature, I'm use the 6.0 version of primefaces and yet don't show the "next/previous button" to change date in calendar.

![sem titulo](https://user-images.githubusercontent.com/4117999/39129080-e00abba8-46df-11e8-9113-c055f4d06690.png)

**Comment by kukel** [comment]
Did you check the 6.2 showcase? it is there and always has been. Did you
check the client-side 'view source'

**Comment by Marlysson** [comment]
@kukel I'm using the Primefaces on 6.0 version..

Analysing the page's view-source I visualized that the classe "datepicker-header" responsible to show the current Month/Year and Next/Previous buttons don't appears ..

**Comment by melloware** [comment]
Since this won't be implemented in the native jquery Calendar I am closing this feature request.
