### ISSUE TITLE
Keyboard: update plugin

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3255]
http://keith-wood.name/keypad.html

Version should be updated from v.1.2.4 to v2.1.0

I've seen in the commit history that the component was broken after jquery update, and only the "broken" places were changed. Why not invest some more minutes and update the lib instead when this happens ;-)

**Comment by melloware** [comment]
I use another Keith Wood component in Extensions for Calculator.  For me I just fixed the Jquery 3.0 things because it doesn't seem like Keith is too active right now.   So I would agree with you let's update it and fix the Jquery 3.0 things by hand.
