### ISSUE TITLE
[Documentation] Create a list of all js third-party libraries used on client side

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3256]
It would be useful to have a list of all third party client libs used in the documentation, to consider if the project using primefaces cann add them too or not, and if conflicts in js or css may arise. 

What i have found:

- jqPlot
- color picker from www.eyecon.ro
- ContentFlow from http://www.jacksasylum.eu/ContentFlow
- Simple Js Inheritance by  http://ejohn.org/
- diagram.js v 2.1.0 from ???
- Interface elements for jquery http://interface.eyecon.ro (dock)
- CLEditor WYSIWYG HTML Editor v1.4.5
- FontAwesome 4.7.0 Font
- jQuery Iframe Transport Plugin 1.8.3
- jQuery File Upload Plugin
- jQuery Hotkeys Plugin 
- Idle Timer - v1.1.0 - 2016-03-21 https://github.com/thorst/jquery-idletimer
- jQuery beforeafter plugin
- jquery.Jcrop.js v0.9.12
- jQuery Cycle Plugin (with Transition Definitions)
- Metadata - jQuery plugin for parsing metadata from elements
- autoNumeric.js
- jQuery Autosize Autosize 3.0.6
- jQuery Browser Plugin v0.0.6
- jQuery plugin for getting position of cursor in textarea
- jQuery Cookie Plugin v1.4.1
- jQuery Masked Input Plugin
- jQuery MouseWheel / jQuery Mousewheel 3.1.13
- jQuery Rangy
- jQuery UI - v1.12.1 - 2017-08-09
- jQuery Timepicker Addon - v1.6.3 - 2016-04-20
- jQuery UI Touch Punch 1.0.5 https://github.com/RWAP/jquery-ui-touch-punch
- Keyboard.js http://keith-wood.name/keypad.html 
- jQuery keyfilter https://github.com/akzhan/jquery-keyfilter
- jQuery Knob (2012)
- jquery.layout 1.5.12 https://github.com/GedMarc/layout
- moment.js 2.18.1
- Quill Editor v1.3.4
- Atmosphere.js
- timeline.js
- TouchSwipe - jQuery Plugin
- Signature http://keith-wood.name/signature.html
- jScrollPane - v2.0.19 - 2013-11-16
- FullCalendar v2.9.1
- jQuery Roundabout - v2.4.2
- Raphaël 2.1.0
- Jquery.print https://github.com/DoersGuild/jQuery.print
- WebcamJS v1.0.21 / webcam.swf Flash

Also i will try to add update this list with "used" and "latest" version so priorities could be made for updating. The oldest ones should be updated first. Quite a lot of them are several years old.

**Comment by Rapster** [comment]
New feature? Enhancement perhaps
