### ISSUE TITLE
Improve the DOM structure of selectItems on SelectOneListbox

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3258]

**Comment by kukel** [comment]
Please document this very carefully since it might (for some users) break backwards compatibility

**Comment by mertsincan** [comment]
Thanks a lot for your comment, but I don't think it'll break backward compatibility. I added only <span> tag into < li > item tag and it doesn't have any CSS style.

Old code;
```<li>Omega</li>```

New code;
```<li><span>Omega</span></li>```
