### ISSUE TITLE
DataTable: add option to show amount of entries

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#3260]
In Primefaces 6.1.12 there is currently (as i knowed ?) no default template for showing the 
current number of rows/entries in the datatable.

I know that a custom paginator template can be added but not the of the current entries
because in an additional paginator template i don't know nothing about the activated/enabled filters
on the client side and this could be a challange to add it outside Primefaces...

_As example something like this - Please forgive me the not perfect 
prepared screenshot, but so you can better see what i mean:_

![primefaces showcase-datatable-example](https://user-images.githubusercontent.com/652355/35609967-e5efdcbc-065f-11e8-9d87-df37e49fed5f.png)

**Comment by tandraschko** [comment]
I can't follow. As our issue template states: Examples, Actual Behavior and Expected Behaviors helps to understand ;)

**Comment by ssibitz** [comment]
_I can't give you a current example here because the
highlighted Text in the Paginator is missing in primefaces !!_

I have prepared an image to better understand:
16 entries: Complete current entries in the datatable
1-4 : Currently showing entry 1 to 4 on current page
so... 1-4 of 16 means: Showing entry 1 to 4 of 16 entries...

**Or other saying:**
There is actually no way to display the current item count of all items in the DataTable
as i described before...

**Comment by ssibitz** [comment]
_By the way:_

Even if I wanted, I could not give you an example because the Primefaces 6.2-SNAPSHOT
build is currently broken and not buildable when i try to build it with maven.

And yes, i have read the tutorials and know how to build it right.
I become a lot of exceptions with missing files which i also can not see in the repository...

**Comment by ssibitz** [comment]
I am using the following command for building the Primefaces 6.2.RC2-SNAPSHOT :
**mvn clean install -Prelease**


And get the following error - attached as LogFile because there are too many errors:

[PrimefacesBuild.txt](https://github.com/primefaces/primefaces/files/1681902/PrimefacesBuild.txt)

**Comment by tandraschko** [comment]
for "by the way" please try the forum instead always putting several stuff in a single ticket.
The build works fine for me - also Travis works fine.

**Comment by ssibitz** [comment]
I will put it in the thread,
but what's about this ticket ?

Is it possible in the primefaces datatable to show the complete number of entries ?

**Comment by melloware** [comment]
@tandraschko @Rapster @ssibitz This ticket can be closed.  This is already possible like this..

```
currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords}"
```
