### ISSUE TITLE
DataTable: Paginator having issue while doing filtering datatable row based on Ajax Call

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3261]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: Latest
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: All

## 2) Expected behavior
What I am doing is I have one input field based on the value enter Datatable rows are showing the matched rows (updating).
I have set the "rows per Page" template in the end of paginator but when I am entering the value in text field doing submit and datatable rows updatingand should show the "rows per Page" to last position (what is before I set )in paginator and the style What I applied it should take.

## 3) Actual behavior
What I am doing is I have one input field based on the value enter Datatable rows are showing the matched rows (updating).
I have set the "rows per Page" template in the end of paginator but when I am entering the value in text field doing submit and datatable rows updating but the "rows per Page" is moved from last to first position in paginator and the style What I was applied is not taking the dropdown for same

## 5) Sample XHTML
 <p:inputText id="search" value="#{Bean.searchField}" rendered="#{Bean.rowsAvailable}">
                            <p:ajax event="keyup" update="list"/>
 </p:inputText>

<p:dataTable  id="wrList" widgetVar="wrList" rows="#{Bean.rows}" var="Record" value="#{Bean.worldRecords}" rendered="#{Bean.rowsAvailable}" paginator="true" 
paginatorTemplate=" {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
 rowsPerPageTemplate="5,10,15">

## 6) Sample bean

..

**Comment by ankitacroit09** [comment]
When this changes will be available for public use

**Comment by tandraschko** [comment]
which change?

**Comment by ankitacroit09** [comment]
correction for this defect

**Comment by tandraschko** [comment]
There are currently no plans to fix it. This is a community issue tracker.
If you need a fix, you can do:
1) use the support (PrimeFaces PRO)
2) provide better analysis and a PR

**Comment by melloware** [comment]
closing as invalid.  Please provide a runnable sample using the Primefaces Test project.  I can't understand what your actual issue is.
