### ISSUE TITLE
Check if we really need to render data-widget

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3263]
As we already have a id<>widgetVar mapping and the widget itself also can access the widgetVar via cfg

**Comment by schlebe** [comment]
Just for info, 

For DialogFramework it is not possible to define a custom ID. If you take the decision to replace widgetvar by id, and to remove data-widget,  don't forget to allow custom ID for DialogFramework :-)

**Comment by cnsgithub** [comment]
You may also rethink your UI. I got a pretty complex JSF application without the use of the DialogFramework. Almost anything can be done by using regular components as well if the dialog framework is giving you headaches.  Also a lot of dialogs are not very user-friendly in my opinion. You can use p:commandButton in combination with p:confirm as well. Dialogs these days are also counterproductive if the webpage / app is going to be used on mobile devices, as responsiveness is much harder to achieve.

**Comment by schlebe** [comment]
@cnsgituhb: I prefer to use DialogFramework for reusability at to avoid using some "include". I find this cleaner and more easy to debug. 
There exists another solution (the best for me) that is Client/Server :-)

**Comment by tandraschko** [comment]
It's only used by some special components, i just refactored a little bit for now.

**Comment by schlebe** [comment]
If I understand well your code,
widgetvar-data = full-widget-id-with-form-name + '_dlgwidget' 

but for DialogFramework, who decide of dialog-widget-id ? Primefaces ? or developper using a new (or already existing) option that allows dialog-widget-id definition ?

**Comment by tandraschko** [comment]
I don't know, also it's not related to that ticket. I just refactored the data attribute name for the DF to match the other parts of PF.
