### ISSUE TITLE
fileUpload: filename returned by UploadedFile should be sanitized

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3269]
## 1) Environment
- PrimeFaces version: primefaces-6.2.RC2-snapshot
- Application server + version: WildFly 11
- Affected browsers: all

## 2) Expected behavior
The filename returned by `UploadedFile ` should be sanitized. Otherwise, this may lead to path traversal vulnerabilities if developers use `UploadedFile.getFileName` to write to the file system - which is common practice and likely to happen. Maybe `NativeUploadedFile.write` could provide some protection as well, e.g. by providing a properly defined interface and strict separation of path and filename.

## 3) Actual behavior
Some complicated escaping seems to be done in `NativeUploadedFile.getContentDispositionFileName`, however it is still possible for the attacker to send a specially crafted POST request that contains e.g. `.. ` or paths in the filename. In the worst case malware could be uploaded to system locations or server config files could be overridden. The filename could for example be sanitized by means of `FilenameUtils.getName ` from Apache commons-io.

## 4) Steps to reproduce
Open the sample XHTML, choose a file to upload, switch to console and enter the following code:
```javascript
	var formData = new FormData(); 
	formData.append($("form").attr("id"),$("form").attr("id")); 
	formData.append($("input[type=file]").attr("id"),$("input[type=file]")[0].files[0],'../../windows/malware.dll');
	formData.append($("button").attr("id"),"");
	formData.append("javax.faces.ViewState",$("input[name$=ViewState]").val());
	var request = new XMLHttpRequest();
	request.open("POST","fileUpload.xhtml");
	request.send(formData);
```

## 5) Sample XHTML
```xml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">  
	<h:head>
		<title>fileUpload test</title>
	</h:head>
	<h:form enctype="multipart/form-data">
	    <p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true"/>
	 
	    <p:commandButton value="Submit" ajax="false" actionListener="#{fileUploadView.upload}" />
	</h:form>
</html>  
```

## 6) Sample bean
```java
package de.test.primefaces;
 
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import org.primefaces.model.UploadedFile;
 
@Named("fileUploadView")
@SessionScoped
public class FileUploadView implements Serializable {
     
    private UploadedFile file;
 
    public UploadedFile getFile() {
        return file;
    }
 
    public void setFile(UploadedFile file) {
        this.file = file;
    }
     
    public void upload() {
        if(file != null) {
        	try {
				file.write("c:\\application_server_root\\upload_dir" + file.getFileName()); //potential path traversal
			}
			catch (Exception e) {
				e.printStackTrace();
			}
        }
    }
}
```

**Comment by melloware** [comment]
I think the tricky part with this one is how do you sanitize it without breaking a valid filename?

https://github.com/primefaces/primefaces/issues/1439
https://github.com/primefaces/primefaces/issues/506
https://github.com/primefaces/primefaces/issues/3034

**Comment by cnsgithub** [comment]
It always depends on the context (file system, JS, HTML, ...) you make use of the filename. If used in file system APIs, make sure filename is handled just as filename and not as directories, if used in JS use JS encoding, if used in HTML, use HTML encoding and so on.

My current code insight is not deep enough to judge.

And I think it is always a good idea to NOT reinvent the wheel in such security-related concerns, as there are people outside that are aware of things we might not think of in our worst dreams.

So, for example use OWASP encoders for the encoding stuff, or commons-io for the file system stuff, e.g. `FilenameUtils ` mentioned above and so on.

Another option would be to drop `UploadedFile.getFileName ` entirely from the interface, as it isn't reliable anyway (however this cannot be done with a patch release).

**Comment by melloware** [comment]
Agreed. I am just saying once again you have to be careful with what "sanitize" means this context that you don't break functionality that was actually intended in some use cases.   Or at least give the option for "unsanitized" file names if that is what the developer desires.

**Comment by cnsgithub** [comment]
What have the use cases to do with proper design and secure development?

What is the advantage of `NativeUploadedFile ` (using `Part` from Servlet 3.0 spec) over `DefaultUploadedFile ` (using `FileItem ` from commons-fileupload) - besides standard vs. non-standard API and another (well tested, de-facto standard) dependency? At the moment I cannot see any advantage.

In contrary, the switch makes things more complicated and difficult to understand. In the first step, I would consider entirely dropping `NativeUploadedFile ` in favor of `DefaultUploadedFile`. In my opinion it is a shortcoming of the Servlet 3.0 API, that access to the filename is not provided out-of-the-box, whereas the `FileItem ` API from commons-fileupload does. 

What PrimeFaces should do is following the rules from e.g. Mozilla (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition):
> filename
> Is followed by a string containing the original name of the file transmitted. The filename is always optional and must not be used blindly by the application: path information should be stripped, and conversion to the server file system rules should be done. This parameter provides mostly indicative information. 

For stripping the path information `FilenameUtils.getName ` (commons-io) as mentioned above may be used.

Then I would search for a well-tried lib to sanitize filenames. I don't know yet, but https://github.com/augustd/owasp-java-fileio sounds pretty good.

I would then refactor the interface method `UploadedFile.write(String)` in a way that makes it much more clearer where the file will be written to and strictly separate path and filename.

Just my two cents...

**Comment by melloware** [comment]
@cnsgithub Perfect just sounds like you signed up to implement the PR!

**Comment by melloware** [comment]
Although I will warn you I am not sure how PrimeTek feels using 3rd party libs that are not "optional".  If you use the OWASP code and make it a dependency it will have to be a required dependency not an optional one.  I know PF in the past has prided itself on just being a standalone JAR library with no dependencies unless you use features that need another lib like Barcode4J for the Barcode component etc.

Just my two cents.

**Comment by cnsgithub** [comment]
No, I didn't sign up automatically to address these issues since I am not aware of all use cases.

However, it would be great to get a statement from PrimeTek to further advance this. E.g. the advantage and necessity of the native implementation is not yet clear (at least to me)? And if PrimeTek is willing to accept a third-party lib like OWASP fileio?

**Comment by tandraschko** [comment]
i'm not sure if we need a additional dependency for this issue. However, if we would need to introduce the dependency for the quilljs issue, we could reuse it.

**Comment by melloware** [comment]
OK after reviewing this one some more I think I can fix it.  I will submit a PR with more unit tests.

**Comment by melloware** [comment]
@cnsgithub Looking at this more it seems the way FileNameUtils.getFileName does it is by stripping everything after either directory slash "/" or "\".

See this source code line: https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/FilenameUtils.java#L707

However if we did that it would break our already existing unit tests for valid filenames from previous tickets.

```java
@Test
    public void testSlashes() {
        // Arrange
        final String input = "form-data; name=\"XXX:XXX\"; filename=\"hello\\\\.png\"";

        // Act
        final String output = file.getContentDispositionFileName(input);

        // Assert
        Assert.assertEquals("hello\\\\.png", output);
    }
```

That would return ".png" as the file name and not "hello\\\\.png" as it does now.  We would have to know whether it was unix or windows escaping the end user wanted.

Thoughts?

**Comment by mertsincan** [comment]
Hi @cnsgithub and @melloware,

Could you please check the fix?

Thanks a lot!

**Comment by melloware** [comment]
@mertsincan 2 things.  

1. Drop this attached NativeFileUploadTest overtop of the one that was there.  You will now see a lot of my test cases failing for filenames that were considered valid by other tickets.

[NativeUploadedFileTest.zip](https://github.com/primefaces/primefaces/files/2331942/NativeUploadedFileTest.zip)

2. In your throw exception I think a better message than:

`throw new FacesException("Invalid filename");`

would be:

`throw new FacesException("Invalid filename: " + filename);`

So it multiple files they know which one caused the violation.

**Comment by mertsincan** [comment]
Thanks a lot for the feedback, @melloware ;)

**Comment by Rapster** [comment]
@mertsincan Build is failing, some tests related to your changes are not passing

**Comment by melloware** [comment]
I think we also need a test for the original issue in this ticket of "c:\\application_server_root\\upload_dir\\test.png" should return only "test.png"?   I think what @cnsgithub was saying was we should strip out directory information but that is difficult because slashes are valid in Unix but not in Windows.

**Comment by mertsincan** [comment]
@Rapster, which tests? Could you please try it after updating your branch? The NativeUploadedFile tests work fine for me. 

@melloware can we/users use File.seperator or File.separatorChar to split path?
https://docs.oracle.com/javase/7/docs/api/java/io/File.html#separatorChar

**Comment by Rapster** [comment]
@mertsincan See https://travis-ci.org/primefaces/primefaces It's a Linux environment so that might explain you're not able to reproduce it

**Comment by Rapster** [comment]
I think @cnsgithub has a point here regarding the stripping and sanitizing part https://github.com/primefaces/primefaces/issues/3269#issuecomment-362503126

I'd rather use OWASP library for such thing than making our own check. Since we're shading third librairies, I don't see the problem to use https://github.com/augustd/owasp-java-fileio

**Comment by mertsincan** [comment]
@melloware, is the "hello\\.png" filename valid in windows? https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names/31976060#31976060

**Comment by melloware** [comment]
@mertsincan It is INVALID in Windows but VALID in UNIX.  That is the trouble you have to know what operating system you are dealing with.

**Comment by mertsincan** [comment]
Thanks a lot for the update! Maybe, we can use System.getProperty("os.name") method to detect OS.
boolean isWindows = (System.getProperty("os.name").indexOf("Windows") != -1) ? true : false;
if(isWindows)
  ...
else
  Assert.assertEquals("hello\\\\.png", output);
what do you think about it?

**Comment by melloware** [comment]
Yep I think you will have to do something like that so you know which characters are valid on Windows vs anything else.

**Comment by mertsincan** [comment]
Thanks a lot ;) @melloware how do we get only the filename from a path? What do you think about it?

**Comment by melloware** [comment]
here is what Commons FileNameUtils does I think we just have to make ours smarter to only check one or the other / or \ per OS.

```java
  /**
     * Returns the index of the last directory separator character.
     * <p>
     * This method will handle a file in either Unix or Windows format.
     * The position of the last forward or backslash is returned.
     * <p>
     * The output will be the same irrespective of the machine that the code is running on.
     *
     * @param fileName  the fileName to find the last path separator in, null returns -1
     * @return the index of the last separator character, or -1 if there
     * is no such character
     */
    public static int indexOfLastSeparator(final String fileName) {
        if (fileName == null) {
            return NOT_FOUND;
        }
        final int lastUnixPos = fileName.lastIndexOf(UNIX_SEPARATOR);
        final int lastWindowsPos = fileName.lastIndexOf(WINDOWS_SEPARATOR);
        return Math.max(lastUnixPos, lastWindowsPos);
    }
```

https://raw.githubusercontent.com/apache/commons-io/master/src/main/java/org/apache/commons/io/FilenameUtils.java

Look at their getName method it takes "C:\Persona\Tools\hello.png" and returns "hello.png".

**Comment by mertsincan** [comment]
Thanks a lot for the update, @melloware ;) I made some changes in my code. What do you think about it?
```
package org.primefaces.util;

import java.io.File;
import java.util.regex.Pattern;
import javax.faces.FacesException;
import org.apache.commons.io.FilenameUtils;

public class FileUploadUtils {
    
    private static final Pattern INVALID_FILENAME_PATTERN = Pattern.compile("([\\/:*?\"<>|])");
    
    private static boolean isSystemWindows = File.separatorChar == '\\';
    
    public static String getValidFilename(String filename) {
        if (filename != null) {
            if (isSystemWindows) {
                if (!filename.contains("\\\\")) {
                    String[] parts = filename.substring(FilenameUtils.getPrefixLength(filename)).split(Pattern.quote(File.separator));
                    for (String part : parts) {
                        if (INVALID_FILENAME_PATTERN.matcher(part).find()) {
                            throw new FacesException("Invalid filename: " + filename);
                        }
                    }
                } else {
                    throw new FacesException("Invalid filename: " + filename);
                }
            }

            String name = FilenameUtils.getName(filename);
            String extension = FilenameUtils.EXTENSION_SEPARATOR_STR + FilenameUtils.getExtension(filename);

            if (!extension.isEmpty() && !name.isEmpty() && !extension.equals(name)) {
                return name;
            } else {
                throw new FacesException("Invalid filename: " + filename);
            }
        }
        
        return filename;
    }
}
``` 

Tests;
```
On Windows;
        filename = "C:\\Persona\\Tools\\hello.png";       //Valid -> hello.png  
        filename = "hello\\\\.png";                                 // InValid
        filename = "hello+.png";                                    //Valid -> hello+.png
        filename = "hello\\.png";                                   // InValid
```

**Comment by melloware** [comment]
I like it!

**Comment by mertsincan** [comment]
@tandraschko , @melloware , @cnsgithub and @Rapster What do you think about this fix? Could you please review it? I checked it on Windows. It works fine for me.

**Comment by melloware** [comment]
I added my comments.
