### ISSUE TITLE
AutoComplete: Trigger clear event when input is cleared by forceSelection=true 

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#3270]
## 1) Environment
- PrimeFaces version: 6.2.RC1
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
Fire the `clear` event when the input is emptied by the setting `forceSelection=true.

## 3) Actual behavior
The newly added `clear` event ( #2846 ) is trigger if the input is emptied using backspace, etc. But if the autoComplete is set to `forceSelection=true` the event is not triggered if no valid item was selected.

## 4) Steps to reproduce
- Setup an autoComplete with `forceSelection=true` and add an `p:ajax event="clear"` to it.
1. 
    - Type something (in this example: TEST) and select an item
    - Remove it again using the backspace key. The `clear` event is fired
2.
    - Type something (in this example: TEST) again and select an item
    - Remove some chars from the input but not all. Leave the input field. `forceSelection` will clear the input field but NO `clear` event is fired
3.
    - Type something (in this example: TEST) again and NOT select an item
    - Leave the input field. `forceSelection` will clear the input field but NO `clear` event is fired

## 5) Sample XHTML
```
<p:autoComplete value="#{bean.txt1}" completeMethod="#{bean.completeText}" forceSelection="true">
     <p:ajax event="clear" listener="#{bean.onClear}" update="msgs" />
</p:autoComplete>
```

## 6) Sample bean
```
@RequestScoped
@Named
public class Bean {
    private String txt1;

    public List<String> completeText(String qry) {
        if(qry != null && qry.startsWith("TEST")) {
            return Arrays.asList("TEST", "TEST1", "TEST2");
        }

        return Collections.emptyList();
    }

    public String getTxt1() {
        return this.txt1;
    }

    public void setTxt1(String txt1) {
        this.txt1 = txt1;
    }
}
```

**Comment by tandraschko** [comment]
@mertsincan could you check that?

**Comment by Pilpin** [comment]
Hello, 

I experienced the same issue on 6.2.
