### ISSUE TITLE
Primefaces is not using FontAwesome Icons when they are activated...

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#3271]
In Primefaces 6.1.13 and also on the 6.2-SNAPSHOT 
i can activate the use of FontAwesome by setting the following context-param:

```
    <context-param>
        <param-name>primefaces.FONT_AWESOME</param-name>
        <param-value>true</param-value>
    </context-param>
```

But when i try the following simple example it will be rendered with an image icon instead
of using the calendar symbol from the FontAwesome Library.

You can also use the Primefaces-Showcase with the calendar-input in button-style to reproduce it.

```
        <p:outputLabel for="button" value="Button:" />
        <p:calendar id="button" value="#{calendarView.date3}" showOn="button" />
```

Instead of using FontAwesome here the button's icon will be rendered as 
ui-icon-calendar which is an image.

Can you fix the renderer for the component's to use the FontAweSome Classes instead of  
using image icon classes ?

Because at the moment i can not change the size, the color, or any style of this icon's
but with using FontAwesome i can do this by set a style or styleClass ...

**Comment by tandraschko** [comment]
It's up to the theme. Premium themes are using font-awesome.
Probably we will create new community theme which will use font-awesome in the future.
