### ISSUE TITLE
SelectOneMenu: Issue with dynamic="true" and required validation.

### ISSUE THREAD

**Issue by koan00** [primefaces/primefaces#3277]
## 1) Environment
- PrimeFaces version: master (5099d890cca46db839045d1b3815a66de6902e3c)
- Does it work on the newest released PrimeFaces version? No, dynamic="true" is a new feature.
- Does it work on the newest sources in GitHub? No.
- Application server + version: Tomcat 7.0.82 / Mojarra 2.2.15
- Affected browsers: IE 11, FF 58, Chrome 63

## 2) Expected behavior
Upon selecting a value in the menu, the value remains set and 'required' validation passes.

## 3) Actual behavior
Upon selecting a value in the menu, the value gets unset and 'required' validation fails

## 4) Steps to reproduce
From top to bottom, select values for all 3 drop downs. Then submit the form. 

Slightly different behavior between the top 2 items. The first item also has a nested <p:ajax> while the second does not.  Finally, last one does not have the dynamic="true" flag set.

## 5) Sample XHTML

`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
		<f:facet name="first">
			<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		</f:facet>
	</h:head>
    <h:body>
			<p:log id="testLogger" />
		<h:form id="dummy"></h:form>
		<form>test regular form</form>
        <h1>#{testView.testString}</h1>
		<p:accordionPanel>
			<p:tab title="test2" rendered="false">
				dummy content
			</p:tab>
		<p:tab title="test">
			<h:form id="testForm">

				<p:panelGrid>
				<p:row>
					<p:column>List1:</p:column>
					<p:column>
						<p:selectOneMenu autoWidth="false" id="list1" effect="none" value="#{testView.itemValue1}" dynamic="true"
										filter="true" filterMatchMode="contains" required="true">
								<f:selectItem itemLabel="– Choose Value 1 –" itemValue="#{null}"/>
								<f:selectItem itemLabel="Item1" itemValue="1"/>
								<f:selectItem itemLabel="Item2" itemValue="2"/>
								<f:selectItem itemLabel="Item3" itemValue="3"/>
								<f:selectItem itemLabel="Item4" itemValue="4"/>
								<p:ajax event="change" update="@form" />
						</p:selectOneMenu>
						<p:message for="list1"/>
					</p:column>
				</p:row>
				<p:row>
					<p:column>List2:</p:column>
					<p:column>			
						<p:selectOneMenu autoWidth="false" id="list2" effect="none" value="#{testView.itemValue2}" dynamic="true"
										  filter="true" filterMatchMode="contains" required="true" >
								<f:selectItem itemLabel="– Choose Value 2 –" itemValue="#{null}"/>
								<f:selectItem itemLabel="Item1" itemValue="1"/>
								<f:selectItem itemLabel="Item2" itemValue="2"/>
								<f:selectItem itemLabel="Item3" itemValue="3"/>
								<f:selectItem itemLabel="Item4" itemValue="4"/>
					
						</p:selectOneMenu>
						<p:message for="list2"/>
					</p:column>
				</p:row>
				<p:row>
					<p:column>List3:</p:column>
					<p:column>	
						<p:selectOneMenu autoWidth="false" id="list3" effect="none" value="#{testView.itemValue3}"
										  filter="true" filterMatchMode="contains" required="true" >
								<f:selectItem itemLabel="– Choose Value 3 –" itemValue="#{null}"/>
								<f:selectItem itemLabel="Item1" itemValue="1"/>
								<f:selectItem itemLabel="Item2" itemValue="2"/>
								<f:selectItem itemLabel="Item3" itemValue="3"/>
								<f:selectItem itemLabel="Item4" itemValue="4"/>

						</p:selectOneMenu>
						<p:message for="list3"/>
					</p:column>
				</p:row>
				</p:panelGrid>
				<p:commandButton id="saveButton" value="Save &amp; Close" action="#{testView.doAction}" 
									process="@form" update="@form" />
									
				<p:outputPanel id="workflowButtonPnlGrdWrapper">
				  Test Panel
				</p:outputPanel>
				<p:dialog>
					Test Dialog
				</p:dialog>

			</h:form>
										
			</p:tab>
			</p:accordionPanel>

    </h:body>
</html>`

## 6) Sample bean

`package org.primefaces.test;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    private String itemValue1;
	private String itemValue2;
	private String itemValue3;
	
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }    
	
	public String getItemValue1() {
        return itemValue1;
    }

    public void setItemValue1(String testString) {
        this.itemValue1 = testString;
    } 
	
	public String getItemValue2() {
        return itemValue2;
    }

    public void setItemValue2(String testString) {
        this.itemValue2 = testString;
    } 
	
	public String getItemValue3() {
        return itemValue3;
    }

    public void setItemValue3(String testString) {
        this.itemValue3 = testString;
    } 	
	
	 public String doAction() {
        return "";
    } 	
}
`

**Comment by koan00** [comment]
Further analysis reveals the form value is never set on the client side when the option is selected. In forms.selectonmenu.js when selectItem: function(item, silent) ... is called, selectedOption.val() is undefined for items created dynamically. However selectedOption.val() does return the correct value for non-dynamically loaded items.

In debugging the ajax response to the dynamic load request, it does appear that a value is present in the response data. In function dynamicPanelLoad: function() ... the call to $this.input.replaceWith(selectTag); doesn't seem to be working as intended. Examining $this.input[0].outerHTML after the call shows the original HTML, not the replaced  HTML.

**Comment by koan00** [comment]
The following code appears to correct the issue:
`    dynamicPanelLoad: function() {
        var $this = this,
        options = {
            source: this.id,
            process: this.id,
            update: this.id,
            global: false,
            params: [{name: this.id + '_dynamicload', value: true}],
            onsuccess: function(responseXML, status, xhr) {
                PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
                    widget: $this,
                    handle: function(content) {
                        var	optionsStart = content.indexOf('<option'),
						optionsEnd = content.indexOf('</select>'),
						index = optionsEnd + 9,
                        optionsList = content.substring(optionsStart, optionsEnd);
						
                        $(this.input).html(optionsList);
						$this.options = $this.input.children('option');
                        $this.itemsWrapper.append(content.substring(index, content.length));
                    }
                });

                return true;
            },
            oncomplete: function(xhr, status, args) {
                $this.isDynamicLoaded = true;
                $this.initContents();
                $this.bindItemEvents();

            }
        };

        PrimeFaces.ajax.Request.handle(options);
    },`

**Comment by tandraschko** [comment]
Fixed - please give it a try.

**Comment by koan00** [comment]
Confirmed the fix works. Thanks!
