### ISSUE TITLE
SplitButton: add outcome support

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3288]
## 1) Environment
- PrimeFaces version: 6.2.RC2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
Clicking on defaut button should alow us to be redirected

## 3) Actual behavior
page refreshed only

## 4) Steps to reproduce
 ```xml
<p:splitButton value="#{i18n['BUTTON_CREATE_RECORD']}" 
                           outcome="navCreate"
                           rendered="#{controller.addRecordRendered}"
                           ajax="false" >
                <p:menuitem value="#{i18n['MENU_ADD_TO_CART']}"
                            action="#{controller.addToCart}"
                            ajax="false"/>
</p:splitButton>
```

## 5) Workaround
Use action attribute and implementing method returning outcome

**Comment by Rapster** [comment]
If #5010 merged I think it'll be easy to fix this one

**Comment by melloware** [comment]
Agreed!

**Comment by melloware** [comment]
@Rapster now that #5010 has been merged do you want to tackle this one?

**Comment by tandraschko** [comment]
@Rapster If you would like to see it, please do it before RC1.

**Comment by Rapster** [comment]
Let me have a look, I'm afraid I was a bit hasty on this one

**Comment by Rapster** [comment]
I thought it'd be easier, but it's not without modifying the PF API. After a deeper analysis, `SplitButton `inherits `HtmlCommandButton` just like `CommandButton`, and this component have no `outcome` attribute, it's certainly wanted that way, to use `action` instead. I think it's better to keep it that way.
