### ISSUE TITLE
selectOneMenu: itemEscape doesn't work correctly

### ISSUE THREAD

**Issue by ebehmen** [primefaces/primefaces#3289]
## 1) Environment
- PrimeFaces version: 6.2.RC1
- Application server + version: Payara Server 172
- Affected browsers: ALL

## 2) Expected behavior

![grafik](https://user-images.githubusercontent.com/13982588/35821972-0eb12562-0aab-11e8-916a-3d356d10436d.png)

## 3) Actual behavior

![grafik](https://user-images.githubusercontent.com/13982588/35821388-2b543e54-0aa9-11e8-98be-3d53af6d13c9.png)

## 4) Steps to reproduce

no special steps required. Works with Primefaces 6.1 as expected.

## 5) Sample XHTML

        <p:selectOneMenu>
            <f:selectItem itemEscaped="true" itemLabel="&lt;Select a city&gt;"/>                                        
        </p:selectOneMenu> 

## 6) Sample bean

no bean required

**Comment by melloware** [comment]
Related to this ticket? https://github.com/primefaces/primefaces/issues/2668

**Comment by tandraschko** [comment]
Don't know why it happens. A PR or analysis is welcome. The code is the same as in 6.1 in this part.

**Comment by melloware** [comment]
PR submitted.  This was a JQuery 3.0 issue introduced.
