### ISSUE TITLE
how to add button inside tabview in primefaces 

### ISSUE THREAD

**Issue by mounika544** [primefaces/primefaces#3297]
<p:tab title="#{selDate.toLongString()}">
                                    <p:tabView value="#{buildingCoverageWeekend.shifts}" var="shift" cache="false">
                                        <p:ajax event="tabChange" listener="#{buildingCoverageWeekend.onTabChange}"  />
                                        <p:tab title="#{shift.short_name}"    titleStyle="#{buildingCoverageLeftPane.tabStyle}"  disabled="#{buildingCoverageLeftPane.isTabDisabled(shift.id)}">
                                            <ui:include  src="overtime/buildingCoverageLeftPane.xhtml"/>
                                        </p:tab>
                                    </p:tabView>

**Comment by melloware** [comment]
Please use the forums for questions: https://forum.primefaces.org/viewforum.php?f=3
