### ISSUE TITLE
PickList: add keyboard support

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#3304]
## Environment
- PrimeFaces version: 6.1
- Application server + version: n/a
- Affected browsers: All

## Reproduce

1. Visit https://www.primefaces.org/showcase/ui/data/pickList.xhtml
1. Click **San Francisco**.
1. Type: `B`

## Expected behavior

Selected item changes from **San Francisco** to **Berlin**.

## Actual behavior

Nothing happens (keyboard input is ignored).

## Additional Details

This behaviour diverges from multiple selection inputs that have long since been a part of standard UI browser behaviour:

``` .html
	<html>
	<body>
	<form>
	<select multiple="multiple" name="input" id="input">
	<option>San Francisco</option>
	<option>London</option>
	<option>Paris</option>
	<option>Istanbul</option>
	<option>Berlin</option>
	<option>Barcelona</option>
	<option>Rome</option>
	</select>
	<select multiple="multiple" name="output" id="output">
	<option>Vancouver</option>
	<option>New York</option>
	</select>
	<input type="submit" name="submit" value="submit" />
	</body>
	</html>
```

In effect, the underlying issue is that the PickList is partially duplicating functionality already present in [every major web browser](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#Browser_compatibility), which can be considered a DRY violation.

While there are extensions that add keyboard behaviours, piling on extra code for behaviour that has already existed for _decades_ is confounding.

Architecturally speaking, the default behaviour should be to use the plain HTML multiple-choice options (as shown above) with CSS for styling and JavaScript to enhance the behaviour (and include shuttling ability). This would enhance accessibility, eliminate the need for an extension, avoid violating the principle of least astonishment (keyboard input ignored without extra effort), result in fewer lines of code pushed to the browser, and confer other advantages.

**Comment by tandraschko** [comment]
Sponsoring via PrimeFaces PRO or PR welcome.

**Comment by melloware** [comment]
@DaveJarvis I am not disagreeing with you and all of your points are **_ABSOLUTELY_** valid.  However, to achieve functionality that the PF picklist has no amount of CSS or JS is going to be able to override the default HTML behavior and provide all the same things the component does.  For example images    Which is why Jquery Plugin developers end up writing their own components.

What I mean by that are the things below as well Drag/Drop targeting etc...

![image](https://user-images.githubusercontent.com/4399574/36005536-2b35023c-0d06-11e8-9614-1d6ab3c98960.png)

To provide this level of flexibility sometimes custom components must be written.  And if it has shortcomings like Keyboard Support then its our job to either a) enhance the component with a PR, b) sponsor development with PF PRO, c) live with the quirks and realize how much amazing work it is doing for us, or d) don't use it at all and just use a CSS styled HTML picklist.

But once again I am NOT disagreeing with all of your valid points or trolling you.  I am just saying things are easier said than done, and trying to style or make an HTML Picklist have images inside of it or images and checkboxes is no small feat for a component that was meant for just plain text like this example.

https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_select_multiple

**Comment by ghost** [comment]
Also agreed, that the following are not possible with the basic `<select>` element:

* Images
* Drag and drop targeting
* Checkbox selections
* Animations

Such features are extensions; whereas, keyboard selection is basic behaviour. The base component can be super-simple and use the core HTML functionality when other behaviour is not desired. For example, here's a high-performance filterable shuttle prototype that can ignore diacritics while filtering:

* http://jsfiddle.net/U8Xre/

As a component, this could be:

``` .html
<p:pickList id="picklist"
    itemValue="#{theme}"
    itemLabel="#{theme.displayName}"
    filterMatchMode="contains, diacritics">
```

By default, this would render as two HTML multiselect boxes with a few JavaScript/jQuery-enabled buttons to control shuttling. For anything more complex, the extensions would load and render the shuttle as a different set of HTML elements altogether.

Since many frameworks offer this (or similar) functionality, another approach is to propose including the shuttle widget as part of the HTML standard, so that all major browsers will adopt it. This would provide native speeds to avoid [performance issues](https://github.com/istvan-ujjmeszaros/bootstrap-duallistbox/issues/21) and eliminate the need for every framework to have its own (probably buggy) implementation.

In summary, from a design perspective, all widgets should be implemented with their basic behaviour founded on core HTML components. Enhancements to that behaviour can do whatever is necessary to make it work. It would be incredible to see a formal process whereby the HTML standards are also improved to avoid reinventing the wheel time and time again:

* http://crlcu.github.io/multiselect/
* http://www.dotnetcurry.com/jquery/1066/move-items-multi-select-list-jquery
* https://xdsoft.net/jquery-plugins/multi-select/
* http://blog.jeremymartin.name/2008/02/easy-multi-select-transfer-with-jquery.html
* https://www.zkoss.org/zkdemo/listbox/dual_listbox
* http://jsfiddle.net/rniemeyer/5Ctg6/
* http://docs.jboss.org/richfaces/latest_3_3_X/en/devguide/html/rich_listShuttle.html
* http://download.oracle.com/tech/blaf/specs/shuttle.html
* https://www.stevefenton.co.uk/cmsfiles/assets/file/twosidedmultiselect.html
* and likely dozens more.

**Comment by ghost** [comment]
To touch on the idea of using basic HTML components a bit more, consider these two bugs I found within a minute of each other. The purpose isn't to log them as bugs, but to illustrate why default HTML components for doing basic behaviours are preferred to the additional complexity implemented that offers no significant UX gains (in situations where the complexity is not warranted).

# Double Space

In this issue, the input field inserts an extra space:

1. Start Google Chrome (Windows 7)
1. Visit https://www.primefaces.org/showcase/
1. Click the Search field (left-hand side).
1. Type: `transfer shuttle`

**Expected Results**
The input field contains `transfer shuttle`.

**Actual Results**
The input field contains an extra space:

```
transfer  shuttle
```

# Unresponsive Keystrokes

In this issue, the `Home` key becomes unresponsive:

1. Start Google Chrome (Windows 7)
1. Visit https://www.primefaces.org/showcase/
1. Click the Search field (left-hand side).
1. Type: `picklist`
1. Click **Data**
1. Click **PickList**
1. Click the Search field, again.
1. Type: `shuttle`
1. Press `Home` key.

**Expected Results**
The cursor jumps to the start of the input field.

**Actual Results**
The cursor remains at the end of the word `shuttle`.

**Additional Details**
This behaviour cannot be reproduced 100% of the time, and using some combination of `Ctrl+Shift+Left Arrow` seems to "unlock" the unresponsive `Home` key (the `End` key is probably affected as well).

**Comment by ghost** [comment]
For completeness, here's a message I posted to the W3C's public HTML specifications mailing list.

---

Many web application frameworks offer developers a high-level user interface component called a List Builder. Having a standard List Builder would address an evident need. To avoid confusion with HTML list elements (OL, UL) and date pickers, the term “shuttle” is a reasonable choice. As a starting point for discussion:

``` .html
<shuttle id="picklist">
  <label for="left-filter">Filter</label>
  <input type="filter" id="left-filter" for="left-shuttle" diacritics="false" case="false">
  <select id="left-shuttle" name="left-shuttle" multiple="multiple" type="source">
    <option value="1" selected="selected"><img src="icon.svg"/> One</option>
  </select>
  <button type="shuttle" arrange="left-up">
  <button type="shuttle" arrange="left-down">
  <button type="shuttle" transfer="left">
  <button type="shuttle" transfer="left-all">
  <button type="shuttle" transfer="right">
  <button type="shuttle" transfer="right-all">
  <button type="shuttle" arrange="right-up">
  <button type="shuttle" arrange="right-down">
  <select id="right-shuttle" name="right-shuttle" multiple="multiple" type="destination">
    <option value="2" type="checkbox">Two</option>
  </select>
</shuttle>
```

The browser would then be responsible for adding features, including drag and drop. The widget defines common cross-implementation behaviours, including:

- A standard shuttle component
- Consistent accessibility controls
- Checkboxes to address UX issues with selections
- Images in options
- Filter none, one, or both multi-select lists
- Ignore diacritics in filters (e.g., “acai” matches “Açaí palm”)
- Enable case-insensitive filtering
- Sorting list elements

**Comment by melloware** [comment]
Yes that would be nice! But as you know the W3C doesn't move at a very fast speed for adoption of new things and then the browsers take a while to adopt those new W3C specs.  

**So in the meantime shouldn't we just add Keyboard support to this already feature rich PickList?**   I can take a shot at adding Keyboard Support if you want?

As to your points about the "Showcase Search Field" that is NOT repeat NOT a PF component. It is a custom field written for the Showcase and yes it has bugs.  But if you go to the PF InputText here:  https://www.primefaces.org/showcase/ui/input/inputText.xhtml you will see it has no issues with the Home key or anything else you mentioned.  So let's not muddy the waters with some custom Jquery code that was written for their Showcase search vs actual PF components.

**Comment by melloware** [comment]
Showcase issue reported:  https://github.com/primefaces/showcase/issues/64

**Comment by ghost** [comment]
> So in the meantime shouldn't we just add Keyboard support to this already feature rich PickList? I can take a shot at adding Keyboard Support if you want?

Most definitely, thank you.

I suspected that the text input field wasn't part of PF -- that said, I think the main point still stands. JavaScript (AJAX) should be used to enhance browsers' default behaviour. It seems that more and more developers are simply rolling their own.

**Comment by melloware** [comment]
OK I submitted a PR if you want to code review it or pull it and check it out.

https://github.com/primefaces/primefaces/pull/3317

**Comment by ghost** [comment]
Looks good. Is it extensible enough to ignore diacritics?

**Comment by melloware** [comment]
Good question.  I guess we need to look at what Javascript sends as keycodes. For example A = 65.  And then this code in the PR converts 65 to 'a'.

```javascript
var keyChar = String.fromCharCode(key).toLowerCase();
```
So I guess it depends on what Javascript treats the keycode as for "a with an accent above it" or regular "a".

**Comment by ghost** [comment]
Another approach is to match against the select item names, ignoring diacritics:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize
* https://stackoverflow.com/a/18391901/59087

Imagine school names listed with French accents, but selection using keyboards that do not easily allow for typing accented characters. The expected behaviour would be that `i` matches `Îles`--ignoring case--such that the user sees Îles, but the code has a secondary list. This could use a lot of memory, so an algorithm that removes diacritics on-the-fly would be useful here. Something like:

1. Create an index map for each of the first letters, with diacritics removed.
1. When the user presses a key, jump to the index.
1. Create an index map for the second letter of each word that starts with the first letter typed.
1. When the user presses a key, jump to the index.
1. Repeat.

Thus, given:

* Haliç
* Îles
* Indus
* Iona

A (1-based) map is set to:

* H: 1
* I: 2

Upon pressing `i` (or `I`), the map is set to:

* L: 1
* N: 2
* O: 3

**Comment by melloware** [comment]
I really like the idea of the using one of the fuctions above to decode the diacritic.  I will review the ones posted.

As for the 2nd part about making maps of characters I think you are referring to as the user types characters keep narrowing what is selected.  But that functionality already exists with the "filter" functionality built into the picklist.  My idea for keyboard support was purely a single letter click jumps you to the first option that has that letter.

See Advanced Example in the showcase where Filtering is already available: https://www.primefaces.org/showcase/ui/data/pickList.xhtml

**Comment by ghost** [comment]
The filtering looks great! Having the showcase with accented characters for testing would be convenient. Also, there's some unexpected behaviour with the filter (#3337).

**Comment by ghost** [comment]
> My idea for keyboard support was purely a single letter click jumps you to the first option that has that letter.

The browser's native select multiple widget behaves a bit differently. For example:

``` .html
<select multiple="multiple">
  <option value="1">Aardvark</option>
  <option value="2">Aardwolf</option>
  <option value="3">Aasvogel</option>
  <option value="4">Abalone</option>
  <option value="5">Addax</option>
</select>
````

The user can type `aardw` to jump to `Aardwolf` (case insensitive by default) or `aas` to jump to `Aasvogel`.

**Comment by melloware** [comment]
Yep I knew that however that would require storing state of the last key pressed.  The browser does that natively because it controls the browser behavior of pure html components since the browser owns them and renders them.  

I don't know if any pattern has been established in PF Javscript for storing variables in the component.  There might be a precedent for doing so but I am not familiar with it.  @tandraschko have you ever stored something like last key pressed in the PF widget JS or can point to a pattern?

**Comment by ghost** [comment]
> Yep I knew that however that would require storing state of the last key pressed. 

Or store the keystrokes as a string, which is similar, but the implementation could be quite different. Perhaps:

1. Wait for user input.
1. User presses an actionable key (i.e., not a modifier).
1. If the key is not a letter, clear the current string buffer.
1. If the key is a navigation key (`Up`, `Down`, `Home`, `End`, `Page Up`, etc.), perform the action and go to step 1.
1. If the key is `Esc`, go to step 1.
1. If the key is not a letter, go to step 1.
1. Append the key to the current string buffer, so long as the buffer length is less than the longest item.
1. Jump to the first entry that matches the buffer (using a longest substring comparison).
1. If no match, leave the selection at the current item.
1. Go to step 1.

Note that "letter" could also be a [logogram](https://en.wikipedia.org/wiki/Logogram).

**Comment by melloware** [comment]
@DaveJarvis I assume if the Picklist loses focus we would also want to clear out the stored keystrokes?  

My thought was all the scenarios like if the user tabbed to a new browser tab or if there were 5 picklists on the screen as soon as you leave one it clears the buffer.

**Comment by ghost** [comment]
> if the Picklist loses focus we would also want to clear out the stored keystrokes?

Yes, I believe that's the same behaviour as a multiple select list.
