### ISSUE TITLE
selectOneMenu: ajax does not work with RequestScoped bean

### ISSUE THREAD

**Issue by rkleijngeld** [primefaces/primefaces#3305]
1) Environment
- PrimeFaces version: PrimeFaces 6.2.RC2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source ->  https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Glashfish 4.1
- Affected browsers: All

## 2) Expected behavior
Ajax listener on bean to be executed

## 3) Actual behavior
Ajax listener not executed with bean of RequestScoped. I.e. a new bean is created.

## 4) Steps to reproduce
Load samples and change bean scope from RequestScoped to SessionScoped 

## 5) Sample XHTML

    <f:view contentType="text/html">
        <h:body>
            <div class="ui-g">
                <h:form id="form1">
                <table>
                    <tr><td><p:inputText value="#{test_bean.postcode}">
                        <p:ajax event="change" listener="#{test_bean.postcodeStateChangeListener}" update="suburbs state"/>
                        </p:inputText>
                        </td>
                    </tr>
                    <tr><td>
                    <p:selectOneMenu id="suburbs" value="#{test_bean.selected_suburb}" >
                        <f:selectItems value="#{test_bean.suburbs}" />
                        <p:ajax event="change" listener="#{test_bean.stateChangeListener}" update="state"/>
                    </p:selectOneMenu>
                    </td></tr>
                    <tr><td>
                <p:inputText id="state" value="#{test_bean.state}"/>
                </td></tr>
                <tr><td><p:commandButton value="Submit"  /></td></tr>
                </table>
                    
                </h:form>
            </div>
        </h:body>
    </f:view>
</html>

## 6) Sample bean
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsftest3;

import java.io.Serializable;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;
import org.primefaces.component.selectonemenu.SelectOneMenu;

/**
 *
 * @author ray
 */
@ManagedBean(eager=true)
@RequestScoped
public class test_bean implements Serializable{

    /**
     * Creates a new instance of postcode_bean
     */
    static final long serialVersionUID = 5L;
    private String postcode;
    private String suburb;
    private String state;
    private String selected_suburb;
    private ArrayList<SelectItem> suburbs;
    
    public String getPostcode() {
        return postcode;
    }
    
    public ArrayList<SelectItem> getSuburbs() {
        return suburbs;
    }
    
    public void stateChangeListener(AjaxBehaviorEvent e)
    {
        System.out.println("State Listener executed");
        SelectOneMenu x = (SelectOneMenu)e.getSource();
        String[] s = ((String)x.getValue()).split(" - ");
        state = s[1];
    }
    
    public void postcodeStateChangeListener(ValueChangeEvent e)
    {
        setPostcode((String)e.getNewValue());
    }
    
    public void postcodeStateChangeListener(javax.faces.event.AjaxBehaviorEvent e)
    {
         System.out.println("postcode Change Listener executed");
    }
    

    public boolean suburbCount()
    {
        return (suburbs.size()!=1);
    }

    public void setPostcode(String _postcode) {
        this.postcode = _postcode;
        try {
            if (suburbs==null)
                suburbs = new ArrayList<SelectItem>();
            suburbs.clear();
            state = "";
            suburbs.add(new SelectItem("Suburb 1 - State 1","Suburb 1"));
            suburbs.add(new SelectItem("Suburb 2 - State 2","Suburb 2"));
            suburbs.add(new SelectItem("Suburb 3 - State 3","Suburb 3"));
            suburbs.add(new SelectItem("Suburb 4 - State 4","Suburb 4"));
            suburbs.add(new SelectItem("Suburb 5 - State 5","Suburb 5"));

            selected_suburb = suburbs.get(0).getLabel();

        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    
    public test_bean() {
        System.out.println("Test Bean constructor");
    }

    public String getSuburb() {
        return suburb;
    }

    public void setSuburb(String suburb) {
        this.suburb = suburb;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getSelected_suburb() {
        return selected_suburb;
    }

    public void setSelected_suburb(String selected_suburb) {
        this.selected_suburb = selected_suburb;
    }
    
    
}

**Comment by melloware** [comment]
Your XHTML above is messed up its missing the actual selectOne.

Why not just create a small re-usable example? Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.

Then I can run "mvn jetty:run" on your sample zip so we can see your reproduced issue easily.

**Comment by rkleijngeld** [comment]
Sorry Melloware but if you copy the the entire xhtml it is interpreting the code instead of just displaying it.

**Comment by tandraschko** [comment]
the sample doesn't even compile.

**Comment by tandraschko** [comment]
You just hit the security mechanism of JSF.
On the second request, when the SelectOneMenu is submitted, the suburbs list is empty and therefore the submitted value is "catched as not available in the model" -> so the change is invalid.
This doesn't happen of course when the scope is bigger as request, as the suburbs  list isn't empty on the second request.
Feel free to create a forum topic, maybe someone will help with some design patterns for this. but probably viewScope is the right scope here.
