### ISSUE TITLE
SelectCheckboxMenu ajax not working with itemValue as custom object

### ISSUE THREAD

**Issue by ShivaniSK** [primefaces/primefaces#3306]
I am trying to perform ajax on selecting any element in selectCheckBoxMenu primefaces.
But ajax event fires only if itemValue is equal to String. If i am passing object then not event is fired. Please have a look.
    
```
    package com.gsep.utility.bean;
    
    import javax.faces.bean.ManagedBean;
    import javax.faces.bean.ViewScoped;
 
    
    @ManagedBean
    @ViewScoped
    public class Tool {
    
    	private int toolId;
    	private String toolName;
    	public int getToolId() {
    		return toolId;
    	}
    	public void setToolId(int toolId) {
    		this.toolId = toolId;
    	}
    	public String getToolName() {
    		return toolName;
    	}
    	public void setToolName(String toolName) {
    		this.toolName = toolName;
    	}
    	
    	
    }
```
    
    
Above is my bean class which i am iterating to display values in selectCheckboxMenu.
Below is jsf code
    
       ```
 ```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:head>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />	
	
        </h:head>	
	<h:form>
		<p:selectCheckboxMenu id="multiple" value="#{projectBean.selectedToolList}" label="Tools" multiple="true"
                              filter="true" filterMatchMode="startsWith" panelStyle="width:250px" >
            						<f:selectItems value="#{projectBean.toolList}" var="toolObject" itemLabel="#{toolObject.toolName}" itemValue="#{toolObject}" />
            						<p:ajax listener="#{projectBean.test()}" />
       	</p:selectCheckboxMenu>
	</h:form>
</html>    
```
```
    
Here if i am changing itemValue attribute to toolObject.toolName then ajax call is happening but i want the selectedToolList as a Tool collection of objects instead of toolName collection of Strings.

@ManagedBean(name = "projectBean")
@ViewScoped
public class ProjectBeanCompUI {
	
	private List<Tool> toolList;
	private List<Tool> selectedToolList;

	public List<Tool> getToolList() {
		toolList = getTools();
		return toolList;
	}
	public void setToolList(List<Tool> toolList) {
		this.toolList = toolList;
	}	
	public List<Tool> getSelectedToolList() {
		return selectedToolList;
	}
	public void setSelectedToolList(List<Tool> selectedToolList) {
		this.selectedToolList = selectedToolList;

		public List<Tool> getTools()
	{
		List<Tool> toolList = new ArrayList<>();
		Tool tool = new Tool();
		tool.setToolId(1);
		tool.setToolName("Eclipse");
		Tool tool1 = new Tool();
		tool1.setToolId(2);
		tool1.setToolName("Jira");
		toolList.add(tool);
		toolList.add(tool1);
		return toolList;
	}

        public void test()
       {
                 System.out.println("hello");
        }

}

**Comment by tandraschko** [comment]
There is no completely runnable example - projectBean missing, we don't have JPA...

**Comment by ShivaniSK** [comment]
added projectBean

**Comment by ShivaniSK** [comment]
added projectBean. Please assist.

**Comment by tandraschko** [comment]
I can assist if you don't ignore our issue template.
It also contains:
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!

**Comment by ShivaniSK** [comment]
have updated the example. It is runnable now. Please check.

**Comment by ShivaniSK** [comment]
the itemValue here is toolObejct. Ajax call is not happening. Only if we change it to toolObject.toolName or toolObject.toolId then ajax call happens.

**Comment by ShivaniSK** [comment]
have added a runnable example. Please assist.

**Comment by melloware** [comment]
From looking at this example do you have a @FacesConverter that converts your Tool Object from a string to Object?   To me is seems like you are missing the Converter and that is why switching it to tool.name works.

**Comment by ShivaniSK** [comment]
Have tried adding converter also. It is still not working. Please check issue 3309. It has a runnable example with converter. But no ajax call happening at server side.

**Comment by melloware** [comment]
So I see you got it resolved on the other issue.  Is this resolved as well or do you still think it is an issue?
