### ISSUE TITLE
SelectCheckBoxMenu: ajax call not happening with itemValue as custom object.

### ISSUE THREAD

**Issue by ShivaniSK** [primefaces/primefaces#3309]
## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
Once u select any item from SelectCheckBoxMenu then "test()" should be called on server side and the selectedItems should be printed.
...

## 3) Actual behavior
Ajax call does not happen. 
..

## 4) Steps to reproduce
Select any item from SelectCheckBoxMenu then it "test()" should be called on server side and the selectedItems should be printed.
.. 

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:head>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />	
	
</h:head>	
	<h:form>
		<p:selectCheckboxMenu id="multiple" value="#{projectBean.selectedToolList}" label="Tools" multiple="true" converter="toolDetailsConverter" 
                              filter="true" filterMatchMode="startsWith" panelStyle="width:250px" >
            						<f:selectItems value="#{projectBean.toolList}" var="toolObject" itemLabel="#{toolObject.toolName}" itemValue="#{toolObject}" />
            						<p:ajax listener="#{projectBean.test(projectBean)}" />
       	</p:selectCheckboxMenu>
       	<h:outputText id="selectedItemText" value=" #{projectBean.selectedToolList}"/>
	</h:form>
</html>
```

## 6) Sample bean

 import javax.faces.bean.ManagedBean;
    import javax.faces.bean.ViewScoped;
 
    
    @ManagedBean
    @ViewScoped
    public class Tool {
    
    	private int toolId;
    	private String toolName;
    	public int getToolId() {
    		return toolId;
    	}
    	public void setToolId(int toolId) {
    		this.toolId = toolId;
    	}
    	public String getToolName() {
    		return toolName;
    	}
    	public void setToolName(String toolName) {
    		this.toolName = toolName;
    	}
    	
    	
    }

      @ManagedBean(name = "projectBean")
      @ViewScoped
       public class ProjectBeanCompUI {	
	private List<Tool> toolList;
	private List<Tool> selectedToolList;

	public List<Tool> getToolList() {
		toolList = getTools();
		return toolList;
	}
	public void setToolList(List<Tool> toolList) {
		this.toolList = toolList;
	}	
	public List<Tool> getSelectedToolList() {
		return selectedToolList;
	}
	public void setSelectedToolList(List<Tool> selectedToolList) {
		this.selectedToolList = selectedToolList;

		public List<Tool> getTools()
	{
		List<Tool> toolList = new ArrayList<>();
		Tool tool = new Tool();
		tool.setToolId(1);
		tool.setToolName("Eclipse");
		Tool tool1 = new Tool();
		tool1.setToolId(2);
		tool1.setToolName("Jira");
		toolList.add(tool);
		toolList.add(tool1);
		return toolList;
	}

        public void test()
       {
              
		List<Tool> toolList1 = pro.getSelectedToolList();
		for(Tool tool: pro.getSelectedToolList())
		{
			System.out.println(tool.getToolId());
		}
		System.out.println("hello");
        }

}

```
import java.util.List;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.ConverterException;
import javax.faces.convert.FacesConverter;
import com.gsep.utility.compui.ProjectBeanCompUI;

@FacesConverter("toolDetailsConverter")
public class ToolDetailsConverter implements Converter {

	@Override
	public Object getAsObject(FacesContext arg0, UIComponent arg1, String value) {
		if(value != null && value.trim().length() > 0) {
            try {
            	  List<Tool> toolList = new ProjectBeanCompUI().getTools();
                 
            	 for(Tool tool: toolList)
            	 {
            		 if(tool.getToolName().equals(value))
            		 {
            			 return tool;
            		 }
            	 }
                  	
                return null;
                
            } catch(NumberFormatException e) {
                throw new ConverterException();
            }
        }
        else {
            return null;
        }
	}

	@Override
	public String getAsString(FacesContext arg0, UIComponent arg1, Object object) {
		 return (String)object;
	}

}

```

..

**Comment by tandraschko** [comment]
itemValue must be a primitive, string or enum as it's rendered to the client. Otherwise you can use a converter like melloware mentioned in your other issue.

**Comment by ShivaniSK** [comment]
tired by adding converter also. Please check above edited code with converter. It is still not working.
