### ISSUE TITLE
DataTable: row is selected when clicking on inputSwitch inside a column

### ISSUE THREAD

**Issue by Kameecoding** [primefaces/primefaces#3310]
## 1) Environment
- PrimeFaces version: 6.1.0
- Does it work on the newest released PrimeFaces version? No Version? 6.1.0
- Does it work on the newest sources in GitHub? No
- Application server + version: Application Server independent
- Affected browsers: browser independent

p:inputSwitch inside a p:dataTable with singleSelection mode

## 2) Expected behavior
Clicking any part of the switch should not changethe selection in the table only the switch itself.

## 3) Actual behavior
Clicking the label on the switch changes selection in the table, while clicking the handle part doesn't.
Demo gif here: https://i.imgur.com/MRbxpEr.gifv
## 4) Steps to reproduce

1. Select row in the table
2. Click on the label part of the input switch in another row

## 6) Sample bean
Sample here: https://github.com/Kameecoding/primefaces-test/commit/c156d9aed29780ccd52da2833535b04cbfa759cd

## 7) Cause
In `\src\main\resources\META-INF\resources\primefaces\datatable\datatable.js`
```
onRowClick: function(event, rowElement, silent) {
    //Check if rowclick triggered this event not a clickable element in row content
    if($(event.target).is(this.rowSelectorForRowClick)) {
```
evaluates to true when clicking the label, because the event target is the span
and the selector: `"td:not(.ui-column-unselectable),span:not(.ui-c)"` does include it.

**Comment by Kameecoding** [comment]
@tandraschko is there a way to get this fix into 6.2.0?

**Comment by tandraschko** [comment]
Maybe, actually it's already to late ;)

**Comment by kukel** [comment]
Same happens for commandButtons iirc...

**Comment by tandraschko** [comment]
So we probably need a better/more global fix. We should target that with 6.3. So please investigate a little bit also check if components have the same problems.

**Comment by kukel** [comment]
Very recent: https://forum.primefaces.org/viewtopic.php?f=3&t=54087 and from loooong ago: https://stackoverflow.com/questions/19246362/jsf-disable-button-when-table-row-is-selected-and-row-selection-listener-is-call

**Comment by Kameecoding** [comment]
well the Selector based on which the selection is triggered is only checking for a span with class `ui-c`

both using div and tagging these affected spans with `ui-c` class fixes this issue

A more general fix could be a check to see if the element is contained within a component element.

**Comment by Kameecoding** [comment]
# Proposed solution:

1. Do not activate rowSelect if click event target has `.ui-widget` class
2. Do not activate rowSelect if click event target element is a child element of an `ui-widget` class

For possible solution see: https://github.com/Kameecoding/primefaces/commit/16528c44259d1786eca7148e8f739562d069368e

**Comment by Kameecoding** [comment]
on a slightly related note, `<img>` and `<pre>` elements do not trigger row selection.

**Comment by tademeit** [comment]
Sorry, I'm late but I have the same issue on Primefaces 6.2!
What I can say is that the problem is caused by an inner span element within a commandLink/commandButton. I've tried it with a div-Element:

<p:commandLink action="...">
<div class=file-pdf-o">PDF</div>
</p:commandLink>

And then the rowselection is not fired. Any suggestions here for a official fix?

**Comment by melloware** [comment]
I just tested this with PrimeFaces 10 and its no longer happening.  If someone has a use case that it does still happen we can re-open the ticket
