### ISSUE TITLE
PrimeFaces-6.2.RC1 - Mobile showcase CSS lost

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#3312]
Current PrimeFaces mobile showcase using PrimeFaces-6.2.RC1 has Javascript and CSS issues. 
It can be seen on accordion and overlaypanel does not work at all.

https://i.imgur.com/72bZ74C.jpg

**Comment by melloware** [comment]
@djmj can you close this ticket and open one on the Showcase Issues page found here:  https://github.com/primefaces/showcase/issues
