### ISSUE TITLE
TAB navigation in autocomplete inside a datatable

### ISSUE THREAD

**Issue by denizque** [primefaces/primefaces#3314]
I have the newest version of primefaces elite.
I put an editable p:dataTable with various columns in it.
When I press the tab key to switch from one column to the other it switches as long as it not an autocomplete component.
The column which has p:inputText or p:selectOneMenu switches fine.
But if I put an autocomplete in that column and I press tab key nothing happens.
Is this a bug? Or what should I do to make it navigating through columns when it has autocomplete in it?

**Comment by melloware** [comment]
Related to this #3087 ?  Looks like something was tweaked in PF 6.1.11.

https://github.com/primefaces/primefaces/issues/3087

**Comment by tandraschko** [comment]
@mertsincan could you check that?

**Comment by huseyinturkmenoglu** [comment]
Hi, 

I don't see any problem. 

Could you share your version of primefaces ? 
And 
Please, you could send your sample code or  create  mvn projet from  : https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment]
Fixed with PR: https://github.com/primefaces/primefaces/pull/4858

If you set `autoSelection="false"` on AutoComplete the TAB key will work like normal and not select the item.
