### ISSUE TITLE
Spinner: does not work with 0, negatives or blank values

### ISSUE THREAD

**Issue by mafaul** [primefaces/primefaces#3320]
## 1) Environment
- PrimeFaces version: 6.2.RC2
- Application server + version: Payara 4.1.173
- Affected browsers: Google Chrome

## 2) Expected behavior
![image](https://user-images.githubusercontent.com/12007706/36087701-6826c576-0fdc-11e8-9c2c-58a1e76d5dbf.png)

## 3) Actual behavior
![image](https://user-images.githubusercontent.com/12007706/36087714-75afffaa-0fdc-11e8-9f88-d48aaa084c24.png)

![image](https://user-images.githubusercontent.com/12007706/36087723-81575844-0fdc-11e8-86f9-c92ab263f106.png)

## 4) Steps to reproduce
Change spinner value to 0, a negative number or try submitting it without a value.

## 5) Sample XHTML
                <h:form>
                    <p:spinner value="#{projectBean.asdf}" size="37" >
                        <p:ajax process="@this" update=":growl" /> 
                    </p:spinner>
                </h:form>

## 6) Sample bean
    private Integer asdf;

    public Integer getAsdf() {
        return asdf;
    }

    public void setAsdf(Integer asdf) {
        this.asdf = asdf;       
        JsfUtil.addSuccessMessage("Done", "Code changed to: " + asdf);
    }

**Comment by mafaul** [comment]
Adding a min="-5" attribute to the spinner solves the issue. Without the min attribute, the lowest you can go is 1. This does not work for blank values though, still get the error message.

**Comment by tandraschko** [comment]
Did it work with RC1 before?

**Comment by tandraschko** [comment]
@cnsgithub could you check that, too? AFAIR we applied a security thing here.

**Comment by cnsgithub** [comment]
@tandraschko I'm able to reproduce this issue and yes, it is related to the security fix. I didn't know that `java.lang.Double.MIN_VALUE` as denoted in `spinner.xml ` as default value for the `min` attribute is positive... I'll try to fix this.

**Comment by cnsgithub** [comment]
Pull request: https://github.com/primefaces/primefaces/pull/3322
