### ISSUE TITLE
DataTable: Allow to store TableState for multiViewState in another scopes

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3324]
## 1) Environment
- PrimeFaces version: 6.2 RC2

## 2) Expected behavior
I would like to have a possibility to use another scope than session scope for storing TableStates.  Would it be possible to allow to define own inplementation of let's say "storage provider" with methods?

org.primefaces.PrimeFaces.**clearTableStates()**
org.primefaces.PrimeFaces.**clearTableState(String key)**
org.primefaces.component.datatable.DataTable.**getTableState(boolean create)**

Using session scope, consumer has to handle clearing of the map in many cases. In our app we use other scopes like Spring's Conversation or Flow scope which we could use to store data for this functionality and they would be cleared automatically when not needed.
Another issue is multi-window usage, where the same table shares it's state with another browser window.

**Comment by tandraschko** [comment]
+1
I would also use ViewAccessScoped in my personal apps

**Comment by kapitanrum** [comment]
If **org.primefaces.component.datatable.TableState** object will be exposed to **p:datatable** arguments, then scope may be driven by programator.

Theoretical example use in .xhtml:
```
<p:datatable tableState="#{myModelBean.myTableState}" ... />
```

Example Spring model class in Spring web flow scope (may be used in CDI view scope or any other scope):
```
package com.example.models;

import org.primefaces.component.datatable.TableState
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;

@Component 
@Scope(value = "flow", proxyMode = ScopedProxyMode.TARGET_CLASS) 
public class MyModelBean implements Serializable {

  private TableState myTableSate;

  public TableState getMyTableSate() {
    return myTableSate;
  }

  public void setMyTableSate(TableState myTableSate) {
    this.myTableSate = myTableSate;
  }

  ...
  ...
  ...

}
```

**Comment by christophs78** [comment]
I´m interessted in this too. 
My personal target would be to optionally support multi-window usage. (for JSF >= 2.2)
```
FacesContext facesContext = Faces.getContext();
ExternalContext externalContext = facesContext.getExternalContext();

ClientWindow clientWindow = externalContext.getClientWindow();
clientWindow.getId();
```

Are there some thoughts on how to implement this? (Maybe @Rapster )

IMO we should make this configurable on an per application-level. (Not on an per-component-instance-level.)

**Comment by tandraschko** [comment]
application level? it's saved in the session, right?

in general +1 to add ClientWindow support, with fallback to session
ClientWindow is a great a idea but the default impl is almost useless.

**Comment by christophs78** [comment]
> application level? it's saved in the session, right?

Application level means to have an (application-level) config-switch whether to store MultiViewState per session or per ClientWindow-ID.

>ClientWindow is a great a idea but the default impl is almost useless.

Do you have some details?

In our inhouse-framework (based on Spring, JSF, ...) we have our own Spring-tabscope (which extends `org.springframework.web.context.request.AbstractRequestAttributesScope`). This implementetion uses `clientWindow.getId()` as an identifier and work´s fine for us.
The application needs to ensure not to loose `jfwid`. (There are some situations where you need to care about this. Most situations just work.)

**Comment by tandraschko** [comment]
so you use the default "url" ClientWindow?
it doesn't even validate if you open a url with another jfwid in tab, which >actually< has a jfwid assigned.

**Comment by christophs78** [comment]
yep. this is one of the limitations.
how do you solve this in a better way?

**Comment by tandraschko** [comment]
deltaspike is the way if you use CDI :P
i general it would be great if the JSF impl could provide a 100% solution

MyFaces 2.3-next introduces an "url-redirect" mode, it's makes it a bit better to not loose the jfwid

but still not 100%

**Comment by christophs78** [comment]
Which way should we implement per-window-MultiViewState in PrimeFaces?

1. Use jfwid via clientWindow.getId() "hardcoded" when per-window-MultiViewState is enabled OR
2. provide some kind of interface for your custom scope (something we need to design in a way which works with CDI and Spring)
3. do the interface-thing but delivery a default-implementation with PrimeFaces which is based on jfwid OR
4. ???

(Deltaspike multi-window-handling: https://deltaspike.apache.org/documentation/jsf.html#Multi-WindowHandling)

**Comment by tandraschko** [comment]
i think 1) is enough if we don't want to support flows

**Comment by zionskind** [comment]
> > application level? it's saved in the session, right?
> 
> Application level means to have an (application-level) config-switch whether to store MultiViewState per session or per ClientWindow-ID.
> 
> > ClientWindow is a great a idea but the default impl is almost useless.
> 
> Do you have some details?
> 
> In our inhouse-framework (based on Spring, JSF, ...) we have our own Spring-tabscope (which extends `org.springframework.web.context.request.AbstractRequestAttributesScope`). This implementetion uses `clientWindow.getId()` as an identifier and work´s fine for us. The application needs to ensure not to loose `jfwid`. (There are some situations where you need to care about this. Most situations just work.)



> > application level? it's saved in the session, right?
> 
> Application level means to have an (application-level) config-switch whether to store MultiViewState per session or per ClientWindow-ID.
> 
> > ClientWindow is a great a idea but the default impl is almost useless.
> 
> Do you have some details?
> 
> In our inhouse-framework (based on Spring, JSF, ...) we have our own Spring-tabscope (which extends `org.springframework.web.context.request.AbstractRequestAttributesScope`). This implementetion uses `clientWindow.getId()` as an identifier and work´s fine for us. The application needs to ensure not to loose `jfwid`. (There are some situations where you need to care about this. Most situations just work.)

Is there a sample implementation for the "in-house tab scope" solution?
I am converting our legacy application to Spring boot with Primefaces via Joinfaces and looking for a replacement for the "Deltaspike @WindowScoped" implementation.
The new "@ClientWindowScoped" was not fit for purpose for my Spring Boot components.

**Comment by tandraschko** [comment]
our clientWindow storage also works without a @ClientWindowScoped bean; you just need to activate JSF clientwindow handling.

**Comment by zionskind** [comment]
Thank you for the quick reply. I probably expressed myself in a misleading way.

This is more likely not a Primefaces problem at all either, but I came across the post and the custom "Tab-Scope" implementation seemed like a solution to my problem.

I need a new @Scope implementation for my Spring Boot components that replaces the old Deltaspike "@WindowScoped". 

old (JBoss Legacy): `@Named
@WindowScoped
public class SomeController implements Serializable`

maybe new (but not working): `@Component
@ClientWindowScoped
public class SomeController implements Serializable`

I need to keep the state of my views (not just Primefaces components) per tab (multi-view handling). Something between @SessionScoped and @ViewScoped.
I've been looking for a solution for a while and you guys had mentioned something similar before (Deltaspike multi-window-handling: https://deltaspike.apache.org/documentation/jsf.html#Multi-WindowHandling)

Sorry if I "misuse" the issue.

**Comment by tandraschko** [comment]
Yeah, please use our GitHub discussions
