### ISSUE TITLE
Calendar: add clean/clear button to clean the date 

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3325]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: All
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior

Like Today button there should be one clean button so that user can clean the date.

## 3) Actual behavior
No equivalent button found

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by Treppenhouse** [comment]
+1

**Comment by melloware** [comment]
This is available in the new PF DatePicker see this example and click on the "Button Bar" eample in the showcase: https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml
