### ISSUE TITLE
selectOneMenu: &nbsp; rendered if label empty or blank

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#3326]
## 1) Environment
- PrimeFaces version:
6.2.RC2
- Does it work on the newest released PrimeFaces version? Version?
Yes, works on 6.1.9.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
Don't know
- Application server + version:
Tomcat 7.0.82
- Affected browsers:
All

## 2) Expected behavior
When rendering an empty label on a selectOneMenu, I expect to see "nothing" as a label.

## 3) Actual behavior
Instead I see `&nbsp;` rendered.

## 4) Steps to reproduce
Put an editable SelectOneMenu on the page with one empty item (= empty/blank label), and one non-empty item.

## 5) Sample XHTML
```
<p:selectOneMenu ..>
<f:selectItems value="#{sampleBean.items}" />
</p:selectOneMenu>
```

## 6) Sample bean
```
...
items.add(new SelectItem(null, ""));
items.add(new SelectItem(someValue, "some label"));
..
```

It seems that it is a regression bug: https://code.google.com/archive/p/primefaces/issues/5624.
Looks like there is javascript in place that should convert `&nbsp;` to "", but somehow it doesn't work. I found this JavaScript for PrimeFaces.widget.SelectOneMenu:
```
...
if (c === "&nbsp;") {
  this.label.val("")
}
...
```

**Comment by tandraschko** [comment]
@melloware we fixed something similar? Could you check?

**Comment by melloware** [comment]
Let me investigate.  It might be related to this: https://github.com/primefaces/primefaces/issues/2366

**Comment by melloware** [comment]
Looks like this was a JQuery 3.0 change as label.text(' ') used to work now it needs to be label.html(' ');

**Comment by tandraschko** [comment]
Did you retest that the other case also still works?

**Comment by melloware** [comment]
Yes it looks like all the test cases from before and this new test case now render properly.

<f:selectItem itemLabel="&lt;Select One&gt;" itemValue="" escape="true"/>
new SelectItem(null, ""), 
new SelectItem("", "")

all tested and working.
