### ISSUE TITLE
PickList: Advanced filter properties

### ISSUE THREAD

**Issue by NEOMNI** [primefaces/primefaces#3329]
## 1) Environment
- PrimeFaces version: 6.1.8
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: n/a
- Affected browsers: All

## 2) Expected behavior
Extend PickList filter properties to support 'filterEvent' and 'filterDelay' like DataTable or TreeTable

## 3) Actual behavior
Only 'filterMatchMode' and 'filterFunction' is supported

## 5) Sample XHTML
<p:pickList showSourceFilter="true" 
  showTargetFilter="true" 
  filterMatchMode="contains"
  filterEvent="enter"
  filterDelay="1000">
</p:pickList>

**Comment by tandraschko** [comment]
PR or sponsoring via PrimeFaces PRO welcome ;)
