### ISSUE TITLE
Bug: Calendar won't accept user input when UTC is selected and the date is different from local zone

### ISSUE THREAD

**Issue by guillep2k** [primefaces/primefaces#3331]
## Expected behavior

Calendar set to:

```
	[dateFormat]="dd-mm-yyyy"
	[showTime]="false"
	[utc]="true"
```

When the user enters a date with the keyboard in the input control (e.g. 03-01-2018) and the browser is in a time zone west of GMT but the control is set to UTC, the date should be accepted.

## Actual behavior

The library rejects the date at Calendar.prototype.parseDate() here:

       if (this.utc)
            date = new Date(Date.UTC(year, month - 1, day));
        else
            date = this.daylightSavingAdjust(new Date(year, month - 1, day));
        if (date.getFullYear() !== year || date.getMonth() + 1 !== month || date.getDate() !== day) {
            throw "Invalid date"; // E.g. 31/02/00
        }

The reason is that the date is different. i.e., 2018-01-03T00:00:00Z in local time is 2018-01-02T21:00:00-03:00, so the comparison fails.

## Steps to reproduce

Set up a Calendar with a browser set to a western time zone (e.g. GMT-3, ART, Argentina Standard Time) with the seettings show above and attempt to enter a date manually (without using the picker).

**Comment by melloware** [comment]
Wrong issues list you want the PrimeNG issues list not the Primefaces issues

**Comment by guillep2k** [comment]
Sorry, I got confused.
