### ISSUE TITLE
PickList: Apply filter after moving elements

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#3337]
**Replicate**
1. Visit https://www.primefaces.org/showcase/ui/data/pickList.xhtml
1. Scroll down to the filter example.
1. Shuttle all items in **Available** filter to **Starting** filter.
1. Set **Available** filter to: `B`
1. Shuttle all items in **Starting** filter to **Available** filter.

**Expected Results**
Only **Black-Tie** appears in the **Available** list.

**Actual Results**
The filter is ignored: all items appear in the **Available** list.

**Additional Information**
The filter is not being applied in all situations, leading to:
![broken-filter](https://user-images.githubusercontent.com/2131950/36220309-f45a778e-116e-11e8-80cc-3e33e498a57b.png)

**Comment by tandraschko** [comment]
PR welcome

**Comment by cnsgithub** [comment]
I first thought fixing this would be as easy as just adding the `filter `calls to picklist.js at the following positions:
```javascript
...
        .on('dblclick.pickList', function() {
            var item = $(this);

            if ($(this).parent().hasClass('ui-picklist-source')) {
                $this.transfer(item, $this.sourceList, $this.targetList, 'dblclick');
                $this.filter($this.targetFilter.val(), $this.targetList); // ADDED
            }
            else {
                $this.transfer(item, $this.targetList, $this.sourceList, 'dblclick');
                $this.filter($this.sourceFilter.val(), $this.sourceList); // ADDED
            }
...
    add: function() {
        var items = this.sourceList.children('li.ui-picklist-item.ui-state-highlight')
        this.transfer(items, this.sourceList, this.targetList, 'command');
        this.filter(this.targetFilter.val(), this.targetList); // ADDED
    },

    addAll: function() {
        var items = this.sourceList.children('li.ui-picklist-item:visible:not(.ui-state-disabled)');
        this.transfer(items, this.sourceList, this.targetList, 'command');
        this.filter(this.targetFilter.val(), this.targetList); // ADDED
    },

    remove: function() {
        var items = this.targetList.children('li.ui-picklist-item.ui-state-highlight');
        this.transfer(items, this.targetList, this.sourceList, 'command');
        this.filter(this.sourceFilter.val(), this.sourceList); // ADDED
    },

    removeAll: function() {
        var items = this.targetList.children('li.ui-picklist-item:visible:not(.ui-state-disabled)');
        this.transfer(items, this.targetList, this.sourceList, 'command');
        this.filter(this.sourceFilter.val(), this.sourceList); // ADDED
    },
...
```

However, although the filter methods get called, they have no effect because it seems the changes are discarded with the following ajax response. Personally, I have no idea how to add these filters in a way that they are called after ajax response had been received.
