### ISSUE TITLE
Primeng Table isn't formatted with columns

### ISSUE THREAD

**Issue by arambrosius** [primefaces/primefaces#3338]
## 1) Environment
- Primeng Version: 5.2.0
- Angular Version: 5.2.5
- Bootstrap Version: 4.0.0

## 2) Expected behavior
![image](https://user-images.githubusercontent.com/35042830/36222260-71a2f434-1186-11e8-941d-55808d92a34a.png)

...

## 3) Actual behavior
![image](https://user-images.githubusercontent.com/35042830/36222296-887dc3be-1186-11e8-82f3-a72ec2c37eff.png)

..

## 4) Steps to reproduce
 <p-calendar [(ngModel)]="value" [inline]="true"></p-calendar>
.. 

I noticed this happened once I upgraded to bootstrap 4. Is there something that I need to add to get my columns back?

**Comment by tandraschko** [comment]
This is the PrimeFACES issue tracker, not PrimeNG.
