### ISSUE TITLE
selectOneMenu: Lazy Load multiple click duplicating select values

### ISSUE THREAD

**Issue by tjkruger23** [primefaces/primefaces#3340]
# ISSUE
When clicking multiple times on a Lazy Load selectOneMenu drop down, when there is a delay, it duplicates the values of the drop down. See screenshot 

![image](https://user-images.githubusercontent.com/14079788/36251608-6d05b136-124a-11e8-9869-675f045c761a.png)

## 1) Environment
- PrimeFaces version: 6.2.RC2
- Application server + version: Payara Server 4.1.2.173 #badassfish (build 24)
- Affected browsers: Chrome, Firefox

## 2) Expected behavior
Display the values set in the bean once as a drop down.

## 3) Actual behavior
Duplicates the values set in the bean and adds for every click.

## 4) Steps to reproduce
Download the sample program at https://github.com/tjkruger23/lazyLoadPFIssue
Used NetBeans to develop.

## 5) Sample XHTML
Look at index.xhtml.
If dynamic="true"is set to false, i.e. not lazy, it works as intended. 

## 6) Sample bean
Look at LazyLoadBean.java

**Comment by tandraschko** [comment]
a PR or deeper anaylsis would be great!

**Comment by tandraschko** [comment]
fixed by https://github.com/primefaces/primefaces/commit/d2d2f6ee4626684ab33b7c4242d9da7804a880f8

Please give it a try.
