### ISSUE TITLE
DataTable: column width causes horizontal scrollbar

### ISSUE THREAD

**Issue by Zerounodue** [primefaces/primefaces#3342]
#  Issue
The datatable width gets somehow calculated wrong.
This happens when setting the column width

this problem is also visible on one of the example:
https://www.primefaces.org/showcase/ui/data/datatable/columnResize.xhtml
"**Expand Mode with Grouping**" section

## 1) Environment
- PrimeFaces version: 
6.1.13 and 6.2.RC2
- Does it work on the newest released PrimeFaces version? Version? 
No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No
- Application server + version:
Wildfly 10
- Affected browsers:
all tested
## 2) Expected behavior

No horizontal scrollbar should be visible. width should not appear

## 3) Actual behavior

a horizontal scrollbar is visible

## 4) Steps to reproduce

go to https://www.primefaces.org/showcase/ui/data/datatable/columnResize.xhtml "Expand Mode with Grouping" section

## 5) Sample XHTML
<p:dataTable
	var="data"
	value="#{myManager.getData}">
	<p:column
		width="200">
		test
	</p:column>

	<p:column
		width="300">
		test
	</p:column>

	<p:column >
		test
	</p:column>

	<p:column >
		test
	</p:column>

	<p:column
		width="100">
		test
	</p:column>

	<p:column
		width="600">
		test
	</p:column>
</p:dataTable>

## 6) Sample bean

---

**Comment by rainermueller** [comment]
We have same issue with 6.1.14 release

```
<p:column headerText="#{msg.username}" sortBy="#{user.name}" width="100">
    <h:outputText value="#{user.name}"/>
</p:column>
```

**Version 6.1.14**
```
<th id="j_idt475:j_idt477" ... style="width: 166px;" ...
```

**Version 6.1.5 + 6.1.9**
```
<th id="j_idt475:j_idt477" ... style="width: 100px;" ...
```

**Comment by rainermueller** [comment]
The `p:dataTable` in our case has `scrollable="true"` and `scrollHeight="440"`.

The issue is gone if we remove attributes `scrollable` and `scrollHeight`.

**Comment by Zerounodue** [comment]
If you are using Mac OSX you may not see this problem because it handles scrollbars differently.
So please use Windows to test it.

**Comment by melloware** [comment]
Testing with PrimeFaces 8.0 I do not see this issue. See: https://www.primefaces.org/showcase/ui/data/datatable/columnResize.xhtml

if you still think its an issue as of PF 8.0 please report back but i will close for now.
