### ISSUE TITLE
Added ui-inputswitch-checked class to parent element on InputSwitch

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3344]

**Comment by martin654** [comment]
Hi! I run into styling issue recently with inputSwitch when I needed to have information about the state of input switch to style the component properly. This looks like it solves my problem. Thank you!

**Comment by melloware** [comment]
Looks like there might be an issue with this fix according to one user:  https://forum.primefaces.org/viewtopic.php?f=3&t=54358

@mertsincan can you investigate please?

**Comment by mertsincan** [comment]
Ok, I'll check it. Thanks @melloware ;)
