### ISSUE TITLE
selectOneMenu: Lazy Load on select menu not submitting value.

### ISSUE THREAD

**Issue by tjkruger23** [primefaces/primefaces#3345]
# Issue
If one has a select one menu drop down with dynamic/lazy property = true, it doesn't submit the value when processing.

## 1) Environment
- PrimeFaces version: 6.2.RC2
- Application server + version: Payara Server 4.1.2.173 #badassfish (build 24)
- Affected browsers: Chrome, Firefox

## 2) Actual behavior
When selecting second in the drop down and processing the dialog is empty.

![image](https://user-images.githubusercontent.com/14079788/36259910-77069a60-1268-11e8-9e0d-e762cf24c402.png)

## 3) Expected behavior
It works fine when dynamic/lazy is false.

![image](https://user-images.githubusercontent.com/14079788/36260089-fb52a228-1268-11e8-8af3-45f0b7cea2d0.png)

## 4) Steps to reproduce
Download the sample program at https://github.com/tjkruger23/lazyLoadPFIssue
Used NetBeans to develop.

## 5) Sample XHTML
See index.xhtml

            <p:selectOneMenu id="lazy" 
                             value="#{lazyLoadBean.option}" 
                             effect="fade" 
                             dynamic="true">
                
                <f:selectItem itemLabel="None" 
                              itemValue="" />
                <f:selectItems value="#{lazyLoadBean.options}"/>
            </p:selectOneMenu>

## 6) Sample bean
Look at LazyLoadBean.java

**Comment by tandraschko** [comment]
Should be the same: https://github.com/primefaces/primefaces/issues/3277
