### ISSUE TITLE
AutoComplete not working in IE8 - tested with showcase

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#335]
Some of our users said they do not get autocomplete options. I don't know what browser they used but I investigated a little in IE 11 emulation mode.

Using IE emulation mode on showcase http://www.primefaces.org/showcase/ui/input/autoComplete.xhtml the problem is visible.

**Not working**

Any document mode above `IE8` in case `User-Agent` is IE8.

`Documentmode: edge`
`User-Agent: IE8`

**Working**

`Documentmode: IE8`
`User-Agent: IE8`

**Workaround:**

Explicitly set compatibility header `X-UA-Compatible` to `IE=8' if user agent is`IE8`.
This looks redundant but it works.

**Comment by cagataycivici** [comment]
I can't seem to replicate.
