### ISSUE TITLE
Pre-sorting with comparator in Java Bean causes Sort on Column header in Datatable to break

### ISSUE THREAD

**Issue by protonbart** [primefaces/primefaces#3350]
## 1) Environment
- PrimeFaces version:
v5.0

## 2) Expected behavior
Sort should function regardless
...

## 3) Actual behavior
Sort by clicking on header wont work in datatable. 
..

## 4) Steps to reproduce
Create Datatable, have sort in it by bean.id, then do another sport in backing bean before you return list to datatable
.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
No example -> invalid. Also not tested with the newest version.
