### ISSUE TITLE
SelectOneMenu: add dirty event - which will be fired onblur when the value has been changed

### ISSUE THREAD

**Issue by jmichler** [primefaces/primefaces#3351]
## 1) Environment
- PrimeFaces version: 6.1.14
- Does it work on the newest released PrimeFaces version? Version? No, 6.1.14
- Does it work on the newest sources in GitHub? no
- Application server + version: glassfish 4.1
- Affected browsers: Chrome at least

## 2) Expected behavior
We have a select-one-menu with an ajax event behind it. We want an update to the server be fired whenever someone leaves the field with a change or selects a value by "mouse click" onto an item. 
...

## 3) Actual behavior
- with the "blur" event we get an update on each leaving the field
- with the itemSelect change or valueChange when navigating through the list with keypress up/down each keypress sends an event to the server
..

## 4) Steps to reproduce
create a selectonemenu as below. Cycle by tab to the selectOneMenu. Press key down multiple times. On each key-down we have a server-side event. You can also see this on the https://www.primefaces.org/showcase/ui/ajax/dropdown.xhtml page

## 5) Sample XHTML
<p:selectOneMenu id="selectMenu"
									value="#{propertyField.currentValue}"
									disabled="#{propertyField.disabled}"
									rendered="#{propertyField.textType eq 'PROPERTY_DROPDOWN' and (not propertyField.hidden or konfigurator.elementProperties.showAdvancedFields)}">
									<f:selectItems value="#{propertyField.options}" var="option" itemDescription="#{option.description}"
										itemLabel="#{option.name}" itemValue="#{option.id}" />
									<f:ajax render=":konfiguratorForm:left" event="blur"/>
								</p:selectOneMenu>
..

## 6) Sample bean
not really relevant
..

**Comment by tandraschko** [comment]
Don't understand your requirement. Do you mean you need a event when the selection will be changed?

**Comment by jmichler** [comment]
yes. But when navigating with the keyboard through that list I don't want the event to be fired on each "change" of the selected row but only when the menu looses the focus. Or at least stays on a selection for 5 seconds or so. I've tried to implement this using the "Blur" event but that fires also when I navigate through my form without any changes at all.

**Comment by tandraschko** [comment]
I see. In CKEditor it's called "dirty" and it will be fired when the value is changed via the blur event.
It could be quite tricky to implement, therefor i would suggest to sponsor it via PrimeFaces PRO.

As workaround you could probably use the change event with a delay configured.

**Comment by melloware** [comment]
Going to close this.  Its been 5+ years and no one else has asked for it and as Thomas mentioned you can use change event with a delay set.
