### ISSUE TITLE
Spinner negative values are broken with min attribute unset

### ISSUE THREAD

**Issue by georgwolf** [primefaces/primefaces#3352]
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT (up to commit d2d2f6e)

## 2) Expected behavior
Spinner with no min value set spins from 0 to -1, -2 etc.

## 3) Actual behavior
Spinner set to -5e-324 when spinning past zero

## 4) Steps to reproduce
Run Primefaces Showcase with latest 6.2-SNAPSHOT and decrease Basic Spinner (on the Input -> Spinner page) past zero

This is related to issue #3320 / pull request #3322, but as they're already closed I thought it's better to open a new issue so that this doesn't slip into 6.2 final.

IMO in spinner.xml the default min value should be "-java.lang.Double.MAX_VALUE" as Double.MIN_VALUE is actually the smallest positive double while Double.MAX_VALUE is the largest magnitude and since the sign is a separate bit "-java.lang.Double.MAX_VALUE" is the largest negative value then.

**Comment by tandraschko** [comment]
AFAIK i reverted all the changes, so the behavior should be like 6.1. Everything else will go into 6.3.

**Comment by tandraschko** [comment]
oh sorrry, now reverted also the min value / spinner.xml.

**Comment by tandraschko** [comment]
Could you please try with a trunk build again?

**Comment by georgwolf** [comment]
Yes, with latest commit 3b9cc9d spinner is working as expected
