### ISSUE TITLE
DataTable: add possibility to define load method separately from model

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3354]
Currently, the org.primefaces.model.**LazyDataModel** used in DataTable component 
does both:
- data loading using load method(s)
- data holding being a model class

This doesn't have to be suitable for all applications. In our case we made architectional decision, that "model" and "controller" should be separated with different scopes and with different responsibilities.  "Model" classes are usually "view scoped" or "flow scoped" and "controller" classes are usualy "singleton scoped". Lazy data model forces us to put those two things together.

I suggest to add a possibility to define the "load" method(s) separately on the DataTable component. There is a piece of code to ilustrate this issue:

Suggested case with separate load method:
```
<p:dataTable widgetVar="productTable" var="row" lazy="true" value="#{model.products}" paginator="true" 
  rows="10" rowsPerPageTemplate="5,10,20,50" sortMode="multiple" 
  paginatorTemplate="{Customization} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" 
  load="#{controller.loadProducts}" >
...
</p:dataTable>
```
- model.products id standard LazyDataModel load method NOT implemented
- controller.loadProducts is method like LazyDataModel.load
- internal logic of DataTable would detect presence of load attribute (MethodExpression) and would use this method to load data into given value list instead of LazyDataModel.load.

Would this approach be feasible? 

We could do this ourselves extending PF DataTable and adding this feature, but other people could benefit from if it was done directly in Primefaces.

Thanks,
Martin

**Comment by tandraschko** [comment]
I also seperate controllers and models but i can't follow for 100%.
Maybe you can give a small example.

A model for a lazyDataModel should never be put into a passivating scope as the memory usage is quite high and serializiation is sometimes required. The best way is to implement a lazyDataModel which directly calls the DB/Repositories. This can simple be added to your controller.

**Comment by martin654** [comment]
Well, in our application we use @Controller annotated classes for logic. Those classes are stateless and efectively singletons. Then we have @Model annotated classses (injectable FlowScoped beans) where we store data. This @Model annotated classes are typically injected into Controllers (using proxy because we inject them to wider scope).
Concept of LazyDataModel does not fit this data / logic separation architecture in our app.

If we annotated specific implemetnation using @Controller, it could call services and load data in load method and store them in injected @Model, but unfortunatelly LazyDataModel has it's state in it. This state would be shared, because as I mentioned, @Controllers are singletons in our case.

Other option is to annotate LazyDataModel using @Model, but then it should not call services or other controllers.

Third option is to annotate it both @Model and @Controller but this violates our architecture. The reason is separation of application layers, when Model should never call Controller or Service.

I hope this brief explanation makes sence to you.

How can we "fix" this?
- allow to specify load attribute on DataTable component as suggested earlier
- change LazyDataModel's implementation in a way that the inner state (4 class level fields) could be placed elsewhere (on our FlowScoped model) efectively making it stateless and possible to annotate it with @Controller. This can be done a nasty-way in our app just simply overriding everything and referencing injected Model in every method instead of using class-fields. Or it can be done better way, that we could alter Primeface's LazyDataModel in a way that we could override let's say new getLazyDataModelState() method and provide our data here.

Please let me know if you need more explanation to understand our problem.

Thanks

**Comment by martin654** [comment]
@tandraschko Thomas, I see you added 'new feature' label here. Is adding new 'load' attribute on dataTable as I suggested the preffered way to handle this issue?

**Comment by tandraschko** [comment]
there is no preffered way for now ;)
I just added the label as it would be a new feature.

**Comment by martin654** [comment]
@tandraschko Thomas, I have another question related to load method. The **load** method is invoked in RENDER_RESPONSE phase, which is inconvenient because error messages could occur here and they would not typically be rendered because p:messages are in most cases rendered as one of first components. We have to do workarounds such as remembering messages and invoking another request using RemoteCommand to retrieve them. Should I create another issue for this? Or could it be considered as part of this ticket?

**Comment by tandraschko** [comment]
IMO i would create a new ticket

**Comment by martin654** [comment]
Created new ticket for this: https://github.com/primefaces/primefaces/issues/3501

**Comment by melloware** [comment]
@martin654 I have been using Lazy datatable for years and I don't quite understand your use case and i think it would add more confusion to users.

I am going to close this ticket for now as there have been no upvotes in years and I really don't think this would be an improvement in behavior or usability.
