### ISSUE TITLE
PanelGrid: search for p:row also in child/childs (e.g. in composites)

### ISSUE THREAD

**Issue by koflerdavidgrawe** [primefaces/primefaces#3355]
## 1) Environment
- PrimeFaces version: 6.1, 6.2.RC2
- Does it work on the newest released PrimeFaces version? Version? See above
- Application server + version: Tomcat 8.0.37
- Affected browsers: Chrome, FF

## 2) Expected behavior
Composite is rendered including its insertChildren

## 3) Actual behavior
a) ui:insertChildren components are not rendered
b) Exception is thrown if insertChildren components are accessed

## 4) Steps to reproduce
[CompositeBugReproducer.zip](https://github.com/primefaces/primefaces/files/1743874/CompositeBugReproducer.zip)

Composite with p:row and composite:insertChildren within
Page with an ui:include and 1 instance of the composite.
The include is dynamic (toggled via a button in the reproducer) were the composition included first contains 1 composite instance, the composition included later contains 2 composite instances.

## 5) Sample XHTML
```
<h:body>
	<h:form>
		<h:panelGroup>
			<ui:include src="#{testBean.string}" />
			<g:testComposite>
				<h:outputText value="" id="testCompositeId1" />
			</g:testComposite>
		</h:panelGroup>
		<h:commandButton action="#{testBean.toggleStatus()}" value="Toggle" />
	</h:form>
</h:body>
```

```
<composite:implementation>
	<!-- ERRORNEOUS CASE -->
	<!-- value call crashes if child is not present, this is just to have an exception when the error occurs -->
	<p:row>
		<h:outputText
			value="#{cc.getFacets().get('javax.faces.component.COMPOSITE_FACET_NAME').children.get(0).children.get(1).id}" />
		<composite:insertChildren />
	</p:row>

	<!-- WORKING CASE -->
	<!-- value call crashes if child is not present, this is just to have an exception when the error occurs -->
	<!-- 	<h:outputText -->
	<!-- 		value="#{cc.getFacets().get('javax.faces.component.COMPOSITE_FACET_NAME').children.get(1).id}" /> -->
	<!-- 	<composite:insertChildren /> -->
</composite:implementation>
```

## 6) Sample bean
Not needed, bean in the reproducer is just a means to toggle the include.

## 7) Notes
- It works fine if both includes contain the same amount of composite instances.
- Children are added to javax.faces.component.UIComponentBase.ChildrenList in both cases, in the erroneous case the children are later missing in org.primefaces.renderkit.CoreRenderer.renderChildren(FacesContext context, UIComponent component)

**Comment by tandraschko** [comment]
I don't think we can fix it, it's up to the JSF impl AFAICS.

**Comment by tandraschko** [comment]
Also the example seems invalid. You can't use p:row as child of composite:implementation.
Also can't see the sense of the ui:include to replicate it.

**Comment by koflerdavidgrawe** [comment]
As the example shows it is working fine without the p:row tag. So I dont think its an issue of the JSF Impl.
Why cant a p:row be a child of a composite:implementation? We have a p:panelgrid surrounding multiple instances of the composite, which substituted gives a valid setup

**Comment by tandraschko** [comment]
The example shows a h:panelGrid.

**Comment by koflerdavidgrawe** [comment]
We wanted to reproduce using as little PF components as possible. The same issue arises with a p:panelGrid, as well as a p:column as a child of that. 
I can provide another reproducer if need be

**Comment by tandraschko** [comment]
I see your usecase but the example doesnt match. But doesn't matter.

The problem is, like in other components, that we only scan the direct childs.
In the PanelGrid case, we only look for p:row in the direct childs instead of looping through e.g. composites.

The same problem happens e.g. with p:tab in p:accordion.

So it's a new feature as it's currently never designed to work with composites.

**Comment by koflerdavidgrawe** [comment]
Are you sure that is the underlying cause? The composites content, as well as the h:outputText, which is a child of the p:row, in the example is rendered. Just the substitue of composite:insertChildren is missing

**Comment by tandraschko** [comment]
I'm almost sure yes. Otherwise we can't fix insertChildren.
Also i don't have time for it.

**Comment by koflerdavidgrawe** [comment]
Okay. How can we help you implement this feature? When can we expect this to be looked at?

**Comment by tandraschko** [comment]
To be honest: you can't expect anything as this is a community issue tracker and quite high effort.
There are 3 ways to get a fix:
- use PrimeFaces PRO support to sponsor the fix
- investigate by yourself and provide a PR to fix that issue
- wait until someone from the community fixes it

**Comment by Rapster** [comment]
Composites wraps the content into a UINamingContainer, so your rows will never be a direct child of panelGrid: it is by design, PF can't do anything about that, or we'll have to make an exception (which will result to ugly code and lost of perf). An easy way to fix your issue is to use facelet tags (since it includes content as it is)
