### ISSUE TITLE
DataTable: .on('...', radioSelector, ...) is slow due to jQuery deficiency 

### ISSUE THREAD

**Issue by vlsi** [primefaces/primefaces#3359]
## 1) Environment
- PrimeFaces version: 3.4.1
- Does it work on the newest released PrimeFaces version? problem is present in `master`
- Does it work on the newest sources in GitHub? problem is present in `master`
- Application server + version: (does not matter, but Weblogic 10g)
- Affected browsers: IE, Chrome

## 2) Expected behavior
DataTable mouseover/mouseout should NOT take lots of resources / JavaScript time

## 3) Actual behavior
DataTable mouseover/mouseout processing is extremely slow when lots of checkboxes present in the table (~100ms, so the highlighting is lagging behind the cursor)

My analysis is as follows:
3.1) DataTable uses jQuery `on` method with `selector` parameter (see https://github.com/primefaces/primefaces/blob/c0c86f31cd530781a6216a0b650a6ff84f8bc1a3/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L632-L652 )

3.2) The event bubbles up to the table level (as DataTable registers the event listener to the table)

3.3) As jQuery tries to identify matching handlers, it executes the provided selector (the selector returns lots of elements!), then jQuery verifies if the event target is in the result set (see https://github.com/jquery/jquery/blob/625e19cd9be4898939a7c40dbeb2b17e40df9d54/src/event.js#L394-L396 ). That is it executes `jQuery( sel, this ).index( cur )`.

The relevant jQuery issue is https://github.com/jquery/jquery/issues/3254

## 4) Steps to reproduce
Add lots of checkboxes to the table (e.g. 100 rows, 10 columns)

**Comment by tandraschko** [comment]
Could you try to provide 1-2 possible solutions to optmize it?

**Comment by vlsi** [comment]
@tandraschko , I think the workaround would be to avoid passing `selector` argument, and add an additional check to the event listener itself.
That is the event handler would be executed, and it would recheck if the element in question is `ui-radiobutton-box` with appropriate parents, etc.

What do you think?

**Comment by vlsi** [comment]
Technically speaking, `radioSelector` is not that complicated, and it might be even optimized at jQuery side. That is jQuery might rewrite the selector to "walk parents, and check class names" kind of filter condition (==reopen https://github.com/jquery/jquery/issues/3254 and optimize jQuery). That, however, sounds harder than fixing a couple of `on` calls in the DataTable code.

**Comment by vlsi** [comment]
Update: actual PrimeFaces version is 3.4.1, and in that version the events are bound to document: https://github.com/primefaces/primefaces/blob/3_4_1/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L322

**Comment by vlsi** [comment]
It seems to be improved in https://github.com/primefaces/primefaces/commit/c0386d2485ee9f9bcb55e3b69e19414dc8f7fa0c

**Comment by vlsi** [comment]
@tandraschko , just in case: even though binding events to the table is better, it does not solve the issue.
It just keeps the impact within the table.

**Comment by tandraschko** [comment]
Could you then please rework your description to match the 6.1/6.2?

**Comment by tandraschko** [comment]
Will close it for now.
tried a DataTable with 200 entries and there is no delay.
