### ISSUE TITLE
DataTable: columns with groupRow=true hides rows

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#3360]
Using _columns_ with _groupRow_="true" in a dataTable hides rows under certain circumstances. In the JEE7 example below, the first and third example is displayed correctly. However, the second table has a row, that could be grouped with the first AND the third row for different columns. In these cases, it's erroneously not displayed at all. During 6.2 development, _groupRow_ bugs have already been fixed. The reason seems not to be Primefaces but the display of _rowSpan_ in browsers, which is documented under https://stackoverflow.com/questions/48930757/rowspan-hides-rows. So you could well argue that this is not a Primefaces problem but than it should be documented or there should be a workaround, as typically the user needs these rows displayed in many usecases. 

## 1) Environment
- PrimeFaces version: (all) PrimeFaces 6.2.RC2 (newest, older even worse)
- Application server + version: Wildfly 11.0.0 (newest), JEE7
- Affected browsers: all (Chrome, FF, IE)

## 2) Expected behavior
All rows should be visible

## 3) Actual behavior
One row is missing

## 4) Steps to reproduce
Just display the XHTML below in a JEE7 enviroment, or create the values in a bean.

## 5) Sample XHTML
```XHTML
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui">
<h:head />
<h:body>
	<h:form>
	<h3 style="color:green">Correct: groupRow=false, value=[[0,1],[0,2],[1,2]]</h3>
	<p:dataTable var="row" value="#{[[0,1],[0,2],[1,2]]}" tableStyle="display:inline">
		<p:columns var="col" value="#{[0,1]}" headerText="#{col}" groupRow="false">
			<p:outputLabel value="#{row[col]}" />
		</p:columns>
	</p:dataTable>
	<h3 style="color:red">Wrong: groupRow=true, value=[[0,1],[0,2],[1,2]]</h3>
	<p:dataTable var="row" value="#{[[0,1],[0,2],[1,2]]}" tableStyle="display:inline" >
		<p:columns var="col" value="#{[0,1]}" headerText="#{col}" groupRow="true">
			<p:outputLabel value="#{row[col]}" />
		</p:columns>
	</p:dataTable>
	<h3 style="color:green">Correct: groupRow=true, value=[[0,1],[0,2],[3,3]]</h3>
	<p:dataTable var="row" value="#{[[0,1],[0,2],[3,3]]}" tableStyle="display:inline" >
		<p:columns var="col" value="#{[0,1]}" headerText="#{col}" groupRow="true">
			<p:outputLabel value="#{row[col]}" />
		</p:columns>
	</p:dataTable>
	</h:form>
</h:body>
</html>
```
![grafik](https://user-images.githubusercontent.com/415392/36537049-4794dd02-17cf-11e8-8d0a-ce0a256eabfb.png)

## 6) Sample bean
XHTML already sufficient

**Comment by mdzaebel** [comment]
One first idea could be, to group from left to right and avoid overlapping rowGroups, that would fall together if they don't have other discriminating columns [datatable.js:groupRow()].

**Comment by mdzaebel** [comment]
There is a better answer from Stackoverflow. Just add the style _height:1em_ to each row (or something similar) when _groupRow=true_. Of course, side effects to other usecases have to be considered in advance.

**Comment by melloware** [comment]
@mdzaebel Thank you for reporting. Since you have provided a CSS workaround I am going to mark this as closed.  This would be odd for PF to try and fix this when its an underlying HTML/CSS issue.  But thank you for posting your workaround!

https://stackoverflow.com/a/48957267/502366
