### ISSUE TITLE
Issue with p:rowExpansion persisting data 

### ISSUE THREAD

**Issue by ahmedelbadry3** [primefaces/primefaces#3361]
Hello guys,

I've been playing around with 6.2RC2 but yet the problem of persisting the data in rowExpansion after toggle seem to exist. any ideas?

thank you

**Comment by jxmai** [comment]
@ahmedelbadry3  Could you please provide more details (sample) since I should have fixed this problem in #942  ?

**Comment by ahmedelbadry3** [comment]
<p:rowExpansion styleClass="variant-expansion" id="variantDetails" >
                                    <p:repeat value="#{addDealBean.attributeVariantList}" var="attr">
                                        <h:panelGrid columns="1" style="border: none">
                                            <h:outputLabel for="attSel" value="Choose the #{attr.attributeName}"/>
                                            <p:selectOneRadio id="attSel" value="#{addDealBean.selectedAttributes[attr.attributeId].attributeName}"
                                                              style="border: none">
                                                <f:selectItems value="#{attr.attributeValues}" var="c" itemLabel="#{c}" itemValue="#{c}"/>
                                                <p:ajax listener="#{addDealBean.onRadioValueChange(attr.attributeId, addDealBean.selectedAttributes[attr.attributeId].attributeName)}"/>
                                            </p:selectOneRadio>
                                        </h:panelGrid>
                                    </p:repeat>
                                </p:rowExpansion>

**Comment by jxmai** [comment]
Could you replicate the problem using https://github.com/primefaces/primefaces-test ?

 (Remember to set the version to 6.2 SNAPSHOT on this line https://github.com/primefaces/primefaces-test/blob/master/pom.xml#L27 to match https://github.com/primefaces/primefaces/blob/master/pom.xml#L15)
