### ISSUE TITLE
Implement Iterator for LazyDataModel

### ISSUE THREAD

**Issue by luizphilipim** [primefaces/primefaces#3364]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: jetty-8.1.9.v20130131
- Affected browsers: All browsers

## 2) Expected behavior

For each over dataModel ends loop.

## 3) Actual behavior

For each over dataModel causes endless loop.

## 4) Steps to reproduce

Create a lazy datatable with a datamodel, then try to do a loop over it.
In the following sample, just click in a row to trigger onRowSelect method.

## 5) Sample XHTML

Just use the showcase DataTable - Lazy:
http://localhost:8080/showcase/ui/data/datatable/lazy.xhtml

## 6) Sample bean

Using showcase project, in class LazyView, add the following code to onRowSelect method:

```java
for (Car car : this.lazyModel) {
	System.out.println(car.getId());
}
```

**Comment by tandraschko** [comment]
I see. It's no problem to create a own iterator here but NOTE: it will call the DB X times.

**Comment by tiagojn** [comment]
I'm having the same infinite loop problem on my servers, but over here we call it a bug  :smile:

**Comment by tandraschko** [comment]
Hm :D it would say: it was never a requirement, so it's a enhancement

**Comment by tandraschko** [comment]
Also there are 2 possible implementations possible:
1) load everything and then loop over it
2) load in steps/pages and do it lazy in the iterator#next method

**Comment by tandraschko** [comment]
Ok it's a little bit more effort... it would be great if someone could create a Iterator implementation which takes as LazyDataModel as constructor arg - i could add it then.
Or sponsor it via PrimeFaces PRO.

**Comment by luizphilipim** [comment]
Also there are 2 possible implementations possible:

1. load everything and then loop over it - I have a datatable with over 1M rows, if load everything, my server will crash :(
2. load in steps/pages and do it lazy in the iterator#next method - it would be ideal

**Comment by cnsgithub** [comment]
In my opinion the first approach would render `LazyDataModel` useless because that would be in fact eager behavior which is sometimes simply impossible. 

The second variant has to be implemented to be confirm to laziness and `Iterator` specifications.

However, to achieve this, the `Iterator` must be in knowledge of sort and filter requirements, otherwise calling `LazyDataModels's `load methods the correct way is impossible. Therefore quite a few refactorings would be necessary.

**Comment by tandraschko** [comment]
i don't think that any sorting or filtering should be applied when doing a for-each over the direct model.
Also it's impossible to pass something via a for-each loop. 
What we coud do is:
1) provide a simple iterator, without any sorting or filtering, so a for-each will work
2) provide a overloaded iterator() method to allow to pass filtering and sorting options

IMO no refactoring is required.

**Comment by cnsgithub** [comment]
In principle, `LazyDataModel.load `could be called in `LazyDataModelIterator.hasNext `to decide whether there are more rows or not. The response could be hold as a prefetch in the iterator instance to be simply returned when `LazyDataModelIterator.next` gets called. This would reduce requests to the database for example. 

@tandraschko The disadvantage of overloading the `iterator `method is that it cannot be used any longer with `foreach`.

A completely different approach would be possible if we knew the exact future-size of the data source beforehand. However, to achieve this in a database would make it necessary to fire a fully blown `select count(*)` beforehand which can be almost as expensive as fetching all rows at once. So, in my opinion, I think this is also not a good idea.

**Comment by tandraschko** [comment]
I would do it the following way:
Add a local variable "int currentRow" and increase this on #next.
#hasNext should simple compare the currentRow with lazyDataModel#getRowCount

This is quite a simple impl
a little bit better would be to load multiple items on "next", doing a query for each single item will lead to bad peformance

**Comment by cnsgithub** [comment]
Pull request: https://github.com/primefaces/primefaces/pull/3370
