### ISSUE TITLE
Schedule: allow custom markup

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#3367]
_Schedule_ could be made more flexible if styling would not be defined in java, but in xhtml markup. Java is the wrong place for styling which currently allows for title, description and adding css-classes.

https://stackoverflow.com/questions/8702058/add-custom-html-to-a-jquery-fullcalendar-cell/24563491 

**Feature:**

Event's are often based on complex data and have more information then just title and a simple description. The tooltip of an event could provide much more informations like order informations, further links to customer website, geo-location and such. Depending on data events could show different icons, like in primefaces timeline showcase.

**Request:**

Add a _p:scheduleEvent_ component bound to inferface _ScheduleEvent_ which allows advanced rendering similar to _p:treeNode_ component. 

**Simple**

    <p:schedule var="varEvent">
        <p:scheduleEvent title="#{varEvent.data.name}" description="#{varEvent.data.description}"/>
    </p:schedule>

**Complex:**

    <p:schedule var="varEvent">
        <p:scheduleEvent styleClass="#{getEventColor(varEvent.data)}">

            <h:panelGroup id="myEvent" >
                
                <i class="fa fa-truck"/><h:outputText value="#{varEvent.dataStart} - #{varEvent.dataEnd}"/>
                
                <i class="fa fa-user"/><a href="http://google.com/maps/q="><h:outputText value="#{varEvent.data.customer.name} "/></a>
            </h:panelGroup>

            
            <p:tooltip for="myEvent"><comp:myEventInfo event="#{varEvent}"/></p:tooltip>

        </p:scheduleEvent>
    </p:schedule>

## 1) Environment

- PrimeFaces version: 6.2

## 2) Expected behavior

- allow event markup to be defined in xml and not java

## 3) Actual behavior

- limited styling and rendering capabilities must be set in java event constructor

**Comment by djmj** [comment]
Do we need to create Event objects programmatically. Could following schedule not internally create events itself based on markup?

     public class Order
     {
           Date start;
           Date end;
     }

     <p:schedule var="varOrder" value="#{bean.ordersDataModel}">
         <p:scheduleEvent start="#{varOrder.start}" end="#{varOrder.end}" title="#{varOrder.customer.name}" styleClass="#{el:getEventColor(varOrder)}">
             <!-- advanced info --
             <h:outputText value="#{varOrder.customer.address}"/>
         </p:scheduleEvent>
     </p:schedule>

**Comment by OBreidenbach** [comment]
The schedule component is a wrapper around the [fullCalendar](https://fullcalendar.io/). 
So you can configure fullCalendar how to render an event:

This can easily be achieved by configure the underlying fullCalendar with the provided extender hook.
```
<p:schedule ... extender="initSchedule" ... />

function initSchedule() {
	// Configure fullCalendar
	this.cfg.eventRender = function (event, element, view) {
		...
	};
}
```
The fullCalendar has much to many options to provide them all directly in the component interface. 
With the extender method there is already a opportunity to achive the desired goal. 
So IMHO this ticket should be closed.

**Comment by melloware** [comment]
Agree with @OBreidenbach this is exactly what the Extender is for.
