### ISSUE TITLE
Como pasar de la 5.3 a 6.x

### ISSUE THREAD

**Issue by jorgeaquino** [primefaces/primefaces#3368]
Quiero saber que tengo que hacer para cambiar de versión de primefaces 5.3 a las 6.x

**Comment by cnsgithub** [comment]
This issue tracker is meant to report problems - in English language. For questions you should use the forum: https://forum.primefaces.org/

This should answer your question:
https://github.com/primefaces/primefaces/wiki/Migration-Guide
