### ISSUE TITLE
Add support for channels in other web applications to <p:socket>

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#337]
Reopening [Google Code Issue 5176](https://code.google.com/p/primefaces/issues/detail?id=5176) which was originally opened by [Kito Mann](https://code.google.com/u/116023911140613727202/):

> Currently, `<p:socket>` assumes that the channel to which you want to connect is in the same web application. It would be great if the component could support channels to other web applications. This would allow completely different web applications to send push notifications to each other, and as well as portlet inter-communication between portlets in different web applications.
> 
> I suggest adding a new attribute called `baseURL`:
> 
> ```
> <p:socket baseURL="/another-app/" channel="chat"/>
> ```
> 
> This would generate the following markup:
> 
> ```
> widgetVar = new PrimeFaces.widget.Socket({
>     url:"/another-app/primepush/chat",
>     ...
> }
> ```

**Comment by cagataycivici** [comment]
We'll consider, thanks.

**Comment by tandraschko** [comment]
PrimeFaces Push will be deprecated in 6.2 and removed in 6.3 ( see https://www.primefaces.org/primefaces-6-2-roadmap/)
Therefor i will close this issue as won't fix. If you will provide a PR to fix this issue until 6.2 RC1, i can merge it.
