### ISSUE TITLE
p:inputNumber not updating after ajax value update

### ISSUE THREAD

**Issue by adjiandov** [primefaces/primefaces#3371]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? 
- No, I tried it on 6.2.RC2
- Does it work on the newest sources in GitHub? 
-It does not.
- Application server + version:
JBoss Wildfly 10.1.0
- Affected browsers:
-Tested on Chrome and Firefox.
## 2) Expected behavior
The inputNumber component value should display the newly updated value after its backing bean value has been changed and the partial page update is being executed.

## 3) Actual behavior

The inputNumber component is being updated (rerendered) after the ajax request completes, this is visible by looking at its title attribute (it is visible that the title attribute gets updated), but the value itself does not receive the newly assigned value.

For the next 3 points I am attaching a small sample based on the prime-faces-test git project. 
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/1763048/primefaces-test-master.zip)

## 4) Steps to reproduce

Click the updateValue link on the test page.

## 5) Sample XHTML

Provided in the attachment

## 6) Sample bean

Provided in the attachment

**Comment by tandraschko** [comment]
The exact same code doesn't work with a p:inputText

**Comment by tandraschko** [comment]
Works fine without immediate.
Will close it as invalid because i can't see a bug, just a weird example ;) Please use the forum.

**Comment by tandraschko** [comment]
JFYI: i never never never used immediate and i use JSF since 8 years ;) It has a weird behavior if you don't know what happens for 100%. Just don't use it.

**Comment by adjiandov** [comment]
@tandraschko Thank you very much. I tried the forum before I posted here, it just never occurred to me that this would cause the issue. Saved me a lot of troubles. :)

**Comment by cnsgithub** [comment]
Immediate has some valid use cases though. One example could be when you need to perform an action on server side 'immediately' (just like the name says), without having to care about whether any input fields which may require validation are correctly filled by the user.

**Comment by tandraschko** [comment]
Sure you could use it for that - but it feels broken for me. That means that the button actually is independent from the inputs and validation doesn't matter. I just use "process=@this" for this purpose.
