### ISSUE TITLE
Hascode method of CheckBoxTreeNode do not use the rowkey attribute

### ISSUE THREAD

**Issue by kaizokun** [primefaces/primefaces#3374]
Hi, the hashcode method of the CheckBoxTreeNode class do not use the rowkey attribute like the DefaultTreeNode class. So two CheckBoxTreeNodes that contain the same datas are considered as equals. Apparently it is an issue and someone asked me to post it here.

**Comment by Rapster** [comment]
Please follow the issue template next time...

**Comment by tandraschko** [comment]
Could some provide a PR for this? (@melloware @jxmai @Rapster @cnsgithub ?)

**Comment by tandraschko** [comment]
there is nothing to reproduce here, so i think it's ok.
We added a change last year to the DefaultTreeNode to take the rowKey into equals/hashcode.

**Comment by kaizokun** [comment]
Ok thank you, is there a particular reason that it's not the case for the CheckBoxTreeNode ?

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3376

**Comment by tandraschko** [comment]
Thanks
