### ISSUE TITLE
p:tree with propagateSelectionDown to false but propagate anyway

### ISSUE THREAD

**Issue by kaizokun** [primefaces/primefaces#3375]
Hello,

I have a strange issue with the tree component. The bean 'MyBean' use a view scope.

```
 <p:tree id="mytree" value="#{myBean.tree}" var="file" selectionMode="checkbox"
            selection="#{myBean.selectedFileNodes}"
            propagateSelectionDown="false" propagateSelectionUp="false"
            animate="true" dragMode="self" cache="true" dynamic="true" 
            draggable="true"droppable="true"
            dragdropScope="fileTreeScope">

        <p:ajax event="select" update="..."/>
     
     </p:tree>

    <p:commandButton value="test" actionListener="#{myBean.test}" update="mytree"></p:commandButton>

```

I update the tree it with a simple button to test.

If I select a node, with the propagateSelectionDown to false, the child nodes are not selected ( so it works ) and with the p:ajax the myBean.selectedFileNodes array is populated with the unique checked node.

Then if I update the p:tree with a simple button the selection is propagated to all the children nodes.

I found a solution inside the actionListener test so before the render response phase : I get the node send to the server, then I use **node.setSelected(value : false, propagate : true)** to unselect the node and its children.
Finaly I use **node.setSelected(value : true, propagate : false)** to re-select the node but this time without the children, and I can keep the node selected. And visually the component stay the same for the user.

**Comment by tandraschko** [comment]
Please follow the issue template.

**Comment by kaizokun** [comment]
I don't have time...

**Comment by tandraschko** [comment]
Why should we invest time in our freetime to check your issue when you even don't have time to provide a reproducer?
No, thanks. Thats not how open source works.

**Comment by kaizokun** [comment]
Sorry I have been a bit rough, it's just that I 'm not familiar with github ... I just want to help, but of course I 'm not that involved than you, I should be more grateful. From my point of view it is a not expected behavior considering the component configuration and I wanted to signal it. I've been able to get the behavior I expected so I don't know if it is an issue or something not implemented yet. I'll resend my post properly if I have time.
