### ISSUE TITLE
DialogFramework: add ability to define a custom widgetVar

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#3378]
Recently, I have posted some remarks about the interception of closing/hiding DialogFramework.

I have now a solution when some parts are explain in
https://github.com/primefaces/primefaces/issues/3373
https://github.com/primefaces/primefaces/issues/2538

This work well, but it is very complicated and tricky to find the DialogFramework Primefaces widget.
I explain that in forum https://forum.primefaces.org/viewtopic.php?f=3&t=54492

The code used to find the PF('widget') is

```
var wgDialog = jQuery(".ui-dialog.ui-overlay-visible",window.parent.document)
                .each
                    (function(nIndex)
                        {
                        var sWidgetName = $(this).attr('data-widgetvar');
                        var wgDialog = window.parent.PF(sWidgetName);
```

It would be simpler if a "widgetvar" attribute exists for DialogFramework widget.

Can somebody at Primefaces team implement that request ?

**Comment by cnsgithub** [comment]
Just for your information: none of your links are working correctly. Could you please correct them in order to get the GitHub referencing working? Simply copy&paste the links, markdown automatically detects them...

https://github.com/primefaces/primefaces/issues/3373
https://github.com/primefaces/primefaces/issues/2538
https://forum.primefaces.org/viewtopic.php?f=3&t=54492

**Comment by tandraschko** [comment]
I even thought about to remove every data-widgetvar as you can simple get the widget via the ID -> PrimeFaces.getWidgetById(elementId)

**Comment by tandraschko** [comment]
See: https://github.com/primefaces/primefaces/issues/3263

**Comment by tandraschko** [comment]
Will likely be a won't fix but lets discuss it if not possible via PrimeFaces.getWidgetById ;)

**Comment by schlebe** [comment]
@cnsgithub: I have corrected the link.

@tandraschko: I understand your proposal but for DialogFramework, it is not possible to assign the ID !

@tandraschko: you have changed the title but this is not correct because DialogFramework has already an data-widgetvar ! What I want is to have the possiblity to define a custom widget-varname that I can simply retrieve using PF('widgetname') javascript function.

**Comment by cnsgithub** [comment]
You can try to set a custom-id and based on the id you can probably get the name 
_dlg -> _dlgwidget
: -> _

**Comment by tandraschko** [comment]
I see. Feel free to provide a PR or sponsor it. Not sure how easy it is.

**Comment by svrolanski** [comment]
I was just dealing with DialogFramework and needed to set the widgetVar, I thought passing it on options map would set the ID or widgetVar, but it doesn't. The processing of the options map should be extended (id, widgetvar, class, style, etc.) so we can customize and manipulate the dialog easily.

**Comment by tandraschko** [comment]
would anyone like to provide a PR?

**Comment by melloware** [comment]
I can work on this.

**Comment by schlebe** [comment]
Thanks to Melloware having implemented this enhancement; but I have stopped to develop in Java for my customer. I regret, but I don't have the opportunity to test this new function. I want only to thank Melloware for his work. Bye
