### ISSUE TITLE
Autocomplete documetation update

### ISSUE THREAD

**Issue by mateuszkl** [primefaces/primefaces#3379]
In PrimeFaces 6.1 user guide in Autocomplete section -> POJO Support, it says: 
"Note that when working with pojos, you need to plug-in your own converter"

Actually it's kind of false, becouse OmniFaces ListConverter works just fine. Just letting you know.
Their docs don't mention this, but it works 100%, no need to write custom converter.
`
<p:autoComplete value=....>
                                <o:converter converterId="omnifaces.ListConverter" list="#{bean.accounts"/>
                                <p:ajax event=.../>
                            </p:autoComplete>`

**Comment by tandraschko** [comment]
from primefaces perspective, omnifaces converter is a "own" converter.

**Comment by mateuszkl** [comment]
I agree, but it would be nice to know immediately that it's compatible. I wasted some time before i found this solution, and it's not like they're competitors.

**Comment by tandraschko** [comment]
I dont think it makes a big difference if we replace "own converter" with "a converter" and we will also not mention the omnifaces converter in our docu as its also a converter

**Comment by mateuszkl** [comment]
yeah, I guess it doesn't
