### ISSUE TITLE
Breadcrumb: allow custom markup

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#3380]
Using breadCrumb involves complicated and unncessary use of MenuModel to represent a linear data structure. This binds markup to Java code and makes rendering less flexible.

A tag like _p:menuItems_ with _var_ attribute. Even more flexible would be renderer for _p:menuItem_ in combination with _ui:repeat_ since it allows declaration of child _f:param_ of item.
 
**Example:**

Menuitems

    <p:breadCrumb>
        <p:menuItems var="varCategory" value="#{bean.flattenNode(bean.childCategory)}" label="#{varCategory.name}"/>
    </p:breadCrumb>

Like timeline using direct child:

    <p:breadCrumb var="varCategory" value="#{bean.flattenNode(bean.childCategory)}">
        <p:menuItem value="#{varCategory.name}" outcome="/sites/category.xhtml">
            <o:param value="#{varCategory} name="category" converter="#{bean.categoryConverter}"/>
        </p:menuItem>
    </p:breadCrumb>

ui:repeat

    <p:breadCrumb>
        <ui:repeat var="varCategory" value="#{bean.flattenNode(bean.childCategory)}">
            <p:menuItem value="#{varCategory.name}" outcome="/sites/category.xhtml">
                <o:param value="#{varCategory} name="category" converter="#{bean.categoryConverter}"/>
            </p:menuItem>
        </ui:repeat>
    </p:breadCrumb>

Issue is very similar to #3367 and #915.

**Comment by melloware** [comment]
@djmj no upvotes in almost 5 years and many other breadcrumb features added.  If you feel strongly about this I suggest sponsoring it via PRO support

**Comment by djmj** [comment]
Yeah i did send a PRO request some days ago. The response was, since programmatically API is stable there is no time to work on it and understandable.

Since we want to create v2 of our shop website in close future and i still remember my "code nightmares" using the programmatic approach. #915 Had some upvotes though, inside the comments and its almost identical ticket. Instead of breadcrumb just example with other menus.
