### ISSUE TITLE
DataTable: not having the keyboard focus on filter input field inside column header

### ISSUE THREAD

**Issue by ankitacroit09** [primefaces/primefaces#3381]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
Should have focus on Input field when filtering enable

## 3) Actual behavior
Datatable not having the keyboard focus on filter input field inside column header

## 4) Steps to reproduce
Do tab on table header

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
Is it replicatable on the showcase? otherwise we need a runnable example

**Comment by melloware** [comment]
Yes I know this issue.  If you have scrollWidth="100%" this is an issue.   What happens is all Input filters get tabindex="-1" which you can view in the browser DOM.   They do this for ScreenReader support so when tabbing for blind it will tab and scroll the columns to the ones off the screen.  

I wrote PF about this back in 2015 and this was their answer.

> Yes, if DataTable components have scrollable="true" attribute, two header is created;
> 
> original header in scrollable-header
> clone header in scrollable-body
>
> originalheader has tabindex=-1 and clone header has tabindex=0 on Datatable with scrollWidth attribute. When you focus to next clone header from a clone header with tab key, the body of Datatable scrolls to the right and you can see next header and its data. But, we changed tabindex=-1 for screenreader and keyboard navigation in original header. We removed it on PF5.3.3, 5.2.16 and 5.4. Only clone headers have tabindex=0. You can see this change on PF-5.3.3. Github issue; https://github.com/primefaces/primefaces/issues/636

JS Fix:

This fix if you run will find all those filters and give them a tabindex so it works like when you don't use scrollWidth="100%" however you will lose the ScreenReader ability mentioned above.

```javascript
      /**
       * When using scrollWidth="100%" on a PF datatable it makes all filters tabindex="-1" so they are not tabbable.
       * This is done for ARIA/ScreenReader requirements when a blind user is tabbing that it will tab the columns to
       * the right that are scrolled off the screen.  PF creates two cloned headers when scrollWidth="100%", but this
       * fix finds all of the filters and sets their tabindex=2001, 2002 etc.  
       */
      fixScrollableFilters: function(){
         $(':input[tabindex=-1]').each(function(i) {
            $(this).attr('tabindex', 2000+i);
        });
      },
```

**Comment by melloware** [comment]
But basically if you have filters you can't tab between them as the column headers get the tabbing.

**Comment by melloware** [comment]
I have posted a workaround to this issue as I don't think PF core is going to fix it.

**Comment by melloware** [comment]
Closing as a workaround is provided and PrimeTek will probably not fix this as it is done on purpose to meet other requirements.
