### ISSUE TITLE
[Documentation] Remove autoUpdate attributes

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3383]
was replaced by p:autoUpdate

**Comment by kito99** [comment]
This component should be added to the showcase should as well.

**Comment by tandraschko** [comment]
@kito99 it would be great if you could use the showcase issuetracker for this - and it would be very great if you could provide a PR.

**Comment by kito99** [comment]
OK. Added https://github.com/primefaces/showcase/issues/81. Not sure about a PR but I will if possible.
