### ISSUE TITLE
Include license information in pom.xml

### ISSUE THREAD

**Issue by reitzmichnicht** [primefaces/primefaces#3389]
## 1) Environment
- PrimeFaces version:
6.1.14

## 2) Expected behavior
pom.xml contains license information

In the distribution download, please add the following to tag/pom.xml

```
    <licenses>
        <license>
            <name>PrimeFaces Commercial License, Version 1.0</name>
            <url>https://www.primefaces.org/store/elite-license.xhtml</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
```

This helps a lot when working with license checking plugins.

**Comment by tandraschko** [comment]
@mertsincan / @cagataycivici Could you do this for elite? I will clseo this ticket for now as it's not related to the community version here.
