### ISSUE TITLE
menu: disappearing fast issue in mozilla

### ISSUE THREAD

**Issue by ravindra1512** [primefaces/primefaces#339]
primefaces submenu are disappearing fast when i am putting cursor on menu.
but same menu's not disappearing in chrome and IE. 
let me know what will be the work around for the same. 
for e.g 
http://www.primefaces.org/showcase/ui/menu/menubar.xhtml

check the issue for edit menu in above link - mozilla

**Comment by lagar84** [comment]
This issue is problably theme dependent, in Aristo its easier to reproduce.
Put mouse cursor on "File", it will show submenu (new, open, quit) - then SLOWLY move mouse to submenu, since there is a small space between "File" and submenu, the submenu will hide before you have the chance to select anything.
(reproduced in firefox 38.0.5 on windows 8.1 http://www.primefaces.org/showcase/ui/menu/menubar.xhtml)

**Comment by cagataycivici** [comment]
I can't replicate, please create a screencast and post a video link.

**Comment by lagar84** [comment]
Here is a short video reproducing the problem: https://youtu.be/wPz9V3Q6p7c

**Comment by lagar84** [comment]
It is possible to workaround this issue with some CSS:
.ui-menubar > .ui-menu-list > .ui-menu-parent > .ui-menu-child {
    top: 25px !important;
}
This value (25px) needs some tweaking depending on the used theme and height of the menubar

**Comment by cagataycivici** [comment]
Thanks, we'll check.

**Comment by tandraschko** [comment]
Does it still occur with the current showcase?

**Comment by lagar84** [comment]
Yes, still occurs in current showcase
(Running PrimeFaces-6.0.14 on Mojarra-2.2.8 - Omega Theme)
Firefox 51.0.1 (32-bit)

Google Chrome still working fine

**Comment by melloware** [comment]
@lagar84 Does this still happen on the current Showcase?  

I am using Firefox Quantum 62.0 and I can't reproduce your issue against the latest showcase.

**Comment by lagar84** [comment]
@melloware  I am also on Firefox Quantum 62 (windows 7) and can't reproduce the problem anymore on current showcase. Also tested on Chrome and IE11. 
Looks like it is safe to close this issue.

**Comment by melloware** [comment]
Agreed thanks for checking. @Rapster can you close please?

**Comment by Rapster** [comment]
Thanks guys 😉
