### ISSUE TITLE
PrimeFaces.current() needs to be Mockable for unit tests

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#3390]
The old RequestContext for unit testing we could do the following:

```java
RequestContext requestContext = Mockito.mock(RequestContext.class);
RequestContext.setCurrentInstance(requestContext, facesContext);
```
So we could verify that things like addCallBackParam were called with..

```java
Mockito.verify(requestContext).addCallbackParam("businessValidationFailed", true);
```

The PrimeFaces.current() static class needs soemthing similar to be able to do something like...

```java
PrimeFaces primefaces= Mockito.mock(PrimeFaces.class);
PrimeFaces.setCurrentInstance(primefaces);
```

**Comment by tandraschko** [comment]
ideas welcome ;)

**Comment by melloware** [comment]
I will submit a PR!

**Comment by melloware** [comment]
This was not as easy as I thought but here is what I came up with that works.  Since I use CDI this made it a lot easier.

1. Produce PrimeFaces.current() from a provider like...
```java
public class PrimeFacesProvider {

   /**
    * The PrimeFaces context for injection.
    * @return the static PrimeFaces but is injectable
    */
   @Produces
   public PrimeFaces getPrimeFaces() {
      return PrimeFaces.current();
   }
}
```

2. Never reference PrimeFaces.current() statically always Inject it like the following code...
```java
@RequestScoped
public class FacesFeedback implements Feedback {

   @Inject
   PrimeFaces primeFaces;

   protected void setBusinessValidationFailedFlag() {
      // provide a flag for ajax events to key on for general business
      // validation failures
      primeFaces.ajax().addCallbackParam(BUSINESS_VALIDATION_FAILED, true);
   }
}
```

3. Unit test you can Mock PrimeFaces and Ajax and verify the call.
```java
 private static final class Mocking {
      @InjectMocks
      final FacesFeedback feedback = new FacesFeedback();
      @Mock
      PrimeFaces primeFaces;
      @Mock
      Ajax ajax;
      

      public Mocking() {
         MockitoAnnotations.initMocks(this);
         
         when(primeFaces.ajax()).thenReturn(ajax);
      }
   }

public void testValidationMessageNoSummary() {
      // Arrange
      final Mocking m = new Mocking();

      // Act
      m.feedback.validationMessage("fieldname", "validation detail");

      // Assert
      verify(m.ajax).addCallbackParam("businessValidationFailed", true);
   }
```

**Comment by tandraschko** [comment]
I would probably use @ApplicationScoped or min. @RequestScoped for the producer ;)

**Comment by melloware** [comment]
Good call @RequestScoped will force it to be reinjected into @SessionScoped or @ApplicationScoped beans.  I feel like that is safer.

**Comment by tandraschko** [comment]
Yep, also it won't get serialized. @Dependent is sometimes tricky as default scope.

**Comment by melloware** [comment]
@tandraschko Found one issue while trying to now run my app.  

```
WELD-001436: Type org.primefaces.PrimeFaces is not proxyable because it has a private constructor private org.primefaces.PrimeFaces() - Producer Method [PrimeFaces] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @RequestScoped public com.xxx.web.provider.PrimeFacesProvider.getPrimeFaces()].
```

Because it has no public empty constructor it can't be proxied. Any thoughts?

**Comment by tandraschko** [comment]
Yep, of course. The problem will also occur with @Dependent and serialization of course.
Could try to add a protected default constructor? If yes, we should add them for 6.3

**Comment by melloware** [comment]
Let me try that.

**Comment by melloware** [comment]
That works.

**Comment by BenHunt-io** [comment]
Awesome guys! 

My team is trying to migrate to Junit5, yet static methods keep pulling us back to Junit4 for PowerMock. Not only was it not testable, it wasn't a clear dependency of the class. But with using the producer method and CDI, it's clear that whatever class is using PrimeFaces.current is dependent upon it.

Now we can use Junit5 :)

**Comment by melloware** [comment]
Glad it helped!
