### ISSUE TITLE
DataTable: new responsive mode

### ISSUE THREAD

**Issue by gallegote** [primefaces/primefaces#3396]
## 1) Environment
- PrimeFaces version:  Primefaces 6.2

## 2) Expected behavior

Add a new responsive mode to the DataTable component, so that it works in a similar way to the jquery plugin [datatables](https://datatables.net/)

This mode is a mixture of the two responsive modes of primefaces. Only columns that are hidden by priority are displayed in reflow mode

![step1](https://user-images.githubusercontent.com/11761767/36876994-32485a5c-1db8-11e8-9efa-495c81433941.png)

![step2](https://user-images.githubusercontent.com/11761767/36876995-32643ed4-1db8-11e8-8072-b5c4b9cc8bc9.png)

![step3](https://user-images.githubusercontent.com/11761767/36876996-327ff87c-1db8-11e8-90c8-31512a48259c.png)

**Comment by tandraschko** [comment]
Probably this will only be done if you sponsor it via PrimeFaces PRO.

**Comment by melloware** [comment]
PrimeTek has removed support for "responsive" mode in other Prime Libraries so i doubt this would be supported even with a PRO request.  See: https://github.com/primefaces/primeng/issues/12047
