### ISSUE TITLE
Calendar: continuous min/max time validation

### ISSUE THREAD

**Issue by svrolanski** [primefaces/primefaces#340]
I'm using calendar to choose time to schedule a job in Quartz.
I'm trying to restrict the time to be out of regular work time.
Thing such as this, doesn't work:

```
<p:calendar showOn="button" mask="true" timeOnly="true" minHour="18" maxHour="7"/>
```

Min/Max time input should be considered as a timeframe in the day.

**Comment by cagataycivici** [comment]
I tried minHour and maxHour, it worked in my case.

**Comment by svrolanski** [comment]
It works if you use something like:
    minHour="7" maxHour="18"
but not:
    minHour="18" maxHour="7"

The funny thing is that you closed it without even seeing my reply....

**Comment by cagataycivici** [comment]
Can you provide a patch?

**Comment by cagataycivici** [comment]
@mertsincan Please take a look at this.

**Comment by mertsincan** [comment]
Do you get a JS error on browser console?

**Comment by christophs78** [comment]
@tandraschko : This issue suggest to allow not only one min/max-range. 
Something like rangeA = 00:00 - 07:00, rangeB == 18:00 - 23:59. This is something DatePicker can´t do too. We may close this issue and open an new one which suggests do add multiple min/max-ranges to DatePicker. Whoever build´s this feature...
