### ISSUE TITLE
ComponentUtils.getHrefURL: lack of encoding

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3409]
As already mentioned in [this](https://github.com/primefaces/primefaces/commit/41fd99e3375227ccda3c4559c64dda26fa02b82a) commit comment parameter keys are not encoded. This may lead to HTTP parameter pollution. 

~~Fragments are also not encoded.~~ See comment [below](https://github.com/primefaces/primefaces/issues/3409#issuecomment-370339135)

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3410

**Comment by cnsgithub** [comment]
@jasonex7 Your method seems to assume that the `baseUrl `already is correctly encoded in all parts: paths, parameters, fragment. Is that correct? Then we should make it a convention in javadoc or maybe annotate the `baseUrl `parameter with `@Encoded` (borrow from `javax.ws.rs`?) to avoid double encoding. What do you think?

**Comment by jasonex7** [comment]
@cnsgithub I encode only the values of OutcomeTarget.getParams() because the original request had only EL in value attribute, but it's good that param key was also encoded. Thanks for the observation and commit.

**Comment by cnsgithub** [comment]
@jasonex7 Ok. However, as getHrefURL is located in ComponentUtils, you have to expect it to be used in other locations as well in future.
