### ISSUE TITLE
paginator.js improve performance on pageCount very high

### ISSUE THREAD

**Issue by michelepra** [primefaces/primefaces#341]
it makes no sense to recreate all options any time i reque a page

https://code.google.com/p/primefaces/source/browse/primefaces/trunk/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js?r=12491#196

from row 196 i suggest change this code

```
    if(this.jtpSelect.length > 0) {
        this.jtpSelect.children().remove();

        for(var i=0; i < this.cfg.pageCount; i++) {
            this.jtpSelect.append("<option value=" + i + ">" + (i + 1) + "</option>");
        }
        this.jtpSelect.children('option[value=' + (this.cfg.page) + ']').prop('selected','selected');
    }
```

to this

```
if (this.jtpSelect.length > 0) {
    var
    self = this,
    children = $(this.jtpSelect[0]).children();
    if (children.length < this.cfg.pageCount) {
        var newOpt = [];
        for (var b = children.length + 1; b < this.cfg.pageCount; b++) {
            newOpt.push('<option value="', b, '">', ( b + 1 ), '</option>');
        }
        children = this.jtpSelect.append(newOpt.join("")).children();
        newOpt = null; //GC free ram!!
    }

    this.jtpSelect.each(function(){
        var children = $(this).children();
        children.slice(0, self.cfg.pageCount).show();
        children.slice(self.cfg.pageCount).hide();
    });
    this.jtpSelect.attr("value", this.cfg.page)
}
```

**Comment by cagataycivici** [comment]
I don't see much difference and performance gain. You still create new elements.

**Comment by michelepra** [comment]
the performance gain is only when pageCount is very high, the performance in normal use is the same.
I have one customer that use dataTable in lazy mode and pageCount is more than 100000, paginated by 15 row. Every time he change page of dataTable browser freeze because the code of primefaces paginator remove and recreate option every time receiving data of new page.

New element that i create was create only when is necessary, not every time. Please regard real and extreme usage case of this code (worse case?)
