### ISSUE TITLE
Diagram: allow synchronization of elements to the server

### ISSUE THREAD

**Issue by brunoaandrade** [primefaces/primefaces#3411]
## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
 After moving the elements in a p:diagram, there position should be updated.
 when a p:commandButton is pressed, the position of the elements are the same.

## 3) Actual behavior
 Diagram elements have always the same position in bean.

## 4) Steps to reproduce
Exemple https://www.primefaces.org/showcase/ui/data/diagram/basic.xhtml

## 5) Sample XHTML
```
<p:diagram  id="diagram" value="#{wfEngineBuilderBean.model}" var="el"  style="height:600px;border:none;" styleClass="ui-widget-content ui-create-diagram">
        <f:facet name="element">
                <h:outputText value="#{el.getCCode()}" style="cursor: default"/>
        </f:facet>
</p:diagram>
<p:commandButton process="@this, diagram" value="Guardar" styleClass="ui-button-yes" icon="fa fa-floppy-o" action="#{wfEngineBuilderBean.save}"   
..
```

## 6) Sample bean
```
public void save()
{
         for (Element element: model.getElements())
         {
                element.getX();
                element.getY()
          }
}
```

## ) Other exemple
https://forum.primefaces.org/viewtopic.php?p=155138

**Comment by tandraschko** [comment]
AFAICS there is no way to syncrhonize the position to the server, so thats an new feature for me.

**Comment by tandraschko** [comment]
If you would like to provide a PR, let me know so i can give you some tips how it's implement in other components.
Otherwise, you can also sponsor it via PrimeFaces PRO.

**Comment by scottmutchler** [comment]
I would like to fund this feature.  How do I make this happen?

**Comment by tandraschko** [comment]
https://www.primefaces.org/support/

**Comment by fanste** [comment]
PR #5197
