### ISSUE TITLE
Inverted DataScroller

### ISSUE THREAD

**Issue by fkjaekel** [primefaces/primefaces#342]
Hi,

I still consider issue [6798](https://code.google.com/p/primefaces/issues/detail?id=6798) from Google Code relevant:

> It would be very useful to have something like a "direction" attribute, with values bottom and top.
> 
> Bottom would be the default component behavior. If "top" is informed, the scrollbar would start in the end (last value fetched), new values would be fetched when it the scroll reaches the top (scrollTop() == 0), and data would be inserted in the begin instead of appended.
> 
> An use case example are chat applications: load the latest messages and load older ones in case the user scrolls top.

Thanks

**Comment by ghost** [comment]
We face the same issue than you @fkjaekel. I'm trying to use the dataScroller in a Comment dialog where the dataScroller should start at the bottom with the most recent comments and then as the user scrolls to the top, it should fetch more items from the server.

I'm looking for a pure Javascript - Primefaces-RemoteCommand solution at the moment.

Having an attribute that allows us to define where the new data should be fetched from (top or bottom), then it would make the dataScroller a perfect component for this use case.

@fkjaekel have you found any work around?

**Comment by fkjaekel** [comment]
I had to implement it using pure JS + RemoteCommand

**Comment by Michel0001** [comment]
Implements only with inline mode
diff patch based on commit (b351710de6) Primefaces 6.2 RC2

[datascroller-reverse.diff.txt](https://github.com/primefaces/primefaces/files/1932712/datascroller-reverse.diff.txt)

**Comment by melloware** [comment]
Looks like "startAtBottom" is added but only works if virtualScroll="true".  https://github.com/primefaces/primefaces/issues/4996

**Comment by mertsincan** [comment]
@melloware Fixed now ;)

For this issue, please use startAtBottom="true".

Best Regards,
