### ISSUE TITLE
URL for push notifications does not contains contextPath

### ISSUE THREAD

**Issue by sentinalll** [primefaces/primefaces#3422]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? Yes. 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: JBoss EAP 7.0.8.GA
--
- Affected browsers:
Google Chrome 64.0.3282.186 (Official Build) (64-bit)
## 2) Expected behavior

URL to send push notification contains contextPath
(http://localhost:8180/myapp/primepush/update?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.3-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1520355199853)
...

## 3) Actual behavior

Websocket failed on first connection attempt. Downgrading to long-polling and resending

socket.js.xhtml?ln=primefaces&v=6.2:1 GET http://localhost:8180/primepush/update?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.3-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1520355199853 404 (Not Found)
..

## 4) Steps to reproduce
Use <p:socket/> component to subscribe
.. 

## 5) Sample XHTML

  <h:outputScript>
      function handleMessage(data) {
       console.log(data);
      }
    </h:outputScript>

    <p:socket onMessage="handleMessage"
              channel="/update"
              transport="websocket"
              fallbackTransport="long-polling"
              widgetVar="socket_var"/>

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
Sorry but PrimePush was already deprecated in 6.2 and removed in master already.
As this issue tracker belongs to the community version, i will just close it.
However, you can set the url via web.xml (should be mentioned in user guide) and if you are PRO/Elite user, i think you can get a fix in the next elite version.

**Comment by PlassJ** [comment]
I am struggling with the same Problem.
Should this be fixed with 6.2.1 ?

**Comment by tandraschko** [comment]
@mertsincan Would you like to check it this for elite?

**Comment by PlassJ** [comment]
I think i have tracked down the problem to the SocketRenderer.
In PF 6.1.15: 
String url = getResourceURL(context, channelUrl);
In PF 6.2.1:
String url = channelUrl;

I changed it back to getResourceURL and everything works as expected.
unfortunately i don't have a clue on how to provide a PR for an not exsisting resource ...

**Comment by tandraschko** [comment]
getResourceUrl is fine if you are not on JSF 2.3. You can't provide a PR but the info should be info to fix it if @mertsincan would like to do.
But you can easily overwrite the renderer in your project.

**Comment by PlassJ** [comment]
Already fixed it, as we maintain our own littel PF branch ;-)

**Comment by mertsincan** [comment]
Fixed for 6.2.8.
