### ISSUE TITLE
Calendar: Popup positioning when overflow-y: auto

### ISSUE THREAD

**Issue by JHookDev** [primefaces/primefaces#3423]
## 1) Environment
- PrimeFaces version: 6.1.13 and 6.2
- Does it work on the newest released PrimeFaces version? No Version? 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7.0.23
- Affected browsers: Chrome, Firefox, IE and Edge

## 2) Expected behavior
The Calendar popup should stay attached to the Calandar input text component when scrolling up or down. Having an appendTo attribute to attach the Calendar popup to the input text component like done with the selectOneMenu could help alleviate this issue.

## 3) Actual behavior
The Calendar popup remains in it's rendered position on the screen, when the rest of the content scrolls up and down as expected.

## 4) Steps to reproduce
Open pfCalendar.xhtml and click 'Open Overflow Modal Panel' button. On dialog presentation the Calendar popup will display, then scroll up or down to see the calendar widget stays in place and does not move with the dialog contents.

## 5) Sample XHTML
Please see attached files:
pfCalendar.xhtml
testPfacesOverflow.xhtml

## 6) Sample bean
Please see attached files:
OverflowTestBean.java
OverFlowTestPojo.java

[Calendar scrolling issue - sample code.zip](https://github.com/primefaces/primefaces/files/1786250/Calendar.scrolling.issue.-.sample.code.zip)

**Comment by melloware** [comment]
@JHookDev Can you check if this is a duplicate of https://github.com/primefaces/primefaces/issues/3545 and close if so?

**Comment by JHookDev** [comment]
@melloware The 2 issues appear to be different. The issue here is that the date selection popup for the calendar does not stay attached to the calendar input box when you scroll the modal panel contents. Where #3545 appears to be referring to the Calendar popup is rendered partly off the view when the calendar component is at the bottom of the view. 3545 also has a scrollable main view where this issue does not.

**Comment by melloware** [comment]
Understood. Thanks for checking!

**Comment by melloware** [comment]
@JHookDev  Using your code above I created this attached test case:
[pf-3423.zip](https://github.com/primefaces/primefaces/files/2714987/pf-3423.zip)

When the pom.xml is set to PF 6.2 I can verify the behavior you reported.  When switching to 6.3-SNAPSHOT the behavior is different.  As soon as you begin to scroll the dialog the Calendar is closed.  To me this is much better behavior and correct behavior because once you start scrolling you have "left the calendar control".

TO run this just run "mvn clean jetty:run" and navigate to http://localhost:8080/primefaces-test/pfCalendar.xhtml

You must first build PF 6.3-SNAPSHOT ..

```
git clone https://github.com/primefaces/primefaces.git
cd primefaces
mvn clean install
```

**Comment by melloware** [comment]
@tandraschko Can you review this and mark it 6.3 and close it?

**Comment by JHookDev** [comment]
@melloware Thanks for the follow-up! I agree that is better behavior.

**Comment by adjiandov** [comment]
For me as I have to stay on 6.2.2, is there any method I can override in order to have the same outcome as in 6.3? Thank you
