### ISSUE TITLE
FileUpload: add event when all files are uploaded

### ISSUE THREAD

**Issue by classicPintus** [primefaces/primefaces#3424]
# Need to understand when all uploads are completed.

I've a p:fileUpload used in order to upload images with the attribute "multiple" set to true. 
Every file upload triggers the update of a p:dataTable that shows to the user the preview of the uploaded images.
When several images are uploaded at the same time, the p:dataTable is updated for every uploaded image, but this approach makes the user experience a little bit slow because the user see the p:dataTable updating multiple times.
The need is to update the p:dataTable only when all the uploads are completed.

## 1) Environment
- PrimeFaces version: 6.2
- Payara 174
- It's happening on all the browsers

## 2) Expected behavior
- The proposal is to make possible to trigger the update of the p:dataTable only when all the uploads are completed.

## 3) Actual behavior
Currently the update is triggered for every completed upload. That's working just fine, but reduce the speed and makes not optimal the user experience.

## 4) Sample XHTML
```
<p:fileUpload multiple="true" update="myTable" fileUploadListener="#{myBean.handleFileUploadOnAddAdvertising}" ... ... />
<p:dataTable id="myTable" ... ... />
```

## 5) Sample bean
```
public void handleFileUploadOnAddAdvertising(FileUploadEvent event) throws IOException {
        // update logic
}
```

**Comment by tandraschko** [comment]
Probably this need a bit of redesign the component event handling and ajax handling.
Currently all update/process stuff is available as direct attribute but fileUpload should then support multiple p:ajax events.
As it's quite a lot of work, it would be great if you could sponsor it via PrimeFaces PRO or provide a PR.

**Comment by mstichweh** [comment]
In the meantime it would be very nice to just have the `data` object as additional parameter in the `onAdd` function:

```
fileupload.js:
...
if($this.cfg.onAdd) {
    $this.cfg.onAdd.call($this, file, function(processedFile) {
        file = processedFile;
        data.files[0] = processedFile;
        this.addFileToRow(file, data);
    }, data);
}
...
```

Then it would be possible to access `data.originalFiles.length` to get the number of uploading files, especially for multiple uploads with auto upload enabled. This value could be transfered to the backing bean by `remoteCommand` then.
To decrement the number of uploading files, when the user cancels the upload of a single file during the upload process, a `remoteCommand` can be used, which is triggered via an additional jQuery click event on the cancel button. Registering of this event can also be done in the `onAdd` JavaScript function. 

This could be an example implementation tracking the total number of uploading files to check in upload handler method if all are uploaded:

```
<p:fileUpload fileUploadListener="#{bean.handleUpload}" onAdd="onAdd" multiple="true" auto="true" mode="advanced" />
<p:remoteCommand name="remoteCommandSetFilesCount" actionListener="#{bean.setFilesCount}" process="@this" update="@none" />
<script>						 
function onAdd(file, processedFileFunc, data) {
	processedFileFunc.call(this, file);
        var isFirstFile = data.originalFiles.length > 0 && data.originalFiles[0].name === file.name;
	if(isFirstFile) {
		remoteCommandSetFilesCount([{name:'filesCount', value:data.originalFiles.length}]);
	}
	$(document).off('click.filescount', this.rowCancelActionSelector)
			.on('click.filescount', this.rowCancelActionSelector, null, function(e) {
                                $(this).off('click.fileupload');
				remoteCommandSetFilesCount([{name:'filesCount', value:-1}]);
			});
		}
	}
}
</script>


Bean.java:
...
public void setFilesCount() {
	int filesCount = Integer.parseInt( FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("filesCount"));
	if(this.totalFiles == null) {
		this.totalFiles = filesCount;
                this.uploadedFiles = 0;
	} else {
		this.totalFiles += filesCount;
	}
}

public void handleUpload(FileUploadEvent event)
{
	this.uploadedFiles++;
	if(this.uploadedFiles == this.totalFiles)
	{
		System.out.println("All files uploaded");
	}
}
...
```

Currently, without the `data` parameter, the `Fileupload` widget must be overridden to get access to `data`, which is not a good solution:

```
PrimeFaces.widget.FileUpload.prototype.addFileToRow = (function() {
	var prototypeFunc = PrimeFaces.widget.FileUpload.prototype.addFileToRow;
	return function() {
		var file = arguments[0];
		var data = arguments[1];
		var isFirstFile = data.originalFiles.length > 0 && data.originalFiles[0].name === file.name;
		if(isFirstFile) {
			remoteCommandSetFilesCount([{name:'filesCount', value:data.originalFiles.length}]);
		}
		prototypeFunc.apply(this, arguments);
	};
})();
```

Providing the `data` object to the `onAdd` method gives more flexibility extending the uploader. It is even a nice feature aside from the allUploadedComplete event.

**Comment by tandraschko** [comment]
I checked this issue now and its quite hard to implement.
1) We could either add a new event which will be called when all uploads are done (that would be another request)
or
2) We could pass the files count and current uploaded file index to the FileUpload event

the 2) would be the better option probably.

Another option (which doesnt fix this direclty) would be to allow to upload multiple files in one request like in simple mode, you can catch the UploadedFilesEvent instead of a single UploadedFileEvent.
To enable this, we have to set singleFileUploads of the jquery widget.
Probably we would then also need to add limitMultiFileUploads and limitMultiFileUploadSize option.

**Comment by tandraschko** [comment]
duplicate; we will add 2) in #7390
