### ISSUE TITLE
Add resetAxesOnResize option for Responsive Charts

### ISSUE THREAD

**Issue by codingPF** [primefaces/primefaces#343]
Take the Area Chart showcase and make it responsive. Than change the model to have a low number in 2008 (e.g. 15 boys & 80 girls). Run the chart and resize the browser window. YAxis scale changed and it starts on a negative number.
Tomee 1.7.2 PF 5.2 FF38

**Comment by codingPF** [comment]
I tracked this down to the makeResponsive method which is resetting the scale of the axis and passing control to jqplot. 
Jqplot says: …to reset all axes min, max, numberTicks and tickInterval setting so axes will rescale themselves...
In my example this looks funny because my graph cannot have negative numbers but jqplot seems to set a new min() value which is negative.

I solved the issue for my usecase by turning of the rescale option using overwrite. This works fine for me since I only need the chart to be resized rather than rescaled.

PrimeFaces.widget.Chart.prototype.makeResponsive= function() {
    var $this = this,
    resizeNS = 'resize.' + this.id; 
    $(window).off(resizeNS).on(resizeNS, function() {
        $this.plot.replot({resetAxes: false});
        }
    });
}

Maybe it makes sense to pass second attribute to the chart tag in order to control this feature? Something like…
<p:chart type="line" responsive="true" responsiveRescale=”false” model="#{view.areaModel}" />

**Comment by codingPF** [comment]
I tracked this down to the makeResponsive method which is resetting the scale of the axis and passing control to jqplot. 
Jqplot says: …to reset all axes min, max, numberTicks and tickInterval setting so axes will rescale themselves...
In my example this looks funny because my graph cannot have negative numbers but jqplot seems to set a new min() value which is negative.

I solved the issue for my use case by turning of the rescale option using overwrite. This works fine for me since I only need the chart to be resized rather than rescaled.

PrimeFaces.widget.Chart.prototype.makeResponsive= function() {
    var $this = this,
    resizeNS = 'resize.' + this.id;

```
$(window).off(resizeNS).on(resizeNS, function() {
    $this.plot.replot({resetAxes: false});
    }
});
```

}

Maybe it makes sense to pass second attribute to the chart tag in order to control this feature? Something like…
<p:chart type="line" responsive="true" responsiveRescale=”false” model="#{view.areaModel}" />

**Comment by cagataycivici** [comment]
So you need it with resetAxes:false ? Do you see any problems with it. Without it, some charts are broken, not sure about bar chart. I guess we can make an attribute for this to make it configurable.

**Comment by codingPF** [comment]
I tried the first 5 showcases (animate/are/bar/bubble/combined) without any negative impcat. Behaviour as expected after the change.
Using IE10 & FF38

**Comment by cagataycivici** [comment]
Ok, thanks.
