### ISSUE TITLE
Various potential DOM XSS vulnerabilities

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3434]
## 1) Environment
- PrimeFaces version: 6.3-snapshot
- Does it work on the newest released PrimeFaces version? Version? 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) yes
- Application server + version: n/a
- Affected browsers:n/a

## 2) Expected behavior
DOM XSS prevention, see https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet

## 3) Actual behavior
Found various locations that are missing escaping and are potentially subject to DOM XSS.
- [x] ~~signature.js, lines 72 and 81~~
- [x] forms.multiselectlistbox.js, line 63 and 118
- [x] forms.selectcheckboxmenu.js, line 876
- [x] forms.password.js, line 38
- [x] ~~0-timeline.js, lines 1912 and 1927~~ _(could not be tested as there is no example on how to use timeline groups; may be a bug in [chap-links-library](https://almende.github.io/chap-links-library/) which is no longer developed)_
- [x] ~~contentflow.js, line 371~~ _(could not be reproduced, probably not reachable from PF; may be a bug in [external lib](http://www.jacksasylum.eu/ContentFlow) which is no longer developed)_

**Comment by tandraschko** [comment]
Mr Security never stops :D

**Comment by cnsgithub** [comment]
@tandraschko I wonder if there is an example on how to use timeline groups. Neither the showcase nor the extensions mentioned in 6.2 user guide seem to contain one.

> Examples
> For examples on editing, grouping, styling, ranges, linked timelines and lazy loading please visit;
> 541
> PrimeFaces User Guide
> http://www.primefaces.org/showcase-ext/sections/timeline/basic.jsf

**Comment by tandraschko** [comment]
Don't know. There were many more examples of the timeline available in the extensions showcase. Maybe someone can port them.

**Comment by cnsgithub** [comment]
From the coding perspective it's also not clear how to use it:

![image](https://user-images.githubusercontent.com/13161711/37092842-93c52324-220d-11e8-9551-3e22b72fdf30.png)

**Comment by tandraschko** [comment]
Don't ask me :D never used it and the component was developed by Oleg. As i said, the only good source are the old examples int he extensions showcase.

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3440
