### ISSUE TITLE
Refactor hide/leave logic on dynamic overlays

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3435]
currently it's implemented several times almost the same.

**Comment by Charriu83** [comment]
Hi,
are there hints, that the problem is back again with Primefaces 10.06 and 11.0.9? I have some auto completes where the suggestion panel disappear when the user tries to drag the scrollbar. Sounds like #3431, which leads me here.

**Comment by melloware** [comment]
> Hi, are there hints, that the problem is back again with Primefaces 10.06 and 11.0.9? I have some auto completes where the suggestion panel disappear when the user tries to drag the scrollbar. Sounds like #3431, which leads me here.

@Charriu83 if its this issue I believe what you are seeing is the correct behavior: https://github.com/primefaces/primefaces/issues/8726

If you scroll the window with an overlay open it should close, and not scroll with the window.

**Comment by Charriu83** [comment]
@melloware 
Sorry, this was a little bit unclear: I have some auto completes where the suggestion panel disappear when the user tries to drag the scrollbar **of the suggestion panels**. It's more like #3431, but good to here from #8726. Somes users already mentioned that too.

**Comment by melloware** [comment]
Hmmm OK can you put together a PrimeFaces Test reproducer using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.

**Comment by iki-hacon** [comment]
@melloware I have reproduced the bug in the Test project: #9481
