### ISSUE TITLE
Treetable: Checkbox Selection Unselect Problem

### ISSUE THREAD

**Issue by ckirbas** [primefaces/primefaces#3439]
## 1) Environment
- PrimeFaces version: 6.1.14
- Application server + version: wildfly 9.0.2
- Affected browsers: All

## 2) Expected behavior

<p:treeTable .... selection="#{myBean.selectedNodes}" ..>
</p:treeTable>

MyBean#
	public void setSelectedNodes(TreeNode[] selectedNodes) {
		this.selectedNodes = selectedNodes;
	}

setSelectedNodes method must be invoked when user selects/unselects a row or rows.

## 3) Actual behavior

setSelectedNodes method is not invoked when user unselects a row or rows.

if I add this event to treetable
<p:ajax event="unselect" listener="#{myBean.onNodeUnselect}" update=":messages"/> and in bean this method with empty body
    public void onNodeUnselect(NodeUnselectEvent event) {
    }

then setSelectedNodes method is invoked when user unselects a row or rows.

**Comment by tandraschko** [comment]
Please read our issue template again and edit your issue.

**Comment by tandraschko** [comment]
Will close it for now, you can still create a new issue if you respect our issue template.
