### ISSUE TITLE
AutoComplete: Item selection on focusout

### ISSUE THREAD

**Issue by codingPF** [primefaces/primefaces#344]
Item is only selected with a click on the result item - not by just typing the text (which exactly matches the result) and just leaving the filed / leaving focus.

Reproducing the issue:

- Change AutoCompleteView line 64 to: if(skin.getName().toLowerCase().startsWith(query.toLowerCase())) {

- /ui/input/autoComplete.xhtml

- Type Afterdark into the "Pojo" autocomplete - do not leave the box (no enter/no tab/no selecting by mouse); Just leave focus by clicking somewhere on the screen

- Press Submitt > Conversion error (internally the ID exchange did not happen)

**Comment by cagataycivici** [comment]
I don't understand anything, please edit your description with a clear one.

**Comment by melloware** [comment]
PR submitted. If you have autoSelection="false" the TAB key will work like normal and not select the item.
