### ISSUE TITLE
Allow own jQuery script file via ContextParam

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3442]
I would like to suggest a new ContextParam which allows to include a self maintained jQuery version to the site instead of bundling it with PrimeFaces. 

This can be useful if MOVE_SCRIPTS_TO_BOTTOM is used, as currently this parameter will also move jQuery to bottom - which causes other non primefaces related scripts which rely on jQuery to fail during page load.

It would also allow to update the jQuery if a new version is released, without having to touch the PrimeFaces Jar.

The context param could be something like  BUNDLE_JQUERY <true|false>. Then the developer has to make sure that a compatible jQuery version is added to the site at a proper spot.

BTW: The documentation of PF 6.2 has a deprecated information:

> 5. Javascript API PrimeFaces renders unobstrusive javascript which cleanly separates behavior from the html. Client side engine is powered by jQuery version 1.8.1 which is the latest at the time of the writing.

**Comment by tandraschko** [comment]
hmm
what about modify the resources in the viewoor before it will be rendered? OmniFaces does the same.

**Comment by cnsgithub** [comment]
Well sure, but doing it directly in primefaces would be better than having to add yet another jar (omnifaces) or manually modifying the resources obviously, which just adds some overhead even if small.

**Comment by tandraschko** [comment]
Really not sure about this one.
I think it would be just a hack and a good solution (which would also provide merging of resources) would be very similar to omnifaces.

**Comment by cnsgithub** [comment]
I don't see why it would be a hack if a framework offers more flexibility to the developers without forcing them to fiddle or find a way around something just because the framework bundles something so essential as jQuery.

Actually i think the omnifaces way is the "hack". By the way - RichFaces (yes it's old of course) had this option back in their glory days.

Ultimately not having this option, makes MOVE_SCRIPTS_TO_BOTTOM not usable for my current application, as jQuery is needed early. (If you need examples i will provide them later). 

A different approach without having a way to specify own jQuery could be to only move the inline scripts to bottom, but keep the resources in the head 
e.g  MOVE_**INLINE**_SCRIPTS_TO_BOTTOM   and  MOVE_**ALL**_SCRIPTS_TO_BOTTOM

**Comment by melloware** [comment]
> It would also allow to update the jQuery if a new version is released, without having to touch the PrimeFaces Jar.

I just don't see how that is possible.  For example Jquery 3.5.0 was released and if we had this feature where a user could include their own jQuery it would have broken 19 components if you look at this PR: https://github.com/primefaces/primefaces/pull/5814/files

That would be hundreds of bug reports about PF not being compatible with 3.5.0 yet etc.  I think we have to live with the fact that PF bundles jQuery so we can absolutely ensure compatibility without new bug reports.  

Closing this ticket if someone really feels strongly about it and submits a PR to fix the issue cleverly but I don't see how we would ever get around the problem above.
