### ISSUE TITLE
Mobile: remove all CSS classes variables in templates

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3445]
See #3386 

@tandraschko I can help you with this if you want

**Comment by tandraschko** [comment]
please, yes.

**Comment by Rapster** [comment]
CarouselRenderer use a mobile CSS class for responsive mode (`MOBILE_DROPDOWN_CLASS`). Should I rename the variable and the CSS selector as well? (e.g `ui-carousel-respdropdown`)?

**Comment by tandraschko** [comment]
why not juse remove it? or is it still uses on the client side somewhere?

**Comment by Rapster** [comment]
Why are you suggesting to remove it? It can still be useful (to make it responsive as the name suggest it)

```java
protected void encodeHeader(FacesContext context, Carousel carousel) throws IOException {
...
    if (carousel.isResponsive()) {
        encodeDropDown(context, carousel, clientId + "_mobiledropdown", Carousel.MOBILE_DROPDOWN_CLASS, itemCount);
    }
...
}
```

The selector is used in css and js

**Comment by tandraschko** [comment]
"mobile" sounds for me like "PrimeFaces Mobile" :D
As you suggested then, i would rename it but i would use "ui-carousel-dropdown-responsive"

**Comment by Rapster** [comment]
Got it! :wink:
