### ISSUE TITLE
Dynamic JSF DataTable [how to assign row element as per column ].

### ISSUE THREAD

**Issue by 001Shiv** [primefaces/primefaces#3447]
//This Class Contains all Column Names
package com.pdf.exporter;
public class ColumnNames {
       private List<String> columnNamesList = new ArrayList<String>();
	public List<String> getColumnNamesList() {
		return columnNamesList;
	}
	public void setColumnNamesList(List<String> columnNamesList) {
		this.columnNamesList = columnNamesList;
	}
	public void addColumnName(String columnName) {
		columnNamesList.add(columnName);
	}
}

//This Class Contains row 
public class Row {
	private List<String> values = new ArrayList<String>();	
	public Row() {
		// TODO Auto-generated constructor stub
	}
	public List<String> getValues() {
		return values;
	}
	public void setValues(List<String> values) {
		this.values = values;
	}
	public void addValue(String value) {
		this.getValues().add(value);
	}
}

//This class contains collection of row
public class Rows {
	private List<Row> rowsList = new ArrayList<>();
	public List<Row> getRowsList() {
		return rowsList;
	}
	public void setRowsList(List<Row> rowsList) {
		this.rowsList = rowsList;
	}
	public void addRow(Row row) {
		rowsList.add(row);
	}
}

// this is my main class which i am using in xhtml page
package com.pdf.exporter;
@ManagedBean (name = "dataTableView")
@ViewScoped
public class DataTableView {
	
	private ColumnNames columnNames;
	private Rows rows;	
	private Row row;
	String jsonData = "[\r\n" + "  [\r\n" + "    \"records.products.md5Digest\",\r\n"
			+ "    \"records.occurrences.md5Digest\",\r\n" + "    
			+ "    \"api\",\r\n" + "    \"2018-02-22T14:58:01.451-05:00\",\r\n" + "    \"admin\",\r\n"
			+ "    \"api\",\r\n" + "    \"20335\",\r\n" + "    \"9738\",\r\n" + "    \"true\",\r\n"
			+ "    \"adpage\"\r\n" + "  ]\r\n" + "]";
    
    @PostConstruct
    private void postConstruct() {
        initColumnProperties();
    }
    private void initColumnProperties() {
    	String jsonElem = "";	
    	try {
			JSONArray jsonArray = new JSONArray(jsonData);
			System.out.println("Json Array lenghth : " + jsonArray.length());
			columnNames = new ColumnNames();
			rows = new Rows();
			JSONArray columnsArray = jsonArray.getJSONArray(0);
			for (int j = 0; j < 4; j++) {		
				jsonElem = columnsArray.getString(j);		
				System.out.println("+++++ Heading Name : " + jsonElem);
				columnNames.addColumnName(jsonElem);
			}
			System.out.println("Column List is "+columnNames.getColumnNamesList());
			for (int i = 1; i < jsonArray.length(); i++) { // loop to iterate array of values
				Row row = new Row();
				JSONArray valuesArray = jsonArray.getJSONArray(i);
				for (int j = 0; j < 4; j++) {
					jsonElem = valuesArray.getString(j);
					row.addValue(jsonElem);
					columnNames.addTableRowElem(jsonElem);
				}
				rows.addRow(row);
			}
		} catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}   	
    }

    public ColumnNames getColumnNames() {
		return columnNames;
	}public void setColumnNames(ColumnNames columnNames) {
		this.columnNames = columnNames;
	}public Rows getRows() {
		return rows;
	}public void setRows(Rows rows) {
		this.rows = rows;
	}public Row getRow() {
		return row;
	}public void setRow(Row row) {
		this.row = row;
	}public ArrayList<String> getRowElements() {
		return rowElements;
	}public void setRowElements(ArrayList<String> rowElements) {
		this.rowElements = rowElements;
	}
}

//this is my Xhtml page
 <p:dataTable id="table" var="rowVar" value="#{dataTableView.rows.rowsList}">
      <p:columns value="#{dataTableView.columnNames.columnNamesList}" var="column">
                <f:facet name="header">
                    <h:outputText value="#{column}"/>    
                </f:facet>
               <h:outputText value="#{rowVar.values}" /> 
       </p:columns>
</p:dataTable>
    

Please check attached output/result and written code 

Problem is Single row visible in Single column instead of one row element in one column .

![capture](https://user-images.githubusercontent.com/37171532/37137707-03016954-22cd-11e8-8965-4b38cbc33235.PNG)

**Comment by cnsgithub** [comment]
Ever heard of a MVCE? https://stackoverflow.com/help/mcve

**Comment by Rapster** [comment]
When your question starts with "How", use forum please

**Comment by tandraschko** [comment]
questions -> forum
