### ISSUE TITLE
Datatable: scrollHeight 100% not working since PF 6.2

### ISSUE THREAD

**Issue by floriandulzky** [primefaces/primefaces#3450]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: jetty / wildfly
- Affected browsers: chrome

## 2) Expected behavior
If I set the property scrollHeight="100%" the datatable height should be calculated.

## 3) Actual behavior
If I set the property scrollHeight="100%" the datatable height won't be calculated.

## 4) Steps to reproduce
set primefaces version to 6.2 (in 6.1 it works)
set datatable scrollHeight="100%" (without % scrollHeight works)

## 5) Sample XHTML
`
<p:dataTable id="testtable" value="#{datatabletest.customers}"
			var="customer" paginator="true" rows="50"
			paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
			rowsPerPageTemplate="10,50,100,200" stickyHeader="true"
			filterDelay="1000" sortBy="#{customer.firstname}"
			binding="#{datatabletest.dataTable}" scrollHeight="100%" scrollable="true" style="height: 100%;">
			<p:column headerText="Firstname" filterBy="#{customer.firstname}">
				<h:outputText value="#{customer.firstname}" />
			</p:column>
			<p:column headerText="Lastname" filterBy="#{customer.lastname}">
				<h:outputText value="#{customer.lastname}" />
			</p:column>
			<p:column>
				<p:outputPanel rendered="#{not empty customer}" required="false">
					<p:selectOneMenu value="#{customer.gender}" id="gender-select" >
						<f:selectItems value="#{datatabletest.genderList}" />
					</p:selectOneMenu>
				</p:outputPanel>
			</p:column>
		</p:dataTable>
`

## 6) Sample bean

`
@ViewScoped
@ManagedBean(name="datatabletest")
public class DatatableTestManagedBean {
	
	private LazyDataModel<Customer> lazyCustomer;

	private List<Customer> customers;
	private List<String> genderList;
	private DataTable dataTable;
	private SelectOneMenu selectOneMenu;
	
	@PostConstruct
	public void init() {
		this.customers = new ArrayList<Customer>();
		for(int i = 0; i < 150; i++) {
			this.customers.add(new Customer("Florian " + i, "D.", "Male"));
			this.customers.add(new Customer("Christian " + i, "K.", "Female"));			
		}
		this.genderList = new ArrayList<String>();
		this.genderList.add("Male");
		this.genderList.add("Female");
	}
... getters/setters
}
`

**Comment by svrolanski** [comment]
If you want to workaround in version 6.2 have the following javascript execute on pageload:

```
PrimeFaces.widget.DataTable.prototype.adjustScrollHeight = function () {
	var relativeHeight = this.jq.parent().innerHeight() * (parseInt(this.cfg.scrollHeight) / 100),
			headerChilden = this.jq.children('.ui-datatable-header'),
			footerChilden = this.jq.children('.ui-datatable-footer'),
			tableHeaderHeight = (headerChilden.length > 0) ? headerChilden.outerHeight(true) : 0,
			tableFooterHeight = (footerChilden.length > 0) ? footerChilden.outerHeight(true) : 0,
			scrollersHeight = (this.scrollHeader.outerHeight(true) + this.scrollFooter.outerHeight(true)),
			paginatorsHeight = this.paginator ? this.paginator.getContainerHeight(true) : 0,
			height = (relativeHeight - (scrollersHeight + paginatorsHeight + tableHeaderHeight + tableFooterHeight));

	if (this.cfg.virtualScroll) {
		this.scrollBody.css('max-height', height);
	} else {
		this.scrollBody.height(height);
	}
};
```

**Comment by Olafxso** [comment]
I am using primefaces 7.0 and try to set the scrollHeight to 100%. 
Here is a complete test app:
[pf-4477.zip](https://github.com/primefaces/primefaces/files/3141764/pf-4477.zip)

This is the result :
<img width="489" alt="scrollHeight100%" src="https://user-images.githubusercontent.com/29576321/57136268-90a44d00-6dac-11e9-9c63-dea589574efe.png">

When scrollHeight is set to a fixed pixel size it will get a tablebody scrollbar.
<img width="487" alt="scrollHeight200" src="https://user-images.githubusercontent.com/29576321/57136271-939f3d80-6dac-11e9-94b2-e50dc8b41e81.png">

I expect the table should take the full height of the visible rect when set the scrollHeight to 100% and get a tablebody scrollbar.

**Comment by melloware** [comment]
@tandraschko we should probably re-open this issue as its not fixed in 7.0 as its marked here.

**Comment by crocimi** [comment]
not sure if it is related but I have a very similar case and it is working after following actions:
- set 'height: 100%' for the form
- set 'height: 100%' for the dataTable

**Comment by melloware** [comment]
Yes Scrollheight is 100% of the parent container its in.   I believe this ticket is working as expected.
