### ISSUE TITLE
defaultCommand: with browser autocomplete not working together in Firefox

### ISSUE THREAD

**Issue by david0** [primefaces/primefaces#3453]
## 1) Environment
- PrimeFaces version: 6.*
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 7.0
- Affected browsers: Firefox (tested with v58)

## 2) Expected behavior
When selecting the browsers autocomplete suggestions using Enter the selected suggestion should be filled in and the `defaultCommand` should not be triggered. The next press of enter should trigger the default command.

This works as expected in in Chrome: 
![defaultcommand-chrome](https://user-images.githubusercontent.com/1685610/37148261-13b975fa-22ca-11e8-9a9e-59316d8f9342.gif)

## 3) Actual behavior

The completion is ignored (the selected value not filled in) and the characters that were typed are submitted.

![defaultcommand-firefox](https://user-images.githubusercontent.com/1685610/37148300-3cf54534-22ca-11e8-982b-b33d29f13b22.gif)

This is really annoying especially for login forms.

## 4) Steps to reproduce
Using firefox on [defaultCommand showcase](https://www.primefaces.org/showcase/ui/misc/defaultCommand.xhtml)

1. Type "name" and press enter
2. Clear the field. Type n
3. Select autocompletion suggestion by arrow keys confirming the selection with Enter

## 5) Sample XHTML & bean
https://www.primefaces.org/showcase/ui/misc/defaultCommand.xhtml

## 6) Related issues

#2448 only Chrome and Safari, which is now working like expected (see 2)

**Comment by tandraschko** [comment]
a PR or deeper analysis would be great.

**Comment by cnsgithub** [comment]
Is the intended behavior to immediately trigger the default command after pressing enter within autocomplete suggestions?

Otherwise, we could simply change `keydown `to `keypress `in `forms.defaultcommand.js`:
![image](https://user-images.githubusercontent.com/13161711/37151800-53d46764-22d7-11e8-9443-8f04d6e98fdb.png)

This would however imply that the user has to press enter twice when using an autocomplete suggestion. Tested in Chrome 65.0.3325.146 and Firefox 58.0.2.

**Comment by david0** [comment]
@cnsgithub: No, pressing twice is absolutly fine for me and seems also more intuitive to me.

I tried your solution, it works like a charm! :+1:

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3455

**Comment by melloware** [comment]
Here was the original issue why NUMPAD_ENTER was re-added. https://github.com/primefaces/primefaces/issues/2448  

Can you please review and confirm its still safe to remove?

**Comment by cnsgithub** [comment]
Re-opened https://github.com/primefaces/primefaces/pull/3455
