### ISSUE TITLE
Confirm: add precondition to dialog opening

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3454]
Related to this topic https://forum.primefaces.org/viewtopic.php?f=3&t=40408

It would be really nice to have some precondition before confirmDialog might open. This could be a new attribute set on p:confirm. My use case is the following:

I have a datatable, and a button allowing to delete the selection. Before the dialog shows up to confirm the removal, a check should be applied to make sure items have been selected (in such case a message could be displayed and dialog not showing up)

**Comment by Rapster** [comment]
Attribute could be called `if`, and after a quick analysis, it'd probably a lot easier if it was client side (and I honestly think it should be enough, but it all depends of the use case right? :-p). Saying all this, a new attribute as `requiredMessage` should come along (I'll create a ticket once this one done)

**Comment by melloware** [comment]
This has been there since 6.2 but never added to the taglib or docs!
