### ISSUE TITLE
Layout: Missing Center-pane Element Error (PF 6.1 to PF 6.2)

### ISSUE THREAD

**Issue by soufanom** [primefaces/primefaces#3457]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source ->  https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: GlassFish Server 4.1.1
- Affected browsers: ALL

## Expected behavior and Actual behavior
For p:commandbuttons with ajax=false or h:commandlinks, a refresh for full page is to take over. When we only upgraded from Primefaces version 6.1 to version 6.2, now clicking on these buttons causes the following error:
**/UI Layout Initialization Error
The center-pane element does not exist.
The center-pane is a required element.
We need to mention that when the commandbutton is clicked, we have a growl type of message to be updated.**
                <p:messages severity="error" showDetail="true" escape="false" closable="true"  style="width:800px; padding-left: 280px"><p:autoUpdate /></p:messages>
                <p:growl id="growl" severity="info, warn" showDetail="true" globalOnly="true" escape="false" sticky="true"><p:autoUpdate /></p:growl> 

We are not sure of the reason of this error except that when we use version 6.1, the Error does not show and all functionalities are fine.

**Could that have to do with an updating settings of certain elements in Primefaces? Please give us any hint.**

.. 

Sample XHTML:
Example 1:
                        <p:commandButton value="Submit" ajax="false"
                                         style ="margin-left: 20px"
                                         onclick="delayShow()"
                                         oncomplete="PF('statusDialog').hide()"
                                         actionListener="#{yyyBean.handleFileUpload()}"/>  

Example 2:
                    <p:commandButton value="Update" action="#{xxxBean.updateSummary()}" 
                                     onclick="PF('statusDialog').show()" ajax="false"/>

Example 3:
                        <h:commandLink style="font-size: 13px; font-weight: bold" action="#{zzzBean.doAnalysis('option_1')}" 
                                       onclick="PF('statusDialog').show()"
                                       value="Some value!"/>

**Comment by melloware** [comment]
I think your error is your are using p:layout correct.  The error is coming from the layout component that you don't have a layoutUnit = "center".  I think...  The Layout JS component was upgraded for Jquery 3 from the old version being used in PF 6.1

**Comment by soufanom** [comment]
We have layoutUnit with position="center" inside layout component. I think if we would not have this, PF 6.1 will also complain but it does not.

**Comment by tandraschko** [comment]
Please provide a complete example.

**Comment by soufanom** [comment]
The error comes when we click **Submit** in the dialog of analysis_main.xhtml:

**template.xhtml:**
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <f:facet name="first">
            <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
            <title>XyZ</title>
        </f:facet>

        <f:metadata> 
            <ui:insert name="metaInfo"> 
            </ui:insert>
        </f:metadata> 
        <ui:insert name="myscript"> 
        </ui:insert>
        <link type="text/css" rel="stylesheet" href="#{facesContext.externalContext.requestContextPath}/resources/css/default.css" />
    </h:head>
    <h:body>
        <p:layout style="margin:0px; padding:0px; font-size: 13px" fullPage="true">
            <p:layoutUnit style="margin:0px; padding:0px" collapsible="true" gutter="0" position="north">
                <ui:insert name="header">
                    <div id="header" style="clear: both; margin: 0; padding: 0;" class="ui-widget ui-widget-header ui-corner-all">
                        <h:panelGrid columns="3" style="width:100%; padding: 0px 0px 0px 36px; margin: 0px">
                            <img src="#{facesContext.externalContext.requestContextPath}/resources/images/xyz.png" height="118px" alt="Logo"/>
                            <h:panelGrid  style="position: absolute; left:220px; top:42px; height: 40px; border-left: 3px solid #FFAE20;"/>
                            <h:panelGrid  columns="2" style="padding-left:40px; padding-bottom: 8px">
                                <h:outputLabel styleClass="headerH2" value="XyZ"/>
                                <h:panelGrid styleClass="subhead">
                                    -- tool for analysis
                                </h:panelGrid>
                            </h:panelGrid>
                        </h:panelGrid>
                    </div>
                </ui:insert>
                <p:messages severity="error" showDetail="true" escape="false" closable="true" autoUpdate="true" style="width:800px; padding-left: 280px"/>
                <p:growl id="growl" severity="info, warn" showDetail="true" globalOnly="true" escape="false" autoUpdate="true" sticky="true"/> 
            </p:layoutUnit>
            <p:layoutUnit style="margin:0px; padding:0px"  collapsible="true" gutter="0" position="center">
                <ui:insert name="centerpane">                     
                </ui:insert>
            </p:layoutUnit>
            <p:layoutUnit style="margin:0px; padding:0px" gutter="0" position="south" collapsible="true">
                <div id="footer" style="clear: both; margin: 0; padding: 0;" class="ui-widget ui-widget-header ui-corner-all">
                    <ui:include src="/frags/_footer.xhtml" />
                </div>
            </p:layoutUnit>
        </p:layout> 

        <p:dialog modal="true" widgetVar="statusDialog" 
                  style="width: 200px; height:120px; padding:20px;" 
                  appendTo="@(body)" header="Processing .... "
                  draggable="false" closable="true" resizable="false"> 
            <h:outputLabel value="This may take a while to complete, please be patient...."/>
            <h:panelGrid style="width: 100%; text-align: center;">
                <p:graphicImage value="/resources/images/ajax-loader.gif" /> 
            </h:panelGrid>
        </p:dialog>

    </h:body>
</html>

====================================

**template_of_template.xhtml**
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="template.xhtml">

    <ui:define name="centerpane">
        <p:layout widgetVar="layoutGeral">

            <p:layoutUnit style="margin:0px; padding:0px"  collapsible="true" gutter="0" position="center" styleClass="myAnalColorLayoutStyle">
                <div style="clear: both; margin: 0; padding: 0; max-width: 1100px">
                    <ui:insert name="content"> 
                    </ui:insert>
                </div>
            </p:layoutUnit>

        </p:layout>

    </ui:define>
</ui:composition>

====================================

**analysis_main.xhtml**

<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="template_of_template.xhtml">
    <ui:define name="metaInfo">
    </ui:define>
    <ui:define name="content">       
        <h:panelGrid style="padding-top:20px; padding-left: 40px; font-size: 12px; width:100%">
            <h2 style="margin-top: 10px; margin-bottom: 4px">Available sets</h2>  
        </h:panelGrid>
        <p:layout>
            <p:layoutUnit position="center" collapsible="true" gutter="0"> 
                <h:form id="form" enctype="multipart/form-data"> 
                    <h:panelGrid style="padding: 10px; width: 100%; line-height: 180%; padding-left: 30px;padding-right: 30px">
                        <h:panelGrid style="width:100%; padding-top: 10px; padding-bottom: 8px">
                            Some text goes here...
                        </h:panelGrid>
                        <p:dataTable id="navipane" var="data" value="#{sBean.dataSets}">  
                            <p:column headerText="Data Upload" style="width:200px; text-align: center">  
                                <p:commandButton  update=":uploadView :cmdPane"
                                                  value="#{data.name}"
                                                  icon="#{data.uploadIcon}"
                                                  oncomplete="PF('uploader').show()">
                                    <f:setPropertyActionListener value="#{data}" target="#{xyzBean.selectedData}" />    
                                </p:commandButton>  
                            </p:column>  
                            <f:facet name="footer">  
                                <p:outputPanel style="width:100%; text-align: right">   
                                    <p:commandButton value="Add New" 
                                                     update=":form:navipane"
                                                     actionListener="#{xyzBean.addData}"/>
                                </p:outputPanel>  
                            </f:facet>  
                        </p:dataTable> 
                        <h:panelGrid style="width:100%; text-align: right; padding-right: 40px">
                            <h:panelGrid columns="2">
                                <h:outputText value="Adjust params" style="font-weight:bold"/>
                                <p:selectBooleanCheckbox value="#{xyzBean.adjustBatch}">
                                    <p:ajax event="change"/>
                                </p:selectBooleanCheckbox>  
                            </h:panelGrid>
                        </h:panelGrid>
                    </h:panelGrid>
                </h:form>  
            </p:layoutUnit>

        </p:layout>
        
        <p:dialog widgetVar="uploader" dynamic="true" modal="true" appendTo="@(body)" 
                  hideEffect="explode" resizable="true"> 
            <h:panelGrid id="uploadView" style="width:540px; padding:2px 20px 20px 20px; line-height: 21px">
                <p>
                    Please make sure you have read <a href="/MetaboAnalyst/faces/docs/Format.xhtml" target="_blank">these instructions</a>
                    on how to format your data before you start. The maximum file size per upload is <b>50M</b>. Data should be uploaded as a comma separated values (.csv) file. 
                </p>
                <h:form id="uploadForm" enctype="multipart/form-data">  
                    <h:panelGrid columns="2" style="width:100%">
                        <p:outputLabel style="font-size:12px; font-weight: bold" value="Format:"/>
                        <p:selectOneMenu styleClass="menu" panelStyleClass="panel" value="#{xyzBean.dataFormat}">
                            <f:selectItem itemLabel="Option 1" itemValue="colu"/> 
                            <f:selectItem itemLabel="Option 2" itemValue="rowu"/> 
                        </p:selectOneMenu>
                        <p:outputLabel style="font-size:12px; font-weight: bold" value="Data File:"/>
                        <p:fileUpload value="#{xyzBean.file}" mode="simple"/>  
                    </h:panelGrid>

                    <h:panelGrid style="width:100%; text-align: center; padding-top: 10px">
                        **<p:commandButton value="Submit" ajax="false"
                                         style ="margin-left: 20px"
                                         onclick="delayShow()"
                                         oncomplete="PF('statusDialog').hide()"
                                         actionListener="#{xyzBean.handleFileUpload()}"/>**  
                    </h:panelGrid>
                </h:form>
            </h:panelGrid>
        </p:dialog>

</ui:composition>

**Comment by melloware** [comment]
If you could create a reproducible example using our test project stripping out everything not needed until you have the smallest reproducible example please.

Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.

I can't seem to reproduce your issue...

**Comment by persapiens** [comment]
hi @melloware,

This error happens at [Joinfaces Example](https://github.com/joinfaces/joinfaces-maven-jar-example)  too. I've just upgraded from PF 6.1 to 6.2.

If you try [running example](https://joinfaces-example.herokuapp.com/customInput.jsf), just press "Click Me" button and the error occurs.

**Comment by melloware** [comment]
OK I will try to put together a small sample and reproduce it.  I definitely see the issue in the example above and that error is definitely coming from the Jquery UI Layout library.

**Comment by melloware** [comment]
OK this sample proves the problem.  I am still looking into it but stepping through the debugger the code works find on page load.  But on refreshing the page I get the error even though the JS its calling is identical.  I feel like it might be a bug in the Jquery Layout but still investigating.  You can run "mvn clean jetty:run" on this project and go to http://localhost:8080/primefaces-test/test.xhtml to see the issue.

[primefaces-layout.zip](https://github.com/primefaces/primefaces/files/1800672/primefaces-layout.zip)

**Comment by melloware** [comment]
PR submitted with fix.

**Comment by tandraschko** [comment]
@mertsincan We should probably merge it to elite

**Comment by melloware** [comment]
Requested via my PRO account.

**Comment by chanmratekoko** [comment]
the same problem occurs

**Comment by melloware** [comment]
When you say the same problem occurs what do you mean?  Are you using 6.3-SNAPSHOT built from the latest source??

**Comment by chopin111** [comment]
@melloware We have the same issue when using layout components from primefaces-extensions 6.2 - pe:layout and pe:layoutPane. Should we create same issue in extensions repo?

**Comment by melloware** [comment]
@chopin111 yes please I will fix it there too so I can make a 6.2.1 PFE Release in the next couple of weeks.

**Comment by melloware** [comment]
Thanks @chopin111 its fixed in PFE now too.  Also for those of you that use Layout I got this note from OptimusPrime...

> Cagatay Civici added a comment - 13/Mar/18 8:14 AM
> Note that Layout component is deprecated in 6.2.x in favor of css driven modern layouts.

So it looks like Layout will be removed in 6.3 so you may want to start switching your projects over to using PrimeFaces Extensions version of Layout which will remain supported.

**Comment by svrolanski** [comment]
If it is deprecated, is there an example of how to replace it in primefaces?

**Comment by melloware** [comment]
Also another suggestion that would have made this work is adding this your web.xml.

```xml
    <context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```
This is a huge page performance optimization that moves all Javascript to the bottom of the page and executes it after the DOM is done loading.  It makes your pages speed up load time greatly and it solves this issue.

**Comment by Javaz81** [comment]
**Yes it was just that!!**
```
 <context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```
Thanks @melloware ! I've setup a Netbeans project with JSF from entity classes and PrimeFaces and then replace PF 5.0 with PF 6.2... The standard JSF datatable entity page show up the mystical UI Layout center pane initialization error due to Javascript PF('xxx').hide method setted on "Close" button on standard crud modal forms that IDE pre-built on the entity page itself. I wasting my entire weekend on this issues and i was continuosly wondering if it was a js library that was running before or after the page loading...oh gosh!

**Comment by melloware** [comment]
Glad I could help!

**Comment by shahrulsiagainfo** [comment]
> Also another suggestion that would have made this work is adding this your web.xml.
> 
> ```
>     <context-param>
>         <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
>         <param-value>true</param-value>
>     </context-param>
> ```
> 
> This is a huge page performance optimization that moves all Javascript to the bottom of the page and executes it after the DOM is done loading. It makes your pages speed up load time greatly and it solves this issue.

hi, melloware
after i put this into web.xml, the problem about layout has been fixed
but, some keyboard key like 'z' not function after success web deployment. Do you have any idea to fix this?

**Comment by melloware** [comment]
@shahrulsiagainfo  MOVE_SCRIPTS_TO_BOTTOM should not have any effect on any code.  So when you say `z` is not working I have no idea what you mean.  But MOVE_SCRIPTS_TO_BOTTOM simply moves all your Javascript to the bottom of the page.
