### ISSUE TITLE
org.primefaces.PrimeFaces should be proxyable

### ISSUE THREAD

**Issue by JensPiegsa** [primefaces/primefaces#3460]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: WildFly 10.1

## 2) Expected behavior

* `org.primefaces.PrimeFaces` should be proxyable.

## 3) Actual behavior

* Forcing static method call to `PrimeFaces.current()` makes it harder to run code within unit test.

## 4) Steps to reproduce

Static dependencies are not exactly great with unit testing, e.g.:

	PrimeFaces.current().executeScript("PF('concurrentEditWarningDialogVar').show()");

I tried to implement a CDI producer

 	@Produces
	@RequestScoped
	public PrimeFaces producePrimeFaces() {
		return PrimeFaces.current();
	}

and inject the instance:

 	@Inject
 	PrimeFaces primeFaces;

to later mock it in the test:

 	bean.primeFaces = mock(PrimeFaces.class);

But the producer cannot be deployed:

>Caused by: org.jboss.weld.exceptions.UnproxyableResolutionException: WELD-001436: Type org.primefaces.PrimeFaces is not proxyable because it has a private constructor private org.primefaces.PrimeFaces() - Producer Method [PrimeFaces] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @RequestScoped public presentation.JsfResources.producePrimeFaces()].
        at org.jboss.weld.bean.proxy.DefaultProxyInstantiator.validateNoargConstructor(DefaultProxyInstantiator.java:52)
        at org.jboss.weld.util.Proxies.getUnproxyableClassException(Proxies.java:230)
        at org.jboss.weld.util.Proxies.getUnproxyableTypeException(Proxies.java:182)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
        ... 13 more

`org.primefaces.context.RequestContext` does not have this limitation.

**Comment by Rapster** [comment]
Duplicate and already fixed #3390 ?

**Comment by tandraschko** [comment]
Already fixed yesterday. I will also add a method do set PrimeFaces#current.

**Comment by JensPiegsa** [comment]
Great! Thanks for your quick response.

**Comment by melloware** [comment]
@JensPiegsa This fix will be included in Elite 6.2.1 release.
