### ISSUE TITLE
SelectOneMenu: converter not called for string values

### ISSUE THREAD

**Issue by thundermeier** [primefaces/primefaces#3462]
## 1) Environment
- PrimeFaces version: **6.2**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? **No**
- Application server + version: **Wildfly 11**
- Affected browsers: **All**

## 2) Expected behavior
When using a converter with _SelectOneMenu_ the converter is called for every value of the select items.
As example I am using the _SelectItemsIndexConverter_ provided by Omnifaces. It should convert all values to their respective index in the list of select items. So HTML should look something like this
```
<select>
    <option value="0">Ascending</option>
    <option value="1">Descending</option>
</select>
```

## 3) Actual behavior
If the value of an SelectItem is of type String the converter is not called.
This leads to problems when the converter's _getAsObject()_ metod is called, without a previous call of _getAsString()_.
Back to the example using the _SelectItemsIndexConverter_ provided by Omnifaces the actual HTLM output looks like this:
```
<select>
    <option value="A">Ascending</option>
    <option value="D">Descending</option>
</select>
```

## 4) Steps to reproduce
```
<p:selectOneMenu value="#{view.sorting}" converter="omnifaces.SelectItemsIndexConverter">
    <f:selectItem itemValue="A" itemLabel="Ascending" />
    <f:selectItem itemValue="D" itemLabel="Descending" />
</p:selectOneMenu>
```
---
This behaviour was introduced with [`a638565`](https://github.com/primefaces/primefaces/commit/a638565051f37f0b626fe3efa447b11db9a39378#diff-e4d3a342df3de892c8fd79acabe27e6bL506)

**Comment by jajajaja** [comment]
Hello,

Could this also be fixed in 6.2 version please?

**Comment by tandraschko** [comment]
We could port the fix to PrimeFaces Elite. Otherwise no way until 6.3, sry.

**Comment by jajajaja** [comment]
PF Elite will work for me.
Thank you.

**Comment by tandraschko** [comment]
@mertsincan Can you port it?
