### ISSUE TITLE
Datatable Expansion: Hiding when autoUpdate component is used

### ISSUE THREAD

**Issue by akallam** [primefaces/primefaces#3464]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? No Version? 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7.0.23
- Affected browsers: Chrome, Firefox, IE, EDGE

## 2) Expected behavior
Expected to render content in row expansion.
(see image expected.jpg)
![expected](https://user-images.githubusercontent.com/29357292/37226918-1cafcf1a-23a1-11e8-93af-ca2b0323364d.jpg)

...

## 3) Actual behavior
When AutoUpdate component is used, the data table is hiding and the content in row expansion is rendering. (see images actual.jpg) 
![actual](https://user-images.githubusercontent.com/29357292/37227007-59487c1a-23a1-11e8-83bd-a80590cc8f9a.jpg)

..

## 4) Steps to reproduce
Push 'Open Overflow ModelPanel' button, scroll down to see datatable, click the toggle button. 
.. 

## 5) Sample XHTML
Please see attached file. 

pfCalendar.xhtml
testPfacesOverflow.xhtml

## 6) Sample bean

OverflowTestBean.java
OverFlowTestPojo.java
..
[DataTable Row Expansion.zip](https://github.com/primefaces/primefaces/files/1798211/DataTable.Row.Expansion.zip)

**Comment by jmorris1501** [comment]
Similar issue, but with autoComplete

tried using this with some autocomplete elements, causes the returned list to display like output text
![pf_1_expected](https://user-images.githubusercontent.com/13099697/37590600-7aaf1df0-2b71-11e8-86e6-bf48229bc00a.png)
![pf_2_actual](https://user-images.githubusercontent.com/13099697/37590613-856e0198-2b71-11e8-98e5-e172da9a5667.png)

Attached pictures before and after clicking on the autocomplete.

<p:autoComplete id="regionDD" cache="true" dropdown="true" value="#{configBean.region}" scrollHeight="300" completeMethod="#{configBean.completeRegion}" var="region" itemLabel="#{region.reName}" itemValue="#{region}" converter="entityConverter" forceSelection="false"
size="35" required="true" disabled="#{not configBean.autoDefaults}">
<p:ajax event="itemSelect" listener="#{configBean.updateCustomers}" />
<p:autoUpdate />
</p:autoComplete>

page element above.

If anyone has encountered this, feedback or advice would be greatly appreciated

**Comment by melloware** [comment]
This is not a bug its expected behavior.  You are telling the component to update itself on every AJAX request made on the page which thus destroys the old component and creates a new one.
