### ISSUE TITLE
DataTable: synchronize cellEdit state on server

### ISSUE THREAD

**Issue by javan-mehdi** [primefaces/primefaces#3465]
## 1) Environment
- PrimeFaces 6.2:
- It doesn't work with the latest released version (6.2)
- It doesn't work with newest sources (6.3-SNAPSHOT)
- Application server: Jetty plugin in Maven and Weblogic 12c
- Affected browsers: Firefox 58.0.2 (latest version)

## 2) Expected behavior

When pencil icon in rowEditor of a dataTable is clicked, the row enters editing state. In that state when the dataTable is updated via an ajax request, I expect that the row remains in editing state and the changes in its cells remains until I click on check-mark icon to confirm them or cancel them by clicking on close icon.

## 3) Actual behavior

When pencil icon in rowEditor of a dataTable is clicked, the row enters editing state. In that state when the dataTable is updated via an ajax request, the editing is canceled and the changes in row cells are lost.

## 4) Steps to reproduce

I cloned primefaces-test repository here: https://github.com/javan-mehdi/primefaces-test and reproduced the situation. After running the project, firstly click on a pencil and edit an inputText, then change tax rate and after blur event of tax rate you can see that the dataTable is no longer in edit mode.

## 5) Sample XHTML

<!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:f="http://java.sun.com/jsf/core"
          xmlns:p="http://primefaces.org/ui"
          xmlns:h="http://java.sun.com/jsf/html">
    
    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
    
        <h:form id="form1">
    
            <h1>#{testView.testString}</h1>
            <p:outputLabel for="taxRate" value="Tax Rate:"/>
            <p:inputText value="#{testView.taxRate}" id="taxRate">
                <p:ajax update="employeesTable" event="blur"/>
            </p:inputText>
            <p:dataTable value="#{testView.employees}"
                         id="employeesTable"
                         var="employee"
                         rowKey="#{employee.name}"
                         editMode="row"
                         editable="true">
                <p:column>
                    <p:rowEditor/>
                </p:column>
                <p:column headerText="Name">
                    <p:cellEditor>
                        <f:facet name="input">
                            <p:inputText value="#{employee.name}"/>
                        </f:facet>
                        <f:facet name="output">
                            <h:outputText value="#{employee.name}"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>
                <p:column headerText="Salary">
                    <p:cellEditor>
                        <f:facet name="input">
                            <p:inputText value="#{employee.salary}"/>
                        </f:facet>
                        <f:facet name="output">
                            <h:outputText value="#{employee.salary}"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>
                <p:column headerText="Net Income">
                    <h:outputText value="#{employee.salary - testView.taxRate * employee.salary}"/>
                </p:column>
            </p:dataTable>
    
        </h:form>
    </h:body>
    </html>

## 6) Sample bean

    package org.primefaces.test;
    
    import javax.annotation.PostConstruct;
    import javax.faces.bean.ManagedBean;
    import javax.faces.bean.ViewScoped;
    import java.io.Serializable;
    import java.util.ArrayList;
    import java.util.List;
    
    @ManagedBean(name = "testView")
    @ViewScoped
    public class TestView implements Serializable {
    
        private String testString;
        private List<Employee> employees;
        private double taxRate = 0.2;
    
        @PostConstruct
        public void init() {
            testString = "Welcome to PrimeFaces!!!";
            employees = new ArrayList<Employee>(5);
            employees.add(new Employee("Anna", 4000));
            employees.add(new Employee("John", 5000));
            employees.add(new Employee("Kristia", 6000));
            employees.add(new Employee("Jack", 4500));
            employees.add(new Employee("Sara", 5400));
        }
    
        public String getTestString() {
            return testString;
        }
    
        public void setTestString(String testString) {
            this.testString = testString;
        }
    
        public List<Employee> getEmployees() {
            return employees;
        }
    
        public double getTaxRate() {
            return taxRate;
        }
    
        public void setTaxRate(double taxRate) {
            this.taxRate = taxRate;
        }
    }

**Comment by melloware** [comment]
Not sure this will be an easy fix as if the datatable is updated via an update="" the AJAX is replacing the DOM for the entire datatable wiping out everything that was there.   Not sure how that state of what you are doing will be retained.

**Comment by javan-mehdi** [comment]
One solution may be storing state of each row in ViewState and use this data in `encodeRow` to determine  whether `EDITING_ROW_CLASS` must be used for the row or not. Right now, when the pencil icon is clicked, the row goes to editing state only by JavaScript and there is no need to send an Ajax request. However, in my proposed solution, an Ajax request is needed to change the state of the row in ViewState.

**Comment by tandraschko** [comment]
It's currently by design. If you need this feature, i suggest to sponsor it via PrimeFaces PRO. It's to much effort to implement this in freetime.

**Comment by melloware** [comment]
No comments in 3 years and as Thomas mentioned this would be difficult to fix with very little reward. Don't update the whole data table while row editing is occurring.
