### ISSUE TITLE
autoComplete: various XSS vulnerabilities

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3468]
## 1) Environment
- PrimeFaces version: 6.3-snapshot
- Does it work on the newest released PrimeFaces version? Version? Yes, 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Yes
- Application server + version: n/a
- Affected browsers: n/a

## 2) Expected behavior
Proper escaping

## 3) Actual behavior
Improper escaping

## 4) Steps to reproduce
- Go to https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml
- Enter `<script>alert('foo');</script>` in arbitrary input field
- Await suggestions
- Choose suggestion with arrow-down key
- Alert box will arise

## 5) Sample XHTML
https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

## 6) Sample bean
https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

**Comment by cnsgithub** [comment]
I changed the title of this issue since it came out that there are even more vulnerabilities in `p:autoComplete` as 'just' the one mentioned above: the attributes `moreText`, `emptyMessage `, `resultsMessage` and `p:column headerText` are also subject to XSS.

**XHTML (excerpt):**
```xml
                <p:outputLabel for="moreText" value="moreText" />
                <p:autoComplete id="moreText" value="#{autoCompleteView.txt1}" completeMethod="#{autoCompleteView.completeText}" moreText="&lt;script&gt;console.log('moreText xss');&lt;/script&gt;" maxResults="2" />

                <p:outputLabel for="emptyMessage" value="emptyMessage" />
                <p:autoComplete id="emptyMessage" value="#{autoCompleteView.txt1}" completeMethod="#{autoCompleteView.completeEmpty}" emptyMessage="&lt;script&gt;console.log('emptyMessage xss');&lt;/script&gt;" />

                <p:outputLabel for="headerText" value="headerText" />
                <p:autoComplete id="headerText" value="#{autoCompleteView.theme2}" completeMethod="#{autoCompleteView.completeTheme}"
                                var="theme" itemLabel="#{theme.displayName}" itemValue="#{theme}" converter="themeConverter" forceSelection="true">
                    <p:column headerText="&lt;script&gt;console.log('headerText xss');&lt;/script&gt;">
                        <h:outputText styleClass="ui-theme ui-theme-#{theme.name}" />
                    </p:column>
                </p:autoComplete>
<!-- rest like in showcase -->
```

**Bean (excerpt):**
```java
    public List<String> completeEmpty(String query) {
        return Collections.emptyList();
    }
   // rest like in showcase
```

**Comment by cnsgithub** [comment]
More XSS:
- `data-item-value`
- `data-item-label`

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3471

**Comment by tandraschko** [comment]
Could you please stop creating issues? :D :D
