### ISSUE TITLE
DataTable: add mode to view it like it in reflow mode or like dataList

### ISSUE THREAD

**Issue by cmastrantono** [primefaces/primefaces#3475]
I talked to Cagatay and he told me to create an issue at GitHub as a request for this.

Te feature request is: be able to activate (with a param) a table view like the reflow one but in any resolution.

(see image below)

![image](https://user-images.githubusercontent.com/1071056/37284201-67ba22d2-25d9-11e8-94d1-c9111e8a2cd7.png)

**Comment by tandraschko** [comment]
Looks like DataList for me.

**Comment by cmastrantono** [comment]
Could be... but I was hoping to use the reflow view in any resolution with an editable datatable

**Comment by tandraschko** [comment]
I see. Not sure about the plans of PrimeTek to add it, but noone in the OS-community will just do it for you, so maybe you should talk with PrimeTek/Cagatay about sponsoring.

**Comment by cnsgithub** [comment]
You can try to dynamically add / remove CSS which overrides the default @media(max-width:640px) for the .ui-datatable-reflow when you want something like this. Then you can force the reflow-layout to be active on any resolution.

To see which classes to override see:

https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css

Line 325+

**Comment by cmastrantono** [comment]
Thanks! I'll try. (Also I just contacted Cagatay to talk about sponsoring)

**Comment by melloware** [comment]
As stated by @cnsgithub this can be done with simple CSS so no need to try and build in a feature for this.
