### ISSUE TITLE
Missing descriptions in the taglib

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#3480]
Not really an issue, but almost all of the components in the file [standard-facelets-taglib.xml](https://github.com/primefaces/primefaces/blob/1a084be2a7ef33e9c4c38fa16b48e5e022d8500b/src/main/resources-maven-jsf/standard-facelets-taglib.xml) do not have the description attribute.

**Comment by tandraschko** [comment]
A PR would be great!
