### ISSUE TITLE
Datatable: Enhancement of paginator

### ISSUE THREAD

**Issue by Hamsterbau** [primefaces/primefaces#3481]
**Forum-Post:** 
https://forum.primefaces.org/viewtopic.php?f=3&t=54773

## 1) Environment
- PrimeFaces version: 6.x

## 2) Expected behavior
A better way to define paginator-Template or just use a facet for paginaton, so it can be changed or created elsewhere, in an easier way.

Perhaps it would be great to have a paginator-Facet, to support the following things:

- Show content if no pagination is needed (less rows than lowest page entries)
- Be able to show different conent (for example p:selectOneMenu for entries per page)
- Better customization for pagination links/buttons

Currently there are a lot of attributes, which can be configured for the dataTable to overcome the limitation (no paginator facet). But at least the possibility to show content, if no pagination is needed, would be great and is only possible by using CSS workarounds.

**Comment by tandraschko** [comment]
Sponsoring welcome, i don't like to touch DataTable ;)

**Comment by melloware** [comment]
Neither do I @tandraschko .  I leave those up to Mert. :)

**Comment by melloware** [comment]
4 years and no PR's or upvotes.  @Hamsterbau i am going to close this for now.
