### ISSUE TITLE
Datatable: Support adding of new rows

### ISSUE THREAD

**Issue by appldo** [primefaces/primefaces#3482]
Feature request: 
The editable datatable is a very useful component, but as soon, as you can edit lines, it is straight forward that you would also like to add lines. We have many tables where we use this functionality and you can do that with some custom javascript and ajax. E.g. like [this](https://stackoverflow.com/questions/13821750/trigger-activate-the-roweditor-from-bean-for-a-primefaces-in-cell-editing-enable). But of course it would be better if this feature were part of the component. 

This could e.g look this way:
![image](https://user-images.githubusercontent.com/16803757/37347406-0f7a5f0c-26d2-11e8-9a7a-ac42737a24ff.png)

or that way:
![image](https://user-images.githubusercontent.com/16803757/37348169-c296f84c-26d3-11e8-99c6-cc316d77a32c.png)

**Comment by tandraschko** [comment]
Its very unlikely that it will be implemented without sponsoring.

**Comment by melloware** [comment]
@tandraschko I would mark this invalid or close it as you can do this already by just adding a button to the header of the table. We do this in our apps.
