### ISSUE TITLE
KeyFilter: not working in Chrome

### ISSUE THREAD

**Issue by ShivaniSK** [primefaces/primefaces#3484]
## 1) Environment
- PrimeFaces version: 6.1
- Affected browsers: Chrome

## 2) Expected behavior
keyFilter with mask alphanum should not allow special characters in input textBox for all browsers
...

## 3) Actual behavior
keyFilter with mask alphanum not working in Chrome . Working in IE
..

## 4) Steps to reproduce
Try entering special characters in the input box in IE and Chrome
.. 

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:head>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />	
	
</h:head>	
	<h:form>
		<h:inputText id="projectKey"  label="Project Key" size="29" maxlength="10">
		</h:inputText>
		<p:keyFilter for="projectKey" mask="alphanum" />
	</h:form>
</html>
```
..

## 6) Sample bean

..

**Comment by huseyinturkmenoglu** [comment]
Your p:keyfilter is using mask="alphanum" that means users can write just string and numeric value. I think you could not use the mask="alphanum".  p:keyFilter is working correctly.

**Comment by melloware** [comment]
When you say special characters what do you mean?    There was this original issue that was fixed a while ago:  https://github.com/primefaces/primefaces/issues/1852

**Comment by melloware** [comment]
I can't reproduce this and there has been no response for more info from OP. I say we close this issue.
