### ISSUE TITLE
Diagram: event "onConnectionChange" have "getNewTargetEndPoint" always null

### ISSUE THREAD

**Issue by brunoaandrade** [primefaces/primefaces#3485]
## 1) Environment
- PrimeFaces version:
6.2

## 2) Expected behavior
When "onConnectionChange" called the method "getNewTargetEndPoint()" should return EndPoint

## 3) Actual behavior
When "onConnectionChange" called the method "getNewTargetEndPoint()" returns always null

## 4) Steps to reproduce
Exemple https://www.primefaces.org/showcase/ui/data/diagram/editable.xhtml

**Comment by tandraschko** [comment]
PR welcome

**Comment by melloware** [comment]
Fixed wtith this PR: https://github.com/primefaces/primefaces/pull/4368
