### ISSUE TITLE
TriStateCheckbox: "NaN" result when calling toggle() javascript method

### ISSUE THREAD

**Issue by sergi-mm** [primefaces/primefaces#3486]
When using method `toggle()` from TriStateCheckbox it sets the value to NaN instead of the next defined value (0,1,2 in the example), and the icon of the TriStateCheckbox does not change. Then it remains in state NaN even if you click it to manually toggle.

This issue has been reproduced in the version 6.2 using its ShowCase page: https://www.primefaces.org/showcase/ui/input/triStateCheckbox.xhtml

### Sample XHTML
```
<p:triStateCheckbox value="#{triStateCheckboxView.value1}" widgetVar="triStateCheckboxJS"/> 
<p:commandButton value="Toggle" type="button" onclick="PF('triStateCheckboxJS').toggle()"/> 
```

**Comment by cnsgithub** [comment]
If you check the toggle function it requires a parameter

![image](https://user-images.githubusercontent.com/13161711/37455004-59341186-283c-11e8-83e6-9aea2d2d9c23.png)

PF('triStateCheckboxJS').toggle(1)

**Comment by sergi-mm** [comment]
Thanks @cnsgithub ! I didn't know that toggle() function has a parameter... How the parameter "direction" works?

In fact, reviewing the documentation, it says there is no parameter...

![imatge](https://user-images.githubusercontent.com/9212820/37456636-2282eed8-2840-11e8-98f6-23fe0a90419c.png)

**Comment by cnsgithub** [comment]
well use +1 to go forward and -1 to to back i guess

**Comment by melloware** [comment]
So I added failsafe to this so the documentation will line up and toggle() will advance to the next one or you can still use toggle(direction) if you want to go forward or back.
