### ISSUE TITLE
Keyboard: Unicode Character does not support at p:keyboard in attribute layoutTemplate

### ISSUE THREAD

**Issue by chanmratekoko** [primefaces/primefaces#3487]
## Environment
	
* PrimeFaces version: 6.2
* Application server: Wildfly 10
* Affected browsers: ALL
	
## Expected behavior and Actual behavior
	
When we only upgraded from Primefaces version 6.1 to version 6.2, now clicking on these keyboard button (or) keyboard causes the following error:
	
'\\' 'u' '1' '0' '4' '1' ..... 'back' ..... '\\' 'u' '1' '0' '4' '4' ... 'clear'
each character set in one keyboard layout button
	
## Sample XHTML:

```xml
<p:keyboard id="myIdState"
	readonly="#{facesContext.currentPhaseId.ordinal eq 6}"
	style="width:40px;margin-left:-4px;" layout="custom"
	layoutTemplate="\u1041\u1042\u1043-back,\u1044\u1045\u1046-clear,\u1047\u1048\u1049-close,\u1040"
	value="#{UserManagementApp.idState}"
	maxlength="2">
```
but this code ok
	
```xml		
<p:keyboard id="myIdState"
	readonly="#{facesContext.currentPhaseId.ordinal eq 6}"
	style="width:40px;margin-left:-4px;" layout="custom"
	layoutTemplate="၁၂၃-back,၄၅၆-clear,၇၈၉-close,၀"
	value="#{UserManagementApp.idState}"
	maxlength="2">
```

When we use version 6.1, the Error does not show and all functionalities are fine.
	
**Could that have to do with updating settings of certain elements in Primefaces? Please give us any hint.**

**Comment by melloware** [comment]
OK from looking at the source code commits this component was not really changed between 6.1 and 6.2.  So I am wondering if a) its a Jquery 3 thing or b) did something else in your environment change?

**Comment by chanmratekoko** [comment]
@melloware 

Error Still Occur testing with this repo 
https://github.com/primefaces/primefaces-test

Test with 
**Primefaces version 6.1 is OK**
but 
**Primefaces version 6.2 does not work with below the code.**

Actual behavior (Error UI) with this source code

	<p:keyboard id="name"
		readonly="#{facesContext.currentPhaseId.ordinal eq 6}"
		layoutTemplate="\u1041\u1042\u1043-back,\u1044\u1045\u1046-clear,\u1047\u1048\u1049-close,\u1040"
		value="#{testView.name}" maxlength="10" />

![error](https://user-images.githubusercontent.com/19842154/38009221-186e3496-3279-11e8-87d9-e506fd550688.JPG)

Expected behavior (Expected UI) with working source code

	<p:keyboard id="expected"
		readonly="#{facesContext.currentPhaseId.ordinal eq 6}"
		layoutTemplate="၁၂၃-back,၄၅၆-clear,၇၈၉-close,၀"
		value="#{testView.expected}" maxlength="10" />


![expected](https://user-images.githubusercontent.com/19842154/38009238-2edd8628-3279-11e8-82e8-412e5c28e62d.JPG)

Testing repo
https://github.com/chanmratekoko/primefaces-test.git

**Comment by melloware** [comment]
Thank you so much for the sample project!  I just submitted a PR with the fix: https://github.com/primefaces/primefaces/pull/3540
