### ISSUE TITLE
p:radio value lost on validation error.

### ISSUE THREAD

**Issue by syabru** [primefaces/primefaces#3488]
## 1) Environment
- PrimeFaces version: 6.2 (works in 6.1)

## 2) Expected behavior
``p:radio`` value keeps its value when validation fails.

## 3) Actual behavior
``p:radio`` value is lost and radio element can't be selected anymore

## 4) Steps to reproduce
Add ``p:selectOneRadio`` element with layout ``custom``
Add a ``p:radio`` element which refers to ``p:selectOneRadio``
Add a checkbox element and fail validation on this element

## 5) Sample XHTML
```
[...]
      <p:selectOneRadio id="myId"
                        value="#{myBean.value}"
                        layout="custom"
                        required="true">
        <f:selectItems value="#{myBean.values}"
                       var="type"
                       itemValue="#{type}"
                       itemLabel="#{type}"/>
        <p:ajax event="change" execute="@this" render="@form" update="@form"/>
      </p:selectOneRadio>
[...]
       <ui:repeat value="#{myBean.values}" var="type" varStatus="status">
          <tr>
            <td>
              <p:radioButton id="paymentOption"
                             for=":myForm:myId"
                             itemIndex="#{status.index}" />
            <td>
          <tr>
      </ui:repeat>

      <p:selectBooleanCheckbox id="myCb"
                                label="myLabel"
                                value="false"
                                required="true"
                                validator="#{myBean.validate}"
      </p:selectBooleanCheckbox>
```

## 6) Sample bean
```java
public class MyBean {
    public void validate(FacesContext context,
            UIComponent component, Object value)
    throws ValidatorException
    {
      throw new ValidatorException("validation failed");
    }
}
```

**Comment by huseyinturkmenoglu** [comment]
Hi,

You could use this: import javax.faces.validator.ValidatorException;

And you should redesign your validate method (no constructor etc.) 

Also, may be alternative, you could examine this example: https://www.primefaces.org/showcase/ui/csv/custom.xhtml

Or you could create a sample project: https://github.com/primefaces/primefaces-test

Greetings,

**Comment by Grizzlijs** [comment]
On PF 6.2 update have same issue.. Radio input buttons loses values after error validation. 
Right now have quick fixes using js adding values back but it is bad solution.

**Comment by tandraschko** [comment]
Could you please add a runnable example? Otherwise we can't test it.
