### ISSUE TITLE
AutoComplete: CSV throws Exception with MyFaces

### ISSUE THREAD

**Issue by Markus-Patt** [primefaces/primefaces#3489]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: jetty-maven-plugin:8.1.9.v20130131 from https://github.com/primefaces/primefaces-test
- Affected browsers: all

## 2) Expected behavior
Should not throw an exception.

## 3) Actual behavior
Throws an exception in org.primefaces.renderkit.CoreRenderer#renderValidationMetadata, called from org.primefaces.component.autocomplete.AutoCompleteRenderer#encodeHiddenSelect

## 4) Steps to reproduce
see 5) and 6), then load page in browser

## 5) Sample XHTML
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h:form>
            <p:autoComplete
                value="#{testView.values}"
                label="test"
                completeMethod="#{testView.complete}"
                multiple="true" />
        </h:form>

    </h:body>
</html>
```

## 6) Sample bean
```java
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.Collections;
import java.util.List;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    private List<String> values;


    public TestView() {
        values = Collections.singletonList("test");
    }

    public List<String> getValues() {
        return values;
    }

    public void setValues(final List<String> aValues) {
        values = aValues;
    }


    public List<String> complete(final String aPattern) {
        return Collections.singletonList(aPattern);
    }

}
```

While encoding the hidden select element, the select-tag gets opened *writer.startElement("select", null);*.
This is followed by encoding the options.

In the end, it's checked, if CSV is active. If this is the case, *renderValidationMetadata(context, ac)* gets called.
If the the attribute "label" is set on the AutoComplete-Component, it gets written on the ResponseWriter *writer.writeAttribute(HTML.VALIDATION_METADATA.LABEL, label, null);*. In the case of myfaces, the ResponseWriter is an instance of *org.apache.myfaces.shared.renderkit.html.HtmlResponseWriterImpl*, which does a check in *writeAttribute*, if the there is a opened start tag. If that is not the case, an IllegalStateException is raised.

In my opinion, it should be enough, to switch the blocks

```java
        if (RequestContext.getCurrentInstance().getApplicationContext().getConfig().isClientSideValidationEnabled()) {
            renderValidationMetadata(context, ac);
        }
```
and
```java
        for (String value : values) {
            writer.startElement("option", null);
            writer.writeAttribute("value", value, null);
            writer.writeAttribute("selected", "selected", null);
            writer.endElement("option");
        }
```
in org.primefaces.component.autocomplete.AutoCompleteRenderer#encodeHiddenSelect 

I will try to create a fix and a PR.

**Comment by tandraschko** [comment]
Thanks, the PR is fine!
