### ISSUE TITLE
Navigation with <p:autoComplete> in <p:dataTable>

### ISSUE THREAD

**Issue by Pooum** [primefaces/primefaces#349]
Hello,

In a datatable with cell editor it is possible to navigate from a cell to the next one using the tab key.
Except when a column is an autocomplete, in this case we can navigate from a cell to an autocomplete but not from an autocomplete to another one.

Example, take the editable datatable fom promefaces showcase ( http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml ) , and replace : 

``` html
<p:column headerText="Brand">
           <p:cellEditor>
               <f:facet name="output"><h:outputText value="#{car.brand}" /></f:facet>
               <f:facet name="input">
                   <h:selectOneMenu value="#{car.brand}" style="width:100%">
                       <f:selectItems value="#{dtEditView.brands}" var="man" itemLabel="#{man}" itemValue="#{man}" />
                   </h:selectOneMenu>
               </f:facet>
           </p:cellEditor>
       </p:column>
```

by 

``` html
<p:column headerText="Brand">
            <p:cellEditor>
                <f:facet name="output">
                    <h:outputText value="#{car.brand}" />
                </f:facet>
                <f:facet name="input">
                    <p:autoComplete value="#{car.brand}" var="p" itemLabel="p" style="width:100%">
                    </p:autoComplete>
                </f:facet>
            </p:cellEditor>
        </p:column>
```

Thanks

**Comment by cagataycivici** [comment]
This is a question, please use forum instead.

**Comment by Pooum** [comment]
Hello,

I don't understand your message, it's not a question, may be I haven't explain enough. 

Actually navigate with "tab", in a datatable containing some autocompletes as input doesn't work.
My point is that it could be good to do it ; actually I need it and I think I'm not alone in this case.

Think of a use case where the user want to edit many data in a datatable.
The best way to do it is to click on the first cell, fill it then press "tab" to go to the next cell ; fill it etc.

It works with checkbox, inputText, selectOneItem and some others. 
Make it work with autocomplete seems logical too.

**Comment by cagataycivici** [comment]
Ok, we'll check again, thanks.

**Comment by jederfreitas** [comment]
Hi Cagatay, Pooum,

Is there a solution or a workaround about it? I have the same problem.

Thanks

**Comment by Prismapanda** [comment]
Hi there,

we experienced this behaviour even if a cell is not editable at all (no p:cellEditor present, v6.0.3). Would be nice to hear of a fix.

**Comment by Rapster** [comment]
Not reproduced in 6.1-SNAPSHOT

**Comment by tandraschko** [comment]
@Rapster did you tried it with the example?
So it fails in 6.0 but works fine in 6.1?

**Comment by Rapster** [comment]
I didn't try with 6.0, but I did test 6.1-SNAPSHOT, I can navigate from an autocomplete to another one with no problem

**Comment by melloware** [comment]
Fixed with PR: https://github.com/primefaces/primefaces/pull/4858

If you set `autoSelection="false"` on AutoComplete the TAB key will work like normal and not select the item.
