### ISSUE TITLE
New component: Material Floating Button 

### ISSUE THREAD

**Issue by ybendek** [primefaces/primefaces#3491]
It could be nice to include a similar component like this component. Commonly used with the google material design

https://github.com/nobitagit/material-floating-button

**Comment by cnsgithub** [comment]
To be honest - I wouldn't add something simple as this. This just bloats PrimeFaces. You can bind the action of the button easily with a <p:remoteCommand> via JS. If you want to make a JSF component for this you can do so by using custom taglibs.

**Comment by tandraschko** [comment]
I suggest to sponsor it try it in PrimeFaces Extensions, it's like an sandbox for new components ;)

**Comment by melloware** [comment]
This has also been asked for previously years ago so there must be a need. See this duplicate ticket...

https://github.com/primefaces/primefaces/issues/1006

**Comment by tandraschko** [comment]
Lets do that in PFE first ;)

**Comment by melloware** [comment]
Finally Arrived in PFE 7.0.1: https://www.primefaces.org/showcase-ext/views/fab.jsf
