### ISSUE TITLE
Primefaces 6.2.1 includes Resources instead of linking to them ...

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#3495]
I am wondering of the big size of the new Primefaces 6.2.1 release.
The current 6.2.1 release is very big in size : 4,07MB !

_So i analyzed that and i found out the following:_

In both versions (community 6.2 and elite/pro 6.2.1) there are webfonts and resources
inside that are coming from the Aristo and Omega Theme and also the fontawesome webfont 
packed into the jar-file instead of only linking to these fonts via CDN-server's !

**How i can see it ?**

_Here are the steps for the 6.2 community-version :_
1.) Download the latest version of Primefaces Community (Current 6.2)

2.) Extract the primefaces-6.2.jar with an unpacker into a folder e.g. primefaces-6.2

3.) Go into the folder and go to the following subfolder:
\primefaces-6.2\META-INF\resources

5.) When you check the filesize of the folders inside the resources you will see where 
the big size is coming from:

\primefaces-6.2\META-INF\resources\primefaces\fa\
\primefaces-6.2\META-INF\resources\primefaces-aristo\
\primefaces-6.2\META-INF\resources\primefaces-omega\

**The filesize of this 3 folders is 1,4MB big !**
On a sum filesize of 4,07MB this is very much !!

**The solution ?**
1.) For using WebFonts it's recommed to only link to the external CDN-Server instead of
including them complete to the application.
For e.g. Font-Awesome use the given CDN-Link when the feature is enabled because it's always 
faster loaded via CDN-Server:

2.) The other resources needed for the Pro/Elite-Themes only should be put into the packed Themes 
and then linked to them.
Also the WebFonts should be loaded from a CDN-Server instead of putting them to the Primefaces-Package. 
If this does not work you can always use the CDNResource-Handler from Omnifaces to redirect
resources to another URL:
[http://showcase.omnifaces.org/resourcehandlers/CDNResourceHandler](http://showcase.omnifaces.org/resourcehandlers/CDNResourceHandler)

**Comment by melloware** [comment]
What about applications behind firewalls that are not allowed to reach out to the Internet?

**Comment by tandraschko** [comment]
Use OmniFaces and be happy with it ;)

**Comment by ssibitz** [comment]
**Really ?** 
Ignoring and closing is not the right way when i payed for that primefaces service.

**And:**  
If you are behind a firewall and can not reach the internet you also cannot access primefaces application
because the user's browser is rendering the whole page and getting the external links 
and not the application server...

This is also a performance issue: The webbrowser can load external links which are not on the current server in paralell. In case of a CDN-Link this is the recommend way from google.

But i also see: 
It seems to be that customers which Elite instead of Prime account are not handled as customers,
so i will also Extend Primefaces with my own libraries in future instead pulling time into another Task's of the Primefaces Extensions by myself or giving new ideas to it...

**Comment by cnsgithub** [comment]
Really? I think the licence allows to modify the *.jar if i'm not wrong. You can easily remove the resources which are not needed. You can probably add this to your build process as well. Modifying a *.class is a different story. You could use gradle for example to integrate this in your build process.

PrimeFaces is not always used in environments with internet access. It can and probably will be used on Intranet with very strict firewall rules. Business / Enterprise is actually the main use-case of JSF in general. Also CDN adds a single point of failure. I don't get why essential dependencies like jQuery sometimes are linked by using a CDN. If that CDN is down (or the DNS resolution on provider-side doesnt work properly) for any reason, your site is un-usable, even if your site is still up. 

Elite is a subscription is just for getting the elite jar btw. No support package. If you want a support package obviously the price is higher (Pro)

Also i don't really get why you are concerned about the file-size of the *.jar. It's server-side anyway. the Java JDK which is needed to run PrimeFaces in the first-place is 500MB+ big. If you want to save storage or deployment size there are probably better places to start with. Outsource *.jar files into the AppServer runtime (e.g. use WildFly modules, don't bundle any jar with your war/ear etc.) 

Note: I'm not affiliated with PrimeTek, just saying what i know.

**Comment by melloware** [comment]
There are a lot of government and homeland security target companies that yes use Intranet applications with absolutely ZERO Internet access.  I personally have worked in these environments where absolutely a CDN link would be blocked from retrieval. 

So to me this is a total showstopper of a requested feature to tie PF to external downloads as a requirement.

**Comment by ssibitz** [comment]
I now have solved this issue by creating a command-line-script which does the following thing:

1.) Unpack primefaces.jar
2.) Remove unwanted/unneeded resources from it like Webfonts or Pro-Themes
3.) Repack it and deploy it to locale maven repository

This resolves my issue that on my company 
that we need an external hosted application with a high performance.
We also don't wont to include unneeded parts like WebFonts, Stylesheets or Script
which are not used to keep the application maintainance small.

This also saves me about 5MB of size for Primefaces and Primefaces-Extensions together.  


It is sad that the Primefaces Library can't be build by selecting all depencies which the user
really needs like you can do on other Big libraries Online (Think of jQuery - You can download it complete or only the parts which are needed...)

**Comment by cnsgithub** [comment]
jQuery is a client-side library. Here it makes more sense to 'save memory'. Whereas PrimeFaces is a server-side runtime jar library. You can most likely start to save storage space somewhere else ;)

**Comment by ssibitz** [comment]
I don't do this to save space.

I do this because my company don't wont to have
deployed any embedded libraries / application on our server's (open source or commercial) when 
they can be loaded from an external CDN-Server in the latest fixed / updated version when there is
a security relevant fix made.

So i removed things like WebFonts / Pro-Themes from the Library
and redirect them to the external original CDN-Server including the version which should be used 
by using Omnifaces CDNResourceHandler.

To keeping an external library up to date i only have to change the settings and redeploy
the application instead of waiting for a new Primefaces-Build with e.g. a new and fixed jQuery-Version 
... 

So an update or patch can be done by changing only the CDN's address.

**Comment by tandraschko** [comment]
As i already said, use OmniFaces and the CDNResourceHandler and be happy with it. I don't see any reason to implement the same again in PrimeFaces.

**Comment by ssibitz** [comment]
**But what about the Pro-Theme-Part's ?**

Why they are included into the Community-Edition and Elite-Edition of Primefaces 
instead of including them only if a user buyed these themes : 
\primefaces-6.2\META-INF\resources\primefaces-aristo\
\primefaces-6.2\META-INF\resources\primefaces-omega\

I don't have the licence to use these themes
and so i also don't want to have these part's always 
included into the Primefaces-Library...

**Comment by tandraschko** [comment]
Everything whats here in this repo, is open source and licenses under apache2. Aristo and Omega are the default themes which are delivered in the primefaces.jar.

**Comment by cnsgithub** [comment]
I don't think what you are doing gives a big benefit. If you're going to use Elite builds, it doesn't make sense to use CDN for some part of it. 

Also if you added omnifaces just for THIS, you're also adding a potential source of errors. I'm not saying that it will happen, but basically when updating omnifaces / jsf / primefaces. You need to make sure / test that everthing works fine, as these three jars are dependent to each other at some point. 

The only thing i do understand however is the problem of jQuery upgrade, which i already mentioned in this issue: https://github.com/primefaces/primefaces/issues/3442 It definetly would make sense to have the option to upgrade jQuery without touching the PF jar and without adding yet another dependency (Omnifaces)
