### ISSUE TITLE
ConfirmDialog: TypeError: this.jqEl is undefined

### ISSUE THREAD

**Issue by lagar84** [primefaces/primefaces#3498]
## 1) Environment
- PrimeFaces version: 6.2; 6.2.1 (it works on version 6.1, so this is a regression)
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: jetty, from reproducer, but it is not relevant
- Affected browsers: at least firefox and chrome latest

## 2) Expected behavior
confirmDialog should appear

## 3) Actual behavior
confirmDialog does not show, an error is logged on console (TypeError: this.jqEl is undefined)

## 4) Steps to reproduce
On the reproducer:  http://localhost:8080/primefaces-test/test.xhtml
Step 1: click on show data button
Step 2: click on delete link. The confirm dialog does not show.
	            	On console, there is an error: TypeError: this.jqEl is undefined

## 5) Sample XHTML

`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        
        <h1>#{testView.testString}</h1>
        
        <h:form>
        	<p:confirmDialog id="globalConfirmDialog" global="true" closeOnEscape="true" >
				<p:commandButton value="Yes " type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"/>  
       			<p:commandButton value="No "  type="button" styleClass="ui-confirmdialog-no"  icon="ui-icon-close"/>       
			</p:confirmDialog>
        </h:form>
        
        <h:form>
        
            <p>
            	Step 1: click on show data button
            </p>
            <p:commandButton ajax="false" value="Show data" action="#{testView.showData}"/>
        
            <p:outputPanel rendered="#{testView.data != null}">
            
	            <p>
	            	Step 2: click on delete link. The confirm dialog does not show.
	            	On console, there is an error: TypeError: this.jqEl is undefined
	            </p>
	            
	        	<p:dataTable value="#{testView.data}" var="d" >
	        	
	        		<p:column>
	        		      <h:outputText value="#{d}" />
	        		</p:column>
	        		
	        		<p:column>
	        			<p:commandLink value="delete" action="#{testView.delete(d)}" process="@this" update="@form">
	        			
	        				<p:confirm header="Confirm"
					   				   message="Sure you want to delete #{d}?"
					   				   icon="ui-icon-alert" />        			
	        			</p:commandLink>        		
	        		</p:column>
	        	
	        	</p:dataTable>
        	</p:outputPanel>
        
        </h:form>
        
    </h:body>
</html>`

## 6) Sample bean

` package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    
    private List<String> data;
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
        
    }
    
    public void showData() {
    	
    	if(data == null) {
    		data = new ArrayList<String>();
    		
    		for(int i = 0; i < 10; ++i) {
            	data.add(String.valueOf(i));
            }
    	}
    }
    
    public void delete(String d) {
    	data.remove(d);
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

	public List<String> getData() {
		return data;
	}

	public void setData(List<String> data) {
		this.data = data;
	}    
}
`

Related issue: #3463

**Comment by melloware** [comment]
In dialogs.js this line is definitely set in the init().
```javascript
this.jqEl = this.jq[0];
```
But when you call show() the this.jqEL is "undefined".  So something is unsetting it I just haven't figured out what.

**Comment by lagar84** [comment]
The only thing I could observe so far, is this bug have a relation to Step 1, when a non ajax postback is fired. Somehow the dom for confirmDialog is different when the same action is fired using ajax. 
If you add this button to the reproducer (after the show data button):

`<p:commandButton ajax="true" value="Show data AJAX" action="#{testView.showData}" process="@form" update="@form" />`

confirmDialog works as expected. But I really dont know why.

**Comment by melloware** [comment]
I reported this through my PRO account.  I looked at this one but its a little above my head on how to fix it.

**Comment by melloware** [comment]
@mertsincan don't forget to add the Milestone labels to this ticket!  And thanks for fixing.

**Comment by mertsincan** [comment]
You're right :))) Thanks a lot!
