### ISSUE TITLE
Delete item with backspace in AutoComplete multiple mode

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#35]
It would be really nice if there was a way to delete the last element of a p:autoComplete field, with multiple selection enabled, by pressing Backspace.

**Comment by sudheerj** [comment]
This can be done by using keup events

`if(key === keyCode.BACKSPACE){
                var selectedItems = $this.multiItemContainer.children('li.ui-autocomplete-token');
                  if(selectedItems.length > 0) {
                      selectedItems.eq(selectedItems.length-1).remove();
                  }
            }`

**Comment by sudheerj** [comment]
The PR is created at #1083
