### ISSUE TITLE
MenuItem: f:param tags ignored in combination with url attribute

### ISSUE THREAD

**Issue by leomekenkamp** [primefaces/primefaces#3507]
## 1) Environment
- PrimeFaces version: 6.2.1
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Tomcat 8.5.15
- Affected browsers: Firefox 59, IE 11, Chrome 64.0.3282.186

## 2) Expected behavior
Menu items add the information from f:param children to the link they generate when the 'url' parameter is specified.

## 3) Actual behavior
f:param is ignored for menu items with a url atribute.

## 4) Steps to reproduce
See the output of the xhtml below. Replace <some_outcome> with a known navigation outcome. 
The 'ok' button will have a href ending with "?is=added", while the 'nok' button has no parameters attached to its href.

## 5) Sample XHTML
```
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"
>
<h:head>
</h:head>
<h:body>
    <h:form>
        <p:menubar>
            <p:menuitem value="ok" outcome="<some_outcome>">
                <f:param name="is" value="added"/>
            </p:menuitem>
            <p:menuitem value="nok" url="http://localhost/foo">
                <f:param name="is" value="ignored"/>
            </p:menuitem>
        </p:menubar>
    </h:form>
</h:body>
</html>
```

## 6) Sample bean

Not applicable

## Remark
Note that adding ``includeViewParams="true"`` to the 'nok' button does not alter its rendered output.

**Comment by tandraschko** [comment]
similar to #2749

**Comment by mertsincan** [comment]
Could you please try this issue with the latest elite jar?

**Comment by melloware** [comment]
I have verified this is fixed in Elite and can be closed!
