### ISSUE TITLE
DataTable: Misaligned rows with specific font size and empty column

### ISSUE THREAD

**Issue by cbasener** [primefaces/primefaces#3508]
## 1) Environment
- PrimeFaces version: 6.2.1
- Does it work on the newest released PrimeFaces version? No, does not work with 6.2.1
- Application server + version: WildFly 11.0.0.Final
- Affected browsers: IE 11.251.16299.0, Edge 41.16299.248.0

## 2) Expected behavior

Using p:dataTable with an empty column and font size 11px should NOT misalign horizontal rows.

![edge_nbsp](https://user-images.githubusercontent.com/35636304/37722969-81563270-2d2d-11e8-801e-dd193fe8ef54.png)

## 3) Actual behavior

Using p:dataTable with an empty column and font size 11px DOES misalign horizontal rows.

![edge_empty](https://user-images.githubusercontent.com/35636304/37722975-87c9de72-2d2d-11e8-9a2d-e96954136839.png)

## 4) Steps to reproduce

Use provided XHTML and Java class.

Adding a nonbreakable space (```&#160;```) as value to the empty column seems to solve this issue.
The first screenshot was taken with this NBSP as column value.
```
            <p:column>
                &#160;
            </p:column>
```

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<f:view encoding="UTF-8" contentType="text/html">

  <h:head>
    <style>
        body { font-size: 11px; }
    </style>
  </h:head>

  <h:body>

    <h:form>
        <p:dataTable
            value="#{testController.entries}"
            var="entry">

            <p:column />

            <p:column headerText="Property1">
                #{entry.property1}
            </p:column>

            <p:column headerText="Property2">
                #{entry.property2}
            </p:column>

            <p:column headerText="Property3">
                #{entry.property3}
            </p:column>

        </p:dataTable>

    </h:form>

  </h:body>

</f:view>

</html>
```

## 6) Sample bean

```
@Model
public class TestController {

  public List<Entry> getEntries() {
    List<Entry> result = new ArrayList<>();

    Entry entry = new Entry("property1", "property2", "property3");

    for (int i = 0; i < 20; i++) {
      result.add(entry);
    }

    return result;
  }

  public static class Entry {
    private String property1;
    private String property2;
    private String property3;

    public Entry(String property1, String property2, String property3) {
      super();
      this.property1 = property1;
      this.property2 = property2;
      this.property3 = property3;
    }

    public String getProperty1() {
      return property1;
    }

    public void setProperty1(String property1) {
      this.property1 = property1;
    }

    public String getProperty2() {
      return property2;
    }

    public void setProperty2(String property2) {
      this.property2 = property2;
    }

    public String getProperty3() {
      return property3;
    }

    public void setProperty3(String property3) {
      this.property3 = property3;
    }
  }
}
```

**Comment by melloware** [comment]
I have tested this on Nova Light and newer themes and this does not happen in PF 8.0.  So the issue seems to be fixed and was theme related with older jQuery themeRoller themes.

Since a workaround has been provided I am going to close this issue.
