### ISSUE TITLE
Timeline: groupsWidth attribute not working

### ISSUE THREAD

**Issue by lucajav** [primefaces/primefaces#3509]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2.1
- Does it work on the newest released PrimeFaces version? NO Version? 6.2.1
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7.0.34
- Affected browsers: Chrome

## 2) Expected behavior
the groupsWidth attribute for timeline component should set the width of the group column

...

## 3) Actual behavior
groupsWidth attribute is not working and the browser consol shows an error related to groupsWidth 
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<p:timeline id="PN_timel" value="#{beanEsempio.model}" 
                                    var="attivita"  
                                    varGroup="group" 
                                    eventMargin="5" eventMarginAxis="0"  
                                    showMajorLabels="false" axisOnTop="true"  
                                    selectable="false" 
                                    editable="false"
                                    timeChangeable="false" 
                                    groupsChangeable="false" groupsOnRight="false" 
                                    start="#{beanEsempio.fil.start}"
                                    min="#{beanEsempio.fil.data}"
                                    max="#{beanEsempio.fil.finegg}"
                                    zoomMin="36000000" 
                                    groupsWidth="200px"
                                    widgetVar="PNtimel"
                                    zoomable="#{beanEsempio.zoomable}" 
                                    > 
                            <p:ajax event="rangechange" oncomplete="onrangechange1()" rendered="#{beanEsempio.timelineGruppo}"/>
                            <p:ajax event="rangechange" oncomplete="onrangechange3()" rendered="#{!beanEsempio.timelineGruppo}"/>
                            <p:ajax event="add" update="" listener="#{beanEsempio.preparaNuovaTime}" oncomplete="PF('PNNuovo').show()"/>  
                            <p:ajax event="edit" update="" listener="#{beanEsempio.onChangeTim}" oncomplete="PF('PNNuovo').show()"/>  
                            <p:ajax event="delete" update="" listener="#{beanEsempio.onDelete}" onstart="PF('PNtimel').cancelDelete()" oncomplete="PF('dialogCancella').show()"/>
                            <p:ajax event="change" update="@none" listener="#{beanEsempio.onChange}"/>
                            <f:facet name="group">  
                                <h:outputText value="#{group.descrizione}" style="font-weight:bold;"/>  
                            </f:facet>
                            <h:outputText value="#{attivita.descrizioneCompletaSCProg}" escape="false"/>  
                        </p:timeline>  
..

## 6) Sample bean

..

**Comment by rastislavtkac** [comment]
There is a simple typo in the TimelineRenderer class, (in version 6.2 on line 160), there is a simple quote character at the end ot the attribute name, it messes up the jquery code generated for the timeline widget.

`wb.attr("groupsWidth'", timeline.getGroupsWidth());`

sould be:

`wb.attr("groupsWidth", timeline.getGroupsWidth());`

**Comment by cnsgithub** [comment]
@rastislavtkac Thanks for the tip. Fixed this in https://github.com/primefaces/primefaces/pull/3827.
