### ISSUE TITLE
[perf] isArray() is slow

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3511]
Based on this post https://stackoverflow.com/questions/16170548/object-isarray-is-slow-is-there-a-fast-way-to-do-that

isArray() has a big cost in terms of performance _(300ms!!!! according to the post)_. It should be always the last case to try when testing eligibility. First, most of the users are using List, second it's faster to evaluate.

We might even consider implementing our own `ArrayUtils.isArray()` by testing the first character of class name. It might sound like a dirty trick, but it's not, the javadoc is quite clear about that: https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getName--
> If this class object represents a class of arrays, then the internal form of the name consists of the name of the element type preceded by one or more '[' characters representing the depth of the array nesting.

Since you guys are doing your best to improve performance (like get rid of iterator) I thought that could be useful

**Comment by tandraschko** [comment]
I don't think you can measure any difference if you change this.

**Comment by tandraschko** [comment]
If you would check the benchmark it's executed tons of times ;)

**Comment by melloware** [comment]
If you are going to add it I think org.primefaces.util.BeanUtils is the right place for this method.

**Comment by tandraschko** [comment]
I tried it by meself and all 3 checks (instanceof, checking the name, and isArray) takes 0ms for 100.000 calls after a small warmup. NN to introduce new methods.
