### ISSUE TITLE
Dialog documentation wrong

### ISSUE THREAD

**Issue by Rourke101** [primefaces/primefaces#3515]
A couple of things I think are wrong in page: https://www.primefaces.org/showcase/ui/df/basic.xhtml

```
    public void viewCars() {
        Map<String,Object> options = new HashMap<String, Object>();
        options.put("resizable", false);
        PrimeFaces.current().dialog.openDynamic("viewCars", options, null);
    }
```
Should be

```
    public void viewCars() {
        Map<String,Object> options = new HashMap<>();
        options.put("resizable", false);
        PrimeFaces.current().dialog().openDynamic("viewCars", options, null);
    }
```
Same for the other example

**Comment by tandraschko** [comment]
it's a showcase issue, please create a issue in the showcase repo and a PR ;)

**Comment by cnsgithub** [comment]
@Rourke101 What's wrong with these snippets? The only difference is that the second one uses the diamond op? :confused:

**Comment by Rourke101** [comment]
@cnsgithub No, the main issue is `dialog()`
