### ISSUE TITLE
Dynamic AbstractMenu implementations: XSS in non-ajax parameter rendering

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3516]
## 1) Environment
- PrimeFaces version: 6.3-snapshot
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: WildFly 12
- Affected browsers: n/a

## 2) Expected behavior
`f:param `in dynamic, non-ajax `AbstractMenu `implementations must be properly escaped.

## 3) Actual behavior
There is an XSS vulnerability due to missing escaping. 

Potentially affected components:
![image](https://user-images.githubusercontent.com/13161711/37815520-749c5c56-2e6f-11e8-9dbf-747fe477bce9.png)

## 4) Steps to reproduce
- Add the `f:param `tag as shown below to the dynamic `p:menu` in showcase: http://localhost:8080/showcase/ui/menu/menu.xhtml
- Click at 'Delete'
- JS alert will be shown

## 5) Sample XHTML
```xml
            <p:menu model="#{menuView.model}">
                <f:param name="param" value="value'});alert('XSS');//" />
            </p:menu>
```

## 6) Sample bean
as in showcase

## 7) Mitigation
PR will follow. @tandraschko Could you please add the security label? Thanks.

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3518

**Comment by kukel** [comment]
@cnsgithub: Wow... I have so much appreciation for you work... Thanks!. But wouldn't it be better to have all these xss issues in a 'private' issuelist so they are not disclosed before a fix has been made?

**Comment by cnsgithub** [comment]
@kukel Thanks. And sorry for posting another one [here](https://github.com/primefaces/primefaces/issues/3520) without having read your comment. I largely agree. But what would be your proposed solution? I don't know/have any 'private' issue trackers.
