### ISSUE TITLE
XSS despite using ComponentUtils.escapeText

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3520]
## 1) Environment
- PrimeFaces version: 6.3-snapshot
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: n/a
- Affected browsers: n/a

## 2) Expected behavior
Developers can rely on `ComponentUtils.escapeText` to properly escape JS.

## 3) Actual behavior
Unfortunately, `ComponentUtils.escapeText `is just for escaping JSON values as already denoted here two years ago: https://github.com/primefaces/primefaces/issues/1194#issuecomment-192155762

Escaping for JSON and JS contexts is similar but obviously not totally identical. Whereas in JS single quotes may also be used for strings, JSON strings must use double quotes, see https://www.json.org/. 

Currently, the big problem is that `escapeText `is used and spread all over the PrimeFaces java sources. And that developers rely on this functioning as a fully secure JS escaper. However, that's wrong.

## 4) Steps to reproduce
This is just one example, there are probably various locations that are vulnerable, too.

Include and click a button in the showcase http://localhost:8080/showcase/ui/button/button.xhtml like shown in 5). 

There will be a console log despite escaping in `ButtonRenderer` (which I previously tried to fix in https://github.com/primefaces/primefaces/issues/3213 and now turned out to be insufficient).

Another susceptible location might be in `CoreRenderer.buildNonAjaxRequest`.

## 5) Sample XHTML
`        <p:button href="');console.log('XSS');window.open('" />`

## 6) Sample bean
n/a

## 7) Mitigation
- Short term: Identify all vulnerable locations, i.e. locations that construct JS using single quotes and make use of `ComponentUtils.escapeText`. In those locations replace single by double quotes. And/or include escaping of single quotes in `ComponentUtils.escapeText` (this might however break valid JSON).
- Long term: Replace all `escape*` methods with appropriate variants from https://github.com/OWASP/owasp-java-encoder. Sensitize developers to proper escaping. Once again: different contexts need different encodings.

**Comment by melloware** [comment]
@cnsgithub I like where you are going with this but here is what I propose and maybe @tandraschko or @mertsincan have different ideas

1. Rather than bring in the OWASP dependency we copy the classes (only 16 of them) into .encoder package in PF.  This code was last updated 1 year ago so its not likes its getting daily updates that we need to keep up with. (trying to keep with PrimeTek's goal of a standalone JAR)

2. In ComponentUtils, XmlUtils etc we replace the encodeText etc calls with the proper Encoder.encodeJavaScript() etc.  We mark those called "deprecated" for a new EscapeUtils that just had the methods we need like encodeEcmaScript, encodeJson, encodeHtml, and encodeXml in it.

3. Then find every place those ComponentUtils methods or XML utils methods are being called and evaluate IF the correct escaping is being done there.

That will set PF up for the future as well. Thoughts?

**Comment by cnsgithub** [comment]
@melloware I agree, OWASP encoding rarely changes and to not get in conflict with PrimeTek's dependency rules it would be okay to take copies of the classes under BSD-3. I also agree with points 2 and 3. I'll start with copying the OWASP classes. Then we'll see further.

**Comment by cnsgithub** [comment]
And btw, @tandraschko could you please add the security label? I hope not to overstretch your index finger... :wink:

**Comment by cnsgithub** [comment]
Reviews for https://github.com/primefaces/primefaces/pull/3525 are very welcome.

**Comment by melloware** [comment]
I made a couple of comments let me know what you guys think. But overall I think this will be a huge improvement for PF going forward for security.

**Comment by augustd** [comment]
Is the fix for this issue in one of the 6.2.x minor versions available on the [Primefaces.org downloads page](https://www.primefaces.org/downloads/) if you purchase support? I see this is tagged as part of the 6.3 milestone, but curious if this is anywhere in 6.2.

**Comment by melloware** [comment]
No this is going to be in the 7.0 release.  If you need it now 7.0.RC3 is available in the PrimeFaces maven repo and will be released shortly as 7.0 final.

**Comment by augustd** [comment]
Thanks! Does that guidance also apply to #3469?
