### ISSUE TITLE
PF 6.2 mobile defects - autocomplete, modal, growl, dialog, checkboxmenu, datalist

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#3521]
I know mobile will be removed and in 6.2 marked as deprecated. But this "deprecated" is more like a showstopper and most component's do not work anymore.

I downloaded PF 6.2 and checked my mobile application which does not work due to a lot of defects and then I checked out the showcase where same defects are present. In firebug i don't see any errors.

## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: Glassfish 4.1 or 5.0 + Mojarra 2.3.2
- Affected browsers: IE, Firefox tested.

## 2) Expected behavior

- should work like in 6.1

## 3) Actual behavior

Most errors are bound to modal / dialog / growl effects which only work once.

All defects visible in showcase:

- autocomplete showcase ajax works only once
- growl example only works once, message is not closable on click on x - (click button _save_ twice)
- checkboxmenu is not closable (weird styling)
- dialog works only once  1. open with click on button _show_, 2. close with click on x, 3. try to open again
- datalist ajax pagination and select is broken

In my application:

I cannot close growl and dialog anymore clicking the x icon. The dialog is also not closable using _oncomplete="PF('dlgWidgetVar').hide();"_.

## 4) Steps to reproduce

See showcase.

**Comment by tandraschko** [comment]
Mobile has already been removed, so this ticket is invalid in the community issue tracker.

**Comment by Lms24** [comment]
I am aware that the issue is closed but would still second it as it would allow us a bit of extra time to migrate our application to the default PF until 6.3 without compromising our apps' security by staying on 6.1.

**Comment by cnsgithub** [comment]
I also recommend to invest some time and migrate your mobile app to regular primefaces (e.g using CSS Grid). It's not even that hard, just remove all <pm: and the renderkit one after another.

As djmj noted PF Mobile was quite buggy to begin with, and to be honest it never worked as good as the regular primefaces renderkit.

**Comment by tandraschko** [comment]
@lms24 This is a issue tracker for the community version, mobile doesn't exist here anymore. You can still get fixed by PrimeFaces PRO/Elite for 6.2.

**Comment by djmj** [comment]
@tandraschko I requested a Quote by e-mail to contact@primetek.com.tr to get a elite release fix, but did not received an answer yet.

**Comment by VsevolodGolovanov** [comment]
PF 6.2 updated to jQuery 3, which the latest existing jQuery Mobile stable release 1.4.5 doesn't support. PF Elite 6.2.30 doesn't fix this - e.g. the dialog hiding issue is still there. So PF Mobile is not just deprecated in 6.2 - it's broken.
Replacing jquery-mobile.js with a version based on 1.5.0-rc1 seems to fix at least the dialog hiding issue. [jquery-mobile.zip](https://github.com/primefaces/primefaces/files/8067590/jquery-mobile.zip) - just put it in your JSF resources at primefaces/mobile.

**Comment by melloware** [comment]
@VsevolodGolovanov the user @djmj has forked PF Mobile and keeps it alive and updated here:  https://github.com/djmj/primefaces-mobile

**Comment by djmj** [comment]
Yes and if you cannot update to PrimeFaces 7 or greater you can use PrimeFaces 6.1 branch where mobile was still working.
