### ISSUE TITLE
Schedule: additional year view

### ISSUE THREAD

**Issue by RueKow** [primefaces/primefaces#3522]
1) Environment
PrimeFaces version: 6.2
Does it work on the newest released PrimeFaces version? No
Application server + version: Tomcat 8.5
Affected browsers: all

2) Expected behavior
new button "Year" (Year-Month-Week-Day) for selecting a year view with 12 months

3) Actual behavior
no year view available

4) Steps to reproduce
see showcase

5) Sample XHTML
...

6) Sample bean
..

**Comment by AzharMobeen** [comment]
Yes, We really need it, Please changed default view from "Month,Week,Day" to "Year,Month,Week,Day".
a lot PF UI users wants this feature.

**Comment by melloware** [comment]
Looks like this would need an additional user built plugin to FullCalendar to make it work: https://stackoverflow.com/questions/10949486/year-view-in-fullcalendar-jquery-plugin

**Comment by melloware** [comment]
Looks like its a not implemented feature of FullCalendar:
https://github.com/fullcalendar/fullcalendar/issues/1140

Will close this ticket as we can't implement it until FullCalendar does. You can use this Native JS Widget for Years which looks really cool:
https://github.com/year-calendar/js-year-calendar/
