### ISSUE TITLE
CheckboxMenu: Add ui-state-active CSS class to if value selected

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#3528]
PrimeFaces: 6.2
Server: Glassfish 5
JSF: Mojarra 2.3.2

User has no visible feedback if an option was selected in default mode.

In this mode the css class ui-state-active could be applied to the component.

**Comment by tandraschko** [comment]
You should already know that we need a example (or link to the showcase) and steps to reproduce. Please edit or it will be closed.
