### ISSUE TITLE
CheckboxMenu: multiple and group displays wrong labels

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#3529]
PrimeFaces: 6.2
Server: Glassfish 5
JSF: Mojarra 2.3.2

When multiple and option groups are used the labels are taken from the option group and not the value itself. See following image:

https://i.imgur.com/ZWOcZbl.jpg

**Comment by tandraschko** [comment]
You should already know that we need a example. Please edit or it will be closed.
