### ISSUE TITLE
SelectOneMenu layout broken in showcase

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#353]
Could you check it @cagataycivici? Maybe it's related to the responsive changes

http://primefaces.org/showcase/ui/misc/defaultCommand.xhtml
or
http://primefaces.org/showcase/ui/input/oneMenu.xhtml

FF 38

**Comment by mertsincan** [comment]
Thanks Thomas. This issue is fixed for 5.2.4.

**Comment by tandraschko** [comment]
Thanks Mert!

**Comment by cagataycivici** [comment]
I fixed it yesterday.
