### ISSUE TITLE
WidgetBuilder generates likely broken scripts for non-ajax postbacks

### ISSUE THREAD

**Issue by leomekenkamp** [primefaces/primefaces#3530]
## 1) Environment
- PrimeFaces version: 6.2.1
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Tomcat 8.5.15
- Affected browsers: Firefox 59, IE 11, Chrome65.0.3325.181

## 2) Expected behavior
The popup panel of the ColumnToggler always shows names of columns with a checkbox for the table it references.

## 3) Actual behavior
After a full POST, the popup panel of the ColumnToggler is empty.
..

## 4) Steps to reproduce
- Run the xhtml sample below.
- Click on 'toggle columns': the names of all four columns are in the popup, together with a checkbox.
- Click on 'post' and wait for the page to be loaded.
- Click on 'toggle columns': the popup is empty.

## 5) Sample XHTML
```
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"
>
<h:head>
</h:head>
<h:body>
    <h:form>
        <p:dataTable id="table">
            <f:facet name="header">
                <p:commandButton id="columnToggler" value="toggle columns"/>
                <p:columnToggler trigger="columnToggler" datasource="table"/>
            </f:facet>

            <p:column headerText="one">
            </p:column>
            <p:column headerText="two">
            </p:column>
            <p:column headerText="three">
            </p:column>
            <p:column headerText="four">
            </p:column>
        </p:dataTable>
        <p:commandButton value="post" ajax="false"/>
    </h:form>
</h:body>
</html>
```

## 6) Sample bean
Not applicable.

## Remarks
Looking at the differences in html page sources, it is obvious that the erroneous POST-screen lacks `$(function(){ /* ... */ })`. Class `org.primefaces.util.WidgetBuilder` has a method `WidgetBuilder initWithDomReady(String, String, String)` that adds this Javascript indirection, but not if `facesContext.isPostback()`. IMHO this check should be removed.

Issue https://github.com/primefaces/primefaces/issues/2888 also seems related to this: if `MOVE_SCRIPTS_TO_BOTTOM` is activated, it would also trigger this bug.

## Update
This issue is definitively related to #2888. If I add
```
    <context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```
to `web.xml` (or in my case `web-fragment.xml`, the popup is filled as expected. So it seems one can use `MOVE_SCRIPTS_TO_BOTTOM` as a workaround / mitigation for this issue.

**Comment by tandraschko** [comment]
Yep, the problem is that we check for postbacks but not for ajax requests...
