### ISSUE TITLE
[DataTable] scrollable, missaligned thead_clone

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#3532]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No, 6.2
- Application server + version:
- Affected browsers: IE11, Firefox

## 2) Expected behavior
Header columns and body columns should be aligned when data table is scrollable

## 3) Actual behavior
Header and body is missaligned by around 21px

## 4) Steps to reproduce
Our layout uses `box-sizing:border-box` for all elements. A bugfix for the datatable cloned the width of the header to the width of the body. But it used the jQuery method `width()` for this. 

In our case `outerWidth()` is the better function. Maybe this is also the general solution to this problem?

**Comment by tandraschko** [comment]
No example -> invalid
