### ISSUE TITLE
Showcases for Java EE 7/8 with CDI 

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#3534]
Showcase examples should be adapted to state of the art Java/Jakarta EE. The use of CDI is commonly aggreed as superior and best practice long ago (e.g. [1](https://stackoverflow.com/questions/4347374/backing-beans-managedbean-or-cdi-beans-named), [2](https://stackoverflow.com/questions/2930889/are-managedbeans-obsolete-in-javaee6-because-of-named-in-cdi-weld)). Of course, backward compatibility is still necessary, but we should have modern examples available. Java EE 6 was published 2009 (now JEE 8). I think it's time to move.

Some examples could be written much easier without managed beans at all, just using newer EL standards (e.g. list creation). Current examples actually lead developers into the wrong directions.

May be its helpful to know, which JEE-Standard is necessary, to run certain examples and have a litte note. An other idea could be, to use state of the art (CDI) examples, while still offering the older versions. May be, you could add the possibility for users to add examples for components.

**Comment by melloware** [comment]
Agreed I tried to do it with PFE Showcase howver Jetty Maven plugin right now has an issue with it automatically includes CDI 1.0 which collides with trying to use EE7/8 needing CDI 1.1 or 1.2.

https://github.com/eclipse/jetty.project/issues/2080

I am waiting until Maven Jetty 9.4.9 plugin is released and then we can do this.

**Comment by tandraschko** [comment]
We also have spring users and the ManagedBean API is more neutral as CDI in that case.
Also i dont see a big benefit in switching to CDI. We just use ManagedBean and ManagedProperty. And we can simply use new EL features.
Note: i'm a big CDI fan and commiter of a Impl.

**Comment by mdzaebel** [comment]
Why not support modern Spring examples too. While Spring and CDI could live in harmony it would be a better user experience to have more suitable and shorter examples at your fingertips. This work has to be done anyway as JSF Managed Beans are deprecated since JSF 2.3 ([Issue26](https://github.com/primefaces/showcase/issues/26)). However, I can't estimate benefit/cost analysis and must admit, that it's still not urgent as your showcases are really excellent, clear and easy to understand.

**Comment by tandraschko** [comment]
We also still have many many JSF 2.0-2.2 users, so i would stick with ManagedBeans till JavaEE9 / JSF 3.0.

**Comment by melloware** [comment]
Shouldn't this ticket be in the Showcase project? https://github.com/primefaces/showcase/issues

**Comment by tandraschko** [comment]
Yep, good point :D Will close it here.
