### ISSUE TITLE
The confirm dilog box not working

### ISSUE THREAD

**Issue by akhilbabu** [primefaces/primefaces#3539]
in prime-faces 6.2  the confirm dialog box not coming up when taking from menu.but after any other action like refresh ,the dialog box start working.Its working when i change version of prime-faces in to 6.1
## 1) Environment
- Prime-faces version:6.2
-Not working on newest version but in 6.1
- Application server + version:glass-fish :4 
- Affected browsers:All

## 2) Expected behavior
confirm dialog pop up
...

## 3) Actual behavior
confirm dialog box popup not showing on clicking action
..

## 4) Steps to reproduce
1)open any  new page which having confirm dialog box on click.(like delete action)
2)click on the action 
.. 

## 5) Sample XHTML

<p:commandLink id="delete_button">
					<p:confirm
						header="confirm"
						message="are you sure?"
						icon="ui-icon-alert" />
					<p:graphicImage library="test"
						name="images/delete.png" />
				</p:commandLink>

<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
					<p:commandButton
						value="yes"
						type="submit" ajax="true" 
						update="table"
						action="#{bean.deleteSelected()}"
						styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
					<p:commandButton
						value="no"
						type="submit" styleClass="ui-confirmdialog-no"
						icon="ui-icon-close" />
				</p:confirmDialog>
..

## 6) Sample bean

public void deleteSelected()
	{
		if (selectionList != null && !selectionList.isEmpty())
		{
			acees.deleteSelectedFromList(selectionList);
		}
	}

**Comment by melloware** [comment]
I think this has been fixed by: https://github.com/primefaces/primefaces/issues/3498

**Comment by tandraschko** [comment]
Do you get a JS error in the console? If yes, it should be fixed.

**Comment by akhilbabu** [comment]
No jsf error  in console

**Comment by tandraschko** [comment]
JS = javascript ;)

**Comment by akhilbabu** [comment]
sorry for that:
an error coming like this> TypeError: this.jqEl is undefined[Learn More]

**Comment by tandraschko** [comment]
Yep, then it's the same bug and already fixed.

**Comment by akhilbabu** [comment]
how can i fix it in my project ? i am using like this  compile 'org.primefaces:primefaces:6.2'

**Comment by tandraschko** [comment]
You can build by source or overwrite the renderer (use google for this), here is the diff: https://github.com/primefaces/primefaces/commit/9f86efba16ead70f9db1194744d291a7f64acefb

**Comment by alailson** [comment]
In the web.xml file:
&lt;context-param&gt;
        &lt;param-name&gt;primefaces.MOVE_SCRIPTS_TO_BOTTOM&lt;/param-name&gt;
        &lt;param-value&gt;true&lt;/param-value>
    &lt;/context-param&gt;
It worked for me.

**Comment by akhilbabu** [comment]
solved untill 6.3

    "compile files('primefaces-6.2.jar') " (latest jar)   instead of  "compile 'org.primefaces:primefaces:6.2' "

**Comment by markwong** [comment]
alailson's workaround works.
