### ISSUE TITLE
Remove CoreRenderer

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3542]
Lately, I was having a look to CoreRenderer and realized it's more an utility than a Renderer per say. I'll go straight to the point, but what about moving all methods in RendererUtils, and delete CoreRenderer?

> Thomas Andraschko
> +0
> moving to a util makes nothing better
> You would have a SelectRendererUtils instead of SelectRenderer...

> Sébastien Lepage
> Well, first it gives less complexity to the class hierarchy. Second, let's say I'm creating a custom Renderer which already inherits from something, I can't reuse utility method of CoreRenderer, only choice I'll have left is copy/paste. SelectRendererUtils? CheckRendererUtils (which btw is RendererUtils)? I don't know... why not? Or put everything in RendererUtils... Another reason is, when I read a class I expect some of these method to be used as Template Method pattern, but none of these are, which is kind of confusing... it's not when you realized that, these methods are utils and not instance based. Last reason is, on a performance level it might have a difference, since the method is not related to an object but a class, i won't put my money it, but it might be faster. Saying all this, I think it will be better to remove CoreRenderer and move these methods in RendererUtils

> Thomas Andraschko
> For me there is no reason as

> - all of our component renderers inherit from CoreRenderer
> - there is no performance difference
> - we already have soo many utils, i prefer inheritance
> 
> but lets talk later, i currently don't have time to do big refactorings
> maybe in ~2 months
> as i said, i currently don't like that much utils and with the escaping stuff, they get even more

> Sébastien Lepage
> - all of our component renderers inherit from CoreRenderer: IMO, this is actually a design mistake
> - there is no performance difference, it won't make 5x faster sure, but I'm not an export in memory allocation either so I can't really argue
> - we already have soo many utils, i prefer inheritance: I don't think this is a good reason to not doing it, if it makes more sense to be static method so be it. Number of utils shouldn't be a problem as long their responsability are well defined

**Comment by melloware** [comment]
I think I am with @tandraschko on this one. Not enough "bang for the buck" for me to endorse doing this without a good refactoring reason.

**Comment by Rapster** [comment]
I understand what you're saying, but my concern is about code quality, and this might be big. Probably minor to some other things but it deserves some attention, as I said to Thomas, I'm quite curious about performance as well, I have to investigate on this...

**Comment by tandraschko** [comment]
There is no measureable performance difference! ;)

**Comment by Rapster** [comment]
How can you be so sure? My ears are wide opened regarding instance method vs static method memory allocation and time execution. I don't find clear answers regarding this topic, so if you can enlight me on this, i'll be glad to ear it :wink:

**Comment by tandraschko** [comment]
Just try it by yourself.
And performance is absolutely NO GO for refactoring something. The difference is not measurable in a single request, it will even be not measurable in 100 requests. Everything else is factor 1000 slower as moving all to static methods...

**Comment by Rapster** [comment]
I prefer to read articles regarding this than running a benchmark that have a lot of change to be wrong... So many examples and counter-examples on satckoverflow :D 

On a general note, performance is definitely a good reason to refactor, specially for a framework like PF, proof is, iterator loop vs index loop, you're doing it! _(and let's be honest, if we were meant to change intance methods calls into static calls, it's quick, easy and transparent for the users, unless they have custom components using these methods, but even that, it's not a big deal)_

> Everything else is factor 1000 slower as moving all to static methods...

How did you come up with such result?

Anyway, as I said, performance is not my first concern regarding this ticket, it's code quality :wink:

**Comment by tandraschko** [comment]
As i already said, i currently don't see any reason to do it. Using inheritance is currently the better way with better quality.

**Comment by melloware** [comment]
The problem with Static Utility calls vs instance methods its makes things harder to mock and unit test.

**Comment by Rapster** [comment]
Yeah I know, that's what I thought but looks like doable now http://www.baeldung.com/intro-to-powermock

**Comment by melloware** [comment]
It's definitely doable but I have found avoiding PowerMock and PowerMockito should be done at all costs unless using it to test a legacy library that you can't control.

> If you can avoid it, do; PowerMock is basically only for tests that interact with badly designed code that you can't change. But sometimes you need to depend on a badly designed library, in which case having a somewhat cumbersome way to mock it is better than nothing.

https://news.ycombinator.com/item?id=8775233

**Comment by Rapster** [comment]
Even though I'm convinced this is the way to go, I'll close it since the team is not up for it
