### ISSUE TITLE
TreeDragDropEvent : incorrect dropIndex value when using drag and drop between sibling nodes

### ISSUE THREAD

**Issue by LoloBeubeu** [primefaces/primefaces#3543]
# Description

When trying to move a node between itself and the next sibling, the dropIndex value returned by DragDropEvent seems to be wrong and should be decreased by 1.

This issue can be seen in this Showcase example : https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml

- if I move "Node 0" on top (which already is), "Node 0" doesn't move and dropIndex = 0
- if I move "Node 0" between "Node 0" and "Node 1", "Node 0" doesn't move and dropIndex = 1
- if I move "Node 0" between "Node 1" and "Node 2", "Node 0" moves between "Node 1" and "Node 2" and dropIndex = 1
- if I move "Node 0" to the bottom, "Node 0" moves after "Node 2" and dropIndex = 2

Maybe it is not a bug, but I can't understand this behaviour.

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? Same problem in 6.3-SNAPSHOT ( last commit c82fae5ffb7956432c3cce21978b7dd1ab37e03d )
- Does it work on the newest sources in GitHub? No
- Affected browsers: tested with latest linux versions of Firefox and Google Chrome

## 2) Expected behavior

When moving a node between itself and the next node, dropIndex should return the final position of the node (0 in above example).

It would enable to get from Java code the actual position of dragNode and to distinguish the cases where a node is moved before the next and where a node is moved after the next.

## 3) Actual behavior

When moving a node between itself and the next node, dropIndex doesn't return the final position of the node (0 in above example).

## 4) Steps to reproduce

(see description and showcase example)

## 5) Some investigation

dropIndex value comes from ajax request param "dndIndex", which is defined in tree.js. Its value seems to be defined as `dropPoint.prevAll('li.ui-treenode').length` (every node `<li class="ui-treenode ...">` before drop point) 

It seems to have something to do with the fact that dropping a node just before or after itself is invalidated by `validateDropPoint` function. In that case, the original node `<li class="ui-treenode">` is not removed from DOM. Then, when dropping a node after itself, dropIndex also counts the original node.

**Comment by melloware** [comment]
Fixed with PR: https://github.com/primefaces/primefaces/pull/4809
