### ISSUE TITLE
Provide Selenium extension/support 

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3544]
Since Primefaces doesn't produce the same HTML as plain JSF or other JSF implementations, Selenium tests need to figure out how to retrieve text from and check attributes of child elements. I'd be nice if accessing PrimeFaces elements in Selenium Java test would be as easy as

    @org.primefaces.FindBy(id="someid")
    private Messages messages;
    ...
    @org.junit.Test
    public void test() {
        assertTrue(messages.containsMessage("summary", "detail"));
        assertEquals(1, messages.getMessageCount());
    }

instead of accessing the children of the `FindBy(id="someid") WebElement messages` with an XPath and testing the other condition demontrated above (a lot of others come to mind) with complex element queries and assertions.

    @org.primefaces.FindBy(id="someid2")
    private SelectOneButton selectOneButton;
    ...
    @org.junit.Test
    public void test() {
        selectOneButton.selectOption(1);
    }

could have spared me the 3 pages stackoverflow question as well as 100 reputation, since

    @FindBy(xpath = "id('mainForm:mainSelectOneButtonPrime:0')/../span")
    private WebElement selectOneButtonOption0;

is definitely not intuitive if not the opposite (see https://stackoverflow.com/questions/47106401/why-can-i-click-an-input-with-type-radio-of-a-hselectoneradio-but-not-one-of-a for details).

The use of custom `@FindBy` is just an idea. Selenium offers extension capabilities.

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No (there seem to be no plans for any similar or this feature)
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) probably not
- Application server + version: Payara 4.1.2.181
- Affected browsers: all

## 2) Expected behavior

Be able to use PrimeFaces component in Selenium texts through a component specific interface (e.g. `p:selectOneButton` needs a method to select one option programmatically, `p:messages` need to be able to check whether a message has been added with one command. "Don't make me think".

## 3) Actual behavior

Information has to be accessed via complex XPath and CSS accessors, mostly by asking stackoverflow.com questions.

## 4) Steps to reproduce

Any component alone on the page.

## 5) Sample XHTML

Any component alone on the page.

## 6) Sample bean

Any component alone on the page.

**Comment by tandraschko** [comment]
I would use Selenide, which provides jquery like selectors.
Also i don't like to use the component classes in tests. (UPDATE: i think you mean a helper class "SelectOneButton", not the component itself)

I think the best way is to work on it with the primefaces-extensions teams. Later we can still merge it into PF if it has been implemented well.

**Comment by krichter722** [comment]
Relevant stackoverflow.com querstions which might serve as a workaround before such an extension exists as well as base for the implementation:

   * https://stackoverflow.com/questions/46765542/how-to-access-primefaces-components-through-graphene-in-the-most-portable-way
  * https://stackoverflow.com/questions/47106401/why-can-i-click-an-input-with-type-radio-of-a-hselectoneradio-but-not-one-of-a
  * https://stackoverflow.com/questions/49610161/how-to-check-a-pselectbooleancheckbox-and-wait-for-it-to-be-checked-in-graphene

**Comment by BalusC** [comment]
This can get you started: https://github.com/omnifaces/arquillian-primefaces

**Comment by melloware** [comment]
@BalusC that is very very cool.

**Comment by tandraschko** [comment]
I'm also working on something similar currently at my company.
If it's ready, i will make it open source and provide support for ~10 components.
Community can enhance it then.

**Comment by krichter722** [comment]
@tandraschko Wouldn't it make more sense to work on the existing https://github.com/omnifaces/arquillian-primefaces? It provides a large set of support already. Starting a separate project seems to re-invent parts of the wheel.

I'm closing this since the problem is solved with arquillian-primefaces for me.

**Comment by tandraschko** [comment]
The usage is completely different
OmniFaces just provides some helper methods
our code is more like your idea
@FindBy(id=)
private CommandButton button;

**Comment by krichter722** [comment]
@tandraschko Ah, great! Looking forward to it. Then I'll reopen the issue and let you close it with a commit message or manually.

**Comment by tandraschko** [comment]
We can also close it :D
i think i will add the prototype in PFE and then lets review and talk about the future of it.

**Comment by tandraschko** [comment]
Very early prototyepe incl test project: https://github.com/tandraschko/primefaces-arquillian

**Comment by tandraschko** [comment]
@krichter722 update: https://github.com/primefaces-extensions/primefaces-arquillian
