### ISSUE TITLE
Calendar: on dialog with scrollable background is broken

### ISSUE THREAD

**Issue by professorxuk** [primefaces/primefaces#3545]
## 1) Environment
- PrimeFaces version: 6.2
works ok on PF <= 6.1

## 2) Expected behavior
Calendar popup should be bound to the input control 

## 3) Actual behavior
Calendar popup is positioned relatice to the scrolled background window e.g. when at top of window the popup is correct, but on scrolling down the popup is too low. Scrolling down a bit more the popup is no longer visible.

## 4) Steps to reproduce
Calendar placed in p:dialog when another p:dialog is shown

## 5) Sample XHTML
`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        
        <h1>#{testView.testString}</h1>
        
        <ui:fragment>
        	<p:dialog id="d1" showEffect="fade" hideEffect="fade"
			          widgetVar="d1DialogBox" modal="true" width="720"
			          visible="true" style="position:static;overflow:scroll;">
        		<div>Calendar 1</div>
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a        		
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>b
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
        		<br/>a
				<p:calendar id="a" navigator="true" pattern="dd/MM/yyyy" readonlyInput="true">
				</p:calendar>
			</p:dialog>        
        	<p:dialog id="d2" showEffect="fade" hideEffect="fade"
			          widgetVar="d2DialogBox" modal="true" width="420" visible="true"
			           >
			    <div>Calendar 2</div>
				<p:calendar id="b" navigator="true" pattern="dd/MM/yyyy" readonlyInput="true">
				</p:calendar>
			</p:dialog>
        </ui:fragment>
    </h:body>
</html>`

The above is based on the template repo https://github.com/primefaces/primefaces-test

## 6) Sample bean

see fork https://github.com/professorxuk/primefaces-test

**Comment by melloware** [comment]
I had reported something similar before they fixed.  This must be a different flavor of it..  https://github.com/primefaces/primefaces/issues/2271

**Comment by professorxuk** [comment]
I have to admit this issue might duplicate https://github.com/primefaces/primefaces/issues/3423 We only use community versions sadly.
Hopefully my xhtml sample will help narrow down a solution. I guess this could be related to the adoption of jquery 3. As a temporary workaround we might switch to p:overlayPanel rather than p:dialog.

**Comment by melloware** [comment]
You are right that ticket looks like it is related to this one.

**Comment by professorxuk** [comment]
I see that PF 6.2 now has jquery.ui.pfextensions.js which does some datepicker re-positioning. Being very inexperienced in jquery's datepicker code let alone PF's customisation I'm not much help I'm afraid. Maybe https://github.com/tandraschko can help?

**Comment by tandraschko** [comment]
I just did a major major refactoring how we handle our javascripts. Everything was in 1 big big file. I just did a splitup and moved our modified code to the jquery.ui.pfextensions.js.
Maybe could debug if the methods are called.

**Comment by mertsincan** [comment]
Could you please try position: absolute instead of position: static?
```
<p:dialog id="d1" showEffect="fade" hideEffect="fade"
                      widgetVar="d1DialogBox" modal="true" width="720"
                      visible="true" style="position:absolute; overflow:scroll;">
```

**Comment by melloware** [comment]
@professorxuk can you try this with 6.3-SNAPSHOT.  I can't reproduce your issue with your test case.  The Calendar opens correctly next to the input.

You must first build PF 6.3-SNAPSHOT ...
```
git clone https://github.com/primefaces/primefaces.git
cd primefaces
mvn clean install
```

I believe it may have been fixed by: https://github.com/primefaces/primefaces/issues/4295

**Comment by melloware** [comment]
@tandraschko Can you review this and mark it 6.3 and close it?
