### ISSUE TITLE
selectOneMenu : disabled on using placeholder

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3547]
Reported By PRO User;
> We are using p:selectOneMenu with placeholder option.
> We noticed that, ui-state-disabled is added when placeholder is present which makes it look disabled.
ex:
```
        <p:selectOneMenu id="console" value="" style="width:125px" placeholder="Select One">
            <f:selectItem itemLabel="" itemValue="" />
            <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
            <f:selectItem itemLabel="PS4" itemValue="PS4" />
            <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
        </p:selectOneMenu>
```

**Comment by jajajaja** [comment]
Hello,

With this fix it is impossible from CSS to address component state without selection. For example if I want to display placeholder with different style. 

I suggest to add additional class like 'ui-state-no-selection' instead of removing line with 'ui-state-disabled'
