### ISSUE TITLE
p:chart tickOptions angle is quoted

### ISSUE THREAD

**Issue by niblings** [primefaces/primefaces#355]
jqplot rendering result is the difference
angle : "0"
  and
angle: 0 

"0" is not centering tick label
0 is centering tick label

In the current version
org.primefaces.component.chart/renderer.CartesianPlotRenderer.java

```
:
writer.write("angle:\"" + tickAngle+ "\"");
:
```

In older versions of PrimeFaces

```
if(tickAngle != 0) writer.write(",tickOptions:{angle:" + tickAngle + "}"); 
```

**Comment by cagataycivici** [comment]
So it should be without quotes right? @mertsincan Can you work on it?

**Comment by cagataycivici** [comment]
Taking ownership.
