### ISSUE TITLE
DataTable: Multiselection with shift-click doesn't work after update

### ISSUE THREAD

**Issue by jthalmai** [primefaces/primefaces#3551]
## 1) Environment
- PrimeFaces version: **6.2**
- Does it work on the newest released PrimeFaces version? **No - 6.2**
- Application server + version: **WildFly 12.0**
- Affected browsers: **Firefox**

## 2) Expected behavior

After clicking entry a) of the datatable and then shift-clicking a second entry b), all entries from a) to b) should be selected, even if the DataTable has bean updated in the meantime.

## 3) Actual behavior

After first click, entry a) is selected.
After updating the DataTable, still a) is selected, this is OK.
But after shift-clicking b), all entries from the first row to b) are selected.

## 4) Steps to reproduce

With the example, select one entry, wait a second, then shift-select another entry

## 5) Sample XHTML

Just use the "Multiple with Meta and Shift keys" example from:
https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

and add the following line to make it update the DataTable, this issue is not just related to the <p:poll> component, it could also be updated with a button or anything else: 
`<p:poll interval="1" update="multipleDT"/>`

**Comment by tandraschko** [comment]
It will be hard to solve this issue.
A update on the dataTable means that the whole table is re-rendered, so the client-side state is lost.

It will be probably a won't fix.

**Comment by jthalmai** [comment]
Well, thank you anyway for the quick response.

**Comment by tandraschko** [comment]
It's not that i don't like to fix that but it's quite a big "new feature" to remember such client-side state. I think you could sponsor it via PrimeFaces PRO, i don't like to touch the DataTable as opensource-committer and also the effort is to big for me.

**Comment by kukel** [comment]
I think it could/can be fixed and the problem might 'just' be that the first click IS remembered in the server (and rendered as such on the client after an update) and it should in that case also be set as the first selection when doing a multi-select. The problem will then be to remember the LAST selected one. Could be fairly easily done in a cookie. Thing is what to do if the originally selected one is on a different page after updating... Then setting it to the first as is done now would be correct I think.

**Comment by tandraschko** [comment]
It can also easily done with a storing it a global PF "store" or just use html5 localstorage e.g.

**Comment by tandraschko** [comment]
But we should think about that: why is it required to update the whole table? Shouldn't it be possible to update the values or whats the actual usecase?

**Comment by kukel** [comment]
True... But since PF uses cookies for several comparable things... Usecase: a live log viewer where you are selecting things that need 'removal'. What is unfortunate is that PF (and even the JSF core in Mojarra if I remember correctly) does not make 'inserting' **new** elements (html data)  in a component possible or deleting them but required the full component to be updated: https://stackoverflow.com/questions/24671911/what-jsf-components-allow-for-insert-in-the-partial-ajax-update. At least the datatable, and certainly the tabView would benefit from this. I wrote a 'hack' once that made it possible for the datatable by abusing things, just like (iirc) the progressBar abuses this.

**Comment by tandraschko** [comment]
In generell it's possible via the JSF API to add new elements or remove single elements, however, as you said, it's not used.
The problem it that it would be very time consuming to write something for each component. 

The lifecycle for such components is just to complex. Even if you update data, you would also need in some cases wo refresh some JS selectors variables inside the widget e.g.

Thats IMO the biggest problems for server-side frameworks.

**Comment by kukel** [comment]
> The problem it that it would be very time consuming to write something for each component.

I'm not talking about **every** component but the ones where it makes a real difference (adding/deleting a tab, adding/deleting a row in the datatable). The amount of effort for the tabView adding a tab is not that high (would even be more simple if Mojarra just implemented the insert instead of update). And deleting is even more simple. 

> Even if you update data, you would also need in some cases wo refresh some JS selectors variables inside the widget e.g.

Not really, the eventlistener (in most cases) are defined so they will fire on new rows, tabs etc too. That **is** possible with jquery luckily (the client-side js frameworks have the same 'issue'). 

>Thats IMO the biggest problems for server-side frameworks.

I've been (forced to) use a client-side js component suite to and that has (lots of) other drawbacks in updating the look of cells in e.g. a datatable when updating individual rows. So For me that is no discussion. 

I'd be happy to work on these components IF there is a guarantee that things get added. There has luckily been a great improvement in PF accepting bugfixes but hopefully improvements will be accepted too. That is the main reason I have been reluctant (I know the inner works of the datatable quite well)

**Comment by tandraschko** [comment]
+1 from my side but as i already said, i don't touch the DataTable for improvements. It's to complex and very likely to destroy something. I don't have time in my freetime for such things.
If you can discuss that with @mertsincan, it's ok for me.

**Comment by awenger63** [comment]
+1 too : I think it's the same issue with this code on p:dataTable with multiple selection 
`<p:ajax event="rowSelect" listener=#{} update"myDataTable" />`
When shft-click, fisrt row always be fisrt line and not previous selected value !
Than it's impossible to update dataTable in this case or to have multiple selection.
Hope this can help to find the best improvement or workaround.

**Comment by awenger63** [comment]
@tandraschko 

> A update on the dataTable means that the whole table is re-rendered, so the client-side state is lost.

in listener (on rowSelect), SelectEvent contain the right selection => it's not a client side state.
When data return to the client side, re-rendered save the current row selected, but it's lost the first row id for multiple selection. Only the first !
I thinks it's no need to use coockies, just re-rendered the first selected line in case of multiline option. 
I would like to find a workarround after update to reassigned the rigth selected row to the first row for multiple selection . Do you have any idea ?
Thanks

**Comment by melloware** [comment]
This fix as way simpler than we made it out.  Basically the row selected index gets set back to NULL on every update.  By only initializing it to NULL when the table is created but ignoring it up updates it allows the above use case to work just fine.

**Comment by jthalmai** [comment]
Will this work if the index of the selected entry changes after the update, e.g. if there is a new entry on top?

**Comment by melloware** [comment]
@jthalmai I tested with the test case listed in this ticket but feel free to try it yourself.  Just add this JS code to your application.
```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.setupSelection = function() {
        this.selectionHolder = this.jqId + '_selection';
        this.cfg.rowSelectMode = this.cfg.rowSelectMode || 'new';
        this.rowSelector = '> tr.ui-widget-content.ui-datatable-selectable';
        this.cfg.disabledTextSelection = this.cfg.disabledTextSelection === false ? false : true;
        this.cfg.selectionPageOnly = this.cfg.selectionPageOnly === false ? !this.cfg.paginator : true;
        this.rowSelectorForRowClick = this.cfg.rowSelector || 'td:not(.ui-column-unselectable),span:not(.ui-c)';

        var preselection = $(this.selectionHolder).val();
        this.selection = (preselection === "") ? [] : preselection.split(',');

        //shift key based range selection
        if (!this.originRowIndex) {
            this.originRowIndex = null;
        }
        if (!this.cursorIndex) {
            this.cursorIndex = null;
        }

        this.bindSelectionEvents();
    };
}
```

Please report back if its working

**Comment by jthalmai** [comment]
Unfortunately it does not work in that case. It remembers the old selected index now, so it only works as long as the index does not change. 
E.g. if old index was 2 and after the update the selected column is at index 3. The entry is initially marked correctly as selected, but when you shift-click index 4 then 2-4 are selected afterwards.

**Comment by melloware** [comment]
Ahh your example in the first post doesn't show that. I did exactly what your steps told me to do.  So if your rows change underneath it would have to refind all the rowkeys and try and match it all up again.  YUCK.  closing my PR.

**Comment by jthalmai** [comment]
I guess so, just as it probably does for the selection itself.

**Comment by Rapster** [comment]
What if table was `@process` before `listener` gets called? That should work no? We just need to make it processable :smile:

**Comment by melloware** [comment]
You can try it @Rapster we have test cases above.  I gave it my shot and failed 😨
