### ISSUE TITLE
Add feature to set ajax request timeout and customize timeout callback

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#3552]
is it possible to add feature to set specific ajax request timeout and customize timeout callback  ?
something like 
<p:commandButton action="{bean.action}" timeout="30" ontimeout="doJavaScriptStuff" />

**Comment by tandraschko** [comment]
questsions -> forum

**Comment by devmsaleh** [comment]
it's not a question it's a feature request ?

**Comment by devmsaleh** [comment]
at least tell me why it's invalid

**Comment by tandraschko** [comment]
"is it possible to...?" is a question for me and indicates you are to lazy to check the docu and google about it. Therefore it's invalid.

I could also set the label "already possible" but we don't have it ;)
