### ISSUE TITLE
FileUpload: does not update the 'aria-disabled' attribute for the upload and cancel buttons

### ISSUE THREAD

**Issue by sarvigalava** [primefaces/primefaces#3553]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: All

## 2) Expected behavior
The widget should update the 'aria-disabled' accordingly to the state of the button.
...

## 3) Actual behavior
The 'aria-disabled' is always true
..

## 4) Steps to reproduce
Chose a file to upload, the upload and cancel buttons will become active but the 'aria-disabled' attribute is not updated
.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by sarvigalava** [comment]
The problem is in the fileUpload.js file. The disable & enable functions does not change the 'aria-disabled' attribute

    disableButton: function(btn) {
        btn.prop('disabled', true).addClass('ui-state-disabled').removeClass('ui-state-hover ui-state-active ui-state-focus');
    },

    enableButton: function(btn) {
        btn.prop('disabled', false).removeClass('ui-state-disabled');
    }

**Comment by melloware** [comment]
Please review my PR.
