### ISSUE TITLE
MOVE_SCRIPTS_TO_BOTTOM should also work without body tag

### ISSUE THREAD

**Issue by yannickb85** [primefaces/primefaces#3555]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2.2
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: WebSphere Liberty Profile 18.0.0.1
- Affected browsers: Chrome, FF, MS Edge

## 2) Expected behavior
We have a payment response page that contains an inline script in the <head> section of the HTML but does not contain any <body> tag as this page is only used as a passthrough.

When using primefaces.MOVE_SCRIPTS_TO_BOTTOM, if the page does not contain a body tag, either create the body tag to move the script in, or do not move the inline script from the head section, but do not discard the script completely.

## 3) Actual behavior

When using primefaces.MOVE_SCRIPTS_TO_BOTTOM and no body tag is defined in the xhtml file, the inline script is completely discarded from the page.

## 4) Steps to reproduce

Add the context param `primefaces.MOVE_SCRIPTS_TO_BOTTOM` with value `true` to web.xml
Create an xhtml file as per the sample below.

## 5) Sample XHTML

<html>
<head>
   <script type="text/javascript">
      // Redirect to get out of the iframe
      var str= self.location.href;
      var res = str.replace("return", "return2");
      
       top.location = res;
   </script>
</head>
</html>

## 6) Sample bean

Obviously this is low priority as there are many workarounds. I personally added an empty body tag to my html and everything started working fine again.

The issue seems to be coming from `primefaces/src/main/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriter.java` where the body tag is expected.

**Comment by tandraschko** [comment]
i'm not sure if a facelet view without body is valid.

**Comment by tandraschko** [comment]
Ok, but lets do a workaround. I will commit something now, please give it a try.
