### ISSUE TITLE
DefaultMenuItem: use builder pattern

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3563]
## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior
Fluent API to create menu items. 
```java
DefaultMenuItem.builder()
            .value("Label")
            .icon("fa-box")
            .styleClass("ui-cart-icon")
            .outcome("recordCart")
            .ajax(false)
            .build();
```

`DefautMenuItem` has 40 attributes, builder would make creation much more easier than constructors.

## 3) Actual behavior
```java
BAMenuItem item = new DefaultMenuItem(cart.getLabel(), cart.getIcon(), null, value);
item.setOutcome(cart.getOutcome())
item.setStyleClass(cart.getStyleClass());
```

**Comment by tandraschko** [comment]
+1 basically but i would do it a little bit different

Some people use a own implementation of MenuItem, so therefore i would do something like that:

MenuItem = new MenuItemBuilder(new xxxMenuItem()).......build();

As packacke i would use org.primefaces.model.builder

**Comment by Rapster** [comment]
Looks over-designed... Plus I don't how you'd make it work. I think i have an idea of what you're trying to achieve. `MenuItemBuilder`  constructor would have a `MenuItem` as a parameter, `MenuItemBuilder` would provide setters, but since `MenuItem` is an interface, you can't set anything from there. Your approach needs one builder per each custom `MenuItem` (that's what make it over-designed to me, while Builder pattern is a simple thing to set up)

Anyway, Builder pattern is quite easy and straighforward to implement these days (e.g Lombok, Spark Generator Builder). I'd suggest to keep it simple

**Comment by tandraschko** [comment]
There is nothing overdesigned, it would just make it be possible to use another instance. But without setters, it's not possible of course.

**Comment by cnsgithub** [comment]
@tandraschko You suggestion would be to introduce an optional `MenuItemBuilder` CTOR like so?

```java
package org.primefaces.model.builder;

import org.primefaces.model.menu.DefaultMenuItem;
import org.primefaces.model.menu.MenuItem;

public class MenuItemBuilder<T extends MenuItem> {
    
    private T menuItem;

    /**
     * Construct default MenuItem builder
     */
    public MenuItemBuilder() {
        menuItem = (T) new DefaultMenuItem();
    }

    /**
     * Construct custom MenuItem builder assuming an accessible default constructor exists
     * @param type
     * @throws ReflectiveOperationException
     */
    public MenuItemBuilder(Class<T> type) throws ReflectiveOperationException {
        menuItem = type.getConstructor().newInstance();
    }
    
    public MenuItemBuilder<T> withValue(Object value) {
        // TODO extend MenuItem interface to include setters, use no-op default methods to not break existing implementations    
        // menuItem.setValue(value);
        return this;
    }
    
    public T build() {
        return menuItem;
    }
    
}
```

**Comment by tandraschko** [comment]
Lets just do it without the possible inheritance for now and only accept defaultmenuitem

**Comment by cnsgithub** [comment]
As an alternative to manually implementing builder classes we could also use [lombok](https://github.com/rzwitserloot/lombok) as already mentioned by @Rapster. This would just introduce a compile time dependency, but not a runtime dependency.

Using lombok would be a big advantage over manual implementation because it would reduce boiler-plate code and is much easier to maintain. Consider just the case when new attributes are being applied to `DefaultMenuItem`, etc.

Example:
```java
import lombok.Builder;

@Builder
public class DefaultMenuItem implements MenuItem, UIOutcomeTarget, AjaxSource, Serializable {
//...
}
```

Usage:
```java
    public static void main(String[] args) {
        DefaultMenuItem.builder().value("foo").build();
    }
```

**Comment by Rapster** [comment]
Reflection is a no go for me, poor performance for something that can be easily generated (IDE have plugins nowadays for that).

Regarding Lombok, I'm not against adding dependencies, but it's using a sledgehammer to crack a nut. Plus, as fancy as Lombok can sound. I'm not a big fan of this library 'cause it's a hack. another thing is, Lombok builder annotation is for immutable classes, DefaultMenuItem is not one of them.

Regarding `@Deprecated`, since 6.3 is planned for December 2018, a few release candidates will be released, migration guide will be updated in consequence. Users will be fully aware of this soon enough, so they can change their code _(which will be easy)_. It's up to Thomas, but keeping constructors (even as deprecated) and builder pattern is quite noisy and wait for a year to finally get rid of this is too long IMO.

**Comment by cnsgithub** [comment]
> Reflection is a no go for me

This was just an example. Implementation could of course be improved to allow for better performance.

> Lombok builder annotation is for immutable classes

Can you point me to the source saying that `@Builder` is for immutables?
I cannot agree. Simply do this and see that `DefaultMenuItem` is modified and therefore is not immutable.
```java
    public static void main(String[] args) {
        DefaultMenuItem menuItem = DefaultMenuItem.builder().value("foo").build();
        menuItem.setValue("bar");
    }
```

> IDE have plugins nowadays for that

However, PrimeFaces developers/contributors are not restricted to use a specific IDE. It is not guaranteed that plugin A is available for all IDEs. Regenerating a builder would stay a manual job (that may be forgotten) anyway. Maven integration would be nice to be up-to-date with the latest attribute changes.

> Regarding `@Deprecated`

I agree.

**Comment by Rapster** [comment]
This is what I deduced from what I read on the Lombok documentation. I don't much about it anyway, but I guess you can workaround the problem using `@Value`

**Comment by tandraschko** [comment]
I would do it without lombok for now.

**Comment by melloware** [comment]
Not sure if its related but in the Showcase all the menu examples are broken.

https://www.primefaces.org/showcase/ui/menu/menu.xhtml

Click on the "Save" menu item.

```
java.lang.NullPointerException
        at org.primefaces.component.menu.BaseMenuRenderer.findMenuitem(BaseMenuRenderer.java:86)
        at org.primefaces.component.menu.BaseMenuRenderer.decode(BaseMenuRenderer.java:67)
```

**Comment by Rapster** [comment]
I'll have a look

**Comment by Rapster** [comment]
I reverted my changes, and it seems the problem was already there

**Comment by melloware** [comment]
Thanks @Rapster I submitted new issue: https://github.com/primefaces/primefaces/issues/4963
