### ISSUE TITLE
InputMask: pattern with '*' doesn't function

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#3566]
Since #3234 an inputMask like "a\*9" doesn't function. Reason:
code inside InputMaskRenderer.translateMaskIntoRegex(InputMask) translates "a*9" into regexp "[A-Za-z]\\[A-Za-z0-9][0-9]". The correct regexp would be "[A-Za-z][A-Za-z0-9][0-9]".

## 1) Environment
- PrimeFaces version: 6.2.2
- Does it work on the newest released PrimeFaces version? Version? Yes
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Yes
- Application server + version: irrelevant (Tomcat 8)
- Affected browsers: irrelevant (Firefox and Chrome)

## 2) Expected behavior
using inputMask "a*9" should accept input "aX3"

## 3) Actual behavior
after entering "aX3" into the field with inputMask "a\*9" and clicking a button the page is re-rendered and the input wasn't stored in the backing bean - the field is empty.

## 4) Steps to reproduce
as described above 

## 5) Sample XHTML
<p:inputText id="inputMaskString" value="..."  inputMask="a\*9"  />

## 6) Sample bean
usual backing bean to store value of input field.

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3569
