### ISSUE TITLE
propagateSelection in p:tree

### ISSUE THREAD

**Issue by beyondtecnic** [primefaces/primefaces#357]
Is it possible to indicate how to propagate as if you check or uncheck a checkbox?.

If it is not currently possible, I think that would be a good improvement.

I use primefaces 5.2.

**Comment by sudheerj** [comment]
Have you tried with propagateSelectionUp and propagateSelectionDown attributes?

**Comment by beyondtecnic** [comment]
Yes i tried, But I want you if selected propagate one way and if unchecked will propagate another.

**Comment by cagataycivici** [comment]
Please use forum for questions like these.
