### ISSUE TITLE
#3562 CellEditing: Add partialSubmit support

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#3570]
This is the point 2.4) of the issue #3562 :
**Table is editable in Cell-Edit-Edit-Mode** -> Only the current cell-datas should be sended to the server.

The problem occurs when the whole table-datas are send via parameter url
and the quantiy of parameters are over 1000.
Then you got a server exception.

**Comment by tandraschko** [comment]
example?
If you don't provide a example to replicate it, which already uses partialSubmit, i will close it as invalid.

**Comment by ssibitz** [comment]
The same example as i forked from the Primefaces-Showcase:
[https://github.com/ssibitz/showcase](https://github.com/ssibitz/showcase)

When you then click in the Edit-Table with Cell Editing enabled 
you can see that the whole datatable is serialized for each Input.
But you can only change 1 input at the same time,
so you will got an server exception if you are over 125 rows and try
to edit only one cell ...

**Comment by tandraschko** [comment]
Close in favor of: https://github.com/primefaces/primefaces/issues/3571
