### ISSUE TITLE
Adding an AddRow-Example to the Primefaces-Showcase ?

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#3572]
As i am using Primefaces 6.2 i got an exception on adding a new row 
which currently will be handled with the ticket #3564 .

For the test's i prepared an example on how to use 
the AddRow of a datatable, so my question:

Should i prepare a new view for the Primefaces-Showcase
to show how to use the AddRow function ?

I searched across the internet to find it out and so i
think this could also be useful for other user's , or not ?

**Comment by tandraschko** [comment]
yes but please please please avoid creating such issues in the future, i will close them just as invalid.

In generell:
- a issue tracker is NOT NOT NOT for questions. Use the forum or gitter
- we always accept showcase improvements like adding not shown features
- this issue tracker is for primfaces, the showcase issue tracker is for the showcase
