### ISSUE TITLE
Tree(Data)table - Have the datatable support tree like functionality

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#3573]
I just came across a requirement for  TreeTable to support similar feature of a Datatable. 

A bit of looking around and found the work done by  Ronald.
https://kukeltje.wordpress.com/2012/12/23/treedatatable-where-do-you-start-tree-or-datatable/
https://github.com/kukel/primefaces-plus

Ronald /  @tandraschko  i created this issue just for discussion.

**Comment by tandraschko** [comment]
Discussion in the forum plz.

**Comment by ravihariharan** [comment]
https://forum.primefaces.org/viewtopic.php?f=3&t=55343
