### ISSUE TITLE
How to execute execCommand in p:textEditor

### ISSUE THREAD

**Issue by sudhansu789** [primefaces/primefaces#3574]
```
<p:textEditor cols="100" rows="2" id="emailInnerSolutionID" widgetVar="emailInnerSolutionResponse"
converter="textConverter" value="#{inquiryManagedBean.inquiryCorrespondence.insertSolution}" />
```
Calling JS function from server side:
RequestContext.getCurrentInstance().execute(insertCursur('emailInnerSolutionResponse','MY DATA')");

JS Function to Execute 
```
function insertCursur(id,value){
	try{
	PF(id).editor.execCommand('inserthtml',value);
	}
	catch(e){
		alert(e);
		alert("Please place cursor in editor.");
	}
}
```

Actual Result: execCommand is not a function and an alert Please place cursor in editor.
Expected Result: It should insert the supplied text to editor.

**Comment by tandraschko** [comment]
Please use the forum first.
