### ISSUE TITLE
Spinner: support for empty input

### ISSUE THREAD

**Issue by orange-buffalo** [primefaces/primefaces#3577]
Currently `p:spinner` does not support empty values if `min` attribute is defined. JavaScript resets the value to `min` if user clears the input: 
https://github.com/primefaces/primefaces/blob/d3abd728d89a967a6bbb6793e4b2900c4a020705/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js#L175-L182

This makes it impossible to support use case "optional value with minimum value constraint".  

It would be great to have an attribute like "supportEmptyValues" and use it in JS to decide if empty user input should be overridden with the `min` value. 

Would you accept a pull request to introduce such an attribute?

**Comment by cnsgithub** [comment]
I think introducing a new attribute `supportEmptyValues `is not reasonable. Why not use the general `required` attribute?

**Comment by orange-buffalo** [comment]
Our team has internal reasons to avoid using this attribute, but I agree that for generic purpose framework it is a better choice than introducing another attribute with similar semantic.

**Comment by orange-buffalo** [comment]
@tandraschko Would it be possible to port the change to the 6.2 version? Our team is using a paid subscription and would be happy to receive the enhancement before 6.3 release.

**Comment by tandraschko** [comment]
thats up to @mertsincan
