### ISSUE TITLE
DataTable: Flick/glitch when scrolling vertically with Virtual Scrolling

### ISSUE THREAD

**Issue by AdriaoNeves** [primefaces/primefaces#3578]
## 1) Environment
It happens in the primefaces showcase  6.2, DataTable > Virtual Scrolling.

- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Bug occurs. Version? 6.2

- Application server + version: JBOSS 7.2
- Affected browsers:
Chrome, Firefox, IE11, Edge.

## 2) Expected behavior
Scroll vertically without any flick/glitch.

## 3) Actual behavior
After fetching new rows while scrolling down, user can see the rows moving up before going back to the correct position.

## 4) Steps to reproduce
It happens in the primefaces showcase  6.2.
- Configure a datatable with virtual scrolling.
- Scroll down until new rows are fetched.
- You will see datatable scroll moving up then going back to the correct position.

## Notes

![virtualscrolling_pf_6 2](https://user-images.githubusercontent.com/423796/38606459-fc6fa356-3d6d-11e8-869c-5fc5b25cc444.gif)

**Comment by huseyinturkmenoglu** [comment]
Hi, I tested Virtual Scrolling from primefaces.org/showcase. But I don't see any issue.

Could you explain the issue with more information or create sample test(https://github.com/primefaces/primefaces-test)?

**Comment by AdriaoNeves** [comment]
Hi, I checked again on https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml and the glitch happens like in the gif I uploaded previously.

If you try to follow the records while you scroll down, you will see that when more rows are fetched, the scrollTop gets sent to 0 (because of datatable update) then the scrollTop is restored to the corrected position, this makes harder to follow records while scrolling down.

**Comment by cagataycivici** [comment]
I've seen this as well and added a fix.
