### ISSUE TITLE
TreeTable: scrollable and paginator does not work together

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#3580]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat
- Affected browsers: All

## 2) Expected behavior
scrollable and paginator should work together.

...

## 3) Actual behavior

With scrollable  property set  paginator  is not shown.
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

Sample from showcase
Only 2 rows are show and the paginator is not shown.
```
<p:treeTable value="#{ttScrollableView.root1}" var="document" style="margin-top:0" scrollable="true" scrollHeight="150" paginator="true" paginatorAlwaysVisible="true" rows="2">
               
                
            </p:treeTable>
```
Works
```
<p:treeTable value="#{ttScrollableView.root1}" var="document" style="margin-top:0"  paginator="true" paginatorAlwaysVisible="true" rows="2">
                            
                
            </p:treeTable>
```

## 6) Sample bean

Sample from showcase

**Comment by huseyinturkmenoglu** [comment]
I send PR : https://github.com/primefaces/primefaces/pull/3651

**Comment by mertsincan** [comment]
Thanks @HuseyinTurkmenoglu!
