### ISSUE TITLE
Calendar: does not validate the input against mindate/maxdate

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#3582]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? No
- Application server + version: Tomcat 8.0
- Affected browsers: Firefox

## 2) Expected behavior

When I specify a mindate/maxdate, validation fails if I enter a date outside this range by manual typing in the input component.

## 3) Actual behavior

Validation does not fail, unless you add your own f:validator that enforces the input date to be within the specified range.

Seems like the same problem as https://github.com/primefaces/primeng/issues/2437

## 4) Steps to reproduce

Create a p:calendar and specify mindate and/or maxdate attributes.

## 5) Sample XHTML

    <p:calendar id="registrationDate" value="#{regData.date}"
    	mindate="#{regData.minDate}" maxdate="#{regData.maxDate}"
    	navigator="true" yearRange="c-2:c"
    	showButtonPanel="true" mask="true" />

## 6) Sample bean

    public class RegData {
        private Date date;
        private Date minDate;
        private Date maxDate;
        // getters/setters omitted
    }

**Comment by cnsgithub** [comment]
Pull request: https://github.com/primefaces/primefaces/pull/3589
