### ISSUE TITLE
DataTable: filtered twice on filter action

### ISSUE THREAD

**Issue by mateofacu** [primefaces/primefaces#3584]
## 1) Environment
- PrimeFaces version: 6.2 - community
- Does it work on the newest released PrimeFaces version? Version?: NO - 6.2.3 (showcase version)
- Application server + version: Tomcat 8.5.30
- Affected browsers: ALL

## 2) Expected behavior

When  datatable component is filtered using a text field, I expect that the ajax filter action is executed just once.

## 3) Actual behavior

When datatable component is filtered using a text field,  filter action is executed twice when you delete the last letter on the input field.

## 4) Steps to reproduce

1 - Go to datatable filter page  in   showcase: https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml

2 - For Id column  type "c" in the filter field. The table is filtered correctly.

3 - Erase the filter text using de backspace. Ajax call for filter is executed twice. 

## 5) Sample XHTML
No need for a sample. The showcase is enough.

## 6) Sample bean
No need for a sample. The showcase is enough.

**Comment by mertsincan** [comment]
Related to #89

**Comment by melloware** [comment]
Maybe we can add in that fix for #89 a  if (PrimeFaces.isIE()) wrapper around that call?
