### ISSUE TITLE
TabView: Add support for other Collections (Set, ...), Map, Iterable as DataModel

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3586]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT (6_1-1337-ge748a61e5)
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: Payara 4.1.2.181, probably all
- Affected browsers: Firefox, probably all

## 2) Expected behavior

Specifying a `Set` fields as `value` of a `p:tabView` causes the `Set` to be evaluated as property instead of a collection of properties which only happens for `List`. This information should be provided in the otherwise quite unhelpful error message which should be `The class 'java.util.HashSet' does not have the property (p:tabView only evaluates java.util.List values as collection)` instead of `The class 'java.util.HashSet' does not have the property`.

Please note, that I'm not arguing that on second thought it makes a lot of sense to only evaluate `List` as collection in order to avoid unpredicatble tab order. I'm suggesting an improvement.

## 3) Actual behavior

unintuitive exception message

## 4) Steps to reproduce

Simply open the sample XHTML page with the backing bean.

## 5) Sample XHTML

```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <p:tabView value="#{backingBean0.entity0s}" var="entity0">
                <p:tab>
                    <h:outputLabel value="#{entity0.property0}"/>
                </p:tab>
            </p:tabView>
        </h:form>
    </h:body>
</html>
``` 

## 6) Sample bean
```
@Named
@ViewScoped
public class BackingBean0 implements Serializable {
    private static final long serialVersionUID = 1L;
    private Set<Entity0> entity0s = new HashSet<>(Arrays.asList(new Entity0("a")));

    public BackingBean0() {
    }

    public Set<Entity0> getEntity0s() {
        return entity0s;
    }

    public void setEntity0s(Set<Entity0> entity0s) {
        this.entity0s = entity0s;
    }
}

public class Entity0 {
    private String property0;

    public Entity0() {
    }

    public Entity0(String property0) {
        this.property0 = property0;
    }

    public String getProperty0() {
        return property0;
    }

    public void setProperty0(String property0) {
        this.property0 = property0;
    }
}
```

**Comment by tandraschko** [comment]
We can even add support for a Set, if the change is very easy. Otherwise i would add a warning.
Please provide a PR.
