### ISSUE TITLE
PickList - disable buttons if no items available

### ISSUE THREAD

**Issue by orange-buffalo** [primefaces/primefaces#3587]
Currently PickList does not disable buttons if source or destination list is empty. It would improve user experience if buttons that do not have effect are disabled. 

https://www.primefaces.org/showcase/ui/data/pickList.xhtml

![image](https://user-images.githubusercontent.com/4532247/38789872-871ba052-4180-11e8-875b-308723c91bbe.png)

![image](https://user-images.githubusercontent.com/4532247/38789882-94cd128a-4180-11e8-8891-3b5854db7d5f.png)

**Comment by tandraschko** [comment]
Feel free to provide a PR.

**Comment by tandraschko** [comment]
Thanks for the PR!
