### ISSUE TITLE
KeyFilter: Not working after calling " ajax update" on h:inputText

### ISSUE THREAD

**Issue by ShivaniSK** [primefaces/primefaces#3596]
## 1) Environment
- PrimeFaces version:  6.1

## 2) Expected behavior
- p:keyFilter should allow only alphabets and numbers in inputText at any point of time.
...

## 3) Actual behavior
After ajax update is called on input Text, the filter does not work
..

## 4) Steps to reproduce
1) Go directly to "Project Key" field and try entering special characters.. it will not allow.. the filter works this time.
2) Now go to "Project Name" field and then click on "Project Key". This time try entering special characters. It allows to enter. The filter does not work now.
.. 

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:head>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />	
	
</h:head>	
	<h:form>
		<h:outputText value="Project Name:"></h:outputText>
		<h:inputText id="projectName" value="#{testBean.projectName}" >
			<p:ajax event="blur" listener="#{testBean.updateKey()}" update="projectKey,filterId" process="@form"></p:ajax>
		</h:inputText>
		<br/>
		<h:outputText value="Project Key:"></h:outputText>
		<h:inputText id="projectKey" value="#{testBean.projectKey}"  label="Project Key" size="29" maxlength="10">
		</h:inputText>
		<p:keyFilter id="filterId" for="projectKey" mask="alphanum" />
	</h:form>
</html>
```
..

## 6) Sample bean
```
import javax.faces.bean.ManagedBean;
import javax.persistence.Entity;

@ManagedBean(name="testBean")
@Entity
public class Test {
	
	private String projectName;
	private String projectKey;
	
	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectKey() {
		return projectKey;
	}

	public void setProjectKey(String projectKey) {
		this.projectKey = projectKey;
	}

	public void updateKey()
	{
		if(projectName.equals("Shivani"))
		{
			projectKey = "SK";
		}
	}
}
```
..

**Comment by tandraschko** [comment]
Thats expected, you need to update the keyfilter too.

**Comment by ShivaniSK** [comment]
Even if i update keyFilter, it does not work.

**Comment by tandraschko** [comment]
Then please update your code to show this problem.

**Comment by ShivaniSK** [comment]
Code updated.

**Comment by ShivaniSK** [comment]
Can you please help me out with this issue? If this won't fix then is there any other way by which i can achieve this?

**Comment by ShivaniSK** [comment]
It is resolved. Nesting both filter and input in ui-fragment and updating the fragment works.
```
<ui:fragment id="inputAndFilter">
    <h:inputText id="text2" />   
    <p:keyFilter for="text2" mask="num" />
</ui:fragment>
```

**Comment by tandraschko** [comment]
nevertheless, your code should work when you update both.

**Comment by ShivaniSK** [comment]
if you check my updated code and try running it, its not working. I am updating both only. After putting it in ui:fragment it is working

**Comment by melloware** [comment]
I think I just fixed this with this PR:  https://github.com/primefaces/primefaces/pull/3805

the original bug was in the keyfilter code here:  https://github.com/akzhan/jquery-keyfilter/issues/7

**Comment by melloware** [comment]
@ShivaniSK can you build 6.3-SNAPSHOT and verify this is fixed.

**Comment by melloware** [comment]
@tandraschko this ticket is safe to close.
