### ISSUE TITLE
Dashboard: Dynamic Panels

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#36]
Enhance dashboard to support dynamic panels using ui:repeat or built-in iteration along with static panels.

**Comment by justin-wesley** [comment]
It would be nice if the dashboard can use composite components that wrap panels as well.

**Comment by cagataycivici** [comment]
I think we should check for UIPanel, yes.

**Comment by cagataycivici** [comment]
I think we should check for UIPanel or create an interface for accepted components.

**Comment by justin-wesley** [comment]
I don't think you would want to use UIPanel as that would allow the use of menus, ribbons, dialogs, etc which I don't think would fit well with a dashboard concept. 

The only reason I would use the composite component is to wrap a panel with default settings and make the panel load dynamically. If the panel had a dynamic attribute so it wouldn't load until visible and expanded, then I wouldn't need that.

**Comment by cagataycivici** [comment]
An interface then.

**Comment by AzoJason** [comment]
Any progress on this feature?

**Comment by melloware** [comment]
From @anuragnz

Hi there,

The dashboard component looks good.
We need to define the columns and then we can add components to each columns like this:

```java
                model = new DefaultDashboardModel();
		DashboardColumn column1 = new DefaultDashboardColumn();
		DashboardColumn column2 = new DefaultDashboardColumn();
		DashboardColumn column3 = new DefaultDashboardColumn();

		column1.addWidget("sports");
		column1.addWidget("finance");

		column2.addWidget("lifestyle");
		column2.addWidget("weather");

		column3.addWidget("politics");

		model.addColumn(column1);
		model.addColumn(column2);
		model.addColumn(column3);
```

For dynamic dashboard components defining columns is not suitable. Rather if we can just define number of columns then it would become a grid layout type. Which would be really great. 

So the option would be
```xml
<p:dashboard columns="3" model="#{}"  />
```

**Comment by anuragnz** [comment]
Any update on this please?

**Comment by jepsar** [comment]
@anuragnz feel free to provide a pull request

**Comment by stolp** [comment]
I like to add, that you can also emulate a column oriented dashboard using `dataView` / `dataViewGridItem`.

The latter has the columns attribute you are looking for. Drag and Drop needs to implemented explicitly in your `dataViewGridItem` content using `draggable` / `droppable`.

We are using this approach successfully for quite a while.

**Comment by melloware** [comment]
@stolp I think a Showcase example showing this functionality with Dataview being used as a Drag Drop dashboard would be awesome!   Even if you want to post the code here I can add it as a showcase example called "Dashboard" under DataView.

**Comment by stolp** [comment]
@melloware I can have a go adding some showcase code later this week. It's not overly complex but it may take some time to extract the relevant part from the application.

**Comment by melloware** [comment]
![dashboard](https://user-images.githubusercontent.com/4399574/216385279-b29c115b-5310-469f-8568-f81913a869f9.gif)

**Comment by anuragnz** [comment]
This is really awesome...

**Comment by Deatthzlicer** [comment]
I am trying to run the Js changes of this branch on  a single xhtml.. trying to override it from the version 12 resources... I dissected primefaces 13 jar into containing only dashboard related (it took me couple of hours) on the java side.

in order to replicate the resources I need BaseWidgetCfg which I am guessing a generated file from node??

Would you mind sharing this file ,, does it have to be running npm? I dont belive so...  

I do want to get this cool feature working. Any ideas would are appreciate.

**Comment by melloware** [comment]
No not generated...all the JS code is there look in core.widget.js

**Comment by melloware** [comment]
Why not just build a 13.0.0-SNAPSHOT jar than go through all this trouble?

**Comment by Deatthzlicer** [comment]
#1 Unreleased Dependency on production is discouraged 
#2 Migration of Pandora  with 11 PrimeFaces
#3 Backwards compatibility and Forward Compatibility
