### ISSUE TITLE
DraggableColumnsFeature does not handle subtables

### ISSUE THREAD

**Issue by cghislai** [primefaces/primefaces#360]
Draggable columns are not handled server-side for subtables.

In the 'public void decode(FacesContext context, DataTable table)' function, only columns which are direct children of the table are handled. 

The code should test for the presence of a SubTable, and if it is present it should iterate over children of the SubTable rather than the main DataTable to find columns to reorder.

**Comment by cagataycivici** [comment]
It is not supported and unlikely to be as we plan to replace subtables with another structure in a later release.
