### ISSUE TITLE
Tree: filtering on uppercase input not triggered

### ISSUE THREAD

**Issue by eversnarf** [primefaces/primefaces#3605]
## 1) Environment
- PrimeFaces version: 6.2.3
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? Not tried
- Application server + version: Tomcat 8.5.20
- Affected browsers: Firefox, Chrome, Edge

## 2) Expected behavior
When using filtering on a `<p:tree>`, I expect the search (to be case insensitive and) to be triggered whether I enter search text in upper or lower case.

## 3) Actual behavior
Filtering is not triggered when I type uppercase characters in the search box.

## 4) Steps to reproduce
If I start typing `LEMO` in the search box, not filtering is applied. As soon as I type a lowercase char or a digit, it starts filtering. So, typing for example `LEMOn` will trigger the filtering as soon as I type the `n`.
See example.

## 5) Sample XHTML
```xml
<p:tree value="#{treeBean.root}" var="node" filterBy="#{node}">
    <p:treeNode>
        <h:outputText value="#{node}"/>
    </p:treeNode>
</p:tree>
```

## 6) Sample bean
```java
public class TreeBean {

    private TreeNode root;

    public TreeBean() {
        this.root = new DefaultTreeNode();
        this.root.getChildren().add(new DefaultTreeNode("Lemon"));
        this.root.getChildren().add(new DefaultTreeNode("Apple"));
        this.root.getChildren().add(new DefaultTreeNode("Cherry"));
        this.root.getChildren().add(new DefaultTreeNode("Banana"));
    }

    public TreeNode getRoot() {
        return root;
    }
}
```

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3606

**Comment by eversnarf** [comment]
Thank you, @cnsgithub and @mertsincan.
Quite fast!
