### ISSUE TITLE
Bound DataTable with footer render multiple footers with same id

### ISSUE THREAD

**Issue by cghislai** [primefaces/primefaces#361]
If you bind a <p:dataTable> to a backing bean DataTable instance (p:dataTable binding=#{myBean.myTable}">), and if you use subtables , then JSF will render multiple elements with the same id, throwing a "java.lang.IllegalStateException: Component ID ... has already been found in the view. " .

I experienced this with ColumnGroup element and footer facelets being rendered multiple times with the same ids.

**Comment by cagataycivici** [comment]
This is known pitfall, please see;

https://myfaces.apache.org/orchestra/myfaces-orchestra-core/component-bindings.html
