### ISSUE TITLE
SelectOneMenu: Crash when Items label contains CSS selector special chars

### ISSUE THREAD

**Issue by xtron** [primefaces/primefaces#3612]
## 1) Environment
- PrimeFaces version: 6.2.3
- Does it work on the newest released PrimeFaces version? Version?
no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
no
- Application server + version:
Wildlfy 10.1
- Affected browsers:
Google Chrome 66.0.3359.117 

## 2) Expected behavior
Work without errors in dev. console
...

## 3) Actual behavior
![image_2018-04-25_14-52-39](https://user-images.githubusercontent.com/345073/39250337-4546c01e-48a9-11e8-8edc-0cf875495a43.png)

## 4) Steps to reproduce

create selectOneMenu with items that contains ( " )
.. 

## 5) Sample XHTML
`<p:selectOneMenu value="#{myBean.value}">`
       `<f:selectItem itemValue="#{myBean.sampleValue}" itemLabel="#{myBean.sampleLabel}"/>`
  `</p:selectOneMenu>`

             
## 6) Sample bean
`@Named`
`@RequestScoped`
`public class myBean{`
 ` .... `
 ` public String getSampleLabel()`
`{`
`   return "ГБУЗ РК \"Центр СПИД\"";`
`} `
`....`
`}`

**Comment by tandraschko** [comment]
@mertsincan should be ported to elite

**Comment by cnsgithub** [comment]
Please note that use of `escapeSelector `seems to be generally missing at various locations. Doing a quick regex search `\[[A-Za-z0-9-_]+=["'].*?\+` (may return false positives) in `*.js` reveals 25 potential erroneous locations, even one more in `forms.selectonemenu.js` addressed in this issue: https://github.com/primefaces/primefaces/blob/0b5805f12d3b8297881905493ec69b18d3e269e6/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L814
![image](https://user-images.githubusercontent.com/13161711/39287396-c3824884-4923-11e8-9650-12c975416467.png)

**Comment by cnsgithub** [comment]
Hi @tandraschko, do you think it's worth creating a separate issue for those jquery escaping issues?

**Comment by melloware** [comment]
@cnsgithub I would create 1 new issue and list the 32 places you found it!

**Comment by cnsgithub** [comment]
I just created a separate issue: https://github.com/primefaces/primefaces/issues/3624
