### ISSUE TITLE
SelectBooleanCheckbox: different style when clicking on label in IE and other browsers

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3617]
only ui-state-focus

the problem is the following IE:
1) open http://localhost:8080/showcase/ui/input/booleanCheckbox.xhtml (trunk version, i added a label instead outputtext there)
2) click on the label:
    - onchange will be fired and ui-state-active will be added (correct)
    - onfocus will be fired (it's ok) but the ui-state-active will be removed
3) e.g. if you use redmon, the checkbox will be orange instead of blue

some components focus event actually only triggers ui-state-focus (e.g. selectOneButton), other not (e.g. selectoneradio)

**Comment by zsolemolina** [comment]
Hi there,
I've an issue with the boolen checkbox. Trying to manage that from the label (click on the label) the checkbox is not showing the active status, is still only showing the focus:

First click on the label:
![image](https://user-images.githubusercontent.com/2143979/50091556-fc29bb80-020b-11e9-805d-ce19df1797a7.png)

Second click on the label, there is no active status appended:
![image](https://user-images.githubusercontent.com/2143979/50091604-195e8a00-020c-11e9-950f-257b2eefbca9.png)

So, I'm wondering if there is anyway to solved it? Clicking direclty on the box is working properly. Thanks

**Comment by tandraschko** [comment]
Please look at the issue here. It was fixed in 6.3 and 6.2.13. There is no other workaround.

**Comment by zsolemolina** [comment]
> Please look at the issue here. It was fixed in 6.3 and 6.2.13. There is no other workaround.

Thank you very much!
