### ISSUE TITLE
CSS is not getting overriden for AccordionPanel after upgraded Primefaces version from 3.5 to 6.1. 

### ISSUE THREAD

**Issue by hanurao007** [primefaces/primefaces#3618]
##1) Environment
- PrimeFaces version: 6.1
- Doesn't work with latest version
- Doesn't work with newest source in GitHub.
- Application Server - JBoss 6.4.19

## 2) Expected Behavior
      
![expected behaviour](https://user-images.githubusercontent.com/17093392/39335120-8bea7066-4966-11e8-850d-df4eec4bc490.png)

## 3) Actual behavior
![actualbehaviour](https://user-images.githubusercontent.com/17093392/39335136-9fc32268-4966-11e8-9ed8-eb3cf53dde3a.png)

## 4) Steps to reproduce

/* css used for primefaces accordian */
.ui-accordion {
	border-left: 1px solid #E0E0E0;
	border-right: 1px solid #E0E0E0;
	color: #000000;
	height: auto;
	position: relative;
	width: 165px !important;
	font-size: 12px;
}

.ui-accordion h3 {
	background: url("../resources/img/menu_bg_active3px.jpg") repeat-x scroll 0 0
		transparent;
	height: 32px;
	margin: 0;
	padding: 0;
}

.ui-accordion .ui-accordion-header a {
	background: url("../resources/img/site_arrow.png") no-repeat scroll 98% 50%
		transparent;
	color: #333333;
	display: block;
	font-size: 12px;
	font-weight: lighter;
	padding: 8px 6px !important;
	text-decoration: none;
}

.ui-state-active a {
	background: url("../resources/img/down.png") no-repeat scroll 98% 60% transparent;
	color: #002878;
	padding: 8px 6px;
}

.ui-accordion-content table {
	width: 100%;
	font-size: 12px;
	border-left: 1px solid #E0E0E0;
	border-right: 1px solid #E0E0E0;
}

.ui-accordion-content table td {
	background: none repeat scroll 0 0 #FFFFFF;
	border-bottom: 2px solid #E0E0E0;
	color: #333333;
	font-weight: lighter;
	
	padding: 0px 0 0 15px;
	line-height: 26px;
}

.ui-accordion-content table td a {
	color: #333333;
	display: block;
	font-weight: lighter;
	height: 100%;
	text-decoration: none;
	width: 100%;
}

.ui-accordion .ui-accordion-content {
	padding: 0 !important;
}

**Comment by tandraschko** [comment]
Please use the forum and/or analyse the styles via firebug/developer tools. There is nothing we can fix, you just need to apply the styles correctly. Maybe the structure has been changed.
