### ISSUE TITLE
Calendar: popup with effect="fold" wrong show

### ISSUE THREAD

**Issue by omarbr** [primefaces/primefaces#3619]
## 1) Environment
- PrimeFaces version: reproduced on 5.3 and 6.2
- Affected browsers: firefox, chrome, edge

simply reproduce on primeface showcase

## 3) Actual behavior
when click on p:calendar input field with effect="fold" show popup dialog and it's ok, click other calendar field, popup dialog is damaged.

## 4) Steps to reproduce
click on on p:calendar input field with effect="fold", not select date (popup dialog remains open), click on other p:calendar input field, then popup dialog is damaged.

## 6) Sample bean
primeface showcase

**Comment by melloware** [comment]
@tandraschko This is a duplicate of https://github.com/primefaces/primefaces/issues/489 and can be closed.
