### ISSUE TITLE
Add active flag to celleditor to reduce DOM.

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#362]
What about an active flag that can be added to `<p:cellEditor>` which only renders the `output` facet if set to `true`. Depending on the complexity of the `input`facet this may be a good idea.

**Workaround**

Current solution is to duplicate `output` facet.

```
<p:column headerText="foo">
    <p:cellEditor rendered="#{cc.attrs.isFooEditable}">
        <f:facet name="output">
            <h:outputText value="#{var.foo}"/>
        </f:facet>
        <f:facet name="input">
            <h:inputText value="#{var.foo}"/>
        </f:facet>
    </p:cellEditor>
    <h:inputText value="#{var.foo}" rendered="#{not cc.attrs.isFooEditable}"/>
</p:column>
```

**Comment by cagataycivici** [comment]
How about readOnly instead of active?

``` java
<p:cellEditor readOnly="#{cc.attrs.isFooEditable}">
```

**Comment by djmj** [comment]
Or `inputOnly` :D ...

or enhance it even more by rendering facet `input` lazy on row or cell edit enter event? 
Makes the new attribute obsolete and initial saves DOM even if editable.

**Comment by cagataycivici** [comment]
I plan to do the second one for 5.3, if that will do it marking this one as closed.
