### ISSUE TITLE
Dynamic Resource loading doesn't work with Mojarra 2.2

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3621]
## 1) Environment
- PrimeFaces version: 6.2.3
- Does it work on the newest released PrimeFaces version? Version? no
- Application server + version: Tomcat v8.0
- Affected browsers: all
- Mojarra version 2.2.15, 2.2.16, 2.2.17

## 2) Expected behavior
When using p:inputNumber inside c:if tag,  "loaded to page by ajax" the javascripts should work properly.

## 3) Actual behavior
Browser's console shows JS error: **Widget not available: InputNumber** and the inputs are not formatted correctly (formatting function with thousand delimiter, currency etc. is not invoked).

If there was p:inputNumber component in the page on page-load, the JS would work. In this example there is no p:inputNumber in page on load and the component is added using ajax request. The inputnumber/inputnumber.js is "transfered" to the client browser but it is somehow broken.

In Mojarra versin 2.3.2 it works well, but I can't upgrade.

## 4) Steps to reproduce
Alter PF showcase using XHTML and Java code below. Go to inputNumber.xhtml and click "crash button". Observe browser's javascript console.

## 5) Sample XHTML
Altered showcase inputNumber.xhtml: 
Added button which updates panel containing c:if tag. At page load, the _inputNumberView.flag_ is _false_. After ajax update it is _true_.

```
<h:form>
        <p:commandButton process="@this" update="@form:updatedPanelGrid" value="crash" 
            action="#{inputNumberView.setFlag(true)}"/>
        <p:panel id="updatedPanelGrid">
            <c:if test="#{inputNumberView.flag}">
              <p:panelGrid class="ui-noborder">  
                  <f:facet name="header">  
                      <p:row>  
                          <p:column style="font-weight: bold;">inputNumber</p:column>  
                          <p:column style="font-weight: bold;">Numeric Value</p:column>  
                          <p:column style="font-weight: bold;">Description</p:column>  
                      </p:row>  
                  </f:facet>
                  <p:row>  
                      <p:column>  
                          <p:inputNumber id="input1" value="#{inputNumberView.input1}">  
                          </p:inputNumber>  
                      </p:column>  
                      ......

                  </p:row>
                </p:panelGrid>
              </c:if>
            </p:panel>
        </h:form>
```

## 6) Sample bean
Add this code to InputNumberView.java:

```
private boolean flag = false;

public boolean isFlag() {
    return flag;
}

public void setFlag(boolean flag) {
    this.flag = flag;
}
```

**Comment by cnsgithub** [comment]
Please remember the different lifecycles of JSTL and JSF. 

Did you try `h:panelGroup rendered="#{inputNumberView.flag}"` (or `ui:fragment`) instead of `c:if test="#{inputNumberView.flag}"`?

However, as you state that it works in Mojarra 2.3.2 this does not seem to be a PrimeFaces issue...

**Comment by martin654** [comment]
Hi!
The example provided is simplified. In the real-world scenario we use dynamic ui:includes like this:
`<ui:include src="#{bean.getFragmentPath}">`
and sometimes we have c:if tag around this include:
```
<c:if test="#{inputNumberView.flag}">
  <ui:include src="#{bean.getFragmentPath}" />
</c:if>
```
In the second case if there is a _p:inputNumber_ in the include and the test condition is false on initial page-load and the whole thing is updated by ajax - the JS exception occurs. 
I think this is valid usage...

**To your question:**
Yes, if I replace c:if with rendered attribute, it seems working OK in the same scenaro. Unfortunately dynamic ui:includes does not work inside "rendered conditioned" components (because of the lifecycle you mentioned).


I found another PF component not working in this scenario- **p:inputSwitch**. I think the problem occurs when component has it's own javascript defined like:

```
@ResourceDependency(library="primefaces", name="inputnumber/inputnumber.js")

@ResourceDependency(library="primefaces", name="inputswitch/inputswitch.js")
```

and it is somehow wrongly processed on the client side after ajax update...

Majority of PF components use 
`@ResourceDependency(library="primefaces", name="components.js")`
which is typically available in the page before the ajax request and they do not suffer from this issue...

Thanks

**Comment by cnsgithub** [comment]
Hi,

> The example provided is simplified

The example you provided is also incomplete (`output1` is missing). That makes it harder to reproduce.

> Unfortunately dynamic ui:includes does not work inside "rendered conditioned" components

Did you also try the rendered attribute within the included XHTML: `ui:composition rendered="..."`?

> the JS exception occurs

I could not reproduce this issue even after changing the showcase to Mojarra 2.2.17. I also tried different browsers with clean caches.

> I think the problem occurs when component has it's own javascript defined like

Not sure about this. I'll have a look at it.

Bye

**Comment by cnsgithub** [comment]
You could also try to wrap your` ui:include `within two ` h:panelGroup` components like so and update the outer one that has `id="wrapper"`:

```xml
<h:panelGroup id="wrapper">
    <h:panelGroup rendered="#{...}">
        <ui:include src="foo.xhtml"/>
    </h:panelGroup>
</h:panelGroup>
```

**Comment by cnsgithub** [comment]
Did you clean up your browser caches as well? Just to ensure you don't have a broken JS in your cache...

**Comment by martin654** [comment]
Hi,

> The example you provided is also incomplete (output1 is missing). That makes it harder to reproduce.

Sorry about the example, the p:ajax inside p:inputNumber is irrelevant. Trigger to this problem is <p:commandButton value="crash"> - I modified the code in the first post.

> Did you clean up your browser caches as well? Just to ensure you don't have a broken JS in your cache...

Yes I did. It did not help in my case.

> I could not reproduce this issue even after changing the showcase to Mojarra 2.2.17. I also tried different browsers with clean caches.

Are you sure? That would be wierd...

Thanks

**Comment by cnsgithub** [comment]
> Are you sure? That would be wierd...

Yes, almost. :wink: Maybe someone else could try to reproduce it, too?

**Comment by martin654** [comment]
There is a difference in response content between the two mojarra versions (2.3.2 and 2.2.17):

**2.3.2**
```
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>
  <changes>
    <update id="javax.faces.Resource">
      <![CDATA[<script type="text/javascript" src="/showcase/javax.faces.resource/inputnumber/inputnumber.js.xhtml?ln=primefaces&amp;v=6.2.3"></script><link type="text/css" rel="stylesheet" href="/showcase/javax.faces.resource/inputnumber/inputnumber.css.xhtml?ln=primefaces&amp;v=6.2.3" />]]>
    </update>
    <update id="j_idt114:updatedPanelGrid">
...
```

**2.2.17**
```
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1">
  <changes>
    <eval>
      <![CDATA[if(window.PrimeFaces){PrimeFaces.ajax.Utils.loadStylesheets(['/showcase/javax.faces.resource/inputnumber/inputnumber.css.xhtml?ln=primefaces&v=6.2.3']);PrimeFaces.ajax.Utils.loadScripts(['/showcase/javax.faces.resource/inputnumber/inputnumber.js.xhtml?ln=primefaces&v=6.2.3']);}]]>
    </eval>
...

```
Edit: sorry, made some mistakes in this post, corrected

**Comment by tandraschko** [comment]
Fyi:
In jsf2.3 a dynamic resource loading was implemented, therefore we skip our logic in 2.3.

Not sure whats wrong. Can you check if the response and the new resource is handeld correctly in our core.ajax.js?

**Comment by tandraschko** [comment]
Works also fine for me. Both with showcase and Mojarra 2.2 and 2.3.
So please provide a cloned primefaces-test project, otherwise it will be closed as 'can't replicate'.

**Comment by martin654** [comment]
Hi!
Forked primefaces-test: https://github.com/martin654/primefaces-test
First click on crash button causes the problem - numbers in inputs are not formatted as expected. 
Second click on crash button causes the inputs to be formatted properly.

I don't see the javascript console error with this forked project anymore, but the behavior of the form is the same.

**Comment by tandraschko** [comment]
The problem is the following:
https://github.com/primefaces/primefaces/issues/2303

we removed async=false, so the script is executed after our widgets initialization.

**Comment by tandraschko** [comment]
implemented this features now exactly the same way as in JSF 2.3.
Only the warning in the browser: "sync requests in the mainthread are deprecated..." will now occur again.

**Comment by martin654** [comment]
Thanks for the fix. Will it be in next Elite version? Thanks!

**Comment by tandraschko** [comment]
@mertsincan would you like to merge it to elite?

**Comment by melloware** [comment]
I will report under my PRO account to get it merged.
