### ISSUE TITLE
[Documentation] AjaxStatus: never shows the success and error facets.

### ISSUE THREAD

**Issue by bzurmaar** [primefaces/primefaces#3625]
## 1) Environment
- PrimeFaces version: 6.2.0
- Does it work on the newest released PrimeFaces version? No.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: Wildfly 12.0
- Affected browsers: All

## 2) Expected behavior
When an ajax request fails ajaxStatus should show its error facet. Likewise in the case of success the success facet should be shown.

## 3) Actual behavior
The complete event always immediately follows an error or success event. This causes the success and error facets to be hidden immediately in favor of the complete facet.

## 4) Steps to reproduce
Just use the sample code below and watch the error facet never appearing.

## 5) Sample XHTML
```xml
<p:ajaxStatus>
	<f:facet name="error">
		<h:outputText value="Error" />
	</f:facet>
	<f:facet name="success">
		<h:outputText value="Success" />
	</f:facet>
	<f:facet name="default">
		<h:outputText value="Idle" />
	</f:facet>
	<f:facet name="start">
		<h:outputText value="Sending" />
	</f:facet>
	<f:facet name="complete">
		<h:outputText value="Done" />
	</f:facet>
</p:ajaxStatus>

<h:form>
    <p:poll listener="#{counterView.increment}"/>
</h:form>
```

## 6) Sample bean
```java
package org.primefaces.showcase.view.ajax;
 
import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
 
@ManagedBean
@ViewScoped
public class CounterView implements Serializable {
     
    public void increment() {
        throw new IllegalStateException("Boy, that escalated quickly.");
    }
}
```
## 7) Analysis
From my point of view the culprit is https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js#L38 The complete event always marks the end of an ajax request regardless of its outcome. Because in the time between the success / error event and the complete event only the DOM tree is updated the error and success facets never have a chance to appear on screen at all. I see the following options to resolve this issue:

1. If no complete facet is defined and either the error or success facet is currently visible then don't hide them. Additionally you could issue a warning message, when the complete facet is defined together with a success or error facet to make the user aware they will never be shown.
1. Deprecate the success and error facets because they are useless in their current state.

**Comment by tandraschko** [comment]
I think we should just add an hint to the documentation, that if an "complete" facet is defined, the user will never see a "error" or "success" facet.

**Comment by bzurmaar** [comment]
Even in the abscence of a complete facet the error and success facets are never shown. At the moment it's completely impossible to show them at all.

**Comment by tandraschko** [comment]
OK i see, Would you please provide a PR that the error/sucess will not be hidden, if no complete facet is defined?

**Comment by bzurmaar** [comment]
Ok, I'll provide a PR in the next few days.

**Comment by bzurmaar** [comment]
Thanks for accepting the PR!

I guess you or the issue's assignee close this issue once the documentation has been updated? Sorry, I'm a novice in open source development.

**Comment by tandraschko** [comment]
your welcome!
Yep, exactly.
