### ISSUE TITLE
Add the relevance of nesting a form inside a dialog when using appendTo="@Body" to the showcase

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#3626]
In the documentation it is explicitly mentioned that a dialog should have its own form when using the appendTo with a value of body... IMHO it would be better to also explicitly add this to the showcase. It is an often recurring issue:

https://stackoverflow.com/questions/18958729/pcommandbutton-action-doesnt-work-inside-pdialog

**Comment by tandraschko** [comment]
A issue and PR in the showcase issuetracker is very welcome. It's not related to PF core.

**Comment by kukel** [comment]
Will do, sorry. Forgot there was a separate issuetracker
