### ISSUE TITLE
Calendar: pattern="yyyy" or  "MMM/yyyy" shows wrong date

### ISSUE THREAD

**Issue by newk5** [primefaces/primefaces#3627]
When using a pattern like "MMM/yyyy" or "yyyy" the p:calendar component shows a wrong date. With my use case I just need the user to choose a month (when using "MMM/yyyy") or a year (when using "yyyy"), but for some reason the calendar always seems to show the date 5 years ahead, 7 months ahead and 8 days ahead . I also tested with navigator="true" but the results were the same.

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: I cloned the primefaces-test repo which I believe is using jetty-8.1.9.v20130131 but I also tested on tomcat 8.5 and the results were the same
- Affected browsers: I tested on Chrome and Firefox.

## 2) Expected behavior
After chosing the date with p:calendar, if the user clicks the p:calendar input again to change to a different date, the calendar popup should be on the same date that's on the input

## 3) Actual behavior
After chosing the date with p:calendar, if the user clicks the p:calendar input again to change to a different date, the calendar popup shows a different date, more specifically it always shows  5 years, 7 months and 8 days ahead

## 4) Steps to reproduce
Simply create a <p:calendar> with pattern="yyyy" and with the value connected to a normal Date on a backing bean

## 5) Sample XHTML
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h1>#{testView.testString}</h1>
        <p:calendar pattern="yyyy"  value="#{testView.someDate}" navigator="true"  />

    </h:body>
</html>

## 6) Sample bean
```
package org.primefaces.test;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    private Date someDate = new Date();
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }    

 
    public Date getSomeDate() {
        return someDate;
    }

    public void setSomeDate(Date someDate) {
        this.someDate = someDate;
    }
}
```
Here's a GIF of the issue:
![2018-05-02_00-39-43](https://user-images.githubusercontent.com/32560510/39499914-dc69dc66-4da8-11e8-9772-b481678298ed.gif)

**Comment by tandraschko** [comment]
does it work with native jqueryui calendar?

**Comment by newk5** [comment]
After testing with the native jqueryUI datepicker I notice it does not work either, although the behaviour is a little different, the year pattern seems to be "yy" instead of "yyyy" and the date doesn't show years ahead but instead always shows the current date no matter what value I choose on the popup ( when using the "yy" or the "yyyy" pattern ). Here's a jsfiddle test showing whats happening: http://jsfiddle.net/wR3CU/447/

About the p:calendar, I'd suggest the addition of 2 new attributes, similar to the "timeOnly" attribute, a "monthsOnly" and "yearsOnly" attribute maybe?

**Comment by Treppenhouse** [comment]
I tested your jsfiddle example and for me it works completely fine!

**Comment by newk5** [comment]
Do the following:
- Choose yy or yyyy from the combobox
- Select a date from 2017
- Click on the input again to change the date
- What date does the calendar popup show now?

**Comment by iancesar** [comment]
Same bug here, any update?

**Comment by manhtq1996126** [comment]
How did you fix that?

**Comment by tandraschko** [comment]
@christophs78 could you do us a favor - if you the time - to go through all p:calender tickets and check if they are fixed in p:datePicker? If yes, we should close it. p:calendar is something like deprecated since p:datePicker.

**Comment by markusg80** [comment]
I think you cannot stop development of calendar component for version where it is not deprecated. Specialy if you not have same features in datepicker like in calendar. For example my issue #5060 is still not merged to the 8.0 branch. So i can not switch to Datepicker so long i not have this feature. So in this case you can deprecate calendar only in upcoming release abd you still have to fix bugs for calendar

**Comment by tandraschko** [comment]
Yep, i understand you.
But probably nobody will fix this 2 years old issue. Also wouldnt it be better to invest time in datePicker , instead of fixing jquery ui bugs?

**Comment by christophs78** [comment]
@tandraschko: I will try to check the old Calendar-issues within the next few weeks against DatePicker.

**Comment by melloware** [comment]
DatePicker does not have this issue so I reccommend switching to that component from Calendar since there is no telling when Jquery UI will fix the true underlying issue.
