### ISSUE TITLE
Partial rendering: insufficient CDATA encoding (XSS)

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3629]
## 1) Environment
- PrimeFaces version: 6.3-snapshot
- Mojarra version: 2.3.2

## 2) Expected behavior
Using `<![CDATA[` or `]]>` within submitted ajax strings must not break things when included in partial response.

## 3) Actual behavior
Client side partial response processing gets aborted without throwing any JS errors. This issue may lead to partial response (XML) injection/XSS as seen in https://github.com/primefaces/primefaces/issues/3623.

## 4) Steps to reproduce
1. Go to growl showcase (https://www.primefaces.org/showcase/ui/message/growl.xhtml)
2. Enter _foo_ and press the _Save_ button. The growl message will be shown correctly.
3. Enter _bar]]>_ and press the _Save_ button. Nothing will happen at all. No JS error will be thrown. The partial response will look like:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>
    <changes>
        <update id="j_idt114:growl">
            <![CDATA[<span id="j_idt114:growl" class="ui-growl-pl" data-widget="widget_j_idt114_growl" data-summary="data-summary" data-detail="data-detail" data-severity="all,error" data-redisplay="true"></span><script id="j_idt114:growl_s" type="text/javascript">PrimeFaces.cw("Growl","widget_j_idt114_growl",{id:"j_idt114:growl",sticky:true,life:6000,escape:true,keepAlive:false,msgs:[{summary:"Successful",detail:"Your message: bar]]>",severity:'info'},{summary:"Second Message",detail:"Additional Message Detail",severity:'info'}]});</script>]]>
        </update>
        <update id="j_id1:javax.faces.ViewState:0">
            <![CDATA[2828231543112704473:4881115358210490980]]>
        </update>
    </changes>
</partial-response>
```

## 5) Misc
- Further reading: https://www.owasp.org/index.php/Testing_for_XML_Injection_(OTG-INPVAL-008)
- I am not yet sure if this issue is related to PrimeFaces' `PrimePartialResponseWriter `or Mojarra's `PartialResponseWriter`.

**Comment by tandraschko** [comment]
Would be great next time if you could check before if it's PF or Mojarra related :P

**Comment by cnsgithub** [comment]
Mojarra's `HtmlResponseWriter.writeText `has this piece of code where `dontEscape `evaluates to `true `if we are writing either a `script` or `style `element:
```java
    public void writeText(Object text, String componentPropertyName)
          throws IOException {
...
        if (dontEscape) {
            writer.write(textStr);
...
        } else { // if writingCdata
...
                writeEscaped(textStr.toCharArray(), 0, textLen);
...
```

Now, for the growl example mentioned above, we definetely write javascript in `GrowlRenderer`, initiated by `WidgetBuilder`. In `encodeMessages`, line 102, we call `HtmlResponseWriter.writeText `assuming that XML escaping is done automatically. But as mentioned before, it gets automatically turned off and we are able to inject XML like` ]]>` or `<update>` in our `partial-response`. Doing that results - at least in this case - most probably in syntactically wrong XML. However, we could also prepare well-formed payloads that allow for XSS. And yes, with the current blacklisting `escapeText ` (instead of OWASP whitelisting) implementation for escaping javascript we could probably break out. This is just one more reason to merge https://github.com/primefaces/primefaces/pull/3525. Maybe OWASP javascript encoding would also solve the CDATA end tag injection as a positive side-effect. However, I am not totally sure if Mojarra shouldn't test for `dontEscape && writingCdata` (in `HtmlResponseWriter.writeText`) and somehow escape `<![CDATA[` and `]]>` occurrences. Any thoughts?

@tandraschko After that being said, I think it's related to both PF and Mojarra. :wink: Could you please add the security label?

**Comment by cnsgithub** [comment]
Just filed an issue at Mojarra as well: https://github.com/javaserverfaces/mojarra/issues/4370

**Comment by Naldorenses** [comment]
Hey there, I am sorry if I shouldn't have posted this here. My question would be if we can expect this issue to be fixed with 6.3? We found this issue to occur in our company as well. Could you also make sure to cover every component, we also experienced this under inputText?

Once again sorry if this is the wrong place to post this, we didn't mean to step on anyone's toes.

**Comment by cnsgithub** [comment]
See https://github.com/eclipse-ee4j/mojarra/issues/4392.

**Comment by tandraschko** [comment]
@cnsgithub Can we close it on our side?

**Comment by cnsgithub** [comment]
@tandraschko Sorry, I have not yet tested with MyFaces + PrimeFaces (or at least cannot remember right now). And unfortunately, I am currently not able to do so. Would you like to give it a try? MyFaces itself seems not to be affected. If MyFaces + PrimeFaces in combination fails, that would mean that PrimeFaces on its own is affected as well. Otherwise we could close the issue and hope that Mojarra guys get it fixed asap.

**Comment by tandraschko** [comment]
Tested, works fine.
