### ISSUE TITLE
Cache invalidation for tabView?

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#3634]
Hi,

I'm trying to invalidate cached tabViews and I've looked through the documentation and googled, but didn't find anything. Such a feature would be very useful and could save whole page reloads while still providing a caching mechanism for tabs.

Is there a way to achieve this or a workaround?

I'm using PrimeFaces version 6.2.

Thank you very much!

**Comment by tandraschko** [comment]
questions -> forum.
