### ISSUE TITLE
InputGroup: support for inputNumber and calendar

### ISSUE THREAD

**Issue by matsandreassen** [primefaces/primefaces#3645]
## 1) Environment
- PrimeFaces version: 6.2.3, Mojarra 2.2.17
- Application server + version: Tomcat 8.5.27
- Affected browsers: At least newest Chrome and Edge

## 2) Expected behavior
Well, I _hoped_ for a perfectly aligned ui-inputgroup-addon but I'm thinking that the components I'm using haven't been tested with the input group functionality.

Since support for "my" components isn't demonstrated in the showcase, this issue becomes "New feature", I guess?
...

## 3) Actual behavior
![input group problems](https://user-images.githubusercontent.com/1419430/39691293-7392879a-51dd-11e8-8368-8081a3b551ee.png)
..

## 4) Steps to reproduce

Combine ui-inputgroup-addon (either FontAwesome icon or textual) with inputNumber or calendar. The alignment is just a few pixels off.

## 5) Sample XHTML

```xml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html>
<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <f:view>

        <h:head />

        <h:body>
            <h:form>

                <div class="ui-g ui-fluid">
                    <div class="ui-g-12">
                        <div class="ui-inputgroup">
                            <div class="ui-inputgroup-addon">Fylke</div>
                            <p:inputNumber value="2"/>
                        </div>
                    </div>
                </div>

            </h:form>

        </h:body>
    </f:view>
</html>
```

**Comment by tandraschko** [comment]
Please provide the example or it will be closed as invalid.

**Comment by matsandreassen** [comment]
Sorry, I'll do better next time. ;) Example is now added.

**Comment by tandraschko** [comment]
Would be great if you can provide a PR.

**Comment by matsandreassen** [comment]
We use the new PF Designer to create our theme. I _thought_ this was a PF bug since it looks fine in the Designer while we tweak the theme. I discovered now that it also looks fine if I revert to the default PF theme in web.xml.

_Somehow_ this seems to be related to our theme generation. Sorry to have wasted your time on this. It's quite puzzling. :(

**Comment by tandraschko** [comment]
All right! I don't know how PrimeTek handle the support about the designer but here it's just for the community stuff, so i will close it.
