### ISSUE TITLE
DataTable: column names with dynamic columns gives null value

### ISSUE THREAD

**Issue by krishnakittu** [primefaces/primefaces#3646]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: glassfish 3.2
- Affected browsers: All

## 2) Expected behavior
column names should be available in managed bean.

 ...

## 3) Actual behavior
On making of col reorder in browser the corresponding ajax method giving null values.
How to get the value of column names in managed bean. Please advice

..

## 4) Steps to reproduce
 Please check the below files
.. 

## 5) Sample XHTML
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      >
      <h:head>
        <title>Column Reorder Event</title>
    </h:head>
    <h:body>
        <h:form id="form">
    <p:growl id="msgs" showDetail="true" />

    <p:dataTable id="cars" var="car" value="#{dtColumnsView.cars1}" draggableColumns="true">  
    <p:ajax event="colReorder" listener="#{dtColumnsView.onColumnReorder}"/>                  
        <p:columns value="#{dtColumnsView.columns}" var="column">
            <f:facet name="header">
                <h:outputText value="#{column.header}" />
            </f:facet>
            <h:outputText value="ID" />
        </p:columns>
    </p:dataTable>
</h:form>

    </h:body>

  </html>

## 6) Sample bean
package test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.component.html.HtmlOutputText;
import javax.faces.event.AjaxBehaviorEvent;

import org.primefaces.component.datatable.DataTable;

@ManagedBean(name="dtColumnsView")
public class ColReorder implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private List<Car> cars1;
	
	
	 private List<ColumnModel> columns;
	
	public List<ColumnModel> getColumns() {
		return columns;
	}

	public void setColumns(List<ColumnModel> columns) {
		this.columns = columns;
	}

	private CarService service=new CarService();

	public ColReorder() {
		super();
		init();
	}

	private void init() {
		cars1=service.createCars(10);
		List<ColumnModel> lst=new ArrayList<ColumnModel>();
		for(int i=0;i<=5;i++){
			ColumnModel c=new ColumnModel("test"+i, i+"");
			lst.add(c);
		}
		columns=lst;
	}

	public List<Car> getCars1() {
		return cars1;
	}

	public void setCars1(List<Car> cars1) {
		this.cars1 = cars1;
	}
	
	
	public void onColumnReorder(AjaxBehaviorEvent event){
		DataTable d=(DataTable)event.getSource();
		for(org.primefaces.component.api.UIColumn ui:d.getColumns()){
			System.out.println(((HtmlOutputText)ui.getFacet("header")).getValue());
		}
	}
	

}

..

**Comment by cnsgithub** [comment]
I think this is rather a forum question.

Anyways, did you try `DataTable.getDynamicColumns` instead of `getColumns`?

**Comment by krishnakittu** [comment]
I tried In all the ways. Always I am getting null value if it is dynamic Column. But when I use static column I am getting a value in bean.

**Comment by kukel** [comment]
@tandraschko: defect AND enhancement at the same time feels like a contradiction. Should the content of the header return the 'rendered' value of it or just the 'unrendered' EL?  If I remember correctly, the position IS returned, so if one keeps a reference to the list that should produce the column names, you can get it that way...

**Comment by tandraschko** [comment]
I don't have time to check all issues in detail and check if it worked before or not... ;) So i set both labels instead of no-label.

**Comment by kukel** [comment]
That is confusing for posters. OP in this case thinks it is an accepted
bug. Maybe a "review" tag "Triage" is better then.

**Comment by krishnakittu** [comment]
Thanks @kukel. At present I am able to complete my task with indexes.
