### ISSUE TITLE
p:ajax with update blocks commandbutton click when focused

### ISSUE THREAD

**Issue by koflerdavidgrawe** [primefaces/primefaces#3647]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) - Did not try
- Application server + version: Tomcat 8.5
- Affected browsers: FF/Chrome

# 2) Expected behavior
A focused input element with p:ajax with attribute update set does not affect command elements when they are clicked

## 3) Actual behavior
A focused input element with p:ajax with attribute update set blocks command elements when they are clicked

## 4) Steps to reproduce
[jsf_bug_reproducer.zip](https://github.com/primefaces/primefaces/files/1980179/jsf_bug_reproducer.zip)

## 5) Sample XHTML
		<p:inputNumber value="#{testBean.test}" onblur="console.log('blur')">
			<p:ajax update="@all" />
		</p:inputNumber>
		<h:commandButton onclick="console.log('click')" />

## 6) Sample bean
Does not apply

## 7) Underlying cause:
When button is clicked the input element is blurred (focus lost) which blocks the button click event.

**Comment by tandraschko** [comment]
Deeper analysis and PR are very welcome.

**Comment by melloware** [comment]
Reproducer:
[pf-3647.zip](https://github.com/primefaces/primefaces/files/4308270/pf-3647.zip)

Works fine in Mojarra 2.2/2.3 and MyFaces 2.2/2.3.  Closing ticket.
