### ISSUE TITLE
RemoteCommand: name="onload" not triggering p:ajaxStatus client side functions

### ISSUE THREAD

**Issue by BryanV91** [primefaces/primefaces#3648]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: WildFly 11
- Affected browsers: Chrome 66.0.3359.139, Firefox 59.0.3

## 2) Expected behavior

p:remoteCommand name="onload" + p:ajaxStatus should be executing onstart, oncomplete, onsuccess and onerror functions, but since PF (6.2) it is not working on Chrome. 

It used to work fine on PF (6.1).

## 3) Actual behavior

AJAX is invoked when the web page has completely loaded all content, but it is not executing the client side functions.

## 4) Steps to reproduce

See `test.xhtml`

## 5) Sample XHTML

`test.xhtml`

```
...
<h:form id="form">
<p:remoteCommand id="remote" name="onload" process="@this"
        action="#{someBean.someAction()}"
	global="true" partialSubmit="true" />
<p:ajaxStatus id="ajaxStatus"
		onstart="$('#ajax-status-dlg').modal('show')"
		onsuccess="$('#ajax-status-dlg').modal('hide')"
		onerror="$('#ajax-status-dlg').modal('hide')" />
	<div id="ajax-status-dlg" class="modal" data-backdrop="static"
		data-keyboard="false">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-body">
					<div class="text-center">
						Loading...
					</div>
				</div>
			</div>
		</div>
	</div>
</h:form>
...
```
## 6) Additional notes

p:remoteCommand + p:ajaxStatus work normally with others functions that don't involve name="onload".

**Comment by tandraschko** [comment]
But it does work fine if the remoteCommand is manually invoked later?

**Comment by BryanV91** [comment]
Yes, it does work properly if it is invoked later.

**Comment by tandraschko** [comment]
It would be great if you could check the problem deeper and provide a PR to fix it.

**Comment by BryanV91** [comment]
Additional info:

When I hit F5, remoteCommand is not invoking ajaxStatus (onstart, oncomplete, onsuccess, onerror). But when I hit Ctrl + F5, it works normally.

**Comment by tandraschko** [comment]
@melloware interessted to check this?
Maybe the name is not valid and should be removed + autoRun=true instead

**Comment by melloware** [comment]
Yep I will check this

**Comment by BryanV91** [comment]
@melloware 

Running now on PF 8.0 works as expected with `name="onload"` and not with `autoRun=true`

**Comment by tandraschko** [comment]
OK
I still think that should not be used as onload runs before $(function())
But it should work with MoveScriptsToBottom
