### ISSUE TITLE
DataTable: Advanced TableState properties

### ISSUE THREAD

**Issue by NEOMNI** [primefaces/primefaces#3652]
## 1) Environment
- PrimeFaces version: 6.1.8
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 8
- Affected browsers: All

## 2) Expected behavior
Extend TableState feature of DataTable to support saving and restoring the column widths

## 3) Actual behavior
TableState only supports sorting (sort by, sort order, sort field, ...)

## 5) Sample XHTML
    <p:dataTable id="tableStateDT" var="car" value="#{dtTableStateView.cars}" widgetVar="carsTable" multiViewState="true" rows="10" paginator="true" paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                 rowsPerPageTemplate="5,10,15" selectionMode="single" selection="#{dtTableStateView.selectedCar}" rowKey="#{car.id}" emptyMessage="No cars found with given criteria" filteredValue="#{dtTableStateView.filteredCars}">

**Comment by tandraschko** [comment]
Would be great if you could sponsor it or provide a PR.

**Comment by mertsincan** [comment]
> Extend TableState feature of DataTable to support saving and restoring the column widths

How do you change column widths? Do you use resizableColumns attribute on DataTable? I added multiViewState support to resizeable DataTable on 6.1.10+. Please see; https://github.com/primefaces/primefaces/issues/3046

**Comment by NEOMNI** [comment]
We use resizableColumns with a self-created column selection dialog to allow the user to save his column selection in the database. We want to extend this to include column sorting and column widths.

**Comment by melloware** [comment]
Fixed with #3046 in PF 6.1.10
