### ISSUE TITLE
SelectOneMenu: after refreshing the widget in an AJAX request the popup opens at wrong position

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#3654]
If an AJAX request updates a SelectOneMenu widget and user opens the popup of that SelectOneMenu the popup opens at wrong position: top left corner of the body instead of aligned to the widget.

Reason:
In PF 6.1 SelectOneMenu had following function, called from init():
```
appendPanel: function() {
        var container = this.cfg.appendTo ? PrimeFaces.expressions.SearchExpressionFacade.resolveComponentsAsSelector(this.cfg.appendTo): $(document.body);

        if(!container.is(this.jq)) {
            **container.children(this.panelId).remove();**
            this.panel.appendTo(container);
        }
    }
```
This removed the old popup panel ('..._panel') before appending the new panel.

In PF 6.2 this method was removed and instead init() contains following code:
`PrimeFaces.utils.registerDynamicOverlay(this, this.panel, this.id + '_panel');`
The passed argument "this.panel" is a two element list, because `this.panel = $(this.panelId)` finds the old and the new popup panel.  `PrimeFaces.utils.registerDynamicOverlay` doesn't work correctly with such a two element list: it calls `PrimeFaces.utils.appendDynamicOverlay` which does nothing because if `(!elementParent.is(appendTo) && !appendTo.is(overlay))` returns false for the two element `overlay` var.

## 1) Environment
- PrimeFaces version: 6.2.2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 8 (arbitrary)
- Affected browsers: IE, FF, Chrome (arbitrary)

## 2) Expected behavior
the popup panel opens aligned to the widget (as normal for a select one dropdown widget)

## 3) Actual behavior
the popup panel opens at the top left corner of the HTML body

## 4) Steps to reproduce
perform an AJAX call which updates the SelectOneMenu widget in it's response. Then open the SelectOneMenu's popup panel via clicking the widget. 

## 5) Sample XHTML
```
<p:selectOneMenu id="mySom" value="#{bean.mySom}" effect="none">
  <f:selectItems value="#{bean.selectItemsMySom}" />
</p:selectOneMenu>

<p:commandButton id="updateMySom" ajax="true" value="AJAX Action" action="#{bean.updateMySom}" process="@all" update="mySom" />
```

## 6) Sample bean
straight forward

**Comment by tandraschko** [comment]
As you didn't provide the bean, it's actually invalid but i think i fixed the issues so please try.

**Comment by tandraschko** [comment]
Will close it for now.
