### ISSUE TITLE
Improper theming

### ISSUE THREAD

**Issue by abelet** [primefaces/primefaces#3658]
Components.css seems to have a lot of style definitions which should be placed in theme files.

For example:

.ui-tooltip .ui-tooltip-text {
    padding: 3px 10px;
    background-color: #4c4c4c;
    background-image: none;
    color: #fff;
}

**Comment by melloware** [comment]
While I agree this type of css doesn’t belong there it’s just a default that all Primetek premium themes override.  And since the jquery themeroller themes are deprecated this is not really an issue.
