### ISSUE TITLE
p:ajax: javax.el.MethodNotFoundException with listener on Tomcat 8.5.31

### ISSUE THREAD

**Issue by ttsiebzehntt** [primefaces/primefaces#3659]
## 1) Environment
- PrimeFaces version: 6.2.2
- Does it work on the newest released PrimeFaces version? Version? No
- Application server + version: Tomcat 8.5.31
- Affected browsers: All

## 2) Expected behavior
p:ajax Listener work as designed.

## 3) Actual behavior
After updating Tomcat from 8.5.24 to 8.5.31 the Ajax Listener stopped working. The following Exceptions appear in the logs:

```
WARNING: javax.el.MethodNotFoundException: Method not found: SelectionView.onRowSelect(org.primefaces.event.SelectEvent)
```

## 4) Steps to reproduce
See sample XHTML and Bean Tomcat 8.5.31

## 5) Sample XHTML
Composite Component:
```xml
<ui:component ...>
  <composite:interface>
    <composite:attribute name="rowSelectAction" method-signature="void action(org.primefaces.event.SelectEvent)" />
  </composite:interface>

  <composite:implementation>
    <p:dataTable>
      <p:ajax event="rowSelect" listener="#{cc.attrs.rowSelectAction}" />
  ...
    </p:dataTable>
  </composite:implementation>
</ui:component>
```

view:
```xml
<xxx:component rowSelectAction="#{dtSelectionView.onRowSelect}" />
```

## 6) Sample bean
```java
@ManagedBean(name="dtSelectionView")
@ViewScoped
public class SelectionView implements Serializable {
  public void onRowSelect(SelectEvent event) {
  ...
  }
}
```

## 7) Workaround

Stay on Tomcat 8.5.24

## 8) Possible Cause

I think the search behaviour in `org.apache.el.util.ReflectionUtil.getMethod` changed with http://svn.apache.org/viewvc/tomcat/tc8.5.x/trunk/java/org/apache/el/util/ReflectionUtil.java?r1=1788324&r2=1817501

They now compare the requested parameter class types and passed values. Since you don't provide any values in `org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processAjaxBehavior` the method isn't found. The try catch blocks don't work because the `MethodNotFoundException` is not propagated. There is a fallback to search for a property. That's why a `PropertyNotFoundException` is thrown.

**Comment by tandraschko** [comment]
Hmmm not sure if it's our bug then.
If you check the MethodExpression#invoke docu:

>   * @throws PropertyNotFoundException if one of the property
     *     resolutions failed because a specified variable or property 
     *     does not exist or is not readable.
     * @throws MethodNotFoundException if no suitable method can be found.

The bean itself is available and will be resolved correctly, only the method without parameters can't be found. So it's actually clear for me that a MethodNotFoundException should be thrown.

**Comment by ttsiebzehntt** [comment]
@tandraschko Sorry for the confusion. It was not as easy as running the showcase. The error only occures if you use a composite component in between. 
When you first search for the method without the parameter, the tomcat el impl is searching for a method with the parameter type SelectEvent because of the method-signiture in the composite component.
Till tomcat 8.5.24 the method was found although you were searching for a method without parameters. Since 8.5.25 the method isn't found because the required parameter types (from the composite component method-signiture) don't match your passed parameters (none).

**Comment by tandraschko** [comment]
It's now really confusing ;)

Just for your understanding:
When creating the Behavior, we eagerly lookup 3 methods:
- the listener without arguments
- the listener with AjaxBehaviorEvent as argument
- the listener with the real event class

now, when invoking the the ajax behavior, we invoke one after other if the the previous method can't be found.

**Comment by tandraschko** [comment]
So, we invoke the first listener and if it throws a propertynotfound exception, we assume, which is correct IMO, that the previous property can't be found.

for example:
cc.attrs.myBean.someListener

A propertyNotFound should be thrown when myBean is null here, not when the listener with argument isn't available.

**Comment by ttsiebzehntt** [comment]
@tandraschko 

> A propertyNotFound should be thrown when myBean is null here, not when the listener with argument isn't available.

The PropertyNotFoundException is thrown starting from Tomcat 8.5.25. Would you mind adding it to the try catch block in `AjaxBehaviorListenerImpl.processAjaxBehavior` and fall back to `processArgListener` like with the MethodNotFoundException.

**Comment by tandraschko** [comment]
I understand that it is thrown now but IMO tomcat shouldn't throw it.
Does it work with both mojarra and myfaces f:ajax correctly?

**Comment by ttsiebzehntt** [comment]
@tandraschko Sorry, I can only test it with mojarra (2.2.16). It's also not working, as they only catch MethodNotFoundException and IllegalArgumentException (https://github.com/javaserverfaces/mojarra/blob/2.2.16/jsf-ri/src/main/java/com/sun/faces/facelets/tag/jsf/core/AjaxHandler.java#L460)

**Comment by tandraschko** [comment]
i see :/
I hope you can contact the tomcat devs and ask why they do it. IMO it makes no sense to throw a PropertyNotFoundException when "everyone" expects a MethodNotFoundException.

**Comment by tandraschko** [comment]
Will close it for now.

**Comment by spadinha1** [comment]
Hello, I am having the same problem.

Did you found a solution ?

I cant update tomcat because ... selectevent inside component not works.

<ui:component...
<cc:interface>
...
		<cc:attribute name="actionSelect" required="true"
			method-signature="void action(org.primefaces.event.SelectEvent)" />
...
<cc:implementation>

<p:dataTable...
<p:ajax event="rowSelect" listener="#{cc.attrs.actionSelect}" ...
</p:dataTable>
</ui:component>


07-Dec-2018 16:33:26.719 SEVERE [http-nio-8080-exec-6] org.primefaces.application.exceptionhandler.PrimeExceptionHandler.logException Property [selecionarTargetFornecedor] not found on type [br.com.santaalice.gsa.web.controller.financeiro.pagar.RazaoFornecedorController]
 javax.el.PropertyNotFoundException: Property [selecionarTargetFornecedor] not found on type [br.com.santaalice.gsa.web.controller.financeiro.pagar.RazaoFornecedorController]
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:260)
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:212)
	at javax.el.BeanELResolver.property(BeanELResolver.java:347)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:92)


PS. Error only on Linux Server. Windows Server works...

regards,

**Comment by NOTiFYcouk** [comment]
I am having the same problem when deploying to JBoss WildFly 16.0.0.Final using Undertow 2.0.19.Final & Mojarra 2.3.9.SP01 . 
https://forum.primefaces.org/viewtopic.php?f=3&t=58877&p=175250#p175250
