### ISSUE TITLE
p:tree - add "fullLeaf" feature (Base leaf decision not on number of child objects and prohibit drop for leaf types)

### ISSUE THREAD

**Issue by fatdevelops** [primefaces/primefaces#366]
Create a parameter called e.g. "fullLeaf" for p:tree. 

If "fullLeaf" is set to false, p:tree will behave as it currently does. Hence, the decision, if the TreeNode object is a leaf is based on the number of ist children. On top of this, dropping other leaves into a leaf is not prohibitted.

If fullLeaf is set to true, the decision if the TreeNode object is a leaf is based on a (B)boolean value that the developer can set. Moreover the user is not allowed to drop nodes into leaf nodes. The p:tree simply remains as is and the TreeNode is not automatically added to the tree. 

If you currently try to avoid dropping a TreeNode into a leaf, you have to manually reset the TreeNode objects in your tree. If a "fullLeaf" feature is not desired, an option that avoids dropping into leaf nodes on client side would be great.

**Comment by cagataycivici** [comment]
Can't you just create a custom TreeNode implementation and override isLeaf?

**Comment by fatdevelops** [comment]
Yes, that is indeed what I did. The main problem is that you are allowed to drop nodes in a leaf node (isLeaf() returns true) when drag and drop is enabled on client side which is not necessarily what you want depending on the use case (no possible restrictions here). If you have a p:tree that represents a file/document structure and you enable drag and drop, a user is able to drop a folder (isLeaf() returns false) into a file (isLeaf() returns true) which seems kind of weird. You need to manually "reset" the tree nodes on dragdrop ajax event which seems a bit tedious.
