### ISSUE TITLE
TextEditor: valueChangeListener is never called

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#3664]
I test my Web application on Primefaces 6.3 for another bug and I have seen that valueChangeListener() function of <p:textEditor> is nver called using Primefaces 6.3 !

I use Glassfish 4.1 with JSF 2.2.

## 1) Environment
- PrimeFaces version: 6.3
- Does it work on the newest released PrimeFaces version? NO 6.3 
- Does it work on the newest sources in GitHub? NO
- Application server + version: Glassfish 4.1 (JSF 2.0)
- Affected browsers: Chrome, Opera

## 2) Expected behavior

I expect that when new text are written in <p:textEditor> valueChangeListener function is called.

## 3) Actual behavior

On Primefaces 6.2.3 and 6.3, listener is never called.

## 4) Steps to reproduce

1. Create a <p:editor> with valueChangeListener attribute
2. Put a break point in function linked to listener
3. enter something in editor widget
4. see that listener is never called !!!

## 5) Sample XHTML

```
<p:textEditor        
    id="TplCommentEditor"
    value="TEST"
    valueChangeListener="#{testViewController.changeAjaxListener}"
    />
```

## 6) Sample bean

```
public void changeAjaxListener(ValueChangeEvent e)
    {
    int i0 = 0;
    }
```

**Comment by tandraschko** [comment]
Deeper analysis or PR is very welcome.

**Comment by tandraschko** [comment]
It would be really great if you could do better tickets in future with a whole example or providing a forked primefaces-test project, otherwise i won't waste my time again.
I just works fine when submitting the form, which contains the textEditor with a commandButton.

**Comment by tandraschko** [comment]
NOTE: i'm doing this in my freetime here and i only would like to work on real bugs - and the issue tracker is not a forum for discuss problems on how to use primefaces. Maybe just use the forum next time or stackoverflow.

**Comment by schlebe** [comment]
Sorry, I have reinstalled PrimeFaces 5.1.14 and the valueChangeListener of <p:textEditor> is only call after pressing on a SUBMIT button.
I thought that the listener is changed every time I press a character.
It is clearly explain by C.Balus on StackOverflow at following link
[https://stackoverflow.com/questions/11879138/when-to-use-valuechangelistener-or-fajax-listener](https://stackoverflow.com/questions/11879138/when-to-use-valuechangelistener-or-fajax-listener)
Sorry.
