### ISSUE TITLE
DataTable: scrollable, header doesn't move with RTL

### ISSUE THREAD

**Issue by pfdeveloper** [primefaces/primefaces#3667]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? NO  
 https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:  apache tomcat 8
- Affected browsers: all 

## 2) Expected behavior

...primefaces datatable rtl scrollable="true" header move with scroll like ltr

## 3) Actual behavior

..primefaces datatable rtl scrollable="true" header doesnt move with scroll

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

<p:dataTable var="car" dir="rtl" scollable="true" scrollheight="170" value="#{dtBasicView.cars}">
    <p:column headerText="Id">
        <h:outputText value="#{car.id}" />
    </p:column>
 
    <p:column headerText="Year">
        <h:outputText value="#{car.year}" />
    </p:column>
 
    <p:column headerText="Brand">
        <h:outputText value="#{car.brand}" />
    </p:column>
 
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
</p:dataTable>

## 6) Sample bean

..
package org.primefaces.showcase.view.data.datatable;
 
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.primefaces.showcase.domain.Car;
import org.primefaces.showcase.service.CarService;
 
@ManagedBean(name="dtBasicView")
@ViewScoped
public class BasicView implements Serializable {
     
    private List<Car> cars;
     
    @ManagedProperty("#{carService}")
    private CarService service;
 
    @PostConstruct
    public void init() {
        cars = service.createCars(10);
    }
     
    public List<Car> getCars() {
        return cars;
    }
 
    public void setService(CarService service) {
        this.service = service;
    }
}

**Comment by tandraschko** [comment]
Still invalid... no examples, no screenshots, nothing.

**Comment by pfdeveloper** [comment]
in general primefaces component doesnt support  rtl orientation .....thank you

**Comment by tandraschko** [comment]
Sorry but we are no "clairvoyant". A issue consists of one problem, for a specific component.
In general PrimeFaces does support RTL, maybe not for all components.

So please change this issue to be correct and reproducable, or use PrimeFaces PRO to get payed support.

**Comment by pfdeveloper** [comment]
i put the direction of main container of datatable to ltr then put the direction of 
.ui-datatable-scrollable table{ 
direction: rtl; 
}
.ui-datatable .ui-datatble-scrollable-body{
direction:rtl;
}

**Comment by melloware** [comment]
Fixed with issue: https://github.com/primefaces/primefaces/issues/4950
