### ISSUE TITLE
improvement request to add in Migration Guide (data-widgetvar)

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#3671]
To improve your migration guide from 6.2 to 6.3, I propose you add that you have replaced data-widgetvar attribute name by data-widget !
Like requested for another issue, I have tested a specific issue using last build of Primefaces (version 6.3) but I have encounter some Javascript problems because data-widgetvar name has been changed.

**Comment by tandraschko** [comment]
data-widgetvar has been removed from all other components, we just leave it for the dialog framework.
Also it's not a API which should be used by the users, so i don't think we need to adjust the migration guide.
Otherwise we would need to add every small internal change to the migration guide.
