### ISSUE TITLE
SelectCheckboxMenu/SelectManyCheckbox: selected values not set in bean when using grouping 

### ISSUE THREAD

**Issue by georgwolf** [primefaces/primefaces#3676]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? 6.2.4 is fine
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source): No

## 2) Expected behavior
When using SelectCheckboxMenu/SelectManyCheckbox with grouped SelectItems checked values are set in backing bean after form submit

## 3) Actual behavior
Empty selection set in backing bean after form submit

## 4) Steps to reproduce
1. Use showcase https://www.primefaces.org/showcase/ui/input/manyCheckbox.xhtml and https://www.primefaces.org/showcase/ui/input/manyCheckbox.xhtml
2. Select something in the grouped selects and submit form
3. -> Empty selection despite having checked values

The issue is introduced by #3299 which doesn't take SelectItemGroup into account here: https://github.com/primefaces/primefaces/pull/3299/files#diff-e25e2f2d8155d591f2de2656bf78310aR298

**Comment by tandraschko** [comment]
@cnsgithub / @melloware can you check this? Otherwise i have to revert

**Comment by tandraschko** [comment]
Thanks!

**Comment by georgwolf** [comment]
Added #3681 as a possible fix

**Comment by tandraschko** [comment]
Maybe fixed or a new PR required - please see my comment in the PR.

**Comment by georgwolf** [comment]
Your refactoring solves this issue but reintroduces #3296 as disabled but initally checked values are now lost after submit - this affects grouped and normal SelectCheckboxMenu/SelectManyCheckbox. It also reintroduces #3264 for grouped SelectCheckboxMenu/SelectManyCheckbox as disabled children of a SelectItemGroup can be submitted succesfully now by manipulating hidden input on client side.

**Comment by tandraschko** [comment]
Would be great if you could provides ideas to fix those both cases.

**Comment by tandraschko** [comment]
i reverted my changes - but will do some cosmetics.
Maybe you can check it later.

**Comment by georgwolf** [comment]
Merged your cosmetics against the fix for including items in a SelectItemGroup
