### ISSUE TITLE
SelectCheckboxMenu: Value instead of label shown after submit for grouped, multiple checkbox menu

### ISSUE THREAD

**Issue by georgwolf** [primefaces/primefaces#3678]
## 1) Environment
- PrimeFaces version: 6.2.4
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No

## 2) Expected behavior
SelectCheckboxMenu with multiple=true and grouped select items displays the label of the selected values after form submit in the input

## 3) Actual behavior
The value instead of the label of the selected items is displayed after form submit (non ajax)

## 4) Steps to reproduce

1. Check some items in the SelectCheckboxMenu and submit form
2. After rerendering values instead of labels are displayed

## 5) Sample XHTML
```
<h:form>
	<h:outputLabel for="grouped" value="Grouped" />
	<p:selectCheckboxMenu id="grouped" 
			value="#{checkboxMb.groupedSelection}"
			multiple="true"
			converter="javax.faces.Integer">
		<f:selectItems value="#{checkboxMb.groupedSelectItems}" />
	</p:selectCheckboxMenu>
	
	<h:commandButton value="Submit" />
</h:form>
```

## 6) Sample bean

```
package demo;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Model;
import javax.faces.model.SelectItem;
import javax.faces.model.SelectItemGroup;

@Model
public class CheckboxMb{
    private List<SelectItem> groupedItems     = null;
    private List<Integer>    groupedSelection = null;

    @PostConstruct
    public void init() {
        this.groupedItems = new ArrayList<>();
        SelectItemGroup group = new SelectItemGroup("German Cars");
        group.setSelectItems(new SelectItem[] {new SelectItem(1, "Audi"), new SelectItem(2, "BMW")});
        this.groupedItems.add(group);
		
        group = new SelectItemGroup("American Cars");
        group.setSelectItems(new SelectItem[] {new SelectItem(3, "Chrysler"), new SelectItem(4, "Ford")});
        this.groupedItems.add(group);
    }
    public List<SelectItem> getGroupedSelectItems(){
        return this.groupedItems;
    }
    public List<Integer> getGroupedSelection(){
        return this.groupedSelection;
    }
    public void setGroupedSelection(final List<Integer> groupedSelection){
        this.groupedSelection = groupedSelection;
    }
}
```

Root cause: SelectItemGroup not taken into account here: https://github.com/primefaces/primefaces/blob/1285d8f0960a964a394260ff39af9ff666da9a50/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java#L233-L239

**Comment by tandraschko** [comment]
a PR would be great

**Comment by georgwolf** [comment]
Created #3680 as a fix

**Comment by georgwolf** [comment]
Could this be included in the next 6.2 Elite release?

**Comment by ArpitAgrawal643** [comment]
Value instead of label is displayed in the page for me in select checkboxmenu for me , 
I have upgraded to primefaces 8.0 . what specific i need to take

**Comment by melloware** [comment]
@ArpitAgrawal643 you won't get much help here about 8.0 as 13.0.5 is the latest version. If you can reproduce the issue on 13.0.5 then please open another ticket.
