### ISSUE TITLE
Full support for FontAwesome's stacked icons and effects

### ISSUE THREAD

**Issue by fatdevelops** [primefaces/primefaces#368]
A p:commandLink is able to have an inner span and render correctly (which means that the span element resides inside the html button), whereas a p:commandButton is not.
If you have a p:commandButton with an inner span, it is always rendered outside the html button element.
Using animations on Fontawesome icons has no effect.

See "Animated Icons" and "Stacked Icons" section of http://fortawesome.github.io/Font-Awesome/examples/.

Please see: http://forum.primefaces.org/viewtopic.php?f=9&t=42067&sid=deec4c9854abbe62f27271ef47d9ede2

**Comment by cagataycivici** [comment]
``` xml
<p:commandButton value="Edit" icon="fa fa-edit fa-spin" />
```

does it for me.
