### ISSUE TITLE
DataTable: typed text is not shown inside CellEditor

### ISSUE THREAD

**Issue by vanuatoo** [primefaces/primefaces#3686]
## 1) Environment
- PrimeFaces version: 6.2.4 with Ultima theme 1.1.1

- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? Don't know
- Application server + version: Payara 5.181
- Affected browsers: Firefox

## 2) Expected behavior
When you go into edit mode and type text, it should be visible.

## 3) Actual behavior
During typing text is not shown, but when you press Enter (exit the edit mode), you can see what you typed.

**Comment by tandraschko** [comment]
does it work without ultima?

**Comment by vanuatoo** [comment]
It works without ultima

**Comment by tandraschko** [comment]
then use the ultima forum pls, this is just for primefaces core here.

**Comment by mertsincan** [comment]
I removed your sample project. Please see Layout License details; https://www.primefaces.org/layouts/licenses/

**Comment by vanuatoo** [comment]
Sorry for accidentally posting a project
