### ISSUE TITLE
Package org.primefaces.json declares two copyrights

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3688]
Some classes in the package `org.primefaces.json` declare more than one copyright holder, e.g. `Copyright 2009-2018 PrimeTek.` and `Copyright (c) 2002 JSON.org`. That can't be logical from a legal point of view.

This might indicate that a FLOSS library has been copied into the source tree and modified there rather than modifying it outside and declaring a dependency on the modified version.

**Comment by tandraschko** [comment]
maybe it was introduced by the maven plugin to check the license headers.

**Comment by melloware** [comment]
PR submitted and I added to the pom.xml to not overwrite this license in the future.
