### ISSUE TITLE
Make [AtmosphereRequest] object directly available inside a @PushEndpoint annotated Class

### ISSUE THREAD

**Issue by Maikel-Nait** [primefaces/primefaces#369]
When using a **@PushEndpoint** annotated class, there is no clean and direct way to get access to the **AtmosphereRequest** object, in either the **@OnOpen** or **@OnClose** methods.

The **RemoteEndpoint** parameter of these APIs do not provide access to **AtmosphereRequest**

Why is this needed ?  An example is when using **Apache Shiro**.
Atmosphere provides an Interceptor called **ShiroInterceptor**, that ensures the **AtmosphereRequest** always contains the right Subject in each HTTP Request.

However, it is impossible to access the Shiro Subject from a **@PushEndpoint** annotated class, as there is no way to get access to the **AtmosphereRequest** through the **RemoteEndpoint** interface.

You can check the answer from Jeanfrancois here:
https://groups.google.com/forum/#!topic/atmosphere-framework/AdDtsNY7wkg

Thanks.

**Comment by Maikel-Nait** [comment]
To make the requirement more clear.
What **we need** is this:

``` java
    @OnOpen
    public void onOpen(RemoteEndpoint r, EventBus eventBus) {
               AtmosphereRequest atmosphereRequest = r.getRequest();
               Subject currentShiroSubject = (Subject) atmosphereRequest.getAttribute(FrameworkConfig.SECURITY_SUBJECT);
               ...
   }
```

but currently we need to do this:

``` java
    @OnOpen
    public void onOpen(RemoteEndpoint r, EventBus eventBus) {

             Method remoteEndpointResourceMethod = RemoteEndpointImpl.class.getDeclaredMethod("resource", new Class<?>[0]);
             remoteEndpointResourceMethod.setAccessible(true);
             AtmosphereResource atmosphereResource = (AtmosphereResource) remoteEndpointResourceMethod.invoke(r, new Object[0]);
             AtmosphereRequest atmosphereRequest = atmosphereResource.getRequest();
             Subject currentShiroSubject = (Subject) atmosphereRequest.getAttribute(FrameworkConfig.SECURITY_SUBJECT);
             ...
}

```

because **RemoteEndpoint** do not have an API to access the **AtmosphereRequest** directly.

**Comment by cagataycivici** [comment]
@jfarcand What do you think?

**Comment by jfarcand** [comment]
@cagataycivici Yes we have had the discussion on the atmosphere [mailing list](https://groups.google.com/forum/#!topic/atmosphere-framework/AdDtsNY7wkg).  I will work on it as soon as I can.

**Comment by cagataycivici** [comment]
No worries, just wanted to hear your opinion.

**Comment by Maikel-Nait** [comment]
Amazing ... thanks a lot !  :)

**Comment by cagataycivici** [comment]
Thank you @jfarcand
