### ISSUE TITLE
Datatable: frozenColumns not working properly

### ISSUE THREAD

**Issue by madhu-singh** [primefaces/primefaces#3691]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:6.1.RC1
- It does not work on newest primefaces version.
- It does not work on newest source from git hub
- Application server + version: glassfish 3
- Affected browsers: firebox

## 2) Expected behavior
In datatable when we use frozenColumns then the datatable should not become distorted.

## 3) Actual behavior
In datatable when we use frozenColumns then the datatable becomes distorted. The height of frozen columns and other columns become different. It is something like after applying frozenColumns datatable is devided into 2 parts. and each part gets the height according to the height of data inside it. Which should not happen.

## 4) Steps to reproduce
add frozenColumns property in dataTable.

## 5) Sample XHTML
	<div class="container">
		<p:dataTable id="bulkGridTable1" var="gridDataVar"
			styleClass="bulkClass" value="#{cc.attrs.bulkGridBean.dataList}"
			widgetVar="dataTableWidget" rowIndexVar="rowIndexVar"
			style="width:100%" resizableColumns="true"
			rowStyleClass="#{(rowIndexVar mod 2) eq 0 ? 'first-row' : 'second-row'}"
			rowKey="#{gridDataVar.rowId}" scrollable="true"
			scrollHeight="#{basicSearchResultsBean.scrollHeight-190}" frozenColumns="4">

## 6) Sample bean
not required

**Comment by melloware** [comment]
PF 6.1RC1 is way old is that the correct version?  If so please upgrade to PF 6.2 and try again.

**Comment by melloware** [comment]
@tandraschko I think this is safe to mark invalid or closed since the user has not responded or provided a primefaces-test example showing the issue.
