### ISSUE TITLE
ui:debug: not working with primefaces.MOVE_SCRIPTS_TO_BOTTOM

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3692]
## 1) Environment
- PrimeFaces version: 6.2.4
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: any
- Affected browsers: any

## 2) Expected behavior
ui:debug is working as usual (in forked example use "ctrl+shift+x")

## 3) Actual behavior
When **primefaces.MOVE_SCRIPTS_TO_BOTTOM** set to true, ui:debug is not working and javascript is visible on web page:

```

Welcome to PrimeFaces!!!
//<![CDATA[ function faceletsDebug(URL) {day = new Date();id = day.getTime();eval("page" + id + " = window.open(URL, '" + id + "', 'toolbar=0,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=1,width=800,height=600,left = 240,top = 212');"); };(function() { if (typeof jsfFaceletsDebug === 'undefined') { var jsfFaceletsDebug = false; } if (!jsfFaceletsDebug) {var faceletsOrigKeyup = document.onkeyup;document.onkeyup = function(e) { if (window.event) e = window.event; if (String.fromCharCode(e.keyCode) == 'X' & e.shiftKey & e.ctrlKey) faceletsDebug('/primefaces-test/test.xhtml?facelets.ui.DebugOutput=1526888810850'); jsfFaceletsDebug = true; if (faceletsOrigKeyup) faceletsOrigKeyup(e); }; }})();//]]>
```

## 4) Steps to reproduce

Checkout https://github.com/martin654/primefaces-test/tree/replicate/uidebug and run with mvn jetty:run.

## 5) Sample XHTML
See https://github.com/martin654/primefaces-test/tree/replicate/uidebug

## 6) Sample bean
See https://github.com/martin654/primefaces-test/tree/replicate/uidebu

**Comment by tandraschko** [comment]
Try to debug that script. I dont think we cam fix it, we cant change the scripts of mojarra ;)

**Comment by tandraschko** [comment]
so the script is not rendered inside a script tag, hm?

**Comment by tandraschko** [comment]
@mertsincan feel free to port to elite

**Comment by martin654** [comment]
Thank you for the fix!
