### ISSUE TITLE
Change transmission of selected row to JSON array

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3694]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: ---
- Affected browsers: ---

## 2) Expected behavior

Row keys should be arbitrary objects.

## 3) Actual behavior

The list of selected row keys is a comma separated list which doesn't use any form of escaping which causes key which are strings and contain commas or have a `toString` representation which contains commas to behave unexpectedly.

The JSON format makes sense because it handles escaping well, has small overhead and implementations for serialization and deserialization are easily available on server and client side.

## 4) Steps to reproduce

I started an implementation attempt at https://github.com/krichter722/primefaces/tree/selection-json, but noticed that my JavaScript capabilities aren't sufficient to handle the change on the client side.

## 5) Sample XHTML

---

## 6) Sample bean

---

**Comment by melloware** [comment]
Closing this issue as no upvotes and no PR was provided.  Can always re-open if there are upvotes or PR in the future.
