### ISSUE TITLE
DataTable : Sticky Header Broken

### ISSUE THREAD

**Issue by tarpatel** [primefaces/primefaces#3699]
# IMPORTANT 

## 1) Environment
- PrimeFaces version: 6.2.4
- Affected browsers: yes affects all browsers

## 2) Expected behavior
according to the Primefaces showcase once you scroll on a database the header becomes sticky at top of browser page. Unfortunately this happens but the header is not aligned to the column data.

## 3) Actual behavior
along with the sticky header not being aligned with the column widths, but there are two column headers that show up initially.

## 4) Steps to reproduce
see below:
.. 

## 5) Sample XHTML

I am not doing anything special in the XHTML...

                                <p:dataTable id="searchresultstable" var="em" value="#{emailManagementBean.emailManagementList}" sortMode="multiple"  stickyHeader="true">
                                    <p:column headerText="Session" sortBy="#{em.sessionName}">
                                        <h:outputText value="#{em.sessionName}"/>
                                    </p:column>
                                    <p:column headerText="Faculty" sortBy="#{em.faculty.fullName}">
                                        <h:outputText value="#{em.faculty.fullName}"/>
                                    </p:column>
                                    <p:column headerText="Email Sent Date Time" sortBy="#{em.emailSent}">
                                        <h:outputText value="#{em.emailSent}">
                                            <f:convertDateTime pattern="E MM/dd/yyyy 'at' hh:mm a"/>
                                        </h:outputText>
                                    </p:column>                             
                                </p:dataTable>

## 6) Sample bean
the list is populated by a simple database call to create a list of object that contains session name, full name and when email was sent. Nothing fancy.

## 7) screen shots

![sticky1](https://user-images.githubusercontent.com/4670516/40365888-4f596aa0-5d9b-11e8-97cf-42c648df6524.PNG)

See how the columns of the sticky header are not in any way aligned with data in the columns?

![sticky2](https://user-images.githubusercontent.com/4670516/40365893-5349c1d2-5d9b-11e8-851f-c4eae53e216a.PNG)

**Comment by tandraschko** [comment]
Did it work fine in 6.2.3?

**Comment by tarpatel** [comment]
Hello, I just tried 

6.2.3
6.2
6.1
6.0

and in all cases the exact same broken behavior is being displayed.

**Comment by tandraschko** [comment]
then please fork primefaces-test and provide a example. It works fine for me in the showcase (https://www.primefaces.org/showcase/ui/data/datatable/sticky.xhtml).

**Comment by tandraschko** [comment]
No example but it could be fixed after fixing #834 - you can try a build from source.
If still broken, you can create a new valid issue with a example.
