### ISSUE TITLE
Add support for firstDay from FullCalendar for p:schedule

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#370]
( Original issue: https://code.google.com/p/primefaces/issues/detail?id=6349 )

My PrimeFaces.locales is 'en_US' which has firstDay: 1

I am trying to write a Payroll application - a payroll week starts on Monday so I would like to display a Calendar of "Payroll weeks" not locale weeks.

**Comment by sudheerj** [comment]
As you mentioned in the old issue post you have to change the first day on a calendar base instead of locale base.(for example 2 calendars on the same page with sunday and monday as first day).This is a   bit rare scenario and Cagatay may decide whether to provide this feature or not

**Comment by cagataycivici** [comment]
Doesn't is already available via PrimeFaces.locales? Locale spefic configuration are done with PrimeFaces.locales. Please check.

**Comment by mores** [comment]
Thanks to http://stackoverflow.com/questions/20842196/primefaces-locale-not-working 
I was able to get the following to work:

`<script type="text/javascript">  
            PrimeFaces.locales['tr'] = {
            closeText: 'Close',
            prevText: 'Previous',
            nextText: 'Next',
            currentText: 'Current Date',
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December' ],
            monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
            dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
            dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Tue', 'Fri', 'Sat'],
            dayNamesMin: ['S', 'M', 'T', 'W ', 'T', 'F ', 'S'],
            weekHeader: 'Week',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: '',
            timeOnlyTitle: 'Only Time',
            timeText: 'Time',
            hourText: 'Time',
            minuteText: 'Minute',
            secondText: 'Second',
            ampm: false,
            month: 'Month',
            week: 'Week',
            day: 'Day',
            allDayText : 'All Day'
        };
        </script>`

`<p:schedule id="schedule" value="#{MyWeek.eventModel}" widgetVar="myschedule"
                                locale="tr"
                                allDaySlot="false"
                                aspectRatio="2.1"
                                initialDate="#{MyWeek.initialDate}"
                                leftHeaderTemplate=""
                                rightHeaderTemplate=""
                                view="agendaWeek"
                                firstDay="3"
                                showWeekends="true"
                                timeZone="America/New_York"
                        >  
                                <p:ajax event="dateSelect" listener="#{MyWeek.onDateSelect}" update=":create" oncomplete="PF('eventDialog').show()" />
                                <p:ajax event="eventSelect" listener="#{MyWeek.onEventSelect}" update=":edit" oncomplete="PF('editDialog').show()" />
                                <p:ajax event="eventMove" listener="#{MyWeek.onEventMove}" oncomplete="PF('myschedule').update();" />
                                <p:ajax event="eventResize" listener="#{MyWeek.onEventResize}" oncomplete="PF('myschedule').update();" update=":week_form" />
                        </p:schedule>`

What seemed strange is that I could not call this locale "customLocale" nothing would render. I tried to call this locale "en_US" but again nothing changed. I could only get the output I desired by calling this locale "tr".

**Comment by sudheerj** [comment]
Ok.You posted the thread related to PrimeFaces locales.But my comments are related to other OP in the original post.

"Via PrimeFaces.locales, it is done on a per-locale basis. There are some cases when this is not satisfactory, and you could want it on a per-calendar basis."

**Comment by cagataycivici** [comment]
Also make sure your locale js is loaded before Schedule gets initialized.
