### ISSUE TITLE
p:dock with scrollbar dont work

### ISSUE THREAD

**Issue by TrapoSAMA** [primefaces/primefaces#3702]
Hi!

somebody can tell me if this are fixed in latest version?

 <ui:insert name="bottom">
                <div class="visible-lg visible-md visible-sm" style="height: 50px;">
                    <p:dock halign="center" itemWidth="50" maxWidth="40" 
                            model="#{sessionScope['usuario'].menuAplicaciones}" >
                    </p:dock>
                </div>
 </ui:insert>

**Comment by melloware** [comment]
Yep fixed in PF 6.2.  See the ticket below...

https://github.com/primefaces/primefaces/issues/1728

Please close the issue.

**Comment by tandraschko** [comment]
the issue tracker is no forum!
