### ISSUE TITLE
Layout: resize ajax event not working

### ISSUE THREAD

**Issue by herbu123** [primefaces/primefaces#3705]
Hi,

 just moved from 6.0 to 6.2 and it looks like the "resize" event stopped working on layout.
(tested on chrome and firefox - no error on client/server side - works perfectly fine on 6.0)

 Regards,
 herbu

 PS
1) in showcase there is no example for resize currently - but it think it used to be there before .... 
2) forum discussin link: [https://forum.primefaces.org/viewtopic.php?f=3&t=55727](url)

`
	<p:layout id="layout_main_id" fullPage="true" dynamic="true" 
		<p:ajax event="resize" listener="#{treeBean.CL.onLayoutResize}"
			update="layout_main_id" />

		<p:layoutUnit id="layoutu_n" position="north" styleClass="layoutNorth layoutNorthContent" >
			<h:form id="formNorthLayout">
			
		(...)
		
`

The bean code:
`
    public void onLayoutResize(org.primefaces.event.ResizeEvent event)
    {
    	org.primefaces.component.layout.LayoutUnit lu = 
    			(org.primefaces.component.layout.LayoutUnit) event.getComponent();
    			
	}   
`

**Comment by tandraschko** [comment]
As the issue template states, we need a full runnable xhtml + bean. Otherwise i will close it as invalid.

**Comment by melloware** [comment]
I have confirmed the Layout Resize event is not working.

**Comment by tandraschko** [comment]
@melloware If you will fix it, it's ok for me without example, Otherwise a example would be great.

**Comment by melloware** [comment]
Fixing it now.

**Comment by tandraschko** [comment]
Thanks!
