### ISSUE TITLE
p:datatable - column filtering issue.

### ISSUE THREAD

**Issue by denizque** [primefaces/primefaces#3707]
DataTable: filterBy column not working properly.
PrimeFaces Version: 6.2.1
Application Server: Jetty
Browsers: Any

parameters used in p:column:
```
filterMatchMode="contains"
filterBy="#{item.product.productCodeAndName}" 
sortBy="#{item.product.productCodeAndName}"
```
I am attaching a recorded gif file when you can visually see the problem.

I have a datatable with multiple columns: Product, Product description, vendor part no, supplier, currency, quantity, list price and some more.

Product column contains p:autoComplete component, currency column contain p:selectOneMenu component, where quantity and list price columns contain p:inputNumber component.

When I try to filter in product column it works properly but when I erase the input and return it to original, currency, quantity and list price lose their values. If I click to sort the original values show up.
The issue is why when returning to non filtered data these columns lose their values?

The recorded gif will clarify what actually the problem is.

[See the gif here](https://ibb.co/nyd9t8)

**Comment by tandraschko** [comment]
Please follow our issue template or the issue will be closed.
This is not a forum here and to replicate  a issue, we need a runnable example.
