### ISSUE TITLE
OutputLabel: Not show required marker for composite constraints

### ISSUE THREAD

**Issue by msgeissler** [primefaces/primefaces#3709]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: not relevant
- Affected browsers: not relevant

## 2) Expected behavior
Using `@NotNull`, `@NotEmpty` and `@NotBlank` on a property that is being referenced by a label shows a required marker. The same should happen in a composite constraint.

## 3) Actual behavior
`@NotNull`, `@NotEmpty` and `@NotBlank` in a composite constraint is not being evaluated, as the `#isBeanValidationDefined` in OutputLabelRenderer only checks the top level constraints.

See #3708 for a PR.

**Comment by tandraschko** [comment]
basically +1 but i would like to see units tests here - maybe you can also outsource the logic to BeanValidationMetadataExtractor

**Comment by msgeissler** [comment]
Might take some time before I can implement the necessary changes, but I will keep this on my radar.

If anyone else is interested in the change in the meantime, the OutputLabelRenderer can be overriden using JSF renderer-config in a relatively easy manner.

**Comment by melloware** [comment]
Integration Tests proving that `@NotNull @NotEmpty and @NotBlank` are working with and without composite.

https://github.com/primefaces-extensions/primefaces-integration-tests/commit/b967b0b9d07ae4874fa6ca56edb09677c9bc3e83
