### ISSUE TITLE
java.lang.StackOverflowError on DataTable row expansion

### ISSUE THREAD

**Issue by ReshmaMuslim** [primefaces/primefaces#371]
Works fine with PrimeFaces 5.0 but not with 5.2.0.
Googled lot and tried many ways of solving but couldn't resolve.

Any Idea or suggestion?

Thanks in advance!

**Comment by sudheerj** [comment]
Not able to replicate the issue on showcase example.Use forum first for the questions.

**Comment by cagataycivici** [comment]
Please use forum for cases like these and follow issue posting guidelines in future.
