### ISSUE TITLE
OutputLabel: inconsistent bean validation check

### ISSUE THREAD

**Issue by msgeissler** [primefaces/primefaces#3710]
This is more of a discussion item than a direct issue / bug report, as such I took the liberty of removing most of the issue template.

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no

## 2) Expected behavior
Using custom `@NotNull`, `@NotEmpty` and `@NotBlank` constraints results in the same behaviour of the OutputLabelRenderer (with regards to the required-marker).

## 3) Actual behavior
Using a custom `@NotNull` constraint does not show a required marker, but using custom `@NotEmpty` and `@NotBlank` do (disregarding any composite constraints, #3708 aims at fixing that use case). The reason for this is the check in the `OutputLabelRenderer#isBeanValidationDefined`. For `@NotNull` the check happens on a class level (`annotationType.equals(NotNull.class)`), that means that the class must be exactly the same (package etc.). For `@NotEmpty` and `@NotBlank` only the simple name is used `(annotationType.getSimpleName()`), that means the constraint can come from any package and just needs the name `@NotEmpty` or `@NotBlank`.
This creates an inconsistency in the way the constraints are handled. It should be one or the other, so the behaviour becomes more predictable.

If someone from the PR team agrees with this, I could easily create a PR to change the behaviour, but I am not sure which version is better: checking the exact class or just the simple name.
Personally I prefer using the class, as it makes it more predictable and works only with the originally intended constraints (for custom use cases they could be wrapped by composite constraints #3708).

This could potentially be a "breaking" change for a few people (the required marker would be missing for people who named their custom constraints `@NotEmpty` or `@NotBlank`).

**Comment by tandraschko** [comment]
We can't use the class here as we don't have access to hibernate or bean-val 2.0 API.

**Comment by msgeissler** [comment]
Ah gotcha, this is still using validation api 1. Didn't think about checking that (now the comment in the code makes sense too).
Do you have any intention of updating to v2+ anytime soon? Maybe this issue can be marked for whatever later release this might be, so the (necessary) changes can be tracked.

How do you feel about checking the package of these classes against string constants as well as a workaround for now? Is it worth it? This might also depend on your plans for updating the validation-api (e.g. if you have plans to update for PF 7, this might not be worth the change).

**Comment by tandraschko** [comment]
the problem is that even hibernate had a NoeEmpty/Blank in V1 and we can never import those classes.

**Comment by tandraschko** [comment]
If those constraints wouldn't exist in Hibernate1.x, we could simply upgrade to validation api 2.x and do a if around (if (validation api 2.x) { ... check for those 2.x constraints })

**Comment by tandraschko** [comment]
Thats one of the keypoints for such a library as PF - we are still fully compatible to JavaEE5! And also Spring e.g... So we can't use CDI e.g. for our internall stuff.

**Comment by msgeissler** [comment]
I just quickly checked back up to Hibernate Validator 4.1 (the oldest tag in their GitHub repo). The hibernate validator annotations of [NotEmpty](https://github.com/hibernate/hibernate-validator/blob/4.1/hibernate-validator/src/main/java/org/hibernate/validator/constraints/NotEmpty.java) and [NotBlank](https://github.com/hibernate/hibernate-validator/blob/4.1/hibernate-validator/src/main/java/org/hibernate/validator/constraints/NotBlank.java) have been using a composite constraint and NotNull under the hood ever since. With #3708 they should be caught by the validation-api NotNull check as well.

So we would only have to check the validation-api 2.x NotEmpty and NotBlank, as they are their own constraints (no composites).

Would this actually be helpful with the migration / change here?

**Comment by tandraschko** [comment]
Please note that NotNull works only in combination with InterpretEmptyStringAsNull - so checking @NotNull only doesn't work for all cases.

**Comment by msgeissler** [comment]
Hm, so if InterpretEmptyStringAsNull is set to false it would not show a required marker for the hibernate NotEmpty and NotBlank then.

And ignoring that option would show the required marker for NotNull even though that validation is basically useless with InterpretEmptyStringAsNull turned off. Dang.
Maybe InterpretEmptyStringAsNull == true should be added to the documentation in the context of bean validation and metadata extraction and either be assumed to be true or strongly recommended to be set to true by the developer for everything to work properly. But that is also no ideal. :/

But I can see that this is even trickier than I initially thought. :(


Btw the information on InterpretEmptyStringAsNull and NotNull seems to be missing from the 6.2 documentation. I couldn't find it on GitHub for a potential PR.

**Comment by tandraschko** [comment]
Yep :) Therefore i asked for unit-tests.

It would be great if you can create a issue for the missing documetation with text + where we should add it

**Comment by tandraschko** [comment]
We will leave it for now, there is no reason to change and hibernate + validation spec is 1 still used.
Maybe we can think about it ~2 years.
