### ISSUE TITLE
schedule: wrong date/time/dayDelta on eventMove

### ISSUE THREAD

**Issue by herbu123** [primefaces/primefaces#3713]
Hi,

just move from 6.0 to 6.2. and fund the following bug (on 6.0 everything work fine).

When on the week view one move event exactly horizontally between days (same time) everything works fine. BUT when one change not only a day but also a time (to some later hour) the event date is calculated wrong (and delta day is wrong) - see picture and use the example below 

![calendarbug62](https://user-images.githubusercontent.com/34067588/40429084-15fb0ebe-5ea2-11e8-9ce7-df6a92ebec62.jpg)

(I don't know why the image is not coming - it is uploaded here: https://ibb.co/cKgFrT )

xhtml:

`

	<h:form id="test">
		<p:panel id="testPanel">
	
		    <p:schedule id="schedule" value="#{testBean.eventModel}" widgetVar="w_schedule"
			    	view="agendaWeek" >
			
		        <p:ajax event="eventMove" listener="#{testBean.onEventMove}" oncomplete="PF('w_schedule').update();" />
			</p:schedule>	
		</p:panel>
	</h:form>	
`

bean:

`@ManagedBean(name = "testBean")
@Named
@Scope("session")
public class TestBean implements Serializable {
	private static final long serialVersionUID = -1178789140271997877L;

	ScheduleModel eventModel = new DefaultScheduleModel();  
	public void setServicesDAO(ServicesDAO servicesDAO) {
		this.servicesDAO = servicesDAO;
		

		DateTime dt = new DateTime();
		
		DefaultScheduleEvent event = new DefaultScheduleEvent ("desc", dt.toDate(), dt.plusHours(2).toDate());
		event.setTitle("title");

		eventModel.addEvent(event);
	}

	public ScheduleModel getEventModel() {
		return eventModel; 
	}

	public void onEventMove(ScheduleEntryMoveEvent event) {  
		SimpleDateFormat full_sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss SSS");

		System.out.println( "StartDate: " + full_sdf.format(event.getScheduleEvent().getStartDate()) );
		System.out.println( "DayDelta: " + event.getDayDelta() );
	}
}
`

Regards,
herbu

primefaces 6.2

**Comment by tandraschko** [comment]
Again, please reuse our issue template. Also adding the whole bean, with annotations and correctly format your code.

**Comment by herbu123** [comment]
Hello Thomas,

I have update the issue / added the missing code- still - I am pasting the formatted code but on preview it is not coming correctly - hope you can handle

/herbu

**Comment by herbu123** [comment]
Hi Thomas,

I have updated the issue - there is still some formatting wrong but I am
not able to fix it - hope you can manage.
Please recheck and provide feedback as this (in 6.2 corrupted)
functionality is crucial for me (and actually make the whole schedule
component useless)

Best Regards,
herbu


On Wed, May 23, 2018 at 4:02 PM, Thomas Andraschko <notifications@github.com

**Comment by tandraschko** [comment]
JFYI: i won't check it. I just validate the issues here, to be in correct format. I'm doing this in my freetime and only check issues to "my related components/parts".
If you need help, i suggest PrimeFaces PRO, fix it by yourself and provide a PR, or wait until someone fixes it for you.

**Comment by melloware** [comment]
Is this similar or duplicate of this issue?  https://github.com/primefaces/primefaces/issues/2296

**Comment by mbeedub** [comment]
+1 for this.

It is still an issue.

**Comment by tandraschko** [comment]
Feel free to fix it an provide a PR ;)

**Comment by melloware** [comment]
Adding @OBreidenbach since he is the schedule expert. :)  There are two open tickets around this issue that have been open for a while.

**Comment by OBreidenbach** [comment]
Provide PR #3991, should also fix #2296.
The bug is visible in the showcase, if you moving events around the message growl shows the wrong values. So you can use the showcase to check if my fix is valid.
