### ISSUE TITLE
InputMask: incorrect handling of optional characters

### ISSUE THREAD

**Issue by tiagojn** [primefaces/primefaces#3715]
## 1) Environment
- PrimeFaces version: **6.3-SNAPSHOT**
- Does it work on the newest released PrimeFaces version? Version? **No, 6.3-SNAPSHOT**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**
- Application server + version: **Wildfly Full 12.0.0.Final**
- Affected browsers: **Chromium 66**

## 2) Expected behavior
An InputMask whose mask has X optional characters should accept any number of optional characters lower than X. Example: "9?9999" should consider the following valid: "9", "99", "999", "9999", etc

## 3) Actual behavior
An InputMask whose mask has X optional characters accepts: 0 optional characters or X optional characters. Example:  "9?9999" considers valid "9" and "99999".

The input value can be valid to the Javascript part of the component, and not to the Java implementation, in which case the value is set to null.

## 4) Steps to reproduce
1. Use an InputMask with the mask: "9?999"
2. Type "99" and submit the form
3. The front end will accept the value (it will not be cleared)
4. The value will be null to the backing bean

## 5) Sample XHTML
```
...
<h:form>
<p:inputMask value="#{bean.value}" mask="9?999" />
<p:commandLink actionListener="#{bean.submit()}"/>
</h:form>								
...
```

## 6) Sample bean
```
@ManagedBean
@ViewScoped
public class Bean {
   private String value;

   public void submit() {
         assert this.value != null;  //fails
   }
...
}

```

**Comment by tiagojn** [comment]
The PR #3716 fails a test because of the regex generation.
The mask "9?99" should generate the regex: `[0-9][0-9]?[0-9]?` and not `[0-9]([0-9][0-9])?`
Let me know if I should modify the test

**Comment by tandraschko** [comment]
@cnsgithub can you check this?

**Comment by cnsgithub** [comment]
@tiagojn Your PR looks good. From reading the documentation of [jquery.maskedinput](https://github.com/digitalBush/jquery.maskedinput) it was unclear if the number of optional characters is fixed or variable. But you're right, the number of optional characters has to be variable, as you can verify here: https://jsfiddle.net/ojbj1grf/. Thanks for the PR.

**Comment by erickdeoliveiraleal** [comment]
maybe the same bug as #3644

**Comment by tiagojn** [comment]
The PR was updated

**Comment by tandraschko** [comment]
Thanks
