### ISSUE TITLE
Problem with selected nodes on tree

### ISSUE THREAD

**Issue by wagnerFaria** [primefaces/primefaces#372]
When you bring the tree with fields already selected the atribute selection=""(witch is a vector) from xml tag p:tree does not get those selected nodes. 
and more ... when you selec nodes on tree and you try to get those selected nodes on java by using node.isSelected() it doesnt work too.

**Comment by cagataycivici** [comment]
Please use forum first and in future provide more information with a more clear description. In my local test with 5.3, preselection works.
