### ISSUE TITLE
Messages: duplicate value on summary and detail if using requiredMesssage attribute

### ISSUE THREAD

**Issue by mafaul** [primefaces/primefaces#3720]
I like to display details using the p:messages component to give users additional info when issuing faces messages programmatically. But with the showDetail set to true, the detail gets duplicated from the suummary when using the requiredMessage attribute.

When using <p:inputText required="true" requiredMessage="Value Required" ... /> the detail is the same as the summary.

This is also the case if the value of the inputfield value is binded to a JPA entity field annotated with @NotNull.

Primefaces Version: 6.2
Affects: Messages, Message, Growl

https://stackoverflow.com/questions/13467881/duplicate-text-in-pmessages-summary-and-detail

![image](https://user-images.githubusercontent.com/12007706/40451766-fe79c8e6-5edf-11e8-9a0e-0fe2306aac5f.png)

**Comment by mafaul** [comment]
https://github.com/primefaces/primefaces/pull/3719
https://github.com/primefaces/primefaces/pull/3718
https://github.com/primefaces/primefaces/pull/3717

**Comment by tandraschko** [comment]
I understand your case but thats not the root problem. You coudl still overwrite the detail message.

But we can introduce this behavior with a attribute on all message components (message, messages, growl), which says something like "don't display detail if detail equals title". Just need a good name and a new PR ;)

**Comment by tandraschko** [comment]
Also one PR for all components in enough next time.

**Comment by mafaul** [comment]
https://github.com/primefaces/primefaces/pull/3722

**Comment by tandraschko** [comment]
We need a attribute on the component itself (p:message doThisNewLogic=true) ;) But we also need good ideas for the attribute first. @melloware @cnsgithub @Rapster ideas? :D

**Comment by melloware** [comment]
My thoughts are:

1. hideSummaryMatchingTitle=true
2. excludeSummaryMatchingTitle=true

**Comment by tandraschko** [comment]
called it "skipDetailIfEqualsSummary" for now

**Comment by tandraschko** [comment]
See: https://github.com/primefaces/primefaces/commit/1178ed49c94a85c2f74a02512df0a4c933227ee4
