### ISSUE TITLE
[Documentation] Fix BeanValidation Transformation and OutputLabel docu

### ISSUE THREAD

**Issue by msgeissler** [primefaces/primefaces#3723]
The behavior has changed a bit over the last years:

**OutputLabel:**
The OutputLabelRenderer indicateRequired attributes has 3 modes:
false = * will NEVER be shown
true = * will always be shown
auto = the renderer will automactically check if the connected inputfield is >actually< required and render the * if true.
Ifs true when:
- beanValidationAvailableAndEnabled && input.getValueExpression("value").hasAnnotation(@NotEmpty || NotBlank)

OR 

- beanValidationAvailableAndEnabled && InterpretEmptyStringAsNull && input.getValueExpression("value").hasAnnotation(@NotNull)
 

**BeanValidation Transformation:**

The BeanValidation Transformer currently only transforms:

@Size to maxlength on HtmlInputText, HtmlInputSecret and InputTextarea
@Max to Spinner max
@Min to Spinner min
@Past to Calendar
@Future to Calendar

**Original issue text:**
-------------------------------------------------------------------------------------------

This is a request to add additional information to the documentation / user guide (follow up on #3710).

User Guide version: 6.2

Proposed change:
Page: 652
Extend the section **11.4 BeanValidation Transformation** -> **Configuration** with the following / similar text:

---

To enable full support for `@NotNull`, `InterpretEmptyStringAsNull` has to be set to `true`. Otherwise no required indicator will be shown for that constraint.
```xml
<context-param>
    <param-name>javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
    <param-value>true</param-value>
</context-param>
```

---

Btw I am hijacking this issue for a small typo: In the very same section an additional semicolon made its way into the primefaces.TRANSFORM_METADATA code `<context-param>;`

**Comment by tandraschko** [comment]
I'm not sure, maybe it's  problem of your understanding, also regarding #3724.

Bean Validation Transformation is something, that transforms annotations of the value binding, before redering the component, into component attributes.
e.g. @Min and @Max is automatically set as a Spinner attribute.

**Comment by tandraschko** [comment]
Now lets talk about the logic in the OutputLabelRenderer:

If you add a NotNull/Empty/Blank and BV is enabled, the component will be validated by the bean-validation-api and is therefore >actually< required (without the input-component is set to required=true).
That is was happens when you set indicateRequired=auto, which is the default mode in trunk.

**Comment by msgeissler** [comment]
> I'm not sure, maybe it's problem of your understanding, also regarding #3724.

I am starting to get that feeling as well. I updated #3724 with another comment as to why I think / thought they are related. The required marker for the outputLabel and NotNull requires InterpretEmptyStringAsNull to be turned on. As the required marker behaviour is explicitly mentioned in the transformation settings I assumed they are / should be connected.

With InterpretEmptyStringAsNull turned off you will never get the behaviour as described in the user guide in the transformation section.

**Comment by tandraschko** [comment]
updated the description and current, correct, behavior

**Comment by tandraschko** [comment]
@msgeissler Would you like to contribute the docu changes via PR? they are in github now as .md file :)

**Comment by tandraschko** [comment]
Or anyone else?

**Comment by msgeissler** [comment]
@tandraschko sorry as I am not working with PrimeFaces or JSF anymore at the moment, I forgot about this issue. I will try to give it a ago, but I might not have the time for a fully fledged out final version.

**Comment by msgeissler** [comment]
@tandraschko I created a PR #4679 with some updates to the documentation.

**Comment by tandraschko** [comment]
@msgeissler Thanks, i really appreciate your help even you don't use PF currently! :)
