### ISSUE TITLE
OutputLabel: TRANSFORM_METADATA is ignored

### ISSUE THREAD

**Issue by msgeissler** [primefaces/primefaces#3724]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: not relevant
- Affected browsers: not relevant

## 2) Expected behavior
If I use Bean Validation without setting primefaces.TRANSFORM_METADATA to true and add `@NotEmpty` or any other constraint to a property that turns it into a required property, I do not see any required marker, as metadata transformation is turned off by default.

## 3) Actual behavior
A required marker is shown if Bean Validation is used and primefaces.TRANSFORM_METADATA is false (default).

The required state is set based on bean validation being active, ignoring metadata transformation settings: https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java#L115

The required indicator is rendered based on the required state and indicate required setting of the label, ignoring metadata transformation settings: https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java#L154

**Comment by tandraschko** [comment]
Sorry, i don't understand your problem. Please try a trunk build.


TRANSFORM_METADATA is completely indepdent from OutputLabelRenderer and will be.

**Comment by msgeissler** [comment]
Hm, maybe it is a misunderstanding with the user guide then.

In the user guide in section 11.4 BeanValidation Transformation it is stated that 

> The required attribute also controls the behavior of p:outputLabel to show or
hide the required indicator (*)

which makes it look like that this behaviour is also controlled by the bean validation transformation setting. Maybe it should be removed from there if it is not being controlled by it on purpose?

**Comment by tandraschko** [comment]
will fix the description in #3723
