### ISSUE TITLE
Calendar (inline): Time values are incorrectly reset on validation error

### ISSUE THREAD

**Issue by matsandreassen** [primefaces/primefaces#3729]
When submitting a form with _inline_ calendar, and a validation error occurs, the _visible_ time values are set to 00:00:00.

The curious thing is that the backend value is set _correctly_.

## 1) Environment
- PrimeFaces version: 6.2.4
- Application server + version: Tested with Tomcat 8.5.27
- Affected browsers: Chrome + Edge, at least

## 2) Expected behavior
The time values are left unaffected.
...

## 3) Actual behavior
Time values are reset.
..

## 4) Steps to reproduce
I've attached a project based on the primefaces-test repo. There's a required input field which should be left blank to provoke the validation error. Change time values to e.g. 09:32 and press the "Save" button.

## 5) Sample 

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/2044318/primefaces-test.zip)

**Comment by melloware** [comment]
@Rapster @tandraschko safe to close this issue as it was fixed in: https://github.com/primefaces/primefaces/issues/3765

**Comment by Rapster** [comment]
@matsandreassen could you have a try please? I didn't follow both tickets and descriptions sound different so... I'd prefer someone to test it and then we'll close it (if fixed)

**Comment by matsandreassen** [comment]
I'd love to, but I can't seem to find out which release contains this fix.

**Comment by Rapster** [comment]
You'll have to compile the sources

**Comment by melloware** [comment]
simply do this to have PF 6.3-SNAPSHOT available for the test project.

```
git clone https://github.com/primefaces/primefaces.git
cd primefaces
mvn clean install
```

**Comment by matsandreassen** [comment]
I'm on it. 👍

**Comment by matsandreassen** [comment]
Confirmed. 6.3-SNAPSHOT fixes our usecase.
