### ISSUE TITLE
Item selection doesn't work in autocomplete with forceSelection="true" and watermark on IE8 

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#373]
```
<h:form>
    <p:autoComplete id="ac" completeMethod="#{bean.complete}" forceSelection="true" />
    <p:watermark for="ac" value="accc" />
</h:form>
```

Input search query, try to select something - the suggestion list disappears, but the autocomplete field contains only the watermarked placeholder.
With `p:ajax event="itemSelect"` the event doesn't fire (no AJAX request happens).
Reproducible in IE8, Browser Mode: IE8, Document Mode: IE8 Standards.
PF version built from git sources on 22.05.15.

**Comment by cagataycivici** [comment]
Watermark does not support this case as it is a javascript solution that conflicts with events of autocomplete, prefer a modern browser that supports placeholder attribute.
