### ISSUE TITLE
Calendar: Today-button not working if mask="true"

### ISSUE THREAD

**Issue by KarlKnapp** [primefaces/primefaces#3732]
## 1) Environment
- PrimeFaces version: 6.2

- Affected browsers: Firefox, Chromium

## 2) Expected behavior
Current date should be set.

## 3) Actual behavior
Date is showing in the component but is overwritten with the previous value instantly.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

<p:calendar mask="true" showButtonPanel="true" />

## 6) Sample bean

..

**Comment by mauritz-lovgren** [comment]
One possible workaround found until fixed:

```
<p:calendar mask="true" showButtonPanel="true">
    <p:ajax event="dateSelect" process="@this" update="@this"/>
</p:calendar>
```

Alternatively, surround with p:fragment (when using complex variant with validators etc...:

```
<p:fragment>
    <p:autoUpdate/>
    <p:outputLabel for="birthdate" value="#{msg['employee.birthdate']}" style="display: block;"/>
    <p:calendar id="birthdate" value="#{employee.birthdate}" mask="true" showButtonPanel="true">
        <p:ajax event="dateSelect"/>
        <p:clientValidator/>
    </p:calendar>
    <p:message for="birthdate"/>
</p:fragment>
```

**Comment by melloware** [comment]
Reproducer: 
[pf-3732.zip](https://github.com/primefaces/primefaces/files/4371622/pf-3732.zip)
