### ISSUE TITLE
DeltaSike ViewAccessScoped support for StreamedConent

### ISSUE THREAD

**Issue by 99sono** [primefaces/primefaces#374]
This issue was original posted and described under:
https://issues.apache.org/jira/browse/DELTASPIKE-914

It essentially has to do with the fact that it appears that p:graphicImage will not work properly if the dynamic content is coming out of a view access scoped bean.

A sample application that can reproduce the issue is available under:
https://github.com/99sono/delta-spike-dynamic-content_issue/

After an initial analysis of the code involved in rendering the p:graphicImage and the PrimeResourceHandler , I am under the impression that this issue might need the coordination of both teams (primefaces and deltaspike) to be fixed.

Kindest regards.

**Comment by tandraschko** [comment]
ViewScoped or ViewAccessScoped? Its a big difference ;)

**Comment by 99sono** [comment]
True,

But just to clarify:  
org.apache.deltaspike.core.api.scope.ViewAccessScoped
:)

Thanks.

**Comment by tandraschko** [comment]
ViewScoped isn't supported by design and ViewAccessScoped integration in ResourceHandler requests is actually a DeltaSpike problem.

**Comment by 99sono** [comment]
Hi there,
And many thanks for your feedback.

If you say that it is a DeltaSpike issue, I believe that you may very well be right.
However, looking at the PrimeFaces ResourceHandler, namely at the code where it sports that the request is targeting a Dnynamic resource, the primefaces code takes over and resolves the ValueExpression that was on the index.xhtml page.

I did not see that DeltaSpike would have many opportunites to somehow spot that it should already have activated the view scoped context. The resource handler is not following a normal JSF life cycle, so is there really a spot where DeltaSpike could somehow have taken over and activate its managed contexts?

Another question.

Since Primefaces seems to be using the external context session properties to store in the value expression and such metada for when the browser comes asking for the image resource.
I would expect that theoretically, since SessionScoped features are alaredy being used, primefaces could probably have its own session/application scoped bean to store a reference to the page bean StreamContent. If such a reference were stored in during the render response phase of the img in an application/session scoped bean it would for sure be able to always find the resource on the second step where the browser comes in asking for that image.

You would simply have to be very careful to avoid memory leaks of too many streamcontent references in the managed session/application scoped bean.
But that does not look like it would be such a big thing, given that the ResourceHandler is already cleaning after itself when it deletes from the external context session properties the metatadata it wrote in there during the render response phase.

Moreover, if you use circular buffer to store in the refences to these StreamResource you can limit the damage of theoretical leak to the number of slots in your circular buffer.

From what I've seen, I would say it would be possible for primefaces p:graphicImage to support any contexted bean - even ViewScoped bean which you say is not supported by design.
It is just a matter of have the Renderer and the Handler have some backing BUS between them that is Session/ApplicationScoped....

Or am I missing something in this picture?

Many thanks for looking at this,
Kindest regards,
Nuno.

**Comment by tandraschko** [comment]
We stored the resource in the session before PF 3.0. Cagatay changed it by design -> https://code.google.com/p/primefaces/issues/detail?id=2073

**Comment by rdebusscher** [comment]
See also as https://github.com/rdebusscher/AdvancedGraphicImageRenderer as another workaround to have the dynamic image when there is a scope image (like within a table, custom component, ...)

**Comment by 99sono** [comment]
Hi there,
And thank you for the feedback.

Rdebusscher, I have taken a look at the blogpost associated to teh AvancedGraphicImageRenderer, it sounds to me like the functionality you've implemented should actually be added to the standard primefaces. Namely, as an optional attribute to the standard renderer such as resolutionStrategy="default/tmpFolder/etc..."

Another thing, the readme file of the project is missing some information on the usage of the library.
It essentially it just states that you have to add the maven dependency.

It would be important for the readMe to explain the main ideas of the blog-post:
(1) That it works around the fact that in some cases value expressions will fail to be resolved by the resource handler and that the new enhanced graphic image will work around it by physically strogin the imageto a temp folder

(2) That it activates automatically on scenarios where a smart alrogithm fifugres out that the EL expression would break

(3) For scenarios where the algorithm fails to figure out that the code would braek that there is an attribute that you can tune in the compnent to force the tmp strategy to activate forcefully -  which I suppose is the scenario I would need to use as a work around for the ViewAccessScoped bean not being active.
I will try to give it a try on monday.

"  By specifying a boolean value for the value attribute, you can control the usage of the advanced rendering functionality."

This is a bit abstract. The good thing is that a boolean value is a binary thing is either true or false.
I suppose this means that if in the graphic image you set value="true" you will activate the feature... but this is left for interpretation. Could you perhaps put a concrete example on how to froce the advanced feature to activate on the p:graphicImage?

Many thanks.
