### ISSUE TITLE
[Documentation] Schedule: explain the usage of the extender method

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#3740]
## 1) Environment
- PrimeFaces version: 6.2

I learned about the extender and how to use it by accident. I just found it mentioned in some github ticket.
So it would be nice, if it could be explained and given an example either in the pdf user-guide or/and in the showcase. 
What do you think?
I do know how to provide PRs for the showcase. 
But I do not know how to provide content to the user guide besides the contents of the schedule.xml file.

**Comment by tandraschko** [comment]
showcase -> https://github.com/primefaces/showcase

**Comment by tandraschko** [comment]
@OBreidenbach Could you please change the documentation? Its here now: https://github.com/primefaces/primefaces/tree/master/docs

**Comment by melloware** [comment]
@OBreidenbach this was merged i think its safe to close?
