### ISSUE TITLE
dialog: has no scrollbars, only on ipad

### ISSUE THREAD

**Issue by rcroonenberghs** [primefaces/primefaces#3742]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: wildfly-10.1.0.Final
- Affected browsers: IPAD safari

## 2) Expected behavior
The content inside the dialog is too big to be displayed. So a vertical scrollbar should be show.

## 3) Actual behavior
There is no scrollbar. And when swiping on the device the content of the main page is scrolled, but the dialog stays in view. But you can not see all info in the dialog.
![image](https://user-images.githubusercontent.com/8414821/40730457-fa33af50-642e-11e8-9f61-531e0f6f132c.png)

Simulating it on Mac with safari in responsive design mode does not give that behavior. 
![image](https://user-images.githubusercontent.com/8414821/40730238-78a9a232-642e-11e8-839b-b4878ea6da26.png)
Also FF, chrome and Android show the correct scrollbars. so it is a ipad only problem.
## 4) Steps to reproduce

String url ="/prospect/detail.xhtml";
Map<String, Object> options = new HashMap<String, Object>();
		options.put("modal", true);
		options.put("draggable", true);
		options.put("resizable", false);
		options.put("contentHeight", 500);
		options.put("contentWidth", 500);
		options.put("height", 500);
		options.put("width", 500);

		addParam("contentHeight", String.valueOf(500));
		addParam("contentWidth", String.valueOf(500));
		PrimeFaces.current().dialog().openDynamic(url, options, params);

**Comment by tandraschko** [comment]
The sample is not runnable. Please fork our primefaces-test project and modifiy it, so we can reproduce your problem.
otherwise it will be closed as invalid.

**Comment by rcroonenberghs** [comment]
I made a small repro case: primefaces-test.7z

one page test.xhtml with 2 buttons. Button "directly in page" opens a dialog that is defined in the xhtml page. This works. on ipad, I can scoll inside the dialog.
2nd button "via bean method" opens a dialog via the bean.  This shows a dialog, but I cannot scroll to the bottom inside the dialog.

On desktop browser and android it works correctly.
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/2096820/primefaces-test.zip)

**Comment by rcroonenberghs** [comment]
Can you reproduce the problem? Any ideas on how to fix it?

**Comment by melloware** [comment]
@rcroonenberghs Can you just try for me and add to your DialogFramework example:

```java
addParam("fitViewport", "true");
addParam("responsive", "true");
```

Does that make it show up?

**Comment by rcroonenberghs** [comment]
@melloware 
I tried what you proposed, but it did not fix the problem. (no change in behavior)

I also tried with options.put. But also no fix
options.put("fitViewport", "true");
options.put("responsive", "true");

Roel

**Comment by melloware** [comment]
OK thanks for trying that out.

**Comment by rcroonenberghs** [comment]
Am I the only one having this issue?

**Comment by melloware** [comment]
Probably not if you were able to reproduce it with the simple PrimeFaces Test project.  It is most likely some kind of Safari IOS CSS issue being translated differently.

**Comment by melloware** [comment]
I think its because Dialog Framework opens the dialog in an IFRAME.  I am not sure how these mobile browsers treat IFRAMES but its probably different than desktop browsers.

**Comment by melloware** [comment]
@rcroonenberghs Have you tried this on newer IOS Safari?  I have a feeling this was definitely a bug in IOS Safari since its working in all other browsers and mobile platform.  Going to close for now.
