### ISSUE TITLE
pop up which confirms the navigation from one page to another

### ISSUE THREAD

**Issue by akhilbabu** [primefaces/primefaces#3744]
## 1) Environment
- PrimeFaces version:6.2
- Application server + version: payara 
- Affected browsers:All

## 2) Expected behavior
While exiting from one page to another from the menu panel .there  should be an option for  pop up just like onbeforeunload java script which allows to cancel navigation .I tried using @PreDestroy ,But the call is not going through the that .while navigating from other menu.
...

## 3) Actual behavior
There should be an option to prevent page navigation .which allow users to save data .(saving just like draft )
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by melloware** [comment]
This is a forum question not a bug.  There are many ways to accomplish what you want.  Please close this ticket and use the forum instead:  https://forum.primefaces.org/viewforum.php?f=3
