### ISSUE TITLE
core.js: PrimeFaces.getFacesResource() throws TypeError "null" when version parameter is passed to it in a portlet environment

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#3746]
## 1) Environment
- > PrimeFaces version:

    `6.2`

- > Does it work on the newest released PrimeFaces version? Does it work on the newest sources in GitHub?

    The bug exists in `master` (`6.3-SNAPSHOT`) as well.

- > Application server + version:

    Tomcat (should be reproducible in any app server)

- > Affected browsers:

    Chrome, Firefox (should be reproducible in any browser)

## 2) Steps to reproduce

1. Copy the sample xhtml into a webapp project and navigate to the page.
2. Click through each of the alerts and note the test results.

## 3) Expected behavior

If the bug is fixed, all alerts will show a "test passed." message.

## 4) Actual behavior

If the bug still exists, an the final alert (for testing a portlet resource URL with a version) will appear with the following message:

> portlet resource URL (with version): TEST FAILED!

The following error will also appear in the browser logs:

```
Uncaught TypeError: Cannot read property '1' of null
    at Object.getFacesResource (core.js.xhtml?ln=primefaces&v=6.3-SNAPSHOT:357)
    at (index):40
```

## 5) Sample XHTML

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:p="http://primefaces.org/ui">
	<h:head />
	<h:body>
		<h:outputScript>

			try {
				var testWebappURL = window.PrimeFaces.getFacesResource("test.css", "testLib");
				console.log(testWebappURL);
				alert('web app resource URL (without version): test passed.');
			}
			catch (error) {
				alert('web app resource URL (without version): TEST FAILED!');
				throw error;
			}

			try {
				var testWebappURL = window.PrimeFaces.getFacesResource("test.css", "testLib", "7.0");
				console.log(testWebappURL);
				alert('web app resource URL (with version): test passed.');
			}
			catch (error) {
				alert('web app resource URL (with version): TEST FAILED!');
				throw error;
			}

			// Replace the core.js resource url with a portlet core.js resource url.
			$('script[src*="/' + window.PrimeFaces.RESOURCE_IDENTIFIER + '/core.js"]').attr('src', 'http://localhost:8080/web/guest/home?p_p_id=pdfviewer_WAR_pdfviewer&amp;p_p_lifecycle=2&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_cacheability=cacheLevelPage&amp;p_p_col_id=column-1&amp;p_p_col_count=2&amp;_pdfviewer_WAR_pdfviewer_javax.faces.resource=core.js&amp;_pdfviewer_WAR_pdfviewer_ln=primefaces&amp;_pdfviewer_WAR_pdfviewer_v=6.3-SNAPSHOT');

			try {

				var testPortletURL = window.PrimeFaces.getFacesResource("test.css", "testLib");
				console.log(testPortletURL);

				alert('portlet resource URL (without version): test passed.');
			}
			catch (error) {
				alert('portlet resource URL (without version): TEST FAILED!');
				throw error;
			}

			try {

				var testPortletURL = window.PrimeFaces.getFacesResource("test.css", "testLib", "7.0");
				console.log(testPortletURL);

				alert('portlet resource URL (with version): test passed.');
			}
			catch (error) {
				alert('portlet resource URL (with version): TEST FAILED!');
				throw error;
			}
		</h:outputScript>
		<p:inputText />
	</h:body>

</html>
```

**Comment by stiemannkj1** [comment]
This bug causes issues for [PrimeFaces Extensions](https://github.com/primefaces-extensions/core) (cc @tandraschko, @melloware) in portlets, since that project uses `getFacesResource()` with the `version` parameter throughout its JavaScript. We discovered the issue with `pe:documentViewer` specifically, but it's likely a problem with many other components. Here's a list of components which may have issues:

- `ckeditor`
- `speedtest`
- `documentViewer`

## Workaround

A simple work around for this issue is to set the `PrimeFacesExt.VERSION` to `null`:

```
<h:head>
	<!-- Your code here... -->
	<f:facet name="last">
		<h:outputScript>
			// Work around https://github.com/primefaces/primefaces/issues/3746
			PrimeFacesExt.VERSION = null;
		</h:outputScript>
	</f:facet>
</h:head>
```

That seems to fix the problem in portlets (without causing major errors) for now.

**Comment by melloware** [comment]
Nice work Kyle!  I approve.

**Comment by tandraschko** [comment]
@stiemannkj1 Could you please add a example here how the URL is different in a porlet enviromemt + add maybe 2-3 comments in the PR?

**Comment by stiemannkj1** [comment]
@tandraschko, I added the comments to the PR: https://github.com/primefaces/primefaces/pull/3747/files

I included the portlet URL in the reproducer:

```
http://localhost:8080/web/guest/home?p_p_id=pdfviewer_WAR_pdfviewer&amp;p_p_lifecycle=2&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_cacheability=cacheLevelPage&amp;p_p_col_id=column-1&amp;p_p_col_count=2&amp;_pdfviewer_WAR_pdfviewer_javax.faces.resource=core.js&amp;_pdfviewer_WAR_pdfviewer_ln=primefaces&amp;_pdfviewer_WAR_pdfviewer_v=6.3-SNAPSHOT
```

The webapp URL looks like this for reference:

```
http://localhost:8080/showcase/javax.faces.resource/core.js?ln=primefaces
```

In a portlet both the resource name and the resource library name are URL parameters (in a webapp the resource name is part of the path). The only other major difference (and the one that causes this problem) is that portlet URL parameters may be namespaced since multiple different portlets may reside on the same page (and potentially use the same parameter names). So the parameters are namespaced to differentiate them between portlets.

**Comment by tandraschko** [comment]
ok, i see.
Just for my interesst :) Is this specified by portlet or just a liferay case?

**Comment by stiemannkj1** [comment]
Ah! Good question! The problem and solution in this case are technically Liferay specific. Sorry, I didn't really think about that. Portlet URLs can have different kinds of encoding (potentially parameters could be encoded in such a way that the client could not even recover the original name=value pair), so this solution does not solve the general problem for portlets. It just fixes things for Liferay where parameters remain relatively similar to their webapp equivalents.

**Comment by tandraschko** [comment]
All right, thanks!
