### ISSUE TITLE
SelectOneMenu: Item Value displayed when fetching data instead of item label for editable = "true"

### ISSUE THREAD

**Issue by ShivaniSK** [primefaces/primefaces#3748]
## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior
When fetching data from DB or passing data during page load , selectOneMenu should display ItemLabel.
...

## 3) Actual behavior
When fetching data from DB or passing data during page load , selectOneMenu is displaying itemValue. 
..

## 4) Steps to reproduce
In the init() method of bean class, the object is initialized with static values. On loading of xhtml page, it should display ItemLabel, but itemValue is getting displayed.
- If we remove editable = true , it works fine. ItemLable is displayed. 
- There was an issue with selectOneMenu where ItemValue was getting displayed all the the time with editable = true. It got resolved in PF 6.2, But now while fetching data from DB or loading data we are facing same issue.
.. 

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:head>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />	
	<script src="../js/projectRequest.js"></script>
</h:head>	
	<h:form id="tst">
		
	<p:selectOneMenu id="city" value="#{projectBean.userInfo.userID}" effect="fold" 
	required="true" requiredMessage="City is required." editable="true" > 
            <f:selectItem itemLabel="Select One" itemValue="" />
            <f:selectItems value="#{projectBean.users}" var="user" itemValue="#{user.userID}" itemLabel="#{user.firstName}"  />
   </p:selectOneMenu>
   
	</h:form>
</html>
```
..

## 6) Sample bean

```
@ManagedBean(name = "projectBean")
@ViewScoped
public class ProjectBeanCompUI {

	@PostConstruct
	public void init()
	{
		userInfo.setFirstName("Shivani");
		userInfo.setLastName("Kanakhara");
		userInfo.setDepartment("IT/QIE");
		userInfo.setUserID("skanakh");
		users.add(userInfo);
       }
       private UserInfo userInfo = new UserInfo();
	private List<UserInfo> users = new ArrayList<>();
	
	
	public UserInfo getUserInfo() {
		return userInfo;
	}
	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}
	public List<UserInfo> getUsers() {
		return users;
	}
	public void setUsers(List<UserInfo> users) {
		this.users = users;
	}

}

```

..

**Comment by melloware** [comment]
I think this is a duplicate of #3477 is it not?

@JhookDev already has a PR ready to fix this: https://github.com/primefaces/primefaces/pull/3685

Please verify its the same issue and close this ticket if it is.

**Comment by ShivaniSK** [comment]
Yes it is the same issue. Thanks. I'll close this one.
But can you please let me know as to when can I expect this issue to be resolved and fixed? Is there going to be a release soon ?

**Comment by melloware** [comment]
You can follow that PR by @JhookDev.  It has not been accepted yet as a fix and I do not work for PrimeTek so I can't predict when it will be accepted and released.

**Comment by melloware** [comment]
I also should mention if you are a PrimeFaces PRO user you can simply request this ticket be fixed.
