### ISSUE TITLE
Bug: Wizard

### ISSUE THREAD

**Issue by bsanders1979** [primefaces/primefaces#375]
When using the Wizard, the actionListener for a CommandButton within a tab beyond the first would not fire because the Wizard is only processing decodes for the first tab. The issue that I see here is that once Wizard.current has been lazily initialized, its value never changes.

See: http://forum.primefaces.org/viewtopic.php?f=3&t=42337

**Comment by cagataycivici** [comment]
Can you post some code please?

**Comment by bsanders1979** [comment]
So, I found this issue prior to opening this, but did not think it was related: https://code.google.com/p/primefaces/issues/detail?id=4736

While putting together the sample code, I see that they are in fact related. The difference is that I'm not using &lt;p:wizard binding="..."&gt;. The binding is occurring elsewhere. My solution is very similar to the one provided in that issue. The difference is that I compare current.id to _step in setStep() instead of in getStepToProcess(). Is there any reason that the code could not be patched to wipe out that variable?

**Comment by cagataycivici** [comment]
Can you post some code please?

**Comment by bsanders1979** [comment]
I felt that putting the check in getStepToProcess() was better since setStep() appears to be generated code. Overriding the process methods to call the getter instead of accessing the variable directly was also necessary.

``` java
package com.n2nglobal.pm.faces.components.wizard;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

import org.primefaces.component.tabview.Tab;

public class Wizard extends org.primefaces.component.wizard.Wizard {

    private Tab current;

    @Override
    public void processValidators(FacesContext context) {
        if(!isBackRequest(context)) {
            getStepToProcess().processValidators(context);
        }
    }

    @Override
    public void processUpdates(FacesContext context) {
        if(!isBackRequest(context)) {
            getStepToProcess().processUpdates(context);
        }
    }

    @Override
    public Tab getStepToProcess() {
        if(current == null || !current.getId().equals(getStep())) {
            String currentStepId = getStep();

            for(UIComponent child : getChildren()) {
                if(child.getId().equals(currentStepId)) {
                    current = (Tab) child;

                    break;
                }
            }
        }

        return current;
    }
}
```

**Comment by tandraschko** [comment]
Will close it for now as no example is available.
You can still create a new issue, respect our issue template and provide a example.
