### ISSUE TITLE
PrimePartialResponseWriter: Nullpointer in line 217

### ISSUE THREAD

**Issue by christophih** [primefaces/primefaces#3753]
## 1) Environment
- PrimeFaces version: 6.2.3
- IBM Websphere ApplicationServer 9.0.0.7, Apache MyFaces

## 2) Expected behavior

Line 217 in PrimePartialResponseWriter ends with a NullpointerException in the class BeanUtils, if the value is null. In previous PF versions, there was a null check.

## 3) Actual behavior

If a callback param with value null is set (I don't know why this happens) a Nullpointer Exception occurs.

Please add the null check to prevent the exception, the execution must run to line 221 in PrimePartialResponseWriter in this case.

Thanks, best regards
Christoph

**Comment by tandraschko** [comment]
should be fixed, please give it a try.
