### ISSUE TITLE
DOM-XSS due to insufficient escaping in PrimeFaces.escapeHTML

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3754]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: n/a
- Affected browsers: n/a

## 2) Expected behavior
`PrimeFaces.escapeHTML` should properly escape HTML and HTML attributes.

## 3) Actual behavior
Implementation of `PrimeFaces.escapeHTML` just escapes `&`, `<` and `>`. However, the function is also used for HTML attribute escaping which the implementation is insufficient for, e.g. in `validation.js`:
```javascript
                else if(display === 'icon') {
                    uiMessage.addClass('ui-message-icon-only')
                            .append('<span class="ui-message-error-icon" title="' + PrimeFaces.escapeHTML(msg.detail) + '"></span>');
                }
```

## 4) Steps to reproduce
- Modify showcase `csv/event.xhtml` like shown below
- Go to http://localhost:8080/showcase/ui/csv/event.xhtml
- Enter _a_ in first input field and click outside the input field to trigger client side validation
- Alert box will appear

## 5) Sample XHTML
```xml
                    <p:inputText id="text" value="#{validationView.text}" required="true" validatorMessage="foo&quot; onmouseover=&quot;alert('xss');">
                        <f:validateLength minimum="2" maximum="5" />
                        <p:clientValidator />
                    </p:inputText>
```

**Comment by cnsgithub** [comment]
@tandraschko Could you please add the security label?

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3762

**Comment by tandraschko** [comment]
Thanks!
