### ISSUE TITLE
photocam: was blocked by chrome

### ISSUE THREAD

**Issue by rafaelbomfim** [primefaces/primefaces#3755]
I use the p:photocam component of primefaces 6.2, but it stopped working in the last few chrome

the browser displays the following error:

[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.

/javax.faces.resource/photocam/photocam.js.xhtml?ln=primefaces&v=6.2

**Comment by erickdeoliveiraleal** [comment]
https://github.com/jhuckaby/webcamjs/issues/276

**Comment by melloware** [comment]
Can someone try it with webcam.js 1.0.25 https://github.com/jhuckaby/webcamjs/releases and see if the issue is fixed?

**Comment by melloware** [comment]
@rafaelbomfim I see you commented on the other forum that this was because you were using photocam inside a p:dialog is that correct?  Once you removed it from the dialog it worked?

**Comment by rafaelbomfim** [comment]
Yes, works well outside the dialog.

**Comment by melloware** [comment]
I updated to PhotoCam 1.0.25 and confirmed the Google deprecation warning is fixed.
