### ISSUE TITLE
Calendar: dialog changes size when browsing months

### ISSUE THREAD

**Issue by mauritz-lovgren** [primefaces/primefaces#3756]
## 1) Environment
- PrimeFaces version: 6.2.4
- Does it work on the newest released PrimeFaces version? No
- Application server + version: JBoss EAP 7.1
- Affected browsers: all major browsers on latest versions

## 2) Expected behavior

Browsing buttons for calendar month should remain in same position regardless of number of days in month when popup pops up above popup button (this happens when calendar is positioned near bottom of page).

## 3) Actual behavior

Dialog popup changes size when month displayed changes between 5 and 6 visible weeks, causing hitting browsing buttons with mouse cursor to be **_troublesome_** when trying to quickly browse a few months ahead or back.

## 4) Steps to reproduce

Go to PrimeFaces showcase for calendar component: https://www.primefaces.org/showcase/ui/input/calendar.xhtml

Make browser window smaller to simulate situation where popup dialog pops up above the button.

Scroll a few months back and forth and notice that the month selector buttons jump up and down and are hard to hit when month changes between 5 and 6 weeks displayed.

## 5) Sample XHTML

N / A, showcase with calendar with button example is good enough.

## 6) Sample bean

N / A, showcase with calendar with button example is good enough.

**Comment by melloware** [comment]
Found this old post on how to fix it:  https://forum.jquery.com/topic/datepicker-height-problem

**Comment by melloware** [comment]
Since this is an issue in core Jquery UI and can be fixed with CSS I am going to close this issue:
```css
.ui-datepicker  {
          font-size: 14px;
          height: 220px;
}
```
