### ISSUE TITLE
SelectCheckboxMenu: CSS state changes only after second click

### ISSUE THREAD

**Issue by grimmjo** [primefaces/primefaces#3759]
## 1) Environment
- PrimeFaces version: 6.1.1
- Does it work on the newest released PrimeFaces version? no
- Application server + version: Wildfly 9.0.2
- Affected browsers: IE11

## 2) Expected behavior
After clicking a select item in the selectCheckboxMenu, the background of the checkbox of the selected item should be set to the correct colour of the css classes ui-state-default or ui-state-active.
...

## 3) Actual behavior

The checkbox of the select item keeps the css class ui-state-focus until the user clicks a second time. 
This also happens to the checkbox for selecting/unselecting all select items.
Maybe this also affects the manyCheckbox component.

## 4) Steps to reproduce

1.  Open the selectCheckboxMenu.
2. After clicking on a select item. The item keeps the background color, defined in the css class ui-state-focus.
![image](https://user-images.githubusercontent.com/14217968/40981524-6439106a-68db-11e8-828b-bca41322db29.png)

3. Click on another select item. The background color of the previous selected item changes, because the css class ui-state-active was assigned and ui-state-focus was removed.
![image](https://user-images.githubusercontent.com/14217968/40981571-883541fa-68db-11e8-8d09-c4410cf923cf.png)

The same happens if the user click on a select item to deselect it. 

## 5) Sample XHTML

N / A, showcase with selectCheckboxMenu with button example is good enough.

## 6) Sample bean

N / A, showcase with selectCheckboxMenu with button example is good enough.

**Comment by tandraschko** [comment]
Currently expected and is the same Problem as here: https://github.com/primefaces/primefaces/issues/3617
