### ISSUE TITLE
Schedule: server side logic should update event model for eventMove & eventResize

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#376]
( Original https://code.google.com/p/primefaces/issues/detail?id=6358 )

Some events in a schedule should be read only - users should be prevented from removing or modifying certain events.

**Comment by cagataycivici** [comment]
There should better be an attribute like updateModelOnEvents="true|false". Where default is true and in your case I think it should be false. Can you confirm?

**Comment by mores** [comment]
There is an attribute called "editable" which prevents an entry to be modified.
In my case I need a little more control, one of the business rules is that an event must be between 9 am and 5 pm. In this case a user should be allowed to move/resize between those values - if they try to resize beyond - it should be denied.

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/pull/6107#issuecomment-654354234
