### ISSUE TITLE
Calendar: Ajax event DateSelect not properly supplying locale specific value

### ISSUE THREAD

**Issue by CJBinder** [primefaces/primefaces#3760]
I am using the p:calendar with mode="inline" and supplying pattern "d-MMM-yyyy HH:mm" and locale of "nl".  I am also using the p:ajax within the component for event "dateSelect" with a process="@this".

If I choose the month of 'mei' and select the 9th day I get the following error "Value '9-May-2018 00:00' could not be understood as a date and time.".  The issue is the component is not properly using 'mei' rather it is using 'May'.  But when trying to parse to a date it is using the passed in Locale which doesn't jive with the value 'May'.  So the ajax event somehow is not translating the selected value per the locale

## 1) Environment
- PrimeFaces version: 6.2.1
- Does it work on the newest released PrimeFaces version? No Version? 6.2.5
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7
- Affected browsers: ALL

## 2) Expected behavior
The value that is parsed should be '9-mei-2018 00:00'
...

## 3) Actual behavior
The value that is parsed is '9-May-2018 00:00' using 'nl' locale which doesn't understand 'May'
..

## 4) Steps to reproduce
Create the component in step #5

.. 

## 5) Sample XHTML
<p:calendar widgetVar="fromCalendar"  mode="inline" id="startDateFilter" value="#{form.startDate}" pattern="d-MMM-yyyy HH:mm" locale="nl">
						<p:ajax listener="#{form.search}"  event="dateSelect" process="@this"  global="false" />
</p:calendar>
..

## 6) Sample bean
Create a form bean that has search method and startDate field with getters and setters.
..

**Comment by CJBinder** [comment]
If I debug using inline mode vs non inline I can see the getSubmittedValue from UIInput returns 'mei' when not in line but 'May' when using inline.

**Comment by CJBinder** [comment]
We fixed the issue by updating the this.cfg.onselect binding when setting the value for the input field, the date/locale settings needs to be passed into the formatDate function.

**Comment by tandraschko** [comment]
PR Welcome ;)

**Comment by CJBinder** [comment]
Did this get accepted as a Defect?

**Comment by tandraschko** [comment]
I could check it if you provide a PR but i dont have to fix it myself.

**Comment by melloware** [comment]
@CJBinder Can you provide the code you used to fix it?

**Comment by CJBinder** [comment]
The following code is what we use to overcome the issue.

       PrimeFaces.widget.Calendar.prototype.bindDateSelectListener = function() {
              var _self = this;

              this.cfg.onSelect = function() {
                     if (_self.cfg.popup) {
                           _self.fireDateSelectEvent();

                           if (_self.cfg.focusOnSelect) {
                                  _self.refocusInput = true;
                                  _self.jqEl.focus();
                                  if (!(_self.cfg.showOn && _self.cfg.showOn === 'button')) {
                                         _self.jqEl.off('click.calendar').on('click.calendar',
                                                       function() {
                                                              $(this).datepicker("show");
                                                       });
                                  }

                                  setTimeout(function() {
                                         _self.refocusInput = false;
                                  }, 10);
                           }
                     } else {
                           // Wrap the config in the settings as the jquery time picker
                           // expects a settings within the init
                           // (1)
                           var settingsObj = {
                                  settings : _self.cfg
                           };

                           var newDate = _self.cfg.timeOnly ? '' : $.datepicker
                                         .formatDate(_self.cfg.dateFormat, _self.getDate(),
                                         /* Begin 2 */$.datepicker
                                                       ._getFormatConfig(settingsObj) /* End 2 */
                                         );
                           if (_self.cfg.timeFormat) {
                                  newDate += ' '
                                                + _self.jqEl.find('.ui_tpicker_time_input')[0].value;
                           }

                           _self.input.val(newDate);
                           _self.fireDateSelectEvent();
                     }
              };
       }
}

[http://static.helpsystems.com/hs/email/templates/signatures-final/images/hs-logo2.png]

CJ Binder
Lead Software Engineer

e. cj.binder@helpsystems.com<mailto:cj.binder@helpsystems.com>
p. 1.800.949.4696 x716
w. GoAnywhere.com<https://www.goanywhere.com/> | HelpSystems.com<https://www.helpsystems.com/>

**Comment by melloware** [comment]
@CJBinder This is an excellent fix. I submitted a PR with this fix.
