### ISSUE TITLE
TreeTable: does not support ajax event "contextMenu"

### ISSUE THREAD

**Issue by iki-hacon** [primefaces/primefaces#3761]
## 1) Environment
- PrimeFaces version: 6.1 / 6.2
- Does it work on the newest sources in GitHub? -> I can not find any hint of this event in the current sources

## 2) Expected behavior
Like Tree and DataTable, TreeTable should also support the ajax event "contextMenu". This is important to react to right click selection with context menu (e.g. to update the menu).

## 3) Actual behavior
Event is not supported.

**Comment by tandraschko** [comment]
PR or Sponsoring via PRO is Welcome.
