### ISSUE TITLE
schedule: Dialog box is not rendered oncomplete of dateSelect event in PF5.3.19.

### ISSUE THREAD

**Issue by shubhangidesh** [primefaces/primefaces#3763]
1) Environment
- PrimeFaces version:5.3.19

2) Expected behavior:
On the p:ajax call inside p:schedule, on completion of dateSelect event PF('myDialog').show() should be displayed.

3) Actual behavior
dialog box is not displayed

4) Sample xhtml
<p:panel style="margin:5px auto;">
	<p:schedule id="mySchedule" widgetVar="mySchedule"
		timeZone="GMT+8" value="#{myscheduleBean.taskList}" draggable="false"
		resizable="false" leftHeaderTemplate="prev,next" aspectRatio="3"
		tooltip="true" timeFormat="hh:mm TT" locale="en">
		<p:ajax event="dateSelect" listener="#{myscheduleBean.onDateSelect}"
			update=":taskDialog" oncomplete="PF('taskDialog').show();" />
		<p:ajax event="eventSelect" listener="#{myscheduleBean.onEventSelect}"
			update=":taskDialog"  />
	</p:schedule>
</p:panel>

<p:dialog id="taskDialog" header="#{myscheduleBean.dialogHeader}"
	widgetVar="taskDialog" showEffect="explode" hideEffect="explode"
	modal="true" resizable="false" >
	<h:form id="myScheduleForm">
		<ui:include src="/myscheduleBody.xhtml" />
	</h:form>
</p:dialog>

**Comment by tandraschko** [comment]
No runnable Sample (bean Missing) andere Not Testes with current Versions -> invalid
