### ISSUE TITLE
confirmDialog: On clicking buttons inside confirmdialog, data from the backing bean is not available 

### ISSUE THREAD

**Issue by shubhangidesh** [primefaces/primefaces#3764]
1) Environment
- PrimeFaces version: 5.3.19

2) Expected behavior:
The values from the bean where confirm dialog opens should be available on clicking buttons inside confirm dialog box.

3) Actual behavior
The values from backing beans are not available after clicking on buttons inside confirm dialog box.
In below example employeeBean.gotoUpdate() is getting selectedEmplyee as null. 

4) Sample xhtml
<p:confirmDialog widgetVar="updateCconfirmation" id="stuConfirmDlgId"
	 message="Do you want to update employee details?"
	 header="Confirmation Dialog" showEffect="explode"
	 hideEffect="explode" modal="true">
	<h:form id="confirmDelDlgForm">
		<div align="center">
			<p:commandButton id="confirmYes"
				 value="Yes" 
				 action="#{employeeBean.gotoUpdate()}"
				 actionListener="#{commonPageLayout.saveReturnPage}"
				 update=":main" immediate="true"
				 onsuccess="PF('updateCconfirmation').hide()">
				<f:setPropertyActionListener
					value="/xhtml/updateEmployeeDetails.xhtml"
					target="#{commonPageLayout.mainIncludePage}"/>
			</p:commandButton>
			<p:commandButton id="confirmNo"
				 value="No" 
				 onclick="PF('updateCconfirmation').hide()" />
		</div>
	</h:form>
</p:confirmDialog>

5) Sample Bean
public class EmployeeBean{
private Employee selectedEmployee;

public Employee getSelectedStudent() {
		if (selectedEmployee == null) {
			return new Employee();
		}
		return selectedEmployee;
	}

	public void setSelectedEmployee(Employee selectedEmployee) {
		this.selectedEmployee = selectedEmployee;
	}

public void gotoUpdate() {
		if (selectedEmployee != null && StringUtils.isNotBlank(selectedEmployee.getEmployeeNo())) {
			initEditProfileBean(selectedEmployee);
		} else {
			restoreMainPage();
		}
	}

}

**Comment by tandraschko** [comment]
No runnable example (WE dont have a employee Classic) andere Not Testes with s current Version -> Invalid.
