### ISSUE TITLE
schedule: Dialog box is not rendered oncomplete of dateSelect event

### ISSUE THREAD

**Issue by shubhangidesh** [primefaces/primefaces#3766]
## 1) Environment
- PrimeFaces version: 5.3.19
- it is working in version Primefaces 5.0 
- It is not working on version Primefaces 5.3.19

- Affected browsers: All browsers

2) Expected behavior:
On the p:ajax call inside p:schedule, on completion of dateSelect event PF('myDialog').show() should be displayed.

3) Actual behavior
dialog box is not displayed

4) Sample XHTML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:i="http://iconnect.ncs.com.sg/jsf/iframe"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/xhtml/templates/mainLayout.xhtml">
	
	<ui:define name="pageTitle">
		<h:outputText value="Employee Task" escape="false" />
	</ui:define>

	<ui:define name="content">

		<p:panel style="margin:5px auto;">
			<p:schedule id="employeeTaskSchedule" widgetVar="employeeTaskSchedule"
				timeZone="GMT+8" value="#{employeeTaskBean.taskList}" draggable="false"
				resizable="false" leftHeaderTemplate="prev,next" aspectRatio="3"
				tooltip="true" timeFormat="hh:mm TT" locale="en">
				<p:ajax event="dateSelect" listener="#{employeeTaskBean.onDateSelect}"
					update=":employeeTaskDialog" oncomplete="PF('employeeTaskDialog').show();" />
			</p:schedule>
		</p:panel>

		<p:dialog id="employeeTaskDialog" header="#{employeeTaskBean.dialogHeader}"
			widgetVar="employeeTaskDialog" showEffect="explode" hideEffect="explode"
			modal="true" resizable="false" >
			<h:form id="employeeTaskForm">
				<ui:include src="/xhtml/employeeTaskFormBody.xhtml" />
			</h:form>
		</p:dialog>
	</ui:define>
</ui:composition>

5) Sample bean

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.DefaultScheduleEvent;
import org.primefaces.model.LazyScheduleModel;
import org.primefaces.model.ScheduleModel;

import EmployeeTask.EmployeeTask;

public class EmployeeBean  {
	private String dialogHeader;
	private ScheduleModel employeeTaskList;
	private boolean isEditable = true;
	private EmployeeTask employeeTask = new EmployeeTask();
	
	public void init() {
		employeeTaskList = new LazyScheduleModel() {
			private static final long serialVersionUID = 1L;

			@Override
			public void loadEvents(Date start, Date end) {
				DefaultScheduleEvent event = null;
				Date date = null;
				// add tasks
				List<EmployeeTask> tasks = getEmpoyeeTasks();
				for (EmployeeTask t : tasks) {
					event = new DefaultScheduleEvent();
					event.setTitle(t.getTaskTitle().trim());
					date = t.getTaskDate();
					event.setStartDate(t.getStartDt());
					event.setEndDate(t.getEndDt());
					event.setDescription(t.getRemarks());
					event.setData(t);					 
	                event.setStyleClass("task");	                    
					addEvent(event);
				}
			
			}

			private List<EmployeeTask> getEmpoyeeTasks() {
				List<EmployeeTask> employeeTasks =new ArrayList<EmployeeTask>();
				EmployeeTask task1 = new EmployeeTask();
				task1.setStaffId("Shubhangi");
				task1.setTaskTitle("Sample Task 1");
				task1.setStartDt(new Date());
				task1.setEndDt(new Date());
				task1.setCreatedBy("Pravin");
				task1.setTaskDate(new Date());
				task1.setRemarks("remarks");
				employeeTasks.add(task1);
				
				EmployeeTask task2 = new EmployeeTask();
				task2.setStaffId("Shweta");
				task2.setTaskTitle("Sample Task 1");
				task2.setStartDt(new Date());
				task2.setEndDt(new Date());
				task2.setCreatedBy("Shubhangi");
				task2.setTaskDate(new Date());
				task2.setRemarks("remarks");
				employeeTasks.add(task2);
				
				return employeeTasks;
			}

		};
	}

	public ScheduleModel getTaskList() {
		if (employeeTaskList == null) {
			init();
		}
		return employeeTaskList;
	}

	public void setTaskList(ScheduleModel taskList) {
		this.employeeTaskList = taskList;
	}
	
	public EmployeeTask getEmployeeTask(){
		return this.employeeTask;
	}

	public void setEmployeeTask(EmployeeTask employeeTask){
		this.employeeTask = employeeTask;
	}
	
	// called when the date be selected in the schedule
	public void onDateSelect(SelectEvent selectEvent) {
		initAddTask((Date)selectEvent.getObject());
	}

	
	private void initAddTask(Date date) {
		isEditable = true;
		dialogHeader = "Add Task";
		RequestContext.getCurrentInstance().reset("EmployeeTaskForm");
		EmployeeTask task = new EmployeeTask();
		task.setTaskDate(date);
		setEmployeeTask(task);
	}
}

**Comment by tandraschko** [comment]
Again: Does it work on 6.2?

**Comment by shubhangidesh** [comment]
No, it is not working on 6.2 as well

**Comment by tandraschko** [comment]
Sample still not complete and a similar example works fine in the showcase.
Next time fork the primefaces-test project instead of providing incomplete samples. Much easier for everyone.

**Comment by shubhangidesh** [comment]
I have provided the Bean and xhtml used in our code, our application is built in using client framework which uses primefaces5.3.19 currently. The same code is working on primefaces5.0. But after upgrade it is not displaying dialogbox oncomplete of ajax call in dateSelect event.

**Comment by melloware** [comment]
Can you provide a fully working sample using the following Test project:  https://github.com/primefaces/primefaces-test  

Simply clone that project and create the smallest working example that will help developers reproduce the problem.

**Comment by shubhangidesh** [comment]
[primefaces-test-master_schedule.zip](https://github.com/primefaces/primefaces/files/2098355/primefaces-test-master_schedule.zip)
This is  fully working sample using the following Test proje
