### ISSUE TITLE
p:autocomplete multiple problem when validation failed

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#377]
Hello team,

My problem is this:

`<h:panelGroup id="panel">`
`<p:inputText value="..." required="true" />`
`<p:autocomplete value="..." required="true" multiple="true" ... />`
`<p:commandButton value="..." process="panel" update="panel" actionListener="..." />`
`</h:panelGroup>`

When I submit the panel, validation fails with inputText and after the panel is updated. When autocomplete is updated the first values are lost and only the last added is retained.

I will try to resolve this problem, meanwhile I hope you check it. I'm using PF 5.2.4.

Greeting,

**Comment by sudheerj** [comment]
I tried to replicate the issue from above scenario(using latest showcase 5.3-snapshot).But all the autocomplete entries remained even after the panel update is completed.Can you make a step by step points to replicate the issue.

**Comment by cagataycivici** [comment]
I can't replicate.
