### ISSUE TITLE
[Documentation] Schedule: update attributes for new FulLCalender version

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3778]
See: https://github.com/primefaces/primefaces/pull/3739

**Comment by tandraschko** [comment]
@OBreidenbach Could you please change the documentation? Its here now: https://github.com/primefaces/primefaces/tree/master/docs

**Comment by melloware** [comment]
@OBreidenbach this was merged i think its safe to close?

**Comment by OBreidenbach** [comment]
@melloware:  @tandraschko opend this issue. So I can not close it.
