### ISSUE TITLE
columnToggler flashing on the left top corner of window

### ISSUE THREAD

**Issue by devprime2** [primefaces/primefaces#378]
i'm using a dataTable using <p:columnToggler> and i've got some <p:commandButton> in ajax mode that update the form/dataTable at completion. When firing my buttons, the content of the toggler is printed and hided very fast like a flash in the let top corner of my page.

issue also reported in https://code.google.com/p/primefaces/issues/detail?id=8164
and in http://forum.primefaces.org/viewtopic.php?f=3&t=42138

**Comment by sudheerj** [comment]
Not able to replicate the issue on latest showcase(runs on PF 5.3-SNAPSHOT).Can you try to replicate the same issue on showcase.

**Comment by devprime2** [comment]
This css code si a workaround

.ui-columntoggler {
    display: none;
}

**Comment by cagataycivici** [comment]
We'll check, thanks.

**Comment by sudheerj** [comment]
The workaround is fine.But I didn't find any flash when the columnToggler datatable component is updated from command actions.May be I missed something.

**Comment by cagataycivici** [comment]
I've added it anyway.

**Comment by devprime2** [comment]
Thanks a lot !

**Comment by karlkilden** [comment]
FYI our team produced a showcase here: https://code.google.com/p/primefaces/issues/detail?id=8164

**Comment by cagataycivici** [comment]
Thank you, this is already fixed as of 5.2.6 and 5.1.19.
