### ISSUE TITLE
commandLink: combination of attributes result in dataTable var corruption

### ISSUE THREAD

**Issue by rvieira5** [primefaces/primefaces#3780]
## 1) Environment
- PrimeFaces version: **6.0**
- Does it work on the newest released PrimeFaces version? Version? **No.** **6.2**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**

## 2) Expected behavior

In the example, the presence of a p:commandLink inside a dataTable should not interfer with the current var attribute value, even if there is another dataTable with the same var attribute name in other locations of the page.

## 3) Actual behavior

During the rendering of the component, the var attribute of the dataTable containing the p:commandLink is being deleted, causing the h:outputText (or any other component inside the h:column tag) to render wrong information in the generated HTML.

## 4) Steps to reproduce

1. Clone the repository https://github.com/rvieira5/primefaces-test
2. Run the command `mvn jetty:run` in the root directory of the project
3. Open the URL http://localhost:8080/primefaces-test in the browser

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:body>
        <h:form id="firstForm">
            <h:dataTable id="firstTable" value="#{testView.list}" var="testRow">
                <h:column>
                    <ui:fragment rendered="#{testRow.flag}">
                        <p:commandLink disabled="#{empty testRow.innerObject}"
                                       update="thirdForm" />
                    </ui:fragment>
                    <h:outputText
                        value="#{empty testRow.innerObject ? 'empty object' : 'not-empty object'}" />
                </h:column>
            </h:dataTable>
        </h:form>

        <h:form id="secondForm">
            <h:dataTable id="secondTable" value="#{testView.list}" var="testRow" />
        </h:form>

        <h:form id="thirdForm">
        </h:form>

    </h:body>
</html>
```

## 6) Sample bean
```
package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import org.primefaces.test.pojo.TestObject;

@ManagedBean(name = "testView")
@RequestScoped
public class TestView implements Serializable {

    private List<TestObject> list;

    @PostConstruct
    public void init() {
        list = new ArrayList<TestObject>();

        list.add(new TestObject(true, new Object()));
        list.add(new TestObject(false, new Object()));
        list.add(new TestObject(false, new Object()));
        list.add(new TestObject(true, new Object()));
        list.add(new TestObject(false, new Object()));
    }

    public List<TestObject> getList() {
        return list;
    }

}
```

**Comment by tandraschko** [comment]
Can you try it with MyFaces? I'm not sure if this is a PF bug.

**Comment by rvieira5** [comment]
Well, it worked as expected with MyFaces. Definitely not a PF bug.

**Comment by erickdeoliveiraleal** [comment]
@rvieira5 create a issue on mojarra side then, https://github.com/eclipse-ee4j/mojarra/issues

**Comment by rvieira5** [comment]
Issue submitted to Mojarra project:

https://github.com/eclipse-ee4j/mojarra/issues/4394
