### ISSUE TITLE
Dialog: fitViewport does not fit correctly if footer is used

### ISSUE THREAD

**Issue by brunoaandrade** [primefaces/primefaces#3784]
## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior
The dialog is larger than the window, so it should adjust the size and a scroll bar on the side, allowing to view all content.
It is very similar to issue [#899](https://github.com/primefaces/primefaces/issues/899).

## 3) Actual behavior
Currently, after clicking on "Show Dialog" the dialog is correctly opened, but at the end, there is some content missing ( about 30px). When the dialog or page is resized, the dialog snaps to the right size.

## 4) Steps to reproduce
Code Below

## 5) Sample XHTML
```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Demo fitViewport</title>
    </h:head>
    <h:body>
        <h:form>
            <p:commandButton  type="button" onclick="PF( 'Test' ).show()" value="Show Dialog" />

            <p:dialog id="Test" widgetVar="Test" header="Test" fitViewport="true" modal="true" responsive="true">
                <div style="height: 1000px;">
                    Demo content
                </div>
                    <f:facet name="footer">
                    <p:commandButton type="button" onclick="PF( 'Test' ).hide()" value="Hide Dialog"/>
                    </f:facet>
            </p:dialog>
        </h:form>
    </h:body>
</html>
```

**Comment by tandraschko** [comment]
Works fine for me with trunk.

**Comment by brunoaandrade** [comment]
My mistake, the commandButton must be inside the footer facet to see the problem. I will correct the code above.

**Comment by tandraschko** [comment]
The problem is that the footerHeight in fitViewport method is not calculated correctly as jquery returns 0.
A fix via PrimeFaces PRO would be great, i tried it fixing it 30 mins but no idea for now.
