### ISSUE TITLE
inputText - KeyFilter: No copy-paste performed in Firefox

### ISSUE THREAD

**Issue by alberto-marin-garcia** [primefaces/primefaces#3785]
Example:

<p:inputText id="filterCommandeNumber" value="#{afrTrackingOTMB.filter.orderNumber}" size="16" maxlength="12">
     <p:keyFilter mask="pint" preventPaste="false"/> 
</p:inputText>

PrimeFaces version:  6.1.15

Neither CTRL-V or right mouse click + paste actions performed into TextBox

**Comment by tandraschko** [comment]
Please respect our issue template or it will be closed.

**Comment by melloware** [comment]
Just tested this little sample and Paste is working fine for me both right click and CTRL+V.  Tested on 6.2 and 6.3-SNAPSHOT.

```xml
<p:inputText  size="16" maxlength="12">
       <p:keyFilter mask="pint" preventPaste="false"/>
</p:inputText>
```

**Comment by alberto-marin-garcia** [comment]
Thanks melloware, tested on Chrome, it works, but is not working in Mozilla !

**Comment by melloware** [comment]
So can you please update the ticket title to say "KeyFilter: No copy-paste performed in Firefox"

**Comment by alberto-marin-garcia** [comment]
In keyfilter.js, keypress event is tested as this:  if (n == 17 || n == 18) { ..
In primeface-extensions (old version) this works with Mozilla too: if (e.ctrlKey || e.altKey) { ...

**Comment by melloware** [comment]
I will investigate and fix.   original code here looks like it is correct have to look and see why it was changed.

https://github.com/akzhan/jquery-keyfilter/blob/master/jquery.keyfilter.js

**Comment by melloware** [comment]
OK it looks like this was changed on purpose in this ticket:  

https://github.com/primefaces/primefaces/issues/1852

I bet we need to do a browser detect.

**Comment by melloware** [comment]
Please review my fix:  https://github.com/primefaces/primefaces/pull/3805

**Comment by alberto-marin-garcia** [comment]
Thanks melloware for your support !!!
