### ISSUE TITLE
ajaxStatus: add attribute "delay"

### ISSUE THREAD

**Issue by jaindsonvs** [primefaces/primefaces#3787]
You can use ajaxStatus to block user from interacting with UI while an ajax call is being made [1]. However, it is very annoying for the user if the ajax call is very fast (it will look like a blink). A delay attribute would make "onstart" to run only after the delay time has passed and only if the ajax is still in progress.
This solution [2] works, but it would be very good to have it native.

[1] https://www.primefaces.org/showcase/ui/ajax/status.xhtml
[2] https://stackoverflow.com/questions/37782947/how-to-delay-primefaces-ajaxstatus-on-jsf

**Comment by melloware** [comment]
I have needed this feature as well so PR submitted.
