### ISSUE TITLE
SelectOneMenu: update not working

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#3788]
Example: https://github.com/erickdeoliveiraleal/primefaces-test

## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? Yes
- Does it work on the newest sources in GitHub? No

## 2) Expected behavior

Click in first selectonemenu, the second should be populated

## 3) Actual behavior

Doesnt work in 6.3-SNAPSHOT

**Comment by jxmai** [comment]
Regression: https://github.com/primefaces/primefaces/issues/3728#issuecomment-395256507

**Comment by tandraschko** [comment]
fixed but heavy testing with appendTo etc combinations welcome ;)
