### ISSUE TITLE
TreeNode: selection vs. value bug

### ISSUE THREAD

**Issue by krisy** [primefaces/primefaces#379]
Hi,

Working on WAS Liberty 8.5.5.5 with PF 5.1 (also tried PF 5.2 as well).
I used the code located on PF showcase Tree selection (http://www.primefaces.org/showcase/ui/data/tree/selection.xhtml), an modified it by adding :

`<propagateSelectionUp="false" propagateSelectionDown="false">`

I experienced the following:
- I selected a top level (parent) node, say: "Pictures"
- The `<selection>` field (`<SelectionView.TreeNode[] selectedNodes2>`) contains only the "Pictures" TreeNode (as expected, since propagation turned off)
- However; if I visit all of the nodes of the tree (`<SelectionView.TreeNode root3>`), I can see that the `<selected>` attribute of all TreeNode elements under "Pictures" is set to true (e.g. "logo")

**Comment by sudheerj** [comment]
The third point is not clear.Can you explain the issue in detail to replicate on showcase example.

**Comment by krisy** [comment]
Thank you for your reply!

If have modified the source code of the showcase (`<SelectionView.java>`) to print out the selected child nodes of the selected nodes:

``` java
    public void displaySelectedMultiple(TreeNode[] nodes) {
        if(nodes != null && nodes.length > 0) {
            StringBuilder builder = new StringBuilder();

            for(TreeNode node : nodes) {
                builder.append(node.getData().toString());
                builder.append("<br />");

                for (TreeNode aChild: node.getChildren()) {
                    if (aChild.isSelected()) {
                        builder.append("selected child found: " + aChild.getData().toString());
                        builder.append("<br />");
                    }
                }
            }

            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Selected", builder.toString());
            FacesContext.getCurrentInstance().addMessage(null, message);
        }
    }
```

If I select "Pictures", I would expect the contents of `<builder>` to only contain "Pictures"; but instead it contains "Pictures", and all of it childnodes:

> Pictures<br />selected child found: barcelona.jpg<br />selected child found: logo.jpg<br />selected child found: optimusprime.png<br />

**Comment by cagataycivici** [comment]
Your link to demo is broken and there are 3 trees if your demo is tree selection. Is it checkbox selection?
If so that is expected, CheckboxTreeNode always propagates, use DefaultTreeNode instead.

**Comment by krisy** [comment]
Updated the broken link; also, thank you for your reply (and yes, I was referring to checkbox selection).
