### ISSUE TITLE
SelectOneMenu: throws ClassCastException if it is used with converter and editable="true" 

### ISSUE THREAD

**Issue by krugerman** [primefaces/primefaces#3791]
## 1) Environment
- PrimeFaces version: 6.2
- Application server: Glassfish 4.1, Wildfly 10.1.0.Final
- Affected browsers: Chrome

## 2) Expected behavior
No exception appears
## 3) Actual behavior
```
SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-8) java.lang.ClassCastException: com.tsystems.ima.sandbox.NamedObject cannot be cast to java.lang.String
	at com.sun.faces.renderkit.html_basic.MenuRenderer.getConvertedValue(MenuRenderer.java:318)
	at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.getConvertedValue(SelectOneMenuRenderer.java:80)
``` 
appears after selecting a value from drop down list
## 4) Steps to reproduce

1. Open page
2. Select 'second' value - exception is thrown

## 5) Sample XHTML
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    
</h:head>
<h:body>
    <h:form id="box">
        <p:outputLabel value="Check select"/>
        <div>
            <p:selectOneMenu id="pdfSelZoom"
                             value="#{namedObjectBean.namedObject}" editable="true"
                             converter="namedObjectConverter">
                <f:selectItems value="#{namedObjectBean.selectItems}"/>
                <p:ajax process="@this" update="selectedValue"/>
            </p:selectOneMenu>
        </div>
        <div>
            <p:outputLabel id="selectedValue" value="Selected value: #{namedObjectBean.namedObject.name}"/>
        </div>
    </h:form>
</h:body>
</html>
```

## 6) Sample bean
```
@ManagedBean
public class NamedObjectBean {
    private NamedObject namedObject = new NamedObject("first");

    private List<SelectItem> selectItems;

    public NamedObject getNamedObject() {
        return namedObject;
    }

    public void setNamedObject(NamedObject namedObject) {
        this.namedObject = namedObject;
    }

    public List<SelectItem> getSelectItems() {
        if (selectItems == null) {
            selectItems = Arrays.asList(
                    new SelectItem(new NamedObject("first"), "first"),
                    new SelectItem(new NamedObject("second"), "second")
            );
        }
        return selectItems;
    }
}
```
## 7) Sample converter
```
@FacesConverter (value = "namedObjectConverter")
public class NamedObjectConverter implements Converter {
    @Override
    public Object getAsObject(FacesContext facesContext, UIComponent uiComponent, String s) {
        return new NamedObject(s);
    }

    @Override
    public String getAsString(
            FacesContext facesContext, UIComponent uiComponent, Object o) {
        return o == null ? null : ((NamedObject)o).getName();
    }
}
```
## 8) Object that is used
```
public class NamedObject {
    private String name;

    public NamedObject(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        NamedObject that = (NamedObject) o;

        return name != null ? name.equals(that.name) : that.name == null;
    }

    @Override
    public int hashCode() {
        return name != null ? name.hashCode() : 0;
    }
}
```

**Comment by melloware** [comment]
Have you tried this with the code in trunk for 6.3-SNAPSHOT?

**Comment by schlebe** [comment]
@Melloware: I have changed my issue's title before reading your comment here.

I can say that this error already exist with Primefaces 6.3-SNAPSHOT.

In #3662 issue, I have documented that String displayed when editable="true" is different from String displayed when editable="false", because ToString() function of Object (not Conerter) is used when readable="true" instead of getAsString() function of Converter !

**Comment by PierreC2** [comment]
Similar problem here. I have a class cast exception stating that  java.lang.Integer cannot be cast to java.lang.String. Reverted back to PF 6.1 and it solved the problem.

**Comment by OBreidenbach** [comment]
I get the same ClassCastException. The failure is introduced by ticket #2862 with commit https://github.com/melloware/primefaces/commit/d95e467070255642be3c9b92dfccd7fdee93322c#diff-e4d3a342df3de892c8fd79acabe27e6bR60.

In [SelectOneMenuRenderer#decode](https://github.com/melloware/primefaces/blob/d95e467070255642be3c9b92dfccd7fdee93322c/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L60) the value of a selectItem is set to submittedValue. With a converter this can be every type of class.
As far as I understand submittedValue, it must be a String. So later on the ClassCastException is thrown:
```
Caused by: java.lang.ClassCastException: com.example.XXX cannot be cast to java.lang.String
	at com.sun.faces.renderkit.html_basic.MenuRenderer.getConvertedValue(MenuRenderer.java:318) 
	at org.primefaces.component.selectonemenu.SelectOneMenu.queueEvent(SelectOneMenu.java:318)
```
in [MenuRenderer](https://github.com/javaserverfaces/mojarra/blob/bbac72aabda02f7e605d05f71da0be2fd0814ce7/impl/src/main/java/com/sun/faces/renderkit/html_basic/MenuRenderer.java#L229)
I am not sure what would be the correct solution for this. 

1. Only set the submittedValue again if the selectItem.value is of type String
1. Only set the submittedValue again if no Converter is present. Not sure what is happening in the case of having an Integer as value in the selectItem.
1. ???

**Comment by melloware** [comment]
Adding @JHookDev since he just fixed this one too: https://github.com/primefaces/primefaces/issues/3477

**Comment by melloware** [comment]
PR submitted can you guys please code review.

**Comment by StevenHachel** [comment]
i try switch from 6.1 to 7.0.15. this problem is not solved!
The change to Primefaces.current() was a lot of work! But unsuccessful!

The change from 4 -> 5 -> 6 always worked. Is Primefaces Dead?

Weblogic 12.1.3.0.0 JavaEE6
jsf-api - 2.1.29-10
omnifaces - 1.14.1
javax.el-api - 2.2.5
primefaces-extensions - 6.1.1

**Comment by tandraschko** [comment]
Why should it be dead? Did you check the commits and activity?....

Why not try a newer version like 8.0?

**Comment by StevenHachel** [comment]
I've been using Primefaces since version 3 and there has never been such a massive problem when upgrading to a new version.

> Why not try a newer version like 8.0?

I hate to move up two levels.

**Comment by tandraschko** [comment]
You cant expect that APIs doesn't change for 10 years. Normally you migrate to 2 other frameworks in this time ;D Check the migration guide, everything is good documented there.

**Comment by GedMarc** [comment]
That is completely unrealistic @StevenHachel - you can't fault on updating your frameworks and then throw your toys when you're out of date.
You fell behind, do the work to catch up.
You can't expect things to work the same they did 5 years or code in the same way you did all those years ago, the technology has changed, quicker now than ever before.

**Comment by StevenHachel** [comment]
> 
> 
> You cant expect that APIs doesn't change for 10 years. Normally you migrate to 2 other frameworks in this time ;D Check the migration guide, everything is good documented there.

i will try again
It is a very large project and therefore very tedious to test everything again.

**Comment by StevenHachel** [comment]
> 
> 
> That is completely unrealistic @StevenHachel - you can't fault on updating your frameworks and then throw your toys when you're out of date.
> You fell behind, do the work to catch up.
> You can't expect things to work the same they did 5 years or code in the same way you did all those years ago, the technology has changed, quicker now than ever before.

There is a reason why it is!

**Comment by GedMarc** [comment]
@StevenHachel There is always a reason on why it's held back, some banks are still running JDK1.4 for pete's sake I'm not about to tell them to upgrade to jackson 2.11, I tell them the R swearword - what is unrealistic is your request, and the comments of things like "i hate moving up 2 versions" - 
So... Welcome to reality. Where if you are unfortunately stuck behind, you are left behind.

**Comment by StevenHachel** [comment]
@GedMarc  "Hate" may be wrongly expressed. bad english, sorry. Unfortunately we don't have the capacity that larger companies have, so it's all a bit difficult!

**Comment by melloware** [comment]
@StevenHachel I understand your frustration but the amount of improvements, security fixes, and bug fixes has been absolutely massive since 6.1  I think over 1200 GitHub tickets have been closed and I know at least 3-4 major security CVE's.  So I highly recommend going to PF8 and reading the Migration Guide.

Yes it will be painful but it will be worth it.

**Comment by StevenHachel** [comment]
@melloware Thanks a lot for this. :) I will upgrade to 8.0 soon. Hopefully it won't be too much of a hassle. :-)

**Comment by StevenHachel** [comment]
@melloware thx for tip for Migration Guide! A lot of work, but now works perfectly!
Steven
