### ISSUE TITLE
duplicated

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#3793]
new Issue https://github.com/primefaces/primefaces/issues/3800

**Comment by Rapster** [comment]
Please follow the template and attach the stacktrace

**Comment by Rapster** [comment]
Thank you but please understand that from what I read from your description, I have no idea how to test your issue... This is why we ask to **follow the issue template**

**Comment by erickdeoliveiraleal** [comment]
Select the second tab and you will see null pointer exception ocuring

**Comment by Rapster** [comment]
I'm not the only one reading this issue, every people in this community might be interested (so don't expect them to read the nth comment to understand what's going on...)

**Comment by erickdeoliveiraleal** [comment]
I updated the issue comment. And now it's very easy to understand how it happens. Why did you marked as invalid?

**Comment by Rapster** [comment]
1. Invalid: because you didn't follow the issue template. Create a new issue and you'll see what it looks like.
2. And unless you have a runnable example including CDI and all the third parties, we encourage people to fork primefaces-test as it's a simple and quick runnable project. So please, either fork it or provide samples that will make it easy to test it on the showcase

**Comment by melloware** [comment]
@Rapster +1 .   @erickdeoliveiraleal Just create a simple example using this project: https://github.com/primefaces/primefaces-test so we can then just run "mvn clean jetty:run" and see your bug in action with a minimal sample.

**Comment by erickdeoliveiraleal** [comment]
I tried, but I can't make CDI work in the repository above. If you don't mind to copy and paste my code (it's very minimal) in a CDI container, please.
ps: would be nice if primefaces-test repository comes with CDI enabled.

**Comment by erickdeoliveiraleal** [comment]
example with spring boot enviroment ( mvn spring-boot:run )
access: http://localhost:8080/helloworld.xhtml
https://github.com/erickdeoliveiraleal/bugpf

**Comment by Rapster** [comment]
I couldn't reproduce the problem using the showcase (and your sample). Don't have time yet to try with Spring Boot.. @erickdeoliveiraleal Would you please **follow the issue template** and have a quick analysis (e.g where exactly occurs the `NullPointerException`, it shouldn't be too difficult), you'd help the team a lot by doing those simple steps

**Comment by tandraschko** [comment]
Please don't use CDI or Spring or anyhting else, each issue must be reproducable with JSF Managed Beans / the plain primefaces-test project, too.

**Comment by erickdeoliveiraleal** [comment]
With managedbean there's no nullpointerexception, only with CDI

**Comment by erickdeoliveiraleal** [comment]
I tested a little more and found that the bug only occurs in a combination of JSF 2.3 + CDI+(Primefaces 6.2 or 6.3-SNAPSHOT)

**Comment by Rapster** [comment]
I'm closing the issue as long the issue template is not filled. Plus, from what you said, panelGrid has nothing to do with this issue. So please make sure to fill everything asked
