### ISSUE TITLE
Message(s): not working correctly with composite components

### ISSUE THREAD

**Issue by kapitanrum** [primefaces/primefaces#3796]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
Element p:message is properly printed for composite component with <cc:editableValueHolder name="input"/> .

## 3) Actual behavior

<p:message> is not printed

## 4) Steps to reproduce

Reproducer: https://github.com/kapitanrum/primefaces-test/tree/demo-label-input-messages

## 5) Sample XHTML

Using like:

````
  <p:outputLabel for="customInputTextTooltipHolder" value="Label for custom InputTextTooltipHolder" />
  <mycomp:inputTextTooltipHolder id="customInputTextTooltipHolder" value="#{testView.testInputCustomHolder}" tooltip="Test tooltip text holder" required="true" />
  <p:message for="customInputTextTooltipHolder" display="text" />

````

resources/mycomp/inputTextTooltipHolder.xhtml:
````
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"  
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <cc:interface>
        <cc:attribute name="value" type="java.lang.String" />
        <cc:attribute name="tooltip" type="java.lang.String" />        
        <cc:attribute name="required" type="java.lang.Boolean" />
        <cc:editableValueHolder name="input" />
    </cc:interface>

    <cc:implementation>
        <span id="#{cc.clientId}">
            <h:inputText id="input" value="#{cc.attrs.value}" required="#{cc.attrs.required}">
                <cc:insertChildren />
            </h:inputText>
            <p:tooltip for="#{cc.clientId}" value="#{cc.attrs.tooltip}" />
        </span>
    </cc:implementation>
</html>
````

![primefaces-messages-issue](https://user-images.githubusercontent.com/450737/41593146-5e318276-73bf-11e8-9751-9a7ec663997c.png)

**Comment by tandraschko** [comment]
The same changes as for outputLabel needs to be done in this component.

**Comment by kapitanrum** [comment]
@tandraschko - Yes

Must be properly identyfied input component in MessageRenderer.java.

Example for fix:

MessageRenderer.java
```
@Override
public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
    Message uiMessage = (Message) component;

    UIComponent target = SearchExpressionFacade.resolveComponent(context, uiMessage, uiMessage.getFor());

>     if (CompositeUtils.isComposite(target)) {
>         target = CompositeUtils.findCompositeInput(target);
>     }
> 

    String targetClientId = target.getClientId(context);

    encodeMarkup(context, uiMessage, targetClientId);
    encodeScript(context, uiMessage, target);
}
```
and in CompositeUtils.java:

```
/**
 * Find first deepest editable value holder composite component.
 *
 * @param composite Composite component
 * @return Editable value holder component
 */
public static UIComponent findCompositeInput(UIComponent composite) {

    if (composite instanceof EditableValueHolder) {
        return composite;
    }

    BeanInfo info = (BeanInfo) composite.getAttributes().get(UIComponent.BEANINFO_KEY);
    @SuppressWarnings("unchecked")
    List<AttachedObjectTarget> targetList = (List<AttachedObjectTarget>) info.getBeanDescriptor().getValue(
            AttachedObjectTarget.ATTACHED_OBJECT_TARGETS_KEY);

    for (AttachedObjectTarget target : targetList) {
        if (target instanceof EditableValueHolderAttachedObjectTarget) {
            final List<UIComponent> children = target.getTargets(composite);
            if (children == null || children.isEmpty()) {
                throw new FacesException(
                        "Cannot find editableValueHolder with name: \"" + target.getName() + "\" in composite component with id: \""
                                + composite.getClientId() + "\"");
            }

            if (children.size() > 1) {
                throw new FacesException(
                        "Only a single editableValueHolder target is supported in composite component with id: \""
                                + composite.getClientId() + "\"");
            }

            final UIComponent child = children.get(0);

            return findCompositeInput(child);
        }
    }

    return null;
}
```

**Comment by tandraschko** [comment]
We must use the COmpositeUtils#invokeOnDeepestEditableValueHolder, too
If we switch to JSF2.3, we can only use callbacks, which is the right way to work on components with the right context.

**Comment by kapitanrum** [comment]
OK, you're probably right.

**Comment by kapitanrum** [comment]
@tandraschko - I do not think callback is needed, because p:message**s** don't have a callback and still display the texts correctly.

**Comment by tandraschko** [comment]
As i said, JSF23 is completely based on callbacks, so therefore introducing a new method doesn't make sense for me.

**Comment by tandraschko** [comment]
could someone try to check why this works with p:messages but not with p:message?
we could easily add this CC logic here BUT in theory it should not work with p:messages as we dont have this CC logic there and we get the messages for the composite-clientId, not for the wrapped input.

**Comment by melloware** [comment]
I have debugged this and can explain why it works for Messages and not Message.

Messages falls into the following `else` block and the value of `forIgnores` is `NULL`.
```java
 else {
            String[] ignores = uiMessages.getForIgnores() == null
                    ? null
                    : SearchExpressionFacade.split(context, uiMessages.getForIgnores(), SearchExpressionFacade.EXPRESSION_SEPARATORS);
            Iterator<String> keyIterator = context.getClientIdsWithMessages();
            while (keyIterator.hasNext()) {
                String key = keyIterator.next();
                if (ignores == null || !LangUtils.contains(ignores, key)) {
                    Iterator<FacesMessage> messagesIterator = context.getMessages(key);
                    while (messagesIterator.hasNext()) {
                        if (messages == null) {
                            messages = new ArrayList<>(5);
                        }
                        messages.add(messagesIterator.next());
                    }
                }
            }
        }
```

So what happens is `Iterator<String> keyIterator = context.getClientIdsWithMessages();` returns all input keys on the page thta have a validation message and displays it in Messages.  Our Message component is simply looking up the `targetClientId` which is not resolving if its inside a Composite..

**Comment by tandraschko** [comment]
Not sure.
If you get the sample project and replace all message with mesages, only the messages in each line for the associated Input is displayed? 
Or do i remember incorrectly?

**Comment by melloware** [comment]
No replacing with `messages` does not work.  Attached is a reproducer:
[pf-3796.zip](https://github.com/primefaces/primefaces/files/5585679/pf-3796.zip)

**Comment by tandraschko** [comment]
it seems to work for me? just replaced all p:message with p:messages in test.xhtml and its displayed each line?

**Comment by melloware** [comment]
Hmm If I replace all `message` with `messages` I still get this:
![image](https://user-images.githubusercontent.com/4399574/100101518-5a1ba080-2e30-11eb-8e99-92d1eda8516d.png)

Those last two inputs should have messages next to them...

**Comment by tandraschko** [comment]
ahhh
yep

im unsure what we should do here
we can easy fix message, first check for messages attaached to the CC, otherwise fallback to extrack the input and check messages for the input
messages a bit more work as its inside a loop and should we also display both - messages attached for the CC and the extraced input?

tooltip is almost impossible to support because of PFS

also CSV needs to be adjusted actually

**Comment by melloware** [comment]
@NicolaIsotta comment on this ticket so I can assign it to you please.

**Comment by NicolaIsotta** [comment]
> messages a bit more work as its inside a loop and should we also display both - messages attached for the CC and the extraced input?

looking at messages/growl right now. I think there are 3 options:

1. leave them as they are
2. extract messages from composites
3. let the user decide with context param or component attribute

I would choose 2, WDYT @tandraschko @melloware ?

**Comment by melloware** [comment]
I personally think 2 as well as these should all behave the same
