### ISSUE TITLE
filtering with checkbox selection for p:tree 

### ISSUE THREAD

**Issue by anhmt90** [primefaces/primefaces#3799]
n Primefaces 6.2 , I have problem when using  `<p:tree>` with `checkbox` selection on a parent node after filtering the tree. 

Let's say I have a tree like this [Tree][1] and I want to filter it by `filterMatchMode="contains"` with keyword *"20"*. After filtering, the tree is displayed like this [filtered Tree][2], which meaning the filter has worked correctly. Then I checkbox the parent node *"parent 0"* to select all the filtered child nodes (I want to select only *"child 20"* and *"child 20-01"*). The problem is that primefaces selects **all** the child nodes of *"parent 0"*, including node *"child 10"*. 

I have googled for a way to retrieving filtered values with in `<p:tree>` but there is no clue about that. I think this may be a bug in Primefaces or a missing in filter feature of tree.

  [1]: https://i.stack.imgur.com/jjx2E.png
  [2]: https://i.stack.imgur.com/0N4Kd.png

**Comment by tandraschko** [comment]
respect our issue template, for questions use the forum.
