### ISSUE TITLE
tabView: event.getTab() null in Mojarra 2.3

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#3800]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: WildFly 14 + EE8 enabled
- Affected browsers: all

## 2) Expected behavior

event.getTab().getId() should work.

## 3) Actual behavior

event.getTab() is null in first click

## 4) Steps to reproduce
Clone: https://github.com/erickdeoliveiraleal/primefaces-test
Run: http://localhost:8080/primefaces-test

Use JSF 2.3 + Named anotation (CDI enabled enviroment)
Run project and click on second tab of the xhtml provided. A NullPointerException will be thrown.
In the .xhtml file I provided there's a selectOneMenu and a panelGrid columns=4 without these combination, no NullPointerException is thrown.

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head>

</h:head>

<h:body>



	<h:form>

		<p:selectOneMenu>
			<f:selectItem itemLabel="Nenhsum" noSelectionOption="true" />

		</p:selectOneMenu>

	</h:form>


	<h:form prependId="false" id="form">
		<p:tabView id="tabView" prependId="false">
			<p:ajax event="tabChange" listener="#{test2.onTabChange}"
				update="@this" />

			<p:tab id="tabDetalhes" title="Detalhes">


				<p:panelGrid columns="4">

					<h:outputText value="Histórico" />
					<h:outputText value="aaa" />

				</p:panelGrid>

			</p:tab>
			<p:tab id="tabDisciplina" title="Disciplina">


			</p:tab>


		</p:tabView>
	</h:form></h:body></html>
```

</html>

## 6) Sample bean

```
@ViewScoped
@Named("test2")
public class TestView implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6417971395080639314L;

	public void onTabChange(TabChangeEvent event) throws Exception {
		System.out.println(event.getTab().getId());
	}
}

```
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/2176658/primefaces-test-master.zip)

**Comment by tandraschko** [comment]
primefaces-tests now supports CDI and both MF and Mojarra 2.3.

Your example only fails on Mojarra23+CDI.

**Comment by tandraschko** [comment]
JFYI: the http parameter clientId+"_newTab" is different on MyFaces and Mojarra, so actually something is different on the client side.
A PR to fix this would be great, don't have time.

**Comment by erickdeoliveiraleal** [comment]
thank you, I added an jetty working example.

**Comment by tandraschko** [comment]
Probably the same problem as #3859

**Comment by erickdeoliveiraleal** [comment]
fixed in #4122

**Comment by NOTiFYcouk** [comment]
"tabView: event.getTab() null in Mojarra 2.3" still current on: 
Mojarra 2.3.14.SP01
WildFly 21.0.2.Final
WELD  3.1.5 (Final)

**Comment by melloware** [comment]
@NOTiFYcouk you can see the Mojarra 2.3 ticket is still open here: https://github.com/eclipse-ee4j/mojarra/issues/4407

Its a Mojarra bug not a PF bug.
