### ISSUE TITLE
TreeTable : Paginator Template issue

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#3801]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) NO
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
As per user guide 6.2 - Paginator Template : Page 147
Also {CurrentPageReport} has it’s own template defined with currentPageReportTemplate option.
You can use {currentPage},{totalPages},{totalRecords},{startRecord},{endRecord} keyword
within currentPageReportTemplate. **Default is {currentPage} of{totalPages}.**

## 3) Actual behavior

The currentPageReportTemplate default is not set.  The workaround is to explicitly define 
`currentPageReportTemplate="{currentPage} of {totalPages}"`

> SEVERE: null
> java.lang.NullPointerException
> 	at org.primefaces.component.paginator.CurrentPageReportRenderer.render(CurrentPageReportRenderer.java:36)
> 	at org.primefaces.renderkit.DataRenderer.encodePaginatorMarkup(DataRenderer.java:112)
> 	at org.primefaces.component.treetable.TreeTableRenderer.encodeRegularMarkup(TreeTableRenderer.java:412)
> 	at org.primefaces.component.treetable.TreeTableRenderer.encodeMarkup(TreeTableRenderer.java:314)
> 	at org.primefaces.component.treetable.TreeTableRenderer.encodeEnd(TreeTableRenderer.java:214)
> 	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:949)
> 	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1912)

..

## 4) Steps to reproduce
Defined paginatorTemplate without currentPageReportTemplate.
.. 

## 5) Sample XHTML
/showcase/src/main/webapp/ui/data/treetable/paginator.xhtml

`<p:treeTable value="#{ttPaginatorView.root}" var="document" paginator="true" paginatorAlwaysVisible="true" rows="2" paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}{LastPageLink} {RowsPerPageDropdown}">`
..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
PR welcome
