### ISSUE TITLE
chart: Charts are not displayed inside primefaces Extention layoutPane

### ISSUE THREAD

**Issue by mazenkhalil** [primefaces/primefaces#3803]
## 1) Environment
- PrimeFaces version: **6.2**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**
- Application server + version:  **Tomcat8 + Tomcat8.5 +Tomcat9 - JSF23 + Mojarra23+CDI**
- Affected browsers: **Firefox + Chrome + IE**

**Using primefaces v6.1 it work well**

## 2) Expected behavior
Charts should be drawn without issues inside pe:layoutPane
...

## 3) Actual behavior
Charts are not drawn inside pe:layoutPane
..

## 4) Steps to reproduce
- Create layout page using primefaces extention
- Inside pe:layoutPane, add p:chart of any type
- Whenever the page is loaded, managed beans get called successfully, but the chart doesn't get rendered (Appears as empty div)
.. 

## 5) Sample XHTML
<pe:layout fullPage="true">  
            <pe:layoutPane position="center">  
                 <p:chart type="pie" model="#{chartView.pieModel}" />
            </pe:layoutPane>  
        </pe:layout
..

## 6) Sample bean
import javax.annotation.PostConstruct;
import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import org.primefaces.model.chart.PieChartModel;
 
@ManagedBean
public class ChartView implements Serializable {
 
    private PieChartModel pieModel;
 
    @PostConstruct
    public void init() {
        createPieModel();
    }

    public PieChartModel getPieModel() {
        return pieModel;
    }

    private void createPieModel() {
        pieModel = new PieChartModel();
        pieModel.set("Brand 1", 540);
        pieModel.set("Brand 2", 325);
        pieModel.set("Brand 3", 702);
        pieModel.set("Brand 4", 421);
        pieModel.setTitle("Simple Pie");
        pieModel.setLegendPosition("w");
    }
}

**Comment by tandraschko** [comment]
@melloware Could you check this if related to PF or PFE?

**Comment by melloware** [comment]
I will check but if I had to guess @tandraschko its the same issue as these:

https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/536

https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/562

Something to do with the old code being wrapped "function(){}" and the new Scripts initWithDomReady().

**Comment by melloware** [comment]
OK I have figured out the issue you can read about it here https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/536

I am releasing PF Extensions 6.2.7 right now should be in Maven Central in a couple of hours and it will fix this issue.  Feel free to close this issue as its not PF issue but a PFE issue.

**Comment by melloware** [comment]
Can you try this again with PFE 6.2.7 which is now in Maven Central?

**Comment by mazenkhalil** [comment]
I tried this with PFE 6.2.7, it is working well. But I realized another case with Layout itself. When the page reloads (or in case of redirection) the center pane takes full size of page initially then other panels starts to take place after loading page content. With 6.1 version, it wasn't behave like this.

This cause a problem with charts size. As it gets drawn based on full page size, then adding the other panels (north and west) take size which results to unresponsive chart drawn on page...

**Comment by melloware** [comment]
@mazen-khalil Can you try adding this to your web.xml and try again?  I just want to see if this fixes it.

```xml
   <context-param> 
       <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM </param-name>
        <param-value>true</param-value>
  </context-param>
```

**Comment by mazenkhalil** [comment]
This makes loading the page more smooth... But chart responsiveness is not working as expected (It may be because I am using bootstrap as well).
I will investigate more about chart responsiveness, if I found something I will issue different ticket.
Thank you for you support!
