### ISSUE TITLE
Form components should not remove ui-state-active onfocus

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3807]

**Comment by martin654** [comment]
@tandraschko Could this be merged into 6.2.x Elite version?

**Comment by tandraschko** [comment]
thats up to @mertsincan 
as it's more a new behavior instead of a bugfix, i wouldn't do it probably.

**Comment by mertsincan** [comment]
Thanks a lot for this enhancement, @tandraschko ;) @martin654 unfortunately, I don't think of adding it to elite versions.

**Comment by mertsincan** [comment]
We decided to add this fix to Elite version.
