### ISSUE TITLE
EmptyMessage Facet for DataGrid

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#381]
Allow custom and more complex empty messages in datagrid defining optional facet for `emptyMessage`:

for good usability search interfaces with possible empty results should show clear indication for which input no results could be provided. 

More advanced interfaces even provide more suggestions:
- Did you mean 'xy'? with a link button to invoke new search
- You may try one of these queries? ... list of queries for certain input parameters
- Display images or very complex html. Show alternative items from different datasource or others.

Possibilities are endless.

Simple example which is already hard to define within a single el expression attribute using ternary operator. 
- No items found for search term 'xy'.
- No items found for search term 'xy' in category 'z'.
- No items found.

Forum URL: http://forum.primefaces.org/viewtopic.php?f=3&t=41865

**Comment by cagataycivici** [comment]
Sounds good, will do.
