### ISSUE TITLE
How to use <p:steps> in Primefaces

### ISSUE THREAD

**Issue by YahiaZZ** [primefaces/primefaces#3811]
## 1) Environment
- PrimeFaces version:
primefaces-6.2

## 2) Expected behavior
Navigating with different steps in <p:steps>
...

## 3) Actual behavior
cannot start correctly
..

## 4) Steps to reproduce

looking for a detailed tutorial

## 5) Sample XHTML
```
<p:steps>
                <p:menuitem value="Personal"/>
                <p:menuitem value="Seat Selection"/>
                <p:menuitem value="Payment"/>
                <p:menuitem value="Confirmation"/>
            </p:steps>
```
..

## 6) Sample bean

..Not yet

Thanks

**Comment by tandraschko** [comment]
Use the Forum for questions, this is for issues
