### ISSUE TITLE
Datatable: provide widget helper functions for navigation and editing

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces/primefaces#3817]
Feature request:

Improve navigation and editing possibilities for the javascript datatable object.

- rowUp and rowDown in single selection mode
- editSelectedRow, saveSelectedRow and cancelSelectedRow when one row is selected
- nextPage and prevPage

users may choose to bind these functions to a hotkey.

**Comment by melloware** [comment]
Closing for now unless more people request this functionality.
