### ISSUE TITLE
MenuItem: url attribute for relative path loses application context

### ISSUE THREAD

**Issue by JHookDev** [primefaces/primefaces#3819]
## 1) Environment
- PrimeFaces version: 6.2.6
- Does it work on the newest released PrimeFaces version? No Version? 6.2.6
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7.0.23 and 9.0.8
- Affected browsers: Chrome, Firefox, IE,...

## 2) Expected behavior

Selecting menuitem with url attribute where relative path is provided within the same application should retain application context and route to page. For example: http://localhost:8080/{applicationContext}/{destinationpage}

This works as expected in versions 6.2.5 and lower.

## 3) Actual behavior

Selecting menuitem with url attribute where relative path is provided within the same application loses the application context resulting in http status 404. For example: http://localhost:8080/{destinationpage}

## 4) Steps to reproduce

Using the sample XHTML files , open browser to menuitem.xhtml and then click the 'Relative Path' menu option using primefaces-6.2.6.jar. You will receive a 404 error, due to not being able to find http://localhost:8080/menuitemlanding.xhtml. Where it should have routed to http://localhost:8080/{applicationContext}/menuitemlanding.xhtml

## 5) Sample XHTML
_menuitem.xhtml_
```
<ui:composition lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:ccds="/ccds/taglib"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


	<h:head>
		<title>menuitem - relative path loses application context</title>
	</h:head>

	<h:body>
		<f:view>
			<h:form id="menuitem">
				<p:menubar id="menuBar">
					<p:menuitem id="menuItem1" url="/menuitemlanding.xhtml" value="Relative Path"/>
				</p:menubar>
			</h:form>
		</f:view>
	</h:body>

</ui:composition>
```

_menuitemlanding.xhtml_
```
<ui:composition lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:ccds="/ccds/taglib"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


	<h:head>
		<title>menuitem - relative path loses application context</title>
	</h:head>

	<h:body>
		<f:view>
			<h:outputText id="outputText" value="made it to menuitemlanding"/>
		</f:view>
	</h:body>

</ui:composition>
```

## 6) Sample bean

N/A

**Comment by tandraschko** [comment]
We changed it by design. Url is the native url, but you can use outcome or add #{request.contextPath}

**Comment by tandraschko** [comment]
Duplicate of: https://github.com/primefaces/primefaces/issues/3154 / https://github.com/primefaces/primefaces/issues/3506

**Comment by JHookDev** [comment]
@tandraschko Thank you for commenting quickly. Are you able to tell us what components and attributes are impacted by the design change so that we can better assess the impact to our application(s)?

In addition, I would like to request that changes such as this be included in the release notes and associated GitHub tags/labels. Since a change of this nature can impact applications negatively.

**Comment by tandraschko** [comment]
I'm not managing the elite releases, mert may just forgot it.

https://github.com/primefaces/primefaces/wiki/Migration-Guide (6.2 - 6.3)
I think all url/href attributes for button/link/menuItem, but i would need to check the code, too.

**Comment by AnkitaNalawade88** [comment]
Can someone provide me this fix, i am facing issues while navigating to different pages, my context root gets changed.
i am using latest version of primefaces ..i.e.
<primefaces.version>6.2</primefaces.version>
<primefacesExt.version>6.2.4</primefacesExt.version>

Please guide, which version supports menu item / url navigations .. ???

**Comment by heatherita** [comment]
Watch out for this one folks! It gave me trouble upon upgrading from PF 6.2 to PF 7.0, partly because I had upgraded to a custom theme at some point along the way and I wasn't sure if the theme was causing the problem. A quick addition of omnifaces method `Faces.getRequestContextPath()`  saved me. So glad to have figured it out!

**Comment by ghost** [comment]
Upgraded 6.2 to 7.0 successfully too with help of this ticket.

@heatherita
As mentionned by @tandraschko 

Replacing menuitem.setUrl() calls by menuitem.setOutcome() does it and you do not need to play with the contextPath,

Imo that is a dirty solution to use Faces.getRequestContextPath(), just forget setUrl

**Comment by tandraschko** [comment]
Yep, Url should only be used for external or non-faces internal Urls
