### ISSUE TITLE
Datatable column render state lost after row edit

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#382]
I have a datatable inside a composite component with a flag which triggers visibility of certain columns. 

After a row editing event sometimes the cell dissapears  in case columns are rendered conditionally and at least one column exists which is not rendered.
(`<td></td>` is not rendered!)
# Cases:

All cells have celleditor inside.
## Initial table:

```
<p:datatable>
    <p:column headerText="A"/>
    <p:column headerText="B"/>
    <p:column headerText="C"/>
    <p:column headerText="D">
    <p:column headerText="E">
        <p:rowEditor/>
    </p:column>
</p:datatable>
```

**Observation:** Everything works as expected.
## Case 2:

Composite argument: `hideColumn = true`

```
<p:datatable>
    <p:column headerText="A"/>
    <p:column headerText="B"/>
    <p:column headerText="C"/>
    <p:column headerText="D" rendered="#{cc.attrs.hideColumn}">
    <p:column headerText="E">
        <p:rowEditor/>
    </p:column>
</p:datatable>
```

**Observation:** Cell "E" of edited row dissapears after row editing. 
## Case 3:

Composite argument: `hideColumn = false` 

```
<p:datatable>
    <p:column headerText="A"/>
    <p:column headerText="B"/>
    <p:column headerText="C" rendered="#{cc.attrs.hideColumn}">
    <p:column headerText="D" rendered="#{cc.attrs.hideColumn}">
    <p:column headerText="E">
        <p:rowEditor/>
    </p:column>
</p:datatable>
```

**Observation:** Cells "C", "D", "E" of edited row dissapear after row editing.

**Workaround:**

Use JSTL `c:if` to render columns conditionally since `ui:fragment` is just being ignored.

**Comment by cagataycivici** [comment]
You can't use conditional column rendering with row edit as it will break table layout and display will be broken. Instead conditionally render the content.

Please use forum for questions like these.
