### ISSUE TITLE
Dialog Framework: option closeOnEscape not working

### ISSUE THREAD

**Issue by jdmc562** [primefaces/primefaces#3824]
## 1) Environment
- PrimeFaces version: 6
- Affected browsers: Chrome, Edge

## 2) Expected behavior
When adding the option closeOnEscape in the dialog framework I expect escape should work, just as it does in a dialog component from xhtml page

## 3) Actual behavior
Option does not seem to function where others do

## 4) Steps to reproduce
 Map<String,Object> options = new HashMap<String, Object>();
        options.put("resizable", false);
        options.put("draggable", false);
        options.put("closeOnEscape", true);
        options.put("modal", true);
        PrimeFaces.current().dialog.openDynamic("select", options, null);

**Comment by melloware** [comment]
Are you using PF 6.2? This was fixed already as you can see here:  https://github.com/primefaces/primefaces/issues/2617

Your ticket above says you are using PF 6.0.
