### ISSUE TITLE
Erroneous use of escapeText on calls to WidgetBuilder.attr

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3825]
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
JS syntax errors must never occur, input must be redisplayed correctly.

## 3) Actual behavior
Double escaping (JS and JSON) may result in JS syntax errors or wrong display.

Since Dec, 28 2017 `WidgetBuilder.attr` escapes the value itself, which in my opinion is the correct approach. However, some of the older callers do the escaping themselves, e.g. in `PasswordRenderer`, lines 67 to 70:
```java
                    .attr("promptLabel", escapeText(password.getPromptLabel()))
                    .attr("weakLabel", escapeText(password.getWeakLabel()))
                    .attr("goodLabel", escapeText(password.getGoodLabel()))
                    .attr("strongLabel", escapeText(password.getStrongLabel()));
```

## 4) Steps to reproduce
Modify the [showcase ](http://localhost:8080/showcase/ui/input/password.xhtml) as shown below and enter just one character within the turkish feedback input. The forward slash of the `weakLabel `will be erroneously escaped and preceded with a backslash.

![image](https://user-images.githubusercontent.com/13161711/42018693-23503616-7ab3-11e8-97b5-814308a893ac.png)

## 5) Sample XHTML
```xml
                <p:password id="turkishFeedback" value="#{passwordView.password3}" feedback="true" 
                            promptLabel="PROMPT" weakLabel="WEAK/"
                            goodLabel="GOOD" strongLabel="STRONG" />
```

## 6) Sample bean
Use the unmodified showcase bean.

## 7) Solution
Find all potential occurrences of `\.attr\(.*escapeText` regex and remove the `escapeText` calls. Ensure that the attributes are escaped correctly in the appropriate JS files.

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3832

**Comment by melloware** [comment]
Thanks for noticing this.  I fixed it in PrimeFaces Extensions as well.
