### ISSUE TITLE
XSS in PrimeFaces.showMessageInDialog

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#3828]
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
Proper escaping

## 3) Actual behavior
Improper escaping

## 4) Steps to reproduce
Go to the showcase, open the console and enter `PrimeFaces.showMessageInDialog({severity:"ERROR", summary:"summary", detail:"<script>alert('xss');</script>"});` This will bring up an alert box.

The aforementioned JS function is also called by method `PrimeFaces.showMessageDynamic `in Java.

**Comment by cnsgithub** [comment]
I'd like to provide a PR for this issue. However, I stumbled upon newline replacement done in `PrimeFaces.showMessageDynamic`:
```java
        public void showMessageDynamic(FacesMessage message) {
            String summary = ComponentUtils.escapeText(message.getSummary());
            summary = ComponentUtils.replaceNewLineWithHtml(summary);

            String detail = ComponentUtils.escapeText(message.getDetail());
            detail = ComponentUtils.replaceNewLineWithHtml(detail);

            executeScript("PrimeFaces.showMessageInDialog({severity:\"" + message.getSeverity()
                    + "\",summary:\"" + summary
                    + "\",detail:\"" + detail + "\"});");
        }
```

Carriage returns and line feeds are replace with HTML `<br>`. However, it's totally unclear that the JS function `PrimeFaces.showMessageInDialog `supports HTML in `summary `and `detail`. And it is indeed not supported completely. From looking at the JS code (`core.dialog.js`, line 202) this cannot work if `summary` contains HTML: `this.messageDialog.titleContainer.text(msg.summary);`

And here is the proof that it doesn't work: Executing this in the console shows up the `<br>` to the user:
`PrimeFaces.showMessageInDialog({severity:"ERROR", summary:"summary<br>containing newline", detail:"detail"});`

![image](https://user-images.githubusercontent.com/13161711/42076503-ba9ad2e8-7b75-11e8-955f-e9a117d4ef6f.png)

So the question is now if we really should support newlines being replaced with HTML? This makes things tricky. If we would handle this correctly we have to split `summary `and `detail `and pass arrays to the JS function which in turn must escape the array elements and put them together with `<br>`.

I'm voting for dropping the newline support at all as it doesn't work either at the moment. What do you think? Vote ups are very welcome. @tandraschko @melloware

**Comment by melloware** [comment]
Hmmm my concern is the newline support was put in there by Optimus Prime for a reason or Mert for a PRO user?  Can we look through the Git Log to see when that newline code was added or if it has always been there?

**Comment by cnsgithub** [comment]
The `PrimeFaces `class was introduced by @tandraschko in revision a69e8a60c5552a6ce349fc0658a7f03cb1f32c66 on October 24, 2017. I think that's just a refactoring (https://github.com/primefaces/primefaces/issues/2853) and the method had been existing before elsewhere.

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3850. Please see PR comments for further information.
