### ISSUE TITLE
Compilation: Build Failure on Windows 7 machine since https://github.com/primefaces/primefaces/commit/b64e8cce5d4015c20f9a5fa1560c5ffc7b522743 - FeedInput.java:[31,30] cannot access org.jdom2.Document

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#3829]
## 1) Environment
- PrimeFaces version: PrimeFaces Trunk
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: N/A
- Affected browsers: N/A

## 2) Expected behavior

Build Failure should not occur on any OS enviroment

## 3) Actual behavior

Build Failure occurs

## 4) Steps to reproduce

Build the source using Windows 7 machine via cmd / git bash

maven info: `Apache Maven 3.5.4`
```
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

After `mvn clean install`:

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /E:/workspace/primefaces/src/main/java/org/primefaces/component/feedreader/FeedInput.java:[31,30] cannot access org.jdom2.Document
  class file for org.jdom2.Document not found
[INFO] 1 error

...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.                                                                                                                1:compile (default-compile) on project primefaces: Compilation failure
[ERROR] /E:/workspace/primefaces/src/main/java/org/primefaces/component/feedread                                                                                                                er/FeedInput.java:[31,30] cannot access org.jdom2.Document
[ERROR]   class file for org.jdom2.Document not found
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                                                                                ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                                                                                d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc                                                                                                                eption

```

vsCode can also detect the same error

![image](https://user-images.githubusercontent.com/10467831/42041183-fb941aa8-7ab6-11e8-84ee-18e71dcbf277.png)

## 5) Analysis:

The build failure message came out after https://github.com/primefaces/primefaces/commit/b64e8cce5d4015c20f9a5fa1560c5ffc7b522743

`update rome tools to 1.9.0 - tested`

After reverted the fix back to 1.7.3. The build will be succeed for sure.

As a proof, checkout https://github.com/primefaces/primefaces/commit/b64e8cce5d4015c20f9a5fa1560c5ffc7b522743 and change the rome version back to 1.7.3

![image](https://user-images.githubusercontent.com/10467831/42041528-b64538b4-7ab7-11e8-8a9f-29ada6c2e6bb.png)
The error will go away immediately

and 
```
[INFO] --------------
[INFO] BUILD SUCCESS
```

@cnsgithub 
 
Could you please elaborate on this one since the upgrade is breaking the build on Windows AFAIC.

**Comment by melloware** [comment]
Hmm I can't reproduce on windows.  Here is what my mvn --version says.
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: C:\Tools\apache-maven-3.5.0
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_111\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by tandraschko** [comment]
Check your maven repo, our builds are also fine.

**Comment by jxmai** [comment]
Alright. Thanks for your elaboration ! Since there is no such issue on your environment, so I just close it for now and do more verification and troubleshoot...

**Comment by cnsgithub** [comment]
@jxmai Guess you're using JDK >= 9? That's not clear from your screenshot. @melloware is using JDK 8 and it doesn't seem to appear. Probably it has something to do with modularization, see https://github.com/rometools/rome/issues/374

**Comment by jxmai** [comment]
Thanks for pointing that out. I went back and double-checked the settings (reconfigured JAVA_HOME and MAVEN_HOME etc) but the problem still exists on one particular system (just leave it for now at this point :) )... It should be a local issue so no worry about it.

JFYI:

```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T13:33:14-05:00)
Maven home: D:\Program Files\apache-maven-3.5.4
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: D:\Program Files\Java\jdk1.8.0_172\jre
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```
