### ISSUE TITLE
SelectManyMenu: new option for selecting all shown items when filter is updated

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#3830]
In my use case there is huge list of versions (xx.xx.xx), which can be filtered by some prefix (e.g. 4.2) and from the rest only few version are skipped. 

Currently it is not possible to select all shown items after updating the filter value. So instead of deselecting few items user has to select almost entire list.

This new option could be tightly related to the filter function. If the particular item matches the filter and is to be shown, it would be automatically selected.

**Comment by melloware** [comment]
@jan-tosovsky-cz Isn't this a duplicate of your other ticket: https://github.com/primefaces/primefaces/issues/3992

**Comment by jan-tosovsky-cz** [comment]
you are right, the other issue is another approach to achieve same behaviour
