### ISSUE TITLE
FileUpload: Updating the parent of a dialog with a fileUpload element causes the fileUpload's "Choose" button to open two file chooser dialogs

### ISSUE THREAD

**Issue by Njol** [primefaces/primefaces#3841]
## 1) Environment
- PrimeFaces version: **6.2.6**
- Does it work on the newest released PrimeFaces version? Version? **no** (6.2.6)
- Does it work on the newest sources in GitHub? **untested**
- Application server + version: **Jetty 9.2.24**
- Affected browsers: **at least Firefox and Internet Explorer**

## 2) Expected behavior
Upon clicking on the "Choose" button of a `<p:fileUpload>` element, only one file chooser dialog should open.

## 3) Actual behavior
Two file chooser dialogs open from a single button press.

## 4) Steps to reproduce
Update a parent element of a `<p:dialog>` that contains a `<p:fileUpload>` element, then click on the "Choose" button of the fileUpload.

## 5) Sample XHTML
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:p="http://primefaces.org/ui">
	<h:head>
	</h:head>
	<body>
		<h:form>
			<p:commandButton value="show dialog" oncomplete="PF('dialogWidgetVar').show();" update="dialogWrapper" process="@this" />
		</h:form>
		<p:outputPanel id="dialogWrapper">
			<p:dialog widgetVar="dialogWidgetVar" visible="false" modal="true" appendTo="@(body)">
				<h:form enctype="multipart/form-data">
					<p:fileUpload widgetVar="fileUploadWidgetVar" mode="advanced" fileLimit="0" />
					<p:commandButton value="close dialog" oncomplete="PF('dialogWidgetVar').hide();" update="@none" partialSubmit="true" process="@none" />
				</h:form>
			</p:dialog>
		</p:outputPanel>
	</body>
</html>
```

To test: click "show dialog", then click "Choose". Two file chooser dialogs will open.

## 6) Sample bean
No bean involved.

## 7) Notes

- We cannot simply update the dialog itself instead of a parent (which prevents this issue), as there are nested dialogs involved.

- This worked fine in version 5.2.23, and only caused issues after upgrading to version 6.2.6.

- For now, we work around this issue by removing all but the first element from the arrays in the fileUpload's widgetVar when the dialog containing it is shown. This is because each array gets a second element when the dialog is updated (which is equal to the first element in the array). Maybe this could help fix this issue?

**Comment by tandraschko** [comment]
works fine for me with master
