### ISSUE TITLE
PickList: long items not fully highligted.

### ISSUE THREAD

**Issue by Dasister** [primefaces/primefaces#3846]
## 1) Environment
- PrimeFaces version: **6.1**
- Does it work on the newest released PrimeFaces version? Version? **No.**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source): **No.**
- Application server + version: **WildFly 10.1**
- Affected browsers: **Chrome, FF, Edge**

## 2) Expected behavior

Long items should be fully highlighted.

## 3) Actual behavior

An item that does not fit into the container is not fully highlighted.

![image](https://user-images.githubusercontent.com/1691753/42230961-eaef4ec6-7ef2-11e8-9333-d3a6d239f75b.png)

## 4) Steps to reproduce

Place <p:pickList>, insert item which is wider than list container, select this item and scroll to the side.

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
	  xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:p="http://primefaces.org/ui"
	  xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>
	<p:pickList value="#{testView.testList}" var="cities" itemLabel="#{cities}" itemValue="#{cities}" />
</h:body>
</html>
```

## 6) Sample bean

```
package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.model.DualListModel;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
    private DualListModel<String> testList;

    @PostConstruct
    public void init() {
        List<String> citiesSource = new ArrayList<String>();
        List<String> citiesTarget = new ArrayList<String>();

        citiesSource.add("Test1");
        citiesSource.add("Test2");
        citiesSource.add("Test3");
        citiesSource.add("Not so long");
        citiesSource.add("Looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong");

        testList = new DualListModel<>(citiesSource, citiesTarget);
    }

    public DualListModel<String> getTestList() {
        return testList;
    }

    public void setTestList(DualListModel<String> testList) {
        this.testList = testList;
    }
}
```

**Comment by melloware** [comment]
You can fix this by changing the width of the picklist items in your application CSS to override the PF style.  The default of the picklist is 200px.
```css
.ui-picklist .ui-picklist-item {
    width: 1000px;
}
```
Here is a sample showing the issue just run "mvn clean jetty:run".  
[primefaces-test-3846.zip](https://github.com/primefaces/primefaces/files/2160222/primefaces-test-3846.zip)

**Comment by Dasister** [comment]
Yes, I can. But I don't know max possible width. 
And unused empty space sounds like something bad. So it's sounds like possible workaround (thank you for suggestion, by the way), not regular solution for me. Am I wrong?

**Comment by melloware** [comment]
No its a workaround if you knew roughly whats the max size of the item in your picklist.  I provided the sample project containing your demo in case any Dev's wanted a working proof to debug or find a fix.  Basically it needs some way of dynamically knowing the max text length of your items.

**Comment by mertsincan** [comment]
I think there are two solutions for this issue;
The first solution (it can be added to PF core);
```
body .ui-picklist .ui-picklist-list li {
    overflow-wrap: break-word;
}
```

The second solution (you can add it to your project);
```
body .ui-picklist .ui-picklist-list li {
   text-overflow: ellipsis;
   overflow: hidden;
   white-space: nowrap;
}
```

**Comment by tandraschko** [comment]
so let's add 1) to PF?

**Comment by melloware** [comment]
I vote for 1)

**Comment by mertsincan** [comment]
Thanks, @tandraschko and @melloware ;)
