### ISSUE TITLE
DataTable: weird behavior with filtering and sticky header 

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#3847]
If you have a sticky header enabled, the header will be cloned in the DOM.
Therefore the filter inputs will be cloned, too.

What happens now? If you change a filter in the sticky header, the value won't be copied to the normal, uncloned/unsticky, header.

**Comment by Rapster** [comment]
From what I can see now, if you set a `stickyHeader` you can't change filter values as they're disabled (I have the same problem in 6.2)

EDIT: Ah I see, they're enabled once the stickyHeader shows up (but disabled if not)

**Comment by melloware** [comment]
@tandraschko @Rapster i just tested this in 13.0.4 and the filters seem to be working fine in Sticky Header?

With stick header I set to Canada and Anna Fali.

![image](https://github.com/primefaces/primefaces/assets/4399574/eb03924e-0522-4b0b-9a3e-4c4d507f3f58)


When its unsticky the regular filters still contain these values.

![image](https://github.com/primefaces/primefaces/assets/4399574/7249096e-a83e-43f0-b8e0-9dd86f294b06)
