### ISSUE TITLE
ContentFlow with two images 

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#3848]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? n/a
- Application server + version: WF 10.0.0
- Affected browsers: Chrome/Edge/Firefox

## 2) Expected behavior
One can switch between the two images in the carousel

## 3) Actual behavior
One can see only one image; one cannot switch to the second one

## 4) Steps to reproduce
just open the page

## 5) Sample XHTML
```
<p:contentFlow value="#{imagesView.images}" var="image">
    <p:graphicImage name="demo/images/nature/#{image}" styleClass="content" />
    <div class="caption">#{image}</div>
</p:contentFlow>
```

## 6) Sample bean

```
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

@ManagedBean
public class ImagesView {

  private List<String> images;

  @PostConstruct
  public void init() {
    images = new ArrayList<String>();
    for (int i = 1; i <= 2; i++) {
      images.add("nature" + i + ".jpg");
    }
  }

  public List<String> getImages() {
    return images;
  }
}

```

**Comment by melloware** [comment]
Issued was reported on the old Google Code page and fix was provided: https://github.com/orhan27799/contentflow/issues/20
