### ISSUE TITLE
p:selectManyButton

### ISSUE THREAD

**Issue by SergeyLyashenko** [primefaces/primefaces#3849]
# <p:selectManyButton> with <p:ajax> doesn't work correct 

I use primefaces 6.2

``` xhtml
<p:selectManyButton id="filter" .....>
     <f:selectItems
          ........./>
     <p:ajax event="change" process="@this" update="table"/>
</p:selectManyButton>
```
code above rendered to

``` html
<div id="form:table:filter"
   class="ui-selectmanybutton ui-buttonset ui-widget ui-corner-all ui-buttonset-6">
   <div class="ui-button ui-widget ui-state-default ui-button-text-only ui-corner-left">
      <input
         id="form:table:filter:0" 
         name="form:table:filter"
         type="checkbox" value="MANUAL" class="ui-helper-hidden-accessible"
         onchange="PrimeFaces.ab({s:&quot;form:table:filter&quot;
                                 ,e:&quot;change&quot;
                                 ,p:&quot;form:table:filter&quot;
                                 ,u:&quot;form:table:filter&quot;});"/>
      <span class="ui-button-text ui-c">MANUAL</span>        
   </div>
   ....
</div>
```
Function `PrimeFaces.ab()` called from `<input>` so ajax works before `PrimeFaces.widget.SelectManyButton`. In this situation ajax send duplicate, can't unselect filters and works incorrect. Without `<p:ajax>` all work fine, but I need it.
I compared with `p:selectCheckboxMenu` and there is no `PrimeFaces.ab()` in `<input>` tag, ajax is called from `PrimeFaces.widget.SelectCheckboxMenu` all works fine.
I read about it in another issues. It should have been fixed in 5.3.x version, but still no.
 How can I fix this?? Can I override PrimeFaces.widget.SelectManyButton to fix it or something else?

**Comment by tandraschko** [comment]
Questions -> Forum.
Issues must follow the issue template.
