### ISSUE TITLE
MOVE_SCRIPTS_TO_BOTTOM combines non javascript

### ISSUE THREAD

**Issue by mulkgun** [primefaces/primefaces#3854]
In my project I have Web GL script<script type="x-shader/x-vertex"> and <script type="x-shader/x-fragment"> MOVE_SCRIPTS_TO_BOTTOM combines them into javascript block. I think it should group them by their type.

**Comment by cnsgithub** [comment]
Might be a good point, but please use the issue template, otherwise chance is low that someone will hear you.

**Comment by tandraschko** [comment]
Not sure If this is required as they are just collected by order. So you can just group them by yourself.

**Comment by cnsgithub** [comment]
```html
<script type="text/javascript">
   console.log('foo');
</script>
PAGE CONTENT
<script type="x-shader/x-vertex">
   //non-javascript code
</script>
```

Will be transformed to 

```html
PAGE CONTENT
<script>
   console.log('foo');
   //non-javascript code
</script>
```

or

```html
PAGE CONTENT
<script type="text/javascript">
   console.log('foo');
</script>
<script type="x-shader/x-vertex">
   //non-javascript code
</script>
```

?

**Comment by cnsgithub** [comment]
Just tried it, the answer is that it results in

```html
PAGE CONTENT
<script type="text/javascript">
   console.log('foo');
   //non-javascript code
</script>
```
which is of course incorrect.

**Comment by tandraschko** [comment]
should we even touch them?

**Comment by cnsgithub** [comment]
I would consequently do so. 

But I am not sure how we can do this in `MoveScriptToBottomResponseWriter` since it's a bit complex. @tandraschko You wrote it?

**Comment by tandraschko** [comment]
yup

**Comment by cnsgithub** [comment]
Btw, there might be other attributes for the `script `tag that must be taken into account, e.g. `async`, `defer`, `nonce`...

And can we turn `"script".equals` into `"script".equalsIgnoreCase`?

**Comment by tandraschko** [comment]
not sure if we should take care of every case, it's makes to code probably to complex.

**Comment by cnsgithub** [comment]
We could just check for attributes besides `type` and if so exclude them from being combined?

**Comment by tandraschko** [comment]
I think also merging them is no problem. But adding support for async, defer, nonce, etc. seems quite complex.
Is it always correct to render all scripts merged in following order:
1) javascript
2) x-shader/x-vertex
3) x-shader/x-fragment

i wonder if its sometimes required that a fragment must be placed before vertex and vice versa.
Maybe it's the best ways to only merge javascripts, and just move all other scripts tags after the merged javascripts.

**Comment by cnsgithub** [comment]
I wouldn't try to change the order at all.

**Comment by tandraschko** [comment]
If someone could write some unittests for the currenct implementation, it would be great.
I will do changes itself before 6.3.

**Comment by cnsgithub** [comment]
@tandraschko Hope that helps: https://github.com/primefaces/primefaces/pull/3872
