### ISSUE TITLE
DataTable: RowGroup do not work correctly with lazy loading 

### ISSUE THREAD

**Issue by floriandulzky** [primefaces/primefaces#3856]
## 1) Environment
- PrimeFaces version: 6.1 / 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: jetty / wildfly 11
- Affected browsers: tested in chrome and FF

## 2) Expected behavior
I have a scrollable datatable with lazy loading and RowGroup implemented.
Initial every rows are grouped correctly.

## 3) Actual behavior
After reloading some data, row grouping do not work correctly.

## 4) Steps to reproduce
scroll the datatable and reload some data.

## 5) Sample 
I have commited an example to reproduce the issue:

https://github.com/floriandulzky/primefaces-test

http://localhost:8080/primefaces-test/testTableRowGroup.xhtml

**Comment by melloware** [comment]
Added documentation warning that RowGroup and Lazy are not compatible features:

> Row Grouping does not work with Lazy loading or LiveScroll as the grouping needs to know about all rows to properly 
> group the rows.
