### ISSUE TITLE
DataExporter: datatable with skipChildren is not working

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3857]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 7
- Affected browsers: All

## 2) Expected behavior
Using that example with Datatable#skipChildren="true" should export content into any supported export file. As the datatable does not contain any inputs, skipChildren make sense. 

## 3) Actual behavior
Content is not exported

## 4) Steps to reproduce
https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml
Set Datatable#skipChildren="true"

## 5) Sample XHTML
See showcase

## 6) Suggestions
In my use case, every columns contains a bunch of infos contained in a `pe:dynaForm` so it makes even more sense to use that attribute. Though, using that flag prevents the use of `p:dataExporter`. Having buttons in paginator works though.

See this code:
```java
    protected void processPhase(FacesContext context, PhaseId phaseId) {
        if (shouldSkipChildren(context)) {
            return;
        }

        setRowIndex(-1);
        processFacets(context, phaseId);
        if (requiresColumns()) {
            processColumnFacets(context, phaseId);
        }
        processChildren(context, phaseId);
        setRowIndex(-1);
    }
```

Do you think, it'd be possible to call UIData#shouldSkipChildren after processing facets? I don't think performance will be affected postponing that call

**Comment by Rapster** [comment]
I had a try using this impl:
```java
    @Override
    protected void processPhase(FacesContext context, PhaseId phaseId) {
        setRowIndex(-1);
        processFacets(context, phaseId);

        if (shouldSkipChildren(context)) {
            return;
        }

        if (requiresColumns()) {
            processColumnFacets(context, phaseId);
        }
        processChildren(context, phaseId);
        setRowIndex(-1);
    }
```

Works fine so far. I'll do more tests before comitting a fix. I even wonder if we shouldn't skip children right before calling `processChildren`

**Comment by Rapster** [comment]
After taking measures, we realized that, with or without skipChildren, does not change anything in terms of traversal speed. If I had to commit something, I would skip children right before calling `processChildren`. WDYT?

**Comment by melloware** [comment]
@Rapster any more on this issue?

**Comment by Rapster** [comment]
I created a PR I let @tandraschko decides whether it should be in this release or not
