### ISSUE TITLE
Layout: Nested layout problem

### ISSUE THREAD

**Issue by Charlie243** [primefaces/primefaces#3858]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? No Version? 6.2.6
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 8.0.15
- Affected browsers: IE 

## 2) Expected behavior
All defined layoutUnits will be displayed.
...

## 3) Actual behavior
The nested "North West" layoutUnit is not displayed. See the forum discussion here:

[https://forum.primefaces.org/viewtopic.php?f=3&t=56206](url)
..

## 4) Steps to reproduce
Just run the XHTML example below.

## 5) Sample XHTML

`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    
    <h:head>
        <title>Layout Test</title>
    </h:head>
    <h:body>
        <p:layout 
            id="mainlayout"
            fullPage="true">

            <p:layoutUnit 
                id="top" 
                position="north" 
                size="80" 
                resizable="true">
                Top
            </p:layoutUnit>

            <p:layoutUnit 
                position="center" 
                resizable="true">
                Center		
            </p:layoutUnit>

            <p:layoutUnit 
                position="west" 
                size="360" 
                resizable="true">

                <p:layout >
                    <p:layoutUnit 
                        position="north" 
                        size="170" 
                        resizable="true">
                        North West
                    </p:layoutUnit>

                    <p:layoutUnit 
                        position="center">
                        Center West
                    </p:layoutUnit>
                </p:layout> 
                
            </p:layoutUnit>
        </p:layout>		
    </h:body>
</html>
`
..

## 6) Sample bean
No  bean is required.
..

**Comment by melloware** [comment]
I will investigate and see if I can see what's going on.

**Comment by melloware** [comment]
Attached is a test case: 
[primefaces-3858.zip](https://github.com/primefaces/primefaces/files/2175916/primefaces-3858.zip)

Just run "mvn clean jetty:run" and navigate to http://localhost:8080/primefaces-test/test.xhtml

1. If I set the pom.xml to PF 6.2 the North West unit looks fine.

2. If I set the pom.xml to 6.3.-SNAPSHOT the North West Unit does not appear so something broke after the release of 6.2  I will see if I can figure out what changed.

**Comment by melloware** [comment]
OK so the only real layout issue that has been merged into Elite releases is this one:  https://github.com/primefaces/primefaces/issues/3457

And that fixed that issue but its possible it somehow introduced this new issue.  I just can't see how.

**Comment by Charlie243** [comment]
Melloware,

I checked again on when this bug appeared in the PF releases and, you're right, in the original 6.2 community release the North West unit looks fine.  It's only in the 6.2.1 Elite release that the North West unit fails to appear.  And the latest 6.2.6 Elite release still exhibits this bug.  So the bug appeared between the 6.2 and 6.2.1 releases.

I also checked on the affected browsers.  I can confirm that the bug appears in IE, Chrome and Firefox.

Finally, the link back to the forum topic in my original post above had a formatting problem.  Here's the URL again:

https://forum.primefaces.org/viewtopic.php?f=3&t=56206

Again, thanks for investigating this!

**Comment by melloware** [comment]
Yep than fix #3457  is definitely the issue but I needed to make that fix to solve another issue.  https://github.com/primefaces/primefaces/issues/3457 .  Have to think about how I can fix both.

**Comment by melloware** [comment]
OK not great but attached is a sample that makes it work. 
[primefaces-3858-fix.zip](https://github.com/primefaces/primefaces/files/2192833/primefaces-3858-fix.zip)

Basically all I added was a widget call to show the NorthWest panel when the page is ready.

```javascript
<script>
$( document ).ready(function() {
    PF('widgetWestLayout').show('north');
});
</script>
```

**Comment by Charlie243** [comment]
Melloware,

Thanks for the workaround!  I hope a fix to PF itself can be done at some point.

I've used this exact layout configuration with PF since version 3.1 and never had a problem with it before.  Was there some major change to the PF 6 codebase that makes the layout component difficult to support in the most recent PF versions?  Is that why layout is deprecated in PF 6?

Also, will PF Extensions continue to support layout -- or is the plan to deprecate it there too?

Thanks for any info you can supply,
Charlie

**Comment by melloware** [comment]
Charlie,

1. The big change was moving from Jquery 1 to Jquery 3 for all the security fixes caused us to have to upgrade the Jquery Layout component which hadn't been updated in 6 years.  

2. PrimeTek has deemed the Layout not needed and you should just use Responsive CSS for your layouts instead of the component so that I believe is why they are deprecating it (Note: I don't work for PrimeTek)

3. Yes, PrimeFaces Extensions will continue to support the Layout component!

**Comment by Charlie243** [comment]
Melloware,

Thanks for the info.  It's very helpful.  

I know the Layout component is considered "old-fashioned" but it suits my needs perfectly -- and I'd rather not go to the work of replacing something that's working fine for me right now.  My guess is that there are other PF users who are in the same situation and will not be happy when they discover Layout is deprecated.

Anyway, I'm very glad to hear that PrimeFaces Extensions will continue to support Layout.  I'm downloading PF Extensions right now and will be trying it out in my application as soon as I get a chance.

Thanks again for all your help!
Charlie

**Comment by melloware** [comment]
Yep I use it too but I use the Extensions version.  It suits my needs as well.

**Comment by tandraschko** [comment]
Will close it as deprecated
