### ISSUE TITLE
selectOneMenu: appearing 2 places in 6.3-SNAPSHOT

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#3860]
## 1) Environment
- PrimeFaces version: 6.3-SNAPHOT
- Does it work on the newest released PrimeFaces version? Version? yes
- Does it work on the newest sources in GitHub? no
- Application server + version: wildfly
- Affected browsers: all

## 2) Expected behavior

should appear only one place

## 3) Actual behavior

appearing in 2 places

## 4) Steps to reproduce

click on button 1
click on button 2
click on first selectOneMenu

## 5) Sample
https://github.com/erickdeoliveiraleal/primefaces-test/tree/bugSelectOne

[primefaces-test-bugSelectOne.zip](https://github.com/primefaces/primefaces/files/2176652/primefaces-test-bugSelectOne.zip)

**Comment by tandraschko** [comment]
works just fine for me.

**Comment by erickdeoliveiraleal** [comment]
Did you first click on button 1 and after 2, and opened selectOneMenu? I  tested in chrome and edge, and the deffect is there using the sample I sent.
![imagem 1](https://user-images.githubusercontent.com/3578953/42458794-d6cd8f48-8370-11e8-9bc3-c14c778bf2c8.png)

**Comment by tandraschko** [comment]
the first selectOneMenu works fine, as stated in your description ;) :P

**Comment by erickdeoliveiraleal** [comment]
the bug only appear after using PrimeFaces.current().dialog().closeDynamic(i);

**Comment by tandraschko** [comment]
I really don't know why this bug happens but #3788 would actually solve exactly this problem.
Could you please also provide the sample for #3788 again?

**Comment by erickdeoliveiraleal** [comment]
I deleted the sample. But I believe it was a simple cascaded selectOneMenu

**Comment by tandraschko** [comment]
Commited a fix. Please please test again the other cases!

And next time it would be great for simples issues like 3788, if you can post the sample in the issue directly, too.

**Comment by erickdeoliveiraleal** [comment]
thanks, tested some pages and it looks ok..
