### ISSUE TITLE
SelectOneMenu: AJAX forces Edge to jump to top of page

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#3863]
## 1) Environment
- PrimeFaces version: **6.1**
- Does it work on the newest released PrimeFaces version? Version? **No. 6.2**
- Does it work on the newest sources in GitHub? **No**
- Application server + version: **WildFly 10.1.0.Final**
- Affected browsers: **Microsoft Edge 42.17134.1.0**

## 2) Expected behavior

Scroll position of page should not vary after selection with AJAX enabled SelectOneMenu.

## 3) Actual behavior

Microsoft Edge jumps to top of page after selection with AJAX enabled SelectOneMenu (standard JSF SelectOneMenu does not).

## 4) Steps to reproduce

Select item with AJAX enabled SelectOneMenu. 

## 5) Sample XHTML

```
<!DOCTYPE html>
<html
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:p="http://primefaces.org/ui"
>
<f:view>
  <h:head></h:head>
  <h:body>
    <h:form id="form">
      <p:outputPanel id="container">
        <p:spacer height="1000"></p:spacer>
        <br />
        <h:selectOneMenu
          id="dropdown_h"
          value="#{dropdownController.value}"
        >
          <f:ajax
            execute="dropdown_h"
            render="container"
          >
          </f:ajax>
          <f:selectItems
            value="#{dropdownController.options}"
            var="option"
            itemLabel="#{option}"
            itemValue="#{option}"
          />
        </h:selectOneMenu>
        <br />
        <p:selectOneMenu
          id="dropdown_p"
          value="#{dropdownController.value}"
        >
          <p:ajax
            process="dropdown_p"
            update="container"
          >
          </p:ajax>
          <f:selectItems
            value="#{dropdownController.options}"
            var="option"
            itemLabel="#{option}"
            itemValue="#{option}"
          />
        </p:selectOneMenu>
        <br />
        <p:spacer height="1000"></p:spacer>
      </p:outputPanel>
    </h:form>
  </h:body>
</f:view>
</html>
```

## 6) Sample bean

```
package org.primfaces.issue;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class DropdownController implements Serializable {

  private static final long serialVersionUID = -6991892064093740746L;

  private String value;

  private List<String> options;

  @PostConstruct
  public void initialize() {
    options = Arrays.asList("1", "2");
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public List<String> getOptions() {
    return options;
  }

  public void setOptions(List<String> options) {
    this.options = options;
  }
}
```

**Comment by tandraschko** [comment]
deeper analysis and/or PR welcome

**Comment by irieill** [comment]
Put a lot of effort in debugging PrimeFaces JS. But so far i am not able to figure out what is the problem. There is one more thing to mention: Selecting the JSF SelectOneMenu after selecting the PrimeFaces SelectOneMenu in the given example, results in the same effect. But only once!

**Comment by melloware** [comment]
@irieill I was just looking forward to the days of never having IE workarounds again so I really hope this is an MS Edge bug and not something we need to begin the era of if (PrimeFaces.isMsEdge()) {...do hack}  :) :) :)

**Comment by Rkhiter** [comment]
Primefaces 6.2.11
you can produce this  by add attribut styleClass selectCheckboxMenu is not working with Edge.
it works well with Firefox and Chrome.
I just tested it with example showCase primefaces just add styleclass.
if you remove styleClass it works well if you add attribut styleClass is not working  with Edge

**Comment by melloware** [comment]
Created a reproducible test case:  
[pf-3863.zip](https://github.com/primefaces/primefaces/files/2653051/pf-3863.zip)

This seems to be a common problem in Edge. https://answers.microsoft.com/en-us/edge/forum/all/microsoft-edge-keeps-jumping-to-top-of-page-after/c9b5d3bb-c01f-4b98-b39f-8dc2de5597ab

**Comment by tandraschko** [comment]
we have the same problem in our applications but didn't find the reason after ~1 hour search

**Comment by melloware** [comment]
Good news is it loos like Microsoft is already abandoning Edge: https://www.criticalhit.net/technology/microsoft-abandoning-edge-building-new-web-browser-based-chromium/

**Comment by tandraschko** [comment]
in generell i dont think that this are good news for the whole ecosystem :P But good for our bugs here, yes...

**Comment by melloware** [comment]
Still happening in Edge 18362 which is the latest version in the latest Windows 10 patch.

**Comment by tandraschko** [comment]
@melloware could you retest with the newest version?

**Comment by melloware** [comment]
Here is the latest version of Edge I have on Windows 10 and its still happening.
```
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362
```

**Comment by melloware** [comment]
Confirmed this is no longer an issue with Version 83.0.478.37 (Official build) (64-bit) of Edge.
