### ISSUE TITLE
Datatable: toggleSelect not updating datatable component

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3864]
## 1) Environment
- PrimeFaces version: 6.2.5 NOT working, 6.2.4 works
- Does it work on the newest released PrimeFaces version? Version? 6.2.6 no
- Application server + version: jetty
- Affected browsers: all

## 2) Expected behavior
On PF **6.2.4** the datatable gets updated on "toggleSelect" event and the example "Action" button (placed in table header) is enabled/disabled regarding any row is selected. I used "rowSelectCheckbox "and "rowUnselectCheckbox" events as well to demonstrate functionality.

## 3) Actual behavior
On PF **6.2.5** the datatable doesn't get updated on "toggleSelect" event and the example "Action" button is not updated. Events "rowSelectCheckbox "and "rowUnselectCheckbox" works as expected.
There are no HTML components updated in response from server on ajax request triggered by "toggleSelect".

Even when I change ajax to update specificaly the Action button:
`<p:ajax event="toggleSelect" update="@this @form:productTableId:actionBtn" global="false" ignoreAutoUpdate="true"/>`
the button does not get updated.

## 4) Steps to reproduce
Use cloned PF example on https://github.com/martin654/primefaces-test/tree/replicate/datatable_selectAll

Click on header checkbox to select all rows of table - "Action" button does not get visible. 
Use  checkbox in rows - they work as expected.
Change PF version to 6.2.4 - the select all checkbox enables/disables "Action" button.

## 5) Sample XHTML
See https://github.com/martin654/primefaces-test/blob/replicate/datatable_selectAll/src/main/webapp/test.xhtml
## 6) Sample bean
See https://github.com/martin654/primefaces-test/blob/replicate/datatable_selectAll/src/main/java/org/primefaces/test/TestViewCdi.java

**Comment by tandraschko** [comment]
@mertsincan Can you check this? worked in 6.2.4, broken in 6.2.5

**Comment by melloware** [comment]
Feels like it might be this fix that caused the regression: https://github.com/primefaces/primefaces/issues/3683

**Comment by mertsincan** [comment]
Hi @martin654,

I couldn't replicate this issue with 6.2.5 and 6.2.6. My test video; https://www.dropbox.com/s/geikjtraczudkv6/test.avi?dl=0

**Comment by martin654** [comment]
Hi @mertsincan,
that is not possible :) my colleague tried the reproducer too and the behavior is the same as reported :(
Could you please test it again, possibly try mvn clean install before mvn jetty:run-exploded ?

Thank you,
Martin

**Comment by pedrodelgado81** [comment]
I have the same behavior

Code sample:
```
<h:form>
<p:dataTable id="myList" var="_var" value="#{mybean.list}" selection="#{mybean.selectionlist}" rowKey="#{_var.code}">
	<p:ajax event="toggleSelect"  listener="#{mybean.action}/>
	<p:column selectionMode="multiple""/>
	<p:column>
		<h:outputText value="#{_var.title}" />
	</p:column>
</p:dataTable>
</h:form>
```
When I click in selectallCheckbox I've got this javascript error and no action launched:
```
core.js.seam?ln=primefaces&v=6.2.6:1 TypeError: Cannot read property 'split' of undefined
    at c.handle (components.js.seam?ln=primefaces&v=6.2.6:12)
    at Object.doUpdate (core.js.seam?ln=primefaces&v=6.2.6:3)
    at Object.handle (core.js.seam?ln=primefaces&v=6.2.6:3)
    at Object.onsuccess (components.js.seam?ln=primefaces&v=6.2.6:12)
    at Object.<anonymous> (core.js.seam?ln=primefaces&v=6.2.6:3)
    at i (jquery.js.seam?ln=primefaces&v=6.2.6:2)
    at Object.fireWith [as resolveWith] (jquery.js.seam?ln=primefaces&v=6.2.6:2)
    at A (jquery.js.seam?ln=primefaces&v=6.2.6:4)
    at XMLHttpRequest.<anonymous> (jquery.js.seam?ln=primefaces&v=6.2.6:4)
```

**Comment by martin654** [comment]
**Changed:** I see JS error in my case too. Original: I do not have any JS error in my case.
```
TypeError: Cannot read property 'split' of undefined
    at Class.handle (components.js:5072)
    at Object.doUpdate (core.js:1670)
    at Object.handle (core.js:1562)
    at Object.onsuccess (components.js:5068)
    at Object.<anonymous> (core.js:1418)
    at u (jquery.js?ln=primefaces&v=6.3-SNAPSHOT:2)
    at Object.fireWith [as resolveWith] (jquery.js?ln=primefaces&v=6.3-SNAPSHOT:2)
    at k (jquery.js?ln=primefaces&v=6.3-SNAPSHOT:2)
    at XMLHttpRequest.<anonymous> (jquery.js?ln=primefaces&v=6.3-SNAPSHOT:2)
```


The ajax request is processed by server, but nothing is upadetd (no DOM elements sent to client from server) no matter what I do.

I tried to add this line into TestViewCdi.fooAction() method:
`PrimeFaces.current().ajax().update("form");`
and the result is that the datatable disappears from page on "select all" click:

response:
```
<?xml version='1.0' encoding='utf-8'?>
<partial-response id="j_id1"><changes><update id="form"><![CDATA[
<form id="form" name="form" method="post" action="/primefaces-test/test.xhtml" enctype="application/x-www-form-urlencoded">
<input type="hidden" name="form" value="form" />
<span id="form:text">foooo</span>
</form>]]></update><update id="j_id1:javax.faces.ViewState:0"><![CDATA[3009900344694369360:7820167624380557155]]></update></changes></partial-response>
```

**Comment by martin654** [comment]
I just found out the difference between the two requests (6.2.4 vs 6.2.5) on toggle select:

The difference is in those two parameters are added to the request in the new version:
```
form:productTableId_encodeFeature: true
form:productTableId_skipChildren: true
```

I think this is related to issue: https://github.com/primefaces/primefaces/issues/3743
And it's changeset: https://github.com/primefaces/primefaces/commit/ad5ed51a2f391694427efa29306ae5aebd7fd342#diff-265f44d9cadc896ec3d21a3a721f15ddR2074
where those parameters are always set to "true".

**Comment by martin654** [comment]
I tried to compile from source for all commits related to DataTable in PF 6.2.5:

- https://github.com/primefaces/primefaces/issues/3584
- https://github.com/primefaces/primefaces/issues/3683
- **https://github.com/primefaces/primefaces/issues/3743**

And it stopped working in the **third** case with commit ID:  ad5ed51

To be sure I tried also "previous" commit to ad5ed51 and it works here. I am pretty sure the case of the problem is in commit ad5ed51.

**Comment by martin654** [comment]
@mertsincan could you please check again? thank you

**Comment by martin654** [comment]
I tried to revert changes only in Datatable.js made by the mentioned commit: ad5ed51 and it started to work again. I think the problem is, that the datatable is not encoded into response when using **encodeFeature=true** attribute.

As I can see in DataTableRenderer.encodeEnd method:
```
if (table.shouldEncodeFeature(context)) {
            for (Iterator<DataTableFeature> it = DataTable.FEATURES.values().iterator(); it.hasNext();) {
                DataTableFeature feature = it.next();

                if (feature.shouldEncode(context, table)) {
                    feature.encode(context, this, table);
                }
            }
        }
        else {
            preRender(context, table);

            encodeMarkup(context, table);
            encodeScript(context, table);
        }
```
the responsibilty to encode something is newly given to features in this type of request (toggleSelect event) - in this case SelectionFeature, which is programmed not to encode anything...

When I use toggling only in single row (rowSelectCheckbox event), the encodeFeature="true" is not used.

@mertsincan  Is it possible that you couldn't replicate this because the browser had some previous Datatable.js implementation cached?

**Comment by pneumcke** [comment]
I can confirm that the issue is still present in the current version 6.27.

**Comment by martin654** [comment]
I saw that no feature from DatatableFeatures handles encoding of header and footer. In my case the button I want to update depends on toggleling of the rows. It enables/disables "perform on all items selected" operation button. 

When using sorting or paging functions on datatable, the toggled rows remains toggled. They can be on different page, but it doesn't affect "perform on all items selected" operation button enabled/disabled state. 
Other situation is for example with adding rows, when added row could be pre-toggled and it could affect "perform on all items selected" operation button. 

**What is confusing for Primefaces user is that toggling single row (rowSelectCheckbox event or rowsSelect event) "repaints" whole table including header and footer, but toggling all rows (toggleSelect) doesn't.**

@mertsincan Would it be feasible to enable encoding capability for SelectionFeature and in int's implenentatuon update datatable header and footer? Does it make sence to you? 
Another option would be adding something like updateFacets="true" which would update header and footer facets in processing of "features".

**Comment by mertsincan** [comment]
Thanks a lot for the info, @martin654 ;) Reverted #3743 and #3751 on 6.2.8 and 6.3.

**Comment by martin654** [comment]
@mertsincan Hi, I tested 6.2.8 today and there is still one issue left.

In commit https://github.com/primefaces/primefaces/commit/ad5ed51a2f391694427efa29306ae5aebd7fd342 from issue https://github.com/primefaces/primefaces/issues/3743 there was made a change in SelectionFeature's decode method - lines added:
```
if (checked) {
  selection = "@all";
}
```
which wasn't reverted in your fix commit https://github.com/primefaces/primefaces/commit/05a280c4ce562a26b9e40af89ed426cb9229f13c.

This causes that toggleSelect (toggle all checkbox used) selects all rows in table (including **all pages** of table) and it **ignores disabledSelection** datatable attribute.

I think that original implementation was better. Only rows from _selection request attribute were used as "all selected" and disabled rows were ignored.
When no row was disabled, then all rows on page were selected. Other page's rows were untouched. User could go through pages and select rows on whole page using toggleSelect.

I think it stil belongs under this ticket, but I can create new one if needed.

Thank you for your help.

Martin

**Comment by mertsincan** [comment]
Hi @martin654, 
Thanks a lot for the update! Could you please create a new ticket for it?
Best Regards,

**Comment by martin654** [comment]
Hi @mertsincan, new ticket created - https://github.com/primefaces/primefaces/issues/3954

**Comment by mertsincan** [comment]
Thanks a lot, @martin654 ;)
