### ISSUE TITLE
Add filterMode attribute to Tree

### ISSUE THREAD

**Issue by eversnarf** [primefaces/primefaces#3866]
## 1) Environment
- PrimeFaces version: 6.2.6
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? Not tried
- Application server + version: Tomcat 8.5.20
- Affected browsers: Firefox, Chrome, Edge

## 2) Expected behavior
When using filtering on a `<p:tree>`, I expect the search to show all matching nodes.

## 3) Actual behavior
When both a parent and a child nodes match, only the parent node is shown.

## 4) Steps to reproduce
Here is a simple two-level tree:
![image](https://user-images.githubusercontent.com/5243336/42587444-092fb738-853b-11e8-99a7-d183f3c72d72.png)

If I start typing `nut` in the search box, I see the nodes `Capsule / Brazil nut`, `Fibrous drupe / Coconut`, `Fibrous drupe / Walnut` and top node `Nut` (so far so good) **but** not its child node `Hazelnut`.

![image](https://user-images.githubusercontent.com/5243336/42587888-613f205c-853c-11e8-81ab-3fb5e001e9b4.png)

Actually, `Nut / Hazelnut` is present in the tree but the `Nut` node is not expanded.
Worse: when you expand it, you see nodes that do not match the search, such as `Nut / Beech` and `Nut / Oak acorn`.

![image](https://user-images.githubusercontent.com/5243336/42587960-99a8f27e-853c-11e8-8539-df6ce41d8c2c.png)

**It actually looks like the filter stops processing child nodes after finding a match.**

## 5) Sample XHTML
```xml
<p:tree value="#{treeBean.root}" var="node" filterBy="#{node}">
    <p:treeNode>
        <h:outputText value="#{node}"/>
    </p:treeNode>
</p:tree>
```

## 6) Sample bean
```java
public class TreeBean {

    private TreeNode root;

    public TreeBean() {
        this.root = new DefaultTreeNode();
        this.root.getChildren().add(buildNode("Achene", "Strawberry"));
        this.root.getChildren().add(buildNode("Capsule", "Brazil nut"));
        this.root.getChildren().add(buildNode("Fibrous drupe", "Coconut", "Walnut"));
        this.root.getChildren().add(buildNode("Legume", "Bean", "Pea", "Peanut"));
        this.root.getChildren().add(buildNode("Nut", "Beech", "Hazelnut", "Oak acorn"));
        this.root.getChildren().add(buildNode("Berry", "Cranberry", "Gooseberry", "Redcurrant", "Tomato"));
        this.root.getChildren().add(buildNode("Drupe", "Apricot", "Cherry", "Olive", "Peach", "Plum"));
    }

    private TreeNode buildNode(String nodeName, String... childrenNames) {
        TreeNode node = new DefaultTreeNode(nodeName);
        for (String childName : childrenNames) {
            node.getChildren().add(new DefaultTreeNode(childName));
        }
        return node;
    }

    public TreeNode getRoot() {
        return root;
    }
}
```

**Comment by Rapster** [comment]
If I'm not mistaken, there is a `filterMatchMode` and by default it's `startsWith`, which would explain your problem

**Comment by eversnarf** [comment]
Sorry, my sample xhtml was not complete, I did specify ` filterMatchMode="contains"` (otherwise it would not return `Brazil nut`, `Coconut`, etc).

```xml
<p:tree value="#{treeBean.root}" var="node" filterBy="#{node}" filterMatchMode="contains">
    <p:treeNode>
        <h:outputText value="#{node}"/>
    </p:treeNode>
</p:tree>
```

**Comment by mertsincan** [comment]
Added filterMode attribute. Valid values are 'exact'(default) and 'contains'. You can use filterMode="contains" for this issue.

**Comment by Rapster** [comment]
@mertsincan What's the diference between filterMode and filterMatchMode?

filterMatchMode: Match mode for filtering
filterMode: Mode for filtering valid values are exact (default) and contains

Please update descriptions to make it more understandable, is this new `filterMode` really necessary?

**Comment by eversnarf** [comment]
@mertsincan I don't think the issue is the type of match but the fact that any matching children are not shown if their parent is already a match.

**Comment by mertsincan** [comment]
> is this new filterMode really necessary?

Yes. FilterMatchMode="..." checks node's text according to its values such as contains, startsWith etc.
filterMode has two values; exact and contains
When using filtering on a tree,
- exact ->If the filtered value matches a node's text, this mode receives the node with the node's children and displays them in the tree. In short, this mode doesn't control node's children. The node is sufficient to match.
- contains -> this mode controls all nodes. It only shows all matches in the tree. If a node matches, but its children do not match, children are not displayed in the tree.

@f-r-a-n-s, please try filterMode="contains" with 6.2.13 release for your issue.
@f-r-a-n-s comment;
>It actually looks like the filter stops processing child nodes after finding a match.

This is a default behavior.(filterMode="exact")

In your case;
Filtered value: **nut**
- exact ->
 **Nut** / _Beech - Hazelnut - Oak acorn_
- contains ->
 **Nut** / _Hazelnut_

**Comment by Rapster** [comment]
Okay I get it now. I think we should rename these options though:

- lenient: your definition of exact
- strict: your definition of contains

**Comment by Rapster** [comment]
@mertsincan please consider my previous comment, otherwise I can do it. As I said, both attributes sounds like already the same, and values are more or less the same: it makes even more confusing. So renaming would be a big help

**Comment by mertsincan** [comment]
Thanks a lot for the feedback, @Rapster ;) We decided these options with @cagataycivici. For me, your options are OK :) @cagataycivici WDYT?

**Comment by Rapster** [comment]
Mert, don't forget to create a ticket to add this new attribute in the documentation 😉 BTW, do you have any clue if it would be possible to make the documentation open source? It would save a lot of effort to whoever is taking care of this

**Comment by cagataycivici** [comment]
I'll be very happy if the odt doc can be ported to something modern like markdown. See;
https://github.com/primefaces/primefaces/issues/4332

**Comment by cagataycivici** [comment]
lenient and strict would be fine, why naming things are so hard?

**Comment by eversnarf** [comment]
Sorry for late reply. The fix correctly filters the children now. Thanks for that.
However the problem is only half-fixed in my case as the parent node is not expanded:

>Actually, `Nut / Hazelnut` is present in the tree but the `Nut` node is not expanded.

This problem is still there. Should I open a separate issue for it?
