### ISSUE TITLE
Calendar: Popup on dialog with wrong position

### ISSUE THREAD

**Issue by Kamark** [primefaces/primefaces#3868]
1) Environment
- PrimeFaces version: PrimeFaces-6.2.6
- Application server + version: Primefaces Showcase
- Affected browsers: Chrome, Firefox 

2) Expected behaviour
Correct position of the popup calendar when browser is zoomed in or out

3) Actual behaviour
When a p:calendar component is placed inside a p:dialog the popup shows in a wrong position when this 2 conditions are met:
- Page is zoomed in or out
- Page is scrolled down

This can be tested on the p:schedule showcase 
https://www.primefaces.org/showcase/ui/data/schedule.xhtml
Clicking in a date shows a dialog with this behaviour

4) Steps to reproduce
- Go to: https://www.primefaces.org/showcase/ui/data/schedule.xhtml
- Zoom to 90% (AFAIK this happens with any percentage)
- Scroll down a little
- Click on a date to open the new event dialog
- Click on the calendar component to bring up the popup

**Comment by wsaca** [comment]
This problem is present due to a miscalculation of the panel position in the jquery datepicker component used by primefaces. When some parent tag has a fixed position, the datepicker panel is placed incorrectly because it's not ignoring the window scrollTop/scrollLeft.

**Comment by tandraschko** [comment]
Thanks @wsaca

**Comment by christophstocker** [comment]
@tandraschko 
@wsaca 

The problem still persist for IE11 and Edge.

- Go to: [Showcase schedule](https://www.primefaces.org/showcase/ui/data/schedule.xhtml)
- Scroll down a litte bit
- Open a day in "**Editable Schedule**"
- Click in the input for "**From**" or "**To**"
- The calendar popup is at the wrong position (only for IE11 and Edge)

**Comment by huinazhu** [comment]
we have the same problem hier, also occurred in Chrome and so on.

1. Environment
PrimeFaces version: PrimeFaces-6.2.26
Affected browsers: Chrome, Firefox

2. Expected behaviour
Correct position of the popup calendar when browser is zoomed in or out

3. Actual behaviour
When a p:calendar component is placed inside a p:dialog the popup shows in a wrong position when this 2 conditions are met:

Page is zoomed in or out
Page is scrolled down
