### ISSUE TITLE
DataTable's emptyMessage and colspan

### ISSUE THREAD

**Issue by jrodalo** [primefaces/primefaces#387]
The &lt;td&gt; created for the emptyMessage it's not aware of the colspan attribute. For example, with this code:

``` xml
<p:dataTable emptyMessage="I should have a colspan=3">
    <p:columnGroup type="header">
        <p:row>
            <p:column headerText="1" />
            <p:column headerText="2" />
            <p:column headerText="3" />
        </p:row>
    </p:columnGroup>
    <p:column colspan="2" />
    <p:column />
</p:dataTable>
```

I expect that emptyMessage's td had a colspan of 3 (2 of the first column and 1 of the second column).

DataTableRenderer.java (line 833)

``` java
writer.writeAttribute("colspan", table.getColumnsCount(), null);
```

Edit:
PrimeFaces 5.2

**Comment by kukel** [comment]
PF version? and you may provide a pull request

**Comment by jrodalo** [comment]
Done!

Pull Request #397

**Comment by cagataycivici** [comment]
Reverting as this change breaks frozen scrollable tables.

**Comment by jrodalo** [comment]
@cagataycivici Could you provide an example? I've tried this code with both versions and the result its the same:

``` xml
<p>3 columns + scrollable + frozenColumns</p>
<p:dataTable emptyMessage="should have a colspan='3'" scrollable="true" frozenColumns="1">
    <p:column headerText="1" />
    <p:column headerText="2" />
    <p:column headerText="3" />
</p:dataTable>
```

![primefaces](https://cloud.githubusercontent.com/assets/1197514/8006573/2b4bf708-0b8d-11e5-9531-9632413e4559.png)

It looks like this case needs a bigger refactor than expected. The "emptyMessage" its duplicated on both sides of the table and hidden with css on the right side ('ui-datatable-frozenlayout-right').

Maybe it should paint 'ui-datatable-empty-message' below the frozenlayout's &lt;td&gt;s, with a fixed colspan of 2? (1->ui-datatable-frozenlayout-left and 1-> ui-datatable-frozenlayout-right).

**Comment by cagataycivici** [comment]
I'll just display a div instead of tbody to avoid colspan issues.
