### ISSUE TITLE
avalon theme:tabView panels not displayed with attribute orientation="left"

### ISSUE THREAD

**Issue by ppelzman** [primefaces/primefaces#3871]
## 1) Environment
- PrimeFaces version: 6.2
- avalon theme version 1.0.5

## 2) Expected behavior
tabView panels should be dispalyed with any attribute orientation

## 3) Actual behavior
tabView panels not displayed with attribute orientation="left"

**Comment by tandraschko** [comment]
Does it work without avalon?
