### ISSUE TITLE
<p:commandLink/> and <p:ajax event="tabChange"> cannot handle ajax-redirect request

### ISSUE THREAD

**Issue by marembo2008** [primefaces/primefaces#3876]
## 1) Environment
- PrimeFaces version: 6.0,6.1,6.2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No (6.3-SNAPSHOT)
- Application server + version: Wildlfy 10.0.0-FINAL, jsf-api 2.2
- Affected browsers: Chrome, Firefox

## 2) Expected behavior
When an ajax-redirect response with 307 status with body:
```
<partial-response>
    <redirect url="http://local.example.com:8080/accounts/login"/>
</partial-response>
```
is received, we expect the ajax handler to redirect to the specified page.

## 3) Actual behavior
ajax handler receives the request but fails with an error
```
core.js.xhtml?ln=primefaces&v=6.3-SNAPSHOT:215 Request return with error:error.
```

## 4) Steps to reproduce
- We preprocess and may redirect any request at the filter level, hence there is no FacesContext active at this point, hence we cannot use `FacesContext.getExternalContext().redirect(...)`
- To achieve the same functionality as the `FacesContext.getExternalContext().redirect(...)`, we write the following response on the filter for ajax-request:

```
servletResponse.setContentType("text/xml");
servletResponse.setCharacterEncoding("UTF-8");
servletResponse.addHeader("Cache-Control", "no-cache")
servletResponseWriter.append(
"<?xml version="1.0" encoding="UTF-8"?>
<partial-response>
    <redirect url="http://local.example.com:8080/accounts/login"/>
</partial-response>"
)
servletResponseWriter.flush();
```
## 5) Sample XHTML
- tested with the following ajax:

```
--- Does not work
<p:ajax event="tabChange" 
             listener="#{accountSettingsTabbingController.onTabChange}"
             process="@this"/>
```

```
--- Does not work

<p:commandLink styleClass="dh-req-btn as-wacc as-right"
                           value="Update"
                           actionListener="#{userController.updateDetails()}"/>
```

```
--- With normal jsf h:commandLink works
<h:commandLink styleClass="dh-req-btn as-wacc as-right"
                           value="Update"
                           actionListener="#{userController.updateDetails()}"/>
```

## 6) Sample bean
- using Filter HttpServletResponse out
```
    private void ajaxRedirect(@NonNull final HttpServletResponse servletResponse,
                              @NonNull final String url) throws IOException {
        //For xml, the default escaping does not skip entities such as &
        final String redirectUrl = StringEscapeUtils.escapeXml10(url);
        final String redirectContent = MessageFormat.format(FACES_AJAX_REDIRECT_CONTENT, redirectUrl);
        final PrintWriter out = servletResponse.getWriter();
        servletResponse.setContentType(FACES_AJAX_REDIRECT_CONTENT_TYPE);
        servletResponse.setCharacterEncoding("UTF-8");
        servletResponse.addHeader("Cache-Control", "no-cache");
        out.append(redirectContent);
        out.flush();
    }

    private boolean isAjaxRequest(@NonNull final HttpServletRequest servletRequest) {
        return requestHeader(servletRequest, FACES_AJAX_HEADER, FACES_AJAX_PARAM)
                || requestHeader(servletRequest, AJAX_REQUESTED_WITH_HEADER, AJAX_REQUESTED_WITH_PARAM);
    }
```

**Comment by tandraschko** [comment]
Plesse provide an runnable example as requested by the issue template.

**Comment by tandraschko** [comment]
At best you can fork the primefaces-test project.

**Comment by marembo2008** [comment]
After further investigation, discoverred that ajax is unable to handle properly, responses which are not in the range of `2XX`, and this works if the response is `200`. Either this is a technicall limitation of jsf, or ajax, but it is better to clarify.

For now, i will close this issue as not necessary.

**Comment by tandraschko** [comment]
IMO it's a bug if it works fine with f:ajax, but not with p:ajax.
We use jquery AJAX under the hood, maybe we need to set a flag to allow it.
