### ISSUE TITLE
AutoComplete doesn't query on backspace/delete in IE9

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#388]
Also on cutting/delete via context menu.
Because IE9 doesn't trigger the input event. This could be worked around, i.e. using the selectionchange event.

**Comment by cagataycivici** [comment]
What is your PF version? Is it plain IE9 or IE10-11 with IE9 mode?

**Comment by VsevolodGolovanov** [comment]
Reproducible in PF showcase, which says "Running PrimeFaces-5.2.5-SNAPSHOT" at the moment.
It's actual IE9 on Windows 7. Browser mode: IE9, Document mode: IE9 Standards.

**Comment by mertsincan** [comment]
Replicated the issue on pure IE9. I will work on it.

**Comment by VsevolodGolovanov** [comment]
Presumably was fixed in #1005 for backspace, but not delete.
