### ISSUE TITLE
InputTextArea: AutoComplete Not Working

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#3881]
## 1) Environment
- PrimeFaces version: 6.2.6
- Does it work on the newest released PrimeFaces version? NO
- Does it work on the newest sources in GitHub?NO
- Application server + version: Showcase
- Affected browsers: All

## 2) Expected behavior

InputText Area with AutoComplete should show AutoComplete items.

## 3) Actual behavior

No AutoComplete items are appearing.

## 4) Steps to reproduce

**Showcase:** https://www.primefaces.org/showcase/ui/input/inputTextarea.xhtml

Just type 4 chars or more into AutoComplete.  You can see the items in the DOM updated but they are not displayed in the UI.

**Comment by melloware** [comment]
Reported through my PRO account.

**Comment by mertsincan** [comment]
Fixed for 6.2.8. It works fine with 6.3-SNAPSHOT.
