### ISSUE TITLE
Tree/TreeTable: List not supported as a selection type

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3887]
Selection in `p:tree` only support arrays but not list (while datatable does)

**Comment by Rapster** [comment]
That's a lot of effort... The existing support of arrays in Tree/TreeTable make that task quite difficult as I need to check/convert (or not) into a List. Datatable is much more simple in that sense.

My guess would be to drop support of arrays since there is a better type that make things much more simpler: List<T>

**Comment by tandraschko** [comment]
@melloware 
do we have some integration tests about tree+treetable selection? i would like to implement this

**Comment by melloware** [comment]
I think we spent most of our time on Datatable tests I don't think we have many if any TreeTable tests.

**Comment by tandraschko** [comment]
if anyone is interessted, some simple integration tests would be great
