### ISSUE TITLE
p:autocomplete selectLimit default value

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#389]
Hello all,

I want to do something like this:
`selectLimit = "#{bean.value eq 'A' ? '1':''}"`

if value is 'A', autocomplete should be limited to 1 otherwise it should be unlimited. The documentation is not clear about what value is used to set "unlimited" options.

In source code, we dont have the implementation to do my requeriment, when selectLimit="", or is empty the input component (_xxxxx_input_) is hidden when widget is initialized. But if selectLimit is less than 0, only accept 1 option, but if I click the X to close that option, the input component (_xxxxx_input_) is hidden again.

If you add a default value the source code could be changed to create a clear solution and avoid this problem.

Regards,

**Comment by cagataycivici** [comment]
It is not clear what your requirement is, please discuss at forum first.
