### ISSUE TITLE
ClientId Resolution: Option to log not throw unresolvable client id

### ISSUE THREAD

**Issue by Helveticus** [primefaces/primefaces#3893]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.3
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 9.1, JSF 2.3
- Affected browsers:All

## 2) Expected behavior
I would like to have a configurable faces-config.xml option for PF to simply log an unresolvable client id in SearchExpressionFacade.cannotFindComponent() instead of throwing an exception.  I am currently converting a very large and complex application from PF 3.5 to 6.3 and will be fighting unresolvable ids in ajax update arguments for a long time.  Rather than throwing an exception into the users' face (a security risk, I might add), I would simply log the incident so that it can be fixed without undue alarm. Most of these errors have either no impact or may cause refresh issues, neither of which raise to the level of a production stopper.

## 3) Actual behavior
Throws a ComponentNotFoundException

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
I'm not sure if i will do this.
It's not a security problem as exceptions should be never printed directly to the UI for endusers.

For me this are real issues as the view doesn't match the update attribute anymore and should be fixed.

**Comment by kukel** [comment]
I'd say that in jsf development mode they full in your face (might even be extended to show more). But id's that are not found result in non-functional applications. So catching them and showing a generic error is the best thing to do like Thomas stated (so that makes this issue sort of void)
