### ISSUE TITLE
Poll: Fix "stop" attribute to not start polling if true

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#3894]
Looking in the poll.xml which generates the documentation for the component is this:

        <attribute>
            <name>stop</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Stops polling when true.</description>
        </attribute>

I cannot find anywhere this property is actually used and I have confirmed it does nothing setting this EL expression.  I think somewhere along the lines this component was modified to autoStart="" attribute but the stop was never removed.

**Comment by tandraschko** [comment]
It's used actually ;) See Poll#broadcast

**Comment by melloware** [comment]
Hmm then we are seeing some really strange behavior using stop then.  will investigate further.

**Comment by melloware** [comment]
Now that I think about it would be that broadcast has to happen once first before it stops?   Because we are seeing are EL evaluation to stop="true" and the page renders and fires the poller.

**Comment by tandraschko** [comment]
Maybe, but removing it is no solution ;)
if "stop" evaluates to true, the polling should stop.

**Comment by tandraschko** [comment]
Probably, yes.

**Comment by melloware** [comment]
Got it.  I removed my PR you are right I didn't see the broadcast.

**Comment by melloware** [comment]
I think I can fix this a different way to work on initialization as well. Will send PR for review.
