### ISSUE TITLE
monitorDownload: Download monitoring won't close

### ISSUE THREAD

**Issue by euanmat** [primefaces/primefaces#3899]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version?
I don't know, I currently have a technical issue with my nexus repo, 
and am unable to maven install the project again with the latest primefaces version..

- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: **FireFox**

## 2) Expected behavior

The download is launched with a button.
Then a popup showing the download progress bar, is opened with a "start()" function.
A js polling is made every second to look for a cookie named "primefaces.download".
When the download is done, a cookie with "true" value is sent to the client.
This triggers the stop() callback function. 
The download progress bar is hidden.
During stopping, the cookie value is set to "null".

## 3) Actual behavior

After the end of a second download, the progress bar is never hidden, 
thus blocking the whole page.

My understanding of this issue:

During stop() method call, a second cookie is created with an "/" added to the contained path.
Then having now 2 "primefaces.download" cookies.

When calling the download a second time, the js polling is made on the cookie set to "null".
The cookie with "true" value is then recreated, but never gets polled.

Proposed fix in the Primefaces.monitorDownload(start, stop, id):
`//PrimeFaces.setCookie(cookieName, null); <<< wrong!

PrimeFaces.deleteCookie(cookieName,{path:'/'}); `

## 4) Steps to reproduce

Click the download button.
copy the downloaded file somewhere.

Click the download a second time.
The download progress bar won't close.

## 5) Sample XHTML

`<p:commandButton id="telechargerFichier" value="#{msg.telecharger}" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop)"  icon="ui-icon-arrowthichk-s">  
<p:fileDownload value="#{exporterController.actionTelecharger()}" />  
</p:commandButton> #{msg.exporter_resultat}
<p:dialog appendTo="@(body)" modal="true" widgetVar="statusDialog" header="#msg.telechargement}" draggable="false" closable="false" resizable="false">
<p:graphicImage value="/images/ajaxloadingbar.gif" />  
</p:dialog>
</h:form>
<script type="text/javascript">  
function start() {  PF('statusDialog').show(); }  
function stop() {  PF('statusDialog').hide(); }  
</script>`

## 6) Sample bean

-

**Comment by tandraschko** [comment]
Please provide a runnable example, we don't have your exporterController.
You can also reuse beans from the showcase.

**Comment by melloware** [comment]
@euanmat see this ticket for a good example on how to provide a "runnable" sample so we can debug.  https://github.com/primefaces/primefaces/issues/3901

**Comment by euanmat** [comment]
As suggested, I have used the example above to deliver a sample.

[primefaces-3899.tar.gz](https://github.com/primefaces/primefaces/files/2228581/primefaces-3899.tar.gz)

I hardly tried to find the case reproducing the problem with this sample, but there is something missing that I can't figure out.

The sample still shows that a cookie with "true" value is created for each download.
But I can't see a cookie with a "null" value set.
I am using firefox quantum 57.0.4 .

> Run this sample app using "mvn clean jetty:run" and navigate to http://localhost:8080/primefaces-test/test.xhtml and press the AddRow button.

**Comment by melloware** [comment]
@euanmat were you ever able to reproduce this?  If not I suggest closing this ticket as I can't reproduce your issue.

**Comment by euanmat** [comment]
As suggested, I am closing this issue, because I wasn't able to reproduce it outside the project, thank you.

**Comment by anhquande** [comment]
I experience the same problem on Primefaces 6.3.
In one page, the stop() is called.
In other page, the stop() is not called.

I cannot find out the difference related to the download file function between these 2 pages. It is hard to reproduce. But i think the problem is still there. And close this issue will make the problem ignored.

**Comment by melloware** [comment]
If you can narrow it down and reproduce the issue is the only way we can help fix it.

**Comment by StevenHachel** [comment]
PrimeFaces Elite: Version 8.0.12
primefaces-extensions: Version 8.0.12
omnifaces: Version 1.14.1
Browser: Firefox, Google Chrome

WebLogic 12 with JavaEE6


Same problem after migrating from PF7 to PF8.
Had to help me with my own implementation in which I read the cookie differently.
$ .Cookie ("primfaces.download") is always null. It worked perfectly up to PF7.

The decisive factor is reading out the cookie with the getCookieByName (name) function.

Am I the only one with this problem? 

new implemetation example:

```
var App = {

monitorDownload: function (start, complete, monitorKey) {
            if (this.cookiesEnabled()) {
                if (start) {
                    start();
                }

                var cookieName = monitorKey ? 'primefaces.download_' + monitorKey : 'primefaces.download';
                window.downloadMonitor = setInterval(function () {
                    var downloadComplete = App.getCookieByName(cookieName);

                    if (downloadComplete === 'true') {
                        if (complete) {
                            complete();
                        }
                        clearInterval(window.downloadMonitor);
                        PrimeFaces.setCookie(cookieName, null);
                    }
                }, 1000);
            }
        },

        getCookieByName: function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");

            // Loop through the array elements
            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if (name == cookiePair[0].trim()) {
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }

            // Return null if not found
            return null;
        },
```

Steven

**Comment by melloware** [comment]
@StevenHachel 
If you provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project we can debug your issue.  I am currently not seeing any issues.
