### ISSUE TITLE
Row grouping in DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#39]
Enable grouping for repeating values;

http://stackoverflow.com/questions/11022456/primefaces-row-grouping-for-repeated-values

**Comment by aluzme** [comment]
have issue fixed yet

**Comment by cagataycivici** [comment]
It would have been marked as closed with a version number.

**Comment by mtbadi39** [comment]
any news !

**Comment by diegooliveiralima** [comment]
nothing yet?

**Comment by cagataycivici** [comment]
Implementation planned during mid december.

**Comment by danhuru** [comment]
hi, any news about this feature?

**Comment by kukel** [comment]
Did you READ any news here? Or in the blog? Or in releasenotes?

**Comment by andrei-ivanov** [comment]
+1

**Comment by lgklein** [comment]
This improvement is still in the plans for implementation? If so, is there any idea to which version?

**Comment by andrei-ivanov** [comment]
6.1 it seems, see http://blog.primefaces.org/?p=4094

**Comment by lgklein** [comment]
Ty!

**Comment by regenduft** [comment]
seems this was implemented with https://github.com/primefaces/primefaces/issues/1950 so this issue could be closed?

**Comment by tandraschko** [comment]
Jup, thanks.
