### ISSUE TITLE
Datatable: add FilterableHeaderOnReflow

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#3902]
## 1) Environment
- PrimeFaces version: 6.2.7
- Does it work on the newest released PrimeFaces version? Version? No. 6.2.7
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: apache-tomcat-8.5.27
- Affected browsers: all

## 2) Expected behavior
When a datatable is filtered and the the width shrinks the table "reflows"
A sorting select dropdown is added above the datatable.
I would like to see all filtering show above the datatable.
...

## 3) Actual behavior
Unable to filter on a datatable that is reflowed
..

## 4) Steps to reproduce
paradise-1.0.3/data.xhtml
                       <p:column headerText="Year" filterBy="#{car.year}" filterMatchMode="exact" sortBy="#{car.year}">
                                      <h:outputText value="#{car.year}" />
                        </p:column>
.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

org/primefaces/component/datatable/DataTableRenderer.java contains

         if (table.isReflow()) {
            encodeSortableHeaderOnReflow(context, table);
        }

perhaps it would look like this:
 
         if (table.isReflow()) {
            encodeFilterableHeaderOnReflow(context, table);
            encodeSortableHeaderOnReflow(context, table);
        }

![image](https://user-images.githubusercontent.com/1318377/43160789-2b928bd4-8f54-11e8-858f-c6ef3f8ed205.png)

![image](https://user-images.githubusercontent.com/1318377/43160808-3aac4cf4-8f54-11e8-9e7a-af9809c30c2d.png)

**Comment by melloware** [comment]
PrimeTek has removed support for "responsive" mode in other Prime Libraries so I doubt this would be supported even with a PRO request. See: https://github.com/primefaces/primeng/issues/12047
