### ISSUE TITLE
New Component: ToggleSwitch

### ISSUE THREAD

**Issue by huseyinturkmenoglu** [primefaces/primefaces#3906]
ToggleSwitch is used to select a boolean value. 
Note: ToggleSwitch is a new generation switcher. This component is similar to inputSwitch component. However, toggleSwitch is better than inputSwitch in performance. ToggleSwitch is created using the power of CSS instead of calculating some Css properties such as width and height. The example CSS switcher; https://www.w3schools.com/howto/howto_css_switch.asp

**Comment by Rapster** [comment]
At least give us a quick description, otherwise what's the point of creating an issue while you're already providing a PR?

**Comment by Rapster** [comment]
Does it mean inputSwitch will be deprecated?

**Comment by mertsincan** [comment]
Hi @Rapster,
Yes, inputSwitch will be deprecated.

**Comment by Rapster** [comment]
Cool, the new one looks very nice

**Comment by martin654** [comment]
@mertsincan Will the new inputSwitch support labels for true/false?
