### ISSUE TITLE
Poll: Allow value binding of interval to java.time.Duration

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3912]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No. 6.3-SNAPSHOT
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: Payara 5.182
- Affected browsers: ./.

## 2) Expected behavior

It'd be nice if one could specify a `java.lang.Duration` property of a backing bean as attribute value of `interval` of the `p:poll` component.

## 3) Actual behavior

Only strings can be specified which are interpreted as seconds.

## 4) Steps to reproduce

./.
## 5) Sample XHTML

./.

## 6) Sample bean

./.

**Comment by tandraschko** [comment]
PR welcome of course ;)

**Comment by tandraschko** [comment]
the benefit isn't big but i like it. Implemented :D
