### ISSUE TITLE
TreeTable: Fixed number of columns in ui:repeat

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#3913]
## 1) Environment
- PrimeFaces version: 6.2 (All)
- Application server: WildFly 11 (Java EE 7)
- Affected browsers: All

## 2) Expected behavior
Columns of second TreeTable should have the additional colum (5).

## 3) Actual behavior
Dynamic columns of TreeTables within ui:repeat all have the same number of columns, determined by the **first** TreeTable. The same construct with DataTable works as expected.

## 5) Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"  xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
  <h:head/>
    <h:body>
      <ui:repeat var="ls" value="#{[[1,2],[3,4,5]]}">
        <p:treeTable value="#{app.createTreeNode(ls)}" var="var" tableStyle="width:auto">
	  <p:columns var="c" value="#{ls}">#{c}</p:columns>
	</p:treeTable>
      </ui:repeat>
      <ui:repeat var="ls" value="#{[[1,2],[3,4,5]]}">
        <p:dataTable value="#{ls}" var="var" tableStyle="width:auto">
	  <p:columns var="c" value="#{ls}">#{c}</p:columns>
	</p:dataTable>
      </ui:repeat>
  </h:body>
</html>
```
![image](https://user-images.githubusercontent.com/415392/43371127-ba4c00ae-938b-11e8-9582-f5e45f1fe445.png)

## 6) Sample bean
```
@ApplicationScoped @Named public class App {
  public TreeNode createTreeNode(List<Long>is) {
    	DefaultTreeNode root=new DefaultTreeNode(is);
    	new DefaultTreeNode(is, root);
    	return root;
  }
}
```

**Comment by mdzaebel** [comment]
In my case, workarounds with c:forEach are impossible, as I have changing number of treeTables within postbacks. So, if you have any idea, to workaround this issue, it would be appeciated. For me, this issue is a showstopper, but certainly not for others. If I could help you in any way (even coding), feel free to ask me. Is there a developer documenation that enables me to dig into the relevant source?

**Comment by tandraschko** [comment]
Sorry, there isn't.
You can also try p:repeat, which is forked from Mojarra and contains a small bugfix,

If this doesn't help, i suggest to use PrimeFaces PRO to get a fix. This code (our UIData, Tree and Mojarra/PF repeat) is quite complex.

**Comment by mdzaebel** [comment]
I already tried p:repeat, unfortunately with the same result. Thanks for the tips. I'll consider them.

**Comment by kukel** [comment]
Tried using the `rowStatePreserved`? attribute? I remember it helped me once. And I can still see if I can find (via the issue list) what the fix was for the datatable, since I'm 100% certain it had the same problem once. And did you try using the rowIndexVar and get the colums from the `#{[[1,2],[3,4,5]]}` using the index? I remember that helping too.

Edit: Found it https://github.com/primefaces/primefaces/issues/88

**Comment by mdzaebel** [comment]
Ronald, thats really kind of you, to help me with your experience. `rowStatePreserved `is only a _p:dataTable_ attribute. `rowIndexVar` is an attribute for _p:dataList_, _p:dataScroller_ and _p:dataTable_, but also does not exist for _p:treeTable_. Using e.g. `columnIndexVar` of _p:columns_ doesn't change anything. 

Hope I'll have the time to look into the implementation.

**Comment by mdzaebel** [comment]
Mert, this is simply great! Thank you so much! I'll test your fix on my example too and reply shortly. In my view, this is an important bug fix. Tell me if I could help you with some easier work too.

**Comment by mdzaebel** [comment]
Works even in more complex test cases.

**Comment by mertsincan** [comment]
Thanks, @mdzaebel !
