### ISSUE TITLE
Calendar: locale is ignored after move to another page

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#3914]
## 1) Environment
- PrimeFaces version:  6.2
- JSF: 2.1 (2.1.29-08)
- Server version:       Apache Tomcat/8.0.0

## 2) Expected behavior
I use [Primefaces.locale](https://code.google.com/archive/p/primefaces/wikis/PrimeFacesLocales.wiki) to translate the labels of a calendar. When I call a bean that send me to another page without `?faces-redirect=true`  (after the end of the URL  in return command), calendars in new page stay in English (default locale).

## 3) Actual behavior
The locale is ignored after, from Bean I change to another page without `?faces-redirect=true` tag in return method.

## 4) Steps to reproduce
Go from a page to another through an action invoked by a h:commandLink that return a URL without 'faces-redirect=true'. **If I use  Primefaces previous versions (until 6.1) or '?faces-redirect=true' tag this problem does not occur.**

## 5) Sample XHTML

Page 1
```
<h:commandLink     id="buttonIncluir"           
     action="#{funcionarioBean.navegarCadastroControleFuncionario}"    > 
	    <h:outputText value="#{msg.button_adicionar}" /> 
   </h:commandLink>
```
 
 Page 2
```
 <p:calendar id="dataMin" locale="pt" 	    navigator="true" pattern="dd/MM/yyyy" mask="true" 
                           required="true"        value="#{myBean.dataMin}"    />
```	

## 6) Sample bean

```
public String navegarCadastroControleFuncionario() {
	 this.funcionarioControleCorrente = new FuncionarioControle();
	 return "/pages/cadastro/mao_obra/controle/cadastrarFuncionariosControle.html;
    //append it with: ?faces-redirect=true" solves the problem, but is not a viable.
	}
```

**Comment by tandraschko** [comment]
Please don't ignore this from our issue template:
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!

Can you check if the locale is correct in the 'PrimeFaces.settings.locale' variable? It should be rendered in the head,

**Comment by edudoda** [comment]
Yes it is present in both pages (source and destination page), In head I can see:  `<script type="text/javascript">if(window.PrimeFaces){PrimeFaces.settings.locale='pt_BR';}</script>` , and in console, 'PrimeFaces.settings.locale' prints pt_BR. 

Strange is that if I type the page URL direct in browser, or with '?faces-redirect=true' when comming from Bean,  it works fine! .... by now I downgraded Primefaces to 6.1

Thanks for helping me

**Comment by tandraschko** [comment]
As i said, please provide a fully runnable example or fork primefaces-test project, otherwise it's hard to test it.

**Comment by tandraschko** [comment]
Will close it for now, feel free to provide a test project and we can reopen it.
