### ISSUE TITLE
DataTable: preselection does not take account "disableSelection"

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3917]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 8
- Affected browsers: All

## 2) Expected behavior
 Scenario is as such:

- DataTable containing a bunch of data, each one of them can be added to a cart
- Select an element and add it to the cart
- From there, it shouldn't be possible to select this item (as it is in a cart: this is our requirement). We're using `disabledSelection` to avoid that...
- But after refreshing the datatable, the previous item should no longer be selected

## 3) Actual behavior
After refreshing the datatable, the previous item is still selected. 

## 4) Steps to reproduce
I used this expression to fake the cart feature: `disabledSelection="#{car.id eq dtSelectionView.selectedCar.id}"` in https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml (See RadioButton sample)

## 5) Sample XHTML
See 4

## 6) Explanations
There is at least an easy explanation, the managed bean being ViewScoped, selected items lives as long we're using the same view: this is why the last selection is kept. But preselection in `DataTable` should consider `disabledSelection`.

**Comment by melloware** [comment]
@Rapster why did you re-open this issue?  Is there some new bug?

**Comment by Rapster** [comment]
Because of this: https://github.com/primefaces/primefaces/issues/5868
