### ISSUE TITLE
Datatable: sorting doesn't update header checkbox when checkAllToggler used

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3919]
## 1) Environment
- PrimeFaces version: 6.2.6
- Does it work on the newest released PrimeFaces version? Version? 6.2.6 NO
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not working on 6.3-SNAPSHOT
- Application server + version: 
- Affected browsers: all

I have a p:datatable component with 
<p:column selectionMode="multiple" style="width:16px;text-align:center"/>
Some rows has their's checkbox disabled using expression in disabledSelection.
I use pagination, so there are pages where no row can be selected.
I also use sorting on some columns.

## 2) Expected behavior
When all of the row's checkboxes on current page are disabled on page load, then the **header checkbox** for toggleAll is disabled. When I use sorting and some of the rows are replaced with rows which are NOT disabled, then the toggleAll checkbox should be updated and become ENABLED.

## 3) Actual behavior
When all of the row's checkboxes on current page are disabled on page load, then the **header checkbox** for toggleAll is disabled. When I use sorting and some of the rows are replaced with rows which are NOT disabled, then the toggleAll checkbox is NOT enabled.

## 4) Steps to reproduce
Will provide if necessary. Fix is simple.
## 5) Sample XHTML
Will provide if necessary. Fix is simple.
## 6) Sample bean
Will provide if necessary. Fix is simple.

**Comment by martin654** [comment]
Fixed here: https://github.com/martin654/primefaces/commit/e7445de035f01496b196216934548d1604d7c177

Created pull request: https://github.com/primefaces/primefaces/pull/3920

**Comment by martin654** [comment]
@tandraschko  Thomas, could this be merged into next elite version? Thank you

**Comment by tandraschko** [comment]
i don't manage elite releases, thats up to @mertsincan

**Comment by martin654** [comment]
Ok, I see... How do you manage pull requests? Should I do something more to get the fix it into master?

**Comment by tandraschko** [comment]
PRs are for the community version
PrimeTek merges selected PRs then into the private elite branches

**Comment by tandraschko** [comment]
@mertsincan Would you merge it to elite?

**Comment by mertsincan** [comment]
Thanks a lot, @tandraschko and @martin654 ;)
