### ISSUE TITLE
PieChart: Legend broken with jqplot 1.0.9

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#3922]
## 1) Environment
- PrimeFaces version: 6.2.7
- Does it work on the newest released PrimeFaces version? No, but it works on 6.2.6
- Does it work on the newest sources in GitHub? Don't know
- Application server + version: Tomcat 7.0.85, Jetty
- Affected browsers: All

## 2) Expected behavior
The PieChart legend should display the correct data series.

## 3) Actual behavior
The PieChart legend displays only "Series 1".

## 4) Steps to reproduce
Run the showcase with 6.2.7, verify that the pie chart legend is broken.

## 5) Sample XHTML
See showcase.

## 6) Sample bean
See showcase.

I guess this is a side-effect of the upgrade to jqplot 1.0.9 (https://github.com/primefaces/primefaces/issues/1030)

**Comment by tandraschko** [comment]
@mertsincan can you check this?
