### ISSUE TITLE
accordionPanel: Can't update tab title on dynamic accordionPanel

### ISSUE THREAD

**Issue by luccotta** [primefaces/primefaces#3929]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Apache Tomcat 7.0.88
- Affected browsers:

## 2) Expected behavior

I should be able to update a dynamic `accordionPanel`'s `tab` titles in `<p:ajax event="tabChange"`

## 3) Actual behavior

I can only update the `tab` title if the `accordionPanel` `has dynamic="false"`

## 4) Steps to reproduce

1. Create a dynamic `accordionPanel` with value as a list from bean
2. Add a `tabChange` event, whose listener is a method in the bean that will change the tab title 
3. When running, click in a tab and the title won't chance

## 5) Sample XHTML

```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
	<h:form id="form">
		<p:accordionPanel id="ap1" dynamic="true" value="#{myBean.myEntityList}" var="entity">
			<p:ajax event="tabChange" listener="#{myBean.onTabClick(entity)}" update="ap1" />
			<p:tab id="t1" title="#{entity.title}">
      			#{entity.description}
      		</p:tab>
		</p:accordionPanel>
	</h:form>
</h:body>
</html>
```

## 6) Sample bean

```
@SuppressWarnings("restriction")
@ManagedBean
@ViewScoped
public class MyBean {
	
	private List<MyEntity> myEntityList;

	@PostConstruct
	public void setUp() {
		
		myEntityList = new ArrayList<>();
		myEntityList.add(new MyEntity(1L,"First title", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
				+ "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, "
				+ "quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"));
		myEntityList.add(new MyEntity(1L,"Second title", "Duis aute irure dolor in reprehenderit in voluptate "
				+ "velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, "
				+ "sunt in culpa qui officia deserunt mollit anim id est laborum."));
		
	}
	
	public void onTabClick(MyEntity entity) {
		entity.setTitle("temp");
	}

	public List<MyEntity> getMyEntityList() {
		return myEntityList;
	}

	public void setMyEntityList(List<MyEntity> myEntityList) {
		this.myEntityList = myEntityList;
	}
}
```

**Comment by tandraschko** [comment]
A PR would be welcome!

**Comment by melloware** [comment]
Reproducer:
[pf-3929.zip](https://github.com/primefaces/primefaces/files/5597208/pf-3929.zip)

**Comment by tandraschko** [comment]
aligned the docu that this is not supported.
