### ISSUE TITLE
MenuModel/MenuElement: Provide equals and hashCode for MenuModel and MenuElement implementations

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3931]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No. 6.3-SNAPSHOT
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: ./.
- Affected browsers: ./.

## 2) Expected behavior

Implementations of `MenuModel` and `MenuElement` should provide an `equals` and `hashCode` implementation. `BaseMenuModel` and `DefaultMenuItem` are good candidates.

## 3) Actual behavior

Methods refer to the `Object` implementation.

## 4) Steps to reproduce

./.

## 5) Sample XHTML

./.

## 6) Sample bean

./.

**Comment by Rapster** [comment]
I don't see why we should have such methods. What is your scenario? What would it fix?

**Comment by krichter722** [comment]
Closing for reason explained in https://github.com/primefaces/primefaces/pull/3930#issuecomment-410499075
