### ISSUE TITLE
TreeTable: Column visibility property ignored or not implemented

### ISSUE THREAD

**Issue by sarvigalava** [primefaces/primefaces#3934]
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Embedded Tomcat + JSF 2.2
- Affected browsers: All

## 2) Expected behavior
Column should be hid when visible=false
...

## 3) Actual behavior
The visible property is ignored. All columns are displayed
..

## 4) Steps to reproduce
Add a TreeTable with an invisible column
.. 

## 5) Sample XHTML
<p:treeTable ...>
<p:column  visible="false">
...
</p:column>
</p:treeTable>

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
It's not implemented yet - a PR would be welcome!

**Comment by melloware** [comment]
This was fixed a while ago in 6.2.11 and 7.0.  See: https://github.com/primefaces/primefaces/issues/4176
