### ISSUE TITLE
ContextMenu: Mobile device opening location

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#394]
The context menu currently opens at the location of the mouse pointer. For desktops this is expected and normal behaviour. For smaller devices, the boundary detection does not work great and the context menu shows up in a way that makes it kind of not useful. Would be great if it showed up in the middle of the screen then. With some small changes, that is possible.

This sould go in PF core:

```
getMediaSize : function() {
    var size;
    if (window.matchMedia('(min-width: 960px) and (max-width:1200px)').matches) {
        /* Intermediate sized desktop */
        size = 5;
    } else if (window.matchMedia('(min-width: 960px)').matches) {
        /* Large desktop */   
       size = 4;
    } else if (window.matchMedia('(min-width: 640px) and (max-width: 960px)').matches) {   
        /* Portrait tablet to landscape <???> and small desktop */
        size = 3
    } else if (window.matchMedia('(min-width:480px) and (max-width: 640px)').matches) {   
        /* Landscape phone to portrait tablet */
        size = 2;
    } else  if (window.matchMedia('(min-width:320px) and (max-width: 480px)').matches) {
        /* Portrait phones and down */
        size = 1;
    } else {
        alert('Are you seriously using this?');
        size = 0;
    }
    return size;
},
```

And this in menu.js in context menu position part

```
if (PrimeFaces.getMedia <3) {

    left = 'calc(50% - '+width+'px/2)';
    top = 'calc(50% - '+height+'px/2)';

} else {
    //collision detection for window boundaries
    if((left + width) > (win.width())+ win.scrollLeft()) {
        left = left - width;
    }
    if((top + height ) > (win.height() + win.scrollTop())) {
        top = top - height;
    }
}
```

The media query stuff does not work on IE<10, but it can be easily detected and ignored if not present or supported with a small polifill (I'd go for ignoring. Who uses IE<10 on a mobile device)

See also: [Forum post](http://forum.primefaces.org/viewtopic.php?f=3&t=42040&p=132324#p132324)

**Comment by cagataycivici** [comment]
How do you open a contextMenu on a mobile device? Do you have an example javascript contextmenu that is responsive?

**Comment by kukel** [comment]
A 'long-click' opens it. And what do you mean by 'a javascript context menu'? I use the PrimeFaces one with the above patches. Nothing else.

**Comment by kukel** [comment]
shall I create a pull request for this against trunk? And to be clear, the only 'responsiveness' is the positionning

**Comment by melloware** [comment]
@kukel is this still an issue?  I just added Long Press for mobile devices to trigger the context menu. https://github.com/primefaces/primefaces/pull/5238

**Comment by melloware** [comment]
@kukel can you test this with 8.0-SNAPSHOT to see if it is still an issue?  I can't quite reproduce what you are seeing?

**Comment by kukel** [comment]
I'll try (sorry, had unseen problems with email account I receive notifications of github on). Will try next week, out of the country for a few days). But a quick check in the showcase at least did have good 'boundary' detection and positions better. But honestly, having a context menu pop-up in the middle of the screen (at least on phones) for me would be better. Luckily the original problem is gone (might have been the result of the jquery upgrade in the mean time)

**Comment by melloware** [comment]
@kukel No worries let me know when you get around to testing it.  I appreciate all of your efforts!
