### ISSUE TITLE
PanelMenu:Accordion Like Behaviour

### ISSUE THREAD

**Issue by sakkie6yster** [primefaces/primefaces#3943]
I have the same problem as noted by "https://github.com/primefaces/primefaces/issues/1658".
Basically, I added "accordion like" behaviour to my PanelMenu, using JavaScript, as this ability did not exist at the time (Primefaces 5.3).  

When migrating the application from 5.3 to 6.0 (also tried 6.1 and 6.2), the JavaScript is not working as before.  In versions 6.0 and 6.1, it does not work at all, whereas with 6.2, the JavaScript function only seems to work after a delay of some sort. 

My question is whether or not there is a different way of adding this behaviour to the PanelMenu, that would ensure that the function does not break with every upgrade?

## 1) Environment
- PrimeFaces version: 6.0
- Application server + version: Wildfly 10.1
- Affected browsers: Tried this in Chrome (probably all)

## 2) Expected behaviour
PanelMenu to show accordion like behaviour, i.e. collapse other  menu headers when one is selected.

## 3) Actual behaviour
PanelMenu does not behave like an accordion. 

## 5) Sample JavaScript

`PF('hbPanelMenu').headers.click(function() {
    var currHeader = $(this);

    PF('hbPanelMenu').headers.each(function() {
        var header = $(this);
        if (header.text() !== currHeader.text()) {
        	PF('hbPanelMenu').collapseRootSubmenu(header);
            header.removeClass('ui-state-hover');
        }
    });
});`

**Comment by tandraschko** [comment]
Maybe we can introduce a option called "multipleSelection" or similar? Maybe a better name?

Default would be true.

**Comment by sakkie6yster** [comment]
That would be fantastic. In the meantime though; any suggestions on getting this "custom" behaviour to work again?

**Comment by tandraschko** [comment]
No sorry. But you can easily check the source and rewrite your code.
Then you could also implemented the behavior and provide a PR :)

NOTE:  PF is open source and the easiest way is to implemented it by yourself and the provide a PR, so we can include it in PF. You can also sponsor the feature via PrimeFaces PRO.

**Comment by huseyinturkmenoglu** [comment]
For your case, I added 'multiple' attribute in the panelMenu. The default value is true.

You could use this example: 
```
<h:form>
<p:panelMenu style="width:300px" multiple="false">
                <p:submenu label="Ajax Menuitems">
                    <p:menuitem value="Save" actionListener="#{menuView.save}" icon="ui-icon-disk" />
                    <p:menuitem value="Update" actionListener="#{menuView.update}" icon="ui-icon-arrowrefresh-1-w" />
                </p:submenu>
                <p:submenu label="Non-Ajax Menuitem">
                    <p:menuitem value="Delete" actionListener="#{menuView.delete}" ajax="false" icon="ui-icon-close" />
                </p:submenu>
                <p:separator />
                <p:submenu label="Navigations">
                    <p:submenu label="Links" icon="ui-icon-extlink">
                        <p:submenu label="PrimeFaces" icon="ui-icon-heart">
                            <p:menuitem value="Home" url="http://www.primefaces.org" icon="ui-icon-home" />
                            <p:menuitem value="Docs" url="http://www.primefaces.org/documentation" icon="ui-icon-document" />
                            <p:menuitem value="Download" url="http://www.primefaces.org/downloads" icon="ui-icon-arrowthick-1-s" />
                            <p:menuitem value="Support" url="http://www.primefaces.org/support" icon="ui-icon-wrench" />
                        </p:submenu>
                    </p:submenu>
                    <p:menuitem value="Mobile" icon="ui-icon-signal" />
                </p:submenu>
            </p:panelMenu>
</h:form>
```

**Comment by sakkie6yster** [comment]
Fantastic! Thank you so much!

**Comment by cbasener** [comment]
Whether I'm missing some important point but this is not working for me.
I tried PF 6.2.9 and PF 6.2.10.
It seems that the new attribute 'multiple' doesn't change a thing.
It doesn't make any difference if I leave the attribute out, use 'multiple="true"' or use 'multiple="false"'.
The behavior is always the same.

This can also be validate with the current PF showcase: https://www.primefaces.org/showcase/ui/menu/panelMenu.xhtml
By default the multiple attribute should be true.
But only one submenu can be active at the same time.
So this attribute is not working properly?

**Comment by mertsincan** [comment]
Thanks a lot, @cbasener! Fixed now. Please see; https://github.com/primefaces/primefaces/issues/4280
