### ISSUE TITLE
Growl: does not show error message except first one (mobile)

### ISSUE THREAD

**Issue by ppelzman** [primefaces/primefaces#3947]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 8
- Affected browsers: Chrome, IE, ..

## 2) Expected behavior
We should be able to show a message with Growl any number of times on the same page.

## 3) Actual behavior
First time Growl is activated on a page works OK.
Next times Growl should show a message on the same page does not show anything.

## 4) Steps to reproduce
click OK several times without entering data.

## 5) Sample XHTML
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pm="http://primefaces.org/mobile">
	
<f:view renderKitId="PRIMEFACES_MOBILE" />

<h:head>
</h:head>

<h:body >
		
	<p:growl id="messages" >
		<p:autoUpdate/>
	</p:growl>
	
	<pm:page id="page">
		<h:form id="pageForm">

			<pm:content id="parcelPanel">
		
				<p:outputLabel value="Field value:" 
					 for="mandatoryField" />	
			
				<p:inputText id="mandatoryField"
					required="true" autocomplete="off"					
					label="Field value is mandatory">
				</p:inputText>

			</pm:content>

			<pm:footer fixed="true">
				<p:toolbar>
					<f:facet name="left">
						<p:commandButton value="OK"
							icon="ui-icon-check" 							
							action="pm:page" 
							process="@form">
						</p:commandButton>
					</f:facet>					
				</p:toolbar>
			</pm:footer>

		</h:form>
	</pm:page>

</h:body>
</html>

**Comment by tandraschko** [comment]
Primefaces Mobile has been deprecated and removed already

**Comment by djmj** [comment]
You must manually show growl again. In your commandButton _oncomplete_ like:

	/* 
	 * show current growl message again - PF-mobile bug on page navigation not showing it 
	 * 
	 * @param widgetVar PF widgetVar
	*/
	function showGrowl(widgetVar)
	{
		PF(widgetVar).show(PF(widgetVar).cfg.msgs);
	}

	<p:growl id="growl" widgetVar="growlWidgetVar"/>

	<p:commandButton action="pm:page" oncomplete="showGrowl('growlWidgetVar');"/>
