### ISSUE TITLE
primefaces-6.3-SNAPSHOT : Only compiles with java 8

### ISSUE THREAD

**Issue by jrichardsz** [primefaces/primefaces#3948]
## 1) Environment
- PrimeFaces version: Current master branch: 6.3-SNAPSHOT (latest version)
- Artifact: primefaces-6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? : Public available artifact is **6.2**. I trying **6.3-SNAPSHOT**
- Does it work on the newest sources in GitHub?: No
- Operative System: Ubuntu 16.04.1
- Affected browsers: No

## 2) Expected behavior
Following this guide: Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source

This command : **mvn clean install** must be create the jar and install it .

## 3) Actual behavior

Following this guide: Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source

This command : **mvn clean install** must be create the jar and install it but it throw an error: 

```
[WARNING] Error injecting: org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo
java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/AuditListener : Unsupported major.minor version 52.0
```
Total log : https://gist.github.com/jrichardsz/c0e7c28ebde721d227b71cd3e6d33b29

..

## 4) Steps to reproduce

- Clone this repository : https://github.com/primefaces/primefaces.git
- Enter and run : **mvn clean install**

.. 

## 5) Works with java 8 ?

As **Unsupported major.minor version 52.0** is a classic error, I tried to compile with java8 and worked

..

Thanks

**Comment by tandraschko** [comment]
@krichter722 can you check this pls?

**Comment by krichter722** [comment]
@tandraschko The build with a JDK version 7 seems to be broken (maybe it was before). Does Primefaces support builds with JDK 7? It's deprecated and it's not tested on Travis. The build guide could be updated to avoid such confusion although I think that it's implied that building with a deprecated JDK is not supported.

**Comment by tandraschko** [comment]
@krichter722 primefaces must still run on java7 currently
Can we readd a build in Travis?

**Comment by krichter722** [comment]
@tandraschko `.travis-ci.yml` says

>  openjdk7  (not possible since JSF 2.3 dependency - we need to compile it)

[And Travis indeed still fails on OpenJDK 7](https://www.travis-ci.org/krichter722/primefaces/jobs/413217840). Oracle JKD 7 has been removed in #2767 because it's no longer supported by Travis CI.

This JRE 7 support slowly grows to get close to the Windows XP support problem. One solution would be to drop JRE 7 support, but I'm aware that a lot of companies and communities don't in order to avoid scaring away users which depend on outdated infrastructure.

**Comment by jrichardsz** [comment]
Hi Primefaces Team.

I just tried with 6.2 tag, and only compiles with java-8.

Thanks a lot.

PD: We are evaluating a web framework like react and angular but due to complexity, I am testing the old school: Primefaces with java. Also, I will try to make a spa with pure primefaces and some api rest as backend.

**Comment by tandraschko** [comment]
ok, i see and remember :D
Could someone build with java8 and run a application with it on java7?
If it's ok, i will close this issue. We can't go back as JSF23 required java8.

**Comment by krichter722** [comment]
> Could someone build with java8 and run a application with it on java7?

[No.](https://stackoverflow.com/questions/16143684/can-java-8-code-be-compiled-to-run-on-java-7-jvm)

Even if Primefaces project doesn't use Java 8 in the source, this wouldn't work. There're backporting solutions (see other answer in the SO question above), but they're overkill for supporting a deprecated JRE.

I added a note to the build guide.

**Comment by tandraschko** [comment]
we don't use java8 features or classes in our code, so there should be no problem as described in your link.

**Comment by jrichardsz** [comment]
I will try to compile again with java-8 and I will show you the result.

I using the commandline. I think that, eclipse ide could be problems when java-6 is in pom but java-8 is required to work. 

Thanks a  lot.

**Comment by tandraschko** [comment]
I will close the issue for now as compilation requires java8.
If you compile it with java8 and running with java7 doesn't work, please create a new issue.
