### ISSUE TITLE
Dialog: unrendering appended dialog's container doesn't hide it

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#3951]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT (latest).
- Application server + version: Wildfly 10.1.
- Affected browsers: All.

## 2) Expected behavior

If the appended dialog stops being rendered, then updating the container hides the dialog.

## 3) Actual behavior

Unrendered dialog is left shown.

## 4) Steps to reproduce

Reproducer:
[pf-3951.zip](https://github.com/primefaces/primefaces/files/13843361/pf-3951.zip)

Deploy sample.
Open the dialog.
Click "Close": should close the dialog and hide modality, but doesn't.

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view locale="en">
	<h:head>
	</h:head>

	<h:body>
		<h:form id="formy">
			<p:commandButton id="open" value="Open" action="#{dialogBean.toggle}" process="@this" update="@form" />

			<p:dialog id="dlgy" visible="true" appendTo="@(body)" rendered="#{dialogBean.rendered}" resizable="false" modal="true" closable="false">
				Rendered #{dialogBean.cnt} times.
				<p:commandButton id="update" value="Update" process="@this" update="@form" />
				<p:commandButton id="close" value="Close" action="#{dialogBean.toggle}" process="@this" update="@form" />
			</p:dialog>
		</h:form>
	</h:body>
</f:view>
</html>
```

## 6) Sample bean

```
import java.io.Serializable;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class DialogBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private boolean rendered;

	public boolean isRendered() {
		return rendered;
	}

	public void toggle() {
		rendered = !rendered;
	}

	private int cnt;

	public int getCnt() {
		return ++cnt;
	}

}
```

**Comment by VsevolodGolovanov** [comment]
Proposal: instead of rendering

```
<div id="client_id" class="ui-dialog...
```
and applying `appendTo` to this root component element,

render:
```
<div id="client_id">
	<div id="client_id_dlg" class="ui-dialog...
```
and `appendTo` the #client_id_dlg, leaving the root element in place. Then removal of the dialog will trigger widget's destruction properly, allowing it to act accordingly.

Would you accept a PR with such changes?

**Comment by VsevolodGolovanov** [comment]
Related bonus: updating the dialog's container removes modality, regardless of appendTo.

**Comment by tandraschko** [comment]
Feel free to provide a PR and some testcases with appendTo and without. So we can check if all cases works.

But it's expected currently, so enhancement/new feature.

**Comment by VsevolodGolovanov** [comment]
@tandraschko, could you take a look at this commit please? So that I know if I'm on the right track.

> Feel free to provide a PR and some testcases

In what form should I provide the testcases? Just post XHTML and Java code or ...?

**Comment by VsevolodGolovanov** [comment]
@tandraschko, I've been fleshing this out a bit, and I don't get one thing. I expected the dynamic overlay utils to automatically remove the appended overlay on widget destroy, but no.

```
removeDynamicOverlay: function(widget, overlay, overlayId, appendTo) {
    appendTo.children("[id='" + overlayId + "']").not(overlay).remove();
},
```

Why `not(overlay)`?

**Comment by VsevolodGolovanov** [comment]
I doubt this has any chance of being accepted, it's too big of a change for a pretty subtle gain.

**Comment by melloware** [comment]
Reproducer:
[pf-3951.zip](https://github.com/primefaces/primefaces/files/13843349/pf-3951.zip)

@VsevolodGolovanov this issue is slightly different than the one in the other ticket. Its similar but definitely a different use case.
