### ISSUE TITLE
DataTable: toggleSelect selecting too many rows

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3954]
Creating this issue as requested in ticket https://github.com/primefaces/primefaces/issues/3864. All important information are in this comment in referenced ticket: https://github.com/primefaces/primefaces/issues/3864#issuecomment-411698394

## 1) Environment
- PrimeFaces version: 6.2.8
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: any
- Affected browsers: any

## 2) Expected behavior
The same as in PF 6.2.6. Click on ToggleSelect should select all rows on current page in datatable. It should ignore rows for which disableSelection attribute evaluates to TRUE.

## 3) Actual behavior
All rows in datatable are selected across all pages including "disabled" ones using disableSelection.

## 4) Steps to reproduce
Will provide if needed.

## 5) Sample XHTML
Will provide if needed.

## 6) Sample bean
Will provide if needed.

**Comment by mertsincan** [comment]
Hi @martin654,

I don't think this issue is related to the following code;
```
if (checked) {
  selection = "@all";
}
```
(https://github.com/primefaces/primefaces/issues/3864#issuecomment-411698394)
However, I'll remove it on next version. Could you please try this issue with 6.2?

**Comment by martin654** [comment]
Thanks, it works now after the fix.
