### ISSUE TITLE
Datatable: problem with last column input rendering using p:columns 

### ISSUE THREAD

**Issue by martin654** [primefaces/primefaces#3957]
## 1) Environment
- PrimeFaces version: 6.2.8
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: any
- Affected browsers: any

## 2) Expected behavior
All invalid inputs are displayed the same way in each table column and the value inserted into last column is not forgotten on process+update when some validation error occurs.

## 3) Actual behavior
The value inserted in input in last column doesn't survive the "Process and update form" action **when some validation error happens on page** (validation on input field inside or outside the datatable).

Invalid inputs in last column have validation message in p:messages, but the input itself is not "rendered invalid" = is without red validation stripe. **They are missing ui-state-error class.**

## 4) Steps to reproduce
Reproducable example here: https://github.com/martin654/primefaces-test/commits/replicate/datatable_columns

**1st case:**
Click "Process and update form" button.
Observe that last column is not visualy marked as invalid, others are.

**2nd case**
Fill value into all input fields except single one.
Click "Process and update form" button.
Observe that last column values are cleared out.
(this happens too when the not-filled input is outside table)

**3rd case**
Fill some values into all input fields.
Click "Process and update form" button.
Observe that last column values are preserved.

## 5) Sample XHTML
Reproducable example here: https://github.com/martin654/primefaces-test/commits/replicate/datatable_columns

## 6) Sample bean
Reproducable example here: https://github.com/martin654/primefaces-test/commits/replicate/datatable_columns

**Comment by melloware** [comment]
@martin654 Can you tell if this existed in 6.2 and was introduced somewhere along the way to Elite 6.2.8?

**Comment by martin654** [comment]
@melloware Yes, it existed in 6.2 version. It even existed in 6.1, 6.0, 5.3, 5.2, 5.1, 5.0 and 4.0. I stopped at 4.0 :)

**Comment by melloware** [comment]
OK good wanted to make sure it wasn't a new issue but an existing issue.
