### ISSUE TITLE
New Component: Search

### ISSUE THREAD

**Issue by amayr666** [primefaces/primefaces#396]
What about a new component which can markup any occurences of a word or a part of a word in a specified object(div, panel,...)? Same thing like the browser search function, but for specified containers. This would be great, especially in addition to filter in dataTable.

eg.
    `<p:markDown styleClass="styleClassForMarkDown" for=":form:searchContainer" value="wordToSearch" />`

**Comment by cagataycivici** [comment]
We will consider, thank you. I believe we can use a jQuery plugin for this or implement our own.

**Comment by melloware** [comment]
This jquery component would be ideal: https://markjs.io/

**Comment by tandraschko** [comment]
Feel free to do it in Extensions and close this issue

**Comment by melloware** [comment]
Added to PF extensions: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/725  So closing this ticket.

**Comment by jxmai** [comment]
The search component is live. Checkout PF extension showcase: https://extensions.primefaces.org/sections/marktext/basicUsage.jsf

**Comment by melloware** [comment]
Nice work @jxmai !
