### ISSUE TITLE
Provide Maven snapshots repository

### ISSUE THREAD

**Issue by krichter722** [primefaces/primefaces#3963]
It'd be nice if snapshots built after every commit to `master` could be uploaded to a Maven repository. The upload could be automated and be be conducted from within Travis CI. This would be a continuous delivery pattern which is generally considered constructive and an improvement of the project. If repository.primefaces.org can't be used for snapshots, [Sonatype OSSRH](https://central.sonatype.org/pages/ossrh-guide.html) provides infrasturcture free of charge for FLOSS projects.

Afaik, `maven-jsf-plugin` only serves to be able to build PrimeFaces so that providing snapshots would only be useful to speed up building PrimeFaces in the CI/CD service.

I searched this tracker, the wiki and the community forums intensively and am now sure that this issue has never been discussed based on such a clean request.

**Comment by tandraschko** [comment]
we had it long time ago into our own repo but noone reconfiguired it.
i won't invest time on it, thats up to PrimeTek.

**Comment by melloware** [comment]
This can be done already with JitPack.  You can get the current snapshot of GitHub any time you want with this in your pom.xml.

```xml
 <dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>

 <repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>
```
