### ISSUE TITLE
 When clicking a selectOneMenu item that extends past an overlayPanel's buttom edge, the overlayPanel is closed.

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#3965]
Reported By PRO User;
> Put a selectOneMenu in an overlayPanel and add several items to it so the list extends below the bottom edge of the overlayPanel. If you open the selectOneMenu's list and click on an item that is below the bottom edge of the overlayPanel, not only will the selectOneMenu accept the selection, but the overlayPanel will close. Also, if you have an item that is partially in and partially out of the overlayPanel, clicking the part of the item that is inside the overlayPanel works as expected but clicking a part that is outside of the overlayPanel causes the overlayPanel to close too.

**Comment by tandraschko** [comment]
Should be fixed in Trunk by checking the DOM hierarchie instead the coordinates
