### ISSUE TITLE
Theme not appearing correctly in chrome vs IE

### ISSUE THREAD

**Issue by panksoni** [primefaces/primefaces#3966]
We use Ultima PrimeNg theme for our project. Suddenly the theme has started appearing without any bold or contrast in chrome vs IE.

For example theme is appearing like this in chrome

![image](https://user-images.githubusercontent.com/6334364/44117133-04f981a0-9fd8-11e8-82a6-e6f3087f13cc.png)

and this is how it appears in firefox or IE

![image](https://user-images.githubusercontent.com/6334364/44117178-2569eeca-9fd8-11e8-85d5-2a9086fe1506.png)

I have tried resetting the chrome browser.

**Comment by tandraschko** [comment]
use the primeng, not the primefaces, issue tracker ;)
