### ISSUE TITLE
selectOneMenu: background-color conflict with jquery UI CSS

### ISSUE THREAD

**Issue by awenger63** [primefaces/primefaces#3968]
PF 6.2
since #3079 new lines appear on forms.css 

`.ui-selectonemenu.ui-state-hover,
.ui-selectonemenu.ui-state-focus {
    background-color: transparent;
}`

This replace default setting for background-color on jquery ui css theme.css on ui-state-hover and ui-state-focus.

Current workarround, put !important on background interaction states in theme.css, but this is not fine !!!

Are you sure this is a correction or a oversigth ?
Thanks for your comment.

**Comment by tandraschko** [comment]
I can't follow you and this is not a valid issue, just a question (we have a forum for this).

Please describe your problem more detailed and provide screenshots.

**Comment by awenger63** [comment]
@tandraschko OK, I tell you my screenShot 
Previous PF version 6.1.15, when mouse hover or focus selectonemenu, it's the background value from theme.css which is applied.
Since PF 6.2 this [commit](https://github.com/primefaces/primefaces/commit/9f03b4ec1e4f1c9d9380929c60c735d56714f76a) the new values from components.css replace background-color for ui-state-hover and ui-state-focus from theme.css for selectonemenu component ! 
In my case, this change custom css layout and my text in white disapear (transparent is white in Chrome or FireFox see screenshot) !
![image](https://user-images.githubusercontent.com/16153617/44209776-c218b200-a164-11e8-8f08-de5202373cc7.png)

I really think this is an issue for other custom css and I hope now it's more comprehensive ?

**Comment by tandraschko** [comment]
@mertsincan Can you check that?

**Comment by awenger63** [comment]
pictures are not enought ?
You can check when unckeck .ui-selectonemenu.ui-state-hover, .ui-selectonemenu.ui-state-focus { background-color: transparent; } on navigator dev tool.
