### ISSUE TITLE
inputSwitch: Not working after update his parent

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#3969]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Not, I'm using PF 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 4) Steps to reproduce
https://forum.primefaces.org/viewtopic.php?t=42821

## Solutions
The problem is related to this line:
https://github.com/primefaces/primefaces/blob/6_2/src/main/resources/META-INF/resources/primefaces/inputswitch/inputswitch.js#L16

**renderDeferred** is called twice:
1. When the component is rendered the first time.
2. After the dialog update.

The **_render** function is called twice when it should be called only one time. To avoid this problem we could use the dialog property **dynamic=true** or add the refresh function in DeferredWidget to remove the deferred renders before initialize the component again:
```
PrimeFaces.widget.DeferredWidget = PrimeFaces.widget.BaseWidget.extend({
        //@Override
        refresh: function(cfg) {
            PrimeFaces.removeDeferredRenders(this.id);

            this._super(cfg);
        },
        
});
```

I think this problem should be taken into account if this component is not going to be deprecated.

**Comment by melloware** [comment]
I am still not quite sure why this component needs to be a deferred renderer at all?

**Comment by cagataycivici** [comment]
Please use toggle switch, inputSwitch is deprecated.
