### ISSUE TITLE
DataTable: stickyHeader + multiple selection makes "Select All" inactive

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#3971]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? yes
- Does it work on the newest sources in GitHub? no
- Application server + version: wildfly
- Affected browsers:

## 2) Expected behavior
it should be toggleable.

## 3) Actual behavior

checkbox is always disabled if stickyHeader = true

## 5) Sample Project

https://github.com/erickdeoliveiraleal/primefaces-test/tree/selectModeMultiple

**Comment by tandraschko** [comment]
PR would be great.

**Comment by Rapster** [comment]
I can reproduce it on the showcase, once sticky header showing up, the checkbox is working

**Comment by Rapster** [comment]
This one is a regression as it's working on 6.2 

**UPDATE**
Not sure actually, I tried on my company app and the app is runnning under 6.2 but we overrided setupStickyHeader so the sticky contains columns header and paginator, so the bug could be there from the start

**Comment by mertsincan** [comment]
Related to https://github.com/primefaces/primefaces/issues/4469
