### ISSUE TITLE
AutoComplete: In TreeTable calls onCellEdit twice

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#3972]
## 1) Environment
PF versions: All, AppServer: WildFly 11 / JEE7, All browsers

## 2) Expected behavior
_onCellEdit_ should be called at most once on change (like _p:dataTable_).

## 3) Actual behavior
_onCellEdit_ called twice on change and once for no change (both wrong).

## 4) Steps to reproduce
1. Click in the first cell (the _treeTable_) and type any char. ("one, two"-selection appears)
1. _&lt;Return&gt;_ to select "one"
1. The console shows, that _onCellEdit_ was called twice (as the value changed)
1. Repeat step 1 and 2  (this time _onCellEdit_ is only called once as the value didn't change)

In the second row (the _dataTable_) you can reproduce, that the _dataTable_ only calls _onCellEdit_ once, when the value changed, otherwise it's not called at all. Using _p:inputText_ instead of _p:autocomplete_ avoids the problem. Note that additionally, _event.oldValue_ and _event.newValue_ are both null, which should also be fixed.

## 5) Sample XHTML
``` html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	      xmlns:f="http://xmlns.jcp.org/jsf/core"   xmlns:p="http://primefaces.org/ui">
<h:head/>
<h:body>
  <h:form>
    <p:treeTable value="#{app.createTreeNode()}" var="v" editMode="cell" editable="true">
      <p:ajax event="cellEdit" listener="#{bean.onCellEdit}"/>
      <p:columns var="c" value="#{[0,1]}">
        <p:cellEditor>
          <f:facet name="input">
            <p:autoComplete value="test" completeMethod="#{bean.complete}" />
          </f:facet>
          <f:facet name="output">#{c}</f:facet>
        </p:cellEditor>
      </p:columns>
    </p:treeTable>
    <p:dataTable value="#{[0]}" var="v" editMode="cell" editable="true">
      <p:ajax event="cellEdit" listener="#{bean.onCellEdit}" />
      <p:columns var="c" value="#{[0,1]}">
        <p:cellEditor>
          <f:facet name="input">
            <p:autoComplete value="test" completeMethod="#{bean.complete}" />
          </f:facet>
          <f:facet name="output">#{c}</f:facet>
        </p:cellEditor>
      </p:columns>
    </p:dataTable>
  </h:form>
</h:body>
</html>
```
## 6) Sample bean
``` java
@ApplicationScoped @Named
public class Bean {
  public TreeNode createTreeNode() {
    DefaultTreeNode root = new DefaultTreeNode();
      new DefaultTreeNode(null, root);
      return root;
  }
  public void onCellEdit(CellEditEvent e) {
    System.out.format("onCellEdit: old=%s, new=%s%n", e.getOldValue(), e.getNewValue());
  }
  public List<String> complete(String query) {
    return new ArrayList<>(Arrays.asList("one", "two"));
  }
}
```

**Comment by mdzaebel** [comment]
Here is a workaround: 

add `<p:ajax event="itemSelect" listener="#{bean.onItemSelect}"/>` inside your p:autoComplete:

Add following to your _viewScoped_ bean:

``` java
/** Whether onCellEdit for treeTable should be executed */
boolean onCellEdit;

public void onCellEdit(CellEditEvent e) {
  if(onCellEdit=!onCellEdit) return; //work around https://github.com/primefaces/primefaces/issues/3972
  // business logic ...
}
public void onItemSelect(SelectEvent e) {
  onCellEdit=false;
}
```

As the _p:autoComple_-Listener triggers _onItemSelect_ before _onCellEdit_, it sets _onCellEdit_ toggle to false, as the first call to _onCellEdit_ should be skipped. In _onCellEdit_, the flag is toggled, so the next call is really executed. The workaround ensures, that the business logic is only called once if necesssary (for new values).

Keep in mind, that this method has to be used up to at least PF6.2. Look for fixes on new PF releases.

**Comment by melloware** [comment]
Closing this as its related to issue: https://github.com/primefaces/primefaces/issues/5639 around TreeTable with dynamic columns and cell editing.
