### ISSUE TITLE
[Documentation] Type documentation & defaults inconsistent

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#3973]
## 1) Environment
PF versions: All, AppServer: WildFly 11 / JEE7, All browsers

## 2) Expected behavior
Types should be correctly documented

## 3) Actual behavior
Types and default values are inconsistent on 3 occurences. As Boolean.valueOf(null) is false, it's not really wrong but inconsistent with other notations in the guide.

## 4) Steps to reproduce
In the User Guide (PDF), look at "null boolean"
 - First occurence is _p:autoComplete_ with "_multiple_", Default=**null** (should be false), Type=Boolean
 - Next occurrence is _p:commandLink_ with "_disabled_" (same problem as above)
 - Next occurence is _p:tab_ with "_title_", Default=null, Type=**Boolean** (should be String)

**Comment by Rapster** [comment]
@tandraschko can't we make the documentation available on Github?

**Comment by tandraschko** [comment]
thats up to PrimeTek
Cagatay said ~1 year ago then is he looking for a way to make it editable from the community
will ping him again

**Comment by Rapster** [comment]
It's not a word document?

**Comment by tandraschko** [comment]
i don't know.
