### ISSUE TITLE
PickList : Filters not seems on california template

### ISSUE THREAD

**Issue by talipkorkmaz** [primefaces/primefaces#3974]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: Spring Boot Embedded Tomcat
- Affected browsers: Chrome

## 2) Expected behavior
Picklist source and target filters should be seem

## 3) Actual behavior
Not appearing.

## 4) Steps to reproduce
@ https://www.primefaces.org/california/data.xhtml 
Picklist card has already this bug.

## 5) Sample XHTML
                        
`<p:pickList id="pickList" value="#{pickListView.cities}" var="cities" itemLabel="#{cities}" itemValue="#{cities}" 
                                    showSourceControls="true" showTargetControls="true" showSourceFilter="true" showTargetFilter="true" responsive="true">
                            <f:facet name="sourceCaption">From</f:facet>
                            <f:facet name="targetCaption">To</f:facet>
                        </p:pickList>`

**Comment by mertsincan** [comment]
I'll work on this issue and get back to you. Also, at next time please use california forum; https://forum.primefaces.org/viewforum.php?f=79

**Comment by Rapster** [comment]
Not related to PF. Use forum as Mert suggested

**Comment by talipkorkmaz** [comment]
ok i opened an issue at forum. waiting for fix. thanks in advance.
