### ISSUE TITLE
Chart: BarChartSeries doesn't take axes parameters into account

### ISSUE THREAD

**Issue by giltal1** [primefaces/primefaces#3976]
## 1) Environment
PrimeFaces version: 6.2

## 2) Expected behavior
Once x and y axes are set in BarChartSeries, expect to be reflected in the chart

## 3) Actual behavior
BarChartSeries does not take x and y axes parameters into account when render.

## 4) Code to fix
highlighted code need to be added:
BarChartSeries.java
...
public void encode(Writer writer) throws IOException {
		**AxisType xaxis = this.getXaxis();
		AxisType yaxis = this.getYaxis();**
		writer.write("{");
		writer.write("label:\"" + ComponentUtils.escapeText(this.getLabel()) + "\"");
		writer.write(",renderer: $.jqplot." + this.getRenderer());
		**if (xaxis != null) {
			writer.write(",xaxis:\"" + xaxis + "\"");
		}
		if (yaxis != null) {
			writer.write(",yaxis:\"" + yaxis + "\"");
		}**
		if (this.disableStack) {
			writer.write(",disableStack:true");
		}
		writer.write("}");
	}

**Comment by tandraschko** [comment]
Would be great if you can provide a PR to fix it.

**Comment by melloware** [comment]
I will submit this PR shortly.
