### ISSUE TITLE
Setup sonarcloud

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3980]
Now there is no longer generated code, it'll be easier to have a fair idea about quality code

**Comment by tandraschko** [comment]
JFYI: the build fails now

**Comment by Rapster** [comment]
I know, I'm having a look right now

**Comment by tandraschko** [comment]
Should we revert it for now or can you fix it today?

**Comment by Rapster** [comment]
@melloware do you see anything wrong with the config of sonarcloud in .travis.yml file? I can't make it work for some reason

**Comment by melloware** [comment]
It looks OK to me.  the last time when we did this for Extensions the whole issue was around the organization and encrypted key being wrong.

**Comment by Rapster** [comment]
I disabled the rule `Constant names should comply with a naming convention` because PropertyKeys are indeed following the convention, but since it's by convention in JSF. I decided to disable to get rid of these errors

**Comment by Rapster** [comment]
BTW, why are we skipping tests in the first instructions and mvn test right after?
```
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
# add --update-snapshots if snapshots are used
- mvn test verify --batch-mode
```

While we could execute tests with mvn install?

**Comment by jxmai** [comment]
Maybe it was leftover from v1 (https://github.com/primefaces/primefaces/commit/67b2386e067ba80f399ae32390babcd86d8d8609#diff-354f30a63fb0907d4ad57269548329e3) ? @krichter722 please chime in if you have different opinions.   I think it is Ok to use one line to execute install and test.

**Comment by krichter722** [comment]
@Rapster This is the standard Travis approach whose idea it is to detect compilation issues quicker if the project is split into different subprojects than if tests are run between the compilation of each subproject. It doesn't apply to Primefaces because it has no subprojects and this separation can be removed.

**Comment by Rapster** [comment]
Okay I'll change that

**Comment by Rapster** [comment]
Hi @primefaces/committers ,

You may have realized the quality gate is failing, it's because a few regressions has been introduced lately. I think it's important from now on to keep quality code stable as the technical debt is already big

To be notified of any new issues, please:

1. sign in on SonarCloud with their github account
2. from there, I'll be able to add you as member
3. you'll be able to manage the notifications you want to receive here: https://sonarcloud.io/account/notifications

Sonarcloud errors found are quite justified, so please sign in to SonarCloud :wink:

**Comment by tandraschko** [comment]
over 50% of the bugs/vulnerabilities can't be marked as "won't fix" - i just need the admin rights for this

I don't care about other stuff like "remove unncessary" cast - they are just nice to have.

**Comment by Rapster** [comment]
I just add you as owner, you should have the rights now. Before setting anything to "Won't fix", I'd rather discuss it here or gitter. Things like "remove unncessary cast" are low priority but we still need to get rid of these as it is code cumbersome.

**Comment by tandraschko** [comment]
take for example:
https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&open=AWWwlygulgbYnohYUhGZ&resolved=false&types=BUG

we have many of them but a NPE would only occur if the request params are modified or there is a big bug (js and server side event doesn't match)
You could of course add a custom exception + message but this case should never occur in "real life"

**Comment by Rapster** [comment]
I understand what you're saying, but every classes should be agnostic to whatever you mentionned. No matter what the input is, proper check (like throwing exception in case event is not supported) needs to be made

**Comment by tandraschko** [comment]
yep, it would be nicer of course. But i won't handle it as bug, this are just cosmetics for me.

**Comment by Rapster** [comment]
Please @mertsincan don't forget to sign in, since you're doing a lot of commits I think it's important that you're notified in case of regressions

**Comment by tandraschko** [comment]
@Rapster we should definitliy disable the following rules:
- S1192; i don't think we will ever replace all e.g. "disabled" by HTML.DISABLED
- S1066; sometimes it's better to seperate for readability, thats up to the developer imo
- S1172; sometimes it's required by the impl, not in the base method. I think the check is to hard.

**Comment by Rapster** [comment]
I'll have a look after I come back from vacation :wink:

**Comment by Rapster** [comment]
How do your search for a squid in sonarcloud? I'd like to see some examples

**Comment by Rapster** [comment]
I got it :wink:

**Comment by Rapster** [comment]
I can't find issues related to these squids (maybe you disabled them?) But my guess is:

- S1192: Yes indeed... I would have love to see a HTML fluent builder to avoid that kind of problem (like https://github.com/xmlet/HtmlApi)

- S1066: I see what you mean, unfortenaly I don't see a concrete example, so hard to tell... But a good formatting should simplify the readibility (to meditate as it's not 100% true)

- S1172: If the method has `@Override` annotation it should not complain. Is the real problem is a missing `@Override`?
