### ISSUE TITLE
Static message (admonition)

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#3981]
In my apps (forms) I put some instructions and explain behavior behind some actions. I put them into notes, tips or warnings. I prefer have them emphasized, similarly like messages. As there is not a dedicated element, I am pasting the p:message HTML code directly to the JSF page:

```html
<div class="ui-messages ui-widget">
    <div class="ui-messages-info ui-corner-all">
        <span class="ui-messages-info-icon"></span>
        <ul><li><span class="ui-messages-info-summary">Note</span><span class="ui-messages-info-detail">This is my note.</span></li></ul>
    </div>
</div>
```

With a dedicated element (with 4 supported types, same as messages) my code would be much cleaner:
```
<p:admonition type="info" title="Note" detail="This is my note."/>
```

**Comment by melloware** [comment]
Can you post a screenshot of this code in use so I can see what it looks like?  I am just trying to figure out your use case.

**Comment by tandraschko** [comment]
I tried to put this in PF some years ago but PF declined: https://code.google.com/archive/p/primefaces/issues/7404
Maybe you can create a issue and implementation for PF Extensions.

**Comment by melloware** [comment]
@tandraschko I like this idea to move it to Extensions.  Is the source still in GitHub somewhere or did it never get moved over from Google Code?  I would like to look at your code and use that for the Extension.

I just created this ticket over at PFE: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/608

**Comment by tandraschko** [comment]
see: https://github.com/primefaces/primefaces/issues/4258
