### ISSUE TITLE
SelectOneMenu: Escaped quotes cause an error on 6.2+

### ISSUE THREAD

**Issue by stevebeatty** [primefaces/primefaces#3982]
## 1) Environment
- PrimeFaces version: 6.2.8
- Works in Primefaces 6.2 & primefaces-test
- Application server + version: TomEE 7.0.5
- Affected browsers: Chrome, Firefox, IE

## 2) Expected behavior

Escaped quotes should display

## 3) Actual behavior

jQuery throws an error to the console:
_Error: Syntax error, unrecognized expression: [data-label=""I'm quoted""]_

## 4) Steps to reproduce

Add the following to any page

## 5) Sample XHTML

```
<p:selectOneMenu>
	<f:selectItem itemLabel="&quot;I'm quoted&quot;" />
</p:selectOneMenu>
```

## 6) Sample bean

Not needed

**Comment by melloware** [comment]
Please also add the error you are getting in the description.

**Comment by melloware** [comment]
Attached is my PF test case.  I can't reproduce using 6.2 or 6.3-SNAPSHOT.

[primefaces-3982.zip](https://github.com/primefaces/primefaces/files/2311671/primefaces-3982.zip)

Run `mvn clean jetty:run' and navigate to http://localhost:8080/primefaces-test/test.xhtml to test.

Could be something introduced in between 6.2 and 6.2.8 but not in 6.3-SNAPSHOT?

**Comment by stevebeatty** [comment]
I think it is a regression due to some release in between 6.2 and 6.2.8.  In the environment section I noted that the behavior wasn't there in 6.2 or primefaces-test (which uses 6.2) and your test case also runs correctly.  I tried some older releases and the error is there in 6.2.3 but not in 6.2.1.

**Comment by melloware** [comment]
Looks like it might be related to this fix: https://github.com/primefaces/primefaces/issues/3547

**Comment by tandraschko** [comment]
can you check that @mertsincan ?

**Comment by mertsincan** [comment]
Fixed now.
