### ISSUE TITLE
OutputLabel: add support for @AssertTrue

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#3986]
## 1) Environment
- PrimeFaces version: all

## 2) Expected behavior
Right now, the `indicateRequired="true"` attribute of `p:outputLabel` considers `@NotNull`, `@NotEmpty` and `@NotBlank` annotations. I think it should cover also the [`@AssertTrue`](https://docs.jboss.org/hibernate/beanvalidation/spec/1.1/api/javax/validation/constraints/AssertTrue.html) annotation. e.g.: A checkbox with the label "Do you accept terms and conditions?".

PR coming.

**Comment by tandraschko** [comment]
Thanks for the PR, i enhaced it by an "instance of".
