### ISSUE TITLE
DataTable: resizeMode="expand" support of table min-width.

### ISSUE THREAD

**Issue by Dasister** [primefaces/primefaces#3987]
## 1) Environment
- **PrimeFaces version:** 6.1
- **Does it work on the newest released PrimeFaces version? Version?** No, it doesn't.
- **Does it work on the newest sources in GitHub?** No.
- **Application server + version:** Wildfly 10.1
- **Affected browsers:** Chrome, Firefox, IE9+, Edge.

## 2) Expected behavior

When a user tries to reduce the size of a column (and if it will lead to overall table width less than min-width value), only two columns should be resized. (like in "fit" mode)

## 3) Actual behavior

All columns are resized.

## 4) Steps to reproduce

Navigate to test.xhtml and reduce size of any column.

## 5) Sample XHTML

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h2>resizeMode="expand"</h2>
        <p:dataTable id="datatable" resizableColumns="true" resizeMode="expand" tableStyle="min-width: 100%;">
            <p:column headerText="Column 1"/>
            <p:column headerText="Column 2"/>
            <p:column headerText="Column 3"/>
            <p:column headerText="Column 4"/>
            <p:column headerText="Column 5"/>
            <p:column headerText="Column 6"/>
            <p:column headerText="Column 7"/>
            <p:column headerText="Column 8"/>
            <p:column headerText="Column 9"/>
        </p:dataTable>

        <h2>resizeMode="fit"</h2>
        <p:dataTable id="datatable_fit" resizableColumns="true" resizeMode="fit" tableStyle="min-width: 100%;">
            <p:column headerText="Column 1"/>
            <p:column headerText="Column 2"/>
            <p:column headerText="Column 3"/>
            <p:column headerText="Column 4"/>
            <p:column headerText="Column 5"/>
            <p:column headerText="Column 6"/>
            <p:column headerText="Column 7"/>
            <p:column headerText="Column 8"/>
            <p:column headerText="Column 9"/>
        </p:dataTable>

    </h:body>
</html>

## 6) Sample bean

Not necessary

**Comment by melloware** [comment]
@Dasister I created a Test application you can run with "mvn clean jetty:run-exploded".  I can't reproduce your issue.  The Table always stays width 100%?  This is using 6.3-SNAPSHOT so its possible its fixed.

[pf-3987.zip](https://github.com/primefaces/primefaces/files/2673816/pf-3987.zip)

**Comment by Dasister** [comment]
Sorry for late reply.
Reproduced on PrimeFaces 7.0.

I've recorded what I've meant:
![resizeMode](https://user-images.githubusercontent.com/1691753/66120842-792ff100-e5e4-11e9-8237-0b3a21a331d4.gif)
As you can see all columns are resized in table with resizeMode="expand" set. And only two columns are resized on second case.

@melloware could you please check this out?

**Comment by melloware** [comment]
OK that helps explain what you mean I thought you meant the table width came in its just the columns get misaligned the table still stays at 100% width. I have removed the can't replicate label
