### ISSUE TITLE
Autocomplete alignment issue with multiple mode

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primefaces#399]
The autocomplete display panel is not aligned properly with the input element.The left and top positions need to be adjusted to make it similar to the other autocomplete types.

![image](https://cloud.githubusercontent.com/assets/3127317/7976176/5477fdaa-0a95-11e5-8a8b-6d1bda28261f.png)

**Comment by cagataycivici** [comment]
Will check this, thanks.
