### ISSUE TITLE
Password: Improve validity strength

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#3990]
Since password has been introduced into PF, password security has changed. Length is no longer a valid criteria to mesure password strength. OWASP made a definition of what a strong password should be: https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Implement_Proper_Password_Strength_Controls

I'm quoting:
```
Implement Proper Password Strength Controls
A key concern when using passwords for authentication is password strength. A "strong" password policy makes it difficult or even improbable for one to guess the password through either manual or automated means. The following characteristics define a strong password:

Password Length
Longer passwords provide a greater combination of characters and consequently make it more difficult for an attacker to guess.

Minimum length of the passwords should be enforced by the application.
Passwords shorter than 10 characters are considered to be weak (NIST SP800-132).
While minimum length enforcement may cause problems with memorizing passwords among some users, applications should encourage them to set passphrases (sentences or combination of words) that can be much longer than typical passwords and yet much easier to remember.

Maximum password length should not be set too low, as it will prevent users from creating passphrases. Typical maximum length is 128 characters.
Passphrases shorter than 20 characters are usually considered weak if they only consist of lower case Latin characters.
Password Complexity
Applications should enforce password complexity rules to discourage easy to guess passwords. Password mechanisms should allow virtually any character the user can type to be part of their password, including the space character. Passwords should, obviously, be case sensitive in order to increase their complexity. Occasionally, we find systems where passwords aren't case sensitive, frequently due to legacy system issues like old mainframes that didn't have case sensitive passwords.

The password change mechanism should require a minimum level of complexity that makes sense for the application and its user population. For example:

Password must meet at least 3 out of the following 4 complexity rules
at least 1 uppercase character (A-Z)
at least 1 lowercase character (a-z)
at least 1 digit (0-9)
at least 1 special character (punctuation) — do not forget to treat space as special characters too
at least 10 characters
at most 128 characters
not more than 2 identical characters in a row (e.g., 111 not allowed)
```

Fortunately, there is a pretty good library doing those tests. It also contains his own "weak password dictionnary" (they are obviously in english) but extra dictionnary can be added. See https://github.com/dropbox/zxcvbn

~~Another point from OWASP, and I think it could be hande by the component itself, is to assess the distance between two passwords, as it is stated: "Require a minimum topology change between old and new passwords". Levenshtein algorithm could be used (https://en.wikipedia.org/wiki/Levenshtein_distance, existing algorithm are out there already)~~

To conclude, two features:
- [X] Feedbacks should no longer be based on PF current algo but zxcvbn's
- [ ] Support extra dictionnary

@cnsgithub WDYT?

**Comment by melloware** [comment]
This would be an improvement.  Every time I use the password component I override the JS and implement my own stronger algorithm than the PF default one using the JS override method.

https://forum.primefaces.org/viewtopic.php?p=109513#p109513

**Comment by Rapster** [comment]
I dropped the last point, since I don't think it should be a built-in feature in PF. A simple validator can be created and in that case Levenshtein algorithm is implemented in apache commons-text. Unless you think it should be there?

**Comment by Rapster** [comment]
@tandraschko I want to give the possibility to make the validation fail (depending what the dev configured) if the password is too weak. How should I proceed? Register an ajax event and write the value into a state holder?

**Comment by tandraschko** [comment]
what do you mean exactly?
The submitted value is set in submittedValue, so it's already there
you just have to attach a validator or overwrite #validate

**Comment by Rapster** [comment]
I want to retrieve the value from zxcvbn. The user can define a property (e.g failedOn="weak") and depending what the score is (from zxcvbn) I want validation to fail. submittedValue will contain the password. Basically at the end, I want to be able to retrieve the score when `isValid` is called

**Comment by tandraschko** [comment]
I would not trust a value from the client in case of validation, so the best way is to rebuild the score-logic on server

**Comment by Rapster** [comment]
I agree, I just figured since the value has been computed, why not reuse it for validation. I think it's quite handy

**Comment by Rapster** [comment]
Thomas, I want to give the possibility to add an extra dictionnary for this feature (see here https://github.com/dropbox/zxcvbn#usage). I would like to do that just like we do with calendar and the locales. Can I create something like `PrimeFaces.passwords` in core.js?

**Comment by cnsgithub** [comment]
`zxcvbn` is several hundred kilobytes (minified+gzipped). We should consider the [performance section](https://github.com/dropbox/zxcvbn#performance) carefully. Especially for mobile this might be a performance loss?

**Comment by cnsgithub** [comment]
Please also consider this interesting discussion: [How much does knowing the zxcvbn password strength help an attacker?](https://security.stackexchange.com/questions/92512/how-much-does-knowing-the-zxcvbn-password-strength-help-an-attacker)

**Comment by tandraschko** [comment]
As i already said, everything on the Client is just a nice gimmick. Only something on the server side gives a real value.

**Comment by cnsgithub** [comment]
There is a Java version as well: https://github.com/GoSimpleLLC/nbvcxz

**Comment by Rapster** [comment]
> As i already said, everything on the Client is just a nice gimmick. Only something on the server side gives a real value.

That's exactly the purpose of this issue, a nice gimmick, have a better feedback on the complexity of the password. Basically the idea is to improve DataTable#testStrength as the current is no longer valid. 

As Thomas said, at the end, complexity has to tested on business-layer side, so no need of https://github.com/GoSimpleLLC/nbvcxz

**Comment by cnsgithub** [comment]
> I want to give the possibility to make the validation fail (depending what the dev configured) if the password is too weak.

If you wanna make the validation fail, it should be repeated on the server side as well, otherwise it can be bypassed, same as other issues regarding _lack of user input validation_.

If you do it on the client side, please consider my [previous comment](https://github.com/primefaces/primefaces/issues/3990#issuecomment-446838558). You'll disclose the password strength secret and make brute forcing less difficult for attackers.

> As Thomas said, at the end, complexity has to tested on business-layer side, so no need of https://github.com/GoSimpleLLC/nbvcxz

In my opinion and taking into account what I've mentioned before (mobile script load latency + security) I would recommend to implement it as fat-server/thin-client solution, i.e. strength validation logic on the server side only, just the feedback on the client side.

I know that's far beyond from just changing the `testStrength` JS function. However, doing it this way would be a real improvement.

**Comment by mauromol** [comment]
I'm a bit lost after these comments, but I think that the original report explains well where PF should really improve, at least the first check box: "Feedbacks should no longer be based on PF current algo".

I mean, right now "1234567" is considered a "good password", but I don't quite think so ;-)

Apart from this, I think proper custom validation is still required if specific needs are required for the input password. PF may help and improve on this area too, of course, but I think these are two different problems.

**Comment by Rapster** [comment]
Since validation should be done server side. There is no need to use a tiers library, though, feedback of PF is outdated, as you said "1234567" is considered a "good password"... I think PF should slightly improve this

**Comment by melloware** [comment]
Since we decided that all real validation should happen in your app i updated the JS to give better feedback than the current implementation.  Must be at least 8 characters and contain any 3 of 4 categories of number, uppercase letter, lowercase letter, or special character.  Its what we use at a couple of my clients.
