### ISSUE TITLE
SelectManyMenu: Filtered Item Selection

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#3992]
In my app I'd like to change the default selection strategy when filter is updated.

I primarily miss the **onFilterUpdate** event in client side API.

Then I would be grateful for two new methods:
- clearSelection() - clears the selection. If selectManyMenu is combined with the filter and some items are selected, these are still selected after updating the filter value, even they disappear from the list. It is confusing and even reported as a bug in my app.

- selectAllFiltered() - clears the previous selection and then select all filtered items. Handy if you need select everything in the filtered list (selectAll() selects also invisible items).

**Comment by melloware** [comment]
@jan-tosovsky-cz I just submitted a PR where the normal `selectAll` `unselectAll` will only select and unselect the items currently filtered.  This is the correct UI/UX behavior for these widget methods.

So if you filter down to 3 items and so `selectAll` it will select those 3 items not the other 97 in the list.  If you then unfilter only those 3 will be selected.
