### ISSUE TITLE
Menu: Not placed correctly when a parent tag is relative

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#3993]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Yes Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
The menu panel should be placed correctly, under the component that triggers it.

## 3) Actual behavior
The menu panel is not placed correctly.

## 4) Steps to reproduce
We should build the source of primefaces 6.3-SNAPSHOT, place the component inside a tag with a relative position.

## 5) Sample XHTML
Taken from primefaces showcase.

```
<div style="position: relative;">
    <h3>Overlay</h3>
    <p:commandButton id="dynaButton" value="Show" type="button" icon="ui-icon-extlink"/>
    <p:menu overlay="true" trigger="dynaButton" my="left top" at="left bottom">
        <p:submenu label="Ajax">
            <p:menuitem value="Save" actionListener="#{menuView.save}" update="messages" icon="ui-icon-disk"/>
            <p:menuitem value="Update" actionListener="#{menuView.update}" update="messages" icon="ui-icon-arrowrefresh-1-w"/>
        </p:submenu>
        <p:submenu label="Non-Ajax">
            <p:menuitem value="Delete" actionListener="#{menuView.delete}" update="messages" ajax="false" icon="ui-icon-close"/>
        </p:submenu>
        <p:submenu label="Navigations">
            <p:menuitem value="External" url="http://www.primefaces.org" icon="ui-icon-home"/>
            <p:menuitem value="Internal" icon="ui-icon-star"/>
        </p:submenu>
    </p:menu>
</div>
```
## 6) Sample bean
I tested this issue using the showcase.

-------------------------------------
The problem was created because the menu panel in PF 6.3-SNAPSHOT is not added in the BODY like PF 6.2 does. The commit related is:
- [bea2ca14e8224e0590035d4d85a9100400faa7d0](https://github.com/primefaces/primefaces/commit/bea2ca14e8224e0590035d4d85a9100400faa7d0#commitcomment-30288784)

The next link explains that the jquery.position() function has problems placing relatively a hidden tag:
- https://stackoverflow.com/a/12902195

A solution could be show the component before calculate its position or don't use **display** to show/hide the panel.

**Comment by tandraschko** [comment]
please try it again

**Comment by wsaca** [comment]
Now its working... Thank you... :thumbsup:
