### ISSUE TITLE
OpenStreetMap Support for Map Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#40]
Consider adding OpenStreetMap implementation in addition to Google Maps.

**Comment by NoFr1ends** [comment]
What about OpenLayers 3 and keep open for other maps too?

**Comment by marcusfey** [comment]
Is this any hope for this feature request to get implemented?

**Comment by erickdeoliveiraleal** [comment]
reference: https://github.com/themrleon/JSF2Leaf

**Comment by marcusfey** [comment]
I know this exist, but that last development was 3 years ago thus I fear it will get outdated over time...

**Comment by melloware** [comment]
If one of the developers doesn't want to tackle this in their free time this is mostly likely a PrimeFaces PRO request to get implemented.   If your company wants to sponsor it if they truly need this functionality it might be the only way it gets implemented.

**Comment by melloware** [comment]
I am closing this ticket as I have opened a PrimeFaces Extensions issue where a new component like this can incubate.

**Comment by melloware** [comment]
OpenStreeMap will be in Extensions 14.0.1: https://github.com/primefaces-extensions/primefaces-extensions/issues/128
