### ISSUE TITLE
ContextMenu: support touch events

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#4000]
## 1) Environment
- PrimeFaces version: **6.2.8**
- Does it work on the newest released PrimeFaces version? **No** Version? **6.2.8**
- Does it work on the newest sources in GitHub? (Build by source ->**not tested because no commit related to that**
- Application server + version: **Payara 5.182**
- Affected browsers: **all**

## 2) Expected behavior

**When pressing long time on the screen the contectmenu should popup**

## 3) Actual behavior

**When pressing long time on the screen default context of ios shows up.**

## 4) Steps to reproduce

**Showcase Datatable ContextMenu example with ios and press long time inside the table** 

## 5) Sample XHTML

**not needed**

## 6) Sample bean

**not needed**

**Comment by tandraschko** [comment]
PR is very welcome

**Comment by tandraschko** [comment]
You could probably workaround it by setting the event to touchstart or something

**Comment by markusg80** [comment]
maybe you can use longtouch jquery plugin. Im not so experienced with developing jsf components.

**Comment by tandraschko** [comment]
JFYI:
this issue tracker is for the community and you have 3 ways to get something fixed or implemented:
1) do it by yourself and provide a PR
2) wait until someone other (including PrimeTek) implements it
3) sponsor it via PrimeFaces PRO

**Comment by markusg80** [comment]
@cagataycivici  Primefaces is replacing Primefaces Mobile in favor of responsive components. For me this is the right decision. But now it would be great when moblie devices like iphones or other android devices will be fully supported. For example the ContextMenu is really helpfull if on a small screen all the tool components wrapping down and the datatable is at the end. Now aftewr select row on datatable you have to scroll up agein for tool button. With contextMenu you dont have to scroll up!
