### ISSUE TITLE
Ultima Rightpanelmenu: When click inside selecetCheckboxMenu Popup Rightmenu Panel disappears

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#4001]
## 1) Environment
- PrimeFaces version: **6.2.8 Ultima 1.1.3**
- Does it work on the newest released PrimeFaces version? **No** Version? **1.1.3**
- Does it work on the newest sources in GitHub? (Build by source -> **No**
- Application server + version: **Payara 5.182**
- Affected browsers: **all**

## 2) Expected behavior

**When on SelectCheckboxMenu Popup inside the Rightpanel Menu something is selected or deselected the Rightpanel Menu keeps showing up.** 

## 3) Actual behavior

**When on SelectCheckboxMenu Popup inside the Rightpanel Menu something is selected or deselected the Rightpanel Menu disappears.** 

## 4) Steps to reproduce

add selectCheckboxMenu to Rightpanel Menu and open popup and (de)select something

## 5) Sample XHTML

**not needed**

## 6) Sample bean

**not needed**

## 7) Other Components affected

**SelectOneMenu**

**Comment by markusg80** [comment]
It is caused because of this code in layout.js:

`if(!$this.rightPanelClick && !$this.rightPanelButtonClick && $this.rightPanel.hasClass('layout-rightpanel-active'))  {
     $this.rightPanel.removeClass('layout-rightpanel-active');
     $this.rightPanelButton.removeClass('rightpanel-btn-active');
}`

**Comment by tandraschko** [comment]
Use the ultima forum pls, this issue tracker is only for PrimeFaces Core.

**Comment by markusg80** [comment]
i already used the ultima forum but no answer:

https://forum.primefaces.org/viewtopic.php?f=42&t=56707

Maybe exist an issue tracker for Ultima?

**Comment by tandraschko** [comment]
Don't think so. AFAIK layout problems are handled in the forum. But i don't work for PrimeTek ;)

**Comment by markusg80** [comment]
Ok now what i have to do if noone responds on forum? Should i tag Catagay? ;-) Or can u give the Link to someone? And thx for your responding!

**Comment by tandraschko** [comment]
Tag cagatay doesnt change anything probably ;)
Wait for response on the forum or write a mail to PrimeTek.
