### ISSUE TITLE
Schedule: Missing height attribute

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#4002]
## 1) Environment
- PrimeFaces version: 6.2.8
- Does it work on the newest released PrimeFaces version? No Version? 6.2.8
- Does it work on the newest sources in GitHub? (Build by source ->No
- Application server + version: Payara 5.182
- Affected browsers: all

## 2) Expected behavior

it should be possible to set the schedule height either with an attribute or with javascript. Best both!

## 3) Actual behavior

Height is only settable throgh th extender and it work not well

## 4) Steps to reproduce

--

## 5) Sample XHTML

..

## 6) Sample bean

..

## 7) Code to Workaround the Problem

i like to workaround the Problem with the extender functionality. this is the called js function:

```javascript 
function resizeExmanSchedule() {
    var windowsHeight = $(window).height();
    var topPanelHeight = $( '.topbar-right' ).outerHeight();
    var controlsHeight = $('#timeform\\:timegrid').outerHeight();
    var tabNavHeight = $('#timeform\\:timetab .ui-tabs-nav').outerHeight();
    
    var scheduleHeight = windowsHeight - topPanelHeight - controlsHeight - tabNavHeight - 90;
    
    if (scheduleHeight < 400) {
        scheduleHeight = 400;
    }
    this.cfg.contentHeight = scheduleHeight;
    console.log(this);
}
```

This function successfully resizes the height but on the browser console i get always those error:

> Uncaught TypeError: Cannot set property 'contentHeight' of undefined

**Comment by tandraschko** [comment]
what about style=height: 400px e.g.?

**Comment by markusg80** [comment]
**The css height attribute doesn't work!**
But exactly in this moment i solved the problem with the extender function like this:
```xhtml
<p:schedule id="reservationschedule"
                    value="#{exerciseTimeBean.reservationLazyModel}" 
                    extender="resizeExmanSchedule" />
```

and js:

```javascript 
function resizeExmanSchedule() {
    this.cfg = $.extend(true, this.cfg, {
        contentHeight: scheduleHeight
    });
    this.cfg.eventRender = function(event, element, view){
        element.find('.fc-title').append("<p>" + event.description + "</p>");
    };
}
```

important is to set porpertie contentHeight.

**Comment by tandraschko** [comment]
OK, then lets close it.
The extender should be used for many cases instead of introducing yet-another-schedule-attribute.

**Comment by markusg80** [comment]
Yes its ok to use the extender! But it is very important to better document it, because it was very hard to find out how to use it! I know you already have a issue for this with 6.3 Documentation ;-)
