### ISSUE TITLE
setStyleClass of event in schedule not working in PF 6.1

### ISSUE THREAD

**Issue by YahiaZZ** [primefaces/primefaces#4003]
## 1) Environment
- PrimeFaces version:
- 6.1
- Application server + version: Apache Tomcat
- Affected browsers: FireFox, GoogleChrome, IE

## 2) Expected behavior
Change the background color of events depending on value from database in bean

## 3) Actual behavior
Nothing happens, the background color not changed

## 5) Sample XHTML

```
<style type="text/css"> 
        .myStyle .fc .fc-event {
            background-color: #{timetableView.eventStyle} !important;
         }
</style>
```

## 6) Sample bean
```
eventStyle="#785211";
event.setTitle("title");
event.setStyleClass("myStyle");
eventModel.addEvent(event);

```

**Comment by tandraschko** [comment]
please use the forum first, this is not a reproducable issue as a runnable example is missing.
Check if the styleclass is added via firebug and then check your selector.

**Comment by YahiaZZ** [comment]
Thanks @tandraschko  for your answer,
I searched first in form but I did'nt find the solution
the styleclass  is added , but nothing happens, when i do it with static value, it works

**Comment by tandraschko** [comment]
I see but thats probably just an issue, how you exactly use the css and selectors probably. For such things, a forum is the best place to check your case exactly and if this is a bug or just a little bit wrong usage.

**Comment by YahiaZZ** [comment]
ok, thank you again @tandraschko , i will try again
