### ISSUE TITLE
SubMenu: does not have attribute disabled

### ISSUE THREAD

**Issue by brunoaandrade** [primefaces/primefaces#4004]
## 1) Environment
- PrimeFaces version: 6.2
- Affected browsers: all

## 2) Expected behavior
it should be possible to set the SubMenu disabled with an attribute. 
If i am using a p:submenu inside a p:menubar i should be able to disable a specific one.

## 3) Actual behavior
SubMenu does not have an attribute disabled

## 4) Steps to reproduce
Example in https://www.primefaces.org/showcase/ui/menu/menubar.xhtml
.. 

## 5) Sample XHTML
<h:form>  
    <p:growl id="messages"/>
    <p:menubar>
        <p:submenu label="File" icon="ui-icon-document">
            <p:submenu label="New" icon="ui-icon-contact" disabled="true">
                <p:menuitem value="Project" url="#" />
                <p:menuitem value="Other" url="#" />
            </p:submenu>
            <p:menuitem value="Open" url="#" />
            <p:separator />
            <p:menuitem value="Quit" url="#" />
        </p:submenu>
 
        <p:submenu label="Edit" icon="ui-icon-pencil">
            <p:menuitem value="Undo" url="#" icon="ui-icon-arrowreturnthick-1-w" />
            <p:menuitem value="Redo" url="#" icon="ui-icon-arrowreturnthick-1-e" />
        </p:submenu>
   </p:menubar>
</h:form>

## 6) Sample bean

..

**Comment by tandraschko** [comment]
Please provide more description to your tickets, otherwise i will close it as invalid.
Should it be possible via xhtml, model or what do you want to archive...
