### ISSUE TITLE
DataTable: column break lines in header not visible with resizeableColumns and multiViewState

### ISSUE THREAD

**Issue by fynnfluegge** [primefaces/primefaces#4005]
## 1) Environment
- PrimeFaces version: 6.2.8
- Application server + version: Red Hat JBoss EAP 6.4
- Affected browsers: IE, Firefox

## 2) Expected behavior
When using 
```
resizableColumns="true"
multiViewState="true"
```
with DataTable the columns are resizeable by moving the vertical column break lines in the table header.

## 3) Actual behavior

The vertical column break lines in the table header are not visible.
However, by clicking on the field where the vertical lines should potentially be, the columns are resizeable as intended.

## 4) Steps to reproduce
Create a DataTable with the following template

## 5) Sample XHTML
```
<p:dataTable value="#{someClass}" var="someObject"
		resizableColumns="true"
		multiViewState="true" >

<p:columnGroup type="header">
	<p:column colspan="4" headerText="header0"/>
	<p:column colspan="1" headerText="header1" style="overflow-wrap:break-word;white-space:normal;"/>
	<p:column colspan="4" headerText="header2" style="overflow-wrap:break-word;white-space:normal;"/>
	<p:column colspan="1" headerText="header3" style="overflow-wrap:break-word;white-space:normal;"/>
	<p:column colspan="1" headerText="header4" style="overflow-wrap:break-word;white-space:normal;"/>
	<p:column colspan="1" headerText="header5" style="overflow-wrap:break-word;white-space:normal;"/>
	<p:column colspan="1" headerText="header6" style="overflow-wrap:break-word;white-space:normal;"/>
	</p:columnGroup>
...
</p:dataTable>
```

## 6) Sample bean
Not required.

**Comment by fynnfluegge** [comment]
Is there any idea for a possible workaround ?

**Comment by melloware** [comment]
According to this it looks like you need to specify a width on each column:
https://forum.primefaces.org/viewtopic.php?f=3&t=34748
