### ISSUE TITLE
Dialog is not centered properly when inside composite component

### ISSUE THREAD

**Issue by teohaik** [primefaces/primefaces#4006]
Screenshot with dialog in the wrong position: 
![dialog-problem-1](https://user-images.githubusercontent.com/1785012/44787843-f480d100-aba0-11e8-9f02-8cde5b954cfa.png)

If browser is resized, dialog appears in the center, as it should.
![dialog-problem-2-centered](https://user-images.githubusercontent.com/1785012/44787845-f480d100-aba0-11e8-8278-91f3b158d5a3.png)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? 
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Weblogic 12.2.1.3
- Affected browsers: Chrome

## 2) Expected behavior
Dialog should appear centered on viewport
...

## 3) Actual behavior
Dialog appears in the lower right corner of the viewport. BUT if the browser is resized, then the dialog centers properly. 
NOTE: Works OK in Internet Explorer (!!)

## 4) Steps to reproduce
Put a dialog with a gif inside a composite component. 
.. 

## 5) Sample XHTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:composite="http://java.sun.com/jsf/composite">

<composite:interface>
    <composite:attribute name="rulesEvaluator" type="com.intrasoft.ssp.pensions.common.api.RulesEvaluator"
                         required="true"/>
    <composite:attribute name="rulesGenericClient"
                         type="com.intrasoft.ssp.pensions.common.api.RulesGenericEvaluator"
                         required="true"/>
</composite:interface>

<composite:implementation>
    <h:outputScript library="pensions-cc" name="eligibilityCheckForm.js" target="head"/>

    <p:dialog widgetVar="progressBarDialog"
              closable="false"
              draggable="false"
              showHeader="false"
              style="border: none; background: none; box-shadow: none !important;"
              responsive="true">
        <p:graphicImage value="/resources/pensions-cc/Spinner-1s-200px.gif"/>
    </p:dialog>

    <h2>#{pageMsgs['pensions.eligibility.step3Header']}</h2>

    <h:panelGroup id="qualifiedMessagePanel"
                  rendered="#{!cc.attrs.rulesEvaluator.isEvaluationSuccessful() and cc.attrs.rulesEvaluator.evaluationFinished()}">
        <h3> #{pageMsgs['pensions.eligibility.step3.qualifiedNotEligibleMessage']}</h3>
    </h:panelGroup>

    <div class="ui-g ui-fluid">
        <div class="ui-md-3">
            <p:commandButton
                    id="startQualificationBtn"
                    styleClass="mb-md"
                    value="#{pageMsgs['pensions.eligibility.step3.qualify']}"
                    update="@form"
                    disabled="#{!cc.attrs.rulesGenericClient.isEditMode()}"
                    action="#{cc.attrs.rulesGenericClient.runGenericQualificationProcess}"
                    onclick="PF('progressBarDialog').show();"
                    icon="ui-icon-check">
            </p:commandButton>
        </div>
        <div class="ui-md-2"><p:commandButton type="button"
                                              disabled="#{!cc.attrs.rulesEvaluator.evaluationFinished()}"
                                              onclick="expandRows()"
                                              value="#{pageMsgs['pensions.expand']}"
                                              icon="ui-icon-arrowthick-1-s"/></div>
        <div class="ui-md-3" style="text-align: right;">
            <p:outputLabel id="filterValues"
                           value="#{pageMsgs['pensions.filterByEligibility']}"
                           style="font-weight: bold"/>
        </div>
        <div class="ui-md-3" style="">
            <p:selectOneMenu id="paymentMethodSelect"
                             disabled="#{!cc.attrs.rulesEvaluator.evaluationFinished()}"
                             value="#{rulesDecisionBean.subtermViewOption}">
                <f:selectItems
                        value="#{rulesDecisionController.subtermViewOptions}" var="var"
                        itemLabel="#{pageMsgs[''+=var.description]}" itemValue="#{var}"/>
                <p:ajax listener="#{cc.attrs.rulesEvaluator.onTermViewOptionChange}"
                        update="@form"/>
            </p:selectOneMenu>
        </div>
    </div>

    <c:if test="#{cc.attrs.rulesEvaluator.evaluationFinished()}">
        <h:panelGroup id="runDroolsPanel">

            <p:remoteCommand oncomplete="expandRows();" autoRun="true"/>

            <p:repeat value="#{cc.attrs.rulesEvaluator.getTermsToDisplay()}" var="be">

                <p:dataTable var="qTerm" value="#{be.qualificationTerms}"
                             sortBy="#{be.description}"
                             expandableRowGroups="true">
                    <p:headerRow>
                        <p:column colspan="3" styleClass="ml-sm">
                            <h:outputText
                                    value=" #{be.description} - #{be.dependentPartyName}"/>
                        </p:column>
                    </p:headerRow>
                    <p:column style="width:16px">
                        <p:rowToggler/>
                    </p:column>
                    <p:column headerText="#{pageMsgs['pensions.qualTermHeader']}">
                        <h:outputText
                                value="#{qTerm.description}"/>
                    </p:column>
                    <p:column headerText="#{pageMsgs['pensions.qualSubtermsHeader']}">
                        <h:outputText
                                value="#{qTerm.subterms.size()}"/>
                    </p:column>
                    <p:rowExpansion>
                        <p:dataTable var="subTerm" value="#{qTerm.subterms}">
                            <p:column headerText="#{pageMsgs['pensions.qualSubtermHeader']}">
                                <h:outputText value="#{subTerm.description}"/>
                            </p:column>
                            <p:column headerText="#{pageMsgs['pensions.isEligibleHeader']}"
                                      styleClass="text-center"
                                      style="background-color:#{subTerm.approved eq 'true' ? 'rgb(215, 253, 204)' : null}">
                                <h:outputText
                                        value="#{cc.attrs.rulesEvaluator.getEligibilityMessage(subTerm.approved)}"/>
                            </p:column>
                        </p:dataTable>
                    </p:rowExpansion>
                </p:dataTable>
            </p:repeat>
        </h:panelGroup>
    </c:if>

</composite:implementation>

</html>

CLIENT:

<h:panelGroup id="step3Panel"
                      rendered="#{alterationController.getNavBean().viewRendered('step3Panel')}">
            <div class="ui-g">
                <div class="ui-g-12 ui-lg-12 main_panel #{alterationController.getNavBean().viewIsBack('step3Panel') ? 'left_animation slideOutRight animated' : ''}
                                                        #{alterationController.getNavBean().viewFromPrevious('step3Panel') ? 'right_animation customSlideInRight animated' : ''}">
                    <div class="ui-g-12 ui-lg-12">
                        <div class="card card-w-title">

                            <h:form>

                                <pensions-cc:eligibilityCheckForm rulesEvaluator="#{rulesDecisionController}"
                                                                  rulesGenericClient="#{alterationController}"/>

                                <p:separator/>
                                <div class="ui-g ui-fluid">
                                    <div class="ui-md-2 ui-g-12">
                                        <p:commandButton
                                                value="#{beansMsgs['uibeans.buttonBack']}"
                                                action="#{alterationController.previousStep()}"
                                                tabindex="-1"
                                                oncomplete="viewsReady(); window.scroll(0, 0);"
                                                update=":viewsPanel"
                                                icon="ui-icon-carat-1-w"/> 
                                    </div>
                                    <div class="ui-md-8 ui-g-12"></div>
                                    <div class="ui-md-2 ui-g-12">
                                        <p:commandButton value="#{pageMsgs['pensions.eligibility.stepNext']}"
                                                         oncomplete="window.scroll(0, 0)"
                                                         disabled="#{!alterationController.rulesDecisionBean.finished}"
                                                         action="#{alterationController.startStep4()}" iconPos="right"
                                                         update=":viewsPanel" icon="ui-icon-carat-1-e"/>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </h:panelGroup>

## 6) Sample bean

--

**Comment by tandraschko** [comment]
Please provide a forked primefaces-test - otherwise it's nearly impossible for us to check your problem and will be closed as invalid.

**Comment by tandraschko** [comment]
Will close it for now, maybe you can try the forum first. If you have a forked primefaces-test (simple as possible) project, we can also reopen this issue.
