### ISSUE TITLE
OverlayPanel: Close button is hidden partially

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4007]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Yes Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
The close button should be placed over the panel.

## 3) Actual behavior
The close button is hidden.

## 4) Steps to reproduce
1. Open https://www.primefaces.org/showcase/ui/overlay/overlayPanel.xhtml
2. Using the browser developer tool add **overflow: auto;** to the rule **.ui-overlaypanel**
3. The close button is hidden.

## 6) Sample bean
I tested this issue using the showcase.

-------------------------------------
The problem was created because of this commit where overflow was added:
- [f87d5410061d1d5f33bfa95465405e71fc83466a](https://github.com/primefaces/primefaces/commit/f87d5410061d1d5f33bfa95465405e71fc83466a#diff-bba4632076be830e73e24fed6790b61c)

**Comment by tandraschko** [comment]
reverted the style change
