### ISSUE TITLE
TabView: doesn't toggle ui-helper-hidden correctly

### ISSUE THREAD

**Issue by Kameecoding** [primefaces/primefaces#4008]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? not yet tested
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) not yet tested
- Application server + version: irrelevant
- Affected browsers: all

## 2) Expected behavior

- When I have tabView i expect that the class .ui-helper-hidden is only added to tab contents that are not active and when I switch tabs this updates accordingly

...

## 3) Actual behavior

- when switching tabs the helper classes do not change making it harder to relayout the tabView component, e.g. when you want a more responsive layout with flexbox
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

TODO
..

## 6) Sample bean

..

**Comment by Rapster** [comment]
Indeed, `ui-helper-hidden` should be responsible of setting `display: none`, but something else adding `display` property (tabview.js?) Anyway, I don't have time for this, we have more important issues to fix right now. Feel free to provide a PR

**Comment by Kameecoding** [comment]
PR here: https://github.com/primefaces/primefaces/pull/4024
