### ISSUE TITLE
Dialog: Modal not working

### ISSUE THREAD

**Issue by chessceres** [primefaces/primefaces#4009]
## 1) Environment
- PrimeFaces version: 6.3
- Does it work on the newest released PrimeFaces version? Version? -> 6.2 it works correctly
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) --> No, it doesn't
- Application server + version:
- Affected browsers: IE11, firefox

## 2) Expected behavior

The dialog has to be shown modal.

## 3) Actual behavior

The dialog is in "not modal" (basic) mode.

## 4) Steps to reproduce

The attribute "visible" from component "p:dialog" has to be set with a bean attribute.
At first the bean attribute is "false", so that the dialog is not shown. Then it is switched to "true". --> The dialog appears in **not** modal mode.

## 5) Sample XHTML

        <p:selectBooleanButton offLabel="OFF" onLabel="ON" value="#{myModel.uploaded}">
          <p:ajax update="test" />
        </p:selectBooleanButton>

        <p:dialog id="test" modal="true" visible="#{myModel.uploaded}" minWidth="200" minHeight="500">
          <h:outputText value="File is uploaded!" />
        </p:dialog>

## 6) Sample bean

@ViewScoped
@Named
public class MyModel implements Serializable {
    private boolean uploaded;
    public boolean isUploaded() {
        return uploaded;
    }
    public void setUploaded(boolean uploaded) {
        this.uploaded = uploaded;
    }
}

**Comment by Rapster** [comment]
> - Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.

Thank you :wink:
