### ISSUE TITLE
itemIndex problem in selectOneRadio with customLayout

### ISSUE THREAD

**Issue by hbarrameda** [primefaces/primefaces#401]
selectOneRadio  in version 5.2 introduced a problem with itemIndex when using the custom layout. The following code will show the issue:

```
  <h:form>
         <p:selectOneRadio id="customRadio" layout="custom" onchange="alert('selected '+this.value)">
                  <f:selectItem itemLabel="0" itemValue="0" />
                  <f:selectItem itemLabel="1" itemValue="1" />
                  <f:selectItem itemLabel="2" itemValue="2" />
              </p:selectOneRadio>


              <h:panelGroup rendered="false">
                  <p:radioButton for="customRadio" itemIndex="0"/>
                  <h:outputText>0</h:outputText>
              </h:panelGroup>

              <h:panelGroup rendered="true">
                  <p:radioButton for="customRadio" itemIndex="1"/>
                  <i>1</i>
              </h:panelGroup>

              <h:panelGroup rendered="true">
                  <p:radioButton for="customRadio" itemIndex="2"/>
                  <i>2</i>
              </h:panelGroup>
     </h:form>
```

**Comment by sudheerj** [comment]
Can you please explain about the issue in detail.I can see that the selectedItem as correct value only.What else issue you faced in this scenario

![image](https://cloud.githubusercontent.com/assets/3127317/7998296/a8c6fad8-0b57-11e5-936a-c301e5a9def6.png)

**Comment by hbarrameda** [comment]
Hello,

   I'm sorry to bother you but I found this problem in my work so I thought
that put it as an issue in the github was the way to go.

I attached here a file I wrote from the example of the showcase. I extract
the fragment related with custom layout and removed unneeded controls. To
execute it, you can use the same RadioView.java used in the showcase.

 The issue appears when the three "custom" options are inside fragments in
order to set dynamically if they are rendered or not. To show you the
problem i set rendered ="false" only for the first option ("red"). When you
submit your selection, the value shown in the dialog is not correct. I must
say that I used the version 5.2 of primeFaces and that it did work in
version 5.1. This could be already solved in current developper version but
I must used a released version in my work.

   I hope that you will be able to reproduce it, but please, do not
hesitate to contact me if you need more details

   Best regards

```
  Hector
```

**Comment by cagataycivici** [comment]
Please do a search before creating new issues;

See #69
