### ISSUE TITLE
SplitButton: add dynamic list of buttons

### ISSUE THREAD

**Issue by schlebe** [primefaces/primefaces#4010]
I have posted following message on Primefaces forum but my problem seems to have no answer and currently no solution !

[https://forum.primefaces.org/viewtopic.php?f=3&t=56730](https://forum.primefaces.org/viewtopic.php?f=3&t=56730)

My request:

**Adding dynamic list of buttons to SplitButton widget.**

Why <p:SplitButton> is using <p:menuItem> instead of <f:selectedItems> as <p:selectOneButton> do ?

To solve this problem "simply", it is perhaps possible to develop a <p:menuItems> (with S at end) component that can be used to specify dynamic list of buttons ? :-)

Is there a solution to my problem without this enhancement ?

**Comment by tandraschko** [comment]
Feel free to implement it and provide a PR or to sponsor it via PrimeFaces PRO.

**Comment by melloware** [comment]
I think a better way to phrase this is that SplitButton needs to support rendering using the server side MenuModel so you can dynamically build the menu right?

**Comment by schlebe** [comment]
Yes, I don't have tought about menu right ! My first idea to solve this problem is to use <f:selectedItems> but now that you speak about menu right, the best solution is perhaps to develop a new class named menuItems !

**Comment by Rapster** [comment]
See #4106
