### ISSUE TITLE
Cleaneup Utils

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#4019]
Deprecrate and remove in 7.0:
 - Base64 (unused; java8 offers java.util.Base64)

Deprecrate (+ remove in 7.0) and move to LangUtils:
 - ClassUtils
 - ArrayUtils
 - CollectionUtils

Shade:
 - BoundedInputStream

**Comment by Rapster** [comment]
Regarding `BoundedInputStream`, use commons-io 2.4

**Comment by tandraschko** [comment]
Why? We are already on java1.7, so we could use 2.6

**Comment by Rapster** [comment]
A mentionned in #3525, cnsgithub asked

> (btw: should we also move BoundedInputStream from commons.io to its original package org.apache.commons.io?)

And my answer was:

> Yes it makes sense, but if we use last version of commons-io (which is 2.5) it will copy a lot more than just BoundedInputStream because it has imports from IOUtils (see https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/input/BoundedInputStream.java) It'll copy a bunch of classes just because BoundedInputStream needs IOUtils#EOF. Although, it should be fine using commons-io 2.4

Basically, to keep a small jar I think it's best to stick to 2.4 (unless there was major improvements in 2.6 regarding BoudedInputStream, but from what I can see there are similar)

**Comment by tandraschko** [comment]
yep, i see

**Comment by tandraschko** [comment]
just removed them as the layouts doesn't use it and it's just internal API
