### ISSUE TITLE
SelectBooleanButton: Remove type attribute rendered on the main div

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4020]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Not Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
The type attribute shouldn't be rendered.

## 3) Actual behavior
The type attribute is rendered.

## 4) Steps to reproduce
1. Open https://www.primefaces.org/showcase/ui/input/booleanButton.xhtml
2. Use the browser developer tool.

-------------------------------------
The reasons:
- The type attribute doesn't apply on a div element.

**Comment by wsaca** [comment]
The PR #4021 was created.

**Comment by tandraschko** [comment]
Thanks
