### ISSUE TITLE
Autocomplete: The style ui-state-active is not removed of dropdown button

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4022]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Not Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
If the mouse is moved out of the dropdown button the css class "ui-state-active" should be removed.

## 3) Actual behavior
The css class "ui-state-active" is not removed.

## 4) Steps to reproduce
1. Open https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml
2. Click on the dropdown button, the css class "ui-state-active" is applied.
3. Move the mouse out of the dropdown button and release the mouse button, the "ui-state-active" is not removed.

**Comment by wsaca** [comment]
Check the PR #4023

**Comment by tandraschko** [comment]
Nice, i really appreciate the PR!
