### ISSUE TITLE
 MenuItem: Url doesn't prefix with the contextPath

### ISSUE THREAD

**Issue by Emilija1365** [primefaces/primefaces#4026]
MenuItem: generated URL does not include the context path of the webapp.

## 1) Environment
- PrimeFaces version: 6.2.8 (Functions properly in version 6.2.5)
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? Not tried
- Application server + version: Tomcat 8.5.20
- Affected browsers: Firefox, Chrome

## 2) Expected behavior
The final url should contain the context path: http://localhost:8080/expected-context-path/menuitem1.jsf

## 3) Actual behavior
Urls are created without context path: http://localhost:8080/menuitem1.jsf -> so the page is not found

## 4) Sample XHTML
```xml
<p:menubar id="menuLinks">
    <p:menuitem url="/menuitem1.jsf" value="Menu Item 1"/>
    <p:menuitem url="/menuitem2.jsf" value="Menu Item 2"/>
</p:menubar>
```

**Comment by tandraschko** [comment]
Duplicate: https://github.com/primefaces/primefaces/issues/3819

**Comment by AnkitaNalawade88** [comment]
Can someone provide me this fix, i am facing issues while navigating to different pages, my context root gets changed. 
i am using latest version of primefaces ..i.e. 
<primefaces.version>6.2</primefaces.version>
		<primefacesExt.version>6.2.4</primefacesExt.version>


Please guide, which version supports menu item / url navigations .. ???

**Comment by tandraschko** [comment]
Check the migration guide, you have do adjust your code.
