### ISSUE TITLE
Dialog: Add resizeStart and resizeStop behavior event

### ISSUE THREAD

**Issue by lionstorke** [primefaces/primefaces#4028]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1.3

- Does it work on the newest released PrimeFaces version? Version?
No.  I checked with primefaces 6.2.8. It's a request for a new feature.

- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No.  It's a request for a new feature.

- Application server + version:
Tomcat 8.0.23

- Affected browsers:
All browsers

## 2) Expected behavior
Similar to a move event, please provide a resize event for a p:dialog. For a move event I can use
<p:dialog>
<p:ajax event="move" listener="#{myController.onMoveDialog}" />
</p:dialog>

For resize event there should be a similar event, which I can use like <p:ajax event="resize" listener="#{myController.onResizeDialog}" />

public class MyController {
public void onMoveDialog(MoveEvent evt) {
int left = evt.getLeft();
int top = evt.getTop());
}

public void onResizeDialog(ResizeEvent evt) {
int width = evt.getWidth();
int height = evt.getHeight());
}

}

## 3) Actual behavior
Feature is not implemented.

## 4) Steps to reproduce
<p:dialog>
<p:ajax event="resize" listener="#{myController.onResizeDialog}" />
</p:dialog>

does not work

## 5) Sample XHTML
<p:dialog>
<p:ajax event="resize" listener="#{myController.onResizeDialog}" />
</p:dialog>

## 6) Sample bean
I provide an implementation for the feature request.
Two files are modified:
1. org.primefaces.component.dialog.Dialog.java
2. META-INF/resources/primefaces/component/dialog/dialog.js

Both files are included with modifications
[attached-files.zip](https://github.com/primefaces/primefaces/files/2352597/attached-files.zip)

**Comment by Rapster** [comment]
Thank for your contribution, but provide a PR instead https://help.github.com/articles/creating-a-pull-request/

It'll be easier for us to review your code, and you'll get all the credits 😉

**Comment by lionstorke** [comment]
Hi Sebastien,
I would like to do so.

But when I modify class Dialog.java, what happens with that modification?
At the top of Dialog.java I found:
/*
* Generated, Do Not Modify
*/

Can you please tell me, what happens, when I change a generated file?

Thank you.

Manfred

**Comment by Rapster** [comment]
Resync your branch, there is no longer generated sources

**Comment by matinh** [comment]
See also issue #1588.

**Comment by tandraschko** [comment]
Next time please provide a PR.
