### ISSUE TITLE
MenuButton: Overlay misaligned in PF-6.3-Snapshot

### ISSUE THREAD

**Issue by RueKow** [primefaces/primefaces#4029]
## 1) Environment
- PrimeFaces version: 6.3 Snapshot
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 8.5
- Affected browsers: Chrome

## 2) Expected behavior

On a right aligned MenuButton the overlay should be aligned right justified.

## 3) Actual behavior

The overlay ist left justified and the rest is truncated.
<img width="174" alt="menubutton" src="https://user-images.githubusercontent.com/5890143/45265897-c037cb00-b452-11e8-8b09-dccfeea5b4c0.png">
<img width="172" alt="menubutton2" src="https://user-images.githubusercontent.com/5890143/45265907-e6f60180-b452-11e8-89c5-31881540d516.png">
https://forum.primefaces.org/viewtopic.php?f=3&t=56834

## 4) Steps to reproduce

Create a simple XHTML page (see ##5).

## 5) Sample XHTML

<h:form>
	<p:outputPanel style="width:100%; padding:24px; text-align:right">
		<p:menuButton value="Aktion" iconPos="right" style="text-align:left">
			<p:menuitem value="Benutzer hinzufügen" icon="ui-icon-add" />
			<p:menuitem value="Email an Benutzer" icon="ui-icon-mail-outline" />
		</p:menuButton>
	</p:outputPanel>
</h:form>

## 6) Sample bean

Not necessary.

**Comment by melloware** [comment]
Screenshots please

**Comment by kukel** [comment]
Panel gets the with of the button inside it. Set css overflow of the panel to show things or use the appendTo attribute if it exists

**Comment by melloware** [comment]
@RueKow please test @kukel suggestions and close this ticket once verified.

**Comment by melloware** [comment]
Possibly related to these recent issues:  https://github.com/primefaces/primefaces/issues/3993 https://github.com/primefaces/primefaces/issues/3861

**Comment by RueKow** [comment]
Using appendTo it is working as expected. Sorry for creating this issue, but in PF6.2 it was working without appendTo.

**Comment by tandraschko** [comment]
Will Check it after Holiday

**Comment by tandraschko** [comment]
made "body" the default again
