### ISSUE TITLE
Add sequential attribute to fileUpload

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#403]
FileUpload sends multiple upload requests in parallel. This is dangerous, because JSF explicitly requires client to queue requests (JSF 2.2 spec 13.3.2 Ajax Request Queueing). JSF's server-side implementation is not required to properly handle multiple requests to the same view simultaneously.

**Comment by cagataycivici** [comment]
It is better to create an attribute to make this configurable. Changing title.

**Comment by nunofaria11** [comment]
@cagataycivici  While this feature isn't available I tried forcing the sequential behavior on a multiple fileUpload component (according to [this answer in SO](http://stackoverflow.com/a/22709515/691916)) - it worked (when it comes to performing sequential requests) but the final outcome results in only one file got actually uploaded (processed by the `fileUploadListener`). Do you have any suggestion for all `fileUploadListener`s to get called?
