### ISSUE TITLE
SplitButton: Overlay not visible in column in PF-6.3-Snapshot

### ISSUE THREAD

**Issue by RueKow** [primefaces/primefaces#4030]
## 1) Environment
- PrimeFaces version: 6.3 Snapshot
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 8.5
- Affected browsers: Chrome

## 2) Expected behavior

Overlay of SplitButton should be visible in a table cell.

## 3) Actual behavior

When SplitButton is placed in a datatable column, the menu overlay is behind table cell.
<img width="278" alt="splitbutton" src="https://user-images.githubusercontent.com/5890143/45265879-82d33d80-b452-11e8-8238-ba4a8153c8f0.png">

https://forum.primefaces.org/viewtopic.php?f=3&t=56838

## 4) Steps to reproduce

In the PrimeFaces showcase (DataTable - Selection) replace p:commandButton with p:splitButton. 

## 5) Sample XHTML

    <p:dataTable id="basicDT" var="car" value="#{dtSelectionView.cars1}">
        <f:facet name="header">
            Basic
        </f:facet>
        <p:column headerText="Id">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Year">
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Brand">
            <h:outputText value="#{car.brand}" />
        </p:column>
        <p:column headerText="Color">
            <h:outputText value="#{car.color}" />
        </p:column>
        <p:column style="width:32px;text-align: center">
		<p:splitButton value="Zeigen" icon="ui-icon-visibility">
			<p:menuitem value="Ändern" icon="ui-icon-edit" />
			<p:menuitem value="Löschen" icon="ui-icon-delete" />
			<p:menuitem value="Kopieren" icon="ui-icon-content-copy" />
		</p:splitButton>
        </p:column>
    </p:dataTable>

## 6) Sample bean

Showcase beans

**Comment by melloware** [comment]
Can you add your screenshots you have on the forum so everyone can see as well?

**Comment by kukel** [comment]
Non-issue... appendTo should be used most likely with a value of body.... See the documentation. (or set overflow to visible on the table cell or related container)

**Comment by melloware** [comment]
@Rapster Safe to close this ticket as "invalid".

**Comment by Rapster** [comment]
Since it was working in PF 6.2, I'd rather wait for Thomas to have a look at it, and give a reason of this regression (if he has an idea). If more users refers to this problem, I'd like to either write something in the migration guide or simply close it (as duplicate) and refers to this issue.

**Comment by melloware** [comment]
Possibly related to these recent issues:  https://github.com/primefaces/primefaces/issues/3993 https://github.com/primefaces/primefaces/issues/3861

**Comment by Rapster** [comment]
Thank you Melloware for searching the root cause :+1:

**Comment by RueKow** [comment]
Using appendTo it is working as expected.

**Comment by RueKow** [comment]
I checked it once more and determined the following behavior.

Initially it is working with appendTo.
![splitbutton1](https://user-images.githubusercontent.com/5890143/45343409-19157980-b5a1-11e8-8f6b-a382c15fcc1f.png)

But after using datatable filter or button click the overlay is rendered twice.
![splitbutton2](https://user-images.githubusercontent.com/5890143/45343452-3cd8bf80-b5a1-11e8-83c8-ec471fc6d03a.png)

JAVA

				public class Test implements Serializable                                   
				{
					String field1;
					String field2;
					public Test(String field1, String field2)
					{
						super();
						this.field1 = field1;
						this.field2 = field2;
					}
					public String getField1()
					{
						return field1;
					}
					public String getField2()
					{
						return field2;
					}
					public void setField1(String field1)
					{
						this.field1 = field1;
					}
					public void setField2(String field2)
					{
						this.field2 = field2;
					}
				}

				@ManagedBean
				@SessionScoped
				public class TestController implements Serializable
				{
					private Test test;
					private List<Test> testList;
					public Test getTest()
					{
						return test;
					}
					public List<Test> getTestList()
					{
						return testList;
					}
					@PostConstruct
					public void init()
					{
						testList = new ArrayList<Test>();
						testList.add(new Test("Record1<br/>Field1", "Record1<br/>Field2"));
						testList.add(new Test("Record2<br/>Field1", "Record2<br/>Field2"));
						testList.add(new Test("Record3<br/>Field1", "Record3<br/>Field2"));
					}
					public void setTest(Test test)
					{
						this.test = test;
					}
					public void setTestList(List<Test> testList)
					{
						this.testList = testList;
					}
				}

XHTML

				<html xmlns="http://www.w3.org/1999/xhtml"
				      xmlns:h="http://java.sun.com/jsf/html"
				      xmlns:f="http://java.sun.com/jsf/core"
				      xmlns:ui="http://java.sun.com/jsf/facelets"
				      xmlns:p="http://primefaces.org/ui">
				    <h:head>
				        <title>Test</title>
				    </h:head>
				    <h:body>
						<h:form style="padding:25px">
							<p:dataTable value="#{testController.testList}" var="t">
								<p:column headerText="Field 1"
									filterBy="#{t.field1}" filterMatchMode="contains">
									<h:outputText value="#{t.field1}" escape="false"/>
								</p:column>
								<p:column headerText="Field 2"
									filterBy="#{t.field2}" filterMatchMode="contains">
									<h:outputText value="#{t.field2}" escape="false" />
								</p:column>
								<p:column headerText="" style="text-align:center; width:120px" styleClass="my-column">
									<p:splitButton value="Show" appendTo="@(body)"
										update="@form">
										<p:menuitem value="Change"
											update="@form" />
										<p:menuitem value="Delete"
											update="@form" />
										<p:menuitem value="Copy"
											update="@form" />
									</p:splitButton>
								</p:column>
							</p:dataTable>
						</h:form>        
				    </h:body>
				</html>

**Comment by melloware** [comment]
Yep when @tandraschko he will investigate I think its related to those two issues I linked.

**Comment by wsaca** [comment]
This problem should be fixed because is affecting some components, was introduced here:
https://github.com/primefaces/primefaces/issues/3788

For example: the autocomplete component calls the function PrimeFaces.utils.registerDynamicOverlay but inside that function we have this condition:
```
if (widget.cfg.appendTo) {

}
```

The class AutoCompleteRenderer never sends the default value @(body) if the property appendTo is not set by the user, because of that the condition is always resolve to false and the panel is not rendered in the body.
