### ISSUE TITLE
Media component: cannot display media with spec filename

### ISSUE THREAD

**Issue by endredy** [primefaces/primefaces#4032]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? dont know
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) dont know
- Application server + version: WildFly 13
- Affected browsers: ff, chrome

## 2) Expected behavior

Media component should display a file.

## 3) Actual behavior

If the filename contains some characters (#,? or %), it cannot display.
For example in case of "hello#.pdf" it won't show the content. (it can be downloaded)

## 4) Steps to reproduce

For example if a pdf file has such name "hello#.pdf", the media component is broken. 
(see ##5 and ##6)

## 5) Sample XHTML

    <p:media player="pdf" value="#{bean.pdfContent}"/>

## 6) Sample bean

    public StreamedContent getPdfContent() {
        ...
	    return new DefaultStreamedContent(stream, "application/pdf", generatedName+".pdf"); // generatedName must not contain #,?,%
    }

**Comment by Rapster** [comment]
Please follow the issue template

**Comment by melloware** [comment]
@Rapster what is missing from his template?  Looks like the issue is pretty clear.

**Comment by Rapster** [comment]
The author has updated the issue accordingly but I wasn't notified. It seems okay, but "dont know" is not answering to the question. @endredy Could you at least try please? Sure we could ourselves give it a try, but we would waste a lot of time if we had to do that for every isues...

**Comment by endredy** [comment]
I'm sure that this bug exists in the latest versions as well, but i didn't test it, and have no option to try it. Sorry!
But i think this info is more then enough to fix it, and as a developer i would be happy to have such an easy bug to fix. :)
It's up to you. :)
 
 
A suggestion:

    static public String validateFilename(String s){
    	    if (s == null || s.isEmpty()) return s;
    	    return s.replaceAll("[\\?%#]", "");
    }

**Comment by melloware** [comment]
@endredy I think that is too "narrow" of a solution.  I think we need to analyze why it doesn't work and then escape and cleanse the file name correctly.

**Comment by Rapster** [comment]
I reproduced the problem, @endredy looking at your web browser console could have spare me some time... According to Chrome console, after renaming into "guide#.pdf" :

> GET http://localhost:8300/showcase/resources/demo/media/guide.pdf?pfdrid_c=true 404 (Not Found)

It seems ignoring the sharp which does not really surprise me since `#` is a separator for URL fragment. So, these special characters has to be replaced by their corresponding percent-encoding characters, see https://fr.wikipedia.org/wiki/Percent-encoding

**Comment by melloware** [comment]
@Rapster something like we do in NativeFileUpload...

```java
           // GitHub #3916 escape + and % before decode
            encoded = encoded.replaceAll("%(?![0-9a-fA-F]{2})", "%25");
            encoded = encoded.replaceAll("\\+", "%2B");
            return URLDecoder.decode(encoded, "UTF-8");
```

**Comment by endredy** [comment]
Yes, i can confirm it. 
My case is similar: p:media is in an updated dialog, so 1st an update arrives (filename: "mypdf#blabla.pdf"):

    <object type="application/pdf" data="/abc/javax.faces.resource/dynamiccontent.properties.xhtml;/mypdf#blabla.pdf?ln=primefaces&amp;v=6.2&amp;pfdrid=..."
2nd: the component wants to download this broken link (404):
http://localhost/abc/javax.faces.resource/dynamiccontent.properties.xhtml;/mypdf

Encoding "#" is a solution (with other spec URL chars: ? and %, which are also enable to break link)

**Comment by Rapster** [comment]
@melloware Yes something like that, also I read this https://stackoverflow.com/a/49796882/4605161

**Comment by melloware** [comment]
Can you review my PR.  I think it is that simple as it went from ...

`http://localhost:8080/showcase/javax.faces.resource/dynamiccontent.properties.xhtml;/hello`

to...

`http://localhost:8080/showcase/javax.faces.resource/dynamiccontent.properties.xhtml;/hello%23.pdf?ln=primefaces&v=8.0-SNAPSHOT&pfdrid=63c2507f24e60841be415b0defa59341&pfdrt=sc&pfdrid_c=true`
