### ISSUE TITLE
SelectCheckboxMenu: When panel is filtered it's not realigned

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4040]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Not Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
When the panel is filtered it should be realigned.

## 3) Actual behavior
The panel is not realigned after filter its content.

## 4) Steps to reproduce
1. Open https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml
2. Resize the window to show the panel above the component.
3. Filter the content.
4. The panel is not realigned.

**Comment by Rapster** [comment]
I can't reproduce this step "Resize the window to show the panel above the component.". Which web browser are you using?

**Comment by wsaca** [comment]
By default the panel is displayed down the component, but if it is near to bottom of the window browser then the panel is displayed above.

**Comment by Rapster** [comment]
Okay I see, and does it go back up if you clear your selection (and filtering)?

**Comment by wsaca** [comment]
When you select/click an item it's aligned correctly, but if you use the filter it's not. The PR that I created try to resolve this.

**Comment by Rapster** [comment]
Sorry, I should've said: "With your PR, does it go back up if you clear your selection (and filtering)?"

**Comment by wsaca** [comment]
Yes, it does. You could try it locally.
