### ISSUE TITLE
ConfirmDialog: screen reader doesn't automatically read message

### ISSUE THREAD

**Issue by Lb-lea** [primefaces/primefaces#4043]
## 1) Environment
- PrimeFaces version: PrimeFaces-6.2.9
- Application server + version: Tomcat7.0.72/Mojarra-2.3.2
- Affected browsers: firefox 
-Screen readr: Orca 3.22.2

## 2) Expected behavior
When the modal appears, the screen reader should read the title, read the message, read the buttons and finish with saying that the ok button is active.

## 3) Actual behavior

When the modal appears, the screen reader reads the title, **skips reading the message**, reads the buttons and finish with saying that the ok button is active.

It works with the classic p:dialog, the message is being read upon the window being displayed.

## 4) Steps to reproduce
click on the command button to get the modal to appear with a screen reader running in the background.

## 5) Sample XHTML
```
<h:form>           

    <p:commandButton value="button"   onclick="PF('dialog').show();">
    </p:commandButton>
 
    <p:confirmDialog widgetVar="dialog" header="Title" message="read me">
        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"  onclick="PF('dialog').hide();"/>
        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"  onclick="PF('dialog').hide();" />
    </p:confirmDialog>
</h:form>
```
## 6) Sample bean
none

**Comment by melloware** [comment]
OK I think I can fix this.  From reviewing: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

I think we need to add 2 things...
1. aria-modal=true
2. aria-describedby=

**Comment by melloware** [comment]
I submitted a PR that I think will fix your issue and update dialogs to the latest ARIA standards.
