### ISSUE TITLE
p:commandButton not working properly inside p:dialog.

### ISSUE THREAD

**Issue by inis30** [primefaces/primefaces#4051]
I am reporting this issue for Primefaces 6.2. The button is acting strange. Sometimes it fires the action and sometimes it does not. The same functionality works properly for version 5.3 without changing  code.

Steps to reproduce : 

1-create a p:dialog component
2-add form inside dialog
3-add commandButton inside the form with properties : value, update, actionListener, onComplete
4- add also a p:remoteCommand outside the dialog

Issue : The actionListener sometimes get fired sometimes not.

**Comment by tandraschko** [comment]
Follow the issue template and provide a runnable example. Otherwise it will be closed as invalid.

**Comment by Rapster** [comment]
>- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
