### ISSUE TITLE
dataTable: cannot see filters (or sorters) when lazy and use field

### ISSUE THREAD

**Issue by dmainardi** [primefaces/primefaces#4052]
## 1) Environment
- PrimeFaces version: 6.2, 7.0, 8.0 and built from source
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: provided by primefaces-test, see below
- Affected browsers: Chrome (on Windows), Firefox (on Ubuntu 18.04), Firefox mobile (on Android) but I think every browser is affected.

## 2) Expected behavior

Filters and sorters must be visible in the second table. If you take a look to the project I forked you can see differences between _first table_ (with **sortBy** and **filterBy**) and _second_ one (with **field**).
Tables should be the same.
If you set (in pom.xml) primefaces version to 6.1 it works as expected.

## 3) Actual behavior

Cannot see filters and sorters in the _second table_ (the one with the **field** into p:column)

## 4) Steps to reproduce

Clone https://github.com/dmainardi/primefaces-test.git and run it with mvn jetty:run-exploded

## 5) Sample XHTML

Provided in test project (see above)

## 6) Sample bean

Provided in test project (see above)

**Comment by melloware** [comment]
Thanks for providing a test project. I definitely verified your issue on 6.3-SNAPSHOT using your test.

**Comment by dmainardi** [comment]
I found a (sort of) patch.
Instead of using
`field="theProperty"`
you can use
`sortBy=#{theProperty} filterBy=#{theProperty}`

I updated the test project, I hope it helped.

**Comment by nandorholozsnyak** [comment]
We are having the same problem with a nested datatable, if we use ```sortField``` on ```p:dataTable``` and ```field``` on ```p:column``` the filtering and sorter UI elements/things are not visible! With 6.1 it works, but with 6.2 it does not.
However the Primefaces Documentation 6.2 says if you are using a datatable with lazy you could use ```sortField``` and ```field``` combination.

**Comment by dmainardi** [comment]
I noticed that, if you add `field` (with or without `sortField`), you cannot see sorter (or `filter`). Did you @Holi60k fix your problem with the (sort of) path I wrote?

**Comment by nandorholozsnyak** [comment]
@dmainardi yes!
We were using the ```sortBy``` tag by default but after in one task we tried out the ```field``` and it worked, on the second day we upgraded the version than it did not work, but then we rewrote the datatable columns with ```sortBy``` :)

**Comment by dmainardi** [comment]
Now with 7.0 version the (sort of) patch doesn't work any more.
I updated test project.

**Comment by dmainardi** [comment]
I found another (sort of) patch for version 7.0.
Instead of using
`field="theProperty"` or `sortBy=#{theProperty} filterBy=#{theProperty}`
you can use
`field="theProperty" sortBy=#{theProperty} filterBy=#{theProperty}`

It gets more and more complicated, I am missing something?

**Comment by dmainardi** [comment]
Now with 8.0 version previous patch works again.
To help further readers:

- Primefaces 6.1 - `field="theProperty"` (as [documented](https://primefaces.github.io/primefaces/8_0/#/components/datatable?id=lazy-loading))
- Primefaces 6.2 - `sortBy=#{theProperty} filterBy=#{theProperty}`
- Primefaces 7.0 - `field="theProperty" sortBy=#{theProperty} filterBy=#{theProperty}`
- Primefaces 8.0 - `sortBy=#{theProperty} filterBy=#{theProperty}`

**Comment by melloware** [comment]
@Rapster don't you have fixes for this?

https://github.com/primefaces/primefaces/pull/5412

**Comment by Rapster** [comment]
Okay I had a quick look, basically it looks like everything is working as "expected". It's a topic that come back very often lately, but I wrote about it few months ago, see https://github.com/primefaces/primefaces/issues/5162#issuecomment-559824603

If there is anything you don't understand or I didn't understand from that issue, dont' hesitate to ask 😉

**Comment by melloware** [comment]
So can I close this ticket?

**Comment by Rapster** [comment]
I'd rather wait for feedbacks from the author if you don't mind

**Comment by dmainardi** [comment]
Hello,
thanks for be interested to this old issue.
I understood what @Rapster did, and I am ok with that.
I agree with [this](https://github.com/primefaces/primefaces/issues/5162#issuecomment-562484559) and I hope in version 9.0 we will be able to code like we used to do in 6.1 (`field="theProperty"` and nothing else).
I updated test project and I close the issue.
