### ISSUE TITLE
SelectCheckboxMenu: Label not updated for disabled component if updateLabel="true"

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4057]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No, 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Wildfly 11, Jetty
- Affected browsers: FF, Chrome

## 2) Expected behavior
If a disabled SelectCheckboxMenu with updateLabel="true" is shown, the label presents the selected items and not the default label.

## 3) Actual behavior
The default label is shown.

## 4) Steps to reproduce
Have a disabled SelectCheckboxMenu with selected items.

## 5) Sample XHTML
```
<h:form>
	<h:outputLabel for="multiple" value="Enabled:" />
	<p:selectCheckboxMenu id="multiple" value="#{checkboxView.selectedCities}" label="test1" updateLabel="true">
		<f:selectItem itemValue="Miami"  itemLabel="Miami"  />
		<f:selectItem itemValue="London" itemLabel="London" />
		<f:selectItem itemValue="Paris"  itemLabel="Paris"  />
	</p:selectCheckboxMenu>
	<br/>
	<h:outputLabel for="multiple" value="Disabled:" />
	<p:selectCheckboxMenu id="multiple2" value="#{checkboxView.selectedCities}" label="test2" updateLabel="true" disabled="true">
		<f:selectItem itemValue="Miami"  itemLabel="Miami"  />
		<f:selectItem itemValue="London" itemLabel="London" />
		<f:selectItem itemValue="Paris"  itemLabel="Paris"  />
	</p:selectCheckboxMenu>
</h:form>
```

## 6) Sample bean
```
@ManagedBean
@ViewScoped
public class CheckboxView {

    private String[] selectedCities;

    public String[] getSelectedCities() {
        return selectedCities;
    }

    public void setSelectedCities(String[] selectedCities) {
        this.selectedCities = selectedCities;
    }
}
```
Screenshot:
![selectcheckboxmenulabelnotupdated](https://user-images.githubusercontent.com/11403755/45817931-7ff10c00-bce0-11e8-9f51-140aee240523.png)

**Comment by Rapster** [comment]
Do you mean that you expect to see "London, Paris" on the disabled check menu after selecting items from enabled checkbox menu?

**Comment by OBreidenbach** [comment]
I mean i expect the same behavior as with other input elements. If it is disabled it shows the current values. 
The SelectCheckboxBox does that if the multiple attribute is set to true.
![selectcheckboxmenumultipleupdated](https://user-images.githubusercontent.com/11403755/45861359-70b7a000-bd6c-11e8-8293-91d19bc08066.png)
So I expect the some behavior for updateLabel=true as for multiple=true.

**Comment by Rapster** [comment]
Sorry if I sound stupid, but if it's disabled how do you select these values? I'm probably missing something, this is why I asked my previous question. Are these default values?

**Comment by Rapster** [comment]
What I see is wrong is that, if multiple and disabled: the default label is not displayed. Is that what you meant?

**Comment by OBreidenbach** [comment]
Our application has an edit and a read only mod. After hitting the edit-button you can edit the values. After hitting the save-button you only can read the values you saved. Therefor we set the disabled attribute at the used components / html elements. So I expect the same behavior as with other input elements. Just show the current value(s). 
SelectCheckboxmenu does this already if it is set to 'multiple'.
