### ISSUE TITLE
Add class ui-shadow to calendar popup overlay

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#406]
Add class ui-shadow to calendar popup overlay to make it more focused and distinct.

And it also looks much better.

**Comment by kukel** [comment]
Did you try what happens on _all_ (other) themes? Might be not that nice looking. And keep in mind that calendar.js is an external JS. No idea if they want to keep merging changes like this over and over again. Maybe try to get it into the calendar component source

**Comment by cagataycivici** [comment]
But it already has it, please check live demo;

http://www.primefaces.org/showcase/ui/input/calendar.xhtml
