### ISSUE TITLE
SelectCheckboxMenu: joins item labels with a comma (',') only

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4061]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No, 6.2
- Does it work on the newest sources in GitHub? No
- Application server + version: wildfly 11. jetty
- Affected browsers: Chrome, FF,..

## 2) Expected behavior
If updateLabel=true is set, the selected items are displayed on label comma separated. For instance:
item1,item3,item5
At least in english and german you have a blank after a comma. So I would expect to see:
item1, item3, item5.

## 3) Actual behavior
Joining items with comma without blank

## 4) Steps to reproduce
Config SelectCheckboxMenu with updateLabel=true

## 5) Sample XHTML
```
<p:selectCheckboxMenu id="first" value="#{checkboxView.selectedCities}"
					  label="test1" updateLabel="true" >
	<f:selectItem itemValue="Miami"  itemLabel="Miami"  />
	<f:selectItem itemValue="London" itemLabel="London" />
	<f:selectItem itemValue="Paris"  itemLabel="Paris"  />
</p:selectCheckboxMenu>
```

## 6) Sample bean
```
@ManagedBean
@ViewScoped
public class CheckboxView {
    private String[] selectedCities;

    public String[] getSelectedCities() {
        return selectedCities;
    }

    public void setSelectedCities(String[] selectedCities) {
        this.selectedCities = selectedCities;
    }
}
```

So the hard coded separator ',' should be changed to ', ' (with a blank). Or the separator for the label should be configurable.

**Comment by Rapster** [comment]
I don't know the rule of each language in the world. But I'd most of them use a space after comma. I was about to say that adding a new property would not be necessary, but actually what if I want to use a different character like "-"? This property could be usefull, so +1

**Comment by OBreidenbach** [comment]
We could do both, adding a space to the default and adding new property.

**Comment by Rapster** [comment]
Yes adding a space after comma (as the default value) makes sense

**Comment by melloware** [comment]
I like this change.  I just submitted two code review comments.

**Comment by OBreidenbach** [comment]
@melloware, I followed your suggestions.
