### ISSUE TITLE
MenuItem: link and command at the same time

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#4068]
PrimeFaces version: 6.3-SNAPSHOT

Right now declaring a menuitem such as:

    <p:menuitem value="Item" url="<url>" action="<action>" />

will result in only the url having effect. The menuitem will be just a link.

Instead it could both. If you simply click it, it would behave like an AJAX action, but if you middle-click or right-click and open in a new tab - then it's a link.

Why would you want that? You know how Jira has the "Create issue" button - if you simply click it, it opens the "Create issue" dialog; if you open it in a new tab, it opens the functionally identical "Create issue" page.

**Comment by Rapster** [comment]
Please follow issue template

**Comment by tandraschko** [comment]
Shouldnt it be enough to render both href and onclick?
Not sure why we did this with a "or" 😁

**Comment by VsevolodGolovanov** [comment]
Rechecked with the current 10.0.0-SNAPSHOT build - still works the same.

**Comment by jepsar** [comment]
No, I don't think that's a better description. Submitting the key modifier will not help you to open a link in a new tab. You will need a link (anchor) with a href to do that.

**Comment by melloware** [comment]
no i closed the other ticket saying this ticket is the better description.  Basically its the same thing A user wants to take different actions depending if modifier is held down.  In @VsevolodGolovanov description he wants to differentiate between a click and say a CTRL+CLICK to open in new tab?

**Comment by jepsar** [comment]
Okay, I thought you meant the other way around.

I would love to have this functionality. Adding an anchor would be best / the only way IMO.

**Comment by melloware** [comment]
I think what we need to do is the following:

- Not short circuit the code if URL or HREF is provided like its doing now.
- Render the AJAX onClick as normal
- If as AJAX event that will take precendence but inject  script to the onclick that if CTRL being held down or using the NON left mouse button do a `window.open(url, "_blank")` to open the URL in a new tab.

**Comment by VsevolodGolovanov** [comment]
@melloware, AFAIK if you do the "Open in new tab" action by any means then the browser will just open the `a href` url in a new tab automatically, we don't need to do anything special for it other then render the appropriate `href` attribute. So you don't need that 3rd item.

> or using the NON left mouse button do a window.open(url, "_blank") to open the URL in a new tab.

Oh no, don't hijack the right click, that's one of the worst things a site can do IMHO, prevent opening the browser's context menu like that.

**Comment by VsevolodGolovanov** [comment]
> @melloware, AFAIK if you do the "Open in new tab" action by any means then the browser will just open the a href url in a new tab automatically, we don't need to do anything special for it other then render the appropriate href attribute. So you don't need that 3rd item.

I just tried opening https://www.primefaces.org/showcase/ui/menu/menu.xhtml and adding `href="http://www.primefaces.org"` to the `Update` item with Developer Tools. Middle click and Right click + Open in New Tab do indeed work as is, but Ctrl+Click doesn't - it still results in the Update action. So you do need the 3rd item, but only for Ctrl+Click. In fact this is the hardest part to implement, so maybe even skip it if it holds the whole issue back - most users would go through the context menu anyway.

**Comment by melloware** [comment]
@VsevolodGolovanov no problem you just mentioned right click above.

I think its trickier than that isn't it?  If the browser sees `href="#"` we use that for AJAX events so the `onClick` happens for AJAX but the browser goes nowhere.  If we render the `href` then eveyr time you click for an AJAX  it will ALSO navigate you.

So I think we need to leave the `href="#"` and then write a script injected into onClick i proposed above?

**Comment by melloware** [comment]
OK you just edited and said the same thing I did about #3.  It has to be that way i think its the only way it would work.

**Comment by VsevolodGolovanov** [comment]
@melloware, yeah, I think so.

(By the way `href="#"` means "scroll to top". That's what would happen without `return false`. It's a bit of an old and not quite correct practice to have a urlless but still clickable and appropriately styled link: https://stackoverflow.com/questions/4855168/what-is-href-and-why-is-it-used.)

**Comment by melloware** [comment]
OK let me give this a shot I think I see it.

**Comment by melloware** [comment]
OK everyone please review my PR.

this allows a MenuItem like this...

```xml
<p:menuitem 
value="Create" 
url="http://jira.apache.org/create" 
actionListener="#{view.create}" 
update="dialog" 
oncomplete="PF('dlg').show();"/>
```

IF single clicking the link will cause an AJAX request to `view.create` and open a new dialog.  If you right-click and do "Open In New Tab" it opens the URL ` url="http://jira.apache.org/create"`

**Comment by jepsar** [comment]
I just checked this fix on my MacBook. Command+Click does not open the link in a new tab.

**Comment by melloware** [comment]
No right now only Right click and "Open In New Tab" works.  The CTRL/CMD is still an issue

**Comment by jepsar** [comment]
Aha. Do we have a separate issue for that?

**Comment by melloware** [comment]
No leave this one open I will take a look at solving it.

**Comment by jepsar** [comment]
This worked for me:
```html
<a href="http://primefaces.org/"
   onclick="if(event.ctrlKey||event.metaKey){return true};console.log('action');return false;">
    Click here
</a>
```

**Comment by melloware** [comment]
so i just think we need to inject that little script if using both command and link.  Let me try it.
