### ISSUE TITLE
Remove CSS font-size in delta theme for ui-button.

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#407]
Using delta theme there is a problem with the font-size of the ui-button text. 

There is no other theme with such a small button text. I don't know why it does not affects showcase but in my application they are small, even smaller then the input components.

Remove:

.ui-button .ui-button-text {
    font-size: 12px;
}

**Comment by cagataycivici** [comment]
Wrong issue tracker, use themes repo please.
