### ISSUE TITLE
ARIA and accessibility attributes are rendered on wrong elements

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#4077]
disabled and readonly are only ALLOWED on this elements:
https://www.w3schools.com/tags/att_disabled.asp

Not sure about the ARIA attributes but its probably allowed on other tags, too:
https://www.w3.org/TR/WCAG20-TECHS/ARIA2

**Comment by tandraschko** [comment]
@melloware here is a ticket for you

**Comment by melloware** [comment]
@tandraschko and @rho66 Just so I fix this correctly

1. If the container component is a DIV I should just use the renderARIARequired() method.

2. Only use renderAccessibilityAttributes if the element its being assigned to is one of: 

```xml
<button> 
<fieldset> 
<input> 
<optgroup> 
<option> 
<select> 
<textarea> 
```

**Comment by melloware** [comment]
Actually according to this "This attribute can be used with any typical HTML **form** element;" the 'aria-required' and 'aria-invalid' attributes should **not** be used on DIV's.  Yet in @rho66 testing he stated the screenreader was not reading it correctly unless it was on the outer DIV.

@rho66 can you confirm?

**Comment by tandraschko** [comment]
not sure, if you check "https://www.w3.org/TR/WCAG20-TECHS/ARIA2", it's also used in "ul"

**Comment by melloware** [comment]
Interesting in that case the Chips implementation on the UL would be correct for aria-required.  Also from reading it seems like whatever fix I make that aria-required and aria-invalid go hand in hand on the same exact elements.

_"When aria-invalid is used in conjunction with the aria-required attribute, aria-invalid should not be set to true before the form is submitted - only in response to validation."_  Which is exactly what my fix for is doing: https://github.com/primefaces/primefaces/pull/4069
