### ISSUE TITLE
SelectBooleanButton: throws TypeError: $.ui is undefined

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4080]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Not Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
No one javascript error should be throw.

## 3) Actual behavior
the component is throwing an error when the keyboard is used to change his value.

## 4) Steps to reproduce
1. Put only a p:selectBooleanButton inside a h:form
2. Try to change the value using the keyboard.

**Comment by Rapster** [comment]
Is it possible to see the JS stack trace to see what exactly is wrong?

**Comment by wsaca** [comment]
The component use "$.ui.keyCode" without add the dependency to jquery-plugins.js where it's located. You can't replicate this problem using the showcase because the commandButton already add this dependency.
