### ISSUE TITLE
DataTable: rowSelect event not triggered when clicking on checkboxes

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#4089]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No (6.2)
- Does it work on the newest sources in GitHub? No
- Application server + version: Tested with Wildfly 10.1.0.Final and PrimeFaces Sample Project with Jetty 9.4.11
- Affected browsers: tested with FireFox 62 and Chromium 69

## 2) Expected behavior

In a dataTable with row-selection enabled and multi-selection active, selecting a row should always trigger the rowSelect event.

## 3) Actual behavior

The rowSelect event is not triggered, if checkbox is clicked instead of anywhere else in the row.

## 4) Steps to reproduce

Click row in dataTable to select it and observe browser console: event is triggered and event handler prints a message.
Click checkbox to select a row and the event is not triggered.

## 5) Sample XHTML

    <h:form id="theForm">
      <p:dataTable value="#{testViewCdi.list}" var="e" rowKey="#{e}">
        <p:ajax event="rowSelect" oncomplete="console.log('selected');"/>
        <p:column selectionMode="multiple"/>
        <p:column>#{e}</p:column>
      </p:dataTable>
    </h:form>

## 6) Sample bean

    @Named
    @RequestScoped
    public class TestViewCdi {
    
        private List<String> list;
    
        @PostConstruct  
        public void init() {
            list = new ArrayList<>();
            list.addAll(Arrays.asList("a", "b", "c", "d", "e"));
        }

        public List getList() {
            return list;
        }
    }

**Comment by cagataycivici** [comment]
There is a separate **rowSelectCheckbox** event for checkboxes.
