### ISSUE TITLE
SelectOneMenu Spark css improvements

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#409]
I noticed two css related things with the selectOneMenu component and the Spark theme
- You cannot give it an invalid look by adding a ui-state-error class. 
- It has no change of appearance when hovering over it.

This can be simply tried in the live demo. It works for other inputs and also for the sentinel theme.

**Comment by cagataycivici** [comment]
Please use layouts tracker;

https://github.com/primefaces/layouts/issues
