### ISSUE TITLE
FileUpload with empty instance

### ISSUE THREAD

**Issue by JamesMung** [primefaces/primefaces#4090]
## 1) Environment
- PrimeFaces version: 4.0
- JSF: 2.2

## 2) Expected behavior
Submit a form with no file and `Uploadedfile` will be null.

## 3) Actual behavior
When I submit form with no attachment file, `Uploadedfile` never be null. but `getContents` and `getFileName` is empty.

## 4) Steps to reproduce
- Open a form.
- Fill the form except file upload.
- Submit the form

## 5) Sample XHTML
```xhtml
<h:form id="form" enctype="multipart/form-data">
  ...
  <p:fileUpload id="file" value="#{FileManageBean.file}" style="height:21px;width:200px;position:relative;top:-23px;left:0px;opacity:0" 
			 	mode="simple" />
  ...
  <p:commandButton value="Submit" type="submit" action="#{FileManageBean.onSubmit}" ajax="false"/>
</h:form>
```
## 6) Sample bean
```java
@ManagedBean
@ViewScoped
public class FileManageBean {
  private UploadedFile file;
  ...

  public void onSubmit(){
    if(file != null) {
      ...
    }
  }

  public UploadedFile getFile() {
	return file;
  }

  public void setFile(UploadedFile file) {
	this.file = file;
  }
}
```
- web.xml
```xml
<context-param>
	<param-name>primefaces.UPLOADER</param-name>
	<param-value>commons</param-value>
</context-param>

<filter>
	<filter-name>PrimeFaces FileUpload Filter</filter-name>
	<filter-class>
		org.primefaces.webapp.filter.FileUploadFilter
	</filter-class>
	<init-param>
		<param-name>thresholdSize</param-name>
		<param-value>0</param-value>
	</init-param> 
</filter>
<filter-mapping>
	<filter-name>PrimeFaces FileUpload Filter</filter-name>
	<servlet-name>Faces Servlet</servlet-name>
</filter-mapping>
```

**Comment by Rapster** [comment]
I don't think PF 4.0 is maintained anymore. Please follow the issue template (e.g try with the last version)

**Comment by melloware** [comment]
Have you tried this with 6.2 or 6.3-SNAPSHOT and is it still an issue?  If not I am afraid this ticket will be closed as invalid.

**Comment by JamesMung** [comment]
My project want to update from PF 3.5 to late version. But I found that the layout of the version after PF 5.0 is distorted. only PF 4.0 is closest. So I decided to use PF 4.0. 

Can you please kindly provide any solution of this issues ?

**Comment by tandraschko** [comment]
Sorry but we dont Support 4.0 anymore since years. I suggest to upgrade to 6.2, everything else doesnt make sense If you already Upgrade versions.

**Comment by elab** [comment]
I can confirm that the issue still exists with PF 6.2.
(In my case, no upload related filters and context-params are set in web.xml)
