### ISSUE TITLE
PhotoCam: Not working in IE 11

### ISSUE THREAD

**Issue by AlexKolesnik** [primefaces/primefaces#4094]
## 1) Environment
- PrimeFaces version: 6.2.9, Official Primefaces Showcase 
- Affected browsers: Internet Explorer 11
- WebCam: Logitech HD Webcam C525

## 2) Expected behavior
When using Internet Explorer 11, the page https://www.primefaces.org/showcase/ui/multimedia/photoCam.xhtml should show a video of a connected webcam. In the absense of supporting browser api, the PhotoCam component should fall back to using flash.
I found a working integration of the camera using flash on https://www.onlinemictest.com/webcam-test/

## 3) Actual behavior
Although a flash file is loaded, no camera picture is shown. 

## 4) Steps to reproduce
Open https://www.primefaces.org/showcase/ui/multimedia/photoCam.xhtml in IE 11.  This problem probably has somethong to do also with the specific model of the webcam. So maybe you are not affected.

**Comment by melloware** [comment]
Most likely related to this issue with the underlying PhotoCam code: 
https://github.com/jhuckaby/webcamjs/issues/151
https://github.com/jhuckaby/webcamjs/issues/67

This patch may work...
https://github.com/jhuckaby/webcamjs/pull/70

**Comment by AlexKolesnik** [comment]
> 
> 
> Most likely related to this issue with the underlying PhotoCam code:
> [jhuckaby/webcamjs#151](https://github.com/jhuckaby/webcamjs/issues/151)
> [jhuckaby/webcamjs#67](https://github.com/jhuckaby/webcamjs/issues/67)
> 
> This patch may work...
> [jhuckaby/webcamjs#70](https://github.com/jhuckaby/webcamjs/pull/70)

Inside the primefaces archive I can only find META-INF\resources\primefaces\photocam\webcam.swf.

When I replace this file with your version https://github.com/jhuckaby/webcamjs/raw/b93a0d4fc1be3d07482dedab86ca0e924ac925ef/webcam.swf , then I can indeed see a camera picture. The picture is a bit scaled up though and when I take a snapshot the size is different again.

To conclude.. your patch almost works.

But thank you very much, we are on the right track.

**Comment by melloware** [comment]
OK so yeah it looks like that solution was to fix the IE11 stuff.  it might not be perfect but at least it now works in IE11.
