### ISSUE TITLE
ConfirmDialog: global="true" needs appendTo="${idOfTheForm}" to be able to update the confirmDialog

### ISSUE THREAD

**Issue by vbalrog** [primefaces/primefaces#4096]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: WildFly 10, Mojarra 2.2.12-jbossorg-2 20150729-1131
- Affected browsers: Firefox 62.0.2

## 2) Expected behavior

When an update is done on a confirmDialog with global="true" (ex to change language of the page), the "yes" and "no" buttons of the confirmDialog must be well updated (in my case when I change language to English, buttons text will be "yes" and "no")

## 3) Actual behavior
The message of the confirmDialog is well updated (language selection to fr, text to fr etc). But the "yes" "no" buttons are not updated, stays to the previous language. And the update is done on the whole form. (in my code example "mainForm"). Problem I found in the DOM is that global confirmDialog id is well formed ("mainForm:idConfirmDialog") but the dialog itself is outside the <form id="mainForm >...</form>. With appendTo="mainForm" attribute to the confirmDialog, id is still good, and update is working well, on message and buttons "yes" and "no". If it is the expected behaviour it should be good to update documentation and showcase accordingly.

## 4) Steps to reproduce

Having a command button able to update something about the "yes" "no" buttons of the confirm dialog (text, language etc).
.. 

## 5) Sample XHTML
```
<h:form id="mainForm">
...
   <p:selectOneMenu
    	value="#{languageForm.selectedLanguage}" >
    	<p:ajax 
    	    	event="change"
    	    	listener="#{languageController.valueChangeListener}"
    	    	process="@this" 
    	    	update="mainForm" />
    	<f:selectItems value="#{languageForm.selectableLanguages}" />
   </p:selectOneMenu>
...
   <p:dataGrid 
      rowIndexVar="rowIndex"
      value="#{aForm.aListOfThings}" 
      var="aThing">
...
      <p:commandButton
          	title="#{msgs['applicationMessage.delete']}"
         	actionListener="#{aController.delete(aThing)}"
          	icon="ui-icon-trash"
	        process="@this" 
          	update="growl" >
    	    	<p:confirm message="#{of:format1(msgs['applicationMessage.deletion.confirmMessage'], rowIndex+1)}" />
      </p:commandButton>	
...
   </p:dataGrid>
   <p:confirmDialog
    	id="confirmDialog"
    	global="true"
    	header="header" 
    	severity="alert">
    	   <p:commandButton value="#{msgs['applicationMessage.yes']}" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
           <p:commandButton value="#{msgs['applicationMessage.no']}" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
   	</p:confirmDialog>
</h:form>
```
..

## 6) Sample bean

..
## 7) Workaround
...
<p:confirmDialog
    	**appendTo="mainForm"**
    	id="confirmDialog"
    	global="true"

**Comment by tandraschko** [comment]
Please provide a runnable example (a small as possible xhtml + bean)

**Comment by tandraschko** [comment]
Will close it for now. Feel free to open a new issue if you got a runnable example / primefaces-test fork.
