### ISSUE TITLE
Schedule: Does not resize correctly when min/maxTime set

### ISSUE THREAD

**Issue by KimGabrielsen** [primefaces/primefaces#4097]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:
I'm using PF 6.2 and the theme Serenity 1.0.4
Payara 5.183

I have build PF 6.3 from source and the problem persists.
 
## 2) Expected behavior
I would have expected the schedule to size according to the number of timeslots in a day in agendaWeek view
...

## 3) Actual behavior
The schedule overflows the expected size of the time slots when restricted with min and maxTime 

As far as I can tell it's because the height is calculated wrong.
.

//inline
element {
    overflow: hidden;
    height: 927px;   <-- this is wrong. If I disable it in my browser it look perfect.
}

//schedule.css line 959
.fc-time-grid-container, .fc-time-grid {
    position: relative;
    z-index: 1;
}

//schedule.css line 850
.fc-view-container *, .fc-view-container ::before, .fc-view-container ::after {
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
}
.

## 4) Steps to reproduce
Simply run the sample included here.
.. 

## 5) Sample XHTML

`
<p:schedule id="schedule" value="#{calenderController.eventModel}" widgetVar="myschedule" timeZone="GMT+2"
                    rightHeaderTemplate="" view="agendaWeek" allDaySlot="false"  
                    minTime="09:00:00" maxTime="17:00:00" />

`

## 6) Sample bean

.
import java.io.Serializable;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import lombok.Data;
import org.primefaces.model.DefaultScheduleModel;
import org.primefaces.model.ScheduleModel;

@Data
@Named
@RequestScoped
public class CalenderController implements Serializable {
    private ScheduleModel eventModel = new DefaultScheduleModel();
}
.

**Comment by KimGabrielsen** [comment]
It seems like the XHTML page did not occur correctly.
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <p:schedule id="schedule" value="#{calenderController.eventModel}" widgetVar="myschedule" timeZone="GMT+2"
                    rightHeaderTemplate="" view="agendaWeek" allDaySlot="false"  
                    minTime="09:00:00" maxTime="17:00:00" />
    </h:body>
</html>

**Comment by KimGabrielsen** [comment]
Sorry for not including a full XHTML file. but it will not show correctly. Only the header is shown. So I have included the simple schedule call I'm using. Itøs just embedded in a simple XHTML file.

**Comment by tandraschko** [comment]
@OBreidenbach would you like to check this? :)

**Comment by OBreidenbach** [comment]
If I understand the failure description correct, their is already a ticket for it at full calendar:
https://github.com/fullcalendar/fullcalendar/issues/4314
So, not much we can do about it at the moment.

**Comment by OBreidenbach** [comment]
As described here  (https://github.com/fullcalendar/fullcalendar/issues/4314#issuecomment-427185432) you could set the height to auto. 
```
<p:schedule ... extender="initSchedule"/>
<script>
  function initSchedule() {
    this.cfg.height="auto";
  }
</script>
```

**Comment by tandraschko** [comment]
Thanks, so i can just close it :)
