### ISSUE TITLE
Chips:  truncate items with double quote

### ISSUE THREAD

**Issue by MatthSHo** [primefaces/primefaces#4099]
1) Environment
PrimeFaces version:
6.1 & 6.2
Application server + version: Wildfly 10.1.0
Affected browsers: Chrome

2) Expected behavior
when adding items to chip I expect that all item gets added

3) Actual behavior
When adding an item with double quotes " the items get added until " is reached.
For instance adding : this is a "double quoted part"
The chip list will contain only : this is a 

4) Steps to reproduce
[primefaces-test-chips-with-dblQuote.zip](https://github.com/primefaces/primefaces/files/2433990/primefaces-test-chips-with-dblQuote.zip)

run and try to add an item with " in the chips, you will see in the UI and in the log that second partt of item is ignored
5) Sample XHTML
6) Sample bean
both in the attached project

Bug linked to forum in https://forum.primefaces.org/viewtopic.php?p=170481

**Comment by melloware** [comment]
Thanks for posting the sample project!  Let me verify.

**Comment by melloware** [comment]
OK I can reproduce your issue with 6.2 but if I use 6.3-SNAPSHOT it appears to be working fine:

![image](https://user-images.githubusercontent.com/4399574/46291631-00273500-c55d-11e8-8036-400817ccc7e3.png)

**Comment by MatthSHo** [comment]
Ok thanks, that is an already fixed bug then :)
I'll wait for 6.3 !

**Comment by tandraschko** [comment]
always try with a source build first :P

**Comment by kukel** [comment]
Then maybe 'nightly' snapshots should be introduced. Waaaay better/easier than to ask 'normal users' of PF to create source builds.
