### ISSUE TITLE
ColumnToggler compatibility with Scrollable DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#41]
Add support for columnToggler in a scrollable datatable.

**Comment by andrespontt** [comment]
I think this should be the expected behavior (using jquery datatables):

http://plnkr.co/edit/xQzMy1TVd8zmpOYZA2tf?p=preview

**Comment by cagataycivici** [comment]
Added support for scrollable datatable, note that frozen columns + column toggler not yet supported.
