### ISSUE TITLE
Add model attribute to SplitButton

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4106]
A menu model instance to create the items of splitButton programmatically.

**Comment by Rapster** [comment]
Great job! Is it possible to create the default action through the model instance?

**Comment by Rapster** [comment]
Might close #766 and #4010

**Comment by melloware** [comment]
@Rapster I agree it should definitely close those two with links to this ticket.

**Comment by mertsincan** [comment]
@Rapster 

> Is it possible to create the default action through the model instance?

No, to create menuitems and submenus in panel
