### ISSUE TITLE
OutputLabel in DataTable does not make selection

### ISSUE THREAD

**Issue by NilsonUehara** [primefaces/primefaces#411]
When `<p:outputLabel>` is included in `<p:dataTable>`, the selection not works.

```
<p:dataTable value="#{myMB.lista}" var="v" selectionMode="single" selection="#{myMB.reciboVerba}" rowKey="#{v.id}">
  <p:ajax event="rowSelect" update=":edit" oncomplete="PF('dlgEdit').show()"/>
  <p:column headerText="Valor" width="100" style="text-align: right;">
    <p:outputLabel value="#{v.valor}"><f:convertNumber pattern="#,##0.00"/></p:outputLabel>
  </p:column>
</p:dataTable>
```

**Comment by cagataycivici** [comment]
It is not supported, use h:outputText instead. OutputLabel is useless in your case as it has no for attribute.

We can support it but it is not common to use as outputText is the way to go. If more users required it, we'll reopen.
