### ISSUE TITLE
FileUpload: Shaded ValidationException class not found

### ISSUE THREAD

**Issue by Helveticus** [primefaces/primefaces#4111]
## 1) Environment
- PrimeFaces version: 6.3
- Does it work on the newest released PrimeFaces version? Yes
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 9.0
- Affected browsers: FF

## 3) Actual behavior

My custom exception handler picks up this exception on each and every file upload:

03-Oct-2018 09:56:29.087 SEVERE [http-nio-8080-exec-9] Custom handler caught exception: java.lang.NoClassDefFoundError: org/primefaces/shaded/owasp/esapi/errors/ValidationException

The snapshot jar shaded tree stops at the 'esapi' level.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
should work now, please try again

**Comment by Helveticus** [comment]
I ended up having to include these 2 additional classes before the file upload worked. It is possible that there are other dependencies lurking:

org/owasp/esapi/errors/EnterpriseSecurityException.class
org/apache/commons/io/FilenameUtils.class

**Comment by tandraschko** [comment]
Updated, please give it a try.

**Comment by Helveticus** [comment]
Seems to work now. Thank you!
