### ISSUE TITLE
ChartJs: CartesianAxis add Labels attribute

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#4112]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2.9
- Does it work on the newest released PrimeFaces version? No Version? 6.2.9
- Does it work on the newest sources in GitHub? (Build by source -> not tested because no changes https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Payara 5.182
- Affected browsers: all

## 2) Expected behavior

it should be possible to set Labels not only global but also per Axis. 

## 3) Actual behavior

Actual it is only possible to set labels global.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..
## 7) Expected ChartsJs Config content:
```
options: {
        scales: {
            xAxes: [{
                type: 'category',
                labels: ['January', 'February', 'March', 'April', 'May', 'June'],
            }]
        }
    }
```
## 8) ChartJs Website Link:
[https://www.chartjs.org/docs/latest/axes/cartesian/category.html](url)

**Comment by melloware** [comment]
OK it looks like this is already possible.  Here is the Javadoc of CartesianAxes.

```java
/**
 * If global configuration is used, labels are drawn from one of the label arrays 
  *   included in the chart data.
 * 
 * If only data.labels is defined, this will be used. 
 *    If data.xLabels is defined and the axis is horizontal, this will be used.
 * 
 * Similarly, if data.yLabels is defined and the axis is vertical, this property will be used.
 * 
 * Using both xLabels and yLabels together can create a chart that uses strings 
 * for both the X and Y axes. CartesianCategoryAxes extends {@link CartesianAxes}.
 */
```

So it looks like it will use the Global config or you can use data.labels or data.xLabels.  Can you give it a shot?

**Comment by markusg80** [comment]
@melloware : The Javadoc is from **CartesianCategoryAxes**. But there i cant see any parameter for example:

```
setLabels(List<String> labels)
```
I only can see inside **CartesianCategoryTicks** a method in this direction. But it seeams that it has no effect.

**Comment by melloware** [comment]
@mertsincan can weigh in here he wrote the javadoc that says that so I was assuming it is possible.  I agree I don't see any way to set this either.  I can definitely add it.
