### ISSUE TITLE
Dialog: centered on document height iso window height

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#4115]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No.
- Does it work on the newest sources in GitHub? No
- Application server + version: EAP 7.0
- Affected browsers: All

## 2) Expected behavior

Dialog always centered in the middle, independent of screen size, browser, resolution etc. Like in Primefaces showcase. When for instance maximizing your browsers window and having still a scrollbar (it means the HTML document is bigger then your browser window), the dialog nicely fits into the middle of the window.

## 3) Actual behavior

When having very large documents, where the document height is two or three times the window height, the dialog falls of the screen and is not visible anymore. However, on the Primefaces showcase this is not the case. There it is always centered on window, iso document. 

## 4) Steps to reproduce

Use sample below and resize your browser untill a scrollbar appears. Then click the button to show the dialog. 

## 5) Sample XHTML

```
<html lang="nl" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">
<h:head>

</h:head>

<h:body>

    <h:form id="show">
        <p:commandButton value="Test" onclick="PF('dialog').show();" />
    </h:form>

    <p:dialog id="dialog" header="dialog" widgetVar="dialog" modal="true" height="100">

        <h:form id="refresh">
            <p:button onclick="document.location.href = document.location.href;" value="Refresh" />
        </h:form>

    </p:dialog>

    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>
    <p>test</p>

</h:body>
</html>
```

## 6) Sample bean

NA

**Comment by ghost** [comment]
@tandraschko Putting the label on 'enhancement' means following things:

- centering on window height is OK. Meaning current implementation (6.2.x) is correct. It also means that dialogs on screens where document is a lot larger then window height, will always fall of screen... 

- Primefaces showcase is showing wrong behaviour, since it centers on document height, which is not OK, it should be window height...

Is this correct? I would expect the label should be 'defect', since we do not absolutely want the dialog fall of the screen when the document height is a lot larger the window height. We always want the dialog centered on the window, just like on the Primefaces showcase...

**Comment by tandraschko** [comment]
Enhancement often means for me: the old behavior is not the nicest, lets do it better

**Comment by comfortandintensity** [comment]
@tandraschko could you confirm then the dialog in the Primefaces showcase is not working as designed?

**Comment by ghost** [comment]
@tandraschko Okay I found the issue. The solution to this problem is to add <!DOCTYPE html> to the head of the page and the behavior is as desired. Then and only then it will center on window height iso document height... ^^

Yes I know, eyes popping out of disbelief... Let me document how I found this, because it is an important issue that has impact on other components as well... I was having an issue when we had datatables with reflow = true, it was showing very broken rendering when going in responsive mode. The issue is explained here:

https://stackoverflow.com/questions/10556310/displayblock-not-working-in-chrome-or-safari

Solution: add the doctype declaration. This was in our application number 2.

In application number 1 we were using dialogs and not working as expected. We didn't declared doctype. Since we couldn't find the issue we created this issue here on github.

Meanwhile, we were starting with application 3, which had databales with reflow true AND dialogs AND doctype declaration. Suddenly the dialog broken behavior was gone. So after doing a lot of research, the conclusion was that the only difference was the doctype declaration. Of course, we didn't believe that this could change the behavior, but since we had our problem of our datatable as stated before, we just went for it. Adding now doctype declaration to application number 1, now everything worked fine.......

Conclusions: 

1. Without doctype declaration, it never works in FF, Chrome, Safari, ... meaning the dialog centers on document height iso window height. To make it work, add the declaration: <!DOCTYPE html>
2. The HTML5 specification declares that a doctype is optional: https://www.w3.org/TR/2014/REC-html5-20141028/the-xhtml-syntax.html#writing-xhtml-documents. Section 9.1 states: 

> XML documents may contain a DOCTYPE if desired, but this is not required to conform to this specification.

 In fact, Primefaces then should still work without doctype declaration.

3. Although doctype declaration is optional for HTML5 documents, Primefaces has at least two components which needs this declaration (datatable and dialog), it should be mandatory for using Primefaces.
4. I have this issue since using 6.0. Before i don't know if this behavior was present
5. At least the documentation of Primefaces since 6.0 should be altered with an important warning to force users to always use the doctype declaration, otherwise components could have broken behavior.
6. The Primefaces showcase has the doctype declaration, and therefor is working as expected. However, nowhere is mentioned doctype declaration is mandatory. Maybe doctype declaration was always around and therefor never caused issues internally... 


I hope this doctype declaration will find the documentation soon... ;-)

**Comment by tandraschko** [comment]
Lets close it for now. It's more a browser problem then.

**Comment by ghost** [comment]
@tandraschko If I may, aren't we getting a little bit to light over it? :-) 

See it this way: user download primefaces, user wants to start using dialogs on large pages.... user notices dialog falls of screen and concludes it is not working (and of course he applied the fact that doctype declarations are optional and didnt add it to his page). For this user, primefaces is faulty, because on any browser it will always display wrong.

By the way, it are not the browsers who are responsible, but jQuery. It uses the doctype to make calculations of positions... If the issue was only on specific browsers and their version, I agree to get this closed, but in this case, it is independent of any browser and for sure not a browser issue.

So, I would like to insist to kindly ask to at least add it to the documentation. A small paragraph in the second chapter would be more then enough.

**Comment by tandraschko** [comment]
I understand you but we have the doctype everywhere in our getting started, showcase, primefaces-test project and so on.
