### ISSUE TITLE
Calendar: readonly attribute not working

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#4119]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: Tomcat 8.0
- Affected browsers: any

## 2) Expected behavior
When setting the attribute readonly="true", mode="popup", showOn="button", I expect a p:calendar to be read-only, so that the user cannot change its value. I expect the popup button to be disabled.
When setting the attribute readonly="true", mode="popup", showOne="focus", I expect a p:calendar to be read-only, so that the user cannot change its value. I expect that nothing happens when the text input component gains focus.

## 3) Actual behavior
When setting the attribute readonly="true", mode="popup", showOn="button", the user can still press the popup button and open the date selection dialog. From there, the user can select a date/time and the p:calendar text input value is changed accordingly. No "dateSelect" Ajax event is fired though.
When setting the attribute readonly="true", mode="popup", showOn="focus", the date selection dialog still opens as soon as the text input component gains focus. From there, the user can select a date/time and the p:calendar text input value is changed accordingly. No "dateSelect" Ajax event is fired though.

## 4) Steps to reproduce
Add a p:calendar component and set its readonly attribute to "true".

## 5) Sample XHTML

```xhtml
<p:calendar readonly="true" mode="popup" showOn="button" value="#{myBean.dateProp}">
  <p:ajax event="dateSelect" action="#{myBean.onDateSelect()}}" />
</p:calendar>
```

## 6) Sample bean

```java
public class MyBean {
  private Date dateProp;
  public Date getDateProp() { return dateProp; }
  public void setDate(Date date) { dateProp = date; }
  public void onDateSelect() { System.out.println("event"); }
}
```

## 7) Additional note

Seems to be the same as #488, but I still reproduce on 6.2.
Also, the suggested solution to use `readonlyInput` instead of  `readonly` does not work for me (I see the same behaviour, plus the `dateSelect` event is fired) and sounds like in contrast with what the documentation says: "Makes **input text** of a popup calendar readonly" (not the whole component).

**Comment by melloware** [comment]
From reading that thread @mauromol I think the property you want is "disabled=true" not readonly right?

Disabled i think would disable the button and text entry from happening.

**Comment by mauromol** [comment]
Yes, but `disabled` is not `readonly`. If I set `disable=true`, not only the button is disabled, but also the input text. 
Just to mention one difference between `disabled=true` and `readonly=true` for an input text, with Firefox you can't select and copy text in a disabled input text, while you can in a readonly one.

So, definitely, having `readonly=true` work correctly for Calendar would be highly desirable.

**Comment by melloware** [comment]
OK you have convinced me. 😄
