### ISSUE TITLE
Dialog: provide client side API to change position (and center on the screen)

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#4120]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: Tomcat 8.0
- Affected browsers: Firefox 62, Chrome 69

## 2) Expected behavior
I'd like to have some client side API to change the dialog position, at least after it has been shown.

## 3) Actual behavior
Currently, the only documented client side API for Dialog component consists of `show()`, `hide()` and `isVisible()`.
Since p:dialog is suffering from a wrong positioning whenever its contents is subject to resizing (see https://stackoverflow.com/questions/31920349/primefaces-pdialog-is-not-centered-when-combined-with-pschedule as an example, but I experience this with p:textEditor components as well), a workaround could be to reposition the dialog on center after showing (using the `onShow` client side callback), but there's no such documented API available at the moment.

**Comment by NicolaIsotta** [comment]
It's not documented, but I use initPosition() when I update the dialog content.
https://github.com/primefaces/primefaces/blob/90d5f0583663df7124278d47ed5bec11672deaef/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L312

**Comment by mauromol** [comment]
Thanks Nicola for the hint, it works! Let's hope this to be "promoted" as a public API.

**Comment by melloware** [comment]
So @mauromol would renaming initPosition() in the widget to just "position()" or "center()" be what you mean?   Or are you saying just add it to the PF documentation?

**Comment by mauromol** [comment]
This is up to you, for me it's the same. If `initPosition()` just centers the dialog, probably `center()` is more appropriate, but if resets the dialog position according to the `p:dialog` `position` attribute, then probably `initPosition()` or `resetPosition()` sounds more appropriate.

**Comment by mauromol** [comment]
Thank you! :+1:
