### ISSUE TITLE
PanelGrid: component causes invalid HTML and broken AJAX communication

### ISSUE THREAD

**Issue by abelet** [primefaces/primefaces#4122]
## Environment ##
- PrimeFaces version: tested with 6.2, 6.2.9
- JSF 2.3

## Maven project demonstrating the problem ##
[jsf-ajax-failure.zip](https://github.com/primefaces/primefaces/files/2450527/jsf-ajax-failure.zip)

## Problem with the implementation ##

JSF components are not perfect. Their implementations can have some faults. For example the primefaces PanelGrid component is liable for not closing table rows. It does not close the last row if “actual number of columns” cannot be divided by the “value of columns attribute” without a remainder.   For example the following JSF fragment:

```xml
<p:panelGrid columns="2" >
    <h:outputLabel value="x"/>
    <h:outputLabel value="x"/>
    <h:outputLabel value="x"/>
</p:panelGrid>
```
produces a HTML table missing a closing TR tag:

```html
<table id="form:j_idt5" class="ui-panelgrid ui-widget" role="grid">
    <tbody>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
        </tr>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
    </tbody>
</table>
```

The JSF fragment cannot be blamed for the problem. It is a natural need to have 2 components in the first and 1 in the second row. So the PanelGrid implementation is wrong, but the improper HTML will be rendered perfectly by the browser. Unfortunately the JSF implementation can make from this mistake an unrecoverable error. But before describing how and in in which circumstances it is done, I have to outline the relevant elements of the JSF implementation.

## Description of the JSF implementation relevant parts ##

The com.sun.faces.renderkit.html_basic.HtmlResponseWriter provides a functionality for renaming HTML tag names generated by JSF Components. With this implementation the following JSF code:

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
   xmlns:h="http://java.sun.com/jsf/html"
   xmlns:ui="http://java.sun.com/jsf/facelets"
   xmlns:pass="http://xmlns.jcp.org/jsf/passthrough"
>
      <h:outputLabel value="Welcome" pass:label_text="Welcome" pass:elementName="span"/>
</ui:composition>
```
will produce a HTML like this:

```html
<span label_text="Welcome">Welcome</span>
```

The key elements of the implementation are the following member variable and methods of the HtmlResponseWriter class:

```java
private LinkedList<String> elementNames;
public void startElement(String name, UIComponent componentForElement)
public void endElement(String name)
private String pushElementName(String original)
private String popElementName(String original)
private String getElementName(String name)
```
In general every JSF component has a renderer class with two major methods:

```java
public void encodeBegin(FacesContext context, UIComponent component)
public void encodeEnd(FacesContext context, UIComponent component)
```

In case of the outputLabel component the com.sun.faces.renderkit.html_basic.LabelRenderer class is the renderer class.
To put it simply encodeBegin method will call the startElement for creating the opening HTML tag, and the encodeEnd method calls the endElement to create the closing HTML tag. The LabelRenderer class provides the “label” element name parameter in the startElement call. But the startElement method will override this element name by calling the pushElementName method. The pushElementName will not provide the name itself, instead it calls the getElementName method for this. The getElementName will check if a pass-through attribute named elementName was provided. If so, it will return the value of this attribute instead of the original element name provided by the component’s renderer class. The pushElementName method will examine the original and the returned name. If they differ, the new one will be pushed into the elementNames stack, and this will be the one to be returned and written out. 
When a JSF component’s renderer class finally calls the endElement for the closing the tag it will call the popElementName passing the element name parameter along. If the elementNames field is null or empty, then the passed element name will be written out. Otherwise the last element which was pushed into the elementNames  stack will be returned and written out.

I have to mention another important change in the JSF implementation which is now can be found in version 2.3. In JSF 2.2.13 the pushElementName method had the following code fragment:

```java
if (original.equals("option")) {
    return original;
}
```
Which has been changed in JSF 2.3 to this:

```java
if (original.equals("option")) {
     if(elementNames == null) {
        elementNames = new LinkedList<>();
     }
     elementNames.push(original);
     return original;
}
```

## The way how PanelGrid implementation leads to broken AJAX communication ##

If you use a selectOneMenu, a PanelGrid component, and use JSF 2.3 your AJAX communication is likely to fail. Let’s make an example. We’ll have a main page with two links which will refresh parts of the page. When you click on a link two regions (selectOnePanel and panelGridPanel) will be refreshed / updated. For example:

```xml
<h:body>
  <h:form id="form">
    <p:commandLink update="selectOnePanel panelGridPanel" action="#{ajaxTestTabMB.doTabChange(0)}">
      <h:outputText value="/dummyPage.xhtml" />
    </p:commandLink>
    <p:commandLink update="selectOnePanel panelGridPanel" action="#{ajaxTestTabMB.doTabChange(1)}">
      <h:outputText value="/errorCaseSelectOne.xhtml" />
    </p:commandLink>
    <h:panelGroup id="selectOnePanel">
      <ui:include src="#{ajaxTestTabMB.firstPage}"/>
    </h:panelGroup>
    <h:panelGroup id="panelGridPanel">
      <ui:include src="#{ajaxTestTabMB.secondPage}"/>
    </h:panelGroup>
  </h:form>
</h:body>
```
We have 4 subpages, but I describe just 2, which are causing the trouble. So we have the errorCaseSelectOne.xhtml, which will be displayed in selectOnePanel

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:ui="http://java.sun.com/jsf/facelets"
>
      <p:selectOneMenu>
          <f:selectItem itemLabel="100"/>
      </p:selectOneMenu>

</ui:composition>
```
and the errorCasePanelGrid.xhtml which will be displayed in panelGridPanel

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
 xmlns:ui="http://java.sun.com/jsf/facelets"
 xmlns:p="http://primefaces.org/ui"
 xmlns:h="http://java.sun.com/jsf/html">

      <p:panelGrid columns="2" >
       <h:outputLabel value="x"/>
       <h:outputLabel value="x"/>
       <h:outputLabel value="x"/>
      </p:panelGrid>

</ui:composition>
```

When you click on the second link,  which calls doTabChange(1), an AJAX request will be sent to the server, and on the server side an AJAX response will be created. If the errorCasePanelGrid.xhtml specified 3 (instead of 2) for the columns attribute above, we would get:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>
          <changes>
                   <update id="javax.faces.Resource">
                             <![CDATA[<link type="text/css" rel="stylesheet" href="/jsf-test-app/javax.faces.resource/components.css.xhtml?ln=primefaces&amp;v=6.2" />]]>
                   </update>
                   <update id="form:selectOnePanel">
                             <![CDATA[<span id="form:selectOnePanel"><div id="form:j_idt19" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" role="combobox" aria-haspopup="true" aria-expanded="false"><div class="ui-helper-hidden-accessible"><input id="form:j_idt19_focus" name="form:j_idt19_focus" type="text" autocomplete="off" aria-expanded="false" /></div><div class="ui-helper-hidden-accessible"><select id="form:j_idt19_input" name="form:j_idt19_input" tabindex="-1" aria-hidden="true"><option value="" selected="selected" data-escape="true">100</option></select></div><label id="form:j_idt19_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label><div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div><div id="form:j_idt19_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="form:j_idt19_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="100" tabindex="-1" role="option">100</li></ul></div></div></div><script id="form:j_idt19_s" type="text/javascript">PrimeFaces.cw("SelectOneMenu","widget_form_j_idt19",{id:"form:j_idt19"});</script></span>]]>
                   </update>
                   <update id="form:panelGridPanel">
                             <![CDATA[<span id="form:panelGridPanel"><table id="form:j_idt20" class="ui-panelgrid ui-widget" role="grid"><tbody><tr class="ui-widget-content" role="row"><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td></tr></tbody></table></span>]]>
                   </update>
                   <update id="j_id1:javax.faces.ViewState:0">
                             <![CDATA[-6160204276543946460:5353968715620084221]]>
                   </update>
          </changes>
</partial-response>
```
But we specified 2, and the response will be:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<partial-response>
          <changes>
                   <update id="javax.faces.Resource">
                             <![CDATA[<link type="text/css" rel="stylesheet" href="/jsf-test-app/javax.faces.resource/components.css.xhtml?ln=primefaces&amp;v=6.2.9" />]]>
                   </update>
                   <update id="form:selectOnePanel"><![CDATA[<span id="form:selectOnePanel"><div id="form:j_idt19" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" role="combobox" aria-haspopup="true" aria-expanded="false"><div class="ui-helper-hidden-accessible"><input id="form:j_idt19_focus" name="form:j_idt19_focus" type="text" autocomplete="off" aria-expanded="false" /></div><div class="ui-helper-hidden-accessible"><select id="form:j_idt19_input" name="form:j_idt19_input" tabindex="-1" aria-hidden="true"><option value="" selected="selected" data-escape="true">100</option></select></div><label id="form:j_idt19_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label><div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div><div id="form:j_idt19_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="form:j_idt19_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="100" tabindex="-1" role="option">100</li></ul></div></div></div><script id="form:j_idt19_s" type="text/javascript">PrimeFaces.cw("SelectOneMenu","widget_form_j_idt19",{id:"form:j_idt19"});</script></span>]]>
                   </update>
                   <update id="form:panelGridPanel">
                             <![CDATA[<span id="form:panelGridPanel"><table id="form:j_idt20" class="ui-panelgrid ui-widget" role="grid"><tbody><tr class="ui-widget-content" role="row"><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td></tr><tr class="ui-widget-content" role="row"><td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td></tr></tbody></table>]]>
                   </span>
                   <update id="j_id1:javax.faces.ViewState:0"><![CDATA[-3598172727742462547:-7062186675995454000]]>
                   </update>
          </update>
</partial-response>
```
You probably remember the problem with the PanelGrid component’s renderer, where the following is generated:

```html
<table id="form:j_idt5" class="ui-panelgrid ui-widget" role="grid">
    <tbody>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
        </tr>
        <tr class="ui-widget-content" role="row">
            <td role="gridcell" class="ui-panelgrid-cell"><label>x</label></td>
    </tbody>
</table>
```

But in the AJAX response the last row is closed. Why? Because we have a selectOnePanel with an option in the AJAX answer. While writing out the option HTML tag in the HtmlResponseWriter class, the elementNames stack will be initiated. Once the elementNames stack become initiated, every single HTML tag opening will be pushed into it. In other words, writing out the option HTLM tag changes everything. When a component renderer calls the HtmlResponseWriter.endElement (in the encodeEnd method), the value of the name parameters doesn’t matter any more. The closing HTML tag will be read from the elementNames  stack. So when the PanelGridRenderer want to close the tbody element, it will close the tr element. Every time a renderer does not close an element which was opened, an extra element remains in the stack, which will cause unexpected closing tag names. The extra element is responsible for the invalid AJAX response above. For example before the partial-response tag an update tag has been placed instead of the changes tag. This is how the unclosed table row lead to an invalid AJAX response, and our application went wrong.

**Comment by tandraschko** [comment]
A PR would be great.

**Comment by abelet** [comment]
A partial response can be found in the description above.

**Comment by tandraschko** [comment]
i mean a Pull Request, to fix the issue

**Comment by jansohn** [comment]
@tandraschko is this also fixed in one of the elite releases?

**Comment by tandraschko** [comment]
Dont think so. Elite is up to @mertsincan. Can you merge it?
