### ISSUE TITLE
DataTable: With selectionMode=multiple it's not possible to select a row using the keyboard

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4123]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Yes Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
We should be able to select a row using the keyboard.

## 3) Actual behavior
When we use the keyboard to select a row using the checkbox, the row is not selected.

## 4) Steps to reproduce
1. Open https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml
2. Go to the datatable example with checkbox.
3. Use the keyboard to focus the checkbox of a row and press the key space.
4. The row is selected and unselected.

**Comment by wsaca** [comment]
It's working with PF 6.2, I will check the issue #3750 to see if it''s the cause.

**Comment by erickdeoliveiraleal** [comment]
maybe related to #3971

**Comment by wsaca** [comment]
Not really, I have resolved this issue locally but your problem was not fixed. I think it's better to create another PR to resolve it, maybe the events are lost when the jquery clone function is used.
