### ISSUE TITLE
Slider + InputNumber: Input does no longer update the slider

### ISSUE THREAD

**Issue by jthalmai** [primefaces/primefaces#4127]
## 1) Environment
- PrimeFaces version: **6.2**
- Does it work on the newest released PrimeFaces version?  **no - 6.2**
- Application server + version: **Wildfly 14.0.1**
- Affected browsers: **Firefox**

## 2) Expected behavior

When entering any input in the p:inputNumber field, the p:slider should immediately be updated as well.

## 3) Actual behavior

The slider is not updated. This worked in PrimeFaces 6.1 and still works for inputText instead of inputNumber.

## 4) Steps to reproduce

Just use the PrimeFaces showcase 'Slider / InputNumber Slider' and enter a number in the input field. The slider is not updated and stays in the '0' position.

## 5) Sample Code

See showcase

**Comment by tandraschko** [comment]
Please try a source build, should work actually.

**Comment by tandraschko** [comment]
works fine in trunk
