### ISSUE TITLE
Datatable: Row selection causes rendering to go in an infinite loop, when updating header from onRowSelect ajax event, and when rows attribute is not set

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#4128]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: jetty from primefaces-test
- Affected browsers: all

## 2) Expected behavior

 When row is selected, expect the row to be selected, and expect the application to continue running smoothly. 

## 3) Actual behavior

When row is selected, no response is received back from the ajax event, and the page is unresponsive.

On debugging, found that it is stuck in an infinite loop in UIData.visitRows
An observation is that this is because the rows attribute is missing from the datatable. However, it was not expected that this be stuck in an infinite loop. Also, everything else works without the rows attribute, for lazy datatable, as the scrollRows is set instead of rows.

## 4) Steps to reproduce

To reproduce use this test repo - https://github.com/amathew121/primefaces-test 

http://localhost:8080/primefaces-test/

On the datatable, click on any row to make a selection. 
At this point it will be stuck in an infinite loop, and other ajax actions (like scrolling) on the page will not work. You can also check the jvm taking up all the CPU.

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h1>#{testView.testString}</h1>

	<h1>#{testViewCdi.testString}</h1>

	<h:form id="tableForm">
		<p:dataTable var="car" value="#{dtLazyView.lazyModel}" scrollRows="20" scrollable="true" virtualScroll="true" scrollHeight="200" lazy="true"
			style="margin-bottom:0" selection="#{dtLazyView.selectedCars}" rowIndexVar="rowIndex">
			<f:facet name="header">
				<h:panelGroup id="usersSelection">
					<h:outputText value="#{dtLazyView.selectedCars.size()} cars selected" />
				</h:panelGroup>
			</f:facet>
			<p:ajax event="rowSelect" immediate="true" process="@this" partialSubmit="true" global="false" listener="#{dtLazyView.onRowSelect}"
				update="usersSelection" />
			<p:ajax event="rowSelectCheckbox" immediate="true" process="@this" partialSubmit="true" global="false" listener="#{dtLazyView.onRowSelect}"
				update="usersSelection" />
			<p:column selectionMode="multiple" style="width:16px;text-align:center" />
			<p:column headerText="Id">
				<h:outputText value="#{car.id}" />
			</p:column>
			<p:column headerText="Year">
				<h:outputText value="#{car.year}" />
			</p:column>
		</p:dataTable>
	</h:form>
	
	<h:form id="form">
		<p:growl id="msgs" widgetVar="msgsWV" showDetail="true" escape="false"
			sticky="false" autoUpdate="true" />
	</h:form>
	
</h:body>
</html>
```

## 6) Sample bean

**LazyView.java**

```
@Named("dtLazyView")
@ViewScoped
public class LazyView implements Serializable {

	private LazyDataModel<Car> lazyModel;
	private List<Car> selectedCars = new ArrayList<>();

	@PostConstruct
	public void init() {
		lazyModel = new LazyCarModel(new CarService().createCars(2000));
	}

	public LazyDataModel<Car> getLazyModel() {
		return lazyModel;
	}

	public void onRowSelect(SelectEvent event) {
		FacesMessage msg = new FacesMessage("Car Selected", ((Car) event.getObject()).getId());
		FacesContext.getCurrentInstance()
				.addMessage(null, msg);
	}

	public void setSelectedCars(List<Car> selectedCars) {
		this.selectedCars = selectedCars;
	}

	public List<Car> getSelectedCars() {
		return new ArrayList<>(selectedCars);
	}
}
```

**LazyCarModel.java**

```
public class LazyCarModel extends LazyDataModel<Car> {

	private List<Car> datasource;
    
	public LazyCarModel(List<Car> datasource) {
        this.datasource = datasource;
    }
     
    @Override
    public Car getRowData(String rowKey) {
        for(Car car : datasource) {
            if(car.getId().equals(rowKey)) {
				return car;
			}
        }
 
        return null;
    }
 
    @Override
    public Object getRowKey(Car car) {
        return car.getId();
    }
 
    @Override
    public List<Car> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String,Object> filters) {
        List<Car> data = new ArrayList<Car>();
 
        //filter
        for(Car car : datasource) {
            boolean match = true;
 
			if (filters != null) {
				// Ignore
            }
 
            if(match) {
                data.add(car);
            }
        }
 
        //sort
        if(sortField != null) {
			// Ignore
        }
 
        //rowCount
        int dataSize = data.size();
        this.setRowCount(dataSize);
 
        //paginate
        if(dataSize > pageSize) {
            try {
                return data.subList(first, first + pageSize);
            }
            catch(IndexOutOfBoundsException e) {
                return data.subList(first, first + (dataSize % pageSize));
            }
        }
        else {
            return data;
        }
    }

}
```

**Comment by tandraschko** [comment]
A PR would be great ;)

**Comment by ghost** [comment]
Sure. Will submit a PR.

**Comment by Rapster** [comment]
@amathew121 Did you figure a fix for this?

**Comment by ghost** [comment]
Sorry. I was busy and didn't get time to look into it. 

I checked again on the latest code, and the issue is not reproduced in the latest code (6.3-SNAPSHOT). On debugging i found that the VisitContext is FullVisitContext in 6.3 and PartialVisitContext in 6.2. I don't understand much about how all these (contexts) work, but I think for a partial ajax request you would still expect a PartialVisitContext.

Even though the issue is not reproduced in the latest code, it is still there and is not reproduced because the runtime path is different in the version due to the contexts.

**Comment by mrswadge** [comment]
We found an infinite loop scenario UIData if there are no rows in the table. 

https://github.com/primefaces/primefaces/blob/f709bc3c89178abadbc7711271d0cb32cdb279ea/src/main/java/org/primefaces/component/api/UIData.java#L1032-L1034

If rows is 0, the second half of the if clause is not executed, so processed increments infinitely whilst rows remains at zero.

**Comment by melloware** [comment]
@mrswadge Can you submit a PR with your fix?

**Comment by tandraschko** [comment]
reverted the PR as it breaks processing of a normal DataTable

**Comment by melloware** [comment]
I can't reproduce the original issue reported in this ticket with PF 8.0. So closing ticket.  @mrswadge if you have a reproducible test case for your issue please open another ticket.

**Comment by Rapster** [comment]
> To reproduce use this test repo - https://github.com/amathew121/primefaces-test

**Comment by melloware** [comment]
@Rapster I did and that repo is empty.  Its just the base test case the XHTML page is this...
```xml
    <h:body>

        <h1>#{testView.testString}</h1>

        <h1>#{testViewCdi.testString}</h1>

    </h:body>
```

**Comment by Rapster** [comment]
Oh yeah indeed 😓 Too bad...
