### ISSUE TITLE
Chartjs: Make Legend customizable

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#4129]
## 1) Environment
- PrimeFaces version: 6.2.9
- Does it work on the newest released PrimeFaces version? No Version? 6.2.10
- Does it work on the newest sources in GitHub? No because there are no commits relatet to this issue
- Application server + version:
Payara 5.183
- Affected browsers:
All

## 2) Expected behavior

It should be possible to set parameters for the options.legend namespace inside chartsjs. 
Reference chartjs Documentation: [Chartjs legend namespace docs](https://www.chartjs.org/docs/latest/configuration/legend.html).

Example:
```
var chart = new Chart(ctx, {
    type: 'bar',
    data: data,
    options: {
        legend: {
            display: true,
            labels: {
                fontColor: 'rgb(255, 99, 132)'
            }
        }
}
});
```

## 3) Actual behavior

Actually it's not possible to set legend position, font color or type and if its showing up or not.  I know in most cases i can set this with the extender, but sometime i like to change some settings dynamicly for example by the user. This is difficult to made because its hard to control javascript content from Managed Bean.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

## 7) Forum
[Primefaces Forum link](https://forum.primefaces.org/viewtopic.php?f=3&t=57092)

**Comment by melloware** [comment]
@mertsincan I think this would be a huge improvement as the Legend looks pretty customizable. WDYT?

I would think it needs to be its own JSON object like you have modeled the others because there are so many props to set.
