### ISSUE TITLE
datatable: cannot display information from selected rows of datatable in dialog

### ISSUE THREAD

**Issue by Kurti123** [primefaces/primefaces#4131]
I tried to implement the example from the datatable showcase w/ lazyloading with my own data from a database.

https://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml

I already implemented the example step by step with my own data model but whenever i click a row, i get an empty selectedCar result back to the dialog element. I tried downgrading the PF versions and as soon as I went down to 5.1, it started working. Versions 5.2 to 6.2 seem to be affected by this issue.

## 1) Environment
- PrimeFaces version: 5.2 - 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Could not compile them, get an error during compilation
- Application server + version: Glassfish 5.0 (25)
- Affected browsers: Firefox 62

## 2) Expected behavior

A dialog frame should open that displays the information of the selected row in the panelgrid.

## 3) Actual behavior

The display opens but the panelgrid remains empty (except for the hardcoded categories)

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

Exact the same as in the example from the link above

## 6) Sample bean

Exact the same as in the example from the link above

**Comment by tandraschko** [comment]
As the showcase works fine, we need a forked primefaces-test project, which a small as possible example, to check it.

**Comment by melloware** [comment]
Make sure you realize the LazyView is @ViewScoped so it remembers your selection.  If you use @RequestScoped it will lose your selection right away after you select it.

```java

@ManagedBean(name="dtLazyView")
@ViewScoped
public class LazyView implements Serializable
```

**Comment by Kurti123** [comment]
Thanks for your response.

@melloware: I had the lazyview set to @viewscoped, @sessionscoped and @applicationscoped but neither worked for me. 

@tandraschko: I'll provide a fork of our project today or tomorrow.

**Comment by melloware** [comment]
@Kurti123 A sample project would definitely help us figure out the issue.

**Comment by Kurti123** [comment]
@tandraschko: You can find the example code here: 

https://github.com/Kurti123/primeBugTest

If you change the PF version in the POM to 5.1, it works just fine.

**Comment by tandraschko** [comment]
you don't use the correct ViewScoped annotation.
