### ISSUE TITLE
Dialog: Modal dialog hides but overlay does not

### ISSUE THREAD

**Issue by Helveticus** [primefaces/primefaces#4133]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? Don't know
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 9.0
- Affected browsers: Mostly Chrome and Opera

## 3) Actual behavior

This is not so much a defect report as a fishing expedition for pointers how to track down the problem I am seeing.
Sporadically, a couple of my modal dialogs with an oncomplete="..hide()" button do hide the dialog proper, but the modal overlay does not get removed. It appears to be worse if the button actionlistener takes time (1-2 secs) and on certain browsers (Chrome).  This behavior is random, I cannot always reproduce it.   I am a mediocre JS debugger, but it appears to me that the dialog component hide() function immediately exits on the visibility test, as if something else had already hidden it, leaving dialog_modal behind.
I have spent a few days trying to track this down and have no idea what else to try.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

.<p:confirmDialog message="#{bundle.delete_confirmation}"
    id="verifyDeleteId" header="#{bundle.text_confirm}"
    severity="alert" widgetVar="verifyDelete">
    <h:panelGroup style="float: right">
        <p:commandButton id="linkDeleteConfirm"
            value="#{bundle.text_delete}" styleClass="button"
            process="@this #{inventory.tableComponentId}"
            update="#{inventory.panelComponentId}"
            actionListener="#{inventory.delete}"
            oncomplete="PF('verifyDelete').hide()"/>
        <p:commandButton value="#{bundle.text_cancel}"
            styleClass="button" onclick="PF('verifyDelete').hide();"/>
    </h:panelGroup>
</p:confirmDialog>

## 6) Sample bean

..

**Comment by tandraschko** [comment]
we don't have "inventory" bean - please provide a runnable example

**Comment by tandraschko** [comment]
Will close it for now. Feel free to open a new issue if you got a runnable example / primefaces-test fork.
