### ISSUE TITLE
Imagecropper: Change imagecropper to cropper.js and support StreamedContent API

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#4136]
## 1) Environment
- PrimeFaces version: **6.2.10**
- Does it work on the newest released PrimeFaces version? **No** Version? **6.2.10**
- Does it work on the newest sources in GitHub? **No - because long no changes here**
- Application server + version: **Payara 5.182**
- Affected browsers: **all**

## 2) Expected behavior

Image cropper should work with streamed Content and improve touch support

## 3) Actual behavior

at the moment there is only bad touch support and image cannot be set by streamedcontent

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
Feel free to provide a PR or sponsor it.

**Comment by markusg80** [comment]
I‘ve never developed a jsf component!  Its the reason why i alwas bet on prime 😉! So maybe at my holiday i will try to create this Component. Should i update existing imageCropper or create a new Component.

**Comment by melloware** [comment]
I think your suggestion of StreamContent was on Cagatay's list years ago as there is this open ticket: https://github.com/primefaces/primefaces/issues/12

**Comment by melloware** [comment]
Touch support should be improved with this PR: https://github.com/primefaces/primefaces/pull/4261

It doesn't fix your Dynamic Content issue but one thing at a time. 😄

**Comment by markusg80** [comment]
Yes i see! But why you not change to cropper.js? In my project i implement with javascript only without creating jsf component, and it works like a charm! The picture data i send as base64 src attribute! My Problem is only that i hav‘nt any experience in developing jsf Components and i‘m involved in many other projects at the moment. So till now it wasn‘t possible for me to find the time to recreate your cropper component

**Comment by melloware** [comment]
I always get the short term fix it for release or for people using the current component and since Chrome 70 broke JCrop we had to get that updated to fix the problem.   The longer term is rewriting the component entirely to use a newer plugin like cropper.js.  Also JCrop is creating modern version 3.0 as well so it will be up to PF what to switch to.

**Comment by melloware** [comment]
Closing this as a duplicate of https://github.com/primefaces/primefaces/issues/12

Touch support was added however.

**Comment by melloware** [comment]
See PR: https://github.com/primefaces/primefaces/pull/5256 for cropper.js switch.
