### ISSUE TITLE
jQueryMobile update for PrimeFaces Mobile

### ISSUE THREAD

**Issue by srbala** [primefaces/primefaces#414]
PrimeFaces Mobile currently uses JQM 1.4.4 release. JQM 1.4.5 was the maintainence release and it has been out for more then eight months.

Tested locally working also plays well PrimeFaces 5.2.

**Comment by cagataycivici** [comment]
Set to 5.3.

**Comment by srbala** [comment]
Posted pull request #428 to update JQM.
