### ISSUE TITLE
Spotlight: Body is still scrollable when the spotlight is shown

### ISSUE THREAD

**Issue by anhquande** [primefaces/primefaces#4140]
## 1) Environment
- PrimeFaces version: 6.3.0
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: Tomcat 8.5.15
- Affected browsers: ALL

## 2) Expected behavior
When the spotlight is visible, it should be already attached to the corresponding item.

## 3) Actual behavior

When the spotlight is visible, if the user scroll the page using mouse wheel then the position of the highlight area is fixed, but the content underneath is moved. It makes the spotlight mark the wrong area.

## 4) Steps to reproduce
- Go to current primefaces showcases: https://www.primefaces.org/showcase/ui/misc/spotlight.xhtml
- Do not enter anything in the form
- Click button SAVE

![primefaces-spotlight](https://user-images.githubusercontent.com/4417654/46941584-bfa2dd80-d06b-11e8-9f85-e3ddbf8801ff.png)

**Comment by tandraschko** [comment]
Melloware added a "blockScroll" atteibute. Thanks.
