### ISSUE TITLE
Build: release 6.0 compress failed

### ISSUE THREAD

**Issue by imosapatryk** [primefaces/primefaces#4144]
1) Environment
- PrimeFaces version: 6.0

2) Expected behavior

Build release compiles without any errors

3) Actual behavior

There is an error when `mvn clean install -Prelease`  

> Failed to execute goal net.alchim31.maven:yuicompressor-maven-plugin:1.3.3:compress (default) on project primefaces: Execution default of goal net.alchim31.maven:yuicompressor-maven-plugin:1.3.3:compress failed: Compilation produced 34 syntax errors. -> [Help 1]

4) Steps to reproduce

`git clone https://github.com/primefaces/primefaces.git

cd primefaces

git fetch --tags

git checkout 6_0

mvn clean install -Prelease`

**Comment by tandraschko** [comment]
6.0 is already released and we don't have branches for the community -> won't fix.

**Comment by imosapatryk** [comment]
What does it mean? It is not possible to build it in release profile on that tag?

**Comment by tandraschko** [comment]
Yep, seems so

**Comment by imosapatryk** [comment]
Could you at least explain why ?

**Comment by tandraschko** [comment]
Looks like it's related to JS compressing. Maybe the tag was done before the actual release and not refreshed. Don't know.
