### ISSUE TITLE
PickList: auto select checkbox in FireFox

### ISSUE THREAD

**Issue by awenger63** [primefaces/primefaces#4145]
## 1) Environment
- PF 6.2.10
- FireFox, not reproduce in Chrome

## 2) Expected behavior
When move/drop a line, with checkBox, chexbox is auto selected (checked) when mousedown if mouse pointer is NEAR checkBox

## 3) Actual behavior
No auto selection when line move

## 4) Steps to reproduce
use Showcase with FireFox : select a line of theme by the picture and move to right part => checkbox is now cheked !

**Comment by tandraschko** [comment]
@mertsincan Would you like to check it?

**Comment by melloware** [comment]
I think the culprit is somewhere in the code below where the checkboxclick gets set to false when dragging but in Firefox when letting go of the click its firing.

```javascript
.on('click.pickList', function(e) {
            //stop propagation
            if($this.checkboxClick||$this.dragging) {
                $this.checkboxClick = false;
                return;
            }
```

**Comment by mertsincan** [comment]
I'll check and get back to you.

**Comment by mertsincan** [comment]
I think this is a FF issue. Please see; https://bugzilla.mozilla.org/show_bug.cgi?id=787944

**Comment by melloware** [comment]
@mertsincan it looks like all the commenters say adding helper clone alleviates the issue for FF.

http://api.jqueryui.com/sortable/#option-helper

**Comment by melloware** [comment]
I submitted a PR with this fix.  Works fine now in Firefox 64.
