### ISSUE TITLE
DataTable: duplicate ContextMenu

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#4147]
## 1) Environment: 
Wildfly 11, PF 6.2.10 (newest), Browsers: IE 11, Chrome 69, (Firefox 62 works correctly!)
Bug introduced by commit 30f362708964bf4b77ac0aa81ed8cdac285a662f (T.Andraschko, 8/28)

## 2) Expected behavior
Old _contextMenu_ should disappear

## 3) Actual behavior
Duplicate contextMenu's.

## 4) Steps to reproduce

- Right click on `row 1` and activate the `menu 1`. (Test 1 message appears)
- Right click on `row 1`
- Right click on `row 2`

Now, menu 1 and menu 2 are both displayed on IE or Chrome. This does not happen, when the dialog is displayed freshly. Note, that ommitting `update="form"` leads to correct behavior, but can't be used as a workaround in my case.

## 5) Sample XHTML
``` html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui">
<f:view id="index" contentType="text/html">  <h:head />
  <h:body>
    <h:form id="form">
      <p:messages> <p:autoUpdate/> </p:messages>
      <p:dataTable value="#{[1,2]}" var="r" tableStyle="width:auto">
        <p:column>
          <p:commandButton id="cm" value="Row #{r}" />
          <p:contextMenu for="cm">
            <p:menuitem value="Menu #{r}" actionListener="#{test.test(r)}" update="form"/>
          </p:contextMenu>
        </p:column>
      </p:dataTable>
     </h:form>
  </h:body>
</f:view>
</html>
```
## 6) Sample bean
``` java
@ViewScoped @Named
public class Test implements Serializable {
  public void test(int i) {
    FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Test "+i));
  }
}
```
![image](https://user-images.githubusercontent.com/415392/47254699-10e50f80-d466-11e8-97bf-820b4b8e682a.png)

**Comment by Rapster** [comment]
Since you have the commit, did you try to figure where could be exactly the problem?

**Comment by mdzaebel** [comment]
The problem lies in `src/main/resources/META-INF/resources/primefaces/menu/menu.contextmenu.js`. Revoking this file in the commit to its former version fixes the bug and other 6.3 fixes work too. Thomas changed the way of how `contextMenus` are appended to the body. I'm sure, he is better in solving this issue, which in my view should be fixed before 6.3 RC1.

**Comment by tandraschko** [comment]
can't replicate it.

EDIT: can replicate it :D Just not in FF...

**Comment by mdzaebel** [comment]
Cool fix Thomas (adding 2 chars ;-). I tested it with a different application on the current master and it worked too (the above example on all browsers too). Furthermore all other fixes work, so the master is clean. Well done and thank you very much!
