### ISSUE TITLE
Unable to get property 'getElementsByTagName'

### ISSUE THREAD

**Issue by Neonell** [primefaces/primefaces#4148]
Hi everybody,

I've an issue with Primefaces 6.1 and JSF 2.2:

When I'm navigating into my application and coming back to a tab, it happens, sometimes, during the refresh of the Tab information that the Primefaces JS code throw a nullpointer exception:

SCRIPT5007: Unable to get property 'getElementsByTagName' of undefined or null reference
File: eval code (66), Line: 3, Column: 9950

This line show a primefaces JS code and point to:
{var n=h.getElementsByTagName("partial-response")[0];

where h is null apparently.

I looked on the internet about this problem and I found only one relevant post on a forum (already dated from 2 years almost) without any answers:  https://forum.primefaces.org/viewtopic.php?t=48982 

I'm also stuck with those PF and JSF Version. I cannot choose to upgrade or downgrade them.

Thanks a lot for the help if anyone can and wish you an awesome day,
Frédéric

**Comment by Rapster** [comment]
Please follow the issue template otherwise it will be closed as invalid

**Comment by Neonell** [comment]
Sorry it's a duplicate... We could totally remove it, after submitting an issue I saw a 404 Error, so I though that due to a timeout the submit didn't worked. 

But it's more GitHub who get a bug this time ;)

Thanks a lot by the way for the quick feedback!

**Comment by cnsgithub** [comment]
Yep, GitHub seems to have some problems today: https://status.github.com/messages
