### ISSUE TITLE
Datatable sorting lost on ajax refresh

### ISSUE THREAD

**Issue by nixj14** [primefaces/primefaces#415]
This appears to be a known bug.  It is originally referenced here https://code.google.com/p/primefaces/issues/detail?id=3887.  There also appears to be a good deal of javascript workarounds to correct the behaviour (http://stackoverflow.com/questions/10032356/pdatatable-loses-sort-column-and-order-after-ajax-refresh).  Is there a reason why this shouldn't work out of the box?  As stated in both the ticket and workarounds, the root cause appears to be in how the "ui-state-active" class is applied to the headers.

I developed my own jQuery hacks that would save the sorting state pre-ajax submission and restore the sorting state post-ajax submssion.  This has worked, but can be cumbersome depending on how many places on a page that ajax requests could occur.  There's also the maintenance nightmare as other developers may not know/understand what the hack/fix is for (although documented).

Another oddity that occurred today with respect to this was specific to not just ajax requests, but with non-ajax requests.  I found that if used a commandButton (ajax=false) and submitted to a method that was either void or returned NULL, I got the same behavior as ajax=true (meaning all columns reported back as sort enabled...ui-state-active).  It wasn't until I explicitly returned to the same navigation page (return "/foo/bar") that I avoided said behaviour.

I know this was first marked wont-fix and then marked future in the Google Code repository.  I wanted to pull it over into GitHub to keep it on the radar.

**Comment by cagataycivici** [comment]
Can you please provide a simple test.xhtml and TestView.java to help use replicate.

**Comment by nixj14** [comment]
I created a simple maven project here to illustrate the bug:

https://www.dropbox.com/s/i5n97pltctn93yq/primefaces_test.tar.gz?dl=0

**Comment by nixj14** [comment]
Just wanted to follow up and see if that example sufficiently supplied you with what you needed.

**Comment by cagataycivici** [comment]
This is now supported, set p:ajax event="sort" skipChildren="false".

#1183

Also check out

#1183

That enables preventing sort if an input is invalid inside.
