### ISSUE TITLE
schedule: URL events enable phishing attacks

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#4154]
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
Clicking at a schedule URL event should not enable the target site to access the window opener.

## 3) Actual behavior
By default, the target site is opened in a new browser window/tab by using `window.open(<url>, '_blank')` javascript. Therefore the target site has access to `window.opener` and is able to modify the `location ` for example, leading to potential phishing attacks.

## 4) Steps to reproduce

1. Just point the birthday party event in the showcase's `ScheduleView.java` to the example target site https://cnsgithub.github.io/foo/:
```java
	    DefaultScheduleEvent birthdayParty = new DefaultScheduleEvent("Birthday Party", today1Pm(), today6Pm());
	    birthdayParty.setUrl("https://cnsgithub.github.io/foo/");
```

2. Open up the [schedule showcase](http://localhost:8080/showcase/ui/data/schedule.xhtml) and click at the birthday party event.

3. Enjoy the party: the target site will show ![image](https://user-images.githubusercontent.com/13161711/47355535-ec856f00-d6c1-11e8-91c2-71dc3d41b537.png)
 while the showcase's location will have changed to a potential phishing site (in this case the genuine PrimeStore).

## 5) Sample XHTML
n/a

## 6) Sample bean
See 4).

## 7) Mitigation
Whenever links to untrusted sites are rendered with `target="_blank" ` or opened via javascript `window.open(<url>, '_blank')` accordingly, we must prevent access to `window.opener` by either setting `rel="noopener noreferrer" `or `opener=null`.

Further reading:

- https://cwe.mitre.org/data/definitions/1022.html
- https://mathiasbynens.github.io/rel-noopener/

Stay tuned, I'll try to provide a PR...

Could someone please add the security label?

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/4156

**Comment by melloware** [comment]
Nice work.  Searching for window.open in the PF codebase returned these places..

ButtonRenderer.java
contentflow.js
gmap.js
printer.js

Not sure if it's vulnerable anywhere but ButtonRenderer definitely looks like a candidate?

**Comment by cnsgithub** [comment]
Yep, that would have been the next step. :+1: `ButtonRenderer` is indeed another candidate. Feel free to fix those as well.

**Comment by cnsgithub** [comment]
Just an idea: we could also provide some built-in security for `LinkRenderer` and others by automatically adding `rel="noopener noreferrer"` per default if `target="_blank"` is specified and not specified differently, e.g. via parameter.

**Comment by cnsgithub** [comment]
Also affected:
- `SplitButtonRenderer`
- `ButtonRenderer`
- `LinkRenderer`
- `BaseMenuRenderer`
