### ISSUE TITLE
selectOneMenu: reset to old value when required=true

### ISSUE THREAD

**Issue by cavoirom** [primefaces/primefaces#4155]
## The bug

When I first select the "Value 1" item, it's fine. Then I select back to "Please Select". The required message was showed which is correct, however the value of selectOneMenu was reset the the previous value (in this case: "Value 1").

Debugging show that in the render phase, the selectOneMenu will compare the selected value with the item to know which one was selected. When we select "Please select", the submittedValue was null, then it get the old value from data model to mark the item selected, which is wrong.

## 1) Environment
- PrimeFaces version: 6.1
- MyFaces 2.0.8

## 2) Expected behavior
- The value "Please select" will display instead of previous value

## 3) Actual behavior
- Value was reset to previous valid value

## 4) Steps to reproduce
1. Select "Value 1"
2. Select "Please select"
.. 

## 5) Sample XHTML
```
<h:panelGroup id="inputWrapper">
	<p:selectOneMenu id="valueSelection" required="true" value="#{data.value}">
		<p:ajax event="change" update="inputWrapper" />
		<f:selectItem itemValue="" itemLabel="Please select" />
		<f:selectItem itemValue="1" itemLabel="Value 1" />
	</p:selectOneMenu>
	<p:message for="valueSelection" />
</h:panelGroup>
```
![selectonemenu_required](https://user-images.githubusercontent.com/756698/47357350-9ed42b00-d6f0-11e8-8379-3a7ba26c90b8.gif)

**Comment by tandraschko** [comment]
Its the same with h:selectOneMenu, isn't it?

**Comment by cavoirom** [comment]
> Its the same with h:selectOneMenu, isn't it?

@tandraschko yes, the h:selectOneMenu has the same behavior, did I do something wrong here?

**Comment by tandraschko** [comment]
Nope, it's expected. 
"Value 1" ist set on the server side and the last valid value.
If you select something invalid now and update the component, it's rendered with the last valid value.

"Please select" should actually not selectable, which can be done via "noSelectOption"

**Comment by cavoirom** [comment]
> Nope, it's expected.
> "Value 1" ist set on the server side and the last valid value.
> If you select something invalid now and update the component, it's rendered with the last valid value.

@tandraschko 
So the behavior is not consistent between components, I see the InputText still keep invalid value when it was updated?

One more hint: if I select the actual value (not empty) but got ValidatorException (which mean it also invalid value), then the selectOneMenu still keep that invalid value. I think these behavior is not consistent on user perspective.

**Comment by tandraschko** [comment]
Maybe a bit yes, see:
https://github.com/primefaces/primefaces/issues/3124
https://github.com/primefaces/primefaces/issues/2821

You can trigger a discussion on the jsf mailing list, maybe we can align it for the future.
