### ISSUE TITLE
LightBox: Overlay Panel is not displayed

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4161]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Yes Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
The panel should be displayed.

## 3) Actual behavior
The panel is not displayed.

## 4) Steps to reproduce
1. This case can be tested in the showcase with PF 6.3-SNAPSHOT.

This issue was introduced in this [commit](https://github.com/primefaces/primefaces/commit/c5bd47f4c8edaa0b987272bd704840b41f170d11#diff-2782592d3b0e81a72383e3d23536c97f)

**Comment by tandraschko** [comment]
set the default as server side as with the other components

**Comment by wsaca** [comment]
I'll take it into account the next time... Thanks...

**Comment by wsaca** [comment]
@tandraschko I thought this issue was resolved but that's not the case, could you check it again? The change was applied to the OverlayPanel component, but the LightBox component has not the property appendTo.

**Comment by tandraschko** [comment]
done
