### ISSUE TITLE
Gmap not open correctly.

### ISSUE THREAD

**Issue by hcmm** [primefaces/primefaces#4166]
## 1) Environment
- PrimeFaces version: 6.3.0

## 2) Expected behavior

map open correctly.

## 3) Actual behavior

map not open correctly.

## 4) Steps to reproduce

Just access https://www.primefaces.org/showcase/ui/data/gmap/basic.xhtml

## 5) Sample XHTML

n/a

## 6) Sample bean

n/a

**Comment by tandraschko** [comment]
It's related to the showcase - not the PF core - as we don't pay / use a API key: https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

Will ping PrimeTek about it and close the issue.
