### ISSUE TITLE
Editor: Bad update on Firefox

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#4167]
## 1) Environment
PF 6.3 Snapshot (current), Wildfly 11, Java EE 7, Firefox (only)

## 2) Expected behavior
Editor should show changes

## 3) Actual behavior
Only IE and Chrome show changes, but on Firefox, "true" is displayed rather than the content.

## 4) Steps to reproduce
- Browse sample in Firefox
- Click on"Add"
- All browsers show `p:textEditor` update ("add" added in front). Only FF displays "true" in `p:editor` 
## 5) Sample XHTML
``` xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head />
<h:body>
   <h:form>
      <p:editor value="#{test.val}" style="height:100px; width:900px" />
      <p:textEditor value="#{test.val}" style="height:150px; width:900px" />
      <p:commandButton value="Add" update="@form" actionListener="#{test.add}" />
   </h:form>
</h:body>
</html>
```
![grafik](https://user-images.githubusercontent.com/415392/47613391-caf40100-da8e-11e8-805a-1b34911648ef.png)

## 6) Sample bean
``` java
@ViewScoped @Named
public class Test implements Serializable {
   private String val="<p>test</p>";
   public String getVal() { return val; }
   public void setVal(String val) { this.val = val; }
   public void add() { val=val.replaceFirst("<p>", "<p>add "); }
}
```
`p:editor` is deprecated, but it should not be deleted for many years (PF 7). It has an important feature (source mode), for which it is possible to create e.g. tables at least manually. `p:textEditor` has no source mode but `pe:ckEditor` has all we need, comes from PE, is more heavyweight and has to be configured specially. The current Snapshot of PF and PE are only fitting for the release candidate. So `p:editor` should at least "_work_" while other bugs should not be fixed any more. If this bug will not be fixed, is there any workaround?

**Comment by mdzaebel** [comment]
Possible workaround could be to add `onclick="editor.saveHTML()"` to `p:editor`, but this doesn't work in a dialog, as it is closed by `saveHTML()`.

**Comment by tandraschko** [comment]
Ckeditor is heavyweight but there is no special config, just the dependency. 
If you provide a PR, i will apply it. Otherwise i wont invest time in a depreacted component.

**Comment by mdzaebel** [comment]
Thanks for the answer, which I expected. Note, that there is quite an effort for new clients to figure out, what's going wrong. As long `p:editor` is in PF, problems should be documented in the User Guide. May be, it's sufficient, to have a list of "_hard_" problems with `p:editor` by just referencing issues like this, as _wontfix_-issues will remain for years. So users can choose the right component in advance, rather than testing it all over again.

**Comment by tandraschko** [comment]
Feel free to provide a pull request for the documentation. We should probably mention that the editor is deprecated and has some problems.
Maybe @melloware or @Rapster is also interessted in improving the documentation here.

**Comment by Rapster** [comment]
I don't know much of p:editor and all the history. I think your suggestion is the best solution Thomas
