### ISSUE TITLE
Schedule: add dynamic properties to schedule event

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4168]
## 1) Environment
- PrimeFaces version: 6.3-snapshot
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
For some cases it would be handy to have additional attributes in a schedule event. For instance if on the client side some extra action is required as in #2451 or #3367.

## 3) Actual behavior
To add additional attributes the (Default)ScheduleEvent and the ScheduleRenderer must be overriden. 
Adding a map to the ScheduleEvent would make it much easier to add additional attributes.

**Comment by melloware** [comment]
I like this idea a lot.  This is different than the normal "extender" pattern since this is just adding new or custom properties to the ScheduleEvent itself.
