### ISSUE TITLE
p:datatable sort params not sent in request when using LazyDataModel

### ISSUE THREAD

**Issue by sachafournier** [primefaces/primefaces#417]
PF: 5.2

I have a lazy datatable with sort event defined in it. When I click a column, my SortEvent listener is not called. The request seem incomplete. According to the stack, _sortDir and _sortKey are missing from request parameter.

Not sure about this one but after digging a little bit in javascript code I think I found the origin of the problem. PrimeFaces.bcnu function is doing a "call" without "this" as first parameter.

After patching the following code in "PrimeFaces.bcnu" function, my issue disapear.

// I changed this line
var f = d[c].call(e);

// for this
var f = d[c].call(this, e);

**Comment by kukel** [comment]
Please edit your post and format the code...

**Comment by cagataycivici** [comment]
Could this be related to;

https://github.com/primefaces/primefaces/issues/23

Also please post your code so we can compare in our environment. The change you suggested is in very core.

**Comment by tandraschko** [comment]
Fixed by #721
