### ISSUE TITLE
SelectOneMenu: if in Dialog the selectBox is rendered at wrong position

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4180]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No, 6.3-SNAPSHOT
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No, 6.3-SNAPSHOT
- Application server + version: wildfly 11
- Affected browsers: FF

## 2) Expected behavior
If selectOneMenu is used inside a dialog the select box should be rendered below the component.

## 3) Actual behavior
The select box is rendered at the top left corner of the page.

## 4) Steps to reproduce
Put a selectOneMenu into a dialog.

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form>
            <p:dialog id="test" widgetVar="myDialog">

                <p:selectOneMenu value="#{myValue}">
                    <f:selectItem itemValue="1" itemLabel="1. Option"/>
                    <f:selectItem itemValue="2" itemLabel="2. Option"/>
                    <f:selectItem itemValue="3" itemLabel="3. Option"/>
                </p:selectOneMenu>
            </p:dialog>

            <p:commandButton value="Start Dialog" onclick="PF('myDialog').show(); return false;"/>
            <p:selectOneMenu id="test3" value="#{myValue}">
                <f:selectItem itemValue="1" itemLabel="1. Option"/>
                <f:selectItem itemValue="2" itemLabel="2. Option"/>
                <f:selectItem itemValue="3" itemLabel="3. Option"/>
            </p:selectOneMenu>
        </h:form>
    </h:body>
</html>
```

## 6) Sample bean
Not needed

![positionselectonemenuselection](https://user-images.githubusercontent.com/11403755/47719029-2dddc780-dc4a-11e8-9fd2-78d13bdce6f3.png)

## Testcase:
https://github.com/OBreidenbach/primefaces-test/tree/PF4180

**Comment by tandraschko** [comment]
Could you check which commit breaks it?

**Comment by OBreidenbach** [comment]
Do not know, but @mertsincan just got this ticket #4126 three weeks ago.
So maybe this commit https://github.com/primefaces/primefaces/commit/fd273ae5db33c871973391e4e5fd0fcb05bcf727 is the reason.

**Comment by mertsincan** [comment]
I could replicate it in 6.3-SNAPSHOT version. It works fine in elite versions.

**Comment by tandraschko** [comment]
Can you check it @mertsincan?

**Comment by mertsincan** [comment]
Unfortunately, I have to solve a problem three/four times to add 5.2.x, 6.2.x, 6.3 etc. ;)
