### ISSUE TITLE
TabMenu: menuitem does not at context path to url attribute

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4181]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? worked in 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) 6.3-SNAPSHOT, no
- Application server + version: wildfly 11
- Affected browsers: FF

## 2) Expected behavior

Behavior with 6.2. Is url is set to '/test.xhmtl' it results in <a ... href="/primefaces-test/test.xhtml">

## 3) Actual behavior

Behavior with 6.3-SNAPSHOT. Is url is set to '/test.xhmtl' it results in <a ... href="/test.xhtml">
The context path is not appended. Is the outcome attribute is used, the context path is added correctly.

## 4) Steps to reproduce

use sample XHTML and inspect generated html

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <p:tabMenu>
            <p:menuitem value="A" url="/test.xhtml"/>
            <p:menuitem value="A" outcome="/test.xhtml"/>
        </p:tabMenu>
    </h:body>
</html>
```
## 6) Sample bean
not necessary

**Comment by tandraschko** [comment]
was discussed many times in almost 5 tickets now :P it's expected and also mentioned in the migration guide.

**Comment by OBreidenbach** [comment]
Sorry for the noise, I should have check that before. :-/
