### ISSUE TITLE
Datatable: Wrong resolveStaticField result used in facelet tag

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#4185]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 7
- Affected browsers: Any

## 2) Expected behavior
Condering this facelet tag:
```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                ...>

    <o:tagAttribute name="value"/>
    <o:tagAttribute name="sortBy"/>
    
    <p:dataTable id="#{id}"
                 widgetVar="wv_#{component.id}"
                 value="#{value}"
                 var="item"
                 sortBy="#{sortBy}">

        <ui:insert/>

    </p:dataTable>
</ui:composition>
```

Intilization of this `<p:dataTable />` should not be a problem

## 3) Actual behavior
Later on, a business exception will be thrown since as DataTable#sortField is evaluated as "sortBy" (and it's a not a property of a bean). See DataTable#resolveStaticField:

```java
    public String resolveStaticField(ValueExpression expression) {
        if(expression != null) {
            String expressionString = expression.getExpressionString();
            expressionString = expressionString.substring(2, expressionString.length() - 1);      //Remove #{}

            return expressionString.substring(expressionString.indexOf(".") + 1);                //Remove var
        }
        else {
            return null;
        }
    }
```

The result of this algorithm will be "sortBy"

## 4) Steps to reproduce
Create a facelet tag, see above

## 5) Sample XHTML
See above

## 6) Proposal
First I came up with this (using regex):
```java
    @Override
    public String resolveStaticField(ValueExpression expression) {
        if (expression != null) {
            String expressionString = expression.getExpressionString();
            Matcher matcher = Pattern.compile("^#\\{\w+\\.(.*)\\}$").matcher(expressionString);
            if (matcher.find()) {
                return matcher.group(1);
            }
        }

        return null;
    }
```

But I'm afraid performance could be lower... Or should I make a simple test "if expressionString contains var"?

This benchmark makes me wonder though: https://www.logicbig.com/tutorials/core-java-tutorial/java-regular-expressions/performance.html

Improvements

- Move Pattern as a member (should save a lot of time)
- Should we create/update an util to parse that kind of expression?

**Comment by tandraschko** [comment]
It would not define it as defect - it's more an enhancement to work with an special omnifaces feature.

It would also be great if you could provide a UnitTest for it.

**Comment by Rapster** [comment]
Enhancement indeed :wink: I'll have a look regarding unit test, I must say I never wrote one of these before (PF related I mean...) :smile:

**Comment by tandraschko** [comment]
Please add an unittest, this is easy testable and the right path is to add unittests, if easy possible, before change core code - especially DT is error-prone.
If you need help, you can ping me.

**Comment by Rapster** [comment]
My bad, I forgot about this one

**Comment by mertsincan** [comment]
Hi @Rapster,

Where is the Milestone? 

Also, This issue is reported by a PRO User. 
Exp; filterBy="#{orderType}" is not working with this change.

**Comment by Rapster** [comment]
Hi @mertsincan 

My bad I forgot about the milestone, but in case it happens again in the future you can easily find the first tag the commit is in:

> git name-rev --tags --name-only 47d9f46edcf9da3982ceed4214118076094b828c

As a result:
> 7.0.RC1

Regarding the issue, you'll have to give me more details in a new ticket to explain what's not working? What is `orderType`? A param, a field? What's the expecting result?

**Comment by Rapster** [comment]
Reopened because of #5162

**Comment by Rapster** [comment]
Changes merged, then reverted and no matter good reason have been given... PR is still on hold for almost a year. Better to be closed
