### ISSUE TITLE
selectCheckboxMenu: label and tootip incosistent

### ISSUE THREAD

**Issue by ohlsen3000** [primefaces/primefaces#4196]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: Tomcat 8
- Affected browsers: Chrome

## 2) Expected behavior
selectCheckboxMenu will allways update label and tootltip when 'updateLabel' is set to true

## 3) Actual behavior
selectCheckboxMenu will under certain circumstances not update label and / or tooltip

## 4) Steps to reproduce
*Case 1:*
- Use ```selectCheckboxMenu``` with ```updateLabel="true"```
- Select some values (A,B,C) and submit the form - selected values are displayed correctly in label and tootip
- Use the deselect all select box

Expected: Values are deselected and label (comma separated List) is cleared

Actual: The selected Values in the textbox remain:
![image](https://user-images.githubusercontent.com/2226986/47900732-3880a280-de7e-11e8-8324-d7c647104553.png)

*Case 2:*
When long list of SelectItems are used (>20) the tooltipp will sometimes not be updated after removing items from the selection:
![image](https://user-images.githubusercontent.com/2226986/47908926-b51b7d00-de8e-11e8-9188-00fa148150bf.png)

## 5) Sample XHTML
```
<p:selectCheckboxMenu value="#{orderDetailView.pf}" id="items"
                                      filter="true" updateLabel="true"
                                      label="Please select"
                                      filterMatchMode="contains">
                    <f:selectItem itemLabel="A" itemValue="A"/>
                    <f:selectItem itemLabel="B" itemValue="B"/>
                    <f:selectItem itemLabel="C" itemValue="C"/>
                </p:selectCheckboxMenu>
```

## 6) Sample bean
```
public class Bean {
    List<String> pf = new ArrayList<>();

    public List<String> getPf() {
        return pf;
    }

    public void setPf(final List<String> pf) {
        this.pf = pf;
    }
}
```

**Comment by tandraschko** [comment]
Please try a source build - afair we fixed something in this place

**Comment by Rapster** [comment]
Yep #4057, sounds different but the fix provided by @OBreidenbach might fix this?

**Comment by ohlsen3000** [comment]
Unfortunately the current 6.3-SNAPSHOT shows the same behaviour.

**Comment by OBreidenbach** [comment]
Did you set the emptyLabel attribute when using the 6.3-SNAPSHOT? It is the text that is shown when no item is selected. 
The label attribute is used for validation messages.

**Comment by ohlsen3000** [comment]
Hi @OBreidenbach, I have the  ```label``` set to something like 'Please choose...'. Has it been renamed in 6.3?

**Comment by OBreidenbach** [comment]
No not renamed. But a new one is added. The label attribute is used in validation messages.
Name: should not be null (for instance)
If you use the label attribute for 'Please choose...', your are ending with: Please choose..., should not be null.
So I introduced the new attribute to define the text, that is shown if no item is selected.

**Comment by OBreidenbach** [comment]
To Case2, in

https://github.com/primefaces/primefaces/blob/ccfe87624a0efe4a6f8c848adcc9cf06d01104a6/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js#L855-L856

the same 'labelText' is set to the label and the title. So they should not show different values. Did you check with other browsers? Do you get a javascript exception when it happens?

**Comment by ohlsen3000** [comment]
Hi @OBreidenbach, all 3 browsers show the same erroneous behaviour and neither of them shows a js error.

**Comment by ohlsen3000** [comment]
![image](https://user-images.githubusercontent.com/2226986/47916663-33841900-dea7-11e8-8864-c6c6943f3bf3.png)

**Comment by ohlsen3000** [comment]
Hello @OBreidenbach, partially good news: Using your new ```emptyLabel``` solves *Case 1* 👍 
Unfortunately the asynch label/title issue remains :(

**Comment by OBreidenbach** [comment]
Sorry, but I can not reproduce your 2nd case. I created a test case:
https://github.com/OBreidenbach/primefaces-test/tree/PF4196?files=1
But the title is always updated.
You should provide a test case showing the issue.

**Comment by ohlsen3000** [comment]
Hi @OBreidenbach , i checked out your test branch and can definitely not reproduce the error with my special testdata. Seems to be caused by an interference with some other script or framework. Thanks so much for your effort!
