### ISSUE TITLE
DataScroller: update not working with lazy loading

### ISSUE THREAD

**Issue by Anton-Petrovskyi** [primefaces/primefaces#4197]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: GlassFish 4.1.0
- Affected browsers: Chrome

## 2) Expected behavior
Update all elements with class name = 'myClass'

## 3) Actual behavior
Update is not working by className attribute. But if I remove lazy='true' and use List instead of LazyDataModel - update works fine (updated="@(.myClass)")).

## 4) Steps to reproduce
1) Create dataScroller with LazyDataModel and lazy='true'
2) Create button that will update all blocks with className = 'myClass'
3) Change data in myClass block and refresh elements by className
4) Update dataScroller to use List and lazy = 'false', to see that it works for non-lazy dataScroller

## 5) Sample XHTML

    <p:dataScroller id="myId" value="#{searchCriteria.lazyDataModel}" lazy="true" var="a" chunkSize="12" rowIndexVar="rowIndex">
        <h:panelGroup id="dummy" styleClass="myClass" layout="block">
            // content is not updated when updated="@(.myClass)"
        </h:panelGroup>
    </p:dataScroller>

    <p:dataScroller id="myId" value="#{searchCriteria.myList}"  var="a" chunkSize="12" rowIndexVar="rowIndex">
        <h:panelGroup id="dummy" styleClass="myClass" layout="block"> 
            // content is updated successfully when updated="@(.myClass)"
        </h:panelGroup>
    </p:dataScroller>

## 6) Sample bean

    public class MyLazyDataModel extends LazyDataModel<MyEntity> implements Serializable{

        private EntityManager em;
        private Query query;

        public MyLazyDataModel(EntityManager em, Query query, int totalSize) {
            this.em = em;
            this.query = query;
            this.setRowCount(totalSize);
        }

        @Override
        public List<MyEntity> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String,Object> filters) {
            query.setFirstResult(first);
            query.setMaxResults(pageSize);
            return parseData(query);
        }

    }

**Comment by Anton-Petrovskyi** [comment]
Update regarding this question: 
If I update p:dataScroller by its className - it will work. 
But same update for h:panelGroup is not working for me.

Also if I update h:panelGroup that is outside p:dataScroller component - update is successful, if h:panelGroup inside p:dataScroller - update is ignored.

**Comment by tandraschko** [comment]
a PR would be great

**Comment by melloware** [comment]
I don't think this is possible to fix.  Its because of `lazy=true` the items are not in the DOM yet for all items so when calling `update=@(.myClass)` the Search expression is not finding the components and does when `lazy=false` because they are in the DOM.  So for this use case I don't think you can use the class style update and will have to use something else.
