### ISSUE TITLE
FileUpload: NoClassDefFoundError: org/apache/commons/io/FilenameUtils

### ISSUE THREAD

**Issue by fabermundi** [primefaces/primefaces#4198]
## 1) Environment
- PrimeFaces version: 6.2.10
- Application server + version: wildfly 10
- Affected browsers: Chrome, Internet Explorer

## 2) Expected behavior
If a file is uploaded there should be no error.

## 3) Actual behavior
Getting error "java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils" after file upload.
After adding the maven depency 
```
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.2</version>
        </dependency>
```
to my POM no more error is shown.

## 4) Steps to reproduce
Run the same xhtml (above) choose a file a choose "upload" after that you will get the error "java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils"

## 5) Sample XHTML
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head></h:head>
    <h:body>
        <h:form id="chantierForm" enctype="multipart/form-data">
            <p:fileUpload />
        </h:form>
    </h:body>
</html>
```

## 6) Sample bean
No bean needed

**Comment by pzygielo** [comment]
I think [user guide 6.2](https://www.primefaces.org/docs/guide/primefaces_user_guide_6_2.pdf) in section *2.2 Dependencies* covers that.

**Comment by tandraschko** [comment]
@mertsincan Can you check that? This doesn't happen on trunk as it's shaded probably.

**Comment by pzygielo** [comment]
@tandraschko - why it was marked as defect? IMO it works as designed.

**Comment by tandraschko** [comment]
If native Upload is used, no commons should be required

**Comment by pzygielo** [comment]
Right, but choosing native depends on JSF version and context param - which are not known for this case.

**Comment by Rapster** [comment]
A stacktrace would be really helpful to understand why Apache utils is called, but my guess is related to #3034

**Comment by mertsincan** [comment]
Please try commons-io v2.4+.

**Comment by pzygielo** [comment]
@mertsincan I think there is some misunderstanding. OP expects to not need commons-io at all (and using v2.2 fixes `NoClassDefFoundError`), thus using version v2.4 won't matter.

**Comment by Rapster** [comment]
@fabermundi again... You'd be a better help if you give the full stacktrace to Mert

**Comment by pzygielo** [comment]
@Rapster I do not have problem described here, nor the stack trace.

**Comment by pzygielo** [comment]
@fabermundi - what is the version of JSF that you are using?

**Comment by mertsincan** [comment]
> @mertsincan Can you check that? This doesn't happen on trunk as it's shaded probably.
- Thanks, @tandraschko ;) This issue has been fixed for the next elite version. FilenameUtils class has been added to the elite JAR as in the trunk.

**Comment by pzygielo** [comment]
Just guessing - *fixed* similar to #4111 (in 5204dc4d70d911297cb9d0943ce10c269e523674).

**Comment by pzygielo** [comment]
(Probably :wink:) my last comment for this one. 
Now that I've learnt about [shade plugin](http://maven.apache.org/plugins/maven-shade-plugin/) and studied [FileUploadUtils](https://github.com/primefaces/primefaces/blob/753177de962880311716b94aa8a6e579cad758c3/src/main/java/org/primefaces/util/FileUploadUtils.java) class I find this issue very educational. Also my understanding of the problem is slightly different than on Friday.

**Comment by melloware** [comment]
Still investigating but with PF 6.2.11 on Jboss EAP 6 (JSF 2.1) we are getting this error now we were not getting on PF 6.2.10.

> JBWEB000236: Servlet.service() for servlet Faces Servlet threw exception: java.lang.NoSuchMethodError: org.apache.commons.fileupload.servlet.FileCleanerCleanup.getFileCleaningTracker(Ljavax/servlet/ServletContext;)Lorg/primefaces/shaded/commons/io/FileCleaningTracker;
> 
> at org.primefaces.webapp.filter.FileUploadFilter.createFileItemFactory(FileUploadFilter.java:123) [primefaces-6.2.11.jar:6.2.11]
> 
> at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:93) [primefaces-6.2.11.jar:6.2.11]
