### ISSUE TITLE
[Documentation] CommandButton/CommandLink: Default values wrong in user guide

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#4199]
Up to PF 6.2, the user guide has wrong default values for `p:commandButton` and `p:commandLink` attributes `process` and `update`. While there are many opportunities for improvement in the guide, these two attributes are quite important. A good explanation from Bauke Scholz can be found at [SO](https://stackoverflow.com/questions/25339056/understanding-primefaces-process-update-and-jsf-fajax-execute-render-attributes). The default values should be:

- **process**: `@form`  (even if the actual value is `@all`, it would be misleading)
- **update**: `@none`  (which should also be defined for p:ajax)

**Comment by tandraschko** [comment]
process @all is default since years, we won't change that.

**Comment by tandraschko** [comment]
Actually the userguide is correct (from a technical aspect) as the default is really null.
our ajax engine just fallback to @all if process=null.

and for the update, null actually means @none

**Comment by mdzaebel** [comment]
Yes, I guessed this, so `null` gets `@all` and `@all` gets effectively `@form`, as HTML will submit only one form. So decide, what would be most helpfull for the user?

**Comment by tandraschko** [comment]
maybe we can write something like:
process = null (effectively @all)
update = null (effectively @none)

**Comment by mdzaebel** [comment]
Thomas, for me it's clearly better, not to bother users with unnecessary implementation details. Especially, if null means different things for different attributes (who is interested in this?). The whole Java history shows, that making things easier to do and easier to understand is in the interest of everyone. Software should reduce complexity. I can tell you that possible misinterpretations surely happen more often that we could imagine. So, there will be many people that need unnecessary time to discover, that `@all` doesn't mean `@all` in this certain situation. So the question is, do you want to have a point or help people and PF? Of course, you already helped people enormously with your outstanding work on PF (and especially me ! )

**Comment by tandraschko** [comment]
ok ;)
lets do
process=@all
update=@none

@form is not correct here and @all is actually used.
