### ISSUE TITLE
TreeTable: Drag & Drop feature

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#42]
Similar to the one available in Tree

**Comment by vfedoriv** [comment]
Any plans to implement it?

**Comment by melloware** [comment]
@vfedoriv in 6 years no open source committer has contributed this feature so you would probably need to sponsor this feature using PrimeFaces PRO or provide a PR if you manage to add the functionality yourself.

**Comment by testing138** [comment]
Are there any plans to integrate this?

**Comment by tandraschko** [comment]
as @melloware said, there are no plans currently
feel free to sponsor it or provide a PR
