### ISSUE TITLE
DataTable - Selection - Checkbox Issue

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4200]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
The issue was reported by actual user of our system.

A user selects a couple checkbox in a DataTable row, but then if they try to select another one, instead of clicking directly in the checkbox they click sort of next to the box instead, all the selected rows get Deselect, and they have to start all over again. 

...

## 3) Actual behavior
This issue is reproducible in showcase.

2 alternative exits 
1. Like Radio button do not do anything if the section is not on the round component.
2. check the box if the row is clicked (toggle the checkbox on row click)
..

## 4) Steps to reproduce
https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

![image](https://user-images.githubusercontent.com/15189434/47968732-d4a3d880-e03b-11e8-9561-b4dc828cadd5.png)

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by Rapster** [comment]
What about `rowSelectMode` set to `add`?

**Comment by ravihariharan** [comment]
Thanks @Rapster .  Completed missed out that it was documented in PrimeFaces User Guide. 

* Use rowSelectMode option to customize the default behavior on row click of a multiple
selection enabled datatable. Default value is "new" that clears previous selections, "add" mode
keeps previous selections same as selecting a row with mouse click when metakey is on and
"checkbox" mode allows row selection with checkboxes only.
