### ISSUE TITLE
the property of rendered does not work for the component <p: ajax>

### ISSUE THREAD

**Issue by julioccr** [primefaces/primefaces#4201]
the property of rendered does not work for the component <p: ajax> the default value is true, but when changing the option to false the operation remains true from the client.

example:
<p: dataTable ....>

       <p: ajax event = "rowSelect" rendered = "false" listener = "# {mybean.init ()}" />
</ dataTable>

**Comment by cnsgithub** [comment]
This is the expected behavior since the `rendered `attribute is not supported for `p:ajax`. You have to use the `disabled `attribute, see section 3.2 of the PrimeFaces user guide.
