### ISSUE TITLE
Update poll.js remove access to response attribute that no longer exists

### ISSUE THREAD

**Issue by german1410** [primefaces/primefaces#421]
Before poll interruption was handled by an attribute passed on the response "stop", this was handled by:

``` javascript
handleComplete: function(xhr, status, args) {
        if(args.stop) {
            this.stop();
        }
    }
```

But at some point the poll was stopped by issuing a call to stop method and the attribute was removed from the response. This leads to errors being displayed on some browsers like IE11.

```
SCRIPT5007: Unable to get property 'stop' of undefined or null reference
File: primefaces.js.jsf, Line: 23, Column: 420
```

**Comment by tandraschko** [comment]
Please explain this a little bit better and detailed:
But at some point the poll was stopped by issuing a call to stop method and the attribute was removed from the response. This leads to errors being displayed on some browsers like IE11.

**Comment by tandraschko** [comment]
AFAICS the #handleComplete method is also not used as the stop logic is done via Poll.java#broadcast

**Comment by cagataycivici** [comment]
Yes, I can't find a reference to handleComplete. @tandraschko Do you know where we have it? It seems obselete as we can RequestContext.execute() approach to call stop() js method. Should we remove handleComplete?

**Comment by tandraschko** [comment]
yep, i would remove it.
