### ISSUE TITLE
Signature:Not working on touchscreen since latest Windows update.

### ISSUE THREAD

**Issue by guylap** [primefaces/primefaces#4212]
Just want to let you know that the signature is not working using the screen since latest windows update and Chrome update. 
In Chrome and Microsoft Edge.

This problem also occurred with jSignature and it was corrected changing some javascript code in the js file.
Here is the link to the thread that corrected the problem.

https://github.com/brinley/jSignature/issues/157

Hope this helps....
Regards

**Comment by melloware** [comment]
I may be wrong but I believe PrimeFaces uses Keith Wood's Signature component not jSignature?

http://keith-wood.name/signature.html

**Comment by guylap** [comment]
Yes possibly, I do not know but I have tried Primefaces signature last week and it was doing the same problem as jSignature. (Could not sign on a touch screen in Windows using Chrome or Microsoft Edge.)
I just thought it might be helpful to mention the correction used by jSignature to the Primefaces team since it is all JavaScript JSON after all, .
Thanks for your input.
Regards

**Comment by melloware** [comment]
I found this issue: https://github.com/kbwood/signature/issues/15

**Comment by melloware** [comment]
I also found it may be Touch related: https://github.com/furf/jquery-ui-touch-punch/issues/309

**Comment by melloware** [comment]
OK I submitted a PR I think will fix it. https://github.com/primefaces/primefaces/pull/4213
