### ISSUE TITLE
Grid CSS: add offset

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#4217]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? no 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
With the commit https://github.com/primefaces/primeng/commit/ba1409006381e2e6f082833b14b6dcd37504388f (which closed primefaces/primeng#3362 ), offset classes were added to the "new" grid CSS. It would be nice if the changes could be ported to primefaces too. 

NB: https://github.com/primefaces/primeng/issues/5144 changes could be ported too

**Comment by tandraschko** [comment]
@mertsincan Are there any plans to port it?

**Comment by melloware** [comment]
+1 on this.

**Comment by melloware** [comment]
Attaching this sample here to prove everything is working.
[pf-grid.zip](https://github.com/primefaces/primefaces/files/3022912/pf-grid.zip)
