### ISSUE TITLE
PrimeFaces.widget.DataTable - resize problem

### ISSUE THREAD

**Issue by normanstrydom** [primefaces/primefaces#422]
This is just to notify you of a small bug in the resize logic in expanded mode - 

function -  
PrimeFaces.widget.DataTable
resize: function(event, ui) {

current,
            if(expandMode) {
                table.width(table.width() + change);

need to change to,
            if(expandMode) {
                table.width(table.width() - change);

**Comment by cagataycivici** [comment]
What is the problem, how can we replicate using showcase?

http://www.primefaces.org/showcase/ui/data/datatable/columnResize.xhtml

Is working as it should.

**Comment by normanstrydom** [comment]
The problem is when the datatable has resizableColumns="true" and 
liveResize="true" then with the new resizeMode="expand" try to resize a 
column, particularily to redice its size, the column sizing "runs" away 
uncontrollably.  Changing the sign of "change" as indicated, leads to 
the correct operation, but you may also find that other combinations 
have a problem as I see similar addition of the "change" in other parts 
of the javascript.

Hope this helps.

Regards
   Norman Strydom

**Comment by cagataycivici** [comment]
I know this, liveResize is not supported in this case due to concurrent number of calculations, browsers tend to misbehave.
