### ISSUE TITLE
Galleria: Improve the animation

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#4226]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Not Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
When we click the next button the previous animation should be controlled. 

## 3) Actual behavior
When we click the next button many times and very fast, the previous animation is not controlled correctly. Actually there are the next problems related:
- The caption panel is still animated after we stop pressing the next button.
- The caption content is changed before the panel is hidden, it should be changed when the panel is hidden and before show it again. Resolve the issue #155.
- We could see more than one thumbnail with opacity = 1.

## 4) Steps to reproduce
1. Go to: https://www.primefaces.org/showcase/ui/multimedia/galleria.xhtml
2. Click the arrow "Next" many times and very fast.
3. We can see the problems described above.

**Comment by melloware** [comment]
@wsaca are you saying this fixed issue #155 because that issue is still open?

**Comment by wsaca** [comment]
@melloware yes, the issue #155 should be closed because the animation problem with the caption text was resolved.

**Comment by melloware** [comment]
Excellent thanks for the update!
