### ISSUE TITLE
Add keyboard support to SelectOneListbox

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4237]
like picklist

**Comment by wsaca** [comment]
@mertsincan This change added the next error "TypeError: $.ui is undefined".

**Comment by mertsincan** [comment]
@wsaca I couldn't replicate it. Which version are you using to test?

**Comment by wsaca** [comment]
@mertsincan If you try it in the showcase this error is not thrown because the tabView component has already a dependency to "jquery-plugins.js". You should test it alone in a xhtml page.
