### ISSUE TITLE
Charts: Model classes should implement Serializable

### ISSUE THREAD

**Issue by anhquande** [primefaces/primefaces#4240]
## 1) Environment
- PrimeFaces version: 6.3.0
- Does it work on the newest released PrimeFaces version? Version? No, 6.3.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: does not matter
- Affected browsers: does not matter

In the new chart package (org.primefaces.model.charts)  Any class that can be converted to a JSON object should implement Serialiable.

**Comment by melloware** [comment]
I can take this one

**Comment by melloware** [comment]
PR Submitted.
