### ISSUE TITLE
selectBooleanCheckbox: shows Label twice when using attribute label

### ISSUE THREAD

**Issue by anhquande** [primefaces/primefaces#4241]
## 1) Environment
- PrimeFaces version: 6.3.0
- Does it work on the newest released PrimeFaces version? Version? yes, 6.2.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: does not matter
- Affected browsers: all browsers

## 2) Expected behavior
- Label should be shown only once
## 3) Actual behavior
.. Label appears twice when using the attribute label

## 4) Steps to reproduce
- Create a page including a selectBooleanCheckbox component.
- Do not use `itemLabel `attribute, but use `label `instead

## 5) Sample XHTML
The following setting is working
`                            <p:selectBooleanCheckbox
                                    value="#{myBean.myCheckedValue}"
                                    itemLabel="Check me"
                            >
                            </p:selectBooleanCheckbox>
`

The following setting shows double label
`                            <p:selectBooleanCheckbox
                                    value="#{myBean.myCheckedValue}"
                                    label="Check me"
                            >
                            </p:selectBooleanCheckbox>
`

**Comment by cnsgithub** [comment]
Related to https://github.com/primefaces/primefaces/commit/b12119aad40e9db23762ee67dfbcb38c65fd9151?

**Comment by tandraschko** [comment]
@Rapster please try to fix, otheriwse it's better to revert

**Comment by Rapster** [comment]
I'll fix it

**Comment by Rapster** [comment]
I can't reproduce your problem, although I had another problem using `itemLabel`. Please sync your repo and let me know if 5a2ce6dc3 fixed your problem
