### ISSUE TITLE
[Documentation] FileUpload: validateContentType

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#4245]
see: https://github.com/primefaces/primefaces/issues/4244

validateContentType used Files#probeContentType to validate the file content.
Per default, the jdk implementation of Files#probeContentType is not reliable enough as it just checks the filename.
Files#probeContentTypes uses the jdk FileTypeDetector, which has a plugin mechanism via ServiceLoader.
Therefore users could add their own detection.

Apache Tika provides such a FileTypeDetector, which will be pickedup automatically and can be used via:

```xml
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-java7</artifactId>
            <version>1.19.1</version>
        </dependency>
```

**Comment by cnsgithub** [comment]
This is the right tika dependency that would be needed:

```xml
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-java7</artifactId>
            <version>1.19.1</version>
        </dependency>
```
