### ISSUE TITLE
p:wizard is not executing setters on step back

### ISSUE THREAD

**Issue by pavel-sedek** [primefaces/primefaces#425]
If the user types into the input some value, clicks next and back, the value retains. If he types the same value into the same input and clicks back and then next, input is blank.

The issue could be simply reproduced on the showcase. http://www.primefaces.org/showcase/ui/panel/wizard.xhtml

1) Type something into firstname and lastname
2) Click next
3) Type something into street
4) Click back
5) Click next, the street input is now blank
6) Type something into street input again
7) Click next
8) Click back, the street input keeps value from step 6

**Comment by cagataycivici** [comment]
That is by design, back does not process anything. Please use forum first for these kinds of cases.
