### ISSUE TITLE
imageCropper: stop working after browser updated

### ISSUE THREAD

**Issue by Victor-Ovchinnikov** [primefaces/primefaces#4255]
## 1) Environment
- PrimeFaces version: 6.2 and on-site demo
- Affected browsers: Chrome Version 70.0.3538.77 (Official Build) (64-bit), Firefox 63.0 (64-bit)

## 2) Expected behavior
Crop area displayed after load

## 3) Actual behavior
Crop area not displayed after load, can't select crop area

## 4) Steps to reproduce
Visit PF demo https://www.primefaces.org/showcase/ui/multimedia/cropper.xhtml and reload the page (ctrl+f5)
Not affect Safari and Opera now. Need to reload the page on Chrome to reproduce.

**Comment by melloware** [comment]
We have seen other Chrome 70 related components stop working like Touch Support because of some API changes in Chrome.  I bet this is related.

**Comment by melloware** [comment]
I will see if I can upgrade this component to a newer version of the plugin.
