### ISSUE TITLE
OverlayPanel: Top position out of view

### ISSUE THREAD

**Issue by tdtappe** [primefaces/primefaces#4263]
1) Environment
Reproduceable with current showcase (6.2.11), primefaces-test-master sample project (6.2 - see below) and my app (6.2.1 with Wildfly 13.0.0.Final)
Browsers: Firefox 63.0.3 and Chrome 70.0.3538.110

2) Expected behaviour
The top of the overlay panel should always be visible (no negative top-value)

3) Actual behaviour
If the browser window is too small the overlay panel is moved to the top of the bound element. But too far so that the top of the overlay panel is no longer visible (exceeds the top of the browser window).

4) Steps to reproduce
See sample project: Decrease the size (height) of the browser window and click the test button. There is enough space to put the overlay panel at the bottom of the panel but it's moved to the top. But even is there wasn't enough space below the button the top of overlay panel should never get out of view.

5) Sample XHTML
See sample project

6) Sample bean
See sample project

Sample project: https://github.com/tdtappe/primefaces-test/tree/overlay-panel-position

**Comment by fanste** [comment]
The fix in #4309 works in my local application. But I can't tell you if this is the best / performant fix.

**Comment by melloware** [comment]
Looks good to me but I will let @tandraschko review it and see.
