### ISSUE TITLE
f:param non longer working with p:splitButton

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4264]
Reported By PRO User;
> after release 6.2.11 , our code that uses f:param inside a p:splitButton crashes with this error below:
> javax.faces.component.UIParameter cannot be cast to org.primefaces.model.menu.MenuElement: java.lang.ClassCastException: javax.faces.component.UIParameter cannot be cast to org.primefaces.model.menu.MenuElement
> at org.primefaces.component.splitbutton.SplitButtonRenderer.encodeElements(SplitButtonRenderer.java:264)

**Comment by Rapster** [comment]
And it worked before 6.2.11?

**Comment by mertsincan** [comment]
Yes, this issue is related to SplitButton feature in 6.2.11.
