### ISSUE TITLE
Global: Serializable and serialVersionUID missing

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#4268]
**Example warning:**  "_The serializable class OrganigramNodeCollapseEvent does not declare a static final serialVersionUID field of type long_"

While this may seem like boilerplate code it is not and it actually causes the compiler to recalculate a hash on the fly every time.

> If a serializable class does not explicitly declare a serialVersionUID, then the serialization runtime will calculate a default serialVersionUID value for that class based on various aspects of the class, as described in the Java(TM) Object Serialization Specification. However, it is strongly recommended that all serializable classes explicitly declare serialVersionUID values, since the default serialVersionUID computation is highly sensitive to class details that may vary depending on compiler implementations, and can thus result in unexpected InvalidClassExceptions during deserialization. Therefore, to guarantee a consistent serialVersionUID value across different java compiler implementations, a serializable class must declare an explicit serialVersionUID value. It is also strongly advised that explicit serialVersionUID declarations use the private modifier where possible, since such declarations apply only to the immediately declaring class serialVersionUID fields are not useful as inherited members.

**From Joshua Bloch's book Effective Java:**

> It is worth noting that Joshua Bloch advices that for every Serializable class it's worth specifying the serial version uid. Quote from chapter 11: Regardless of what serialized form you choose, declare an explicit serial version UID in every serializable class you write. This eliminates the serial version UID as a potential source of incompatibility (Item 74). There is also a small performance benefit. If no serial version UID is provided, an expensive computation is required to generate one at runtime.

**Proposal:** I propose to submit a PR adding the serialVersionId to all the classes that are missing it.

```java
private static final long serialVersionUID = 1L;
```

**Comment by tandraschko** [comment]
we should check the current JDKs before, if there is really a difference. IMO its just boilerplate and we should only apply it if there is a performance difference or we use it correctly.

**Comment by melloware** [comment]
Still true as of JDK 11.  https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/Serializable.html

**Comment by tandraschko** [comment]
where exactly?

**Comment by tandraschko** [comment]
The text is bit long ;)

**Comment by melloware** [comment]
Its the last paragraph of the Javadoc header.

> ANY-ACCESS-MODIFIER static final long serialVersionUID = 42L;
>  
> If a serializable class does not explicitly declare a serialVersionUID, then the serialization runtime will calculate a default serialVersionUID value for that class based on various aspects of the class, as described in the Java(TM) Object Serialization Specification. However, it is strongly recommended that all serializable classes explicitly declare serialVersionUID values, since the default serialVersionUID computation is highly sensitive to class details that may vary depending on compiler implementations, and can thus result in unexpected InvalidClassExceptions during deserialization. Therefore, to guarantee a consistent serialVersionUID value across different java compiler implementations, a serializable class must declare an explicit serialVersionUID value. It is also strongly advised that explicit serialVersionUID declarations use the private modifier where possible, since such declarations apply only to the immediately declaring class--serialVersionUID fields are not useful as inherited members. Array classes cannot declare an explicit serialVersionUID, so they always have the default computed value, but the requirement for matching serialVersionUID values is waived for array classes.
> Since: 1.1

**Comment by tandraschko** [comment]
All right, then plz proceed :)
