### ISSUE TITLE
PrimeFaces 5.2 and Atmosphere 2.3.2 (regression)

### ISSUE THREAD

**Issue by smithh032772** [primefaces/primefaces#427]
[ANN] Atmosphere 2.3.2 released
https://groups.google.com/forum/#!topic/atmosphere-framework/DAQnl3wxYGY

me:
I downloaded the atmosphere-runtime 2.3.2 JAR and replaced the atmosphere-runtime 2.3.1 JAR in my project, and now PrimeFaces 5.2 Push no longer sends messages to the client. I use the notify (faces messages) example. No errors in the server log and no errors in the client/browser.

jfarcand:
Hi,

it seems 2.3.2 doesn't work with 5.2, only with 5.3
https://groups.google.com/forum/#!topic/atmosphere-framework/8qkqGObHvGY

I will make sure 2.3.4 will be compatible with 5.2.

A+

@PathParam are not injected in PF5.2 with Atmosphere 2.3.2 (regression)
https://groups.google.com/forum/#!topic/atmosphere-framework/8qkqGObHvGY

**Comment by cagataycivici** [comment]
I think @jfarcand will create a new issue for this.
