### ISSUE TITLE
Improve encodeMenuItem method on BaseMenuRenderer For Premium Layouts

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4284]
For Premium Layouts

**Comment by Rapster** [comment]
This new method is never called... How can it work? I suggest to give more details about it, as it could be deleted in the future. (I personnaly delete unused methods as it pollute code)

**Comment by melloware** [comment]
@Rapster my guess is in the premium layouts they use it.  Most of the Premium Layouts come with their own special menu for the sidebar.

**Comment by Rapster** [comment]
Yeah I think so too, but how to use it if it's never called?

**Comment by mertsincan** [comment]
We use it on Templates. Please do not remove this method. If you remove it I have to add it again. Thanks a lot, @melloware ;)

**Comment by Rapster** [comment]
In that case leave a comment, but can you explain how it is called? why don't you simply call encodeMenuItem(context, menu, menuitem, "-1");?

**Comment by mertsincan** [comment]
Please review the codes in previous commits. Because, we override the method on templates.

**Comment by mertsincan** [comment]
Also please read our support protocol on the templates.

**Comment by tandraschko** [comment]
If it's really unused in PF core, we should at least add a comment. someting like // don't remove it, it's used by templates

**Comment by Rapster** [comment]
Mert, I understand you override methods in premium layouts. But based on your commit, this new method is called nowhere, so even though you override it, how can it be called? 

I'm just trying to understand.... But even though it's called, why don't you override `encodeMenuItem(FacesContext context, AbstractMenu menu, MenuItem menuitem, String tabindex)`, and then call `super.encodeMenuItem(context, menu, menuitem, "-1");`?

**Comment by mertsincan** [comment]
> why don't you override encodeMenuItem(FacesContext context, AbstractMenu menu, MenuItem menuitem, String tabindex), and then call super.encodeMenuItem(context, menu, menuitem, "-1");?
- We don't work on only one PF version on templates.
on Template pages;
> Officially supported for 5.x, 6.0 and newer.
> Compatible with modern browsers and Internet Explorer 9+

```encodeMenuItem(FacesContext context, AbstractMenu menu, MenuItem menuitem, String tabindex)``` this method is only available in 6.2.x and 6.3 versions.

**Comment by Rapster** [comment]
Okay I see, I encourage you to write a comment on that method then
