### ISSUE TITLE
p:pickList is not updating from p:ajax in h:selectOneMenu with primefaces-6.1.2(It is working fine with primefaces-5.2.5)

### ISSUE THREAD

**Issue by tirumala27** [primefaces/primefaces#4291]
# IMPORTANT 
p:pickList is not updating from p:ajax in h:selectOneMenu with primefaces-6.1.2
It is working fine with primefaces-5.2.5. I have migrated the jar to primefaces-6.1.2. 

## 1) Environment
- PrimeFaces version: 6.1.2

## 2) Expected behavior
p:pickList should update when p:ajax event completed in h:selectOneMenu with primefaces-6.1.2

## 3) Actual behavior
p:pickList is not update when p:ajax event completed in h:selectOneMenu with primefaces-6.1.2. Same id working with primefaces-5.2.5 jar.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
Ajax: <p:ajax event="change" listener="#{xxxxBean.processFINDataByState}" update="pickList"/> 

p:pickList:
<p:pickList id="pickList" value="#{xxxBean.finCodeNameParentDualList}"   
                            var="fin" itemLabel="#{fin.finCode}-#{fin.finName}" itemValue="#{fin}">
                           <p:ajax event="transfer" listener="#{xxxBean.onTransferSelectedParent}" update="pickList,pickListMsg" />
                            <p:column >
                                <c:if test="#{xxxBean.sortBy == 'Name'}">
                                   #{fin.finName} - #{fin.finCode} 
                                 </c:if>
     
                            </p:column>    
                        </p:pickList>

## 6) Sample bean

..

**Comment by tandraschko** [comment]
We need a runnable example, otherwise -> invalid.

**Comment by Rapster** [comment]
In addition, please format your code properly, see https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by tandraschko** [comment]
Will close it for now.
Feel free to create a new issue again with a fully runnable example.
