### ISSUE TITLE
TextEditor: Text justify not work

### ISSUE THREAD

**Issue by marcelocaser** [primefaces/primefaces#4292]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not tested.
- Application server + version: Tomcat 9
- Affected browsers: All

## 2) Expected behavior

![2018-11-28_085639](https://user-images.githubusercontent.com/4403920/49154089-ad6cbe00-f2fe-11e8-94f8-c78f2f79d25d.png)

## 3) Actual behavior

![2018-11-28_085521](https://user-images.githubusercontent.com/4403920/49154104-b65d8f80-f2fe-11e8-9f9c-b2725c6f9b68.png)

## 4) Steps to reproduce

Just use primefaces showcase and primefaces extension

## 5) Sample XHTML

Just use primefaces showcase and primefaces extension

## 6) Sample bean

Not used.

**Comment by tandraschko** [comment]
Can you try the native Quill Editor ?
If it works there, we probably can just upgrade the editor.

**Comment by melloware** [comment]
Looks like this issue: 
https://github.com/quilljs/quill/issues/2289 or https://github.com/quilljs/quill/issues/396

**Comment by marcelocaser** [comment]
@tandraschko Yes i tryed and not work. 

@melloware Thanks. For me not work in any browser.

**Comment by marcelocaser** [comment]
Sory @melloware. It worked using the Chrome browser in both PrimeFaces and Quill Editor as issue https://github.com/quilljs/quill/issues/396. But in Firefox not work.

**Comment by melloware** [comment]
@marcelocaser No problem.  At the heart of it, its a QuillJS issue not a Primefaces issue.

**Comment by tandraschko** [comment]
Yep, i will close it for now.
We should upgrade the quillJS dependency, when the bug got resolved there.
