### ISSUE TITLE
SelectBooleanCheckbox: Add option to optionally display label (old itemLabel)

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4293]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT

## 2) Expected behavior
A new option (e.g. `showLabel=true|false`, default = true) should be added to optionally display the label next to the checkbox. Till PF 6.2 you had `itemLabel`, which was the label next to the checkbox, and `label`, which was the label for e.g. validation messages.

I have a datatable which has a column + header text. The content of that column is a `p:selectBooleanCheckbox`. The header text is enough to label the checkbox but in case of a validation error I need the (old) label attribute to add a unique name to the error message.

## 3) Actual behavior
`itemLabel` and `label` have been merged into `label`. Therefore the checkbox will always have a label next to it which is too much, in my case with the datatable.

**Comment by melloware** [comment]
@Rapster this is related to your fix https://github.com/primefaces/primefaces/issues/4231 any thoughts?

**Comment by Rapster** [comment]
Ahhh I didn't expect that. Fair enough, I'll revert the commits 😉 Thank you for reporting. I was quite happy to get rid of `itemLabel` as the name is quite confusing (knowing we have a bunch of components having `f:selectItem`), and in this case there are none eligible...
