### ISSUE TITLE
Tree DragDrop can't DragDrop to top level

### ISSUE THREAD

**Issue by HipDragon** [primefaces/primefaces#4294]
## 1) Environment
- PrimeFaces version: 6.2.11 & 6.3-Snapshot
- Affected browsers: FireFox
- PrimeFaces Demo site has the bug to view (https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml)
- Previous worked on PrimeFaces 6.1.x

## 2) Expected behavior
Should be able to drag any sub tree node to the top tree node.

## 3) Actual behavior
When dragging a subnode to top level it doesn't drag but shows a outline box and stops working entirely. Refreshing the page makes it work again. You can drag any sub nodes out of a sub node, but never to a top level node.

## 4) Steps to reproduce
On PrimeFaces Demo/Showcase you should be able to drag "Item 0.0" to above "Item 0" or below "Item 1" to any top level tree area. It does not work and makes that item stop working until page refresh.

**Comment by melloware** [comment]
I think this is a duplicate of https://github.com/primefaces/primefaces/issues/4091

**Comment by HipDragon** [comment]
Correct this is a duplicate of #4091, sorry my search didn't find that duplicate issue.

**Comment by melloware** [comment]
Fixed in 6.2.13 with this commit: https://github.com/primefaces/primefaces/commit/4cf1d84cd57511271ec2d77721e8159d0c13ea89
