### ISSUE TITLE
Calendar: Opens under input field which is at bottom of page

### ISSUE THREAD

**Issue by babubabu** [primefaces/primefaces#4295]
## 1) Environment
- PrimeFaces version: 6.2.11, 6.2.12
- Application server + version: Tomcat 8.5.32 /Jetty 9.4.11
- Affected browsers: Firefox 63.0.3, IE 11.785, Chrome 70.0.3538.110

## 2) Expected behavior
If an p:calendar field is located at the bottom of the page and the datepicker opens, the datepicker open above the field and not under. 

## 3) Actual behavior
The datepicker open under the field and the body gets bigger.

## 4) Steps to reproduce
Scroll to field and click into it.

## 5) Sample XHTML
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h1>#{testView.testString}</h1>

        <h1>#{testViewCdi.testString}</h1>

        <h:form>
            <div style="height: 300px;">just to fill viewport</div>

            <p:calendar value="#{testView.myDate}" />
        </h:form>

    </h:body>
</html>

## 6) Sample bean
package org.primefaces.test;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.Date;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    private Date myDate;
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

    public Date getMyDate() {
        return myDate;
    }

    public void setMyDate(Date myDate) {
        this.myDate = myDate;
    }
}

**Comment by tandraschko** [comment]
probably the jquery datepicker doesn't have such a colission detection.

**Comment by wujianbin-sh** [comment]
I find one solution to fix this problem:
In the generated package /primefaces-6.3.jar
Open this file:  META-INF/resources/primefaces/jquery/jquery-plugins.js and modify it as below:

Find the line 15810 like `this.updateDatePickerPosition = function (inst) {`
At the end of this function definition, at about line 15826, add one line code like this:
        `this.updateDatePickerPosition(inst);`
This will call the function to adjust calendar's position.

**Comment by melloware** [comment]
@wujianbin-sh  Are you suggesting at the end of the function to call itself recursively?  Won't that cause an infinite loop?

**Comment by wujianbin-sh** [comment]
> @wujianbin-sh Are you suggesting at the end of the function to call itself recursively? Won't that cause an infinite loop?

No, not call it in its body, 
Just after its definition body, like this:
```
//its definition starts here:
this.updateDatePickerPosition = function (inst) {
....
}
//its definition ends here

//then add code after its definition here:
this.updateDatePickerPosition(inst);
```

**Comment by melloware** [comment]
Test case that proves the problem: 
[pf-4295.zip](https://github.com/primefaces/primefaces/files/2704092/pf-4295.zip)

**Comment by melloware** [comment]
@wujianbin-sh Your fix worked perfectly and I just submitted a PR.
