### ISSUE TITLE
Touch support not working correctly on Win10 + IE11 / Edge

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4297]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Affected browsers: Tested on Windows 10 +  IE11 / Edge

## 2) Expected behavior
On desktop browsers no touch support should be done by jquery.ui.touch-punch.js

## 3) Actual behavior
In my specific case: `p:dialog` with `draggable = true, resizable=true` and a child `p:selectBooleanCheckbox`
A click on the checkbox inside the dialog triggers the click event twice. The first one is done by touch-punch triggered by the draggable/resizable mode of the dialog. The second one is the normal browser click, that happend on the checkbox.

The correct behavior can be archive, if you click-and-hold the checkbox, move the mouse inside the checkbox and than release the mouse. touch-punch does not think it was a click event and won't trigger it.

## 4) Steps to reproduce
The sample shows 3 checkboxes. 2 are in dialogs, 1 is on the page.
 - The one on the page is working correctly.
 - The one in dialog "Test - working" is working correctly - draggable /resizable are set to `false`.
 - The one in dialog "Test - buggy" is not working - both/one of draggable/resizable are set to true.

Test project is available: https://github.com/fanste/primefaces-test-touch-punch
It requires a 6.3-SNAPSHOT to be available for maven.

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

      <span onclick="PF('dlgTest').show()" style="display:inline-block;margin-right:50px">Open 'buggy' Dialog</span><span onclick="PF('dlgTest1').show()" style="display:inline-block">Open 'working' Dialog</span><br /><br />
      <h:form>
            <p:dialog widgetVar="dlgTest" header="Test - buggy" draggable="true" resizable="true" modal="true">
                  <p:selectBooleanCheckbox itemLabel="click me - I'm buggy" />
            </p:dialog>
            
            <p:dialog widgetVar="dlgTest1" header="Test1 - working" draggable="false" resizable="false" modal="true">
                  <p:selectBooleanCheckbox itemLabel="click me - I'm working" />
            </p:dialog>

            <p:selectBooleanCheckbox itemLabel="click me - I'm working" />
      </h:form>
    </h:body>
</html>
```

## 6) Sample bean
Not needed

## 7) Possible fix
As seen in the repo of touch-punch (original)
```
$.support.touch = ('ontouchstart' in document || 'ontouchstart' in window || navigator.maxTouchPoints > 0 || navigator.msMaxTouchPoints > 0);
```

I'm not able to test on touch devices. But on desktop it works fine after this change.

**Comment by tandraschko** [comment]
can we just upgrade the plugin?

**Comment by melloware** [comment]
I already fixed this by upgrading touch punch in this PR: https://github.com/primefaces/primefaces/pull/4213

Let me fix it to use the navigator.msMaxTouchPoints > 0

**Comment by melloware** [comment]
I see now I just submitted a PR.  While touch punch was updated with tons of bug fixes and to support Chrome 70 it did not fix it for IE 11.  This fix will cure them all.

**Comment by tandraschko** [comment]
Could you create a issue on their side? So we don't get this error next time when upgrading?

**Comment by melloware** [comment]
Yep its already open: https://github.com/furf/jquery-ui-touch-punch/issues/309
