### ISSUE TITLE
DataTable issue when using scrolling, freezing and cell edit

### ISSUE THREAD

**Issue by Tecnocom** [primefaces/primefaces#430]
I have a data table which is editable, scrollable and has frozen columns.
The editMode is "cell".
I have a "cellEdit" event set up similarly to that in the example on the ShowCase.

Upon editing any cell within the scrollable area (to the right of the frozen columns), the CellEditEvent is populated with the wrong data (not to mention that the table itself is populated with the wrong data). The data seems to be taken from cells residing to the left of the cell which has just been edited. If there are two frozen columns in the data table, then the content will be taken from the second cell to the left of the one being edited.

**Comment by cagataycivici** [comment]
Please use forum first for these kinds of cases and post your code there. Your issue is also missing a lot of information like a runnable test case, version information and so on.
