### ISSUE TITLE
Calendar: Typo in javascript

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4300]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Affected browsers: All

## 2) Description
Calendar with `mode=inline` + `event=dateSelect` will throw a JS error because of a typo in the JS file introduced in the bugfix of #3760

calendar.js line 201 => _self instead of $this

PR #4301

**Comment by melloware** [comment]
This was my bad that I didn't catch this.  Thanks for fixing.

**Comment by melloware** [comment]
[pf-cal.zip](https://github.com/primefaces/primefaces/files/5361026/pf-cal.zip)

Uploading this reproducer to prove its fixed
