### ISSUE TITLE
Improve FileUpload API

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#4305]
After fixing #4038 it brings some design flaws. By definition UploadedFile is either simple or multiple but can't be both. This is what the current design is implying. It's quite confusing... See also @cnsgithub coment: https://github.com/primefaces/primefaces/issues/4038#issuecomment-438169951

> Depending on the CTOR being called we either have the single vs. multiple file upload situation. Since there are two separate field members, part and parts, the other will stay null and therefore is predestinated for NPEs thrown later on. E.g. methods getSize or getInputstream are suitable for the single file upload case only.

A proper design might imply some breaking changes of the current model. We have to make a clear distinction between simple and multiple uploaded file.

I had a quick thought about it:
![image](https://user-images.githubusercontent.com/7521311/49343646-c6ae9b00-f66d-11e8-9207-f661cbbeb53e.png)

**Comment by tandraschko** [comment]
I would do the following....
- UploadedFile with all methods from UploadedFile and SimpleUploaded, Native and Default can extend it
- UploadedFiles, which contains a list of UploadedFile and maybe helper methods

**Comment by Rapster** [comment]
Yup sounds simpler. I would love to see this for 6.3, as the commit will bring a lot of issues. But I labelled it 7.0 as I wasn't  sure about the changes

**Comment by tandraschko** [comment]
It's actually late for big changes, RC1 >actually< targets december.
We should wait for the release.

**Comment by Rapster** [comment]
Fair enough, let's stick to 7.0 then 😉

**Comment by Rapster** [comment]
Okay having a look at FileUploadEvent#getFile, I realize we should have a common interface between UploadFiles/UploadFile. I updated my proposal

**Comment by tandraschko** [comment]
I think it's better to change FileUploadEvent instead.
In generell, i think it's always good to have #getFiles and the user can get the first or all or whatever from this list.
So also a single upload should create a UploadedFiles with with size=1

So FileUploadEvent could have:
- getFiles

and maybe something like:
- getSingleFile
which could throw a Exception if size > 1

**Comment by Rapster** [comment]
I'll make a PR and we'll discuss about it

**Comment by Rapster** [comment]
FYI, I just realized there is one event per upload, see doc:

> Note that multiple mode is for selection only, it does not send all files in one request. FileUpload component always uses a new request for each file.

So one event for one file, that put aside the discussion regarding FileUploadEvent#getFiles

**Comment by melloware** [comment]
Not sure this is right place for it but I was messing around with Jboss 7 which is JSF 2.2 and since JSF 2.2 it uses the Native upload I was getting Classloader failures because it couldn't find Commons FileUpload classes.  I was under the impression if we use JSF 2.2 we don't need to include Commons FileUpload at all. 

But I am not seeing that as the case.

**Comment by tandraschko** [comment]
AFAIR it should only use commons on 2.2 if explicitly defined in the webconfig

Also NOTE: there was a bug in the last (or next to last) elite version that even native required commons fileupload as the shading wasn't configured correctly.

**Comment by melloware** [comment]
Ahhh let me check that.  i wonder if it was still in web.xml.

**Comment by melloware** [comment]
You were right i had the FileUploadListener in my web.xml.  Once I removed that it all worked.  Sorry about that!

**Comment by Rapster** [comment]
PR available here: https://github.com/primefaces/primefaces/pull/4911

Feedbacks are welcome! BTW, I did a bit of refactoring 'cause I feel `org.primefaces.model` is getting congested, so I moved the files into `org.primefaces.model.file`

**Comment by tandraschko** [comment]
@Rapster please also update the migration guide + docs
