### ISSUE TITLE
FileUpload: mode simple + multiple true displays one filename

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#4306]
Since #4038 it's possible to have multiple files uploaded in simple mode, but only one filename is displayed. At least 2 should be displayed, if too many, ends with "etc."? @mertsincan could you have a look at it please

**Comment by melloware** [comment]
Maybe end with "..." instead of "etc"?

**Comment by Rapster** [comment]
Yup I took the first thing that crossed my mind 😄 But actually, to be more accurate, it should display something like:

A.pdf, B.pdf and 24 more

**Comment by cnsgithub** [comment]
> A.pdf, B.pdf and 24 more

I like this. Please don't forget I18N then. :wink:

**Comment by Rapster** [comment]
@mertsincan it would be nice to have this fixed for 6.3, WDYT?

**Comment by Rapster** [comment]
I cant' reproduce the problem on Chrome and Firefox: it might have been fixed by the web browser itself. Although on IE 11 it doesn't show anything. I'll probably close this one then

**Comment by tandraschko** [comment]
doesn't work on firefox for me
