### ISSUE TITLE
OverlayPanel: Dynamic panel is broken when parent container is re-rendered

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4307]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Affected browsers: ALL
- Similar issue: #1671

## 2) Expected behavior
OverlayPanel with `dynamic = true` is inside a DataTable. The pagination of the DataTable should not break the OverlayPanel once the panel content was loaded.

## 3) Actual behavior
An empty panel is shown, if the OverlayPanel was part of an AJAX re-render

## 4) Steps to reproduce
Hover over the icon, wait till the panel is shown. Change the page of the DataTable and again back to the old page. Hover the same icon. Empty panel is shown.

## 5) Sample XHTML
```
<p:dataTable value="#{[1,2,3,4,5,6,7,8,9,10]}" var="trow" pagination="true" rows="2">
	<p:column>row #{trow}</p:column>
	<p:column>
		<p:commandLink id="clNotes"><i class="fa fa-a fa-file-o"></i></p:commandLink>
		<p:overlayPanel for="clNotes" dynamic="true" showDelay="1000" showEvent="mouseover">
			<dl>
				<ui:repeat value="#{[1, 2, 3, 4]}" var="note">
				<dt><b>[date-#{note}]</b> FROM</dt>
				<dd>note-#{note} note-#{note} note-#{note} note-#{note} note-#{note} note-#{note}</dd>
				</ui:repeat>
			</dl>
		</p:overlayPanel>
	</p:column>
</p:dataTable>
```

## 6) Sample bean
Not needed

**Comment by fanste** [comment]
As far as I've seen there may be two solutions:
 - track the `content-loaded` flag on the server side in the component and directly render the children.
 - reset the `content-loaded` flag on the client side on `refresh`

What would/should be preferred?

**Comment by tandraschko** [comment]
2) sounds easier

**Comment by fanste** [comment]
PR #4308 - tested in my local application
