### ISSUE TITLE
OverlayPanel: improve performance of resize handler

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4310]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Affected browsers: ALL

## 2) Description
Is there a reason why the `align()` is always invoked on window-resize even when the panel is not visible?
E.g. a datatable with hundret of rows and a embedded overlay-panel will have a huge performance impact.

A solution could be to guard the `align()` call with a `$this.jq.hasClass('ui-overlay-visible')`

**Comment by tandraschko** [comment]
core.utils actually does it:

`                if (element && element.is(":hidden")) {
                    return;
                }`

**Comment by tandraschko** [comment]
improved it to also check visibility. you can check again?

**Comment by fanste** [comment]
The problem was that the visibility property is always considered visible. I did't check the core.utils - my bad...

Your fix with checking the visibility it self works just fine. Thanks
