### ISSUE TITLE
Tree: swapping root elements by drag drop causes an Error

### ISSUE THREAD

**Issue by hansmeiser2000** [primefaces/primefaces#4312]
Open the showcase
https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml
and open the developer tools of 
the browser with F12
In the example drag 'Node 1' above 'Node 0'.
Dependent on your browser you get different errors on the console. After the error is thrown, no further drag'n drop is possible.

FF
![image](https://user-images.githubusercontent.com/25437309/49450246-e87a6000-f7dc-11e8-9590-ae7943ff79da.png)

Chrome
![image](https://user-images.githubusercontent.com/25437309/49450356-195a9500-f7dd-11e8-8222-ee0adb243b6e.png)

..

**Comment by melloware** [comment]
I believe this has been reported 3 times now.  Duplicate of https://github.com/primefaces/primefaces/issues/4091  Please close if it is a dupe.

**Comment by hansmeiser2000** [comment]
Yes that's the error it happens only on root nodes.

**Comment by melloware** [comment]
@tandraschko can you assign https://github.com/primefaces/primefaces/issues/4091 to @mertsincan since this issue keeps getting reported i feel like its something that needs to be fixed by PrimeTek sooner than later without a user PR.

**Comment by melloware** [comment]
Fixed in 6.2.13 with this commit: https://github.com/primefaces/primefaces/commit/4cf1d84cd57511271ec2d77721e8159d0c13ea89

**Comment by hansmeiser2000** [comment]
Thank you for the quick fix, I patched it in components.js in primefaces-6.2.11.jar and it works.
