### ISSUE TITLE
InputSwitch: Rendering inside hidden divs fails

### ISSUE THREAD

**Issue by thereserayza** [primefaces/primefaces#4314]
In primefaces 6.1, when a container with `style="display:none;'` has an inputSwitch inside and the container is toggled, the inputSwitch is not rendered (only showing a thin gray line) and its CSS attributes are empty. When the style of the container is removed, it is displayed normally.

**Comment by tandraschko** [comment]
This is no valid issue, please follow our issue template and provide the required&runnable example.

**Comment by melloware** [comment]
IF you read this ticket InputSwitch is being deprecated for ToggleSwitch.  https://github.com/primefaces/primefaces/issues/3969

**Comment by Rapster** [comment]
@thereserayza could you please try with toggleSwitch. It's available in PF 6.2.8, or you'll have to wait for 6.3. In any case, don't expect a fix for this issue as this component is no longer maintened
