### ISSUE TITLE
inputNumber: Can't clear input field when minimun value is not equal to zero

### ISSUE THREAD

**Issue by BryanV91** [primefaces/primefaces#4315]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: WildFly 13
- Affected browsers: Chrome, Firefox

## 2) Expected behavior

Whenever I press backspace or delete key, input field must be cleared.

## 3) Actual behavior

Whenever I press backspace or delete key, input field stays with the same value, unless I do a full selection with my mouse and then press backspace or delete key.

## 4) Steps to reproduce

See sample XHTML.

## 5) Sample XHTML

Doesn't work.

`<p:inputNumber minValue="1" maxValue="6" />`

Works correctly.

`<p:inputNumber minValue="0" maxValue="6" />`

## 6) Sample bean

Not necessary.

**Comment by tandraschko** [comment]
Thats by design from the used autonumeric plugin.
This was alraedy discussed multiple times in the past: https://github.com/primefaces/primefaces/issues/3025
