### ISSUE TITLE
RemoteCommand: The form attribute is ignored

### ISSUE THREAD

**Issue by schulzp** [primefaces/primefaces#4317]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: WildFly 14
- Affected browsers: Any

## 2) Expected behavior

Using `<p:remoteCommand form=":rootForm" />` outside a `h:form` should render fine.

## 3) Actual behavior

Using `<p:remoteCommand form=":rootForm" />` outside a `h:form` causes a `javax.faces.FacesException: RemoteCommand 'doStuff'must be inside a form.`

## 4) Steps to reproduce

* create a plain view file `remote-command-test.xhtml`
* insert `<p:remoteCommand form=":rootForm" />` (*not* nested inside a `h:form`, see below)
* try to render the view.

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<h:body>

  <h:form id="rootForm" />

  <p:remoteCommand form=":rootForm" />

</h:body>
</html>
```

Like #2358 this is caused by the [renderer](https://github.com/primefaces/primefaces/blob/ae1e952d897e310de6c5b6acb09aa3851b22f870/src/main/java/org/primefaces/component/remotecommand/RemoteCommandRenderer.java#L62) which does not consider the form attribute and instead just looks for the enclosing form. Right now only the [AjaxBehaviorRenderer](https://github.com/primefaces/primefaces/blob/ae1e952d897e310de6c5b6acb09aa3851b22f870/src/main/java/org/primefaces/behavior/ajax/AjaxBehaviorRenderer.java#L97) considers the form attribute at all.

**Comment by melloware** [comment]
Good analysis.  And I agree it looks a lot like #2358 as if PrimeTek had intended on implementing this feature but never actually did.  Interested in in analyzing AjaxBehaviorRenderer and submitting a PR to fix this?

**Comment by melloware** [comment]
Looking at this I think this can be relatively easy to fix.  We need to check if the RemoteCommand has a form set and resolve it, if it has no form set then do the ComponentTraversalUtils.findClosestForm() method.

**Comment by Rapster** [comment]
`p:commandButton` has a form attribute and it works. You can have look from there and provide a PR :wink:
