### ISSUE TITLE
Signature Pad, New Component/feature request.

### ISSUE THREAD

**Issue by srbala** [primefaces/primefaces#432]
I would like to propose new component/feature, **_Signature Pad**_. with the raise of mobile users, mobile optimized views, it would be good addition to PrimeFaces. I would prefer this in mobile components too.

It was [discussed in forums](http://forum.primefaces.org/viewtopic.php?f=3&t=7183&p=28952&hilit=signature+pad#p28952) few years back, I think it never made it to feature request list. 
Review of four possible jQuery library can be used or modeled after as below.

http://www.sitepoint.com/4-jquery-digital-signature-plugins/

http://willowsystems.github.io/jSignature/#/about/ this leads to its original source of https://github.com/brinley/jSignature 
http://thomasjbradley.ca/lab/signature-pad/
http://keith-wood.name/signature.html

Forum discussion link http://forum.primefaces.org/viewtopic.php?f=3&t=42450
Thank you,
Bala

**Comment by srbala** [comment]
Fellow developer suggested another product
https://github.com/triceam/Mobile-Signature-Capture/tree/master/html%20client/src/js   repository
https://raw.githubusercontent.com/triceam/Mobile-Signature-Capture/master/html%20client/src/js/signatureCapture.js   javascript file

License unknown, posted question to developer.

**Comment by srbala** [comment]
Another work of signature capture based on @triceam work;
The link below was the one I was explained you about the signature capture rewrite, this work is generated using coffee script under MIT. 

https://github.com/doublerebel/Mobile-Signature-Capture
https://raw.githubusercontent.com/doublerebel/Mobile-Signature-Capture/master/lib/signaturecapture.js

**Comment by cagataycivici** [comment]
This is likely to be sponsored by a PRO user.

**Comment by srbala** [comment]
That is good news. Looking forward for the new component.

**Comment by cagataycivici** [comment]
See #13, implemented now.
