### ISSUE TITLE
Refactor PrimeFaces#clearTableState

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#4329]
Quoting myself on Gitter:

> I've been using multiviewstate feature on DataTable lately, and I kinda don't like the signature of this method: PrimeFaces#clearTableState. First, name of the parameter is "clientId" which makes me suppose that it expects the clientid of a datatable, but it's wrong. The key set on a table state is actually the combination of a viewId and a clientId (e.g pages/record/search/recordListSearchResult.xhtml_table_form:results:table). And this combination is not a simple concatenation, see DataTable#getTableState
> 
> ```java
>         String viewId = fc.getViewRoot().getViewId().replaceFirst("^/*", "");
>         String stateKey = viewId + "_" + this.getClientId(fc);
> ```
> 
> I would change the signature by clearTableState(String viewId, String clientId), and the impl would do the fiddling. Today I have to make it by myself which is not good thing

@tandraschko coulld we do this on 6.3?

**Comment by tandraschko** [comment]
it's ok for me to mark the old method as @Deprecated and introduce a second overloaded method.
+ add a entry in the MigrationGuide.

**Comment by Rapster** [comment]
At a glance, we could have these methods:

- clearMultiViewStates(String key) (e.g key being Constants.TABLE_STATE, or DATALIST_STATE, could be an enum actually)
- clearMultiViewState(String key, String viewId): clear states of a viewId
- clearMultiViewState(String key, String viewId, String clientId)

Instead of having clearTableState and clearDataListState. Then deprecate these

**Comment by tandraschko** [comment]
@mertsincan WDYT?

**Comment by Rapster** [comment]
Another thought, we could use the same key (e.g Constants.MULTI_VIEW_STATES) for every saved states. It does not change much since the concatenation of viewId and clientId is unique. Unless there is a scenario as follows: "we want to clear all datalist states but not datatable states", still doable but a bit slower

- clearMultiViewStates(): O(1)
- clearMultiViewState(String viewId): O(n) _(at worst)_
- clearMultiViewState(String viewId, String clientId): O(1)

**Comment by Rapster** [comment]
@mertsincan if you could have an opinion on this please. Would be nice to do something about it before RC1

**Comment by tandraschko** [comment]
I would also give my thoughts but not before january.
I would like to review the whole multiviewstate stuff then.

**Comment by mertsincan** [comment]
Yes, it's better if we make these changes after 6.3 release.

**Comment by Rapster** [comment]
@mertsincan Any reason why we're doing this: `String viewId = fc.getViewRoot().getViewId().replaceFirst("^/*", "")` Does it occur a bug if it starts with `/`?

**Comment by mertsincan** [comment]
Hi @Rapster,

I don't remember now, but this was reported by a PRO user. Does the current code cause an error?

**Comment by Rapster** [comment]
No it doesn't, I'm just wondering why this tweak... But I tried to reproduced the problem from the PRO user, and I don't have any problem

**Comment by christophs78** [comment]
- clearMultiViewStates(): O(1)
- clearMultiViewState(String viewId): O(n) (at worst)
- clearMultiViewState(String viewId, String clientId): O(1)

as you suggested should do the work.
It would hide the internal build of the key. And you are able to control to amount of MultiViewState you want to clean. I think this granularity ist fine enough. IMO we don´t need to differentiate the state of DataList and DataTable´s within a view.

**Comment by christophs78** [comment]
One additonal idea: Currently the multiViewState is stored session-scoped. JSF 2.2 would allow to save multiViewState an a per browser-tab granularity. (Use-case: User opens multiple independent instances of your application in different browser-tabs.)
@tandraschko - What do you think about increasing the minimum JSF-Version required by Primefaces 7.1? Are there still some people which stick to JSF 2.0 and upgrade to new PF-versions?

**Comment by tandraschko** [comment]
i don't think we can upgrade, there are still many JSF 2.1 users

**Comment by christophs78** [comment]
PF 7.1 requires Java 8. Do they use JSF 2.1 with JavaEE 6 and Java8?
I personally would (naive?) expect that Java8 is often combined with a JavaEE 7 or JavaEE 8 - application server. Or they use something like Tomcat with Java8+ and bring JSF on their own.
Maybe i´m a bit naive to expect people which update Java-versions and PF-versions to also update JSF-versions....

**Comment by tandraschko** [comment]
Sure why not.
Upgrading a application server with many old applications brings much more problems as updating to java8  or update one single application to PF 7.x.

**Comment by melloware** [comment]
@christophs78 I know at my one client we use Jboss EAP 6 which is JSF 2.1 running Java 8.

**Comment by christophs78** [comment]
Understand. :-) Thanks for your feedback!

**Comment by Rapster** [comment]
PR available here: https://github.com/primefaces/primefaces/pull/4906

Waiting for feedbacks ;-)

**Comment by tandraschko** [comment]
@Rapster can you also align the docu?

**Comment by Rapster** [comment]
I'll do that, also I'm thinking of renaming methods, call these like this `PrimeFaces.current().multiViewState().clearMultiViewStates()` is a bit too repetitive

**Comment by Rapster** [comment]
and should I use an acronym for `multiViewState` like `mvs`?

**Comment by Rapster** [comment]
@tandraschko @melloware I'd like to have your opinion on my last comments please

**Comment by melloware** [comment]
@Rapster I like the full word PrimeFaces.current().multiViewState() and since you are prefixing it with that namespace maybe you can just say clear like...

`PrimeFaces.current().multiViewState().clear()`

**Comment by Rapster** [comment]
Alright perfect, I was either aiming for acronym like `mvs` or renaming methods like you just mentionned. I'll do that then thanks

**Comment by tandraschko** [comment]
yep, +1 for no shorcut too
