### ISSUE TITLE
DataTable: Allow Enter and Esc to be used in editing to confirm/cancel editing

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#433]
Having a `<p:datatable>` with a `<p:rowEditor>`, it would be quite natural to be able to use Enter to confirm editing and Esc to cancel it. Instead, these keys are currently ignored and captured by other elements in the page.

**Comment by mauromol** [comment]
Currently, since there's no client-side API for doing this, it's a bit hard to make this work:
http://stackoverflow.com/questions/13287220/using-return-enter-key-to-save-edited-cell-in-primefaces-3-4-in-cell-editable-da

**Comment by cagataycivici** [comment]
CellEditor supports these (editMode="cell"), by design we don't support it for row edit. If more users require it, I'll reopen.

**Comment by mauromol** [comment]
OK Catagay, but please reconsider. That's the first thing I tried to do as soon as I started typing something in the fields of the edited row. I think it's also a matter of accessibility: right now, you are forced to take the mouse, move its pointer and click on the "check" icon to confirm.

I can't think of any good reason for which they shouldn't be implemented "by design".

**Comment by cagataycivici** [comment]
Ok, I'll reopen to see if more users will demand it. I have some performance changes upcoming in 5.3 to row editor, maybe will do it along the way.

**Comment by bsanders1979** [comment]
I've actually implemented this very functionality (not the escape key) and it was pretty easy to do. However, I added the escape piece because it's pretty simple. I can see why it's not implemented OOTB because it might be difficult to cover all use cases without overstepping boundaries.

```
<p:dataTable widgetVar="datatable" rowIndexVar="rowIndex">
    <p:column>
        <p:cellEditor>
            <f:facet name="input">
                <p:inputText
                    onkeydown="PF('datatable').onKeyDown(event)"
                    onkeyup="PF('datatable').onKeyUp(event, #{rowIndex})"
                />
            </f:facet>
        </p:cellEditor>
    </p:column>
</p:dataTable>

<script type="text/javascript">
//<![CDATA[
    $(function() {
        $.extend(PF("datatable"), {
            onKeyDown : function(e) {
                var key = e.which,
                    keyCode = $.ui.keyCode;

                if((key === keyCode.ENTER||key === keyCode.NUMPAD_ENTER)) {
                    e.preventDefault();
                }
            },

            onKeyUp : function(e, rowIndex) {
                var key = e.which,
                    keyCode = $.ui.keyCode;

                if((key === keyCode.ENTER||key === keyCode.NUMPAD_ENTER)) {
                    this.tbody
                        .find('.ui-row-editor .ui-icon-check')
                        .eq(rowIndex)
                        .click();
                }

                if (key === keyCode.ESCAPE) {
                    this.tbody
                        .find('.ui-row-editor .ui-icon-close')
                        .eq(rowIndex)
                        .click();
                }
            }
        });
    });
//]]/>
</script>
```

**Comment by mauromol** [comment]
Actually, I'm currently using the code provided by BalusC on Stackoverflow with no issues so far. It's quite brief. I'm reporting it here how the Enter key is handled:

``` javascript
$(document).on("keydown", ".ui-cell-editor-input input", function(event) {
    if (event.keyCode == 13) {
        $(this).closest("tr").find(".ui-row-editor .ui-icon-check").click();
    }
});
```

**Comment by kannextic** [comment]
I'd like this function, or at least the option to enable it for RowEditor.

**Comment by victorcarvalhosp** [comment]
We need this option too... All of our customers click ENTER and think something is wrong...

**Comment by samphire** [comment]
I implemented the BalusC code and it works like a charm... except that if I type a space in the cell I am editing, nothing I type is entered any more. Any ideas why?

**Comment by yannickb85** [comment]
We need this option too.

**Comment by bgmoon** [comment]
Need this option for "in place" as well :)

**Comment by cagataycivici** [comment]
Please create a separate ticket for inplace and we'll discuss.

**Comment by okworx** [comment]
I'd like this function as well OOTB.

**Comment by ademcaliskan** [comment]
+1
That's the usual way I think. Click enter to accept changes and esc to cancel editing.

**Comment by ghost** [comment]
+1

**Comment by elab** [comment]
Slightly modified version of the [BalusC code](https://stackoverflow.com/a/18613759/522578) cited by @mauromol [above](#issuecomment-116488027):
- prevent adding new row to the table on "Enter" click
- cancel editing on "Escape" click
```javascript
$(document).on("keydown", ".ui-cell-editor-input input", function(event) {
    if (event.keyCode == 13) { // Enter
        $(this).closest("tr").find(".ui-row-editor .ui-icon-check").click();
        return false; // prevents executing other event handlers (adding new row to the table)
    }
    if (event.keyCode == 27) { // Escape
        $(this).closest("tr").find(".ui-row-editor .ui-icon-close").click();
        return false;
    }
});
```

**Comment by melloware** [comment]
@elab.  I am using the showcase and your fix for Cell editor is already natively in the latest Showcase Cell Edit event: https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml  This ticket was about ROW editing right?

Nevermind: I see you are attaching to the Cell Editor to close the row editor.

**Comment by elab** [comment]
@melloware yes, the ticket is about the row editing.
I'm (actually, BalusC) attaching the handler to the cell editor as the key press is happening in an input element which is located under div with the "ui-cell-editor-input" class (while we are on row editing):
```
<div class="ui-cell-editor-input">
    <span id="form:table:12:j_idt61" class="ui-inputnumber ui-widget"
	    <input id="form:table:12:j_idt61_input" name="form:table:12:j_idt61_input" type="text" ...
```
(just checked that)

**Comment by melloware** [comment]
OK I submitted a PR.  I modified all answers slightly.

1. Use `:input` instead of `input` so if you are are a select dropdown you can still press ENTER or ESC.  Previously it would only work if you were in an input box.

2. Modified the ROW finder to use the more specific styles `.ui-row-editor-check` and `..ui-row-editor-close` instead of `.ui-row-editor .ui-icon-close`

3. used Jquery constants for ENTER and ESC.

**Comment by elab** [comment]
@melloware: you made me thinking about,  we could in fact catch key events for the row itself (to automatically cover any input elements), this also simplifies the code a bit:

```javascript
$(document).on("keydown", "tr.ui-row-editing", function(event) {
	if (event.keyCode == 13) { // Enter
		$(this).find(".ui-row-editor .ui-icon-check").click();
		return false; // prevents executing other event handlers (adding new row to the table)
	}
	if (event.keyCode == 27) { // Escape
		$(this).find(".ui-row-editor .ui-icon-close").click();
		return false;
	}
});
```

**Comment by melloware** [comment]
@elab I think the problem is the `ui-row-editing` style does NOT appear until you actually click and edit a row.  So when the component loads no rows are marked with `ui-row-editing` yet right?

**Comment by elab** [comment]
In the initial state no rows are marked with that, right.
But it works. It looks like browser's event processing always takes the current state of elements into consideration when processing events.

**Comment by melloware** [comment]
Cool let me test it locally and update my PR.

**Comment by melloware** [comment]
Tested and its working great.  PR updated.
