### ISSUE TITLE
Modernize Documentation

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#4332]
Documentation is currently done offline using a word processor, we should make expose it to markdown or similar to committer can maintain it.

**Comment by tandraschko** [comment]
Finally! :) Thats a good decision

**Comment by Rapster** [comment]
Sounds awesome! Does the final support has to be a PDF? If not, we could simply use github pages. We could use primefaces/primefaces repo itself, I can work on a first draft if that's okay?

**Comment by cnsgithub** [comment]
Good decision!

Maybe we could also define some templates (e.g. freemarker or velocity) to automatically get attributes and descriptions out of `primefaces-p.taglib.xml`. This would ensure code and documentation to be in sync.

**Comment by melloware** [comment]
So just throwing my two cents in Spring Boot projects use something called AsciiDoc.  http://asciidoc.org/

The files are all stored in GitHub, but the output can be HTML, PDF, ePUB etc.  For an example of what Spring boot documentation looks like check out this: https://cloud.spring.io/spring-cloud-netflix/2.0.x/

It generates single page HTML or MultiPage and I think it looks quite nice.

**Comment by cnsgithub** [comment]
> So just throwing my two cents in Spring Boot projects use something called AsciiDoc. http://asciidoc.org/

I'd like that! Introducing a table of content or things like that work like a charm.

We could have included static as well as dynamically generated contents.

**Comment by cnsgithub** [comment]
Automatically publishing generated docs via `mvn site `to GitHub Pages would be cool: https://github.github.com/maven-plugins/site-plugin/

**Comment by cnsgithub** [comment]
There's the [Asciidoctor ](https://asciidoctor.org/) (also available via `asciidoctor-maven-plugin`) that is able to generate different formats like HTML from `adoc` files.

**Comment by melloware** [comment]
@cnsgithub this is an example Spring Boot project doc so you can see the layout of the .adoc pages and the Maven pom.xml to generate.  https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-docs

**Comment by tandraschko** [comment]
TomEE also uses adoc + JBake.
Here is a small history what TomEE did in the past: http://tomee-openejb.979440.n4.nabble.com/Merging-Old-and-New-Websites-td4685488.html

**Comment by mertsincan** [comment]
![image](https://user-images.githubusercontent.com/11868120/50093010-93007300-0220-11e9-81cd-913addc9938b.png)

I did a little work for 6.2; https://github.com/primefaces/primefaces/wiki/Configuration
I've finished the section 1 and 2. Also, I can move old pages such as 'Building From Source', 'Locales', 'Migration Guide', 'Contributing to PrimeFaces' and 'More secure file upload' to custom sidebar

**Comment by tandraschko** [comment]
puh
to be honest, i would not put in the wiki.
Currently 2.1-2.4 is just available as single pages, i would like to see that i could also click on 2. and all 2.x are listed on the view. 
Otherwise it's annoying as hell.

**Comment by tandraschko** [comment]
Maybe it would be much better if we would just have a "2. Setup" page instead of Y sub-pages.

**Comment by mertsincan** [comment]
I've created using the pdf structure. Modifications can, of course, be made. Some pages may even be unnecessary. I'm just waiting for feedback :D Maybe we won't use wiki. This is just a test.

**Comment by Rapster** [comment]
@mertsincan At first, I thought the same, converting pdf into markdown and simply migrating, this is why I mentionned to reuse github's markdown support and hosting... I didn't expect there would be so much excitement about this ticket, but I guess we can do much better than a simple migration. 

It would be awesome to generate component properties documentation through primefaces taglib xml. It means no more ticket about updating the documentation!

For doing so, we need proper tools, supporting at least processing and templating feature, a few have been mentionned: https://asciidoctor.org and https://jbake.org/

So far, I feel that https://asciidoctor.org could be enough, it depends what we really want to achieve at the end

**Comment by Rapster** [comment]
Problem using wiki is that, it will always shows last version, while we should show documentation according to a certain version (e.g doc of 6.2 or 6.3 or 7.0). Using git tags? Probably

**Comment by mertsincan** [comment]
![image](https://user-images.githubusercontent.com/11868120/50094725-ea084700-0224-11e9-8272-bb199bec887c.png)

Please see my screenshot. Some pages may be the same. For example, if a component on 6.2 and 6.3 have not changed at all, it is enough to direct only one page for both versions.

Exp;
For 6.2 and 6.3
``` * [1.1 What is PrimeFaces?](https://github.com/primefaces/primefaces/wiki/What-is-PrimeFaces%3F)```

Please try https://github.com/primefaces/primefaces/wiki

**Comment by tandraschko** [comment]
I don't think that wiki is the nicest ways.
As i said, each li/ul is a completly own and "delimited" view. 
We could fix that by other structures (remove 2.x, just put everything in 2.) but not sure...
Also there is no search in wiki.

If possible, i would really like to have the documentation in the src directory, so it's tagged with the source code and we can auto-generate stuff like the component properties.

**Comment by cnsgithub** [comment]
Furthermore wiki is not per default read-only, is it? Everyone can modify without PR.

**Comment by tandraschko** [comment]
yep, thats another -0.5 for me

**Comment by Rapster** [comment]
You can change an option to make wiki editable by collaborators. But indeed, no PR feature on this (which is basically what we need the most)

**Comment by Rapster** [comment]
@primefaces/committers @melloware @cnsgithub Do we need to keep skinning/CSS classes in documentation? I personnaly never had to use it

**Comment by melloware** [comment]
@Rapster do you mean sections in the PDF that say if you want to override XX use .ui-toolbar style etc?    I usually don't look through the documentation for this  I usually just end up studying the style classes etc.  But I can't say whether it doesn't help everyone.   I personally would be OK removing them from the docs.

**Comment by tandraschko** [comment]
Could you give a example? UserGuide Page XXX?

**Comment by Rapster** [comment]
Page 18, 36 etc. (from 6.2)

**Comment by Rapster** [comment]
Sorry I meant "skinning/CSS classes section"

**Comment by tandraschko** [comment]
Ahh i see. I would keep it for now as we already have it.
The benefit isn't big of course as it doesn't cover all cases but it think it's ok as entrypoint for users.

**Comment by Rapster** [comment]
I said that 'cause the whole migration is a heavy task... So if we can get rid of these, it'd a lot more easier 😋 Anyway, if you'd like to contribute, let me know so I can add you as contributor, just checkout my repos: https://github.com/Rapster/primefaces-asciidoc and https://github.com/Rapster/primefaces/tree/fix-4332

Feel free to come up with some kick ass ideas 😉 I thought about generating the client side API, but some function are not "javascript-doced" and I thought private functions were prefixed by "_", it turns out it's not always true...

@tandraschko I thought about having the ascii-doc sources in the same repo, why not having primefaces as a module parent, ascii-doc as a child module, we could actually do the same for showcase

**Comment by tandraschko** [comment]
So you say that the Initial work is done and we just need to migrate content?
If yes, we could apply the PR probably, publish the first result and ask the community to Help?

How can we host? How can User reach it?

I would really parse the wigets for publics APIs. If you check the js files from Extensions, we can just add "@public" to those methods AFAIR



What so you exactly mean with the modules?

**Comment by Rapster** [comment]
Yes, the initial work is done. What's left is migrating into asciidoc, using processors and insert new images with current luna themes.

What I mean by module, is a maven module:
```
 +-- primefaces (parent)
 |   + -- src
 |        + -- main
 |   + -- asciidoc (asciidoc extension src)
 |   + -- showcase (showcase src)
```

Yes I guess, we can apply the PR, but either `primefaces-asciidoc` becomes a child module or we need a new repo for it. I prefer the first option. Either way, it'll be better using primefaces repos than mines.

I guess using `@public` is better than using naming conventions I agree so +1. But still, we need to doc these.

**Comment by tandraschko** [comment]
OK. I need to talk with cagatay about the repo changes but that will make life easier for us.
But we need the release first.

I meantime it would be perfect if you would complete the technical part and also parse the js wigets + apply the correct js method docus to wigets which are already migrated to the system.

Thank you for your great contributions. Thats an big task now, same as removing the old maven Plugin.

**Comment by melloware** [comment]
+1 on all your hard work @Rapster this will make life so much easier going forward.

**Comment by Rapster** [comment]
UPDATE: The Client API is from now on generated :wink:

**Comment by melloware** [comment]
Nice work!

**Comment by tandraschko** [comment]
Yeah!!!

**Comment by Rapster** [comment]
If you have any suggestions, feel free: [index.txt](https://github.com/primefaces/primefaces/files/2730941/index.txt)


P.S: To rename into .html (Of course, they are plenty of sections that has not been migrated yet, I can't do all of that on my own 😄 )

**Comment by tandraschko** [comment]
looks nice on the first view!

How do you lookup the default values of the attribtues? Could we read them from the java classes, as there is no "default" node in the taglib?

(also seems like the tables of most of the components are not generated correctly for now? Starts from the Calender componet)

**Comment by Rapster** [comment]
I didn't touch the Calendar component (if you don't see a `_<tagName>.adoc` it means I didn't touch it. Regarding the default value, I have this for example:

```xml
        <attribute>
            <description><![CDATA[Mode for filtering valid values are exact (default) and contains.]]></description>
            <name>filterMode</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>exact</defaultValue>
        </attribute>
```

But I just realized indeed `defaultValue `is not supported in taglib.xsd... Quite annoying as sometimes we put the default value in the description itself

**Comment by tandraschko** [comment]
yep exactly.
I think we can do 2 things:
1) read the default values from the classes
2) verify that each description in the taglib has the default value at the end and read it from there

probably 2) is the better way as we would also have it in the code completion in the IDE.

**Comment by Rapster** [comment]
Arf even 2 is annoying... But I guess we don't have a lot of choice, unless it's "legit" to add our own xml tag? Okay for 2, but we need a standard way to define default value (e.g `Default value(s) is|are: blablablah`)

**Comment by Rapster** [comment]
Definitely will need help, I'd like to work on #4278 again, and soon the RC1 will be released and there is at least one ticket I'd like to have a look at #3971 before final

**Comment by tandraschko** [comment]
Im not an xsd pro but it could be possible via an own namespace. But even If we do, we probably still need it in the description for the IDE.
As i said, If would be cool If you could finish the technical stuff, everything else will need manpower from PrimeTek and/or community.

**Comment by cnsgithub** [comment]
This is what I've found in [Practical RichFaces](https://books.google.de/books?id=g3TCFczl0IwC&pg=SA10-PA74&lpg=SA10-PA74&dq=facelet-taglib+default+value&source=bl&ots=Gg_fAbGA9g&sig=Qx7cQspaY3T0e3SSlQmVPouMujU&sa=X&redir_esc=y#v=onepage&q=facelet-taglib%20default%20value&f=false):

![image](https://user-images.githubusercontent.com/13161711/50757062-72936980-125e-11e9-8340-9ffa765ff70c.png)

Couldn't we just provide our own component annotations, put them on `UIComponent `getters together with default values and generate the taglib content out of them? There would be just one place then for the component definition. and nothing has to be repeated. We could also include the default value in the generated taglib `description`.

**Comment by Rapster** [comment]
Yup it would have been the best option, CDK has been part of a long discussion in https://github.com/primefaces/maven-jsf-plugin/issues/4 and https://github.com/primefaces/primefaces/issues/3967, I even created a tool `primefaces-cdk` but it has been decided to do otherwise. I think Thomas didn't want to introduce a new tool and keep the complexity low.  

@tandraschko I don't know about introducing a new namespace, I don't think it would fix anything from our original problem... IMO, The JSF guys should introduce this tag in the specs, but for now I guess we'll have to read from tag's description

**Comment by melloware** [comment]
Sadly I guess we can close this ticket because the documentation decision to use Docsify has been made and is now the new standard.
