### ISSUE TITLE
TreeTable: Make TreeNode interface serializable

### ISSUE THREAD

**Issue by jansohn** [primefaces/primefaces#4335]
## 1) Environment
- PrimeFaces version: 6.1.12
- Does it work on the newest released PrimeFaces version? Version? - No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) - No
- Application server + version: Apache Tomcat 8.5
- Affected browsers:

## 2) Expected behavior
`TreeNode` interface should extend `Serializable` so we can use it as a member variable in our backing beans.

## 3) Actual behavior
`TreeNode` interface does not extend `Serializable` although both its implementation classes `CheckboxTreeNode` and `DefaultTreeNode` implement the `Serializable` interface.
This produces warnings like `Make "treeTableRoot" transient or serializable.` and gives problems during undeploy and redeploy phases of the web application.

## 4) Steps to reproduce
see showcase: https://www.primefaces.org/showcase/ui/data/treetable/basic.xhtml

## 5) Sample XHTML
see showcase: https://www.primefaces.org/showcase/ui/data/treetable/basic.xhtml

## 6) Sample bean
see showcase: https://www.primefaces.org/showcase/ui/data/treetable/basic.xhtml

**Comment by tandraschko** [comment]
If you have a field:
private TreeNode treeNode = new DefaultTreeNode()
it should still be serializable.
And per default, a treeNode must NOT be serializable. A user could also build the model on each request.

**Comment by jansohn** [comment]
> 
> 
> And per default, a treeNode must NOT be serializable. A user could also build the model on each request.

I'm not quite sure I can follow you here. Are you talking about `@RequestScoped` beans?

I don't see how adding the `Serializable` interface to `TreeNode` would break anything? If the custom class does not implement `Serializable` then `TreeNode` would not be serialized anyway...

**Comment by tandraschko** [comment]
Exactly.

And i don't see how making it Serializable would avoid a bug at your side. It's just a IDE warning.

The custom class doesn't need to implemenet Serializable with your suggestion, it would be inherited by implementing TreeNode.

**Comment by jansohn** [comment]
So we could add it to avoid the warning?

**Comment by tandraschko** [comment]
I currently don't see any real reason to add it.
If we would make it serializable and users implement it (maybe stored in RequestScoped beans) with  non-serializable fields, they would also see a warning in the IDE ;)

If the warning is annoying for you and as you are already use DefaultTreeNode, why not just use the DefaultTreeNode in your model?

**Comment by jansohn** [comment]
In your (far fetched) example where someone implements their own `TreeNode` class the programmer would simply need to implement

    private void writeObject(java.io.ObjectOutputStream out)
        throws IOException
    private void readObject(java.io.ObjectInputStream in)
        throws IOException, ClassNotFoundException;

to serialize / deserialize non-serializable fields, nothing hard about that.

Reasons against directly using `DefaultTreeNode`:
- It's best practice to program to interfaces
- The node events return the interface (e.g. `NodeUnselectEvent.getTreeNode()`) which requires unnecessary type checking and casting

IMHO this change would have practically no risk (3 lines of code change) while making the life easier for everybody using it.

**Comment by melloware** [comment]
I submitted a PR.  To me this seems like a good change, that should not have any downstream impacts.  @tandraschko if you disagree you can of course reject the PR!

**Comment by Rapster** [comment]
> This produces warnings like Make "treeTableRoot" transient or serializable. and gives problems during undeploy and redeploy phases of the web application.

What's the problem? Maybe the real problem is there and not in PF. Regarding your warning, it might be a bad design, I'm guessing your class implements Serializable, but TreeNode does not. Fair enough, but are you sure you want treenode as attribute and not the corresponding data?

> IMHO this change would have practically no risk (3 lines of code change) while making the life easier for everybody using it.

I agree, in theory implements shouldn't change anything but that's something we can't be 100% sure. 😄 

Implementing Serializable does not really make sense to me, as we don't serialize `TreeNode` anywhere in PF, so why imply that while we're not doing it? It gives a wrong indication to developers. I would use Serializable for serializable reasons (e.g web services, export xml, etc.). TreeNode is a UI representation of your model, not meant to be serializable.

**Comment by tandraschko** [comment]
We dont serialize it, right. But most people use it in ViewScoped beans and the Bean needs to implement serializeable with CDI. Therefore the warning occurs with the IDE.

But its just a warning...

**Comment by tandraschko** [comment]
Lets close it until there is a real reason. both with and without serializeable has pro and contras from cosmetical perspective.

**Comment by Rapster** [comment]
Ah I see, that's a different story then... Indeed from https://docs.oracle.com/javaee/7/api/javax/faces/view/ViewScoped.html, it says

> Use of this annotation requires that any beans stored in view scope must be serializable and proxyable as defined in the CDI specification.

And from Omnifaces ViewScoped

> Please note that the bean must implement Serializable, otherwise the CDI implementation will throw an exception about the bean not being passivation capable.

**Comment by jansohn** [comment]
> 
> 
> > This produces warnings like Make "treeTableRoot" transient or serializable. and gives problems during undeploy and redeploy phases of the web application.
> 
> What's the problem? Maybe the real problem is there and not in PF. Regarding your warning, it might be a bad design, I'm guessing your class implements Serializable, but TreeNode does not. Fair enough, but are you sure you want treenode as attribute and not the corresponding data?
> 
> > IMHO this change would have practically no risk (3 lines of code change) while making the life easier for everybody using it.
> 
> I agree, in theory implements shouldn't change anything but that's something we can't be 100% sure. 😄
> 
> Implementing Serializable does not really make sense to me, as we don't serialize `TreeNode` anywhere in PF, so why imply that while we're not doing it? It gives a wrong indication to developers. I would use Serializable for serializable reasons (e.g web services, export xml, etc.). TreeNode is a UI representation of your model, not meant to be serializable.

Did you even take a look at the showcase of `treeTable`? Because what you are writing does not make any sense, sorry to be so blunt...

Please just take a look at the `basic.xhtml` and the `BasicView.java` of the showcase example. There's no way to NOT use it as a member variable.

**Comment by Rapster** [comment]
Hi @jansohn,

It's okay, I don't consider myself as a "know-it-all" in JSF, so there are few things that I might be missing out... See my comment right there: https://github.com/primefaces/primefaces/issues/4335#issuecomment-450729230

It's easy to say it does not make any sense, but you have to justify this statement as I don't see you giving relevant reasons to do it! 😉 Although, the fact that the specification mentions ViewScoped must be Serializable, and BalusC statement annoys me... I had a look at the showcase, and with or without Serializable works also very fine, no warning, no exception. So I guess your last statement is wrong 😋 

Now back to the real "problem" (if there is any), we have to consider this use case (using TreeNode, and others PF model in ViewScoped beans) to happen, and also, the spec is pretty clear on this. Also another statement from BalusC (see http://balusc.omnifaces.org/2010/06/benefits-and-pitfalls-of-viewscoped.html):

> Note that the bean needs to implement Serializable as it will be stored in the view map which is in turn stored in the session. Some servletcontainer configurations will namely store sessions on disk instead of in memory. This is also mandatory when you have configured JSF view state saving method to client instead of (default) server.

So if we want to be compliant with the specs, then we should probably do it (but that mean to do that for other PF model then no?)

**Comment by tandraschko** [comment]
JSF ManagedBean ViewScoped must not implement Serializeable until you enable state serialization to session. With the JSF CDI you would get an exception on Startup.


As i said already, its just a hint from the IDE. Serialization is fine If you declare the Interface but the instance is a serializable impl.

**Comment by jansohn** [comment]
CDI is pretty much standard now in web applications so the right thing to do would be to add the Serializable interface and fix the serialization issues in the implementations (https://github.com/primefaces/primefaces/pull/4338#pullrequestreview-186531859). Just closing this issue and ignoring it doesn't solve anything...

**Comment by tandraschko** [comment]
There is no issue - or can give me a example which throws a exception?

**Comment by jansohn** [comment]
I can give two examples.

1\) Create a custom TreeNode class which does not implement Serializable and contains a non-serializable member variable, e.g. a `Thread` object. This throws `java.io.NotSerializableException`:

    WARNING: Cannot serialize session attribute [com.sun.faces.application.view.activeViewMaps] for session [9B3FD35F0CAC2195EB0127AE56E2E5C0]
    java.io.NotSerializableException: com.test.CustomTreeNode
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        [...]

2\) Use a data bean (`Document` in the showcase) which does not implement Serializable and contains a non-serializable member variable, e.g. a `Thread` object. This again throws a `java.io.NotSerializableException`, just on a different object:

    WARNING: Cannot serialize session attribute [com.sun.faces.application.view.activeViewMaps] for session [9B3FD35F0CAC2195EB0127AE56E2E5C0]
    java.io.NotSerializableException: com.test.Document
    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	[...]

I do understand that adding the Serializable interface would only "fix" the first example but it is the safer way to code IMHO. Define it in the contract and make it harder to make mistakes in the future. Plus it would get rid of the IDE warning which at the moment (!) is a false-positive, I agree, but only because all implementations currently implement the Serializable interface explicitly.

**Comment by melloware** [comment]
I think the long term fix for PF 7.0 should be in any of our "Default" objects or interfaces we should be using Serializable instead of java.lang.Object.  But that would be something we would have to get buy in from PrimeTek for.

**Comment by tandraschko** [comment]
@melloware we don't need to buy in or something, we just need a good reason, i can discuss it and i can apply it.

@jansohn 
Don't get me wrong, i'm happy that we have such a good discussion here - and it's good for a framework to have such users! :)

1) is not an real issue for me. If the user uses serialization, he can easily add Serializable to his custom TreeNode.
2) is even unrelated.

Sometimes there is not only one case, we have many cases which we need to consider - also if your case is probably the most used one.
If we would add "extend Serializable", we need to change "data" to Serializable to make it more correct.

This change would even break some applications....
Many people use ViewScoped beans, which will never get serialized as they don't use clustering.
So what they do is to put normal POJOs into the TreeNode data. This POJO are most of the time even not serializable as they just don't need it.
Now if we would change the "data" to Serializable, many applications wouldn't even compile as their POJOs doesn't implement serializable.

I could also list ~2 other cases, which will also give real problem instead of a IDE warning.

As you can see, there is no perfect way.
Maybe the only way is to add another interface "SerializableTreeNode" with a Serializable data. But is it worth for a IDE warning?

**Comment by jansohn** [comment]
> 
> 
> If we would add "extend Serializable", we need to change "data" to Serializable to make it more correct.

I have to disagree here. It would be perfectly fine to extend Serializable as a first step now (doesn't break anything) and fix the data type in a major release later on because it might break things (though most POJOs should already implement Serializable).

>
>
> Now if we would change the "data" to Serializable, many applications wouldn't even compile as their POJOs doesn't implement serializable.

In this case they will already get `java.io.NotSerializableException` during re-/undeploy phases. I'd argue that having the error visible at compile time is better.

I certainly don't think that adding another interface makes sense btw!

**Comment by tandraschko** [comment]
> In this case they will already get java.io.NotSerializableException during re-/undeploy phases. I'd argue that having the error visible at compile time is better.

Thats not true. As i said it's perfectly fine and used (actually most of the times) that ViewScoped is not serialized into the session.

**Comment by jansohn** [comment]
I stand corrected for `@ManagedBean`. Haven't used those for ages. They are already deprecated in JSF 2.3 so I would question your "most of the times".

**Comment by tandraschko** [comment]
It's the same for CDI.
You will only see a serialization exception if:
- the field in your Session or ViewScoped bean is not serializable
  && javax.faces.SERIALIZE_SERVER_STATE == true
  && container session persistence / replication is enabled

**Comment by tandraschko** [comment]
(probably javax.faces.SERIALIZE_SERVER_STATE doesn't even matter here, not sure about the exact state saving impl since 2.3)

**Comment by jansohn** [comment]
> 
> 
> It's the same for CDI.
> You will only see a serialization exception if:
> 
>     * the field in your Session or ViewScoped bean is not serializable
>       && javax.faces.SERIALIZE_SERVER_STATE == true
>       && container session persistence / replication is enabled

Why does the official documentation (https://docs.oracle.com/javaee/7/api/javax/faces/view/ViewScoped.html) say otherwise then?

>
>
> Use of this annotation requires that any beans stored in view scope must be serializable and proxyable as defined in the CDI specification.

Sounds pretty clear to me.

**Comment by tandraschko** [comment]
I dont know ;)

**Comment by melloware** [comment]
@jansohn I guess the CDI vendors chose to delay any errors until the bean actually get serialized rather than checking the bean and failing up front.

**Comment by jansohn** [comment]
@melloware this is described here (https://www.knitelius.com/2016/05/18/cdi-passivation-uncovered/)

>
>
> It is important to note that the CDI container, as per specification, is only required to validate injection points. All other members are ignored by the container.
> [...]
> Even though MySession passes the CDI deployment validation, it will fail serialization at runtime due to its non-transient unserializable member causing a java.io.NotSerializableException. All unmanaged members have to be either serializable or transient.

**Comment by melloware** [comment]
ahh yep that explains it.  So if you just have a ViewScoped or SessionScoped bean used only by JSF and not injected anywhere it is not being scanned for passivation.

**Comment by tandraschko** [comment]
it's just impossible to validate this earlier as the object instances can be different.

In OWB we just validate if the bean implements Serializable, everything else can only be done by the servlet container when the session map is serialized to disk or other instances.
