### ISSUE TITLE
TreeTable: support Select All Checkbox

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4336]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
Similar to a Data Table there should be checkbox option to Select All , Deselct All for a TreeTable.
![image](https://user-images.githubusercontent.com/15189434/50163850-52036f80-02af-11e9-99de-12a2013e9ae8.png)

...

## 3) Actual behavior
![image](https://user-images.githubusercontent.com/15189434/50163932-79f2d300-02af-11e9-8906-426b7be10cf6.png)

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

https://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml

..

## 6) Sample bean

..

**Comment by melloware** [comment]
You can do this with a facet easily on the column header:
```xml
<f:facet name="header">
    <p:selectBooleanCheckbox>
            <pe:javascript event="valueChange" execute="PF('treeTable').jq.find(".ui-chkbox-box").trigger('click')"/>
        </p:selectBooleanCheckbox>
</f:facet>
```
