### ISSUE TITLE
datatable: select all option does not work well when using the filter

### ISSUE THREAD

**Issue by kaushikmeduri** [primefaces/primefaces#4337]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
${component}: ${title}
Example:
SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1.19
- Does it work on the newest released PrimeFaces version? Version? Not Sure / it gave other problems when upgraded to 6.2.13
This issue closely related to https://github.com/primefaces/primeng/issues/1862 
Please advise which version has the fix for 1862 
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)  Not Tried
- Application server + version:  Jboss 7
- Affected browsers:  IE , Chrome , Firefox , All browsers 

## 2) Expected behavior

...When using filter with data table and use  selectionMode="multiple"   <p:dataTable selection   reflects array of  selected values  . 

## 3) Actual behavior
...When using filter with data table and use  selectionMode="multiple"   <p:dataTable selection  value does not  reflect selected array of   values  .  Instead it some time shows previous filtered or selected values.

..

## 4) Steps to reproduce

Create a data table , use multi check box for selection.
Once data table is filtered , click on button to read selected values . 
<p:commandButton id="pendingEmailButton" value="Email" 
## 5) Sample XHTML

<p:dataTable id="pendingusers" var="userPending"
emptyMessage="No Pending Approvals" reflow="true"
value="#{userRegistrationBean.pendingUsers}"
selection="#{userRegistrationBean.selectedUsers}"
paginator="false" rowKey="#{userPending.uniqueId}"
filteredValue="#{userRegistrationBean.filteredPendingUsers}"
widgetVar="pendFilterTable"> 
<div align="center">To see details, select one/multiple checkboxes and click "View" button. 
Select Checkboxes and click "Approve" button <br /><br />  </div>

<p:column exportable="false" selectionMode="multiple" style="width:50px;"/>
Once data table is filtered , click on button on screen for export of selected  values ...

<p:commandButton id="pendingEmailButton" value="Email"
## 6) Sample bean

Checkbox code 

..<p:column exportable="false" selectionMode="multiple" style="width:50px;"/> 

.Array of Selctted Checkbox items Bean 

public User[] getSelectedUsers() {
return selectedUsers;
}

public void setSelectedUsers(User[] selectedUsers) {

this.selectedUsers = selectedUsers;
}

**Comment by Rapster** [comment]
Please format your code: https://help.github.com/categories/writing-on-github/

**Comment by melloware** [comment]
Also what is the scope of your "userRegistrationBean".  A better thing to do would be to create a small reproducible example so the developers can debug it.  Simply clone this project and make us a small test project.  https://github.com/primefaces/primefaces-test

**Comment by tandraschko** [comment]
No runnable example -> invalid.

**Comment by kaushikmeduri** [comment]
> No runnable example -> invalid.



> Also what is the scope of your "userRegistrationBean". A better thing to do would be to create a small reproducible example so the developers can debug it. Simply clone this project and make us a small test project. https://github.com/primefaces/primefaces-test

Issue is actually not reproduced every time . Scope is ViewScope.

**Comment by kaushikmeduri** [comment]
> No runnable example -> invalid.

This issue closely related to primefaces/primeng#1862
Mrtcndkn added this to the 2.0-RC2 milestone on Jan 20, 2017

Please advise which version has the fix for 1862.  I have downloaded  6.2.13 , so far issue not produced in 6.2.13 
Could you advise if fix actually went in after 6.1.19?

**Comment by tandraschko** [comment]
primefaces != primeng.
Sorry, but if you can't provide a runnable example / MVCE, i have to close it for now.
Feel free to create a new issue someday with a runnable example, so we can reproduce and fix it.
