### ISSUE TITLE
SelectOneMenu : IE 11 with f:selectItems converts string to scientific notation

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4339]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version?  6.2 No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: NA
- Affected browsers: IE

## 2) Expected behavior
The String values should be shown correctly when using f:selectItems.

...

## 3) Actual behavior
![image](https://user-images.githubusercontent.com/15189434/50238571-bf85cd80-038d-11e9-89ba-a02ac013f066.png)

..

## 4) Steps to reproduce

Tested in IE : Value shown is 5.12345678901235e+15

![image](https://user-images.githubusercontent.com/15189434/50238777-49359b00-038e-11e9-8a9d-439b4168ae16.png)

Select a value from p:selectOneMenu , the value seems to be consider as number.

https://github.com/ravihariharan/primefaces-test-issue1
.. 

## 5) Sample XHTML
```
<p:selectOneMenu id="console4" value="#{testViewCdi.console2}">
		<f:selectItem itemLabel="Select One" itemValue="" />
		<f:selectItems value="#{testViewCdi.cars}" var="def"
			itemLabel="#{def.value}" itemValue="#{def.label}" />
</p:selectOneMenu>
```
..

## 6) Sample bean
```
cars = new ArrayList<SelectItem>();
        cars.add(new SelectItem("5123456789012345", "5123456789012345"));
        cars.add(new SelectItem("5123456789012346", "5123456789012346"));
        cars.add(new SelectItem("5123456789012347", "5123456789012347"));
```
..

**Comment by ravihariharan** [comment]
the only workaround i found was using labelTemplate="{0}". 
i tried to debug forms.selectonemenu.js , but could not find why it has issue only with IE 11.
Chrome , FireFox , Edge all work fine without the  labelTemplate="{0}".

@tandraschko / @Rapster  / @melloware  can you have a second look at the selectItem in forms.selectonemenu.js of what could cause the issue with IE 11.

**Comment by melloware** [comment]
@ravihariharan let me investigate.  Thanks for the sample project.

**Comment by melloware** [comment]
PR Submitted.  Just a one line fix.  By making it a String IE or JQuery won't try and convert it t scientifc notation. https://github.com/primefaces/primefaces/pull/4342

**Comment by tandraschko** [comment]
THanks!
