### ISSUE TITLE
defaultCommand skips client-side validation

### ISSUE THREAD

**Issue by rapito** [primefaces/primefaces#434]
Client-side validation is being bypassed when using the _enter_ key.
## example code

```
<h:form id="form-number">
    <h:outputText value="Number: "/>
    <p:inputMask id="input-number" value="#{MB.number}" mask="9999999999">
        <f:validateLength minimum="10" maximum="10"/>
    </p:inputMask>

    <p:commandButton value="Reset">
        <p:ajax update="@form" listener="#{MB.clean}"/>
    </p:commandButton>
    <p:commandButton id="btn-save" value="Save" action="#{MB.save}" update="@form"/>
    <p:defaultCommand target="btn-save"/>
</h:form>
```
## behaviour
- when _clicking_ on the `save button` the client-side validations are executed. 
- after focusing the inputMask and presssing enter, server-side method executes even though the input is empty or the length requirement isn't met.

**Comment by melloware** [comment]
Cannot reproduce.  Added showcase example:https://github.com/primefaces/primefaces-showcase/commit/fe5907335ad60855c2184509b2180e4c2dafb0c9
