### ISSUE TITLE
Datatable: RowEdit validation with RowGroup

### ISSUE THREAD

**Issue by src-skyworld** [primefaces/primefaces#4340]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? No Version? 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Unsure
- Application server + version: Tomcat/8.5.27, JVM/1.8.0_161-b12
- Affected browsers: Chrome

## 2) Expected behavior
Clicking row-edit check for the last row should apply `.ui-state-error` to that row.

## 3) Actual behavior
Clicking row-edit check for the last row applies `.ui-state-error` 2 rows (number of row groups before this row) above the last row.

## 4) Steps to reproduce
Click row-edit check for the last row.

![image](https://user-images.githubusercontent.com/23561376/50247169-26fb4780-03a5-11e9-9d8f-4b837eb609c9.png)

## 5) Sample XHTML
```xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" 
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
<h:head />
<h:body>
	<h:form>
		<c:set var='dataSet' value="#{[[1,1],[1,2],[1,3],[2,1],[2,2],[2,null]]}"/>

		<p:dataTable var="data" value="#{dataSet}" tableStyle="display:inline" sortBy="#{data[0]}" editable="true" editingRow="true" expandableRowGroups="true" >

			<p:headerRow>
				<p:column colspan="2">
					<h:outputText value="#{data[0]}" />
				</p:column>
			</p:headerRow>

			<p:column>
				<p:inputNumber value="#{data[1]}" required="true" />
			</p:column>

			<p:column>
				<p:rowEditor />
			</p:column>
		</p:dataTable>
	</h:form>
</h:body>
</html>
```

## Other Notes
`getRowMeta`:
(https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L3217)
`invalidateRow`:
(https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2852)

`getRowMeta` and `invalidateRow` don't use the same method of row indexing. 
`getRowMeta` accounts for `rowGroups` looking at `data-ri`.
`invalidateRow` looks at all rows with `tbody.children('tr')`

**Comment by melloware** [comment]
@tear-gas Interested and trying to fix it and submitting a PR?
