### ISSUE TITLE
Ajax: requires form

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4341]
## 1) Environment
- PrimeFaces version:
- Works on 6.2
- Does not work on 6.3-SNAPSHOT (2018/12/20)
- Application server + version: Wildfly 11
- Affected browsers: does not matter

## 2) Expected behavior
Example is rendered with PF 6.3-SNAPSHOT, as it is with PF 6.2.

## 3) Actual behavior
Exception is thrown:
```
Caused by: javax.faces.FacesException: Component 'dialog' must be inside a form or reference a form via its form attribute.
	at org.primefaces.util.AjaxRequestBuilder.form(AjaxRequestBuilder.java:75)
	at org.primefaces.util.AjaxRequestBuilder.form(AjaxRequestBuilder.java:93)
	at org.primefaces.behavior.ajax.AjaxBehaviorRenderer.getScript(AjaxBehaviorRenderer.java:96)
	at javax.faces.component.behavior.ClientBehaviorBase.getScript(ClientBehaviorBase.java:103)
	at org.primefaces.renderkit.CoreRenderer.encodeClientBehaviors(CoreRenderer.java:564)
	at org.primefaces.component.dialog.DialogRenderer.encodeScript(DialogRenderer.java:81)
	at org.primefaces.component.dialog.DialogRenderer.encodeEnd(DialogRenderer.java:47)
```
This is caused by the changes of commit c7f8c9539ff07ce291a7f6e9f24fe4ad33431b79 at
https://github.com/primefaces/primefaces/blob/6e5f177d4a35b817c4cdadfbd41b04acc23fe3c0/src/main/java/org/primefaces/util/AjaxRequestBuilder.java#L67-L90
by @tandraschko.

I always thought that a dialog does not need to be in a form. Having a form inside the dialog is enough. 
The same is true for the commandButton in my example. With PF6.2 it does not need to be inside a form.

## 4) Steps to reproduce
Run the example with current version of PF6.3-SNAPSHOT

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="formButton">
            <p:commandButton id="buttonShow"
                             onclick="PF('dialogVar').show()"
                             value="Open Dialog"/>
        </h:form>
        <p:dialog id="dialog"
                  widgetVar="dialogVar"
                  closable="true" >
            <p:ajax event="close" onstart="alert('Closing!!!');" />

            <h:form id="formDialog">
                <p:commandButton id="buttonHide"
                                 onclick="PF('dialogVar').hide()"
                                 value="Hide Dialog"/>
            </h:form>
        </p:dialog>

    </h:body>
</html>
```

## 6) Sample bean
not necessary

**Comment by tandraschko** [comment]
Actually it's by design.
If you use a ajax event on dialog, a form is required to send the request.

We did (and still do!) a fallback on the first form in the DOM.

**Comment by OBreidenbach** [comment]
But if you do a fallback to the first form, why do I get an exception?

**Comment by tandraschko** [comment]
because the fallback is IMO just for edge-cases and done in JS.
Also it could be wrong on portlets.

**Comment by tandraschko** [comment]
We could probably switch to a warning instead of the exception - but that could be a real issue for some cases, therefore just ignore it, isn't a good idea.

**Comment by OBreidenbach** [comment]
OK, defining the form to use at the AjaxBehavior solves the problem.
```
<p:ajax event="close" onstart="alert('Closing!!!');" form="formDialog" />
```
But that means, I have to change that at all places in my application.

**Comment by tandraschko** [comment]
Yep.
maybe a warning log is enough. Thats also what the JSF impls do.

**Comment by tandraschko** [comment]
merry christmas ;)
