### ISSUE TITLE
Scrollable Datatable: height should be adaptative

### ISSUE THREAD

**Issue by sergi-mm** [primefaces/primefaces#4357]
Datatable scrollable body height is fixed and should be adaptative when using `scrollable=true` and `scrollHeight=X`. As it is now, when there are few rows to display, table body occupies all assigned height with nothing to show. 

Changing the style property "height" to "max-height" will fix this issue. I will attatch a pull request for this.

**Comment by sergi-mm** [comment]
Added pull request #4358

**Comment by melloware** [comment]
@sergi-mm thanks for the PR. Can you review this item as well: https://github.com/primefaces/primefaces/issues/250
