### ISSUE TITLE
New Component: DatePicker

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4360]
DatePicker is an input component to select a date, such as Calendar component. It is more flexible and easily customizable. Thus, new features can be added easily by us.

Some features;
- Range Selection
- Multiple Selection
- Month Picker
- Touch UI
- Date Template
etc.

**Comment by cnsgithub** [comment]
@mertsincan This new component seems to be a huge improvement, thank you! 

I just left a few commit comments here: https://github.com/primefaces/primefaces/commit/35d9ee93463f693c60d93790b7144e896a84a979

**Comment by mertsincan** [comment]
Thanks a lot for your tests and comments, @cnsgithub.

**Comment by martin654** [comment]
@mertsincan Is the old calenar going to be deprecated in future?

**Comment by mertsincan** [comment]
No ;)
