### ISSUE TITLE
datePicker: lack of user input validation when using disabled dates/days

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#4362]
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
Disabled dates/days must be validated on backend side.

## 3) Actual behavior
It's possible to bypass client side input validation and apply unallowed dates to the model.

## 4) Steps to reproduce
1. Go to http://localhost:8080/showcase/ui/input/datePicker.xhtml.
2. Manually set a disabled date, e.g. in dev console: `$('#form\\:disabledDD_input').val('1/8/19')`.
![image](https://user-images.githubusercontent.com/13161711/50765943-d24a3e80-1277-11e9-8450-1e1851e28d39.png)
3. Press the submit button.
4. See the unallowed date being applied:
![image](https://user-images.githubusercontent.com/13161711/50765898-a464fa00-1277-11e9-9a31-00ad5168dce9.png)

**Comment by mertsincan** [comment]
Hi @tandraschko and @cnsgithub,

What do you think about my fix?

**Comment by cnsgithub** [comment]
Hi @mertsincan,

Thanks for your quick response. I've not yet checked it in detail, but it looks reasonable. (Now I can remember again why I never liked the old `java.util.Date` API. 😉 But Java 8 is foreseeable. 😉)

Just one thing, did you consider the timezone stuff?

**Comment by mertsincan** [comment]
> Just one thing, did you consider the timezone stuff?
- Fixed now ;)

**Comment by cnsgithub** [comment]
@mertsincan Just tried to re-check this issue again after applying your fix and wondered if the semantics has changed?

Because in contrast to the screenshot above, _1/8/19_ is no longer disabled and afaik there was no change to the showcase:

![image](https://user-images.githubusercontent.com/13161711/50901239-dca33e80-1417-11e9-86fa-2e9db28e8aec.png)

**Comment by cnsgithub** [comment]
@mertsincan Just tried to recheck this issue after applying your fix and wondered if semantics has changed?

The dates that are initially disabled differ now from those in the screenshot above, although there was no change to the showcase afaik:

![image](https://user-images.githubusercontent.com/13161711/50901526-c0ec6800-1418-11e9-9377-76b39f79ca42.png)

**Comment by cnsgithub** [comment]
Backend side validation seems to be consistent with dates disabled in the screenshot. :+1:
