### ISSUE TITLE
datePicker: not working in IE 11 at all

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#4365]
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
`datePicker` should work in IE 11 as well, shouldn't it?

## 3) Actual behavior
A syntax error is thrown (just click at the input fields, some will open the picker, others won't).

![image](https://user-images.githubusercontent.com/13161711/50768263-14777e00-1280-11e9-83d8-c4c92b1a46b7.png)

The problem is the use of the arrow function in `0-datepicker.js`, line 691. Unfortunately, IE 11 doesn't support arrow functions, see https://caniuse.com/#search=arrow%20function.

## 4) Steps to reproduce
http://localhost:8080/showcase/ui/input/datePicker.xhtml

**Comment by mertsincan** [comment]
Thanks @cnsgithub ;)
