### ISSUE TITLE
Diagram: at connectionChange event.getNewTargetEndPoint() is always null

### ISSUE THREAD

**Issue by ruzsaz** [primefaces/primefaces#4367]
The problem should be at /master/src/main/java/org/primefaces/component/diagram/Diagram.java
line 125:
`EndPoint newTargetEndPoint = model.findEndPoint(newTargetElement, params.get(clientId + "_targetEndPointId"));`

`"_targetEndPointId"` should be `"_newTargetEndPointId"`

**Comment by tandraschko** [comment]
Please provide a PR and test it

**Comment by ruzsaz** [comment]
I'm sorry, but I'm not a primefaces developer, just got that nullpointerexception, and looked for the sources to find the problem.

In short: I'd be happy to made that PR and test, but I don't know how...

**Comment by melloware** [comment]
@tandraschko I verified @ruzsaz is correct and I submitted a PR.

**Comment by ruzsaz** [comment]
Thx

**Comment by melloware** [comment]
Duplicate of #3485

**Comment by melloware** [comment]
Also duplicate of https://github.com/primefaces/primefaces/issues/817  Looks like this issue has been out there for a while!
