### ISSUE TITLE
selectOneMenu: filter="true" - filter field clears but items still filtered after selection

### ISSUE THREAD

**Issue by jdesmet** [primefaces/primefaces#4372]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Not tested on > 6.2
- Does it work on the newest sources in GitHub? Not tested
- Application server + version: TomEE
- Affected browsers: Safari, other untested

## 2) Actual behavior

When using <p:selectOneMenu filter="true" filterMatchMode="startsWith">,

1. Open up drop-down
2. Start typing in the filter field
3. Select a menu option
4. Open up drop-down again with the intent to select something different

Issue now is that the filter field is cleared, but the menu items are still filtered. This appears to confuse my users. 

## 3) Expected behavior

Either following option should be acceptable:

1. The previously used filter is still populated, so the user can manually clear it
2. or, the user is again presented with the full selection options, and a cleared filter field.

Either option will work as filter-field, and offered menu options will always match.

**Comment by melloware** [comment]
Can you try it on the Showcase https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

The Advanced dropdown is filterable with StartsWith. If I type "Om" it filters for Omega.  If I select it and then clicked the dropdown again the filter remains "Om" with Omega filtered.  Are you saying when you select an item your filter is getting cleared?  

Can you fork or download this Test app and create a small reproducible example for us?  https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment]
@jdesmet any update on this?

**Comment by jdesmet** [comment]
I would be glad to comply. I have logged it for full measure (was easy enough), but need to find the time to do all the testing. My apologies for the delay.

**Comment by melloware** [comment]
@jdesmet Any update?
