### ISSUE TITLE
menuButton: add support for submenus

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#4374]
PrimeFaces' `<p:menubar>` component supports nested `<p:submenu>`s to group menu-items into sub-menus. This grouping is currently not supported for `<p:menuButton>`. `<p:submenu>`s inside a menuButton is silently ignored. It would be nice to also have sub-menu support in menu-buttons.

## 1) Environment

PrimeFaces 6.2

**Comment by tandraschko** [comment]
Feel free to implement it and provide a PR.
Or sponsor it via PrimeFaces PRO.
