### ISSUE TITLE
SEO paginator - GET / next / prev support

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#4376]
Pagination could be a built-in PrimeFaces feature but its complex to work in all cases. Currently it uses AJAX navigation buttons, so pagination data is not indexed by default. 

SEO friendly pagination basically requires GET navigation buttons / links. Those can be normal links in paginator or specific _next / prev_ links in head section.

Google info: https://support.google.com/webmasters/answer/1663744

# Options

For SEO friendly pagination there are two options:

1. AJAX paginatior and add_next / prev_ links in head _section_
2. use get links / buttons for paginator without AJAX _(no next / prev links required since GET links are indexable by nature)_

# Example

In our shop we use the _next_ and _prev_ links in _head_ section for any data listing page to provide SEO friendly GET support to directly jump to a certain page. We rewrite URL's to SEO friendly clean versions using Java-EE library http://www.ocpsoft.org/rewrite/.

This example shows that a lot of markup is required to make it work.

## Products category page

-  **live:** https://www.getraenkelieferant-duisburg.de/c/Limonade/page/2
- **clean-uri:** _/c/Limonade/page/2_
- **uri:**  _/products.xhtml?category=Lemonade&page=2

## Head markup

Render _next / prev_ links.

	
	<ui:fragment rendered="#{cc.attrs.bean.paginationData.hasNext()}">
				
		
		
		<o:outputFormat var="varLinkHrefNext" value="#{view.viewId}" converter="myPackage.BookmarkableUrlConverter">
			<o:param name="category" value="#{cc.attrs.beancategory}" converter="#{bean.categoryConverter}" disable="#{cc.attrs.bean.category eq null}"/>

			
			<o:param name="page" value="#{cc.attrs.bean.paginationData.index + 1}"/>

			
		</o:outputFormat>
					
		
		<link rel="next" href="#{varLinkHrefNext}"/>
					
	</ui:fragment>

### Page markup

Pass pagination _viewParam_ to bean and use them in _p:dataGrid_

	<f:metadata>
		<o:viewParam name="category" value="#{bean.category}" 
			converter="#{bean.categoryConverter}" />
		<f:viewParam name="page" value="#{bean.paginationData.index}" />
		<f:viewParam name="pageSize" value="#{bean.paginationData.pageSize}" />
	<f:metadata>

	
	<p:dataGrid value="#{cc.attrs.bean.dataModel}" 
		columns="2" rows="#{bean.paginationData.pageSize}" lazy="true"
		paginator="true" first="#{bean.paginationData.getItemIndex()}">

	</p:dataGrid>

# Idea

Passing the paginator URI using placeholders could enable option 1 or 2 using an attribute like _paginatorGET_.

1. false - uses AJAX buttons and adds _next / prev_ links to head
2. true - use GET buttons to reload page with new pagination params

	
	<p:dataGrid value="#{cc.attrs.bean.dataModel}" 
		columns="2" rows="#{bean.paginationData.pageSize}" lazy="true"
		paginator="true" first="#{bean.paginationData.getItemIndex()}"
		paginatorUri="/c/Limonade/page/{page}?pageSize={pageSize}" paginatorGET="false">

	</p:dataGrid>

**Comment by tandraschko** [comment]
Please don't create such batch tickets and split it up. Menu has absolutely no relation to menus. If someone would work on it, he would never implement it batch on all those components. Maybe just on related components (like DataGrid and DataTable as the paginator is similar).
