### ISSUE TITLE
[Documentation] fileUpload: virus scan

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#4377]
- new attribute `p:fileUpload performVirusScan="true"`
- see https://github.com/primefaces/primefaces/pull/4259, https://github.com/primefaces/primefaces/issues/4256

**Comment by cnsgithub** [comment]
@Rapster Could you please add the 6.3 milestone and assign it to @cagataycivici?

**Comment by tandraschko** [comment]
@cnsgithub would you like to move your wiki page about secure upload to the docs?

**Comment by cnsgithub** [comment]
@tandraschko We are still awaiting for PrimeTek to join the documentation discussion [here](https://github.com/primefaces/primefaces/pull/4334). Please don't get me wrong, but I don't want to waste time as long as there is no official roadmap for documentation.

**Comment by tandraschko** [comment]
AFAIK the decision was made by Cagatay and i can't change it. I think thats the official roadmap for now.

I'm not 100% happy as rapster invested many time and i know myself how that feels.
But its still much better as the PDF as we can improve the docu now.

**Comment by cnsgithub** [comment]
Convinced. Where do you want me to move the wiki?

**Comment by tandraschko** [comment]
I would add it as sub-sections to the FileUpload.md.
Mert said that the guide.md is generated from the single *.md files via:
```npm i docsify-cli -g```
```.../primefaces/docs/7_0_0> docsify serve```

**Comment by tandraschko** [comment]
ok even better
guide.md is not required, i will delete it
if we change something, github auto deploys it

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/4665

**Comment by tandraschko** [comment]
Thanks
