### ISSUE TITLE
datePicker: not working in IE 11 at all - reloaded

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#4378]
## 1) Environment
- PrimeFaces version: 6.3-snapshot
- Affected browsers: IE 11

## 2) Expected behavior
`p:datePicker` should work in IE 11 as well.

## 3) Actual behavior
A syntax error is thrown:

![image](https://user-images.githubusercontent.com/13161711/50902412-1a559680-141b-11e9-9c77-74f3a8593005.png)

Probably colon and `function `keyword are missing for definition of `renderDateCellContent`:

![image](https://user-images.githubusercontent.com/13161711/50902504-512bac80-141b-11e9-9353-f875a3747eb5.png)

## 4) Steps to reproduce
Open http://localhost:8080/showcase/ui/input/datePicker.xhtml in IE 11.

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/4379

**Comment by mertsincan** [comment]
Thanks a lot for the PR ;)
