### ISSUE TITLE
[perf] DefaultScheduleModule#addEvent() using UUID.randomUUID().toString()

### ISSUE THREAD

**Issue by smithh032772** [primefaces/primefaces#439]
DefaultScheduleModule#addEvent() is using UUID.randomUUID().toString() to populate ScheduleEvent.id. See below.

```
public void addEvent(ScheduleEvent event) {
    event.setId(UUID.randomUUID().toString());

    events.add(event);
}
```

This presents a performance issue when there are many events added to the schedule component. In my app, I have Previous/Next buttons which allows enduser to navigate to previous/next month, and it is very likely that there are 100+ (or more) events per month. As you can see (attached), there is a performance concern.

I think I may populate ScheduleEvent.id, myself, via an approach similar to recommended code at URL below:

http://stackoverflow.com/a/16518915/933054

![20150615_perfaddeventuuid1](https://cloud.githubusercontent.com/assets/2723055/8167342/a5a1e572-136b-11e5-812e-f4f95db4c05f.png)

![20150615_perfaddeventuuid2](https://cloud.githubusercontent.com/assets/2723055/8167348/b2fa8d32-136b-11e5-80a6-6dd3425d4bf7.png)

**Comment by cagataycivici** [comment]
Would be better than if you create a custom implementation of ScheduleModel using your own id generator instead of DefaultScheduleModel and contribute one :)

**Comment by smithh032772** [comment]
Okay. I did as I mentioned earlier (populate id with recommended code at URL, above), and DefaultScheduleModule#addEvent() no longer shows up in jvisualvm (Sampler).
