### ISSUE TITLE
Autocomplete: Ampersand in suggestions returns escaped markup

### ISSUE THREAD

**Issue by SaschaPro** [primefaces/primefaces#4395]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? Yes - 6.2
- Does it work on the newest sources in GitHub? Not tested
- Application server + version: JBoss EAP 7.* - tested on multiple versions
- Affected browsers: Chrome 71.0.3578.98

## 2) Expected behavior

The suggestions of the autocomplete component should not display nor highlight the escaped ampersand.

## 3) Actual behavior

The suggestions of the autocomplete component display an escaped ampersand, if the item matching the search query contains any character in the escaped ampersand (&amp;).
See Screenshot.
![primefaces_github](https://user-images.githubusercontent.com/35800594/50974051-a256a180-14ea-11e9-9903-df8cf0f66845.PNG)

## 4) Steps to reproduce

The search query from the autocomplete component must contain any character in the escaped ampersand (&amp;). e.g. 'M' in the sample provided.

## 5) Sample XHTML

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Web Client Test</title>
    </h:head>
    <h:body>
        <h:form>
            <p:outputLabel value="Simple:" for="acSimple" />
            <p:autoComplete id="acSimple" value="#{mainController.txt1}" completeMethod="#{mainController.completeText}" />
        </h:form>
    </h:body>
</html>
```

## 6) Sample bean

```
public class MainController implements Serializable {
    private List<String> list;
    private String txt1;

    @PostConstruct
    public void init() {
        list = new ArrayList<>();
        list.add("Metro & Co.");
        list.add("McKesson");
        list.add("Morgan Stanley");
        list.add("Merrill Lynch");
        list.add("Marathon Oil");
    }

    public List<String> completeText(final String query) {
        return list.stream()
                .filter(item -> StringUtils.containsIgnoreCase(item, query))
                .collect(Collectors.toList());
    }

    public String getTxt1() {
        return txt1;
    }

    public void setTxt1(final String txt1) {
        this.txt1 = txt1;
    }
}
```
[web-client-test.zip](https://github.com/primefaces/primefaces/files/2745664/web-client-test.zip)

Related issue:
https://github.com/primefaces/primefaces/issues/1385

**Comment by melloware** [comment]
Well I just tested this and its working fine. Attached is my sample test case: 
[pf-4395.zip](https://github.com/primefaces/primefaces/files/2792833/pf-4395.zip)

Run it with "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

Screenshot: 
![image](https://user-images.githubusercontent.com/4399574/51696483-9df2b400-1fd3-11e9-87e0-6e0d549584e8.png)

**Comment by SaschaPro** [comment]
@melloware
I think there is a mistake in your example.
The bug only occurs if the search query from the autocomplete component matches the characters in the escaped ampersand (& amp;).
In the sample I provided the 'M' matches the 'm' in '& amp;'.
It works fine if the search query is 'Mo', because that does not match the characters in the escaped ampersand.
Therefor I think your example will not work, because your search query does not match with the escaped ampersand.
In the zip archive I provided there is an compiled version of my code in the folder 'build\libs\', maybe you could try that.
Also there is no highlighting in your example. I don't know if that has anything to do with the bug.

**Comment by melloware** [comment]
OK that was the hint I needed. I submitted a PR to fix it.

![image](https://user-images.githubusercontent.com/4399574/51838756-4b680f00-22d5-11e9-8557-7b02e0cb0e9f.png)
