### ISSUE TITLE
ImageSwitch resource imageswitch.css does not exist.

### ISSUE THREAD

**Issue by RayfenWindspear** [primefaces/primefaces#44]
Wherever a Primefaces ImageSwitch is used, the page reports that imageswtich.css(.jsf) could not be loaded. Looking through the source shows that this file doesn't even exist at all. It should be in primefaces/src/main/resources/META-INF/resources/primefaces/imageswitch/ but it doesn't exist. Other components such as ImageCropper have css files of their own, but the ImageSwitch appears to be missing this.

It should be created or, if it is not meant to exist, it should be removed as a requirement in the component itself.

**Comment by cagataycivici** [comment]
I don't see a request to imageswitch.css using live demo.

http://www.primefaces.org/showcase/ui/multimedia/switch.xhtml

Why in your case your page requires imageswitch.css, do you add it dynamically with an ajax update to the component tree?

**Comment by RayfenWindspear** [comment]
Yes, it is added programmatically in java code, though it doesn't have an ajax update. At least not one that we added.

**Comment by cagataycivici** [comment]
Ok, we'll add an empty one as a workaround.
