### ISSUE TITLE
PickList: Throws NullPointerException when escape parameter is omitted

### ISSUE THREAD

**Issue by fabermundi** [primefaces/primefaces#4413]
## 1) Environment
- PrimeFaces version: 6.2.14
- Does it work on the newest released PrimeFaces version? No

## 2) Expected behavior
Using pickList without the "escape" parameter should not throw an NullPointerException.

## 3) Actual behavior
An NullPointerException is thrown when page is loaded. Adding escape = "false" fixes the issue.

## 4) Steps to reproduce
Load the following sample (from the primefaces showcase).

## 5) Sample XHTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Test Picklist</title>
    </h:head>
    <h:body>
        <h:form>
            <p:pickList id="pickList" value="#{testBean.cities}" var="cities" itemLabel="#{cities}" itemValue="#{cities}" escape="false" />
        </h:form>
    </h:body>
</html>

## 6) Sample bean
package lu.etat.pch.docroom.ejb.controllers;

import org.primefaces.model.DualListModel;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Named
@SessionScoped
public class TestBean implements Serializable {
    private static final long serialVersionUID = 4904613979704812025L;

    private DualListModel<String> cities;

    @PostConstruct
    public void init() {
        //Cities
        List<String> citiesSource = new ArrayList<>();
        List<String> citiesTarget = new ArrayList<>();

        citiesSource.add("San Francisco");
        citiesSource.add("London");
        citiesSource.add("Paris");
        citiesSource.add("Istanbul");
        citiesSource.add("Berlin");
        citiesSource.add("Barcelona");
        citiesSource.add("Rome");

        cities = new DualListModel<>(citiesSource, citiesTarget);
    }

    public DualListModel<String> getCities() {
        return cities;
    }

    public void setCities(DualListModel<String> cities) {
        this.cities = cities;
    }
}

**Comment by tandraschko** [comment]
@mertsincan missing defaultValue in elite xml's?

**Comment by mertsincan** [comment]
Yes @tandraschko ;) Fixed for 6.2.15 now. Default value is true. @fabermundi can use escape="true" for now.
