### ISSUE TITLE
DataExporter: Enhance DataExporter to support Other Data Components

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4414]
PrimeFaces version: 6.2
Does it work on the newest released PrimeFaces version? Version? NA
Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) NA
Application server + version: NA
Affected browsers: NA

Once DataExporter: Support custom Export class #4397 is in place we would be able to support other Data Components.

Primefaces by default provide out of box support for Excel , CVS , XML for DataTable.

A minor code refactor will allow user to support custom implementation of export for any component.  
The below is suggested approach considering TreeTable.

1.  Refactor and Rename Exporter to DataTableExporter
2. Create a new interface called Exporter

```
public interface Exporter<TABLE> {
    void export(FacesContext facesContext, TABLE table, String outputFileName, boolean pageOnly, boolean selectionOnly,
           String encodingType, MethodExpression preProcessor, MethodExpression postProcessor, ExporterOptions options,
           MethodExpression onTableRender) throws IOException;

    void export(FacesContext facesContext, List<String> clientIds, String outputFileName, boolean pageOnly,
            boolean selectionOnly, String encodingType, MethodExpression preProcessor, MethodExpression postProcessor,
            ExporterOptions options, MethodExpression onTableRender) throws IOException;

    void export(FacesContext facesContext, String outputFileName, List<TABLE> tables, boolean pageOnly,
            boolean selectionOnly, String encodingType, MethodExpression preProcessor, MethodExpression postProcessor,
            ExporterOptions options, MethodExpression onTableRender) throws IOException;

    String getSheetName(FacesContext context, TABLE table);
}
```

3. DataTableExporter implements Exporter

`public abstract class DataTableExporter implements Exporter<DataTable>`

4. A developer could then create a TreeTableExporter  Exporter<TreeTable>.

`public abstract class TreeTableExporter implements Exporter<TreeTable>`

**Comment by Rapster** [comment]
> 4. A developer could then create a TreeTableExporter Exporter.

But how the user would reuse it? So far `ExporterFactory#getExporterForType` is the decision maker

**Comment by ravihariharan** [comment]
![image](https://user-images.githubusercontent.com/15189434/60360475-cf6c1300-99a9-11e9-90a9-685378e6366f.png)

**Comment by Rapster** [comment]
First, I think with your PR, this test no longer makes sense, but we should be able to test if the component is supported by one of the defined exporters. Which brings us to this:
```java
if (customExporterInstance == null) {
    return ExporterFactory.getExporterForType(exportAs, exporterOptions);
}
```

As mentionned earlier, this is trickiest part in this PR in my opinion. As you're giving the possibility to add more exporters, these new exporters have to be registered somehow so they can be used right? Otherwise I don't see how you can use them (and creating a new tag handler for that is definitely not a option, as far as I understand...) the static `ExporterFactory` shows his limitations in that sense, you basically can't override it

I think we need something that I've been thinking for quite some time now: a service locator.

Keep in mind, that my objective is to be able to reuse these exporters by doing so:

```xml
<p:dataExporter type="xls" target="tbl" fileName="cars" pageOnly="true"/>
```

Meaning, it shoud be transparent for the user 😉

**Comment by Rapster** [comment]
Tell me if I'm wrong but you're planning to use your custom exporter like this right:
```xml
<p:dataExporter type="xls" target="tbl" fileName="cars" pageOnly="true" customExporter="#{sthExporter}" />
```

**Comment by ravihariharan** [comment]
@Rapster  Yes

e.g. if we want to export a quickbooks format then we could do something like 
<p:dataExporter type="quickbooks" customExporter="#{quickbooksExporter}" />

 type="quickbooks" is only added for readability

**Comment by ravihariharan** [comment]
The initial scope was to ensure 
1) Existing DataTable will continue to support the already defined format (cvs,xls , xlsx, PDF). 
2) For cases where we need custom format e.g.  say quickbook , quicken , text a developer could provide a customExporter.

For components that do not support default export like TreeTable , we could still use the customExporter but it needed the refactor for a interface that was not specific to DataTable.

My PR scope was not to cover a default exported for TreeTable , but only to provide a interface that could be leveraged to write custom export.
