### ISSUE TITLE
DatePicker: calendar-popup does not work with iOS 12.1.1 (Safari) and Android 8 (Chrome 71)

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#4417]
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT, 7.0 RC1
- Affected browsers: 
Safari (iOS 12.1.1); tested with iPad Pro 10.5"
Chrome 71 (Android 8.0); tested with Huawei P10 lite

## 2) Expected behavior
https://www.primefaces.org/showcase/ui/input/datePicker.xhtml should work similar to https://www.primefaces.org/showcase/ui/input/calendar.xhtml

DatePicker does not open calendar-popup when used on Safari (iOS) or Chrome (Android).

## 3) Actual behavior
![datepicker_ios_12_1_1](https://user-images.githubusercontent.com/10461942/51083235-d0202e00-1716-11e9-8b28-64bf65e2a47f.png)
![calendar_ios_12_1_1](https://user-images.githubusercontent.com/10461942/51083236-d0b8c480-1716-11e9-8570-3631d282ead5.png)

https://www.primefaces.org/primeng/#/calendar work´s fine with iOS 12.1.1.
![primeng_calendar_ios_12_1_1](https://user-images.githubusercontent.com/10461942/51083255-402eb400-1717-11e9-8971-6a78bdba427b.png)

As far as i understand Primefaces - DatePicker replicates PrimeNG Calendar.

## 4) Steps to reproduce
Open Showcase with iOS - Browser

**Comment by markusg80** [comment]
For me same issue

**Comment by mertsincan** [comment]
Hi @christophs78 and @markusg80,

Could you please try this fix?

**Comment by christophs78** [comment]
@mertsincan - the official showcase had not been updated yet?
I will recheck after it is updated. (I have no environment where i am able to test the current github-Snapshot easily on my iPad.)

**Comment by markusg80** [comment]
For me same situation

**Comment by christophs78** [comment]
The issue still persists with PF 7.0 RC1. (official showcase)
I´m able to reproduce this issue with iOS 12.1.1 (Safari) and on Android (8.0) with Chrome 71 (Huawei P10 lite).
![screenshot_20190116-174853](https://user-images.githubusercontent.com/10461942/51264828-a89bc080-19b7-11e9-973d-f0b2de9c4313.jpg)

**Comment by christophs78** [comment]
@mertsincan - I invested some time to remote-debug chrome 71 on my android-phone.
Console show´s following error when i put the focus into the "Popup" - input-field:
![grafik](https://user-images.githubusercontent.com/10461942/51339977-13b7c680-1a8e-11e9-8312-3a1a81a3bc9b.png)
Can we please reopen this issue?

**Comment by mertsincan** [comment]
Good catch, @christophs78 ;) Fixed now.

**Comment by mertsincan** [comment]
Please try again; https://www.primefaces.org/showcase/ui/input/datePicker.xhtml

**Comment by christophs78** [comment]
Well done! Datepicker now works on iOS and Android/Chrome.

**Comment by mertsincan** [comment]
Thanks to you ;)

**Comment by markusg80** [comment]
Now it looks nice! Thank you
