### ISSUE TITLE
DataTable: rowSelectMode="none" ContextMenu is selecting row and checkbox

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#4422]
I have a dataTable with multiple selection and atrribute rowSelectMode="checkbox" and contextMenu. So I want to select rows only with checkbox. But in this combination, I get row selected using RMB together with contextMenu

1) Environment
- PrimeFaces version: **6.2.14**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Application server + version: **WLS 12.1.3.0.0**
- Affected browsers: **All, ie. FirefoX, IE, Chrome**

2) Expected behavior

**Checkbox should stay unchecked**

3) Actual behavior

**Ceckbox is being checked.**

4) Steps to reproduce

**Create dataTable with rowSelectMode="checkbox" and selectionMode set to multiple and add contextMenu to it. Right click on a row.**

**Comment by majkers** [comment]
Moreover. It seems that RMB click removes selection and highlight from other rows when clicked row is not selected!

**Comment by melloware** [comment]
Agreed.  Please review my PR.  now in Checkbox mode it just performs the selection of that row and breaks out of other logic.

**Comment by majkers** [comment]
But I think that You changed onRowDblclick not onRowRightClick function. Am I right?

**Comment by majkers** [comment]
Actually I am sure whether a selection mode check that is implemented in onRowClick function is better. WIll it work in New mode?

**Comment by melloware** [comment]
No the fix is in onRightClick it basically performs the focus of the row but then short circuits out if its a checkbox and does not perform the rest like selecting the row and unselecting all other values etc.

```javascript
onRowRightClick: function(event, rowElement, cmSelMode) {
        var row = $(rowElement),
        rowMeta = this.getRowMeta(row),
        selected = row.hasClass('ui-state-highlight');

        this.assignFocusedRow(row);
        
        // GitHub #4422
        if (cmSelMode === 'checkbox') {
            this.clearTextSelection();
            return;
        }

        
        if(cmSelMode === 'single' || !selected) {
            this.unselectAllRows();
        }

        this.selectRow(row, true);

        this.fireRowSelectEvent(rowMeta.key, 'contextMenu');

        this.clearTextSelection();
    },
```

**Comment by melloware** [comment]
actually looking at it more i need to tweak it

**Comment by melloware** [comment]
I think this is more correct.
```javascript
    onRowRightClick: function(event, rowElement, cmSelMode) {
        var row = $(rowElement),
        rowMeta = this.getRowMeta(row),
        selected = row.hasClass('ui-state-highlight');

        this.assignFocusedRow(row);
        
        // GitHub #4422
        if (cmSelMode !== 'checkbox') {
            if(cmSelMode === 'single' || !selected) {
                this.unselectAllRows();
            }

            this.selectRow(row, true);
        }
        
        this.fireRowSelectEvent(rowMeta.key, 'contextMenu');
        this.clearTextSelection();
    }
```

**Comment by majkers** [comment]
It is not working.
`if (cmSelMode !== 'checkbox')` cmSelMode has value 'multiple'. I think You should use `this.cfg.rowSelectMode`. And remember and please have in mind other selectione modes like 'new' and 'add'. I would also add highlighting row with `this.highlightRow(row);` if in 'checkbox' mode.

**Comment by melloware** [comment]
Yep its definitely more complicated than 1 scenario.   Closing my PR.

**Comment by majkers** [comment]
Still not working as expected

**Comment by majkers** [comment]
I submitted this issue when rowSelectMode had values new, add and checkbox. Since version 12, option checkbox ws renamed to none according to this:
https://primefaces.github.io/primefaces/11_0_0/#/../migrationguide/12_0_0
'Row select mode checkbox is now none.'

**Comment by melloware** [comment]
Understood, but this ticket is still an issue correct? Just the title needs to be changed to "none".?

**Comment by majkers** [comment]
Yes. Actually I do not have time right now to prepare a reproducer in 13.0.3 version sorry

**Comment by melloware** [comment]
@majkers then feel free to report this through your PRO account.

**Comment by majkers** [comment]
@melloware I do nto have PRO account, just elite licence. I have a monkey patch for it but it is usefull only for my application because it does some other stuff too so I can;t make a PR
