### ISSUE TITLE
FileUpload on Primefaces 5.2; not working / can't get it to work

### ISSUE THREAD

**Issue by rwaals** [primefaces/primefaces#443]
I am using Jetty 9.2.1 in combination with Primefaces version 5.2.

Didn't get the file upload to call my handler using the primefaces.UPLOADER, value auto. 
I went as far as setting it to commons and including the speficied commons and fuleupload libraries + the filter and filter mapping from the documentation. That did not work either (in combination with both the simple and advanced fileUpload field); fileupload component on the GUI seems to work, with progressbar and all, but the handler is never being called (file always NULL). 

After that, I changed it to:
    <context-param>
        <param-name>primefaces.UPLOADER</param-name>
        <param-value>native</param-value>
     </context-param>

Which does not work either; no error shown, the fileUpload element shows correctly but when pressing upload the progress bar does work but the handler is not being called. I have tried everything, including everything mentioned in the various fora, but alas, no success. Everything else is working (other components I mean). 

Last thing I tried was to set up one simple page, a simple header and within the body section the following:

```
<h:form enctype="multipart/form-data">
    <p:fileUpload fileUploadListener="#{fileBean.handleFileUpload}" />
</h:form>
```

The FileBean as simple as specified:

```
public class FileBean {
    public void handleFileUpload(FileUploadEvent event) {
        UploadedFile file = event.getFile();
    }
}
```

The result was; element shown correctly, handler not being called, at all. 
I am not using any other libraries (such as Glassfish or Prettyfaces, etc).

For completeness, the followign JAR files are located in the WEB-INF/lib folder (i have removed the commons libraries "commons" and "fileupload" as this did not make any difference):
asm-5.0.1.jar
asm-commons-5.0.1.jar
bootstrap-1.0.10.jar
fcgi-client-9.2.1.v20140609.jar
fcgi-server-9.2.1.v20140609.jar
javax-inject.jar
javax-websocket-client-impl-9.2.1.v20140609.jar
javax-websocket-server-impl-9.2.1.v20140609.jar
javax.annotation-api-1.2.jar
javax.el-3.0.0.jar
javax.faces-2.2.7.jar
javax.faces-api-2.2.jar
javax.mail.glassfish-1.4.1.v201005082020.jar
javax.security.auth.message-1.0.0.v201108011116.jar
javax.servlet.jsp-2.3.2.jar
javax.servlet.jsp-api-2.3.1.jar
javax.servlet.jsp.javax.servlet.jsp-api-2.3.1.jar
javax.servlet.jsp.jstl-1.2.2.jar
javax.transaction-api-1.2.jar
javax.websocket-api-1.0.jar
jetty-jsp-jdt-2.3.3.jar
jetty-monitor-9.2.1.v20140609.jar
jetty-setuid-java-1.0.1.jar
org.apache.taglibs.taglibs-standard-impl-1.2.1.jar
org.apache.taglibs.taglibs-standard-spec-1.2.1.jar
org.eclipse.jdt.core-3.8.2.v20130121.jar
org.eclipse.jetty.apache-jsp-9.2.1.v20140609.jar
org.eclipse.jetty.orbit.javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
org.eclipse.jetty.orbit.org.eclipse.jdt.core-3.8.2.v20130121.jar
org.mortbay.jasper.apache-el-8.0.3.v20140313.jar
org.mortbay.jasper.apache-jsp-8.0.3.v20140313.jar
primefaces-5.2.jar
smoothness-1.0.10.jar
websocket-api-9.2.1.v20140609.jar
websocket-client-9.2.1.v20140609.jar
websocket-common-9.2.1.v20140609.jar
websocket-server-9.2.1.v20140609.jar
websocket-servlet-9.2.1.v20140609.jar

I am running on Windows 7, tried this with both IE 11 and Chrome (latest version). 

web.xml content:

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://java.sun.com/xml/ns/javaee"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
id="WebApp_ID" version="3.0">
<display-name>Data Crow Web Client</display-name>

<welcome-file-list>
    <welcome-file>index.xhtml</welcome-file>
</welcome-file-list>

<context-param>
    <param-name>primefaces.UPLOADER</param-name>
    <param-value>native</param-value>
 </context-param>
<context-param>
    <description>State saving method: 'client' or 'server' (=default). See JSF Specification 2.5.2</description>
    <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
    <param-value>client</param-value>
</context-param>
<context-param>
    <param-name>primefaces.THEME</param-name>
    <param-value>bootstrap</param-value>
</context-param>
<context-param>
    <param-name>javax.servlet.jsp.jstl.fmt.localizationContext</param-name>
    <param-value>resources.application</param-value>
</context-param>
<context-param>
    <param-name>primefaces.FONT_AWESOME</param-name>
    <param-value>false</param-value>
</context-param>

<servlet>
    <servlet-name>Faces Servlet</servlet-name>
    <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
</servlet>
<servlet>
    <servlet-name>staticAssets</servlet-name>
    <servlet-class>org.eclipse.jetty.servlet.DefaultServlet</servlet-class>
</servlet>

<servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>/faces/*</url-pattern>
</servlet-mapping>
<servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.jsf</url-pattern>
</servlet-mapping>
<servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.faces</url-pattern>
</servlet-mapping>
<servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.xhtml</url-pattern>
</servlet-mapping>
<servlet-mapping>
    <servlet-name>staticAssets</servlet-name>
    <url-pattern>/images/*</url-pattern>
</servlet-mapping>
<servlet-mapping>
    <servlet-name>staticAssets</servlet-name>
    <url-pattern>/resources/*</url-pattern>
</servlet-mapping>

<mime-mapping>
    <extension>png</extension>
    <mime-type>image/png</mime-type>
</mime-mapping>
<mime-mapping>
    <extension>jpeg</extension>
    <mime-type>image/jpeg</mime-type>
</mime-mapping>
<mime-mapping>
    <extension>jpg</extension>
    <mime-type>image/jpeg</mime-type>
</mime-mapping>

<listener>
    <listener-class>com.sun.faces.config.ConfigureListener</listener-class>
</listener>
</web-app>
```

I am working on a web version for Data Crow (http://datacrow.net) and am rapidly building this with your excellent components. I am hoping to use the fileupload for picture uploading. 

Cheers,
Robert

**Comment by srbala** [comment]
Have you posted your question in PrimeFaces forum, you will get your answer since it has been reviewed by all community members.

**Comment by rwaals** [comment]
Thanks, I have submited a topic there.

**Comment by cagataycivici** [comment]
Could be an issue with jetty 9 upload impl so not related to PrimeFaces, try commons uploader.

**Comment by srbala** [comment]
commons-fileupload-1.3.0.jar is missing on your jar files list you may want to add that. Primefaces components has dependency on it
https://raw.githubusercontent.com/primefaces/primefaces/master/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java

Few web.xml entries missing, you may want to add them too.

```
<listener>
    <listener-class>org.apache.commons.fileupload.servlet.FileCleanerCleanup</listener-class>
</listener>

<filter>
    <filter-name>PrimeFaces FileUpload Filter</filter-name>
    <filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>PrimeFaces FileUpload Filter</filter-name>
    <servlet-name>Faces Servlet</servlet-name>
</filter-mapping>
```

**Comment by rwaals** [comment]
I have it working now on Tomcat, using the native method (not including any of the commons libraries). I have tried everything to get it to work on Jetty, but, alas, it simply doesn't work there.

**Comment by Arvoreen** [comment]
I managed to get this to work, with some minor differences
1. I am using Jetty 9.2.9.v20150224
2. You can not use commons file uploader. Since Jetty DOES implement the Sevlet 3.0 spec, it will try to parse the multipart form itself, even if you add the file upload filter in place.  I make sure to force 'native' processing by setting primfaces.UPLOAD context param to 'native'
3. With that parameter, the filter will bypass so it is safe to leave in place.
4. I also am using a more recent release of javax.faces (2.2.11)
5. I found that I didn't have to explicitly register the Faces Servlet. It was being picked up via annotations, and registered as **'FacesServlet'** .  Actually, my duplicate registration may have caused problems.

**Comment by cagataycivici** [comment]
Glad to hear, thanks for sharing this.
