### ISSUE TITLE
DatePicker: mindate and maxdate with selectionMode=range

### ISSUE THREAD

**Issue by majulvez** [primefaces/primefaces#4435]
## 1) Environment
- Version 6.2.14
- Tested with version 7-SNAPSHOT too and it happens the same error
- Apache Tomcat 7.0.62
- Chrome/Firefox

## 2) Expected behavior
Showing datePicker component with a min a max interval

## 3) Actual behavior
 It shows javascript errors

## 4) Steps to reproduce
Just go to see the xhtml file in the browser and you see the same picture I posted in the forum
https://forum.primefaces.org/viewtopic.php?f=3&t=57916
.. 

## 5) Sample XHTML
<h:form id="form">
        <p:datePicker id="minmax" selectionMode="range" value="#{calendarView.dates}" mindate="#{calendarView.minDate}" maxdate="#{calendarView.maxDate}"  />
    </h:form>
..

## 6) Sample bean
package com.primefaces.test;

import javax.faces.bean.ManagedBean;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

@ManagedBean(name = "calendarView")
public class CalendarView implements Serializable {

    private Date minDate;
    private Date maxDate;
    private List<Date> dates;

    public CalendarView() {
        Date today = Calendar.getInstance().getTime();
        long oneDay = 24 * 60 * 60 * 1000;
        minDate = new Date(today.getTime() - (365 * oneDay));
        maxDate = new Date(today.getTime() + (365 * oneDay));
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getMinDate() {
        return minDate;
    }

    public void setMinDate(Date minDate) {
        this.minDate = minDate;
    }

    public Date getMaxDate() {
        return maxDate;
    }

    public void setMaxDate(Date maxDate) {
        this.maxDate = maxDate;
    }

    public List<Date> getDates() {
        return dates;
    }

    public void setDates(List<Date> dates) {
        this.dates = dates;
    }
}

##7 Comments
I tested selectionMode="range" and disabledDates option together and datePicker is showing mostly the same errors than in this issue

**Comment by mertsincan** [comment]
Fixed for next version. Thanks a lot!
