### ISSUE TITLE
DatePicker: selectionMode=range and range with disabled dates in between

### ISSUE THREAD

**Issue by majulvez** [primefaces/primefaces#4439]
## 1) Environment
- PrimeFaces version: 6.2.14
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Apache Tomcat 7.0.62
- Affected browsers: Chrome/Firefox

## 2) Expected behavior
Selecting a range of dates with disabled dates in between is not possible

## 3) Actual behavior
Selecting a range of dates with disabled dates in between IS possible

## 4) Steps to reproduce
Just view xhtml page in the browser and select the first date before the disabled date and the second date after.

## 5) Sample XHTML
`
<h:form>
    <p:datePicker numberOfMonths="2" selectionMode="range" value=“#{calendarView.dates}" disabledDates="#{calendarView.disabledDates}"  />
</h:form>
`

## 6) Sample bean
`
import javax.faces.bean.ManagedBean;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

@ManagedBean(name = "calendarView")
public class CalendarView implements Serializable {

    private List<Date> dates;
    private List<Date> disabledDates;

    public CalendarView() {
        Date today = Calendar.getInstance().getTime();
        long oneDay = 24 * 60 * 60 * 1000;
        Date disabledDate = new Date(today.getTime() + (3 * oneDay));

        disabledDates = new ArrayList<>();
        disabledDates.add(disabledDate);
    }

    public List<Date> getDates() {
        return dates;
    }

    public void setDates(List<Date> dates) {
        this.dates = dates;
    }

    public List<Date> getDisabledDates() {
        return disabledDates;
    }

    public void setDisabledDates(List<Date> disabledDates) {
        this.disabledDates = disabledDates;
    }
}
`

**Comment by majulvez** [comment]
Is this issue considered a bug?

**Comment by melloware** [comment]
I would say its a bug.

**Comment by tandraschko** [comment]
@mertsincan wdyt?

**Comment by mertsincan** [comment]
No bug, we have decided that users can control disabledDays in range using ajax events and throw a validation exception.
