### ISSUE TITLE
Duplication of the header bar in <p:dataTable> when the DOM changes (with stickyHeader)

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#444]
Hello,
Here are some screenshots to better understand the problem:

![cap](https://cloud.githubusercontent.com/assets/12255492/8199154/81ebd116-14a0-11e5-9fda-00440e7e7f43.png)

Options in dataTable:

```
stickyHeader="true"
paginator="true" 
paginatorPosition="both" 
paginatorTemplate="{Exporters}"
reflow="false"
editable="false"
editingRow="false"
+
<p:columnToggler datasource="xxxxxx" trigger="toggler" />
```

thanks.

**Comment by cagataycivici** [comment]
What do you mean by dom changes?

**Comment by RejDev** [comment]
for example, when we remove a table element with the "remove button" , it displays a message with the function :

```
FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "test test test test test test test"));
```

it adds the message, and it shifts the dataTable, if you close the message,it activates the "stickyHeader" erroneously.

**Comment by RejDev** [comment]
for example, when we remove a table element with the "remove button" , it displays a message with the function :

```
FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "test test test test test test test"));
```

it adds the message, and it shifts the dataTable, if you close the message,it activates the "stickyHeader" erroneously.

**Comment by sudheerj** [comment]
The issue is replicated and caused by default slideUp effect of a messages close icon during the click event.If there is a close effect then we can change the default close effect behavior.So it is good to have issue title as close effect feature.

In the mean time you might customize the messages renderer or use custom jquery code as a workaround.

**Comment by cagataycivici** [comment]
It is a very edge case yes. We can't now if DT is pushed down. Also you haven't mentioned your PF version, try with the latest version.

**Comment by RejDev** [comment]
Hello,
I tested with the latest version (primefaces-5.3-SNAPSHOT - 21/06/2015) .
The problem still exists.

**Comment by khanasad** [comment]
This happens with the columnToggler as well. If you add a new column one gets duplicate header (one with the previous column set and the other one with the new one). It happens with Primefaces 5.3
