### ISSUE TITLE
DataTable/TreeTable: ContextMenu disappears after update

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#4448]
I have a dataTable with contextMenu and menuItem dynamically being shown/disabled or not in it.

More or less it looks like this:

`<p:dataTable id="dataTableId">
.....
<p:ajax event="contextMenu" 
listener="#{controller.onMenuDisplay} 
update="contextMenuId" />
.....
</p:dataTable>
`

And below:

`
<p:contextMenu id="contextMenuId" for="dataTableId"
widgetVar="contextMenuWidgetVar">
					<p:menuitem value="XXX"
								process="@this"
								actionListener="#{controller.action}"
								rendered="#{controller.shouldBeRendered}"/>
`
After executing ajax event, contextMenu shows for a while and disappers.

1) Environment
- PrimeFaces version: 6.2.14
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: WLS 12.2.3.0.0
- Affected browsers: All (FireFox, Chrome, Edge, IE)

2) Expected behavior

Context menu must update its menuItems and stay visible

3) Actual behavior

Context menu updates, shows itself for a while and disappears.

4) Steps to reproduce
Click with RMB on a row in a dataTable with p:ajax event="contextMenu" with update being set on contextMenu with rendered and disabled parameters.

**Comment by tandraschko** [comment]
Please provide a simple reproducer xhtml+bean and also try 7.0.RC1.

**Comment by majkers** [comment]
You can use code from showcase https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml The only thing You have to change is to add an event contextMenu to dataTable with update on p:contextMenu and rendered function to menuItem

**Comment by tandraschko** [comment]
So please modify the xhtml and post it here. 
Issues without sample are actually invalid by our definition.
90% of the people here are helping in the freetime and if you like that someones fixes a bug for you, please provide a reproducer.

**Comment by majkers** [comment]
I know that is why I used some code snippets in a description...Ok later on I will add come extra code

**Comment by majkers** [comment]
Just modifying https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

contextMenu.xhtml

```js
<h:form id="form">
    <p:dataTable id="cars" var="car" value="#{dtContextMenuView.cars}" rowKey="#{car.id}"
                 selection="#{dtContextMenuView.selectedCar}" selectionMode="single">

        <p:ajax event="contextMenu" update="contextMenuId"/>

        <f:facet name="header">
            RightClick to View Options
        </f:facet>
        <p:column headerText="Id">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Year">
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Brand">
            <h:outputText value="#{car.brand}" />
        </p:column>
        <p:column headerText="Color">
            <h:outputText value="#{car.color}" />
        </p:column>
    </p:dataTable> 
 
    <p:contextMenu id="contextMenuId" for="cars">
        <p:menuitem value="Delete" update="cars" icon="pi pi-times" action="#{dtContextMenuView.deleteCar}" 
rendered="#{dtContextMenuView.renderDeleteCar()}"/>
    </p:contextMenu>
</h:form>
```

And ContextMenuView.java
```java
@ManagedBean(name="dtContextMenuView")
@ViewScoped
public class ContextMenuView implements Serializable {
     
    private List<Car> cars;
     
    private Car selectedCar;
     
    @ManagedProperty("#{carService}")
    private CarService service;
 
    @PostConstruct
    public void init() {
        cars = service.createCars(10);
    }
     
    public List<Car> getCars() {
        return cars;
    }
 
    public Car getSelectedCar() {
        return selectedCar;
    }
 
    public void setSelectedCar(Car selectedCar) {
        this.selectedCar = selectedCar;
    }
 
    public void setService(CarService service) {
        this.service = service;
    }

    public boolean renderDeleteCar() {
        return selectedCar != null && selectedCar.getYear() > 1970;
    }
     
    public void deleteCar() {
        cars.remove(selectedCar);
        selectedCar = null;
    }
}
```

**Comment by melloware** [comment]
I think what is happening is it an ordering problem.  What I think happens is this..

1. Jquery event to display the Context Menu in the browser.
2. Ajax event fires to the server side for the p:ajax event.
3. Since you have update="contextMenuId" to update the contextMenu the DOM of the entire context menu is being replaced thus its detroying the current menu that is being displayed on screen.

This is tricky.

**Comment by majkers** [comment]
The solution is here: https://forum.primefaces.org/viewtopic.php?t=41973

**Comment by melloware** [comment]
So when you say solution the JS hack or the fact to update the context menu with "rowSelect" Ajax event instead of the ContextMenu ajax event?

**Comment by majkers** [comment]
It is more like a workaround not a fix. I meant a post by CORSIC.

**Comment by melloware** [comment]
OK. Definitely a workaround.

**Comment by bkampsnl** [comment]
Any update ?

**Comment by melloware** [comment]
@bkampsnl This is definitely not high priority so without someone providing a PR this most likely will not be worked on.  Especially since above there is a provided workaround.

**Comment by naofireblade** [comment]
I have a fix for that but did not test it with TreeTable yet.

**Comment by iscozak** [comment]
The same correction should be applied to TreeTable, as adviced in incidence subject.
