### ISSUE TITLE
inputTextarea: counter component not updated after selected text is cut via mouse

### ISSUE THREAD

**Issue by tdtappe** [primefaces/primefaces#4449]
If some text is selected in an inputTextarea and the selected text is deleted/cut via mouse context menu the counter component is not updated and still shows the same number of remaining characters.
If the selected text is deleted via pressing the delete key everything's fine.

PrimeFaces version: 6.2.14
Wildfly 13.0.0.Final
Firefox 64.0.2, Chrome 71.0.3578.98

**Comment by tandraschko** [comment]
please provide a example or at least the steps to reproduce it in the showcase.
Issues without all informations requested are actually invalid.

**Comment by melloware** [comment]
I have verified this issue and it's broken for InputText and InputTextArea.  I have submitted a PR that fixes it and i tested in IE11, Firefox, Chrome, and Edge and its working in all scenarios now.

**Comment by tandraschko** [comment]
Thanks melloware!
