### ISSUE TITLE
Reimplement Row and Cell Editing in DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#445]
Current implementation is not effective, both output and input facets are rendered to the client. Instead we should lazy load it, when a row goes in edit mode, an ajax call should fetch the row in edit mode by rendering the input facets only. This will really help reducing page size and speed up performance.

**Comment by cagataycivici** [comment]
Will not proceed.

**Comment by VsevolodGolovanov** [comment]
@cagataycivici, is there a technical issue preventing this, or just not enough demand? Was interested in trying to implement this.
The current implementation is very problematic with live scroll (submits all inputs in the table and there can easily be too many) and when there are select-inputs (the page is way too heavy both in element count and raw size).
