### ISSUE TITLE
TextEditor: support image upload

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#4452]
I just stumbled upon an idea on primefaces-extensions/primefaces-extensions#757 and think it's worth being picked up as new feature request for PrimeFaces 7.1.

It woud be nice to have an additional editor button to upload images.

Since `p:textEditor` actually submits HTML it would make sense to embed Base64 encoded image data URLs using javascript's `FileReader` API. See my comment here: primefaces-extensions/primefaces-extensions#757.

Feature add-ons would be support for drag&drop as well as copy&paste.

If I find some time, I'll try to provide a PR.

**Comment by rider87** [comment]
> I just stumbled upon an idea on [primefaces-extensions/primefaces-extensions#757](primefaces-extensions/primefaces-extensions#757) and think it's worth being picked up as new feature request for PrimeFaces 7.1.
> 
> It woud be nice to have an additional editor button to upload images.
> 
> Since `p:textEditor` actually submits HTML it would make sense to embed Base64 encoded image data URLs using javascript's `FileReader` API. See my comment here: [primefaces-extensions/primefaces-extensions#757 (comment)](primefaces-extensions/primefaces-extensions#757).
> 
> Feature add-ons would be support for drag&drop as well as copy&paste.
> 
> If I find some time, I'll try to provide a PR.

Did you had the time for a PR?

**Comment by melloware** [comment]
The new SunEditor in PFE does this by default and makes the URL a Base64 encoded image URL: https://www.primefaces.org/showcase-ext/sections/sunEditor/basicUsage.jsf
