### ISSUE TITLE
Datatable: Rowgrouping issue if value is null

### ISSUE THREAD

**Issue by KarlKnapp** [primefaces/primefaces#4455]
If the group value is empty a new group is created for each row.

## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior

![grouprowfixed](https://user-images.githubusercontent.com/30590617/51478910-0e5bc400-1d8d-11e9-86fc-eb06684f300b.png)

## 3) Actual behavior

![grouprowbroken](https://user-images.githubusercontent.com/30590617/51478918-19aeef80-1d8d-11e9-91a9-0b2d4ae3dd1a.png)

## 5) Sample XHTML
``` 
<p:headerRow>
       <p:column colspan="8">
              <h:outputText value="#{item.THIS_VALUE_IS_NULL}" />
      </p:column>
 </p:headerRow>
```

**Comment by mertsincan** [comment]
Thanks a lot for the PR ;)

**Comment by tandraschko** [comment]
@KarlKnapp refactored with Objects.equals - Could you give it a try?

**Comment by KarlKnapp** [comment]
Seems to work, too.
