### ISSUE TITLE
Wizard - Next button causes NullPointerException

### ISSUE THREAD

**Issue by PiotrRaszkowski** [primefaces/primefaces#446]
When you move to the last step, the "Next" button disappears but you can change the css property "display" to block and then you are able to click the button again (additionally you can click the button before it disapears). This action causes NullPointerException in your code:
Line 76, WizardRenderer

**Comment by cagataycivici** [comment]
How to replicate at showcase?

**Comment by PiotrRaszkowski** [comment]
Hi,

Use FireBug or similar tool to change the "display" property (from "none" to  "block"):
![image](https://cloud.githubusercontent.com/assets/6020028/8202756/20ec1f32-14dd-11e5-8fb9-f1b158021495.png)

Click "Next"
![image](https://cloud.githubusercontent.com/assets/6020028/8202725/efad31e0-14dc-11e5-9da0-1cc0ff58a4c8.png)

**Comment by sudheerj** [comment]
Thats fine.But generally Why user will  change the CSS through firebug and do the web interactions.

**Comment by PiotrRaszkowski** [comment]
This bug has been detected by our tester - he was able to click the button before it disappeared... and it is possible also using your showcase :).

**Comment by cagataycivici** [comment]
Ok, will look into it.
