### ISSUE TITLE
DatePicker: firstDay: 1 not working

### ISSUE THREAD

**Issue by majulvez** [primefaces/primefaces#4460]
## 1) Environment
- PrimeFaces version: 6.2.14
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Apache Tomcat 7.0.62
- Affected browsers: All

## 2) Expected behavior
First day of the week is monday

## 3) Actual behavior
First day of the week is SUNDAY

## 4) Steps to reproduce
Just load the .xhtml file and do click in datepicker component

## 5) Sample XHTML
<h:outputScript>
PrimeFaces.locales['es'] = {
    closeText: 'Cerrar',
    prevText: 'Anterior',
    nextText: 'Siguiente',
    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
    dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    weekHeader: 'Semana',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: '',
    timeOnlyTitle: 'Sólo hora',
    timeText: 'Tiempo',
    hourText: 'Hora',
    minuteText: 'Minuto',
    secondText: 'Segundo',
    currentText: 'Fecha actual',
    ampm: false,
    month: 'Mes',
    week: 'Semana',
    day: 'Día',
    allDayText: 'Todo el día'
};
</h:outputScript>
<p:datePicker id="inline" value="#{calendarView.date1}" inline="true" locale="es" />

## 6) Sample bean
@ManagedBean
public class CalendarView {
    private Date date1;

    public Date getDate1() {
        return date1;
    }
 
    public void setDate1(Date date1) {
        this.date1 = date1;
    }
}

## 7)Comments
Even in the show case is not working properly (spanish example) https://www.primefaces.org/showcase/ui/input/datePicker.xhtml

**Comment by melloware** [comment]
This may be a dumb question but why do you assume the first day of the week should be MONDAY?  Based on the Spanish Locale?

**Comment by fcorneli** [comment]
https://www.timeanddate.com/calendar/days/

**Comment by fcorneli** [comment]
According to international standard ISO 8601, Monday is the first day of the week.

**Comment by melloware** [comment]
OK I was under the impression that it said "not working" like it was a bug when really this is a feature request.

While that may be true about ISO 8601 I would definitely not expect Monday to be the first day in a calendar component.  Every real world calendar I have including the one I am looking at my desk right now has the UI as Sunday to Saturday.  So I would hate for the component not to mimic the real world calendar people are used for usability.

To me this should be marked enhancement and it should be an attribute on the component to allow either view Sunday to Saturday or Monday to Sunday.

**Comment by majulvez** [comment]
Hi @melloware ,

same property in component calendar it works as I expected. Calendar component starts the week in monday if I use firstDay:1 so I thought this issue would be considerer as a bug

**Comment by majulvez** [comment]
Maybe I confused you because I forgot to write down I am using spanish locale in the example. I'm going to edit it

**Comment by melloware** [comment]
Understood!  yes please add SPanish locale to your example it would help.  But yes this feature definitely looks missing in the DatePicker as its not in the PrimeNG component it was based on.  https://www.primefaces.org/primeng/#/calendar

**Comment by majulvez** [comment]
In primeNG component is working fine using firstDayOfWeek: 1

I tried that property in date picker settings just in case but no luck

**Comment by melloware** [comment]
@majulvez Let me look. If it's in the PrimeNG component I think I can fixt this component.  Investigating now.

**Comment by melloware** [comment]
OK figured it out its a documentation error.  The property is firstDayOfWeek: 1 and not firstDay.

```javascript
<script type="text/javascript">
    PrimeFaces.locales['es'] = {
        closeText: 'Cerrar',
        prevText: 'Anterior',
        nextText: 'Siguiente',
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
        dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
        weekHeader: 'Semana',
        firstDayOfWeek: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: '',
        timeOnlyTitle: 'Sólo hora',
        timeText: 'Tiempo',
        hourText: 'Hora',
        minuteText: 'Minuto',
        secondText: 'Segundo',
        currentText: 'Fecha actual',
        ampm: false,
        month: 'Mes',
        week: 'Semana',
        day: 'Día',
        allDayText: 'Todo el día'
    };
</script>
```

I will update the showcase

**Comment by melloware** [comment]
Submitted PR to showcase: https://github.com/primefaces/showcase-facelift/pull/26

**Comment by majulvez** [comment]
Hi @melloware ,

does it work with firstDayOfWeek:1? 

I just did a test and It's not working as we expected. I still see sunday as a first day of the week

**Comment by melloware** [comment]
Attached is my test project you can run with "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

firstDayOfWeek: 1
![image](https://user-images.githubusercontent.com/4399574/51561913-7cb88900-1e56-11e9-8b55-b305127d117c.png)

FirstDayOfWeek: 0
![image](https://user-images.githubusercontent.com/4399574/51561978-a1acfc00-1e56-11e9-98e5-34884b54769c.png)

[pf-firstDay.zip](https://github.com/primefaces/primefaces/files/2784389/pf-firstDay.zip)

**Comment by majulvez** [comment]
I tested with 6.2.14. Maybe is the version. I see your test is with 7 snapshot. I'll give a try and I'll let you know

Thx!

**Comment by melloware** [comment]
yep it could be a bug in 6.2.14 branch that is fixed in 7.0-SNAPSHOT

**Comment by majulvez** [comment]
I made a mistake in the last test. It's working fine in 6.2.14 using firstDayOfWeek:1 too

Thank you for your help @melloware

**Comment by melloware** [comment]
No problem. Can you close this ticket?  I have updated the Showcase appropriately for the next release.

**Comment by GedMarc** [comment]
Hi There,

What maven repo can I pull 7.0-Snapshot from? :)

**Comment by melloware** [comment]
change 7.0-SNAPSHOT to 7.0.RC1 and it should work.

that is in the PrimeTek repo which that pom.xml already has mapped.

**Comment by GedMarc** [comment]
Phew! Not going crazy!
Considering my week so far this is comforting xD 

Perhaps this is just incompatibility with options? The datepicker shows so that's already a massive step forward!

[pfdatepicker.zip](https://github.com/primefaces/primefaces/files/2788845/pfdatepicker.zip)

**Comment by melloware** [comment]
Whoops OK now I fixed it.  Try this one...
[pf-datepicker.zip](https://github.com/primefaces/primefaces/files/2788861/pf-datepicker.zip)
