### ISSUE TITLE
ImageCropper: broken

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#4464]
@melloware it seems that imageCropper is broken in trunk showcase and firefox. As you updated the plugin, can you check that?

**Comment by melloware** [comment]
Investigating...

**Comment by melloware** [comment]
Hmm I am using Firefox Quantum 64.02 and ImageCropper seems to be working fine for me?

![image](https://user-images.githubusercontent.com/4399574/51608153-a7e9b980-1ee4-11e9-835d-0f08d123afa1.png)

**Comment by tandraschko** [comment]
please try on localhost with trunk

**Comment by melloware** [comment]
Hmm localhost with the latest 7.0-SNAPSHOT from this morning is also working fine in Chrome and Firefox for me.

**Comment by mertsincan** [comment]
@melloware Please see; https://www.dropbox.com/s/p6m81vxtlgko693/cropper_test.avi?dl=0

After the page refresh, cropper component works fine for me on FF 64.0.2

**Comment by tandraschko** [comment]
yep, same for me
but it also works only randomly on refresh
maybe is the script initialized to early and "wb.initWithComponentLoad" doesn't work correctly?

**Comment by melloware** [comment]
ok interesting let me keep messing with it to try and reproduce.

**Comment by mertsincan** [comment]
It works fine for me with "wb.init" instead of "wb.initWithComponentLoad"

**Comment by melloware** [comment]
@mertsincan you want to fix it or do you want me to submit a PR?

**Comment by tandraschko** [comment]
the problem is that wb.init will be actually be executed on document.ready (before window.load) and therefore the image shoudln't be loaded yet.
initWithComponentLoad actually should be the better solution - maybe also related a bit with MOVE_SCRIPTS_TO_BOTTOM.

**Comment by melloware** [comment]
Confirmed. If I change Showcase to MOVE_SCRIPTS_TO_BOTTOM=false it works fine.

**Comment by tandraschko** [comment]
probably jq "$element.on('load')" doesn't execute the listener when it's already loaded. Is there a jquery solution like "execute listener on load or when already loaded"?

**Comment by melloware** [comment]
@tandraschko Am I reading this wrong?  It says Load method was deprecated in Jquery 1.8 and removed in 3.0.  Are we getting it because we have the migrate script?

https://api.jquery.com/load-event/

**Comment by tandraschko** [comment]
i think there is a difference between the old-style load method or the .on('load') event

**Comment by melloware** [comment]
Hmm that page says "This method is a shortcut for .on( "load", handler )."

**Comment by melloware** [comment]
Excellent fix!

**Comment by marcelocaser** [comment]
I think the problem still persists. When clicking on the 'crop' button an error page is generated!

**Comment by melloware** [comment]
Ahh that is a new issue please open a new issue.
