### ISSUE TITLE
DataTable: Row Selection does not select Radio Button

### ISSUE THREAD

**Issue by bl4cksun** [primefaces/primefaces#4468]
## 1) Environment
- PrimeFaces version: 6.2.9
- Does it work on the newest released PrimeFaces version: no, can be reproduced in PrimeFaces Showcase (7.0-SNAPSHOT)
- Application server + version: presumably all
- Affected browsers: presumably all

## 2) Expected behavior

- when selecting a row in a table with radio button selection via mousedown, the corresponding radio button and the row should be selected
- the expected behavior would be consistent with the behavior for a table with check box selection this way

## 3) Actual behavior

- upon row-hover, the cursor changes into a pointer but neither the hover effect does is shown nor the row selected on mousedown
- selection is only possible by selecting the radio button directly, but the pointer cursor suggests, the whole row is selectable as well
- see https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

## 4) Steps to reproduce

- hover the mouse over the data table with radio button selection
- perform mousedown anywhere except the radio button itself

## 5) Sample XHTML

- see https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

## 6) Sample bean

- see https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml

**Comment by melloware** [comment]
Similar or same as this issue: https://github.com/primefaces/primefaces/issues/1417

**Comment by bl4cksun** [comment]
@melloware 

You are correct, issue #1417 it is similar. However, there seems to be an inconsistency between the DataTable selectable via CheckBoxes and via RadioButton. I would expect the same behavior in both, either the row is selectable by mousedown elsewhere or it is not.

It would be good to know, which is the desired/expected behavior here.

**Comment by melloware** [comment]
@bl4cksun Agreed.  It seems radio and checkbox do two different things but PF should just pick one and make it the same for both.

**Comment by bl4cksun** [comment]
Since #1417 and this issue differ in the expected behavior, maybe the behavior should be configurable with a default behavior that is intuitive for most people.
