### ISSUE TITLE
7.0.RC1 - DatePicker : Combination of selection="multiple" and numberOfMonths results in a broken date picker

### ISSUE THREAD

**Issue by GedMarc** [primefaces/primefaces#4470]
[pfdatepicker.zip](https://github.com/primefaces/primefaces/files/2788871/pfdatepicker.zip)

Not sure what else to say, it's all in the title :)

7.0.RC1

**Comment by melloware** [comment]
Thanks for including the reproducible sample!

**Comment by mertsincan** [comment]
I think this issue is fixed on 7.0.Final. Please try 7.0-SNAPSHOT.

**Comment by GedMarc** [comment]
which repo can I get 7.0-snapshot from?

**Comment by cnsgithub** [comment]
```xml
 <dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>7.0.RC1</version>
 </dependency>

 <repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>
```

Or `master-SNAPSHOT` as version, see https://github.com/primefaces/primefaces/blob/master/README.md

**Comment by GedMarc** [comment]
Ok not yet - it selects, but doesn't store.

**Comment by GedMarc** [comment]
[pfdatepicker-mastersnapshot.zip](https://github.com/primefaces/primefaces/files/2790736/pfdatepicker-mastersnapshot.zip)

![image](https://user-images.githubusercontent.com/5367513/51664390-06d13080-1fc2-11e9-9927-cc4bf9015f47.png)

On Form Update
![image](https://user-images.githubusercontent.com/5367513/51664418-105a9880-1fc2-11e9-92f4-a107dfb54a6f.png)


Jan 24, 2019 10:22:45 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: javax.faces.FacesException: Value could be either String or java.util.Date
        at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:136)
        at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:55)


I fixed this one in my custom hackathon by doing

```

	private String getValueString(FacesContext context, UICalendar uicalendar)
	{
		String value = null;
		ValueExpression ve = uicalendar.getValueExpression("value");
		if (ve != null) {
			Object valObject = ve.getValue(context.getELContext());
			if(valObject != null)
			{
				if(!valObject.getClass().equals(ArrayList.class))
					value = CalendarUtils.getValueAsString(context, uicalendar, valObject);
				else
				{
					List<Date> dates = (List<Date>) valObject;
					if(!dates.isEmpty()) {
						StringBuilder valueBuilder = new StringBuilder();
						for (Date date : dates) {
							SimpleDateFormat dateFormat = new SimpleDateFormat(uicalendar.calculatePattern(), uicalendar.calculateLocale(context));
							dateFormat.setTimeZone(uicalendar.calculateTimeZone());
							valueBuilder.append(dateFormat.format(date)).append(",");
						}
						value = valueBuilder.toString();
						value = value.substring(0, value.length() - 1);
					}
				}
			}
		}
		return value;
	}
```

**Comment by GedMarc** [comment]
Other things I had to fix, was the immediate controller, Looks like this still stays around - 
I did my ugly hack like this :
```
![image](https://user-images.githubusercontent.com/5367513/51664563-56176100-1fc2-11e9-9fcd-288c8fac994c.png)

```

Then I simply added in the range options as well with the multiple filter, and my custom build worked ;)

**Comment by GedMarc** [comment]
![image](https://user-images.githubusercontent.com/5367513/51664683-a4c4fb00-1fc2-11e9-834a-111f6e055dab.png)

**Comment by GedMarc** [comment]
Please re-open, Only close issues on confirmation of resolution?
You guys aren't the best at testing your implementations ;)

**Comment by GedMarc** [comment]
as you can obviously see by performing any update... It's really quite annoying.

**Comment by GedMarc** [comment]
@melloware And again, no testing occurs when making changes. This is terrible.
I'm pulling out of this, I have a working version that does what I need it to.

**Comment by melloware** [comment]
@tandraschko please reopen this.  There are clearly unresolved issues.

**Comment by melloware** [comment]
When I run this sample and select a few dates on the mutliple calendar and press the All Button I get this stack trace with 7.0-SNAPSHOT.

```
Jan 24, 2019 7:41:10 AM com.sun.faces.application.view.FaceletViewHandlingStrategy handleRenderException
SEVERE: Error Rendering View[/test.xhtml]
javax.faces.FacesException: Value could be either String or java.util.Date
        at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:136)
        at org.primefaces.util.CalendarUtils.getValueAsString(CalendarUtils.java:55)
        at org.primefaces.component.calendar.BaseCalendarRenderer.encodeEnd(BaseCalendarRenderer.java:58)

```
[pf-4470.zip](https://github.com/primefaces/primefaces/files/2791694/pf-4470.zip)

**Comment by tandraschko** [comment]
then please create a new issue + PR, as the owner closed this 2 times here, we should leave it closed.

**Comment by melloware** [comment]
No problem i will create a new one.

**Comment by mertsincan** [comment]
Thanks @melloware ;)
