### ISSUE TITLE
DatePicker - TypeError: dayIndex is undefined (on windows only)

### ISSUE THREAD

**Issue by rmpestano** [primefaces/primefaces#4473]
Hi guys, I'm getting an js error with datepicker but only on windows machines (Firefox/Chrome/Edge - all with clean browser caches). I've tested on two different windows 7 and 8 computers and 3 Linuxes (Ubuntu) desktops. I have no issues on ubuntu machines.

It is important if someone else with windows machines could also test the provided sample project.

****

## 1) Environment
- PrimeFaces version: 7.0-SNAPSHOT (commit hash: 1b86074953711c5b06a14178373657befd5e48ad)
- Application server + version:Jetty 9
- Affected browsers: Chrome 70/71, Edge and Firefox (62.3) and Edge (42.171)

## 2) Expected behavior

Datepicker should open.

## 3) Actual behavior

DatePicker doesn't open and page has javascript errors (it affects other componets and page get unusable)

## 4) Steps to reproduce

1 - [Install primefaces 7.0-SNAPSHOT ](https://github.com/primefaces/primefaces/wiki/Building-From-Source) locally
2 - Download sample project (it is primefaces-test project with datepicker sample page) below:

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/2798425/primefaces-test.zip)

3 - start application with `mvn jetty:run`
4 - access http://localhost:8080/primefaces-test/datepicker.xhtml

A quickier test is to access [this page](http://admin-showcase-admin.1d35.starter-us-east-1.openshiftapps.com/showcase/pages/components/datepicker.xhtml)  from a windows machine (or chrome/firefox for android which also fails but we cannot see the js errors).

## 5) Sample XHTML

see datepicker.xhtml on provided sample project

## 6) Sample bean

See DatePickerMB.java

### Screenshots:
![dayindex1](https://user-images.githubusercontent.com/1592273/51780643-46e5ff80-20f7-11e9-8352-9bada8d112f7.jpg)
 
![51780644-477e9600-20f7-11e9-8f3e-2e15d0b1cb8e](https://user-images.githubusercontent.com/1592273/51780802-e3f56800-20f8-11e9-9794-efd426c98d0f.jpg)

### Firefox console log
[firefox-log.txt](https://github.com/primefaces/primefaces/files/2798430/firefox-log.txt)

### DatePicker.js being used (extrated from page source)

[datepicker-widget.zip](https://github.com/primefaces/primefaces/files/2798433/datepicker-widget.zip)

**Comment by rmpestano** [comment]
Guys,

I`ve created a windows 10 VM and **could not reproduce** the issue, its working on all browsers both primefaces-test and the link I've provided. 

It may be some kind of cache or browser version, please don't close this issue yet, I'll investigate a bit further.

**Comment by melloware** [comment]
I was testing this heavily on windows 10 yesterday and everything was looking good. Definitely let us know if you can reproduce j can try out what you find.

**Comment by rmpestano** [comment]
Hi @melloware, I just don't know what's happening. 

Things I've done:

- Took same primefaces jar which is working on the windows 10 VM
- reinstaled firefox
- clear browser caches dozens of times
- use private ff windows
- tested on chrome and FF

Things I've noticed:

- It works on primefaces showcase (Also ran the showcase locally and it worked!)
- it fails on two different windows machines (at my company and at home)
- It works on 3 linuxes machines and one Windows machine under a virtualbox VM
- it fails on two mobile phones (I suppose the issue is the same cause the symptoms are the same, datepicker doesn't show up and page is unusable/broken)

**Comment by melloware** [comment]
This weekend I will retest all 4 browsers on Windows 10 and let you know if I see anything strange. Chrome Firefox IE11 and Edge.

**Comment by rmpestano** [comment]
Look the generated html of the same page (with only an inline datepicker) on showcase (working) and on primefaces-test project:

The scripts look very similar:

![prime-test](https://user-images.githubusercontent.com/1592273/51793417-7f451680-21a7-11e9-8d68-99a861095d6d.png)
![showcase](https://user-images.githubusercontent.com/1592273/51793418-7f451680-21a7-11e9-9d42-5fb5f0e3b399.png)

Now the component html was not generated completely on primefaces-test project:

![pf-test-input](https://user-images.githubusercontent.com/1592273/51793477-3fcafa00-21a8-11e9-90e6-7074ffebe0db.png)
![showcase-input](https://user-images.githubusercontent.com/1592273/51793478-40639080-21a8-11e9-99fa-d02a386000a2.png)

**Comment by rmpestano** [comment]
Alright, found the problem, it is a locale issue.

If you look carefully on the images above you'll see primefaces-test application was using my machine locale (PT_BR):
```
<script type="text/javascript">var pf=window.PrimeFaces;if(pf){pf.settings.locale='pt_BR';};
pf.cw("DatePicker","widget_form_inline",{id:"form:inline",inline:true,locale:"pt_BR",dateFormat:"dd\/mm\/y",selectionMode:"single",showOnFocus:true});</script>
```

forcing the locale to en (as primefaces showcase does) on faces-config solves the issue.


Now I think you can solve the issue, right? following is a sample app with pt_BR locale configured as default to reproduce the issue:

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/2799567/primefaces-test.zip)

**Comment by melloware** [comment]
Yep that will help let me do some debugging

**Comment by mertsincan** [comment]
Hi @rmpestano,

Could you please test it again?

**Comment by rmpestano** [comment]
Hi @mertsincan,

I'm still getting the same error:  `TypeError: dayIndex is undefined[Learn More] datepicker.js.xhtml:214:17`

![screenshot from 2019-01-28 11-49-50](https://user-images.githubusercontent.com/1592273/51840268-c0960d00-22f2-11e9-8128-13fe2e35e5b6.png)


My local primefaces copy points to the following commit:

```
commit 6abcf67ff0fdc73027b9112e93fe692b1292a2ec (HEAD -> master, origin/master, origin/HEAD)
Author: mertsincan <sincan.mert@gmail.com>
Date:   Mon Jan 28 09:39:43 2019 +0300

    Fixed #4473

```

Does the [sample application](https://github.com/primefaces/primefaces/files/2799567/primefaces-test.zip) works for you?

**Comment by melloware** [comment]
@mertsincan the sample is still broken for me.  I think what the component needs is to detect if the PrimeFaces.locale is not defined in the JS that it falls back to "en_US" and logs a warning to the console.

```javascript
    configureLocale: function() {
        var localeSettings = PrimeFaces.locales[this.cfg.locale];

        if(localeSettings) {
            var locale = {};
            for(var setting in localeSettings) {
                locale[setting] = localeSettings[setting];
            }
            
            this.cfg.locale = locale;
        }
    },
```

**Comment by mertsincan** [comment]
@rmpestano and @melloware Please try again ;) Fix; https://github.com/primefaces/primefaces/commit/8417e00ac8bd9304110117b1026742aaba0dea01

**Comment by melloware** [comment]
Looks good to me but better have @rmpestano chime in too.  Since my default locale is en_US.

**Comment by rmpestano** [comment]
Yea it is working great now! thank you guys!

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for the update!
