### ISSUE TITLE
Add HumanReadablePlacement settings to barcode

### ISSUE THREAD

**Issue by SavchenkoVV** [primefaces/primefaces#448]
Barcode4J provides 3 placement:

public static final HumanReadablePlacement HRP_NONE = new HumanReadablePlacement("none");

public static final HumanReadablePlacement HRP_TOP  = new HumanReadablePlacement("top");

public static final HumanReadablePlacement HRP_BOTTOM  = new HumanReadablePlacement("bottom");

**Comment by cagataycivici** [comment]
Sorry but what is this about? Please provide more info.

**Comment by SavchenkoVV** [comment]
HRP_BOTTOM
![1](https://cloud.githubusercontent.com/assets/12197986/8237840/6a06443e-160b-11e5-9dc8-5a2b62b3e626.png)

 HRP_NONE
![2](https://cloud.githubusercontent.com/assets/12197986/8237841/6a061e46-160b-11e5-952d-acd2eba1e9af.png) 

HRP_TOP
![3](https://cloud.githubusercontent.com/assets/12197986/8237839/6a03e504-160b-11e5-8fa4-1e59edb340f8.png)

**Comment by cagataycivici** [comment]
Ok, got it.

**Comment by cagataycivici** [comment]
Care to make a pull request?

**Comment by huds8n** [comment]
It would be an excellent option

**Comment by erickdeoliveiraleal** [comment]
eg 
public class EAN13Generator implements BarcodeGenerator {
	public void generate(CanvasProvider canvasProvider, String value) throws IOException {
		EAN13Bean bean = new EAN13Bean();
		bean.setMsgPosition(HumanReadablePlacement.HRP_TOP);
		bean.generateBarcode(canvasProvider, value);
	}
}

**Comment by tandraschko** [comment]
@erickdeoliveiraleal a PR is welcome here!

**Comment by melloware** [comment]
PR submitted.  Added new "hrp" attribute so you can set hrp="top" for example.
