### ISSUE TITLE
Upload functionality is not working with tabs

### ISSUE THREAD

**Issue by banmani** [primefaces/primefaces#4481]
## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior
In the first click of tab only p:fileUpload functionality should work
And Calendar pop-up also should work

## 3) Actual behavior
After Navigating the tab p:fileUpload functionality is not working.
We have to click on the tab 2nd time or Navigate back to any other tab and coming back then only fileUpload functionality is working
If i enable <h:head/> tag in first click only p:fileUpload is working but  calenar pop-up is not showing. It is flickering

## 4) Steps to reproduce
1) Open MainTest.xhtml page
2) Click on Second Tab and upload any excel file. File is not uploading
3) Click on the same tab again or Navigate to first tab and come back to the same tab and upload the file. It is working
4) In the subTest.xhtml file if i add <h:head/> then first click on Second Tab only fileUpload is working
5) After enabling the <h:head/> tag navigate to Thirdtab and come back to second tab and go back to third tab Calendar pop-up is not showing

## 5) Sample XHTML
[Xhtml Files.zip](https://github.com/primefaces/primefaces/files/2811930/Xhtml.Files.zip)

## 6) Sample bean

[Bean.zip](https://github.com/primefaces/primefaces/files/2811923/Bean.zip)

**Comment by melloware** [comment]
@banmani can you please take your examples and make them runnable so we can debug?  This should be easy to do just clone this project: https://github.com/primefaces/primefaces-test

You can execute the sample with "mvn jetty:run-exploded" command and hit http://localhost:8080/primefaces-test to run the page.

**Comment by tandraschko** [comment]
I did the following:
- add h:body
- clean h:head (to make it clean as possible and to test PF ;))
- make the handleFileUpload public (the exception was that the method cant be resolved)
- "click second tab", upload something and make a system.err.println into the handleFileUpload method
