### ISSUE TITLE
Global configured partial submit does not apply on default events, without defined p:ajax

### ISSUE THREAD

**Issue by krishnakittu** [primefaces/primefaces#4483]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0-SNAPSHOT 
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
Only query value or component to be posted to the server side
...

## 3) Actual behavior
Autocomplete component on complete method its posting complete form.
![screenshot from 2019-01-31 12-17-47](https://user-images.githubusercontent.com/2696719/52036220-9f335c00-2552-11e9-840f-48e1af3cb3b9.png)

..

## 4) Steps to reproduce
It was easily replicated in show case.
.. 

## 5) Sample XHTML
Not needed
..

## 6) Sample bean
Not Needed
..

**Comment by tandraschko** [comment]
partialSubmit is deactivated per default, see the user guide.

**Comment by krishnakittu** [comment]
@tandraschko 
For autocomplete component on query event Partial submit is not working. I added the Context param(**Primefaces.SUBMIT**) as per documentation. But still the full form is submitting.

**Comment by tandraschko** [comment]
Yep seems like that the global partialSubmit is not applied.
This works:
`<p:ajax event="query" partialSubmit="true" />`

It should even work if you activate it in web.xml and only add:
`<p:ajax event="query"  />`

**Comment by tandraschko** [comment]
Currently the primefaces.SUBMIT param is only evaluated for scripts generated on the server side (like p:ajax or p:commandButton).
Some components requires a default ajax event to get data from the server (p:autoComplete query, p:datatTable paginate, ..., ...), which ignores the global config.

New feature as it never worked for this case. As we already have a RC2, i will do it for 7.1.

**Comment by tandraschko** [comment]
Fixed ;)
