### ISSUE TITLE
TabView: validation failures not handled correctly with AJAX and skipChildren="false"

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#4485]
When you have a `<p:tabView>` with an `<p:ajax skipChildren="false">`, validation of all components inside the tabView will happen. If validation fails, model is not updated and listeners/setters are not called. so far, this is expected behavior. However, the active tab on client-side (in the browser) changes and thus client and server are not in sync regarding `activeIndex`, which is probably a bug!

Due to the tab-change in browser, validation-failure messages might be overlooked by the user, as they are likely to be shown in an inactive tab.

## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior
On validation failures, tab-switch should not happen at all (neither server nor client).

## 3) Actual behavior
Server state stays correct, but browser-state of widget changes.

## 4) Steps to reproduce
 [primefaces-test-4485.tar.gz](https://github.com/primefaces/primefaces/files/10390123/primefaces-test-4485.tar.gz)

Run demo and change tabs without entering any values in the input fields.
First change from tab "One" to "Two" will trigger validation failure but validation message won't be shown as tab "Two" will be shown to the user.

## 5) Sample XHTML

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>

    <h:body>

    <h:form id="theForm">

      <p:tabView id="myTabs" widgetVar="myTabs"
                 activeIndex="#{testViewCdi.activeIndex}"
                 dynamic="true" cache="false">
        <p:ajax event="tabChange" skipChildren="false"
                listener="#{testViewCdi.tabChangedListener}"
                oncomplete="console.log('activeIndex=' + PF('myTabs').getActiveIndex())" />

        <p:tab id="tabOne" title="One">
          <div>This is Tab 1!</div>
          <h:inputText id="in1" required="true" requiredMessage="in1 required!"/>
          <p:message for="in1"/>
        </p:tab>

        <p:tab id="tabTwo" title="Two">
          <div>This is Tab 2!</div>
          <h:inputText id="in2" required="true" requiredMessage="in2 required!"/>
          <p:message for="in2"/>
        </p:tab>

      </p:tabView>

    </h:form>

    </h:body>
</html>

## 6) Sample bean

    @Named
    @ViewScoped
    public class TestViewCdi implements java.io.Serializable {

        private int activeIndex;
    
        @PostConstruct  
        public void init() {
            activeIndex = 0;
        }

        public void tabChangedListener(TabChangeEvent event) {
            System.out.println("Tab changed to " + event.getTab().getId());
        }

        public int getActiveIndex() {
            return activeIndex;
        }

        public void setActiveIndex(int idx) {
            System.out.println("setting activeIndex to " + idx);
            this.activeIndex = idx;
        }   
    }

**Comment by tandraschko** [comment]
Enhancement as we never implemented this behavior.
Would be great if you can work on a PR.

Maybe wizard is also a better component to use for this case?!

**Comment by matinh** [comment]
> Would be great if you can work on a PR.

I had a look at `tabview.js`. I guess I'd have to start in the `select` function and create an AJAX request there before changing the active tab. However, I'm totally new to PrimeFaces component development and am thus not able to create a PR for this enhancement.

If you could give me some hints how to implement this or point me to some documentation, maybe I could have another look at it.

> Maybe wizard is also a better component to use for this case?!

I was thinking of this, but my use-case is not really a typical wizard use-case. TabView seems more suitable for me. (I just switched from RichFaces to PrimeFaces and the RichFaces TabPanel did exactly what I needed.)

**Comment by melloware** [comment]
This was implemented in #9054

**Comment by matinh** [comment]
Sorry, but this is NOT fixed. I just tried the reproducer with PrimeFaces 12.0.0 and the original behavior is still reproducible.
Please reopen!

The related issues #8659 and #9054 are a step towards a solution, but it seems for this use-case, they is not enough.

**Comment by melloware** [comment]
@matinh did you set `focusOnError="true"` on your TabView?   Can you please provide an actual PrimeFaces Test reproducer and not just snippets of code?  I can't reproduce.

I will re-open once a PrimeFaces Test reproducer is provided that shows the issue.

**Comment by matinh** [comment]
@melloware I tried with and without `focusOnError="true"` without much difference. The problem is even reproducible on the current show-case: https://www.primefaces.org/showcase/ui/panel/tabView.xhtml
Scroll to "Events and Validation", enter "foo" for the firstname and "b" for the lastname (which triggers a validation failure). Now don't hit the Save-button but switch to another tab immediately. You won't be notified of any validation error in the first tab.

If you still can't reproduce it, I'll submit another reproducer.

**Comment by melloware** [comment]
@matinh I am using the showcase and to me its working exactly as I would expect.  

If you enter data and switch tabs you should NOT be notified as you have not submitted the form.   So because those two fields are required in your scenario you would NEVER be able to switch off the first tab until the fields are filled out properly.  That would be unexpected behavior.  

So to be clear are you saying in the Showcase example if you were to just go to the page and switch to tab 2 you would expect both fields to show "Required" validation and the tab to not change?

**Comment by matinh** [comment]
@melloware Ok, the topic is a bit more complex. So simple things first: the Showcase works as expected. My previous expectations were not completely correct. Sorry for this one.

In my previous comment I really meant (as you stated), if you go to the page and switch to tab2 an validation error should happen for the _lastname_ input, due to the nested `<p:ajax>`. What I was missing is, that there was no update of the `<p:tabView>` or its containing form.

When I add a corresponding `update`-attribute, the validation error is correctly signaled via the `<p:tabView>`.

What is IMHO not working as expected is, if you set the `dynamic`-attribute of the `<p:tabView>` to `true`, as it is in this issue's original description. In this case, the validation-error is not signaled via the  `<p:tabView>`. What would you say? Is this a bug? Should a new issue be created for this case?

**Comment by melloware** [comment]
If you create me a reproducer showing your exact use case and then update this ticket with the exact issue and instructions that would be great.

I feel like your original description is now a bit muddled as to what the exact problem is.  So I will re-open this one once you update the description and provide a reproducer showing the issue with `dynamic="true"`

**Comment by matinh** [comment]
@melloware I created an attachment with a reproducer: [primefaces-test-4485.tar.gz](https://github.com/primefaces/primefaces/files/10390123/primefaces-test-4485.tar.gz)

I did not update the original description, as this is still the actual problem: state on server-side and in browser might get out of sync when validation-errors happen. This is also described on the XHTML page in the reproducer.

The validation-indication in the <p:tabView> header is a side-problem which was addressed by #8659 but IMHO still has problems with `dynamic="true"`. This actually confused me in my previous comments, where I lost focus on the actual problem described by this issue. So let's focus on the state-out-of-sync problem again.

If you also feel the validation-error-indication with `dynamic="true"` is a bug, we should create another issue for this one.

Can you reproduce the problem now? If so please reopen this issue.

Many thanks for your time and investigations! :smile:

**Comment by melloware** [comment]
Awesome reproducer!   OK looking at this in your second scenario adding `focusOnError="true"` fixes it as now you can't leave that first tab and the ActiveIndex is correctly in line with the server side index.  Meaning when you try to leave tab 1 it correctly returns you to Tab 1 as that is where the validation error occurs.  That was the exact use case of adding `focusOnError`.

As for the first scenario you are right it looks like with Dynamic="true" the highlighting is not happening.  Let me reopen this ticket.

**Comment by matinh** [comment]
Thanks for reopening!

The documentation for `focusOnError` says:
> Whether to focus the first tab that contains an error after form submission.

In this simple use case the behavior is now as expected, but to me this looks like a workaround and not a fix to the actual problem. Do I really have to specify `focusOnError="true"` to make the component not go out of sync between server and client?

**Comment by melloware** [comment]
I absolutely think you have to specify `focusOnError` as like you said when its a validation error the Server side prevents updating values. That is just how JSF works.  There is no way to say "update this value anyway" even though the Validation phase failed.

**Comment by matinh** [comment]
I understand your point. And I think I know how JSF works :wink:
Anyway, having client- and server state out of sync doesn't sound promising to me and needs to be fixed.
IMHO it would be better to prevent client-side from switching tab when a validation fails. Currently as I understand it, the first tab with an validation error is activated (on client-side only), which is not necessarily the same.

**Comment by melloware** [comment]
Yep I am just not sure how its possible to set the backing bean ActiveTabIndex when the ApplyValues phase is never actually reached.  Maybe someone else has some ideas on how to do this but its out of my range of knowledge without doing something hacky.

**Comment by matinh** [comment]
Well, I think you got me wrong. When validation failed, DO NOT change state on server. Just make sure state on client is not changed! This means the tab which was active before submit should also be active after submit.

**Comment by melloware** [comment]
Oh I see yeah this could be possible with a bunch more javascript at least on `dynamic="true"` where you can get the AJAX response and check `pfArgs.validationFailed=true`

**Comment by melloware** [comment]
@matinh I marked this as needs reproducer because its been so long since I looked at this and we went round and around I don't have a reproducer of what the ACTUAL issue is.  I think we landed on when `dynamic="true"` and you get a server side validation error you want the tab to remain on the tab you were on correct?  A reproducer would be great.

**Comment by matinh** [comment]
Hi @melloware!
There is already a reproducer attached, reference here:  https://github.com/primefaces/primefaces/issues/4485#issuecomment-1378401749_
Just unpack the file with `tar xzvf primefaces-test-4485.tar.gz`, change to new directory and run `mvn jetty:run-exploded`.
After this, point your browser to http://localhost:8080/primefaces-test/ and you should see a test-page with detailed explanation.

You are right, what I expected was, when validation failure occurred, tab switching on client-side (in browser) should be prevented, as it is also prevented on server-side. IMHO server and client (browser) should always be in sync!

**Comment by melloware** [comment]
@matinh thank you i will take another look at this.

**Comment by melloware** [comment]
@matinh can you try this version I have monkeyPatched:
[pf-4485.zip](https://github.com/primefaces/primefaces/files/13875169/pf-4485.zip)

Using `dynamic` it now keeps you on the tab you were trying to leave and highlights the tab you were going to in RED.

![image](https://github.com/primefaces/primefaces/assets/4399574/c71e1d41-d7ae-471a-8f11-4b5a6b4c93d9)


However what I don't understand is how you will EVER be able to click on Tab2 as the validation error is coming from it trying to dynamically load Tab 2??

**Comment by melloware** [comment]
AHHH I thought you would say that but it DOESN'T. The validation error occurs because the AJAX is loading Tab2 and that is what is returned in the AJAX saying "Tab2 is invalid".  If you look at the network traffic you are dynamically loading Tab2 and that is what is saying it is in error?

**Comment by melloware** [comment]
OK this version highlights Tab 1 instead but the real issue is that is not what is returned in the AJAX call.
[pf-4485-2.zip](https://github.com/primefaces/primefaces/files/13876156/pf-4485-2.zip)

**Comment by matinh** [comment]
I tested your second version. The non-dynamic version seems to work as I expected.

The dynamic-version works partly. It has problems when you do the following:
1) try to switch to tab2 (this fails, as validation fails)
2) enter some value in text input
3) try to switch to tab3 again.
This time switch should work, but it doesn't.

And regarding you previous comment about validation:
> The validation error occurs because the AJAX is loading Tab2 and that is what is returned in the AJAX saying "Tab2 is invalid".

This is not completely correct. Looking at the answer it contains the following tags:
* `<update id="theFirstForm:myTabs1">`: the actual HTML update for the tabs
* `<update id="j_id1:javax.faces.ViewState:0">`: the update of the JSF view-state
* `<extension ln="primefaces" type="args">{&#34;validationFailed&#34;:true}</extension>`: The PrimeFaces information that validation failed. It doesn't say which component failed, or do I miss something?

The request leading to the above was a tab-switch with empty text field, containing the following data:
```
	"javax.faces.partial.ajax": "true",
	"javax.faces.source": "theFirstForm:myTabs1",
	"primefaces.skipchildren": "false",
	"javax.faces.partial.execute": "theFirstForm:myTabs1",
	"javax.faces.partial.render": "theFirstForm:myTabs1",
	"javax.faces.behavior.event": "tabChange",
	"javax.faces.partial.event": "tabChange",
	"theFirstForm:myTabs1_contentLoad": "true",
	"theFirstForm:myTabs1_newTab": "theFirstForm:myTabs1:tabTwo",
	"theFirstForm:myTabs1_tabindex": "1",
	"theFirstForm": "theFirstForm",
	"theFirstForm:myTabs1:in1a": "",
	"theFirstForm:myTabs1_activeIndex": "1",
	"javax.faces.ViewState": "3144736310811448927:6398766277948733762"

````
So IMHO there is no information, neither in request nor in response, which component actually failed.

One more thing: In non-dynamic mode I noticed a flicker on switching tabs with validation failure. It seems tab-switch on client-side is not prevented but reverted. The result is the same but this might lead to potential problems. If possible, I'd prefer completely preventing the switch.

Thanks for looking into this!

**Comment by matinh** [comment]
@melloware 
> Dynamic mode submits the form but loads 1 tab so you have no idea whether the error is on Tab1 or Tab5 or Tab99 because that is the whole point of Dynamic...to load a single tab for performance.

If what you say is correct, than you should know the validation error is in the current tab, as the state and thus the active tab won't change (at least on server).

Sorry, I currently don't have the time for closer look at the PrimeFaces code (busy with other things). Maybe I can come up with a patch some time later on...

**Comment by melloware** [comment]
Yes I can mark the current tab in violation like you saw in my demo above the only thing it won't have is "XX field is required" etc because Tab 1 is not reloaded I am only marking it in violation.

**Comment by matinh** [comment]
Ahh! So if I get you right, the problem with the dynamic tab is only the update of the <p:message> for the failed component?
Well, this would have to be handled on the server side.

But as I said, I can't have a closer look at the moment... If you are stuck, please leave it open and I'll try to investigate later on.

**Comment by melloware** [comment]
Cool I will assign it to you.

**Comment by matinh** [comment]
I finally got a chance to have look at this issue again. Unfortunately I'm not able to fix the issue with my limited knowledge of PrimeFaces component development. It seems, the component was simply not designed to stay in sync with server. Tab-Switching happens 'onclick' in Browser, regardless of the server response :(

**Comment by melloware** [comment]
@matinh yes I agree.  With Dynamic tab rendering there is just no way to properly highlight the Tab that has failures etc.
