### ISSUE TITLE
columnToggler: After dataTable data refresh resorts back to displaying all columns

### ISSUE THREAD

**Issue by NOTiFYcouk** [primefaces/primefaces#4492]
## 1) Environment
- PrimeFaces version: primefaces-7.0.RC2
Does it work on the newest released PrimeFaces version? Version? No primefaces-7.0.RC2
Does it work on the newest sources in GitHub? No
Application server + version: JBoss WildFly 15.0.1.FINAL (EE8)
Affected browsers: Google Chrome/Safari

## 2) Expected behaviour

1. On start-up displays all columns in dataTable.
2. Use columnToggler to select columns to display.
3. Using 'selectCheckboxMenu' to filter results returned from the database. 
4. Populates dataTable with new filtered data.
5. Only columns selected in # 2 are displayed. 
..
...

## 3) Actual behaviour

On start-up displays all columns in dataTable = OK
Use columnToggler to select columns to display = OK
Use Pagination to navigate through table data = OK retains columns selected
Change Pagination size = OK retains columns selected

Using 'selectCheckboxMenu' to filter results returned from the database. Returns new resultSet
Populates dataTable with new data.

All columns (in the dataTable) are displayed again. 
..

## 4) Steps to reproduce

Have a dataTable populated with enough rows to paginate and enough columns to fill the page and a filter mechanism to filter data returned. Select half of the columns available and select one category that returns a small result set. Change 'filter" to select all or no filter. Observe all columns are now displayed. 
..
.. 

## 5) Sample XHTML
`<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<f:view>
    <head>
    </head>

    <h:body>
        <h:form id="formMotorcycles">
            <h:outputLabel for="selectCheckboxMenuManufacturer" value="Manufacturer:"/>
            <p:selectCheckboxMenu id="selectCheckboxMenuManufacturer"
                                  value="#{manufacturerController.selectedManufacturers}"
                                  valueChangeListener="#{motorcycleController.selectedManufacturerChanged}"
                                  converter="omnifaces.SelectItemsConverter"
                                  label="Manufacturer"
                                  multiple="true"
                                  filter="true"
                                  filterMatchMode="startsWith"
                                  panelStyle="width:250px">
                <f:selectItems value="#{manufacturerController.allManufacturers}"/>
                <p:ajax event="change" process="@this"
                        update="tabHomeView:formMotorcycles:dataTableMotorcycles"></p:ajax>
            </p:selectCheckboxMenu>

            <p:dataTable value="#{motorcycleController.allMotorcycles}" style="width:100%" var="motorcycle" border="1"
                         id="dataTableMotorcycles"
                         rows="20"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15,20,25,30,35,40,45,50"
                         resizableColumns="true"
                         draggableColumns="true"
                         multiViewState="true"
                         scrollWidth="100%">

                <f:facet name="header">
                    <p:commandButton id="columnTogglerMotorcycles" type="button" value="Columns" style="float:right"
                                     icon="pi pi-align-justify"/>
                    <p:columnToggler datasource="dataTableMotorcycles" trigger="columnTogglerMotorcycles"/>
                </f:facet>

                <p:column sortBy="#{motorcycle.manufacturer}" headerText="Manufacturer">
                    <h:outputText value="#{motorcycle.manufacturer}">
                    </h:outputText>
                </p:column>

                <p:column sortBy="#{motorcycle.model}" headerText="Model">
                    <h:outputText value="#{motorcycle.model}">
                    </h:outputText>
                </p:column>

                <p:column sortBy="#{motorcycle.year}" headerText="Year">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.year}">
                            <f:convertDateTime pattern="yyyy"/>
                        </h:outputText>
                    </div>
                </p:column>

                <p:column headerText="Colours">
                    <div style="text-align: center;">
                        <p:selectOneMenu id="selectOneMenuColour" value="#{motorcycleController.currentColour}"
                                         converter="omnifaces.SelectItemsConverter"
                                         rendered="${motorcycle.colours.size() > 0}"
                                         valueChangeListener="#{motorcycleController.selectedColourChanged}">
                            <f:selectItems value="#{motorcycle.colours}" var='colours'
                                           itemValue="#{colours.colour}"
                                           itemLabel="#{colours.colour}"/>
                            <p:ajax event="valueChange" execute="@this" update=""></p:ajax>
                        </p:selectOneMenu>
                    </div>
                </p:column>

                <p:column headerText="In Production">
                    <div style="text-align: center;">
                        <h:outputText value="Yes" rendered="#{motorcycle.inProduction}"></h:outputText>
                        <h:outputText value="No" rendered="#{!motorcycle.inProduction}"></h:outputText>
                    </div>
                </p:column>

                

                <p:column sortBy="#{motorcycle.engine.type}" headerText="Engine Type">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.type}">
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.displacement}" headerText="Capacity">
                    <f:facet name="header">
                        <h:outputText value="Engine Capacity"/>
                    </f:facet>
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.displacement}">
                            <f:convertNumber maxFractionDigits="0"/>`
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.capacityUnit}" headerText="Capacity Unit">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.capacityUnit}">
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.bore}" headerText="Bore">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.bore}">
                            <f:convertNumber maxFractionDigits="0"/>
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.boreMeasurement}" headerText="Bore Measurement">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.boreMeasurement}">
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.stroke}" headerText="Stroke">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.stroke}">
                            <f:convertNumber maxFractionDigits="0"/>
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.strokeMeasurement}" headerText="Stroke Measurement">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.strokeMeasurement}">
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.distribution}" headerText="Distribution">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.distribution}">
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.maxiumPowerHp}" headerText="Power HP">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.maxiumPowerHp}">
                            <f:convertNumber maxFractionDigits="0"/>
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.maxiumPowerKilowatt}" headerText="Power Kw">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.maxiumPowerKilowatt}">
                            <f:convertNumber maxFractionDigits="0"/>
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.maxiumPowerRpm}" headerText="Power RPM">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.maximumTorqueRpm}">
                            <f:convertNumber maxFractionDigits="0"/>
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.maximumTorque}" headerText="Torque">
                    <f:facet name="header">
                        <h:outputText value="Torque"/>
                    </f:facet>
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.maximumTorque}">
                            <f:convertNumber maxFractionDigits="0"/>
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.maximumTorqueUnit}" headerText="Torque Unit">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.maximumTorqueUnit}">
                        </h:outputText>
                    </div>
                </p:column>

                <p:column sortBy="#{motorcycle.engine.maximumTorqueRpm}" headerText="Torque RPM">
                    <div style="text-align: center;">
                        <h:outputText value="#{motorcycle.engine.maximumTorqueRpm}">
                            <f:convertNumber maxFractionDigits="0"/>
                        </h:outputText>
                    </div>
                </p:column>

            </p:dataTable>
        </h:form>
    </h:body>
</f:view>
</html>
`
..

## 6) Sample bean

The method in Manufacturers Controler Bean:

`public List<String> getAllManufacturers() {
        //LOGGER.info(">>>>> getAllManufacturers motorcyclesEJB {}", motorcyclesEJB);
        //LOGGER.info(">>>>> getAllManufacturers motorcyclesList = {}", motorcyclesList.size());

        List<String> manufacturerList = manufacturerEJB.getAllManufacturers();
        LOGGER.info(">>>>> getAllManufacturers manufacturerList = {}", manufacturerList.size());

        return manufacturerList;
    }`

The method in Motorcycle  Controler Bean:
` public List<MotorcycleFields> getAllMotorcycleFields() {
        if (this.motorcycleFieldsList == null) {
            LOGGER.info(">>>>> getAllMotorcycles motorcycleFieldsList = {}", this.motorcycleFieldsList);
            motorcycleFieldsList = motorcyclesEJB.getAllMotorcyclesFields();
        } else {
            LOGGER.info(">>>>> getAllMotorcycles motorcycleFieldsList = {}", this.motorcycleFieldsList.size());
        }

        return motorcycleFieldsList;
    }`

The method in the Manufacturers EJB:

`@Produces
    public List<String> getAllManufacturers() {

        Query query = this.mongoDbEntityManager.createQuery("FROM Manufacturer m ORDER BY m.manufacturer");
        List<Manufacturer> manufacturerList = query.getResultList();

        List<String> manufacturers = manufacturerList.stream().map(x -> x.getManufacturer()).collect(Collectors.toList());

        manufacturers.forEach(manufacturer -> System.out.println(manufacturers));

        return manufacturers;
    }`

The method in the Motorcycle EJB:

`@Produces
    public List<Motorcycle> getAllMotorcycles() {

        LOGGER.info("***** 1 getAllMotorcycles motorcycleManufacturers = {}", (Object) MotorcycleController.motorcycleManufacturers);

        StringBuilder stringBuilderSQL = new StringBuilder(MotorcyclesEJB.ZERO);
        stringBuilderSQL.append("FROM Motorcycle m");

        if (MotorcycleController.motorcycleManufacturers != null) {
            LOGGER.info("***** 2 getAllMotorcycles motorcycleManufacturers length = {}", MotorcycleController.motorcycleManufacturers.length);

            if (MotorcycleController.motorcycleManufacturers.length > MotorcyclesEJB.ZERO) {
                stringBuilderSQL.append(WHERE);
                for (int x = MotorcyclesEJB.ZERO; x < MotorcycleController.motorcycleManufacturers.length; x++) {
                    LOGGER.info(">>>>> selectedManufacturerChanged motorcycleManufacturers =  {}", MotorcycleController.motorcycleManufacturers[x]);

                    stringBuilderSQL.append(MotorcyclesEJB.MANUFACTURER);
                    stringBuilderSQL.append(MotorcyclesEJB.EQUALS);
                    stringBuilderSQL.append(MotorcyclesEJB.SINGLE_QUOTE);
                    stringBuilderSQL.append(MotorcycleController.motorcycleManufacturers[x]);
                    stringBuilderSQL.append(MotorcyclesEJB.SINGLE_QUOTE);

                    if ((x + 1) < MotorcycleController.motorcycleManufacturers.length) {
                        stringBuilderSQL.append(MotorcyclesEJB.OR);
                    }
                }
            }
        }
        LOGGER.info(">>>>> getAllMotorcycles stringBuilderSQL = {}", stringBuilderSQL.toString());

        Query query = this.mongoDbEntityManager.createQuery(stringBuilderSQL.toString());
        List<Motorcycle> motorcycleList = query.getResultList();
        //LOGGER.info(">>>>> getAllMotorcycles motorcycleList = {}", motorcycleList.size());

        // Assign new motorcycleList to public static motorcycleList in MotorcycleController
        MotorcycleController.motorcycleList = motorcycleList;

        return motorcycleList;
    }`
..

**Comment by melloware** [comment]
Smaller reproducible test case: 
[pf-4492.zip](https://github.com/primefaces/primefaces/files/2824464/pf-4492.zip)

1. Navigate to http://localhost:8080/primefaces-test/test.xhtml
2. Use Column Toggler to remove some columns.
3. Use the paginator to page to the next page.
4. Now press the Update button you will see the columns re-appear.

**Comment by mertsincan** [comment]
Could you please try it after adding <p:ajax event="toggle" />? Please see; https://github.com/primefaces/primefaces/issues/3044#issue-279257719

**Comment by NOTiFYcouk** [comment]
Thanks. That appears to have fixed it. 

Have added and removed columns, moved and resorted them. Added and removed Manufacturers and repeated previous.

Be good to update the example in the Showcase. That's always my first port of call when using a component for the first time.

**Comment by mertsincan** [comment]
Thanks a lot for the update and your suggestion. We can add a demo for such issues. Thanks again ;)
