### ISSUE TITLE
Tag Library: XSD validation errors

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#4493]
Using Eclipse it is validating the tag library XML against the XSD.  It is reporting the whole document is invalid because the order of the elements.

**Current:**
```xml
 <tag>
        <tag-name>captcha</tag-name>
        <description><![CDATA[Captcha is a form validation component based on Recaptcha API.]</description>
```
**Expected:**
```xml
 <tag>
        <description><![CDATA[Captcha is a form validation component based on Recaptcha API.]</description>
        <tag-name>captcha</tag-name>
```

Basically the order of description of tag-name is backwards.  On PrimeFaces extensions they are in the correct order and the document is valid. Adding @Rapster .

**Comment by Rapster** [comment]
Before make the changes, I would have ping the JSF guys to make sure if it makes sense to define an order. IMO, It's been working so far for many years, so my guess is that the XSD is not properly well defined

**Comment by melloware** [comment]
Well regardless of what JSF team says the scheme is definitely defined with order. My guess is a lot of the tools are forgiving but it definitely was not validating in XML Spy or in Eclipse so I feel like this is the right change.

**Comment by Rapster** [comment]
I understood an order was set, but my question is does is make sense? It's not up to PF team anyway, but asking would have been nice though. At the end, I kinda don't care but reading the tagname first feels more natural than the other way around. Whatever floats your boat 😉
