### ISSUE TITLE
Include OSGi headers in MANIFEST.MF for all builds

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#4498]
OSGi headers are only included when the project is built with the `release` profile. These headers should be included in all builds.

**Comment by Rapster** [comment]
Since Tika is no longer an optional/required dependency (only used for unit tests though), does it mean we need to remove this line from pom.xml:
https://github.com/primefaces/primefaces/blob/0f49b1c0634b85018d07295f32afbb6e142f41e8/pom.xml#L441

**Comment by tandraschko** [comment]
yup
