### ISSUE TITLE
fileUpload breaks with single quote inside validation messages

### ISSUE THREAD

**Issue by forguesr** [primefaces/primefaces#45]
With PF 4.0 : Single quotes are not escaped and it makes JS crash when displaying a message.  

Can be reproduced with :

```
<p:fileUpload
  fileUploadListener="#{fileUploadView.handleFileUpload}"
  mode="advanced"
  multiple="true"
  sizeLimit="100000" 
  fileLimit="3" 
  allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
  invalidSizeMessage="Something with quote ' "
  invalidFileMessage="Something with quote ' "
  fileLimitMessage="Something with quote ' "
  messageTemplate="{name} {size} ' ">
</p:fileUpload>
```

Probably related to https://code.google.com/p/primefaces/issues/detail?id=5593 and https://code.google.com/p/primefaces/issues/detail?id=6532.

**Comment by cagataycivici** [comment]
Have you tried with 5.2? 4.x is not supported anymore.

**Comment by sudheerj** [comment]
I'am not able to replicate the issue on latest showcase(5.3 snapshot)
