### ISSUE TITLE
Add default icon for p:confirm

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#450]
See the following minimal example, maybe the "alert" icon would be more appropriate instead of the plain "default" icon (which is the caret in our situation):
# Minimal Example
## page.xhtml

``` html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:view>
        <h:head/>
        <h:body>
            <h:form>
                <p:commandButton>
                    <p:confirm/>
                </p:commandButton>

                <p:confirmDialog global="true"/>
            </h:form>
        </h:body>
    </f:view>
</html>
```
## Result

![global-confirm-dialog-default-icon](https://cloud.githubusercontent.com/assets/11957680/8226738/c12e5662-15a1-11e5-87e4-1ae69f5795be.png)

**Comment by jfgeiger** [comment]
Upon change to Primefaces 5.2.6 I learned that the default icon is set to "alert" already, Issue can be closed.

**Comment by cagataycivici** [comment]
Issue is there is no default-icon so I think we should add one :)

**Comment by ghost** [comment]
True, but as a non-global confirm dialog uses "alert" as default severity, it would either be nice not to display an icon at all or fallback to a default (perhaps "alert"? :-))

**Comment by cagataycivici** [comment]
Added alert as default.
