### ISSUE TITLE
Tree with propagateSelectionDown to false still propagates selection on update

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#4505]
## 1) Environment
- PrimeFaces version: 6.2.0
- Does it work on the newest released PrimeFaces version? Version? Not working in 7.0.RC2
- Does it work on the newest sources in GitHub? Not working
- Application server + version: Wildfly 10.1.0.Final
- Affected browsers: All

## 2) Expected behavior

When setting attribute 'propagateSelectionDown' to 'false' in checkbox selection, I expect there is no selection propagation to child nodes.

## 3) Actual behavior

If I select a node with some childs, child nodes are selected or unselected in backing model. 
This behavior can be seen on updating the tree component.

## 4) Steps to reproduce

First, check a node with some childs like this : 
![image](https://user-images.githubusercontent.com/26894018/52279246-70095a00-2959-11e9-84b3-70aa27ec4eb8.png)

After this, click on ajax button which updates the tree, it will results on this : 
![image](https://user-images.githubusercontent.com/26894018/52279378-bfe82100-2959-11e9-9802-683e089863bd.png)

## 5) Sample XHTML

```xhtml
<h:form>
	<p:tree value="#{testTreeBean.root}"
		var="data"
		selectionMode="checkbox"
		selection="#{testTreeBean.selectedNodes}"
		propagateSelectionDown="false"
		propagateSelectionUp="false">
				
		<p:treeNode>
			<h:outputText value="#{data}"/>
		</p:treeNode>
	</p:tree>
			
	<p:commandButton value="test" update="@form" />
</h:form>
```

## 6) Sample bean

```java
@Named
@ViewScoped
public class TestTreeBean implements Serializable {	
	private TreeNode root;
	private TreeNode[] selectedNodes;
	
	@PostConstruct
	public void init() {
		root = new CheckboxTreeNode();
		
		// First Level
		TreeNode fruits = new CheckboxTreeNode("Fruits", root);
		TreeNode vegetables = new CheckboxTreeNode("Vegetables", root);
		
		// Fruits Childs
		TreeNode apple = new CheckboxTreeNode("Apple", fruits);
		TreeNode strawberry = new CheckboxTreeNode("Strawberry", fruits);
		
		// Apple Childs
		TreeNode greenApple = new CheckboxTreeNode("Green Apple", apple);
		TreeNode yellowApple = new CheckboxTreeNode("Yellow Apple", apple);
	}

	public TreeNode getRoot() {
		return root;
	}

	public void setRoot(TreeNode root) {
		this.root = root;
	}

	public TreeNode[] getSelectedNodes() {
		return selectedNodes;
	}

	public void setSelectedNodes(TreeNode[] selectedNodes) {
		this.selectedNodes = selectedNodes;
	}
}
```

**Comment by melloware** [comment]
Reproducible Test Case showing the issue: 
[pf-4505.zip](https://github.com/primefaces/primefaces/files/2833589/pf-4505.zip)

Run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml
