### ISSUE TITLE
Charts - Bar - IE Style not applied 

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4507]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0.RC2
- Does it work on the newest released PrimeFaces version? Version?No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)-No
- Application server + version: NA
- Affected browsers:IE

## 2) Expected behavior
style should be uniform for all browser.

showcase example
<p:barChart model="#{chartJsView.barModel}" style="width: 100%; height: 500px;"/>

...

## 3) Actual behavior

Style not working in IE 11
IE - https://www.primefaces.org/showcase/ui/chartjs/bar/bar.xhtml
`<canvas width="1537" height="768" class="chartjs-render-monitor" id="j_idt695_canvas" style="width: 1537px; height: 768px; display: block;"></canvas>`

Working correctly in Chrome
`<canvas id="j_idt695_canvas" style="width: 100%; height: 500px; display: block;" width="1537" height="500" class="chartjs-render-monitor"></canvas>`

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
showcase example
https://www.primefaces.org/showcase/ui/chartjs/bar/bar.xhtml
..

## 6) Sample bean

..

**Comment by melloware** [comment]
@ravihariharan looks like its a know ChartsJS issue?  https://github.com/chartjs/Chart.js/issues/3378

Looks like PF just renders the canvas and ChartsJS takes it from there:
```java
        writer.startElement("canvas", null);
        writer.writeAttribute("id", clientId + "_canvas", null);
        if (style != null) writer.writeAttribute("style", style, "style");
        writer.endElement("canvas");
```
