### ISSUE TITLE
ChartsJS Support Export 

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4508]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0.RC2
- Does it work on the newest released PrimeFaces version? Version?NA
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:All
- Affected browsers:All

## 2) Expected behavior

Support for export to image
similar to https://www.primefaces.org/showcase/ui/chart/export.xhtml

...

## 3) Actual behavior

..
![image](https://user-images.githubusercontent.com/15189434/52304206-2ff9a580-2960-11e9-9813-7d0612495feb.png)

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
change showcase example similar to the old export.xhtml

`
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">
	<ui:define name="head">
		<script type="text/javascript">
			//<![CDATA[
			function exportChart() {
				//export image
				$('#output').empty().append(PF('chart').exportAsImage());

				//show the dialog
				PF('dlg').show();
			}
			//]]>
		</script>
	</ui:define>

	<ui:define name="title">
        Charts - <span class="subitem">Bar</span>
	</ui:define>

	<ui:define name="description">
        BarChart is created with a BarChartModel.
    </ui:define>

	<ui:define name="implementation">
		<p:barChart model="#{chartJsView.barModel}"
			style="width: 100%; height: 500px;" widgetVar="chart" />
		<p:commandButton type="button" value="Export" icon="pi pi-home"
			onclick="exportChart()" />

		<p:dialog widgetVar="dlg" showEffect="fade" modal="true"
			header="Chart as an Image" resizable="false">
			<p:outputPanel id="output" layout="block"
				style="width:500px;height:300px" />
		</p:dialog>
	</ui:define>

</ui:composition>
`

## 6) Sample bean

..

**Comment by melloware** [comment]
Good suggestion.  Just submitted PR with the fix.  It now works identical to the old Charts exportAsImage() function.
