### ISSUE TITLE
RangeSlider not updating values on submit

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4510]
Reported By PRO User;
> You can try on the showcase page; change the range slider to new value and try to submit: values on the 
> backing bean are not updated.
> 
> The issue is present also on other slider in the same page.

**Comment by mertsincan** [comment]
Hi @tandraschko, @melloware and @Rapster,

Could you please check this issue? I couldn't replicate it in elite versions.  Test case; https://www.primefaces.org/showcase/ui/input/slider.xhtml

**Comment by tandraschko** [comment]
just a showcase problem as the validation error was hidden. See:
- https://github.com/primefaces/showcase-facelift/commit/358062a9fe7ff5ac17c645bc269d8ff6919ecd92
- https://github.com/primefaces/showcase-facelift/commit/7a975691517d85b33645502dde658d9a39b5f62f
