### ISSUE TITLE
p:calendar: processUpdates / updateModel converts input with LocalDate.toString

### ISSUE THREAD

**Issue by Pillez7** [primefaces/primefaces#4512]
See forum for details, including stack trace of the calls:
https://forum.primefaces.org/viewtopic.php?f=3&t=57911

## 1) Environment
- PrimeFaces version 6.2

## 2) Expected behavior
String value in the bean should have the correct pattern.

## 3) Actual behavior
String value in the bean ignores the pattern and is created by .toString() method.

## 4) Steps to reproduce
1. open the page
2. chose a date
3. commit the form

## 5) Sample XHTML
<p:calendar
		id=..."
		value="#{cc.attrs.valueFrom}" 
		pattern="dd.MM.yyyy"
		locale="de"
		navigator="true"
		converter="#{cc.attrs.converter}"
		styleClass="..."
		disabled="..."
		required="...">
		<p:ajax ...

**Comment by tandraschko** [comment]
please provide a runnable example (both xhtml + bean), otherwise it's invalid.

**Comment by Pillez7** [comment]
I'm not sure when and if I have the time to do this because I need to finish the project for the costumer in the next weeks and month.

As I wrote in the forum the call hierachie looks like this:
- Calender(UIInput).processUpdates
- Calender(UIInput).updateModel
- ...
- ELSupport.coerceToType
- ...
- ELSupport.coerceToString
- LocalDate.ToString

Because LocalDate.toString gives a yyyy-MM-dd value, the value of the calender is in the wrong format.

The calender class should override the methods of UIInput to use the converter to get the correct String format of the input.

**Comment by melloware** [comment]
@christophs78 Can you investigate this one?  I think this is invalid but wanted to confirm.

**Comment by christophs78** [comment]
PF<=7.0 uses java-versions < 8. So PF has no OOTB-understanding of Java8-Types like LocalDate.
So the workaround for PF<=7.0 was to use a converter.
```
<p:datePicker id="popupConvertDateTime" value="#{calendarJava8View.date13}" pattern="MM/dd/yyyy">
    <f:convertDateTime pattern="MM/dd/yyyy" type="localDate" />
</p:datePicker>
```
(same for Calendar)

@Pillez7 - You bind the value of the Calendar to a String-Object? This is not supported OOTB.
see https://primefaces.github.io/primefaces/7_0/#/components/calendar?id=calendar
PF 7.1 will allow to bind java.time-Types OOTB (see https://primefaces.github.io/primefaces/7_1/#/components/calendar?id=calendar)
Is there a good argument to bind Calendar or DatePicker to a String-Object? From my perspective you should always bind to java.util.Date or (comming with PF 7.1 to something like java.time.LocalDate).
If you need the Date for some Backend-Components as a String you should be able to convert the Date-Object to a String by using SimpleDateFormat or the LocalDate-Object by using DateTimeFormatter before you call the Backend-Component.

**Comment by christophs78** [comment]
Some additional thoughts:
@Pillez7 - For binding Calendar or DatePicker to a String-Object you would need some kind of String-To-String-Converter. The method getAsObject(FacesContext fc, UIComponent uic, String value) of the converter always get´s a string as value-Parameter. (The string is sent from the client to the server.) getAsObject should convert this to something you want on the server. You want a string. (But as written before, i don´t think this is a good idea.)
@melloware - I agree to you. I also think this is invalid. It´s not a defect.

**Comment by melloware** [comment]
Marking as invalid and closing issue.
