### ISSUE TITLE
DataTable: custom global filter function 

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#4513]
.. allowing to create your own, custom global filter function.

See also: https://stackoverflow.com/questions/54543368/primefaces-datatable-multiple-keyword-search-using-global-filter

**Comment by tandraschko** [comment]
Feel free to sponsor it. The community commiters doesn't like to touch datatable :D

**Comment by tandraschko** [comment]
@jepsar could you please add a showcase page which demonstrates this globalFilter + globalFilterFunction?
So i could test my refactorings

**Comment by ebehmen** [comment]
Is the global filter executed as the last one, after applying all column filters? I want to limit the result to a  distinct value in a column but still want to show maximum number of results by applying the global filter as the last one.

**Comment by jepsar** [comment]
@ebehmen I think you want to have a look at the lazy data model
