### ISSUE TITLE
DataTable: clearFilter does not work if only globalFilter ist used

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4516]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No, 7.0RC2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: wildfly 11
- Affected browsers: FF, Chrome, ...

## 2) Expected behavior

Having a table with a globalFilter but without any column filter. I expect the global filter field to be cleared and the table to be reloaded without filter.

## 3) Actual behavior

Nothing happens because of the early exit in, 
https://github.com/primefaces/primefaces/blob/f57cfd531815afc8ac6b7edbc5d497bee5fd0ae2/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2921-L2928

## 4) Steps to reproduce

Having a table with a globalFilter but without any column filter.

The early exit was introduced with: #1818
But it seams, as it not necessary any more. Locally I do not get any failure without it. Maybe that is because of #2965?

So my suggestion would be to remove the early exit. I can provide a PR if desired.
The same would apply to the clearFilter method of TreeTable: 
https://github.com/primefaces/primefaces/blob/f57cfd531815afc8ac6b7edbc5d497bee5fd0ae2/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js#L118-L122

**Comment by tandraschko** [comment]
@mertsincan WDYT?

**Comment by mertsincan** [comment]
@OBreidenbach, Could you please attach a PR for this issue? Thanks a lot!
