### ISSUE TITLE
OverlayPanel: OverlayPanel with show effet open with not visible content when doubleclick on trigger

### ISSUE THREAD

**Issue by bvandaele** [primefaces/primefaces#4517]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? not working (6.2)
- Does it work on the newest sources in GitHub? not working
- Application server + version: Wildfly 10.1.0
- Affected browsers: Firefox 65, Chrome 72, IE 11

## 2) Expected behavior

When double clicking on overlay panel trigger element, the overlay panel should shortly open and close on second click

## 3) Actual behavior

When double clicking, the panel open then the content become not visible.

## 4) Steps to reproduce

For an overlay panel with show effect, double click on trigger element.
on double click:
![overlay](https://user-images.githubusercontent.com/14332203/52425138-a8489e00-2afb-11e9-85ac-b11d63b31f20.PNG)

on simple click:
![overlay2](https://user-images.githubusercontent.com/14332203/52425313-070e1780-2afc-11e9-8631-e2dd031a53a5.PNG)

## 5) Sample XHTML

```xhtml
<p:commandButton id="imageBtn" value="Basic" type="button" />
<p:overlayPanel id="imagePanel" for="imageBtn" showEffect="blind">
    test
</p:overlayPanel>
```

## 6) Sample bean

No need for sample bean

**Comment by tandraschko** [comment]
Thanks!
