### ISSUE TITLE
AutoComplete : Removal of all items at once

### ISSUE THREAD

**Issue by krishnakittu** [primefaces/primefaces#4519]
## 1) Environment
- PrimeFaces version: all

- Application server + version: all servers
- Affected browsers: all browsers

## 2) Expected behavior
Is it possible to remove all items at once in multiple items in autocomplete
...

## 3) Actual behavior
As of now we need to hold backspace key untill its cleared
..

## 4) Steps to reproduce
no need
.. 

## 5) Sample XHTML
no need
..

## 6) Sample bean
no need
..

**Comment by melloware** [comment]
Instead of CTRL+A then BACKSPACE I have holding CTRL or SHIFT+BACKSPACE as removing all items so you can do it with one keystroke.

Also added client side widget method `removeAllItems` so you can do it programmatically.

**Comment by krishnakittu** [comment]
Thanks for your Fix.
