### ISSUE TITLE
Dialog: auto heigth does not increase page height

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4524]
## 1) Environment
- PrimeFaces version: 7.2.RC2
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Wildfly 11
- Affected browsers: Firefox, Chrome

## 2) Expected behavior
If the the height of a dialog is higher than the page, the page height have to increase. Worked this way in release 6.2.

## 3) Actual behavior
The dialog only increases only to the bottom of the page. The content of the dialog gets hidden and is unreachable.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="formButton">
            <p:commandButton id="buttonShow"
                             onclick="PF('dialogVar').show()"
                             value="Open Dialog"/>
        </h:form>
        <p:dialog id="dialog"
                  positionType="absolute"
                  position="center top+30"
                  widgetVar="dialogVar"
                  visible="true"
                  closable="true"
        resizable="true">

            <h:form id="formDialog">
                <p:accordionPanel id="accordionPanel1" activeIndex="0,1,2" multiple="true" >
                    <p:tab id="tab1" title="Tab 1">
                        <p:repeat value="#{testViewCdi.list}" var="text">
                            <h:outputText value="#{text}"/><br/>
                        </p:repeat>
                    </p:tab>
                    <p:tab id="tab2" title="Tab 2">
                        <p:repeat value="#{testViewCdi.list}" var="text">
                            <h:outputText value="#{text}"/><br/>
                        </p:repeat>
                    </p:tab>
                    <p:tab id="tab3" title="Tab 3">
                        <p:repeat value="#{testViewCdi.list}" var="text">
                            <h:outputText value="#{text}"/><br/>
                        </p:repeat>
                    </p:tab>
                    <p:tab id="tab4" title="Tab 4">
                        <p:repeat value="#{testViewCdi.list}" var="text">
                            <h:outputText value="#{text}"/><br/>
                        </p:repeat>
                    </p:tab>
                    <p:tab id="tab5" title="Tab 5">
                        <p:repeat value="#{testViewCdi.list}" var="text">
                            <h:outputText value="#{text}"/><br/>
                        </p:repeat>
                    </p:tab>
                </p:accordionPanel>
                <p:commandButton id="buttonHide"
                                 onclick="PF('dialogVar').hide()"
                                 value="Hide Dialog"/>
            </h:form>
        </p:dialog>

    </h:body>
</html>
```

## 6) Sample bean
```
@Named
@RequestScoped
public class TestViewCdi {
    private List<String> list;

    @PostConstruct  
    public void init() {
        List<String> list = new ArrayList<>();
        for (int i = 1; i <= 10; i++) {
            list.add("Text " + i);
        }
        this.list = list;
    }
    public List<String> getList() {
        return list;
    }
}
```
## Image with PrimeFaces 6.2 with resized page and scroll bar visible:
![dialog6 2top](https://user-images.githubusercontent.com/11403755/52554747-189b3c00-2de8-11e9-97ca-6114e625e96e.jpg)
![dialog6 2bottom](https://user-images.githubusercontent.com/11403755/52554756-1c2ec300-2de8-11e9-9cea-567c77df9609.jpg)
## Image with PrimeFaces 7.0.RC2 without scrollbar.
![dialog7 0 rc2](https://user-images.githubusercontent.com/11403755/52554799-3ff20900-2de8-11e9-876c-de8aa4ceba91.jpg)
## Test case
https://github.com/OBreidenbach/primefaces-test/tree/PF4524

**Comment by OBreidenbach** [comment]
Ok, this happens because of #2130.
If I remove
.ui-dialog {... max-height: 100vh; max-width: 100vw; }
at
https://github.com/primefaces/primefaces/blob/14494a7cc1539b6d5b5155a90954c77ecd20f310/src/main/resources/META-INF/resources/primefaces/dialog/dialog.css#L1
everything works fine.

**Comment by melloware** [comment]
Hmm but if you remove those 100vh does it reintroduce issue #2130?

**Comment by OBreidenbach** [comment]
I guess it will reintroduce the issue #2130. But it is a false solution.

The dialog has the attribute 'fitViewport' which is set to false by default. So I expect that the dialog can exceed the viewport. That is not true anymore with (max-height: 100vh; max-width: 100vw;) set.
We are using positionType="absolute", if you shrink the window you get scroll bars, so you can scroll to close the dialog.

If positionType="fixed" is used, it is possible to shrink the windows so that the dialog can not be closed. 
So the fix for #2130 must only address the positionType="fixed". We do not use this type, so I have now opinion how it should work.
One option could be, to reset the dialog position on resize:
```
<script>
    window.addEventListener("resize", function (ev) { PF('dialogVar').resetPosition(); });
</script>
```
The solution for #2130 came @jxmai, so maybe he has a suggestion, how it should be solved.

**Comment by jxmai** [comment]
> The dialog has the attribute 'fitViewport' which is set to false by default. So I expect that the dialog can exceed the viewport.

@OBreidenbach This is a really valid point. 👍  I agree what you proposed and the previous solution did not consider this part.

However, we cannot simply remove the css since that css appeared for #2130 (unless we can address both)

---

We might think of making improvement through renderer, and if your point is valid

> If positionType="fixed" is used, it is possible to shrink the windows so that the dialog can not be closed.
So the fix for #2130 must only address the positionType="fixed".

```java

protected void encodeMarkup(FacesContext context, Dialog dialog) throws IOException {
        ...
        
        if (positionType.equals("absolute")) {
            styleClass += " ui-dialog-absolute";
        }
```

```css
.ui-dialog { position: fixed; padding: 0; overflow: hidden; display:none; max-height: 100vh; max-width: 100vw; }
.ui-dialog.ui-dialog-absolute { position: absolute; }
```

Can we think of separating the position fixed and position absolute with different css ?

```css
.ui-dialog {
padding: 0; overflow: hidden; display:none;
}

.ui-dialog.ui-dialog-fixed {
position: fixed; max-height: 100vh; max-width: 100vw; 
}
.ui-dialog.ui-dialog-absolute { position: absolute; }
```
---

but we need to consider the viewPort=True..

**so the real issue is to investigate why the dialog will be locked in the first place**. I did not dig deep enough last time. If you have a better suggestion. Feel free to share 😃

**Comment by OBreidenbach** [comment]
Actually, I do not see how #2130 is fixed at all. If you have a fixed dialog which is smaller (hight and width) than the viewport, you can still move the dialog to the lower right corner. If you then drag the lower right corner of the browser to the left / top, the closing button still disappears. 
IMHO with #2130 a regression was introduced which even does not solve the problem. So the commit should be reverted and a better solution should be found.
But maybe there is no solution for #2130. If you do put the dialog to a fixed position, it is at a fixed position and it stays there, if you change the window size. So maybe the best solution is to reset the position on a window resize:
```
<script>
    window.addEventListener("resize", function (ev) { PF('dialogVar').resetPosition(); });
</script>
```

**Comment by tandraschko** [comment]
if a bugfix destroys features, we can revert and check the original issue after the release.

**Comment by jxmai** [comment]
Since I brought it up, I will revert it  then (@tandraschko Please reopen #2130 after that).

**Comment by tandraschko** [comment]
reopnend, thanks!
