### ISSUE TITLE
p:autocomplete: multiple="true" does not hide placeholder on element added

### ISSUE THREAD

**Issue by RaduFurnea** [primefaces/primefaces#4528]
## 1) Environment
- PrimeFaces version: 6.2
- JSF: 2.2.17
- Affected browsers: all

## 2) Expected behavior

p:autocomplete with multiple enabled, expecting placeholder to disappear when element is added.

## 3) Actual behavior

Placeholder remains visible regardless of number of elements added.

## 4) Steps to reproduce

Self explanatory from the description.

## 5) Sample XHTML

`								 <p:autoComplete id="autocomplete" multiple="true" 
								 				 placeholder="Employees" value="#{sendEmailController.model.employees}"
								 				 completeMethod="#{sendEmailController.onCompleteEmployee}"
												 var="employee" itemLabel="#{employee.email}"
												 itemValue="#{employee}">
								 </p:autoComplete>`

## 6) Sample bean

Complete method queries employee list from backing bean.
Employees is a list of entities. 

Problem showcased below: 

![image](https://user-images.githubusercontent.com/40205921/52631626-efea7380-2ec7-11e9-9a22-80b22d814984.png)

Edit: applies to p:chips component also.

**Comment by Rapster** [comment]
Please follow issue template (and don't forget samples)

**Comment by RaduFurnea** [comment]
> Please follow issue template (and don't forget samples)

Updated answer.

**Comment by melloware** [comment]
I submitted Chips as a separate issue: https://github.com/primefaces/primefaces/issues/4529

**Comment by melloware** [comment]
PR submitted please review.  Its a similar fix to Chips.
