### ISSUE TITLE
Locale support for p:spinner

### ISSUE THREAD

**Issue by fcanevar** [primefaces/primefaces#453]
The spinner component (http://www.primefaces.org/showcase/ui/input/spinner.xhtml) should support different locales to enable input like "1,1" or "1.000,582" instead of "1.1".

This problem was first discovered in 2010 (http://forum.primefaces.org/viewtopic.php?f=3&t=6398), then an issue was opened in Jan 2015 (https://code.google.com/p/primefaces/issues/detail?id=7852) but still no luck.

Can anyone fix this? 

Thanks

**Comment by cagataycivici** [comment]
What options should be defined by locale?

**Comment by fcanevar** [comment]
Mainly the decimal and the thousands separator, for example you could see how this one works: http://jqueryui.com/spinner/#decimal . If you use the German locale the decimal separator changes. (try input 1.000,99 and then press '+').
Thank you very much for your prompt reply

**Comment by fante76** [comment]
Hi! I've the same problem in the web application I'm developing. I'll stay tuned for a good solution.

**Comment by cagataycivici** [comment]
I think we can get it from PrimeFaces.locales maybe. We already have decimal seperator and grouping separator. Will keep this in our radar for 5.3.

**Comment by fcanevar** [comment]
Thanks a lot, is there a roadmap for the 5.3 release?

**Comment by fcanevar** [comment]
This is the patch that I've made based on this one: http://jsf.hatemalimam.com/DailyLab/spinner/main.xhtml , keep in mind that it's tailored on our needs and that I'm not a JavaScript developer.

String.prototype.replaceAll = function(search, replace) {
    if (replace === undefined)
        return this.toString();
    else
        return this.split(search).join(replace);
}

PrimeFaces.widget.Spinner.prototype.getDecimalSeparator = function() {
    return '#{bean.decimalSeparator}';
};

PrimeFaces.widget.Spinner.prototype.getGroupingSeparator = function() {
    return '#{bean.groupingSeparator}';
};

PrimeFaces.widget.Spinner.prototype.getRegex = function() {
    return /(\d+)(\d{3})/;
};

PrimeFaces.widget.Spinner.prototype.format = function() {
    if (this.value !== null) {
        var res = (this.value+'').split('.'),
            result = res[0];
        while(this.getRegex().test(result))
            result = result.replace(this.getRegex(), '$1'+this.getGroupingSeparator()+'$2');
        if(res.length==2)
            result += this.getDecimalSeparator()+res[1];
        this.input.val(result);
    }
};

PrimeFaces.widget.Spinner.prototype.updateValue = function() {
    this.value = this.input.val().toString().replaceAll(this.getGroupingSeparator(),'').replace(this.getDecimalSeparator(), '.');
};

PrimeFaces.widget.Spinner.prototype.spin = function(dir) { 
    this.value = parseFloat(this.toFixed(Number(parseFloat(this.value ? this.value : 0) + parseFloat(this.cfg.step \* dir)), this.cfg.precision));
    this.format();
    this.input.attr('aria-valuenow', this.input.val());
};

It's tested on 5.2.6 but it should work also with previous versions.

**Comment by cagataycivici** [comment]
Thank you, we'll consider this for 5.3.

**Comment by fcanevar** [comment]
I'd say that #475 is relative to this issue and could be bundled in an unique changeset

**Comment by orange-buffalo** [comment]
Hi @cagataycivici, version 6.1 has been already released, do you have any plans to incorporate the fix?

**Comment by hreichert** [comment]
Any news on this?

**Comment by tandraschko** [comment]
As always, you can do it by yourself (and provide a PR), sponsor it via PrimeFaces PRO or just wait until the issue gets fixed and closed ;)
