### ISSUE TITLE
ChartJS Support 'hidden' on datasets

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4539]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0.RC2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: NA
- Affected browsers: NA

## 2) Expected behavior

Support 'hidden' on datasets. This will allow us to set default hidden on page load for a chart.

https://github.com/chartjs/Chart.js/issues/6069

https://github.com/chartjs/Chart.js/issues/689
https://stackoverflow.com/questions/36846177/chart-js-how-to-set-a-line-chart-dataset-as-disabled-on-load
...

## 3) Actual behavior

click on Legend works to hide a dataset.

![image](https://user-images.githubusercontent.com/15189434/52724577-9f355200-2f7d-11e9-9084-d83712362c71.png)

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by melloware** [comment]
I can take this one.  Should be easy to add.

**Comment by melloware** [comment]
Please review my PR. Thanks!

**Comment by ravihariharan** [comment]
I have tested Line and Bar chart and its working . Thanks for the fix @melloware

**Comment by AcuarioCat** [comment]
This works but there is strange behavior on multi-axis graphs. This can be seen on https://www.chartjs.org/samples/latest/charts/line/multi-axis.html, clicking one of the datasets to disable it replaces the axis scale with values from -1 to 1. Expected behavior would be either leave the axis unchanged or hide the axis.

**Comment by melloware** [comment]
@AcuarioCat I would report that on the ChartJS issues page as that issue is in the core of ChartsJS: https://github.com/chartjs/Chart.js/issues
