### ISSUE TITLE
p:panelGrid 's children must be a multiple of the option columns when layout="grid", otherwise it causes an error in the DOM.

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#454]
Hello,
if the number of children of `p:panelGrid` are not a multiple of the `columns` option when `layout="grid"`, the div:

```
<div id="form:j_idt5" class="ui-panelgrid ui-widget">
```

will not be closed !

<b>Code:</b> (columns="3" , but only 5 `<p:outputPanel>` ) [[ if 3/6/9/12/... no bug ]]

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form id="form">
            <p:panelGrid  columns="3" layout="grid">
                <p:outputPanel>1</p:outputPanel>
                <p:outputPanel>2</p:outputPanel>
                <p:outputPanel>3</p:outputPanel>

                <p:outputPanel>4</p:outputPanel>
                <p:outputPanel>5</p:outputPanel>
            </p:panelGrid>
        </h:form>
    </h:body>
</html>
```

<b>Screenshot of the error in the generated html code:</b>
![cap5](https://cloud.githubusercontent.com/assets/12255492/8243975/a4790a84-160b-11e5-8b1a-c3a4a729d207.png)

<b>Screenshot of the browser error:</b>
![cap4](https://cloud.githubusercontent.com/assets/12255492/8243828/40eecdd8-160a-11e5-8742-683bb115dee5.png)

---

the problem is located here:
PanelGridRenderer.java

that explains the problem of this issue:
https://github.com/primefaces/primefaces/issues/219

Thanks.

**Comment by cagataycivici** [comment]
This is expected, in layout mode, Grid CSS rules should be followed. Maybe should be documented better on our side though.

**Comment by RejDev** [comment]
Thank you for your reply, 
I have a proposal , why not add hidden divs to compensate ?

**Comment by cagataycivici** [comment]
We'll consider it if more users require it so won't take any action just for now.

**Comment by VsevolodGolovanov** [comment]
@cagataycivici, just spent multiple hours debugging mysterious issues:
- pe:layoutPanes not being positioned and sized properly;
- p:dialog blocked by its own modal overlay.

No errors in browser (Firefox, Chrome) consoles. All caused by this unclosed div, not obvious at all.
I don't think hidden divs are necessary, but at least not generate invalidate markup? Or just fail fast with an exception?
This mistake is pretty easy to make, but too hard to debug.

**Comment by AliTool** [comment]
Hi, 
I suggest to add a warning message when working in the development mode
this will be very helpful
