### ISSUE TITLE
Autocomplete: wrong fixed position autocomplete-panel on page with scroll and p:dialog 

### ISSUE THREAD

**Issue by astranCZ** [primefaces/primefaces#4541]
## 1) Environment
- PrimeFaces version: 7.0.RC2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 7 + 9
- Affected browsers: Chrome, Firefox, Edge...

## 2) Expected behavior
Autocomplete panel on dialog will not leave when scroll on mouse.

## 3) Actual behavior
Autocomplete panel on dialog leaves when scroll on mouse.

## 4) Steps to reproduce
On the vertical scrollbar page, I see p:dialog with autocomplete dropdown.
Unpack the autocomplete panel by clicking on the dropdown.
Scrolling the mouse on the main page and the autocomplete panel leave position.

## 5) Sample XHTML

```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body style="height: 1500px;">
	<p:commandButton value="Modal" type="button" onclick="PF('dlg2').show();" />

	<p:dialog header="Autocomplete" widgetVar="dlg2" modal="true" position="400,200" width="300" height="150">
		<h:form>
			<p:autoComplete id="dd" dropdown="true" scrollHeight="250"
				value="#{testController.autocompleteValue}" 
				completeMethod="#{testController.completeText}" >				
			</p:autoComplete>
		</h:form>
	</p:dialog>
</h:body>
</html>
```

![image](https://user-images.githubusercontent.com/15103640/52766783-95b4f400-3028-11e9-9288-2630729b424c.png)

## 6) Sample bean
```
public List<String> completeText(String query) {
	List<String> results = new ArrayList<String>();
	for (int i = 0; i < 100; i++) {
		results.add(String.format(query + " - %#04x", i));
	}
	return results;
}
```

**Comment by melloware** [comment]
This doesn't fix your issue but a temporary fix on 7.0RC2 is to set the p:dialog property to blockScroll="true".  That disables the page scrollbar while a modal dialog is being displayed.

```xml
<p:dialog header="Autocomplete" widgetVar="dlg2" modal="true" blockScroll="true">
```
