### ISSUE TITLE
Datatable : removing filter token invoke sort 

### ISSUE THREAD

**Issue by ludekz** [primefaces/primefaces#4542]
I use datatable with filter facet, that has selectCheckboxMenu. It is in the mode, that shows multiple tokens -  multiple="true" updateLabel="true" 

Example is on https://github.com/ludekz/primefaces-test.git

When I click on X to remove token

![obrazek](https://user-images.githubusercontent.com/22681931/52780590-c9087a80-304a-11e9-82ba-bb42f17118c3.png)

also sort of table is invoked:

![obrazek](https://user-images.githubusercontent.com/22681931/52780614-da518700-304a-11e9-9a4d-7c2af273f305.png)

When datatable is in lazy mode, a load function is called twice. 
Like in other cases clicking to an area of a filter components should not invoke sorting of the table.

**Comment by martin654** [comment]
Reported under a PRO account
