### ISSUE TITLE
InputNumber: value not rendered in the hidden input field

### ISSUE THREAD

**Issue by ventsislavhristov** [primefaces/primefaces#4543]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version?: No, tested on 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source): not tried, but should not be different.
- Application server + version: Tomcat 8.5
- Affected browsers: All 

## 2) Expected behavior
p:inputNumber renders two input fields - one is the visible one, with a name containing the "_input" suffix, used for user input and formatted by the autoNumeric jQuery plugin. The other field is the hidden one, with a "_hinput"; it is populated by the inputNumber widget each time the visible input changes. One form submission, it is actually the value in the hidden input which is used on the server side for processing, binding to bean properties, etc.

The issue is that on page rendering time, the InputNumberRenderer adds the "value" attribute only to the visible input and not to the hidden input. The client side InputNumber widget during its initialization copies/populates the hidden input value from the value of the visible field. 

The above behaviour can cause an issue in pages which contain numerous p:inputNumber fields - think a spreadsheet-like page content with hundreds (600-1000-more) input number fields. The initialization of all widgets then can take non-negligible time in the area of several seconds and even more if there are additional widgets on the page (in our case there are also p:selectOneMenu fields). Until the initialization is completed, the hidden inputs remain with no value set. If during this time the user performs an action which submits the whole form - for example, by using a commandButton or another ajax command - the server request contains no value for the hidden input, which results in the backing bean property being set to null. 
In an actual case due to the timing of the user action this has resulted in actual deletion of all user data in a big form (hundreds of fields) which lead to a real loss of data.
...

## 3) Actual behavior
As per my understanding, just setting the value also to the hidden input in addition to the visible input at page render time will fix this issue. 

This will need simply an update of the protected void encodeHiddenInput(FacesContext context, InputNumber inputNumber, String clientId) method in org.primefaces.component.inputnumber.InputNumberRenderer class to take the additional String valueToRender parameter and write it to the response writer, exactly the way that encodeInput method does.

..

## 4) Steps to reproduce
Inspect the generated HTML from the sample XHTML below. The hidden input is rendered as below, with no "value" attribute:
`
<input id="f:test_hinput" name="f:test_hinput" type="hidden" autocomplete="off" />
`

.. 

## 5) Sample XHTML
`<h:form id="f">
    <p:inputNumber id="test" value="10"/>
  </h:form>`
  

..

## 6) Sample bean

..

**Comment by melloware** [comment]
Have you tried this with 7.0.RC2 to see if its fixed?

**Comment by ventsislavhristov** [comment]
Just tested it with 7.0.RC2, the issue is still there. It is also fairly obvious from looking at the source code of InputNumberRenderer at https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java , lines 160-186, there is no rendering of the "value" attribute.

**Comment by melloware** [comment]
Yep I a agree with you and I see the issue.   Let's wait for @tandraschko to weigh in with his opinion but I would definitely support fixing this and can make the fix if he agrees.

**Comment by ventsislavhristov** [comment]
Thanks a lot!

**Comment by tandraschko** [comment]
Yup, why not.
