### ISSUE TITLE
DatePicker: mask attribute

### ISSUE THREAD

**Issue by mlribes** [primefaces/primefaces#4546]
The DatePicker component is much better and more flexible than Calendar, but missing masks support

**Comment by NoNamesfriend** [comment]
Are there some updates?
That's something really important for my use case.
Thank´s a lot 😀

**Comment by melloware** [comment]
Most likely you will have to either...
1. Submit a PR with the fix if you want to add the functionality yourself.
2. Sponsor it via PrimeFaces Case: https://www.primefaces.org/support/  See the "Case" section.

**Comment by tandraschko** [comment]
Feel free to sponsor it via PrimeFaces PRO if its important or implement it and provide a PR

**Comment by melloware** [comment]
Same request for PrimeReact: https://github.com/primefaces/primereact/issues/765

**Comment by melloware** [comment]
Once PR #6062 is merged I will fix this ticket.

**Comment by jepsar** [comment]
Cool! I was about to submit this issue :-)

**Comment by melloware** [comment]
I think @fanste is already using this feature and found one bug he fixed but so far it seems to work well!
