### ISSUE TITLE
Text is being saved as images by Primefaces fileUpload

### ISSUE THREAD

**Issue by evesmary** [primefaces/primefaces#455]
I have a fileuploader and inputtext in a page. When I paste a text copied from a microsoft excel file to the inputtext component, the file uploader method is being invoked. As the result, the text is being saved as an image by primefaces fileUpload component.

Using PrimeFaces 5.1, JSF 2.1 Mojarra, Spring 3.2.13 and tomcat 7. Windows 7 professional, Microsoft Excel 2013 (xlsx).
common-fileupload-1.2.2, commons-io-2.4.

Steps : Copy the cell from the excel. Single click on the cell and ctrl+c and paste the same to inputtext component.

This issue doesnot occur if you double cllick the cell and copy its text contents only.

File upload component is used to upload an image there..it is not connected with the inputtext component.
This inputtext is input value to another variable for some other use.

Please note that this issue is not reproducible in linux machines.

Update: 
I tested in Chrome41, firefox 38 and Safari. This issue occurs only in Chrome.

TestBean

```
private String name; //include its getter and setter
public StreamedContent getImage() throws IOException {
    FacesContext context = FacesContext.getCurrentInstance();
    int petId=0;
    String petSpecies = "";
    if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
        return new DefaultStreamedContent();
    }
    else {
        petSpecies = "Dog";
        FilesModel petPic = null; /*new FilesModel()*/;
        if(petPic == null){
            ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
            InputStream input;
            if(petSpecies.equalsIgnoreCase("Dog")){
                input = externalContext.getResourceAsStream("/images/dog-no-image.jpg");
            }else{
                input = externalContext.getResourceAsStream("/images/cat-no-image.jpg");
            }
            DefaultStreamedContent content = new DefaultStreamedContent(input);
            content.setContentType("image/jpeg");
            return content;
        }else{
            return new DefaultStreamedContent(new ByteArrayInputStream(petPic.getFile()));
        }
    }
}

public void handleFileUpload(FileUploadEvent event) {
    FacesContext context = FacesContext.getCurrentInstance();
    int petId = Integer.parseInt((String) event.getComponent().getAttributes().get("petId"));

        //Code to save to database

    FacesMessage message = new FacesMessage("Succesful", event.getFile()
            .getFileName() + " is uploaded.");
    FacesContext.getCurrentInstance().addMessage(null, message);
}
```

test.xhtml

```
<h:form prependId="false" id="asdf">
<p:growl id="notifications" showDetail="false" autoUpdate="true" globalOnly="true" />
<p:inputText
        value="#{testBean.name}"
        label="Spouse Name" id="spousename" >
</p:inputText>

<h:panelGrid columns="2" >
    <p:graphicImage alt="No Image" styleClass="ui-button"
        value="#{testBean.image}"
        style="height:50px;width:55px;" id="petPhotoId"
        onclick="uploadFn();" cache="false">
        <f:param name="petId" value="1" />
        <f:param name="species" value="dog" />
    </p:graphicImage>
    <p:fileUpload id="upl"  style="display:none;" 
        fileUploadListener="#{testBean.handleFileUpload}"
        mode="advanced" dragDropSupport="false" label="Change"
        auto="true" sizeLimit="5000000" fileLimit="3"
        allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
        invalidFileMessage="Invalid File Type"
        invalidSizeMessage="Invalid File Size">
        <f:attribute name="petId" value="1" />
    </p:fileUpload>
</h:panelGrid>
</h:form>
```

<script>
   function uploadFn(row){
       $('#upl_input').click()
    }
</script>

web.xml

```
 <filter>
       <filter-name>PrimeFaces FileUpload Filter</filter-name>
        <filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>
  </filter>
   <filter-mapping>
      <filter-name>PrimeFaces FileUpload Filter</filter-name>
       <servlet-name>Faces Servlet</servlet-name>
       <dispatcher>FORWARD</dispatcher>
    </filter-mapping>
```

See http://forum.primefaces.org/viewtopic.php?f=3&t=42520

**Comment by cagataycivici** [comment]
What do you mean by inputtext? Please post a minimal test.xhtml replicating this.

**Comment by evesmary** [comment]
I tested in Chrome41, firefox 38 and Safari. This issue occurs only in Chrome...inputtext means p:inputText..I have update the issue with the test code.

**Comment by cagataycivici** [comment]
Have you tried with 5.1, we can't replicate this.

**Comment by evesmary** [comment]
Was this issue tested by copying the cell instead of copy the text of a cell?

**Comment by cagataycivici** [comment]
Sorry we are unable to replicate.

**Comment by ghost** [comment]
Hi,
  i faced the above issue in chrome when copying the cell and pasting it in a textbox. But the fileupload is  getting invoked i don't know why it is invoked please provide some solutions

**Comment by ghost** [comment]
Please reopen this issue

**Comment by cnsgithub** [comment]
You should create new issue containing a MCVE (https://stackoverflow.com/help/mcve), and follow the Issue creation template. This one is based on 3-yr old code and probably has nothing to do with your problem
