### ISSUE TITLE
Consider removing resources/META-INF/resources/primefaces/dock/assets/iepngfix.htc

### ISSUE THREAD

**Issue by rdebusscher** [primefaces/primefaces#4552]
The file seems unused and has a possible conflicting License.

The Eclipse Foundation flagged this file as not compatible.

**Comment by melloware** [comment]
I would say safe to remove and check the Dock still works in the showcase.  I don't think IE specific fixes are supported much anymore so this should be OK to remove.

**Comment by rdebusscher** [comment]
@melloware Thx

I do not have IE (nor Windows) so I can not verify if the Dock works OK without this file.

**Comment by melloware** [comment]
Yep I tested on IE11 and it works fine without this file.
