### ISSUE TITLE
Carousel : Page Scroll not working (only mobile devices)

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#4553]
## 1) Environment
Primefaces official Demo and the issue is present in the GIT version also.

## 2) Expected behavior
The page should be scrollable

## 3) Actual behavior
The page is not scrollable

## 4) Steps to reproduce
1. Open the Carousel component in the Primefaces Official demo in any mobile device.
2. Try swiping up/down to scroll.
3. The page can be scrolled only when it is swiped on the area which is not covered by the carousel component (When the carousel is combined with a scroll-able datatable in each slide, this becomes tricky as the scroll in that datatable doesn't work).

Skipping the example code sections as this can be replicated in the Primefaces official demo itself.

**Comment by ghost** [comment]
A new pull request (#4554) has been created to fix this issue.

**Comment by melloware** [comment]
Nice fix. Thanks for submitting.
