### ISSUE TITLE
ChartJS: DataSet only supports List<Number> but not List<Points> 

### ISSUE THREAD

**Issue by darkcloud8027** [primefaces/primefaces#4564]
I request an enhancement for New ChartJS to add another dataset List<Points> in order to draw like time series diagram or scatter point diagram

**Comment by melloware** [comment]
I think this would be a good enhancement.

Example diagram using Point: https://www.chartjs.org/docs/latest/charts/scatter.html

**Comment by melloware** [comment]
We should also support TimePoint type: https://www.chartjs.org/docs/latest/axes/cartesian/time.html#time-cartesian-axis

So I think we should have NumberPoint and TimePoint type points.

**Number:**
{x: number, y:number}

**Time:**
{x:date y:number}

**Comment by melloware** [comment]
Please review my PR I will create a ScatterChart showcase page once the PR is accepted showing how to use it.

**Comment by melloware** [comment]
@tandraschko I think this is safe to close now.
