### ISSUE TITLE
Barcode: Code128 as PNG not scannable

### ISSUE THREAD

**Issue by wilhei** [primefaces/primefaces#4565]
When I generate a Barcode (Code128) with format=png, it cannot be scanned because the second last strip is too wide. 
![2019-02-21 09_46_10-strokesplus](https://user-images.githubusercontent.com/43268706/53156083-cc59b400-35be-11e9-9f67-66ea1b5a6146.png)

My example code:
`<p:barcode value="9710287" type="code128" format="png" height="200" width="400"/>`
`<p:barcode value="9710287" type="code128" height="200" width="400"/>`

Happens also with the newest Version.

I need to use png, as it is not possible to strech the svg-Format (with other ratio). E.g. the example image above: The svg image has a height of 200, but not a width of 400.

**Comment by tandraschko** [comment]
did you try a newer barcode4j? we likely cant fix it. but feel free to anaylze it.

**Comment by wilhei** [comment]
Yes, in my project I'm generating Barcodes with barcode4j-2.1 as png to insert them in a pdf. This generated png-barcodes (Code128) work fine. But I didn't try whether in barcode4j-2.0 this error accours.

For now I replaced my primefaces-Barcode with https://lindell.me/JsBarcode/, which seems to work fine to display them on the page.

Here, how I generate my png-barcode with barcode4j-2.1, which works fine:

```java    
   /** Create a barcode128 image with the given value
     * @param value The value the barcode128 will have
     * @param showHumanReadableText If true, the value is printed under the barcode. If false, no human readable text is printed
     * @return The generated image as file
     * @throws IOException
     */
    private static File createBarcodeImage(String value, boolean showHumanReadableText) throws IOException {

        // http://barcode4j.sourceforge.net/2.1/embedding-bean.html
        Code128Bean bean = new Code128Bean();

        //hide human readable text, if must not show
        if (!showHumanReadableText) {
            bean.setMsgPosition(HumanReadablePlacement.HRP_NONE);
        }
        
        //Open output file
        File outputFile = File.createTempFile("Barcode", ".png");
        OutputStream out = new FileOutputStream(outputFile);
        try {
            //Set up the canvas provider for monochrome PNG output 
            BitmapCanvasProvider canvas = new BitmapCanvasProvider(
                    out, "image/x-png", 300, BufferedImage.TYPE_BYTE_BINARY, false, 0);

            //Generate the barcode
            bean.generateBarcode(canvas, value);

            //Signal end of generation
            canvas.finish();
        } finally {
            out.close();
        }

        return outputFile;
    }

**Comment by melloware** [comment]
2 things.  

1. If you simply include Barcode4J 2.1 in your pom.xml does the PF component generate Code128 correctly?  Since PF doesn't bundle that JAR its up to you to provide it.

2. The only difference I see between PF code and your code is this line... We use the value 150 where you used 300.

```java
BitmapCanvasProvider bitmapCanvasProvider = new BitmapCanvasProvider(
                            out, "image/x-png", 150, BufferedImage.TYPE_BYTE_BINARY, false, orientation);
```

**Comment by melloware** [comment]
@wilhei Any updates to my questions?  Wondering what we can do to fix this?

**Comment by melloware** [comment]
Closing as no response from OP.  Will reopen if my questions are answered.
