### ISSUE TITLE
TabView: effect attribute on on demand Loading not working on first click

### ISSUE THREAD

**Issue by krishnakittu** [primefaces/primefaces#4567]
## 1) Environment
- PrimeFaces version: Primefaces Showcase
- Application server + version: no need
- Affected browsers: no need

## 2) Expected behavior
The behavior should be consistent every time.
...

## 3) Actual behavior
On First Click fold effect is not working
..

## 4) Steps to reproduce
Not needed
.. 

## 5) Sample XHTML
not needed
..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
If its reproduceable in the Showcase we need at least a url and steps to reproduce

**Comment by krishnakittu** [comment]
Steps to reproduce the issues.
1. URL: https://www.primefaces.org/showcase/ui/panel/tabView.xhtml
2. go to on-demand loading block
3. click on godfather II tab.
4. we cannot observing fold effect.
5. if you click on godfather II tab again you can observe fold effect.
