### ISSUE TITLE
Reimplemented RadioButton component

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4569]
It may have a widget and we can move all custom events from SelectOneRadio.

**Comment by melloware** [comment]
@mertsincan I don't understand this ticket.  Are you talking about reimplementing `SelectOneRadio`???

**Comment by mertsincan** [comment]
> Are you talking about reimplementing SelectOneRadio???

Yes, for Custom layout in https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml
