### ISSUE TITLE
SelectOne(Radio): Submit without value skips required-validation

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4574]
## 1) Environment
- PrimeFaces version: 7.0.RC3
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: WF 10, JSF 2.2 
- Affected browsers: ALL

## 2) Expected behavior
A selectOneRadio with a value that does not match any of the selectItems should perform a required-validation.

## 3) Actual behavior
required validation is skipped

## 4) Steps to reproduce
The value member of the bean is initialized with ``null``. Therefore it won't match any on the selectItems (values are 1 and 2) until the user actively selects one radio button. If you submit the form without clicking a radio button, the client will submit NO value for the selectOneRadio.

The PR #4447 (issue #4446) introduces a new behavior that is even different from the e.g. mojarra impl 2.1 and 2.2 (and most probably also 2.3). The decode method does not set the submitted value to an empty string anymore and therefore submitted value defaults to ``null``. That means, that the validation phase is not able to differ between "not submitted at all" and "submitted without value". Therefore it skips the required validation which breaks existing code.

The mojarra implementation uses a special constant ``com.sun.faces.RIConstants.NO_VALUE`` (which effectively is also just an empty string) which is set as the submitted value when the request params does not contain any value for the selectOneRadio. Therefore the component is able to differ between "not submitted at all" and "submitted without value".

## 5) Sample XHTML
```
<h:form>
    <p:selectOneMenu value="#{myBean,value}" required="true">
        <f:selectItem itemValue="1"  itemLabel="First" />
        <f:selectItem itemValue="2"  itemLabel="Second" />
    </p:selectOneMenu>
    <p:commandButton value="Send" process="@form" update="@form" />
</h:form>
```

## 6) Sample bean
```
@Named
@ViewScoped
public class MyBean implements Serializable {
    private Integer value = null;

    public Integer getValue() {
        return this.value;
    }

    public void setValue(integer value) {
        this.value = value;
    }
}
```

**Comment by tandraschko** [comment]
Did it work in 6.2? A PR would be great.

**Comment by tandraschko** [comment]
@cnsgithub mr security, could you assist? :D

**Comment by fanste** [comment]
Yes, it did work. The bug is definitely introduced by the patch of PR #4447. I have a working solution, but it is absolutely not nice...

The other thing is, that I'm totally unable to reproduce the bug of #4446 using a PF 6.2 as stated in that issue. So it could be enough to simply set the submitted value back to empty string. And @Gaboros should report back if the error appears again that he encountered in #4446. Then it would be helpful to have a running example.

**Comment by tandraschko** [comment]
@gaboros plz provide a sample Till tuesday, otherwise we have to revert in favor of Security

**Comment by tandraschko** [comment]
I will revert now and Open the other issue, its the better way.
Please retest after the revert
