### ISSUE TITLE
Dataview - Support for lazy loading

### ISSUE THREAD

**Issue by ngwaambe** [primefaces/primefaces#4575]
Dataview:Support for lazy loading
PrimeFaces version:7.0C3

Are they any plans to support this feature for DataView

**Comment by tandraschko** [comment]
Dont think so but you can easily sponsor features via PrimeFaces PRO or implement by yourself and provide a PR

**Comment by ngwaambe** [comment]
Ok, thanks for the information.

**Comment by ngwaambe** [comment]
Hi all. 
I created a branch from master for adding lazymodel support for dataview. Am unable to push my branch(Not allowed 403). Am I missing something.

Thanks in advance.

**Comment by melloware** [comment]
See https://help.github.com/en/articles/creating-a-pull-request for how to submit your PR from your branch.

Or: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by ngwaambe** [comment]
Hey guys,
how do I proceed from here. [Pullrequest](https://github.com/primefaces/primefaces/pull/4614)

**Comment by melloware** [comment]
@ngwaambe PF is getting ready to release 7.0 so no major changes are being pulled in right now only major bugfixes.  Right after 7.0 is released your PR will be review and probably merged for 7.1!

Thanks for your submission!

**Comment by ngwaambe** [comment]
Hey guys any info on this minor feature?

**Comment by tandraschko** [comment]
@ngwaambe Please see my comment in the PR. We need a showcase example and documentation update. Then i will apply it.

**Comment by ngwaambe** [comment]
Sure, missed that comment!

**Comment by tandraschko** [comment]
@ngwaambe Applied it now. Please provide a PR in the showcase-facelift to show that feature
