### ISSUE TITLE
TabView : Tabclose event receives null tab in the listener with jstl / c:forEach

### ISSUE THREAD

**Issue by krishnakittu** [primefaces/primefaces#4576]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: glassfish 4.1
- Affected browsers: al

## 2) Expected behavior
 Tab Close event listener should receive closed tab

## 3) Actual behavior
Receives null tab

## 4) Steps to reproduce
1. Generate 3 tabs by click on new tab button
2. Close the first tab you receive closed tab in listener.
3. Close the second tab then you receive null.

## 5) Sample XHTML

	<h:form>
		<p:commandButton id="cmdbutton" value="NewTab"
			actionListener="#{bean.buttonListener}" update=":tabView"></p:commandButton>
	</h:form>
	<p:tabView id="tabView" dynamic="true" cache="false"
		widgetVar="tabViewVar">

		<p:ajax event="tabClose" listener="#{bean.onTabClose}"
			partialSubmit="true" />

		<p:tab title="Godfather Part I">
			<h:form>
				<p:commandButton id="cmdbutton12" value="button" update=":tabView"></p:commandButton>
				<h:panelGrid columns="2" cellpadding="10">
					<h:outputText value="The story begins as Don Vito Corleone..." />
				</h:panelGrid>
			</h:form>
		</p:tab>
		<c:forEach items="#{bean.dynamicTab}" var="tab">
			<p:tab id="#{tab.id}" binding="#{tab}"></p:tab>
		</c:forEach>
	</p:tabView>

## 6) Sample bean
@ManagedBean(name="bean")
@ViewScoped
public class Bean implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private List<Tab> dynamicTab = new ArrayList<Tab>();

	public List<Tab> getDynamicTab() {
		return dynamicTab;
	}
	public void setDynamicTab(List<Tab> dynamicTab) {
		this.dynamicTab = dynamicTab;
	}
	public Bean() {
		super();
	}

	public void buttonListener(ActionEvent a){
		HtmlForm f=new HtmlForm();
		Tab tempTab = new Tab();
		String id="abc"+UUID.randomUUID().toString();
		tempTab.setId(id);
		tempTab.setTitle(id);
		tempTab.setClosable(true);
		tempTab.getChildren().add(f);
		dynamicTab.add(tempTab);
	}

	public void onTabClose(TabCloseEvent event) {
		Tab tab = event.getTab();
		dynamicTab.remove(tab);

	}

**Comment by melloware** [comment]
Have you tried PF 7.0.RC3 to see if this was already fixed? See https://github.com/primefaces/primefaces/issues/3800

**Comment by tandraschko** [comment]
i dont think that c:forEach will work in this case used with ajax.

**Comment by krishnakittu** [comment]
@melloware  i tried with 7.0.RC3 . Its not working. @tandraschko  can you please suggest any work around for this to work. Its working for the first close event  but the second one not.

**Comment by tandraschko** [comment]
use it like the datamodel sample in the showcase and google about jstl disadvantages for your knowledge.

**Comment by krishnakittu** [comment]
@tandraschko as per your suggestion i used datamodel for dynamic tabs with binding. Its giving empty tabs. 
Sample code:
**<p:tabView id="tabView" value="#{bean.dynamicTab}" var="tabvar"><p:tab binding="#{tabvar}" /> </p:tabView>**

**Comment by tandraschko** [comment]
you cant bind a tab to a datamodel var, that doesnt make any sense. binding should be avoided in generell.

**Comment by krishnakittu** [comment]
Sorry for asking repeated questions,
In my scenario tabs are generated on server side by programmatically. Can you suggest how  can i show it on UI by tabview.

**Comment by tandraschko** [comment]
Showcase / tabview / datamodel

**Comment by krishnakittu** [comment]
Hi Team
The issue was solved by adding 
**TabView t=(TabView)PrimeFacesContext.getCurrentInstance().getViewRoot().findComponent("tabView");
		t.getChildren().remove(tab);**
on the tab close event listener. May be it helps someone.
