### ISSUE TITLE
Multiple date selection in Calendar navigation

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#4577]
From drop down select the Month to April , The calendar stays back to December 2018, 

![image](https://user-images.githubusercontent.com/9069988/53298593-4061b980-3856-11e9-8c6c-be0c5c4b0ba9.png)

If i navigate using < button once, then everything works fine.

## 1) Environment
- PrimeFaces version: 7.0 RC3 Also in 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Application server + version: Tomcat 9
- Affected browsers: Firefox

**Comment by tandraschko** [comment]
no sample or steps to reproduce -> invalid

**Comment by arunvc** [comment]
[test.zip](https://github.com/primefaces/primefaces/files/2898184/test.zip)

Sample attached

Run and open http://localhost:8080/test/index.xhtml
Click the date textbox and change the month in combo

**Comment by arunvc** [comment]
Xhtml code

```
<p:calendar value="#{testing.entryDate}" maxdate="#{testing.now}" pages="3" 
      required="true" requiredMessage="Required" converterMessage="Invalid" 
      maxlength="10" size="7"  id="entryDate" pattern="dd/MM/yyyy"
      showButtonPanel="true" navigator="true" mask="true" />

```

Bean code, add getter and setter

```
@Named(value = "testing")
@ViewScoped
public class Testing implements Serializable {
    private Date entryDate = new Date();
    private Date now = new Date();
}
```

**Comment by melloware** [comment]
@arunvc why did you close this? Did you resolve the issue?

**Comment by arunvc** [comment]
> @arunvc why did you close this? Did you resolve the issue?

Since its marked invalid i created a new issue #4612
