### ISSUE TITLE
Enhancement: MOVE_SCRIPTS_TO_BOTTOM should remove script from DOM

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#4579]
Currently all widgets call remove script to remove their script from the DOM once the component executes.

For example a widget script is given an ID matching the ID of the component and  is then removed in the WidgetVar initialization.

```xml
<script id="form:popup_s" type="text/javascript">
```

If you navigate to the Showcase which is using MOVE_SCRIPTS_TO_BOTTOM you can see the entire script is left in the DOM. https://www.primefaces.org/showcase/ui/input/inputText.xhtml

Leaves this in the DOM...

```
<script type="text/javascript">var pf=window.PrimeFaces;if(pf){pf.settings.locale='en';pf.settings.validateEmptyFields=true;pf.settings.considerEmptyStringNull=true;};
pf.cw("Growl","widget_selectedThemeGrowl",{id:"selectedThemeGrowl",sticky:false,life:6000,escape:false,keepAlive:false,msgs:[]});
changeTheme = function() {pf.ab({s:"j_idt64",f:"j_idt59",u:"selectedThemeGrowl",pa:arguments[0]});};
pf.cw("InputText","widget_j_idt697",{id:"j_idt697",maxlength:-2147483648});
pf.cw("TabView","widget_j_idt700",{id:"j_idt700",effectDuration:"normal",scrollable:false});
pf.cw("AjaxStatus","widget_j_idt709",{id:"j_idt709"});</script>
```

I wonder if there is some way to give this script an ID and then remove it after the page is done initializing?

**Comment by tandraschko** [comment]
Sure

**Comment by tandraschko** [comment]
Please test! :D

**Comment by melloware** [comment]
Works perfectly. Thanks for the fix!
