### ISSUE TITLE
ColumnToggler: Toggles too many columns with p:columnGroup

### ISSUE THREAD

**Issue by JavaTesting1** [primefaces/primefaces#4582]
## 1) Environment
- PrimeFaces version: 6.2.16
- Does it work on the newest released PrimeFaces version? No (Tested on 6.2.17)
- Does it work on the newest sources in GitHub? Not tested
- Application server + version: Tomcat 8.5.35
- Affected browsers: Chrome 72.x

## 2) Expected behavior
ColumnToggler should only toggle the column which has been clicked in the columnToggler overlay.

## 3) Actual behavior
ColumnToggler toggles two columns: Not only the column which has been clicked on the columnToggler overlay but also the column header at the same index of the p:columnGroup although these columns have the attribute toggleable="false"

## 4) Steps to reproduce
Simple Example for reproducing the bug is available here:
https://github.com/JavaTesting1/columnTogglerBug

**Comment by melloware** [comment]
This is confirmed fixed in 9.0
