### ISSUE TITLE
PrimeApplicationContext is not thread safe

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/primefaces#4585]
## 1) Environment
- PrimeFaces version: **`7.0.RC3`**
- Does it work on the newest released PrimeFaces version? **No**
- Does it work on the newest sources in GitHub? **No**

## 2) Explanation

The `PrimeApplicationContext` is an application scoped object that is lazily initialized. However, its initialization is not protected by any `synchronized` blocks or other thread safety code. So if X threads call `PrimeApplicationContext.getCurrentInstance(facesContext)` at the same time, they may instantiate as many as X `PrimeApplicationContext` instances.

Another aspect of `PrimeApplicationContext` that isn't thread safe is the lazy initialization of member data (such as `VirusScanner`). [This article](https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html) explains the issue in detail, but essentially the current implementation may allow threads to access partially initialized objects.

**Comment by tandraschko** [comment]
It would handle it as enhancement which can only occur in the first requests after context startup. Even then we just create some shortliving instances.

**Comment by stiemannkj1** [comment]
@tandraschko that's true for the `PrimeApplicationContext` itself, but the current implementation can expose partially constructed `CacheFactory` or `VirusScanner` as well. That's a bug.

**Comment by tandraschko** [comment]
How can a partial construction Happen? Afair the worst Case should be multiple Shirt living virusscanner

**Comment by stiemannkj1** [comment]
> The big problem with constructors in threaded applications is that the compiler has the permission, under the Java memory model, to reorder the operations inside of the constructor so they take place after (of all things) the object reference is created and the constructor finishes.  final fields will be guaranteed to be fully initialized by the time the constructor finishes but not other "normal" fields.

https://stackoverflow.com/questions/12611366/constructor-synchronization-in-java

**Comment by stiemannkj1** [comment]
@tandraschko, I think I have a fix. It includes some API changes. I'm testing now.

**Comment by tandraschko** [comment]
fixed the double checked locking now.

**Comment by tandraschko** [comment]
to make it 100% correct, we still need to sync the creation in PrimeApplicationContext#getCurrentInstance

**Comment by tandraschko** [comment]
I made some other lazy initialization.
IMO the only "bug" which could occur now is that if multiple requests hit the app after container startup in the same millis.
This could lead to multiple shortliving (1 per thread) PrimeApplicationContext objects, which includes:
- 1 PrimeEnvironment
- 1 PrimeConfiguration
- 2 ConcurrentHashMap
- 4 Lazy objects

its not the nicest way but its very hard to sync it... IMO everything else is just a enhancement, which i would ignore as it can only happen after container startup.
Its very cheap to creata new PrimeEnvironment & PrimeConfiguration. Its just some classForName and web.xml parameter reading.

**Comment by stiemannkj1** [comment]
@tandraschko, since `PrimeEnvironment`, `PrimeConfig`, and all `CacheProvider`s are still **mutable** and don't provide any locking or thread-safety mechanism, they will break if anyone uses their mutable features. I recommend that you remove all setters from these classes. The setters are basically pointless on those classes anyway. If you do that and [merge my PR](https://github.com/primefaces/primefaces/pull/4599), that should fix all thread-safety concerns.

**Comment by tandraschko** [comment]
done! @stiemannkj1 @melloware @cnsgithub @jxmai @Rapster it would be great if you could give my changes a try in your applications, if everything works as expected before we release the final.

**Comment by stiemannkj1** [comment]
@tandraschko just ran all the Faces tests and everything is working great!
