### ISSUE TITLE
p:selectOneMenu performance is down for huge data

### ISSUE THREAD

**Issue by rajankumar20** [primefaces/primefaces#4588]
Hi,

p:selectOneMenu is working for slow for huge data (3000 records).
Please improve this bug. For huge data it is taking a lot of time for populate.

Thanks & Regards,
Rajan kumar

**Comment by melloware** [comment]
You did not fill out the template correctly.  This will be closed unless you do.

For example you did not provide a runnable test case or even provide what version of PF you tested against.

Also just my UI 2 cents... 3000 items is too many for a select one.  3000 items you should be using an AutoComplete or some thing like that, that lets the user quickly search and find records.

**Comment by rajankumar20** [comment]
Dear team,
Thanks a lot.  I was using jsf version 6.1I have used Autocomplete for huge data and it is working fine.SelectOne is not suitable for huge data but Autocomplete is good for this purpose.
Thanks & Regards,Rajan kumar


    On Wednesday, 27 February, 2019, 5:30:02 pm IST, Melloware <notifications@github.com> wrote:  
 
 
You did not fill out the template correctly. This will be closed unless you do.

For example you did not provide a runnable test case or even provide what version of PF you tested against.

Also just my UI 2 cents... 3000 items is too many for a select one. 3000 items you should be using an AutoComplete or some thing like that, that lets the user quickly search and find records.

**Comment by melloware** [comment]
@tandraschko safe to close this ticket.
