### ISSUE TITLE
DataExporter XML does not correctly escape headers containing special characters

### ISSUE THREAD

**Issue by dieter57** [primefaces/primefaces#459]
Creating a datatable with variable column names is not exportable as XML with the DataExporter because the created tag is not correctly escaping the character `<`.

Having following definition in an xhtml page

``` xhtml
<p:dataTable id="tbl" var="stat" value="#{backing.statistikDetails}"`
              paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {Exporters}"
              paginator="true" rows="20" style="margin-bottom:20px">

        <f:facet name="{Exporters}">
            <h:commandLink>
                <p:graphicImage name="/img/xml.png" width="24"/>
                <p:dataExporter type="xml" target="tbl" fileName="stat3" />
            </h:commandLink>
        </f:facet>

        <p:column>
          <f:facet name="header">
             <h:outputText value="#{backing.columnname[0]" />
          </f:facet>
          <h:outputText value="#{stat.data[0]}" />
        </p:column>

        <p:column>
          <f:facet name="header">
             <h:outputText value="#{backing.columnname[1]" />
          </f:facet>
          <h:outputText value="#{stat.data[1]}" />
        </p:column>

</p:dataTable>  
```

with 

`columnname[0] = "erw. >50% behind."`
`columnname[1] = "kind >50% behind."`
and
`statistikDetails0] = "10"`
`statistikDetails1] = "5"`

the produced xml looks like

``` xml
   <erw._<50%_behind.>10</erw._<50%_behind.>
   <kind_<50%_behind.>5</kind_<50%_behind.>

```

**Comment by cagataycivici** [comment]
Yes, we should escape it, care to provide a pull request for XMLExporter.java?

**Comment by dieter57** [comment]
I just cloned the project and will have a look int the XMLExporter.java 
tomorrow.
Hopefully coming up with an idea how to escape the special characters.
Regards
Dieter

Am 21.06.2015 um 14:14 schrieb Çağatay Çivici:

**Comment by dieter57** [comment]
I have a solution - just contact me in the primefaces community orum with the same userid or (dieter@wintop.net)

**Comment by cagataycivici** [comment]
Can't you just provide a pull request, what is so secret about it :)

**Comment by dieter57** [comment]
Just had to struggle with the build of the library because of some dependencies not in the pom.
Solved the issue, could test it and provided the pull.

**Comment by cagataycivici** [comment]
Thanks, will check!
