### ISSUE TITLE
p:toggleSwitch not recognised in PF 7.0 RC3

### ISSUE THREAD

**Issue by YahiaZZ** [primefaces/primefaces#4594]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

Hi 

## 1) Environment
- PrimeFaces version: 7.0 RC3

- Application server + version: Tomcat 7
- Affected browsers: All

## 2) Expected behavior
toggleSwitch worked
...

## 3) Actual behavior
Error cannot resolve the name
<p:toggleSwitch> Tag Library supports namespace: http://primefaces.org/ui, but no tag was defined for name: toggleSwitch

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<p:panelGrid>
..<p:toggleSwitch  value="#{teamView.state}" ></p:toggleSwitch>
</p:panelGrid>

state is boolean

## 6) Sample bean
state=true;
..

**Comment by tandraschko** [comment]
Can someone check it if its working fine in the Showcase?

**Comment by YahiaZZ** [comment]
Hi,
It's working fine in the showcase, but when i try  to use it , it fails i don't know why

**Comment by tandraschko** [comment]
Probably multiple jar Files. @melloware can you verify if its working fine with rc3?

**Comment by YahiaZZ** [comment]
By the way, RequestContext is not resolved in PF 7.0 ?

**Comment by tandraschko** [comment]
Check the Migration Guide ;)

**Comment by YahiaZZ** [comment]
Ok thanks ^.^

**Comment by mertsincan** [comment]
I couldn't replicate it. But, maybe we can change 'COMPONENT_TYPE' of ToggleSwitch to be compatible with others components;
COMPONENT_TYPE = "org.primefaces.component.ToggleSwitch"; instead of 'org.primefaces.ToggleSwitch'
and
```<component-type>org.primefaces.component.ToggleSwitch</component-type>```
...

@melloware Could you please make this change after checking this issue? Thanks a lot ;)

**Comment by melloware** [comment]
I will investigate and fix.

**Comment by melloware** [comment]
I have verified this is an issue. Still investigating.

**Comment by melloware** [comment]
Attached is a reproducible sample: 
[pf-4594.zip](https://github.com/primefaces/primefaces/files/2916948/pf-4594.zip)

**Comment by melloware** [comment]
Sorry updated sample.  I am stumped on this one: 
[pf-4598.zip](https://github.com/primefaces/primefaces/files/2916990/pf-4598.zip)

**Comment by melloware** [comment]
I debugged this a little further. It seems to work for me with 7.0.RC3 but is failing with the 7.0-SNAPSHOT.

**Comment by mertsincan** [comment]
Hi @melloware,
I added the following line to faces-config.xml;
```
<component-type>org.primefaces.component.ToggleSwitch</component-type>
```
Could you please try again?

**Comment by melloware** [comment]
@mertsincan can you explain why this makes it work?  Its the same value in the PF Taglib.  And why 7.0.RC3 works but the SNAPSHOT has started failing?

**Comment by tandraschko** [comment]
for me everything looks correct now.

**Comment by melloware** [comment]
One thing that may be different is I am on Windows 10 are you both on Mac/Linux?

**Comment by melloware** [comment]
@tandraschko @mertsincan this is safe to close!  I realized my dumb mistake locally and verified this is all working now.
