### ISSUE TITLE
Add filterBy and matchMode to Autocomplete 

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#461]
I implemented a generic DAO using apache beanutils BeanComparator that I use to have a generic approach to be used in AutoComplete component.

My generic DAO can be obsolete if AutoComplete component will be enhanced adding `filterBy` and `matchMode` attributes and filter the binded collection itself.

`<p:autoComplete value="#{bean.foos}" var="varFoo" filterBy="#{varFoo.bar.name}" matchMode="contains" ... />`

In many cases where data-list is not loaded lazy this makes it much easier to develop and maintain since no custom bean method is required.

**Comment by cagataycivici** [comment]
This is a too custom requirement and the value added is not worth the effort.
