### ISSUE TITLE
Calendar: bad browser performance if pages attribute set

### ISSUE THREAD

**Issue by bjjoop** [primefaces/primefaces#4610]
## 1) Environment
- PrimeFaces version: 6.2.16
- Application server + version: Apache Tomcat 9.0.7
- Affected browsers: Edge, Chrome

## 2) Expected behavior
Browser should not have a visible delay after changing the date via the input element

## 3) Actual behavior
After changing the date in the input element and leaving the field (e.g. tab), a delay can be observed. The reason for this delay are (due to chrome performance logging) Recalculate Style and Layout caused by primefaces jquery-plugins.js upon calling _updateDatePicker.
This update method seems to check the offset for updating the date picker position and seems to cause the browser to work hard on layouting and style calculation.

Attached are two screenshots of the main culprits in chrome performance log from the actual application (not the basic example).
![recalculatestyle](https://user-images.githubusercontent.com/48278813/53873785-5a8f5a80-4001-11e9-8a8c-a8524a370743.PNG)
![layout](https://user-images.githubusercontent.com/48278813/53873787-5a8f5a80-4001-11e9-91ae-55eb4fde97d3.PNG)

On my machine (setup in a virtual box, win10, starting application from eclipse) the delay takes between 2-4 seconds

## 4) Steps to reproduce
- Starting with a page containing two calendars, one which is disabled.
- Setting a date in the non-disabled calendar. 
- Manually changing the selected date in input field via keyboard (setting year from 2019 -> 2020)
- Tab out of control
-> seeing noticable delay until tab is finished in which the recaluclate style + layout causes the browser (both edge, chrome) to briefly freeze up.

Screens with multiple calendars that are update via JS Api (for some kind of batch editing) freeze up for several minutes.

Removing the pages attribute settings (see example below) fixes the performance issue.

## 5) Sample XHTML
```xml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body>
	<p:calendar value="" pages="3" showButtonPanel="true" showTodayButton="true" navigator="true" showOn="button"/>
</h:body>
</html>

**Comment by melloware** [comment]
This is most likely not a PF problem but a bug in the underlying JQuery DatePicker the PF Calendar is based on.  

Here is the source for the Jquery DatePicker: https://github.com/jquery/jquery-ui/blob/master/ui/widgets/datepicker.js

"Pages" is actually the "numberOfMonths" settings in the underlying Jquery DatePicker.

If you analyze deeper and can provide a PR that would be great.  There is not much activity right now on the Jquery UI Widgets GitHub so its something you might have to help us fix.

**Comment by melloware** [comment]
Since this is a core Jquery UI issue it is unlikely to get fixed by PF and you can always switch to the new DatePicker from PF.
