### ISSUE TITLE
Calendar: Multiple date selection and navigation

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#4612]
From drop down select the Month to April , The calendar stays back to December 2018,

![image](https://user-images.githubusercontent.com/9069988/53947834-8f2c1080-40ec-11e9-8e4a-2c7f5fdde76d.png)

Sample attached 
[test.zip](https://github.com/primefaces/primefaces/files/2940544/test.zip)

Run and open http://localhost:8080/test/index.xhtml
Click the date textbox and change the month in combo

Sample Xhtml code

```
<p:calendar value="#{testing.entryDate}" maxdate="#{testing.now}" pages="3" 
      required="true" requiredMessage="Required" converterMessage="Invalid" 
      maxlength="10" size="7"  id="entryDate" pattern="dd/MM/yyyy"
      showButtonPanel="true" navigator="true" mask="true" />

```

Bean code, add getter and setter

```
@Named(value = "testing")
@ViewScoped
public class Testing implements Serializable {
    private Date entryDate = new Date();
    private Date now = new Date();
}
```

1) Environment

    PrimeFaces version: 7.0 RC3 Also in 6.2
    Does it work on the newest released PrimeFaces version? Version? No
    Application server + version: Tomcat 9
    Affected browsers: Firefox

**Comment by christophs78** [comment]
@arunvc : Can you use DatePicker instead of Calendar? DatePicker is the replacement for Calendar und should be pretty useable with PrimeFaces 8.0. (With PrimeFaces 7.0 it had major bugs.)

**Comment by melloware** [comment]
DatePicker has resolved this issue and its most likely Calendar will never get this fix so I would switch to DatePicker.
