### ISSUE TITLE
Schedule: Problem with PF6.1

### ISSUE THREAD

**Issue by YahiaZZ** [primefaces/primefaces#4613]
## 1) Environment
- PrimeFaces version: PF6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 7
- Affected browsers: all browsers

## 2) Expected behavior
Displaying p:schedule with its events
...

## 3) Actual behavior
Nothing displayed, it shows errors:
`SyntaxError: missing : after property id[Learn More] jquery.js.xhtml:1:320 `
`globalEval4 jQuery updateElement http://localhost:8080/xxxxx/javax.faces ... es&v=6.1:3
doUpdate http://localhost:8080/xxxx/javax.faces. ... es&v=6.1:3
handle http://localhost:8080/xxxx/javax.faces. ... es&v=6.1:3
success http://localhost:8080/xxx/javax.faces.r ... es&v=6.1:3
i4jQuery`
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
`<p:schedule id="schedule" value="#{mainView.eventModel}" axisFormat="H:mm" 
       		style="width:80%;height:80%"  view="agendaWeek" allDaySlot="false" aspectRatio="2" timeZone="GMT+1" 
       		minTime="0:00" maxTime="23:00" columnFormat="ddd DD/MM">

</p:schedule>`
..

## 6) Sample bean
`DefaultScheduleEvent evt = new DefaultScheduleEvent(Team.get(j).getName()+" | "+Team.get(j).getItem(), 
							 start, end,status);
				evt.setData(taches_perTeam.get(j));
				eventModel.addEvent(evt);`
..

Many Thanks

**Comment by tandraschko** [comment]
Please provide a runnable example. We don't have a MainView or Team.get() ;)

**Comment by tandraschko** [comment]
And does it work on 7.0.RC3?

**Comment by YahiaZZ** [comment]
I cannot use 7.0 RC3 because I have to change a huge project developed initially  with PF 6.1 but it works with PF 6.0, the problem with 6.0 is that I cannot use p:chips !

**Comment by tandraschko** [comment]
If you need a Bugfix for 6.1, you can check PrimeFaces Elite and Pro. Here we cant do anything for you.
You can however fork the 6.1 tag and fix it by yourself.
