### ISSUE TITLE
DefaultMenuItem: EL is not calculated in setStyleClass method

### ISSUE THREAD

**Issue by usharik** [primefaces/primefaces#4617]
## 1) Environment
- PrimeFaces version: 7.0.RC3
- Does it work on the newest released PrimeFaces version? Version? No (7.0.RC3)
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) not tested
- Application server + version: Wildfly 7.0.0.Final
- Affected browsers: Google Chrome

## 2) Expected behavior

EL expression assigned to the item by method DefaultMenuItem.setStyleClass() is correctly interpreted and produce the required behavior of dynamic menu component.

## 3) Actual behavior

EL expression assigned to the item by method DefaultMenuItem.setStyleClass() treated as a simple string and assigned to final HTML item class as it was passed into the method. Example of how it's looks `a tabindex="-1" class="ui-menuitem-link ui-corner-all #{&quot;1&quot;.equals(categories.category) ? &quot;ui-state-active&quot; : &quot;&quot;}">`

## 4) Steps to reproduce

Create a managed bean and XHTML pattern as explained below and run 

## 5) Sample XHTML

```
<p:panelMenu id="id-categories" model="#{categories.model}" expanded="true"/>
```

## 6) Sample bean

```
@ManagedBean(name = "categories")
@SessionScoped
public class CategoriesBean {

    private static String CATEGORY_ID ="categoryId";

    private DynamicMenuModel model;

    @Inject
    private CategoryRepository categoryRepository;

    private Category category;

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Collection<Category> getAll() {
        return categoryRepository.getAll();
    }

    @PostConstruct
    private void init() {
        model = new DynamicMenuModel();

        DefaultSubMenu categoriesSubmenu = new DefaultSubMenu("Categories");
        categoriesSubmenu.setExpanded(true);

        for (Category category : categoryRepository.getAll()) {
            categoriesSubmenu.addElement(createMenuItem(String.valueOf(category.getId()), category.getName()));
        }
        model.addElement(categoriesSubmenu);

        model.generateUniqueIds();
    }

    public MenuModel getModel() {
        return model;
    }

    public String actionSelectCategory(ActionEvent event) {
        MenuItem menuItem = ((MenuActionEvent) event).getMenuItem();
        String id = menuItem.getParams().get(CATEGORY_ID).get(0);

        this.category = categoryRepository.getById(Long.valueOf(id));
        return "/index.xhtml?faces-redirect=true";
    }

    private MenuItem createMenuItem(String id, String name) {
        DefaultMenuItem item = new DefaultMenuItem(name);
        item.setId(id);
        item.setCommand("#{categories.actionSelectCategory}");
        item.setParam(CATEGORY_ID, id);
        item.setStyleClass("#{\"" + id + "\".equals(categories.category) ? \"ui-state-active\" : \"\"}");
        return item;
    }
}
```

**Comment by tandraschko** [comment]
still don't understand this request.
Why not just pass the Category pojo to the createMenuItem and set the correct styleClass when building the model?

probably a won't fix.

**Comment by usharik** [comment]
1. If setCommand understand ELs why setStyleClass not?
2. I'm trying to use PanelMenu as a navigation element on which currently selected category should be highlighted. That's why I'm trying to use EL in setStyleClass().

**Comment by tandraschko** [comment]
Because the info should be already there when you build the model. You just have to make it requestscoped instead viewscoped.

Because a command/listener can only be a EL

**Comment by usharik** [comment]
I can't use request scope because I need to store selected category between requests.

**Comment by tandraschko** [comment]
As you are the first one since years, i suggest you to use the following workaround:

```java
class MyDefaultMenuItem extends DefaultMenuItem {    
    @Override    
    public String getStyleClass() {    
        FacesContext facesContext = FacesContext.getCurrentInstance();    
        return facesContext.getApplication().evaluateExpressionGet(facesContext, super.getStyleClass(), String.class);    
    }    
}    
```

**Comment by tandraschko** [comment]
sorry, i'm stupid enough each time to dont remember how to format correctly.

**Comment by melloware** [comment]
@tandraschko I fixed the formatting.   Thanks for the workaround!

**Comment by ansurakin** [comment]
Thanks!
My be need create property like: boolean evaluateExpression
