### ISSUE TITLE
AutoComplete - add maxResults parameter to filter method definition

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#462]
Add maxResults parameter to filter method definition. Similar to LazyDataModel.
Bean is not responsible of number of results.

In markup we set `maxResults` but in bean method we have to duplicate the number of results.

`<p:autoComplete maxResults="5" completeMethod="#{bean.filter}"/>`

`public List filter(String query) { return dao.getRows(query, 5) }`

Seperation of concern makes it cleaner:

`public List filter(String query, int count) { return dao.getRows(query, count) }`

**Comment by cagataycivici** [comment]
You can just bind the maxResults to a bean property and call your backend call with it, instead of we passing it.

**Comment by djmj** [comment]
Thats what i am currently doing which is a lot of boilerplate max result count definitions. It is nothing severe but its just unnecessary Java code in my opinion. Also maintaining is more work since one must always go into the bean to change the count.

And thats what I like a lot about JSF and PF, to write less Java Code :)

Your comment shows the inconsistency between the autoComplete filter and lazy load method of LazyDataModel, which by design do the same thing - loading data. 
In later you pass the row count resulting in clean separation of markup and java code and in autoComplete we have to define a bean property for it.

Using many autocomplete components in project we have many code like 

# Current

_Bean:_

```
class Bean
{
    int fooAutoCompleteMaxResults = 5;

    public List<Foo> filter(String query)
    {
        return this.dao.getRows(query, this.fooAutoCompleteMaxResults);
    }

    public int getFooAutoCompleteMaxResults()
    {
        return this.fooAutoCompleteMaxResults;
    }
}
```

_Markup:_

```
<p:autoComplete maxResults="#{bean.fooAutoCompleteMaxResults}" filterMethod="#{bean.filter}"/>
```

# Alternative

Less code and dependencies.

_Bean:_

```
class Bean
{
    public List<Foo> filter(String query, int count)
    {
        return this.dao.getRows(query, count);
    }
}
```

_Markup:_

```
<p:autoComplete maxResults="5" filterMethod="#{bean.filter}"/>
```

**Comment by cagataycivici** [comment]
If more users demand it, we can do it for sure but for now won't take action.
