### ISSUE TITLE
Calendar:  Value could be either String or java.util.Date (Regression 6.2 > 7.0.RC3)

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#4621]
## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version? yes
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Jetty
- Affected browsers:

## 2) Expected behavior

On click first calendar should not throw exception. maxdate/mindate

## 3) Actual behavior

Exception thrown

## 4) Steps to reproduce

Click first calendar
## 5) Sample 
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form>

		<p:calendar maxdate="today">
			<p:ajax event="dateSelect" update="@form" />
		</p:calendar>

	</h:form>

</h:body>
</html>
```
https://github.com/erickdeoliveiraleal/primefaces-test

**Comment by tandraschko** [comment]
@mertsincan can you check before releasing it?

**Comment by erickdeoliveiraleal** [comment]
I simplified the example

**Comment by tandraschko** [comment]
@cnsgithub could you check that please? otherwise i have to revert the validation for the final release.

**Comment by cnsgithub** [comment]
@erickdeoliveiraleal @tandraschko Was `maxdate="today"` an allowed value at some point in time? Didn't know, also cannot find this in user guide. Maybe it was just passed through to jquery datepicker and was supported unofficially. Workaround would be to not use those unofficial magic strings and rather go with strings following the specified date pattern or `java.util.Date`. Wontfix.

**Comment by erickdeoliveiraleal** [comment]
I did not know that either. but other developers in my work yes. it's in some answers from stackoverflow too. but there are alternatives like {now} from Omnifaces. Perhaps it could be documented in the migration guide.

**Comment by tandraschko** [comment]
is there a list of keywords supported by jquery datepicker? We could at least log a warning in such cases.

**Comment by cnsgithub** [comment]
Not sure, cannot find it [here](https://api.jqueryui.com/datepicker/#utility-formatDate). Also, since the utility method is used by @mertsincan' new `datepicker` as well, we must pay extra attention when trying to support JS-specific stuff here.

**Comment by melloware** [comment]
I think "today" might be the only special one.  In case of "today" for backwards compatibility maybe we should make it today using new Date() or something?

**Comment by tandraschko** [comment]
i think its really ok to add such a special handling for today

**Comment by cnsgithub** [comment]
Using max time of `new Date()`?

**Comment by mertsincan** [comment]
No, please see the other value types;
```
maxDate 
Type: Date or Number or String
Default: null
The maximum selectable date. When set to null, there is no maximum.
Multiple types supported:
Date: A date object containing the maximum date.
Number: A number of days from today. For example 2 represents two days from today and -1 represents yesterday.
String: A string in the format defined by the dateFormat option, or a relative date. Relative dates must contain value and period pairs; valid periods are "y" for years, "m" for months, "w" for weeks, and "d" for days. For example, "+1m +7d" represents one month and seven days from today.
```
http://api.jqueryui.com/datepicker/#option-maxDate

Exp; maxDate="+1m +7d"

**Comment by cnsgithub** [comment]
Okay, if you want to support those, more effort must be spend to translate those formats into java. @tandraschko In this case I'd recommend to revert input validation. 

Btw, this should have been documented somehow.

**Comment by melloware** [comment]
Agreed we can revert the input validation for now.

**Comment by cnsgithub** [comment]
Or do at least if `value instanceof Date`?

**Comment by mertsincan** [comment]
@cnsgithub, you're right ;) We'll add it into next documentation.

**Comment by tandraschko** [comment]
If you assign maxdate to a Date ValueExpression? Does this work on the client side currently?

**Comment by cnsgithub** [comment]
Yes, as far as I can remember, that worked properly.

**Comment by mertsincan** [comment]
```
.attr("minDate", CalendarUtils.getValueAsString(context, calendar, calendar.getMindate()), null)
.attr("maxDate", CalendarUtils.getValueAsString(context, calendar, calendar.getMaxdate()), null)
```
Yes ;)

**Comment by tandraschko** [comment]
Ok, so i would just do validation for "instanceof Date" for now and note it somewhere.

**Comment by tandraschko** [comment]
Could someone do it?
I'm on a different thing today - will publish a JSF benchmark update soon :D

**Comment by cnsgithub** [comment]
I am currently doing it...

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/4622

**Comment by tandraschko** [comment]
Looks good for me. Thank you!

**Comment by tandraschko** [comment]
(would be great if someone could retest with some different cases)
