### ISSUE TITLE
Dialog Framework: Update Dialog Height on validation errors

### ISSUE THREAD

**Issue by Reslop** [primefaces/primefaces#4623]
## 1) Environment
- PrimeFaces version: 7.0.RC3
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Glassfish 5
- Affected browsers: Chrome, Firefox, Microsoft Edge

## 2) Expected behavior
If you have the height set to the default (auto) and you update your form and a validation messages occurs the dialog height is auto resize so you can see complete content without scrolling like p:dialog.

## 3) Actual behavior
The dialog does not auto resize height after a validation message occurs.

## 4) Steps to reproduce
Use the following code sample to reproduce just hit submit button

## 5) Sample XHTML
`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Titel</title>
</h:head>

<h:body>
	<h:form id="form">
		<p:messages id="messages">
			<p:autoUpdate />
		</p:messages>
		<h:panelGrid cellpadding="5" columns="1">
			<p:inputText value="#{dialogService.value}" required="true"
				requiredMessage="No Value" />
			<p:commandButton value="Submit" update="form" />
		</h:panelGrid>
	</h:form>

</h:body>
</html>`

![df_1of2](https://user-images.githubusercontent.com/48483620/54207346-456f6b80-44da-11e9-89d1-738a5cb85fbd.png)
![df_2of2](https://user-images.githubusercontent.com/48483620/54207355-4902f280-44da-11e9-8eae-bca39f478f04.png)

## 6) Sample bean
`Map<String, Object> options = new HashMap<>();
		options.put("modal", true);
		options.put("resizable", false);
		options.put("draggable", false);
		options.put("responsive", true);
		options.put("contentWidth", "auto");`

**Comment by melloware** [comment]
Runnable sample: 
[pf-4623.zip](https://github.com/primefaces/primefaces/files/2964211/pf-4623.zip)

Run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

However it works if I add...

```java
options.put("contentHeight", "auto");
```

**Comment by melloware** [comment]
Ahh debugging this further its because Dialog Framework dialogs get opened inside an iframe which is why the height gets fixed.

**Comment by melloware** [comment]
OK because the iFrame size is set initially the workaround of setting `options.put("contentHeight", "auto");` is the best option for this as the iFrame has to be sized when the dialog is rendered using dialog framework.
