### ISSUE TITLE
DatePicker: Time is not set on Date Object

### ISSUE THREAD

**Issue by carlbradwell17** [primefaces/primefaces#4625]
## 1) Environment
- PrimeFaces version: 7.0.0-RC3

## 2) Expected behavior
When I use a datePicker to set a Date object on a bean, both the date and time should be set.

## 3) Actual behavior

The date is set, but the time is always 00:00:00.
E.g. if I set the datepicker to "14/03/19 11:57", when I inspect the Date object, the value is "Thu Mar 14 00:00:00 GMT 2019".

## 4) Steps to reproduce

Create a datepicker, with no options set other than showTime="true". Set a date and time and then check the Date object after submission.

## 5) Sample XHTML
<h:form>
<p:datePicker value="#{testBean.date1}" showTime="true" />
<p:commandButton action="#{testBean.submit}" value="submit" />	
</h:form>

## 6) Sample bean

@Named
@ViewScoped
public class TestBean {
private Date date1;

	public String submit() {
		return null;
	}
public Date getDate1() {
        return date1;
    }
 
    public void setDate1(Date date1) {
        this.date1 = date1;
    }

}

**Comment by christophs78** [comment]
Applied a fix/work-around for this (for LocalDateTime) during my work on java.time-support.

**Comment by christophs78** [comment]
Additional improvements with https://github.com/primefaces/primefaces/pull/5191

**Comment by melloware** [comment]
@christophs78 Is this safe to mark closed?
