### ISSUE TITLE
DatePicker: pattern including date and time

### ISSUE THREAD

**Issue by carlbradwell17** [primefaces/primefaces#4626]
## 1) Environment
- PrimeFaces version: 7.0-RC3

## 2) Expected behavior
If i want to use a datePicker to set a date object which includes the time, I should set the showTime attribute to true to allow the user to select a time. I then should be able to set a pattern parameter, to format the datetime in the input. 
It is possible to pass a pattern for the time when the datePicker is set to timeOnly="true".
The behaviour of accepting a pattern with date and time is how the calendar component works,

## 3) Actual behavior

Setting showtime to true adds the time to the end of the value. The pattern attribute therefore only seems to affect the date portion. I therefore have no way of customising the formatting of the time portion. 

## 4) Steps to reproduce

create a datePicker with showTime set to true and a pattern including time. E.g. if I click 12th march 2019, and set the time to 11:09, the value displayed in the input is "12-Mar-2019 HH:03 11:09". The value cannot be set on the date object, i.e. nothing happens when submitting the form.

## 5) Sample XHTML

<h:form>
 <p:datePicker value="#{testBean.date1}" showTime="true" pattern="dd-MMM-yyyy HH:mm" />
 <p:commandButton action="#{testBean.submit}" value="submit" />	
			
</h:form>
## 6) Sample bean

@Named
@ViewScoped
public class TestBean {
private Date date1;

public String submit() {
		return null;
	}
public Date getDate1() {
        return date1;
    }
 
    public void setDate1(Date date1) {
        this.date1 = date1;
    }
}

**Comment by christophs78** [comment]
This was solved with https://github.com/primefaces/primefaces/pull/5191.
