### ISSUE TITLE
DatePicker: Unselectable values not indicated in month view

### ISSUE THREAD

**Issue by carlbradwell17** [primefaces/primefaces#4628]
## 1) Environment
- PrimeFaces version: 7.0-RC3

## 2) Expected behavior
 When I use a datePicker, and set view="month" and maxdate="#{now}", I should not be able to select months greater than the current month, and they should be visually disabled.

## 3) Actual behavior

There is no visual differentiation of disabled months, and I am able to select one, but it sets the value to the current month instead of the selected one.

## 4) Steps to reproduce

Create a datepicker with month view and a maxdate set. Try to select a month greater than maxdate.

## 5) Sample XHTML

<h:form>
<p:datePicker view="month" maxdate="#{now}" />
</h:form>

**Comment by tandraschko** [comment]
whats #{now}?

**Comment by carlbradwell17** [comment]
From omnifaces, "The builtin managed bean #{now} returns you the java.util.Date instance representing the current time." Any Date object will do in this example.

**Comment by melloware** [comment]
Reproducer: 
[pf-4628.zip](https://github.com/primefaces/primefaces/files/4078356/pf-4628.zip)

**Comment by melloware** [comment]
@carlbradwell17 For your example maxdate of April 01, 1997 were you expecting April to be disabled or enabled?

![image](https://user-images.githubusercontent.com/4399574/77451795-87104300-6dcb-11ea-9eee-c50fedd53845.png)
