### ISSUE TITLE
Dialog: Not supporting HTML content in 7.0

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#4629]
## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version? yes
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no

## 2) Expected behavior
Clicking button should display a link

## 3) Actual behavior
Showing a escaped text

## 4) Steps to reproduce
Click button

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form>
		<p:commandButton action="#{testView.displayMsg}" />
	</h:form>
</h:body>
</html>
```

## 6) Sample bean
```
package org.primefaces.test;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.PrimeFaces;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

	public void displayMsg() {
		PrimeFaces.current().dialog().showMessageDynamic(new FacesMessage(FacesMessage.SEVERITY_INFO,
				"Auto de Apreensão", "<a target='_blank' href='http://googlde.com'>Clique here</a>"));
	}

}

```

**Comment by tandraschko** [comment]
@cnsgithub can we somehow control it with a escape flag in this case? Maybe we need to introduce a flag here

**Comment by melloware** [comment]
Runnable sample.  PR coming. 
[pf-4629.zip](https://github.com/primefaces/primefaces/files/2964140/pf-4629.zip)
