### ISSUE TITLE
Messages.properties can't use label with primefaces.slider.OUT_OF_RANGE and primefaces.calendar.OUT_OF_RANGE

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#4630]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? yes. 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version:
- Affected browsers:

## 2) Expected behavior

PrimeFaces 7.0 introduced primefaces.calendar.OUT_OF_RANGE.

primefaces.slider.OUT_OF_RANGE

## 3) Actual behavior
Can't use label of the input field in validation {0}

## 4) Steps to reproduce
Select a invalid date in calendar with mindate defined

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/4634
