### ISSUE TITLE
JSF 2.3 compatibility: values getting null

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#4635]
## 1) Environment
- PrimeFaces version: no
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version:
- Affected browsers:

## 2) Expected behavior

Value should remain, even with javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL set to true

## 3) Actual behavior
value is null

## 4) Steps to reproduce
access: http://localhost:8080/primefaces-test/?tipo=U&test=Bah
click first button, click second button

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">
<f:metadata>

	<f:viewParam name="test" value="#{testView.testString}" />
	<f:viewAction action="#{testView.inicializar}" />

</f:metadata>
<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form id="cadastro">
		<h:commandButton value="click me"
			action="#{testView.inserirNaLista()}">
			<f:ajax execute="@form" render="@form" />
		</h:commandButton>
		<p:commandButton
			value="click me - 2 (this button causes the null value)"
			action="#{testView.inserirNaLista()}" />

	</h:form>


</h:body>
</html>
```

## 6) Sample bean
```
package org.primefaces.test;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
	private String testString;

	public void inicializar() {
		System.out.println("initializing: " + testString);

	}

	public void inserirNaLista() {
		System.out.println(testString);
	}

	public String getTestString() {
		return testString;
	}

	public void setTestString(String testString) {
		this.testString = testString;
	}

}

```

https://github.com/erickdeoliveiraleal/primefaces-test/tree/update

**Comment by melloware** [comment]
Are you using Mojarra? Is it related to this? https://github.com/primefaces/primefaces/issues/4533

**Comment by erickdeoliveiraleal** [comment]
I'm using Mojarra. I don't know if is related, not present in Mojarra 2.2

**Comment by melloware** [comment]
Can you please paste the nullpointer stack trace?

**Comment by melloware** [comment]
Oh OK you aren't getting a NullPointerException your value is just NULL. OK.   This is most likely not a PrimeFaces issue but a Mojarra bug: https://stackoverflow.com/questions/53759078/related-problem-with-null-versus-empty-string-when-updating-to-jsf-2-3-mojarra

**Comment by erickdeoliveiraleal** [comment]
I read it, and it doesn't look like it's the same bug. I will post mojarra issue then.
Stackoverflow: https://stackoverflow.com/questions/55173655/using-javax-faces-interpret-empty-string-submitted-values-as-null-causes-viewpar
