### ISSUE TITLE
DataTable: "IllegalArgumentException: Unsupported rows per page value" with ShowAll in rowsPerPageTemplate

### ISSUE THREAD

**Issue by d-bykov** [primefaces/primefaces#4636]
## 1) Environment
- PrimeFaces 7.0.RC3
- WildFly Full 16.0.0.Final
- Affected browsers: Firefox 65.0.2

## 2) Expected behavior

When I select "All" in DataTable's rows per page drop-down list, all available rows should be shown.

## 3) Actual behavior

When the "All" option is selected, empty table is shown and there is an _java.lang.IllegalArgumentException: Unsupported rows per page value: 15_ error in server's log.

## 4) Steps to reproduce

Load the page, select the "All" option in the DataTable's rows per pages drop-down list.

## 5) Sample XHTML

    <h:form>
        <p:dataTable value="#{dataTableController.rows}" var="row" paginator="true"
                     rowsPerPageTemplate="5,10,{ShowAll|'All'}" rows="5">
            <p:column>
                <h:outputText value="#{row}"/>
            </p:column>
        </p:dataTable>
    </h:form>

## 6) Sample bean

    @Named
    @ApplicationScoped
    public class DataTableController implements Serializable {
        private static final int ROW_COUNT = 15;
        private static final List<String> ROWS = new ArrayList<>(ROW_COUNT);

        static {
            for (int i = 0; i < ROW_COUNT; i++) {
                ROWS.add("Row " + i);
            }
        }

        public List<String> getRows() {
            return ROWS;
        }
    }

**Comment by tandraschko** [comment]
@melloware @cnsgithub @Rapster any idea?
This really breaks a migration. The problem is that "All" resolves to 15, which is actually not in the list of "rowsPerPageTemplate".
We probably have to pass "All" instead a rownumber in this case to the server. 
Otherwise we have to allow all numbers.

**Comment by cnsgithub** [comment]
Original issue: https://github.com/primefaces/primefaces/issues/3519

I'll have a look into this. But again, these undocumented features are quite annoying and prevent us from rolling out any new features without breaking something. There is no word about `rowsPerPageTemplate="{ShowAll|'All'}"` in the user guide. :cry:

**Comment by Rapster** [comment]
Good catch @cnsgithub :wink: Regarding documentation, I had in mind to throw an exception if such a case happened, so it doesn't happen anymore

**Comment by mertsincan** [comment]
Release time :D

**Comment by cnsgithub** [comment]
@mertsincan Oops, I did a pull request at the same time :wink:: https://github.com/primefaces/primefaces/pull/4640

I just had a look at your commit: it's very similar despite it's using `{ShowAll|` again hardcoded. I think we should use a constant here.

**Comment by mertsincan** [comment]
@melloware, so sorry :( I didn't see your PR. 

> I just had a look at your commit: it's very similar despite it's using {ShowAll| again hardcoded. I think we should use a constant here.

You're right! Could you please attach a new PR? Thanks a lot!

**Comment by fabermundi** [comment]
Hi, I've tried your fix (thanks for that) but it seems, that there is still an issue when filtering is enabled. In that case the condition "Integer.toString(data.getRowCount()).equals(rowsParam))" results "false" and the error is still thrown...

**Comment by tomlux** [comment]
Hi,
the "getRowCount" method is returning the row count of the filtered rows. The "rowsParam" has the row count of the non-filtered table.
I did a small workaround in the UIData.java to fix/bypass it by updating the isRowsPerPageValid method:
https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/api/UIData.java#L252


My modified lines:
```java
int totalRowCount = ((List) getValueExpression("value").getValue(getFacesContext().getELContext())).size();
if (opt.equals(rowsParam) || (opt.startsWith("{ShowAll|")) && (Integer.toString(getRowCount()).equals(rowsParam) || Integer.toString(totalRowCount).equals(rowsParam))) {
    return true;
}
```

Here the entire method:
```java
 private boolean isRowsPerPageValid(UIData data, String rowsParam) {
        if (rowsParam == null) {
            return true;
        }
        String rowsPerPageTemplate = data.getRowsPerPageTemplate();
        if (rowsPerPageTemplate != null) {
            int totalRowCount = ((List) getValueExpression("value").getValue(getFacesContext().getELContext())).size();
            String[] options = rowsPerPageTemplate.split("[,]+");
            for (String option : options) {
                String opt = option.trim();
                if (opt.equals(rowsParam) || (opt.startsWith("{ShowAll|"))
                        && (Integer.toString(getRowCount()).equals(rowsParam) || Integer.toString(totalRowCount).equals(rowsParam))) {
                    return true;
                }
            }
            return false;
        }
        int rows = data.getRows();
        if (rows > 0) {
            return Integer.toString(rows).equals(rowsParam);
        }
        return true;
    }
```

**Comment by melloware** [comment]
Please review my PR: https://github.com/primefaces/primefaces/pull/4853

I changed your casting of List to Collection just to be safe and not assume its a list inside.
I refactored the code slightly to not do so many Integer.toString() calls.
