### ISSUE TITLE
primefaces 7.0 jar missing in mvnrepository

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4645]
https://www.primefaces.org/primefaces-7-0-final-released/

https://mvnrepository.com/artifact/org.primefaces/primefaces

![image](https://user-images.githubusercontent.com/15189434/54543468-16db1000-4974-11e9-8b3a-210f45682faf.png)

**Comment by tandraschko** [comment]
Primetek is aware of that
