### ISSUE TITLE
Wrong link in docs

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#4649]
I cannot reopen #2770 
Wrong link is:
https://github.com/primefaces/primefaces/blob/80d10c8a792e2cecfe15a50c952822d96dfdaf4b/docs/7_0_0/misc.md#L304
It should point to GitHub instead.

**Comment by tandraschko** [comment]
Why not just provide a PR instead of a issue?

**Comment by NicolaIsotta** [comment]
PR is coming… just a sec.

**Comment by tandraschko** [comment]
Thanks :) please skip the issue for doc the next time, it's not required for tracking :)
