### ISSUE TITLE
Parameter passed to ui:composition is not resolved by p:ajax

### ISSUE THREAD

**Issue by nelsongraca** [primefaces/primefaces#465]
The problem seems to be the same as here, still affects PF5.2
https://code.google.com/p/primefaces/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20TargetVersion%20Reporter%20Owner%20Summary&groupby=&sort=&id=4075

**Comment by cagataycivici** [comment]
This has been discussed many times, you need to cast AjaxBehaviorEvent in a case like this.

**Comment by nelsongraca** [comment]
While that works, I just want to say it feels more like a workaround than a fix, and would be nice to find some reference to this in the docs (I couldn't find any).

**Comment by cagataycivici** [comment]
I'm aware of that, we worked on this before but there is no other workaround.
