### ISSUE TITLE
JQPlot: Device Pixel Ratio

### ISSUE THREAD

**Issue by hichamglia** [primefaces/primefaces#4655]
This is my first issue report.
metergauge is not displayed as expected.
Even if I set the style="width:400px;height:250px" the output is not readable.
You can check what I am talking about in the demo page :
https://www.primefaces.org/showcase/ui/chart/metergauge.xhtml

**Comment by melloware** [comment]
I don't understand. Can you explain what exactly is not working?  When you say the output is not readable I don't know what you are referring to.

The Custom chart in that example has `meterGaugeModel2.setShowTickLabels(false);` so that is why labels are not being displayed in the second gauge?

**Comment by hichamglia** [comment]
Both charts are not well displayed.
Only 1/4 of the chart is displayed as you can see in the screenshot below
<img width="1024" alt="pf" src="https://user-images.githubusercontent.com/20902770/54639448-4b8abc80-4a85-11e9-8485-fbf24c9ce845.png">

**Comment by melloware** [comment]
What browser?  I am in Chrome and here is what mine looks like...

![image](https://user-images.githubusercontent.com/4399574/54640459-36eafc00-4a66-11e9-8baf-4555d670865c.png)

**Comment by pzygielo** [comment]
@adamo901 - please reset zoom in your browser

**Comment by hichamglia** [comment]
The zoom is set to normal in all my browsers.
The below screenshot is from safari
<img width="1134" alt="PF2" src="https://user-images.githubusercontent.com/20902770/54641126-492a6180-4a89-11e9-8b75-e4f56fdfc596.png">

And I have also the same issue on Chrome 73.0.3683.75 and FireFox 66.0 (64 bits)

**Comment by melloware** [comment]
Here is my firefox. Its working in IE, Chrome, Firefox.

![image](https://user-images.githubusercontent.com/4399574/54679805-a3a1dd00-4ade-11e9-84c6-ac1b3c423a48.png)

**Comment by iimayconii** [comment]
I tested and is rendering as follows (Chrome version: 73.0.3683.75):

![image](https://user-images.githubusercontent.com/5523917/54683896-9c37ff00-4af1-11e9-93a9-44c5026509d9.png)

**Comment by melloware** [comment]
If you can dig deeper into it please do.  I have tested on 2 different computers in 3 different browsers and it looks fine for me.

**Comment by iimayconii** [comment]
I think the zoom problem in the chart is generated by the size calculation according to window.devicePixelRatio.
Basically the rendering problem happens for screens with the largest pixel density.

Documentation of "window.devicePixelRatio: (https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio)

The code snippet in the jqPlot that generates the calculation is at line 294 of the jqplot.core.js file.

jqPlot code snippet:

>            var canvasBackingScale = 1;
>            if (window.devicePixelRatio > 1 && (cctx.webkitBackingStorePixelRatio === undefined || 
>                                                cctx.webkitBackingStorePixelRatio < 2)) {
>                canvasBackingScale = window.devicePixelRatio;
>            }
>            var oldWidth = canvas.width;
>           var oldHeight = canvas.height;
>            canvas.width = canvasBackingScale * canvas.width;
>            canvas.height = canvasBackingScale * canvas.height;
>            canvas.style.width = oldWidth + "px";
>            canvas.style.height = oldHeight + "px";
>            cctx.save();
>            cctx.scale(canvasBackingScale, canvasBackingScale);

**Comment by melloware** [comment]
Look like there are open issues on JQPlot...

https://github.com/jqPlot/jqPlot/issues/119

According to that the way to fix it is...

```javascript
else if (tagname == 'canvas') {
                var hh = $(el).innerHeight() - 2 * parseInt($(el).css('padding-top'), 10);
                var ww = $(el).innerWidth() - 2 * parseInt($(el).css('padding-left'), 10);

                newContext.drawImage(el, left, top, ww, hh);
            }
```

**Comment by melloware** [comment]
OK I fixed it and submitted a PR.  Thanks for investigating this issue!

**Comment by iimayconii** [comment]
> OK I fixed it and submitted a PR. Thanks for investigating this issue!

You're welcome! I thank you for the excellent work that you guys do!

**Comment by melloware** [comment]
The subject of this ticket should be re-titled to "JQPlot: Device Pixel Ratio"

**Comment by hichamglia** [comment]
Many thanks for the great work.
I think the title should still keep some word related to "metergauge primefaces chart".

**Comment by melloware** [comment]
Well according to the JQplot ticket it affects more than MeterGauge it can affect any chart so that is why I wanted the issue described more generically.  MeterGauge was a symptom not the cause.

**Comment by RalfScania** [comment]
It is still not fixed in RC3, please review.

**Comment by melloware** [comment]
Can you create a PrimeFaces Test case proving the issue: https://github.com/primefaces/primefaces-test

I am using the Showcase and I can't reproduce the issue.

**Comment by RalfScania** [comment]
![image](https://user-images.githubusercontent.com/54022311/73752144-b0640980-4760-11ea-8e37-5b3a0d351646.png)

This is a screen from the actual showcase.

**Comment by melloware** [comment]
Found this issue too:  https://github.com/jqPlot/jqPlot/issues/117

Fixing...
