### ISSUE TITLE
Dynamic DataTable ajax update issue

### ISSUE THREAD

**Issue by cavalka** [primefaces/primefaces#4659]
I have a dynamic table where I can delete records from the table.  After clicking the delete button the action bean is initiated to delete record from database and then the data table is to be update.  Problem is the data table never gets refreshed with the deleted record removed from data table.  The ajax update is not working on dynamic data table.  If I execute PF('mrTable').filter() on complete the data table is updated.  Problem when I issue this command is the data table looses it's current state. 
Requesting a new function in datatable.js to refresh data without loosing current state of data table or make it so the normal ajax update works in dynamic data table.

**Comment by tandraschko** [comment]
Please follows our issue template.
