### ISSUE TITLE
LinkButton: 'target' and 'title' attributtes not rendered

### ISSUE THREAD

**Issue by jasonex7** [primefaces/primefaces#4662]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Jetty 9.4 from https://github.com/primefaces/primefaces-test
- Affected browsers: ALL

## 2) Expected behavior

'Target' and 'title' attributes should be rendered because there are in `primefaces-p.taglib.xml`.
```XHTML
<p:linkButton outcome="test2" target="_BLANK" title="Test Title" value="Link Button" />
```
Should be render as

```HTML
<span id="j_idt6" class="ui-linkbutton ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" title="Test Title">
     <a href="/primefaces-test/test2.xhtml" target="_BLANK"><span class="ui-button-text ui-c">Link Button</span></a>
</span>
```

## 3) Actual behavior

Doesn't render 'target' nor 'title' attributes.

Got render as

```HTML
<span id="j_idt6" class="ui-linkbutton ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">
     <a href="/primefaces-test/test2.xhtml"><span class="ui-button-text ui-c">Link Button</span></a>
</span>
```

## 4) Sample XHTML

```XHTML
<p:linkButton outcome="test2" target="_BLANK" title="Test Title" value="Link Button" />
```

**Comment by erickdeoliveiraleal** [comment]
@mertsincan can you merge it in elite release?

**Comment by mertsincan** [comment]
Of course! Thanks a lot ;)
