### ISSUE TITLE
menuItem: disableClientWindow does not apply to url

### ISSUE THREAD

**Issue by wklaczynski** [primefaces/primefaces#4676]
When use  with "url" attribute 
When I use the <p:menuitem with the "url" attribute and the "disableClientWindow='true'" attribute, the window parameter is still rendered.

                        <p:menuitem
                            value="Users"
                            url="faces/web/users/list-users.xhtml"
                            disableClientWindow="true"
                            ajax="false"
                            />
Rendered:
    faces/web/users/list-users.xhtml?jfwid=SFnBQ.....

1) Environment

    PrimeFaces version: 7.0
    Application server + version: wildflay 15
    Affected browsers: firefox
   JSF 2.3

**Comment by wklaczynski** [comment]
The problem is in "OutcomeTargetRenderer", for "url" it should be the same as for "outcome".

```
        String href = outcomeTarget.getHref();
        if (href != null) {
            url = "#".equals(href) ? "#" : context.getExternalContext().encodeRedirectURL(href, outcomeTarget.getParams());
        }

```



```
        String href = outcomeTarget.getHref();
        if (href != null) {
            try {
                if (PrimeApplicationContext.getCurrentInstance(context).getEnvironment().isAtLeastJsf22()
                        && outcomeTarget.isDisableClientWindow()) {

                    clientWindow = context.getExternalContext().getClientWindow();

                    if (clientWindow != null) {
                        clientWindowRenderingModeEnabled = ((ClientWindow) clientWindow).isClientWindowRenderModeEnabled(context);

                        if (clientWindowRenderingModeEnabled) {
                            ((ClientWindow) clientWindow).disableClientWindowRenderMode(context);
                        }
                    }
                }

                url = "#".equals(href) ? "#" : context.getExternalContext().encodeRedirectURL(href, outcomeTarget.getParams());

            }
            finally {
                if (clientWindowRenderingModeEnabled && clientWindow != null) {
                    ((ClientWindow) clientWindow).enableClientWindowRenderMode(context);
                }
            }
        }    

```

**Comment by melloware** [comment]
Looking at this to prevent all the code from being duplicated i think this method needs refactoring.

**Comment by melloware** [comment]
I took a shot at refactoring this method, if felt wrong to repeat all that client window code inside of each IF statement.

**Comment by tandraschko** [comment]
Could someone check if the JSF impls really applies the windowId it to the url and not only for outcome?
I generell i would say the clientWindow should only be appended to internal urls (outcome) and not external (url).

**Comment by tandraschko** [comment]
lets leave it for now, jsf doesn't have a url/href attr.
