### ISSUE TITLE
RowEditor: Not 508 compliant 

### ISSUE THREAD

**Issue by kaushikmeduri** [primefaces/primefaces#4686]
## 1) Environment
- PrimeFaces version:6.1.19
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version:  Jboss 6.0
- Affected browsers: All browsers

## 2) Expected behavior

We are using <p:rowEditor/> 
We are expecting Pencil , Check and Close icons to show Title/Label.

 ...

## 3) Actual behavior

We do not have way to override content / title of .ui-icon-pencil,.ui-icon-check,.ui-icon-close

## 4) Steps to reproduce

use Row Editing  of https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml
Row Editor is   accessibe via key board for   selections . However 
we are expecting  to see title/label for  of .ui-icon-pencil,.ui-icon-check,.ui-icon-close

## 5) Sample XHTML
<p:column style="width:5%;border-left:none;text-align:left;">
<p:rowEditor/>
</p:column>
 

## 6) Sample bean

@ManagedBean(name = "partCBean")
@ViewScoped

public class PartCBean
{
public void onEdit(RowEditEvent event) throws IOException 
{ 

}
public void onCancel(RowEditEvent event)
{
}
}
..

**Comment by tandraschko** [comment]
Feel free to provide a PR

**Comment by kaushikmeduri** [comment]
We do not have fix . Please advise if prime faces can provide a price quote for fixes to be included as patch. In the past our agency has some work done for 508 fixes

**Comment by tandraschko** [comment]
Please see: primefaces.org/support - there is a "get a quote" button

**Comment by melloware** [comment]
@kaushikmeduri This is already implemented. see the documentation for RowEditor is has properties for these titles..
https://primefaces.github.io/primefaces/8_0/#/components/roweditor?id=attributes

However I don't know how to actually set them.  @tandraschko any thoughts?

**Comment by melloware** [comment]
You can do this...
```xml
<p:rowEditor editTitle="Edit Row" cancelTitle="Cancel Edit" saveTitle="Save Row"/>
```

Added example to Showcase and closing this ticket.
