### ISSUE TITLE
SelectOneRadio: label not generating Title for screen readers

### ISSUE THREAD

**Issue by kaushikmeduri** [primefaces/primefaces#4687]
## 1) Environment
- PrimeFaces version:6.1.19
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version:  Jboss 6.0
- Affected browsers: All browsers

## 2) Expected behavior

We are using <p:selectOneRadio label=
We are expecting  label to show up for screen readers.

 ...

## 3) Actual behavior

label is not shown in HTML Output.

## 4) Steps to reproduce

use any of https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml
if Label  is tied to select box then screen reader can detect title.

When we use label attribute <p:selectOneRadio label= EL
https://www.primefaces.org/docs/vdl/4.0/primefaces-p/selectOneRadio.html 
HTML output do not show label.

## 5) Sample XHTML

<p:panel id="isChoiceHeadingY"  >
			
<p:selectOneRadio value="#{testBean.value}" label="#{testBean.label}"  	   >
<f:selectItem  itemLabel="Yes"  itemValue="Yes"  ></f:selectItem>
<f:selectItem  itemLabel="No"  itemValue="No"  ></f:selectItem>
</p:selectOneRadio>
 		
</p:panel>
 

## 6) Sample bean

@ManagedBean(name = "testBean")
@ViewScoped 
public class DynaBean 
{

public String value;
public String label;

public String getValue() 
{
	return value;
}
public void setValue(String value)
{
	value= value;
}

public String getLabel() 
{
	return label;
}
public void setLabel(String label)
{
	label= label;
}

}

**Comment by melloware** [comment]
I am looking at the native JSF selectOneRadio and neither one of them respect the label="" property.

```xml
<h:selectOneRadio value = "#{testView.testString}" label="Label" title="Title"> 
	<f:selectItem itemValue = "1" itemLabel = "Item 1" /> 
	<f:selectItem itemValue = "2" itemLabel = "Item 2" />
</h:selectOneRadio>
```
Looking at the generated output in HTML it uses the title attribute but the label is ignored as each item gets its own label.

```html
<table>
	<tbody><tr>
<td>
<input type="radio" name="j_idt5:j_idt18" id="j_idt5:j_idt18:0" value="1" title="Title"><label for="j_idt5:j_idt18:0"> Item 1</label></td>
<td>
<input type="radio" name="j_idt5:j_idt18" id="j_idt5:j_idt18:1" value="2" title="Title"><label for="j_idt5:j_idt18:1"> Item 2</label></td>
	</tr>
</tbody></table>
```

**Comment by melloware** [comment]
@kaushikmeduri what was your expectation the Radio button would do as far as ARIA or Screenreader?  It does not look like the Label field is the correct field as every radio item gets its own Label.

**Comment by kaushikmeduri** [comment]
We have requirement to associate radio box group title/label to each radio box choice when selecting.
I am trying to find a solution sticking with prime faces tags to associate / group radio box choices to common label/legend
Examples below ....
https://www.w3.org/WAI/tutorials/forms/grouping/ https://webaim.org/techniques/forms/controls#radio

**Comment by melloware** [comment]
Those examples say to use a FieldSet around your radio group?  

So just use a FieldSet from PF: https://www.primefaces.org/showcase/ui/panel/fieldset.xhtml

**Comment by melloware** [comment]
@kaushikmeduri Any update on using the PF FieldSet to accomplish your needs?

**Comment by kaushikmeduri** [comment]
pf field set works some sample code . 
However my root issue is  i am generating  <h:selectOneRadio dynamically and result is  title not being generated. 
I would like <h:selectOneRadio title also to be generated ...Please advise if you think i need to create a seperate ticket for this.  I am unable to give <h:selectOneRadio id dynamically since it wont support EL syntax .

Also when generating dynamically title is not coming

**Comment by melloware** [comment]
I don't think this is actually a Primefaces issue.  I think PF is currently generating all the proper ARIA standards for this unless you can point to a spec where we are not?

This sounds like a custom use case you have and I would recommend closing this ticket.

**Comment by melloware** [comment]
@tandraschko I think this issue is safe to close as its a non-issue.
