### ISSUE TITLE
ImageCropper image is black on Chrome

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#4693]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: WildFly or Jetty
- Affected browsers:

## 2) Expected behavior

ImageCropper show image

## 3) Actual behavior

ImageCropper shows image on Firefox but on Chrome it is black

## 4) Steps to reproduce

take photo with photocam

## 5) Sample XHTML

```
<h:form>
		<p:photoCam widgetVar="photoCam" update="imageCropperFotoId"
			listener="#{testView.oncapture}" />

		<p:commandButton value="Capturar" type="button" ajax="true"
			update="imageCropperFotoId" icon="fa fa-camera"
			onclick="PF('photoCam').capture();" />
		<p:imageCropper prependId="false" initialCoords="0,0,100,100"
			id="imageCropperFotoId"
			image="#{pageContext.servletContext.contextPath}/imagens/#{testView.nomeFoto}" />


	</h:form>
```

## 6) Sample bean

```
package org.primefaces.test;

import java.io.File;
import java.io.FileOutputStream;
import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;

import org.primefaces.event.CaptureEvent;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
	String nomeFoto = String.valueOf(Math.random() * 10000.0) + ".png";
	String path = ((ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext()).getRealPath("")
			+ File.separator + "imagens" + File.separator + nomeFoto;

	public void oncapture(CaptureEvent captureEvent) {
		System.out.println(path);
		try (FileOutputStream fos = new FileOutputStream(path);) {
			fos.write(captureEvent.getData());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public String getNomeFoto() {
		return nomeFoto;
	}

	public void setNomeFoto(String nomeFoto) {
		this.nomeFoto = nomeFoto;
	}

}

```

**Comment by melloware** [comment]
See https://github.com/primefaces/primefaces/issues/2444

**Comment by erickdeoliveiraleal** [comment]
sorry, thank you

**Comment by erickdeoliveiraleal** [comment]
I defined in jsf tag backgroundColor="black" or transparent and the issue persists

**Comment by erickdeoliveiraleal** [comment]
Looks like different issues, since my image is all black. in #2444 only background is black

**Comment by melloware** [comment]
Looks like its a common JCrop reported issue: https://www.google.com/search?q=jcrop+black+image+site:stackoverflow.com&rlz=1C1CHBF_enUS819US819&sa=X&ved=2ahUKEwj90r2I25_hAhXIx1kKHe2oAgcQrQIoBDAAegQIBRAM&biw=1920&bih=947

https://stackoverflow.com/questions/22091164/jcrop-creates-a-black-image-instead-of-new-image
