### ISSUE TITLE
SelectCheckboxMenu: Add ability to provide custom rendering of items in the dropdown menu

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#4696]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: Tomcat 8

## 2) Expected behavior
`selectOneMenu` supports the ability to provide custom rendering of the items in the dropdown list, see "Advanced" example at: https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml
I would expect / it would be nice to have the same ability with `selectCheckboxMenu`.

## 3) Actual behavior
`selectCheckboxMenu` does not allow to change the displaying of elements in the drop down menu.

## 4) Steps to reproduce
Add a `<p:selectCheckboxMenu>` to your facelet, like below.

## 5) Sample XHTML
```xml
<p:selectCheckboxMenu
  value="#{bean.myStrings}" multiple="true" filter="true"
  filterMatchMode="contains" dynamic="true">
    <f:selectItems value="#{bean.allStrings}" var="string"
      itemLabel="#{string.toUpperCase()}" />
    <p:column>
      <h:outputText value="Custom rendering: #{string}" />
    </p:column>
</p:selectCheckboxMenu>
```

## 6) Sample bean
```java
public class MyBean {
  private List<String> myStrings; // getter/setter omitted
  public List<String> getAllStrings() { 
    return Arrays.asList("one", "two", "three");
  }
}
```

**Comment by tandraschko** [comment]
Feel free to sponsor it or provide a PR :)

**Comment by melloware** [comment]
@ltlBeBoy if you comment on this ticket I can assign it to you.

**Comment by ltlBeBoy** [comment]
OK.

**Comment by melloware** [comment]
Added to #8765 which now this will have duplicate ids as well similar to selectone menu
