### ISSUE TITLE
Button: Missplaced active frame with Firefox

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4697]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? no, 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Does not matter
- Affected browsers: Firefox

## 2) Expected behavior
Frame around clicked buttons which only have a icon and no text is close to the button.

## 3) Actual behavior
On Firefox the left frame boarder is moved somewhere to the left

## 4) Steps to reproduce
Use Firefox to go to: https://www.primefaces.org/showcase/ui/button/commandButton.xhtml
and click the button with only the save icon.

![buttonFrameFirefox2](https://user-images.githubusercontent.com/11403755/55056102-7f597980-5065-11e9-8a9c-605515a979c8.jpg)

**Comment by melloware** [comment]
Can you tell if this is Theme related or actually button related?

**Comment by jepsar** [comment]
It's caused by this property:

https://github.com/primefaces/primefaces/blob/c28c0bccc615bffb99c30825c8c7d8084c3a72da/src/main/resources/META-INF/resources/primefaces/forms/forms.css#L376

Is someone already working on a PR?

**Comment by mertsincan** [comment]
Hi,

Could you please try the following css for this issue?

```
<style type="text/css">
body .ui-button.ui-button-icon-only {
  overflow: hidden; 
}
body .ui-button.ui-button-icon-only .ui-button-text {
    text-indent: 0;
    white-space: nowrap;
    visibility: hidden; 
}
</style>
```

**Comment by jepsar** [comment]
@mertsincan looks like less of a hack to me. First test with Firefox is promising. I'll test with Chrome and Safari in a few hours.
