### ISSUE TITLE
p:link href attribute value not relative to conext root in primefaces 7

### ISSUE THREAD

**Issue by jsabev** [primefaces/primefaces#4699]
## 1) Environment
- PrimeFaces version: 7.0
- Does not work with latest snapshot version.
- Affected browsers: ALL

## 2) Expected behavior

<p:link> components with href attributes result in absolute server root rather than being relative to the application context as was the case in previous prime faces releases.

<p:link href="/logout" /> should render a link <applicationcontext>/logout. This has been the standard behaviour in primefaces prior to version 7.0

## 3) Actual behavior

In PrimeFaces 7.0

<p:link href="/logout"> renders a link as /logout. The root of the link is not relative to the application context.

**Comment by melloware** [comment]
This was done on purpose.  See the migration guide: https://github.com/primefaces/primefaces/wiki/Migration-Guide

Fixed because of this issue: https://github.com/primefaces/primefaces/issues/3506

**Comment by tandraschko** [comment]
Yup. Use Outcome or append it by request.contextPath

**Comment by jsabev** [comment]
Thanks. Somehow I missed that. Closing issue.
