### ISSUE TITLE
PanelGrid: borders in header and footer are not visible with luna and nova themes

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#4708]
## 1) Environment
- PrimeFaces version: 7.0
- Application server + version: ALL
- Affected browsers: ALL

## 2) Expected behavior
Visible borders

## 3) Actual behavior
Not visible borders.

## 4) Steps to reproduce
Go to https://www.primefaces.org/showcase/ui/panel/panelGrid.xhtml
, choose nova-dark, nova-colored or one of the luna themes and look at the grouping section.

**Comment by tandraschko** [comment]
@mertsincan can you check that? nova scss is not public
