### ISSUE TITLE
Nova and Luna themes: FontAwesome icons are wrongly sized.

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#4709]
## 1) Environment
- PrimeFaces version: 7.0
- Application server + version: ALL
- Affected browsers: ALL

## 2) Expected behavior
PrimeIcons and FontAwesome icons have similar sizes.

## 3) Actual behavior
![Cattura](https://user-images.githubusercontent.com/18428155/55277076-3838e600-52fc-11e9-92d6-0a6a88531717.JPG)

## 4) Steps to reproduce
Enable FontAwesome in web.xml or add it with css.

## 5) Sample XHTML
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head/>

    <h:body>
		
		<p:button href="#" icon="fa fa-star" value="fa"/>

		<p:button href="#" icon="pi pi-star" value="pi"/>

    </h:body>
</html>
```

## 6) Sample bean
Not needed.

## 7) Additional notes
FontAwesome 5+ icons are affected too.

**Comment by melloware** [comment]
It looks like I see this style in the nova and luna themes.

```css
body .pi {
  font-size: 1.25em; 
}
```

Can you see if setting FontAwesome to the same size in a local style sheet works?  That way we can at least recommend a fix.

```css
body .fa {
  font-size: 1.25em; 
}
```

**Comment by NicolaIsotta** [comment]
I've had some time to debug.
First thing I've noticed is that PrimeIcons are considerably smaller than FontAwesome icons, but I guess that's a design choiche.
To make them bigger, the themes change the font-size. The problem is that they do it two times:
https://github.com/primefaces/primefaces/blob/9b145fa0c4557fc33f72313cb1022588e31ff814/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css#L51-L54
https://github.com/primefaces/primefaces/blob/9b145fa0c4557fc33f72313cb1022588e31ff814/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css#L63-L64
While the second rule affects only PrimeIcons, the first one includes fa icons too, when they're included e.g. in a button.
I've tried to remove the `font-size` in the `body .ui-icon` rule and the result is much better:
![fixed](https://user-images.githubusercontent.com/18428155/55405614-c3171c00-555a-11e9-9083-32d62d6f2ad0.JPG)

**Comment by melloware** [comment]
@mertsincan I would submit a PR but I have a feeling this is something you have to edit in the SASS that we don't have access to.

**Comment by mertsincan** [comment]
The value of font-size is 1.25em on the fa-* and pi-* icons . This issue is related to drawing of star icons.

pi/fa-home;
![image](https://user-images.githubusercontent.com/11868120/58002206-678ef680-7ae6-11e9-96ab-06861535bd3e.png)

Therefore, you can set the styles according to yourself. Exp; for the fa-fa-star, please use font-size: 1em;
