### ISSUE TITLE
PF 7 User Guide not savable / offline readable

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#4713]
The new documenation can also be referenced from outside, thats good. Hovever, formerly you could use it offline, but currently, we can't save it from web as the result can't be searched any more and some "undefined" occur in the navigation, at least if I save from Chrome. So, for me, it would be better to have a searchable offline PDF or repair link issues.

**Comment by tandraschko** [comment]
Feel free to work on it ;)
We won't the change the format again, so try to find a better way to convert it to a PDF.

**Comment by mdzaebel** [comment]
Might be better to gather requirements, before changing things in the coolest newest way.

**Comment by fcorneli** [comment]
> Might be better to gather requirements, before changing things in the coolest newest way.

Not needed anymore, welcome to the new world!
:)

**Comment by jepsar** [comment]
If you want to have an offline copy, you could use `wget` to download it.

**Comment by melloware** [comment]
Looks like this is what you need for using Docsify offline  https://github.com/docsifyjs/docsify/blob/master/docs/pwa.md
