### ISSUE TITLE
Calendar: if popup shows date and time it is placed in front of input field

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#4719]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No, 7.1
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Wildfly 10.1
- Affected browsers: Firefox, Chrome, ...

## 2) Expected behavior

Calendar popup open below or above the input field.

## 3) Actual behavior

If is not enough space below the input field, the popup is placed above the input field. But it seams as if the additional space for the time part is not taken into account. 
Because of that the calendar popup is hiding input field.

## 4) Steps to reproduce
1. Got to the showcase, https://www.primefaces.org/showcase/ui/input/calendar.xhtml
1. make the browser window small
1. scroll the 'Datetime' input to the bottom of the view port
1. click into the input
1. the calendar popup opens in front of the input field

![calendarPopupBelowInput](https://user-images.githubusercontent.com/11403755/55628603-72e5c700-57b1-11e9-9391-1e8448eb7f0d.jpg)
![calendarPopupAboveInput](https://user-images.githubusercontent.com/11403755/55628614-78dba800-57b1-11e9-9e15-a3add1c33bbe.jpg)

**Comment by melloware** [comment]
The calendar hit logic decides to draw it either up or down based on whether it would fall off the screen.  In your case above it looks like it can't safely draw it above or below the text box so it must be doing some other logic to try and make it fit on screen.

**Comment by OBreidenbach** [comment]
Even if there is enough space above the input field the popup is placed in front of the input. I have the impression that the time part of the popup is not taken into account.
![popupInFrontOfInput](https://user-images.githubusercontent.com/11403755/55704984-ef5ced80-59dd-11e9-82fa-607cbc7f7bf3.jpg)


After resizing the browser window the popup jumps to the right place.
![popupAfterResizing](https://user-images.githubusercontent.com/11403755/55704830-7bbae080-59dd-11e9-967c-2e561d0d8cba.jpg)

## Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
    <div style="height: 500px;"></div>
    <h:panelGrid columns="2" cellpadding="5">
        <p:outputLabel for="datetime" value="Datetime:"/>
        <p:calendar id="datetime" pattern="MM/dd/yyyy HH:mm:ss"/>

        <p:outputLabel for="popup" value="Popup:" />
        <p:calendar id="popup" />
    </h:panelGrid>
</h:body>
</html>
```

**Comment by OBreidenbach** [comment]
I did some debugging and found the following.
The position is calculated in 
https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.js#L7521
before the time part is added to popup in 
https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js#L313
so I did some hacking in
https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.timepicker.js#L1453
```
$.datepicker._updateDatepicker = function (inst) {

    // don't popup the datepicker if there is another instance already opened
    var input = inst.input[0];
    if ($.datepicker._curInst && $.datepicker._curInst !== inst && $.datepicker._datepickerShowing && $.datepicker._lastInput !== input) {
        return;
    }

    if (typeof(inst.stay_open) !== 'boolean' || inst.stay_open === false) {

        // this._base_updateDatepicker(inst); patch

        // Reload the time control when changing something in the input text field.
        var tp_inst = this._get(inst, 'timepicker');
        if (tp_inst) {
            tp_inst._addTimePicker(inst);
        }
        // patch begin
        this._base_updateDatepicker(inst);
        if (tp_inst) {
            tp_inst._addTimePicker(inst);
        }
        // patch end
    }
};
```
which did the trick for me. But I guess there are much more elegant solutions for this bug.

**Comment by melloware** [comment]
I would submit this as a patch and add the info to \src\main\resources\META-INF\resources\primefaces\jquery\extensions.txt you will see we have commented other specific fixes in there.

**Comment by melloware** [comment]
Actually i will submit a PR if you don't mind?

**Comment by melloware** [comment]
OK can you review my PR.  We already had $.datepicker._updateDatepicker overridden in jquery.pfextensions.js file so I just tweaked it with your change.

**Comment by OBreidenbach** [comment]
What can I say. It is my solution and it solves the problem.
But for me it looks some how clumsy to have to call the _addTimePicker method twice. So I thought you guys know a better solution.

**Comment by melloware** [comment]
Well I know why the solution works, but don't really know of any better options without hacking the internals of the component.

**Comment by OBreidenbach** [comment]
Then so be it.

**Comment by OBreidenbach** [comment]
Just noticed that clicking a day in the popup let jump it in front of the input again.

**Comment by OBreidenbach** [comment]
Maybe #4732 is a nicer solution. For sure it also fixes the positioning on doing selections in the popup.

**Comment by OBreidenbach** [comment]
Any plans to fix this? What is wrong with my PR?

**Comment by tandraschko** [comment]
I would like to leave such changes to mert. He knows the calendar much better as more.

Also i'm a big advocate of not changing third-party code and fix it where it comes from. (but thats only my opinion)

**Comment by OBreidenbach** [comment]
But Primefaces adds the time sliders to the popup. So Primefaces has to take care about the larger popup.
