### ISSUE TITLE
Calendar: DateTimePicker error in javascript for mode="inline"

### ISSUE THREAD

**Issue by gollrich** [primefaces/primefaces#472]
I´m reopening an bug from your old issuetracker...

https://code.google.com/p/primefaces/issues/detail?id=6790&thanks=6790&ts=1397477544

for more information also read 
http://stackoverflow.com/questions/23036356/bug-in-primefaces-calendar-timepicker

issues still exists in 5.1.19 and 5.2.6

**Comment by squaregoldfish** [comment]
This bug still exists in 6.1

**Comment by gollrich** [comment]
thanks good to know, still using 6.0.3, but removed all the inline calendar now.... lost the hope that the problem would be fixed any time soon.

**Comment by tandraschko** [comment]
@gollrich You can still analyse the problem and maybe provide a PR ;)

**Comment by matsandreassen** [comment]
Hi!

We're encountering this same problem in 6.1.9. When combining "inline" with date time pattern like this:

`<p:outputLabel for="startTime" value="Start: " />
<p:calendar id="startTime" value="#{editControlBean.currentControl.startTime}" mode="inline" pattern="dd/MM/yyyy HH:mm" />
`

we get a validation error like this: "Start '16/11/2017' could not be understood as a date and time"

The forum post https://forum.primefaces.org/viewtopic.php?p=95453 seems to contain a _potential_ patch

**Comment by melloware** [comment]
From looking at his potential patch that definitely seems like a hacky way to try and fix it.  I think its seems like something else simpler is missing because this component works fine with DateTime's when not using inline mode so we know it "can" work.

**Comment by melloware** [comment]
OK I modified his patch slightly, tested it and submitted a PR.

**Comment by matsandreassen** [comment]
That's great news! Here's hoping it's included in 6.1.10.

**Comment by matsandreassen** [comment]
Any possiblity of getting this ported to 6.1.14?

**Comment by melloware** [comment]
@mertsincan can you port this into 6.1.14 please?
