### ISSUE TITLE
[Documentation]: Docsify Search doesn't find attributes

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#4720]
At least component and attribute names should be found by the new web search in the user guide, that is currently not savable any more. However, e.g. looking for **skipChildren** doesn't work, even if it occurs in 4 PF components. Attributes seem to be ignored? While markdown is certainly the right direction, at least essential usecases should be possible that were possible before.

**Comment by melloware** [comment]
Not much documentation on the full text search of Docsify: https://docsify.js.org/#/plugins?id=full-text-search

So not sure how its determining what is in the full text search?  Something called "headlineDepth" is the only real parameter I see.

**Comment by melloware** [comment]
OK found an open issue it does not search tables: https://github.com/docsifyjs/docsify/issues/582

**Comment by tandraschko** [comment]
@melloware can we patch the search.js and deliver it in via our repo instead using unpkg.com? (see index.html)

**Comment by tandraschko** [comment]
i tried to apply the patch but it throws errors now.
I will close this for now. If a new docsify is released someday, the documentation will automatically use the newer version.
