### ISSUE TITLE
Inplace: callBehavior misses options

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4721]
## 1) Environment
- PrimeFaces version: 7.0
- It works with: 6.2
- Application server + version: Wildfly 10.1
- Affected browsers: All

## 2) Expected behavior
`p:inplace` with embedded `p:ajax` switches back to view-mode when save or cancel button is pressed.

## 3) Actual behavior
It stays in edit-mode

This wrong behavior was introduce during refactor in c2fe208. It changed
```
var saveBehavior = this.cfg.behaviors['save'];
 saveBehavior.call(this, options);
```
to
```
this.fireBehaviorEvent('save');
```
and misses the second argument `, options`.

## 4) Steps to reproduce
 - Click on inplace to enter edit-mode
 - Click save to fire ajax and switch back to view-mode

## 5) Sample XHTML
```
<p:inplace>
    <p:ajax event="save" /> <!-- no update attribute -->
</p:inplace>
```

## 6) Sample bean
Not needed

**Comment by fanste** [comment]
PR #4722

**Comment by tandraschko** [comment]
thanks for the PR!

@mertsincan can be merged to elite
