### ISSUE TITLE
SelectOneMenu: flickers + unwanted horizontal scroll bar with Edge & IE

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#4723]
## 1) Environment
- PrimeFaces version: 7.0
- Application server + version:
- Affected browsers: Edge 44 & IE 11 (Firefox too but without flicker)

## 2) Expected behavior
No flicker, no horizontal scroll bar.

## 3) Actual behavior
![bug](https://user-images.githubusercontent.com/18428155/55642662-63767600-57d1-11e9-933d-4027a7a6394f.gif)

## 4) Steps to reproduce
To reproduce the flicker, go to [the showcase](https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml) and open the the Grouping menu. I 've prepared a little reproducer for the horizontal scroll bar problem.

## 5) Sample XHTML
```xhtml
<h:form id="form1">
	<p:selectOneMenu id="testSelect">
		<f:selectItem itemValue=""/>
		<f:selectItem itemValue="LOOOOOOONG1" itemLabel="LOOOOOOONG1"/>
		<f:selectItem itemValue="LOOOOOOONG2" itemLabel="LOOOOOOONG2"/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
		<f:selectItem itemValue="" itemLabel=""/>
	</p:selectOneMenu>
</h:form>
```

## 6) Sample bean
Not needed

**Comment by melloware** [comment]
can you investigate if it s style related?

**Comment by melloware** [comment]
Lots of issue related to IE and Edge and this component:
https://github.com/primefaces/primefaces/issues/3863
https://github.com/primefaces/primefaces/issues/884

**Comment by NicolaIsotta** [comment]
I tried to debug, but I'm not really a js expert, so far I've not found the cause.
Meanwhile I've found out Firefox is affected too (even though without the flicker).

**Comment by melloware** [comment]
OK narrowed it down.  If you use `effect="none"` on your selectOne this issue does not happen.  It only happens when using the animation effect here:
https://github.com/primefaces/primefaces/blob/c8e95abf9341d9abffc4046156ddea4606ff4992/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L689-L703

**Comment by melloware** [comment]
Going to close this one since the workaround is to use effect="none" to turn the animation off.  If someone feels strongly about IE/Edge issue in the future we can re-open.
