### ISSUE TITLE
CellEditor: Dynamic columns cellEdit event

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#4724]
The components _p:dataTable_ and _p:treeTable_ both have the following problem:
## 1) Environment
- All PF, browser and AppServer versions

## 2) Expected behavior
  * Event.old/new values should not be null
  * onCellEditInit should be called
  * Documentation of p:cellEditor should reference p:treeTable too
  * Documentation of p:treeTable should explain, why there are no cellEditInit and cellEditCancel events documented.

## 3) Actual behavior
  * "cellEdit" event.old/new values are null for value expressions like #{bean.values[index]}
  * cellEditInit not signaled?

## 4) Steps to reproduce
Change first "val" in the upper table to "val2".
![grafik](https://user-images.githubusercontent.com/415392/55672803-94bd7780-589f-11e9-94c7-bf29943aeadc.png) 
![grafik](https://user-images.githubusercontent.com/415392/55672879-87ed5380-58a0-11e9-948d-b8b522d95b78.png) This is correct.

Now, change "values1" to "values11".
![grafik](https://user-images.githubusercontent.com/415392/55672908-fcc08d80-58a0-11e9-9be3-e6902274d42c.png)
The old and new value in the event is null, which is wrong. Additionally, there is no event fired for *cellEditInit*. I'd recommend, to add test cases for any event into the showcase, as just this case is missing.

Note that form of ValueExpression is absolute important for anyone, who has a data model with a dynamic length of values in a list. Note that this usecase - which seems to be quite normal - is not in you showcases, even if you have "dynamic columns", which however are fixed to possible fields. I don't see an other option to implement a p:dataTable with an unknown number of columns. If there is any workaround, I'd be very interested. Otherwise, could you give me some hints on how to fix it?

## 5) Sample XHTML
```xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui">
<h:head />
<h:body>
  <h:form id="form">
  <p:growl id="growl" sticky="true"/>
    <p:dataTable value="#{[0]}" var="v" editMode="cell" editable="true" tableStyle="display: inline">
      <p:ajax event="cellEdit" listener="#{bean.onCellEdit}" update=":form:growl" />
      <p:ajax event="cellEditInit" listener="#{bean.onCellEditInit}" update=":form:growl" />
      <p:ajax event="cellEditCancel" listener="#{bean.onCellEditCancel}" update=":form:growl" />
      <p:columns var="c" value="#{[0,1]}">
        <p:cellEditor>
          <f:facet name="input"> 
            <p:inputText value="#{bean.val}" />
          </f:facet>
          <f:facet name="output">#{bean.val}</f:facet>
        </p:cellEditor>
      </p:columns>
    </p:dataTable>
    <p:dataTable value="#{[0]}" var="v" editMode="cell" editable="true" tableStyle="display: inline">
      <p:ajax event="cellEdit" listener="#{bean.onCellEdit}" update=":form:growl" />
      <p:columns var="c" value="#{[0,1]}">
        <p:cellEditor>
          <f:facet name="input">
            <p:inputText value="#{bean.values[c]}" />
          </f:facet>
          <f:facet name="output">#{bean.values[c]}</f:facet>
        </p:cellEditor>
      </p:columns>
    </p:dataTable>
  </h:form>
</h:body>
</html>
```
## 6) Sample bean
```java
@SessionScoped @Named
public class Bean implements Serializable {	
	String val="val";
	public String getVal() { return val; }
	public void setVal(String val) { this.val = val; }
	
        List<String>values=new ArrayList<>(Arrays.asList("values1","values2"));
        public List<String> getValues() { return values; }
        public void setValues(List<String> values) { this.values = values;  }
	
	public void onCellEdit(CellEditEvent e) { info("cellEdit", e); }
	public void onCellEditInit(CellEditEvent e) { info("cellEditInit", e); }
	public void onCellEditCancel(CellEditEvent e) { info("cellEditCancel", e); }
	
	public static void info(String method, CellEditEvent e) {
		String message=String.format("%s: old=%s, new=%s",
				method, e.getOldValue(), e.getNewValue());
		FacesContext.getCurrentInstance().addMessage(null, 
				new FacesMessage(message));
	}
}
```

**Comment by mdzaebel** [comment]
Workaround deleted.

**Comment by tandraschko** [comment]
a deeper analysis / PR would be great. Not sure if its related to PF only.

**Comment by mdzaebel** [comment]
My deeper analysis revealed, that even the workaround above does not work. Additionally, I recognized, that the problem does not occur, when I don't use **p:columns** (e.g. in a p:dataTable). So currently, p:columns could not be edited (and you don't have a testcases for it), but I have quite a lot of similar logic in each column, so I urgently need the ability to use <p:ajax event="cellEdit" ...> with p:columns. Any idea of when this could be fixed?

**Comment by tandraschko** [comment]
No plans from my side, i even never used p:columns :D

As always, you have 3 ways:
1) fix it by yourself and provide a PR
2) wait until someones fixes it
3) use PrimeFaces PRO

**Comment by melloware** [comment]
SHould we update the title of this to something like "CellEditor: Dynamic columns cellEdit event"

**Comment by mdzaebel** [comment]
As you like. The culprit component seems to be `p:columns`. By the way, the proposal of Thomas does not work for me, as the use of `c:forEach` with `p:column` would evaluate at build time, but it's inside a `ui:repeat` of which values are not available in the build phase.

**Comment by mafaul** [comment]
It worked in PF 6.2 + JSF 2.2, it does not work in PF 7+ JSF 2.3 anymore.
I suspect that this was exactly the same issue: https://github.com/primefaces/primefaces/issues/4765
When using p:columns the filterBy value is not passed to the LazyDataModel

**Comment by mafaul** [comment]
[sample.zip](https://github.com/primefaces/primefaces/files/3264787/sample.zip)
Herewith a sample project to easily view issues.
Tested on Payara 5.191 running AWS Corretto jdk1.8.0_202
**Actual Outcome:**
![image](https://user-images.githubusercontent.com/12007706/59087433-e49ed600-8904-11e9-9cad-145a2d3f9d28.png)
**Expected outcome:**
    Old: Hello 3
    New: test
    Field: string
    RowNo: 4

**Comment by mafaul** [comment]
https://www.bountysource.com/issues/72488814-celleditor-dynamic-columns-celledit-event

**Comment by mdzaebel** [comment]
I retested successfully with 8.0-SNAPSHOT for `p:dataTable`. However, `p:treeTable` does not work. Here is the sample for p:treeTable:

## Bean3.java

``` java
@SessionScoped @Named
public class Bean3 implements Serializable {
  private static final long serialVersionUID = 1L;

  public class Test implements Serializable { // Content class of TreeNodes
    private static final long serialVersionUID = 1L;	
    public String value;
    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }

    public int index;
    public int getIndex() { return index; }
    public void setIndex(int index) { this.index = index; }
		
    public Test(String value, int index) { this.value=value; this.index=index; }
  }
	
  TreeNode root;
  public TreeNode getRoot() { return root; }
  public void setRoot(TreeNode root) { this.root = root; }

  public void createTreeNodes() { 
    root=new DefaultTreeNode(new Test("Root", 0), null);
	new DefaultTreeNode(new Test("One", 1), root);
	new DefaultTreeNode(new Test("Two", 2), root);
  }
  @PostConstruct public void init() { createTreeNodes(); }
	
  public void onCellEdit(CellEditEvent<?> e) { info("cellEdit", e); }
  public void onCellEditInit(CellEditEvent<?> e) { info("cellEditInit", e); }
  public void onCellEditCancel(CellEditEvent<?> e) { info("cellEditCancel", e); }
	
  public static void info(String method, CellEditEvent<?> e) {
    String message=String.format("old=%s, new=%s", e.getOldValue(), e.getNewValue());
    FacesContext.getCurrentInstance().addMessage(null, 
      new FacesMessage(FacesMessage.SEVERITY_INFO, method+":", message));
  }
}
```
## treeTable.xhtml
``` xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
   xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui" >
<h:head />
<h:body>
  <h:form id="form">
    <p:growl id="msgs" showDetail="true"/>
    <p:treeTable value="#{bean3.root}" var="var" editMode="cell" editable="true" tableStyle="width:auto">
      <p:ajax event="cellEditInit" listener="#{bean3.onCellEditInit}" update=":form:msgs"/>
      <p:ajax event="cellEdit" listener="#{bean3.onCellEdit}"  update=":form:msgs"/>
      <p:columns var="property" value="#{['value','index']}"  headerText ="#{property}">
        <p:cellEditor>
          <f:facet name="output"><h:outputText value="#{var[property]}" /></f:facet>
          <f:facet name="input"><p:inputText value="#{var[property]}" /></f:facet>
        </p:cellEditor>
      </p:columns>
    </p:treeTable>
  </h:form>
</h:body>
</html>
```
## Reproduce
- Click in the top/left cell and change the value. It will not change (bug).
  - The message shows `cellEdit: old=One, new=One`, but `new` should be changed.
  - Also, cellEditInit is not fired for treeTable (but for dataTable)
- Hovever, in the second row, it works
