### ISSUE TITLE
Menus: allow custom content

### ISSUE THREAD

**Issue by AdolfGalland** [primefaces/primefaces#4738]
[BrokenMenu.zip](https://github.com/primefaces/primefaces/files/3080005/BrokenMenu.zip)
## 1) Environment
- PrimeFaces version: 7.0 or 6.2
- Does it work on the newest released PrimeFaces version? Version?No
- It works with PrimeFaces 5.2
- Application server + version: Payara 5
- Affected browsers: FireFox 61

## 2) Expected behavior
The index page should be sent to the browser

## 3) Actual behavior
The browser receives an error page with the sign: "MenuItem must be inside a form element" 

## 4) Steps to reproduce
Load the index page
## 5) Sample XHTML
<p:menubar >
            <p:submenu  label="Cane" >
                <p:menuitem value="Broken menu" >
                    <h:link outcome="SecondPage" value="SecondPage" />
                </p:menuitem>
            </p:submenu>
        </p:menubar>
## 6) Sample bean
[BrokenMenu.zip](https://github.com/primefaces/primefaces/files/3080012/BrokenMenu.zip)

..

**Comment by melloware** [comment]
Yes but the error says "MenuItem must be inside a form element" You need to put it inside an `<h:form>`.

It will not work without one.

**Comment by tandraschko** [comment]
The question is if the case is valid?
A form is required when a POST request must be generated, which is actually not required in this case.

**Comment by tandraschko** [comment]
Currently it's by design.
If you remove the "value" attr, your link is rendered correctly.

Its still requires a form as a POST script is rendered per default.

**Comment by tandraschko** [comment]
I reverted it for now as it breaks a simple case:

`                            <p:menuitem icon="fa fa-building"  
                                        action="#{indexController.company}"  
                                        update="@form">  
                                <p:spacer width="10"/>MyMenuItem  
                            </p:menuitem>`

The reason is that "custom content" isnt the same as "no onclick required".
If you check MenuItemAwareRenderer#encodeOnClick, it's quite easy to check if a GET request is required.
But what about POST?
Not sure if we can determine it automatically.

Maybe we need a attribute on the menuItem like "submitting=false" or something.

WDYT @melloware @Rapster ?

**Comment by melloware** [comment]
maybe just `"submit=false"` ??

**Comment by Rapster** [comment]
Is it possible to update the ticket, i'm not sure I'm following what's wrong?

**Comment by tandraschko** [comment]
The problem is that the menu always automatically renders a onclick with either a POST or GET script.
But in the case from the reporter, he has his own link and don't need a onclick.

**Comment by Rapster** [comment]
What about using a facet to override this?

**Comment by tandraschko** [comment]
facet name=action?

**Comment by Rapster** [comment]
yes it's just a thought, but with name=custom sounds better

**Comment by matinh** [comment]
If somebody will have a look at this, please also consider components other than `<h:link>`. It would be really nice if one could use `<p:toggleSwitch>` or `<p:button>` inside `<p:menuItem>` to create menus like modern browsers have for zoom/unzoom or cut/copy/paste.
This basically comes down to just render child-components if present. Or maybe some new component like `<p:menuItemWithInputs>` would be needed for this.

**Comment by melloware** [comment]
@matinh I think this might be a pretty invasive change.  It might only get implemented with PRO sponsorship or a 1 time quote from PrimeTek.

**Comment by tandraschko** [comment]
I dont think it's invasive; we just need a facet to render custom content?

**Comment by melloware** [comment]
Oh you think it will be that easy?  OK!

**Comment by melloware** [comment]
OK it doesn't look like MenuItem can have facets in their current state since its not a component?

**Comment by Rapster** [comment]
It is a UIComponent, unless we're not talking about the same UIMenuItem

**Comment by melloware** [comment]
Ahhh you are right I was casting MenuItem as the interface not as a `UIMenuItem` so I saw no `getFacet` but if i cast it to UIMenuItem it is there!  DOH!

**Comment by melloware** [comment]
OK PR Added. Reproducer: 
[pf-4738.zip](https://github.com/primefaces/primefaces/files/10466485/pf-4738.zip)

You can simply do this now to completely control the rendering of a MenuItem.

```xml
<p:menubar>
	<p:submenu label="Cane">
		<p:menuitem>
			<f:facet name="custom">
				<h:link outcome="SecondPage" value="SecondPage"/>
			</f:facet>
		</p:menuitem>
	</p:submenu>
</p:menubar>
```
