### ISSUE TITLE
SelectCheckboxMenu: IllegalArgumentException caused by giving Collection parameter instead of Array

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#4742]
## 1) Environment
- PrimeFaces version: 7.1-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? Yes, OK in 7.0
- Does it work on the newest sources in GitHub? Not Working
- Application server + version: Wildfly 10.1.0.Final
- Affected browsers: All

## 2) Expected behavior

Don't get the error 500 and show selectCheckboxMenu:
>java.lang.IllegalArgumentException: Argument is not an array

## 3) Actual behavior

Exception IllegalArgumentException thrown in method encodeMultipleLabel from class SelectCheckboxMenuRenderer at line :
```java
int length = Array.getLength(valuesArray);
```

In the problem case valuesArray is a Collection.

## 4) Steps to reproduce

Add multiple="true" to selectCheckboxMenu component.

## 5) Sample XHTML

```xhtml
<h:body>
	<h:form>
		<p:selectCheckboxMenu value="#{testView.stringValues}" multiple="true" label="Test" updateLabel="true">
			<f:selectItems value="#{testView.items}" />
		</p:selectCheckboxMenu>
	</h:form>
</h:body>
```

## 6) Sample bean

```java
@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
    
    private static final long serialVersionUID = 1L;
	
	private List<SelectItem> items;
	private List<String> stringValues;

	@PostConstruct
	public void init() {
		items = new ArrayList<>();
		stringValues = new ArrayList<>();
		
		items.add(new SelectItem(null, "One"));
		items.add(new SelectItem("two","Two"));
		items.add(new SelectItem("three"));
		items.add(new SelectItem(null));
	}

	public List<SelectItem> getItems() {
		return items;
	}

	public void setItems(List<SelectItem> items) {
		this.items = items;
	}
	
	public List<String> getStringValues() {
		return stringValues;
	}

	public void setStringValues(List<String>  stringValues) {
		this.stringValues = stringValues;
	}
}
```

It seems to be caused by #4712 correction

**Comment by tandraschko** [comment]
Can't replicate it

**Comment by brivalin** [comment]
Can you try with this ? It runs on 7.1-SNAPSHOT and simulate my problem.

[PF_4742.zip](https://github.com/primefaces/primefaces/files/3085305/PF_4742.zip)
