### ISSUE TITLE
ChartJs : CartesianLinearTicks Does not have property for Precision

### ISSUE THREAD

**Issue by carlbradwell17** [primefaces/primefaces#4743]
## 1) Environment
- PrimeFaces version: 7.0.0

## 2) Expected behavior

I expect to be able to set the precision for ticks, as per https://www.chartjs.org/docs/latest/axes/cartesian/linear.html

I want to be able to keep the dynamic ticks (i.e. not define the Steps), but keep the scale as integers.

## 3) Actual behavior

All other options are present in the CartesianLinearTicks class, yet precision is missing. The dynamic ticks on the y-axis scale down to 0.5 in my scenario.

## 4) Steps to reproduce

Produce a LineChart with:

List<Number> values = new ArrayList<>();
        values.add(1);
        values.add(4);

**Comment by melloware** [comment]
I can fix this one.
