### ISSUE TITLE
Documentation ToggleSwitch

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4745]
https://primefaces.github.io/primefaces/7_0/#/components/toggleswitch?id=toggleswitch

There is no onLabel="yes" offLabel="no" for ToggleSwitch

![image](https://user-images.githubusercontent.com/15189434/56308798-23d75480-6116-11e9-9fbd-433601c04414.png)

**Comment by tandraschko** [comment]
Please provide a PR, this is even the same amount of work as creating this ticket :D
And feel free to skip creating a issue for a docu PR.
