### ISSUE TITLE
Spinner: add precision attr

### ISSUE THREAD

**Issue by fcanevar** [primefaces/primefaces#475]
I've noticed that the parameter "cfg.precision" is based on the stepFactor, that assumption is not always correct in my case. For example I could have a quantity of 2.75 meters and a stepFactor of 5 meters but the precision requested is 2 and not 0, I think it should be a parameter as the stepFactor is.

**Comment by melloware** [comment]
Fixed in PF 6.2 by this ticket which added DecimalPlaces attribute. https://github.com/primefaces/primefaces/issues/2751
