### ISSUE TITLE
Datepicker multiple months navigator duplicates month names

### ISSUE THREAD

**Issue by denizque** [primefaces/primefaces#4751]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Jetty 9.3.5.v20151012
- Affected browsers: Opera

## 2) Expected behavior
Month names in multi range selection be one after another.
i.e. datepicker with numberOfMonths="3" and monthNavigator="true" to have Month navigator months as: January, February,  March. 

Or perhaps as an idea could be instead of showing month navigator in both 3 month panels, it can show only in one of the panels.

## 3) Actual behavior
Instead of January, February, March, it shows January, January, January.

## 4) Steps to reproduce
Use the sample from show show case with parameters: numberOfMonths="3" monthNavigator="true"

## 5) Sample XHTML
<p:datePicker id="dateFromTo" selectionMode="range" value="#{bean.range}" readonlyInput="true" numberOfMonths="3" yearRange="2000:2050" yearNavigator="true" monthNavigator="true" />

## 6) Sample bean

..

**Comment by melloware** [comment]
@christophs78 Also this one, I verified its an issue with the example above.

**Comment by christophs78** [comment]
Same issue with yearPicker.

Notes for myself:
0-datepicker.js
- Functions renderTitleMonthElement, renderTitleOptions
- updateViewDate, _setInitOptionValues

`_setInitOptionValues` is the one we need to fix.

**Comment by christophs78** [comment]
https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts is implemented Angular-specific. But quite sure, it has the same issue.
