### ISSUE TITLE
Wizard: add behavior support

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#4755]
The component `<p:wizard>` already supports the events `onnext` and `onback`. It would be nice to also support `oncomplete` to call some JavaScript when the AJAX request finished. `onsuccess` and `onerror` would also be great to have.

**Comment by tandraschko** [comment]
Normally we don't have on* ajax events on the component itself BUT we provide a way to overwrite the AJAX request options via 
`<p:ajax event="...." on*="...." />`

**Comment by tandraschko** [comment]
PR welcome ofcourse!

**Comment by matinh** [comment]
Well, it doesn't really matter (to me) how this feature would be implemented. But currently `<p:wizard>` doesn't support `<p:ajax>` as a child and there are already `onnext` and `onback` events, so I thought, this would be the best way.
