### ISSUE TITLE
MethodExpression support for p:grahicImage 

### ISSUE THREAD

**Issue by patrickgarner** [primefaces/primefaces#476]
org.primefaces.el.ValueExpressionAnalyzer doesn't allow nested method call per EL spec.  One must use nested property instead.

```
at org.primefaces.el.ValueExpressionAnalyzer.intercept(ValueExpressionAnalyzer.java:69) [primefaces-5.2.jar:5.2]
at org.primefaces.el.ValueExpressionAnalyzer.getExpression(ValueExpressionAnalyzer.java:44) [primefaces-5.2.jar:5.2]
```

Please see http://stackoverflow.com/q/31037315/984932 for a discussion on this.

**Comment by tandraschko** [comment]
Currently graphicImage shoudln't even support a single MethodExpression.
I will improve this for further versions.

**Comment by cagataycivici** [comment]
I also agree that we should throw exception or something when a method is bound, only values should be allowed per implementation.

**Comment by tandraschko** [comment]
Should be fixed, please give it a try.
