### ISSUE TITLE
Tree: NodeSelectEvent has no TreeNode when dynamic="true"

### ISSUE THREAD

**Issue by theobisproject** [primefaces/primefaces#4760]
## 1) Environment
- PrimeFaces version: 7.0
- Application server + version: Wildfly 13
- Affected browsers: IE, Firefox, Chrome

## 2) Expected behavior

The NodeSelectEvent contains the selected TreeNode regardlessly if the dynamic attribute is `true` or `false`.  
This was the behaviour up until 6.2.

## 3) Actual behavior

Since 7.0 the selected TreeNode is only contained if the dynamic attribute is `false`

## 4) Steps to reproduce

Checkout the repository https://github.com/theobisproject/primefaces-test on the `tree-null-node` branch. Switch the dynamic attribute on and off. A Nullpointer is thrown when `dynamic="true"` is set.

**Comment by maasvdberg** [comment]
Broken by c637e47

**Comment by selvait90** [comment]
I stuck with the same scenario, what is the release date of version 7.1 which has this fix. Is there any other workaround to handle this problem/use fix until launch of version 7.1 .

**Comment by melloware** [comment]
@selvait90 if you need this fix right now just add this JS snippet to your page which inline patches it with this fix.

```javascript
PrimeFaces.widget.BaseTree.prototype.fireNodeSelectEvent = function(node) {
        if(this.isCheckboxSelection() && this.cfg.dynamic) {
            var $this = this,
            options = {
                source: this.id,
                process: this.id
            };

            options.params = [
                {name: this.id + '_instantSelection', value: this.getRowKey(node)}
            ];

            options.oncomplete = function(xhr, status, args, data) {
                if(args.descendantRowKeys && args.descendantRowKeys !== '') {
                    var rowKeys = args.descendantRowKeys.split(',');
                    for(var i = 0; i < rowKeys.length; i++) {
                        $this.addToSelection(rowKeys[i]);
                    }
                    $this.writeSelections();
                }
            };

            if(this.hasBehavior('select')) {
                this.callBehavior('select', options);
            }
            else {
                PrimeFaces.ajax.Request.handle(options);
            }
        }
        else {
            if(this.hasBehavior('select')) {
                var ext = {
                    params: [
                        {name: this.id + '_instantSelection', value: this.getRowKey(node)}
                    ]
                };

                this.callBehavior('select', ext);
            }
        }
    };
```

**Comment by melloware** [comment]
@mertsincan This tiny fix should probably go in an Elite release?

**Comment by selvait90** [comment]
@melloware It works like a charm. You made my day. thank you so much for quick response.

**Comment by melloware** [comment]
No problem!
