### ISSUE TITLE
Calendar: Popup mode with date/time pattern, sliders don't render properly when supplied with Date object with date and time

### ISSUE THREAD

**Issue by pneumcke** [primefaces/primefaces#4767]
## 1) Environment
- PrimeFaces version: 6.2.19 and 7.0.1
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Jetty (irrelevant)
- Affected browsers: all

## 2) Expected behavior
The time-part of a date is correctly displayed in a p:calendar component when using the popup mode.

## 3) Actual behavior
When the date object from a backing bean for a p:calendar contains a time, the time display shows "00:00:00" and all the sliders are on the left border, also representing "0".

## 4) Steps to reproduce
In calendar.xhtml from the sample, replace
`<p:calendar id="datetime" value="#{calendarView.date10}" pattern="MM/dd/yyyy HH:mm:ss" />`
with 
`<p:calendar id="datetime" value="#{session.lastAccessedTime}" pattern="MM/dd/yyyy HH:mm:ss" />`
Now click in the calendar input field and have a look at the popup.

## 5) Sample XHTML
See above.

## 6) Sample bean
No changes necessary.

The problem probably has been introduced by fixing https://github.com/primefaces/primefaces/issues/3765. Fixing the issue for the inline mode introduced the exact same problem for the popup mode.

**Comment by melloware** [comment]
Already reported fixed in Elite 7.0.2 with this fix.  https://github.com/primefaces/primefaces/issues/4733
