### ISSUE TITLE
inputmask: doesn't work properly with tooltip

### ISSUE THREAD

**Issue by joaopmi** [primefaces/primefaces#4769]
Hi, i'm making a web page with jsf2.3 and [primefaces 7.0] https://mvnrepository.com/artifact/org.primefaces/primefaces/7.0). When i use the tooltip with inputmask, it doesn't erase the input from user if it not matches the mask.

Ex:
```
<p:inputMask id="input" mask="999"/>
<p:tooltip for="input" value="Tooltip"/>
```

then if i insert only one 9, it will not disappear even with autoclear="true". But if i remove the tooltip, it works normally.

Thanks!!!

**Comment by cnsgithub** [comment]
I've not managed to reproduce this issue:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13161711/57905919-74a6ae00-7878-11e9-93f8-457806b89470.gif)

**Comment by melloware** [comment]
@joaopmi any update on reproducing this issue?

**Comment by melloware** [comment]
Closing issue as OP never responded.
