### ISSUE TITLE
UI issue when input components placed in overlayPanel

### ISSUE THREAD

**Issue by mbeedub** [primefaces/primefaces#477]
Very unsightly UI behaviour with overlayPanel when it contains input components (inputText, commandButtons etc) - for example when it's being used as an overlay for a login)

http://forum.primefaces.org/viewtopic.php?f=3&t=42565&p=133774#p133774

This contains simple code example taken from Primefaces showcase and also link to demonstrated behaviour:

http://www.videosprout.com/video?id=d54293d1-2e0f-4668-acc7-dcb12e4afb3d

**Comment by kukel** [comment]
Bad issue report. In the forum you stated it did work, with what version? Which version are you using now? etc...

**Comment by mbeedub** [comment]
As per the forum, I haven't noticed if it was working previously or not so unfortunately can't say if it's been introduced recently.

This is a reproducible problem (at least for us) using PF5.2.5 using code taken from the showcase.

**Comment by cagataycivici** [comment]
A couple of questions... Which theme do you use, do you have a PrimeFaces layout as well like Sentinel? An external css option could be the issue, also what browser do you experience this with?

**Comment by mbeedub** [comment]
You're quite right.  We've traced it to an external CSS file.   Please close this as a non issue.  Apologies for the false ticket.
