### ISSUE TITLE
tooltip: needs a update @form to work

### ISSUE THREAD

**Issue by joaopmi** [primefaces/primefaces#4770]
Hi, i'm making a web page with jsf2.3 and [primefaces 7.0] https://mvnrepository.com/artifact/org.primefaces/primefaces/7.0) and i was thinking in using p:tooltip to display front-end validation messages. The p:tooltip disappear after i update a single component related to it, i need to update the entire form or panel of the inputs to the tooltip work properly and stay normal, so i need to update all the inputs unnecessaries to a single tooltip. There's a way one can update a single component without bugging the tooltip?

Thanks!!!

**Comment by tandraschko** [comment]
the key is to register the event on the body instead the target component.
see the second solution here: https://stackoverflow.com/questions/13767919/jquery-event-wont-fire-after-ajax-call

**Comment by joaopmi** [comment]
i'll try
thx

**Comment by joaopmi** [comment]
> the key is to register the event on the body instead the target component.
> see the second solution here: https://stackoverflow.com/questions/13767919/jquery-event-wont-fire-after-ajax-call

i'll try
thx
