### ISSUE TITLE
TabMenu: Unexpected tab-switch on AJAX request after validation failure with Mojarra

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#4771]
[StackOverflow](https://stackoverflow.com/questions/55812486/)

## Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? -> No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) -> No
- Application server + version: Tested on Wildfly 10.1 and Jetty 9.4.15
- Affected browsers: All.
- JSF version: buggy with (at least) Mojarra 2.2.17 and 2.2.19, Mojarra 2.3.9; works with MyFaces 2.2.12

## Steps to reproduce

1. clone https://github.com/matinh/primefaces-test.git using the branch *tab-view* with `git clone 'https://github.com/matinh/primefaces-test.git' -b tab-view`
1. change directory `cd primefaces-test`
1. run `mvn jetty:run-exploded`
1. goto http://localhost:8080/primefaces-test/
1. try to switch to *Tab 1* which causes a validation failure for the input field (*Tab 0* is still active)
1. enter some text in the input field and click somewhere to trigger the change event
1. Now *Tab 1* will be active which is unexpected

**Comment by matinh** [comment]
Maybe this issue is related with #4756?

**Comment by melloware** [comment]
Still happening with Mojarra 2.3.13 but not with MyFaces 2.2 or 2.3

**Comment by melloware** [comment]
@matinh I recommend you report this to mojarra similar to how I reported this bug:
https://github.com/eclipse-ee4j/mojarra/issues/4680

Do it exactly like my bug where you attach your reproducer and show it works with Myfaces 2.2 and 2.3
