### ISSUE TITLE
InputText: Float Label for Primefaces

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primefaces#4777]
It would be great to have support for floating labels on inputTexts or other inputs like there is already in primeng or primereact:
https://www.primefaces.org/primeng/#/inputtext

:)

**Comment by melloware** [comment]
OK I have a prototype working base on what PrimeNG did.  Design question though.

Here is what my prototype does...just like PrimeNG or like PF InputGroup you use a SPAN to wrap it.
```xml
<span class="ui-float-label">
           <p:inputText id="float-input" />
           <label for="float-input">Username</label>
</span>
```

I like this because then its just CSS.

Or should it be like this...
```xml
<p:inputText id="float-input" floatLabel="Username" />
```
... where the component would generate the SPAN and the LABEL???

**Comment by ProfEibe** [comment]
Yeah, this was my first approach too. And I think that it could work with other input fields too.
But is it really just CSS? How do you check if the field is filled or not? I had to use some JS.

I think the most convenient would be the second version. But it would have to be added to all input tags I think. But front-end code would be much cleaner. It´s more capsuled.

**Comment by melloware** [comment]
You are right I do need a little JS to determine if its filled.

My thoughts again (and I don't know what is right..)

1. HTML/CSS solution above with a little JS makes it more generic and more like Input Group: https://www.primefaces.org/showcase/ui/input/inputGroup.xhtml  It could easily then be implemented for InputNumber (InputPhone from PFE) etc.

2. Attribute like floatLabel="" solution makes it more JSF like and handles rendering all the HTML etc.   But would have to be re-implemented in every text component.  

So I am struggling which way is the right away to go?

**Comment by ProfEibe** [comment]
Who can decide that?

**Comment by melloware** [comment]
That is a great question.  @Rapster @mertsincan @tandraschko  anyone want to weigh in on this?

**Comment by tandraschko** [comment]
+1 for 1)

**Comment by melloware** [comment]
OK I am pretty happy with it.  Stolen/borrowed almost exactly from PrimeNG. I decided to put the JS code in PrimeFaces.skinInput() since for most input components they call this to set up and skin the component.

 It works great for InputText and InputMask but for InputPhone/InputNumber we would have to do some more work only because those have inner containers that the styles don't work for.

```xml
<span class="ui-float-label">
       <p:inputText id="float-input" value="#{basicView.text}" />
       <p:outputLabel for="@previous" value="Username" />
</span>
```

**Comment by ProfEibe** [comment]
I´ve updated mellowares css a little bit so it also works with textarea inputfields.
please use the second commit (9ddb7af), i don´t know how to remove the first one :/

I hope I´ve done this right, it´s my first time contributing to this project.

**Comment by mertsincan** [comment]
Hi @melloware 
Thanks a lot for the PR, I made some changes for components that wrap input element. Exp; calendar

Best Regards,

**Comment by melloware** [comment]
Awesome!   Mert do you think that trick will work for InputNumber as well?  I noticed since InputNumber was wrapped in a Div it wasn't quite working right.  So I wonder if Calendar is the same way.

**Comment by mertsincan** [comment]
> Mert do you think that trick will work for InputNumber as well? 
- Yes, it works fine for me.

> I noticed since InputNumber was wrapped in a Div it wasn't quite working right. 
- It has `<span>`, no `<div>`;
````
<span class="ui-inputnumber" ...>
   <input ...>
````
