### ISSUE TITLE
Font Awesome version is outdated

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#4778]
In Primefaces 7.0.1 when i set the web.xml configuration to:

```
    <context-param>
        <param-name>primefaces.FONT_AWESOME</param-name>
        <param-value>true</param-value>
    </context-param>

```
Only the old fontawesome version 4.7.0 will be used which is using 
elements which are no longer available/supported in the 
latest version which is currently 5.8.1.
Also the tag's are no longer equal because they have been changed:
Instead of "fa fa-trademark" you have now write "fas fa-trademark" ...

I am always using the latest version of font-awesome by
redirecting it to the latest by using omnifaces CDN Resource Handler:

```
    <context-param>
        <param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS</param-name>
        <param-value>
           primefaces:fa/font-awesome.css=https://use.fontawesome.com/releases/v5.8.1/css/all.css
        </param-value>
    </context-param>

```

You can see this in the current Primefaces ShowCase .
So please Update this old version from 2017 to the latest because they have much more free icons with a lot of new features.
Please then also update to use these font instead of using png-sprites because when a user is zooming in he will get ugly artifacts if only a png is used...

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/issues/3056

**Comment by ssibitz** [comment]
You close an new issue because you find an already closed issue and mark as duplicate ?

Where is the current issue ?

**Comment by tandraschko** [comment]
Its a wont fix. PrimeTek decided to not upgrade because of new stlye classes which breaks migrations.
PF components supports Primeicons and fontawesome 4 and 5.
The way to go is the official fontawesome webjar.

**Comment by ssibitz** [comment]
Have you really read the manual which describes how to upgrade from 4.x to 5.x 
without changing the old icon names or anything else ?

The only "TODO" for upgrading from version 4.x to 5.x is to add 
a compability stylesheet - no more to do to be ready for using 5.x version's !

Please take a look here:
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

... and read the section "Upgrade Shims" :

> Want to upgrade in the quickest way possible? Need some extra help and assurance that your existing icons will render without issue? We’ve created shim files to use as band-aids until you get the time to do a proper upgrade. Our v4 shims allow you to keep your old version 4 icon names, aliases, and syntax while mapping version 5 icons to your current references.

```
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
</head>

```

**Comment by tandraschko** [comment]
It was the decision by primetek to move torwards Primeicons and just add basic style support for 5.x.
(i'm not a member of primtek ;))

**Comment by melloware** [comment]
@ssibitz What happens if you use your OmniFaces trick to load 5.8.1 and just include these shims in your page?  Does it then work?

@tandraschko I personally love FontAwesome and would like to upgrade to 5.8.1 maybe we could convince PrimeTek by doing a PR which includes these shims so its a seamless drop in?  Do you think I should try and we can get @mertsincan to review?

**Comment by tandraschko** [comment]
you can ask him
i'm a fan of the webjar, everyone can include his version he would like to use ;) for me it was not a good way to include it directly in PF.

**Comment by melloware** [comment]
Should we remove FontAwesome for 7.1 and provide a migration guide?  The WebJars solution is much nicer and pulls this code our of PF.

**Comment by tandraschko** [comment]
+1
@mertsincan wdyt?

**Comment by ssibitz** [comment]
It seems that when i redirect the old FontAwesome of Primefaces via Omnifaces to the latest version
and include the v4-shims.css into my application's template 
both of them (old and new icon's) are working right...

**Comment by melloware** [comment]
What I do is remove PrimeFaces FontAwesome entirely or disable it.

**web.xml**
```xml
<context-param>
     <param-name>primefaces.FONT_AWESOME</param-name>
     <param-value>false</param-value>         
</context-param>
```

**pom.xml** (add the webjar)
```xml
<dependency>
     <groupId>org.webjars</groupId>
     <artifactId>font-awesome</artifactId>
     <version>5.8.1</version>
</dependency>
```

Declare these two files in my layout XHTML.

```xml
<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/all-jsf.css" />
<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/v4-shims.min-jsf.css" />
```

So you don't need to use the OmniFaces CDN Handler at all (unless you want to).  You can use the new "fas fa-ellipsis-v" style 5.8.1 icons and the SHIM keeps the current PrimeFaces icons working like "fa fa-pencil"

**Comment by ssibitz** [comment]
I tried it in my development environment and currently it looks good.
The old and the new styles are working fine together.

But please use the complete minimized version of fontawesome by using:
`<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/all.min.css" />`

When i set the context-param primefaces.FONT_AWESOME to false 
is then primefaces using his "ugly" icon images which are not zoomable 
or only don't include the fontawesome header files ?

**Comment by tandraschko** [comment]
FONT_AWESOME=true only includes the CSS

**Comment by ssibitz** [comment]
Perfect ! 

Then this can be a workaround for using new FontAweSome Icons.
I think this is a thing also for other user's,
so a new Blog entry or a simple description in the primefaces-documentation would be nice ...

**Comment by ssibitz** [comment]
Okay, one thing i have - but that comes from the webjars.
The compressed(minimized) version is buggy because they also 
removed the resource-url's to the font's on the server so the client can't find the font itselfs. 

So using the uncompressed version is currently the only way, but it works:
`<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/all-jsf.css" />`

@melloware : So your configuration is working right !

**Comment by melloware** [comment]
@ssibitz yes I use teh all-jsf because they replace in the CSS with the proper #resource{} urls so it resolves properly in all JSF containers.

However I reported this bug in their MIN version which is why I am using the non-min version: https://github.com/webjars/font-awesome/issues/47

If you want to go vote for that issue 😄

**Comment by christophs78** [comment]
Think this is together with PF-Premium-Layouts a bit more complicated.
We use Babylon...
![grafik](https://user-images.githubusercontent.com/10461942/61281303-b640d000-a7b9-11e9-93c7-c0c8e6b442e7.png)
@mertsincan - What do you think?

Currently i work around via:
```
<h:outputStylesheet library="primefaces" name="fa/font-awesome.css" />
<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/all-jsf.css" />
<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/v4-shims-jsf.css" />
```

**Comment by melloware** [comment]
@christophs78 Are you saying using the WebJars + Shim solution does not work out of the box for Babylon?  I had it working locally?  I think the larger issue is PF needs to remove FontAwesome entirely and just recommend this WebJars solution.  Thoughts?

**Comment by christophs78** [comment]
@melloware Yes. WebJars+Shim (Fontawesome 5.8.1) does not work OOTB with Babylon 3.0.1 on my workstation. (Most icons work, but .ui-icon-triangle-1-s is broken.) 

PrimeFaces Designer 1.0.1 does not have this issue. PF-Designer uses primeicons.
```
// Icon Override Mixin
@mixin icon_override($icon) {
    font-family: 'primeicons';
    speak: none;
    font-style: normal;
    font-weight: normal;
```

Babylon 3.0.1 uses FontAwesome.
```
// Icon Override Mixin
@mixin icon-override($icon) {
    background: none;
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
```

Removing FontAwesome from PF and recommending the WebJars solution is IMO OK, when it does not break exisiting Layouts/Themes.

**Comment by ssibitz** [comment]
I currently use both (FontAwesome old & new) inside the currently new buyed 
"Premium Harmony Layout" by using these settings here.
This should only documented in the primefaces document under using FontAwesome.

The settings i used here are which are working with both font's are:

**1.) pom.xml - Dependencies:**
```
		<!-- Font Awesome -->
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>font-awesome</artifactId>
			<version>5.9.0</version>
		</dependency>

```

**2.) Settings in web.xml with activated "old" fontawesome** 
```
    <context-param>
        <param-name>primefaces.FONT_AWESOME</param-name>
        <param-value>true</param-value>
    </context-param>

```

**3.) Files which needs to be included after the default stylesheets like i am using for the Harmony:**

```
    <!-- Default stylesheets -->
    <h:outputStylesheet name="harmony-layout/css/nanoscroller.css"/>
    <h:outputStylesheet name="harmony-layout/css/layout-fate.css"/>
    <!-- Use FontAwesome as default -->
    <h:outputStylesheet library="webjars" name="font-awesome/5.9.0/css/all-jsf.css" />
    <h:outputStylesheet library="webjars" name="font-awesome/5.9.0/css/v4-shims.min-jsf.css" />

```

**Comment by melloware** [comment]
@christophs78 I would also report your icon issue in the Babylon forum: https://forum.primefaces.org/viewforum.php?f=98

Usually things reported there get fixed.

**Comment by christophs78** [comment]
Existing Babylon-forum-entry: https://forum.primefaces.org/viewtopic.php?f=98&t=57813&sid=f2140e686d3270aeb2befb9656ef6e56

**Comment by christophs78** [comment]
new Babylon-forum-entry: https://forum.primefaces.org/viewtopic.php?f=98&t=59425

**Comment by mertsincan** [comment]
Hi @christophs78,

We don't intend to update FA font files in core. Users can add them as in the above examples. We'll only support new syntax of FA by modifying our CSS within the core. Please see this issue;
https://github.com/primefaces/primefaces/issues/4276

Best Regards,

**Comment by erickdeoliveiraleal** [comment]
there's a free fork of fontawesome too: https://github.com/ForkAwesome/Fork-Awesome

**Comment by melloware** [comment]
We have considered removing FontAwesome 4.7 from inside PrimeFaces JAR entirely.  Since there is a proper webjars implementation that lets you keep it up to date yourself.
