### ISSUE TITLE
(Free) themes no longer available ?

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#4779]
In the current primefaces-showcase 
with the version 7.0.2 i can't see the 
**"sam-theme"** any more under the free themes
and also other themes are removed in this release.

Are there any reasons for that ?

Why i am asking:
We are currently discussing about buying a premium-theme
so the main question we have is 
how long is a theme supported in general
or are there currently themes which are planned to be removed in future releases ?

Lifetime support sounds good, but when the lifetime is only 1 year up to 2 years or less then that 
we can not plan a theme for a longer release cycle ...

**Comment by tandraschko** [comment]
AFAIK primetek removed those old-fashioned themes from the showcase as doesn't look good anymore and were just created with themeroller. They are still available in github.
The newer premium themes (also like nova or omega) are created from hand with much more passion and love.

I can't answer your question but as you can see, many of the premium layouts/themes are many years old and maintained.
I also don't know if it's possible to buy a theme without layout. Maybe the PrimeFaces Designer is the right thing for you.

But nevertheless, please ask such questions via mail or forum. This is just a issue tracker for community things (not payed layouts etc)
