### ISSUE TITLE
DataTable: missing return statement in cloneTableHeader

### ISSUE THREAD

**Issue by ErtelJessica** [primefaces/primefaces#4781]
## 1) Environment
- PrimeFaces version: 7.0.1
- Affected browsers: tested in firefox

## 2) Expected behavior

The use of the method cloneTableHeader in cloneHead lets us assume that it should return something.

```
    cloneHead: function() {
        this.theadClone = this.cloneTableHeader(this.thead, this.bodyTable);

        //reflect events from clone to original
        if(this.sortableColumns.length) {
            this.sortableColumns.removeAttr('tabindex').off('blur.dataTable focus.dataTable keydown.dataTable');

            ...
        }
    }
```

## 3) Actual behavior
But there is no return statement at the end of that function. This causes an error because this.thead in cloneHead is undefined.

```
     /**
     * Clones a table header and removes duplicate ids.
     */
    cloneTableHeader: function(thead, table) {
        var clone = thead.clone();
        clone.find('th').each(function() {
            var header = $(this);
            header.attr('id', header.attr('id') + '_clone');
            $(this).children().not('.ui-column-title').remove();
            $(this).children('.ui-column-title').children().remove();
        });
        clone.removeAttr('id').addClass('ui-datatable-scrollable-theadclone').height(0).prependTo(table);
    },
```

We fixed this by simply adding `return clone;` at the en of cloneTableHeader.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by mertsincan** [comment]
Thanks a lot! Fixed for 7.1. PF7.0.x doesn't contain cloneTableHeader method.

Best Regards,
