### ISSUE TITLE
Schedule: update to new version of Fullcalendar (3.10.0)

### ISSUE THREAD

**Issue by fheldt** [primefaces/primefaces#4783]
Actually primefaces 7.0 uses FullCalendar V3.9.0, the current version is V4.1.0

**Comment by melloware** [comment]
@OBreidenbach Care to look at this one?

**Comment by OBreidenbach** [comment]
No. We are happy with the FullCalendar release V3.9.0. 
For the update to V3.9.0 we just replaced the FullCalendar files (*.js and *.css) in PrimeFaces
With release V4.0 FullCalendar removed the dependency to JQuery and moment.js. See: https://fullcalendar.io/docs/upgrading-from-v3
So I doubt that changing to V4.1.0 is as easy as it was changing to V3.9.0.
Who ever wants the new release should take the effort.

**Comment by fheldt** [comment]
In this case you should at least consider upgrading to V3.10.0 See: https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0

**Comment by tandraschko** [comment]
@fheldt just to clarify:
Thats @OBreidenbach personal opinion. If some does the work or sponsor it, PrimeFaces could upgrade to any version if there are no breakers or a decision by PrimeTek.

**Comment by christophs78** [comment]
I´ll play around with FullCaelndar 4.x within the next weeks and keep you updated.

**Comment by melloware** [comment]
I updated the title of this ticket to 3.10.0 which is what FullCalendar we upgraded to.  @christophs78 If you get 4.X working just create a new ticket so we can track that change separately.  Thanks for looking into this!
