### ISSUE TITLE
Listener not being called for the drop down, but the listener works for the date functionality

### ISSUE THREAD

**Issue by Glennjacob** [primefaces/primefaces#4784]
Listener not being called for the drop down, but the listener works for the date functionality

## 1) Environment
- PrimeFaces version: 5.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Websphere 10.3
- Affected browsers: All

## 2) Expected behavior

The ajax method listener should be called for the district drop down listener="#{dataMB.districtSelect}" 
The ajax method listener should be called for the date select

## 3) Actual behavior

The ajax method listener is not called for the district drop down
The ajax method listener is called for the date select 

## 4) Steps to reproduce
 
Declare a bean
Declare a <p:selectOneMenu and a p:ajax inside it

## 5) Sample XHTML

                   <div class="ui">
    <p:panelGrid columns="9" layout="grid" id="dateFilterPanel" >     
        <h:panelGroup> 

        <p:outputLabel value="District"> 
        <p:selectOneMenu id="district" value="#{dataMB.selectedDistrict}" >
        <p:ajax event="select"  listener="#{dataMB.districtSelect}" update=":dataForm" /> 
            <f:selectItem itemLabel="Select District" itemValue="" />
            <f:selectItems value="#{dataMB.districtList}" />
        </p:selectOneMenu>

        <h:outputLabel value="dateFrom" for="dateFrom">
        <p:calendar id="dateFrom" mode="popup" readonlyInput="true" value="#{dataMB.dateFrom}" pattern="MM/dd/yyyy" navigator="true">
            <p:ajax event="dateSelect"  listener="#{dataMB.dateSelectFrom}" update=":dataForm" />
        </p:calendar>                  
    </p:panelGrid> 
    </div>
            <div class="ui">

                    <p:dataTable styleClass="fixed-size" value="#{dataMB.searchResultsList}"    
                        var="searchResultsRow" rows="10" paginator="true"  widgetVar="searchResults"
                        emptyMessage="No results found for search." id="searchResults"
                        rowKey="#{searchResultsRow.dateFrom}" selection="#{dataMB.selectedData}"
                        draggableColumns="true" selectionMode="single" >

                    <p:column
                            headerText="Date From"
                            sortBy="#{searchResultsRow.dateFrom}"
                            filterBy="#{searchResultsRow.dateFrom}"
                            filterMatchMode="contains" id="dateFromId">

                            <h:outputText id="dateFrom" value="#{searchResultsRow.dateFrom}">
                                <f:convertDateTime pattern="MM-dd-yyyy" />
                            </h:outputText>
                        </p:column> 

                    </p:dataTable>

           </div>                           

            </h:form>
        </h:body>

6) Sample bean

            public void dateSelectFrom(SelectEvent  event) {
             }

                 public void districtSelect(SelectEvent  event) {
                 }

--------------

<p:ajax event="select"
<p:ajax event="itemSelect"           
<p:ajax event="valueChange"
<p:ajax event="change"

I have tried these in the xhtml page, But none of them works. No errors in the console

**Comment by tandraschko** [comment]
Please provide a fully runable bean and xhtml. And also try 7.0
