### ISSUE TITLE
PrimeIcons pi-heart is missing (in showcase)

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#4789]
Not sure if this issue should be filed here or at the icons project, but currently the showcase has an entry for `pi-heart`, but no icon is showing.

https://www.primefaces.org/showcase/ui/misc/primeicons.xhtml

The selector for `pi-heart` is missing at

https://www.primefaces.org/showcase/javax.faces.resource/primeicons/primeicons.css.xhtml?ln=primefaces&v=7.0.2-SNAPSHOT

There is also no heart here:

https://github.com/primefaces/primeicons

**Comment by tandraschko** [comment]
Until it's not in the primeicons project, please provide a feature request there or lets remove it from the showcase.
We will upgrade primeicons here before the new release.
