### ISSUE TITLE
DatePicker: client side setDate() sets wrong value

### ISSUE THREAD

**Issue by DrTotenkopf** [primefaces/primefaces#4790]
## 1) Environment
- PrimeFaces version: 7.0.1
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Tomcat 8.5
- Affected browsers: Firefox, IE, Chrome

## 2) Expected behavior
When calling client side function "setDate('12/11/13')" of the DatePicker component, the corresponding inputfield should show the passed date and the popup calendar should show the month December and highlight the day "11".

## 3) Actual behavior
Apparently the function "setDate" sets the parsed date object as value to the input field. The input field uses the toString() method to display the date and showing "Wed Dec 11 2013 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)". The date is also not selected in the popup calendar.

## 4) Steps to reproduce
Simply call setDate() Method of the widget variable from the DatePicker component in JavaScript.

## 5) Sample XHTML
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Test Page</title>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	</f:facet>
</h:head>

<h:body>
	<h:form id="form">
		<p:outputLabel for="datepicker" value="DatePicker:"/>
		<p:datePicker id="datepicker" widgetVar="datepickerWdg" pattern="MM/dd/yy" />
		<br />
		<p:commandButton type="button" value="Set date (12/11/13)" onclick="PF('datepickerWdg').setDate('12/11/13')" />
	</h:form>
</h:body>
</html>
```

## 6) Sample bean
no bean necessary.
..

**Comment by melloware** [comment]
@christophs78 want to look at this one too?

**Comment by christophs78** [comment]
Yes, i will look at this. Datepicker is something we call in my language „Fass ohne Boden“.  (barrel without ground) Looked today at the TypeScript-File which implements Calendar for PrimeNG. There had been some fixes during this year. And no one ported them to PrimeFaces. (Shared component, but not shared defect fixing....)

**Comment by melloware** [comment]
I have noticed that as well.  and in fact a fix I made in Primefaces is still a bug in the PrimeNG one.

**Comment by christophs78** [comment]
@DrTotenkopf: Could you try setViewDate? When I look into https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js this may do what you expect.

**Comment by melloware** [comment]
When I try this on the showcase:https://www.primefaces.org/showcase/ui/input/datePickerJava8.xhtml
Open a console and type...
```javascript
PrimeFaces.widgets.widget_form_popup.setViewDate('12/11/13');
```
I get this error:

> Uncaught TypeError: this.viewDate.getMonth is not a function

**Comment by DrTotenkopf** [comment]
I just tried setViewDate() with Primefaces 7.0.10. I get this error:  TypeError: PF(...).setViewDate is not a function. It seems there is no function with the name setViewDate.
