### ISSUE TITLE
TreeTable: poor performance with lot of nodes

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#4798]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? NO
- Application server + version: WF 10.0.0
- Affected browsers:

## 2) Expected behavior
Better performance

## 3) Actual behavior
Lot of time needed to load the nodes

## 4) Steps to reproduce
Create a TreeTable with a parent and a lot of nodes (>15000)

**Comment by crocimi** [comment]
Pull request #4799

**Comment by tandraschko** [comment]
could you please also describe a bit your changes and what exactly is slow?

**Comment by crocimi** [comment]
every time a node is added to a parent update updateRowKeys is called (recursively) on all children of that parent. So, the keys are computed for every child, even that ones that haven't changed its position. This has a big impact on the performance, especially when a Parent has a lot of nodes.

My idea: 
1) if a node is inserted at (or removed from) position 'X' we can just update the indexes starting from this position. 
1) if a node is set at position 'X' (replacing another one) we can just compute the ids for this node and its children
