### ISSUE TITLE
DataExporter choice of the CSV Separator

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#48]
We'd like to choose the CSV separator for the DataExporter component, for instance use semicolon or tab in place of comma.

Why ?
Because in no Anglo-Saxon countries (at least in France), Microsoft Excel uses semicolon as the default CSV file separator. As a result, a CSV document exported with the DataExporter component doesn't open properly (the user has to reopen the document in choosing the coma separator to have the columns rightly displayed).

We suggest to add an attribute "CsvSeparator" to the DataExporter component that will allow to choose the Csv separator character.

**Comment by Quix0r** [comment]
When will this be included? I may need to change the "column" separator.

**Comment by gulbinas** [comment]
+1

**Comment by Kill3r444** [comment]
Could we please have an update on this topic ? This feature would be very useful to a lot of users. For now I  include a custom CSVExporter in my project, but this is a lot of work to check for change at each Primefaces update. Anyway, thanks for your work, I love your framework !

**Comment by tandraschko** [comment]
You can sponsor the change via PrimeFaces PRO or do it by yourself and provide a PR!

**Comment by cnsgithub** [comment]
I'm interested in providing a PR...

**Comment by Kill3r444** [comment]
@cnsgithub : not a native english speaker, so not sure what you mean : do you want to provide a PR yourself, or do you want me to provide one ?

**Comment by cnsgithub** [comment]
I'll provide a PR, stay tuned.

**Comment by cnsgithub** [comment]
PR: https://github.com/primefaces/primefaces/pull/3822

Please see PR comment for details.

**Comment by Kill3r444** [comment]
Thanks, but I'm a newbie here  : what do I have to do now ? may I test your code in any way ?

**Comment by cnsgithub** [comment]
You may fork or clone this repository and build your own primefaces snapshot based on the master branch: https://github.com/primefaces/primefaces/wiki/Building-From-Source

Otherwise, you can wait until a member of this repository merges the PR and releases a new minor (available to the public) or bugfix release (PrimeFaces Pro/Elite).

**Comment by Kill3r444** [comment]
I reviewed your changes and have a question : why do you use a StringBuilder object while I have a Writer object in my Primefaces source (6.2.5) ?

**Comment by cnsgithub** [comment]
For questions regarding code changes, please comment in the PR at the appropriate lines.

**Comment by Kill3r444** [comment]
This isn't a change you made, it is a difference between my PF version (downloaded from PF website) and the one on the repository

**Comment by cnsgithub** [comment]
Yes, because there might have been some refactorings between PrimeFaces 6.2.5 and the master branch (6.3-snapshot).

**Comment by Kill3r444** [comment]
Ok thanks, that change was commited on Nov 20, 2017, and seems to have been included in 6.2.6.

**Comment by Kill3r444** [comment]
Just tested your commit and it works great, thanks !
