### ISSUE TITLE
Columns misalignment with box-sizing: border-box style on Scrollable DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4801]
On Scrollable DataTable, if users use a CSS library that has box-sizing: border-box style(Exp; bootstrap), columns are misaligned with it. Details; https://blog.jquery.com/2012/08/16/jquery-1-8-box-sizing-width-csswidth-and-outerwidth/

**Comment by regenduft** [comment]
This commit breaks everything. 

It does NOT work at all anymore with the primefaces default theme (without border-box).

And even if I set border-box style for all scrollable datatable TD and TH, it does calculate column sizes wrong when using p:columns tag and no explizit width= attribute.
