### ISSUE TITLE
error drapdrop panel in IE

### ISSUE THREAD

**Issue by vanquyen906** [primefaces/primefaces#4802]
drapdrop panel in IE to the left end,right end .you can see panel always move same scroll endless.chrome and firefox that so oke but error in IE you can check link mainpage primeface.
https://www.primefaces.org/showcase/ui/dnd/draggable.xhtml

**Comment by melloware** [comment]
I see what you mean in IE/Edge you can drag an item to the right and it never stops scrolling.  In Firefox and Chrome its contained to the browser window.

**Comment by melloware** [comment]
Looks like this might be the solution: https://stackoverflow.com/questions/15265427/jquery-draggable-drags-off-screen

**Comment by melloware** [comment]
It looks like you can simply use the "Containment" option.

http://api.jqueryui.com/draggable/#option-containment

Possible values: "parent", "document", "window"  So just do..

```xml
<p:draggable for="vpnl" axis="y" containment="parent"/>
```

**Comment by tandraschko** [comment]
should we close it? It's more like a showcase optimization

**Comment by melloware** [comment]
Yep we should close it.
