### ISSUE TITLE
Tree: dropRestrict="sibling" does not work as expected.

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#4808]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No. Same issue in 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Jetty
- Affected browsers: All

## 2) Expected behavior
Node 0
Node 1

Dragging Node 1 over Node 0 should not make node 1 the child of Node 0 (as dropRestrict="sibling")

## 3) Actual behavior

Dragging Node 1 over Node 0 makes Node 1 child of Node 0

Before dragging

Node 0
Node 1

After dragging

Node 0
\> Node 1

## 4) Steps to reproduce
To reproduce use this test (dropRestrict branch) repo - https://github.com/amathew121/primefaces-test/tree/dropRestrict

Go to http://localhost:8080/primefaces-test/

Drag Node 1 on to Node 0. 
Expected nothing to happen. Instead, Node 1 is made the child of Node 0
 

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="form">
            <p:growl id="msgs" showDetail="true" />

            <p:tree id="tree1" value="#{treeDNDView.root1}" var="node"
                    draggable="true" droppable="true" dragdropScope="demo" dropRestrict="sibling">
                <p:ajax event="dragdrop" listener="#{treeDNDView.onDragDrop}" update=":form, :form:msgs" />
                <p:treeNode>
                    <h:outputText value="#{node}" />
                </p:treeNode>
            </p:tree>
        </h:form>
    </h:body>
</html>
```

## 6) Sample bean

```
@Named("treeDNDView")
@ViewScoped
public class DragDropView implements Serializable {
     
    private TreeNode root1;

    @PostConstruct
    public void init() {
        root1 = new DefaultTreeNode("Root", null);
        TreeNode node0 = new DefaultTreeNode("Node 0", root1);
        TreeNode node1 = new DefaultTreeNode("Node 1", root1);
    }
 
    public TreeNode getRoot1() {
        return root1;
    }

    public void onDragDrop(TreeDragDropEvent event) {
        TreeNode dragNode = event.getDragNode();
        TreeNode dropNode = event.getDropNode();
        int dropIndex = event.getDropIndex();
         
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Dragged " + dragNode.getData(), "Dropped on " + dropNode.getData() + " at " + dropIndex);
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
}
```

**Comment by melloware** [comment]
Is what you fixed anyway relatedto this issue?  https://github.com/primefaces/primefaces/issues/3543

**Comment by ghost** [comment]
Yes. My PR fixes that issue as well. 

In v6.1, fireDragDropEvent was not called if not a valid drop point. However, in 6.2 after some refactoring, the fireDragDropEvent is called even when not a valid drop point.

**Comment by melloware** [comment]
Excellent!  Its great when a PR fixes multiple issues.

**Comment by melloware** [comment]
@amathew121 I just merged your PR along with fixing the IE11 issue.  Can you please verify with the latest code from master that everything is working as expected please.
