### ISSUE TITLE
Remove ms-clear icons from all inputs

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#4817]
Reported By PRO User;
> In Internet Explorer 11 and Edge it's possible to click on clear button on input fields. When that button is clicked in tree filter, the tree filter is cleared but the Tree does not handle that event.

etc.

**Comment by ProfEibe** [comment]
Sry about asking this question here. I don´t know where else would be intelligent.

@mertsincan maybe you can help me: Is there a possiblity to checkout the latest version from 6.2 with all bugfixes? I know i can search for the tag with 6_2 but as far as I know this is the release version with 6.2.0. But this fix is labled with 6.2.21. Is this a version accessable?
Is there a branch with the bugfixes from the old version or maybe something similar? Or is this not possible?

I hope you don´t mind asking this question here.
Thank you!

**Comment by tandraschko** [comment]
Elite Versions Like 6.2.x are closed source and must be payed for it. Only community Versions like 6.1, 6.2 and 7.0 are open source and free

**Comment by ProfEibe** [comment]
Aah, alright. So the versions I receive through the public maven repository are most probably the community versions as well, right?

**Comment by tandraschko** [comment]
Exactly

**Comment by melloware** [comment]
@ProfEibe if you pay 99$ for Elite you have access to all the versions and you can download PF 6.2.20 which is the latest patched version of 6.2.
