### ISSUE TITLE
Add rangeSeparator attribute to DatePicker

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#4818]
With pattern set to "yyyy-MM-dd" it's impossible to use selectionMode "range". DatePickerRenderer has hardcoded separator string in line 186, and since the number of elements in the parts array isn't equal to 2, it doesn't even try to parse those dates. Please allow to specify different separator string for range and multiple selectionModes.

## 1) Environment
- PrimeFaces version: 7.0.2
- Application server + version: WildFly 16.0.0
- Affected browsers: All

## 2) Expected behavior

Getting list with two elements.

## 3) Actual behavior

Getting empty list.

**Comment by melloware** [comment]
Good debugging.  I think you mean this line 194: 
https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java#L193-L200

```java
            case "range": {
                String[] parts = submittedValue.split("-");
                List<Object> range = new ArrayList<>();
                if (parts.length == 2) {
                    for (String part : parts) {
                        range.add(super.getConvertedValue(context, component, part));
                    }
                }
```

**Comment by morvael** [comment]
In my sources for 7.0.2 (we have commercial support, and probably there is different license header) the line number is different, but it's the same piece of code.

**Comment by morvael** [comment]
By the way I wanted to write my own coverter to custom object (range with two fields "from" and "to"), and with the way this code is written it's impossible to do it.

**Comment by youngroman** [comment]
same issue here. easy fix would be to change the default separators to include the spaces. I don't know of a Date/Time-Pattern that uses ", " or " - " so this might be a permanent fix unless you decide to customize the separators.

proposed code looks like this:
`
            case "multiple": {
                String[] parts = submittedValue.split(", ");
`
and
`            case "range": {
                String[] parts = submittedValue.split(" - ");
`

**Comment by melloware** [comment]
@youngroman not a bad suggestion.  @mertsincan WDYT?  I can submit a PR if you think its OK.

**Comment by Edubits** [comment]
Please note the same issue exists in PF 7.0.4 in datepicker.js. `text.split(/-| - /)` is used instead of `text.split(' - ')`

**Comment by melloware** [comment]
@mertsincan the JS piece @Edubits is talking about above is in the shared DatePicker code between PrimeNG, PrimeReact, and PrimeFaces so I am hesitant to touch it. Can you please review?

**Comment by mertsincan** [comment]
Hi @melloware,

We can add "rangeSeparator" attribute for this issue.

**Comment by mertsincan** [comment]
Hi @morvael

Please use rangeSeparator attribute.

Best regards,
