### ISSUE TITLE
p:fileUpload inside a panel grid fails

### ISSUE THREAD

**Issue by ozziej** [primefaces/primefaces#482]
In this example:

``` java
            <p:panelGrid id="fileGrid" style="width:100%;">
                <h:form id="uploadForm" enctype="multipart/form-data">
                    <p:fileUpload mode="advanced" fileUploadListener="#{fileUploadController.handleUploadFile}" update="growl"/>
                </h:form>
            </p:panelGrid>
```

If you have the p:panelGrid, you get the following error in the browser debugger.

Uncaught TypeError: Cannot read property 'getContext' of undefined
fileupload.js?ln=primefaces&v=5.2:1 
Removing the `<p:panelGrid>` will then allow the uploader to work.

**Comment by cagataycivici** [comment]
Your code formatting is broken, please fix.

**Comment by ozziej** [comment]
Sorry about that, its what happens when you copy and paste without checking :-)

**Comment by cagataycivici** [comment]
How about p:panelGrid columns="1"

**Comment by tandraschko** [comment]
works fine for me.
