### ISSUE TITLE
New feature: combine fileupload with image cropper

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#4837]
Image cropper and fileupload are nice plugins but a combination of both would be awesome since the cropping could be done before saving the image in the system.

**Process**

When the user selects an image a crop button / checkbox could be shown next to the preview.

On upload a dialog (master / detaillevel) can be shown where the user can select the crop rectangle and we programmers will automatically receive the cropped image in the bean. 

Maybe the rectangle coordinates can be selected on the local blob? In this case these coordinates can be passed to a custom JSF converter that crops the image, so there is no need to save the images in the bean during cropping?

**Comment by tandraschko** [comment]
very unlike that it will be implemented without sponsoring

**Comment by djmj** [comment]
Understandable but it should also wait until a new base like cropper.js is selected #4136.

**Comment by melloware** [comment]
Now that Cropper has been updated and in 9.0 supports dynamic streamed content this showcase PR demonstrates using FileUpload and Cropper together: https://github.com/primefaces/primefaces-showcase/pull/157

**Comment by SwiftWizard** [comment]
> Now that Cropper has been updated and in 9.0 supports dynamic streamed content this showcase PR demonstrates using FileUpload and Cropper together: https://github.com/primefaces/primefaces-showcase/pull/

Broken link...

**Comment by melloware** [comment]
@SwiftWizard what link are you looking for?

The showcase has the example right here: https://www.primefaces.org/showcase/ui/multimedia/cropper/fileupload.xhtml?jfwid=095fe
