### ISSUE TITLE
Specialization of QR Code with implementation of Error Correction

### ISSUE THREAD

**Issue by flavio-pessoa** [primefaces/primefaces#484]
doubts arose when one is developing a screen using PrimeFaces 5.1 component (Barcode) , the requirements asked to create a QR Code with recovery level H.

how QRGen its build in zxing and himself suport recover level it's basic extend AbstractQRCode, equal example QRCode in QRGen directory (https://github.com/kenglxn/QRGen/blob/master/javase/src/main/java/net/glxn/qrgen/javase/QRCode.java) in method withErrorCorrection. 

I propose change in classe QRCodeHandler of primeface, to afford error correction.

i need reply, please.

Sincerely Sr. Flavio Luis Lopes Pessoa

**Comment by tandraschko** [comment]
Would be great if you could provide a PR.

**Comment by melloware** [comment]
PR submitted: https://github.com/primefaces/primefaces/pull/2647
