### ISSUE TITLE
DataTable: Cannot update footer only as initial footer is not rendered anymore

### ISSUE THREAD

**Issue by jansohn** [primefaces/primefaces#4840]
## 1) Environment
- PrimeFaces version: `7.0`
- Application server + version: `Tomcat 8.5.37`
- Affected browsers: tested with `Firefox` and `Edge`

## 2) Expected behavior
`<h:panelGroup id="buttonPanel">` component in `<f:facet name="footer">` should be updateable (without updating the whole datatable) even if in the initial state all `<p:commandButton>` components are not rendered.

## 3) Actual behavior
I need to update the whole datatable to have an updated footer with buttons based on the selected row.

## 4) Steps to reproduce
Extend showcase `Single with Row Click` (https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml) by showing the button only if a row is selected.
We therefore currently add a named container, e.g. `h:panelGroup` which can be separately updated and accordingly add row select and unselect events.

## 5) Sample XHTML
```
<p:dataTable id="singleDT" var="car" value="#{dtSelectionView.cars2}" selectionMode="single" selection="#{dtSelectionView.selectedCar}" rowKey="#{car.id}">
    <f:facet name="header">
        Single with Row Click
    </f:facet>
    <p:ajax event="rowSelect" update="buttonPanel" />
    <p:ajax event="rowUnselect" update="buttonPanel" />
    <p:column headerText="Id">
        <h:outputText value="#{car.id}" />
    </p:column>
    <p:column headerText="Year">
        <h:outputText value="#{car.year}" />
    </p:column>
    <p:column headerText="Brand">
        <h:outputText value="#{car.brand}" />
    </p:column>
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
    <f:facet name="footer">
        <h:panelGroup id="buttonPanel">
            <p:commandButton process="singleDT" update=":form:carDetail" icon="pi pi-search" value="View" oncomplete="PF('carDialog').show()" rendered="#{dtSelectionView.selectedCar != null}" />
        </h:panelGroup>
    </f:facet>
</p:dataTable>
```

## 6) Sample bean
unchanged to showcase.

This is probably caused by https://github.com/primefaces/primefaces/issues/2825. Our current solution still worked with PrimeFaces 6.1.

**Comment by melloware** [comment]
Just to make sure I understand are you saying.. if one of your buttons IS rendered then the h:panelGroup is updateable?

**Comment by jansohn** [comment]
Yes, that is correct. If one of my buttons is always shown the `h:panelGroup` is updateable.

**Comment by melloware** [comment]
Understood. If you need a quick fix right now you can simply hide a component in there styling it to be hidden like...
```xml
<p:button style=“display:none” />
```

This will make the footer rendered but that will never be displayed or take up screen real estate.

**Comment by stefanpr** [comment]
Will this issue be fixed in Primefaces 9.x?

**Comment by melloware** [comment]
@tandraschko @Rapster I think we need to revert  https://github.com/primefaces/primefaces/issues/2825 because many people have come upon this issue.  Thoughts?

**Comment by tandraschko** [comment]
make it configurable is better probably

**Comment by Rapster** [comment]
I don't think we should revert. We recently migrate to PF 8.0, and are quite happy about no longer displaying empty footer. In this scenario, it makes sense to use @melloware solution _(using CSS style, should work also without h:panelGroup)_

But also, when I read this:
 ```xml
<f:facet name="footer">
        <h:panelGroup id="buttonPanel">
            <p:commandButton process="singleDT" update=":form:carDetail" icon="pi pi-search" value="View" oncomplete="PF('carDialog').show()" rendered="#{dtSelectionView.selectedCar != null}" />
        </h:panelGroup>
    </f:facet>
```

I expect it to work... The thing is, the `h:panelGroup` is the facet, and `ComponentUtils.shouldRenderFacet` starts from here and loop over children... Not easy...

**Comment by Rapster** [comment]
@jansohn I'm trying to find a middle ground to make everyone happy, I don't think we should revert what has been introduced in PF 7.0 because in many cases I encoutered, it prevents to display an empty footer (which makes does not make your component nice), but I understand why you see it as a bug. 

You can either use @melloware solution, or what about using `disabled` attribute? I'm guessing you simplified your real use case into this one, let me know what you think?

Another solution would be to modify `ComponentUtils#shouldRenderFacet` and play with `UINamingContainer` _(since it's a very common case to use panelGroup to allow updates)_, e.g in case of facet of being a UINamingContainer, don't loop over children

**Comment by tandraschko** [comment]
i think the easiest way would be to add a attribute showEmptyFooter, which defaults to false?

**Comment by melloware** [comment]
How about attribute `alwaysRenderFacets` that can be used for header or footer?

**Comment by Rapster** [comment]
But what about the other components? I can think of `p:panel` also

**Comment by melloware** [comment]
Well I think for now lets just solve it for Datatable because it seems to be the one the people are using the most from this ticket?

**Comment by jansohn** [comment]
I'm also for an attribute to switch between the two options.
