### ISSUE TITLE
CodeMirror readonly attribute

### ISSUE THREAD

**Issue by slawomirkisiel** [primefaces/primefaces#485]
If I need to use readonly feature on pe:codeMirror component I have to use "readOnly" attribute (upper "O") which works fine but in taglib (META-INF\primefaces-extensions.taglib.xml) there is defined "readonly" attribute (lower "o"). It causes error notification in NetBeans while using this attribute.

**Comment by tandraschko** [comment]
use the extensions issuetracker next time and it's already fixed.

**Comment by cagataycivici** [comment]
Wrong tracker :)
