### ISSUE TITLE
inputNumber: value becomes corrupted because of p:remoteCommand autoRun="true"

### ISSUE THREAD

**Issue by MMetz-OV** [primefaces/primefaces#4852]
After days of debugging I found an issue, that a p:remoteCommand with attribute autoRun="true" does corrupt an p:inputNumber to set the value in the backent to 0 by loading the page.

From my point of view, it looks like, that the autoRun="true" does create a kind of AJAX update too early which does try to send back the not initialized hidden input field to the server. But the hidden input field does contain an empty string which is converted to the number 0.

## 1) Environment
- PrimeFaces version: 7.0
- Application server + version: Wildfly 14.0
- Affected browsers: Firefox 67

## 2) Expected behavior

Do not corrupt the backend value. The log output should only be:
> 11:25:20,651 INFO  [de.onevision.playground.primeinputnumber.ControllerBean] (default task-8) getNumber(): 100

## 3) Actual behavior

While loading the page, there is the log output:

> 11:25:20,651 INFO  [de.onevision.playground.primeinputnumber.ControllerBean] (default task-8) getNumber(): 100
> 11:25:20,842 INFO  [de.onevision.playground.primeinputnumber.ControllerBean] (default task-11) getNumber(): 100
> 11:25:20,858 INFO  [de.onevision.playground.primeinputnumber.ControllerBean] (default task-11) setNumber(0)

so, the number value is actively set to 0 before you press the submit button.

## 4) Steps to reproduce

Load the page, see the log.

## 5) Sample XHTML

``<?xml version='1.0' encoding='UTF-8' ?>``
``<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">``
``<html xmlns="http://www.w3.org/1999/xhtml"``
``	xmlns:h="http://java.sun.com/jsf/html"``
``	xmlns:f="http://java.sun.com/jsf/core"``
``	xmlns:ui="http://java.sun.com/jsf/facelets"``
``	xmlns:p="http://primefaces.org/ui"``
``	xmlns:c="http://java.sun.com/jsp/jstl/core">``

``	<h:head>``
``		<title>Playground: Prime InputNumber</title>``
``	</h:head>``

``	<p:remoteCommand name="corruptNumber"``
``		autoRun="true"``
``	/>``
``	<!-- Because of the autoRun="true", there is the bug.``
``	     You can avoid this, by autoRun="false" or with process="@this" or by removing the h:head. -->``

``	<h:body>``
``		<h:form>``
``			<p:inputNumber value="#{controllerBean.number}"/>``
``			<p:commandButton value="Submit" action="#{controllerBean.submit()}" />``
``		</h:form>``
``	</h:body>``
``</html>``

## 6) Sample bean

`` import javax.inject.Named;``
`` import org.jboss.logging.Logger;``

`` @Named``
`` public class ControllerBean {``
`` 	private static final Logger LOG=Logger.getLogger(ControllerBean.class);``
`` 	private int number=100;``
`` 	public void setNumber(int newValue) {``
`` 		LOG.info("setNumber("+newValue+")");``
`` 		number=newValue;``
`` 	}``
`` 	public int getNumber() {``
`` 		LOG.info("getNumber(): "+number);``
`` 		return number;``
`` 	}``
`` 	public String submit() {``
`` 		LOG.info("submit(): Number is: "+number);``
`` 		return "";``
`` 	}``
`` }``

**Comment by tandraschko** [comment]
Can you try the master? I think it may already be fixed as we set the Input value not via js anymore

**Comment by melloware** [comment]
I agree with @tandraschko I think it may be fixed with this ticket: https://github.com/primefaces/primefaces/issues/4543

**Comment by MMetz-OV** [comment]
Thanks for the fast response. Where can I download a JAR to test with?

**Comment by melloware** [comment]
You can download the 7.1-Master SNAPSHOT by doing this in your pom.xml to use JitPack.

```xml
<dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>

 <repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>

```

**Comment by MMetz-OV** [comment]
OK. Not so easy to get the snapshot for a non Maven user, but I tested with and it works!

In the log I get now:
> 14:52:18,172 INFO  [de.onevision.playground.primeinputnumber.ControllerBean] (default task-5) getNumber(): 100
> 14:52:19,139 INFO  [de.onevision.playground.primeinputnumber.ControllerBean] (default task-4) getNumber(): 100
> 14:52:19,139 INFO  [de.onevision.playground.primeinputnumber.ControllerBean] (default task-4) setNumber(100)

So, I still have all getter and setter but now the setter with the right value. So I will keep the process="@this" in my code, but I know, that future versions will not longer contain this pitfall.

Thanks again for the fast response and all your work!

**Comment by chovyy** [comment]
For those who are not able to update to the latest version, a workaround is to call the remoteCommand explictly from JavaScript instead of using `autoRun="true"`:

```
<script>
    $(document).ready(function() {
        corruptNumber();
    });
</script>
```
