### ISSUE TITLE
AutoComplete: Item from dropdown selected when pressing "tab"

### ISSUE THREAD

**Issue by fabermundi** [primefaces/primefaces#4857]
## 1) Environment
- PrimeFaces version: 7.0.3
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Wildfly 16
- Affected browsers: Chrome, Firefox, IE

## 2) Expected behavior
First element of dropdown should not be selected when using "tab" button.

## 3) Actual behavior
When setting focus to the next component using the "tab" button, the first element of the dropdown is selected.

## 4) Steps to reproduce
Go to the primefaces showcase ([https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml]) now go to the first Autocomplete and start typing for example a "d". Now suggestions are shown (d0, d1, ...). Now you have to type a "1" and then press the tabulator before the dropdown list is updated.
-> "d0" is selected nevertheless you typed "d1".
I think when exiting the autocomplete "d1" should stay (which is the case when you exist it using the mouse)
I also tried to set the "autoSelection" to "false" but this didn't helped.

## 5) Sample XHTML
Use primefaces showcase

## 6) Sample bean
Primefaces showcase

**Comment by melloware** [comment]
I think your issues may be related to these others?

https://github.com/primefaces/primefaces/issues/344
https://github.com/primefaces/primefaces/issues/1719
https://github.com/primefaces/primefaces/issues/3314

**Comment by fabermundi** [comment]
#1719 and #3314 Seems to describe another (design) problem, not related to this.
I already saw #344 but did not found out, what he means. By rereading the issue I think it could be releated (but I'm still not sure) for me it seems that the "autoSelection" property is ignored when leaving the autocomplete with the tabulator.

**Comment by melloware** [comment]
PR submitted. If you have autoSelection="false" the TAB key will work like normal and not select the item.

**Comment by fabermundi** [comment]
Great! Thank you

**Comment by melloware** [comment]
@fabermundi Please re-open the PR has not been reviewed or accepted yet.
