### ISSUE TITLE
BlockUI: Showcase examples do not work

### ISSUE THREAD

**Issue by koan00** [primefaces/primefaces#4864]
## 1) Environment
- PrimeFaces version:  Running PrimeFaces-7.1-SNAPSHOT on Mojarra-2.3.2.
- Affected browsers: Chrome / Firefox

## 2) Expected behavior

All three examples work.

## 3) Actual behavior

Only the first example 'Basic' works.

## 4) Steps to reproduce

1. Visit https://www.primefaces.org/showcase/ui/misc/blockUI.xhtml
2. Use the second or third example

**Comment by melloware** [comment]
I am working on a fix and it also showed another problem.

**Comment by melloware** [comment]
OK good catch, it turned out to be Floating Label related that was breaking the JS on the page.  Fix submitted.
