### ISSUE TITLE
selectBooleanButton value is String literal

### ISSUE THREAD

**Issue by scsynergy** [primefaces/primefaces#487]
Hi,

with primefaces 5.2, selectBooleanButton passes its value as a String literal "true" or "false" instead of as a boolean value. As soon as I added

```
converter="javax.faces.Boolean"
```

it worked without problems.

```
<p:selectBooleanButton converter="javax.faces.Boolean" value="#{search.object.lock}" offLabel="" onLabel=""
     onIcon="fa fa-lock" offIcon="fa fa-unlock"  disabled="#{search.notSelf}" rendered="#{!search.object.deleteMe}">
                            <p:ajax listener="#{search.saveObject()}" update="object"/>
</p:selectBooleanButton>
```

Sadly, noone would verify my findings - here is the forum thread
http://forum.primefaces.org/viewtopic.php?f=3&t=42498

Regards,
Ronny

**Comment by cagataycivici** [comment]
Not sure what is wrong on your side but component does the implicit conversion for you already, live demo is at;

http://www.primefaces.org/showcase/ui/input/booleanButton.xhtml

**Comment by scsynergy** [comment]
#{search.object} is a HashMap, whithout the explicit converter the value for the key 'lock' is either the "true" or "false" literal string. With the explicit converter the value is Boolean.TRUE or Boolean.FALSE - looks to me like the implicit conversion fails for this specific scenario.

**Comment by cagataycivici** [comment]
Does h:selectBooleanCheckbox work with that case?

**Comment by scsynergy** [comment]
Yes, even p:selectBooleanCheckbox works without errors.

**Comment by scsynergy** [comment]
Cool, thanks!
