### ISSUE TITLE
TreeTable: Keyboard navigation

### ISSUE THREAD

**Issue by zoltanrunyo** [primefaces/primefaces#4877]
## 1) Environment
- PrimeFaces version: 7.0.4
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Wildfly 16
- Affected browsers: Google Chrome, Mozilla Firefox

## 2) Expected behavior

The following tree based components support keyboard navigation (user is able to expand node, collapse node and navigate one level deeper in tree using keyboard's cursor keys): PrimeFaces Tree, PrimeNG Tree and TreeTable, PrimeReact Tree and TreeTable. Please add keyboard support for PrimeFaces TreeTable as well if it is possible.

## 3) Actual behavior

No navigation action for cursor keys after a specific node is selected.

## 4) Steps to reproduce

This issue can be easily reproduce by checking it in current PrimeFaces Showcase:  
https://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml

**Comment by rastislavvocko** [comment]
Hello @melloware , I see that this ticket is fixed for PrimeNg https://www.primefaces.org/primeng-v7-lts/#/treetable , but in primefaces I can not expand row with keyboard. It is accessibility issue. Please can you look on that?

**Comment by jepsar** [comment]
@rastislavvocko please read https://github.com/primefaces/primefaces#community--elite--pro

**Comment by melloware** [comment]
Moved to: #11250
