### ISSUE TITLE
Calendar read only show overlay to select date

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#488]
Calendar have a bug, when the parameter `readonly` is on. You can modify the value of the calendar via the overlay if the calendar doesn't have a value (example above).

``` html
  <p:calendar readonly="true" />
```

If the calendar is readonly, that not make sense to have an overlay to choose a date.

PF 5.2

**Comment by sudheerj** [comment]
When we used calendar readonly property then popup date will be selected but not submitted.The disabled attribute only protects from both input and popup selection.

**Comment by Julienng** [comment]
That not make sense to have a readonly property when this property accept write too. Final user doesn't understand if he can choose a date but never saved it.

**Comment by cagataycivici** [comment]
I agree, will work on it.

**Comment by cagataycivici** [comment]
I remember this, you need to use readonlyInput instead.

**Comment by Julienng** [comment]
Ok but why have a parameter `readonly` who is not `readonly` and a parameter `readonlyInput` who is a `readOnly` parameter? That look strange for me. I just want to understand the choice to go to the better way for my constraint.

**Comment by cagataycivici** [comment]
Because JSF does not process readonly fields at server side so we had to introduce readonlyInput specially for calendar as it is useful to pick dates from datepicker only without manual input where value is processed by JSF.

**Comment by Julienng** [comment]
Ok. Sound good for me, thanks !

**Comment by mauromol** [comment]
So, what's the fix version for this? 5.3 milestone has been removed and I still find this problem in 6.2. "readonly" does not prevent the popup button from opening the date selection dialog, which lets you select a date and will update the input field contents when a day is chosen, although the "dateSelect" ajax event is not fired. "readonlyInput", if used alone, seems to be even worse: not only the date is still selectable and updates the input field, but the "dateSelect" event is fired as well!
