### ISSUE TITLE
ColumnToggler: Duplicate id

### ISSUE THREAD

**Issue by MarkusChur** [primefaces/primefaces#4882]
ColumnToggler produces duplicate identifiers. Verified with the current showcase. 

Generated output contains an empty DIV element, e. g.:
`<div id="cars:j_idt703"></div>`
And a div element containing the links:
`<div id="cars:j_idt703" role="dialog" class="ui-columntoggler ui-widget ui-widget-content ui-shadow ui-corner-all" style="z-index: 1004; width: 101.719px; display: none; top: 554.984px; left: 2391.89px;"><a href="#" class="ui-columntoggler-close" aria-label="Close"></div>`

In my opinion the root cause is https://github.com/primefaces/primefaces/blob/dc0a8c69979e2f2aa0e8a334272b2b4485ffa44a/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js#L46

This script just appends DIV elements instead of operating on DIV created in the ColumnTogglerRenderer

**Comment by tandraschko** [comment]
Please provide at least steps to produce.

**Comment by MarkusChur** [comment]
Steps to reproduce:

- Either use the ColumnToggler Component or browse to https://www.primefaces.org/showcase/ui/data/datatable/columnToggler.xhtml
- Use a tool or verify manually that there are duplicate component ids.
![ColTog1](https://user-images.githubusercontent.com/6985014/59270516-f3adbd00-8c51-11e9-92a7-2a13ec56d75c.PNG)

**Comment by melloware** [comment]
@MarkusChur What tool are you using?  Chrome is not reporting duplicate Id's and looking at the code the "render" is only called once to create that DIV so it should be the only thing with that ID.

**Comment by melloware** [comment]
@Rawi01 Can you confirm this with your tools?  I am not seeing the issue.

**Comment by MarkusChur** [comment]
https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni
https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm

![addin1](https://user-images.githubusercontent.com/6985014/59348976-d1cb3d80-8d18-11e9-8c11-7c3d5ed3dede.PNG)
![addin2](https://user-images.githubusercontent.com/6985014/59348977-d1cb3d80-8d18-11e9-8847-6ea16ee4406d.PNG)

**Comment by MarkusChur** [comment]
The screenshot in https://github.com/primefaces/primefaces/issues/4882#issuecomment-500812069 shows  the automated check result of "Acessibility Insights for Web"

**Comment by Rawi01** [comment]
@melloware Can confirm this one. It adds an empty div right after the button itself and add a second div with the same id to the body

**Comment by melloware** [comment]
I see it.  Fixing.

**Comment by melloware** [comment]
Thanks for the help guys, I had never used that Chrome Extension before but now I really like it!   It was a simple fix the Renderer was already creating the DIV we just needed to look it up instead of creating a new one as @MarkusChur suggested.
