### ISSUE TITLE
Calendar: overlay isn't always open

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#489]
When you have a focus on a calendar with effect and click directly into the input of another calendar, the overlay isn't open.

Try on the show case:
- click into the calendar with label `Effect:` -> the overlay is open
- click into the calendar with label `Popup` -> the previous overlay is hidden but the new one doesn't appear
- click some where in the page
- click into the calendar with label `Popup` -> the overlay is open

**Comment by Julienng** [comment]
If you lose the focus of the current calendar before open another the overlay work correctly. But that cause problem when you create a page with create date - delivery date. People click directly into the next calendar.

**Comment by cagataycivici** [comment]
Can you replicate at;

https://jqueryui.com/datepicker/#animation

**Comment by Julienng** [comment]
Nope, need to have two or more calendar into the same parent to have the problem. Like your showcase or my application.
The problem: i'm not able to open the overlay of another calendar when i already have the focus on a calendar.

**Comment by sudheerj** [comment]
I can able to replicate the issue on PF showcase example.But we need to try it out in the jquery UI demo by adding popup calendar and animated calendar in the page(i.e by checkout the source).Then it can be formed whether it created an issue from jquery UI plugin or PF side.

**Comment by Julienng** [comment]
Ok thanks !

**Comment by Julienng** [comment]
Any news about this bug ? That a big problem for me indeed

**Comment by tandraschko** [comment]
Feel free to provide a PR!

**Comment by christophs78** [comment]
@tandraschko: DatePicker (which replaces Calendar) does not have a effect-attribute/feature. I played around a bit with https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml and i don´t think DatePicker has this issue.
