### ISSUE TITLE
LinkButton icon only variant has incorrect theme styling

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#4893]
See #4888 and #4889
I think it's caused by the following rule in the theme CSS:

```
body .ui-button.ui-button-icon-only {
  overflow: hidden;
}
```

**Comment by melloware** [comment]
How can this be fixed? In the theme?

**Comment by jepsar** [comment]
Yeah. I found where they are. Will fix it when I'm back from my holiday.

**Comment by jepsar** [comment]
Introduced by fixing #4697
