### ISSUE TITLE
XmlRequestHttp : Jquery Issue

### ISSUE THREAD

**Issue by NicolasDo** [primefaces/primefaces#4898]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: mojarra22
- Affected browsers: Chrome

## 2) Expected behavior
On print button press, print the generate pdf file

## 3) Actual behavior
(index):13 Uncaught TypeError: xhr.getResponseHeader is not a function
    at callPrint ((index):13)
    at Object.onco ((index):9)
    at Object.<anonymous> (core.js.xhtml?ln=primefaces&v=7.0:1058)
    at u (jquery.js.xhtml?ln=primefaces&v=7.0:2)
    at Object.fireWith [as rejectWith] (jquery.js.xhtml?ln=primefaces&v=7.0:2)
    at k (jquery.js.xhtml?ln=primefaces&v=7.0:2)
    at XMLHttpRequest.<anonymous> (jquery.js.xhtml?ln=primefaces&v=7.0:2)

xhr is not format to XML response but directly the pdf file

## 4) Steps to reproduce
Click on print button

## 6) Sample bean
Download primefaces test : https://github.com/NicolasDo/xhr-issue-primefaces
Related post : https://forum.primefaces.org/viewtopic.php?f=3&t=59118

**Comment by tandraschko** [comment]
is this related to PF or jQuery?

**Comment by NicolasDo** [comment]
It's related to PF i think, like Melloware answer this is in this file : https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js#L577-L599

**Comment by tandraschko** [comment]
how is it related?
PrimeFaces just passthrought XHR to your method, nothing else.
And the jquery xhr in your screenshot says "its not a valid XML". Maybe jQuery now requires a XML response from ajax? no idea.

**Comment by NicolasDo** [comment]
I can't answer because I don't have enough experience with Jquery.
I just know that when i change :
```
if(cfg.oncomplete) {
     cfg.oncomplete.call(this, xhr, status, xhr.pfArgs);
}
```
for that it's work :
```
if(cfg.oncomplete) {
     cfg.oncomplete.call(this, data, status, data.pfArgs);
}
```

When i compare ajax.core.js with old PF version this changed and will broken in 6.2.

**Comment by tandraschko** [comment]
This would mean that it worked unintended because our docu always mentioned that we pass "xhr" and not "data".
I think you can just use "onsucess" where we always passed "data": https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js#L556

**Comment by NicolasDo** [comment]
I try with onsuccess but it passed in .fail and return a parseerror.
Maybe because i overload the XML response with the PDF but don't know how to return pdf with xml format.
i'll investigate.

**Comment by tandraschko** [comment]
Otherwise we can also add "data" to oncomplete

**Comment by NicolasDo** [comment]
So instead of use callPrint(xhr, status, args) it should be like callPrint(data, status, args) ?
I think it's a good alternative.

**Comment by tandraschko** [comment]
commited ;)
