### ISSUE TITLE
Tooltip support for AutoComplete

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#49]
Tooltip does not support autocomplete when defined explicitly as a target of tooltip.

**Comment by kafelez** [comment]
This is an issue since 2013
http://forum.primefaces.org/viewtopic.php?f=3&t=33452

Any code warrior there ? :)

**Comment by sudheerj** [comment]
Currently tooltip is applied for `<li>` tag which has normal input width so it appears to specific area only.We need to add title separately for parent element(either div or ul tag) to apply it for full input width.

**Comment by sudheerj** [comment]
Fixed for 6.0

**Comment by mertsincan** [comment]
Thanks @sudheerj :+1: Can you please add Labels and Milestone to this issue?

**Comment by cagataycivici** [comment]
Is it fixed for 5.3.12 as well, @sudheerj
