### ISSUE TITLE
Effect: not working

### ISSUE THREAD

**Issue by Dsleeper** [primefaces/primefaces#4901]
The Blind, Clip and Drop effects among others does not seem to be animated properly in the showcase. Explode and bounce are working though.

Reference p:effect showcase:
https://www.primefaces.org/showcase/ui/misc/effect.xhtml

## 1) Environment
Showcase version & tested locally on PF 7.0.4

## 2) Expected behavior
Effect tag renders animation 

## 3) Actual behavior
The animations are not triggered

## 4) Steps to reproduce
Open showcase URL and test directly

Originally posted in this forum thread:
https://forum.primefaces.org/viewtopic.php?f=3&t=59154

**Comment by melloware** [comment]
I have a feeling this was somehow a change with Jquery 3.3.0 as looking at the PF code there is not much going on there and its calling the Jquery UI API correctly.

**Comment by melloware** [comment]
I think it is effects all around.  I am noticing weirdness with Picklist effects as well.

**Comment by melloware** [comment]
OK digging into this deeper if I just create a standalone XHTML page in a simple app the effects are working. It appears to be related to the CSS styles or theme of the Showcase?

**Comment by melloware** [comment]
I am closing this ticket as I have opened a showcase ticket for this instead: https://github.com/primefaces/showcase-facelift/issues/96

**Comment by melloware** [comment]
I finally got around to fixing this in the Showcase.  Will be fixed in the final release of 10.0 Showcase.

See PR: https://github.com/primefaces/primefaces-showcase/pull/259
