### ISSUE TITLE
PickList: Showcase is broken (JS-error; causing subsequent problems)

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#4905]
## 1) Environment
- PrimeFaces version: 7.1-SNAPSHOT
- Affected browsers: Chrome, FF, IE, Edge

## 2) Expected behavior
https://www.primefaces.org/showcase/ui/data/pickList.xhtml
"PickList on Steroids" should work
Switching between XHTML und Java should work

## 3) Actual behavior
"PickList on Steroids" does not allow to select items.
Switching to PickListView.java does not work.

## 4) Steps to reproduce
see 2 and 3

**Comment by christophs78** [comment]
JS-error:
![grafik](https://user-images.githubusercontent.com/10461942/59680440-9fff1e80-91d1-11e9-8ca4-84e9efbf129a.png)

**Comment by tandraschko** [comment]
already reported this week; works fine in trunk, just not new showcase deployed
@mertsincan you can deploy a new version?
