### ISSUE TITLE
LineChart: LinearAxes on x-axis is not available

### ISSUE THREAD

**Issue by pouwelsjochem** [primefaces/primefaces#4908]
## 1) Environment
- PrimeFaces version: 7.0.3
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: WildFly 16
- Affected browsers: All

## 2) Expected behaviour
When using a CartesianLinearAxes model as xAxes on the CartesianScales it should show the axis correctly.

## 3) Actual behaviour
The default 'category' axis is shown, because of the widget.cfg.config.options.scales.xAxes[0].type property with 'category' value. (although this can be changed by manually setting type on the CartesianLinearAxes.)

But even with this type there is no possibility to set the data correctly because the LineChartDataSet expects a List<Number> while ChartJS expects an object like {x: 5, y: 20}.

## 4) Steps to reproduce
This happens on initial render, no steps required.

## 5) Sample XHTML
```<p:lineChart model="#{bean.lineChartModel}" style="height:600px;" responsive="true"/>```

## 6) Sample bean
```
lineChartModel = new LineChartModel();

LineChartOptions lineChartOptions = new LineChartOptions();
CartesianScales cartesianScales = new CartesianScales();

CartesianLinearAxes cartesianLinearAxes = new CartesianLinearAxes();
CartesianLinearTicks cartesianLinearTicks = new CartesianLinearTicks();
cartesianLinearTicks.setMin(0);
cartesianLinearTicks.setMax(100);
cartesianLinearTicks.setStepSize(10);
cartesianLinearAxes.setTicks(cartesianLinearTicks);
cartesianLinearAxes.setScaleLabel(ChartUtils.createCartesianScaleLabelWithLabel(label));
cartesianScales.addXAxesData(cartesianLinearAxes);

CartesianLinearAxes cartesianLinearAxes = new CartesianLinearAxes();
CartesianLinearTicks cartesianLinearTicks = new CartesianLinearTicks();
cartesianLinearTicks.setMin(0);
cartesianLinearTicks.setMax(100);
cartesianLinearTicks.setStepSize(10);
cartesianLinearAxes.setTicks(cartesianLinearTicks);
cartesianLinearAxes.setScaleLabel(ChartUtils.createCartesianScaleLabelWithLabel(label));
cartesianScales.addYAxesData(cartesianLinearAxes);

lineChartOptions.setScales(cartesianScales);
lineChartModel.setOptions(lineChartOptions);

ChartData chartData = new ChartData();
lineChartModel.setData(chartData);

LineChartDataSet lineChartDataSet = new LineChartDataSet();
chartData.addChartDataSet(lineChartDataSet);

cartesianScales.setLabels(Arrays.ofList(8, 20, 59, 90));
lineChartDataSet.setData(Arrays.ofList(5, 10, 20, 66));
```

## 7) My hacky solution
I can get it to work correctly by manually setting type to "linear" on the cartesianLinearAxes and by implementing a new type of fake object which extends number but only implements the toString() to print the required format. Then I remove the setLabels call and just do
```lineChartDataSet.setData(Arrays.ofList(new LineChartDataPoint(8, 5), etc...));```

```
public class LineChartDataPoint extends Number {

    private String x;
    private String y;

    public LineChartDataPoint(Number x, Number y) {
        this.x = x.toString();
        this.y = y.toString();
    }

    public String toString() {
        return String.format("{x: %s, y: %s}", x, y);
    }

    @Override
    public int intValue() {
        return 0;
    }

    @Override
    public long longValue() {
        return 0;
    }

    @Override
    public float floatValue() {
        return 0;
    }

    @Override
    public double doubleValue() {
        return 0;
    }

}
```

**Comment by melloware** [comment]
I think its like this ticket right?  https://github.com/primefaces/primefaces/issues/4564

I plan on fixing this.
