### ISSUE TITLE
SelectOneMenu: label attribute not working

### ISSUE THREAD

**Issue by Eehol** [primefaces/primefaces#4919]
## 1) Environment
- PrimeFaces version: 7.0.0
- Application server + version: JBoss EAP 7.1.1
- Affected browsers: IE11, Chrome 75

## 2) Expected behavior

The label of the selectonemenu is "Hello World"

## 3) Actual behavior

The label is the itemLabel of the selected entry.

## 4) Steps to reproduce

Just run the xhtml.

## 5) Sample XHTML

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title></title>
        
    </h:head>
    <h:body>
		<p:selectOneMenu label="Hello World">
			<f:selectItem itemValue="YELLOW" itemLabel="Yellow" />
			<f:selectItem itemValue="BLUE" itemLabel="Blue" />
			<f:selectItem itemValue="RED" itemLabel="Red" />
		</p:selectOneMenu>
    </h:body>
</html>
```

## 6) Sample bean

None

**Comment by tandraschko** [comment]
did it work in older versions?
If not, i don't think we ever implemented this feature

**Comment by Eehol** [comment]
Indeed I just tried on PF6.2 and it doesn't work.

**Comment by melloware** [comment]
What would the label do?  Isn't that what the noSelectionOption is for?

`<f:selectItem itemLabel="Select City" itemValue="" noSelectionOption="true" />`

See: https://www.primefaces.org/showcase/ui/ajax/dropdown.xhtml

**Comment by Eehol** [comment]
The label should act in the same way as the label of selectCheckBoxMenu (+ both "label" attribute of selectCheckBoxMenu and selectOneMenu have the same description in the PrimeFaces user guide 7.0).

More precisely, the label is displayed independently of the selection, unlike to the "noSelectionOption" selectItem. Our goal is to use this attribute to replace the end of the label by "..." if it reaches a certain number of characters

**Comment by melloware** [comment]
Understood!  Interested in researching and providing a PR?

**Comment by Eehol** [comment]
Yes why not, I'll give it a try

**Comment by tandraschko** [comment]
Thanks!

**Comment by tandraschko** [comment]
@melloware @Eehol i think i need to revert this one
if you have a simple case:

p:outputLabel for=@next value=blub
p:selectOneMenu

and a value is already asigned the to p:selectOneMenu, "blub" is displayed instead of the real value

**Comment by melloware** [comment]
OK feel free to revert.

**Comment by tandraschko** [comment]
I think we would need a option, to enable this behavior
maybe something like: alwaysDisplayLabel=true|false? false per default

JFYI:
label is automatically set when you attach a p:outputLabel to a input

**Comment by tandraschko** [comment]
If thats ok for you, i would be a happy to apply a PR again, which considers this option
and also a docu update of course

**Comment by melloware** [comment]
Reproducer:
[pf-4919.zip](https://github.com/primefaces/primefaces/files/5547188/pf-4919.zip)
