### ISSUE TITLE
Primefaces-Events (eg SelectEvent): use generics

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#4923]
## 1) Environment
- PrimeFaces version: 7.1

## 2) Expected behavior
`org.primefaces.event.SelectEvent` is currently untyped.
For some usages it would IMO make sense to change it to 
`org.primefaces.event.SelectEvent<T>`.

**Comment by Rapster** [comment]
Do you have an example as why it'd make more sense?

**Comment by christophs78** [comment]
It would be some kind of syntactic sugar. :-)

Old (1):
```
public void onNodeSelect(SelectEvent event) {
   MindmapNode node = (MindmapNode) event.getObject();
```
New (1):
```
public void onNodeSelect(SelectEvent<MindmapNode> event) {
    MindmapNode node = event.getObject();
```
Old (2):
```
public void onDateSelect(SelectEvent event) {
    FacesContext facesContext = FacesContext.getCurrentInstance();
    LocalDate date= (LocalDate)event.getObject();
    DateTimeFormatter formatter =  DateTimeFormatter.ofPattern("dd/MM/yyyy");
    facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Date Selected", date.format(formatter)));
}
```
New (2):
```
public void onDateSelect(SelectEvent<LocalDate> event) {
    FacesContext facesContext = FacesContext.getCurrentInstance();
    DateTimeFormatter formatter =  DateTimeFormatter.ofPattern("dd/MM/yyyy");
    facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Date Selected", event.getObject().format(formatter)));
}
```

Old (3):
```
public void onRowSelect(SelectEvent event) {
    FacesMessage msg = new FacesMessage("Car Selected", ((Car) event.getObject()).getId());
    FacesContext.getCurrentInstance().addMessage(null, msg);
}

New (3):
public void onRowSelect(SelectEvent<Car> event) {
    FacesMessage msg = new FacesMessage("Car Selected", event.getObject().getId());
    FacesContext.getCurrentInstance().addMessage(null, msg);
}
```

**Comment by Rapster** [comment]
Ok that's what I thought, I understand what you're saying but I'm not sure if the change would bring any added value (syntaxically speaking). 

Since you have no control over event and listener instanciation, having a generic does not guarantee anything in terms of what the `FacesEvent#getObject` type it will be.

In both cases scenario, you'll end up with ClassCastException if bad type is set.

I'm not against making that change, I'm just saying that I think it doesn't make any difference (syntaxically speaking).

**Comment by christophs78** [comment]
Technically i totally agree to you.
To some degree this would be a marketing move. People are used to generics today. A typecast looks "old school".
Do you see some way to do this "the right" way with additional type-safety?

**Comment by christophs78** [comment]
Talked to some of my colleagues this week. Their argument was generics would make code a bit more expressive. (Even if it does not add additonal type-safety.)
