### ISSUE TITLE
selectOneMenu: INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL

### ISSUE THREAD

**Issue by WxU2U2gSsAw20uD** [primefaces/primefaces#4927]
### 1) Environment

- PrimeFaces version: 7.0.0
- Tomcat version: 9.0.x
- javax.faces glassfish version: 2.3.x
- javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL=true
- javax.faces.VALIDATE_EMPTY_FIELDS=true
- Custom JSF 2.3 converter with generics

### 2) Expected behavior

When user submit empty string: <f:selectItem itemLabel="&nbsp;" itemValue="" />
The converter receive a NULL object.
Issue cannot be reproduce with Primefaces 6.2.0.

### 3) Actual behavior

When user submit empty string: <f:selectItem itemLabel="&nbsp;" itemValue="" />
The converter receive an empty string.

The following error is observed:
`java.lang.ClassCastException: java.lang.String cannot be cast to package.Contact`

### Validator

`public class SoldToContactConverter implements Converter<Contact> {`

### XHTML

`<p:selectOneMenu id="soldToContact" disabled="#{not ta.saveable}" required="false" value="#{er.soldToContact}" converter="soldToContactConverter" var="contact" filter="true" filterMatchMode="contains" autoWidth="false" styleClass="wpe-select">
	<f:selectItem itemLabel="&nbsp;" itemValue="" />
	<f:selectItems value="#{er.soldToContacts}" var="selectable" itemValue="#{selectable}" itemLabel="#{selectable.itemLabel}" />
	<p:column><h:outputText value="#{contact.id}" /></p:column>
	<p:column><h:outputText value="#{contact.firstName}" /></p:column>
	<p:column><h:outputText value="#{contact.lastName}" /></p:column>
	<p:column><h:outputText value="#{contact.officePhone}" /></p:column>
	<p:column><h:outputText value="#{contact.mail}" /></p:column>
	<p:column><h:outputText value="#{td1017['edit.sold.to.contact.primary.'.concat(contact.primary)]}" /></p:column>
	<f:ajax event="change" render="soldToContactFirstName soldToContactFirstNameMessage soldToContactLastName soldToContactLastNameMessage soldToContactOfficePhone soldToContactOfficePhoneMessage soldToContactMail soldToContactMailMessage" />
	<f:attribute name="editResult" value="#{er}" />
	<f:attribute name="contacts" value="#{er.bpCache.soldToContacts}" />
</p:selectOneMenu>`

**Comment by tandraschko** [comment]
you probably need itemValue=#{null}, also see the migration guide

**Comment by tandraschko** [comment]
`SelectOneMenu / ThemeSwitcher: If custom content (with p:column(s) as child) is used with POJOs and you have a default f:selectItem like "Choose...", null (value="#{null}") instead of empty string (value="") should be used. Otherwise the properties on the var can't be resolved and a exception will be thrown.`
