### ISSUE TITLE
BaseMenuRenderer: Hide icons from assistive technology

### ISSUE THREAD

**Issue by Rawi01** [primefaces/primefaces#4929]
## 1) Environment
- PrimeFaces version: **latest**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**
- Application server + version: **-**
- Affected browsers: **-**

## 2) Expected behavior

Menu item icons that use icon fonts should be hidden using `aria-hidden="true"`.

## 3) Actual behavior

No aria attribute.

## 4) Steps to reproduce

Check it in showcase

---
PR will be added soon

**Comment by tandraschko** [comment]
why should it be hidden?
Please describe your problems a bit more before creating PR's, we can't just apply PRs without reason.

**Comment by Rawi01** [comment]
I'm sorry for the short description, I will try to describe problems more detailed in the future. 

In general icons that use icon fonts should be hidden from assistive technology because they may try to translate them to there target audience. For example a screen reader might try to read this one `✎ Edit` as `Edit Edit` or `Pencil Edit`. You can find a longer explanation at the [fontawesome page](https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility).
