### ISSUE TITLE
Responsive rowExpansion

### ISSUE THREAD

**Issue by fcanevar** [primefaces/primefaces#493]
If the datatable containing the p:rowExpansion uses columns with the priority attribute, the generated html doesn't keep track of that and uses the same colspan ruining the layout.

Example:

``` xml
<p:dataTable value="#{bean.list}" id="dataTable" var="row">
    <p:ajax event="rowToggle" global="false" process="@this" />
    <p:column id="tglcolumn" width="35">
      <p:rowToggler id="toggler" />
    </p:column>
    <p:column id="priorityColumn" priority="6" width="100%">
      <h:outputText value="priority column" />
    </p:column>
     <p:rowExpansion>
    <h:outputText value="expansion" />
     </p:rowExpansion>
</p:dataTable>
```

You can see that when the "priorityColumn" disappears, the expansion colspan remains "2".

Thanks

**Comment by sudheerj** [comment]
Is that means the rowExpansion table doesn't support the responsive feature  for rowExpansion data?

**Comment by fcanevar** [comment]
Yes, it doesn't support the responsive feature of the datatable

**Comment by cagataycivici** [comment]
No idea how we can support this with css, marking as wontfix as a result, if we can find an idea will reopen.

If you could provide a patch, please let us know.

**Comment by fcanevar** [comment]
Hi, I think it could be done by creating JS events attached to the CSS mediaqueries that are used to hide the columns and than use the events to change the colspan attribute.

**Comment by cagataycivici** [comment]
Feel free to do a pull request about this then.

**Comment by ravihariharan** [comment]
I was looking at a similar case and was able to use TreeTable for my requirement. 

I found a link for a sample which uses jquery and hence linking it to this issue.
 
[https://datatables.net/extensions/responsive/examples/child-rows/column-control.html](url)
