### ISSUE TITLE
TextEditor: Saving text without closing tags

### ISSUE THREAD

**Issue by russo177x** [primefaces/primefaces#4934]
## 1) Environment
- PrimeFaces version: 6.2
- Application server + version: Glassfish Server 3
- Affected browsers: Firefox

## 2) Expected behavior
I need the text with the closed tags, for example: <p.. > Teaching games. </ P>

## 3) Actual behavior
![Screenshot_2](https://user-images.githubusercontent.com/47541108/60050250-929cd500-96a6-11e9-99c2-aa8577cbee89.png)

## 4) Steps to reproduce
Just using the text editor and saving this words : Introdução de consoante
## 5) Sample XHTML

<p:textEditor id="texto-aula" value="#{registroAulaJsfBean.crudObj.conteudo}"
                                    placeholder="Digite aqui o conteúdo ministrado durante a aula..." height="80"/>

**Comment by tandraschko** [comment]
i don't think we can change that, thats up to the used quill editor.

**Comment by melloware** [comment]
Agreed with @tandraschko you will have to write a Validator if you want to validate the HTML and correct it.

**Comment by russo177x** [comment]
Thanks for the answer

**Comment by russo177x** [comment]
> 
> 
> Agreed with @tandraschko you will have to write a Validator if you want to validate the HTML and correct it.

You have a example how to use the validator with the TextEditor??

**Comment by melloware** [comment]
I do not but when I do is in my backing bean when it receives the value from the Editor you can run it through JSoup (https://jsoup.org/) or some other library to fix the tags.
