### ISSUE TITLE
Issue in prime faces pagination

### ISSUE THREAD

**Issue by lodhipra** [primefaces/primefaces#4936]
Currently i am using datatable without pagination so it shows all recods in single page as 

<p:dataTable value="#{txn_incident_createcontroller.allIncOrgDateStatus()}" var="liste" border="1" style="width: 100%;" id="datastatus"
		>
				
                    <p:column >
                        <f:facet name="header" >
                            <h:outputText value="" />
                        </f:facet>
                        <h:outputText value=""/>
                    </p:column>
					
					<p:column>
                        <f:facet name="header">
                            <h:outputText value="" />
                        </f:facet>
                        <h:outputText value=""/>
                    </p:column>
					
					<p:column>
                        <f:facet name="header">
                            <h:outputText value="" />
                        </f:facet>
                        <h:outputText value=""/>
                    </p:column>
					
					<p:column>
                        <f:facet name="header">
                            <h:outputText value="" />
                        </f:facet>
                        <h:outputText value=""/>
                    </p:column>	
					</p:dataTable>

later i have applied  paginator then i have successfully applies pagination but when i move to other page i destroys all recods and show null data table.

![datatable](https://user-images.githubusercontent.com/45519944/60071663-8feac000-9738-11e9-966b-ecd4af8a7cc8.jpg)

but it have all records in it when i will export it using
<p:dataExporter type="csv" target="datastatus" fileName="t"/>

**Comment by tandraschko** [comment]
Please follow the issue template and provide all infos.

**Comment by lodhipra** [comment]
Sir sorry due to security  reason we are unable to give you code ,
but i will provide you a full description

as initial data table have rows="10" and it shows all records fine but when i will click on another page button or next button it remove all records in the datatable. So, the problem arrives when i will perform any click action to navigate of filter in the datatable.

as you will see datatable shows two pages records but gives NO RECORDS FOUND message in the datatable.

**Comment by tandraschko** [comment]
i don't want your production code, we need a new created sample code to reproduce your issue.

**Comment by tandraschko** [comment]
Also it sounds more like a forum question currently.

**Comment by tandraschko** [comment]
Will close it for now. Please create a new and valid issue if you come back.
