### ISSUE TITLE
TextEditor: Should use JODIT instead of QUILL

### ISSUE THREAD

**Issue by RueKow** [primefaces/primefaces#4940]
## 1) Environment
- PrimeFaces version: 7.x
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 9
- Affected browsers: All

## 2) Expected behavior
TextEditor should have features:
- Insert table
- Insert horizontal line
- . . . see Open Source WYSIWYG editor JODIT
- https://xdsoft.net/jodit/

## 3) Actual behavior
Expected features are not available.

## 4) Steps to reproduce
- showcase
- https://forum.primefaces.org/viewtopic.php?f=3&t=59209

**Comment by tandraschko** [comment]
i dont think that this will happen. PrimeTek decided for QuillJS some releases before.
Maybe the best way is to introduce a new editor in PFE.

But in generell -1 for my side, this would be the 4. editor in the PF world ;)

**Comment by stolp** [comment]
From the website of JODIT i see that his is under a GPL v2 license, so I don't think that it would be a good idea to have it present in either libraries (PF or PFE).

Having said this, I would love to see a 4th (or 3rd as p:editor is already deprecated) alternative in PF or PFE.

**Comment by melloware** [comment]
Yes GPL v2 is no good.  Someone could create it as a standalone JSF library. Or do it like PFE CKEditor does it as a separate JAR.

**Comment by melloware** [comment]
I am going to close this ticket as PrimeTek uses Quill in PrimeNG, PrimeReact, and Primefaces so i doubt this will happen.
