### ISSUE TITLE
Add range selection support to Datepicker with month view

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#4941]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? 7.0 is latest
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not tested
- Affected browsers: FF, IE11

## 2) Expected behavior
A range of months should be selectable.

## 3) Actual behavior
The datepicker closes when a the start of the range was selected.

## 4) Steps to reproduce
 - click in input field to open datepicker
 - select first month => popup closes
 - reopen datepicker
 - end of range could be selected

## 5) Sample XHTML
```
<h:form id="frmMain">
    <p:datePicker view="month" selectionMode="range"  />
</h:form>
```
## 6) Sample bean
_Not needed_

**Comment by fanste** [comment]
JS throws an error if you additionally enable inline mode

```
TypeError: this.value.getMonth is not a function
```
In method `isMonthSelected`

**Comment by tandraschko** [comment]
@mertsincan can you check this? AFAIR you need to sync sources

**Comment by mertsincan** [comment]
Fixed now.
