### ISSUE TITLE
dataExporter : command buttons need to always have Ajax set to false

### ISSUE THREAD

**Issue by ozziej** [primefaces/primefaces#4946]
When using either commandButton or commandLink to enclose the p:dataExporter, these always need to be set to ajax=false.
If not, you get an error in the Javascript console (no output in server logs)

Request return with error:parsererror.
error: core.js.xhtml:174
(anonymous function) core.js.xhtml:1032
u - jquery.js.xhtml:1231
fireWith - jquery.js.xhtml:1269:98
k - jquery.js.xhtml:3352:616
(anonymous function) -  jquery.js.xhtml:3442:241

Primefaces 7.0 (community edition)
Application Server : Wildfly 10 / 13 / 15
Any browser (tested on Safari 12.1.1 and Chrome 75.0)

## 2) Expected behavior
File should download with the correct filename in the correct format (xls in this example)
Documentation should include this as a "must"
Sample code on pages should also include this note.
https://www.primefaces.org/showcase/ui/data/dataexporter

## 3) Actual behavior
Error as above in console

## 4) Steps to reproduce
Data table, with the commandLink or commandButton with p:dataExporter.
ajax=false NOT set. (i.e. default options as per below)
Include ajax="false" and it works perfectly. remove this and it fails with error.

## 5) Sample XHTML
<h:form id="orderListForm">
                    <p:dataTable style="margin-top:8px;font-size:14px;" id="orderDataTable" var="orderData" value="#{ordersController.orders}" rows="10"
                                 paginator="true" paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                 rowsPerPageTemplate="5,10,15" selection="#{ordersController.selectedOrder}" selectionMode="single" widgetVar="ordersTable" lazy="true"
                                 rowKey="#{orderData.orderId}" paginatorPosition="top">
                        <p:column headerText="Order Id" style="text-align: center;" sortBy="#{orderData.orderId}">
                            <h:outputText value="#{orderData.orderId}"/>
                        </p:column>
                        <p:column headerText="Created By" style="text-align: center;" sortBy="#{orderData.user}">
                            <h:outputText value="#{orderData.user.firstName} #{orderData.user.surname}"/>
                        </p:column>
                        <p:column headerText="Company Name" style="text-align: center;" sortBy="#{orderData.company}">
                            <h:outputText value="#{orderData.company.companyName}"/>
                        </p:column>
                        <p:column headerText="Order Date" sortBy="#{orderData.orderDate}">
                            <h:outputText value="#{orderData.orderDate}"/>
                        </p:column>
                        <p:column headerText="Order Status" sortBy="#{orderData.statusType}">
                            <h:outputText value="#{orderData.statusType}"/>
                        </p:column>
                    </p:dataTable>
                    <p:commandButton value="Export">
                        <p:dataExporter type="xls" target=":orderListForm:orderDataTable" fileName="orders"/>
                    </p:commandButton>
                </h:form>
..

## 6) Sample bean
    public void getOrdersList() {
        orders = new LazyDataModel<Orders>() {...}

    public Orders getSelectedOrder() {
        return selectedOrder;
    }

    public void setSelectedOrder(Orders selectedOrder) {
        this.selectedOrder = selectedOrder;
    }

    public LazyDataModel<Orders> getOrders() {
        return orders;
    }

<img width="383" alt="Screenshot 2019-06-27 at 09 50 32" src="https://user-images.githubusercontent.com/13061222/60247489-0fa39680-98c1-11e9-9678-5f37bf230cbc.png">

..

**Comment by tandraschko** [comment]
i think thats expected because you can't download a file via ajax.

**Comment by ozziej** [comment]
> i think thats expected because you can't download a file via ajax.

Sure, but, it's not documented in the examples NOR the documentation and if this is the case, it should at least produce a decent error - not some random error on the browser console.

**Comment by tandraschko** [comment]
Sure! Would you like to provide a PR for a better documentation?

**Comment by tandraschko** [comment]
mentioned it in the documentation now.
