### ISSUE TITLE
DatePicker: popup panel hidden in DataTable

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#4953]
## 1) Environment
- PrimeFaces version: 7.0.4
- Application server + version: WildFly 16.0.0
- Affected browsers: all

## 2) Expected behavior

DatePicker's popup panel appears correctly over DataTable's cells.

## 3) Actual behavior

DatePicker's popup panel overflow hidden inside DataTable's cell.

## 4) Steps to reproduce

Use DataTable with DatePicker in one of the columns.

My browser reports overflow:hidden comes from components.css.xhtml line 1158:
> .ui-datatable thead th, .ui-datatable tbody td, .ui-datatable tfoot td, .ui-datatable tfoot th

Another overflow:auto which hides the panel comes from components.css.xhtml line 1136:
> .ui-datatable-tablewrapper

I think the panel itself in DatePicker is implemented incorrectly, it should display properly over everything.

**Comment by melloware** [comment]
Reproducible Test Case: 
[pf-4953.zip](https://github.com/primefaces/primefaces/files/3349711/pf-4953.zip)

**Comment by tandraschko** [comment]
Isnt it the same as: https://github.com/primefaces/primefaces/issues/5024#issuecomment-549873683 ?

**Comment by melloware** [comment]
Yes. I just tested my example with `appendTo="@(body)"` and its working great!  Closing this ticket.
