### ISSUE TITLE
DatePicker: annoying min-width

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#4954]
## 1) Environment
- PrimeFaces version: 7.0.4
- Application server + version: WildFly 16.0.0
- Affected browsers: all

## 2) Expected behavior

DatePicker's text input is as flexible as text inputs from other components.

## 3) Actual behavior

DatePicker's text input is forced to have a min-width of 17em by '.p-datepicker' class (components.css.xhtml line 5973). This is way too long for date only (or year-month only) patterns.

## 4) Steps to reproduce

Use DatePicker :)

**Comment by morvael** [comment]
I think it's a defect - other input components are not enforcing their width in such brute force way.

**Comment by melloware** [comment]
@morvael What happens if you remove that 17em?  Does the component look and work fine?

**Comment by morvael** [comment]
Yes, I did just that and it worked fine. Input was narrower than picker panel, as it should be. Someone wanted to make input just as wide as picker panel. Maybe makes sense in inline mode, with popup not so much.

**Comment by melloware** [comment]
I agree min-width should not be defined.  PR submitted.
