### ISSUE TITLE
DatePicker: Omega Theme MonthPicker CSS Issue

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#4955]
## 1) Environment
- PrimeFaces version: 7.0.4
- Application server + version: WildFly 16.0.0
- Affected browsers: all

## 2) Expected behavior

Month names displayed in 3 columns and 4 rows.

## 3) Actual behavior

Month names displayed in 2 columns and 6 rows with plenty of empty space on the right.

## 4) Steps to reproduce

Used DatePicker with Polish month names:
> monthNamesShort: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'],

As a workaround I've modified width manually:
> .ui-monthpicker .ui-monthpicker-month {
>     width: 4.5em !important;
> }

**Comment by morvael** [comment]
I think it's a defect - month picker should display itself in the same way in any language (provided short month names are 3-letter long).

**Comment by melloware** [comment]
So looking at the CSS it has `width: 33.3%` to give each column 1/3rd.  when I tried your Polish Month Names in the Showcase it looks fine?

![image](https://user-images.githubusercontent.com/4399574/60456675-e740d280-9c07-11e9-9117-9de22d242702.png)

**Comment by morvael** [comment]
I guess with some differences in margin due to global style inheritance, 33.3% was too long. This component's CSS should make sure to specify its own margins so that the look will work unless direct CSS will be overridden.

**Comment by melloware** [comment]
So do you mean your own CSS's global inheritance or PF?  So to me it looks like everything is working unless you globally change margins with your own CSS? 

If that is the case i think this ticket is invalid because you have changed the margins of the app.

**Comment by morvael** [comment]
Will verify tomorrow. My CSS consists mostly of hacks needed for PF to display correctly (as I see it), not as they want to be displayed. Through the years some bloat may have crept in. The problem is if a component doesn't protect itself some very generic setting applied on very high level (like default font size) can alter its presentation significantly. Width 33.3% means 0 space for margins, so they should be specified as such.

**Comment by morvael** [comment]
I have checked and there is nothing affecting this component except global
> .ui-widget {
>     font-size: 10pt !important;
> }

and it looks like this:
![cal](https://user-images.githubusercontent.com/1133953/60491925-26276480-9caa-11e9-98b2-6c472daf5b0b.jpg)

**Comment by morvael** [comment]
Now that I compare those two images I see differences, especially the dark bar. Don't know what's causing this, as we only have the primefaces library dependency, without any other theme library enabled.

So, the showcase runs with nova theme enabled. Perhaps the problem is limited to default (no) theme configuration.

**Comment by morvael** [comment]
Replicated this in showcase. Switch theme to Omega and observe :)

**Comment by melloware** [comment]
OK updated title and marked it as a defect in Omega Theme CSS.

**Comment by melloware** [comment]
Because this is a theme issue that the community cannot fix I reported it on the forums for Omega: https://forum.primefaces.org/viewtopic.php?f=40&t=60106

Please follow the issue there and I will close this ticket.
