### ISSUE TITLE
Themes: Wrong characters in packaged theme.css

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#4958]
## 1) Environment
- PrimeFaces version: 7.0.4
- Application server + version: WildFly 16.0.0
- Affected browsers: all

## 2) Expected behavior

Icons made from unicode characters stored in css display correctly.

## 3) Actual behavior

Icons made from unicode characters stored in css do not display correctly.

Spent a lot of time on this. Made sure my WildFly appends correct encoding headers etc to no avail.

Breadcrumb in Omega theme which uses plain image:
![bc_omega](https://user-images.githubusercontent.com/1133953/60508036-d3f63b80-9cc9-11e9-8be7-99a4fb10a7d9.png)
Breadcrumb in Nova-dark theme which uses unicode character:
![bc_nova_dark](https://user-images.githubusercontent.com/1133953/60508064-deb0d080-9cc9-11e9-8d6d-82072e0ece16.png)

CSS as seen in Chrome:
![css_downloaded](https://user-images.githubusercontent.com/1133953/60508137-13bd2300-9cca-11e9-8d9a-0789577c95cb.png)

CSS pulled directly from primefaces jar, text editor displays warning (even if I manually set encoding to UTF-8):
![editor](https://user-images.githubusercontent.com/1133953/60508197-3ea77700-9cca-11e9-9e5d-86acd55443b6.png)

CSS pulled from https://www.primefaces.org/showcase/javax.faces.resource/theme.css.xhtml?ln=primefaces-nova-dark
![css_page](https://user-images.githubusercontent.com/1133953/60508257-6991cb00-9cca-11e9-9077-2342afaa2fc2.png)

PF's showcase uses uncompressed (un-minified) css, maybe in the process of compression (minification) those CSS files are damaged?

**Comment by tandraschko** [comment]
needs to checked by mert

**Comment by morvael** [comment]
Attaching test page from bug [4959](https://github.com/primefaces/primefaces/issues/4959), which also allows to verify this issue:
[breadcrumb.zip](https://github.com/primefaces/primefaces/files/3353765/breadcrumb.zip)

Looks like this:
![bugs](https://user-images.githubusercontent.com/1133953/60572778-98fe1180-9d76-11e9-9aa3-183e18462dcc.png)

**Comment by morvael** [comment]
Make sure to run it with published primefaces-7.0.4.jar, not sources :)

**Comment by melloware** [comment]
@mertsincan It looks like even the source is messed up.

**Comment by mertsincan** [comment]
I couldn't replicate this issue. Please see;
https://www.dropbox.com/s/gadfb5e6keq1fu8/Theme_icon_test.avi?dl=0

Also, Omega and Aristo theme use an image for icons but the other themes use an icon library named PrimeIcons.

> Icons made from unicode characters stored in css do not display correctly.
- This is related to encoding. We are using SASS to create new themes and when you provide CSS files from SASS file, it encodes icon codes. I don't think this will be a problem. We use this method on all Premium Layouts. You can check this in live demos. Exp; 
![prestige_layout_icon_test](https://user-images.githubusercontent.com/11868120/66126611-87850980-e5f2-11e9-9f6d-ce92c01eac80.PNG)

Best Regards,

**Comment by melloware** [comment]
@mertsincan Is it just a matter of adding this to the page for the premium themes?
```xml
 <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces"/>
```

**Comment by morvael** [comment]
EE A4 81 from theme pulled from https://www.primefaces.org/showcase/javax.faces.resource/theme.css.xhtml?ln=primefaces-nova-dark
![Screenshot at 2019-10-03 14-36-54](https://user-images.githubusercontent.com/1133953/66127243-80a6c880-e5eb-11e9-9c40-c8a1de227bbf.png)
EE A4 3F from theme pulled from primefaces-7.0.5.jar
![Screenshot at 2019-10-03 14-37-45](https://user-images.githubusercontent.com/1133953/66127276-94522f00-e5eb-11e9-9c06-76e20a210c79.png)

**Comment by morvael** [comment]
First file opens in xed editor without problems. Second gives warning about invalid characters. Bytes differ. So something must be wrong.

**Comment by morvael** [comment]
Files in my possession:
[themes.zip](https://github.com/primefaces/primefaces/files/3686047/themes.zip)

**Comment by morvael** [comment]
Bad file:
    iconv -f UTF-8 theme.css -o /dev/null; echo $?
    iconv: illegal input sequence at position 32498
    1

Good file:
    iconv -f UTF-8 theme.css.xhtml\?ln\=primefaces-nova-dark -o /dev/null; echo $?
    0

**Comment by mertsincan** [comment]
@melloware, premium layouts use FontAwesome icons. Luna and Nova use primeicons. My above comment is related to icon encoding. When you provide CSS file from SASS file, It encodes all icons of any library.

@morvael, does it work with PF7.0.5 or the latest elite version?

**Comment by morvael** [comment]
Icons in primeicons are perhaps encoded ok, but the unicode character pointing to them in the css is damaged during css compression.

Doesn't work in 7.0.5. Haven't upgraded to latest PF yet, but may soon check the css file stored inside.

**Comment by morvael** [comment]
In 7.0.8:
iconv -f UTF-8 theme.css -o /dev/null; echo $?
iconv: illegal input sequence at position 32498
1

**Comment by mertsincan** [comment]
> maybe in the process of compression (minification) those CSS files are damaged?
- You're right! I checked it again. if the last two characters of the icon code end with 01, yuicompressor is encoding wrong. Exp;
```
in scss file;
ui-datepicker-next:before {content: "\e901"} /* or \e801 or \e701 etc*/
```
the output after yuicompressor;
![image](https://user-images.githubusercontent.com/11868120/66133966-3845d580-e600-11e9-960e-77af02ddccb5.png)

When I change content code, exp; ui-datepicker-next:before {content: "\e902"}
the output after yuicompressor;
![image](https://user-images.githubusercontent.com/11868120/66134091-69bea100-e600-11e9-9e52-4873dec2be81.png)

Before yuicompressor;
![image](https://user-images.githubusercontent.com/11868120/66134139-82c75200-e600-11e9-987c-fcc0fe34047b.png)

**Comment by morvael** [comment]
That's the message I was trying to convey from the start :)

**Comment by mertsincan** [comment]
We don't use yuicompressor on Premium Layouts. Therefore, until now, no questions about it did not come on them.

Example, you don't have a problem with home icon of breadcrumb. Because its icon code is "\e925" (not 01). Right?

**Comment by morvael** [comment]
Yes, it's even visible in the first post of this bug report.

**Comment by mertsincan** [comment]
Thanks a lot for the update! I think we can exclude theme.css files from yuicompressor on pom.xml. @tandraschko @melloware WDYT?

**Comment by melloware** [comment]
So can you stop SASS from encoding them?  Because I just ran a test with YUI Compressor raw and it compressed this properly.
```css
.ui-icon-triangle-1-n:before{content:"\e933"}body .ui-button .ui-icon-clock:before{content:"\e901"}
```
So really having the raw unicode values would allow YUI to still work and I definitely think we want to be compressing our CSS.

**Comment by melloware** [comment]
Or in your SASS build script if you are using NPM use uglify.js to compress the CSS before you check it  into GitHub here.  Then we just exclude them from being compressed?

**Comment by mertsincan** [comment]
Hi @melloware,
> So can you stop SASS from encoding them?
- No, please see this issue; https://github.com/sass/sass/issues/1395 this link contains a lot of solutions. But, hacky.
> So really having the raw unicode values would allow YUI to still work and I definitely think we want to be compressing our CSS. ...
> Or in your SASS build script if you are using NPM use uglify.js to compress the CSS before you check it into GitHub here. Then we just exclude them from being compressed?
- I'll create gulp file for it on designer and test this issue.
