### ISSUE TITLE
UIData: rowIndexVar ignored when rowStatePreserved=true

### ISSUE THREAD

**Issue by mbechler** [primefaces/primefaces#496]
The copied UIData.setRowIndexRowStatePreserved implementation does not set the rowIndexVar in the request context. Probably should call setRowModel.

**Comment by tandraschko** [comment]
Would you like to provide a PR?

**Comment by tandraschko** [comment]
can't find anything like this in the original method, will close it as invalid as infos are missing.
You can still create a new issue and provide all informations requested by our issue template.
