### ISSUE TITLE
Menuitem: Menuitem with commandlink creating two anchor tags for menurenderer

### ISSUE THREAD

**Issue by krishnakittu** [primefaces/primefaces#4960]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not tested
- Application server + version: glassfish 5.1
- Affected browsers: all

## 2) Expected behavior
It should be rendered as only one anchor tag rather than two anchor tags. In Splitbutton it is rendered as only one anchor tag
...

## 3) Actual behavior
It is rendered as two anchor tags.
..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<p:menu my="left top"
		at="left bottom"
		style="white-space: nowrap;
					width:auto;background-color : #f4f4f4">
					<p:menuitem>
						<p:commandLink styleClass="ui-menuitem-link">
						<h:outputText styleClass="ui-menuitem-icon ui-icon ui-icon-file-upload" />
                        <h:outputText styleClass="ui-menuitem-text" value="test Menu" />
						</p:commandLink>
					</p:menuitem>
		
		</p:menu>
..

## 6) Sample bean
No Bean is needed.
..

**Comment by melloware** [comment]
I guess my question is why are you using a commandlink inside the menu item when the menuitem is a command link?

```xml
<p:menuitem value="Test Menu" icon="ui-icon-file-upload"/>
```

Is the exact same as what you are doing above without the need for the extra command link.

**Comment by krishnakittu** [comment]
Yes we can acheive the same by done above. But furhter i need to extend this to support dialog return event on the menuitem.

**Comment by melloware** [comment]
So really you want this ticket fixed:  https://github.com/primefaces/primefaces/issues/52

Correct?

**Comment by krishnakittu** [comment]
Yes. If it was closed it was a very good move for me. For the time being i am looking for alternate ways to fix this.

**Comment by melloware** [comment]
Then I will mark this ticket as a duplicate and close as the real issue is that you want Dialog Return in MenuItem.

**Comment by melloware** [comment]
@krishnakittu @Rapster has submitted a PR that will fix this issue: https://github.com/primefaces/primefaces/pull/5003

**Comment by krishnakittu** [comment]
Thank you very much for notifying me.
