### ISSUE TITLE
OutputLabel: removes style attribute from h:inputText

### ISSUE THREAD

**Issue by smirnov-vladimir** [primefaces/primefaces#4964]
## 1) Environment
- PrimeFaces version: 5, 6, 7
- Application server: WildFly 12, 16, 17. Error is **not** reproduced in WildFly 10

## 2) Expected behavior
After click button and AJAX request complete, the `inputText` stil have `style="background-color: red"`

## 3) Actual behavior
After AJAX request complete and DOM updated, HTML `input` lost `style` attribute. `<partial-response>` contains no `style` attribute in `<input>` element.

## 4) Steps to reproduce
`value` attribute of the `OutputLabel` must be reference to some `resource-bundle` like  `value="#{msg.testMsg}"`.
If define like `value="Test message"`, then **not** reproduced. Also **not** reproduced if replace `h:inputText` with `p:inputText`

## 5) Sample XHTML
```
<html xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<f:view>
    <h:head/>

    <h:body>
        <h:form>
            <h:panelGrid id="gridSearch" columns="2">
                <p:outputLabel value="#{msg.testMsg}" for="pinInput1"/><!--Broken-->
                <h:inputText style="background-color: red" id="pinInput1"/>

                <p:outputLabel value="Test message" for="pinInput2"/><!--OK-->
                <h:inputText style="background-color: red" id="pinInput2"/>

                <p:commandButton update="@form" value="Submit"/>
            </h:panelGrid>
        </h:form>
    </h:body>
</f:view>
</html>

**Comment by tandraschko** [comment]
Pleaese provide a forked primefaces-test project, otherwise i cant replicate it.

**Comment by smirnov-vladimir** [comment]
I sink, its reproducible with Mojarra 2.3, but profile `mojarra23` wont start with command `mvn jetty:run-exploded`.
This is my project: https://drive.google.com/uc?authuser=0&id=16CketklEXVSSafrxJJtO8oV1JH0uD1Gf&export=download

This is already packaged WAR: https://drive.google.com/uc?authuser=0&id=1zNIP2qRr51BMEOv0Twg6WcAcngCXxpv9&export=download
Just deploy on any version of WildFly from 12 to 17 (have Mojarra 2.3) to reproduce

**Comment by tandraschko** [comment]
It's probably a Mojarra bug. It works fine with MyFaces and with p:inputText.
