### ISSUE TITLE
Charts exported to PNG show wrong legend position

### ISSUE THREAD

**Issue by robertoferreirajrr** [primefaces/primefaces#4967]
Hi! When I export a charts to a png, the legends of the chart appears in wrong position! In the showcase it happens too!... I using primefaces 7.0, i see that in show case the version is 7.1, and still happening... I know that this issue not follow the recommended template, but like I describe, the problem occurs in showcase... 

![Image of Problem](https://i.ibb.co/N7nmd0v/Deepin-Screenshot-selecionar-rea-20190704091618.png)

**Comment by melloware** [comment]
I believe its related to this issue: https://github.com/jqPlot/jqPlot/issues/144

Have you tried the newer ChartsJS?   https://www.primefaces.org/showcase/ui/chartjs/export.xhtml

The Charts you are using are the old JQPlot Charts which still have bugs and the library is not updated much anymore.

**Comment by robertoferreirajrr** [comment]
Hi @melloware , thanks for your answer..

I don't believe that this issue is related, like you said the library is too old, probably the same version of library is used in both, Primefaces 6.2 and 7... in the 6.2 all works perfect!

Unfortunately my code have a lot of customization using charts in Jqplot, combining jqplot plugins, I planing work in a code change to a newer library, like chartjs, only when I can't use jqplot more lol :D...

**Comment by melloware** [comment]
Ahh yes between 6.2 and 7.0 we upgraded to latest JQPlot : https://github.com/primefaces/primefaces/issues/1030

So that must have broken your issue.  If you can figure out the change I would be happy to fix it.

**Comment by mertsincan** [comment]
This issue is related to Jquery version. Fixed for 7.0.5 and 7.1.

![image](https://user-images.githubusercontent.com/11868120/60672519-40b23700-9e7e-11e9-9ab1-e61ecdd97757.png)

**Comment by robertoferreirajrr** [comment]
Nice! =) Thanks guys! Excellent support! Primefaces rocks!

**Comment by robertoferreirajrr** [comment]
When this changes will be available in maven repositories?

**Comment by robertoferreirajrr** [comment]
@mertsincan The problem persists in showcase again... 

![Image of Problem](https://i.ibb.co/N7nmd0v/Deepin-Screenshot-selecionar-rea-20190704091618.png)

showcase PrimeFaces-7.1-SNAPSHOT on Mojarra-2.3.2.
