### ISSUE TITLE
Datatable: Partial rendering of datatable with stickyHeader="true" and stickyTopAt="..." increases z-index of div

### ISSUE THREAD

**Issue by dgusoft** [primefaces/primefaces#4968]
## 1) Environment
- PrimeFaces version: 7.0.2
- Application server + version: JBoss EAP 7.0.7.GA (Mojarra 2.2.12.SP4)
- Affected browsers: chrome
## 2) Expected behavior
Partial rendering of datatable with sticky table header should keep z-index stable
## 3) Actual behavior
z-index of div-Element above table-element increases with each ajax request which causes the datatable to be partially rendered.
example in our application:
before partial rendering:
<pre>
&lt;div class="ui-datatable ui-datatable-sticky ui-widget ui-shadow ui-sticky" style="position: fixed; width: 1629px; top: 0px; left: 17px; z-index: 1001;"&gt;
</pre>
after partial rendering
<pre>
&lt;div class="ui-datatable ui-datatable-sticky ui-widget ui-shadow ui-sticky" style="position: fixed; width: 1629px; top: 0px; left: 17px; z-index: 1003;"&gt;
</pre>

This behaviour leads to the effect that the drop downs of the primefaces menubar appear under the sticky table header after some partial renderings.

## 4) Steps to reproduce
Put a p:datatable on a sample page and a commandbutton which causes the datatable to rerender on ajax request.
## 5) Sample XHTML
...
<pre>
&lt;div class="ui-sticky"&gt;&lt;/div&gt;
&lt;p:dataTable id="id" var="item" value="#{controller.list}"
            	      stickyHeader="true" stickyTopAt=".ui-sticky"
                      rowSelectMode="checkbox" 
                      selection="#{controller.selectedRows}" rowKey="#{item.id}"&gt;
...
</p:dataTable>
</pre>
...

## 6) Cause
This part of the setupStickyHeader-function of datatable.js is responsible for the increasing z-index:
<pre>
        this.stickyContainer.css({
            position: "absolute",
            width: d.outerWidth(),
            top: g.top,
            left: g.left,
            "z-index": ++PrimeFaces.zindex
        });
</pre>
By the way: It is not the only code fragment where "++PrimeFaces.zindex" is found in the primefaces-javascript. In my oppinion this sort of dynamic increase of the zindex auf html-Elements leads to a lot of issues.

**Comment by tandraschko** [comment]
no runnable example (controller missing) -> invalid

**Comment by melloware** [comment]
Can you please create a runnable example using Primefaces Test: https://github.com/primefaces/primefaces-test

If not I am afraid your ticket will be closed.  I do agree the zindex++ feels like a code smell to me but I need to see the problem in action.
