### ISSUE TITLE
Sticky: initialization incomplete

### ISSUE THREAD

**Issue by metaxmx** [primefaces/primefaces#497]
The "Sticky" component does not fully support reloading:
- The component performs the first layouting when the first window.scroll event is fired.If the browser is already scrolled down when the sticky component is initializing, the target component is not made sticky until the user starts scrolling
- The status of the Sticky JavaScript component is not reset completely on reloading. When the Sticky and the target component is refreshed, while the user is scolled down below the original position of the target component, it is not layouted until the user has scrolled up above the position of the target component, and then scrolled down again

Tested on Primefaces 5.2

See the following GIST as demo:
https://gist.github.com/metaxmx/5ee091da6c0c16630575

**Comment by tandraschko** [comment]
Feel free to provide a PR!

**Comment by melloware** [comment]
Here is a reproducer using PF 8.0 and this seems fixed to me: 
[pf-497.zip](https://github.com/primefaces/primefaces/files/5755523/pf-497.zip)

I actually think it was fixed by https://github.com/primefaces/primefaces/issues/660
