### ISSUE TITLE
Lazy Data Table pagination changes displays raw text instead of datat able.

### ISSUE THREAD

**Issue by balayogeeswar** [primefaces/primefaces#498]
Dear PF team,

I have implemented Lazy data loading in ta tab view , Once the data loaded I will set total count of records from db and i will only fetch few records based on LIMIT, but when i click pagination the data table fetches the data and displays like raw text , how can fix this?.

Please let me know how to fix this. am using latest prime faces version too.
![on data load](https://cloud.githubusercontent.com/assets/5469469/8514339/e4ddc7ce-23bf-11e5-854c-fd720b331c4a.PNG)

![upon click paginator displays raw text](https://cloud.githubusercontent.com/assets/5469469/8514337/dd14f3d2-23bf-11e5-99af-cd85f6949e02.PNG)

**Comment by cagataycivici** [comment]
Please use forum for cases like these, probably you are updating the datatable itself or its container on page event via p:ajax event="page".
