### ISSUE TITLE
Default command is triggered inside text areas

### ISSUE THREAD

**Issue by beadaptive** [primefaces/primefaces#4984]
## Summary
In Primefaces 7.0 (and latest), the default command is triggered even when inside a textarea. Adding a new line in the text area triggers the default command. The problem seems to be that the event target is incorrect. There is a check in place

`$(e.target).is('textarea,button,input[type="submit"],a')`

However, the target is not resolved to a textarea. In PF 6 this worked as expected and there was a change in forms.defaultcommand.js 7 months ago, fixing [#4324](https://github.com/primefaces/primefaces/issues/4324).

## 1) Environment
- PrimeFaces version: 7.0
- Does not work in latest snapshot either
- Affected browsers: Tested in Chrome, Firefox, IE

## 2) Expected behavior
The default command should not be triggered when inside a textarea.

## 3) Actual behavior
The default command is triggered when inside a text area.

## 4) Steps to reproduce
Create a textarea and a commandlink with default command. Try to add a new line in the textarea, the default command is triggered.

**Comment by tandraschko** [comment]
@mertsincan as it was your change, would you like to check it?

**Comment by mertsincan** [comment]
Hi @beadaptive,

Unfortunately, I couldn't replicate it. Could you please attach a sample maven project for us to replicate?

For now, this issue is "can't replicate".

Best Regards,

**Comment by beadaptive** [comment]
[pf-4984.zip](https://github.com/primefaces/primefaces/files/3504572/pf-4984.zip)

Hi,
sure, project is attached. I've also included Eclipse settings, you can remove them of course.
Just open http://localhost:8080/pf-4984/, enter some text to the text area and press enter. The default command is then triggered inside the text area.
We are using MyFaces (2.2 and 2.3), but this should not be the problem i suppose. It works when we revert the js-part back to the version before the change, so it is definitely connected to the change mentioned before.

Best regards,

**Comment by melloware** [comment]
@beadaptive Thanks for the reproducer.  
@mertsincan here is an easier version using Primefaces Test.  Just run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

[pf-4984.zip](https://github.com/primefaces/primefaces/files/3506038/pf-4984.zip)

**Comment by melloware** [comment]
@mertsincan Debugging this it appears in this line....

```javascript
if ($(e.target).is('textarea,button,input[type="submit"],a')) {
```
$(e.target) is the FORM and not the TEXTAREA.
