### ISSUE TITLE
DatePicker/Calendar duplicates

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#4988]
`Calendar#queueEvents()` and `Calendar#validate()` seems to be duplicate with `DatePicker#queueEvents()` and `DatePicker#validate()`

Safe to pull that up to UICalendar?

**Comment by tandraschko** [comment]
Calendar is deprecated? If yes, i wouldnt do it

**Comment by Rapster** [comment]
Yeah indeed, but there is nothing saying when it will be removed from PF though
