### ISSUE TITLE
Primefaces + Atmosphere Push Message Bug

### ISSUE THREAD

**Issue by indracrg** [primefaces/primefaces#499]
Updating the latest Primefaces and Atmosphere libraries in our system the push messages stop working, doing some tests and research we found that using PF 5.2.7 with Atmosphere 2.3.1 (or higher) in a Wildfly 8.2 (JEE7, Servlet 3.1), make Push messages unresponsive. It seems a change in Atmosphere 2.3.1+ related with the bug https://github.com/Atmosphere/atmosphere/issues/1799. 
We have tried the workaround with the Primefaces’ Push Servlet but websocket remains unresponsive. By now, downgrading Atmosphere to 2.3.0 fixes the problem.

Maybe this enhancement #317 is the way or maybe the solution must come from Atmosphere and a real solution of their https://github.com/Atmosphere/atmosphere/issues/1799 issue.

**Comment by jfarcand** [comment]
Can you share some exception or code describing the issue?

**Comment by jfarcand** [comment]
Please try `2.3.4-SNAPSHOT`, I think I've found the issue.

**Comment by indracrg** [comment]
We are sorry for the delay. We tried with 2.3.4-SNAPSHOT but it didn't work. There isn't a exception or trace to pinpoint the issue, all we know is that apparently the p:socket doesn't receive the notification we are firing.

Thanks.

**Comment by jfarcand** [comment]
@indracrg I will need a test to reproduce it. Try with the `showcase` or any primefaces demo. For me after this fixes everything works as expected.

**Comment by indracrg** [comment]
Hello, we are sorry again for the delay. We got it working with Atmosphere 2.3.4-SNAPSHOT and Primefaces 5.2.8

Thank you very much for your help!
