### ISSUE TITLE
Image Cropper boxHeight/boxWidth

### ISSUE THREAD

**Issue by neXus1987** [primefaces/primefaces#4991]
Hello,

i´ve got the Problem that in Primefaces 7.0 the imageCropper selection area is too large, when i set the boxWidth/boxHeight. The image is smaller, but the selection area is too large. As i googled, there is something with trueSize for jCrop, maybe this will help!?

Thanks
Phil

**Comment by tandraschko** [comment]
Please follow our issue template or use the forum.
