### ISSUE TITLE
ImageCropper: boxHeight/boxWidth breaks selectionArea

### ISSUE THREAD

**Issue by neXus1987** [primefaces/primefaces#4992]
## 1) Environment
- PrimeFaces version: 7.0
- It works on 6.2
- tomcat 8.5
- Affected browsers: Firefox/Chrome

## 2) Expected behavior

when setting the boxHeight/boxWitdth, the image is shown on this fixed sizes and the selection area is scaled down/up

## 3) Actual behavior

the image is shown in boxWidth/boxHeight size, but the selection Area is shown as the image would be on original size

## 4) Steps to reproduce

load and image with the imageCropper (eg. 1000x1000), set the boxWidth/boxHeight to 500x500 and the minSize="750,750". So the selectionArea will be outside the image.

## 5) Sample XHTML
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">
<f:view locale="de" contentType="text/html">

	<h:head>
		<title>ImageCropper</title>

	</h:head>
	<h:body>
		<h:form>

			<p:imageCropper initialCoords="" image="https://www.hellwach-medien.de/wp-content/uploads/2019/07/66752695_424769121443548_5306511280520036352_n.png" boxWidth="500" boxHeight="500"
				minSize="750,750"></p:imageCropper>
		</h:form>

		<h:form>

			<p:imageCropper initialCoords=""   image="https://www.hellwach-medien.de/wp-content/uploads/2019/07/66752695_424769121443548_5306511280520036352_n.png" minSize="750,750"></p:imageCropper>
		</h:form>
	</h:body>
</f:view>

</html>

## 6) Sample bean

not used

**Comment by neXus1987** [comment]
as i googled, there is an option trueSize for jCrop, maybe this is the solution?

**Comment by melloware** [comment]
I believe this is what you mean? http://deepliquid.com/content/Jcrop_Sizing_Issues.html

**Comment by neXus1987** [comment]
Yes this is what i mean, but as i read the document, it should work just with boxHeight/boxWidth, but it won't. In my example the selection area is larger than the image, because the image is scaled to 500x500 (trueSize 1000x1000) and the selection area is 750x750 and is not down scaled to - in this example - 375x375

**Comment by melloware** [comment]
You might want to search through JCrop issues might be a bug there: https://github.com/tapmodo/Jcrop/issues

**Comment by neXus1987** [comment]
Yes, this sounds like my error:

https://github.com/tapmodo/Jcrop/issues/276

**Comment by neXus1987** [comment]
calculating the scaled minSize before setting it would be a temporary fix:

//ImageSize beinhaltet die original minWidth/minHeight
	public String getMinSize(String url, ImageSize config, Integer boxWidth, Integer boxHeight) {

		 
		String	imageMinSize = "100,100";// getWidth() + "," + getHeight();
			BufferedImage img;
			try {
				img = ImageIO.read(new URL(url));

				Integer imageWidth = img.getWidth();
				Integer imageHeight = img.getHeight();
				img.flush();

				Double minSizeWidth = null;
				Double minSizeHeight = null;
				Double ratio = (Double) imageWidth.doubleValue() / (Double) imageHeight.doubleValue();

				Double ratioBox = (Double) boxWidth.doubleValue() / (Double) boxHeight.doubleValue();
				double imgRatioScale;
				if (ratioBox > ratio) {

					imgRatioScale = boxHeight.doubleValue() / imageHeight.doubleValue();
					 
				} else {
					imgRatioScale = boxWidth.doubleValue() / imageWidth.doubleValue();
				}

				minSizeWidth = ((double) config.getWidth()) * imgRatioScale;
				minSizeHeight = ((double) config.getHeight()) *imgRatioScale;
				imageMinSize = minSizeWidth.intValue() + "," + minSizeHeight.intValue();

			} catch (Exception e) {
				logger.error("error image min size " + url, e);
			}
		 
		return imageMinSize;
	}

**Comment by melloware** [comment]
Shouldn't this be submitted as a PR on the JCrop github as the issue lies in the core JCrop code?

**Comment by tandraschko** [comment]
yup

**Comment by melloware** [comment]
@neXus1987 I am thinking of switching the plugin to not use JCrop anymore since Jcrop looks like it has stopped receiving updates.  There is Cropper.js https://fengyuanchen.github.io/cropperjs/ which is very popular and is kept up to date.

I don't see "boxHeight/boxWidth" equivalents in Cropper.js can you look?   They allow aspectRatio but I don't see anything about those two particular when looking to migrate off of JCrop.  Let me know if you see an equivalent way of doing it.

**Comment by melloware** [comment]
Closing this issue as its a JCrop issue.
