### ISSUE TITLE
DataScroller: new load AJAX event

### ISSUE THREAD

**Issue by neXus1987** [primefaces/primefaces#4994]
##  1) Environment
- PrimeFaces version: new Version
 

## 2) Expected behavior

<p:ajax event="load"/> so that after each data load this event is called. This is useful, when you have to do some javascript task after items are loaded.

## 3) Actual behavior

not available

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by neXus1987** [comment]
my workaround at the moment is, to call a javascript method for each row. for better performance i will ask if this is the last row from the load:

loadId=rowIndexVar+1
loadChunk=chunkSize
allElements=rowCount
if(loadId%loadChunk===0 || loadId===allElements  )

**Comment by tandraschko** [comment]
A PR would be great!

**Comment by neXus1987** [comment]
What is PR?

**Comment by tandraschko** [comment]
pull request

**Comment by neXus1987** [comment]
So i will push a new branch revert-4994-master with the additional code for this page event and then i can raise a PR?

(i´ve never worked on an "open source" git project)

**Comment by tandraschko** [comment]
Please just use the master branch. About a PR, just use google :)
