### ISSUE TITLE
Dialog/BlockUI: allow custom animation duration for show/hide

### ISSUE THREAD

**Issue by ssibitz** [primefaces/primefaces#4998]
## 1) Environment
I currently use the latest primefaces Elite/Pro Version 7.0.5.
As this function currently does not exists this is an extension 
for the existing release, but i think very easy to implement.

## 2) Expected behavior
I am using **e.g. the primefaces "ajaxStatus"** component
to show a please wait dialog and also lock the entire page while Ajax is not ready.
But when Ajax is ready i hide the "Please wait dialog" and then remove the page 
lock also by hiding them.

Now here's my problem/improvement idea:
In summary the hidding of the 2 components needs about 400ms because
the dialog and also the lock page will be faded out.
So it seems that in the background jQuery is working here which 
is able to set the speed in ms (milliseconds) or as text when i don't won't a 
default fadein/fadeout.

So is it possible to set the parameters of primefaces show/hide 
exact like i can do in jquery ?

Here an example to understand what i currently do
and what i want:

_My default form template i use on each form:_
```
<h:form id="DefaultFormId" prependId="false" autocomplete="off">
	<!-- Global Ajax please wait dialog -->
	<p:dialog widgetVar="bui" id="bui" modal="true" draggable="false" closable="false"
			  resizable="false" showHeader="false" position="center" style="z-index:10000; opacity: 0.85;">
		<p:panel style="margin-top:10px;">
			<f:facet name="header">
				<h:outputText value="Please wait" style="color:#000000;"/>
			</f:facet>
			<h:outputText style="color:#ffa500;" value="Loading, please wait..."/>
		</p:panel>
	</p:dialog>
    <!-- Inline javascript functions -->
    <h:outputScript>
        function LockPage() {
            PF('BlockDefaultLayoutWrapper').show();
            PF('bui').show();
        }
        function UnLockPage() {
                PF('bui').hide();
                PF('BlockDefaultLayoutWrapper').hide();
        }
        // Execute script on page ready
        $(document).ready(function()
        {
            UnLockPage();
        });
    </h:outputScript>
	<!-- Ajax status -->
	<p:blockUI block="DefaultLayoutWrapper" widgetVar="BlockDefaultLayoutWrapper"/>
	<p:ajaxStatus onstart="LockPage();" oncomplete="UnLockPage();" onerror="UnLockPage();" onsuccess="UnLockPage();"/>
</h:form>
```

The show() and the hide() functions fade the dialog and the blockUI page in/out
which is visual very slow for a user.

What i want is to call the show/hide like in jquery:
```
PF("...").show("fast");
PF("...").show("slow");
PF("...").show(); // Default 400ms like in jQuery
PF("...").show(100); // 100ms
```
... and the same for the hide function.

As i think that the function calling jquery inside
the only thing to do here is to pass the parameters directly to the jQuery functions ?!

**Comment by ssibitz** [comment]
As it seems only the blockUI-component is using fadein/fadeout,
but nevertheless the user/developer should have a way to control 
the fadein/fadeout time by using show/hide like in jquery as i described ...

**Comment by melloware** [comment]
Not a bad idea.  I assume you mean for BlockUI and for Dialog both.

**Comment by tandraschko** [comment]
AFAIR there are configs for the animation and animationDUration in some components.

**Comment by ssibitz** [comment]
@melloware :  
Yes, i mean **BlockUI** and **Dialog** because this are the "components" which are the most used.
So also a general dialog can be shown/hidden slow, fast or whatever the developer want.

@tandraschko : What do you mean with the "animation configs" in detail or is it an internal usage ?

**Comment by tandraschko** [comment]
https://primefaces.github.io/primefaces/7_0/#/components/dialog ;)

**Comment by ssibitz** [comment]
@tandraschko  : 
But for the Dialog and BlockUI i can't find a config that defines the hide/show time
when i later show or hide a Dialog or BlockUI by Javascript.

This is the default case for e.g. the BlockUI component and also for a Dialog ...

**Comment by tandraschko** [comment]
did you try show/hideEffect 'none' or empty?

**Comment by ssibitz** [comment]
Yes, and then the BlockUI animates about 400ms which seems as the default animation timeout of jQuery. And yes, i know that i can turn off the animation but i only want the animation faster ...

I wan't to "control" the speed because sometimes e.g. an Error-Dialog should be animated longer which causes the user to recognize that an error has occured as example.
When anything goes right, also the speed of a dialog can be "faster" which is an indicator for the user that anything is going right ...
