### ISSUE TITLE
SelectCheckboxMenu with SelectItemGroups

### ISSUE THREAD

**Issue by jrodalo** [primefaces/primefaces#500]
It would be nice if SelectCheckboxMenu supports SelectItemGroup like SelectOneMenu does.

With the following code:

``` xml
<p:selectCheckboxMenu value="#{checkboxView.selectedCars}" label="Cars">
    <f:selectItems value="#{checkboxView.cars}" />
</p:selectCheckboxMenu>
```

and

``` java
//cars
SelectItemGroup g1 = new SelectItemGroup("German Cars");
g1.setSelectItems(new SelectItem[] {
  new SelectItem("BMW", "BMW"),
  new SelectItem("Mercedes", "Mercedes"),
  new SelectItem("Volkswagen", "Volkswagen"
});

SelectItemGroup g2 = new SelectItemGroup("American Cars");
g2.setSelectItems(new SelectItem[] {
  new SelectItem("Chrysler", "Chrysler"),
  new SelectItem("GM", "GM"),
  new SelectItem("Ford", "Ford")
});

cars = new ArrayList<SelectItem>();
cars.add(g1);
cars.add(g2);
```

I expect to see something like this:

![primefaces_2](https://cloud.githubusercontent.com/assets/1197514/8520074/273a92d2-23cf-11e5-97a9-5db8deb80573.png)

But Primefaces 5.2.x its rendering this:

![primefaces_1](https://cloud.githubusercontent.com/assets/1197514/8520086/3ee784bc-23cf-11e5-8d80-e1b91626a59c.png)

**Comment by cagataycivici** [comment]
Sounds good to me :)

**Comment by OskarsPakers** [comment]
As a workaround I have used standard `h:selectManyCheckbox` component and to applied prime-like styling using primeUI.

```
$("[name='myForm:myCheckboxId']").puicheckbox();
```

**Comment by darwiesh** [comment]
is it soon to see the issue marked as closed ??

**Comment by OskarsPakers** [comment]
I added a pull request for this bugfix, but still no update.
https://github.com/primefaces/primefaces/pull/804

**Comment by tandraschko** [comment]
Mergen - Thanks for the PR!

**Comment by drj123** [comment]
if this issue is resolved. where I can find the sample code

**Comment by schmolleg** [comment]
Hi all, 
ich still have the same issue. I use primefaces 6.0 but the example code from above doesn't work. Does anyone have sample code. It's very urgent and i don't get the grouping working.

**Comment by OskarsPakers** [comment]
@schmolleg The pull request was about supporting grouped items in SelectManyCheckbox, it might be that SelectCheckboxMenu does not support grouped items still.

**Comment by schmolleg** [comment]
Oh you're right.
I need grouping in SelectCheckboxMenu i don't find a solution :-(
