### ISSUE TITLE
DataTable: Frozen column width massively increases when resizing browser window

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#5005]
## 1) Environment
- PrimeFaces version: 7.0.5

- Application server + version: Wildfly 15
- Affected browsers:
All

## 2) Expected behavior

When using a p:dataTable with frozen columns, I expect that the width of the frozen data part reflects the sum of the widths of the frozen data columns.
In my attached example, I've define the width of the single frozen column to 30px, but indeed the frozen col will be rendered much bigger (130px).
![grafik](https://user-images.githubusercontent.com/47218021/61461617-5856e880-a971-11e9-8907-ff4232caa470.png)

When resizing the browser window, firs shrink it an then make it bigger, the frozen coulmn size massively grows, while the data part of the table shrinks. The frozen col grows even when reducing the browser window width.

![grafik](https://user-images.githubusercontent.com/47218021/61461749-9fdd7480-a971-11e9-83b5-1c8a8cf39c29.png)

As a workaround I can control the width of the frozen table by adapting the style class **.ui-datatable-frozenlayout-left**, but this is very uncomfortable.
e.g.
``
.ui-datatable-frozenlayout-left {
	width: 5%
}
``

Example see attached zip file, contaning:
XHTML
CSS
Bean
theme
[PF_ticket2.zip](https://github.com/primefaces/primefaces/files/3406721/PF_ticket2.zip)

..

**Comment by melloware** [comment]
I can't reproduce this in 12.0. If you can reproduce it in 12.0 please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

I will re-open if you can provide that.
