### ISSUE TITLE
Refactor BaseCalendarRenderer#getConvertedValue

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#5006]
Method's complexity is way too high. The way of how exception are handled are too cumbersome (I blame java for that...) Using Try monad could help. PR on this way (SPOILER alert: I took a lot on liberty on this)

Feedbacks are welcome 😉 

I tagged it as enhancement but it's also experimental 😋

**Comment by Rapster** [comment]
@christophs78 @melloware @tandraschko Thanks for having a look

**Comment by Rapster** [comment]
@christophs78 I feel there is some duplicates in `CalendarUtils`. Do you think there is some stuff that I did in my last commit refactoring that could be reused?

**Comment by christophs78** [comment]
@Rapster I´ll look into this within the next weeks.
