### ISSUE TITLE
Tree: Wrong dropIndex in AJAX behavior event

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5015]
## 1) Environment
- PrimeFaces version: Trunk
- Application server + version: WF 10.1.0.Final
- Affected browsers: IE, FF, ...

## 2) Expected behavior
There are multiple possibilities, where a tree node could be dropped. Either **on** other nodes , which will make them siblings of that node. Or **between** nodes, which will insert the node at that position.

The second case (between) is working correctly. The `dropIndex` has the correct value. But the first case (on) should always either add the node at the beginning or at the end of the drop nodes child list. That means, that the `dropIndex` should either be `0` or `count of child-nodes`

## 3) Actual behavior
The `dropIndex` contains the index from inside the old parent node. This produces different results of the tree based on the child count of the drop node. If the drop node has enough children so that the `dropIndex` is in range, it will be inserted at the same index it previously had in the old parent node. Otherwise it will be appended to the end.

But the AJAX behaviour event will always report the original index, event if the node was appended instead of inserted. You have to manually adjust that value. That is not a good idea because you have to know the implementation logic of the tree renderer and that may change at any time which may cause bugs.

## 4) Steps to reproduce
 - Setup a tree with multple nodes and child nodes and an AJAX behavior event for drag'n'drop.
 - Move one node to an other one, the dropIndex of the event is always the index from inside the parent. Not from the drop node.

## 5) Sample XHTML
Will be provided if really needed

## 6) Sample bean
Will be povided if really needed

## 7) Possible fix
Always append the dragged node to end of the drop node children. For the correct index, change the line `dndIndex = targetDragNode.prevAll('li.ui-treenode').length;` to `dndIndex = dropNode.find('>.ui-treenode-children>li.ui-treenode').length;`

(the image contains some debug output, that could be ignored)
![PF Issue](https://user-images.githubusercontent.com/3531183/61696104-04fbe600-ad35-11e9-8f49-4ae2a3ca6b0b.png)

**Comment by fanste** [comment]
If you agree with my fix (we've already tested it internally and it seems to work as expected), than I will provde a PR.

**Comment by melloware** [comment]
Please provide PR.

**Comment by melloware** [comment]
Can you also check this one: https://github.com/primefaces/primefaces/issues/3543 to see if its the same issue.

**Comment by melloware** [comment]
PR Submitted. @fanste please review.

**Comment by fanste** [comment]
Sorry, I was on vacation and currently I'm busy with business related things :/
I will have a look at #3543 as soon as I have more time again.

Your PR looks good. Thank you.

**Comment by fanste** [comment]
My collegue just told me, that he included the fix of PR #4809 in our internal version which we used to find this issue. The PR seems to work (he exchanged includes with the jQuery function for IE11 compatibility). We never tried the PR of this issue without the PR #4809. We can do this in few days if it is what you want.

**Comment by melloware** [comment]
@fanste I just merged the other PR.  I tested everything in Chrome and IE11 can you please retest your scenarios.
