### ISSUE TITLE
SelectManyMenu: Basic selection regression issue

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5018]
## 1) Environment
- PrimeFaces version: 7.1-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub?NO
- Application server + version: Showcase
- Affected browsers: All

## 2) Expected behavior

Basic SelectManyMenu should only submit the value selected

## 3) Actual behavior

It is submitting any value or previous value selected

## 4) Steps to reproduce

Navigate to ShowCase: https://www.primefaces.org/showcase/ui/input/manyMenu.xhtml

Select Basic Option 1 and press Submit (only 1 is selected)

Select Basic Option 2 and press Submit (1 & 2 are selected as its remembering the previous selection)

This is a regression from the fix for #2089, I am submitting a PR to fix.

**Comment by tandraschko** [comment]
i assume it works fine in al browsers with your PR?

**Comment by melloware** [comment]
Tested in Chrome, Firefox, Edge, and IE11!

**Comment by tandraschko** [comment]
ok, feel free to apply it :D
