### ISSUE TITLE
Date Time picker and Time picker for Mobile

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#502]
It would be nice to have a time picker for PF Mobile, 
while using <p:calendar and  PRIMEFACES_MOBILE render kit, time is not rendered

Refer
http://forum.primefaces.org/viewtopic.php?f=3&t=20524
http://code.google.com/p/mobiscroll/

**Comment by tandraschko** [comment]
Already there: http://primefaces.org/showcase/mobile/calendar.xhtml

**Comment by tandraschko** [comment]
PrimeFaces Mobile will be deprecated  in 6.2 and removed in 6.3 ( see https://www.primefaces.org/primefaces-6-2-roadmap/)
Therefor i will close this issue as won't fix. If you will provide a PR to fix this issue until 6.2 RC1, i can merge it.
