### ISSUE TITLE
mobile: add panel (left,right), page, popup, column toggle from jquery-mobile

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#5020]
For mobile: please add some features from jquery-mobile:
1. panel (left,right),
2. page, popup, 
3. column toggle

**Comment by tandraschko** [comment]
you know that we removed PrimeFaces mobile?

**Comment by mertsincan** [comment]
Sorry, PrimeFaces no longer support it.

Best Regards,

**Comment by tandraschko** [comment]
@mertsincan i think you mean "PrimeFaces mobile"? :D

**Comment by mertsincan** [comment]
Yes, PrimeFaces mobile :D
