### ISSUE TITLE
ChartJS: Move renderers in org.primefaces.component.chartjs

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#5030]
Move chartjs renderers into `org.primefaces.component.chartjs`, so far it's spread all over `org.primefaces.component` which gets annoying, specially if you want an overview of the impls. jqplot charts follow that, so let's do the same for chartjs _(rename into chartjs also, and not charts)_

**Comment by tandraschko** [comment]
Currently the tags are name e.g. p:barChart, therefore org.primefaces.component.barchart.BarChartRenderer is the correct path

**Comment by Rapster** [comment]
They are individual components indeed (even though it shouldn't and I think it's a design mistake), but still, those different chartjs components should remain in one package instead of making `org.primefaces.component` congested. If I wanted to have a look on Chartjs code, I expect to be able to find all the infos in one place, not navigating all over our main component package to find it

**Comment by mertsincan** [comment]
I agree with Thomas ;)

**Comment by Rapster** [comment]
Well, I clearly don't! 😄 If if we had a `p:chartjs` I would agree, but PrimeTek decided to do something else. I'm curious why you didn't want to do just like `p:chart` with a model attribute, it would have simplify so many things, see all the duplicates we have now on these components [sonarcloud](https://sonarcloud.io/component_measures?id=org.primefaces%3Aprimefaces&metric=duplicated_lines_density&selected=org.primefaces%3Aprimefaces%3Asrc%2Fmain%2Fjava%2Forg%2Fprimefaces%2Fmodel%2Fcharts&view=list).

Anyway, even though they're defined as independant component they all are chartjs based component. I must say that sometimes I'm having a tough time to recognize new charts from the old ones (code speaking). So having them in a more accurate package is more relevant than having them in `org.primefaces.component`

**Comment by melloware** [comment]
So where did we end up on this ticket?  Can it be closed it sounds like @mertsincan and @tandraschko  are both -1 on it?

**Comment by Rapster** [comment]
Sadly, I guess it can be closed...
