### ISSUE TITLE
DatePicker: wrong DayNames when firstDay of Locale not equal 0

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5036]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? 7.0
- Application server + version: does not matter
- Affected browsers: does not matter

## 2) Expected behavior
For local "de" firstDay is 1. (=monday)
dayNamesMin and dayNames should be shown correct in DatePicker-popup.

## 3) Actual behavior
dayNamesMin ist shown correct. (recognices firstDay )
dayNames ist shown wrong. (does not recognice firstDay )
![grafik](https://user-images.githubusercontent.com/10461942/62106757-56acef00-b2a6-11e9-86ed-2465983f8346.png)
![grafik](https://user-images.githubusercontent.com/10461942/62106798-6f1d0980-b2a6-11e9-85cd-ac79c60ec615.png)

## 4) Steps to reproduce
`<p:datePicker id="geburtsdatum" locale="de"  pattern="dd.MM.yyyy" />`
And use de-local.js.
```
PrimeFaces.locales ['de'] = {
    closeText: 'Schließen',
    prevText: 'Voriges',
    nextText: 'Nächstes',
    monthNames: ['Jänner', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember' ],
    monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez' ],
    dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    dayNamesShort: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    dayNamesMin: ['S', 'M', 'D', 'M ', 'D', 'F ', 'S'],
    weekHeader: 'Woche',
    firstDay: 1,
```

Issue may be located within https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js.

**Comment by melloware** [comment]
Is it similar to this issue? https://github.com/primefaces/primefaces/issues/4973

**Comment by christophs78** [comment]
I saw #4973 before, but i think this are two different issues.

**Comment by christophs78** [comment]
DatePicker in this case recognizes the de-Locale (Sonntag instead of Sunday, ....) and shows the popup. 
But it does not seem to recognize firstDay when he renders dayNames .

**Comment by melloware** [comment]
Got it.
