### ISSUE TITLE
p:dataTable: ColumnToggler does not work with lazy loading

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#5042]
## 1) Environment
- PrimeFaces version: 7.0.5

- Application server + version: Wildfly 15
- Affected browsers: All

## 2) Expected behavior
When hiding columns via the **p:columnToggler**, I expect, that the hidden columns are considered with lazy loading and virtualScroll as well. Instead, the headers of the hidden columns will stay hidden when scrolling, but the newly loaded data rows, will contain the hidden columns data, which corrupts the table layout.

## 4) Steps to reproduce
See attached zip file with relevant Code,
1. Open table
2. Hide some columns (e.g. ID)
3. Scroll down until new data is being loaded from the server.
4. Check the table layout -> for the hidden columns, the headers are still hidden, but the data rows contain data which lead to misalignment in header and data cols.

Screenshots:
a) Table before hiding columns
![grafik](https://user-images.githubusercontent.com/47218021/62278319-1b4a2600-b448-11e9-9e5e-5921e1bf0856.png)

b) Table after hiding  column 'ID' (Use button **Columns** in the table header on the right)
![grafik](https://user-images.githubusercontent.com/47218021/62278401-4cc2f180-b448-11e9-811c-06f343ef1a2d.png)

Everything looks fins, Column was hidden.

c) Scroll down until data is being loaded from the server
![grafik](https://user-images.githubusercontent.com/47218021/62278606-b80cc380-b448-11e9-8a64-cb0f0dd8b6b4.png)

## 5) Sample

[PF_ticket3.zip](https://github.com/primefaces/primefaces/files/3455716/PF_ticket3.zip)

**Comment by tandraschko** [comment]
I don't want to sell something but you already created 4 datatable issues the last weeks.
If you would like to get a fix the next weeks/months, i really suggest to use PrimeFaces PRO.

**Comment by wlhUser** [comment]
Thanks for the offer. 
I started using the p:datatable some weeks ago, and as I found some problems, I thought you might want to get informed, in order to improve the functionality for the community. Up to now I do not see the need to use PrimeFaces PRO, as the problems I found are not blocking, but maybe it is an option for the future.

**Comment by mikereem** [comment]
I had the same issue and found ticket https://github.com/primefaces/primefaces/issues/96 where the solution (workaround) was working for this one too. See: https://www.primefaces.org/stateful-column-toggler/

**Comment by melloware** [comment]
Thanks @mikereem I will close this ticket thanks for providing a solution.
