### ISSUE TITLE
Remove java.util.Date fallbacks

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5043]
user can still attach their own JSF convert for a calendar/Datepicker of course

**Comment by tandraschko** [comment]
@christophs78 WDYT? shall we do it or wait until the old classes are deprecated in java itself?

**Comment by melloware** [comment]
My personal preference would be wait until the are deprecated in the JDK or at worst at least one more major PF revision of 9.0.

**Comment by christophs78** [comment]
Yep. We should wait.

**Comment by stolp** [comment]
Speaking from the pure consumer side I would also appreciate that the support for java.util.Date stays in as long as possible. Some apps have a long legacy to look back on.
