### ISSUE TITLE
PrimeFaces.ajax.Response.handleReFocus focuses wrong input if user moves focus after setTimeout called

### ISSUE THREAD

**Issue by bravocharlie** [primefaces/primefaces#505]
The `handleReFocus` method uses setTimeout to recheck focus was set (it is commented as required for IE but is called with any browser).  Once this timeout is set, if the user moves focus to a new element before the timeout expires, the focus will be moved back to the element that was focused previously.  Whilst this is a small window of opportunity (currently 150ms), it is sufficiently long enough to be a real problem for keyboard warriors.

This can be solved by adding a handler to check for focus changes whilst the timeout elapses, and in the timeout callback, use this value in preference of `activeElementId` - something along the lines of

``` javascript
$(document).on("focus", ":input", function(){
        var focusId = $(this).attr('id');
        if (focusId && PrimeFaces.ajax.Response.isInReFocusTimeout){
            PrimeFaces.ajax.Response.overrideReFocusId = focusId;
        }
    });
```

My implementation is not currently good enough quality for a patch, sorry.

**Comment by tandraschko** [comment]
Can you please describe your idea to fix the problem a little bit more detailed?
I don't think we have a easy to way to check if we have to refocus or not.
Maybe we can decrease the timeout to e.g. 50ms but we must test it on older computers with IE8.

**Comment by bravocharlie** [comment]
Sure - my method has a global flag which is set to true after setTimeout in
handleReFocus is called.

A handler it is attached to document to monitor focus events on all inputs.
When an item is focused and the global flag is true (timeout has been
called) we store the id of this element in another global variable.

When the timeout callback executes, it checks to see if an another element
id has been set, and use this in preference of activeElementId.  Finally
set global flag to false.

It might be more correct to use a counter rather than a boolean flag to
account for multiple concurrent setTimeouts..

Hope that is clearer.  Your suggestion for reducing timeout may also work :)

Thanks
Ben

**Comment by tandraschko** [comment]
i reduced it to 50ms. Could you please give it a try?
