### ISSUE TITLE
DataTable: lazy DataTable with virtual scrolling skips rows and shows wrong expansions

### ISSUE THREAD

**Issue by Foobartender** [primefaces/primefaces#5051]
## 1) Environment
- PrimeFaces version: 7.0.5
- Does it work on the newest released PrimeFaces version? No.
- Does it work on the newest sources in GitHub? Did not try.
- Application server + version: latest Payara
- Affected browsers: any

## 2) Expected behavior
Lazy DataTable with virtual scrolling and row expansions shows correct rows and corresponding row expansions.

## 3) Actual behavior
When row 2*scrollRows comes into view, rows are skipped. When the index of the first row loaded is an odd multiple of scrollRows, the wrong row expansion is displayed.

## 4) Steps to reproduce
Run the provided test project (see comment below).

**Comment by Foobartender** [comment]
Looking for a workaround, I figured that it's not that simple, because setRowIndex() is usually called with values from 0..pageSize-1. Except on row expansion (and maybe inline edits?), then it's called with the actual row index. So it's easy to workaround for values >= pageSize, but tricky for values < pageSize. Luckily, on row expansion the setRowIndex() call is preceded with `setRowIndex(-1)`, so the following workaround works for me. Values < pageSize/2 can be and effectively are left unchanged.

```java
public abstract class LazyDataModelWorkaround<T> extends LazyDataModel<T> {
 protected abstract int getFirst();


 @Override
 public void setRowIndex(int rowIndex) {
  if (getPageSize()!=0 && getRowIndex()==-1 && rowIndex>=getFirst()) rowIndex-=getFirst();
  super.setRowIndex(rowIndex);
 }
}
```

**Comment by Rapster** [comment]
1. Please follow issue template
1. Provide a reproducer using primefaces-test
1. Since you already made an analysis, please provide a PR :wink:

**Comment by Foobartender** [comment]
[primefaces-test-5051.tar.gz](https://github.com/primefaces/primefaces/files/3482889/primefaces-test-5051.tar.gz)

Just scroll down until row 100 comes into view. Issues appear depending on range.

**Comment by 123MarkA321** [comment]
This problem exists in PF 8.0 too.
[https://forum.primefaces.org/viewtopic.php?f=3&t=62004](https://forum.primefaces.org/viewtopic.php?f=3&t=62004)

**Comment by melloware** [comment]
Updated reproducer for PF 8.0:
[pf-5051.zip](https://github.com/primefaces/primefaces/files/5755328/pf-5051.zip)

**Comment by 123MarkA321** [comment]
Start the view and scroll down:
<img width="162" alt="2021-01-02 11_56_41" src="https://user-images.githubusercontent.com/64163092/103455947-cae88f00-4cf1-11eb-9106-b51d2dd7efa3.png">

Now hide and show the expandedRow:
<img width="72" alt="2021-01-02 11_56_57" src="https://user-images.githubusercontent.com/64163092/103455945-ca4ff880-4cf1-11eb-9ac0-94ada8de3733.png">
We see now 199 and not 149.

We click of the commandButton and the Item 199 is selected too.
<img width="111" alt="2021-01-02 11_56_49" src="https://user-images.githubusercontent.com/64163092/103455946-ca4ff880-4cf1-11eb-9e2a-bdf2e08cffa5.png">
<img width="290" alt="2021-01-02 11_57_08 " src="https://user-images.githubusercontent.com/64163092/103455944-c9b76200-4cf1-11eb-9c7b-940f59b924d7.png">

I think all events must remember their index in JS event for select correct object in DataTable (in this case data-ri="149" from tr tag)
<img width="1210" alt="2021-01-02 12_03_15-DevTools" src="https://user-images.githubusercontent.com/64163092/103456030-96c19e00-4cf2-11eb-948c-2be5318d91ec.png">

**Comment by melloware** [comment]
@123MarkA321 I didn't dig into why I just wanted to make sure we had a reproducer for 8.0 and prove the issue.  Yep its definitely a bug just didn't investigate a fix yet.  If you want to help PR's are welcome!

**Comment by 123MarkA321** [comment]
I have a workaround for the liveScroll=true (not virtualScroll). This changes is in class Model in test  reproducer
```java
private final List<Item> completeData = new ArrayList<>();
private int currentRowIndex = 0;

@Override
  public List<Item> load(final int first, final int pageSize, final Map<String, SortMeta> sortBy, final Map<String, FilterMeta> filterBy) {
    final ArrayList<Item> r = new ArrayList<>(pageSize);
    for (int i = first; i < first + pageSize && i < ROW_COUNT; i++) {
      final Item currentItem = new Item(Integer.valueOf(i));
      r.add(currentItem);
      //add current item in completeData list
      if (isRowAvailable()) {
        completeData.add(currentItem);
      }
    }
    return r;
  }

  //Override for get row from completeData list with current rowIndex
  @Override
  public Item getRowData() {
    if (currentRowIndex == -1) {
      return super.getRowData();
    } else {
      return completeData.get(currentRowIndex);
    }
  }

  // Override for set current rowIndex for current line (in this case row 149)
  @Override
  public void setRowIndex(final int rowIndex) {
    currentRowIndex = rowIndex;
    super.setRowIndex(rowIndex);
  }
```

Here the result:
<img width="156" alt="2021-01-02 23_53_13" src="https://user-images.githubusercontent.com/64163092/103468165-bd192500-4d56-11eb-8ea3-61dca848cb44.png">
<img width="280" alt="2021-01-02 23_53_41" src="https://user-images.githubusercontent.com/64163092/103468224-21d47f80-4d57-11eb-9ea9-063393f0e4ca.png">

I hope this helps for fix this in origin code

**Comment by melloware** [comment]
reproducer for 11.0.0 that its still a bug: 
[pf-5051-PF11.zip](https://github.com/primefaces/primefaces/files/7072582/pf-5051-PF11.zip)
