### ISSUE TITLE
Core: Refactor Exporter - Part 1

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#5053]
Recently I had a deeper look on newly introduced `Exporter` interface, and to me that kinda of definition is wrong:
```java
public interface Exporter<T extends UIComponent> {

    void export(FacesContext facesContext, T component,
            String outputFileName, boolean pageOnly, boolean selectionOnly,
            String encodingType, MethodExpression preProcessor,
            MethodExpression postProcessor, ExporterOptions options, MethodExpression onTableRender) throws IOException;

    void export(FacesContext facesContext, List<String> clientIds,
            String outputFileName, boolean pageOnly, boolean selectionOnly,
            String encodingType, MethodExpression preProcessor,
            MethodExpression postProcessor, ExporterOptions options, MethodExpression onTableRender) throws IOException;

    void export(FacesContext facesContext,
            String outputFileName, List<T> components, boolean pageOnly, boolean selectionOnly,
            String encodingType, MethodExpression preProcessor,
            MethodExpression postProcessor, ExporterOptions options, MethodExpression onTableRender) throws IOException;

}
```

1. 3 methods that does 99% the same thing
1. methods having 10 parameters

As a result, there is a lot of duplicates (recently sonarcloud complained about it) which makes it even tougher to read the code.

I think there is a need to be able to export a datable inside an iterator component such as `ui:repeat`, the reason why we have these `xxxExportVisitCallback`. But IMO, we should be able to solve this more simply.

PR on his way

**Comment by tandraschko** [comment]
@Rapster ExportConfiguration produces warnings in the maven build
it's also a mix between pojo and builder
what about making it a normal POJO and create a Builder subclass?

**Comment by Rapster** [comment]
Yeah I forgot to put `private` keywords. It's not really a mix, it's a chain method pattern. I guess I could use a pattern builder, I just made it quick. I'll do that asap
