### ISSUE TITLE
[Documentation] Improve on copied classes from JSF impls

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#5059]
We have different component in PF that are a copy of, either MyFaces or Mojarra. But it doesn't say:
- from which version it has been copied? Should we keep them updated?
- what does it fix?
- any custom code?

We have:
- `org.primefaces.component.api.UIData`
- `org.primefaces.model.IterableDataModel`
- `org.primefaces.component.repeat.UIRepeat`
- `org.primefaces.component.repeat.IterationStatus`
- `org.primefaces.component.api.UITabPanel`

IMO, javadoc & doc should be provided, also are these fixes still necessary today?

**Comment by tandraschko** [comment]
p:repeat is a hacky bugfix for mojarra and still necessary as long as the Implementation doesnt Change. Also see: https://download.oracle.com/javaee-archive/javaserverfaces-spec-public.java.net/jsr372-experts/2016/01/0926.html

**Comment by Rapster** [comment]
I see, sounds like a tough one and does not seem it's gonna be fixed anytime soon. So basically, `UIRepeat#isNestedWithinIteator` is the only method that need to be fixed?

**Comment by tandraschko** [comment]
Exactly
I think we have to talk with the mojarra Team, If they can add suppport some class name patterns or reimplement it on their side

**Comment by tandraschko** [comment]
Or Check why UiTabPanel is no UiData

**Comment by Rapster** [comment]
Why don't we just use UIRepeat from MyFaces for `p:repeat`?

**Comment by tandraschko** [comment]
Because we should get rid of p:repeat and Not fix mojarra bugs

**Comment by Rapster** [comment]
No that I know, but meantime Mojarra fix that issue. Why don't we simply reuse UIRepeat from MyFaces, it doesn't seem to have any isNestedWithinIterator method in this class

**Comment by tandraschko** [comment]
May be possible but we should then also change our UIData impl....

**Comment by Rapster** [comment]
Can we then use `UIData` from MyFaces also? Might sound stupid question, but hard to understand the history of this issue. Is it possible to reproduce the issue using `ui:repeat` on the showcase?

**Comment by tandraschko** [comment]
Probably
But our goal should be to not change this classes for now and motivate the mojarra team to change their Implementation, to not require the nested iterator thing anymore

**Comment by tandraschko** [comment]
So please also revert this change in your PR
If you have time, it would be great If you can try to contribute to mojarra

**Comment by Rapster** [comment]
I found an issue that I can try on to test (see https://github.com/eclipse-ee4j/mojarra/issues/4535) which should be the reason why `p:repeat` has been introduced. In 2.3.2, the problem is not reproduced (I just tried)

**Comment by tandraschko** [comment]
If the example contains nesting of a repeating UiTabPanel inside/Outside of ui:repeat, it could be the same

**Comment by tandraschko** [comment]
See https://code.google.com/archive/p/primefaces/issues/7190

**Comment by Rapster** [comment]
In case we need to update copied classes (and I think we must do it), here is the scenario to make sure everything works fine:

```xml
<h:form id="form">
    <p:accordionPanel value="#{tabbedView.cars}" var="car">
        <p:tab title="Car - #{car.id}">
            <ui:repeat value="#{[1,2,3,4]}" var="cls">
                <p:message for="@next" />
                <h:inputText required="true"/>
            </ui:repeat>
        </p:tab>
    </p:accordionPanel>
    <h:commandButton value="test"  />
</h:form>
```

- Not working with Mojarra 2.3.3
- Working if using p:repeat
- Working with MyFaces 2.3.4 (using `ui:repeat`)

**Comment by Rapster** [comment]
I don't plan to change `UIData#isNestedWithinIterator` since:
- it's our custom implementation
- we should probably update `UIData` with a more updated version (from MyFaces/Mojarra?)
- even though Mojarra fixes it, since PF support 2.2 we should fix this 
- on the long run, we actually might not need it (looking at MyFaces code)

I'll provide a PR "simplifying" a lot `UITabPanel` and a more updated version of `UIRepeat`

I could contribute to Mojarra or MyFaces, but I honestly don't where to start...

**Comment by tandraschko** [comment]
really, i would like to leave this classes as they are for now - they are copied, it's ok for now

we have so many bugs and enhancement requests, i think we should put in some effort there
i know, developers are more into refactoring and performance improvements...

Whenever you don't like something in MyFaces, create issues and PRs (but note: all branches are in maintanence mode, just master is open for refactoring).

About Mojarra.... There are some issues of PrimeFaces users in Mojarra since months/years. I think it would be good if you could contribute there, the JSF impls is the heart of PrimeFaces.

https://github.com/eclipse-ee4j/mojarra/issues/4553
https://github.com/eclipse-ee4j/mojarra/issues/4262 (simple IF-statement if you compare with MyFaces)
https://github.com/eclipse-ee4j/mojarra/issues/4265

**Comment by melloware** [comment]
@Rapster So what are we doing about this? If nothing we should close it.

If we are just updating JavaDoc headers to explain where the classes were copied from?

**Comment by Rapster** [comment]
Right now, let's not touch it. It's not an easy topic since these classes has been copied and modified (without knowing exactly what has been modified and from where...) Using latest impls fix most the cases but I managed to reproduce a bug using the above sample. I don't think it's only a matter of doc but also code. To be continued

**Comment by tandraschko** [comment]
enhanced the docs for now.
I would like to get rid of p:repeat but thats up to Mojarra.
