### ISSUE TITLE
p:fileUpload handles files with semicolon in name improperly

### ISSUE THREAD

**Issue by tomi213** [primefaces/primefaces#506]
If I try to upload a file that contains semicolon in the name the file name, the file name gets clipped. 
Eg. file "my.exe;image.jpg" is renamed to "my.exe". This allows the person that is uploading the file to bypass allowTypes feature and potentially upload files with any extension.

File name is shown correctly on the web page before upload, but when I push the file name to p:growl from the backing bean the name gets clipped.

I used following libraries:
primefaces-5.2.jar
javax.servlet-api-3.0.1.jar
jsf-api-2.2.10.jar
jsf-impl-2.2.10.jar

JDK 1.8
Apache Tomcat 8.0.15.0

fragment from xhtml file:

```
 <h:form enctype="multipart/form-data">
            <p:growl id="messages" showDetail="true" />
            <p:fileUpload value="#{uploadBean.file}" mode="simple" skinSimple="true" 
                   allowTypes="/(\.|\/)(gif|jpe?g|png)$/"/>
            <p:commandButton value="Submit" ajax="false" 
                   actionListener="#{uploadBean.uploadOne()}"/>
 </h:form>
```

UploadBean.java:

```
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import org.primefaces.model.UploadedFile;

@ManagedBean
public class UploadBean {
    UploadedFile file;
    public UploadedFile getFile() { 
           return file; 
   }
   public void setFile(UploadedFile file) { 
        this.file = file;
   }

    public void uploadOne() {
        if(file != null) {
            FacesMessage message = new FacesMessage("Succesful", file.getFileName() + 
                    " is uploaded.");
            FacesContext.getCurrentInstance().addMessage(null, message);
           //...
        }
    }
}
```

**Comment by melloware** [comment]
relates to https://github.com/primefaces/primefaces/issues/3034

**Comment by jxmai** [comment]
> Eg. file "my.exe;image.jpg" is renamed to "my.exe". This allows the person that is uploading the file to bypass allowTypes feature and potentially upload files with any extension.

Wow, this is a really good point. PR: #3036
