### ISSUE TITLE
DatePicker: No timeInput attribute like Calendar

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#5060]
## 1) Environment
- PrimeFaces version: 6.2.21
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Payara 5.192
- Affected browsers: All

## 2) Expected behavior

Datepicker should have timeInput attribute to enter time/date manually like with calendar.

## 3) Actual behavior

There is no obvios way in actual API to get this 

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by markusg80** [comment]
Any news regarding this issue? It is really important feature for us to change from Calendar to Datepicker component

**Comment by tandraschko** [comment]
Not really :D
Feel free to provide a PR or sponsor it via PrimeFaces PRO!

**Comment by markusg80** [comment]
Is there really no one else with the need to enter the time with Keyboard? It can be very boring to enter time value with mouse controls. To submit a pr i dont have the time st this moment and my company dont have any intension to spend money for one festure.

**Comment by melloware** [comment]
There probably are others out there that need this feature but it will only get fixed if someone in the community submits a PR or sponsors it via PRO.  if your company doesn't want to then you will just have to wait and rely on others.

**Comment by markusg80** [comment]
And why Primefaces has no intensions to add features to his components many people asking for. It is always an advantage for Primefaces to have useful features for the components! I think its not so a big effort for experienced programmer to implement this. I doesn‘t have experience in creating web components. so for me it will be a big effort to implement feature in a Webcomponent and to ensure to respect all Primefaces guidelines.

**Comment by melloware** [comment]
I don’t disagree. I am just telling you your options for making it happen.

**Comment by christophs78** [comment]
@markusg80 
Most of us do this work in our spare time for free. (As it´s the same with a good amount of other open source projects. There are some "big ones" which are sponsored. This means there´s a company behind which pays some developers. But for PrimeFaces at this point in time maybe 80% of the work is done by the "community" for free.)

Calendar has the following UI for date + time:
![grafik](https://user-images.githubusercontent.com/10461942/69898028-ff9e5000-1353-11ea-931c-43d6b234cc82.png)

DatePicker the following:
![grafik](https://user-images.githubusercontent.com/10461942/69898035-147ae380-1354-11ea-9827-6934b9c9308a.png)

Calendar comes OOTB with a time (Zeit) - input which is disabled by default. (You "unlock" it with the timeInput - attribute.) 
What do you expect from the DatePicker-UI? Should we build separat input´s for hour, minute and (optional) second?

**Comment by markusg80** [comment]
First thank you for your time. I know how open source software works. And i think its really good. So for me the main Problem is time and I’m absolutely without experience to develop Primefaces Components.

So to your question: 
Should we build separat input´s for hour, minute and (optional) second?
Yes this is exactly what i expected 😉

**Comment by markusg80** [comment]
Can you please merge this also to 7 branch? We still nit some time to migrate to Primefaces 8 because there are many breaking changes

**Comment by markusg80** [comment]
Can you please also merge this to 8.0 elite versions? We really waiting for this feature and i'm at the moment on migrating our project to 8.0 for this. Please. Please. Please.

**Comment by tandraschko** [comment]
as always, this is up to @mertsincan ; the community cant touch elite releases

**Comment by markusg80** [comment]
@mertsincan Can you please merge this to 8 Elite release. At the minent i take the effort to migrate my project to pf8. So then i like to change from Calendar to Datepicker. I think to merge this will not break anything for existing code for other Primefaces users. Next you can make experience with this Feature for the upcoming 9.0 Release.
