### ISSUE TITLE
Dialog does not close in Chrome on touch devices

### ISSUE THREAD

**Issue by RalfScania** [primefaces/primefaces#5061]
**Environment**
PrimeFaces version: 7.0.5
Did work on 6.X

Affected browsers: Chrome Mobile
Tested on Samsung TabActive and S10

**Expected behavior**
Dialog should close on touch off the close icon in the top right panel

**Actual behavior**
Dialog does not close

**Steps to reproduce**
[primefaces-test-dialog.zip](https://github.com/primefaces/primefaces/files/3491654/primefaces-test-dialog.zip)

**Sample XHTML**
```
<h:body>
        <p:commandButton value="Basic" type="button" onclick="PF('dlg1').show();" />
        <p:dialog header="Basic Dialog" widgetVar="dlg1" minHeight="40">
            <h:outputText value="Resistance to PrimeFaces is futile!" />
        </p:dialog>
</h:body>


```

**Comment by melloware** [comment]
Is the only way to test with the physical hardware?  I don't really see anything out of the ordinary with the close icon code.

https://github.com/primefaces/primefaces/blob/039f5d75c614914fb532e536c6acf8bcf2105850/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js#L237-L240

**Comment by RalfScania** [comment]
If you use the virtual device in chrome, it works.
It only happens if you use a touch device on android.

By the way, ConfirmDialog works.

**Comment by lagar84** [comment]
I had a similar issue, just reproducible on physical hardware.
I workarounded it by setting draggable="false" (default is true). 
It looks like dialog was confusing the touch to close with touch to drag. 
Try it to see if it is the same issue.

**Comment by RalfScania** [comment]
Yes, if you set draggable to false, it works.

**Comment by melloware** [comment]
OK this appears to be a problem with Jquery UI Touch.  https://github.com/furf/jquery-ui-touch-punch/issues/295

I will handle fixing it.
