### ISSUE TITLE
SelectCheckboxMenu: Disabling a SelectItem does nothing

### ISSUE THREAD

**Issue by theobisproject** [primefaces/primefaces#5063]
## 1) Environment
- PrimeFaces version: `7.0`
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) `No`
- Application server + version: `Wildfly 13`
- Affected browsers: `Firefox`, `Chrome`, `Edge`

## 2) Expected behavior
The checkbox get's disabled when the Bean sets the disabled attribute of the SelectItem to `true`.

## 3) Actual behavior
Disabling the SelectItem has no visible effect.
When I add the `ui-state-disabled` class to the checkbox the checkbox changes as expected.
It seems like the change in the bean does not trigger the css class to be added to the element.

## 4) Steps to reproduce
Test project can be found at https://github.com/theobisproject/primefaces-test on the `selectItem-disable` branch

**Comment by melloware** [comment]
Thanks for your test case it helped me debug the issue.  PR submitted.
