### ISSUE TITLE
Datatable: Partial rendering of datatable with stickyHeader="true" and stickyTopAt="..." increases z-index of div

### ISSUE THREAD

**Issue by dgusoft** [primefaces/primefaces#5064]
## 1) Environment
- PrimeFaces version: 7.0.2
- Application server + version: JBoss EAP 7.0.7.GA (Mojarra 2.2.12.SP4)
- Affected browsers: all
-  example with existing serenity theme showcase 

## 2) Expected behavior
Partial rendering of datatable with sticky table header should keep z-index stable
## 3) Actual behavior
z-index of div-Element above table-element increases with each ajax request which causes the datatable to be partially rendered.
example in our application:
before partial rendering:
<pre>
&lt;div class="ui-datatable ui-datatable-sticky ui-widget ui-shadow ui-sticky" style="position: fixed; width: 1629px; top: 0px; left: 17px; z-index: 1001;"&gt;
</pre>
after partial rendering
<pre>
&lt;div class="ui-datatable ui-datatable-sticky ui-widget ui-shadow ui-sticky" style="position: fixed; width: 1629px; top: 0px; left: 17px; z-index: 1003;"&gt;
</pre>

This behaviour leads to the effect that the drop downs of the primefaces menubar appear under the sticky table header after some partial renderings.

## 4) Steps to reproduce
Put a p:datatable on a sample page and a commandbutton which causes the datatable to rerender on ajax request.
## 5) Sample XHTML
...
<pre>
&lt;div class="ui-sticky"&gt;&lt;/div&gt;
&lt;p:dataTable id="id" var="item" value="#{controller.list}"
            	      stickyHeader="true" stickyTopAt=".ui-sticky"
                      rowSelectMode="checkbox" 
                      selection="#{controller.selectedRows}" rowKey="#{item.id}"&gt;
...
</p:dataTable>
</pre>
...

## 6) Cause
This part of the setupStickyHeader-function of datatable.js is responsible for the increasing z-index:
<pre>
        this.stickyContainer.css({
            position: "absolute",
            width: d.outerWidth(),
            top: g.top,
            left: g.left,
            "z-index": ++PrimeFaces.zindex
        });
</pre>
By the way: It is not the only code fragment where "++PrimeFaces.zindex" is found in the primefaces-javascript. In my oppinion this sort of dynamic increase of the zindex auf html-Elements leads to a lot of issues.

**Comment by dgusoft** [comment]
To reproduce: Put the file sticky-header.xhtml into the showcase (main Folder) and open the page sticky-header.xhtml within the showcase url in a browser (f. ex. chrome) [http://localhost:9090/serentity/sticky-header.xhtml]
[sticky-header.zip](https://github.com/primefaces/primefaces/files/3500325/sticky-header.zip)
see also the screenshots:
![screen2](https://user-images.githubusercontent.com/18658082/63004241-340c0000-be7a-11e9-8fb5-33728a5e0d9a.png)
![screen1](https://user-images.githubusercontent.com/18658082/63004242-340c0000-be7a-11e9-856c-2453d326c51b.png)
z-index starts by 1001 and get increased by one with every partial update (button click)

**Comment by melloware** [comment]
I am assuming PF did the zindez++ to solve some problem.  Do you have a proposed solution?

**Comment by dgusoft** [comment]
Not at the moment. It would interesting to know what problem was solved by using ++PrimeFaces.zindex. In the ressource loaded als components.js.jsf?ln=primefaces&v=7.0.2 I found 31 places where ++PrimeFaces.zindex is used.
I think the problem is that the same code is executed on full page reload and on partial update.

**Comment by ChrisRescher** [comment]
@melloware: 
Maybe the problem came in  with primefaces 7.x and the new dataTable attribute  **_stickyTopAt_** 
At the other hand, i don't know how to use stickyHeader without that "anchor" attribute - so stickyTopAt was longtime expected by community.

As @dgusoft  mentioned, the ++PrimeFaces.zindex, should not executed on partial requests

**Comment by melloware** [comment]
OK so we need some way to detect a partial update vs page load.  Maybe @tandraschko can weigh in if we have needed to do this elsewhere.  Because right now all widgets just reinitialize when they are partially updated.

**Comment by melloware** [comment]
PR Submitted please review.

**Comment by dgusoft** [comment]
Is there any possibility to test your changes? What would I have to download where?

**Comment by melloware** [comment]
If you are good at Git you chould checkout master and then merge this commit set PR into your branch: https://github.com/melloware/primefaces/commit/5ec5fb7a01c6de85f83ca642a6dcd0d2a5bb47de

**Comment by schlagges** [comment]
The StickyToolbar does quite the same. It increases the z-index each time you scroll down and back to top. Starting from 1002. That leads to an overlayed Navigation and so on.
