### ISSUE TITLE
fileUpload: multiple file layout overflows component

### ISSUE THREAD

**Issue by philwilkinson** [primefaces/primefaces#5066]
The contents of the primefaces fileUpload component expand\overflow past its boundary when uploading multiple files.

[This issue can be seen on the primefaces showcase page for fileupload](https://www.primefaces.org/showcase/ui/file/upload/multiple.xhtml) ...
![primefaces-showcase-fileUpload-overflow-bug](https://user-images.githubusercontent.com/8225012/63020622-83602980-be96-11e9-8979-67d789a6676a.png)
.. which I assume is using the latest version of primefaces.
It's quite subtle there, but the delete buttons are outside of the component, as would be the progress bar if I made the page width less.

It's more obvious in the app I am developing, where the space is more restricted.
![primefaces-6-2-fileUpload-overflow-bug](https://user-images.githubusercontent.com/8225012/63020861-21ec8a80-be97-11e9-87c9-a1ffb6c2f695.png)
This is with primefaces 6.2

To repeat try to upload files with long(ish) names as illustrated, that seems to trip it up.

There is a closed ticket for this overflow, #325 and that is linked to the enhancement ticket #2226 to add responsive layout to fileUpload.  That says that it was fixed in 6.1.RC3

**Comment by melloware** [comment]
Can you debug in and see what CSS is being applied?  I am wondering if this is something being overridden in the Premium Themes.

**Comment by philwilkinson** [comment]
Hi, I am not using any premium themes. And the issue is repeatable on the primefaces showcase page, for which I have not used any premium themes either. 
Just create an empty file with a longish name, e.g.
"encoded_20190215062434.gif"
content doesn't matter for this, just ensure the extension is .gif, as that's what it can upload.
goto https://www.primefaces.org/showcase/ui/file/upload/multiple.xhtml and upload it. resize page until it goes wrong - you will see the issue as captured with my 1st screenshot.

**Comment by melloware** [comment]
The PF Showcase is a Premium theme by default it uses "nova-light" by default.  But thanks for reporting that its not one of the newer themes.  Can you tell me exactly what theme you are using?

**Comment by philwilkinson** [comment]
Hi, I am using the omega theme from org.primefaces.themes:all-themes:1.0.10 on primefaces 6.2. However I don't think the theme is the issue as I can repeat the problem on the PF showcase page with the nova*, luna* and omega free themes.
