### ISSUE TITLE
Tree: Change/Improve contextmenu handling

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5069]
## 1) Environment
- PrimeFaces version: trunk
- Affected browsers: all

## 2) Expected behavior
A tree with an `p:contextmenu` should be able to use the selected tree node to determine the available actions of the context menu.

## 3) Actual behavior
The tree node selection and display of the context menu takes place simultaneously. Therefore the context menu will be closed again if you perform an update of the context menu.
The display of the context menu should be delayed to the `oncomplete` of the `contextMenu` behavior.

That would make it to a real **context** menu.

## 4) Steps to reproduce
 - Setup a tree with a context menu and a `contextMenu` behavior event.
 - The behavior event performs an update on the context menu to display menu items that are relevant for the selected tree node.
 - Right click a tree node
 - The context menu will show for a very short amount of time and is instantly closed again by the update

There are quite a lot of hacks in the internet, including the PF forum (e.g. [here for datatable](https://forum.primefaces.org/viewtopic.php?t=41973#top)). Why not make the hack to a real feature?

PR is coming, already tested in our internal PF version

**Comment by fanste** [comment]
PR #5070

**Comment by melloware** [comment]
Thanks for the PR!

**Comment by melloware** [comment]
@fanste couldnt this same fix be applied for the datatable as well?  https://github.com/primefaces/primefaces/issues/4448

**Comment by fanste** [comment]
I have to test it once I have a bit more time again. But I can't see why not.
