### ISSUE TITLE
InputTextarea: autocomplete function does not trigger itemSelect AJAX behavior event.

### ISSUE THREAD

**Issue by Selaron** [primefaces/primefaces#5071]
## 1) Environment

PF 7.0 + 7.1-SNAPSHOT
Mojarra 2.3
OpenWebBeans
Tomcat 9

## 2) Expected behavior

When using inputTextarea with autocomplete and adding a p:ajax event="itemSelect", the itemSelect event should be triggered by the user selecting a suggested item.

## 3) Actual behavior

The event simply does not trigger.

## 4) Steps to reproduce

Select a suggestion from inputTestarea and (don't) wait for the ajax lister to get called.

## 5) Sample XHTML

```xml
<h:form>
	<p:inputTextarea widgetVar="textarea" completeMethod="#{myBean.autoCompleteString}" >
		<p:ajax event="itemSelect" listener="#{myBean.onSelectItem}" />
	</p:inputTextarea>
</h:form>
```

## 6) Sample bean

```java
@Named
@ViewScoped
public class MyBean {
public List<String> autoCompleteString(final String filter) {
		final List<String> result = new ArrayList<>();
		for (int i = 0; i < 30; i++) {
			result.add(filter + i);
		}
		return result;
	}

	public void onSelectItem(SelectEvent<String> event) {
		final int i = 8;
	}
}
```

**Comment by Selaron** [comment]
Would like to add a pull request if you are not already on it.

Root cause short: InputTextareaRenderer . encodeScript() does not encodeClientBehaviors().

**Comment by melloware** [comment]
Please do I will review it when you submit.

**Comment by Selaron** [comment]
This issue came up in a recent [question on StackOverflow.com](https://stackoverflow.com/questions/57500617/does-inputtextarea-trigger-any-event-after-a-suggestion-is-clicked).

**Comment by melloware** [comment]
Thank for the PR!
