### ISSUE TITLE
Link and CommandLink: Add icon property

### ISSUE THREAD

**Issue by hfluz** [primefaces/primefaces#5076]
I propose that the property `icon` be added to Link and CommandLink components.

If icon is set, `<i class="fa fa-[icon]"></i>` is inserted inside `<a>` tag.

I can make a PR with this change, I just would like to know if it could be accepted or if there is any consideration.

**Comment by melloware** [comment]
Why not just do it like this: https://github.com/primefaces/primefaces/issues/3873

Another consideration would the icon be before or after the link?  I have a feeling PrimeTek will want to keep these pure links to match and HTML link.

So my vote would be -1

**Comment by hfluz** [comment]
The main reason is because I think the code gets cleaner.

Comparison:
```
<p:commandLink value="p:commandLink">
    <i class="fa fa-chevron-circle-up"/>
</p:commandLink>
```

```
<p:commandLink value="p:commandLink" icon="fa fa-chevron-circle-up"/>
```

I already have a fork of Primefaces with this and some other changes, but I want to avoid having to resolve conflicts after every release. So I'm trying to send upstream all the possible changes and create new components inheriting Primefaces ones if it can't be upstreamed.

In this case, I have developed my own responsive menu component and I use the [Link|CommandLink].icon property to display the icon to the left side.

The consideration about the side which the icon should be rendered doesn't also apply to Button and CommandButton, which have the icon property?

**Comment by tandraschko** [comment]
-0.5 as well

commandButton is different as it requires much more markup (compared to a default html button), a link is just a link

**Comment by melloware** [comment]
@hfluz Instead of having a fork of PrimeFaces why not just make your own composite component that does this?  No need to fork and modify the code.

**Comment by hfluz** [comment]
Yes, it was a decision I made a few years ago without thinking too much about it (just being able to customize Primefaces for my own needs was quite interesting back then). 

I already have a list of changes I made and I'm considering all the approaches I can choose for each of them. Thanks for the suggestion of the composite component for this issue, I'll consider it.

**Comment by melloware** [comment]
@hfluz Thanks. I will close this ticket.  Thanks for your thoughtful input though!
