### ISSUE TITLE
 Locale support for p:chart

### ISSUE THREAD

**Issue by fcanevar** [primefaces/primefaces#508]
The chart component (http://www.primefaces.org/showcase/ui/chart/line.xhtml) should support different locales to visualise numbers like "1,1" or "1.000,582" instead of "1.1".
If I wear to implement this I would add a new "locale" attribute and format the numbers according to the locale, jQplot supports internationalisation via these parameters: $.jqplot.sprintf.thousandsSeparator, $.jqplot.sprintf.decimalMark.

Thanks

**Comment by fcanevar** [comment]
Right now I'm using an extender but I think it could be more transparent by using a "locale" attribute

**Comment by cagataycivici** [comment]
This should be up to you using tickFormat.
