### ISSUE TITLE
TabView:Tab: Adding form into tab prevents commandButtons executing

### ISSUE THREAD

**Issue by AhmetKoca** [primefaces/primefaces#5080]
1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? No , but works in 6.2
- Application server + version: Apache Tomcat 9.0.22
- Affected browsers: chrome , firefox. Not testet on other browsers.

2) Expected behavior
Being able to use <h:from> and <p:commandButton> s inside a <p:tab>
as in version 6.2
3) Actual behavior
The commandbuttons are not executing(backing method is not called)

4) Steps to reproduce
Create a Tabview with 2 tabs and a form with commndbutton(s) in each tabs
5) Sample XHTML

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sec="http://www.springframework.org/security/tags">

	<p:tabView scrollable="true" id="detailsTabView"
		activeIndex="#{testPlanController.activeTabIndex}" dynamic="true"
		cache="false">
		<p:ajax event="tabChange" listener="#{testPlanController.onTabChange}" />

		<p:tab >
			<h:form id="testPlanDetailsForm">
				<p:toolbar style="margin-bottom:3px;">
					<f:facet name="right">
						<p:commandButton id="saveDetails" value="#{word['saveDetails']}"
							action="#{testPlanController.saveDetails()}" icon="ui-icon-save"
							styleClass="btn-primary" process="testPlanDetailsForm"
							update=":main:messages :main:treePG "
							rendered="#{!testPlanController.selectedNode.type.equalsIgnoreCase(commonConstants.treeNodeDefaultType)}" />
					</f:facet>
				</p:toolbar>
			</h:form>
		</p:tab>
		
		<p:tab >
			<h:form id="blabla">				
			</h:form>
		</p:tab>
	</p:tabView>
</ui:composition>
```

 6) Sample bean

```java
@ManagedBean(name = "testPlanController")
public class TestPlanController implements Serializable {

public String saveDetails() {
                //This method is never called
		return null;
	}
}
```

**Comment by melloware** [comment]
I am not positive but I don't think you can use Tabview this way since its an AJAX component.  The entire TabView must be wrapped in `<h:form>` so it can submit tab changes etc.   And of course you can't have an `<h:form>` inside and `<h:form>` as that is a violation of the HTML spec.

You said this worked in PF 6.2?

**Comment by tandraschko** [comment]
in generell melloware is right
- nested forms are not valid
- there SHOULD be a form around your tabView, it should however work without it. I removed the exception again before 7.0 final.

**Comment by AhmetKoca** [comment]
> I am not positive but I don't think you can use Tabview this way since its an AJAX component. The entire TabView must be wrapped in `<h:form>` so it can submit tab changes etc. And of course you can't have an `<h:form>` inside and `<h:form>` as that is a violation of the HTML spec.
> 
> You said this worked in PF 6.2?

Sorry for insufficient information.
This page is included from another page in a <h:form> element.
So the <p:tabView> is indeed wrapped by <h:form>.

Yes it works well when i revert back to 6.2

**Comment by AhmetKoca** [comment]
I was unaware of that HTML spec.
Now I am using partial processing and partial update of <p:tab> instead of nested forms.
So problem seems solved.

**Comment by melloware** [comment]
That is why it worked before. You had a form wrapping the TabView which was the only form that mattered.  Those inner forms were being ignored by JSF.  Thanks for closing.
