### ISSUE TITLE
IdleMonitor: support multiple on the same page

### ISSUE THREAD

**Issue by pazepaze** [primefaces/primefaces#5084]
# IdleMonitor: support multiple on the same page
When using multiple idle monitor tags, they influence each other. I needed to use separate idle timers on the same page with different timeout times.

I also made a pull request with my solution #5083. I developed this for primefaces 6.1 but rebased and adapted it to the current 7.1.SNAPSHOT master.

Note that the idle timer is from [https://github.com/thorst/jquery-idletimer](https://github.com/thorst/jquery-idletimer).
## 1) Environment
- PrimeFaces version: 7.1
- Issue is present on 6.1 and current master as well
- Application server + version: Wildfly 17.0.1.Final, but affects all
- Affected browsers: Chrome 76.0.3809.100, but should affect all

## 2) Expected behavior
When using multiple p:idleMonitor tags with different timeouts, they should all work independently of each other.

## 3) Actual behavior
The idleMonitors all store data under the same key and overwrite the timers of each other.

## 4) Steps to reproduce

Use two p:idleMonitor tags on the same page with different timeouts. Check when onidle is executed.

## 5) Sample XHTML

This reproduces the issue. Check console log when onidle timers are executed.
[https://github.com/pazepaze/primefaces-test/commit/0785d96c1b04be240558e7fbba1208c74fd930b9](https://github.com/pazepaze/primefaces-test/commit/0785d96c1b04be240558e7fbba1208c74fd930b9)

## 6) Sample bean

not applicable

**Comment by melloware** [comment]
Ticket submitted to IdleTimer core JS project: https://github.com/thorst/jquery-idletimer/issues/53
