### ISSUE TITLE
Spinner: attribute decimalPlaces not effective if the value is initially null.

### ISSUE THREAD

**Issue by Selaron** [primefaces/primefaces#5085]
## 1) Environment
- PrimeFaces version: 7.0, 7.1-SNAPSHOT and probably earlier

## 2) Expected behavior

When setting the decimalPlaces attribute to 3, I'd expect being able to input 3 decimal places into the spinner. This should not depend on the component initial value (the value received from ValueExpression when rendered)

## 3) Actual behavior
If the initial value is null, decimalPlaces="3" does not take effect and I'm unalbe to input decimal places at all. If the inital value is not null, it works as expected.

## 4) Steps to reproduce

In example below, the first spinner doesn't allow decimal, the second does.

## 5) Sample XHTML

```
<h:form>
	<p:spinner value="#{myBean.dblVal}" decimalPlaces="3"/>
	<p:spinner value="#{myBean.dblVal2}" decimalPlaces="3"/>
</h:form>

```

## 6) Sample bean

```
@Named
public class MyBean implements Serializable {
	private Double dblVal;
	private Double dblVal2 = 25.;
       // getter and setter
}
```

## 7) Looking into it

In spinner.js, [this line of code](https://github.com/primefaces/primefaces/commit/d3abd728d89a967a6bbb6793e4b2900c4a020705#diff-79a7d2ebb6077041b69b516c990a58c8R15) depends on a nun null value being present:

```
 if(this.input.val().indexOf('.') > 0 && this.cfg.decimalPlaces) {
   this.cfg.precision = this.cfg.decimalPlaces;
  }
```

I'm not sure why it requires an initial value to contain a dot in order to take the configured decimalPlaces attribute.

**Comment by Selaron** [comment]
Requiring an initial value to contain a dot might have been done in order to 'ensure' our value attribute is bound to a decimal typed property, not an Integer.

**Comment by melloware** [comment]
Couldn't we just make it...
```javascript
if(this.cfg.decimalPlaces > 0) {
   this.cfg.precision = this.cfg.decimalPlaces;
  }
```

Where even if decimalPlaces is undefined it will report FALSE.

**Comment by melloware** [comment]
Test case reproducer: 
[pf-5085.zip](https://github.com/primefaces/primefaces/files/3534713/pf-5085.zip)
