### ISSUE TITLE
Tree: search does not show all matching nodes

### ISSUE THREAD

**Issue by eversnarf** [primefaces/primefaces#5089]
## 1) Environment
- PrimeFaces version: 7.0.7
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? Not tried
- Application server + version: Tomcat 8.5.20
- Affected browsers: Firefox, Chrome, Edge

## 2) Expected behavior
When using filtering on a `<p:tree>`, I expect the search to show all matching nodes, expanding all ancestor nodes to a matching one.

## 3) Actual behavior
When both a parent and a child nodes match, only the parent node is shown, i.e. the parent node is not expanded and as a result the child node is not directly visible (one has to expand the parent to see it).

## 4) Steps to reproduce
Here is a simple two-level tree:
![image](https://user-images.githubusercontent.com/5243336/42587444-092fb738-853b-11e8-99a7-d183f3c72d72.png)

If I start typing `nut` in the search box, I see the nodes `Capsule / Brazil nut`, `Fibrous drupe / Coconut`, `Fibrous drupe / Walnut` and top node `Nut` (so far so good) **but** not its child node `Hazelnut`.

![image](https://user-images.githubusercontent.com/5243336/42587888-613f205c-853c-11e8-81ab-3fb5e001e9b4.png)

Actually, `Nut / Hazelnut` is present in the tree but the `Nut` node is not expanded.

## 5) Sample XHTML
```xml
<p:tree value="#{treeBean.root}" var="node" filterBy="#{node}" filterMatchMode="contains">
    <p:treeNode>
        <h:outputText value="#{node}"/>
    </p:treeNode>
</p:tree>
```

## 6) Sample bean
```java
public class TreeBean {

    private TreeNode root;

    public TreeBean() {
        this.root = new DefaultTreeNode();
        this.root.getChildren().add(buildNode("Achene", "Strawberry"));
        this.root.getChildren().add(buildNode("Capsule", "Brazil nut"));
        this.root.getChildren().add(buildNode("Fibrous drupe", "Coconut", "Walnut"));
        this.root.getChildren().add(buildNode("Legume", "Bean", "Pea", "Peanut"));
        this.root.getChildren().add(buildNode("Nut", "Beech", "Hazelnut", "Oak acorn"));
        this.root.getChildren().add(buildNode("Berry", "Cranberry", "Gooseberry", "Redcurrant", "Tomato"));
        this.root.getChildren().add(buildNode("Drupe", "Apricot", "Cherry", "Olive", "Peach", "Plum"));
    }

    private TreeNode buildNode(String nodeName, String... childrenNames) {
        TreeNode node = new DefaultTreeNode(nodeName);
        for (String childName : childrenNames) {
            node.getChildren().add(new DefaultTreeNode(childName));
        }
        return node;
    }

    public TreeNode getRoot() {
        return root;
    }
}
```

**Comment by eversnarf** [comment]
Relates to #3866

**Comment by melloware** [comment]
Also relates to  https://github.com/primefaces/primefaces/issues/3926 ?

**Comment by eversnarf** [comment]
Not really. In my case, node selection is not in the picture.

**Comment by melloware** [comment]
Attached is a test case reproducer: 
[pf-5089.zip](https://github.com/primefaces/primefaces/files/3541414/pf-5089.zip)

However I am not sure this is a bug.  I would like @Rapster input on this.  Because your TreeNode itself matches "Nut" it considers the whole node and all its children a match.
Example:
![image](https://user-images.githubusercontent.com/4399574/63695616-137f6680-c7e7-11e9-96fd-305966a7149f.png)

However if I change the Node "Nut" to "Test" it properly shows the Hazlenut option only.

![image](https://user-images.githubusercontent.com/4399574/63695435-b2f02980-c7e6-11e9-9988-5fc301fd8e56.png)

Is your real issue just that the node is not expanded for you automatically?

**Comment by melloware** [comment]
Just submitted a PR which expands the "Nut" node in your example test case.

**Comment by eversnarf** [comment]
> Is your real issue just that the node is not expanded for you automatically?

Issue is that I expect the node to be expanded if and only if one or more of its descendants matches the search.
So, in my example, I expect the `Nut` node to be expanded because its child node `Hazelnut` is also a match.

**Comment by melloware** [comment]
OK so with my fix I added a new branch "Pine Nut" that has Nut in the node name but not in any of the leaves and it also expands.  See this screenshot.
![image](https://user-images.githubusercontent.com/4399574/64018063-5730e380-caf9-11e9-9402-8336253a08e0.png)

It expands your node for "Hazlenut" though also. Can you confirm this is what you want?

**Comment by eversnarf** [comment]
Ideally, in my case, it should not expand `Pine nut`. My feeling is that, as a user, I expect that all matching nodes are directly visible (what your fix does) but not to see the children of a node if none of them is a match.

**Comment by melloware** [comment]
Hmm that makes it more difficult because in my mind Pine Nut **is** a match.  The parent node has the word "Nut" it in even though its children do not is a match.  And there is no way to know a parent doesn't have any children that match without walking the set of nodes a second time which doesn't seem very efficient.  

Unless you come up with something more clever I think a matching parent node name **should** expand the node.

**Comment by eversnarf** [comment]
Let me see if I can propose something.

**Comment by eversnarf** [comment]
In my opinion, the issue with the solution in your PR is that it not only expands the matching node but also all its descendants. 
Imagine that we have a three-level tree with 10 children for each node and we do a _lenient_ (non-strict) search. Then, even if the matching node is at the root level, we display 100 nodes below it - even if none of them actually matches the filter. I think that this is not what users would expect.

I think a I have a working solution. I just need to test it a bit more then I'll be happy to propose a PR.

**Comment by melloware** [comment]
Absolutely please submit a PR for review.

**Comment by eversnarf** [comment]
PR created: [#5109](https://github.com/primefaces/primefaces/pull/5109)
