### ISSUE TITLE
p:ajax - automatically add @this to process if not already set

### ISSUE THREAD

**Issue by sdsdf23423reasdf** [primefaces/primefaces#509]
Please see the stackoverflow question here - this still happens as of version 5.2.

http://stackoverflow.com/questions/10287115/primefaces-ajax-listener-not-executed-when-process-attribute-is-specified-for-a

This is extremely confusing and is the opposite of how the standard JSF components work. If specfying a component id to process, we should not have to also explicity specify @this in the process attribute for the action listener to be invoked. 

Finally, the process and update attributes should be called and should have the same default values as the execute and render attributes (respectively) of the f:ajax component. It does not seem like there is any utility or reason for renaming the attributes and making the default values different.

**Comment by tandraschko** [comment]
We can do something like this:
if (!process.contains("@this")) {
    process = "@ŧhis " +  process;
}

**Comment by cagataycivici** [comment]
This will break many apps, we should not touch it at all. It has been like this for years and all of a sudden after an upgrade to a new version, behavior of apps will change and backward compatibility possibly broken for some cases.

**Comment by sdsdf23423reasdf** [comment]
Can this not be a configuration value at the least? The workaround is simple enough once you know the issue, but it seems very broken to me and has left me and many other developers puzzled for hours as to why an action listener is not being called.

Finally, do you really think any application would be relying on broken behavior of this to work correctly? I know you can't anticipate exactly how hundreds of applications are using it, but it seems to be a very paranoid view to believe that this could possibly have an adverse effect.

It should be a configuration value that by default works correctly as expected, but can be changed back to not automatically implicitly add @this in the case that an application is relying on this incorrect to work. If so, this should be well documented in the release notes.

**Comment by tandraschko** [comment]
+1

@cagataycivici 
If a app will be broken with this change, the application is >already broken< as the developed action/actionListener won't be called.
With this change, many boilerplate code can be removed.
