### ISSUE TITLE
DataTable: stickyHeader breaks after sidebar collapse

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#5094]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: all
- Affected browsers: Chrome, Edge, Firefox

## 2) Expected behavior
Sticky header adapts to the sidebar collapsing

## 3) Actual behavior
Sticky header doesn't adapt:
![sticky](https://user-images.githubusercontent.com/18428155/63756777-38dca500-c8b9-11e9-8330-69a3199c8dfd.jpg)

## 4) Steps to reproduce
Go to https://www.primefaces.org/showcase/ui/data/datatable/sticky.xhtml and resize the window until the sidebar collapses

**Comment by NicolaIsotta** [comment]
I discovered the issue while testing the Apollo layout, so I don't know if this is the right place to report it.

**Comment by melloware** [comment]
This is due to the fact the sticky is registered for browser resizing but not for when a CSS Media Query makes the sidebar disappear after resize.  there is no Jquery notification for that.
```javascript
PrimeFaces.utils.registerResizeHandler(this, 'resize.sticky-' + this.id, null, function(e) {
```

**Comment by miedrl** [comment]
@melloware Will this issue be fixed in PrimeFaces 11.0.0?

**Comment by melloware** [comment]
That's up to @mertsincan he seemed to have an idea on how to solve this for 11.0

**Comment by mertsincan** [comment]
Hi all,

Such sticky problems will be completely solved with the new table integration. Exp;
https://primefaces.org/primevue/showcase/#/datatable/scroll (Datatable uses _position: sticky_ style)
It will be very pleasant for me to delete all the JS codes related to Sticky. :) 

For now, could @melloware please make a fix using registerResizeHandler method? Thanks a lot!

**Comment by melloware** [comment]
Yep let me see what I can do!
