### ISSUE TITLE
The mindate/maxdate not working with timeOnly mode on DatePicker and Calendar

### ISSUE THREAD

**Issue by Selaron** [primefaces/primefaces#5099]
## 1) Environment
- PrimeFaces version: **7.0**
- Does it work on the newest released PrimeFaces version? **No** (7.0)
- Does it work on the newest sources in GitHub? **No**
- Application server + version: **Apache Tomcat 9**
- Affected browsers: **Any**

## 2) Expected behavior

If I set an instance of java.util.Date for the maxdate attribute with time e.g. 19:00, datePicker should limit time selection to 19:00.

## 3) Actual behavior

A javascript exception is thrown and the datePicker initialization fails, making it unusable. (No popup on focus).
The same is true for the mindate attribute.
When removing the maxdate attribute, it works as expected but with unlimited time selection.

jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2 Uncaught Unexpected literal at position 0
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
setTimeout (async)
k.readyException @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
e @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
t @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
setTimeout (async)
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
c @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
c @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
t @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
setTimeout (async)
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
c @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
c @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
ready @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2
B @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:2

## 4) Steps to reproduce

Just invoke following xhtml and watch the browser dev tools console:

## 5) Sample XHTML

```
<h:form>
	<p:datePicker value="#{myBean.dateValue}" timeOnly="true"
		pattern="HH:mm" maxdate="#{myBean.dateMaxValue}" />
	<p:commandButton value="submit" process="@form" update="out" />

	<h:outputText id="out" value="#{myBean.dateValue}" />
</h:form>
```

## 6) Sample bean
```

package my.pkg;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class MyBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Date dateValue;

	private Date dateMaxValue;

	@PostConstruct
	public void init() {
		Calendar calendar = GregorianCalendar.getInstance();
		// make it 01.01.1970 11:33:09
		calendar.setTimeInMillis(0);
		calendar.set(Calendar.HOUR_OF_DAY, 11);
		calendar.set(Calendar.MINUTE, 33);
		calendar.set(Calendar.SECOND, 9);
		dateMaxValue = calendar.getTime();
	}

	public Date getDateValue() {
		return dateValue;
	}

	public void setDateValue(Date dateValue) {
		this.dateValue = dateValue;
	}

	public Date getDateMaxValue() {
		return dateMaxValue;
	}

}

```

**Comment by melloware** [comment]
@Selaron have you been able to debug the JS at all?

**Comment by Selaron** [comment]
In the uncompressed version of JQuery 3.4.1 (https://code.jquery.com/jquery-3.4.1.slim.min.map) it happens in line 10154 where jQuery.fx is undefinied:

```
L10154 >	jQuery.fx.step[ hook ] = function( fx ) {
			if ( !fx.colorInit ) {
				fx.start = color( fx.elem, hook );
				fx.end = color( fx.end );
				fx.colorInit = true;
			}
			jQuery.cssHooks[ hook ].set( fx.elem, fx.start.transition( fx.end, fx.pos ) );
		};
	} );

};

```

The exception log looks like this:

```
jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10154 Uncaught TypeError: Cannot read property 'step' of undefined
    at String.<anonymous> (jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10154)
    at each (jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:367)
    at Function.color.hook (jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10116)
    at jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10166
    at jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10208
    at jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:14
    at jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:16
(anonymous) @ jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10154
each @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:367
color.hook @ jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10116
(anonymous) @ jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10166
(anonymous) @ jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:10208
(anonymous) @ jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:14
(anonymous) @ jquery-plugins.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:16
jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3850 Uncaught Unexpected literal at position 0
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3850
setTimeout (async)
jQuery.readyException @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3849
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3869
mightThrow @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3557
process @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3625
setTimeout (async)
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3663
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3291
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3421
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3429
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3291
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3421
process @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3645
setTimeout (async)
(anonymous) @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3663
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3291
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3421
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3429
fire @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3291
fireWith @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3421
ready @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3901
completed @ jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT:3911

```

**Comment by melloware** [comment]
Is it this: https://forum.jquery.com/topic/jquery-fx-is-undefined

**Comment by Selaron** [comment]
Ok my previous post is invalid - I picked up the wrong JQuery script with no FX. It's not even required to get the uncompressed JQuery but just make Firefox dev tools stop on handled JS exceptions.

The error is thrown from line 733 in datepicker.js:

```
checkLiteral = function() {
	if (value.charAt(iValue) !== format.charAt(iFormat)) {
		throw "Unexpected literal at position " + iValue;
	}
	iValue++;
};

```

While:

```
vaue =  "11:33"
format = "HH:mm"
iValue = iFormat = 0
```

**Comment by mertsincan** [comment]
I think this issue is related to #5186. But, it has some issues. Could you please check this issue again?

**Comment by christophs78** [comment]
see https://github.com/primefaces/primefaces/pull/5313

**Comment by christophs78** [comment]
see PR https://github.com/primefaces/primefaces/pull/5313
