### ISSUE TITLE
 dataGrid: paginator not working correctly

### ISSUE THREAD

**Issue by hfatgit** [primefaces/primefaces#5100]
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/3555040/primefaces-test.zip)
![2019-08-29 10_19_19-OTCM - OTCM](https://user-images.githubusercontent.com/6489931/63932302-357f2000-ca57-11e9-8cc2-2fed2485f6e8.png)

## 1) Environment
- PrimeFaces version: 7.0
- Application server + version: Tomcat 8.5 on Linux & Windows
- Affected browsers: seems browser independend. 
- Tested on  
Chrome 76.0.3809.100 (32-Bit), 
FireFox 60.8.0esr (32-bit), 
Microsoft Edge 38.14393.2068.0, 
InternetExplorer 11.2906.14393.0

## 2) Expected behavior
When setting the count of items to display per page, show the selected number of items

## 3) Actual behavior
When setting "rowsPerPage" to a value not matching a multiple of "columns", the control fills the view with the next full multiple of declared columns.
Controls (like p:commandButton) contained in the extra items do not respond as expected. 
Buttons do not communicate with bean. 

## 4) Steps to reproduce
- Add more items to the dataGrid as needed to fill the view with more than rowsPerPage items. 
- Set rowsPerPage to value not beeing a multiple of the configured columns. Here columns="4" rowsPerPage="10"

## 5) Sample XHTML
See test.xhtml  in the attached project zip.

## 6) Sample bean
See Test.java and TestViewCdi.java in the attached project zip.
For CDI i used the Weld libraries to enable Tomcat CDI

The samples are based on the primefaces-test project. The sources of my tests are contained in the attached primefaces-test.zip file

**Comment by melloware** [comment]
You want it to look like this right?
![image](https://user-images.githubusercontent.com/4399574/63936771-b37b0100-ca2e-11e9-8b66-2856c0bfea17.png)

**Comment by hfatgit** [comment]
> 

> 
> 
> You want it to look like this right?
> ![image](https://user-images.githubusercontent.com/4399574/63936771-b37b0100-ca2e-11e9-8b66-2856c0bfea17.png)

Either looking like this or get the extra items functional. The more "correct" way would be your suggestion.

**Comment by melloware** [comment]
OK PR submitted with the fix.
