### ISSUE TITLE
Add validateMask attribute to InputMask

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#5105]
Defines whether mask pattern would be validated or not on the server side.

validateMask="true|false(default)"

**Comment by melloware** [comment]
@mertsincan shouldn't TRUE be the default to be more secure by default and let the user opt-out of security if they want to?

**Comment by tandraschko** [comment]
+1, yep

**Comment by mertsincan** [comment]
I need to talk to the PRO User again. He says that the application was not running when the user switched from 6.2 to 7.0. 

I don't think that most users who are currently migrating applications from version 6.2 to 7.0 are aware that they have lost this feature. We should specify them in the documentation. 
> https://github.com/primefaces/primefaces/issues/3234#issuecomment-361221532
> However, PrimeFaces does not seem to implement this feature. So I ignored it in my commit.

(I'm not sure if the priority is to protect existing applications or to change applications for security.)

I'll talk about it again. 
(Note: My personal idea is that the default value should be "true").

**Comment by melloware** [comment]
@mertsincan I added this InputMask blurb to the Migration Guide
