### ISSUE TITLE
placeHolder does not render for autoComplete component when multiple="true"

### ISSUE THREAD

**Issue by githubde** [primefaces/primefaces#511]
placeholder does not render for autoComplete component when multiple="true"

version primefaces 5.2

**Comment by sudheerj** [comment]
I can't replicate the issue on latest 5.3-SNAPSHOT(i.e, I can see the placeholder on autoComplete component when multiple option enabled).By the way the attribute name should be 'placeholder' not 'placeHolder'

**Comment by githubde** [comment]
@sudheerj, I have updated comment to "placeHolder" to correct "placeholder". I have retested in v5.2 and it is reproducible. I have a TestCase eclipse project but cannot attach .zip to issue tracker. How do I get access to 5.3-SNAPSHOT.jar so I could test it? Perhaps it is already fixed as you stated, but if it is reproducible in 5.2 should it be fixed in that version? Here is p:autoComplete usage in my .xhtml 

<p:autoComplete id="cc" value="#{cc.attrs.countryValue}"
        completeMethod="#{countryACMBean.complete}" var="c"
        itemLabel="#{c.nameEn}" itemValue="#{c}" multiple="true"
        converter="#{countryACConverter}" maxlength="50" size="40"
        required="true" requiredMessage="country is required"
        placeholder="test place holder for country FORM3" />

**Comment by cagataycivici** [comment]
Unable to replicate with 5.3 and 5.2.8.
