### ISSUE TITLE
MenuBar: Wrap if there is a separator in the menu

### ISSUE THREAD

**Issue by wklaczynski** [primefaces/primefaces#5126]
**When you use the separator in a menu, then the menu is wrapping.**

## 1) Environment
- PrimeFaces version: 7.0
- Affected browsers: Firefox

## 2) Sample XHTML

                <p:menubar>
                    <p:menuitem 
                        value="Main" 
                        icon="fa fa-home"
                        url="/app/faces/main.xhtml"/>
                    <p:separator/>
                    <p:menuitem 
                        value="Organization" 
                        icon="fa fa-institution"
                        url="/app/faces/organizations.xhtml"/>
                </p:menubar>

## 3) Proposed solution:
add ui-vertical and vertical separator icon. 

            .ui-menu>ul>li.ui-separator:not(.ui-megamenu-vertical), .ui-separator.ui-vertical { 
                background-image: url("#{resource['default:images/separator.png']}"); 
                background-position-x: 50%;
                background-position-y: 50%;
                background-repeat: no-repeat;
                border: none; 
                clear: none; 
                margin: 4px 6px 0; 
                box-shadow: none; 
                width: 2px;
                height: 23px;
            }

**Comment by melloware** [comment]
Can you please add the following information.

1. What theme are you using?

2. Can you post screenshots of before your fix and after your fix?

**Comment by wklaczynski** [comment]
I basically use the "delta" theme. But I can switch to others theme.

            <p:menubar>
                <p:menuitem 
                    value="Informacje" 
                    icon="fa fa-user"
                    url="/app/faces/main.xhtml"/>
                ........
                <p:separator/>
                <p:menuitem 
                    value="Organizacje" 
                    icon="fa fa-institution"
                    url="/app/faces/organizations.xhtml"/>
                ............
            </p:menubar>

This is how it looks after the patch.

        .ui-menu>ul>li.ui-separator:not(.ui-megamenu-vertical) { 
            background-image: url("#{resource['default:images/separator.png']}"); 
            background-position-x: 50%;
            background-position-y: 50%;
            background-repeat: no-repeat;
            border: none; 
            clear: none; 
            margin: 6px 6px 0; 
            box-shadow: none; 
            width: 2px;
            height: 18px;
        }

Before:

![obraz](https://user-images.githubusercontent.com/2326804/64489879-2e76bf80-d258-11e9-852b-d2a3473910ac.png)

Result:

![obraz](https://user-images.githubusercontent.com/2326804/64489444-abec0100-d253-11e9-99aa-1f461364b332.png)

**Comment by wklaczynski** [comment]
Additional style code also improves the use of vertical separators. This makes it possible to use the separator when the display is flex.

                        <h:panelGroup layout="block" style="display:flex;">
                            <p:button
                                href="....."
                                icon="fa fa-home"
                                />
                            <p:separator styleClass="ui-vertical"/>
                            <p:commandButton
                                id="j_security_start_button"
                                ajax="false"
                                value="Zaloguj się"
                                icon="fa fa-unlock"
                                >
                            </p:commandButton>
                            ......
                        </h:panelGroup>

Fix css style for "ui-vertical" css class:

    .ui-separator.ui-vertical {
            background: none; 
            background-image: url("#{resource['default:images/separator.png']}"); 
            background-position-x: 50%;
            background-position-y: 50%;
            background-repeat: no-repeat;
            border: none; 
            float: left;
            clear: none; 
            margin: 0px 4px;
            padding: 0px;
            box-shadow: none; 
            width: 2px;
            height: 23px;
        }

Used separator image:

![separator](https://user-images.githubusercontent.com/2326804/64489639-c9ba6580-d255-11e9-95b8-a0b7dfc0267c.png)

Before:
![obraz](https://user-images.githubusercontent.com/2326804/64489823-b8725880-d257-11e9-9433-ff1f89b820d6.png)

Result:
![obraz](https://user-images.githubusercontent.com/2326804/64489576-4a2c9680-d255-11e9-84e9-4d90ea2e73b4.png)

**Comment by melloware** [comment]
Thanks! Assigning to @mertsincan to review since its CSS related.

**Comment by melloware** [comment]
I think this should be done with the new Divider class like ...

```xml
<p:divider layout="vertical" />
```

**Comment by mertsincan** [comment]
Yes, Divider can be used instead of p:separator component. OR f:facet name="separator" ?? @melloware WDYT?

**Comment by melloware** [comment]
I feel like we should use Divider as it seems to make logical sense and it allows the flow the XHTML to look correct.

**Comment by mertsincan** [comment]
Thanks @melloware ;)

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primefaces/issues/7053
