### ISSUE TITLE
New carousel padding/margin are off.

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#513]
The padding/margin of upcoming carousel are a little bit off since basic ui-panel uses _0.2em_ padding and new carousel uses fixed _1px_.

Current view where borders are very close to each other.

http://fs2.directupload.net/images/150708/x785as4w.jpg

**Suggestions:**

Except a little right margin of the last visible item all paddings and margins are same as from other container components.

```
.ui-carousel
{
    padding: 0.2em; // or use ui-panel class
}

.ui-carousel .ui-carousel-viewport 
{
    margin: 0.2em 0;
}

.ui-carousel .ui-carousel-viewport .ui-carousel-items .ui-carousel-item
{
    margin-right: 0.2em;
}

.ui-carousel .ui-carousel-footer 
{
    // remove margin definition
}

.ui-carousel .ui-carousel-header 
{
    // remove margin definition
}
```

Preview:

http://fs1.directupload.net/images/150708/9kuln8at.jpg

**Comment by cagataycivici** [comment]
Should have been a forum post, it is a personal preference, you can increase it for your app.
