### ISSUE TITLE
ConfirmDialog: modal overlay does not disappear when showEffect has a value

### ISSUE THREAD

**Issue by uweklosa-veroveli** [primefaces/primefaces#5144]
## 1) Environment
- PrimeFaces version: 7.1-SNAPSHOT
- Does it work on the newest released PrimeFaces version? YES Version? 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) NO
- Application server + version: Jboss EAP 7.2.3
- Affected browsers: Firefox, Edge, Chrome

## 2) Expected behavior
After closing the confirmDialog the modal overlay should disappear
...

## 3) Actual behavior
A confirmDialog with for example showEffect="fade" does not remove the modal overlay after closing. The error is cause by the last change in src\main\resources\META-INF\resources\primefaces\dialog in line 206. instead of hideEffect  showEffect is used here.
..

## 4) Steps to reproduce
Try the example page, click on the button, click on Y_es or No
.. 

## 5) Sample XHTML
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

	<h:head>
		<title>PrimeFaces Test</title>
	</h:head>
	<h:body>
		<f:view>
			<h:form>
				<p:commandButton value="Confirm">
					<p:confirm header="Confirm" message="Confirm?"/>
				</p:commandButton>
			</h:form>
			<p:confirmDialog global="true" showEffect="fade">
				<p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>
				<p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"/>
			</p:confirmDialog>
		</f:view>
	</h:body>
</html>
```

..

## 6) Sample bean

..

**Comment by melloware** [comment]
I see the problem I will submit a fix.
