### ISSUE TITLE
TimeLine: drag&drop event between groups doesn't keep the date range

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#5147]
## 1) Environment
- PrimeFaces version: 7.0.7
- Does it work on the newest released PrimeFaces version? No Version? 7.0.7

## 2) Expected behavior
When moving an event from one group to another group - visually it should look the same and act the same. You should still be able to resize it. The model appears to be correct - the UI does not match the model.

## 3) Actual behavior
The event gets anchored to the top, it becomes a fixed width, and you can not change its width.

## 4) Steps to reproduce
https://github.com/mores/primefaces-test/tree/timeline001-changeGroup
mvn jetty:run-exploded

## 5) Sample XHTML
see github

## 6) Sample bean
see github

This issue has been around for a while: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/332

![image](https://user-images.githubusercontent.com/1318377/64815077-d2bb7780-d572-11e9-99e5-13a2295962be.png)

- - - - - - - 
Group: User 5
Start: Wed Sep 11 12:00:00 EDT 2019
End: Wed Sep 11 16:00:00 EDT 2019

![image](https://user-images.githubusercontent.com/1318377/64815112-e961ce80-d572-11e9-9ba3-f61f23ff9c93.png)

Group: User 4
Start: Wed Sep 11 14:00:00 EDT 2019
End: Wed Sep 11 18:00:00 EDT 2019

**Comment by melloware** [comment]
@jasonex7 Another one for you to investigate if you don't mind?

**Comment by jasonex7** [comment]
This is related to this issue #5097 that was already fixed.

**Comment by melloware** [comment]
@mores this is fixed in 7.0.8 Elite (should be out soon) and future 7.1 community. Thanks for reporting!
