### ISSUE TITLE
Timeline: TimelineUpdater is null when javax.faces.PARTIAL_STATE_SAVING is false

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#5149]
## 1) Environment
- PrimeFaces version: 7.0.7
- Does it work on the newest released PrimeFaces version? No Version? 7.0.7

## 2) Expected behavior
I expect timelineUpdater not to be null

## 3) Actual behavior
timelineUpdater is null

## 4) Steps to reproduce
https://github.com/mores/primefaces-test/tree/timeline001-nullUpdater

         <context-param> 
                <param-name>javax.faces.PARTIAL_STATE_SAVING</param-name> 
                <param-value>false</param-value> 
        </context-param>

## 5) Sample XHTML
see github

## 6) Sample bean
Timeline source = (Timeline)event.getSource();
TimelineUpdater timelineUpdater = TimelineUpdater.getCurrentInstance( source.getClientId() );
see also github

**Comment by melloware** [comment]
@jasonex7 Another one to investigate.  Thanks @mores for all of these reports.  We are working on a timeline overhaul for 7.1 so yours is perfect timing.

**Comment by melloware** [comment]
@mores What is your use case that you have PARTIAL_STATE_SAVING false?  

I believe in future JSF this will be the only option and they will be removing Full state saving.

**Comment by mores** [comment]
Back in 2011 this application was using icefaces. In order to utilize Advanced Components it had to be false ( http://res.icesoft.org/docs/v2_devguide/html/ICEfaces%202.0.0%20Release%20Notes.html )

At some point we migrated to primefaces.

Over the years we have tried to set it back to true, only to find certain pages are now broken, so it keeps getting set back to false. 

It would take some time to find out if we can switch back to true today, and if not why.

**Comment by jasonex7** [comment]
This is an old bug:

- https://forum.primefaces.org/viewtopic.php?t=42460
- https://forum.primefaces.org/viewtopic.php?f=14&t=41800
- #774
- primefaces-extensions/primefaces-extensions.github.com#127

I think the solution to this is use javax.faces.PARTIAL_STATE_SAVING = true (the default and recommended behavior in JSF) and use javax.faces.FULL_STATE_SAVING_VIEW_IDS to indicate the pages of the project that really needs full state saving and let the others, among them the page with <p:timeline>, that behave as default. [Reference](https://forum.primefaces.org/viewtopic.php?p=133767&sid=d8121321bb7c7db4ea0a6730e0c12bc3#p133767)

**Comment by melloware** [comment]
Thanks for the research @jasonex7

**Comment by jasonex7** [comment]
I found a much better solution that fixes this problem once for all. The problem with PARTIAL_STATE_SAVING = false is that there is no RESTORE_VIEW phase so the TimelineListener (which is responsible for setting TimelineUpdater) gets executed on RENDER_RESPONSE phase which is too late for event listeners. When PARTIAL_STATE_SAVING = true, the TimelineListener gets executed on RESTORE_VIEW and TimelineUpdater is available for event listeners. 

I'm going to make PR for this with current <p:timeline> implementation and when PrimeFaces merged that, I'm going to merge on my PR #5113

**Comment by mores** [comment]
When javax.faces.PARTIAL_STATE_SAVING is set to true, my panelGroup that is created using binding breaks. 
Adding that page to FULL_STATE_SAVING_VIEW_IDS makes it work again.
