### ISSUE TITLE
Datatable paginator orientation

### ISSUE THREAD

**Issue by Lemongrass3110** [primefaces/primefaces#515]
The paginator of the datatable is not rendered in one line for the header and the footer, which makes it looking unprofessional.

I am running on primefaces 5.2 from maven central. The image was taken from IE 11.

![primefaces datatable paginator](https://cloud.githubusercontent.com/assets/3517879/8644355/b70231f8-293e-11e5-8e88-51ec7ff96adf.jpg)

Sample code:

```
<p:dataTable 
    id="persons"
    var="person" 
    value="#{controller.persons}"
    emptyMessage="No entries were found."
    paginator="true"
    rows="20"
    paginatorTemplate="{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
    rowsPerPageTemplate="10,20,50,100"
    rowKey="#{person.id}"
    selectionMode="single"
    selection="#{controller.selectedPerson}">

    <p:column headerText="ID">
        <h:outputText value="#{person.id}"/>
    </p:column>
    <p:column headerText="Nachname">
        <h:outputText value="#{person.nachname}"/>
    </p:column>
    <p:column headerText="Vorname">
        <h:outputText value="#{person.vorname}"/>
    </p:column>
    <p:column headerText="Geburtsdatum">
        <h:outputText value="#{person.geburtsdatum}"/>
    </p:column>
</p:dataTable>
```

**Comment by cagataycivici** [comment]
What do you mean in one line? What is the issue here?

**Comment by Lemongrass3110** [comment]
Sorry to bother you, it was something style related it seems.
After I removed a `<div>` which was next to the datatable on the left side, it is now behaving correctly.
I just do not really understand why only the paginator was misplaced and not the whole datatable.
And my problem with it was that I personally think that it looks unprofessional if it is placed on different identitations in the header and the footer of the datable.

I would understand that you do not want to look further into this, so feel free to close this.

**Comment by cagataycivici** [comment]
I don't understand your question. I can't replicate your issue.
