### ISSUE TITLE
Timeline: model is not being updated with changes

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#5156]
## 1) Environment
- PrimeFaces version: 7.0.7
- Does it work on the newest released PrimeFaces version? No Version? 7.0.7

## 2) Expected behavior
When a user changes an event - the model should be kept in sync with all changes

## 3) Actual behavior
The TimelineEvent from the TimelineModificationEvent is correct, but the TimelineModel will still have the original End Date

## 4) Steps to reproduce
https://github.com/mores/primefaces-test/tree/timeline001-modelNotUpdating
mvn jetty:run-exploded

## 5) Sample XHTML
see github

## 6) Sample bean
see github

![image](https://user-images.githubusercontent.com/1318377/64866574-adc61380-d609-11e9-89d2-3b044ed54409.png)

![image](https://user-images.githubusercontent.com/1318377/64866600-be768980-d609-11e9-8de8-46630c1a679d.png)

onEdit
EndDate from timelineEvent: Thu Sep 12 23:00:00 EDT 2019
EndDate from model: Fri Sep 13 04:33:55 EDT 2019

**Comment by melloware** [comment]
@jasonex7 ??

**Comment by jasonex7** [comment]
This is a documentation problem and the lack of an example in PrimeFaces showcase of server side edit. When you update the timeline javascript component that not necessarily means you update the server side model. To keep both sync, you have to update the model in the corresponding add, delete or changed listener method. To learn how to use that I had to check original PrimeFaces Extension showcase that had more timeline examples so maybe in the future those examples can be migrated to PF showcase.

![image](https://user-images.githubusercontent.com/16229253/64868317-b2d49400-d604-11e9-9dc5-f9eb88cd0d35.png)

This is related to https://github.com/primefaces/primefaces/issues/5118#issuecomment-528891817

**Comment by melloware** [comment]
So after we merge your PR we should then create more showcase examples to match the old PFE Timeline examples.  @mores can you confirm this fixes your issue and we can close this issue.

**Comment by mores** [comment]
Yes, this fixes my issue.

**Comment by jasonex7** [comment]
> So after we merge your PR we should then create more showcase examples to match the old PFE Timeline examples.

@melloware Yeah, those examples should be back then.
