### ISSUE TITLE
FileUpload

### ISSUE THREAD

**Issue by sulaiman-allemyar** [primefaces/primefaces#5158]
I am developing a web application using spring boot and primeface.
When I upload files more than 1Mb it can not be uploaded. However  I didnt limit the size of file in my view page.
when I limit it to a large size(like 4000000000), it even does not work in this situation too.
When I upload a file more than 1MB it does not even call the backing bean method.
Please help me it is urgent problem

**Comment by melloware** [comment]
Please use the forum for questions: https://forum.primefaces.org/viewforum.php?f=3

This issue tracker is only for bugs and enhancements not questions.

Although it looks like Spring boot is 1MB by default you have to change it. See: https://stackoverflow.com/questions/40271484/spring-upload-file-size-limit
