### ISSUE TITLE
InputNumber and Spinner: support additional bean validation constraints

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#5165]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: all
- Affected browsers: all

## 2) Issue Description
Right now, only Spinner is considered in [BeanValidationInputMetadataTransformer](https://github.com/primefaces/primefaces/blob/70a71f9524dd68d065198c9c442d80253274c9c1/src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java) :
https://github.com/primefaces/primefaces/blob/70a71f9524dd68d065198c9c442d80253274c9c1/src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java#L91-L102
InputNumber should be included too.
Adding `@DecimalMax` and `@DecimalMin` (and maybe `@Digits`) annotations support would be useful too.

**Comment by NicolaIsotta** [comment]
I'll provide a PR as soon as I have some time to test.

**Comment by melloware** [comment]
Excellent I will review your PR after you submit.
