### ISSUE TITLE
DatePicker: Initial value doesn't render the rangeSeparator

### ISSUE THREAD

**Issue by Hellebrekers** [primefaces/primefaces#5170]
## 1) Environment
- PrimeFaces version: 7.0.5
- Does it work on the newest released PrimeFaces version? 7.06, No
- Does it work on the newest sources in GitHub? No
- Application server + version: WildFly 16
- Affected browsers: All

## 2) Expected behavior
When setting the attached 'selection' within a bean on @PostConstruct then the component should also use the rangeSeparator.

## 3) Actual behavior
It now uses " - " as separator (probably caused by https://github.com/primefaces/primefaces/blob/7132ccfe36214a76a7ecd2fcebbcd82359ff48f8/src/main/java/org/primefaces/util/CalendarUtils.java#L205)

## 4) Steps to reproduce
See ##2, then just render the page

## 5) Sample XHTML
```<p:datePicker selectionMode="range" selection="#{bean.selectedDateRange}"/>```

## 6) Sample bean
```
@PostConstruct
public void init() {
    selectedDateRange = Arrays.asList(new Date(), new Date());
}

**Comment by melloware** [comment]
Original Issue: https://github.com/primefaces/primefaces/issues/4514

**Comment by melloware** [comment]
@Hellebrekers can you review my PR.  I just tested your snippet using the showcase and I get this on page load.
![image](https://user-images.githubusercontent.com/4399574/65151545-4edf1080-d9f4-11e9-804a-42c298945856.png)

Is your issue that if you assign a custom rangeSeparator it was not being respected?

**Comment by melloware** [comment]
And if I set rangeSeparator="@" I see this on page load.

![image](https://user-images.githubusercontent.com/4399574/65152199-7aaec600-d9f5-11e9-9664-85f9dfaffd01.png)

**Comment by Hellebrekers** [comment]
@melloware Works perfectly fine like that!
