### ISSUE TITLE
p:selectOneMenu option element titles not working

### ISSUE THREAD

**Issue by afd0174** [primefaces/primefaces#5178]
1) Environment

PrimeFaces version: 7.0
Wildfly 10.1
Mojarra 2.2.13.SP1
Affected browsers: All browsers (server-side issue)

2) Expected behavior

In PrimeFaces 6.2, I could use Javascript to attach title attributes to the HTML option elements generated from the p:selectOneMenu tag (with the title elements appearing on hover-over as tool tips) .  In PrimeFaces 7.0, the Javascript approach does not yield tool-tips on hover over, nor does using the p:selectOneMenu attribute syncTooltip="True".  The same Javascript approach does work to add working title elements when using an h:selectOneMenu tag.

3) Actual behavior

In PrimeFaces 7.0, the p:selectOneMenu tag does not allow for title elements that display on hover-over.

4) Steps to reproduce

I've attached a maven project to demonstrate the issues described.

5) Sample XHTML

See maven project.

6) Sample bean

See maven project.

7) Attached code
[primefaces-selectonemenu-bug.zip](https://github.com/primefaces/primefaces/files/3637412/primefaces-selectonemenu-bug.zip)

**Comment by melloware** [comment]
Just change your JS to the following and it works fine.
```xml
<script type="text/javascript"> 
            $( document ).ready(function() {
                $('.ui-selectonemenu-item').attr('title', function(){
                    return this.innerText;
               });
             });
</script> 
```
