### ISSUE TITLE
Document CSP

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5179]
@melloware interessted?

**Comment by melloware** [comment]
Yep I can take the first crack at it and submit for review!

**Comment by melloware** [comment]
Reproducer for forum post: https://forum.primefaces.org/viewtopic.php?f=3&t=62352

[pf-csp.zip](https://github.com/primefaces/primefaces/files/4831583/pf-csp.zip)

Run `mvn clean jetty:run-exploded` and navigate to http://localhost:8080/primefaces-test/csp.xhtml

**Comment by melloware** [comment]
Reproducer for forum post: https://forum.primefaces.org/posting.php?mode=reply&f=3&t=62609

[pf-csp.zip](https://github.com/primefaces/primefaces/files/4896655/pf-csp.zip)

Run `mvn clean jetty:run-exploded` and navigate to http://localhost:8080/primefaces-test/radiocheck.xhtml
