### ISSUE TITLE
TreeTable: Add editInitEvent attribute to editable TreeTable

### ISSUE THREAD

**Issue by doleron** [primefaces/primefaces#5182]
Since 6.2 ```DataTable``` has an ```editInitEvent``` property to define a client side event to open cell on editable table (see [\#2603]) however the same property is not available for TreeTables.

**Comment by melloware** [comment]
@doleron Want to tackle this one now that you have some experience?

**Comment by doleron** [comment]
Sure!

**Comment by doleron** [comment]
@melloware let me know if this met the requirements: https://github.com/primefaces/primefaces/pull/6004
