### ISSUE TITLE
CSP: Spinner not registering change event

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5183]
PrimeFaces version: 7.1-SNAPSHOT

**CSP Disabled:**
- Go to the Showcase spinner example: http://localhost:8080/showcase/ui/input/spinner.xhtml
- On the Ajax Spinner press up or down and you will see the Ajax fire and the label updated

**CSP Enabled:**
- Go to the Showcase spinner example: http://localhost:8080/showcase/ui/input/spinner.xhtml
- On the Ajax Spinner press up or down and you will see no Ajax events fired.

I can see PrimeFaces registered the change event for the spinner.
```javascript
PrimeFaces.csp.register('j_idt710:ajaxSpinner_input',
  'onchange',function(event){PrimeFaces.ab({s:"j_idt710:ajaxSpinner",e:"valueChange",f:"j_idt710",p:"j_idt710:ajaxSpinner",u:"j_idt710:ajaxSpinnerValue"});}
);
```

However in the spinner code when its triggering the 'change' event nothing is happening.
```javascript
$this.input.trigger('change');
```

**Browsers:**
_IE11, Chrome, Firefox, _Edge:_ are all not firing the event

**Comment by melloware** [comment]
OK I think these two articles explain the problem...

https://stackoverflow.com/questions/37113525/how-to-trigger-js-native-even-addeventlistenerchange-function-by-jquery

https://stackoverflow.com/questions/21290775/jquery-el-triggerchange-doesnt-fire-native-listeners

**Comment by tandraschko** [comment]
What about using jquery.on instead of element.addEventListener in PrimeFaces.csp.register?

**Comment by melloware** [comment]
Oh I am OK with that I just assumed you were attaching it to the DocumentListener for a reason!

**Comment by tandraschko** [comment]
@melloware fixed it
if you test some other cases, it would be great

**Comment by melloware** [comment]
This is a great fix!  I will poke around with it.  I think our last remaining CSP issue is whether we want to allow whitelists or not: https://github.com/primefaces/showcase-facelift/issues/39

**Comment by tandraschko** [comment]
Not sure :D
PrimeFaces.current().executeScript() is currently broken. I investigate....

**Comment by melloware** [comment]
OK I have confirmed the Spinner issue is fixed and the Confirm Dialog issue is fixed in IE, Edge, Firefox, and Chrome!

**Comment by tandraschko** [comment]
great!
also fixed the #executeSCript thing now. Would be great if someone could really go through the showcase with enabled CSP and check everything....

**Comment by melloware** [comment]
I have been running the showcase solely with CSP=true so anytime I am using it its with CSP.

**Comment by melloware** [comment]
I have searched the entire codebase and there are no other calls to "new Function()" so that is good however there is 1 place still calling `$.globalEval` which is in the file `0-jquery.iframe-transport.js`.  I think we need to switch that call to our `PrimeFaces.csp.eval` call to be safe?
