### ISSUE TITLE
inputTextarea: autocomple only append remain number of words but not replace all with the chosen one

### ISSUE THREAD

**Issue by easttall** [primefaces/primefaces#5184]
## 1) Environment
- PrimeFaces version: 5.3, 6.2 & 7.0
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: tomcat 7
- Affected browsers: chrome 77, IE 11, Firefox 69

## 2) Expected behavior
key in some words to textarea, for example 234
show the suggestion list, for example 1234, 12345, 123456, 1234567
choose one of these, for example 123456
the textarea value become 123456

## 3) Actual behavior
key in some words to textarea, for example 234
show the suggestion list, for example 1234, 12345, 123456, 1234567
choose one of these, for example 123456
the textarea value become 234456
..

## 4) Steps to reproduce
key in some words to textarea, for example 234
show the suggestion list, for example 1234, 12345, 123456, 1234567
choose one of these, for example 123456
the textarea value become 234456
.. 

## 5) Sample XHTML
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
		<h:form id="registerForm" enctype="multipart/form-data">
			<h:panelGroup id="issuePanel">
				<p:inputTextarea rows="5" cols="50" maxlength="2000" 
					id="inputText1" value="#{testView.text1}" 
					completeMethod="#{testView.getSuggestion}" queryDelay="500" >
				</p:inputTextarea>
			</h:panelGroup>
		</h:form>

    </h:body>
</html>

## 6) Sample bean
package org.primefaces.test;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.ArrayList;
import java.util.List;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

private String text1;

@PostConstruct  
    public void init() { }

   public String getText1(){
		return text1;
	}
	
	public void setText1(String text1){
		this.text1=text1;
	}
	
	public List<String> getSuggestion(String query) {
        List<String> results = new ArrayList<String>();
         
        System.out.println("getSuggestion('"+query+"')");
        
        String[] s = new String[]{"1234","12345","123456","1234567"};
        
        results.add(s[0]);
        results.add(s[1]);
        results.add(s[2]);
        results.add(s[3]);
         
        return results;
    }
}

..
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/3650930/primefaces-test.zip)

**Comment by melloware** [comment]
Thank you for the reproducer!  Let me investigate.

**Comment by melloware** [comment]
Submitted a patch.  If you need this fix right now in your code just add this JS to your page.

```javascript
PrimeFaces.widget.InputTextarea.prototype.bindDynamicEvents = function() {
        var _self = this;

        //visuals and click handler for items
        this.items.on('mouseover', function() {
            var item = $(this);

            if(!item.hasClass('ui-state-highlight')) {
                _self.items.filter('.ui-state-highlight').removeClass('ui-state-highlight');
                item.addClass('ui-state-highlight');
            }
        })
        .on('click', function(event) {
            var item = $(this),
            itemValue = item.attr('data-item-value'),
            selectionStart = _self.jq.getSelection().start,
            queryLength = _self.query.length;

            _self.jq.focus();

            _self.jq.setSelection(selectionStart-queryLength, selectionStart);
            _self.jq.replaceSelectedText(itemValue);

            _self.invokeItemSelectBehavior(event, itemValue);

            _self.hide();
        });
    };
```

**Comment by easttall** [comment]
> ```js
> PrimeFaces.widget.InputTextarea.prototype.bindDynamicEvents = function() {
>         var _self = this;
> 
>         //visuals and click handler for items
>         this.items.on('mouseover', function() {
>             var item = $(this);
> 
>             if(!item.hasClass('ui-state-highlight')) {
>                 _self.items.filter('.ui-state-highlight').removeClass('ui-state-highlight');
>                 item.addClass('ui-state-highlight');
>             }
>         })
>         .on('click', function(event) {
>             var item = $(this),
>             itemValue = item.attr('data-item-value'),
>             selectionStart = _self.jq.getSelection().start,
>             queryLength = _self.query.length;
> 
>             _self.jq.focus();
> 
>             _self.jq.setSelection(selectionStart-queryLength, selectionStart);
>             _self.jq.replaceSelectedText(itemValue);
> 
>             _self.invokeItemSelectBehavior(event, itemValue);
> 
>             _self.hide();
>         });
>     };
> ```

thanks..

**Comment by sismondi99** [comment]
Hello, l'm facing the same problem and l'd like to know if there is a way to resolve it.

Thank you.

**Comment by melloware** [comment]
@sismondi99 that was fixed years ago in 8.0.  What version of PF are you using?

**Comment by sismondi99** [comment]
Thanks for your reply. I'm using the 7.0

**Comment by melloware** [comment]
yep fixed in 8.0 or higher...

**Comment by sismondi99** [comment]
So for 7.0, is there a solution

**Comment by melloware** [comment]
No.
