### ISSUE TITLE
DatePicker: pattern messed with LocalDateTime and showTime="true"

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#5186]
## 1) Environment
- PrimeFaces version: trunk
- Application server + version: jetty 9.20
- Affected browsers: all

## 2) Expected behavior
The user-provided pattern is not modified.

## 3) Actual behavior
HH:mm is added to the pattern, causing conversion errors.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
```xhtml
<h:form>
	<div>
		<p:outputLabel for="date1" value="Date1" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date1" value="#{testViewCdi.date1}" showTime="true"/>
		<p:message for="date1"/>
	</div>
	<div>
		<p:outputLabel for="date2" value="Date2" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date2" value="#{testViewCdi.date2}" showTime="true" pattern="dd/MM/yy HH:mm"/>
		<p:message for="date2"/>
	</div>
	<div>
		<p:outputLabel for="date3" value="Date3" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date3" value="#{testViewCdi.date3}"/>
		<p:message for="date3"/>
	</div>
	<div>
		<p:outputLabel for="date4" value="Date4" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date4" value="#{testViewCdi.date4}" pattern="dd/MM/yy"/>
		<p:message for="date4"/>
	</div>
	<p:commandButton id="sub" value="submit" update="@form"/>
</h:form>
```

## 6) Sample bean
```java
@Named
@ViewScoped
public class TestViewCdi implements java.io.Serializable {

	private java.time.LocalDateTime date1 = java.time.LocalDateTime.now();

	private java.time.LocalDateTime date2 = java.time.LocalDateTime.now();

	private java.time.LocalDateTime date3 = java.time.LocalDateTime.now();

	private java.time.LocalDateTime date4 = java.time.LocalDateTime.now();

	// getters and setters
}
```

**Comment by NicolaIsotta** [comment]
Additional sub-issue: the ConverterException may not be thrown if the pattern contains time:
https://github.com/primefaces/primefaces/blob/7421d91ab7b4a9e50a49c799a4d1df564ef16158/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java#L205-L207
https://github.com/primefaces/primefaces/blob/7421d91ab7b4a9e50a49c799a4d1df564ef16158/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java#L217-L219
https://github.com/primefaces/primefaces/blob/7421d91ab7b4a9e50a49c799a4d1df564ef16158/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java#L240-L242
`LocalDate.now()` has to be replaced by `LocalDateTime.now()`

**Comment by NicolaIsotta** [comment]
Related to #4625 and #4626

**Comment by christophs78** [comment]
We have to look at BaseCalendarRenderer and CalendarUtils. And test changes against Calendar and DatePicker.
We should add test-methods in DatePickerTest and CalendarUtilsTest.

**Comment by christophs78** [comment]
And we have to look into the clientside JS. (0-datepicker.js)
Methods formatDateTime, formatDate, formatTime.
As far as i remember the clientside-JS can not handle a pattern which includes time. We´ll have to change the clientside-JS too. Or we need to remove HH:mm in DatePickerRenderer when we render dateFormat-attribute.
Question: Is there any other time-pattern than HH:mm which is relevant? If yes -> we have to touch the clientside JS.
And we have to keep in mind, clientside JS is shared with PrimeNG. 
See [https://www.primefaces.org/primeng/#/calendar](https://www.primefaces.org/primeng/#/calendar)
PrimeNG calendar only supports dateFormat.

**Comment by NicolaIsotta** [comment]
IMHO the easiest and best solution is the server-side only:

1. If the user provides a pattern and if the pattern contains a time part, remove the part
2. This "cleaned" pattern will be passed by the widget builder
3. if showTime is true, generate a time pattern from the datepicker attributes (hourFormat and showSeconds)
4. Combine the "clean" pattern and the generated time pattern to create a "full" pattern. This one will be used to convert the value

**Comment by NicolaIsotta** [comment]
Created PR #5191 
Feel free to test and review

**Comment by mertsincan** [comment]
Hi @NicolaIsotta,

Why do you remove time patterns?
```
@Override
    public String calculateWidgetPattern() {
        return CalendarUtils.removeTime(super.calculatePattern());
    }
```
Exp;
```
<p:datePicker id="timeonly" value="#{calendarView.date14}" timeOnly="true" pattern="HH:mm" maxdate="#{calendarView.maxDate}"/>
```
MaxDate is empty string on the widget's script.

**Comment by NicolaIsotta** [comment]
User-provided time pattern is ignored because it's evaluated from the component properties:
https://github.com/primefaces/primefaces/blob/dbf4a3759045ad77920c9174480d9015d526abaa/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java#L407-L421
I'll check why this case is not working.

**Comment by NicolaIsotta** [comment]
Ok now I remember. This is the function used to parse `mindate` and `maxdate`:
https://github.com/primefaces/primefaces/blob/ac15b2b3d605d711afdeef79702bb19ad0e35150/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L135-L142
In time-only datepickers `dateFormat` is always empty, so `mindate` and `maxdate` are not supported.

**Comment by NicolaIsotta** [comment]
I found a fix, PR coming

**Comment by NicolaIsotta** [comment]
PR: #5313
