### ISSUE TITLE
CSP: Not working in MS Edge

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5189]
In the Console it is reporting: 

> CSP14312: Resource violated directive 'script-src 'nonce-ZGEyMTlhODAtMjY4Yi00OTMyLWIwMTAtM2E5YjcxMThlMzMy'' in Content-Security-Policy: http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=7.1-SNAPSHOT. Resource will be blocked.

See this post for why: https://github.com/elastic/kibana/issues/30988#issuecomment-463786740

Apparently CSP is broken in Edge and Microsoft probably won't fix it until they release their new browser.   So the questions are:

1. Should we fix it like that post IF browser is Edge add all those unsafe directives?

2. Should we just do nothing since all the other browsers work and leave Edge unsupported until they fix the issue?

**Comment by tandraschko** [comment]
+1 for 1

**Comment by melloware** [comment]
Actually found a better fix that is working in all browsers and supported by Microsoft Edge 44.18362.329.0
