### ISSUE TITLE
Dialog Framework: Closing dialog doesn't work when in iframe

### ISSUE THREAD

**Issue by beikov** [primefaces/primefaces#5193]
I'm on Primefaces 7.0 and this issue is related to https://github.com/primefaces/primefaces/issues/1403 and https://github.com/primefaces/primefaces/issues/1776

I have a JSF page that contains an iframe with a JSF page as src. The nested JSF page now opens a dialog, which works, but when closing, it tries to find the sourceWidget which it can't because the dialog is attached to the root window, but the sourceWidget is in a sub-frame.

main.xhtml
```
<iframe src="some.xhtml"></iframe>
```

some.xhtml
```
<p:commandButton value="open dialog" actionListener="#{bean.openDialog()}"/>
```

dialog.xhtml
```
<p:commandButton value="close dialog" actionListener="#{bean.closeDialog()}"/>
```

Bean.java
```
public void openDialog() {
  PrimeFaces.current().dialog().openDynamic("dialog.xhtml", options, null);
}

public void closeDialog() {
  PrimeFaces.current().dialog().closeDynamic(null);
}
```

Here the sourceWidget is `undefined`: https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.dialog.js#L165

I'm not sure how this could be fixed, maybe capture the frame position of the source widget and resolve the frames form the root?

**Comment by melloware** [comment]
I created this test case: 
[pf-5193.zip](https://github.com/primefaces/primefaces/files/3659350/pf-5193.zip)

Just run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/main.xhtml

it looks like it is working fine for me.

**Comment by beikov** [comment]
I think the main.xhtml should also use a Primefaces component so that it gets the `PF` initialized in the window.

**Comment by melloware** [comment]
I am not quite sure what you mean.  Can you just paste a full main.xhtml that you think would exhibit the behavior?

**Comment by beikov** [comment]
Sure, just add a PF component so that the JS Object `PrimeFaces` is setup on the main window.

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
<p:commandButton value="Some button"/>
<iframe src="some.xhtml"></iframe>

    </h:body>
**</html>**
```

**Comment by melloware** [comment]
Done.  Still working fine for me.  Attached test case: 
[pf-5193.zip](https://github.com/primefaces/primefaces/files/3659553/pf-5193.zip)

**Comment by beikov** [comment]
That is by coincidence because the components have the same id/widgetVar...
Use the following main.xhtml to reproduce it

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

	<h:head>
		<title>PrimeFaces Test</title>
	</h:head>
	<h:body>
		<h:form>
			<p:commandButton id="btn" widgetVar="btnVar" value="Some button"/>
		</h:form>
		<iframe src="some.xhtml"/>
	</h:body>
</html>
```

**Comment by melloware** [comment]
OK that finally makes the bug appear: 
[pf-5193.zip](https://github.com/primefaces/primefaces/files/3659796/pf-5193.zip)

**Comment by melloware** [comment]
Not quite sure how to fix this one.  Looping over all available Iframes and Windows until you find the one the widget lives in? Not even sure that is possible.

**Comment by beikov** [comment]
You could capture the path from the root window to the source widget when creating the iframe for the dialog and uses that to determine the source widget object.

**Comment by melloware** [comment]
Any chance you want to take a shot at it and if you get it working either submit a PR or paste the code here and I can submit it?

**Comment by beikov** [comment]
Let's see, I'll give it a shot

**Comment by beikov** [comment]
There you go: https://github.com/primefaces/primefaces/pull/5204

**Comment by melloware** [comment]
I think this is the exact same issue: https://github.com/primefaces/primefaces/issues/2086
