### ISSUE TITLE
Chart (jqPlot): Disable series strikes-through wrong series in legend (combined with stacked-feature)

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5198]
1. Visit current showcase, e.g. bar-chart (Horizontal and Stacked) https://www.primefaces.org/showcase/ui/chart/bar.xhtml
2. - Click on "Boys" (blue series) in legend => blue series is removed, but "Girls" is striked-through
    - Click on "Girls" (yellow series) in legend => yellow series is removed, but "Boys" is striked-throug

This is reported as [jqplot#177](https://github.com/jqPlot/jqPlot/issues/177).

PR for primefaces is coming.

**Comment by melloware** [comment]
Don't forget to update jqplot.txt that is in that folder mentioning this ticket and the patch being applied.

**Comment by fanste** [comment]
Thanks for the info.

PR #5199
