### ISSUE TITLE
Dialog Framework: DialogReturn event for Menuitem

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#52]
In addition to commandButton and commandLink, also add dialogReturn event for menuitem.

**Comment by Rapster** [comment]
We plan to move to DF in the next few months. We open a lot of dialog through menu items, do you have an idea when this feature could be achieved?

**Comment by mhmghanem** [comment]
When will this feature be added ?

**Comment by tandraschko** [comment]
No plans.
Feel free to sponsor it via PrimeFaces PRO.

**Comment by mdzaebel** [comment]
Now - >3 years after reporting - it might be usefull to document the workaround in the User Guide
