### ISSUE TITLE
PickList: Getting instance of transferred object

### ISSUE THREAD

**Issue by e-reznik** [primefaces/primefaces#5205]
## 1) Environment
- PrimeFaces version: 7.0

## 2) Expected behavior
When an element (entry in the PickList) has been transferred, I want to get an instance of that element.

## 3) Actual behavior
After being invoked after a transfer event, I can get a list of the transferred objects by `event.getItems() `
The element in that list is of type `String` and as value it has the actual transferred object: `com.project.model.MyObj@25or385f`
Instead of type `String`, I need the actual type of the transferred object, in my case its `MyObj`
A simple cast like `List<MyObj> list = event.getItems()` is not possible.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
```
<p:pickList id="games" value="#{controller.model}" var="obj" itemValue="#{obj}" itemLabel="#{obj.name}">
    <p:ajax event="transfer" listener="#{controller.onTransfer}" />
</p:pickList>
```

## 6) Sample bean
```
public void onTransfer(TransferEvent event) {
    List<?> list = event.getItems();
    for (Object o : list) {
        MyObj obj1 = (MyObj) o;
        System.out.println(o.getName);
    }
}
```

**Comment by melloware** [comment]
@e-reznik Have you researched this issue for a possible fix?  Interested in submitted a PR?

**Comment by tandraschko** [comment]
Thats already supported if you use a converter. Just look at the second example in the showcase.
