### ISSUE TITLE
Serenity static vertical menu and PrimeFaces >= 7.

### ISSUE THREAD

**Issue by kec-ebranchekoden** [primefaces/primefaces#5206]
Please see:

https://forum.primefaces.org/viewtopic.php?f=73&t=57972
https://forum.primefaces.org/viewtopic.php?p=177694#p177694
https://forum.primefaces.org/viewtopic.php?f=73&t=59136

For a detailed description of the issue.

**Comment by melloware** [comment]
@mertsincan can you check this one since is premium theme related?

**Comment by tandraschko** [comment]
WIll close it. This is for the PrimeFaces community and we can't handle it here.

I will ping mert why we don't have an issue tracker for and if he can reply in the forum.

**Comment by mertsincan** [comment]
Yes, please use forum for such Layout issues. 

In the forum, I'll check your issue and get back to you. 

Best Regards,
