### ISSUE TITLE
selectCheckboxMenu: Callback for remove items when using "multiple='true'"

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#5207]
## 1) Environment
- PrimeFaces version: 7.0

## 2) Expected behavior
I have a very special use of the selectCheckboxMenu. For performance reasons I don't use the "onChange" callback because the user is able to check multiple entries in the menu. So I decided to use the "onHide" callback. When the user is hiding/closing the selection I reload my data. But there is a problem for me: I have the parameter "multiple" on the setting "true". In the closed selectCheckBoxMenu the items are now displayed together with an "x" icon at the end to remove the item selection without opening the whole menu. Because of this situation, if the user removes an item with a click on the "x" the item gets removed from the list but I dont get any information about it (no callback). Using the onChange is no option for me. I would need an callback for "onMultipleRemove" that reacts when removing an item from the "multiple" handling of the component.

![grafik](https://user-images.githubusercontent.com/56062437/66022492-781c9800-e4ee-11e9-8aec-b7e1b6502674.png)

## 3) Actual behavior
none

## 4) Steps to reproduce
none

## 5) Sample XHTML
<p:selectCheckboxMenu multiple="true" onHide="executeOnOnHide();">

## 6) Sample bean
none

**Comment by melloware** [comment]
For now add this to your page.  This will fire your onHide="" callback whenever the "X" is pressed on one of the token labels to remove it.

```javascript
PrimeFaces.widget.SelectCheckboxMenu.prototype.bindMultipleModeEvents =  function() {
        var $this = this;
        this.multiItemContainer = this.jq.children('.ui-selectcheckboxmenu-multiple-container');

        var closeSelector = '> li.ui-selectcheckboxmenu-token > .ui-selectcheckboxmenu-token-icon';
        this.multiItemContainer.off('click', closeSelector).on('click', closeSelector, null, function(e) {
            var item = $this.items.filter('[data-item-value="' + $(this).parent().data("item-value") +'"]');
            if(item && item.length) {
                if($this.cfg.dynamic && !$this.isDynamicLoaded) {
                    $this._renderPanel();
                }

                $this.uncheck(item.children('.ui-chkbox').children('.ui-chkbox-box'), true);
                $this.hide(true);
            }
            
            e.stopPropagation();
        });
    };
```

**Comment by tandraschko** [comment]
added "itemUnselect" event

**Comment by evgeniyshylko** [comment]
After upgrading to Primefaces 11 this script stopped exceuting onHide callback. 
replacing line $this.hide() with $this.postHide() resolved the issue. 
`PrimeFaces.widget.SelectCheckboxMenu.prototype.bindMultipleModeEvents =  function() {
        var $this = this;
        this.multiItemContainer = this.jq.children('.ui-selectcheckboxmenu-multiple-container');

        var closeSelector = '> li.ui-selectcheckboxmenu-token > .ui-selectcheckboxmenu-token-icon';
        this.multiItemContainer.off('click', closeSelector).on('click', closeSelector, null, function(e) {
            var item = $this.items.filter('[data-item-value="' + $(this).parent().data("item-value") +'"]');
            if(item && item.length) {
                if($this.cfg.dynamic && !$this.isDynamicLoaded) {
                    $this._renderPanel();
                }

                $this.uncheck(item.children('.ui-chkbox').children('.ui-chkbox-box'), true);
                $this.postHide();
            }
            
            e.stopPropagation();
        });
    };`

**Comment by evgeniyshylko** [comment]
> For now add this to your page. This will fire your onHide="" callback whenever the "X" is pressed on one of the token labels to remove it.
> 
> ```js
> PrimeFaces.widget.SelectCheckboxMenu.prototype.bindMultipleModeEvents =  function() {
>         var $this = this;
>         this.multiItemContainer = this.jq.children('.ui-selectcheckboxmenu-multiple-container');
> 
>         var closeSelector = '> li.ui-selectcheckboxmenu-token > .ui-selectcheckboxmenu-token-icon';
>         this.multiItemContainer.off('click', closeSelector).on('click', closeSelector, null, function(e) {
>             var item = $this.items.filter('[data-item-value="' + $(this).parent().data("item-value") +'"]');
>             if(item && item.length) {
>                 if($this.cfg.dynamic && !$this.isDynamicLoaded) {
>                     $this._renderPanel();
>                 }
> 
>                 $this.uncheck(item.children('.ui-chkbox').children('.ui-chkbox-box'), true);
>                 $this.hide(true);
>             }
>             
>             e.stopPropagation();
>         });
>     };
> ```

in Primefaces 11 replace $this.hide() with $this.postHide()

**Comment by melloware** [comment]
@evgeniyshylko this was fixed in 8.0 so this monkeypatch should not be necessary in 11.0?

**Comment by evgeniyshylko** [comment]
@melloware I also expected that it was fixed, but still i didnt find possibility to trigger callback when unselecting (clicking X) on one of selected values. If there is better solution, could you please share.

**Comment by melloware** [comment]
@evgeniyshylko so the `itemUnselect` AJAX event is not working for you?
