### ISSUE TITLE
AjaxStatus: causes JS error on ajax calls

### ISSUE THREAD

**Issue by EugenFischer** [primefaces/primefaces#5208]
Using blockUI component with ajaxStatus on one page cause UnexpectedType error after ajax call is finished.
Error occurs inside BlockUI javaScript, but it's curious why it's called at all. 

## 1) Environment
Cloned [primefaces git project](https://github.com/primefaces/primefaces-test.git)
PrimeFaces version : 7.0 ( also 7.0.7 )
Application server : Jetty, Tomcat 9, Wildfly 17
Browser : IE11, FF69, Chrome77

## 2) Expected behavior

No javaScript errors

## 3) Actual behavior
```
TypeError: c is undefined components.js.xhtml:4:1039
    bindTriggers http://localhost:8080/primefaces-test/javax.faces.resource/components.js.xhtml?ln=primefaces&v=7.0:4
    jQuery 7
    bindToStandard http://localhost:8080/primefaces-test/javax.faces.resource/core.js.xhtml?ln=primefaces&v=7.0:8
    sendEvent http://localhost:8080/primefaces-test/javax.faces.resource/jsf.js.xhtml?ln=javax.faces:1
    response http://localhost:8080/primefaces-test/javax.faces.resource/jsf.js.xhtml?ln=javax.faces:1
    onComplete http://localhost:8080/primefaces-test/javax.faces.resource/jsf.js.xhtml?ln=javax.faces:1
    onreadystatechange http://localhost:8080/primefaces-test/javax.faces.resource/jsf.js.xhtml?ln=javax.faces:1

 ```

## 4) Steps to reproduce

* naviagte to application http://localhost:8080/primefaces-test/test.xhtml
* select input field
* adapt the entered text
* hit tab key, or click outside the input field to execute ajax call 

After ajax call is finished you will find an javascript error in dev-tools of your browser.

## 5) Sample XHTML

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h1>#{testViewCdi.testString}</h1>

        <p:ajaxStatus>
            <f:facet name="error">
                <h:outputText value="Error" />
            </f:facet>
            <f:facet name="success">
                <h:outputText value="Success" />
            </f:facet>
            <f:facet name="default">
                <h:outputText value="Idle" />
            </f:facet>
            <f:facet name="start">
                <h:outputText value="Sending" />
            </f:facet>
            <f:facet name="complete">
                <h:outputText value="Done" />
            </f:facet>
        </p:ajaxStatus>

        <h:form id="form1">
            <p:panel id="group1">

                <h:outputText id="someText" value="#{testViewCdi.testString}"/>

                <br/>

                <h:outputText id="someTextUpdateOnSaveAction" value="#{testViewCdi.testString}"/>

                <br/>

                <h:inputText id="textInput" value="#{testViewCdi.testString}">
                    <f:ajax id="jsfAjax" execute="@this" render=":form1:someText"/>

                </h:inputText>

                <br/>

                <p:commandButton id="submitBtn" value="Save 1" actionListener="#{testViewCdi.someLongRunningOperation}"
                                 update="@form" process="@form"/>

                <p:blockUI id="blockTheAction" block="group1" trigger="submitBtn"/>

            </p:panel>

        </h:form>

    </h:body>
</html>

```

## 6) Sample bean
```Java
package org.primefaces.test;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class TestViewCdi {
    
    private String testString;
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces (from CDI!) !!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

    public void someLongRunningOperation() {
        try {
            Thread.sleep(3000);
        } catch (final InterruptedException e) {
            // should not happen
        }
    }
}

```

**Comment by melloware** [comment]
Thanks for the reproducer!  Let me try it.

**Comment by melloware** [comment]
Actually the link to your clone is not correct? Can you just attach a zip file of your project here without the /target folder?

**Comment by EugenFischer** [comment]
[primefaces-test-clone.zip](https://github.com/primefaces/primefaces/files/3681444/primefaces-test-clone.zip)

**Comment by melloware** [comment]
It works fine if you switch..
```xml
<f:ajax id="jsfAjax" execute="@this" render=":form1:someText"/>
```

To...
```xml
<p:ajax id="jsfAjax" process="@this" update=":form1:someText"/>
```

**Comment by EugenFischer** [comment]
As you can imagin this is just the simpelst example, our applications do use a mix of primefaces and jsf ajax calls so this may solve some cases, but we need a reliable solution for.

Does it make sence to adapt the blockUI method where the error occurs to check first if the parameter exist before access the property? Or will some other side effects happen?

Kind Regadrs
Eugen

**Comment by melloware** [comment]
I think it needs deeper Analysis with F Ajax. But the problem is definitely the mix of f:Ajax with block.  Just checking for that variable and ignoring might make the problem go away but not actually fix the problem.

**Comment by melloware** [comment]
OK I submitted a PR which is harmless and prevents the issue.

**Comment by melloware** [comment]
If you need this fix right now just add this to your JS file that you include on every page.
```javascript
PrimeFaces.widget.BlockUI.prototype.bindTriggers = function() {
        var $this = this;
        
        //listen global ajax send and complete callbacks
        $(document).on('pfAjaxSend.' + this.id, function(e, xhr, settings) {
            if (!settings) {
                return;
            }
            var sourceId = $.type(settings.source) === 'string' ? settings.source : settings.source.name;
            // we must evaluate it each time as the DOM might has been changed
            var triggers = PrimeFaces.expressions.SearchExpressionFacade.resolveComponents($this.cfg.triggers);
            
            if($.inArray(sourceId, triggers) !== -1 && !$this.cfg.blocked) {
                $this.show();
            }
        });

        $(document).on('pfAjaxComplete.' + this.id, function(e, xhr, settings) {
            if (!settings) {
                return;
            }
            var sourceId = $.type(settings.source) === 'string' ? settings.source : settings.source.name;
            // we must evaluate it each time as the DOM might has been changed
            var triggers = PrimeFaces.expressions.SearchExpressionFacade.resolveComponents($this.cfg.triggers);
            
            if($.inArray(sourceId, triggers) !== -1 && !$this.cfg.blocked) {
                $this.hide();
            }
        });
    };
```

**Comment by EugenFischer** [comment]
Nice,
is it possible to get this fix on our primefaces prime account?

**Comment by tandraschko** [comment]
Hmmm. So we just ignore f:ajax now? Not sure if it's a good solution

**Comment by melloware** [comment]
Well I as just offering it up to @EugenFischer because he has a large project he is migrating and needs a solution to get him working.  As for the fix provided it appears during `f:ajax` calls BlockUI is subscribed to
```javascript
$(document).on('pfAjaxComplete.' + this.id, function(e, xhr, settings) {
```

However the `settings` object is always undefined.

**Comment by tandraschko** [comment]
Yeah, but we should try to get it working with f:ajax, not just skipping?

**Comment by melloware** [comment]
Yes we should get `f:ajax` working.    I didn't know where to begin to start looking on why this object is undefined for `f:ajax` but fine for `p:ajax`.  Do you want take a look?

I thought the defensive undefined check on` settings` seemed harmless though.

**Comment by tandraschko** [comment]
i think thats the problem of an bad implemented ajaxStatus.

Instead that the ajaxStatus catches the f:ajax for displaying the ajaxStatus itself, it catches the f:ajax status and resend them as p:ajax events.

I will change this now

**Comment by tandraschko** [comment]
please review.

**Comment by melloware** [comment]
Looks good!

**Comment by Toryn19** [comment]
@EugenFischer https://stackdev.space/questions/handling-exceptions-in-jsf-during-ajax-eventsensuring-proper-exception-handling
