### ISSUE TITLE
Advanced multiple fileupload delete last file with double click removes all files

### ISSUE THREAD

**Issue by olpf** [primefaces/primefaces#521]
Open the fileupload "multiple" in the showcase. Add 3 files. Double click on the "X" button of the last file  and all other files are removed too. Same behaviour if there are more than 3 files but the showcase is limited to 3.
If the fileupload is inside a dialog, even the dialog is closed.Probably a page refresh occurs.
JSF 2.2.11, PF 5.2.6 tested with chrome and FF.

**Comment by olpf** [comment]
If some files are selected for the upload and one of the files is removed by double clicking on the X-button and afterwards the fileupload cancel button is clicked, the double clicked file remains but the ui state is so that there is no selection (e. g. the cancel button is disabled). This is reproducable in the showcase.

**Comment by melloware** [comment]
This appears to be fixed in the latest showcase so closing the issue.
