### ISSUE TITLE
p:dataTable: p:rowExpansion doesn't work with p:columnToggler

### ISSUE THREAD

**Issue by Dasister** [primefaces/primefaces#5211]
## 1) Environment
- PrimeFaces version: 7.0 and below
- Does it work on the newest released PrimeFaces version? Version?: No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source): No
- Application server + version: WildFly 10
- Affected browsers: all known

## 2) Expected behavior
Colspan of expanded row is equal to number of visible columns in dataTable

## 3) Actual behavior
Colspan is not equal to visible number of columns. It leads to this:
![hidden-cols](https://user-images.githubusercontent.com/1691753/66119467-64059300-e5e1-11e9-9a0b-6b23342b95c2.PNG)

## 4) Steps to reproduce
1. Open test page
2. Hide some columns with Column Toggler
3. Expand row

Sample project: [pf-rowexpansion.zip](https://github.com/primefaces/primefaces/files/3685574/pf-rowexpansion.zip)

**Comment by fanste** [comment]
The PR #5349 fixes even some more issues regarding `p:columnToggler` and `p:dataTable`.

I once quickly clicked through using the provided sample project.
@Dasister please test my changes.

**Comment by fmarangon** [comment]
This bugfix caused an issue when using **row expansion** on a **frozen datatable**.

The line 
            **this.updateExpandedRowsColspan();**
in method **init** (**datatable.js**, row **40**) calls **getExpandedRows** which relies on **this.frozenTbody** being already initialized, but at this point method **setupScrolling()** hasn't been called yet (it's called by **this.renderDeferred();** in method init, row **65**)

Should this issue be reopened or should I post another one?

This behaviour is reproducible up to **RC.02**

**Comment by fanste** [comment]
PR #5519
