### ISSUE TITLE
Minification introduces javascript errors

### ISSUE THREAD

**Issue by Faldrian** [primefaces/primefaces#522]
I'm using PrimeFaces 5.2 via maven and stumbled upon the `b is undefined` error (known from other searches I did - with no real solution found).
Since I'm using maven and my project should be buildable using official repositories, I could build my own PrimeFaces-package, but it would be better if this is done right upstream. :)

This is the (beautified) minified javascript that is included in the package downloaded via maven:

```
(function(a) {
        if (a.PrimeFaces) {
              b.debug('PrimeFaces already loaded, ignoring duplicate execution.');
              return
    }
```

If you compare this to the source at 5.2 (not minified), you see the semantic difference and the error the minifier did.
https://github.com/primefaces/primefaces/blob/7a640b825cee43e0f874441df156525bd0321a32/src/main/resources/META-INF/resources/primefaces/core/core.js#L4

`b is not defined`, because it is only set locally inside this function after the initial check and is set inside the scope of this function at the firsts call (and not set anymore when the function is called again).

**Comment by tandraschko** [comment]
Already fixed -> https://github.com/primefaces/primefaces/commit/0c2cd5c2cc0e778c07b6d5ba1230ddbf8bfc4aed#diff-4588c1df59105a4881283bfe70b4cd89

**Comment by Faldrian** [comment]
thanks :) now i have to get the fixes version into maven somehow...

**Comment by cagataycivici** [comment]
5.1.x and 5.2.x have this fix.

**Comment by Faldrian** [comment]
The code I quoted in my report is taken from the primefaces-5.2.jar from the maven repository.
Of course I checked the latest package version (5.2) prior to opening this issue...
