### ISSUE TITLE
JS: Global offon() JQuery function

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5223]
We do a lot of this in the JS code 
 ```javascript
this.tbody.off('click.dataTable-rowclick', rowSelector)
                .on('click.dataTable-rowclick', rowSelector, null, function(e) {
```
where we turn off an event to turn it on to clear the old event.
I would like to add this Jquery function to do this in one step like
```javascript
$.fn.offon = function(events , selector ,data, handler) {
  this.off(events, selector)
       .on(events, selector, data, handler);
}
```
This will then let the code be cleaner with...
```javascript
this.tbody.offon('click.dataTable-rowclick', rowSelector, null, function(e) {
```

**Comment by mertsincan** [comment]
Hi @melloware,

Adding a global method is -1 for me ;( Maybe, you can add it to core.utils.js. This usage can confuse users and they might think this is a method in jquery. In my personal opinion, our codes should be both clean and understandable.

Thanks a lot for your effort ;)

**Comment by tandraschko** [comment]
core.utils makes it unreadable in the widgets IMO.
If would leave it for now then.

**Comment by melloware** [comment]
I understand your points i will close the ticket and PR.  The reason I personally think this is a huge improvement...
**Pros:** 
- Prevent human error in typing when adding off() events
- Easy to switch on() events to offon() without cutting and pasting the block for the off()
- Leverage the power of JQuery and Javascript extensibility
- Reduces boilerplate code
