### ISSUE TITLE
Grid CSS / PrimeFlex: label align-issue with horizontal forms

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5227]
## 1) Environment
- PrimeFaces version: 7.1 (SNAPSHOT)
- Affected browsers: all browsers

## 2) Behavior
Grid CSS and PrimeFlex align labels on the upper left corner. This is not ideal. They should be baselined.
![grafik](https://user-images.githubusercontent.com/10461942/66381836-59207900-e9ba-11e9-8d07-fdd35068a5d7.png)
(Issue is not specific for babylon-theme.)

PrimeFlex offers CSS-class p-align-baseline to get this done right. But this has (at least) issues with SelectOneMenu:
![grafik](https://user-images.githubusercontent.com/10461942/66382081-d3e99400-e9ba-11e9-818c-cde09150ff4e.png)
```
<h3>Responsive (PrimeFlex, p-align-baseline)</h3>
<p:panelGrid columns="4" layout="flex" columnClasses="p-col-12 p-md-3 p-xl-2, p-col-12 p-md-9 p-xl-4, p-col-12 p-md-3 p-xl-2, p-col-12 p-md-9 p-xl-4" contentStyleClass="p-align-baseline ui-fluid">
	<p:outputLabel for="text1" value="Text 1" />
	<p:inputText id="text1" />

	<p:outputLabel for="text2" value="Text 2" />
	<p:inputText id="text2" />

	<p:outputLabel for="date" value="Date" />
	<p:datePicker id="date" showIcon="true" style="width:auto" />

	<p:outputLabel for="checkbox" value="Checkbox" />
	<p:selectBooleanCheckbox id="checkbox" itemLabel="Checkbox" />

	<p:outputLabel for="text3" value="Text " />
	<p:inputText id="text3" />

	<p:outputLabel for="selectOne" value="SelectOne (misaligned)" />
	<p:selectOneMenu id="selectOne">
		<f:selectItem itemLabel="Select One" itemValue="" />
		<f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
		<f:selectItem itemLabel="PS4" itemValue="PS4" />
		<f:selectItem itemLabel="Wii U" itemValue="Wii U" />
	</p:selectOneMenu>
</p:panelGrid>
```

When we look to [Bootstrap](https://getbootstrap.com/docs/4.3/components/forms/#horizontal-form) they solve this issue by offering the CSS-Class .col-form-label which add´s padding-top.

I´m currently not totaly sure what´s the best solution.

**Comment by melloware** [comment]
Not sure if you should open this on the PrimeFlex issues page?  https://github.com/primefaces/primeflex/issues

**Comment by christophs78** [comment]
I don´t think this is something primeflex can solve.
p-align-baseline uses CSS property align-items: baseline. This may work for native browser html-(input-)elements, but not for custom components drawn via a UI-component-library.
I´ll give it a try in babylon-forum.

**Comment by christophs78** [comment]
[https://forum.primefaces.org/viewtopic.php?f=98&t=60180](https://forum.primefaces.org/viewtopic.php?f=98&t=60180)

**Comment by christophs78** [comment]
@mertsincan came up with the following idea:
```
<style type="text/css">
   .customPanelGrid .ui-panelgrid-content {
            align-items: center;
    }
</style>

<p:panelGrid columns="4" layout="flex" columnClasses="p-col-12 p-md-3 p-xl-2, p-col-12 p-md-9 p-xl-4, p-col-12 p-md-3 p-xl-2, p-col-12 p-md-9 p-xl-4" styleClass="customPanelGrid">
```

This is not pixel-perfect but quite good:
![grafik](https://user-images.githubusercontent.com/10461942/66774801-c9e7f980-eec2-11e9-99fe-c1280356061b.png)

**Comment by melloware** [comment]
@christophs78 where are we with this ticket?

**Comment by christophs78** [comment]
Hm... We have the project-specific solution, we included into the showcase.
Do we want to add something to PrimeFaces OOTB? Or do we want do write a note into the documentation?
IMO this ticket ist not really "finished".

**Comment by melloware** [comment]
@christophs78 I say we write a note in the documentation and then close this ticket.

**Comment by melloware** [comment]
Assigned to you @christophs78 whether you want to add the documentation or close this ticket.
