### ISSUE TITLE
Wrong legend color position in exporter jqplot chart.

### ISSUE THREAD

**Issue by robertoferreirajrr** [primefaces/primefaces#5234]
Charts: Wrong position when use export component

Hi! When I export a charts to a png, the legends of the chart appears in wrong position! In the showcase it happens too!... I using primefaces 7.0, i see that in show case the version is 7.1, and still happening... the problem occurs in showcase... 

![Image of Problem](https://i.ibb.co/N7nmd0v/Deepin-Screenshot-selecionar-rea-20190704091618.png)

In the past you have fix this here: #4967 but the problem goes back!

PS.: I have edited my project changing the lines like fix related in issue #4967, the fix only works when legends have just one column, if have two or more columns the legend position stills wrong...

## 1) Environment
- PrimeFaces version: Running PrimeFaces-7.1-SNAPSHOT on Mojarra-2.3.2, showcase is affected by this issue.
- Affected browsers: Tested in Chrome, Firefox

## 2) Expected behavior

Rigth legend colors position by side of legend text

## 3) Actual behavior

Wrong legend colors position

## 4) Steps to reproduce

1 - open showcase at https://www.primefaces.org/showcase/ui/chart/export.xhtml
2 - click in the export button

**Comment by mertsincan** [comment]
Hi @robertoferreirajrr, 
I'll try it with elite versions and get back to you.

**Comment by tandraschko** [comment]
Please follow the issue template. Does it work with trunk/7.1-SNAPSHOT?

**Comment by robertoferreirajrr** [comment]
> Please follow the issue template. Does it work with trunk/7.1-SNAPSHOT?

Hi @tandraschko , updated following the issue template

**Comment by melloware** [comment]
Adding @fanste because of knowledge of jqPlot and the current legend fix he has out there.

**Comment by tandraschko** [comment]
The showcase hosted by PrimeTek may never be up to date, so please try it in a sample, your application or checkout the showcase

**Comment by fanste** [comment]
@melloware I won't call it knowledge :D

But I checked to showcase hosted by PrimeTek and tandraschko is right. The showcase does not include the fix for #4797.

I run a quick test in one of my applications changing PF to 7.1-SNAPSHOT and the exported image looks fine for me.
![grafik](https://user-images.githubusercontent.com/3531183/66489710-5738e180-eab0-11e9-8db8-08c6da0e949a.png)

**Comment by tandraschko** [comment]
ok, good.

also talked with @mertsincan if they can autodeloy the showcase for trunk nightly at PrimeTek.
Otherwise we may look for alternatives.

**Comment by fanste** [comment]
@tandraschko Maybe it would be enough to include a build date + revision of PF in the footer of the showcase.

**Comment by tandraschko** [comment]
in general it would be great (a PR would be cool!=
but that will not fix the real problem as we have only 1 online showcase
i think we have to differ between stable elite releases and unstable trunk showcase - also in the hosted showcases
