### ISSUE TITLE
Cannot resolve EL variable in h:outputStylesheet

### ISSUE THREAD

**Issue by wklaczynski** [primefaces/primefaces#5242]
When use h:outputStylesheet with primefaces inside body, can not resolve variable.

## 1) Environment
- PrimeFaces version: 7.0
- Wildflay 18.0.0.Final:
- Affected browsers: firefox

## 2) Sample XHTML
```xml
              <p:repeat 
                        value="#{pui_document_form_select.primitives}"
                        var="pval">
                    
                        <h:outputStylesheet
                            library="forms" 
                            name="#{pval.form.namespace}/sys/actions.css"/>  
                        
                        <p:commandButton 
                            styleClass="#{pval.styleClass}"
                            value="#{pval.title}">
                        
                        </p:commandButton>
                    
                    
                    
                    </p:repeat>
```
## 3) Proposed solution.

org.primefaces.renderkit.HeadRenderer.

```java
        //Middle facet
        UIComponent middle = component.getFacet("middle");
        if (middle != null) {
            middle.encodeAll(context);
        }

        //Registered Resources
        UIViewRoot viewRoot = context.getViewRoot();
        List<UIComponent> resources = viewRoot.getComponentResources(context, "head");
        List<String> resorceIds = new ArrayList<>();
        for (int i = 0; i < resources.size(); i++) {
            UIComponent resource = resources.get(i);
            resorceIds.add(resource.getClientId(context));
        }

        if (!resorceIds.isEmpty()) {
            Set<VisitHint> hints = EnumSet.of(VisitHint.SKIP_ITERATION);
            VisitContext visitContext = VisitContext.createVisitContext(context, resorceIds, hints);
            viewRoot.visitTree(visitContext, (VisitContext vc, UIComponent resource) -> {
                if (resource instanceof UIComponent) {
                    try {
                        resource.encodeAll(context);
                    } catch (IOException ex) {
                        throw new FacesException(ex);
                    }
                }
                return VisitResult.ACCEPT;
            });
        }
```

**Comment by tandraschko** [comment]
The issue template has:


# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

**Comment by tandraschko** [comment]
please add a good description and a runnable bean+xhtml. I have no idea what your problem currently is.

**Comment by Rapster** [comment]
I understand what's wrong but please:

1. Follow @tandraschko instructions
1. What makes you so sure EL variable is not resolved?
1. Explain what's wrong with the current code
1. Explain how your patch fix that issue

Understand that, with poor information you're giving, there is no way to consider spending time on this and applying your fix

**Comment by wklaczynski** [comment]
Unfortunately. I have analyzed the problem more. This cannot be solved. The problem is with the majora. Unfortunately "ui: repeat" and "p: repeat" calculate the value "var" much too late to be resolved when rendering head. The head itself does not belong to the component tree. The solution doesn't help. The problem has no solution. Head can only take static values. The only exception is the composite component, but also with restrictions. Please close the problem.

**Comment by tandraschko** [comment]
Yep, i see. Next time please post more code.
I think supporting simple EL is no problem for us but ui:repeat would be much more work.
