### ISSUE TITLE
SelectManyMenu:deselected values set along with selected ones

### ISSUE THREAD

**Issue by macribbs** [primefaces/primefaces#5246]
The p:selectManyMenu component, when processed, is not correctly reflecting the selections on the view.  I noticed this behavior on one of my views and then confirmed that it acts this way on the **PrimeFaces Showcase** as well.  If a user selects an option, but then clicks another option using a simple click (no other keys used), both options are set in the backing bean when the view is submitted.

## 1) Environment
- PrimeFaces version:  7.0.5
- Application server + version: Tomcat 3.17 Java 1.8
- Affected browsers: Chrome 77.0.3865.90, Safari 13.0.2, Firefox 69.0.2 -- all 64 bit versions

## 2) Expected behavior
When the view is submitted, the values set in the backing bean should reflect only those options that are currently highlighted on the view.

## 3) Actual behavior
If an option is selected, and then subsequently deselected because the user clicked on another option, that first (now unhighlighted) option is set along with the selected one.  Any values that are clicked are accumulated in the setter until the component is updated through an ajax update call.

## 4) Steps to reproduce

- On the PrimeFaces Showcase view, navigate to the SelectManyMenu view
- In the 'Basic' section, select Option 1
- Hit the 'Submit' button and you will see in the dialog box that the selection list shows Option 1.  This is correct.
- Close the dialog.
- Click on Option 2.  On the component this removes the highlighting from Option 1 and leaves only the second one highlighted.
- Click the 'Submit' button and you will see both Option 1 and Option 2 listed as selected.

You can also see this happen if you come into the view and click Option 1, and then click Option 2 (thereby de-selecting Option 1).  When you submit, the dialog opens and you see both options listed as being selected.

This behavior does not occur if you do a similar test on the 'Advanced' section of the view.  If you click on one option and then another, the original clicked option does not show as being selected.

## 6) Sample bean

These are available to you on the PrimeFaces Showcase site, under SelectManyMenu

**Comment by melloware** [comment]
Is your issue this which was fixed in 7.0.6?  https://github.com/primefaces/primefaces/issues/5018

**Comment by macribbs** [comment]
Will download the later version and test.  Thanks very much.

**Comment by melloware** [comment]
Let me know if it fixes your issue and i will close this ticket.

**Comment by macribbs** [comment]
I confirm that it is fixed as of 7.0.6
