### ISSUE TITLE
PanelMenu: missing expand icon 

### ISSUE THREAD

**Issue by Eehol** [primefaces/primefaces#5258]
## 1) Environment
- PrimeFaces version: 7.0
- Application server + version: JBoss EAP 7.1.1.GA (WildFly Core 3.0.12.Final-redhat-1)
- Affected browsers: Chrome 64bits v77.0.3865.120, Internet Explorer v11.1268.16299.0, Firefox 32bits 60.9.0esr, Opera v63.0.3368.107

## 2) Expected behavior

**Context** :
* Use a panelMenu with 3 levels of menu (MainMenu expandable> SubMenu1 expandable > SubMenu2 not expandable)
* Expand all menus by default with expanded="true"

**Expectation** : 
When clicking the collapse-icon of SubMenu1, the submenu should collapse and the icon for expansion should appear.

## 3) Actual behavior

The collapse-icon of SubMenu1 is not displayed. It seems that the CSS class `ui-icon-triangle-1-e` is not added to the `span`. Refresh the page makes the icon appear in some cases, but with a fresh session the icon is never displayed.

## 4) Steps to reproduce

1/ Start a fresh session in your favorite browser.
2/ Acced the page containing the `panelMenu` and collapse SubMenu1
3/ The expand-icon is not displayed
( 4/ press F5, it may sometimes makes the icon appear )

## 5) Sample XHTML

```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head />
<h:body>
	<h:form>
		<p:panelMenu style="width:300px">
			<p:submenu label="MainMenu" expanded="true">
				<p:submenu label="SubMenu1" expanded="true">
					<p:menuitem value="SubMenu2" url="http://www.primefaces.org"/>
				</p:submenu>
			</p:submenu>
		</p:panelMenu>
	</h:form>
</h:body>
</html>
```

## 6) Sample bean

None is necessary.

**Comment by melloware** [comment]
Attached is my test case: 
[pf-5258.zip](https://github.com/primefaces/primefaces/files/3750823/pf-5258.zip)

It is working in PF 7.1-SNAPSHOT I believe because this issue was fixed.
https://github.com/primefaces/primefaces/issues/4958
