### ISSUE TITLE
DataTable: support row editing in responsive mode

### ISSUE THREAD

**Issue by jederfreitas** [primefaces/primefaces#526]
As the post i did in post http://forum.primefaces.org/viewtopic.php?f=23&t=42756, the responsive datatable doesn't support row editing, so i opened this question as a suggestion by aragon to develop that functionality, in my case i have a cell editing, and i use selectBooleanCheckbox to edit bean values.

<img src="http://i58.tinypic.com/1zx146b.jpg"> 

Source code before edit

<img src="http://i61.tinypic.com/1e07cj.jpg"> 

Source code after edit

<img src="http://i59.tinypic.com/nlq2q0.jpg"> 

Code from my datatable:
<img src="http://i62.tinypic.com/dvfypw.png">

**Comment by cagataycivici** [comment]
Editable in responsive is not supported.

**Comment by melloware** [comment]
It looks like this is supported already: https://github.com/primefaces/primefaces/issues/258
