### ISSUE TITLE
Schedule: Upgrade Fullcalendar (4.3.1) 

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5267]
succeeds https://github.com/primefaces/primefaces/issues/4783
Migration-Guide: https://fullcalendar.io/docs/upgrading-from-v3

**Comment by christophs78** [comment]
@melloware : Started to work on this. At this point in time i switched to the new version and got the rendering up and running. I´ll have to put more work on this. (events etc) But i hope to have a complete PR within some weeks. (spare time is limited...)

**Comment by melloware** [comment]
fantastic!  Much appreciated.

**Comment by ProfEibe** [comment]
Will this include the List-View of the calendar-events?
Or is this already in the 3.10 version?

**Comment by christophs78** [comment]
Yes, we will include https://fullcalendar.io/docs/list-view with 4.x.
