### ISSUE TITLE
OmegaMenu: java.lang.NoClassDefFoundError: org/primefaces/context/RequestContext giving error after Prime Faces Upgrade to 7.0 from 6.1.19

### ISSUE THREAD

**Issue by kaushikmeduri** [primefaces/primefaces#5270]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${OmegaMenu}: ${java.lang.NoClassDefFoundError: org/primefaces/context/RequestContext}
  

## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version?  No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version:  Jboss 7.0 
- Affected browsers: All

## 2) Expected behavior

Omega Classes should use new Classes when Prime Faces upgrade happened.

...

## 3) Actual behavior

 

 java.lang.NoClassDefFoundError: org/primefaces/context/RequestContext

13:04:03,911 ERROR [stderr] (default task-25) java.lang.NoClassDefFoundError: org/primefaces/context/RequestContext

13:04:03,911 ERROR [stderr] (default task-25) 	at org.primefaces.omega.component.menu.OmegaMenu.processEvent(OmegaMenu.java:115)

## 4) Steps to reproduce

.. Install Omega on Prime Faces 6.1 https://www.primefaces.org/omega/docs.xhtml

## 5) Sample XHTML
xmlns:po="http://primefaces.org/omega"
.<po:menu 

## 6) Sample bean

..No Java classes required

**Comment by melloware** [comment]
1. You are trying to use an old Omega theme with PF 7.0  

2. You need to log into your Elite account and get the latest Omega Theme which has been updated for PF 7.0.

3. Premium Theme Questions go to forum: https://forum.primefaces.org/viewforum.php?f=40

**Comment by kaushikmeduri** [comment]
Hello,
can you advise where can we get new Omega for Prime Faces 7

**Comment by melloware** [comment]
Log in here with your account and it will be available for you to download: https://www.primefaces.org/store/

Assuming you have purchased it?

**Comment by padupa-eeoc** [comment]
following up on @kaushikmeduri question. we have renewed our elite subscription, but don't see access to the omega template download link.

**Comment by melloware** [comment]
Your Omega subscription should be under the same account you originally purchased it under.  Having an Elite subscription alone is not enough it has to be the account the purchased the Omega template.  If you think you are using the account that purchased the template I would contact PrimeTek @onursenture @mertsincan

**Comment by mertsincan** [comment]
Hi @kaushikmeduri,

You must use Omega 2.0.0 version to work with 7.0. If you are an Elite User, please use "Other" tab under Elite section to download the new version;
![image](https://user-images.githubusercontent.com/11868120/67837516-481de000-fb00-11e9-9396-08cae3711da5.png)

If you encounter any problems with access, please send an email to contact_at_primetek.com.tr

Best Regards,
