### ISSUE TITLE
TextEditor: <li> indentation doesn't work if sanitized even if allowStyles="true"

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#5283]
## 1) Environment
- PrimeFaces version: 7.0.5
- Does it work on the newest released PrimeFaces version? Version? No 
- Does it work on the newest sources in GitHub? Don't think so
- Application server + version: Tomcat 9.0.26
- Affected browsers: All

## 2) Expected behavior
If I use indentation of a bulleted list in p:textEditor, the identation is correctly saved.

## 3) Actual behavior
The indentation is lost.

## 4) Steps to reproduce
Use the indentation buttons in p:textEditoreditor, e.g. in showcase, and then submit.

## 5) Sample XHTML
`<p:textEditor allowBlocks="true" allowFormatting="true" allowImages="true" allowLinks="true" allowStyles="true" ...`

My analysis:
ql-editor saves the indentation e.g. as `<li class=ql-indent-1">`, but the XSS protection in p:textEditor removes it although I specify `allowStyles="true"`.

My solution: I patched HtmlSanitizer by adding "li" to the elements that are allowed to have a "class" attribute. Works well for me.
```
private static final PolicyFactory HTML_STYLES_SANITIZER = Sanitizers.STYLES
	.and(new HtmlPolicyBuilder()
	.allowElements("span", "li")
	.allowAttributes("class")
	.onElements("span", "li")
	.toFactory());
```

**Comment by melloware** [comment]
I agree with you I submitted your fix.

**Comment by joergmattes** [comment]
Thank you!

**Comment by lbroker** [comment]
I see similar issue on Primefaces 8.0, actual test did with PF 8.0.22
tested with text alignment, and it does work with sanitizer.
Tested on PF10, and there is no this issue on PF10 version.

**Comment by jepsar** [comment]
> I see similar issue on Primefaces 8.0, actual test did with PF 8.0.22 tested with text alignment, and it does work with sanitizer. Tested on PF10, and there is no this issue on PF10 version.

@lbroker Please read https://github.com/primefaces/primefaces#community--elite--pro

If it works with the most recent version of PrimeFaces, there isn't much we can do here.
