### ISSUE TITLE
datatable render problem after rowedit with rendered="false" columns

### ISSUE THREAD

**Issue by giorgioprimefaces** [primefaces/primefaces#529]
I am using PF 5.2.8
if I set a column rendered="false" rowedit fails to render datatable (loses last one column)
before:
![screenshot183](https://cloud.githubusercontent.com/assets/4611791/8699478/039bf95e-2b06-11e5-9482-a326e33c10a6.jpg)
after:
![screenshot184](https://cloud.githubusercontent.com/assets/4611791/8699479/03cca1e4-2b06-11e5-976e-03cf891598c7.jpg)

the same happens if I use column toggler, it's even worse! (with or without rendered="false")
![screenshot182](https://cloud.githubusercontent.com/assets/4611791/8699487/2613045a-2b06-11e5-85f2-acc4f6b2a081.jpg)

**Comment by giorgioprimefaces** [comment]
upgraded to PF 5.2.9, still having this problem 
hope it will be fixed soon

**Comment by djmj** [comment]
Workaround:

Use JSTL c:if to render columns conditionally since ui:fragment is just being ignored.

**Comment by giorgioprimefaces** [comment]
thanks djmj, I've just upgraded to 5.2.13 and this problem seems to be fixed
