### ISSUE TITLE
SelectOneRadio: multiple AJAX events on 1 click submitting wrong value

### ISSUE THREAD

**Issue by rvieira5** [primefaces/primefaces#5293]
## 1) Environment
- PrimeFaces version:7.0
- Does it work on the newest released PrimeFaces version? Version? No. 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Apache Tomcat 8.5
- Affected browsers: Chrome, Firefox
- JSF implementation: MyFaces 2.3, Mojarra 2.3

## 2) Expected behavior

When the user selects some option in the page, the backing bean property should be set accordingly. Even when the component tag is surrounded by a `<label>` tag.

## 3) Actual behavior

The option selected by the user is not set correctly in the backing bean.

For some reason, it appears that the `<label>` tag influences the behaviour of the execution flow. If it is removed, the component behaves correctly.

## 4) Steps to reproduce

- Create a page with a h:form containing a p:selectOneRadio surrounded by a `<label>` tag
- Insert two options inside p:selectOneRadio using `<f:selectItem>` tag
- Bind the value property in p:selectOneRadio to a backing bean property
- Use a p:ajax tag inside p:selectOneRadio , and configure the update attribute pointing to some output component to see the current value of the backing bean property
- Select both of the options

## 5) Sample XHTML

```<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:p="http://primefaces.org/ui">

<h:head/>
<h:body>
	<h:form id="testForm">
		<label>Choose an operation:
			<p:selectOneRadio value="#{testView.option}">
				<f:selectItem itemValue="x" itemLabel="Times"/>
				<f:selectItem itemValue="/" itemLabel="Divided by"/>
				<p:ajax update="container"/>
			</p:selectOneRadio>
		</label>
	</h:form>

	<p:outputPanel id="container">
		Current operation is <h:outputText value="#{testView.option}" />
	</p:outputPanel>
</h:body>
</html>
```

## 6) Sample bean

```
package org.primefaces.test;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestView implements Serializable {
    
    private String option;
    
    @PostConstruct  
    public void init() {
        option = "+";
    }

    public String getOption() {
        return option;
    }

    public void setOption(String option) {
        this.option = option;
    }    
}
```

**Comment by melloware** [comment]
I have verified the issue.  Attached is the reproducible test case:
[pf-5293.zip](https://github.com/primefaces/primefaces/files/3793644/pf-5293.zip)

**Comment by melloware** [comment]
I can see in the network traffic when I select the first radio it fires one AJAX event.  When I click the second radio it fires 2 AJAX events the first for "/" the second for "x" which is why its setting the value to "X". 
![image](https://user-images.githubusercontent.com/4399574/67946276-62ff5b80-fbb7-11e9-9b95-af35046bd767.png)

I am not sure why.

**Comment by tandraschko** [comment]
It would be great if someone could so JS debugging and see who triggers the second request.

**Comment by melloware** [comment]
It if firing the valuechange for both. Here are the two ajax calls.

1. Fires the minus sign (-) when I click Minus Radio.
![image](https://user-images.githubusercontent.com/4399574/68120361-1e373580-fed3-11e9-8875-3ebfb1d3945b.png)

2. Immediately fires the times (x).
![image](https://user-images.githubusercontent.com/4399574/68120394-3f982180-fed3-11e9-8b87-2d47947e3f3f.png)

**Comment by tandraschko** [comment]
but who triggers the change event on JS side?
maybe one comes from event bubbling or something...
