### ISSUE TITLE
POM: License information missing

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5294]
We use Sonatype IQ server and its reporting PrimeFaces as missing its license info and marking it as an alert.

![image](https://user-images.githubusercontent.com/4399574/67975314-39135c80-fbea-11e9-9e92-4074ca6cb26f.png)

**Comment by der-tkw** [comment]
Will this also be fixed for the elite version?

**Comment by melloware** [comment]
That's up to @mertsincan whether or not this goes into Elite
