### ISSUE TITLE
Add queryMode attribute to Autocomplete

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#5298]
| Name | Default | Type | Description |
|---|---|---|---|
| queryMode | server | String | Specifies query mode, valid values are "server" (default), "client" and "hybrid".

**Query Modes:**

1. **server** mode;
- When the input field is entered a query value, autocomplete _always_ sends an ajax request to find the new values of the panel. This is the current behavior.
**The affected attributes**;
  1. The _completeMethod_'s type is _List_.

2. **client** mode;
- Firstly, after the page is loaded, autocomplete sends an ajax request to cache the panel's value at the client-side. Then, when the input field is entered a query value, autocomplete _always_ searches it inside the cached data. If autocomplete doesn't find it, the panel is not opened. It never sends an ajax request to find the new values of the panel.
**The affected attributes**;
   1. The _completeMethod_'s type is _Map<String, List<?>>_.
   2. The _cache_ is always true.

3. **hybrid** mode;
- It is similar to client mode. But, if autocomplete doesn't find it, it _always_ sends an ajax request to find the new values of the panel and add them to the cached data. When the same value is entered in the input field again, autocomplete returns the panel's values from the cached data.
**The affected attributes**;
   1. The _completeMethod_'s type is _Map<String, List<?>>_.
   2. The _cache_ is always true.

Exp;
```
public class AutoCompleteView {

    private String txt1;
    private String txt2;
    private String txt3;
    private String txt4;

    public List<String> completeText(String query) {
        List<String> results = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            results.add(query + i);
        }

        return results;
    }

    public Map<String, List<String>> completeQueryMode(String query) {
        Map<String, List<String>> results = new HashMap<>();

        List<String> list = new ArrayList<>();
        for (int i = 0; i < 3; i++) {
            list.add("a" + i);
        }
        results.put("a", list);

        list = new ArrayList<>();
        for (int i = 0; i < 4; i++) {
            list.add("b" + i);
        }

        results.put("b", list);

        return results;
    }

    public Map<String, List<String>> completeHybridQueryMode(String query) {
        Map<String, List<String>> results = new HashMap<>();
        if ("".equals(query)) {
            results = this.completeQueryMode(query);
        } else {
            List<String> list = new ArrayList<>();
            for (int i = 0; i < 3; i++) {
                list.add(query + i);
            }

            results.put(query, list);
        }

        return results;
    }

    /* getters; setters; */
}
```

```
...
<h:form>
    <h:panelGrid columns="2" cellpadding="5">                
        <p:outputLabel value="Server(Default):" for="server" />
        <p:autoComplete id="server" value="#{autoCompleteView.txt1}" completeMethod="#{autoCompleteView.completeText}" />

        <p:outputLabel value="Server with cache=true:" for="server2" />
        <p:autoComplete id="server2" value="#{autoCompleteView.txt2}" cache="true" completeMethod="#{autoCompleteView.completeText}" />

        <p:outputLabel value="Client (the cached keys: 'a' and 'b'):" for="client" />
        <p:autoComplete id="client" value="#{autoCompleteView.txt3}" queryMode="client" completeMethod="#{autoCompleteView.completeQueryMode}" />

        <p:outputLabel value="Hybrid (the cached keys: 'a' and 'b'):" for="hybrid" />
        <p:autoComplete id="hybrid" value="#{autoCompleteView.txt4}" queryMode="hybrid" completeMethod="#{autoCompleteView.completeHybridQueryMode}" />
    </h:panelGrid>
</h:form>
...
```

**Comment by ssibitz** [comment]
Sounds like a nice feature, but why i have to use a 
"stringlist - hashmap" 
for the client/hybrid mode instead of a normal stringlist in the original server - mode ?

Does that mean that i have to build a stringlist/hashmap with all possible queries 
and the values as list which should be shown then for the autocomplete ?

**Comment by Rapster** [comment]
@mertsincan can you please update the showcase?
