### ISSUE TITLE
SelectOneMenu: with required=true and f:SelectItem with itemDisabled=true for empty value prevents ajax update with validation error

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#5299]
## 1) Environment
- PrimeFaces version: **7.0**
- Does it work on the newest released PrimeFaces version? **No**
- Does it work on the newest sources in GitHub? **Not tested**
- Application server + version: **Wildfly 17.0.1.Final**
- Affected browsers: **Tested with Firefox, IE, Edge**

## 2) Expected behavior
Given a p:SelectOneMenu with required=true, with an initial empty value and a f:SelectItem with itemDisabled=true for empty value, it should be possible to update the value via Ajax (regardless if p:ajax or f:ajax) as it is possible with simple h:SelectOneMenu.

## 3) Actual behavior
Unable to change the value because of a validation error (value required).

Interesting side observation: selecting an option of one of the p:SelectOneMenus first, leads to the error. selecting an option of one of the h:SelectOneMenus right after, all menus are updated with the correct value, except the first selected one.

## 4) Steps to reproduce
Select item from one of the menus.

## 5) Sample XHTML
Note the mix of p:SelectOneMenu, h:SelectOneMenu, p:ajax and f:ajax.
```
<!DOCTYPE html>
<html
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:p="http://primefaces.org/ui"
>
<f:view>
  <h:head></h:head>
  <h:body>
    <p:log></p:log>
    <h:form id="form">
      <p:growl>
        <p:autoUpdate></p:autoUpdate>
      </p:growl>
        <p:outputPanel id="subcontainer">
          <p:selectOneMenu
            id="dropdown_prfa"
            value="#{dropdownController.value}"
            required="true"
          >
            <f:ajax
              execute="dropdown_prfa"
              render="subcontainer"
            >
            </f:ajax>
            <f:selectItem
              itemLabel="?"
              itemValue=""
              noSelectionOption="true"
              itemDisabled="true"
            />
            <f:selectItems
              value="#{dropdownController.options}"
              var="option"
              itemLabel="#{option}"
              itemValue="#{option}"
            />
          </p:selectOneMenu>
          <br />
          <p:selectOneMenu
            id="dropdown_prpa"
            value="#{dropdownController.value}"
            required="true"
          >
            <p:ajax
              process="dropdown_prpa"
              update="subcontainer"
            >
            </p:ajax>
            <f:selectItem
              itemLabel="?"
              itemValue=""
              noSelectionOption="true"
              itemDisabled="true"
            />
            <f:selectItems
              value="#{dropdownController.options}"
              var="option"
              itemLabel="#{option}"
              itemValue="#{option}"
            />
          </p:selectOneMenu>
          <br />
          <h:selectOneMenu
            id="dropdown_hrfa"
            value="#{dropdownController.value}"
            required="true"
          >
            <f:ajax
              execute="dropdown_hrfa"
              render="subcontainer"
            >
            </f:ajax>
            <f:selectItem
              itemLabel="?"
              itemValue=""
              noSelectionOption="true"
              itemDisabled="true"
            />
            <f:selectItems
              value="#{dropdownController.options}"
              var="option"
              itemLabel="#{option}"
              itemValue="#{option}"
            />
          </h:selectOneMenu>
          <br />
          <h:selectOneMenu
            id="dropdown_hrpa"
            value="#{dropdownController.value}"
            required="true"
          >
            <p:ajax
              process="dropdown_hrpa"
              update="subcontainer"
            >
            </p:ajax>
            <f:selectItem
              itemLabel="?"
              itemValue=""
              noSelectionOption="true"
              itemDisabled="true"
            />
            <f:selectItems
              value="#{dropdownController.options}"
              var="option"
              itemLabel="#{option}"
              itemValue="#{option}"
            />
          </h:selectOneMenu>
        </p:outputPanel>
    </h:form>
  </h:body>
</f:view>
</html>
```
## 6) Sample bean
```
package org.primfaces.issue;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class DropdownController implements Serializable {

  private static final long serialVersionUID = -6991892064093740746L;

  private String value;

  private List<String> options;

  @PostConstruct
  public void initialize() {
    this.value = "";
    this.options = Arrays.asList("1", "2");
  }

  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public List<String> getOptions() {
    return this.options;
  }

  public void setOptions(List<String> options) {
    this.options = options;
  }
}
```

**Comment by melloware** [comment]
Is this your issue?
https://github.com/primefaces/primefaces/issues/4927

**Comment by irieill** [comment]
Further testing reveals that this issue relies on the itemDisabled property of f:SelectItem set to true. When ommited evething works as expected. Nevertheless my usecase requires this property set to true, and issue still exists for p:SelectOneMenu.

@melloware 
I do not think the linked issue is related. I did not set javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL nor javax.faces.VALIDATE_EMPTY_FIELDS explicitly.

**Comment by melloware** [comment]
understood the real issue is `itemDisabled=true`.

**Comment by melloware** [comment]
Wonder if its related to this:
https://github.com/primefaces/primefaces/issues/1636

**Comment by melloware** [comment]
I wonder if also this line of code is causing the issue in the Java code
```java
if (disabled) {
    writer.writeAttribute("disabled", "disabled", null);
 }
```
Basically its marking it disabled in the browser HTML can you see if the regular h:selectOne marks that "option" as disabled?  I wonder if it has special handling for the noselectoption.

**Comment by irieill** [comment]
I do not know if i understand you correctly. This is the rendered ouptput of the four different select variants
```
<select aria-hidden="true" id="form:dropdown_prfa_input" name="form:dropdown_prfa_input" 
  onchange="mojarra.ab('form:dropdown_prfa',event,'valueChange','form:dropdown_prfa','form:subcontainer')" tabindex="-1">
	<option data-escape="true" disabled="disabled" selected="selected" value="">?</option>
	<option data-escape="true" value="1">1</option>
	<option data-escape="true" value="2">2</option>
</select>

<select aria-hidden="true" id="form:dropdown_prpa_input" name="form:dropdown_prpa_input" 
  onchange="PrimeFaces.ab({s:&quot;form:dropdown_prpa&quot;,e:&quot;valueChange&quot;,f:&quot;form&quot;,p:&quot;form:dropdown_prpa&quot;,u:&quot;form:subcontainer&quot;,ps:true});" tabindex="-1">
	<option data-escape="true" disabled="disabled" selected="selected" value="">?</option>
	<option data-escape="true" value="1">1</option>
	<option data-escape="true" value="2">2</option>
</select>

<select id="form:dropdown_hrfa" name="form:dropdown_hrfa" 
  onchange="mojarra.ab(this,event,'valueChange','form:dropdown_hrfa','form:subcontainer')" size="1">
	<option disabled="disabled" selected="selected" value="">?</option>
	<option value="1">1</option>
	<option value="2">2</option>
</select>

<select id="form:dropdown_hrpa" name="form:dropdown_hrpa" 
  onchange="PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;form&quot;,p:&quot;form:dropdown_hrpa&quot;,u:&quot;form:subcontainer&quot;,ps:true});" size="1">
	<option disabled="disabled" selected="selected" value="">?</option>
	<option value="1">1</option>
	<option value="2">2</option>
</select>
```

**Comment by melloware** [comment]
OK so all of them have `disabled="disabled"` so that is not the problem.  Thanks for checking.

**Comment by irieill** [comment]
I think i have found the problem. It is still the same code in master branch.

- submittedValue is determined correctly
- submittedValues is not determined correctly - it contains the disabled SelectItems value as first item
- which then is choosen as submitted value falsely

https://github.com/primefaces/primefaces/blob/5095fa7ee2b5712ff347435941e0c73388851476/src/main/java/org/primefaces/renderkit/SelectOneRenderer.java#L43-L46

Wrong determination takes place here. If the disabled SelectIem value has been set before it is considered valid/selected. Comments on line 343-345 should hold here too!
https://github.com/primefaces/primefaces/blob/5095fa7ee2b5712ff347435941e0c73388851476/src/main/java/org/primefaces/renderkit/SelectRenderer.java#L341-L350

**Comment by melloware** [comment]
Care to submit a PR?

**Comment by irieill** [comment]
> 
> 
> Care to submit a PR?

Jep

**Comment by tandraschko** [comment]
If we uncomment those lines, other things are broken again
i somewhere commented it.

**Comment by irieill** [comment]
Well - I removed my fix. I am not sure if changing the submitted value order is ok. Additionally I recognized the following doc

https://github.com/primefaces/primefaces/blob/5095fa7ee2b5712ff347435941e0c73388851476/src/main/java/org/primefaces/renderkit/SelectRenderer.java#L299-L306

Which refers to https://github.com/primefaces/primefaces/issues/3296. I think both issues conflict with each other.

**Comment by melloware** [comment]
@irieill Did you settle on a fix?

**Comment by irieill** [comment]
> 
> 
> @irieill Did you settle on a fix?

Jep. https://github.com/primefaces/primefaces/pull/5306 Unfortunately I botched the commit message XD

**Comment by melloware** [comment]
That is OK at least you submitted the PR!
