### ISSUE TITLE
Advanced DataTable filtering fails with Dynamic Columns

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#53]
Using the new filter mechanism in PF5 with Dynamic Columns does not filter.
When debugging (using a lazyDataModel) the filter map is always empty. 

``` xml
<p:dataTable value="#{abc01BackingBean.testList}" var="vo" widgetVar="testTable2">

            <p:columns value="#{abc01BackingBean.columnsList}" var="column"
                       filterBy="#{column.property}">
                <f:facet name="header">
                    #{column.header}
                </f:facet>
                <f:facet name="filter">
                    <h:inputText onchange="PF('testTable2').filter()"/>
                </f:facet>
                <h:outputText value="#{vo[column.property]}"/>
            </p:columns>
        </p:dataTable>
```

**Comment by the86freak** [comment]
is there a known workaround for that issue?

**Comment by mafaul** [comment]
See http://stackoverflow.com/questions/24181130/filter-a-lazy-datatable-with-dynamic-columns/27876091#27876091

**Comment by daniel-armino** [comment]
Cagatay, one question about this error, do you know how version this ticket will be ok? I'm developing an application with datatable colums and dynamic filter on Primefaces 5.2 and this error remains.

**Comment by mafaul** [comment]
Having this issue resolved would really be awesome! Keep up the good work.

**Comment by kkoehler** [comment]
Hi,

we encountered the same problem. Why not integrating the proposed solution from stackoverflow?
I created a pull request for that:
https://github.com/kkoehler/primefaces/pull/1

Kristian

**Comment by kkoehler** [comment]
https://github.com/primefaces/primefaces/pull/930
