### ISSUE TITLE
p:dataTable - p:columnToggler: Number of frozen columns not considered correctly in column toggler

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#5302]
<p:columnToggler>
  Example:
  The JavaScript **PrimeFaces.widget.ColumnToggler** object contains an attribute **frozenColumnCount**, which might not be initialized correctly. Hence the toggled column id is not being sent correctly to the server side in **fireToggleEvent**

To reproduce: 
- Create a data table with **2** frozen columns and a column toggler
- Check the value of the attribute **frozenColumnCount** of the columnToggler widget via browser console or debugger ( PrimeFaces.getWidgetById('<clientIdOfToggler>').frozenColumnCount )
- It will show in my case 1 instead of 2.

## 1) Environment
- PrimeFaces version: 7.0.8

- Application server + version: WildFly 15
- Affected browsers: Tested with Firefox, but supposedly all browsers are affected

Please check in **columntoggler.js**  line 19 (bold). In my view it is not correct.

Excerpt of code:

```javascript
 if(this.hasFrozenColumn) {
            this.thead = $(clientId + '_frozenThead,' + clientId + '_scrollableThead');
            this.tbody = $(clientId + '_frozenTbody,' + clientId + '_scrollableTbody');
            this.tfoot = $(clientId + '_frozenTfoot,' + clientId + '_scrollableTfoot');
           **this.frozenColumnCount = this.thead.eq(0).children('tr').length;**
}
```

Instead I think it should be:
```javascript
 this.frozenColumnCount = this.thead.eq(0).find('th').length;
```

**Comment by melloware** [comment]
Have you tested your fix?

wouldn't it also be wrong in the coltoggler `check()` method as well?

**Comment by wlhUser** [comment]
I did not test the solution as I proposed it, but I applied a equivalent fix in my own js code correcting the value of the attribute **frozenColumnCount** of the columnToggler  widget. This fix works - at least in the cases I tested.

I'm not sure what exactly you mean related to the check() method. But of course the **check** and **uncheck** methods rely on the frozenColumnCount attribute, and behave in a wrong was when its value is incorrect.

**Comment by melloware** [comment]
OK I meant this but it looks like in the check() method of colToggler.js it does this...
https://github.com/primefaces/primefaces/blob/2f8da82feeb8d471ca9fd173455ee6b3f3ad142d/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js#L286-L288

So its using TH appropriately there.

**Comment by melloware** [comment]
Submitted PR

**Comment by wlhUser** [comment]
I did not debug this code you are referring to in the check() method, but I suppose it is correct.
