### ISSUE TITLE
p:calendar shows no shadow, if showOn attribute not set

### ISSUE THREAD

**Issue by mrclBIE** [primefaces/primefaces#532]
I recognized, that there is missing the shadow in my datepicker div. After a short look in the javascript, I´ve seen that the ui-shadow class is only added, if the showOn attribute is not undefined. So I decided to set it actively and then i became the ui-shadow styleclass in the ui-datepicker-div.

I´am using primefaces version 5.2. The code snippet i copied from 5.3-SNAPSHOT.

The shortened code snippet:

``` javascript
if(this.cfg.popup && this.cfg.showOn) {
     PrimeFaces.skinButton(triggerButton);
     $('#ui-datepicker-div').addClass('ui-shadow');
}
```

Regards, 
Marcel

**Comment by cagataycivici** [comment]
Works with 5.3.
