### ISSUE TITLE
Timeline: timeZone and browserTimeZone are ignored when manually set

### ISSUE THREAD

**Issue by sergi-mm** [primefaces/primefaces#5320]
I have an issue using Timeline component in different timezones: we want to force the visualization of the events in an specific timezone, but if we force the timezone in Timeline component, is completely ignored (both _timeZone_ and _browserTimeZone_ parameters). BTW I use Primefaces 7.0.8.

The issue can be simply reproduced using any timeline demo like this: https://www.primefaces.org/showcase/ui/data/timeline/allEvents.xhtml

```
<p:timeline id="timeline" value="#{allEventsTimelineView.model}"
            editable="true" eventMargin="10" eventMarginAxis="0" 
            start="#{allEventsTimelineView.start}" 
            end="#{allEventsTimelineView.end}" 
            timeZone="Europe/Paris"
            browserTimeZone="Europe/Paris">
```

Start the application and access to the app through another device with another timezone on its computer (like American or Asian timezone). You will see that all events will be displaced in time as they are displayed with the device timezone instead of the server timezone as specified.

**Comment by tandraschko** [comment]
@christophs78 can you assist?

**Comment by christophs78** [comment]
@sergi-mm: Can you check this against 8.0-Snapshot? We did some major rework with 8.0. (updated JS-Library; LocalDateTime instead of java.util.Date, ... (see https://github.com/primefaces/primefaces/wiki/Migration-Guide)

**Comment by sergi-mm** [comment]
> 
> 
> @sergi-mm: Can you check this against 8.0-Snapshot? We did some major rework with 8.0. (updated JS-Library; LocalDateTime instead of java.util.Date, ... (see https://github.com/primefaces/primefaces/wiki/Migration-Guide)

Ok, we will check it with 8.0-snapshot version, but I see there are many changes in Timeline so we should refactor and test the code

**Comment by christophs78** [comment]
Think we need to implement https://visjs.github.io/vis-timeline/docs/timeline/#Time_zone in PrimeFaces-Timeline to support this usecase.

**Comment by melloware** [comment]
@jasonex7 any thoughts on this?

**Comment by jasonex7** [comment]
> Think we need to implement https://visjs.github.io/vis-timeline/docs/timeline/#Time_zone in PrimeFaces-Timeline to support this usecase.

I agree with @christophs78. I'm going to make a PR to handle that parameter in vis timeline component.

**Comment by melloware** [comment]
@christophs78 please review the PR before I merge it.
