### ISSUE TITLE
Excel(X)Exporter: Improve performance for huge exports

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5321]
## 1) Environment
- PrimeFaces version: 7.1-SNAPSHOT from the past

## 2) Expected behavior
A datatable with thousands of rows and tens of columns should be exported in a reasonable time.

## 3) Actual behavior
The export takes a really long time and even may crash the application server because of the feature `autoSizeColumn` that is always invoked at the end of the excel export.

A PR is coming that allows to disable this feature (`autoSizeColumn`) using exporter options.

**Comment by fanste** [comment]
PR #5322

**Comment by melloware** [comment]
Introduced an NPE: https://github.com/primefaces/primefaces/issues/5469
