### ISSUE TITLE
DataTable: draggableRows -> wrong value sent to view after reordering

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#5326]
## 1) Environment
- PrimeFaces version: 7.0.9
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: WildFly 10.1.0
- Affected browsers: All

## 2) Expected behavior
After dragging and reordering rows in a DataTable the currently displayed value is sent to the view by an action.

## 3) Actual behavior
After dragging and reordering rows in a DataTable the value previously at this position is sent to the view by an action.

![image](https://user-images.githubusercontent.com/8350714/68762260-1cc5e580-0616-11ea-9ead-1f609ff90689.png)

## 4) Steps to reproduce
Click on the commandButtons to confirm that "1" displays the growl message for TestValue with id 1 and so on. Reorder a row. Click on the commandButtons to confirm that the growl message displays the TestValues still in the 1,2,3 order and not in the order displayed after reordering the rows.

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
    <title>PrimeFaces Test</title>
</h:head>
<h:body>

    <h1>#{testView.testString}</h1>

    <h:form>

        <p:dataTable value="#{testView.testValues}"
                     draggableRows="true"
                     var="testValue">

            <p:column>
                <h:outputText value="#{testValue.id}: "/>
                <p:commandButton action="#{testView.testAction(testValue)}"/>
            </p:column>

        </p:dataTable>

        <p:growl life="8000">
            <p:autoUpdate/>
        </p:growl>

    </h:form>

</h:body>
</html>
```

## 6) Sample bean
```
package org.primefaces.test;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Named
@ViewScoped
public class TestView implements Serializable {

    private String testString;
    private List<TestValue> testValues;

    @PostConstruct
    public void init() {
        testString = "Welcome to PrimeFaces!!!";

        testValues = new ArrayList<>();
        testValues.add(new TestValue(1));
        testValues.add(new TestValue(2));
        testValues.add(new TestValue(3));
    }

    public void testAction(TestValue testValue) {
        FacesContext.getCurrentInstance().addMessage("id", new FacesMessage(testValue.toString()));
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

    public List<TestValue> getTestValues() {
        return testValues;
    }

    public void setTestValues(List<TestValue> testValues) {
        this.testValues = testValues;
    }

    public class TestValue {
        private int id;

        public TestValue(int id) {
            this.id = id;
        }

        public int getId() {
            return id;
        }

        @Override
        public String toString() {
            return "TestValue{" +
                    "id=" + id +
                    '}';
        }
    }
}
```

Please see the attached test project, cloned from the primefaces-test.git.
[datatable-draggablerows-test.zip](https://github.com/primefaces/primefaces/files/3839991/datatable-draggablerows-test.zip)

**Comment by melloware** [comment]
Is this similar to this issue?  https://github.com/primefaces/primefaces/issues/1499

**Comment by mkomko** [comment]
It sounds like it is probably related, but I can't be sure. Also, I just couldn't believe that it's still the same bug after all these years?

**Comment by melloware** [comment]
Things only get fixed if...

A) you yourself or an open source committer dedicates time to fixing an issue and submitting the fix
B) You pay PrimeTek for the one time bug fix
C) You pay for PrimeTek Pro support

**Comment by melloware** [comment]
Can you try your sample above using the trick they suggested the `<p:ajax event="rowReorder" update="@this"/>` to the datatable?

**Comment by mkomko** [comment]
> Things only get fixed if...
> 
> A) you yourself or an open source committer dedicates time to fixing an issue and submitting the fix
> B) You pay PrimeTek for the one time bug fix
> C) You pay for PrimeTek Pro support

I see! Surprising that no Pro customer had the problem yet :-).

> Can you try your sample above using the trick they suggested the `<p:ajax event="rowReorder" update="@this"/>` to the datatable?

That does indeed work!

**Comment by melloware** [comment]
OK let me see if I can fix it for good but at least you have a workaround!

**Comment by mkomko** [comment]
Thank you! That StackOverflow answer sounds like a good analysis of the problem: https://stackoverflow.com/a/33911857/10157328

**Comment by melloware** [comment]
Also it looks like you can use `rowStatePreserved="true"`. Closing this ticket for now as there are provided solutions

**Comment by rider87** [comment]
Can you please fix that in the core PF version?
`rowStatePreserved="true"` was also not working for me.

Please see also my forum post:
https://forum.primefaces.org/viewtopic.php?f=3&t=63298&p=184578#p184578

**Comment by melloware** [comment]
@rider87 can you download this reproducer: 
[pf-5326.zip](https://github.com/primefaces/primefaces/files/5201390/pf-5326.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml and follow the steps in the original post you will see the bug.

Then stop the reproducer and add
```xml
<p:ajax event="rowReorder" update="@this"/>
```
to the Datatable and re-run you will see the issue is fixed.

**Comment by rider87** [comment]
@melloware , please find attached....
[pf-5326_new.zip](https://github.com/primefaces/primefaces/files/5201895/pf-5326_new.zip)

![image](https://user-images.githubusercontent.com/9787533/92734320-bb2af080-f378-11ea-870b-6feedf68d28f.png)

**Comment by melloware** [comment]
Thank for the reproducer let me debug!

**Comment by melloware** [comment]
@rider87 I fixed your code using PF 8.0.  See the code and give it a shot...
[pf-5326-fixed.zip](https://github.com/primefaces/primefaces/files/5202026/pf-5326-fixed.zip)

**Comment by rider87** [comment]
Oh @melloware thank you so much. It´s working fine. Many many thanks!!!

**Comment by melloware** [comment]
No problem I discovered this note in the PrimeFaces code:
```java
 LOGGER.info("Row reordering is only available for list backed datatables, "
                        + "use rowReorder ajax behavior with listener for manual handling of model update.");
```

Which basically means if you are using `rowReorder` you have to handle manipulating the List yourself! Glad I could help.

**Comment by stolp** [comment]
So perhaps this should better read:

```
 LOGGER.info("Row reordering is only available for list backed datatables, "
                        + "use rowReorder ajax behavior with listener and manually handle the model update.");
```
The initial sentence suggests to me that there is also a non-manual way to handle this. I am not a native speaker though.

**Comment by melloware** [comment]
agreed I updated my PR with this wording change.

**Comment by rider87** [comment]
As discussed in the forum:
[primefaces_datatable.zip](https://github.com/primefaces/primefaces/files/5228020/primefaces_datatable.zip)

**Comment by melloware** [comment]
The workaround provided is the solution desired by PrimeTek not to break other functionality.

**Comment by klaros-testmanagement** [comment]
Just an idea, but wouldn't it make sense to provide a working example in the showcase or an explanation in the documentation for this (and similar) problem regarding drag & drop, input fields and datatable?
