### ISSUE TITLE
dataTable: filtering with dynamic id not working

### ISSUE THREAD

**Issue by neXus1987** [primefaces/primefaces#5327]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 8.5
- Affected browsers: Chrome/Firefox

## 2) Expected behavior
When i filter the datatable without a dynamic id it works. When i set the id of the datatable with a value from a model, e.g. an id -> id="tblObjects#{model.object.id}" -> tblObjects1 or tblObjects2 it should also filter as without dynamic ids.

## 3) Actual behavior
nothing happens, the data in the datatable is still the same. 

## 4) Steps to reproduce
just filter the datatable

## 5) Sample XHTML

<p:dataTable value="#{adminModel.listString}"
				id="tblObjects#{adminModel.id}"
				filteredValue="#{adminModel.listStringFiltered}" var="n">
				<p:column sortBy="#{n}" filterBy="#{n}">
							 #{n}
				</p:column>
</p:dataTable>

## 6) Sample bean
@Named
@ViewScoped
public class AdminModel implements Serializable{
	private Integer id=1;
	private List<String> listString;
	private List<String> listStringFiltered;
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public List<String> getListString() {
		if(listString==null) {
			listString=	new ArrayList<String>();
			listString.add("Text1");
			listString.add("Text2");
			listString.add("Text3");
		}
		return listString;
	}

	public void setListString(List<String> listString) {
		this.listString = listString;
	}

	public List<String> getListStringFiltered() {
		return listStringFiltered;
	}

	public void setListStringFiltered(List<String> listStringFiltered) {
		this.listStringFiltered = listStringFiltered;
	}
}

**Comment by tandraschko** [comment]
Works fine for me.
@melloware can you verify?

**Comment by melloware** [comment]
[pf-5327.zip](https://github.com/primefaces/primefaces/files/3843339/pf-5327.zip)

Attached is a Test case works fine in 7.0 and 8.0-SNAPSHOT for me.
