### ISSUE TITLE
TrackMouse error in <p:message display="tooltip"

### ISSUE THREAD

**Issue by diogo-cvs** [primefaces/primefaces#533]
If <p:tooltip trackMouse="true" is defined, cause js error in 'blur' event (p:inputText)

**Comment by cagataycivici** [comment]
Global or Normal tooltip?

**Comment by diogo-cvs** [comment]
Global

2015-09-22 5:50 GMT-03:00 Çağatay Çivici notifications@github.com:

**Comment by JaviRpo** [comment]
I have the same error with global tooltip.
The first time the tooltip display, but the second time in same component or in another component it causes a JS error.
![image](https://cloud.githubusercontent.com/assets/8562436/20034065/8d3f4c72-a37f-11e6-92b5-2a76abeed3f3.png)

I'm in PrimeFaces 6.0

The error happens in this showcase with `trackMouse="true"` attritbute
http://www.primefaces.org/showcase/ui/overlay/tooltip/tooltipGlobal.xhtml
