### ISSUE TITLE
SearchExpressionHint should be a Enum

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5330]
to be similar to JSF2.3, also this case fails:

        Assertions.assertFalse(
            SearchExpressionUtils.isHintSet(
                SearchExpressionHint.VALIDATE_RENDERER | SearchExpressionHint.SKIP_UNRENDERED | SearchExpressionHint.RESOLVE_CLIENT_SIDE,
                SearchExpressionHint.IGNORE_NO_RESULT));

**Comment by melloware** [comment]
Can you check I am getting a compile failure "SelectCheckboxMenuRenderer.java:[327,129] incompatible types: org.primefaces.expression.SearchExpressionHint cannot be converted to java.util.Set<org.primefaces.expression.SearchExpressionHint>"
