### ISSUE TITLE
Improve quality gate before 8.0

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#5335]
Before 8.0 gets released, I'd like to clean up few things based on sonarcloud analysis. The idea is just to apply the simplest fix to the squids. I'm planning to start with [maintainability section](https://sonarcloud.io/component_measures?id=org.primefaces%3Aprimefaces&metric=Maintainability). Of course, I'll do whatever I can in the most reasonable way. I'll certainly ping you for advice.

**Comment by tandraschko** [comment]
please also check why our sonar-project.properties isn't used correctly
i always deactived the rules in our properties first but doesn't work, so i had to use the UI to disable checks.

**Comment by tandraschko** [comment]
What should we do about:
https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&open=AWWwlzIHlgbYnohYUhY0&resolved=false&types=VULNERABILITY

**Comment by Rapster** [comment]
2 options: disable the rule or turning into immutable list.

I don't think sonarcloud consider the properties file, see https://stackoverflow.com/a/45095506/4605161

**Comment by Rapster** [comment]
@tandraschko I created that ticket so we can link commits, and also I think it'd be better to commit per squid and not randomly...

**Comment by Rapster** [comment]
squid:S2176 I think it has a good point and we shouldn't disable it, mostly we should rename all into ClientXXXConverter or ClientXXXValidator

**Comment by Rapster** [comment]
squid:S1611 "Parentheses should be removed from a single lambda input parameter when its type is inferred" Why disable it?

**Comment by christophs78** [comment]
Ok. I´ll look into TimelineEvent und ScheduleEvent. (introduce builder, deprecate args constructors)

**Comment by Rapster** [comment]
@christophs78 Could you have a look at [this one](https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&open=AWxM5-Nqdg2jiL0yV2Wf&resolved=false&rules=squid%3AS2175) please

**Comment by tandraschko** [comment]
i think it's right to disable squid:S2176; also think about SelectOneMenu or InputText.

**Comment by Rapster** [comment]
What about them? Their hierarchy looks good to me

**Comment by tandraschko** [comment]
We will also have classes with the same name as in the JSF API/Impl, therefore S2176 doesn't make sense for me.

**Comment by Rapster** [comment]
Well, I'd say using same names as api was not the best thing to do in a first place... It's definitely an unusual move... Anyway I'll check it out later

**Comment by tandraschko** [comment]
yup but there is no reason to change it ;) therefore -1 to change something here.

**Comment by Rapster** [comment]
Working on that [squid](https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&resolved=false&rules=squid%3AS1161&types=CODE_SMELL):
1. `DatePickerBase#getSelectionMode`: I think there is a design issue here, since Calendar has not selectionMode

2. `SelectOneMenuBase#setDir`: Hides `HtmlSelectOneMenu#setDir` which does a `handleAttribute("dir", dir);`. IMO, we shouldn't override getDir/setDir methods at all. getDir defines a default value, but we should be able to handle that in `ComponentUtils#isRTL`

**Comment by Rapster** [comment]
@tandraschko Since you updated UIRepeat recently, does UITabPanel need also to be updated since it's copied from MyFaces?

**Comment by christophs78** [comment]
>     1. `DatePickerBase#getSelectionMode`: I think there is a design issue here, since Calendar has not selectionMode
I think that´s fine. DatePicker has a selectionMode. (single, multiple, range)
Calendar has it´s own base-class which does not contain selectionMode, because calendar does not support selectionMode.

**Comment by Rapster** [comment]
@christophs78 @tandraschko don't you think `LazyScheduleModel#loadEvents` should be abstract?

**Comment by christophs78** [comment]
Yes, should be abstract.

**Comment by christophs78** [comment]
@Rapster: https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&issues=AWkJ_LvjgtFwgfOLlJpO&open=AWkJ_LvjgtFwgfOLlJpO seems to be a false-positive. It seems to be the only "critical" security issue. Is there a way to get rid of it?

**Comment by Rapster** [comment]
Should we delete `ConstantsHashMap` and `EnumHashMap`? We should simply do a simple test and throw an exception, no need to create a new class for that

**Comment by tandraschko** [comment]
nope, we can't as we just put them into the FC attributes

**Comment by Rapster** [comment]
Oh yeah I see what you mean

**Comment by Rapster** [comment]
Just a thought, just like we did for fileupload, should we move some of the classes in `org.primefaces.model` into a more appropriate package? I was thinking of packages like:
- data
- tree 
- schedule
- dashboard

**Comment by christophs78** [comment]
Schedule already has a some breaking changes. So developers need to touch code. Think this is a good opportunity the also move model-classes into a distinct package.
On the other ones i would be conservative.

**Comment by tandraschko** [comment]
Time for breaking changes is over now, WE will probably so rc1 this week.
So Testing on my side already started.

**Comment by Rapster** [comment]
I think it's better to make breaking changes once and for all than at every release. Specially that we already made modifications that makes developers touch the code like @christophs78 said, and renaming package is not the kinda task that takes time

**Comment by tandraschko** [comment]
we can't do this without asking PrimeTek and i even didn't get a answer if we release RC1 this week or not.

@rapster WDYT about disabling the "duplicate code" checks? We always try to optimize duplicate code but most of the issues can't be resolved. We are a component framework - some component are always similar.

**Comment by Rapster** [comment]
I know the "duplicate code" is big and sometimes we can't do much about it _(this is why I disabled it for XXBase.java)_, but regarding renderers and others, I think it's better to keep an eye on it, we can't simply ignore it

**Comment by christophs78** [comment]
How´s the releationship between community and PrimeTek? PrimeNG, PrimeReact und PrimeVue seem to be driven by PrimeTek by at least 95%. PrimeFaces ist different at this point in time. It´s driven primary by the community.
Is PrimeTek happy with the current state of things? Does the commerical part work for them? Is there some kind of coordination between PrimeTek und community?

**Comment by melloware** [comment]
I think your analysis is correct about the other Prime projects are 95% PrimeTek right now similar to how PrimeFaces was back from 2011-2015.  Since 2015 it seems Mert is the PrimeTek employee overseeing PF but he typically only fixes PrimeFaces PRO reported issues leaving all other issues up to the community to fix.

However if its a MAJOR refactoring usually Thomas will check with Mert first for example this PR: https://github.com/primefaces/primefaces/pull/4920

PrimeTek rejected for their reasons.

**Comment by tandraschko** [comment]
PrimeTek is the "owner" - i'm the "community lead" and therefore the "bridge" between PrimeTek and community.
I'm also not a employee of PrimeTek. I just have good connections to PrimeTek and use PrimeFaces since many years in my daily job.

You can just compare the numbers of stars and everything on github.
PrimeNG is probably ~5x more often used as PrimeFaces. Thats also expected - Angular works with every backend, not just Java :D
And compard to other Prime*, PrimeFaces is the most feature complete.

So PrimeTek cares about Elite and PRO. If the community improves the codebase, it's fine, otherwise it's by paying customers.
From time to time PrimeTek own components like DatePicker are migrated back to PrimeFaces.

**Comment by melloware** [comment]
@Rapster how close are we to finishing this ticket?  I still see 44 open items on the report. I think you fixed the XXE one but its still showing up on the report?

**Comment by Rapster** [comment]
44? I see 602! What are these XXE you mentionned? For 8.0, we might be okay, there is still 2 or 3 squid I'd like to fix. I'd like to have your opinion on this squid [Fields in a "Serializable" class should either be transient or serializable](https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&open=AWWwly4VlgbYnohYUhPP&resolved=false&rules=squid%3AS1948&types=CODE_SMELL)

**Comment by melloware** [comment]
Its 44 Vulnerabilities: https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&resolved=false&types=VULNERABILITY

Not the 602 code smells I am more concerned about vulnerabilities.

**Comment by melloware** [comment]
As for your question we have two options.
```java
CellEditEvent<T extends Serializable>
```
or
```java
private transient T oldValue;
```

I personally prefer option 1.

**Comment by Rapster** [comment]
Well, by the look of it I'm not really concerned, you can have a look it's 99% the same problem, but I don't think sonarcloud suggestion is the best. I would use an immutable set instead of making it protected

**Comment by melloware** [comment]
I think the XXE one that was assigned to you about the XML Transformer you fixed but it's still showing up?

**Comment by christophs78** [comment]
Yep, i also think the XXE is a false positive. Asked a few days ago whether we are able to mark it as false positive...

**Comment by tandraschko** [comment]
I already marked it as false positive but on the next checks, it shows again.

**Comment by tandraschko** [comment]
About the vulnerabilities...

95% of the issues are public modifiable arrays/sets/lists whatever.
It's not nice but whats the problem here? that a user can manipulate our HTML attributes? Thats even possible with unmodifieable maps or anything else. Reflection makes it possible.

Therefore, if we don't find a good reason, -1 from my side to change it.

Of couse immutable set is a nicer code - but we can also do it after 8.0.
Mert said they he plans a RC1 today, so it's not far away anymore.

**Comment by Rapster** [comment]
I disabled that "XML transformers should be secured" squid. Regarding the rest, I think sonar has his good reasons to consider it as a vulnerability (actually it's listed in the squid description), even though I understand it, I don't mind it

**Comment by Rapster** [comment]
`UIOutcomeTarget#getChildren` never used: safe to delete?

**Comment by Rapster** [comment]
@tandraschko Does `DefaultStreamedContent` needs to implement `Serializable`? I'm pretty sure there was a long discussion about this, but can't find the ticket

**Comment by tandraschko** [comment]
yep
normally it's used in requestscoped bean but sessionscoped could serialize it

**Comment by melloware** [comment]
Here is the problem I have with that mutability warning.
```java
public static final Set<SearchExpressionHint> SET_IGNORE_NO_RESULT = EnumSet.of(SearchExpressionHint.IGNORE_NO_RESULT);
```
Is immutable as EnumSet.of makes an immutable set.  But their detector just sees a `public static Set` and assumes its mutable.

**Comment by Rapster** [comment]
EnumSet is not immutable unfortunately

**Comment by melloware** [comment]
You are right I just fixed it and Sonar respected wrapping in UnmodifiableSet!  Seeing if I can fix the others.

**Comment by tandraschko** [comment]
Cagatay postponed RC1 to early next week
but as we already in bugfixing phase, please don't commit big refactorings anymore

**Comment by melloware** [comment]
OK we will freeze this ticket until after RC1 is released.

**Comment by Rapster** [comment]
> `UIOutcomeTarget#getChildren` never used: safe to delete?

Should we?

Another thing, you'll see  few things increased on [sonarcloud](https://sonarcloud.io/dashboard?id=org.primefaces%3Aprimefaces), it's because I added js/css files. Those results has been uploaded from my personal PC, I'm working on creating a new profile in maven for this. Just like for java files, there might be rules that need to be disabled. But please, let's talk about it first

**Comment by christophs78** [comment]
I think we should target js/css-qualitiy-improvements for 9.0 release.
Why? Last year Microsoft screwed the MS-SQL-Server-JDBC-driver 7.2 - release by doing some last minute code-improvements suggested by SonarCloud (or some similar tool). They had no appropiate automated tests. So the 7.2 - release had a major bug. They needed to reject it und replace it with 7.2.1.
Think we should target js/css-qualitity improvements through the whole next development-cycle. And maybe we should setup some sort of automated JS and/or UI-tests.

**Comment by tandraschko** [comment]
As i said, code is freezed for refactoring now.
I will check tomorrow If the Method mentioned by rapster can be removed.

**Comment by Rapster** [comment]
I didn't plan to do anything on that front for this release, I was keeping you updated in case you didn't notice

**Comment by Rapster** [comment]
To be continued on 8.1...
