### ISSUE TITLE
PanelMenu: link ignores "target" attribute

### ISSUE THREAD

**Issue by ndrikdarto** [primefaces/primefaces#5339]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (PrimeFaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0 Community
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 9.0.4
- Affected browsers: FireFox, Chome

## 2) Expected behavior
I want to display an url in iframe using panelMenu. The iframe should be as target. The result should be displayed in iframe. 

## 3) Actual behavior
The result displayed in page. The page will load the url.

## 4) Steps to reproduce

Display in page
```
<h:form id="menuForm">
    <p:panelMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:panelMenu>
</h:form>
```
Display in iframe
```
<h:form id="menuForm">
    <p:slideMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:slideMenu>
</h:form>
```

## 5) Sample XHTML

menu.xhtml
Display in page
```
<h:form id="menuForm">
    <p:panelMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:panelMenu>
</h:form>
```
Display in iframe
```
<h:form id="menuForm">
    <p:slideMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:slideMenu>
</h:form>
```
iframepage.xhtml
```
<h:body>

    <div class="row-container">

        <div class="first-row">
            <div class="start-button">
                <p:commandButton icon="fa fa-arrow-right" value="Start"
                    oncomplete="PF('nsidebar').show()" />
            </div>
            <div class="bottom">
                <ui:include src="bottom.xhtml" />
            </div>
        </div>

        <div class="second-row">
            <iframe id="dcontainer" name="dcontainer"> </iframe>
        </div>
    </div>

    <p:sidebar widgetVar="nsidebar" style="width:300px;">
        <ui:include src="menu.xhtml" />
    </p:sidebar>

</h:body>
```

## 6) Sample bean

..

**Comment by tandraschko** [comment]
@melloware 
thats something for you
PrimeFaces.utils.openLink(e, currentLink); doesn't honor the target attribute

**Comment by melloware** [comment]
Looking into it!

**Comment by melloware** [comment]
@tandraschko @ndrikdarto This work fine for me in PF 7.0 and 8.0-SNAPSHOT.  Attached is a test case where I open the same URL in an IFRAME, _self, and _blank to open in a new window.  It is respecting the "target" attribute correctly.

[pf-5339.zip](https://github.com/primefaces/primefaces/files/3859337/pf-5339.zip)

```xml
	<h:body>

		<h:form id="iframeForm">
			<p:slideMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px;height:250px">
				<p:menuitem value="Primefaces IFrame" url="http://www.primefaces.org" target="dcontainer" />
				<p:menuitem value="Primefaces Self" url="http://www.primefaces.org" target="_self" />
				<p:menuitem value="Primefaces New Tab" url="http://www.primefaces.org" target="_blank" />
			</p:slideMenu>
		</h:form>

		<div class="second-row">
			<iframe id="dcontainer" name="dcontainer"/>
		</div>

	</h:body>
```

**Comment by tandraschko** [comment]
Test the panelMenu  case :P
SlideMenu doesn't use the PrimeFaces.utils.openLink method

**Comment by melloware** [comment]
Ahhh i see his test case is PanelMenu.  Creating a reproducer now.  I can reproduce on PF7.0 and 8.0.

**Comment by melloware** [comment]
OK submitted fix and tested in IE11, Chrome, Firefox, Edge.
