### ISSUE TITLE
Client Side Validation: CSV for byte value is inconsistent with server-side validation

### ISSUE THREAD

**Issue by maruTA-bis5** [primefaces/primefaces#5340]
## 1) Environment
- PrimeFaces version: 7.0 Community
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source): No
- Application server + version: WildFly 18.0.1
- Affected browsers: All

## 2) Expected behavior
-127 ~ 128 is valid for byte value.

## 3) Actual behavior
- -127 ~ -1 is invalid in Client Side Validation.
- 129 ~ 255 is invalid in server-side validation but it is valid in Client Side Validation.

## 4) Steps to reproduce
1. Input -128 ~ -1 or 129 ~ 255 to inputNumber.
1. Click `submit` button.

## 5) Sample XHTML
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form>

        <p:messages>
            <p:autoUpdate />
        </p:messages>
        <p:outputLabel for="byteInput" value="Input number as byte (-128 ~ 127): " />
        <p:inputNumber id="byteInput" value="#{testView.byteValue}" required="true" />
        <p:commandButton value="submit" actionListener="#{testView.onSubmit}" validateClient="true" />

        </h:form>
    </h:body>
</html>
```

## 6) Sample bean
```java
package org.primefaces.test;

import java.io.Serializable;
import javax.faces.view.ViewScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;

import org.primefaces.PrimeFaces;

@Named
@ViewScoped
public class TestView implements Serializable {

    private Byte byteValue;

    public void setByteValue(Byte byteValue) {
        this.byteValue = byteValue;
    }

    public Byte getByteValue() {
        return byteValue;
    }

    public void onSubmit() {
        PrimeFaces.current().dialog().showMessageDynamic(new FacesMessage("Input: " + getByteValue()));
    }
}
```

Test project is available on: https://github.com/maruTA-bis5/primefaces-test/tree/csv-byte-range-issue

**Comment by tandraschko** [comment]
A PullRequest with a bugfix would be great!

**Comment by Rapster** [comment]
I think the problem comes from here: https://github.com/primefaces/primefaces/blob/0ce35ffd518c794f5db5e392b381e87efb8bb9e0/src/main/resources/META-INF/resources/primefaces/validation/validation.js#L377

And byte has a minimum value of -128 and a maximum value of 127 inclusive

**Comment by Rapster** [comment]
@maruTA-bis5 just fix it, please try with the latest snapshot

**Comment by maruTA-bis5** [comment]
@Rapster This issue still reproduces.

1. Input `-1`
    - expected: no error
    - actual: `'-1' must be a number between 0 and 255.`
2. Input `128`
    - expected: `'128' must be a number between -128 and 127.`
    - actual: '128' must be a number between 0 and 255.

**Comment by Rapster** [comment]
Having a look

**Comment by Rapster** [comment]
Can you try again please? Dont forget to clear your cache

**Comment by maruTA-bis5** [comment]
4e85d2b3da works perfectly. Thank you @Rapster  !
