### ISSUE TITLE
Timeline: buffer rangechange-events to reduce the amount of requests

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5355]
Primefaces 8.0-SNAPSHOT (but not a new 8.0 issue)

When we look at https://www.primefaces.org/showcase/ui/data/timeline/allEvents.xhtml and scroll within the timeline we see a huge amount of rangechange-events are fired. 

![grafik](https://user-images.githubusercontent.com/10461942/69262979-b2d4af80-0bc4-11ea-9479-6155b6dac003.png)

Maybe we should send only all 100ms (or so) one event to the server to reduce the noise and only send the last/newest one to the server.

Off-Topic:
Showcase seems to send all 2 seconds a request to https://mc.yandex.ru/webvisor. I don´t like this. @mertsincan: Can we at least increase the intervall of these requests?
(Update: Maybe it was already removed from Showcase-master.)

**Comment by melloware** [comment]
Adding @jasonex7

**Comment by christophs78** [comment]
Maybe it´s simple a bad idea to listen to to rangechange-event and someone should only listen to the rangechanged-event.

**Comment by jasonex7** [comment]
I don't think server side processing of rangechange-event is appropriate, I think that event is best for client-side maybe with [<pe:javascript />](https://www.primefaces.org/showcase-ext/sections/clientBehaviours/javascriptBehaviour.jsf) tag.

**Comment by christophs78** [comment]
Ok. I will add a note to the documentation and remove rangechange-event from the allEvents-showcase-page.
