### ISSUE TITLE
Check MyFaces ViewPooling compatibility

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5356]
See: https://myfaces.apache.org/wiki/core/user-guide/configuration-of-special-features/view-pooling.html

especially:

> All components used in a view that uses view pooling must be compatible with the technique. The reason is some components has some variables that are not part of the state, but plays an important role. For example, in UIData there is a variable used to hold the dataModel and if a reset is required, the model must be cleared. In other cases, since all state is contained in the inner StateHelper instance provided by MyFaces implementation through UIComponentBase, there is no need to do anything else to make it compatible. If a component extends from UIComponent directly, it should add the necessary code to reset the view in saveState(...) method.

**Comment by tandraschko** [comment]
Open:
- DataTable
- DataView
- UIRepeat
- Tree
- TreeTable

Done/Checked:
- UICache
- AutoComplete
- Calendar
- Columns
- ColumnToggler
- CellEditor
- DatePicker
- InputTextarea
- OrderList
- Panel
- PickList
- Rating
- Schedule
- SelectOneRadio
- SelectManyCheckbox
- Wizard

**Comment by tandraschko** [comment]
@christophs78 can you please try to analyze why in Calendar and DatePicker there is a customEvents, which triggers the event later in the validation phase? little bit strange code
Nevermind, same in PickList and OrderList, probably just to trigger the event after validation

**Comment by tandraschko** [comment]
in case of Panel or CellEditor: the old code would be fine as the component reference is from the same view(pool) but it think it's a bit cleaner without vars

**Comment by christophs78** [comment]
> @christophs78 can you please try to analyze why in Calendar and DatePicker there is a customEvents, which triggers the event later in the validation phase? little bit strange code
> Nevermind, same in PickList and OrderList, probably just to trigger the event after validation

Yep, think the same. eg dateSelect should only be triggered after the selected value was validated successful.

**Comment by Rapster** [comment]
I'm not sure I understand those changes according to view pooling definition of MyFaces. First, it sounds like in case there are attributes that needs to be saved/restored in the state then saveState/restore has to be implemented. Does all attributes needs to be saved and restored? MyFaces uses UIData as an example, but I feel it's a complex component to take as an example 😅 

Second, since components are request scoped, and with these changes, how does it make a difference?

As an example: https://github.com/primefaces/primefaces/commit/fb5b6c9ba59608ca22c297c2d959c8ce46a3d65d

**Comment by tandraschko** [comment]
I probably reverted the commit you linked as the component references are ok, they are in the same view.

Most of the times we use fields as Cache in current request. This has to be resetted as the view is now reused in other requests

**Comment by Rapster** [comment]
Working on ticket #4278 for post 8.0, and I thought of adding attributes in some classes but since this ticket I have doubts now,  does it mean we can't have attributes? What's the rule?

**Comment by tandraschko** [comment]
do you mean UIComponent#getAttributes?

**Comment by Rapster** [comment]
No class attributes, most of your commits got rid of class attributes

**Comment by tandraschko** [comment]
yep, those should be avoided
just think aoubt that UIComponent instances are shared between requests and that wrong state could be still there from a old request/view

**Comment by Rapster** [comment]
Ok and same with renderers ?

**Comment by tandraschko** [comment]
renderes should not have any fields, they are appscoped AFAIK

**Comment by tandraschko** [comment]
I didn't implement it for UIRepeat, it should not be used in MyFaces environments at best.
