### ISSUE TITLE
Meter Gauge Chart display incorrectly!!

### ISSUE THREAD

**Issue by lmy46** [primefaces/primefaces#536]
When I finished the set will be displayed incorrectly.

Code:

MeterGaugeChartModel meterGaugeChartModel = new MeterGaugeChartModel();
meterGaugeChartModel.setValue(140);
List<Number> ticks = new ArrayList<Number>() {
    {
        add(20);
        add(50);
        add(120);
        add(220);
    }
};
meterGaugeChartModel.setTicks(ticks);

**Comment by tandraschko** [comment]
Not replicateable anymore: #2369
