### ISSUE TITLE
Calendar/DatePicker: value not set in component, if no value-binding is set

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5361]
A common case for DataTable filter is that the filter facet contains a datepicker/calendar without a value binding.
In this case we don't convert the submitted value and the DatePicker#getValue is null -> no filtering applied

**Comment by tandraschko** [comment]
@christophs78 please also review

**Comment by christophs78** [comment]
The fix looks reasonable. 
But it may be some kind of breaking change to return LocalDate if no ValueExpression is present. Up to 7.0 BaseCalendarRenderer#getConvertedValue returned a java.util.Date without a explicit converter.
Now we return LocalDate if no ValueExpression is present and no explicit converter is defined.
Think we need to add this to the MigrationGuid. (IMO this may cause some not so easy to find issues in combination with LazyDataModel and FilterMeta. Update: Maybe even without LazyDataModel. One column of the table may contain java.util.Date-Values. Now we try to filter them via java.time.LocalDate OOTB.)

**Comment by tandraschko** [comment]
yep, could you add something to the migration guide?

**Comment by christophs78** [comment]
Yes

**Comment by christophs78** [comment]
done

**Comment by christophs78** [comment]
@tandraschko:
Maybe stupid question: Which client-side event of Calender/DatePicker do you use to filter the DataTable? onchange only get´s triggerd when i type text into the field and leave it. When i pick a date via Calendar/Datepicker there does not seem to be a appropriat event to listen to.

**Comment by tandraschko** [comment]
It was from a customer
he registered p:ajax on onchange and dateselect and triggered the DT filter in oncomplete

**Comment by kukel** [comment]
@christophs78: Long standing issue using the onchange. I'll create a patch for the dataPicker too address this. @tandraschko: Using pe:javascript would have been a solution too, not creating a superfluous ajax call.
