### ISSUE TITLE
${project.version} isn't replaced in core.js

### ISSUE THREAD

**Issue by der-tkw** [primefaces/primefaces#5372]
## 1) Environment
- PrimeFaces version: 7.0 and 7.0.10 (6.2.2.6 is still OK)
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) N/A
- Application server + version: All
- Affected browsers: All
- Related issue: #2747

## 2) Expected behavior
Version should be substituted (by Maven).

## 3) Actual behavior
Version is not substituted.

## 4) Steps to reproduce
Use `PrimeFaces.VERSION` in javascript.

**Comment by tandraschko** [comment]
@mertsincan this works fine in trunk, probably the maven-resource-plugin isn't configured in the elite versions? can you check?

Will close the ticket as not related to the community version.

**Comment by mertsincan** [comment]
This is not related to elite version. Could you please try the released versions such as 6.2, 7.0 etc.?
Please see in 7.0 source;
```
VERSION: '${project.version}'
```
Version-SNAPSHOTS works fine. We need to do this in the release bundle.

**Comment by mertsincan** [comment]
Hi @melloware, Could you please improve the fix within https://github.com/primefaces/primefaces/issues/2747?

Thanks a lot!

**Comment by melloware** [comment]
Yep I will take a look at this

**Comment by melloware** [comment]
OK @mertsincan PR submitted.

**Comment by mertsincan** [comment]
Thanks a lot, @melloware ;)
