### ISSUE TITLE
FileUpload: add show function in client API

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#5373]
To make it very simple, I'd like to open a file upload through a menu item. See this code:
```xml
    <p:splitButton value="#{i18n['TSK_START_NEW_CONF']}"
                   action="#{confVersionListController.startNewConf()}">
        <p:menuitem value="#{i18n['TSK_IMPORT_EXISITNG_CONF']}"
                    onclick="$(PF('confUpload').jqId + '_input').click()" />
    </p:splitButton>

    <p:fileUpload widgetVar="confUpload"
                  mode="advanced"
                  fileUploadListener="#{confVersionListController.importNewConf}"
                  auto="true"
                  style="display: none" />
```

First, I want to take advantage of `FileUpload#listener` method , that's why I'm using it. Second, I make it not visible using CSS since I want to open it through menuitem. Now I need to open the file dialog when clicking on menu item.

Since there is no `PF('fileupload').show()` implemented in the client API... I'm using this ugly workaround: `$(PF('fileUpload').jqId + '_input').click()` 

I was thinking of introducing this function in client API of fileUpload, WDYT?

**Comment by melloware** [comment]
+1 for me, client API functions additions that get around workarounds like above are always useful.

**Comment by Rapster** [comment]
FYI, a new version of this plugin is available, should we upgrade?

**Comment by melloware** [comment]
I thought I just upgraded this recently to the latest version

**Comment by melloware** [comment]
I uprgaded to 10.2.0 26 days ago https://github.com/primefaces/primefaces/pull/5292

**Comment by Rapster** [comment]
https://github.com/blueimp/jQuery-File-Upload/releases/tag/v10.4.0

**Comment by melloware** [comment]
Ahh yep if you update it don't forget to update the 3rd part libs docs: https://primefaces.github.io/primefaces/8_0/#/core/thirdpartylibs
