### ISSUE TITLE
InputNumber: The minValue attribute does not work correctly

### ISSUE THREAD

**Issue by JoakinAA** [primefaces/primefaces#5376]
## 1) Environment

- PrimeFaces version: 7.0.8
- Application server + version: Tomcat 9.0.26
- Affected browsers: Chrome, Firefox and IE 11+

## 2) Expected behavior

It should allow me to write when the minimum value is a double digit

## 3) Actual behavior

If minValue = "10" does not allow me to enter any number

## 4) Steps to reproduce

See primefaces-test example.

## 5) Sample XHTML

See primefaces-test example.

## 6) Sample bean

See primefaces-test example.

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/3896967/primefaces-test.zip)

**Comment by tandraschko** [comment]
I think thats the same issue as here: https://github.com/primefaces/primefaces/issues/4315
and it's expected by the underlying autoNumeric plugin

**Comment by tandraschko** [comment]
and
https://github.com/primefaces/primefaces/issues/3025

was discussed many times actually

**Comment by melloware** [comment]
Here is the issue from AutoNumeric explaining it: https://stackoverflow.com/questions/39287389/how-type-value-in-autonumeric-input-with-set-vmin

Closing as duplicate.
