### ISSUE TITLE
DataTable & ContextMenu: ContextMenu does not open for empty DataTables

### ISSUE THREAD

**Issue by dclaroni** [primefaces/primefaces#5378]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Affected browsers: Firefox

## 2) Expected behavior
When right-clicking an empty row in a datatable the context menu is displayed.

## 3) Actual behavior
When right-clicking an empty row in a databale the default browser context menu is displayed (e.g. the PF context menu is not displayed).

The browser console indicates "TypeError: g is undefined."

## 4) Steps to reproduce
1) Create a DataTable and a context menu that is associated with the table. Ensure that the table is empty and that there is a emptyMessage attribute set on the data table.
2) Right click on the empty row.

I looked into it in detail and found that in my components.js file there is a variable "g" that is not instantiated in the scope of its use. There is however a variable "f" which looks like it should be used instead of "g". I believe "f" and "g" are used because the file was minified & obfuscated.

In the latest version of primefaces, this code is located in datatable.js ( primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js ) and that "f" variable corresponds to "row" on line 882 and "g" corresponds to "$this" on line 903. The error is happening on line 903: `else if(row.hasClass('ui-datatable-empty-message') && !$this.cfg.disableContextMenuIfEmpty) {` because the "$this" variable is defined outside of the scope where it is used here (line 909). 

I think replacing "$this" with "row" on line 903 will fix the issue.

## 5) Sample XHTML
```xml
<p:dataTable id="testTable" emptyMessage-"No Data">
    <f:facet name="header">Table</f:facet>
    <p:column headerText="Column 1"></p:column>
</p:dataTable>
<p:contextMenu for="testTable">
    <p:menuitem value="Add" onclick="alert('added');" />
</p:contextMenu>
```

## 6) Sample bean
N/A - not relevant

**Comment by melloware** [comment]
I was able to verify your issue.  I fixed it correctly, you can't use row as that does not have cfg it needs to be the datatable itself.  I tested my fix and its now working properly.  

If you need this fix right now just add this script to your page.
```javascript
PrimeFaces.widget.DataTable.prototype.bindContextMenu = function(menuWidget, targetWidget, targetId, cfg) {
        var $this = this;
        var targetSelector = targetId + ' tbody.ui-datatable-data > tr.ui-widget-content';
        var targetEvent = cfg.event + '.datatable';
        this.contextMenuWidget = menuWidget;

        $(document).off(targetEvent, targetSelector).on(targetEvent, targetSelector, null, function(e) {
            var row = $(this);

            if(targetWidget.cfg.selectionMode && row.hasClass('ui-datatable-selectable')) {
                targetWidget.onRowRightClick(e, this, cfg.selectionMode);

                menuWidget.show(e);
            }
            else if(targetWidget.cfg.editMode === 'cell') {
                var target = $(e.target),
                cell = target.is('td.ui-editable-column') ? target : target.parents('td.ui-editable-column:first');

                if(targetWidget.contextMenuCell) {
                    targetWidget.contextMenuCell.removeClass('ui-state-highlight');
                }

                targetWidget.contextMenuClick = true;
                targetWidget.contextMenuCell = cell;
                targetWidget.contextMenuCell.addClass('ui-state-highlight');

                menuWidget.show(e);
            }
            else if(row.hasClass('ui-datatable-empty-message') && !$this.cfg.disableContextMenuIfEmpty) {
                menuWidget.show(e);
            }
        });

        if(this.cfg.scrollable && this.scrollBody) {
            this.scrollBody.off('scroll.dataTable-contextmenu').on('scroll.dataTable-contextmenu', function() {
                if($this.contextMenuWidget.jq.is(':visible')) {
                    $this.contextMenuWidget.hide();
                }
            });
        }
    }
```
