### ISSUE TITLE
InputNumber : not listen style width setting

### ISSUE THREAD

**Issue by ndrikdarto** [primefaces/primefaces#5380]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (PrimeFaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0 Community
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: tomcat 9.0.4
- Affected browsers: FireFox, Chrome

## 2) Expected behavior
The width of inputnumber changes according to style setting.

## 3) Actual behavior
The width of inputnumber do not changes according to style setting.
I tried to use style in InputText, and it works. The width of inputText follow the style width setting.

## 4) Steps to reproduce
```
<p:inputText style="width:50px" />
<p:inputNumber style="width:50px" />
```

## 5) Sample XHTML
```
<p:inputText style="width:50px" />
<p:inputNumber style="width:50px" />
```

**Comment by ndrikdarto** [comment]
I use it in dataTable
```
<p:column width="100">
     <p:inputText style="width:50px" />
     <p:inputNumber style="width:50px" />
</p:column>
```

**Comment by ndrikdarto** [comment]
sorry, I found the way.

```
<p:inputNumber inputStyle="width:50px" />
<p:inputText style="width:50px" />

```
It can be closed.

**Comment by tandraschko** [comment]
Please use Google next time before creating a issue
