### ISSUE TITLE
InputTextArea: Server Validation Problem with maxlength and \r\n

### ISSUE THREAD

**Issue by enricokl** [primefaces/primefaces#5381]
## 1) Environment
PrimeFaces version: 7.0.10, 8.0
Application server + version: Tomcat 9.0.21
Affected browsers: Tested on IE and FF

## 2) Expected behavior
The number of signs in InputTextArea in Javascript are the same as in Java, if you push ENTER.

## 3) Actual behavior
The number of signs in InputTextArea in Javascript not are the same as in Java, if you push ENTER.
So it is possible that the the server validation discard the input in InputTextAreaRenderer.java. 

![PFNextLineIssue](https://user-images.githubusercontent.com/58223973/69804046-f7bc9f80-11dd-11ea-8d52-248fd2306d5b.PNG)

![PFNextLineIssueFill](https://user-images.githubusercontent.com/58223973/69804642-53d3f380-11df-11ea-98ce-eb01591ff1a1.PNG)

I believe that the problem is because of #5329. The Problem is fixed on client only.

## 4) Steps to reproduce
- Push ENTER in a InputTextArea field with maxlength and fill the input with max signs

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
   <title>PrimeFaces Test</title>
</h:head>
<h:body>
   <h:form>
      <h1>#{testView.testString}</h1>
      <p:inputTextarea id="test"
                       value="#{testView.textAreaString}"
                       maxlength="20"
                       rows="6"
                       counterTemplate="Count Javascript: {0} signs left"
                       counter="counterComment"
                       autoResize="false">
         <p:ajax event="blur" update="count_java"/>
      </p:inputTextarea>
      <br/>
      <h:outputText id="counterComment"/>
      <br/>
      <h:outputText id="count_java" value="Count Java: #{testView.getLength()}"/>
   </h:form>
</h:body>
</html>
```
## 6) Sample bean
```
package org.primefaces.test;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    private String textAreaString;

    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(final String testString) {
        this.testString = testString;
    }

    public String getTextAreaString() {
        return textAreaString;
    }

    public void setTextAreaString(final String textAreaString) {
        this.textAreaString = textAreaString;
    }

    public int getLength(){
        return this.textAreaString == null ? 0 : this.textAreaString.length();
    }
}
```

**Comment by melloware** [comment]
Attached is my test case: 
[pf-5381.zip](https://github.com/primefaces/primefaces/files/3902487/pf-5381.zip)

PR Submitted fixes the issue so the newlines on the client and server match again.
