### ISSUE TITLE
Datatable: stickyTopAt broken at showcase when div.layout-notification is shown

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5387]
## 1) Environment
- PrimeFaces version: 8.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Not sure
- Does it work on the newest sources in GitHub? No
- Application server + version: -
- Affected browsers: all

## 2) Expected behavior
The stickyTopAt attribute points to .layout-topbar and this should be the top position.

## 3) Actual behavior
The datatable header stops at the .layout-notification element above, parially hiding the topbar.

## 4) Steps to reproduce
Go to https://www.primefaces.org/showcase/ui/data/datatable/sticky.xhtml during the Black-Friday week, in this case a div.layout-notification is rendered above the div.layout-topbar. If deleting the div.layout-notificaction during display, everything is back to normal.

## 5) Sample XHTML
See showcase

## 6) Sample bean
See showcase

If this is needed I can also try to provide an additional reproducer.

**Comment by melloware** [comment]
This may be similar to this: https://github.com/primefaces/primefaces/issues/5094

**Comment by melloware** [comment]
It is because the way the styled it the topbar has top of 70px so that is what the sticky is using even though the notification bar is also adding 70px to top.
```css
.layout-wrapper .layout-notification + .layout-topbar {
    top: 70px;
}
```
So I think the sticky doesn't know its supposed to be 140px total as its just looking at the target component and seeing top of 70px

**Comment by stolp** [comment]
I have not yet located the code for this but my hunch is that top attribute is ignored and only the height is taking into account. Might be wrong though.

**Comment by melloware** [comment]
This appears to be fixed on the latest showcase: https://www.primefaces.org/showcase/ui/data/datatable/sticky.xhtml

See the ad for Siberia at the top?  Sticky seems to respect it now.

**Comment by stolp** [comment]
I am sorry to say that - but it does not work for me.

Expected: The sticky should end at the inner white area.
Observed: The sticky ends at the primefaces header.

**Comment by melloware** [comment]
Oh yep I thought you were saying it was not stopping at Siberia.

**Comment by melloware** [comment]
I know why.... 

1. The div with `class="layout-news"` is set to render `display:none`.

2. Then Sticky calculates its dimensions because the page has finished loading.  So it calculates "top" based on the current DOM and `display:none` components are not ever counted.

3. Then this JavaScript runs very last to show the News if you haven't already closed it and they have your cookie marked.

```javascript
initPrimeNewsBar: function() {
            var topbarNewsBar = this.wrapper.children('.layout-news');
            if (topbarNewsBar.length) {
               var topbarNewsCloseButton = topbarNewsBar.find('.layout-news-close'),
               removeTopbarNewsBar = function() {
                   $.cookie('showcase_newsbar', false, {path: '/'});
                   topbarNewsBar.removeClass('layout-news-active');
               };
               
                var newsbarcookie = $.cookie('showcase_newsbar');
                if (newsbarcookie) {
                    topbarNewsBar.removeClass('layout-news-active');
                }
                else {
                    topbarNewsBar.addClass('layout-news-active');
                    topbarNewsCloseButton.on('click', function(e) {
                        removeTopbarNewsBar();
                        e.preventDefault();
                    });
                }
            }
        }
```

So I don't think this is a flaw in Sticky, I think its just a flaw with the Showcase and how they have designed it.

**Comment by melloware** [comment]
So I am still going to close this.  You can open an issue on the Showcase issues page if you feel strongly about it...  https://github.com/primefaces/primefaces-showcase/issues
