### ISSUE TITLE
TimeLine: JS Error

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5388]
Go to the showcase: https://www.primefaces.org/showcase/ui/data/timeline/allEvents.xhtml

Open the console and you will see this error:

> Uncaught ReferenceError: el is not defined
>     at Class._bindTimelineEvents (timeline.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:418)

This bug was introduced with https://github.com/primefaces/primefaces/commit/7be389313032a191dd25796b986c4282e162fe2c#diff-28cd7b7805f212735ee6518b1cc7cf93

The old bindEvents had a el-parameter, the new _bindItemsEvent misses this parameter:
![grafik](https://user-images.githubusercontent.com/10461942/69847362-2aff3d00-1277-11ea-9933-3ec1b0bc22b1.png)

**Comment by jasonex7** [comment]
Thanks @melloware 👍  .
