### ISSUE TITLE
TextEditor: Add Custom (Google) Fonts

### ISSUE THREAD

**Issue by WillemLab** [primefaces/primefaces#5394]
Add an easy way of adding your custom fonts (**Google Fonts**) to the TextEditor fonts `Select Menu`.

StackOverflow: https://stackoverflow.com/questions/59152951/add-google-fonts-to-primefaces-text-editor

Example how to add custom fonts to QuillJS which is the library TextEditor uses: https://quilljs.com/playground/#custom-fonts

**Comment by melloware** [comment]
To achieve registering a custom font or any other custom module in QuillJS I think we need to add "extender" functionality to this component similar to how other components have implemented it to allow the user to get at the core QuillJS configuration before it is created.

Also possibly a "register" method on the widget to allow registering the fonts before the component is loaded.

**Comment by WillemLab** [comment]
What is the current status on development for this?

**Comment by tandraschko** [comment]
Still untouched.
Feel free to work on it and provide a Pull Request or sponsor it via PrimeFaces PRO.

**Comment by melloware** [comment]
Support for Google Fonts has been added to the PrimeFaces Extensions SunEditor.

```xml
 <!-- Google Fonts can be used "Roboto", "Bruno Ace SC"
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&amp;family=Roboto&amp;display=swap" rel="stylesheet" />
    -->

    <pe:sunEditor id="sunEditor" widgetVar="sunEditor" value="#{basicSunEditorController.html}"
                  extender="editorExtender" toolbar="[['font','fontSize','formatBlock']]">
    </pe:sunEditor>

    <script type="text/javascript">
        function editorExtender() {
            // this = widget
            // this.cfg = JSON configuration
            this.cfg.font = ["Serif", "Sans-Serif", "Monospace", "Roboto", "Bruno Ace SC"];
            this.cfg.defaultStyle = "font-family:Serif;";
        };
    </script>
```

**Comment by melloware** [comment]
Closing this since QuillJS 1.3.7 has stopped development and 2.0 has been 4 years in the making and this component will need to be re-engineered for 2.0 anyway.
