### ISSUE TITLE
MenuModel: 8.0.rc1 - method addElement removed without deprecation

### ISSUE THREAD

**Issue by pzygielo** [primefaces/primefaces#5398]
_I understand that release 8 might introduce breaking changes with relation to release 7 and you exercise this right to do so._

## 1) Environment
- PrimeFaces version: upgrade from 7.0 to 8.0.rc1

## 2) Expected behavior
`MenuModel.addElement` to be deprecated for at least one release to allow easy PF upgrade and update of client code separately.

## 3) Actual behavior
I found method `MenuModel.addElement` removed without warning/deprecation.
My previous code
```java
    MenuModel menu = new DefaultMenuModel();
    menu.addElement(new DefaultMenuItem());
```
requires from me to care for MenuModel details now and use
```java
    MenuModel menu = new DefaultMenuModel();
    menu.getElements().add(new DefaultMenuItem());
```

It changes upgrade of PF (I hoped for just bumping version) to whole _migration_.

**Comment by tandraschko** [comment]
We had some breaking changes in 8.0 (like changing events to LocalDate), where we can't add deprecation. So we decided to also break some minor things like this issue, too.

**Comment by pzygielo** [comment]
Understood, just raised for issue visibility. Hope to see this change mentioned in final release notes.
