### ISSUE TITLE
UploadedFile: method getContents renamed without deprecation

### ISSUE THREAD

**Issue by pzygielo** [primefaces/primefaces#5399]
_I understand that release 8 might introduce breaking changes with relation to release 7 and you exercise this right to do so._

## 1) Environment
- PrimeFaces version: upgrade from 7.0 to 8.0.rc1

## 2) Expected behavior
https://github.com/primefaces/primefaces/blob/29b5d2d0ef4a1b6da5213b1d7f2e11476c3160c5/src/main/java/org/primefaces/model/file/UploadedFile.java#L35 to be named `getContents` as it was in 
https://github.com/primefaces/primefaces/blob/45bb466d5a52707fa0542a0dbf68fb5ddcc8abc3/src/main/java/org/primefaces/model/UploadedFile.java#L40

## 3) Actual behavior
I found method `getContents` renamed without warning/deprecation.

(Also [content-or-contents](https://dictionary.cambridge.org/grammar/british-grammar/content-or-contents), this method returns very countable bytes.)

So previous code
```java
   FileUploadEvent e
   e.getFile().getContents()
```
has to be updated on PF upgrade. `UploadedFile` moved to different package is fine (if not used directly, as above).

**Comment by tandraschko** [comment]
Why do you create those tickets? we have a migration guide where everything is listed

**Comment by tandraschko** [comment]
Just check our wiki -> https://github.com/primefaces/primefaces/wiki/Migration-Guide

**Comment by pzygielo** [comment]
> Just check our wiki -> https://github.com/primefaces/primefaces/wiki/Migration-Guide

Thanks for the link. Didn't check it before.

However this one change introduced grammar error I think.

**Comment by tandraschko** [comment]
which one?
