### ISSUE TITLE
Update reCAPTCHA to V2

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#54]
Update the p:captcha component to use the new Google No Captcha reCaptcha:

"A significant number of your users can now attest they are human without having to solve a CAPTCHA. Instead with just a single click they’ll confirm they are not a robot. We’re calling it the No CAPTCHA reCAPTCHA experience. See blog for more details."

http://googleonlinesecurity.blogspot.com/2014/12/are-you-robot-introducing-no-captcha.html

**Comment by puneet739** [comment]
Hi,
By when are you planing to update this new component

**Comment by mafaul** [comment]
Email from Google:

Google launched reCAPTCHA v2 (i.e. No CAPTCHA reCAPTCHA) in Dec, 2014. The new version provides a more simplified user experience than reCAPTCHA v1, with an enhanced spam fighting mechanism. 

Action requested: please upgrade your site implementation to reCAPTCHA v2.

Thank you, 
reCAPTCHA Support

**Comment by cagataycivici** [comment]
My colleague @mertsincan is working on this now.

**Comment by cagataycivici** [comment]
Available for 5.2.9 and 5.3.

**Comment by gregor2005** [comment]
I found it in the showcase -> http://www.primefaces.org/showcase/ui/misc/captcha.xhtml
Should that mean ELITE/PRO users can use it?

**Comment by puneet739** [comment]
Anyone can use in now. Just get the latest snapshot of Primefaces.
or as stated earlier any version greater then 5.2.9

On Mon, Aug 17, 2015 at 9:44 PM, gregor2005 notifications@github.com
wrote:

> FYI: I found it in the showcase ->
> http://www.primefaces.org/showcase/ui/misc/captcha.xhtml
> Should that mean ELITE/PRO users can use it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/primefaces/primefaces/issues/54#issuecomment-131876107
> .

## 

Regards
Puneet Behl
0-9711616135

**Comment by gregor2005** [comment]
I'm not sure. As you can see in the download page the latest version is 5.2.6 and for the community 5.2

Download-Page: http://www.primefaces.org/downloads
Snapshot-Page: https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/
