### ISSUE TITLE
Component css: use primeicons 

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#5400]
Instead of define hundreds of rules and then override them inside theme.css
it would be better to use directly primeicons inside component.css

**Comment by melloware** [comment]
That's up to @mertsincan I am assuming there is a reason they do not as the themeroller themes use different icons.

**Comment by tandraschko** [comment]
IMO themeroller is outdated, PrimeIcons not complete yet. Not sure whats the best way.

**Comment by melloware** [comment]
Agree and I prefer FontAwesome 5.X to all of them as it has 8000+ icons.

**Comment by pizzi80** [comment]
There's also MaterialIcons that are licenced with Apache License Version 2.0

https://google.github.io/material-design-icons/

**Comment by tandraschko** [comment]
I dont think we plan to support "yet another item set".

I think a good goal would be to replace all jqueryicons by primeicons when they are feature complete (compared to jquery).
we should still support fontawesome of course.

**Comment by melloware** [comment]
I just updated the docs on how to use FontAwesome5 with PrimeFaces: 
https://primefaces.github.io/primefaces/8_0/#/core/fonticons?id=fontawesome-5x-or-higher

**Comment by stolp** [comment]
I followed the instructions for FontAwesome5 and it works great. This came just at the right time. Thanks a lot!

**Comment by melloware** [comment]
According to this post fro Cagatay about the roadmap to PF10 is that PrimeIcons 4.0 will be a first class citizen of PF for the new themes.
See: https://www.youtube.com/watch?v=SqeoPsPQwOw
