### ISSUE TITLE
FileUpload: temporary file handlers leak

### ISSUE THREAD

**Issue by pawwal** [primefaces/primefaces#5408]
## 1) Environment
- PrimeFaces version: **7.0**
- Does it work on the newest released PrimeFaces version? Version? **No - the problem is still there**
- Does it work on the newest sources in GitHub? **No - the problem is still there**
- Application server + version: **verified on WildFly 10.0.0 and 18.0.1**
- Affected browsers: **Not relevant**

## 2) Expected behavior
Temporary file handlers should be closed after uploading a file.

## 3) Actual behavior
Temporary file handlers are not closed after uploading a file using FileUpload component (native JSF2.2 uploading). They just leak silently. This can potentially lead to "too many open files" error when OS limits are reached.  The problem is not visible in the app server itself but on the OS level only, so there is no stacktrace available. 

After some debuging I believe I found issues in two methods:

* org.primefaces.util.FileUploadUtils#isValidType
* org.primefaces.util.FileUploadUtils#isValidFile

They both retrieve `InputStream` from `UploadedFile.getInputStream()` but never close it.

## 4) Steps to reproduce
1. Upload any file using FileUpload component with file validation turned on. 
1. Check open file handlers on the OS level. On Linux and Mac `lsof -u USERNAME | grep upload` may be used (provided that WildFly app server is used - otherwise the grep expression should be changed accordingly). 
1. There should be two hanging file handlers more after each upload. Please note that the files themselves are not there anymore - they have been correctly removed by the app server.

**Comment by tandraschko** [comment]
thanks!
did a small improvment, please check my last commit

**Comment by stevendegroote** [comment]
May I ask if this issue was also present in PF6.x ?

**Comment by melloware** [comment]
From looking at the 6.2 tag in Git no I don't believe this issue was present.
