### ISSUE TITLE
SelectCheckboxMenu: clicked text doesn't work, but event is still fired

### ISSUE THREAD

**Issue by jasonex7** [primefaces/primefaces#5410]
## 1) Environment
- PrimeFaces version: 8.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- It works with PrimeFaces 7.0
- Application server + version: jetty with primefaces-test repo
- Affected browsers: All

## 2) Expected behavior
It should select the item when text is clicked and fire one ajax request

## 3) Actual behavior
Doesn't select the item but 2 ajax events are fired.

## 4) Steps to reproduce
See sample on: https://github.com/jasonex7/primefaces-test/tree/checkbox-issue

![4b4abe68-10c4-4a66-94ad-cd3e2b30220c](https://user-images.githubusercontent.com/16229253/70360318-1bba5980-184c-11ea-8bf4-edee79deeb3b.gif)

## 5) Sample XHTML
```xhtml
        <h:form>
            <p:growl>
                <p:autoUpdate />
            </p:growl>
            <p:selectCheckboxMenu id="checkbox" value="#{testView.selected}" label="Select One">
                <p:ajax listener="#{testView.onItemSelect}" />
                <f:selectItems value="#{testView.testList}" var="t" itemLabel="#{t}" itemValue="#{t}" />
            </p:selectCheckboxMenu>
        </h:form>
```

## 6) Sample bean
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    
    private List<String> selected;
    private List<String> testList;
    
    @PostConstruct  
    public void init() {
        testList = new ArrayList<>();
        testList.add("item 1");
        testList.add("item 2");
        testList.add("item 3");
        testList.add("item 4");
        testList.add("item 5");
    }

    public List<String> getTestList() {
        return testList;
    }

    public List<String> getSelected() {
        return selected;
    }

    public void setSelected(List<String> selected) {
        this.selected = selected;
    }

    public void onItemSelect() {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Selected values: " + selected));
    }
}

```

**Comment by tandraschko** [comment]
A PR would be great

**Comment by melloware** [comment]
Excellent bug ticket @jasonex7 . I can look at this one on Monday.

**Comment by jasonex7** [comment]
Thanks @melloware. It works as expected now.
