### ISSUE TITLE
p:dialog:  inaccessible nested modal dialog

### ISSUE THREAD

**Issue by JeeDevUser** [primefaces/primefaces#5413]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (PrimeFaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Payara 5.193
- Affected browsers: Firefox 68+, Chrome 98

## 2) Expected behavior
The modal nested p:dialog  should be accessible when it is open 
...

## 3) Actual behavior
if the nested p:dialog is modal, the modal icon covers the entire page, thus making modal dialog itself inaccessible. When dialog is not modal, everything works fine
..

## 4) Steps to reproduce
In the provided sample xhtml, click  "Open dialog" button, which opens outDlg.
Then, from that dialog, click the ""Open nested dialog" button in order to open nested dialog.
The nested dialog became inaccessible
.. 

## 5) Sample XHTML

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<h:head>
 
</h:head> 
<h:body> 
   <p:commandButton value="Open dialog" process="@this" oncomplete="PF('widget_outDlg').show();"/>

	<p:dialog id="outDlg" widgetWar="outDlg" dynamic="true">
	     <p:commandButton value="Open nested dialog" process="@this" oncomplete="PF('widget_nestedDlg').show();"/>
	     <p:dialog id="nestedDlg" widgetWar="nestedDlg" modal="true" dynamic="true"/>
	</p:dialog>
</h:body>
</html>


```

## 6) Sample bean
There is no Java code involved at all

**Comment by JeeDevUser** [comment]
![nested_modal_dialog](https://user-images.githubusercontent.com/56500986/70375881-7d89ca80-1903-11ea-984d-b69d6804036f.png)

**Comment by melloware** [comment]
See: https://stackoverflow.com/questions/8970685/modal-confirmdialog-over-modal-dialog-everything-is-blocked

**Comment by melloware** [comment]
This works fine for me using appendTo. Closing ticket.
```xml
<h:form>
	<p:commandButton value="Open dialog" process="@this" oncomplete="PF('outDlg').show();"/>

	<p:dialog id="outDlg" widgetVar="outDlg" dynamic="true" appendTo="@(body)">
		<p:commandButton value="Open nested dialog" process="@this" oncomplete="PF('nestedDlg').show();"/>
		<p:dialog id="nestedDlg" widgetVar="nestedDlg" modal="true" dynamic="true" appendTo="@(body)"/>
	</p:dialog>
</h:form>
```
