### ISSUE TITLE
FileUpload:  VirusTotal API limit error 

### ISSUE THREAD

**Issue by zakhdar** [primefaces/primefaces#5417]
By defaut VirusTotal have a rate limit (4 requests/minute) for non premium user.
I you try to scan more than 4 files in one minute you get a JSON exception because the response from Virus Total is not correctly managed 

```java
org.primefaces.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.primefaces.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.primefaces.json.JSONObject.<init>(JSONObject.java:196)
	at org.primefaces.json.JSONObject.<init>(JSONObject.java:320)
	at org.primefaces.virusscan.impl.VirusTotalVirusScanner.performVirusScan(VirusTotalVirusScanner.java:73)
	at org.primefaces.virusscan.VirusScannerService.performVirusScan(VirusScannerService.java:72)
	at org.primefaces.util.FileUploadUtils.performVirusScan(FileUploadUtils.java:280)
```

1) Environment
- PrimeFaces version: 7.0
- Application server + version: Wildlfy 17.0.1
- Affected browsers: Firefox / Chrome

## 2) Expected behavior

Have a correct message that indicate in log that we have exceeded the rate limit or the default message : "Cannot perform virus scan"   (VirusTotalVirusScanner.java:92)

## 3) Actual behavior

JSON Exception 

## 4) Steps to reproduce
create a fileupload page with performVirusScan=true , create a  free account on Virustotal try to scan more than 4 files in one minute

**Comment by tandraschko** [comment]
A PR would be great

**Comment by zakhdar** [comment]
Ok i will prepare this tomorrow

**Comment by melloware** [comment]
PR submitted to catch JSON Exception and display the default "Cannot perform virus scan" error message

**Comment by Rapster** [comment]
Is is possible to see the body response? From the API doc, it should return a 204 code

**Comment by melloware** [comment]
I think we would have to modify this code since the current code is just doing url.openConnection() we are never even checking the HTTP response code its just calling an assuming. So I took the least impactful approach in catching the JSONException.  We would need to change to something like...

```java
URL url = new URL("http://example.com");
HttpURLConnection connection = (HttpURLConnection)url.openConnection();
connection.setRequestMethod("GET");
connection.connect();

int code = connection.getResponseCode();
```

**Comment by Rapster** [comment]
I understand, but I think it's important to inform the end user about that rate limit error. The current expection thrown is not clear enough. i like your last proposal, but I just wonder what the body message looks like...

**Comment by melloware** [comment]
Updated my PR to give better error messages regardless of body.
