### ISSUE TITLE
Issue with resizing layoutUnit with iframe

### ISSUE THREAD

**Issue by michiel-BG** [primefaces/primefaces#542]
When I build two resizable layoutUnits (like in the showcase: http://www.primefaces.org/showcase/ui/panel/layout/element.xhtml) and put an iframe in one of the two units, the resizing does not work properly anymore. Sometimes it doesn't resize at all and when it does, it is really jerky. I am using PrimeFaces 5.1.

**Comment by kukel** [comment]
How do you expect anyone to reproduce this? Code and a better explanation of **what does not resize at all** the iframe? Parts of the layout? and what is jerky?

**Comment by tandraschko** [comment]
Will close it for now as no example was provided.
You can still create a new issue and provide all informations requested by our issue template.
