### ISSUE TITLE
DatePicker: Ajax only updates other components the first time the date is selected

### ISSUE THREAD

**Issue by aLeXcBa1990** [primefaces/primefaces#5420]
I have a DatePicker that updates a table when selecting a date, but only updates the table the first time I select the date.

## 1) Environment
- PrimeFaces version: 8.0.RC1
- Application server + version: spring-boot-starter-undertow
- Affected browsers: Firefox / Chrome

## 2) Expected behavior

When selecting a date in the DatePicker with ajax, the other components must be updated regardless of how many times I change the date

## 3) Actual behavior

When selecting a date in the DatePicker, it updates its form, when selecting another date it no longer updates the form.

## 4) Steps to reproduce

Create a DatePicker that updates the data of a DataTable using ajax, select a value in the DatePicker (this will update the DataTable) and then select another value in the DatePicker (the DataTable will not be updated)

**Comment by tandraschko** [comment]
Example please or a forked primefaces-test Project 😜
