### ISSUE TITLE
Dialog: closeDynamic fails due to invalid use of data-widgetvar

### ISSUE THREAD

**Issue by stklcode** [primefaces/primefaces#5422]
## 1) Environment
* **PrimeFaces version:** 7.0.10
* **Does it work on the newest released PrimeFaces version?** No.
* **Does it work on the newest sources in GitHub?** In works in showcase.
* **Application server + version:** Apache TomEE 8.0.0 (Tomct 9.0.22, MyFaces 2.3.4)
* **Affected browsers:** all tested

## 2) Expected behavior

Opening and closing a dialog from backend bean by
```java
PrimeFaces.current().dialog().openDynamic("/myDialog", opt, par);
/* ... */
PrimeFaces.current().dialog().closeDynamic(res);
```
should open and close the dialog.

## 3) Actual behavior

Opening works correctly, but adds the old attribite `data-widgetvar` to the markup (shortened):
```html
<div id="myForm:dlgBtn_dlg" class="..." data-pfdlgcid="..." data-widgetvar="myForm_dlgBtn_dlgwidget" role="dialog">
<!-- ... -->
</div>
```
Closing throws this error in the browser console:
```
core.js.xhtml?ln=primefaces&v=7.0.10:1 Widget for var 'undefined' not available!
components.js.xhtml:1 Uncaught TypeError: Cannot read property 'cfg' of undefined
```
This line tries to read `data-widget` which is not populated:
https://github.com/primefaces/primefaces/blob/45bb466d5a52707fa0542a0dbf68fb5ddcc8abc3/src/main/resources/META-INF/resources/primefaces/core/core.dialog.js#L142

## 4) Steps to reproduce

Implement an application like this:
https://www.primefaces.org/showcase/ui/df/basic.xhtml

## 5) Sample XHTML

**page.xhtml**
```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<f:view>
    <h:body>
        <h:form id="myForm">
            <p:commandLink actionListener="#{myBean.openDialog}" id="openDlg" value="Open Dialog"/>
        </h:form>
    </h:body>
</f:view>
</html>
```

**myDialog.xhtml**

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<f:view>
    <h:body>
        <h:form id="myDialogForm">
            <p:commandLink actionListener="#{myBean.closeDialog}" id="closeDlg" value="Close Dialog"/>
        </h:form>
    </h:body>
</f:view>
</html>
```

## 6) Sample bean

**MyBean.java** (minimal extract from real project, translated from Scala)
```java
import org.primefaces.PrimeFaces;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Named("myBean")
@SessionScoped
public class MyBean implements Serializable {
    public void openDialog() {
        Map<String, Object> options = new HashMap<>();
        options.put("modal", true);
        options.put("width", 650);
        options.put("height", 500);
        Map<String, List<String>> param = new HashMap<>();
        param.put("ids", Arrays.asList("123", "456"));

        PrimeFaces.current().dialog().openDynamic("/myDialog.xhtml", options, param);
    }

    public void closeDialog() {
        PrimeFaces.current().dialog().closeDynamic(null);
    }
}
```

**Comment by tandraschko** [comment]
good analysis! a PR to fix it would be a next good step :)

**Comment by melloware** [comment]
@tandraschko I think this is a bug in Elite as in 8.0 we only use data-widget everywhere.  @mertsincan I feel like there is a mix between data-widgetvar and data-widget in Elite.

I have attached my sample project and its working fine in 8.0.
[pf-5422.zip](https://github.com/primefaces/primefaces/files/3944889/pf-5422.zip)

**Comment by stklcode** [comment]
Apparently my analysis was not good enough :wink:
I'm sorry, but PrimeFaces already does it right - at least in 7.0.8 and 7.0.10 (Elite license) and 8.0 (master).

https://github.com/primefaces/primefaces/blob/45bb466d5a52707fa0542a0dbf68fb5ddcc8abc3/src/main/resources/META-INF/resources/primefaces/core/core.dialog.js#L17-L19

Somebody in our company had the (not so) gread idea to overwrite the `PrimeFaces.dialog.DialogHandler.openDialog` function in one of our core JS libs to add some additional behavior. This code was based on some early PF 6.x release... :grimacing:
