### ISSUE TITLE
CSS: Replace non-standard zoom property

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5429]
Go to the showcase page in Firefox 71+: https://www.primefaces.org/showcase/ui/panel/accordionPanel.xhtml

In the console it reports:

> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

They are correct if you look here its a non standard CSS which used to be used to fix IE8 issues.
https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

It should be replaced with:
```css
transform: scale(1); /* Standard Property */
transform-origin: 0 0;  /* Standard Property */
```

**Components affected:**
- [x] Accordion
- [x] AutoComplete
- [x] Dialog
- [x] Forms
- [x] Menu
- [x] Paginator
- [x] Tabview
- [x] Tree
- [x] Omega Theme (@mertsincan)

**Comment by mertsincan** [comment]
Hi @melloware,

I find an issue related to transform-origin: 0 0; Please check selectOneMenu demo;
![Screen Shot 2019-12-18 at 13 48 41](https://user-images.githubusercontent.com/11868120/71080011-5ea9f480-219d-11ea-9e72-e1ddbca348cc.png)

**Comment by melloware** [comment]
I will investigate.

**Comment by melloware** [comment]
I have fixed all the issues and tested in multiple browsers and everything I an see seems to be working.

**Comment by cocorossello** [comment]
Hi, this is causing problems with other components with z-index.

If you open a bootstrap modal that is rendered inside a .ui-tab component it doesn't work right with the transform. It works fine with the zoom: 1

**Comment by melloware** [comment]
@cocorossello Feel free to investigate.  Zoom is not supported on Firefox.  So you may have to implement some custom styles for this to work without using zoom CSS.

**Comment by metaxmx** [comment]
Hi,
The `transform: scale(1)` creates a different "stacking context" for the HTML element, which will break the `z-index` comparison between elements inside the container element and those outside. 
The stacking contexts are explained here (MDN): https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

In short, if you have a container element with a non-empty `transform` property, all `z-index` attributes of elements inside this container element will have only an effect among each other, but won't have any effect against all elements outside this container element.

This is especially problematic, if you have backdrops from e.g. a modal dialog, which is placed as child-element of `<body>`, while the dialog itself (or any element which should be above the backdrop) is located inside the container lement (e.g. a TabView).

@melloware please have a look at this again, as the change introduced in 8.0 breaks z-index-based layouting concepts, e.g. #5675 
Although the `zoom: 1` wasn't standard and did nothing in Firefox, at least it did not create a new stacking context and left the z-index usable.

I'm not sure, why the `transform: scale(1)` is there in the first place. It doesn't seem to fulfil any purpose. If it's really only for some old IE8 problems and you need to support it (although not even microsoft supports it any more), can't you just keep the `zoom` if IE8 understands it? It won't break code in newer browsers then ...
And if you don't support IE8 any more, I believe you can just drop it altogether, can't you?

**Comment by melloware** [comment]
@metaxmx as IE is no longer supported I agree with removing this entirely!
