### ISSUE TITLE
FileUpload: button doesn't work for 100% in advanced mode

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5431]
http://primefaces.org/showcase/ui/file/upload/auto.xhtml

The "hand" cursor isn't shown everywhere in the button and sometimes the click doesn't open the upload window (at least in harmony e.g.).

**Comment by tandraschko** [comment]
If somehone has time to check it...

**Comment by Rapster** [comment]
> The "hand" cursor isn't shown everything in the button

What is supposed to show? What is everything?

> sometimes the click doesn't open the upload window (at least in harmony e.g.).

I know it can take some time to open, but it does open eventually. Any js errors?

**Comment by tandraschko** [comment]
sorry, "everywhere". If you have the cursor near the border, often doesn't show the hand cursor.

no js error. I think it opens always in the showcase but my customer use a modified harmony and there it doesn't always open.

**Comment by Rapster** [comment]
Looks fine on the showcase, I think it's a premium theme issue. Up to @mertsincan to fix it

**Comment by tandraschko** [comment]
For me it's not fine in the showcase. If you have the cursor on the button, there is no "hand" as cursor. All other buttons are working fine. (tested in current online showcase + FF)

**Comment by Rapster** [comment]
Which browser? (Looks fine on Chrome 78)

**Comment by tandraschko** [comment]
newest FF

**Comment by Rapster** [comment]
I confirm the problem on FF (Next time please follow issue template :yum: )

**Comment by mertsincan** [comment]
> If you have the cursor on the button, there is no "hand" as cursor. All other buttons are working fine. 

Replicated it. We need to add a style to fileupload.css in core. Maybe,
`.ui-fileupload-choose.ui-state-hover { cursor: pointer;}`

**Comment by melloware** [comment]
I can look at this one if you guys want?

**Comment by mertsincan** [comment]
@tandraschko 
> ... the click doesn't open the upload window (at least in harmony e.g.).

Does it work in showcase?

**Comment by tandraschko** [comment]
+1 for the style overwrite

nope, even not in the harmony showcase. I think it's up to my customers code. 
So if the style is fixed, we can close it.

**Comment by melloware** [comment]
OK I tried that style and that does not fix it.  I even tried to overwrite with `cursor: pointer !important;` in a few places and none of them have any effect.

**Comment by melloware** [comment]
It also happens on Mirage theme.  Seems to be the "border-box" styled premium themes have the issue in Firefox.

**Comment by wsaca** [comment]
You could try disabling pointer-events on the hidden input:
```css
.ui-fileupload-choose input {
  pointer-events: none;
}
```

**Comment by melloware** [comment]
@wsaca that does the trick!   I am going to submit a PR.
