### ISSUE TITLE
DataTable: rename filterMeta back to filterBy

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5435]
for better naming and backward compatitiliby

**Comment by Rapster** [comment]
I would also rename `sortMeta` into `sortBy` _(at least for consistency)_

**Comment by tandraschko** [comment]
Not possible - sortBy is already there. I created another issue for 9.0 for it.

**Comment by Rapster** [comment]
Ah I see... From the doc sounds like it does the same thing. Ideally, maybe we should have only sortBy (which can take a String/SortMeta/List<Meta>)
