### ISSUE TITLE
Provide a alternative for p:component function

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5441]
Actually the replacement is:

`#{p:resolveClientId('@id(myID)', view)};`

but this doesn't work with EL, as the param of @id is not resolved as expression:

`#{p:resolveClientId('@id(cc.attrs.target)', view)};`

also a string concat with "+" doesn't work as it's handled as int. The only solution is:

`#{p:resolveClientId('@id('.concat(cc.attrs.value).concat(')'), view)});`

I think we should provide p:component again but with a better name

**Comment by tandraschko** [comment]
maybe something like:

`#{p:resolveFirstComponentWithId(cc.attrs.target, view).clientId}` ?

Thats really what i does: find the first UIComponent with the ID equals the param; 
This is not unique as it's not a search expression or absolute path or something.
I don't like to name it `resolveFirstClientIdWithId`, it sounds weird.
I think `resolveFirstComponentWithId` is good. the clientId is just a attribute of the returned UIComponent.

@melloware @Rapster ?

**Comment by tandraschko** [comment]
And it's also usable for p:widgetVar:

`#{p:resolveFirstComponentWithId(cc.attrs.target, view).widgetVar}`

**Comment by melloware** [comment]
I like it.

**Comment by tandraschko** [comment]
@melloware can you please test it? I didnt test it yet.

**Comment by melloware** [comment]
I will test it today.

**Comment by melloware** [comment]
This worked like a charm! Thanks for this fix.
