### ISSUE TITLE
DataExporter: Pre/PostProcessors not called

### ISSUE THREAD

**Issue by carlbradwell17** [primefaces/primefaces#5442]
## 1) Environment
- PrimeFaces version: 8.0.RC1
- Does it work on the newest released PrimeFaces version? Yes, works on 7.0

## 2) Expected behavior

If I set the postProcessor or preProcessor attribute on a p:dataExporter, it should call the method.

## 3) Actual behavior

The method is not called at all, for postProcessor or preProcessor and where type is any of XML,CSV,XLS or PDF.

## 4) Steps to reproduce

Create a p:dataExporter for a DataTable. Set postProcessor attribute, pointing to a public void method in a bean, which takes an Object property.

## 5) Sample XHTML

<p:commandButton value="Download XML" ajax="false">
<p:dataExporter type="xml" target="myTable" fileName="myFile" postProcessor="#{dataExporterBean.postProcessXML}" />
</p:commandButton>

## 6) Sample bean

@Named
@SessionScoped
public class DataExporterBean implements Serializable {

private static final long serialVersionUID = 1L;

    public void postProcessXML(Object document) throws IOException, BadElementException, DocumentException {
        
    	String string = ((StringBuilder) document).toString();
    	
    	((StringBuilder) document).replace(0, ((StringBuilder) document).length(), string);
    }
    
}

**Comment by melloware** [comment]
Confirmed it doesn't look like its working on the showcase: https://www.primefaces.org/showcase/ui/data/dataexporter/customizedDocuments.xhtml

@Rapster i am assuming this is related to all that Exporter refactoring to move the exporters to the package.

**Comment by Rapster** [comment]
Fixed! Thanks for reporting

**Comment by carlbradwell17** [comment]
Tested on snapshot build, now working as expected.
