### ISSUE TITLE
Bean validation enabled

### ISSUE THREAD

**Issue by gvozdevs** [primefaces/primefaces#5443]
## 1) Environment
- PrimeFaces version: 8.0.RC1

## 2) Expected behavior
When javax.faces.validator.DISABLE_DEFAULT_BEAN_VALIDATOR is setter to true, PrimeConfiguration.beanValidationAvailable is set to false

## 3) Actual behavior
When javax.faces.validator.DISABLE_DEFAULT_BEAN_VALIDATOR is setter to true, PrimeConfiguration.beanValidationAvailable is also set to true

Error commit https://github.com/primefaces/primefaces/commit/246a12d88fa7b112d9e020871e86bb119085686b#diff-a1fbd983ec1ef231114b23c0b9db778a

Old code:
`beanValidationEnabled` = (value == null) ? true : !Boolean.valueOf(value);`

New code:
`beanValidationEnabled = Boolean.parseBoolean(value);`

**Comment by tandraschko** [comment]
to be honest, i would just revert the commit it for now

**Comment by Rapster** [comment]
Fixed! Thanks for reporting
