### ISSUE TITLE
InputNumber is not working with initial value

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#5444]
Reported By PRO User;
> We found an major issue with this version: if we load a form having an valorized p:inputNumber and we submit the form without change anything, the component will send null to the BakingBean.

**Comment by melloware** [comment]
@mertsincan @tandraschko Shouldn't this have fixed this issue a while ago: https://github.com/primefaces/primefaces/issues/4543

I thought this was also done to prevent the JS code from doing it because of that issue above reported a performance problem with lots of InputNumbers?

**Comment by tandraschko** [comment]
i think so
@mertsincan did you just copy the code from elite to trunk, without trying it?

**Comment by melloware** [comment]
also, I use InputNumber if 25 applictions using 7.X elite and all of our apps our working fine.  I don't think this fix is necessary.

**Comment by mertsincan** [comment]
Adding the value inside the renderer is not the right approach. When you set an initial value, 
you write it to the hidden area without using the autoumeric api on #4543. Then, when you change the value in input number, the formatted values are written to the hidden input. Exp;
Initial value: 123.5678
Component: decimalPlaces=2
If you write this value inside Renderer, the value of hidden input is 123.5678. This is wrong.
You need to send the initial value to autonumeric API. Maybe, users can submit without changing anything.

**Comment by melloware** [comment]
I guess that makes sense. But the ticket above says the value is "null" when its submitted.  Shouldn't it be 123.5678 in your example and not NULL because we are setting the hidden field always?

**Comment by mertsincan** [comment]
Yes, this ticket is related to 7.0.x. On 8.0, the behavior of the inputnumber is incorrect for initial values.
Another example on 8.0 before my fix;
decimalPlaces=2

Initial value: 123.456
The value of hidden input: 123.456
Submitted value: 123.456

Initial value: null
The value of hidden input after you enter 123.456 to inputnumber: 123.45
Submitted value: 123.45

the behaviors are very different.

**Comment by melloware** [comment]
Understood thanks for the explanation!
