### ISSUE TITLE
Create a Testsuite

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5447]
PrimeFaces offers a extraordinary amount of UI-components which are extensive configurable.

This causes sometimes issues because it´s hard the test all possible mutations of the components. Sometimes we create regressions when fixing a bug. Some impulsive people call PrimeFaces rubbish because of corner-cases which do not work as expected.

During this year i tried to extend the showcase-project whenever i added features to components or made bugfixes/refactorings. But IMO it does not make sense to put "everything" into the showcase-project. (It may look bloated.)

IMO it would make sense to 
a) create a "internal" Testsuite-project OR
b) add a "internal" section to the Showcase-project which is hidden in the deployed public project

IMO this would be a mid- to longterm project.

Whenever we touch something we add this to the Testsuite. Maybe instead of building a small sandbox-example to reproduce a issue we add this to the Testsuite-project.
The next time you come back and have to touch the component again you already have something in the Testsuite-project to run some (manual) regression-tests.

This would allow us to add automated ui-test´s (eg Selenium) at a later point in time.

**Comment by melloware** [comment]
Thomas has been working on this PrimeFaces Selenium project. Maybe you could contribute?  
https://github.com/primefaces-extensions/primefaces-selenium

**Comment by tandraschko** [comment]
I think the first step is just a much bigger Showcase
Like a database with samples

**Comment by christophs78** [comment]
First of all: We all do our best to avoid regressions. And we do most of the time a good job.

https://github.com/primefaces-extensions/primefaces-selenium is a good project. It help´s us to test applications built with PrimeFaces. Maybe i contribute at some point in the future. :-) But IMO it does not (direct) help us with improving qualitiy of PrimeFaces itself.

When we fix bug´s or add features we often build small sandbox-examples we throw away afterwards. When we touch the component the next time it´s not always easy to think of all the possible combinations how to use it. That´s the thing that causes sometimes regressions.

Making the Showcase bigger as suggested by @tandraschko is a valid way. I´ll contine to contribute to the Showcase to make it bigger.

**Comment by melloware** [comment]
OK Integration Test project has been created and we welcome contributors to start adding test cases!

https://github.com/primefaces-extensions/primefaces-integration-tests

`mvn clean package -DskipTests`
`mvn test`
