### ISSUE TITLE
primefaces-8.0.RC1.jar: META-INF/LICENSE.txt is Apache License, not MIT

### ISSUE THREAD

**Issue by maruTA-bis5** [primefaces/primefaces#5449]
## 1) Environment
- PrimeFaces version: 8.0.RC1
- Does it work on the newest released PrimeFaces version? Version? No. 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No. 87fd21c71ecb9e7669d76def21cd6375c1b42fbd
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior
In primefaces-8.0.RC1.jar, `META-INF/LICENSE.txt` content should same as PrimeFaces' license, MIT.

## 3) Actual behavior
`META-INF/LICENSE.txt` content is "Apache License, Version 2.0".

## 4) Steps to reproduce
n/a

## 5) Sample XHTML
n/a

## 6) Sample bean
n/a

**Comment by Rapster** [comment]
LICENSE.txt in resources/META-INF needs to be replaced by MIT License. Being said, we should use https://www.mojohaus.org/license-maven-plugin/ since mycilla is no longer maintened
