### ISSUE TITLE
Dialog: improve accessibility

### ISSUE THREAD

**Issue by dariorios** [primefaces/primefaces#545]
There are a few of issues that needs to have the dialog framework data in order to be able to accesible support. 

For example, there's not support for the ARIA attributes. In this link, appears a few of the contemplations that the dialog should take to work accesible.

http://www.nczonline.net/blog/2013/02/12/making-an-accessible-dialog-box/

The normal dialog implements a few of this things that actually works in other versions and they are useful for this component.

**Comment by melloware** [comment]
I think this is fixed with my PR: https://github.com/primefaces/primefaces/pull/4044 Relates to #4043

**Comment by melloware** [comment]
Relates to #4043
