### ISSUE TITLE
Global: Invalid state for inputs referenced from a FacesMessage via clientId

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5454]
We sometimes add errors to inputs via Java-business-logic:
`FacesContext.getCurrentInstance().addMessage("form:txt", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error!", "Contact admin."));`

This come with the limitation, that this input does not get the same red border like inputs which have an validation-error.

The following generic code make setValid(false) to all input´s which have a error-message.
```
private void transferFacesErrors2NotValid() {
	Spliterator<String> spliterator = Spliterators.spliteratorUnknownSize(FacesContext.getCurrentInstance().getClientIdsWithMessages(), 0);
	StreamSupport.stream(spliterator, false).forEach(clientId -> {
		long errors = FacesContext.getCurrentInstance().getMessageList(clientId).stream().filter(m -> m.getSeverity().equals(FacesMessage.SEVERITY_ERROR)).count();

		if (errors>0) {
			UIComponent uiComp = FacesContext.getCurrentInstance().getViewRoot().findComponent(clientId);
			if (uiComp instanceof UIInput) {
				((UIInput) uiComp).setValid(false);
			}
		}
	});
}
```
By setting valid to false the inputs get the red border.

Is this something we may add in some way to PrimeFaces?

**Comment by tandraschko** [comment]
to be honest, i don't know :D
you are the first since ~10 years PrimeFaces which asked about such a feature

**Comment by christophs78** [comment]
look at eg https://forum.primefaces.org/viewtopic.php?t=25085

**Comment by tandraschko** [comment]
ok sorry, you are the second one :D

**Comment by tandraschko** [comment]
I think we can add it with a config flag in 9.0 which is disabled per default

**Comment by tandraschko** [comment]
@christophs78 thats a present for you :P You will just need to test it.

**Comment by melloware** [comment]
nice work @tandraschko clever change!

**Comment by christophs78** [comment]
Thank you! I´ll provide some integration-tests.

**Comment by christophs78** [comment]
@tandraschko : Just started with some integration-tests. see https://github.com/primefaces-extensions/primefaces-integration-tests/pull/30
But:
![image](https://user-images.githubusercontent.com/10461942/91898956-c6a55a00-ec9c-11ea-886c-dc23ca8af1b1.png)
I don´t get the PrimeFacesContext for `FacesContext.getCurrentInstance()`. As a result the classic JSF addMessage-method is called.
Am I missing something?

**Comment by tandraschko** [comment]
should work actually
can you debug PrimeFacesContextFactory?

**Comment by christophs78** [comment]
From my understanding/debugging `javax.faces.context.FacesContext.setCurrentInstance(xx)` is never called for `PrimeFacesContext`.
So currentInstance is the MyFaces/Mojarra FacesContextImpl.

`PrimeFacesContextFactory` is used and `PrimeFacesContext`-instances are created. But not connected to currentInstance.

**Comment by tandraschko** [comment]
weird because PrimeFacesContext#setResponseWriter is called

**Comment by tandraschko** [comment]
should work now

**Comment by christophs78** [comment]
> weird because PrimeFacesContext#setResponseWriter is called

IMO because of the following inside FacesServlet
![image](https://user-images.githubusercontent.com/10461942/91945841-5aa80d80-ecff-11ea-8f3f-5c048163e955.png)

I´ll check your last commit. :-)

**Comment by christophs78** [comment]
> should work now

look good
