### ISSUE TITLE
update first and rows attribute in primefaces lazy loading datalist

### ISSUE THREAD

**Issue by mrclBIE** [primefaces/primefaces#547]
I have a problem with my primefaces DataList:

It is a searchresult list with a paginator. I set the first and rows primefaces attributes to be in my backing bean to recover the status after a page reload. So if an user goes through the results, is maybe on page 3 with 15 results in list, and reloads the page, he is at exactly this position.

Now the problem:

If the user starts a new search, I set the first and rows attribute to the start values (0 and 10) in my backing bean, to start in the new result list at the beginning of the list. BUT it shows the last page 3 with 15 results. If the user reloads the page now, the paginator is at the correct position, I set in my backing bean.

The problem propably raises because the lazyload function is called in the RENDER_RESPONSE phase and not in the UPDATE_MODEL_VALUE phase. For DataTable there was a similiar problem http://forum.primefaces.org/viewtopic.php?f=3&t=23235 which was resolved by changing some code lines from one to another method. But DataList do not have the processUpdates() method...

Does anyone now, how I can achieve, that I can control the first and rows attribute in my backing bean?

I have a workaround for it, but it doesn´t make me happy... I call handlePagination of the DataList, so that it displays correctly. But in this case the load method is called again, which I like to avoid!

**Comment by cagataycivici** [comment]
Please use forum for these kinds of questions not the issue tracker.
