### ISSUE TITLE
DialogActionListener.java: needs default constructor

### ISSUE THREAD

**Issue by Didjit01** [primefaces/primefaces#5472]
## 1) Environment
- PrimeFaces version: 7.0
- MyFaces: 2.3.5, 2.3.6
- Tomcat 9

## 2) Expected behavior
In `faces-config.xml`, should be able to specify this:
```
<action-listener>
     org.primefaces.application.DialogActionListener
</action-listener>
```

## 3) Actual behavior
Faces initialization fails (`MyFaces: FacesConfigurator#configureApplication( )`).

MyFaces initialization calls `ClassUtils#buildApplicationObject` with a list of ActionListener classes and `null` as the default implementation.  With no default, MyFaces attempts to instantiate the ActionListener with a default constructor.  However, DialogActionListener only provides a parameterized constructor `public DialogActionListener(ActionListener base)`

Most other subclasses of ActionListener appear to implement a default constructor.

## 4) Steps to reproduce
Add the following to faces-config.xml:
```
<action-listener>
     org.primefaces.application.DialogActionListener
</action-listener>
```

## 5) Sample XHTML
N/A

## 6) Sample bean
N/A

## 7) Work-around
Extend DialogActionListener with your own class that provides a default constructor.  Specify this new class in the faces-config.xml.

**Comment by tandraschko** [comment]
I think it's an bug in MyFaces.
Mojarra first looks for a constructor with param, also if the param is null. As fallback the default constructor is used.
I will create a MyFaces issue and link it here.

**Comment by tandraschko** [comment]
@Didjit01 i really wonder about your environment. JSF itself has a action-listener and this should be used as base for DialogActionListener. So the base-action-listener MUST not be null.

Therefor it also never occurs e.g. in the primefaces showcase.
Can you try to not use the myfaces-bundle but the api/impl jar? Maybe its related to this.

**Comment by Didjit01** [comment]
@tandraschko when I dug into the MyFaces code a bit, the call to buildApplicationObject is called with an explicit null for the base object.  Perhaps that's the root bug?  But I must confess I'm a real novice at JSF, so my setup should remain suspect.

**Comment by tandraschko** [comment]
Yes, thats what i mean
if you check the MyFaces code, there is: `<action-listener>org.apache.myfaces.application.ActionListenerImpl</action-listener>`
which is the default impl.

As i said, please try to not use the myfaces-bundle, just the api and impl jar.

If that doesn't work ad if you send me your applciation, i can debug whats wrong. 

For now i will close the issue as it's not a PF issue.

**Comment by tandraschko** [comment]
@Didjit01 maybe you can just grab some MyFaces+SpringBoot sample app and check if it works fine for you.
Joinfaces has something
