### ISSUE TITLE
Schedule: JS error (RangeError: invalid language tag: "pt_BR")

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#5473]
## 1) Environment
- PrimeFaces version: 8.0.RC2
- Does it work on the newest released PrimeFaces version? Version? 7.0 yes
- Does it work on the newest sources in GitHub? no
- Affected browsers: all

## 2) Expected behavior
Should display normal

## 3) Actual behavior
Error in browser console

## 4) Steps to reproduce
add pt_BR locale to faces-config:
`<locale-config>
			<default-locale>pt_BR</default-locale>
			<supported-locale>pt_BR</supported-locale>
		</locale-config>`

## 5) Sample XHTML
Using the showcase schedule exemple is sufficient

**Comment by tandraschko** [comment]
@christophs78 can you have a look plz?

**Comment by christophs78** [comment]
@erickdeoliveiraleal: Thanks for reporting this issue. With PrimeFaces 8.0 we use FullCalendar 4.x. FullCalendar 4.x comes with it´s own localication-mechanism. Just provided a PR which adjusts Java/PrimeFaces-locale to FullCalendar-locale.
