### ISSUE TITLE
Unable to build it

### ISSUE THREAD

**Issue by Betlista** [primefaces/primefaces#5476]
## 1) Environment
- PrimeFaces version:
The last one in GitHub - last commit b1188af2273eb726c26627b9647255ccaea822a0
- Does it work on the newest released PrimeFaces version? Version?
N/A
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No.
- Application server + version: N/A
- Affected browsers: N/A

## 2) Expected behavior

After cloning from git one can build it.

## 3) Actual behavior

I'm getting compilation error:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /c:/betlista/Git/GitHub.com/PrimeFaces/primefaces/src/main/java/org/primefaces/util/HtmlSanitizer.java:[37,13] cannot access com.google.common.base.Predicate
  class file for com.google.common.base.Predicate not found
[ERROR] /c:/betlista/Git/GitHub.com/PrimeFaces/primefaces/src/main/java/org/primefaces/util/HtmlSanitizer.java:[42,13] cannot access com.google.common.base.Function
  class file for com.google.common.base.Function not found
[INFO] 2 errors
```

Additional details:

```
c:\betlista\Git\GitHub.com\PrimeFaces\primefaces>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

c:\betlista\Git\GitHub.com\PrimeFaces\primefaces>mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: c:\betlista\progs\no-install\apache-maven-3.5.3\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: c:\java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

c:\betlista\Git\GitHub.com\PrimeFaces\primefaces>java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b35)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b35, mixed mode)
```

## 4) Steps to reproduce

git clone ...
mvn clean compile

## 5) Sample XHTML

N/A

## 6) Sample bean

N/A

**Comment by tandraschko** [comment]
works finr for me with jdk1.8.0_161 and Apache Maven 3.5.4

**Comment by tandraschko** [comment]
also our builds are fine: https://travis-ci.org/primefaces/primefaces

**Comment by Betlista** [comment]
Interesting, and can you tell me, where the dependency is coming from?

When I added:

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>28.1-jre</version>
        </dependency>

it got fixed for me.

In dependency tree (mvn dependency:tree) I see only:

```
[INFO] +- org.apache.tika:tika-java7:jar:1.22:test
[INFO] |  +- org.apache.tika:tika-core:jar:1.22:test
[INFO] |  \- org.apache.tika:tika-parsers:jar:1.22:test
[INFO] |     +- com.sun.activation:jakarta.activation:jar:1.2.1:test
                ...
[INFO] |     +- com.google.guava:guava:jar:28.0-jre:test
```

...but this is for tests.

**Comment by tandraschko** [comment]
its from the optional tika integration for filetype detection (a fileupload security feature)

**Comment by tandraschko** [comment]
maybe we can update the rika version after 8.0 release and also use the java8, not java7 dependency. Maybe this will fix it

**Comment by Betlista** [comment]
I tried with Eclipse and yes, Eclipse has no problem with that, because Eclipse does not work as it should with maven projects. Is that how you tested?

If you try from **command line** you should see same error.

But how it worked on Travis CI is a big unknown for me...

**Summary** (as I see it at the moment):
`com.google.common.base.Function` and `com.google.common.base.Predicate` are from Guava, but for primefaces this is a test dependency and while it is used in `org.primefaces.util.HtmlSanitizer` (not a test class) maven is (correctly) complaining.

**Fix**
Add guava explicitly as a dependency, maybe `28.0-jre` as tika is using the same.

**Comment by tandraschko** [comment]
i use CMD ;)

adding guava is not a fix, we  don't use guava. it's just a dependency from a optional dependency of primefaces.

**Comment by Betlista** [comment]
Ok, the problem was (of course) on my side...

I had warnings:

```
[WARNING] The POM for com.healthmarketscience.jackcess:jackcess:jar:3.0.1 is missing, no dependency information available
[WARNING] The POM for com.healthmarketscience.jackcess:jackcess-encrypt:jar:3.0.0 is missing, no dependency information available
[WARNING] The POM for org.ow2.asm:asm:jar:7.2-beta is missing, no dependency information available
[WARNING] The POM for com.rometools:rome:jar:1.12.1 is missing, no dependency information available
[WARNING] The POM for com.github.junrar:junrar:jar:4.0.0 is missing, no dependency information available
[WARNING] The POM for org.apache.opennlp:opennlp-tools:jar:1.9.1 is missing, no dependency information available
[WARNING] The POM for com.github.openjson:openjson:jar:1.0.11 is missing, no dependency information available
[WARNING] The POM for com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:jar:20190503.1 is missing, no dependency information available
```

on maven build

The important one in this case was 

```
[WARNING] The POM for com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:jar:20190503.1 is missing, no dependency information available
```

because `org.owasp.html.HtmlPolicyBuilder` (used in `org.primefaces.util.HtmlSanitizer`) is using Guava and while dependency info was not available I got that error from maven as well as in Idea.

I fixed it so, that I deleted `com\googlecode\owasp-java-html-sanitizer\owasp-java-html-sanitizer` from local maven repository (it was downloaded and the warning is gone same as compilation problem).

Thanks!
