### ISSUE TITLE
Tree: composite components inside miss their values on update (only mojarra with full state saving)

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#5477]
(Attached the primefaces-test based reproducer, see first comment.)

## 1) Environment
- PrimeFaces version: 6.1.
- Does it work on the newest released PrimeFaces version? Version? No, 7.0.
- Does it work on the newest sources in GitHub? No - checked with com.github.primefaces:primefaces:master-SNAPSHOT.
- Application server + version: Wildfly 10.1, Wildfly 18.1. Also primefaces-test's jetty (mojarra only).
- Affected browsers: Firefox (shouldn't matter).

## 2) Expected behavior

Updating the tree correctly rerenders the composite components in its nodes.

## 3) Actual behavior

Composite components' values dissappear.

## 4) Steps to reproduce

Press the "Update the tree" button. See values dissapear.

![image](https://user-images.githubusercontent.com/8070317/71446772-1019ce80-2738-11ea-8904-90c73f2a388d.png)

## 5) Sample XHTML

The view.
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ccomp="http://xmlns.jcp.org/jsf/composite/composites">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h1>#{testView.testString}</h1>
		<p />
		<h:form>
			<p:tree id="tree" value="#{testView.dateTree}" var="data">
				<p:treeNode>
					<ccomp:outputDate id="od" value="#{data}" />
				</p:treeNode>
			</p:tree>
			<p:commandButton value="Update the tree" process="@this" update="tree" />
		</h:form>

    </h:body>
</html>
```

And the composite component.
```
<ui:component xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough" xmlns:cc="http://java.sun.com/jsf/composite">

	<cc:interface>
		<cc:attribute name="value" type="java.util.Date" required="true" />
	</cc:interface>

	<cc:implementation>
		<span id="#{cc.clientId}" class="comp-date">
			Time: #{cc.attrs.value.time}
		</span>
	</cc:implementation>

</ui:component>
```

## 6) Sample bean

```
package org.primefaces.test;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import org.primefaces.model.TreeNode;
import org.primefaces.model.DefaultTreeNode;

@Named
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }    

    private TreeNode dateTree;

    public TreeNode getDateTree() {
		if (dateTree == null) {
			dateTree = new DefaultTreeNode();
			new DefaultTreeNode(new Date(), dateTree);
			new DefaultTreeNode(new Date(), dateTree);
		}
        return dateTree;
    }

}
```

## Also necessary: disable partial state saving in web.xml:

```
	<context-param>
		<param-name>javax.faces.PARTIAL_STATE_SAVING</param-name>
		<param-value>false</param-value>
	</context-param>
```

**Comment by VsevolodGolovanov** [comment]
[primefaces-tree-with-composite-test.zip](https://github.com/primefaces/primefaces/files/4000526/primefaces-tree-with-composite-test.zip)

**Comment by VsevolodGolovanov** [comment]
The reproducer shows that the issue is not present with the myfaces22 or myfaces23 profiles.
Is it a Mojarra issue? Maybe related to https://github.com/eclipse-ee4j/mojarra/issues/4338 ?
Not sure. Since there is no vanilla JSF tree component, I'm not sure how to correctly reproduce the issue without PrimeFaces.

**Comment by tandraschko** [comment]
JFYI: my personal motivation is quite low to investigate hours into such a bug, which just exists in mojarra and full state saving.
I dont think that full state saving should be used.

**Comment by VsevolodGolovanov** [comment]
Debugging during update shows that when org.primefaces.component.tree.TreeRenderer#encodeTreeNode calls `uiTreeNode.encodeAll(context);` execution gets to the composite component instance's `encodeBegin`, where it calls `pushComponentToEL` as it should, but it doesn't go into this `if`'s body:

```
        // if the pushed component is a composite component, we need to update that
        // stack as well
        if (UIComponent.isCompositeComponent(component))
        {
          _getComponentELStack(_CURRENT_COMPOSITE_COMPONENT_STACK_KEY,
                               contextAttributes).push(component);

          // we only do this because of the spec
          if (setCurrentComponent) {
              contextAttributes.put(UIComponent.CURRENT_COMPOSITE_COMPONENT, component);
          }
        }
```

\- the component is not recognized as composite, so the `cc` references in xhtml evaluate to null.

`javax.faces.component.UIComponent#isCompositeComponent` consults the `component.isCompositeComponent` field, which holds `true` during initial GET render, but for some reason `false` during update.

**Comment by VsevolodGolovanov** [comment]
When a view is restored first all of its components get constructed, then all their states get restored.
During construction `pushComponentToEL` gets called, and so `UIComponent#isCompositeComponent` gets called, and that's how `component.isCompositeComponent=false` gets assigned - because the state was not yet restored, so the attributes are not there.

This is compensated by the following code in `javax.faces.component.UIComponent#processEvent`:

```
public void processEvent(ComponentSystemEvent event) throws AbortProcessingException {
	if (event instanceof PostRestoreStateEvent) {
	assert(this == event.getComponent());
		// if this component has a component value reference expression,
		// make sure to populate the ValueExpression for it.
		ValueExpression valueExpression;
		if (null != (valueExpression = this.getValueExpression("binding"))) {
			valueExpression.setValue(FacesContext.getCurrentInstance().getELContext(), 
					this);
		}
		isCompositeComponent = null;

	}
}
```

This resets the erroneus `false` value in `isCompositeComponent`. Now that the component has its attributes restored, the next time `isCompositeComponent` will be correctly calculated to `true`.

The problem is that PrimeFaces' Tree does not visit its descendants during the `PostRestoreStateEvent` delivering tree walk. The Tree interprets the `SKIP_ITERATION` hint as a reason not to visit descendants at all, which is wrong - instead it should visit them just once, without iterating over the bound `TreeNode` value model.

This has further implications than just affecting full state saving. E.g. judging by the `processEvent` code, it could break the `binding` attribute. And other functionality interested in walking components without iterating over data...

**Comment by VsevolodGolovanov** [comment]
PR submitted: https://github.com/primefaces/primefaces/pull/5479
