### ISSUE TITLE
Calendar: not localized

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#5478]
How to reproduce: Set your language to pt-br in faces-config
`<locale-config>
			<default-locale>pt_BR</default-locale>
			<supported-locale>pt_BR</supported-locale>
		</locale-config>`

PrimeFaces 7.0: 
![Capturar2](https://user-images.githubusercontent.com/3578953/71447170-3759a700-270a-11ea-8fe2-a5379b3d8348.JPG)

PrimeFaces Snapshot or 8.0.RC2: 
![Capturar](https://user-images.githubusercontent.com/3578953/71447172-42143c00-270a-11ea-89c2-2d7e18a5d38e.JPG)

**Comment by tandraschko** [comment]
@christophs78  sorry :D can you also check this one? you had the most contact with calendar/datepicker

**Comment by christophs78** [comment]
@erickdeoliveiraleal : This seem´s to work fine. Tried with Showcase (Datepicker/Calendar). And locale via attribute of DatePicker and via default-locale in faces-config.xml.
![grafik](https://user-images.githubusercontent.com/10461942/71449403-0d28d900-274c-11ea-81c1-f11cef138380.png)

Did you include https://github.com/primefaces/primefaces/wiki/Locales for pt_BR into your XHTML? (or template used by your XHTML).
Calendar and DatePicker fall back to english when the locale-JS is missing for your locale.

Always fun to look into potential bugs between eating christmas-cakes and playing with my children. ;-)

**Comment by erickdeoliveiraleal** [comment]
Sorry, maybe it is related to my browser cache. idk.
