### ISSUE TITLE
multiViewState: add component reset option

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5482]
## 1) Environment
- PrimeFaces version: 8.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
`PrimeFaces.current().multiViewState().clear...` should also reset the DataTable/DataList.

## 3) Actual behavior
MultiViewState is reseted, but it has no impact on the current view/XHTML.

## 4) Steps to reproduce

1. https://www.primefaces.org/showcase/ui/data/datatable/tableState.xhtml
2. Click on "clear table state"

## 5) Sample XHTML
https://www.primefaces.org/showcase/ui/data/datatable/tableState.xhtml

## 6) Sample bean
`org.primefaces.showcase.view.data.datatable.TableStateView#clearTableState`

(With 8.0 we explicit need to call reset() on the DataTable after clearing the multiViewState. Maybe we should reset DataTable/DataList per default or we should offer an additional parameter/method to control whether DataTable/DataList should be reset.)

**Comment by Rapster** [comment]
I wonder if I should remove the consumer, I introduced this so I can do later a reset... I think I should have introduced reset option instead of consumer, my bad...

**Comment by christophs78** [comment]
IMO you did overall a realy good job in improving the handling of MultiViewState with 8.0.
Related to replacing the consumer with a reset-option: Is there something als than reseting we may do with the consumer?

**Comment by tandraschko** [comment]
@Rapster i commited a small refactoring, please review
i also changed the showcase
could someone please adjust the docus? i dont have much time this week

**Comment by Rapster** [comment]
Arf... I was actually working on those changes, please next time let me know you plan to do something :wink:
