### ISSUE TITLE
DataView (and other UIData-impls): add multiViewState

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5483]
DataTable and DataList have it already. Now add it to...
- [x] DataView
- [x] DataGrid
- [ ] TreeTable

**Comment by Rapster** [comment]
I'm working on a PR for the reset thing, and I realized almost every UIData component should support multiview state, so I think you can make this ticket bigger 😉

**Comment by christophs78** [comment]
Yep. I´d would be nice to have multiViewState for all UIData-implementations. Just the question, where to start and where to stop. Where to put our effort, ...

**Comment by tandraschko** [comment]
added TreeTable, not sure how easy it is

**Comment by tandraschko** [comment]
I will create a new issue for the DataView tracking for RC3

**Comment by melloware** [comment]
@tandraschko is working on TreeTable now: https://github.com/primefaces/primefaces/issues/6592

**Comment by tandraschko** [comment]
Will be handled in #6592
