### ISSUE TITLE
DataList: lazy=true; LazyDataModel#load called twice when restoring multiViewState

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5485]
## 1) Environment
- PrimeFaces version: 8.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
`LazyDataModel#load ` shoud be called once per request

## 3) Actual behavior
`LazyDataModel#load ` is called twice when multiViewState is restored

## 4) Steps to reproduce
Navigate, to XHTML includeing DataList with lazy="true" multiViewState="true". Do some paging. Reload page.

## 5) Sample XHTML
```
<p:dataList value="#{dtLazyView.lazyModel}" var="car" lazy="true" multiViewState="true" type="unordered" itemType="none" style="width: 450px"
			paginator="true" rows="5" rowsPerPageTemplate="5,10,20" pageLinks="5"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}">
	<h:panelGrid columns="3" columnClasses="logo,detail">
		<p:graphicImage name="demo/images/car/#{car.brand}-big.gif" />

		<p:outputPanel>
			<h:panelGrid columns="2" cellpadding="5">
				<h:outputText value="Id:" />
				<h:outputText value="#{car.id}" style="font-weight: bold"/>

				<h:outputText value="Year:" />
				<h:outputText value="#{car.year}" style="font-weight: bold"/>

				<h:outputText value="Color:" />
				<h:outputText value="#{car.color}" style="font-weight: bold"/>
			</h:panelGrid>
		</p:outputPanel>

		<p:commandLink update=":form:carDetail" oncomplete="PF('carDialog').show()" title="View Detail">
			<h:outputText styleClass="ui-icon pi pi-search" style="margin:0 auto;" />
			<f:setPropertyActionListener value="#{car}" target="#{dtLazyView.selectedCar}" />
		</p:commandLink>
	</h:panelGrid>
</p:dataList>
```

## 6) Sample bean
Showcase: `org.primefaces.showcase.view.data.datatable.LazyCarDataModel`

**Comment by melloware** [comment]
I think it is similar to this issue? https://github.com/primefaces/primefaces/issues/1151

**Comment by christophs78** [comment]
Yes. I´ll look into this. Sounds like DataExporter has a similar bug.
