### ISSUE TITLE
Datatable: Sequence of multisort

### ISSUE THREAD

**Issue by mafaul** [primefaces/primefaces#5491]
## 1) Environment
- PrimeFaces version: 8 RC2
- Application server + version: Payara 5.194
- Affected browsers: Chrome

## 2) Expected behavior
I see that the LazyDataModel changed to take a map for multisort data instead of a list. 
A list is ordered in java and a map not. How would it retain the order in which the columns where sorted? 
For filters it doesn't matter because the results will be the same, but for sorting the sequence of the results may differ.
For instance, order by age then gender would have a different result sequence than order by gender then age.

## 3) Actual behavior

Sort data: {
j_idt353:j_idt387:mainTableForm:recordList:pick_recList_dbCols:6=SortMeta [columnKey=j_idt353:j_idt387:mainTableForm:recordList:pick_recList_dbCols:6, sortField=office, sortOrder=ASCENDING, sortFunction=null], 
j_idt353:j_idt387:mainTableForm:recordList:pick_recList_dbCols:11=SortMeta [columnKey=j_idt353:j_idt387:mainTableForm:recordList:pick_recList_dbCols:11, sortField=tel, sortOrder=ASCENDING, sortFunction=null], 
j_idt353:j_idt387:mainTableForm:recordList:pick_recList_dbCols:0=SortMeta [columnKey=j_idt353:j_idt387:mainTableForm:recordList:pick_recList_dbCols:0, sortField=district, sortOrder=ASCENDING, sortFunction=null]}

**Comment by tandraschko** [comment]
we can simply use a LinkedHashMap - but not sure if this fixes, i thought that we rebuild this map each request

**Comment by tandraschko** [comment]
Can you retest plz? Commited the change to LinkedHashMap

**Comment by mafaul** [comment]
Tested, it works. Thank you very much.
