### ISSUE TITLE
InputNumber: setting type="number" on InputNumber breaks following SelectOne controls

### ISSUE THREAD

**Issue by davegiwd** [primefaces/primefaces#5496]
Setting "type=number" on an InputNumber results in any subsequent SelectOne controls to not respond to clicks.

## 1) Environment
- PrimeFaces version: Behavior observed with both 8.0.RC1 and 7.0.11
- Application server + version: Tomee Plume 7.1.0 (running Mojarra 2.2.12)
- Affected browsers: Chrome, Firefox, IE11 tested. Same behavior on all 3. Also, same behavior on Chrome mobile

## 2) Expected behavior
All of the components should respond to clicks.

## 3) Actual behavior
In the sample below, the components sb3 and sb4 do not respond to clicks when component in1 has `type="number"`. Components sb1, sb2 and sb5 all respond to clicks as expected.

## 4) Steps to reproduce

See sample below.

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
<f:view encoding="UTF-8" contentType="text/html">
    <h:head>
        <f:facet name="first">
            <meta charset="UTF-8" />
        </f:facet>
        <title>Number test</title>
    </h:head>
    <h:body>
        <h:form id="form1">
            <p:panelGrid columns="2" layout="grid">
                <p:outputLabel for="sb1" value="SB1" />
                <p:selectOneButton id="sb1">
                    <f:selectItem itemLabel="Yes" itemValue="true" />
                    <f:selectItem itemLabel="No" itemValue="false" />
                </p:selectOneButton>
                <p:outputLabel value="SB2" for="sb2" />
                <p:selectOneRadio id="sb2">
                    <f:selectItem itemLabel="Yes" itemValue="true" />
                    <f:selectItem itemLabel="No" itemValue="false" />
                </p:selectOneRadio>
                <p:outputLabel value="IN1" for="in1" />
                <p:inputNumber id="in1" type="number" />
                <p:outputLabel for="sb3" value="SB3" />
                <p:selectOneRadio id="sb3">
                    <f:selectItem itemLabel="Yes" itemValue="true" />
                    <f:selectItem itemLabel="No" itemValue="false" />
                </p:selectOneRadio>
                <p:outputLabel for="sb4" value="SB4" />
                <p:selectOneButton id="sb4">
                    <f:selectItem itemLabel="Yes" itemValue="true" />
                    <f:selectItem itemLabel="No" itemValue="false" />
                </p:selectOneButton>
                <h:outputLabel for="sb5" value="SB5" />
                <h:selectOneRadio id="sb5">
                    <f:selectItem itemLabel="Yes" itemValue="true" />
                    <f:selectItem itemLabel="No" itemValue="false" />
                </h:selectOneRadio>
            </p:panelGrid>
        </h:form>
    </h:body>
</f:view>
</html>
```
## 6) Sample bean

N/A

**Comment by melloware** [comment]
Getting this Javascript error in the console: `Uncaught Error: The input type "number" is not supported by autoNumeric`.

![image](https://user-images.githubusercontent.com/4399574/71743880-a5514d00-2e33-11ea-8681-4a76d2e368e3.png)


From the AutoNumeric docs : https://github.com/autoNumeric/autoNumeric

> Please note than due to browser constraints, only the following supported <input> types are supported :
> 
> text,
> tel,
> hidden, or
> no type specified at all
> <input type='text' value="1234.56">
> <input type='tel' value="1234.56">
> <input type='hidden' value="1234.56">
> <input value="1234.56">
> 
> Note : the number type is not supported simply because autoNumeric formats numbers as strings (ie. '123.456.789,00 &#8364;') that this input type does not allow.

**Comment by tandraschko** [comment]
please google next time, it was already discussed some time ago
