### ISSUE TITLE
DataTablePDFExporter: Accessing Document Object

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5497]
## 1) Environment
- PrimeFaces version: 8.0RC2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Irrelevant
- Affected browsers: Irrelevant

## 2) Expected behavior

I like to extend the `DataTablePDFExporter` class to export a PDF document with landscape orientation.
For this, I must overload the `preExport` method as I need to call a different constructor for document.

I expected to see a protected `setDocument` method to set the document in `DataTablePDFExporter` from my overloaded method. Would this be possible to add this to the `DataTablePDFExporter` class?

## 3) Actual behavior

I need to overload all methods which are using the document field in DataTablePDFExporter. This is not the best solution here, since a lot of code has to be needlessly duplicated.
..

## 4) Steps to reproduce

Does not apply here.

## 5) Sample XHTML

Does not apply here.

## 6) Sample bean

Does not apply here.

**Comment by melloware** [comment]
Let me investigate.

**Comment by melloware** [comment]
Just submitted PR please review.  I think it is a valuable improvement to this class.

It will allow you to override `getDocument()` to create your own instance of the Document.

**Comment by stolp** [comment]
Looks perfect for me. Thanks!

I also liked to add that the dataexporter interface in 8.0 is far more clearer and usable now than the one back in 7.0.
