### ISSUE TITLE
Schedule columnFormat not working

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#55]
The old syntax:

columnFormat="month : 'ddd', week : 'ddd D.M.', day : 'dddd D.M.'"

is in fullcalendar 2 replaced with:

views: {
        month: { // name of view
            titleFormat: 'YYYY, MM, DD'
            // other view-specific options here
        }
    }

See: http://fullcalendar.io/docs/views/View-Specific-Options/
Old full calendar 1 columnFormat: http://fullcalendar.io/docs/views/View_Option_Hash/

**Comment by cagataycivici** [comment]
We'd appreciate a pull request, I'd prefer a fix at the widget side by parsing the old columnFormat and create javascript objects for each view. I do not think parsing with comma is safe though as format can have comma inside it. Any suggestions?

**Comment by tryptichon** [comment]
Pull request made. It corrects this issue, a timezone/DST issue and adds another attribute to the schedule to enable weekNumbers.

**Comment by cagataycivici** [comment]
Thank you but separate pull requests are required for other issues instead of one that does a couple of other unrelated things.

**Comment by tryptichon** [comment]
I see. I'll try to clean that up and split it into one pull request per issue.

**Comment by cagataycivici** [comment]
Thank you.

**Comment by tryptichon** [comment]
https://github.com/primefaces/primefaces/pull/138

**Comment by mertsincan** [comment]
This issue is fixed; #1472
