### ISSUE TITLE
InputTextarea: Autocomplete doesn't work in datatable

### ISSUE THREAD

**Issue by tpzstamp** [primefaces/primefaces#5502]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version?
Not sure.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
Not sure.
- Application server + version:
Red Hat JBoss Enterprise  7.0
- Affected browsers:
Firefox

## 2) Expected behavior
I try to put the inputTextarea in an editable datatable. Enable autocomplete feature with adding the completeMethod attribute. 
...

## 3) Actual behavior
After click this cell, the inputTextarea does appear. But the autocomplete feature is not there. I checked the page source. The textarea is not decorated with the autocomplete feature.

Btw, I put another inputTextarea out of the datatable in the same page. The autocomplete works as expected.

..

## 4) Steps to reproduce
Put the inputTextArea in the datatable. Make the datatable editable. 
Add a column, which including input/output facet.
Click the cell to edit in the textarea.

.. 

## 5) Sample XHTML

`<f:facet name="input">
                                    <p:inputTextarea rows="6" cols="50" completeMethod="#{myView.getTempRemarkList}" queryDelay="600" minQueryLength="2" value="#{myBean.tempRemark}" id="tempRemarkInput" process="@this">
                                        <f:attribute name="itemCode" value="#{myBean.id}" />
                                    </p:inputTextarea>
                                </f:facet>`
..

## 6) Sample bean
`public class MyBean {
    public List<String> getTempRemarkList(String queryParam) {
        List<String> resultList = new ArrayList<String>();
        resultList.add("test1");
        resultList.add("abcdefg");
        return resultList;
    }
}`
..

**Comment by tandraschko** [comment]
Please follow the issue template

**Comment by tpzstamp** [comment]
> 
> 
> Please follow the issue template

I've revised my post following the template. Could you please mark it as valid and proceed to investigate? Thank you.

**Comment by melloware** [comment]
Can you use PrimeFaces Test project: https://github.com/primefaces/primefaces-test

And create a runnable sample for us to see and debug the problem?

**Comment by tpzstamp** [comment]
I'm not good at setting up the project environments via maven. Just created very very simple testing code in 3 files. I've reproduced it in JDK 1.8 and Tomcat 9. Could you please try it? 
Btw, the code is not correctly formated here. I also attached them in the zip file. Thanks .

```java
@ViewScoped
public class TestView {
	private List<TestBean> dataList;
	private String myText;

	public List<TestBean> getDataList() {
		this.dataList = new ArrayList<TestBean>();
		this.dataList.add(new TestBean(1,"John"));
		this.dataList.add(new TestBean(2,"Tim"));
		this.dataList.add(new TestBean(3,"Max"));
		return dataList;
	}

	public void setDataList(List<TestBean> dataList) {
		this.dataList = dataList;
	}
	
	public String getMyText() {
		return myText;
	}

	public void setMyText(String myText) {
		this.myText = myText;
	}

	public List<String> autoCompleteTest(String queryParam) {
		List<String> resultList = new ArrayList<String>();
		
		resultList.add("no 1");
		resultList.add("test");
		resultList.add("1234");
		
		return resultList;
	}
	
	public void onTableEdit(CellEditEvent evt) {
		try {
			
		}catch(Exception e) {
			System.out.println(e);
		}
	}
}
```
```xml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
   
<html xmlns = "http://www.w3.org/1999/xhtml"
   xmlns:f = "http://java.sun.com/jsf/core"
   xmlns:h = "http://java.sun.com/jsf/html"
   xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
   
<h:head>Home</h:head>
<h:body>

<h:form>
	<p:dataTable id="testTable" var="_item"  value="#{testView.dataList}" draggableColumns="true" 
                        editable="true" editMode="cell"
                        rowKey="#{_item.id}" selectionMode="single" >
        <p:ajax event="cellEdit"
                            listener="#{testView.onTableEdit}" process="@this" />
                            
        <p:column id="testCol" headerText="Name">
            <p:cellEditor>
                <f:facet name="output">
                    <h:outputText id="outputCol" value="#{_item.name}" />
                </f:facet>
                <f:facet name="input">
                    <p:inputTextarea rows="6" cols="50" completeMethod="#{testView.autoCompleteTest}" queryDelay="600" minQueryLength="2" value="#{_item.name}"  process="@this">
                    </p:inputTextarea>
                </f:facet>
            </p:cellEditor>
        </p:column>
    </p:dataTable>
    
    <p:inputTextarea rows="6" cols="50" completeMethod="#{testView.autoCompleteTest}" queryDelay="600" minQueryLength="2"  process="@this" value="#{testView.myText}" var="originEntry"/>
    
</h:form>

</h:body>
</html>
```
```java
public class TestBean {
	private String name;
	private int id;

	public TestBean(int id, String param) {
		this.name = param;
		this.id = id;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
}
```
[inputTextarea_autocomplete.zip](https://github.com/primefaces/primefaces/files/4048985/inputTextarea_autocomplete.zip)

<img width="158" alt="apache-tomcat-9 0 22_webapps_jsfTest_WEB-INF_lib" src="https://user-images.githubusercontent.com/36370600/72199042-14045b00-3471-11ea-9dbc-81a1e0c8bbbf.png">

**Comment by melloware** [comment]
OK I will give it a shot.  I formatted the code for you. Next time in GitHub you just need 3 ticks to start in end instead of 1 tick.

**Comment by melloware** [comment]
Attached is a test case based on your example that proves the issue.

[pf-5502.zip](https://github.com/primefaces/primefaces/files/4053562/pf-5502.zip)

**Comment by melloware** [comment]
OK this might be complex to understand but add `autoResize="false"` to your InputTextArea in your datatable. That fixes it.

This is because when AutoResizing the InputText is a "Deferred" Widget and since the datatable is not  displaying it yet the render method never gets called to set up the InputTextArea.

By setting autoResize=false you are telling it not to be a deferred widget and this everything is configured correctly.

**Comment by tpzstamp** [comment]
> 
> 
> OK this might be complex to understand but add `autoResize="false"` to your InputTextArea in your datatable. That fixes it.
> 
> This is because when AutoResizing the InputText is a "Deferred" Widget and since the datatable is not displaying it yet the render method never gets called to set up the InputTextArea.
> 
> By setting autoResize=false you are telling it not to be a deferred widget and this everything is configured correctly.

I see. Thank you, melloware.
