### ISSUE TITLE
InputNumber: Regression in handling large numbers for value/minValue/maxValue after AutoNumeric update

### ISSUE THREAD

**Issue by metaxmx** [primefaces/primefaces#5504]
## 1) Environment
- PrimeFaces version: 7.0.11 (Elite)
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 9
- Affected browsers: Firefox tested

## 2) Expected behavior
The formatting/encoding of the decimal numbers in the `value`/`minValue`/`maxValue` is problematic for for large values (which are usually rendered in scientific notation for double) or for values which a large precision (BigDecimal). Also the check against the default min/max value in is not preformed before rendering, which results in an error.

Consider the following examples:

1. `maxValue` is a bean property with the double value `1_000_000_000_000_000_000.0`
2. `minValue` is a bean property with the double value `-1_000_000_000_000_000_000.0`
3. `minValue` and `maxValue` are not defined, and the value is `90_000_000_000_000.0` (above AutoNumeric default max value `10_000_000_000_000.0`)
4. `value` property is a bean property of type BigDecimal with value `new BigDecimal("123456789012345678901234567890.1234567890")` and `maxValue` of `new BigDecimal("9786543120978654312097865431209786543120.9786543120")`

Expected behaviour: The component is rendered without any JavaScript Errors and the original values and max/min values are considered as given. Also, the value can be changed according to the given constraints and the changed values will be decoded correctly in the component and written to the bound value expression as correctly.

## 3) Actual behavior

The actual behavior for the 4 examples above:
1. The `maxValue` is encoded as String `"1.0E18"` and not correctly reformatted by the InputNumberComponent before passing to the AutoNumeric JavaScript library. This results in a JavaScript exception `"The maximum possible value option 'maximumValue' is invalid ; it should be a string that represents a positive or negative number, [1.0E18] given."` and the Component is broken and doens't handle any change events.
2. same as 1, but with min instead of max
3. The value is formatted as `9.0E13` in the input field. Also, the component fails to perform a range check for the value against the default range of AutoNumeric, and so a JavaScript exception is shown: `"The value [90000000000000] being set falls outside of the minimumValue [-10000000000000] and maximumValue [10000000000000] range set for this element"`. As a result the component is broken and doesn't handle an change events.
4. The BigDecimal number is cut after 20 integer places, so only `12.345.678.901.234.567.890,12` is shown in the input field. When the value is edited, the long number seems to be always rounded as double, although AutoNumeric and `BigDecimal` both support a lot more places. When the value is edited into a large enough numer, the resulting value will be `0.00`, because the precision of the number is reduced to the precision of a double, and then the high digits will be removed by the "maximum 20 integer digits" formatting, leaving only 0 digits in the lower places.

## 4) Steps to reproduce
See example XHTML/Bean 

## 5) Sample XHTML
```html
<h:body>
    <h1>NumberInput Example</h1>
    <h:form>
        <p:growl id="grwl" />
        <h:panelGrid columns="2" cellpadding="5">

            <p:outputLabel for="largeMax" value="Large MaxValue:" />
            <p:inputNumber id="largeMax" value="#{numberExample.numberWithLargeMax}" maxValue="#{numberExample.largeMax}" inputStyle="width: 500px;">
                <p:ajax update="@form" process="@this" />
            </p:inputNumber>

            <p:outputLabel for="largeMin" value="Large MinValue:" />
            <p:inputNumber id="largeMin" value="#{numberExample.numberWithLargeMin}" minValue="#{numberExample.largeMin}" inputStyle="width: 500px;">
                <p:ajax update="@form" process="@this" />
            </p:inputNumber>

            <p:outputLabel for="aboveDefaultMax" value="Above Default Max:" />
            <p:inputNumber id="aboveDefaultMax" value="#{numberExample.numberAboveDefaultMax}" inputStyle="width: 500px;">
                <p:ajax update="@form" process="@this" />
            </p:inputNumber>

            <p:outputLabel for="bigDecimal" value="Big Decimal:" />
            <p:inputNumber id="bigDecimal" value="#{numberExample.numberBigDecimal}" maxValue="#{numberExample.maxBigDecimal}" decimalPlaces="5" inputStyle="width: 500px;">
                <p:ajax update="@form" process="@this" />
            </p:inputNumber>
        </h:panelGrid>
    </h:form>
</h:body>
```

## 6) Sample bean
```java
@ViewScoped
@Named("numberExample")
public class NumberExample implements Serializable {

    private static final double max_large = 1_000_000_000_000_000_000.0;

    private static final double min_large = -1_000_000_000_000_000_000.0;

    private double numberWithLargeMin = 123_456_789;

    private double numberWithLargeMax = 123_456_789;

    private double numberAboveDefaultMax = 90_000_000_000_000.0;

    private BigDecimal numberBigDecimal = new BigDecimal("123456789012345678901234567890.1234567890");

    private static final BigDecimal maxBigDecimal = new BigDecimal("9786543120978654312097865431209786543120.9786543120");

    public double getLargeMax() {
        return max_large;
    }

    public double getLargeMin() {
        return min_large;
    }

    public double getNumberWithLargeMin() {
        return numberWithLargeMin;
    }

    public void setNumberWithLargeMin(double numberWithLargeMin) {
        this.numberWithLargeMin = numberWithLargeMin;
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                "Number Changed to " + numberWithLargeMin, "Number is now " + numberWithLargeMin));
    }

    public double getNumberWithLargeMax() {
        return numberWithLargeMax;
    }

    public void setNumberWithLargeMax(double numberWithLargeMax) {
        this.numberWithLargeMax = numberWithLargeMax;
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                "Number Changed to " + numberWithLargeMax, "Number is now " + numberWithLargeMax));
    }

    public double getNumberAboveDefaultMax() {
        return numberAboveDefaultMax;
    }

    public void setNumberAboveDefaultMax(double numberAboveDefaultMax) {
        this.numberAboveDefaultMax = numberAboveDefaultMax;
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                "Number Changed to " + numberAboveDefaultMax, "Number is now " + numberAboveDefaultMax));
    }

    public BigDecimal getMaxBigDecimal() {
        return maxBigDecimal;
    }

    public BigDecimal getNumberBigDecimal() {
        return numberBigDecimal;
    }

    public void setNumberBigDecimal(BigDecimal numberBigDecimal) {
        this.numberBigDecimal = numberBigDecimal;
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                "BigDecimal Number Changed to " + numberBigDecimal, "Number is now " + numberBigDecimal));
    }
}
```

## 7) Problem analysis
After analyzing the class `InputNumberRenderer` and the corresponding `1-inputnumber.js` JavaScript file, I have identified multiple independent causes for the behaviour decribed above.

The main regression concerning the `minValue`/`maxValue` seems to be a result in the AutoNumeric update in #5279, because the old version if AutoNumeric didn't have such strong check for the format of the minimum and maximum number.

The problems with the precision seem to come from conversion to double in JavaScript:
```javascript
getValue: function () {
        var val = this.autonumeric.getNumericString();
        if (val && this.cfg.decimalPlaces) {
            return parseFloat(val).toFixed(this.cfg.decimalPlaces);
        }

        return val;
    }
```

Also in the renderer, some values are converted to double (`new BigDecimal(...).doubleValue()`) which reduces precision. 

Concerning the third point: there is a check against the given `minValue`/`maxValue` if they are specificed in the component. If the AutoNumeric default values for these are in place however, there is no such check that the value must not be outside this range.

And finally, in the function `formatForPlugin` a number formatter is used with fixed minimum/maximum digits, which is problematic for the use with `BigDecimal` with arbitrary scale and precision.
```
NumberFormat formatter = new DecimalFormat("#0.0#");
//autoNumeric jquery plugin max and min limits
formatter.setMinimumFractionDigits(15);
 formatter.setMaximumFractionDigits(15);
formatter.setMaximumIntegerDigits(20);
```

Contrary to the code comment, the neew AutoNumeric version seems to be fine with a lot larger precision/scale numbers.

**Comment by melloware** [comment]
Good debugging.  Have you tried to tweak any of the code to get it working?  PR perhaps?

**Comment by alfonx** [comment]
Backport to 7.12 would be very much appreciated.

**Comment by tandraschko** [comment]
the changes are to big IMO for RC3
we will check it after the release

**Comment by alfonx** [comment]
JFI: This is a regression.. It worked great with all 7.0.0 to 7.0.10
