### ISSUE TITLE
InputText: Floating Label is broken in firefox but works with edge and chrome.

### ISSUE THREAD

**Issue by bigbonsai** [primefaces/primefaces#5508]
## 1) Environment
- PrimeFaces-8.0-SNAPSHOT on Mojarra-2.3.13.
- Firefox latest 72.0.1 (64-Bit)

## 2) Expected behavior
The floating label should fit above the inputfield when input made.

## 4) Steps to reproduce
Open Showcase (https://www.primefaces.org/showcase/ui/input/inputText.xhtml) for inputText with firefox. Start entering content in the inputfield with the floating label.

**Comment by bigbonsai** [comment]
The css rule gets not affected:
`.ui-float-label > input:focus ~ label, .ui-float-label > input.ui-state-filled ~ label, .ui-float-label > input:-webkit-autofill ~ label, .ui-float-label > textarea:focus ~ label, .ui-float-label > textarea.ui-state-filled ~ label, .ui-float-label > textarea:-webkit-autofill ~ label, .ui-float-label > .ui-inputwrapper-focus ~ label, .ui-float-label > .ui-inputwrapper-filled ~ label {
    top: -.75em;
    font-size: 12px;
}`
Entering 
`$('.ui-float-label > input.ui-state-filled ~ label').css('top', '-0.75em')` fixes the issue.

**Comment by melloware** [comment]
@bigbonsai can you add this CSS to your page and see if it fixes it.
```css
.ui-float-label > input.ui-state-focus ~ label {
    top: -.75em;
}
```

**Comment by bigbonsai** [comment]
Yes adding the css to the page fixes it.

**Comment by bigbonsai** [comment]
Your fix will only work on focus.
I removed the  -webkit-autofill rules in css and this fixes the issue.

**Comment by melloware** [comment]
Let me try that.

**Comment by melloware** [comment]
OK so those are there to solve if the fields ae auto filled by the browser like an Address form the floating label will move.  I feel like this might be a bug in Firefox.

**Comment by melloware** [comment]
OK i just submitted anothre fix.  By moving the webkit-autofills into their own section Firefox now works.

**Comment by bigbonsai** [comment]
This fix works perfect.
Thank you very much.

Close #5510

**Comment by tandraschko** [comment]
Please don't close it; the PR is still not merged
