### ISSUE TITLE
AutoUpdate: event/observer pattern

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#5509]
Based on this https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/358

I'd like to be able to write something like this:
```xml
<pa:menuButton icon="fa-shopping-cart"
               model="#{cartManager.cartModel}">
    <p:autoUpdate on="update-cart" listener="#{cartManager.createMenuModel}" />
</pa:menuButton>

<p:commandButton value="#{i18n['ADD_ITEM_CART']}"
                 action="#{cartManager.addItemToCart}" 
                 update="@obs('update-cart)"/>
```

`on`: attribute indicating the kind of event to observe
`listener`: action to execute when `update-cart` is fired (before getting updated, being said I don't know if we should have a pre & post listener?)
`@obs`: retrieve client ids from components subscribing to the specified event

**Comment by tandraschko** [comment]
maybe ´@event´ instead ´@sub´?

**Comment by Rapster** [comment]
sounds good

**Comment by Rapster** [comment]
I kinda like `@sub` as it means subscribers, or maybe `@obs` for observers... I want short keyword and fluent reading so it can be read like "update `@id`", "update `@widgetvar`",  "update `@all`" Doesn't sound good with `@event` because it's not event that being updated but subscribers/observers/listeners to it

**Comment by tandraschko** [comment]
i commited a solution, please review and check.
Also added a showcase sample, would be great if you can review, test, improve docs and showcase :D

thanks :D

**Comment by melloware** [comment]
Showcase looks great I will tackle updating the docs!

**Comment by melloware** [comment]
I also added Integration Tests for this: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/e6f58f1c40c599340f54e0d14d59b0bb852143a4

**Comment by melloware** [comment]
@tandraschko safe to close this ticket as I think all implementations, docs, and integration tests are complete?

**Comment by tandraschko** [comment]
yup
