### ISSUE TITLE
DataTable default sort if sortMode = multiple

### ISSUE THREAD

**Issue by amayr666** [primefaces/primefaces#551]
Hi,
I want to use a dataTable with sortMode = multiple and a default sort. I tried to do it by 
`<p:dataTable sortMode = "multiple" sortBy="#{item.value}" sortOrder="ascending">`

but this throws an NPE

```
09:43:41,491 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-52) Error Rendering View[/restricted/dispo/editLoad.xhtml]: java.lang.NullPointerException
at org.primefaces.component.datatable.feature.SortFeature.multiSort(SortFeature.java:173) [primefaces-5.2.3.jar:5.2.3]
at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:107) [primefaces-5.2.3.jar:5.2.3]
at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:83) [primefaces-5.2.3.jar:5.2.3]
at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919) [jboss-jsf-api_2.2_spec-2.2.6.jar:2.2.6]
at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:312) [jsf-impl-2.2.6-jbossorg-4.jar:]
```

**Comment by sudheerj** [comment]
You need to provide the List of SortMeta for sortBy property.

<p:dataTable sortBy="#{bean.multiSortMeta}" .../>
private List<SortMeta> multiSortMeta;

**Comment by amayr666** [comment]
Hi, added this to `@PostConstruct` due to some stackoverflow posts (because nothing about sortMeta is written in the PF docu):

```
private void buildSortOrder() {
    preSortOrder = new ArrayList<>();
    UIViewRoot viewRoot = FacesContext.getCurrentInstance().getViewRoot();
    UIComponent column = viewRoot.findComponent("form:orderTable:from");

    SortMeta sm1 = new SortMeta();
    sm1.setSortBy((UIColumn) column);
    sm1.setSortField("from");
    sm1.setSortOrder(SortOrder.ASCENDING);
    preSortOrder.add(sm1);
}
```

while preSortOrder is a `List<SortMeta> preSortOrder = new ArrayList<>();`.

The compiler says `Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Comparable`

How else is SortMeta used? I haven't found any appropriate usage for this..

**Comment by mertsincan** [comment]
I added a maven project to dropbox. Please try; https://www.dropbox.com/s/7j2yts9oe9nadef/test.rar?dl=0

You can execute the sample with mvn jetty:run command and hit http://localhost:8080/test to run the page.

**Comment by HelainSchoonjans** [comment]
@mertsincan the dropbow link is not working anymore. Can you send a new one?

**Comment by melloware** [comment]
@HelainSchoonjans what exactly do you need?  We already have all these examples on the PF Showcase.

**Comment by HelainSchoonjans** [comment]
Hello @melloware, is it this page then? http://primefaces.org/showcase/ui/data/datatable/sort.xhtml?jfwid=71080

**Comment by melloware** [comment]
@HelainSchoonjans yes look at the Default Sort example.
