### ISSUE TITLE
DatePicker: Touch UI does not open correctly

### ISSUE THREAD

**Issue by marcelocaser** [primefaces/primefaces#5513]
## 1) Environment
- PrimeFaces version: PrimeFaces-8.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 9 + JDK 13
- Affected browsers: Opera 65.0.3467.69 / Chrome 79.0.3945.79

## 2) Expected behavior

The example can be reproduced by the showcase itself.

## 3) Actual behavior

As you can see, it seems to open and close !!! When you change the browser tab and return to the previous one the DatePicker is displayed !!

## 4) Steps to reproduce

[https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml](url)

## 5) Sample XHTML

Not necessary

## 6) Sample bean

Not necessary

**Comment by melloware** [comment]
@christophs78 Any chance you want to look at this one?  It is easily reproducible on the showcase.

**Comment by christophs78** [comment]
Yes, i´ll look at this.

**Comment by christophs78** [comment]
Does not occur with FF, Edge and IE.

**Comment by christophs78** [comment]
Issue is located in `0-datepicker.js`, function `enableModality`.

**Comment by melloware** [comment]
Is it because now the new datepicker is appended to BODY by default and enable modality is doing 
`$(document.body).append(this.mask).addClass('ui-overflow-hidden');`

or zIndex related?
`this.mask.css('z-index', String(parseInt(this.panel.css('z-index'), 10) - 1));`

**Comment by christophs78** [comment]
Inline is already excluded from append to BODY. I will try the same for touchUI. (I will continue tomorrow. It´s getting 10pm in good old europe. Time to slow down and going to bed.)

**Comment by christophs78** [comment]
Maybe same (already fixed) issue for PrimeNG-Calendar: https://github.com/primefaces/primeng/issues/7389

and some more... https://github.com/primefaces/primeng/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+touch+calendar

**Comment by christophs78** [comment]
![grafik](https://user-images.githubusercontent.com/10461942/72361890-7c15a400-36f2-11ea-883c-e9334c8f5121.png)
