### ISSUE TITLE
DataView: add multiViewState support

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5516]
see: https://github.com/primefaces/primefaces/issues/5483

**Comment by tandraschko** [comment]
@christophs78 there is a TODO in the #reset method. Do you still know why? Otherwise i would just uncomment it, DataTable resets the rows the same way

**Comment by christophs78** [comment]
good question :-)

comparing a few things and looking at the timeline ...

![image](https://user-images.githubusercontent.com/10461942/233135694-10b88bcc-dc08-493f-a7c8-0d213295866d.png)

![image](https://user-images.githubusercontent.com/10461942/233136338-9281ced5-ca11-4ee1-9726-526d5846915b.png)

![image](https://user-images.githubusercontent.com/10461942/233135993-783e1fa5-9c4f-40fe-90a0-1f85ec482565.png)

From my current feeling we may try following.

```java
public void reset() {
	setFirst(0);
	resetRows();
	setLayout(null);
}
```

And add IT`s for DataView-multistate....

**Comment by christophs78** [comment]
i'll try to add a IT this weekend. hope for rainy weather to find time. ;-)
