### ISSUE TITLE
Rio theme ; SelectManyMenu with checkbox = true misaligned in firefox mozilla browser.

### ISSUE THREAD

**Issue by nehadhavale** [primefaces/primefaces#552]

**Comment by mertsincan** [comment]
What rio version are you using? Can you please attach screenshots and sample codes for us to replicate? Also, We have a fix about SelectManyMenu. Please check it(https://github.com/primefaces/layouts/issues/3)
Next time, please use primefaces forum for your theme issues. (http://forum.primefaces.org/viewforum.php?f=26)

**Comment by nehadhavale** [comment]
Thanks for your prompt reply. Really appreciate it...
I was using 1.1 Rio version. But just checked it by using Rio 2.0 and it is resolved. 
Also, I am using font awesome. But again its button icons are not displayed properly in mozilla. Any idea about that?

And yes, next time I will post an issue in (http://forum.primefaces.org/viewforum.php?f=26)

**Comment by mertsincan** [comment]
Glad to hear, thanks!

> Also, I am using font awesome. But again its button icons are not displayed properly in mozilla.

Can you please attach screenshots and a sample test.xhtml for us to replicate?

**Comment by nehadhavale** [comment]
![font-awesome](https://cloud.githubusercontent.com/assets/13449794/8824889/b1e5c85a-3097-11e5-990c-3b143aa95403.png)

Code...
 <p:commandButton id="view" icon="fa fa-search White" title="#{msg.View}" actionListener="#{studentBean.viewStu(item)}" styleClass="GreenButton"
                                                 process="@this" update=":popup:viewDlg" onstart="PF('blockActionPanel').block();" oncomplete="PF('viewDlg').show();PF('blockActionPanel').unblock();"
                                                 rendered="#{accountContext.hasPermission('student.htm','v')}"/>

**Comment by nehadhavale** [comment]
This is the command button used:
<p:commandButton id="view" icon="fa fa-search White" title="#{msg.View}" actionListener="#{studentBean.viewStu(item)}" styleClass="GreenButton"  process="@this" update=":popup:viewDlg" onstart="PF('blockActionPanel').block();" oncomplete="PF('viewDlg').show();PF('blockActionPanel').unblock();"                                                rendered="#{accountContext.hasPermission('student.htm','v')}"/>

**Comment by mertsincan** [comment]
I couldn't replicate the issue. Do you try it in other browsers? 
Also, please check in your web.xml;

```
<context-param>
        <param-name>primefaces.FONT_AWESOME</param-name>
        <param-value>true</param-value>
</context-param>
```

My test case;

```
<h:form id="form">
   <p:dataTable ...>
       ....
         <p:column headerText="Buttons" footerText="Buttons">
             <p:commandButton icon="fa fa-home" styleClass="GreenButton" />
             <p:commandButton icon="fa fa-home" styleClass="OrangeButton"/>
             <p:commandButton icon="fa fa-home" styleClass="RedButton"/>
          </p:column>
    </p:dataTable>
</h:form>
```

screenshot; 
![capture](https://cloud.githubusercontent.com/assets/11868120/8825232/22e100fe-3086-11e5-8901-c2d2493e3475.PNG)

**Comment by nehadhavale** [comment]
Yes, its working fine with google chrome. I ll check my web.xml and get back.

**Comment by nehadhavale** [comment]
My web.xml has this code. I don't know what the issue is. Google chrome has no problem.
I also updated my browser to the latest version. :(

**Comment by nehadhavale** [comment]
![googlw_chrome](https://cloud.githubusercontent.com/assets/13449794/8825651/4f330428-309e-11e5-8df9-c1dbbc139993.png)
results using chrome browser...

**Comment by mertsincan** [comment]
I researched this problem and found a issue in FF; https://support.mozilla.org/en-US/questions/959250
Also,If you have Rio Layout, you can try this solutions(font-awesome.css); http://superuser.com/questions/446001/firefox-cannot-render-icons-from-font-awesome-webfont-set

I still couldn't replicate it.

**Comment by nehadhavale** [comment]
Thanks. Will have a look at these and keep you posted.

**Comment by nehadhavale** [comment]
Hey, I resolved the issue. I had some font-awesome css included in my project which were not required. After removing them the issue was resolved. Thanks for your help :).

**Comment by mertsincan** [comment]
Glad to hear, thanks!

**Comment by cagataycivici** [comment]
Please post at forum first and then layouts tracker not the PF tracker.
