### ISSUE TITLE
[perf] use JS native .closest when lookup parent overlay containers

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5520]

**Comment by melloware** [comment]
@tandraschko I don't think closest is supported in IE.  See: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

I think we will have to use a polyfill. I am getting "Object doesn't support property or method closest".

**Comment by tandraschko** [comment]
i already added a polyfill ;)

**Comment by melloware** [comment]
OK i see the polyfill now but I am getting this error in IE11. I am wondering if its related to MOVE_SCRIPTS_TO_BOTTOM.

**Comment by melloware** [comment]
OK I found the problem.  My maven pom.xml was not updated so it did not include the script.  Closing the ticket.

**Comment by jasonex7** [comment]
I have some errors related to this commit, please consider my comments:

- https://github.com/primefaces/primefaces/commit/fd04cd4c47dbc04d0588dda949e1d22ef5796efd#r37046408

- https://github.com/primefaces/primefaces/commit/fd04cd4c47dbc04d0588dda949e1d22ef5796efd#r37046425

**Comment by tandraschko** [comment]
should be fixed now

**Comment by jasonex7** [comment]
The error disappeared. Thank you 👍🏼
