### ISSUE TITLE
SelectOneMenu: filter does not use 100% width

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5522]
## 1) Environment
- PrimeFaces version: 7.0.0
- Does it work on the newest released PrimeFaces version? Version? No, 8.0-SNAPSHOT
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: does not matter
- Affected browsers: does not matter

## 2) Expected behavior
Filter-Input-Field should be width:100%
![grafik](https://user-images.githubusercontent.com/10461942/72419342-effc8e80-377c-11ea-97b6-7facd27b75ae.png)

## 3) Actual behavior
Showcase:
![grafik](https://user-images.githubusercontent.com/10461942/72419392-06a2e580-377d-11ea-81d6-23c98be6780c.png)

Custom Project with Babylon-Layout:
![grafik](https://user-images.githubusercontent.com/10461942/72419403-0c98c680-377d-11ea-828c-c5b475d859a9.png)

## 4) Steps to reproduce
http://localhost:8080/showcase_facelift_war_exploded/ui/input/oneMenu.xhtml

## 5) Sample XHTML
Add filter="true" to longItemLabel-selectOneMenu

**Comment by christophs78** [comment]
We are able to fix this with:
```
.ui-selectonemenu-filter-container {
    width: 100%;
}
```
Can we add this OOTB to PrimeFaces? (form.css)

**Comment by tandraschko** [comment]
+1 from my side
@mertsincan ?

**Comment by melloware** [comment]
+1 from me too.
