### ISSUE TITLE
DatePicker : Localization of Time

### ISSUE THREAD

**Issue by carlbradwell17** [primefaces/primefaces#5528]
## 1) Environment
- PrimeFaces version: 8.0.RC2
- Does it work on the newest released PrimeFaces version? Not working on 7.0 either

## 2) Expected behavior

When a datepicker has the showTime option set to true, or the timeOnly option set to true, the time should be localised, according to the locale.

This is possible with the calendar component by setting a pattern, although for datepicker the pattern is for date only according to the documentation.

## 3) Actual behavior

The time is never localised, will always be displayed as HH:mm or HH:mm:ss if showSeconds is true.

## 4) Steps to reproduce

Create a datepicker, with localization options set.

## 5) Sample XHTML

<p:datePicker id="dp" locale="de" timeZone="#{localeBean.timeZone}" showTime="true" pattern="dd/MM/yyyy" />

## 6) Sample bean

import java.io.Serializable;
import java.util.TimeZone;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named
@SessionScoped
public class LocaleBean implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private TimeZone timeZone = TimeZone.getTimeZone("Europe/Copenhagen");
	
	public TimeZone getTimeZone() {
		return timeZone;
	}

	public void setTimeZone(TimeZone timeZone) {
		this.timeZone = timeZone;
	}
	
}

**Comment by melloware** [comment]
@christophs78 can you take a look?

**Comment by christophs78** [comment]
Yes.

**Comment by christophs78** [comment]
org.primefaces.component.datepicker.DatePickerBase#calculateTimeOnlyPattern

```
@Override
public String calculateTimeOnlyPattern() {
	if (timeOnlyPattern == null) {
		boolean ampm = "12".equals(getHourFormat());
		timeOnlyPattern = ampm ? "KK" : "HH";
		timeOnlyPattern += ":mm";
		if (isShowSeconds()) {
			timeOnlyPattern += ":ss";
		}
		if (ampm) {
			timeOnlyPattern += " a";
		}
	}
	return timeOnlyPattern;
}
```

**Comment by christophs78** [comment]
@carlbradwell17: Does it help to use `hourFormat="12"`?

**Comment by carlbradwell17** [comment]
Hi,
My application uses java.util.Locale and java.time.format.DateTimeFormatterBuilder to produce the patterns for datetimes.
For a language such as Danish (da), the desired pattern is **dd/MM/y HH.mm**, where the seperator is dot rather than colon.
This works fine with the Calendar component, as enabling the time picker is done by providing time as part of the pattern, but not in datepicker where time is a fixed format, enabled by showTime.

e.g.

```
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.chrono.Chronology;
import java.time.format.DateTimeFormatterBuilder;
import java.time.format.FormatStyle;
import java.util.Locale;

public class DateTimeFormattingDemo {

	public static void main(String[] args) {
		
		Locale locale = Locale.forLanguageTag("da");
		Chronology chronology = ZonedDateTime.now(ZoneId.of("UTC")).getChronology();
		FormatStyle format = FormatStyle.SHORT;
		
		String pattern = DateTimeFormatterBuilder.getLocalizedDateTimePattern(format, format, chronology, locale);
		
		/*
		 * dd/MM/y HH.mm
		 * */
		System.out.println(pattern);
	}
}
```

**Comment by christophs78** [comment]
Ok. I understand. :-)
To be honest this is a feature i don´t need in my day-job. 
And the DatePicker-component was designed by the original author in a way that does not make it easy to do what you expect.
Is it an option for you to provide a PR?

The method `calculateTimeOnlyPattern` is also used to format the pattern for the client. So it´s maybe not enough to modify/extend only this method.

**Comment by melloware** [comment]
Can either or both of you review my PR for this issue please?

**Comment by melloware** [comment]
@carlbradwell17 Just a note in JDK8 Danish is ":" but in JDK11 its properly "."

**JDK8:**
```
en = h:mm a
de = HH:mm
da = HH:mm
```

**JDK11:**
```
en = h:mm a
de = HH:mm
da = HH.mm
```
