### ISSUE TITLE
IE8 client side behavior encoding

### ISSUE THREAD

**Issue by mbechler** [primefaces/primefaces#553]
It seems that IE8 gets confused by the generated javascript for client side behaviors and starts throwing around “Expected identifier, string or number” errors. Quoting the eventName in CoreRenderer fixes the issue.

Fix in CoreRenderer.encodeClientBehaviors:
writer.write(eventName + ":");
->
writer.write("'" + eventName + "':");

**Comment by tandraschko** [comment]
any example application? works fine for me in my applications.
