### ISSUE TITLE
DatePicker:TimeOnly has wrong icons for picker down

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#5535]
When p:datePicker is used with the attribute timeOnly="true", the icons for the picker down are wrong (exactly the same as for picker up) -> see attached screenshot.

![Screenshot from 2020-01-17 08-37-17](https://user-images.githubusercontent.com/10051373/72593657-cb7fee00-3905-11ea-95d6-a1e7978a36bb.png)

The problem is caused by a typo: use ui-icon-car**e**t-1-s instead of ui-icon-car**a**t-1-s

the generate code should be:

`<a tabindex="0" class="ui-picker-down"><span class="ui-icon ui-icon-caret-1-s"></span></a>
`
instead of 

`<a tabindex="0" class="ui-picker-down"><span class="ui-icon ui-icon-carat-1-s"></span></a>
`
by the way, there is also a layout issue: the distances from the picker up and picker down icons to the value are significantly different which does not look good.

## 1) Environment
PrimeFaces version: 8.0 RC2
Application server + version: GF5.1, Payara
Affected browsers: any

## 3) Actual behavior

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

```
<p:datePicker
            value="#{instrument.reservationLatestTime}"
            stepMinute="5"
            pattern="HH:mm"
            timeOnly="true" />
..
```

## 6) Sample bean

..

**Comment by melloware** [comment]
I can't reproduce with 8.0.RC2.  See screenshot:
![image](https://user-images.githubusercontent.com/4399574/72612757-aedeb880-38fb-11ea-8199-9fda2f59cbab.png)

Here is my reproducer just run "mvn clean jetty:run-exploded" and navigate to: http://localhost:8080/primefaces-test/test.xhtml

[pf-5535.zip](https://github.com/primefaces/primefaces/files/4076805/pf-5535.zip)

What "theme" are you using?

**Comment by tuerker** [comment]
Thanks for the feedback. Your example is convincing. I will have a closer view on our side and let you know about the outcome.

**Comment by melloware** [comment]
It might be your THEME. Check what theme you are using I am using Omega in the example above.

**Comment by tuerker** [comment]
I am using the attached theme, which was created via the standard JQuery Theme Roller  https://jqueryui.com/themeroller/

[jquery-ui-1.12.1.custom.zip](https://github.com/primefaces/primefaces/files/4077061/jquery-ui-1.12.1.custom.zip)

This generated theme does not include any ui-icon-carat-* icons but there ui-icon-caret-* icons.

On https://jqueryui.com/upgrade-guide/1.12/#theme it is stated the deprecated ui-icon-carat-* classes were removed and replaced by the ui-icon-caret-* classes.

It looks that PrimeFaces is still using the ui-icon-carat-* classes?

**Comment by melloware** [comment]
PF kept that most likely for backward compatibility those ThemeRoller themes are being phased out in favor of their newer non ThemeRoller themes like Omega, Nova, and Luna that are free and premium themes.

In the PF jar they still include 1 legacy themeRoller them called Aristo you can find here: https://github.com/primefaces/primefaces/tree/master/src/main/resources/META-INF/resources/primefaces-aristo

I juts looked and it still has them named "carat" not "caret" so you might want to edit your theme and rename those icons to "carat" to make it work.

**Comment by tuerker** [comment]
Sure, cloning all ui-icon-caret-* to ui-icon-carat-* classes worked. 

Nevertheless, PrimeFaces should use the ui-icon-caret-* classes instead of the deprecated ui-icon-carat-* classes.

**Comment by melloware** [comment]
well like i said they are phasing out ThemeRoller entirely so i doubt they will update it since their Premium Theme use "carat".
