### ISSUE TITLE
PrimeIcons: Documentation and showcase information missing

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5536]
## 1) Environment
- PrimeFaces version: 8.0RC2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Not relevant
- Affected browsers: Not relevant

## 2) Expected behavior

The documentation on how to activate PrimeIcons is missing from the 8.0 documentation. Likewise the showcase is missing the vital part to include the correct css:

`<h:outputStylesheet name="primeicons/primeicons.css" library="primefaces" />`

This leads to the confusion that while using the correct css classes the icons are not displayed, especially given that FontAwesome is working out of the box.

I think this documentation was originally included in the release notes when PrimeIcons was first introduced but 8.0 users will not find this anymore.

**Comment by melloware** [comment]
I will take care of this.

**Comment by melloware** [comment]
Check this out: https://primefaces.github.io/primefaces/8_0/#/core/fonticons

**Comment by stolp** [comment]
+1 from me

**Comment by melloware** [comment]
Working on updating showcase next.

**Comment by stolp** [comment]
Thanks for including the FontAwesome 5 part, I was not aware of this before.

**Comment by melloware** [comment]
That is how i run my production apps.  FontAwesome 5 has so many more options.

**Comment by erickdeoliveiraleal** [comment]
there's a free fork of fontawesome too: https://github.com/ForkAwesome/Fork-Awesome
