### ISSUE TITLE
DatePicker: Unable to select date.

### ISSUE THREAD

**Issue by marcelocaser** [primefaces/primefaces#5537]
## 1) Environment
- PrimeFaces version: PrimeFaces-8.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? not tested
- Does it work on the newest sources in GitHub? not tested
- Application server + version: not relevant
- Affected browsers: All

## 2) Expected behavior

After selecting a date, you can change it! 

## 3) Actual behavior

You cannot select another date when you already have one selected.

All examples of showcase have this inssues.

## 4) Steps to reproduce

You can test using the showcase. For example, select some date from 'Disabled Date / Day:' and then click again on the 'input' field. As you can see, it is no possible to select any other day. It will only be possible to change it when we click outside the 'input' field and then click again in 'input'.

## 5) Sample XHTML

Not necessary.

## 6) Sample bean

Not necessary.

**Comment by melloware** [comment]
Agree I have verified this in the showcase. It will only let you select another date once you click outside the input field.

**Comment by melloware** [comment]
@christophs78 When I debug this it works if I step through the debugger because in the `showOverlay` method the panel.show() is showing it. However not debugging it does not show.  So I feel like this is a setTimeout issue you had used before and then removed I think we need to put that back.  it feels like it needs to be delayed.

**Comment by melloware** [comment]
I have verified a fix and submitted a PR.  The setTimeout of 100 ms delays fixes it and the panel shows every time
