### ISSUE TITLE
Datatable: Unable to change paginatorPosition once table is rendered

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5544]
## 1) Environment
- PrimeFaces version: 8.0RC2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? Not tested
- Application server + version: Tomcat 9
- Affected browsers: all

## 2) Expected behavior

I try to dynamically switch the paginatorPosition based on the number of rows of the table and the selected rowsPerPage to only display the bottom paginator when enough rows are actually displayed.

I expect that the lower paginator is changing visibility when switching from `top` to `both` and vice versa.

## 3) Actual behavior

The initial setting of the paginatorPosition persists even when the paginatorPosition attribute changes.

## 4) Steps to reproduce

Change the paginatorPosition of a dataTable after initial display.

## 5) Sample XHTML

Will provide a reproducer if required.

## 6) Sample bean

Will provide a reproducer if required.

**Comment by tandraschko** [comment]
we always need a reproducer ;)

**Comment by stolp** [comment]
I put something together ... just checking if this is supported anyway.

**Comment by stolp** [comment]
I added a reproducer. Please let me know i you find something missing or wrong.

[pf-5544.zip](https://github.com/primefaces/primefaces/files/4081537/pf-5544.zip)

**Comment by stolp** [comment]
I am not sure that this is really an enhancement request.

Shouldn't the row selection event trigger a redraw of the table component?

In this case I think it is a bug.

**Comment by melloware** [comment]
i don't think pagination retriggers a redraw of the whole table it only replaces the TBODY I believe.  If you step through the debugger in the browser you will see it remove the old rows and replace the new ones.  So I think this is an enhancement.

See code below which executes after pagination.

```javascript
    updateData: function(data, clear) {
        var empty = (clear === undefined) ? true: clear;

        if(empty)
            this.tbody.html(data);
        else
            this.tbody.append(data);

        this.postUpdateData();
    },
```

**Comment by stolp** [comment]
Thanks, I feared that this is the case.

Noob question: Is my reading of the sources correct in that the paginator is rendered only once during widget creation (called from DatatableRenderer:encodeEnd())?

**Comment by melloware** [comment]
Yes and also in the widget init() method which is whenever the entire datatable is updated in an update="" call.

See..
```javascript
        if(this.cfg.paginator) {
            this.bindPaginator();
        }
```

That sets up the paginator on the datatable.

**Comment by stolp** [comment]
Ok so in this case I could imagine that it would make sense to have an additional datatable event like `pageSizeSelect`. With this the user (like me) would be able to update the whole component if he chooses to.

Would this make sense?

**Comment by melloware** [comment]
I usually leave that kind of advice up to @mertsincan only because the datatable is so complex.

**Comment by stolp** [comment]
@mertsincan What is your opinion on introducing a pageSizeSelection ajax event to the datatable component?

**Comment by mertsincan** [comment]
Hi @stolp, 

Sorry for the delayed response :( I checked this issue but, I think you need to update all datatable. This issue is not only related to paginatorPosition attribute. In all other attributes, you can see this issue.

Maybe,  you can use the following solution for this issue;
in test.xhtml(pf-5544.zip)
```
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Test Page</title>

        <style type="text/css">
            .ui-datatable.show-both-paginator-container .ui-paginator {
                display: block;
            }
            .ui-datatable.show-top-paginator-container .ui-paginator-bottom {
                display: none;
            }
        </style>

        <script type="text/javascript">
        //<![CDATA[
            $(window).on('load', function() {
                changePaginatorPosition();
            });
            
            function changePaginatorPosition() {
                var table = PF('myTable');
                
                if (table) {
                    var rppVal = table.paginator.getRows();
                    
                    if (rppVal > 5) {
                        table.jq.removeClass('show-top-paginator-container').addClass('show-both-paginator-container');
                    }
                    else {
                        table.jq.removeClass('show-both-paginator-container').addClass('show-top-paginator-container');
                    }
                }
            }
        //]]>
        </script>
    </h:head>

    <h:body>
        <p>Switching to more than 5 rows per page should display the bottom paginator but it doesn't.</p>
        <h:form>
            <p:dataTable
                widgetVar="myTable"
                value="#{testView.data}" var="element"
                paginator="true" paginatorPosition="both"
                rowsPerPageTemplate="5,10,15,20"
                paginatorTemplate="{RowsPerPageDropdown}"
                rows="#{testView.rows}">

                <p:ajax event="page" oncomplete="changePaginatorPosition()" />

                <p:column>
                    #{element}
                </p:column>

            </p:dataTable>

        </h:form>
    </h:body>
</h:html>
```
Best Regards,
Sorry again ;)

**Comment by stolp** [comment]
Hi @mertsincan 

Thanks for your reply., This is a nifty solution, thank you!
