### ISSUE TITLE
FileUpload: support chunking and resume

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5547]
PrimeFaces FileUpload (as of 8.0) is not ideal for uploading realy large files. (hundreds of MB or even larger)
- There is no support for resume
- (as far as i understand) we need a good amount RAM because the uploaded file has to fit into the memory

There are libraries like http://www.resumablejs.com/ and https://github.com/blueimp/jQuery-File-Upload which try to solve both requirements. What do you think about adding this with 9.0?

**Comment by tandraschko** [comment]
If you would like to work on it - sure :)

**Comment by christophs78** [comment]
I´ll look at this at some point in the future.

**Comment by christophs78** [comment]
PrimeFaces already includes https://github.com/blueimp/jQuery-File-Upload.
Maybe we only need the server-side part for chunking. And some client-side configuration. (https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads)

**Comment by tandraschko** [comment]
@rapster @christophs78 could you please check our quality gate? 2 new entries here: https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&resolved=false&sinceLeakPeriod=true&types=VULNERABILITY
