### ISSUE TITLE
Dialog: keeping the html/body scroll when showing modal dialog 

### ISSUE THREAD

**Issue by adjiandov** [primefaces/primefaces#5548]
## 1) Environment
- PrimeFaces version: 6.2.2
- Application server + version: JBoss Wildfly 10.0.0
- Affected browsers: all

## 2) Expected behavior
I would like to either override or have a parameter to decide if the scroll in the modal background should be hidden or not.
...

## 3) Actual behavior
When a modal dialog is shown the html/body tags overflow property is set to hidden. for pages that have displayed scroll on these tags when a modal dialog is shown this causes the components on the page to shift right (using the width of the scroll) and then shift left when the dialog is closed.
..

## 4) Steps to reproduce
Open any page that has vertical scroll, then open a dialog.

**Comment by adjiandov** [comment]
Please remove this issue.

**Comment by melloware** [comment]
Closing an issue is all you can do there is no delete issue.
