### ISSUE TITLE
ImageCropper: error page

### ISSUE THREAD

**Issue by marcelocaser** [primefaces/primefaces#5549]
## 1) Environment
- PrimeFaces version: PrimeFaces-8.0-SNAPSHOT

## 2) Expected behavior

The image to be cropped.

## 3) Actual behavior

As you can see in the showcase, a page error is generated after clicking on the 'Crop' button

## 4) Steps to reproduce

Open Cropper in showcase and than click on the 'Crop' button.

## 5) Sample XHTML

Not necessary

## 6) Sample bean

Not necessary

**Comment by Rapster** [comment]
Not reproducible with the latest snapshot (that's why it's important to follow issue template :wink:)

**Comment by melloware** [comment]
@marcelocaser When I run the showcase locally this does not happen so I will wait and see when the next time the showcase is deployed to the public if the Cropper is working ok.

**Comment by marcelocaser** [comment]
thanks @melloware! thank you for your attention!!
