### ISSUE TITLE
P:editor from Primefaces not working

### ISSUE THREAD

**Issue by dimmykarson** [primefaces/primefaces#555]
I have a application with JSF 2.0, Primefaces 5.2, using MDL: Material Design Lite from Google (MDL - http://www.getmdl.io/components/index.html). When I put p:editor on my jsf page it's not working, every elements on editor stay disabled. I inspect elements and saw: every div's disabled.

But, we have a easter egg: When I enter in page, the editor not work, but when I press F12 (to see javascript console) and close that tab (console) the editor starts to work.

Anyone can I help me?

**Comment by tandraschko** [comment]
Please use the forum. It's working fine in the showcase.
