### ISSUE TITLE
Tree: ContextMenu is not working in 8.0RC1 showcase

### ISSUE THREAD

**Issue by adupeyron** [primefaces/primefaces#5550]
## 1) Environment
- PrimeFaces version: 8.0RC1

## 2) Expected behavior
ContextMenu is displayed, and different based on nodeType

## 3) Actual behavior
ContextMenu is not displayed

## 4) Steps to reproduce
showcase Tree: ContextMenu in 8.0RC1
https://www.primefaces.org/showcase/ui/data/tree/contextMenu.xhtml

**Comment by tandraschko** [comment]
Confirmed; Can someone check it?

**Comment by melloware** [comment]
I can investigate

**Comment by melloware** [comment]
The fix for ticket https://github.com/primefaces/primefaces/issues/5069 is what broke this.

@fanste Can you look at your fix? If not I will have no choice but to revert it for the 8.0 release.

**Comment by fanste** [comment]
Nothing to do for me anymore, right? Thanks for providing the fix

**Comment by melloware** [comment]
@fanste Nope you are good I worked it out!

**Comment by adupeyron** [comment]
ok its working and ok with different context menu based on nodeType
Thanks

**Comment by melloware** [comment]
Excellent thanks for reporting it and testing.
