### ISSUE TITLE
PhotoCam: when will it be fixed in Comunity version?

### ISSUE THREAD

**Issue by gambit4348** [primefaces/primefaces#5552]
1) Environment
- PrimeFaces version: **7.0 Community**
- Does it work on the newest released PrimeFaces version? Version? **Possibly YES**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **Not checked**
- Application server + version: **JBoss 7.1.3**
- Affected browsers: **Google Chrome**

2) Expected behavior
Successfully render and operate the component PhotoCam in application deployed in JBoss 7.1.3 and compiled with JDK 1.7

3) Actual behavior
In the moment the page will be handered the following error stack is showed:
**java.lang.IllegalAccessException: Class javax.faces.component.UIComponentBase$AttributesMap can not access a member of class org.primefaces.component.selectonebutton.SelectOneButtonBase with modifiers "public"**
at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:110)
at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:262)
at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:254)
at java.lang.reflect.Method.invoke(Method.java:599)
at javax.faces.component.UIComponentBase$AttributesMap.get(UIComponentBase.java:2342)
at ...

4) Steps to reproduce
Just change the maven dependency from PrimeFaces 6.2 to 7.0 and run the application.

5) Sample XHTML
No need.

6) Sample bean
No need.

7) Additional details
The component PhotoCam does not work in current versions of Google Chrome. Google searches returned some discussions stating that the fix is to upgrade PF to version 7.0 that replaces the file webcam.js to a new version.

However, just doing so produces the problem described. The PrimeFaces forum [issue 58239](https://forum.primefaces.org/viewtopic.php?t=58139) shows a discussion that states PrimeFaces 7.0.10 fixes the problem to users that cannot move from JDK 1.7 to JDK 1.8 (my case), but such a fix is not present in Community version 7.0.

I would like to know about plans for releasing such a fix to PrimeFaces Community. Is there the intention? Is there a date?

Thanks in advance!!!

**Comment by melloware** [comment]
It will be fixed when Community release 8.0 is out.  There is no Community fixes for 7.0 only Elite releases.
