### ISSUE TITLE
Calendar: LocalDateTime validation too lenient

### ISSUE THREAD

**Issue by kaiwinter** [primefaces/primefaces#5554]
Validation of `java.util.Date` is more strict than the validation of `LocalDateTime`. Example see below. Before PrimeFaces 8 I was using a custom Converter which sets `DateTimeFormatter` to `ResolverStyle.STRICT`. This would lead to the same behavior for `LocalDateTime` as for `java.util.Date`. 
I think [`BaseCalendarRenderer:convertToJava8DateTimeAPI`](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java#L194) should be updated to use `ResolverStyle.STRICT` in the [`DateTimeFormatter`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#withResolverStyle-java.time.format.ResolverStyle-) as this is consistent to `java.util.Date` parsing. Currently, by default [ResolverStyle.SMART](https://docs.oracle.com/javase/8/docs/api/java/time/format/ResolverStyle.html) is used.
Another way would be to add a new attribute to `p:calendar` and companions to let the user select the ResolverStyle. What do you think?

Is there any chance to get this into 8.0.Final if I submit a PR? :grimacing:

Just for reference: I was discussing this already in the forum: [PrimeFaces 8.0.RC2, p calendar: ResolverStyle.STRICT](https://forum.primefaces.org/viewtopic.php?f=3&t=60922&p=179780#p179780).

## 1) Environment
- PrimeFaces version: 8.0.RC2

## 2) Expected behavior
When parsing a `java.util.Date` I get an validation error, if I enter `30.02.2020 00:00:00`:
![date](https://user-images.githubusercontent.com/110982/72960972-ee038280-3daf-11ea-9ff2-0440b241ffb9.PNG)
The same error should popup for `LocalDateTime`.

## 3) Actual behavior
The same date when validated to a `LocalDateTime` gets parsed but gets quietly adjusted:
![localdatetime](https://user-images.githubusercontent.com/110982/72961001-05db0680-3db0-11ea-94bf-4351c0498f95.PNG)
A date of `32.02.2020 00:00:00` will popup the validation message :weary:

## 4) Steps to reproduce
Enter the date: 30.02.2020 00:00:00
Example here: https://github.com/kaiwinter/primefaces-test

## 5) Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

         <h:form id="form">
             <p:growl id="msgs" showDetail="true" skipDetailIfEqualsSummary="true" />
              
             <h:panelGrid columns="4">
                 <p:outputLabel for="button1" value="Date:" />
                 <p:calendar
                        id="button1"
                        value="#{testView.date}"
                        showOn="button"
                        pattern="dd.MM.yyyy HH:mm:ss"
                        navigator="true"/>
                 <p:outputLabel for="button1Result" value="Parsed:" />
                 <p:outputLabel id="button1Result" value="#{testView.date}" />
                 
                 <p:outputLabel for="button2" value="LocalDateTime:" />
                 <p:calendar
                        id="button2"
                        value="#{testView.localDateTime}"
                        showOn="button"
                        pattern="dd.MM.yyyy HH:mm:ss"
                        navigator="true"/>
                 <p:outputLabel for="button2Result" value="Parsed:" />
                 <p:outputLabel id="button2Result" value="#{testView.localDateTime}" />
                  
             </h:panelGrid>
              
             <p:commandButton value="Submit" update="msgs button1Result button2Result" />
              
         </h:form>

    </h:body>
</html>
```

## 6) Sample bean
```
@Named
@ViewScoped
public class TestView implements Serializable {

   private Date date;
   private LocalDateTime localDateTime;

   public Date getDate() {
      return date;
   }

   public void setDate(Date date) {
      this.date = date;
   }

   public LocalDateTime getLocalDateTime() {
      return localDateTime;
   }

   public void setLocalDateTime(LocalDateTime localDateTime) {
      this.localDateTime = localDateTime;
   }

}
```

**Comment by tandraschko** [comment]
@christophs78 WDYT?

**Comment by christophs78** [comment]
We should make this configureable via a new ResolverStyle-attribute. (IMO it depends on the usecase what´s "right".)
And we should do this for Calendar and DatePicker.
PR is welcome. (Please also add a few UnitTest´s for this.)

**Comment by kaiwinter** [comment]
OK, I'm working on this.

**Comment by kaiwinter** [comment]
This is a bit embarasing but I missed a positive unit test, which parses a valid date when `resolverStyle` = `STRICT`. Now I've added one and **it fails currently**. The problem is that STRICT is well veeeery strict. When using the date format `yyyy-MM-dd` the `DateTimeFormatter` doesn't know which era you want to parse (yyyy = year of era). Better would be using `uuuu-MM-dd` (uuuu = year). But the calendar and datepicker components doesn't understand "uuuu" and just prints it as text when selecting a date.

A quick fix which I found on [Stackoverflow](https://stackoverflow.com/a/30478777/714965) would be to hardcode the era: `.parseDefaulting(ChronoField.ERA, 1 /* era is AD */)`.

Some more background information can be found on Stackoverflow: [`uuuu` versus `yyyy` in `DateTimeFormatter`](https://stackoverflow.com/a/41182911/714965).

So the question is: Should the current implementation be extended to handle patterns containing "u" or should we just hardcode the era? For now it seems the best solution to go with the hardcoded version (years < 1 can't be parsed). The integration of "u" may be done in a different issue.

@christophs78 what do you think?

**Comment by christophs78** [comment]
IMO hardcoding the ERA-Default is fine. (And it´s only a default, so it´s still theoretical possible to add "G" to the date format.)  I already did a similar trick with DAY_OF_MONTH for monthpicker.
I´ll open another issue for replacing uuuu with yyyy (and similar) in `org.primefaces.convert.DatePatternConverter`.
Can you (re-)open a PR so we are able to merge your modification into master?

**Comment by kaiwinter** [comment]
Great, I've opened a new PR. Sorry for the inconvenience and thanks for your fast replies that makes it a pleasure to contribute here.
