### ISSUE TITLE
DatePicker: Date picker not showing/disappearing in popup mode

### ISSUE THREAD

**Issue by MatthiasScherrerFGCZ** [primefaces/primefaces#5558]
The date picker is not showing resp. disappearing when clicked if there is not enough space to display it, i.e., after a resize or if the window is small from the beginning.
On Firefox (v72.0.1) it works, however on Chrome and Chromium it does not. See the three short videos attached in the zip showing the one working (FF) as well as the two not working examples (Chrome and Chromium).
[datePicker_examples.zip](https://github.com/primefaces/primefaces/files/4104017/datePicker_examples.zip)

## 1) Environment
- PrimeFaces version: PrimeFaces-8.0-SNAPSHOT
- Application server + version: Mojarra-2.3.13
- OS on the client: Ubuntu 18.04.3 LTS
- Affected browsers: Chrome (v79.0.3945.130), Chromium (v79.0.3945.79)

## 2) Expected behavior
- The date picker should be rendered (popup) even if it is not fully visible.

## 3) Actual behavior
- The date picker is rendered (popup) for a short period and then disappears.

## 4) Steps to reproduce
- Go to the PF showcase (https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml)
- Resize to a small window size.
- Click on the field to open up the date picker.

**Comment by melloware** [comment]
I believe this is already fixed.  Have you tested it locally with the latest 8.0-SNAPSHOT?  
See: https://github.com/primefaces/primefaces/issues/5513

The Showcase is still using 8.0.RC1 and is behind the current 8.0-SNAPSHOT.
