### ISSUE TITLE
PrimeReact TreeTable: column parameter not passed to template

### ISSUE THREAD

**Issue by benjblack** [primefaces/primefaces#5565]
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

## 1) Environment
- PrimeFaces version: PrimeReact 3.4.0
- Does it work on the newest released PrimeFaces version? No
- Affected browsers: all

## 2) Expected behavior
`
  nameTemplate(rowData, column) {
    return rowData[column.field];    //this returns the field value
  }

      let testDynamicTreeColumns = testTreeCols.map((col,i) => {
        return <Column key={col.field} field={col.field} header={col.header} body={this.nameTemplate} expander={col.field == 'groupLabel'} />;
      });

          <TreeTable value={testGroupedListItems} header={header} globalFilter={this.state.globalFilter}>
              {testDynamicTreeColumns}
            </TreeTable>

`

...

## 3) Actual behavior
This throws an error because column is undefined!!!
`  nameTemplate(rowData, column) {
    return rowData[column.field];    
  }`

..

## 4) Steps to reproduce

Just setup column templating and try to access the column property.  

I noticed in the source, that in TreeTableBodyCell.js line 120, column is passed to the body handler:
content = this.props.body(this.props.node, this.props.column);

But in TreeTableRow.js line 501, I don't see where column is passed to TreeTableBodyCell.  Only props are:

`<TreeTableBodyCell key={column.props.columnKey||column.props.field} {...column.props} node={this.props.node}>`
..

**Comment by melloware** [comment]
Wrong tracker please use the PrimeReact Issue tracker not the PrimeFaces one.  
**Use:**
https://github.com/primefaces/primereact/issues
