### ISSUE TITLE
Tree: Create ui-tree-droppoint inside empty tree

### ISSUE THREAD

**Issue by usrflo** [primefaces/primefaces#5566]
With the current TreeRenderer implementation there is no drop-point for an empty but droppable tree.

I propose to change https://github.com/primefaces/primefaces/blob/4380e49adb34c4afd3b321000607652541db9ba6/src/main/java/org/primefaces/component/tree/TreeRenderer.java#L801
in the following way:

	public void encodeTreeNodeChildren(FacesContext context, Tree tree, TreeNode node, String clientId, boolean dynamic,
			boolean checkbox, boolean droppable) throws IOException {
		int childCount = node.getChildCount();
		if (childCount > 0) {
			for (int i = 0; i < childCount; i++) {
				if (i == 0 && droppable) {
					encodeDropTarget(context, tree);
				}

				encodeTreeNode(context, tree, node.getChildren().get(i), clientId, dynamic, checkbox, droppable);
			}
		// PATCH START
		} else if (droppable && "root".equals(node.getRowKey())) {
			encodeDropTarget(context, tree);
		}
		// PATCH END
	}

The same needs to be done on horizontal trees I guess.

**Comment by tandraschko** [comment]
It would be great if you can work on it and provide a PR for both PF and the showcase (add a new example)

**Comment by melloware** [comment]
Horizontal and Vertical tree use the same renderer so this fix automatically applies to both.  I also used the already defined constant instead of "root".
