### ISSUE TITLE
SelectOneMenu: Typing in the select list will only match the first character

### ISSUE THREAD

**Issue by Tosken1337** [primefaces/primefaces#5568]
1) Environment
- It does not work on version 7.0.11 or 8.x RC
- It works on previous versions 6.1.x
- Affected browsers: Chrome, IE and Firefox

2) Expected behavior
When the select list is open, typing should select the option which matches the complete typed string.
E.g. selectOneMenu contains (Paris, Istanbul)
Typing 'Pari' should select Paris.

3) Actual behavior
Each typed character will select an entry where the first character matches the typed character.
Typing 'Pari' will select 'Instanbul' (because of the last i)

4) Steps to reproduce
You can check it here
https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

**Comment by melloware** [comment]
Read through this whole ticket: https://github.com/primefaces/primefaces/issues/4682

I think it depends on how fast you type.  If I type Paris fast it works if I type it slow it goes to Instanbul.

And also try it with a normal native HTML5 select box to compare the behaviors.

**Comment by Tosken1337** [comment]
Okay, i see.
There was a change in the 7.1 milestone for this right?
Will there also be a fix in the 7.0.x branch?

**Comment by melloware** [comment]
That fix was put in 7.0.2 so if you are using 7.0.11 you have the current HTML5 like behavior already.

**Comment by Tosken1337** [comment]
Okay now i checked again and figured out whats wrong.
I use a capital first letter.
Then it does not work as expected.
So go to the sample page and type:
'Pari' with capital P.
This will select Instanbul

**Comment by melloware** [comment]
Ahh yep that makes sense.

**Comment by Tosken1337** [comment]
This behavior makes sense for you?
Is it not an issue from your point of view?

**Comment by melloware** [comment]
Unfortunately no i don't think its broken.  

in PF 6.2 it did this and always forced to lowercase text
```javascript
var text = String.fromCharCode(key).toLowerCase();
```

But that was the cause of this reported issue: https://github.com/primefaces/primefaces/issues/4764

**Comment by melloware** [comment]
Also it was broken previously in 6.2 see this ticket: https://github.com/primefaces/primefaces/issues/2356

**Comment by melloware** [comment]
However you are more than welcome to debug and provide a fix just make sure to regression test #2356 #4764 and #4682
