### ISSUE TITLE
p:inputNumber: Too restrictive for double/float values

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#5573]
The p:inputNumber component Is too restrictive and thus not really useful for double/float values. By default, the decimalPlaces attribute is set to 2 digits and you cannot even get rid of this default value. In case of double/floating, you do not know in advance how much fraction digits are needed and thus you cannot set it explicitly. The workaround to use a large number for the decimalPlaces attribute has the disadvantage that it does not work nicely when padControl is activated because then the value will be padded with a lots of zeros.

Therefore, the decimalPlaces attribute of the p:inputNumber component should not generally be restricted to 2. This depends on the type of the incoming value.

## 1) Environment
- PrimeFaces version: 8.0 RC3

## 2) Expected behavior

Calling p:inputNumber on a double value should not pose any restriction on the decimalPlaces, which is set to 2 in any case, which is obviously not a good decision for double/floating values. 

## 3) Actual behavior

Using <p:inputNumber  value="#{AnyDoubleValue}" /> will restrict the fraction to 2 digits. 

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
WDYT @metaxmx @melloware @Rapster ?

**Comment by metaxmx** [comment]
The current InputNumber implementation makes heavy use of the formatting library AutoNumeric (https://github.com/autoNumeric/autoNumeric).
However, the AutoNumeric library only seems to support fixed-point inputs, specialized for currencies, percentages etc.
I found no support to enter a floating-point number, like `"1.45e27"`, only fixed-point decimals like `"0.00000000000000000345"` or `"123400000000000000000000000000000000.0"` which then can be converted to a float with the `getNumber` function in JS or by binding it to a double/float in the backend.

@tuerker You can have a look at the configuration options yourself: http://autonumeric.org/configurator
Unfortunately I found no way to configure it for real float support. Best I can think of is setting the `allowDecimalPadding` to `"never"` (I guess this means setting the `padControl` property of the widget to `false`), enter a large number for `decimalPlaces` and also a large number for `minimumValue` and `maximumValue` which is ten trillion by default (`10000000000000` and `-10000000000000`).

I guess, to allow entering floats (as in floating-point number, contrary to fixed-point number), you would either need to use a different number library than AutoNumeric or use a different widget.
I suppose, if you don't have a fixed-point display format, you don't need a lot of other features like setting the `digitalGroupSeparator` as well.

However, this is just my perception of this problem. I'm not an expert.

**Comment by tandraschko** [comment]
Thanks @metaxmx, i appreciate your feedback.

**Comment by melloware** [comment]
I agree with @metaxmx assessment.  I think there is nothing for us to fix here, if you want InputNumber you have to declare how many decimal places you want.

If you want a truly floating point number i think you will have to use a different custom JS component other than AutoNumeric or just use InputText and write some client side JS to restrict to only numeric entry onKeyDown.

**Comment by tuerker** [comment]
@melloware: i know it is not the fully fixing the issue, but could you do also the following 

```
        String defaultDecimalPlaces = "2";
        if (value instanceof Long || value instanceof Integer **|| value instanceof Short**) {
            defaultDecimalPlaces = "0";
        **} else  if (value instanceof Double || value instanceof Float) {
            defaultDecimalPlaces = "MAXVALUE_THAT_IS_SUPPORTED";**
        }

```
as you did it for the long/integer fix in

https://github.com/melloware/primefaces/commit/0b88faff7c5ebb3b582030b00d239c36ba1a968e

by the way, you could easily add defaultDecimalPlaces = "0" for Short;

Many thanks in advance.

**Comment by melloware** [comment]
So you are saying leave decimalPlaces 2 for BigDecimal 0 for Integer/Long/Short and Max Value supported for Double and Float.  Do you know what the max value supported is?

**Comment by metaxmx** [comment]
I'm not sure that a very high `decimalPlaces` would be a good default value for a widget that handles fixed-point numbers. AutoNumeric itself has also a default value of `2` (probably because this is a reasonable precission for currency values).

You can easily set up AutoNumeric for e.g. 200 decimal places. But then your numbers would be formatted like `"7.81000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001"` which doesn't even make sense for entering float/double values ...

**Comment by melloware** [comment]
@metaxmx I agree with you.  I do think "0" is reasonable for int/long/short but "2" should be the smart default for all other types.
