### ISSUE TITLE
InputNumber: @Digits is ignored for decimalPlaces

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#5574]
The p:inputNumber component takes into account certain javax validation constraints such as @DecimalMin or @DecimalMax, but ignores some important ones such @Digits or @Positive, or @PositiveZero.

## 1) Environment
- PrimeFaces version: 8.0 RC3

## 2) Expected behavior

Calling p:inputNumber on a value with the annotation     

@Digits(integer = 6, fraction = 3)

should implicitly set decimalPlaces to 3, the maxValue to 999999.999, and the minValue to -999999.999 (unless these values are not overwritten by other annotations).

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
Feel free to work on it: https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java#L124

**Comment by melloware** [comment]
Digits is already in use because its a BV1.0 class however it just doesn't do the min and max number but it does account for decimal places...
https://github.com/primefaces/primefaces/blob/29e6f9fecf0f80f7af0240e4d25e876b8d39d2f4/src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java#L140-L143

However @Positive and @PositiveZero are BV1.1 and cannot be imported into BeanValidationInputMetadataTransformer

**Comment by tandraschko** [comment]
it can be used if we check for 1.1 before accessing it
just check e.g. JSF23Helper

**Comment by tuerker** [comment]
@melloware Could it be that the following code 

```
            if (annotationType.equals(Digits.class) && LangUtils.isValueBlank(inputNumber.getDecimalPlaces())) {
                Digits digits = (Digits) constraint;
                inputNumber.setDecimalPlaces(String.valueOf(digits.fraction()));
            }

```
is not working as expected since 

`inputNumber.getDecimalPlaces()
`
is always set to 2 by default and therefore this if statement always delivers false such that the Digit annotation has no effect even on the decimalPlaces value?

**Comment by melloware** [comment]
I would step through the debugger and see. I would expect that to get triggered.

And are you also sure you have enabled Bean Validations in your web.xml with...
```xml
<context-param>
    <param-name>primefaces.TRANSFORM_METADATA</param-name>
    <param-value>true</param-value>
</context-param>
```
https://primefaces.github.io/primefaces/8_0/#/core/beanvalidationtransformation

**Comment by tandraschko** [comment]
@tuerker is right here, AFAIR the default was set last week; so the value is never empty.

A possible fix would be to render a default in the renderer and not set the default via the initialValue in the stateHelper

**Comment by melloware** [comment]
Ahh yeah we probably need to check if its empty or DEFAULT value

**Comment by tandraschko** [comment]
Please see my commit. This should at least fix the current supported annotations

**Comment by melloware** [comment]
@tandraschko that looks good.

**Comment by tandraschko** [comment]
Please create a new issue for supporting new annotations; i renamed this issue to fix @Digits

**Comment by tuerker** [comment]
Many thanks. I will create a new issue.
