### ISSUE TITLE
Spinner: should not allow to enter non-numeric values

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#5579]
The p:spinner component should not allow to enter non-numeric values. 

## 1) Environment
- PrimeFaces version: 8.0 RC3

## 2) Expected behavior

The spinner component allows only numeric values and does not let the user enter any symbols that would lead to non-numeric values.

Above that the spinner should only allow only values that are instances of the underlying number class. For instance, if the spinner is invoked with Long/Integer/Short values it should automatically apply decimalPlaces="0". 

Ideally, all bean validation constraints should be also fully respected to.

## 3) Actual behavior

Current you can enter any string. In some cases, the spinner will crop them to numeric values, in some not. See Below:

* you can enter -1-222 and will produce -1.

* when you enter .022.222 it will even be accepted as it is.

## 4) Steps to reproduce

Just use the basic spinner demo https://www.primefaces.org/showcase/ui/input/spinner.xhtml
and enter the above values.

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tuerker** [comment]
@melloware: This seems to be broken again! I am on the (~3 weeks old) latest snapshot.

**Comment by tuerker** [comment]
You can easily enter non-numeric values for the spinner.

**Comment by melloware** [comment]
I am looking through the changelog since March 24 and this component really hasn't been touched.  This ticket only talked about not allowing two negative signs or multiple period "." Are you sure this was ever actually reported?

I am out on the 8.0 Showcase here: https://www.primefaces.org/showcase/ui/input/spinner.xhtml and it has your old problem of allowing multiple negative signs as well as allowing "abc".

**Comment by tuerker** [comment]
Look at the title of the issue "Spinner: should not allow to enter non-numeric values".

**Comment by melloware** [comment]
Yep but i looked at your two examples given in this ticket...
```
you can enter -1-222 and will produce -1.

when you enter .022.222 it will even be accepted as it is.
```

You didn't specify not typing in "abc" or any other character.

I need to write some integration tests.

**Comment by tuerker** [comment]
many thanks.

**Comment by melloware** [comment]
Added failing integration tests:
https://github.com/primefaces-extensions/primefaces-integration-tests/commit/2028db3f4cf8670825892ce6eb0698ca72885860

**Comment by melloware** [comment]
All integration tests are now passing after this fix. 
https://github.com/primefaces-extensions/primefaces-integration-tests/actions/runs/368763582
