### ISSUE TITLE
Autocomplete(multiple = "true") won't call converter if declare with @FacesConverter(forClass... but only with explicit call 

### ISSUE THREAD

**Issue by zamrokk** [primefaces/primefaces#558]
PrimesFaces version 5.2

i have an autocomplete "multiple=true" on an object list

if i use a converter like this
    @FacesConverter(forClass = TypeDocumentDto.class)
then converter is not called

if i do this 
     @FacesConverter(value="typeDocumentConverter",forClass = TypeDocumentDto.class)
and this in the xhtml
     converter="typeDocumentConverter"
then the conveter is finally called

i was expecting the conveter to be called in any manner because it works with a single selection autocomplete 

Does this require a dev or is a bug ?

**Comment by fanste** [comment]
Search for `@FacesConverter forClass` via your favorite search engine and you will be pointed to some JSF bugs. E.g. http://forum.primefaces.org/viewtopic.php?f=3&t=30074

**Comment by cagataycivici** [comment]
Not sure if we are able to extract the type info from a List binding with ValueExpression APIs which is the case for multiple so explicit declaration is required. @tandraschko Do you know if this is possible to retrieve Type class from _List<Type> list_ value expression?

``` xml
<p:autoComplete value="#{bean.list}"
```

``` java
private List<Type> list;

//getter-setter
```

**Comment by tandraschko** [comment]
I can check it but AFAIK it's not possible cause type erasure.

**Comment by tandraschko** [comment]
AFAICS it's only possible to get the type from a field:
http://stackoverflow.com/questions/1942644/get-generic-type-of-java-util-list

This would require some reflection stuff on our side.
We would need to get #{bean} first and get "list" via reflection to get the generic type.

 I would close it as won't fix as it's seems to be very hacky and the workaround is very easy.

**Comment by cagataycivici** [comment]
I agree, thank you.
