### ISSUE TITLE
DataTable: Reordering duplicates columns after update

### ISSUE THREAD

**Issue by jthalmai** [primefaces/primefaces#5582]
## 1) Environment
- PrimeFaces version: 8.0-Snapshot
- Does it work on the newest released PrimeFaces version? No (7.0)
- Does it work on the newest sources in GitHub? No
- Application server + version: WildFly 18
- Affected browsers: Firefox

## 2) Actual behavior

On our page we have a `p:dataTable` with `draggableColumns="true"` which is updated via Ajax when there is new data available. If an update happens after the user has started dragging a column and then the user drops the column at the desired position, this column is duplicated.

## 3) Steps to reproduce

Can be reproduced with the showcase 'DataTable - Reorder' by adding an id to the table and a `p:poll` to simulate the update:

```
<p:poll update="reorderTable" autoStart="true"/>
    
    <p:dataTable id="reorderTable" ...
```

Then drag a column, wait 2 seconds until the table is updated, and drop the column at another position afterwards.

**Comment by melloware** [comment]
I am not sure this is easily fixable because you are dragging while the AJAX update happens underneath of you in the DOM.    I think the only thing possibly may be to not allow that as a drop target if an AJAX event happens underneath while you are dragging.

**Comment by jthalmai** [comment]
Do you think it would also be possible to just check for duplicated column IDs in the drop event listener?

**Comment by melloware** [comment]
Possibly. Feel free to investigate looks like all the drag and drop code is in datatable.js in the method `setupDraggableColumns()`.

**Comment by melloware** [comment]
Was able to fix it for draggableRows or draggableColumns as they both had the issue.

Reproducer: 
[pf-5582.zip](https://github.com/primefaces/primefaces/files/4405110/pf-5582.zip)

**Comment by melloware** [comment]
If you need this right now just add this JavaScript to your page:
```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.unbindEvents = function() {
        if (this.sortableColumns) {
            this.sortableColumns.off();
        }
        if (this.paginator) {
            this.paginator.unbindEvents();
        }

        // #5582: destroy any current draggable items
        if (this.cfg.draggableColumns || this.cfg.draggableRows) {
            var dragdrop = $.ui.ddmanager.current;
            if (dragdrop) {
                document.body.style.cursor = 'default';
                dragdrop.cancel();
            }
        }
    };
}
```
