### ISSUE TITLE
Datatable: Additional Header text shown in a dragged datatable row when reflow="true" is set

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5584]
[pf-5584.zip](https://github.com/primefaces/primefaces/files/4152578/pf-5584.zip)
## 1) Environment
- PrimeFaces version: 8.0RC3
- Does it work on the newest released PrimeFaces version? No (Checked against 7.0.10)
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: -
- Affected browsers: All

## 2) Expected behavior

The dragged row should not change when reflow="true" is set.

## 3) Actual behavior

The dragged row contains the header text as well as the row content.

## 4) Steps to reproduce

See supplied reproducer. Try to drag a row.

## 5) Sample XHTML

See supplied reproducer. 

## 6) Sample bean

See supplied reproducer.

**Comment by klaros-testmanagement** [comment]
@melloware: I do not understand why this is flagged as an enhancement and not as a bug.

Shouldn't a dragged row keep its look when reflow is set to true?

**Comment by stolp** [comment]
@melloware: I do not understand why this is flagged as an enhancement and not as a bug.

Shouldn't a dragged row keep its look when reflow is set to true?

**Comment by melloware** [comment]
switched to defect.

**Comment by melloware** [comment]
I know why. For reflow it looks like the column title <span> is put inside every single row like this...

```xml
<td role="gridcell" class="ui-sortable-handle">
   <span class="ui-column-title">Year</span>
   1977
</td>
```

so when you drag its taking the HTML content of the cell which is "Year1977".

**Comment by melloware** [comment]
@stolp can you test this before I merge my fix.  Add this to your JS.

```javascript
PrimeFaces.widget.DataTable.prototype.makeRowsDraggable =function() {
        var $this = this,
        draggableHandle = this.cfg.rowDragSelector||'td,span:not(.ui-c)';

        this.tbody.sortable({
            placeholder: 'ui-datatable-rowordering ui-state-active',
            cursor: 'move',
            handle: draggableHandle,
            appendTo: document.body,
            start: function(event, ui) {
                ui.helper.css('z-index', ++PrimeFaces.zindex);
            },
            helper: function(event, ui) {
                var cells = ui.children(),
                helper = $('<div class="ui-datatable ui-widget"><table><tbody class="ui-datatable-data"></tbody></table></div>'),
                helperRow = ui.clone(),
                helperCells = helperRow.children();

                for(var i = 0; i < helperCells.length; i++) {
                    var helperCell = helperCells.eq(i);
                    helperCell.width(cells.eq(i).width());
                    // #5584 reflow must remove column title span
                    helperCell.children().remove('.ui-column-title');
                }

                helperRow.appendTo(helper.find('tbody'));

                return helper;
            },
            update: function(event, ui) {
                var fromIndex = ui.item.data('ri'),
                toIndex = $this.paginator ? $this.paginator.getFirst() + ui.item.index(): ui.item.index();

                $this.syncRowParity();

                var options = {
                    source: $this.id,
                    process: $this.id,
                    params: [
                        {name: $this.id + '_rowreorder', value: true},
                        {name: $this.id + '_fromIndex', value: fromIndex},
                        {name: $this.id + '_toIndex', value: toIndex},
                        {name: this.id + '_skipChildren', value: true}
                    ]
                }

                if($this.hasBehavior('rowReorder')) {
                    $this.callBehavior('rowReorder', options);
                }
                else {
                    PrimeFaces.ajax.Request.handle(options);
                }
            },
            change: function(event, ui) {
                if($this.cfg.scrollable) {
                    PrimeFaces.scrollInView($this.scrollBody, ui.placeholder);
                }
            }
        });
    };
```

**Comment by stolp** [comment]
Thanks a lot @melloware!

I tried it and it basically works, but I still have the same effect upon the first page load.
Once switching the tab view back and forth (in my use case the table is inside a tab), everything works as expected.

It may have to do with the initialization time of the Javascript in my case, I currently have placed this inside an `<o:onloadScript> `.

**Comment by melloware** [comment]
Oh then it will most likely work as if its part of the core datatable code it will be run properly its just an AJAX timing issue with TabView in your current setup.  But thanks for Testing the fix I will merge it.
