### ISSUE TITLE
Media: quicktime player NPE with StreamedContent in 8.0RC3

### ISSUE THREAD

**Issue by adupeyron** [primefaces/primefaces#5586]
## 1) Environment
- PrimeFaces version: 8.0RC3

## 2) Expected behavior

mp4 video auto play

## 3) Actual behavior

java.lang.NullPointerException
	at org.primefaces.component.media.MediaRenderer.encodeEnd(MediaRenderer.java:63)

## 4) Steps to reproduce
 
with a bean returning a mp4 as StreamedContent

## 5) Sample XHTML

			<p:media height="200px" value="#{mediaBean.testMp4}" player="quicktime">
				<f:param name="autoPlay" value="false" />
				<f:param name="autostart" value="false" />
			</p:media>

## 5) Sample Bean

@Named
@RequestScoped
public class MediaBean {

	public StreamedContent getTestMp4() {
		File fileReport = new File("xxx", "20170823_142100.mp4");
		String contentType = FacesContext.getCurrentInstance().getExternalContext().getMimeType(fileReport.getName());
		return DefaultStreamedContent.builder().stream(() -> {
			try {
				return new BufferedInputStream(new FileInputStream(fileReport));
			} catch (FileNotFoundException e) {
				e.printStackTrace();
				return null;
			}			
		}).contentType(contentType).name(fileReport.getName()).build();
	}
}

## 7) Proposed correction
In org.primefaces.component.media.MediaRenderer.java 
in encodeEnd line 63

replace
        if (value instanceof StreamedContent && player.getType().equals("application/pdf")) {
by
        if (value instanceof StreamedContent && "application/pdf".equals(player.getType())) {
 or by
       if (value instanceof StreamedContent && player.getType() != null && player.getType().equals("application/pdf")) {

ok in line 73

**Comment by melloware** [comment]
I submitted a PR.   This is good defensive programming either way Joushua Bloch always says compare the constant on the left to prevent NPE's.
