### ISSUE TITLE
ImportConstants: Limited to top-level scope - unable to use ui:include

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5588]
[pf-5588.zip](https://github.com/primefaces/primefaces/files/4159408/pf-5588.zip)
## 1) Environment
- PrimeFaces version: 8.0RC3
- Does it work on the newest released PrimeFaces version? Version? no, 7.0.10
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: All
- Affected browsers: All

## 2) Expected behavior

I expect to be able to put the <p:importConstants> element inside an included file (via ui:include) and reuse it in several files.

## 3) Actual behavior

<p:importConstants> has to be present directly on the top-level jsf file.

The user does not expect this.
See (speculative):  https://forum.primefaces.org/viewtopic.php?t=58493

If this is unevitable it should at least be documented.

## 4) Steps to reproduce

See attached reproducer.

## 5) Sample XHTML

See attached reproducer.

## 6) Sample bean

See attached reproducer.

**Comment by melloware** [comment]
I will let @tandraschko answer as he knows more than I do but JSF 2.3 added `f:importanConstants` which is what PrimeFaces and OmniFaces ImportConstants was used for in the past.

If you look at the JavaDoc: https://javaee.github.io/glassfish/doc/5.0/vdldoc/f/importConstants.html

It says "Used inside of the metadata facet of a view,".

So a good practice it to declare your constants in metatadata like..

```xml
<f:metadata>
  <f:importConstants type="javaee8.jsf23.PlayerEnum" />
 </f:metadata>
```

That should make it available on your whole page and in all your ui:includes.

**Comment by tandraschko** [comment]
Please provide a PR for the documentation

**Comment by stolp** [comment]
Thanks for the hints and clearing this up.

My point was that I liked to reuse the **importConstants elements** via <ui:include> in several files.

From what I got here (and some further experiments), this seems not possible with current JSF implementations.

Am I correct here?

**Comment by melloware** [comment]
I think that is correct as the recommended place is in f:metadat unless f:metadata allows using ui:include which I have never tried.  @tandraschko am I wrong on this?

**Comment by stolp** [comment]
From my experiments with the reproducer ui:include seems not to be supported in f:metadata,

I am unsure if this is a side effect, intentional or just unspecified.

**Comment by melloware** [comment]
If I had to guess it was intentional in the JSF spec.

**Comment by melloware** [comment]
OK check out the updated docs I added a Warning at the bottom.
https://primefaces.github.io/primefaces/8_0/#/components/importconstants

**Comment by tandraschko** [comment]
The docu is not correct
p:importConstants/Enum must NOT be in f:metadata, thats only for the f:*, which was IMO a bad decision for the JSF api

**Comment by melloware** [comment]
Are you sure?  Mine works fine having p:importConstants in f:metadata?

**Comment by tandraschko** [comment]
p:importConstants works everywhere on the page, it doesnt matter
also it works inside the ui:include, when declared inside the ui:include itself
the var is set as attribute to the FaceletContext

**Comment by tandraschko** [comment]
the JSF API just has the restriction to only work in f:metadata, PF doesn't has this restriction
