### ISSUE TITLE
FileUpload: Improve VirusScanner Interface

### ISSUE THREAD

**Issue by Thomas-Schindler** [primefaces/primefaces#5594]
I would suggest to improve the VirusScanner interface which is intented for implementing custom scan services, so that within the implementation file metadata about the uploaded file (name, MIME-type) and a reference to the fileupload component is available. This would make it possible to log the filename etc. and to inform the user about the problem if a virus threat was detected.

Also it would be great to change the `org.primefaces.virusscan.VirusException` in a way that it extends `javax.faces.validator.ValidatorException` and the message of the thrown exception is shown as error message in the FileUpload component for informing the user about the detected problem with the file.

I described my problem here: [https://forum.primefaces.org/viewtopic.php?f=3&t=61116](https://forum.primefaces.org/viewtopic.php?f=3&t=61116)

## 1) Environment
- PrimeFaces 7.0.11
- JSF: Mojarra 2.3.9.SP04
- JBoss Wildfly 18.0.1 Final
- Affected browsers: all Browsers

## 2) Expected behavior

The interface should perhaps look like this:

`    /**
     * Perform virus scan and throw exception if a virus has been detected.
     * @param inputStream input stream to perform virus scan on
     * @param facesContext the current FacesContext
     * @param uploadedFile The uploaded file the scan is conducted for containing the files metadata
     * @param fileUpload the fileUpload component
     * @throws VirusException if a virus has been detected by the scanner
     */
    void performVirusScan(InputStream inputStream, FacesContext facesContext, UploadedFile uploadedFile, FileUpload fileUpload) throws VirusException;

`

If it is not acceptable to provide the UploadedFile (which in turn exposes an InputStream of the uploaded file, what may not be intended.), at least the name and mime type should be provided.

## 3) Actual behavior

Currently only an FileInputStream is available:
`    /**
     * Perform virus scan and throw exception if a virus has been detected.
     * @param inputStream input stream to perform virus scan on
     * @throws VirusException if a virus has been detected by the scanner
     */
    void performVirusScan(InputStream inputStream) throws VirusException;

`

**Comment by melloware** [comment]
@Thomas-Schindler thanks for reporting. Since 8.0 is about to be released this won't make it until the next version.  Any chance you would like to submit a PR for this enhancement?

**Comment by Rapster** [comment]
+1 Regarding:

First problem: What about having this signature: `VirusScanner#performVirusScan(UploadedFile)` as simple as that? Let me know if you need more arguments, but I feel UploadedFile contains everything you need

Second problem: fully agree, we lose on VirusException infos. We'll have to rethink `FileUploadUtils#isValidFile` impl, maybe it should no longer return a boolean but throw an exception in case something wrong, maybe `FileUploadUtils#tryValidateFile` instead?

WDYT @Thomas-Schindler ?

**Comment by Thomas-Schindler** [comment]
Hi,

@melloware 
Yes, definitely I would like to submit a PR for this enhancement. I just need some time to get familiar  with the Terms&Conditions for contributing to PrimeFaces. :-)

@Rapster Thank you for your considerations. 

I totally agree with you to keep the signature as simple as possible. So I would go for your suggestion to change the Interface to `VirusScanner#performVirusScan(UploadedFile)`. 

I would suggest to enhance the components interface with a `detectedVirusMessage` so the JSF developer can define, what information is presented to the user of the web application. This should be displayed in case a virus is detected, similar to the error message for the size or content type limit. Maybe the implementation of `FileUploadUtils#isValidFile` has to be changed for this.

Whether to log which virus threats were detected on which file is up to the implementer of the `VirusScanner` Interface.

**Comment by Rapster** [comment]
I'm actually working on a PR for this, I'll submit something ASAP

**Comment by Thomas-Schindler** [comment]
OK - that's fine! :-)

**Comment by Rapster** [comment]
See PR #5615

**Comment by tandraschko** [comment]
@Rapster please also adjust the migration guide
