### ISSUE TITLE
PDF exporter downloads or pops open the file based on # of records in datatable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#5598]
Reported By PRO User;
> Observed with Primfaces 8 RC2 , PDF DataExporter.

> Issue:
> When datatable has more than 300 rows, data exporter is opening the pdf file on click of PDF exporter.
> When less number of rows(approx. 20) are present in data table, data exporter is downloading the pdf.

>Expected result:
>Always prefer the pdf to be downloaded, like in Primefaces 7, rather than opening, on click of PDF exporter icon.

**Comment by melloware** [comment]
@mertsincan can you check my comment, I think there may be a bug introduced?
