### ISSUE TITLE
ManyMenu CSS - icon state highlight overrides active - must be reverse

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#560]
There is a CSS issue regarding ManyMenu with checkboxes and the selected items.

In DOM class _ui-state-active_ is applied to the checkbox icon. But in parent _<tr>_ element class _ui-state-highlight_ is applied so the state is overriden.

This results in the icon color being ignored from the _active_ class and the color is taken from _highlight_ class, which result in invisble icons.

This is not appearant in many themes because by chance the icon's color of class _active_ and _highlight_ are similar.

It is very obvious in themes _cruze_ and _dark-hives_

![Selected item without icon checkbox](http://fs1.directupload.net/images/150724/jwkqrpkc.jpg)
## Workaround
- Use same renderer as content of _CheckboxMenu_
- Apply _!important_ to _ui-state-active_ _background-image_ css attribute to overwrite it.
- Apply class _ui-state-highlight_ only to cells without the checkbox

**Comment by melloware** [comment]
Closing this issue as it should be reported in the Legacy Themes issue page here: https://github.com/primefaces/themes/issues 

I don't have permission to transfer this to that repository so I am closing it.
