### ISSUE TITLE
SelectManyMenu: selectAll/unselectAll throws an exception when showCheckbox is true

### ISSUE THREAD

**Issue by andrewtobilko** [primefaces/primefaces#5600]
## 1) Environment
- PrimeFaces version: 8.0.RC-3

## 2) Expected behavior

As usual, `selectAll` would mark all the items as selected, and set/remove appropriate classes.

## 3) Actual behavior

`selectAll` throws an exception

> components.js.jsf?ln=primefaces&v=8.0.RC3:25 Uncaught TypeError: Cannot read property 'classList' of undefined

    selectAll: function() {
        for (var c = 0; c < this.items.length; c++) {
            var e = this.items.eq(c);
            var b = e[0];
            b.classList.add("ui-state-highlight");
            b.classList.remove("ui-state-hover");
            if (this.cfg.showCheckbox) {
                var f = e.children("div.ui-chkbox").children("div.ui-chkbox-box");
                var a = f[0];
                // it happens here, a is undefined
                a.classList.remove("ui-state-hover");
                a.classList.add("ui-state-active");
                var d = f.children("span.ui-chkbox-icon")[0];
                d.classList.remove("ui-icon-blank");
                d.classList.add("ui-icon-check")
            }
        }
        for (var c = 0; c < this.options.length; c++) {
            this.options[c].selected = true
        }
    },

The same happens when you `unselectAll` because the two methods share the same faulty logic.

## 4) Steps to reproduce

1. Define a widget with `showCheckbox="true"` as shown below in the sample.
2. Call `PF('test').selectAll();`.

## 5) Sample XHTML

    <p:selectManyMenu id="basic" widgetVar="test" var="var" showCheckbox="true">
        <f:selectItem itemLabel="Option 1" itemValue="1"/>
        <f:selectItem itemLabel="Option 2" itemValue="2"/>
        <f:selectItem itemLabel="Option 3" itemValue="3"/>
    </p:selectManyMenu>

**Comment by andrewtobilko** [comment]
@melloware forgot to mention - the same goes for `unselectAll`, I will update the post accordingly.

**Comment by christophs78** [comment]
Minor notes:
1. We should add unselectAll() to selectmanymenu.md
2. We should add a selectAll/unselectAll example to the showcase

**Comment by christophs78** [comment]
I tried the following:
![grafik](https://user-images.githubusercontent.com/10461942/74592711-4aab3380-5024-11ea-877a-730324430f95.png)
It currently work´s for "basic" but it has a defect for "advanced" (because using p:column)

**Comment by melloware** [comment]
nice work @christophs78
