### ISSUE TITLE
SelectManyMenu: deselecting the only selected option and clicking outside of the checkbox area doesn't trigger 'change'

### ISSUE THREAD

**Issue by andrewtobilko** [primefaces/primefaces#5604]
## 1) Environment
- PrimeFaces version: 8.0.RC3

## 2) Expected behavior

Clicking on ANY element within an option (an element with class`.ui-selectlistbox-item`) should trigger `'change'` for both selecting and unselecting.

## 3) Actual behavior

When deselecting the only selected option (1) and clicking outside of the checkbox area (2), `change` isn't being triggered.

## 4) Steps to reproduce

Scenario 1:

1. Select two options.
2. Deselect any of them by clicking on a non-checkbox area.
3. An ajax `'change'` listener has been triggered. OK.

Scenario 2:
1. Select one option.
2. Deselect it by clicking on a non-checkbox area.
3. An ajax `'change'` listener has not been triggered. NOT OK.

## 5) Sample XHTML

    <p:selectManyMenu id="basic" showCheckbox="true">
        <p:ajax async="true" event="change" listener="#{ctrl.listener}"/>

        <f:selectItem itemLabel="Option 1" itemValue="1" />
        <f:selectItem itemLabel="Option 2" itemValue="2" />
        <f:selectItem itemLabel="Option 3" itemValue="3" />
    </p:selectManyMenu>

**Comment by melloware** [comment]
The bug is this line right here. It doesn't make any sense to me on what it is trying to prevent.
```javascript
unchanged = (!metaKey && selectedItems.length === 1 && selectedItems.index() === item.index());
```

**Comment by melloware** [comment]
Reproducer: 
[pf-5604.zip](https://github.com/primefaces/primefaces/files/4214321/pf-5604.zip)
