### ISSUE TITLE
Event with multiple days in the Schedule component is shown 1 day short

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#561]
After upgrading PF5.2 from PF5.1, when an event which has multiple days is created with the Schedule component, the event is always one day short on the schedule menu. The start date of the event on the schedule menu is correct, but the end date is one day before the real end date of the event. The Schedule Demo in the PrimeFaces ShowCase has the same problem.

**Comment by cagataycivici** [comment]
Demo is implemented that way, when 00:00 does not include next day so next day is not added, in your code you can just choose to include next day. Watch out for timezones though.

**Comment by cagataycivici** [comment]
Edited demo to avoid confusion.

**Comment by ghost** [comment]
Thank you for your reply, but even if the time of the end date in my application is set, as long as the time is less than 9am or all day flag is set to true, the end date is not shown correctly, 1 day short. However my application worked well with PF5.1, but not with PF5.2. As for timezone, it is correctly set to Schedule component and Calendar components which are used to set Start Date and End Date for an event.

**Comment by ghost** [comment]
This problem is not closed yet. Schedule Demo in PF ShowCase still has the same problem. As I am not familiar with this Issue Tracker system, I do not know how to change the status back to "Open". Should I create a new issue?
