### ISSUE TITLE
TreeNode add selectable attribute

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#5610]
Currently you can allow selections to be made in a tree:

https://www.primefaces.org/showcase/ui/data/tree/selection.xhtml

I would like to have an option to exclude nodes from being selectable.

**Comment by melloware** [comment]
@jepsar you can do this now with `setSelectable(false)`?

I just did this...

```java
TreeNode expenses = new CheckboxTreeNode("document", new Document("Expenses.doc", "30 KB", "Word Document"), work);

expenses.setSelectable(false);
```

and here is the resulting screenshot where the expenses doc is not selectable.
![image](https://user-images.githubusercontent.com/4399574/74933073-3c0ca580-53b1-11ea-91f3-0ceae924b492.png)

**Comment by jepsar** [comment]
Oops, sorry. I got confused by https://primefaces.github.io/primefaces/8_0/#/components/treenode , but of course I should have looked in the model!
