### ISSUE TITLE
SelectManyMenu: showCheckbox=false requires a meta key to work as a select many component

### ISSUE THREAD

**Issue by andrewtobilko** [primefaces/primefaces#5611]
Hi guys! It's my third issue on this component, and it's an improvement request rather than a bug.

## 1) Environment
- PrimeFaces version: 8.0RC

## 2) Expected behavior

As the description from the showcase goes

> `SelectManyMenu` is used to choose multiple items from a list.

Being a simple user, I click on the item, it's selected, click again on it - it's unselected. I don't know what meta keys are, and how to use them. It's a select MANY component, several items should be selected by simple clicks rather than fancy combinations (RMC + command) unknown to the experienced.  

It would be great to achieve the same behaviour as a component with `showCheckbox="true"` has. For the table widget, you have `rowSelectMode`, and `rowSelectMode="add"` (`"new"` as default) is what I am describing. Similarly, `selectMode` would be helpful here (with `"add"` as default).

## 3) Actual behaviour

It behaves as a select one component unless you know the trick. You can't select more than one element by simply clicking.

## 4) Steps to reproduce

1. Create a widget.
2. Click on an item.
3. Click on another item. The previous item is deselected. The only selected is the one you just clicked.

## 5) Sample XHTML

      <p:selectManyMenu id="basic">
            <f:selectItem itemLabel="Option 1" itemValue="1" />
            <f:selectItem itemLabel="Option 2" itemValue="2" />
            <f:selectItem itemLabel="Option 3" itemValue="3" />
        </p:selectManyMenu>

**Comment by melloware** [comment]
Here is a reproducer which fixes your problem and #5604 
[pf-5611.zip](https://github.com/primefaces/primefaces/files/4236081/pf-5611.zip)

Just run "mvn clean jetty:run" and navigate to http://localhost:8080/primefaces-test/test.xhtml to try it out.

The values are selected on single click and #5604 is fixed by calling 'change' event even when a single item is clicked.

The trick is I overrode the JS file myself using test.js to include this prototype override and forced `metakey=true;`

```javascript
PrimeFaces.widget.SelectManyMenu.prototype.bindEvents = function() {
    var $this = this;

    if (!this.cfg.disabled) {
        this.items.on('click.selectListbox', function(e) {
            //stop propagation
            if ($this.checkboxClick) {
                $this.checkboxClick = false;
                return;
            }

            var item = $(this),
                selectedItems = $this.items.filter('.ui-state-highlight'),
                metaKey = true;

            if (!e.shiftKey) {
                if (!metaKey && !$this.cfg.showCheckbox) {
                    $this.unselectAll();
                }

                if ((metaKey || $this.cfg.showCheckbox) && item.hasClass('ui-state-highlight')) {
                    $this.unselectItem(item);
                } else {
                    $this.selectItem(item);
                    $this.cursorItem = item;
                }
            } else {
                //range selection
                if ($this.cursorItem) {
                    $this.unselectAll();

                    var currentItemIndex = item.index(),
                        cursorItemIndex = $this.cursorItem.index(),
                        startIndex = (currentItemIndex > cursorItemIndex) ? cursorItemIndex : currentItemIndex,
                        endIndex = (currentItemIndex > cursorItemIndex) ? (currentItemIndex + 1) : (cursorItemIndex + 1);

                    for (var i = startIndex; i < endIndex; i++) {
                        var it = $this.allItems.eq(i);

                        if (it.is(':visible') && !it.hasClass('ui-state-disabled')) {
                            $this.selectItem(it);
                        }
                    }
                } else {
                    $this.selectItem(item);
                    $this.cursorItem = item;
                }
            }

            $this.input.trigger('change');
            $this.input.trigger('click');
            PrimeFaces.clearSelection();
            e.preventDefault();
        });

        if (this.cfg.showCheckbox) {
            this.checkboxes = this.jq.find('.ui-selectlistbox-item:not(.ui-state-disabled) div.ui-chkbox > div.ui-chkbox-box');

            this.checkboxes.on('mouseover.selectManyMenu', function(e) {
                    var chkbox = $(this);

                    if (!chkbox.hasClass('ui-state-active'))
                        chkbox.addClass('ui-state-hover');
                })
                .on('mouseout.selectManyMenu', function(e) {
                    $(this).removeClass('ui-state-hover');
                })
                .on('click.selectManyMenu', function(e) {
                    $this.checkboxClick = true;

                    var item = $(this).closest('.ui-selectlistbox-item');
                    if (item.hasClass('ui-state-highlight'))
                        $this.unselectItem(item);
                    else
                        $this.selectItem(item);

                    $this.input.trigger('change');
                });
        }
    }
};
```
