### ISSUE TITLE
DataTable: Initial multi-column sorting using SortMeta doesn't highlight column headers

### ISSUE THREAD

**Issue by kawoolutions** [primefaces/primefaces#5614]
There's a forum conversation for this issue: https://forum.primefaces.org/viewtopic.php?f=3&t=61170

There's also a fork to a PF test case detailing the problem at https://github.com/kawoolutions/primefaces-test

Note the `multisort` dirs under Java and webapp dirs, for beans + XHTML respectively.

## 1) Environment
- PrimeFaces version: 8.0.RC3
- Does it work on the newest released PrimeFaces version? Version? No. 8.0.RC3
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: Any
- Affected browsers: Firefox (others untested)

## 2) Expected behavior

Usually the given SortMeta columns for a 

```
<p:dataTable ...
                     sortBy="#{multiSortView.getInitialSortMetas()}"
                     sortMode="multiple">
```
shall be highlighted with `ui-state-active`, which doesn't seem to happen.

## 3) Actual behavior

No highlighting is present.

## 4) Steps to reproduce

Just call the page multisort.xhtml as in the test case, the initial table view suffices to see the effects.

## 5) Sample XHTML

https://github.com/kawoolutions/primefaces-test/tree/master/src/main/webapp/multisort

## 6) Sample bean

See 3 files here: https://github.com/kawoolutions/primefaces-test/tree/master/src/main/java/org/primefaces/test/multisort

**Comment by melloware** [comment]
@tandraschko I have verified this with their reproducer its definitely not picking up the SortMeta.

**Comment by tandraschko** [comment]
i don't think i can work on it, i don't have much time until i moved to my new home :D

**Comment by tandraschko** [comment]
TBH: i can reproduce it but i think it will be fixed during: https://github.com/primefaces/primefaces/issues/5438

Please try to use the sortMeta attribute instead sortBy

**Comment by melloware** [comment]
Fixed reproducer: [pf-5614.zip](https://github.com/primefaces/primefaces/files/4255775/pf-5614.zip)

@tandraschko You are correct. I just updated the reproducer here to use sortMeta and it is working fine.

**Comment by kawoolutions** [comment]
I can confirm that this is working now.

@melloware : your example uses `HashMap`, but you might want to update it with a `LinkedHashMap`, because otherwise the order of the rows of the rendered table is incorrect, because a plain `HashMap` doesn't keep the insertion order.

Why did it have to become a map anyway?

**Comment by melloware** [comment]
@kawoolutions It was made a Map if you read this very long thread 

https://github.com/primefaces/primefaces/issues/30

See @Rapster comment starting here... https://github.com/primefaces/primefaces/issues/30#issuecomment-562208798

**Comment by Rapster** [comment]
In my comment I'm talking about `LazyDataModel#load` methods and not `DataTable#filterMeta`

**Comment by melloware** [comment]
Yes but this led to @tandraschko refactoring to make both FilterMeta and SortMeta maps and make it easier for quick retrieval instead of looping over the list.

Rapster your comment is this..

Before:

`FilterMeta filter = filters.get("yearFrom")`

Now:

```
FilterMeta filter = filters.stream()
                .filter(f -> f.getFilterField().equals("yearFrom"))
                .findFirst()
                .orElse(null);
```
@kawoolutions Is asking why was filterMeta switched to a Map everywhere.

**Comment by Rapster** [comment]
> Yes but this led to @tandraschko refactoring to make both FilterMeta and SortMeta maps and make it easier for quick retrieval instead of looping over the list.

I don't know if it "led to" this decision, probably, but having a map in `LazyDataModel#load` was definitely better. See #5433.

Does `DataTable#filterMeta` should expect a Map as an input? I don't think so. It's probably something that will change in 9.0
