### ISSUE TITLE
ImageCropper: JS error when cropping image

### ISSUE THREAD

**Issue by ZiupeX** [primefaces/primefaces#5616]
When area for croop image is extended then in console.log there is js error

![image](https://user-images.githubusercontent.com/45762682/75091764-39f14500-5571-11ea-9211-9ead4d86c850.png)

**Image size**: 1,33 MB
**Image resolution**: 5472 x 3684
**p:imageCrooper settings**:

![image](https://user-images.githubusercontent.com/45762682/75091797-8f2d5680-5571-11ea-9cd2-158fe6e9476b.png)

Similary situation is on main primefaces size:

![image](https://user-images.githubusercontent.com/45762682/75091814-c00d8b80-5571-11ea-8e76-016cc6ca69fb.png)

**Comment by melloware** [comment]
Can you create a small reproducer using the Test project?  I can't reproduce it using the Showcase?
https://github.com/primefaces/primefaces-test

Or a better explanation on how to reproduce?

**Comment by ZiupeX** [comment]
1. open google chrome
1. enter https://www.primefaces.org/showcase/ui/multimedia/cropper.xhtml
2. open console.log
3. hover over crooper
4. scroll mouse whell out to focus out
5. see on the console log

**Comment by melloware** [comment]
Ahh thank you I see it now!  Scroll Mouse Wheel is the key.

**Comment by melloware** [comment]
OK Cropper.js https://github.com/fengyuanchen/cropperjs

Has a property "zoomOnWheel" which I think I should disable.

> zoomOnWheel
> Type: Boolean
> Default: true
> Enable to zoom the image by wheeling mouse.

**Comment by ZiupeX** [comment]
But the problem is not only with zoom of box where image is crooped. When you create simple ImageCrooper and you start crooping custom big image for example with resolution 2400 x 1800

lets take it below image:
https://media.wired.com/photos/5ba158545cee1848e576bc00/master/pass/ferrari_monza_1_sp2.jpg

you get the same error. You need to strecht the crooping area to fill all image and then you will see error on console log.

![image](https://user-images.githubusercontent.com/45762682/75093853-ed643480-5585-11ea-8914-c9ced9d68a0c.png)


The bug is happen on primefaces 8.0 version at version 7.0 crooping is working ok. But there different javascript version of crooping images

**Comment by melloware** [comment]
OK let me investigate.  I think the error is here getting in an infinite loop.

https://github.com/primefaces/primefaces/blob/83229b193fa19e24f98aa827c62b1fa8ccd885a4/src/main/resources/META-INF/resources/primefaces/imagecropper/2-imagecropper.js#L64-L86

**Comment by melloware** [comment]
@ZiupeX try this.  Add this JS to your page and see if it fixes all your issues.

```javascript
PrimeFaces.widget.ImageCropper.prototype.onCrop = function (event) {
        if (this.cropping) {
            return;
        }
        
        var width = event.detail.width;
        var height = event.detail.height;

        // constrain the box if necessary
        if (width < this.cfg.minCropBoxWidth
                || height < this.cfg.minCropBoxHeight
                || width > this.cfg.maxCropBoxWidth
                || height > this.cfg.maxCropBoxHeight) {

            width = Math.max(this.cfg.minCropBoxWidth, Math.min(this.cfg.maxCropBoxWidth, width));
            height = Math.max(this.cfg.minCropBoxHeight, Math.min(this.cfg.maxCropBoxHeight, height));

            this.cropping = true;
            this.cropper.setCropBoxData({
                width : width,
                height : height
            });
        }

        // set the new box coordinates
        var cropCoords = event.detail.x + "_" + event.detail.y + "_" + width + "_" + height;
        this.jqCoords.val(cropCoords);
        this.cropping = false;
    };
```

**Comment by ZiupeX** [comment]
@melloware 
the console log error (Maximum call stack size exceeded) no longer shows. But the problem is still not fixed. 

Please try to reproduce with the following:

image 
https://media.wired.com/photos/5ba158545cee1848e576bc00/master/pass/ferrari_monza_1_sp2.jpg

![image](https://user-images.githubusercontent.com/45762682/75166512-3eaa2a80-5724-11ea-944b-ca0674c3328b.png)

![image](https://user-images.githubusercontent.com/45762682/75166529-479afc00-5724-11ea-83c3-eaedfb1632d5.png)

**Comment by melloware** [comment]
I am using the Showcase with ...
```xml
<p:imageCropper value="#{cropperView.croppedImage}"
 image="/resources/demo/images/nature/nature6.jpg" />
```
No initial coords, min or max set like you have and I can't reproduce it.  So you are doing something different than I am doing.  Can you give me EXACT steps.

**Comment by ZiupeX** [comment]
I`m not sure what resolution of image you use  **nature6.jpg**. I working with big images where resolution is big. My ferrari image is in resolution 2400 x 1800 but it also happen with other images:

![image](https://user-images.githubusercontent.com/45762682/75168060-93e73b80-5726-11ea-83f1-f4da322e5cc5.png)

**Comment by ZiupeX** [comment]
here is my chrome version (newest) but I tested already on opera and there is the same

![image](https://user-images.githubusercontent.com/45762682/75168261-e32d6c00-5726-11ea-97bf-314e839c3ad1.png)

**Comment by melloware** [comment]
OK let me try with your large image.  Resolution must have something to do with it.

**Comment by ZiupeX** [comment]
if you using this image:

https://www.primefaces.org/showcase/resources/demo/images/nature/nature6.jpg

resolution is only 500 x 313. Error not happend on that small image. Try again with big resolution. 

![image](https://user-images.githubusercontent.com/45762682/75168939-fab92480-5727-11ea-85a8-50ee5155ca88.png)

**Comment by melloware** [comment]
OK will do. And this time I will create a runnable reproducer so we can hand each other a running project back and forth.

**Comment by melloware** [comment]
OK attached is a reproducer: 
[pf-5616.zip](https://github.com/primefaces/primefaces/files/4246764/pf-5616.zip)



Unzip it and run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by melloware** [comment]
OK I think I figured it out...

```javascript
        var imageWidth = this.image.width(),
            imageHeight = this.image.height();
```
Just gives you the dimensions of what is displayed on the browser screen like 1881 x 1400

```javascript
        var imageWidth = this.image[0].naturalWidth,
            imageHeight = this.image[0].naturalHeight;
```
Give you the real size of the image like 2400 x 1800.

**Comment by melloware** [comment]
@ZiupeX let me know if you can test out my tester above today so I can merge this fix in before the 8.0 release.

**Comment by ZiupeX** [comment]
ok let me test it

**Comment by ZiupeX** [comment]
@melloware now it fixed :) everything is okey I tested on multiple images and it seems is not okey. But last thing that you cna improve in JS script. Just remove duplication of event call

![image](https://user-images.githubusercontent.com/45762682/75264911-6a92e200-57f0-11ea-8107-e4518b00b902.png)

**Comment by ZiupeX** [comment]
btw. when release 8.0 will be released??

**Comment by melloware** [comment]
8.0 should be soon. And I already made your fixes your can see my final PR changes here: https://github.com/primefaces/primefaces/pull/5617/files
