### ISSUE TITLE
DatePicker: ui-datepicker-next skips next month

### ISSUE THREAD

**Issue by DilyanaN** [primefaces/primefaces#5618]
## 1) Environment
- PrimeFaces version: 7.0.11
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version:
- Affected browsers: Chrome, IE, Firefox...

## 2) Expected behavior
On click on "Next month" (after submit), the next month is displayed, independent on the selected date.

## 3) Actual behavior
If a date is selected, which is *not* existent in the next month, by selecting next month via ui-datepicker-next (after submit) the next month is skipped and the month after is displayed.

## 4) Steps to reproduce
- Choose 31. January 2020
- Click on "Submit"
- Click on the datePicker field
- Select next month via ui-datepicker-next
- See month *March*

## 5) Sample XHTML

```
<f:view>
  <h:body>
      <h:form>
        <div class="ui-g">

          <div class="ui-g-6">
            <p:datePicker yearNavigator="true" showIcon="true" yearRange="1900:2150" pattern="dd.MM.yyyy"/>
          </div>

          <div class="ui-g-6">
            <p:commandButton value="Submit" ajax="false"/>
          </div>

        </div>
      </h:form>

  </h:body>
</f:view>
```

**Comment by melloware** [comment]
@christophs78 can you try this with 8.0?

**Comment by christophs78** [comment]
Ok, I will look at this and #5619

**Comment by melloware** [comment]
Here is my reproducer:
[pf-5618.zip](https://github.com/primefaces/primefaces/files/4257283/pf-5618.zip)

Just run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by melloware** [comment]
OK both issues were the same exact issue see my PR.
