### ISSUE TITLE
DatePicker: ui-datepicker-prev does not show previous month on single click

### ISSUE THREAD

**Issue by DilyanaN** [primefaces/primefaces#5619]
### 1) Environment
- PrimeFaces version: 7.0.11
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version:
- Affected browsers: Chrome, IE, Firefox...
### 2) Expected behavior
On single click on ui-datepicker-prev (after submit), previous month is displayed, independent on the selected date.

### 3) Actual behavior
If a date is selected, which is not existent in the previous month, the user has to click twice on ui-datepicker-prev in order to see previous month.

### 4) Steps to reproduce
- Choose 31. March 2020
- Click on "Submit"
- Click on the datePicker field
- Select previous month via ui-datepicker-prev
- You have to click again on ui-datepicker-prev in order to see previous month

5) Sample XHTML

```
<f:view>
  <h:body>
      <h:form>
        <div class="ui-g">

          <div class="ui-g-6">
            <p:datePicker yearNavigator="true" showIcon="true" yearRange="1900:2150" pattern="dd.MM.yyyy"/>
          </div>

          <div class="ui-g-6">
            <p:commandButton value="Submit" ajax="false"/>
          </div>

        </div>
      </h:form>

  </h:body>
</f:view>
```

**Comment by melloware** [comment]
Attached is a reproducer and I could reproduce this with 8.0RC3 this time.
[pf-5619.zip](https://github.com/primefaces/primefaces/files/4257305/pf-5619.zip)
