### ISSUE TITLE
Spotlight: spinner is not completely blocked

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#5620]
## 1) Environment
- PrimeFaces version: 7.0/8.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tested with Jetty (primefaces-demo)
- Affected browsers: Tested with Firefox and Opera, probably applies to all

## 2) Expected behavior
`<p:spotlight>` should block all inputs that are not spotlighted.

## 3) Actual behavior
When a `<p:spinner>` is on a page that uses `<p:spotlight>`, the buttons of the spinner have a too high z-index, so they are not blocked.

## 4) Steps to reproduce

Just paste the XHTML shown below into primefaces-demo und load it with the browser. 

## 5) Sample XHTML

````xml
    <h:form id="theForm">
      <div><p:inputText id="txt" /></div>
      <div><p:spinner id="sp"/></div>
      <p:spotlight target="txt" active="true" />
    </h:form>
````

**Comment by melloware** [comment]
Attached is a reproducer: 
[pf-5620.zip](https://github.com/primefaces/primefaces/files/4255595/pf-5620.zip)

**Comment by melloware** [comment]
If you need this fix right now just add this JS to your page.

```javascript
PrimeFaces.widget.Spotlight.prototype.calculatePositions = function () {
	var doc = $(document),
		documentBody = $(document.body),
		offset = PrimeFaces.utils.calculateRelativeOffset(this.target),
		zindex = ++PrimeFaces.zindex;

	documentBody.children('div.ui-spotlight-top').css({
		'left': 0,
		'top': 0,
		'width': documentBody.width(),
		'height': offset.top,
		'z-index': zindex
	});

	var bottomTop = offset.top + this.target.outerHeight();
	documentBody.children('div.ui-spotlight-bottom').css({
		'left': 0,
		'top': bottomTop,
		'width': documentBody.width(),
		'height': doc.height() - bottomTop,
		'z-index': zindex
	});

	documentBody.children('div.ui-spotlight-left').css({
		'left': 0,
		'top': offset.top,
		'width': offset.left,
		'height': this.target.outerHeight(),
		'z-index': zindex
	});

	var rightLeft = offset.left + this.target.outerWidth();
	documentBody.children('div.ui-spotlight-right').css({
		'left': rightLeft,
		'top': offset.top,
		'width': documentBody.width() - rightLeft,
		'height': this.target.outerHeight(),
		'z-index': zindex
	});
};
```

**Comment by matinh** [comment]
Thx @melloware for looking into this.

The bug is not that important for us and we have another simple workaround: just increase z-index for `.ui-widget-overlay.ui-spotlight` to 110 or something like this:

````css
.ui-widget-overlay.ui-spotlight {
    z-index: 110;
}
````

**Comment by melloware** [comment]
@matinh Just be careful with your fix if you use p:poller and were to update your spinner `update="sp"` after 10 polls the z-index of the spinner would be 111 because of `++PrimeFaces.zindex`.  Just something to be aware of.
