### ISSUE TITLE
DataTableExcelExporter: DataTable.getColumnsCount() returns wrong value exporters

### ISSUE THREAD

**Issue by elab** [primefaces/primefaces#5624]
All implementations of [`DataTableExporter.exportCells()`](https://github.com/primefaces/primefaces/blob/8.0.RC3/src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java#L304), e.g. DataTableExcelExporter, do column export if it is [rendered and **exportable**](https://github.com/primefaces/primefaces/blob/8.0.RC3/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java#L117-L119).

But the [`DataTable.getColumnsCount()`](https://github.com/primefaces/primefaces/blob/8.0.RC3/src/main/java/org/primefaces/component/datatable/DataTable.java#L909) considers only columns which are [rendered](https://github.com/primefaces/primefaces/blob/8.0.RC3/src/main/java/org/primefaces/component/datatable/DataTable.java#L914) and [**visible**](https://github.com/primefaces/primefaces/blob/8.0.RC3/src/main/java/org/primefaces/component/datatable/DataTable.java#L922).

This discrepancy causes the ["autoSize" is not set for all exported columns](https://github.com/primefaces/primefaces/blob/8.0.RC3/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java#L83-L87). Namely the columns with `visible="false"` are exported but not counted, therefore "autosize" is set for fewer columns than actually exported.

PrimeFaces 8.0 RC3

----------

Use case: exporting more columns than displayed in GUI by setting `visible="false"` to those additional columns.

----------

Current workaround: set CSS style `display: none;` for the `p:column`. In this way, it formally remains "visible" and therefore gets counted in `getColumnsCount()`.

**Comment by melloware** [comment]
@elab thanks for the bug report and please review my PR.

**Comment by elab** [comment]
Thank you, @melloware !
The PR looks good to me. The logic for autoSize columns is now aligned with the logic for columns export (i.e. columns should be "rendered" and "exportable") and the `DataTable.getColumnsCount()` is not used there anymore. Not sure about the function of `applyStatelessModel()`, but it's also called for exporting, therefore the use in autosizing should be OK, too.

**Comment by melloware** [comment]
Yep I tested it and I added a new Showcase Example under the Exportable columns for XLSXSTREAM example and all is working!
