### ISSUE TITLE
Hotkey: Add support for disabling a hotkey via disabled attribute

### ISSUE THREAD

**Issue by klaros-testmanagement** [primefaces/primefaces#5625]
## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
There are many use cases where a user wants to disable hotkeys from the server side.
One example is the display of a modal dialog where it is expected that page related hotkeys are disabled.

See also discussion in: [https://forum.primefaces.org/viewtopic.php?f=3&t=61198](url)

The obvious solution is add a `disabled` attribute to the component.

I will provide a pull request for this.

Support for widget representation will be done in a different issue/pr.

## 3) Actual behavior

Support for this is missing.

**Comment by stolp** [comment]
You may use this reproducer to test the functionality.

[primefaces-test-5625.zip](https://github.com/primefaces/primefaces/files/4262824/primefaces-test-5625.zip)

**Comment by klaros-testmanagement** [comment]
@melloware 9.0, really? I desperately need support for this in 8.0 or 8.0.1 and forward.

**Comment by tandraschko** [comment]
mert may add it to 8.0.1 but 8.0 is closed for features/enhancements actually. Monday is release.

**Comment by stolp** [comment]
@mertsincan Can you please include this enhancement in 8.0.1 after the 8.0 release is done?
