### ISSUE TITLE
DatePicker: Not fully functional with OverlayPanel

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5630]
## 1) Environment
- PrimeFaces version: trunk
- Affected browsers: all

## 2) Expected behavior
`p:datepicker` (popup mode) inside `p:overlayPanel` should not close overlay panel when input field is clicked.

## 3) Actual behavior
Overlay panel is closed

## 4) Steps to reproduce
 - open overlay panel (popup of calender is opened automatically)
 - click on input field
 - overlay panel closes, date picker overlay is still visisble

## 5) Sample XHTML
```
    <p:overlayPanel>
        <p:datepicker appendTo="@(body)" />
    </p:overlayPanel>
```

**Comment by christophs78** [comment]
@fanste : Is this a new issue in 8.0 or had it been there already in 7.0? (I´ll guess it had been there already in 7.0)

**Comment by fanste** [comment]
We have a custom version of 7.x that already has this error and it is still reproducible in 8.x.

**A possible fix:**
File: 0-datepicker.js
Function: onInputClick
```
event.stopPropagation();
...
```

I can't see any negative side effects

**Comment by melloware** [comment]
@fanste do you mean something like this...
```javascript
        onInputClick: function (event) {
            event.stopPropagation();

            if (this.documentClickListener) {
                this.datepickerClick = true;
            }

            if (this.options.showOnFocus && !this.panel.is(':visible')) {
                this.showOverlay();
            }
        }
```

**Comment by fanste** [comment]
Exactly. But I'm currently a bit short on time so I can't test all possible cases :/

**Comment by melloware** [comment]
OK PR submitted.  This does seem like a safe fix.

**Comment by fanste** [comment]
Thank you

**Comment by melloware** [comment]
@fanste I am having trouble reproducing.  can you try this reproducer? 
[pf-5630.zip](https://github.com/primefaces/primefaces/files/4281208/pf-5630.zip)

Just run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by fanste** [comment]
Well.. my fault - sorry :(

My use case: Complex custom datatable filter which has its input components in the overlay panel. Due to an bug in my custom component the overlay panel was a child of the trigger component.

And even though I had removed trigger, overlay panel and calendar from the table during testing, I put the same error there - overlay panel as child element of the trigger. Just stupid...

Issue is invalid and PR should be reverted. Sorry melloware
