### ISSUE TITLE
Server requests that result in an unauthorized request (eg session timeout) should redirect to Location(aka) login

### ISSUE THREAD

**Issue by mP1** [primefaces/primefaces#5635]
This is an improvement request. The use case is for a PrimeFaces app where the session has timed out, and the user then attempt to interact again with the app. When an AJAX request eventually happens the server will reply with a 401 (Unauthorized), and result in nothing. It would be desirable if the LOCATION header in the response was used to load that page via a window.location.

A fix has been identified and a PR submitted: https://github.com/primefaces/primefaces/pull/5634

## 1) Environment
- PrimeFaces version: v 7.0

- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)

The same block in core-ajax.js remains unchanged so it is expected the same behaviour results.

- Application server + version:
JBOSS EAP 7.1.6.GA

- Affected browsers: ALL

## 2) Expected behavior
This is a feature (improvement) request. A better solution would be to honour a 401 (Unauthorized) response and redirect the browser window location to this header.

## 3) Actual behavior
None. 401 Location is ignored.

## 4) Steps to reproduce
Interact with any app so that AJAX requests are made to the server, after waiting for the session to timeout.

## 5) Sample XHTML
N/A

## 6) Sample bean
N/A

**Comment by tandraschko** [comment]
Thanks for the PR!

**Comment by SimonePadovan** [comment]
Hi, how can i set the LOCATION header in the response ? thanks
