### ISSUE TITLE
StaticMessage: styleClass is not added by renderer

### ISSUE THREAD

**Issue by naofireblade** [primefaces/primefaces#5636]
The staticMessage renderer does not add the styleClass.

## 1) Environment
- PrimeFaces version: 8.0.RC3
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Wildfly 14.0.1
- Affected browsers: All

## 2) Expected behavior

Adding styleClass to the component should add and extra class in the rendered component.

## 3) Actual behavior

Extra class is missing in the rendered component.

## 4) Steps to reproduce

Add a p:staticMessage component with styleClass attribute.

## 5) Sample XHTML

```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:p="http://primefaces.org/ui">
   <body>
      <p:staticMessage detail="Hello there!" severity="warn" styleClass="large"/>
   </body>
</html>
```

## 6) Sample bean

not necessary

**Comment by tandraschko** [comment]
thanks for the PR!
