### ISSUE TITLE
DatePicker: ShowTime/ShowSeconds based on pattern

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#5638]
There are some further issues/bugs with the p:datePicker component.

Issue 1) It should not require to explicitly set the attribute showTime in order to be usually for LocalDateTime. Without this attribute the validation does not pass. Event showTime="false" does not work.

Issue 2) When the attribute pattern is NOT fully applied in case of LocalDateTime. For instance, pattern="yyyy-MM-dd" still show the time although I do not want to show it as expressed by the pattern. In general, other patterns like pattern="yyyy-MM-dd HH" are "ignored".

Issue 3) It is not possible to set the seconds (and smaller time units) in case LocalDateTime.

## 1) Environment
- PrimeFaces version: 8.0 RC3
- Affected browsers: All

## 2) Expected behavior

Issue 1) When p:datePicker is used for a LocalDateTime it should not be required to set showTime=true". The pattern should define how the date(Time)Picker should look like.

Issue 2) When p:datePicker is used for a LocalDateTime with the "yyyy-MM-dd" it should be accepted and the time part set implicitly to 00:00:00.000. Accordingly, When p:datePicker is used for a LocalDateTime with the "yyyy-MM-dd HH" it should be accepted and the time part set implicitly to HH:00:00.000. of course, in this case, the time selector should only show the hours part.

Issue 3)  When p:datePicker is used for a LocalDateTime with the "yyyy-MM-dd HH:mm:ss", the time selector should have a seconds selector.

**Comment by melloware** [comment]
@christophs78 care to look at this one?

**Comment by christophs78** [comment]
Do we have a new 8.0-Final-Releasedate? (Thought it was yesterday.)

IMO we should try to fix issue 3) for 8.0. I´ll try to look into this later this day, but not sure because im busy on my day-job.

Issues 1) and 2) are future work for 9.0. It´s not easy to keep backward-compatibililty with java.util.Date and life with some not optimal design-decisions built into the initial datepicker-design.

**Comment by christophs78** [comment]
@tuerker: Issue 3 - did you try showSeconds="true"?

`<p:datePicker id="time5" value="#{calendarJava8View.dateTime5}" showTime="true" showSeconds="true"/>`

**Comment by tuerker** [comment]
no. i quickly tried. this actually does the job. thanks.

anyway, it would be great if the showTime and showSeconds attributes could be eliminated in future releases and the pattern alone decides what is shown.
