### ISSUE TITLE
TreeTable: CellEdit event not working for dynamic columns

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#5639]
I retested https://github.com/primefaces/primefaces/issues/4724.  successfully with 8.0-SNAPSHOT for `p:dataTable`. However, `p:treeTable` does not work. Here is the sample for p:treeTable:

## Bean3.java

``` java
@SessionScoped @Named
public class Bean3 implements Serializable {
  private static final long serialVersionUID = 1L;

  public class Test implements Serializable { // Content class of TreeNodes
    private static final long serialVersionUID = 1L;	
    public String value;
    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }

    public int index;
    public int getIndex() { return index; }
    public void setIndex(int index) { this.index = index; }
		
    public Test(String value, int index) { this.value=value; this.index=index; }
  }
	
  TreeNode root;
  public TreeNode getRoot() { return root; }
  public void setRoot(TreeNode root) { this.root = root; }

  public void createTreeNodes() { 
    root=new DefaultTreeNode(new Test("Root", 0), null);
	new DefaultTreeNode(new Test("One", 1), root);
	new DefaultTreeNode(new Test("Two", 2), root);
  }
  @PostConstruct public void init() { createTreeNodes(); }
	
  public void onCellEdit(CellEditEvent<?> e) { info("cellEdit", e); }
  public void onCellEditInit(CellEditEvent<?> e) { info("cellEditInit", e); }
  public void onCellEditCancel(CellEditEvent<?> e) { info("cellEditCancel", e); }
	
  public static void info(String method, CellEditEvent<?> e) {
    String message=String.format("old=%s, new=%s", e.getOldValue(), e.getNewValue());
    FacesContext.getCurrentInstance().addMessage(null, 
      new FacesMessage(FacesMessage.SEVERITY_INFO, method+":", message));
  }
}
```
## treeTable.xhtml
``` xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
   xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui" >
<h:head />
<h:body>
  <h:form id="form">
    <p:growl id="msgs" showDetail="true"/>
    <p:treeTable value="#{bean3.root}" var="var" editMode="cell" editable="true" tableStyle="width:auto">
      <p:ajax event="cellEditInit" listener="#{bean3.onCellEditInit}" update=":form:msgs"/>
      <p:ajax event="cellEdit" listener="#{bean3.onCellEdit}"  update=":form:msgs"/>
      <p:columns var="property" value="#{['value','index']}"  headerText ="#{property}">
        <p:cellEditor>
          <f:facet name="output"><h:outputText value="#{var[property]}" /></f:facet>
          <f:facet name="input"><p:inputText value="#{var[property]}" /></f:facet>
        </p:cellEditor>
      </p:columns>
    </p:treeTable>
  </h:form>
</h:body>
</html>
```
## Reproduce
- Click in the top/left cell and change the value. It will not change (bug).
  - The message shows `cellEdit: old=One, new=One`, but `new` should be changed.
  - Also, cellEditInit is not fired for treeTable (but for dataTable)
- Hovever, in the second row, it works

**Comment by melloware** [comment]
Attached is a reproducer for the issue:
[pf-5639.zip](https://github.com/primefaces/primefaces/files/4287328/pf-5639.zip)

**Comment by mdzaebel** [comment]
@melloware Thanks for your immediate work and the reproduction zip. I'd whish I could help in any way too. As #4724 was targeted to 8.0, will this issue also be targeted to 8.0? I see, you're already solving the cellEditInit problem on TreeTable? This is great! Are you planing to solve the cellEdit problem too or is it already solved with your last commit? TreeTable is an important component that contributes significantly to Primefaces. I think it's worth to have it editable with p:colums. As stated a year before, c:forEach is no solution in my case an I had to stop the development of my project due to this defect.

**Comment by melloware** [comment]
So I fixed the treetable CellEditInit event issue.  But still working on the CellEdit event. It is so werid it only happens on the first cell but row 2 it works fine.

**Comment by mdzaebel** [comment]
I tested with multiple rows and identified, that the problem exists on **all** rows but the **last** one. Only the last row shows the new value correctly. Even, if you introduce indented layers, only the last (possibly indented) row works.

**Comment by melloware** [comment]
OK I merged the CellEditInit event fix but reopened this ticket since the CellEdit issue is not resolved.

**Comment by mdzaebel** [comment]
I verified that with your last commit, TreeTable now fires the cellEditInit event correctly. Good luck for CellEdit, if you have the time.

**Comment by tandraschko** [comment]
@melloware will you further work on it?

**Comment by melloware** [comment]
@tandraschko I updated this ticket. CellEdit works fine for regular TreeTable columns like in our Showcase but with Dynamic Columns it does not work.

```xml
<p:columns var="property" value="#{['value','index']}"  headerText ="#{property}">
					<p:cellEditor>
						<f:facet name="output">
							<h:outputText value="#{var[property]}" />
						</f:facet>
						<f:facet name="input">
							<p:inputText value="#{var[property]}" />
						</f:facet>
					</p:cellEditor>
</p:columns>
```

I think its similar to these issue:
https://github.com/primefaces/primefaces/issues/5117

The fix for https://github.com/primefaces/primefaces/pull/5592 works for DataTable but does not work for TreeTable even though it uses the same CellEditEvent code. So I am stumped on this one?

**Comment by tandraschko** [comment]
@melloware can you retest again?

**Comment by melloware** [comment]
Yep!

**Comment by melloware** [comment]
@tandraschko This issue is still happening with the reproducer.

**Comment by tandraschko** [comment]
@melloware you have to press "Process and Refresh" before normal "Refresh", otherwise the changes are not posted via AJAX. Or attach AJAX to p:columnToggler.

EDIT: wrong issue, sorry. WIll check it maybe tomorrow.

**Comment by tandraschko** [comment]
still not fixed by my changes. If anyone would like to have this fixed, i need more debugging infos what wents wrong in the PF internals.
