### ISSUE TITLE
Datatable: Footer misaligned with grouped columns in scrollable datatable

### ISSUE THREAD

**Issue by lapetro** [primefaces/primefaces#564]
Datatable with scrolling and with colspan and rowspan in footer results footer columns that are not correctly aligned with the body columns of the table. The results are browser and browser size dependent. In some cases the result is OK.

![pic1](https://cloud.githubusercontent.com/assets/13519607/8903841/19446f30-345b-11e5-8874-2262657bbb39.jpg)

**Comment by melloware** [comment]
We need a reproducible example test case or at least the XHTML code you used to produce the above.  Closing for now unless this is provided.
