### ISSUE TITLE
Ajax Update/Process: Allow non-existent Ids

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5640]
in very dynamic views its (sometimes) easier to update all possible element, also those which are currently NOT included in the current state
if you do this with p:ajax, it throws a ComponentNotFoundException

PrimeFaces.current().ajax(...) just logs ComponentNotFoundException instead of throwing a exception

I should add a attribute to p:ajax - maybe "allowNonExistentComponent" or similar

**Comment by tandraschko** [comment]
i will call it "ignoreComponentNotFound"

**Comment by tandraschko** [comment]
commited something
can someone review and do a short test?

**Comment by melloware** [comment]
I just reviewed. This change looks excellent!

**Comment by tandraschko** [comment]
Thanks!
