### ISSUE TITLE
Docu: make sure up-to-date versions are delivered to the client

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5645]
Due to this (old versions) of the documentation are loaded from "Cache Storage".

![grafik](https://user-images.githubusercontent.com/10461942/75908039-b0335880-5e49-11ea-8ba8-5cbb764c7136.png)
![grafik](https://user-images.githubusercontent.com/10461942/75908071-bde8de00-5e49-11ea-9e86-19b1eb3147a9.png)

When we update documentation users still have the old versions in their "Cache Storage". Only pushing Ctrl + F5 (or cleanup all Browser-Cache) helps.

When we look at https://docsify.js.org/#/?id=docsify itself does not use a serviceworker.

There´s a docsify-issue: https://github.com/docsifyjs/docsify/issues/190
It say´s we should remove the serviceworker because it´s not needed anymore.

**Comment by melloware** [comment]
I think that serviceWorker was done because of this ticket: https://github.com/primefaces/primefaces/issues/4713

**Comment by christophs78** [comment]
Makes sense. But we should find a way to get updated docu reliable to our users.
Maybe modify the service worker so it only uses Cache Storage when no network-connection is available or ....

**Comment by melloware** [comment]
I am open to suggestions!

**Comment by christophs78** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine
Have to think where we are able to apply this to the serviceworker.

**Comment by christophs78** [comment]
I will try to debug the Serviceworker. There seems to be some code which tries to update Cache Storage.

**Comment by christophs78** [comment]
Loading docu the first time (after past visit) --> you still see the old docu. (Because loaded from Cache Storage.)
Second visit --> we see the updated docu. (Because as part of our first visit the Cache Storage was updated.)

**Comment by melloware** [comment]
Looks like this is a common issue:
https://stackoverflow.com/questions/41903097/how-to-force-service-worker-to-update

**Comment by christophs78** [comment]
The stackoverflow-article is related to updating the ServiceWorker-JS itself.

Our issue is related to following code in sw.js:
```
    // Call respondWith() with whatever we get first.
    // If the fetch fails (e.g disconnected), wait for the cache.
    // If there’s nothing in cache, wait for the fetch.
    // If neither yields a response, return offline pages.
    event.respondWith(
      Promise.race([fetched.catch(_ => cached), cached])
        .then(resp => resp || fetched)
        .catch(_ => { /* eat any errors */ })
    )
```

Loading the content from Cache Storage almost always is a few milliseconds faster than loading it from the remote server. (So loading from Cache Storage wins.) I will try something like adding a setTimeout with 500ms to the cached-promise. (Inspired by https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race)
So the actual version fetched from the remote server should „win“ in most times.

I need to check this idea against some kind of local webserver.
