### ISSUE TITLE
Themes: Progress bar does not display label

### ISSUE THREAD

**Issue by ozziej** [primefaces/primefaces#5648]
p:progressBar css wrong, hides the label

## 1) Environment
- PrimeFaces version: 7
- Issue shows up on https://www.primefaces.org/showcase (running 8.0)
- Application server + version: TomEE 1.8 (tomcat 9.0) unrelated as also occurs in Wildfly (any version)
- Affected browsers: All

## 2) Expected behavior
By default the label should show 
...

## 3) Actual behavior
Label will NEVER show. CSS for all luna and nova override the display attribute with !important which prevents the user CSS from displaying it. Omega and Aristo themes do NOT have this issue.

The display none attribute should be changed from 

```css
body .ui-progressbar .ui-progressbar-label{
...
display:none!important;
}
```

to
```css
body .ui-progressbar .ui-progressbar-label{
...
display:block;
}
```

to allow user to override.
..

## 4) Steps to reproduce
any incantation of <p:progressBar> will NOT show the label.
(check https://www.primefaces.org/showcase/ui/misc/progressBar.xhtml for complete example)
.. 

## 5) Sample XHTML
```xml
<p:progressBar style="margin-bottom: 8px; height: 20px;" id="progressBar" value="#{controller.percentComplete}" labelTemplate="{value} %"/>
```

## 6) Sample bean
```java
public int getPercentComplete() {
    return 50;
}
```

![Screenshot 2020-03-06 at 10 32 45](https://user-images.githubusercontent.com/13061222/76066518-73c14300-5f96-11ea-878a-9b04bcc13cf1.png)
![Screenshot 2020-03-06 at 10 32 51](https://user-images.githubusercontent.com/13061222/76066527-77ed6080-5f96-11ea-8149-a6893ffb4a48.png)

..

**Comment by tandraschko** [comment]
Thats a decision by the theme to show or hide it. Seems like some newer themes hides it by design.

**Comment by ozziej** [comment]
> Thats a decision by the theme to show or hide it. Seems like some newer themes hides it by design.

Okay, I get that, however, the theme SHOULD allow you to override this, however, if they use the !important tag, then you CANNOT override this. I disagree with that. There needs to be some flexibility.

**Comment by tandraschko** [comment]
@mertsincan can we remove the !important here?

**Comment by mertsincan** [comment]
Hi @ozziej and @tandraschko,

This is by design on Nova and Luna. We can not remove !important because label has an inline style to show text. We need to change setValue method in progressbar widget to remove !important.
```
  setValue: function(value) {
        if(value >= 0 && value<=100) {
            if(value == 0) {
                this.jqValue.hide().css('width', '0%').removeClass('ui-corner-right');

                this.jqLabel.hide();
            }
            else {
                this.jqValue.show().animate({
                    'width': value + '%'
                }, this.cfg.animationDuration, 'easeInOutCirc');

                if(this.cfg.labelTemplate) {
                    var formattedLabel = this.cfg.labelTemplate.replace(/{value}/gi, value);
                    this.jqLabel.text(formattedLabel).show();
                }
            }

            this.value = value;
            this.jq.attr('aria-valuenow', value);
        }
    },
```
I agree with Thomas.
```
/* Always show label */
body .ui-progressbar div.ui-progressbar-label {
   display: block !important;
}

OR

/* Always show label except '0' value */
body .ui-progressbar .ui-progressbar-value[style*="width"] + div.ui-progressbar-label {
     display: block !important;
}
```
This is the design team's decision.

Thanks a lot for your understanding!
Best Regards,
