### ISSUE TITLE
DataTable: Pagination combined with first not correct

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5649]
## 1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior
`<p:dataTable pagination="true" rows="20" first="105" ...>` should be the 6th item on the 6th page. 

## 3) Actual behavior
The 6th page is opened but the item is at the very top of that page. But if you go to another page and than back to page 6 again, the item is at the 6th position and not at 0 anymore.

![grafik](https://user-images.githubusercontent.com/3531183/76068070-c39d0b80-5f90-11ea-80c3-c6d0c7bca7c7.png)

What do you think. Should this be changed?

**Comment by tandraschko** [comment]
you know, issues without samples are invalid :P
Can you replicate it in the showcase?

**Comment by fanste** [comment]
Well, the sample (kind of..) is provided in the **expected behavior** section :D

But here you go: https://github.com/fanste/primefaces-test/tree/test-5649

**Comment by kukel** [comment]
I would not call this a defect per say. Keeping this 'working' would require passing a 'remainer' to and from the client (so it keeps working using short requestscoped backing beans) and take it into account in calculating a 'new' first. Currently page and pagesize are used for this. 'Improvement' is a better tag, but when a 'lazyDataModel' is used. this can be 'fixed' in there. Not something the datatable should support by definition. Lots of more important things to improve imo.

**Comment by tandraschko** [comment]
sample not available anymore
please create a issue with reproducer if its still a problem in current github master

**Comment by fanste** [comment]
I have no idea, why the reproducer was not available anymore...

I pushed it again to the [same address](https://github.com/fanste/primefaces-test/tree/test-5649) and upgraded it to `-SNAPSHOT` available on Jitpack. The behavior of the datatable is still wrong.

Open the reproducer, page 6 will be shown with item `105` at the 1st row - but the item should be the 6th row. Switch to page 1 and back to page 6 and everything will be as expected.

**Comment by tandraschko** [comment]
Could you create new integrationt test for it and work on a PR?

**Comment by melloware** [comment]
Updated reproducer still an issue in 13.0.3:

[pf-5649.zip](https://github.com/primefaces/primefaces/files/13444133/pf-5649.zip)

**Comment by Rapster** [comment]
The issue here is that you set 105 (which is not divisible by 20) as first when it should be 100 at best (or something divisible by 20). DataTable is lenient here, while it could actually throw an exception as it's not quite correct, but since it's a old issue and no one else complain about it, I'm right now more in favor to do nothing about it, or log at best

**Comment by melloware** [comment]
I vote for lets log it in Development mode so its a warning that its an invalid `first` value?

**Comment by melloware** [comment]
I see its this code.

```java
else if ("page".equals(eventName) || "virtualScroll".equals(eventName) || "liveScroll".equals(eventName)) {
                int rows = getRowsToRender();
                int first = Integer.parseInt(params.get(clientId + "_first"));
                int page = rows > 0 ? (first / rows) : 0;

                wrapperEvent = new PageEvent(this, behaviorEvent.getBehavior(), page);
            }
```
