### ISSUE TITLE
DatePicker: Range not set when specified in abstract class

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#5656]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Payara 5.181
- Affected browsers: Firefox, Chrome, ...

## 2) Expected behavior

For multiple statistics views I have an abstract base class that handles the valid year range, the maximum date and the selected date range.
When a users selects a date range, then the setter should be called after selection of the start date **and after selection of the end date**.

## 3) Actual behavior

When a users selects a date range, then the setter is **only called after the selection of the start date**.

## 4) Steps to reproduce

See sample view and bean.

## 5) Sample XHTML

```
<p:datePicker id="dateDayRange"
              maxdate="#{testAbstractBacking.dayRangeMax}"
              monthNavigator="true"
              readonlyInput="true"
              selectionMode="range"
              size="16"
              showButtonBar="true"
              showIcon="true"
              value="#{testAbstractBacking.dayRange}"
              yearNavigator="true" yearRange="#{testAbstractBacking.yearRange}">
    <p:ajax event="dateSelect" />
</p:datePicker>
```

## 6) Sample bean

```
public abstract class AbstractTest
        implements Serializable {

    private String yearRange;

    private LocalDate dayRangeMax;

    private List<LocalDate> dayRange;

    @PostConstruct
    public void init() {
        // initialize the default year range
        final LocalDate localDateNow = LocalDate.now();
        yearRange = localDateNow.minusYears(10).getYear() + ":" + localDateNow.getYear();

        // set the current date as maximum date
        dayRangeMax = LocalDate.now();
    }

    public String getYearRange() {
        return yearRange;
    }

    public LocalDate getDayRangeMax() {
        return dayRangeMax;
    }

    public List<LocalDate> getDayRange() {
        return dayRange;
    }

    public void setDayRange(List<LocalDate> dayRange) {
        this.dayRange = dayRange;

        System.out.println("AbstractTest.setDayRange() -> " + dayRange);
    }

}

@Named
@ViewScoped
public class TestAbstractBacking
        extends AbstractTest {

    @Override
    public void setDayRange(List<LocalDate> dayRange) {
        System.out.println("TestAbstractBacking.setDayRange()");

        super.setDayRange(dayRange);
    }

}
```

**Comment by melloware** [comment]
Are you sure the Abstract Class has anything to do with it?  Does it work fine if it is just a normal bean with no abstract class with proper setters and getters?

Or is the real issue that the DateSelect event is not being called when End Date is selected?

**Comment by ltlBeBoy** [comment]
> Are you sure the Abstract Class has anything to do with it?

Yes, it works without an abstract class.

And I found the reason:
[org.primefaces.component.calendar.BaseCalendarRenderer](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java)`#resolveDateType(FacesContext, UICalendar)` calls [org.primefaces.util.LangUtils](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/util/LangUtils.java)`#getUnproxiedClass(Class)` which loops through the super classes, but unfortunately ignores the abstract class.

**Comment by melloware** [comment]
OK thanks for the investigation.  We will look to fix it.

**Comment by ltlBeBoy** [comment]
Positive test (without an abstract class):

```
<p:datePicker id="dateDayRange"
              maxdate="#{testBacking.dayRangeMax}"
              monthNavigator="true"
              readonlyInput="true"
              selectionMode="range"
              size="16"
              showButtonBar="true"
              showIcon="true"
              value="#{testBacking.dayRange}"
              yearNavigator="true" yearRange="#{testBacking.yearRange}">
    <p:ajax event="dateSelect" />
</p:datePicker>
```
```

@Named
@ViewScoped
public class TestBacking
        implements Serializable {

    private String yearRange;

    private LocalDate dayRangeMax;

    private List<LocalDate> dayRange;

    @PostConstruct
    public void init() {
        // initialize the default year range
        final LocalDate localDateNow = LocalDate.now();
        yearRange = localDateNow.minusYears(10).getYear() + ":" + localDateNow.getYear();

        // set the current date as maximum date
        dayRangeMax = LocalDate.now();
    }

    public String getYearRange() {
        return yearRange;
    }

    public LocalDate getDayRangeMax() {
        return dayRangeMax;
    }

    public List<LocalDate> getDayRange() {
        return dayRange;
    }

    public void setDayRange(List<LocalDate> dayRange) {
        this.dayRange = dayRange;

        System.out.println("TestBacking.setDayRange() -> " + dayRange);
    }

}

```

**Comment by melloware** [comment]
Reproducer: 
[pf-5656.zip](https://github.com/primefaces/primefaces/files/4302155/pf-5656.zip)

**Comment by melloware** [comment]
OK submitted a fix that will fix it but i want other dev's eyes on it before I merge it.

**Comment by ltlBeBoy** [comment]
Thank you for the quick response!

An annotation to your fix

```
Class<?> unproxiedClass = LangUtils.getUnproxiedClass(base.getClass());
while (unproxiedClass != null) {
     try {
          Field field = unproxiedClass.getDeclaredField((String) property);
          ParameterizedType parameterizedType = (ParameterizedType) field.getGenericType();
          Type listType = parameterizedType.getActualTypeArguments()[0];
          type = Class.forName(listType.getTypeName());
          unproxiedClass = null;
     }
     catch (ReflectiveOperationException ex) {
          unproxiedClass = unproxiedClass.getSuperclass();
     }
}
```

It will not work because `LangUtils.getUnproxiedClass(Class)` ignores abstract classes.

I don't know if it is save to extend `LangUtils`. So I wrote a fix for the `BaseCalendarRenderer`. It loops over the abstract super classes in case there are multiple of them:

```
Class unproxiedClass = LangUtils.getUnproxiedClass(base.getClass());
String fieldName = (String) property;

try {
    Field field = unproxiedClass.getDeclaredField(fieldName);
    type = resolveTypeFromField(field);
    unproxiedClass = null;
}
catch (NoSuchFieldException nsfEx) {
    Class checkClass = unproxiedClass.getSuperclass();
    while ((checkClass != null) && Modifier.isAbstract(checkClass.getModifiers())) {
        boolean containsField = Arrays.stream(checkClass.getDeclaredFields())
            .anyMatch(field -> field.getName().equals(fieldName));
        if (containsField) {
            try {
                type = resolveTypeFromField(checkClass.getDeclaredField(fieldName));
                unproxiedClass = null;
                break;
            }
            catch (ReflectiveOperationException ex) {
                throw new FacesException(ex);
            }
        }
        checkClass = checkClass.getSuperclass();
    }
}
...


private Class<?> resolveTypeFromField(Field field)
        throws ClassNotFoundException {

    ParameterizedType parameterizedType = (ParameterizedType) field.getGenericType();
    Type listType = parameterizedType.getActualTypeArguments()[0];

    return Class.forName(listType.getTypeName());
}


```

**Comment by melloware** [comment]
Did you try my fix?  I tested it against your exact use case and it works fine.

LangUtils returns -> TestView.

I then called getDeclaredField() against TestView and it fails. It then asks for TestViews getSuperClass() which returns AbsractTest.  Then it calls getDeclaredField() on AbstractTest and properly finds the field.

**Comment by ltlBeBoy** [comment]
> Did you try my fix? I tested it against your exact use case and it works fine.

Ah, yes. The point is that you just get the direct super class:
```
unproxiedClass = unproxiedClass.getSuperclass();
```

That does work for that particular test case, but it does not work if that super class also has an abstract base class. In my software for example I have an abstract base class for the date limit and date range handling. And an additional abstract class is derived from it and for special statistics views, that group the statistics by an entity, e.g. shipment method or country. And then there are multiple classes derived from this class for the actual view.
```
AbstractStatisticsSalesBacking
    -> AbstractStatisticsGroupingEntitySalesBacking
        -> StatisticsShippingOrderCountrySalesBacking
        -> StatisticsShippingOrderShipmentMethodSalesBacking
        -> ...
```
This is why I loop over each abstract super class:

```
Class checkClass = unproxiedClass.getSuperclass();
while ((checkClass != null) && Modifier.isAbstract(checkClass.getModifiers())) {
```

**Comment by tandraschko** [comment]
guys, i did a small refactoring
we should use the `getter` as the property is public (otherwise it cant be used in EL)
i think it's a bit cleaner now

**Comment by tandraschko** [comment]
See: https://github.com/primefaces/primefaces/commit/32a6ed51a27245ff70f9ec91b8aad710f562c707

**Comment by ltlBeBoy** [comment]
Perfect! Works fine with my software.
Thank you!

**Comment by christophs78** [comment]
@tandraschko: We run into a regression in `LangUtils#getTypeFromCollectionProperty` due to your last refactoring, when i test against the showcase. (DatePicker, multiple- and range-mode)

![grafik](https://user-images.githubusercontent.com/10461942/77256439-90d06400-6c6e-11ea-8fd9-b2881eeeba2c.png)

The condition `if (getter.getGenericReturnType() instanceof ParameterizedType) {` is not fullfilled.

I´ll try to fix this as part of https://github.com/primefaces/primefaces/pull/5718.

**Comment by christophs78** [comment]
@tandraschko:
State within UnitTest (no CDI):
![grafik](https://user-images.githubusercontent.com/10461942/77256650-db061500-6c6f-11ea-924f-4e0a248cca86.png)

State in ApplicationServer (with CDI):
![grafik](https://user-images.githubusercontent.com/10461942/77256675-fd982e00-6c6f-11ea-9e5a-e13151e299a9.png)

Due to CDI we have a proxied object/class which behaves different and does not seem to have generic information. Any suggestions? Or do we need to revert the last refactoring.

@tandraschko, @melloware: Think we should reopen this issue.

**Comment by tandraschko** [comment]
Can you try
`BeanInfo beanInfo = Introspector.getBeanInfo(getUnproxiedClass(base.getClass()));`
instead
BeanInfo beanInfo = Introspector.getBeanInfo(base.getClass());

**Comment by christophs78** [comment]
works

**Comment by tandraschko** [comment]
Also pushed another test which doesn't work currently

**Comment by christophs78** [comment]
Tried to look how spring https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/GenericTypeResolver.java solves this...
Takes some time to understand this.

**Comment by christophs78** [comment]
@tandraschko: Can you have a look at https://github.com/primefaces/primefaces/pull/5718/commits/5d0f6f1c7672161ce8092ee431b575060d13cce0.
This fixes the new test, but it addresses only a part of the iceberg yet.

**Comment by christophs78** [comment]
Did some more work to cover more cases of generic superclasses. 
See https://github.com/primefaces/primefaces/pull/5718/commits/677a64b7b45435e9f2349f2d731a3b0a412c6002
