### ISSUE TITLE
IdleMonitor: Change this context of onactive callback

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#5659]
Low priority. I came across this while adding types and docs for #5027 (yes, still working on this, got some time on my hands now and should be done soon).

The IdleMonitor widget [has got two callback the user can set](https://primefaces.github.io/primefaces/7_0/#/components/idlemonitor?id=attributes): `onactive` and `onidle`.

`onidle` is called with `this` [set to the widget instance](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/idlemonitor/1-idlemonitor.js#L14)

But for `onactive`, it is [set to the document element](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/idlemonitor/1-idlemonitor.js#L21).

That seems inconsistent, so I think that line 21 in `1-idlemonitor.js` should probably changed to:

```javascript
$this.cfg.onactive.call($this);
```

**Comment by melloware** [comment]
I agree with you. PR Submitted.

**Comment by tandraschko** [comment]
Thanks for the PR!
