### ISSUE TITLE
Repeat: exception

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#5661]
## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version? 8.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version:
- Affected browsers:

## 2) Expected behavior
click on button should not fire exception 
version 7.0 is ok

## 3) Actual behavior

an exception ocurred

java.lang.NoSuchMethodError: javax.faces.event.FacesEvent.getFacesContext()Ljavax/faces/context/FacesContext;
	

## 4) Steps to reproduce

click on any button

sample project: https://github.com/erickdeoliveiraleal/primefaces-test

**Comment by Rapster** [comment]
`FacesEvent#getFacesContext` is only available in 2.3

**Comment by tandraschko** [comment]
yep, i re-ported the ui:repeat but didn't test with older JSF versions
