### ISSUE TITLE
Chart JS: Wrong documentation for chart extender

### ISSUE THREAD

**Issue by yennor** [primefaces/primefaces#5663]
## 1) Environment
- PrimeFaces version: 8

## 2) Problem
In the documentation to chart js component is written that the construct for the chart extender in javascript should look like:
`
options ={ legend:{.....}}
`
Which definitely doesn't work.
What works is:
`
options = { options: { legend :{....}}}
`
Would save people some time if you'd correct that :-)

**Comment by tandraschko** [comment]
The docu is in github (https://github.com/primefaces/primefaces/tree/master/docs/8_0), so please create a PR :)

**Comment by yennor** [comment]
ups. Sorry. didn't see that ;-).
here we go:
https://github.com/primefaces/primefaces/pull/5664

**Comment by melloware** [comment]
Thanks yennor good catch.  Can you also make the same change in the 9_0 documentation section and then I will merge your PR. Thanks!

**Comment by melloware** [comment]
I fixed the 9_0 docs.
