### ISSUE TITLE
ChartsJS: TimePoint value type

### ISSUE THREAD

**Issue by yennor** [primefaces/primefaces#5665]
## 1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior
Charts js allows to pass datapoints as x/y Tuples. Right now Primefaces implemented that using the NumericPoint class. Which works, but only accepts, oh wonder, numeric points ;-).
It would be greate if there would be also a DatePoint class, or something similar, which accepts, a combination of LocalDatetime and Numeric points. 
e.g.
x = 2020-01-01-12-00-00
y = 123.45

Charts Js accepts that without any problems and shows them properly when using the type "time" for an axes.

## 3) Actual behavior
I'ts not possible to pass a Date (or LocalDatetime or ...) value to chars js. I have to figure out the conversation on my own...

**Comment by melloware** [comment]
See this ticket: https://github.com/primefaces/primefaces/issues/4564

I think we need a TimePoint object not extend NumericPoint.

**Comment by yennor** [comment]
> I think we need a TimePoint object not extend NumericPoint.

I guessed so, but I didn't want to get into implementation details ;-).

For now. If anybody else stumples over that problem, you can convert your Date object to epoch in seconds (unix timestamp) and pass it in the NumericPoint class, and for chart js you set following parameters for the axes:
time: {
  parser: "X",
}

**Comment by melloware** [comment]
Yeah when I dug into it more with parser etc and needing a datetimeformat on the chartJS side I stopped pursuing it.

**Comment by yennor** [comment]
it works well on the chartJs side if you just use a javascript Date object. Then you don't need to define any parser. But still some other axes options like type: "time",...
To be honest, yes, it's quite a mess and I've got no idea how to implement that in a way it's not going to be confusing to the user by automatically setting some of the axes options without telling him... And otherwise a lot of documentation needs to be written to tell the user he needs to set those options himself....
