### ISSUE TITLE
java: cannot find symbol   symbol:  

### ISSUE THREAD

**Issue by samantrader** [primefaces/primefaces#5680]
hello  

i  write   a   sample  code     with  joinface   

and  use    ContextMenu      but     in    MenuView   class   has   thsi  error  

Error:(25, 53) java: cannot find symbol
  symbol:   method builder()
  location: class org.primefaces.model.menu.DefaultSubMenu

how  fix  it   

thanks

**Comment by tandraschko** [comment]
please use the forum, this is for real issues, not for support
