### ISSUE TITLE
DatePicker: Manually clearing the input field should result in null value instead of empty string

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5681]
## 1) Environment
- PrimeFaces version: latest from trunk

## 2) Expected behavior
1. An initial empty datepicker: `widget.getDate()` returns null
2. Clearing the Datepicker using the clear-button: `widget.getDate()` returs null
3. Manually clearing the input field of the datepicker: `widget.getDate()` returns null

## 3) Actual behavior
 3. Manually clearing the input field of the datepicker: `widget.getDate()` returns an empty string

## 4) Steps to reproduce
Go to https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml
- Execute `PF('widget_form_buttonbar').getDate()` in the browsers console: NULL
- Pick a date from the "Button Bar" calendar
- Clear the date using the "clear" button
- Execute `PF('widget_form_buttonbar').getDate()` in the browsers console: NULL
- Pick a date from the "Button Bar" calendar
- Clear the date by manually deleting everything form the input field
- Execute `PF('widget_form_buttonbar').getDate()` in the browsers console: ""

## 5) Possible fix
Change [this line](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L2163) to detect the empy string and exchange it with `null`

**Comment by fanste** [comment]
PR #5682

**Comment by melloware** [comment]
@christophs78 Can you please review?
