### ISSUE TITLE
DatePicker: Incomplete manual input throws JS error in hideOverlay

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5683]
## 1) Environment
- PrimeFaces version:  8.0 (Showcase)

## 2) Expected behavior
Never throw JS error, when the calendar overlay closes

## 3) Actual behavior
JS error is thrown when the overlay closes and the value of the input fiels does not represent a valid date. The manual input is broken until a date is selected from the calendar.
```
TypeError: this.viewDate.getMonth is not a function               datepicker.js.xhtml:1098:67
renderDateView https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:1098
    $.widget/</proxiedPrototype[prop]</< jQuery
    renderPanelElements https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:1079
    $.widget/</proxiedPrototype[prop]</< jQuery
    updateViewDate https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:2157
    $.widget/</proxiedPrototype[prop]</< jQuery
    hideOverlay https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:1805
    $.widget/</proxiedPrototype[prop]</< jQuery
    documentClickListener https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:1814
```

## 4) Steps to reproduce
 - Select a date from the [Datepicker "Popup"](https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml)
 - `PF('widget_form_popup').getDate()` returns that date
 - Click again in the input field, the overlay opens. Manually change the date so it won't be valid. Click outside the datepicker. Overlay closes. JS error is thrown in the console.
 - `PF('widget_form_popup').getDate()` returns the invalid input as string
 - Click again in the input field, overlay opens. Manually change the date until it is valid. Each keyup will throw the same JS error. Click outside the datepicker. Overlay closes. JS error is still thrown.
 - `PF('widget_form_popup').getDate()` will return the valid date as string
 - Click again in the input field, overlay opens. Select a date. Error is thrown again, but if you open the calendar again, the correct view is shown.
 - `PF('widget_form_popup').getDate()` returns the selected date

## 5) Possible fix
 Don't call [`this.updateViewDate(null, viewDate)`](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L1805) until `viewDate` is really a date.

Something like:
```
if(viewDate instanceof Date) {
    this.updateViewDate(null, viewDate);
}
```

WDYT?

**Comment by melloware** [comment]
Not a bad idea. have you tried it?

**Comment by fanste** [comment]
Not yet, but soon. 

It will be similar to [onUserInput](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L1575) which simply ignores the call to `this.updateViewDate` if the date could not be parsed (`catch` only update the model not the view).

**Comment by fanste** [comment]
Seems to be working.

PR #5687
