### ISSUE TITLE
DatePicker: setDate throws JS error

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5684]
## 1) Environment
- PrimeFaces version: 8.0 (Showcase)

## 2) Expected behavior
Don't throw JS error on `widget.setDate(...)`

## 3) Actual behavior
JS error is thrown because of missing variable
```
TypeError: event is undefined
    onDateSelect https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:1923
    $.widget/</proxiedPrototype[prop]</< jQuery
    setDate https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:195
    jQuery 5
    setDate https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:2384
```

## 4) Steps to reproduce
 - Open [Showcase](https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml)
 - Execute one of the follwoing examples in the browsers console:
    - `PF('widget_form_popup').setDate('3/27/20')`
    - `PF('widget_form_popup').setDate(new Date())`

## 5) Possible fix
Replace [`event`](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L194) with `null`.

```
this.updateViewDate(null, newDate);
this.onDateSelect(null, newDateMeta);
```

**Comment by melloware** [comment]
@christophs78 Please review this also.

**Comment by fanste** [comment]
PR #5685

**Comment by melloware** [comment]
After your fix I still get the error here: `PF('widget_form_popup').setDate(new Date())`

**Comment by melloware** [comment]
Nevermind its fixed.
