### ISSUE TITLE
DatePicker: Support string-input for setViewDate

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5688]
## 1) Environment
- PrimeFaces version: 8.0 (Showcase)

## 2) Expected behavior
`widget.setViewDate` should work with string and Date input. `widget.setDate` also allows both types.

## 3) Actual behavior
Only Date input is working.

## 4) Steps to reproduce
 - Open the browser console in the [Showcase](https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml)
 - `PF('widget_form_popup').setViewDate('04/20/21')`: JS exception is thrown, because `updateViewDate` expects a date
 - `PF('widget_form_popup').setViewDate(new Date())`: is working

PR is coming

**Comment by fanste** [comment]
PT #5689

**Comment by melloware** [comment]
Nice work. I would like @christophs78 to review all your fixes but to me they look good.
