### ISSUE TITLE
p:blockUI doesn't work with p:commandButton

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#569]
I have a p:commandButton which y want block with p:blockUI but it doesn't with this component.

I used following libraries:
primefaces-5.2.jar
jsf-api-2.2.10.jar
jsf-impl-2.2.10.jar
JDK 1.8

fragment from xhtml file:
<code><pre>
<p:commandButton id="saveBtn" value="save" action="#{myBean.anyAction}" />
<p:blockUI bloked="true" block="saveBtn" />
</pre></code>

the problem is that the block's div tag is inside the tag button

**Comment by cagataycivici** [comment]
Buttons cannot be blocked directly, you need a wrapper component like outputPanel around it and block it instead.
