### ISSUE TITLE
DatePicker: setDate should handle null or empty string parameter

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5692]
## 1) Environment
- PrimeFaces version: 8.0 (Showcase)

## 2) Expected behavior
`widget.setDate(null)` or `widget.setDate('')` should clear the date picker.

## 3) Actual behavior
`widget.setDate(null)` 
```
TypeError: newDate is null
    setDate https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:191
    jQuery 5
    setDate https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:2384
```
`widget.setDate('')`
```
TypeError: newDate.getDate is not a function
    setDate https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:191
    jQuery 5
    setDate https://www.primefaces.org/showcase/javax.faces.resource/datepicker/datepicker.js.xhtml?ln=primefaces&v=8.0-SNAPSHOT:2384
```

## 4) Steps to reproduce
 - Open browser console on [Showcase > Datepicker](https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml)
 - Execute `PF('widget_form_popup').setDate(null)` or `PF('widget_form_popup').setDate('')`

## 5) Possible Fix
The fix is relatively easy but it would be possible in two ways:

1.  Implement the fix on the PF component (1-datepicker.js / setDate)
    - Check for `date == null || date == ''` and either invoke `widget.jq.data().primeDatePicker.updateModel(null, null)` or `this.jq.datePicker('setDate', date);`
2. A) Implement the fix on the date picker (0-datepicker.js / setDate)
    - Check for `newDate instanceof Date` after `parseValue` and either invoke `this.updateModel(null, null)` or _the code as it is currently implemented_.
3. B) Implement the fix on the date picker (0-datepicker.js / setDate)
    - Check for `date == null || date == ''` before`parseValue` and either invoke `this.updateModel(null, null)` or _the code as it is currently implemented_.

I prefer no.  3. WDYT?

**Comment by melloware** [comment]
I like #3 also

**Comment by fanste** [comment]
PR #5693
