### ISSUE TITLE
Timeline: Performance issues with large datasets

### ISSUE THREAD

**Issue by MatthiasScherrerFGCZ** [primefaces/primefaces#5697]
The timeline component is not usable anymore for larger datasets 

## 1) Environment
- PrimeFaces version: PrimeFaces-8.0
- Application server + version: Mojarra-2.3.13
- OS on the client: Ubuntu 18.04.3 LTS
## 2) Expected behavior
The timeline (tested with around 9500 datasets) should render the timeline within a reasonable amount of time (e.g., < 2s).
In PF7, this was no problem at all.

## 3) Actual behavior
The timeline (tested with around 9500 datasets) takes extremely long to render (up to 2min).
It is also visible in the console where it shows:
[Violation] 'requestAnimationFrame' handler took 107511ms
This happens as PF redraws the items via the vis.js library
..

## 4) Steps to reproduce
Simply use a large enough number of items in the timeline.

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
  <title>PrimeFaces Test</title>
</h:head>
<h:body>

  <p:timeline
    id="timeline"
    value="#{basicTimelineView.model}"
    height="250px"
    selectable="#{basicTimelineView.selectable}"
    zoomable="#{basicTimelineView.zoomable}"
    moveable="#{basicTimelineView.moveable}"
    stackEvents="#{basicTimelineView.stackEvents}"
    axisOnTop="#{basicTimelineView.axisOnTop}"
    eventStyle="#{basicTimelineView.eventStyle}"
    showCurrentTime="#{basicTimelineView.showCurrentTime}">
  </p:timeline>

</h:body>
</html>
```

## 6) Sample Bean
```
@Named("basicTimelineView")
@ViewScoped
public class TestView implements Serializable {

    private boolean axisOnTop;

    private String eventStyle = "box";

    private TimelineModel<String, ?> model;

    private boolean moveable = true;

    private boolean selectable = true;

    private boolean showCurrentTime = true;

    private boolean showNavigation = false;

    private boolean stackEvents = true;

    private boolean zoomable = true;

    public String getEventStyle() {
        return eventStyle;
    }

    /**
     * Get model.
     *
     * @return the model
     */
    public TimelineModel<String, ?> getModel() {
        return model;
    }

    @PostConstruct
    protected void initialize() {
        model = new TimelineModel<>();

        long startTime = System.currentTimeMillis();
        for (int year = 2010; year < 2021; year++) {
            for (int month = 1; month < 12; month++) {
                for (int day = 1; day < 26; day++) {
                    String dateString = year + "_" + month + "_" + day;
                    model.add(TimelineEvent.<String>builder().data(dateString).startDate(LocalDate.of(year, month, day)).build());
                }
            }
        }

        long endTime = System.currentTimeMillis();
        long duration = endTime - startTime;
        System.out.println("nodes == " + model.getEvents().size());
        System.out.println("duration for node generation on server in ms == " + duration);
    }

    public boolean isAxisOnTop() {
        return axisOnTop;
    }

    public boolean isMoveable() {
        return moveable;
    }

    public boolean isSelectable() {
        return selectable;
    }

    public boolean isShowCurrentTime() {
        return showCurrentTime;
    }

    public boolean isShowNavigation() {
        return showNavigation;
    }

    public boolean isStackEvents() {
        return stackEvents;
    }

    public boolean isZoomable() {
        return zoomable;
    }

    public void setAxisOnTop(boolean axisOnTop) {
        this.axisOnTop = axisOnTop;
    }

    public void setEventStyle(String eventStyle) {
        this.eventStyle = eventStyle;
    }

    /**
     * Set model.
     *
     * @param model the model to set
     */
    public void setModel(TimelineModel<String, ?> model) {
        this.model = model;
    }

    public void setMoveable(boolean moveable) {
        this.moveable = moveable;
    }

    public void setSelectable(boolean selectable) {
        this.selectable = selectable;
    }

    public void setShowCurrentTime(boolean showCurrentTime) {
        this.showCurrentTime = showCurrentTime;
    }

    public void setShowNavigation(boolean showNavigation) {
        this.showNavigation = showNavigation;
    }

    public void setStackEvents(boolean stackEvents) {
        this.stackEvents = stackEvents;
    }

    public void setZoomable(boolean zoomable) {
        this.zoomable = zoomable;
    }
}
```

The given sample always takes around 28k to 39k milliseconds to render.

I already used the vis.js library in another project in 2015 and the number of nodes in a graph for example presented already a limitation.

**Comment by melloware** [comment]
Can you create a simple test case for us using the PrimeFaces Test project so I can debug it?
https://github.com/primefaces/primefaces-test

**Comment by MatthiasScherrerFGCZ** [comment]
@melloware Will provide a reproducer case tomorrow.

**Comment by christophs78** [comment]
Is it an option to use LazyLoading?
https://www.primefaces.org/showcase/ui/data/timeline/lazy.xhtml

**Comment by MatthiasScherrerFGCZ** [comment]
@melloware I updated it with the reproducer xhtml and bean.

**Comment by melloware** [comment]
thank you very much.  Let me investigate.

**Comment by ltlBeBoy** [comment]
I like to mention that there also is a performance issue when the events are grouped. You can reproduce this by opening the showcase and then jump between "Basic" and "Grouping". The grouped events are rendered much slower. This was not the case with PrimeFaces 7.0.

**Comment by melloware** [comment]
Runnable reproducer: 
[pf-5697.zip](https://github.com/primefaces/primefaces/files/4344689/pf-5697.zip)

@jasonex7 being included in case he cares and I opened a ticket with vis-timeline.

**Comment by melloware** [comment]
here is a JSFiddle: https://jsfiddle.net/Ld37yspu/

It is set to 2000 items it works relatively well but set it to 5000 items or more.

```javascript
var itemCount = 5000;
```

**Comment by MatthiasScherrerFGCZ** [comment]
@melloware Is there any update on this issue from your side? I see on the vis.js side, there are no updates.

**Comment by melloware** [comment]
This is a vis-timeline.js issue and I created that ticket there but they seem to be ignoring it so far. There is nothing for PF to fix here its got to be fixed in vis-timelines as you see my JSFiddle example above whick takes PF out of the equation.

**Comment by MatthiasScherrerFGCZ** [comment]
@melloware Thanks for the clarification. I hope vis.js will address this issue in the near future.

**Comment by jasonex7** [comment]
> Is it an option to use LazyLoading?
> https://www.primefaces.org/showcase/ui/data/timeline/lazy.xhtml

Hi, I'm agree with @christophs78 in using Lazy Loading as a workaround, because it's a great feature to handle great amount of `TimeLineEvent`'s. I'm using that in a project and it works fine.

**Comment by melloware** [comment]
I am going to close this issue for now since it is being tracked on the vis-timeline page.  I am following that ticket and will update PF if/when they fix it.

**Comment by melloware** [comment]
As a note in the latest Timeline they added an optimization for large datasets. See: https://github.com/visjs/vis-timeline/pull/1281

**Comment by MatthiasScherrerFGCZ** [comment]
@melloware   
Thanks, we tested it and it greatly improves the performance, even if it is not on the level before the breaking changes. But it is now in a state where we can use it.

**Comment by melloware** [comment]
Thanks for testing and reporting back!
