### ISSUE TITLE
ExceptionHandler: suppress logging certain exception types

### ISSUE THREAD

**Issue by kawoolutions** [primefaces/primefaces#5705]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? No. 8.0.
- Does it work on the newest sources in GitHub? n.a.
- Application server + version: Any
- Affected browsers: Any

## 2) Expected behavior

There's a forum posting here:
https://forum.primefaces.org/viewtopic.php?f=3&t=61388

## 3) Actual behavior

We would like to be able to suppress logging any exceptions, most notably `ViewExpiredException`'s, which occurr after session expiry. It would be pretty unnecessary to stuff the log files with these exception traces.

## 4) Steps to reproduce

The showcase example pretty much demonstrates it: https://www.primefaces.org/showcase/ui/misc/exceptionHandler.xhtml

Just click on any of the buttons to trigger an exception. The exception trace gets logged...

We need a way to suppress certain exception types, first and foremost `ViewExpiredException`'s.

The OmniFaces FullAjaxExceptionHandler shows how this could be done:

http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler

Maybe like:

```
<context-param>
    <param-name>org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING</param-name>
    <param-value>javax.faces.application.ViewExpiredException</param-value>
</context-param>
```

## 5) Sample XHTML

See showacse: https://www.primefaces.org/showcase/ui/misc/exceptionHandler.xhtml

## 6) Sample bean

See showacse: https://www.primefaces.org/showcase/ui/misc/exceptionHandler.xhtml

**Comment by stolp** [comment]
I am facing the same problem and I am likewise interested in a solution for this.

**Comment by melloware** [comment]
Looks like the PrimefacesExceptionHanlder already ignores ViewExpired if JSF Stage is production.  See the code here:

https://github.com/primefaces/primefaces/blob/b581f9d30cbf106db7b83a67f6e98e2de69d7760/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandler.java#L131-L140

**Comment by melloware** [comment]
@stolp @kawoolutions can you verify the above if your JSF project stage is Production the viewExpired is not logged by the PF exceptionHandler?

**Comment by melloware** [comment]
@stolp @kawoolutions ???

**Comment by stolp** [comment]
Will check for this tomorrow. Sorry - missed this.

**Comment by stolp** [comment]
I did some first tests with this.

I added the following code to my page template in a form:

`<p:ajaxExceptionHandler type="javax.faces.application.ViewExpiredException" />`

I added the following to faces-config.xml

```
  <application>
    <el-resolver>
        org.primefaces.application.exceptionhandler.PrimeExceptionHandlerELResolver
    </el-resolver>
  </application>
  
  <factory>
    <exception-handler-factory>
    org.primefaces.application.exceptionhandler.PrimeExceptionHandlerFactory
    </exception-handler-factory>
  </factory>
```

After timeout I clicked a button. No exception was logged.

I am running PrimeFaces 8.0 under Mojarra 2.3

So for me this is working.

**Comment by melloware** [comment]
ok great.  I think the ticket is still valid though the be able to add "other" types of exceptions you don't want logged similar to OmniFaces.

**Comment by stolp** [comment]
Agreed - this might be useful.

**Comment by tandraschko** [comment]
i can imagine a new context param with exceptions seperated by ,
what would be a good name? @melloware ?

**Comment by melloware** [comment]
Here is what OmniFaces does...

> By default all exceptions are logged. You can supply a context parameter "org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING" to specify exception types to ignore from logging. The context parameter value must be a commaseparated string of fully qualified names of exception types. Note that this also covers subclasses of specified exception types.

```xml
<context-param>
    <param-name>org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING</param-name>
    <param-value>javax.faces.application.ViewExpiredException</param-value>
</context-param>
```

So how about...
```xml
<context-param>
    <param-name>primefaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING</param-name>
    <param-value>javax.ejb.EJBException,javax.persistence.RollbackException</param-value>
</context-param>
```

**Comment by tandraschko** [comment]
Commit my proposal. Would you like to test it?

**Comment by melloware** [comment]
yep will test!

**Comment by melloware** [comment]
This works great.  I think it is safe to close this ticket!

**Comment by tandraschko** [comment]
thanks!
