### ISSUE TITLE
InputNumber: Hidden input is not always updated

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5706]
## 1) Environment
- PrimeFaces version: 8.0 (Showcase)

## 2) Expected behavior
Changes to the visible input field should always be written to the hidden input field. Otherwise the value submitted may not be the one you see.

## 3) Actual behavior
In some cases the value is written to the hidden input on blur and not ASAP.

## 4) Steps to reproduce
 - Open the browser console on the [Showcase > InputNumber](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml)
 - Select the first InputNumber with the DOM selector
 - Enter some value. Each keyup will trigger an update to the hidden input :heavy_check_mark:
 - Strg+A, Strg+X (or Strg+Z, ...). Input field is empty, Hidden input still contains the previous value :x:
 - Use the mousewheel to change the number. Hidden input is updated on blur or any other change trigger :x:

## 5) Possible fix
According to the [source code](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js#L6034) a native `input` event is triggered after using the mouswheel at at least on Strg+X/+V but not on +Z (after a short test via browser console)

**Comment by melloware** [comment]
I think I can fix it.

**Comment by melloware** [comment]
Try add this to your page..  It fixes mousehweel and paste issue.  But it does not seem to handle CTRL-X (cut) or CTRL+Z (undo)

```javascript
PrimeFaces.widget.InputNumber.prototype.wrapEvents = function() {
        var $this = this;

        // copy the value from the input to the hidden input
        var originalOnkeyup = this.input.prop('onkeyup');
        this.input.prop('onkeyup', null).off('keyup').on('keyup', function (e) {

            var oldValue;

            var keyCode = e.which;
            if (keyCode === 8 || keyCode === 13 || keyCode === 32
                    || (keyCode >= 46 && keyCode <= 90)
                    || (keyCode >= 96 && keyCode <= 111)
                    || (keyCode >= 186 && keyCode <= 222)) {

                oldValue = $this.copyValueToHiddenInput();
            }

            if (originalOnkeyup && originalOnkeyup.call(this, e) === false) {
                if (oldValue) {
                    $this.setValueToHiddenInput(oldValue);
                }
                return false;
            }
        });

        var originalOnchange = this.input.prop('onchange');
        this.input.prop('onchange', null).off('change').on('change', function (e) {

            var oldValue = $this.copyValueToHiddenInput();
            if (originalOnchange && originalOnchange.call(this, e) === false) {
                $this.setValueToHiddenInput(oldValue);
                return false;
            }
        });

        var originalOnkeydown = this.input.prop('onkeydown');
        this.input.prop('onkeydown', null).off('keydown').on('keydown', function (e) {

            var oldValue = $this.copyValueToHiddenInput();
            if (originalOnkeydown && originalOnkeydown.call(this, e) === false) {
                $this.setValueToHiddenInput(oldValue);
                return false;
            }
        });

        this.input.off('input').on('input', function (e) {
            $this.copyValueToHiddenInput();
        });
    };
```

**Comment by fanste** [comment]
That is working.

The only maybe negative side effect: `input` is also triggered on any key press (or holding the key down). This will always call `copyValueToHidenInput` twice.

**Comment by melloware** [comment]
I think that is OK. Its a pretty lightweight operation.
