### ISSUE TITLE
[Documentation] p:inputNumber emptyValue, symbolPosition, decimalPlaces outdate

### ISSUE THREAD

**Issue by nokiajavi** [primefaces/primefaces#5708]
According to the PF 8 migration guide, now the emptyValue attribute of the InputNumber component, the value sign is now always.
The attribute information is also outdated: symbolPosition: prefix is now p, suffix is now s
The attribute information is also outdated: decimalPlaces: now defaults to 2

**Comment by melloware** [comment]
I updated the migration guide with more accurate info for InputNumber migration.
https://github.com/primefaces/primefaces/wiki/Migration-Guide

I updated the docs for 8.0 and 9.0 you can see the updated in this PR:
https://github.com/primefaces/primefaces/pull/5707/files

Can you verify this is what you are expecting?

**Comment by nokiajavi** [comment]
Yes! is correct! very well explained. thanks
