### ISSUE TITLE
DatePicker: Add showWeek option like Calendar

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5713]
## 1) Environment
- PrimeFaces version: 8.0

## 2) Description
`p:calendar` has the options `showWeek` and `calculateWeek`. This will add an additional column infront of each week containing the week number.

This should be supported by the new `p:datePicker`.

PR is on the way

**Comment by fanste** [comment]
PR #5715

**Comment by melloware** [comment]
@fanste Does your new method fix this issue as well? https://github.com/primefaces/primefaces/issues/1052
