### ISSUE TITLE
dialogReturn event listener not called when commandButton disabled changes

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#5714]
## 1) Environment
- PrimeFaces version: 7.0.12, test case using 7.0
- Application server + version: WildFly 18.0.1, test case using Jetty 9.4.20.v20190813
- Affected browsers: tested on Firefox, probably all

## 2) Expected behavior

Ajax dialogReturn event listener called, button disabled afterwards (on update).

## 3) Actual behavior

Since disabled is called multiple times at various process/render stages (you can add logging to my test case if you wish), if getter recalculates disabled state to true, ajax event listener is not called (even though onstart JavaScript shows the event begins, and update is performed). Using process="@none" doesn't help, as then nothing happens.

## 4) Steps to reproduce

Run attached test case. Open and close first level dialog twice, see in the log that dialogReturn was called only once. Ignore option to open more levels of nested dialogs, I was checking if that wasn't source of problem.

```
My sequence:
Mar 20, 2020 2:54:14 PM org.primefaces.test.TestView init
INFO: 1: init (inDialog 0)
Mar 20, 2020 2:54:15 PM org.primefaces.test.TestView showDialog
INFO: 1: showDialog
Mar 20, 2020 2:54:15 PM org.primefaces.test.TestView init
INFO: 2: init (inDialog 1)
Mar 20, 2020 2:54:17 PM org.primefaces.test.TestView closeDialog
INFO: 2: closeDialog
Mar 20, 2020 2:54:18 PM org.primefaces.test.TestView dialogReturn
INFO: 1: dialogReturn
Mar 20, 2020 2:54:20 PM org.primefaces.test.TestView showDialog
INFO: 1: showDialog
Mar 20, 2020 2:54:20 PM org.primefaces.test.TestView init
INFO: 2: init (inDialog 1)
Mar 20, 2020 2:54:25 PM org.primefaces.test.TestView closeDialog
INFO: 2: closeDialog
```
[primefaces-test.tar.gz](https://github.com/primefaces/primefaces/files/4359950/primefaces-test.tar.gz)

**Comment by morvael** [comment]
My use case is that button is disabled if a database record exists, otherwise button allows to open dialog in which the user can add that record. Closing that dialog returns the newly added record id to caller. In dialogReturn listener I want to do something with that id, sadly I can't because the event works only partially (as it is processed it disables the button and that prevents listener from firing, even though update="" happens normally).

**Comment by melloware** [comment]
Doesn't work on 8.0 either.  Have you done any deep analysis for a potential fix?

**Comment by morvael** [comment]
I don't know the innards of JSF/PF well enough to propose a fix. IMHO, it would be good if p:ajax call would not check rendered/disabled on parent during execution of a call (if it already started, why not let it run to completion?). A workaround could be added that allows to set a flag on ajax element to run despite parent being not rendered/disabled.

**Comment by morvael** [comment]
By default p:ajax runs with process="@this", but @this means parent commandButton. And with @none it doesn't work at all. It could be made to work with @none or there should be something between @none and @this that means commandButton is not to be processed, but ajax event is. I don't know if this even makes any sense to you, for me both are xhtml elements, but p:ajax is not an actual component.

**Comment by melloware** [comment]
Hmm I will defer to @tandraschko as he knows more about this than I do.

**Comment by morvael** [comment]
Will try a workaround, returning disabled false for PhaseId APPLY_REQUEST_VALUES.
```
Mar 20, 2020 4:09:31 PM org.primefaces.test.TestView init
INFO: 1: init (inDialog 0)
Mar 20, 2020 4:09:31 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:31 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:31 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:32 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId APPLY_REQUEST_VALUES 2)
Mar 20, 2020 4:09:32 PM org.primefaces.test.TestView showDialog
INFO: 1: showDialog
Mar 20, 2020 4:09:32 PM org.primefaces.test.TestView init
INFO: 2: init (inDialog 1)
Mar 20, 2020 4:09:32 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:32 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:32 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:35 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId APPLY_REQUEST_VALUES 2)
Mar 20, 2020 4:09:35 PM org.primefaces.test.TestView closeDialog
INFO: 2: closeDialog
Mar 20, 2020 4:09:37 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId APPLY_REQUEST_VALUES 2)
Mar 20, 2020 4:09:37 PM org.primefaces.test.TestView dialogReturn
INFO: 1: dialogReturn
Mar 20, 2020 4:09:37 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:37 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:37 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:38 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId APPLY_REQUEST_VALUES 2)
Mar 20, 2020 4:09:38 PM org.primefaces.test.TestView showDialog
INFO: 1: showDialog
Mar 20, 2020 4:09:38 PM org.primefaces.test.TestView init
INFO: 2: init (inDialog 1)
Mar 20, 2020 4:09:38 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:38 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:38 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:39 PM org.primefaces.test.TestView isCommandDisabled
INFO: 2: isCommandDisabled (phaseId APPLY_REQUEST_VALUES 2)
Mar 20, 2020 4:09:39 PM org.primefaces.test.TestView closeDialog
INFO: 2: closeDialog
Mar 20, 2020 4:09:42 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId APPLY_REQUEST_VALUES 2)
Mar 20, 2020 4:09:42 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:42 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
Mar 20, 2020 4:09:42 PM org.primefaces.test.TestView isCommandDisabled
INFO: 1: isCommandDisabled (phaseId RENDER_RESPONSE 6)
```

**Comment by morvael** [comment]
The problem is how to detect which one call in APPLY_REQUEST_VALUES phase is to dialogReturn event, in order to keep default behaviour for other events.

**Comment by morvael** [comment]
Name of the event can be found in FacesContext.getCurrentInstance().getExternalContext().getRequestParameterValuesMap():
```
INFO: 1: isCommandDisabled (phaseId APPLY_REQUEST_VALUES 2, viewRootId /test.xhtml, params [form:cmd1_pfdlgcid->[19f1813a-aa73-40ba-b5d0-c7ba6a37ead6], javax.faces.behavior.event->[dialogReturn], form->[form], javax.faces.partial.render->[form:formPanel], javax.faces.ViewState->[-4519141637617302563:5191855289635608104], javax.faces.source->[form:cmd1], javax.faces.partial.event->[dialogReturn], javax.faces.partial.ajax->[true], javax.faces.partial.execute->[form:cmd1]])
```

**Comment by morvael** [comment]
Workaround for my example:
```
    public boolean isCommandDisabled() {
        if (isEvent(PhaseId.APPLY_REQUEST_VALUES, "dialogReturn")) {
            return false;
        }
        return counter >= 3;
    }

    private static boolean isEvent(PhaseId phaseId, String event) {
        FacesContext fc = FacesContext.getCurrentInstance();
        if (fc != null && fc.getCurrentPhaseId().equals(phaseId)) {
            ExternalContext ec = fc.getExternalContext();
            if (ec != null) {
                Map<String, String> map = ec.getRequestParameterMap();
                if (map != null) {
                    return event.equals(map.get("javax.faces.behavior.event"));
                }
            }
        }
        return false;
    }
```
results in
```
Mar 20, 2020 4:37:13 PM org.primefaces.test.TestView init
INFO: 1: init (inDialog 0)
Mar 20, 2020 4:37:14 PM org.primefaces.test.TestView showDialog
INFO: 1: showDialog
Mar 20, 2020 4:37:14 PM org.primefaces.test.TestView init
INFO: 2: init (inDialog 1)
Mar 20, 2020 4:37:16 PM org.primefaces.test.TestView closeDialog
INFO: 2: closeDialog
Mar 20, 2020 4:37:17 PM org.primefaces.test.TestView dialogReturn
INFO: 1: dialogReturn
Mar 20, 2020 4:37:18 PM org.primefaces.test.TestView showDialog
INFO: 1: showDialog
Mar 20, 2020 4:37:18 PM org.primefaces.test.TestView init
INFO: 2: init (inDialog 1)
Mar 20, 2020 4:37:20 PM org.primefaces.test.TestView closeDialog
INFO: 2: closeDialog
Mar 20, 2020 4:37:21 PM org.primefaces.test.TestView dialogReturn
INFO: 1: dialogReturn
```
dialogReturn listener was called twice.

**Comment by morvael** [comment]
BTW, it isn't great that disabled getter is called three times during update. What if it's a costly operation?

**Comment by tandraschko** [comment]
if the AJAX listener would be executed on a disabled a button, it would be a big security risk.

also it's know that e.g. rendered flags are called multiple times ;) Please see my hints here: http://tandraschko.blogspot.com/2017/11/increase-your-jsf-application.html

**Comment by morvael** [comment]
The problem is it's not disabled beforehand, and the event starts executing, but becomes disabled mid-way and only the listener part stops working as a result. IMHO that's a bug. The whole problem is the button should become disabled because of the event, after the event, but due to how this framework (or JSF as a whole) is working, it checks disabled mid-way and breaks itself because it becomes disabled during the event.

**Comment by morvael** [comment]
What works: process, update, client-side events like onstart
What stops working: listener

It's not a very consistent behavior.

**Comment by tandraschko** [comment]
it's by design in JSF and nothing we can change in PF.

Your workaround is valid and i already used in the past.

**Comment by tandraschko** [comment]
I would suggest you to create a jsf-spec issue for the future and close this issue here.

**Comment by morvael** [comment]
Thanks
