### ISSUE TITLE
Dashboard: DataExport does not work in disabled dashboard

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#5723]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? No, 8.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Unknown
- Application server + version: Wildfly 18
- Affected browsers: Firefox 74, Chrome 80

## 2) Expected behavior

A p:dataExport inside a p:dashboard that is disabled="true" should popup the export dialog. The disabled attribute is defined in the docs as: "Disables reordering feature." and that is how we use it. This worked in 6.2.6 (currently upgrading from there).

## 3) Actual behavior

Clicking a p:dataExport inside a disabled p:dashboard ignores the export and triggers the ajax="false" of the commandLink submitting an empty post request.

## 4) Steps to reproduce

See code. Setup a disabled p:dashboard, put a datatable and p:dataExport inside, click link.

## 5) Sample XHTML

[test.xhtml.txt](https://github.com/primefaces/primefaces/files/4372029/test.xhtml.txt)

## 6) Sample bean

[TestController.java.txt](https://github.com/primefaces/primefaces/files/4372030/TestController.java.txt)

**Comment by firsthour** [comment]
Without knowing much about this situation, I wonder if it's related to #5606?

**Comment by melloware** [comment]
That would make sense as the link is inside a disabled component it most likely is that issue.  But why would you expect something to work inside a disabled Dashboard?

**Comment by melloware** [comment]
A good explanation as to why this was implemented is in the ticket: https://github.com/primefaces/primefaces/issues/5603

**Comment by melloware** [comment]
Ahhh you know what.  Disabled is a bad name for it in the Dashboard component.    The name of the property in the dashboard should be `disableReordering`.

**Comment by melloware** [comment]
@firsthour To solve your problem in the short term set `disabled="false"` on the component and add this JS to your page.

```javascript
PrimeFaces.widget.Dashboard = PrimeFaces.widget.Dashboard.extend({
    init: function(cfg) {
        this._super(cfg);

        this.cfg.connectWith = this.jqId + ' .ui-dashboard-column';
        this.cfg.placeholder = 'ui-state-hover';
        this.cfg.forcePlaceholderSize = true;
        this.cfg.revert = false;
        this.cfg.handle = '.ui-panel-titlebar';

        var $this = this;

        if (this.hasBehavior('reorder')) {
            this.cfg.update = function(e, ui) {
                if (this === ui.item.parent()[0]) {
                    var itemIndex = ui.item.parent().children().filter(':not(script):visible').index(ui.item),
                        receiverColumnIndex = ui.item.parent().parent().children().index(ui.item.parent());

                    var ext = {
                        params: [{
                                name: $this.id + '_reordered',
                                value: true
                            },
                            {
                                name: $this.id + '_widgetId',
                                value: ui.item.attr('id')
                            },
                            {
                                name: $this.id + '_itemIndex',
                                value: itemIndex
                            },
                            {
                                name: $this.id + '_receiverColumnIndex',
                                value: receiverColumnIndex
                            }
                        ]
                    };

                    if (ui.sender) {
                        ext.params.push({
                            name: $this.id + '_senderColumnIndex',
                            value: ui.sender.parent().children().index(ui.sender)
                        });
                    }

                    $this.callBehavior('reorder', ext);
                }
            };
        }

        this.cfg.disabled = true;
        $(this.jqId + ' .ui-dashboard-column').sortable(this.cfg);
    }
});
```

That manually sets the Dashboard disabled in JS code but leaves it enabled for the server side code.

**Comment by firsthour** [comment]
Thanks for going through all this and understanding and explaining it to me. I like the reordering attribute a lot, we've got Elite so I hope we can see that in the near future.

**Comment by melloware** [comment]
Hopefully that can be added to 8.0.1 Elite if @mertsincan approves.  And yes `reordering` seems like a clearer attribute and disabled is now what real disabled should be and disables the whole dashboard and greys it out.
