### ISSUE TITLE
ChartJS: Bar chart axes offset always true

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#5726]
## 1) Environment
PrimeFaces version: PrimeFaces-8.0
Application server: Jetty 9.4.27 + version: Mojarra-2.2.20

## 2) Expected behavior

In the chart the two yAxes must overlap because offset is set to false.

```java
		CartesianLinearAxes axesY1 = new CartesianLinearAxes();
		axesY1.setId("A");
		axesY1.setPosition("left");
		axesY1.setType("linear");
		axesY1.setOffset(false); // => offset forced to false
		CartesianLinearTicks ticksY1 = new CartesianLinearTicks();
		ticksY1.setMin(0);
		ticksY1.setStepSize(50);
		axesY1.setTicks(ticksY1);
```

## 3) Actual behavior

The two yAxes do not overlap because the yAxes offset is always generated as true in chart.js json.

json of PF8.0 example
```javascript
{
   "scales":{
      "display":true,
      "yAxes":[
         {
            "offset":true,
            "position":"left",
            "id":"A",
            "stacked":false,
            "type":"linear",
            "ticks":{
               "autoSkip":true,
               "mirror":false,
               "beginAtZero":false,
               "min":0,
               "stepSize":50
            }
         },
         {
            "offset":true,
            "position":"right",
            "id":"B",
            "stacked":false,
            "type":"linear",
            "ticks":{
               "autoSkip":true,
               "mirror":false,
               "beginAtZero":false,
               "min":0,
               "stepSize":2
            }
         }
      ]
   }
}
```

## 4) Steps to reproduce

Run the example, check the generated json.

Workaround forced "offset":false in javascript (commented out in code):

```java
barModel.setExtender("testExender);
```
```xml
<h:outputScript target="head">
  function testExender() {
    var options = $.extend(true, {}, this.cfg.config);
    options = {
      "options":{
        "scales": {
          "yAxes":[{
            "offset":false,
          }
          ,
          {
            "offset":false
          }]
        }
      }
    };
    $.extend(true, this.cfg.config, options);
  };
</h:outputScript>
```

## 5) Sample XHTML / Sample bean
See attached project.
primefaces-test-offset.zip

[primefaces-test-offset.zip](https://github.com/primefaces/primefaces/files/4379950/primefaces-test-offset.zip)

**Comment by melloware** [comment]
Bizarrely these 3 lines of code have been there since it was first checked in.
https://github.com/primefaces/primefaces/blob/fcb8ddce0beae94748900eafb7c994a4584bfed8/src/main/java/org/primefaces/component/charts/ChartRenderer.java#L220-L222

Here is current screenshot:
![image](https://user-images.githubusercontent.com/4399574/77533782-dd35c280-6e6d-11ea-8c75-e9034db5b851.png)

**Comment by melloware** [comment]
Screenshot after removing those 3 lines of code.
![image](https://user-images.githubusercontent.com/4399574/77534847-cabc8880-6e6f-11ea-9f8a-2b2490ef8375.png)
