### ISSUE TITLE
SelectCheckBoxMenu: Change AJAX event not working

### ISSUE THREAD

**Issue by tkernstock** [primefaces/primefaces#5730]
# IMPORTANT 

I use p:ajax to call a method after a delay. This worked perfectly until version 8.0. 
For example:
```xml
<p:selectCheckboxMenu id="berufsfelder" value="#{jobsearchPage.jobsuchKriterien.listBerufsfelder}" multiple="true" filter="true" filterMatchMode="startsWith" panelStyle="width:400px">
	<f:selectItems value="#{tabBerufsfeldService.mapTextKey}" />
       <p:ajax update="cmdSave1 cmdSave11 resultcount :stellenangebote" listener="#{jobsearchPage.handleCriteriaChanged}" delay="1500" />
</p:selectCheckboxMenu>
```

## 1) Environment
- PrimeFaces version: 8.0
- Application server + version: Payara 5.184
- Deltaspike 1.8.2
- Omnifaces 3.3
- Affected browsers: FireFox, Chrome, Ege

## 2) Expected behavior
The listener-method should be called after 1500ms

## 3) Actual behavior
The method isn't called anymore

## 4) Steps to reproduce
Try the SelectManyCheckbox demo -> https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml 

The method onItemUnselect is never called in my installation.

## 5) Sample XHTML
I also tried out my delay, adding a single line to the page ->

```xml
<p:selectCheckboxMenu id="multiple" value="#{checkboxView.selectedCities2}" label="Cities" multiple="true" filter="true" filterMatchMode="startsWith" panelStyle="width:250px">
		_**<p:ajax listener="#{checkboxView.handleCriteriaChanged}" delay="1500" />**_
		<p:ajax event="itemUnselect" listener="#{checkboxView.onItemUnselect}" />
		<f:selectItems value="#{checkboxView.cities}" />
</p:selectCheckboxMenu>
```

## 6) Sample bean
Adding one Method to the bean CheckboxView.java- >
```java
   public void handleCriteriaChanged(ValueChangeEvent e) {
    	System.out.println("ChangeEvent called " + e.getNewValue().toString());
    }
```
which isn't called!

**Comment by melloware** [comment]
If I change your code to..
```java
import javax.faces.event.AjaxBehaviorEvent;

public void handleCriteriaChanged(AjaxBehaviorEvent e) {
   System.out.println("ChangeEvent called " + e.toString());
}
```

it works fine.  Are you sure this worked before in PF and if so which is the last version that ValueChanged worked correctly?

**Comment by tandraschko** [comment]
the issue is weird. It says that itemUnselect isn't called but also that change doesn't call the listener?

Facts:
1) the itemUnselect works fine in the showcase
2) AFAIR/AFAIK ValueChangeEvent is only passed to the "valueChangeListener", p:ajax is always a AjaxBehaviorEvent. And ValueChangeEvent doesn't inherit from AjaxBehaviorEvent. So i dont think that ever worked.

**Comment by melloware** [comment]
@tandraschko yes I am getting an error locally blowing up saying AjaxBehaviorEvent is not ValueChangedEvent  So I don't see how this EVER worked I looked back in 7.0 and 6.2 and this change event has never sent a ValueChanged.

**Comment by tkernstock** [comment]
Hi guys,
thank you for the quick reply. 
Rigth now I'm using Primefaces 7.0 and Method works fine with the ValueChangedEvent. You can see it working at https://www.isg.com/jobs/search/ - just change any filterelement.
@Melloware: 
- also if I change to AjaxBehaviour the method isn't called. The same is true for onItemUnselect which is in the original code and works fine on primefaces demo!? 
- as you can see in the link above the code is deployed and working correctly. Here is the code of my backing bean for the xhtml code above:

```
public void onDienstortSelect(NodeSelectEvent e){
	handleCriteriaChanged();
	getTreeModel().setNodesSelected();
}
	
public void onDienstortUnSelect(NodeUnselectEvent e){
	handleCriteriaChanged();
	getTreeModel().setNodesSelected();
}
	
public void handleCriteriaChanged(ValueChangeEvent e){
	handleCriteriaChanged();
}
```

**Comment by tkernstock** [comment]
By the way - the p:ajax is also not working in p:inputText and p:tree

**Comment by tandraschko** [comment]
Please provide us a forked primefaces-test project, everything else is impossible for us to replicate.

**Comment by melloware** [comment]
@tkernstock I tested all of that already and it works fine.

This works just fine.
```xml
                <p:inputText id="firstname" value="#{userView.firstname}">
                    <p:ajax event="keyup" update="out1" delay="1500" />
                </p:inputText>
                <h:outputText id="out1" value="#{userView.firstname}" />
```

And so does your example above once I changed it to an AjaxBehaviorEvent.   So to me its all working fine.

**Comment by melloware** [comment]
@tkernstock Attached is my example.
[pf-5730.zip](https://github.com/primefaces/primefaces/files/4382702/pf-5730.zip)

Run `mvn clean jetty:run-exploded` and navigate to http://localhost:8080/primefaces-test/test.xhtml

You will see the AJAX works fine and wait 1500 ms before firing.

**Comment by melloware** [comment]
Here is a better version including your CheckBoxMenu example working perfectly fine.  
[pf-5730.zip](https://github.com/primefaces/primefaces/files/4382741/pf-5730.zip)

**Comment by tkernstock** [comment]
@melloware 
Meanwhile I created a new project an their it works fine. ??!
I also changed the code in my projekt to AjaxBehaviorEvent - but since also the Textfield and Tree didn't work there was no change - ajax seems to be broken somehow in my project. Mhhhh.

**Comment by melloware** [comment]
Yep you are having some enviroinment issue or LIB issues.  Check your WEB-INF/lib or your server for too many libs etc. I feel like you have a strange conflict going on.

**Comment by tkernstock** [comment]
I will try to update to Deltaspike_1.9 maby there is a problem with 1.9.2. I will let you know if if find out what caused the problem.

**Comment by melloware** [comment]
Please do.  Also make sure its not some weird javascript conflict if you are using any JS libraries not inclduded with PF.

**Comment by tkernstock** [comment]
Well, the problem was primefaces-extensions-8.0.jar. After removing it from the projekt, p:ajax works again. 
Thanx for your help!!

**Comment by melloware** [comment]
OK well now I am curious why??  PFE 8.0 should work with PF 8.0.  Let me try it in my Tester.

**Comment by tkernstock** [comment]
It also doesn't work if I'm readding primefaces-extensions-7.0.jar!

**Comment by melloware** [comment]
What are you adding from PE on your page?

Here is another tester adding PFE8.0 inputPhone on the page.
[pf-5730.zip](https://github.com/primefaces/primefaces/files/4383000/pf-5730.zip)

**Comment by tkernstock** [comment]
[testcase.war.zip](https://github.com/primefaces/primefaces/files/4383255/testcase.war.zip)

I'm using blockUI. But even if I don't use anything p:ajax stops wortking by just adding the jar file.
Since I don't use maven I can only provide an eclipse project. This one runs on Payara 5.184.
[Testcase.zip](https://github.com/primefaces/primefaces/files/4383243/Testcase.zip)

**Comment by melloware** [comment]
That doesn't make any sense.  Maybe report it to the Payara team?  since you can see it works with Jetty and OpenWebBeans I feel like its Payara related.

**Comment by tkernstock** [comment]
Well, I know there maybe other issues on payara/mojarra when changing the server versions, but in this case I only changed the primefaces version and not the server. Mhh. Don't think that payara team will invastigate on that.
Anyway. I will stay on Primefaces 7.0 for the moment.
Thanx for your time and help.
