### ISSUE TITLE
InputNumber: Very slow to load page in Internet Explorer if es6-shim and InputNubmer are used.

### ISSUE THREAD

**Issue by albfernandez** [primefaces/primefaces#5732]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? No . 8.0
- Does it work on the newest sources in GitHub? unknown
- Application server + version: tested in Jetty 9, Payara 4, Wildfy 10. May fail in all servers
- Affected browsers: Internet Explorer 11

## 2) Expected behavior
Page loads almost instantly

## 3) Actual behavior
It loads fast in Firefox, Chrome, others.
It takes about 90 seconds to load in Internet Explorer 11

## 4) Steps to reproduce
Put an ```p:inputNumber``` in a page which uses/loads es6-shim.js.
Open the page in Internet Explorer 11. Wait about 90 seconds to load (Explorer seems to hang but finally loads the page)

Sample project: [primefaces-test-inputnumber_slow_es6shim_ie11.zip](https://github.com/primefaces/primefaces/files/4386661/primefaces-test-inputnumber_slow_es6shim_ie11.zip)

## 5) Sample XHTML
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
        <h:outputScript name="es6-shim.js"></h:outputScript>
    </h:head>
    <h:body>

        <h:form>
        	<p:inputNumber value="#{testInputNumber.example}" />
        </h:form>

    </h:body>
</html>
```

## 6) Sample bean

```java
package org.primefaces.test;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestInputNumber implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer example;
	
	public TestInputNumber() {
		super();
	}

	public Integer getExample() {
		return example;
	}

	public void setExample(Integer example) {
		this.example = example;
	}
	
}
```

**Comment by tandraschko** [comment]
does it also occur with native autonumeric.js?

**Comment by albfernandez** [comment]
autonumeric seems to work fine

```html
<!DOCTYPE html>
<html>
<head>
	<title>Autonumeric test</title>
	<script src="es6-shim.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.5.9"></script>
</head>
<body>

<input id='myNumber' type='text' value="1234.56">

<script type="text/javascript">
new AutoNumeric(document.getElementById('myNumber'));
</script>
</body>

```

**Comment by melloware** [comment]
Can you run the profiler? it will tell you where all the time is spent in Javascript.

**Comment by albfernandez** [comment]
> Can you run the profiler? it will tell you where all the time is spent in Javascript.

Thanks!
I've found the solution. By desing, es6-shim should be the first script loaded and executed, but in the example i've provided it loads after, which causes to this bad behaviour.
Changing the order in native autonumeric triggers the error as well.

Fixed with:
```xml
    	<f:facet name="first">
            <h:outputScript name="es6-shim.js"></h:outputScript>
            <title>PrimeFaces Test</title>
        </f:facet>
```

**Comment by melloware** [comment]
Awesome!  Closing issue.
