### ISSUE TITLE
layoutunit [open] button is invisible

### ISSUE THREAD

**Issue by pangbuddy** [primefaces/primefaces#5741]
## 1) Environment
- PrimeFaces version: 8.0
- Affected browsers:
Chrome Version 80.0.3987.149 (Official Build) (64-bit)
Firefox 74.0 (64 bits)

## 2) Expected behavior

A collapsible layoutunit, it should be displayed a little icon button at a side to reopen the unit when it is collapsed.

## 3) Actual behavior
The open button is available, but it's invisible.

## 4) Steps to reproduce
This issue could be represented at official demo page. please checking at following link.
https://www.primefaces.org/showcase/ui/panel/layout/full.xhtml

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
Layout is actually deprecated and i would not fix it anymore.
WDYT @melloware ?

**Comment by pangbuddy** [comment]
sorry i did not read the official document properly, i will also change my layout with other new components, thanks for your comment.

**Comment by tandraschko** [comment]
ok, then i will close it
