### ISSUE TITLE
Add "global" to p:overlayPanel

### ISSUE THREAD

**Issue by testing138** [primefaces/primefaces#5745]
Hi, 

can you please add the "global" also to p:overlayPanel.
Please find also:
https://forum.primefaces.org/viewtopic.php?f=3&t=61521&sid=ba09b89d2ce6f30c2fb8fc179c9bc374

Thank you

**Comment by tandraschko** [comment]
I think there already is one? 
<p:ajax event="show" global="false" /> ?

**Comment by testing138** [comment]
you mean? This is not working for me:
<p:ajax> Unable to attach behavior to non-ClientBehaviorHolder parent


			`										<p:overlayPanel id="overlayPanel" for="friendshipPanel" global="false"
														dynamic="true" showEvent="mouseover" hideEvent="mouseout"
														dismissable="true">
														
														<p:ajax event="show" global="false" />`

**Comment by tandraschko** [comment]
do you use 8.0? might be a new feature, just checked the docs here:

https://primefaces.github.io/primefaces/8_0/#/components/overlaypanel?id=overlaypanel

**Comment by tandraschko** [comment]
yep, its there
https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/overlaypanel/OverlayPanelBase.java#L32

**Comment by mauromol** [comment]
I'm using PF 8.0. The Ajax behaviour for "show" event is there, however global="false" does not work: the opening of the overlayPanel still triggers the global ajaxStatus.

**Comment by melloware** [comment]
@mauromol have you tried it in 12.0 to see if its something that has already been resolved since 8.0?

**Comment by haraleib** [comment]
I have tried it with PF12 and it also doesnt work. I see "this is marked as not planned". Would be a nice enhancement. Is there quick fix on how I can achieve this?

**Comment by tandraschko** [comment]
`<p:ajax event="show" global="false" />`

must work, otherwise please create a new issue with a reproducer (forked primefaces-test)
