### ISSUE TITLE
DatePicker: timeOnly causes infinite loop

### ISSUE THREAD

**Issue by aligit** [primefaces/primefaces#5748]
## 1) Environment
- PrimeFaces version: 8
- Does it work on the newest released PrimeFaces version?  Non
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source): Non
- Application server + version: Payara 5.201
- Affected browsers: Firefox+ Chrome

## 2) Expected behavior

The timer only is not starting an infinite loop and user can easily set the time

## 3) Actual behavior

After few clicks on the timer an infinite loop is started and the screen become unresponsive

## 4) Steps to reproduce

When trying to set up a datepicker with time only 

## 5) Sample XHTML
```xml
        <ui:decorate template="/fragments/edit.xhtml">
          <p:datePicker
            id="reservationEarliestTime"
            pattern="HH:mm"
            timeOnly="true"
            value="#{instrumentSetting.reservationEarliestTime}">
            <p:ajax
               event="dateSelect"
               listener="#{instrumentSettingManager.reservationEarliestTimeChanged}"
               update="edit"
               process="@this"
               global="false" />
          </p:datePicker>
        </ui:decorate>
```

## 6) Sample bean

```java
    public void reservationEarliestTimeChanged(SelectEvent<LocalTime> event) {
        getInstrumentSetting().setReservationEarliestTime(event.getObject());
        if (getInstrumentSetting().isReservationEarliestLatestTimeInvalid()) {
            getFacesMessagesManager().printError(Messages.get("errorLabel"));
        }
    }
```

**Comment by melloware** [comment]
Confirmed with this reproducer: 
[pf-5748.zip](https://github.com/primefaces/primefaces/files/4416107/pf-5748.zip)

**Comment by melloware** [comment]
OK it looks like its getting into the infinite loop when it calls repeat on the MouseDown.
```javascript
        onTimePickerElementMouseDown: function (event, type, direction) {
            if (!this.options.disabled && event.which === 1) {
                this.repeat(event, null, type, direction);
                event.preventDefault();
            }
        },
```

**Comment by christophs78** [comment]
Think we need to port this PrimeNG-commit: https://github.com/primefaces/primeng/commit/722b46ac71e8e0ac82c68baf0ac2b601a12de676

**Comment by christophs78** [comment]
Hm. There´s already some code which should clean up the TimePicker-timer:
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L1512-L1528

**Comment by christophs78** [comment]
Think this problem is related to the dateSelect-event. Each single increment fire´s this event.
Without dateSelect-event i can´t reproduce this issue.

**Comment by christophs78** [comment]
Yep! This single line causes the issue:
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L2242

**Comment by melloware** [comment]
So we somehow need to figure out if repeat is being held down? and not call DateSelect until the last one?

**Comment by christophs78** [comment]
Yes, something like this.

**Comment by christophs78** [comment]
I´m working on this and try to provide a PR.
