### ISSUE TITLE
Exporter: Switch iText to OpenPDF by LibreOffice

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5749]
URL: https://github.com/LibrePDF/OpenPDF

> OpenPDF is a Java library for creating and editing PDF files with a LGPL and MPL open source license. OpenPDF is the LGPL/MPL open source successor of iText, and is based on a fork, of a fork, of iText 4 svn tag. We welcome contributions from other developers. Please feel free to submit pull-requests and bugreports to this GitHub repository.

Basically they forked the last know good itext version before it went commercial and have been bugfixing and optimizing since.  The license is friendly and I feel better using an up to date library vs a 10 year old iText 2.1.7

I have tested and it is 100% backwards compatible.

- [x] Update lib
- [x] Update showcase
- [x] Update WIKI

**Comment by melloware** [comment]
Showcase PR: https://github.com/primefaces/primefaces-showcase/pull/137

**Comment by kukel** [comment]
Some time ago (several years) I created an 'exporter' that was based on https://github.com/flyingsaucerproject/flyingsaucer. It could even 'export' many parts of full pages (e.g. forms). Exporting datatables also exported images in cells, background colors and much more. Effectively all you need is to server side render the (part of) the page and pass the html (with css etc) on to the flyingsaucer renderer. I'll try do dig it up. Would make a nice addition.

**Comment by melloware** [comment]
@kukel now that sounds like a great Extensions addition.
