### ISSUE TITLE
TextEditor:  Dropping CSS Class from Paragraph Tags

### ISSUE THREAD

**Issue by SteveIreland** [primefaces/primefaces#5756]
Similar to #5283,  The use of the Align method applies a class of either "ql-align-right" or "ql-align-center" to the paragraph tag.

HTMLSanitizer then appears to be responsible for stripping the class attribute from the tag when I save the form. 

I tested it using the latest PrimeFaces Showcase demo and it's not working there either.  (If you click on the Submit button the tags are dropped from the popped up dialog.)

And the util/HTMLSanitizer code does not appear to be making an allowance for the P tag.

Suggestions for a quick workaround would be greatly appreciated.  I haven't had to make my own changes to PrimeFaces but if I gotta go there then I gotta learn to go there.

**Comment by melloware** [comment]
@SteveIreland This looks like it going to be a PrimeFaces code fix.  If you are using PrimeFaces 8.0 you can turn the `secure` attribute to `false` and that stops using the Sanitizer.

if you can't upgrade to PF8.0 unfortunately this will require a similar fix as #5283

**Comment by SteveIreland** [comment]
Thanks!  I will upgrade to PF8.

**Comment by SteveIreland** [comment]
I upgraded to PF8 and applied the secure="false" attribute but owasp-java-html-sanitizer was still wiping out the class names.

It turns out that it is necessary to both remove owasp-java-html-sanitizer from the pom AND set secure="false" on all occurrences of textEditor.

The secure="false" flag only prevents the missing owasp-java-html-sanitizer artifact system failure from happening.  But that works for me for now.  Looking forward to PF9.

**Comment by melloware** [comment]
Ahh yes forgot to mention it checks the classpath too.  Sorry!
