### ISSUE TITLE
PanelMenu: accessibility

### ISSUE THREAD

**Issue by LianeK** [primefaces/primefaces#576]
Please add keyboard accessibility and ScreenReader support for PanelMenu

**Comment by tandraschko** [comment]
Could you please test it again?
@melloware WDYT? We have aria attributes on the panelmenu, i just don't have a screenreader

**Comment by melloware** [comment]
@tandraschko I agree the aria roles all look correct and and i was able to TAB and press ENTER to expand and contract menus so the keyboard accessibility looks OK too.  I think its safe to close.
