### ISSUE TITLE
Carousel : firstVisible attr not working in v8+

### ISSUE THREAD

**Issue by haiderali-456** [primefaces/primefaces#5765]
Carousel : firstVisible attr not working in v8+

have any alternate solution for **firstVisible** in latest versions8+ of primeng

but it's working fine in primeng version6

**Comment by tandraschko** [comment]
Still PrimeNG?
Your issue is invalid without description and sample.

**Comment by haiderali-456** [comment]
@tandraschko  could u pls help me on this?

**Comment by tandraschko** [comment]
as i said, this is not for PrimeNG! PrimeNG is here: https://github.com/primefaces/primeng

**Comment by haiderali-456** [comment]
https://github.com/primefaces/primeng/blob/master/src/app/components/carousel/carousel.ts

**Comment by stolp** [comment]
@haiderali-456 You should go to https://github.com/primefaces/primeng/issues with your problems.
