### ISSUE TITLE
deactivate option in p:autoComplete

### ISSUE THREAD

**Issue by chrisu86** [primefaces/primefaces#577]
It would be very nice, if there was a "deactivate" option in p:autoComplete tag.
I want to be able to activate/deactivate the autocomplete behavior by a Bean value.
At the Moment i have to do something like this:

```
<p:autoComplete widgetVar="myAutocomplete"/>

<h:panelGroup rendered="#{!myBean.activeAutocomplete}">
   <script type="text/javascript">
    PF('myAutocomplete').deactivate();
   </script>
</h:panelGroup>
```

**Comment by cagataycivici** [comment]
Why don't you use disabled="true".

**Comment by chrisu86** [comment]
I dont want to disable the input field, i just want to turn off the autocomplete feature...
