### ISSUE TITLE
Provide a way to disable the fileUpload component while upload is in progress

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#578]
It would be useful in many cases to disable the fileUpload component while upload is in progress. The upload process may take a while and processing the uploaded file may take some more time. The progress indicator is not very meaningful and the user may think the upload is hanged and try to click on the choose button to select the file again (note I'm using fileUpload in advanced mode, auto=true). This can cause issues and/or require proper synchronization on the server side.

I tried to find a way to disable the component while upload is in progress, by hooking onstart and oncomplete. However the documentation does not say anything about any client-side API to do this. I looked and the PF JS code and experimented with something like this:

```
<p:fileUpload 
    fileUploadListener="#{bean.handleUpload}"
    multiple="false" auto="true" sizeLimit="5000000"
    widgetVar="myFileUpload"
    onstart="PF('myFileUpload').disableButton(PF('myFileUpload').chooseButton)"
    oncomplete="PF('myFileUpload').enableButton(PF('myFileUpload').chooseButton)" />
```

This partially works, but apart from the fact I'm using non-documented functions (which may break after a PF update), the choose button, even if disabled, is still clickable (and opens the file browse dialog).

So, an "official" way to do this would be useful, either by an attribute like `disableOnUpload="true"` (default false) or by providing an enable/disable client-side API to do this.

**Comment by kukel** [comment]
or use some `p:blockui` ?

**Comment by cagataycivici** [comment]
Workaround is not bad, will reopen if we get more requests.

**Comment by mauromol** [comment]
I can't provide an actual use case, but I can state for sure that from my tests and experiments I did some time ago, the `p:blockui` does not perform the job, at least not in a way it's actually useful. I mean, the user can trigger a double click on the upload component before the blockui can actually block further interactions. So, if the final purpose is to avoid double clicks, blockui is not the solution. This is indeed a real pain to properly handle.

**Comment by mauromol** [comment]
Could you please reopen and/or explain how to use the `<p:blockui>` with `<p:fileUpload>`? If I set the `<p:fileUpload>` id into `<p:blockui>` `trigger` attribute, the block is not triggered.
I'm using a standard (`mode="advanced"`) `<p:fileUpload>` with `auto="true"`.

**Comment by mauromol** [comment]
Ok, I managed to get it working with `onstart` and `oncomplete` on the `<p:fileUpload>` and the `<p:blockUI>` JS API... I still believe this should be much easier to set up...
