### ISSUE TITLE
DataTable: scrollHeight=100% does not take position of p:datatable related to parent into account

### ISSUE THREAD

**Issue by kukel** [primefaces/primefaces#5780]
Please tag as enhancement and assign to me

## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? No Version? 8.0
- Does it work on the newest sources in GitHub? No
- Application server + version: N/A
- Affected browsers: N/A

## 2) Expected behavior

If I have a container with a height of e.g. 400px and this container contains  some text and a datatable with `scrollHeight=100%`, the resulting content of the container **will not** overflow. 

## 3) Actual behavior

If I have a container with a height of e.g. 400px and this container contains a some text and a datatable with `scrollHeight=100%`, the resulting content of the container **will** overflow. 

## 4) Steps to reproduce

I'll create a testcase while creating a solution

## 5) Sample XHTML

I'll create a testcase while creating a solution

## 6) Sample bean

I'll create a testcase while creating a solution

## 7) Cause/Fix

This is 'caused' by the datatable not taking other content in the container into account. Solving this for all cases is problematic, but the case where the datatable is already positioned lower in the container due to preceding (visualy, not xhtml wise) content. This can be solved [in the adjustScrollHeight function in datatables.js](https://github.com/primefaces/primefaces/blob/34680f85c5ab5a75796623abbcb34ffa310b0ce8/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L1155)

## 8) Discussion
 - Keep using `scrollHeight="100%"`  for this behaviour and maybe regressing some existing cases
 - Introduce a new uom (e.g. rpch, remaining parent container height)
 - ... ?

**Comment by melloware** [comment]
It would be nice to handle both scenarios?  like scrollheight="100%" or scrollHeight="33vh" or scrollHieght="50pc" for 50% of remaining parent container height?

**Comment by kukel** [comment]
Yes, all are options... Do we want to keep the 100% working like it does now? For backwards compatibility?

**Comment by melloware** [comment]
feels like the safe move?

**Comment by melloware** [comment]
Mentioned on the forums too: https://forum.primefaces.org/viewtopic.php?f=3&t=70076

**Comment by melloware** [comment]
@kukel are you still around?  are you still interested donating a PR for this or should I close it?

**Comment by jepsar** [comment]
Haven't seen him on Stackoverflow for a while

**Comment by melloware** [comment]
Agreed nor seen on SO or the forums for over 18 months

**Comment by jmlaya** [comment]
Hi all, what is the workaround for this issue?
