### ISSUE TITLE
Task: Remove FontAwesome 4.7

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5781]
Since FontAwesome 5 can be used and users can keep it up to date with whatever version they choose we should remove FontAwesome 4.7 from core PrimeFaces JAR.

Plus PrimeTek has been going with PrimeIcons so it makes even more sense to remove it.

See: https://primefaces.github.io/primefaces/8_0/#/core/fonticons

Vote up or down here if your like or dislike the idea.

**Comment by christophs78** [comment]
AFAIK PrimeTek uses FontAwesome-Icons within their Premium-Theme. They may need to make some minor update to them. (Update docu, bundle FontAwesome with the theme, ???)

**Comment by melloware** [comment]
@christophs78 I think they have switched them all to use PrimeIcons?  I could be wrong.

**Comment by NicolaIsotta** [comment]
Apollo Remastered still uses FontAwesome

**Comment by christophs78** [comment]
Same for Sibera. (the newest premium-theme)
![grafik](https://user-images.githubusercontent.com/10461942/78985558-5ea57a00-7b29-11ea-8346-1a53d6888cf3.png)

**Comment by melloware** [comment]
That should be fine as long as you include the shims CSS it would be a drop in replacement right?
```xml
<h:outputStylesheet library="webjars" name="font-awesome/5.12.0/css/v4-shims.min-jsf.css" />
```

**Comment by tandraschko** [comment]
This decission is up to primetek

**Comment by melloware** [comment]
FontAwesome should be considered deprecated for PF10 and will be removed from the JAR in PF11

**Comment by mertsincan** [comment]
Yes, deprecated ;) We can remove Font Awesome icons from all Premium layouts up to version PF11.
