### ISSUE TITLE
Datatable: RTL Column resize issue

### ISSUE THREAD

**Issue by NRanjbaran** [primefaces/primefaces#5782]
I'm using Primefaces version 8.0.
Resize column in datatable when direction is RTL has problem. When I drag the resizer to the right side then the column size increases, but because of the direction is RTL that column should be smaller.
In other words, when I drag the resizer to the right, the column gets larger to the left.

I solve this problem on this file : 
path : primefaces-8.0.jar\META-INF\resources\primefaces - ZIP archive
file : components.js
In first resizer method, replace this line : 
k = (l.position.left - l.originalPosition.left), e = (d.width() + k), g = (f.width() - k)
with : 
k = (l.position.left - l.originalPosition.left), e = (d.width() - k), g = (f.width() + k)

please solve this problem on RTL direction,
Thanks

**Comment by tandraschko** [comment]
Please follow the issue template and provide all infos like a example to replicate

**Comment by NRanjbaran** [comment]
```xml
<p:dataTable id="rtlTable" var="car" value="#{view.cars}" resizableColumns="true" dir="rtl">
    <p:column headerText="Id">
        <h:outputText value="#{car.id}" />
    </p:column>
    <p:column headerText="Year" filterBy="#{car.year}">
        <h:outputText value="#{car.year}" />
    </p:column>
    <p:column headerText="Brand">
        <h:outputText value="#{car.brand}" />
    </p:column>
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
</p:dataTable>
```

**Comment by tandraschko** [comment]
Please check our issue template and follow all steps - otherwise it's hard to replicate and the most people wont invest time in your issues without all informations and examples.

**Comment by melloware** [comment]
Reproducible test case:
[pf-5782.zip](https://github.com/primefaces/primefaces/files/4455857/pf-5782.zip)

**Comment by melloware** [comment]
@NRanjbaran even with your fix I don't think it behaves quite right. I think there is a lot more to it than just your fix above.

**Comment by melloware** [comment]
@NRanjbaran What RTL language are you using? We are looking for translators for RTL languages: See this WIKI: https://github.com/primefaces/primefaces/wiki/Locales

We want to add these files to the core of PF.
