### ISSUE TITLE
Widgets: Missing this._super(cfg) call in init method of a few widgets

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#5787]
While working on the type declarations for the JavaScript API, I noticed a few widgets are missing the call to `this._super(cfg)` in the init method. Is that intentional? The [init method](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.widget.js#L74) from the BaseWidget doesn't seem to be doing anything harmful

This results in a few properties such as `widgetVar` and `jq` not being set (violating the Liskov substitution principle unless those properties are made optional in `BaseWidget`), and repeats some boilerplate such as `this.jqId = PrimeFaces.escapeClientId(this.id)`.

Following widgets are missing the super call:

- [BlockUI](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js#L7)
- [DefaultCommand](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js#L7)
- [Draggable](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/dragdrop/dragdrop.js#L7) (`this.jq` is set to the target, should probably use `this.jqTarget`  for that)
- [Droppable](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/dragdrop/dragdrop.js#L44) (`this.jq` is set to the target, should probably use `this.jqTarget`  for that)
- [Effect](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/effect/effect.js#L7)
- [Growl](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/growl/growl.js#L7)
- [KeyFilter](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/keyfilter/1-keyfilter.js#L9)
- [Paginator](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js#L4) (pretty strange - `this.id` is an array of the IDs of all paginators [such as the top and bottom of a data list] which is incompatible with the `BaseWidget` super type; setting `id` to the first id and adding `this.extraIds` could help)
- [Poll](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/poll/poll.js#L7)
- [Resizable](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/resizable/resizable.js#L7)
- [Tooltip](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js#L7)
- [Watermark](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/watermark/watermark.js#L7)

**Comment by tandraschko** [comment]
I dont think its by design, just never migrated. A PR is very Welcome :)

**Comment by melloware** [comment]
I have noticed this too and just figured that somewhere along the way PF refactored more code into BaseWidget and just never hit all the components.  PR is very welcome.
