### ISSUE TITLE
Charts: Chart export wrong image when legends with more then one column

### ISSUE THREAD

**Issue by robertoferreirajrr** [primefaces/primefaces#5789]
Charts: Chart export wrong image when legends with more then one column

![chart17cm (17)](https://user-images.githubusercontent.com/264819/79091660-7e54c200-7d24-11ea-81d9-4d8334735ac2.png)

## 1) Environment
- PrimeFaces version: 8.0
- Not work on the newest released PrimeFaces version.
- Not work on the newest sources in GitHub.
- Glassfish 5.0.1:
- Affected browsers: All them

## 2) Expected behavior

Expected right color legend positions.

## 3) Actual behavior

All color legends in same display block

## 4) Steps to reproduce

Just put legends with more then one column and then try to export image of charts.

## 5) Sample XHTML

`<p:chart id="chart" model="#{relatorio.graficoLeituraDoInstrumento}"  type="line" style="height: 600px"  widgetVar="lineChart" />`

And then click button:

```
 <script type="text/javascript">
                            function exportChart() {
                                $('#tabsInstrInf\\:saidaimagem').empty().append(PF('lineChart').exportAsImage());
                                PF('dlgG').show();
                            }
 </script>
```

## 6) Sample bean

`[Chartmodel].setLegendCols(3);`

**Comment by melloware** [comment]
Related to: https://github.com/primefaces/primefaces/issues/4967 ???

**Comment by robertoferreirajrr** [comment]
Hey Guys!
Only to your acknowledgment: This issue persists since Primefaces version 7. I wait between versions, this fix, to update my lib on project. Sorry for not report. A time ago I reported similar issue: [4967](https://github.com/primefaces/primefaces/issues/4967), the fix implemented in this issue fix one column legend export problem, but when legends have more than one column a new problem rises.

**Comment by melloware** [comment]
Unfortunately the JQPlot library is very old and its not really maintained anymore. The newer ChartsJS is still and active and vibrant library.  SO I am sure how much effort this ticket will get unless you are a PRO customer.

**Comment by robertoferreirajrr** [comment]
> Unfortunately the JQPlot library is very old and its not really maintained anymore. The newer ChartsJS is still and active and vibrant library. SO I am sure how much effort this ticket will get unless you are a PRO customer.

I understand... I have sent a quote request for this... thanks for your answer...

Have some kind of prediction when this library will be deprecated and remove from Primefaces?

This issue is Reported in Jqplot git issues too: https://github.com/jqPlot/jqPlot/issues/186

Like reported seems that Jqplot have a serie of issues when using jQuery > 3.2.1.

Best regards =)

**Comment by melloware** [comment]
I don't work for PrimeTek so I can't answer when that will be deprecated but i have a feeling so many customers used these original charts they won't deprecate it anytime soon, but the pain is you have to live with these quirks.

**Comment by robertoferreirajrr** [comment]
I have implemented a fix in function _jqpToImage, works for me:

![chart17cm (39)](https://user-images.githubusercontent.com/264819/79126490-686fed00-7d76-11ea-88ef-edcc5bfa106c.png)


```
$(el).find('div.jqplot-table-legend-swatch-outline').each(function () {
     // get the first div and stroke it
     var elem = $(this);
     newContext.strokeStyle = elem.css('border-top-color');

     newContext.strokeStyle = elem.css('border-top-color');


    var containerOffset = elem.parent().parent().offset();

    var rowOffset = elem.offset();
    console.log(containerOffset.top);

    var position = {
               top: ((rowOffset.top - containerOffset.top) * 5) == 0 ? 3 : (rowOffset.top - containerOffset.top) * 5,
               left: rowOffset.left - containerOffset.left
                              };
    console.log(position);

    var l = left + position.left;
    var t = top + position.top;
    //newContext.strokeRect(l, t, elem.innerWidth(), elem.innerHeight());

    // now fill the swatch

    l += parseInt(elem.css('padding-left'), 10);
    t += parseInt(elem.css('padding-top'), 10);
    var h = elem.innerHeight() - 2 * parseInt(elem.css('padding-top'), 10);
    var w = elem.innerWidth() - 2 * parseInt(elem.css('padding-left'), 10);


    var swatch = elem.children('div.jqplot-table-legend-swatch');
    newContext.fillStyle = swatch.css('background-color');
    newContext.fillRect(l, t, w, h);
    console.log(t);
});
```
Explanation:

position() of a div in a td, the position would be relative to the table. Since 3.3.0+, the position is relative to the td, so that all swatches have a position of 0/0 and lay over each other. I have used parent() method to get reference of table, after that I store relative positions in a var named "position" and use them in l and t;

**Comment by melloware** [comment]
Did you report this to PRO or do you want me to submit a PR with your proposed fix?

**Comment by robertoferreirajrr** [comment]
> Did you report this to PRO or do you want me to submit a PR with your proposed fix?

A PR with proposed fix would be great!
tks @melloware

**Comment by melloware** [comment]
Please review my PR.

**Comment by robertoferreirajrr** [comment]
> Please review my PR.

All right to me! Awesome! =) tks @melloware.
Best regards!
