### ISSUE TITLE
CSP: DefaultCommand Failing

### ISSUE THREAD

**Issue by nokiajavi** [primefaces/primefaces#5790]
When I use in a commandButton in the oncomplete method, the javascript function handleModalRequest (xhr, status, args, 'dialogWidget') and I have CSP enabled, the variable args says it is undefined, I use that variable to get the value of the attribute validationFailed to know if the validations have failed not to close the dialog or any variable sent to it by ajax.

## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Apache Tomcat 9 + JSF 2.3.2
- Affected browsers: All

## 2) Expected behavior
When I use a javascript function to get the validation errors of ajax requests and I use the parameters xhr, status, args in this javascript method, the variable args must be defined and with the attribute validationFailed to true or false, depending on whether they have occurred validation errors or not when CSP is enabled.

## 3) Actual behavior
When I use a javascript function to get validation errors from ajax requests and use xhr, status, args parameters in that javascript method, args variable is always undefined when CSP is enabled.

## 4) Steps to reproduce
0. Enable CSP
1. Create a dialog with an inputText with the attribute required = "true" 
2. Place a p:commandbutton inside the dialog and enter the JS function: handleModalRequest (xhr, status, args, 'dialogWidget') in the oncomplete attribute where dialogWidget is the value of the dialog widgetvar attribute.
3. Open the dialog and press **ENTER** inside the text field.
4. The browser displays the error causing the dialog to close:
`index.xhtml:39 Uncaught TypeError: Cannot read property 'validationFailed' of undefined
    at handleModalRequest (index.xhtml:39)
    at Object.onco (index.xhtml:47)
    at Object.<anonymous> (VM8 core.js.xhtml:18)
    at c (VM7 jquery.js.xhtml:2)
    at Object.fireWith [as rejectWith] (VM7 jquery.js.xhtml:2)
    at l (VM7 jquery.js.xhtml:2)
    at Object.abort (VM7 jquery.js.xhtml:2)
    at Object.abortAll (VM8 core.js.xhtml:18)
    at VM8 core.js.xhtml:18
    at dispatch (VM7 jquery.js.xhtml:2)`

The line where it says it fails is: if (args.validationFailed) {
`<script type="text/javascript" nonce="NzU3ZTNlNjUtZGI4Mi00NzA2LWI5ZWItNzQwY2FjMzY2M2Iz">
			function handleModalRequest(xhr, status, args, modal) {
				if (args.validationFailed) {
					PF(modal).jq.effect("shake", {
						times : 5
					}, 100);
				} else {
					PF(modal).hide();
				}
			}
	</script>`

And this is caused by the core.js file showing the following error:
`TypeError: Cannot read property 'requestContent' of undefined`
## 5) Sample XHTML
```
<h:form>
<p:commandButton ajax="true" oncomplete="PF('dialog').show()" value="MOSTRAR DIALOGO"/>
</h:form>
	<p:dialog widgetVar="dialog">
        <h:form id="form1">
		    <h:panelGrid columns="3" cellpadding="5">
		        <h:outputLabel for="name" value="Name:" style="font-weight:bold"/>
		        <p:inputText id="name" required="true"/>
		    </h:panelGrid>
		    <p:commandButton value="Button1" id="btn1" onclick="PF('dialog').hide()"/>
		    <p:commandButton value="Button2" id="btn2" oncomplete="handleModalRequest(xhr, status, args, 'dialog');"/>
		    <p:defaultCommand target="btn2" />
		</h:form>
	</p:dialog>
	<script type="text/javascript">
			function handleModalRequest(xhr, status, args, modal) {
				console.log(args);
				if (args.validationFailed) {
					PF(modal).jq.effect("shake", {
						times : 5
					}, 100);
				} else {
					PF(modal).hide();
				}
			}
	</script>
```

## 6) Sample bean

N/A

**Comment by tandraschko** [comment]
can you check it @melloware ?

**Comment by melloware** [comment]
Yep let me check it.

**Comment by melloware** [comment]
Attached is a test project:
[pf-5790.zip](https://github.com/primefaces/primefaces/files/4474980/pf-5790.zip)

I can't reproduce the issue.  Run "mvn clean jetty:run-exploded" and then navigate to:
http://localhost:8080/primefaces-test/test.xhtml

@nokiajavi can you please try?

**Comment by nokiajavi** [comment]
I have downloaded the project @melloware  and started apache tomcat and if I reproduce the error

Attach gif: https://gifyu.com/image/lvzv

maybe an error with apache tomcat?

**Comment by melloware** [comment]
not with tomcat... `mvn clean jetty:run-exploded`

**Comment by melloware** [comment]
Could be your Mojarra version?

**Comment by nokiajavi** [comment]
> not with tomcat... `mvn clean jetty:run-exploded`

same error running with jetty. I have used the pom you have sent me. I see you don't have the specified mojarra version.

**Comment by melloware** [comment]
it works 100% fine for me with that version. It uses Mojarra 2.2.20 by default.

What browser are you using?

**Comment by nokiajavi** [comment]
Yes mojarra 2.2.20 in this proyect, but in my proyect I use mojarra 2.3.2 Google Chrome

Log tomcat:
INFORMACIÓN: Inicializando Mojarra 2.3.2 ( 20170627-2139 e63598abf2ed2bb1a24674f308a734e0dce18a72) para el contexto '/nice-looking-jsf-apps-with-prime-faces-7'
abr 14, 2020 2:22:11 PM com.sun.faces.spi.InjectionProviderFactory createInstance
INFORMACIÓN: JSF1048: hay presentes anotaciones PostConstruct/PreDestroy.  Los métodos de beans administrados marcados con estas anotaciones procesarán dichas anotaciones.
abr 14, 2020 2:22:14 PM org.primefaces.webapp.PostConstructApplicationEventListener processEvent
INFORMACIÓN: Running on PrimeFaces 9.0-SNAPSHOT
abr 14, 2020 2:22:14 PM org.primefaces.extensions.application.PostConstructApplicationEventListener processEvent
INFORMACIÓN: Running on PrimeFaces Extensions 8.0

**Comment by melloware** [comment]
ok then run with `mvn clean jetty:run-exploded -Pmojarra23` and that runs with Mojarra 2.3.14

**Comment by melloware** [comment]
Looks like you have 2 PrimeFaces loaded 8.0 and 9.0-SNAPSHOT?  Are you having LIB issues?

**Comment by nokiajavi** [comment]
> Looks like you have 2 PrimeFaces loaded 8.0 and 9.0-SNAPSHOT? Are you having LIB issues?

PF9 an PFE 8.0

**Comment by melloware** [comment]
OH that is OK.  OK try it with `mvn clean jetty:run-exploded -Pmojarra23`

**Comment by nokiajavi** [comment]
Tested with profile and same error

**Comment by melloware** [comment]
Works perfectly fine for me in Chrome.

**Comment by nokiajavi** [comment]
[PruebasPF9.zip](https://github.com/primefaces/primefaces/files/4475208/PruebasPF9.zip)
I attach my eclipse test project

**Comment by nokiajavi** [comment]
I use:

`<dependency>
		    <groupId>org.glassfish</groupId>
		    <artifactId>javax.faces</artifactId>
		    <version>2.3.2</version>
		</dependency>`

**Comment by melloware** [comment]
I just did the following:

1. Downloaded your project above.
2. Change Mojarra to 2.3.2 version you are using.
3. ran `mvn clean jetty:run-exploded -Pmojarra23`
4. Works perfectly fine in Chrome.

**Comment by nokiajavi** [comment]
If that is rare, do you know what the problem may be?

**Comment by melloware** [comment]
well until i can reproduce it I don't see an actual problem.  You have to be able to prove it witha reproducer.

**Comment by nokiajavi** [comment]
ok thanks, i will try to see the problem to see if i can reproduce it. Thank you very much

**Comment by nokiajavi** [comment]
@melloware When you have performed the tests, to send the dialog form, you have pressed the enter key of the keyboard instead of the dialog button right? It's just that with the dialog button it works well it's just when you press intro It doesn't work 

Thank you.

**Comment by melloware** [comment]
Ahh there it is.  Nope i was always pressing the button.

**Comment by nokiajavi** [comment]
ohh thank goodness you were able to reproduce it, I was ready to shoot myself with thousands of tests and version changes. Thank you very much.

**Comment by melloware** [comment]
OK I don't quite understand why but in forms.defaultcommand.js to execute the default command it is finding your button and clicking it.
```javascript
if (!$this.jqTarget.is(':disabled, .ui-state-disabled')) {
      $this.jqTarget.click();
}
```

However the jquery `click();` trigger is not behaving the same as me physically clicking the button.

**Comment by melloware** [comment]
And debugging the returned XHR object is:
```
xhr: "abort"
status: "abort"
args: undefined
modal: "dialog"
```

**Comment by nokiajavi** [comment]
From the tests I have done, I can tell you that with CSP disabled in Primefaes 8 it works and with Primefaces 7 and CSP enabled as well.

**Comment by melloware** [comment]
Yep its definitely CSP related it is just not obvious why other that Jquery click is not being treated the same as a mouse click on the button.

primefaces 7 did not have CSP.  It is introduced in 8. So in 7 its the same as running 8 with CSP=false.

**Comment by nokiajavi** [comment]
Yes, Primefaces 7 not have CDP, sorry.
I don't know if it will be related to a bug that was corrected in Primefaces 7, I had to put this in my code:
```

$ .extend ($ .ui.keyCode, {
NUMPAD_ENTER: 108
});
```

Because if I did not put it when I selected from the browser's autocomplete the values, this would execute the action of the defaultCommand button

**Comment by melloware** [comment]
I don't think that has anything to do with it. That is this ticket: https://github.com/primefaces/primefaces/issues/3615

**Comment by nokiajavi** [comment]
Well, I don't know more things right now, I'm sorry. I hope you can solve it. Many thanks for your work

**Comment by melloware** [comment]
Might need @tandraschko help here on this one

**Comment by nokiajavi** [comment]
@melloware For the help, I noticed that when the enter key is pressed, it looks like it's running a non ajax request, instead of ajax causing the page to be reload and the dialog obviously closes.

**Comment by melloware** [comment]
Good observation it is like the jq.click() is somehow not doing an AJAX call its just submitting the button.

**Comment by melloware** [comment]
Can you do me a favor?  Add the following code to a JS file that you load after PF.

```javascript
PrimeFaces.widget.DefaultCommand.prototype.init = function(cfg) {
    this.cfg = cfg;
    this.id = this.cfg.id;
    this.jqId = PrimeFaces.escapeClientId(this.id);
    this.jqTarget = $(PrimeFaces.escapeClientId(this.cfg.target));
    this.scope = this.cfg.scope ? $(PrimeFaces.escapeClientId(this.cfg.scope)) : null;
    var $this = this;

    // container support - e.g. splitButton
    if (this.jqTarget.is(':not(:button):not(:input):not(a)')) {
        this.jqTarget = this.jqTarget.find('button,a').filter(':visible').first();
    }

    //attach keypress listener to parent form
    var closestForm = this.jqTarget.closest('form');
    closestForm.off('keydown.' + this.id).on('keydown.' + this.id, {
        scopeEnter: false
    }, function(e, data) {
        var keyCode = $.ui.keyCode;

        data = data || e.data;
        if (($this.scope && data.scopeEnter && data.scopeDefaultCommandId === $this.id) ||
            (!$this.scope && !data.scopeEnter && (e.which == keyCode.ENTER))) {
            //do not proceed if target is a textarea,button or link
            if ($(e.target).is('textarea,button,input[type="submit"],a')) {
                return true;
            }

            if (!$this.jqTarget.is(':disabled, .ui-state-disabled')) {
                var clickEvent = $.Event("click");
                clickEvent.preventDefault()
                $this.jqTarget.trigger(clickEvent);
            }
            e.preventDefault();
            e.stopImmediatePropagation();
        }
    });

    if (this.scope) {
        this.scope.off('keydown.' + this.id).on('keydown.' + this.id, function(e) {
            var keyCode = $.ui.keyCode;
            if (e.which == keyCode.ENTER) {
                closestForm.trigger(e, {
                    scopeEnter: true,
                    scopeDefaultCommandId: $this.id
                });
                //e.preventDefault();
                e.stopPropagation();
            }
        });
    }

    this.removeScriptElement(this.id);
}
```

**Comment by nokiajavi** [comment]
Okay without problems, Tomorrow as soon as I get to work I try it and tell you if it works. Thanks a lot

**Comment by nokiajavi** [comment]
it works perfectly! what cracks! Thank you very much for everything.

**Comment by melloware** [comment]
Thanks for testing.  I explained the issue and what was happening in the PR: https://github.com/primefaces/primefaces/pull/5797

If you are curious.

**Comment by mertsincan** [comment]
Hi @melloware, 
Is null check required for PrimeFaces.csp in the following code?
```
$this.jqTarget.trigger(PrimeFaces.csp.clickEvent());
```

**Comment by melloware** [comment]
No it should not be necessary.  The old code did this.
```javascript
$this.jqTarget.click();
```
In Jquery 3.0 world that should be this.
```javascript
$this.jqTarget.trigger('click');
```

Which can also be done by creating the Jquery event first like this
```javascript
var event = $.Event( "click" );
$this.jqTarget.trigger(event );
```

So the PrimeFaces.csp.clickEvent always returns either the normal `click` event or a `click` event with the preventDefault enabled if we are in CSP mode.

**Comment by nokiajavi** [comment]
Good @melloware I have seen a behavior of a component that I think is caused by the p: defaultCommand also, I tell you and if you see that it is related or you do not tell me if I put the issue or not.

the p: selectOneMenu component, when pressing ENTER KEY on a value in the list, the action of the button associated with the defaultCommand is executed, this only happens if the component does not have the filter = "true" property. 
If there is no defaultCommand inside the form, the component works correctly.

Example code that produces the sending form when pressing ENTER KEY:
```
<h:form id="form">
		<p:selectOneMenu>
			<f:selectItem itemValue="1" itemLabel="uno"/>
			<f:selectItem itemValue="2" itemLabel="dos"/>
			<f:selectItem itemValue="3" itemLabel="tres"/>
			<p:ajax event="change"></p:ajax>
		</p:selectOneMenu>
		
		<p:defaultCommand target="boton1"></p:defaultCommand>
		<p:inputText id="input" required="true" label="INPUT" />
		<p:messages id="mesinput" showDetail="true" showSummary="false"/>
		
		<p:commandButton id="boton1" ajax="true" process="@form" update="@form" validateClient="true" value="BOTON"></p:commandButton>
	</h:form>
```

Example code that does NOT send form when pressing ENTER KEY:
```
<h:form id="form">
		<p:selectOneMenu filter="true" filterMatchMode="startsWith">
			<f:selectItem itemValue="1" itemLabel="uno"/>
			<f:selectItem itemValue="2" itemLabel="dos"/>
			<f:selectItem itemValue="3" itemLabel="tres"/>
			<p:ajax event="change"></p:ajax>
		</p:selectOneMenu>
		
		<p:defaultCommand target="boton1"></p:defaultCommand>
		<p:inputText id="input" required="true" label="INPUT" />
		<p:messages id="mesinput" showDetail="true" showSummary="false"/>
		
		<p:commandButton id="boton1" ajax="true" process="@form" update="@form" validateClient="true" value="BOTON"></p:commandButton>
	</h:form>
```

Thanks!

**Comment by melloware** [comment]
I would create a new issue, I think that is a bug in SelectOneMenu not trapping the ENTER key.

**Comment by nokiajavi** [comment]
Created #5889
