### ISSUE TITLE
Datatable: When disabled, remove checked items

### ISSUE THREAD

**Issue by wagneresa** [primefaces/primefaces#5796]
## 1) Environment
- PrimeFaces version: 7 and 8
- Application server + version: Wildlfy 14 or greather
- Affected browsers: All

## 2) Expected behavior
Come marked and disabled the datatable lines

## 3) Actual behavior
All lines are disabled and unchecked
..

## 4) Steps to reproduce
fill the selection property with some items
.. 

## 5) Sample XHTML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<h:body>
	<h:form id="form">

			<p:dataTable id="checkboxDT" var="car" value="#{bemVindoAction.cars}"
						 selection="#{bemVindoAction.selectedCars}" rowKey="#{car.id}"
						 style="margin-bottom:0" disabledSelection="true">

				<f:facet name="header">
					Checkbox
				</f:facet>

				<p:column selectionMode="multiple" style="width:32px;text-align:center"  selectRow="false"/>

				<p:column headerText="Id" selectRow="false">
					<h:outputText value="#{car.id}"/>
				</p:column>
				<p:column headerText="Year" selectRow="false">
					<h:outputText value="#{car.year}"/>
				</p:column>
				<p:column headerText="Brand" selectRow="false">
					<h:outputText value="#{car.brand}"/>
				</p:column>
				<p:column headerText="Color" selectRow="false">
					<h:outputText value="#{car.color}"/>
				</p:column>
				<f:facet name="footer">
					<p:commandButton process="checkboxDT" update="#{p:resolveFirstComponentWithId('multiCarDetail', view).clientId}"
									 icon="pi pi-search" value="View" oncomplete="PF('multiCarDialog').show()"/>
				</f:facet>
			</p:dataTable>

			<p:dialog header="Selected Cars" widgetVar="multiCarDialog" modal="true" showEffect="fade"
					  hideEffect="fade" resizable="false" width="220">
				<p:outputPanel id="multiCarDetail" style="text-align:center;">
					<ui:repeat value="#{bemVindoAction.selectedCars}" var="car">
						<h:outputText value="#{car.id} - #{car.brand}" style="display:block"/>
					</ui:repeat>
				</p:outputPanel>
			</p:dialog>
	</h:form>
</h:body>
</html>

## 6) Sample bean
package com.mkyong.editor;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Named
@ViewScoped
public class BemVindoAction implements Serializable {

    private List<Car> cars;
    private Car selectedCar;
    private List<Car> selectedCars;

    @Inject
    private CarService service;

    @PostConstruct
    public void init() {
        cars = service.createCars(10);

        selectedCars = new ArrayList<>();

        selectedCars.add(cars.get(0));
        selectedCars.add(cars.get(2));
        selectedCars.add(cars.get(4));
        selectedCars.add(cars.get(6));
        selectedCars.add(cars.get(8));
    }

    public List<Car> getCars() {
        return cars;
    }

    public void setService(CarService service) {
        this.service = service;
    }

    public Car getSelectedCar() {
        return selectedCar;
    }

    public void setSelectedCar(Car selectedCar) {
        this.selectedCar = selectedCar;
    }

    public List<Car> getSelectedCars() {
        return selectedCars;
    }

    public void setSelectedCars(List<Car> selectedCars) {
        this.selectedCars = selectedCars;
    }
}

**Comment by Rapster** [comment]
Indeed, disabled items are removed from the selection, see issue https://github.com/primefaces/primefaces/issues/3917
