### ISSUE TITLE
[Documentation] GridCSS and FlexGrid not show in components list

### ISSUE THREAD

**Issue by nokiajavi** [primefaces/primefaces#5798]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? N/A
- Does it work on the newest sources in GitHub? N/A
- Application server + version: N/A
- Affected browsers: N/A

## 2) Expected behavior
The GridCSS and FlexGrid components should appear in the list of components, and also when searching

## 3) Actual behavior
Grid CSS and FlexGrid components do not appear in the component list in Primefaces 8.0 documentation. It is only accessible through Layout or LayoutUnit. They also don't appear when using search, just the reference inside Layout and LayoutUnit components.
..

## 4) Steps to reproduce
enter the Primefaces 8 documentation page: https://primefaces.github.io/primefaces/8_0/#/

## 5) Sample XHTML
N/A

## 6) Sample bean
N/A

**Comment by melloware** [comment]
You are right.  I will look at addressing this.

**Comment by melloware** [comment]
There is this page: https://primefaces.github.io/primefaces/8_0/#/core/responsive

But it doesn't look complete and should have headlines for Grid CSS and PrimeFlex show it shows up in Search.

**Comment by melloware** [comment]
Grid CSS has its own page I can find under search too: https://primefaces.github.io/primefaces/8_0/#/components/gridcss?id=grid-css

**Comment by nokiajavi** [comment]
Yes! Thanks you.
