### ISSUE TITLE
TreeTable lose its children when added programmatically

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#58]
Forum Post URL: http://forum.primefaces.org/viewtopic.php?f=3&t=24530

I think that the problem is in org.primefaces.component.api.UITree#visitTree.

Potential patch;

Anyway, see this for the patch: http://forum.primefaces.org/viewtopic.php?f=3&t=31158&p=99645#p99645

**Comment by melloware** [comment]
Retested with 8.0 and this is fixed.
