### ISSUE TITLE
Schedule: DefaultScheduleModel should not overwrite ID of an event if already set 

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#5802]
Just came across this while working with the schedule component. I was building a DefaultScheduleEvent via the builder and set the ID of the event via [Builder#id(...)](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/model/DefaultScheduleEvent.java#L262). Then I added the event to the DefaultScheduleModel. This resulted in the ID being different from what I set it to.

Turns out the [DefaultScheduleModel](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/model/DefaultScheduleModel.java#L48) always overwrites the ID of the event, even if one is set already.

Is there any reason to do so? fullcalendar does not seem to require it to be a UUID. I would propose to set the ID of the event only if it's empty, like this:

```java
    @Override
    public void addEvent(ScheduleEvent<?> event) {
        if (StringUtils.isEmpty(event.getId()) {
            event.setId(UUID.randomUUID().toString());
        }
        events.add(event);
    }
```

(Can be worked around via a custom schedule model, but it's still strange imo, as the builder has an `id()` method)

**Comment by melloware** [comment]
Similar to this issue: https://github.com/primefaces/primefaces/issues/1039

**Comment by christophs78** [comment]
DefaultScheduleModel#addEvent had not been touch since 3.0.
IMO it would make sense to add the isEmpty-check as suggested by @blutorange.
(Had to debug a PF-schedule issue with a colleague yesterday where we wondered why we always have different event-Id´s.)
I may check this and provide a PR.
