### ISSUE TITLE
ChartJs PieChart, how to show the percentage on the pie chart

### ISSUE THREAD

**Issue by saycchai** [primefaces/primefaces#5803]
PrimeFaces version:8.0

How can I show the percentage in the chartjs pie chart p:pieChart (I think it is very usual that people want to see the percentage in the pie chart component?)
I cannot find any example in the showcase https://www.primefaces.org/showcase/ui/chartjs/pie.xhtml, and seems the java related classes PieChartModel, PieChartDataSet, PieChartOptions do not have such property?

**Comment by melloware** [comment]
It is not part of ChartsJS by default however there is a solution.

Source Code: https://github.com/emn178/chartjs-plugin-labels

Demo: https://emn178.github.io/chartjs-plugin-labels/samples/demo/

And to enable this simply use the PrimeFaces ChartJS extender functionality to enable the plugin documented here:  https://primefaces.github.io/primefaces/8_0/#/components/charts?id=extender
