### ISSUE TITLE
AutoComplete: accept array as a value (in addition to List)

### ISSUE THREAD

**Issue by astappiev** [primefaces/primefaces#5808]
## 1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior
- Accept `String[]` as a valid type for a value of the component

## 3) Actual behavior
throws `java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [Ljava.lang.String; (java.util.ArrayList and [Ljava.lang.String; are in module java.base of loader 'bootstrap')`

Right now the following components accept an array as a valid type:
- SelectCheckboxMenu
- SelectManyCheckbox

But `AutoComplete` accept only `List`.

It has something about converting `List` to `array` in `AutoCompleteRenderer:encodeMultipleMarkup`, but I don't know how to use it.
Also, the result is stored as an `array`  in `decodeMultiple` but then converted to `List` in `validate` method.

To solve the issue I extended `AutoComplete` class with the following methods:
```java
private boolean isInputValueArray = false;

@Override
public Object getValue()
{
    Object value = super.getValue();

    if (value != null && value.getClass().isArray())
    {
        isInputValueArray = true;
        Object[] array = (Object[]) value;
        return Arrays.asList(array);
    }

    return value;
}

@Override
public void setValue(Object value)
{
    if (isInputValueArray && value instanceof List)
    {
        value = ((List<String>) value).toArray(new String[0]);
    }

    super.setValue(value);
}
```

I can create a PR, but I think there is a better way to do that. If you can help me, I will implement it.

**Comment by melloware** [comment]
Do you mind putting together a [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help and I want to see your problem before i recommend the right way to fix it.

**Comment by melloware** [comment]
@astappiev Any update on this?

**Comment by astappiev** [comment]
Sorry, will update tomorrow

**Comment by melloware** [comment]
@astappiev I am going to close this ticket if an example Test case is not provided....

**Comment by astappiev** [comment]
Sorry 😔
https://github.com/astappiev/primefaces-test/tree/example-autocomplete

Change `rendered` attribute on [this line](https://github.com/astappiev/primefaces-test/blob/example-autocomplete/src/main/webapp/test.xhtml#L34) to get an error.

**Comment by melloware** [comment]
Thank you very much for the reproducer.  @tandraschko I am not sure if this should be fixed the way @astappiev did it or it should be done in the Renderer.  The AutoCompleteRenderer definitely hardcodes some assumptions about List.

**Comment by tandraschko** [comment]
i'm even not sure if we should support it. If we sould support Arrays, we should even support Sets.

How is this implemented in e.g. in the JSF impls with selectMany components?

**Comment by tandraschko** [comment]
As workaround a user can write custom getter/setter or use a converter to convert it.

**Comment by astappiev** [comment]
Hi @tandraschko :)

There is small missunderstanding: the List is alredy supported (and it is the only supported type) and I whould like to have a support for arrays.

**Comment by astappiev** [comment]
As far as I know, most JSF components supports only arrays.

**Comment by tandraschko** [comment]
> There is small missunderstanding: the List is alredy supported (and it is the only supported type) and I whould like to have a support for arrays.

I think you missunderstood me a bit :D I just said that if we add support for Arrays, we also have to support Sets.

**Comment by tandraschko** [comment]
and as always: it would be great if you can check other components how they support multiple collection types and provide a PR :)

**Comment by Rapster** [comment]
I'm not really in favor of supporting arrays in PF code base, supporting Collections and Arrays is source of boilerplate code... Simply have a look at `SelecttionFeature#decodeMultipleSelection` and see the number of lines of code added so PF can support arrays. Best example is to check in DataTable 😄

**Comment by astappiev** [comment]
I have tried to implement required changes and took `SelectManyCheckbox` as an example but found that it requires hundreds of lines of code from faces implementation to implement `getConvertedValue` to properly detect type of variable and convert value.

I thought that maybe it will make sense to extend `AutoCompleteBase` from `UISelectMany` instead of `HtmlInputText` to reuse the code from faces. It will require some changes, in particular, `UISelectMany` don't have any styles properties, but I guess it is not big deal to copy them or we can use `HtmlSelectManyCheckbox` where they already implemented. Is that bad idea?

**Comment by melloware** [comment]
Personally its not worth the risk of changing from `HtmlInputText` to `UISelectMany` for two reasons:
1. All of the inherited properties of `HtmlInputText` are expected.
2. AutoComplete is a singular input so extending UISelectMany feels wrong.

**Comment by melloware** [comment]
Although I didn't realize AutoComplete has a "multiple" mode now so maybe it could be possible to change to `UISelectMany`

**Comment by melloware** [comment]
@astappiev if you aren't going to work on this I would prefer to close this ticket as no one else has asked for this feature in 10 years so unless you feel strongly about it and provide a PR I think we will be closing this ticket.

**Comment by astappiev** [comment]
Hi @melloware , I will try to implement using `UISelectMany` in the next few days...

**Comment by Rapster** [comment]
What about using ArrayList, wouldn't that be a simpler and quicker fix? I understand a few component supports arrays but as I said, supporting both List and arrays is not as trivial as you might think. I wouldn't encourage devs to use arrays, on the contrary I would suggest to use collections like List. So please, reconsider this ticket

**Comment by astappiev** [comment]
I don't remember exactly, it was long ago but there was an issue with another component where I can use only array, but not list. I will try to change that once more to find out which component it was, may be it will be easier to update that component.

**Comment by astappiev** [comment]
Tried to use ArrayList one more time, and I'm getting the following error when trying to save a value of `p:selectCheckboxMenu`. And unfortunately, I'm unable to create MRE https://github.com/astappiev/primefaces-test/tree/example-list (it doesn't throw the error, but save button doesn't work, just do nothing).

I also tried to use `p:selectCheckboxMenu` with ArrayList and it works fine, but in my use-case, we have a wrapper for value which implements `Map<String, List<String>>`. Something similar you can find in [the example](https://github.com/astappiev/primefaces-test/blob/example-list/src/main/webapp/test.xhtml#L17) (mentioned above).

I understood that if simple component work, then you have no deal to help me, but just in case you meet something similar.

```
java.lang.ClassCastException: class [Ljava.lang.String; cannot be cast to class java.util.List ([Ljava.lang.String; and java.util.List are in module java.base of loader 'bootstrap')
	at de.l3s.learnweb.resource.Resource$MetadataMultiValueMapWrapper.put(Resource.java:1438) ~[classes/:?]
	at javax.el.MapELResolver.setValue(MapELResolver.java:84) ~[el-api.jar:3.0.FR]
	at javax.el.CompositeELResolver.setValue(CompositeELResolver.java:115) ~[el-api.jar:3.0.FR]
	at org.apache.el.parser.AstValue.setValue(AstValue.java:202) ~[jasper-el.jar:9.0.35]
	at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:263) ~[jasper-el.jar:9.0.35]
	at org.jboss.weld.module.web.el.WeldValueExpression.setValue(WeldValueExpression.java:64) ~[weld-servlet-shaded-3.1.4.Final.jar:3.1.4.Final]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.setValue(ContextAwareTagValueExpression.java:146) ~[myfaces-impl-2.3-next-M2.jar:2.3-next-M2]
	at javax.faces.component.UIInput.updateModel(UIInput.java:407) ~[myfaces-api-2.3-next-M2.jar:2.3-next-M2]
	at javax.faces.component.UIInput.processUpdates(UIInput.java:353) ~[myfaces-api-2.3-next-M2.jar:2.3-next-M2]
```

**Comment by melloware** [comment]
Closing for now.  Can always reopen if you do decide to submit a PR.

**Comment by astappiev** [comment]
In [this commit](https://github.com/astappiev/primefaces-test/commit/299f6b9a5aed119559e81ddcd4f28567eb9e8ef7) I replaced `InputRenderer` with `SelectManyRenderer` and it seems to work. But I guess it can not be merged without risks because there is no test which covers every usecase.

**Comment by melloware** [comment]
Looks pretty good to me minus my one comment.  Why not submit it as a PR for review by the team?

**Comment by astappiev** [comment]
No good solution found as for now.

**Comment by Rapster** [comment]
Till we don't have a clean way of supporting arrays and list, I'm against supporting more array stuff. It's not because arrays are "old school" or anything like that, it's just it results as ugly/messy code
