### ISSUE TITLE
JS: Remediate all JQMIGRATE deprecations

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5817]
I think the JQMigrate plugin needs to be run against the showcase and all deprecation warnings should be addressed.

https://github.com/jquery/jquery-migrate

A lot of these deprecation are being removed in Jquery 4.0 so fixing them now will alleviate pain later.

- [x] jQuery.fn.bind()/unbind() are deprecated
- [x] jQuery.isArray is deprecated
- [x] jQuery.isFunction is deprecated
- [x] jQuery.trim is deprecated; use String.prototype.trim 
- [x] Use of number-typed values is deprecated in CSS
- [x] jQuery.fn.click() event shorthand is deprecated, use `on` and `trigger` instead.  Also includes blur, focus, focusin, focusout, resize, scroll, dblclick, mousedown, mouseup, mousemove, mouseover, mouseout, mouseenter, mouseleave, change, select, submit, keydown, keypress, keyup, and contextmenu

**Comment by melloware** [comment]
I have one last one to go but its a big one.

**Cause:** The .on() and .trigger() methods can set an event handler or generate an event for any event type, and should be used instead of the shortcut methods. This message also applies to the other event shorthands, including: blur, focus, focusin, focusout, resize, scroll, dblclick, mousedown, mouseup, mousemove, mouseover, mouseout, mouseenter, mouseleave, change, select, submit, keydown, keypress, keyup, and contextmenu.

**Solution:** Instead of `.click(fn)` use `.on("click", fn)`. Instead of `.click()` use `.trigger("click")`.

**Comment by erickdeoliveiraleal** [comment]
this commit broke some of the dialogs of my application.
before it my dialog was like this: 
![Capturar](https://user-images.githubusercontent.com/3578953/89579520-4e1cbc00-d80a-11ea-97ad-02a8c7d2eff7.PNG)
now it looks like this:
![image](https://user-images.githubusercontent.com/3578953/89579872-e1ee8800-d80a-11ea-9155-4b766c610399.png)

**Comment by erickdeoliveiraleal** [comment]
Or maybe I'm wrong about the specific commit, but it is some of the recent commits, I'm trying to identify if the this is the right one.

**Comment by erickdeoliveiraleal** [comment]
if I reset hard at 803af03265c75f90e8a39706346f5f605036e927 it is ok
and if I reset hard at d5365288654862bf7786e21e012cd7db566a1de7 the problem appears, so I believe the problem is there. But the strage part to me is if I revert the problematic commit I still see the problem :D

**Comment by erickdeoliveiraleal** [comment]
I reverted locally the commit d5365288654862bf7786e21e012cd7db566a1de7 and my problem is gone.

**Comment by melloware** [comment]
I will investigate. I prefer not to revert i would like to get to the bottom of the issue.  Can you provide a small dialog reproducer please.  JQuery 4.0 will not allow this in the future so we need to figure out what is different and fix it.

**Comment by melloware** [comment]
Its this issue that is causing it so comment on that thread please: https://github.com/primefaces/primefaces/pull/5937

**Comment by melloware** [comment]
@erickdeoliveiraleal I just checked in a fix that I think fixes your issues can you please try it?
