### ISSUE TITLE
TreeTable: Add filter AJAX event

### ISSUE THREAD

**Issue by MatthiasScherrerFGCZ** [primefaces/primefaces#5819]
Feature request

## 1) Environment
- PrimeFaces version: PrimeFaces-8.0
- Application server + version: Mojarra-2.3.13
- OS on the client: Ubuntu 18.04.3 LTS
## 2) Expected behavior
`<p:ajax event="filter"/>` and no error
## 3) Actual behavior
`<p:ajax event="filter"/>` and error _<p:ajax> Event:filter is not supported._

Currently, the TreeTable component can be sorted and filtered. However, only the sort event (sort | org.primefaces.event.SortEvent) is supported at the moment. It would be useful to have support for a filter event as in the DataTable.

**Comment by tandraschko** [comment]
Your nickname looks like you would like to work on it and provide a PR? :D

**Comment by MatthiasScherrerFGCZ** [comment]
@tandraschko I can have a look at it :)

**Comment by tandraschko** [comment]
@MatthiasScherrerFGCZ any news?

**Comment by tandraschko** [comment]
added basic support; data will be null in the event as TreeTable doesnt have the "filteredValue" in the state as DataTable.
