### ISSUE TITLE
confirmDialog should appear at the center of the browser, not at the center of the page 

### ISSUE THREAD

**Issue by pm2013** [primefaces/primefaces#582]
Now on longer pages confirmDialogs are hidden and users cannot even scroll to the dialog.

At least shold be possible to set the top property, as it is for the p:dialog.

**Comment by kukel** [comment]
> _"Now on longer pages"_

Now being? PF 5.1, 5.2? And it did not happen before?

**Comment by pm2013** [comment]
In version 4 PF p:confirmDialogs and p:dialog appear by default at the center of the browser, with no problems.

**Comment by cagataycivici** [comment]
Positioning has not changed, it is center of window, check out the code initPosition method.

**Comment by pm2013** [comment]
Please see attachment: in your own Showcase,
if the browser area is limited, dialogs are opened
outside the visible area.

Pozdrawiam / Best regards,
Piotr Małecki
