### ISSUE TITLE
DataTable: No records found not deleted

### ISSUE THREAD

**Issue by KimGabrielsen** [primefaces/primefaces#5823]
1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers:

## 2) Expected behavior
When a new row is added to the table the 'No records found' should be removed
...

## 3) Actual behavior
The text is still show as first record in the table and added records below
..

## 4) Steps to reproduce
https://www.primefaces.org/showcase/ui/data/datatable/addRow.xhtml
shows the files necessary.

In AddRowView 
change
```java
@PostConstruct
    public void init() {
        cars1 = service.createCars(15);
    }
```
to 
```java
@PostConstruct
    public void init() {
        **cars1 = service.createCars(0);**
    }
```
so the table is empty on start. Then add a row by clicking the 'add new row' button.

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by melloware** [comment]
If you need this fix right now just add this to your Javascript.
```javascript
PrimeFaces.widget.DataTable.prototype.addRow = function() {
    var $this = this,
        options = {
            source: this.id,
            process: this.id,
            update: this.id,
            params: [{
                    name: this.id + '_addrow',
                    value: true
                },
                {
                    name: this.id + '_skipChildren',
                    value: true
                },
                {
                    name: this.id + '_encodeFeature',
                    value: true
                }
            ],
            onsuccess: function(responseXML, status, xhr) {
                PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
                    widget: $this,
                    handle: function(content) {
                        this.tbody.append(content);
                    }
                });

                if ($this.isEmpty()) {
                    $this.tbody.children('tr.ui-datatable-empty-message').remove();
                }

                return true;
            }
        };

    PrimeFaces.ajax.Request.handle(options);
};
```
