### ISSUE TITLE
DataTable: fix sort oncomplete callback

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#5825]
## 1) Environment
- PrimeFaces version: master, latest 8.0, 7.*

## 2) Expected behavior
If sort ajax request is aborted, there is not any error. The problem is in sort function of datatable.js. The oncomplete callback doesn't fail if args is undefined. The second if condition have to check args like the first one.

**Comment by tandraschko** [comment]
thanks for the PR!
