### ISSUE TITLE
DatePicker: selectEvent with selectionMode="range" and AJAX Event dateChange not work

### ISSUE THREAD

**Issue by 123MarkA321** [primefaces/primefaces#5830]
## 1) Environment
- 8.0
- Application Tomcat 9.0.33
https://forum.primefaces.org/viewtopic.php?f=3&t=61731
## 2) Expected behavior
call dateChange event after set correct start - end
## 3) Actual behavior
By the first click of a day. my ArrayList value is empty. By the second click my value is now null
Post in PF forum: 
## 4) Steps to reproduce
see 5)
## 5) Sample XHTML
```xml
<p:datePicker id="calendarRange" converter="#{value}" validator="#{value.validate}" selectionMode="range" value="#{value.currentValue}"
showIcon="true" size="18"
yearRange="#{value.yearRange}" locale="#{localeProvider.language}"
styleClass="#{value.styleClass}" showButtonBar="true" showOnFocus="false" numberOfMonths="3">
<p:ajax event="dateSelect" process="@this" update="mainForm:filterPanel" />
<f:ajax event="change" execute="@this" render="mainForm:filterPanel"/>
</p:datePicker>
```

**Comment by melloware** [comment]
Reproducer: 
[pf-5830.zip](https://github.com/primefaces/primefaces/files/4522425/pf-5830.zip)

Run with "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

@123MarkA321 Is what you are saying is when you pick the "first" date you are expecting the array to be filled with 1 date?   

@christophs78 I could be wrong but I think this is by design and the range is only set when a complete range is there. If only the first date is selected the range is still empty.

**Comment by 123MarkA321** [comment]
I not expecting set first value. i expecting that no call the event DateChange by first click.

The DateChange Event will be fired by first click. I think this event should be fired after set correct range.
Case:
clickFirst date: on my validate method comes empty arrayList
after update...input field is empty. 
clickSecond date: on validate method comes now "null" and not the ArrayList<LocalDate> with size 2.
after update...input field is empty and invalid because no value could set (null)

THe event should be fired only by set a correct dateRange and not by first click (invalid range)

In the reproducer pf-5830.zip in method dateSelect() the event.getObject().toString() is always empty and this is also wrong.

**Comment by 123MarkA321** [comment]
First click:
<img width="43" alt="firstClick" src="https://user-images.githubusercontent.com/64163092/80107362-439c2680-857b-11ea-8ba7-90dee406d59f.png">
Call validate (should not call)
<img width="647" alt="resultValidate1" src="https://user-images.githubusercontent.com/64163092/80107364-4434bd00-857b-11ea-8a50-5776feef664f.png">
<img width="252" alt="secondClick" src="https://user-images.githubusercontent.com/64163092/80107365-4434bd00-857b-11ea-9a64-60fd7e02099f.png">
Call validate (value is now null and here is expected 01.04.2020 - 30.06.2020
<img width="803" alt="resulktValidate2" src="https://user-images.githubusercontent.com/64163092/80107367-44cd5380-857b-11ea-9f01-4fccc197896f.png">
Validated failed because field is null:
<img width="100" alt="resultAfterSetCorrectRange" src="https://user-images.githubusercontent.com/64163092/80107368-44cd5380-857b-11ea-97f2-466d3faa8630.png">
Here the useCase in images

**Comment by melloware** [comment]
OK I understand now. You are OK with the dateSelect when its set just not on the first click when no value is actually set.  I understand.

**Comment by 123MarkA321** [comment]
Sorry my english is very very terrible ^^ german is better for me :)

**Comment by christophs78** [comment]
Just looked at this too.... 

`<p:ajax event="dateSelect" listener="#{calendarJava8View.onDateSelect}" update="msgs" />` get´s after each click. First time after only begin-date is selected, second time after begin- and enddate are selected.

With begin-date-only the array is empty. After begin- and enddate it looks Ok:
![grafik](https://user-images.githubusercontent.com/10461942/80110489-06d22e80-857f-11ea-8b77-deffc7bc0ccf.png)

**Comment by christophs78** [comment]
Part of the root cause seems to be `DatePickerRenderer#getConvertedValue`
![grafik](https://user-images.githubusercontent.com/10461942/80110897-7f38ef80-857f-11ea-8c48-a105c43c4261.png)

Maybe we should allow parts.length == 1 and parts.length == 2

**Comment by 123MarkA321** [comment]
I have override in first step the DatePickerRenderer and have add this:
} else if (parts.length == 1) {
          //condition for set from - until with selectEvent AJAX identifier
          range.add(getConvertedValueFromBaseCalendarRenderer(context, component, parts[0]));
        }

But then i become a OutOfBoundsException from DatePikcer in validate process...i ignore the OutOfBounds at the time and it work...but is not nice :)

**Comment by 123MarkA321** [comment]
getConvertedValueFromBaseCalendarRenderer() is a origin copy because i can not call super.super.getConvertedValue()

**Comment by christophs78** [comment]
Yes, we have to cross-check (at least) this against `DatePicker#validateValueInternal`

```
else if (value instanceof List && getSelectionMode().equals("range")) {
	List<?> rangeValues = (List) value;

	if (rangeValues.get(0) instanceof LocalDate) {
		LocalDate startDate = (LocalDate) rangeValues.get(0);
		validationResult = validateDateValue(context, startDate);

		if (isValid()) {
			LocalDate endDate = (LocalDate) rangeValues.get(1);
			validationResult = validateDateValue(context, endDate);

			if (isValid() && startDate.isAfter(endDate)) {
				setValid(false);
				validationResult = ValidationResult.INVALID_RANGE_DATES_SEQUENTIAL;
			}
		}
	}
	else if (rangeValues.get(0) instanceof Date) {
		Date startDate = (Date) rangeValues.get(0);
		validationResult = validateDateValue(context, CalendarUtils.convertDate2LocalDate(startDate, CalendarUtils.calculateZoneId(getTimeZone())));

		if (isValid()) {
			Date endDate = (Date) rangeValues.get(1);
			validationResult = validateDateValue(context, CalendarUtils.convertDate2LocalDate(endDate, CalendarUtils.calculateZoneId(getTimeZone())));

			if (isValid() && startDate.after(endDate)) {
				setValid(false);
				validationResult = ValidationResult.INVALID_RANGE_DATES_SEQUENTIAL;
			}
		}
	}
```

We should think about this a bit longer. And write UnitTests.

Can you provide a PR (including UnitTests) and run regression-tests against all other DatePicker-examples within showcase?

**Comment by melloware** [comment]
Couldn't we tackle this another way and not call `dateSelect` in the JavaScript if type == range and parts !===2 ?

**Comment by 123MarkA321** [comment]
My expected behavior is: only fire dateSelect by range after click the second date

**Comment by 123MarkA321** [comment]
range is only valid with 2 dates...so dateSelect for first date is not correct i think

**Comment by melloware** [comment]
@123MarkA321  can you add this JS to your JS file.
```javascript
PrimeFaces.widget.DatePicker.prototype.fireDateSelectEvent = function() {
    // #5830: do not fire in range mode if only the first value is set
    if (this.cfg.selectionMode === "range" && this.input.val().indexOf(this.cfg.rangeSeparator) === -1) {
        return;
    }

    this.callBehavior('dateSelect');
};
```

This should prevent the `dateSelect` on the first selection.

**Comment by 123MarkA321** [comment]
works fine now. Thx for help
