### ISSUE TITLE
Inplace: switches to output mode even if validation fails when facets are used

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#5833]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Tomcat 8.0.39
- Affected browsers: Firefox 75

## 2) Expected behavior
When I have a `p:inplace` with `editor="true"` and nested `f:facet`s for input and output, if I press on the confirm button but validation fails, the component does not switch to output mode and just updates its input facet contents.

## 3) Actual behavior
When I have a `p:inplace` with `editor="true"` and nested `f:facet`s for input and output, if I press on the confirm button but validation fails, the component switches to output mode, without applying changes. Switching again to input mode, shows validation error consequences.

## 4) Steps to reproduce
- create a `<p:inplace editor="true">` with nested `<f:facet name="output">` and `<f:facet name="input">`
- in the `<f:facet name="input">` put an input component with some validation rules and a `<p:message>`
- click on the `<p:inplace>`
- change the input value to an invalid value
- click on the confirm button

## 5) Sample XHTML

```xml
<p:inplace editor="true">
  <f:facet name="output">
    <h:outputText value="#{bean.foo}">		
      <f:convertNumber />
    </h:outputText>
  </f:facet>
  <f:facet name="input">
    <p:inputText id="fooInput" value="#{bean.foo}" required="true">
      <f:convertNumber />
      <f:validateDoubleRange minimum="0" maximum="100" />
    </p:inputText>
    <p:message id="fooMessage" for="fooInput" />
  </f:facet>
  <p:ajax event="cancel" global="false" />
  <p:ajax event="save" global="false" />
</p:inplace>
```

## 6) Sample bean

```java
public class Bean {
  private double foo;
  // getters and setters omitted
}
```

See the difference if you change the facelet fragment to:

```xml
<p:inplace editor="true" label="#{bean.foo}">
  <p:inputText id="fooInput" value="#{bean.foo}" required="true">
    <f:convertNumber />
    <f:validateDoubleRange minimum="0" maximum="100" />
  </p:inputText>
  <p:message id="fooMessage" for="fooInput" />
  <p:ajax event="cancel" global="false" />
  <p:ajax event="save" global="false" />
</p:inplace>
```

In the latter case, the behaviour is as expected: validation errors are immediately shown and the inplace component does not switch to output mode until you fix your changes or hit the cancel button.

**Comment by melloware** [comment]
Reproducible test case: 
[pf-5833.zip](https://github.com/primefaces/primefaces/files/4522570/pf-5833.zip)

This issue still exists in 8.0 and 9.0-SNAPSHOT.

**Comment by melloware** [comment]
@mauromol Can you add this JS code to your javascript in your app.
```javascript
PrimeFaces.widget.Inplace.prototype.save = function(e) {
    var $this = this;

    var options = {
        source: this.id,
        update: this.id,
        process: this.id,
        formId: this.cfg.formId,
        oncomplete: function(responseXML, status, xhr) {
            if (xhr && xhr.validationFailed) {
                $this.show();
            }
            return true;
        }
    };

    if (this.hasBehavior('save')) {
        this.callBehavior('save', options);
    } else {
        PrimeFaces.ajax.Request.handle(options);
    }
};
```

**Comment by mauromol** [comment]
> @mauromol Can you add this JS code to your javascript in your app.

Hi @melloware, thanks for the quick feedback. If I try that code in may app, when I click on the "save" button I get this error in Firefox JS console:

    TypeError: this.callBehavior is not a function

The error comes from line:

    this.callBehavior('save', options);

**Comment by melloware** [comment]
Oh sorry you are on 6.2!   Try this JS...
```javascript
PrimeFaces.widget.Inplace.prototype.save = function(e) {
    var options = {
        source: this.id,
        update: this.id,
        process: this.id,
        formId: this.cfg.formId,
        oncomplete: function(responseXML, status, xhr) {
            if (xhr && xhr.validationFailed) {
                $this.show();
            }
            return true;
        }
    };

    if (this.hasBehavior('save')) {
        var saveBehavior = this.cfg.behaviors['save'];

        saveBehavior.call(this, options);
    } else {
        PrimeFaces.ajax.AjaxRequest(options);
    }
};
```

**Comment by mauromol** [comment]
`$this.show();` produces `$this is undefined`. Replacing it with `this.show();` (because I guess it's just a typo), I still get:

    TypeError: this.show is not a function

**Comment by melloware** [comment]
Sorry was missing one line..
```javascript
PrimeFaces.widget.Inplace.prototype.save = function(e) {
    var $this = this;
    var options = {
        source: this.id,
        update: this.id,
        process: this.id,
        formId: this.cfg.formId,
        oncomplete: function(responseXML, status, xhr) {
            if (xhr && xhr.validationFailed) {
                $this.show();
            }
            return true;
        }
    };

    if (this.hasBehavior('save')) {
        var saveBehavior = this.cfg.behaviors['save'];

        saveBehavior.call(this, options);
    } else {
        PrimeFaces.ajax.AjaxRequest(options);
    }
};
```

**Comment by mauromol** [comment]
Thank you @melloware, with this code it now works in an acceptable way. There's a "bouncing effect" though: the inplace component is switched to output mode for a moment, then it is brought back to input mode to show validation errors. This bouncing effect doesn't happen when facets are not used. It's not very elegant, anyway for now it is an acceptable compromise for me.

**Comment by melloware** [comment]
I think there might be a better way to fix it.

**Comment by melloware** [comment]
My final fix is better and there is no flickering it works the way the component was intended.  although it won't do you much good because PrimeTek is no longer patching 6.2.  You would have to override the Inplace component in code to get the real fix.
