### ISSUE TITLE
PanelGrid: No way to manage style or identifiers of panelgrid cells except for tabular mode

### ISSUE THREAD

**Issue by tim12s** [primefaces/primefaces#5840]
Responsive panelgrid does not currently allow specific cells within the grid to be identified or styled uniquely. This capability only exists with the layout='tabular' mode.

This pull requests now enables row and column components to be used with layout='grid' and column components to be used with layout='flex'.

The usefulness of this can be seen in the context of legacy tabular mode which allowed for rows to be highlighted differently based on odd or even colors. In the context of responsive design there is still a need to control the styling of rows and cells within the grid and this pull request enables that.

## 1) Environment
- PrimeFaces version: All
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Irrelevant
- Affected browsers: Irrelevant

## 2) Expected behavior

Need a method to add style, styleClass, and ID attributes to DIVs created

## 3) Actual behavior

Feature Request, Not a bug

## 4) Steps to reproduce

Feature Request, Not a bug

## 5) Sample XHTML

```xml
<p:panelGrid columns="2" columnClasses="ui-grid-col-4,ui-grid-col-8" layout="grid">

<p:row styleClass="ui-lets-make-this-special">
     User Account
</p:row>

<p:outputLabel for="field01" value="First Name"/>
<p:inputText id="field01" value="#{user.firstname}"/>

<p:column id="LastNameLabel">
    <p:outputLabel for="field02" value="Last Name"/>
</p:column>
<p:inputText id="field02" value="#{user.lastname}"/>

<p:row style="background-color: lightgray;">
     Other
</p:row>

<p:outputLabel for="field03" value="Cats Name"/>
<p:inputText id="field03" value="#{user.catsname}"/>

<p:outputLabel for="field04" value="Vet Number"/>
<p:inputText id="field04" value="#{user.vetNumber}"/>

<p:row id="lastRow" styleClass="my-header-style-class">
<p:column id="lastRowLeft"><p:outputLabel for="field05" value="Some Title"/></p:column>
<p:column id="lastRowRight"><p:inputText id="field05" value="#{user.someTitle}"/></p:column>
</p:row>

</p:panelGrid>
```

## 6) Sample bean

Not a bug

**Comment by melloware** [comment]
Thanks for the PR.  Please progress with a showcase PR.

**Comment by jrcampins** [comment]
On April 28, 2020, @tim12s wrote: "Responsive panelgrid does not currently allow specific cells within the grid to be identified or styled uniquely. This capability only exists with the layout='tabular' mode."

I will really appreciate if someone can tell me how to set the style of specific cells of a panelGrid with layout=tabular.

I want to "hide" some cells. I have partially solved the problem using p:row and p:column; but those components don't work well inside a p:wizard. So I was wondering if there is another way to do it. Right now, I'm only hiding the cell content, but I'd also like to remove the padding and borders from the generated td.
