### ISSUE TITLE
org.primefaces.PrimeFaces: improve robustness

### ISSUE THREAD

**Issue by svenkatgit** [primefaces/primefaces#5843]
# 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: tomee 7.1.1
- Affected browsers: Browser independent

## 2) Expected behavior
No NPE should be triggered, if FacesContext is not initialized. Use of isAjaxRequest(), executeScript() should not trigger NPE. Please let isAjaxRequest() return false instead.
A method to check if FacesContext is available would be helpful: isFacesRequest (proposed by tandraschko).

## 3) Actual behavior
On non-jsf calls trigger a NullPointerException

## 4) Steps to reproduce
Following code called by a non-jsf bean will trigger an NPE when isAjaxRequest() is called:
`
   PrimeFaces pf = PrimeFaces.current();
    if (pf != null && pf.isAjaxRequest()) {
      pf.executeScript("window.location.assign('test.html');");
      FacesContext.getCurrentInstance().renderResponse();
    }
`

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment]
in 9.0 you can use:

```
if (PrimeFaces.current().isFacesRequest() && PrimeFaces.current().isAjaxRequest()) { 
   pf.executeScript("window.location.assign('test.html');");
   FacesContext.getCurrentInstance().renderResponse(); 
}
```
