### ISSUE TITLE
Schedule: Issues with "customButtons" when set via the extender

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#5847]
## Environment
Tried it with PF 8.0, but looking at the source, most likely also present in the current master.

## Issue
I was trying to add [custom buttons](https://fullcalendar.io/docs/customButtons) to the schedule / fullcalendar header, by using the `extender` option of the schedule widget:

```xhtml
<p:schedule extender="function(){this.cfg.customButtons={myButton:{text:"foobar"}}}" centerHeaderTemplate="myButton"/>
```

Now that works and adds the button to the center of the schedule header. There is one problem, however, that occurs once an AJAX update is performed. The schedule disappears and the following error message is logged:

```
Uncaught Error: The FullCalendar view "myButton" does not exist. Make sure your plugins are loaded correctly.
```

## Cause

Looking around in the source code a bit, the problem is that when the widget is refreshed, it attempts to pass `myButton` as the value of the [defaultView](https://fullcalendar.io/docs/defaultView) option, which is not allowed.

The schedule components saves the currently selected view in a hidden input field, so that the view can be restored after an AJAX update, see [1-schedule.js#241-263](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L241). The code there in `bindViewChangeListener`

* iterates over all buttons
* excludes some predefined buttons
* parses the style classes of the buttons to figure out the view of that button
* saves that view via $.fn.data
* listens for a click event on the button
* and finally reads the view via $.fn.data from the button and saves it

Since custom buttons are, well, custom, they are not excluded in step 2, so `myButton` is saved as the view and later set as the `defaultView`, which causes the error.

## Possible solution

This process seems a bit convoluted to me - am I missing something? I took a quick look at the full calendar API and found some events such as [viewSkeletonRender](https://fullcalendar.io/docs/viewSkeletonRender). It seems to be fired when the view is changed:

```javascript
PF("schedule").calendar.on("viewSkeletonRender", ev => console.log(ev.view.type))
```

**Comment by christophs78** [comment]
IMO a PR for a better implementation is welcome.

There had been many hands on the fullcalendar-integration. I am the one who migrated this from fullcalendar 3.x to 4.x and switched the model behind from java.util.Date to java.time.LocalDateTime.

There may be JS-code which was written a long time ago for a old fullcalendar - version. When we are able to do the same with less and simpler code (maybe using functionality that came with newer versions of fullcalender) this is welcome.

**Comment by blutorange** [comment]
Yeah, I thought it might be historical. I'll take a look and see if it works out the way I mentioned.
