### ISSUE TITLE
InputNumber: option to disable modifyValueOnWheel

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#5849]
Since upgrading AutoNumeric in 8.0, there is a new feature enabled by default on p:inputNumber fields. If you focus the field and try to scroll up or down, the value in the field changes.
Here's an example from the Showcase:
![inputnumber](https://user-images.githubusercontent.com/6633403/80706533-c0358480-8ae8-11ea-886b-95bf987838be.gif)

This behavior might be irritating though. If you quickly enter a value and scroll down to save, you might change the field's value accidentally. Therefore I would like to disable this feature in my application.

The solution might be simple as AutoNumeric provides an option to disable the feature via:

> { modifyValueOnWheel: false }

According to the [configurator](http://autonumeric.org/configurator):

> **modifyValueOnWheel**
> Allows the user to increment or decrement the element value with the mouse wheel
>
> modifyValue: true, Allows using the wheel event to either increment of decrement the element value
> doNothing: false, The wheel event is ignored

**Comment by melloware** [comment]
Thanks for reporting. I will take care of this.

**Comment by GabrieleFrau** [comment]
Will you backport it to Primefaces 8.0.3?

**Comment by melloware** [comment]
I have requested from PrimeTek that this be added to 8.0.3.

**Comment by melloware** [comment]
8.0.3 has been released with this fix.

**Comment by ravihariharan** [comment]
@mertsincan  can back fix this to elite  7

**Comment by rho66** [comment]
Please reopen this issue, because scolling up and down with mousewheel in p:inputNumber ist still there in PF10 and Elite 12.0.4.
