### ISSUE TITLE
SelectBooleanCheckbox: Disabled selectBooleanCheckbox with itemLabel defined

### ISSUE THREAD

**Issue by svenkatgit** [primefaces/primefaces#5850]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version?: No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: tomee 7.1.1
- Affected browsers: Firefox, Chrome, ...

## 2) Expected behavior
If SelectBooleanCheckbox is disabled and an ItemLabel is defined, the label should also be disabled.
(as in the 2. field of screenshot)

## 3) Actual behavior
The label looks like activated and has also the "click-finger" cursor (as the 3. field in the screenshot)
![SelectBooleanCheckbox](https://user-images.githubusercontent.com/37800416/80712398-3d192c00-8af2-11ea-92ab-8eeb55785d5f.png)

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
```xml
<p:panelGrid columns="2">
	<p:selectBooleanCheckbox id="cb1"
		value="true"
		disabled="false"
		itemLabel="1. disabled='false'">
	</p:selectBooleanCheckbox>
	<p:selectBooleanCheckbox id="cb2"
		value="true"
		styleClass="ui-state-disabled"
		disabled="false"
		itemLabel="2. disabled='false' styleClass='ui-state-disabled'">
	</p:selectBooleanCheckbox>
	<p:selectBooleanCheckbox id="cb3"
		value="true"
		disabled="true"
		itemLabel="3. disabled='true'">
	</p:selectBooleanCheckbox>
	<p:selectBooleanCheckbox id="cb4"
		value="true"
		styleClass="ui-state-disabled"
		disabled="true"
		itemLabel="4. disabled='true' styleClass='ui-state-disabled'">
	</p:selectBooleanCheckbox>
</p:panelGrid>
```

## 6) Sample bean

..

**Comment by stolp** [comment]
I verified that this is indeed an issue and will provide a pull request for this.

**Comment by stolp** [comment]
As this is now assigned to me, is there anything else expected from my side?

**Comment by melloware** [comment]
Nope just waiting to see if anyone else reviews it before I merge it. Thanks for the fix!
