### ISSUE TITLE
DataExporter: Missing dependency

### ISSUE THREAD

**Issue by astappiev** [primefaces/primefaces#5852]
1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior
Dependency documented [there](https://primefaces.github.io/primefaces/8_0/#/gettingstarted/dependencies?id=dependencies) or not used.

## 3) Actual behavior
```
java.lang.NoClassDefFoundError: org/apache/xmlbeans/impl/common/XMLChar
	at org.primefaces.util.EscapeUtils.forXmlTag(EscapeUtils.java:176) ~[primefaces-8.0.jar:8.0]
	at org.primefaces.component.datatable.export.DataTableXMLExporter.getColumnTag(DataTableXMLExporter.java:131) ~[primefaces-8.0.jar:8.0]
```

**Comment by melloware** [comment]
Yeah for exporter you need POI.

https://primefaces.github.io/primefaces/8_0/#/gettingstarted/dependencies?id=dependencies

I will update it to say XML or Excel.

**Comment by astappiev** [comment]
No, `org.apache.poi/poi` is alredy added, it provides only `org.apache.poi` package and there is no dependency of anything that includes `org.apache.xmlbeans` package.

**Comment by astappiev** [comment]
The required class is provided by `org.apache.xmlbeans/xmlbeans` package. And the package is not used anywhere else in PrimeFaces except this method.

**Comment by melloware** [comment]
```xml
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.version}</version>
        </dependency>
```

That is for Excel and XML.

**Comment by astappiev** [comment]
Okay, that makes sense.

Perhaps, this should be added to the documentation (use `poi-ooxml` not just `poi`) for someone like me.

**Comment by zhedar** [comment]
What about adding the maven dependencies directly to the documentation as an example? Might be more concise than it is currently.

**Comment by melloware** [comment]
Sure just submit w PR. The documentation is easy to update it’s just Markdown files

**Comment by stolp** [comment]
The pom.xml already nicely lists the optional dependencies including the supported versions (including comments for their targeted components).

I think the documentation should simply link to https://github.com/primefaces/primefaces/blob/master/pom.xml (or better a tagged version) to have a single point of reference.

**Comment by zhedar** [comment]
I guess that would be enough for those looking for the info. The problem with a tagged version might be, that you would need to change that on every release. I guess this would be forgotten quite easily.  
On the other side the current pom already lists different dependencies (ancient itext dropped, yay!) and therefore might be confusing.

**Comment by stolp** [comment]
You are right, it would for example be https://github.com/primefaces/primefaces/blob/6b6c5b91a9f6e6b37a7a2c5448a2782f38904026/pom.xml for 8.0.

I still think this would be more maintainable than duplicating the content in the documentation.

Is there a release procedure defined which could include steps like this?

**Comment by zhedar** [comment]
If you link the tagged version, it might be easier to find and replace though:
https://github.com/primefaces/primefaces/blob/8.0/pom.xml

**Comment by stolp** [comment]
This was what I was initially looking for, thanks!
