### ISSUE TITLE
Core / Ajax: possibility for remote commands to return a promise

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#5859]
Remote commands are useful in many cases, including when you have some custom JavaScript for client-side interaction and want to call a bean method. Running a remote command works fine - we just have to call the function created in the global window scope.

One thing I found lacking, however, is the ability to register a callback for when the remote command completes. Yes, I can add callback via the `onsuccess` or `oncomplete` attributes, but the problem here is that this allows only for one specific callback to be set. Sometimes I need to register a callback dynamically from the calling JavaScript code, or when binding symbols via a closure. For the time being, I made a quick hack by overriding some of the `PrimeFaces.ajax` methods, but a proper solution would be great.

Implementing doesn't seem to be particularly hard, I made a demonstration here: https://github.com/blutorange/primefaces/commit/b665c40fea17ff7bf0cadaa1e58a0fbfdc6b6dbd (Works also when client side validation is on. Creates a `$.Deferred` object, saves it in the `cfg` object, and resolves or rejects it when the AJAX request is done.)

![image](https://user-images.githubusercontent.com/2456413/80915100-2d971e80-8d50-11ea-8f42-d12be2389d8b.png)

Any opinions on this? I could make a PR if there aren't any objections.

**Comment by melloware** [comment]
I say submit it and let us review!

**Comment by melloware** [comment]
BTW the JSDOC work you did was amazing.  I am going to update the showcase to now have two links for each component "Documentation" and "JsDoc" links to take you right to the components widget.

**Comment by tandraschko** [comment]
ost of the PF users are "oldschool" and avoid JS
if you have some newschool JS API improvements -> +1 from my side
