### ISSUE TITLE
ImageCropper: Error on Unix systems

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5861]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: Any UNIX OS
- Affected browsers: ALL

## 2) Expected behavior

Cropping should work on UNIX systems.

## 3) Actual behavior

Based on forum post: https://forum.primefaces.org/viewtopic.php?f=3&t=61847

The problem I am having is with the imageCropper component, in version 6.2 it worked correctly for me but after updating it started to fail. The server log shows me the following warning:

> 17: 19: 55,183 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-13) Path traversal attempt - absolute path not allowed .: javax.faces.FacesException: Path traversal attempt - absolute path not allowed.

```
java.io.FileNotFoundException: /home/user/Documents/Primefaces/pf-3286/target/primefaces-test-1.0-SNAPSHOTresources/images/nature6.jpg (No such file or directory)
```

## 4) Steps to reproduce

Showcase: http://localhost:8080/showcase/ui/multimedia/cropper.xhtml

**Comment by kneringerjohann** [comment]
Dear Primetek-Team,
could you add this fix to an elite-release?
thank you in advance.
