### ISSUE TITLE
SelectBooleanButton: "converter" support

### ISSUE THREAD

**Issue by andrewtobilko** [primefaces/primefaces#5864]
## 1) Environment
- PrimeFaces version: 9.0

## 2) Expected behavior

It would be nice to have the SelectBooleanButton supporting the converter attribute. Sometimes, it's very useful to have a converter to wrap/unwrap your abstraction over a boolean.

## 3) Actual behavior

The "converter" attribute has no effect on the component.

## 4) Steps to reproduce

1. Create a SelectBooleanButton.
2. Define a converter for it.
3. Debug the converter.

## 5) Sample XHTML

            <p:selectBooleanButton
                    converter="MyBooleanConverter"
                    value="#{myBooleanAbstration}" />

**Comment by melloware** [comment]
Feel free to submit a PR for review.
