### ISSUE TITLE
Datatable: disabledSelection with initial selection removes active ui-state-active-class to the checkboxes

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#5868]
Reported By PRO User;
> We have encountered a difference between versions 6.2.x and 7.0.x that cause a graphic bug for the checkbox element.
In the 6.2.x version, when we check the checkbox and then we disable it, the checkbox keeps both the “ui-state-active” and “ui-state-disabled” CSS classes.
It doesn’t show the same behavior in the 7.0.x version: if a checkbox is checked it has the “ui-state-active” CSS class, but when we disable it, that class is overridden by the “ui-state-disabled” one.
We expect to have both CSS classes in the checkbox element.
We have encountered this bug in the “dataTable” component by defining the attribute “disabledSelection” and we have found this difference by testing both PrimeFaces (JSF) versions.

**Comment by Rapster** [comment]
This fix reverts this issue: https://github.com/primefaces/primefaces/issues/3917

@tandraschko @melloware I'd like to hear your thoughts? My fix is simple, if an item is disabled it shouldn't be part of the selection, just like when an input is disabled it is not decoded.

**Comment by melloware** [comment]
Agreed, i feel like there may be a better way to solve this PRO user's issue.

**Comment by Rapster** [comment]
First, I don't think there is any bug in here unless you guys agree an element can be "active" and "disabled", I tend to disagree with this but still let me know.

If we want a fix for this user, I might have an idea which would be, first revert that commit and add a new CSS class for those element selected and then disabled.

**Comment by melloware** [comment]
@Rapster i say you submit you PR for review.  I think you have the right idea for fixing both issues.

**Comment by Rapster** [comment]
@mertsincan Would it be possible to request a reproducer as close as his use case to figure out the best way to fix this and #3917 please?
