### ISSUE TITLE
SelectBooleanCheckbox: wrong CSS-Class for Label

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5874]
## 1) Environment
- PrimeFaces version: 9.0
- Does it work on the newest released PrimeFaces version? Version? 8.0 Yes
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
![grafik](https://user-images.githubusercontent.com/10461942/81259924-40a03c00-9039-11ea-9a1c-1f37d87fd6e5.png)

## 3) Actual behavior
![grafik](https://user-images.githubusercontent.com/10461942/81259955-56156600-9039-11ea-8f47-2390b1c3c199.png)

## 4) Steps to reproduce
https://www.primefaces.org/showcase/ui/input/booleanCheckbox.xhtml

This regression was introduced with https://github.com/primefaces/primefaces/commit/c65920d7f8eb9cfbc6a357135b22cf0ff5358a66#diff-dd8ff5bc15f695ed0a5e3c6f0b9c5676

This Commit uses a wrong CSS-class for the label:
![grafik](https://user-images.githubusercontent.com/10461942/81260049-8230e700-9039-11ea-830b-1d1eeb0af510.png)

Same for TriStateCheckboxRenderer.java.

@stolp - Can you please provide a PR to fix this regression?

**Comment by stolp** [comment]
Darn, I will fix this. Thanks for spotting.

**Comment by stolp** [comment]
Adding a reproducer to be double safe here.

[pf-5874.zip](https://github.com/primefaces/primefaces/files/4592184/pf-5874.zip)
