### ISSUE TITLE
ImportEnum does not support inner Enum

### ISSUE THREAD

**Issue by sasynkamil** [primefaces/primefaces#5878]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Not, also 8.0.1 does not work.
- Does it work on the newest sources in GitHub? Not
- Application server + version: Jetty used in primefaces-test project
- Affected browsers: All

## 2) Expected behavior
ImportEnum should support Enum inside the Class. 

## 3) Actual behavior
```console
Exception is thrown:  javax.servlet.ServletException: javax.servlet.ServletException: org.primefaces.test.EnumAsInnerClass.Day
Caused by: java.lang.ClassNotFoundException: org.primefaces.test.EnumAsInnerClass.Day
```

## 4) Steps to reproduce
In java create public class and inside public enum.
In xhtml use importEnum to import this enum.

(project attached)

## 5) Sample XHTML
```xhtml
<p:importEnum type="org.primefaces.test.EnumAsInnerClass.Day"/>
<h:outputText value="#{Day.MONDAY}"/>
```

## 6) Sample bean
```java
public class EnumAsInnerClass {

    public static final int MY_CONSTANT = 1;

    public enum Day {
        MONDAY,
        TUESDAY,
        WEDNESDAY
    }
}
```
[primefaces-test_bug_import_enum.zip](https://github.com/primefaces/primefaces/files/4595951/primefaces-test_bug_import_enum.zip)

**Comment by tandraschko** [comment]
https://stackoverflow.com/questions/7007831/instantiate-nested-static-class-using-class-forname

**Comment by sasynkamil** [comment]
1) Oh, great this '$' is working of course, thank you.
2) Even if I can live with the proposed solution, please rethink if "." shouldn't be supported as well in p:importEnum & p:importConstants. We migrated from OmiFaces and there is this supported. I believe this would be more userfriendly since it would be the same as in java:

```xhtml
xmlns:p="http://primefaces.org/ui"
xmlns:o="http://omnifaces.org/ui"

<p:importEnum type="org.primefaces.test.EnumAsInnerClass$Day"/>
<o:importConstants type="org.primefaces.test.EnumAsInnerClass.Weekend"/>

<h:outputText value="#{Day.MONDAY}"/>
<h:outputText value="#{Weekend.SATURDAY}"/>
```

**Comment by tandraschko** [comment]
we just rely on the java basics and use Class#forName - therefore we wont add hacks here around #forName
