### ISSUE TITLE
Question: how to maintain DataTable#sortMeta (sortBy/sortOrder) in PF8.0

### ISSUE THREAD

**Issue by kaisor6688** [primefaces/primefaces#5879]
Question about DataTable#sortBy.
I want to keep the sortMeta (sortOrder+ sortBy) in backbean. 
in PF7.0 sortBy can be saved/restored in Backbean as List<SortMeta>.
how can it be done in PF8.0?

```
<p:dataTable  sortMode="multiple"  sortBy="#{backBean.sortMetaList}" ...>
<p:ajax event="sort"  listener="#{backBean.onSort}" />
...
</p:dataTable>

 public void onSort() {
    DataTable dataTable = findDataTable();
    List<SortMeta> sortMeta = dataTable.getMultiSortMeta();
    backBean.setSortMetaList(sortMeta);
  }
```

thanx in advance!

kaisor

**Comment by melloware** [comment]
Use `sortMeta` instead of `sortBy`. 

See: https://github.com/primefaces/primefaces/issues/5614

Its a LinkedHashSet so it keeps the order as well.

**Comment by kaisor6688** [comment]
datatable#sortMeta is not exposed in taglib...

**Comment by melloware** [comment]
Going to be fixed with this ticket: https://github.com/primefaces/primefaces/issues/5438

**Comment by tandraschko** [comment]
im sure sortMeta works, maybe it's just not visible for the IDE because of missing taglib entry
