### ISSUE TITLE
AutoComplete: autocomplete=off is not working in chrome

### ISSUE THREAD

**Issue by peda** [primefaces/primefaces#588]
Chrome does not honor the html attribute autocomplete=off instead it does expect autocomplete=false
where this might be an issue with most of the controls, it definitely is with the p:autocomplete control because the chrome autocomplete is shown above the primefaces autocomplete

**Comment by cagataycivici** [comment]
It is a bug of Chrome that should be fixed on Chrome side hopefully.

https://code.google.com/p/chromium/issues/detail?id=352347

**Comment by cagataycivici** [comment]
So do you propose using "false" if user agent is chrome and "off" otherwise?

**Comment by peda** [comment]
yes, I think it would be great if that could be done user agent dependent - even though I'm not a big fan of browser specific implementations it might be useful as Chrome has a major market share

**Comment by tandraschko** [comment]
AFAIR autocomplete=false doesn#t work also very good. The proposed solution is always to clear it via JS or set autocomplete=off to the form. So thats up to the user. Will close it for now.
