### ISSUE TITLE
ThemeSwitcher: Not respecting SelectOne attributes

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#5882]
http://primefaces.org/showcase/ui/misc/themeSwitcher.xhtml

If you open the first selectOneMenu, the second selectOneMenu is displayed OVER the overlay of the first.

Can someone check it?

**Comment by melloware** [comment]
I can confirm but what is really strange is it  extends SelectOneMenu and that widget does not have this issue.
