### ISSUE TITLE
SelectXXX: Implement hideNoSelectionOption attribute

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#5886]
## 1) Environment
- PrimeFaces version: 8.0
- Affected browsers: All

## 2) Expected behavior
The JSF standard components support the `hideNoSelectionOption="true|false"` attribute which automatically removes the `f:selectItem` marked with `noSelectionOption="true"`.

Official testcase xHTML: https://github.com/javaserverfaces/mojarra/blob/master/test/servlet30/systest/src/main/webapp/standard/selectOneLiteralHideNoSelectionOption.xhtml

## 3) Actual behavior
The attribute `noSelectionOption` on `f:selectItem` has not the desired effect.

## 4) Steps to reproduce
 - Create a SelectOneMenu with the attribute `hideNoSelectionOption`
 - Mark one item as `noSelectionOption `
 - Open the dropdown, the `noSelectionOption` item is visible
 - Select some valid item
 - Open the dropdown again, the `noSelectionOption` should be gone but it is still visible

## 5) Sample XHTML
``` html
<p:selectOneMenu value="#{testBean.selection}" hideNoSelectionOption="true">
    <p:ajax process="@this" update="@this" />

    <f:selectItem itemValue="#{null}" itemLabel="Please select..." noSelectionOption="true" />
    <f:selectItems value="#{testBean.itemList}" />
</p:selectOneMenu>
```

## 6) Sample bean
``` java
@ViewScoped
@Named
public class TestBean implements Serializable {
    private Integer _selection;
    private List<SelectItem> _itemList;

    @PostConstruct
    public void __initialize() {
        _itemList = new ArrayList<>();
        _itemList.add(new SelectItem(1, "Item 1"));
        _itemList.add(new SelectItem(2, "Item 2"));
        _itemList.add(new SelectItem(3, "Item 3"));
    }

    public Integer getSelection() {
        return _selection;
    }
    public void setSelection(Integer selection)  {
        _selection = selection;
    }

    public List<SelectItem> getItemList() {
        return _itemList;
    }
}
```

**Comment by melloware** [comment]
Based on @fanste comment here: https://github.com/primefaces/primefaces/pull/5909#issuecomment-630648609

This new feature doesn't work exactly like native JSF one.  Well all the native JSF one is doing is adding an automatic AJAX call after you make a selection.  I would rather not add that automatic AJAX call to 10+ components that this is implemented for. So to accomplish the exact same behavior simply add an EL expression in your `hideNoSelectionOption="#{not empty testView.testString}"` like my example below and now the JSF and PF implementations do the exact same thing.

```xml
<h:form>
    <b>JSF Standard dropdown</b><br />
    <h:selectOneMenu value="#{testView.testString}" hideNoSelectionOption="true">
        <f:ajax execute="@this" render="@this" />

        <f:selectItem itemValue="" itemLabel="-- please select --" noSelectionOption="true" />
        <f:selectItem itemValue="t1" itemLabel="Test 1" />
        <f:selectItem itemValue="t2" itemLabel="Test 2" />
    </h:selectOneMenu>

    <br />
    <br />
    <br />
	
    <b>PrimeFaces dropdown</b><br />
    <p:selectOneMenu value="#{testView.testString}" hideNoSelectionOption="#{not empty testView.testString}">
        <p:ajax process="@this" update="@this" />

        <f:selectItem itemValue="" itemLabel="-- please select --" noSelectionOption="true" />
        <f:selectItem itemValue="t1" itemLabel="Test 1" />
        <f:selectItem itemValue="t2" itemLabel="Test 2" />
    </p:selectOneMenu>
</h:form>
```

**Comment by melloware** [comment]
Showcase updated to reflect this new example: https://github.com/primefaces/primefaces-showcase/pull/151

**Comment by fanste** [comment]
>  Well all the native JSF one is doing is adding an automatic AJAX call after you make a selection

I can't see that automatic AJAX. I've updated my test project with a `h:selectOneMenu` without a nested `f:ajax` and the dropdown is not updated after the selection changes. So you always have to manually add that AJAX behaviour.

In my opinion, the way the attribute works should be the same, otherwise it just confuses unnecessarily.

**Comment by melloware** [comment]
Yuck. Then they must be doing it with Javascript which means 10 PrimeFaces components need to add this client side Javascript to their component.

Also components like "SelectOne" also have Advanced mode for rendering any HTML you want with  the Advanced example here: https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml .  You will have to write custom client side JS for each of these including the different modes like Advanced rendering vs normal rendering for removing the noSelectOption.

My current solution works with all of these already without any JS code and just an EL expression + AJAX call.   

Is it really worth writing all that JS code in 10 components? If the answer is YES then  feel free to work on a PR to add that client side JS to all 10 components.

**Components to modify:**
- multiselectlistbox
- selectcheckboxmenu
- selectmanybutton
- selectmanycheckbox
- selectmanymenu
- selectonebutton
- selectonelistbox
- selectonemenu
- selectoneradio
- themeswitcher
