### ISSUE TITLE
ColorPicker: attribute "required" is ignored

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#5887]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Payara 5.181
- Affected browsers: Firefox, Chrome, ...

## 2) Expected behavior

When the ColorPicker value is initially `null` or an empty string and the attribute `required` is set to `true`, then the validation of the form should fail on submit and an error message should be displayed.

## 3) Actual behavior

The attribute `required` is ignored and no error message is displayed.

## 4) Steps to reproduce

See sample view and bean.

## 5) Sample XHTML

_Hint: When commenting out the color picker and uncommenting the input text an error message is displayed._
```
        <h:form id="fmT">
            <div class="ui-g">
                <!--chartColorHex-->
                <div class="ui-g-12">
                    <p:outputLabel for="chartColorHex"
                                   value="chartColorHex:" />
                    <p:colorPicker id="chartColorHex"
                                   required="true" requiredMessage="Field 'chartColorHex' is required!"
                                   value="#{testView.chartColorHex}" />
                    <!--<p:inputText id="chartColorHex"
                                    required="true" requiredMessage="Field 'chartColorHex' is required!"
                                    value="#{testView.chartColorHex}" />-->
                    <p:message for="chartColorHex" />
                </div>

                <div class="ui-g-12">
                    <p:commandButton action="#{testView.save()}"
                                     icon="fa fa-save"
                                     update="@form"
                                     value="Save!" />
                </div>
            </div>
        </h:form>
```

## 6) Sample bean

```
    @Named
    @ViewScoped
    public class TestView
            implements Serializable {

        @NotNull
        private String chartColorHex;

        public String getChartColorHex() {
            return chartColorHex;
        }

        public void setChartColorHex(String chartColorHex) {
            this.chartColorHex = chartColorHex;
        }

        public void save() {
            System.out.println("TestView.save() -> '" + chartColorHex + "'");
        }

    }
```

**Comment by melloware** [comment]
Reproducer: 
[pf-5587.zip](https://github.com/primefaces/primefaces/files/4617286/pf-5587.zip)

**Comment by ltlBeBoy** [comment]
I was just wondering whether it is a problem that this component has no attribute `disabled`. For example, if the attribute `required` is set to `true` but the value of the component should be ignored until a condition is met.

**Comment by melloware** [comment]
Let me check disabled.

**Comment by melloware** [comment]
Can you open another issue asking for ColorPicker to have a disabled attribute please?

**Comment by ltlBeBoy** [comment]
OK.
Thank you for this fix!

**Comment by melloware** [comment]
No problem. I just want to track adding disabled flag as separate from this original issue. But both will be fixed
