### ISSUE TITLE
SelectOneMenu: not trapping the ENTER key.

### ISSUE THREAD

**Issue by nokiajavi** [primefaces/primefaces#5889]
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Apache Tomcat 9.5
- Affected browsers: All

## 2) Expected behavior
When a form has a p: defaultCommand, the p: selectOneMenu component should not execute the defaultCommand action when you press the ENTER key in the selectonemenu value list

## 3) Actual behavior
the p: selectOneMenu component, when pressing ENTER KEY on a value in the list, the action of the button associated with the defaultCommand is executed, this only happens if the component does not have the filter = "true" property. 
If there is no defaultCommand inside the form, the component works correctly.

## 4) Steps to reproduce
1. Create un form with un selectonemenu, commandButton and a defaultCommand what link to the button.
2. Open values from selectoneMenu
3. Press ENTER KEY in a value.
4. The form is sended

## 5) Sample XHTML

```
<h:form id="form">
		<p:selectOneMenu>
			<f:selectItem itemValue="1" itemLabel="uno"/>
			<f:selectItem itemValue="2" itemLabel="dos"/>
			<f:selectItem itemValue="3" itemLabel="tres"/>
			<p:ajax event="change"></p:ajax>
		</p:selectOneMenu>
		
		<p:defaultCommand target="boton1"></p:defaultCommand>
		<p:inputText id="input" required="true" label="INPUT" />
		<p:messages id="mesinput" showDetail="true" showSummary="false"/>
		
		<p:commandButton id="boton1" ajax="true" process="@form" update="@form" validateClient="true" value="BOTON"></p:commandButton>
	</h:form>
```

Case in which it does not fail

```
<h:form id="form">
		<p:selectOneMenu filter="true" filterMatchMode="startsWith">
			<f:selectItem itemValue="1" itemLabel="uno"/>
			<f:selectItem itemValue="2" itemLabel="dos"/>
			<f:selectItem itemValue="3" itemLabel="tres"/>
			<p:ajax event="change"></p:ajax>
		</p:selectOneMenu>
		
		<p:defaultCommand target="boton1"></p:defaultCommand>
		<p:inputText id="input" required="true" label="INPUT" />
		<p:messages id="mesinput" showDetail="true" showSummary="false"/>
		
		<p:commandButton id="boton1" ajax="true" process="@form" update="@form" validateClient="true" value="BOTON"></p:commandButton>
	</h:form>
```

## 6) Sample bean

N/A

**Comment by melloware** [comment]
Reproducer: 
[pf-5589.zip](https://github.com/primefaces/primefaces/files/4617230/pf-5589.zip)

**Comment by melloware** [comment]
If you need this fix right now just add this JS code:
```javascript
PrimeFaces.widget.SelectOneMenu.prototype.handleEnterKey = function(event) {
    if (this.panel.is(':visible')) {
        this.selectItem(this.getActiveItem());
    }

    event.preventDefault();
    event.stopPropagation();
};
```

**Comment by nokiajavi** [comment]
Thanks for the code! You're great.

**Comment by melloware** [comment]
This is actually the better fix...

```javascript
PrimeFaces.widget.SelectOneMenu.prototype.handleEnterKey = function(event) {
    if (this.panel.is(':visible')) {
        this.selectItem(this.getActiveItem());
        event.stopPropagation();
    }

    event.preventDefault();
};
```

**Comment by nokiajavi** [comment]
Thank you very @melloware, I will update it in my code.
