### ISSUE TITLE
Media: late decoding of the value expression does not resolve params and no error log is produced

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#5903]
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? not tested
- Does it work on the newest sources in GitHub? not tested
- Application server + version: Tomcat 8.0.39, Tomcat 8.5.55
- Affected browsers: any

## 2) Expected behavior

I can specify the `p:media` `value` attribute using some previously defined `param` in my facelet.
Or at least, if it can't be done, an exception is produced in the server log to explain what is wrong, when trying to render the document.

## 3) Actual behavior

No document is displayed, no error is produced at all, the generated URL returns a 404 and the generated `<object>` is simply invisible.

## 4) Steps to reproduce

- suppose you have defined this in your facelet:

```xml
<ui:param name="bean" value="#{myBean}" />
```
- then you use:

```xml
<p:media value="#{bean.myStreamedDocument}" player="pdf" />
```

- please note that in the above example `bean.myStreamedDocument` returns a `StreamedContent` instance
- no PDF document is displayed

This seems to be related to the way in which PrimeFaces encodes and decodes the `value` expression when rendering the `p:media` component. This StackOverflow reply was enlightening:
https://stackoverflow.com/a/35341461/1465635
It talks about `p:graphicImage`, but I suspect the issue here is the same.
If changing how this is handled is too problematic, I would appreciate at least an exception in the log saying that `bean` cannot be resolved. Finding the actual problem (and BalusC reply) was really hard.

## 5) Sample XHTML

```xml
<ui:param name="bean" value="#{myBean}" />

<p:media value="#{bean.myStreamedDocument}" player="pdf" />
```

## 6) Sample bean

```
public class MyBean {
  public StreamedContent getMyStreamedDocument() {
    // let "is" be a FileInputStream built on a pdf file taken somewhere
    return new DefaultStreamedContent(new BufferedInputStream(is), "application/pdf", "TEST.pdf.xhtml");
  }
}
```

**Comment by tandraschko** [comment]
Thats by desing and therefore a wont fix.
The VE needs to be evaluated in the resource request, not when rendering the view.
Otherwise we would need to evaluate the StreamedContent when rendering the view and store it in the session. This is a no-go for me.

If you need to pass a info, you can pass infos to the resource request via f:param on the graphicImage / media.

**Comment by tandraschko** [comment]
If you can debug our code, i think we already throw a exception when evaluating the ValueExpression fails 
See StreamedContentHandler ln64

Should we just add a logging statement here? (ln 111)

**Comment by mauromol** [comment]
@tandraschko I'll try to debug and see what happens at that row next weekd, but I'm sure no log at all gets printed to the console. Probably the expression is simply evaluated to `null` because, in my case, `bean` is not a managed bean at that point. But this really doesn't help to understand what is wrong. Maybe a hint in the documentation could help to avoid such errors.

Would you be so kind to show me just a tiny example of what can be done by "passing infos to the resource request via f:param on the graphicImage/media"?

**Comment by tandraschko** [comment]
you can pass the content of your method param via url like:
https://stackoverflow.com/questions/9320557/how-to-use-pgraphicimage-with-streamedcontent-inside-uirepeat-hdatatable-pda

**Comment by mauromol** [comment]
@tandraschko 

> If you can debug our code, i think we already throw a exception when evaluating the ValueExpression fails
> See StreamedContentHandler ln64
> 
> Should we just add a logging statement here? (ln 111)

In PF 6.2 lines are different, here is the piece of code that handles the `ValueExpression`:

```java
ELContext eLContext = context.getELContext();
ValueExpression ve = context.getApplication().getExpressionFactory().createValueExpression(
        context.getELContext(), dynamicContentEL, StreamedContent.class);
streamedContent = (StreamedContent) ve.getValue(eLContext);

if (streamedContent == null || streamedContent.getStream() == null) {
    if (externalContext.getRequest() instanceof HttpServletRequest) {
       externalContext.responseSendError(HttpServletResponse.SC_NOT_FOUND,
                ((HttpServletRequest) externalContext.getRequest()).getRequestURI());
    }
    else {
       externalContext.responseSendError(HttpServletResponse.SC_NOT_FOUND, null);
    }
    return;
}
```

In my original example, the evaluation of the `ValueExpression` assigned to `streamedContent` is simply `null` and a 404 is produced, with no logging at all.

Probably a log entry saying that my expression (`#{bean.myStreamedDocument}` in my case) evaluates to `null` would have helped me to guess the problem was bound to late evaluation (a concept that sometimes pops in other contexts too) rather than to other obscure causes.

So, I would suggest to add such a log entry.

**Comment by tandraschko** [comment]
ok, please add a log statement if the StreamedContent is null and provide a PR!
