### ISSUE TITLE
Autocomplete: Custom empty result action

### ISSUE THREAD

**Issue by john182** [primefaces/primefaces#5905]
## 1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior

Possibility to customize, container for no results found, so that it can for example add a button asking the user if he wants to create a new record, EX:

![image](https://user-images.githubusercontent.com/10438644/82100454-0e00de00-96e0-11ea-91b3-2acf5025bafe.png)

## 3) Actual behavior

..

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by melloware** [comment]
So the request here is to allow for either `emptyMessage` or an `empty` facet like...
```xml
<f:facet name="empty">
    No results found <p:commandButton action="" />
</f:facet>
```

**Comment by jepsar** [comment]
I would keep this in line with how "moreText" works. It can be styled using the `ui-autocomplete-moretext` class and the click could be handled using the `moreText` click event.

A class is already present (`ui-autocomplete-emptyMessage`). The only thing missing is a click listener event.
