### ISSUE TITLE
"my" and "at" option in p:autoComplete

### ISSUE THREAD

**Issue by chrisu86** [primefaces/primefaces#591]
Im missing a "my" and "at" option in p:autoComplete to define the position of the suggestions panel.
I want to show the suggestions on the right side of the input field:

![autocomplete right](https://cloud.githubusercontent.com/assets/13551170/9002119/4e47dd7c-3760-11e5-9884-cd53d45fc173.JPG)

Here is my current solution to this problem:
1. The autocomplete field
   
   ```
    <p:autoComplete id="myAutocomplete" panelStyleClass="autocompleteRightTop">
        <p:ajax event="query" oncomplete="moveAutocompletePanelRightTop('myAutocomplete')"/>
    </p:autoComplete>
   ```
2. Javascript for panel positioning
   
   ```
   function moveAutocompletePanelRightTop(inputId){
       var id = '#'+inputId;
   
       var input = $(id);
       var inputPosition = input.position();
       var inputWidth = $(id).width();
   
       var left = inputPosition.left+inputWidth;
       var top = inputPosition.top;
   
       $("head").append("<style>.autocompleteRightTop { TOP: "+top+"px !important; LEFT: "+left+"px !important;}</style>");
   }
   ```

**Comment by cagataycivici** [comment]
Available for 5.2.11 and 5.3.
