### ISSUE TITLE
DatePicker: with pattern has confusing behaviour when editing

### ISSUE THREAD

**Issue by pasirr** [primefaces/primefaces#5912]
p:datePicker in PrimeFaces-8.0 (and earlier) seem to have a confusing behavior when editing the input field. 

In PrimeFaces Showcase, p:datePicker with id="german" (that has pattern="dd.MM.yyy" and locale="de") : enter value 01.01.2020, click between 0 and 1 either on day or month and press Backspace (like user wants to change 01 to 10). -> the cursor jumps to the end of input value and nothing gets deleted. This is at least confusing and can cause invalid values to be entered if user does not check carefully what happens on page. 

This p:datePicker behavior could probably be categorized as a bug because p:calendar behaves more logically with same input sequence. 

This might be related to handling of locale as kukeltje on PrimeFaces forum indicated that it seems to work correctly with some locales.

**Comment by melloware** [comment]
Confirmed this is still happening in 9.0-SNAPSHOT as well

**Comment by christophs78** [comment]
Must be related to the client-side-JavaScript of DatePicker. But i do not think it´s direct related to the locale. (IMO client-side JS does not have „real“ knowledge of the locale. A bit simplified it only knows which localized labels to show for weekdays and monthnames.)
It may be related to specific patterns.

**Comment by christophs78** [comment]
https://primefaces.org/primeng/showcase/#/calendar does not seem to have this issue. Maybe there is some fix for PrimeNG we can backport.

**Comment by melloware** [comment]
I debugged why.  The method `parseDate` is parsing `27.7.2019` for format `dd.mm.yy` correctly back into `27.07.2019` which is happening in `onUserInput` when the user presses a key.  Normally its expecting an exception if the format is not correct.

I think i will check the length of the format vs value in the `onuserInput` to allow this functionality.

**Comment by melloware** [comment]
@christophs78 I just put this patch in for a customer and they are very happy with the new behavior.

**Comment by mertsincan** [comment]
Thanks @christophs78 ;)
