### ISSUE TITLE
Calendar: java.lang.Object not supported

### ISSUE THREAD

**Issue by ohlsen3000** [primefaces/primefaces#5913]
**Describe the defect**
Evaluating PF8 I started to remove legacy LocalDateConverter for all Calendars, since it is not required anymore. It works so far. But if the the LocalDate value resides in a generic structure it causes the error mentioned above. 

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _MyFaces 2.2.10_
 - Affected browsers: _ALL_

**To Reproduce**
1. Use a calendar that is connected to a LocalDate in a generic class
2. Do not use a custom converter

**Expected behavior**
LocalDate is written to the bean without an error or failed validation

**Example XHTML**
```xml
<p:calendar value="#{myView.rangeDate.min}"/>
```

**Example Bean**
```java
@Named
@WindowScoped
public class MyView  implements  Serializable {

    Range<LocalDate> rangeDate = new Range<>();

    public Range<LocalDate> getRangeDate() {
        return rangeDate;
    }

    public void setRangeDate(final Range<LocalDate> rangeDate) {
        this.rangeDate = rangeDate;
    }
}


public class Range<T> implements Serializable {

    private static final long serialVersionUID = 1L;

    private transient T min;
    private transient T max;

    public T getMin() {
        return min;
    }

    public void setMin(final T min) {
        this.min = min;
    }

    public T getMax() {
        return max;
    }

    public void setMax(final T max) {
        this.max = max;
    }
}
```

**Comment by tandraschko** [comment]
Please ALWAYS try a trunk version before creating a issue. 
I remember that we already fixed something regarding generics.

**Comment by ohlsen3000** [comment]
Just checked current master (9.0-SNAPSHOT), same problem there.

**Comment by tandraschko** [comment]
@christophs78 would you like to check this?
i think we cant fix it easily. We would need to get the parent field etc etc.
Mabye its better to introcude a attribute, to pass the type. like valueType="....LocalDate"

**Comment by christophs78** [comment]
I will look at this within the next week or so.
During our iterations between 7 and 8 we had something like the valueType for some time. But we removed it because we thought/hoped we dont need it. I will look how easy/hard it´s with our current codebase to re-introduce such an attribute.

**Comment by christophs78** [comment]
@ohlsen3000 : Can you work around this this by using `f:convertDateTime`?

```
<p:calendar value="#{myView.rangeDate.min}"/>
    <f:convertDateTime type="localDate" />
</p:calendar>
```

**Comment by melloware** [comment]
reproducer:
[pf-5913.zip](https://github.com/primefaces/primefaces/files/4682287/pf-5913.zip)

And I confirmed that `<f:convertDateTime type="localDate" />` does not fix it I still get a Conversion error.

**Comment by christophs78** [comment]
I´ll look into this. At this point in time i would personally prefer getting <f:convertDateTime type="localDate" /> working over building our own valueType="localDate" - mechanism.

**Comment by melloware** [comment]
100% agree

**Comment by christophs78** [comment]
> And I confirmed that `<f:convertDateTime type="localDate" />` does not fix it I still get a Conversion error.

@melloware : Just checked this with your reproducer. Seems like you need to add a pattern to `f:convertDateTime`.

Following XHTML work´s on my dev-machine. The pattern may depend on locale, ...
```
<p:calendar value="#{testView.rangeDate.min}">
    <f:convertDateTime type="localDate" pattern="dd.MM.yy" />
</p:calendar>
```

Can you cross check this on your dev-machine?

**Comment by melloware** [comment]
It works for me if my patterns match..
```html
<p:calendar value="#{testView.rangeDate.min}" pattern="dd.MM.yy">
	<f:convertDateTime type="localDate" pattern="dd.MM.yy" />
</p:calendar>
```

But if I do..
```html
<p:calendar value="#{testView.rangeDate.min}">
	<f:convertDateTime type="localDate" pattern="dd.MM.yy" />
</p:calendar>
```

I get "05/28/20 could not be understood as a date" so the calendar is defaulting to my locale's format "MM/dd/yy".

**Comment by christophs78** [comment]
Yes, there seems to be some difference in default-pattern between PrimeFaces (Calendar/DatePicker) and base JSF (f:convertDateTime).
It´s not ideal but IMO it´s a work-around for this corner case.

I looked some weeks/months ago for an other DatePicker-generics-Issue into how to detect the type for complex usecases with generics. Spring Framework seems to have a solution for this. But we do not want the add Spring Famework as an dependency. And the Spring type-detection-code was IMO way to complex to port it to PrimeFaces, or implement something like this on our own.

**Comment by christophs78** [comment]
We discussed this as part of https://github.com/primefaces/primefaces/issues/5656.

https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/GenericTypeResolver.java Is the Spring-Solution to this.

**Comment by melloware** [comment]
Well it might be worth bringing in as a util?

**Comment by melloware** [comment]
Copying it I mean...not including Spring Framework.

**Comment by christophs78** [comment]
It´s not done with this single class. GenericTypeResolver depends on some more classes, ...

**Comment by melloware** [comment]
Ughh.  Yes I see it now it spiderwebs to basically about 30-50 Spring classes.

**Comment by christophs78** [comment]
https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java#L282

Maybe we should change
`if (type == null) {`
to something like
`if (type == null || type.equals(Object.class)) {`

So we would use the java.time.* - defaults as fallback.

It may not be ideal but it would be a bit better than the current implementation.

**Comment by melloware** [comment]
I am ok with that.  Anything we can do to keep improving the implementation.
