### ISSUE TITLE
Timeline: Localization pt_BR with warning

### ISSUE THREAD

**Issue by claudioweiler** [primefaces/primefaces#5920]
**Describe the defect**
Permanent warning when timeline is loaded:
`WARNING: options.locales['pt_BR'] not found. See https://visjs.github.io/vis-timeline/docs/timeline/#Localization`

Maybe related: https://github.com/primefaces/primefaces/commit/434edac3a89369f3d65b1b5ded56476cb34d0861

**Reproducer**
Set default locale to 'pt_BR' in faces-config.

**Environment:**
 - PF Version: 8.0
 - JSF + version: Mojarra 2.3.9
 - Affected browsers: ALL

**To Reproduce**
1. Open page with timeline
2. See console warning

**Expected behavior**
No warning

**Comment by melloware** [comment]
thanks for the hint i think it is the same problem as Schedule fixed already.  I will let you know.

**Comment by melloware** [comment]
I think the real problem is that Timeline doesn't have a Brazlian translation see there available locales here: https://visjs.github.io/vis-timeline/docs/timeline/#Localization

Port-Brazil is not one of them so maybe you can volunteer to donate a pt-BR translation to the vis-timelime project.

Here are their current locales: https://github.com/visjs/vis-timeline/blob/master/lib/timeline/locales.js

**Comment by claudioweiler** [comment]
PR: https://github.com/visjs/vis-timeline/pull/490

**Comment by melloware** [comment]
@claudioweiler do you mind providing a PT translation for server side as well. See this ticket: https://github.com/primefaces/primefaces/issues/6995

**Comment by claudioweiler** [comment]
Hi @melloware!

Sorry, I don't understand what should be done.

I edited https://github.com/primefaces/primefaces/wiki/Locales, that already has an `pt_BR` translation snippet, but has an minor typo. Also edited `en` snippet, that was outdated, to be equals to https://github.com/primefaces/primefaces/blob/master/src/main/resources/org/primefaces/Messages_en.properties.

Should I just add an comment with this snippet on ticket #6995, or should I post a PR to primefaces?

Or maybe you want a specific `pt` translation? In that case, I can't help with confidence, there are subtle differences between `pt` and `pt_BR` that I am not aware. In the absence of this translation, `pt_BR` can be copied to `pt` until someone correct this.

**Comment by melloware** [comment]
No just add a comment to the #6995 that you have reviewed the pt_BR on the Wiki! Thanks!
