### ISSUE TITLE
DataTable: with selectionMode="multiple/single" keeps a focus on previous selected row after selects another row

### ISSUE THREAD

**Issue by Basyav** [primefaces/primefaces#5922]
## 1) Environment:
 - PF Version: 8.0.1(reproducible in 9.0-SNAPSHOT)
 - JSF + version:  Mojarra 2.3.13
 - Affected browsers: Chrome, Firefox

## 2) Steps to reproduce the behavior:
Reproducible on the tables with id="singleDT" and id="multipleDT" [Showcases](https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml)
1. Select a row in the table.
2. Switch to other tab of the browser.
3. Return to the tab with the table and select other row.

## 3) Actual behavior:
Previous selected row is not selected but focus is kept on it.

## 4) Expected behavior:
Previous selected row is not selected and is not kept focus

**Comment by Basyav** [comment]
As workaround:
```
<p:dataTable>
   <p:ajax event="rowSelect" listener="#{dataTableHelper.selectTableRow}" global="false"
                   oncomplete="selectTableRowCallback(xhr, status, args)"/>
</p:dataTable>

public void selectTableRow(SelectEvent event) {
    String tableId = ((DataTable) event.getSource()).getClientId();
    PrimeFaces.current().ajax().addCallbackParam("tableId", tableId);
}

function selectTableRowCallback(xhr, status, args) {
    if (status === 'success') {
        let tableId = '#' + args.tableId.replace(/:/g,'\\:');
        $(tableId + '_data tr').removeClass('ui-state-hover');
    } else {
        console.log('selectTableRowCallback() error');
}
```

**Comment by melloware** [comment]
I have a much simpler solution for you. Just add this JS to your app.
```javascript
PrimeFaces.widget.DataTable.prototype.unhighlightRow = function(row) {
    row.removeClass('ui-state-highlight ui-state-hover').attr('aria-selected', false);
};
```

**Comment by Basyav** [comment]
Thank you for simpler solution

**Comment by melloware** [comment]
No problem! Thanks for reporting
