### ISSUE TITLE
DataTable: Add support for RequestScoped LazyDataModel in editable mode

### ISSUE THREAD

**Issue by yanLanglois** [primefaces/primefaces#593]
There is a NullPointerException when rowEdit and rowEditCancel are triggered within a dataTable with : 
- lazy = true
- editable = true
- RequestScoped LazyDataModel

For more information : http://forum.primefaces.org/viewtopic.php?f=3&t=42886

**Comment by Pollum** [comment]
I've discovered the same problem and added my stacktrace to the primefaces forum topic.

**Comment by melloware** [comment]
I always use @ViewScoped for my LazyDatatables.  @RequestScoped implies you want to re-create the LazyDataModel on every Ajax request etc.  Which defeats the purpose of the LazyDataModel being able to page data etc.

**Comment by tandraschko** [comment]
IMO it should be possible to use a lazy datatable within a stateless view! This requires a lit bit work on the js side, too..

**Comment by tandraschko** [comment]
i see the problem now and we can fix it as rowExpand already has a fix for it.

**Comment by tandraschko** [comment]
still not working, will leave it as it is now and look again in the future.
Would be great if someone could check it.

The fix i applied for it is in RowExpand:
'''

        if (table.isLazy() && ((LazyDataModel) table.getValue()).getWrappedData() == null) {
            table.loadLazyData();
        }
'''

but even when adding this before:
```
wrapperEvent = new RowEditEvent(this, behaviorEvent.getBehavior(), getRowData());
```

creates a exception

**Comment by tandraschko** [comment]
the same exception will likely occur in rowToggle request as getRowData() is called before lazyData is loaded. Therefore the above fix should actually work.
