### ISSUE TITLE
Task: Move configs to /src/conf

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#5931]
**Description**
To have less clutter in the root of the project I would like to do what other projects have done and move configs to `/src/conf` folder.

Also removing the CHANGLOG.MD as no one is keeping it up to date and its not necessary with Git Labels and Tags.

**Comment by NicolaIsotta** [comment]
Hi @melloware 
To reduce the clutter even more, the .MD files can be moved to the .github folder
Sources: [README](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes) [CONTRIBUTING](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) [CODE_OF_CONDUCT](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project)

**Comment by stolp** [comment]
I personally think it is good practice to place such files in the top level directory and not hide them in a dot folder. People should read them. Interesting to know though.

**Comment by melloware** [comment]
Hmmm I didn't know that either.  I personally like having a clean root folder.
