### ISSUE TITLE
PrimeExceptionHandler doesn't see error pages defined in a web fragment

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#594]
ConfigContainer should parse `META-INF/web-fragment.xml` as well.

**Comment by tandraschko** [comment]
Could you please post a real use case?
I actually don't include such a "application dependent" config in a shared jar.

**Comment by VsevolodGolovanov** [comment]
It's a modular enterprisey web application. A customer can purchase a set of modules, and that defines which modules get included in the build.
The modules are implemented as web fragment projects: servlets look up META-INF/web-fragment.xml specific configuration, JSF parses META-INF/faces-config.xml, sees templates and other resources in META-INF/resources, CDI discovers beans. It works well.

**Comment by tandraschko** [comment]
Done, please test it!
