### ISSUE TITLE
FileUpload: default values of `invalidSizeMessage`, `invalidFileMessage` and `fileLimitMessage`

### ISSUE THREAD

**Issue by doleron** [primefaces/primefaces#5941]
**Description**

In the docs the default value of `invalidSizeMessage`, `invalidFileMessage` and `fileLimitMessage` is null but in 'advanced' mode these attributes have the following default values: 'Invalid file size', 'Invalid file type' and 'Maximum number of files exceeded'.

For simple mode the default value is null. As an enhancement, the default value for simple mode could be the same as the ones in advanced mode.

**Comment by doleron** [comment]
I just checked out the code and realized that  `invalidFileMessage` and `fileLimitMessage` aren't even defined for simple mode. Thus, they could be defined and initialized properly.
In the case of `invalidSizeMessage` if not explicitely defined, the attribute is currently initialized with the 4-chars string "null" (not the null reference).

**Comment by melloware** [comment]
Is this just a documentation change a code change or both?  Were you going to submit a PR?

**Comment by doleron** [comment]
In my understanding this need to be changed in both docs and code:
+ changing FileUploadRenderer.java/2-fileupload.js to define/initialize the attributes
+ updating docs according
I'm glad to submit a PR for this. Should I wait for the merge of this another PR https://github.com/primefaces/primefaces/pull/5940 before submit this new one?

**Comment by melloware** [comment]
Yes you submit another PR.  What you should do is in your fork...create a branch so that way you are not working in "master".
See this guide on how to create a branch: https://guides.github.com/activities/hello-world/

I would call this branch "PF-5941" I always like to name my branches after the ticket # they fix.  Then you can make this fix on that branch and submit the PR.  That way the PR only contains what you have fixed.

In fact after you commit and push on that branch GitHub will have a yellow banner popup that says "Do you want to submit a PR?" because it knows you are working in a branch.

**Comment by doleron** [comment]
Ok, I'm working on the PR PF-5941 right now. I dug a little bit more into the behavior of `FileUpload` in `simple` mode. Let me summarize what I have found so far:

**Comment by doleron** [comment]
1) The default value of `invalidSizeMessage` is actually a "null" String (not a null ref). Follow the comparasion of simple/advanced modes using both default and custom `invalidSizeMessage`:

![image](https://user-images.githubusercontent.com/9665358/82688333-18b2fa00-9c2f-11ea-8339-00872d7575e8.png)

This is the code:
```xhtml
<h:outputText value="simple mode - default message" />
<p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" sizeLimit="10240" />
<h:outputText value="simple mode - custom message" />
<p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" sizeLimit="10240" invalidSizeMessage="File to big"/>
<h:outputText value="advanced mode - default message" />
<p:fileUpload value="#{fileUploadView.file}" mode="advanced" sizeLimit="10240"/>
<h:outputText value="advanced mode - custom message" />
<p:fileUpload value="#{fileUploadView.file}" mode="advanced" sizeLimit="10240" invalidSizeMessage="File to big"/>
```

**Comment by doleron** [comment]
2) There is no validation or even a definition of `allowTypes `/`invalidFileMessage` in simple mode:

![image](https://user-images.githubusercontent.com/9665358/82688725-bad2e200-9c2f-11ea-87da-b844e4a3a8bb.png)
 
This is the code:
```xhtml
<h:outputText value="simple mode - default message" />
<p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" allowTypes="/(\.|\/)(png)$/" />
<h:outputText value="simple mode - custom message" />
<p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" allowTypes="/(\.|\/)(png)$/" invalidFileMessage="File type not allowed"/>
<h:outputText value="advanced mode - default message" />
<p:fileUpload value="#{fileUploadView.file}" mode="advanced" allowTypes="/(\.|\/)(png)$/"/>
<h:outputText value="advanced mode - custom message" />
<p:fileUpload value="#{fileUploadView.file}" mode="advanced" allowTypes="/(\.|\/)(png)$/" invalidFileMessage="File type not allowed"/>
```

**Comment by doleron** [comment]
3) `fileLimit` is also not handled by validation in simple mode. In the following print I tried to input 3 files when the limit is 2.

![image](https://user-images.githubusercontent.com/9665358/82689395-c5da4200-9c30-11ea-9ee7-067861cd552a.png)

It is noteworthy that `advanced` mode deal with it properly.

Code:

```xhtml
<h:outputText value="simple mode - default message" />
<p:fileUpload value="#{fileUploadView.files}" mode="simple" skinSimple="true" multiple="true" fileLimit="2"/>
<h:outputText value="simple mode - custom message" />
<p:fileUpload value="#{fileUploadView.files}" mode="simple" skinSimple="true" multiple="true" fileLimit="2" fileLimitMessage="Max number of files reached"/>
<h:outputText value="advanced mode - default message" />
<p:fileUpload value="#{fileUploadView.files}" mode="advanced" multiple="true" fileLimit="2"/>
<h:outputText value="advanced mode - custom message" />
<p:fileUpload value="#{fileUploadView.files}" mode="advanced" multiple="true" fileLimit="2" fileLimitMessage="Max number of files reached"/>
```

**Comment by doleron** [comment]
4) The displayed messages are nullified by using `messageTemplate` in combination with `simple` mode:
![image](https://user-images.githubusercontent.com/9665358/82689861-86602580-9c31-11ea-9dc8-4cd1f003b1f1.png)

Code:
```xhtml
<h:outputText value="simple mode - default template" />
<p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" sizeLimit="10240"/>
<h:outputText value="simple mode - custom template" />
<p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" sizeLimit="10240" messageTemplate="The file name is {name} and File size is {size}"/>
<h:outputText value="advanced mode - default template" />
<p:fileUpload value="#{fileUploadView.file}" mode="advanced" sizeLimit="10240"/>
<h:outputText value="advanced mode - custom template" />
<p:fileUpload value="#{fileUploadView.file}" mode="advanced" sizeLimit="10240" messageTemplate="The file name is {name} and File size is {size}"/>
```
