### ISSUE TITLE
Dialog framework: JS error on close "Widget not available"

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#5942]
**Describe the defect**
When closing a Dialog with closeDynamic a Javascript error is displayed (note: only if PROJECT_STAGE=Development)

**Environment:**
 - PF Version: 8.0_ (I think there was no error with PF7.0)
 - JSF + version: MyFaces 2.2.7
 - Affected browsers: ALL

**To Reproduce**
Steps to reproduce the behavior in the example below:
1. Click on 'View'
2. Click on 'Close'
-> error in console

Steps to reproduce the behavior in the swocase:
0. Go to Dialog Framework - Basic
1. Click on 'View'
2. Click on 'x'
3. Open the dialog again
-> error in console

**Expected behavior**
Behavior is correct (Dialog is closed), but there is a JS error:
core.js.xhtml?ln=primefaces&v=8.0:16 Widget for var 'myForm_viewCarsButton_dlgwidget' not available!

**Example XHTML**
bais.xhtml
```xml
    <h:form>
        <p:growl id="growl" showDetail="true" sticky="true" />

        <p:commandButton value="View" icon="pi pi-home" action="#{carsView.viewCars}" id="viewCarsButton">
            <p:ajax event="dialogReturn"  action="#{carsView.showMessageAfterClose}" update="@form" />
        </p:commandButton>
    </h:form>
```
viewCars.xhtml
```xml
    <p:dataTable var="car" value="#{carsView.cars}">
        <p:column headerText="Car">
            <h:outputText value="#{car}" />
        </p:column>

    </p:dataTable>

    <h:form>
        <p:commandButton value="Close" icon="pi pi-home" action="#{carsView.closeDialog}" id="closeButton">
        </p:commandButton>

    </h:form>
```
**Example Bean**
```java
import org.primefaces.PrimeFaces;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@ManagedBean
@ViewScoped
public class CarsView implements Serializable{

  private List<String> cars;

  @PostConstruct
  public void init() {
    cars = new ArrayList();
    cars.add("Volvo");
    cars.add("Mercedes");
    cars.add("Peugeot");
    cars.add("Fiat");
  }

  public List<String> getCars() {
    return cars;
  }

  public void viewCars() {
    Map<String,Object> options = new HashMap<String, Object>();
    options.put("resizable", false);
    PrimeFaces.current().dialog().openDynamic("viewCars", options, null);
  }

  public void closeDialog() {
    PrimeFaces.current().dialog().closeDynamic(null);
  }

  public void showMessageAfterClose(){
    FacesContext context = FacesContext.getCurrentInstance();
    context.addMessage(null, new FacesMessage("info",  "Dialog closed") );
  }

}
```

**Comment by melloware** [comment]
@Mich2424 do you mean this is reproducible in the showcase?

I can't reproduce on the showcase? https://www.primefaces.org/showcase/ui/df/data.xhtml

**Comment by crocimi** [comment]
It is reproducible but you have to set PROJECT_STAGE=Development, open the car's dialog, close it (with 'x') and open it again.

**Comment by melloware** [comment]
I don't think there is anything to worry about that message is only printed in DEVELOPMENT mode.
```javascript
widgetNotAvailable: function(widgetVar) {
           PrimeFaces.error("Widget for var '" + widgetVar + "' not available!");
        }
```

Are you seeing any adverse behavior because of it?  PrimeFaces tries to clean up detatched widgets on close and clearly this widget is already gone when this is called?

**Comment by crocimi** [comment]
Ok, Everythink works, as you say I was just a little bit worried... :-) Thx for your time
