### ISSUE TITLE
Ajax Queue: All queued xhrs are sent when calling abortAll

### ISSUE THREAD

**Issue by bzurmaar** [primefaces/primefaces#5943]
**Describe the defect**
When calling `PrimeFaces.ajax.Queue.abortAll()` all queued events are fired rather than discarded. 

**Environment:**
 - PF Version: _8.0_ (or any later version)
 - JSF + version: Mojarra 2.3.9.SP06 (on Wildfly 19.0)
 - Affected browsers: _Chrome, Chromium, Vivaldi (I guess all Chromium-based Browsers)_

**To Reproduce**
1. Load the given xhtml page.
2. Click a few times on "Do long running stuff".
3. Click on "Abort all"
4. Look at the console output.

**Actual behavior**
The console shows that right after cancelling several (i.e. all remaining in the queue) requests were started to be processed at once. Sample output:
```
15:14:50,558 INFO  [stdout] (default task-5) Starting to idle @ 0
15:14:52,559 INFO  [stdout] (default task-5) Idling finished @ 0
15:14:52,586 INFO  [stdout] (default task-5) Starting to idle @ 1
15:14:52,985 INFO  [stdout] (default task-2) Starting to idle @ 2
15:14:52,986 INFO  [stdout] (default task-3) Starting to idle @ 3
15:14:52,988 INFO  [stdout] (default task-1) Starting to idle @ 5
15:14:52,988 INFO  [stdout] (default task-6) Starting to idle @ 4
15:14:54,586 INFO  [stdout] (default task-5) Idling finished @ 1
15:14:54,986 INFO  [stdout] (default task-2) Idling finished @ 2
15:14:54,988 INFO  [stdout] (default task-3) Idling finished @ 3
15:14:54,988 INFO  [stdout] (default task-1) Idling finished @ 5
15:14:54,989 INFO  [stdout] (default task-6) Idling finished @ 4
```

**Expected behavior**
The console should show that the last action was finished and no further requests were processed.

**Example XHTML**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:form id="form">
  <p:commandButton id="button" value="Do long running stuff" action="#{fooController.idle()}"/>
  <input type="button" value="Abort all" onclick="PrimeFaces.ajax.Queue.abortAll();"/>
</h:form>

</html>
```

**Example Bean**
```java
package test;

import java.io.Serializable;
import java.util.concurrent.atomic.AtomicLong;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

@Named
@ApplicationScoped
public class FooController implements Serializable {

    private static final long serialVersionUID = 1L;

    private AtomicLong sequence = new AtomicLong();

    public void idle() {
    	final long number = sequence.getAndIncrement();
    	System.out.println("Starting to idle @ " + number);
        try {
            Thread.sleep(2000);
        }
        catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        System.out.println("Idling finished @ " + number);
    }
}
```
**Additional thoughts**
This behavior is especially dangerous because the idea behind the ajax queue is to serialize the requests - processing one at a time. As [abortAll() is called on every page load](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js#L1285) a simple page reload can lead to serious concurrency problems on the server side when you rely on this. This was a very hard find for me.

**Comment by melloware** [comment]
Hmm here is the source for abortAll
```javascript
/**
             * Aborts all requests that were already sent, but have not yet received an answer from the server. Also
             * removes all requests that are waiting in the queue and have not been sent yet.
             */
            abortAll: function() {
                for(var i = 0; i < this.xhrs.length; i++) {
                    this.xhrs[i].abort();
                }

                this.xhrs = new Array();
                this.requests = new Array();
            }
```

It looks like it is doing the right thing and calling `abort` and re-initializing the arrays?

**Comment by melloware** [comment]
Also here is a SO post about the Abort issue in Jquery.  Note we are using Jquery 3.4.1 in 8.0.
https://stackoverflow.com/a/446626/502366

And this answer: https://stackoverflow.com/a/446622/502366

> You can't recall the request but you can set a timeout value after which the response will be ignored. See this page for jquery AJAX options. I believe that your error callback will be called if the timeout period is exceeded. There is already a default timeout on every AJAX request.
> 
> You can also use the abort() method on the request object but, while it will cause the client to stop listening for the event, it will not stop the server from processing it.

**Comment by bzurmaar** [comment]
I also had a look at the code and share your evaluation that the code of abortAll does seemingly the right thing. I don't know where the error comes from. It has to be hidden somewhere deeper. My guess is that abort() is a good candidate to look at.

It's clear that the client cannot magically prevent the server from processing anything that's send to him. This is not what this issue is about. The problem is that the queue fires all queued requests at once when the abortAll method is called. You can see that in the sample output above. 5 requests (1-5) are started simultaneously which is quite obviously the opposite of what the queue is expected to do.

**Comment by melloware** [comment]
yeah weird it looks like we need to look at Jquery `abort` and there is all kinds of conversation here: https://github.com/jquery/jquery/issues/2084#issuecomment-308173243

it looks like they changed `abort` to a Promise.  I don't quite understand why its not working.

have you debugged the JS in your browser when `abort` gets called?

**Comment by tandraschko** [comment]
So it works fine in Firefox? :D

**Comment by bzurmaar** [comment]
@tandraschko I tested the browsers noted above and the issue was reproducible immediately. I also made a quick test on Firefox but failed to cause the same behavior. So I guess it's only the Chromium-based ones, but I don't want to jump to conclusions.

@melloware I had a second look at the code and I'm even more puzzled than before.
1. The for loop iterates over xhrs, which is per documentation supposed to hold the requests already fired. abort() is only called on these already sent requests. I don't understand how that influences the queued ones. The requests stored in requests are never touched by abortAll(). Is there a chance of these two lists being mixed up somewhere.
1. I don't even understand why you need a *list* of requests fired in a queue. There should always be exactly zero or one requests pending.

I did not do an in depth debugging session. My javascript experience is limited to say the least.

**Comment by melloware** [comment]
I think you are right it should also loop over the QUEUED list.

**Comment by melloware** [comment]
What happens if you add this script to your page...
```javascript
PrimeFaces.ajax.Queue.abortAll = function() {
    for (var i = 0; i < this.xhrs.length; i++) {
        this.xhrs[i].abort();
    }

    for (var i = 0; i < this.requests.length; i++) {
        this.requests[i].abort();
    }

    this.xhrs = new Array();
    this.requests = new Array();
};
```

**Comment by melloware** [comment]
I see the same behvior in Firefox and Chrome.  If I pause in the debugger as soon as I hit
```javascript
this.xhrs[i].abort();
```

It actually CAUSES the ajax request to fire.

**Comment by melloware** [comment]
Attached is the reproducer:
[pf-5943.zip](https://github.com/primefaces/primefaces/files/4670117/pf-5943.zip)

**Comment by bzurmaar** [comment]
This is really weird. When I insert your code it does the following: It iterates over xhrs which initially contains exactly one element. For every iteration it calls abort(). On the call of abort an element disappears from the requests array and one is added to the xhrs array. Is there any callback configured that does this? This happens until the requests array is empty. The second for loop you added of course then has no effect as the requests contains no further elements.

So it seems calling abort transfers the element from the requests array to the xhrs array.

It's still not clear to me though why you want to iterate over the requests array. These requests have never been fired in the first place so why care aborting them?

**Comment by melloware** [comment]
even stranger is why a call to abort() actually fires the request.

**Comment by melloware** [comment]
Its almost like the `abort` is triggering the `always` clause of the XHR or something which in some way is triggering it to fire.

**Comment by bzurmaar** [comment]
Removing both loops and hence not aborting anything seems to yield the correct behavior. This is of course not a satisfactory solution, but indicates we're on the right track.

**Comment by melloware** [comment]
OK I figured it out and fixed it.  Check out my PR and explanation.

if you need this fix right now
```javascript
PrimeFaces.ajax.Queue.abortAll = function() {
    this.requests = new Array();
    for (var i = 0; i < this.xhrs.length; i++) {
        this.xhrs[i].abort();
    }
    this.xhrs = new Array();
};
```

**Comment by bzurmaar** [comment]
Thank you so much for your help and the lightning fast fix!
