### ISSUE TITLE
DataTable: JS's selectRow doesn't take into account the "selection" attribute

### ISSUE THREAD

**Issue by andrewtobilko** [primefaces/primefaces#5944]
**Describe the defect**

`selectRow` doesn't take into account the "selection" attribute. If I have a single selection table, from the client-side I am able to select as many rows as I want.

**Environment:**
 - PF Version: 8.0

**To Reproduce**

1. Define a table with `widgetVar="table" selection="single"`
2. `PF('table').selectRow(1, false);` select row 1.
3. `PF('table').selectRow(2, false);` select row 2 keeping row 1 selected.

**Expected behavior**

If the selection is single, step 3 would deselect row 1 and leave row 2 to be the only selected option.

**Comment by melloware** [comment]
If you need this fix right now just add this JS:
```javascript
PrimeFaces.widget.DataTable.prototype.selectRow = function(r, silent) {
    var row = this.findRow(r);
    if (!row.hasClass('ui-datatable-selectable')) {
        return;
    }

    // #5944 in single select all other rows should be unselected
    if (this.isSingleSelection()) {
        this.unselectAllRows();
    }

    var rowMeta = this.getRowMeta(row);

    this.highlightRow(row);

    if (this.isCheckboxSelectionEnabled()) {
        if (this.cfg.nativeElements)
            row.children('td.ui-selection-column').find(':checkbox').prop('checked', true);
        else
            this.selectCheckbox(row.children('td.ui-selection-column').find('> div.ui-chkbox > div.ui-chkbox-box'));

        this.updateHeaderCheckbox();
    }

    this.addSelection(rowMeta.key);

    this.writeSelections();

    if (!silent) {
        this.fireRowSelectEvent(rowMeta.key, 'rowSelect');
    }
};
```

**Comment by andrewtobilko** [comment]
@melloware great, thank you!
