### ISSUE TITLE
SelectCheckboxMenu: Behavior when values contain a value for which no SelectItem exists 

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#5956]
**Description**

Consider a `<p:selectCheckboxMenu multiple="true"/>` which has a list of values  and some `f:selectItems` set. The behavior when the value list contains a value for which no selectItem exists (which can happen easily when the select items are from a dynamic source) is a bit strange / inconsistent:

* When the page is rendered, values for which no selectItem exists are still rendered.
* But the user cannot delete the offending values, neither by clicking on the "x" icon, nor by deselecting it in the dropdown list.
* But once the form is submitted, the value is removed.

![image](https://user-images.githubusercontent.com/2456413/82885817-8ae05300-9f3d-11ea-95c6-e7efc08d5367.png)

**Describe the solution you would like**

First we need to decide how the expected behavior should be. Would probably also be a good idea to check the behavior of other SelectXXX components.

1. I took a look at what happens with the `selectManyCheckbox` from `http://xmlns.jcp.org/jsf/html`. It simply omits any values for which no SelectItem exists. That would be consistent with the current behavior, as the value is removed upon submission anyway. Would also be a simple and small change.
1. Leave everything as it is, but fix the "x" icon so that it actually deletes the value. Still a bit inconsistent, though, as the value is deleted automatically anyway upon submission, irrespective of whether the user deleted it. 
1. Alternatively, we could also add an option for whether values with no SelectItem should be retained. That sounds more complex and also raises other questions such as what the `itemLabel` of such a value should be.

Personally, I'd prefer option 1 - other opinions?

**Comment by melloware** [comment]
OK so 2 things.
1. The value being removed upon submit is the correct behavior.
2. I think the only incorrect behavior is not being able to delete items.

**Comment by blutorange** [comment]
I agree with your 2 points. The one thing I'm not sure about is whether it's correct to display the item at all? Since no matter whether the user deletes it or not, it gets deleted upon submit.

**Comment by melloware** [comment]
Well there is this new feature I just added for `hideNoSelectOptions`: https://github.com/primefaces/primefaces/issues/5886

**Comment by blutorange** [comment]
@melloware Thanks, I saw that issue, but I'm not quite sure how it applies to this case? For example, let's say there's a bean with `list = [1,2,3]` and `availableOptions = [1,2]`

```xhtml
<p:selectCheckboxMenu value="#{bean.list}" multiple="true">
  <f:selecItems value="#{bean.availableOptions}" />
</p:selectCheckboxMenu>
```

If I understood correctly, `hideNoSelectOptions` only hides `<f:selectItem noSelectionOption="true" />`?, right? The problem with the example above is that is still shows the item `3`, even though that is not an available option.

In my use case it would be preferable to just silently remove the value `3` upon redisplay. Well, that could be done manually in the bean. It's just I wanted to make sure the component has a useful, well-defined behavior for that case first.

**Comment by melloware** [comment]
Yes sorry when I read your original post i assumed you were talking about noSelectItem="true" you are talking about items that are NOT in the selectItems at all.

**Comment by blutorange** [comment]
No need to apologize - I could have explained it better : )

So I guess the remaining question is whether values that correspond to no SelectItem should be shown initially or whether this should be configurable via an additional option. Personally I'd prefer just not showing them, the `<h:selectManyCheckbox />` just omits these values as well.

**Comment by melloware** [comment]
agreed they should be omitted if they are not valid.
