### ISSUE TITLE
<p:tree> nodeSelect event is not working

### ISSUE THREAD

**Issue by shubforall** [primefaces/primefaces#596]
I am having <p:tree> component inside the composite component.
The select event is not working and there are no error logs.

The same is working fine if <p:tree> component is moved out of the composite component.

Forum link : http://forum.primefaces.org/viewtopic.php?f=3&t=42908

Environment - PrimeFaces version - 5.2, Websphere liberty profile.

**Comment by tandraschko** [comment]
No Example -> Invalid
Also works fine in the showcase: http://primefaces.org/showcase/ui/data/tree/events.xhtml
