### ISSUE TITLE
TabView: Layout of nested tabViews broken if updated from outer tabView

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#5960]
**Describe the defect**
Layout of nested tabViews broken if updated from outer tabView

**Reproducer**
https://github.com/erickdeoliveiraleal/primefaces-test/

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.16
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. click button

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>
	<h:form prependId="false">

		<p:tabView id="tabView">

			<p:tab id="tabPrincipal" title="Principal">

				<p:commandButton update="tabPerm"></p:commandButton>

			</p:tab>

			<p:tab title="Permissões" id="tabPerm">

				<p:tabView>
					<p:tab title="Geral">

					</p:tab>
				</p:tabView>

			</p:tab>

		</p:tabView>

	</h:form>

</h:body>
</html>




```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

}
```

**Comment by melloware** [comment]
Is this issue related to this one at all? https://github.com/primefaces/primefaces/issues/5933

**Comment by tandraschko** [comment]
A tab is not updatable, thats by design and discussed multiple times in the past. 
You have to update the tabView, as the TabView renders the tab.

**Comment by tandraschko** [comment]
updated the docs now
