### ISSUE TITLE
TypeScript: DataTable: Property 'value' does not exist on EventTarget (ts2339)

### ISSUE THREAD

**Issue by HerrB92** [primefaces/primefaces#5963]
If the example code is written as TS in Visual Studio Code, then it is currently not possible to compile it.

In the following line e is considered only a generic EventTarget of an HTMLElement, not having a value, and not - as far as I understand - as EventTarget of an HTMLInputElement:

```
const inputTextEditor = (props: any, field: string) => {
        return <InputText type="text" value={props.rowData[field]} onChange={(e) => onEditorValueChange(props, e.target.value)} />;
    };

```
The same error is shown in the sandbox (but there it compiles):
https://codesandbox.io/s/3vpem?file=/src/demo/DataTableEditDemo.tsx

My solution (at least it compiles, I am a beginner):
```
const inputTextEditor = (props: any, field: string) => {
        return <InputText type="text" value={props.rowData[field]} onChange={(e: React.ChangeEvent<HTMLInputElement>) => onEditorValueChange(props, e.target.value)} />;
    };
```

Regards,
HerrB92

**Comment by melloware** [comment]
I think you want PrimeReact issue not PrimeFaces Issues.  Go here: https://github.com/primefaces/primereact/issues
