### ISSUE TITLE
DataTable: CellSelect event

### ISSUE THREAD

**Issue by mfrenaij** [primefaces/primefaces#5965]
**Description**
I would like to select a cell in p:dataTable to show its content. My p:dataTable contains cells with large descriptions which I could like to show in e.g. a p:overlay. Using p:dataTable only rows can be selected, but this is not what I want: I would like to select a single cell.

**Describe the solution you would like**
Please implement a cellSelect ajax (FacesEvent) to the p:dataTable that is based on cellEdit event already used in p:cellEditor/p:dataTable.

**Additional context**
With p:cellEditor I can select a cell in p:dataTable. It triggers a cellEdit ajax event only when modifying the cell. Why not providing a cellSelect ajax event which could be used to select a cell without modifying it?

**Example XHTML**
This example is based on the code from https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml
```xml
<h:form id="frmTest">
    <p:dataTable id="cars2" var="car" value="#{dtEditView.cars2}" editable="false" widgetVar="cellCars">

        <p:ajax event="cellSelect" listener="#{dtEditView.onCellSelect}" update=":form:msgs" />
 
        <p:column headerText="Id">
               <p:cellEditor>  <!--maybe a new component p:cellSelector would be a better idea for this purpose  -->
                   <f:facet name="output"><h:outputText value="#{car.id}" /></f:facet>
                   <f:facet name="input"><p:inputText id="modelInput" value="#{car.id}" style="width:96%"/></f:facet>
               </p:cellEditor>
           </p:column>
     </p:dataTabe>
</h:form>
```

**Example Bean**
```java
@ManagedBean(name = "dtEditView")   // old way of annotation
@ViewScoped
public class EditView implements Serializable {
    public void onCellSelect(CellSelectEvent event) {
        Object cellContent = event.getValue();

        FacesContext context = FacesContext.getCurrentInstance();

        if (cellContent != null) {
            FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Cell content", cellContent.toString());
            FacesContext.getCurrentInstance().addMessage(null, msg);
        }
    }
}
```

**Comment by melloware** [comment]
Why not use PFE Sheet?  It has a "cellSelect" AJAX event exactly like you are looking for: https://www.primefaces.org/showcase-ext/sections/sheet/ajaxEvents.jsf

"Sheet provides ajax events for cellSelect, change, sort, filter, columnSelect, rowSelect."

**Comment by melloware** [comment]
This ticket will most likely not be done by the community and would probably have to be sponsored through PRO account or "one time quote" to PrimeTek.

**Comment by mfrenaij** [comment]
Thank you for the quick response!
We indeed have investigated the use of PFE Sheet, Unfortunately PFE Sheet is 'lightweight' and we are using some features that do not seem to be supported by PFE Sheet like exporting rows or pagination. Furthermore its layout does not nicely fit Ultima template (we have some issues with that), there is no column toggler (although PFE Sheet has an alternative way for hiding columns), and we would like to modify the bar representing the number of records. Concluding: although PFE Sheet has many nice features, it is currently not an option for us. But we will consider the PRO account or the 'one time quote'.

**Comment by melloware** [comment]
@mfrenaij you can accomplish this now with p:overlayPanel and a simple trigger on the cell contents.  A new custom cell select is not necessary for what you are trying to accomplish.

**Comment by philpil** [comment]
Can we take another look at this, even if we do the approach of selectionMode singleCell and multipleCells ? 

Would be useful also if we could pass through a row selected with the selected cell also ?

**Comment by melloware** [comment]
@philpil i just added it here to the Sponsoring Required list: https://github.com/primefaces/primefaces/issues/11251
