### ISSUE TITLE
Tooltip: Global with a static message

### ISSUE THREAD

**Issue by wafa-ogh** [primefaces/primefaces#5971]
**Description**
when the tooltip is global, the value attribute is ignored in client-side 

It is true global tooltip is supposed to be global and show the title/data-tooltip attribute value of its target elements.
A static message may be needed for a specific group of elements, especially for components that do not provide title attribute and ignores passthrough attributes like columns/column/row components.
so creating a global tooltip with a selector "td.class1,tr.class2" won't be helpful. 

there may be ways around this, but a static value may be helpful to be rendered initially in a global tooltip.

**Comment by melloware** [comment]
I am confused by what you are asking?   Are you saying if it finds components that don't have a `title` already to apply the `value` as a default?  

To me that does not feel like a good idea as the whole point of tooltip is to replace existing titles, not create new ones where they are missing.  Maybe someone else has a different opinion.

**Comment by wafa-ogh** [comment]
I'm asking if it is possible to render value attribute of tooltip even if it is global, actually, it is getting ignored

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.   I need to see what you are talking about with a runnable project.

**Comment by melloware** [comment]
@wafa-ogh unless you provide the request above i will close this ticket

**Comment by wafa-ogh** [comment]
@melloware sure, I will
