### ISSUE TITLE
DragDrop - Draggable doesn't extend the box

### ISSUE THREAD

**Issue by tgotwig** [primefaces/primefaces#5977]
I think the DragDrop documentation needs a little bit of rework, so for me it would be nice if the box could be extended after an element was dropped and the dropped element realigned etc. 🤔

![image](https://user-images.githubusercontent.com/30773779/83498850-bd013000-a4bc-11ea-9207-776c0bd8572c.png)

**Comment by tandraschko** [comment]
sounds more like a forum topic ;)

**Comment by tandraschko** [comment]
The issuetracker is for concrete issues or feature requests
your issue sounds like "would be great if something magical could happen to resize it somehow anyway"

in this case we use a simple panel/div, which can be resized after ondrop in your own application.
probably just a showcase topic.
