### ISSUE TITLE
FileDownload: should not require ajax="false"

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5978]
**Description**
FileDownload currently requires to set ajax to false for the commandButton or commandLink.
1. This is something you need to know. Or read in the documentation.
2. This causes issues when you use multiple forms within one XHTML. (Essentially you loose all input to other forms.)

Maybe there are way´s to solve this which had not been present 10 year ago, when PrimeFaces was built. IMO single page applications (Angular, React, Vue, ...) must have a way to do this without sending an attachment via Content-Disposition-header.

Found eg http://danml.com/download.html and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download

It may require some research how to combine this with the already exisiting code for FileDownload. Or how to integration this into the JSF/PrimeFaces-infrastructure.

**Describe the solution you would like**
FileDownload should work with ajax="true".

**Additional context**
see https://www.primefaces.org/showcase/ui/file/download.xhtml

**Comment by melloware** [comment]
This also fixes the Safari issue found here: https://github.com/primefaces/primefaces/issues/6327
