### ISSUE TITLE
General: Bean Validations 2.0

### ISSUE THREAD

**Issue by GedMarc** [primefaces/primefaces#5993]
**Description**
I would like to be able to use bean validations 2.x while maintaining the current package hierarchy.

**Describe the solution you would like**
Please use Jakarta validations API < version 3 (jakarta.x namespace)

**Additional context**
There are methods that validations 1.x does not have. The overrides methods for these have been removed

**Comment by melloware** [comment]
We support most of the 2.X validations now.  Are you finding a particular one that is not supported?

**Comment by GedMarc** [comment]
Should be simple enough for me to replicate on a example - 

It's when calling the method on the validations 2.0.2 - when it goes through EL it fire the deescripter and fails with the missing method

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project primefaces: Compilation failure
[ERROR] /C:/Java/projects/primefaces/src/main/java/org/primefaces/validate/bean/ConstraintDescriptorWrapper.java:[37,8] org.primefaces.validate.bean.ConstraintDescriptorWrapper is not abstract and does not override abs
tract method <U>unwrap(java.lang.Class<U>) in javax.validation.metadata.ConstraintDescriptor
[ERROR]
```

**Comment by melloware** [comment]
Interesting I use Jboss/Wildfly with BV2.0 and have not had any issues.

**Comment by GedMarc** [comment]
Looks like added in 2.0.2 :)

https://docs.jboss.org/hibernate/beanvalidation/spec/2.0/api/?javax/validation/metadata/ConstraintDescriptor.html
