### ISSUE TITLE
General: JDK9 module referencing

### ISSUE THREAD

**Issue by GedMarc** [primefaces/primefaces#5995]
**Description**
Please include a module-info for primefaces in order to build Java Native Images and to use it JMod, JImage and JPackage

**Describe the solution you would like**
I would like to use moditect as a proven method of forcing module-info definitions

**Additional context**
The file will be placed inside the versions folder for multi-release jars.
Multi-Release jars need to flag set inside of the manifest in order to be jmods or jimages.

**Comment by melloware** [comment]
@GedMarc going to close this for now.  We can reopen if you decide to update your PR!

**Comment by GedMarc** [comment]
100% just seeing if i can sort out a few of the upload/cropper things

**Comment by GedMarc** [comment]
may have to wait for jakarta 9
