### ISSUE TITLE
Layout : Please update to 1.8.1

### ISSUE THREAD

**Issue by GedMarc** [primefaces/primefaces#5999]
**Description**
Please update the layout library to 1.0.8.0

**Describe the solution you would like**
Please update the library to 1.0.8.0 for Layout, to implement and include the bind/unbind, $.type, $.css, $.click and others to version 9

**Comment by melloware** [comment]
@GedMarc Why is this release now 1MB the old one was 344KB?

**Comment by GedMarc** [comment]
bleeding hell :)

**Comment by melloware** [comment]
OK I grabbed your 1.8.1 and submitted a PR.
