### ISSUE TITLE
Escape option to p:confirm

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#60]
When we set the message attribute we don't have a option to indicate if this text should be escaped or not.

Without this option we can't use a global confirmDialog because to resolve this is necessary use <f:facet name="message"> with <h:outputText value="..." escape="false">.

I believe an attribute like "escapeMessage" will be useful in p:confirm.

**Comment by carpet-stain** [comment]
Ahh, this feature would be greatly appreciated. Took me a little while to find a workaround.

**Comment by mbeedub** [comment]
Would be an incredibly useful enhancement.

**Comment by maol74** [comment]
What is the status on this, this is a most needed feature?

**Comment by tandraschko** [comment]
@melloware your fix add this attribute to p:confirmDialog but the issue here is about p:confirm.

**Comment by melloware** [comment]
hmmm I was using the showcase example...

https://www.primefaces.org/showcase/ui/overlay/confirmDialog.xhtml

But it looks like the Dialog is what renders the message so the escapeMessage I thought should go on the dialog and not on the p:confirm?  I can look at this some more to see how the p:confirm actually links to the confirmDialog.

**Comment by tandraschko** [comment]
Yep, just check it.
ConfirmDialog doesn't need a escapeMessage attribute as the facet can be used. On p:confirm, a facet can NOT be used.

**Comment by melloware** [comment]
Ahhh I see it now it actually renders a Script to the UI.  let me cancel this PR and fix it a different way

**Comment by melloware** [comment]
See this post: https://forum.primefaces.org/viewtopic.php?f=3&t=53195&p=161912

**Comment by jjcampos** [comment]
Hi @melloware as you asked at that thread I created a pull request for this here: https://github.com/primefaces/primefaces/pull/3181

**Comment by jjcampos** [comment]
Sorry for the confusion, previous closed pull request I forgot the change on standard-facelets-taglib.xml. Fixed it now.
