### ISSUE TITLE
dock: scrollbar not shown

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#6010]
**Environment:**
 - PF Version: _8.0_
 - JSF + version: _Mojarra 2.2.8_
 - Affected browsers: _ALL_

**To Reproduce**
1. Edit `dock.xhtml` in `showcase-facelift`, put `<p style="height:900px">test</p>` into `<ui:define name="implementation">`.
2. Start `showcase-facelift` and navigate to http://localhost:8080/showcase/ui/menu/dock.xhtml
3. The scrollbar is missing.

**Expected behavior**
The scrollbar should not disappear. This worked with PrimeFaces 7.

**Example XHTML**
```html
    <ui:define name="implementation">
        <p style="height:900px;">
            test
        </p>
        <p:dock position="bottom">
            <p:menuitem value="Home" icon="/resources/demo/images/dock/home.png" url="#"/>
            <p:menuitem value="Music" icon="/resources/demo/images/dock/music.png" url="#"/>
            <p:menuitem value="Video" icon="/resources/demo/images/dock/video.png" url="#"/>
            <p:menuitem value="Email" icon="/resources/demo/images/dock/email.png" url="#"/>
            <p:menuitem value="Portfolio" icon="/resources/demo/images/dock/portfolio.png" url="#"/>
            <p:menuitem value="Link" icon="/resources/demo/images/dock/link.png" url="#"/>
            <p:menuitem value="RSS" icon="/resources/demo/images/dock/rss.png" url="#"/>
            <p:menuitem value="History" icon="/resources/demo/images/dock/history.png" url="#"/>
        </p:dock>
    </ui:define>
```

![image](https://user-images.githubusercontent.com/13161711/84010828-7fe1e580-a975-11ea-9ef5-d863fa06be8d.png)

**Comment by cnsgithub** [comment]
**Solution**
`<p:dock blockScroll="false">`

**Comment by tandraschko** [comment]
hmm
@melloware why should dock block scroll?
it should just always be on the bottom?

**Comment by melloware** [comment]
Hey guys I added blockScroll as an option and defaulted to TRUE because of this ticket: https://github.com/primefaces/primefaces/issues/3153

I an flip it to be false but my thought was most people using Dock are using it in a SPA like fashion.  If you two both think I should flip it to make the default FALSE I can do that no problem since this rewrite is new for 9.0

**Comment by tandraschko** [comment]
i would really flip it.
Nobody expects that dock removes the scrollbar
