### ISSUE TITLE
Timeline: OnDrop Group is null or empty

### ISSUE THREAD

**Issue by kneringerjohann** [primefaces/primefaces#6014]
**Describe the defect**
If you drag&drop an element to a grouped timeline, the group element from TimelineDragDropEvent is alway null or empty

**Reproducer**
To reproduce clone repository in branch "timelinedropissue" in here https://github.com/kneringerjohann/primefaces-test/tree/timelinedropissue.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: mojarra 2.3 (org.glassfish jakarta.faces 2.3.14)
 - Affected browsers: ALL_

**To Reproduce**
1. Checkout project in branch "timelinedropissue"
2. Go to http://localhost:8080/primefaces-test/
3. Drag & Drop 1 Element from "Drag and drop events" to a specificy group on the timline (Truck 10-15).
4. Growl Message with Info that group is not set will occur.

**Expected behavior**
A group is set in the TimelineDragDropEvent, because without the group it cannot be placed in the timeline.

**Comment by melloware** [comment]
OK I see the issue.  But if there is no group what "group" do you think it should create?    Couldn't you receive the event, create the group in your TimeLineModel and then update the Timeline?

**Comment by kneringerjohann** [comment]
> OK I see the issue. But if there is no group what "group" do you think it should create? Couldn't you receive the event, create the group in your TimeLineModel and then update the Timeline?

In my case there are 5 Groups already created in the TimeLineModel before. 
I want to drop the Item to a specific group, which is not possible in this case, as no group is delivered.

**Comment by melloware** [comment]
OK so its getting right group id "2" that I dropped it onto but the group's content is NULL.

![image](https://user-images.githubusercontent.com/4399574/84144053-9ba4c480-aa25-11ea-8d69-56968bd36af1.png)

So on the Java side when it gets it and does `params.get(clientId + "_group")` that value is NULL.

**Comment by kneringerjohann** [comment]
> OK so its getting right group id "2" that I dropped it onto but the group's content is NULL.
> 
> ![image](https://user-images.githubusercontent.com/4399574/84144053-9ba4c480-aa25-11ea-8d69-56968bd36af1.png)
> 
> So on the Java side when it gets it and does `params.get(clientId + "_group")` that value is NULL.

What we also saw is that the content for the group header in the ajax request is not set/empty:

![timeline_group](https://user-images.githubusercontent.com/9606575/84145048-8184d980-aa59-11ea-92b4-eea007682c1c.png)

**Comment by melloware** [comment]
Yep that is this JavaScript:
```javascript
if (group) {
                    params.push({
                        name: this.id + '_group',
                        value: group.content
                    });
                }
```

The `group.content` is NULL.   What should the value be?  Its just a String  in the TimeLineEvent but what is that String supposed to be?

**Comment by melloware** [comment]
I wonder if this should pass `groupId: "id3"` instead of content?  Would the id of the group be more valuable?

**Comment by kneringerjohann** [comment]
> Yep that is this JavaScript:
> 
> ```js
> if (group) {
>                     params.push({
>                         name: this.id + '_group',
>                         value: group.content
>                     });
>                 }
> ```
> 
> The `group.content` is NULL. What should the value be? Its just a String in the TimeLineEvent but what is that String supposed to be?

Its passing the Id of the Group as a String...In Java you can also set an Generic-Type for the Group, but in the TimelineDragDropEvent-Object you find only a String with the ID (in Primefaces 7).

**Comment by melloware** [comment]
OK can you try this test:
[pf-6014.zip](https://github.com/primefaces/primefaces/files/4752110/pf-6014.zip)

**Comment by kneringerjohann** [comment]
> OK can you try this test:
> [pf-6014.zip](https://github.com/primefaces/primefaces/files/4752110/pf-6014.zip)

on JS side after drag&drop I get this error in the console:

test.js.xhtml:114 Uncaught TypeError: PrimeFaces.toISOString is not a function
    at c.<anonymous> (test.js.xhtml:114)
    at HTMLDivElement.i (jquery.js.xhtml?ln=primefaces&v=8.0:2)
    at K.<computed>.<computed>._trigger (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at K.<computed>.<computed>._drop (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:133)
    at K.<computed>.<computed>._drop (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at K.<computed>.<computed>.<anonymous> (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:133)
    at Function.each (jquery.js.xhtml?ln=primefaces&v=8.0:2)
    at Object.drop (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:133)
    at K.<computed>.<computed>._mouseStop (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:124)
    at K.<computed>.<computed>._mouseStop (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)

Also, I do not get a growl notification with the group...Do you get a growl notification with the group name/id?

**Comment by melloware** [comment]
Ahh sorry i made that from 9.0-SNAPSHOT.  Hold on let me fix it.

**Comment by melloware** [comment]
try this one:
[pf-6014.zip](https://github.com/primefaces/primefaces/files/4752192/pf-6014.zip)

**Comment by kneringerjohann** [comment]
> try this one:
> [pf-6014.zip](https://github.com/primefaces/primefaces/files/4752192/pf-6014.zip)

just had the same experience

**Comment by melloware** [comment]
Press CTRL+F5 in your browser to reload JS.  Its working fine for me that last version.

**Comment by kneringerjohann** [comment]
> Press CTRL+F5 in your browser to reload JS. Its working fine for me that last version.

I'm sorry...working right! thx for your time!
