### ISSUE TITLE
progressBar: missing jquery-plugins

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#6017]
The following:
```
<p:progressBar widgetVar="progressBar"/>
<script type="text/javascript">
    $(function () {
        PF('progressBar').setValue(50);
    });
</script>
```
results in a Javascript error. Adding:
```
<h:outputScript library="primefaces" name="jquery/jquery-plugins.js" />
```
fixes the issue. I guess `org.primefaces.component.progressbar.ProgressBar` is missing:
```
@ResourceDependency(library = "primefaces", name = "jquery/jquery-plugins.js")
```

PrimeFaces version: 7.0.14

**Comment by melloware** [comment]
I have verified this and you are correct.
[pf-6017.zip](https://github.com/primefaces/primefaces/files/4752468/pf-6017.zip)
