### ISSUE TITLE
Provide native ClientWindow implementation

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6030]
In the past MyFaces Orchestra/CODI/DeltaSpike had a Window/TabScope. This was later promoted to JSF 2.2.
So JSF itself provides a good abstraction and API but the default implementation is very basic and has some limitations.

The DeltaSpike LAZY (*1) implementation is, compared to CLIENTWINDOW (*2), very easy to implement and only has a small downside:
When you have a active tab with e.g. windowId=1, and open a link in this tab with e.g. windowId=2, we need to refresh the current link to windowId=1 again.

Whats the difference to the default url mode in the JSF impl?
The windowId will be remembered in the sessionStorage/window.name and therefore we can validate it.
Also a initial redirect is performanced to add the windowId always to the url. Also ExternalContext#redirect is overwritten to add the windowId.

1) https://deltaspike.apache.org/documentation/jsf.html#LAZY
2) https://deltaspike.apache.org/documentation/jsf.html#CLIENTWINDOW

**Comment by tandraschko** [comment]
As PrimeFaces MultiViewState now also can use ClientWIndow to store it, it's a good time to add something.
It might actually not a perfect idea to add it to PrimeFaces as one can easily add DeltaSpike. But the overhead of adding it to PrimeFaces might be like 2-5kb. For DeltaSpike you need core-api/impl and jsf-module-api/impl which is more than 500kb and is also only usable for CDI users.

In the future it would also be great that the mode in the JSF could be enhanced.

Also we need a ClientWindowScoped: https://github.com/eclipse-ee4j/faces-api/issues/1509

**Comment by tandraschko** [comment]
Here we go....
Add:

`    <factory>
        <lifecycle-factory>org.primefaces.clientwindow.PrimeClientWindowLifecycleFactory</lifecycle-factory>
    </factory>`

and it should work ;) please test test test

would be great if someone could also retest https://issues.apache.org/jira/browse/DELTASPIKE-729 and write a docu for it

**Comment by tandraschko** [comment]
It would also need some JS docs... @blutorange  interessted? :)

**Comment by tandraschko** [comment]
The mode is almost equals to DeltaSpike LAZY mode: https://deltaspike.apache.org/documentation/jsf.html#Multi-WindowHandling

it just uses the sessionStorage instead window.name

Would be great if someone could port the "Background" and "LAZY" mode to the documentation

it also only works on JSF 2.2 as it uses the JSF API for it

DeltaSpike also worded for 2.0 AFAIR

**Comment by blutorange** [comment]
@tandraschko Sure, I can take a look later this day. It's about the JSDocs in `core.clientwindow.js`, right?

**Comment by melloware** [comment]
Awesome work @tandraschko I don't mind volunteering to do the documentation.
@blutorange can hopefully review the JS Docs
@christophs78 will hopefully help test!

**Comment by christophs78** [comment]
Yes, i will test. Not immediately but within a few days.
@tandraschko : Thanks for your work!

**Comment by christophs78** [comment]
First run with PF-Showcase on Tomcat 9.x with Mojarra results in
```
22-Jun-2020 17:14:43.557 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.StandardHostValve.custom Exception Processing ErrorPage[exceptionType=java.lang.Throwable, location=/error.xhtml]
	java.lang.NullPointerException
		at com.sun.faces.context.ExternalContextImpl.encodeRedirectURL(ExternalContextImpl.java:1103)
		at javax.faces.context.ExternalContextWrapper.encodeRedirectURL(ExternalContextWrapper.java:997)
		at org.primefaces.clientwindow.PrimeClientWindow.constructInitialRedirectUrl(PrimeClientWindow.java:121)
		at org.primefaces.clientwindow.PrimeClientWindow.decode(PrimeClientWindow.java:80)
		at org.primefaces.clientwindow.PrimeClientWindowLifecycle.attachWindow(PrimeClientWindowLifecycle.java:51)
		at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:706)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)

```

**Comment by christophs78** [comment]
![image](https://user-images.githubusercontent.com/10461942/85305144-f66dff80-b4ac-11ea-839d-17147c2afb9a.png)
![image](https://user-images.githubusercontent.com/10461942/85305226-100f4700-b4ad-11ea-9136-1759be61eda6.png)

**Comment by tandraschko** [comment]
explains why it was implemented that complicated in DS...

**Comment by tandraschko** [comment]
fixed Mojarra now ;)

**Comment by christophs78** [comment]
![grafik](https://user-images.githubusercontent.com/10461942/85319612-10fea380-b4c2-11ea-8373-3d25a025ea05.png)
Broken jfwid when in click on an ShowCase-menu-entry.

**Comment by tandraschko** [comment]
@christophs78 only happens in mojarra

**Comment by tandraschko** [comment]
The specs says that the ClientWindowId is always appended to the url and getQueryURLParameters is just something additional.

That means we have 2 bugs:
1) Mojarra doesnt handle the additional getQueryURLParameters correctly (thats the behavior you currently see in your screenshot, the second param needs a & before)
2) MyFaces doesn't append the ClientWindowId per default, it just uses getQueryURLParameters

**Comment by tandraschko** [comment]
@christophs78 please test again

**Comment by tandraschko** [comment]
See: https://issues.apache.org/jira/browse/MYFACES-4345

**Comment by tandraschko** [comment]
fixed for the upcoming MyFaces versions. So our PF ClientWIndow doesnt work on older MyFaces versions

**Comment by melloware** [comment]
@tandraschko I think that is OK better to fix it the right way for the future since this is a new feature than to try and make it backwards compatible

**Comment by tandraschko** [comment]
yeah
in general it would be great if someone could fix the mojarra bug also...
see https://github.com/eclipse-ee4j/mojarra/blob/2d22f78f81548c10f2c48a8fd8a04caa1628c0b3/impl/src/main/java/com/sun/faces/context/UrlBuilder.java#L242

I think this needs to be replaced by "&", so the screenshot of @christophs78 would contain:
?jfwid=39494&jfwid=39494

**Comment by tandraschko** [comment]
would be great if someone could create a issue and PR there

**Comment by melloware** [comment]
I will take care of that.

**Comment by melloware** [comment]
Mojarra Issue: https://github.com/eclipse-ee4j/mojarra/issues/4727

Mojarra PR: https://github.com/eclipse-ee4j/mojarra/pull/4728

**Comment by christophs78** [comment]
Looks good. :-)

I´ll work later this week on the Showcase-PR to do
![image](https://user-images.githubusercontent.com/10461942/85411497-bcfaca00-b568-11ea-8f2d-0de55a355883.png)
for the whole project.

**Comment by tandraschko** [comment]
will close it for now. Please test ;)

**Comment by tandraschko** [comment]
@melloware @christophs78 did a small refactoring, please review (and/or test :D)

**Comment by melloware** [comment]
I like it. Looks good.

**Comment by christophs78** [comment]
Looks good. Maybe i can add some integration-test for this.
