### ISSUE TITLE
Storage: Switch from cookies to HTML5 local storage

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6053]
**Description**
Based on a conversation with @GedMarc cookies were used for storing client side state because legacy browers like IE7 could only support cookies.  

**Describe the solution you would like**
Now that PF supports IE11 and higher we should switch client cookie usage for HTML5 LocalStorage which has the same lifespan as a cookie does but allows for more than 4KB of values and is the proper way to handle this type of behavior today.

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by tandraschko** [comment]
isn't session storage only for the current tab?

**Comment by melloware** [comment]
You are right should we use localStorage instead?

> Opening a page in a new tab or window creates a new session with the value of the top-level browsing context, which differs from how session cookies work.

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by tandraschko** [comment]
yeah
