### ISSUE TITLE
p:resize is broken with toggleable="true"

### ISSUE THREAD

**Issue by scipio11** [primefaces/primefaces#606]
I have p:panel toggleable="true" and panel is made resizable by p:resizable.
Then size of pane was changed and toggle button was clicked, the content of panel disapears, but the pannel remains untoggle

 <p:panel id="pnl" header="Poisitions"  toggleable="true" widgetVar="pnl" >  
                            <h:form prependId="false" >  
                                <p:dataTable scrollable="true" id="positions" value="#{Table.positions}" 
                                                             var="repeater" scrollHeight="150"
                                                       >
                                       <p:column   style="text-align:right" width="80" headerText="Name">  
                                           <h:outputText value="#{repeater.name}" />
                                       /p:column
                                       <p:column   style="text-align:right" width="80" headerText="position">  
                                           <h:outputText value="#{repeater.difference}" >
                                                <f:convertNumber type="number" 
                                                                 groupingUsed="true" locale="en" />
                                            /h:outputText  
                                       /p:column  
                                 /p:dataTable 
                            /h:form
                        /p:panel
                        <p:resizable for="pnl"  aspectRatio="true"/>

Primefaces 5.2 Mojarra 2.2.7 Glassfish 4.1

**Comment by cagataycivici** [comment]
Your formatted code is corrupted.
