### ISSUE TITLE
DatePicker\Calendar: Validate minDate is before maxDate

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6068]
**Describe the defect**
When you invoke the datepicker with the attributes maxdate and mindate while maxdate < mindate holds true, then the datepicker looks corrupted. The month/year is not shown correct.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.8 or MyFaces 2.3.6_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
When you invoke the datepicker with the attributes maxdate and mindate wihle maxdate < mindate holds true, then the datepicker looks corrupted. the month/year is not shown correct.

**Expected behavior**
Actually in such a case, when maxdate < mindate  holds true, a warning should be shown that maxdate should not be before mindate. Or you even do not show the datepicker at all since you cannot use anyhow.

**Comment by tandraschko** [comment]
i would throw a FacesException. WDYT @melloware?

**Comment by melloware** [comment]
Yep I agree and will throw a FacesException as this is invalid configuration. I am on it.

**Comment by melloware** [comment]
The PR fixes it for both DatePicker and Calendar since they share a common inheritance hierarchy.
