### ISSUE TITLE
Diagram : elements displayed using "toString()" if facet contains conditional (rendered) blocks

### ISSUE THREAD

**Issue by mikioma** [primefaces/primefaces#6079]
**Describe the defect**
Say you want to customize how each element is displayed in the diagram by using "<p:outputPanel rendered=..." with the appropriate condition for each element.

If the facet only contains blocks like that with no unconditional block, then the facet displays element using "toString()" instead of the panel contents (even though the condition to render them is true)

**Reproducer**
I've attached primefaces-test from your repository, including a simple test bean and facelet showing this issue
[primefaces-test.tar.gz](https://github.com/primefaces/primefaces/files/4829508/primefaces-test.tar.gz)

**Environment:**
 - PF Version: _8.0_
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: ALL

**To Reproduce**
1. Load "testView.jsf" in the attached sample
2. Elements' "toString()" is used for display, see:
![diagram_wrong](https://user-images.githubusercontent.com/3715539/85670926-a916ab80-b6c1-11ea-853d-481421b9f4c5.png)

3. Place whatever contents inside the facet but outside the panel, even a simple empty "span" will suffice
4. Reload the page
5. The diagram displays just ok, see:
![diagram_ok](https://user-images.githubusercontent.com/3715539/85670925-a87e1500-b6c1-11ea-9c4a-1ce77c08e71d.png)

**Expected behavior**
"rendered" conditions should be evaluated even if there is no contents outside any "rendered" conditioned block

**Example XHTML**
This makes the facet to be displayed wrong
```html
    <h:body>
        <p:diagram value="#{testView.model}" var="elem" style="height: 100vh">
            <f:facet name="element">
                <p:outputPanel rendered="#{not empty elem.name}">
                    <h:outputText value="#{elem.name}" />
                </p:outputPanel>
            </f:facet>
        </p:diagram>
    </h:body>
```

But this, makes it work. Note that I have only added an empty "span" outside any "rendered" block
```html
    <h:body>
        <p:diagram value="#{testView.model}" var="elem" style="height: 100vh">
            <f:facet name="element">
                <span />
                <p:outputPanel rendered="#{not empty elem.name}">
                    <h:outputText value="#{elem.name}" />
                </p:outputPanel>
            </f:facet>
        </p:diagram>
    </h:body>
```

All elements in the model have a non-empty name attribute
**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

    private DefaultDiagramModel model;

    @PostConstruct
    public void init() {
        model = new DefaultDiagramModel();
        Element elementA = new Element(new ElementData("A"), "20em", "6em");
        Element elementB = new Element(new ElementData("B"), "10em", "18em");
        Element elementC = new Element(new ElementData("C"), "40em", "18em");
        model.addElement(elementA);
        model.addElement(elementB);
        model.addElement(elementC);
    }

    public DiagramModel getModel() {
        return model;
    }

    public static class ElementData {
        private final String name;
        public ElementData(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public String toString() {
            return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " +
                    "Curabitur efficitur ante mauris, vel ultricies neque lacinia et. " +
                    "Nullam urna erat, ullamcorper a nulla nec, auctor consequat erat. In sed mollis mi. " +
                    "Cras tristique ac orci sed luctus. Ut eu gravida lectus. Aenean dignissim, turpis convallis facilisis vestibulum, " +
                    "odio sapien tincidunt tortor, et lobortis erat quam sed felis. " +
                    "Praesent scelerisque nibh eget tempor egestas. In vitae arcu lectus. Nulla facilisi. " +
                    "Vestibulum quis cursus lorem, et mattis nisl. Ut posuere elit eget libero imperdiet consectetur. " +
                    "Nullam eu ornare tellus. Donec bibendum sapien maximus leo suscipit, sed varius sem malesuada. " +
                    "Maecenas vehicula ac ipsum non efficitur. Donec vitae fringilla quam, in congue neque. " +
                    "Pellentesque vel sem a lacus sagittis accumsan.";
        }
    }
}
```

**Comment by mikioma** [comment]
If it may help: A couple of friends have been digging into "DiagramRendered" class and believe the problem might be in here:
```java
    protected void encodeMarkup(FacesContext context, Diagram diagram) throws IOException {
        ResponseWriter writer = context.getResponseWriter();
        DiagramModel model = (DiagramModel) diagram.getValue();
        // ...
            List<Element> elements = model.getElements();
                for (int i = 0; i < elements.size(); i++) {
                    // ...
                    if (var != null && ComponentUtils.shouldRenderFacet(elementFacet)) {
                        requestMap.put(var, data);
                        elementFacet.encodeAll(context);
                    }
                    else if (data != null) {
                        writer.writeText(data, null);
                    }
```

"ComponentUtils.shouldRenderFacet(elementFacet)" is evaluated before the actual element data is made available to the "elementFacet"

Hope this helps

**Comment by melloware** [comment]
Please review my PR.  The issue was if Facet was not rendered it automatically fell into the `else` clause.  The else clause should only fall through if you are NOT using an element facet.

**Comment by stolp** [comment]
This is one of the best documented issues I have seen here in a long while. Just wanted to point that out.

**Comment by melloware** [comment]
@stolp Agreed. This makes it so much easier on devs to see the problem and debug it.

**Comment by german1410** [comment]
@melloware I don't think the fix covers the issue. The problem is when the  elements on the facet are rendered depending on the information of the current element. That only applies when 'var' attribute is set. What about putting the element data on the request map before the call to "ComponentUtils.shouldRenderFacet(elementFacet)", with that change, elements inside the facet will have the element data available in order to determine whether or not to render it.

**Comment by melloware** [comment]
I see so I didn't realize you posted expected output screenshot.  OK let me look further.

**Comment by melloware** [comment]
OK PR updated.  Please review again and now your tester is show "A B C" in my local environment.

**Comment by mikioma** [comment]
Thank you very much everyone :) For the comments and the quick fix!!!

I Appreciate it.
