### ISSUE TITLE
DataTable: add swipe support

### ISSUE THREAD

**Issue by fcanevar** [primefaces/primefaces#608]
It would be nice to have the same swipe functionalities that are available in the mobile-renderkit also in the standard one so that responsive pages could be swipable.

Fabio

**Comment by fcanevar** [comment]
I'd add that it could be interesting to add a boolean attribute "swipable" to the datatable component that, if enabled and if the paginator is rendered, enables the user to swipe left and right to go in the next/prev page without using the paginator itself.

Here it is some code that I've made, hope it helps.

I've made a custom paginator to add the swipe functionality for the current datatable:

```
$(function(){
    addSwipe('#{component.namingContainer.clientId}');
});
```

The addSwipe js function looks like this:

```
function addSwipe(id){
    $(document.getElementById(id)).swipe({
        swipeLeft : function(event, direction, distance, duration, fingerCount, fingerData) {
            // do paginator next
        },
        swipeRight : function(event, direction, distance, duration, fingerCount, fingerData) {
            // do paginator previous
        }
    });
}
```

It works like a charm, @tandraschko do you think that this functionality could be a good fit for PrimeFaces?

**Comment by tandraschko** [comment]
don't know, it's up to @cagataycivici  :)

**Comment by tandraschko** [comment]
Would be great if you could provide a PR. It's a great feature for tablets which doesn't require a mobile renderkit.

**Comment by cocorossello** [comment]
Hi, 

This is not configurable, and can cause problems if datatable has horizontal scroll.

Of course, it can be deactivated with a hacky patch, but it would be good if one can configure it.

`PrimeFaces.widget.Paginator.prototype.bindSwipeEvents = function() {}
`

**Comment by melloware** [comment]
@cocorossello Please create a new ticket to make this configurable.
