### ISSUE TITLE
Theme: CSS is loaded without version

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6083]
**Description**
PrimeFaces theme.css is loaded in `HeadRenderer` but does not append the version so its causing the browser to not refresh the cache on PF updates.

```xml
<link type="text/css" rel="stylesheet" 
         href="/primefaces-test/javax.faces.resource/theme.css.xhtml?ln=primefaces-omega" />
```

**Describe the solution you would like**
The version to be appended to the theme.css resource.

```xml
<link type="text/css" rel="stylesheet" 
         href="/primefaces-test/javax.faces.resource/theme.css.xhtml?ln=primefaces-omega&amp;v=8.0"" />
```

**Additional context**
The bug is in `PrimeResource` only looking for ln=primefaces exactly and not "startsWith" primefaces because the themes are `ln=primefaces-omega` etc.

**Comment by tandraschko** [comment]
any news here @melloware ?

**Comment by melloware** [comment]
No I was going to resubmit my PR.  My PRO ticket is still open.
