### ISSUE TITLE
ImageCropper : two render issues

### ISSUE THREAD

**Issue by maasvdberg** [primefaces/primefaces#6085]
1. BoxHeight instead of Box**Width** is rendered for max-**width**
2. NPE when no initialCoords is specified

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

1. I don't know what you mean as its doing this
```java
 writer.writeAttribute("style", "max-width: 100%;", null);
```

2. I can't reproduce.  I removed `initialCoords ` in Showcase and it works fine. 

So again without a reproducer there is not much we can do to help.

**Comment by melloware** [comment]
Nice PR I can now see both issues!
