### ISSUE TITLE
PrimeExceptionHandler should lookup error page in accordance with the servlet spec

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#609]
Shouldn't just go with root cause and expect an exact exception class match.
As servlet 3.1 spec defines it:

> The Web application may have declared error pages using the exception-type
> element. In this case the container matches the exception type by comparing the
> exception thrown with the list of error-page definitions that use the exception-type
> element. A match results in the container returning the resource indicated in the
> location entry. The closest match in the class hierarchy wins.
> If no error-page declaration containing an exception-type fits using the classhierarchy match, and the exception thrown is a ServletException or subclass
> thereof, the container extracts the wrapped exception, as defined by the
> ServletException.getRootCause method. A second pass is made over the error
> page declarations, again attempting the match against the error page declarations,
> but using the wrapped exception instead.

See Undertow implementation for reference: https://github.com/undertow-io/undertow/blob/master/servlet/src/main/java/io/undertow/servlet/core/ErrorPages.java

**Comment by tandraschko** [comment]
Please post a example whats the difference and why you think we should change it.

**Comment by VsevolodGolovanov** [comment]
Servlet spec says: look at the caught exception, and in the error pages definitions find the exception-type that is the closest match in the class hierarchy (i.e. exact class match or nearest superclass).
PEH: look at the root cause, find exact exception class match with the exception-type.

You're relying on a web application descriptor, it's format and the way it's processed is specified in the servlet specification. It's iffy to just repurpose someone else's config to be interpreted in another way.
What if I use multiple exception handlers, some are complying and PEH is not. They're gonna lookup  error pages differently? That's a mess.

It's better to separate error page lookup in a protected method. Do it according to the spec by default. If someone needs it different, then he can inherit PEH and overload the method.

**Comment by tandraschko** [comment]
Feel free to provide a pull request, so that i can have a look at it and review it.

**Comment by VsevolodGolovanov** [comment]
Thanks!
