### ISSUE TITLE
Responsive Grid: ui-g-0 ui-md-0 ui-lg-0

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primefaces#6098]
**Description**
Sometimes, I'd like a component (or simply a div) to be shown only on desktop. I'd like it to disappear (at least visually) on mobile, and vice-versa.

Consider [this social login example](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_social_login), I'd like to show:

- "**Or sign in manually:**" on mobile only (e.g., through a hypothetical `<div class="ui-g-12 ui-md-0 ui-lg-0"/>`
- "**Or:**" on desktop only (e.g., through a hypothetical `<div class="ui-g-0 ui-md-2 ui-lg-2"/>`

**Comment by melloware** [comment]
@mossaab0 the grid.css is right here if you would like to suggest a PR..
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/grid/grid.css

Also PrimeFlex is the newer version of this grid.css you might want to check it out and open a ticket there as well.
See here: https://github.com/primefaces/primeflex

**Comment by melloware** [comment]
I reported this on PrimeFlex as well: https://github.com/primefaces/primeflex/issues/24
