### ISSUE TITLE
New Component: Image Zoom

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#61]
Forum Post URL: http://forum.primefaces.org/viewtopic.php?f=3&t=23801

It would really great to have a component like this demos:
http://jdbartlett.com/loupe/
http://www.dynamicdrive.com/dynamicindex4/featuredzoomer.htm
http://codecanyon.net/item/epic-image-zoom/full_screen_preview/264395?ref=lvraa&ref=lvraa&clickthrough_id=73086153&redirect_back=true

**Comment by rider87** [comment]
agreed - would be great to have this in PF11

**Comment by MMAliAbbas** [comment]
+1

**Comment by melloware** [comment]
New Component in PrimeFaces Extensions can be used against `GraphicImage` or `Galleria`.

See: https://github.com/primefaces-extensions/primefaces-extensions/issues/461

And you can use it with `GraphicImage` like this...

```xml
    <p:graphicImage id="tibet"
                    alt="Tibet"
                    value="/resources/images/imagezoom/tibet-small.jpg"
                    pt:data-zoom-src="/showcase-ext/resources/images/imagezoom/tibet-hd.jpg"/>

    <pe:imageZoom for="tibet"/>
```

or with `Galleria` like this...

```xml
<p:galleria id="galleria" value="#{images}" var="image">
            <p:graphicImage value="/images/#{image}"
                            a:data-zoom-src="/images/hd/#{image}"/>
</p:galleria>
<pe:imageZoom for="galleria"/>
```

**Comment by Mredul-Hasan** [comment]
+1

**Comment by melloware** [comment]
@Mredul-Hasan see my post above this exists in PFE: https://www.primefaces.org/showcase-ext/sections/imagezoom/basicZoom.jsf
