### ISSUE TITLE
Primefaces 5.2 not invoke fileuploadlistener

### ISSUE THREAD

**Issue by umitmert** [primefaces/primefaces#610]
I want to use pf fileupload but fileupload listener is not invoked. My configuration is below. Could you help me?

web.xml

<filter>
<filter-name>PrimeFaces FileUpload Filter</filter-name>
<filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>
</filter>
<filter-mapping>
<filter-name>PrimeFaces FileUpload Filter</filter-name>
<servlet-name>Faces Servlet</servlet-name>
</filter-mapping>
<context-param>
<param-name>primefaces.UPLOADER</param-name>
<param-value>auto</param-value>
</context-param>

JSF

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
xmlns:s="http://jboss.org/schema/seam/taglib"
xmlns:ui="http://java.sun.com/jsf/facelets"
xmlns:f="http://java.sun.com/jsf/core"
xmlns:h="http://java.sun.com/jsf/html"
xmlns:p="http://primefaces.org/ui" template="../layout/template.xhtml">

<ui:define name="body">
<h:head>/h:head
<h:form enctype="multipart/form-data">
<p:fileUpload
fileUploadListener="#{customerAttachmentUploader.handleFileUpload()}"
mode="advanced" dragDropSupport="false" multiple="true"
sizeLimit="10000000" fileLimit="3"
allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
/h:form
/ui:define
/ui:composition

Java

public void handleFileUpload(FileUploadEvent event) {
System.out.println("successful");
FacesMessage message = new FacesMessage("Succesful",
event.getFile().getFileName() + " is uploaded.");
FacesContext.getCurrentInstance().addMessage(null, message);
}

Lib

commons-io-2.4.jar
commons-fileupload-1.3.1.jar

JSF 2.1
Primefaces 5.2
Seam 2.3

**Comment by cagataycivici** [comment]
Please use forum for these kind of questions.
