### ISSUE TITLE
Taglib: Wrong Signatures

### ISSUE THREAD

**Issue by Markus-Patt** [primefaces/primefaces#6102]
**Describe the defect**
primefaces-p.taglib.xml defines 

```xml
<function>
  <function-name>resolveFirstComponentWithId</function-name>
  <function-class>org.primefaces.util.ComponentTraversalUtils</function-class>
  <function-signature>java.lang.String firstWithId(java.lang.String, javax.faces.component.UIComponent)</function-signature>
</function>
```

The signature of `ComponentTraversalUtils.firstWithId` is
```java
public static UIComponent firstWithId(String id, UIComponent base)
```

Since the taglib defines the return value to be a String instead of an UIComponent, the IDE issues a warning.

**Comment by melloware** [comment]
Nice catch are you submitting a PR?

**Comment by Markus-Patt** [comment]
Yes, working on it.

btw. IntelliJ warns about some more definitions: ifGranted, ifAllGranted, ifAnyGranted and ifNoneGranted.
They are defined with a return type of "java.lang.Boolean", while it should be "boolean".
Is this intentional? It doesn't seem to be the same "kind of wrong" as firstWithId.

**Comment by melloware** [comment]
yeah not sure submit another PR with the changes to boolean if you want.

**Comment by Markus-Patt** [comment]
Ok, working on it.
