### ISSUE TITLE
FileDownload: error while use download with HTTPS

### ISSUE THREAD

**Issue by garcia-jj** [primefaces/primefaces#6111]
**Describe the defect**
When I tried to download a file using `p:download` component I get the error below. This error occurs only while running the website over HTTPS. Over HTTP the error doesn't occur.

`No enum constant com.sun.faces.context.ExternalContextImpl.ALLOWABLE_COOKIE_PROPERTIES.sameSite: java.lang.IllegalArgumentException: No enum constant com.sun.faces.context.ExternalContextImpl.ALLOWABLE_COOKIE_PROPERTIES.sameSite`

I see the related source code, and this possible bug has been introduced here: https://github.com/primefaces/primefaces/commit/54046f7fc16829c04348ac5f2e7db494e0cdf4d3#diff-5db35c17609edb98e035328d46b0c601R79

I'm running Primefaces built from source on Wildfly 20.

**Environment:**
 - PF Version: the latest built from source
 - JSF + version: jboss-jsf-api_2.3_spec-3.0.0.SP03 from Wildfly 20
 - Affected browsers: _e.g. All browsers

**To Reproduce**
1.  Visit the page using HTTP and then click on the Download button;
2. See that the file has been downloaded fine;
3. Visit the page using HTTPS and then click on the Download button;
2. See error

**Expected behavior**
Download file properly without any errors

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
	
	<h:body>
		<h:form>
			<p:commandButton value="Download" ajax="false" icon="pi pi-arrow-down">
				<p:fileDownload value="#{primefacesDownload.download()}" />
			</p:commandButton>
		</h:form>
	</h:body>
</html>
```

**Example Bean**
```java
import java.io.ByteArrayInputStream;
import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

@Named
@ViewScoped
public class PrimefacesDownload implements Serializable {

	private static final long serialVersionUID = 1L;

	public StreamedContent download() {
		return DefaultStreamedContent.builder()
				.name("primefaces-download.txt")
				.contentType("text/plain")
				.stream(() -> new ByteArrayInputStream("primefaces".getBytes()))
				.build();
	}
}
```

**Comment by tandraschko** [comment]
i think you need to remove sameSite or only add it in MyFaces

**Comment by melloware** [comment]
I will investigate if there is a way to make it work more generically for more containers.  I really wish they would have put this in Servlet 4.0!

**Comment by melloware** [comment]
Yep the problem is Mojarra here:
https://github.com/eclipse-ee4j/mojarra/blob/8509da68f0d6b48090745228b427b2332767dbea/impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java#L105-L111

I will open a ticket in Mojarra and submit a PR.  @tandraschko Is it OK if I detect MyFaces and leave this sameSite in?

**Comment by tandraschko** [comment]
Yep.
We already have a mojarra/myfaces check in the behavior code. I think we can move it to PrimeEnvironment

**Comment by melloware** [comment]
Perfect I will take care of it.

**Comment by melloware** [comment]
Actually it looks like MyFaces would throw an exception as well?

https://github.com/apache/myfaces/blob/master/impl/src/main/java/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java#L848

**Comment by melloware** [comment]
Unfortunately, I think we have no choice but to comment out this cookie setting until Servlet 5.0.

**Comment by garcia-jj** [comment]
Hello @melloware and @tandraschko. Thank you for your quick reply and fix 😍

**Comment by tandraschko** [comment]
@melloware i also get a warning in firefox with trunk (now):

Das Cookie “pf.initialredirect-c3e0f” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

sorry for not translating it, dont have much time. Please check it with google translate

**Comment by melloware** [comment]
Yep I am on it.

**Comment by melloware** [comment]
Yep this is the standard warning that all browsers have begun doing which is why SameSite in Servlet 5.0 is so important.

_The cookie “pf.initialredirect-c3e0f” will soon be rejected, since it says either “none” or an invalid value for the “sameSite” attribute without using the “secure” attribute. For more information on the "sameSite" attribute,_ 

Because we have `secure=true`  to support this ticket: https://github.com/primefaces/primefaces/issues/6040 the browser is now telling us because `SameSite` is not set it default to `none` which is bad.  

There is absolutely nothing we can do about this until Servlet 5.0 supports adding SameSite to the `Cookie` object.

PrimeClientUtils is setting `secure=true` only if you are over HTTPS over HTTP its not set.

**Comment by GedMarc** [comment]
Hmm cookie is just a string though, you can append  ;SameSite=true to the cookie

```
; SameSite=Strict ;Secure=true; 
```

**Comment by melloware** [comment]
Well not sure how to handle that but right now we are use FacesContext ExternalContent adddResponseCookie which delegates to Servlet Cookie.

https://github.com/primefaces/primefaces/blob/e375ec467e83933288b14ddbbb428e48ef6a102b/src/main/java/org/primefaces/util/ResourceUtils.java#L71-L84

And `Cookie` only allows setting these properties as of Servlet 4.0.
https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/Cookie.html
