### ISSUE TITLE
Calendar/DatePicker: this.input.inputmask is not a function

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6119]
just upgraded my applications to current SNAPSHOT and i get:

this.input.inputmask is not a function

it happens in the Calendar widget.

@melloware AFAIR you changed something here?

**Comment by melloware** [comment]
Yep I did but I tested it all with the Showcase?  The Calendar and DatePicker now include `@ResourceDependency(library = "primefaces", name = "inputmask/inputmask.js")`

InputMask has been separated into its own JS it used to be part of jquery Plugins but its too big and should be its own component.

**Comment by melloware** [comment]
I am running the Showcase locally and DatePicker and Calendar are both working fine for me with no console errors?

**Comment by tandraschko** [comment]
Yep, i see
i inherit the component class...
Still another error: formatCode[(match[0][0] + "x")] is undefined

my mask is 99.99.99?99 / 99.99.99[99]

**Comment by melloware** [comment]
Yep I updated the WIKI: https://github.com/primefaces/primefaces/wiki/Migration-Guide#80-to-90

_InputMask Optional section of mask no longer starts with ? but must be wrapped in [ and ]._

The new InputMask does it correctly instead of ? it uses [ and ] which in turn also fixes this issue: https://github.com/primefaces/primefaces/issues/1892

The new InputMask fixed 4 old bugs with the old InputMask.

**Comment by tandraschko** [comment]
yeah, i switched to 99.99.99[99] but the error occurs.
Can you try my case?

**Comment by melloware** [comment]
Sure let me test.  What is your calendar pattern="" ?

**Comment by tandraschko** [comment]
pattern="dd.MM.yyyy"


locale de

**Comment by melloware** [comment]
perfect thanks will debug.

**Comment by melloware** [comment]
OK I fixed it can you pull and try again?  

Basically the new InputMask has alias for DateTime so it will take a mask like 'mm.dd.yyyy" if you say `mask='true'` but I didn't realize the mask can also be `mask='99.99.9999'` so the InputMask has different config for that.
