### ISSUE TITLE
Perf: MoveScriptsToBottom

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6123]
**Description**
Currently MoveScriptsToBottom uses string concatenation and `String.replace` function calls to shrink the output script.  However each of these replace calls results in String concat and garbarge collection.

**Describe the solution you would like**
Perform the multiple replaces without String concat and garbage collection by using an efficient method using a String Builder and the least number of passes over the string to do replacement.  Perfect candidate is Commons Lang `StringUtils.replaceEachRepeatedly`.

**Additional context**
The performance of this method say over 1000 characters looking for 10 string replacements takes `0 seconds, 7 millis`

**Comment by tandraschko** [comment]
please post some numbers before/after

**Comment by melloware** [comment]
Will do!

**Comment by melloware** [comment]
OK so I have before and after numbers using 2 showcase pages the Datatable Scroll example and the DatePicker page since that has a lot of components on it.

**BEFORE:**
DatePickerExecution time nanoseconds : 707600
DataTable Scroll Execution time nanoseconds : 179800

**AFTER:**
DatePicker Execution time in nanoseconds : 477400 (32% improvement)
DataTable Scroll Execution time in nanoseconds : 125000 (30% improvement)

What these numbers don't capture is the reduction in garbage collection of the temporary strings that were being constructed before where the new method uses a String Builder the whole time.

**Comment by tandraschko** [comment]
please do at least something like: https://gist.github.com/tandraschko/4abf2416cca6c19dd024e39e7033a47c (NOTE: the warmup is important)

you cant really measure such changes via JSF requests

**Comment by tandraschko** [comment]
i dont think generated objects are really important here (compared to speed performance), its only once per request

**Comment by melloware** [comment]
You are right the performance is negligible when using the new function.
```java
@Test
    public void testPerformance() throws IOException {
        // Arrange
        String id = "1";
        String type = "text/javascript";
        List<String> inlines = new ArrayList<>(1000000*2);
        for (int i = 0; i < 1000000; i++) {
            inlines.add("PrimeFaces.cw(" + RandomStringUtils.random(30) + ")");
            inlines.add("window.PrimeFaces");
        }

        // Act
        long start = System.currentTimeMillis();
        String result =  writer.mergeAndMinimizeInlineScripts(id, type, inlines);
        System.err.println("Minimize Script 1 = " + (System.currentTimeMillis() - start) + "ms");

        start = System.currentTimeMillis();
        result =  writer.mergeAndMinimizeInlineScripts(id, type, inlines);
        System.err.println("Minimize Script 2 = " + (System.currentTimeMillis() - start) + "ms");

        start = System.currentTimeMillis();
        result =  writer.mergeAndMinimizeInlineScripts(id, type, inlines);
        System.err.println("Minimize Script 3 = " + (System.currentTimeMillis() - start) + "ms");

        // Assert
        org.junit.jupiter.api.Assertions.assertNotNull(result);
    }
```

**Before:**
Minimize Script 1 = 2793ms
Minimize Script 2 = 1436ms
Minimize Script 3 = 1547ms

**After:**
Minimize Script 1 = 2615ms
Minimize Script 2 = 1381ms
Minimize Script 3 = 1486ms

**Comment by tandraschko** [comment]
please do at lest like 1000 warmups before measure and measure at least 100 times (accumulated)

**Comment by melloware** [comment]
OK I think I did this right by adding 100 warmup runs and the numbers look much different.

```java
    @Test
    public void testPerformance() throws IOException {
        // Arrange
        String id = "1";
        String type = "text/javascript";
        List<String> inlines = new ArrayList<>(1000000*2);
        for (int i = 0; i < 1000000; i++) {
            inlines.add("PrimeFaces.cw(" + RandomStringUtils.random(30) + ")");
            inlines.add("window.PrimeFaces");
        }

        // 100 warm ups
        for (int i = 0; i < 100; i++) {
            writer.mergeAndMinimizeInlineScripts(id, type, inlines);
        }

        // Act
        long start = System.currentTimeMillis();
        String result =  writer.mergeAndMinimizeInlineScripts(id, type, inlines);
        System.err.println("Minimize Script 1 = " + (System.currentTimeMillis() - start) + "ms");

        start = System.currentTimeMillis();
        result =  writer.mergeAndMinimizeInlineScripts(id, type, inlines);
        System.err.println("Minimize Script 2 = " + (System.currentTimeMillis() - start) + "ms");

        start = System.currentTimeMillis();
        result =  writer.mergeAndMinimizeInlineScripts(id, type, inlines);
        System.err.println("Minimize Script 3 = " + (System.currentTimeMillis() - start) + "ms");

        // Assert
        org.junit.jupiter.api.Assertions.assertNotNull(result);
    }
```
**Before:**
Minimize Script 1 = 739ms
Minimize Script 2 = 739ms
Minimize Script 3 = 1183ms

**After:**
Minimize Script 1 = 535ms
Minimize Script 2 = 580ms
Minimize Script 3 = 534ms

**Comment by tandraschko** [comment]
Please do 100 runs instead of 3 and compare the whole result

**Comment by melloware** [comment]
OK 100 runs of each with AVG calculated at the bottom:
**Before:**
Minimize Script 0 = 2824ms
Minimize Script 1 = 1400ms
Minimize Script 2 = 1482ms
Minimize Script 3 = 1206ms
Minimize Script 4 = 672ms
Minimize Script 5 = 1524ms
Minimize Script 6 = 650ms
Minimize Script 7 = 660ms
Minimize Script 8 = 615ms
Minimize Script 9 = 604ms
Minimize Script 10 = 631ms
Minimize Script 11 = 625ms
Minimize Script 12 = 614ms
Minimize Script 13 = 598ms
Minimize Script 14 = 629ms
Minimize Script 15 = 607ms
Minimize Script 16 = 609ms
Minimize Script 17 = 638ms
Minimize Script 18 = 716ms
Minimize Script 19 = 652ms
Minimize Script 20 = 690ms
Minimize Script 21 = 688ms
Minimize Script 22 = 667ms
Minimize Script 23 = 710ms
Minimize Script 24 = 652ms
Minimize Script 25 = 659ms
Minimize Script 26 = 694ms
Minimize Script 27 = 679ms
Minimize Script 28 = 660ms
Minimize Script 29 = 707ms
Minimize Script 30 = 711ms
Minimize Script 31 = 713ms
Minimize Script 32 = 678ms
Minimize Script 33 = 689ms
Minimize Script 34 = 697ms
Minimize Script 35 = 666ms
Minimize Script 36 = 713ms
Minimize Script 37 = 684ms
Minimize Script 38 = 693ms
Minimize Script 39 = 701ms
Minimize Script 40 = 685ms
Minimize Script 41 = 708ms
Minimize Script 42 = 704ms
Minimize Script 43 = 697ms
Minimize Script 44 = 680ms
Minimize Script 45 = 687ms
Minimize Script 46 = 684ms
Minimize Script 47 = 684ms
Minimize Script 48 = 692ms
Minimize Script 49 = 688ms
Minimize Script 50 = 710ms
Minimize Script 51 = 705ms
Minimize Script 52 = 706ms
Minimize Script 53 = 703ms
Minimize Script 54 = 680ms
Minimize Script 55 = 741ms
Minimize Script 56 = 737ms
Minimize Script 57 = 683ms
Minimize Script 58 = 701ms
Minimize Script 59 = 695ms
Minimize Script 60 = 685ms
Minimize Script 61 = 696ms
Minimize Script 62 = 694ms
Minimize Script 63 = 690ms
Minimize Script 64 = 702ms
Minimize Script 65 = 693ms
Minimize Script 66 = 715ms
Minimize Script 67 = 710ms
Minimize Script 68 = 684ms
Minimize Script 69 = 688ms
Minimize Script 70 = 703ms
Minimize Script 71 = 696ms
Minimize Script 72 = 692ms
Minimize Script 73 = 704ms
Minimize Script 74 = 720ms
Minimize Script 75 = 711ms
Minimize Script 76 = 712ms
Minimize Script 77 = 715ms
Minimize Script 78 = 729ms
Minimize Script 79 = 719ms
Minimize Script 80 = 705ms
Minimize Script 81 = 718ms
Minimize Script 82 = 703ms
Minimize Script 83 = 704ms
Minimize Script 84 = 706ms
Minimize Script 85 = 762ms
Minimize Script 86 = 698ms
Minimize Script 87 = 702ms
Minimize Script 88 = 708ms
Minimize Script 89 = 699ms
Minimize Script 90 = 713ms
Minimize Script 91 = 709ms
Minimize Script 92 = 690ms
Minimize Script 93 = 701ms
Minimize Script 94 = 723ms
Minimize Script 95 = 730ms
Minimize Script 96 = 701ms
Minimize Script 97 = 718ms
Minimize Script 98 = 716ms
Minimize Script 99 = 686ms
### Average = 739ms

**After:**
Minimize Script 0 = 2429ms
Minimize Script 1 = 1294ms
Minimize Script 2 = 1467ms
Minimize Script 3 = 770ms
Minimize Script 4 = 755ms
Minimize Script 5 = 697ms
Minimize Script 6 = 622ms
Minimize Script 7 = 1118ms
Minimize Script 8 = 543ms
Minimize Script 9 = 617ms
Minimize Script 10 = 833ms
Minimize Script 11 = 609ms
Minimize Script 12 = 1430ms
Minimize Script 13 = 503ms
Minimize Script 14 = 1214ms
Minimize Script 15 = 577ms
Minimize Script 16 = 980ms
Minimize Script 17 = 526ms
Minimize Script 18 = 1020ms
Minimize Script 19 = 581ms
Minimize Script 20 = 567ms
Minimize Script 21 = 1317ms
Minimize Script 22 = 537ms
Minimize Script 23 = 552ms
Minimize Script 24 = 541ms
Minimize Script 25 = 519ms
Minimize Script 26 = 560ms
Minimize Script 27 = 1193ms
Minimize Script 28 = 515ms
Minimize Script 29 = 561ms
Minimize Script 30 = 512ms
Minimize Script 31 = 512ms
Minimize Script 32 = 590ms
Minimize Script 33 = 1208ms
Minimize Script 34 = 513ms
Minimize Script 35 = 519ms
Minimize Script 36 = 510ms
Minimize Script 37 = 519ms
Minimize Script 38 = 515ms
Minimize Script 39 = 508ms
Minimize Script 40 = 520ms
Minimize Script 41 = 591ms
Minimize Script 42 = 1320ms
Minimize Script 43 = 550ms
Minimize Script 44 = 554ms
Minimize Script 45 = 529ms
Minimize Script 46 = 510ms
Minimize Script 47 = 578ms
Minimize Script 48 = 539ms
Minimize Script 49 = 523ms
Minimize Script 50 = 1221ms
Minimize Script 51 = 545ms
Minimize Script 52 = 536ms
Minimize Script 53 = 551ms
Minimize Script 54 = 542ms
Minimize Script 55 = 515ms
Minimize Script 56 = 556ms
Minimize Script 57 = 527ms
Minimize Script 58 = 507ms
Minimize Script 59 = 1025ms
Minimize Script 60 = 602ms
Minimize Script 61 = 542ms
Minimize Script 62 = 585ms
Minimize Script 63 = 537ms
Minimize Script 64 = 541ms
Minimize Script 65 = 555ms
Minimize Script 66 = 1314ms
Minimize Script 67 = 553ms
Minimize Script 68 = 542ms
Minimize Script 69 = 600ms
Minimize Script 70 = 511ms
Minimize Script 71 = 531ms
Minimize Script 72 = 1040ms
Minimize Script 73 = 524ms
Minimize Script 74 = 557ms
Minimize Script 75 = 526ms
Minimize Script 76 = 546ms
Minimize Script 77 = 618ms
Minimize Script 78 = 501ms
Minimize Script 79 = 1282ms
Minimize Script 80 = 533ms
Minimize Script 81 = 565ms
Minimize Script 82 = 514ms
Minimize Script 83 = 531ms
Minimize Script 84 = 1273ms
Minimize Script 85 = 568ms
Minimize Script 86 = 510ms
Minimize Script 87 = 571ms
Minimize Script 88 = 560ms
Minimize Script 89 = 1243ms
Minimize Script 90 = 525ms
Minimize Script 91 = 525ms
Minimize Script 92 = 523ms
Minimize Script 93 = 554ms
Minimize Script 94 = 1176ms
Minimize Script 95 = 588ms
Minimize Script 96 = 551ms
Minimize Script 97 = 545ms
Minimize Script 98 = 576ms
Minimize Script 99 = 576ms
### Average = 701ms

**Comment by tandraschko** [comment]
ok
a bit unsure.... you measure 1000000 inline scripts
i think 10-200 are realistic, so the improvement is like 0.01ms when rendering a view

**Comment by melloware** [comment]
Yep I am sold...

**Comment by tandraschko** [comment]
did you test with java8?
https://stackoverflow.com/questions/16228992/commons-lang-stringutils-replace-performance-vs-string-replace

java13 should even be faster as commons
java9 equals to commons
java8 only is slower

**Comment by melloware** [comment]
Yep all my tests were with 8 so yeah I can live with closing this.

**Comment by tandraschko** [comment]
If it would be called X times each request, i would be ok by merging it but.... :)

**Comment by melloware** [comment]
No worries this test has satisfied me that with 1000's of users this is not worth changing the code and when we move to Java 13 it really would not be worth it.
