### ISSUE TITLE
Schedule: Slots starting at a shifted time

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6126]
**Description**
If i have not overlooked something, the following modeling is not supported by the current schedule component:

Non-overlapping 12 h slots starting a given time, e.g., at 08:00 and 20:00.

In this case, the daily schedule should have two slots as follows:

08:00 ...
20:00 ...

The current implementation supports the following only:

00:00 ...
12:00 ...

when slotDuration="12:00" is defined.

So, it would be great to extend schedule component by an additional attribute to shift the slots by a given duration as desired. 

Of course, the value of this duration attribute must be smaller than the value of the attribute slotDuration.

... and the implementation should also work for any slotDuration which is a divisor of 24 h.

I am pretty sure that this shifted operation should be a typical use case in many applications. In our case, for instance,  instruments run from 08:00-20:00 in supervised mode while they run from 20:00-08:00 in silent mode.

**Comment by melloware** [comment]
@blutorange can you confirm?

**Comment by melloware** [comment]
@tuerker Can you post your XHTML snippet of your Schedule please so we can see your configuration?

**Comment by tuerker** [comment]
here is it.

        <p:schedule id="schedule"
                    value="#{instrumentReservationManager.lazyEventModel}"
                    initialDate="#{instrumentReservationManager.initialDate}"
                    showWeekends="#{instrumentReservation.instrumentReservationSetting.weekendAllowed}"
                    minTime="#{instrumentReservation.instrumentReservationSetting.minTimeFormat}"
                    maxTime="#{instrumentReservation.instrumentReservationSetting.maxTimeFormat}"
                    slotDuration="#{instrumentReservation.instrumentReservationSetting.slotDuration}"
                    slotEventOverlap="false"
                    slotLabelFormat="HH:mm"
                    timeFormat="HH:mm"
                    columnHeaderFormat="week:'dddd DD MMM', month:'dddd'"
                    rightHeaderTemplate="timeGridDay,timeGridWeek,dayGridMonth"
                    leftHeaderTemplate="prev, next, today"
                    tooltip="true"
                    showWeekNumbers="false"
                    allDaySlot="false"
                    aspectRatio="150"
                    view="agendaDay">

**Comment by melloware** [comment]
Looks like we need to add `slotMinTime`:
https://fullcalendar.io/docs/slotMinTime

You can use this right now if you use the Extender feature of Schedule:
https://primefaces.github.io/primefaces/8_0/#/components/schedule?id=extender-method

**Comment by melloware** [comment]
Actually according to the v4 docs it should be `minTime` and `maxTime`?  What do you have minTime and maxTime set to? "08:00:00" and "20:00:00"??

**Comment by melloware** [comment]
Here is what mine looks like with...
```xml
<p:schedule id="schedule" 
     value="#{scheduleJava8View.eventModel}" 
     widgetVar="myschedule"  
     minTime="08:00:00"
     maxTime="20:00:00">
```

![image](https://user-images.githubusercontent.com/4399574/86918706-0dd7fa00-c0f5-11ea-9c78-917d413256d2.png)

**Comment by tuerker** [comment]
The minTime and maxTime attributes are needed to restrict the daily available time. In your example you have restricted the schedule to events between 8:00 in the morning and 20:00 in the evening. 

My use case is orthogonal to that. I primarily do not want to restrict the daily available time but i want to state that slots can only start at certain times, e.g. at 08:00 and 20:00 in case of slotDuration="12:00". In the schedule, it should be shown that the slot goes from 20:00 to 08:00 of the next day, for instance. 

For realizing that I think an additional attribute is needed.

This becomes obvious when you consider the following use case where all four attributes would be needed:
Instruments are can be booked every day between 08:00 and 20:00 but you want to restrict the booking to 4h slots starting at following times:

18:00 -20:00 of previous day and 08:00 -10:00
10:00 -14:00
14:00 -18:00
18:00 -20:00 and 08:00-10:00 of next day

To define this use case, the following attributes would be needed:

minTime="08:00"
maxTime="20:00"
slotDuration="04:00"
and
slotMinTime="10:00"

**Comment by melloware** [comment]
Feel free to submit a PR as this looks like this functionality is not native to FullCalendar as far as I can tell.  Or possibly even report it on the FullCalendar issues page.

https://github.com/fullcalendar/fullcalendar/issues

**Comment by melloware** [comment]
Not sure if this is what you are looking for: https://github.com/fullcalendar/fullcalendar/issues/5224

**Comment by tuerker** [comment]
What about the scrollTime? 

https://fullcalendar.io/docs/scrollTime

Could this be a solution. 

I tried to apply the counterpart in p:schedule but there was no effect at all. Can you please verify whether the attribute scrollTime is really working on p:schedule.

**Comment by tuerker** [comment]
> Not sure if this is what you are looking for: [fullcalendar/fullcalendar#5224](https://github.com/fullcalendar/fullcalendar/issues/5224)

this is yet another issue i would love to have, too.

**Comment by tuerker** [comment]
some while ago, i created already an issue which goes into that direction:

https://github.com/primefaces/primefaces/issues/5551

**Comment by melloware** [comment]
> some while ago, i created already an issue which goes into that direction:
> 
> #5551

Well that is for DatePicker not for FullCalendar so not really related.  You should go upvote the https://github.com/fullcalendar/fullcalendar/issues/5224 issue if you want it.

And `scrollTime` is implemented in PF8.0 and defaults to `06:00:00`...
```java
.attr("scrollTime", schedule.getScrollTime(), "06:00:00")
```

**Comment by tuerker** [comment]
The scrollTime had no effect in my example below. Therefore, i was asking whether it really works.

<p:schedule id="schedule"
                    value="#{instrumentReservationManager.lazyEventModel}"
                    initialDate="#{instrumentReservationManager.initialDate}"
                    showWeekends="#{instrumentReservation.instrumentReservationSetting.weekendAllowed}"
                    scrollTime="08:00"
                    slotEventOverlap="false"
                    slotLabelFormat="HH:mm"
                    timeFormat="HH:mm"
                    columnHeaderFormat="week:'dddd DD MMM', month:'dddd'"
                    rightHeaderTemplate="timeGridDay,timeGridWeek,dayGridMonth"
                    leftHeaderTemplate="prev, next, today"
                    tooltip="true"
                    showWeekNumbers="false"
                    allDaySlot="false"
                    aspectRatio="150"
                    view="agendaDay">

![Screenshot from 2020-07-08 16-09-09](https://user-images.githubusercontent.com/10051373/86928917-82cb2400-c135-11ea-9fa7-db8048bc9aec.png)

**Comment by melloware** [comment]
And I am answering you YES its implemented but whether its a bug in FullCalendar or not I don't know.  See the open `scrollTime` issues and closed ones since 4.3.
Open: https://github.com/fullcalendar/fullcalendar/issues?q=is%3Aissue+is%3Aopen+scrolltime
Closed: https://github.com/fullcalendar/fullcalendar/issues?q=is%3Aissue+scrolltime+is%3Aclosed

**Comment by tuerker** [comment]
Many thanks for all your support. I will dig into that issue deeper.

**Comment by melloware** [comment]
For now I am marking this ticket as "third party" as its seems like we need some new FullCalendar features so there is nothing to fix in PF for your original issue.   I am happy to reopen if you decide to fix it with a quality PR or if FullCalendar ever implements your features.

**Comment by tuerker** [comment]
Since June 21, 2020 the fullcalendar library is out in Version 5.1.0. PF 9.0 currently relies on 4.3.1. It would be great if somebody could upgrade PF 9.0 to fullcalendar Version 5.1.0, which actually provides a number of new attributes including slotMinTime and slotMaxTime, which would by the way solve my feature request.

**Comment by melloware** [comment]
It’s already done if you look at the PRs it’s been upgraded to 5.1.0

**Comment by tuerker** [comment]
Great. After having a deeper look into fullcalendar v5, it looks like that slotMinTime and slotMaxTime are just the current minTime and maxTime attributes. So this will not solve my feature request.
