### ISSUE TITLE
PF 8 DatePicker: mindate,maxdate with selectionMode=range and i18n

### ISSUE THREAD

**Issue by KarimSI** [primefaces/primefaces#6127]
I have a problem with datePicker (rang minDate maxDate) and i18n (French-LFT- and Arabic – RTF-) don't work correctly.
for example in managed bean with : minDate="08/07/2020" and maxDate="11/08/2020" is show correctly in French page
but in arabic page become minDate="08/06/2020" and maxDate="11/05
![dateitre](https://user-images.githubusercontent.com/68004217/86901740-ee48cd80-c104-11ea-8fd4-047b2163655c.png)
/2020"

**Comment by KarimSI** [comment]
Sorry, the problem is in  Arabic.js file

**Comment by melloware** [comment]
@KarimSI would you be willing to update the Arabic locale here???
https://github.com/primefaces/primefaces/wiki/Locales#arabic

Use can use American English as the example that contains all the values that need to be translated?
See: https://github.com/primefaces/primefaces/wiki/Locales#american-english
