### ISSUE TITLE
Calendar: bug if mask defined

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#6129]
**Describe the defect**
inputmask.js.faces?ln=primefaces&v=9.0-SNAPSHOT:8 Uncaught TypeError: Cannot read property 'slice' of undefined in console

**Reproducer**
https://github.com/erickdeoliveiraleal/primefaces-test

**Environment:**
 - PF Version: master
 - JSF + version: _e.g. Mojarra 2.2.20
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. Run the project
2. Look in console

**Comment by melloware** [comment]
Thanks its fixed if you want to try 9.0-SNAPSHOT again.   It was just the order of scripts.

**Comment by erickdeoliveiraleal** [comment]
thanks
