### ISSUE TITLE
Screen Reader support for ColumnToggler and keyboard accessibility

### ISSUE THREAD

**Issue by LianeK** [primefaces/primefaces#613]
The checkboxes of new ColumnToggler element in DataTable are not accessible with keyboard

**Comment by melloware** [comment]
As of PF 7.0 I am able to tab to the checkboxes of Column Toggler and i am able to select unselect them using the SPACE bar.  So I am closing this ticket for now, if someone has other issues they can open a new ticket with more specific details.
