### ISSUE TITLE
DataTable: rows attribute get overriden with default value

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#6132]
**Describe the defect**
We have a composite component around a dataTable. So we can define a lot of defaults. After the upgrade from PrimeFaces 7.0 to 8.0 the change of rows to show does not work correctly. That is because of changes introduced with #4931 and #5527 which writes the new value to the value expression instead of writing into the attribute of the table.
Most likely this bug also exists for the other UiData implementing components.

**Reproducer**
https://github.com/OBreidenbach/primefaces-test/tree/DatatablePaginator

**Environment:**
 - PF Version: 8.0, 9.0-SNAPSHOT (9th July 2020)
 - JSF + version: Mojarra 2.3.9
 - Affected browsers: does not matter

**To Reproduce**
1. Go to 'open test page in reproducer'
2. Change number of rows in paginator
3. sort column
4. number of displayed rows jumps back to the initial 10 rows

**Expected behavior**
It should be displayed the number of rows that where selected in the paginator.

**Example XHTML**
```html
<mytags:myDataTable value="#{testView.rows}" myrows="10"/>
```
myDataTable 
```html 
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:cc="http://xmlns.jcp.org/jsf/composite"
                xmlns:p="http://primefaces.org/ui">

    <cc:interface>
        <cc:attribute name="value"  required="true"/>
        <cc:attribute name="myrows" type="java.lang.String" default="5" />
    </cc:interface>

    <cc:implementation>
        <p:dataTable id="pf_dataTable"
                     value="#{cc.attrs.value}"
                     var="row"
                     rows="#{cc.attrs.myrows}"
                     paginator="true"
                     rowsPerPageTemplate="2,5,10,30">

            <p:column id="row" filterBy="#{row.str}" filterMatchMode="contains" sortBy="#{row.str}">
                #{row.str}
            </p:column>

        </p:dataTable>
    </cc:implementation>
</ui:composition>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

    private String testString;
    private List<Row> rows;

    @PostConstruct
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
        List<Row> _list = new ArrayList<>(50);
        for (int i = 0; i < 50; i++) {
            _list.add(new Row(i));
        }
        rows = _list;
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

    public List<Row> getRows() {
        return rows;
    }

    public static class Row implements Serializable{
        private String str;

        public Row() {
        }

        public Row(int i) {
            this.str = String.format("row %02d", i);
        }

        public String getStr() {
            return str;
        }

        public void setStr(String str) {
            this.str = str;
        }
    }
}
```

**Comment by melloware** [comment]
@OBreidenbach Only when inside a composite component but the same thing works outside of a composite?

**Comment by OBreidenbach** [comment]
It works fine outside of a composite.

**Comment by melloware** [comment]
You are right previously it evaluated rows once and then stored the value.  Now if its an EL expression like `rows="#{cc.attrs.myrows}"` is re-evaluating the EL expression everytime.  Not sure how to fix this since the EL re-evaluation was added to fix the bugs you mentioned above.

**Comment by OBreidenbach** [comment]
In my humble opinion #4931 was not a bug, it is the false usage of the component. The problem could be solved different.

1. It is the pagers job to change the first or rows attribute. So the pager should be used. If @matinh want's to use a spinner, instead the drop down of the pager may be the pager should be more configurable.
2. If i want to set the component attributes I would just do so. Either in java or in xhtml. Example:
```html
<p:dataTabel id="grid" binding=#{myDataTable} ...>
</p:dataTable>

<p:spinner id="entries" value="#{myDataTable.rows}">
    <p:ajax update="grid"/>
 </p:spinner>
```
3. If soneone wants to override the component functions he should just do so for his project. Their is no need to breaking functions which worked for years.

I would revert the 'fix' for  #4931 and #5527 and choose a better solution for the initial problem.

**Comment by melloware** [comment]
I would like @tandraschko and @Rapster to weigh in too please.

**Comment by OBreidenbach** [comment]
May be the client side api would help to change the rowsPerPage from outside the paginator:
dataTableWidget.getPaginator().setRowsPerPage()

**Comment by melloware** [comment]
Want to give it s shot and see?

**Comment by OBreidenbach** [comment]
If I were @matinh I had solved the problem the following way:
https://github.com/OBreidenbach/primefaces-test/tree/dataGrid

```html
<h:form id="myForm">
    <p:dataGrid id="grid"
                columns="1"
                value="#{testViewCdi.entries}"
                var="_it"
                paginator="true"
                paginatorAlwaysVisible="true"
                rowsPerPageTemplate="1,2,3"
                first="#{testViewCdi.first}"
                rows="#{testViewCdi.columns}"
                binding="#{myDataGrid}">
        <p:ajax event="page" update="@form:anotherpager" />
        <h:outputText value="value: #{_it}"/>
    </p:dataGrid>

    <h:panelGrid id="anotherpager" columns="2">
        <h:outputLabel for="first" value="first="/>
        <p:spinner id="first" value="#{myDataGrid.first}">
            <p:ajax update="grid"/>
        </p:spinner>

        <h:outputLabel for="entries" value="columns="/>
        <p:spinner id="entries" value="#{myDataGrid.rows}">
            <p:ajax update="grid"/>
        </p:spinner>
    </h:panelGrid>
</h:form>
```

**Comment by OBreidenbach** [comment]
Or by using client side api:
```html
<h:form id="myForm">
    <p:dataGrid id="grid"
                columns="1"
                value="#{testViewCdi.entries}"
                var="_it"
                paginator="true"
                paginatorAlwaysVisible="true"
                rowsPerPageTemplate="1,2,3,4,5,6,7,8"
                first="#{testViewCdi.first}"
                rows="#{testViewCdi.columns}"
                widgetVar="dataGridWidgetVar">
        <p:ajax event="page" update="@form:anotherpager" />
        <h:outputText value="value: #{_it}"/>
    </p:dataGrid>

    <h:panelGrid id="anotherpager" columns="2">
        <h:outputLabel for="first" value="first="/>
        <p:spinner id="first"
                   value="#{testViewCdi.first}"
                   onchange="PF('dataGridWidgetVar').getPaginator().setPage(parseInt($(this).val()));">
        </p:spinner>

        <h:outputLabel for="entries" value="columns="/>
        <p:spinner id="entries"
                   value="#{testViewCdi.columns}"
                   onchange="PF('dataGridWidgetVar').getPaginator().setRowsPerPage(parseInt($(this).val()));">
        </p:spinner>
    </h:panelGrid>
</h:form>
```

**Comment by matinh** [comment]
Hi!

In preparation to fix #4931 @tandraschko wanted me to analyze what actually happened (https://github.com/primefaces/primefaces/pull/4937#issuecomment-505469850). I did this and concluded in https://github.com/primefaces/primefaces/issues/4931#issuecomment-505859004:

> IMHO the suggested fix should be ok. I'm not 100% sure if this is the suggested way, how PrimeFaces components should handle this situation, but currently I do not see any problems with this approach.

@melloware than created a new pull-request and @tandraschko merged it. So I thought, the changes originally suggested by @Rapster and finalized by me were ok. At the time of creating this patch I had no deeper knowledge of PrimeFaces internals, but 3 contributors/committers of the PrimeFaces project reviewed the patch. So I had no doubt, the changes were valid.

@OBreidenbach's suggestions might work (I didn't have time to test them), they sound reasonable to me. Still the observed behavior before #4931 was 'fixed', looks unintuitive and like a bug to me. Reverting this changes reintroduces that behavior: if I have a component with an attribute that accepts an EL-expression, I would expect that the component writes changes to this attribute back to the EL-expression and not only to its internal state, which was the case.

Hence, I cannot say, what is the best solution. IMHO, some JSF expert like @tandraschko should make this the decision.

Kind regards,
\- martin

**Comment by OBreidenbach** [comment]
@melloware, @tandraschko, @Rapster, @mertsincan  any suggestions how we can go on with this?

**Comment by melloware** [comment]
I am not sure either so i will defer to @mertsincan and @tandraschko

**Comment by tandraschko** [comment]
@melloware 
i wonder why its writable? https://github.com/primefaces/primefaces/commit/0b3bab65696a6730b453ca8ac67c6cf91c0f9775#diff-dbd5bf010355a6e45344e7e75e5ff676R152

**Comment by melloware** [comment]
Well that was to fix if someone wanted a dynamic rows="#{EL}" it was never re-evaluating the EL.  See: https://github.com/primefaces/primefaces/issues/4931

**Comment by tandraschko** [comment]
nono, my question is why #{cc.attrs.myrows} with a fixed value=10, is a writeable EL? Or what else doesnt work in this case?

**Comment by melloware** [comment]
Huh that is a good question.

**Comment by tandraschko** [comment]
if i understand correctly, the rows attribute should be saved as attribute as the VE isnt writeable actually?

**Comment by tandraschko** [comment]
you owe me a beer now ;)

**Comment by melloware** [comment]
Nice work !!!
