### ISSUE TITLE
InputNumber: valueChange event not fired if CSP context-param is set

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces#6142]
When using p:inputNumber, the p:ajax default (valueChange) event does not fire on change of value when the CSP context-param is set... unless the MOVE_SCRIPTS_TO_BOTTOM context-param is _also_ set, in which case it works normally.

**Reproducer**
See attached. Ths sampe code is based on the InputNumber showcase example.
[tester_inputNumber_src.zip](https://github.com/primefaces/primefaces/files/4907592/tester_inputNumber_src.zip)

**Environment:**
 - PF Version: _8.0_
 - Mojarra 2.3
 - Affected browsers: _ALL_

**To Reproduce**
See reproducer. Set web.xml to include CSP and exclude Move_Scripts_to_Bottom. 
The sample app. is based on Showcase.

**Expected behavior**
The p:ajax events should fire normally regardless of whether CSP is set or not.

**Workaround**
Either don't use CSP context-param, or if you need to, also use Move_Scripts_to_Bottom context-param.

**Comment by melloware** [comment]
Thanks for the reproducer. I will look into it!

**Comment by melloware** [comment]
If you need this fix right now just add this JS to your page.
```javascript
PrimeFaces.widget.InputNumber.prototype.wrapEvents = function() {
    var $this = this;

    // copy the value from the input to the hidden input
    var originalOnkeyup = this.input.prop('onkeyup');
    this.input.prop('onkeyup', null).off('keyup').on('keyup', function(e) {

        var oldValue;

        var keyCode = e.which;
        if (keyCode === 8 || keyCode === 13 || keyCode === 32 ||
            (keyCode >= 46 && keyCode <= 90) ||
            (keyCode >= 96 && keyCode <= 111) ||
            (keyCode >= 186 && keyCode <= 222)) {

            oldValue = $this.copyValueToHiddenInput();
        }

        if (originalOnkeyup && originalOnkeyup.call(this, e) === false) {
            if (oldValue) {
                $this.setValueToHiddenInput(oldValue);
            }
            return false;
        }
    });

    var originalOnchange = this.input.prop('onchange');
    this.input.prop('onchange', null).off('change.inputnumber').on('change.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnchange && originalOnchange.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    var originalOnkeydown = this.input.prop('onkeydown');
    this.input.prop('onkeydown', null).off('keydown.inputnumber').on('keydown.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnkeydown && originalOnkeydown.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    // handle mousewheel and paste
    this.input.off('input.inputnumber').on('input.inputnumber', function(e) {
        $this.copyValueToHiddenInput();
    });
};
```

**Comment by melloware** [comment]
Sorry that didn't quite fix it.  Still working on it.

**Comment by melloware** [comment]
OK can you add this JS to your application and run it and see if it fixes your issue.
```javascript
PrimeFaces.widget.InputNumber.prototype.wrapEvents = function() {
    var $this = this;

    // copy the value from the input to the hidden input
    var originalOnkeyup = this.input.prop('onkeyup');
    this.input.prop('onkeyup', null).off('keyup.inputnumber').on('keyup.inputnumber', function(e) {

        var oldValue;

        var keyCode = e.which;
        if (keyCode === 8 || keyCode === 13 || keyCode === 32 ||
            (keyCode >= 46 && keyCode <= 90) ||
            (keyCode >= 96 && keyCode <= 111) ||
            (keyCode >= 186 && keyCode <= 222)) {

            oldValue = $this.copyValueToHiddenInput();
        }

        if (originalOnkeyup && originalOnkeyup.call(this, e) === false) {
            if (oldValue) {
                $this.setValueToHiddenInput(oldValue);
            }
            return false;
        }
    });

    var originalOnchange = this.input.prop('onchange');
    this.input.prop('onchange', null).off('change.inputnumber').on('change.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnchange && originalOnchange.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    var originalOnkeydown = this.input.prop('onkeydown');
    this.input.prop('onkeydown', null).off('keydown.inputnumber').on('keydown.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnkeydown && originalOnkeydown.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    // handle mousewheel and paste
    this.input.off('input.inputnumber').on('input.inputnumber', function(e) {
        $this.copyValueToHiddenInput();
    });
};
```

**Comment by brooksie** [comment]
I just added <script>... </script> to the body of the affected web page and got:
Error Parsing /index.xhtml: Error Traced[line: 167] The entity name must immediately follow the '&' in the entity reference.
PS. Javscript is definitely not my strong point. Sorry.
    On Sunday, 12 July 2020, 20:32:58 BST, Melloware <notifications@github.com> wrote:  
 
 


OK can you add this JS to your application and run it and see if it fixes your issue.
PrimeFaces.widget.InputNumber.prototype.wrapEvents = function() {
    var $this = this;

    // copy the value from the input to the hidden input
    var originalOnkeyup = this.input.prop('onkeyup');
    this.input.prop('onkeyup', null).off('keyup.inputnumber').on('keyup.inputnumber', function(e) {

        var oldValue;

        var keyCode = e.which;
        if (keyCode === 8 || keyCode === 13 || keyCode === 32 ||
            (keyCode >= 46 && keyCode <= 90) ||
            (keyCode >= 96 && keyCode <= 111) ||
            (keyCode >= 186 && keyCode <= 222)) {

            oldValue = $this.copyValueToHiddenInput();
        }

        if (originalOnkeyup && originalOnkeyup.call(this, e) === false) {
            if (oldValue) {
                $this.setValueToHiddenInput(oldValue);
            }
            return false;
        }
    });

    var originalOnchange = this.input.prop('onchange');
    this.input.prop('onchange', null).off('change.inputnumber').on('change.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnchange && originalOnchange.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    var originalOnkeydown = this.input.prop('onkeydown');
    this.input.prop('onkeydown', null).off('keydown.inputnumber').on('keydown.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnkeydown && originalOnkeydown.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    // handle mousewheel and paste
    this.input.off('input.inputnumber').on('input.inputnumber', function(e) {
        $this.copyValueToHiddenInput();
    });
};

**Comment by melloware** [comment]
You can't add it to the page because of XHTML and ampersand & in JS.  Add to a JS file.

Attached is example adding `test.js` to the page with this fix:
[pf-6142.zip](https://github.com/primefaces/primefaces/files/4912348/pf-6142.zip)

**Comment by brooksie** [comment]
Hi, 

Yes, that seems to work fine.
Thanks.

    On Monday, 13 July 2020, 13:21:52 BST, Melloware <notifications@github.com> wrote:  
 
 


You can't add it to the page because of XHTML and ampersand & in JS. Add to a JS file.

Attached is example adding test.js to the page with this fix:
pf-6142.zip

**Comment by melloware** [comment]
Here is the final proper method for CSP and non CSP usage.
```javascript
PrimeFaces.widget.InputNumber.prototype.wrapEvents = function() {
    var $this = this;

    // get the current attached events if using CSP
    var events = $._data(this.input[0], "events");

    // copy the value from the input to the hidden input
    var originalOnkeyup = this.input.prop('onkeyup');
    if (!originalOnkeyup && events.keyup) {
        originalOnkeyup = events.keyup[0].handler;
    }
    this.input.prop('onkeyup', null).off('keyup').on('keyup.inputnumber', function(e) {

        var oldValue;

        var keyCode = e.which;
        if (keyCode === 8 || keyCode === 13 || keyCode === 32 ||
            (keyCode >= 46 && keyCode <= 90) ||
            (keyCode >= 96 && keyCode <= 111) ||
            (keyCode >= 186 && keyCode <= 222)) {

            oldValue = $this.copyValueToHiddenInput();
        }

        if (originalOnkeyup && originalOnkeyup.call(this, e) === false) {
            if (oldValue) {
                $this.setValueToHiddenInput(oldValue);
            }
            return false;
        }
    });

    var originalOnchange = this.input.prop('onchange');
    if (!originalOnchange && events.change) {
        originalOnchange = events.change[0].handler;
    }
    this.input.prop('onchange', null).off('change').on('change.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnchange && originalOnchange.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    var originalOnkeydown = this.input.prop('onkeydown');
    if (!originalOnkeydown && events.keydown) {
        originalOnkeydown = events.keydown[0].handler;
    }
    this.input.prop('onkeydown', null).off('keydown').on('keydown.inputnumber', function(e) {

        var oldValue = $this.copyValueToHiddenInput();
        if (originalOnkeydown && originalOnkeydown.call(this, e) === false) {
            $this.setValueToHiddenInput(oldValue);
            return false;
        }
    });

    // handle mousewheel and paste
    this.input.off('input.inputnumber').on('input.inputnumber', function(e) {
        $this.copyValueToHiddenInput();
    });
};
```
