### ISSUE TITLE
InputNumber: unable to clear value from field when using min/max range both > 0

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces#6145]
**Describe the defect**
There appear to be two related issues:
(i) it is not possible to delete a value again from an inputNumber field where the min/val values are set to be wholly positive and does not include zero - e.g. minValue 1, maxValue 100 - The field is an option, and is not a required value. The problem is the same whether the emptyValue attribute is absent, or when it is set to "null". (PS. the meaning of attribute values of "focus" and "press" per the documentation is not clear to me)
(ii) When the range is wholly negative (e.g. minValue -100, maxValue -1), it is not possible to enter any value into the field.

**Reproducer**
See attached.
[tester_inputNumber_delete_src.zip](https://github.com/primefaces/primefaces/files/4912144/tester_inputNumber_delete_src.zip)

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _Mojarra 2.2.8_
 - Affected browsers: _(at least) Firefox_

**To Reproduce**
Run the reproducer:
1. Enter a valid value into the first three fields, per the range specified.
     You will be unable to enter a value for the negative range in the third case [issue (ii)]
2. Now select each valid value in turn and delete the value from the field
     For the positive range, the old value is restored and not deleted [issue (i)].
Note that the actions work correctly for the second field where the range is -100 to +100.

**Expected behavior**
As the field is optional, it should be possible to remove the value and make it empty / null again (unless the emptyValue attribute specified that something else should be used).

**Comment by melloware** [comment]
@brooksie InputNumber uses a component called AutoNumeric under the covers.  Please see this long thread on why `minValue>0` causes this issue: https://github.com/autoNumeric/autoNumeric/issues/543

Here is the warning in the docs:
http://autonumeric.org/guide#minimumValue

_Warning: If minimumValue is superior to 0, then you'll effectively prevent your users to entirely delete the content of their AutoNumeric-managed element_

As for your issue about `min=-1 max=-10`  here is what I get in the Autonumeric error.log

_Uncaught Error: The minimum possible value option is greater than the maximum possible value option ; 'minimumValue' [-1] should be smaller than 'maximumValue' [-10]._

You can try it yourself with Codepen: https://codepen.io/AnotherLinuxUser/pen/JyBGpz

Just use:
```javascript
// AutoNumeric initialisation
const anElement = new AutoNumeric('input', {
  minimumValue: '-1',
  maximumValue: '-10'
});
```
