### ISSUE TITLE
IdleMonitor: multiWindowSupport propagates just idle event

### ISSUE THREAD

**Issue by sasynkamil** [primefaces/primefaces#6151]
When used IdleMonitor & multiWindowSupport=true, just "idle" ajax event is propagated to second (inactive window/tab). "active" event is not propagated.

Basically I don't know if this is feature or bug. Since user is not active in second (inactive window/tab) then I can understand that this is feature. In that case it would be good to mention this in IdleMonitor documentation.

If this is bug I can provide testing project.

**Environment:**

PF Version: 8.0
Mojarra 2.3
Affected browsers: ALL

**How to reproduce:**

1) Implement
```xml
<p:idleMonitor timeout="5000" update="messages">
    <p:ajax event="active" onstart="console.log('active')"/>
    <p:ajax event="idle" onstart="console.log('idle')"/>
</p:idleMonitor>
```

2) Open two windows
3) Open browser console in both
4) Stay idle 5s+ / be active in front window
5) Watch console: back (inactive) window will have logs just for "idle" / front window will have logged both idle & active.

**Comment by tandraschko** [comment]
The current behavior is completely by design from a customer

**Comment by melloware** [comment]
@sasynkamil here was the original ticket implementation: https://github.com/primefaces/primefaces/issues/2461

**Comment by melloware** [comment]
@tandraschko Since I think this is the correct behavior I updated the documentation to describe the behavior for `active` vs `idle` events and mutliWindowSupport.

I also updated the key creation to our new method `createStorageKey` vs the current custom implementation in IdleMonitor.
