### ISSUE TITLE
Component: DatePicker and rangeSeparator issue

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#6155]
CalendarUtils does not honor rangeSeparator in 7.0.14 (in 8.0.* it does). Please fix it.

master:
```
String separator = "multiple".equals(calendar.getSelectionMode()) ? "," : " " + calendar.getRangeSeparator() + " ";
```
7.0
```
String separator = "multiple".equals(calendar.getSelectionMode()) ? "," : " - ";
```

**Comment by morvael** [comment]
Enchancement? It's half baked feature (works in one way instead of two way as it should). To me it's a defect. Anyway, good to know it will be fixed. Too bad only in 7.0.16, was hoping for 7.0.15.

**Comment by melloware** [comment]
Closing issue as its an Elite issue fixed in 7.0.16. Thanks @mertsincan

**Comment by morvael** [comment]
Yes, we're using Elite. Is there another way to report problems in Elite?

**Comment by melloware** [comment]
Unfortunately NO not without a PRO account there is no Elite forum or JIRA although there should be.
