### ISSUE TITLE
Schedule: Javascript Error

### ISSUE THREAD

**Issue by vitsin** [primefaces/primefaces#6156]
**Description**
At what point the Java11 support for p:schedule (PF v8.x) will be added ?
I've just tested p:schedule (PF v8.0.2) under Java 11 - p:schedule showing up, but none of the Events from the Model appear on p:schedule.
Example used: https://www.primefaces.org/showcase/ui/data/schedule/basic.xhtml but with Java 11, not Java 8.
Thanks.

**Comment by stolp** [comment]
I am using PrimeFaces 8.0.2 with Java 11 and my p:schedule component is able to display events correctly.

If your events are missing, this is probably related to something else.

**Comment by melloware** [comment]
yes i just switched the showcase locally to Java 11 and its working fine.

**Comment by GedMarc** [comment]
I'm on JDK 14 with PF 9-Snap in native modules - no issues here

**Comment by melloware** [comment]
@vitsin if you can reproduce it with a PrimeFaces Test example I will reopen but for now we have 3 people reporting Java11+ work fine.

**Comment by vitsin** [comment]
This is how I've used one single event on very simple model:
```		
ScheduleModel model = new DefaultScheduleModel();
		
DefaultScheduleEvent<?> event = DefaultScheduleEvent.builder()
    .title("Birthday Party")
    .startDate(today1Pm())
    .endDate(today6Pm())
    .description("Aragon")
    .overlapAllowed(true)
    .allDay(false)
    .build();
		
model.addEvent(event);
```

I do not see Event on GUI.
Does above Event definition is wrong ?
Appreciate your help.

**Comment by melloware** [comment]
Only 1 way we can help....

Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by vitsin** [comment]
sure thing, thanks

**Comment by vitsin** [comment]
[primefaces.schedule.pom.zip](https://github.com/primefaces/primefaces/files/4956054/primefaces.schedule.pom.zip)
@melloware 
hello,
1. primefaces-test project appears w/o p:schedule, using PF v8.0, Java 11, Redhat.
2. if adding manually into project primefaces-8.0.3.jar - project returns HTTP 503.

**Comment by melloware** [comment]
OK good news @vitsin 

1. Your issue is a duplicate of https://github.com/primefaces/primefaces/issues/6157

2. Its fixed for 9.0 and hopefully for 8.0.4.

3. Attached I tweaked your reproducer to make it work for you right now by hiding a p:button on the page.  Try this:
[pf-6156.zip](https://github.com/primefaces/primefaces/files/4959704/pf-6156.zip)

**Comment by vitsin** [comment]
@melloware , 
would love to have v8.0.4, thanks.

**Comment by melloware** [comment]
@vitsin this will be in 8.0.4 elite
