### ISSUE TITLE
Schedule: component javascript error

### ISSUE THREAD

**Issue by christophih** [primefaces/primefaces#6157]
The component lacks the resource dependendy to jquery (@ResourceDependency(library = "primefaces", name = "jquery/jquery.js") ).
On page, where the p:schedule is the only component, a javascript error occurs.

**Environment:**
 - PF Version: 8.0.3
 - JSF + version: MyFaces 2.3.6
 - Affected browsers: ALL

**To Reproduce**
1. Use the p:schedule component as the only component on a page. Javascript error $ is not defined occurs.

**Expected behavior**
The component must define the @ResourceDependency(library = "primefaces", name = "jquery/jquery.js")

**Comment by christophs78** [comment]
FullCalendar does not require jQuery anymore since version 4.
But or own https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js still needs jQuery. So we run into this issue.
I´ll provide a PR.

**Comment by tandraschko** [comment]
@mertsincan can you merge it to 8.0.4?
