### ISSUE TITLE
Programmatic Menu: not possible to create a dynamic expression for a boolean attribute (rendered, disabled...)

### ISSUE THREAD

**Issue by mirurita** [primefaces/primefaces#616]
Based on the following forum post (2013-09-17):
http://forum.primefaces.org/viewtopic.php?f=3&t=33906

It seems that setValueExpression method from DefaultMenuItem class was removed on PF 4.0

It is an API break, but the Migration Guide does not provide any workaround or info about how it should be migrated.
https://code.google.com/p/primefaces/wiki/MigrationGuide

Having the following disabled attribute in a menu item:

MenuItem item = new MenuItem();
ValueExpression value = factory.createValueExpression(FacesContext.getCurrentInstance().getELContext(), "#{not empty bean.myList}", Boolean.TYPE);
item.setValueExpression("disabled", value);

how could you achieve the same in PF 5?

**Comment by cagataycivici** [comment]
You can't us expression, you need to resolve the expression yourself and set disabled true or false.
