### ISSUE TITLE
Carousel: CommandButton doesn't execute action

### ISSUE THREAD

**Issue by stonewoodman** [primefaces/primefaces#6168]
**Describe the defect**
Click on a CommandButton that is embedded in a Carousel, doesn't execute the action. A post-request is called, but a breakpoint in action-method doesn't stop.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _MyFaces 2.3.6_
 - Affected browsers: _ALL_

**To Reproduce**
1. Click on 'test-btn'
2. Post-request is called
3. Method 'doAction' was not executed

**Expected behavior**
The Method 'doAction' was executed

**Example XHTML**
```html
<p:carousel effect="easeInStrong" numVisible="1" pageLinks="1" autoPlayInterval="10000">
    <p:tab>
        <p:commandButton id="test-btn" value="Test" action="#{testView.doAction}"/>
    </p:tab>
</p:carousel>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    public void doAction() {
        // do something
    }
}
```

**Comment by melloware** [comment]
Still a problem in 9.0-SNAPSHOT attached is reproducer:
[pf-6168.zip](https://github.com/primefaces/primefaces/files/4954372/pf-6168.zip)
