### ISSUE TITLE
DataTable: Lazy getRowData Repeat the query twice

### ISSUE THREAD

**Issue by eric-5512** [primefaces/primefaces#6169]
**1) Environment**

PrimeFaces version: 8.0

org.joinfaces.primefaces-spring-boot-starter  4.3.0

**2) Expected behavior**

I hope that when I select a piece of data in the datatable, getRowData is executed only once.

**3) Actual behavior**

When I select a piece of data in the datatable, getRowData is executed twice, which is very strange.

**AbstractLazyModel**

```
    public abstract class AbstractLazyModel<T> {

    private T[] selects;
    private T select;

    private LazyDataModel<T> lazyDataModel;

    protected abstract LambdaQueryWrapper<T> getQueryParam();

    protected abstract BasicService getBasicService();

    protected  abstract String getKey(T t);


    public LazyDataModel<T> getResultModel() {
        if (lazyDataModel == null) {
            lazyDataModel = new LazyDataModel<T>() {
                @Override
                public List<T> load(int first, int pageSize, Map<String, SortMeta> sortMeta, Map<String, FilterMeta> filterMeta) {
                    int currentPage = (first / pageSize) + 1;
                    Page<T> page =  new Page(currentPage,pageSize);
                    page.setOptimizeCountSql(false);
                    return getBasicService().getResultList(page,getQueryParam());
                }

                @Override
                public T getRowData(String rowKey) {
                    return   (T)getBasicService().findById(rowKey);
                }

                @Override
                public String getRowKey(T t) {
                    return getKey(t);
                }
            };
            lazyDataModel.setRowCount( getBasicService().getRowCount(getQueryParam()));
        }
        return lazyDataModel;
    }

    protected void refresh() {
        this.setSelect(null);
        search();
    }

    public void search() {
        lazyDataModel = null;
    }
```

**Example Bean**

```
@Slf4j
@Data
@Component
@ViewScoped
public class ErpSysCodeTypeView extends AbstractLazyModel<ErpSysCodeType> implements java.io.Serializable {

    @Autowired
    private ErpSysCodeTypeService erpSysCodeTypeService;


    @Autowired
    private PrimeFaces primeFaces;

    @Autowired
    private FacesContext facesContext;

    private SysCodeTypeRequest sysCodeTypeRequest;

    private String codeName;


    private List<ErpSysCodeType> sysCodeTypeList;

    private ErpSysCodeType oldErpSysCodeType;


    public void searchListener() {
        this.refresh();
    }

    public void onRowSelect(SelectEvent<ErpSysCodeType> event) {
      // this.setSelect( event.getObject());
    }




    @PreDestroy
    public void destroy() {
        log.info("ErpSysCodeTypeView destroy");
    }


    @Override
    protected LambdaQueryWrapper<ErpSysCodeType> getQueryParam() {
        return new LambdaQueryWrapper<ErpSysCodeType>().
                likeRight(!StringUtils.isEmpty(codeName),ErpSysCodeType::getName,codeName);
    }


    @Override
    protected BasicService getBasicService() {
        return erpSysCodeTypeService;
    }

    @Override
    protected String getKey(ErpSysCodeType erpSysCodeType) {
        return String.valueOf(erpSysCodeType.getId());
    }

}

```

**Example Xhtml**

```
  <p:dataTable id="dataTableId"
                                         widgetVar="sysCodeTypeTableVar"
                                         value="#{erpSysCodeTypeView.resultModel}"
                                         paginatorPosition="bottom"
                                         rowIndexVar="rowIdx"
                                         rows="10"
                                         lazy="true"
                                         selection="#{erpSysCodeTypeView.select}"
                                         selectionMode="single"
                                         rowKey="#{_sysCodeType.id}"
                                         var="_sysCodeType"
                                         emptyMessage="暂无数据."
                                         paginator="true"
                                         currentPageReportTemplate="查询到{totalRecords}条记录，本页显示{startRecord}～{endRecord}；第{currentPage}/{totalPages}页"
                                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                         rowsPerPageTemplate="5,10,15">

                                <p:ajax event="rowSelect"  listener="#{erpSysCodeTypeView.onRowSelect}" process="@this"/>

                                <p:column width="50">
                                    <f:facet name="header">序号</f:facet>
                                    <h:outputText value="#{rowIdx + 1}"/>
                                </p:column>

                                <p:column headerText="字典代码">
                                    <h:outputText value="#{_sysCodeType.code}"/>
                                </p:column>

                                <p:column headerText="字典名称">
                                    <h:outputText value="#{_sysCodeType.name}"/>
                                </p:column>

                                <p:column headerText="启用">
                                    <h:outputText value="#{_sysCodeType.status == 1 ? '启用':'关闭'}"/>
                                </p:column>

                                <p:column headerText="创建时间">
                                    <h:outputText value="#{_sysCodeType.createDate}">
                                        <f:convertDateTime pattern="yyyy-MM-dd HH::mm:ss"/>
                                    </h:outputText>
                                </p:column>

                            </p:dataTable>

```

**Comment by tandraschko** [comment]
Please provide all infos like requested in our template.

**Comment by eric-5512** [comment]
Hi,@tandraschko  

I have already provided information about the problem. What information is needed? Code?

**Comment by tandraschko** [comment]
Please read our template:




**Describe the defect**
A clear and concise description of what the defect is.

**Reproducer**
Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your reproducer here. **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub. Please test with that before reporting a bug that may already be fixed.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.8 or MyFaces 2.3.6_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Example XHTML**
```html
<h:form id="frmTest">
  ..
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

}
```

**Comment by eric-5512** [comment]
Hi @tandraschko 

I updated the content again.

**Comment by tandraschko** [comment]
thanks, its better now.
But we need a sample view + controller, so we can run it via our primefaces-test project, which doesnt have e.g. SysCodeTypeRequest

**Comment by eric-5512** [comment]
Hi @tandraschko 
**SysCodeTypeReques**t Does not use garbage code

**Comment by tandraschko** [comment]
to replicate your issue, we need to RUN your testcode. Please provide a runnable xhtml and bean without dependencies (like SysCodeTypeRequest) or fork primefaces-test for us.
Otherwise we cant replicate your case and cant help you.

**Comment by eric-5512** [comment]
OK ,I understand, I prepare a test after get off work, thank you @tandraschko

**Comment by eric-5512** [comment]
Hi @tandraschko  

my Project

[testPro.zip](https://github.com/primefaces/primefaces/files/4959514/testPro.zip)

run , url http://localhost:8080/test.xhtml

You will find that every time you choose, print twice in the console.

**Comment by melloware** [comment]
@tandraschko isn't this invalid because of the following:

From your Performance doc here: https://primefaces.github.io/primefaces/8_0/#/core/performance?id=patterns

_"Try to avoid logic in getters because they can be called multiple times - especially for the rendered attribute!"_

**Comment by tandraschko** [comment]
getRowData isnt a normal getter, it likely executes a query

**Comment by melloware** [comment]
@eric-5512 I tried `mvn spring-boot:run` but your project is not runnable.  This does not look like a valid JoinFaces runnable project?

**Comment by melloware** [comment]
OK I was able to use the Showcase and `Thread.currentThread().dumpStack();` to see where it is being called twice.

**First: SelectionFeature.decodeSingleSelection(SelectionFeature.java:81)**
```

        at org.primefaces.component.datatable.DataTable.getRowData(DataTable.java:819)
        at org.primefaces.component.datatable.feature.SelectionFeature.decodeSingleSelection(SelectionFeature.java:81)
        at org.primefaces.component.datatable.feature.SelectionFeature.decode(SelectionFeature.java:59)
        at org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:72)
```

**Second: .DataTable.queueEvent(DataTable.java:344)**
```
       at org.primefaces.component.datatable.DataTable.getRowData(DataTable.java:819)
        at org.primefaces.component.datatable.DataTable.queueEvent(DataTable.java:344)
        at org.primefaces.behavior.ajax.AjaxBehaviorRenderer.decode(AjaxBehaviorRenderer.java:55)
        at javax.faces.component.behavior.ClientBehaviorBase.decode(ClientBehaviorBase.java:110)
        at org.primefaces.util.ComponentUtils.decodeBehaviors(ComponentUtils.java:212)
        at org.primefaces.renderkit.CoreRenderer.decodeBehaviors(CoreRenderer.java:594)
        at org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:76)

```

**Comment by tandraschko** [comment]
ok so it only happens twice in the selection request but otherwise not?

**Comment by melloware** [comment]
So far that is what I am seeing.  But I definitely didn't test every case just the specific one above.

**Comment by eric-5512** [comment]
@melloware 

Can it run? So, how should this problem be solved?

**Comment by melloware** [comment]
This problem requires a code change.

**Comment by eric-5512** [comment]
Ok,Thx @melloware

**Comment by melloware** [comment]
@eric-5512 Couldn't you do something like this?
```java
if (lazyDataModel == null) {
    lazyDataModel = new LazyDataModel < T > () {
        private T lastSelected = null;
        private String lastRowKey = null;

        @Override
        public List < T > load(int first, int pageSize, Map < String, SortMeta > sortMeta, Map < String, FilterMeta > filterMeta) {
            int currentPage = (first / pageSize) + 1;
            Page < T > page = new Page(currentPage, pageSize);
            page.setOptimizeCountSql(false);
            return getBasicService().getResultList(page, getQueryParam());
        }

        @Override
        public T getRowData(String rowKey) {
            if (lastRowKey.equals(rowKey)) {
                return lastSelected;
            } else {
                lastRowKey = rowKey;
                lastSelected = (T) getBasicService().findById(rowKey);
                return lastSelected;
            }
        }

        @Override
        public String getRowKey(T t) {
            return getKey(t);
        }
    };
    lazyDataModel.setRowCount(getBasicService().getRowCount(getQueryParam()));
}
```

**Comment by melloware** [comment]
@eric-5512 did you get a chance to try my suggestion?

**Comment by eric-5512** [comment]
@melloware 

I'm sorry I have been sick recently.

**Comment by eric-5512** [comment]
> @eric-5512 Couldn't you do something like this?
> 
> ```java
> if (lazyDataModel == null) {
>     lazyDataModel = new LazyDataModel < T > () {
>         private T lastSelected = null;
>         private String lastRowKey = null;
> 
>         @Override
>         public List < T > load(int first, int pageSize, Map < String, SortMeta > sortMeta, Map < String, FilterMeta > filterMeta) {
>             int currentPage = (first / pageSize) + 1;
>             Page < T > page = new Page(currentPage, pageSize);
>             page.setOptimizeCountSql(false);
>             return getBasicService().getResultList(page, getQueryParam());
>         }
> 
>         @Override
>         public T getRowData(String rowKey) {
>             if (lastRowKey.equals(rowKey)) {
>                 return lastSelected;
>             } else {
>                 lastRowKey = rowKey;
>                 lastSelected = (T) getBasicService().findById(rowKey);
>                 return lastSelected;
>             }
>         }
> 
>         @Override
>         public String getRowKey(T t) {
>             return getKey(t);
>         }
>     };
>     lazyDataModel.setRowCount(getBasicService().getRowCount(getQueryParam()));
> }
> ```
@melloware 
No problem, it's all right. But it's strange. Thank you.

**Comment by melloware** [comment]
Thanks for testing.

**Comment by melloware** [comment]
@tandraschko since my workaround above is not hard to implement i am wondering if we should close this ticket only because in all the features and different components of datatable they all call `getRowData` so I think it would be a difficult and buggy refactoring to try and fix this in the component.  Thoughts?

**Comment by Rapster** [comment]
I submitted a PR for this, @eric-5512 you can have a try with your original code to see if it works

**Comment by melloware** [comment]
I personally vote for closing this ticket as a workaround has been provided and as @Rapster researched there is no simple or straightforward way of preventing this at the moment.

**Comment by Rapster** [comment]
@eric-5512  As a workaround, you can always implement a cache just like the one in the PR I made (as long your lazy model is at least viewscoped)

**Comment by melloware** [comment]
Going to close since valid workaround provided and no simple coding solution can fix this.

**Comment by Rapster** [comment]
I might have a solution for this
