### ISSUE TITLE
DatePicker: YearRange and default pattern

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6170]
**Describe the defect**
Forum Post: https://forum.primefaces.org/viewtopic.php?f=3&t=62741

**Reproducer**
[pf-datepicker.zip](https://github.com/primefaces/primefaces/files/4959959/pf-datepicker.zip)

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Try and pick a year before 2020 and it won't work.

**Expected behavior**
I should be able to pick a year between 1920 and 2020.  However if you manually set `pattern="dd/MM/yyyy"` it works.

**Example XHTML**
```html
<h:form id="frmTest">
            <p:datePicker id="dob" 
                          value="#{testView.dob}" 
                          inline="true" 
                          yearNavigator="true" 
                          monthNavigator="true" 
                          yearRange="1920:2020" 
                          required="true" 
                          requiredMessage="Required" 
                          maxdate="#{testView.maxDate}" 
                          mindate="#{testView.minDate}" />
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    
	@Past
    private LocalDate dob;
    private LocalDate minDate;
    private LocalDate maxDate;
    
    @PostConstruct  
    public void init() {
       minDate = LocalDate.of(1920, 1, 1);
	   maxDate = LocalDate.now();
    }

    public LocalDate getDob() {
        return dob;
    }

    public void setDob(LocalDate dob) {
        this.dob = dob;
    }

    public LocalDate getMinDate() {
        return minDate;
    }

    public void setMinDate(LocalDate minDate) {
        this.minDate = minDate;
    }

    public LocalDate getMaxDate() {
        return maxDate;
    }

    public void setMaxDate(LocalDate maxDate) {
        this.maxDate = maxDate;
    }    
}
```

**Comment by tony-in-nz** [comment]
Sorry Melloware this slipped through the net.
I was supposed to raise this.
https://forum.primefaces.org/viewtopic.php?f=3&t=62741&e=1&view=unread#unread

The default is YY not YYYY and that led to some real confusion for me (like this ticket).

When your expecting the date to be YYYY as default, then the errors you get back when you don't supply the pattern is very very confusing.

i.e. I had a @Past on the bean and was getting "Data has to be in past" when selecting 1980..... the only way I figured this all out was that after 1/1/2000 the @Past worked; but before 12/12/1999 I got a "Data has to be in past"... this took a long time to figure out.

**Comment by tony-in-nz** [comment]
Fix #6170: Locale default pattern should be 4 digit year #6172
this should fix it...

**Comment by melloware** [comment]
No problem thanks for checking in!   The fix I tested locally with the test case and all the unit tests and it definitely fixes it.  I agree I don't think a 2 digit year is ever a good default for cases exactly like this.

**Comment by tony-in-nz** [comment]
Thx man.
I love primefaces... and do use the Themes (even though it takes a lot of ferkeling to get the topbar going with your own login etc)
https://forum.primefaces.org/viewtopic.php?f=68&t=57858

Also just wondered how the Quarkus integration is going (non native as JSF native is just too hard I believe!).
Keen to see a Primefaces demo working with Quarkus.
Quarkus is being pushed hard (especially by the cloud people) and as its pure Jee (dont tell people) then it should work, non native, with JSF...

**Comment by melloware** [comment]
If you want to see how Quarkus is going check this project out: https://github.com/rmpestano/quarkus-omnifaces

Its a sample runnable using Quarkus, Omnifaces, and Primefaces.

**Comment by tony-in-nz** [comment]
Thx...
Your the man...
https://www.youtube.com/watch?v=t7Y0I91rubg
