### ISSUE TITLE
TreeTable: Filter CustomTreeNodes

### ISSUE THREAD

**Issue by biesalsk** [primefaces/primefaces#6173]
**Description**
Type of TreeNodes will be lost after filtering TreeTable. The problem is probably caused by 

`TreeTableRenderer.createNewNode(TreeNode node, TreeNode parent); `

This method will always return DefaultTreeNode or CheckboxTreeNode, even if the Type of parameter _node_ is CustomTreeNode. Because this method is called due filtering (TreeTableRenderer.filter(...)), the type of all nodes will be lost. 

**Environment:**
 - PF Version: 8.0
 - JSF:  Mojarra 2.3.9

**Expected behavior**
createNewNode should return a node with the same type as node in parameter, so that nodes in TreeTable are the same type after filtering as before. 

```java
CustomTreeNode node = new CustomTreeNode(...);
TreeNode newNode = createNewNode(node, null) ;
if(newNode instanceof CustomTreeNode){
   //correct
}else{
   //incorrect
}
```

**Possible solutions**
* handle filtering without creating new nodes
* copy node via reflection

**Comment by Rapster** [comment]
I recently came across that problem. I'll provide a PR

**Comment by melloware** [comment]
Thanks Rapster!

**Comment by biesalsk** [comment]
Thanks for the quick response!
Previous commits will work, as long as CustomTreeNode has no members. 
Probably a copy constuctor in DefaultTreeNode will help here. This way it is possible to override and take care of current state.

**Comment by melloware** [comment]
@biesalsk do you want to elaborate your suggestion or make it in @Rapster's PR?

**Comment by Rapster** [comment]
Though you have a good point, why the nodes are being created all over again? Only a new tree structure should be created when filtered/sorted. Not sure how easy it is to rework this

**Comment by biesalsk** [comment]
Rebuilding the structure of tree should be made possible by updating childs.... 
so in createFilterNodeFromRowKeys(...) you could remember childs of this node, clear them and add them again after checking filter

Here is a snipped of what I'm thinking about... not sure if it works
```java
    private void createFilteredNodeFromRowKeys(TreeTable tt, TreeNode node, List<String> filteredRowKeys) {
        int childCount = node.getChildCount();
        List<TreeNode> children = new ArrayList(node.getChildren()); //remember current children
        node.getChildren().clear(); //clear them
        for (int i = 0; i < childCount; i++) {
            TreeNode childNode = children.get(i);
            String rowKeyOfChildNode = childNode.getRowKey();

            for (String rk : filteredRowKeys) {
                if (rk.equals(rowKeyOfChildNode) || rk.startsWith(rowKeyOfChildNode + "_") || rowKeyOfChildNode.startsWith(rk + "_")) {
                    if (rk.startsWith(rowKeyOfChildNode + "_")) {
                        childNode.setExpanded(true);
                    }
                    node.getChildren().add(childNode); //add child again if it should be visible
                    createFilteredNodeFromRowKeys(tt, childNode, filteredRowKeys);
                    break;
                }
            }
        }
    }
```

**Comment by melloware** [comment]
@biesalsk Do you wanna give your suggestion a try and if it works submit a PR?

**Comment by melloware** [comment]
I think we should merge @Rapster PR as is as it fixes the original problem.  We can open a new ticket if we decide we want to optimize the method further.  Thoughts?

**Comment by tandraschko** [comment]
@biesalsk what is your usecase here?

**Comment by tandraschko** [comment]
i will commit something now which doesnt break existing apps. We may even define a attribute "cloneOnFilter" because it might hurt performance and i currently dont have a case where the filteredValue needs to be a custom node.

**Comment by biesalsk** [comment]
We created a CustomTreeNode which triggers a background process if the node expands. It is necessarry to hold the received state within the TreeNode. On filter, all TreeNodes gets recreated and we're loosing all states.

The original problem was, that we need to enable lazy loading of data from external systems for TreeTables.

**Comment by tandraschko** [comment]
I see. Please test again - you need to set cloneOnFilter=true now

**Comment by biesalsk** [comment]
> i will commit something now which doesnt break existing apps. We may even define a attribute "cloneOnFilter" because it might hurt performance and i currently dont have a case where the filteredValue needs to be a custom node.

In my oppinion, there is no reason to recreate each TreeNode while filtering regardless of which implementation for TreeNode is used.

**Comment by tandraschko** [comment]
Yeah, but thats the current impl. A improvement for the future would be to add a "filtered" flag to the TreeNode and not render again based on this decision.
