### ISSUE TITLE
DatePicker: inline=true add style class 'ui-state-error' to when validation has failed

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6178]
This will allowing users to create a CSS rule for `body .ui-datepicker-inline.ui-state-error`, or even adding it to themes.

**Comment by melloware** [comment]
@jepsar can you also check what happens when using `inline=true` and `disabled=true`???  I wonder if the inline also doesn't display disabled?  It will help me determine the right way to fix this...

**Comment by melloware** [comment]
Please review the PR if you don't mind
