### ISSUE TITLE
CSV: add ability to execute complex validation

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6182]
like: when checkbox a is selected, input must be required

**Comment by tandraschko** [comment]
i think about something like:

```xml
<div data-p-val="mycompany.customvalidator1">
....
</div>
```

```js
    PrimeFaces.validator['mycompany.customvalidator1'] = {

    }
```

which recevies the whole container instead of a single input as normally `data-p-val` is only applied on inputs.

So `PrimeFaces.validate` which search for *:not(:input)[data-p-val] after all inputs are processed.

**Comment by tandraschko** [comment]
@melloware any thoughts?

**Comment by melloware** [comment]
I like it!

**Comment by tandraschko** [comment]
the code probably needs a big refactoring

**Comment by melloware** [comment]
Looks good so far and I just comitted line ending fix for 2 files.   Yeah taking a step back it can probably use a refactoring but I agree with you i always like to get code working first then refactor.

**Comment by tandraschko** [comment]
refactored some structure/packages
probably JSDoc fails
i'm 4 days in holiday now, so if someone would like to fix JSdocs... :)

**Comment by melloware** [comment]
I will fix the JSDOC.  Enjoy your holiday!

**Comment by melloware** [comment]
JsDoc fixed!

**Comment by tandraschko** [comment]
implemented the functionality
documentation still missing + we need to understand what vi/validateInstant is
