### ISSUE TITLE
DataTable: Onfocus event fired three times with cellEdit/rowEdit

### ISSUE THREAD

**Issue by mikeante81** [primefaces/primefaces#6187]
**Describe the defect**
onfocus fired three times on inputtext with cellEdit DataTable

**Environment:**

- PF Version: 8.0
- JSF + version: 2.2.12-jbossorg-2
- Affected browsers: ALL

**To Reproduce**
2. Click on cell Year
3. Show browser console 
4. See same log three times for focus

**Example XHTML**
```html
        <p:column headerText="Year">
            <p:cellEditor>
                <f:facet name="output"><h:outputText value="#{car.year}" /></f:facet>
                <f:facet name="input"><p:inputText value="#{car.year}" style="width:96%" label="Year" onfocus="console.log('focus row'+#{index})"/></f:facet>
            </p:cellEditor>
        </p:column>
```

**Comment by melloware** [comment]
any debugging or PR would be appreciated.

**Comment by mikeante81** [comment]
I also have the problem with your demo, I only added onfocus with console.log

**Comment by melloware** [comment]
Yep not disputing the problem, asking if you have debugged into the cause etc.

**Comment by melloware** [comment]
I can see 3 focus events are registered to the input thus that is why 3 are being called.
![image](https://user-images.githubusercontent.com/4399574/89195047-2dd4cf00-d576-11ea-8019-8a5d596e9fc8.png)

Trying to figure out how to handle this.

**Comment by mirmalag** [comment]
Same problem here, causing some serious headaches, difficult to work-around

**Comment by mirmalag** [comment]
Any news about it?

**Comment by melloware** [comment]
I didn't spend too much time on it but I did not find the root cause yet.

**Comment by mirmalag** [comment]
I understand is not so easy to dig out.
Anyway, thank you for notifying me.
Hope to hear from you again soon.

Best regards,
Mirco

Mirco Malaguti

mirco.malaguti@ingeniaonline.it

**Comment by melloware** [comment]
Can any or all of you try this.  Add this to your javascript file that loads after PF.  And let me know if it fixes your issue?
```javascript
PrimeFaces.widget.DataTable.prototype.showRowEditors = function(row) {
    row.addClass('ui-state-highlight ui-row-editing').children('td.ui-editable-column').each(function() {
        var column = $(this);

        column.find('.ui-cell-editor-output').hide();
        column.find('.ui-cell-editor-input').show();
    });

    var inputs = row.find(':input:enabled');
    if (inputs.length > 0) {
        inputs.first().triggerHandler('focus');
    }
};
```

**Comment by melloware** [comment]
Any Input from this fix @mikeante81 @mirmalag @dieuph ???

**Comment by mirmalag** [comment]
Hi there,
office is closed for summer holidays.
I’ll test it as soon as I can and give feedback.

Thank you to get on it,
Mirco

**Comment by mikeante81** [comment]
Hi, the fix doesn't solve the issue.

**Comment by melloware** [comment]
@mikeante81 Here is a reproducer:
[pf-6187.zip](https://github.com/primefaces/primefaces/files/5150790/pf-6187.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml.  You will see when you edit a row only 1 console output not 3 times for `console.log('Cell Edit Focus');`   Can you check you have your setup exactly like mine.  The JS override is in the file test.js.

**Comment by melloware** [comment]
ping @mikeante81 ???

**Comment by melloware** [comment]
@mirmalag Are you back from holiday to test this?

**Comment by mikeante81** [comment]
@melloware sorry for the delay in replying, I tried the patch, but it doesn't seem to work. Maybe because the function you sent me refers to rowEdit and not cellEdit?
thanks

**Comment by melloware** [comment]
Please try this reproducer: https://github.com/primefaces/primefaces/files/5150790/pf-6187.zip

it's your scenario EXACTLY....

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml. You will see when you edit a row only 1 console output not 3 times for console.log('Cell Edit Focus'); Can you check you have your setup exactly like mine. The JS override is in the file test.js.

**Comment by mikeante81** [comment]
@melloware Maybe I haven't explained myself well, the problem I find on cellEdit with datatable attribute editMode = "cell"

**Comment by melloware** [comment]
OK it was broken for both row editing and cell editing. I was only looking at row editing.

try this one:
[pf-6187-cell.zip](https://github.com/primefaces/primefaces/files/5262169/pf-6187-cell.zip)

```javascript
PrimeFaces.widget.DataTable.prototype.showCurrentCell = function(cell) {
        var $this = this;

        if(this.currentCell) {
            if(this.cfg.saveOnCellBlur)
                this.saveCell(this.currentCell);
            else if(!this.currentCell.is(cell))
                this.doCellEditCancelRequest(this.currentCell);
        }

        if(cell && cell.length) {
            this.currentCell = cell;

            var cellEditor = cell.children('div.ui-cell-editor'),
            displayContainer = cellEditor.children('div.ui-cell-editor-output'),
            inputContainer = cellEditor.children('div.ui-cell-editor-input'),
            inputs = inputContainer.find(':input:enabled'),
            multi = inputs.length > 1;

            cell.addClass('ui-state-highlight ui-cell-editing');
            displayContainer.hide();
            inputContainer.show();
            var input = inputs.eq(0);
            input.triggerHandler('focus');
            input.triggerHandler('select');

            //metadata
            if(multi) {
                var oldValues = [];
                for(var i = 0; i < inputs.length; i++) {
                    var input = inputs.eq(i);

                    if(input.is(':checkbox')) {
                        oldValues.push(input.val() + "_" + input.is(':checked'));
                    }
                    else {
                        oldValues.push(input.val());
                    }
                }

                cell.data('multi-edit', true);
                cell.data('old-value', oldValues);
            }
            else {
                cell.data('multi-edit', false);
                cell.data('old-value', inputs.eq(0).val());
            }

            //bind events on demand
            if(!cell.data('edit-events-bound')) {
                cell.data('edit-events-bound', true);

                inputs.on('keydown.datatable-cell', function(e) {
                        var keyCode = $.ui.keyCode,
                        shiftKey = e.shiftKey,
                        key = e.which,
                        input = $(this);

                        if(key === keyCode.ENTER) {
                            $this.saveCell(cell);
                            $this.currentCell = null;

                            e.preventDefault();
                        }
                        else if(key === keyCode.TAB) {
                            if(multi) {
                                var focusIndex = shiftKey ? input.index() - 1 : input.index() + 1;

                                if(focusIndex < 0 || (focusIndex === inputs.length) || input.parent().hasClass('ui-inputnumber') || input.parent().hasClass('ui-helper-hidden-accessible')) {
                                    $this.tabCell(cell, !shiftKey);
                                } else {
                                    inputs.eq(focusIndex).trigger('focus');
                                }
                            }
                            else {
                                $this.tabCell(cell, !shiftKey);
                            }

                            e.preventDefault();
                        }
                        else if(key === keyCode.ESCAPE) {
                            $this.doCellEditCancelRequest(cell);
                            e.preventDefault();
                        }
                    })
                    .on('focus.datatable-cell click.datatable-cell', function(e) {
                        $this.currentCell = cell;
                    });
            }
        }
        else {
            this.currentCell = null;
        }
    };
```

**Comment by melloware** [comment]
This causes a regression.  reopening.

**Comment by melloware** [comment]
After reverting this fix I think the only way you can handle this is in  your `onfocus` event you will have to call `e.preventDefault()` or `e.stopPropagation()` to prevent this event from bubbling up.
