### ISSUE TITLE
Datatable Header is not lining up when using scrollable

### ISSUE THREAD

**Issue by MALPI** [primefaces/primefaces#619]
As soon as I set scrollable = true, the datatable header columns aren't aligned well.

See Screenshot:

![unbenannt](https://cloud.githubusercontent.com/assets/1839910/9179003/01baaaec-3f9a-11e5-9e59-c573e0654190.png)

**Comment by kukel** [comment]
Cannot reproduce: http://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml. Create an mcve, most likely somewhere during the creation of the mcve, you'l  see the alignment becoming correct

**Comment by cagataycivici** [comment]
Can't replicate
