### ISSUE TITLE
SplitButton: Both action button and action item are executed

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#6192]
**Describe the defect**
The core refactoring of @Rapster (#5009) introduced a bug to `p:splitbutton` and maybe to other components (did not check it).
Before the code changes the logic of [`super.decode()`](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java#L61) was inside an if block and the code below was inside an else-if block ([see here](https://github.com/primefaces/primefaces/blob/b4b33923cac78331d6a372f72784bb5b826b5bf7/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java#L83)).

That means, that both action listeners will be executed. The one of the menu item in `super.decode()` and the one from the standalone if block. But only the one of the menu item should be executed if a menu item was clicked.

This seems to happen only to a splitbutton that uses the `model` attribute.

**Reproducer**
https://github.com/fanste/primefaces-test/tree/test-6192

**Environment:**
 - PF Version: 8.0
 - JSF + version: Mojarra 2.1.19
 - Affected browsers: ALL

**To Reproduce**
1. Go to 'index.jsf'
2. Click on 'ALL'
3. Only the ALL action listener is executed
4. Click on any menu item of the split button
3. Action listener of ALL and menu item is executed

**Expected behavior**
_Already explained in the defect description_

**Comment by melloware** [comment]
@fanste Do you have a proposed PR for us to review?

**Comment by fanste** [comment]
While writing the reproducer I recognized, that only a `p:splitbutton` with the `model` attribute is affected by the bug. Before that I thought the simpliest would be to let `super.decode()` return `true/false` if a menu item was (not) processed. But now I will debug it first more deeply.

**Comment by fanste** [comment]
That was a short debug session :D

Static `p:menuItem` will be handled by UIMenuItem itself while the dynamic one will be handled by the SplitButton. The proposed fix should be the correct way.

Let `MenuItemAwareRenderer#decode` return `true/false` and `SplitButtonRenderer#decode` should handle that return value.

**Comment by fanste** [comment]
Well forget that proposed fix.. Its an overwritten method from JSF... Another solution would be to extract the code form `MenuItemAwareRenderer#decode` to a new method which allows a return value. `MenuItemAwareRenderer#decode` will then forward to that new method and simply ignore the return value while 

-  `SplitButtonRenderer#decode` uses the new method 
- OR `SplitButtonRenderer#decode` will be removed and the new method in `MenuItemAwareRenderer`  is overwritten and used.

What do you think?

**Comment by melloware** [comment]
@Rapster thoughts?

**Comment by Rapster** [comment]
Indeed, removing that else instruction has a side effect. Though, the problem might be from onclick function.

With model: `PrimeFaces.ab({s:"j_idt5:j_idt7",f:"j_idt5",g:false,pa:[{name:"j_idt5:j_idt7_menuid",value:"1"}]});return false;`
Static items: `PrimeFaces.ab({s:"j_idt5:j_idt11",f:"j_idt5"});return false;`

Trying to undersand that part

**Comment by Rapster** [comment]
I made a PR

**Comment by fanste** [comment]
Thanks for the PR. I can confirm, that everything is working now.
