### ISSUE TITLE
Calendar: readonlyInput="true" mask="true" breaks submit

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#6198]
**Describe the defect**
After submiting the calendar input and clicking the second button the bean class is not called.

**Reproducer**
https://github.com/erickdeoliveiraleal/primefaces-test/tree/viewparam

**Environment:**
 - PF Version: _9.0-SNAPSHOT_

**To Reproduce**
1. Choose date
2. Click first button
3. Click second button

**Expected behavior**
backing bean should be called

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>


	<h:form id="frmTest">
		<p:calendar id="data" pattern="dd/MM/yyyy" mask="true"
			value="#{testView.data}" readonlyInput="true" />
		<p:commandButton value="1st button" update="@form"
			process="@this data" action="#{testView.test()}" />
		<p:commandButton actionListener="#{testView.test()}" ajax="false"
			value="2nd button" />
	</h:form>

</h:body>
</html>
```

**Example Bean**
```java
import java.io.Serializable;
import java.util.Date;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestView implements Serializable {
	Date data ;

	public void test() {
		System.out.println(1);
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
```

**Comment by melloware** [comment]
I could be wrong but isn't this proper behavior of the HTML spec?  If a form value is readonly a Form Submit will not send the value to the server.  

So I guess you are saying you want the AJAX behavior to also not send the value even if process="@this" ??

**Comment by melloware** [comment]
OK I see what you are saying this works in 8.0 and does not work in 9.0.
