### ISSUE TITLE
GMap: Destination attribute

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#62]
GMap component should have "destination" attribute to enable google.maps.DirectionsService.

If destination is not null, DirectionsService is used to visualize a route from "center" to "destination".

**Comment by JDetwiler15** [comment]
Seeing that this hasn't had any activity for 4 years, I'm guessing it won't picked up any time soon. However, I too would like to see gmap support directions.

**Comment by tandraschko** [comment]
Then feel free to work on it and provide a PR. Otherwise sponsor it via PrimeFaces PRO

**Comment by melloware** [comment]
Going to close this as not planned.  PrimeTek has stopped supporting GMap in other 3 libs but we have decided to keep it here in JSF as its useful and it was discussed on Discord.
