### ISSUE TITLE
Dialog: Add "cache" attribute

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6211]
TabView has the attributes dynamic and cache. With the combination of dynamic=true and cache=false you can ensure the content of a tab is reloaded when you switch to the tab.

Dialog currenty only has dynamic-attribute. When you look at https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml (first example) you see this currently requires a work-around to update the content of the dialog.

**Comment by melloware** [comment]
@christophs78 are you tackling this one?

**Comment by christophs78** [comment]
I´ll give it a try. Hope this is not that complicated...

**Comment by tandraschko** [comment]
looks good, thanks!
