### ISSUE TITLE
ChartJs: Animation attributes definition

### ISSUE THREAD

**Issue by coldhack** [primefaces/primefaces#6212]
LineChartModel doesn't present a way to enable/disable chart animation. Animation comes by default, and I could not find a way to disable it.

**Comment by melloware** [comment]
Here is the LineChart docs. https://www.chartjs.org/docs/latest/charts/line.html

Doesn't look like there is an `animation` property available?

**Comment by coldhack** [comment]
I was exactly editing the issue post referring this. The problem is that I think it should be possible define this attribute from `LineChartModel` (at least `LineChartOptions`). Don't you think?

**Comment by melloware** [comment]
You can just add this 1 line of JS to your page to disable animation.
```javascript
Chart.defaults.global.animation.duration = 0;
```

**Comment by melloware** [comment]
Agreed this should be a gloabl option in the chart options for all charts.

**Comment by coldhack** [comment]
Agree, I could do it from javascript, easily, and it would be similar to define all properties from JavaScript context. But this would be more handy if I could do it from component model too. 

Adding `Chart.defaults.global.animation.duration = 0;` would affect all charts, right? I'm trying for only one (having more than one on the same view).

**Comment by melloware** [comment]
Please review my PR.  You will be able to do this with this PR:
```java
Animation animation = new Animation();
animation.setDuration(0);
animation.setEasing("easeOutQuart");
options.setAnimation(animation);
 
lineModel.setOptions(options);
```

**Comment by coldhack** [comment]
This would be great!
