### ISSUE TITLE
DataTable: Selection; Radio-Buttons; multiple rows can be selected

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6215]
**Describe the defect**
Regression in 9.0-SNAPSHOT. Multiple rows can be selected by clicking onto the row instead of direct to the radio-button.

**Reproducer**
http://localhost:8080/showcase_war_exploded/ui/data/datatable/selection.xhtml
Example "RadioButton"
![image](https://user-images.githubusercontent.com/10461942/89832592-de873380-db5f-11ea-8246-29619b89b62c.png)

**Environment:**
 - PF Version: 8.0 works
 - PF Version: 9.0 broken
 - Browser: Chrome, FF, (new) Edge

**Comment by melloware** [comment]
@christophs78 See this ticket: https://github.com/primefaces/primefaces/issues/4468

I think that fix caused this issue. I will investigate.

**Comment by melloware** [comment]
OK please review PR and thanks for reporting!
