### ISSUE TITLE
DataTable: FilterMeta/SortMeta equals() and hashcode()

### ISSUE THREAD

**Issue by koan00** [primefaces/primefaces#6219]
**Describe the defect**
In our unit tests, we like to compare the some of the data returned by the datatable.getFilterBy(), which returns a Map of <String, FilterMeta>. For instance we setup some initial filters, do some test work, and then verify the filters match what we expect after the work is complete. In PrimeFaces 7.0, would do something like:
```

Map<String, Object> testData = new HashMap<>();
testData,put("key", "value");
assertEquals(testData, datatable.getFilters());
```

The FilterMeta class in Primefaces 8.0 does not implement the equals method. So, the map comparison will fail even if all of the values in the FilterMeta objects match.

**Reproducer**
```
		Map<String, FilterMeta> filters1 = new HashMap<>();
		filters1.put("title", new FilterMeta("title", "title001"));
		
		Map<String, FilterMeta> filters2 = new HashMap<>();
		filters2.put("title", new FilterMeta("title", "title001"));
		
		System.out.println("Equals: " + filters1.equals(filters2));
```
Result is false

**Environment:**
 - PF Version: 8.0.3

**Expected behavior**
Adding a sensible equals method to the FilterMeta class allow for successful comparison of Maps containing the objects of the FilterMeta type.

**Comment by melloware** [comment]
I agree. Will fix

**Comment by koan00** [comment]
Could this fix also be back ported to 8.0 ?

**Comment by melloware** [comment]
The best you can hope for is for @mertsincan to put it in Elite 8.0.4 but no it will not be ported to Community 8.0.  You will have to wait for Community 9.0 if you are not an Elite subscriber.

**Comment by koan00** [comment]
Yes I meant 8.0.4, thanks!
