### ISSUE TITLE
TextEditor: HTML Sanitizer runs even when configured with secure=false

### ISSUE THREAD

**Issue by koan00** [primefaces/primefaces#6221]
**Describe the defect**
We created a custom component that extends the standard PrimeFaces p:textEditor because we needed to add customization such as Quill image resize plugin support. Along with that we modify the standard quill image blot such that the IMG tag may contain HEIGHT and WIDTH attributes which quill would normally strip. This worked up through PF 7.0, but broke with 8.0. We debugged the issue down to the new HTML Sanitizer feature. We noticed if we remove the owasp jar and set secure = false it would work. If we re-introduce the owasp jar so it can be used by other standard p:textEditors in our application, the Santizer will still run even though we still have secure=false, removing our IMG height/width tags before reaching the backing bean.

**Environment:**
 - PF Version: 8.0.3
 - Mojarra 2.2.20
 - Affected browsers: ALL

**Expected behavior**
When secure=false attribute is set on p:textEditor, the HTML sanitizer should not run, even if it is available.

It appears to be a simple fix to TextEditorRenderer.decode. I will submit the PR shortly.

**Comment by melloware** [comment]
Thank you for the explanation and the PR.  This makes perfect sense.

**Comment by koan00** [comment]
I see this wasn't back-ported to the 8.0 branch and didn't make it into 8.0.4. Could it please be included into 8.0.5? @mertsincan
