### ISSUE TITLE
EL function closestWidgetVar

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6226]
Currently you have an EL method `resolveWidgetVar(String expression, UIComponent source)` to find a widget var. I would like to have a method to find the widget var relative to the current component, so go up to the root until a component which implements `Widget` is found.

I created this method in my project:
```
  public static String closestWidgetVar() {
    return Stream.iterate(Components.getCurrentComponent().getParent(),
                          c -> Objects.nonNull(c.getParent()),
                          UIComponent::getParent)
            .filter(Widget.class::isInstance)
            .findFirst()
            .map(Widget.class::cast)
            .map(Widget::resolveWidgetVar)
            .map(w -> String.format("PF('%s')", w))
            .orElse(null);
  }
```
It uses Java 9 and OmniFaces, so it needs a bit of rewriting. If you want to I can create a PR for this.

**Comment by melloware** [comment]
I would say submit the PR for review.

**Comment by tandraschko** [comment]
i would give it a other name like: closestWidgetVar

**Comment by tandraschko** [comment]
and allow to pass a component

**Comment by tandraschko** [comment]
and also introduce closestWidget, which can be reused by closestWidgetVar

**Comment by tandraschko** [comment]
Thanks for the PR!
