### ISSUE TITLE
Timeline: showCurrentTime uses default system timezone to show current time instead of clientTimeZone

### ISSUE THREAD

**Issue by BirolYildiz** [primefaces/primefaces#6227]
**Describe the defect**
If you set `showCurrentTime="true"`, the timeline shows a red, vertical line displaying the current time. Currently, it shows the current time using the system's default timezone, making the current dependent on the machine where the app is running. Effectively making this attribute useless, if your PrimeFaces app serves users from multiple timezones.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: Mojarra 2.2.8
 - Affected browsers: ALL_

**To Reproduce**
Use any `p:timeline` with `showCurrentTime="true"`
```html
<p:timeline 
  id="timeline" 
  value="#{someBean.timelineModel}" 
  showCurrentTime="true" 
  clientTimeZone="#{someBean.timezone}">
</p:timeline>
```

Have a look at to spot the issue https://github.com/primefaces/primefaces/blob/313a6298837d9c2648820aea49d3fe868f71f70f/src/main/java/org/primefaces/component/timeline/TimelineRenderer.java#L154-L156

Calling `LocalDateTime.now()` without a timezone is the issue.

**Expected behavior**
It should use `clientTimeZone` attribute of the timeline to show the current time.

**Comment by melloware** [comment]
The `clientTimezone` attribute defaults to NULL and above in your example you have not set it on the p:timeline?  I assume you mean client timezone if its not NULL?

**Comment by melloware** [comment]
Nevermind we have a function that tries to evaluate it and if its NULL we use `System.defaultZoneId();`

**Comment by BirolYildiz** [comment]
> The `clientTimezone` attribute defaults to NULL and above in your example you have not set it on the p:timeline? I assume you mean client timezone if its not NULL?

Yes, sorry. The client timezone was set. I'll edit the bug description.
