### ISSUE TITLE
DataTable: automatically detect lazy-attribute

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6230]
Does value implement LazyDataModel? Yes --> lazy=true

**Comment by tandraschko** [comment]
We cant remove the attr but Autodetect is ok as lazy can also be used with a simple list

**Comment by christophs78** [comment]
Clear. We only autodetect this if it was not set explizit.

**Comment by tandraschko** [comment]
@christophs78  can you adjust the showcase please?

**Comment by christophs78** [comment]
Yes, I will update the showcase. And we should do the same for DataView, DataGrid and DataList.

**Comment by christophs78** [comment]
Ah. :-) The modification was done for UIData. Very good.

**Comment by Rapster** [comment]
I'd like to come back on this Thomas:
> We cant remove the attr but Autodetect is ok as lazy can also be used with a simple list

I understand you can implement a lazy loading without LazyDataModel, but then why setting `DataTable#lazy` to true if you're not using LazyDataModel?

**Comment by tandraschko** [comment]
I cant remember but lazy=true is/was used to internally not just for detecting the value-type.
Maybe you can check old google issues, we removed the lazy attribute and reintroduced it in the past ;)

**Comment by Rapster** [comment]
Ok, i found the issues: 
- https://code.google.com/archive/p/primefaces/issues/2993
- https://code.google.com/archive/p/primefaces/issues/3840

Basically, DataTable#lazy was automatically detected with the value reference type which cause a few issues _(e.g Object MyController#lazyDataModel() wouldn't work)_... Swift RHino mentionned another issue with this use case:
>  if the model is null then it will fail as well so I'm looking for a better solution here.

But I tried, and works fine. Even using getValue should have worked at that time... Anyway, I think having `UIData#lazy` is still a good thing I internally, but shouldn't be used by users that much as the new impl is good. One thing for sure then, `DataTable#lazy` was used to indicate if `DataTable#value` was a `LazyDataModel` and nothing else. I just wanted to make sure of that

**Comment by christophs78** [comment]
@Rapster : I currently work on integration-tests. Especially for DataTable. (see https://github.com/primefaces-extensions/primefaces-integration-tests/pull/18)
Hope this helps at some point in the future to allow for more refactorings without introducing major regressions.
