### ISSUE TITLE
SelectCheckboxMenu: Calls Converter#getAsString with serialized string, compares string with object

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#6236]
Unless I'm doing something horribly wrong, it seems that `SelectCheckboxMenuRenderer#encodeMultipleLabel` mixes the converted string value with the actual object in at least two places.

**Reproducer**

* Clone the current showcase https://github.com/primefaces/primefaces-showcase (9.0-SNAPSHOT)
* Edit `src/main/webapp/ui/input/checkboxMenu.xhtml` and add the following xhtml
* Create a `AtLeast2ValidatorClass` with the code below
* Start the showcase, go to `/showcase/ui/input/checkboxMenu.xhtml`, select 1 theme, and press the `Update` button.
* You get an exception with the stack trace as shown below

```xml
                <h:outputLabel for="themes" value="Themes:" />
                <p:selectCheckboxMenu id="themes" value="#{selectManyView.selectedThemes}" label="Themes"
                				      multiple="true" showCheckbox="true"
               						  converter="#{themeConverter}"
                                      filter="true" filterMatchMode="startsWith" panelStyle="width:250px">
                    <f:validator validatorId="AtLeast2Validator"/>
                    <f:selectItems value="#{selectManyView.themes}" var="theme" itemLabel="#{theme.displayName}" itemValue="#{theme}" />
                </p:selectCheckboxMenu>
                <p:commandButton id="update" value="Update" process="themes" update="themes" partialSubmit="true"/>
```

```java
package org.primefaces.showcase.convert;

import java.util.Collection;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.FacesValidator;
import javax.faces.validator.Validator;
import javax.faces.validator.ValidatorException;

@FacesValidator(value = "AtLeast2Validator")
public class AtLeast2Validator implements Validator {

	@Override
	public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
		if (value instanceof Collection<?> && ((Collection) value).size() < 2) {
			throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid", "At least 2 items required."));
		}
	}
}
```

```
Aug 21, 2020 11:00:50 AM com.sun.faces.application.view.FaceletViewHandlingStrategy handleRenderException
SEVERE: Error Rendering View[/ui/input/checkboxMenu.xhtml]
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.primefaces.showcase.domain.Theme (java.lang.String is in module java.base of loader 'bootstrap'; org.primefaces.showcase.domain.Theme is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @2d36a2a6)
	at org.primefaces.showcase.convert.ThemeConverter.getAsString(ThemeConverter.java:54)
	at org.primefaces.renderkit.SelectRenderer.getOptionAsString(SelectRenderer.java:206)
	at org.primefaces.component.selectcheckboxmenu.SelectCheckboxMenuRenderer.encodeMultipleLabel(SelectCheckboxMenuRenderer.java:245)
	at org.primefaces.component.selectcheckboxmenu.SelectCheckboxMenuRenderer.encodeMarkup(SelectCheckboxMenuRenderer.java:93)
	at org.primefaces.component.selectcheckboxmenu.SelectCheckboxMenuRenderer.encodeEnd(SelectCheckboxMenuRenderer.java:64)
```

**Cause**

* [SelectCheckboxMenuRendere#L235](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java#L235) uses the `submittedValues` of the UIInput if available, which is an array of strings
* The converter in the repro above is necessary only because otherwise the `submittedValues` are reset to `null` when there are no validation errors
* So when submittedValues is not null, the Converter#getAsString is called with the submitted string value instead of the object in [SelectCheckboxMenuRenderer#245](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java#L245)
* Similarly, in [SelectCheckboxMenuRenderer#L252](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java#L252) and L258, the string value is compared against the object from the `SelectItem`. This doesn't work and results in no item being selected upon redisplay.

When I replace `p:selectCheckboxMenu` in the XHTML snippet above with `p:selectManyMenu`, it works as expected. so this is probably a bug that should be fixed.

**Comment by melloware** [comment]
@blutorange can you compare the two components and see what you think might needs fixing?

**Comment by blutorange** [comment]
I guess for starters the `submittedValues` should be passed through `FacesConverter`, but I can take a closer look during the week end.

**Comment by melloware** [comment]
much appreciated
