### ISSUE TITLE
editor with focus and tab navigation

### ISSUE THREAD

**Issue by dariorios** [primefaces/primefaces#624]
The editor is a complex component, very useful for keeping notes and  create some special documents. But it's not supporting tab navigation. It is possible to work with some accesibility features here?  http://www.web2access.org.uk/test/11/

**Comment by tandraschko** [comment]
p:editor uses cleditor under the hood which is not maintained since years. 
I would suggest to use PrimeFaces Extensions CKEditor or the new p:textEditor (which doesn't work on all browsers).
