### ISSUE TITLE
Schedule: build with release profile fails

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6246]
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [1:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 1:column 7:syntax error
        export * from '@fullcalendar/core';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [2:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 2:column 7:syntax error
        export * from '@fullcalendar/interaction';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [3:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 3:column 7:syntax error
        export * from '@fullcalendar/daygrid';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [4:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 4:column 7:syntax error
        export * from '@fullcalendar/timegrid';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [5:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 5:column 7:syntax error
        export * from '@fullcalendar/list';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [6:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 6:column 7:syntax error
        export * from '@fullcalendar/moment';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [7:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 7:column 7:syntax error
        export * from '@fullcalendar/moment-timezone';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [9:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 9:column 7:syntax error
        import allLocales from "@fullcalendar/core/locales-all"
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [11:19]: not a valid default namespace statement. Syntax is: default xml namespace = EXPRESSION;
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 11:column 19:not a valid default namespace statement. Syntax is: default xml namespace = EXPRESSION;
        export {default as interactionPlugin} from '@fullcalendar/interaction';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [12:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 12:column 7:syntax error
        export {default as dayGridPlugin} from '@fullcalendar/daygrid';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [13:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 13:column 7:syntax error
        export {default as timeGridPlugin} from '@fullcalendar/timegrid';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [14:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 14:column 7:syntax error
        export {default as listPlugin} from '@fullcalendar/list';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [15:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 15:column 7:syntax error
        export {default as momentPlugin} from '@fullcalendar/moment';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [16:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 16:column 7:syntax error
        export {default as momentTimezonePlugin} from '@fullcalendar/moment-timezone';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [18:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 18:column 7:syntax error
        export const globalLocales = {};
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [19:11]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 19:column 11:syntax error
        for (const locale of allLocales) {
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [20:40]: Invalid assignment left-hand side.
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 20:column 40:Invalid assignment left-hand side.
            globalLocales[locale.code] = locale;
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [23:7]: syntax error
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 23:column 7:syntax error
        import './main.css';
[ERROR] D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js [1:0]: Compilation produced 18 syntax errors.
[ERROR] ...D:\OpenSource Projects\primefaces\src\main\resources\META-INF\resources\primefaces\schedule\build\src\main.js:line 1:column 0:Compilation produced 18 syntax errors.

**Comment by melloware** [comment]
I will look at this one.

**Comment by melloware** [comment]
OK @tandraschko this is fixed if you want to try again.  It was picking up the build folder and the node_modules etc under schedule.  I have excluded the `build` folder and everything is working now.

**Comment by tandraschko** [comment]
works fine, thanks!
