### ISSUE TITLE
InputText: Support HTML5 events

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#6250]
**Description**
If text is pasted via the browser menu, the change in the inputtext field goes unnoticed on the server side. Even if the component is registered for 'change' Ajax events, this change will not be propagated immediately. This is especially nasty if you rely on detecting the dirty state of a form on the server side.

**Describe the solution you would like**
A working solution has already be found in the following forum post: [p:inputText start listener if a value was pasted?](https://forum.primefaces.org/posting.php?mode=edit&f=3&p=184227).

A listener should be added to the 'paste' event of the inputfield, which triggers the Ajax change event.

The solution described in the post will only work on a single component, adding this to the component itself is more desirable and add consistent behavior for the different text-based input components.

For consistency, this change should also be added to InputTextarea component as well. TextEditor seems to already cover this nicely out of the box.

**Comment by tandraschko** [comment]
not sure
change == onchange
so when onpaste doesnt trigger onchange, you should probably register a p:ajax for onpaste (which currently isnt possible probably)

**Comment by melloware** [comment]
But @tandraschko i believe Jquery `trigger('change')` triggers it no matter what if it has an onchange or AJAX change event registered. This seems like a sensible expectation of this component?
```javascript
this.jq.on("paste", function(e) {
    _self.trigger('change');
});
```

Should be a pretty harmless and effective change no?

**Comment by tandraschko** [comment]
actually not sure
onpaste is more like keyup actually, which can happen multiple times before leaving the input and trigger onchange?

**Comment by stolp** [comment]
I agree that onpaste and onchange are probably indeed two different pair of shoes,

So maybe it would be a cleaner solution to add onpaste as an additional event types to the list of supported events?

**Comment by melloware** [comment]
Since these inherit JSF HtmlInputText i would think 'paste` needs to be added to JSF Impl??

```java
private static final Collection<String> EVENT_NAMES = Collections.unmodifiableCollection(Arrays.asList("blur","change","valueChange","click","dblclick","focus","keydown","keypress","keyup","mousedown","mousemove","mouseout","mouseover","mouseup","select"));
```

**Comment by tandraschko** [comment]
Yeah; also related to: https://github.com/primefaces/primefaces/issues/1493

**Comment by melloware** [comment]
Here is a fun fact I just learned while implementing this:
`paste` fires on pasting but BEFORE the text is pasted into the input.  So for an AJAX event if you paste "hello" in the box the AJAX submits but the Input is still empty because paste fires before the text is pasted.
```xml
<p:inputText id="lastname" value="#{userView.lastname}">
          <p:ajax event="paste" update="out3" />
 </p:inputText>
```

However, to accomplish this properly the `input` event can be used and it captures basically a combination of "change, cut, copy, and paste" so it works and submits the value "hello" when pasting. _Script to be run when an element gets user input_
```xml
<p:inputText id="lastname" value="#{userView.lastname}">
          <p:ajax event="input" update="out3" />
 </p:inputText>
```

**Comment by stolp** [comment]
Thanks, this is both interesting and good news.

This really helps preventing cluttering my input fields with yet another AJAX listener.

**Comment by melloware** [comment]
Yep `input` looks like it does exactly what you want so you should be able to replace "change" with "input" when I am done to meet all your needs.

**Comment by stolp** [comment]
Hopefully it is not only *my* needs ;-)

**Comment by melloware** [comment]
Nah considering #1493 has been open for 4+ years this change is a long time coming.

**Comment by stolp** [comment]
Totally impressive. Thanks a million.

**Comment by melloware** [comment]
No problem this is a really useful addition for 9.0.
