### ISSUE TITLE
Schedule: columnHeaderFormat documentation

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primefaces#6251]
**Describe the defect**
When I specify a custom value for `columnHeaderFormat`, the locale is not honored anymore. E.g., I get **Mo, Tu, ... Su**, instead of their French equivalent **Lu, Ma, ... Di**. Note that I do get the French names when `columnHeaderFormat` is not explicitly specified.
```
<p:schedule columnHeaderFormat="timeGridWeek: 'dd'" locale="fr">
```

**Environment:**
 - PF Version: 8.0
 - JSF + version: joinfaces 4.3.0 (primefaces-spring-boot-starter, mojarra-spring-boot-starter).
 - Affected browsers: ALL

**Expected behavior**

**Comment by melloware** [comment]
I don't think your columnHeaderFormat is correct is it?
Doc: https://fullcalendar.io/docs/v4/columnHeaderFormat

**Comment by mossaab0** [comment]
> I don't think your columnHeaderFormat is correct is it?
> Doc: https://fullcalendar.io/docs/v4/columnHeaderFormat

I didn't find PF specific documentation for `columnHeaderFormat`. What I posted works as expected (i.e., it shows the first two characters of the day of the week only for the `timeGridWeek` view), except for the Locale part.

**Comment by melloware** [comment]
I just tried this and it worked `columnHeaderFormat="timeGridWeek: {weekday: 'long'}`

![image](https://user-images.githubusercontent.com/4399574/91215868-10ad9f00-e6e3-11ea-8559-f5c2d8828cbf.png)

**Comment by mossaab0** [comment]
> I just tried this and it worked `columnHeaderFormat="timeGridWeek: {weekday: 'long'}`
> 
> ![image](https://user-images.githubusercontent.com/4399574/91215868-10ad9f00-e6e3-11ea-8559-f5c2d8828cbf.png)

That helps. Thanks!

I've got the `dd` notation from https://fullcalendar.io/docs/v3/columnHeaderFormat. I see that this is an old version. It seems that `dd` is still supported (because it works on PF8.0, which loads FC v4.3.1), but undocumented? Perhaps, this is why its locale break?

**Comment by mossaab0** [comment]
This is what I get with `columnHeaderFormat="timeGridWeek: 'dd'"`:
![Untitled](https://user-images.githubusercontent.com/2341730/91217058-d528ca00-e70e-11ea-85a0-fc140f2f81c8.png)

**Comment by melloware** [comment]
Hmm that should not work according to the FullCalendar Docs.

The values for weekday are `narrow`, `short` and `long`??

Here is what `columnHeaderFormat="timeGridWeek: {weekday: 'narrow'}"` looks like...

![image](https://user-images.githubusercontent.com/4399574/91217391-6c792780-e6e5-11ea-9a0c-b8d194a03141.png)

So I am not sure where you are coming up with 'dd' as a valid value?

See: https://devhints.io/wip/intl-datetime
See: https://fullcalendar.io/docs/v4/columnHeaderFormat

**Comment by melloware** [comment]
The old FullCalendar V3 docs have the 'dd' https://fullcalendar.io/docs/v3/columnHeaderFormat but PF 8.0 uses FullCalendar 4.0 and the documentation i have provided above.

**Comment by mossaab0** [comment]
Thanks @melloware! `{weekday: 'narrow'}` is useful. I'll settle with it and close the issue. It seems that `dd` is still (unofficially?) supported in FC 4.0, which contributed to the confusion.

**Comment by melloware** [comment]
No problem. Yeah they might have left it in but I can confirm its removed fully in FullCalendar v5 which PF9.0 will use.

**Comment by mossaab0** [comment]
@melloware  Back to confusion :-)
[PF8](https://primefaces.github.io/primefaces/8_0/#/components/schedule) and [PF9 ](https://primefaces.github.io/primefaces/9_0/#/components/schedule) documentations mention:

columnHeaderFormat  | null  | String  |  Format for column headers. (eg week:'dd DD MMM' or timeGridWeek: 'DD MM', timeGridDay: 'dd')  |
|---|---|---|---|


So, `dd` is indeed (supposedly) supported.

**Comment by melloware** [comment]
Yep docs are wrong. Fullcalender v4 docs are correct.  This component just sits on top of FullCalender.

**Comment by melloware** [comment]
I have updated the PF 8.0 and 9.0 documentation.

FullCalendar V3 used to allow 'dd'as you can see here: https://fullcalendar.io/docs/v3/columnHeaderFormat

FullCalendar v4 and v5 do not and switched to use Intl.DateTimeFormat instead: https://fullcalendar.io/docs/v4/columnHeaderFormat
