### ISSUE TITLE
Calendar/DatePicker: Error with SimpleDatePattern with 1-letter year (eg. dd.MM.y) 

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#6257]
**Describe the defect**

So unless I understand the docs wrongly, the `pattern` option on <p:calendar> and <p:datePicker> allows for a [SimpleDateFormat](https://docs.oracle.com/javase/10/docs/api/java/text/SimpleDateFormat.html) pattern.

When the year portion of the pattern is  `yyyy` (full year) or `yy` (2 digits), everything works. However, when it is only `y`, it won't work (see below).

This is because the [SimpleDateFormat](https://docs.oracle.com/javase/10/docs/api/java/text/SimpleDateFormat.html) interprets `y` as:

> For formatting, if the number of pattern letters is 2, the year is truncated to 2 digits; **otherwise it is interpreted as a number**.

While the [JQueryUI datepicker](https://api.jqueryui.com/datepicker/#utility-formatDate) (and thus p:calendar and p:datepicker which uses the same algorithm) interprets `y` as 

> y - year (two digit)

So the Date gets formatted as `20 May 2020` by the server, but the client expects `20 May 20`.

Now I suppose most people would just use `yyyy`, but `y` is essentially the full year with a fall back for 2-digit year numbers.

How I even found out about this issue is because I had been using the default pattern from SimpleDataFormat.LONG. Observe how the following program gives different outputs for different Java versions:

```java
import java.text.SimpleDateFormat;
import java.util.Locale;

public class Test {
  public static void main(String[] args) {
     String s =((SimpleDateFormat)SimpleDateFormat.getDateTimeInstance(SimpleDateFormat.LONG, SimpleDateFormat.SHORT, Locale.GERMAN)).toPattern();
     System.out.println(s);
  }
}
```

With Java 14:

```bash
user@mypc:/tmp/javatest$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)
user@mypc:/tmp/javatest$ javac Test.java && java Test
d. MMMM y, HH:mm
user@mypc:/tmp/javatest$ javac Test.java && java -Djava.locale.providers=COMPAT,CLDR Test
d. MMMM yyyy HH:mm
```

With Java 8:

```bash
user@mypc:/tmp/javatest$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
user@mypc:/tmp/javatest$ javac Test.java && java Test
d. MMMM yyyy HH:mm
```

It seems like the one letter year format `y` is the default since Java 9, although that can be changed with system properties https://stackoverflow.com/a/57050058

**Reproducer**

[reproducer.zip](https://github.com/primefaces/primefaces/files/5141453/reproducer.zip)

**Environment:**
* PF Version: _9.0-SNAPSHOT_

**To Reproduce**

Click in the date input field. A date picker should show up, but instead an error message is logged in the console.

```xhtml
<p:datePicker id="timeDe" value="#{testView.testDate}" showTime="false" pattern="dd.MM.y"/>
```

![image](https://user-images.githubusercontent.com/2456413/91549372-bc8efe80-e91e-11ea-90a8-2a45e2eff2f2.png)

**Comment by melloware** [comment]
Yep this whole converting from Java to Javascript dates has been a mutliyear bug fix battle if you look through the history of Calendar tickets. :)
