### ISSUE TITLE
InputNumber description of attributes not in line with documentation

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#6260]
The description of the inputNumber attributes in https://github.com/primefaces/primefaces/blob/8.0/src/main/resources/META-INF/primefaces-p.taglib.xml is not in line with the documentation at https://primefaces.github.io/primefaces/8_0/#/components/inputnumber

Example:
emptyValue (primefaces-p.taglib.xml)

> Controls empty input display behavior, options are empty, zero, sign. Default is empty.

emptyValue (Documentation site)

> Defines what to display when the input value is empty (possible options are null, focus, press, always, min, max, zero, number, or a string representing a number)

**Environment:**
 - PF Version: _8.0_

**Expected behavior**
The description of attributes should be in line with the documentation site.

**Comment by pfumi** [comment]
Please also fix in 8.0.x release

**Comment by pfumi** [comment]
@melloware emptyValue was just an example. Can you please also adjust the following attributes (other attributes are okay I guess):

- leadingZero (is not in documentation at all)
- decimalPlaces
- maxValue
- minValue
- symbolPosition

**Comment by pfumi** [comment]
Is there any chance to get this into 8.0.4 by a PrimeTek staff member?

**Comment by melloware** [comment]
Ahh please be specific next time. I thought you were pointing out the 1 issue was wrong. Always list everything that is wrong.

**Comment by pfumi** [comment]
Sorry, next time I do for sure :)

**Comment by melloware** [comment]
Updated..
- taglig.xml to have correct descriptions
- 8.0 docs updated : https://primefaces.github.io/primefaces/8_0/#/components/inputnumber?id=inputnumber
- 9.0 docus updated:  : https://primefaces.github.io/primefaces/9_0/#/components/inputnumber?id=inputnumber

**Comment by melloware** [comment]
Note you may have to press CTRL+F5 in your browser to refresh the docs as they may be cached.
