### ISSUE TITLE
DatePicker: document AJAX Events

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6269]
Allowing you to use [disabled dates](https://primefaces.github.io/primefaces/8_0/#/components/datepicker?id=date-restriction) limited to the month(s) currently shown.

**Comment by melloware** [comment]
@jepsar I assume you mean Navigate whenever the months are moved forward or backward?  What about year?

**Comment by jepsar** [comment]
@melloware For both (so year as well). You can assign this issue it to me if want to. Or are you already working on in?

**Comment by melloware** [comment]
it looks like it already exists as `viewChange` event?
```javascript
/**
     * Triggers the event for when the date picker changed to a different month or year page.
     * @private
     * @param {number} year The year to which the date picker changed.
     * @param {number} month The year to which the date picker changed, starting with `0` for `Janurary`.
     */
    fireViewChangeEvent: function(year, month) {
        if(this.cfg.behaviors) {
            var viewChangeBehavior = this.cfg.behaviors['viewChange'];

            if(viewChangeBehavior) {
                var ext = {
                        params: [
                            {name: this.id + '_month', value: month},
                            {name: this.id + '_year', value: year}
                        ]
                };

                viewChangeBehavior.call(this, ext);
            }
        }
    },
```

**Comment by jepsar** [comment]
Thanks! I didn't look at the source yet, only the [documentation](https://primefaces.github.io/primefaces/8_0/#/components/datepicker?id=ajax-behavior-events) (which needs to be updated). I'll create a PR for that.

**Comment by melloware** [comment]
Yep I thnk we need to add a MD Table for the 3 special events `dateSelect`, `viewChange`, and `close`.  I have just updated the 9.0 docs to have all the events but it doesn't doc those 3 special ones very well.

**Comment by melloware** [comment]
Also you can cut and paste whatever you do to Calendar MD as well as it has the exact same events as DatePicker.
