### ISSUE TITLE
FileDownload: add multiple file support

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6273]
See https://github.com/primefaces-extensions/primefaces-extensions/issues/1

> - Extend `fileDownload` tag, FileDownloadTagHandler, FileDownloadActionListener, StreamedContent, DefaultStreamedContent. The main goal is to generate a zip file of many StreamedContents.
>
> - Allow to add children of type StreamedContent to the new ZipStreamedContent (extends StreamedContent). ZipStreamedContent zips all containing children of type StreamedContent.
>
> - Allow to handle byte arrays (byte[]) as content and not only InputStream.
>
> - FileDownloadActionListener should distinguish between StreamedContent and ZipStreamedContent. It should zip files and generate zipped output if "file" implements ZipStreamedContent.
>
> - FileDownloadActionListener should be able to be used in portlet environment (no direct access to reqiest object!).
>
> - Add a new attribute "responseHeader" to the tag fileDownload which accepts a single value, an array, a collection or list of string(s). Possible response headers are e.g. Cache-Control and Pragma. FileDownloadTagHandler should be extended to this attribute.
>
> - Don't forget to check in action listener if response was completed. If yes ==> return from action listener. Call facesContext.responseComplete() (s. PF's FileDownloadActionListener) is not enough because events are queued and all action listeners are called in INVOKE_APPLICATION phase until the phase finished (regardless of set flags). At the end of each phase UIViewRoot.clearFacesEvents() is called, checks set flags and clears queued events if nessesary.
>
> PF related bug http://code.google.com/p/primefaces/issues/detail?id=1656
>
> By the way, IFrame will not solve problem with ajaxified components.

**Comment by jepsar** [comment]
Won't this turn into a possible performance drain? Of course.. it's all in the hands of the user and will depend on the size of the data that needs to be processed.

**Comment by melloware** [comment]
Whenever i do this in any of my projects I just zip up the data and send a ZIP file to the download rather than multiple downloads.  Been doing that for years so never found the need for a multiple download so far.

**Comment by jepsar** [comment]
Should we refactor Ajax downloading into a static utility method? See for example https://stackoverflow.com/questions/66470751/primefaces-streamedcontents-download-by-one-button

This would allow you to download several files triggered by one request.

https://github.com/primefaces/primefaces/blob/8d9e7700e97db2aff288d6d709287fb6a5609ff0/src/main/java/org/primefaces/component/filedownload/FileDownloadActionListener.java#L83-L88

**Comment by tandraschko** [comment]
sure, create a feature request for v11

**Comment by jepsar** [comment]
Hmm, not possible to create a static method as you will need the value attribute of the action listener. Multiple files should just be offered as a zip IMO.
