### ISSUE TITLE
DatePicker: numberOfMonths > 1 should only show month + year navigator above the first month

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6274]
It could be a personal thing, but I was a bit confused by the multiple navigators, and it seems that they all affect the first month only.

I would have expected navigation above the first month, and the other months just to have heading texts for month and year.

<img width="824" alt="Screen Shot 2020-09-01 at 13 51 35" src="https://user-images.githubusercontent.com/7500178/91848797-48749380-ec5b-11ea-8943-23cbad0edb52.png">

```
<p:datePicker monthNavigator="true"
              yearNavigator="true"
              numberOfMonths="3">
```

**Comment by melloware** [comment]
I think I agree with you.  Does changing those other dropdowns affect the control in any way?

**Comment by jepsar** [comment]
They all seem to affect the first / leftmost month. I haven't looked in the code yet. I'll have a look tonight.

**Comment by melloware** [comment]
After fix:
![image](https://user-images.githubusercontent.com/4399574/91988566-6a265700-ecfd-11ea-837a-281c2c7634dc.png)
