### ISSUE TITLE
DatePicker: offer updating disabled dates and days through widgetVar

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6277]
I'm using disabled dates based on a database query. I've chosen to only fetch the available dates based on the currently visible month. I was planning to use the `viewChange` listener to fetch available dates again when the view changes. The listener is called, but the component does not (re)read the disabled dates list. I tried updating the component, but that will cause the popup to close.

I would be nice if we could use something similar to the `LazyScheduleModel` and keep the number of requests limited.

**Comment by melloware** [comment]
Why not in your `viewChange` use `oncomplete='javascript()` to update the DatePicker's internal disabledDates array.
```javascript
if (this.options.disabledDates) {
                for (var i = 0; i < this.options.disabledDates.length; i++) {
                    this.options.disabledDates[i] = this.parseOptionValue(this.options.disabledDates[i]);
                }
            }
```
That is what controls the disabled dates in the drawing of the component.  Or you could try this in the oncomplete 
```javascript
widget.jq.datePicker('_setInitValues');
```

That would reinitialize all the init values like disabledDates.

**Comment by jepsar** [comment]
I also looked for a way to it using the widget API. I'll have a look. You might need to trigger a render after setting the disabled dates. Maybe we could offer your suggestion as a function in the widget.

**Comment by melloware** [comment]
So do me a favor see if you can get it working and then we can create a widget method like `updateConfiguration` or something liek that to wrap up all the functionality for an `oncomplete`.

**Comment by jepsar** [comment]
Sure thing! I'll post what I came up with here. Not sure when though. I want to do the documentation and showcase on the file download first tonight.

**Comment by melloware** [comment]
I think the only trick will be in the `viewChange` we need to pass back the config values else the disabledDates value will still be the original widgets disabledDates since your don't want to update the component and wipe out the popup.

**Comment by jepsar** [comment]
I don't seem to get this to work. First I tried to unset the disabled dates like:

```
PF('newDate').cfg.disabledDates = null;
```

and then see if I can get the date picker panel to rerender using JS.

```
PF('newDate').jq.datePicker('_setInitValues')
jquery.js.xhtml?ln=primefaces&v=8.0:2 Uncaught Error: no such method '_setInitValues' for datePicker widget instance

PF('newDate').jq.datePicker('_setInitOptionValues')
jquery.js.xhtml?ln=primefaces&v=8.0:2 Uncaught Error: no such method '_setInitOptionValues' for datePicker widget instance

PF('newDate').jq.datePicker('updateViewDate')
datepicker.js.xhtml?ln=primefaces&v=8.0:2 Uncaught TypeError: Cannot read property 'getFullYear' of undefined
    at K.<computed>.<computed>.cfg.onViewDateChange (datepicker.js.xhtml?ln=primefaces&v=8.0:2)
    at K.<computed>.<computed>.updateViewDate (datepicker.js.xhtml?ln=primefaces&v=8.0:1)
    at K.<computed>.<computed>.updateViewDate (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at HTMLSpanElement.<anonymous> (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at Function.each (jquery.js.xhtml?ln=primefaces&v=8.0:2)
    at k.fn.init.each (jquery.js.xhtml?ln=primefaces&v=8.0:2)
    at k.fn.init.K.fn.<computed> [as datePicker] (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at <anonymous>:1:18

PF('newDate').jq.datePicker('updateViewDate', null, new Date())
// No error, no effect

PF('newDate').jq.datePicker('updateConfiguration')
jquery.js.xhtml?ln=primefaces&v=8.0:2 Uncaught Error: no such method 'updateConfiguration' for datePicker widget instance
```

**Comment by melloware** [comment]
How about trying...
```javascript
PF('newDate').jq.data().primeDatePicker._setInitValues();
```

**Comment by melloware** [comment]
OK if go here and press F12: https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml

This script worked for me:
```javascript
var datepicker = PrimeFaces.widgets.widget_form_disabledDD.jq.data().primeDatePicker;
datepicker.options.disabledDays = null;
datepicker.options.disabledDates = null;
datepicker._setInitValues();
```

**Comment by jepsar** [comment]
Thanks! I ended up doing this to get the panel rerendered:

```
var datepicker = PrimeFaces.widgets.widget_form_disabledDD.jq.data().primeDatePicker;
datepicker.options.disabledDates = null;
datepicker.panel.get(0).innerHTML = datepicker.renderPanelElements();
```

It would be cool if we could do `PF('widVar').updateDisabledDates(['9/21/2020', '9/22/2020'])`. Should I create a PR?

**Comment by melloware** [comment]
Absolutely create a PR.   Adding widgets methods like this makes the component more usable/flexible.

**Comment by jepsar** [comment]
I think this issue led to a useful addition to the widget. But still, I would like to have some kind of auto update of the date picker panel when the view changes. WDYT?

**Comment by melloware** [comment]
If you can figure it out i would create a new issue and PR.
