### ISSUE TITLE
Add JS function to get the widget instance by the clientId

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#629]
e.g.

PrimeFaces.getWidgetById('form:theDivOfMyDialog');

**Comment by tandraschko** [comment]
Done. @cagataycivici, could you please add this js helper function to our documentation?

**Comment by dmaidaniuk** [comment]
This new JS function has a bug. I already describe it here:
http://blog.hatemalimam.com/get-widgetvar-by-id/#comment-5139
Correct version of it is next:

```
getWidgetById : function(id) {

        for (var widgetVar in PrimeFaces.widgets) {
             var widget = PrimeFaces.widgets[widgetVar];
             if (widget && widget.id === id) {
                 return widget;
             }
         }

         return null;
    },
```

Otherwise it will produce sometimes JS error: `Cannot read property 'id' of null`.

**Comment by tandraschko** [comment]
Than please post a example (and a new issue) how the entry become null. This should be fixed actually.

**Comment by dmaidaniuk** [comment]
Sure, I will extract example from our application and post it as a new issue than.

**Comment by dmaidaniuk** [comment]
Posted new bug with described above `NULL` problem in `PrimeFaces.widgets`. See #715 .

**Comment by dmaidaniuk** [comment]
Is this feature included in recent release 5.3 (or 5.3.1)?

**Comment by tandraschko** [comment]
Try it ;) But should be, yes.

**Comment by kukel** [comment]
@tandraschko: then 'close' it or set a new milestone ;-)

**Comment by dmaidaniuk** [comment]
This function for sure present in PrimeFaces 5.3. Thus I agree with @kukel that this task should be closed.

**Comment by tandraschko** [comment]
Sure but i assigned it to cagatay and it's still missing in the documentation.
I will send him an email.
