### ISSUE TITLE
DataTable: evaluate removal of SelectableDataModelWrapper

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6296]
follow-up to https://github.com/primefaces/primefaces/pull/6295

originally introduced with https://github.com/primefaces/primefaces/commit/a92e580ac1d4579661653f95001690d154e20851

**Comment by melloware** [comment]
Digging through Google Code logs its seems likely that 1 of these was the original issue in 2011:

https://code.google.com/archive/p/primefaces/issues/2270 (most likely this one based on the date)

https://code.google.com/archive/p/primefaces/issues/2094

https://code.google.com/archive/p/primefaces/issues/2393 (linked from 2270)

https://code.google.com/archive/p/primefaces/issues/2272 (linked from 2270)

**Comment by Rapster** [comment]
I'm closing this for now as I'm working on #1390 and they're related
