### ISSUE TITLE
DataTable: body should be rendered before footer

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6301]
https://github.com/primefaces/primefaces/blob/cb796a4e7e0be29e715110e7fcfa6a128eddf2a8/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java#L444-L446

The main issue with this is when you have focusable elements in the body and the footer, the tab order is wrong.

I'm aware that the datatable is a complex component, so probably it will take more then just swapping the lines above. I'll have some time later this week to swap the lines and check with the showcase if all the examples still work.

**Comment by melloware** [comment]
You are right. Might want to look through commit history as to why but this does seem odd.

**Comment by melloware** [comment]
Actually looking at this I think it is just a mistake.  Here is how encode scrollable is..

```java
encodeScrollAreaStart(context, table, DataTable.SCROLLABLE_HEADER_CLASS, DataTable.SCROLLABLE_HEADER_BOX_CLASS, tableStyle, tableStyleClass);
encodeThead(context, table, 0, frozenColumns, clientId + "_frozenThead", "frozenHeader");
encodeFrozenRows(context, table, 0, frozenColumns);
encodeScrollAreaEnd(context);
encodeScrollBody(context, table, tableStyle, tableStyleClass, 0, frozenColumns, clientId + "_frozenTbody");
encodeScrollAreaStart(context, table, DataTable.SCROLLABLE_FOOTER_CLASS, DataTable.SCROLLABLE_FOOTER_BOX_CLASS, tableStyle, tableStyleClass);
encodeTFoot(context, table, 0, frozenColumns, clientId + "_frozenTfoot", "frozenFooter");
encodeScrollAreaEnd(context);
```

it has them ordered correctly.  When I order the `regularTable` method...
```java
encodeThead(context, table);
encodeTbody(context, table, false);
encodeTFoot(context, table);
```
I am running the Showcase and there are no side effects on any of the footer examples...
