### ISSUE TITLE
ROMA: 2.2.0

### ISSUE THREAD

**Issue by haramoz** [primefaces/primefaces#6302]
I downloaded the ROMA primefaces 2.2.0 skin which is based on PF 8.0.

When I follow the css generation script it gives the error like this for the all themes. 

Error: Can't find stylesheet to import.
  ╷
3 │ @import './designer/_theme';
  │         ^^^^^^^^^^^^^^^^^^^
  ╵
  ..\sass\theme\_theme.scss 3:9  @import
  theme.scss 7:9                 root stylesheet

Any idea how to fix this or where to find the missing Designer.css ??

**Comment by tandraschko** [comment]
Please use the ROMA forum. This issuetracker is only for PrimeFaces Core.

**Comment by haramoz** [comment]
ok
