### ISSUE TITLE
[perf] Reduce object instances

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6307]
Before:
223 540 ArrayList$Itr instances in 400 requests with a DataTable

After:
~70 000 ArrayList$Itr instances in 400 requests with a DataTable

**Comment by tandraschko** [comment]
@melloware would be great if you can do a short review (hopefully i dont have a i/j mismatch...)

**Comment by melloware** [comment]
Reviewed and looks great.  I like the precompiled Pattern too, that is my preferred approach.

**Comment by Rapster** [comment]
Hopefully `UIComponent#getChildren` will never return a LinkedList 😋

**Comment by tandraschko** [comment]
yeah, hopefully :D
did some other improvements, we are down to 65k now
with a newer MF 23next snapshot even under 60k

**Comment by tandraschko** [comment]
down to 12k with a MF change
223k vs 12k is a big change, i will try to get the change into tomcat EL impl

**Comment by tandraschko** [comment]
https://github.com/apache/myfaces/commit/834a79ad3fac3fb73a28beeb05828bc2c743708e
and
https://github.com/apache/tomcat/pull/355

**Comment by melloware** [comment]
Awesome work @tandraschko
