### ISSUE TITLE
AutoComplete: case insensitive autoSelection (and forceSelection)

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6310]
https://github.com/primefaces/primefaces/blob/4dff1fb6a5239ad106b43749bf5d6f09002aae86/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js#L1026-L1031

Now you have exactly input all capitals correctly. Most people will probably search in lower case.

Case insensitivity might also help with `forceSelection`.

Maybe add a `caseInsensitive` flag instead of making it default?

**Comment by melloware** [comment]
Can you follow the template and provide a use case of exactly what you are expecting?  I am confused by what this ticket is asking for?

**Comment by jepsar** [comment]
Sorry, I thought it was clear enough.

Let's say you have a list of currencies containing "Euro". Typing "euro", will find "Euro" (server side search is case insensitive), but it won't be auto selected. I would like to be able to auto select "Euro" when I search for "euro" and remove focus from the field.

I could create a branch of the showcase to show what I'm trying to do.

**Comment by melloware** [comment]
Nope I understand now.  PR coming?

If the server side does case insenstive then so should the client side.

**Comment by jepsar** [comment]
> Nope I understand now. PR coming?

Well, I would like to have a look tonight. I'm currently at my day job and cannot spend too much time on this now.

> If the server side does case insensitive then so should the client side.

True. But the component will not know what is done on the server side.

Do you think case insensitive should be the default? Or add an attribute / toggle?

**Comment by melloware** [comment]
Well if we add a "toggle" it should be respected by the client and server side.  so if you add `caseInsensitive` attribute its default should be true and both client and server should respect it.

**Comment by jepsar** [comment]
> Well if we add a "toggle" it should be respected by the client and server side. so if you add `caseInsensitive` attribute its default should be true and both client and server should respect it.

Server side is implemented by the user via the `completeMethod`. We have no control over what's happening there.

**Comment by melloware** [comment]
OK understood.

**Comment by jepsar** [comment]
Okay.. It seems I have an XY-problem. I thought I had a fix I wanted to test, but could not reproduce the issue I had in the showcase. It turned out that setting `autoHighlight="true"` helped a lot. So, I'll close this for now.
