### ISSUE TITLE
Ajax update of mobile-rendered selectOneMenu fails

### ISSUE THREAD

**Issue by mvreijn** [primefaces/primefaces#632]
As noted here at SO: http://stackoverflow.com/questions/31965296/primefaces-mobile-ajax-update-of-selectonemenu-fails

The standard example from [PF showcase](http://www.primefaces.org/showcase/ui/ajax/dropdown.xhtml) where two selectOneMenu components update eachother, fails when the mobile renderer is used. 

Tested using PF community 5.2 and 5.3 SNAPSHOT built from SVN on 17/08/2015.

**Comment by mertsincan** [comment]
Please try with 5.3.4, 5.2.17 or 6.0.
Similar issue; https://github.com/primefaces/primefaces/issues/963
