### ISSUE TITLE
Column: currently only allow % and px as width

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6321]

**Comment by tandraschko** [comment]
@melloware please do a short review :D

**Comment by melloware** [comment]
This looks great.  Only minor comment would be if the "px" and "%" were the first two checks in the OR list it would short circuit it faster because there is a high probably it is one of those two.  But probbaly not worth the microsecond performance gain :)

**Comment by tandraschko** [comment]
good hint, updated it ;D
