### ISSUE TITLE
SelectManyMenu: Editable options

### ISSUE THREAD

**Issue by ZiupeX** [primefaces/primefaces#6322]
It will be very useful when we could edit some value before we select some items from multislection list and send it to the backend bean.
 
For example I would select 3 items from set of  10 items but also edit some text inside the object. Then send it selection to the backend bean. I saw in SelectOneMenu there is something like editable attrubite which allow to edit selected value before send to serwer.

I tried with the following code:

![image](https://user-images.githubusercontent.com/45762682/93358115-63412d80-f841-11ea-950b-f27e5413837f.png)

but the problem is when I trying click on input field in second column. Then option is selected and I lost focus on input field each time when I try to enter some value.

**Comment by ZiupeX** [comment]
the problem could resolver the simple start support attribute 'selectRow' which currently is supported in DataTable

![image](https://user-images.githubusercontent.com/45762682/93468849-e7ea8500-f8ef-11ea-8dcc-3adfce963be3.png)

**Comment by melloware** [comment]
A quality PR providing the solution is welcome.

**Comment by melloware** [comment]
@ZiupeX going to close this one. None of the other Prime libraries have this feature and I have never seen a UI component like this with this behavior.  If you feel strongly about it I suggest requesting it and financing it through PRO support.
