### ISSUE TITLE
DataTable: add 'expanded' variable to p:headerRow

### ISSUE THREAD

**Issue by hajekm** [primefaces/primefaces#6325]
It'll be more easy to work with expandableRowGroups if you can determine which rows should be expanded.

**Comment by melloware** [comment]
A quality PR providing the solution is welcome.

**Comment by hajekm** [comment]
@melloware I meant something like this, but I don't know where the code must be overwritten. I expect this is not that simple like it looks:

`public abstract class HeaderRowBase extends UIComponentBase {

    public static final String COMPONENT_FAMILY = "org.primefaces.component";

    public static final String DEFAULT_RENDERER = "org.primefaces.component.HeaderRowRenderer";

    public enum PropertyKeys {
        expanded
    }

    public HeaderRowBase() {
        setRendererType(DEFAULT_RENDERER);
    }

    @Override
    public String getFamily() {
        return COMPONENT_FAMILY;
    }

    public boolean isExpanded() {
        return (Boolean) getStateHelper().eval(PropertyKeys.expanded, true);
    }

    public void setExpanded(boolean expanded) {
        getStateHelper().put(PropertyKeys.expanded, expanded);
    }

}`

`public class HeaderRowRenderer extends CoreRenderer {

    @Override
    public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
        HeaderRow row = (HeaderRow) component;
        DataTable table = (DataTable) row.getParent();
        ResponseWriter writer = context.getResponseWriter();
        boolean isExpandableRowGroups = table.isExpandableRowGroups();
        boolean isExpanded = row.isExpanded();

        writer.startElement("tr", null);
        writer.writeAttribute("class", DataTable.HEADER_ROW_CLASS, null);

        boolean isFirstColumn = true;
        for (int i = 0; i < row.getChildCount(); i++) {
            UIComponent child = row.getChildren().get(i);
            if (child.isRendered() && child instanceof Column) {
                Column column = (Column) child;
                String style = column.getStyle();
                String styleClass = column.getStyleClass();

                writer.startElement("td", null);
                if (style != null) {
                    writer.writeAttribute("style", style, null);
                }
                if (styleClass != null) {
                    writer.writeAttribute("class", styleClass, null);
                }
                if (column.getRowspan() != 1) {
                    writer.writeAttribute("rowspan", column.getRowspan(), null);
                }
                if (column.getColspan() != 1) {
                    writer.writeAttribute("colspan", column.getColspan(), null);
                }

                if (isExpandableRowGroups && isFirstColumn) {
                    String ariaLabel = MessageFactory.getMessage(DataTable.ROW_GROUP_TOGGLER, null);

                    writer.startElement("a", null);
                    writer.writeAttribute("class", DataTable.ROW_GROUP_TOGGLER_CLASS, null);
                    writer.writeAttribute(HTML.ARIA_EXPANDED, String.valueOf(isExpanded), null);
                    writer.writeAttribute(HTML.ARIA_LABEL, ariaLabel, null);
                    writer.writeAttribute("href", "#", null);
                    writer.startElement("span", null);
                    writer.writeAttribute("class", isExpanded ? DataTable.ROW_GROUP_TOGGLER_ICON_S_CLASS : DataTable.ROW_GROUP_TOGGLER_ICON_E_CLASS, null);
                    writer.endElement("span");
                    writer.endElement("a");

                    isFirstColumn = false;
                }

                column.encodeAll(context);

                writer.endElement("td");
            }
        }

        writer.endElement("tr");
    }`

**Comment by melloware** [comment]
OK I took your hint but it needed more work than that but I was able to accomplish it.  Please see PR.

**Comment by hajekm** [comment]
Great and fast thanks a lot. This is what I exactly meant
