### ISSUE TITLE
FileDownload: Safari Naming Issue

### ISSUE THREAD

**Issue by danielamorais** [primefaces/primefaces#6327]
**Describe the defect**
When the file name is too long and I try to download it in Safari, the file is renamed to part of URL. E.g, if my current URL is localhost:8080/app/documents/771 then the file is renamed to "771". Note that it works fine in Chrome.

**Environment:**
 - PF Version: 6.2
 - JSF + version: JSF 2.2 + MyFaces 2.2.6
 - Affected browsers: Safari

**To Reproduce**
1. Rename a PNG image to "Screen Shot 2552018-09-10 at 08.17.168792378923879423789324789234789234789023478943829009872438723487990724490237842378947289379802323478923478974283923487943287937428978932478324789873924789324879034278978923478923478923470897890432879 (1).png"
2. Upload it 
3. Try to download it with the code snippet below in Safari 14 or Safari 13
4. See the error

**Expected behaviour**
Download the file with the original name and extension

**XHTML**
```html
<h:commandLink value="#{document.fileName}" ajax="false" immediate="true"
 onclick="PrimeFaces.monitorDownload(PF('blockUIWV').show(), PF('blockUIWV').hide()); _paq.push(['trackEvent', 'Documents', 'Download document,'Download']);">
 <p:fileDownload value="#{bean.downloadDocument(document.myDocument)}" />
</h:commandLink>
```

I tried with HTML5
```html
<h:commandLink value="#{document.filename}" ajax="false" immediate="true"
 pt:download="#{document.filename}
 onclick="PrimeFaces.monitorDownload(PF('blockUIWV').show(), PF('blockUIWV').hide()); _paq.push(['trackEvent', 'Documents', 'Download document,'Download']);">
 <p:fileDownload value="#{bean.downloadDocument(document.myDocument)}" />
</h:commandLink>
```

**Code**
```java
@Entity
public class Document implements Serializable {
        @Getter
	@Setter
	private String fileName;
}
```

**Comment by melloware** [comment]
Safari on MacOS or on Windows?

**Comment by melloware** [comment]
I can confirm even on PF 9.0 the is a Safari issue and here is the error in the Safari console **"Failed to load resource: Frame load interrupted"**:
![image](https://user-images.githubusercontent.com/4399574/93616667-065d8880-f9a3-11ea-90cd-fa3f554e681a.png)

If I use @jepsar new Ajax Download it works in Safari and downloads the file correctly with the correct file name.

https://github.com/primefaces/primefaces/issues/5978

**Comment by melloware** [comment]
@danielamorais I suggest you open a ticket with Apple.  This is definitely a bug and the filename works fine in Chrome and Firefox and MS Edge.

**Comment by melloware** [comment]
Now that 10.0.0.RC1 is released you can now use AJAX filedownload and this Safari issue is resolved.
