### ISSUE TITLE
InputNumber: Does not perfectly respect @Digits

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6328]
p:inputNumber  shall restrict the input according to the JPA annotations (of course when javax.faces.validator.ENABLE_VALIDATE_WHOLE_BEAN is set to true). However, for decimal values p:inputNumber does not work perfectly. 

Look at my example case:

<p:inputNumber thousandSeparator="" value="#{consumable.price}">

based on attribute price of class consumable:

@DecimalMin("0")
@Digits(integer = 10, fraction = 2)
private BigDecimal price;

Here, i can enter the value="12345678901" which has 11 integer digits. This should be not possible in this case.

When the validation clicks in, it will correctly report

numeric value out of bounds (<10 digits>.<2 digits> expected)

but - as said above - we should not come to that stage if the user was not allowed to entered an invalid decimal number.

**Comment by melloware** [comment]
So I believe the PF code you are referring to is this...
```java
        if (input instanceof InputNumber) {
            InputNumber inputNumber = (InputNumber) input;

            if (LangUtils.isValueBlank(inputNumber.getMaxValue())) {
                if (annotationType.equals(Max.class)) {
                    Max max = (Max) constraint;
                    inputNumber.setMaxValue(String.valueOf(max.value()));
                }
                if (annotationType.equals(DecimalMax.class)) {
                    DecimalMax max = (DecimalMax) constraint;
                    inputNumber.setMaxValue(max.value());
                }
                if (annotationClassName.equals(NegativeClientValidationConstraint.CONSTRAINT_ID)) {
                    inputNumber.setMaxValue("-0.0000001");
                }
                if (annotationClassName.equals(NegativeOrZeroClientValidationConstraint.CONSTRAINT_ID)) {
                    inputNumber.setMaxValue("0");
                }
            }

            if (LangUtils.isValueBlank(inputNumber.getMinValue())) {
                if (annotationType.equals(Min.class)) {
                    Min min = (Min) constraint;
                    inputNumber.setMinValue(String.valueOf(min.value()));
                }
                if (annotationType.equals(DecimalMin.class)) {
                    DecimalMin min = (DecimalMin) constraint;
                    inputNumber.setMinValue(min.value());
                }
                if (annotationClassName.equals(PositiveClientValidationConstraint.CONSTRAINT_ID)) {
                    inputNumber.setMinValue("0.0000001");
                }
                if (annotationClassName.equals(PositiveOrZeroClientValidationConstraint.CONSTRAINT_ID)) {
                    inputNumber.setMinValue("0");
                }
            }

            if (annotationType.equals(Digits.class) && LangUtils.isValueBlank(inputNumber.getDecimalPlaces())) {
                Digits digits = (Digits) constraint;
                inputNumber.setDecimalPlaces(String.valueOf(digits.fraction()));
            }
        }
```

**Comment by melloware** [comment]
It looks like its only using DIGITS to check for the decimalPlaces value.

**Comment by melloware** [comment]
It doesn't look like AutoNumeric has a way of limiting the integer portion of the value except by the use of maxValue="" however that may override a specific maxValue you have already set on the component.

Not sure it is possible to fix this?  Do you have any suggestions?

**Comment by tuerker** [comment]
by defining

@DecimalMin("0")
@digits(integer = 10, fraction = 2)
private BigDecimal price;

i am expecting that i can only enter decimals with max 10 digits before the comma and max. 2 after the comma.

everything else is hack. so AutoNumeric should fix this by providing an attribute that allows to map integer part.

however, i made bad experience with AutoNumeric. they are not really responsive. i have placed there 

an important issue to be fixed more than half a year ago: https://github.com/autoNumeric/autoNumeric/issues/674

**Comment by melloware** [comment]
Yep will close for now as there is nothing PF can do about this it would have to be fixed at AutoNumeric for us to be able to do anything useful.

**Comment by tuerker** [comment]
PF could do the following: whenever @digits(integer = Y, fraction = 2) is defined, then 

inputNumber.setMaxValue(X);

could be set X =MAX(max.value(), maxNumber_of_Y).

**Comment by melloware** [comment]
Feel free to submit a PR.
