### ISSUE TITLE
OSGi: Export-Package directive does not include shaded classes

### ISSUE THREAD

**Issue by ngriffin7a** [primefaces/primefaces#6338]
**Describe the defect**
The OSGi Export-Package directive does not include packages that are added by the maven-shade-plugin

**Reproducer**
N/A

**Environment:**
 - PF Version: _8.0_
 - JSF + version: N/A
 - Affected browsers: N/A

**To Reproduce**
1. Deploy primefaces-8.0.jar to an OSGi container (i.e. Glassfish's OSGi modules)
2. Within a WAR project, embed WEB-INF/primefaces-extensions-8.0.1.jar
3. Deploy the WAR project

**Expected behavior**
Deployment should work without errors, but instead a `ClassNotFoundException` will get thrown due to classes in `org/primefaces/shaded/json` not being available to the ClassLoader.

**Example XHTML**
N/A

**Example Bean**
N/A

**Comment by melloware** [comment]
I am definitely not an OSGI expert but doesn't `<Export-Package>org.primefaces.*;version="${project.version}</Export-Package>` in the pom.xml mean that everthing in org.primefaces is exported?

```xml
 <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>4.2.1</version>
                <extensions>true</extensions>
                <configuration>
                    <supportedProjectTypes>
                        <supportedProjectType>jar</supportedProjectType>
                    </supportedProjectTypes>
                    <instructions>
                        <Export-Package>org.primefaces.*;version="${project.version}</Export-Package>
```

**Comment by ngriffin7a** [comment]
@melloware No, that's not enough because the shade plugin adds stuff that the maven-bundle-plugin doesn't see. I'll be sending a pull request shortly with the fix.

**Comment by melloware** [comment]
excellent i see this is a pretty common problem: https://stackoverflow.com/questions/18280608/using-maven-bundle-plugin-with-the-maven-shade-plugin

Looking forward to your PR!

**Comment by ngriffin7a** [comment]
See https://github.com/primefaces/primefaces/pull/6340

**Comment by ngriffin7a** [comment]
@melloware If you find the PR acceptable, then I would be much obliged if you would consider backporting. Thank you.

**Comment by melloware** [comment]
Looks good to me I made one comment.  And @mertsincan decides whether this gets backported to 8.0.5

**Comment by melloware** [comment]
Thanks for your PR!

**Comment by ngriffin7a** [comment]
It was my pleasure @melloware thank so much for the speedy review and merge! :)

**Comment by melloware** [comment]
You should be able to check it out locally to make sure using 9.0 SNAPSHOT:
```xml
<dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>

 <repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>
```
