### ISSUE TITLE
SelectOneMenu - editable="true" - If I delete the value, the value for itemLabel is set by the first and deactivated item | pf 7.0.16

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#6342]
simple code:
```
<p:selectOneMenu id="ustId" styleClass="editable-dropdown"
                                         value="#{stammdatenAdministrationController.item.umsatzSteuerId}"
                                         editable="true" tabindex="34"
                                         required="#{stammdatenAdministrationController.requiredUmsatzId}"
                                         validator="#{stammdatenAdministrationController.validateUstId}">
                            <f:selectItem itemDisabled="true"
                                          itemLabel="please choosed"
                                          itemValue="#{null}" value="#{null}"/>
                            <f:selectItems value="#{stammdatenAdministrationController.schlUstidEntityList}" var="item"
                                           itemLabel="#{item.name}" itemValue="#{item.name}"/>
                            <p:ajax event="change" process="@this" immediate="true"/>
                        </p:selectOneMenu>
```

the backend bean has one element in list. when i choosed this element from backend, then is the label corect.
when i the inputfield of selectedOneMenu cleared over keyboard and then commited form and reloaded this, then is label from selectOneMenu filled with "please choosed".

**Comment by melloware** [comment]
you did not follow the issue template and list what version of PF you are using?  whether you have tried the latest version? Mojarra or Myfaces version?

**Comment by melloware** [comment]
Also here is a reproducer:
[pf-6342.zip](https://github.com/primefaces/primefaces/files/5275545/pf-6342.zip)

Can you update it to reproduce your issue please?  Just run `mvn clean jetty:run` and then navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by StevenHachel** [comment]
so sorry! 

- Primefaces 7.0.16
- Java 8, JavaEE 6
- jsf-api 2.1.29-11

under PF 6.0 works without this effect.

**Comment by melloware** [comment]
OK can you update my  reproducer above and zip it here so I can debug the issue.

**Comment by melloware** [comment]
Actually what is your expected behavior of this?  When you clear out the value then the value = NULL and it matches this item:
```xml
<f:selectItem itemDisabled="true"
                                          itemLabel="please choosed"
                                          itemValue="#{null}" value="#{null}"/>
```
So I would expect it to say "please choosed" since it matches the value.

**Comment by StevenHachel** [comment]
**selectedItem** has parameter **itemDisabled**="true".
then the selection should not appear. It is also misleading for the user after clearing the field.

**Comment by melloware** [comment]
I believe your issue is this: https://github.com/primefaces/primefaces/issues/5299

See this comment specifically: https://github.com/primefaces/primefaces/issues/5299#issuecomment-549492475

Fixed already in 8.0.

**Comment by StevenHachel** [comment]
okay, next step upgrade to 8. :-D

**Comment by melloware** [comment]
i can reopen if that is not the issue but it feels like it is

**Comment by StevenHachel** [comment]
sorry for my late reply!
Here is a modified example that shows what describes my problem when you enter the page. Deactivated elements are preselected in the dropdown. But that shouldn't be.
[pfTest.zip](https://github.com/primefaces/primefaces/files/5457074/pfTest.zip)

![grafik](https://user-images.githubusercontent.com/29144366/97545685-a3acd300-19cb-11eb-8a19-c83ed472861c.png)
![grafik](https://user-images.githubusercontent.com/29144366/97545602-8f68d600-19cb-11eb-9fe6-233cf8b26638.png)

```
<p:selectOneMenu value="#{testView.testString}" hideNoSelectionOption="#{not empty testView.testString}" >
    <p:ajax process="@this" update="@this" />
        	
    <f:selectItem itemValue="#{null}" value="#{null}" itemLabel="-- please select --" noSelectionOption="true" />
    <f:selectItem itemValue="t1" itemLabel="Test 1" />
    <f:selectItem itemValue="t2" itemLabel="Test 2" />
    <f:selectItem itemValue="#{null}" value="#{null}" itemLabel="Test 3 disabled" itemDisabled="true" noSelectionOption="true"/>
    <f:selectItem itemValue="t4" itemLabel="Test 4" />
</p:selectOneMenu>
```

And that this will only be fixed in version 8 is unfavorable!

**Comment by melloware** [comment]
I think its actually a duplicate of https://github.com/primefaces/primefaces/issues/5886

Can you try my version here:
[pf-6342-PF9.zip](https://github.com/primefaces/primefaces/files/5458053/pf-6342-PF9.zip)

That uses a BETA of PF9 and you can see the issue is fixed.

**Comment by StevenHachel** [comment]
Yes it works! Then don't I hope for a fix for version 7?

Steven

**Comment by melloware** [comment]
Unless you are a PRO subscriber and can request it I doubt this will be backported to 7. I don't work for PrimeTek though...

**Comment by StevenHachel** [comment]
Already very threesome when you have to go from elite to pro user to get an expected functioning dropdown box. Isn't there anything special that I'm asking for? :-)

Thx for help!

Steven

**Comment by tandraschko** [comment]
We dont work for PrimeTek, so thats up to @mertsincan. We only work in the current master as Community.
