### ISSUE TITLE
FileUpload fails to execute listener on every second upload

### ISSUE THREAD

**Issue by fcanevar** [primefaces/primefaces#635]
Hi, I would like to see this google code issue resolved: https://code.google.com/p/primefaces/issues/detail?id=6157, it still happens to me with PrimeFaces 5.2.9 and MyFaces 2.2.7, I think it's a problem of the MyFaces implementation, but the patch suggested in the issue works fine, could someone implement it in the 5.3 or 5.2.\* release?

I copy/paste the whole issue:

Reported by ryan.ben...@gmail.com, Sep 23, 2013
Primefaces 4.0.RC1 - MyFaces 2.1.12 - Spring Webflow 2.3.2 - Jetty/Tomcat 7

I found that overriding the isTransient method of the org.primefaces.component.fileupload.FileUpload component fixes the issue. It looks like the Common and Native decoders are setting the value to true after queuing the FileUpload event and this then removes the component from the ui tree when it is next processed. It would be good to know why it is set to transient as this seems to be new with the 4.0 branch. For anyone else wondering, you can override the component by creating a class:

```
public class NonTransientFileUpload extends org.primefaces.component.fileupload.FileUpload {
    @Override
    public boolean isTransient() {
        return false;
    }
}
```

and then add the following to the webapps faces-config

```
    <component>
        <component-type>org.primefaces.component.FileUpload</component-type>
        <component-class>mypackage.NonTransientFileUpload</component-class>
    </component>
```

**Comment by tandraschko** [comment]
What about providing an COMPLETE example which demostrates the problem instead just reopening the case?
maybe you should try it without webflow or switching to mojarra etc.
For me, the fileupload works fine with MyFaces on every upload.

**Comment by fcanevar** [comment]
Here it is a complete example, I'm Running it on: PrimeFaces 5.2.10, MyFaces 2.2.8, Java+Tomcat 8.
Only once every two it uploads the file correctly.

index.xhtml

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
    <h:form id="myform">
        <p:growl id="myGrowl" autoUpdate="true" globalOnly="false" />
        <p:tabView dynamic="true">
            <p:tab id="tab1" title="tab1"></p:tab>
            <p:tab id="tab2" title="tab2">
                <p:fileUpload id="uplaod"
                    fileUploadListener="#{testBck.fileUploadListener}" auto="true"
                    update="@form" />
            </p:tab>
        </p:tabView>
    </h:form>
</h:body>
</html>
```

TestBck.java

```
package com.test;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

public class TestBck {
    public void fileUploadListener(FileUploadEvent event) throws Exception {
        final UploadedFile item = event.getFile();
        System.out.println(item.getFileName());
        FacesContext.getCurrentInstance().addMessage(
                null,
                new FacesMessage(FacesMessage.SEVERITY_INFO,
                        item.getFileName(), item.getContentType()));
    }
}
```

faces-config.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<faces-config xmlns="http://xmlns.jcp.org/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_2.xsd"
    version="2.2">
    <managed-bean>
        <managed-bean-name>testBck</managed-bean-name>
        <managed-bean-class>com.test.TestBck</managed-bean-class>
        <managed-bean-scope>session</managed-bean-scope>
    </managed-bean>
</faces-config>
```

web.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://java.sun.com/xml/ns/javaee"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
    id="WebApp_ID" version="3.0">
    <display-name>TestPrime</display-name>
    <context-param>
        <param-name>javax.faces.FACELETS_REFRESH_PERIOD</param-name>
        <param-value>2</param-value>
    </context-param>
    <context-param>
        <param-name>com.sun.faces.validateXml</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
        <param-value>server</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.DEFAULT_SUFFIX</param-name>
        <param-value>.xhtml</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.FACELETS_SUFFIX</param-name>
        <param-value>.xhtml</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.PROJECT_STAGE</param-name>
        <param-value>Development</param-value>
    </context-param>
    <context-param>
        <param-name>com.sun.faces.verifyObjects</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.FACELETS_SKIP_COMMENTS</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
        <param-name>org.apache.myfaces.PRETTY_HTML</param-name>
        <param-value>false</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.ALLOW_JAVASCRIPT</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.CONFIG_REFRESH_PERIOD</param-name>
        <param-value>0</param-value>
    </context-param>
    <context-param>
        <param-name>org.apache.myfaces.EARLY_FLUSH_ENABLED</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
        <param-name>org.apache.myfaces.RESOURCE_MAX_TIME_EXPIRES</param-name>
        <param-value>1000</param-value>
    </context-param>
    <context-param>
        <param-name>org.apache.myfaces.LOG_WEB_CONTEXT_PARAMS</param-name>
        <param-value>false</param-value>
    </context-param>
    <context-param>
        <param-name>javax.faces.PARTIAL_STATE_SAVING</param-name>
        <param-value>false</param-value>
    </context-param>
    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.jsf</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.faces</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>/faces/*</url-pattern>
    </servlet-mapping>

    <welcome-file-list>
        <welcome-file>index.xhtml</welcome-file>
    </welcome-file-list>
    <listener>
        <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
    </listener>
</web-app>
```

Thanks!

**Comment by fcanevar** [comment]
I've tried the same example also with Mojarra 2.2.12 and I've the same issue. :(

**Comment by tandraschko** [comment]
removing

```
    <context-param>
        <param-name>javax.faces.PARTIAL_STATE_SAVING</param-name>
        <param-value>false</param-value>
    </context-param>
```

works fine for me. I don't see any case i would ever disable partial state saving.

**Comment by fcanevar** [comment]
I've asked around, it seems that we needed to disable partial state saving due to "duplicated id" errors.
I don't think I can change it in our application, it would be to big of a deal to test it all again. Being it a parameter that can be disabled, shouldn't the framework account for that possibility?

**Comment by tandraschko** [comment]
From PrimeFaces side, everything looks fine after some minutes of debugging.
We would need more time to find the reason why it doesn't work. Feel free to debug the problem - also in the JSF impls.

About partial state saving:
IMO it should never be deactivated as it's a very big performance/memory improvement in JSF 2.0.
I would check if the "duplicate id" error still exists and otherwise try to fix this in your code.
If the "duplicate id" error only occurs on e.g. one view, you can still active full state saving for this one view via: javax.faces.FULL_STATE_SAVING_VIEW_IDS

**Comment by fcanevar** [comment]
Thanks a lot, I'll try to use it in my current version of the application and to test it as much as I can.
Keep up the good work ;)

**Comment by tandraschko** [comment]
I debugged a little bit more into the issue and it seems that on every second request the FileUpload component doesn't exist in the component tree.
I have no idea why it works e.g. with an h:inputText with attached p:ajax but not p:fileUpload.

**Comment by lagar84** [comment]
Maybe it´s related to this mojarra issue:
https://java.net/jira/browse/JAVASERVERFACES-3404
(note that it was fixed for  2.2.11)
Mojarra h:inputFile was not working on second submit with PARTIAL_STATE_SAVING = false

**Comment by tandraschko** [comment]
Thanks but the fix seems a little bit weird as the uploaded file will remain in the viewstate propably.
I will check it for 5.3.

**Comment by tandraschko** [comment]
Fixed in trunk.
Would be great if you could do a intensive test.

**Comment by fante76** [comment]
Hi Mr. tandraschko
Mr. fcanevar is no longer a member of our development team, so he cannot access our code. 
We will test PF5.3 soon and this fix too, reporting here a feedback.
Thank you.
