### ISSUE TITLE
DatePicker: lazy load disabled dates

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6355]
As explained in https://github.com/primefaces/primefaces/issues/6277 I would like to be able to lazy load disabled dates on `viewChange`. Also, I'm thinking of adding date CSS styles / colors / classes to dates later. This is also something which should be lazy loadable. So, I was thinking of adding a `DateMetaData` object which could contain stuff like `disabled` and `styleClass`.

@melloware can you assign this issue to me, please?

**Comment by melloware** [comment]
Done

**Comment by jepsar** [comment]
@melloware could you set the milestone for this issue, please?

**Comment by melloware** [comment]
Done! Don't know how i missed that!

**Comment by tandraschko** [comment]
@jepsar i have to reopen as i found some "weird" stuff:

1) bindViewChangeListener now fires 2 AJAX event if viewChange is defined; there should only be one
2) the lazyModel request does not define a event name, therefore we cant check whats the reason of the request on the server side
3) because of 2) we ALWAYS encodes the metadata now DatePickerRenderer#encodeEnd, even if the DatePicker IS NOT the source of the request. We should use ComponentUtils#isEventSource + check the event name here

**Comment by tandraschko** [comment]
would be great if you can polish it

**Comment by tandraschko** [comment]
I also did some renamings and therefore reviewed it

**Comment by melloware** [comment]
I updated the Showcase as well for Metadata changes you just made.

**Comment by jepsar** [comment]
I'll look into it

**Comment by jepsar** [comment]
Can someome please explain how

https://github.com/primefaces/primefaces/blob/8064e53c5725e2eb13f82e64905d5cccf1343a18/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L271

relates to

https://github.com/primefaces/primefaces/blob/8064e53c5725e2eb13f82e64905d5cccf1343a18/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L315-L318

?

Also, based on @tandraschko 's remark 3 I would expect an is event source check at

https://github.com/primefaces/primefaces/blob/8064e53c5725e2eb13f82e64905d5cccf1343a18/src/main/java/org/primefaces/component/schedule/ScheduleRenderer.java#L78

But it not there, right?

**Comment by melloware** [comment]
Its possible its missing in Schedule also.

**Comment by jepsar** [comment]
What about the JavaScript part? I'm trying to fully understand how the schedule component works, and then try to port that to the date picker.

**Comment by melloware** [comment]
@jepsar I think all @tandraschko is saying is change this line...
```java
if (context.getExternalContext().getRequestParameterMap().containsKey(datePicker.getClientId(context))) {
```

to the more correct...
```java
if (ComponentUtils.isRequestSource(datePicker, context)) {
```
In fact looking through the code base we are still doing the first option above in a lot of places that should be switched to `isRequestSource`

**Comment by tandraschko** [comment]
i general 
`
if (ComponentUtils.isRequestSource(datePicker, context) && event == 'viewChange') {
`

and merge both ajax requests on the client side

**Comment by melloware** [comment]
@tandraschko should I create another ticket to refactor all the places doing it Like #1 above to use `ComponentUtils.isRequestSource(datePicker, context)` ??

**Comment by tandraschko** [comment]
you can but its likely more work then just change the if - we should encode the special logic on special events
so isRequestSource isnt enough in most cases

**Comment by jepsar** [comment]
> and merge both ajax requests on the client side

I would like to, but I fail to see how that's done in the schedule component. Can someome please explain how

https://github.com/primefaces/primefaces/blob/8064e53c5725e2eb13f82e64905d5cccf1343a18/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L271

relates to

https://github.com/primefaces/primefaces/blob/8064e53c5725e2eb13f82e64905d5cccf1343a18/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L315-L318

**Comment by jepsar** [comment]
I think I found the solution in the data table JavaScript.
