### ISSUE TITLE
DataTable: NumberFormatException when cell editable and cellEditInit AJAX event

### ISSUE THREAD

**Issue by dmainardi** [primefaces/primefaces#6357]
**Describe the defect**
With cell-editable-enabled dataTable and cellEditInit ajax event, if you TAB through cells and reach last cell, last TAB rises a NumberFormatException exception.

**Reproducer**
Just clone https://github.com/dmainardi/primefaces-test repository and follow instructions.

**Environment:**
 - PF Version: 6.2 (exception rose TABBING at the end of row (not last)), 8.0, SNAPSHOT
 - JSF + version: Mojarra 2.2.20, (Mojarra) Jakarta Faces 2.3.14, **it works as expected with MyFaces 2.2.12 and MyFaces 2.3.6**
 - Affected browsers: ALL

**To Reproduce**
- clone https://github.com/dmainardi/primefaces-test.git
- run it with `mvn jetty:run`
- click on a cell (as you wanted to edit it) and TAB until table's end
- TAB another time, error is risen (check error log)

**Expected behavior**
No exception risen

**Example XHTML**
https://github.com/dmainardi/primefaces-test/blob/master/src/main/webapp/test.xhtml

**Example Bean**
https://github.com/dmainardi/primefaces-test/blob/master/src/main/java/org/primefaces/test/CarView.java

**Comment by melloware** [comment]
thank you for the runnable example.  let me investigate

**Comment by melloware** [comment]
If you need this fix right now just add this JS to your applicaton:
```javascript
PrimeFaces.widget.DataTable.prototype.showCellEditor = function(c) {
    this.incellClick = true;

    var cell = null;

    if (c) {
        cell = c;

        //remove contextmenu selection highlight
        if (this.contextMenuCell) {
            this.contextMenuCell.parent().removeClass('ui-state-highlight');
        }
    } else {
        cell = this.contextMenuCell;
    }

    var editorInput = cell.find('> .ui-cell-editor > .ui-cell-editor-input');
    if (editorInput.length !== 0 && editorInput.children().length === 0 && this.cfg.editMode === 'cell') {
        // for lazy cellEditMode
        this.cellEditInit(cell);
    } else {
        this.showCurrentCell(cell);

        if (this.hasBehavior('cellEditInit')) {
            var cellInfo = this.getCellMeta(cell);
            if (cellInfo.indexOf('undefined') === -1) {
                var ext = {
                    params: [{
                        name: this.id + '_cellInfo',
                        value: cellInfo
                    }]
                };
                this.callBehavior('cellEditInit', ext);
            }
        }
    }
};
```

**Comment by dmainardi** [comment]
Great,
it works!
Thank you.
