### ISSUE TITLE
DataTable: Column sort icon disappears after selecting another column

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6358]
**Describe the defect**
Column sort icon gets removed after selecting another column. Regression from #3818. These new changes might be the cause https://github.com/primefaces/primefaces/commit/82abe07fb648d503e47487ac5fc715f1e3e8d325#diff-265f44d9cadc896ec3d21a3a721f15ddR2030-R2048

**Environment:**
 - PF Version: 9.0-SBAPSHOT
 - JSF + version: Mojarra 2.2.8 or MyFaces 2.3.6
 - Affected browsers: Chrome, iOS, ALL

**To Reproduce**
- Go http://localhost:8080/showcase/ui/data/datatable/columns.xhtml
- Sort ID asc
- Sort BRAND
- Icon of previous selected column disappear

**Expected behavior**
Sort icon should be reinitialized to unsort icon

@eduarddrenth Could you help us to sort this out?

**Comment by eduarddrenth** [comment]
I will have a look, may take a while

**Comment by dieuph** [comment]
Can I work on this issue?

**Comment by eduarddrenth** [comment]
fine with me, I cannot until 12 oct earliest.
