### ISSUE TITLE
FileDownload: configure Cache-Control

### ISSUE THREAD

**Issue by bstobbe** [primefaces/primefaces#6359]
**Description**
Currently the fileDownload component uses Cache-Control: public and Pragma: public as the default response header.  Sometimes users have the possibility to download sensitive data. These files should not be cached anywhere. (especially considering the GDPR)

**Describe the solution you would like**
Adding a new attribute "cache-handling" or possibly a generic "response-headers", where the cache-control level can be configured.

**Comment by tandraschko** [comment]
IMO there is no reason to make it public and cacheable as default, as FileDownload is, at least for 90%, dynamically generated files.

**Comment by melloware** [comment]
@bstobbe do you have a specific GDPR use case?  @tandraschko if he has a valid GDPR use case I think maybe we should add a property override?

**Comment by tandraschko** [comment]
we could but we should likely change our default here

**Comment by bstobbe** [comment]
The GDPR says "Personal data shall be processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’)." (Art. 5f GDPR)
If every cache server can possibly save this data this confidentiality is not given

**Comment by melloware** [comment]
OK I will submit a PR.
