### ISSUE TITLE
Row selection of dataTable the up and down keys

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primefaces#636]
Line selection of dataTable the keys up and down, as in this example:
http://showcase.richfaces.org/richfaces/component-sample.jsf?demo=extendedDataTable&sample=exTableSelection&skin=wine

**Comment by xKopax** [comment]
This would be awesome =)

**Comment by diegoarantes** [comment]
Yes for sure, long time wait for this feature :(

**Comment by diegoarantes** [comment]
@cagataycivici, what do you think of this feature?

**Comment by cagataycivici** [comment]
Available for 5.4, 5.3.3 and 5.2.16.
