### ISSUE TITLE
Ajax: support form enctype

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6360]
Currently we completely ignore the enctype of the form

See: https://github.com/primefaces/primefaces/issues/6351

**Comment by tandraschko** [comment]
a PR would be great

**Comment by tandraschko** [comment]
@melloware first step commited, please review

**Comment by melloware** [comment]
OK your refactoring looks great!  My test case is still failing with your new code but I know you are still working on the other ticket for input files.
