### ISSUE TITLE
DefaultMenuItem and DefaultSubMenu setting Id does not work

### ISSUE THREAD

**Issue by sefatascan** [primefaces/primefaces#6367]
DefaultMenuItem and DefaultSubMenu  setting id does not work, For exaple, I am using `defaultMenuItem.setId("testMenuItem") `
Normaly, it should be `<li id="menuform:testMenuItem" />` but it render like that `<li id="menuform:j_idt51_3" />`

**Comment by Rapster** [comment]
Please follow defect report, otherwise closing as invalid

**Comment by Rapster** [comment]
Duplicate of #1039

**Comment by melloware** [comment]
@Rapster @sefatascan can you review my PR I believe this was quite simple to fix: https://github.com/primefaces/primefaces/pull/6371
