### ISSUE TITLE
DataTable: headerRow refactoring

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6372]
**Description**
Based on https://www.primefaces.org/showcase/ui/data/datatable/rowGroup.xhtml

**Describe the solution you would like**
As I started to have a look at #5438, `DataTable#sortBy` is used for grouping feature. And since the idea is to remove `DataTable#sortBy` I wonder how to make row grouping working... The way I see it, we should be able to simply configure row grouping like this:
```xml
<p:dataTable var="car" value="#{dtRowGroupView.cars}">

    <p:headerRow groupBy="#{car.brand}" expandable="true" />

    <p:column headerText="Year">
        <h:outputText value="#{car.year}" />
    </p:column>
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
    <p:column headerText="Id">
        <h:outputText value="#{car.id}" />
    </p:column>
</p:dataTable>
```

**Additional context**
My idea is to give slightly less responsability to DataTable which already contains a lot of attributes. Also, I like the idea that headerRow component is the determinist element _(carrying all sorts of attributes)_ that will activate the feature, just like `Column#groupRow` does.

As of today, headerRow has to contain at least one column. I don't have any scenario where several columns would be needed but I guess it can be solved with a facet if user wants to do so.

Anyway, let me know what you think?

**Comment by melloware** [comment]
yes i don't like that double use of `sortBy`.  i agree the Headerrow should have the `groupBy="#{car.brand}"`
