### ISSUE TITLE
DatePicker: month navigation buttons get not disabled when min-/maxDate is reached

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#6379]
**Describe the defect**
In the popup of the Calendar component the forward and backward navigation buttons are disabled if the min- or maxDate are reached.
This was already part of #5967. The fix was to ignore clicking the navigation buttons. But with this solution there ist no distinction between active and disabled navigation button. 
In my opinion the behavior should be as by the calendar. The navigation buttons of the datePicker should rendered but disabled, as it is for the Calendar.

**Reproducer**
Look at the showcase for Calendar - Restricted vs. DatePicker - MinMax,
or #5967

**Environment:**
 - PF Version: PrimeFaces-8.0.2-SNAPSHOT (showcase)
 - JSF + version: Mojarra-2.3.13
 - Affected browsers: does not matter

Possible Solution:
Add style class in renderBackwardNavigator and renderForwardNavigator if link sould be disabled to indicate that.

**Comment by melloware** [comment]
@OBreidenbach you mention this problem is in 8.0.2 but the fix mentioned above is in 9.0 have you tried 9.0-SNAPSHOT?  Or are you saying its a problem in 9.0 still?

**Comment by melloware** [comment]
Oh nevermind I understand now we are removing the buttons you are just saying to disable them so they are still on screen.

**Comment by OBreidenbach** [comment]
The buttons are not removed, they stay. Just he click event is ignored

**Comment by melloware** [comment]
Yep I just submitted PR to disable then with `ui-state-disabled`
