### ISSUE TITLE
DataTable: sticky header does not stick when table inside a TabView

### ISSUE THREAD

**Issue by dmainardi** [primefaces/primefaces#6381]
**Describe the defect**
If you insert a dataTable with sticky header inside e tabView, the header is not sticky. Same table outside tabView works as expected.

**Reproducer**
Just clone https://github.com/dmainardi/primefaces-test repository and follow instructions.

**Environment:**
 - PF Version: 8.0. **It works (sort of) in 6.1, 6.2 and 7.0**
 - JSF + version: Mojarra 2.2.20, (Mojarra) Jakarta Faces 2.3.14, MyFaces 2.2.12, MyFaces 2.3.6
 - Affected browsers: ALL

**To Reproduce**
1. clone https://github.com/dmainardi/primefaces-test.git
2. run it with `mvn jetty:run`
3. scroll web page and see the error (last table without sticky header)

**Expected behavior**
Sticky header in all the tables.

**Example XHTML**
https://github.com/dmainardi/primefaces-test/blob/master/src/main/webapp/test.xhtml
and
https://github.com/dmainardi/primefaces-test/blob/master/src/main/webapp/stickyHeaderTable.xhtml

**Example Bean**
https://github.com/dmainardi/primefaces-test/blob/master/src/main/java/org/primefaces/test/CarView.java

**Comment by melloware** [comment]
Related to this issue/workaround?: https://github.com/primefaces/primefaces/issues/960

**Comment by dmainardi** [comment]
My test project was not so clear.
The problem is not "duplicated header" but "header does not stick".
I tried the workaround but it doesn't work.
I updated the test project, now (I hope) it is clearer.

**Comment by melloware** [comment]
Yep I tried the workaround too and it did not work.

**Comment by melloware** [comment]
I don't thnk this will ever be supported as the sticky can't work inside the TabView
