### ISSUE TITLE
Schedule: Event URL Opens a New Empty Tab

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primefaces#6382]
**Describe the defect**
I have a schedule model. The events are added this way

```
DefaultScheduleEvent.builder()
                .[...]
                .url("/r/" + id);
```
The schedule renders fine. However, when I click on the URL of the event, the browser opens a new `about:blank` tab. Once I close it, I find that the original tab navigated correctly to the intended URL.

**Environment:**
 - PF Version: 8.0
 - JSF + version: joinfaces 4.3.0 (primefaces-spring-boot-starter, mojarra-spring-boot-starter).
 - Affected browsers: ALL

**Expected behavior**
The new tab should not open.

**Comment by melloware** [comment]
@mossaab0 See the docs for Schedule Attribute `urlTarget`; https://primefaces.github.io/primefaces/8_0/#/components/schedule?id=attributes

> urlTarget | _blank | String | Target for events with urls. Clicking on such events in the schedule will not trigger the selectEvent but open the url using this target instead. Default is "_blank".

try changing it to `urlTarget="_self"`

**Comment by mossaab0** [comment]
That helped. Thanks @melloware !

**Comment by melloware** [comment]
No problem I did find another issue as I was testing this I am fixing for 9.0.
