### ISSUE TITLE
CI: move from Travis CI to Github Actions 

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6391]
We have already done this for https://github.com/primefaces-extensions/primefaces-integration-tests.
We will do this for PF Selenium with https://github.com/primefaces-extensions/primefaces-selenium/issues/35.

After both are done successful i´ll try to provide a PR to do this for PrimeFaces too.

**Comment by melloware** [comment]
OK i am watching this build to make sure it works.  The first build will be slow because it has to cache all the Maven JARs.
