### ISSUE TITLE
Scheduler: Scrolling on a long vertical viewport will not open a dialog popup

### ISSUE THREAD

**Issue by aligit** [primefaces/primefaces#6392]
**Describe the defect**
Short slotDuration may cause long vertical scheduler screen. If the user scrolls down then the "dialog" position is computed and will cause the dialog popup show up at a position the user can not see.

**Environment:**
 - PF Version: _master-SNAPSHOT_
 - JSF + version: _e.g. Mojarra 2.2.8
 - Affected browsers:  ALL_

**To Reproduce**
1. Go to a screen with scheduler where slotDuration is very small. Like 5 or 10 minutes. 
2. Put the mouse over the scheduler component
3. Scroll down to the bottom
4. Try to press the scheduler
5. The popup dialog will not show up

**Expected behavior**
I would expect that the modal dialogue of scheduler is correctly open at the center regardless of the slotDuration.

**Example XHTML**
```html
   <h:form id="#{constants.EDIT}">
      <h:panelGrid columnClasses="value">
        <p:schedule
          id="schedule"
          widgetVar="scheduleWidgetVar"
          value="#{instrumentReservationManager.lazyEventModel}"
          slotDuration="00:10:00"
          slotEventOverlap="false"
          slotLabelFormat="HH:mm"
          timeFormat="HH:mm"
          columnHeaderFormat="week:'dddd DD MMM', month:'dddd'"
          rightHeaderTemplate="timeGridDay,timeGridWeek,dayGridMonth"
          leftHeaderTemplate="prev, next, today"
          tooltip="true"
          showWeekNumbers="false"
          allDaySlot="false"
          nextDayThreshold="00:00"
          draggable="true"
          resizable="true"
          aspectRatio="100"
          view="timeGridWeek"
          extender="initSchedule">
        </p:schedule>
```

**Comment by melloware** [comment]
@aligit Are you referring to the example like this where the dialog is controlled by you?
https://www.primefaces.org/showcase/ui/data/schedule/basic.xhtml

I am trying to understand what dialog you are referring to?

**Comment by aligit** [comment]
Dear @melloware I resolved this problem with the position attribute. I was using the absolute position. Apologies for the inconvenience.
Best Regards
