### ISSUE TITLE
FileUpload: confirm alert

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#6396]
**Description**
Client side event to ask confirmation alert before upload

**Describe the solution you would like**
`onupload="return confirm('Are you sure?')"`

**Additional context**
Forum posts
https://forum.primefaces.org/viewtopic.php?t=59755
https://forum.primefaces.org/viewtopic.php?t=56412

**Comment by melloware** [comment]
I decided to call it `onupload` instead of `onbeforesend`.
