### ISSUE TITLE
SelectOneListbox: can scroll item selected by mouse click out of view because of focus

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6401]
**Reproducer**
https://www.primefaces.org/showcase/ui/input/listbox.xhtml

**Environment:**
 - PF Version: _8.0_ and _9.0-SNAPSHOT_
 - Affected browsers: _Chrome_ (in Firefox the page moves up slightly).

**To Reproduce**
Scroll down to the point that "Omega" is at the top of the screen. Then click "Omega". Page scrolls to top.

**Expected behavior**
No scrolling.

**Comment by jepsar** [comment]
I can have a look at the cause tonight.

**Comment by melloware** [comment]
Also might be related: https://stackoverflow.com/questions/64230954/pselectonelistbox-scroll-to-pre-selected-item

**Comment by jepsar** [comment]
I narrowed it down to this line. I put a breakpoint there. Right after that line the scrolling has happened. But I don't know where I can find the source of the `focus` method that is triggered.

https://github.com/primefaces/primefaces/blob/f882f4e50bf48dda28dfa4c6f52a623422023af4/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonelistbox.js#L47

**Comment by melloware** [comment]
That is Jquery .focus() which if the input control gets focus i wonder if the browser is automatically scrolling to it.

**Comment by melloware** [comment]
See: https://stackoverflow.com/questions/4898203/jquery-focus-without-scroll

**Comment by jepsar** [comment]
The focus line was intended for keyboard navigation:

https://github.com/primefaces/primefaces/blob/f882f4e50bf48dda28dfa4c6f52a623422023af4/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonelistbox.js#L44-L47

I think we can make that part conditional. See https://stackoverflow.com/a/35034284/880619 and https://stackoverflow.com/questions/19244666/how-to-detect-if-click-event-has-been-triggered-by-enter

This happens in many places, so a core function seems to be needed which can be used in all components.

https://github.com/primefaces/primefaces/search?q=trigger%28%27focus%27%29

**Comment by jepsar** [comment]
I think I'll be solving this like:

```
if (PrimeFaces.utils.isKeyboard(e)) {
  $this.removeOutline();
  $this.focusedItem = item;
  $this.input.trigger('focus');
}
```

Where `PrimeFaces.utils.isKeyboard` contains `return event.originalEvent.detail === 0;`.

**Comment by melloware** [comment]
I see this note in StackOverflow: "IE11 event.detail is 0 for both mouse and keyboard click events "

So it may works for other browser but in your function you may have to check if `Primefaces.isIE()` then `if (evt.screenX == 0 && evt.screenY == 0) {` which works for IE?

**Comment by jepsar** [comment]
.. actually, I think it should be something like:

```
if (PrimeFaces.utils.isKeyboard(e)) {
  $this.input.trigger('focus');
}
else {
  PrimeFaces.focusWithoutScrolling($this.input);
}
```

or even

```
PrimeFaces.focusMouseAware($this.input, event);
```

and there focus but not scroll if the mouse was used.

**Comment by jepsar** [comment]
.. or even not changing anything at all on the PrimeFaces side and override the jQuery `focus` method in my project. I think that's the best solution here. Shall I close this issue?

**Comment by melloware** [comment]
Yep I closed it but you might want to post here you overridden Jquery focus just for others who find this thread to see.
