### ISSUE TITLE
DataTable: cleanup filtering

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6402]
**Description**
Clean up filtering following #5438 fix. 

**Update**
- DataTable#filterBy: expect a list of FilterMeta and no longer a map
- FilterFeature#filter: performance killer (iterate over every single cells, while it could only iterate over changed columns)

**Comment by melloware** [comment]
Have you reviewed PR #6295 from @christophs78  ??

**Comment by Rapster** [comment]
I renamed the PR and the corresponding issue (as the title was not 100% correct)

**Comment by Rapster** [comment]
I don't know if anyone can help me to understand what it is done here. Regarding globalFilter & globalFilterFunction, from the moment a row matches globalFilter using globalFilterFunction, there is no need to iterate over the columns right? From what I read, even though there is a global match, it keeps iterating... Am I missing something?

https://github.com/primefaces/primefaces/blob/b987875ca6b3f45dbe66f2efe4bfaddacd819e97/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java#L184-L220

**Comment by melloware** [comment]
I agreee why can't it just `continue` in the row loop
```java
if (globalFilter != null && globalFilterFunction != null) {
    globalMatch = (Boolean) globalFilterFunction.invoke(elContext,
        new Object[] {
            table.getRowData(), globalFilter.getFilterValue(), filterLocale
        });

    if (globalMatch) {
        continue;
    }
}
```

The one in the repeating row

**Comment by Rapster** [comment]
I think I understand the confusion. First, variable names: it's not about whether or not the filter input is matching the column value or the entire row, but more, is the row/column eligible as a result, see the difference? For example, the filter might be null, the column value not but still "matching"... To go back to my last post, when globalMatch is true, it means either there was a real match or the filter input is null... Basically it's not easy to really know what is the result 😅 

Maybe boolean is not the best return type... int? 1 = match, 0 not matching, -1 "not matching but acceptable". Doing this would give more options to the user, for example if globalFilterFunction set, he could decide to return 0 so it skips the line and go next (today even if it's truly matching it keeps looping over columns)

**Comment by melloware** [comment]
Oh I see.  I think this section definitely needs some better in line comments!

**Comment by Rapster** [comment]
Can we just say if globalFilterFunction returns false, it simply does not match the line and go next?

**Comment by Rapster** [comment]
@jepsar You might be able to have an opinion also on my last comment?

**Comment by Rapster** [comment]
The way I see it, globalFilter will match a result if:
- globalFilter: any columns contains globalFilter input (see GlobalFilterConstraint)
- globalFilter + globalFilterFunction: custom impl deciding whether the row data is part of the result

**Comment by jepsar** [comment]
> Can we just say if globalFilterFunction returns false, it simply does not match the line and go next?

Yes, I think that's correct. In case of true you could narrow the result down by applying column filters. In case of false this will never evaluate to true:

```
            boolean matches = localMatch;
            if (globalFilter != null) {
                matches = localMatch && globalMatch;
            }
```

**Comment by jepsar** [comment]
An issue was reported on https://discord.com/channels/787967399105134612/787975395793305601

Supposedly the `globalFilterFunction` is never called.

I used to test that with the showcase, but that example has been removed...

Edit: the issue seems to be more generic. Default global filtering also does not work.

**Comment by Rapster** [comment]
Regression introduced by 47c582ddee39c598e3e441fc8c2a8ef00885db94. Looping over columns will never call globalFilter. @tandraschko should have an idea how to fix this

**Comment by jepsar** [comment]
See also #6910
