### ISSUE TITLE
Firefox editor empty submit

### ISSUE THREAD

**Issue by dayoffrettchen** [primefaces/primefaces#641]
The submit of text don't work with this Firefox version.

Reproduce:
Primefaces: Running PrimeFaces-5.2.10 on Mojarra-2.2.8
Tested Firefox version:
  "geckoAppInfo": {
    "_v": 1,
    "vendor": "Mozilla",
    "name": "Firefox",
    "id": "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",
    "version": "39.0",
    "appBuildID": "20150629114848",
    "platformVersion": "39.0",
    "platformBuildID": "20150629114848",
    "os": "Linux",
    "xpcomabi": "x86_64-gcc3",
    "updateChannel": "release"
  }
(possible versions with the same behavior (not tested): Firefox 31.7.0, Firefox 38.0.6)

enter text (without pressing any button on the editor) and submit. -> result: empty textbox
![screenshot-www primefaces org 2015-08-19 14-15-33](https://cloud.githubusercontent.com/assets/5052781/9355844/f208d062-467c-11e5-84d3-fc259593c33e.png)

As long as the redo button is disabled the form submits an empty field.

**Comment by mertsincan** [comment]
I didn't replicate the issue. Please try with FF-40.0.2.
![editor](https://cloud.githubusercontent.com/assets/11868120/9357591/836df6aa-4690-11e5-817c-9292ef46b953.PNG)
