### ISSUE TITLE
Schedule: Poll Inconsistently Causes a Scroll Up

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primefaces#6412]
**Describe the defect**
In the snippet below, when I scroll to the bottom of the page (such that the schedule header isn't visible anymore), then no problem occurs following a poll. However, if I reduce `height: 10000px` to  a smaller number, such as `200px`, then the page keeps scrolling to the top after each poll.

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:view>
        <h:head>
        </h:head>
        <h:body>
            <h:form>
                <p:poll update="schedule"/>
                <div style="height: 10000px"/>
                <p:schedule id="schedule" value="#{myController.schedule}"/>
            </h:form>
        </h:body>
    </f:view>
</html>

```

```
import javax.enterprise.context.RequestScoped;
import org.primefaces.model.DefaultScheduleModel;
import org.springframework.stereotype.Controller;

@RequestScoped
@Controller
public class MyController {

    private DefaultScheduleModel schedule = new DefaultScheduleModel();

    public DefaultScheduleModel getSchedule() {
        return schedule;
    }

    public void setSchedule(DefaultScheduleModel schedule) {
        this.schedule = schedule;
    }
}
```

**Environment:**
 - PF Version: 8.0
 - JSF version: joinfaces 4.3.3 (primefaces-spring-boot-starter, mojarra-spring-boot-starter).
 - Affected browsers: Chrome.

**Expected behavior**
There should be no scrolling to top in both cases.

**Comment by melloware** [comment]
I believe part of your issue is this: https://github.com/primefaces/primefaces/issues/6382

Fixed by: https://github.com/primefaces/primefaces/pull/6383/files

**Comment by mossaab0** [comment]
But there are no URLs in the schedule (it actually doesn't have any events).

**Comment by melloware** [comment]
Then why does your issue say this "The schedule renders fine. However, when I click on the URL of the event, the browser opens a new about:blank tab. Once I close it, I find that the original tab navigated correctly to the intended URL."

**Comment by mossaab0** [comment]
I said that in that other issue. Now, in the issue I've just opened, the schedule doesn't have any events.

**Comment by tandraschko** [comment]
i think thats by design. If you update the component, it rerenders and with the initial scrollt position.

**Comment by mossaab0** [comment]
@tandraschko I don't get it. Why does it scroll to the top when `<div style="height: 200px"/>`, while it doesn't scroll when `<div style="height: 10000px"/>`?

Whatever the design is, it should be consistent.

**Comment by tandraschko** [comment]
i dont know, i didnt test your case. Its just a normal behavior that if you update it, that it rerenders.

**Comment by melloware** [comment]
[pf-6412.zip](https://github.com/primefaces/primefaces/files/5372176/pf-6412.zip)

I can't reproduce with the attached reproducer?  the poller is working fine and the page is not scrolling back up?

**Comment by christophs78** [comment]
Maybe it would be better to update with `PF('myschedule').update();` JS instead of p:poll. eg triggered by https://www.w3schools.com/jsref/met_win_setinterval.asp
Also see https://primefaces.github.io/primefaces/8_0/#/components/schedule?id=ajax-updates.

**Comment by mossaab0** [comment]
> [pf-6412.zip](https://github.com/primefaces/primefaces/files/5372176/pf-6412.zip)
> 
> I can't reproduce with the attached reproducer? the poller is working fine and the page is not scrolling back up?

Correct. It does not scroll up with `height: 10000px`. But it scrolls up with `height: 200px`

**Comment by mossaab0** [comment]
> Maybe it would be better to update with `PF('myschedule').update();` JS instead of p:poll. eg triggered by https://www.w3schools.com/jsref/met_win_setinterval.asp
> Also see https://primefaces.github.io/primefaces/8_0/#/components/schedule?id=ajax-updates.

That actually ended up to be a nice workaround to avoid `p:poll`. The page didn't scroll. Thanks!

**Comment by melloware** [comment]
Should we mark this as WontFix @tandraschko this is just how polling and updates work?

**Comment by tandraschko** [comment]
Yep
