### ISSUE TITLE
Calendar/DatePicker: tabindex order lost on selecting a date/time

### ISSUE THREAD

**Issue by MP2E** [primefaces/primefaces#6416]
**Describe the defect**
If you click a date/time in the calendar widget, then press tab, it goes to the very top of the browser instead of the next item in the tab order

Note that if you just click the box and don't select anything in the Calendar widget, and press tab, it behaves as expected

datePicker mostly works as expected, unless showTime="true" while timeOnly="false", in that case tab order also seems to get messed up if a date is selected. Using the time picker does not mess up the tab order.

**Reproducer**
- https://www.primefaces.org/showcase/ui/input/calendar/calendarJava8.xhtml

**Environment:**
 - PF Version: _8.0_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to https://www.primefaces.org/showcase/ui/input/calendar/calendarJava8.xhtml
2. Select the box next to Popup
3. Click a day of the month, then press tab
4. See bug

**Expected behavior**
The next item in the tabindex to be selected

**Comment by melloware** [comment]
I think in both `Calendar` and `DatePicker` you want to add `focusOnSelect="true"`.

https://primefaces.github.io/primefaces/8_0/#/components/calendar?id=attributes

_If enabled, the input is focused again after selecting a date. Default is false._

**Comment by melloware** [comment]
Will close for now unless I hear back from OP.
