### ISSUE TITLE
SelectOneMenu: performance-optimization

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6418]
Especially for SelectOneMenu´s with a huge amount of SelectItems. (hundreds to thousands)

some ideas:

- [x] SelectOneMenuRenderer#encodeSelectItems; improve selected-check
- [x] SelectOneMenuRenderer renders currently encodeHiddenSelect and encodePanelContent; instead render only encodeHiddenSelect on the server; use this to render the panel on the client with JS; with custom content keep it as-is

**Comment by tandraschko** [comment]
Is 2) really faster? Please provide a Benchmark on different Browser

+1 for 1)
