### ISSUE TITLE
p:columnToggler hidden columns reappear after change page

### ISSUE THREAD

**Issue by ReedElliott** [primefaces/primefaces#642]
I created a p:dataTable with p:columnToggler by copying the code documented in the following blog:

http://blog.primefaces.org/?p=3341

When I select the column toggler button and uncheck a column, the column disappears and I see that primefaces added a style="display: none;" attribute to the appropriate th and td elements.

However, when I select the next page button or one of the numbered page buttons on the paginator, the column returns but the column header is still hidden. The th element still has the style="display: none;" attribute but the same attribute is missing from the td elements. The td elements do have a new ui-helper-hidden class.

Please see the following PrimeFaces forum entry for more information.

http://forum.primefaces.org/viewtopic.php?f=27&t=43042

**Comment by jplette** [comment]
still buggy in 5.3 and 5.2 when used in lazy table and filter for data
