### ISSUE TITLE
DataExporter: PDF in Landscape Mode

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6425]
**Description**
A feature that PFE Exporter that we need to bring over to PF is the ability to render PDF in Landscape mode to give it more room to render.

See: https://github.com/primefaces-extensions/primefaces-extensions/issues/133

**Comment by stefan-dan** [comment]
@melloware please update the wiki, there is written "_PDF can now be set in Portrait Mode..._", I think it should be Landscape Mode. https://primefaces.github.io/primefaces/10_0_0/#/../migrationguide/10_0_0?id=dataexporter

**Comment by melloware** [comment]
Yep you are right.

**Comment by melloware** [comment]
Fixed!
