### ISSUE TITLE
Datatable: filter issue with retaining object values when filter returns no rows

### ISSUE THREAD

**Issue by gannulee** [primefaces/primefaces#6427]
I am using primefaces(6.2) datatable, while using column filter I am observing a weird behavior, though all the columns (with outputText, inputText) retain the object value, columns with 'selectOneMenu', 'selectBooleanCheckbox' not retaining the object value and returning null, false.
Issue occurring only while performing the filter and filer returns no rows, if the filter returns at least one row everything looks normal and all columns are behaving normally. please find below code snippet that I am using to troubleshoot, I really appreciate any inputs to resolve this issue.

**XHTML**

        <html xmlns="http://www.w3.org/1999/xhtml"
    	xmlns:h="http://xmlns.jcp.org/jsf/html"
    	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    	xmlns:f="http://xmlns.jcp.org/jsf/core"
    	xmlns:p="http://primefaces.org/ui"
    	xmlns:c="http://java.sun.com/jstl/core">
    <h:body>
    
    <h:form id="frmClientDetails">
    							<p:dataTable 
    										value="#{myBean.lstContact}" var="varContact" 
    										rowStyleClass="#{varContact.strRowCSS}">
    								<p:column width="180" headerText="Sal">
    									<p:selectOneMenu value="#{varContact.strSalutation}">
    									<f:selectItem itemLabel="--Select one--" itemValue=""></f:selectItem>
    									<f:selectItem itemLabel="DR" itemValue="DR"></f:selectItem>
    									<f:selectItem itemLabel="MISS" itemValue="MISS"></f:selectItem>
    									<f:selectItem itemLabel="MRS" itemValue="MRS"></f:selectItem>
    									<f:selectItem itemLabel="MR" itemValue="MR"></f:selectItem>
    									<f:selectItem itemLabel="MS" itemValue="MS"></f:selectItem>
    									</p:selectOneMenu>
    								</p:column>
    								<p:column width="200" filterBy="#{varContact.strFirstName}" headerText="First Name">
    									<p:inputText maxlength="2000" value="#{varContact.strFirstName}"/>
    								</p:column>
    								
    							   </p:dataTable>
     
    							</h:form>
    
    		</h:body>
    </html>

**ManagedBean**

    import java.util.ArrayList;
    import java.util.List;
    
    import javax.annotation.PostConstruct;
    import javax.inject.Named;
    import org.springframework.context.annotation.Scope;
    import com.model.Contact;
    @Named("myBean")
    @Scope("view")
    public class MyBean extends BaseManagedBean {
    	private List<Contact> lstContact;
    
    	@PostConstruct
    	public void init() {
    		lstContact = new ArrayList<Contact>();
    		Contact obj1 = new Contact();
    		obj1.setStrSalutation("MR");
    		obj1.setStrFirstName("AAA");
    
    		Contact obj2 = new Contact();
    		obj2.setStrFirstName("BBB");
    		
    		Contact obj3 = new Contact();
    		obj3.setStrSalutation("MR");
    		obj3.setStrFirstName("CCC");
    		lstContact.add(obj1);
    		lstContact.add(obj2);
    		lstContact.add(obj3);
    	}
    	
    	public List<Contact> getLstContact() {
    		return lstContact;
    	}
    
    	public void setLstContact(List<Contact> lstContact) {
    		this.lstContact = lstContact;
    	}
    }

If I just enter 'X' in second column(First Name) filter and remove 'X' all values at first column (Salutation) are gone.

**Comment by Rapster** [comment]
Can you please provide a reproducer using https://github.com/primefaces/primefaces-test?

**Comment by melloware** [comment]
@gannulee Without a reproducer mentioned by @Rapster there is no way devs can help debug the problem.

**Comment by melloware** [comment]
Closing for now. Will re-open if OP provides reproducer.

**Comment by gannulee** [comment]
sure... Many thanks for your response, never tried this before, will check and get back very shortly...

**Comment by gannulee** [comment]
Please find attached code in the requested format...
[primefaces-test-master_6427.zip](https://github.com/primefaces/primefaces/files/5448680/primefaces-test-master_6427.zip)

**Comment by gannulee** [comment]
Please advice if I need to create a new issue as this ticket is already closed.

**Comment by melloware** [comment]
No I reopened this issue i will investigate your reproducer.

**Comment by melloware** [comment]
I have confirmed your issue.

**Comment by gannulee** [comment]
Many thanks for checking and necessary actions.

**Comment by Rapster** [comment]
A similar issue has been reported #6652, can you try it out with master?

**Comment by melloware** [comment]
I retested this with latest Master and its still broken. It also exposed a JS error which I just fixed.
![image](https://user-images.githubusercontent.com/4399574/101987812-5d9e8c80-3c64-11eb-846d-f63f8607ea20.png)

But it does not fix this issue it just prevents an error when `this.headers` is undefined.

**Comment by buunsal** [comment]
When I just tested it, I couldn't reproduce the issue with myfaces 2.2 or 2.3 versions. But when I tested it with mojarra, I was able to reproduce the issue. Could it be a mojarra issue?

**Comment by melloware** [comment]
I can confirm its working fine in MyFaces so this definitely is a Mojarra issue. 

In the past we report it to Mojarra with the reproducer and close the ticket like this one: https://github.com/eclipse-ee4j/mojarra/issues/4562

**Comment by tandraschko** [comment]
there could also be a very very small possibility that its a related to our own UIData which contains some mojarra code and it just works magically with MyFaces. But unlikely.
Most of the times the MyFaces algorithm is more stable.

**Comment by melloware** [comment]
@tandraschko so is it safe to close this ticket as I don't think there is anything we will fix besides your new 11.0 ticket to rip out Mojarra UI data? https://github.com/primefaces/primefaces/issues/6773

**Comment by christophs78** [comment]
https://github.com/eclipse-ee4j/mojarra/releases/tag/2.3.15 is available
