### ISSUE TITLE
jquery not defined PF 5.2 IE 11

### ISSUE THREAD

**Issue by janncors** [primefaces/primefaces#643]
Hello, I´m using PF 5.2, App Server Wildfly 9.0 Final and JSF 2.2.2. I've developed an web application using facelets templates. I've got many js scripts errors related when jquery when I've tried to render the application in IE11. Others browsers work fine (Mozilla, Opera and Chrome).

The following errors are showed by the IE debug console:
### Null reference of 'nodeType'  property:

SCRIPT5007: No se puede obtener la propiedad 'nodeType' de referencia nula o sin definir
Archivo: jquery.js.jsf, Línea: 25, Columna: 35277
### jQuery and $ not defined:

SCRIPT5009: 'jQuery' no está definido
Archivo: jquery-plugins.js.jsf, Línea: 5, Columna: 83
SCRIPT5009: '$' no está definido
Archivo: primefaces.js.jsf, Línea: 2, Columna: 400
SCRIPT5009: '$' no está definido
Archivo: index.jsf, Línea: 1, Columna: 1
SCRIPT5009: '$' no está definido
Archivo: index.jsf, Línea: 1, Columna: 1
### Error getting ui properties' elements:

SCRIPT5007: No se puede obtener la propiedad 'CommandButton' de referencia nula o sin definir
Archivo: primefaces.js.jsf, Línea: 1, Columna: 4440
SCRIPT5007: No se puede obtener la propiedad 'CommandButton' de referencia nula o sin definir
Archivo: primefaces.js.jsf, Línea: 1, Columna: 4440
SCRIPT5007: No se puede obtener la propiedad 'Menubar' de referencia nula o sin definir
Archivo: primefaces.js.jsf, Línea: 1, Columna: 4440
SCRIPT5007: No se puede establecer la propiedad 'cssText' de referencia nula o sin definir
Archivo: jquery.js.jsf, Línea: 25, Columna: 29703

Therefore primefaces components don't work property in IE 11 browser.
### Facelets default template:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions">
<h:head>
    <h:outputStylesheet name="css/screen.css" />
    <h:outputScript name="js/functions.js" />
    <link rel="shortcut icon" type="image/x-icon"
        href="#{request.contextPath}/resources/gfx/favicon.ico" />
    <f:facet name="first">
        <meta http-equiv="Content-Type" content="text/xhtml; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta http-equiv="Cache-Control" content="no-cache" />
        <meta http-equiv="Pragma" content="no-cache" />
        <title>Integración pagos PayU - Comunican</title>
    </f:facet>
</h:head>
<h:body>
    <div id="container">
        <div class="brand">
            <img src="resources/gfx/logo.png" />
        </div>
        <p:growl id="mensajes" />
.....
```

Best regards,
Jann Cortés
### Firefox:

![menu items ok firefox](https://cloud.githubusercontent.com/assets/13801132/9374070/f1b0ce28-46b6-11e5-9864-ccfac80c5c57.PNG)
![confirmation dialog ok firefox](https://cloud.githubusercontent.com/assets/13801132/9374071/f1b3b44e-46b6-11e5-97bb-38ec805bbe9e.PNG)
### IE 11:

![confirmation dialog not displayed ie11](https://cloud.githubusercontent.com/assets/13801132/9374073/f968a744-46b6-11e5-81b7-27371c91a4b8.PNG)
![menu items not displayed ie11](https://cloud.githubusercontent.com/assets/13801132/9374074/f996f1d0-46b6-11e5-8ba9-c2b4a499557e.PNG)

**Comment by cnsgithub** [comment]
Hi, i'm not from the PrimeFaces Team (just a user) , but I think it would be useful to have a fully runnable example to reproduce instead of a imcompete XHTML with a lot of proprietary stuff. then it would be easier to find the cause.

**Comment by tandraschko** [comment]
If you don't provide a complete maven project, i will close it as won't fix.
Our applications are working fine in IE11 - same as the showcase.

**Comment by janncors** [comment]
Hello, I´ve shared the complete project in dropbox:
[Maven project](https://www.dropbox.com/s/y47bv47bwud7nrz/payuintegration.rar?dl=0)

Thanks,

**Comment by cagataycivici** [comment]
I've reviewed the sample, looks ok, not sure what is wrong, try adding jquery manually;

{code}
<h:head>
<h:outputScript name="jquery/jquery.js" library="primefaces" />
{code}
