### ISSUE TITLE
DataExporter: Align cells based on column alignment

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6430]
**Description**
Another feature that PFE Exporter has that needs to be migrated is the ability to right, center, and left align cells in PDF and Excel exports.

See: https://www.primefaces.org/showcase-ext/sections/exporter/columnAlignments.jsf

Right now I don't like the way PFE does it assuming that your column is `<h:outputText>` and checking its styles.  It should check the `<p:column>` itself.

**Example XHTML**

If the column has a `style` containing the word "right" or a `styleClass` containing the word "right" then right align the cell.

Using Style...
```xml
<p:column style="text-align:right"
```

Using styleClass...
```xml
<p:column styleClass="column-right"
```

**Comment by stolp** [comment]
Great improvement.
