### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

### ISSUE THREAD

**Issue by vitsin** [primefaces/primefaces#6431]
**Describe the defect**
when using p:selectOneMenu with p:ajax on another p:selectOneMenu, getting CSP error and second f:selectItems never get updated.

**Reproducer**
project to reproduce the issue:
[jsf22.pf8.zip](https://github.com/primefaces/primefaces/files/5409102/jsf22.pf8.zip)

**Environment:**
 - PF Version: 8.0.4
 - JSF 2.2: Mojarra 2.3.24
 - Affected browsers: Chrome, Firefox, MS Edge
 - Spring Boot v2.3.2.RELEASE
 - Spring v5.2.9.RELEASE
 - Spring Security is disabled

**To Reproduce**
1. Go to http://localhost:8080/ui/home
2. Click on Country value
3. See error ![CSP error](https://user-images.githubusercontent.com/33527522/96595289-81bf9c00-12b9-11eb-949d-bf70a37df11b.png)

**Expected behavior**
Second f:selectItems (City) should show new values, but nothing get updated.

**Comment by melloware** [comment]
Can't reproduce:
[pf-6431.zip](https://github.com/primefaces/primefaces/files/5409751/pf-6431.zip)

Run `mvn clean jetty:run` and navigate to: http://localhost:8080/primefaces-test/test.xhtml

CSP is working fine with the example.  Its using just JSF 2.2, Mojarra, and PF and takes Spring out of the equation.

**Comment by melloware** [comment]
You could compare my View Source of the HTML page to compare to your version to see what is different.

**Comment by vitsin** [comment]
thanks, so is it JoinFaces or Spring guys should I go with this issue than ?

**Comment by melloware** [comment]
No I would first run my demo and right click in the Browser and do "View Source" and save it as HTML.  then I would do the same with your project and see what in the HTML or JS is different to narrow it down.  

But yes its safe to say its not a PrimeFaces issue as far as I can reproduce.

**Comment by vitsin** [comment]
no luck with jetty with your pom.xml: "Plugin could not be resolved".

Here is attached for your review View Source HTML for my original project page under Spring:
[jsf22pf8.selectonemenu.html.zip](https://github.com/primefaces/primefaces/files/5410813/jsf22pf8.selectonemenu.html.zip)

**Comment by melloware** [comment]
It looks like something is wrong and you maybe have Multiple PF JARs in your classpath?

Your HTML:
```
http://localhost:8080/ui/javax.faces.resource/jquery/jquery.js?ln=primefaces&amp;v=8.0.4&amp;v=8.0.4&amp;v=8.0.4
```

My HTML:
```
http://localhost:8080/primefaces-test/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&amp;v=8.0
```

See how yours has the version 8.0.4 appended 3 times?  That is definitely not right.

**Comment by melloware** [comment]
And your "Plugin could not be resolved". is because you are using an in house Maven resolver?  That should work fine as that Plugin is available in Maven Central.

**Comment by melloware** [comment]
Also you are using `p:layout` which has been removed for PF 9.0 so I would not use it.
https://github.com/primefaces/primefaces/issues/2168

**Comment by vitsin** [comment]
thanks for your help,
1.p:layout - will remove
2."in house Maven resolver?" - not at all, my pom.xml is attached to original issue project, would love to if you can help me with it.
3."See how yours has the version 8.0.4 appended 3 times?" - yes, its because I had primefaces-8.0.4.jar, primefaces-8.0.4-javadoc.jar and primefaces-8.0.4-sources.jar assigned to project from user lib. 
Once removed, the PF v8.0 is now in use from JoinFaces.

Unfortunatelly, even with PF v8.0 I m keep getting same error, pls see View Source.
[jsf22pf8.selectonemenu.002.html.zip](https://github.com/primefaces/primefaces/files/5411077/jsf22pf8.selectonemenu.002.html.zip)

**Comment by melloware** [comment]
I can't run your project with `mvn spring-boot:run` it fails with...
```
Caused by: java.lang.ClassNotFoundException: jsf23.jsf23.App
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.727 s
[INFO] Finished at: 2020-10-20T15:33:03-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.2.RELEASE:run (default-cli) on project jsf23: Application finished with exit code: 1 -> [Help 1]
[ERROR]
```

**Comment by vitsin** [comment]
[jsf22.pf8.zip](https://github.com/primefaces/primefaces/files/5411113/jsf22.pf8.zip)
sorry about that, here it goes.

**Comment by melloware** [comment]
OK I am running your project and when I watch the Network traffic with F12 in Chrome.

I see every one of your AJAX reuqests doing a POST and getting a 302 redirect and then a GET. And look at the output of your get.
```xml
<partial-response><changes><update id="j_id1:javax.faces.ViewState:0"><![CDATA[e1s1]]></update><eval><![CDATA[PrimeFaces.csp.init('NmNkOGE3ZDUtZmM4Ny00M2Q4LTllNTMtMGEyOWI4NTA5NmUy');;]]></eval></changes></partial-response>
```

See how ViewState is `e1s1` that is wrong that is the value on your URl?

Something is seriosuly wrong with all of the filtering or magic going on here.  here is what the proper AJAX response should looks like
```xml
<?xml version='1.0' encoding='utf-8'?>
<partial-response id="j_id1"><changes><update id="frmTest:city"><![CDATA[<div id="frmTest:city" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all" aria-owns="frmTest:city_panel" style="width:150px" role="combobox" aria-haspopup="listbox" aria-expanded="false"><div class="ui-helper-hidden-accessible"><input id="frmTest:city_focus" name="frmTest:city_focus" type="text" autocomplete="off" aria-labelledby="frmTest:j_idt17" /></div><div class="ui-helper-hidden-accessible"><select id="frmTest:city_input" name="frmTest:city_input" tabindex="-1" aria-hidden="true"><option value="" data-escape="true">Select City</option><option value="Rio de Janerio" data-escape="true">Rio de Janerio</option><option value="Salvador" data-escape="true">Salvador</option><option value="Sao Paulo" data-escape="true">Sao Paulo</option></select></div><label id="frmTest:city_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label><div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div><div id="frmTest:city_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="frmTest:city_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-noselection-option" data-label="Select City" tabindex="-1" role="option">Select City</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="Rio de Janerio" tabindex="-1" role="option">Rio de Janerio</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="Salvador" tabindex="-1" role="option">Salvador</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="Sao Paulo" tabindex="-1" role="option">Sao Paulo</li></ul></div></div></div><script id="frmTest:city_s" type="text/javascript" nonce="MDZmMDAyNTMtYmY2Ni00NzMzLThlNDYtNzQ4MTdlMzc2MmZk">PrimeFaces.cw("SelectOneMenu","widget_frmTest_city",{id:"frmTest:city",appendTo:"@(body)"});</script>]]></update><update id="j_id1:javax.faces.ViewState:0"><![CDATA[458081516138038683:-5036955922754820965]]></update><eval><![CDATA[PrimeFaces.csp.init('MDZmMDAyNTMtYmY2Ni00NzMzLThlNDYtNzQ4MTdlMzc2MmZk');;]]></eval></changes></partial-response>
```

Notice my `<update id="j_id1:javax.faces.ViewState:0"><![CDATA[458081516138038683:-5036955922754820965]]></update>`

I think you need to peel back a bunch of layers on this JoinFaces project.  I use JoinFaces but I don't have any of these issues.

**Comment by vitsin** [comment]
sounds like rewrite-spring-boot-starter will require some rule to prevent such redirect. Thank you, I'll keep posted once figured it out.

**Comment by melloware** [comment]
OK thanks I think Spring Flow might be the culprit.  I do not use that in Any of my Joinfaces projects and I do use Rewrite URL.

**Comment by vitsin** [comment]
no Spring Flow? so what is your replacement than?

**Comment by melloware** [comment]
I don't know what spring flow does but I built a large joinfaces project without it.  I followed the joinfaces-example project on how to layout and do a joinfaces project. I highly recommend you do the same.
