### ISSUE TITLE
Github Actions CI: run Sonar Cloud only for primefaces/primefaces

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6433]
Currently it´s also executed for master-branch of forks / clones. (And does not work there.)
https://forum.primefaces.org/viewtopic.php?f=3&t=63854

**Comment by melloware** [comment]
I think you can make the line:
```
if: github.repository =='primefaces/primefaces' && github.ref == 'refs/heads/master' && matrix.java == 11
```

**Comment by christophs78** [comment]
Yep. PR incoming. :-)
