### ISSUE TITLE
Frozen columns mismatch of header and rows and other various issues with it

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#644]
Hi, since the day this feature is in PrimeFaces it has been almost unusable for me due to some very annoying bugs. I have created a basic test case where you can see the major flaws about this component. Please try to fix it in the PF code. Any CSS or JS workaround is not a real option because it would basically make this component very hard to re-use.

So, here are the issues: 
1. If any row on the scrollable part is bigger than the rows on the fixed/frozen part, they become misaliged
2. If any header row on the scrollable part is bigger than the header on the fixed part, they become misaliged. This is not only caused by using the facet , but also by PF features like the filter
3. Frozen/Scrollable part are always set to 50% width. It would be better to have the frozen part be of dynamic width, based on the content. 
4. When using a fixed with for a specific column, the paginator will stay at the current datatable width, resulting in the datatable content being wider than the paginator

Hope this can be addressed in a future Elite version. thanks

XHTML/Facelet:   http://pastie.org/pastes/10363243/text?key=8fj0fpv0okvvrooowgsrcg
Bean:  http://pastie.org/pastes/10363249/text?key=o5yyldxy22xsj3ne9prmea
Classes used in Bean: http://pastie.org/pastes/10363251/text?key=uaz3tc6zupytrxfbbsjueg

Environment: Primefaces Elite 5.2.10 @ Mojarra 2.2.11 @ WildFly 9.0.1

![bugpf](https://cloud.githubusercontent.com/assets/13161711/9377227/24d32d68-4717-11e5-9ab6-64aaff100d36.png)

**Comment by kukel** [comment]
1 and 2: identical issues. Very hard to fix since you have to read the size of each row and apply it to the frozen one **or vice-versa**. Using css to e.g. get 'overflow' instead of wrapping etc is a better and way easier 'fix' that we apply to. 

3: afaics in the showcase, there is no 50% specified. It is the default due to css that is applied to the table (table-layout: fixed iirc). Providing an explicit width for a  column and applying the width for the left and right part (see the css in the showcase) will 'fix' this

```
.ui-datatable-frozenlayout-left {
    width: 5%;
}
```

4 is a bug... and I think I remember an issue  being reported for this, but I cannot find it.

**Comment by cnsgithub** [comment]
About 1 + 2. I think it should be possible to fix it, cant be too hard - please try ;-) overflow is not an option as it hides important info. Ill post my workaround for the header but i don't want to use this in each data-table i need. Its almost more JS code inside the Facelet file than actual Facelets. Maybe it can be adapted it to work for rows too.

//get jsf element by using the id part 
 function getJSFElementById(id){
  return $("[id$='"+id+"']")[0];
 }

//id of the p:datatable
tableGrid = getJSFElementById('my-table-grid')
    columnHeaders = $(tableGrid).find('[role=\'columnheader\']');

```
       biggestHeight = 0;
            for (var i = 0; i < columnHeaders.length; i++) {
                    if(biggestHeight < columnHeaders[i].offsetHeight){
                        //console.log(columnHeaders[i].offsetHeight);
                        biggestHeight = columnHeaders[i].offsetHeight;
                    }
                }
                for (var i = 0; i < columnHeaders.length; i++) {
                     columnHeaders[i].height = biggestHeight + "px";
                }
```
1. As you said this can be done with an easy CSS workaround, when you know the size of the left part, but especially when the content is dynamic, i have to use dirty JS hacks too to set the correct width..

Hope this helps...

**Comment by cagataycivici** [comment]
We've tried matching heights with javascript before many times and it is never pixel perfect, also can't do something like this if you have grouping. Well known working workaround is adding a placeholder with visibility hidden to duplicate content so headers match;

``` xml
<p:dataTable var="car" value="#{dtScrollView.cars5}" scrollable="true" scrollHeight="150" scrollWidth="300" frozenColumns="1" paginator="true" rows="10">
                <p:column footerText="Id">
                    <f:facet name="header">
                        Id
                        <p:commandButton type="button" value="XXX" style="visibility: hidden"/>
                    </f:facet>
                    <h:outputText value="#{car.id}" />
                </p:column>
                <p:column footerText="Year">
                    <f:facet name="header">
                        <p:commandButton type="button" value="XXX"/>
                    </f:facet>
                    <h:outputText value="#{car.year}" />
                </p:column>
                <p:column headerText="Brand" footerText="Brand">
                    <h:outputText value="#{car.brand}" />
                </p:column>
                <p:column headerText="Color" footerText="Color">
                    <h:outputText value="#{car.color}" />
                </p:column>
            </p:dataTable>
```

3) Can be changed with css.

4) Can't replicate.

**Comment by cnsgithub** [comment]
Hi, closing this without any action basically means for 90% of sample data or just if you add a column with an image on the right side - the fixed-column-feature is not usable without hacking in things via js / css or hidden elements? 

Also what does it mean - we've tried and it never is pixel perfect. I've posted a solution and it is pixel perfect in Chrome, FF and IE. For you it should be even easier because you don't have to grab the elements via selectors.  And besides: 1-2 pixel off would still be better than 50 pixel off ;-) 

The same should be possible for the rows (actually this is even more important, as you said, for the header there are other reasonable solutions) After the table has been rendered, there is no reason why you cant grab all heights, get the biggest one of each row and adapt the others

Code for replicating issue No. 4: (using the same bean as posted originally)
Please not i have hard-coded every column with to 80px, in a real world scenario the widths would come from the bean to make each text fit into a cell (since the table doesnt do this by its own).

Also this code example shows how the fix i proposed is pixel perfect for the headers.. 

Also here is a screenshot showing that issue No.4 (and the whole table) does not behave the same in all browsers actually in IE11 it seems to be ok. 

If you need a running *.war file i can upload it too. 

http://abload.de/img/ieff-chromee5jzz.png

```


       <h3>Frozen Columns</h3>

    <p:dataTable id="frozencoltable" var="car" style="width: 900px;"  paginator="true" paginatorPosition="both" rowsPerPageTemplate="5,10,15"
    paginatorTemplate="{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" paginatorAlwaysVisible="true" rows="10"
value="#{dtScrollView.cars5}" scrollable="true"  frozenColumns="2"   scrollWidth="400px">

        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Year" footerText="Year" >
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Brand" footerText="Brand" >
            <h:outputText value="#{car.brand}" />
        </p:column>
        <p:column headerText="Color" footerText="Color" >
            <h:outputText value="#{car.color}" />
        </p:column>
        <p:column headerText="Color" footerText="Color"  >
                <f:facet name="header">
                            <h:panelGroup >
                                <h:outputText value="weight" />
                                <br />
                                <h:outputText value="in"   />
                                <br />
                                <h:outputText value="[kg]" />
                            </h:panelGroup>
                    </f:facet>
            <h:outputText value="#{car.color}" />
        </p:column>
           <p:column headerText="Color" footerText="Color" style="width: 80px;">
            <h:outputText value="#{car.color}" />
        </p:column>
          <p:column headerText="Color" footerText="Color"   style="width: 80px;">
            <h:outputText value="#{car.color}" />
             <h:outputText value="additional info" />
        </p:column>
            <p:column headerText="Color" footerText="Color" style="width: 80px;">
            <h:outputText value="#{car.color}" />
        </p:column>
            <p:column headerText="Color" footerText="Color" style="width: 80px;">
            <h:outputText value="#{car.color}" />
        </p:column>
               <p:column headerText="Color" footerText="Color" style="width: 80px;">
            <h:outputText value="#{car.color}" />
        </p:column>
               <p:column headerText="Color" footerText="Color" style="width: 80px;">
            <h:outputText value="#{car.color}" />
        </p:column>
               <p:column headerText="Color" footerText="Color" style="width: 80px;">
            <h:outputText value="#{car.color}" />
        </p:column>
               <p:column headerText="Color" footerText="Color" style="width: 80px;">
            <h:outputText value="#{car.color}" />
        </p:column>
    </p:dataTable>

    <script type="text/javascript">
    //<![CDATA[
    //fix header heights

                var delayFunct = (  function() {
     var timer = 0;
     return function(callback, ms) {
         clearTimeout (timer);
         timer = setTimeout(callback, ms);
     };
 })();

                function getJSFElementById(id){
                      return $("[id$='"+id+"']")[0];
                     }

               delayFunct(  function() {  

                    tableGrid = getJSFElementById('frozencoltable')
                    columnHeaders = $(tableGrid).find('[role=\'columnheader\']');

                    biggestHeight = 0;
                    for (var i = 0; i < columnHeaders.length; i++) {
                        if(biggestHeight < columnHeaders[i].offsetHeight){
                            //console.log(columnHeaders[i].offsetHeight);
                            biggestHeight = columnHeaders[i].offsetHeight;
                        }
                    }
                    for (var i = 0; i < columnHeaders.length; i++) {
                         columnHeaders[i].height = biggestHeight + "px";
                    }

               }, 15);

            //]]>   
               </script>     

```

**Comment by cagataycivici** [comment]
Please do a pull request and we'll review.

**Comment by walllzzz** [comment]
Is it fixed ? or not yet ?
