### ISSUE TITLE
InputNumber: Open numerical keyboard default on touch devices

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#6442]
**Description**
The inputNumber component default opens an alphabetic keyboard on touch devices even though it only permits numerical input.

**Describe the solution you would like**
The inputNumber component should default open a numerical keyboard

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

**Comment by tandraschko** [comment]
Doesnt work, as suffix and prefix wouldnt be supported.
Just use a Input type=number then

**Comment by melloware** [comment]
Another option is to see the PFE Calculator example here:
https://www.primefaces.org/showcase-ext/sections/calculator/basicUsage.jsf

it opens up a keypad on InputNumber and it allows prefix and suffix.

**Comment by melloware** [comment]
Also from AutoNumerics docs:

> "Tips:
> Since the number type is not supported, if you want to display a numeric keyboard when selecting an AutoNumeric-managed element in a mobile browser, you can use the input tel type.
> 
> In the future, you'll be able to add the inputmode="numeric" Html attribute in order to achieve the same effect."

So try this..
```xml
<p:inputNumber id="input1" value="#{inputNumberView.input1}" type="tel">  
```

**Comment by pfumi** [comment]
The solution type="tel" does indeed work. The best solution would be of course to use the "inputMode" attribute. If you decide to add it, can it be pushed to 8.0.5 release aswell?

**Comment by melloware** [comment]
You can review my PR.  If it gets approved it will be for 9.0 and up to @mertsincan to merge for 8.0.5 ELITE.

**Comment by melloware** [comment]
@pfumi you can also do this...
```xml
xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"

<p:inputNumber id="input1" value="#{inputNumberView.input1}" pt:inputmode="numeric">  
```

**Comment by pfumi** [comment]
Perfect, I didn't even consider that. Thanks
