### ISSUE TITLE
DatePicker: Race-Condition between input-event and mask support

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#6445]
**Environment:**
 - PF Version: _9.0-SNAPSHOT_
 - Affected browsers: _ALL_

**To Reproduce**
1. Select date or enter it manually (do not press any key, after the component accepted the date)
2. Select the whole date using the mouse (not Ctrl+A or similar)
3. Press backspace / delete to clear the input
4. The datepicker won't update it's model

**Expected behavior**
Model of the datepicker should be updated to empty value.

**Root cause and solution**
The problem is caused by the inputmask library. It caches the backspace key to clear the field. It then triggers the `input` event. The `onUserInput` function of the datepicker won't process that `input` event, because it misses the previous `keydown` event (early out because of an IE11 fix). The `keydown` event will be handled after the `input` event.

The solution is quite simple: Move `this.applyMask()`  to the end of the `init` method or at least after `this.jq.datePicker(this.cfg);`. The event callbacks will be reordered so that the datepicker will process the `keydown` event before the inputmask library will do it.

**Example XHTML**
```html
<h:form id="frmTest">
  <p:datePicker widgetVar="dp" mask="true" pattern="yyyy-MM" view="month" />
</h:form>
```
**Example Javascript (DevTools)**
```js
console.log(PF('dp').getDate());
```

**Comment by fanste** [comment]
PR #6446

**Comment by melloware** [comment]
Great explanation and debugging. Thanks for the fix!

**Comment by melloware** [comment]
@fanste I think we have a similar issue now with the onchange event. See: https://github.com/primefaces/primefaces/issues/7176
