### ISSUE TITLE
InputNumber: Not working anymore as expected

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6453]
@melloware With the change from Oct 22, 2020, p:inputNumber is not working as expected anymore. 

The problem is caused by line 141 of the class InputNumberRenderer

        String defaultDecimalPlaces = "2";

decimalPlaces should not be set to 2 by default. I know that autonumeric does that, too. But this is simply too restrictive and only useful for "money" numeric data. The PF solution so far was good  because it allowed to use p:inputNumber also for cases where you cannot set the decimalPlaces by default to a specific value.

Using the following line instead would allow continue using p:inputNumber as it was before:

        String defaultDecimalPlaces = inputNumber.getDecimalPlaces();

Could you please check this and apply it if it has no negative side effects.

**Comment by melloware** [comment]
good catch, i was storing the calculated default DecimalPlaces and I should not have been.

**Comment by tuerker** [comment]
Thanks for the very quick fix.

**Comment by tuerker** [comment]
However, something else must have been changed, too, for p:inputNumber which works differently than before. 

When i used p_inputNumber on a BigDecimal or Double attribute, the values were not padded before. For example, when i entered 12 for a BigDecimal field, then 12 was stored in the corresponding database table column. now, however, 12.0000000... is stored. Maybe you know immediately what might have caused this?

**Comment by melloware** [comment]
That is this fix made by PrimeTek and requested by a PRO user how it used to work before: https://github.com/primefaces/primefaces/issues/6387

**Comment by tuerker** [comment]
This is not nice. We have use cases for p:inputNumber with decimalPlaces up to 32. This will blowup all the screens, especially the batch edit table screens such that the numbers will not be readable anymore, even if only one of thousand values actually use some part of the precision.

Do you have an idea how to circumvent this?

**Comment by melloware** [comment]
Yep just MonkeyPatch it by adding this JS to your code.
```javascript
PrimeFaces.widget.InputNumber.prototype.getValue = function() {
    return this.autonumeric.getNumericString();
};
```

**Comment by tuerker** [comment]
where should i place this code such that it has to be done only once for the my entire code?

**Comment by melloware** [comment]
so I a assume you have an `application.js` file you load in your template that gets loaded on all pages right?  Just add it there and it makes it effective for all InputNumbers on every page you load.

**Comment by tuerker** [comment]
ok. i will try. many thanks again for your great responsiveness.

**Comment by melloware** [comment]
Sorry to be safe its..
```javascript
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.getValue = function() {
        return this.autonumeric.getNumericString();
    }
};
```

So it works on pages where you are not even using an InputNumber.

**Comment by tuerker** [comment]
many thanks. this works!
