### ISSUE TITLE
InputMask: optional part does now work correctly

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6469]
@melloware with the change from the april to latest snapshot, p:inputMask is not working anymore correctly at least for mask with optional cases.

example:

            <p:inputMask
              value="#{user.phoneNumber.areaCode}"
              mask="9[999]"
              size="4" />

previously it was working well as follows:

            <p:inputMask
              value="#{user.phoneNumber.areaCode}"
              mask="9?999"
              size="4" />

can you please check and fix this.

when i try to save, it clears the inputMask fields (see screenshot)

![Screenshot from 2020-11-02 13-33-45](https://user-images.githubusercontent.com/10051373/97868587-42109f80-1d10-11eb-974f-48f9f6233545.png)

**Comment by tandraschko** [comment]
Please always check the migration guide before you create a ticket ;) https://primefaces.github.io/primefaces/9_0/#/../migrationguide/9_0

sorry, only checked the last example :D

**Comment by melloware** [comment]
I will look into this but we moved to a new component as the previous InputMask had so many bugs including problems with `?` as the optional character.

**Comment by melloware** [comment]
To fix it right now add `validateMask="false"` which turns off the server side validation which is where its failing.  I have to look at how the server side regex is being translated and fix it.

**Comment by tuerker** [comment]
validate="false" does not solve it. if i enter 44 for the areacode this is translated to 44__ such that the folloowing error is thrown:

'44__' must be a number between -2147483648 and 2147483647 Example: 9346

**Comment by tuerker** [comment]
this is because error is of course due to the fact that areaCode should be an integer here!

**Comment by tuerker** [comment]
using                

slotChar=""

is a partial workaround which works in our case because we do not have case where two or more digits are required at least.

this should give you also a hint for the bugfix.

**Comment by tuerker** [comment]
you have to clear the slotChars before doing the validation

**Comment by melloware** [comment]
I have a fix. working on it now and writing and integration test.

**Comment by melloware** [comment]
Integration Test; https://github.com/primefaces-extensions/primefaces-integration-tests/commit/147341e414c61e0db84b70ad9c3af578735d0688
