### ISSUE TITLE
InputNumber: Default decimalPlaces="0" for null integer

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6475]
@melloware : there is still a bug in p:inputNumber of the latest snapshot.

when p:inputnumber is invoked on an integer/long field which is null at the beginning, the entered integer value is changed to a decimal. 

here is the reproducer: with 3 cases: 
1) working when integer field is initialized with a non-null value
2) working when integer field is initialized null but an additional "decimalPlaces="0" ist used, which should not be needed to be used
3) not working correctly when integer field is initialized null

[p-inputNumber.zip](https://github.com/primefaces/primefaces/files/5481609/p-inputNumber.zip)

**Comment by melloware** [comment]
This is not a bug. This is how Java works.
See: https://stackoverflow.com/a/2950415/502366

```java
if (value instanceof Long || value instanceof Integer || value instanceof Short || value instanceof BigInteger) {
    defaultDecimalPlaces = "0";
}
```

If `value` is `NULL` it cannot be an `instanceof` anything so it evaluates to false and thus you get the default `2` decimalPlaces.

**Comment by tuerker** [comment]
you are right!

**Comment by tuerker** [comment]
so we then have to use always decimalPlaces:="0" for all integer/long fields.

**Comment by melloware** [comment]
If you plan on them being null yes you need to explicitly declare decimalPlaces="0".  There is no way around it.

**Comment by tuerker** [comment]
thanks.

**Comment by tuerker** [comment]
maybe be you can a short note in the documentation that one must use the attribute decimalPlaces="0" in case of long/integer/short/biginteger fields when the field is not initialized with a non-null value.

**Comment by melloware** [comment]
Docs updated: https://github.com/primefaces/primefaces/blob/master/docs/9_0/components/inputnumber.md
