### ISSUE TITLE
BreadCrumb: option to only render the last n items

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6478]
We have an application where you can select an item from a list, see details of the item, select a child (ManyToOne) and basically recurse until no childs are available anymore. The path is shown in a breadcrumb, which can get very long:

<img width="513" alt="Screen Shot 2020-11-04 at 16 30 12" src="https://user-images.githubusercontent.com/7500178/98131776-e6831500-1ebb-11eb-93d5-9426efb563e0.png">

So I think it would be a good addition to have an attribute to only render the last n items.

And then maybe options to show the root or not and to go up a level, so you can end up with something like

root / .. / item 5 / item 6 / item 7

or

.. / item 5 / item 6 / item 7

or

item 5 / item 6 / item 7

**Comment by melloware** [comment]
I love this idea.  Its a UI paradigm seen with breadcrumbs

**Comment by jepsar** [comment]
@melloware alright, you can assign me to this issue if you like.

**Comment by Rapster** [comment]
My 2 cents, but what about trying to find a middle ground? With this ticket, either you display the whole thing or just the last item, but about minimizing the lost of items. See this example: https://www.jqueryscript.net/demo/jQuery-Plugin-To-Create-Fully-Responsive-Breadcrumbs-asBreadcrumbs/

**Comment by jepsar** [comment]
@Rapster I like the idea of a responsive breadcrumb! But, I don't think we can use that library (I believe PrimeTek is moving away from jQuery UI based libraries and replacing them with in house versions). Even, if we could, it would mean that we will need a new UI element and styling for navigating to the hidden items. Although I think that could be an overlay panel with a menu.

I do want to have a look at it, but I feel that it's more of a new component to first play around with in PrimeFaces Extensions.

For now I'd like to stick to adding a fixed limit at the PrimeFaces side.

**Comment by tandraschko** [comment]
we can add a fixed limit attr but we should also make it responsive in future.

**Comment by mertsincan** [comment]
Hi all,
The best solution is to create a responsive breadcrumb. For now, users can use the rendered="false" property of p: menuitem Or they can hide items with CSS.

We can continue to discuss;
https://github.com/primefaces/primefaces/issues/6480
