### ISSUE TITLE
Carousel: customize dropdownTemplate using var attribute

### ISSUE THREAD

**Issue by clebersa** [primefaces/primefaces#6483]
According to the [documentation][1] of the Carousel component, there is a `dropdownTemplate` that can be used to customize the dropdown options text to select which slide to go to. However, the documentation does not provide an example of how that template can be customized using the `var` attribute of the carousel. I could not find an example on the Web as well.

The only available variable for the dropdown template seems to be `page`. I am looking for a way to use the `var` attribute of the Carousel to customize the dropdown text. Something like:

    <p:carousel value="#{bean.users}"
                var="user"
                pageLinks="0"
                dropdownTemplate="#{user.name}"
                ...
                >
    ...
    </p:carousel>

I also tried calling a javascript function in the `dropdownTemplate`, but that did not work. Calling the bean is an option, but how to pass the `page` parameter to the bean function?

I can update the select dropdown using javascript after the carousel loads, but I was wondering if there is a more elegant solution to the problem.

Thanks in advance.

  [1]: https://primefaces.github.io/primefaces/8_0/#/components/carousel

**Comment by melloware** [comment]
I am pretty sure you cannot  use the `var` attribute in the paginator.

Default value: `{page}`

the template replaces {page} with the actual page number. So if you made the template `dropdownTemplate="Page {page}"`

You would see it print out Page 1, Page 2 etc.

**Comment by melloware** [comment]
Since I don't think there is any action here and the question has been answered going to close this ticket.  Can re-open if there is any action item.
