### ISSUE TITLE
Sheet: move from extensions to core?

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6484]
The pe:sheet component of the primeface extensions package is very useful. It would be great if this component would be in the primefaces core package (just to avoid to maintain yet another dependency, especially when working on snapshots). Are there any intentions to move this component from the extensions to core?

**Comment by tandraschko** [comment]
nope as we stuck with a old sheet version. Its fine in extensions.

https://github.com/primefaces-extensions/primefaces-extensions/issues/152

**Comment by melloware** [comment]
@tuerker for more info see this ticket: https://github.com/primefaces-extensions/primefaces-extensions/issues/152
