### ISSUE TITLE
Schedule: JS error when only one slot per day is configured

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6485]
@melloware: Whenever the schedule is used with one slot per day, as show in the example in the screenshot below, the schedule crashes and becomes unusable.

Version: Latest Snapshot

It looks like that the bug is probably caused by fullcalendar. In any case, it must be fixed. Could you please have a look at that.

![Screenshot from 2020-11-06 11-30-46](https://user-images.githubusercontent.com/10051373/98357051-e0f50e80-2024-11eb-925e-d2142cbe39c7.png)

**Comment by tuerker** [comment]
below is the reproducer. just open inspect console and click on week or day view.

[p-schedule.zip](https://github.com/primefaces/primefaces/files/5500823/p-schedule.zip)

![Screenshot from 2020-11-06 11-55-56](https://user-images.githubusercontent.com/10051373/98358488-13077000-2027-11eb-895f-25770375f1a3.png)

**Comment by melloware** [comment]
Yep I would create a FullCalendar bug and reproducer there using JSFiddle so the devs can see the problem: https://github.com/fullcalendar/fullcalendar/issues

Nothing for PF to fix or hack here as its in the core of FullCalendar.

**Comment by tuerker** [comment]
thanks. i have now created an issue on fullcalendar. https://github.com/fullcalendar/fullcalendar/issues/5952.

would be good if you support this since this is a must-fix bug.

**Comment by melloware** [comment]
I am monitoring that ticket and if they fix it I will upgrade FullCalendar here.

**Comment by tuerker** [comment]
@melloware unfortunately this issue is still not fully solved. fullcalendar has another bug. see my comment in:

https://github.com/fullcalendar/fullcalendar/issues/5952

so it would be good to reopen this issue to monitor it. thanks and regards.

**Comment by melloware** [comment]
I am monitoring the issue. Will leave this closed for now since its a FullCalendar bug.

**Comment by tuerker** [comment]
@melloware this issue is actually fixed. i must have been ony a "older" snapshot where the full calendar fix not yet included. i move d now to `<version.primefaces>10.0.0-rc.1</version.primefaces>`. there the problem is gone.

**Comment by tuerker** [comment]
@melloware i wanted to apply my reproducer above to that version 10.0.0-rc.1. however, i am getting following error. so something must have changed here?


```
URI: | /primefaces-test/
-- | --
500
javax.servlet.ServletException: javax.servlet.ServletException: Error loading css, cannot find "theme.css" resource of "primefaces-omega" library
default
javax.servlet.ServletException: javax.servlet.ServletException: Error loading css, cannot find "theme.css" resource of "primefaces-omega" library
javax.servlet.ServletException: Error loading css, cannot find "theme.css" resource of "primefaces-omega" library
javax.faces.FacesException: Error loading css, cannot find "theme.css" resource of "primefaces-omega" library


```

**Comment by tandraschko** [comment]
omega has been removed, i will add it to the migration guide

**Comment by tandraschko** [comment]
and the correct version is "10.0.0-RC1"

**Comment by tuerker** [comment]
thanks for the hints. the primefaces pom.xml has the following entry from where i copied it:

`   <version>10.0.0-rc.1</version>`

**Comment by tuerker** [comment]
set theme to none and the reproducer works now again. many thanks again for your great responsiveness.

**Comment by tuerker** [comment]
@tandraschko i've seen that you have now changed the version to `10.0.0-SNAPSHOT`. it was `10.0-SNAPSHOT` before. it this change intended?

**Comment by tandraschko** [comment]
just check the history of pom.xml ;)

**Comment by tuerker** [comment]
i see. it was also changed last week.

**Comment by melloware** [comment]
Yep we are moving to semantic versioning. So 10.0.0 will be final release
