### ISSUE TITLE
Cropper not working on showcase

### ISSUE THREAD

**Issue by mukulraidutta** [primefaces/primefaces#6487]
Cropper not working in showcase
[PrimeFaces Showcase.pdf](https://github.com/primefaces/primefaces/files/5504546/PrimeFaces.Showcase.pdf)
https://www.primefaces.org/showcase/ui/multimedia/cropper.xhtml

When i click on crop button then error page in open
[PrimeFaces Showcase error.pdf](https://github.com/primefaces/primefaces/files/5504548/PrimeFaces.Showcase.error.pdf)
https://www.primefaces.org/showcase/error.xhtml

**Comment by melloware** [comment]
It works locally if you check the Showcase out of Git and run it.   I believe the issue is the server is out of disk space because it writes temp files.

**Comment by melloware** [comment]
You can report it here on Showcase Issue: https://github.com/primefaces/primefaces-showcase/issues
