### ISSUE TITLE
SelectRenderer: add fast path to doValidateSubmittedValues

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6490]
`SelectRenderer#doValidateSubmittedValues` eats up a good amount of CPU-cycles. Especially with explicit converter.
We can stop evaluating when `submittedValues.length == validSubmittedValues.size()`.

**Comment by melloware** [comment]
@christophs78 should this be closed now since you figured out your issues?

**Comment by christophs78** [comment]
Yes, i think we may close this.
There is still some optimization-potential, but no low-hanging fruit to do improvements without increasing code-complexity.
