### ISSUE TITLE
SelectRenderer: performance-regression since PF 7.0

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6492]
https://github.com/primefaces/primefaces/pull/3299 introduced SelectRenderer#restoreAndCheckDisabledSelectItems this was later renamed to SelectRenderer#validateSubmittedValues.

This iterates over all SelectItems and calls the converter for each of this items. This can cause major CPU-usage when eg SelectOneMenu contains a huge a amount of items and/or the converter is maybe a bit more complex.

Background:
My organisation uses a JSF/PrimeFaces - powered Covid-19-contact-tracing application. As Covid-19-infections raise in our country exponential the number of staff who use this application also raises to very high levels.
With this high level of concurrent users changes like https://github.com/primefaces/primefaces/pull/3299 do matter.

**Comment by melloware** [comment]
Maybe need a way of disabling the server side check like we do with some other components?

**Comment by christophs78** [comment]
Yep. 

Additional ideas:
- Only relevant with disabled items?
- Put allowed values during rendering into a HashSet. Put this HashSet into StateHelper. Reuse this during 'SelectRenderer#restoreAndCheckDisabledSelectItems'.
- Or use a String-Array instead of HashSet.

**Comment by tandraschko** [comment]
1) unsure
2,3) i dont like to put something in the state, which blows up sessionmemory.

we can also make it optional but why is your converter that slow? or how many items to do you have?

Another thing i like to ask if someone has performance critical apps... Do you use MyFaces 2.3-next? :D

**Comment by christophs78** [comment]
Currently we only have limited time to iterate over all possible changes / optimiziations...

MyFaces 2.3-next may help to increase base JSF-performance. It´s something we should look into mid- to long-term. But IMO it´s not a good a idea to switch a currently critical application (where we also have to add features, ...) from one day to another from Mojarra to MyFaces 2.3-next.
(But MyFaces 2.3-next IMO can´t compensate for not ideal application-design and/or PF-components with heavy footprint.)

Some of our SelectOneMenu´s have thousands of entries. One of our options is to move them to AutoComplete. Performance-wise this would IMO be a good idea. But it has a bit different behaviour. So not totally sure weather our users like this. But we may try to do this first.

Our generic converter has - the way it is used in this application - look weather the object is a proxied hibernate-object, ... One option may be to write specialized high-perf-converters. (Originaly we used Omnifaces SelectItemsIndexConverter. This one is absolute terribel when used for SelectOneMenu with a huge amount of SelectItems.)

As an enterprise-dev i don´t like the idea of totally disabling validation. (via an new attribute you explicit have to turn on)
Trading in memory-usage against cpu-usage would be a new attribute you explicit have to turn on.

**Comment by melloware** [comment]
I will say SelectOne is ideal for say 100 items or less.  I feel like if you have 1000+ options this is not the right control. Just what I have seen of UI over the years.  A lot of UX people do not like it.  So I would think AutoComplete might be the more efficient option in your use case

**Comment by tandraschko** [comment]
+1

i think we can apply changes here (like your shortcut, if it hasnt any downside) to optimize.
I would create a RequestScoped CDI bean, which implements a converter, which loads lazy all "relevant" items a single time. Its should be much faster then do a single request for each entry.

**Comment by tandraschko** [comment]
and about:

| As an enterprise-dev i don´t like the idea of totally disabling validation. (via an new attribute you explicit have to turn on)

we should make it enabled per default of course

**Comment by christophs78** [comment]
One - a bit off-topic - question regarding AutoComplete: Each time completeMethod need´s to be called triggers RestoreViewPhase of the whole XHTML? So for a (very) complex XHTML and high load this also causes significant CPU usage. Right?
Is there a solution to avoid this beside playing around with minQueryLength and queryDelay which compromises UX?

**Comment by tandraschko** [comment]
Yes, this is how JSF works. It could be that the AutoComplete component is inside a repeat or CC, which needs to be restored and visited to get the correct "context"
We could provide some integration for a JSON endpoint e.g.
this would avoid that

**Comment by christophs78** [comment]
I currently make our own custom PrimeFaces-build. After our changes are battle-tested i´l bring them back as PRs.

**Comment by melloware** [comment]
@christophs78 what is the status of this ticket?

**Comment by christophs78** [comment]
IMO our time and energy is invested better for other things. I don´t plan to work on this furher. At least for now.
Yes, there was a perf-regression with 7.0, but you could work around by using fast converters, avoid using SelectOneMenu for to many entries, ...
