### ISSUE TITLE
TypeError: $(...).zIndex is not a function

### ISSUE THREAD

**Issue by rainermueller** [primefaces/primefaces#6494]
**Describe the defect**
In a PF dialog the following error shows in the browser console

```
TypeError: $(...).zIndex is not a function
```

**Environment:**
 - PF Version: 7.0.14
 - JSF 2.3
 - Affected browsers: all

**Reason**
The `core.utils.js` Script function `preventTabbing` is using the removed function `zIndex()`

`zIndex()` was deprecated in jQuery UI v1.11 and removed in v1.12

**Comment by tandraschko** [comment]
The community does not maintain elite versions and it's fixed in trunk, so i will close it and ping PrimeTek.

@mertsincan we re-added the zIndex method as you can see in jquery.ui.pfextensions.js

**Comment by melloware** [comment]
@mertsincan  What is strange is that zIndex() has been in jquery.ui.pfextensions.js since 2017 so it should be in 7.0.14 unless it accidentally got removed.
