### ISSUE TITLE
Schedule: Locales not fully respected

### ISSUE THREAD

**Issue by sasynkamil** [primefaces/primefaces#6496]
All European locales have first day of the week Monday [[link](http://chartsbin.com/view/41671)]. But e.g. Norwegian is stariting by Sunday (søn.) in `p:schedule` component, which is wrong.

All, except EN schould be Mon:

| PF version | EN | DE | SV | NO |
|:------------|:-----| :-----|:-----|:-----|
| 8.0             | Sun | Mon | Mon | **Sun** |
| 8.0.2          | Sun | Mon | Mon | **Sun** |
| 8.0.5          | Sun | Mon | Mon | **Sun** |
| snapshot* | Sun | **Sun** | **Sun** | **Sun** |

(*) primefaces-master-6_1-gf9d6444-4838.jar

* FullCalendar demo is working correctly: https://fullcalendar.io/docs/locale-demo. E.g if I choose "nb" locale (nb - Norwegian Bokmål, nn - Norwegian Nynorsk), then week starts by  monday (man.).

* Setting of `p:schedule weekNumberCalculation` to "ISO" does not help, even if FullCalendar is saying "If weekNumberCalculation is set to 'ISO', this option defaults to 1 (Monday)".
https://fullcalendar.io/docs/firstDay

**XHTML**
```html
<p:schedule id="myCalendarId"
			view="agendaWeek"
			rightHeaderTemplate="false"
			value="#{scheduleController.eventModel}"
			locale="#{scheduleController.locale}"
			timeZone="#{scheduleController.timeZone}"
			clientTimeZone="#{scheduleController.clientTimeZone}"
			weekNumberCalculation="local"
			showWeekends="true"
			allDaySlot="false"
			aspectRatio="1.2"
			timeFormat="HH:mm">
</p:schedule>
```

**ScheduleController.java**
```java
private static final String clientTimeZone = "local";

private static final Locale LOCALE_EN_US = new Locale("en", "US");
private static final Locale LOCALE_DE_DE = new Locale("de", "DE");
private static final Locale LOCALE_SV_SE = new Locale("sv", "SE");
private static final Locale LOCALE_NO_NO = new Locale("no", "NO");

public static final ZoneId ZONE_ID_UTC = ZoneId.of("UTC");
public static final ZoneId ZONE_ID_BERLIN = ZoneId.of("Europe/Berlin");
public static final ZoneId ZONE_ID_STOCKHOLM = ZoneId.of("Europe/Stockholm");
public static final ZoneId ZONE_ID_OSLO = ZoneId.of("Europe/Oslo");
```

**Comment by melloware** [comment]
OK so I think the issue is your Locale of "NO".  Here are the FullCalendar Locales.
https://github.com/fullcalendar/fullcalendar/tree/master/packages/core/src/locales

For example here is Sweden: https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/locales/sv.ts and you can see `dayOfWeek=1`.

However there is no "no.js" file for Norwegian only "nb.js". So that is why you are getting the US English default of `dayOfWeek=0`.

However you can override this yourself by creating your own PF local in 9.0-SNAPSHOT, 8.0.5 as you can see here:
https://github.com/primefaces/primefaces/blob/f9d6444fbe5607d7fa748f2a6ed710199fdce896/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L96-L124

So I would suggest you open a ticket at FullCalendar.io and provide a PR for a Norwegian translation!

**Comment by melloware** [comment]
Or use Java Locale "nb" instead of "no". See: https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html

**Comment by sasynkamil** [comment]
Great and thank you @melloware - you pointed me to the right dirrection...

I. I found out that language "no" in locale is deprecated: "A locale with language "no", country "NO", and variant "NY", representing Norwegian Nynorsk (Norway), is converted to a language tag "nn-NO"."
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Locale.html

So the correct ones are:
```java
new Locale("nb", "NO");
new Locale("nn", "NO");
```
And both are included in FullCalendar (and both have set Monday as first day), also **I succesfully tested with PF 8.x,y versions**.
https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/locales/nb.ts
https://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/locales/nn.ts

So it means that `no.js` shouldn't be part of FullCalendar, since it is old/deprecated.

II. So leftover is why PF snapshot has Sunday as first week day for all (e.g. de, sv, nb, nn).

**Comment by melloware** [comment]
Let me look into that

**Comment by melloware** [comment]
@blutorange I can confirm this in the latest 9.0-SNAPSHOT it has stopped using locales even though I can see it loaded correctly and I call see the `FullCalendar.globalLocales` global locales has all the code.  Might need help investigating this.

**Comment by melloware** [comment]
I can confirm `PrimeFaces.widgets.myschedule.calendar.getAvailableLocaleCodes();` only contains English US.

![image](https://user-images.githubusercontent.com/4399574/98704871-25e1b380-234b-11eb-8c5d-f744295c343b.png)

**Comment by melloware** [comment]
OK I found the problem and fixed it.  the `locales` need to be added now for FullCalendar to be aware of them

![image](https://user-images.githubusercontent.com/4399574/98711076-832d3300-2352-11eb-9982-ff9fa7b2c098.png)

**Comment by melloware** [comment]
I added an Integration Test to our suite so this is caught in the future.

```java
    @Test
    @Order(4)
    @DisplayName("Schedule: GitHub #6496 locale switching")
    public void testLocales(Page page) {
        // Arrange
        assertButton(page, "fc-today-button", "Current Date");
        assertButton(page, "fc-dayGridMonth-button", "Month");
        assertButton(page, "fc-timeGridWeek-button", "Week");
        assertButton(page, "fc-timeGridDay-button", "Day");

        // Act
        page.buttonFrench.click();

        // Assert
        assertButton(page, "fc-today-button", "Aujourd'hui");
        assertButton(page, "fc-dayGridMonth-button", "Mois");
        assertButton(page, "fc-timeGridWeek-button", "Semaine");
        assertButton(page, "fc-timeGridDay-button", "Jour");
        assertConfiguration(page.schedule.getWidgetConfiguration());
    }
```

**Comment by blutorange** [comment]
@melloware Looks good. I originally tested switching locales and looking at the commit history, there was a change that probably broke it, so having a test for that is great.

**Comment by melloware** [comment]
Yep it looks like they changed this somewhere between 5.0 release and the 5.3 release because it definitely worked before.
