### ISSUE TITLE
DataTable: Add liveScroll event

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#65]
It would be useful creating new AJAX event in dataTable. This event will be fired on loading rows during live scrolling:

``xml
  <p:ajax event="liveScroll" listener="..."/>

```

This event is useful if some action on rows must be executed on client (some JavaScript), and because of live scrolling not all rows are loaded.
```

**Comment by ptrzyna** [comment]
This AJAX event could also be used to refresh the counts/position in the table during live scrolling:
Example: Footer could have something like the following: "Showing 10 through 50 of 105999 records."

**Comment by cagataycivici** [comment]
I agree.

**Comment by pdurbin** [comment]
Our use case for this event is explained at https://github.com/IQSS/dataverse/issues/2681 but to summarize, we are looking for a way to display the number of visible rows based on scrolling. Let's say there are 500 items and we display 25 at a time. We want to show "25 items" at the top when the page first loads and then "50 items" when the user scrolls to show 25 more. Then "75 items" etc., as the user continues to scroll.
