### ISSUE TITLE
Selection dataTable doesn't work when click on child of `td`

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#650]
Hi,
I found a bug when dataTable selectionMode is `single`. If the element of the column is an `input` and you click into it. The row is never selected.

I override the `onRowClick` of `dataTable` like that:

``` JavaScript
if ($(e.target).is("td:not(.ui-column-unselectable),span:not(.ui-c)") || $(e.target).parents("td").is("td:not(.ui-column-unselectable),span:not(.ui-c)")) {
...
}
```

I can do a pull request if my change is ok for you.

**Comment by cagataycivici** [comment]
It is by design, clickable components like inputs, buttons, links do not trigger row selection.
