### ISSUE TITLE
ColumnToggler: Toggling on columns after resizing others breaks table width

### ISSUE THREAD

**Issue by jthalmai** [primefaces/primefaces#6501]
**Describe the defect**
The issue happens when you use both resizableColumns="true" and a p:columnToggler in a dataTable.
As long as you only resize while all columns are visible, you can toggle columns and they will always be fitted to the table width. But when you toggle some columns off, resize some of the remaining ones, and show again the hidden ones, the columns are now wider than the table and a scrollbar appears.

**Environment:**
 - PF Version: _PrimeFaces 8.0-SNAPSHOT_
 - JSF + version: _Mojarra 2.3.13_
 - Affected browsers: _tested on Chrome and Firefox_

**To Reproduce**
I used the DataTable - Resize example from the showcase and added a columnToggler like shown in the example xhtml.
1. Use the column toggler to hide one or more columns.
2. Resize the remaining columns.
3. Use the column toggler to show all columns again.
4. See columns getting too wide and scrollbar appear.

**Expected behavior**
The column widths should be fit to the table width as the default resizeMode of the dataTable suggests.

**Example XHTML**
```html
<f:facet name="header">
    Basic Resize with toggler
    <p:commandButton id="toggler" type="button" value="Columns" icon="pi pi-align-justify"/>
    <p:columnToggler datasource="products1" trigger="toggler"/>
</f:facet>
```

**Comment by Rapster** [comment]
8 or 9 SNAPSHOT?

**Comment by jthalmai** [comment]
> 
> 
> 8 or 9 SNAPSHOT?

8.0-SNAPSHOT

**Comment by buunsal** [comment]
The same issue continues with 9.0-SNAPSHOT

**Comment by mertsincan** [comment]
Hi @sqores,
With this PR, the problem still exists. When we toggle a few columns, the table shows a horizontal scroll. Unfortunately, reverted.

**Comment by buunsal** [comment]
Hi @mertsincan,
I am working on it.

**Comment by buunsal** [comment]
Already resolved with this https://github.com/primefaces/primefaces/pull/6370
