### ISSUE TITLE
Calendar: Using min-/maxdate throws an error

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#6506]
**Describe the defect**
When using mindate or maxdate as java.sql.Date the calendar component throws an exception.
See
`class java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException
	at java.sql.Date.toInstant(Date.java:315)
	at org.primefaces.util.CalendarUtils.convertDate2ZonedDateTime(CalendarUtils.java:439)
	at org.primefaces.util.CalendarUtils.convertDate2LocalDate(CalendarUtils.java:452)
	at org.primefaces.util.CalendarUtils.convertDate2LocalDate(CalendarUtils.java:444)
	at org.primefaces.util.CalendarUtils.getObjectAsLocalDate(CalendarUtils.java:80)
	at org.primefaces.component.calendar.Calendar.validateValue(Calendar.java:139)
	at javax.faces.component.UIInput.validate(UIInput.java:670)`

**Environment:**
 - PF Version: 8.0.3
 - JSF version: MyFaces 2.3
 - Affected browsers: ALL

**Example XHTML**
```<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
	
	<h:form>
		<p:messages />
		<p:calendar mindate="#{testHandler.minDate}" maxdate="#{testHandler.maxDate}" value="#{testHandler.date}" />
		<p:commandButton value="Save" actionListener="#{testHandler.save}" update="@form" />
	</h:form>

</ui:composition>
```

**Example Bean**
```java
package test;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Date;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestHandler implements Serializable {

	private static final long serialVersionUID = 1L;

	private Date date;

	public Date getMinDate() {
		return java.sql.Date.valueOf(LocalDate.now().minusDays(10));
	}

	public Date getMaxDate() {
		return java.sql.Date.valueOf(LocalDate.now());
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public void save() {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "saved", null));
	}

}
```

**Comment by pfumi** [comment]
With PrimeFaces 7 it was not possible to use the Java 8 LocalDate classes, so we converted them to Date. But now the code breaks since PrimeFaces 8.

**Comment by melloware** [comment]
Is it because you are  using `java.sql.Date` and you should be using `java.util.Date`??

See: https://stackoverflow.com/questions/36435492/unsupportedoperationexception-why-cant-you-call-toinstant-on-a-java-sql-dat

**Comment by pfumi** [comment]
To convert LocalDate to Date I can either do
a) java.util.Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant())
or
b) java.sql.Date.from(LocalDate.now())


b) Does not work anymore since PF8, but worked in PF7. I know I can just use LocalDate now and dont have to bother with the Date classes anymore.

Just wanted to give you the information that it worked before.

**Comment by melloware** [comment]
OK let me look if its an easy fix.

**Comment by melloware** [comment]
Reproducer:
[pf-6506.zip](https://github.com/primefaces/primefaces/files/5537461/pf-6506.zip)

**Comment by melloware** [comment]
I added an Integration Test to catch this in the future: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/18e6a35b5220e9fd0ee2d913f2f969c69f2a37da
