### ISSUE TITLE
validateLongRange with a minimum of 0 does not work with client side validation

### ISSUE THREAD

**Issue by weissreto** [primefaces/primefaces#651]
If I use `<f:valdidateLongRange minimum="0" maximum="10">` with client side validation then values from Long.MIN_VALUE .. 10 are accepted instead of 0 .. 10! 

If I configure `minimum="1"` or `minimum="-1"` then the validation correctly accepts only values from 1 .. 10 respective -1 .. 10

**Comment by tandraschko** [comment]
Could you please try to change your pull requests just to use Integer instead of int? This wouldn't require the additional boolean var.

**Comment by weissreto** [comment]
Hi Thomas

Do you mean something like this:

```
public class LongRangeValidator extends javax.faces.validator.LongRangeValidator implements ClientValidator {

    private Map<String,Object> metadata;
    private Long minimum;
    private Long maximum;

    public Map<String, Object> getMetadata() {
        metadata = new HashMap<String, Object>();

         if(minimum!=null)
            metadata.put(HTML.VALIDATION_METADATA.MIN_VALUE, minimum);

        if(maximum!=null)
            metadata.put(HTML.VALIDATION_METADATA.MAX_VALUE, maximum);

        return metadata;
    }

    public String getValidatorId() {
        return LongRangeValidator.VALIDATOR_ID;
    }

    public void setMaximum(long maximum) {
        super.setMaximum(maximum);
        this.maximum=maximum;
    }

    public void setMinimum(long minimum) {
        super.setMinimum(minimum);
         this.minimum=minimum;
    }
}
```

**Comment by tandraschko** [comment]
yep, exactly :)
if this is working fine, i have no problems to accept the pull request!

**Comment by cagataycivici** [comment]
Why can't we check against Double.MIN_VALUE and Double.MAX_VALUE to decide if values should go in metadata? Not sure about duplicating field and methods already available in parent class.

**Comment by cagataycivici** [comment]
Ok, I see now. isMaximumSet() and isMinimumSet() are private. Wish they weren't. I actully prefer the booleans, less confusing for me since we need to check if these values are checked. Using Long, duplicates the field at parent class.
