### ISSUE TITLE
p:menuitem icon="flight-land" not showing up

### ISSUE THREAD

**Issue by vitsin** [primefaces/primefaces#6510]
<p:menuitem id="sr_db_landing" value="Landing" icon="flight-land" ... /> - show up icon that match "flight" icon and not "flight-land".
<p:menuitem id="sr_db_landing" value="Landing" icon="flight" ... /> - proper "flight" icon show up.

Theme Sapphire: v2.0.2
PrimeFaces: v8.0.5

**Comment by melloware** [comment]
Please report on the Saphire forums: https://forum.primefaces.org/viewforum.php?f=106

I am not even sure where the icon "flight" or "flight-land" are coming from.  What icon set are you using?

**Comment by vitsin** [comment]
https://www.primefaces.org/sapphire/utils.xhtml

**Comment by melloware** [comment]
OK yep all issues for premium themes do not get dealt with by the Community only by PrimeTek so report your issue to the the Saphire forum: https://forum.primefaces.org/viewforum.php?f=106

**Comment by vitsin** [comment]
thanks
