### ISSUE TITLE
AutoComplete: optionally allow to consume REST-endpoint for suggestions

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6511]
Idea would be to optionally use a simple REST-endpoint to provide AutoComplete-suggestions.
This would avoid having the JSF-lifecycle-overhead including RestoreViewPhase for just providing a few AutoComplete-suggestions.
Once a value is selected "everthing" (eg converters) would happen JSF-"style".

I´ll try to work on this within the next weeks.
Just started with a simple Showcase-Draft-PR: https://github.com/primefaces/primefaces-showcase/pull/221

**Comment by christophs78** [comment]
We have this feature (as part of our custom PrimeFaces 8.0-build) in our enterprise-grade COVID-19-contract-tracing application since 3 weeks in production. Works very well. :-)
We replaced 3 fat SelectOneMenu´s in our main XHTML (which contains all information around one person) with AutoComplete with REST-endpoint. Average CPU-time for this XHTML went down from 70ms to 50ms. (And there happens way more on this XHTML like SOAP-calls to our DMS.) This XHTML ist called between 250.000 and 600.000 times a day. (Depending on the amount of new COVID-19-infections.)
Each REST-Call takes between 2 and 4ms. (Highly optimized implementation.)

**Comment by melloware** [comment]
Thanks for reporting. I think this is an excellent addition to AutoComplete.

**Comment by tandraschko** [comment]
great, thanks for the feedback.
