### ISSUE TITLE
SelectOneMenu: Escaping issue when using multiple SelectItemGroups with the same SelectItem

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#6514]
**Describe the defect**
Escapes certain SelectItems if they appear multiple times in different SelectGroups, although they are not meant to be escaped. The problem seems to lie in the calculation of the index when checking against the "escape" property of the SelectItem. In this example there is an offset of -1, which when selecting the first not escaped option ("0"), results in the application checking against the first SelectItem ("Escape") which is to be escaped.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _Mojarra 2.3.14_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to 'http://localhost:8080/primefaces-test/'
2. Open the SelectOneMenu
3. Click on "0"
4. "0" shows up escaped

**Expected behavior**
"0" should not show up escaped, just like the other options "1" and "2".

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="frmTest">
            <p:selectOneMenu id="selectOneMenu" value="#{testView.text}">
                <f:selectItems value="#{testView.items}"/>
            </p:selectOneMenu>
        </h:form>
    </h:body>
</html>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

    private String text;

    private List<SelectItem> items;
    
    @PostConstruct  
    public void init() {
        SelectItemGroup group;

        items = new LinkedList<>();

        items.add(new SelectItem("Escape", "Escape", null, false, true));

        for(int g = 0; g<2; g++) {
            String example = String.format("<span>%s</span>", "Example");
            group = new SelectItemGroup(example);
            group.setEscape(false);
            group.setSelectItems(new SelectItem[0]);
            items.add(group);

            for(int i = 0; i<3; i++) {
                String text = String.format("<span>%s</span>", i);
                items.add(new SelectItem(i, text, null, false, false));
            }
        }
    }

    public List<SelectItem> getItems() {
        return items;
    }

    public void setItems(List<SelectItem> items) {
        this.items = items;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
```

**Comment by melloware** [comment]
Thanks for reporting and test case.  Let me investigate.

Reproducer:
[pf-6514.zip](https://github.com/primefaces/primefaces/files/5546307/pf-6514.zip)

**Comment by melloware** [comment]
I can confirm this is already fixed in 9.0-SNAPSHOT if you would like to give 9.0 a shot.
```xml
<dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>

 <repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>
```

**Comment by fcjm** [comment]
I am currently trying the fixes coming from RC1 in our application and the problem still seems to be there. I tried it with the example i gave you back in november and though it looks fine, the variable "option" used in setLabel() still isnt set to the right value. Therefore you might end up checking the escape property of something different than the actual selected option.

Code in question (from setLabel() in forms.selectonemenu.js lines 1066-1069):

                if(this.items) {
                    var selectedItem = this.items.filter('[data-label="' + $.escapeSelector(value) + '"]');
                    option = this.options.eq(this.resolveItemIndex(selectedItem));
                }

selectedItem in my example then becomes an array with 2 entries which seems to create an offset in resolveItemIndex() - in the end pointing towards the wrong option. In our application we have a case where this leads to html showing up as plaintext.

**Comment by melloware** [comment]
Can you tweak the reproducer to show the issue?

**Comment by fcjm** [comment]
Ehm so yeah. I fiddled around with the reproducer for a bit and it is a mess now. But i got some new insight.

We update the form once we select an item from the dropdown menu - meaning we go through the init function again. There setLabel() is also called. There seems to be a difference in calling setLabel in init(), but i have not looked into it just yet.

I updated the reproducer so only "1" has "escape=false". If you want to reproduce the error i mentioned before you have to select "1" and press the update-button. Then "1" will also show up as plaintext. "2" also does not  act like it should since its checking against option "1" for the escape property. I hope this reproducer gives you some insight.


[reproducer.zip](https://github.com/primefaces/primefaces/files/5912253/reproducer.zip)

**Comment by fcjm** [comment]
Works perfectly now. Thank you for the fix!

**Comment by melloware** [comment]
Integration test added: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/84f2fac176bdb05b7459e3bede893b492587c7c5
