### ISSUE TITLE
Spinner: Lock to stepFactor with 'round' attribute

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6521]
It would be great if one could define this:

```
<p:spinner
                value="#{spinnerView.number1}"
                min="0"
                max="55"
                stepFactor="5">

```

and the spinner would allow the intended values only. In this case: 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, and 55!

among others, it should not be possible to enter non-numeric values and unintended numeric values (here any decimals or integers not in the list above)

**Comment by melloware** [comment]
I have fixed part of this with my latest commit. If your number is an Integer i no longer allow the decimalSeparator char to be entered like "."

**Comment by melloware** [comment]
This could be tricky because to enter "10" you need to enter "1" then "0"  The "1" is not on the stepFactor so it would block it from entering.

**Comment by tuerker** [comment]
> I have fixed part of this with my latest commit. If your number is an Integer i no longer allow the decimalSeparator char to be entered like "."

thanks. unfortunately, i cannot run my system with the latest PF snapshot since there were some breaking changes in the last days (regarding datatables). we have to do some migration work first.

**Comment by tuerker** [comment]
> This could be tricky because to enter "10" you need to enter "1" then "0" The "1" is not on the stepFactor so it would block it from entering.

i am aware of the difficulties. maybe in case of the numbers the entering would be allowed but when the spinner is left the value is reset (to the closest or null) with providing a corresponding message.

**Comment by melloware** [comment]
Added Integration Test: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/12ed3ec3b9cf7771c1f010148e3a6ed454b86de7
