### ISSUE TITLE
CSP: DialogReturn not handled correctly when CSP is enabled

### ISSUE THREAD

**Issue by ubench-tdv** [primefaces/primefaces#6527]
**Describe the defect**
There seems to be a problem in handling the DialogReturn ajax event when CSP is enabled. The DialogReturn event is not triggered and the dialog does not close.

**Reproducer**

See the attached file

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/5560663/primefaces-test.zip)

**Environment:**
- PrimeFaces version: 8.0 (also tested 8.0.4)
- CSP enabled? yes
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Apache Tomcat 9 + JSF 2.3.14
- Affected browsers: All

**To Reproduce**
1. Open the sample application
2. Click on "Open Dialog (not working)"
3. Try to close the dialog.

**Expected behavior**
The DialogReturn ajax event should be correctly processed upon closing a dialog.

**Example XHTML**
```html
<h:form>
  <p:commandButton value="Open dialog" action="#{helloworld.openDialog}">
	 <p:ajax event="dialogReturn" listener="#{helloworld.handleReturn}"/>
  </p:commandButton>
  <p:commandLink action="#{helloworld.openDialog}">
	 <h:outputText value="Open dialog"/>
	 <p:ajax event="dialogReturn" listener="#{helloworld.handleReturn}"/>
  </p:commandLink>
</h:form>
```
**Example dailog XHTML**
```html
<h:form>
  <p:commandButton value="Close" action="#{helloworld.closeDialog}"/>
</h:form>
```

**Example Bean**
```java
@Named("helloworld")
@ViewScoped
public class HelloWorldBean implements Serializable {

   public String getMessage() {
      return "Hello World";
   }

   public void openDialog() {
      PrimeFaces.current().dialog().openDynamic("dialog.xhtml");
   }

   public void closeDialog() {
      PrimeFaces.current().dialog().closeDynamic(null);
   }

   public void handleReturn(SelectEvent event) {
      System.out.println("Return from dialog");
   }
}
```

**Example web.xml**
```html
<context-param>
  <param-name>primefaces.CSP</param-name>
  <param-value>true</param-value>
</context-param>
<context-param>
  <param-name>primefaces.CSP_POLICY</param-name>
  <param-value>script-src 'self'</param-value>
</context-param>

```

If you open the dialog via the link you will see that you can not close it and the return event is not handled. Opening via the command button seems to work.

If you disable CSP all works perfectly.

**Comment by melloware** [comment]
Thank you for following the template and the excellent use case!  It makes it so much easier to debug issues.

**Comment by ubench-tdv** [comment]
No thank you, for your response and this great product called Primefaces!

**Comment by melloware** [comment]
@mertsincan I think this should go in Elite 8.0.6
