### ISSUE TITLE
DatePicker: range + onchange not called

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6540]
**Describe the defect**
JS callback when range selection set

**Environment:**
 - PF Version: 9.0-SNAPSHOT

**To Reproduce**
1. Based on https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml
2. Define a selection for range example
3. JS callback not called

**Expected behavior**
JS callback called

**Example XHTML**
```html
<h:form id="frmTest">
    <p:datePicker selectionMode="range" onchange="console.log('hello world')" />
</h:form>
```

**Analysis**
JS callback not called due to this:
```js
    fireDateSelectEvent: function() {
        // #5830: do not fire in range mode if only the first value is set
        if (this.cfg.selectionMode === "range" && this.input.val().indexOf(this.cfg.rangeSeparator) === -1) {
            return;
        }

        this.input.trigger('change');
        this.callBehavior('dateSelect');
    },
```

`this.cfg.rangeSeparator` is undefined, so it will always returns -1. The reason is because `rangeSeparator` is never passed to the widget, and that's because of `WidgetBuilder#attr(String name, String value, String defaultValue)` (since value equals defaultValue). 

I think I mentionned this a while back but I never fully understood  that method. Why explicitely passing a default value while this job is already done by the component java itself? Redundant no? Or it supposed the widget will define a defalut value... but shouldn't be component java responsability to do so? Anyway, the fix is to call  `WidgetBuilder#attr(String name, String value)` instead

**Comment by melloware** [comment]
That widget builder method is so we don't waste network traffic sending the JSON value if its the known default.

So the widget init method needs this
```javascript
this.cfg.rangeSeparator = this.cfg.rangeSeparator||'-';
```

**Comment by Rapster** [comment]
Ah ok thanks
