### ISSUE TITLE
RemoteCommand: Calling remote command in Javascript unload event does not work in all browser

### ISSUE THREAD

**Issue by theobisproject** [primefaces/primefaces#6548]
**Describe the defect**
I need to change state in my application when the user closes the browser while some action is performed. This is currently implemented with a call to a remoteCommand in when the unload event is triggered in the browser.

The call to the remote command does not work in Firefox and Internet Explorer. Seems like the Ajax request is aborted. In the Internet Explorer there even happens an exception in the reproducer.

Is there anything i can do different to make this work?

**Reproducer**
https://github.com/theobisproject/primefaces-test/tree/remote-command

**Environment:**
 - PF Version: _8.0_, _7.0_
 - JSF + version: _Mojarra 2.2.8_
 - Affected browsers: _Firefox_, _Internet Explorer_

**To Reproduce**
1. Open Reproducer
2. Close Browser
3. In the jetty log a log statement should be printed

**Expected behavior**
Logstatement is printed in all browsers

**Comment by tandraschko** [comment]
We abort all PF AJAX requests in window unload (NOTE: we had a bug in 7.0/8.0 that we did it in beforeunload, i fixed it this week in trunk).

In general there is no guarantee that a AJAX request will work in unload: https://stackoverflow.com/questions/19274486/doing-an-ajax-call-on-window-unload and therefore its not a bug on our side. You can only rely on beforeunload.

For questions please use the forum or stackoverflow.

**Comment by theobisproject** [comment]
Are you able to tell me why the request is not aborted when I do this using chrome?
EDIT: Sorry it is mentioned in the stackoverflow that chrome always completes them
