### ISSUE TITLE
DatePicker: what happened to attribute disabledWeekends of p:datePicker?

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6549]
Surprisingly it looks like that at least in the recent PF9 snapshots the attribute disabledWeekends of p:datePicker does not exists anymore. Is this true?

I would really favor to have disabledWeekends back since it is more convenient for its purpose compared to the attribute disabledDays which of course is more powerful and emulate it. The latter however increases error-proneness.

**Comment by melloware** [comment]
@tuerker I am looking at the docs for PF 7.0. and 8.0 and I can't find any reference to `DisabledWeekends`?

7.0: https://primefaces.github.io/primefaces/7_0/#/components/datepicker

8.0: https://primefaces.github.io/primefaces/8_0/#/components/datepicker

**Comment by tuerker** [comment]
I went now into the history of our code. Somebody must have left this attribute after having migrated from p:calendar to p:datePicker. So actually this attribute disabledWeekends belongs to p:calendar.

Nevertheless, i think that would be a good addition to the datePicker. What do you think? Many thanks.

**Comment by melloware** [comment]
Ahh I see you are confusing `DatePicker` with the older jQuery `Calendar` component.

DatePicker is much more powerful and flexible and you can accomplish the same with `disabledDays="0,6"` or if you want to make it more description `disabledDays="#{dateProvider.disabledWeekends}"`

Adding `disabledWeekends` doesn't make much sense to me if all it will do is add 0,6 to the list and could also cause confusion if someone has `disabledDays="1"` to disable Mondays and `disabledWeekends=true` now Sunday, Monday, and Saturday are disabled.

**Comment by melloware** [comment]
@christophs78 @jepsar your thoughts but I am leaning towards **wontfix** status?

**Comment by jepsar** [comment]
@melloware +1 for `disabledDays="0,6"` / won't fix.

**Comment by tuerker** [comment]
@melloware 

disabledDays="0,6" does unfortunately not work. delivers: 

`Cannot convert 0,6 of type class java.lang.String to interface java.util.List`

So you are forced to write a method which delivers a list.

You are right w.r.t. the confusion that the combination of disabledDays and disabledWeekends could cause. Therefore, forget this extension. Thanks.

**Comment by melloware** [comment]
You might have to do `disabledDays="[0,6]"` ??  But I think you are right I think it has to be a method that returns a List<Integer> so `disabledDays="#{dateProvider.disabledWeekends}"`

**Comment by tuerker** [comment]
disabledDays="[0,6] is also not working. i have used the list returning method.

**Comment by christophs78** [comment]
https://primefaces.github.io/primefaces/9_0/#/components/datepicker?id=date-restriction
This works in https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml, „Disabled Date/Day“
