### ISSUE TITLE
InputNumber : Have a option to disable scroll to change value

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#6552]
Run the test on showcase  

1. https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml
2. Click on an input number box
3. use the mouse to  scroll up or down
_4. The number get updated._ 

When the focus is on a InputNumber  and the user tries to scroll assuming it is page , the number get updated like Spinner. 
This case unexpected issue  and there should be option to disable the changing of value on mouse scrolling .

**Comment by melloware** [comment]
Isn't that this fix: https://github.com/primefaces/primefaces/issues/5849

Fixed in 8.0.3 an 9.0

**Comment by ravihariharan** [comment]
@melloware .. i hope @mertsincan  can back fix this to elite  7

**Comment by melloware** [comment]
You can fix it in your app right now yourself just add this script to your app.

```javascript
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        this.input = $(this.jqId + '_input');
        this.hiddenInput = $(this.jqId + '_hinput');
        this.plugOptArray = cfg.pluginOptions;
        this.valueToRender = cfg.valueToRender;
        this.disabled = cfg.disabled;
        this.cfg.modifyValueOnWheel = false;

        //bind events if not disabled
        if (this.disabled) {
            this.input.attr("disabled", "disabled");
            this.input.addClass("ui-state-disabled");
            this.hiddenInput.attr("disabled", "disabled");
        }

        //Visual effects
        PrimeFaces.skinInput(this.input);

        this.wrapEvents();
        this.bindInputEvents();

        this.autonumeric = new AutoNumeric(this.jqId + '_input', this.cfg);

        if (this.valueToRender !== "") {
            //set the value to the input the plugin will format it.
            this.autonumeric.set(this.valueToRender);
        }

        this.copyValueToHiddenInput();

        //pfs metadata
        this.input.data(PrimeFaces.CLIENT_ID_DATA, this.id);
        this.hiddenInput.data(PrimeFaces.CLIENT_ID_DATA, this.id);
    }
};

**Comment by melloware** [comment]
I copied the code out of 9.0 but you might want to look at 7.0's init method by digging into your elite JAR and starting with that. Then just add `this.cfg.modifyValueOnWheel = false;`

**Comment by AceDoan** [comment]
> You can fix it in your app right now yourself just add this script to your app.
> 
> ```js
> if (PrimeFaces.widget.InputNumber) {
>     PrimeFaces.widget.InputNumber.prototype.init = function(cfg) {
>         PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
>         this.input = $(this.jqId + '_input');
>         this.hiddenInput = $(this.jqId + '_hinput');
>         this.plugOptArray = cfg.pluginOptions;
>         this.valueToRender = cfg.valueToRender;
>         this.disabled = cfg.disabled;
>         this.cfg.modifyValueOnWheel = false;
> 
>         //bind events if not disabled
>         if (this.disabled) {
>             this.input.attr("disabled", "disabled");
>             this.input.addClass("ui-state-disabled");
>             this.hiddenInput.attr("disabled", "disabled");
>         }
> 
>         //Visual effects
>         PrimeFaces.skinInput(this.input);
> 
>         this.wrapEvents();
>         this.bindInputEvents();
> 
>         this.autonumeric = new AutoNumeric(this.jqId + '_input', this.cfg);
> 
>         if (this.valueToRender !== "") {
>             //set the value to the input the plugin will format it.
>             this.autonumeric.set(this.valueToRender);
>         }
> 
>         this.copyValueToHiddenInput();
> 
>         //pfs metadata
>         this.input.data(PrimeFaces.CLIENT_ID_DATA, this.id);
>         this.hiddenInput.data(PrimeFaces.CLIENT_ID_DATA, this.id);
>     }
> };
> ```

Hi @melloware ,
1. I can used this scripts successfully but it affected to others attributes like 
"maxValue="100"
decimalSeparator="," 
thousandSeparator="""
These attributes would be turned off when I use the scripts above
2. The second problem is when I use 
<p:ajax ignoreAutoUpdate="true" update="percentageLowerLimit percentageUpperLimit" />
inside of <p:inputNumber then the content of inputtext will be reset after mouse over.
Could you help to take a look? Or do you have any idea?

**Comment by melloware** [comment]
1. It should not be because this line calls the default constructor: PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);`  But do me a favor add this line right after...
```javascript
PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
this.cfg = cfg;
```

See if that fixes it.

2. Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by AceDoan** [comment]
Hi @melloware ,
Seems It's did not fixed with Primefaces 7.0.17, right? I can succeed with 10.0.0 but not for 7.0.17.
About 10.0.0 the attribute maxLength will inactive when I set modifyValueOnWheel="false".

**Comment by melloware** [comment]
Nope it's in 8.0.3 and 10.0.0+ if you look at the labels on the right

**Comment by AceDoan** [comment]
@melloware Do we have any way to fix it for 7.0.17?

**Comment by melloware** [comment]
@AceDoan see my MonkeyPatch above you can use that right now with 7.0.17.

**Comment by AceDoan** [comment]
@melloware hmm, it does not work correct. It affected to others attribute as i mentioned above.

**Comment by melloware** [comment]
I tested it and it works for me.
