### ISSUE TITLE
DataTable: filtering doesnt work inside p:panelGrid

### ISSUE THREAD

**Issue by fabermundi** [primefaces/primefaces#6563]
**Describe the defect**
My datatable did not filter when entering a text in the filter box, so I simplified my code until getting the above shown code and tracked down that when changing the p:panelGrid to h:panelGrid the filter is working again.
Unfortunately I can not track this down anymore so I let the experts here handle this...

**Environment:**
 - PF Version: 8.0.5
 - JSF + version: JSF 2.3
 - Affected browsers: all

**To Reproduce**
Enter a text in the filter input and nothing will happen.

**Expected behavior**
The column should be filtered

**Example XHTML**
This does **not** work:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:view>
        <h:head>
        </h:head>
        <h:body>
            <h:form>
            </h:form>

            <p:panelGrid>
                <h:form>
                    <p:dataTable value="#{testBean.testValues}" var="test">
                        <p:column headerText="TestValue" filterBy="#{test}">
                            <h:outputText value="#{test}" />
                        </p:column>
                    </p:dataTable>
                </h:form>
            </p:panelGrid>
        </h:body>
    </f:view>
</html>
```
When changing the panelGrid to a "h:panelGrid" the filtering works:
```html
...
<h:body>
    <h:form>
    </h:form>
    <h:panelGrid>
        <h:form>
            <p:dataTable value="#{testBean.testValues}" var="test">
                <p:column headerText="TestValue" filterBy="#{test}">
                    <h:outputText value="#{test}" />
                </p:column>
            </p:dataTable>
        </h:form>
    </h:panelGrid>
</h:body>
...
```

**Example Bean**
```java
@Named
@SessionScoped
public class TestBean implements Serializable {
    public List<String> getTestValues() {
        List<String> result = new ArrayList<>();
        for (int i = 0; i < 5; i++)
            result.add(String.valueOf(i));
        return result;
    }
}
```

**Comment by melloware** [comment]
I can take a look at this one.

**Comment by melloware** [comment]
I think it might just be a misunderstanding of the panelGrid.

A naked `<p:panelGrid>` like you have expects it to have `<p:row>` items as its direct descendents for you to "draw" how you want your grid see the "Grouping" example here at the showcase: https://www.primefaces.org/showcase/ui/panel/panelGrid.xhtml

To fix your issue you can switch to grid or flex mode by simply adding..

```xml
<p:panelGrid columns="1">
```

... like in the Responsive Basic example of the Showcase: https://www.primefaces.org/showcase/ui/panel/panelGrid.xhtml

**Comment by tandraschko** [comment]
can't we make columns=1 as default then?

**Comment by melloware** [comment]
Well I think if columns=null is what triggers p:panelGrid to look for p:row values instead of it formatting,  Once you use columns="1" as default that would break.

**Comment by tandraschko** [comment]
ok ok
but the panelGrid in the example is rendered as exepcted, just filtering doesnt work?

**Comment by melloware** [comment]
Attached is reproducer:
[pf-6563.zip](https://github.com/primefaces/primefaces/files/5604104/pf-6563.zip)

No it actually break it because the panel grid is looking for a `<p:row>` and doesn't it find it. So its `table` tags mess up the datatable `table` tags and the whole thing is rendered off.

**Comment by melloware** [comment]
You can see the top table rendering is off the bottom table is correct.

![image](https://user-images.githubusercontent.com/4399574/100374741-bb7f7300-2fda-11eb-9d6a-b5ce5a0d25c6.png)

**Comment by tandraschko** [comment]
yep ok, then its completely by design.

**Comment by tandraschko** [comment]
we could however log a warning in this case? columns = null and no p:row

**Comment by melloware** [comment]
I am wondering if we should actually throw a FacesException?

**Comment by tandraschko** [comment]
yeah, even better

**Comment by fabermundi** [comment]
I agree. It would really be good to send out some kind of error message as it took me some time to track this down.
Thanks for your help.

**Comment by melloware** [comment]
Ok I will submit a PR

**Comment by melloware** [comment]
OK need a decision here. The code is doing this:
```java
for (UIComponent child : grid.getChildren()) {
            if (child.isRendered()) {
                if (child instanceof Row) {
                    String rowStyleClass = i % 2 == 0
                                           ? PanelGrid.TABLE_ROW_CLASS + " " + PanelGrid.EVEN_ROW_CLASS
                                           : PanelGrid.TABLE_ROW_CLASS + " " + PanelGrid.ODD_ROW_CLASS;
                    encodeRow(context, (Row) child, "gridcell", rowStyleClass, PanelGrid.CELL_CLASS);
                    i++;
                }
                else {
                    child.encodeAll(context);
                }
            }
        }
```

Basically it says if you are not a `Row` just encode whatever component it is.  However in this case the `<table>` tag is already open so its rendering the Datatable wrong.   So I am not sure I should replace `child.encodeAll(context);` with a FacesException since I guess there could be use cases where you would just want to render the component?

**Comment by tandraschko** [comment]
i think we should remember if a Row is available as child and after the loop check !rowFound && columns==null -> throw

**Comment by melloware** [comment]
OK that is good idea.
