### ISSUE TITLE
Panel: Runtime error on panel show()

### ISSUE THREAD

**Issue by Jens-dojo** [primefaces/primefaces#6576]
Hello,

the close() function of a panel has

 close: function() {
        if(this.visibleStateHolder) {
            this.visibleStateHolder.val(false);
        }

The show() function however does NOT check if visibleStateHolder exists and throws a runtime error when that is the case

  show: function() {
...
  this.visibleStateHolder.val(true);

I have no ideas how pull requests work....
Maybe someone could change this for
 if(this.visibleStateHolder) {
            this.visibleStateHolder.val(true);
        }

Thank you!
Jens

**Comment by melloware** [comment]
Thank you for reporting you are correct this is a bug. To fix right now just add this JS to your application.

```javascript
if (PrimeFaces.widget.Panel) {
    PrimeFaces.widget.Panel.prototype.show = function() {
        var $this = this;
        this.jq.fadeIn(this.cfg.closeSpeed, function() {
            PrimeFaces.invokeDeferredRenders($this.id);
        });

        if (this.visibleStateHolder) {
            this.visibleStateHolder.val(true);
        }
    };
}
```

**Comment by Jens-dojo** [comment]
Thank you for your prompt reply and help!
