### ISSUE TITLE
FilterMeta: javadoc on deprecated ctor

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6579]
With the changes in the class FilterMeta from Nov 28 there is no constructor FilterMeta(String field, Object filterValue) anymore, which had used so far. We require advice how to migrate this since there is also no setField method.

Thanks in advance.

**Comment by tandraschko** [comment]
Please check the migration guide

**Comment by tuerker** [comment]
Of course, I checked https://primefaces.github.io/primefaces/9_0/#/../migrationguide/9_0. But there is no answer to that. 
I would be glad if you can point at the place where this is described.

**Comment by tandraschko** [comment]
`DataTable#filterBy: no longer expect a Map, but a single or a collection of FilterMeta (use FilterMeta#builder)`

**Comment by melloware** [comment]
@Rapster we are also using this Deprecated method in TreeTable.java but there is no JavaDocs in the deprecated method for what to do and how to fix it.

**Comment by Rapster** [comment]
Yeah true, I'll put a comment on this ctor so users know what to do, I don't plan to modify TreeTable though (since I think this component needs a complete refactoring 😅 )

**Comment by tuerker** [comment]
> `DataTable#filterBy: no longer expect a Map, but a single or a collection of FilterMeta (use FilterMeta#builder)`

thanks for the hint. however, i am not get the builder approach to work. it is unclear how to translate the "old"

new FilterMeta(String field, Object filterValue)

to 

FilterMeta.builder()...

There are no methods, such as setField or setFilterValue, available on the FilterMeta.builder() expression.

**Comment by tandraschko** [comment]
FilterMeta.builder().field(...).filterValue(...).build(); ;)

**Comment by tandraschko** [comment]
its also already updated in the showcase, however we dont have control of the deployment. You may get it from github sources.

**Comment by Rapster** [comment]
You can have a look here: https://primefaces.github.io/primefaces/9_0/#/components/datatable?id=filtering

**Comment by tuerker** [comment]
this is actually what i tried intuitively, too. however, intellij was stating that there is no such field() method. 

![Screenshot from 2020-11-30 17-38-01](https://user-images.githubusercontent.com/10051373/100637474-34f8c780-3333-11eb-8fc2-353315dd0321.png)

after closing intellij and invalidating the cache of intellij this is now also working. thanks again.
