### ISSUE TITLE
Improvement in behavior of components that have overlay panels in scrollable containers

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6583]
**Describe the defect**
There have been multiple defects reported about overlay panel of components not sticking with the component when scrolling in a dialog or in a window.

**Reproducer**
[overlay-scroll.zip](https://github.com/primefaces/primefaces/files/5625120/overlay-scroll.zip)

**Components:**
- [x] AutoComplete https://github.com/primefaces/primefaces/issues/4541
- [x] SelectOneMenu https://github.com/primefaces/primefaces/issues/4609
- [x] SelectCheckboxMenu
- [x] ColorPicker
- [x] DatePicker
- [x] Calendar

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
There are two types of problems.  

1. When a component is opened in a dialog that can be scrolled scrolling in the dialog separates from the component like:
![image](https://user-images.githubusercontent.com/4399574/100790500-e8ba8f80-33e5-11eb-838a-16cf2e5015fb.png)

2. Scrolling in the Document Window can separate the component like:
![image](https://user-images.githubusercontent.com/4399574/100790659-18699780-33e6-11eb-8b51-7cb8ee0fdfbd.png)

**Comment by mertsincan** [comment]
The registerScrollHandler method doesn't do exactly that. Users can have nested scrollable containers. 
Note: I have now added a fix for the datePicker. I'll make improvements to others after RC1.

PrimeReact;
https://github.com/primefaces/primereact/issues/1589
https://github.com/primefaces/primereact/issues/1655

**Comment by mertsincan** [comment]
When the scrollable container(**not document**) is scrolled or window is resized, all open overlay panels will be closed.

- [x] AutoComplete
- [x] CascadeSelect
- [x] Datepicker
- [x] Password
- [x] SelectCheckboxMenu
- [x] SelectOneMenu
- [x] ThemeSwitcher
- [x] SplitButton
- [x] OverlayPanel
- [x] Menu
- [x] MenuButton
- [x] SlideMenu
- [x] TieredMenu
- [x] ConfirmPopup
- [x] ContextMenu
- [x] ColorPicker
- [x] Keyboard
