### ISSUE TITLE
Schedule: ContextMenu support

### ISSUE THREAD

**Issue by aligit** [primefaces/primefaces#6587]
**Description**
I'm using the **schedule** but there is currently no integration of the contexMenu to associate the event with it. This integration is already provided in TreeTable and DataTable.

**Describe the solution you would like**
Extend the list of events with something like onEventRightClick able to catch which event has been chosen(or at least which startDate)

**Example XHTML**
```xml
    <h:form id="#{constants.EDIT}">
      <p:growl id="messages" showDetail="true" />
      <h:panelGrid>
        <p:schedule
          id="schedule"
          widgetVar="scheduleWidgetVar"
          value="#{eventManager.lazyEventModel}"
          extender="initSchedule">
          <p:ajax
            event="onEventRightClick"
            listener="#{eventManager.onEventRightClick}" />
        </p:schedule>
        <p:contextMenu for="schedule">
          <p:menuitem value="Approve" url="#" onclick="PF('gallery').previous()" />
          <p:menuitem value="Reject" url="#" onclick="PF('gallery').next()" />
        </p:contextMenu>
      </h:panelGrid>

      <p:dialog
        widgetVar="eventDialog">
        <h:panelGroup id="eventDetails">
          <ui:include src="/event/edit.xhtml" />
            <p:commandButton
              value="#{messages.saveLabel}"
              action="#{eventManager.save}"
              update="eventDetails" />
        </h:panelGroup>
      </p:dialog>
    </h:form>

```

**Example Bean**
```java
@Named
@ViewScoped
public class EventManager implements Serializable {

public void onEventRightClick(SelectEvent<ScheduleEvent<Event>> event){
...
}
```

**Comment by melloware** [comment]
The AJAX method to make it consistent with other components would be "contextMenu". Similar to: https://github.com/primefaces/primefaces/issues/3761

**Comment by melloware** [comment]
This is dependent on Right Click being supported by FullCalendar. See this open ticket: https://github.com/fullcalendar/fullcalendar/issues/2748

**Comment by melloware** [comment]
There is also this plugin: https://github.com/mherrmann/fullcalendar-rightclick

However it doesn't work for FullCalendar 5 and the author left a very unprofessional answer to my ticket: https://github.com/mherrmann/fullcalendar-rightclick/issues/23

**Comment by aligit** [comment]
Thank you @melloware

**Comment by melloware** [comment]
Tracking this in the third party library will re-open here when fixed in third party library
