### ISSUE TITLE
Add shared interface between TreeTable and DataTable for managing column/columns

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6588]
Currenly both TreeTable and DataTable have very much similar methods like findColumn, findColumnInGroup, getColumnCount and so on.

to be honest, i dont like the default-method interfaces that much but its a way that we can share methods easily.

**Comment by melloware** [comment]
I know what you mean Default Interfaces feel like cheating but I guess its better than an alternative Static Utility like TableUtils.java ....

**Comment by Rapster** [comment]
I was originally not thrilled about these changes, but now you're turning a lot of things into default-method interfaces, I'm getting more and more sceptical... Ideally, it's temporary but in my experience, temporary things tend to last...😅

**Comment by tandraschko** [comment]
i dont think its temporary but IMO still nicer then using util methods here
