### ISSUE TITLE
Add global criteria properties to LazyDataModel?

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#659]
It would be great if filters and sorting criteria could be added in global scope to a LazyDataModel.

This is useful in case some critera should be applied outside of the scope of the data component, like predefined sort criteria which are accessible via a `selectOneMenu`.

 Or some initial data shall be provided.

Javascript widget methods like `addFilter("bean.foo", 1)` or `addSortMeta("bean.bar", ASC)` would also be helpful.

Something like: 

```
<a onclick="PF('dataTableId').addFilter('bean.foo', 1);"/>
```
## Workaround

I extend from LazyDataModel to support it and combine global criteria with local load method criteria.

Pseudocode:

```
public class GlobalFilterLazyDataModel<T> extends LazyDataModel<T>
{
    private Map<String, Object> globalFilters = new HashSet<>();
    private List<SortMeta> globalMultiSortMeta = new ArrayList<>();

    public List<T> load(int first, int pageSize, List<SortMeta> multiSortMeta, Map<String, Object> filters)
    {
        // combine filters with globalFilters, local filters override global filters
        Map<String,Object> newFilters;

        // combine sort meta with global sort meta, local overrides global, keep order
        List<SortMeta> newMultiSortMeta;

        return this.loadImpl(first, pageSize, newMultiSortMeta, newFilters)
    }

    /* Getter and Setter to allow dynamic setting */
    public Map<String, Object> getGlobalFilters() { return this.globalFilters; }
}
```

In markup or related bean, one can now add or remove global filters and update the datatable for example.

```
<p:commandButton action="#{bean.model.globalFilters.put('bean.bar', 1)}" update="dataTableId"/>
```

**Comment by cagataycivici** [comment]
A custom implementation like yours would do the trick, no plans for a built-in one right now.
