### ISSUE TITLE
InputNumber: Does not work correctly with @Positive

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6590]
@melloware The p:inputNumber has still some flaws. Two things, I have detected now:

1) I thought that you had fixed that when p:inputNumber runs on an integer attribute that it is not needed to write decimalPlaces="0" anymore. However, this is not the case with the current snapshot.

2) When p:inputNumber runs on an integer attribute which is annotated with @Positive, then it is NOT possible anymore to save NULL for attribute. You can delete the content of p:inputNumber such that it looks empty but when you save it keeps the old value.

**Comment by melloware** [comment]
@tuerker 

1. I have an integration test for this and its passing during last nights build.

2. Yes you have to use `PostiiveOrZero`.
```java
                if (annotationClassName.equals(PositiveClientValidationConstraint.CONSTRAINT_ID)) {
                    inputNumber.setMinValue("0.0000001");
                }
                if (annotationClassName.equals(PositiveOrZeroClientValidationConstraint.CONSTRAINT_ID)) {
                    inputNumber.setMinValue("0");
                }
```

**Comment by melloware** [comment]
Integration Test:
```xml
<p:inputNumber id="inputnumber" value="#{inputNumber001.value}">
        <p:ajax process="@this"/>
</p:inputNumber>
```

```java
    @Test
    @Order(2)
    @DisplayName("InputNumber: Test integer input without decimal places default to 0")
    public void testInteger(Page page) {
        // Arrange
        InputNumber inputNumber = page.inputnumber;
        Assertions.assertEquals("50", inputNumber.getValue());

        // Act
        inputNumber.setValue("98.54");
        page.button.click();

        // Assert
        Assertions.assertEquals("99", inputNumber.getValue());
        Assertions.assertEquals("0", cfg.get("decimalPlaces"));
    }
```

**Comment by tuerker** [comment]
1) this is my code

```
    @Positive
    @Max(999999)
    @XmlElement
    private Long debitorNumber;

```
```
            <p:inputNumber
              value="#{division.debitorNumber}"
              thousandSeparator="" />

```
![Screenshot from 2020-12-02 17-17-16](https://user-images.githubusercontent.com/10051373/100899545-42908780-34c2-11eb-8de2-f1d788868c24.png)

as you see from the screenshot, the fraction of two is included (when decimalPlaces="0" is not used).

2) Actually when PostiiveOrZero is used, it can be set to NULL but however it is not the case for Positive (which i require in my use case since debitornumbers should be 0 when entered)

**Comment by melloware** [comment]
Well Positive means Positive and 0 is not Positive.  That is why Bean Validations have PositiveOrZero.  NULLing out your field I bet Bean Validations are thinking its 0 and failing validation.

**Comment by tuerker** [comment]
But this is wrong. 

The positive annotation shall ensure that only positive values are accepted besides the NULL value (if not explicitly excluded by NotNull) .

https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/Positive.html

**Comment by melloware** [comment]
Let me write some integration tests.

**Comment by melloware** [comment]
OK  I wrote 4 Integration Test scenarios:

https://github.com/primefaces-extensions/primefaces-integration-tests/commit/d35cc75805138d6e539d691402055ccc08591e3d#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

For your issue #1 it proves its not an issue and everything is working properly with `decimalPlaces="0"`.  Feel free to review my test case.

For your issue #2 it verified your problem with @Positive and it resetting the value.   I am investigating if there is anything that can be done.

**Comment by melloware** [comment]
Reproducer:
[pf-6590.zip](https://github.com/primefaces/primefaces/files/5631674/pf-6590.zip)

**Comment by melloware** [comment]
OK I know why and not sure how its possible to fix.  So in this scenario here is the widget config:
```javascript
minimumValue:"0.0000001",maximumValue:"999999",decimalPlaces:"0"
```

That is what AutoNumeric gets.  So when you blank it out and we call `var val = this.autonumeric.getNumericString();` AutoNumberic knows that blank < 0.0000001 so its returning the internal value it already has since it failed validation.

Not sure what we can do to fix this nor if we should.  So while you are right @Positive allows NULL AutoNumeric does not.  So i would say if you need this set in your InputNumber `minValue="0'` that lets you still use @Positive on the backend but allow AutoNumeric to still work on the front end.

**Comment by tuerker** [comment]
It should be fixed. Question: by whom? 

What I do not get why is @PositiveOrZero working well for the NULL case while @Positive does not. Following your explanation above, autonumeric should do the same for blank < 0 in case of @PositiveOrZero?

**Comment by melloware** [comment]
Because @PositiveOrZero does this...
```
minimumValue:"0",maximumValue:"999999",decimalPlaces:"0"
```

and AutoNumeric is treating blank "" with minValue="0" to be "" in `var val = this.autonumeric.getNumericString();`.

Most likely because of JavaScript truthiness treating 0 and "" as identical.

**Comment by tuerker** [comment]
This could be the explanation. I have tested also

    @Min(1)
    @Max(999999)

instead of 

    @Positive
    @Max(999999)

which has the same meaning. These result is the same in case of integers. So @Positive and @Min(1) behave exactly the same here.

**Comment by tuerker** [comment]
Nevertheless, autonumeric should do some revisions.

A while ago i had placed there another important issue which they did not took serious.

https://github.com/autoNumeric/autoNumeric/issues/674

I think this is also a crucial issue which must be fixed. Otherwise, we will always have this hack where certain min/max values are arbitrarily set like it is done with 

`minimumValue:"0.0000001"
`
The same holds true for decimalPlaces which should not be set to 2 be default. This is legacy coming from the wish to handle money values.

**Comment by melloware** [comment]
I think it's also your expectation of what Java  @Positive means vs what the JavaScript autonumeric MinValue means. They are not the same thing so the only way to translate positive is to give it something greater than 0 like 0.000001.  Autonumeric is then doing the correct thing saying blank "" Which means 0 < 0.00001 so it's not valid.   Once again solvable by simply putting minValue="0" on the XHTML rather than using the @Positive default.  

Like I said not sure how to solve this even from the Java side.

**Comment by tuerker** [comment]
I thinking loud. Since you set minimumValue:"0.0000001". Can't you send also "0.0000001" to autonumeric for validation in case of NULL?

**Comment by melloware** [comment]
I think that would be a hack.  What if we detect an integer type value and instead of 0.00001 we use 0. I think then everything would work?

**Comment by tuerker** [comment]
Yes, this could work.

**Comment by melloware** [comment]
@tuerker I wrote even more Integration tests proving this fix:
https://github.com/primefaces-extensions/primefaces-integration-tests/blob/master/src/test/java/org/primefaces/extensions/integrationtests/inputnumber/InputNumber004Test.java

However I did discover an issue we discussed earlier with NULL not being an instance of Long. See Test below proves the isue that when you have a Long and then you NULL it out in the backend it can no longer determine its Long. So even though you have @Positive etc because it can't tell its Long it goes back to `decimalPlaces="2"` and `minValue=0.00001.

This may be the issue you were seeing above with it being "65.00" when you expected and integer.

```java
@Test
    @Order(4)
    @DisplayName("InputNumber: GitHub #6590 Integer bean validation constraints @Positive removing value resets component")
    public void testIntegerRemovingValue(final Page page) {
        // Arrange
        InputNumber inputNumber = page.integer;
        Assertions.assertEquals("66", inputNumber.getValue());

        // Act
        inputNumber.setValue("3");
        inputNumber.getInput().sendKeys(Keys.BACK_SPACE);
        inputNumber.getInput().sendKeys(Keys.DELETE);
        Assertions.assertEquals("", inputNumber.getValue());
        page.button.click();

        // Assert
        Assertions.assertEquals("", inputNumber.getValue());

        // NOTE: because its now NULL the default decimal places is set back to 2 because its no longer an Integer
        assertConfiguration(inputNumber.getWidgetConfiguration(), "2", "0.0000001", "999999");
    }
```

**Comment by tuerker** [comment]
@melloware yes i remember the discussion. when the value is null the instanceof check cannot be done and so by definition  decimalPlaces=2 is taken.

and this is actually what i think autonumeric has to fix. the default decimalPlaces=2 is simply too restrictive.

as i wrote in that mentioned open issue at autonumeric, there should be at least the possibility to explicitly set decimalPlaces to unrestricted. it looks like that the did not get that point. it is rather a bugfix report than a feature request.

**Comment by melloware** [comment]
OK so I will commit my PR which fixes the @Positive and @negative issue with Integer type values defaulting to 0.

**Comment by jepsar** [comment]
@melloware can you please have a look at InputNumber004Test test 4? I think we should change "0.0000001" to "0" due to https://github.com/primefaces/primefaces/pull/9117

**Comment by melloware** [comment]
We should change it I think it's the same issue the unit test had.
