### ISSUE TITLE
TreeTable: rework filter, sort + add MultiViewState

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6592]
Current limitations:
- TreeTable does only support single-column-filtering
- No MultiViewState implementation
- No globalFilter + GlobalFilterFunction
- Current DataTable refactorings has moved some fields to UIColumn and removed from DataTable
- add multiSort
- add allowUnsorting

First step is to implement all these functionality, later i can check to unify code between DataTable and TreeTable

**Comment by tandraschko** [comment]
commited first draft, will make it feature complete tomorrow and add all possible showcase examples.

After that i'm going to try to reuse FilterFeature and move some features to shared default-method-interface

**Comment by Rapster** [comment]
My 2 cents, IMO I think TreeTable is broken by design... The only and main difference between DataTable and TreeTable is that one has a flat model and the other a treemodel, few features might be shared between those two components, other would probably have to change. In terms of rendering, only rows (and cells?) are different (there is the expand/collapse icon). 

I'm not saying it has to be done, but to be consider... 😅

**Comment by tandraschko** [comment]
maybe but doesnt change anything for now :D we have users, which uses the treetable with all its features, just MVS is missing. This is payed refactoring + implement MVS.

**Comment by melloware** [comment]
@tandraschko I believe this ticket also fixes these two:

#1926
#5483

**Comment by tandraschko** [comment]
@Rapster currently we have FilterableTable, SortableTable and ColumnHolder. I think we could merge them to 1 class, at least we could merge Filter and Sort?

**Comment by Rapster** [comment]
Yes i guess, I didn't really follow your devs, I suggest for that kind of dev you make a PR (do many commits as you want) so  we get the chance to have a clear idea of your changes, also you get feedbacks in return and finally whenever you feel like it's done: squash & merge it (and keep the commit history clean)

**Comment by tandraschko** [comment]
@Rapster should we merge all 3 and call it UITable?

**Comment by Rapster** [comment]
Sure

**Comment by tandraschko** [comment]
did it in 2 classes now as SubTable doesnt need filtering/sorting

**Comment by Rapster** [comment]
Mmmh... I see your point, but I would still make it one interface, it's okay if SubTable doesn't need it though it could support it if we want to.

**Comment by tandraschko** [comment]
i dont like to add many empty methods there, when they are not needed
also i dont like to make e.g. getSortByAsMap a empty default method

**Comment by Rapster** [comment]
Ah ok I thought they all contain default stuff... I guess it's okay then

**Comment by tandraschko** [comment]
@Rapster 
what about FilterMeta resolveFilterField? it still looks like old code, which doesnt use the Map?

**Comment by Rapster** [comment]
sorry i don't follow?

**Comment by tandraschko** [comment]
nvm, its based on the column. all good :D sry

**Comment by tandraschko** [comment]
there is one thing left i would like to refactor before going to the final tests.
In DataTable we have some static utils like resolveStaticField, resolveDynamicField and createValueExprFromVarField

they belong to TreeTable and DataTable actually, should move them to UISortableFilterableTable?

**Comment by Rapster** [comment]
yes

**Comment by Rapster** [comment]
What about renaming `UITable` into `ColumnAware` and `UISortableFilterableTable` into `UITable`?. `SubTable` is no table but a custom tr/td renderer. I feel that `UISortableFilterableTable` is a bit too verbose for a class name

**Comment by tandraschko** [comment]
done

**Comment by tetzla** [comment]
I'm a little bit confused: This ticket is closed, but according to the documentation the feature "MultiViewState" is not supported for the component "TreeTable": https://primefaces.github.io/primefaces/10_0_0/#/core/multiviewstate

Could you please add this feature? DataTable and TreeTable should behave as identically as possible.

**Comment by melloware** [comment]
@tetzla can you open a new ticket for TreeTable MVS support please.

**Comment by tetzla** [comment]
see https://github.com/primefaces/primefaces/issues/8756
