### ISSUE TITLE
UIPageableData: new class

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6593]
**Description**
UIData is an enchanced version of `javax.faces.component.UIData`. Actually, it's not quite accurate. UIData "supports" also pageable  feature, and fill few holes starting from JSF 2.0 (bug & enchancements). As of today, it's hard to make a distinction between PF feature and JSF impl. fixes.

Another thing, is that a lot of classes inherits from UIData PF while they don't use any features (like `p:columns`). Basically, I would like to keep UIData from PF as small as possible to clearly see the gap between UIData from JSF and PF.

**Comment by melloware** [comment]
I think this is a good idea.
