### ISSUE TITLE
limitConcurrentUploads option for FileUpload

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#66]
Expose this option of fileupload plugin to the component.

**Comment by VsevolodGolovanov** [comment]
sequentialUploads where implemented in #403. There are mistakes in description though:

> Uploads are concurrent by defaukt, set this option to false for sequential uploads.

should be

> Uploads are concurrent by default, set this option to true for sequential uploads.

**Comment by cagataycivici** [comment]
Will fix the description, thanks.

**Comment by melloware** [comment]
This was implemented as "fileLimit".  Closing as this is fixed in the docs: https://primefaces.github.io/primefaces/7_0/#/components/fileupload?id=fileupload
