### ISSUE TITLE
Is it possible to use primefaces with thymeleaf?

### ISSUE THREAD

**Issue by vicanfon** [primefaces/primefaces#6602]
I am using thymeleaf a the rendering engine of my springboot project.

Is it possible to use primefaces? how?

**Comment by Rapster** [comment]
not sure what the question is... but sure you can use PF and thymeleaf in the same app

**Comment by tandraschko** [comment]
You can not use PrimeFaces components inside a thymeleaf view. You can however use JSF+PrimeFaces on SpringBoot and serve both JSF and thymeleaf on different URLs.

**Comment by vicanfon** [comment]
> You can not use PrimeFaces components inside a thymeleaf view. You can however use JSF+PrimeFaces on SpringBoot and serve both JSF and thymeleaf on different URLs.

Thanks @tandraschko, I meant just that. using Primefaces components inside thymeleaf.

Thanks for the clarification
