### ISSUE TITLE
Datatable: filtering crash with null column values 

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6609]
@Rapster i have detected another bug. The following NPE is thrown when filtering on a datatable (which was workling for long years):

```
java.lang.NullPointerException
	at org.primefaces.model.filter.StringEqualityFilterConstraint.isMatching(StringEqualityFilterConstraint.java:42)
	at org.primefaces.component.datatable.feature.FilterFeature.filter(FilterFeature.java:168)
	at org.primefaces.component.datatable.feature.FilterFeature.decode(FilterFeature.java:109)
	at org.primefaces.component.datatable.DataTable.processValidators(DataTable.java:297)
```

The columns looks as follows:

```
  <p:column
    sortBy="#{entity[0]}"
    filterBy="#{entity[0]}"
    filterMatchMode="contains">
    <f:facet name="header">
      <h:outputText value="#{messages.yearLabel} " />
    </f:facet>
    <h:outputText value="#{entity[0]}"/>
  </p:column>

```

This datatable iterates over a list of objects:

```
public List<Object> getBookedChargeServiceHierarchy() {
        return createNativeQuery(
            "select year, servicename, servicetypename, serviceareaname, num_charges, price, discountedprice, serviceid, servicetypeid, serviceareaid from bookedchargeservicehierarchy")
            .getResultList();
    }
```

Could you please check and fix it. Thanks in advance.

**Comment by Rapster** [comment]
`StringEqualityFilterConstraint#predicate` is null which I don't see how it could happen... Are you using a custom FilterConstraint? Because `StringEqualityFilterConstraint` is never directly called from our codebase

**Comment by tuerker** [comment]
no. as you can see in this use case, we have a datatable that iterates over a list of objects that are computed via a nativequery based on a view. the expression entity[0] refers to the first column of the view which is a string value. interestingly, the filter for the numeric columns, e.g., num_chages (entity[4]), price(entity[5]), anddiscountedprice (entity[6]), are working correctly.

**Comment by tuerker** [comment]
something must have changed here since the corresponding screens were running since years.

**Comment by Rapster** [comment]
Something did change indeed... My best guess would be to debug and see when/how StringEqualityFilterConstraint is instanciated with a null predicate?

**Comment by tuerker** [comment]
line StringEqualityFilterConstraint.java:42

        return predicate.test(val, str);

states that the predicate must be null.

so the question is here: how can it be that the predicate is not set? 

I drilled down the problem: I have found out that the problem occurs when the corresponding column contains at least one null value. I hope that this helps you to fix the bug.

**Comment by tuerker** [comment]
here is a reproducer:

[p-filter-datatable.zip](https://github.com/primefaces/primefaces/files/5652204/p-filter-datatable.zip)

**Comment by tuerker** [comment]
col_2 is a column that in contrast to col_1 contains a null value. there the filter does not work.

**Comment by Rapster** [comment]
Ok I see it now

**Comment by Rapster** [comment]
Fixed. Thanks for reporting

**Comment by tuerker** [comment]
great. thanks. when it will be in the master?

**Comment by Rapster** [comment]
it's already there

**Comment by tuerker** [comment]
i see it now. thanks.
