### ISSUE TITLE
Datatable: Filtering conversion issue

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6617]
@Rapster : Found another issue: When filtering over LocalDate/LocalDateTime column, filtering is not working anymore: I get the following error when i enter "20" into the filtering box:

`Cannot convert 20 of type class java.lang.String to class java.time.LocalDateTime`

**Comment by Rapster** [comment]
Please follow issue template

**Comment by tuerker** [comment]
have no computer currently with me to create a reproducer. should be easy for you to change the type of the column of the reproducer i sent you before from string to localdatetime.

**Comment by tuerker** [comment]
here is the reproducer. thanks in advance.

[p-filter-datatable-2.zip](https://github.com/primefaces/primefaces/files/5657568/p-filter-datatable-2.zip)

**Comment by melloware** [comment]
We just got an Integration test failure after this change.
```
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.257 s <<< FAILURE! - in org.primefaces.extensions.integrationtests.datatable.DataTable008Test
Error:  testFilterIssue_5481{Page}  Time elapsed: 0.297 s  <<< ERROR!
```

**Comment by melloware** [comment]
Rerunning now I think I fixed the test.
