### ISSUE TITLE
DatePicker: year filter does not work anymore

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6619]
In the latest snapshot, the year filter is not working anymore. see screenshot below. it has some "arbitrary" range as default. in my example 2007 to 2020. if you need to go beyond that range using the prev/next buttons, the drop-down is empty.

![Screenshot from 2020-12-08 09-14-21](https://user-images.githubusercontent.com/10051373/101457873-5f9bdf00-3936-11eb-961c-25afe5b28144.png)

**Comment by melloware** [comment]
Can you post your  XHTML snippet. I have a feeling this has to do with min and max date validation.

**Comment by tuerker** [comment]
The problem occurs in both cases: 

* with and without bean validation
* and for both LocalDate as well as well for LocalDateTime

`    private LocalDate installationDate;
`
```
          <p:datePicker
            id="installationDate"
            value="#{instrument.installationDate}"
            pattern="yyyy-MM-dd"
            showButtonBar="true"
            yearNavigator="true" />

```

**Comment by melloware** [comment]
Works fine for me:
[pf-6619.zip](https://github.com/primefaces/primefaces/files/5659296/pf-6619.zip)

![image](https://user-images.githubusercontent.com/4399574/101485109-ad114f80-3928-11eb-8c17-32bfb2908864.png)

**Comment by tuerker** [comment]
thanks. i have checked your reproducer. it reveals exactly the problem i have described above.

do the following:

1) press on the year drop-down and select the first/last year (2010 or 2030)

2) if you have chosen first (2010) use the prev button to go back in the months till 2009 is reached. then the year will disappear

the same happens on the other end.

![Screenshot from 2020-12-08 14-22-11](https://user-images.githubusercontent.com/10051373/101489197-e5348480-3960-11eb-9393-d7b27a784664.png)

**Comment by melloware** [comment]
2 issues:

1. None of those steps were in your original ticket. You never mentioned going back to year 2010 etc.  So how as a dev are we supposed to debug your ticket when you don't follow the issue template.

2. You state "In the latest snapshot, the year filter is not working anymore." which is also not true.  If you run the reproducer with PF 8.0 this has NEVER worked.   So why do you state this is recently broken in 9.0-SNAPSHOT?

I appreciate you reporting bugs but please you have to be **thorough** in your description or it makes our lives impossible.

**Comment by tuerker** [comment]
i thought the bug is obvious. sorry for being not precise enough in the first description. it will try to do better.

thanks for all your efforts.

**Comment by melloware** [comment]
The bug has always been there in the JS:
```javascript
            if (this.options.yearRange === null && this.options.yearNavigator) {
                var viewYear = this.viewDate.getFullYear();
                this.options.yearRange = (viewYear - 10) + ':' + (viewYear + 10);
            }
```

**Comment by tuerker** [comment]
just a side mark: the "arbitrary" range (2007 to 2020) mentioned in the original description was sure from an example where the @PastOrPresence annotation was used. For me it looked "arbitrary" because i had no explanation why it is a 14 year range while it was somewhere else 20 years.

**Comment by tuerker** [comment]
I tried it out the latest code. The issue is still there. Have I overlooked something?

![Screenshot from 2020-12-08 17-32-54](https://user-images.githubusercontent.com/10051373/101512594-787ab380-397b-11eb-8077-d06d8f94c9fd.png)

**Comment by melloware** [comment]
Did you press CTRL+F5 to reload JavaScript?

**Comment by tuerker** [comment]
After clearing cache, it works. Thanks.
