### ISSUE TITLE
while having liveScroll on datatable some columns disappear ...  (i provide the explanation below)

### ISSUE THREAD

**Issue by zamrokk** [primefaces/primefaces#662]
i am using PF 5.2

when i am scrolling a datatable on livescroll, them the other records loaded have missing columns.

I have debugged the problem and there is something wrong with the calculation of the number of columns to be displayed on the encode function in Primefaces.

Here is the problem :   DataTableRendered.java

line 917 :
        return this.encodeRow(context, table, clientId, rowIndex, 0, table.getColumnsCount());

the last arguments will calculate on VISIBLE column ( getColumnsCount function )

then line 963 :
        for(int i = columnStart; i < columnEnd; i++) {

it will loop on ALL columns (VISIBLE OR NOT) and columnEnd variable is the one for VISIBLE columns indexes 

so at final, n columns not visible will skip n last columns that should be encoded 

Please could you correct it asap ?

**Comment by cagataycivici** [comment]
Looks similar to #607

**Comment by cagataycivici** [comment]
Should be fixed in 5.2.10 also your description is not clear.

**Comment by zamrokk** [comment]
Yes is the same issue
