### ISSUE TITLE
InputMask: IE11 not supported anymore

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#6626]
**Describe the defect**
The input mask uses the external library [0-jquery.inputmask.js](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/inputmask/0-jquery.inputmask.js) which uses `Array.prototype.includes`. This function is not available in IE11.

Is IE11 still supported in PF9?
Then maybe we should simply include a polyfill. Or at least mention it in the documentation, that a polyfill is required.

**Environment:**
 - PF Version: 9.0-SNAPSHOT
 - Affected browsers: IE11

**Comment by tandraschko** [comment]
+1 to add a polyfill
we already have some of them in a seperate file

**Comment by fanste** [comment]
I've just found the polyfill-file.

PR #6627

**Comment by tandraschko** [comment]
Thanks!

**Comment by melloware** [comment]
Thanks @fanste I should have caught this but I never test with IE11 much anymore as all my clients have dropped it as an acceptable browser.
