### ISSUE TITLE
ExceptionHander: Lost session when session tracking mode is 'URL'

### ISSUE THREAD

**Issue by dgoicocheta** [primefaces/primefaces#6628]
When session tracking mode is configured as URL in web.xml, ExceptionHander don't append the jsessionid param to the location of error page, the session is lost and, all the exception info is lost in page error.

**To Reproduce**
Configure sesion tracking mode as URL in web.xml, 
```
<session-config>
        <tracking-mode>URL</tracking-mode>
</session-config>
```
Configure ExceptionHandler as usual in faces-config.xml, launch a exception, and in the redirect error page, the jsessionid param is missing and the exception info is lost.

In ajax mode without redirect the ExceptionHander works properly.

**Environment**
All versions of PF and JSF.

Example proyect:
[primefaces-test-exceptionhandler.zip](https://github.com/primefaces/primefaces/files/5665435/primefaces-test-exceptionhandler.zip)

**Expected behavior**
When session traking is 'URL' the jsessionid must be appended to the location of error page.

**Workarround in PF 9.0**
In PF 9.0 you can add manually the jsessionid to the location page in web.xml with EL expresion `<location>/error.jsf;jsessionid=${session.id}</location>`
but i think it's not the correct solution

**Comment by tandraschko** [comment]
should work now, please test test test

**Comment by dgoicocheta** [comment]
The solution an works with myfaces, but no with mojarra, I review the ExternalContext.encodeRedirectURL method from myfaces and mojarra, and while myfaces uses the encodeRedirectURL from HttpServletResponse, mojarra only append the collection map parameters, not the jsessionid, Maybe it`s a bug from mojarra i don't know.

**Comment by dgoicocheta** [comment]
> 
> 
> should work now, please test test test

The solution an works with myfaces, but no with mojarra, I review the ExternalContext.encodeRedirectURL method from myfaces and mojarra, and while myfaces uses the encodeRedirectURL from HttpServletResponse, mojarra only append the collection map parameters, not the jsessionid, Maybe it`s a bug from mojarra i don't know.

**Comment by tandraschko** [comment]
should be better now

**Comment by dgoicocheta** [comment]
Ok, tested with mojarra 2.2 and 2.3 (2.2.20,  2.3.14), and myfaces 2.2 and 2.3 (2.2.12, 2.3.7)  and it's work.

**Comment by melloware** [comment]
Excellent thanks for testing!
