### ISSUE TITLE
DataTable: mutli-sort does not always respect priority

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#6637]
The whole refractoring regarding #5438 reverted the functionality of #4557.

1. `UITable.getSortMetaAsString` now returns ALL sort meta instead of only the active sort meta.
2. `UITable.getSortMetaAsString` returns the sort meta at a random order, not according the priority.
3. `LazyDataModel.load#multiSortMeta` is a `HashMap` and a user has to sort the meta according the priority before it could be applied to e.g. the DB-query
4. It seems to work (untested, only based on code) for internal sorting via `SortFeature.sort` as it converts the sort meta map to a `LinkedHashMap` sorted using `SortMeta.compare`

In the most cases (if not all), the sort meta has to be applied according to the priority or the result is not the desired one. Multiple possibilities: 
- Why not always provide a sorted map (`LinkedHashMap`)? => sort it after the initial map was built and after sort feature was decoded
- Provide at least a utility to sort the map according to the priority so not every user has to implement the priority-sorting.

Regarding error 1 & 2: The returned string must always contain the sort meta sorted by priority. Additionally it should only contain the active sort meta or the `datatable.js` has to be fixed as it only expects active sort meta.

**Comment by fanste** [comment]
I already started to implement a PR #6638 before you assigned the ticket to yourself, @Rapster.

If you have a own/better implementation, feel free to close my PR.

**Comment by Rapster** [comment]
Cool, i'll do the review then

**Comment by fanste** [comment]
Most probably a refactor would be even better to really make `sortByAsMap` a `LinkedHashMap` which eliminates the sorting at all other places.

**Comment by melloware** [comment]
+1 we use linkedHashMap in all of our custom implementations.

**Comment by Rapster** [comment]
I quite expected that issue to happen, but I was hoping to fix it once we figure out #6532, but it's not gonna happen in this release... I made few changes to your PR, otherwise it looked good 😉
