### ISSUE TITLE
Chips: validator acts on list instead of item

### ISSUE THREAD

**Issue by svenhaag** [primefaces/primefaces#6640]
Using e.g. `<f:validateLongRange minimum="0" maximum="42" />` in the chips component does not work as the validator acts on the value list instead of the single items.
Adding a valid integer item results in a validation error.
It seems impossible to use `List<Integer>`.

On the other hand, adding a string to the int list immediatelly throws an error. The validator is not called at all.

**Environment:**
 - PF Version: 8.0.2
 - Mojarra 2.3.14

**Expected behavior**
The validator validates an added item before the item is finally added to the list.

**Comment by tandraschko** [comment]
i will mark it as new feature as its by design.
normally the "value" of a component is validated and the value is a List for a "selectMany" component

**Comment by svenhaag** [comment]
Hi @tandraschko, so it's designed to work with `List<String>` only? Please also refine the documentation on this.

**Comment by tandraschko** [comment]
looks like other types are supported as i can see converter supporter in our code

**Comment by svenhaag** [comment]
The convert works property on the single items.

**Comment by tandraschko** [comment]
yep

**Comment by melloware** [comment]
so what is the action here?

**Comment by tandraschko** [comment]
unsure
we have to check e.g. selectMany* first

**Comment by svenhaag** [comment]
> 
> 
> The convert works property on the single items.

To me, the (item) converter does not make any sense if validator acts on the list.

**Comment by melloware** [comment]
Reproducer:
[pf-6640.zip](https://github.com/primefaces/primefaces/files/5697209/pf-6640.zip)

I think your only choice now is to write a custom validator...
See "Custom Validator" here: http://incepttechnologies.blogspot.com/p/validation-in-jsf.html

**Comment by svenhaag** [comment]
Thanks @melloware, that's exactly what I already did. Like so:
```
public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
  List list = (List) value;
  for (Object entry : list) {
    if (null != entry) {
      final long longValue = Long.parseLong(String.valueOf(entry));
      if (666L == longValue) { // exemplary
        throw new ValidatorException(...);
      }
    }
  }
}
```
Additionally I have set up a ValueChangeListener to modify (sort and make unique) the Chips entries, like so:
```
public void handleChipsValueChange(final ValueChangeEvent event) {
	final List<String> newList = ((List<String>) event.getNewValue());
	newList.removeAll(Collections.singleton(null));
	newList.sort(Comparator.comparingInt(Integer::valueOf));

	// remove duplicates in place
	final Set<String> deDuplicated = new HashSet<>();
	Iterator<String> it = newList.iterator();
	while (it.hasNext()) {
		final String entry = it.next();
		if (deDuplicated.contains(entry)) {
			it.remove();
		} else {
			deDuplicated.add(entry);
		}
	}
}
```

Cheers

**Comment by melloware** [comment]
Excellent! That is the beauty of JSF.  If something doesn't work the way you want plugging in an fixing it with customization is so easy!

**Comment by melloware** [comment]
I am going to close this for now as the current expectation of validators is correct and this workaround is easy enough to implement.

**Comment by melloware** [comment]
Actually the more i think about this maybe it should handle this.  reopening.

**Comment by melloware** [comment]
Thomas is right the default here is to validate the input which is the list of items. A custom converter is the way to go.
