### ISSUE TITLE
Chips: Unique/Distinct entries

### ISSUE THREAD

**Issue by svenhaag** [primefaces/primefaces#6643]
The p:chips component should ignore duplicate entries.
Make this feature configurable with an attribute.

**Comment by melloware** [comment]
Similar to `p:collector` the attribute should be called `unique`.  For example `unique="true"`

**Comment by melloware** [comment]
Integration Test: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/1bdd2727f2582f2e728aa75b8ec63550c0c2e86d
