### ISSUE TITLE
multipart/form-data support in p:commandButton in ajax mode

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#665]
multipart/form-data support in p:commandButton in ajax mode is not working in PF5.3 
http://forum.primefaces.org/viewtopic.php?f=3&t=38163

h:commandButton do support multipart/form-data in ajax mode

**Comment by cagataycivici** [comment]
We don't support it, use advanced uploader instead which is way better.

**Comment by melloware** [comment]
Fixed in 9.0. See: https://github.com/primefaces/primefaces/issues/6360
