### ISSUE TITLE
Chips: Stop ENTER propagating to Row Editor

### ISSUE THREAD

**Issue by HalitTalha** [primefaces/primefaces#6666]
Having a component that depends on ENTER key event, like chips, inside a rowEditor appears to cause event propogation kind of troubles.
Let's say you will enter a tag via the chips input, when you hit ENTER, rowEditor also responds to that.

I suggest making the functionality originally proposed here #433 optional. Otherwise users of the API will have to solve this with less intuitive workarounds.

I personally chose this workaround for my case; I removed the event binding for the corresponding css class at the right document event callbacks.

**Comment by melloware** [comment]
So is your issue specific to Chips or do you have other components in mind that this happens with?

**Comment by melloware** [comment]
I fixed the Chips issue with that PR.  AutoComplete looks like it already had this fix.   So are there other components triggering the RowEditor close when you press Enter that is not expected behavior besides chips?

**Comment by HalitTalha** [comment]
It is only chips for my case.
Thanks alot for the quick fix
