### ISSUE TITLE
Datatable: clearFilter widget function should support custom filters

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6669]
Below you will find a repoducer which demontrates that a datatable filter is not cleared when it is created using a facet-filer.

[p-facet-filter-datatable.zip](https://github.com/primefaces/primefaces/files/5697235/p-facet-filter-datatable.zip)

To reproduce the problem:

1) select true or false from the selectonemenu of colum 1 and enter "00" into the filter of the second column
2) now use the radio-buttons on/off which are simply invoking "clearFilters()"

The filter of column 1 is not clear while the filter of column 2 is cleared.

Many thanks in advance.

**Comment by tuerker** [comment]
```
  <h:form>
    <h:selectOneRadio
      value="#{entityView.selector}"
      onclick="PF('entityVar').clearFilters()">
      <f:selectItem itemValue="true" itemLabel="on" />
      <f:selectItem itemValue="false" itemLabel="off" />
      <p:ajax
        event="change"
        update="entityTable" />
    </h:selectOneRadio>

    <p:dataTable id="entityTable" var="entity" value="#{entityView.entities}" widgetVar="entityVar">
      <p:column
        sortBy="#{entity[0]}"
        filterBy="#{entity[0]}"
        filterMatchMode="contains">
        <f:facet name="header">
          <h:outputText value="c1" />
        </f:facet>
        <f:facet name="filter">
          <h:selectOneMenu onchange="PF('entityVar').filter()">
            <f:selectItem itemLabel="#{messages.noFilterLabel}" />
            <f:selectItem itemValue="true" />
            <f:selectItem itemValue="false" />
          </h:selectOneMenu>
        </f:facet>
        <h:outputText value="#{entity[0]}" />
      </p:column>
      <p:column
        sortBy="#{entity[1]}"
        filterBy="#{entity[1]}"
        filterMatchMode="contains">
        <f:facet name="header">
          <h:outputText value="c2" />
        </f:facet>
        <h:outputText value="#{entity[1]}" />
      </p:column>
    </p:dataTable>
  </h:form>

```

**Comment by Rapster** [comment]
Indeed, so far clearFilters only support native filter

**Comment by Rapster** [comment]
Did you try using `.ui-column-filter` class?

**Comment by melloware** [comment]
i think i have an idea

**Comment by melloware** [comment]
This should do it:
```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.clearFilters = function() {
        this.thead.find('> tr > th.ui-filter-column > .ui-column-filter').val('');
        this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter :input').val('');
        $(this.jqId + '\\:globalFilter').val('');
        this.filter();
    };
}
```

**Comment by tuerker** [comment]
> This should do it:
> 
> ```js
> if (PrimeFaces.widget.DataTable) {
>     PrimeFaces.widget.DataTable.prototype.clearFilters = function() {
>         this.thead.find('> tr > th.ui-filter-column > .ui-column-filter').val('');
>         this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter :input').val('');
>         $(this.jqId + '\\:globalFilter').val('');
>         this.filter();
>     };
> }
> ```

Many thanks. However, I could not manage it. I added this code fragment to my util.js file. But it has no effect even after having cleared the browser's cache several times.

**Comment by melloware** [comment]
Here is your reproducer using PF 8.0 which has the bug but I added the snippet to test.js.
[pf-6669.zip](https://github.com/primefaces/primefaces/files/5702565/pf-6669.zip)

If you test this you should see its working fine.

**Comment by tuerker** [comment]
I got it working now. Thanks again.

**Comment by melloware** [comment]
No prob thanks for reporting!
