### ISSUE TITLE
Button inside p:contentFlow not working

### ISSUE THREAD

**Issue by araza26** [primefaces/primefaces#667]
The problem is here on button <p:commandButton value="#{row.fileId}" action="#{fileOnDeskViewDlgBacking.fileNoting(row.fileId)}" /> the method does not pass fileId and it resolved to null, where as #{row.fileId} alwasys give its value.

MORE It do work in p:dataTable, there is any problem with the component i think.

Following is my code:
<p:contentFlow value="#{fileOnDeskViewDlgBacking.filesContentFlowList}" var="row">
<p:panel styleClass="filePanel" >
<p:outputLabel value="#{row.srNo}" />
        <p:panelGrid styleClass="borderless" columns="2">
           <p:graphicImage name="/dashboard/images/file_64px.png"/>

```
        <p:panelGrid styleClass="borderless" columns="1">
            <p:outputLabel value="(#{row.subject})" />
        </p:panelGrid>
    </p:panelGrid>
    <p:outputLabel style="color:#3D83B5;" value="Files#{row.date}">
        <f:convertDateTime pattern="dd/mm/yyy HH:mm" />
    </p:outputLabel>
    <h:panelGrid styleClass="borderless" columns="2">
        <p:outputLabel value="FileId:" />
        <p:outputLabel styleClass="wrapText" value="#{row.Id}" />

        <p:outputLabel value="Description:" />
        <p:outputLabel styleClass="wrapText" value="#{row.description}" />

        <p:outputLabel value="Heading:" />
        <p:outputLabel value="#{row.name}" />

        <p:outputLabel value="Priority:" />
        <p:outputLabel value="#{row.priorityName}" />

        <p:outputLabel value="Type:" />
        <p:outputLabel value="#{row.typeName}" />

        <!-- <p:outputLabel value="Created By:" />
        <p:outputLabel value="#{row.createdBy}" /> -->

    </h:panelGrid>
    <p:spacer height="5px" />
    <p:separator />
    <p:commandButton value="#{row.fileId}" action="#{fileOnDeskViewDlgBacking.fileNoting(row.fileId)}" />
</p:panel></p:contentFlow>
```

**Comment by cagataycivici** [comment]
Code format is broken but this is expected as contentFlow is not a data component, workaround is to send parameters via f:param and read it from request parameter map to identify which record is clicked. Kinda old school but a valid workaround for components that do not extend from UIData such as datatable e.g. contentFlow but tend to repeat their content.
