### ISSUE TITLE
Datatable: dynamic content switch issue

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6671]
I have detected another issue with the datatable component. Below you will find a repoducer which demontrates the problem.

[p-datatable-paginator.zip](https://github.com/primefaces/primefaces/files/5701616/p-datatable-paginator.zip)

Quick description of the setting: 

* There are two lists: the first with 11 records, the second with 6 records.
* There is a selector to switch between these two lists.

To reproduce the problem:

* Use the radio button to switch between these two lists and carefully check the content of the datatable and the shown numbers in the paginator.

* Both are wrong.

* When clicked on all, 11 records should be shown but only the iniital six are shown in the content. In the paginator, the filtered number of records is still 6 but the total record size is correct, i.e. 11.

![Screenshot from 2020-12-16 10-25-58](https://user-images.githubusercontent.com/10051373/102330938-77084700-3f8a-11eb-819d-19517045827d.png)

* Then, click on "true only", 6 records should be shown but now all 11 records are shown. Accordingly, the number of the filtered records in the paginator are 11 while the total record size is correct again, i.e. 6.

![Screenshot from 2020-12-16 10-26-19](https://user-images.githubusercontent.com/10051373/102330957-7c659180-3f8a-11eb-966c-cac2c9d7c48b.png)

* Interestingly, when you click twice on the same radio-item, then you get the result that you have expected originally.

Would be great if you can check this. Many thanks in advance.

**Comment by melloware** [comment]
I fixed your example. Its working fine.  You had an AJAX ordering issue.
[pf-6671.zip](https://github.com/primefaces/primefaces/files/5703325/pf-6671.zip)

```xml
 <p:ajax
        event="change"
        update="entityTable" 
        oncomplete="PF('entityVar').clearFilters()"/>
```

**Comment by tuerker** [comment]
i see. i have adapted my code accordingly. 

@melloware i really appreciate your great responsiveness and the quality of your responses. thank you very much.

**Comment by melloware** [comment]
No problem. Thanks for the reproducers it makes our job so much easier to debug a problem if we can see it!
