### ISSUE TITLE
HeadRenderer: When Session tracking is 'URL', HeadRenderer don't add the jsesionid param to the resources

### ISSUE THREAD

**Issue by dgoicocheta** [primefaces/primefaces#6674]
**Reproducer**
When session tracking mode is 'URL', the jsesionid must be appended to the resources url.
HeadRenderer don't append the jsessionid to the css and validation resources, then new session is created on every request.

**Environment:**
 - PF Version: all
 - JSF + version: all

**Expected behavior**
HeadRenderer must encode resources to append jsessionid

**Comment by melloware** [comment]
Thanks for reporting I created this PFE issue as its ShortCut Icon would have the same issue:
https://github.com/primefaces-extensions/primefaces-extensions/issues/248
