### ISSUE TITLE
DataTable: refactor/fix filterBy/sortByMap lifecycle

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6688]
Currently the maps are initialized in #initSortBy; this is correct done for sortBy but not for filterBy. FilterBy is initialized multiple time.
Also user-defined filterBy, global and MVS is applied multiple times then.

How should it looks:

1) ViewScoped filter/sortByMap should be intialized the getter; when there is no state available yet, the ViewScoped state should be initialized there. so initFilterBy/initSortBy should be called there. NOTE: our eval lamba does evaluate the default value, not a initial value, we have to set it directly like in #getColumnMeta)
2) initFilterBy/initSortBy should create the initial map based on
     - user defined via xhtml
     - user defined via code (sortBy/filterBy attr)
     - global (only for filter?)
     - MVS
3) so when the 2) is done, the sort/filterBy is only updated on a sort and filter request, therefore i introduced the new UITableFeatures to make it reusable for both; on a sort/filter request, we also need to synch back the updated filter/sortBy to MVS

**Comment by tandraschko** [comment]
i hope this are just some small refactorings

**Comment by Rapster** [comment]
Before I do anything, there is one PR I need to merge and one I need to polish ('cause it's been bugging our app for a while...). And if I'm start working on this before them, I'll have to resolve conflicts which I've been doing to many times lately...

Regarding initialization, as far as I can remember, it's initialized once and updated every request.

**Comment by tandraschko** [comment]
also it seems that SortMeta isnt sorted by priority, i think we have to add this somewhere to sort this map in each request

**Comment by Rapster** [comment]
I'm gonna assign it to you, as you've been bringing a lot of changes recently to DataTable you'll be able to do changes according to what fits best for you
