### ISSUE TITLE
OL3 Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#67]
Hi,

OL3 is a "A high-performance, feature-packed library for all your mapping needs".

It would be great to have ol3 components implemented by primefaces team.

Best regards,

Robert

**Comment by kukel** [comment]
Has already been worked on by someone: https://github.com/themrleon/JSF2Leaf. Baybe join efforts?

**Comment by cagataycivici** [comment]
Not sure, for new features we prefer implementing it ourselves as a team. Especially for big tickets.

**Comment by melloware** [comment]
I am closing this ticket as I have opened a PrimeFaces Extensions issue where a new component like this can incubate.

**Comment by melloware** [comment]
OpenStreeMap will be in Extensions 14.0.1: https://github.com/primefaces-extensions/primefaces-extensions/issues/128
