### ISSUE TITLE
Layout: top and south units are not displayed

### ISSUE THREAD

**Issue by dimonrv** [primefaces/primefaces#6703]
**Describe the defect**
The example (https://www.primefaces.org/showcase/ui/panel/layout/nested.xhtml) does not display layout unit "Middle top unit content" and "Middle south unit content".

**Environment:**
 - PF Version: 8.0
 - JSF + version: _e.g. Mojarra 2.3.2
 - Affected browsers: ALL

**Comment by melloware** [comment]
Layout has been removed in 9.0. It is recommend to switch to straight CSS or to the PFE version of Layout.

See: https://github.com/primefaces/primefaces/issues/2168
