### ISSUE TITLE
SelectOneMenu: one of yesterdays (21.12.2020) commits broke integration-tests

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6707]
Error:  Failures: 
Error:    SelectOneMenu001Test.testBasic:45 expected: `<Max>` but was: `<MaxMax>`
Error:    SelectOneMenu002Test.testSelectItemGroup:50 expected: `<Volkswagen>` but was: `<VolkswagenVolkswagen>`
Error:    SelectOneMenu005Test.testHideNoSelectionOption:54 expected: `<4>` but was: `<9>`
[INFO] 
Error:  Tests run: 142, Failures: 3, Errors: 0, Skipped: 2

https://github.com/primefaces-extensions/primefaces-integration-tests/actions/runs/436866298

**Comment by christophs78** [comment]
This issue was introduced by https://github.com/primefaces/primefaces/commit/c303520232406391d855b95d729232a904094db2 @mertsincan

**Comment by melloware** [comment]
Issue: https://github.com/primefaces/primefaces/issues/6700

I am looking into this.

**Comment by melloware** [comment]
OK my PR constrains the new fix just to the Safari browser.

**Comment by melloware** [comment]
Integration tests are passing again.
