### ISSUE TITLE
DataTable: component broken when updated with draggableColumns

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6714]
Open
http://localhost:8080/showcase/ui/data/datatable/displayPriority.xhtml?jfwid=ab131

and add:
`<p:commandButton value="Update" process="@this" update="@form"/>`

**Comment by tandraschko** [comment]
@melloware 
would you like to check it? Its related to #5582

**Comment by melloware** [comment]
Yep let me look.

**Comment by melloware** [comment]
OK I tested with your scenario and its fixed and tested against original #5582 scenarios and they remain fixed.

**Comment by tandraschko** [comment]
thanks!
