### ISSUE TITLE
Define type attribute in AutoComplete

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#672]
Primefaces does not support "type" in AutoComplete and InputText so we can handle HTML5 features:
http://www.w3schools.com/html/html_form_input_types.asp

Origin of the issue is to set type="search" in order to display the cross in the input once something have been typed.

Post: http://forum.primefaces.org/viewtopic.php?f=3&t=43065&p=135269

**Comment by cagataycivici** [comment]
Pass through attributes can help? e.g. pt-type="search"

**Comment by Rapster** [comment]
Not working with AutoComplete using two ways as explained here: https://jsflive.wordpress.com/2013/08/08/jsf22-html5/

(Did not try with InputText so far, but given the example it should work)

**Comment by cagataycivici** [comment]
Which JSF version do you have and PF?

**Comment by Rapster** [comment]
Mojarra 2.2.9 and PF 5.2
