### ISSUE TITLE
Timeline: Support B.C. Dates

### ISSUE THREAD

**Issue by ufuk23** [primefaces/primefaces#6721]
In the last version, you force that DateTime with timezone should be used for the timeline component. We would like to see the timeline component for past times. In the previous versions, we could see a date which is past like B.C but now we could not. How could we do that? Is there any way to do it?

Feature request:
The timeline component should support the past like B.C.

**Comment by melloware** [comment]
@ufuk23 Can you give an example of how you currently construct a BC Date currently?  When you say last version supported B.C. do you mean PrimeFaces 7? And you are now using 8?


And Timeline should support LocalDate as well so for 100 .B.C for example..
```java
LocalDate ld = LocalDate.of(-100, 1, 1);
```
That should be 100 B.C. is that working?

**Comment by ufuk23** [comment]
Thanks for your help. The Primefaces version 6 we used was working, but we could not get it work version 8. We can set the date like this LocalDate.of(-1200,1,1), but client side has an error about jquery and cannot show the past correctly.

**Comment by melloware** [comment]
OK let me investigate.

**Comment by melloware** [comment]
Confirmed for `LocalDate.of(-140, 1, 1).atStartOfDay();` its sends this JS to the browser `new Date('-0141-12-31T22:00:00-04:56:02')`

Which is not a valid date.
![image](https://user-images.githubusercontent.com/4399574/103141475-bdfce780-46c2-11eb-95b8-f8903decdfa3.png)


Explained here why this is messy: https://stackoverflow.com/questions/25846123/how-to-format-bc-dates-like-700-01-01
