### ISSUE TITLE
DataTable: RowGroup does not work anymore

### ISSUE THREAD

**Issue by buunsal** [primefaces/primefaces#6731]
Grouping features no longer works on Primefaces 9 with the current showcase on github master.
![image](https://user-images.githubusercontent.com/45278820/103252999-51b70800-4990-11eb-943e-8f5862f5d504.png)

@tandraschko Could this has occurred after your last commits?

**Comment by tandraschko** [comment]
will check it on weekend

**Comment by tandraschko** [comment]
seems like this commit https://github.com/primefaces/primefaces/commit/7dba5cb7fdf185ecdf2a03515103faa9f57ca585 broke it
not sure why, i fixed sorting afterwards

**Comment by tandraschko** [comment]
[pf-2672.zip](https://github.com/primefaces/primefaces/files/5752255/pf-2672.zip)

**Comment by tandraschko** [comment]
@Rapster do you know how HeaderRow/rowGrouping works? maybe you have a short idea here

**Comment by Rapster** [comment]
Yeah, from what I can see sorting doesn't seem to be working. The condition on columnKey is never verified:
```java
 default void invokeOnColumn(String columnKey, Consumer<UIColumn> callback) {
        forEachColumn((column) -> {
            if (column.getColumnKey().equals(columnKey)) {
                callback.accept(column);
                return false;
            }
            return true;
        });
    }
```
sorting is then not called.

**Comment by tandraschko** [comment]
@Rapster fixed it now and added comments that we have to refactor that code when you refactored column grouping

**Comment by christophs78** [comment]
We need to add integration-tests for RowGroup. :-)
