### ISSUE TITLE
DataTable: checkbox selection not fully checked on click 

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6734]
**Describe the defect**
A picture is worth a thousand words. So let me show you (or you can reproduce on showcase)
![selection](https://user-images.githubusercontent.com/7521311/103317882-e3745300-4a2c-11eb-90f6-e413e985199a.gif)

In 2 words, checkbox selection is not fully checked on first click. My best assumption _(and I can be completely wrong)_ is that, this problem came with the new themes (I don't recall this problem showing before) but it seems to be a mishmash with js and css

**Environment:**
 - PF Version: 9.0-SNAPSHOT
 - Affected browsers: Chrome, Edge

**To Reproduce**
1. Go to http://localhost:8080/showcase/ui/data/datatable/selection.xhtml
2. Checkbox selection
3. Click on checkbox
4. See weird behavior

**Expected behavior**
Just the usual selection 😅

**Comment by melloware** [comment]
I noticed this too. I will investigate and fix. I think I know what is happening.

**Comment by melloware** [comment]
OK its being captured by two different click events and they are at war.

1. Row Click itself.
```javascript
.on('click.dataTable', this.rowSelector, null, function(e) {
            $this.onRowClick(e, this);
            $this.mousedownOnRow = false;
        });
```

2. and Checkbox click

```javascript
.on('click.dataTable', checkboxSelector, null, function() {
                            var checkbox = $(this);

                            if(checkbox.attr('aria-checked') === "true") {
                                $this.unselectRowWithCheckbox(checkbox);
                            }
                            else {
                                $this.selectRowWithCheckbox(checkbox);
                            }
                        });
```

So I think in the RowClick I need to jump up if its the `ui-chkbox-box` being clicked. I can't do it with a clever RowSelector I don't think as the whole TR gets the click event.

**Comment by melloware** [comment]
@Rapster I moved your issue to the Showcase as its a PrimeOne theme issue and nothing to do with core PF code.

See: https://github.com/primefaces/primefaces-showcase/issues/258

**Comment by Rapster** [comment]
Sounds good
