### ISSUE TITLE
Draggable datatable in a p:dialog problem [BUG]

### ISSUE THREAD

**Issue by jjcampos** [primefaces/primefaces#675]
When creating a draggable datatable inside a p:dialog component every time I try to move a line from one position to another inside the datatable the selected line appears behind the dialog. In the same "z-index" as the overlay div which is behind the dialog.

Everytime you move the a row the "z-index" attribute for the dialog div gets updated but not the div for the moved row.

The image below shows the erratic behavior:
![image](https://cloud.githubusercontent.com/assets/1906804/9611305/4dbced7a-50b5-11e5-8902-de673b3d850f.png)

Looking into the primefaces javascript I saw that this behavior is happening because the "PrimeFaces.zindex" variable is not getting updated when the "div" of the moved row gets created

Unfortunately I was unable to find the exact location to fix the problem so I couldn't provide a patch. I'm still trying though.

I was able to detect that this issue is directly related with the "appendTo" attribute on the p:dialog component. In order to my dialog open over the overlay I had to add this attribute as appendTo="@(body)"  if I don't use this the dialog appears behind the overlay therefore I cant access it.

When I do not use this attribute and via google development tools I get rid of the overlay everything works fine see the image below: 
![image](https://cloud.githubusercontent.com/assets/1906804/9611671/52b4c3fa-50b7-11e5-9bac-62057107c20f.png)

The p:dialog code I used to cause the problem:
p:dialog id="testDialog" header="Dialog test" modal="true" widgetVar="wvTestDialog" appendTo="@(body)" position="center" width="400" closable="false"

modal="true" or modal="false" -> also causes the same problem

I'm using primefaces version 5.1 (also tested in version 5.2 with same behavior) with JSF 2.2.4.

**Comment by andythefox** [comment]
I had the same issue today with a DataTable on a modal dialog.
My workaround is the following piece of CSS:

``` css
.ui-datatable.ui-sortable-helper {
    z-index: 2000 !important;
}
```

**Comment by jjcampos** [comment]
Hi there @AndyKay80 !! Thank you for your piece of code it did the trick. Although you should be aware that 2000 is a fairly low number since the Primefaces updates the z-index value for the dialog window everytime you drag a row which leaves you a window of 1000 changes. Here in my application the user do a lot more than that. So I change it to 10000 !!

Thank you very much.

But the bug persists! I hope the Primefaces guys fix it.
