### ISSUE TITLE
BreadCrumb: style new accessible HTML

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6757]
See #4928

@melloware can you take care of setting the theme label and milestone? And maybe assign @mertsincan

**Comment by melloware** [comment]
Done

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primefaces/commit/4260e749c00648c86ba0a29ea5dc0e418206ff9a

Thanks a lot, @jepsar ;)
