### ISSUE TITLE
p:ajaxExceptionHandler does not work with generic type of exceptions

### ISSUE THREAD

**Issue by sergi-mm** [primefaces/primefaces#676]
Hello,
The component _p:ajaxExceptionHandler_ as is only supports **one Exception** class by defining the attribute _type_:
`<p:ajaxExceptionHandler type="java.lang.Exception" onexception="PF('errorDialog').show()" />`

The problem is that if the exception thrown in ajax is a NullPointerException (which extends java.lang:Exception), the sample code does not work, it only works when `type="java.lang.NullPointerException"`

The problem is in the class [AjaxExceptionHandlerVisitCallback#50](https://github.com/primefaces/primefaces/blob/7a640b825cee43e0f874441df156525bd0321a32/src/main/java/org/primefaces/component/ajaxexceptionhandler/AjaxExceptionHandlerVisitCallback.java#L50) where comparing the Exception thrown with the type type:

``` java
if (throwable.getClass().getName().equals(currentHandler.getType())) {
                handler = currentHandler;
                return VisitResult.COMPLETE;
            }
```

To correctly check if _throwable_ is instanceof _java.lang.Exception_ or _java.lang.NullPointerException_, you should replace by something like this:

``` java
try {
                Class<?> clazz = Class.forName(currentHandler.getType());
                if (clazz.isInstance(throwable)) {
                    handler = currentHandler;
                    return VisitResult.COMPLETE;
                }
            } catch (ClassNotFoundException e) {
                Logger.getLogger(AjaxExceptionHandlerVisitCallback.class.getName()).log(Level.SEVERE, e.getMessage());
            } 
```

Hope this can be fixed and included in next Primefaces release.
Thanks.

**Comment by tandraschko** [comment]
Done in trunk. Please give it a tray.

**Comment by sergi-mm** [comment]
Hi, I was looking your commit (https://github.com/primefaces/primefaces/commit/645bee9e124ec977a99de7e1421ac886749630e2) and don't want to annoy you, but don't you think is bit inneficient to iterate over classes and looking in a Map for the right class name? Don't would be better to simply check if the class defined in the AjaxExceptionHandler component is **instanceOf** the exception thrown?  The method `Class.instanceOf(Object o)` already checks all superclasses and you will avoid to create a Map with handlers...

It's only my opinion, but I would like to understand your point of view.

Regards,
Sergi

**Comment by tandraschko** [comment]
Please see: https://github.com/primefaces/primefaces/issues/609

We need to iterate through the inheritance hierarchie because:

Exception extends Throwable
ExceptionA extends Exception
ExceptionB extends ExceptionA

<p:ajaxExceptionHandler type="ExceptionA" />
<p:ajaxExceptionHandler type="Throwable" />

When a ExceptionB will be thrown by the application, the handler for ExceptionA must be used and not the handler for Throwable.
Therefore we need to iteratore trough the inheritance hierarchie.

Also the performance of my code isn't bad and it's a "exception", not the normal case.

**Comment by sergi-mm** [comment]
Ok, I understand your point of view. The thing here is the **order** in which the component is placed in the view, so in case you put the "Throwable" in first place, it will capture all the exceptions, right? But in your example, it will only capture exceptions that doesn't extends from ExceptionA.

Anyway, I tried a similar case with my code defining two _ajaxExceptionHandler_ and throwing a ViewExpiredException (which it also extends Throwable):

``` xml
<p:ajaxExceptionHandler type="ViewExpiredException" />
<p:ajaxExceptionHandler type="Throwable" />
```

And it worked fine executing the first handler.

**Comment by tandraschko** [comment]
Exactly, the order doesn't matter.
