### ISSUE TITLE
POM: Exclude certain transitive dependencies

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6760]
**Describe the defect**
To prevent some `provided` dependencies from being used in code we should `exclude` those transitive dependencies from the pom.xml.

Example: Commons Collections4

**Comment by Rapster** [comment]
Did you try this:
```xml
<exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
```

It should exclude all transitive dependencies in a less verbose way

**Comment by melloware** [comment]
I did not try that. I usually only ever exclude individual but I like this idea better.

**Comment by melloware** [comment]
OK I tried it and it excludes too much and the build fails. So I will leave the precisions excludes for now.
