### ISSUE TITLE
FileUpload: 7.0.18 regression in Safari no longer working in dialog

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#6768]
Seems like there is some regression in version 7.0.18 when using `p:fileUpload` within a `p:dialog`.
Under Safari, nothing happens. Under Chrome, a second "open file" dialog is shown, and then it works.
7.0.17 does not have this issue.

It seems like `p:fileUpload` is only affected when used within a `p:dialog`. Outside a `p:dialog` it is still working.

**Comment by melloware** [comment]
I have a feeling its this: https://github.com/primefaces/primefaces/issues/6700

**Comment by fcorneli** [comment]
@melloware Looking at the source code diff between 7.0.17 and 7.0.18 that is indeed the only possibility.

**Comment by melloware** [comment]
@fcorneli thanks for checking we assigned this to Mert.  It broke our Integration Test suite so we reverted it in Master.  Those Integration Tests are coming in really handy!

**Comment by stolp** [comment]
I just experienced the same behavior using 8.0.6 with Brave. Reverting to 8.0.5 fixed this issue.

**Comment by fcorneli** [comment]
@melloware I noticed the work on the PrimeFaces Integration Tests. Very nice! Now, if somebody could run them **BEFORE** a release, that would be even better. :)
@stolp Thanks for sharing this info, I already have several projects running on 8, will revert them too.

**Comment by melloware** [comment]
> @melloware I noticed the work on the PrimeFaces Integration Tests. Very nice! Now, if somebody could run them **BEFORE** a release, that would be even better. :)

We are working on that for the future.... Our goal is to have every commit run against the suite.

**Comment by JuanMiguelBG** [comment]
I experienced the issue in 8.0.6 and 7.0.18 too with both Chrome a Firefox. I've been to revert to 8.0.5 and 7.0.17 versions.

**Comment by melloware** [comment]
Yep this will be fixed in 8.0.7 and 7.0.19
