### ISSUE TITLE
UIData: remove Mojarra hacks and rowStatePreserved backport for JSF 2.0

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6773]
2.1 is there since 2010 and Mojarra should be stable enough now.

**Comment by tandraschko** [comment]
i already removed this stuff locally: https://gist.github.com/tandraschko/b9168b3bc4982f5ce3eab373f32244b4
basically we overwrite some Mojarra code because their internal "isNestedInIterator" doesnt work for PrimeFaces components

i think we should only apply it after adding some intergrationtests for old cases, too
we need do check old google issues
and some tests where multiple datatables are nested in a ui:repeat e.g.

would be great if someone has time

**Comment by melloware** [comment]
@tandraschko I am not positive but I don't think multiple datatable works in `ui:repeat` right now see: https://github.com/primefaces/primefaces/issues/3812

So I am not sure that is worth testing.

**Comment by stolp** [comment]
In my PrimeFaces 10 application, I am using a p: tabView with p:repeat over p:tabs containing a p:dataTable each.

This is so far working for me, but I am not using selection.

So yes, this pattern is in use out there.

**Comment by melloware** [comment]
> In my PrimeFaces 10 application, I am using a p: tabView with p:repeat over p:tabs containing a p:dataTable each.
> 
> This is so far working for me, but I am not using selection.
> 
> So yes, this pattern is in use out there.

Interesting that this has been PrimeTek's stance on this issue: https://github.com/primefaces/primefaces/issues/3812#issuecomment-710003755

**Comment by stolp** [comment]
I stand corrected: It is indeed a <c:forEach>

**Comment by tandraschko** [comment]
TBH i think PF is just doing something wrong if everything works but no selection
therefore i would like to have some tests, so we know at least what works and what not

**Comment by melloware** [comment]
Mojarra 2.3.18, 3.0.3 and 4.0 fixed their `isNestedIterator` finally with this...

```java
public static boolean isNestedInIterator(FacesContext context, UIComponent component) {
        UIComponent parent = component.getParent();

        if (parent == null) {
            return false;
        }

        for (UIComponent p = parent; p != null; p = p.getParent()) {
            if (p instanceof UIData || p instanceof UIRepeat) {
                return true;
            }
        }

        // https://github.com/eclipse-ee4j/mojarra/issues/4957
        // We should in long term probably introduce a common interface like UIIterable.
        // But this is solid for now as all known implementing components already follow this pattern.
        // We could theoretically even remove the above instanceof checks.
        Pattern clientIdNestedInIteratorPattern = getPatternCache(context.getExternalContext().getApplicationMap()).computeIfAbsent(CLIENT_ID_NESTED_IN_ITERATOR_PATTERN, k -> {
            String separatorChar = Pattern.quote(String.valueOf(UINamingContainer.getSeparatorChar(context)));
            return Pattern.compile(".+" + separatorChar + "[0-9]+" + separatorChar + ".+");
        });

        return clientIdNestedInIteratorPattern.matcher(parent.getClientId(context)).matches();
    }
```

**Comment by tandraschko** [comment]
Perfect
Lets remove both p:repeat and cleanup UiData in v13

**Comment by melloware** [comment]
Perfect tickets created and marked for 13.0.0

**Comment by Rapster** [comment]
Just catching up, but if `p:repeat` has been removed on account that `ui:repeat` is now stable in 2.3, that means users who are in 2.2 must upgrade to JSF 2.3 (otherwise they stuck with 12.0.0 so they can user `p:repeat`). That kinda put them in a fix no?

**Comment by melloware** [comment]
i think we decided 2.2 came out almost 10 years ago and most of those users stay on PF 6 or 7 and never seen to upgrade anyway.  So I think it was about "thinning out hacks" in the PF code that were workarounds to JSF.  It actually works in MyFaces 2.2 it just Mojarra that is the issue.

**Comment by Rapster** [comment]
Indirectly I feel, we asking users to upgrade to Mojarra 2.3 then? But PF remains compatible with 2.2 (because of MyFaces like you said) 

>   * `p:repeat` in favor of `ui:repeat` (both Mojarra and MyFaces support what this used to do)

Maybe it worth mentionning Mojarra 2.3 here

**Comment by melloware** [comment]
Yeah in the code in 12.0.0: https://github.com/primefaces/primefaces/pull/8825/files

The 12.0.0 Migration guide has this..

## Repeat
  * **Repeat** is deprecated. Apache MyFaces all versions and Mojarra 2.3.18, 3.0.3, 4.0+ please switch to ui:repeat.


The code does this:
```java
if (environment.isMojarra()) {
            LOGGER.log(Level.WARNING, "Mojarra versions 2.3.18, 3.0.3, and 4.0+ do not require p:repeat, "
                        + "please upgrade and switch to ui:repeat.");
        }
        else {
            LOGGER.log(Level.WARNING, "Apache MyFaces does not require p:repeat, please switch to ui:repeat.");
        }
```

**Comment by Rapster** [comment]
Oh my apologies, I didn't look in the 12 migration guide 😅 Looks great!

Considering the name of this issue, shouldn't we also remove rowStatePreserved, rowIndex?

**Comment by melloware** [comment]
Yeah the Repeat we handled with this ticket: https://github.com/primefaces/primefaces/issues/8824  Since it was a separate issue.  This one I left because I didn't quite understand what needed to come out of UIData.

**Comment by Rapster** [comment]
Don't think there is anything else to do here... Closing for now
