### ISSUE TITLE
DataTable: Add emptyMessage localization support

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#6774]
**Description**
I always need to set a `p:datatable`s `emptyMessage` to a localized string. Often times I just forget that though. The text "`No records found.`" seems to be hard coded into 
`src/main/java/org/primefaces/component/datalist/DataListBase.java`,  
`src/main/java/org/primefaces/component/datagrid/DataGridBase.java` and  
`src/main/java/org/primefaces/component/treetable/TreeTableBase.java`.

**Solution**
This is something I would really like to see added to something like the [PrimeFaces Locales Javascript API](https://github.com/primefaces/primefaces/wiki/Locales).

**Comment by melloware** [comment]
Please see my PR.  This is localized now using the server side `Messages.properties` or if you language was German you would include a `Messages_de.properties`.

Not in the JavaScript locales API since this is not used in JS only in Server Side loading.

**Comment by zhedar** [comment]
Thanks for your efforts, that was fast! Looking forward to added that to me properties file. That's what I actually meant.

**Comment by melloware** [comment]
Hopefully this will go into 10.0 which is schedule to have RC1 release in the next couple of weeks.

**Comment by stolp** [comment]
Perhaps we should add a place to keep some pre-translated message files as seen for some js Localizations?

**Comment by melloware** [comment]
I have to update the docs to include this.  Right now this only talks about client side localication:
https://primefaces.github.io/primefaces/10_0/#/core/localization
