### ISSUE TITLE
ContextMenu: Datatable long touch is not working on IOS

### ISSUE THREAD

**Issue by ebaykal** [primefaces/primefaces#6776]
Datatable Context Menu is not working on Iphone IOS (Safari and Chrome). On Android, touch & hold opens the Contextmenu, but it is not working on Iphone (both Safari and Chrome).

**Reproducer**
The example shown in PF Showcase is not working on IOS too.
https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

**Environment:**
 - PF Version: _8.0.6_
 - JSF 2.2
 - Affected browsers: iOS

**To Reproduce**
1. Go to 'https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml' with iOS device 
2. Touch & Hold on row to see context menu
3. Text selection mode is started instead of showing context menu

**Expected behavior**
Datatable context menu should be shown with Touch & Hold action on iOS.

**Example XHTML**
All source coding is exist at page => https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

**Comment by melloware** [comment]
I have confirmed this issue with my iPhone
