### ISSUE TITLE
jQuery UI Touch Punch: Upgrade to 1.0.8

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#6779]
Hi,

We had a penetration testing of our application using Primefaces 8.0 and got this finding:

 >jQuery UI Touch Punch 1.0.5
>URL: .../javax.faces.resource/jquery/jquery-plugins.js
>
>NODEJS:328 Cross-Site Scripting (XSS) -> https://vulners.com/nodejs/NODEJS:328
>NODEJS:329 Cross-Site Scripting -> https://vulners.com/nodejs/NODEJS:329
>NODEJS:330 Denial of Service -> https://vulners.com/nodejs/NODEJS:330

Primefaces uses the jQuery UI Touch Punch fork by RWAP:
https://github.com/RWAP/jquery-ui-touch-punch

Maybe Primefaces should upgrade to the current release of this fork: 1.0.8

**Comment by melloware** [comment]
Let me investigate

**Comment by melloware** [comment]
@OBreidenbach I can confirm the 1.0.5 version we are currently using has none of these issues. I think your pentration tester is reporting false positives.   Or its falsely identiifying Touch Punch but really the problems are in Jquery UI which has fixed all these issues but they have not done an offical 1.13 release yet.  

I have considered doing a custom build of Jquery UI for PF to fix these issue but I would have to discuss with PrimeTek.

For now I upgraded this plugin to 1.0.8 which adds Microsoft Surface support.

**Comment by OBreidenbach** [comment]
@melloware Thanks for looking into this and sorry for opening this ticket as the library does not have these issues.
Just out of curiosity. You signed this ticket to release 10.0. Does this mean that release will be released soon?

**Comment by melloware** [comment]
10.RC1 is going to be released in the next 2 weeks!   And I have been given permission to upgrade Jquery UI which fixes these issues for 10.0.  That will be in another ticket.

**Comment by OBreidenbach** [comment]
Thanks for this fast responce.

**Comment by melloware** [comment]
@OBreidenbach just to double check what version of PF are you running 8.0 or Elite 8.0.5 etc when they ran this PEN test?

**Comment by melloware** [comment]
And also do you know what tool was used to produce these results?

**Comment by OBreidenbach** [comment]
@melloware we are using PF 8.0 the community version. I will ask which tool was used and come back to you.

**Comment by melloware** [comment]
OK so the issues above were fixed in 8.0.2 with this ticket: https://github.com/primefaces/primefaces/issues/5807

It will of course be in the 10.0 community release as well.

**Comment by OBreidenbach** [comment]
@melloware If you are still interested, which tool was used: https://github.com/portswigger/software-vulnerability-scanner

**Comment by melloware** [comment]
Thank you for letting me know I will check it out!
