### ISSUE TITLE
9.0 git tag

### ISSUE THREAD

**Issue by flashboss** [primefaces/primefaces#6788]
Where is the 9.0 tag in github repository?

**Comment by melloware** [comment]
We never released 9.0 PF is going right to 10.0 from 8.0.  So there will be a 10.0 GIT tag when its released in the next month.

**Comment by flashboss** [comment]
cool... will the 10 version be compliant with jakartaee 9?

**Comment by tandraschko** [comment]
it is, check the docs (https://primefaces.github.io/primefaces/10_0_0/#/gettingstarted/download), readme or google pls next time.
