### ISSUE TITLE
Menubar: Inactive submenu visible

### ISSUE THREAD

**Issue by JHookDev** [primefaces/primefaces#6796]
**Describe the defect**
There are times when mousing over the menubar where a submenu will become visible even though another submenu is active and open. The erroneous submenu will be visible, however the submenu heading is not highlighted. The erroneous submenu will remain open until the user interacts with that specific submenu again. The user can interact with other submenus, while the erroneous submenu is open. I've attached a screenshot depicting the issue. Through debugging I've found that it's related to the addition of the delay attribute, and calling setTimeout called in PrimeFaces.widget.Menubar.prototype.showSubmenu. Since setTimeout places a message on the queue for the browser to process once there is no script processing, it's running into a situation where the submenu is no longer the active submenu by the time it 'shows' the submenu.

![PrimeFaces - menubar - stuck submenu reproducer - screenshot](https://user-images.githubusercontent.com/18311972/104219173-6620e900-5403-11eb-8b46-7badde46df71.png)

**Reproducer**
Reproducer attached
[primefaces-test-menubar-stuck_submenu.zip](https://github.com/primefaces/primefaces/files/5797482/primefaces-test-menubar-stuck_submenu.zip)

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _Mojarra 2.2.20_
 - Affected browsers: _Tested on Chrome, Brave and Firefox_

**To Reproduce**
It can be a little difficult at times to recreate the issue, generally it occurs as a user is mousing quickly across the menubar from right to left and vice versa. Sometimes using a circular type motion from left to right.
1. Mouse over the menubar from left to right and vice versa, and even where the mousing is not necessarily linear.
4. See submenu open that is not 'active' along with other submenus still showing and hiding as expected.

**Expected behavior**
Submenus in the menubar should not display if they aren't the active submenu.

**Example XHTML**
See attached reproducer

**Example Bean**
N/A

**Comment by melloware** [comment]
Good debugging and thanks for the reproducer.

**Comment by JHookDev** [comment]
I have a PR that I will submit shortly.
