### ISSUE TITLE
Schedule: Background Events

### ISSUE THREAD

**Issue by aligit** [primefaces/primefaces#6798]
**Description**
To prevent date selection(dateSelect) in a given date interval I've to close the pop-up right after it's opened. This is frustrating because the user has to click in order to notice that reservation at selected date is not possible.

**Describe the solution you would like**
I would like an additional attribute in the scheduler which accepts start and end date/time and the cells in this time interval are visually distinguishable(color as another attribute). FullCalendar apparently does that through [Background Events](https://fullcalendar.io/docs/background-events)

**Additional context**
Ideally opening of calendar should be optional. 

**Example XHTML**
```xml
          <p:schedule
            id="scheduleGrid"
            backgroundEventStartDate="#{bean.bgStartDate}"
            backgroundEventEndDate="#{bean.bgEndDate}"
            backgroundEventColor="#{bean.bgColor}"
            backgroundEventPopUp="true"
            widgetVar="scheduleWidgetVar"
            value="#{bean.lazyEventModel}">
          </p:schedule>
```

Thanks in advance

**Comment by melloware** [comment]
Two things...

1. Wouldn't Background Events be part of the Model and not properties on the Timeline?

2. Can you make any event not have the popup appear if you mark that event `editable="false"` so you can choose which events bring up the popup or not?  Or am I missing something?

**Comment by melloware** [comment]
Usage:
```java
event = DefaultScheduleEvent.builder()
				.title("")
				.startDate(LocalDateTime.now().minusDays(4))
				.endDate(LocalDateTime.now().minusDays(3))
				.overlapAllowed(true)
				.editable(false)
				.resizable(false)
				.display("background")
				.backgroundColor("lightgreen")
				.build();
eventModel.addEvent(event);
```

Screenshot:
![image](https://user-images.githubusercontent.com/4399574/104373920-1c153180-54ef-11eb-8719-724605c32c4b.png)

**Comment by aligit** [comment]
Great! Thanks! @melloware
