### ISSUE TITLE
Datatable: Grouped keyboard selection

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#6799]
**Describe the defect**
Grouped Data Table key up/down only select the prev/next row within the current group. I'm not sure if it was itentional or not

**Reproducer**
Data Table with group and active selection

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.8 or MyFaces 2.3.6_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. Select a row
2. Press up (or down) on the keyboard
3. If the first (or last) row of a group is selected we cannot navigate further

**Expected behavior**
One should be able to select the row in the prev/next group

**Comment by Mich2424** [comment]
https://github.com/primefaces/primefaces/pull/6800

**Comment by crocimi** [comment]
#6800
