### ISSUE TITLE
ColumnToggler doesn't work if parent is invisible

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#68]
p:columnToggler inside p:accordionPanel, p:tabView or p:wizard doesn't work

The list component works properly only with the first visible tab.

**Comment by sudheerj** [comment]
Not able to replicate on PF 6.0-SHANSHOT.The columnToggler works properly inside naming containers as mentioned above.

**Comment by kukel** [comment]
@sudheerj: Most likely fixed due to one of the checkins related to https://github.com/primefaces/primefaces/issues/523 and all. Please check one release earlier to (either snapshot or current Elite) and mark it 'fixed' if it fails in earlier versions

**Comment by tandraschko** [comment]
Not replicateable anymore: #2369
