### ISSUE TITLE
Core: Remove redundant initializer

### ISSUE THREAD

**Issue by arturobernalg** [primefaces/primefaces#6802]
Java will initialize fields with known default values so any explicit initialization of those same defaults is redundant and results in a larger class file (approximately three additional bytecode instructions per field).

**Comment by tandraschko** [comment]
can you proove your statement?
I would say that the compiler should produce same bytecode if you not init a boolean or init it with boolen=false

**Comment by arturobernalg** [comment]
> can you proove your statement?
> I would say that the compiler should produce same bytecode if you not init a boolean or init it with boolen=false

Hi @tandraschko 

The PR try to solve a PMD warning --> https://pmd.github.io/latest/pmd_rules_java_performance.html#redundantfieldinitializer
