### ISSUE TITLE
DataView: Multiple drop events for a single drag and drop operation with DataViewGridItems

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#6803]
**Describe the defect**
I was playing with drag and drop in a data view and noticed that for some drop operations multiple DragDropEvents are generated. I was yet not able to determine a reproducible behavior here.

**Reproducer**
Clone: https://github.com/stolp/primefaces-test/tree/PF-6803

This is basically the DataView showcase code with added draggable, droppable and an event listener.

I tried both with PrimeFaces 8.0 and 10.0-SNAPSHOT.

**Environment:**
 - PF Version: _8.0_, _10.0_
 - JSF + version: _Mojarra 2.2.20_
 - Affected browsers: _ALL_

**To Reproduce**
1. Activate the DataGrid view
2. Drag one Car and drop it on another car (repeat for different cars)
3. Watch the console log messages

**Expected behavior**
One drop operation should generate exactly one DragDropEvent.

**Comment by melloware** [comment]
I think I see the issue. If I drag and completely hover over another Car and drop I only get one event. If I drag and hover in between two panels it drops it and then move the other one with a drag drop.  So its like it has to move both panels.

**Comment by stolp** [comment]
This issue is not yet on the list of issues for the 10.0 milestone. Is there any chance that a fix will be part of PrimeFaces 10?

**Comment by tandraschko** [comment]
Yeah, work on a proposal and PR 😜

**Comment by ghost** [comment]
> I think I see the issue. If I drag and completely hover over another Car and drop I only get one event. If I drag and hover in between two panels it drops it and then move the other one with a drag drop. So its like it has to move both panels.

None of the panels are actually moved. 

I tested it with the reproducer. A separate drop event is logged for each panel on which the dragged panel is dropped.

- Drag a panel over another panel -> 1 event is logged
- Drag a panel over two panels -> 2 events are logged, one for each panel
- the same is true for three and four panels

**Comment by melloware** [comment]
PR is welcome if it seems like it is tracking drag over every panel its dragged over that seems like the bug.

**Comment by ghost** [comment]
Update: the tolerance of the droppable was set to "touch" (as in the showcase and the documentation) , therefore each droppable that the draggable was dropped onto was (rightfully) receiving a drop event. Using tolerance="pointer" solves this issue.

**But** I noted that the default value of the tolerance attribute (fit, pointer, touch or intersect) is not documented in https://primefaces.github.io/primefaces/10_0_0/#/components/dragdrop?id=droppable , it just states that the default value is "null".

It is indeed "intersect":

https://github.com/primefaces/primefaces/blob/7341b3936aac3a69e9bcf2116ab9d0fdab93f3b5/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.js 

`$.widget( "ui.droppable", {
	version: "1.12.1",
	...
		tolerance: "intersect",`

This should be noted in the documentation imho.

**Comment by melloware** [comment]
@klaffke great detective work.  See my PR I have updated the taglib and the docs.  I will also update the DND DataView showcase example to "pointer".
