### ISSUE TITLE
DatePicker: Clear button does not reset the time fields

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#6810]
**Describe the defect**
I have a datePicker with showTime="true" showOnFocus="true" showButtonBar="true".

When hitting the clear button, the time selector is not reset, it stays at the current time.

**Reproducer**
Please clone the following Repository: https://github.com/stolp/primefaces-test/tree/PF-6805

**Environment:**
 - PF Version: _8.0_, _10.0_
 - JSF + version:  Mojarra 2.2.8
 - Affected browsers: _ALL_

**To Reproduce**
1. Click in the datepicker field
2. Select date and time
3. Hit clear
4. Select another time

**Expected behavior**
Clear button should reset the entered time

**Comment by melloware** [comment]
Thanks for the reproducer!

**Comment by melloware** [comment]
I wrote an Integration test for this so its caught in the future.
