### ISSUE TITLE
ChartJS: Upgrade to V3

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6812]
Something we should keep in mind for PrimeFaces 11.
They are currently at https://github.com/chartjs/Chart.js/releases/tag/v3.0.0-beta.8.

https://www.chartjs.org/docs/master/getting-started/v3-migration

**Comment by christophs78** [comment]
As ChartJS 3 is gone into RC-state i´ll start to work on this.

**Comment by melloware** [comment]
Reproducer for stacked group charts...

[stacked-group.zip](https://github.com/primefaces/primefaces/files/8770688/stacked-group.zip)

**Comment by jarciano** [comment]
We upgraded Babylon to 6.0.0 with Primefaces 6.0.4 and the error persists.

[[Charts createStackedBarModel](https://forum.primefaces.org/viewtopic.php?f=98&t=72619&p=200253#p200253)](https://forum.primefaces.org/viewtopic.php?f=98&t=72619&p=200253#p200253)

**Comment by melloware** [comment]
I just don't see how Babylon is affecting it as it should work the same in all themes like my reproducer works in Saga theme.
