### ISSUE TITLE
TreeTable regression: NodeSelectEvent has no tree node

### ISSUE THREAD

**Issue by Helveticus** [primefaces/primefaces#6828]
Describe the defect
I am using an ajax 'select' event to keep track of a single tree node selection.  With the latest snaphot, the tree node in the NodeSelectEvent is null. It appears that the Javascript no longer returns the tree node identifier.

Reproducer

                <p:treeTable id="mytree"
                             value="#{bean.root}"
                             var="node"
                             selectionMode="single"
                             selection="#{bean.selectedNode}"
                             dynamic="true">

                    <p:ajax event="select"
                            listener="#{bean.onNodeSelect}"
                            update="@this" />

                    <p:column headerText="Title">
                        <h:outputText value="#{node.name}" />
                    </p:column>
                </p:treeTable>

Environment:

    PF Version: 10.0 Snaphot
    JSF + version: Mojarra 2.3.9
    Affected browsers: ALL

Expected behavior
NodeSelectEvent getTreeNode() should return the selected node like it did in PF 8.

**Comment by tandraschko** [comment]
seems like the showcase is also broken: http://localhost:8080/showcase/ui/data/treetable/selection.xhtml?jfwid=266ad

**Comment by melloware** [comment]
I see the problem.

**Comment by melloware** [comment]
@tandraschko the Showcase is broken for a different reason i notified PrimeTek on Discord.
