### ISSUE TITLE
PanelGrid: Regression, Exception when all rows in a panel grid are conditional

### ISSUE THREAD

**Issue by Helveticus** [primefaces/primefaces#6829]
**Describe the defect**
In a panel grid where all rows have a rendered attribute, Primfaces throws an exception:

javax.faces.FacesException: PanelGrid without a 'columns' attribute expects at least one <p:row> element.

**Reproducer**
n/a

**Environment:**
 - PF Version: 10.0 Snapshot
 - JSF + version: _e.g. Mojarra 2.3.9
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**

**Expected behavior**
Used to work in PF 8

**Example XHTML**
<p:panelGrid id="gridid">
  <p:row rendered="#{bean.showme eq 'yes'}">
    <p:column>some column title</p:column>
    <p:column>#{bean.description}</p:column>
  </p:row>
</p:panelGrid>

```

**Comment by melloware** [comment]
I will fix this.
