### ISSUE TITLE
fileUpload not working when contentType set to xhtml+xml

### ISSUE THREAD

**Issue by mulderbaba** [primefaces/primefaces#683]
When contentType attribute of f:view is set to "application/xhtml+xml", fileUpload component is not working and giving JS errors on client side.

<img width="899" alt="screen shot 2015-09-05 at 23 57 32" src="https://cloud.githubusercontent.com/assets/603285/9701269/e7e2fcce-5429-11e5-9e46-d11249962042.png"/>

**Comment by cagataycivici** [comment]
application/xhtml+xml not supported especially on webkit.
