### ISSUE TITLE
New Component: CascadeSelect

### ISSUE THREAD

**Issue by buunsal** [primefaces/primefaces#6832]
CascadeSelect displays a nested structure of options.

**Comment by mertsincan** [comment]
@melloware Can I get help from you for JsDoc? Is there a command code to generate them automatically?
Exp;
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by melloware** [comment]
@mertsincan Yep let me review it and make any tweaks I see needed. Nice job though!
