### ISSUE TITLE
Core: remove deprecates introduced in 8.0

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6841]
Deprecated but still used:
- ~CalendarUtils#calculateTimeZone~
- `TimeLineModel#getIndex` (not sure what I'm supposed to do with this...)
- `p:chart` untouched as the whole component will be deprecated

**Comment by Rapster** [comment]
@christophs78 You certainly have a better understanding of what to do regarding Calendar component. Is it truly deprecated or is it too soon?

@jasonex7 You deprecated `TimeLineModel#getIndex` but still used, and also you're saying index is no longer required but instead of removing that method, you're suggering to turn into a private method. I'm not very familiar with this component, and I'm kinda confused of what I should do here

**Comment by christophs78** [comment]
Regarding Calendar. Think we have to look how much DatePicker - issues come up after 10.0.0 - release.
With 7.0 DatePicker was way to much broken. With 8.0 it was better but still had issues compared to Calender.
Hope we hit with 10.0 the point where people realy prefer DatePicker over Calendar.

**Comment by Rapster** [comment]
Okay so if I understand it well, these methods have no reason to be deprecated as they can't be removed or replaced, they will be removed only when Calendar component will be removed from PF.

**Comment by christophs78** [comment]
Looked into the code...
`CalendarUtils#calculateTimeZone` is used for `java.util.Date` - support. (For Calendar and DatePicker) So deprecated is relative. We should not use this for new code. But we have to keep this as long as we need to support java.util.Date. So probably for a long long time.

But it should be easy to get rid of `DatePatternConverter `and `TimePatternConverter`. Both simply call `DateTimePatternConverter`. So why not directly call `DateTimePatternConverter`?

**Comment by melloware** [comment]
We should undeprecate java.util.date stuff as we plan on supporting it for a long long time as there is just too much code out there written for it.

**Comment by Rapster** [comment]
@christophs78 Ok I see what you mean regarding the converters, indeed it should be easy to get rid of them since both delegate call to `DateTimePatternConverter`. Now about `CalendarUtils#calculateTimeZone`, I think it should be undeprecated just like mentionned @melloware.

**Comment by Rapster** [comment]
@melloware You might be able to enlight me on `TimeLineModel#getIndex`, since index is no longer used and no longer need to be sync with whatever what... I feel this method is no longer useful, am I wrong?

**Comment by melloware** [comment]
Let me take a look.  I think it might no longer be needed I will get back to you.

**Comment by Rapster** [comment]
Ok, if so I think we should remove `TimeLineModel#update` methods, and move `TimeLineModel#updateAll` into `TimeLineUpdater`

**Comment by Rapster** [comment]
I just realized that TimeLineEvent has setters and a builder, and setters are not marked deprecated... Oversight? For that kinda of class, setters could return current TimeLineEvent instance, specially if they're supposed to be mutable (and no need of a builder), but I guess Builder was used to be more consistent with the rest of the code? Should I mark them deprecated? Also `TimelineEvent#Builder#build` should ensure startDate is not null, and if id null a default one should be set.

I'll do that in a separate PR

**Comment by christophs78** [comment]
> @christophs78 Ok I see what you mean regarding the converters, indeed it should be easy to get rid of them since both delegate call to `DateTimePatternConverter`. Now about `CalendarUtils#calculateTimeZone`, I think it should be undeprecated just like mentionned @melloware.

Agree
