### ISSUE TITLE
Datatable "On-Demand Data"Live scrolling feature doen't work on Chrome zoomed in/out

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primefaces#685]
Hi,

Issue: Datatable's liveScroll="true" doesn't work on Chrome browser when Zoomed in or Zoomed out. 
Component: p:dataTable
Browser: Google Chrome
Versions: Up to latest version 5.2. 
Replicated on Showcase: Yes

**Comment by sekmiller** [comment]
From our project, it appears that it is the presence of a footer on the data table that causes the live scrolling to fail.

**Comment by melloware** [comment]
@kishor-p @sekmiller I can't reproduce in the latest showcase and Chrome 62.  https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml

Can either of you verify?
