### ISSUE TITLE
SelectOneMenu: JS error calling disable()

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6851]
**Describe the defect**
Found during Integration Testing...

When calling the widget `disable()` method throws the following JS error using the Showcase.

![image](https://user-images.githubusercontent.com/4399574/104950852-726eee00-598f-11eb-8f2a-13ab332ae729.png)

This can happen whenver the items are rendered on the client.

```java
.attr("renderPanelContentOnClient", menu.getVar() == null,  false);
```

**Environment:**
 - PF Version: _10.0_

**Expected behavior**
The SelectOneMenu should be disabled.

**Example XHTML**
```html
<p:selectOneMenu id="hideNoselectionOption" value="#{selectOneMenuView.hideNoSelectOption}"
                                hideNoSelectionOption="#{not empty selectOneMenuView.hideNoSelectOption}">
         <p:ajax update="@this" process="@this"/>
         <f:selectItem itemLabel="Select One" itemValue="#{null}" noSelectionOption="true"/>
         <f:selectItem itemLabel="Option1" itemValue="Option1"/>
          <f:selectItem itemLabel="Option2" itemValue="Option2"/>
          <f:selectItem itemLabel="Option3" itemValue="Option3"/>
</p:selectOneMenu>
```

**Comment by melloware** [comment]
@christophs78 this was introduced with https://github.com/primefaces/primefaces/issues/6418

**Comment by melloware** [comment]
Failing Integration Test now passes!

![image](https://user-images.githubusercontent.com/4399574/104957579-69384e00-599c-11eb-8cf4-e3d04626f0d8.png)

**Comment by christophs78** [comment]
Thanks for fixing this!
