### ISSUE TITLE
New Component: ConfirmPopup

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#6853]
ConfirmPopup displays a confirmation overlay displayed relatively to its target.

**Comment by tandraschko** [comment]
@mertsincan cant we reuse ConfirmDialog here?

**Comment by melloware** [comment]
@tandraschko are you suggesting use confirm dialog but have a `popup="true"` ?

**Comment by mertsincan** [comment]
@tandraschko ConfirmDialog and ConfirmPopup have different UI.
https://primefaces.org/primereact/showcase/#/confirmpopup
https://primefaces.org/primereact/showcase/#/confirmdialog

**Comment by tandraschko** [comment]
for me it looks the same:
confirmPopup == confirmDialog header=null closable=false :D

**Comment by mertsincan** [comment]
Is it the same for you on overlayPanel and Dialog :D
These choices depend entirely on the user's need. I can generate multiple components from an overlayPanel using CSS :D :D

**Comment by tandraschko** [comment]
hmm, i see
what about a different name then? For me "dialog" is a name as "popup" but actually means the same :D

also the build is currently broken

**Comment by melloware** [comment]
I would guess its ConfirmPopup to be consistent with PrimeReact/Vue/NG.  Which is not a terrible thing.
