### ISSUE TITLE
databable, filter row

### ISSUE THREAD

**Issue by tecbea** [primefaces/primefaces#686]
Hi,
it will be great to have the option of filter of datable on new row, instead of the row of the labels;

**Comment by kukel** [comment]
they kind of are... they are all beneath the labels

**Comment by tecbea** [comment]
the looking stays much better if separated in rows;

**Comment by sudheerj** [comment]
I didn't see filters in separate rows much.Do you have any demo examples where it used?

**Comment by tecbea** [comment]
http://openfaces.org/demo/datatable/DataTable_general.jsf

**Comment by melloware** [comment]
@tandraschko its been three years I think its safe to close this suggestion as no one else has really asked for it and the PF Filters are probably not going to change.
