### ISSUE TITLE
Core: migrate String nullity check with LangUtils

### ISSUE THREAD

**Issue by arturobernalg** [primefaces/primefaces#6860]
The idea is use isEmpty instead  of "length() == 0"
In the case of " "".equals" it performance issues
! isEmpty  instead if length() > 0

**Comment by Rapster** [comment]
I don't think it's about performance here (on the contrary...), though it sounds very similar to #2513. Ideally, every nullity check on String should be turned into a LangUtils.isBlank/isNotBlank

**Comment by stolp** [comment]
I actually agree with @Rapster's comment about the consistent use of Util-Classes, but from back experience this is also a great opportunity to introduce hidden bugs at a late stage.

And to add my two cents: As commons-lang is basically partly reimplemented here, I think that the seperation between StringUtils, CollectionUtils etc. should be applied to LangUtils as well. But maybe this has been discussed before.

**Comment by melloware** [comment]
@Rapster I totally agree.  @Stolp we still have RC2 so even though its late its not like 10.0 isn't being release final until end of Feb.

**Comment by tandraschko** [comment]
we will apply it after 10.0 Final, no need to apply cosmetics now
