### ISSUE TITLE
TimeLine: Using CSP breaks JS

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6868]
**Describe the defect**
Using timeline with CSP=true is failing Integration Tests and this was proven locally.

![image](https://user-images.githubusercontent.com/4399574/105234036-a3d6ed80-5b38-11eb-9564-c05dab9a425c.png)

**Environment:**
 - PF Version: _10.0.0-rc1_

This is because the "standalone" vis-timeline build must be used.

See: https://github.com/visjs/vis-timeline#standalone-build

**Comment by melloware** [comment]
CC @sqores

**Comment by melloware** [comment]
For **charlietran1986**

Download and unzip this:
[pf-csp.zip](https://github.com/primefaces/primefaces/files/5852029/pf-csp.zip)

Run `mvn clean jetty:run` and go to http://localhost:8080/primefaces-test/test.xhtml

**Comment by charlie1986** [comment]
I have created new Enable command button to enable back input text, but the browser console still throws such error.
[pf-csp.zip](https://github.com/primefaces/primefaces/files/5862549/pf-csp.zip)

**Comment by melloware** [comment]
Just tried your reproducer. Its because there is no "enable" script in test.js.  So there is no function to call unless I am not seeing it?

**Comment by melloware** [comment]
Ahh you are disabling too much. You can't disable hidden inputs like ViewState or you break JSP. I tweaked your example so now it works...
[pf-csp-working.zip](https://github.com/primefaces/primefaces/files/5862608/pf-csp-working.zip)
