### ISSUE TITLE
DataTable: column field based on array-valued iteration

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6872]
I have a lot of generic data tables (based on native queries delivering `List<Object>`) with columns of the following form, where `entity` is the name of the iteration variable and the columns are the values of that array-valued entity:

```
  <p:column
    sortBy="#{entity[0]}"
    filterBy="#{entity[0]}">
    <f:facet name="header">
      <h:outputText value="#{messages.yearLabel}" />
    </f:facet>
    <h:outputText value="#{entity[0]}" />
  </p:column>
  <p:column
    sortBy="#{entity[1]}"
    filterBy="#{entity[1]}">
    <f:facet name="header">
      <h:outputText value="#{messages.numberLabel}" />
    </f:facet>
    <h:outputText value="#{entity[1]}" />
  </p:column>
...
```
Currently, i do not see how to use the new field notation in this case. So the following (with or without the square brackets) does not work :

```
  <p:column
    field="[0]"
    headerText="#{messages.yearLabel}" />
...
```
How can this be done? If it cannot be done currently, please make a feature request out of it. Many thanks in advance.

**Comment by tandraschko** [comment]
thats a question for @Rapster

**Comment by Rapster** [comment]
Issue tracker is meant for issues or features purposes, otherwise please use forum and ping me on discord. Can you provide a reproducer of your first sample please?

**Comment by tuerker** [comment]
@Rapster here is the reproducer. 

[p-datatable-field.zip](https://github.com/primefaces/primefaces/files/5849037/p-datatable-field.zip)

when you comment out the second table, you will see the working one.

**Comment by Rapster** [comment]
Since var is no pojo, there is no field

**Comment by tuerker** [comment]
This is not an urgent issue since there is a working solution. However, in the long run it would be good if non-pojo vars could be consistently used with the field attribute.
