### ISSUE TITLE
DataTable: default headerText based on field

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6873]
It would be cool if you could further extend the datatable column field concept such that you can use p:column without the necessity to provide a headerText:

`  <p:column field="name" />
`

instead of 

`  <p:column field="name" headerText="Name" />
`

or

`  <p:column field="name" headerText="#{messages.nameLabel}" />
`

In this default case, when the headerText attribute is missing, the headerText should be the capitalized value of the attribute field. In this case: 

`Name
`

The transformation of the field name should work as follows: 

`axxByyCzz` 

should be transformed to 

`Axx Byy Czz` 

by default.

**Comment by melloware** [comment]
I like this idea.  I have some production code that already does this let me submit a PR for review.

**Comment by melloware** [comment]
I modified one of the Integration Tests to use fields and to check this use case:

https://github.com/primefaces-extensions/primefaces-integration-tests/commit/e0de119d1664debdc753616163cae5b74a577d0a
