### ISSUE TITLE
DataView: "No records found." message missing if the DataView has no elements

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#6876]
**Describe the defect**
If a DataView (GridLayout and/or ListLayout) has no elements in it, the message "No records found." should be displayed.

![2021-01-21 11_35_34-PrimeFaces Test](https://user-images.githubusercontent.com/1710231/105340538-501edf80-5bde-11eb-8c81-6bba22b67052.png)

**Reproducer**
[primefaces-reproducer.zip](https://github.com/primefaces/primefaces/files/5848666/primefaces-reproducer.zip)

**Environment:**
 - PF Version: master-SNAPSHOT (10.0)
 - JSF + version: Mojarra 2.3.14
 - Affected browsers: all

**To Reproduce**
Run the reproducer.

**Expected behavior**
The message "No records found." should be displayed

**Comment by Rapster** [comment]
I encourage you to make a PR 😉

**Comment by melloware** [comment]
Yep you should be able to look at what DataTable is doing for empty records.

**Comment by ghost** [comment]
OK, I'm on it 👍
