### ISSUE TITLE
SelectOneMenu: Align width of overlay panel with input

### ISSUE THREAD

**Issue by milansie** [primefaces/primefaces#6877]
**Description**
Overlay panel of p:selectOneMenu is changing size (width) according to size of values (width could be even wider than the screen size). There is an option 'autoWidth', but it works in opposite way - it extends width of input by size of values.

**Describe the solution you would like**
It would be nice, if there will be an options to fix overlay width with input width. 
Solution may be like this somehow (if new attribute will be named "alignPanelWidthWithInput"):
```
alignPanelWidth: function() {
        //align panel and container
        if(!this.panelWidthAdjusted) {
            var jqWidth = this.jq.outerWidth();
            if(this.cfg.alignPanelWidthWithInput || this.panel.outerWidth() < jqWidth) {
                this.panel.width(jqWidth);
            }
            else {
                this.panel.width(this.panel.width());
            }

            this.panelWidthAdjusted = true;
        }
    }
```
 + add to css .ui-selectonemenu-list-item:
```
text-overflow: ellipsis;
overflow: hidden;
```

Thanks

**Comment by melloware** [comment]
@milansie Why not just overwrite the wigdet method and CSS to do this by default in your application?

**Comment by milansie** [comment]
@melloware Hi, of course I have done that. I just thought, that default behaviour is not 100% correct (if overlay panel renders outside of the screen) and should be changed. But decision is on you, I don't insist :) I'm satisfied with workaround solution :)
Have a nice day

**Comment by melloware** [comment]
I am going to close this for now   The default behavior has been this way for years with little complaint and a workaround is available if needed

**Comment by SoozaV** [comment]
> @milansie Why not just overwrite the wigdet method and CSS to do this by default in your application?

Hi, could you explain how to do that please? I have the same issue, the panel width is wider than the input:
![image](https://github.com/primefaces/primefaces/assets/23610892/bc1dc63a-d303-4ea6-b097-9d7484888e52)

I had the same issue with the Dropdown component when I was working on a React project (I used primereact), and I solved it using the following classNames:

```
<Dropdown
    className="w-12 relative"
    panelClassName="max-w-min"
    // other props...
/>
```

I tried the same with the oneSelectMenu component:

```
<p:selectOneMenu 
    styleClass="min-w-max w-auto relative"
    panelStyleClass="max-w-min overflow-x-hidden"
    // other props...
>
    <f:selectItems value="#{bean.values}" />
</p:selectOneMenu>
```

I'm not sure how to adjust the overlay panel width with input width.

**Comment by melloware** [comment]
Did you try turning autowidth=false along with your style classes above?

**Comment by melloware** [comment]
@SoozaV here is a working version of your code:
[pf-6877.zip](https://github.com/primefaces/primefaces/files/11574832/pf-6877.zip)

You can see my two small tweaks in `test.js` and `test.css` that override PF default behavior.

```js
if (PrimeFaces.widget.SelectOneMenu) {
    PrimeFaces.widget.SelectOneMenu.prototype.alignPanelWidth = function() {
        //align panel and container
        if (!this.panelWidthAdjusted) {
            var jqWidth = this.jq.outerWidth();
            this.panel.width(jqWidth);
            this.panelWidthAdjusted = true;
        }
    }
}
```

```css
body .ui-selectonemenu-panel .ui-selectonemenu-items .ui-selectonemenu-item,
body .ui-selectonemenu-panel .ui-selectonemenu-items .ui-selectonemenu-item.ui-state-highlight {
	text-overflow: ellipsis;
	overflow: hidden;
}
```

Your screen now...

![image](https://github.com/primefaces/primefaces/assets/4399574/00267934-48c7-455d-90ff-72eced2ca19d)

**Comment by melloware** [comment]
Submitted PR for PF 16.0.0
