### ISSUE TITLE
DataTable: set default column filter match mode 

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6879]
@Rapster In all our table tables we are using the filter match mode "contains". It would be great if one could to set the default filter match mode to something else than startsWith for all data tables. This could be a config parameter in web.xml, for instance.
Any solution would be appreciated. Many thanks in advance.

**Comment by Rapster** [comment]
See https://primefaces.github.io/primefaces/10_0_0/#/core/globalattributes?id=global-attributes

**Comment by Rapster** [comment]
I wish there could was a way more straightforward to override this default properties like a properties file but I think it's been decided in the past to stick to java

**Comment by tuerker** [comment]
thanks for the hint. 

by the way: this is unfortunately a very uncomfortable solution. would be great if this solution could be reviewed. at least there should be a properties file from which this java code is generated.

**Comment by melloware** [comment]
@tuerker that is just an example how to do it.  There is nothing stopping you from writing a custom `createComponent` in the `ApplicationWrapper ` that reads from a properties file etc.   This is pure JSF and not even PrimeFaces.  

This gives you a hook to do something before every single component is created.
