### ISSUE TITLE
Paginator: Refocus the paginator after pagination should be optional

### ISSUE THREAD

**Issue by kito99** [primefaces/primefaces#688]
In Paginator.updatePageLinks(), there is the following code that refocuses on the page button:

``` javascript
....
        focusContainer, tabindex;

        if(focusedElement.hasClass('ui-paginator-page')) {
            var pagesContainerIndex = this.pagesContainer.index(focusedElement.parent());
            if(pagesContainerIndex >= 0) {
                focusContainer = this.pagesContainer.eq(pagesContainerIndex);
                tabindex = focusedElement.index();
            }
        }
...
     if(focusContainer) {
            focusContainer.children().eq(tabindex).trigger('focus');
        }
```

This makes sense, but in some cases (like when the row content is really tall inside of a DataList or DataGrid), you may want to set the focus elsewhere. It'd be nice if the current behavior was optional.

**Comment by melloware** [comment]
PR submitted.

By default the behavior is not changing as it defaults to refocusing the paginator as it always has.  This just creates a widget method to give downstream users the ability to turn off refocus with...

```javascript
PrimeFaces.widget.Paginator.prototype.allowRefocus =  function() {
        return false;
 };
```

**Comment by melloware** [comment]
Since you can override updatePageLinks PrimeTek has recommended to close this ticket.
