### ISSUE TITLE
Picklist: buttons rotated when used in a dialog

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces#6880]
When the picklist component is included in a dialog, the button to add/remove etc. are rotated by 90 degrees. i.e instead of pointing left/right/ they point up/down. Please see the picture:
![PF picklist in dialog issue](https://user-images.githubusercontent.com/4806551/105425024-737a7680-5c40-11eb-97fa-9b454c3ef9fd.png)
Note that the issue ony occurs where a dialog is being used. On a normal page, the buttons are correct. Also note that the buttons all work correctly. Just the icons used are incorrect.

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/5852678/primefaces-test.zip)
I haven't tested this on the latest snapshot version of PF.

**Environment:**
 - PF Version: _8.0_
 - Reproducer fails on both Mojarra and myfaces for JSF2.3 (reproducer requires JSF2.3)
 - Affected browsers: all (tested with Firefox and Chrome)

**To Reproduce**
Open app - shows picklist in a normal page. Press Open Dialog to see picklist in a dialog box.

**Expected behavior**
There should be no difference in UI between a normal page and a dialog box when using the picklist component.

**Comment by melloware** [comment]
Thank you for the reproducer. I will let you know what I find out.

**Comment by melloware** [comment]
@mertsincan I can confirm this looks like theme issue in all premium themes including the new Saga Vela Arya themes in PF 10.0.

**Comment by mertsincan** [comment]
<img width="739" alt="Screen Shot 2021-01-24 at 00 23 28" src="https://user-images.githubusercontent.com/11868120/105614463-ad7f8000-5dda-11eb-995c-681319acaa38.png">
I couldn't replicate it on RC1. For now, close ;)

**Comment by melloware** [comment]
@mertsincan I can reproduce with this reproducer using SAGA theme with 10.0.0-SNAPSHOT the latest code.

[pf-6880.zip](https://github.com/primefaces/primefaces/files/5861158/pf-6880.zip)

Just run "mvn clean jetty:run" and navigate to http://localhost:8080/primefaces-test/test.xhtml

![image](https://user-images.githubusercontent.com/4399574/105615188-b4879d80-5d9c-11eb-9f2d-7cae0ab87276.png)
