### ISSUE TITLE
Ajax requests don't work as expected

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#6881]
**Describe the defect**
Components which were working without problems in 8.0.3 suddenly became non-functional in 8.0.6. Both AutoComplete and SelectOneMenu are affected. AutoComplete does not set the selected value in view bean. SelectOneMenu won't show dropdown even though disabled property tied to item availablity shows values are not empty and the drop down should appear. Without any changes in the code going back to 8.0.3 makes everything functional again.

**Reproducer**
So far failed to create reproducer, simple use case works. Will work on it more in the coming week.

**Environment:**
 - PF Version: 8.0.6
 - JSF + version: Mojarra 2.3.9.SP11 (Wildfly 20.0.1 and 20.0.0)
 - Affected browsers: Chrome, Edge on Windows, Chrome, Firefox on Linux, perhaps all

**Comment by melloware** [comment]
Yep will be fixed in 8.0.7.  You can read all about the fix and what is being reverted here:

https://github.com/primefaces/primefaces/issues/6700

**Comment by christophih** [comment]
Who knows when v8.0.7 is released?

**Comment by tandraschko** [comment]
@mertsincan @sqores

**Comment by mertsincan** [comment]
Today. I am currently doing some tests.

**Comment by christophih** [comment]
Sorry :-), same question again: is the release done today?

**Comment by melloware** [comment]
I just looked in my PrimeStore account and 8.0.7 is there!

**Comment by christophih** [comment]
thanks, after login the link is visible - thanks!
