### ISSUE TITLE
Menus: allow to use p:divider instead of p:separator in PF10

### ISSUE THREAD

**Issue by astappiev** [primefaces/primefaces#6882]
**Describe the defect**
```
class org.primefaces.component.divider.Divider cannot be cast to class org.primefaces.model.menu.MenuElement (org.primefaces.component.divider.Divider and org.primefaces.model.menu.MenuElement are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @5b6b17fa)
```

**Reproducer**
Replace `p:separator` (which was deprecated in PF10) with `p:divider` in this example
https://www.primefaces.org/showcase/ui/menu/menuButton.xhtml?jfwid=b7b31

**Environment:**
 - PF Version: 10-RC1

**Comment by melloware** [comment]
Good idea let me look.

**Comment by melloware** [comment]
Showcase updated and this fix makes it work for all menus.

https://github.com/primefaces/primefaces-showcase/pull/297
