### ISSUE TITLE
Primefaces X unable to run with Jakarta EE 9 compatiable server glassfish 6

### ISSUE THREAD

**Issue by niravpradhan** [primefaces/primefaces#6884]
I tried to use primefaces x with jarkarta ee 9 compatiable server glassfish n got the ava.lang.NoClassDefFoundError: javax/servlet/ServletRequestListener.

With Jakarta EE 9, the namespaces is changed from javax to jakarta.
So primefaces is not compatible with Jakarta Server Faces 3.0 but as per the primefaces x documentation, it says its compatible.

![image](https://user-images.githubusercontent.com/3373553/105532376-c1f74600-5d10-11eb-9e10-414d677f0d98.png)
[error_logs_for_primefaces_x.txt](https://github.com/primefaces/primefaces/files/5857950/error_logs_for_primefaces_x.txt)

**Comment by melloware** [comment]
Are you using the right JAR with the `jakarta` classifer?
```xml
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>10.0.0-RC1</version>
    <classifier>jakarta</classifier>
</dependency>
```

**Comment by niravpradhan** [comment]
I am using the gradle build tool with following dependency

implementation "org.primefaces:primefaces:${primefaces_version}"

where primefaces_version = 10.0.0-RC1

after using below, its working. Thank you for the help. Sorry raising the non-issue.
implementation "org.primefaces:primefaces:${primefaces_version}:jakarta"
