### ISSUE TITLE
TypeScript: Updates

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#6885]
**Description**
@blutorange Before 10.0.0 final is released i wouldn't mind some help with a few things. 

1. A review of our current TypeScript stuff.

2. I tried to do `npm update` to update the libs and it did but got all kinds of ESLINT issues I didn't understand.

3. I think we want to update `package.json` to Timeline 7.4.6 and FullCalendar 5.5.0 but was also getting errors I didn't understand!

Much appreciated.

**Comment by blutorange** [comment]
Yeah, I did notice 10.0 was just around the corner. Didn't have much time lately, but I will take some time this weekend. I already started fixing a few errors in the TypeScript definition. Will also take a look at what you mentioned.

I'm looking forward to v10 :)

**Comment by melloware** [comment]
Yep 10.0.0-RC1 was released today to Maven Central so you can give it a try.  And I really appreciate the help.  I have been doing a good job of trying to keep the TypeScript stuff correct but these errors were stumping me.

**Comment by blutorange** [comment]
Just a quick update: I resumed work on my branch which I had started in December. I fixed some typings, updated all dependencies. 

I also updated TypeDoc, which had some fixes and now organizes files in modules. This changes the URLs to the JSDoc  so I need to update to docs and the showcase to account for that. Tomorrow I'll merge the master into my branch and take a look at the recent changes to the widgets

**Comment by melloware** [comment]
Excellent work. Looking forward to it

**Comment by blutorange** [comment]
@melloware  Another thing I'd like to ask: I"m already using the type declarations file in a project where I needed to create custom widgets and write additional client-side code. The project uses TypeScript to check all code, which helps when updating PrimeFaces and the API changes. Right now I've just copied the declarations file, which is hard to maintain -- it would be great if I could just fetch it from NPM. 

Publishing to NPM itself should be easy, can we get in touch with PrimeTek regarding the package name and who should publish it / who do we need to ask?

**Comment by melloware** [comment]
I can ask PrimeTek on the Discord channel.  They already publish to NPM for React NG etc so hopefully it will be no big deal.

**Comment by melloware** [comment]
OK I asked them and I showed them your instructions which make it super easy to just put in their user and token in a Maven command.  I will let you know what they say.

**Comment by melloware** [comment]
Fantastic work!
