### ISSUE TITLE
DataTable: exports do not work with field

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6890]
@melloware @Rapster The datatable exporter seems not work with the new column field attribute notation if i have not missed any additionally required adaptations.

Just add the following column to /showcase/ui/data/dataexporter/basic.xhtml to verify:

```
                  <p:column
                    field="code"
                    headerText="CodeNew"/>

```
The exporter delivers empty fields for such a column.

**Comment by melloware** [comment]
Let me investigate. Thanks for reporting.

**Comment by melloware** [comment]
I can confirm its definitely an issue.

**Comment by tuerker** [comment]
@melloware: this fix does not work me. see my example:

![Screenshot from 2021-01-25 15-38-50](https://user-images.githubusercontent.com/10051373/105720417-b465da00-5f23-11eb-8f01-00f4bb0a4810.png)

delivers the following "broken" csv:

![Screenshot from 2021-01-25 15-43-22](https://user-images.githubusercontent.com/10051373/105720800-22120600-5f24-11eb-8944-e3ed99d5b2fe.png)

with the following error:

```
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:786)

```

maybe i have to adapt something?

**Comment by melloware** [comment]
Nothing has changed as far as writing goes so this looks like your Stream is being closed by your container...  

Working fine for me locally.  If you can put together a PF Test reproducer I can debug it.  But it looks like a different issue

**Comment by tuerker** [comment]
before the fix, all exports were working but only the columns using the field notation were empty. now, it is really "broken".

i will try to find out when it is not working and to come with a reproducer.

**Comment by melloware** [comment]
Yep let me know if you can reproduce it

**Comment by tuerker** [comment]
i am step further. it looks like that it is a type conversion problem. with string columns it works, but with other type not.

```
java.lang.Long cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at org.primefaces.component.datatable.export.DataTableCSVExporter.addColumnValue(DataTableCSVExporter.java:220)
	at org.primefaces.component.datatable.export.DataTableCSVExporter.exportCells(DataTableCSVExporter.java:170)
	at org.primefaces.component.datatable.export.DataTableExporter.exportRow(DataTableExporter.java:261)
	at org.primefaces.component.datatable.export.DataTableExporter.exportAll(DataTableExporter.java:232)
	at org.primefaces.component.datatable.export.DataTableCSVExporter.doExport(DataTableCSVExporter.java:84)
```

**Comment by melloware** [comment]
Got it. I think I know what it is.

**Comment by tuerker** [comment]
i see, you got it alread. just to let you know. it is definitively an type coversion issue:

this one does not work (id is Long field; idString delivers its string representation):
```
  <p:column
    field="name"
    headerText="#{messages.name}"/>
  <p:column
    field="id"
    headerText="#{messages.id}">
    <h:outputText value="#{entity.idString}"/>
  </p:column>

```

while this one does:
```
  <p:column
    field="name"
    headerText="#{messages.name}"/>
  <p:column
    headerText="#{messages.id}">
    <h:outputText value="#{entity.idString}"/>
  </p:column>
```

so as soon as the field is not a string field, the problem occurs.

**Comment by melloware** [comment]
OK I fixed it if you want to try again.  I had only tested String fields not realizing that Objects could be returned.

**Comment by tuerker** [comment]
great. now it works. many thanks.

**Comment by melloware** [comment]
@tuerker My latest fix also converts the values in the Exporter so your LocalDateTime example should now export in your expected format as well.

**Comment by tuerker** [comment]
@melloware this is unfortunately not the case (if this fix is merged into the master)

```
 <p:column
      field="fileDate"
      headerText="#{messages.fileDate}" />
 <p:column
      field="expirationDate"
      headerText="#{messages.expirationDate}" />
```

![Screenshot from 2021-01-28 14-04-36](https://user-images.githubusercontent.com/10051373/106142546-ea989900-6171-11eb-845c-506be5fd1cea.png)

![Screenshot from 2021-01-28 14-05-10](https://user-images.githubusercontent.com/10051373/106142571-f1271080-6171-11eb-802c-9c346244c603.png)

**Comment by melloware** [comment]
Are you positive you rebuilt the SNAPSHOT correctly?  Because I am calling the exact same code @Rapster wrote that is displaying in the column so the Exporter is calling the exact same converter code.

**Comment by tuerker** [comment]
Yes but I will check it again and let you know.

**Comment by tuerker** [comment]
Actually i pulled the master shortly before your last merge 30 minutes ago.

So, actually it works. Many thanks again.

**Comment by melloware** [comment]
thanks for testing. I was hoping you would say that!

**Comment by tuerker** [comment]
@melloware I brought also up the idea to map fields without headerText to the corresponding messages.property.

Thus writing

```
<p:column field="fileDate">
```

would be a shortcut for 

```
<p:column
      field="fileDate"
      headerText="#{messages.fileDate}" />
```

Wdyt?

**Comment by tuerker** [comment]
or by using an additional attribute to do that mapping by default. my goal would be to reduce the potential inconsistencies.

**Comment by melloware** [comment]
I don't think core PF should do that.  But you can do it easily with something like this totally untested example code...

https://primefaces.github.io/primefaces/10_0_0/#/core/globalattributes

```java
if (component instanceof Column) {
    final Column column = (Column) component;
    if (column.getField() != null) {
        String header = MessageUtils.getMessage("column." + column.getField());
        column.setHeaderText(header);
    }
}
```

Then in your resource bundle have...
```
column.name=Car Name
column.product=Product Type
```

**Comment by tuerker** [comment]
Thanks for the hint. I tried to add this code fragment to the ApplicationWrapper:

```
    @Override
    public UIComponent createComponent(FacesContext context, String componentType, String rendererType) {
        final UIComponent component = super.createComponent(context, componentType, rendererType);

        if (component instanceof ColumnBase) {
            final ColumnBase column = (ColumnBase) component;
            // Set the default datatable column filterMatchMode to "contains".
            column.setFilterMatchMode("contains");

            // Set the default headerText.
            String field = column.getField();
            if (column.getField() != null) {
                 String header = Messages.get(column.getField());
                 column.setHeaderText(header);
            }
        }

        if (component instanceof UICalendar) {
            final UICalendar calendar = (UICalendar) component;
            // Set the default calendar pattern.
            calendar.setPattern(Constants.LOCALDATE_PATTERN);
        }

        return component;
    }
```

But the ApplicationWrapper is not the right do that since here the column field is not set yet, i.e., null at this point in time. I need to hook in this code fragment after the column field is set. It must be before your default replacement of the empty headerText by the field's value is done. I fear that this is not possible, or? Can you please give me a hint where to do that?

**Comment by Rapster** [comment]
Unless i'm mistaken, `Application#createComponent` is called during build time while var is set during render time, so not possible that way. Easiest way is to override `DataTable#getHeaderText`. But I would suggest creating a facelet tag (wrapping dataTable) that define a common way to display a dataTable, quite easy to handle default values and breaking changes.

Or, maybe using a ValueExpression. Define a ValueExpressionWrapper on headerText and implement `ValueExpressionWrapper#getValue` with what you wrote before. Not sure if it works... But writing a wrapper component (e.g facelet tag/composite) would be a lot more easy IMO
