### ISSUE TITLE
ScheduleEvent: Builder<Object> cannot be converted to Builder<String>

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primefaces#6896]
**Describe the defect**
I'm upgrading from 8.0 to 10.0.0-RC1 (in a JoinFaces project). My IDE issues the warning indicated in the subject, and I can no longer compile my project.

A code snippet similar to the one below (I'm using my own custom class instead of String) used to compile just fine. But it's not compiling anymore with 10.0.0-RC1.

```
public DefaultScheduleEvent.Builder<String> eventBuilder() {
    return DefaultScheduleEvent.builder().data("");
}
```

**Environment:**
- PF Version: 10.0.0-RC1
- JSF Version: joinfaces 4.4.2 (jsf-spring-boot-starter, mojarra-spring-boot-starter).

**Comment by melloware** [comment]
I think this might be change that did it: https://github.com/primefaces/primefaces/issues/6108

What happens if you do this:
```java
	public DefaultScheduleEvent.Builder<String> eventBuilder() {
	    return DefaultScheduleEvent.<String>builder().data("");
	}
```

**Comment by mossaab0** [comment]
> I think this might be change that did it: #6108
> 
> What happens if you do this:
> 
> ```java
> 	public DefaultScheduleEvent.Builder<String> eventBuilder() {
> 	    return DefaultScheduleEvent.<String>builder().data("");
> 	}
> ```

This works, and am happy with it. Closing. Thanks!
