### ISSUE TITLE
DataTable: support Converter#forClass for field shorthand notation

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6897]
@melloware @Rapster It seems that the field notation ignores existing faces converters. 
I am seeing this for LocalDateTime fields.

```
<p:column field="startDate" headerText="startDate" />
```
delivers field values of the default LocalDateTime pattern, e.g. 2021-01-22T09:02:43.147

while in case of
```
<p:column field="startDate" headerText="startDate">
      <h:outputText value="#{entity.startDate}">
</p:column>
```
the field values are actually converted using the existing converter, e.g. 2021-01-22 09:02.
my converter is defined as follows:

```
@FacesConverter(forClass = LocalDateTime.class)
public class LocalDateTimeConverter implements Converter<Object> {
 ...
    private static String getPattern(UIComponent component) {
        String pattern = (String) component.getAttributes().get("pattern");
        if (pattern == null) {
            pattern = "yyyy-MM-dd HH:mm";
        }
        return pattern;
    }
}

```

I am not sure whether this a bug report  or feature request. In any case, many thanks in advance for having a view on this issue.

**Comment by melloware** [comment]
Another good one @tuerker !

**Comment by Rapster** [comment]
It's kinda Christmas for you lately 😋

**Comment by tuerker** [comment]
Works. Many thanks.

**Comment by Rapster** [comment]
Not working with p:columns
