### ISSUE TITLE
OutputLabel: Don't show required indicator, if input component is disabled

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#6898]
**Description**
Currently the required indicator of `p:outputLabel` is always visible (in auto-mode) if the referenced input component is disabled. Currently I have to manually either set the `required=false` based on disabled or `indicateRequired` from `auto` to `false` based on the disabled-state.

(`disabled` could be replaced with `readonly` which has the same effect)

**Describe the solution you would like**
Either always check the `disabled` attribute of the input or introduce a new attribute that optionally activates this check (to keep it backwards compatible). Maybe a new option for `indicateRequired` would be suffice - e.g. `auto-enhanced`.
But then a global config option would be nice to let `auto` include the new check.

Additionally a new attribute `syncRequiredIndictor=true|false` would be nice, that automatically updates the `p:outputLabel` if the referenced input component is updated. I don't know if this is possible at all without a huge overhead or a lot of new code.

**Comment by fanste** [comment]
If accepted at all: I will prepare a PR, if we simply change the default implementation of `auto`. Otherwise I will set it to my TODO as soon as I have time for it.

Waiting for your feedback.

**Comment by melloware** [comment]
I added integration tests showing the current behavior.

https://github.com/primefaces-extensions/primefaces-integration-tests/commit/7c97151a94e1299e365fd7cd31b550bfe84c3bce

**Comment by melloware** [comment]
I can see Disabled removing the * but for ReadOnly that is still submitting the value in the form right so technically its required still?

**Comment by tandraschko** [comment]
syncRequiredIndictor is to much magic IMO.

IMO the current behavior isnt wrong. The field can be required but currently not ediable during other inputs in the form.

If you would like to disable it, we should add a new attribute like: skipRequiredIndicatorOnDisabledInput

**Comment by tandraschko** [comment]
or we make
indicateRequired=true|false|auto|autoSkipDisabled

**Comment by fanste** [comment]
`disabled` and `readonly` are normally handled the same way internally -> do not decode the submitted value. Everything else would be the wrong behaviour IMO, as the logic say "nothing will/should change due to disabled/readonly" but then the new value is decoded and changes the state.

The feature request is based on a requirement from a collegue who must not show the indicator if the field is not editable.
I totally agree with you, that the current behavior is not wrong (therefore it is a feature request not a defect ;) ).

It's the question if only `disabled` should be checked or also `readonly`. Either it would be:
- indicateRequired = autoSkipNotEditable or autoSkipDisabled
- skipRequieredIndicatorOnNotEditableInput or skipRequieredIndicatorOnDisabledInput

I think the 'indicateRequired'-change would be nicer.

> syncRequiredIndictor is to much magic IMO.

Totally okay for me. You have more knowledge about the PF internals.

**Comment by tandraschko** [comment]
I would call it autoSkipDisabled and also check readonly there?

**Comment by melloware** [comment]
Yep my vote is for `indicateRequired=true|false|auto|autoSkipDisabled` and to check both readonly and disabled.

**Comment by fanste** [comment]
Alright, added it to my TODO.

**Comment by fanste** [comment]
I just wanted to implement that and luckily saw, that it is already done. Thanks melloware!
