### ISSUE TITLE
SelectOneRadio with CustomLayout ignores itemIndex

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#69]
If you define a selectoneradio with a custom layout like mentioned in the demo site the itemIndex of the p:radiobutton is ignored. Only the order in which the radioButtons are defined is taken is into consideration.

I added a dummy entry as second selectItem and adjusted the itemIndex for Green and Blue.
If I click on the radio buttons I would expect to get Red, Green, Blue as values if i check the radiobuttons. But I'm getting Red,Dummy,Green

``` xml
<h3>Custom Layout</h3>
    <p:outputPanel id="customPanel" style="margin-bottom:10px">
        <p:selectOneRadio id="customRadio" onchange="alert(this.value)" layout="custom">
            <f:selectItem itemLabel="Red" itemValue="Red" />
            <f:selectItem itemLabel="Dummy" itemValue="Dummy" />
            <f:selectItem itemLabel="Green" itemValue="Green" />
            <f:selectItem itemLabel="Blue" itemValue="Blue" />
        </p:selectOneRadio>

        <h:panelGrid columns="3" cellpadding="5">
            <p:radioButton id="opt1" for="customRadio" itemIndex="0" />
            <h:outputLabel for="opt1" value="Red" />
            <p:spinner />

            <p:radioButton id="opt2" for="customRadio" itemIndex="2" />
            <h:outputLabel for="opt2" value="Green" />
            <p:inputText />

            <p:radioButton id="opt3" for="customRadio" itemIndex="3" />
            <h:outputLabel for="opt3" value="Blue" />
            <p:calendar />
        </h:panelGrid>
    </p:outputPanel>
```

gandulf.k

**Comment by fanste** [comment]
This fix seems to introduce a new bug in 5.3 (I have access to the community release only).

We use radio buttons with custom layout inside a c:forEach with a nested ui:repeat (yeah... ugly but working in 5.2). Sometimes the selection of a radio button is not transferred to the server - the network dump shows that the the radio button is transferred as an empty string. If we change the layout to the default (non-custom) or if we use PF5.2 it works.

Some debugging using firebug reveals that the state is not properly synced between inputs and originalInputs.

Edit: Also happens with 5.4-SNAPSHOT
