### ISSUE TITLE
Timeline: Calling move()/zoom() functions on timeline does not fire rangeChanged event

### ISSUE THREAD

**Issue by buunsal** [primefaces/primefaces#6902]
When using the move/zoom buttons on timeline as per the example here [https://www.primefaces.org/showcase/ui/data/timeline/custom.xhtml?jfwid=fbbab](url) 
the rangeChanged ajax event does not get fired.

**Comment by melloware** [comment]
Related to #5455   verified my PR still works for this use case and for #5455.

**Comment by melloware** [comment]
Integration tests added for this so we catch it in the future if someone removes this code or changes it.

https://github.com/primefaces-extensions/primefaces-integration-tests/commit/0ca0e0fdd5beb1fa4e7cdecd2edb242d8af7dba2
