### ISSUE TITLE
DefaultScheduleEvent: Remove ScheduleRenderingMode

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#6908]
**Description**
Coming from the Migration Guide of FullCalendar (https://fullcalendar.io/docs/upgrading-from-v4) the "rendering" attribute has been replaced with the new "display" attribute. I am working on a project where we previously set the rendering attribute via the Enum "ScheduleRenderingMode" in combination with the builder function "renderingMode".

Since the "rendering" attribute does not exist anymore this function is now obsolete.

**Describe the solution you would like**
I would suggest removing the ScheduleRenderingMode and its occurences/functions in other classes entirely since it is not needed anymore.

**Comment by fcjm** [comment]
I made a pull request for the topic.

**Comment by melloware** [comment]
Much appreciated. This will hopefully get merged before RC2.
