### ISSUE TITLE
DataTable: GlobalFilter no longer works with PF10

### ISSUE THREAD

**Issue by newk5** [primefaces/primefaces#6910]
I've tried the PF10 RC and I noticed global datatable filters no longer work.

To reproduce you can check out the showcase here: https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml?jfwid=8d219 which uses default filtering, but even when you have a method bound to the globalFilterFunction, that function is never called. I tested it in my application switching back and forth between PF8 and PF10 I can confirm it's working with PF8

**Expected behavior**
The globalFilterFunction should be called and the defaulf filtering should be working aswell.

**Comment by tandraschko** [comment]
@Rapster what is globalFilter attr on DT for?

**Comment by tandraschko** [comment]
was it a temp storage for the current-request globalFilter value?

**Comment by Rapster** [comment]
I think it's for setting the default value... Yeah that's what the doc says:
> Value of the global filter to use when filtering by default.

**Comment by tandraschko** [comment]
@Rapster 

if globalFilter is used (and no filterFunction is passed), the globalFilter itself calls all other filters, right?
So shouldnt we skip all other filters then in FilterFeature#filter in this case?

**Comment by tandraschko** [comment]
the implemetation of GlobalFilterConstraint seems to be completely different, can you explain?
The old GlobalFilter just tested the string value and the current one invokes all filters. This leads to to invoke all filters 2 times if globalFilter is used.

**Comment by tandraschko** [comment]
restored the old behavior for now and prooved that its working.
Please watch changes with ?w=1, commited with CRLF stuff the first time

**Comment by tandraschko** [comment]
@Rapster if you would like to refactor it like you had it in mind, please create a issue for v11. Would really like to get rid of the forEachColumn/ui:repeat which wouldnt work with your version of GlobalFilterConstraint.

**Comment by Rapster** [comment]
Sure thing, I'm pretty sure global filter with or without function was working just fine with initial version (as I spent some time to test it...) But to answer quickly: 

> if globalFilter is used (and no filterFunction is passed), the globalFilter itself calls all other filters, right?
So shouldnt we skip all other filters then in FilterFeature#filter in this case?

If no filterFunction, yes

> the implemetation of GlobalFilterConstraint seems to be completely different, can you explain?
The old GlobalFilter just tested the string value and the current one invokes all filters. This leads to to invoke all filters 2 times if globalFilter is used.

GlobalFilter is simply an aggregate of all filter functions defined, more coherent and consistent than using contains predicate. That's debatable, but imposing a constraint is neither good, maybe DataTable#globalFilterFunction could either expect a String or a FilterConstraint? Regarding the filters called 2 times, yeah indeed... Ideally, globalFilter should be the first in the map (which should be easy to do)

There is still room for improvement for sure...
