### ISSUE TITLE
Avatar: support dynamic images (StreamedContent)

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6915]
It seems to be that one cannot directly use a byte[] image in p:avatar:

`    <p:avatar image="#{user.profileImage}">
`

Would be a great addition. Many thanks in advance.

**Comment by tuerker** [comment]
By the way, it would also be cool if p:graphicImage would also do that, i.e., work directly on byte[] a la omnifaces o:graphicImage.

**Comment by tandraschko** [comment]
i dont think we will support byte[] in graphicImage, we would need to introduce attributes for contentType e.g. and the risk is higher for bad performance as this value-binding method is always called 2 times. With our new builder, the stream() method is only called once.

**Comment by tandraschko** [comment]
I think we should do the same here. Allow usage of StreamedContent and stream=true|false

**Comment by tuerker** [comment]
how would the current solution look like for the above given example?

**Comment by tandraschko** [comment]
like the dynamic GraphicImage examples

**Comment by tuerker** [comment]
thanks. i see. you are probably referring at:

```
    @PostConstruct
    public void init() {
        try {
            graphicText = DefaultStreamedContent.builder()
                    .contentType("image/png")
                    .stream(() -> {
                        try {
                            BufferedImage bufferedImg = new BufferedImage(100, 25, BufferedImage.TYPE_INT_RGB);
                            Graphics2D g2 = bufferedImg.createGraphics();
                            g2.drawString("This is a text", 0, 10);
                            ByteArrayOutputStream os = new ByteArrayOutputStream();
                            ImageIO.write(bufferedImg, "png", os);
                            return new ByteArrayInputStream(os.toByteArray());
                        }
                        catch (Exception e) {
                            e.printStackTrace();
                            return null;
                        }
                    })
                    .build();

            chart = DefaultStreamedContent.builder()
                    .contentType("image/png")
                    .stream(() -> {
                        try {
                            JFreeChart jfreechart = ChartFactory.createPieChart("Cities", createDataset(), true, true, false);
                            File chartFile = new File("dynamichart");
                            ChartUtilities.saveChartAsPNG(chartFile, jfreechart, 375, 300);
                            return new FileInputStream(chartFile);
                        }
                        catch (Exception e) {
                            e.printStackTrace();
                            return null;
                        }
                    })
                    .build();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

nevertheless, i think i would be good if the framework would do that whenever it detects that the given image is a byte[].
otherwise every primefaces user has to define such a helper method which translates the bytearry into a defaultstreamedcontent.

**Comment by tandraschko** [comment]
it doesnt just translate it.
We could support it but then you have 2 calls to createPieChart, and i dont like to support bad patterns. Also we need a contentType attr on the graphicImage/avatar to be safe. This is just nice enough when you already have byte[] inside a POJO. But when you need to "call logic" for creating the byte-array, its really not that good.

It would only 1 call to createPieChart when setting stream=false. But using stream=false isnt nice anyway as it blows up your HTML drastically and is likely slower when not using very very small images.

**Comment by tuerker** [comment]
i see with your point and especially agree with with the 2. statement that one should not use here stream=false.

the question is whether is an elegant way out of the need to always call a helper method such as

    public static DefaultStreamedContent getDefaultStreamedContent(InputStream inputStream, String contextType, String fileName) {
        return DefaultStreamedContent.builder().stream(() -> inputStream).contentType(contextType).name(fileName).build();
    }

to use p:graphicImage or p:avatar in case you have the byte[] inside a POJO, which is typically the case for profile pictures.
There it would be good to have a wrapper component which translates the byte[] into a DefaultStreamedContent and then invokes the current p:graphicImage as of now.

**Comment by tandraschko** [comment]
See: https://github.com/primefaces/primefaces/issues/6916

i will rename this issue then

**Comment by Rapster** [comment]
@tandraschko I wonder if it's a smart move to introduce `Avatar` with `image` attribute as it seems it expects a path. One reason is security obviously (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#security_and_privacy_concerns) and another is, most users will fetch from a local cache or db. Instead, i would remove image attr and replace it with value (to be consistent with other components) and expect just like you mentionned a `StreamedContent`

**Comment by tandraschko** [comment]
yep, i would like to completely align it but there may be a better solution.
Currently Avater supports 3 modes:

- label
- icon
- image

so why not allow p:graphicImage as a child when no label or icon is defined?

**Comment by tandraschko** [comment]
Removed the image attr and allow p:graphicImage as child. Updates docs and showcase
