### ISSUE TITLE
Dynamic Content Streaming: Evaluate possibility to reduce method call to 1 with getExpectedType

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6916]
Currently our DynamicContentSrcBuilder receives the "value" to check the type of the "value" ValueExpression return value (String/StreamedContent).
In theory we could also use `ValueExpresison#getExpectedType()`, so we can reduce the first call when rendering the view.

Also see https://primefaces.github.io/primefaces/10_0_0/#/core/dynamiccontent

This should work in most cases, we should check some cases with composites, f:param to a ui:include and some JSF/EL impls.
We can still do a fallback if the expectedType doesnt return StreamdContent/String/byte[].

This would allow us to use a direct binding to a byte[] without having 2 calls to the "create image stream logic", which is currently prevented by DefaultStreamedContentBuilder#stream(lamba), as the lambda is only invoked once.
But we also have to add a contentType attr to the components like graphicImage/avatar.

**Comment by tuerker** [comment]
Great. Many thanks in advance.

**Comment by tandraschko** [comment]
We could even think about a more radical change.
The first call is only required because of non-dynamic images (value=/mydir/mydir.jpg). If we make `p:graphicImage` only support dynamic images, we can get rid of the this check as `p:graphicImage` doesnt have any benefits over `h:graphicImage` for non-dynamic images.
Or create a new `p:dynamicImage` and deprecate `p:graphicImage`.

**Comment by melloware** [comment]
We could also think about incorporating `lazy` in graphic image like OmniFaces does.

Since OmniFaces 3.10, you can set the `lazy` attribute to true to indicate that the referenced image should only be loaded when the window is finished loading and the image is visible in the viewport.

```xml
<o:graphicImage ... lazy="true" />
```
This attribute is ignored when the dataURI attribute is set to true.

**Comment by tandraschko** [comment]
please create a new issue if you would like to see it, thats a different topic

**Comment by tandraschko** [comment]
I think we should close this as wont fix. we need 3 attributes for full flexiblity actually: content type, content length, content name
therefore StreamedContent is the smarter choice.

**Comment by melloware** [comment]
+1

**Comment by tandraschko** [comment]
i refactored the code to avoid the getter call
as i said, we could now support byte[] and inputstream easily, however we would need to pass content type, optional filename and optional content length to the DynamicContentSrcBuilder.
Not sure if we should add this attributes to graphicImage and maybe other components.

wdyt @Rapster @melloware ?

**Comment by tandraschko** [comment]
the code now is also cleaner and more documented

**Comment by tuerker** [comment]
> i refactored the code to avoid the getter call
> as i said, we could now support byte[] and inputstream easily, however we would need to pass content type, optional filename and optional content length to the DynamicContentSrcBuilder.
> Not sure if we should add this attributes to graphicImage and maybe other components.
> 
> wdyt @Rapster @melloware ?

@tandraschko could it be that all these attributes are optional such that you have just provide the byte[], while the others are set to defaults, as in omnifaces -> https://showcase.omnifaces.org/components/graphicImage

**Comment by tandraschko** [comment]
yeah but i dont like to introduce like 12 or 15 attributes in multiple components because you dont like to write a bean method :D
not sure here.

**Comment by melloware** [comment]
This refactoring does clean it up nicely!

**Comment by tuerker** [comment]
many thanks. i see your point.

as always it is a question where to pay the price. it is not just about single method.

with the current implementation, you have to introduce the following code everywhere you have a byte[] content:

```
    @Transient
    DefaultStreamedContent streamedContent;

    public DefaultStreamedContent getStreamedContent() throws IOException {
        if (streamedContent == null) {
            streamedContent = FileHelper.getDefaultStreamedContent(new ByteArrayInputStream(getContent()), "image/*", getIdString());
        }
        return streamedContent;
    }

```
if this extension is once implemented by the framework, everybody could avoid these repeating code fragments.

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/issues/6967

**Comment by edudoda** [comment]
Hi guys, I just updated from PF10 to last RC2 and  `<p:graphicImage />`  is not working anymore, when a value content is returned from Bean. Eg: Using a simple method that returns String (path) :  
`<p:graphicImage value="#{utilBean.retrieveS3Url(utilBean.user.logo)}" />` now throws: _Property [retrieveS3Url] not found on type [...]_

It was working in PF10.0.0-RC1 and earlier, also it still works when changed it to JSF standard component `h:graphicImage` or place a plain text over there. Anyone can help? Need to serve it as **StreamedContent** even when I know the path?

**Comment by tuerker** [comment]
i assume that you need to use the attribute `stream="false"`.

**Comment by edudoda** [comment]
> i assume that you need to use the attribute `stream="false"`.

Doesn't work as well

**Comment by tuerker** [comment]
in my case following works:

`<p:graphicImage  value="#{instrument.image.streamedContent}" stream="false" />`

the value should be DefaultStreamedContent.

**Comment by edudoda** [comment]
> in my case following works:
> 
> `<p:graphicImage value="#{instrument.image.streamedContent}" stream="false" />`
> 
> the value should be DefaultStreamedContent.

But I just want to retrieve a simple String as an image path from bean (like: https://s3.amazonaws.com/xpto/1/logo_square.png)
