### ISSUE TITLE
DataTable: Sort and Selection

### ISSUE THREAD

**Issue by felixoi** [primefaces/primefaces#6918]
**Describe the defect**
After sorting the table two times all bean values are null.

**Reproducer**
https://github.com/felixoi/primefaces-test

**Environment:**
 - PF Version: 10.0.0-RC1
 - JSF + version: MyFaces 2.3.7
 - Affected browsers: All

**To Reproduce**
1. Go to 'http://0.0.0.0:8080/primefaces-test/'
2. Click on 'The column header "Correction date" to sort the datatable'
3. Click on 'The column header "Correction date" to sort the datatable'

**Expected behavior**
The datatable gets sorted with all beans still having their correct values.

**Example XHTML**
See https://github.com/felixoi/primefaces-test/blob/master/src/main/webapp/test.xhtml and https://github.com/felixoi/primefaces-test/blob/master/src/main/java/org/primefaces/test/TestView.java

**Comment by melloware** [comment]
@Rapster This looks a lot like https://github.com/primefaces/primefaces/issues/6913 it has `selectionMode="single"`.

**Comment by Rapster** [comment]
Yeah looks quite similar, in both scenarios I have error like this:
> SEVERE: java.lang.IllegalStateException: java.lang.InstantiationException: org.primefaces.test.Submission
	at javax.faces.component.StateHolderSaver.restore(StateHolderSaver.java:157)
	at javax.faces.component.UIComponentBase.restoreAttachedState(UIComponentBase.java:1801)
	at javax.faces.component.ComponentStateHelper.restoreState(ComponentStateHelper.java:301)
	at javax.faces.component.UIComponentBase.restoreState(UIComponentBase.java:1629)
	at javax.faces.component.UIData.restoreState(UIData.java:1750)
	at org.primefaces.component.api.UIData.restoreState(UIData.java:1118)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy$2.visit(FaceletPartialStateManagementStrategy.java:379)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:151)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:683)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)

I had to delombok as it generates default constructor, but does attached bean need to have a default ctor? I can't recall it needs one...

**Comment by melloware** [comment]
I thought anything ViewScoped or SessionScoped had to have default constructor so it can be passivated.

**Comment by Rapster** [comment]
Yeah but look at Product, no default ctor... Really makes wonder me now

**Comment by tandraschko** [comment]
all passivating scoped beans and variables of it needs to be serializable + have a default ctor

**Comment by melloware** [comment]
Product in our showcase?

**Comment by Rapster** [comment]
yeah

**Comment by melloware** [comment]
Right in our showcase I see
```java
public Product() {}
```

**Comment by Rapster** [comment]
Oh yeah my bad, I didn't see this little one.... Well I fixed this issue by making Submission implement Serializable that's all 😅  @felixoi Can you give have a try please?

**Comment by melloware** [comment]
Got it I wonder if we can detect this somehow and throw a better error message?

**Comment by felixoi** [comment]
@Rapster Working as expected now. Thanks for the fast help guys! I'll leave this open because of @melloware question. Please close if needed.

**Comment by tandraschko** [comment]
In theory we could do the following in PRojectStage dev:
when render the DT, took the first item, serialize/derialize it and nicely log if a error occurs

**Comment by melloware** [comment]
I like that idea.

**Comment by tandraschko** [comment]
me not actually :D
JSF already logs what exactly is not serializable, so we would just make the message a bit nicer
i dont think we should "wrap" that

**Comment by melloware** [comment]
So should we close this ticket as WontFix?

**Comment by tandraschko** [comment]
+1
