### ISSUE TITLE
PrimeFaces.Ajax: add ignoreAutoUpdate to PrimeFaces.current().ajax().update()

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6921]
eg `p:commandButton` and `p:autoUpdate` already support this

Keep existing method-signatures AS-IS. Add another one which allows to pass ignoreAutoUpdate - boolean. Internally call the same implementation.

**Comment by tandraschko** [comment]
+1

**Comment by tandraschko** [comment]
btw im not sure if this is possible ;D please provide feedback if you tried it

**Comment by christophs78** [comment]
Tried the following to prototype:

```java
public class PrimeRequestContext {

	...

	public void setIgnoreAutoUpdate(Boolean ignoreAutoUpdate) {
		this.ignoreAutoUpdate = ignoreAutoUpdate;
	}
}
```

And afterwards in a sample backing-bean:
```java
PrimeRequestContext.getCurrentInstance().setIgnoreAutoUpdate(true);
PrimeFaces.current().ajax().update("form1:inputText1");
```

This two lines may be integrated into a single one. What do you think?

**Comment by tandraschko** [comment]
```       
        // PostAddToViewEvent should work for stateless views
        //                  but fails for MyFaces ViewPooling
        //                  and sometimes on postbacks as PostAddToViewEvent should actually ony be called once
        component.subscribeToEvent(PostAddToViewEvent.class, listener);

        // PreRenderComponentEvent should work for normal cases and MyFaces ViewPooling
        //                      but likely fails for stateless view as we save the clientIds in the viewRoot
        component.subscribeToEvent(PreRenderComponentEvent.class, listener);
``` 
        
As you backing is executed between both, it should not work in all cases. Therfore we pass it as request param.

**Comment by christophs78** [comment]
Hm. How do play `AutoUpdateListener` and `AutoUpdatePhaseListener` together?
`AutoUpdateListener` collects components but does not care about `PrimeRequestContext#isIgnoreAutoUpdate`.
From my analysis it looks like `PrimeRequestContext#isIgnoreAutoUpdate` is only called from `AutoUpdatePhaseListener#beforePhase`. AutoUpdatePhaseListener subscribes to `PhaseId.RENDER_RESPONSE`.

From this point of view i currently think it´s safe to do something like
```java
PrimeRequestContext.getCurrentInstance().setIgnoreAutoUpdate(true);
PrimeFaces.current().ajax().update("form1:inputText1");
```

**Comment by tandraschko** [comment]
yep, you are right

maybe we should also create a shortcut in PrimeFaces.ajax
