### ISSUE TITLE
SelectOneMenu: Clicking the same item twice leads to wrong item being highlighted

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#6922]
**Describe the defect**
If you click on the same Item twice in the dropdown menu of the SelectOneMenu component with groups you will see that the wrong item is being selected & highlighted. From my research it seems like the problem lies within the revert() function of the SelectOneMenu widget which unselects the current item and instead tries to select the "Please Select" item.

Called in forms.selectonemenu.js: 

        .on('click.selectonemenu', function() {
            $this.revert();
            $this.selectItem($(this));
            $this.changeAriaValue($(this));
        });

revert function: 

    /**
     * Unselect the selected item, if any, and select the `please select` option.
     */
    revert: function() {
        if(this.cfg.editable && this.customInput) {
            this.setLabel(this.customInputVal);
            this.items.filter('.ui-state-active').removeClass('ui-state-active');
            this.items.eq(0).addClass('ui-state-active');
        }
        else {
            // this gets called
            this.highlightItem(this.items.eq(this.preShowValue.index()));
        }
    },

The function selectItem() will be skipped for the most part, since the currentOption still matches the originally selected item. Therefore sameOption will be true and the changes from the revert() function will remain.

**To Reproduce**
SelectOneMenu Showcase -> Grouped

If you select "Turkey" twice for example the label will change to "Germany"

**Comment by melloware** [comment]
Good debugging. I fixed it.  The grouping was throwing if off its index so I found other places where it correctly determines the index.  Thanks for reporting and debugging!

**Comment by melloware** [comment]
Integration test added: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/84f2fac176bdb05b7459e3bede893b492587c7c5
