### ISSUE TITLE
Sidebar: different opening effects

### ISSUE THREAD

**Issue by JoHoop** [primefaces/primefaces#6925]
The Sidebar always slides into the view when opened. There should be a `showEffect` and `hideEffect` attribute to change this effect (like there is for the Dialog component). Perhaps another effect could be added to make the sidebar shrink the main content or push it to the side.

**Comment by melloware** [comment]
OK so all the other dialogs use Jquery to Show and Hide and thus effects can be applied.  Sidebar just does this...

```javascript
this.jq.addClass('ui-sidebar-active');
```

and use CSS to animate it with ...

```css
.ui-sidebar {
    transition: transform .3s;
}
```

So you can simply override the CSS for `.ui-sidebar` to change the animation or speed.

**Comment by JoHoop** [comment]
That's working!
Thanks so much :)
