### ISSUE TITLE
Sidebar: add attribute to disable close on click

### ISSUE THREAD

**Issue by JoHoop** [primefaces/primefaces#6926]
The Sidebar always closes when clicking anywhere on the background.
There should be an option to disable this behaviour.
There could also be a `permanent` attribute to show the sidebar permanently.

**Comment by melloware** [comment]
OK you don't want a `permanent` attribute you want `showCloseIcon="false"` in combination with `modal="false"` this will do what you want.

```xml
<p:sidebar position="bottom" modal="false" showCloseIcon="false">
```
