### ISSUE TITLE
DataTable: JumpToPageDropdown does not perform for larger lazy tables

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6929]
Using JumpToPageDropdown in the datatable paginator does not really work with larger lazy tables.
For tables in the area of 1 million or more rows it is even blocking. I am wondering whether there is something to be improved or whether one should simply not use JumpToPageDropdown for larger tables (since for instance in case of lazy table with a row count > 1000000 and rowsPerPage = 10 the dropdown will have 100000 entries)?

**Comment by tandraschko** [comment]
i dont think it was ever designed for that amount

**Comment by stolp** [comment]
@tuerker: Maybe it would help to get a client side performance analysis for this use case?

**Comment by tuerker** [comment]
@stolp what do you expect here exactly?

**Comment by tuerker** [comment]
I can imagine that JumpToPageDropdown was not forseen for larger datatables since then the dropdown gets large and to jump on the page,e.g., 14567, the selection of the page in the dropdown is not comfortable enough. I will use JumpToPageInput instead JumpToPageDropdown.

**Comment by stolp** [comment]
Opening developer tools in your browser shows a performance tab (under Chrome). Using record you can get a performance analysis of how time is spent in your browser (e.g. when loading the page or other interactions).

I found this extremely helpful with analyzing #5530.

**Comment by tuerker** [comment]
here is a screnshot. use case: go to screen with a lazy datatable having more than 7 millions row. i stopped after a minute. the screen is still rendering.

![Screenshot from 2021-02-03 11-57-05](https://user-images.githubusercontent.com/10051373/106737558-1b1b7f80-6617-11eb-93b3-9289c35f8f80.png)

**Comment by stolp** [comment]
This is interesting. Basically all time is spent rendering this page using the CPU. It would be interesting to see the Network Marker open if possible (left hand side). Also the Bottom-up view (lower tab). How big is the page in KB?

**Comment by tuerker** [comment]
page size 115kB.

here is the network screnshot. it looks like that the page is recursively rendered.

![Screenshot from 2021-02-03 13-09-45](https://user-images.githubusercontent.com/10051373/106745255-1eb40400-6621-11eb-81e3-58b154f6e7a1.png)

in contrast when using JumpToPageInput instead JumpToPageDropdown, the page works really fine:

![Screenshot from 2021-02-03 13-08-33](https://user-images.githubusercontent.com/10051373/106745398-53c05680-6621-11eb-87e5-856eced8c980.png)

![Screenshot from 2021-02-03 13-07-20](https://user-images.githubusercontent.com/10051373/106745401-5458ed00-6621-11eb-8307-751afd488c5d.png)

**Comment by melloware** [comment]
This is just a thought but when you say Jump to bottom is your Lazy Datatable then querying for 7 million rows to find the bottom?

**Comment by tuerker** [comment]
In case of lazy tables the database query would use the offset that corresponds to the last page and delivers only the rowsPerPage amount of rows. Actually, the problem occurs without clicking anywhere on the table, i.e., when the page is rendered. I assume during the computation of the paginator.

**Comment by stolp** [comment]
@tuerker When using JumpToPageDropdown, does the page source contain all the select options available for the selector or is this loaded dynamically?

If I did not miscalculate here, there are ~700000 option entries in this SelectOneMenu. I think it is fair to say that this is not a realistic use case scenario.

I also have used lazy datatables with entries in the 100.000 - 1.000.000 entry range. In this case, I used the following Paginator pattern successfully (with pageLinks="5"):

paginatorTemplate="{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"

This scales well in my cases while given the user some interaction options.

**Comment by tuerker** [comment]
@stolp as you can see in the first screen, the paginator is even not build and the page completely stucks. so i cannot look in the selector. compare it to the JumpToPageInput variant (third screenshot). there you see the full paginator. as in your case, our paginator is similar to yours, except the jump part.

in general, the lazy tables work really well even with millions of rows (unless you add JumpToPageDropdown to the paginator). 
as stated before, i am now using JumpToPageInput instead JumpToPageDropdown.

**Comment by tuerker** [comment]
I would opt to deprecate JumpToPageDropdown since it's usage is limited and less comfortable than JumpToPageInput, even for small tables.

I brought this issue up such that the DataTable developers might have deeper look at the reason for this problem to avoid potential (performance) problems, e.g., induced by rendering components unnecessarily.

**Comment by melloware** [comment]
I think its a useful use case if you have a reasonable amount of items.  7 million to me is not what I would consider reasonable.

And here is the problem in paginator.js.  It uses Jquery to build and append the HTML Options into the select.  So 700,000 options is a lot of JS time so it explains why the CPU is spiked.

```javascript
//jump to page dropdown
        if(this.jtpSelect.length > 0) {
            if(this.jtpSelect[0].options.length != this.cfg.pageCount){
                var jtpOptions = '';
                for(var i = 0; i < this.cfg.pageCount; i++) {
                    jtpOptions += '<option value="' + i + '">' + (i + 1) + '</option>';
                }

                this.jtpSelect.html(jtpOptions);
            }
            this.jtpSelect.children('option[value=' + (this.cfg.page) + ']').prop('selected','selected');
        }
```

**Comment by melloware** [comment]
Also here is an old thread about it: https://github.com/primefaces/primefaces/issues/2933

**Comment by stolp** [comment]
To return to our discussion back in #5530 / #5533: Can't the html() call be replaced with innerHtml() here? There is no JavaScript involved in this case I think.

Sorry for my ongoing stupidity regarding JavaScript development ...

**Comment by melloware** [comment]
@stolp I think it would probably be safe to make that change for this particular use case but not sure how much it will improve if the list has 700,000 items.  That is still a LOT of HTML to append into the DOM.   Let me try it.

**Comment by melloware** [comment]
OK I tested it and it works fine switching to  `innerHTML`  which is definitely a performance improvement but I doubt its enough to solve @tuerker issue of volume.

**Comment by tuerker** [comment]
> I think its a useful use case if you have a reasonable amount of items. 7 million to me is not what I would consider reasonable.
> 
> And here is the problem in paginator.js. It uses Jquery to build and append the HTML Options into the select. So 700,000 options is a lot of JS time so it explains why the CPU is spiked.
> 
> ```js
> //jump to page dropdown
>         if(this.jtpSelect.length > 0) {
>             if(this.jtpSelect[0].options.length != this.cfg.pageCount){
>                 var jtpOptions = '';
>                 for(var i = 0; i < this.cfg.pageCount; i++) {
>                     jtpOptions += '<option value="' + i + '">' + (i + 1) + '</option>';
>                 }
> 
>                 this.jtpSelect.html(jtpOptions);
>             }
>             this.jtpSelect.children('option[value=' + (this.cfg.page) + ']').prop('selected','selected');
>         }
> ```

yep, that's it.

**Comment by tuerker** [comment]
> OK I tested it and it works fine switching to `innerHTML` which is definitely a performance improvement but I doubt its enough to solve @tuerker issue of volume.

i will test it and we will see.

**Comment by melloware** [comment]
I still think this line is probably just as big of a problem:
```javascript
 jtpOptions += '<option value="' + i + '">' + (i + 1) + '</option>';
```
Its building a giant string of all 700000 options in memory.

**Comment by tuerker** [comment]
i tested it. the fix is surely an improvement. the datatable with 7 mio lazy rows and JumToPageDropdown is now rendered at least. it takes around a minute. but after that it is practically not usuable/responsive.

for smaller tables (< 200000 lazy rows) it is working fine but for beyond 1 million lazy row it is getting unusuable.

as said above, i am now using JumpToPageInput instead. 

maybe you could drop a hint in the documentation to avoid that others are stumbling over this issue, too.

many thanks.
