### ISSUE TITLE
Dialog: responsive should be default

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6931]
Currently if you open https://www.primefaces.org/showcase/ui/df/basic.xhtml?jfwid=c9317, open the dialog, resize, the dialog is not centered again.

WDYT @melloware @mertsincan ?

**Comment by tandraschko** [comment]
i think we already have this funcitionality with "responsive" flag but its false per default. Should we make it true?

**Comment by mertsincan** [comment]
@tandraschko we can make some changes in Dialog. But on PF11 ;) Instead of adding an attribute to the dialog, we can always make responsive using Flexbox structure like in PrimeReact.
https://primefaces.org/primereact/showcase/#/dialog

> i think we already have this funcitionality with "responsive" flag but its false per default. Should we make it true?

For now, it can be 'true'.

**Comment by tandraschko** [comment]
perfect

**Comment by melloware** [comment]
Another thing we can do in the future is make the dialog `FlexAware` interface and if someone sets 
```xml
<context-param>
    <param-name>primefaces.FLEX</param-name>
    <param-value>true</param-value>
</context-param>
```

We could automatically apply Merts new PrimeReact styles and make it responsive.  

But for now I prefer `responsive="true"` since I set that on all my dialogs anyway!
