### ISSUE TITLE
FileUpload: Wrong invalid file name pattern

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6936]
**Describe the defect**
Since 8.0, file name is validated on server side (for security reasons, mostly intrusions). Though, a filename like `D2021-00022/V2020-00093/D-00001300/xxxx.xml` throws an exception while there is no attempt to path traversal. Exception is throw just because there is a `/`

```
Invalid filename: D2021-00022/V2020-00093/D-00001300/xxxx.xml
javax.faces.FacesException: Invalid filename: D2021-00022/V2020-00093/D-00001300/xxxx.xml
	at org.primefaces.util.FileUploadUtils.getValidFilename(FileUploadUtils.java:77)
	at org.primefaces.model.file.NativeUploadedFile.resolveFilename(NativeUploadedFile.java:113)
	at org.primefaces.model.file.NativeUploadedFile.<init>(NativeUploadedFile.java:53)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decodeAdvanced(NativeFileUploadDecoder.java:100)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decode(NativeFileUploadDecoder.java:53)
	at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:59)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)
	at javax.faces.component.UIInput.decode(UIInput.java:771)
```
**Reproducer**
Tricky as I'm uploading a directory using https://github.com/primefaces/primefaces/issues/2705 tweak

**Environment:**
 - PF Version: 8.0

**Expected behavior**
No exception. 

On a general note, I don't think PF should define these validation rule, it's a very tricky topic... Library like this one https://github.com/ESAPI/esapi-java-legacy exists already and seems to do a good job. Also, users should have the possibility to skip those tests, it's company responsability to use whether or not FileUpload safety features. In mine, we don't want it for several reasons (perf, owasp compliancy etc.)

Though, I'm thinking of having an attribute `FileUpload#secure` that will validate content type, filename, content etc. _(see Esapi's `DefaultValidator#asserValidFileUpload`)_ Maybe virusScan also?

**Comment by melloware** [comment]
Whatever it is we can't break https://github.com/primefaces/primefaces/issues/3268 because the security firms will ding us and my management team freaks out.  So we have to defend against Path Traversal.

**Comment by Rapster** [comment]
Sure, but I'm not talking about breaking anything here, my point is PF should support safety file upload of course but maybe instead of reinventing the wheel, we could reuse ESAPI. 

Right now, the issue is that filename is considered as invalid (whether it is true or not), users should be able to bypass these tests, just like there is an attribute validateContentType (maybe I should turn this defect into a new feature...)

**Comment by melloware** [comment]
Good idea.  Just want to make sure we didn't break anything!
