### ISSUE TITLE
FileUpload: secure attribute

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6938]
**Description**
Following up #6936, uploading a file with filename containg a `/` is impossible (`FileUploadUtils#getValidFilename` throws an exception), it should be user responsability and not component to define whether or not those test should be made

**Describe the solution you would like**
Introducing `FileUpload#secure` _(default value: false)_ would:
- validateContentType (deprecate `FileUpload#validateContentType`)
- check filename / check path traversal
- virus scan?
- using [ESAPI library ](https://github.com/ESAPI/esapi-java-legacy)

**Comment by melloware** [comment]
I like the idea.

**Comment by Rapster** [comment]
Since #6936 will no longer be blocking issue, I close this one
