### ISSUE TITLE
DataTable liveScroll="true",column rendered="false" columns will not render after scroll

### ISSUE THREAD

**Issue by sll97163** [primefaces/primefaces#694]
when use liveScroll,if one column set rendered="false",then last column will not render after scroll.if two column set rendered="false",then last two column will not render  after scroll.

Component: p:dataTable
Browser: firefox 40.0.3/chrome 45.0.2454.85
Versions: primefaces-5.2  javax.faces-2.1.9

test page:

> ```
>           <p:dataTable value="#{testBean.testli}" var="col"
>                      scrollable="true" scrollHeight="200"
>                      liveScroll="true" scrollRows="20">
>             <p:column headerText="code" rendered="false">
>                 #{col.code}
>             </p:column>
>             <p:column headerText="name" rendered="false">
>                 #{col.name}
>             </p:column>
>             <p:column headerText="address" rendered="true">
>                 #{col.address}
>             </p:column>
>             <p:column headerText="tel">
>                 #{col.tel}
>             </p:column>
>             <p:column headerText="zip">
>                 #{col.zip}
>             </p:column>
>             <p:column headerText="age">
>                 #{col.age}
>             </p:column>
>         </p:dataTable>
> ```

TestBean:

> ```
> @ManagedBean(name = "testBean")
> @ViewScoped
> public class TestBean implements Serializable {
>     private List<Test> testli = new ArrayList();
>     public TestBean() {
>         for (int i = 0; i < 100; i++) {
>             Test t = new Test();
>             t.setAddress("address");
>             t.setAge(10);
>             t.setCode("" + i);
>             t.setName("name");
>             t.setTel("10001");
>             t.setZip("101010");
>             testli.add(t);
>         }
>     }
>     public List<Test> getTestli() {
>         return testli;
>     }
>     public void setTestli(List<Test> testli) {
>         this.testli = testli;
>     }
> }
> ```

Test:

> ```
> public class Test {
>     private String code;
>     private String name;
>     private String address;
>     private String tel;
>     private String zip;
>     private Integer age;
> //getter and setter
> ...
> }
> ```

**Comment by cagataycivici** [comment]
I can't replicate this.

**Comment by cagataycivici** [comment]
Maybe related to #607

**Comment by sll97163** [comment]
I downloaded the showcase,issue is also there.
Data --> DataTable --> scroll --> On-Demand Data:
![image 2](https://cloud.githubusercontent.com/assets/3340080/10091481/7e500302-636e-11e5-9827-7d0d325dfffa.png)
I set first two columns rendered="false" and add a column:

> ```
> <p:dataTable var="car" value="#{dtScrollView.cars6}" scrollRows="20" scrollable="true" liveScroll="true" scrollHeight="150" style="margin-bottom:0">
>         <p:column headerText="Id" footerText="Id" rendered="false">
>             <h:outputText value="#{car.id}" />
>         </p:column>
>         <p:column headerText="Year" footerText="Year" rendered="false">
>             <h:outputText value="#{car.year}" />
>         </p:column>
>         <p:column headerText="Brand" footerText="Brand">
>             <h:outputText value="#{car.brand}" />
>         </p:column>
>         <p:column headerText="Brand" footerText="Brand">
>             <h:outputText value="#{car.brand}" />
>         </p:column>
>         <p:column headerText="Color" footerText="Color">
>             <h:outputText value="#{car.color}" />
>         </p:column>
> </p:dataTable>
> ```
