### ISSUE TITLE
InputNumber: ajax change event fired even if value isn't changed

### ISSUE THREAD

**Issue by FabioMarangonSMI** [primefaces/primefaces#6940]
**Describe the defect**
When i use and p:inputNumber with ajax behaviour on change that updates the component container, the event gets fired even if the value isn't changed. Note: the exact same example using p:inputText is working correctly.

**Environment:**
 - PF Version: 8.0.7
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: Chrome, Firefox

**To Reproduce**
1. select the first input number, change it's value
2. use TAB to move to the second (a change event is fired - correct)
3. from the second input number use SHIFT+TAB to go back (a new change event is fired - WRONG)
4. from now on, moving from one input to the other (without changing the value) fires a change ajax event

**Expected behavior**
A change event should be fired only when the input value is actually changed

**Example XHTML**
```html
<h:form id="frmTest">
	<p:outputPanel styleClass="x">
		<p:inputNumber value="#{bean.a}">
			<p:ajax process="@this" update="@(.x)"/>
		</p:inputNumber>
		<p:inputNumber value="#{bean.b}">
			<p:ajax process="@this" update="@(.x)"/>
		</p:inputNumber>
	</p:outputPanel>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class Bean implements Serializable {
	private double a=3.2;
	private double b=1.2;
	public double getA() {
		return a;
	}
	public void setA(double a) {
		this.a = a;
		return;
	}
	public double getB() {
		return b;
	}
	public void setB(double b) {
		this.b = b;
		return;
	}
}
```

**Comment by tandraschko** [comment]
@melloware can you check and verify that it works fine in trunk?

**Comment by melloware** [comment]
Yes I will investigate.

**Comment by melloware** [comment]
Reproducer:
[pf-6940.zip](https://github.com/primefaces/primefaces/files/5925737/pf-6940.zip)

Verified its happening in 8.0 and 10.0.0-RC1.  Now investigating a fix.

**Comment by melloware** [comment]
From my preliminary investigation I think these change events are being bubbled up from Autonumeric.

**Comment by melloware** [comment]
OK I figured out what is going on.  The `change` was being fired from AutoNumeric here:
```javascript
    key: "_onBlur",
    value: function _onBlur(e) {
      // Keep track if the element is currently focused
      this.isFocused = false; // Keep track if the user is currently editing the element

      this.isEditing = false; // Send a `change` event if the raw value has been changed since the last focus or 'enter' validation

      if (this.rawValue !== this.rawValueOnFocus) {
        this._triggerEvent(AutoNumeric.events["native"].change, e.target);
      }

      this.rawValueOnFocus = void 0; // Reset the tracker
    }
```

The value of `if (this.rawValue !== this.rawValueOnFocus) {` was not equals because `rawValueOnFocus` is undefined and thus fires the change event.  Not sure if this is a bug in AutoNumeric but the fix is simple.  PR on the way.

**Comment by FabioMarangonSMI** [comment]
Hi @melloware, thank you for the quick answer, I tested your solution on the 8.0.7 (extending PrimeFaces.widget.InputNumber in my project) and I can confirm it solves my problem.

I will keep the fix until you release it in the next version, thanks for your work :)

**Comment by melloware** [comment]
Excellent thanks for reporting the issue and testing it!
