### ISSUE TITLE
DataTable/TreeTable: widget cfg.formId is missing

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6948]
See for example:

https://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml

and in the JS console:

PF('widget_form_customerTable').cfg.formId

See also https://github.com/primefaces/primefaces/pull/6937

**Comment by melloware** [comment]
switch this from defect to performance becuse this basically prevents core.ajax from looking up the form over and over every time you sort, filter, page etc.
