### ISSUE TITLE
p:tabView doesn't update activeIndex's bound value when not in a form

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#695]
PrimeFaces 5.2.11, Wildfly 8.2.0.Final.

XHTML

```
<p:tabView id="tabz" activeIndex="#{bean.activeIndex}">
    <p:ajax event="tabChange" />
    <p:tab title="tab 0">
        tab 0
    </p:tab>
    <p:tab title="tab 1">
        tab 1
    </p:tab>
</p:tabView>
```

Bean

```
private Integer activeIndex;

public Integer getActiveIndex() {
    System.out.println("getActiveIndex: " + activeIndex);
    return activeIndex;
}

public void setActiveIndex(Integer activeIndex) {
    System.out.println("setActiveIndex: " + this.activeIndex + " -> " + activeIndex);
    this.activeIndex = activeIndex;
}
```

In a browser switch to tab 1, and back to tab 0. Output:

```
2015-09-14 14:54:06,337 INFO  [stdout] (default task-61) getActiveIndex: null
2015-09-14 14:54:06,337 INFO  [stdout] (default task-61) setActiveIndex: null -> 0
2015-09-14 14:54:06,841 INFO  [stdout] (default task-55) getActiveIndex: 0
2015-09-14 14:54:06,857 INFO  [stdout] (default task-55) setActiveIndex: 0 -> 0
```

Setter is called always with a zero.
Enclose the `p:tabView` in an `h:form` and the output becomes:

```
2015-09-14 14:58:52,222 INFO  [stdout] (default task-18) setActiveIndex: null -> 1
2015-09-14 14:58:52,653 INFO  [stdout] (default task-21) setActiveIndex: 1 -> 0
```

Setter is called with the correct values, that correspond to the selected tabs.

This is an old bug: http://code.google.com/p/primefaces/issues/detail?id=1640

**Comment by tandraschko** [comment]
When you use p:ajax on a tabview, it's like a input component. To get a 100% working component, you need to put in a form. Same with h:inputText etc.

**Comment by VsevolodGolovanov** [comment]
Can be worked around by enabling partialSubmit (on the `p:ajax` or globally).

**Comment by ralf-br** [comment]
Thanks for the partialSubmit workaround!
(Easier than the other also working workaround i found here: http://forum.primefaces.org/viewtopic.php?f=3&t=18159)
