### ISSUE TITLE
Core: Drop Internet Explorer support

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6956]
With Internet Explorer dying in foreseeable future we may discuss dropping support with a future PrimeFaces-release.

This would allow use to use more modern JavaScript for new features and/or components. Maybe ES6 would be a proper base-level for some time.
Thanks to our integration-tests we have a good base to check compatibility against the 3 most wide-spreaded browsers. (Chrome, Safari and Firefox)

This suggestion is somehow inspired by Cagatay Civici who spoke about plans to replace JS-based animations within PrimeFaces with up2date CSS-animations.

**Comment by melloware** [comment]
I know a couple of things....
1) Microsoft has recommended people stop using IE for anything but legacy apps however it will still be supported until 2025.
2) JQuery I believe is dropping support for IE in 4.0

**Comment by christophs78** [comment]
https://github.com/jquery/jquery/issues/4299 (jQuery 4 drops support for IE<11; but still supports IE11)

**Comment by christophs78** [comment]
One option would be to use something like https://polyfill.io/v3/ to provide some kind of IE11-backwards-compatibility.

**Comment by melloware** [comment]
In my opinion once we decide to drop IE support we should rip out all blocks of code where `PrimeFaces.env.isIE` is found and just rip the band aid off. :)  Like the JQuery team said "If someone still needs IE support they can stay on JQuery 3(aka PrimeFaces 8)."

**Comment by pizzi80** [comment]
The FileUpload could use directly js FormData instead of ajax with iframe

**Comment by tandraschko** [comment]
FormData is already partly used

**Comment by martin654** [comment]
@melloware 
You said "Microsoft has recommended people stop using IE for anything but legacy apps however it will still be supported until 2025.". Do you please have source of this information? I haven't find this myself... Thank you

**Comment by pizzi80** [comment]
IMHO whatever the EOL of IE I think it's time to enter the ES6 / CSS 3 era

Primefaces it's getting huge in Java / JS and CSS size to support the 1% of population

May be the v11 could remove all old Java / JSF / JS / CSS hacks and target for

JSF 3+
Java 11+
JS ES6
CSS 3

I think that for Primetek it could be also a business oppportunity to offer an LTS legacy version 
for old browser and stack with a subscription based license and leave the rest of the world to develop modern software

**Comment by tandraschko** [comment]
JSF3+ and Java11+ doesnt bring any benefit currently
JSF4+ will be a bigger change then.
But we will remove JSF 2.0 support, so we can cleanup our UIData.

**Comment by pizzi80** [comment]
@tandraschko I really wanted to write JSF4 then I corrected myself to not look too aggressive :)

**Comment by melloware** [comment]
@martin654 To answer.

Countdown: https://death-to-ie11.com/

When it boils down to it, IE11's support is tied to Windows 10 - which will see its mainstream support ending Oct. 13, 2020, and its extended support ending Oct. 14, 2025. It's likely that both of those dates will get pushed further to the right as Microsoft has a history of extending support for operating systems.

"Microsoft really doesn’t want you to use Internet Explorer anymore": https://www.theverge.com/2019/2/8/18216767/microsoft-internet-explorer-warning-compatibility-solution

"Microsoft Stops IE11 support for Office 365 in August 2021": https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge

**Comment by melloware** [comment]
Microsoft has bumped up the timeline...

https://bit.ly/341JvuE

"the Internet Explorer 11 desktop application will be retired and go out of support on June 15, 2022, for certain versions of Windows 10."

**Comment by melloware** [comment]
Also remove the IE function in the Java class `AgentUtils`.

**Comment by jepsar** [comment]
If IE is dropped we could DRY up CSS using the `:is()` pseudo selector

https://caniuse.com/css-matches-pseudo
https://developer.mozilla.org/en-US/docs/Web/CSS/:is

**Comment by tandraschko** [comment]
we discussed this today in our company and IE11 end of life seems to be 06/2022

**Comment by tandraschko** [comment]
https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

**Comment by tandraschko** [comment]
even 01-2023: 
Even IE11 running on Windows 7 will be supported longer than next June. Commercial customers who pay for the third year of Extended Security Updates (ESUs) will receive support for IE through the end of that contract, or until Jan. 10, 2023.

**Comment by pizzi80** [comment]
Angular do not support IE so PrimeNG do not support IE 

[https://github.com/angular/angular/issues/41840](https://github.com/angular/angular/issues/41840)


just saying... but, If people is comfortable to pay for IE11 it should be comfortable to pay a PrimeFaces "legacy" or "LTS" version even double the price of the current version....

**Comment by melloware** [comment]
React doesn't support it either without a 3rd party library `react-app-polyfill`.

**Comment by tandraschko** [comment]
i need IE support personally until support ends, so...

**Comment by jepsar** [comment]
Support ends tomorrow 😅

But... "Internet Explorer mode in Microsoft Edge enables backward compatibility and will be supported through at least 2029".
