### ISSUE TITLE
.ui-datatable-fs width:auto, not working well

### ISSUE THREAD

**Issue by fcanevar** [primefaces/primefaces#696]
In one of our web applications I've a bunch of datatables with frozencolumns and p:columns. Yesterday I've updated this application from PF 5.0.8 to PF 5.2.11 and the width of the datatables were broken.
This is the style that I've used:

```
.ui-datatable-frozenlayout-left {
    width: 65%;
}
.ui-datatable-frozenlayout-right {
    width: 35%;
}
```

After some investigation turns out that the problem is this style:

```
.ui-datatable table.ui-datatable-fs {
    width: auto;
}
```

After setting it to 100% it works like a charm again.

**Comment by cagataycivici** [comment]
Showcase works fine so not sure what the problem is, we have auto width already in datatable.css.

**Comment by elperez** [comment]
Hello, I have a question.
I have frozen columns in .ui-datatable-frozenlayout-left that I don't want to be resized and eaten up by .ui-datatable-frozenlayout-right. is there any way I can make .ui-datatable-frozenlayout-left nonresizeable and always visible (so the frozen columns are visible)?
