### ISSUE TITLE
GraphicImage: allow byte[] and InputStream as value

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#6967]
This will require at least a new contentType attr.

**Comment by Rapster** [comment]
What you describe sounds very much like StreamedContent

**Comment by tandraschko** [comment]
it does but it makes it simpler; just do e.g.
```p:grahicImage value=#{varInUIRepeat.byteArray} contentType="image/png" stream=false```

so you dont have a wrapper method in your model class e.g.

**Comment by Rapster** [comment]
I don't know what you mean by wrapper method... one part of graphicImage input is set at different places: markup and java while it could be done in one place. You already implementing a getter in varInUIRepeat returning a byte[],  you can return StreamedContent at this point

**Comment by tandraschko** [comment]
varInUIRepeat might just be a POJO/Entity whatever, without PrimeFaces model stuff from another project-layer

**Comment by tandraschko** [comment]
i now commited it, its very basic and doesnt introduce new attributes.
What does this mean?
- we try to get the content type from the content via magic numbers in Data URI mode (stream=false)
- we dont set a content-type in the header when stream=true


IMO if someone would like to set contenttype, encoding, filename -> StreamedContent should be used.

@melloware interessted in document it? actually i didnt had the time today for implemeting it... :D

**Comment by melloware** [comment]
Yes let me review and document.
