### ISSUE TITLE
GMap: InfoWindow requires 'overlaySelect' and  'overlayDblSelect' simultaneously

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#6969]
**Describe the defect**
 
In  PF10.0.0-RC1  GMAP with  InfoWindow only works if both ajax are informed  (overlaySelect and overlayDblSelect) 

**Reproducer**

 [Docummentation]( https://primefaces.github.io/primefaces/10_0_0/#/components/gmap) doesn't mention that both are required, and  [infoWindow showcase](https://www.primefaces.org/showcase/ui/data/gmap/infoWindow.xhtml?jfwid=af262)  is also broked.  GMapRender.class should evaluate which of then are informed to prevent nullPointer.
  
**Environment:**
 - PF Version: 10.0.0-RC1
 - JSF + version: JSF 2.2.19
 - Affected browsers:  Chrome, Safari
 
**To Reproduce**
1. Go to  a page with <p:gmap> and <p:gmapInfoWindow>
2. GMapRender.class throws an exception when only one   ajax (overlaySelect or overlayDblSelect) was informed
3.    java.lang.NullPointerException at org.primefaces.component.gmap.GMapRenderer.encodeScript(GMapRenderer.java:134)  

**Expected behavior**

GMapRender.class should first evaluate which of then are informed to prevent nullPointer.

**Example**

XHTML 
 ```xml
   <p:ajax event="overlaySelect" listener="#{mapBean.onMarkerSelect}" update=":globalMessages" /> 
```

Error throwed by GMapRender.class:
```java
/*
         * Behaviors
         * - Adds hook to show info window **if one defined**
         * - Encodes behaviors
         */
        if (infoWindow != null) {
            Map<String, List<ClientBehavior>> behaviorEvents = map.getClientBehaviors();
            List<ClientBehavior> overlaySelectBehaviors = behaviorEvents.get("overlaySelect");
            for (ClientBehavior clientBehavior : overlaySelectBehaviors) {
                ((AjaxBehavior) clientBehavior).setOnsuccess("PF('" + widgetVar + "').openWindow(data)");
            }
            List<ClientBehavior> overlayDblSelectBehaviors = behaviorEvents.get("overlayDblSelect");
            for (ClientBehavior clientBehavior : overlayDblSelectBehaviors) {
                ((AjaxBehavior) clientBehavior).setOnsuccess("PF('" + widgetVar + "').openWindow(data)");
            }
        } 
```

**Comment by melloware** [comment]
Can you paste the stack trace of the error thrown?

**Comment by melloware** [comment]
Nevermind I see the issue.  Behaviors get can return NULL.
