### ISSUE TITLE
Wrong element gets focus when updatePageLinks is called in paginator

### ISSUE THREAD

**Issue by aldolizas** [primefaces/primefaces#697]
at the updatePageLinks method of paginator.js the focus event is fired for the element at tabindex
 if(focusContainer) {
            focusContainer.children().eq(tabindex).trigger('focus');
        }

Instead I suggest: 

  var selectedIndex;
        for(var i = start; i <= end; i++) {
            var styleClass = 'ui-paginator-page ui-state-default ui-corner-all';
            if(this.cfg.page == i) {
                styleClass += " ui-state-active";
                selectedIndex = i-start ;
            }

```
   this.pagesContainer.append('<span class="' + styleClass + '" tabindex="0">' + (i + 1) + '</span>')
   }
if(focusContainer) {
        focusContainer.children().eq(selectedIndex).trigger("focus");

    }
```

**Comment by ralf-br** [comment]
I had the same problem with exactly that trigger('focus') statement. In the updatePageLinks method it first determines focusContainer and tabindex. Then the visible page links get recalculated and at the end the focus gets triggered even if the page links changed. No focus event should be triggered or at least to the correct newly selected page.

This effect I can especially reproduce on IE9 with more then 10 pages in a lazy datatable (PF 5.2)... Clicking for example on Page 10 (last element) after the pagination the current Page 10 plus Page 14 (new last element, has the focus) is highlighted. See screenshot.
![paginationfocusbug](https://cloud.githubusercontent.com/assets/15786855/11088631/0ebf2638-8864-11e5-81df-afdef78a4fe5.PNG)

As a workaround I just triggered a blur() for all pages after each pagination event - obviously this shouldn't be the solution:

```
<p:ajax event="page" oncomplete="PF('idOfTable').getPaginator().pagesContainer.children('.ui-paginator-page').blur();" />
```

**Comment by melloware** [comment]
This has been fixed at some point in the last 4 years you can see from the source it now selects the active element of the children.
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js#L308
