### ISSUE TITLE
Improve animation performance on overlay panels

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#6973]
Remove show/hide animation of JqueryUI from the connected overlay panel. They can use CSS animations.

- [x] AutoComplete (remove 'effect' and 'effectDuration' attributes)
- [x] CascadeSelect
- [x] Datepicker
- [x] Password
- [x] SelectCheckboxMenu
- [x] SelectOneMenu (remove 'effect' and 'effectSpeed' attributes)
- [x] ThemeSwitcher (remove 'effect' and 'effectSpeed' attributes)
- [x] SplitButton
- [x] OverlayPanel (remove 'showEffect' and 'hideEffect' attributes)
- [x] Menu (overlay mode)
- [x] MenuButton
- [x] SlideMenu (overlay mode)
- [x] TieredMenu (overlay mode)
- [x] ConfirmPopup (remove 'showEffect' and 'hideEffect' attributes)
- [x] ContextMenu
---

This feature will not be added as the following components use a 3rd party API.
- [ ] ColorPicker
- [ ] Keyboard

**Comment by christophs78** [comment]
IMO there´s a regression with lazy SelectOneMenu. (reproduceable in showcase; ui/input/oneMenu.xhtml)
When you first click on the Lazy one it does not open. Please compare this to http://primefaces.org/showcase/ui/input/oneMenu.xhtml

**Comment by melloware** [comment]
I think DatePicker might have something similar going on.

**Comment by christophs78** [comment]
Overall this is a really good improvement!
We "only" should avoid breaking existing usecases. Together we get this done. :-)

**Comment by mertsincan** [comment]
> IMO there´s a regression with lazy SelectOneMenu. (reproduceable in showcase; ui/input/oneMenu.xhtml)
When you first click on the Lazy one it does not open. Please compare this to http://primefaces.org/showcase/ui/input/oneMenu.xhtml

@christophs78, it works fine for me.  Which browser are you using?

**Comment by christophs78** [comment]
> > IMO there´s a regression with lazy SelectOneMenu. (reproduceable in showcase; ui/input/oneMenu.xhtml)
> > When you first click on the Lazy one it does not open. Please compare this to http://primefaces.org/showcase/ui/input/oneMenu.xhtml
> 
> @christophs78, it works fine for me. Which browser are you using?

Edge 88; i´ll recheck this evening; currently (very) busy on my day-job

**Comment by christophs78** [comment]
> > IMO there´s a regression with lazy SelectOneMenu. (reproduceable in showcase; ui/input/oneMenu.xhtml)
> > When you first click on the Lazy one it does not open. Please compare this to http://primefaces.org/showcase/ui/input/oneMenu.xhtml
> 
> @christophs78, it works fine for me. Which browser are you using?

Everything fine today. .-) Maybe i had some browser-caching-issue yesterday.

**Comment by mertsincan** [comment]
Thanks a lot, @christophs78 ;)
