### ISSUE TITLE
Improve registered events on components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#6978]
For example, if a component is using the PrimeFaces.utils.registerScrollHandler to close its panel, the scroll event is called even if the panel is closed. Such events can be registered when the panel is visible.

https://user-images.githubusercontent.com/11868120/107623300-2ea79580-6c6a-11eb-836e-2c2cf7894f90.mov

- [x] AutoComplete
- [x] CascadeSelect
- [x] Datepicker
- [x] Password
- [x] SelectCheckboxMenu
- [x] SelectOneMenu
- [x] ThemeSwitcher
- [x] SplitButton
- [x] OverlayPanel
- [x] Menu
- [x] MenuButton
- [x] SlideMenu
- [x] TieredMenu
- [x] ConfirmPopup
- [x] ContextMenu
- [x] ColorPicker
- [x] Keyboard

**Comment by tandraschko** [comment]
we currently do this in each widget itself, see dialog.js ln784

**Comment by mertsincan** [comment]
Yes, but, I could not find unbind operations in components. The scroll event is always called. I think this will cause performance problems.

**Comment by tandraschko** [comment]
registerScrollHandler should remove itself on widget destroy

EDIT: it already does, see core.utils.js lin 384

**Comment by tandraschko** [comment]
Or do you like to remove/add the scroll handler when open/close a overlay?
its better of course but more "maintainence" in each widget

**Comment by mertsincan** [comment]
@tandraschko
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/forms/forms.password.js#L137

https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/forms/forms.password.js#L154

**Comment by tandraschko** [comment]
yep, thats cool

**Comment by melloware** [comment]
@mertsincan I always wondered about this since DatePicker registers and unregisters on popup open and close but I noticed we weren't doing that anywhere else in PF.  This is a good improvement!
