### ISSUE TITLE
Core: Bundle and automatically load client side locale Javascripts

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6982]
See

* https://github.com/primefaces/primefaces/wiki/Locales#client-localization
* https://github.com/primefaces-extensions/primefaces-extensions/issues/310

**Comment by jepsar** [comment]
We should probably bundle / translate these as well https://github.com/primefaces/primefaces/blob/master/src/main/resources/org/primefaces/Messages.properties

Should that become a new issue?

**Comment by tandraschko** [comment]
+1 for new issue

**Comment by jepsar** [comment]
Can be done per language.. I can take care of Dutch.

**Comment by melloware** [comment]
Added showcase Locale selector so anyone can see and test our locales.

![image](https://user-images.githubusercontent.com/4399574/108413654-45fdfa00-71f9-11eb-825d-de8e0e0be8fb.png)
