### ISSUE TITLE
Primefaces X release candidate 1 for jsf.

### ISSUE THREAD

**Issue by jdbenitezh** [primefaces/primefaces#6983]
Using a p:password after p:selectOneMenu causes the drop-down to contain the available login passwords instead of the assigned data.   

`
ui:define name="content">
        <h:form id="fform">
            <p:card>

                <div class="ui-fluid">
                    <p:outputLabel for="@next" value="#{lbl.language}" styleClass="p-col-12 p-md-2"/>
                    <div class="p-col-12 p-md-10">
                        <p:selectOneMenu value="#{userAdmCrudMB.editionItem.langCode}" required="true">
                            <f:selectItem itemValue="#{null}" itemLabel="#{lbl.chooseLang}"/>
                            <f:selectItem itemValue="ca"    itemLabel="Català"/>
                            <f:selectItem itemValue="es" itemLabel="Castellano"/>
                        </p:selectOneMenu>
                    </div>
                </div>

                <div class="p-field p-grid">
                    <p:outputLabel for="@next" value="#{lbl.password}" styleClass="p-col-12 p-md-2"/>
                    <div class="p-col-12 p-md-10" align="left">
                        <p:password/>
                    </div>
                </div>

            </p:card>
        </h:form>

    </ui:define>
`

**Comment by melloware** [comment]
Can't reproduce:
[pf-6983.zip](https://github.com/primefaces/primefaces/files/5974465/pf-6983.zip)


Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml
