### ISSUE TITLE
Tabview: facet actions not displayed properly

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#6985]
Hi there,

The new primefacesX component Tabview have issue with facet name="actions" is not displaying properly.

Here is sample code

```xml
<p:tabView>
            <p:tab title="general">
                <f:facet name="actions">
                    <h:panelGroup style="float:right">
                        <p:commandButton value="Save" />
                    </h:panelGroup>
                </f:facet>
            </p:tab>
            <p:tab title="Expenses">
                
            </p:tab>
</p:tabView>
```

Please see here:

![image](https://user-images.githubusercontent.com/3331466/107858807-ff2b9f80-6e9a-11eb-975f-14e3559031e0.png)

**Comment by melloware** [comment]
What theme are you using?

**Comment by anuragnz** [comment]
Its using default theme which I think is "Saga".

**Comment by melloware** [comment]
This is definitely a Theme issue assigning to @mertsincan .

Reproducer:
[pf-6985.zip](https://github.com/primefaces/primefaces/files/5976589/pf-6985.zip)


8.0
![image](https://user-images.githubusercontent.com/4399574/107862466-04e1a080-6e1b-11eb-8f49-f107b6277da5.png)

10.0.0
![image](https://user-images.githubusercontent.com/4399574/107862506-1e82e800-6e1b-11eb-8a24-dec735f4bfdb.png)

**Comment by anuragnz** [comment]
Thanks. Just confirming its working fine now.
