### ISSUE TITLE
Button: button and commandButton are laid out differently

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6986]
It looks that p:button and p:commandButtons are differently layouted. In my example below buttons 1,2,3, and 6 are p:button while 4 and 5 are p:commandButtons

![Screenshot from 2021-02-13 21-06-16](https://user-images.githubusercontent.com/10051373/107860465-bf839a00-6e3f-11eb-8383-eba76ac3424b.png)

Many thanks in advance for having a look on this issue.

**Comment by melloware** [comment]
Can you provide exact XHTML to reproduce. Or a PF test reproducer?

**Comment by tuerker** [comment]
While trying to create a reproducer (see below), i detected the problem has other reasons: button and commandButton are not layouted differently.

Rather the reported layout problem is simply due to the fact that in my panelGrids the h:form is around each commandButton as follows:

```
    <h:panelGrid columns="2">
      <p:button value="Button" />
      <h:form>
        <p:commandButton value="CommandButton" />
      </h:form>
    </h:panelGrid>

```
Interestingly, with THEME=none (as in the reproducer) this problem does not appear. But for the template DIAMOND i had the problem as shown above. Of course, this problem can easily be avoided when the h:form is placed around the panelGrid:

```
  <h:form>
    <h:panelGrid columns="2">
      <p:button value="Button" />
      <p:commandButton value="CommandButton" />
    </h:panelGrid>
  </h:form>
```

[p-button.zip](https://github.com/primefaces/primefaces/files/5976711/p-button.zip)

**Comment by melloware** [comment]
**No theme:**
![image](https://user-images.githubusercontent.com/4399574/107876656-38611100-6e95-11eb-8648-a046ab397932.png)

**Saga:**
![image](https://user-images.githubusercontent.com/4399574/107876680-54fd4900-6e95-11eb-89d7-b161818e5fae.png)


Both look fine to me.  Could your issue be you are using the Diamond theme that hasn't been updated for PF10 yet?  Because Saga Vela and Arya all look fine.

**Comment by tuerker** [comment]
@melloware i can verify that the reproducer looks fine for the given example in both cases: theme=none as well as for the diamond template. the form element in the css looks as follows in any case:

```
form {
    display: block;
    margin-top: 0em;
}
```

using the code fragment of the reproducer in my code, however, produces the following css element for the form whenever the form is used inside a panelgrid:

```
form {
    display: block;
    margin-top: 0em;
    margin-block-end: 1em;
}
```

![Screenshot from 2021-02-14 21-51-35](https://user-images.githubusercontent.com/10051373/107889077-bf070400-6f10-11eb-9dac-6ad116124076.png)

the difference to the reproducer is the third line:

`    margin-block-end: 1em;
`

which is not added in case of the repoducer.

since i am not using any css parts of our code, I am pretty sure that this must be produced by the "diamond" template.

maybe the theme experts have an idea when this margin-block-end comes into the game?

**Comment by mertsincan** [comment]
Hi,
I couldn't replicate it with Saga, Vela and Arya themes. Could you please try these themes? If you think this problem is related to the Diamond theme, please create a ticket in https://forum.primefaces.org/viewforum.php?f=136 

For now, close. If the problem persists, please reopen this ticket.

Best Regards,

**Comment by tuerker** [comment]
@mertsincan i can confirm that this issue does not arise it with Saga, Vela and Arya themes. however, it is definitely an issue with the Diamond template. Our Diamond template is from November 2020. Is there an update of this template? If yes, how we get it?
