### ISSUE TITLE
DataTable/TreeTable: sortBy not working with client saving state method

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#6987]
**Describe the defect**
After migrate from PF8 to 10, all DataTables and TreeTables with  "sortBy" defined in columns stops to work. 

Trying to debug I could see that in  **org.primefaces.component.datatable.feature.SortFeature.class** , from  line 152:
`Map<String, SortMeta> sortBy = table.getActiveSortMeta();` is always empty and `Object varBackup = context.getExternalContext().getRequestMap().get(var);`  is null.   

I also note that `getSortByAsMap().values().stream().filter(SortMeta::isActive)` shows that 'SortMeta cannot be resolved'. I can confirm that all of them was working fine in PF previous version.  **Anyone could help?**

**Environment:**
PF Version: 10.0.0-RC1
JSF + version: JSF 2.2.19
Affected browsers: Chrome, Safari
Locale var:  'pt_BR'

**Reproducer:**
https://github.com/edudoda/primefaces-test-cases

**To Reproduce**
0. Set STATE_SAVING_METHOD  as client in **web.xml:**
```
  <context-param>
        <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
        <param-value>client</param-value>     <!--  when = 'server' is ok!  -->
    </context-param>

```
 1. Go to '<p:dataTable' component with any column defined with a  single like  '<p:column  sortBy="#{item.name}"'
2. Click on 'Sort header.'
3. Nothing changes.

**Expected behavior**

**Example XHTML**
```     
 <p:column    sortBy="#{item.name}"      >    
```

**Example Bean**
```java
public void sort(FacesContext context, DataTable table) {
        Object value = table.getValue();
        if (value == null) {
            return;
        }

        List<?> list = resolveList(value);    //ok with objects
        Locale locale = table.resolveDataLocale();   // << pt_BR
        String var = table.getVar(); // << item
        Collator collator = Collator.getInstance(locale);   //<< java.text.RuleBasedCollator@289747d6
        AtomicInteger comparisonResult = new AtomicInteger();  // <<  = 0
        Map<String, SortMeta> sortBy = table.getActiveSortMeta();  //   = {}  SortMeta cannot be resolved'

        Object varBackup = context.getExternalContext().getRequestMap().get(var); // = null

        list.sort((o1, o2) -> {
            for (SortMeta sortMeta : sortBy.values()) {
...
```

**Comment by tandraschko** [comment]
@Rapster can you assist please?

**Comment by Rapster** [comment]
Did you try with the latest source/build (e.g jitpack)? I can't reproduce the issue on showcase

**Comment by edudoda** [comment]
I'm running it from Maven, also my JSF related is:  
```
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>10.0.0-SNAPSHOT</version>
</dependency>

 <dependency>
	<groupId>com.sun.faces</groupId>
	<artifactId>jsf-api</artifactId>
	 <version>2.2.19</version> 
 </dependency>
	
<dependency>
      <groupId>com.sun.faces</groupId>
      <artifactId>jsf-impl</artifactId>
      <version>2.2.19</version>
</dependency>  
```

**Comment by Rapster** [comment]
Still can't reproduce your issue based on infos you've given. Please provide a runnable reproducer of your issue using https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment]
I cant reproduce either. Closing until OP comes back with a reproducer.

**Comment by edudoda** [comment]
I ran 'primefaces-test' and it works. 
But not in my environment, I'm still trying to figure it out... will try to send a reproducer... 
Thanks in advance!

**Comment by edudoda** [comment]
Hi @melloware and @Rapster, 
sorry for the long delay, it took me a while to discover what was wrong. I started reproducing all my environment libs and configurations comparing it to the **primefaces-test** code provided and finally found it!

To reproduce the problem, just include this param in **web.xm**l:
```
  <context-param>
        <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
        <param-value>client</param-value>     <!--  when = 'server' is ok!  -->
    </context-param>
```

Also, as I noticed if I downgrade to PF 8.0 it works.

**Comment by edudoda** [comment]
Hi guys, I also noted that now, when a table is initially sorted using a Collection (not SortMeta type) eg.:  `<p:dataTable sortBy="#{bean.xpto}" .../> `  it **doesn't show the initial active sorted icon** on that column and **always defaults to descending** order, it's only possible to change/use  sortOrder="asc" when in each column (before we could set it from p:dataTable param).  

And also, each column we set "sortOrder" param it becomes automatically initially sorted by default. Is it right?

**Comment by Rapster** [comment]
> Hi guys, I also noted that now, when a table is initially sorted using a Collection (not SortMeta type) eg.: `<p:dataTable sortBy="#{bean.xpto}" .../> ` it **doesn't show the initial active sorted icon** on that column and **always defaults to descending** order, it's only possible to change/use sortOrder="asc" when in each column (before we could set it from p:dataTable param).
> 
> And also, each column we set "sortOrder" param it becomes automatically initially sorted by default. Is it right?

Does it happen because of the client saving state method?

**Comment by edudoda** [comment]
No... not related,  I already switched to server saving after that, so it's happening in server method.

It's another issue, but I'm asking first because maybe it's the new desired behavior, as I didn't found sortOrder="" param  for dataTable itself on [new manual](https://primefaces.github.io/primefaces/10_0_0/#/components/datatable?id=datatable). 

I just can see   'Defect report' or  'Feature request', where is the best place to ask questions like that? Or should I always open as an issue next times?

**Comment by Rapster** [comment]
Sounds like an defect then

**Comment by melloware** [comment]
So @edudoda is this still an issue now that Rapster pointed out the other problem with your reproducer?

**Comment by edudoda** [comment]
Yes, reproducer is now updated to reflect this.

**Comment by melloware** [comment]
This client side saving issue has also been raised on Discord and the forums by other users.

**Comment by SirError** [comment]
is there any workaround for this case besides changing the state saving method to server?

**Comment by paoesco** [comment]
Hello everybody,

Facing the same problem here.
Adding in web.xml
```
    <context-param>
      <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
      <param-value>client</param-value>
    </context-param>
```
I reproduce the issue in my code (very simple datatable) and also in a more complex project.

No workaround found, and I would love to have this issue resolved, I wanted to avoid to pay for extra memory when users can store the state in their side :)

**Comment by robertoferreirajrr** [comment]
Hi Guys!

Same here!... exactly like @paoesco describes!

**Comment by matsandreassen** [comment]
Took me all day to discover this. Great to see that others have already encountered it. I use client side state saving in order to load balance effectively so I'd prefer this be fixed as well.

**Comment by tandraschko** [comment]
can anyone provide me a simple as possible primefaces-test project?

**Comment by melloware** [comment]
@tandraschko here you go...
[pf-6987.zip](https://github.com/primefaces/primefaces/files/6421169/pf-6987.zip)

**Comment by tandraschko** [comment]
fixed it now by removing UIComponent from Meta
they were transient and not correctly initialized, also UIComponent shouldnt be used actually, therefore we have invokeOnColumn

**Comment by tandraschko** [comment]
@mertsincan @sqores good candidate for 10.0.1

**Comment by stolp** [comment]
10.0.1 is already released it seems ...

**Comment by Species8372** [comment]
I am currently using Version 10.0.1, with server-side state-saving.

Changing Sortings by clicking on column-headers did not pass the information all the way to the lazy model. 
The sort-information got lost in SortFeature.decode(), because the SortMeta.getComponent() was always null.

I removed the following lines in SortFeature.decode() and it is now behaving as i'd expect:

`
if (!(sortBy.getComponent() instanceof UIColumn)) {
                continue;
}
`

It looks like it is correlated to @tandraschko 's comment  "fixed it now by removing UIComponent from Meta" from 4.th of May...

**Comment by melloware** [comment]
@Species8372 why not update to 10.0.2 since you are using 10.0.1 i believe it has this fix already in it?

**Comment by Species8372** [comment]
Thankx for the hint. I was not aware of the 10.0.2 - release as i have started the migration just before its release.
I can confirm the Sort is now working.

Thank you for your quick response, melloware

**Comment by paoesco** [comment]
Is this only for elite users ?
That's a regression from previous primefaces versions so I would have expected to be available to everybody

**Comment by melloware** [comment]
@paoesco Yes the bug is in Community 10.0 and the fix is only in Elite 10.0.2. That is how the Elite subscription works.  If not you will have to wait until Community 11.0 comes out.

**Comment by BalusC** [comment]
In case anyone is interested, here's a work around (I also faced this issue on non-elite PF10).

```
public class PatchedDataTableRenderer extends DataTableRenderer {
    @Override
    public void decode(FacesContext context, UIComponent component) {
        ((DataTable) component).setSortByAsMap(null); // PF #6987: Clear out unsaved transient state.
        super.decode(context, component);
    }
}
```
`faces-config.xml`
```
<render-kit>
    <renderer>
        <component-family>org.primefaces.component</component-family>
        <renderer-type>org.primefaces.component.DataTableRenderer</renderer-type>
        <renderer-class>com.example.PatchedDataTableRenderer</renderer-class>
    </renderer>
</render-kit>
```

**Comment by melloware** [comment]
@BalusC thank you i have added the label "workaround" for your excellent workaround provided.
