### ISSUE TITLE
DataTable: Paginator not highlighting the currently focused item

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#6988]
**Describe the defect**
I am currently checking parts of our application for an upcoming accessibility test and when testing the PF10 branch I found that the paginator does not highlight the currently focused item.

In PF8 when you tabbed through the different paginator elements of a DataTable, the currently focused item would always be highlighted to give the user feedback as to which item was currently selected. In PF10 it seems like this does not work anymore. The showcase is also affected. The "ui-state-focus" class is still being set correctly but it seems like the CSS for it is missing.

**Reproducer**
Showcase DataTable Pagination -> Tab through paginator elements
https://www.primefaces.org/showcase/ui/data/datatable/paginator.xhtml?jfwid=443e5

**Expected behavior**
The currently focused item should be highlighted.

**Comment by melloware** [comment]
Theme issue so I have assigned to @mertsincan
