### ISSUE TITLE
Theme: p:selectOneMenu with empty noSelectionOption is too small

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6990]
Reproducer:
```
<p:selectOneMenu value="#{testView.string}">
    <f:selectItem noSelectionOption="true"/>
    <f:selectItems value="#{['a','b','c']}"/>
</p:selectOneMenu>
```

Confirmed with Saga, but will likely occur on all new themes:

<img width="104" alt="Screenshot 2021-02-15 at 14 59 11" src="https://user-images.githubusercontent.com/7500178/107955714-641bee00-6f9e-11eb-95e1-d8d274e76028.png">

<img width="93" alt="Screenshot 2021-02-15 at 14 59 42" src="https://user-images.githubusercontent.com/7500178/107955768-785feb00-6f9e-11eb-8983-129f4150df54.png">

**Comment by tandraschko** [comment]
@mertsincan theme error, can you check it plz?

**Comment by jepsar** [comment]
As a workaround one could use `itemLabel="&#xA0;"`...

**Comment by melloware** [comment]
Hmm in the `forms.selectonemenu.js` we put `labelText = '&nbsp;';` in other situations where its null.  I wonder if its not happening in this case?  Or you are saying this was working in 8.0 and definitely broken with the new themes?

**Comment by jepsar** [comment]
Yes, this was working with 8 (Nova Light)

**Comment by mertsincan** [comment]
It's fixed for now, but we need to change the placeholder behavior in PF11.
https://primefaces.org/primereact/showcase/#/dropdown
