### ISSUE TITLE
PickList - Version 6.0.2 - Not able to move selected item one item above

### ISSUE THREAD

**Issue by riteshsingh03** [primefaces/primefaces#6991]
**Describe the defect**
Not able to move selected item one step above, showing error in console TypeError: e.querySelector is not a function.

[https://primefaces.org/primereact/showcase/#/picklist](url)

**Reproducer**
Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your reproducer here. **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub. Please test with that before reporting a bug that may already be fixed.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.8 or MyFaces 2.3.6_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. Go to Picklist and select on item from the picklist item list.
2. Click on single up arrow button.
3. See error and it will show blank screen.

**Expected behavior**
It should move selected item one item above.

**Example XHTML**
```html
<h:form id="frmTest">
  ..
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

}
```

**Comment by tandraschko** [comment]
This repository is for PrimeFaces, not PrimeReact. Please use the right repository/issue tracker.
