### ISSUE TITLE
ProgressBar: labelTemplate not visible anymore

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#6997]
**Defect**
PrimeFaces 10 seems to break `progressBar`'s `labelTemplate`. The specified text is not shown anymore. Default template is used in both cases. Custom css removed for test purposes.

Behaviour until 8.0:
<img width="228" alt="Bildschirmfoto 2021-02-16 um 17 04 42" src="https://user-images.githubusercontent.com/6633403/108089865-563b9b00-707a-11eb-8602-1f4a7b084f59.png">

Current behaviour (RC1 and current master):
<img width="218" alt="Bildschirmfoto 2021-02-16 um 17 05 17" src="https://user-images.githubusercontent.com/6633403/108089991-72d7d300-707a-11eb-8845-f09571e9291a.png">

**Environment:**
 - PF Version: _10.0.0-RC1_
 - JSF + version: _Mojarra 2.3.9.SP06_
 - Affected browsers: _ALL_

**Expected behavior**
Label template text is shown on progress bar.

**Example XHTML**
```
<p:progressBar labelTemplate="Text"/>
```

**Comment by tandraschko** [comment]
@mertsincan thats a theme issue for you

**Comment by melloware** [comment]
Yep its broken currently in showcase: https://www.primefaces.org/showcase/ui/misc/progressBar.xhtml

**Comment by buunsal** [comment]
closed with https://github.com/primefaces/primefaces/commit/cf8b7d67b1b52dfeca8f46bc274b2212fce4b5f5
