### ISSUE TITLE
Multiple date selection in Calendar

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#7]
Add a feature to calendar component to support multiple dates instead of single. Value attribute should refer to a list of dates.

**Comment by buddhika75** [comment]
If value attribute referral changed from Date to List of dates, will it change the backward compatibility?

**Comment by cagataycivici** [comment]
It will be backward compatible, by default value is a Date. When multiple selection is enabled, we'd assume it is a list.

**Comment by banifou** [comment]
That would be great to have this. Can't wait!

**Comment by kukel** [comment]
If I work on https://github.com/primefaces/primefaces/issues/2202, this one will most likely be 'fixed' too

**Comment by melloware** [comment]
This will be fixed with the new DatePicker being ported from PrimeNG in the next PF: https://www.primefaces.org/primeng/#/calendar

**Comment by melloware** [comment]
This feature is now available in DatePicker: https://github.com/primefaces/primefaces/issues/4360

@tandraschko this ticket can be closed.
