### ISSUE TITLE
Toolbar: Styles are not responsive

### ISSUE THREAD

**Issue by buunsal** [primefaces/primefaces#7000]

**Comment by Rapster** [comment]
Why remove separator support?

**Comment by buunsal** [comment]
Because the seperator component was deprecated, it had to be replaced with the divider or removed. What is your opinion on this issue? Do you think the separator should remain or be replaced with the divider component? You can also take a look at the current showcase github for use without a seperator.

**Comment by Rapster** [comment]
We usually deprecate first and then remove support on the next release.

**Comment by melloware** [comment]
@sqores did you try Toolbar with `<p:divider layout="vertical" />` I know I fixed it for MenuBar with this PR: https://github.com/primefaces/primefaces/pull/6992
