### ISSUE TITLE
Documentation: deprecate locales wiki and redirect to documentation

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7002]
.. as done with the migration guide.

https://github.com/primefaces/primefaces/wiki/Locales

https://primefaces.github.io/primefaces/10_0_0/#/core/localization

See also

https://github.com/primefaces/primefaces/issues/6982

https://github.com/primefaces/primefaces/issues/6995

From the documentation we could link to the locale file folder(s) in the source tree instead of embedding them all.

**Comment by melloware** [comment]
This is complete! Wiki Deprecated with instructions on what to do if you have a new language or a change to be made.  Localization.md has been updated with links to the source tree.
