### ISSUE TITLE
DatePicker: JS-Error in destroy and refresh

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#7004]
**Describe the defect**
When the DatePicker widget should be removed during `PrimeFaces.ajax.Response.destroyDetachedWidgets` it will throw a JS error because of an illegal usage of a utililty method.

![grafik](https://user-images.githubusercontent.com/3531183/108367960-37fca900-71fa-11eb-92c8-852b688cc6d5.png)

```Javascript
// ... code from refresh
PrimeFaces.utils.cleanupDynamicOverlay(this, this.panel, this.id + '_panel', this.cfg.appendTo);

// ... code from destroy
PrimeFaces.utils.removeDynamicOverlay(this, null, this.id + '_panel', this.cfg.appendTo);
```

In both cases `this.cfg.appendTo` is a string - per default `@(body)`. But both utility methods expect a JQuery instance. (see [here](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.utils.js#L83))

**Environment:**
 - PF Version: 10.0.0-RC1
 - Affected browsers: ALL

**Comment by tandraschko** [comment]
@melloware you introduced core.utils.js #resolveAppendTo.
for me the method is quite weird. what is panel? the overlay?

**Comment by melloware** [comment]
Looking...

**Comment by tandraschko** [comment]
I think we should pass it as param and add a good doc for it.

**Comment by melloware** [comment]
yep on it. I am looking at that commit and most of the components have a "panel" but we should pass it in.  working on it now.

**Comment by melloware** [comment]
OK please review my PR.  Refactored appendTo to take Panel in and in 1-datepicker.js used the same `resolveDynamicOverlay` method as used in the core widget.

**Comment by fanste** [comment]
Thanks for the quick fix. But there seems to be one error:
```Javascript
resolveDynamicOverlayContainer(widget)
```

`widget` == `this`? Because `widget` is undefined.

**Comment by tandraschko** [comment]
already fixed it. can you try again?

**Comment by tandraschko** [comment]
@melloware overlaypanel.js #setupDialogSupport - isnt that exactly your #resolveAppendTo method?

**Comment by melloware** [comment]
Yep!  Looks like I never found that one when I did the original refactoring of all this boilerplate.  You fixing it?

**Comment by tandraschko** [comment]
would be great if you can do that in another ticket and do the tests:
+ only 1 DOM overlay left after update
+ all DOM overlay removed on widget destroy

both with custom appendTo (like @form) and default.
Thats really a tricky place an everything must work.

also see colorpicker (may a bit different, no appendTo config support, we may refactor this even in another ticket)

**Comment by fanste** [comment]
> 
> 
> already fixed it. can you try again?

Now it is working. Thanks

**Comment by melloware** [comment]
New ticket created: https://github.com/primefaces/primefaces/issues/7009

And you are right ColorPicker does look similar but slightly different. Have to look at that one more.
