### ISSUE TITLE
Resuse already resolved FacesContext

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#7005]
**Describe the defect**

Not really a defect, but a minor improvement.

While debugging through the PF code I found a place where the FacesContext is resolved using `getFacesContext()` while it is already available as a method parameter. A search revealed 3 places where this is the case.

https://github.com/primefaces/primefaces/blob/afc689c39b6ae3675cd7455f65a081737a3a3334/src/main/java/org/primefaces/component/api/UIData.java#L260
https://github.com/primefaces/primefaces/blob/afc689c39b6ae3675cd7455f65a081737a3a3334/src/main/java/org/primefaces/component/api/UIData.java#L289
https://github.com/primefaces/primefaces/blob/afc689c39b6ae3675cd7455f65a081737a3a3334/src/main/java/org/primefaces/component/api/UITabPanel.java#L231

Any reason why it does not reuse the method parameter? Or simply a "mistake" due e.g. copy&paste?

**Environment:**
 - PF Version: 10.0.0-RC1

**Comment by tandraschko** [comment]
PR would be great

**Comment by tandraschko** [comment]
same here e.g. https://github.com/primefaces/primefaces/blob/afc689c39b6ae3675cd7455f65a081737a3a3334/src/main/java/org/primefaces/component/api/UITabPanel.java#L637
