### ISSUE TITLE
Core: getUnproxiedClass support Quarkrus/Hibernate

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7015]
**Description**
Our code `LangUtils.getUnproxiedClass(class)` is returning the incorrect class for Quarkus.

Quarkus proxies end with `_ClientProxy` so for example:

```
Class:class com.melloware.AutoCompleteView_ClientProxy 
SuperClass:class com.melloware.AutoCompleteView
```

**Comment by tuerker** [comment]
@melloware: what about hibernate proxy which was formerly $$

    private static final String HIBERNATE_PROXY = "$HibernateProxy$";

**Comment by melloware** [comment]
Is that new?  Meaning did hibernate just change that?

**Comment by tuerker** [comment]
I think more than 2 years ago. From our git i see that we changed it in May 2018.

**Comment by tuerker** [comment]
i would revise it as follows to run also with older hibernate versions:

`(name.contains("$$") || name.contains("$HibernateProxy$") || name.contains("_ClientProxy"))`

**Comment by melloware** [comment]
@tandraschko what do you think?

**Comment by tandraschko** [comment]
Yep, why not

**Comment by melloware** [comment]
I also submitted a PR at DeltaSpike: https://github.com/apache/deltaspike/pull/116
