### ISSUE TITLE
TreeTable: Add Support for new DataExporter

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#7018]
**Description**
At the moment only Datatable is implemented with the _new_ DataExporter Implementation

**Describe the solution you would like**
Also support exporting TreeTables with the new generic DataExporter

See PR for possible Solution, atm its more or less a 1:1 copy of the DataTable Exporter with adjustments for the TreeTable node iteration.
Maybe some common functionality could be merged, but then they would no longer be independent, and I would have needed to change the datatable functionality as well, which I would rather not do. So atm there is a bit of copied/duplicated code.

see Pull Request at: https://github.com/primefaces/primefaces/pull/7017

```

**Comment by melloware** [comment]
Nice. I think when we broke these out the idea was each component implement its own exporters so I am ok with the copying.  You are right if we refactor too much we don't want to lose the independence.
