### ISSUE TITLE
Datatable: SelectOneMenu has wrong value after filtering

### ISSUE THREAD

**Issue by felixoi** [primefaces/primefaces#7026]
**Describe the defect**
After filtering in a datatable with a SelectOneMenu in a column the value of the SelectOneMenu gets a wrong value. It seems like the selection is still the value from the entry which was in the row before the filtering.

**Reproducer**
https://github.com/felixoi/primefaces-test

**Environment:**
 - PF Version: 10.0.0-RC1
 - JSF + version: Mojarra 2.2.8
 - Affected browsers: All

**To Reproduce**
1. Take a look at the last row in the datatable. The SelectOneMenu has the value 'THREE'.
2. Filter the name by 'Test 5'.
3. As you can see, 'ONE' is now selected.
4. You can remove the filter, 'ONE' is still selected for 'Test 5'

**Expected behavior**
The value of the SelectOneMenu should not change.

**Comment by Rapster** [comment]
I can see it works fine in 8.0 but not in the current build

**Comment by torbenw** [comment]
We have the same problem with PF 10.0.0-RC1. When debugging you can see that the setter for the property is called in the backend, so it's not just a frontend problem.

**Comment by melloware** [comment]
This is ringing a bell. I think we fixed a similar issue for 10RC1 that was the SelectOne not having the right values after filtering. I am trying to find the ticket.

**Comment by melloware** [comment]
This is the issue I was referring to but it turned out to be a Mojarra only issue: https://github.com/primefaces/primefaces/issues/6427

**Comment by Rapster** [comment]
Yeah but it's working in 8.0... :(

**Comment by melloware** [comment]
Yep so probably not the same issue. It just sounded familiar.

**Comment by Rapster** [comment]
Or, my last clue is that something changed in UIData between 8.0 and 10.0

**Comment by felixoi** [comment]
Seems like we need to sadly move down to 8.0 again, as our software heavily depends on datatables 😞

**Comment by Rapster** [comment]
Did you try with a `h:selectOneMenu` ?

**Comment by felixoi** [comment]
Yes, I'm getting the same result @Rapster.

**Comment by Rapster** [comment]
Did you try to debug and see why current behavior happens?

**Comment by felixoi** [comment]
I only did the debugging as far as @torbenw. The setter is called with the wrong value when filtering. Any tips what to debug further (never did any primefaces internal debugging)? @Rapster

**Comment by Tammo0987** [comment]
I have the same issue, the fix is also urgent for me.

**Comment by tandraschko** [comment]
Can you try to revert PF UIData changes and try fo find a breaking commit?

**Comment by felixoi** [comment]
Last working is 9b5c7a23d0f717b524ab669166dba8265315ab38 and first broken is f6e3969e1c8cbedeec945c6bd9f3546152fb2b34 @tandraschko

**Comment by tandraschko** [comment]
can you try to revert some stuff and provide a PR?
maybe a naming issue ( columns vs uicolumns)? Otherwise i dont see anything releated

**Comment by Rapster** [comment]
You sure about that, looks like only renaming has been done in this commit regarding DataTable?

**Comment by felixoi** [comment]
Theoretically, it can also be any other commit between these both which do not affect UIData. Only checked the commits which had changes in UIData

**Comment by Rapster** [comment]
I see, so maybe in DataTable post https://github.com/primefaces/primefaces/commit/9b5c7a23d0f717b524ab669166dba8265315ab38

**Comment by felixoi** [comment]
@Rapster as I said, 9b5c7a23d0f717b524ab669166dba8265315ab38 is working.

**Comment by Rapster** [comment]
Yup that's what I'm saying 😉

**Comment by felixoi** [comment]
@Rapster sorry, i missread your message :) I acutally found the commit, it's 6ce1163c107f3445962620ecb14075cffc23d63a

**Comment by Rapster** [comment]
Cool, I'll try to have a look as soon as I can

**Comment by Rapster** [comment]
You can have a try with PR https://github.com/primefaces/primefaces/pull/7033 (you can either fork or download source from my branch https://github.com/Rapster/primefaces/tree/fix-7026)

**Comment by felixoi** [comment]
Reopening as this is not fully fixed. I've updated my reproducer accordingly.

New steps to reproduce:
- Filter by name 'Test 5'
- Filter by type 'Three'
-> All SelectOneMenu values are set to null

**Comment by Rapster** [comment]
Since there is only one result, how do you end up having all select components values to null? Can't reproduce so far

**Comment by felixoi** [comment]
Actually i don't know if my steps to reproduce are/were correct. I even get this if i search for 'Test 6' which has no results and then removing the filtering again.

**Comment by melloware** [comment]
Make sure to try with -Pmyfaces23 profile there was a similar bug reported like this before and it was a mojarra issue it worked fine in MyFaces.

**Comment by felixoi** [comment]
@melloware Seems like you are correct. Both works for myfaces..

**Comment by Rapster** [comment]
Reproduced indeed with Test 6, but the bug is also here in 8.0. At this point, we can blame Mojarra :p

**Comment by melloware** [comment]
Yep another user I think in the ticket I posted higher up in this thread reported the same thing and We realized it was a mojarra. Myfaces rocks.

**Comment by christophs78** [comment]
We should add a integration-test for this. I´ll look into this. DataTable is such a complex beast.

**Comment by kguelzau** [comment]
Is there any workaround beside switching to myfaces?
We had no problems with PF 8.x and mojarra 2.2.20 but with PF 10.0 and mojarra 2.3.14

Is https://github.com/eclipse-ee4j/mojarra/issues/4562 which is mentioned in #6427 also the root cause for this issue?

**Comment by Rapster** [comment]
Try to set to true rowStatePreserved attribute of datatable. Let us know if that work?

**Comment by torbenw** [comment]
We tried to set rowStatePreserved on the datatable, but after that the label of each dropdown seems to be a concatenated string of all the selected dropdown values in the datatable. It's not possible to open the dropdown menus either.
![rowStatePreserved1](https://user-images.githubusercontent.com/1230226/111613149-80e65400-87de-11eb-916f-b552875a78cc.png)
![rowStatePreserved2](https://user-images.githubusercontent.com/1230226/111613154-817eea80-87de-11eb-9fc5-9bb4ce1afb67.png)


On a different page the option causes an exception and the page can't be rendered anymore. "var" is set for the datatable. "field" is not set, but is not set for the working datatable and its columns either.
`javax.faces.FacesException: Table 'var' and Column 'field' attributes must be non null.
    at org.primefaces.component.api.UITable.createValueExprFromVarField(UITable.java:100)
    at org.primefaces.component.api.UITable.getConvertedFieldValue(UITable.java:571)
    at org.primefaces.component.datatable.DataTableRenderer.encodeDefaultFieldCell(DataTableRenderer.java:1345)
    at org.primefaces.component.datatable.DataTableRenderer.encodeCell(DataTableRenderer.java:1332)
    at org.primefaces.component.datatable.DataTableRenderer.encodeRow(DataTableRenderer.java:1256)
    at org.primefaces.component.datatable.DataTableRenderer.encodeRows(DataTableRenderer.java:1165)
    at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:1105)
    at org.primefaces.component.datatable.DataTableRenderer.encodeTbody(DataTableRenderer.java:1058)
    at org.primefaces.component.datatable.DataTableRenderer.encodeRegularTable(DataTableRenderer.java:392)
    at org.primefaces.component.datatable.DataTableRenderer.encodeMarkup(DataTableRenderer.java:322)
    at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:95)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
    ...`

**Comment by christophs78** [comment]
Overall this is far away from ideal. It may cause people loosing data. Think of someone who first set´s a filter and saves data without looking what happened.
Even if it´s a Mojarra bug. To someone without in depth-knowledge it look´s like the overall package is bad.

**Comment by christophs78** [comment]
@Dazzlingbob: Did some debug-work on this, based on our integration-tests.
I looked what happens after https://github.com/primefaces-extensions/primefaces-integration-tests/blob/master/src/test/java/org/primefaces/extensions/integrationtests/datatable/DataTable009Test.java#L162.

MyFaces:
![DataTable_7026_MyFaces](https://user-images.githubusercontent.com/10461942/113034308-3d9ec480-9192-11eb-9dd6-f4cc3839e078.png)

Mojarra:
![DataTable_7026_Mojarra](https://user-images.githubusercontent.com/10461942/113034337-4394a580-9192-11eb-91a8-c151b7b69410.png)

Do you have some idea how to reproduce this on Mojarra without PrimeFaces. So we can open an Mojarra-issue?

**Comment by christophs78** [comment]
Did some more debugging why it behaves different with Mojarra compared to MyFaces.

When DataTable has a filter which results in no rows a empty list is put as value into StateHelper.
![image](https://user-images.githubusercontent.com/10461942/113043378-a5f2a380-919c-11eb-83f6-61adf737bd21.png)

One request-cycle later - on Mojarra - it´s not a empty list any more. Instead it´s null. And null causes a EL-re-evaluation. Resulting in this issue.
![image](https://user-images.githubusercontent.com/10461942/113043408-adb24800-919c-11eb-84a1-93bab4dd5def.png)

On MyFaces it´s still the empty list one request-cycle later.
![image](https://user-images.githubusercontent.com/10461942/113044060-8c9e2700-919d-11eb-91d2-b14303065574.png)

@tandraschko , @arjantijms, @BalusC - any ideas on this implementation-difference.

**Comment by christophs78** [comment]
Think i figured it out:
https://github.com/eclipse-ee4j/mojarra/blob/2.3.14-RELEASE/impl/src/main/java/javax/faces/component/UIComponentBase.java#L1337
Empty lists get discarded during UIComponentBase#saveAttachedState. (Only lists which contain at least one entry are saved.)

**Comment by melloware** [comment]
Wonder if this line...

```java
List<StateHolderSaver> resultList = null;
```

Should be ...
```java
List<StateHolderSaver> resultList = new ArrayList<>();
```

or
```java
List<StateHolderSaver> resultList = Collections.emptyList();
```

But I think the 2nd one makes it n unmodifiable list.

**Comment by christophs78** [comment]
MyFaces does not check (indirect) for empty list´s and discards them
https://github.com/apache/myfaces/blob/myfaces-core-module-2.3.8/api/src/main/java/javax/faces/component/_DeltaStateHelper.java#L700

**Comment by christophs78** [comment]
> ```java
> List<StateHolderSaver> resultList = new ArrayList<>();
> ```

Yeah. resultList should be initialized independent of having items within the list. At least from this perspective and to align it with MyFaces. 
But why has Mojarra this pretty complicated code? Trying to optimize things?

**Comment by christophs78** [comment]
This part of Mojarra-code did not change over the last 10 years. Even 2.0.4 is like today https://github.com/javaee/mojarra/blob/2.0.4/jsf-api/src/main/java/javax/faces/component/UIComponentBase.java#L1542. 
I´ll do a Mojarra-PR to change this. Maybe tomorrow.

**Comment by christophs78** [comment]
https://github.com/eclipse-ee4j/mojarra/releases/tag/2.3.15 is available
