### ISSUE TITLE
DataTable: Using an inputtextarea in a celleditor - no line break / no new line possible

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#7028]
**Describe the defect**
It is not possible to enter multiple lines into an inputtextarea within a celleditor, because every keypress on ENTER will close the input-mode and submits the form.

**Reproducer**
Run attached clone of https://github.com/primefaces/primefaces-test.git with following command:

mvn clean jetty:run -Pmojarra23

**Environment:**
 - PF Version: 10.0
 - JSF + version:  Mojarra 2.3
 - Affected browsers: ALL

**To Reproduce**
1. Run with 'mvn clean jetty:run -Pmojarra23''
2. Enter 'http://localhost:8080/primefaces-test/' in browser
2. Click on the pencil in a row
3. Enter text and hit ENTER in column 'Name'
4. input-mode is closed and form is submitted

**Expected behavior**
Hitting ENTER in the inputtextare should result in a line break

**Example XHTML**
see test.xthml in attached archive

**Example Bean**
see EditView.java in attached archive

[my-primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/6022598/my-primefaces-test-master.zip)

**Comment by melloware** [comment]
I think I know how to fix this.  Thanks for the reproducer!

**Comment by stolp** [comment]
@melloware: You might want to have a look at https://forum.primefaces.org/viewtopic.php?f=3&t=59362

**Comment by rho66** [comment]
@stolp: this does not worked for me

**Comment by melloware** [comment]
It was broken in both row editing and cell editing. That post was only trying to fix cell editing.  I have fixed both scenarios with my PR.

**Comment by rho66** [comment]
@melloware Thank you, for the quick fix! I'll try to apply this to PF 8.0 also!

**Comment by rho66** [comment]
Got it also running with PF 8.0 ;-)

**Comment by melloware** [comment]
Nice work @rho66 !
