### ISSUE TITLE
Slider: Manual input number via AZERTY SHIFT does not work

### ISSUE THREAD

**Issue by rcroonenberghs** [primefaces/primefaces#7032]
**Describe the defect**
When using an AZERTY lay out keyboard it is necessary to press < SHIFT > + a number to enter a number. When doing this in regular inputfields this works. But when doing this in an inputfield related to a slider, it does nothing. The entry is not catched. When entering numbers via the numeric pad it works. When using a QWERTY lay out, you don't need the shift key and that also works.

**Reproducer**
Go to the showcase and try entering a number via the shift key 
https://www.primefaces.org/showcase/ui/input/slider.xhtml?jfwid=2a18e

**Environment:**
 - PF Version: 10 and 8.0 and also 6.2.12
 - Affected browsers: Firefox Chrome Edge

**To Reproduce**
1. Go to https://www.primefaces.org/showcase/ui/input/slider.xhtml?jfwid=2a18e
2. Click on the inputfield of the basic slider
3. type SHIFT + 1  
4. It does nothing
5. type 1 via the numeric pad and 1 is entered in the field

**Expected behavior**
Entry of a number should be possible via the shift key

**Comment by melloware** [comment]
In slider.js this is done on purpose right now with this block
```javascript
 //prevent special characters with alt and shift
 if(e.altKey || (e.shiftKey && !(key === keyCode.UP || key === keyCode.DOWN || key === keyCode.LEFT || key === keyCode.RIGHT))) {
        e.preventDefault();
 }
```

**Comment by melloware** [comment]
Because on a normal keyboard QWERTY SHIFT+1 is actually `!` and we don't want special characters added into the input only numbers and decimal and comma.

**Comment by melloware** [comment]
Here is the whole block if you want to investigate how we can fix it on both QWERTY and AZERTY.
```javascript
var metaKey = e.metaKey || e.ctrlKey,
    isNumber = (key >= 48 && key <= 57) || (key >= 96 && key <= 105) || (key === 190);

//prevent special characters with alt and shift
if (e.altKey || (e.shiftKey && !(key === keyCode.UP || key === keyCode.DOWN || key === keyCode.LEFT || key === keyCode.RIGHT))) {
    e.preventDefault();
}

//prevent letters and allow letters with meta key such as ctrl+c
//also allow '.' when the step is defined as decimal
// #6319 if number allow negative sign
if (!isNumber && !metaKey &&
    !($this.cfg.min < 0 && key === 189) &&
    !($this.decimalStep && key === 190)) {
    e.preventDefault();
}
```

**Comment by stevendegroote** [comment]
Needless to say, the code is pretty bad, as a whole lot of special chars can be typed into that field with an Azerty keyboard (including @ , # , & etc)

Might I suggest to checkout the below logic, like I do in several places to enforce numeric-only input?

    $('.some-integer-field-class').on('keypress', function (e) {
    	if (e.which < 32) return true; // Control chars (charcode)
        if (decimalsep == ',' && String.fromCharCode(e.which).match(/[^0-9\.-]/g)) return false;
        if (decimalsep == '.' && String.fromCharCode(e.which).match(/[^0-9,-]/g)) return false;
        return true;
    });


This uses the resulting key character, and not the actual key pressed on the keyboard (which obviously has a different outcome with different keyboard layouts)
More info here: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event

**Comment by melloware** [comment]
I agree the current code is bad.  Yours looks much better but i noticed you are using "keypress" which is not supported in Android. Did you mean keydown?

**Comment by melloware** [comment]
Also yours doesn't handle #6319 `Allow enter of "-" in associated input if minValue is less then 0`

**Comment by stevendegroote** [comment]
The minus is supported. Please check the regex carefully ;)
But those are details, I've just given an example.

I confirm I'm using keypress, which I see is not favoured anymore. But perhaps the regex logic can be used via keydown or keyup too.

**Comment by stevendegroote** [comment]
Also, according to MDN, keypress is (still) supported on all listed browsers on Android.

**Comment by melloware** [comment]
OK so yeah the reason this is so complex is there are some use cases you are missing.
1. #6319 Only allow Negative sign if the slider setting `minValue < 0` basically don't allow a negative if the slider is expected to only be positive.  Yours does not handle that and allows negative always.
2. #5579: Does yours prevent someone from entering two decimals like "55.66.77"? Or two negative signs "--100" ?
3. Does your allow CTRL+C and CTRL+V for pasting?

As for keypress see: https://stackoverflow.com/questions/22473950/keypress-event-not-firing-in-android-mobile

**Comment by melloware** [comment]
Actually it even looks like the current version allows multiple "." its only prevented in Spinner.

**Comment by stevendegroote** [comment]
Ok so considering keypress is no longer recommended according to MDN, then use input:

    $('.int-input').on('input', function(e) {
      var start = this.selectionStart,
        end = this.selectionEnd;
      $(this).val($(this).val().replace(/[^0-9\.-]/g, ''));
      this.setSelectionRange(start, end);
    });

I put this together in 5mins, so only tested on Azerty ;)
And yes, Ctrl+C and Ctrl+V are supported for both the keypess and input variants.

Here's a testable example (and please, again, it's an EXAMPLE. The function's body can be extended):
https://jsfiddle.net/stevendegrote/2mLqaurv/1/

**Comment by melloware** [comment]
I am working on something from your example that handles all the scenarios (I hope).

**Comment by melloware** [comment]
Can you guys try this one on AZERTY?  It works for QWERTY and I am trying to remain using `keydown`. 
It also...
- prevents duplicate negative sign
- prevents duplicate decimal separator
- only allow negative sign if min < 0

https://jsfiddle.net/Lbrkp6c5/

**Comment by rcroonenberghs** [comment]
This does not work. I can enter with shift, but I can't with the numeric pad anymore. And I can enter non numeric character like "'(§
![image](https://user-images.githubusercontent.com/8414821/109038398-f96c6000-76cb-11eb-8f1c-0dd2e59055f8.png)

**Comment by melloware** [comment]
@rcroonenberghs can you try this version: https://jsfiddle.net/Lbrkp6c5/1/

**Comment by rcroonenberghs** [comment]
This seems to be working. 
Only thing I can't put in is a comma. Depending on locale, a comma can be used as decimal point. Not sure on how to support that and if that is necessary.

**Comment by melloware** [comment]
Yep in that fiddle just change the following and click Run:
```
var decimalsep = ',';
var minValue = 0;
```

Now you should be able to enter comma not dot and not allowed to enter a negative sign.

**Comment by stevendegroote** [comment]
Works fine. I tested with the comma as decimal separator, and that works too.
Tested on PC in firefox and brave.

Side note: don't we need to allow thousand separators? Or was that not supported before either?

**Comment by melloware** [comment]
i don't think that was supported before only a decimal sep.  Since the slider only cares about a real number?  Ok I will submit this as a PR.  Thanks for reporting and testing everyone!
If you need this right now just add this to your project..

```javascript
if (PrimeFaces.widget.Slider) {

    PrimeFaces.widget.Slider.prototype.bindEvents = function() {
        var $this = this;

        this.jq.on('slide', function(event, ui) {
            $this.onSlide(event, ui);
        });

        if (this.cfg.onSlideStart) {
            this.jq.on('slidestart', function(event, ui) {
                $this.cfg.onSlideStart.call(this, event, ui);
            });
        }

        this.jq.on('slidestop', function(event, ui) {
            $this.onSlideEnd(event, ui);
        });

        if (this.input.parent().hasClass('ui-inputnumber')) {
            this.input.parent().find('input:hidden').off('change.slider').on('change.slider', function() {
                $this.setValue($(this).val());
            });
        } else {
            this.input.on('keydown.slider', function(e) {
                var keyCode = $.ui.keyCode,
                    key = e.which;

                switch (key) {
                    case keyCode.UP:
                    case keyCode.DOWN:
                    case keyCode.LEFT:
                    case keyCode.RIGHT:
                    case keyCode.BACKSPACE:
                    case keyCode.DELETE:
                    case keyCode.END:
                    case keyCode.HOME:
                    case keyCode.TAB:
                        break;

                    default:
                        if (key < 32) return true; // Control chars (charcode)
                        var character = e.key;
                        var current = $(this).val();

                        // don't allow duplicate decimal separators
                        var separatorRegex = '';
                        if ($this.decimalStep) {
                            if (character === ',') {
                                if (current.indexOf(',') !== -1) {
                                    return false;
                                } else {
                                    separatorRegex = ',';
                                }
                            }
                            if (character === '.') {
                                if (current.indexOf('.') !== -1) {
                                    return false;
                                } else {
                                    separatorRegex = '\\.';
                                }
                            }
                        }

                        // #6319 only allow negative once and if min < 0
                        var negativeRegex = '';
                        if ($this.cfg.min < 0) {
                            if (character === '-' && current.indexOf('-') !== -1) return false;
                            negativeRegex = '-';
                        }
                        var regex = new RegExp('[^0-9' + separatorRegex + negativeRegex + ']', 'g');
                        return !character.match(regex);
                }
            }).on('keyup.slider', function(e) {
                $this.setValue($this.input.val());
            });
        }
    }
};
```

**Comment by melloware** [comment]
Hang on need to fix that script. decimalStep is just a boolean `this.decimalStep = !(this.cfg.step % 1 === 0);`

**Comment by melloware** [comment]
OK I updated the script above.  Unfortunatey right now '.' is the only decimal character that will work as ',' is not respected as a decimal character and would take some rework of this component etc.  But for not it solves this AZERTY issue.

**Comment by melloware** [comment]
Also this website is amazing for debugging JavaScript key event issues: https://w3c.github.io/uievents/tools/key-event-viewer.html
