### ISSUE TITLE
TreeTable: "setPartialSelected=true", TreeNode checkbox does not change

### ISSUE THREAD

**Issue by FernandoGiovanellaDias** [primefaces/primefaces#7036]
**Describe the defect**

In a "TreeNode" of an <p: treeTable> attribute, the "setPartialSelected (true)" does not change the checkBox to partially selected.

**Environment:**
 - PF Version: _8.0_
 - java version "1.8.0_211"
 - Affected browsers:  Chrome

**To Reproduce**

1 - to create a TreeTable, use a List< Deck>
2 - for each item in this list, I create a TreeNode with the root Node and the object of type Deck;
3 - add the TreeNode inside a "HashMap <Deck, TreeNode> map";
4 - if this deck is in the database deck list it defines: "node.setSelected (true);" and calls the "test" method by passing the [deck containing it] as a parameter;
5 - within the "test" method, I search for the TreeNode using the "TreeNode node = map.get (baralho.getBaralhoPai ());" and if he doesn't have "node.isSelected ()" he should set "setPartialSelected" to true, that way

```
private void carregarArvore(Baralho baralhoPai, TreeNode nodePai) {
        List<Baralho> baralhosFilhos = baralhos.baralhosPorColecao(utilService.colecaoUsuarioLogado(), baralhoPai);
        if (baralhosFilhos != null && baralhosFilhos.size() > 0) {
            for (Baralho baralhoFilho : baralhosFilhos) {
                TreeNode node = new DefaultTreeNode(baralhoFilho, nodePai);
                map.put(baralhoFilho, node);
                carregarArvore(baralhoFilho, node);
                if (verificarSelecao(baralhoFilho)) {
                    node.setSelected(true);
                    listaTreeNode.add(node);
                    teste(baralhoFilho);
                }
            }
        }
    }
```

```
    private void teste(Baralho baralho) {
        if (baralho.getBaralhoPai() != null) {
            TreeNode node = map.get(baralho.getBaralhoPai());
            Baralho baralhoPai = (Baralho) node.getData();
            if (node.isSelected()) {
                teste(baralhoPai);
            }
            if (!node.isSelected()) {
                node.setPartialSelected(true);
                teste(baralhoPai);
            }
        }
    }
```

**Expected behavior**
The TreeTable checkbox should be partially selected:
-Image link: https://ibb.co/z4pH7RP

**Reality**
The TreeTable checkbox is not changed
-Image link: https://ibb.co/QbsQR7w

**Comment by tandraschko** [comment]
Please provide a small reproducer (bean + xhtml) or fork primefaces-test.

Also a PR would be great

**Comment by melloware** [comment]
Closing without a reproducer and no response from OP.  If a reproducer is provided will re-open this ticket.
