### ISSUE TITLE
DataTable: Slow header loading in reflow mode

### ISSUE THREAD

**Issue by leosj29** [primefaces/primefaces#7038]
**Describe the defect**
In a "Datatable" with the attribute reflow = "true" and in Responsive mode, the column headers are displayed lag behind the content.

**Reproducer**
Go to Showcase http://primefaces.org/showcase/ui/data/datatable/responsive.xhtml.

**Environment:**
- PF Version: 8 and 10.0
- java version "1.8.0_265"
- Affected browsers: All

**Example**

![prime](https://user-images.githubusercontent.com/2030440/109205531-5881b180-776c-11eb-89c8-8582a6f4343c.gif)

**Comment by melloware** [comment]
I am not having that issue. Could it be that Chrome is trying to bring up the "Ingles v Espanol" translate bar?

**Comment by melloware** [comment]
Does the same happen in Firefox or Edge or any other browser?

**Comment by leosj29** [comment]
> Does the same happen in Firefox or Edge or any other browser?

Yes, in firefox too.

**Comment by leosj29** [comment]
> Does the same happen in Firefox or Edge or any other browser?

**Comment by leosj29** [comment]
> I am not having that issue. Could it be that Chrome is trying to bring up the "Ingles v Espanol" translate bar?

The translator appears because I use my mobile. But in Chrome and Firefox on desktop in responsive mode it also happens.

**Comment by tandraschko** [comment]
Maybe to wide Ajax Update in the Showcase?

**Comment by melloware** [comment]
Hmmm I don't see any AJAX happening during this while I am resizing back and forth.  Very strange I am on my desktop only and it doesn't happen for me.

**Comment by leosj29** [comment]
> Hmmm, no veo ningún AJAX sucediendo durante esto mientras estoy cambiando el tamaño de un lado a otro. Muy extraño, estoy solo en mi escritorio y no me pasa.

It only happens when the responsive mode is entered directly, if the datatable is resized this does not happen

**Comment by melloware** [comment]
OK that helps.  let me try that.

**Comment by melloware** [comment]
OK so its not AJAX but it is JS code.  The table loads and renders then the JS code to make it responsive then fires that is why you see this delay.  The DOM loads then the Datatable JS code then proceeds to make it responsive..

I have a workaround for you if this is definitely bothering you.  Try this: https://stackoverflow.com/questions/9550760/hide-page-until-everything-is-loaded-advanced/28129691#28129691
