### ISSUE TITLE
Cropper not work in chrome mobile

### ISSUE THREAD

**Issue by julio0345** [primefaces/primefaces#704]
Hello guys
I'm brazilian, then my english is very bad. i'm sorry.
I found a problem. The component Cropper used in Chrome Android (mobile) do not work. Anybody already looked this?
I Think the component not accept lose the focus of image, then, nothing other component work.
Help-me please
Thanks

**Comment by julio0345** [comment]
Anybody?

**Comment by tandraschko** [comment]
Duplicate of: https://github.com/primefaces/primefaces/issues/1243
