### ISSUE TITLE
SelectOneMenu: empty value breaks layout

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7044]
Whenever the item value of a p:selectOneMenu is empty, layout of the menu changes (shrinks). Example:

```
          <p:selectOneMenu value="#{user.title}">
            <f:selectItem itemLabel="" />
            <f:selectItem itemValue="Dr." itemLabel="Dr." />
            <f:selectItem itemValue="Prof. Dr." itemLabel="Prof. Dr." />
          </p:selectOneMenu>

          <p:selectOneMenu value="#{user.salutation}">
            <f:selectItem itemLabel="#{messages.select}" itemDisabled="true" noSelectionOption="true" />
            <f:selectItem itemValue="Mr" itemLabel="Mr" />
            <f:selectItem itemValue="Ms" itemLabel="Ms" />
          </p:selectOneMenu>

```

![Screenshot from 2021-02-26 16-06-56](https://user-images.githubusercontent.com/10051373/109317132-acfc5e00-784c-11eb-87a5-e70a973beb80.png)

**Comment by tandraschko** [comment]
AFAIR this was already fixed 1-2 weeks ago @melloware ?

**Comment by melloware** [comment]
Mert fixed that in the CSS in the latest snapshot.

**Comment by melloware** [comment]
Make sure you CTRL+F5 in your browser after you build the latest SNAPSHOT.

**Comment by tuerker** [comment]
I did CTRL+F5 and i am running on the latest snapshot. Hope that this is not related to diamond template i am using?

**Comment by melloware** [comment]
Oh yep it is.  Mert fixed it in the themes.  SO it will be fixed when your diamond template is updated.

See: https://github.com/primefaces/primefaces/issues/6990

And the fix: https://github.com/primefaces/primefaces/commit/8616a113dcdfb61796ee6030f7e0773a6c3a0015

**Comment by tuerker** [comment]
@melloware after having created a reproducer for https://github.com/primefaces/primefaces/issues/7045, i have also created a reproducer for this one.

the problem is not due to diamond. it is simply still persistent.

see: 
[p-selectonemenu-2.zip](https://github.com/primefaces/primefaces/files/6050888/p-selectonemenu-2.zip)
