### ISSUE TITLE
SelectOneMenu: item value is not printed when there is no label

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7045]
p:selectOneMenu delivers empty label when itemLabel is not explicitly defined. Example:

```
        <p:selectOneMenu value="#{user.title}">
            <f:selectItem itemLabel="" />
            <f:selectItem itemValue="Dr." />
            <f:selectItem itemValue="Prof. Dr." />
          </p:selectOneMenu>
```

![Screenshot from 2021-02-26 16-12-49](https://user-images.githubusercontent.com/10051373/109318802-7a536500-784e-11eb-83a9-146cec02231d.png)

p:selectOneMenu in contrast just prints the item value in such a case:

```
        <h:selectOneMenu value="#{user.title}">
            <f:selectItem itemLabel="" />
            <f:selectItem itemValue="Dr." />
            <f:selectItem itemValue="Prof. Dr." />
          </h:selectOneMenu>
```

**Comment by melloware** [comment]
Please create a reproducer. I don't understand the issue.

**Comment by tuerker** [comment]
here is the reproducer: 

[p-selectonemenu.zip](https://github.com/primefaces/primefaces/files/6050810/p-selectonemenu.zip)
