### ISSUE TITLE
DataTable: integration-tests fail since today

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7048]
Our integration-tests fails since today due to
`DataTable009Test.testFilterIssue1390:54 expected: <Java,JavaScript> but was: <null>`
see https://github.com/primefaces-extensions/primefaces-integration-tests/runs/1987979513?check_suite_focus=true

Maybe it´s caused by https://github.com/primefaces/primefaces/commit/89972adc0ce27294ec36bf454b153005cc2b753e

@Rapster

**Comment by melloware** [comment]
Yep I reported it to him.

**Comment by christophs78** [comment]
(Outdated) https://github.com/primefaces-extensions/primefaces-integration-tests/pull/123

**Comment by christophs78** [comment]
https://github.com/primefaces-extensions/primefaces-integration-tests/pull/124

**Comment by melloware** [comment]
Integration tests passing again!

**Comment by Rapster** [comment]
So I don't get it, what's the expected behavior about the filter event order?

**Comment by christophs78** [comment]
The ideal solution would be to events. The existing "filter" - event which fires before filter and something like "afterFilter", "postFilter" (or whatever fit´s into our naming-conventions which) fires after filtering.

**Comment by tandraschko** [comment]
in general there is only one client-behavior: filter
this p:ajax events are normally "pre" events, so we introduced e.g. PostFilterEvent 

i think this is quite good

**Comment by Rapster** [comment]
Ok but PostFilterEvent is no client behavior, subscribing to this event shouldn't be any different than filter

**Comment by tandraschko** [comment]
yeah but it will
p:ajax is designed for client events, event handling on the server side is actually provided by f:event / #subscribeToEvent
