### ISSUE TITLE
DataTable: cellEditInit event not triggered for the first row

### ISSUE THREAD

**Issue by felixoi** [primefaces/primefaces#7049]
**Describe the defect**
The cellEditInit event is not triggered for the first row in a datatable.

**Reproducer**
https://github.com/felixoi/primefaces-test/tree/report-3

**Environment:**
 - PF Version:  10.0.0-RC1
 - JSF + version: Mojarra 2.2.8 & MyFaces 2.3.6
 - Affected browsers: ALL

**To Reproduce**
1. Click on the first row to edit (no console output)
2. Click on all other rows (console output)

**Expected behavior**
The cellEditInit should be triggered for the first row also.

**Comment by tandraschko** [comment]
@melloware would you like to check it?

**Comment by melloware** [comment]
Yep I will check this one.

**Comment by melloware** [comment]
thanks for the reproducer. It was a JS truthiness issue with row=0!
