### ISSUE TITLE
Display problems when using Carousel with lots of entries

### ISSUE THREAD

**Issue by scroach** [primefaces/primefaces#705]
I stumbled upon a display problem with the Carousel component when using it with lots of entries/pages.
In my case only 37 pages would show and afterwards everything just went blank.

After investigating the problem I found that the wrapper is set to a fixed width of 32.000px.
Here: [carousel.css](https://github.com/primefaces/primefaces/blob/40142487d155b8b5d085357ad51419936e90746b/src/main/resources/META-INF/resources/primefaces/carousel/carousel.css#L11)

I fixed this issue for my project by simply overriding the css with 100.000px width - but isn't there any better or elegant than using those fixed 32.000 pixels?

**Comment by melloware** [comment]
Since you can simply override the CSS the current default seems reasonable to me.  Ticket has been open for 4 years with no upvotes so closing issue.
