### ISSUE TITLE
Unify checkbox-radio state visuals

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#7052]
Sync the behaviors (e.g. focus, active, hover) of all checkbox - radio elements with the behaviors from other Prime libraries.

**Comment by tandraschko** [comment]
JFYI:
we talked and decided some years ago that there is not only 1 single state on a element and they are combinable (e.g. state-active + state-hover)
so we should not remove .ui-state-active e.g. on hover (https://github.com/primefaces/primefaces/issues/2510)

**Comment by tandraschko** [comment]
also https://github.com/primefaces/primefaces/issues/3257

**Comment by mertsincan** [comment]
Hi @tandraschko,

No, we'll remove ui-state-{hover|focus|active}.  The following events should only do the following operations without being affected by other ui-state-{hover|focus|active}.

|Jquery Events| Style Class |
| --- | ---|
focus | addClass('ui-state-focus')
blur | removeClass('ui-state-focus')
mouseenter | addClass('ui-state-hover')
mouseleave | removeClass('ui-state-hover')

These situations should not change depending on whether the element has a ui-state-highlight/active.

- [x] ColumnToggler
- [x] DataTable
- [x] SelectBooleanCheckbox
- [x] SelectCheckboxMenu
- [x] SelectManyMenu
- [x] SelectOneRadio
- [x] Picklist
- [x] Tree
- [x] Horizontal Tree
- [x] TreeTable
- [x] TriStateCheckbox

Note: After  PF10 has been released, improvements can be made to other components.
