### ISSUE TITLE
What about Maven release for 10.0.0-RC2?

### ISSUE THREAD

**Issue by astappiev** [primefaces/primefaces#7054]
This would simplify testing, at least for us :)

**Comment by melloware** [comment]
Its in Maven Central right now. https://repo.maven.apache.org/maven2/org/primefaces/primefaces/

**Comment by astappiev** [comment]
Pretty strange, because I can't download it via Maven, also https://mvnrepository.com/artifact/org.primefaces/primefaces shows only the RC1 build.

Ok, probably we just need to wait for a little

**Comment by melloware** [comment]
No need to wait. Those UI's like MVN repository sometimes take hours or days to display but you can use it right now.

https://repo.maven.apache.org/maven2/org/primefaces/primefaces/10.0.0-RC2/

I am already using it.

**Comment by astappiev** [comment]
Not really :(

> Cannot resolve org.primefaces:primefaces:10.0.0-RC2

**Comment by melloware** [comment]
workfing absolutely fine for me from 3 different machines.
```xml
<dependency>
  <groupId>org.primefaces</groupId>
  <artifactId>primefaces</artifactId>
  <version>10.0.0-RC2</version>
</dependency>
```

**Comment by melloware** [comment]
Also listed in Maven Search:
https://search.maven.org/artifact/org.primefaces/primefaces/10.0.0-RC2/jar

**Comment by astappiev** [comment]
Works on the server, indeed the problem with my system, sorry.

**Comment by melloware** [comment]
no worries
