### ISSUE TITLE
Primefaces editor fail in the copy/paste with the right click

### ISSUE THREAD

**Issue by camiloarcc** [primefaces/primefaces#706]
In the primafaces component, editor exists a problem with the copy/paste action but only fail with the right click function, the text show in the textarea but in the moment of process the text is not caught but the variable take a whitespace.

**Comment by cagataycivici** [comment]
Does it also happen at;

http://premiumsoftware.net/cleditor/

**Comment by camiloarcc** [comment]
YES, also happen in this editor, have the same problem

2015-09-21 6:45 GMT-05:00 Çağatay Çivici notifications@github.com:

**Comment by tandraschko** [comment]
p:editor uses cleditor under the hood which is not maintained since years. 
I would suggest to use PrimeFaces Extensions CKEditor or the new p:textEditor (which doesn't work on all browsers).
