### ISSUE TITLE
DataTable / Paginator: Custom content syntax not JSF spec compatible

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7060]
https://primefaces.github.io/primefaces/10_0_0/#/components/datagrid?id=custom-content-in-paginator

This works in Mojarra but not in MyFaces if you have a JSF component inside this custom facet:

```
                <f:facet name="{Exporters}">
                    <p:commandLink id="test" />
                </f:facet>
```

In Mojarra, the generated clientId of the commandLink will be: form:datatable:test
In MyFaces, generated clientId is: form:datatable:__f_{Exporters}:test

And { } is invalide inside a id.

Not sure which is by design, we have to check this.

**Comment by tandraschko** [comment]
it seems that Mojarra doesnt add a special id to it, MyFaces does
not sure whats more aligned to specs

not sure whats the best way to fix it

**Comment by tandraschko** [comment]
see: https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4381

**Comment by willbigas** [comment]
@tandraschko Do you expect to release the version with the correction? 2.3.9 I think

**Comment by tandraschko** [comment]
Yeah but not this or next month, we already did a release train in february
You might use Apache snapshot repo: https://repository.apache.org/content/groups/snapshots/org/apache/myfaces/core/myfaces-impl/2.3.9-SNAPSHOT/

**Comment by tandraschko** [comment]
It would be great If you can test

**Comment by tandraschko** [comment]
MyFaces 2.3.9 released
