### ISSUE TITLE
MenuItem: allow ui-state-active on menu item

### ISSUE THREAD

**Issue by wklaczynski** [primefaces/primefaces#7066]
**It is not possible to light the menu when the selection is active**

This would allow the programmer to set a different appearance for a menu item when the target associated with that item is active. 

This could be an "active" parameter, which when set to "true" adds the "ui-state-active" style displayed according to the selected "theme". 

```xml
<p:menuitem 
  active="true"
....
```

from model
```java
...
DefaultMenuItem menuitem = ...;
menuitem.setActive(true);
....
```

**Comment by tandraschko** [comment]
why not just add ui-state-active styleclass?

**Comment by wklaczynski** [comment]
Of course, the style could be attributed: 
```java
menuitem.setContainerStyleClass(Objects.equals(menuitem.getId(), selectedId) ? "ui-state-active" : null);
```

Unfortunately, such a style does not exist in theme.css. You can add yourself in css, but then choosing a different theme would not update it, it would not look like the theme. But you could add a style like that like "p: tabMenu", for "p: menu", etc ... 

Css examle:
```script
body .ui-menu .ui-menu-list .ui-menuitem.ui-state-active {
    background: #ffffff;
    border-color: #2196F3;
}

body .ui-menu .ui-menu-list .ui-menuitem.ui-state-active a {
    color: #2196F3;
}

body .ui-menu .ui-menu-list .ui-menuitem.ui-state-active a .ui-icon {
    color: #2196F3;
}
```

**Comment by wklaczynski** [comment]
Actually, the "ui-state-active" style in theme.css can be treated as the style that applies to most components. Do not limit it to a selector of selected components. Because similar problems are in p: tree, etc ... Practically even like "p: label", etc ... developer will set styleClass to "ui-state-active", should deselect according to theme. But the "active" parameter in some would speed up programming, although it is not necessary. In most cases it is enough for the "ui-state-active" style to fulfill its function in all components.

**Comment by tandraschko** [comment]
i will set it as theme issue, to allow ui-state-* on menu-items
i dont think we should add a java-wrapper-method for this.

**Comment by melloware** [comment]
I agree adding a new option doesn't make sense when its just a style change.

**Comment by buunsal** [comment]
We do not add styles that are not actively used in our components. Theme files would grow excessively if we decided to add a style for the sake of one user. Unlike you, most people don't want that. So you can add it manually.

> i dont think we should add a java-wrapper-method for this.

I'm closing because @tandraschko said that. If there is a different request, open a new issue.
