### ISSUE TITLE
jQuery: Upgrade to 3.6.0

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7068]
**Description**
3.6.0 Released...
https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/

**Comment by pizzi80** [comment]
I'm testing with PF 8 / JSF 2.2 with no problem at all ... going in production right now ... why not target PF 10 ?

You could easily replace jquery for testing with Omnifaces CDN 
```xml
<context-param>
    <param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS</param-name>
    <param-value>
        primefaces:jquery/jquery.js=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
    </param-value>
  </context-param>
```

**Comment by melloware** [comment]
PrimeTek is trying to minimize chnages for 10.0.0 final release.  Plus there is no security impact to this release so I thought it was safer to wait.  If it fixed a security CVE I would absolutely push for it.

**Comment by pizzi80** [comment]
ok! thanks for the reply! ;)

**Comment by vonnai** [comment]
there is a bug in jquery 3.5.1, the code $(selector).css('max-height', '100') does nothing, it works only if the value is a number or string with px. So dialog feature fitVieport in Primefaces 10.0.0 doesn't work (file: dialog.js, function fitViewport). It works well with jquery 3.6.0. When do you suppose the Primefaces 10.0.1 will be released? Should I create a new issue for this bug? Thanks

**Comment by melloware** [comment]
@vonna yes create a new issue.  The right fix is to make it `$(selector).css('max-height', '100%')` pr 'px' but PX doesn't make sense I assume they wanted 100% max height?

**Comment by vonnai** [comment]
@melloware the code $(selector).css('max-height','100') does nothing in jquery 3.5.1, it means there is not any max-height property set to element's style attribute. Expected property in style attribute should be `max-height:100px`. You are using this not working construction in dialog.js function fitViewport (PF 10.0.0). My question is: are you going to upgrade jquery in 10.0.1? or should I create issue for fixing fitviewport function ?

**Comment by vonnai** [comment]
new issue is #7139.
