### ISSUE TITLE
TreeTable: Global Filter is not working

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#7071]
**Describe the defect**
Global filter in TreeTable is not working  in PF10.0.0-RC2  (only column filters is working).
The same was happening before with <p:datatable/> was already fixed  and related to   #6968  #6953  

**Environment:**
PF Version: 10.0.0-RC2
JSF + version: JSF 2.2.19 

**To Reproduce**
1. Include  global filter in a TreeTable component
2. Try to filter, 
3. It should work as  it works per column.

**Example XHTML**
```
 <p:treeTable value="#{relatorioBean.root}"  widgetVar="customersTable"		  ... >
      <f:facet name="header" > 
              <h:inputText id="globalFilter" onkeyup="PF('customersTable').filter()"  />  
        </f:facet>
          ...
  </p:treeTable>
```

**Comment by tandraschko** [comment]
@Rapster please review
i think we still have a broken "globalFilter" attribute
AFAICS it should set the default value of the "globalFilter" input component
but its called each request, not only in the initial GET
or do i miss something?
