### ISSUE TITLE
ClassCastException with DefaultMenuItem in MenuModel when set an id programmatically

### ISSUE THREAD

**Issue by Baegger92** [primefaces/primefaces#7072]
Describe the defect
When setting MenuModel for a menubar programmatically and giving an id to an DefaultMenuItem, their is an ClassCastException on clicking the menu items.

Environment:
PF Version: 10.0.0-RC 1+2

Example working:
```xml
            <p:menubar>
                <p:menuitem value="Default Item" id="default" />
                <p:submenu label="Submenu">
                    <p:menuitem value="Submenu Default Item" />
                </p:submenu>
            </p:menubar>
```

Example not working:
```xml
                <p:menubar model="#{controller.menu}" />
```

```java
	public MenuModel getMenu() {
		final DefaultMenuModel menu = new DefaultMenuModel();

		menu.getElements().add(DefaultMenuItem.builder().value("Default Item").id("default").build());
		final DefaultMenuItem submenu_item = DefaultMenuItem.builder().value("Submenu Default Item").build();
		menu.getElements().add(DefaultSubMenu.builder().label("Submenu").elements(ImmutableList.of(submenu_item)).build());
		menu.generateUniqueIds();
		return menu;
}
```

Exception:
SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-3) java.lang.ClassCastException: org.primefaces.model.menu.DefaultMenuItem cannot be cast to org.primefaces.model.menu.MenuGroup at org.primefaces.renderkit.MenuItemAwareRenderer.findMenuitem(MenuItemAwareRenderer.java:192)

In Primefaces 8, both ways are working.

**Comment by tandraschko** [comment]
@melloware something for you?

**Comment by melloware** [comment]
Yep looking at this now.

**Comment by melloware** [comment]
I am getting a different error:
```
Mar 05, 2021 7:42:47 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.NumberFormatException: For input string: "default"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.primefaces.renderkit.MenuItemAwareRenderer.findMenuitem(MenuItemAwareRenderer.java:180)
        at org.primefaces.renderkit.MenuItemAwareRenderer.decodeDynamicMenuItem(MenuItemAwareRenderer.java:210)
        at org.primefaces.renderkit.MenuItemAwareRenderer.decode(MenuItemAwareRenderer.java:57)

```

**Comment by stolp** [comment]
I saw a similar error once I did a setId() on the menu item. I think you are not allow to change it.

**Comment by melloware** [comment]
Its related to this fix..

https://github.com/primefaces/primefaces/issues/1039

https://github.com/primefaces/primefaces/issues/6367

https://github.com/primefaces/primefaces/issues/6647

**Comment by Baegger92** [comment]
> 
> 
> I am getting a different error:
> 
> ```
> Mar 05, 2021 7:42:47 AM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
> SEVERE: java.lang.NumberFormatException: For input string: "default"
>         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
>         at java.base/java.lang.Integer.parseInt(Integer.java:652)
>         at java.base/java.lang.Integer.parseInt(Integer.java:770)
>         at org.primefaces.renderkit.MenuItemAwareRenderer.findMenuitem(MenuItemAwareRenderer.java:180)
>         at org.primefaces.renderkit.MenuItemAwareRenderer.decodeDynamicMenuItem(MenuItemAwareRenderer.java:210)
>         at org.primefaces.renderkit.MenuItemAwareRenderer.decode(MenuItemAwareRenderer.java:57)
> ```

Ok crazy, i tried it again with my posted example on RC-2 and got the ClassCastException again...

**Comment by Baegger92** [comment]
Now found it out. If you clicked on the MenuItem with the id, you got a NumberFormatException. Clicking in the Submenu on the other MenuItem (Submenu Default Item), you get the ClassCastException.

**Comment by melloware** [comment]
Here is my runnable reproducer:
[pf-7072.zip](https://github.com/primefaces/primefaces/files/6090714/pf-7072.zip)

You can run with `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

Can you tweak my example so I get your ClassCastException.    So then I can test my fix.

**Comment by melloware** [comment]
OK I am not sure HOW this working in 8.0 other than it ignored your ID "default".  Because MenuBar all menu's get coordinates like "0_0" or "1_2" where the first number is the Submenu and the 2nd number is the menu item under that submenu.  Yours is failing because now it says "default" which can't find the coordinates of the menu item.

I suggest removing the ID and letting the MenuBar generate its coordinates properly.

**Comment by Baegger92** [comment]
Correct. That solved it. Wasn't clear to me, that i shouldn't use that in combination and it was only luck that it worked for me in PF 8.

**Comment by melloware** [comment]
Yep the new part for setting ID's in menu items is for other types of menus.  @tandraschko I wonder if we should defend against this in MenuBar and throw a better FacesException?
