### ISSUE TITLE
Overlays: On mobile not working

### ISSUE THREAD

**Issue by cadubad** [primefaces/primefaces#7075]
I'm using a Samsung Galaxy S10, and when a click at https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml -> Advanced, the select items list closes unexpectedly.

**Comment by melloware** [comment]
I only have an iPhone to test on and it works fine. Sorry I don't have an Android to test with!

**Comment by cadubad** [comment]
It happened at the showcase with Android.

In my application it happens with Android and Iphone too

I put the bug on YT so you can check

https://www.youtube.com/watch?v=LAgHPXt3ALU

this started to happen after the upgrade of Prime 8 to 10

**Comment by melloware** [comment]
Weirs its not happening on my iPhone.  Its like the keyboard on your Android display causes the menu to close.

**Comment by cadubad** [comment]
I have a video of a user of my app that shows the problem on the iphone. Would it help if I made it available on YT?

I had to remove the filter = "true" for the selectonemenu to work again

**Comment by melloware** [comment]
you can cause no matter what I do it works fine on my iPhone.

**Comment by cadubad** [comment]
https://www.youtube.com/watch?v=XNfSHndAo-o

**Comment by melloware** [comment]
OK not happening on mine.  Could be an issue with the theme you are using or custom CSS.  Can you tester do the same test with his iPhone on the PF Showcase?

**Comment by cadubad** [comment]
I did the following tests.

My App:
Galaxy S10 - It didn't work.
Galaxy S20 - It didn't work.
Iphone (Video 2) - It didn't work.

PF Showcase:
Galaxy S10 (Video 1) - It didn't work.
Galaxy S20 - It didn't work.
Iphone - It worked.

**Comment by christophs78** [comment]
I can reproduce this issue with https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml on my Huawei P30 with up2date Chrome.
Maybe (not sure) it´s related to the switch from jQuery animations to CSS-animations.

**Comment by fanste** [comment]
Isn't there some kind if `close overlays on scroll`?` Maybe the appearance of the keyboard triggers the scroll event as the visible keyboard changes the viewport-height of the browser.

it only happens if the menu has a filter input which is automatically focused (according to video).

I think it is either
https://github.com/primefaces/primefaces/blob/fb751e12bdf8931fb8a0f23b5d4c32de57a71972/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L368
or
https://github.com/primefaces/primefaces/blob/fb751e12bdf8931fb8a0f23b5d4c32de57a71972/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L373

I can't do any tests as I do not have access using my Android to any application server with an PF based application that I can change.

**Comment by melloware** [comment]
Yes if the browser fires a `scroll` event or a `resize` event the overlay is hidden. See: https://github.com/primefaces/primefaces/issues/6583

**Comment by melloware** [comment]
@cadubad or anyone else can you try this MonkeyPatch by adding this JS to your app and testing again and see if the mobile browser works?
```javascript
if (PrimeFaces.widget.SelectOneMenu) {
    PrimeFaces.widget.SelectOneMenu.prototype.bindPanelEvents = function() {
        var $this = this;

        this.hideOverlayHandler = PrimeFaces.utils.registerHideOverlayHandler(this, 'mousedown.' + this.id + '_hide', this.panel,
            function() {
                return $this.label.add($this.menuIcon);
            },
            function(e, eventTarget) {
                if (!($this.panel.is(eventTarget) || $this.panel.has(eventTarget).length > 0)) {
                    $this.hide();
                    setTimeout(function() {
                        $this.revert();
                        $this.changeAriaValue($this.getActiveItem());
                    }, 2);
                }
            });

        this.resizeHandler = PrimeFaces.utils.registerResizeHandler(this, 'resize.' + this.id + '_hide', this.panel, function() {
            if (PrimeFaces.env.mobile) {
                $this.alignPanel();
            } else {
                $this.hide();
            }
        });

        this.scrollHandler = PrimeFaces.utils.registerConnectedOverlayScrollHandler(this, 'scroll.' + this.id + '_hide', this.jq, function() {
            if (PrimeFaces.env.mobile) {
                // GitHub #1173/#4609 keep panel with select while scrolling
                $this.alignPanel();
            } else {
                $this.hide();
            }
        });
    }
}
```

**Comment by cadubad** [comment]
Hi @melloware 

It seems to have solved it.

I encountered a similar problem. When I use OverlayPanel with some input inside it, it is closing on its own. Should I open another case?

https://www.youtube.com/watch?v=Pda6RL6sEo8

**Comment by melloware** [comment]
Hang on let me have you try another snippet here and if it works I will just update this ticket to be more inclusive.

**Comment by melloware** [comment]
Try this...
```javascript
if (PrimeFaces.widget.OverlayPanel) {
    PrimeFaces.widget.OverlayPanel.prototype.bindPanelEvents = function() {
        var $this = this;

        //hide overlay when mousedown is at outside of overlay
        if (this.cfg.dismissable && !this.cfg.modal) {
            this.hideOverlayHandler = PrimeFaces.utils.registerHideOverlayHandler(this, 'mousedown.' + this.id + '_hide', this.jq,
                function() {
                    return $this.target;
                },
                function(e, eventTarget) {
                    if (!($this.jq.is(eventTarget) || $this.jq.has(eventTarget).length > 0 || eventTarget.closest('.ui-input-overlay').length > 0)) {
                        $this.hide();
                    }
                });
        }

        this.resizeHandler = PrimeFaces.utils.registerResizeHandler(this, 'resize.' + this.id + '_hide', this.jq, function() {
            if (PrimeFaces.env.mobile) {
                $this.align($this.target);
            } else {
                $this.hide();
            }
        });

        this.scrollHandler = PrimeFaces.utils.registerConnectedOverlayScrollHandler(this, 'scroll.' + this.id + '_hide', this.target, function() {
            if (PrimeFaces.env.mobile) {
                $this.align($this.target);
            } else {
                $this.hide();
            }
        });
    }
}
```

**Comment by cadubad** [comment]
In the first test it didn't work.

so I changed the second line for this (based on your first code):

`PrimeFaces.widget.OverlayPanel.prototype.bindPanelEvents = function() {`

And it worked!

Thanks!

**Comment by melloware** [comment]
My bad was in a hurry.

**Comment by cadubad** [comment]
So far everything is working perfectly. Thanks for the quick feedback!

**Comment by gernansoares** [comment]
Even after I apply this monkey patch, datePicker is still closing automatically on mobile when trying to navigate months, is there any other option? Monkey patch really worked for SelectOneMenu, OverlayPanel and SelectCheckboxMenu, but not worked for datePicker

I tried using:

Galaxy S10
Galaxy S8
Galaxy A51

**Comment by melloware** [comment]
I didn't MonkeyPatch DatePicker which explains why this didn't fix it.  Give me a few minutes I will see if I can provide a patch to try.

**Comment by gernansoares** [comment]
> I didn't MonkeyPatch DatePicker which explains why this didn't fix it. Give me a few minutes I will see if I can provide a patch to try.

Yeah I know that, just thought it could be fixed by fixing the overlay, my mistake

**Comment by melloware** [comment]
Try this MonkeyPatch...
```javascript
if ($.prime.datePicker) {
    $.prime.datePicker.prototype.bindWindowResizeListener = function() {
        if (this.options.inline) {
            return;
        }

        var $this = this;
        $(window).on('resize.' + this.options.id, function() {
            if (PrimeFaces.env.mobile) {
                $this.alignPanel();
            } else {
                $this.hideOverlay();
            }
        });
    }
}
```

**Comment by gernansoares** [comment]
> Try this MonkeyPatch...
> 
> ```js
> if ($.prime.datePicker) {
>     $.prime.datePicker.prototype.bindWindowResizeListener = function() {
>         if (this.options.inline) {
>             return;
>         }
> 
>         var $this = this;
>         $(window).on('resize.' + this.options.id, function() {
>             if (PrimeFaces.env.mobile) {
>                 $this.alignPanel();
>             } else {
>                 $this.hideOverlay();
>             }
>         });
>     }
> }
> ```

Worked like a charm, thank you so much

**Comment by melloware** [comment]
no problem I updated my PR with this.

**Comment by melloware** [comment]
I made a small cut and paste issue on this which was fixed with: https://github.com/primefaces/primefaces/issues/7302
