### ISSUE TITLE
Frozen columns width

### ISSUE THREAD

**Issue by lgklein** [primefaces/primefaces#708]
When we use the datatable frozen columns, the table is automatically separated into width 50% to each side, a frozen and thawed other.
I believe that there should be a frozenColumnsKeepsWidth attribute where the default was false keeping the current behavior and when changed to true, he kept the original width of the columns and calculate the size of tables (frozen and thawed) based on that size.

**Comment by cagataycivici** [comment]
Use css to give different widths;

{code}

<style type="text/css">   
          .ui-datatable-frozenlayout-left {
              width:20%;
          }
          .ui-datatable-frozenlayout-right {
              width:80%;
          }
      </style>

{code}

Width of columns are effected by these two containers anyway so I don't think calculating original widths can't work as table-layout is fixed and so called original widths depend on these two containers.

**Comment by lgklein** [comment]
If you are considering ALWAYS that when using the freeze columns the table is already set up that way, your suggestion work...
But it can be used in dynamic colums...
Imagine a table with 1200px of width, generated by dynamic columns, where each column has a width calculated in back bean based on a result to be displayed in each column, may have from 1 to N columns where when the columns exceed the width 1200, that table use scroll. This table at first does not appear with frozen columns but has a button that can be clicked to freeze columns (Changes the bean property referring to the number of frozen columns from 0 to N, where N depends on the number of columns generated on the screen and does update in datatable).
In this case, the display is never equal to the form to set the css as you suggested.
I believe the Primefaces should be possible to use in applications and situations that are much more complex than the basic or anticipated as simpler...
