### ISSUE TITLE
DataTable: cellEdit no longer sets focus on InputText content

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7086]
**Describe the defect**
In PrimeFaces 8 clicking in a table cell will automatically activate/focus the input text, so the user can start typing immediately.

In PrimeFaces 10 this behavior has changed. The user needs to click in the input text component again to enter content.

For keyboard only usage this is even worse. Hitting tab from an inputText cell will activate the next cell, but the keyboard focus is not there. hitting tab again sets the focus and the user may enter content.

I think this is a regression. Same can be found for other components as well (SelectMenu for example).

**Reproducer**
This can be reproduced in the showcase.

**Environment:**
 - PF Version: _8.0_, _10.0-SNAPSHOT_
 - JSF + version: Mojarra 2.2.8
 - Affected browsers: _ALL_

**To Reproduce**
1. Click on a table cell in a table with editMode=cell
2. Click on the cell again to gain focus
3. Use Tab / Shift Tab to navigate
4. 
**Expected behavior**
Clicking on a table cell should set the focus on the contained input component.

**Comment by melloware** [comment]
OK its caused by this fix: https://github.com/primefaces/primefaces/issues/6187

**Comment by stolp** [comment]
Thanks. I will cross check this once it is merged.

**Comment by stolp** [comment]
I tested this with 10.0.0 Final but the behavior is still as described. Was this merged in 10.0.0?

**Comment by melloware** [comment]
Looks like it was merged but are you using the Showcase?  it has not been deployed yet so would still show the issue.  Looking in GitHub this was definitely in the 10.0.0 release.

**Comment by stolp** [comment]
No - I built our project with 10.0.0 and checked there.

**Comment by melloware** [comment]
Huh then maybe its a different issue. Can you create a reproducer?

**Comment by melloware** [comment]
when I use the PF showcase CellEdit example it seems to be working fine and focusing the cell.

**Comment by stolp** [comment]
I will see if i can find a reproducer.

**Comment by melloware** [comment]
OK latest showcase is deployed and when I go here: https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml?jfwid=3a9d8 when I click on  CellEdit example the Cell is being focused.

**Comment by stolp** [comment]
Thanks, I can confirm that the showcase seems fixed now. Still weird that this is not the same on my side. Will try to pin this down.

**Comment by stolp** [comment]
Ok found it. My code still contained the monkey patch in https://github.com/primefaces/primefaces/issues/6187

After removing it, everything worked as expected.

**Comment by melloware** [comment]
Excellent thanks for reporting back!
