### ISSUE TITLE
TreeTable: wrong column sizes  when scrollable="true" and dynamic columns

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#7090]
**Describe the defect**
When we have scrollable="true" with dynamic component generating columns in tree table, the column sizes are different from header to the body.    Maybe is related to #7070

Also, don't know why but this only works with **<c:forEach/>** component, when using the equivalent **<ui: repeat/>** nothing is displayed, which I think is another bug. Is it right?
  
**Environment:**
PF Version: 10.0.0-RC2 (Was working in PF8)
JSF + version: JSF 2.2.19
Affected browsers: Chrome, Safari

**To Reproduce**
1. Insert scrollable="true"  in  p:treeTable
2. Incude some dynamic columns and set their width's
3. See error

**Expected behavior**
Columns in the second table  ( scrollable="true") should match the fist one:
![image](https://user-images.githubusercontent.com/1834036/110345500-63aacc00-800d-11eb-800d-50b7de1d80a3.png)

**Example XHTML**
``` 
 <p:treeTable value="#{relatorioBean.root}"     var="item" id="tabelaItens" 
                          scrollable="true"      	  >  

           <p:column      style="width:150px;"    >  
			            <f:facet name="header">  <h:outputText value="col1"  />       </f:facet>  
			            <h:outputText value="col1"  />  
	     </p:column>  


  <c:forEach var="i" begin="0"       end="#{fn:length(relatorioBean.listaPeriodicidade) -1}" step="1"  >
	 <!--   equivalent  ui:repeat doesn't work here -->	
                       
                                            <p:column      field="#{item.listaPeriodoValor[i]}"
			                                       style="width: 100px;" width="100" > 
	                                              <!--   Apparently the width="100" param has no effect here -->		 
                                                      <f:facet name="header" >   
						               <h:outputText     value="title #{i}"  />
						       </f:facet> 
						     <h:outputText  value="#{i} value "  />
					   </p:column>
				        </c:forEach>  		      
```

**Comment by melloware** [comment]
Did ui:rpeat work in PF8?  I don't think it would I think you have to use `forEach` or `p:columns` if you want dyanmic columns.

**Comment by edudoda** [comment]
> Did ui:rpeat work in PF8? I don't think it would I think you have to use `forEach` or `p:columns` if you want dyanmic columns.

No, to generate columns indeed I use c:forEach, but is just a doubt related to this, why we can't use it, I generally try to use it in favor of c:forEach as component says it's a 'safe' replacement:  `<ui:repeat: "Repeatedly renders its content by iterating through the List returned from the value attribute. Intended as a JSF-safe replacement for c:forEach."`
And it works fine when is inside each <p:colum />, but can't use to generate them.

**Comment by melloware** [comment]
No its due to the way the component is rendered `repeat` does not work for Columns..  You really should be using `<p:columns` not forEach anyway?

**Comment by edudoda** [comment]
> No its due to the way the component is rendered `repeat` does not work for Columns.. You really should be using `<p:columns` not forEach anyway?

Got it! Just tried with `p:columns` and got the same problem  as `c:forEach` regarding to the column-size layout. 

However, when used `p:columns` dynamic columns are not exported as they are using `c:forEach` with    `l:dataExporter`  (xmlns:l="http://www.lapis.com/jsf/exporter")

**Comment by melloware** [comment]
I don't know what that Lapis exporter is so it could have a bug where it doesn't understand p:columns...

**Comment by edudoda** [comment]
> I don't know what that Lapis exporter is so it could have a bug where it doesn't understand p:columns...

It's an [old project/code](https://github.com/rdicroce/jsfexporter) that enable us to export p:treeTables to Excel/PDF out of the box. BTW it's not related to this issue.

**Comment by melloware** [comment]
Can you put together a reproducer or test your code against the latest 10..0.0-SNAPSHOT which now has the other scrollable fix in it?

**Comment by edudoda** [comment]
> Can you put together a reproducer or test your code against the latest 10..0.0-SNAPSHOT which now has the other scrollable fix in it?

Sure...should I upgrade my code to this version or it has some broke code yet? Because now my code broke in many parts:
- **org.primefaces.model.UploadedFile**  .getInputStream()  becomes  getInputstream()
- **org.primefaces.model.SortMeta** lost the new SortMeta.builder() 
- **org.primefaces.component.columntoggler**; getDataSourceComponent() is lost and getDatasource() dont bring .getChildren()
- There is **org.primefaces.model.file.UploadedFile** and also  **org.primefaces.model.UploadedFile;** 
- **org.primefaces.model.chart.PieChartModel** lost showDatatip();
-  and others...

**Comment by edudoda** [comment]
Sure, but how can I download this version? 
Can't see it on Maven:  Missing artifact org.primefaces:primefaces:jar:10.0.0-SNAPSHOT
 
```
 <dependency>
                    <groupId>org.primefaces</groupId>
                    <artifactId>primefaces</artifactId>
                    <version>10.0.0-SNAPSHOT</version>   <!-- and 10..0.0-SNAPSHOT -->
  </dependency>   
```

**Comment by stolp** [comment]
You want that:

```
 <dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>

 <repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>
```

See https://github.com/primefaces/primefaces

**Comment by edudoda** [comment]
> You want that:
> 
> ```
>  <dependency>
>      <groupId>com.github.primefaces</groupId>
>      <artifactId>primefaces</artifactId>
>      <version>master-SNAPSHOT</version>
>  </dependency>
> 
>  <repositories>
>  	<repository>
>  	    <id>jitpack.io</id>
>  	    <url>https://jitpack.io</url>
>  	</repository>
>  </repositories>
> ```
> 
> See https://github.com/primefaces/primefaces

I didn't mention but I tried that in my legacy code, but I don't know why  it gives me old primefaces-5.1.jar
**But when run it from https://github.com/primefaces/primefaces-test  it works!**  Apparently this issue was fixed.

**Comment by melloware** [comment]
Yep that is why we always recommend you use PrimeFaces Test.

**Comment by edudoda** [comment]
Found it, it was due to that lib [com.lapis.jsfexporter](https://mvnrepository.com/artifact/com.lapis.jsfexporter/export-source-primefaces/1.0.3.Final)  I mentioned above =x,  which was requesting for PF5.1 version, and because when using -SNAPSHOT approach [maven resolves  to the nearest version](https://stackoverflow.com/questions/34201120/maven-set-dependency-mediation-strategy-to-newest-rather-than-nearest), not newest one.
Inserting    `<exclusion> <groupId>org.primefaces</groupId> ...` in that lib solves the problem, but nice to see that it still working after so many years and versions.

**Comment by melloware** [comment]
TreeTable will have a first class Exporter in PF11 so you can get rid of that lib hopefully.
