### ISSUE TITLE
Message: display="tooltip" does not work since 8.0

### ISSUE THREAD

**Issue by juvenislux015** [primefaces/primefaces#7097]
**Describe the defect**
p:message as tooltip is not working.

**Reproducer**
See www.primefaces.org/showcase/ui/message/messages.xhtml
![image](https://user-images.githubusercontent.com/22677843/110563413-3df50280-8186-11eb-92c5-e08d1b2a4afe.png)

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _2.3.5_
 - Affected browsers: _Chrome, Firefox_

**To Reproduce**
```<p:tooltip/>
    <h:form>
        <h:panelGrid id="grid" columns="3" cellpadding="7">
            <p:outputLabel for="tt" value="Tooltip:"/>
            <p:inputText id="tt" required="true"/>
            <p:message for="tt" display="tooltip"/>
        </h:panelGrid>
        <p:commandButton id="submitButton" value="Submit" update="grid" styleClass="p-mt-3" />
    </h:form>
```

**Expected behavior**
Required message should be displayed as tooltip.

**Comment by melloware** [comment]
Looks like there are 2 issues here.  1 we need to make the style more specific to hide the current message
```css
body .ui-message.ui-helper-hidden {
  display: none;
}
```
Second issue is when even after I hide the message why the tooltip is not displayed.
