### ISSUE TITLE
PanelGrid: make attribute "columns" optional

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7099]
Currently, p (as well as h) panelGrid requires the attribute columns. It would cool to get rid of this restriction and to create the grid based on the actual child elements. For instance, 

    <p:panelGrid>
           <h:outputText value="a" />
           <h:outputText value="b" />
           <h:outputText value="c" />
    </p:panelGrid>

would be equivalent to:

    <p:panelGrid columns="3">
           <h:outputText value="a" />
           <h:outputText value="b" />
           <h:outputText value="c" />
    </p:panelGrid>

The big advantage would be that the panelGrids could be used more generically for all computed content where the number of elements is not known in advance. 

Wdyt?

**Comment by stolp** [comment]
-1. I am strictly against such a change, since it totally breaks backwards compatibility.

**Comment by tuerker** [comment]
the attribute should only be optional and will thus not break backwards compatibility.

**Comment by tuerker** [comment]
you could still use it as of now with the columns attribute.

**Comment by stolp** [comment]
I was to quick with my objection. I think the current state is, that columns is already optional with 0 as the default.
In that case a p:row is required.

**Comment by tuerker** [comment]
i think it should be a straight-forward extension to make the attribute columns optional without the necessity to use p:row or whatever.

**Comment by tuerker** [comment]
currently i have hundreds of panelGrids, e.g., using the same rendering conditions and styleClass attributes, which i cannot refactor because the panel grids does not have the same number of columns.

**Comment by tandraschko** [comment]
i general i dont even understand why someone would use a h/p:panelGrid. I like plain html and grid systems much more, people should more rely on plain html.

**Comment by melloware** [comment]
-1. I agree with @tandraschko and also @tuerker i think it needs the columns so it knows where to wrap right especially in layout="flex" or layout="grid".

So columns=2 
```xml
<p:panelGrid columns="2">
       <h:outputText value="a" />
       <h:outputText value="b" />
       <h:outputText value="c" />
</p:panelGrid>
```

Would put A and B on the first row and C on the second row.  So I don't think we should change this to assume what a user wants they should have to be explicit about it.

**Comment by stolp** [comment]
> i general i dont even understand why someone would use a h/p:panelGrid. I like plain html and grid systems much more, people should more rely on plain html.

I agree, but think this is typically a problem with legacy code. There was a time when grid systems where just not ready. Refactoring a few hundred p:panelGrid instances really is time consuming and no fun.

**Comment by tuerker** [comment]
@melloware i am not proposing to change the current semantics. i am just asking for a little extension. so whenever the attribute columns is not provided, the panelgrid should derive it automatically from the number of child elements.

**Comment by melloware** [comment]
So this could be done but it would rquired two loops.  1 loop to figure out how many columns there are and you can't use `getChildCount` because you have to account for unrendered items.
```java
        for (UIComponent child : grid.getChildren()) {
            if (!child.isRendered()) {
                continue;
            }

            int colMod = i % columns;
```

Also we currently throw an exception if columns=0.
```java
int columns = grid.getColumns();
        if (columns == 0) {
            throw new FacesException("Columns of PanelGrid \"" + grid.getClientId(context) + "\" must be greater than zero in grid layout.");
        }
```

**Comment by tuerker** [comment]
dear @melloware, i am thinking loud since i am not deep in the code. would it be not sufficient to change the method

`public int getColumns() { return (Integer) getStateHelper().eval(PropertyKeys.columns, 0); }`

such that it checks whether attribute columns is explicitly set, and if yes it return the corresponding value.  if the attribute columns is not set, then it counts the rendered childs and return this value. then everything else should work unchanged?

**Comment by melloware** [comment]
While it works for static layouts like...
![image](https://user-images.githubusercontent.com/4399574/111482093-f502f800-8709-11eb-824c-a47335e99adb.png)

It breaks using `<p:row>` example where its EXPECTING `columns=0` like in the Showcase.
![image](https://user-images.githubusercontent.com/4399574/111481922-cd139480-8709-11eb-9c09-b5af8961bbdf.png)

```xml
<h5>Grouping</h5>
    <p:panelGrid style="margin-top:20px">
        <f:facet name="header">
            <p:row>
                <p:column colspan="7">1995-96 NBA Playoffs</p:column>
            </p:row>
            <p:row>
                <p:column colspan="2">Conf. Semifinals</p:column>
                <p:column colspan="2">Conf. Finals</p:column>
                <p:column colspan="2">NBA Finals</p:column>
                <p:column>Champion</p:column>
            </p:row>

        </f:facet>

        <p:row>
            <p:column style="font-weight: bold;">Seattle</p:column>
            <p:column style="font-weight: bold;">4</p:column>

            <p:column rowspan="2" style="font-weight: bold;">Seattle</p:column>
            <p:column rowspan="2" style="font-weight: bold;">4</p:column>

            <p:column rowspan="5">Seattle</p:column>
            <p:column rowspan="5">2</p:column>

            <p:column rowspan="11" style="font-weight: bold;">Chicago</p:column>
        </p:row>

        <p:row>
            <p:column>Houston</p:column>
            <p:column>0</p:column>
        </p:row>

        <p:row>
            <p:column colspan="4" styleClass="ui-widget-header">
                <p:spacer height="0"/>
            </p:column>
        </p:row>

        <p:row>
            <p:column style="font-weight: bold;">Utah</p:column>
            <p:column style="font-weight: bold;">4</p:column>

            <p:column rowspan="2">Utah</p:column>
            <p:column rowspan="2">3</p:column>
        </p:row>

        <p:row>
            <p:column>San Antonio</p:column>
            <p:column>2</p:column>
        </p:row>

        <p:row>
            <p:column colspan="6" styleClass="ui-widget-header">
                <p:spacer height="0"/>
            </p:column>
        </p:row>

        <p:row>
            <p:column style="font-weight: bold;">Chicago</p:column>
            <p:column style="font-weight: bold;">4</p:column>

            <p:column rowspan="2" style="font-weight: bold;">Chicago</p:column>
            <p:column rowspan="2" style="font-weight: bold;">4</p:column>

            <p:column rowspan="5" style="font-weight: bold;">Chicago</p:column>
            <p:column rowspan="5" style="font-weight: bold;">4</p:column>
        </p:row>

        <p:row>
            <p:column>New York</p:column>
            <p:column>1</p:column>
        </p:row>

        <p:row>
            <p:column colspan="4" styleClass="ui-widget-header">
                <p:spacer height="0"/>
            </p:column>
        </p:row>

        <p:row>
            <p:column>Atlanta</p:column>
            <p:column>1</p:column>

            <p:column rowspan="2">Orlando</p:column>
            <p:column rowspan="2">0</p:column>
        </p:row>

        <p:row>
            <p:column style="font-weight: bold;">Orlando</p:column>
            <p:column style="font-weight: bold;">4</p:column>
        </p:row>


        <f:facet name="footer">
            <p:row>
                <p:column colspan="4" style="text-align: right">
                    Finals MVP
                </p:column>
                <p:column colspan="3" rowspan="3">
                    Michael Jordan (Chicago)
                </p:column>
            </p:row>

            <p:row>
                <p:column colspan="4" style="text-align: right">
                    Season MVP
                </p:column>
            </p:row>
            <p:row>
                <p:column colspan="4" style="text-align: right">
                    Top Scorer
                </p:column>
            </p:row>
        </f:facet>
    </p:panelGrid>
```

So I am inclined NOT to make this change.

**Comment by stolp** [comment]
I feel sorry @tuerker but I also still agree to not implement this.

**Comment by tuerker** [comment]
this is rather hint that the attribute columns is expected to be = 0 somewhere else instead of dealing with the null/empty value.

of course, there would the solution to extend the panelgrid by a new attribute "autoColumns" (or "derivedColumns", ...) which is set to true whenever one cannot/want not to explicitly set the number of columns upfront. 

@melloware wdyt?

**Comment by melloware** [comment]
I agree I think this would require a new attribute

**Comment by melloware** [comment]
Going to close this for now.  Can always re-open if we get lots of feedback but right now no plan to implement.
