### ISSUE TITLE
Editor tooltips not disappearing when text area not active

### ISSUE THREAD

**Issue by jensendk** [primefaces/primefaces#710]
Hello primetek

I have been using your Editor, the thing I have found is that when, the text area is not marked/active the tooltips of all the abilities to change font size etc. is not disappearing, see Screenshot

http://i60.tinypic.com/14o26mv.png

When one activates the text area, the button is now enabled and the tooltips works correctly. See screenshot

http://i57.tinypic.com/11rpuvo.png

As you can see on the lower screenshot, the disabled buttons created the behavior, the active once doesn’t.

Is this a know issue or what is going on?

**Comment by smokeybandit** [comment]
I just came across this, too in v.5.3.    Only seems to be an issue in IE.  The disabled button never receives the hoverleave/mouseleave event.

**Comment by jensendk** [comment]
Date: Mon, 2 May 2016 09:39:12 -0700

**Comment by tandraschko** [comment]
p:editor uses cleditor under the hood which is not maintained since years.
I would suggest to use PrimeFaces Extensions CKEditor or the new p:textEditor (which doesn't work on all browsers).
