### ISSUE TITLE
CSP: default-src seems to be a directive, not a value

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#7103]
**Describe the defect**
I have found that default-src is added after nonce with comma which gives "default-src seems to be a directive, not a value" error. As a result nonce value is not approved by csp evaluator (https://csp-evaluator.withgoogle.com).

web.xml CSP_POLICY settings
```
<param-value>script-src 'self' https: *.googleapis.com</param-value>
```
and the result is

```
script-src 'self' https: *.googleapis.com 'nonce-NmQwNmMxY2YtMGI2Ni00MGFmLTg4YTQtM2U2OTg5ODNjOWY5', default-src * data: 'unsafe-eval' 'unsafe-inline'
```

<img width="960" alt="Screen Shot 2021-03-11 at 00 03 01" src="https://user-images.githubusercontent.com/9448030/110698220-6caebf80-81fe-11eb-946d-c47961cbbb01.png">

How can I remove or override default-src?

**Environment:**
 - PF Version: _8.0_
 - Affected browsers: Safari

**Comment by melloware** [comment]
Can you double check.  PrimeFaces does not add this `, default-src * data: 'unsafe-eval' 'unsafe-inline'` so I have no idea where that is coming from.

**Comment by melloware** [comment]
I just tested locally and this is what PF is generating...

![image](https://user-images.githubusercontent.com/4399574/110699188-9646f700-81bc-11eb-8289-45b73d72314c.png)

And its working properly.

**Comment by melloware** [comment]
Here is your policy also working...
![image](https://user-images.githubusercontent.com/4399574/110699977-6ba96e00-81bd-11eb-8d39-dcb104ad355c.png)

**Comment by aripddev** [comment]
Found it. It is because of nginx header settings which adds `Content-Security-Policy`.
Sorry for taking your time.
