### ISSUE TITLE
DataTable: Select single does not work when containing character comma

### ISSUE THREAD

**Issue by jsolanou** [primefaces/primefaces#7105]
Hi, I have a problem with the datatable component, when I want to display 
the value that ​​contains a comma character for example "dummy,some text.pdf".
The single selection and the multiple selection are no longer works. 
The event works fine, but when I debug it, doesn't bring the row selected it show 0 elements.
I'm using PrimeFaces Version 8.0

Is there a quick possible solution for this?

**Comment by tandraschko** [comment]
please follow the issue template and provide a reproducer, otherwise invalid.
and please test with todays released 10.0 before.

**Comment by jsolanou** [comment]
ok, thanks i will try with the primefaces version 10

**Comment by melloware** [comment]
I think your issue is this: https://github.com/primefaces/primefaces/issues/5946

**Comment by jsolanou** [comment]
@melloware  Thank you very much, if it is exactly the same behavior but reading the trace of the issue, it is a design error on my part since row key is a unique identifier and should be a number or alphanumeric.
