### ISSUE TITLE
Schedule rendering issue when minTime/maxTime used

### ISSUE THREAD

**Issue by mbeedub** [primefaces/primefaces#711]
Use of minTime/maxTime leads to rendering of large div which fills space below schedule to height of page (see attached).

![capturar](https://cloud.githubusercontent.com/assets/12140029/9991921/4cc56260-6066-11e5-9ebd-355575841aaa.jpg)

Also see 

http://forum.primefaces.org/viewtopic.php?f=3&t=43237&p=135625&hilit=schedule+height+auto#p135625

and 

http://forum.primefaces.org/viewtopic.php?f=3&t=43085&hilit=schedule+ajax

**Comment by kukel** [comment]
isn't this a jquery-fullcalendar issue? That is what PF uses and that is doing all the rendering.

**Comment by OBreidenbach** [comment]
This is duplicate to #4097
