### ISSUE TITLE
ThemeSwitcher: Remove in 11.0

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7119]
**Description**
Per PrimeTek the ThemeSwitcher component will be removed in 11.0

**Comment by texasaggie1994** [comment]
Out of curiosity, is the component simply redundant now and there is another way to accomplish switching themes or is it simply not supported? I was working on a way for a user to switch between a dark and light theme similar to the showcase and noticed that this widget was not working recently.

**Comment by melloware** [comment]
try something like this...
```xml
<h:form id="frmTest">
<p:selectOneMenu id="themeSelectMenu" value="#{userSettings.currentTheme}">
         <p:ajax process="@this" oncomplete="PrimeFaces.changeTheme($('#frmTest\\:themeSelectMenu_label').text());"/>
         <f:selectItems  value="#{userSettings.availableThemes}"/>
</p:selectOneMenu>
</h:form>
```
