### ISSUE TITLE
Publish TypeScript declarations to NPM

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#7124]
Now that 10.0 is released and the JavaScript docs [are up-to-date](#7123), it would be great if the [TypeScript declarations](https://github.com/primefaces/primefaces/blob/master/docs/PrimeFaces.d.ts) could be published to NPM. For now, in my own projects, I just copied said file into my project, but that's a bit hard to update and maintain. If it were published on NPM, people could then just

* npm install -D primefaces

and add

```javascript
/// <reference types="primefaces" />
```

to the top of their file to (a) enjoy auto completion and (b) type checking.

* There's a script and maven profile for publishing to NPM, see [the readme](https://github.com/primefaces/primefaces/tree/master/src/main/type-definitions#publish-to-npm). 
* For now I set the package name `primefaces`. This does not exist yet on NPM, but we could also use another name.
* @melloware I think you did ask PrimeTek about this? Did they say anthing about this?

Also note, the publish maven profile reads the version from the pom, which is now 11, so we need to specifiy the version explicitly:

```bash
mvn org.codehaus.mojo:build-helper-maven-plugin:parse-version \
  com.github.eirslett:frontend-maven-plugin:npm@publish-to-npm \
  "-Dnpm.token=token" \
  -DparsedVersion.majorVersion=10 \
  -DparsedVersion.minorVersion=0
```

**Comment by melloware** [comment]
I did ask PrimeTek and it didnt sound like they were interested in publishing it.    I will ask one more time and if not then I think I should create a token and publish them no?

**Comment by blutorange** [comment]
@melloware First of all, thanks for asking. Hmm yeah well, would be great if you ask again. Though I guess the only question would be if they have anything against us doing it or whether they have any preferences regarding the package name etc.

Publishing to NPM shouldn't be hard, go ahead and get a token and claim the package name.

**Comment by melloware** [comment]
OK I will let you know what they say.

**Comment by melloware** [comment]
Also are you on the Discord channel?  If not you should be!

**Comment by melloware** [comment]
OK PrimeTek said it was OK if I push it to NPM.  However when running the commend above with my proper token I get this error.
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:npm (publish-to-npm) on project primefaces: Failed to run task: 'npm run npm-publish -- --major 10 --minor 0 --readme src/main/type-definitions/NPM.md --extrafiles LICENSE --prompt false --username --password --email --token XXX' failed. java.io.IOException: Cannot run program "C:\dev\primefaces\primefaces-melloware\target\node\node.exe" (in directory "C:\dev\primefaces\primefaces-melloware\src\main\type-definitions"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]

```

**Comment by blutorange** [comment]
Are you working on a `clean`ed directory? There's [a separate goal that installs Node / NPM and runs npm install](https://github.com/primefaces/primefaces/blob/master/pom.xml#L361-L368). Can you try doing a `mvn package` first, this should run those goals?

If that works, we should include it in the publish profile.

**Comment by melloware** [comment]
Yep I was in a cleaned directory.  OK its published!

See: https://www.npmjs.com/package/primefaces

**Comment by blutorange** [comment]
Awesome, looks great. I'll give it a try later.
