### ISSUE TITLE
DatePicker: AutoDetect Display Mode

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7126]
**Description**
Add a new `autoDetectDisplay` attribute to the DatePicker which will detect if the browser is Mobile it will set `touchUi=true` else it will be false for Desktop browser.

Based on conversation on Discord with @jepsar and @willbigas

**Comment by jepsar** [comment]
Maybe a standard input with some pass throughs will do instead of reimplementing the UI of this component. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by melloware** [comment]
Well that input looks like its just for Time Input?

**Comment by melloware** [comment]
Maybe a new `InputTime` component?

**Comment by jepsar** [comment]
> Will that input looks like its just for Time Input?

No, not at all.. and it is browser dependent. Wasn't thinking of building it into this component, but to use it as an alternative.

Can find any good, modern time pickers.. have been looking for quite a while now.

Something like this would be nice https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#handling_browser_support

**Comment by melloware** [comment]
Actually I think you can use this now like this...
```xml
<p:inputText type="time" />
```

**Comment by jepsar** [comment]
> Actually I think you can use this now like this...
> 
> ```
> <p:inputText type="time" />
> ```

Yeah, with some pass throughs.

This would be nice if it looked good on retina screens https://github.com/loebi-ch/jquery-clock-timepicker

**Comment by jepsar** [comment]
Oh no.. I was commenting at the wrong issue! Sorry for the noise.. Comments should have been on https://github.com/primefaces-extensions/primefaces-extensions/issues/283
