### ISSUE TITLE
Layout: no tag was defined for name

### ISSUE THREAD

**Issue by samgoularte** [primefaces/primefaces#7137]
**Describe the defect**
Layout and LayoutUnit tags are not being recognized in version 10.0.0.

**Reproducer**
_n/a_

**Environment:**
 - PF Version: _10.0.0_
 - JSF 
 - Affected browsers: _All_

**Example XHTML**
```html
<p:layout fullPage="true">
   <p:layoutUnit position="west" collapsible="true">
      <h:form id="frmTest">
      <!-- any content here -->
      </h:form>
  </p:layoutUnit>
  
  <p:layoutUnit position="south">
      <!-- any content here -->
  </p:layoutUnit>
</p:layout>
```

**Example Bean**
_n/a_
```
![image](https://user-images.githubusercontent.com/54247948/111529064-7f664e80-8740-11eb-97de-b099cd55ec4f.png)

**Comment by melloware** [comment]
Yep was removed in PF10.0.0 see: ticket: https://github.com/primefaces/primefaces/issues/2168

You can use Layout from PrimeFaces Extensions: https://www.primefaces.org/showcase-ext/views/layout.jsf;
