### ISSUE TITLE
Dialog fitViewport doesn't work in pf 10.0.0

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#7139]
**Describe the defect**
dialog.js function fitViewport, please change the row `this.content.css('max-height', String(maxHeight));` to `this.content.css('max-height', maxHeight);`. String constant for max-height without units doesn't work in jquery 3.5.1 which is used in PF 10.0.0. In jquery 3.6.0 it works fine.

**Environment:**
 - PF Version: 10.0.0

**Comment by melloware** [comment]
@vonnai can you try this and verify it works... Just add this script to your application.
```javascript
if (PrimeFaces.widget.Dialog) {
    PrimeFaces.widget.Dialog.prototype.fitViewport = function() {
        var windowHeight = $(window).height();
        var margin = this.jq.outerHeight(true) - this.jq.outerHeight();
        var headerHeight = this.titlebar.outerHeight(true);
        var contentPadding = this.content.innerHeight() - this.content.height();
        var footerHeight = this.footer.outerHeight(true) || 0;
        var maxHeight = windowHeight - (margin + headerHeight + contentPadding + footerHeight);
        this.content.css('max-height', maxHeight + 'px');
    }
}
```

**Comment by vonnai** [comment]
yes, these solutions `this.content.css('max-height', maxHeight + 'px');` or `this.content.css('max-height', maxHeight);` works fine. But you didn't have to do that for pf 11 with jquery 3.6.0. Only 10.0.1 needs it. Thanks

**Comment by melloware** [comment]
Yep I just think it makes this fix more explicit with its intent.  jquery keeps going back on forth on requiring Strings for CSS variables.

**Comment by melloware** [comment]
That is why it broke they had JQuery Migration plugin telling us that it was a violation passing a number into CSS it had to be a String.  And they still may require that for jQuery 4.0

**Comment by VsevolodGolovanov** [comment]
Not sure why you're scripting at all here. Could just style smth like `max-height: calc(100vh - 50px);`. This should work even in IE9. I'd remove the fitViewport option and just have it like this by default. Then if someone really needs an overflowing dialog they could just override max-height by styling.
