### ISSUE TITLE
Spinner: without thousands and decimals separator

### ISSUE THREAD

**Issue by leosj29** [primefaces/primefaces#7144]
**Description**

I think it would be important to create an attribute to the component to show its numeric content without any formatting or with a desired format (separators, which are already there)

**Example XHTML**
```xml
<p:spinner                                    
   useSeparators="true"  />  <!-- default -->
```

![Selection_500](https://user-images.githubusercontent.com/2030440/111841051-f4fa2800-88c2-11eb-9e27-47627fc9b6bc.png)

```xml
<p:spinner                                    
   useSeparators="false"  /> 
```

![Selection_499](https://user-images.githubusercontent.com/2030440/111841079-017e8080-88c3-11eb-9bf7-47d729174d13.png)

**Comment by leosj29** [comment]
I have two possible options.

The first option is to add the **useSeparators** property (default true)


**Option 1 -> SpinnerBase.java**
```java
public String getDecimalSeparator() {
        return ComponentUtils.eval(getStateHelper(), PropertyKeys.decimalSeparator,
            () -> (!isUseSeparators() ? Constants.EMPTY_STRING : LocaleUtils.getDecimalSeparator(getFacesContext())));
  }

  public String getThousandSeparator() {
      return ComponentUtils.eval(getStateHelper(), PropertyKeys.thousandSeparator,
          () -> (!isUseSeparators() ? Constants.EMPTY_STRING : LocaleUtils.getThousandSeparator(getFacesContext())));
  }
```

The second option is to ignore the Locale and leave the use of the separators to the choice of the developer

**Option 2 -> SpinnerBase.java**
```java
public String getDecimalSeparator() {
        return ComponentUtils.eval(getStateHelper(), PropertyKeys.decimalSeparator,null);
  }

  public String getThousandSeparator() {
      return ComponentUtils.eval(getStateHelper(), PropertyKeys.thousandSeparator,null);
  }
```

**Comment by melloware** [comment]
You can already do this now.

```xml
 <p:spinner id="basic" value="#{spinnerView.number1}" decimalSeparator="" thousandSeparator=""/>
```

![image](https://user-images.githubusercontent.com/4399574/111869466-13f5ca00-8956-11eb-95eb-1781bc778563.png)


And if you wanted to do this for all your spinners you can set it globally like this: https://primefaces.github.io/primefaces/10_0_0/#/core/globalattributes

**Comment by leosj29** [comment]
> You can already do this now.
> 
> ```
>  <p:spinner id="basic" value="#{spinnerView.number1}" decimalSeparator="" thousandSeparator=""/>
> ```
> 
> ![image](https://user-images.githubusercontent.com/4399574/111869466-13f5ca00-8956-11eb-95eb-1781bc778563.png)
> 
> And if you wanted to do this for all your spinners you can set it globally like this: https://primefaces.github.io/primefaces/10_0_0/#/core/globalattributes

By default, before version 8 it did not generate the separators. I think that for compatibility reasons the separators should appear if indicated by the developers and not have to remove them as indicated above.

**Comment by melloware** [comment]
As with all major version upgrades things are subject to change and not stay backward compatible forever.  The decision was made to default this as enabled and allow a developer to disable them if they don't want them in my example above.

**Comment by leosj29** [comment]
OK, thanks

**Comment by leosj29** [comment]
> > You can already do this now.
> > ```
> >  <p:spinner id="basic" value="#{spinnerView.number1}" decimalSeparator="" thousandSeparator=""/>
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/4399574/111869466-13f5ca00-8956-11eb-95eb-1781bc778563.png)
> > And if you wanted to do this for all your spinners you can set it globally like this: https://primefaces.github.io/primefaces/10_0_0/#/core/globalattributes
> 
> By default, before version 8 it did not generate the separators. I think that for compatibility reasons the separators should appear if indicated by the developers and not have to remove them as indicated above.



I tried to use the properties as you mentioned above, but when submitting the form it generates error.

![Selection_586](https://user-images.githubusercontent.com/2030440/115800293-8dd70400-a397-11eb-91ac-b2c3967a59c2.png)
And when sending the form it generates
![Selection_585](https://user-images.githubusercontent.com/2030440/115800360-ae9f5980-a397-11eb-85c4-67a883b649f4.png)

The code is

> > ```
> ><h:form>            
> >   <p:spinner id="basic" 
> >         value="#{dtFilterView.number1}"
> >         decimalSeparator=""
> >         thousandSeparator=""/>  
> >    <br/>
> >   <p:commandButton ajax="false"
> >         value="Send" 
> >         icon="ui-icon-disk"
> >         action="#{testView.save}" />
> > </h:form>
> > ```

**Comment by melloware** [comment]
ReproduReproducer is working fine for me:
[pf-7252.zip](https://github.com/primefaces/primefaces/files/6364784/pf-7252.zip)

Rune `mvn clean jetty:run` and go to http://localhost:8080/primefaces-test/test.xhtml
