### ISSUE TITLE
DefaultMenuItem: Breaking change not documented

### ISSUE THREAD

**Issue by clarktrip1** [primefaces/primefaces#7145]
new DefaultMenuItem( "SomeReallyCoolText" ) worked in 8.0.3 but no longer works.  That constructor has been removed.  I don't spot that breaking changing in the doc.

**Comment by melloware** [comment]
When you say worked in 8.0.3 and doesn't work do you mean in 10.0.0?

**Comment by melloware** [comment]
There is this in the 8.0 Migration Guide: https://primefaces.github.io/primefaces/10_0_0/#/../migrationguide/8_0?id=menu

```java
 DefaultMenuItem item = DefaultMenuItem.builder()
                .value("Save (Non-Ajax)")
                .icon("pi pi-save")
                .ajax(false)
                .command("#{menuView.save}")
                .update("messages")
                .build();
```
