### ISSUE TITLE
Datatable: selection set to empty array with array VE

### ISSUE THREAD

**Issue by aissous** [primefaces/primefaces#7147]
When the selectedRows attribute is Array in LazyDataModel, the items of the array have null values.
The problem is in org.primefaces.component.datatable.feature.SelectionFeature in setSelection method : 
selection = isArray ? Array.newInstance(clazz.getComponentType(), selected.size()) : selected;
This instruction create array with null objects.

**Comment by melloware** [comment]
This issue was also reported on Discord Channel.  @Rapster its definitely a regression.

@aissous to fix it right now switch from using `Car[] selectedCars` to `List<Car> selectedCars` will fix your issue.
