### ISSUE TITLE
Localization: Message property files use UTF-8 encoding which is not supported in Java 8

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7149]
**Describe the defect**
All message property files use UTF-8 encoding. This is not supported with Java 8, here we need ascii with utf-8 escapes.

This is leading to encoding errors for non-ASCII characters as reported here: https://forum.primefaces.org/viewtopic.php?f=3&t=66065

**Reproducer**
Run the showcase under Java 8,

**Environment:**
 - PF Version: _10.0.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**

Check the Localization example.

**Expected behavior**
Non ASCII characters should be properly encoded.

PR is following.

**Comment by stolp** [comment]
@melloware : I have a pull request ready, but it is stumbling over a checkstyle violation rule which I think should be lifted in the case of message properties:

/home/runner/work/primefaces-1/primefaces-1/src/main/resources/org/primefaces/Messages_ru.properties:35: Line is longer than 160 characters (found 315). [LineLength]
...

See: https://github.com/stolp/primefaces-1/commit/54336cf3e32a2e213b57dd30d0653bcbf380884c

**Comment by jepsar** [comment]
@stolp https://stackoverflow.com/questions/2362652/excluding-classes-in-maven-checkstyle-plugin-reports

**Comment by tandraschko** [comment]
isnt there a way to pass the encoding in MessageFactory? Maye use Properties instead of ResourceBundle?
i would like to stay with UTF8 if possible.

**Comment by melloware** [comment]
Yep I think I have a fix for this...

**Comment by stolp** [comment]
This is indeed the better solution. I will drop my work on a pull request.

**Comment by christophs78** [comment]
IMO this one did not made it into 10.0.1. Could it be added with 10.0.2?
