### ISSUE TITLE
Sidebar: Components z-index behind control

### ISSUE THREAD

**Issue by jarciano** [primefaces/primefaces#7153]
**Describe the defect**
When trying to use the DatePicker or autoComplete components within the sidebar they do not work, Another problem is that when adding a form with several fields the sidebar does not create a scroll. 

**Environment:**
 - PF Version: _8.0.7_
 - Affected browsers: _Chrome, iOS, ALL_

**To Reproduce**

Just add within a page the button that will call the sidebar and add the DatePicker or autoComplete components and the error will be simulated.

You can use your demo: http://www.primefaces.org:8080/showcase/ui/overlay/sidebar.xhtml

And add something like this:

**Expected behavior**
Run all existing Primefaces components within the sidebar, in addition to creating scrolling for cases where the form is large. 

**Example XHTML**
```html
<p:sidebar style="width: 80em" modal="true" position="right" baseZIndex="10000"
                                  widgetVar="Test" blockScroll="true">
<h3>Test Sidebar</h3>

<p:outputLabel value="Data da emissão"/>
                                                <p:datePicker value="#"
                                                              id="idDataEmissao" locale="br" pattern="dd/MM/yyyy"/>

  <p:outputLabel value="Simple" for="@next"/>
                <p:autoComplete id="acSimple" value="#{autoCompleteView.txt1}"
                            completeMethod="#{autoCompleteView.completeText}" scrollHeight="250"/>

</p:sidebar>
```

**Comment by melloware** [comment]
What happens if you set baseZIndex="1000" ?

**Comment by jarciano** [comment]
@melloware did the test to remove **baseZIndex="10000"** and the component apparently worked.

**Comment by melloware** [comment]
Yes I think the example should not show it at 10,000.  PF starts all zindex at 1000 so your DatePickers etc will get 1002, 1003 etc and be above the Sidebar.

**Comment by jarciano** [comment]
Really, even with baseZIndex="1000" the problem continues.

**Comment by melloware** [comment]
hmmm OK let me look.

**Comment by melloware** [comment]
Ahh I think the `baseZIndex` should only be used with `dyanmic="true"` to lazy load the sidebar until its clicked on.  Can you try that?

**Comment by jarciano** [comment]
It didn't work, see that I added `dyanmic="true"` and even then the components don't work.

```
<p:sidebar style="width: 80em" modal="true" position="right" baseZIndex="1000" dynamic="true"
                                  widgetVar="dialogAdicionarNF" blockScroll="true">...
```

https://www.loom.com/share/97e63b60f7a747c29818ee8baa771dd9

**Comment by melloware** [comment]
ok so baseZindex is a problem no matter what.  I will have to see why that property is even there.

**Comment by melloware** [comment]
I dont ses how this would ever work since it does this every time it shows the sidebar:
```javascript
this.jq.css('z-index', String(this.cfg.baseZIndex + (++PrimeFaces.zindex)));
```

**Comment by jarciano** [comment]
And in the case of scrolling the content inside the sidebar any solution?

**Comment by melloware** [comment]
Sorry can you use a ScrollPanel with height and width set to 100%.
https://www.primefaces.org/showcase/ui/panel/scrollPanel.xhtml

**Comment by jarciano** [comment]
It really worked, did it that way is correct? `<p:scrollPanel mode="native" style="width:100%;height:100%">`

Now I would like to remove the contour line from the panel that was created 
https://gyazo.com/8a433fbc03eb0436ef0424992d8d323b

**Comment by melloware** [comment]
```css
body .ui-scrollpanel {
    border: none;
}
```

**Comment by jarciano** [comment]
I prefer to work directly on the component, and it worked just by adding `border: none;`
`<p:scrollPanel mode="native" style="width:100%; height:100%; border:none;">`

**Comment by melloware** [comment]
Decided since this property has value in certain circumstances to just update the documentation to provide more clarity on this attribute.
