### ISSUE TITLE
Exporter: code looks weird

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7163]
See: https://github.com/primefaces/primefaces/pull/7017#issuecomment-804979792

**Comment by tandraschko** [comment]
@ravihariharan  please see my questions in the linked ticket and come back

**Comment by melloware** [comment]
@tandraschko I just updated a showcase example for Grouped Datatable that shows it exporting two datatables.

```xml
<p:dataExporter type="xlsxstream" target="tblSales tblPlayers" fileName="grouped"/>
```

For XLS download it puts each Datatable in its own Excel Sheet in the download.

**Comment by tandraschko** [comment]
@melloware 
can you check this example? http://localhost:8080/showcase/ui/data/datatable/group.xhtml?jfwid=99ad4

export throws a exception for me

**Comment by melloware** [comment]
Yep will investigate.

**Comment by tandraschko** [comment]
i get something like this:
```
java.lang.IllegalArgumentException: Invalid cell range, having lastRow < firstRow || lastCol < firstCol, had rows 0 >= 0 or cells -1 >= 0
	at org.apache.poi.ss.util.CellRangeAddress.<init>(CellRangeAddress.java:49)
```
	
PDF seems also broken

**Comment by melloware** [comment]
Yep I see the problem.  Working on a fix.

**Comment by melloware** [comment]
OK fixed and merged.  I assumed ColumnMeta always returned the ColumnMeta for the table but it is allowed to be empty if you are not using DisplayProiorty or others.  So it has to handle both cases.  Exporter is now fixed all around.

**Comment by tandraschko** [comment]
@melloware refactored; can you review plz?

**Comment by melloware** [comment]
Looks great and I just tested everything locally and everything is working as expected!
