### ISSUE TITLE
Datatable: Lazy Loading and sort listener in wrong call order

### ISSUE THREAD

**Issue by CGSUser1** [primefaces/primefaces#7164]
**Describe the defect**
When I use a sort listener in a datatable with lazy loading, the load method is called before the sort listener method. It works fine with a page listener.

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _MyFaces 2.3.6_
 - Affected browsers: _Chrome_

**To Reproduce**
Steps to reproduce the behavior: There is no showcase. See the code below.

**Expected behavior**
In Version 8 the sort listener was called before the load method

**Example XHTML**
```html
<p:dataTable value="#{controller.lazyDataModel}"
             lazy="true"
             sortMode="multiple"
             ...>

    <p:ajax event="sort" listener="#{controller.sortListener()}" process="@this" />
    <p:ajax event="page" listener="#{controller.pageListener()}" process="@this" />

...
</p:dataTable>
```

**Example Bean**
```java
@Named
@ViewScoped
public class Controller implements Serializable {

    ...

    public void sortListener() {
        sortEvent = true;
    }

    public void pageListener() {
        pageEvent = true;
    }
}
```

**Comment by melloware** [comment]
@Rapster does this go back to the point that these features are not in a ordered Map so its random not predictable order that was reported before?

**Comment by Rapster** [comment]
Current scenario sounds good to me. Though, features has always been decoded before behaviors so I'm kinda surprised it didn't work that way in 8.0

**Comment by melloware** [comment]
Linking to this ticket which is related: https://github.com/primefaces/primefaces/issues/6690

**Comment by melloware** [comment]
Wait I thought the Load Method was called in RENDER_RESPONSE phase so how can this be?  The Sort should be called before the load method?

**Comment by Rapster** [comment]
Oh I get how it was working in 8.0, indeed sort was called in RENDER_RESPONSE phase, that would explain why sort listener was called before load actually happen.

**Comment by melloware** [comment]
Reproducer:
[pf-7164.zip](https://github.com/primefaces/primefaces/files/6503374/pf-7164.zip)

**10:0.0:** 
```
LazyDataModel.load() called
TestView.sort() called
```

**Comment by melloware** [comment]
Here is what happens when I dump the stack when the page first loads..
```
LazyDataModel.load() called
java.base/java.lang.Thread.getStackTrace(Thread.java:1607)
org.primefaces.test.LazyCustomerDataModel.load(LazyCustomerDataModel.java:68)
org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:459)
org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:126)
org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:93)
javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
```

But when the field is sorted you can see the "lazy" method is called in the SortFeature.
```
LazyDataModel.load() called
java.base/java.lang.Thread.getStackTrace(Thread.java:1607)
org.primefaces.test.LazyCustomerDataModel.load(LazyCustomerDataModel.java:68)
org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:459)
org.primefaces.component.datatable.feature.SortFeature.decode(SortFeature.java:103)
org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:72)
javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)
org.primefaces.component.api.UIData.processDecodes(UIData.java:117)
```
