### ISSUE TITLE
Add partialUpdate attribute to DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#7165]
| Name | Default | Type | Description
| ---| --- | --- | --- |
| partialUpdate | true | Boolean  | When disabled, it updates the whole table instead of updating a specific field such as body element in the client requests of the dataTable. Default is true.

Note: When disabled, it updates the whole table for _Sorting_, _Filtering_, and _Page_ events.

Details; https://github.com/primefaces/primefaces/pull/7157

**Comment by tandraschko** [comment]
@mertsincan its still called autoUpdate currently

**Comment by mertsincan** [comment]
Fixed now.

**Comment by tandraschko** [comment]
looks better :) just did a small cosmetics on the request param (the opposite of "partial update" is "full update")

**Comment by mertsincan** [comment]
Thanks @tandraschko, the "fullupdate" word didn't sound nice to me, so I used the "rerender" word :)
