### ISSUE TITLE
Datatable: liveScroll not working when inside OverlayPanel

### ISSUE THREAD

**Issue by ufukarmagan** [primefaces/primefaces#7167]
Datatable liveScroll not working when inside OverlayPanel

**Reproducer**
Datatable liveScroll (inside OverlayPanel) worked on PF 8, but after upgrading PF10, it's not working.

 - PF Version: 10
 - JSF + version: 2.2
 - Affected browsers: ALL

**Comment by ufukarmagan** [comment]
any workarounds will be welcome

**Comment by melloware** [comment]
When you say its not working can you be more specific or provide a PrimeFaces Test reproducer please?

**Comment by ufukarmagan** [comment]
At PF8, when I open overlay, first datatable's 10 rows fetched, then other 10 rows fetched when scrolling inside overlayPanel, so liveScroll worked.
At PF10, still first 10 rows fetching, but when scrolling inside overlayPanel this time nothing happen, 
![overlay_defect](https://user-images.githubusercontent.com/17969359/112476280-c973b380-8d82-11eb-8238-2ae7caaa0abe.PNG)
so other rows not fetching (because of LazyDataModel's load method not called)

**Comment by melloware** [comment]
Something tells me the calculation of determining that the scroll has changed to fire the load has changed.  Possibly Jquery change or something else...
```javascript
           else if($this.shouldLiveScroll) {
                var scrollTop = Math.ceil(this.scrollTop),
                scrollHeight = this.scrollHeight,
                viewportHeight = this.clientHeight;

                if((scrollTop >= ((scrollHeight * $this.cfg.liveScrollBuffer) - (viewportHeight))) && $this.shouldLoadLiveScroll()) {
                    $this.loadLiveRows();
                }
            }
```

**Comment by melloware** [comment]
would be great if you could debug.

**Comment by melloware** [comment]
@ufukarmagan Can you put together a reproducer using PF Test so I can debug the issue?
See: https://github.com/primefaces/primefaces-test

**Comment by ufukarmagan** [comment]
I've been forked PF Test project for this case: https://github.com/ufukarmagan/primefaces-test

**Comment by ufukarmagan** [comment]
> @ufukarmagan Can you put together a reproducer using PF Test so I can debug the issue?
> See: https://github.com/primefaces/primefaces-test

I've been forked PF Test project for demonstrating this issue. Link: https://github.com/ufukarmagan/primefaces-test

**Comment by melloware** [comment]
Can you add this JS to your application and test it.  It should fix the problem.

```javascript
if (PrimeFaces.widget.OverlayPanel) {
    PrimeFaces.widget.OverlayPanel.prototype.loadContents = function(target) {
        var $this = this,
            options = {
                source: this.id,
                process: this.id,
                update: this.id,
                params: [{
                    name: this.id + '_contentLoad',
                    value: true
                }],
                onsuccess: function(responseXML, status, xhr) {
                    // must show the overlay first so deferred wigets can render
                    $this._show(target);
                    PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
                        widget: $this,
                        handle: function(content) {
                            this.content.html(content);
                            this.loaded = true;
                        }
                    });

                    return true;
                }
            };

        PrimeFaces.ajax.Request.handle(options);
    }
}
```

**Comment by ufukarmagan** [comment]
> Can you add this JS to your application and test it. It should fix the problem.
> 
> ```js
> if (PrimeFaces.widget.OverlayPanel) {
>     PrimeFaces.widget.OverlayPanel.prototype.loadContents = function(target) {
>         var $this = this,
>             options = {
>                 source: this.id,
>                 process: this.id,
>                 update: this.id,
>                 params: [{
>                     name: this.id + '_contentLoad',
>                     value: true
>                 }],
>                 onsuccess: function(responseXML, status, xhr) {
>                     // must show the overlay first so deferred wigets can render
>                     $this._show(target);
>                     PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
>                         widget: $this,
>                         handle: function(content) {
>                             this.content.html(content);
>                             this.loaded = true;
>                         }
>                     });
> 
>                     return true;
>                 }
>             };
> 
>         PrimeFaces.ajax.Request.handle(options);
>     }
> }
> ```

Yes, it fixed the problem, thanks for supporting.

**Comment by tandraschko** [comment]
reopened because still not commited in PF codebase
