### ISSUE TITLE
SelectCheckBoxMenu: Invalid DOM (WCAG conformity)

### ISSUE THREAD

**Issue by tetzla** [primefaces/primefaces#7170]
**Description** 

The serialized DOM of the selectCheckboxMenu component does not fulfill the "Web Content Accessibility Guidelines (WCAG)" (see https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#qr-ensure-compat-parses).

**Reproducibility**

1.	Add bookmarklets "Check serialized DOM of current page" and "Check for WCAG 2.0 parsing compliance" from https://validator.w3.org/nu/about.html to browser favorites.
2.	Open http://www.primefaces.org:8080/showcase/ui/input/checkboxMenu.xhtml.
3.	Run bookmarklet "Check serialized DOM of current page" on this showcase page.
4.	Run bookmarklet "Check for WCAG 2.0 parsing compliance" on the validator page.

I have attached the test results. We are providing web applications for the public sector, therefore WCAG conformity is required (see https://en.wikipedia.org/wiki/Web_Content_Accessibility_Guidelines#European_Union).

**Environment**

 - PF version: 10.0.0
 - Affected browsers: ALL
 
[HTML Check.pdf](https://github.com/primefaces/primefaces/files/6206194/HTML.Check.pdf)

**Comment by melloware** [comment]
PR is welcome

**Comment by melloware** [comment]
These two `label` and `group-label` probably need to be `data` attributes not regular attributes.

**Comment by melloware** [comment]
@tetzla Appreciate the reports.  Keep them coming if you find others!

**Comment by tetzla** [comment]
Thanks for your fast solution!
