### ISSUE TITLE
GMap: Invalid DOM (WCAG Conformity)

### ISSUE THREAD

**Issue by tetzla** [primefaces/primefaces#7172]
**Description**

The serialized DOM of the GMap component does not fulfill the "Web Content Accessibility Guidelines (WCAG)" (see https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#qr-ensure-compat-parses).

**Reproducibility**

1. Add bookmarklets "Check serialized DOM of current page" and "Check for WCAG 2.0 parsing compliance" from https://validator.w3.org/nu/about.html to browser favorites.
2. Open http://www.primefaces.org:8080/showcase/ui/data/gmap/basic.xhtml.
3. Run bookmarklet "Check serialized DOM of current page" on this showcase page.
4. Run bookmarklet "Check for WCAG 2.0 parsing compliance" on the validator page.
5. I have attached the test results (controlwidth/controlheight not allowed on element div). We are providing web applications for the public sector, therefore WCAG conformity is required (see https://en.wikipedia.org/wiki/Web_Content_Accessibility_Guidelines#European_Union).

**Environment**

PF version: 10.0.0
Affected browsers: ALL

[HTML Check.pdf](https://github.com/primefaces/primefaces/files/6210700/HTML.Check.pdf)

**Comment by melloware** [comment]
Unfortunately there is nothing PrimeFaces can fix about this.  This element...
```xml
<div class="gmnoprint gm-bundled-control gm-bundled-control-on-bottom" draggable="false" controlwidth="40" controlheight="113" style="margin: 10px; user-select: none; position: absolute; bottom: 127px; right: 40px;">
```

with the invalid `controlwidth="40" controlheight="113"` is generated by the Google Maps JS code itself and not by Primefaces.  I suggest you open a ticket on the Google Maps issues. You want to go here: https://developers.google.com/maps/support#issue_tracker

And pick the Bug Report for "Maps JavaScript API".

**Comment by tetzla** [comment]
Thanks for the information. I've created a Google bug report.

**Comment by melloware** [comment]
Can you post a link to your ticket here so I can follow it?

**Comment by tetzla** [comment]
https://issuetracker.google.com/issues/183690333

**Comment by melloware** [comment]
Looks like the issue has been moved here and Google has been slowly working on Accessibility issues over the last 3 years.

See: https://issuetracker.google.com/issues/69541792

**Comment by tetzla** [comment]
The Google Maps bug https://issuetracker.google.com/issues/183690333 was fixed. An update of the corresponding Google Maps library would be nice.

**Comment by melloware** [comment]
@tezla that's not up to us right that comes from this library when you load it right?

```xml
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
```

so isnt that just when Google updates it you will get the newest changes?

**Comment by tetzla** [comment]
You're right. It's working automatically. Sorry.
