### ISSUE TITLE
DatePicker: dialog redisplays, if datePicker is updated via ajax request

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#7174]
**Describe the defect**
If the datePicker itself is updated via `<p:ajax event="dateSelect" update="@form"/>`, the date picker dialog doesn't properly hide or seems to open up again instantly. Another click is needed to lose focus and hide the date dialog. This behaviour doesn't happen, if `p:calendar` is used.

![calendarDatepicker](https://user-images.githubusercontent.com/6633403/112666090-12e40180-8e5c-11eb-9b21-0493468c9700.gif)

**Environment:**
 - PF Version: _10_
 - Affected browsers: _ALL_

**Example XHTML**
```
<h:form>
	<p:panelGrid columns="2">
		<h:outputText value="p:calendar" />

		<p:calendar value="#{someBean.selectedDate}">
			<p:ajax event="dateSelect" update="@form" />
		</p:calendar>

		<h:outputText value="p:datePicker" />
		<p:datePicker value="#{someBean.selectedDate}">
			<p:ajax event="dateSelect" update="@form" />
		</p:datePicker>

	</p:panelGrid>
</h:form>
```

**Comment by melloware** [comment]
@zhedar can you try it with `focusOnSelect="true"` so like

```xml
<p:datePicker value="#{someBean.selectedDate}" focusOnSelect="true">
	<p:ajax event="dateSelect" update="@form" />
</p:datePicker>
```

Or with `hideOnDateTimeSelect="true"`...
```xml
<p:datePicker value="#{someBean.selectedDate}" hideOnDateTimeSelect="true">
	<p:ajax event="dateSelect" update="@form" />
</p:datePicker>
```

**Comment by melloware** [comment]
I can't reproduce.
[pf-7174.zip](https://github.com/primefaces/primefaces/files/6213353/pf-7174.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by zhedar** [comment]
Sorry, I should have provided the Java code as well.

This does happen, when a Date without time is used.
try 
`private LocalDate localDate;` instead of `LocalDateTime`
and
```
<p:datePicker value="#{testView.localDate}">
  <p:ajax event="dateSelect" update="@form" />  
</p:datePicker>```

**Comment by melloware** [comment]
Yep I see it now.

**Comment by melloware** [comment]
OK try this script just add it to your project. Make sure you have `focusOnSelect="false"` on your DatePicker.

```javascript
$.prime.datePicker.prototype.onDateSelect = function(event, dateMeta) {
    if (this.options.disabled || !dateMeta.selectable) {
        if (event) {
            event.preventDefault();
        }
        return;
    }

    var $this = this;

    if (this.isMultipleSelection()) {
        if (this.isSelected(dateMeta)) {
            var value = this.value.filter(function(date, i) {
                return !$this.isDateEquals(date, dateMeta);
            });
            this.updateModel(event, value);
        } else if (!this.options.maxDateCount || !this.value || this.options.maxDateCount > this.value.length) {
            this.selectDate(event, dateMeta);
        }
    } else {
        this.selectDate(event, dateMeta);
    }

    if (!this.options.inline && this.isSingleSelection() && (!this.options.showTime || this.options.hideOnDateTimeSelect)) {
        setTimeout(function() {
            $this.hideOverlay();
        }, 100);

        if (this.mask) {
            this.disableModality();
        }
    }

    if (event) {
        event.preventDefault();
    }
}
```

**Comment by melloware** [comment]
Here is a patched reproducer showing its fixed:
[pf-7174.zip](https://github.com/primefaces/primefaces/files/6213675/pf-7174.zip)

**Comment by zhedar** [comment]
I can confirm, that this works great. Thanks for your quick action!

As `focusOnSelect` is `false` by default, this doesn't require any further configuration.
