### ISSUE TITLE
Datepicker: Change event is not called when using mask="true"

### ISSUE THREAD

**Issue by SirError** [primefaces/primefaces#7176]
**Describe the defect**
The ajax "change event" is not called when the date is type istead of being selected.
The behaviour should be the same as the other inputs, the value of the input is changed and the user leaves the field,  the event is called.
Calendar works like this.

**Environment:**
 - PF Version: 10.0
 - JSF + version: _e.g. Mojarra 2.2.14
 - Affected browsers:  ALL_

**To Reproduce**
1. focus datepicker
2. type a date and leave
3. change event is not called

**Expected behavior**
If I change the value of the datepicker typing the date then the ajax method "change" should be called.

**Example XHTML**
```html
<p:datePicker mask="true"
		      value="#{testView.data}"
		      maskSlotChar=" "
		      pattern="dd/MM/yyyy"
		      monthNavigator="true"
		      yearNavigator="true"
		      showIcon="true"
		      showOnFocus="false">
	<p:ajax event="dateSelect" listener="#{testView.onDateSelect()}"/>
	<p:ajax event="change" listener="#{testView.onChange()}"/>		
</p:datePicker>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

	private Date data;

	public void onDateSelect() {
		System.out.println("hi date select");
	}

	public void onChange() {
		System.out.println("hi onChange");
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}
	
}
```
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/6214023/primefaces-test-master.zip)

**Comment by melloware** [comment]
Reproducer: 
[pf-7176.zip](https://github.com/primefaces/primefaces/files/6214110/pf-7176.zip)

**Comment by melloware** [comment]
Can you try it with `mask="false"`.  I think its the mask that is eating the change events.

**Comment by SirError** [comment]
Yeah, you are right, 
with mask="false" it works, 
but I need the mask, :/
would it be possible to keep the mask and have the change event?

**Comment by melloware** [comment]
I have a feeling its a problem with the InputMask component not triggering the change: https://github.com/RobinHerbots/Inputmask/issues

So if I have 10/10/2021 and then I remove the last 1 and make it 2 so 2022 its not triggering the change.  Its like once the mask is complete its not firing a change.

**Comment by melloware** [comment]
The weird part is it seems to be working with this JSFiddle: https://jsfiddle.net/ucatw6k1/1/

**Comment by melloware** [comment]
OK it was a bug in the Plugin. I just tested it with the latest InputMask and its firing every time.  Here is a patched version of your reproducer:
[pf-7176.zip](https://github.com/primefaces/primefaces/files/6223901/pf-7176.zip)

**Comment by SirError** [comment]
> 
> 
> OK it was a bug in the Plugin. I just tested it with the latest InputMask and its firing every time. Here is a patched version of your reproducer:
> [pf-7176.zip](https://github.com/primefaces/primefaces/files/6223901/pf-7176.zip)

Hum, almost.
I noticed that it's calling the event even when I don't change the value.
So, it's acting like "blur" instead of "change"

**Comment by melloware** [comment]
I am not seeing that.  Its only firing your change if the value actually changes?

**Comment by melloware** [comment]
OK I simplified your test case.  the two DatePicker and Calendar both bound to the same listener and value is what was throwing it off.
[pf-7176.zip](https://github.com/primefaces/primefaces/files/6224312/pf-7176.zip)

This simplified test case shows its still not working with just DatePicker.

**Comment by melloware** [comment]
OK its a regression caused by this issue: https://github.com/primefaces/primefaces/issues/6445

@fanste if I flip flop the lines back then the onchange event in this reproducer works.

**Comment by melloware** [comment]
OK I think I have a fix for all scenarios I am working on.

**Comment by melloware** [comment]
OK try this patched version. All fixes are in the `test.js` file.
[pf-7176.zip](https://github.com/primefaces/primefaces/files/6228888/pf-7176.zip)

@fanste This also fixes #6445

**Comment by fanste** [comment]
I will test this in my application as soon as I find some time for it.
Thanks for improving the fix. I totally agree with you (PR message), that no time should be wasted for IE anymore (even our company has switched to MS Edge Chome and our IT is really slow 😉)

**Comment by SirError** [comment]
> 
> 
> OK try this patched version. All fixes are in the `test.js` file.
> [pf-7176.zip](https://github.com/primefaces/primefaces/files/6228888/pf-7176.zip)
> 
> @fanste This also fixes #6445

It's working now, thanks a lot :)

**Comment by fuinhaazulgit** [comment]
Sorry to revive this thread, but this bug is happening to me using 10.0.2 or 10.0.7 version. Both calendar and datepicker is not firing change event if the mask attribute is used. dateSelect event is working fine.

Any sugestions?

**Comment by melloware** [comment]
Can you provide a Test case like above that proves the issue?

**Comment by fuinhaazulgit** [comment]
Never mind. The problem was a js on blur event doing the same thing as mask does, but on previous prime versions it dit not cause any problem.   Thanks!

**Comment by melloware** [comment]
Ok great thanks for reporting back!
