### ISSUE TITLE
DataTable: Add row issue

### ISSUE THREAD

**Issue by raveendrag** [primefaces/primefaces#7183]
Hi 
I am adding data into datatable after adding first row , trying to add with different data but second one overwriting with first one but two rows are created

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
Closing until OP comes back with a reproducer.
