### ISSUE TITLE
DatePicker: rangeSeparator split can conflict with date part separator

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7186]
https://github.com/primefaces/primefaces/blob/4b74f0f75a2beb4a7915a0b12298ebc413b90958/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java#L305-L314

With default range separator and ISO date format you will get the following string value for all days in March 2021 (in this case, Dutch format): `01-03-2021 - 31-03-2021`. Split by `-`:

<img width="700" alt="Screenshot 2021-03-31 at 14 26 37" src="https://user-images.githubusercontent.com/7500178/113144560-aa1ad180-922d-11eb-989e-32d8b8024b9e.png">

Splitting like `submittedValue.split(" " + datePicker.getRangeSeparator() + " ");` will be better, but still not bullet proof

Maybe using `–` (long dash) instead of `-` (regular hash) by default as the range separator? But this makes typing values harder.

**Comment by melloware** [comment]
@Rapster thoughts?

**Comment by melloware** [comment]
What happens if you just use a custom range separator like tilde `rangeSeparator="~"` ??

**Comment by jepsar** [comment]
That's basically what I did to temporarily fix it. I used a long / em hash instead of a regular hash. Try using a regular expression special character as separator ;-)

You can assign this issue to me if you like.

**Comment by melloware** [comment]
Done!
