### ISSUE TITLE
Autocomplete sends change and ItemSelect events concurrently.

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#719]
Hello, 

I use p:autocomplete with ajax events itemSelect and change. If I change text inside input, then autocomplete search results. It's OK. But then I click on item in searched result list and autocomplete sends change and itemSelect events concurrently. If I select item in searched result list by ENTER key, autocomplete sends only itemSelect event. Problem is, that change event sends changed value, not selected.

Thank you
PF Elite 5.2.12, JSF 2.2.12

**Comment by omarbr** [comment]
have a same problem. code to reproduce this bug on forum topic [http://forum.primefaces.org/viewtopic.php?f=3&t=44090](url)

**Comment by m-mchugh** [comment]
I encountered the same problem but was able to resolve it by adding a widgetVar to the autocomplete and then adding the following line to my change action:

onstart="if(PF('yourWidgetVarName').panel.is(':visible')) return false;"

This will return the changed value if the user does not make a selection before leaving the field.  It will suppress the change action and return the selection if the user makes one, either with the mouse or the enter key.

**Comment by markusg80** [comment]
I have the same issue and Workaround it like m-mchugh has descripted before. But for me ist just a Workaround, because this usecase should work without any Workaround. Maybe you can add Attribute like forceSelectionOnChange="true" to fire select Event on Change.

**Comment by mertsincan** [comment]
We decided to trigger the 'change' event of input when item is selected using enter or mouse-click.
