### ISSUE TITLE
DataTable/TreeTable: GlobalFilter not working with filterable="false"

### ISSUE THREAD

**Issue by stefan-dan** [primefaces/primefaces#7193]
**Describe the defect**
Global filter works only on p:column that has atribute `filtarable="true"`, but it should work on every column that has `filterBy=""` atribute.
I have a datatable where I need only the global filter, not the column filters. To disable column filter I use `<p:column filterable="false"/>`, but this breaks the GlobalFilter in PF10, in PF8 it works as expected.
I haven't tested yet, but this may affect treetable too.

**Reproducer**
Clone repository https://github.com/stefan-dan/primefaces-test

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _Mojarra 2.2.8 and MyFaces 2.3.6_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to 'http://localhost:8080/primefaces-test/'
2. Click on 'Global filter _Enter keyword'_
3. Write 'Stefan'
4. Works as expected
5. Write 'Moldova'
6. See error

**Expected behavior**
Expected behaviour: Global filter should work on all p:columns that has atribute filterBy="", despite of filterable="" value.

**Example XHTML**
```html
<p:dataTable var="customer" value="#{dtFilterView.customers1}" widgetVar="customersTable"
                             emptyMessage="No customers found with given criteria"
                             filteredValue="#{dtFilterView.filteredCustomers1}">

                    <f:facet name="header">
                        <div class="p-d-flex p-ai-center p-jc-between">
                            <span>List of Customers</span>
                            <p:inputText id="globalFilter" onkeyup="PF('customersTable').filter()" style="width:10rem" placeholder="Enter keyword" />
                        </div>
                    </f:facet>

                    <p:column headerText="Name" sortBy="#{customer.name}" filterBy="#{customer.name}" filterable="false">
                        <h:outputText value="#{customer.name}" />
                    </p:column>
</p:dataTable>
```

**Comment by melloware** [comment]
interesting. So if it is a global search you want it searching all columns but right now we filter only by active or filterable columns assuming you don't want the others checked.

**Comment by stefan-dan** [comment]
@melloware yes, you can downgrade to PF 8 to see the behaviour I need. Or maybe there is a way to make the column `filterable=true` and to hide the input column filter?

**Comment by melloware** [comment]
Yep you can hide the filters with this CSS.
```css
body .ui-datatable .ui-column-customfilter,
body .ui-datatable .ui-column-filter {
   display: none;
}
```

**Comment by stefan-dan** [comment]
Thank you, it is working. It's possible to know if it will be fixed, or should I apply this workaround?

**Comment by melloware** [comment]
For now I would apply the workaround because I am not sure if the new behavior is actually the correct one. if I mark a column filterable="false" i would expect it to not be involved in filters.    Becuase then how else will user exclude columns from the global filter?  Marking as workaround and for discussion.

**Comment by stefan-dan** [comment]
User can exclude column from global and column filter by removing the `filterBy` attribute. I think that the attribute `filterable` duplicates the meaning of `filterBy` attribute, beacause why you will need to set `filterBy` for a column that you don't want to filter. We can replace `filterable` attribute with something like `columnFilter` or `globalFilter`. But this is only my opinion, thanks for fast reply.

**Comment by melloware** [comment]
because of this example: https://www.primefaces.org/showcase/ui/data/datatable/field.xhtml
Fields sets a whole bunch of defaults and you can turn things off with `filterable="false"` etc.

**Comment by asterisk360-admin** [comment]
I have the same problem.
When enable the global filter dont work as usual, PF 10 force to add filterBy and filtarable for work with global filter
This way add a filterbox in each column and the table have lots of filter boxes.
Im think when you enable the global filter must apply to all columns. if dont need filter one column you can use filtarable="false"

**Comment by asterisk360-admin** [comment]
The way in PF 10 adds more tags in all columns for implement the global filter.
Its lots of work hidding all the filters of columns with css.

I'm think add a parameter "hideFilter" in column will be helpfull.

**Comment by tandraschko** [comment]
yep, we need a param for that. maybe with name:
1) hideFilter
2) globalFilterOnly

Maybe others

**Comment by melloware** [comment]
How about instead of `hideFilter` we use `filterDisplayed` with a default to `true` and you can hide it with `filterDisplayed="false"` that way it starts with the word "filter" so IDE's and our doc pages have it lined up with other filter props?
