### ISSUE TITLE
PieChart: PieChart code from showcase keeps growing when rendered in the browser

### ISSUE THREAD

**Issue by tarwork** [primefaces/primefaces#7194]
**Describe the defect**
We are using PF 10.0. I am trying to run the PieChart example from the Showcase in our app. When the piechart is rendered in the browser it keeps growing in size indefinitely.

**Reproducer**
Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your reproducer here. **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub. Please test with that before reporting a bug that may already be fixed.

**Environment:**
 - PF Version: 10.0
 - JSF + version: Mojarra 2.2.8
 - Affected browsers: ALL

**To Reproduce**
use the exact same code in the Primefaces Showcase for xhtml and backing bean.

**Expected behavior**
The expectation is the pie chart honors the size specified in the call.

**Comment by melloware** [comment]
I don't understand. it doesn't happen in the Showcase here: https://www.primefaces.org/showcase/ui/chartjs/pie.xhtml
So how I am supposed to reproduce your issue if it doesn't happen in the showcase and your instructions are to copy the showcase code?  Can you provide a runnable PF reproducer to show me the issue? 
Provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by christophs78** [comment]
Maybe it‘s in some way related to your surrounding HTML-code. And maybe some CSS assigned to this HTML.

**Comment by tarwork** [comment]
I will try to do a primefaces test project when i have a little more time but let me do a better job of explaining what i have done and what seems to be a work around.

in my xhtml i had something like : 

...
```xml
<p:panel id="chart">
    <p:pieChart model="#{dashboardReportBean.pieModel2}" style="width: 100%; height: 300px;"/>
</p:panel>
```
...

My IDE is Netbeans 8 and I am using JDK 8 with Tomcat version 8.0.27. The backing bean code is exactly like in the showcase. When i run my project and go to the xhtml page the pie chart starts off at height 300px and then grows infinitely ever larger.

On a whim along the same lines as @christophs78 has mentioned I added an old fashioned table wrapped around the p:piechart. So some thing like this : 

...
```xml
<p:panel id="chart">
    <table width="300" ><tr><td>
         <p:pieChart model="#{dashboardReportBean.pieModel2}" style="width: 100%; height: 300px;"/>
    </td></tr></table>
</p:panel>
```
...

all of a sudden the piechart does not grow anymore, it stays the size i specify in the html table. 

It could be something in my code but i have been using roughly the same xhtml template with all types of PF versions from around 6.x and this is the first time a piechart or any pf component has behaved this way (i.e. infinite increase in size on its own) after a pf jar upgrade.

anyway,  i will certainly try to submit a primefaces-test project but until i do hopefully this is a better explanation of what i am seeing than what i posted initially.

**Comment by melloware** [comment]
Can't reproduce. Here is a runnable reproducer.
[pf-7194.zip](https://github.com/primefaces/primefaces/files/6254513/pf-7194.zip)


Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

I don't see the issue.

**Comment by melloware** [comment]
OK this explains it: https://www.chartjs.org/docs/latest/configuration/responsive.html#configuration-options

ChartJS are `responsive=true` by default so they are naturally responding to their container size.

**Comment by tarwork** [comment]
If the Chart.js team decided to have that as a default I can live with that and adapt it to my needs.

Thank you again.

Will close issue as this is not a bug...
