### ISSUE TITLE
FileUpload: onupload + oncancel never called in simple mode, oncancel not called in advanced mode

### ISSUE THREAD

**Issue by kawoolutions** [primefaces/primefaces#7196]
**Describe the defect**
The fileUpload component has an onupload and oncancel callbacks. In simple mode onupload and oncancel are never called. In advanced mode, oncancel is never called, however onupload is.

**Reproducer**

I have forked the PF test repo and created a branch on my own Github account that I will create a PR from...

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _I used the PF test default_
 - Affected browsers: _ALL_

**To Reproduce**

SIMPLE MODE:

1. Go to test.xhtml
2. Open browser debugger and switch to console tab
3. Click on 'Browse...'
4. Select some file and upload OR cancel
5. The messages set in onupload OR oncancel are never logged to the console

ADVANCED MODE:

1. Go to test.xhtml
2. Open browser debugger and switch to console tab
3. Click on 'Choose'
4. Select some file and upload
5. Click on 'Upload' -> console says "ON UPLOAD CALLED!" [OK]
6. Click on 'Choose' again
7. Select some file again and upload
8. Click on 'Cancel' -> no console output "ON CANCEL CALLED!" [BUG?]

**Expected behavior**
In both modes I'd expect the callbacks to be executed.

However, for simple mode, this might not be technically possible at all. It would however be GREAT if there was such a feature in simple mode, too.

**Example XHTML**

test.xhtml from the forked reproducer at https://github.com/kawoolutions/primefaces-test

```html
[code]<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
        <h:outputScript name="test.js" />
    </h:head>
    <h:body>

        <h1>#{testView.string}</h1>
        <h:form id="frmTest">
            <p:fileUpload mode="simple"
                          onupload="console.log('ON UPLOAD CALLED!');"
                          oncancel="console.log('ON CANCEL CALLED!');">
            </p:fileUpload>
        </h:form>

    </h:body>
</html>[/code]```

**Example Bean**

None needed.

**Notes**

If ever fixed, please backport to PF 7.0, because this is the actual version we use at work.

**Comment by kawoolutions** [comment]
A test case PR is here: https://github.com/primefaces/primefaces-test/pull/79

**Comment by melloware** [comment]
It looks like its a misunderstanding of what "cancel" is used for.  IT looks like in Advanced Mode it is called when the AJAX upload "fails".

```javascript
 fail: function(e, data) {
                if (data.errorThrown === 'abort') {
                    if ($this.cfg.resumeContextPath && $this.cfg.maxChunkSize > 0) {
                        $.ajax({
                            url: $this.cfg.resumeContextPath + '?' + $.param({'X-File-Id' : $this.createXFileId(data.files[0])}),
                            dataType: 'json',
                            type: 'DELETE'
                        });
                    }

                    if ($this.cfg.oncancel) {
                        $this.cfg.oncancel.call($this);
                    }
                    return;
                }
```

**Comment by melloware** [comment]
And it looks like according to the documentation the ABORT error is thrown for the fail function which is when we are calling the oncancel.

Doc is right here explaining it: https://github.com/blueimp/jQuery-File-Upload/wiki/API#how-to-cancel-an-upload

**Comment by melloware** [comment]
**onupload** - is called when pressing the Upload button. See: https://github.com/primefaces/primefaces/issues/6396

Example:
```xml
<p:fileUpload listener="#{fileUploadView.handleFileUpload}" 
   mode="advanced" 
   dragDropSupport="false"
   update="messages"
   sizeLimit="100000" 
   fileLimit="3" 
   allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
   validateContentType="true" accept=".gif,.jpg,.jpeg,.png"
   onupload="return confirm('Are you sure?')"/>
```

It gives you a chance to do something like the upload and bring up an "Are you sure?" dialog.

**Comment by kawoolutions** [comment]
Indeed. This is really confusing. Thanks for clearing up a couple of things.
