### ISSUE TITLE
Dialog: Button-Icons not correct width

### ISSUE THREAD

**Issue by Ponferson** [primefaces/primefaces#7199]
**Describe the defect**
Icon-Buttons in Dialog-Footer has not correrct width.
The previously set width is correct and is overwritten by the theme.
The theme has the CSS-class "body .ui-dialog .ui-dialog-footer button" with the attribute "width:auto".
**Reproducer**
Clone repository https://github.com/primefaces/primefaces-test

**Environment:**
 - PF Version: 10.0
 - Affected browsers: ALL

**To Reproduce**
1. Go to http://localhost:8080/primefaces-test/

**Example XHTML**
```html
<p:dialog visible="true" width="200px">
<f:facet name="footer">
	<p:commandButton icon="pi pi-save" />
</f:facet>
</p:dialog>
```

**Comment by melloware** [comment]
This is theme related not PF core related so assigning to @mertsincan.

However you can easily fix this yourself with CSS.
```css
body .ui-dialog .ui-dialog-footer button {
    width: 5em;
}
```
