### ISSUE TITLE
Exporter: Dragged columns incorrect Excel export order

### ISSUE THREAD

**Issue by vulkman** [primefaces/primefaces#7200]
**Steps to reproduce**

* load a DataTable with DataExporter and draggable columns
* drag a table column 
* perform an Excel export

**Expected result**

The Excel file contains the new sequence of column headers with the new sequence of column data.

**Actual result**

The Excel file contains the new sequence of column headers but with the old sequence of column data.

**Comment by melloware** [comment]
I have verified this is an issue and still an issue as far as PF 10.0
