### ISSUE TITLE
Menu: Rendering menus throw ClassCastException if child element is XML comment

### ISSUE THREAD

**Issue by wal-jan** [primefaces/primefaces#7201]
**Describe the defect**
XML comments as child elements of _p:MenuButton_ (and presumably other menu elments) cause a ClassCastException.

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/6265793/primefaces-test.zip)

**Environment:**
 - PF Version: _8.0_ _10.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. mvn clean jetty:run; http://localhost:8080/primefaces-test
2. See error (stacktrace)
```txt
javax.servlet.ServletException: class com.sun.faces.facelets.compiler.UIInstructions cannot be cast to class org.primefaces.model.menu.MenuElement
...
	at org.primefaces.component.tieredmenu.TieredMenuRenderer.encodeElements(TieredMenuRenderer.java:110)
```

**Expected behavior**
A successfully rendered page.

**Example XHTML**
```html
        <h:form id="frmTest">
            <p:menuButton value="Menu">
                <!-- This comment breaks rendering of menu button. -->
            </p:menuButton>
        </h:form>
```

**Example Bean**
N/A

**Comment by wal-jan** [comment]
I've already corrected the child element handling an can provide a PR.

**Comment by melloware** [comment]
Sure please provide we can review!

**Comment by melloware** [comment]
Reproducer: 
[pf-7201.zip](https://github.com/primefaces/primefaces/files/6267393/pf-7201.zip)
