### ISSUE TITLE
Low FPW animations on Firefox

### ISSUE THREAD

**Issue by XakepSDK** [primefaces/primefaces#7203]
**Describe the defect**
Animations have low FPS on Firefox. This happens with all components that have animations

**Reproducer**
1. Open this in Firefox and Chromium or Chrome https://www.primefaces.org/showcase/ui/panel/accordionPanel.xhtml
2. Interact with Accordion elements
3. Growl animation has low FPS https://www.primefaces.org/showcase/ui/message/growl.xhtml
4. https://www.primefaces.org/showcase/ui/multimedia/galleria.xhtml

**Environment:**
 - PF Version: 8.0; 10.0
 - JSF + version: not sure
 - Affected browsers: Firefox
 - 
**Expected behavior**
Animations have same FPS as in Chrome or Chromium

**Comment by tandraschko** [comment]
@mertsincan @sqores  something for PrimeTek, related to latest animation changes

**Comment by XakepSDK** [comment]
> @mertsincan @sqores something for PrimeTek, related to latest animation changes

Oh, i forgot to mention, this was happening with PF 8.0 too

**Comment by melloware** [comment]
OK then these must be Jquery animations because in 10.0 most things switched to CSS animations but if you are seeing this in 8.0 and 10.0 it must be jQuery animations.

**Comment by melloware** [comment]
I am using Firefox 86.0.1 and I am seeing no issues including Growl.  Are you sure the issue is not a plugin you are using in Firefox?

**Comment by XakepSDK** [comment]
Thanks for testing. Looks like it's Firefox profile bug.
I have tested on Firefox 88.0b7
1. With extensions - issue present
2. In safe mode (no extension and customizations enabled) - issue present
3. Fresh profile - no issue
4. Re-created my current profile - no issue
