### ISSUE TITLE
PhotoCam device selection not working

### ISSUE THREAD

**Issue by fumogmbh** [primefaces/primefaces#7210]
Try showcase https://www.primefaces.org/showcase/ui/multimedia/photocam/deviceSelection.xhtml

device selection is not working. Not on pc, not on tablets, not on mobile devices.

```

**Comment by Rapster** [comment]
Any exception?

**Comment by melloware** [comment]
on my machine photocom is just showing a black image.  I think this plugin is not working properly.

**Comment by jepsar** [comment]
Working on macOS!

**Comment by melloware** [comment]
I am using Chrome on Windows 10 and i just get a black screen even though my camera is on and PrimeFaces.org is allowed to use my camera.

**Comment by jepsar** [comment]
Might be the same SSL stuff we experienced with the code scanner in PFE. @fumogmbh does it work when you run the showcase on localhost? @melloware is code scanner working for you?

**Comment by melloware** [comment]
let me try the showcase localhost.

**Comment by melloware** [comment]
OK running locally it works fine.

**Comment by fumogmbh** [comment]
Webcam itself is running online and on localhost as well (it just needs https if not localhost)
Its just the device selection whitch is not working, it freezes on android/chrome or always shows the same camera on iPad etc.

**Comment by fumogmbh** [comment]
sorry, closed this..

**Comment by jepsar** [comment]
Works for me with Android + Chrome as well. @fumogmbh please provide more detailed information, else I don't see this getting resolved.

**Comment by jepsar** [comment]
Relates to https://github.com/primefaces/primefaces/pull/6009 ? I don't get why the JavaScript was modified and no PR was made at https://github.com/jhuckaby/webcamjs Now upgrading will be a pain when new versions are released.

**Comment by fumogmbh** [comment]
Unfortunately I don't have any further information at the moment, I'll keep looking.
I tested it on 5 different android devices, an iPad, 1 android tablet and a pc with windows 10 and 2 webcams. Unfortunately, it didn't work anywhere to switch from the front to the rear or first to the second camera.

**Comment by jepsar** [comment]
Found the issue. The showcase used an unspecific query selector to read the value of the device selector, which matched the locale select element.

**Comment by melloware** [comment]
Excellent work.
