### ISSUE TITLE
AutoComplete: Add option to highlight split query string

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7212]
Our auto complete methods allow you to search on multiple words, split by space. So searching for "pears apples" will match with "apples and pears". I would like to have this as well, as an option, in the query string highlighting. So, "**apples** and **pears**" will be shown.

https://github.com/primefaces/primefaces/blob/4f34341de3ed915d296541c496fb39033727929e/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js#L763-L773

@melloware you can assign me on this

**Comment by melloware** [comment]
Done
