### ISSUE TITLE
Password: ui-state-error, ui-state-disabled doesn't work in PF10

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#7219]
**Describe the defect**
As I see in PasswordRenderer.java, the styleClass attribute never contains classes ui-state-error and ui-state-disabled, because there is not any call the function createStyleClass (InputRenderer.java). Please, fix it to 10.0.1

```
protected void encodeMarkup(FacesContext context, Password password) throws IOException {
        ResponseWriter writer = context.getResponseWriter();
        String clientId = password.getClientId(context);
        boolean toggleMask = password.isToggleMask();

        if (toggleMask) {
            writer.startElement("span", null);
            boolean isRTL = ComponentUtils.isRTL(context, password);
            String positionClass = getStyleClassBuilder(context)
                        .add(Password.STYLE_CLASS)
                        .add(Password.MASKED_CLASS)
                        .add(Password.WRAPPER_CLASS)
                        .add(isRTL, "ui-input-icon-left", "ui-input-icon-right")
                        .build();
            writer.writeAttribute("class", positionClass, null);
        }

        String inputClass = getStyleClassBuilder(context)
                        .add(!toggleMask, Password.STYLE_CLASS)

 // this row can be removed
                        .add(Password.INPUT_CLASS)

//this row should be added
                        .add(createStyleClass(password, Password.INPUT_CLASS)) 
                        .add(password.getStyleClass())
                        .build();
```

**Environment:**
 - PF Version: 10.0.0

**Comment by melloware** [comment]
@sqores @mertsincan another one for 10.0.1

**Comment by melloware** [comment]
Thank for reporting. I was able to remove another line as well as password.getStyleClass is automatically done in that other method.

**Comment by vonnai** [comment]
Yes, you are right, I have checked it now. Thanks for the quick fix and hope for it in 10.0.1 .

**Comment by melloware** [comment]
I just added Integration Tests for this issue as well: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/519891651f6de7a1649d1c5dafb10e45885e40a6

**Comment by vonnai** [comment]
@sqores,  @mertsincan, please, don't forget to add this fix to 10.0.1 ;-) Thank you.

**Comment by vonnai** [comment]
Can anybody or @cagataycivici, @tandraschko explain to me, how you assign labels to defects, please? Some tasks have label 10.0.1, the others have label elite. This bug has still label 11.0.0. So I really don't know what you are able to put in elite 10.0.1, which is the version that I'm waiting for. I have reported 3 defects for pf 10, I think that they have the same priority:

[7139](https://github.com/primefaces/primefaces/issues/7139)  label: elite
[7211](https://github.com/primefaces/primefaces/issues/7211)  label: 10.0.1
[7219](https://github.com/primefaces/primefaces/issues/7219) label: 11.0.0

Thanks for the explanation. This is a little confusing and it demotivates me to report bugs. I am pf-elite customer for 7 years.

**Comment by tandraschko** [comment]
I dont have a relation to Elite as i dont work for PrimeTek. 
@mertsincan @sqores

**Comment by melloware** [comment]
@vonnai your best bet is to sign up for PrimeFaces PRO and that way you can request what goes into Elite releases in a private channel directly to primetek.  Right now these community issues its totally up to PrimeTek to decide what goes in Elite and what is a priority or not.  PRO is the only way you can "force" priority.

**Comment by vonnai** [comment]
@melloware how dangerous is it to use the actual version with all fixes from 10.0.0 which is in the repo now, or should I make fixes on my own? I don't see any benefits of the elite subscription. Many thanks for the previous replies guys.

**Comment by melloware** [comment]
I would say its fairly safe I do it once in a while for my client and put it in my own Nexus private repo if I really need a fix that is not coming for a while like in 11.0.  I would say use at your own risk but I am fairly confident what is in master is always pretty solid especially now that we have more integration test coverage.

**Comment by buunsal** [comment]
> Can anybody or @cagataycivici, @tandraschko explain to me, how you assign labels to defects, please? Some tasks have label 10.0.1, the others have label elite. This bug has still label 11.0.0. So I really don't know what you are able to put in elite 10.0.1, which is the version that I'm waiting for. I have reported 3 defects for pf 10, I think that they have the same priority:
> 
> [7139](https://github.com/primefaces/primefaces/issues/7139) label: elite
> [7211](https://github.com/primefaces/primefaces/issues/7211) label: 10.0.1
> [7219](https://github.com/primefaces/primefaces/issues/7219) label: 11.0.0
> 
> Thanks for the explanation. This is a little confusing and it demotivates me to report bugs. I am pf-elite customer for 7 years.

Hi,

"elite" labels show that it is still in the planning phase. The tags we have added such as "10.0.2" show which elite version it was added. This fix is included in the elite version, which will be released tomorrow. Thanks for the PR @melloware

**Comment by melloware** [comment]
Yep so "elite" is how we mark one that we think should be in the next Elite release.

Once @mertsincan or @sqores actually merges that fix into an Elite release you remove the Elite label and add 10.0.2 label or whatever elite releases it is in.
