### ISSUE TITLE
SelectBooleanButton: make onLabel/offLabel attributes optional

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7222]
Currently, p:selectBooleanButton requires the attributes onLabel/offLabel. Could you please makes these attributes optional and use the default labels true/false in that case.

This would help to quickly migrate SelectOneCheckboxes by simply replacing h:selectBooleanCheckbox by p:selectBooleanButton.

**Comment by melloware** [comment]
I don't like "True" and "False" as defaults plus we would have to make these IL8N labels so it could be tweaked per Locale.

And you can already control this yourself by using Global Attributes like this:
https://primefaces.github.io/primefaces/10_0_0/#/core/globalattributes

```java
if (component instanceof SelectBooleanButton) {
   final SelectBooleanButton button = (SelectBooleanButton) component;
   button.setOnLabel("On");
   button.setOffLabel("Off");
}
```
No change to PF needed.

**Comment by tuerker** [comment]
the global attributes have a major disadvantage: the IDE then shows everywhere the missing attributes. i know one can also configure the settings accordingly that this is suppressed. but in any case this has to be done by any developer. therefore, i am in favor having default cases which do not cause any additional work if the default case does the job.

of course, the ideal solution would map true/false to corresponding IL8N labels redefinable in messages.properties.

**Comment by jepsar** [comment]
I usually create custom tags to handle stuff like that. Downside is that you might need to create a lot of properties, depending on the tag.

**Comment by melloware** [comment]
My vote is -1 on this.  Lets see what others have to say.

**Comment by jepsar** [comment]
Yeah, think so too. Another pro of using custom tags by the way is being able to easily switch between components. If you even decide a `p:switch` is a better option, you only have to change it in your custom tag. I usually create a tag per data type for inputs and table columns.

**Comment by tandraschko** [comment]
I think we could do it like:

```
primefaces.datatable.SORT_ASC = Ascending
primefaces.datatable.SORT_DESC = Descending
```

via Messages

true/false is really something global

**Comment by melloware** [comment]
> the global attributes have a major disadvantage: the IDE then shows everywhere the missing attributes. i know one can also configure the settings accordingly that this is suppressed. but in any case this has to be done by any developer. therefore, i am in favor having default cases which do not cause any additional work if the default case does the job.
> 
> of course, the ideal solution would map true/false to corresponding IL8N labels redefinable in messages.properties.

@tuerker No matter what solution your IDE is going to complain about them missing because they are marked as required in the TagLib.  So we would have to make them not required in the TagLib as well. But if you use a Custom tag you could mark them not required in your taglib.xml for your custom tag.

```xml
        <attribute>
            <description>
                <![CDATA[]]>
            </description>
            <name>onLabel</name>
            <required>true</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <description>
                <![CDATA[]]>
            </description>
            <name>offLabel</name>
            <required>true</required>
            <type>java.lang.String</type>
        </attribute>
```

**Comment by melloware** [comment]
I am working on a PR for this now.

**Comment by tuerker** [comment]
great. many thanks again.

**Comment by melloware** [comment]
@tuerker please review my new change: https://github.com/primefaces/primefaces/issues/7963

**Comment by tuerker** [comment]
@melloware: it looks like that it is working as before in 10.0 

when the onLabel/offLabel are missing, then the button is empty.

```
      <h5>No onLabel/offLabel</h5>
      <p:selectBooleanButton style="width:6rem"/>

      <h5>Basic</h5>
      <p:selectBooleanButton onLabel="Yes" offLabel="No" style="width:6rem"/>

      <h5>With Icon</h5>
      <p:selectBooleanButton onLabel="Yes" offLabel="No"
                             onIcon="pi pi-check" offIcon="pi pi-times" style="width:6rem" />

      <h5>Icon Only</h5>
      <p:selectBooleanButton onIcon="pi pi-check" offIcon="pi pi-times" />

```

delivers

![Screenshot from 2021-10-30 02-50-24](https://user-images.githubusercontent.com/10051373/139514381-eedbab7c-c199-45fb-b6d5-83b16464a0d5.png)

**Comment by melloware** [comment]
Fixed and integration test added.

**Comment by tuerker** [comment]
great. this one fixed it.
