### ISSUE TITLE
SelectOneMenu: empty string becomes null and triggers valuechangelistener 

### ISSUE THREAD

**Issue by clockwiser** [primefaces/primefaces#7224]
**Describe the defect**
trigger valuechangelistener when there is no change
**Reproducer**
1. Select blank option from selectonemenu.
2. Submit the form data which causes some validation error after submitted to server side bean.
3. Submit again with the blank option of selectonemenu.
4. No change of selection from selectonemenu, but triggers valuechangelistener with newvalue = null and oldvalue="".

**Environment:**
 - PF Version: _8.0_
 - JSF + version: Mojarra 2.2
 - ALL_

**Expected behavior**
At the step 4, the newvalue should be "" and no triggering of valuechangelistener.

```
1. Empty string is converted to null here.
com.sun.faces.renderkit.html_basic.MenuRenderer:convertSelectOneValue()
2. But null is converted to empty string and updated to the bean.
org.apache.el.lang.ELSupport:coerceToString()

The conversion between null and empty string is inconsistent.

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by clockwiser** [comment]
Get around using p:ajax's listener which works fine.
