### ISSUE TITLE
ContextMenu: Datatable long touch is not working on iPad

### ISSUE THREAD

**Issue by naofireblade** [primefaces/primefaces#7225]
Datatable Context Menu is not working on iPad. Issue #6776 fixed it for iPhone but the Context Menu still does not open on iPad (Air 2020 iPadOS 14.4.2)

**Reproducer**
The example shown in PF Showcase is not working on iPad too.
https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

**Environment:**
 - PF Version: 10.0.0
 - JSF 2.2
 - Affected browsers: iPad OS

**To Reproduce**
1. Go to 'https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml' with iPad
2. Touch & Hold on row to see context menu
3. Text selection mode is started instead of showing context menu

**Expected behavior**
Datatable context menu should be shown with Touch & Hold action on iOS.

**Example XHTML**
All source coding is exist at page => https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

**Comment by naofireblade** [comment]
The problem is that `PrimeFaces.env.ios` is false on iPad:
```
{"touch":true,"ios":false,"browser":{"safari":true,"version":"605.1.15","versionNumber":14,"mac":true,"desktop":true,"webkit":true,"name":"safari","platform":"mac"}}
```

This is the result of `window.navigator.userAgent` on iPad:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
```

**Comment by naofireblade** [comment]
Apple messed up the User Agent on iPad OS: https://developer.apple.com/forums/thread/119186

**Comment by melloware** [comment]
Hey this is great research and much appreciated for the fix!
