### ISSUE TITLE
ContextMenu: Selection is not performed and contextMenu event is not fired on iOS

### ISSUE THREAD

**Issue by naofireblade** [primefaces/primefaces#7228]
**Describe the defect**
When opening the context menu on iOS the row (datatable) or node (tree) is not selected. Therefore you have to tap the row first to select it and hold to open the context menu afterwards.
The ajax event contextMenu is not fired as well.

**Reproducer**
The example shown in PF Showcase is not working on IOS too.
https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

**Environment:**
- PF Version: 10.0.0
- JSF 2.2
- Affected browsers: iOS

**To Reproduce**
1. Go to 'https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml' with iOS device
2. Touch & Hold on row to see context menu
3. Context Menu opens but row is not selected

**Expected behavior**
Row should be selected when opening the context menu like on desktop devices. Event contextMenu should be fired like on desktop.

**Example XHTML**
All source coding is exist at page => https://www.primefaces.org/showcase/ui/data/datatable/contextMenu.xhtml

**Comment by naofireblade** [comment]
The problem does not occur on Android devices.

**Comment by melloware** [comment]
Since you have been debugging any insight on this problem as to why it doesn't select the row?

**Comment by naofireblade** [comment]
Not yet, but I'm planning to find a solution in the next weeks.

**Comment by melloware** [comment]
This is working fine for me on the latest iOS 15
