### ISSUE TITLE
Responsive Dialog Framework support

### ISSUE THREAD

**Issue by jederfreitas** [primefaces/primefaces#723]
Primefaces 5.3.RC1 does not support it?

Possible code params that i did and it does not works:

```
    Map<String,Object> options = new HashMap<String, Object>();

    options.put("modal",        true);
    options.put("resizable",    false);
    options.put("width",        780);
    options.put("contentWidth", 738);
    options.put("responsive",   true);

    RequestContext.getCurrentInstance().openDialog("/cadastros/pesquisa/pesquisarmaquina.xhtml", options, null);
```

**Comment by mertsincan** [comment]
PrimeFaces 5.3 doesn't support 'responsive' feature on DF. We can add this feature in 5.3.x and 5.4.

**Comment by cagataycivici** [comment]
Set to 5.4.

**Comment by LuisGustav0** [comment]
Boa tarde Çağatay Civici!
Ja tem previsão quando vai lançar a 5.4?

**Comment by jederfreitas** [comment]
@cagataycivici it will not be released?in 6.0 milestone?

**Comment by tandraschko** [comment]
6.0 is already released since some months ;) It seems there are no plans for it currently.

**Comment by andyserrato** [comment]
Any news on this one ?
