### ISSUE TITLE
DataTable: using ui:decorate inside the datatable component

### ISSUE THREAD

**Issue by rabiter** [primefaces/primefaces#7231]
**Describe the defect**
Neither "decorate" nor "include" can be used inside a datatable if an EL they use is based on a datatable row variable (see the code example below)

**Reproducer**
primefaces-test application is attached
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/6317431/primefaces-test-master.zip)

**Environment:**
 - PF Version: all
 - JSF + version: both mojarra and myfaces
 - Affected browsers: not relevant

**Example XHTML**
```html
<p:dataTable id="products" var="product" value="#{dtColumnsView.products}">
    <p:columns value="#{dtColumnsView.columns}" var="column" columnIndexVar="index">
        <f:facet name="header">#{column}</f:facet>

        <!-- ERROR ! #{product.facelet} is evaluated to null when used in decorate -->      
        <!-- I'm wondering if there is a workaround... -->
        <!-- the idea is to let cells decide on thier own what content to render by specifying the facelet path -->       
        <ui:decorate template="#{product.facelet}"/>
  
    </p:columns>
</p:dataTable>
```

I'm not sure if this is a bug, but still wondering if there is a workaround? The idea I tried to achieve was to let cells to define the content they want to render by specifying a facelet path.

**Comment by melloware** [comment]
This is a question for @tandraschko I have no idea if this scenario is valid or whether Datatable can support this.

**Comment by tandraschko** [comment]
no idea, sorry. never used decorate, no idea if it should work

**Comment by rabiter** [comment]
yeah, thanks anyway, Closing the ticket then.
