### ISSUE TITLE
DataTable: not working filterBy & sortBy in dynamic columns (p:columns)

### ISSUE THREAD

**Issue by sasynkamil** [primefaces/primefaces#7232]
**Describe the defect**
Filtering & sorting is not working for dynamic columns p:columns in p:dataTable. Sorting does not trigger sorting. And filtering result is always empty table.

Followed Dynamic Columns in PF 8 & 10 showcase and [doc](https://primefaces.github.io/primefaces/10_0_0/#/components/datatable)

(Note: If I enter "A" or "a" to the filtering input box above string column, nothing happen (data stays in the table), for any other character or world filtering is resulting in empty table).

**Reproducer**
PrimeFaces test (PF10) project attached: [primefaces-test-10.zip](https://github.com/primefaces/primefaces/files/6322972/primefaces-test-10.zip)

**Environment:**
 - PF Version: 8.0, 8.0.4, 10.0.0, Snapshot (2021-04-15)
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: ALL
 - STATE_SAVING_METHOD: server or client

**To Reproduce**
First column in attached project is static (p:column), others are dynamic (p:columns).
Click on sorting icon.
Enter some char or chars to filter data.

**Expected behavior**
Sorting, filtering.

**Example XHTML**
```html
    <h:form id="frmTest">

        <p:dataTable value="#{dynamicColumnsView.products}" var="product"
                     emptyMessage="No Data Available">

            <p:column field="id" headerText="Id static"
                      filterMatchMode="contains"
                      sortBy="#{product.id}"
                      filterBy="#{product.id}">
                <h:outputText value="#{product.id}"/>
            </p:column>

            <p:columns value="#{dynamicColumnsView.columns}" var="column"
                       filterMatchMode="contains"
                       sortBy="#{column.property}"
                       filterBy="#{column.property}">
                <h:outputText value="#{product[column.property]}"/>
            </p:columns>

        </p:dataTable>

    </h:form>
```

**Example Bean**
```java
@Data
@AllArgsConstructor
public class Product implements Serializable {
    private long id;
    private String name;
    private Integer quantity;
    private LocalDateTime date;
}
```

```java
@Data
@Named
@ViewScoped
public class DynamicColumnsView implements Serializable {
    private List<Product> products = new ArrayList<>();
    private List<ColumnModel> columns = new ArrayList<>();

    @PostConstruct
    protected void initialize() {
        Product product;
        product = new Product(1001, "Audi", 5, LocalDateTime.now());
        products.add(product);
        product = new Product(1002, "BMW", 3, LocalDateTime.now().minusDays(30));
        products.add(product);
        product = new Product(1003, "Toyota", 7, LocalDateTime.now().minusDays(100));
        products.add(product);

        createDynamicColumns();
    }

    private void createDynamicColumns() {
        ColumnModel column;
        column = new ColumnModel("Identifier", "id");
        columns.add(column);
        column = new ColumnModel("Name", "name");
        columns.add(column);
        column = new ColumnModel("Quantum", "quantity");
        columns.add(column);
        column = new ColumnModel("When", "date");
        columns.add(column);
    }

    static public class ColumnModel implements Serializable {
        private String header;
        private String property;

        public ColumnModel(String header, String property) {
            this.header = header;
            this.property = property;
        }

        public String getHeader() {
            return header;
        }

        public String getProperty() {
            return property;
        }
    }
}
```

**Comment by melloware** [comment]
Hmm it seems to be working on the Showcase?  Can you check what is different between yours and the showcase?

See: https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml?

**Comment by melloware** [comment]
OK I have your test case working if you change your dynamic columns to use `field` like the showcase exmaple like this...
```xml
<p:columns value="#{dynamicColumnsView.columns}" var="column" field="#{column.property}">
    <h:outputText value="#{product[column.property]}"/>
</p:columns>
```

**Comment by sasynkamil** [comment]
Ok, thx for investigation (I was focusing on version & doc v8) . I can see that this `field` is new feature in v10 doc: 

- Ajax based filtering is enabled by setting field or filterBy at column level

And I verified that this `field` alternative is working in v10 for filtering, but sorting does not work.
So for v8.0 - v8.0.4 this `field` is not supported and sortBy & filterBy is broken.

**Comment by melloware** [comment]
I just tested this runnable example: 
[pf-7232.zip](https://github.com/primefaces/primefaces/files/6335680/pf-7232.zip)

Sorting and filtering work fine in v10.0.0.  You are reporting Sorting is not working?  Can you try my reproducer?

**Comment by sasynkamil** [comment]
I tested project 'pf-7232.zip' as it is (master-SNAPSHOT, dynamic p:columns, field) and sorting and filtering is working correctly. But when I change project from 'server' to 'client', then sorting stops working (also sorting for normal p:column stops working). Filter is working with both settings 'server' or 'client' correctly.

    <context-param>
        <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
        <param-value>client</param-value>
    </context-param>

Looks this is already reported: https://github.com/primefaces/primefaces/issues/6987

**Comment by tandraschko** [comment]
Then lets close this one here

**Comment by sasynkamil** [comment]
Ok, so I understand that filterBy & sortBy in v8 will not be fixed.

**Comment by tandraschko** [comment]
mixed p:column / p:columns are not supported in V8
thats a new feature in V10

**Comment by sasynkamil** [comment]
Interesting - we have using mix of p:column & p:columns since v5.

**Comment by tandraschko** [comment]
might work for basis usages yup but we did heavily refactoring in V10, to support this for sort/filter correclty

**Comment by tandraschko** [comment]
and fixing bugs in elite is up to PrimeTek (CC @sqores @mertsincan)
i dont think they can easily backport it.

**Comment by sasynkamil** [comment]
Ok. I verified in simple vanilla PF project that if both p:column & p:columns are present in v8:
1) sorting is working for all columns
2) filtering is working just for p:columns

Noted differences in `sortBy` and `filterBy` values: `#{product[column.property]}` and not `#{column.property}`.
```html
        <p:dataTable value="#{dynamicColumnsView.products}" var="product">

            <p:column headerText="IdA"
                      sortBy="#{product.id}"
                      filterBy="#{product.id}"
                      filterMatchMode="contains">
                <h:outputText value="#{product.id}"/>
            </p:column>

            <p:columns value="#{dynamicColumnsView.columns}" var="column"
                       sortBy="#{product[column.property]}"
                       filterBy="#{product[column.property]}"
                       filterMatchMode="contains">
                <f:facet name="header">
                    #{column.header}
                </f:facet>
                <h:outputText value="#{product[column.property]}"/>
            </p:columns>

        </p:dataTable>
```
