### ISSUE TITLE
Change the deprecated BigDecimal.ROUND_DOWN

### ISSUE THREAD

**Issue by tsobis** [primefaces/primefaces#7236]
Since the world is moving away from java 8 little by little how about I change the deprecated BigDecimal.ROUND_DOWN with RoundingMode.DOWN for scaling of BigDecimals?

**Comment by melloware** [comment]
Since RoundingMode has been available since 7 I think then yes I think its safe to change to `RoundingMode.DOWN`.

**Comment by melloware** [comment]
Thanks for the PR.  I should have caught this myself when I added this code. 😄

**Comment by tsobis** [comment]
It was helpful to me to check the process of giving back to the project.
