### ISSUE TITLE
SelectCheckboxMenu: Attribute emptyLabel is ignored

### ISSUE THREAD

**Issue by Microbobs** [primefaces/primefaces#7241]
**Describe the defect**
Using the SelectCheckboxMenu with the attribute emptyLabel set still results in displaying the label text when there is no selection. I couldnt find a related issue, so i created this one.

**Reproducer**
https://github.com/Microbobs/primefaces-test

**Environment:**
 - PF Version: 10.0.0
 - JSF + version: Mojarra 2.2.x
 - Affected browsers:  ALL

**To Reproduce**
1. Open http://localhost:8080/primefaces-test/
2. Check the displayed label when there is no selection

**Expected behavior**
It is expected to display the emptyLabel (here: "Test")
![image](https://user-images.githubusercontent.com/43138453/115665965-3d828680-a344-11eb-86ee-32cf0085f4e3.png)

**Example XHTML**
```html
<h:form id="frmTest">
   <p:selectCheckboxMenu id="cityOutput" label="Cities" emptyLabel="Test" updateLabel="true" value="#{testView.selectedCities}" multiple="true"
                                  filter="true" disabled="true" styleClass="disabled-selectCheckboxMenu">
                <f:selectItems value="#{testView.cities}"/>
    </p:selectCheckboxMenu>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private String[] selectedCities;
    private List<String> cities;
    
    @PostConstruct  
    public void init() {
        string = "Welcome to PrimeFaces emptyLabel Test!!!";

        cities = new ArrayList<>();
        cities.add("Miami");
        cities.add("London");
        cities.add("Paris");
        cities.add("Istanbul");
        cities.add("Berlin");
        cities.add("Barcelona");
        cities.add("Rome");
        cities.add("Brasilia");
        cities.add("Amsterdam");
    }
}
```

**Comment by melloware** [comment]
See: https://primefaces.github.io/primefaces/10_0_0/#/components/selectcheckboxmenu?id=attributes

try adding `updateLabel="true"` and let me know if that does it?  The emptyLabel is only used if that updateLabel property is true.

**Comment by Microbobs** [comment]
Hi,
thanks for your reply. I missed that part when recreating the issue in the primefaces-test environment. It works fine there now. I guess the mistake must be within my actual project. I'll try to reproduce it.

**Comment by Microbobs** [comment]
I updated the test-repo. The issue seems to be linked with "multiple=true".

**Comment by melloware** [comment]
That is correct that option is specifically not designed for `multiple` mode. See the snippet below.

```javascript
if (!this.cfg.multiple) {
    if (this.cfg.updateLabel) {
       this.updateLabel();
    }
}
```

**Comment by torshid** [comment]
@melloware is there a reason why we can't use the `emptyLabel` with the `multiple` mode? The documentation does not specify anything.

Is there currently a way for displaying a placeholder when there is no selection in `multiple` mode, which would be different than the `label` attribute?

Thanks.

**Comment by melloware** [comment]
@torshid the component actually renders two different sets of HTML based single mode or multiple mode.  So the label is for single mode.

Let me re-open this ticket and mark it as an enhancement request to show the label in multiple mode.

**Comment by torshid** [comment]
Excellent, thanks.
