### ISSUE TITLE
AutoComplete (dropdown="true"): Accessibility of button

### ISSUE THREAD

**Issue by javiermiraticarum** [primefaces/primefaces#7244]
**Describe the defect**
According to WCAG criterion 4.1.2 all buttons must have an accessible name.

**Environment:**
 - PF Version: _8.0_
 - Affected browsers: _ALL_

**Expected behavior**
The button must have a text in the span ui-button-text or in an aria- * attribute
which could be entered in an attribute of the component.

**Example HTML**
Current 
```html
<button class="ui-autocomplete-dropdown ui-button ui-widget ui-state-default ui-corner-right ui-button-icon-only"
	type="button" role="button" aria-disabled="false">
	<span class="ui-button-icon-primary ui-icon ui-icon-triangle-1-s"/>
	<span class="ui-button-text">&nbsp;</span>
</button>
```
Expected
```html
<button class="ui-autocomplete-dropdown ui-button ui-widget ui-state-default ui-corner-right ui-button-icon-only"
	type="button" role="button" aria-disabled="false" aria-label="Show options">
	<span class="ui-button-icon-primary ui-icon ui-icon-triangle-1-s"/>
	<span class="ui-button-text">Show options</span>
</button>
```

**Comment by melloware** [comment]
Wouldn't just `aria-label="Show options"` be enough with no need to change the `ui-button-text` ?

**Comment by javiermiraticarum** [comment]
> 
> 
> Wouldn't just `aria-label="Show options"` be enough with no need to change the `ui-button-text` ?

Yes, one of the two options is enough.

**Comment by melloware** [comment]
OK PR Submitted for new `dropdownAriaLabel="Show Options"` attribute with server side property default.
