### ISSUE TITLE
LinkButton: Style regression

### ISSUE THREAD

**Issue by juceda** [primefaces/primefaces#7245]
**Describe the defect**
With latest commit b5b4ee432ed131cc88acc42cd419680fa8331a8e, now class ui-button-text-icon-right are added always on text-only buttons without icon.

**Reproducer**
Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your reproducer here. **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub. Please test with that before reporting a bug that may already be fixed.

**Environment:**
 - PF Version: _10_
 - Affected browsers: ALL

**To Reproduce**
1. Just create LinkButton with value (text) and without icon.
2. See how the text are not centered, and it's like to the left

**Expected behavior**
Text should be centered with no "padding" at right when no icon is specified.  Therefore ui-button-text-icon-right is wrongly added.

**Example XHTML**
```html
 <p:linkButton outcome="productDetail" value="Bookmark" style="margin-right:20px;">
        <f:param name="productId" value="10"/>
    </p:linkButton>
```

You can check also on PrimeFaces doc.. the showcase is showing the same behavior:
   https://www.primefaces.org/showcase/ui/button/linkButton.xhtml?jfwid=873c7

As an additional comment / FIX:
Code were changed from:
```
if (value != null && !LangUtils.isValueBlank(icon)) {
            styleClass = getIconPos().equals("left") ? HTML.BUTTON_TEXT_ICON_LEFT_BUTTON_CLASS : HTML.BUTTON_TEXT_ICON_RIGHT_BUTTON_CLASS;
        }
```
to
```
                    .add(isTextAndIcon && "left".equals(linkButton.getIconPos()), HTML.BUTTON_TEXT_ICON_LEFT_BUTTON_CLASS, HTML.BUTTON_TEXT_ICON_RIGHT_BUTTON_CLASS)

```
which is **NOT** the same.. since third parameter on add is the "default value" i guess. So when the condition is not true, HTML.BUTTON_TEXT_ICON_RIGHT_BUTTON_CLASS is added always.

**Comment by melloware** [comment]
Thank you for reporting....PR submitted.
