### ISSUE TITLE
Tree: CSS customization when dropRestrict=sibling is enable

### ISSUE THREAD

**Issue by zakhdar** [primefaces/primefaces#7248]
**Description**

When drag&drop is activated on a p:tree with the dropRestrict = sibling attribute, when we click on a node to move it, it would be interesting to change the color of the drop point if it is a valid drop point or not, that would allow for a more intuitive interaction.

**Describe the solution you would like**
A solution would be to have a attribute like  siblingClass when we can define for example the color of drop point if drag&drop is authorized or not 

Example when drag&drop is in same parent node

![image](https://user-images.githubusercontent.com/56843747/115738309-76d6e880-a37c-11eb-82a0-c366173187be.png)
Example when drag&drop is out of parent node

![image](https://user-images.githubusercontent.com/56843747/115738638-bf8ea180-a37c-11eb-9d88-d7af295265cb.png)

**Comment by melloware** [comment]
This is pretty tricky since PF doesn't evaluate whether the drop is allowed until AFTER you actually drop the node.
```javascript
/**
     * After a drag&drop, validates if the drop is allowed.
     * @private
     * @param {JQuery} dragNode Node that was dragged.
     * @param {JQuery} dropPoint Element where the node was dropped.
     * @return {boolean} Whether the drop is allowed.
     */
    validateDropPoint: function(dragNode, dropPoint) {
        //dropped before or after
        if(dragNode.next().get(0) === dropPoint.get(0)||dragNode.prev().get(0) === dropPoint.get(0)) {
            return false;
        }

        //descendant of dropnode
        if(dragNode.has(dropPoint.get(0)).length) {
            return false;
        }

        //drop restriction
        if(this.cfg.dropRestrict) {
            if(this.cfg.dropRestrict === 'sibling' && dragNode.parent().get(0) !== dropPoint.parent().get(0)) {
                return false;
            }
        }

        return true;
    },
```

So it will be tough to preemptively tell its not allowed to drop and change the `helper` css to a different style.  At least not without some major rework of the tree drag and drop.

**Comment by melloware** [comment]
Going to mark this as won't fix only because it is not currently possible
