### ISSUE TITLE
MenuButton  does not expand when we have ui:include in the same xhtml

### ISSUE THREAD

**Issue by zakhdar** [primefaces/primefaces#7250]
**Describe the defect**
p:menuButton does not expand when whe have ui:include in the same xhtml

**Reproducer**
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" 
xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html">
<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>
	<h:form>
		<p:menuButton  id="menu" value="test">
			<p:menuitem value="foo" />
			<p:menuitem value="bar" />
		</p:menuButton>
		<ui:include src="blank.xhtml" />
	</h:form>
</h:body>
</html>
```

blank.xhtml 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:f="http://xmlns.jcp.org/jsf/core" 
xmlns:h="http://xmlns.jcp.org/jsf/html" 
xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
xmlns:p="http://primefaces.org/ui"
xmlns:o="http://omnifaces.org/ui">
</html>
```

just try to click on the menu , nothing happens even in web console (no javascript event / error)

but if you remove this line `<ui:include src="blank.xhtml" />` it's work fine.

**Environment:**
 - PF Version: 10
 - JSF + version: Mojarra 2.3.14.SP02
 - AS : Wildfly 22
 - Affected browsers: Firefox
 - Java version :  "11.0.9" 2020-10-20 LTS

**Comment by melloware** [comment]
Works fine for me.  reproducer:
[pf-7250.zip](https://github.com/primefaces/primefaces/files/6359748/pf-7250.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by zakhdar** [comment]
Hi @melloware , 

I tested your reproducer and it's work fine. 
i will try to make a complete reproducer and post it for further research.

thanks for your support.

**Comment by melloware** [comment]
No problem just post back if you can or can't reproduce.  I have a feeling your issue is your DOCTYPE.  Look at my blank.xhtml vs yours.

**Comment by zakhdar** [comment]
You are right when I use your "blank" file with my project it works, but what seems strange to me if I use my version of the "blank" file on your reproducer it works also.
Just for my information do you think this is due to Mojarra version or application server (i am using WildFly)?

**Comment by melloware** [comment]
could be a bunch of things or even Firefoz not liking the DocType could be anything.
