### ISSUE TITLE
Spinner: without thousands and decimals separator

### ISSUE THREAD

**Issue by leosj29** [primefaces/primefaces#7252]
> > You can already do this now.
> > ```
> >  <p:spinner id="basic" value="#{spinnerView.number1}" decimalSeparator="" thousandSeparator=""/>
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/4399574/111869466-13f5ca00-8956-11eb-95eb-1781bc778563.png)
> > And if you wanted to do this for all your spinners you can set it globally like this: https://primefaces.github.io/primefaces/10_0_0/#/core/globalattributes
> 
> By default, before version 8 it did not generate the separators. I think that for compatibility reasons the separators should appear if indicated by the developers and not have to remove them as indicated above.

I tried to use the properties as you mentioned above, but when submitting the form it generates error.

![Selection_586](https://user-images.githubusercontent.com/2030440/115800293-8dd70400-a397-11eb-91ac-b2c3967a59c2.png)
And when sending the form it generates
![Selection_585](https://user-images.githubusercontent.com/2030440/115800360-ae9f5980-a397-11eb-85c4-67a883b649f4.png)

The code is

> > ```
> ><h:form>            
> >   <p:spinner id="basic" 
> >         value="#{dtFilterView.number1}"
> >         decimalSeparator=""
> >         thousandSeparator=""/>  
> >    <br/>
> >   <p:commandButton ajax="false"
> >         value="Send" 
> >         icon="ui-icon-disk"
> >         action="#{testView.save}" />
> > </h:form>
> > ```

_Originally posted by @leosj29 in https://github.com/primefaces/primefaces/issues/7144#issuecomment-825286572_

**Comment by melloware** [comment]
Reproducer is working fine for me:
[pf-7252.zip](https://github.com/primefaces/primefaces/files/6364784/pf-7252.zip)

Rune `mvn clean jetty:run` and go to http://localhost:8080/primefaces-test/test.xhtml

**Comment by leosj29** [comment]
> Reproducer is working fine for me:
> [pf-7252.zip](https://github.com/primefaces/primefaces/files/6364784/pf-7252.zip)
> 
> Rune `mvn clean jetty:run` and go to http://localhost:8080/primefaces-test/test.xhtml

Yes, the code works very well, the problem gives if you add the property decimalSeparator = "".
I added it and it causes the mentioned error.

Add the property decimalSeparator = ""

![Selection_587](https://user-images.githubusercontent.com/2030440/115878523-e0e7a000-a405-11eb-9115-4e540487a5ec.png)

**Comment by melloware** [comment]
But why are you adding it if you want an Integer value?  You should just leave it out like my reproducer?

**Comment by leosj29** [comment]
> But why are you adding it if you want an Integer value? You should just leave it out like my reproducer?

I think the problem is not that it is an integer value or not. The problem it is specifying that empty property. But if you think that this is how it should work, then I agree with it.

**Comment by melloware** [comment]
Yeah I guess I am trying to figure out a use case where this matters?

**Comment by melloware** [comment]
Integration Test proving the bug: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/124b982fe0e59b489f0bcfc517097b1e2de64623

**Comment by melloware** [comment]
@leosj29 Fixed for 11.0 thanks for reporting!
