### ISSUE TITLE
InputText and InputTextarea: Let the counter count bytes instead of characters

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#7253]
**Description**
I needed the counter in the textarea to count bytes instead of characters. 
I providing a PR as may be some one else find it usefull.
The countBytesAsChars feature is borrowed from the word count plugin for the ckeditor.

**Comment by OBreidenbach** [comment]
PR https://github.com/primefaces/primefaces/pull/7254

**Comment by OBreidenbach** [comment]
@melloware you assigned the issue to me and approved my PR. Is there any action, I should do with this issue?

**Comment by melloware** [comment]
Nope just waiting for some others to review. No action on your part.

**Comment by jepsar** [comment]
@OBreidenbach thanks for adding this!
