### ISSUE TITLE
Datatable: not visible columns within grouped columns become visible after sorting/filtering

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7255]
A column with the attribute visible="false" that is part of a grouped column becomes visible after any click on the table, e.g., sort, filter, or page navigation. 

See attached repoducer. Open the page and you see three column where the first two are grouped. When you sort on the first column, the non-visible column become visible such that four columns are now shown (while the table header is kept stable und thus misaligned!)

[p-datatable-groupedcolumn.zip](https://github.com/primefaces/primefaces/files/6366414/p-datatable-groupedcolumn.zip)

The expected behavior is of course that the non-visible column stays non-visible (and it only used for the export).

Many thanks in advance for fixing.

**Comment by melloware** [comment]
OK this ticket is related to this one: https://github.com/primefaces/primefaces/issues/7051

Basically grouped rows don't play nicely with Column Toggler and column visibility because in your case there are 5 row headers and 3 columns and the code is trying to figure out which ones are visible but the columns don't line up 5 vs 3.

Here is a MonkeyPatch that fixes it for you right now:
```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.updateColumnsView = function() {
        if (this.isEmpty()) {
            return;
        }

        // update the visibility of columns but ignore expanded rows and GitHub #7255 grouped headers
        if (this.headers && !this.hasColGroup()) {
            for (var i = 0; i < this.headers.length; i++) {
                var header = this.headers.eq(i),
                    col = this.tbody.find('> tr:not(.ui-expanded-row-content) > td:nth-child(' + (header.index() + 1) + ')');

                if (header.hasClass('ui-helper-hidden')) {
                    col.addClass('ui-helper-hidden');
                } else {
                    col.removeClass('ui-helper-hidden');
                }
            }
        }

        // update the colspan of the expanded rows
        if (this.cfg.expansion) {
            this.updateExpandedRowsColspan();
        }
    }
}
```

**Comment by tuerker** [comment]
many  thanks again.
