### ISSUE TITLE
Font aweseome - larger icons cutted of

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#726]
Larger icons are cutted off and often the margin to the aligned text in button or menuitem is very small (see icon bed in image below).

Go to showcase and replace icons with larger icons: 

http://www.primefaces.org/showcase/ui/misc/fa.xhtml

If i remove _overflow: hidden_ from class _ui-icon_ it works

See image:

http://fs5.directupload.net/images/150926/jxdxrx8c.png

**Comment by djmj** [comment]
The problem is this rule in theme.css.

.ui-icon {
    border-radius: 10px;
}

In my tests this border-radius is not necessary. So Primefaces can override it to 0.

**Comment by melloware** [comment]
@NicolaIsotta any thoughts on this one?

**Comment by NicolaIsotta** [comment]
Yep, it's like I wrote in the font issue. Font awesome icons are cutted. It's more visible with Aristo.
I don't have access to the projects right now, but I think I temporary fixed the issue with a rule like `.ui-icon.fa { overflow: visible }` or something like that.
On monday I'll check, maybe the  default `overflow` or the `border-radius` can be safely removed.

**Comment by melloware** [comment]
thanks @NicolaIsotta let me know what you discover.

**Comment by NicolaIsotta** [comment]
@melloware 
Took a deeper look, the guility css rule is this one:
https://github.com/primefaces/primefaces/blob/af20d1f75ca6a5e0ec708256e49057e71a10516c/src/main/resources/META-INF/resources/primefaces-aristo/theme.css#L15-L19

It's only present in the Aristo theme and, like @djmj said,  I'm pretty sure it can be removed safely.

**Comment by melloware** [comment]
Thanks guys. PR submitted!

**Comment by NicolaIsotta** [comment]
Aside from that @melloware , the combination of the `ui-icon` and `fa` is not perfect IMHO.
Just go to https://www.primefaces.org/showcase/ui/misc/fa.xhtml and choose Cruze or Bootstrap theme, you'll see the user icon is cutted on the left.
There's already a rule which makes the classes cooperate
https://github.com/primefaces/primefaces/blob/72a25feaf374be910c1fab22662074e4763be8b8/src/main/resources/META-INF/resources/primefaces/core/core.css#L99-L104
I'd add at least `overflow: visible;` to it.

Also, `ui-icon` has `width: 16px;` which is not needed by FontAwesome icons, so I'd remove it with:
```css
.ui-widget .ui-icon.fa:not(.fa-fw),
.ui-icon.fa:not(.fa-fw) {
    width: auto;
}
```
But this last modification may have some effects on current users.

**Comment by melloware** [comment]
@mertsincan @onursenture Can you guys please weigh in on this before I add this to my PR?
