### ISSUE TITLE
Datatable: right-align all columns of a "numeric" datatype by default

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7262]
Is there an easy way to globally set that all datatable columns of a "numeric" datatype should be right-aligned by default?

Currently, i am adding style="float:right" to each column of a "numeric" datatype individually (and thus often leads to inconsistent layout depending whether the different developers of the project have this in mind or not)

**Comment by tandraschko** [comment]
-1 from my side to add a auto-feauture for this

**Comment by stolp** [comment]
I use a column style class for this purpose:

```
.columnRight {
  text-align: right;
}
```

I am not sure an automatism is a good idea here. It would at least require an additional attribute to enable a non backward compatible behavior. What would be gained in such a case?

**Comment by tandraschko** [comment]
exactly - a styleclass in a user app is better as a new magic attribute, which is probably different in some locales and even requires some reflection work

**Comment by tuerker** [comment]
i am fully aware of the problem of backward compatibility. therefore i asked whether there is a way to globally set this property once for all tables.

**Comment by tuerker** [comment]
> I use a column style class for this purpose:
> 
> ```
> .columnRight {
>   text-align: right;
> }
> ```
> 
> I am not sure an automatism is a good idea here. It would at least require an additional attribute to enable a non backward compatible behavior. What would be gained in such a case?

yes but this is not enough.

it should be done datatype-dependent, i.e., for all columns of a "numeric" type.

gain: it is not needed anymore to place style="float:right" or styleClass="columnRight" for each column individually, i.e., hundred times.

**Comment by melloware** [comment]
-1

I use PrimeFlex `styleClass="p-text-right"` as you can see in the Quantity Column in this example: 
https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml?jfwid=371f5

@tuerker Not sure how we could possibly automate this.  I really don't find it that inconvenient to configure my columns when setting up a datatable.  I think the only way you could accomplish this is to override the DatatableRenderer and do some magic where you check the column type and add the style automatically as you are rendering.

**Comment by tandraschko** [comment]
this can only be implemented in one single case: when the `field` on `p:column` is used. For every other markup, we cant even identify if its number or not.
And its not worth to introduce a new attribute for one single case, which would be required for backward compatibility

**Comment by tuerker** [comment]
@melloware whether using styleClass="p-text-right" or style="float-right" does not really change here anything. i actually would like to get rid of the need to add such an attribute to each numeric column. the idea could be to configure a context parameter once which tells the datatable renderer to add "float:right;" (or - more generically - the corresponding context parameter value) to the style attribute of the column whenever it renders a numeric column. the challenge is to detect the (numeric) datatype of the column. 

@tandraschko i am inline with your statement. to clearly point out: i was not asking for adding an attribute to column element since then of course i could directly use the currently available style or styleClass attribute. defining an additional context parameter, on the other hand, would not effect backward compatibility if a solution for the datatype detection problem could be found.

many thanks again for considering this issue.
