### ISSUE TITLE
AutoComplete: Theme: Add padding to .ui-autocomplete-footer and .ui-autocomplete-empty-message

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7266]
See also https://github.com/primefaces/primefaces/pull/7258

Without custom styling message and footer look like

<img width="375" alt="Screenshot 2021-04-28 at 15 08 48" src="https://user-images.githubusercontent.com/7500178/116409213-e7c24880-a833-11eb-9bdf-7fdad47c6382.png">

<img width="373" alt="Screenshot 2021-04-28 at 15 09 16" src="https://user-images.githubusercontent.com/7500178/116409225-eabd3900-a833-11eb-9be2-7966a975cde5.png">

While it "should" look something like this IMO

<img width="374" alt="Screenshot 2021-04-28 at 15 12 57" src="https://user-images.githubusercontent.com/7500178/116409799-7a62e780-a834-11eb-9bc1-2efa9a97fde4.png">

**Comment by tandraschko** [comment]
`ui-autocomplete-emptyMessage` doesnt fit our naming conventions? maybe better use `ui-autocomplete-emptymsg`

**Comment by jepsar** [comment]
It was already like that, but I could rename it. Has no impact on theme.

**Comment by tandraschko** [comment]
maybe you can check the naming of other style classes like this (e.g. DT)

**Comment by jepsar** [comment]
I noticed that a padding value is set for empty message:

https://github.com/primefaces/primefaces/blob/a74d415cbdd2e85862da7af3c2ef0b9eb4c9e9c2/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.css#L150-L152

I could change it to match the Saga padding value and do the same for footer. Or are there great differences between different themes as it comes to padding values?

**Comment by buunsal** [comment]
Closed via https://github.com/primefaces/primefaces/commit/bd9907bfc876ee0303c9009d40553681807fbe0b
