### ISSUE TITLE
AutoComplete: change CSS class names to comply with conventions

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7267]
See https://github.com/primefaces/primefaces/issues/7266

@melloware you can assign this to me

**Comment by jepsar** [comment]
I've found an other instance: `.ui-timepicker-oneLine`.

**Comment by tandraschko** [comment]
lets align it with datatable: ui-datatable-empty-message

**Comment by jepsar** [comment]
@tandraschko done. Sorry, I didn't get what you were saying yesterday.
