### ISSUE TITLE
Carousel : Change pagination buttons style to be page numbers

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#7269]
I was wondering if it's possible to change the carousel pagination buttons style to be page numbers?
something like paginationStyle='pageNumbers'

**Comment by Rapster** [comment]
A rework of this component is planned for PF 11. Up to @mertsincan

**Comment by melloware** [comment]
It would definitely require modification to this component.

**Comment by buunsal** [comment]
#7759 Carousel has been reimplemented so I am closing this issue for now.
