### ISSUE TITLE
fa-aweseome Icon in Tree

### ISSUE THREAD

**Issue by sardineuser** [primefaces/primefaces#727]
Hello,
fa icons on Tree node components are not well positionned. 
Using fa icons make a CR/LF on tree node between icon and text.

Best regards.

**Comment by cagataycivici** [comment]
<img width="325" alt="tree" src="https://cloud.githubusercontent.com/assets/686247/11785435/876e50aa-a28a-11e5-83eb-a29d79ba87d8.png">

Doesn't look bad to me?

``` xml
<p:treeNode expandedIcon="fa fa-folder-open" collapsedIcon="fa fa-folder">
```
