### ISSUE TITLE
Tree: Selection is not WCAG compliant

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#7273]
**Issue Description**
Primefaces' Tree Selection component does nut fulfil the WCAG accessibility criterion [4.1.1](https://www.w3.org/WAI/WCAG21/Understanding/parsing.html) as it renders syntactically incorrect HTML code. The problems seems to be that in complex trees which include components like checkboxes the included components are rendered as 'div' elements while the tree itself as well as its tree nodes are rendered as 'span' elements ('div' elements are not allowed as child elements of 'span' elements).

**To Reproduce**
1. Open showcase [Tree Selection](https://www.primefaces.org/showcase/ui/data/tree/selection.xhtml?jfwid=4c890).
2. Use bookmarklet "Check serialized DOM of current page" from https://validator.w3.org/nu/about.html#extras to run Nu Html 
    Checker on the showcase.
3. Drag and drop bookmarklet "Check for WCAG 2.0 parsing compliance" from the same page to your browser's bookmark 
    toolbar and execute it on the website of Nu Html Checker which you opened in Step 2. This bookmarklet will filter the results
    of Nu Html Checker so that only WCAG relevant results remain.
4. After running both bookmarklets, if the Nu Html Checker still shows error messages, the syntax of the checked HTML code is
    not correct.

**Expected behavior**
To fulfil the accessibility criterion Nu Html Checker should show no error messages after checking the tree's HTML code.

**Example XHTML**
`<p:tree value="#{treeSelectionView.root3}" var="doc"
                selectionMode="checkbox"
                selection="#{treeSelectionView.selectedNodes2}">
            <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                <h:outputText value="#{doc.name}"/>
            </p:treeNode>
</p:tree>`

**Comment by melloware** [comment]
If you review my PR I think it was as easy as changing the SPAN to a DIV.  Everything is working properly.

![image](https://user-images.githubusercontent.com/4399574/116562327-0e828c80-a8d1-11eb-9e8a-24df74c6dc82.png)
