### ISSUE TITLE
FileUpload: Add dropZone attribute

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7279]
Facet content should act as the drop zone for uploading files instead of the default component DOM output

**Comment by melloware** [comment]
Want me to assign to you?

**Comment by jepsar** [comment]
Okay with me

**Comment by jepsar** [comment]
Okay.. attribute it will be. That would also allow you to use a text area as drop zone.

**Comment by mertsincan** [comment]
Hi @jepsar, 

This might be annoying but can you update your showcase PR? Thanks a lot ;)
