### ISSUE TITLE
[Bug] PrimeFaces Clock skip displaying 1 second per every synchronization request

### ISSUE THREAD

**Issue by dmaidaniuk** [primefaces/primefaces#728]
PrimeFaces Clock widget has an issue when displayed server time and synchronization enabled.
Try to set `<p:clock mode="server" autoSync="true" syncInterval="10000"/>` and every 10 sec clock jumps over 1 sec, i.e. 6 is changed to 8.

This happens because of bug in synchronization algorithm. Just received from server current time (populated by `ClockRenderer` into callback variable `datetime`) increased by 1 second and only after that shows on the page. See `oncomplete` JS-callback:

```
   sync: function() {
        this.stop();

        var $this = this,
        options = {
            source: this.id,
            process: this.id,
            async: true,
            global: false,
            params: [{
                name: this.id + '_sync', value: true
            }],
            oncomplete: function(xhr, status, args) {
                $this.current = new Date(args.datetime);
                $this.start();
            }
        };

        PrimeFaces.ajax.AjaxRequest(options);
    }
```

And then `start` and `updateOutput` functions:

```
start: function() {
        var $this = this;
        this.interval = setInterval(function(){
            $this.updateOutput();
        }, 1000);
},
updateOutput: function() {
        this.current.setSeconds(this.current.getSeconds() + 1);
        this.jq.text(this.cfg.dateFormat.format(this.current));   
},
```

Also stopping clock before AJAX call freeze clock on slow network connections until response arrive. Better way is stop clock inside `oncomplete` JS-callback. 
Thus to resolve bug with skipped 1 sec function `sync` should be looks like this:

```
   sync: function() {
        var $this = this,
        options = {
            source: this.id,
            process: this.id,
            async: true,
            global: false,
            params: [{
                name: this.id + '_sync', value: true
            }],
            oncomplete: function(xhr, status, args) {
                $this.stop();
                $this.current = new Date(args.datetime);
                $this.jq.text($this.cfg.dateFormat.format($this.current));
                $this.start();
            }
        };

        PrimeFaces.ajax.AjaxRequest(options);
    }
```

Tested on PrimeFaces version 5.2.8.

**Comment by melloware** [comment]
I have witnessed the same 1-2 second delay as you have in our usage.  Submitting your fix as a PR.

**Comment by dmaidaniuk** [comment]
Hi @melloware ,
Thanks. It is strange that issue reported in far 2015 is still alive...

**Comment by melloware** [comment]
I find that the PF developers focus on PRO user defects and adding new features.  For these GitHub issues they count on PR's from users like us. :)   Or if enough people have a problem with a ticket and gets up-voted they will fix it.  I happen to use this Clock component and appreciate your fix.

**Comment by dmaidaniuk** [comment]
Hi @melloware ,
Finally with help of yours PR this fix goes to master :) . Thanks for assistance! I will take into account your suggestion about PRs in future bug-reports for PrimeFaces.

Regards,
Dmytro
