### ISSUE TITLE
Spinner: Add list of allowed values

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7282]
For zooming for example you might want to allow `[ 25, 50, 75, 100, 150, 200, 400, 800 ]`

**Comment by jepsar** [comment]
I think this does not make much sense, as you can input values in the input field. At least not without removing the input field and display the selected value statically.

**Comment by melloware** [comment]
I agree. Do you want me to close it?  For this type I would use a SelectOneMenu or something if it truly only had these many values.

**Comment by jepsar** [comment]
I'm not sure yet. I think it's still useful to be able to +/- through select items, but I'm not sure if this should be spinner or a selectOneMenu variant. I think spinner make most sense, but that will require not rendering the input type=text, but a hidden input instead.

**Comment by melloware** [comment]
@jepsar Did you decide to not implement this one?  I forget what we decided.

**Comment by jepsar** [comment]
I'll have a go at it. I'll add it to the spinner, not to selectOneMenu. I was hoping for the horizontal buttons to be merged first, but I guess I'll have to digest some conflicts 😆

**Comment by melloware** [comment]
any update on this ticket?  keep open or close it?

**Comment by jepsar** [comment]
It doesn't have priority for me currently. Might get back to it later. Feel free to close for now.
