### ISSUE TITLE
FileUpload: show function in client API doesn't work for the second time

### ISSUE THREAD

**Issue by iwamun** [primefaces/primefaces#7284]
** using client API  FileUpload can't call listener method **
Calling show function of FileUpload same as #5373

**Environment:**
 - PF Version: 10.0
 - JSF + version: Mojarra 2.2.19
 - Affected browsers: Safari Chrome may be any browser.

**To Reproduce**
1. Click on button 'CSV Upload'
2. Click on menu item '0'
3. Chose some file
4. Repeat these steps
5. FileUpload doesn't call listener method at twice

**Expected behavior**
FileUpload should call listener method repeatedly

**Example XHTML**
```html
<h:head/>
<h:body>
<f:view>
<h:form>
<p:growl id="growl"/>
<p:menuButton value="CSV Upload">
  <p:menuitem value="0" onstart="PF('upload0').show()"/>
  <p:menuitem value="1" onstart="PF('upload1').show()"/>
  <p:menuitem value="2" onstart="PF('upload2').show()"/>
  <p:menuitem value="3" onstart="PF('upload3').show()"/>
  <p:menuitem value="4" onstart="PF('upload4').show()"/>
  <p:menuitem value="5" onstart="PF('upload5').show()"/>
  <p:menuitem value="6" onstart="PF('upload6').show()"/>
  <p:menuitem value="7" onstart="PF('upload7').show()"/>
  <p:menuitem value="8" onstart="PF('upload8').show()"/>
  <p:menuitem value="9" onstart="PF('upload9').show()"/>
</p:menuButton>
<p:fileUpload widgetVar="upload0" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv0}" update="growl"/>
<p:fileUpload widgetVar="upload1" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv1}" update="growl"/>
<p:fileUpload widgetVar="upload2" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv2}" update="growl"/>
<p:fileUpload widgetVar="upload3" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv3}" update="growl"/>
<p:fileUpload widgetVar="upload4" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv4}" update="growl"/>
<p:fileUpload widgetVar="upload5" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv5}" update="growl"/>
<p:fileUpload widgetVar="upload6" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv6}" update="growl"/>
<p:fileUpload widgetVar="upload7" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv7}" update="growl"/>
<p:fileUpload widgetVar="upload8" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv8}" update="growl"/>
<p:fileUpload widgetVar="upload9" auto="true" style="display:none;" listener="#{UploadTest.uploadCsv9}" update="growl"/>
</h:form>
</f:view>
</h:body>
```

**Example Bean**
```java
@ManagedBean(name="UploadTest")
@ViewScoped
public class UploadTestManagedBean {
	public void uploadCsv0(FileUploadEvent event){uploadCsv(event.getFile(), 0);}
	public void uploadCsv1(FileUploadEvent event){uploadCsv(event.getFile(), 1);}
	public void uploadCsv2(FileUploadEvent event){uploadCsv(event.getFile(), 2);}
	public void uploadCsv3(FileUploadEvent event){uploadCsv(event.getFile(), 3);}
	public void uploadCsv4(FileUploadEvent event){uploadCsv(event.getFile(), 4);}
	public void uploadCsv5(FileUploadEvent event){uploadCsv(event.getFile(), 5);}
	public void uploadCsv6(FileUploadEvent event){uploadCsv(event.getFile(), 6);}
	public void uploadCsv7(FileUploadEvent event){uploadCsv(event.getFile(), 7);}
	public void uploadCsv8(FileUploadEvent event){uploadCsv(event.getFile(), 8);}
	public void uploadCsv9(FileUploadEvent event){uploadCsv(event.getFile(), 9);}
	public void uploadCsv(UploadedFile data, int fileId){
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "FileId:" + fileId, null));
	}
}
```

**Comment by melloware** [comment]
Here is a reproducer it is working fine for me?
[pf-7284.zip](https://github.com/primefaces/primefaces/files/6414926/pf-7284.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by iwamun** [comment]
I create environment of pf-7284.zip.
It is not working in the same way as my example.

Perhaps my English is problem.
Did you click on menu item '0' twice?
It works for the first time. but it doesn't work for the second time.

I try to reproduce in safari/chrome on Mac, and edge/firefox on Win10.
But it's not working.

**Comment by melloware** [comment]
Ok now I understand I did not click the same link twice.  I will try that.

**Comment by melloware** [comment]
Confirmed this is a defect.

**Comment by melloware** [comment]
OK I fixed it. Try this reproducer...
[pf-7284-fixed.zip](https://github.com/primefaces/primefaces/files/6421261/pf-7284-fixed.zip)

You need to `update="@form"` not `update="growl"`

**Comment by melloware** [comment]
Actually `update="@this growl"` is even better.  The fileUpload itself needs to be updated after to reset it.

**Comment by melloware** [comment]
Going to close this issue for now that it has been resolved and I don't think there is anything we should hack into the code for this specific scenario.

**Comment by tandraschko** [comment]
why should a update be required?

**Comment by melloware** [comment]
It looks like the FileUpload component needs to be reset when called like this.  @Rapster added this client side show method which I have never used but it looks like after you use it it puts the FileUpload in a state where it needs to be reset.  I can reopen if you want?

**Comment by tandraschko** [comment]
yeah please
i think we could reset automatically somehow? update=@this is just a hack IMO

**Comment by melloware** [comment]
I wonder if its this line in 3-fileupload.js...
```javascript
var update = this.cfg.update ? PrimeFaces.expressions.SearchExpressionFacade.resolveComponents(this.cfg.update).join(' ') : null;
```

Its not adding itself to the update list.

**Comment by tandraschko** [comment]
why updating? couldnt we do this on JS side? updating is always just a hack

**Comment by melloware** [comment]
I guess all the FileUpload client side show is doing is this...
```
/**
     * Brings up the native file selection dialog.
     */
    show: function() {
        if (this.cfg.skinSimple) {
            this.input.trigger("click");
        }
        else {
            this.jq.trigger("click");
        }
    },
```
But after uploading the File the component is in a bad state I am not sure why or how this is different from a regular file upload.

**Comment by melloware** [comment]
Let me see if I can step through the debugger and figure out where this goes wrong.

**Comment by iwamun** [comment]
> Actually `update="@this growl"` is even better. The fileUpload itself needs to be updated after to reset it.

Hi! @melloware. 
I conrirmed your fixed program. I should try to find some hack as you did.

**Comment by tandraschko** [comment]
i fixed it with a small hack
it seems that the fileupload plugin doesnt trigger the change event anymore, maybe thats also related to #7352
maybe @melloware finds a solution for this and we can try to apply a similar fix to this issue

**Comment by melloware** [comment]
i will let you know what i find out

**Comment by tandraschko** [comment]
not sure why but it works now with this commit

**Comment by melloware** [comment]
Weird does the JQ Input not exist at the time or is the name slightly different than we expect?

**Comment by tandraschko** [comment]
May be detached by the plugin, not sure.
