### ISSUE TITLE
PickList: Add localization support

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7285]
**Description**
With PrimeFaces 10, localization message files are now part of the distribution. Not all components do support that. 
For example, PickList shows fixed tooltip strings like 'Add',, 'Add all' etc. for the control buttons.

As a hack for localization, the following attributes are currently available in PickList: addLabel, addAllLabel, removeLabel, removeAllLabel, moveUpLabel, moveTopLabel, moveDownLabel, moveBottomLabel.

**Describe the solution you would like**
Message resource entries should be added for these labels and used instead of the hardcoded strings.

Additional suggestion: The existing label attributes should be deprecated in version 11 and removed in version 12.

Please comment.

I will follow up with a pull request resolving this.

**Comment by stolp** [comment]
The following reproducer shows the localization for German language in action.

[PF-7285.zip](https://github.com/primefaces/primefaces/files/6412270/PF-7285.zip)

**Comment by jepsar** [comment]
NL:

primefaces.picklist.ADD = Voeg toe
primefaces.picklist.ADD_ALL = Voeg alles toe
primefaces.picklist.REMOVE = Verwijder
primefaces.picklist.REMOVE_ALL = Verwijder alles
primefaces.picklist.MOVE_UP = Eerste
primefaces.picklist.MOVE_TOP = Omhoog
primefaces.picklist.MOVE_DOWN = Laatste
primefaces.picklist.MOVE_BOTTOM = Omlaag
