### ISSUE TITLE
Printer: Unable to print Charts 

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7288]
**Describe the defect**
When printing my page using the p:printer component, Charts objects are missing from the print output.
If I use Ctrl-P, the page is rendered correctly.

**Reproducer**
See: https://github.com/stolp/primefaces-test/tree/PF-7285

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _e.g. Mojarra 2.3.14_
 - Affected browsers: _ALL_

**To Reproduce**

1. Print page via Print Button
2. Print Page via CTRL-P
3. Compare

**Expected behavior**
The page should print correctly.

**Comment by melloware** [comment]
I wonder if its a bug in the JS lib or some setting we are missing?

See: https://github.com/DoersGuild/jQuery.print

**Comment by stolp** [comment]
Maybe https://github.com/DoersGuild/jQuery.print/issues/43 is relevant here?

**Comment by melloware** [comment]
I just commented on that ticket.  I tried `print({globalStyles:false,timeout:1500, iframe: false});` and none of it works.  It seems the plugin can't print `canvas` elements which is what ChartsJS is.

Charts can be exported as images but not sure if that does you any good or not? http://localhost:8080/showcase/ui/chartjs/export.xhtml

**Comment by melloware** [comment]
I think this method is not detecting `canvas` correctly...
https://github.com/DoersGuild/jQuery.print/blob/master/jQuery.print.js#L141

**Comment by melloware** [comment]
OK here is the real problem.  https://stackoverflow.com/questions/41239428/jquery-clone-does-not-clone-content-of-canvas

**Comment by stolp** [comment]
Yes, canvas is what I saw in DoersGuild/jQuery.print#43 as well.

Sadly, exporting images does not help my use case.

All I want is to present the user a button to print the whole page as it is (the content is already optimized for printout).

I do not need the feature of the printer component to print parts of the page at all.

Is there is an easier way to do this via JavaScript? Pressing Ctrl-P is all I need.

Apart from my personal use case, other users will be probably be irritated that Charts/Canvas objects are missing from their printout. I think that should get documented at the printer component.

**Comment by stolp** [comment]
@melloware You are just too fast ... :)

**Comment by melloware** [comment]
So I think we need to patch that printer.js with copying the canvas as well. :)

**Comment by melloware** [comment]
Maybe we should upgrade to Print.js it seems to do canvas... https://github.com/crabbly/Print.js/issues/267

**Comment by stolp** [comment]
I cannot really judge if it is the better alternative, but it seems to be better maintained at the moment.

How about incubating this in pimefaces-extensions? It is less of a risk in breaking anything and gets feedback earlier this way.

**Comment by melloware** [comment]
Not a bad idea.  Let me do that.

**Comment by melloware** [comment]
Just an update on this ticket.  This is fixed by a combination of PrintJS which handle's `canvas` objects and by ChartsJS 3.X while ChartsJS 2.9.3 when using responsive makes it print out 900+ pages :)

**Comment by melloware** [comment]
Now that we have upgraded to Charts 3.2 for PF11 I updated the Printer component and created a showcase example and now Charts are printing correctly.

**Comment by melloware** [comment]
@stolp check out https://github.com/primefaces/primefaces/pull/8493 I verified with your tester above its fixed with jQuery.print 1.6.2.

[pf-7288.zip](https://github.com/primefaces/primefaces/files/8146691/pf-7288.zip)

**Comment by stolp** [comment]
Let me check this.

**Comment by melloware** [comment]
Cool let me know if you approve.

**Comment by stolp** [comment]
I verified that printing a chart canvas via p:printer is working in that branch.

I experience a distorted aspect ratio with the chart, but my guess is that is a different issue I have to check in detail.

**Comment by melloware** [comment]
ok let me know.
