### ISSUE TITLE
GitHub Defect Template: PrimeFaces and JSF versions suggested should be aligned with the issue template

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7289]
**Describe the defect**
Currently it suggests PrimeFaces 8 and Mojarra 2.2.8. The primefaces-test project usesPrimeFaces 10.0 and  Mojarra 2.2.20.

**Reproducer**
Create a defect issue.

**Comment by melloware** [comment]
Good call and thanks for the PR.
