### ISSUE TITLE
FileUpload: Add buttonStyleClass

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7292]
To style buttons like https://www.primefaces.org/showcase/ui/button/button.xhtml

@melloware you can assign me to this as well

**Comment by melloware** [comment]
Done

**Comment by jepsar** [comment]
Why don't we do

```xhtml
<p:fileUpload ...>
    <p:button styleClass="ui-fileupload-choose ..."
              value="..."
              icon="..."
              title="..."/>
</p:fileUpload>
```

instead of

```xhtml
<p:fileUpload ...
              uploadButtonStyleClass="..."
              uploadLabel="..."
              uploadIcon="..."
              uploadButtonTitle="..."/>
```

and just take the supported properties from the child buttons? This will save a lot of attributes.

**Comment by melloware** [comment]
I think its because FileUpload has 3 or 4 different modes and buttons don't make sense for all modes which is why they did it this way.

**Comment by jepsar** [comment]
I was not implying to render the child buttons as is, I just wanted to read their properties. Will be less coder friendly though.

**Comment by jepsar** [comment]
Added 3 attributes. (See PR).
