### ISSUE TITLE
DataTable: Paginator doesn't work after filtered.

### ISSUE THREAD

**Issue by iwamun** [primefaces/primefaces#7293]
**Describe the defect**
Instance of row's bean is renewed after filtered.

**Environment:**
 - PF Version: 10.0
 - JSF + version: Mojarra 2.2.19
 - Affected browsers: Safari Chrome may be any browser.

**To Reproduce**
1. Filter rows
2. Clear the filtered rows
3. Move to other pages
4. Instance of row's bean is renewed

**Expected behavior**
It doesn't reproduce on primefaces 8

**Example XHTML**
```html
<f:view>
<h:head/>
<h:body>
<h:form>
  <p:dataTable var="row" value="#{FilterTest.list}"
      filteredValue="#{FilterTest.filteredList}" paginator="true" rows="10">
    <p:column filterBy="#{row.id}">
      <h:outputText value="#{row.id}"/>
    </p:column>
  </p:dataTable>
</h:form>
</h:body>
</f:view>
```

**Example Bean**
```java
@ManagedBean(name="FilterTest")
@ViewScoped
public class FilterTest extends BaseSettingManagedBean {
	private List<Bean> list = new ArrayList<>();
	private List<Bean> filteredList;
	public FilterTest() {
		for(int i = 0; i < 1000; i++) {
			list.add(new Bean(i));
		}
	}
	public List<Bean> getList() {
		return list;
	}
	public List<Bean> getFilteredList() {
		return filteredList;
	}
	public void setFilteredList(List<Bean> filteredList) {
		this.filteredList = filteredList;
	}
}
public class Bean {
	private int id;
	public Bean() {}
	public Bean(int id){this.id = id;}
	public int getId(){return id;}
}
```

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by iwamun** [comment]
ok. I understood.I'll provide an example using this project.

**Comment by iwamun** [comment]
@melloware
Here is an example. Thank you for your help.
[pf-7293.zip](https://github.com/primefaces/primefaces/files/6424416/pf-7293.zip)

**Comment by melloware** [comment]
@iwamun Can you try my fixed version here:
[pf-7293-fixed.zip](https://github.com/primefaces/primefaces/files/6426667/pf-7293-fixed.zip)

**Comment by melloware** [comment]
OK attached is my fixed version:
[pf-7293-fixed.zip](https://github.com/primefaces/primefaces/files/6426704/pf-7293-fixed.zip)

Your `TestBean` was not `Serializable` and since you are using a `@ViewScoped` bean all beans must be Serializable for it to hold them in the filtered list and then restore them properly.

**Comment by iwamun** [comment]
I confirm your fixed version. Thanks for your help again.
Can I ask a question?
Why does it work well on primefaces 8.0? 
Could you tell me what is the different if you don't mind.

**Comment by melloware** [comment]
There is no way this should have worked on 8.0 if you did not have Serializable it should have worked the same way.

**Comment by iwamun** [comment]
My example pf-7293.zip works on 8.0.
Because I found these difference when our service is going to migrate from 8 to 10.
You can change the environment of 10 to 8 with modifing 2 files, pom.xml and web.xml.
```xml
<context-param>
   <param-name>primefaces.THEME</param-name>
   <param-value>omega</param-value>
</context-param>
```
```xml
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>8.0</version>
</dependency>
```

**Comment by melloware** [comment]
It should not have.  All ViewScoped beans must be Serializable as part of the JSF spec (not PrimeFaces Related). So your old code was wrong either way.  Why it worked before I am not sure and I am not going to research.

**Comment by iwamun** [comment]
Thanks for your reply. I understand what you say,  my code is wrong.
But I recognize that the instance of bean maintains in the same view according the JSF spec.
In my case the view doesn't move so that the instance should remains without implementing serializable.
Sorry if I misunderstand.

**Comment by melloware** [comment]
Yes I don't believe that is how ViewScoped works.

**Comment by melloware** [comment]
Here you go: 
https://stackoverflow.com/a/10508127/502366

https://stackoverflow.com/a/18999562/502366

**Comment by iwamun** [comment]
I visited their sites.
This is why my view scoped bean are fortunately stored by Mojarra.
Thank you for your information.
