### ISSUE TITLE
SummaryRow/HeaderRow: conflict with PanelGridBodyColumnRenderer

### ISSUE THREAD

**Issue by BalusC** [primefaces/primefaces#7296]
**Describe the defect**
When `<p:dataTable><p:summaryRow><p:column>` is nested in `<p:panelGrid><p:row><p:column>` then the `ColumnRenderer` of `<p:summaryRow><p:column>` incorrectly delegates to `PanelGridBodyColumnRenderer` as "helper renderer", causing a rendering of a double-nested `<td>` element.

**Reproducer**
```
<p:panelGrid>
	<p:row>
		<p:column>
			<p:dataTable id="table" value="#{[
				{'id':1,'group':'odd'},
				{'id':3,'group':'odd'},
				{'id':5,'group':'odd'},
				{'id':2,'group':'even'},
				{'id':4,'group':'even'}
			]}" var="item" sortBy="#{item.group}">
				<p:column headerText="id">
					#{item.id}
				</p:column>
				<p:column headerText="group">
					#{item.group}
				</p:column>
				<p:summaryRow>
					<p:column>
						#{item.group} ids
					</p:column>
					<p:column>
						#{item.group} summary
					</p:column>
				</p:summaryRow>
			</p:dataTable>
		</p:column>
	</p:row>
</p:panelGrid>
```

**Environment:**
 - PF Version: 8.0
 - JSF + version: Mojarra 2.3.15
 - Affected browsers: ALL

**To Reproduce**
1. Copy paste above XHTML snippet into `<h:body>` of empty template (no bean needed)
2. Open page in webbrowser
3. Observe following output (Chrome)

![image](https://user-images.githubusercontent.com/173372/117203856-87944f00-adbd-11eb-8cbb-188bfb3f455f.png)

**Expected behavior**
No double-nested `<td>` cells in summary row
![image](https://user-images.githubusercontent.com/173372/117203816-7ba88d00-adbd-11eb-9711-0b64f4a521bc.png)

**Work around**
Remove `Constants.HELPER_RENDERER` attribute from context. This can be achieved by editing the example XHTML as follows
```
<p:summaryRow listener="#{facesContext.attributes.remove('org.primefaces.HELPER_RENDERER')}">
```

**Solution**
Probably in `SummaryRowRenderer#encodeXxx()`. Remove that attribute, render, then put back that attribute.

**Comment by melloware** [comment]
Thanks for the debug!   Will fix.

**Comment by melloware** [comment]
@BalusC Attached is a reproducer. If you run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

[pf-7296.zip](https://github.com/primefaces/primefaces/files/6433994/pf-7296.zip)

If I use PrimeFaces 8.0 its broken but if I switch the pom.xml to 10.0.0 its working fine.  So I believe this has already been fixed for 10.0.0.  

But looking through the changes for 10.0.0 I can't seem to nail down what exactly fixed this???

**Comment by BalusC** [comment]
Not sure how it looks for you, but entire summary row doesn't show up in first place.
![image](https://user-images.githubusercontent.com/173372/117294019-23ff3580-ae40-11eb-8278-6358904c1203.png)

**Comment by melloware** [comment]
HA yeah you are right.  Yep looking into it.

**Comment by BalusC** [comment]
Looks like things have incompatibly changed in `<p:dataTable sortBy>`. Now it expects a concrete `SortMeta` instance or a collection thereof instead of an EL expression referring the column property `sortBy="#{item.group}"`, or a plain vanilla String `sortBy="group"` or even map in EL `sortBy="#{{'field':'group','order':'ASCENDING'}}"`. None of them work any more. The `UITable#updateSortByWithUserSortBy()` implementation is definitely open for improvement in this regard.

**Comment by melloware** [comment]
I got it. I used the showcase and followed your example and got it to break.
![image](https://user-images.githubusercontent.com/4399574/117299052-177ddb80-ae46-11eb-8ef6-317a3f053462.png)

**Comment by BalusC** [comment]
Was about to report the same after sorting out the sortBy in local project :) 

![image](https://user-images.githubusercontent.com/173372/117299239-4dbb5b00-ae46-11eb-89b3-7207da075709.png)

**Comment by melloware** [comment]
OK i submitted a draft PR with your fix but its still doesn't fix my issue.  Can you review to make sure it is what you were expecting?

https://github.com/primefaces/primefaces/pull/7297/files

**Comment by melloware** [comment]
OK I updated my PR.  I had to do the same fix in HeaderRow if you are using both a Summary Row and and Header Row.  Now its all working.

**Comment by BalusC** [comment]
LGTM but I'm wondering if this doesn't warrant some sort of integration test?

**Comment by melloware** [comment]
Yep I need to add a new test here: https://github.com/primefaces-extensions/primefaces-integration-tests

I guess the trick will be how to detected is rendered "incorrecctly" vs "correctly" with Selenium.

**Comment by BalusC** [comment]
Oh they are there. Yes I see, thanks!

**Comment by melloware** [comment]
Yeah we have about 300+ tests so far and growing as we add scenarios.  Runs against Mojarra and Myfaces.  And against Firefox, Chrome, and Safari.

**Comment by christophs78** [comment]
> LGTM but I'm wondering if this doesn't warrant some sort of integration test?

Same opinion. In an ideal world we would add for almost each issue we fix at least one integration test. Even when writing integration-test(s) takes more time than the fix itself. But - maybe not unexpected - it´s hard to convince all contributors to do this. Still a long way to go until PrimeFaces has good test coverage.
But as @melloware already mentioned: One year ago we had no integration test´s at all. Now we have 300+, running against 3 browsers, two JSF-impls and Java 8/11.
