### ISSUE TITLE
DataTable: Column widths get corrupted

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#7299]
**Describe the defect**
In a dataTable with resizable columns, the column width is OK when the table is displayed initially, but gets messed up (made much too small) when refreshing the table one or two times via ajax.

**Environment:**
 - PF Version: 10.0.1
 - JSF + version:  Mojarra 2.3 
 - Affected browsers:  ALL

**To Reproduce**

I do not have an example to reproduce, but I debugged the code, and think I discovered the problem.

Please have a look at **DataTableRenderer.java** line **629** ff.

`
if (columnMeta != null && columnMeta.getWidth() != null) {
            width = columnMeta.getWidth();
        }
`
When debugging and taking a look at columnMeta.getWidth(), I find cases where it contains the String  "null", not null.
As result the width of the respective columns is being set to the String "null", which leads in the end to corrupted column widths.
Please have a look at ColumnMeta.setWidth, and make sure it does not allow setting false content.

For myself, I could fix this at another place in my code, just by fetching the list of ColumnMeta objects from the dataTable, and replacing "null" with null in the width attribute.

Hope my explanation is understandable even without an example.

**Comment by melloware** [comment]
I see what you mean but trying to figure out how the word "null" gets in there.  Its only set in 1 place in the code when it gets the values from the AJAX call on resize. so its possible the JavaScript has null which then gets converted to "null".

**Comment by tandraschko** [comment]
Please provide a reproducer.

**Comment by wlhUser** [comment]
Maybe a stacktrace hepls to reproduce.
In the method 'decodeColumnResizeState' the variable 'columnResizeStateParam' gets filled in the very first line, and this contains kind of 'null' values per column.

![grafik](https://user-images.githubusercontent.com/47218021/117416823-0e5e3e80-af1a-11eb-9188-2916dc9c95ff.png)
![grafik](https://user-images.githubusercontent.com/47218021/117416993-35b50b80-af1a-11eb-99b2-a38183ac3c8d.png)

**Comment by tandraschko** [comment]
In think its related to Client Side. We need a reproducer

**Comment by melloware** [comment]
Agreed I can see multiple places in the Client Side JS that need to defend against NULL.  @wlhUser can you even post just your Datatable settings for us to see?

**Comment by wlhUser** [comment]
Hi melloware,
I think its not the client side code, but the server side. In fact the i think it is: **UITable.getColumnsWidthForClientSide**
The data generated there is being sent to the client side as **<tableClientId>_resizableColumnState**, and from there it gets returned to the server in the next request. 
See **DataTableRenderer.java line 346**
`  if (resizable) {
            encodeStateHolder(context, table, table.getClientId(context) + "_resizableColumnState", table.getColumnsWidthForClientSide());
        }
`

Regarding my DataTable settings - its quite complicated, as in our case we encapsulated the  dataTable  in another component.
The main settings are:
frozenColumns="1" // Notice Frozen columns > 1 does not work any longer. Will write another ticket
resizableColumns="true"
virtualScroll="true"
scrollable="true"
lazy="true" 
draggableColumns="true"

**Comment by melloware** [comment]
hmm but it should be reproducible outside of your "complicated" scenario.  If you create a small sample using those same settings does it happen?

**Comment by wlhUser** [comment]
Will try to make a small  example

**Comment by wlhUser** [comment]
Attached you find a zip file containing a xhtml file and the corresponding Bean. To have the same layout as me, I've attached the theme as well.

When opening the page the first time it looks like this:
![grafik](https://user-images.githubusercontent.com/47218021/117479115-383a5400-af60-11eb-95f6-2cc38399a18c.png)

Now press the **Refresh** button **twice**.
After the first press, everything is OK, but after the 2nd click, the table looks like this:

![grafik](https://user-images.githubusercontent.com/47218021/117479263-66b82f00-af60-11eb-9931-778f04b0fc92.png)


[PrimeFaces_Ticket.zip](https://github.com/primefaces/primefaces/files/6443022/PrimeFaces_Ticket.zip)

**Comment by melloware** [comment]
Excellent thank you! let me investigate.

**Comment by melloware** [comment]
Attached is my reproducer I can't get your sample code to work.  
[pf-7299.zip](https://github.com/primefaces/primefaces/files/6443553/pf-7299.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by melloware** [comment]
OK I as able to reproduce it!
[pf-7299.zip](https://github.com/primefaces/primefaces/files/6446214/pf-7299.zip)

And yep look at what the client is sending on that second call..
```
frmTest:test_list:textId4_null,frmTest:test_list:textId5_null,frmTest:test_list:textId2_null,frmTest:test_list:textId3_null,frmTest:test_list:brandId_null,frmTest:test_list:textId6_null,frmTest:test_list:brandId2_null,frmTest:test_list:brandId3_null,frmTest:test_list:idId_null,frmTest:test_list:selectId_null,frmTest:test_list:textId_null,frmTest:test_list:brandId6_null,frmTest:test_list:brandId4_null,frmTest:test_list:brandId5_null
```

**Comment by melloware** [comment]
You were definitely right.  I submitted a 1 line PR fix.

**Comment by wlhUser** [comment]
Thanks a lot for the very quick fix.

**Comment by melloware** [comment]
@wlhUser Thanks for reporting this and providing me with the example to fix it.  I would have had a tough time reproducing it without it!
