### ISSUE TITLE
ColorPicker should support hexadecimal Color strings

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#730]
Hi, I've stumbled across this issue:

See:
http://forum.primefaces.org/viewtopic.php?f=3&t=17597&p=128483&hilit=colorpicker#p128483

Now I'm overriding the PrimeFaces class to support Hexadecimal color values "#FF00FF" etc.. I think it should be possible to specify a prefix. Usually color values are saved like this because they can be easily reused for building CSS wtihout having to add # troughout the sourcecode. So I dont see why PF Component only sets/gets Strings like "ff00ff" 

```
@Override
    protected void encodeMarkup(FacesContext context, ColorPicker colorPicker, String value) throws IOException {
        if (value != null) {
            value = value.replace("#", "");
        }

@Override
    protected void encodeScript(FacesContext context, ColorPicker colorPicker, String value) throws IOException {
        if (value != null) {
            value = value.replace("#", "");
        }
```

**Comment by cagataycivici** [comment]
It is for simplicity, # is not needed when working with the component.

**Comment by cnsgithub** [comment]
Hi, i think it doesn't matter how the component itself does it, but the issue is how the value is set into the bean. It is done without "#" 

Since it is a String it would be more reasonable to save it as a valid Hex color value ( http://www.w3schools.com/tags/ref_colorpicker.asp ) a color is specified as #RRGGBB or #AARRGGBB and not just "RRGGBB". I dont think that anyone would save colors into database _without a #_.  

Also adding a property like useHashPrefix="true" to do this would be a very minimalistic change and wouldnt break it for other users. 

I hope you agree with me that its not nice having to use the workaround above, especially if one has like 10-20 colorpickers throughout a web-application.

So let me guess - If i had Pro instead of Elite this would already be in? ;-)
