### ISSUE TITLE
ChartsJS: Memory leak after ajax updates

### ISSUE THREAD

**Issue by jthalmai** [primefaces/primefaces#7300]
**Describe the defect**
On our page we have multiple _p:barChart_ components that are updated with ajax when there is new data available. After a while an out of memory error occurs in the browser.
Some investigation showed that the JavaScript object _Chart_ of the _ChartJS_ library keeps all the old chart instances and after an update also has the new ones. So this probably also affects other types of charts that are drawn using _ChartJS_.

**Environment:**
 - PF Version: _10.0.0_
 - JSF + version: _Mojarra 2.3.14_
 - Affected browsers: _ALL_

**To Reproduce**
1. Have a p:barChart on your page, you can just use the showcase for this.
2. Update it with ajax, e.g. add the following button and click it a few times:
```
<p:commandButton value="update" update="@(.ui-chart)" oncomplete="console.log(Chart.instances)"/>
```
3. Check the browser's JavaScript console.
4. See the error, after each update, the number of instances grows and grows.

**Expected behavior**
No longer used chart instances should not remain in memory. According to the ChartJS documentation, probably the destroy() method should be called for all no longer used chart instances, see:
https://www.chartjs.org/docs/latest/developers/api.html#destroy

**Comment by melloware** [comment]
This is probably ALL charts I agree.  Can you add this MonkeyPatch to your application.js and let me know if it cleans up the leak?
```javascript
PrimeFaces.widget.BaseChart.prototype.refresh = function(cfg) {
    if (this.chart) {
        this.chart.destroy();
    }

    PrimeFaces.widget.BaseWidget.prototype.refresh.call(this, cfg);
};
PrimeFaces.widget.BaseChart.prototype.destroy = function() {
    PrimeFaces.widget.BaseWidget.prototype.destroy.call(this);

    if (this.chart) {
        this.chart.destroy();
    }
};
```

**Comment by tandraschko** [comment]
sorry, i was faster :P
could someone test?

**Comment by melloware** [comment]
HAHAH yes I was just about to submit a PR.  Thanks for beating me to it!

**Comment by jthalmai** [comment]
The MonkeyPatch works for us. Only the current instance is kept.

**Comment by melloware** [comment]
Nice!  OK this is fixed for 11.0.

**Comment by stolp** [comment]
I am assuming that it is safe to use this monkeypatch with PrimeFaces 8 as well?

**Comment by melloware** [comment]
Yep safe for 8.0 as the widget itself has not changed.

**Comment by jthalmai** [comment]
My previous scenario only tested the 'refresh' case of the monkeypatch. Now I also tested the 'destroy' case with a conditionally rendered chart, but there I get a JS error 'cfg is not defined' in the first line of the destroy function.

**Comment by melloware** [comment]
Sorry try this..
```javascript
PrimeFaces.widget.BaseChart.prototype.destroy = function() {
    PrimeFaces.widget.BaseWidget.prototype.destroy.call(this);

    if (this.chart) {
        this.chart.destroy();
    }
};
```

**Comment by jthalmai** [comment]
Thanks, this works.
