### ISSUE TITLE
JS minify broken due to #7173 (a typo I guess)

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#7302]
**Describe the defect**
I was trying to build the project with js minification and I found it's broken

**Reproducer**
mvn package -Prelease

**Environment:**
Master branch complation

**To Reproduce**
Clone and execute:
mvn clean install -Prelease

**Expected behavior**
yuicompressor should work

**Comment by cocorossello** [comment]
https://github.com/primefaces/primefaces/pull/7303

**Comment by melloware** [comment]
Thanks for the PR!
