### ISSUE TITLE
Exporter: Currency handle infinite numbers

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#7307]
**Describe the defect**
Exporter is broken if column contains value similar to 74E221

**Reproducer**
```html
        <p:dataTable id="sometable" value="#{testView.someList}">
            <p:column>
                <h:outputText value="74E221"/>
            </p:column>
        </p:dataTable>

        <p:commandButton value="XLXS">
            <p:dataExporter type="xls" target="sometable" fileName="anything"/>
        </p:commandButton>
```

**Environment:**
 - PF Version: Latest build
 - JSF + version: MyFaces 2.3.5-NEXT
 - Affected browsers: ALL

**To Reproduce**
Click on the exporter button

**Expected behavior**
Maybe CurrencyValidator should do some validation before or try not to parse Infinity

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    public List getSomeList() {
       return List.of(new Object());
    }
}
```

**Comment by melloware** [comment]
Yep let me look at this one.

**Comment by cocorossello** [comment]
Wow, so fast. I've attached a PR, it's just an idea...

**Comment by melloware** [comment]
@cocorossello I see what you did can you submit the PR please. It looks pretty good to me.
