### ISSUE TITLE
Avatar : Gravatar Insecure Content Warning

### ISSUE THREAD

**Issue by carlbradwell17** [primefaces/primefaces#7309]
**Describe the defect**
When including p:avatar with the Gravatar options, an Insecure Content warning is displayed in the browser.
This is due to AvatarRenderer loading the image via HTTP rather than HTTPS:
` private static final String GRAVATAR_URL = "http://www.gravatar.com/avatar/";`

**Environment:**
 - PF Version: 10.0.0
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: ALL

**To Reproduce**
1. Within a JSF page, include a p:avatar with Gravatar options set, e.g.:
`<p:avatar gravatar="contact@primetek.com.tr" gravatarConfig="d=mp" />`
2. Check the browser "Insecure Content" warning, and network logs for www.gravatar.com

**Expected behavior**
In a site secured using HTTPS, no "Insecure Content" warning should be displayed. The GRAVATAR_URL should use HTTPS.

**Comment by melloware** [comment]
I wonder if we should just use HTTPS always?

**Comment by melloware** [comment]
I just tested it and HTTPS works fine for localhost and HTTP so this should be the default.

**Comment by bjorntj** [comment]
Is this only fixed in version 11? if so, why?

**Comment by melloware** [comment]
@bjorntj Fixed in 11.0.0-RC1.  Only PrimeTek decides what goes in Elite this is just the Community Forum tracker.  I can mark the label "elite" but it doesn't guarantee it goes into 10.X.  I suggest you request it through your PRO support account if you have one.

**Comment by bjorntj** [comment]
I only have Elite and not Pro.. But this fix should be in earlier versions also but I guess then this is up to PrimeTek...
Thx..
