### ISSUE TITLE
ToggleSwich: Support switching value when clicking on an assigned outputLabel

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7311]
**Description**
`p:toggleSwitch` does not behave like `p:selectBooleanCheckBox` when activated by clicking on an `p:outputLabel ` with a `for ` attribute set to the id of the ToggleSwitch.

**Describe the solution you would like**
ToggleSwitch should change its value like selectBooleanCheckBox  does when a user clicks on the assigned label.

**Additional context**

**Example XHTML**
```xml
<h:form id="frmTest">
  <p:outputLabel for="@next" value="Click Me" />
  <p:toggleSwitch value="#{bean.value}" />
</h:form>
```

**Comment by melloware** [comment]
Ahh I see SelectBooleanCheckbox is not attaching to an external `p:outputLabel` its using its own built in `label` and attaching an onClick to it.

See: https://www.primefaces.org/showcase/ui/input/booleanCheckbox.xhtml

I wonder if there are any PF components that actually allow `p:outputLabel` to be the trigger?

**Comment by melloware** [comment]
This works though..
```xml
<p:outputLabel for="@next" value="Click Me" onclick="PF('toggle1').toggle();" />
<p:toggleSwitch widgetVar="toggle1" value="#{selectBooleanView.value1}"/>
```

**Comment by tandraschko** [comment]
i think its native HTML, that it triggers focus of the attached input.

**Comment by stolp** [comment]
Well, p:selectBooleanCheckbox does - I use this all the time. Same goes for p:inputText, p:selectCheckBox etc. (This activates the field).

I think this is basic HTML functionality (label -> input).

**Comment by stolp** [comment]
What puzzles me, is that toggleswitch is sharing almost the same implementation with seletBoleanCheckbox when it comes to HTML.

I tried to spot differences in the source, but failed to identify them.

**Comment by melloware** [comment]
OK yeah these components do look almost the same.  They both use a hidden input to track the checkbox so i would expect they would work the same?

**Comment by stolp** [comment]
That was my assumption when bringing that up.

I can confirm that the workaround is working. Thanks for that!

**Comment by melloware** [comment]
OK I am going to align these components more closely as they are different but should be more like each other. I will see i that fixes this issue.
