### ISSUE TITLE
inputNumber:  bad conversion on focus lost when decimalSeparator=","  and thousandSeparator="."  

### ISSUE THREAD

**Issue by dgoicocheta** [primefaces/primefaces#7315]
**Describe the defect**
The inputNumber do a bad conversion on focus lost when decimalSeparator=","  and thousandSeparator="."  the number don't have decimals and only have one thousand separator

(Better explain above with examples) 

**Environment:**
 - PF Version:  10.0
 - JSF + version: ALL
 - Affected browsers:  ALL

**To Reproduce**
Change the default locale in faces-config to es_ES (or one locale with decimalSeparator=","  and thousandSeparator="." )  or configure input number with decimalSeparator=","  and thousandSeparator="."  fail in both cases.

When you write "1234" in inputNumber, is converted to 1.234 but on focus lost the value change to 1,23
If you write 1000000 is converted to 1.000.000 then on focus lost change to 1.000.000,00, and if write 1234,5  its converted to 1.234,50.  in these cases it's work's fine.

So only fail when you write a number between 1000 and 999999 (only one thousand separator and no decimal separator)

The expeted behavior is if you write 1234 must be converted to 1.234,00 

Don't need submit the value, fails on focus lost, and only in PF 10, in PF 8.0 it's working. 

Example:
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/6465679/primefaces-test.zip)

**Comment by melloware** [comment]
Already fixed https://github.com/primefaces/primefaces/issues/7271

Workaround is provided in that ticket.
