### ISSUE TITLE
Add icon to header of datatable

### ISSUE THREAD

**Issue by raullm83** [primefaces/primefaces#732]
How can you put an icon in the header of a datatable as displayed in the picture ?
![captura](https://cloud.githubusercontent.com/assets/13123294/10134032/eb3289ba-65e2-11e5-874f-bd56c6e89070.PNG)

**Comment by mertsincan** [comment]
Please try with;

```
<p:column filterBy="#{car.id}">
     <f:facet name="header">
         <i class="fa fa-home" />
     </f:facet>
     <h:outputText value="#{car.id}" />
</p:column>
```

Next time, please use primefaces forum.
