### ISSUE TITLE
ERROR Error: Expecting instance of DOM Element Component: Title

### ISSUE THREAD

**Issue by JulyJuli** [primefaces/primefaces#7320]
I try to use paginator dropdown in the table. On element click I receive the next error.
![image](https://user-images.githubusercontent.com/34139003/118293815-bcea1c80-b4e2-11eb-8edf-311a20c16fde.png)

![image](https://user-images.githubusercontent.com/34139003/118293837-c2dffd80-b4e2-11eb-9bfb-305234762ad3.png)

I tried to debug paginator example on [Stackbiz](https://stackblitz.com/edit/primeng-paginator-demo-z6fcke) but here is another renderer for this component: 
![image](https://user-images.githubusercontent.com/34139003/118293627-814f5280-b4e2-11eb-8b18-022e30d6b710.png)
Frankly, I can't understand how this renderer can be changed.

Use Angular 11.

Can somebody help?

**Comment by tandraschko** [comment]
Please use the PrimeNG not PrimeFaces issuetracker
