### ISSUE TITLE
DataTable/TreeTable: Global Filter not preserved by MultiViewState

### ISSUE THREAD

**Issue by MatthiasPischka** [primefaces/primefaces#7325]
**Describe the defect**
As discussed earlier in the primefaces forum (https://forum.primefaces.org/viewtopic.php?f=3&t=66857): When i am using the globalFilter IntputField in combination with the MultiViewState, the table entries are still filtered after revisiting the same site but the value (search keywords) of the globalFilter InputField is resettet. 

**Reproducer**
Visit the PrimeFaces Showcase for example: https://www.primefaces.org/showcase/ui/data/datatable/multiViewState.xhtml, enter something at the right in the global filter field (first dataTable on page), go to another page in Showcase and come back again. The entries are still filtered but the global input field is resetted.

**Environment:**
 - PF Version: _10.0.0_
 - JSF + version: _Mojarra 2.3.14.SP01_
 - Affected browsers: _Testet in Firefox and Chrome_

**To Reproduce**
See above (reproducer)

**Expected behavior**
The entered value should be preserved in case of using MultiViewState

**Comment by melloware** [comment]
This was pretty easy. The filter was being stored in MVS it just wasn't being restored.

**Comment by doteo78** [comment]
@melloware: Any chance to include this in a 10.0.x version?
I am not sure if it will fix that global filter keywords are lost after updating the datatable even when not using MultiViewState.

**Comment by melloware** [comment]
@doteo78 I don't work for PrimeTek so I don't get to decide what goes in Elite releases.   That is up to @sqores

**Comment by doteo78** [comment]
Alright!!
Do you think this issue is the same that occurs when not using MultiViewState? You can reproduce it with datatable crud showcase and with my reproducer attached in #7336. It works fine with 11.0.0-SNAPSHOT but I don't know if it is because of this fix.

**Comment by melloware** [comment]
My guess is its most likely because of this fix if it works in 11.0.0-SNAPSHOT.

**Comment by doteo78** [comment]
@sqores: Would it be possible to include this fix in 10.0.7 version ???

**Comment by joergmattes** [comment]
I would love this to be included in 10.0.7 as well.
