### ISSUE TITLE
DatePicker: dateStyleClasses shifts to wrong date

### ISSUE THREAD

**Issue by smirnov-vladimir** [primefaces/primefaces#7328]
**Describe the defect**
When added metadata with some styles, the styles is applied to wrong date: shifts +/- one day.

**Environment:**
 - PF Version: _10.0_
 - Time zone in browser is UTC+06:00

**To Reproduce**
1. Set time zone on you PC to UTC+06:00
2. After 18:00 styles is shifts on next day

**Solution**
Function **toISODateString()** in _datepicker.js_ now is:
```JavaScript
toISODateString: function (b) {
  return b.toISOString().substring(0, 10)
}

```
must be:
```JavaScript
toISODateString: function (b) {
  return new Date(b.getTime() - (b.getTimezoneOffset() * 60000)).toISOString().substring(0, 10)
}
```

**Comment by melloware** [comment]
cc @christophs78 @jepsar for second set of eyes. I know we have a lot of Integration tests for DatePicker but not sure if we have this scenario covered.

**Comment by christophs78** [comment]
Propably not covered by integration tests.
`toISODateString` is currently only called from `renderDateCellContent` during evaluation of `this.options.dateStyleClasses`. So we at least should not break other functionally. And dateStyleClasses  is only populated via dateMetadata introduced with PF 10. (Think we have no integration tests for dateMetadata.)

**Comment by melloware** [comment]
Perfect.  Then I definitely agree with this fix.  @jepsar do you agree?

**Comment by melloware** [comment]
If someone needs this MonkeyPatch now just apply this to your application JS.
```javascript
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.toISODateString: function(date) {
        return new Date(date.getTime() - (date.getTimezoneOffset() * 60000)).toISOString().substring(0, 10);
    }
}
```

**Comment by jepsar** [comment]
I can have a good look at it this evening. The function was indeed introduced with the metadata addition.

**Comment by jepsar** [comment]
Looking good!
