### ISSUE TITLE
Barcode: Type: qr

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#7330]
The QR code does not appear.

It works in PF10.0 but not from the latest PF11.0 as I just downloaded to test and have the issue.

<p:barcode value="0123456789" type="qr"/>

The error on console:
**No dynamic resource handler registered for: qr. Do you miss a dependency?**

**Comment by jepsar** [comment]
We have switched to `io.nayuki:qrcodegen`. See https://github.com/primefaces/primefaces/issues/7101

You need to add this to your project

```xml
<dependency>
    <groupId>io.nayuki</groupId>
    <artifactId>qrcodegen</artifactId>
    <version>1.6.0</version>
</dependency> 
```
and you can remove
```xml
<dependency>
    <groupId>net.glxn</groupId>
    <artifactId>qrgen</artifactId>
    <version>1.4</version>
</dependency>
```

https://github.com/primefaces/primefaces/blob/master/docs/migrationguide/11_0_0.md

**Comment by anuragnz** [comment]
Thanks a lot. It works now.

**Comment by jepsar** [comment]
@melloware milestone should be 11

**Comment by melloware** [comment]
Sorry thanks for correcting!
