### ISSUE TITLE
InputMask: mask not working correctly when trying to restrict to upper letters 

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7332]
I am not sure whether this is a bug or simply not forseen. Whenever one uses an upper A instead of a lower a in the mask to enforce upper letters, then the entering on the form looks correct but the data is not stored, i.e., send to the backing bean.

Use this example to verify: 

`<p:inputMask id="key" value="#{maskView.productKey}" mask="AAA-999.999.999" validateMask="true"/>
` 

Many thanks in advance for looking at it.

**Comment by melloware** [comment]
I have verified this.  It looks like the server side validateMask method is not validating the mask correctly when using uppercase.  In my integration test everything works with `validateMask="false"` can you confirm?

**Comment by melloware** [comment]
OK thanks for reporting!  Integration Test was failing and now is passing...
```xml
<p:inputMask id="alphanumeric" value="#{inputMask001.alphanumeric}" mask="aa-999-A999" validateMask="true"/>
```

```java
@Test
    @Order(2)
    @DisplayName("InputMask: Alphanumeric mask with valid value")
    public void testAlphanumericValid(final Page page) {
        // Arrange
        final InputMask inputMask = page.alphanumeric;
        Assertions.assertEquals("", inputMask.getValue());

        // Act
        inputMask.setValue("ab-123-c456");
        page.button.click();

        // Assert
        Assertions.assertEquals("ab-123-C456", inputMask.getValue());
        assertConfiguration(inputMask.getWidgetConfiguration(), "aa-999-A999");
    }
```

**Comment by melloware** [comment]
Integration Test updated: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/a83a3340b208f7f011489fae146fe56e8daff395

**Comment by tuerker** [comment]
as usual many thanks for your great work.
