### ISSUE TITLE
FileUpload: File upload doesn't work with BlockUI

### ISSUE THREAD

**Issue by Charriu83** [primefaces/primefaces#7335]
**Describe the defect**
FileUpload caused an JavaScript exception while uploading a file when a p:blockUI with trigger exists on the same xhtml site. The JavaScript errors is `Uncaught TypeError: c.source is undefined` (Firefox) or `Uncaught TypeError: Cannot read property 'name' of undefined` (Chrome) and leads to `bindTriggers()` function in components.js. Without trigger everything is okay.

**Reproducer**
It is possible to use the primefaces-test-master with the changes below to reproduce. Or download it here https://wetransfer.com/downloads/ee2ed7ea0125fdb6768668e143d7aa5920210519143234/f7ee2e2f941e6febef540fb90656a9c520210519143300/efb561 (available for 7 days).

**Environment:**
 - PF Version: _10.0_
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: _ALL_

**To Reproduce**
1. Create a p:blockUI and a p:commandButton
2. The trigger of the p:blockUI is the id of the p:commandButton
2. Add a p:fileUpload component
3. Start application
4. Try to upload a file and look at the web console of the browser

**Expected behavior**
File should be uploaded.

**Example XHTML**
```html
<h1>Primefaces Test - FileUpload with BlockUI</h1>
<h:form id="frmTest">
        <p:blockUI widgetVar="blockerObj"
                block="frmTest"
                trigger="button"/>

        <p:commandButton id="button"
                value="Click me!"/>

        <p:fileUpload id="stopsetFile"
                listener="#{testView.handleFileUpload}"
                auto="true"
                mode="advanced"/>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

    @Getter
    @Setter
    private UploadedFile file;

    public void handleFileUpload(final FileUploadEvent event) {
        System.out.println("Filename = " + event.getFile().getFileName());
    }

    public void handleFileUpload(final FilesUploadEvent event) {
        for (UploadedFile _file : event.getFiles().getFiles()) {
            System.out.println("Filenames = " + _file.getFileName());
        }
    }

}
```

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/7151

Can you try the solution posted in there please?

**Comment by Charriu83** [comment]
Good morning melloware,
the workaround from #7151 fixed the JS error. In the example project the listener is now called.

In my project the listener is still not called and file is always NULL. No more JS errors and no errors in the java console.

**Comment by melloware** [comment]
Hmmm if you remove BlockUI from your project does the file upload work?  You may be having some other issue unrelated to blockui.

**Comment by Charriu83** [comment]
Hello again,
it was a problem with Jetty v10. We need some additions to get the file upload work properly:

```
        // add MultipartConfigInjectionHandler to make Primefaces FileUpload working
        MultipartConfigInjectionHandler multipartConfigInjectionHandler = new MultipartConfigInjectionHandler();
        HandlerCollection collection = new HandlerCollection();
        collection.addHandler(context); // add all "real" handlers
        multipartConfigInjectionHandler.setHandler(collection);
```

Found here https://stackoverflow.com/a/51555219.

**Comment by melloware** [comment]
thanks for posting back about your issue and solution.

**Comment by agharta** [comment]
Hi all,
In 10.0.6 problem persists.
In advanced mode, my workaround is setting global="false" to p:fileUpload component, and all works fine (because fileupload have its upload bar).

Has anyone tried this solution? What do you think about it @melloware ?

Regards

**Comment by melloware** [comment]
@agharta yes this problem is in 10.0.6 because you see this ticket is marked fixed in 11.0.0. So yes you will still see the issue but I posted a fix if you need it right now you can implement in your project right now.

See this solution: https://github.com/primefaces/primefaces/issues/7151#issuecomment-804050300

**Comment by agharta** [comment]
Ah! I see! Sorry, my mistake.
Ok, for my situation the global="false" option is actually a valid solution and doesn't generate collateral effects. 
When 11 will be released l'll go back to global="true" and test again it.

Cheers

**Comment by melloware** [comment]
@agharta why not use my MonkeyPatch in the other ticket?  It will allow you to use global="true" right now?

**Comment by agharta** [comment]
@melloware  because I tend not to override external frameworks: more generally, if any incompatibility with the override is introduced in the future version 11 or later, then my entire product will suffer.
I prefer - where possible - to stick to what is provided by the framework and, if necessary, to rely on the migration guide.

global = "false" actually makes sense - at least to me - in fileupload with advanced mode and autoupload. 

It's just my habit :-)

Thanks for your patience

**Comment by melloware** [comment]
understood but I usually add these monkeypatchs to a file called patch.js with @TODO "Remove in 11.0.0" etc.  Just my preference.  And then when a new PF comes out I simply review my patch.js file for what I can remove.

**Comment by agharta** [comment]
May be a solution: one unique patch file to keep reviewed. You're right too. 
Ok, I evaluate this way with my colleagues.
Thanks a lot for the tip!

Best regards
