### ISSUE TITLE
ToolbarGroup: Align="right" doesn't work

### ISSUE THREAD

**Issue by hfluz** [primefaces/primefaces#7338]
**Describe the defect**
In Primefaces 8 I had many toolbars that have only buttons aligned to right, like the one below:

![image](https://user-images.githubusercontent.com/832674/119228000-240d5f80-bae7-11eb-9f24-a57cc118f6c3.png)

After updating to Primefaces 10, the alignment to right doesn't work anymore:

![image](https://user-images.githubusercontent.com/832674/119228035-5e76fc80-bae7-11eb-9bcc-6857b9e508cb.png)

**Reproducer**
https://github.com/hfluz/primefaces-test

**Environment:**
 - PF Version: 10.0.0 and 11.0.0-SNAPSHOT
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: all

**To Reproduce**
1. Just open the reproducer's test page.

**Expected behavior**
Align="right" property should be respected, but it's ignored.

Instead, the only way to align a toolbarGroup to the right is adding another toolbarGroup first, since the second one will be aligned to right. Since I didn't find anything about this change in the migration guide, I assume it wasn't intended.

I belive this is the commit that broke it: https://github.com/primefaces/primefaces/commit/5365f7c0c17c6cf6b6e03b0c80eb0abd9b0ef2d0#diff-29a14603d40c8eed580bde9d89fa970008bfe6763f254edd13682ce96e21831b

ui-toolbar-group-left and ui-toolbar-group-right have exactly the same styles after this change.

**Comment by melloware** [comment]
Assigning to @sqores to review since he made the change.

**Comment by buunsal** [comment]
Although the toolbar group on the left is empty, it needs to be rendered. Issue stems from this. No need to add an extra css. I'll fix it next week.
