### ISSUE TITLE
Showcase: Include imports in bean code snippets

### ISSUE THREAD

**Issue by cd2357** [primefaces/primefaces#7342]
**Description**

Some classes used are ambiguous (same class name in different packages).

For example
* `org.primefaces.model.chart.LineChartModel` vs `org.primefaces.model.charts.line.LineChartModel`
* `javax.faces.view.ViewScoped` vs `javax.faces.bean.ViewScoped`

This can make it hard for users to get value from the provided code snippets. They might use the snippet but it might not work, just because they may have used the wrong import.

**Describe the solution you would like**

In the Java code snippets from the [showcase](https://www.primefaces.org/showcase/index.xhtml) please also provide the relevant imports.

Thanks.

**Comment by melloware** [comment]
Can you please report this issue under the Showcase project instead found here: https://github.com/primefaces/primefaces-showcase

Thanks!
