### ISSUE TITLE
HotKey: allow two different combinations for Mac and PC

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7344]
On Mac you might want to use `command+e` (`meta+e`) while on PC you would want to use `ctrl+e` for the same action.

We could do:

1. introduce a new attributes `bindMac` and use `bind` for PC
2. introduce new attributes `bindMac` and `bindPC` and deprecate `bind`
3. allow JSON in `bind`, for example `{pc:'ctrl+e',mac:'meta+e'}`
4. introduce a new key name, like `metaCtrl` which translated to `command` or `ctrl` based on the OS

**Comment by melloware** [comment]
I see some weird Meta key handling already in HotKey.js.

```javascript
      // metaKey is triggered off ctrlKey erronously
      if (event.metaKey && !event.ctrlKey && special !== "meta") {
        modif += "meta+";
      }

      if (event.metaKey && special !== "meta" && modif.indexOf("alt+ctrl+shift+") > -1) {
        modif = modif.replace("alt+ctrl+shift+", "hyper+");
      }
```

I also noticed Meta is not listed under special keys?

How about a new property `osAware` so `osAware="true"` will be CTRL on PC and META on MAC.  I think that is the proper https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by jepsar** [comment]
Yeah I noticed meta. But isn't it mapped to the Windows key on a PC? But apart from the command button, the delete button also requires special handling. And Mac has a function key. So option 4 is no good.

**Comment by jepsar** [comment]
I think this should be done with option 1. @melloware can you please assign me?

**Comment by melloware** [comment]
Done
