### ISSUE TITLE
MenuItem - inconsistency of the default value of the "global" attribute in UIMenuItemBase and DefaultMenuItem

### ISSUE THREAD

**Issue by milansie** [primefaces/primefaces#7349]
Hello,

I don't know correct category - it's not defect, maybe a question or something..

We noticed different default value in "global" atribute in MenuItems.  

Default value of "global" atribute  = true in UIMenuItemBase (and all other components), but false ("not defined") in dynamic DefaultMenuItem. 

Is there any reason for that? Could it be changed for same value - for clarity  and better usability? 

Thanks

**Comment by melloware** [comment]
Not sure if there is any reason to it other than I assume PrimeTek did not want to trigger the global AJAX indicator every time you pressed a menu option by default.  I wonder if we should change DefaultMenuItem to `false` as well?

**Comment by milansie** [comment]
Umm, it is `false` in DefaultMenuItem. Question was, if it could be `true`, same as in static (xhtml) menuItem (UIMenuItemBase).
I understand that someome did not want to trigger global ajax indicator everytime - but why they do that just in part of cases? In my opinion it make sense to do it same way all the time - either way...

**Comment by melloware** [comment]
Yep not sure where or why the original decision was made.  They should be consistent.

**Comment by milansie** [comment]
Thank you very much. Should I close issue, or it will be closed automatically by background processes after release?
