### ISSUE TITLE
p:diagram is not showing correctly with extensions pe:layout

### ISSUE THREAD

**Issue by mandrader** [primefaces/primefaces#735]
Is there any way to solve this? <pre>Issue 8187:    diagram is not showing correctly...it is a bug on pe:layout or on <p:diagram>? <a href="https://code.google.com/p/primefaces/issues/detail?id=8187">Issue 8187</a></pre>

**Comment by tandraschko** [comment]
does it work correctly in e.g. a dialog or something?

**Comment by melloware** [comment]
Is this still valid @mandrader with PF 6.1 and extensions 6.1?

**Comment by melloware** [comment]
@tandraschko I say close this issue.  No follow up in 2 years and the Google Code issue originally said it was resolved.
