### ISSUE TITLE
MediaPlayer/PhotoCam: remove Flash support

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7354]
> With Flash's EOL announced, many browsers took steps to gradually restrict Flash content (caution users before launching it, eventually blocking all content without an option to play it). By January of 2021, all major browsers started blocking Flash without ability to play it. Only IE11, niche browser forks, and some browsers built for China plan to continue support. Furthermore, excluding the China variant of Flash, Flash execution software has a built-in kill switch which prevents it from playing Flash after January 12, 2021.[65] In January 2021, Microsoft released an optional update KB4577586 which removals Flash Player from Windows; in July 2021 this update will be pushed out as a security update and applied automatically to all remaining systems.[66]

https://en.wikipedia.org/wiki/Adobe_Flash

**Comment by melloware** [comment]
Photocam also has an SWF fallback we should remove as well.
