### ISSUE TITLE
Responsive option for ConfirmDialog

### ISSUE THREAD

**Issue by ulspider** [primefaces/primefaces#736]
I don't find the "responsive" attribute in confirmDialog. Is it a mistake ?

**Comment by mertsincan** [comment]
PrimeFaces 5.3 doesn't support 'responsive' feature on Confirm Dialog. Only p:dialog have responsive attribute. We can add this feature in 5.3.x and 5.4.

**Comment by funfried** [comment]
+1

**Comment by cagataycivici** [comment]
+1
