### ISSUE TITLE
InputMask: Disabled or ReadOnly breaks the page

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7362]
**Environment:**
 - PF Version: _10.0_
 - JSF + version: ALL
 - Affected browsers: ALL

Forum Post: https://forum.primefaces.org/viewtopic.php?f=3&t=66983

**To Reproduce**
[pf-inputmask.zip](https://github.com/primefaces/primefaces/files/6548359/pf-inputmask.zip)

1. Run the reproducer the menu and save buttons do not work and no JavaScript errors are thrown.
2. Set `readonly="false"` and `disabled="false"` the page begins to work again.

**Expected behavior**
The page should work properly with `readonly` or `disabled` InputMasks.

**Example XHTML**
```html
<h:form id="frmTest">
  <p:inputMask value="#{testView.string1}" mask="*****-*****-*****-*****" maxlength="23" size="55" readonly="true"/>
</h:form>
```

**Comment by melloware** [comment]
This MonkeyPatch fixes it right now...
```javascript
if (PrimeFaces.widget.InputMask) {
    PrimeFaces.widget.InputMask.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        if (this.cfg.mask && !this.jq.is('[readonly]') && !this.jq.is(':disabled')) {
            this.jq.inputmask('remove').inputmask(this.cfg);
        }
        PrimeFaces.skinInput(this.jq);
    }
};
```

**Comment by educalize** [comment]
In these cases the popup does not work either.
