### ISSUE TITLE
DataTable: check remove of SelectableDataModelWrapper

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7368]
i reintroduced SelectableDataModelWrapper because of a bug
this was added to fix a bug between filtered values and the selection of a value

@melloware @christophs78 could you try to add some integration tests for this?
im not sure what the case was as its not in the commit comment of 2011 ;D 

maybe like you select a value, filter (and therefore remove the selection from the displayed list) and do something with the table? no idea TBH

**Comment by melloware** [comment]
I know with @Rapster we also could never figure out the use case for SelectableDataModelWrapper either.  Its been there forever but we could not tell what problem it was solving!

**Comment by tandraschko** [comment]
do we have tests wich tries different states with selection + filtering? If yes, lets remove it

**Comment by melloware** [comment]
We will check i am pretty sure we do have selection and filtering together.

**Comment by melloware** [comment]
Added Selection with Filtering test and verified its passing:
https://github.com/primefaces-extensions/primefaces-integration-tests/commit/39cbcb121b582e0b504fc4b6b5a8d8cd4a5ea125

I filter the table and make sure the selection is held and then I unfilter the table and make sure the selection is held.

Would you like me to remove SelectableDataModelWrapper locally and re-run the test?

**Comment by melloware** [comment]
OK then I removed the SelectableDataModelWrapper code and rebuilt and re-ran the Integration Test and its still passing.  So yeah the same conclusion @Rapster came to I have no idea what problem it was trying to solve but it definitely does not seem needed.

**Comment by christophs78** [comment]
Hm. Maybe stupid question or i overlook something...
I think SelectableDataModel and SelectableDataModelWrapper is ONLY used for LazyDataModel.
I placed breakpoints to the SelectableDataModelWrapper-constructors and run eg DataTable021Test. We never run into this breakpoints.
DataTable only creates new instances of SelectableDataModelWrapper when there is already a instance of SelectableDataModel. (=LazyDataModel)
Maybe we need to add some more integration tests for LazyDataModel + Selection + Filtering. (not sure whether we already have some of them)

**Comment by christophs78** [comment]
Think we need to add filtering to our existing DataTable006Test. (DataTable006Test checks LazyDataModel together with Selection but currently misses filtering.)

**Comment by melloware** [comment]
Yep I agree. I can take care of it.

**Comment by christophs78** [comment]
> Yep I agree. I can take care of it.

Please. Thank you!

**Comment by melloware** [comment]
Added test: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/79472d2e20e1b603b40e970c3e5bc9378cad472c

it fails with...
```
SEVERE: class org.primefaces.extensions.integrationtests.datatable.ProgrammingLanguageLazyDataModel cannot be cast to class java.util.List (org.primefaces.extensions.integrationtests.datatable.ProgrammingLanguageLazyDataModel is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class org.primefaces.extensions.integrationtests.datatable.ProgrammingLanguageLazyDataModel cannot be cast to class java.util.List (org.primefaces.extensions.integrationtests.datatable.ProgrammingLanguageLazyDataModel is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
	at javax.faces.model.ListDataModel.setWrappedData(ListDataModel.java:122)
	at org.primefaces.model.SelectableDataModelWrapper.<init>(SelectableDataModelWrapper.java:39)
	at org.primefaces.component.datatable.DataTable.updateValue(DataTable.java:314)
	at org.primefaces.component.datatable.feature.SelectionFeature.decode(SelectionFeature.java:63)
```

**Comment by melloware** [comment]
If I remove the SelectableDataModelWrapper everything works.

**Comment by christophs78** [comment]
I extended @melloware integration-test and still looks good with SelectableDataModelWrapper removed.
And if some comes up with another corner-case after this we have to further extend our integration-tests.

**Comment by tandraschko** [comment]
perfect, i will remove it again

**Comment by christophs78** [comment]
Maybe `SelectableDataModelWrapper` was introduced at some point for https://primefaces.github.io/primefaces/10_0_0/#/components/datatable?id=rowkey?

**Comment by melloware** [comment]
I think we should update that doc for 10.0 and 11.0 removing that blurb about SelectableDataModel.  If should just say you must implement `rowKey`.
