### ISSUE TITLE
DataTable: filteredValues broken with scope bigger then ViewScoped

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7373]
See #7336

bah
i basically restored #5481 and i think the behavior was partly correct (they were restored on postback only, not on pageload/f5)
the filteredValues are stored in the SessionScoped and therefore it should be restored on f5 actually, or not?
the problem is that the filter-input doesnt contain the old text ("2010" in the test) anymore as its component state (viewscoped)

so one state is stored in sessionscoped bean, the other state is stored in viewscoped component state, thats a problem

we have 3 possible solutions

1) should we say, filteredValues should not be used with SessionScoped?
2) make filteredValues write-only but e.g. my customer uses it in read-only manner
3) add a note to the docs, that when used SessionScoped, you also have to maintain filterBy (or set MVS) and save it in session (is this possible?) So that filteredValues and filterBy matches when pressing f5

**Comment by melloware** [comment]
I think I like option 3.  For the most part if people want their filters remembered they use MVS right?

**Comment by christophs78** [comment]
Add a note to docs sounds good. Same opinion like @melloware - MVS is the way to get this done.

**Comment by tandraschko** [comment]
would one of you add notes to the docs?
what should we do with the failing integration test? switch to ViewScoped or remove it?

**Comment by christophs78** [comment]
> what should we do with the failing integration test? switch to ViewScoped or remove it?

i disabled the related i-test via
```java
@Disabled("Disabled because DataTable-filter does not support @SessionScoped - see https://github.com/primefaces/primefaces/issues/7373")
```
--> all our i-tests are passing
