### ISSUE TITLE
InputNumber: switch to PrimeTek native code

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#7375]
Like;
https://primefaces.org/primereact/showcase/#/inputnumber

**Comment by mertsincan** [comment]
Maybe, inputnumber can be ported from PrimeReact in the future. For now, the pros and cons of both APIs are comparable.

**Comment by mertsincan** [comment]
For now, InputNumber component in PrimeReact needs to prove itself a little more.

**Comment by melloware** [comment]
@mertsincan Primefaces has been using AutoNumeric for 12 years and it's very mature.  I am not sure moving to a custom InputNumber is worth the "bang for buck" of all the possible regression bugs?

**Comment by melloware** [comment]
Will close for now we can re-open in the future if we deem its necessary but PF has been very stable with AutoNumeric not sure its worth the regression bugs effort.
