### ISSUE TITLE
DataTable: scroll headers do not align with body cells in Chromium 91 based browsers

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7379]
**Describe the defect**
In scroll mode, headers do not align with body cells. See:

https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml

<img width="1111" alt="Screenshot 2021-05-31 at 14 37 07" src="https://user-images.githubusercontent.com/7500178/120290979-216af100-c2c3-11eb-8ab7-e0511cdade25.png">

**Environment:**
 - PF Version: _10.0.0_, _11.0.0-SNAPSHOT_
 - Affected browsers: _Chrome Version 91.0.4472.77, Safari Version 14.0.3 (16610.4.3.1.7)_ (not with Firefox 88.0.1)

I haven't noticed this on previous Chrome versions

**Comment by buunsal** [comment]
Can you test it @jepsar ? It should be fixed.

**Comment by melloware** [comment]
MonkeyPatch:
```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.getScrollbarWidth = function() {
        if (!this.scrollbarWidth) {
            this.scrollbarWidth = PrimeFaces.calculateScrollbarWidth();
        }

        return this.scrollbarWidth;
    }
}
```

**Comment by jepsar** [comment]
> Can you test it @jepsar ? It should be fixed.

@sqores Looking good! Thanks!

**Comment by melloware** [comment]
Looks like we aren't the only ones who had Chrome 91 issues: https://github.com/fullcalendar/fullcalendar/releases/tag/v5.7.2

**Comment by buunsal** [comment]
"Chrome 91 updates the way it renders tables on web pages. This change fixes known issues and brings Chrome closer to the behavior of other browsers, so we expect the impact to be minimal. However, you should test important workflows in your environment for unexpected issues. A full explainer is available https://docs.google.com/document/d/16PFD1GtMI9Zgwu0jtPaKZJ75Q2wyZ9EZnVbBacOfiNA/edit"
