### ISSUE TITLE
FileUpload: pass files count in FileUploadEvent

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#7390]
**Description**
If both advanced mode and multiple is set for FileUpload component, every file is uploaded separately via handleFileUpload(FileUploadEvent event)
However, it is not easy to determine which one is the last to trigger some subsequent action.

Currently I utilize remoteCommand, which passes the number of uploaded files to backend via FleUploaded onstart event.

```
<h:form id="upload" enctype="multipart/form-data">

    <p:remoteCommand name="setFilesCount" action="#{bean.setFilesCount}" />

    <p:fileUpload
                  mode="advanced"
                  multiple="true"
                  listener="#{bean.handleFileUpload}"
                  widgetVar="fileUploader"
                  onstart="setFilesCount([{name:'filesCount', value: PF('fileUploader').files.length}]);"/>
```
Then in the backend I check if the count matches and if so, I perform some processing
```
    public void handleFileUpload(FileUploadEvent event) throws IOException {

        UploadedFile file = event.getFile();
        fileStreamMap.put(file.getFileName(), file.getInputStream());
        
        if (fileStreamMap.size() == filesCount) {
```

**Describe the solution you would like**
I can imagine that total count could be passed via that FileUploadEvent, so instead of helper filesCount variable set via remoteCommand I could simply use:
 ```
    public void handleFileUpload(FileUploadEvent event) throws IOException {

        UploadedFile file = event.getFile();
        fileStreamMap.put(file.getFileName(), file.getInputStream());
        
        if (fileStreamMap.size() == event.getFilesCount()) {
 ```

**Comment by tandraschko** [comment]
Similar to: https://github.com/primefaces/primefaces/issues/3424

**Comment by tandraschko** [comment]
@jan-tosovsky-cz would you like to contribute this feature?

**Comment by jan-tosovsky-cz** [comment]
@tandraschko tbh I am not JS expert (it would be tough to find proper lines in PF codebase and create tests)
