### ISSUE TITLE
Datatable: Row remains selected after clearing backing bean

### ISSUE THREAD

**Issue by doteo78** [primefaces/primefaces#7391]
**Describe the defect**
Basic datatable with single selection: when a row is selected and an action that clears the backing bean selected row object is executed, the row remains selected in the browser.

This only happens when the datatable has declared the "rowSelect" event.

**Reproducer**
Run the attached project (mvn jetty:run) and visit http://localhost:8080/primefaces-test/. Then select a row and click "Unselect row" button. The row remains selected in the browser.

It works fine (the row is no longer selected) if you comment out the following line in test.xhtml:

```html
<p:ajax event="rowSelect" listener="#{testView.onSelectProduct}" />
```

**Environment:**
 - PF Version: _10.0.x_
 - JSF + version: _Mojarra 2.2.20 and MyFaces 2.3.9_
 - Affected browsers: _ALL_

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/6608723/primefaces-test-master.zip)

**Comment by tandraschko** [comment]
@melloware @christophs78 do we have a integration test for this?

**Comment by melloware** [comment]
We have tons of selection tests.  Let me add this specific case and see.

**Comment by tandraschko** [comment]
integration moved to this repo now, feel free to work on it :)

**Comment by melloware** [comment]
Failing Integration Test provided.

**Comment by melloware** [comment]
here is a workaround for now. Give your Datatable a widgetVar like `widgetVar="selectTable"` and then add this to your command button.

```xml
<p:commandButton 
   process="@this" 
   update="@form"
   value="Unselect row" 
   action="#{testView.unselectRow}" 
   onclick="PF('selectTable').clearSelections();"
   oncomplete="PF('selectTable').unselectAllRows();" />
```

**Comment by tandraschko** [comment]
Did this work in 8.0?

**Comment by melloware** [comment]
Looks like it did in 8.0 the selection is cleared.   Attached is 8.0 reproducer.
[pf-7391-80.zip](https://github.com/primefaces/primefaces/files/6631643/pf-7391-80.zip)

**Comment by doteo78** [comment]
> here is a workaround for now. Give your Datatable a widgetVar like `widgetVar="selectTable"` and then add this to your command button.
> 
> ```
> <p:commandButton 
>    process="@this" 
>    update="@form"
>    value="Unselect row" 
>    action="#{testView.unselectRow}" 
>    onclick="PF('selectTable').clearSelections();"
>    oncomplete="PF('selectTable').unselectAllRows();" />
> ```

That's what I'm doing for now. Indeed I am checking if there were validation errors because I don't want to unselect the row if the action (business logic) could not be done. For example:

```
oncomplete="if(!args.validationFailed) {PF('$dtCategories').unselectAllRows()}"
 ```

**Comment by melloware** [comment]
When I debug 8.0 vs 10.0 in the Javascript for `setupSelection` the `_selection` value holder has the value in 10.0 and does not in 8.0.

```javascript
setupSelection: function() {
        this.selectionHolder = this.jqId + '_selection';
        this.cfg.rowSelectMode = this.cfg.rowSelectMode||'new';
        this.rowSelector = '> tr.ui-widget-content.ui-datatable-selectable';
        this.cfg.disabledTextSelection = this.cfg.disabledTextSelection === false ? false : true;
        this.cfg.selectionPageOnly = this.cfg.selectionPageOnly === false ? !this.cfg.paginator : true;
        this.rowSelectorForRowClick = this.cfg.rowSelector||'td:not(.ui-column-unselectable):not(.ui-grouped-column),span:not(.ui-c)';

        var preselection = $(this.selectionHolder).val();
```

Investigating more.

**Comment by melloware** [comment]
I think its the SelectionFetaure does a `decode` but there is never anything on the `encode` that checks and re-valuates the selection and sets the `selectedRowKeys` value based on the user setting.

**Comment by melloware** [comment]
Figured it out. Thanks for the reproducer helping me debug it!

**Comment by doteo78** [comment]
Working properly with version 10.0.6. Thanks!
