### ISSUE TITLE
MoveScriptsToBottom: Firefox flash of unstyled content (FOUC)

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7395]
**Description**
Optimizing a PrimeFaces app using the following tricks...

- PrimeFaces MOVE_SCRIPTS_TO_BOTTOM
- OmniFaces CombinedResourceHandler
- PrimeFaces Extensions CombinedResourceHandler Helper https://github.com/primefaces-extensions/primefaces-extensions/issues/293

Causes the Firefox Flash of Unstyled Content (FOUC) issue.   If you go to the PFE Showcase using Firefox: https://www.primefaces.org/showcase-ext/views/home.jsf and then start bouncing around different links you see a flashing effect. It looks like the page is being rendered without CSS and then the CSS is applied.  It is not an issue on any Chrome based browser or IE.  Its specific to Firefox

Firefox Issue: https://stackoverflow.com/questions/21147149/flash-of-unstyled-content-fouc-in-firefox-only-is-ff-slow-renderer

Firefox Bug open for years: https://bugzilla.mozilla.org/show_bug.cgi?id=1404468

OmniFaces Issue: https://github.com/omnifaces/omnifaces/issues/632

**Comment by tandraschko** [comment]
its related to the layout plugin, because it requires javascript to display correctly?
therefire it doesnt occur with pure css layouts?!

**Comment by melloware** [comment]
No that is just the example @stolp was able to verify it in all his apps as well as all of my client apps which do not use layout.  Its purely a FF issue because it renders the HTML before applying CSS if everything is deferred like we have it.  The PFE Showcase was just the easiest place to demo the problem.

**Comment by melloware** [comment]
Sorry forgot to mention you also have to be using all 3 optimizations above which removes PrimeFaces theme.css and JS code from headrenderer and also moves it to the bottom of the page deferred.

https://github.com/primefaces-extensions/primefaces-extensions/issues/293
