### ISSUE TITLE
Autocomplete dropdown width in p:cellEditor

### ISSUE THREAD

**Issue by nicolas-mu** [primefaces/primefaces#740]
If we use autocomplete in a cell editor, and the width of the autocomplete is 100%,
the dropdown button is not part of the 100% in the column.
I mean, if I have an autocomplete with dropdown=true in a cellEditor and width=100%,
I was hopping to see the whole autocomplete (input text + dropdown button) but it's not like this
now, the input text use 100% of the column's width and the dropdown button is hidden.
If I use the mouse to resize the column and make it bigger then i can see all (input text + dropdown button).
Is there a way to always see all (input text + dropdown button) ?
I think when we use dropdown, the button should be part of the whole component to calculate the size (not only input text)

**Comment by melloware** [comment]
No example or sample project or screenshots.  Ticket is 4 years old and this can be accomplished by CSS so closing ticket.
