### ISSUE TITLE
Showcase: add profiles for servlet containers

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7408]
in general the showcase pom/build needs some facelift 
we should add a profile for servlet-containers, which contains the JSF+CDI etc. impls
so that one could also build the showcase for EE containers

also some readme improvements

**Comment by tandraschko** [comment]
we should add a "servlet-container" profile and move all EE dependencies to this profile and activate by default

but we would also need the possibility to empty jsf-listener for EE and introduce a second filter prop cdi-listener

anyone interessted?

**Comment by tandraschko** [comment]
any review welcome

**Comment by tandraschko** [comment]
mvn clean package -Pee works fine on TomEE

**Comment by melloware** [comment]
This looks great @tandraschko very clever!
