### ISSUE TITLE
Showcase: Let the user select the localization

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7412]
**Description**
The fact that PrimeFaces now comes with built-in localization should be made more prominent, so more localization input could be gathered from the community.

To test and verify localization files, it would be great if the showcase can be switched to other languages by the user.

**Describe the solution you would like**
I would like to see an additional selector (like the theme selector) on every page, letting the user select from all the available localizations.

It may or may not be useful to autoselect the localization based on the browser language settings.

**Comment by jepsar** [comment]
There is a locale selector in the right bar:

<img width="585" alt="Screenshot 2021-06-10 at 15 09 04" src="https://user-images.githubusercontent.com/7500178/121530560-d442f980-c9fd-11eb-9425-04bc219f89c9.png">

**Comment by melloware** [comment]
Yep I already added it as @jepsar pointed out!
