### ISSUE TITLE
DataTable: Column FilterFunction not being called

### ISSUE THREAD

**Issue by mafulafunk** [primefaces/primefaces#7413]
Describe the defect
filterFunction of column in dataTable not called when

    <context-param>
        <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
        <param-value>client</param-value>
    </context-param>

is set to "client"

Reproducer

https://github.com/mafulafunk/primefaces-test

Branch that works: master
Branch showing the issue: issue

Environment:

PF Version: 10.0.0
JSF + version: Default as in Reproducer
Affected browsers: Safari

In the reproducer got to:
http://localhost:8080/primefaces-test/

When the filter method is called. System out printlns are thrown out on the terminal.

There is explicitly no filter logic implemented in the method, it was only meant to show that toggling the context-parameter exposes the behaviour of not calling the "filterFunction"

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/6987 already fixed in Elite 10.0.2

**Comment by mafulafunk** [comment]
Without further knowledge on to what Elite 10.0.2 refers to precisely 

I retested with the 11 Snapshot build

I installed locally of the commit ebee2cc303dea786761a0b15a277529e94434ee7
of PrimeFaces main branch.
Problem still persists.

**Comment by melloware** [comment]
Your example works fine for me with 11.0.0-SNAPSHOT.
[pf-7413.zip](https://github.com/primefaces/primefaces/files/6634021/pf-7413.zip)

Sorting and Filtering both work fine.

**Comment by melloware** [comment]
Oh hang on I see what you mean. FilterFunction is not being called by the default `filterBy="#{customer.name}"` is being called.

**Comment by melloware** [comment]
Its actually got nothing to do with Client side state saving. FilterFunction is not being called is the real bug not that your table isn't filtering.

**Comment by melloware** [comment]
Integration Test proving the bug: https://github.com/primefaces/primefaces/pull/7415

**Comment by melloware** [comment]
@Rapster any chance you can look at this?  I can see on page initialization its a proper `FunctionFilterConstraint` however when the filter is actually called i can see in the debugger its now a `StartsWithFilterConstraint` and the FunctionFilterConstraint is gone.

**Comment by Rapster** [comment]
I can have a quick look at it

**Comment by melloware** [comment]
Integration test now passing!  Thanks @Rapster

**Comment by cloudbuster13** [comment]
Dear @melloware, could you label the Fix #7413 to upcoming primefaces elite v10.0.8. Using PF 10 with Wildfly 17 HA Cluster we're facing heavily this issue of DataTable FilterFunctions gets lost after deserialization as it is transient, many thx.

**Comment by melloware** [comment]
@cloudbuster13 do you have a PRO account?  That is your best bet of getting this fix into 10.0.8 as it looks like Rapster changed 14 files to make this work.  I add the `elite` label but its up to @mertsincan whether it makes it into 10.0.8 or not.
