### ISSUE TITLE
Inplace: editor=true buttons not focusable in Safari

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7416]
**Describe the defect**
Inplace: editor=true buttons not focusable in Safari

<img width="273" alt="Screenshot 2021-06-11 at 08 59 44" src="https://user-images.githubusercontent.com/7500178/121644772-ba53f600-ca93-11eb-85df-3ae3f91223bd.png">

**Reproducer**
* https://www.primefaces.org/showcase/ui/input/inplace.xhtml
* Click "PrimeFaces" (under header "Edit")
* Press tab

**Environment:**
 - PF Version: _10.0_, _11.0.0-SNAPSHOT_
 - Affected browsers: _Safari 14.0.3 (16610.4.3.1.7) (macOS)_

@melloware can be assigned to me

**Comment by jepsar** [comment]
Apparently this is an issue with Safari and buttons in general...
https://stackoverflow.com/questions/42758815/safari-focus-event-doesnt-work-on-button-element
https://gist.github.com/cvrebert/68659d0333a578d75372

With `[option]`+`[tab]` it does work (yeah.. really)

@melloware please remove the milestone

**Comment by melloware** [comment]
Removed milestone and marked it WontFix since there is nothing we can fix.
