### ISSUE TITLE
Development: multi-module + shade + IDE - issues

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7419]
Not a issue for PrimeFaces-users, but a issue for people working on this OpenSource-project.

IntelliJ does not understand shaded classes in multi-module-projects: https://stackoverflow.com/questions/30407065/getting-intellij-to-import-shaded-dependencies-in-a-multi-module-maven-project/30898810

Causes e.g. issues for showcase-module:
![image](https://user-images.githubusercontent.com/10461942/121746436-2d965000-cb06-11eb-8c39-e408fbb14129.png)

And i can´t start showcase on Tomcat via IntelliJ-run-configuration any more. (so i´m able do debug showcase/PrimeFaces) I have to fallback to the jetty-plugin.

I don´t expect a short-term-solution for this. Just want to create some awareness of this issue.

**Comment by melloware** [comment]
I have the same issue with Eclipse

**Comment by christophs78** [comment]
Maybe we can create an optional maven-profile for showcase-module which tries to compensate this shading issues for our dev-environments.

**Comment by melloware** [comment]
I can't get Showcase or Integration Tests to work in the IDE so I have to in Eclipse use the option ""Maven -> Disable Workspace Resolution" so it doesn't hook the projects up instead it always uses the JAR from .m2.  This makes it work but then doesn't allow me to DEBUG PF code while running the IT or Showcase.

**Comment by tandraschko** [comment]
@melloware @christophs78 

i wonder if we should:
1) add javaee-api into root pom as provided dependency
    we would not need jsf,cdi,bval,servlet api in all modules anymore
2) add shared dependencies (openpdf, fileupload, poi, rome) into root pom dependency-management

**Comment by melloware** [comment]
@tandraschko That is 100% my preferred way of handling dependencies and kinda what we do in the PFE multimodule. So we can just change a dependency in 1 place even if its used in multiple pom's.

**Comment by christophs78** [comment]
good idea!
