### ISSUE TITLE
SelectOneRadio and SelectBooleanCheckbox are not pixelperfect

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#742]
Hi, ive noticed that these two components look odd compared to default html one. Is it possible to make it more crisp and 100% centered like the html components? 

Especially if the background gradient is removed, the dot doesn't look like it is centered

![Image of Compnents](http://abload.de/img/primefacesbvjvz.png)

**Comment by mertsincan** [comment]
Please try with;

```
.ui-state-active,
.ui-state-hover,
.ui-state-default {
     box-shadow: none !important;
}
```

**Comment by cnsgithub** [comment]
Yea thanks, this solves it partly, thanks for the hint, however in case of the radio button the dot is still not exactly centered , seems to be 1px off in 2 axis, if i change the ui-radiobutton / ui-radiobutton-box width and height from 16px to 17px it seems to be better though..

Will your CSS be included with the next version or do i have to keep it in my code?

**Comment by melloware** [comment]
@mertsincan was this ever implemented in PF itself?  It seems like this would be a better default styling?

**Comment by cnsgithub** [comment]
Would like to bring this up again, the visuals of the radios and checkboxes are really ugly compared to the native ones. I'm sure this can be improved.

See for example:  https://lokesh-coder.github.io/pretty-checkbox/

They are scalable without becoming blurry.. (and misaligned, actually the're misaligned even with 100% zoom if you look closely)

It would also be possible to use Fontawesome instead of Images (as this could be easier since PF already includes it)

Images again to see the uglyness compared to scalable ones.

![check](https://user-images.githubusercontent.com/13161711/27083710-b54e71e4-5049-11e7-978d-c3654c7a909a.png)
![radio](https://user-images.githubusercontent.com/13161711/27083712-b6dea380-5049-11e7-9b36-3125553b71db.png)
![perfect](https://user-images.githubusercontent.com/13161711/27083714-b840d8d8-5049-11e7-9fa4-86f1e7664735.png)

**Comment by cnsgithub** [comment]
Possible CSS workaround:
Way better than using images..

```
.ui-radiobutton-box {
	text-align: center;
}
.ui-radiobutton-icon{
	margin: 0;
}
.ui-icon-bullet {
    background: none !important;
    display: inline;
}
.ui-icon-bullet::before {
	font-weight: normal;
	content: '\25CF';
	font-size: 18px;
	line-height: 13px;
	color: #7096ab;
}
```

Result:

![image](https://user-images.githubusercontent.com/13161711/27629480-c8537e60-5bf2-11e7-9bac-85a4c0fe20c5.png)

**Comment by cnsgithub** [comment]
Edit: See my answer here: https://github.com/primefaces/primefaces/pull/3233

And here: https://github.com/cnsgithub/primefaces-openicons

For those who want an easy solution for this..

**Comment by melloware** [comment]
This would be cool.

**Comment by cagataycivici** [comment]
Thank you for the PR however font icons are a premium feature in PrimeFaces, all premium templates replace the old png icons with font-awesome icons already, we need to keep it as it is.
