### ISSUE TITLE
PrimeExceptionHandler customizable logging

### ISSUE THREAD

**Issue by frunk** [primefaces/primefaces#743]
The PrimeExceptionHandler uses a "private static" field to define a logger. This cannot be overridden if you want to use other logging than java.util.logging.
Solution would be to implement "protected void log(...)" method that could be overridden in own extending class.

**Comment by tandraschko** [comment]
Not sure if i will introduce this.
JUL is used in many frameworks and bridges to log4j/slf4j etc. are available.
Also logging is used in many other places in PrimeFaces.

@cagataycivici WDYT?

**Comment by tandraschko** [comment]
Maybe it makes really sence for the current exception - but i will never change the whole logging to such a hack.
