### ISSUE TITLE
DialogFramework: resizeable is broken

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7437]
**Describe the defect**
Showcase; Dialog Framework --> Data
Modify DFView#chooseProduct
```java
Map<String, Object> options = new HashMap<>();
options.put("resizable", true);
options.put("draggable", true);
options.put("modal", true);
PrimeFaces.current().dialog().openDynamic("selectProduct", options, null);
```

draggable works, resizeable has no effect

**Environment:**
 - PF Version: 11.0-SNAPSHOT
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: Firefox, Chrome, Edge (probably all)

**Comment by melloware** [comment]
Are you sure it's not the same as the other open resizable issue where it's actually a theme issue. Check the other ticket to see if it's related.

**Comment by melloware** [comment]
#7154

**Comment by melloware** [comment]
@christophs78 were you able to check if this is a duplicate of #7154 ?

**Comment by christophs78** [comment]
Yes it´s the same issue like #7154.

**Comment by melloware** [comment]
Closing as duplicate.
