### ISSUE TITLE
FileUpload: Broken in 10.0.2

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#7438]
**Describe the defect**
File Upload is broken

**Environment:**
 - PF Version:  10.0.2
 - JSF + version:  Mojarra 2.3
 - Affected browsers: tested on Firefox, Chrome

**To Reproduce**
1. Open a page with a fileUpload component in 'simple' mode
2. Click the 'plus' button and select a file in the file browser
3. Nothing was selected !!
This worked perfectly in 10.0.1

**Usage**:
`<p:fileUpload mode="simple" skinSimple="true" value="#{bean.file}" />`

**Comment by Rapster** [comment]
Which impl: native, commons, auto? Any JS errors? Any exceptions?

**Comment by wlhUser** [comment]
I have to correct my data from the initial post: 
- the problem occurs with the 'simple' mode - 'advanced' mode works fine
- no JS errors
- no exceptions

**Comment by melloware** [comment]
The only fix made in 10.0.2 was this one: https://github.com/primefaces/primefaces/issues/7352

**Comment by Rapster** [comment]
Ctrl + F5? 😄

**Comment by wlhUser** [comment]
Yes, seems to be related to #7352.
My usage of fileUpload is:
`<p:fileUpload mode="simple" skinSimple="true" value="#{bean.file}" />`
For the case of 'skinSimple' something had been changed in the ticket mentioned above.
In case I do **not** use 'skinSimple', it works fine - (but does not look that nice)

**Comment by melloware** [comment]
So we need a PrimeFaces Test reproducer that uses both #7352 and your scenario above and we then must test both to ensure both work.

**Comment by melloware** [comment]
@wlhUser can you try this MonkeyPatch:

```javascript
if (PrimeFaces.widget.SimpleFileUpload) {
    PrimeFaces.widget.SimpleFileUpload.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        if (this.cfg.disabled) {
            return;
        }

        this.cfg.invalidFileMessage = this.cfg.invalidFileMessage || 'Invalid file type';
        this.cfg.invalidSizeMessage = this.cfg.invalidSizeMessage || 'Invalid file size';
        this.cfg.fileLimitMessage = this.cfg.fileLimitMessage || 'Maximum number of files exceeded';
        this.cfg.messageTemplate = this.cfg.messageTemplate || '{name} {size}';
        this.cfg.global = (this.cfg.global === true || this.cfg.global === undefined) ? true : false;
        this.sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];

        this.maxFileSize = this.cfg.maxFileSize;

        this.form = this.jq.closest('form');


        if (this.cfg.skinSimple) {
            this.input = $(this.jqId + '_input');
            this.button = this.jq.children('.ui-button');
            this.display = this.jq.children('.ui-fileupload-filename');

            if (!this.input.prop('disabled')) {
                this.bindEvents();
            }
        } else if (this.cfg.auto) {
            var $this = this;
            this.input = $(this.jqId);
            this.input.on('change.fileupload', function() {
                $this.upload();
            });
        }
    }
}
```

**Comment by melloware** [comment]
@wlhUser did you get a chance to try the above MonkeyPatch?  If it works for you I will submit a PR.

**Comment by wlhUser** [comment]
Not yet, I'm happy that it works without simpleSkin.
I'll give feedback after I tried it.

**Comment by wlhUser** [comment]
Have tested the proposed code, and can confirm it works with  simpleSkin='true'.
(Added it at the end of my xhtml file and re-executed the init method of the fileUpload widget,)

Thanks melloware

**Comment by melloware** [comment]
Thanks for testing! I am fixing it now!
