### ISSUE TITLE
Menubar/TieredMenu: mobile detection click handling

### ISSUE THREAD

**Issue by stefan-dan** [primefaces/primefaces#7439]
**Describe the defect**
On chromium based browsers and Safari, you should tap twice to open a submenu of a p:menubar, on Firefox it is working as expected. It's not a showcase bug, I can reproduce it on my private project.

**Reproducer**
Showcase: https://www.primefaces.org/showcase/ui/menu/menubar.xhtml

**Environment:**
 - PF Version: 10.0
 - JSF + version: Mojarra 2.2.20 or MyFaces 2.3.9
 - Affected browsers: Chrome, Edge, Safari, exept Firefox.
 
**To Reproduce**
1. On Google Chrome go to https://www.primefaces.org/showcase/ui/menu/menubar.xhtml?jfwid=3414e
2. Press F12 and then press Ctr+Shift+M to switch to resposive device
3. Tap on "File" menu -> nothing happens
4. Tap again on "File" menu, and it opens

**Expected behavior**
Submenu should open on the first tap, on all browsers.

**Example XHTML**
```html
<p:menubar>
            <p:submenu label="File" icon="pi pi-fw pi-file">
                <p:submenu label="New" icon="pi pi-fw pi-plus">
                    <p:menuitem value="Bookmark" icon="pi pi-fw pi-bookmark"/>
                    <p:menuitem value="Video" icon="pi pi-fw pi-video"/>
                </p:submenu>
                <p:menuitem value="Delete" icon="pi pi-fw pi-trash"/>
                <p:divider />
                <p:menuitem value="Export" icon="pi pi-fw pi-external-link"/>
            </p:submenu>
</p:menubar>
```

**Comment by melloware** [comment]
Confirmed this behavior even on 11.0-SNAPSHOT.

**Comment by melloware** [comment]
Temporary fix:

```xml
<p:menubar toggleEvent="click">
```

You can't use "hover" which is the default when in Touch mode.  I am going to submit a fix that switches `toggleEvent="click"` automatically if a mobile browser is detected.

**Comment by melloware** [comment]
MonkeyPatch:

```javascript
if (PrimeFaces.widget.TieredMenu) {
    PrimeFaces.widget.TieredMenu.prototype.bindItemEvents = function() {
        if (this.cfg.toggleEvent === 'click' || PrimeFaces.env.isTouchable(this.cfg))
            this.bindClickModeEvents();
        else if (this.cfg.toggleEvent === 'hover')
            this.bindHoverModeEvents();
    }
}
```
