### ISSUE TITLE
FileUpload : action listener with FilesUploadEvent as parameter unrecognized

### ISSUE THREAD

**Issue by zakhdar** [primefaces/primefaces#7441]
**Describe the defect**
I'm using FileUpload in advanced mode (uploader = auto) to upload multiple files , i'm using for that the File**s**UploadEvent as parameters of my actionListener,  (i'm testing the code of primefaces showcase) 

```
public void handleFilesUpload(FilesUploadEvent event) {
        for (UploadedFile f : event.getFiles().getFiles()) {
            FacesMessage message = new FacesMessage("Successful", f.getFileName() + " is uploaded.");
            FacesContext.getCurrentInstance().addMessage(null, message);
        }
    }
```

when i upload some files i get this error : 

`listener="#{testBean.handleFilesUpload}": Method not found: class  com.test.TestBean.handleFilesUpload(org.primefaces.event.FileUploadEvent)
`
actionListener with **FilesUploadEvent** as parameter are unrecognized.

If i replace **FilesUploadEvent** by **FileUploadEvent** it's work. 

it's normal ? i checked the doc of 10.0.0  and nothing on usage of **FilesUploadEvent**.

I see in showcase source code the method **public void handleFilesUpload(FilesUploadEvent event)**  it's present but never used.

JSF = Mojarra 2.3
AS = Wildlfy 23
Primefaces = master-SNAPSHOT 
Java Version = 11

**Comment by melloware** [comment]
You are not following this example exaclty: https://www.primefaces.org/showcase/ui/file/upload/basicAuto.xhtml

```xml
<p:fileUpload value="#{fileUploadView.files}" mode="simple" skinSimple="true" multiple="true"
                      auto="true"
                      process="@this" update="messages"
                      listener="#{fileUploadView.handleFilesUpload}"/>
```

Multiple with skinSimple="true is what triggeres the File(s) other than that its the singular File upload one at a time.

**Comment by zakhdar** [comment]
Hi @melloware , 

thank you for your response after some test it's work when mode="simple" skinSimple is related to theming.
