### ISSUE TITLE
FileUpload: upload to an API

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#7442]
**Description**
Upload file to an API would be great. 

**Describe the solution you would like**
We have a separate media server  where we like to upload all the media files to that without interfering and avoid slowing down the web application.
It would be great if we can directly upload files to an API and update the Jsf page to view those uploaded files as preview.

Would be great to have attribute like type="client/server", uploadUrl="" 

Will that be possible?

**Comment by Rapster** [comment]
The widget seems to have an option for that _(see url option)_: https://github.com/blueimp/jQuery-File-Upload/wiki/Options

If you can investigate how to integrate in PF, would be great

**Comment by melloware** [comment]
That is weird though because that is under AJAX options and AJAX is not allowed to send data except to the host system originating the page for security reasons?  So I wonder how this could possibly work?

**Comment by melloware** [comment]
Ahhh its a partial URL or relative URL.  I don't think it can send to a "different" server as requested above.  I am really not sure this would be possible.

**Comment by Rapster** [comment]
See https://github.com/blueimp/jQuery-File-Upload/wiki/Upload-directly-to-S3

Regarding security reason, that is up to your CSP policy and not AJAX don't you think?

**Comment by melloware** [comment]
Ahhh no it looks like the Form POST is to Amazon but the BlueImp uses JSON call to the local server at `/documents` to post its JSON config.  I have to admit I don't fully understand the BlueImp component but that would make sense if its POST/PUT the file to Amazon but the orchestration of the component is all local AJAX.

**Comment by jepsar** [comment]
I think we should look into the multiple uploads issue first. #7364

**Comment by tandraschko** [comment]
why not just upload the file in your controller to an API?

**Comment by Rapster** [comment]
There can be a real advantage when you deal with big files, you're saving time by not copying the file on the webapp server, in few words: you're making one upload and not two. But if that's not the case, then I wouldn't bother... If copying is slowing down your webapp, the problem might be elsewhere...

**Comment by anuragnz** [comment]
When lot of users concurrently uploading files then web application gets really slow. So directly uploading to another server via API would be ideal.

**Comment by tandraschko** [comment]
@anuragnz would you like to contribute this feature via a PR?

**Comment by melloware** [comment]
Another thing to consider is CORS as you are uploading to a different server than your originating server. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by tandraschko** [comment]
I would close it as wont fix TBH. Can be done in the backend.
PrimeFaces is a component library, build for the current webapp.

**Comment by melloware** [comment]
Agreed and this also can be done with Vanilla JS
