### ISSUE TITLE
SelectOneMenu: not vertically centered

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#7447]
When using `p:selectOneMenu` in for example an `h:panelGroup`, the component is not vertically centered as was the case on PrimeFaces 7 or 8.

See screenshots in attachment.

**Environment:**
 - PF Version: 10.0.2
 - JSF + version: Mojarra 2.3.14.SP04 (WildFly 23.0.2)
 - Affected browsers: all

**Example XHTML**
```html
<h:panelGroup>
                <p:spinner binding="#{cc.days}" size="3"/>
                <h:outputText value=" days and "/>
                <p:selectOneMenu binding="#{cc.hours}">
                    <f:selectItems value="#{cc.hoursSelectItems}"/>
                </p:selectOneMenu>
                <h:outputText value=" hours"/>
            </h:panelGroup>
```

<img width="394" alt="Schermafbeelding 2021-06-19 om 12 10 06" src="https://user-images.githubusercontent.com/771606/122647502-cccdcf80-d124-11eb-93ac-507916c7b15a.png">

<img width="454" alt="Schermafbeelding 2021-06-19 om 12 10 19" src="https://user-images.githubusercontent.com/771606/122647508-d22b1a00-d124-11eb-8041-765c263494e5.png">

**Comment by melloware** [comment]
The problem is the PF themes have SelectOne with `vertical-align: baseline`. 

Reproducer: 
[pf-7447.zip](https://github.com/primefaces/primefaces/files/6682226/pf-7447.zip)

To fix this right now just add this CSS to your application:
```css
body .ui-selectonemenu {
   vertical-align: middle;
}
```

![image](https://user-images.githubusercontent.com/4399574/122673279-aac46380-d19d-11eb-99eb-f31c552792c1.png)

**Comment by fcorneli** [comment]
@melloware The suggested fix indeed works. Thanks.

**Comment by fcorneli** [comment]
Same issue applies for the p:autoComplete component and PrimeFaces version 10.0.6.

**Comment by melloware** [comment]
@fcorneli please open a new issue so we can track it as this one is fixed and closed.
