### ISSUE TITLE
Toolbar content not responsive

### ISSUE THREAD

**Issue by sardineuser** [primefaces/primefaces#745]
Hello, 
regarding the toolbar responsive mode, the content of the widget is not placed responsivly.
Trying to place in a toolbar, some p:calendar in the "f:facet left" header, and p:selectonemenu in the "f:facet right" header, i notice that widgets are not correctly localized in low terminal width mode.

**Comment by cagataycivici** [comment]
This is not related to toolbar, you need to use grid css in combination with ui-fluid. Content definition is up to you, toolbar is a div.

**Comment by sardineuser** [comment]
Thanks,
i uses this : and will try to add css grid on it

            

                
                    

                    
                                 showWeek="true" 
                                 label="Date1" 
                                 pattern="dd/MM/yyyy HH:mm:ss" 
                                 mask="true" 
                                 showOn="button" 
                                 value="#{statBean.date1}"

                                 />
                    

                    
                                showWeek="true" 
                                label="Date2" 
                                pattern="dd/MM/yyyy HH:mm:ss"  
                                mask="true" 
                                showOn="button"
                                value="#{statBean.date2}"
                                />
               
                   
                
                
                    
                    

                        
                    

                
            

# 

Message du 03/10/15 09:01
De : "Çağatay Çivici" 
A : "primefaces/primefaces" 
Copie à : "sardineuser" 
Objet : Re: [primefaces] Toolbar content not responsive (#745)

This is not related to toolbar, you need to use grid css in combination with ui-fluid.
—
Reply to this email directly or view it on GitHub.

---

Mode, hifi, maison,… J'achète malin. Je compare les prix avec Voila.fr http://shopping.voila.fr/
