### ISSUE TITLE
Make String.prototype.replaceAll polyfill ECMA-262 compliant

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#7451]
Current polyfill for String.prototype.replaceAll is not really compliant with [ECMA-262](https://tc39.es/ecma262/#sec-string.prototype.replaceall) and always assumes the string to be replaced is a regular expression.

This causes issues when InputNumbers use a period as the grouping seperator, resetting any kind of input to an empty string. To reproduce, open PrimeFaces showcase in Internet Explorer and edit the Currency field in the InputNumber examples.

**Comment by melloware** [comment]
Why did we add a second file and not just update core.polyfill.js?  To me its just adding more files unecessarily?

**Comment by tandraschko** [comment]
the polyfill isnt as small as others

**Comment by melloware** [comment]
If we go with this: https://github.com/primefaces/primefaces/issues/6956

This change won't be needed at all if we drop IE support.

**Comment by tandraschko** [comment]
yep, IF we drop
we dont have any decision yet by PrimeTek
