### ISSUE TITLE
OverlayPanel: Doesn't disappear when double clicking in input text

### ISSUE THREAD

**Issue by Samuel-StO** [primefaces/primefaces#7455]
**Describe the defect**
When you have an overlayPanel that needs to be displayed on a click event of an input box, sometimes the overlaypannel doesn't go away when we click elsewhere on the page

**Reproducer**
 Reproducer : https://github.com/Samuel-StO/primefaces-overlaypannel-issue

**Environment:**
 - PF Version: 10.0
 - Affected browsers:  ALL

**To Reproduce**
1. Click on input text area 
2. Write some text 
2. Double-click on text 
3. Click somewhere else on the page
4. The overlay panel is still present

**Expected behavior**
The OverlayPanel should disappear when clicking anywhere else on the page.

**Example XHTML**
```html
<h:form id="frmTest">
        <p:inputText id="mailbsubject" styleClass="castLargeStaticField">
            <p:ajax event="click" global="false"
                    onstart="if (PF('emailDynamicParams')) {PF('emailDynamicParams').show();}"/>
        </p:inputText>
        <p:overlayPanel widgetVar="emailDynamicParams" style="top:0;width:500px;">
		        <p:outputLabel value="Lorem Ipsum is simply dummy text."/>
        </p:overlayPanel>
</h:form>
```

**Comment by melloware** [comment]
Thanks for the reproducer. Can you try this MonkeyPatch:

```javascript
if (PrimeFaces.widget.OverlayPanel) {

    PrimeFaces.widget.OverlayPanel.prototype.show = function(target) {
        if (this.isVisible()) {
            return;
        }
        var thisPanel = this;
        this.showTimeout = setTimeout(function() {
            if (!thisPanel.loaded && thisPanel.cfg.dynamic) {
                thisPanel.loadContents(target);
            } else {
                thisPanel._show(target);
            }
        }, this.cfg.showDelay);
    }
}
```

**Comment by Samuel-StO** [comment]
The MonkeyPatch works well, thanks.
