### ISSUE TITLE
DatePicker: lazy load disabled dates when panel is opened

### ISSUE THREAD

**Issue by pmensalt** [primefaces/primefaces#7457]
**Describe the defect**
Lazy loading disabled dates was implemented in ticket #6355.
However, this doesn't work when opening the panel, no viewChangeEvent is fired. When changing months, the viewChangedEvent is fired correctly.

At the moment, when closing the panel, a viewChangeEvent is fired to set the the state of the dates of the current month to prepare the state the next time the panel is shown. However, this is not lazy. it should be initialized when showing the panel, not when hiding.

I think the following things should be changed;
When a LazyDateMetadataModel is used, ...
* a viewChangedEvent should be fired when the panel is opened.
* no viewChangedEvent should be fired when the panel is closed.

**Environment:**
 -  PF Version: 10.0
 -  JSF + version: Mojarra 2.3.9.SP09
 - Affected browsers: ALL (I could reproduce this with Chrome, Firefox and Edge, all updated to latest version. Haven't tested it with other browsers)

**Comment by jepsar** [comment]
I don't understand your issue completely. Are you manipulating the date before opening the panel? The model is fetched for the set date when the component is rendered.

Also, I don't agree with firing events that don't relate to what is actually happening to fix an issue elsewhere. So we should only fire a view change when the view actually changes.

**Comment by pmensalt** [comment]
Let me explain my usecase:

I have many DatePickers on a page. Changing the value of any of them _might_ have an impact on the disabled days of the other ones. 
At the moment, when I change a value of DatePicker 1, then the state of the disabled days isn't updated for DatePicker 2. However, opening, closing and reopening the panel of DatePicker 2 shows the correct disabled days (because a viewChangedEvent is fired when closing the panel which updates the state).

To fix this, I _could_ rerender _all_ my other DatePickers when changing a value of one of them. However, this will do a lot of calculations that are not needed or wanted:
- I might not reopen the others DatePickers
- I could reopen one of them, change the selected date, and _all_ the values of the other DatePickers will be recalculated again (and I didn't even use them when they got recalculated the first time). This can happen many times on the same page.

And to be consistent: When lazy evaluation is used, it makes more sense to _always_ calculate the values at the moment when they are needed, for all cases, not only when changing months. 
At the moment, it isn't completely lazy evaluation, as the initial values for the current moment are calculated when the view is rendered.

**Comment by pmensalt** [comment]
In respond to your 2nd part of your message:
When the panel is opened, this can be seen as a viewChanged event, right? the view _is_ changed, something is added. This event is also fired when the panel is closed. In my opinion, this is the same kind of behaviour: Something is removed from the view, so a viewChanged event is fired. So to be consistent, a viewChangedEvent should also be fired when opening the panel.

**Comment by jepsar** [comment]
I'm not sure if updating the lazy model on opening the panel should be default behavior. If we would add that, I think it should be at least an option.

That a view changed is triggered by closing the popup is a bug in my opinion.

@melloware WDYT

**Comment by melloware** [comment]
I am no quite sure if that is a bug or not but most things in DatePicker are done for a reason.   But its definitely possible its a bug.

**Comment by pmensalt** [comment]
In my opinion (if I understand it correctly how it works), the view is changed when closing the popup for a reason: When reopening the popup, the default month is again visible, so it should contain the state for that month. If it isn't updated when the popup is closed, then it is never updated (because it's also not updated when the popup is shown, because that's what I'm asking here)

**Comment by jepsar** [comment]
I see what you mean when you don't select a date. In that case the picker is reverted to the set date (one might argue if that is a good thing) and a view change event is appropriate. I would just leave the picker at the browsed to month and send no event.

If you do select a date, the view change is also fired, which I think is a bug, or at least inefficient.

I don't know if the behavior of both scenarios is intended. I so, I would like to know if we could swap that behavior to opening the panel. @melloware do you know who can provide us with that info?

**Comment by melloware** [comment]
I guess its an @mertsincan question?

**Comment by melloware** [comment]
@jepsar I am not sure anyone is going to chime in so I think we should make a reasonable assumption here as to the expected behavior.  What do you think?

**Comment by pmensalt** [comment]
I still think this is a bug. Imo, 'lazy loading' means loading the data the moment it is needed, not sooner. This is not the case here. 
Lazily loading the data would mean in this case loading it whenever the popup is shown, or when the month view is changed. 
At the moment, only when changing the month view is lazily loaded, not when the popup is show.

This should be the intended behaviour in my opinion:
- don't initialize when the page is created.
- whenever the popup is displayed, initialize the data for the displayed month
- when month view is changed, fetch new data for the displayed month.
- don't fire an view change event when the popup is closed. 
- On reopening the popup, there could be two options:
-1.  show the month that was displayed before when the popup was closed
-2.  show the default month.  In that case, the data should be reinitialized again. 

I think I would go for the second option, which is closest to the behaviour as it currently is .

**Comment by jepsar** [comment]
I agree with the suggested changes mentioned by @pmensalt. I'm happy to create a PR, but there already is a draft PR https://github.com/primefaces/primefaces/pull/7709 created by @wal-jan. @wal-jan, are you willing to change your PR as described above? I think the `refreshLazyModel` attribute can be dropped.

**Comment by melloware** [comment]
@jepsar if you have time submit a PR.

**Comment by wal-jan** [comment]
@melloware, @jepsar sorry for the late answer. In the moment I'm very busy and do not have the time to change the PR. Feel free to use or discard my draft PR .

**Comment by pmensalt** [comment]
It took me a while to validate it, but I found the time to do it now, and it seems to be working fine. Thanks!
