### ISSUE TITLE
InputNumber: focus on mouseover over empty fields, if symbol is used

### ISSUE THREAD

**Issue by zhedar** [primefaces/primefaces#7460]
**Describe the defect**
If symbols are used, `p:inputNumber` focuses on mouseover.

![inputnumber-mouseover2](https://user-images.githubusercontent.com/6633403/123258564-cdcf7a00-d4f3-11eb-8923-f7f90da1b880.gif)

**Environment:**
 - PF Version: _10.0_
 - Affected browsers: _ALL_

**To Reproduce**
1.  hover of field
2. put cat on keyboard (alternatively: start typing)
3. hover of next fields
4. eventually hover over non-empty fields

**Expected behavior**
No focus on mouseover.

**Example XHTML**
```<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
</h:head>
<h:body>
	<p:inputNumber symbol=" Unit" symbolPosition="s" />
	<p:inputNumber symbol=" Unit" symbolPosition="s" />
	<p:inputNumber symbol=" Unit" symbolPosition="s" />
	<p:inputNumber symbol=" Unit" symbolPosition="s" />
	<p:inputNumber symbol=" Unit" symbolPosition="s" />
</h:body>
</html>
```

**Comment by zhedar** [comment]
Just **after**  opening this issue, I discovered the seemly new `emptyValue` property, which defaults to `focus`. The behaviour from PF 8 is restored, when `emptyValue="empty"` is used. So I guess, this isn't a defect, but rather intentional. 
It got me puzzled though. It seems, this behaviour doesn't appear, if no symbol is used.

**Comment by melloware** [comment]
Yep its as designed in the InputNumber component. See this ticket: https://github.com/primefaces/primefaces/issues/6441

**Comment by melloware** [comment]
Definitely looks like an Autonumeric bug.
