### ISSUE TITLE
DataTable: Reflow Sortable Columns Incorrect

### ISSUE THREAD

**Issue by susantaylorcollier** [primefaces/primefaces#7471]
**Describe the defect**
I reported this defect in the primefaces forum and the developer indicated it was a defect and should be reported here:

I have a page where I use the 'sort by' attribute in the datatable. However, on mobile display, once the reflow option kicks in and the sort button appears instead of the arrows on the columns, the column titles that display in the dropdown list do not map correctly.

For example, the data table displays the following columns in this order on the page: RR, RN, Date, Station, Shop, Code.... (and so on). On the drop down however, you will see the columns listed out of order, like RR, Shop, Code, RN, Date, Station....(and so on) which as you can see does NOT match the order of the columns on the datatable. However, If you select, for example, the third item in the list (i.e. Code Ascending or Code Descending using our above example) it will sort the third column in the datatable which is 'Date' not Code as listed. So it is as if, the titles in the list are randomly ordered in name, but map to the correct column number. 

**Reproducer**
You can reproduce this error on your Primefaces Showcase 'CRUD' datatable.  Simply, minimize table until reflow kicks in.  Then try to use the sort button.  You will see the behavior detailed above.

**Environment:**
 - PF Version: _10.0_
 - Affected browsers:  Chrome

**To Reproduce**
1. Go to Primefaces Showcase
2. Go to Datatable - CRUD https://www.primefaces.org/showcase/ui/data/datatable/crud.xhtml
3. Minimize screen until reflow kicks in and you see the Sort option
4. Select different sort fields
5. See error

**Expected behavior**
I expect that the column I select in the sort option is the one that the datatable gets sorted by

**Comment by melloware** [comment]
This looks like a sorting issue where the JS thinks the headers are on one order and the server thinks they are in another order I think.

**Comment by markpalermo** [comment]
Changing the column order after initial rendering seems to break the ordering expected by filters/sorters.
On the Primefaces Showcase:
https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml

Change the columns to be "code  quantity category name" and click "Update".
Sorting and filtering will now be against the wrong column for most of them.

**Comment by tandraschko** [comment]
@markpalermo your issue is #8159, we fixed the showcase for that problem
