### ISSUE TITLE
Dashboard: for dynamic components with Grid layout

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#7472]
Hi there,

The dashboard component looks good.
We need to define the columns and then we can add components to each columns like this:

```java
                model = new DefaultDashboardModel();
		DashboardColumn column1 = new DefaultDashboardColumn();
		DashboardColumn column2 = new DefaultDashboardColumn();
		DashboardColumn column3 = new DefaultDashboardColumn();

		column1.addWidget("sports");
		column1.addWidget("finance");

		column2.addWidget("lifestyle");
		column2.addWidget("weather");

		column3.addWidget("politics");

		model.addColumn(column1);
		model.addColumn(column2);
		model.addColumn(column3);
```

For dynamic dashboard components defining columns is not suitable. Rather if we can just define number of columns then it would become a grid layout type. Which would be really great. 

So the option would be
```xml
<p:dashboard columns="3" model="#{}"  />
```

**Comment by melloware** [comment]
I moved your comment to here as it is a duplicate: https://github.com/primefaces/primefaces/issues/36
