### ISSUE TITLE
AutoComplete: preserve order of underlying List with unique=true option

### ISSUE THREAD

**Issue by AndrewG10i** [primefaces/primefaces#7486]
Faced with an issue that AutoComplete component doesn't keep the order of the original List to which it is bind to (when it has an option `unique="true"` set). In some scenarios (like in ours) preserving an original order is crucial.

From the component code we see that it uses `HashSet` for filtering out duplicated values, also seems the implementation is similar for both PF 8 and 10 versions.

Source code for ref:
https://github.com/primefaces/primefaces/blob/8.0/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java#L412

You can see the following line:
`Collection<Object> items = ac.isUnique() ? new HashSet<>(values) : values;`

It is proposed to replace with the following implementation:
`Collection<Object> items = ac.isUnique() ? new LinkedHashSet<>(values) : values;`

So using LinkedHashSet instead of just a HashSet will help to preserve original order of values.

So for now we just removed `unique="true"` property in order to resolve this, but in future it would be nice to see that implemented.

Thank you for consideration!

**Comment by melloware** [comment]
Thanks for the suggestion!  I have submitted the fix and updated the Integration Test which actually already was proving your bug and I didn't realize it :)

**Comment by AndrewG10i** [comment]
@melloware, great, thanks for addressing this so quickly! )

**Comment by AndrewG10i** [comment]
Just curious any chance to see this in let say 8.0.12? ...it might take some time until we upgrade to 10/11.x. Thank you! ;)
