### ISSUE TITLE
SelectOneMenu: Hover effect on select items is not continuous with long item names

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#7489]
**Describe the defect**
If selectOneMenu has a select item whose name is longer than the options box, a scroll bar appears so that the full name can be read by scrolling. When hovering over a select item, the background and text color of the respective item changes (e.g. to blue blackground and white text) but for select items with overlong names, the hover effect does not color the whole background of the select item.

![selectOneMenu_UI](https://user-images.githubusercontent.com/77431692/123803495-a2ca9900-d8ec-11eb-9031-074a4f43d559.png)

**Environment:**
 - PF Version: _10.0_

**To Reproduce**
The error also appears in PrimeFaces Showcase for SelectOneMenu.
1. Go to http://www.primefaces.org:8080/showcase/ui/input/oneMenu.xhtml?jfwid=ed6c3
2. Activate the browser's developer tools and select the first selectOneMenu.
3. Change the html code of one of the menu's select items so that its name is longer than the box (a horizontal scroll bar should appear).
4. Scroll right and hover over the select item you just changed.
5. See error. The hover effect only covers a part of the select item's name.

**Expected behavior**
By hovering over a select item of selectOneMenu the background of the item should be colored completely (e.g. blue).

**Example XHTML**
Note: Check that the width of the options box is smaller than the select item's name.
```html
<h:form id="frmTest">
  <p:selectOneMenu id="option" style="width: 150px">
        <f:selectItem itemLabel="Select One" itemValue=""/>
        <f:selectItem itemLabel="Short Entry" itemValue="Short Entry"/>
        <f:selectItem itemLabel="Very loooooooooooooooooooooooooooooooooong Entry"
                              itemValue="Very loooooooooooooooooooooooooooooooooong Entry"/>
  </p:selectOneMenu>
</h:form>
```

**Comment by melloware** [comment]
Which theme are you using just to make sure we have all the info?

**Comment by miedrl** [comment]
I'm using the Rain Theme.

**Comment by melloware** [comment]
Works fine for me with Saga see this reproducer:
[pf-7489.zip](https://github.com/primefaces/primefaces/files/6740770/pf-7489.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

![image](https://user-images.githubusercontent.com/4399574/123959212-e7514580-d97b-11eb-9896-dca67727fda8.png)


Are you sure you are using the latest version of Rain theme for PrimeFaces 10?

**Comment by miedrl** [comment]
The problem only appears when the box for the select items is smaller than the name of the item it contains (a horizontal scroll bar must appear). In your example, the box's width was automatically adjusted to the item's name's length so there is no scroll bar.

The problem also appears in the Rain demo (https://www.primefaces.org/rain/input.xhtml), when you change the select item's name so that it exceeds the box (I did this via the browser's developer tools to change the html):

![grafik](https://user-images.githubusercontent.com/77431692/123960473-9eb37f80-d9af-11eb-97d2-3fde2eef0b94.png)

**Comment by melloware** [comment]
Can you update my attached reproducer above so I can see the problem.  I can't fix it if I can't reproduce it.

**Comment by miedrl** [comment]
Please try this reproducer. I've added javascript to adapt the box's width [pf-7489.zip](https://github.com/primefaces/primefaces/files/6741205/pf-7489.zip)

**Comment by melloware** [comment]
I see it now.  But just as a note you didn't need JS to do this just use the `panelStyle` attribute...

```xml
<p:selectOneMenu id="option" style="width: 150px" panelStyle="width: 200px" >
```

**Comment by melloware** [comment]
OK I found a workaround.  Not sure what your RAIN color theme is but if you add this CSS to your application it will fix it. Its missing `overflow: auto`

```css
body .ui-selectonemenu-panel .ui-selectonemenu-items .ui-selectonemenu-item.ui-state-highlight {
    background: #E3F2FD;
    color: #495057;
    overflow: auto;
}
```

But it only highlights up until its container elements width of 200px.

**Comment by melloware** [comment]
Assigning to PrimeTek to fix in the themes.

**Comment by miedrl** [comment]
melloware: "But it only highlights up until its container elements width of 200px."

But I think the problem is still not fixed because the complete select item should be colored, not only until the width of 200px. Is there a way to color the whole item, no matter the size of its container element's width?

**Comment by melloware** [comment]
It is fixed if you use my CSS above.  Here is my screenshot:

![image](https://user-images.githubusercontent.com/4399574/123990417-bda61780-d997-11eb-8801-2803d0ada06e.png)

**Comment by miedrl** [comment]
It works with Rain now, thank you.
