### ISSUE TITLE
SubTable: Column ignores rendered attribute

### ISSUE THREAD

**Issue by skybber** [primefaces/primefaces#7497]
**Describe the defect**
Column in SubTable is rendered even if rendered="false". `SubTableRenderer.encodeRow(...)`shoud check column.isRendered()

**Reproducer**
Simply add rendered="false" to column in subTable

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: ALL_

**To Reproduce**
1. Add rendered="false" to column in subTable
2. See error

**Expected behavior**
Column should be hidden.

**Comment by melloware** [comment]
Thanks for the report I submitted a PR to fix it.
