### ISSUE TITLE
CheckboxMenu should show selected items in label

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#75]
Feature request / improvement. We already discussed this in the blog post http://blog.primefaces.org/?p=2040. At the moment, new CheckboxMenu component doesn't show selected items when page is displayed. Users have to open the combobox to see selected items. The component should show selected items like in multiply AutoComplete. By the way, some other users think the same http://blog.primefaces.org/?p=1662 (old blog post).

When this feature is done, we will remove this stupid request https://code.google.com/p/primefaces-extensions/issues/detail?id=183 :-)

Looking forward to powerful CheckboxMenu. Many thanks.

Oleg Varaksin

**Comment by karlkilden** [comment]
Would love a milestone for this one...

**Comment by melloware** [comment]
@cagataycivici Can this be closed as this now works with the multiple="true" option in CheckboxMenu?

**Comment by melloware** [comment]
@tandraschko this can be closed as this feature is already implemented with multiple="true".

**Comment by tandraschko** [comment]
with target RC3?

**Comment by melloware** [comment]
I am using 6.0.17 and this feature works right now.
