### ISSUE TITLE
p:confirm and p:confirmDialog doen't work with p:commandButton with attribute  ajax="false"

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#750]
I used following libraries:
primefaces-5.2.jar
jsf-api-2.2.10.jar
jsf-impl-2.2.10.jar
JDK 1.8

p:confirm and p:confirmDialog doen't work with p:commandButton with attribute ajax="false"
<code><pre>
<p:commandButton immediate="true" ajax="false" update="growl" action="#{bean.delete}" value="Delete" icon="ui-icon-delete">
    <p:confirm message="Are you sure?" icon="ui-icon-alert" />
</p:commandButton>
<p:confirmDialog global="true" >
    <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
    <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>
</p:confirmDialog>
</pre></code>

the action delete in ManageBean doesn't call

**Comment by kukel** [comment]
remove global="true"... or use it differently. See the PF docs...

**Comment by Rapster** [comment]
Duplicate of #99?

**Comment by tandraschko** [comment]
Yep probably.
