### ISSUE TITLE
SubTable: Column does not use `colspan/rowspan

### ISSUE THREAD

**Issue by skybber** [primefaces/primefaces#7504]
Describe the defect
SubTableRenderer.encodeRow(...) shoud write attribute colspan to `td` using value from `column.getColspan()`

Reproducer
Simply use colspan="2" in subtable

Environment:

    PF Version: 10.0
    JSF + version: e.g. Mojarra 2.2.20 or MyFaces 2.3.9
    Affected browsers: ALL_

To Reproduce

    Add colspan="2" to column in subTable
    See error

Expected behavior
Column should span over 2 columns.

**Comment by melloware** [comment]
Added `rowSpan` and `colSpan` since that is what main table columns supports.
