### ISSUE TITLE
Timeline: component needs scrollable attribute

### ISSUE THREAD

**Issue by ufuk23** [primefaces/primefaces#7506]
We need a scrollable attribute for the timeline component. The header of the timeline must be constant at the top of the timeline.

We try to use the timeline wrapped in the scrollpanel, but the header of the timeline is not shown steady at the top when the rows are so much like below. Sharing some pictures to tell more about that.

**So we need a scrollable property that will be used inside of the timeline component.** 

![image](https://user-images.githubusercontent.com/8513827/124144498-b6186880-da94-11eb-9966-5630d6b87e62.png)

![image](https://user-images.githubusercontent.com/8513827/124145366-67b79980-da95-11eb-9f59-a2f649d78637.png)

**Comment by melloware** [comment]
You might want to check what is possible in the vis-timeline component itself since PF is just wrapping that underlying component.

https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options

**Comment by melloware** [comment]
You can do this now...

![image](https://user-images.githubusercontent.com/4399574/124179990-8ca21180-da81-11eb-891f-547d05b41bf5.png)

I add this facet which adds the scroll right and scroll left buttons on the Timeline shown in the picture.

```xml
<f:facet name="menu">
   <p:commandButton type="button" icon="fa fa-chevron-left" onclick="PF('organizerTimelineWidget').move(-0.3);"
					title="Scroll Left" pt:aria-label="Scroll Left" />
   <p:commandButton type="button" icon="fa fa-chevron-right" onclick="PF('organizerTimelineWidget').move(0.3);"
					title="Scroll Right" pt:aria-label="Scroll Right" />
</f:facet>
``

**Comment by ufuk23** [comment]
That is not the same I told. We need vertical scroll that allows the header steady

**Comment by melloware** [comment]
See `verticalScroll` here: https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options

> Show a vertical scroll on the side of the group list and link it to the scroll event when zoom is not triggered. Notice that defining this option as true will NOT override horizontalScroll. The scroll event will be vertically ignored, but a vertical scrollbar will be visible

And we already have this property available on the timeline: https://primefaces.github.io/primefaces/10_0_0/#/components/timeline?id=timeline

Just set `verticalScroll="true"`
