### ISSUE TITLE
TabView: Vertical - css remove fixed width

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#752]
**Left navigation menu**
The vertical tab navigation menu occupies harcoded 23% of space which is very large. 

**Enhancement**

Use auto sizing using table-layout and 100% list content element like:

```
<div class="ui-helper-clearfix">
    <ul style="display: table; table-layout: fixed; float: left;">
        <li style="display: table-row;"><p:button value="Test" style="width: 100%;"/></li>
        <li style="display: table-row;"><p:button value="Test12345" style="width: 100%;"/></li>
        <li style="display: table-row;"><p:button value="Test123456789" style="width: 100%;"/></li>
    </ul>
    <div style="overflow: hidden;">
        lorem ipsum ....    
    </div>
</div>
```

**Right content panel**

To allow dynamic size replace:

```
float: right;
width: 75%;
```

with:

```
overflow: hidden;
```

See: http://www.stubbornella.org/content/2009/07/23/overflow-a-secret-benefit/

http://forum.primefaces.org/posting.php?mode=edit&f=3&p=125281

**Comment by tandraschko** [comment]
A PR is very welcome here.
