### ISSUE TITLE
TreeTable: provide integrationtests

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7523]
Please assign this one to me, i´ll try to work on this.

**Comment by melloware** [comment]
CC @FlipWarthog as I was working with him on doing Tree tests.

**Comment by FlipWarthog** [comment]
Yep, @melloware gave me the rundown on adding new integration tests so I've started on Tree in reference to #3887. I'm sure TreeTable will be completed first, so I'll watch this issue and pull in the changes when they're complete.

**Comment by melloware** [comment]
Got one of these today: "TreeTable001Test.testGlobalFilter:223 » StaleElementReference stale element re.."

**Comment by christophs78** [comment]
Already looked at this, but currently no idea whats wrong.
https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/treetable/TreeTable001Test.java#L223

**Comment by christophs78** [comment]
TreeTable001Test.testGlobalFilter:217 » StaleElementReference stale element re...
TreeTable001Test.testGlobalFilter:224 » StaleElementReference stale element re...

**Comment by christophs78** [comment]
Maybe we should add some wait after 213.
Or better modify https://github.com/primefaces/primefaces/blob/925ff332c4d44270d29aaff1e019be713dbd47ba/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/AbstractTableTest.java#L57.

**Comment by christophs78** [comment]
Ok. For DataTable-integration-tests we set `filterEvent="enter"`.
TreeTable does not have this attribute, so filter ist (propably) fired after each keyup. So we need different implementations of filterGlobal for DataTable und TreeTable.
