### ISSUE TITLE
PanelMenu with global state

### ISSUE THREAD

**Issue by schaeferm** [primefaces/primefaces#7531]
**Describe the defect**
With #6054 the state saving was changed from Cookies to LocalStorage. As discussed in https://github.com/primefaces/primefaces/issues/6054#issuecomment-874127828 ff. the new implementation behaves different in that the state is now saved on a per page basis vs. previously globally.

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _MyFaces 2.3.9_
 - Affected browsers: ALL

**To Reproduce**
1. Create app with at least 2 pages and a shared main menu
2. The main menu should have multiple subsections
3. Open some of them on the first page
4. Navigate to 2nd page
5. The subsections are closed again.

**Expected behavior**
There should be an attribute that allows to configure global state saving for at least PanelMenus, possibly other components as well. This should allow to display the menu in the same state on both pages.

**Comment by melloware** [comment]
I guess the question for everyone is should we introduce a new attribute to determine this?  Does it make sense for all components or should we just restore the PanelMenu behavior back to being a "global" since that is how it was before.

**Comment by melloware** [comment]
@schaeferm if you need a MonkeyPatch right now you can add the following to your app.

```javascript
if (PrimeFaces.widget.PanelMenu) {

    PrimeFaces.widget.PanelMenu.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        this.headers = this.jq.find('> .ui-panelmenu-panel > h3.ui-panelmenu-header:not(.ui-state-disabled)');
        this.menuContent = this.jq.find('> .ui-panelmenu-panel > .ui-panelmenu-content');
        this.menuitemLinks = this.menuContent.find('.ui-menuitem-link:not(.ui-state-disabled)');
        this.menuText = this.menuitemLinks.find('.ui-menuitem-text');
        this.treeLinks = this.menuContent.find('.ui-menu-parent > .ui-menuitem-link:not(.ui-state-disabled)');

        //keyboard support
        this.focusedItem = null;
        this.menuText.attr('tabindex', -1);

        //ScreenReader support
        this.menuText.attr('role', 'menuitem');
        this.treeLinks.find('> .ui-menuitem-text').attr('aria-expanded', false);

        this.bindEvents();

        if (this.cfg.stateful) {
            this.stateKey = 'PanelMenu' + this.id;
        }

        this.restoreState();
    }
}
```
