### ISSUE TITLE
TreeTable: multisort is broken

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7537]
**Describe the defect**
Multisort does not respect sort sortPriority. Example 3 "Document Viewer (multi sort, predefined sort in markup)"

**Reproducer**
http://primefaces.org/showcase/ui/data/treetable/sort.xhtml

**Environment:**
 - PF Version: 10.0, 11.0-SNAPSHOT

**To Reproduce**
Look at example 3.

**Notes**
https://github.com/primefaces/primefaces/blob/1f60dda906c252c33865fe38b7614662b8ef1308/primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java#L1187 sort´s one column after another. So the last column wins.
Probably should be more like https://github.com/primefaces/primefaces/blob/2e79cbc628fa98885cad4688813fc7e82f6f3a97/primefaces/src/main/java/org/primefaces/component/datatable/feature/SortFeature.java#L166 and iterate over sortBy/SortMeta.

also see https://github.com/primefaces/primefaces/pull/7525

**Comment by christophs78** [comment]
please active https://github.com/primefaces/primefaces/blob/b56889f50fa7609ac63530268c166f713d6930e3/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/treetable/TreeTable002Test.java#L61 after this one is fixed

**Comment by tandraschko** [comment]
@christophs78 do you plan to work on this?
too complicated for my spare time currenctly :D

**Comment by christophs78** [comment]
No short term-plans to work on this. Maybe later.
