### ISSUE TITLE
DataTable/TreeTable: draggable columns can not be filtered with touch.

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#7562]
**Describe the defect**
Draggable columns of data table can not be filtered with touch.

**Reproducer**
https://github.com/irieill/primefaces-test

I think the problem is that `touchstart` event on the default filter `input` is bubbling to the columns table header which has handlers defined when `draggable` that prevent focusing.

As workaround i added a custom event handler to the filter input that calls `stopPropagation()`.

**Comment by melloware** [comment]
Care to submit a PR or provide what you did here as a MonkeyPatch?

**Comment by irieill** [comment]
I hook into/extend [`bindTextFilter`](https://github.com/primefaces/primefaces/blob/bc22e09bb3b45137a833f0bd1c07cdd5cc4de65c/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L679) to add my custom event handler on the filter input.

```JavaScript
//
// workaround for https://github.com/primefaces/primefaces/issues/7562
// TODO: remove when fixed
//
(function() {
  var DataTable = PrimeFaces.widget.DataTable.prototype;
  DataTable.setupTextFilterEventPropagation = function(filter) {
    filter.on('touchstart', e => {
      e.stopPropagation();
    });
  };
  var bindTextFilterOriginal = DataTable.bindTextFilter;
  function bindTextFilterExtension(filter) {
    bindTextFilterOriginal.call(this, filter);
    this.setupTextFilterEventPropagation(filter);
  }
  DataTable.bindTextFilter = bindTextFilterExtension;
})()
```

**Comment by melloware** [comment]
Can you try this monkeypatch instead of your code above?  It should do the same thing.

```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.bindTextFilter = function(filter) {
        if (this.cfg.filterEvent === 'enter')
            this.bindEnterKeyFilter(filter);
        else
            this.bindFilterEvent(filter);

        // #7562 draggable columns cannot be filtered with touch
        if (PrimeFaces.env.isTouchable(this.cfg)) {
            filter.on('touchstart', function(e) {
                e.stopPropagation();
            });
        }
    }
}
```

**Comment by irieill** [comment]
Of course, that works too. Thank you!
