### ISSUE TITLE
Datepicker: numberOfMonths > 12 shows wrong month names + year

### ISSUE THREAD

**Issue by iki-hacon** [primefaces/primefaces#7563]
**Describe the defect**
An (inline) p:datePicker with numberOfMonths  > 12 shows wrong month names and wrong years after the second october

**Environment:**
 - PF Version: _10.0_
 - JSF + version: does not matter

**Expected behavior**
Correct months names and years

**Example XHTML**
```html
<h:form id="frmTest">
<p:datePicker id="calendars" numberOfMonths="15" inline="true"></p:datePicker>
</h:form>
```
See last 3 months (should be Nov 2021, Dec 2021 and Jan 2022)
![datepickerFehler](https://user-images.githubusercontent.com/39994847/125082388-74f10b80-e0c7-11eb-87a1-e95da16d5f71.png)

The error is in 
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Line 342ff
the calculation does modulo 11 (and we have 12 months!?!). This only works (by chance) for the first year.

Fix: 
Calculate with modulo 12 and also calculate the correct year
```
createMonths: function (month, year) {
        var months = [];
        for (var i = 0; i < this.options.numberOfMonths; i++) {
            var m = month + i,
                y = year;
            if (m > 11) {
                y = year + Math.floor(m / 12);
                m = m % 12;
            }
            months.push(this.createMonth(m, y, i));
        }
        return months;
    },
```

**Comment by melloware** [comment]
Is it using `11` because months are 0-11 or are they 1-12?

cc @wal-jan @jepsar

**Comment by iki-hacon** [comment]
Yes, they are numbered from 0 to 11, but they are 12 elements. Modulo 12 also gives numbers from 0 to 11. In our test, this fix gives the correct result.
