### ISSUE TITLE
Internet Explorer 8 Ajax update broken in PF5.3RC1

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#757]
Hi, for some reason ajax calls no longer work on IE8.

I'm running on Wildfly 9.0.1, Mojarra 2.2, PF 5.3 RC1. This issue basically kills IE8 support completely. Don't know if 5.3 still supports IE8. If not please enlighten me. 

In Chrome, Firefox and newer IE, it works

Now the simple code to reproduce the issue:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pm="http://primefaces.org/mobile"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:head>
        <title>TestPage</title>
    </h:head>

    <h:body>
         <h:form>
            <h:outputText id="testInput" value="#{testBean.UUID}"></h:outputText><br></br>
            <p:commandButton update="testInput" value="Update!" onerror="alert(error);"></p:commandButton>

                  <h:commandButton value="Update(PlainJSF)!">
                 <f:ajax execute="testInput" render="@form" />
             </h:commandButton>

        </h:form>
    </h:body>

</html>

```

Bean:

```
package de.test.primefaces;

import java.io.Serializable;
import java.util.UUID;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name="testBean")
@SessionScoped
public class TestBean implements Serializable {

    private static final long serialVersionUID = 1L;

    public String getUUID(){

        String uuid = UUID.randomUUID().toString();
        return uuid;

    }

}
```

![ie8issue](http://abload.de/img/primefaces3knyr1.png)

**Comment by tandraschko** [comment]
Does ist also occur if you use e.g. IE10 in IE8 compatibility mode for you?

**Comment by cnsgithub** [comment]
Hi, nope. Only real IE8. I've found out some additional info. It seems jQuery uses an ActiveX Object to parse the XML and by default (or GPO) it is set to disable. So basically there is a workaround to set it to 'enabled'. But it's not a nice one. However the error is more jQuery related it seems. It would be better to avoid using ActiveX 

![ie8issue](http://abload.de/img/ie8setting6clcy.png)

**Comment by tandraschko** [comment]
Hmm, weird.
My applications are still working fine after upgrading to 5.3.
Also the xml from your screenshot is looking good and not sure if there is a solution without ActiveX. Also it's really related to jQuery.

@cagataycivici Did we upgrade jQuery to a newer version?

**Comment by cnsgithub** [comment]
Just for info, the same happens in 5.2.13, so i cant actually say if it hasn't been always like that. Probably, the posted ActiveX Setting was never set to Disable before. Ill ask here http://bugs.jquery.com/ when the site comes up again ;-)

**Comment by tandraschko** [comment]
Oh, good to know!
Could you please identify the elite release when it occured the first time?

**Comment by cagataycivici** [comment]
We've tested with 5.2.13 and 5.3.RC1 and cannot replicate on plain IE8. jQuery version in 5.2.13 is 1.11 and 1.11.3 on 5.3.RC1.
