### ISSUE TITLE
Badge: Icon is duplicated if update badge only

### ISSUE THREAD

**Issue by artragis** [primefaces/primefaces#7572]
**Describe the defect**
If another component (poll, commandButton) update a badge by its id the badge content is duplicated.

**Reproducer**

Clone & launch the branch https://github.com/artragis/primefaces-test/tree/badge_duplication 
Wait for some seconds and observe : 
![badge_dupli](https://user-images.githubusercontent.com/1523653/125252066-3f7f3480-e2f8-11eb-9a39-74e49d1ea3b8.gif)
Nota: if you update the container (here notifTree) instead of the badge itself, the bug does not appear

**Environment:**
 - PF Version: _10.0_
 - JSF + version: jsf 2.3

**To Reproduce**
1. add a badge component with id "badge" and an icon as inner content
2. add a poll that will update the badge content, and add `update="badge"` attribuyte
3. wait for the poll to refresh

**Expected behavior**

The badge number updates, the content icons remains the same

**Example XHTML**

see reproducer

**Comment by tandraschko** [comment]
can you try to update the commandlink? Maybe a weird case when badge is inside a commandlink

**Comment by artragis** [comment]
Like I said in the issue, updating the command link or the container just works. The issue is quite strange and unexpected. Perhaps it just worth documentation.
