### ISSUE TITLE
Italian server localization

### ISSUE THREAD

**Issue by AlessandroBori** [primefaces/primefaces#7573]
Localization of primefaces.data.EMPTY_MESSAGE is missing
 should be _primefaces.data.EMPTY_MESSAGE= Nessun record trovato._ or similar

**Comment by jepsar** [comment]
It's missing in all the `Messages_xx.properties` files, so missing for each language.

**Comment by melloware** [comment]
@jepsar I am only seeing it missing for Italian?

**Comment by AlessandroBori** [comment]
In 10.0.2 release (and further releases 10.0.3 & 10.0.4) is present in some languages (German, french etc...) but not in italian

**Comment by jepsar** [comment]
Oh, that's weird, I did a search for the key.. probably in the wrong context.. I'm getting results now. Sorry for the fuzz.

**Comment by melloware** [comment]
Acutally @AlessandroBori  the Italian is missing quite a few keys.  Do you mind translating all of these and I will fix it?

```
primefaces.autocomplete.aria.DROPDOWN_LABEL=Show Options
primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Validation Error: Start date is greater than the end date.
primefaces.calendar.INVALID = {0}: Validation Error: Value is not valid.
primefaces.calendar.MAX_DATE = {0}: Validation Error: Value must be {2} or before.
primefaces.calendar.MIN_DATE = {0}: Validation Error: Value must be {1} or later.
primefaces.calendar.OUT_OF_RANGE = {0}: Validation Error: Value must be between {1} and {2}.
primefaces.captcha.INVALID = {0}: Validation Error: Value is not valid.
primefaces.captcha.INVALID_detail = {0}: ''{1}'' does not match the displayed text.
primefaces.data.EMPTY_MESSAGE = No records found.
primefaces.datatable.aria.FILTER_BY = Filter by {0}
primefaces.datatable.aria.HEADER_CHECKBOX_ALL = Select All
primefaces.datatable.SORT_ASC = Ascending
primefaces.datatable.SORT_DESC = Descending
primefaces.datatable.SORT_LABEL = Sort
primefaces.dialog.aria.CLOSE = Close
primefaces.fileupload.CLAM_AV_FILE = ClamAV has identified file '{0}' as potentially dangerous with message '{1}'
primefaces.fileupload.VIRUS_TOTAL_FILE = Virus Total has identified file '{0}' potentially dangerous
primefaces.input.aria.filter = Filter
primefaces.messages.aria.CLOSE = Close
primefaces.messages.aria.ERROR = Error
primefaces.messages.aria.FATAL = Fatal
primefaces.messages.aria.INFO = Information
primefaces.messages.aria.WARN = Warning
primefaces.paginator.aria.FIRST_PAGE = First Page
primefaces.paginator.aria.HEADER = Pagination
primefaces.paginator.aria.LAST_PAGE = Last Page
primefaces.paginator.aria.NEXT_PAGE = Next Page
primefaces.paginator.aria.PREVIOUS_PAGE = Previous Page
primefaces.paginator.aria.ROWS_PER_PAGE = Rows Per Page
primefaces.panel.aria.OPTIONS_MENU = Toggle Options Menu
primefaces.panel.aria.TOGGLE = Toggle Panel
primefaces.password.INVALID_MATCH = {0}: Validation Error.
primefaces.password.INVALID_MATCH_detail = {0} should match with {1}.
primefaces.picklist.ADD = Add
primefaces.picklist.ADD_ALL = Add all
primefaces.picklist.REMOVE = Remove
primefaces.picklist.REMOVE_ALL = Remove all
primefaces.picklist.MOVE_UP = Move up
primefaces.picklist.MOVE_TOP = Move top
primefaces.picklist.MOVE_DOWN = Move down
primefaces.picklist.MOVE_BOTTOM = Move bottom
primefaces.rowgrouptoggler.aria.ROW_GROUP_TOGGLER = Toggle Row Group
primefaces.rowtoggler.aria.ROW_TOGGLER = Toggle Row
primefaces.slider.OUT_OF_RANGE = {0}: Validation Error: Value is out of range.
primefaces.switch.LABEL_ON = On
primefaces.switch.LABEL_OFF = Off
primefaces.tree.REQUIRED = {0}: Validation Error.
primefaces.tree.REQUIRED_detail = Selection is required.
```

**Comment by melloware** [comment]
ping @AlessandroBori ???

**Comment by AlessandroBori** [comment]
@melloware i'm on it

**Comment by AlessandroBori** [comment]
done 

`primefaces.autocomplete.aria.DROPDOWN_LABEL=Mostra elementi
primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Errore di validazione: La data d''inizio è successiva alla data di fine.
primefaces.calendar.INVALID = {0}: Errore di validazione: Valore non valido.
primefaces.calendar.MIN_DATE = {0}: Errore di validazione: Il valore dev''essere {1} o successivo.
primefaces.calendar.MAX_DATE = {0}: Errore di validazione: Il valore dev''essere {2} o precedente.
primefaces.calendar.OUT_OF_RANGE = {0}: Errore di validazione: Il valore dev''essere compreso tra {1} e {2}.
primefaces.captcha.INVALID = {0}: Errore di validazione: Valore non valido.
primefaces.captcha.INVALID_detail = {0}: ''{1}'' non corrisponde al testo visualizzato.
primefaces.data.EMPTY_MESSAGE = Nessun risultato trovato.
primefaces.datatable.aria.FILTER_BY = Filtro per {0}
primefaces.datatable.aria.HEADER_CHECKBOX_ALL = Seleziona tutti
primefaces.datatable.SORT_ASC = Crescente
primefaces.datatable.SORT_DESC = Decrescente
primefaces.datatable.SORT_LABEL = Ordina
primefaces.dialog.aria.CLOSE = Chiudi
primefaces.fileupload.CLAM_AV_FILE = ClamAV ha identificato il file '{0}' come potenzialmente dannoso con messaggio '{1}'
primefaces.fileupload.VIRUS_TOTAL_FILE = Virus Total ha identificato il file '{0}' come potenzialmente dannoso
primefaces.input.aria.filter = Filtro
primefaces.messages.aria.CLOSE = Chiudi
primefaces.messages.aria.ERROR = Errore
primefaces.messages.aria.FATAL = Fatale
primefaces.messages.aria.INFO = Informazione
primefaces.messages.aria.WARN = Attenzione
primefaces.paginator.aria.FIRST_PAGE = Prima pagina
primefaces.paginator.aria.HEADER = Paginazione
primefaces.paginator.aria.LAST_PAGE = Ultima pagina
primefaces.paginator.aria.NEXT_PAGE = Pagina successiva
primefaces.paginator.aria.PREVIOUS_PAGE = Pagina precedente
primefaces.paginator.aria.ROWS_PER_PAGE = Righe per pagina
primefaces.panel.aria.OPTIONS_MENU = Menu di selezione opzioni
primefaces.panel.aria.TOGGLE = Pannello di selezione
primefaces.password.INVALID_MATCH = {0}: Errore di validazione.
primefaces.password.INVALID_MATCH_detail = {0} dovrebbe corrispondere a {1}.
primefaces.picklist.ADD = Aggiungi
primefaces.picklist.ADD_ALL = Aggiungi tutti
primefaces.picklist.REMOVE = Rimuovi
primefaces.picklist.REMOVE_ALL = Rimuovi tutti
primefaces.picklist.MOVE_UP = Sposta in alto
primefaces.picklist.MOVE_TOP = Sposta in cima
primefaces.picklist.MOVE_DOWN = Sposta in basso
primefaces.picklist.MOVE_BOTTOM = Sposta al fondo
primefaces.rowgrouptoggler.aria.ROW_GROUP_TOGGLER = Seleziona/deseleziona gruppo di righe
primefaces.rowtoggler.aria.ROW_TOGGLER = Seleziona/deseleziona riga
primefaces.slider.OUT_OF_RANGE = {0}: Errore di validazione: Il valore è fuori intervallo.
primefaces.switch.LABEL_ON = On
primefaces.switch.LABEL_OFF = Off
primefaces.tree.REQUIRED = {0}: Errore di validazione.
primefaces.tree.REQUIRED_detail = È richiesta una selezione.`

**Comment by AlessandroBori** [comment]
done
```
primefaces.autocomplete.aria.DROPDOWN_LABEL=Mostra elementi
primefaces.calendar.DATE_INVALID_RANGE_MESSAGE_ID = {0}: Errore di validazione: La data d''inizio è successiva alla data di fine.
primefaces.calendar.INVALID = {0}: Errore di validazione: Valore non valido.
primefaces.calendar.MIN_DATE = {0}: Errore di validazione: Il valore dev''essere {1} o successivo.
primefaces.calendar.MAX_DATE = {0}: Errore di validazione: Il valore dev''essere {2} o precedente.
primefaces.calendar.OUT_OF_RANGE = {0}: Errore di validazione: Il valore dev''essere compreso tra {1} e {2}.
primefaces.captcha.INVALID = {0}: Errore di validazione: Valore non valido.
primefaces.captcha.INVALID_detail = {0}: ''{1}'' non corrisponde al testo visualizzato.
primefaces.data.EMPTY_MESSAGE = Nessun risultato trovato.
primefaces.datatable.aria.FILTER_BY = Filtro per {0}
primefaces.datatable.aria.HEADER_CHECKBOX_ALL = Seleziona tutti
primefaces.datatable.SORT_ASC = Crescente
primefaces.datatable.SORT_DESC = Decrescente
primefaces.datatable.SORT_LABEL = Ordina
primefaces.dialog.aria.CLOSE = Chiudi
primefaces.fileupload.CLAM_AV_FILE = ClamAV ha identificato il file '{0}' come potenzialmente dannoso con messaggio '{1}'
primefaces.fileupload.VIRUS_TOTAL_FILE = Virus Total ha identificato il file '{0}' come potenzialmente dannoso
primefaces.input.aria.filter = Filtro
primefaces.messages.aria.CLOSE = Chiudi
primefaces.messages.aria.ERROR = Errore
primefaces.messages.aria.FATAL = Fatale
primefaces.messages.aria.INFO = Informazione
primefaces.messages.aria.WARN = Attenzione
primefaces.paginator.aria.FIRST_PAGE = Prima pagina
primefaces.paginator.aria.HEADER = Paginazione
primefaces.paginator.aria.LAST_PAGE = Ultima pagina
primefaces.paginator.aria.NEXT_PAGE = Pagina successiva
primefaces.paginator.aria.PREVIOUS_PAGE = Pagina precedente
primefaces.paginator.aria.ROWS_PER_PAGE = Righe per pagina
primefaces.panel.aria.OPTIONS_MENU = Menu di selezione opzioni
primefaces.panel.aria.TOGGLE = Pannello di selezione
primefaces.password.INVALID_MATCH = {0}: Errore di validazione.
primefaces.password.INVALID_MATCH_detail = {0} dovrebbe corrispondere a {1}.
primefaces.picklist.ADD = Aggiungi
primefaces.picklist.ADD_ALL = Aggiungi tutti
primefaces.picklist.REMOVE = Rimuovi
primefaces.picklist.REMOVE_ALL = Rimuovi tutti
primefaces.picklist.MOVE_UP = Sposta in alto
primefaces.picklist.MOVE_TOP = Sposta in cima
primefaces.picklist.MOVE_DOWN = Sposta in basso
primefaces.picklist.MOVE_BOTTOM = Sposta al fondo
primefaces.rowgrouptoggler.aria.ROW_GROUP_TOGGLER = Seleziona/deseleziona gruppo di righe
primefaces.rowtoggler.aria.ROW_TOGGLER = Seleziona/deseleziona riga
primefaces.slider.OUT_OF_RANGE = {0}: Errore di validazione: Il valore è fuori intervallo.
primefaces.switch.LABEL_ON = On
primefaces.switch.LABEL_OFF = Off
primefaces.tree.REQUIRED = {0}: Errore di validazione.
primefaces.tree.REQUIRED_detail = È richiesta una selezione.
```

**Comment by melloware** [comment]
awesome let me fix it right now.
