### ISSUE TITLE
Primefaces-Showcase: Typo in DataExporter / DataTable examples

### ISSUE THREAD

**Issue by elab** [primefaces/primefaces#7574]
Some buttons in examples are titled with "XLXS" where it should be "XLSX".

Affected files (simply search by "XLXS"):

primefaces-showcase/src/main/webapp/ui/data/dataexporter/basic.xhtml
primefaces-showcase/src/main/webapp/ui/data/dataexporter/excludeColumns.xhtml
primefaces-showcase/src/main/webapp/ui/data/dataexporter/lazy.xhtml
primefaces-showcase/src/main/webapp/ui/data/dataexporter/treetable.xhtml
primefaces-showcase/src/main/webapp/ui/data/datatable/group.xhtml

PrimeFaces Version: current master

**Comment by melloware** [comment]
Thanks for pointing this out!
