### ISSUE TITLE
Tree: TreeNode Drag&Drop not working

### ISSUE THREAD

**Issue by msquare** [primefaces/primefaces#7575]
**Describe the defect**
With #7273 the support for drag&drop in the tree element broke. This is since the javascript init function applies drag&drop classes to span elements, which were changed to div in #7273.

**Reproducer**
Just try the tree dragdrop example from the showcase.

**Expected behavior**
The expected behavior is that you can drag items around using your mouse.

**Example**
https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml

**Suggested Fix**
Change these two lines from `span` to `div`:
https://github.com/primefaces/primefaces/blob/c0566bca0afa3c3ec3ca5cb5e330ec2b6051d4fa/primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.base.js#L184
https://github.com/primefaces/primefaces/blob/c0566bca0afa3c3ec3ca5cb5e330ec2b6051d4fa/primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.base.js#L189

Thank you!

**Comment by melloware** [comment]
Good catch!
