### ISSUE TITLE
Calendar: mindate and maxdate does not work

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#7576]
**Describe the defect**
As described here
https://forum.primefaces.org/viewtopic.php?f=3&t=67214
setting mindate/maxdate in p:calender get strange results. 

This one works:
`<p:calendar id="cal" mode="inline"
	value="#{data.selectedDate}"
	pattern="dd.MM.yyyy" locale="de"
	mindate="03.06.2021"
	maxdate="09.06.2021">
	<p:ajax event="dateSelect" listener="#{controller.dateSelectListener}" update="controlButtons"/>
</p:calendar>`

For this dates, I got a  error "Calendar : "cal" minimum date must be less than maximum date.": 
`<p:calendar id="cal" mode="inline"
	value="#{data.selectedDate}"
	pattern="dd.MM.yyyy" locale="de"
	mindate="27.05.2021"
	maxdate="10.06.2021">
	<p:ajax event="dateSelect" listener="#{controller.dateSelectListener}" update="controlButtons"/>
</p:calendar>`

**Reproducer**
Just open your showcase
https://www.primefaces.org/showcase/ui/input/calendar/calendar.xhtml
In your showcase mindate="4/1/14" and maxdate="7/1/14". It seems that p:calendar does not use these values.

**Environment:**
 - PF Version: 10.0.0
 - JSF + version: MyFaces 2.3.9
 - Affected browsers: all

**To Reproduce**
See "Reproducer" for details.

**Expected behavior**
mindate and maxdate should work as expected for ALL dates. I can't migrate to datepicker at the moment, which was suggested by another user.

**Example XHTML**
See "Reproducer" for details.

**Example Bean**
See "Reproducer" for details.

**Comment by wal-jan** [comment]
DatePicker shows same behaviour
```
<p:datePicker id="datepicker" mindate="27.05.2021" maxdate="10.06.2021" pattern="dd.MM.yyyy"/>
```
results in `... minimum date must be less than maximum date`
