### ISSUE TITLE
TreeTable: Filtering and selectionMode checkbox combination bug

### ISSUE THREAD

**Issue by BalthaZarr83** [primefaces/primefaces#7581]
Defect:
When I add filtering capacity to a treeTable with selectionMode set to checkbox, the checkboxes get rendered even for nodes with selectable set to false. Somehow the styleclass ui-treetable-selectable-node is also added to the tr element corresponding with the unselectable node.

I created a sample Project based on the primefaces test prpject:
https://github.com/BalthaZarr83/PF-TreeTable-Bug-Demo

The problem also exists on the latest elite Version (10.0.3) and is independent of jsf implementations.

Kind Regards,
Mike

**Comment by BalthaZarr83** [comment]
I looked a bit deeper into the problem:
It seems the problem lies in the TreeTableRenderer class:
The filter method is calling the cloneTreeNode(TreeTable tt, TreeNode node, TreeNode parent) method.
But this method is ignoring the selectable property of the original node, therefore the clone gets the selectable=true default property.

**Comment by melloware** [comment]
Let me look...

**Comment by melloware** [comment]
Hmm I see this in clone tree node?

```java
clone.setSelected(node.isSelected());
clone.setExpanded(node.isExpanded());
```

**Comment by BalthaZarr83** [comment]
Right, but selected is not selectable. It's selectable property that defines whether the ui-treetable-selectable-node styleclasses get added to the tr elements.

**Comment by BalthaZarr83** [comment]
...so:
clone.setSelectable(node.isSelectable));
should do it.

**Comment by melloware** [comment]
Good catch. PR submitted.
