### ISSUE TITLE
Badge: does not render with ui-badge-dot class on empty value

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7586]

**Comment by melloware** [comment]
Can you just add a description or code snippet to the problem please.

**Comment by jepsar** [comment]
It's not much more than the title. `Badge.DOT_CLASS` is never added when you use `<p:badge value="#{null}">` or `<p:badge value="">` in the test project.

```java
String styleClass = getStyleClassBuilder(context)
                    ....
                    .add(value == null, Badge.DOT_CLASS)
```
