### ISSUE TITLE
DataTable: with frozen and dynamic columns loses sorting on refresh

### ISSUE THREAD

**Issue by jlaera** [primefaces/primefaces#7590]
After re-render the table, the icons that indicates which column was used in the sorting does not appear everywhere. 
Actually the sort indicator is only displayed for the frozen columns but not for the dynamic ones.

For the reproducer, you can use the showcase "DataTable Dynamic Columns" and by simply adding the frozen attribute like below:

```
<p:dataTable id="customers" var="customer" value="#{dtColumnsView.customers}" widgetVar="customersTable" frozenColumns="2" scrollable="true" ...>
```

**Steps to reproduce the behavior:**
_please adapt the showcase "DataTable Dynamic Columns" as mentionned above_
1. click the first 3 columns to activate the multiple sort
2. click on the update button
3. first 2 columns keep the sort indicator but not the third one.

**Environment:**
 - PF Version: 10.0.4
 - JSF 2.3 : Mojarra 2.4.0
 - Affected browsers: ALL

**Expected behavior:**
The sort status must be displayed correctly for all column types

**Comment by melloware** [comment]
I have confirmed this is still an issue in 11.0.0-SNAPSHOT.  It works fine if `frozenColumns=2` is removed.

**Comment by melloware** [comment]
in PF 12.0 with this ticket: https://github.com/primefaces/primefaces/issues/8620

The sort indicators are cleared now and reset upon the update which is better.  If you then use `mutliViewState="true"` to remember your sorts and filters you still get the same behavior above with the frozen columns keeping their sort indicators but the non-frozen column not.

```xml
<p:dataTable id="customers" var="customer" value="#{dtColumnsView.customers}" widgetVar="customersTable"
                      filteredValue="#{dtColumnsView.filteredCustomers}" frozenColumns="2" scrollable="true" multiViewState="true">
```
