### ISSUE TITLE
TreeTable: Issue with filtering and unselectable Nodes

### ISSUE THREAD

**Issue by BalthaZarr83** [primefaces/primefaces#7591]
Somehow when using a treeTable with selectionMode="checkbox" and a column with the filterBy attribute, nodes with selectable set to false can end up in the TreeNode Array referenced by the selection attribute.

To reproduce it:
Select one item via the checkbox.
Then enter something in the Filter so that the previously selected element is no longer visible.
Then make another selection.

Environment
PF:10.0.0; independent of jsf implementations

I think the Issue is, that those propagation methods in the CheckboxTreeNode class (propagateSelectionDown(boolean value) and propagateSelectionUp(boolean value) don't check whether the nodes are selectable or not.

And one slightly-off-topic question:
The UiTree.PropertyKeys propagateSelectionDown and propagateSelectionUp can not be configured somehow for the treeTable component? Or am I missing something?
So far I was always overriding the treetable.js file and removing the propagation code and that worked, but now with the added filtering option that seems to be no longer sufficient...

Kind regards and thanks for the help on the last issue!
Mike

**Comment by tandraschko** [comment]
please provide a reproducer

**Comment by melloware** [comment]
> And one slightly-off-topic question:
> The UiTree.PropertyKeys propagateSelectionDown and propagateSelectionUp can not be configured somehow for the treeTable component? Or am I missing something?
> So far I was always overriding the treetable.js file and removing the propagation code and that worked, but now with the added filtering option that seems to be no longer sufficient...

@BalthaZarr83 your issue about propagation is already open and has been for a while here: https://github.com/primefaces/primefaces/issues/4644

**Comment by melloware** [comment]
PR submitted please review.

**Comment by BalthaZarr83** [comment]
Wow you are fast:-)
That would be the reproducer, if it still helps
https://github.com/BalthaZarr83/PF-TreeTable-Bug-Demo

Note that to prove that the propagation bug is independent of the yesterday reported bug in the cloneMethod I added a custom TreeTableRenderer with the extra line that fixes the clone bug.

**Comment by BalthaZarr83** [comment]
> 
> 
> > And one slightly-off-topic question:
> > The UiTree.PropertyKeys propagateSelectionDown and propagateSelectionUp can not be configured somehow for the treeTable component? Or am I missing something?
> > So far I was always overriding the treetable.js file and removing the propagation code and that worked, but now with the added filtering option that seems to be no longer sufficient...
> 
> @BalthaZarr83 your issue about propagation is already open and has been for a while here: #4644

Thanks melloware, and sorry for not checking that before!

**Comment by melloware** [comment]
@BalthaZarr83 I submitted a PR for the propagation props too.  It was already supported just missing from the taglib.xml for you to be able to set them.

https://github.com/primefaces/primefaces/pull/7593

**Comment by BalthaZarr83** [comment]
Great! Thanks!
