### ISSUE TITLE
Global: PF generates natural ids risking duplicates

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#7595]
**Describe the defect**
PrimeFaces renders helper markup such as overlay panels and generates ids to tie them together, by adding things like "_panel" to the base component id. Problem is those are very natural ids, that a web application developer could easily specify himself. The ids are generated in such a way that Mojarra's duplicate id detection doesn't notice them. Duplicate ids result in strange and hard to debug behavior at runtime.

**Reproducer**
[primefaces-duplicate-ids.zip](https://github.com/primefaces/primefaces/files/6824589/primefaces-duplicate-ids.zip)

**Environment:**
 - PF Version: _6.2.30_, _10.0_
 - JSF + version: _Mojarra 2.3.3_
 - Affected browsers: _ALL_

**To Reproduce**
1. Open http://localhost:8080/primefaces-test/
2. Click the menu
3. Note the overlay looking weird and the label and menu jumping down
4. Click on an option
5. Note label and menu dissappearing from the page
![dupids](https://user-images.githubusercontent.com/8070317/125819848-091589bb-43a2-4743-a7ab-e871299d2fb3.gif)

**Expected behavior**
PrimeFaces generates more obscure ids, that are harder to clash with. And/or supports validating generated id uniqueness.

**Example XHTML**
```
<h:form>
	<p:outputPanel id="stuff_panel">
		<p:outputLabel for="@next" value="stuff:"/>
		<p:selectOneMenu id="stuff">
			<f:selectItem itemLabel="Option1" itemValue="Option1"/>
			<f:selectItem itemLabel="Option2" itemValue="Option2"/>
		</p:selectOneMenu>
	</p:outputPanel>
</h:form>
```

**Example Bean**
Not needed.

**Comment by tandraschko** [comment]
I dont think we will change this. Its been there since over 10 years without problems.

I think one could easy create a simple JS to catch duplicate ids.

**Comment by VsevolodGolovanov** [comment]
This was brought on by upgrade from 6.1 to 6.2.30, where old code that lucked out and worked suddenly broke.

> without problems

Probably caused some wasted time, just nobody bothered reporting it.

**Comment by VsevolodGolovanov** [comment]
Even adding something small like "_pf_panel" would help a lot. And adapting to this change would be trivial, if someone hardcoded it in their css or js. Could be a simple change for a next major version.

**Comment by melloware** [comment]
I understand what you are saying. But yeah this would be a huge change in all the components everywhere.    Can definitely be done in a major version upgrade but it would probably touch almost every Renderer.java and every .js file.

**Comment by VsevolodGolovanov** [comment]
Maybe add configurable suffix, and leave it empty by default, so that it's an opt-in mechanism.

**Comment by tandraschko** [comment]
i will close this for now
as i said, im working on PF stuff since 2013 and never had such reports

i think this should be a sponsored thing as its a major change in almost every component
