### ISSUE TITLE
TabMenu: Add orientation

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#76]
Similar to TabView, add orientation support for TabMenu.

**Comment by tandraschko** [comment]
@melloware i thought we only stale defects?

**Comment by melloware** [comment]
I just updated it to exempt "New Feature and Enhancement" labels. 

 I wanted the first pass to mark everything older than 2 years to see if we really do need it.  For example this issue is 5 years old and came over from Google Code and honestly it has no upvotes or comments and realistically is never going to be implemented. See: https://github.com/primefaces/primefaces/issues/29

**Comment by mmagiati-egritos** [comment]
Hello, any news with this feature?

thank you!

**Comment by melloware** [comment]
@mmagiati-egritos Most likely you would have to sponsor this feature from PrimeTek.  You can use the email contact@primetek.com.tr to request a Quote for how much it would cost to implement this feature.

**Comment by jepsar** [comment]
This one is easy to do with just a few CSS tweaks. I could add an example to the showcase.
```xml
<div class="card">
    <h5 class="mt-0">Vertical</h5>
    <style>
        body .ui-tabmenu.vertical .ui-tabmenu-nav {
            flex-direction: column;
        }
        body .ui-tabmenu.vertical .ui-tabmenu-nav .ui-tabmenuitem {
            border-bottom: 0;
            border-right: 2px solid var(--surface-d);
        }
        body .ui-tabmenu.vertical .ui-tabmenu-nav .ui-tabmenuitem.ui-state-hover {
            border-right-color: var(--text-color-secondary);
        }
        body .ui-tabmenu.vertical .ui-tabmenu-nav .ui-tabmenuitem.ui-state-active {
            border-right-color: var(--primary-color);
        }
    </style>
    <p:tabMenu activeIndex="#{param.i}" style="width:15rem" styleClass="vertical">
        <p:menuitem value="Home" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-home">
            <f:param name="i" value="0"/>
        </p:menuitem>
        <p:menuitem value="Calendar" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-calendar">
            <f:param name="i" value="1"/>
        </p:menuitem>
        <p:menuitem value="Edit" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-pencil">
            <f:param name="i" value="2"/>
        </p:menuitem>
        <p:menuitem value="Documentation" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-file">
            <f:param name="i" value="3"/>
        </p:menuitem>
        <p:menuitem value="Settings" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-cog">
            <f:param name="i" value="4"/>
        </p:menuitem>
    </p:tabMenu>
</div>
```
<img width="481" alt="Screenshot 2022-06-26 at 10 00 39" src="https://user-images.githubusercontent.com/7500178/175805255-2eb7ee50-db50-43e6-97c5-7789704ef27e.png">

**Comment by melloware** [comment]
I wonder if we just add a `layout` attribute that is either horizontal or vertical and just add the CSS style that will apply your custom CSS  by just setting the style to Renderer?

**Comment by jepsar** [comment]
Will do
