### ISSUE TITLE
Column: wrong parsing of fieldname from sortby/filterBy VE

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#7607]
**Describe the defect**
As we're migrating all of our columns to use `UIColumn#field` instead of sortBy/filterBy. I recently discovered a bug when sortBy contains an expression like: `#{i18n[row][property]}`, it resolves a fieldname `i18n[row][property]` which obvisouly turn into a bug later on. Same goes for `p:columns` with `#{i18n[row][column[property]]}` (`row][column[property]` being resolved). Basically, our regexes are not restrictive enough, it should handle two very basic cases:

- `#{car.name}` -> name (for static columns)
- `#{car[column.property]}` -> name (for dynamic columns)

Beyond that, it gets too complicated to resolve field

**Environment:**
 - PF Version: 10.0
 - JSF + version:  Mojarra 2.2.20
 - Affected browsers: Chrome

**To Reproduce**
1. For static columns: Use a VE like `#{i18n[row][property]}` for sortBy 
2. For dynamic columns: Use a VE like `#{i18n[row][column[property]]}` for sortBy 

**Expected behavior**
Where field is not set, resolving field from these expressions should return null

**Comment by tandraschko** [comment]
We should even think about it, if we really need to parse field from the VE
field in SortMeta/FilterMeta isnt mandatory at all

**Comment by Rapster** [comment]
Well I always said that we should remove that thing, you'll always find a VE that will mess this up (I'm just fixing it for backward compatibility)... Regarding `UIColumn#field`, on the contrary I think it should be mandatory for sorting and filtering on the long run. Make even more sense for lazy tables, as it's some sort of alias of the column it helps you to identify your column.

**Comment by tandraschko** [comment]
what does your PR fix now?
"#{i18n[row][column[property]]}" still listed as unsupported in the test?

**Comment by Rapster** [comment]
That's the idea, better to return null than a wrong field. As mentionned, we should support two very basic VE of sortBy/filterBy instead of trying so hard to support everything
