### ISSUE TITLE
Tree: Focus / Navigation broken if tree is droppable

### ISSUE THREAD

**Issue by shelcomite** [primefaces/primefaces#7613]
If droppable is active on a p:tree and you tab to it the whole tree container is focused. And in this case it is impossible to select a node via keyboard.

**Reproducer**
https://www.primefaces.org/showcase/ui/data/tree/basic.xhtml
https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml

**Environment:**
PF Showcase v10

**To Reproduce**
Tab to focus the tree on both pages.

**Expected behavior**
basic tree: first node is focused
dragdrop tree: whole tree container focused. impossible to focus a node via keyboard.

**Example XHTML**
---

**Example Bean**
---

**Comment by melloware** [comment]
Definitely confirmed this issue and its something to do with multiple focus call conflicts when using Drag and Drop.

**Comment by FlipWarthog** [comment]
@melloware I started working on adding integration tests to reveal this issue, first proving that it works in the normal case and is broken in the drag/drop case, and it looks like this is happening for normal trees too in 11.0.0. 

Reproducer: [primefaces-test-pf7613.zip](https://github.com/primefaces/primefaces/files/6859413/primefaces-test-pf7613.zip)

**Comment by melloware** [comment]
Excellent.  When I run the showcase 11.0-SNAPSHOT I see the same behavior described above.  Focus is fine for normal trees and wrong for DragDrop Tree.  Are you saying your reproducer thinks its wrong for 11.0 for normal trees?

**Comment by shelcomite** [comment]
In V10 the droppoints (also li elements like nodes) are the problem. The jQuery find() selectors are looking for li instead of li.ui-treenode.


For example in VerticalTree: 

```
getFirstNode: function() {
    return this.jq.find("> ul.ui-tree-container > li:first-child")
}
```

should be something like this: 

```
getFirstNode: function () {
    return this.jq.find("> ul.ui-tree-container > li.ui-treenode").first();
};
```

**Comment by FlipWarthog** [comment]
> Excellent. When I run the showcase 11.0-SNAPSHOT I see the same behavior described above. Focus is fine for normal trees and wrong for DragDrop Tree. Are you saying your reproducer thinks its wrong for 11.0 for normal trees?

That's the behavior I'm seeing with both the primefaces-test(linked above) and the new integration test. I haven't done a dive into the showcase page to see what the differences are.

I still need to step through the js debugger to see if what I'm seeing is similar to what @shelcomite mentioned, which I think is what we were talking about yesterday.

**Comment by melloware** [comment]
Can either of you try this MonkeyPatch...
```javascript
if (PrimeFaces.widget.VerticalTree) {
    PrimeFaces.widget.VerticalTree.prototype.getFirstNode = function() {
        return this.jq.find("> ul.ui-tree-container > li.ui-treenode").first();
    }
}
```

**Comment by FlipWarthog** [comment]
@melloware That didn't quite work. I think the issue is related to [this issue](https://github.com/primefaces/primefaces/issues/7575).

Changing the above, as well as changing from span to div seems to fix it:
```javascript
    /**
     * Finds the first node.
     * @return {JQuery} The first node of this tree.
     */
    getFirstNode: function() {
        return this.jq.find("> ul.ui-tree-container > li.ui-treenode").first();
    },

    /**
     * Finds the label element for the given node.
     * @param {JQuery} node Node for which to find the corresponding label.
     * @return {JQuery} The element with the label for the given node.
     */
    getNodeLabel: function(node) {
        return node.find('> div.ui-treenode-content > span.ui-treenode-label');
    },
```

**Comment by melloware** [comment]
So this MonkeyPatch...
```javascript
if (PrimeFaces.widget.VerticalTree) {
    PrimeFaces.widget.VerticalTree.prototype.getFirstNode = function() {
        return this.jq.find("> ul.ui-tree-container > li.ui-treenode").first();
    };

    PrimeFaces.widget.VerticalTree.prototype.getNodeLabel = function(node) {
        return node.find('> div.ui-treenode-content > span.ui-treenode-label');
    };
}
```

**Comment by FlipWarthog** [comment]
Correction, your original MonkeyPatch works in PrimeFaces 10 since the span/div change wasn't made until later:
```javascript
if (PrimeFaces.widget.VerticalTree) {
    PrimeFaces.widget.VerticalTree.prototype.getFirstNode = function() {
        return this.jq.find("> ul.ui-tree-container > li.ui-treenode").first();
    }
}
```

There's a hitch, though: while this fixes the main focus issue, the bindKeyEvents cases for KeyCode.UP and KeyCode.DOWN still hit the droppoints so you're required to press either twice to actually move once.
