### ISSUE TITLE
Splitbutton: Spacebar does not keep menu open in Firefox

### ISSUE THREAD

**Issue by weiprd** [primefaces/primefaces#7614]
**Issue Description**
The submenu of the [SplitButton](https://www.primefaces.org/showcase/ui/button/splitButton.xhtml?jfwid=9a7bd) can be opened by pressing down the spacebar. When you release the spacebar, the submenu closes immediately. 
It stays open using the return key.

**Expected behavior**
I would expect the submenu to also stay open when using spacebar, so you can make the selection using the arrow keys. Just like it works with [SelectOneMenu](https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml?jfwid=2304f).
Both use the arrow to show the submenu.

**Comment by melloware** [comment]
I can't reproduce?  When I press the SpaceBar the splitButton menu opens and I can navigate it with arrows keys just fine?

Chrome 91.

**Comment by weiprd** [comment]
I used Firefox 78.12.0esr (64-Bit)

**Comment by melloware** [comment]
Firefox 89.0.2 (64-bit) has the same issue but Chrome and Edge do not.  @jepsar can you try Safari since I know you are a mac user?

**Comment by jepsar** [comment]
No issue with Safari Version 14.1.1 (16611.2.7.1.4)
