### ISSUE TITLE
InputGroup: highlighting does not cover whole inputGroup

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#7623]
**Describe the defect**
When an input text (or another input component) is part of an input group and the input text is hovered over or focused, only the input text is highlighted but not the input group addons (see picture below). The defect appears no matter if the input group addons are set before or after the input text.

![screenshot_highlighting_inputgroup](https://user-images.githubusercontent.com/77431692/126660033-b82644bb-9c5f-460b-8174-13b32300de1b.png)
![screenshot_highlighting_inputgroup_2](https://user-images.githubusercontent.com/77431692/126660810-29fc8f6b-be65-4039-9b68-23824b65dbfa.png)
![screenshot_highlighting_inputgroup_3](https://user-images.githubusercontent.com/77431692/126660833-0c65e87b-c758-4cce-9a25-1517dafd795a.png)

**Environment:**
 - PF Version: _10.0_
 - Rain 2.0.0

**Expected behavior**
When the input component of an input group is hovered over or focused, the highlighting should cover the whole input group including its input group addons.

**Example XHTML (for first picture above)**
```html
<h:form id="frmTest">
    <div class="ui-inputgroup p-col-2">
        <p:inputText placeholder="Username"/>
	<span class="ui-inputgroup-addon"><i class="pi pi-times"></i></span>
    </div>
</h:form>
```

**Comment by tandraschko** [comment]
new feature as never implemented to support this

**Comment by stolp** [comment]
To add my two cents, I don't think that this is a desirable behavior. 

IMHO hover-highlighting should be limited to active input elements, one at a time.

**Comment by melloware** [comment]
I just had this same conversation with a co-worker about this too and I agree with @stolp

**Comment by miedrl** [comment]
Okay but then I would expect the input element to be fully covered by the highlighting as in the second picture. In my opinion, the right border of the input element should be highlighted as well if the element has an inputgroup-addon attached at the right.

**Comment by melloware** [comment]
Assigning to PrimeTek

**Comment by miedrl** [comment]
Is there any update on when this will be fixed/implemented?

**Comment by jepsar** [comment]
@miedrl  this is easy to fix in your project with custom CSS. This is working for me (Chrome) in the showcase:
```css
.ui-inputgroup > :focus {
  z-index: 1;
}
```
