### ISSUE TITLE
PrimeFaces Selenium: evaluate http-proxy as generic solution for PrimeSelenium#guardAjax

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7625]
We may play around with https://github.com/lightbody/browsermob-proxy#http-request-manipulation.
I don´t plan to work on this immediatelly. Just to put it in our backlog and maybe come back later.

**Comment by melloware** [comment]
I created a new "integration_test" label so we can label tickets specifically for this.

**Comment by melloware** [comment]
@christophs78 going to close this as we have 700 integration tests running so I think the ship has sailed on this one.  I can re-open if you feel strongly about it. 😄
