### ISSUE TITLE
Primefaces 10: Removal of ui-state-error on password

### ISSUE THREAD

**Issue by sreekaranr** [primefaces/primefaces#7627]
**Describe the defect**

ui-state-error is not added to the list of classes when validation fails on p:password. This was working in version 8 and that is how we were able to identify and highlight the fields. In addition to removal of ui-state-error, no update on classes is made on validation errors for p:password making it difficult to implement a custom solution.

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. Go to 'https://www.primefaces.org/showcase/ui/input/password.xhtml?jfwid=62e38'
2. Inspect element on "Password" field and take a note of the classes. 
2. Click on 'Save' with out entering any fields and inspect on "Password" field
4. See error. You'll notice that there's no change in classes.

**Expected behavior**
ui-state-error is added or a class is updated in anyway to identify that there's been an error,
Example in version 8:
1. Go to 'https://www.primefaces.org/showcase-v8/ui/input/password.xhtml'. This is version 8.
2. Inspect element on "Password" field and take a note of the classes. 
3. Click on 'Save' with out entering any fields and inspect on "Password" field.
4. See expected behavior within "classes" where a new "ui-state-error" is added.

**Comment by melloware** [comment]
duplicate already fixed in Elite 10.0.2 and 11.0.0 see: https://github.com/primefaces/primefaces/issues/7219
