### ISSUE TITLE
Exporting from Data Table with lazy data model generates incorrect file if table is manipulated while exporting

### ISSUE THREAD

**Issue by hades646** [primefaces/primefaces#763]
The `org.primefaces.component.export.Exporter.exportAll(FacesContext, DataTable, Object)` method manipulates the `DataTable` object it receives, establishing the first row as 0, the page size as the total number of records, then it loads the "page" (the whole list) and it exports it, row by row. Finally, it restores the original values of the different variables and loads again the original page the user was seeing.

``` java
if(lazy) {
        if(rowCount > 0)
             {
                table.setFirst(0);
                table.setRows(rowCount);
                table.clearLazyCache();
                table.loadLazyData();
             }

            for(int rowIndex = 0; rowIndex < rowCount; rowIndex++) {
                exportRow(table, document, rowIndex);
            }

            //restore
            table.setFirst(first);
            table.setRowIndex(-1);
            table.clearLazyCache();
            table.loadLazyData();
        } 
```

The problem is that sometimes a lazy export can take long time to execute (why would we use lazy tables if not?) and, while the file is being generated, the user could change the filter or change the page, which would change the same `DataTable` object the export is using, thus generating an incorrect file.

Right now, my workaround is to create an identical hidden DataTable and linking the exporter to that one (since the user cannot manipulate it).

I'm guessing a good solution would be to clone the `LazyDataModel` object and use this clone only for that particular export. I guess the main challenge should be to evaluate the EL expressions over items of the clone instead of over the original one (maybe cloning also the `DataTable` object?).

I'm using PF 5.1 but checking [https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/export/Exporter.java](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/export/Exporter.java), the bug seems to be also present on the latest version.

Thank you very much.

**Comment by mateofacu** [comment]
I am facing the same problem here: PF 5.3
As you explained, the exporter could use a different instance of the lazyDataModel. 

Another work around is blocking the table UI depending on how long the export takes. Of couse, if its too long this is not a good appoach. In our case, we have limited the ammount of data to be exported so it is not a problem

**Comment by melloware** [comment]
I am going to close this for now as there is no good option other than blocking the UI.  Making a copy of the data does not seem to make sense for this corner case.    or another option you could write your own REST Service to export the data that way you control it and don't count on what's in the datatable.

**Comment by hades646** [comment]
You don't need to copy the data. You just need the state of the component (filters, sorting, etc.) and a clone of the lazydatamodel.
