### ISSUE TITLE
TreeTable: DefaultTreeNode.setChildren() produces NullPointerException

### ISSUE THREAD

**Issue by KaBo00oM** [primefaces/primefaces#7634]
**Describe the defect**
When using the Function DefaultTreeNode.setChildren(List<TreeNode> children) to setup the TreeTable a NullPointerException is thrown. because the rowKey of the Children is never set/updated. 

**Reproducer**
I recreated the issue by forking the primefaces-test git-repository to https://github.com/KaBo00oM/primefaces-test to show what happens.

**Environment:**
 - PF Version: _10.0.0_
 - JSF + Mojarra 2.2.20 
 - Affected browsers:  tested with Chrome, Edge, Firefox

**To Reproduce**
1. Create a root tree node
2. Add child node(A) as usual by using the Constructor ```public DefaultTreeNode(Object data, TreeNode parent)``` where parent is the root node
3. Create a another child node(B) but instead of using the same Constructor as in 1,
    use the Constructor  ```public DefaultTreeNode(Object data)```.
4. Put the child node into a new list 
5. Use the function ```DefaultTreeNode.setChildren(List<TreeNode> children)``` on the node (A) to add the node(B) to that node (where children is the List from **4.**)
6. Click on the button to expand the node(A) 
7. NPE

**Expected behavior**
I would expect that there is no difference between setting the parent in the child node via the Constructor or setting the children in the parent node via setChildren().

**Example XHTML**
```html
<h:form id="frmTest">
  <h1>#{testView.string}</h1>
        <p:outputPanel id="TreeTable2">
            <p:treeTable value="#{testView.root2}" var="data">
                <p:column headerText="Level">
                    <h:outputText value="#{data.level}"/>
                </p:column>
                <p:column headerText="Parent">
                    <h:outputText value="#{data.cxParent}"/>
                </p:column>
                <p:column headerText="Data">
                    <h:outputText value="#{data.uuid}"/>
                </p:column>
            </p:treeTable>
        </p:outputPanel>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
private String string;
    private Integer integer;
    private BigDecimal decimal;
    private LocalDateTime localDateTime;

    private DefaultTreeNode root2;
    
    @PostConstruct  
    public void init() {
        string = "Tree Table Test";
        initTree_2();
    }

    private void initTree_2() {
        root2 = new DefaultTreeNode(new TreeNodeData("Root", "-", UUID.randomUUID().toString()));

        DefaultTreeNode root2_lvl1_0 = new DefaultTreeNode(new TreeNodeData("Level 1", "root2", UUID.randomUUID()+"-0"), root2);

        List<TreeNode> treeNodeList_Children_0 = new ArrayList<>();
        treeNodeList_Children_0.add(new DefaultTreeNode(new TreeNodeData("Level 2", "root2_lvl1_0", UUID.randomUUID()+"-0")));

        root2_lvl1_0.setChildren(treeNodeList_Children_0);

    }
}
```

**Possible Location of the Bug**
The row keys are never set in the child nodes which produces the NPE in the Renderer.
in the Function.
```
public class TreeNodeChildren extends TreeNodeList {

...

 private void updateRowKeys(int index, TreeNode node) {
        int childCount = node.getChildCount();
        if (childCount > 0) {
            for (int i = index; i < childCount; i++) {
                TreeNode childNode = node.getChildren().get(i);
                updateRowKeys(node, childNode, i);
            }
        }
    }
}
 ```
The variable childCount is always 0 which means that the rowkey never gets set.

**Comment by tandraschko** [comment]
fixed it and added a unittest
