### ISSUE TITLE
Spinner: different stepFactor for increase/decrease

### ISSUE THREAD

**Issue by netslow** [primefaces/primefaces#7639]
**Description**
I've faced with task where I need different **stepFactor** for increase and decrease value. 

**Describe the solution you would like**
For increase **stepFactor** should be 6, when decrease it should be 1. Add two properties like: stepPlus and stepMinus.

**Additional context**
I've tried to handle it in setter method in bean. But if user clicks fast, this method doesn't work well.

**Comment by jepsar** [comment]
I'm not sure if this is really common thing to add to the spinner. What is your use case?

**Comment by melloware** [comment]
To me this is not really a needed feature and is easy to just MonkeyPatch yourself to get this behavior for that sepcific spinner.  Just use this patch script.

```javascript
if (PrimeFaces.widget.Spinner) {

    PrimeFaces.widget.Spinner.prototype.spin = function(dir) {
        var step = 0;
        if (dir > 0)
            step = 6 * dir;
        else
            step = 1 * dir;

        var currentValue = this.value ? this.value : 0,
            newValue = this.parseValue(currentValue + step);

        if (this.cfg.maxlength !== undefined && newValue.toString().length > this.cfg.maxlength) {
            newValue = currentValue;
        }

        this.value = newValue;
        this.format();
        this.input.attr('aria-valuenow', this.getValue());
    }
}
```

**Comment by melloware** [comment]
I am going to close this as wontFix.  We can always re-open if more and more people request this feature but since its easy enough for people to just use the MonkeyPatch above I don't think this should go into the product.

**Comment by jepsar** [comment]
@melloware Should't it be
```js
        if (dir > 0)
            step = 6 * dir;
        else
            step = 1 * dir;
```
?

**Comment by melloware** [comment]
Yep just updated my script :)

**Comment by netslow** [comment]
> To me this is not really a needed feature and is easy to just MonkeyPatch yourself to get this behavior for that sepcific spinner. Just use this patch script.
> 
> ```js
> if (PrimeFaces.widget.Spinner) {
> 
>     PrimeFaces.widget.Spinner.prototype.spin = function(dir) {
>         var step = 0;
>         if (dir > 0)
>             step = 6 * dir;
>         else
>             step = 1 * dir;
> 
>         var currentValue = this.value ? this.value : 0,
>             newValue = this.parseValue(currentValue + step);
> 
>         if (this.cfg.maxlength !== undefined && newValue.toString().length > this.cfg.maxlength) {
>             newValue = currentValue;
>         }
> 
>         this.value = newValue;
>         this.format();
>         this.input.attr('aria-valuenow', this.getValue());
>     }
> }
> ```

Thank you. I'll try this workaround.

**Comment by melloware** [comment]
Excellent let me know if that doesn't work for you.
