### ISSUE TITLE
TriStateCheckbox: required not working

### ISSUE THREAD

**Issue by macbyte0815** [primefaces/primefaces#7647]
required attribute is in <p:triStateCheckbox> not working.
Tested on version 6.25 and 8.0
Code:

```xml
<h:form>
<p:triStateCheckbox required="true" requiredMessage="Test123" >
</p:triStateCheckbox>
<p:commandButton value="TEST" actionListener="#{testBean.test()}"/>
<p:messages id="messages">
 <p:autoUpdate />
</p:messages>
</h:form>
```

Bean Code:

```java
@ManagedBean(name="testBean")
@SessionScoped
public class TestBean {

	public TestBean() {
		// TODO Auto-generated constructor stub
	}
	
	public void test() {
		System.out.println("TEST");
	}

}
```

**Comment by melloware** [comment]
You don't explain what doesnt work?  What you posted above the tristatecheckbox is not even bound to a backing bean?

**Comment by melloware** [comment]
Well not sure what the correct behavior is as a checkbox unchecked IS a value.  IS your idea that if its required they HAVE to check the box?  Because unchecked is sending a proper value that its unchecked.  Juts like a boolean checkbox its either TRUE or FALSE I don't think you can mark it "required"?   @tandraschko ??

**Comment by macbyte0815** [comment]
Im sorry. Well this is true. It sends a "0" for empty. In this case i thought it works like an empty InputText or InputNumber.
When required attribute is true. You have to set it to "1" or "2".
You can mark it as required see PrimeFaces User Guide 6.2 - Page 569

**Comment by melloware** [comment]
Unfortunately checkboxes don't work this way there is ALWAYS a value.

**Comment by jepsar** [comment]
See also https://showcase.omnifaces.org/validators/RequiredCheckboxValidator
