### ISSUE TITLE
DataTable/TreeTable: In a sorted datatable the aria-label in Primefaces 10 always shows the text "undefined" after the column name.

### ISSUE THREAD

**Issue by serial389** [primefaces/primefaces#7648]
In Primefaces 10 the `aria-label` for a sorted datatable is partly broken and always shows the text "undefined" after the column name.
In Primefaces 8 the `aria-label` works as expected.

 - PF Version: 8.0  works
 - PF Version: 10.0  don't work
 - PF Version: 11.0-SNAPSHOT  don't work
 - Affected browsers: ALL

**To Reproduce**
To see what is wrong go to the Primefaces showcase for DataTable Sort https://www.primefaces.org/showcase/ui/data/datatable/sort.xhtml
See in the HTML code the  `th` tags and the `aria-label` attribute.
All `aria-label` attribute always shows the text "undefined" after the column name.

**Expected behavior**
The `aria-label` should show the text like before in Primefaces 8

**That is wrong**.
In Primefaces 10 in the file src/main/resources/META-INF/resources/primefaces/datatable/datatable.js the aria label informations are get with this 3 lines of code
```
//aria messages
this.ascMessage = PrimeFaces.getAriaLabel('datatable.sort.SORT_ASC');
this.descMessage = PrimeFaces.getAriaLabel('datatable.sort.SORT_DESC');
this.otherMessage = PrimeFaces.getAriaLabel('datatable.sort.SORT_LABEL');
```
But the english default locale in the file src/main/resources/META-INF/resources/primefaces/core/core.js still has the old Primefaces 8 aria label keys for the datatable sort.
```
aria: {
    'paginator.PAGE': 'Page {0}',
    'calendar.BUTTON': 'Show Calendar',
    'datatable.sort.ASC': 'activate to sort column ascending',
    'datatable.sort.DESC': 'activate to sort column descending',
    'columntoggler.CLOSE': 'Close',
    'overlaypanel.CLOSE': 'Close'
 }
```

Btw.
The documentation for Primefaces 10 is also still on Primefaces 8 for these default datatable sort language keys.

So here is my fix for the file src/main/resources/META-INF/resources/primefaces/core/core.js:
```
aria: {
    'paginator.PAGE': 'Page {0}',
    'calendar.BUTTON': 'Show Calendar',
    'datatable.sort.SORT_ASC': 'activate to sort column ascending',
    'datatable.sort.SORT_DESC': 'activate to sort column descending',
    'datatable.sort.SORT_LABEL': 'activate to unsort column',
    'columntoggler.CLOSE': 'Close',
    'overlaypanel.CLOSE': 'Close'
 }
```

**Comment by melloware** [comment]
Great analysis.  Check out my PR. the PF8 labels are the correct labels and these should not have ben updated to their "server" side keys.

**Comment by serial389** [comment]
You PR bings back the aria-lables but it has a sideeffect on the new Primefaces 10 feature "allowUnsorting".
When for a DataTable allowUnsorting="true" is set the aria-label text is sometimes wrong because now there is no text for "no sort" in your PR.
In Primefaces 8 there is no allowUnsorting but this is new in Primefaces 10.
So you now in Primefaces 10 needs three different aria label text for sorting
1. ascending
2. descending
3. no sort

As an example it should work like this when allowUnsorting="true":
1. Table is sorted ascending - aria-lable shows after column name "activate to sort column descending"
2. Toggle the sort
3. Table is sorted descending - aria-lable shows after column name "activate to unsort column"
4. Toggle the sort
5. Table is unsorted - aria-lable shows after column name "activate to sort column ascending"

And of couse when allowUnsorting="false" the unsort is not possible and it works like in Primefaces 8.

**Comment by melloware** [comment]
No so when the column is unsorted it uses the Asc label which is `activate to sort column ascending` which is correct if you activate this column it will sort ascending.

```
                'datatable.sort.ASC': 'activate to sort column ascending',
                'datatable.sort.DESC': 'activate to sort column descending',
```

**Comment by serial389** [comment]
When i run your RP this is what i get for a sorted table with allowUnsorting="true":

1. Table is sorted ascending - aria-lable shows after column name "activate to sort column descending"
2. Toggle the sort
3. Table is sorted descending - aria-lable shows after column name "`activate to sort column ascending`"
4. Toggle the sort
5. Table is `unsorted` - aria-lable shows after column name "activate to sort column ascending"

And now the third line shows a wrong text.
When you toggle the sort in line 4 you will get the new unsorted table but the aria-lable has told you that you will get an ascending sort.

You are right the line 5 shows a correct text.
The problem is the line 3 which tells the next sort will be ascending but in fact the user will get an unsorted table.

**Comment by melloware** [comment]
I see let me fix

**Comment by melloware** [comment]
Ughhh this actually has to be dynamic based on `allowUnsorting` property as when `allowUnsorting='false"` then the next step in Step 3 would be "activate to sort column ascending".  So the logic was wrong previously even without missing labels.

**Comment by melloware** [comment]
@serial389 can you try my latest PR I think I have it all fixed.

**Comment by serial389** [comment]
I have tested your PR and the aria-label in a sorted datatable works as expected.

**Comment by melloware** [comment]
thanks for testing!
