### ISSUE TITLE
FileUpload: Chunked file upload throws ClassCastException if resume and commons-upload

### ISSUE THREAD

**Issue by wal-jan** [primefaces/primefaces#7659]
**Describe the defect**
Chunked FileUpload in advanced mode throws ClassCastException if `UPLOADER=commons` and `FileUpload Resume Servlet` is configured.
```
org.primefaces.webapp.FileUploadChunksServlet sendError
SEVERE: class org.eclipse.jetty.server.Request cannot be cast to class org.primefaces.webapp.MultipartRequest (org.eclipse.jetty.server.Request is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @60a7e509; org.primefaces.webapp.MultipartRequest is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @76973a6)
java.lang.ClassCastException: class org.eclipse.jetty.server.Request cannot be cast to class org.primefaces.webapp.MultipartRequest (org.eclipse.jetty.server.Request is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @60a7e509; org.primefaces.webapp.MultipartRequest is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @76973a6)
	at org.primefaces.component.fileupload.CommonsFileUploadDecoder.getUploadDirectory(CommonsFileUploadDecoder.java:36)
	at org.primefaces.util.FileUploadUtils.getChunkDir(FileUploadUtils.java:397)
	at org.primefaces.util.FileUploadUtils.listChunks(FileUploadUtils.java:376)
	at org.primefaces.component.fileupload.AbstractFileUploadDecoder.decodeUploadedBytes(AbstractFileUploadDecoder.java:132)
	at org.primefaces.webapp.FileUploadChunksServlet.doGet(FileUploadChunksServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
```
Browser console shows
```
GET http://localhost:8080/primefaces-test/file/resume/?X-File-Id=file.ext,1625515344526,application/x-zip-compressed,7464948
500 Server Error
{
"servlet":"FileUpload Resume Servlet",
"message":"Server Error",
"url":"/primefaces-test/file/resume/",
"status":"500"
}
 ```

**Reproducer**
[PF-7364-resume.zip](https://github.com/primefaces/primefaces/files/6918554/PF-7364-resume.zip)

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _Mojarra and MyFaces_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start server `mvn jetty:run`
2. Go to 'localhost:8080/primefaces-test/'
3. Click 'choose'
4. Select any non empty file
5. See errors in server log and browser console

**Expected behavior**
ClassCastException should not be thrown.

**Example XHTML**
```html
<h:form id="frmTest">
    <p:fileUpload id="fileupload" mode="advanced" maxChunkSize="65536" .../>
</h:form>
```

**Example web.xml**
```
    ...
    <context-param>
        <param-name>primefaces.UPLOADER</param-name>
        <param-value>commons</param-value>
    </context-param>
    ...
    <filter>
        <filter-name>PrimeFaces FileUpload Filter</filter-name>
        <filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>PrimeFaces FileUpload Filter</filter-name>
        <servlet-name>Faces Servlet</servlet-name>
    </filter-mapping>
    ...
    <servlet>
        <servlet-name>FileUpload Resume Servlet</servlet-name>
        <servlet-class>org.primefaces.webapp.FileUploadChunksServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>FileUpload Resume Servlet</servlet-name>
        <url-pattern>/file/resume/</url-pattern>
    </servlet-mapping>
```

**Example Bean**
see Reproducer

**Comment by wal-jan** [comment]
The root cause is: `UPLOADER=commons` requires `<filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>`. This filter wraps all POST requests having Content-Type `multipart...` with `org.primefaces.webapp.MultipartRequest`.
If FileUpload resume is configured the FileUpload widget sends GET or DELETE requests to the FileUpload Resume Servlet url-pattern (e.g. `/file/resume/`). These requests will be processed by `org.primefaces.webapp.FileUploadChunksServlet` `doGet` respectivly `doDelete` methods. These methods need to know the chunkDir for which they call `CommonsFileUploadDecoder#getUploadDirectory(MultipartRequest)`. But the FileUploadFilter did not wrap the request with MultipartRequest and processing of the requests result in ClassCastExceptions. 

I'm not sure what's the best way to resolve this issue. Maybe `FileUploadFilter` should wrap all requests to Resume Servlet url-pattern with `MultipartRequest`.

**Comment by melloware** [comment]
So Commons Upload supports this we are just not supporting it correctly?  My only other option is if it was not possible to support would be to throw an exception saying that "chunked is not supported with Commons FileUpload please use JSF Native uploading." or something like that.

**Comment by tandraschko** [comment]
im also not sure if we should support chunks in commons-upload mode as the way to go is servlet-upload IMO
and commons is just for older servers - or does it still have some nice features?

**Comment by wal-jan** [comment]
I'm fine with resuming chunked file uploads is only supported with native servlet uploader. But Primefaces should give a clear error message if the configuration is not supported.

**Comment by Rapster** [comment]
I'll have to take a look at this. As far as I can tell, filter mapping is not properly defined for FileUploadFilter

**Comment by tandraschko** [comment]
@Rapster still interessted? i would otherwise merge the PR

**Comment by Rapster** [comment]
Yup don't like the fix so far but don't have much time right now... but there is a real question regarding should we keep supporting commons. As you said, it's for old servers, which mostly likely are EOL today so it might not worth the effort

**Comment by tandraschko** [comment]
yep, ok
feel free to create a sucessor ticket in the future
