### ISSUE TITLE
Avatar: Color adjustments for dynamicColor mode

### ISSUE THREAD

**Issue by JensPiegsa** [primefaces/primefaces#7662]
**Description**

The current color spectrum of the `dynamicColor` mode might not fit into the theme of a page.

**Describe the solution you would like**

The widget could be used in a more flexible way if it would allow to customize the generated background colors.
How about two new optional attributes for saturation and lightness components?

**Example XHTML**
```xml
<p:avatar dynamicColor="true" saturation="80" lightness="33" label="..." />
```

**AvatarRenderer**
```java
    protected String generateBackgroundColor(Avatar avatar) {
        return "color:#fff;background-color: hsl(" 
                + Math.abs((avatar.getLabel().hashCode() % 40) * 9) + ", " 
                + avatar.getSaturation() + "%, "
                + avatar.getLightness() + "%);";
    }
```

**Comment by jepsar** [comment]
@melloware can be assigned to me if you like

**Comment by melloware** [comment]
Done!

**Comment by JensPiegsa** [comment]
@jepsar: Awesome!
