### ISSUE TITLE
TextEditor: QuillJS has security vulnerabilities

### ISSUE THREAD

**Issue by bh-tt** [primefaces/primefaces#7679]
**Description**
QuillJS is used in the TextEditor component and has [security vulnerabilities](https://snyk.io/vuln/SNYK-JS-QUILL-1245047). Unfortunately it appears to be [dead](https://github.com/quilljs/quill/issues/3359#issuecomment-832299063).

**Describe the solution you would like**
One can either patch the vulnerability itself using a fork or replace the component with another library (I'm not well versed in JS libraries so I have no recommendations).

**Additional context**
The JS library is usually found at `/javax.faces.resource/texteditor/texteditor.js.xhtml?ln=primefaces&v=8.0.4`

**Comment by melloware** [comment]
But isn't this why we use the OWASP HTML Sanitizer with Text Editor?

**Comment by bh-tt** [comment]
Yes, you're completely right. I need to do more research before opening an issue.
