### ISSUE TITLE
inputTextarea count new line (\r\n) as one symbol

### ISSUE THREAD

**Issue by skokovsergey** [primefaces/primefaces#768]
When i paste text from Word or other places inputTextarea count new line (\r\n) as one symbol and this two symbols will be send to back-end.

Reproduced here:
http://www.primefaces.org/showcase/ui/input/inputTextarea.xhtml

**Comment by mertsincan** [comment]
Fixed for 5.3.10 and 6.0.

Thanks @sudheerj  for your PR :+1:
