### ISSUE TITLE
DataView: misses ResourceDependency to touch/touchswipe.js

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#7686]
**Describe the defect**
When using DataView with a pager in mobile/touch modus, there will be an exception in the console 
'Uncaught TypeError: a.swipe is not a function'.
The same is true for DataGrid and DataList. All components missing the ResourceDependency to touch/touchswipe.js.

**Reproducer**
See example code below.

**Environment:**
 - PF Version: 10.0
 - JSF + version: does not matter
 - Affected browsers:  FF, all I guess

**To Reproduce**
Use example code provided. In Firefox using developer tools, to simulate a touch device. Look at the JS-Console:
Uncaught TypeError: a.swipe is not a function

**Expected behavior**
No exception.

**Example XHTML**
```html
<h:form id="frmTest">
            <p:dataView id="dataView"
                        columns="1"
                        value="#{testView.entries}"
                        var="_it"
                        paginator="true"
                        paginatorAlwaysVisible="true"
                        widgetVar="dataGridWidgetVar">
                <p:column>#{_it}</p:column>
            </p:dataView>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private List<String> entries = Arrays.asList("a", "b", "c", "d", "e", "f", "g");

    public List<String> getEntries() {
        return entries;
    }
}
```

**Comment by OBreidenbach** [comment]
@melloware: Just wondering if it not also missing at TreeTable?

**Comment by melloware** [comment]
If it is in DataTable then it should be in TreeTable.

**Comment by melloware** [comment]
OK I just fixed it adding it to treetable!
