### ISSUE TITLE
InputGroup: InputTextarea within InputGroup has wrong border-radius

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#7692]
**Describe the defect**
When I use an InputTextarea within an InputGroup (instead of an InputText), the InputTextarea does not have the right border-radius (e.g. 4px) on the side where no InputGroup-addons exist (see pictures below).

![inputGroup_inputTextarea](https://user-images.githubusercontent.com/77431692/128987246-a91ff47d-716e-40c9-ae3a-e071bdcadcc4.png)
![inputGroup_inputTextarea2](https://user-images.githubusercontent.com/77431692/128987268-1f652378-06f0-432b-811a-da1712a7ef36.png)

**Environment:**
 - PF Version: _10.0_
 - Diamond Theme

**Expected behavior**
The InputTextArea should have the right border-radius when used within an InputGroup. I know I can fix this with custom SCSS/CSS but it should be fixed from the source.

**Example XHTML**
```html
<h:form id="frmTest">
  <div class="ui-inputgroup>
    <p:inputTextarea />
    <i class="pi pi-check ui-inputgroup-addon"/>
  </div>
</h:form>
```

**Comment by melloware** [comment]
Assigned to PrimeTek
