### ISSUE TITLE
InputGroup: Is not responsive at 320px screen width (Firefox)

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#7693]
**Describe the defect**
In order to be accessible to all users, a website or web application has to fulfill a list of WCAG 2.1 success criteria. PrimeFaces' InputGroup does not fulfill success criterion [1.4.10](https://www.w3.org/TR/WCAG21/#reflow) as it does not adapt to a screenwidth of 320px, instead it flows over the edges of the viewport (see picture below).

![inputGroup_responsiveness](https://user-images.githubusercontent.com/77431692/128989653-c9cf5dfd-9876-4fdd-a5ee-b70ca68f61db.png)

**Environment:**
 - PF Version: _10.0_
 - Diamond Theme

**To Reproduce**
1. Go to the input showcase of the Diamond theme https://www.primefaces.org/diamond/input.xhtml
2. Scroll down to the end of the page, to the inputGroup showcase
4. Zoom the browser to 400% or use the browser's developer tools (e.g. Ctrl + Shift + M in Firefox) to change the viewport width to 320px.

**Expected behavior**
The InputGroup component should adapt its width to the width of the screen/viewport and not overflow the viewport.

**Comment by melloware** [comment]
Assigned to PrimeTek

**Comment by buunsal** [comment]
@miedrl 
![image](https://user-images.githubusercontent.com/45278820/129346472-8cbfb4ac-ce80-4516-89ef-fc099e65713f.png)
I didn't reproduce your issue

**Comment by miedrl** [comment]
@sqores I tried again and the error seems to only appear in Firefox. The responsiveness is fine in Google Chrome, Edge and Internet Explorer though.

**Comment by buunsal** [comment]
@miedrl  please update your browser or remove extensions
![image](https://user-images.githubusercontent.com/45278820/129355093-8a7f6601-c28f-40a3-b5a1-356c3507943f.png)

**Comment by melloware** [comment]
I can't reproduce either on Firefox 91.0 x64

**Comment by miedrl** [comment]
Okay, it's a problem with my browser. We use Extended Support Release 78.13
