### ISSUE TITLE
DatePicker: it needs a 2nd outside click to close the panel

### ISSUE THREAD

**Issue by iki-hacon** [primefaces/primefaces#7694]
**Describe the defect**
When you open the date picker panel with the button, and then click outside of the panel to close it again, it only closes on the second click.

**Reproducer**
https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml'
2. Click on the calendar icon in the "button" example
3. Click outside the panel to close it
4. Click again outside the panel to close it

**Expected behaviour**
It closes in step 3

Fix:
Remove in https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
the line 1855

```
        onButtonClick: function (event) {
            if (!this.isPanelVisible()) {
                this.inputfield.trigger('focus');
                this.showOverlay();
            }
            else {
                this.hideOverlay();
            }

            //REMOVE THIS LINE: this.datepickerClick = true;
        },
```
It sets the "datepickerClick" state to true on opening the panel which then prevents it from closing on the first outside/document click.
From my understanding this state is only for events from within the panel and inputfield and should not be used for the button. Am I right?

**Comment by melloware** [comment]
@jepsar can you review this?

**Comment by jepsar** [comment]
I'm having vacation right now. I can have a look this weekend.

**Comment by christophs78** [comment]
This line was part of the initial contribution. It was not added to fix some other issue.
![image](https://user-images.githubusercontent.com/10461942/129093334-4ac2c766-319c-4063-afe5-7f50d674dc2d.png)

From my side green flag to remove it.

**Comment by melloware** [comment]
MonkeyPatch:

```javascript
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.onButtonClick = function (event) {
            if (!this.isPanelVisible()) {
                this.inputfield.trigger('focus');
                this.showOverlay();
            }
            else {
                this.hideOverlay();
            }
    }
}
```

**Comment by stolp** [comment]
Applying this monkeypatch yields: Uncaught SyntaxError: Unexpected token ':'

Am I doing something wrong here?

**Comment by melloware** [comment]
Nope I just fixed the script :)  It has to be = not : before function

**Comment by stolp** [comment]
Thanks, now it works :-)
