### ISSUE TITLE
Tree: ContextMenu unbound when removing all tree nodes

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#7695]
**Describe the defect**
ContextMenu unbound when removing all tree nodes (except root node). The context menu is then launch with the selected node to null and could generate NullPointer by using a button afterwards.

**Reproducer**
[pf-tree-ctxmenu.zip](https://github.com/primefaces/primefaces/files/6969260/pf-tree-ctxmenu.zip)

**Environment:**
 - PF Version: _10.0_ and _11.0.0-SNAPSHOT_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Delete all visible tree nodes with 'Delete' button from ContextMenu
2. Right Click anywhere on the page to see the ContextMenu appear

**Expected behavior**
Right click anywhere on the web page should show the browser menu and not the tree context menu

**Example XHTML**
```html
<h:form id="frmTest">
    <p:tree id="treeTest" 
    	value="#{testView.root}" 
    	var="node" 
    	selectionMode="single" 
    	selection="#{testView.selectedNode}">
    	<p:treeNode>
         <h:outputText value="#{node}"/>
     </p:treeNode>
    </p:tree>
    
    <p:contextMenu for="treeTest">
    	<p:menuitem value="Delete"
    		icon="pi pi-trash"
    		action="#{testView.deleteNode}"
    		update="treeTest" />
    </p:contextMenu>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private static final long serialVersionUID = 1L;
	
    private TreeNode root;
    private TreeNode selectedNode;
    
    @PostConstruct  
    public void init() {
    	root = new DefaultTreeNode("Files", null);
    	
	TreeNode node0 = new DefaultTreeNode("Documents", root);
	TreeNode node1 = new DefaultTreeNode("Events", root);
        
        node0.getChildren().add(new DefaultTreeNode("Expenses.doc"));
        node0.getChildren().add(new DefaultTreeNode("Resume.doc"));
        
        node1.getChildren().add(new DefaultTreeNode("Invoices.txt"));
    }

    public void deleteNode() {
        selectedNode.getChildren().clear();
        selectedNode.getParent().getChildren().remove(selectedNode);
        selectedNode.setParent(null);

        selectedNode = null;
    }
    
    // GETTERs + SETTERs
    public TreeNode getRoot() {
        return root;
    }
    
    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }
}
```

**Comment by melloware** [comment]
Thanks for the reproducer. @FlipWarthog want to tackle this one?  I have a feeling the ContextMenu says if it can't find what its target is it binds to "document".

**Comment by FlipWarthog** [comment]
> Thanks for the reproducer. @FlipWarthog want to tackle this one?  I have a feeling the ContextMenu says if it can't find what its target is it binds to "document".

Can do.

**Comment by FlipWarthog** [comment]
@melloware After a bunch of poking and digging it seems the culprit is this block of code in `BaseTree`'s `bindContextMenu` method (tree.base.js, starting at line 137):
```js
$(document).off(containerEvent, this.jqTargetId).on(containerEvent, this.jqTargetId, null, function(e) {
    if(targetWidget.isEmpty()) {
        menuWidget.show(e);
    }
});
```

Unfortunately, it looks like that logic was explicitly put there but root driver for it is hard to tell. It originated with [this commit](https://github.com/primefaces/primefaces/commit/364309638f829973f07825eab55754a7c0629bf6).

#1920 seems related as well; it'll probably be worth adding a handful of new integration tests for Tree + ContextMenu to prove what works works and what doesn't doesn't, then see what the fix'll look like.

**Comment by FlipWarthog** [comment]
This MonkeyPatch should do it:
```js
if (PrimeFaces.widget.BaseTree) {
    PrimeFaces.widget.BaseTree.prototype.bindContextMenu = function(menuWidget, targetWidget, targetId, cfg) {
        var nodeContentSelector = targetId + ' .ui-tree-selectable',
        nodeEvent = cfg.nodeType ? cfg.event + '.treenode.' + cfg.nodeType : cfg.event + '.treenode',
        containerEvent = cfg.event + '.tree';

        $(document).off(nodeEvent, nodeContentSelector).on(nodeEvent, nodeContentSelector, null, function(e) {
            var nodeContent = $(this);

            if($(e.target).is(':not(.ui-tree-toggler)') && (cfg.nodeType === undefined || nodeContent.parent().data('nodetype') === cfg.nodeType)) {
                var isContextMenuDelayed = targetWidget.nodeRightClick(e, nodeContent, function(){
                    menuWidget.show(e);
                });

                if(isContextMenuDelayed) {
                    e.preventDefault();
                    e.stopPropagation(); 
                }
            }
        });

        $(document).off(containerEvent, this.jqTargetId).on(containerEvent, this.jqTargetId, null, function(e) {
            if(e.target.id == targetWidget.id && targetWidget.isEmpty()) {
                menuWidget.show(e);
            }
        });
    }
}
```

**Comment by brivalin** [comment]
I tried your MonkeyPatch and contextMenu doesn't appear anymore outside the tree when empty. That's OK for this.

But on my mind, I thought that the contextMenu should only appear on right click on nodes, and not appear on right click on the tree panel when there are no nodes inside.

What do you think about it ?

**Comment by FlipWarthog** [comment]
So, looking at that block of logic, I get the feeling that they explicitly need the ContextMenu to still be available even if all the nodes are removed. E.g. my ContextMenu has both Remove and Add, if I remove all I can no longer add new ones. If the behavior you're describing is how you'd like it to behave, you can use the following MonkeyPatch in your own app, but I think for the actual fix we'll probably want to leave that piece in (@melloware).

```js
if (PrimeFaces.widget.BaseTree) {
    PrimeFaces.widget.BaseTree.prototype.bindContextMenu = function(menuWidget, targetWidget, targetId, cfg) {
        var nodeContentSelector = targetId + ' .ui-tree-selectable',
        nodeEvent = cfg.nodeType ? cfg.event + '.treenode.' + cfg.nodeType : cfg.event + '.treenode',
        containerEvent = cfg.event + '.tree';

        $(document).off(nodeEvent, nodeContentSelector).on(nodeEvent, nodeContentSelector, null, function(e) {
            var nodeContent = $(this);

            if($(e.target).is(':not(.ui-tree-toggler)') && (cfg.nodeType === undefined || nodeContent.parent().data('nodetype') === cfg.nodeType)) {
                var isContextMenuDelayed = targetWidget.nodeRightClick(e, nodeContent, function(){
                    menuWidget.show(e);
                });

                if(isContextMenuDelayed) {
                    e.preventDefault();
                    e.stopPropagation(); 
                }
            }
        });
    }
}
```

**Comment by melloware** [comment]
Yes I  would submit a PR with your original MonkeyPatch fix.  It seems to be safer to do.

**Comment by brivalin** [comment]
It seems to be OK for me with the workaround.
I close the issue.
