### ISSUE TITLE
Dialog Framework: Action and JavaScript errors

### ISSUE THREAD

**Issue by NRanjbaran** [primefaces/primefaces#7698]
**Describe the defect**
There is a p:commandButton to open the dialog framework inside the xhtml page, which is itself a composite template.
After opening the dialog framework, show contents with the following JavaScript error in chrome inspection and the listeners on the dialog do not work too : 

`Uncaught TypeError: v.test is not a function
    at Function.se [as find] (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)
    at S.fn.init.find (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)
    at new S.fn.init (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)
    at S (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)
    at HTMLDocument.<anonymous> (serp.js.xhtml?ln=js:814)
    at HTMLDocument.dispatch (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)
    at HTMLDocument.v.handle (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)
    at jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2
    at ce (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)
    at se.setDocument (jquery.js.xhtml?ln=primefaces&v=10.0.0&e=10.0.0:2)`

If we do not use the main page into a template, we will not have an error.

**Environment:**
 - PF Version: 10.0.0
 - JSF version: 2.2
 - Affected browsers: Chrome

**To Reproduce**
1. Click on a p:commandButton into a h:form in a xhtml file
2. Open dialog framework
3. Get inspect element on chrome and see the JavaScript errors

**Example XHTML**

template.xhtml :
```
<!DOCTYPE html>
<html
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes"/>
            <meta name="theme-color"/>
        </f:facet>
        <h:outputScript library="ultima-layout" name="js/nanoscroller.js"/>
        <h:outputScript library="ultima-layout" name="js/layout.js"/>
        <h:outputScript library="js" name="serp.js"/>

        <ui:insert name="head"/>
    </h:head>
    <h:body class="main-body">
        <h:outputStylesheet library="ultima-layout" name="css/nanoscroller.css"/>
        <h:outputStylesheet library="ultima-layout" name="css/animate.css"/>
        <h:outputStylesheet library="css" name="serp.css"/>

       <ui:insert name="content"/>
    </h:body>
</html>
```

MyPage.xhtml (This page is ui:composition with template property, Click on button to open dialog framework) :
 ```
<ui:composition 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:o="http://omnifaces.org/ui"
                template="/WEB-INF/template.xhtml"
                xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:define name="content">
           <h:form>
            <p:commandButton 
                             icon="fa fa-arrow-circle-o-down"
                             actionListener="#{attachController.showDialog()}"/>
        </h:form>
    </ui:define>
</ui:composition>
```

attach.xhtml (xhtml form to open as dialog framework) :
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

<h:head>

</h:head>
<h:body>
    test content
</h:body>
</html>
```

**Example Bean**
```java
@Named
@SessionScoped
public class AttachController implements Serializable {

public void showDialog() {
        Map<String,Object> options = new HashMap<>();
        options.put("includeViewParams", true);
        options.put("closable", false);
        options.put("modal", true);
        options.put("width", "70%");
        options.put("height", "60%");
        options.put("dynamic", "true");

        PrimeFaces.current().dialog().openDynamic("/resources/attach/attach.xhtml", options, null);
    }
}
```

**Comment by melloware** [comment]
I can't reproduce. Attached is my reproducer:
[pf-7698.zip](https://github.com/primefaces/primefaces/files/6975494/pf-7698.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

its working fine for me.

**Comment by NRanjbaran** [comment]
It worked properly on a reproducer, but it has an error on my project. I need more research in my project.
Thank you very much

**Comment by melloware** [comment]
No problem.  It could be Ultima related I see you are using that theme.  Other than that it must be something local in your project.
