### ISSUE TITLE
Datatable: LazyDataModel+RowEditor breaks with Session serialized/restored

### ISSUE THREAD

**Issue by t-oster** [primefaces/primefaces#7699]
**Describe the defect**
When using Datatable with a lazy data model and a row editor, as soon as the session is serialized/deserialized between the requests (e.g. with spring session for load-balancing), the model does not get updated anymore before the RowEditEvent is processed.

**Reproducer**
See my clone of the primefaces-test repo.
This commit https://github.com/t-oster/primefaces-test/commit/aeee1eeb4195ce2730958c107e6446cd85f820b1 introduces the bug by just enabling session serializing/restoring on every request.

**To Reproduce**
Create a Datatable with Row editor and lazy data model. You can use this as working example:
https://github.com/t-oster/primefaces-test/commit/a77ad2ffbd95809d942c15df3378bb21c9c2c04e
If you edit a row, the updated value is shown in the growl.
Apply the next commit  https://github.com/t-oster/primefaces-test/commit/aeee1eeb4195ce2730958c107e6446cd85f820b1  and retry. Now the setSampleValue() is never called during postback, eventhough the values are sent as POST and the row edit event is fired.

**Comment by tandraschko** [comment]
Can you please try a 11.0 Snapshot?
We fixed around 50 datatable bugs since 10.0

**Comment by t-oster** [comment]
Thanks for the quick response. Can you give me an exact version number for the pom.xml?
I just tried 
```
<dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>
```
but I cannot get it to compile/run.

**Comment by tandraschko** [comment]
Check our readme how to configure jitpack
Otherwise build from source

**Comment by t-oster** [comment]
It downloads the latest version from jitpack and compiles. But when it starts it only complains about a number of duplicate jar files and bails out:
```org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement scanned from multiple locations: jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/animal-sniffer-annotations-1.17.jar!/org/codehaus/mojo/animal_sniffer/IgnoreJRERequirement.class, jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/animal-sniffer-annotations-1.14.jar!/org/codehaus/mojo/animal_sniffer/IgnoreJRERequirement.class
com.fasterxml.classmate.AnnotationConfiguration$StdConfiguration scanned from multiple locations: jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.5.1.jar!/com/fasterxml/classmate/AnnotationConfiguration$StdConfiguration.class, jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.3.4.jar!/com/fasterxml/classmate/AnnotationConfiguration$StdConfiguration.class
com.fasterxml.classmate.AnnotationConfiguration scanned from multiple locations: jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.3.4.jar!/com/fasterxml/classmate/AnnotationConfiguration.class, jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.5.1.jar!/com/fasterxml/classmate/AnnotationConfiguration.class
com.fasterxml.classmate.AnnotationInclusion scanned from multiple locations: jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.3.4.jar!/com/fasterxml/classmate/AnnotationInclusion.class, jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.5.1.jar!/com/fasterxml/classmate/AnnotationInclusion.class
com.fasterxml.classmate.AnnotationOverrides$StdBuilder scanned from multiple locations: jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.3.4.jar!/com/fasterxml/classmate/AnnotationOverrides$StdBuilder.class, jar:file:///home/thomas/NetBeansProjects/primefaces-test/target/primefaces-test-1.0-SNAPSHOT/WEB-INF/lib/classmate-1.5.1.jar!/com/fasterxml/classmate/AnnotationOverrides$StdBuilder.class
```
and many more....

I cannot find any other reference to jitpack in the readme as just to add the repository (which is already added in the test-project) and change the groupId to com.github.primefaces, which I did.

https://github.com/t-oster/primefaces-test/commit/39fb23ef7e9d53c0df2e41ce969da2727f667a09

**Comment by melloware** [comment]
Don't run in Netbeans run at command line `mvn clean jetty:run`.

**Comment by tandraschko** [comment]
When i clone your repo, the Error is already visible without applying the commit you mentioned?

**Comment by t-oster** [comment]
I now compiled 11.0.0-SNAPSHOT from the github repository.
I get 
```
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@5396eeb1{/primefaces-test,[file:///home/thomas/NetBeansProjects/primefaces-test/src/main/webapp/, jar:file:///home/thomas/.m2/repository/org/glassfish/javax.faces/2.2.20/javax.faces-2.2.20.jar!/META-INF/resources, jar:file:///home/thomas/.m2/repository/org/primefaces/primefaces/11.0.0-SNAPSHOT/primefaces-11.0.0-SNAPSHOT.jar!/META-INF/resources],UNAVAILABLE}{file:///home/thomas/NetBeansProjects/primefaces-test/src/main/webapp/}
java.lang.reflect.MalformedParameterizedTypeException
    at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments (ParameterizedTypeImpl.java:59)
```
even when running from command line.

If you run
```
git clone https://github.com/t-oster/primefaces-test.git
cd primefaces-test
git checkout working
mvn clean jetty:run
#now go to http://localhost:8080/primefaces-test/ and verify the changes are reflected in the message when saving a row
#now ctrl+c
git checkout broken
mvn clean jetty:run
#now the changes are not reflected anymore
```

**Comment by melloware** [comment]
can you please run `mvn --version` and show us the entire results?  I want to see what JDK you are using etc.

**Comment by t-oster** [comment]
```
Apache Maven 3.8.1 (NON-CANONICAL_2021-04-26T21:52:54Z_root)
Maven home: /opt/maven
Java version: 11.0.12, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.13.5-arch1-1", arch: "amd64", family: "unix"
```

I also tried opendk-8

**Comment by tandraschko** [comment]
test project now works again with PF11

**Comment by tandraschko** [comment]
i now reintroduced that old code
it would be great if we could somehow create a test for it, so we can easily refactor in future
@melloware @christophs78 any idea? maybe we can set such a serialization strategy in tomcat/tomee

**Comment by melloware** [comment]
@tandraschko is this the same issue the JoinFaces guys were reporting?

**Comment by tandraschko** [comment]
looks like the same, yes

**Comment by christophs78** [comment]
@tandraschko Should javax.faces.STATE_SAVING_METHOD=client also kick in serialization or is this different?
(https://github.com/primefaces/primefaces/pull/7702 adds client side state-saving to our nightly IT´s. IMO we missed to test this until now.)
Do we need some more for this issue? (At least we probably need to add another integrationtest for this specific DataTable-rowedit-usecase.)
Which part cares about serialization? Core-Java? (Or are there some differences between CDI and Spring, different CDI-implemetations, different applicationserver, JSF-impls, .... ???)
@persapiens - some input on this?

**Comment by tandraschko** [comment]
Good point and idea.
Serialization of component/viewstate is done by jsf impl and saved on client or server with Java serialization but replaceable by e.g. Myfaces SPI.

CDI beans (viewscoped, sessionscoped, window,...) are stored in session and the AS or servlet container decides when to serialize

**Comment by christophs78** [comment]
Tomcat/TomEE - equivalent to `org.eclipse.jetty.server.session.NullSessionCache` / `org.eclipse.jetty.server.session.FileSessionDataStore`. (see https://github.com/t-oster/primefaces-test/commit/aeee1eeb4195ce2730958c107e6446cd85f820b1)

Basic strategy:
https://stackoverflow.com/questions/35917945/tomcat-how-to-persist-a-session-immediately-to-disk-using-persistentmanager 

How to do this with embedded Tomcat (and hopefully TomEE): 
https://stackoverflow.com/questions/33871335/how-to-add-context-xml-file-to-embedded-tomcat-server

UPDATE: TomcatEmbeddedServletContainerFactory is Spring-specific. Does not help in our usecase.

**Comment by christophs78** [comment]
To add something like https://github.com/t-oster/primefaces-test/commit/a77ad2ffbd95809d942c15df3378bb21c9c2c04e to our IT´s:
We already have DataTable007Test which checks rowEdit-event for non-lazy datasource. We need something similar for lazy datasources.

**Comment by t-oster** [comment]
Thank you for the quick response and fix. However the underlying cause is described in https://github.com/joinfaces/joinfaces/issues/1159#issuecomment-893390402 and an IMHO easier fix instead of reintroducing old code is just fix the deserializer.

I added a fixed branch to my repository https://github.com/t-oster/primefaces-test/commit/1cd8d2473c20c01c9f47eed868da1251d6a8ebaa which includes the workaround mentioned in https://github.com/joinfaces/joinfaces/issues/1159#issuecomment-897930857. 

So if anyone needs a workaround now, feel free to use https://github.com/t-oster/primefaces-test/blob/workaround/src/main/java/org/primefaces/test/LazyDataModelFixed.java

EDIT: Not yet tested in all cases. Fixes my test-case though.

**Comment by tandraschko** [comment]
+1 for your nicer fix
Can you provide a PR?

**Comment by t-oster** [comment]
@tandraschko after I confirm it works in my big project tomorrow, I will.

**Comment by t-oster** [comment]
@tandraschko I improved my version a bit because it did not work in my bigger project. I now wrap the data in a LinkedList because I got a NotSerializableException in some cases and I also try to backup/restore the rowIndex and listeners.
However it may be that the listeners are called on restore because I have to call setRowIndex(). Also I guess the wrapped list is now serialized twice (first in the original serialization and then in my version), which may be a waste of storage.

All in all I am not sure if this is the most elegant solution, seems a bit hacky to me.

Are you still interested in a PR?

**Comment by tandraschko** [comment]
hmmm
doesnt sound better as the current solution ;D

**Comment by t-oster** [comment]
yes, that was what I thought. However for anyone stuck with PF 10 the workaround can be used. Thanks for the quick replies.

**Comment by christophs78** [comment]
I´m giving up trying to find a Tomcat/TomEE - equivalent for org.eclipse.jetty.server.session.NullSessionCache (https://github.com/t-oster/primefaces-test/commit/aeee1eeb4195ce2730958c107e6446cd85f820b1) we may add to our integrationtests.
At least it looks like there´s no OOTB-solution for this. Tried a few things without success.

**Comment by Rapster** [comment]
Just catching up with modifications that has been made lately, IMO the solution would be what BalusC is saying here: https://github.com/jakartaee/faces/issues/1585

> The recommended approach is however to make it transient and then lazily construct it in getter method.

Besides that, if we continue with that fix,  `LazyDataModel` should inherit from `DataModel` and no longer `ListDataModel` (because everything is overrided :smile: )
