### ISSUE TITLE
Add input page to Paginator

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#77]
One of the most demanded functionality of our clients is that the paginators should contain an input text where they can type the page of the datatable/datagrid, press enter and display that page.

**Comment by sudheerj** [comment]
We can add {JumpToPageInput} input template similar to {JumpToPageDropdown} dropdown.But Do we need to skip setting the page when user enters an invalid value(out of range,non-numeric characters) or any error notifications for the user.

**Comment by tandraschko** [comment]
Duplicate of: https://github.com/primefaces/primefaces/issues/3198
