### ISSUE TITLE
Filters: MatchMode NOT_EQUAL

### ISSUE THREAD

**Issue by jesjimher** [primefaces/primefaces#7704]
**Description**
Building a filter with `FilterMeta` is very easy:

```
FilterMeta fm=FilterMeta.builder()
                .field("status")
                .filterValue(CustomerStatus.NEW)
                .matchMode(MatchMode.EQUALS)
                .build();
```
But available `MatchMode`s don't cover all needs. According to javadoc, the only supported values for `MatchMode` are:

```
CONTAINS     
ENDS_WITH    
EQUALS   
EXACT    
GLOBAL   
GREATER_THAN     
GREATER_THAN_EQUALS  
IN   
LESS_THAN    
LESS_THAN_EQUALS     
RANGE    
STARTS_WITH
```
So, something as simple as filtering by value different than X, isn't possible with `FilterMeta` right now.

**Describe the solution you would like**
It would be nice if `MatchMode.NOT_EQUALS` existed. For coherence, `NOT_IN`, `NOT_CONTAINS` and others should exist too.

Perhaps a wiser alternative would be leaving `MatchMode` alone, but adding a `not()` method to `FilterMeta` builder, which would negate current `MatchMode`. This way, a "different than" filter could be written like:

```
FilterMeta fm=FilterMeta.builder()
                .field("status")
		.not()
                .filterValue(CustomerStatus.NEW)
                .matchMode(MatchMode.EQUALS)
                .build();
```

**Comment by tandraschko** [comment]
as "not" cant be applied to all MatchModes, i think we should introduce new MatchModes like NOT_EQUAL, NOT_CONTAIN and so on

@Rapster WDYT?

**Comment by Rapster** [comment]
Which MatchMode you think negation can't be applied? Beside GLOBAL (which is not really a matchmode) everything else look ok to me. +1 for adding new matchmode, just need to figure out a proper name for it (notIn, notEq, notRange etc. ?)

**Comment by tandraschko** [comment]
Range?
And greater/less is already  negated?

**Comment by Rapster** [comment]
Ah I didn't see it that way, yeah that work too. 
Yes like not in range, exclusion?

**Comment by tandraschko** [comment]
ok, so we can do it for:
```
CONTAINS     
ENDS_WITH    
EQUALS   
EXACT
IN
RANGE    
STARTS_WITH
```

but not for

```
GLOBAL   
GREATER_THAN     
GREATER_THAN_EQUALS  
LESS_THAN    
LESS_THAN_EQUALS     
```

right?

**Comment by jesjimher** [comment]
Shouldn't it be simpler to add a `.not()`/`.invert()` method to `FilterMeta`, that negated/inverted current `MatchMode`? I don't see any `MatchMode` that can't be negated. At most, some of them would be somewhat redundant (f. e. negating `GREATER_THAN` would be the same as just using `LESS_THAN_EQUALS`), but there's no actual harm in allowing two different ways of achieving the same effect. And just adding a single `.not()` method would be cleaner than having to add a bunch of `NOT_CONTAINS`, `NOT_EQUALS`, etc. MatchModes.

Just my opinion, of course.

**Comment by tandraschko** [comment]
yeah maybe
GLOBAL isnt even a MatchMode actually, so negation can be applied to all others probably
it isnt just as nice that greater/less is already negated but i think we can ignore that fact

also just for ref: https://github.com/primefaces/primeng/blob/2444986ee9e47dc4a502ef0b1eaf2e87d51ad3e7/src/app/components/api/filtermatchmode.ts

**Comment by jesjimher** [comment]
Oops, looks like PrimeNG implements it with `MatchMode`s, not with a method. Perhaps it's wiser doing it the same way in both libraries, then.

**Comment by tandraschko** [comment]
so lets go with new enums like in PrimeNG?

**Comment by Rapster** [comment]
I guess so, I don't know what is "is", "isNot" though. And I don't think we need the date filters.

**Comment by tandraschko** [comment]
yep, we dont need date stuff. less/greater is enough.

Should we rename "range" to "between" like used in SQL?
what about less / greater? should we allow "not greater" or should user go with less?

**Comment by tandraschko** [comment]
```
public enum MatchMode {

    STARTS_WITH("startsWith"),
    NOT_STARTS_WITH("notStartsWith"),
    
    ENDS_WITH("endsWith"),
    NOT_ENDS_WITH("notEndsWith"),
    
    CONTAINS("contains"),
    NOT_CONTAINS("notContains"),

    EXACT("exact"),
    NOT_EXACT("notExact"),

    LESS_THAN("lt"),
    LESS_THAN_EQUALS("lte"),

    GREATER_THAN("gt"),
    GREATER_THAN_EQUALS("gte"),

    EQUALS("equals"),
    NOT_EQUALS("notEquals"),
    
    IN("in"),
    NOT_IN("notIn"),

    BETWEEN("between"),
    NOT_BETWEEN("notBetween"),

    // special mode
    GLOBAL("global");
```

**Comment by Rapster** [comment]
Looks good, maybe it's time to remove GLOBAL. Really don't know what it's used for

**Comment by tandraschko** [comment]
i think its used to idenfity the global filter in a custom LazyDataModel.

**Comment by Rapster** [comment]
Arf...  Let's stick to this issue for now

**Comment by tandraschko** [comment]
@Rapster could you please review?

**Comment by Rapster** [comment]
Looks good
