### ISSUE TITLE
[5.2.11 regression] selectManyButton deselection issue

### ISSUE THREAD

**Issue by smokeybandit** [primefaces/primefaces#771]
In 5.2.11, issue #87 introduced some keyboard accessibility code for various widgets including the selectManyButton.  Since that release (including 5.3 branch, too), when a button is selected, it takes two clicks to deselect it.   This works as expected in 5.2.10.

When trying to deselect a button, the new code for focus/blur events in forms.js for #87 is removing **.ui-state-active** on focus.  Then once the click event fires, it treats the click as a select click since .ui-state-active is not there.  It seems the focus/blur events shouldn't attempt to change the .ui-state-active class or change how the click event checks if a button is selected or not

**Comment by Mrjoui** [comment]
i have the same problem.
I have a selectManyButton in a cellEditor DataTable with cell edit mode. And when i select the manybutton cell to edit, the component has focussed, and loose the ui-state-active and adds ui-state-focus.

I work with PF 6.0

**Comment by tandraschko** [comment]
Works fine in the showcase.
If the issue still persists in the newest version, please create new issue and respect our template.

**Comment by thienquach** [comment]
I have the same problem, is there any solution to overcome this problem?
I'm using PF 5.3
