### ISSUE TITLE
Themes: focussed ui-state-error elements should be bordered in the error color

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7710]
See #7582

@sqores requested to be assigned (I don't have the permission to do that).

**Comment by buunsal** [comment]
Could you please take a look at our other ui library examples? All the same anyway. I can do the same. Is this appropriate @jepsar 

https://primefaces.org/primeng/showcase/#/invalid
https://primefaces.org/primereact/showcase/#/invalid
https://primefaces.org/primevue/showcase/#/invalid

**Comment by jepsar** [comment]
Having only the border as red will certainly help and it would make things consistent. I personally like a red outline as well.

**Comment by buunsal** [comment]
OK, I'm doing the same with other ui libraries.

**Comment by buunsal** [comment]
Could you please test @jepsar

**Comment by jepsar** [comment]
@sqores The border is red, but the outline (which is a `box-shadow` I just noticed) is still blue (Saga). What did you mean with "I'm doing the same with other ui libraries"? I'm going to do the same as with the other ui libraries OR I'm going to do the same with the other ui libraries?

**Comment by buunsal** [comment]
I think there was a misunderstanding. Just wanted to say that I will do the same thing that is done in the other ui libraries.

**Comment by jepsar** [comment]
Okay, then it is working. Still believe a red outline color will be an improvement.

**Comment by jepsar** [comment]
Should I open a new issue for the outline?

**Comment by buunsal** [comment]
It's a design decision. We do not intend to change at the moment. I can only change it if it changes in other ui libraries in the future. If you take a look at our material themes as an example, you will see that they are different. 
https://www.primefaces.org/serenity/invalidstate.xhtml

**Comment by jepsar** [comment]
Alright, I was not sure it was intended. Thanks for the info.

**Comment by jepsar** [comment]
@sqores One thing though, will theme changes (in general) also be applied to upcoming versions of the premium themes? We're using the Diamond theme in our apps for example. You pointed out that Serenity has different styling. See also https://primefaces.org/diamond/invalidstate.xhtml

Should I drop a note on this in the PF Forum?

**Comment by buunsal** [comment]
@jepsar I released a new Diamond version now. Please check your PrimeStore account.
