### ISSUE TITLE
OutputPanel: Update deferred behavior based on Scaffolding

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7712]
**Description**
Thanks to the great work of @jepsar PrimeTek has asked we port the Scaffolding component to core PF.

See: https://www.primefaces.org/showcase-ext/sections/scaffolding/basicUsage.jsf

This will allow the Skeleton component to be useful and provide a true Skeleton experience users have come to expect with other languages.

```xml
<p:scaffolding ready="#{not empty scaffoldingController.data}" id="scaffolding"
                loader="#{scaffoldingController.fetchData(2000)}">
    <f:facet name="loading">
        <p:skeleton width="3rem" height="3rem" shape="circle"/>
    </f:facet>
    <f:facet name="ready">
        <p:avatar label="#{scaffoldingController.data}" size="large" shape="circle" />
    </f:facet>
</p:scaffolding>
```

**Comment by buunsal** [comment]
Thanks for your great work @jepsar

**Comment by jepsar** [comment]
Cool, I can take care of it

**Comment by Rapster** [comment]
Why "scaffolding" btw? 😅

**Comment by jepsar** [comment]
> Why "scaffolding" btw? 😅

@Rapster I think it's appropriate: you scaffold your UI until the data is loaded. I'm open for suggestions. How about `p:texasSwitch`? https://www.youtube.com/watch?v=AtupVg6tiMo 🤣

.. if the current skeleton was called bone, the new component could be skeleton, but that would be too confusing.

**Comment by melloware** [comment]
We are definitely open to names as its quite difficult to name exactly what this is doing...   And since you don't HAVE to use a Skeleton you could literally swap any two UI components on load calling it Scaffolding seemed more generic.

**Comment by jepsar** [comment]
I think @stolp was even planning to swap an entire view 😉

**Comment by Rapster** [comment]
I have no objection with the name, I'm just having a hard time to see the relation between a scaffold and this component 😅

**Comment by jepsar** [comment]
Naming options:

🎉  = loader
❤️ = deferred
👀 = placeholder
😕  = scaffold

**Comment by tandraschko** [comment]
i dont like scaffolding, too

the functionally actually is the same as dynamic=true on dialog or sidebar, but just with a temp content before

maybe its more like a "defferedContent"

**Comment by melloware** [comment]
How about just `<p:deferred>` ??

**Comment by FlipWarthog** [comment]
OR `p:placeholder` ?

**Comment by FlipWarthog** [comment]
I personally love the name `p:scaffolding`, but I can see how it might be obscure/odd

**Comment by melloware** [comment]
Well @tandraschko is right Angular refers to this as `deferredContent` https://stackoverflow.com/questions/42142235/how-to-use-the-deferredcontent-directives-in-angular-dart-components

**Comment by jepsar** [comment]
Lol.. we need a poll tool. I think I like `deferred`

**Comment by melloware** [comment]
> OR `p:placeholder` ?

I am afraid people would confused PlaceHolder with `p:watermark` which updates the "placeholder" attribute on components :)

**Comment by stolp** [comment]
I am pro scaffold/scaffolding as it gives me the association of a building being erected.

I would prefer the shorter form, but I am not a native speaker.

For me deferredContent only tells half the story, as the presence of a temporary replacement is not inferable from the name.

**Comment by melloware** [comment]
OK my votes would be `scaffold` or `deferred` but i am starting to like `scaffold` the best.

**Comment by Rapster** [comment]
If it makes sense to you I'm cool with it :wink:

**Comment by buunsal** [comment]
My vote is for `skeletor` 😅

**Comment by jepsar** [comment]
Lol, skeletor also crossed my mind. Scaffold is probably the best option, as the (deferred) loader is optional.

**Comment by tandraschko** [comment]
TBH i never heard of scaffold in any UI library, also i didnt know the word ;D
can someone check other UI libraries for this?

**Comment by jepsar** [comment]
After reading https://blog.logrocket.com/improve-ux-in-react-apps-by-showing-skeleton-ui/ and https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a `loader` seems appropriate as well and might be easier to get for non native speakers.

**Comment by jepsar** [comment]
Scaffolding is also used as a term to generate code from a model. See for example https://www.toptal.com/angular-js/your-first-angularjs-app-part-2-scaffolding-building-and-testing and https://book.cakephp.org/1.3/en/The-Manual/Developing-with-CakePHP/Scaffolding.html

**Comment by melloware** [comment]
OK so let's go with `loader` since you are right scaffolding might be confusing.

**Comment by tandraschko** [comment]
some thoughts:

1) most frameworks are talking about `async components`, `dynamic components`, `defer rendering`, `deffered loading`
    i think we should choose a similar name, `loader` is a bit to global IMO
2) we should remove the loader, async, global attr and use p:ajax for that, so ppl can even more customize of the request
3) only use one facet, for the un-loaded template markup

A example of my ideas without final name:
```
<p:defferedPanel id="pnl" ready="#{not empty scaffoldingController.data}">
     <p:ajax event="load" listener="#{scaffoldingController.fetchData(2000)}" />           
                
    <f:facet name="template">
        <p:skeleton width="3rem" height="3rem" shape="circle"/>
    </f:facet>

     <p:avatar label="#{scaffoldingController.data}" size="large" shape="circle" />
</p:defferedPanel>
```

**Comment by tandraschko** [comment]
and after thinking more about it, dont we have it already? https://www.primefaces.org/showcase/ui/panel/outputPanel.xhtml?jfwid=f285d

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/outputpanel/outputpanel.js ;)

**Comment by tandraschko** [comment]
i think we just may extend outputpanel to render a template facet before

**Comment by melloware** [comment]
Not a bad idea i should have considered that originally.   @jepsar what do you think?  Then we should update the Skeleton showcase example to show this behavior since everyone asks how to use it!

**Comment by Rapster** [comment]
if I'm not mistaken: one seems to be based on server side condition, the other is client based. Maybe we should have a component that covers both.

**Comment by tandraschko** [comment]
seems so @Rapster 
so we need this 2 enhancements and deffered outputPanel should work perfectly

**Comment by jepsar** [comment]
Sounds as a plan! 👍🏻

**Comment by Rapster** [comment]
From what I can see already, reusing outputPanel code will end up with this bug https://github.com/primefaces-extensions/primefaces-extensions/issues/505. A correction that I made to prevent this https://github.com/primefaces/primefaces/issues/3815 to happen (which I'm guessing p:scaffold have already, hope I'm wrong :D)

**Comment by Rapster** [comment]
Also, after mentionning all these names, it becomes pretty clear `outputPanel` name is far from what the component actually is 😄 We could introduce a new tag name resuing outputPanel and renderer, but at some point it should be renamed properly .

**Comment by melloware** [comment]
@Rapster What is your preferred tag name?   I know OmniFaces had suggested `lazyPanel` but that's not the only thing this is used for right?

**Comment by Rapster** [comment]
Everything but outputPanel (kinda of a pleonasm if you think about it...) I'm cool with lazy/deferred whatever comes after. outputPanel does simple output also (but IMO I'll never use this for that purpose, I'll simply go with a div or panelGroup). 

This component should stick to his purpose: deferring content loading/display (make me think those are two different things but I'll come back to that later). Though, you should be able to disable that functionnality for whatever reason, but again, whenever you use that component is to defer stuff (not anything else)

**Comment by tandraschko** [comment]
defferedPanel (with the options of the current outputPanel) and remove the features from OutputPanel is also ok for me 

but then in general p:outputPanel is quite useless

**Comment by Rapster** [comment]
What is the difference between options and features that you just mention?

**Comment by tandraschko** [comment]
the deffered feature in general and there is a defferentMode or something similar (im on the phone currently, cant check code)

**Comment by christophs78** [comment]
We use p:outputPanel to have a (JSF-) container we can update via Ajax. (For usecases where we use the server-side rendered-attribute to control visibility of ui-elements.)

**Comment by Rapster** [comment]
p:outputPanel does no magic here. You can do the same with a h:panelGroup and maybe with a div using passtrough attrs.

**Comment by melloware** [comment]
@Rapster agreed but outputPanel has been there almost since Day 1 and we have thousands and thousands of instances of it over hundreds of XHTML pages.  Not that it can't be changed but jst pointing out it would make migration to 11.0 a pain to remove it so i am for creating the new component based on it with a different name.  Just my two cents.

**Comment by christophs78** [comment]
Yep. p:outputPanel does no magic. But it is currently used in this way and we should only break it when it's worth breaking it.

**Comment by jepsar** [comment]
Indeed. I would create a new tag and maybe deprecate `p:outputPanel`.

**Comment by Rapster** [comment]
@melloware @christophs78 Yeah I understand, and also sorry about that... If it worth removing it? Well it is quite useless as it is, and buggy so... But as @melloware said, it seems a lot of people are using ouputPanel but misinterpreted the benefit of it (showcase and doc was to blame to be honest). 

So we can't simply remove it, though it worth mentionning in the migration guide/docs that p:outputPanel would be deprecated and scaffold would be the new stuff (if deffered feature is needed, otherwise div/panelGroup is the best way to about it)

**Comment by tandraschko** [comment]
I think the best replacement for outputPanel is 
div jsf:id=
But only for jsf 2.2+

I think its not worth to remove for now and i would implement the new feature in outputPanel
Deffered mode is there since 2013

**Comment by stolp** [comment]
> I think its not worth to remove for now and i would implement the new feature in outputPanel

As long as outputPanel stays 100% backwards compatible I fully agree with that.

If there is a breaking change introduced I would prefer to have a new component introduced.

**Comment by rider87** [comment]
I prefer also to have a new component. 
Users already using the component from PFE.  There should be only a search / replace to PF core afterwards.

**Comment by tandraschko** [comment]
Users are using deffered outputPanel since 2013 ;)

**Comment by rider87** [comment]
yeah, therefore leave outputPanel like it is and create new component p:scaffolding....
Maybe deprecate `p:outputPanel`
If users want to use p:scaffolding (instead p:outputPanel), they have to change it in there project anyway.

**Comment by jepsar** [comment]
@rider87 a new component does not imply that there will be a search and replace migration from PFE. I will incorporate improvements 2 and 3 suggested by @tandraschko in comment https://github.com/primefaces/primefaces/issues/7712#issuecomment-901926450

You can setup you current code so you can migrate more easily, but that's up to you. Have a look at the linked comment to get an idea of what to expect.

**Comment by tandraschko** [comment]
i would suggest 2 PRs for now:
1) add the template facet
2) add the server-side condition (ready attr)

even the load ajax event is already there on outputPanel

later we can talk with PrimeTek, if we should rename the whole component to e.g. "defferedPanel" and/or deprecate the old outputPanel etc.

**Comment by jepsar** [comment]
PR 1: https://github.com/primefaces/primefaces/pull/7728
