### ISSUE TITLE
mask not work well in a tablet, celphone...

### ISSUE THREAD

**Issue by andersonneira** [primefaces/primefaces#772]
I use <p:inputMask into a system.. but when the system is started on a mobile phone or tablet the screen is small the mask does not work, tested in the primefaces showcase , and gave the same problem ..

**Comment by mertsincan** [comment]
I think this is an issue of Android System. Please see; Issue 302 in https://github.com/digitalBush/jquery.maskedinput/issues/

**Comment by andersonneira** [comment]
thank you.. I try with a jelly bean and not work, and I try with a lollipop and works..
