### ISSUE TITLE
MenuButton: Accept button styles

### ISSUE THREAD

**Issue by chovyy** [primefaces/primefaces#7720]
**Description**
Currently you cannot style **MenuButtons** as described here: https://www.primefaces.org/showcase/ui/button/button.xhtml since the `styleClass` attribute will not be applied in conjunction with `.ui-button` but to the outer `span`.

**Describe the solution you would like**
Similar to #7292 a new attribute `buttonStyleClass` should be added, so one can style the generated button.

**Example XHTML**
```xml
<h:form id="frmTest">
    <p:menuButton value="Options" buttonStyleClass="ui-button-outlined ui-button-secondary">
        <p:menuitem value="Save (Non-Ajax)" action="#{menuView.save}" ajax="false" update="messages" icon="pi pi-save"/>
        <p:menuitem value="Update" action="#{menuView.update}" update="messages" icon="pi pi-refresh"/>
    </p:menuButton>
</h:form>
```

**Comment by tandraschko** [comment]
why not just write different selectors?

**Comment by jepsar** [comment]
I see the point. Can be assigned to me.

We should do the same for `SplitButton`.

It seems though that `SplitButton` already has partial button style class support through the parent element though.

**Comment by chovyy** [comment]
> why not just write different selectors?

Does that mean, I will apply the button style directly to the menuButton?

```xml
<p:menuButton value="Options" styleClass="ui-button-outlined ui-button-secondary">...</p:menuButton>
```

Would be even better...

**Comment by jepsar** [comment]
That's already done partly for the `SplitButton`. If it will be made more generic and made to support all of the button classes it'll also work for the `MenuButton`. @sqores should this be solved in the themes?

**Comment by tandraschko** [comment]
hm?


1) either you (if its your own style) or PF themes needs to adjust the selector to e.g.
```
ui-button-secondary button
```

2) or we introduce buttonStyleClass


2 is easier and used alogn other components

**Comment by buunsal** [comment]
@chovyy you can use overlay menu for styleable button. https://www.primefaces.org/showcase/ui/menu/menu.xhtml?jfwid=1a3bd
@tandraschko Option 2 makes sense to me. But I think the span rendered outside is unnecessary. If we remove it, complexity will be reduced and the issue will be solved. We can only render button. Of course, I did not examine it in detail.

**Comment by jepsar** [comment]
The wrapping span cannot be removed as it contains both the button and the menu.

https://github.com/primefaces/primefaces/blob/65de61e60e6218b28ff147f947ed422e1ffd8916/primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonRenderer.java#L66-L69

**Comment by chovyy** [comment]
> @chovyy you can use overlay menu for styleable button. https://www.primefaces.org/showcase/ui/menu/menu.xhtml

Might be an option, but I guess, custom CSS would then be the nicer workaround.

**Comment by jepsar** [comment]
@chovyy I'll submit a PR

**Comment by chovyy** [comment]
Cool, thanks a lot! :+1:

**Comment by jepsar** [comment]
Just checked `SplitButton` which consists of two buttons, which make applying buttons styles on them less straightforward. Outline will work if you would remove a border. So I won't touch that for now.

For `MenuButton` we have another option. We could render the `styleClass` on the button as well, so:

```xhtml
<p:menuButton styleClass="ui-button-outlined ui-button-secondary"/>
```

will render:

```html
<span class="ui-button-outlined ui-button-secondary ..." ...>
  <button class="ui-button-outlined ui-button-secondary ..." ...>...</button>
</span>
```

**Comment by jepsar** [comment]
@sqores please see comment above. Do you prefer using the `styleClass` attribute or should we introduce `buttonStyleClass`?

**Comment by tandraschko** [comment]
i think introducing buttonStyleClass is the only clean thing
reusing it for 2 elements is quite hacky/dirty

**Comment by buunsal** [comment]
@jepsar you can add buttonStyle and buttonStyleClass
