### ISSUE TITLE
DataTable: components can't overflow in editable cells

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7724]
See https://github.com/primefaces-extensions/primefaces-extensions/issues/511

<img width="504" alt="Screenshot 2021-08-20 at 11 58 36" src="https://user-images.githubusercontent.com/7500178/130237860-f924317d-079d-4159-b99c-bb131eb5c1f5.png">

This CSS rule sets overflow to hidden:

https://github.com/primefaces/primefaces/blob/65de61e60e6218b28ff147f947ed422e1ffd8916/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css#L29-L37

Shouldn't it be visible at least when a cell is editable?

https://github.com/primefaces/primefaces/blob/65de61e60e6218b28ff147f947ed422e1ffd8916/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css#L195-L201

**Comment by melloware** [comment]
@jepsar i would submit a PR and then we can assign to PrimeTek to review?

**Comment by jepsar** [comment]
I'm not 100% sure if you want this for every component. But I could create a PR. It would be simply having `overflow: visible;` in the second block above.

**Comment by melloware** [comment]
Yep I would think when editing it seems a reasonable choice.

**Comment by jepsar** [comment]
This causes wide texts to overflow. We can revert this or change to overflow-y. @melloware WDYT?

Do we need a new issue for this, as this was part of RC1?

**Comment by jepsar** [comment]
Hmm.. overflow-y is no good. I'd say revert.

**Comment by tandraschko** [comment]
yeah, i will revert

**Comment by melloware** [comment]
yep submit a PR to revert please. No new ticket just assign it this ticket number and we can re-=open this ticket.

**Comment by jepsar** [comment]
This issue can be reopened so a different fix can be applied

**Comment by jepsar** [comment]
This should fix it properly (only allow to overflow when the cell is being edited). I'll do some tests this evening to be really sure and submit a PR then.

```css
.ui-datatable .ui-datatable-data td.ui-cell-editing {
    overflow: visible;
}
```

**Comment by mertsincan** [comment]
I think this is too risky. If the component in PrimeFaces Extensions has a property like appendTo="body", I suggest you use it. 
In recent years, we have been making overlay panels append to body by default, especially in Prime* JS libraries. Especially with the OverlayEventBus service, we enable such structures to communicate with each other. Exp: Editing + Dropdown panel

**Comment by jepsar** [comment]
Alright, thanks for your reply
