### ISSUE TITLE
Button: dialog refreshes the page after open

### ISSUE THREAD

**Issue by dima-fedotovs** [primefaces/primefaces#7729]
When you open a dialog via PF('dlg').show() - it appears on the screen for a moment and then the page is reloaded. Affected versions (ELITE) 10.0.5 and 10.0.6. **It isn't reproducible with 10.0.4**

The demo project can be found in GitHub - https://github.com/dima-fedotovs/PFDialogReproducer

**Environment:**
 - PF Version: __10.0.5__, __10.0.6__
 - JSF + version: __Mojarra 2.3.14.SP04__
 - App server: __WildFly 23.0.2__ _(no configuration required)_
 - Affected browsers: __ALL__ _(not a browser specific)_

**To Reproduce**
1. Go to 'index.xhtml'
2. Click on the 'Show Dialog' button
4. Dialog appears on the screen for a moment and then the page is reloaded

**Expected behavior**
The page shouldn't be reloaded after the dialog is open.

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
    <title>Hello</title>
</h:head>
<h:body>
    <p:button onclick="PF('dlg').show()" value="Show Dialog"/>

    <p:dialog header="Greeting" widgetVar="dlg">
        <h1>HELLO</h1>
    </p:dialog>
</h:body>
</html>
```

**Example Bean**
No beans are required to reproduce

**Comment by dima-fedotovs** [comment]
After further investigation, I've found that it isn't p:dialog. Seem in PF 10.0.5 the p:button changed its behaviour. Now it is navigating to the same view after click.

**Comment by dima-fedotovs** [comment]
Probably related to #7461

**Comment by melloware** [comment]
I agree @tandraschko this does look related to #7461

**Comment by tandraschko** [comment]
its actually the same with 8.0
if you check the rendered xhtml:
`onclick="PF('dlg').show();window.open('\/primefaces\-test\/index.xhtml','_self')"`

**Comment by tandraschko** [comment]
yeah, its by design
if you check h:button rendering, its the same
so you MUST add "return false" after your statement

**Comment by mertsincan** [comment]
Hi,

In a semantic version such as 10.0.x, this change should not be made. So sorry for the confusion. I'll revert it on PF10.0.8.

I would like to briefly explain the problem. Firstly, you need to examine the view-sources of page in browser to fully understand this complexity.
```test.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
    <title>Hello</title>
</h:head>
<h:body>
    <p:button value="Back" onclick="history.go(-1)" />
</h:body>
</html>
```

**On 10.0.1;**
_DOM_
```
<button onclick="history.go(-1)" role="button" aria-disabled="false" ...><span class="ui-button-text ui-c">Back</span></button>
```
_view-source_
```
<button onclick="history.go(-1)" onclick="history.go(-1)" onclick="history.go(-1);window.open('\/primefaces\-test\/test.xhtml','_self')" ...><span class="ui-button-text ui-c">Back</span></button>
```
- As you can see in view-source, three _onclick_ events are bound to the button. This is completely wrong. Because only the first one will be run in the browser. Please try the example below with the HTML button tag;
https://www.w3schools.com/code/tryit.asp?filename=GUZXAJAQYR0U

**On 10.0.5;**
```
<button onclick="history.go(-1);window.open('\/primefaces\-test\/test.xhtml','_self')" role="button" aria-disabled="false" ...><span class="ui-button-text ui-c">Back</span></button>
```
_view-source_
```
<button onclick="history.go(-1);window.open('\/primefaces\-test\/test.xhtml','_self')" ...><span class="ui-button-text ui-c">Back</span></button>
```
- As seen in the code above, only one onclick event is bound to the button in the view-source.

I hope I was able to explain the difference. if you think there is any problem with this change, please add a comment with a sample project. We can discuss it together as a team. For now, I agree with @tandraschko ;)

As I said, I'll revert the change in #7729 on 10.0.8.

Sorry again!
Best Regards,

**Comment by clarktrip1** [comment]
Mert, I tested your change. I can confirm that it again creates 3 onclick handlers:
<button id="statusForm:j_idt110" name="statusForm:j_idt110" type="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="history.go(-1); return false;"
						onclick="history.go(-1); return false;" onclick="history.go(-1); return false;;window.open('\/maintenance\/views\/office\/import\/hours\/importFromSynerion.jsf','_self')">

While I appreciate you rolling the back to the 10.0.1 functionality, I think the fundamental question not yet addressed is why is there is a window.open(...) being added at all.  Whether it's Mojarra or PF's renderer doing this, that's a bad idea.  The affect is if I want to do something using a PF themed button, it's going to reload the current page for me.  That's adding functionality that we didn't have in the past and seems illogical to have now.

**Comment by tandraschko** [comment]
we just fixed PF to be aligned with the JSF specs again

**Comment by tandraschko** [comment]
you can simple add "return false;", thats a pattern used in JSF and html/js itself since ages
