### ISSUE TITLE
Mobile HeadRenderer doesn't wrap PrimeFaces.settings.projectStage assignment in a script

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#773]
The Mobile HeadRenderer just renders `PrimeFaces.settings.projectStage='Development';` as a text node. Chrome thinks that this belongs to body, and just displays it.

If you use pm:page, then it may not be noticeable right away, since the page would cover it, but sometimes this text causes a horizontal scrollbar.

PrimeFaces 5.2.12.

**Comment by tandraschko** [comment]
Could you please post a example? It's not rendered in the showcase (which is also weird)

**Comment by VsevolodGolovanov** [comment]
> It's not rendered in the showcase (which is also weird)

Probably because the showcase has the production stage configured:

```
if (!projectStage.equals(ProjectStage.Production)) {
    writer.write("PrimeFaces.settings.projectStage='" + projectStage.toString() + "';");
}
```

**Comment by VsevolodGolovanov** [comment]
The reproducer is trivial:

```
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:p="http://primefaces.org/ui">

<f:view encoding="UTF-8" contentType="text/html">
    <h:head>
    </h:head>

    <h:body>
        lala
    </h:body>
</f:view>

</h:html>
```

![projstage](https://cloud.githubusercontent.com/assets/8070317/10427372/de8995f4-70f1-11e5-96cc-0c090899bbfc.png)

**Comment by tandraschko** [comment]
Weird.
