### ISSUE TITLE
Datatable: Selection Update Bug

### ISSUE THREAD

**Issue by mci-daniel** [primefaces/primefaces#7736]
**Describe the defect**
I have a lazy datatable (rowSelectMode="multiple", selectionPageOnly="true") inside a dynamic p:dialog.
I open the dialog with a p:commandButton - update="@widgetVar(dialog)", oncomplete="PF('dialog').show()".
The problem is that the selection of the datatable is not updated correctly (the selectionholder doesn't contain the most current selected rowkeys).

e.g.
- Open the dialog with the table
- Select 3 entries of the table
- Close the dialog
- Remove a selected entry (by clicking some other input component)
- Open the dialog with the table again (including ajax update of the dialog)
- The table still has 3 selected entries, instead of 2. The java list which holds the selection contains the expected 2 elements, but the table still shows the "old" selection.

Am I missing something here? The same workflow worked fine with PF8

**Environment:**
 - PF Version: 10.0
 - JSF + version: Mojarra 2.4.0
 - Affected browsers: ALL

**Comment by tandraschko** [comment]
please provide a forked primefaces-test and try 11.0-SNAPSHOT
we already fixed ~50 DataTable bugs since 10.0

**Comment by mci-daniel** [comment]
Thanks for the quick reply.

I think this issue is a duplicate of https://github.com/primefaces/primefaces/issues/7391
