### ISSUE TITLE
Jitpack master resolves to 6_1

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7739]
https://github.com/primefaces/primefaces/issues/7737

can you check plz @melloware ?

**Comment by melloware** [comment]
Checking....

**Comment by melloware** [comment]
When I look at JitPack Master buld from this morning it built 11.0-SNAPSHOT.

https://jitpack.io/com/github/primefaces/primefaces/master-6_1-ga678c02-6066/build.log

But I do see this error at the bottom so maybe JitPack is having trouble.
```
Found artifact: org.primefaces:primefaces-parent:11.0.0-SNAPSHOT
ERROR: Time-out getting container status
Error building
```

**Comment by tandraschko** [comment]
could it be related to your repo restructure?

**Comment by melloware** [comment]
It could be but it looks like its just running the root pom.xml and building everything correctly.  It should just be checking out Git Master and running.  Let me see if JitPack has any support ticket I can open.

**Comment by Rapster** [comment]
There are instructions regarding multi-module: https://jitpack.io/docs/BUILDING/#multi-module-projects

Not sure if that can help. Also, someone created an issue regarding the error message @melloware, see https://github.com/jitpack/jitpack.io/issues/4494

**Comment by melloware** [comment]
I also submitted a support request using their "Report a Bug" feedback on their home page.

**Comment by jitpack-io** [comment]
Hi,

It seems like there was a timeout as we have a 15 minute limit. Rebuilding the same commit was successful this time:
https://jitpack.io/com/github/primefaces/primefaces/a678c02/build.log

**Comment by tandraschko** [comment]
@jitpack-io i see but https://jitpack.io/com/github/primefaces/primefaces/master-SNAPSHOT/maven-metadata.xml still says 6_1?

**Comment by melloware** [comment]
I sent another support request about this.

**Comment by melloware** [comment]
Team, I have verified while this is bad naming on Jitpack's part the JAR is correct and its been doing this for over a year. See my history...
![image](https://user-images.githubusercontent.com/4399574/131335771-5674502d-a2cb-447b-95a9-a7ff23a2d5fc.png)


The JARS when you crack them open are the proper 11.0-SNAPSHOT. So while it "looks" incorrect the MASTER-SNAPSHOT is resolving correctly.
```xml
<dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>
 ```
