### ISSUE TITLE
partial-response when session expires

### ISSUE THREAD

**Issue by pzoli** [primefaces/primefaces#774]
ViewExpiredException and AjaxExceptionHandler combinated with protected content not work.
Please see forum topic for more details and way near to solution:
http://forum.primefaces.org/viewtopic.php?f=3&t=43470

**Comment by tandraschko** [comment]
Please provide a complete example app. (which runs fine via mvn jetty:run)

**Comment by pzoli** [comment]
Here is where you can found:
https://github.com/pzoli/Homeworks4U
It's run on Wildfly 8.2 - 9.0 and postgresql
JBoss Developer Studio 9 project
(you can build it with "mvn package", deploy with "mvn wildfly:deploy")
I made an installation document.

**Comment by pzoli** [comment]
I switch to client side State Saving Method. I don't know how, sometime appears the dialog box, sometime happens nothing (pager do nothing after ViewExpiredException). This kind of bug most ranking. I need dig in deeper.

**Comment by pzoli** [comment]
I changed to myfaces-2.2.8 on wildfly 9.0.1-Final
set context params:
STATE_SAVING_METHOD=client
PARTIAL_STATE_SAVING=false

Now it seems like working. Please test with this.

**Comment by pzoli** [comment]
please supptort PARTIAL_STATE_SAVING=true
http://forum.primefaces.org/viewtopic.php?f=14&t=41800

**Comment by tandraschko** [comment]
Will close it for now as the example requires postresql and we also fixed something regarding TimelineUpdater in trunk.
If the issue still persists in the newest version, please create new issue and respect our template.
