### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by shersial** [primefaces/primefaces#7758]
**Describe the defect**
BUILD FAILURE

**Reproducer**
Hi there. I've just bought Primefaces Designer but I am not able to start it. Some errors. How can I get help? thanks

**Environment:**
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: C:\Program Files\apache-maven-3.8.2
Java version: 16.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-16.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

C:\_MyWork\primefaces-designer-10.0.0 (2)>echo %JETTY_HOME%
C:\jetty-home-11.0.6

ERROR

[INFO] Scanning for projects...
Downloading from central: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.4.36.v20210114/jetty-maven-plugin-9.4.36.v20210114.pom
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.jetty:jetty-maven-plugin:9.4.36.v20210114: Plugin org.eclipse.jetty:jetty-maven-plugin:9.4.36.v20210114 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.jetty:jetty-maven-plugin:jar:9.4.36.v20210114
Downloading from central: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.maven.plugins/maven-metadata.xml from/to central (https://repo1.maven.org/maven2): transfer failed for https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml, proxy: ProxyInfo{host='websenseproxy.sedd.gov.ae', userName='null', port=8080, type='http', nonProxyHosts='null'}
[WARNING] Could not transfer metadata org.codehaus.mojo/maven-metadata.xml from/to central (https://repo1.maven.org/maven2): transfer failed for https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml, proxy: ProxyInfo{host='websenseproxy.sedd.gov.ae', userName='null', port=8080, type='http', nonProxyHosts='null'}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.516 s
[INFO] Finished at: 2021-08-26T10:11:19+04:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\10016\.m2\repository), central (https://repo1.maven.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
![Screenshot 2021-08-26 092007](https://user-images.githubusercontent.com/4200050/130910304-2a3527a6-e2f6-4275-b742-966354c38941.jpg)

**Comment by tandraschko** [comment]
Please use the Forum
This issue tracker is just for primefaces core / community
