### ISSUE TITLE
TreeTable: scrollable header clone duplicate ids

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#7762]
**Describe the defect**
A scrollable treeTable with custom inputs added via the header facet creates duplicate ids when cloning the header for scrollable body.

**Reproducer**
[primefaces-scrollable-treetable-duplicate-ids.zip](https://github.com/primefaces/primefaces/files/7067223/primefaces-scrollable-treetable-duplicate-ids.zip)
(Targets 10.0.0 instead of master-SNAPSHOT due to #7739.)

**Environment:**
 - PF Version: 6.2.30, 10.0.0
 - JSF + version: ALL
 - Affected browsers: ALL

**To Reproduce**
1. Open the reproducer.
2. See the error message in the browser console (a script detects duplicate ids and logs them).
![image](https://user-images.githubusercontent.com/8070317/131136269-3440dd58-8602-4179-bccc-b926e275c671.png)

**Expected behavior**
Header components cloned with differents ids, or no ids, or not cloned at all. DataTable used to have the same problem, but now seems to not clone such header components at all.

**Example XHTML**
```html
<h:form id="form">
	<p:treeTable id="treetable" value="#{testView.treeRoot}" var="v" scrollable="true">
		<p:column>
			<f:facet name="header">
				Header <p:inputText id="header_input" />
			</f:facet>
			#{v}
		</p:column>
	</p:treeTable>
</h:form>

<script>
	(function() {
		setTimeout(function() {
			var ids = {};
			$('[id]').each(function() {
				var id = this.id;
				if (id &amp;&amp; ids[id]) {
					ids[id].push(this);
					console.error('Duplicate id: ' + id + ' in elements', ids[id]);
				} else {
					ids[id] = [this];
				}
			});
		}, 100);
	})();
</script>
```

**Example Bean**
```java
@Data
@Named
@ViewScoped
public class TestView implements Serializable {
    
	private TreeNode treeRoot = new DefaultTreeNode("Root", null) {
		{
			new DefaultTreeNode("Node 0", this) {
				{
					new DefaultTreeNode("Node 0.0", this);
					new DefaultTreeNode("Node 0.1", this);
				}
			};
			new DefaultTreeNode("Node 1", this);
		}
	};

    public TreeNode getTreeRoot() {
        return treeRoot;
    }

}
```

**Comment by melloware** [comment]
Yep I remember fixing this for Datatable.  We pobably just need to apply the same fix...

**Comment by melloware** [comment]
MonkeyPatch:

```javascript
if (PrimeFaces.widget.TreeTable) {
    PrimeFaces.widget.TreeTable.prototype.cloneHead = function() {
        this.theadClone = this.headerTable.children('thead').clone();
        this.theadClone.find('th').each(function() {
            var header = $(this);
            header.attr('id', header.attr('id') + '_clone');
            header.children().not('.ui-column-title').remove();
            header.children('.ui-column-title').children().remove();
        });
        this.theadClone.removeAttr('id').addClass('ui-treetable-scrollable-theadclone').height(0).prependTo(this.bodyTable);
    }
};
```

**Comment by melloware** [comment]
@VsevolodGolovanov if you don't mind trying that monkeypatch above and letting me know if it resolves your issue. Testing locally it seems to be working properly and removing the duplicate IDs properly.

**Comment by VsevolodGolovanov** [comment]
@melloware, yes, that works.
