### ISSUE TITLE
AutoComplete: duplicate ids with custom content

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#7763]
**Describe the defect**
An autocomplete with custom content renders duplicate ids in query results.

**Reproducer**
[primefaces-autocomplete-custom-content-duplicate-ids.zip](https://github.com/primefaces/primefaces/files/7067446/primefaces-autocomplete-custom-content-duplicate-ids.zip)
(Targets 10.0.0 instead of master-SNAPSHOT due to #7739.)

**Environment:**
 - PF Version: 6.2.30, 10.0.0
 - JSF + version: ALL
 - Affected browsers: ALL

**To Reproduce**
1. Open the reproducer.
2. Type "1" into the field.
3. See the error message in the browser console (a script detects duplicate ids and logs them).
![image](https://user-images.githubusercontent.com/8070317/131140466-472e3e76-e2a0-4da7-a342-6859ed0de106.png)

**Expected behavior**
Client ids should probably include iteration, like with `ui:repeat`: "x:1:y", "x:2:y"...

**Example XHTML**
```html
<h:form id="form">
	<p:autoComplete id="autocomplete" completeMethod="#{testView.complete}"
		var="v" itemLabel="#{v}" itemValue="${v}">
		<p:ajax event="query" oncomplete="checkDuplicateIds()" />
		<p:column>
			<p:graphicImage value="#{resource['folder.png']}" />
			#{v}
		</p:column>
	</p:autoComplete>
</h:form>

<script>
	function checkDuplicateIds() {
		setTimeout(function() {
			var ids = {};
			$('[id]').each(function() {
				var id = this.id;
				if (id &amp;&amp; ids[id]) {
					ids[id].push(this);
					console.error('Duplicate id: ' + id + ' in elements', ids[id]);
				} else {
					ids[id] = [this];
				}
			});
		}, 100);
	}
	checkDuplicateIds();
</script>
```

**Example Bean**
```java
@Data
@Named
@ViewScoped
public class TestView implements Serializable {
    
	public List<String> complete(String query) {
		return Stream.of("qwer", "asdf", "zxcv", "asdfg", "000", "111", "123").filter(e -> e.contains(query)).collect(Collectors.toList());
	}

}
```

**Comment by melloware** [comment]
Hmmm is that the issue or is it that the original content has not been removed from the DOM yet before adding the new items to the panel?

**Comment by VsevolodGolovanov** [comment]
No, after the update is finished each search result ends up with elements with duplicate ids. In this case the graphicImage generated id.

**Comment by melloware** [comment]
yep i see it now. It this block of code...

```java
for (int i = 0; i < ac.getColums().size(); i++) {
            Column column = ac.getColums().get(i);
            if (column.isRendered()) {
                writer.startElement("td", null);
                if (key != null) {
                    writer.writeAttribute("data-item-key", key, null);
                }
                if (column.getStyle() != null) {
                    writer.writeAttribute("style", column.getStyle(), null);
                }
                if (column.getStyleClass() != null) {
                    writer.writeAttribute("class", column.getStyleClass(), null);
                }

                column.encodeAll(context);

                writer.endElement("td");
            }
        }
```

Its just calling EncodeAll.   I am not sure how to fix this so I will leave for @tandraschko or @Rapster to chime in.

**Comment by VsevolodGolovanov** [comment]
Also:
```
<f:facet name="itemtip">
	<h:outputText id="tip" value="#{v} tip" />
</f:facet>
```
Same problem.

**Comment by melloware** [comment]
Closing in favor of this tracking ticket: https://github.com/primefaces/primefaces/issues/8765
