### ISSUE TITLE
DataTable: rowExpansion+rowEditor creates duplicate ids

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#7765]
**Describe the defect**
Using dataTable with rowExpansion and rowEditor creates duplicate ids.

**Reproducer**
[primefaces-datatable-rowexpansion-roweditor-duplicate-ids.zip](https://github.com/primefaces/primefaces/files/7068337/primefaces-datatable-rowexpansion-roweditor-duplicate-ids.zip)
(Targets 10.0.0 instead of master-SNAPSHOT due to #7739.)

**Environment:**
 - PF Version: _6.2.30_, _10.0.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Open the reproducer.
2. Click rowEditor to start editing a row.
3. Finish editing (apply or cancel - doesn't matter).
4. See the error message in the browser console (a script detects duplicate ids and logs them).
![image](https://user-images.githubusercontent.com/8070317/131158979-251e96a7-17a3-4976-b4e4-c625d57ff121.png)
For some reason rowExpansion content is cloned on row edit finish.

**Expected behavior**
No duplicate ids.

**Example XHTML**
```html
<h:form id="form">
	<p:dataTable id="datatable" value="#{[1,2]}" var="row" editable="true" expandedRow="true">
		<p:ajax event="rowEdit" oncomplete="checkDuplicateIds()" />
		<p:ajax event="rowEditCancel" oncomplete="checkDuplicateIds()" />

		<p:column width="80">
			<p:rowToggler />
		</p:column>

		<p:column width="80">
			<p:rowEditor />
		</p:column>

		<p:column>
			#{row} row
		</p:column>

		<p:rowExpansion>
			<h:outputText id="text" value="#{row} details"/>
		</p:rowExpansion>
	</p:dataTable>
</h:form>

<script>
	function checkDuplicateIds() {
		setTimeout(function() {
			var ids = {};
			$('[id]').each(function() {
				var id = this.id;
				if (id &amp;&amp; ids[id]) {
					ids[id].push(this);
					console.error('Duplicate id: ' + id + ' in elements', ids[id]);
				} else {
					ids[id] = [this];
				}
			});
		}, 100);
	}
	checkDuplicateIds();
</script>
```

**Example Bean**
None.

**Comment by melloware** [comment]
I am assuming OrderList has the same issue according to this ticket: https://github.com/primefaces/primefaces/issues/3781 ??

**Comment by melloware** [comment]
Created new tracking issue: https://github.com/primefaces/primefaces/issues/8765

**Comment by melloware** [comment]
Reopening because this causes too many issues with AJAX.  See: https://github.com/primefaces/primefaces/pull/10350

**Comment by melloware** [comment]
I have decided to close this as RowExpansion with any sort of complex component will have issues with duplicate id's.  Its not illegal in HTML just frowned upon for accessibility but if that is the concern then simply do not use Row Expansion.
