### ISSUE TITLE
SelectOneMenu: duplicate ids with custom content

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#7767]
**Describe the defect**
Using selectOneMenu with custom content results in duplicate ids.

**Reproducer**
[primefaces-7767-selectonemenu-custom-content-duplicate-ids.zip](https://github.com/primefaces/primefaces/files/7068606/primefaces-7767-selectonemenu-custom-content-duplicate-ids.zip)
(Targets 10.0.0 instead of master-SNAPSHOT due to #7739.)

**Environment:**
 - PF Version: _6.2.30_, _10.0.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Open the reproducer.
2. See the error message in the browser console (a script detects duplicate ids and logs them).
![image](https://user-images.githubusercontent.com/8070317/131164393-e20ab1f7-a9ff-4add-9c13-e06a6197a0fd.png)

**Expected behavior**
Client ids should probably include iteration, like with ui:repeat: "x:1:y", "x:2:y"...

**Example XHTML**
```html
<h:form id="form">
	<p:selectOneMenu id="menu" var="v">
		<f:selectItems value="#{testView.selectItems}" />
		<p:column>
			<h:outputText id="item_id" value="#{v.id}" />
		</p:column>
		<p:column>
			<h:outputText id="item_name" value="#{v.name}" />
		</p:column>
	</p:selectOneMenu>
</h:form>

<script>
	function checkDuplicateIds() {
		setTimeout(function() {
			var ids = {};
			$('[id]').each(function() {
				var id = this.id;
				if (id &amp;&amp; ids[id]) {
					ids[id].push(this);
					console.error('Duplicate id: ' + id + ' in elements', ids[id]);
				} else {
					ids[id] = [this];
				}
			});
		}, 100);
	}
	checkDuplicateIds();
</script>
```

**Example Bean**
```java
@Data
@Named
@ViewScoped
public class TestView implements Serializable {
    
	private List<TestBean> data = Arrays.asList(new TestBean(0, "Zero"),
			new TestBean(1, "One"), new TestBean(2, "Two"));

	public List<SelectItem> getSelectItems() {
		return data.stream().map(bean -> new SelectItem(bean, bean.getName())).collect(Collectors.toList());
	}

	public static class TestBean {

		private Integer id;
		private String name;

		public TestBean() {
		}

		public TestBean(Integer id, String name) {
			this.id = id;
			this.name = name;
		}

		public Integer getId() {
			return id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		@Override
		public String toString() {
			return getId() + " " + getName();
		}

	}

}
```

**Comment by melloware** [comment]
@VsevolodGolovanov Jitpack is resolving correctly. The name 6.1 looks bad but its the correct JAR it is downloading and using for 11.0-SNAPSHOT.

**Comment by melloware** [comment]
Closing in favor of this tracking ticket: https://github.com/primefaces/primefaces/issues/8765
