### ISSUE TITLE
Component: DataTable - SummaryRow

### ISSUE THREAD

**Issue by stallprobbe** [primefaces/primefaces#7769]
I have upgrade from primeface 5 to primeface 10.0.5, works nice but I have problem with (DataTable)  <p:summaryRow>, it works if I add sortby on a column and click on that, but before it shown the  <p:summaryRow> when I populate the data. I use Freya 2.0.0  as template.

Run the include test, you need to click on a column, then summaryrow shows.

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7070525/primefaces-test-master.zip)

**Comment by christophs78** [comment]
There were major changes in DataTable with 10.0.0: https://primefaces.github.io/primefaces/10_0_0/#/../migrationguide/10_0_0?id=datatable

Probably relevant for your reproducer:
`DataTable#sortBy: expects a single or a collection of SortMeta (default sorting can either be configured through markup or programmatically)`

--> Please try to provide SortMeta for DataTable#sortBy.

**Comment by melloware** [comment]
@christophs78 is right change your datatable to remove `sortBy` and move it to the `p:column` like...

```xml
<p:dataTable var="car" value="#{dtSummaryRowView.cars}">
        <p:column headerText="Id" sortBy="#{car.id}">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Year" sortBy="#{car.year}">
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Brand" sortBy="#{car.brand}" sortPriority="1" sortOrder="asc">
            <h:outputText value="#{car.brand}" />
        </p:column>
        <p:column headerText="Color" sortBy="#{car.color}">
            <h:outputText value="#{car.color}" />
        </p:column>
        <p:summaryRow>
            <p:column colspan="3" style="text-align:right">
                <h:outputText value="Total:" />
            </p:column>
            <p:column>
                <h:outputText value="#{dtSummaryRowView.randomPrice}">
                    <f:convertNumber type="currency" currencySymbol="$" />
                </h:outputText>
            </p:column>
        </p:summaryRow>
    </p:dataTable>
```

**Comment by christophs78** [comment]
SortMeta provided for DataTable#sortBy gives you the option to set some default-sort you may need for your summaryRow-usecase.

**Comment by erickdeoliveiraleal** [comment]
here I need to put groupRow="true" on the column then the summaryRow appear without click on sortBy column, version 12.0.11

**Comment by erickdeoliveiraleal** [comment]
if I put a headerRow like `<p:headerRow field="attr.attr" expandable="true"></p:headerRow>` it also appears.

**Comment by erickdeoliveiraleal** [comment]
I started a discussion https://github.com/orgs/primefaces/discussions/4393
