### ISSUE TITLE
FileUpload: Explain client side API show() and user activation

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7772]
https://www.primefaces.org/showcase/ui/file/upload/basic.xhtml (so PrimeFaces 10.0.0, but I don't think that matters) 

```js
PF('widget_j_idt302_j_idt303').show()
```

Logs this error in the JS console:

```
<input> picker was blocked due to lack of user activation.
```

Firefox version: 91.0.2

No longer works with Chrome (it used to). Chrome reports:

```
File chooser dialog can only be shown with a user activation.
```

**Comment by jepsar** [comment]
https://stackoverflow.com/questions/210643/in-javascript-can-i-make-a-click-event-fire-programmatically-for-a-file-input

**Comment by melloware** [comment]
Hmmm have you tried any of these tricks?

**Comment by jepsar** [comment]
Tried some briefly. Seems like a won't fix (documentation mention) so far.

**Comment by jepsar** [comment]
I'll submit a PR with documentation changes.

**Comment by jepsar** [comment]
The only workaround I've seen is hijacking a mouse move event and use that to trigger a click. But that's too ugly in my book and it may fail at a later moment.

**Comment by melloware** [comment]
Perfect assigned to you,

**Comment by jepsar** [comment]
It no longer is browser specific, it also does not work with Chrome. So it will probably fail with all browsers (soon). If no solution can be found, I think we should deprecate / remove `show()`.

**Comment by melloware** [comment]
should we not deprecate it should we remove it entirely @tandraschko ?

**Comment by tandraschko** [comment]
If it doesnt work anymore -> remove

**Comment by jepsar** [comment]
@melloware can you please fix the labels?

**Comment by melloware** [comment]
Fixed.

**Comment by Rapster** [comment]
It does work for me, at least with latest chrome 93.0.4577.63 and Edge 92.0.902.84. I don't see those error message on console either

**Comment by jepsar** [comment]
Wait, what!? Now it is working again in Chrome. I checked my version, and it prompted to update. I'm on 93.0.4577.63 now and it's working again.

Someone on StackOverflow was also complaining it was not working for him with Chrome. So the least we can say it is not very reliable.

What to do here? Restore and warn to use at own risk?

**Comment by melloware** [comment]
Yes restore and use and at own risk.

**Comment by jepsar** [comment]
@melloware can you revert the PR?

**Comment by melloware** [comment]
sure

**Comment by melloware** [comment]
Reverted

**Comment by Rapster** [comment]
All I could find was this: https://bugzilla.mozilla.org/show_bug.cgi?id=1678389

Related to a popup blocker?

**Comment by melloware** [comment]
I added the browser specific label again since this only affects Firefox and Opera right now.
