### ISSUE TITLE
AccordionPanel: strange/unexpected data model update behavior

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#7777]
**Describe the defect**
Submitting a form containing an `AccordionPanel` with dynamic `Tab`s results in strange/unexpected data model update behavior in that only the last `Tab`s elements setters are invoked.

**Reproducer**
https://github.com/irieill/primefaces-test

**To Reproduce**
Observe the differences in console output while reproducing.

1. Click on 'Save' (no setters)
2. Click on 'Group 1'
3. Click on 'Save' (no setters)
4. Click on 'Group 2'
5. Click on 'Save' (some setters)
6. Click on 'Group 2'
7. Click on 'Save' (some setters)
8. Click on 'Save' (no setters)

**Expected behavior**
Consistent data model update behavior, e.g. update all or nothing.

**Comment by irieill** [comment]
Changing `multiple` does not matter. Setting `dynamic=false` makes the issue even more obvious, regardless if some `Tab` is activated.

**Comment by melloware** [comment]
Looks like it's releated to you using "ui:repeat" ??   Seems like lots of issues in past with TabView and Accordion and ui:repeat.

See: https://github.com/primefaces/primefaces/issues/523
See: https://github.com/primefaces/primefaces/issues/998
See: https://github.com/primefaces/primefaces/issues/720

What happens if you just put straight text boxes inside accordion without the `ui:repeat` i wonder if it works.

**Comment by irieill** [comment]
Not using `ui:repeat` but straight text boxes works! Thank you for pointing me in the right direction. Did not see the relation to these issues. Unfortunately thats not an option for my real usecase. But replacing with `p:repeat` also works. That is perfectly fine. [As stated in the docs](https://primefaces.github.io/primefaces/10_0_0/#/components/repeat)
> `p:repeat` is a fork of the Mojarra `ui:repeat` to provide/backport important bugfixes for users, which must stay on older Mojarra versions. If you don't have problems with `ui:repeat`, please dont use `p:repeat`.

What is the reason not using p:repeat as general replacement in PF based projects?

**Comment by tandraschko** [comment]
Because its a hack as the mojarra impl of ui:repeat isnt well enough designed. P:repeat should not exist and we can hopefully remove it in the future.
I cant remember if they fixxed it, maybe try the newest version.

**Comment by tandraschko** [comment]
@melloware @christophs78 could we add some unittests for this issues?

**Comment by melloware** [comment]
I believe Mojarra has fixed most of the issues for ui:repeat and I believe this does not affect MyFaces correct?  

@irieill What version of Mojarra are you using?

**Comment by melloware** [comment]
OK update it looks like Mojarra ui:repeat still has issues.

`mvn clean jetty:run -Pmojarra22` = broken
`mvn clean jetty:run -Pmojarra23` = broken
`mvn clean jetty:run -Pmyfaces22` = WORKS!
`mvn clean jetty:run -Pmyfaces23` = WORKS!

So it sounds like we need to roll more changes into Mojarra UI:repeat.

**Comment by irieill** [comment]
@melloware I am running WildFly 22.0.1 that ships with Mojarra 2.3.14.SP02.

**Comment by melloware** [comment]
yeah even with Mojarra 2.3.16 its still an issue . So Mojarra still has bugs in repeat.

**Comment by melloware** [comment]
OK comparing Mojarra to PrimeFaces p:repeat it looks like the only diffrence now after all these years is this...

PrimeFaces:
```java
private boolean isNestedInIterator() {
        UIComponent parent = this;
        while (null != (parent = parent.getParent())) {
            if (parent instanceof javax.faces.component.UIData || parent.getClass().getName().endsWith("UIRepeat")
                    || (parent instanceof UITabPanel && ((UITabPanel) parent).isRepeating())) {
                return true;
            }
        }
        return false;
    }
```

Mojarra:
```java
 private boolean isNestedInIterator() {
        UIComponent parent = this.getParent();
        while (parent != null) {
            if (parent instanceof UIData || parent instanceof UIRepeat) {
                return true;
            }
            parent = parent.getParent();
        }
        return false;
    }
```

PrimeFaces has a custom had for `UITabPanel` and UITabPanel states this...

> /**
>  * UITabPanel is a specialized version of UIRepeat focusing on components that repeat tabs like tabView and accordionPanel.
>  * Most of the code is copied from MyFaces.
>  */

**Comment by tandraschko** [comment]
Yeah
Myfaces algorithm works fine without this check

**Comment by melloware** [comment]
I was looking at MyFaces UiRepeat and its completely different.  I can't tell how it determines if its nested or not.  Based on DataModel?

**Comment by tandraschko** [comment]
Its a different algorithm which doesnt need a "Check if nested in another repeat"

**Comment by melloware** [comment]
I opened a Mojarra ticket: https://github.com/eclipse-ee4j/mojarra/issues/4957
