### ISSUE TITLE
DataTable: Scroll Height attribute add 'px' when using 'vh' value

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#7778]
**Describe the defect**
Use scrollable height feature on Datatable breaks CSS when using the 'vh' to have the scroll generated based on viewport. It had 'px' after 'vh'. Example: I use scrollHeight="50vh", It results in "max-height: 50vhpx". 
![datatable_vh](https://user-images.githubusercontent.com/26894018/131638453-f850d563-25f7-4218-8d32-16aa32e02c21.PNG)

**Reproducer**
[primefaces-datatable-vh.zip](https://github.com/primefaces/primefaces/files/7089532/primefaces-datatable-vh.zip)

**Environment:**
 - PF Version: _10.0_ and _11.0.0-SNAPSHOT
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**Expected behavior**
Don't add 'px' to 'vh' value.

**Example XHTML**
```html
<h:form id="frmTest">
  <p:dataTable id="dtTest"        	
        value="#{testView.ids}"
        var="id"
        scrollable="true" 
        scrollHeight="50vh">
        <p:column headerText="Id">
            #{id}
        </p:column>
    </p:dataTable>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private static final long serialVersionUID = 1L;
	
    private List<Integer> ids;
    
    @PostConstruct  
    public void init() {
    	ids = new ArrayList<>();
    	
    	for(int i = 0 ; i < 50 ; i++) {
    	    ids.add(Integer.valueOf(i));
    	}
    }
    
    // GETTERs + SETTERs
    public List<Integer> getIds() {
	return ids;
    }
}
```

I think this is an issue because an enhancement has already be done for TreeTable component : #3406

**Comment by melloware** [comment]
Fixed with my PR. Thanks for the reproducer!
![image](https://user-images.githubusercontent.com/4399574/131666698-53ac286a-a276-41a1-ab96-3b030788e495.png)
