### ISSUE TITLE
PanelGrid: Exception when ui:repeat is used to populate rows

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#7780]
**Describe the defect**
In a p:panelGrid when ui:repeat is used to populate all the rows, Primefaces throws an exception:

javax.faces.FacesException: PanelGrid without a 'columns' attribute expects at least one <p:row> element.

**Reproducer**
n/a

**Environment:**
 - PF Version: _10.0.6_
 - Affected browsers: _ALL_

**To Reproduce**
1. Try to load page

**Expected behavior**
The panelGrid should appear populated from the ui:repeat and no exception should be thrown.

Related to #6829, this issue can be easily fixed by adding <p:row rendered="false" />, but coming from PF 7, we were surprised on a few pages by this. (original blame goes to #6563 it looks like, but I understand why this was done)

I completely understand if this is something you didn't want to support, just something to consider. The PanelGridRenderer.encodeStaticBody() method is very specific about looking for Row instances only.

**Example XHTML**
```
        <h:form id="frmTest">
            <p:panelGrid>
            	<ui:repeat
            		value="#{testController.rows}"
            		var="row">
            		<p:row>
            			<p:column>
            				#{row}
            			</p:column>
            		</p:row>
            	</ui:repeat>
            </p:panelGrid>
        </h:form>
```

**Example Bean**
```
@Named
@ViewScoped
public class TestController implements Serializable {
	private static final long serialVersionUID = 1L;
	
	public List<String> getRows() {
		return List.of("a", "b", "c");
	}
}
```

**Comment by Rapster** [comment]
Please post the full stacktrace. But from what I can see, `<ui:repeat />` is not eligible as children of `<p:panelGrid />`, you can workaround it using `<c:foreach />` which is executed at build time (see https://stackoverflow.com/a/3343681/4605161 for more details). Or if PanelGrid had a `var` attribute, that would be even better?

**Comment by melloware** [comment]
I definitely understand this use case.  I think if there is a UIRepeat we should just not throw the error about missing Rows.

**Comment by melloware** [comment]
Reproducer:
[pf-7780.zip](https://github.com/primefaces/primefaces/files/7098442/pf-7780.zip)

**Comment by Rapster** [comment]
I understand it too. Ideally, using a var attr would be more straightforward or am I missing something?

**Comment by melloware** [comment]
@Rapster PanelGrid has 3 rendering modes with flex, grid, table, etc and introducing `UIData` or whatever it takes to make it a `var` with repeating seems like a much bigger change no?  This is simply asking for it to put back pre 10.0 behavior and not blow up if there is a UIRepeat in it which is reasonable. We got burned on one my projcets with this error.

We can always do a folow on PR to add `var` but I was planning on going for the simple right now before 11.0 is released.

**Comment by Rapster** [comment]
Agreed 100% on fixing this issue with a simple fix (my devs usually go that route but as I was facing that same issue, I realized it'd be more clean to simply have a var attr, specially depending the JSF version and impl it doesn't always work...). I don't think you would need UIData since you don't need to save state of each row.
