### ISSUE TITLE
TriStateCheckbox: Add readonly attribute

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#7781]
**Description**
The `<p:triStateCheckbox>` is missing a `readonly` attribute that allows to render the checkbox in a non-disabled fashion, still maintaining it read-only.
It's not even possible to simulate such a behaviour with something like `onclick="return false"` because this component is also missing the `onclick` attribute.

**Describe the solution you would like**
Adding the ability to set `<p:triStateCheckbox readonly="true" />` to make the tri state checkbox look enabled but readonly. This is also useful if you want to submit its value in a form although not letting the user change it.

It seems like this was implemented in primeng: https://github.com/primefaces/primeng/issues/2999

**Comment by Rapster** [comment]
Feel free to provide a PR

**Comment by melloware** [comment]
I followed what PrimeNG was doing.
