### ISSUE TITLE
Themes: Nova

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#7789]
All three Nova themes look the same, even on Primefaces Demo page. I think this wasn't the case before, they were different.

![Screenshot 2021-09-03 at 08-58-05 PrimeFaces Showcase](https://user-images.githubusercontent.com/1133953/131963906-9e74164b-fa46-4c78-9879-6416bcedce43.png)

![Screenshot 2021-09-03 at 08-58-41 PrimeFaces Showcase](https://user-images.githubusercontent.com/1133953/131963915-09ba39cc-576b-4900-8d48-220ac20c67e3.png)

![Screenshot 2021-09-03 at 08-58-53 PrimeFaces Showcase](https://user-images.githubusercontent.com/1133953/131963934-a96c1144-0aac-4366-bb7c-1fa0a8027cc7.png)

**Comment by melloware** [comment]
Its definitely changing the theme you can see it in the CSS inspector.  I think the issue is these themes are very subtly different but its definitely changing the Nova themes.

**Comment by melloware** [comment]
Assigning to @sqores you are right its that these themes are too close together. Something was messed up when converting to PrimeOne CSS.

**Comment by buunsal** [comment]
There are only color differences between nova themes. These color differences are in the main colors, highlight colors and container header colors. Please check another than inputtext demos. For example: https://www.primefaces.org/showcase/ui/panel/tabView.xhtml?jfwid=1ebce
