### ISSUE TITLE
Footer moves down with Horizontal Scrolling and Selection

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#78]
In Internet Explorer 9 (IE9), with a DataTable if we enable Row Selection (single or multiple) and we enable scrollable with a scrollWidth small enough to cause horizontal scrollbar, the footer of the DataTable moves down the page whenever we mouseover the data rows.  The more you move the mouse on mouseover, the more it moves down.  Mouse movement can be either side-to-side or up-and-down.  Clicking on an item in the list will reset the footer back to normal.

This is reproducible by taking the PrimeFaces ShowCase application and modifying either ui/datatableRowSelectionSingle.xhtml or ui/datatableRowSelectionMultiple.xhtml by adding the following attributes to the <p:dataTable> tag:

```
scrollable="true" scrollWidth="250"
```

Note that this appears to only occur in IE9.  IE8 (or IE8 compatibility mode) and IE10 do not exhibit this behavior.

**Comment by nileshk** [comment]
This appears to have been fixed.  I tried this with the 5.2 Showcase app and it was not a problem with IE9 on Win7.  It's quite possible it was fixed long ago; I haven't tested for this in quite a while.
