### ISSUE TITLE
minify themes please

### ISSUE THREAD

**Issue by banifou** [primefaces/primefaces#780]
hey guys, 
I'm using Primefaces 5.2.12 and Omnifaces to combine resources in production. Pagespeed was complaining about bigger size of CSS resources and I realized that theme.css (in my case aristo) and primefaces.css (jQuery UI CSS) are not minified. In fact, I minified these files with YUI compressor and the size difference is about 4.4 KB and 4.7 KB which is NOT negligible.

**Comment by tandraschko** [comment]
Don't know if 5.2.12 was really not minified but 5.1.13 is. Don't know if you use an unofficial release.

**Comment by banifou** [comment]
I always used official releases since 2,5 years. I checked 5.1.13, same problem! the CSS file Aristo contains to many commented line/text, minifying it with YUI reduces it by 4.7 KB. Why are you kipping comments in these files? 
And how can I override them? 
Thanks
