### ISSUE TITLE
OverlayPanel: should not show from SplitButton menu click

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#7806]
**Describe the defect**
When attaching an overlayPanel to a splitButton, the panel is shown not only when the button is clicked, but also when the menu is clicked, causing the panel to lay on top of the menu. I think the overlayPanel should only be shown when clicking the button proper, not the menu.

I understand if you believe this to be expected functionality, just wanted to raise something I saw when updating our applications.

**Environment:**
 - PF Version: _10.0.6_

**To Reproduce**
1. Click on left side of split button
2. Click on right/menu side of split button
3. See how overlay panel lays on top of menu

**Expected behavior**
The overlayPanel should only show when the left side of the splitButton is clicked.

**Example XHTML**
```
<h:form>
	<p:splitButton
		id="split"
		value="Create Overlay">
		<p:menuitem value="Here's the Split Menu." />
		<p:menuitem value="Here's another menu item." />
	</p:splitButton>
	<p:overlayPanel for="split">
		Here's the Overlay Panel.
	</p:overlayPanel>
</h:form>
```
![overlay](https://user-images.githubusercontent.com/12001281/132760913-7d4e43be-b525-4426-a690-74ecc4957328.PNG)

**Comment by melloware** [comment]
I am not sure about this one. When you say `for="split"` its assigning the `onclick` event to the whole Splitbutton wrapper DIV.  It has no idea its a SplitButton or that it has two internal buttons.  Unless we write some custom code specificall in OverlayPanel for SplitButton?

Right now its just finding the target element and binding your events for overlaypanel to it.

```javascript
this.target = PrimeFaces.expressions.SearchExpressionFacade.resolveComponentsAsSelector(this.cfg.target);
this.bindTargetEvents();
```

Its just a DOM element at that point not any specific component.

**Comment by tandraschko** [comment]
IMO we should not add custom Splitbutton code, 'for' with PFS is the right way

**Comment by firsthour** [comment]
How would you use PFS in this instance?

**Comment by tandraschko** [comment]
Just like a jquery selector
Check it via browser debugger tools

**Comment by melloware** [comment]
@firsthour going to close this ticket  Post back once you figured out the right selector for just the main button.
