### ISSUE TITLE
Upgrade to FontAwesome 4.5

### ISSUE THREAD

**Issue by mbeedub** [primefaces/primefaces#781]
Would it be possible to upgrade to FontAwesome 4.4 in an upcoming release?  There are some great new icons in 4.4.

**Comment by djmj** [comment]
Have a look at omnifaces CDNResourceHandler, with that you dont need to rely on primefaces included resources and uses always most recent font-awesome icons.

**Comment by diegoarantes** [comment]
Update Now to 4.5

**Comment by diegoarantes** [comment]
It would be interesting to Showcase, separate FontAwesome for categories. Equal on the official website, so easy to find icons .
![capturar222](https://cloud.githubusercontent.com/assets/5193643/11809458/33694ad0-a30e-11e5-888d-f0ea80527374.PNG)
