### ISSUE TITLE
Core: Jakarta EE10

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7813]
We already shade PrimeFaces for Jakarta EE and provide it via classifier=jakarta.

We should do following additonal work:

- [x] Add a (maven-)profile to run showcase on Jakarta EE 9/10 (with Mojarra 3/4 and MyFaces 3/4)
We already hava a jakarta-branch for primefaces-test. Which uses Jetty 11.x.
- [x] Run integration-test also against Jakarta EE 9/10 (with Mojarra 3/4 and MyFaces 3/4)
There´s currently (2021-09-12) no embedded TomEE available for Jakarta EE 9. Maybe we should try to use Jetty for integration-test. May be a bit more work.
- [ ] JSF 4.0 will no longer use 'type="text/JavaScript"' if HTML5 Doctype is recognized. Therefore in the PF code base anywhere type is being used we should detect 4.0 and conditionally print it out or not. (https://github.com/primefaces/primefaces/issues/8472)

**Comment by melloware** [comment]
I totally agree this would be great.

**Comment by melloware** [comment]
I thought we had to make a branch for Jakarta because there are so many web.xml, faces-config.xml and other changes for it to work with Jetty 11?

**Comment by christophs78** [comment]
> I thought we had to make a branch for Jakarta because there are so many web.xml, faces-config.xml and other changes for it to work with Jetty 11?

You are right. This worked for primefaces-test, but probably not viable solution for our main PrimeFaces-project.

**Comment by tandraschko** [comment]
I think we need 3 modules for PF core in future:
primefaces-core (js, CSS and so on)
primefaces-javax
primefaces-jakarta

I dont think we can shade forever
And some day we will merge back and remove javax

**Comment by melloware** [comment]
You might be right @tandraschko but it will mean fixing bugs in two places every time for a while but maybe we should do thi once JSF 4.0 goes final?

**Comment by tandraschko** [comment]
Sure
We shouldnt do anything before ee 10.0 anyway

**Comment by GedMarc** [comment]
The current patch works (for me) - 
I'm also waiting for the next Jakarta release

**Comment by tandraschko** [comment]
EE9 is the same as EE8, just different namespace
So we dont need Integration tests for it

**Comment by tandraschko** [comment]
lets postpone this ticket to EE10?

**Comment by christophs78** [comment]
Yep. Nothing we need to work on immediately.
But we should come back later this year.

**Comment by tandraschko** [comment]
all right

i think in general it would be great to make a big bang to EE10 but i think we will still need to support javax for some releases
even quarkus still uses javax

**Comment by christophs78** [comment]
Spring 6 - comming end of 2022 requires Java 17 and Jakarta EE 9 as Baseline.
But they will still support Spring 5 for some time even after releasing Spring 6.

IMO end of 2022 is the earliest point in time when we may think about dropping javax-support. Maybe even later due to JSF / PrimeFaces - legacy. Maybe we should talk to @arjantijms what they plan for Core-JSF.

**Comment by tandraschko** [comment]
from my expierience, we cant remove javax completely the next 2+ years
many users cant upgrade the server environments but can easily deliver a new PF in the WAR

maybe we can talk with PrimeTek and agree to something like:
- still support javax 1-2 yearw after all major AS released a EE10 server
- then completely drop javax and therefore push elite releases, which still support javax. This would also push elite income for PrimeTek

**Comment by arjantijms** [comment]
> EE9 is the same as EE8, just different namespace
> So we dont need Integration tests for it

EE 9 is indeed that and not really aimed at end-users so much (since it brings little value over EE 8 to them). However, the intend of EE 9 is so that library projects and tools can start running their test against it in preparation for when EE 10 does role around.

**Comment by melloware** [comment]
I am going to mark this as done for now as @tandraschko has added Jakarta integration tests and we are running against Mojarra and MyFaces4.
