### ISSUE TITLE
Rating: Keyboard Support

### ISSUE THREAD

**Issue by weiprd** [primefaces/primefaces#7818]
**Describe the defect**
The rating component does not get the focus. So it can not be operated by keyboard and does not fulfill the WCAG 2.1 success criteria [2.1.1](https://www.w3.org/TR/WCAG21/#keyboard).

**Environment:**
 - PF Version: 10.0.0
 - Affected browsers: Chrome, Firefox, Edge

**To Reproduce**
1. Go to https://www.primefaces.org/showcase/ui/input/rating.xhtml?jfwid=55438
2. Navigate through the site using the tab key
3. Rating stars are skipped

**Expected behavior**
I would expect the rating stars to get the focus and that the selection can be made using the arrow keys.

**Comment by jepsar** [comment]
I'll have a look at this.

**Comment by jepsar** [comment]
@melloware are you sure this should go to 11?
