### ISSUE TITLE
AjaxBehaviorListenerImpl#processAjaxBehavior: handle PropertyNotFoundException like MethodNotFoundException

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#7819]
Complicated issue together wie Composite Components.

Mojarra "converts" MethodNotFoundException into PropertyNotFoundException with following code.
https://github.com/eclipse-ee4j/mojarra/blob/2.3.14-RELEASE/impl/src/main/java/com/sun/faces/facelets/el/ContextualCompositeMethodExpression.java#L176

PropertyNotFoundException ist not handeled by https://github.com/primefaces/primefaces/blob/2e79cbc628fa98885cad4688813fc7e82f6f3a97/primefaces/src/main/java/org/primefaces/behavior/ajax/AjaxBehaviorListenerImpl.java#L73
So PF-Fallback-code does not work.

IMO we also should catch PropertyNotFoundException and handle it like MethodNotFoundException.

There had been a similar issue in the past: https://github.com/primefaces/primefaces/issues/1375
This was adressed in a similar way.

**Comment by tandraschko** [comment]
Can you please also check MF?

**Comment by christophs78** [comment]
MyFaces implements this aspects in a different way.

We ran into this issue with an existing application because OpenLiberty made some EL-checks more restrictive for 21.0.0.8 with following https://github.com/OpenLiberty/open-liberty/commit/33341639a0b4d62826170a035dc1dcdcb7a8f55c

This OpenLiberty - modification is essentially what Apache did for Tomcat 9.0.3 back in 2017 with following commit: https://github.com/apache/tomcat/commit/b7ce5679b9e6a073dadbc31e6ecde12ad1e0ede8#diff-47ceb829581fe10be2b13fed4602fdb7b4ce2e46f41cde8d984b87894eb080d2
