### ISSUE TITLE
DataView: add sorting support

### ISSUE THREAD

**Issue by dadadom** [primefaces/primefaces#782]
It would be great if the datagrid supported reordering like the datatable.

I could imagine it to behave like the jQuery UI sortable in grid mode: http://jqueryui.com/sortable/#display-grid

**Comment by melloware** [comment]
DataGrid has been marked deprecated as of PF10.0 and will be most likely removed in PF 11.0 it is recommend to use DataView instead.  So I am updating this ticket to say DataView.

**Comment by melloware** [comment]
DataView does have resorting https://www.primefaces.org/showcase/ui/dnd/dataView.xhtml?jfwid=b083a
