### ISSUE TITLE
Inputs: WCAG compliance

### ISSUE THREAD

**Issue by weiprd** [primefaces/primefaces#7821]
**Describe the defect**
Diamond showcase 'input' does nut fulfil the WCAG accessibility criterion [4.1.1](https://www.w3.org/WAI/WCAG21/Understanding/parsing.html) as it renders syntactically incorrect HTML code. There are 3 errors that element div is not allowed as child of element span in this context.
![Input_HTML-Validierung](https://user-images.githubusercontent.com/77721887/133379157-3edb542e-9fbe-4e86-b690-7ef2b5c9a840.png)

**Reproducer**
1. Open showcase [input](https://www.primefaces.org/diamond/input.xhtml) of the Diamond theme 
2. Use bookmarklet "Check serialized DOM of current page" from https://validator.w3.org/nu/about.html#extras to run Nu Html
Checker on the showcase.
3. Drag and drop bookmarklet "Check for WCAG 2.0 parsing compliance" from the same page to your browser's bookmark
toolbar and execute it on the website of Nu Html Checker which you opened in Step 2. This bookmarklet will filter the results
of Nu Html Checker so that only WCAG relevant results remain.
4. After running both bookmarklets, if the Nu Html Checker still shows error messages, the syntax of the checked HTML code is
not correct.

**Environment:**
 - PF Version: 10.0.0

**Expected behavior**
To fulfil the accessibility criterion Nu Html Checker should show no error messages after checking the tree's HTML code.

**Comment by melloware** [comment]
Please don't use Diamond Theme.  Please only use PrimeFaces Showcase.

**Comment by melloware** [comment]
Invalid.  That Diamond Showcase this is the issue...
![image](https://user-images.githubusercontent.com/4399574/133804873-c275862b-35cb-4f2e-bc2b-31c754d4547c.png)

Its because that SHowcase is using `<span>` for InputGroup so not a PF core issue simply a showcase issue.

**Comment by melloware** [comment]
I have fixed the showcase to use DIV not SPAN and that solves the issue
