### ISSUE TITLE
Menu : WCAG compliance

### ISSUE THREAD

**Issue by weiprd** [primefaces/primefaces#7822]
**Describe the defect**
Diamond showcase 'menu' does nut fulfil the WCAG accessibility criterion [4.1.1](https://www.w3.org/WAI/WCAG21/Understanding/parsing.html) as it renders syntactically incorrect HTML code. There are 8 errors that element table is not allowed as child of element ul in this context.

![Menu_HTML-Validierung](https://user-images.githubusercontent.com/77721887/133389285-11a885d3-5b5d-40fb-8eeb-e8167c6472b9.png)

**Environment:**
 - PF Version: 10.0.0

**To Reproduce**
1. Open showcase [menu](https://www.primefaces.org/diamond/menu.xhtml) of the Diamond theme
2. Use bookmarklet "Check serialized DOM of current page" from https://validator.w3.org/nu/about.html#extras to run Nu Html
Checker on the showcase.
3. Drag and drop bookmarklet "Check for WCAG 2.0 parsing compliance" from the same page to your browser's bookmark
toolbar and execute it on the website of Nu Html Checker which you opened in Step 2. This bookmarklet will filter the results
of Nu Html Checker so that only WCAG relevant results remain.
4. After running both bookmarklets, if the Nu Html Checker still shows error messages, the syntax of the checked HTML code is
not correct.

**Expected behavior**
To fulfill the accessibility criterion Nu Html Checker should show no error messages after checking the tree's HTML code.

**Comment by melloware** [comment]
Please do not use the Diamond Theme.  The theme has nothing to do with your issues please use the PrimeFaces Showcase.

**Comment by jepsar** [comment]
I only see tables being rendered for the MegaMenu on that page.

**Comment by melloware** [comment]
@jepsar I was inclined to close this ticket because there is so little information.  And it uses the Diamond Theme showcase and not the main Showcase which removes all custom components of Diamond.

**Comment by melloware** [comment]
There is just too much going on in that Diamond Menu page.
