### ISSUE TITLE
Inputs: Hidden inputs should never render readonly attribute

### ISSUE THREAD

**Issue by kunzen16A** [primefaces/primefaces#7827]
**Description:**
The Diamond showcase 'List' does not fulfill the WCAG accessibility criterion 4.1.1 as it renders syntactically incorrect HTML code. There are 24 errors that the attributes readonly and aria-readonly are not allowed on element input at this point.

![image](https://user-images.githubusercontent.com/77410849/133409760-50bff34f-b417-47a0-bfb5-c9b691228c7b.png)

**Environment:**
PF Version: 10.0.0

**Reproduction:**
Use the following steps to reproduce the behavior:

- Open the showcase Tabel of the Diamond theme
- Use the bookmarklet "Check serialized DOM of current page" from https://validator.w3.org/nu/about.html#extras to run Nu
    Html Checker on the showcase
-  Subsequently use the bookmarklet "Check for WCAG 2.0 parsing compliance" from the page named before and execute it on 
    the website of Nu Html Checker which you allready opened to filter the results
-  Check the errors the Nu Html Checker still shows after running both bookmarklets

**Expected behavior:**
To fulfill the accessibility criterion Nu Html Checker should show no error messages after checking the list's HTML code.

- [x] ColorPicker
- [x] MultiSelectListBox
- [x] Rating
- [x] Signature

**Comment by tandraschko** [comment]
JFYI
Please check those issues in the normal Showcase, too for a valid issue report
The issue tracker is only for primefaces core, not any template

**Comment by melloware** [comment]
Thanks for reporting I fixed it for the 4 components that had this issue...

-  ColorPicker
-  MultiSelectListBox
-  Rating
-  Signature
