### ISSUE TITLE
TreeTable:  Selection behaviour for Checkbox unexpected

### ISSUE THREAD

**Issue by neXus1987** [primefaces/primefaces#7828]
**Describe the defect**
Issue 1
when you select the first node with checkboxes in a TableTree, in the selectionvalue only this node arrives, after expand this node also the other values and also the values from not expanded nodes will be shown. 
Issue 2
Also there are still nodes refreshed after refresh the page.

**Reproducer**
PrimeFaces Showcase
https://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml

**Environment:**
PF Showcase
 - PF Version: 10.0.0
 - Affected browsers:  Issue 1: Firefox, Chrome/ Issue 2: Firefox

**To Reproduce**
Issue 1
go to
https://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml
under Checkbox Selection
check Application and click Display, Only Applications is selected
expand Application click again Display, still just Applications is selected
unselect Applications and select it again, while Applications is expanded, every value is selected (as expected, also the sub values from node Primefaces)

Issue 2
After this refresh the page and expand Applications, all Subvalues from Applications are still selected except Applications, so 

**Expected behavior**
Issue 1:
all nodes including subnodes should be selected directly

Issue 2:
option 1: the selection should be the same as before refresh 
option 2: nothing should be selected
1 prefer option 2 (as it is currently under chrome)

**Example XHTML**
```html
<h:form id="frmTest">
 <div class="card">
        <h5>Checkbox Selection</h5>
        <p:treeTable value="#{ttSelectionView.root3}" var="document" selectionMode="checkbox"
                     selection="#{ttSelectionView.selectedNodes2}">
            <p:column headerText="Name">
                <h:outputText value="#{document.name}"/>
            </p:column>
            <p:column headerText="Size">
                <h:outputText value="#{document.size}"/>
            </p:column>
            <p:column headerText="Type">
                <h:outputText value="#{document.type}"/>
            </p:column>
        </p:treeTable>

        <p:commandButton value="Display" update="msgs" icon="pi pi-clone" styleClass="p-mt-3"
                         action="#{ttSelectionView.displaySelectedMultiple(ttSelectionView.selectedNodes2)}"/>
    </div>

</h:form>
```

**Example Bean**
```java
@Named("ttSelectionView")
@ViewScoped
public class SelectionView implements Serializable {

    private TreeNode root1;
    private TreeNode root2;
    private TreeNode root3;
    private TreeNode selectedNode;
    private TreeNode[] selectedNodes1;
    private TreeNode[] selectedNodes2;

    @Inject
    private DocumentService service;

    @PostConstruct
    public void init() {
        root1 = service.createDocuments();
        root2 = service.createDocuments();
        root3 = service.createCheckboxDocuments();
    }

    public TreeNode getRoot1() {
        return root1;
    }

    public TreeNode getRoot2() {
        return root2;
    }

    public TreeNode getRoot3() {
        return root3;
    }

    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }

    public TreeNode[] getSelectedNodes1() {
        return selectedNodes1;
    }

    public void setSelectedNodes1(TreeNode[] selectedNodes1) {
        this.selectedNodes1 = selectedNodes1;
    }

    public TreeNode[] getSelectedNodes2() {
        return selectedNodes2;
    }

    public void setSelectedNodes2(TreeNode[] selectedNodes2) {
        this.selectedNodes2 = selectedNodes2;
    }

    public void setService(DocumentService service) {
        this.service = service;
    }

    public void displaySelectedSingle() {
        if(selectedNode != null) {
            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Selected", selectedNode.getData().toString());
            FacesContext.getCurrentInstance().addMessage(null, message);
        }
	}

    public void displaySelectedMultiple(TreeNode[] nodes) {
        if(nodes != null && nodes.length > 0) {
            StringBuilder builder = new StringBuilder();

            for(TreeNode node : nodes) {
                builder.append(node.getData().toString());
                builder.append("<br />");
            }

            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Selected", builder.toString());
            FacesContext.getCurrentInstance().addMessage(null, message);
        }
	}
}
```

**Comment by melloware** [comment]
@FlipWarthog wanna check this one out...

**Comment by FlipWarthog** [comment]
@melloware Yep, you can assign this to me. I just confirmed that it's still an issue in the latest SNAPSHOT of PF11 running the showcase locally.

**Comment by FlipWarthog** [comment]
I'm not able to pick this one up at the moment, but if anyone is motivated to take a pass at it, the propagation issue seems to be the same as #3926 where the child nodes of the collapsed parent are not rendered in the DOM, and therefore not known to the JS. I believe the solution will be similar: encode all the elements but add a style to hide the ones that should be hidden.

For the second issue, it seems that FireFox is hanging on to the _selection hidden input on refresh; as a note, it does not behave this way if you either re-navigate to the same URL or hit Ctrl+F5.

**Comment by melloware** [comment]
The Firefox issue is this I think: https://stackoverflow.com/questions/7377301/firefox-keeps-form-data-on-reload

**Comment by melloware** [comment]
OK I just fixed the Firefox issue part with this commit: https://github.com/primefaces/primefaces/commit/81662d32dbd24b14acf1a096c0c5f7e843a29e1e

It puts it in line with what DataTableRenderer was doing with its encodeStateHolder.

**Comment by melloware** [comment]
Closing this in favor of https://github.com/primefaces/primefaces/issues/10217 which is the same issue but provides a reproducer.
