### ISSUE TITLE
Datatable: draggable columns with filterBy not working on mobile devices

### ISSUE THREAD

**Issue by elias-jk** [primefaces/primefaces#7830]
**Describe the defect**
When using `draggableColumns="true"` on a `p:dataTable`, filtering data in the table won't work on mobile devices.

**Environment:**
 - PF Version: _10.0_
 - Server: _Payara 5.194_
 - Affected browsers: _Chrome on Android_

**To Reproduce**
1. Try to click on the filter text field / type something (won't work)

**Expected behavior**
The textfield in the filterable column is selected.

**Example XHTML**
```html
[...]
<p:dataTable value="#{testTableBean.people}" var="person" draggableColumns="true">
    <p:column headerText="Vorname" filterBy="#{person.forename}" sortBy="#{person.forename}" styleClass="textLongColumn">
        <h:outputText value="#{person.forename}" />
    </p:column>
    <p:column headerText="Nachname" filterBy="#{person.surname}" sortBy="#{person.surname}">
        <h:outputText value="#{person.surname}" />
    </p:column>
</p:dataTable>
[...]
```

**Example Bean**
```java
package com.aiti.formguard.web;

import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import lombok.Getter;

@Named
@ApplicationScoped
public class TestTableBean {

    @Getter
    private List<Person> people;

    @PostConstruct
    public void init() {
        people = List.of(
            new Person("Adam", "Bien") // ...
        );
    }

}

package com.aiti.formguard.web;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Data
public class Person {
    private String forename;
    private String surname;
}
```

**Comment by melloware** [comment]
can you provide a runnable reproducer?  Have you tested with 11.0-SNAPSHOT to see if its already fixed?

**Comment by elias-jk** [comment]
Just tested with 11.0-SNAPSHOT, there is no difference in behaviour. Do you really need a reproducer? In my applications using PF 8 or 10 the error occurs invariably in every table having the `draggableColumns="true"` attribute set. And it works again when this attribute is removed.

**Comment by melloware** [comment]
Thanks for verifying.  OK when you say "Affected browsers: Chrome on Android" Its ONLY Chrome on Android?  Have you tested another browser on Android?  Positive its not happening on Apple IOS?

You are right I can't even test this because I don't own and Android.   Does it happen in desktop Chrome set to "mobile" in the Developer tools?

**Comment by elias-jk** [comment]
It seems to be affecting Firefox on Android as well. Also reproducible in with Chrome desktop developer tools. Unfortunately, I don't have an IOS device for verification.

**Comment by christophs78** [comment]
Maybe "draggable rows"-code simply listens to events which are not triggered on a mobile device with touchscreen?

**Comment by christophs78** [comment]
Should we update the title of the issue? 
You say draggableColumns="true" does not work together with sort- and filter-feature. The title of this issue says something different.

**Comment by elias-jk** [comment]
I updated the description and title. `sortBy` is not required to reproduce the issue.

**Comment by christophs78** [comment]
draggableColumns instead of draggableRows?

**Comment by elias-jk** [comment]
Whoops sorry

**Comment by christophs78** [comment]
Played around a bit with Showcase (DataTable / Filtering - example with `draggableColumns="true"` added.)
Can´t reproduce it yet. Filter is still working after reordering columns.
![image](https://user-images.githubusercontent.com/10461942/133627532-1b3cf5f1-b4d5-4c3c-82dc-a23fc149f24b.png)

**Comment by christophs78** [comment]
@kollerfuzzi : Can you please check with 11.0.0-SNAPSHOT?
Just checked the enhanced Showcase-example on my Android-phone with Chrome. Works.

**Comment by melloware** [comment]
@kollerfuzzi going to close for now.  If you prove its broken in 11.0 then I can re-open the ticket.
