### ISSUE TITLE
AutoComplete: invalid behaviour for forceSelection=true and autoSelection=false

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#7832]
**Describe the defect**
With #3156 (PR #3162) the `autoSelection` property was implemented for `p:autoComplete`. The combination of `forceSelection=true` and `autoSelection=false` produces an invalid state. 

`forceSelection` ensures, that the autoComplete always submits valid values as returned by the `completeMethod`. If no valid item was selected (either manually or auto-selected), the autoComplete is cleared.

With disabled `autoSelection` the `forceSelection` algorithm still validates the entered label but the matching item is not selected resulting in an invalid state - the label instead of the item-value will be submitted to the server. This may cause an error in the backend due to e.g. a type missmatch (In my case: the converter expects an parseable number and not an string).

**Expected Behaviour**
In my opinion the autoComplete should be cleared or the documented logic of `forceSelection` is broken.

If `forceSelection` is `true` and you search a value but no suggested item is manually selected, always clear the state of the autoComplete when the input is blurred and `autoSelection` is `false`,

**Reproducer**
_I have to prepare a reproducer if required._

**Environment:**
 - PF Version: 10.0

**Comment by melloware** [comment]
@OBreidenbach what do you think? you did the original PR for this so wanted your thoughts.

**Comment by melloware** [comment]
We also probably need an Integration Test for this like this one: https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/autocomplete/AutoComplete005Test.java

**Comment by OBreidenbach** [comment]
Since #3156 (PR #3162), which was more than three years ago, we are using autocomplete with:
`
multible="true"
forceSelection="true"
autoSelection="false"
`
Since then we did not have any problems.
I am not sure what would be the correct behavior for 'mulible="false"'.

**Comment by melloware** [comment]
@fanste do you have a suggested fix?

**Comment by fanste** [comment]
I will have a look at this next week

**Comment by melloware** [comment]
@fanste I am writing an Integration Test and I can't reproduce your issue.  Here is my test and its all working properly.

https://github.com/primefaces/primefaces/pull/8022

**Comment by melloware** [comment]
Going to close this for now. If you can reproduce I can reopen!
