### ISSUE TITLE
Paginator: Customize {PageLinks} 

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#7834]
I was trying to replace Datatable Paginator element "{PageLinks}" with my custom implementation of a PaginatorElementRenderer but only the initial rendering was successful.
After clicking on "Next Page" Button it renders the same output as the original PageLinksRenderer Class from Primefaces did.

I discovered that the same rendering was done in "paginator.js" also. It looks like this happens after the first interaction with the Paginator controls. Here is the code from PageLinksRenderer Class:

```
public class PageLinksRenderer implements PaginatorElementRenderer {

    @Override
    public void render(FacesContext context, Pageable pageable) throws IOException {
        ResponseWriter writer = context.getResponseWriter();
        int currentPage = pageable.getPage();
        int pageLinks = pageable.getPageLinks();
        int pageCount = pageable.getPageCount();
        int visiblePages = Math.min(pageLinks, pageCount);

        //calculate range, keep current in middle if necessary
        int start = Math.max(0, currentPage - (visiblePages / 2));
        int end = Math.min(pageCount - 1, start + visiblePages - 1);

        //check when approaching to last page
        int delta = pageLinks - (end - start + 1);
        start = Math.max(0, start - delta);

        writer.startElement("span", null);
        writer.writeAttribute("class", UIPageableData.PAGINATOR_PAGES_CLASS, null);

        for (int i = start; i <= end; i++) {
            String styleClass = currentPage == i ? UIPageableData.PAGINATOR_ACTIVE_PAGE_CLASS : UIPageableData.PAGINATOR_PAGE_CLASS;

            writer.startElement("a", null);
            writer.writeAttribute("class", styleClass, null);
            writer.writeAttribute("tabindex", 0, null);
            writer.writeAttribute("href", "#", null);
            writer.writeText((i + 1), null);
            writer.endElement("a");
        }

        writer.endElement("span");
    }
}

```
and this is the code from "paginator.js" beginning from line 369:

```
    /**
     * Updates the UI of page link button so that they reflect the current pagination state.
     * @private
     */
    updatePageLinks: function() {
        var start, end, delta,
        focusedElement = $(document.activeElement),
        focusContainer;

        if(focusedElement.hasClass('ui-paginator-page')) {
            var pagesContainerIndex = this.pagesContainer.index(focusedElement.parent());
            if(pagesContainerIndex >= 0) {
                focusContainer = this.pagesContainer.eq(pagesContainerIndex);
            }
        }

        //calculate visible page links
        this.cfg.pageCount = Math.ceil(this.cfg.rowCount / this.cfg.rows)||1;
        var visiblePages = Math.min(this.cfg.pageLinks, this.cfg.pageCount);

        //calculate range, keep current in middle if necessary
        start = Math.max(0, Math.ceil(this.cfg.page - ((visiblePages) / 2)));
        end = Math.min(this.cfg.pageCount - 1, start + visiblePages - 1);

        //check when approaching to last page
        delta = this.cfg.pageLinks - (end - start + 1);
        start = Math.max(0, start - delta);

        //update dom
        this.pagesContainer.children().remove();
        for(var i = start; i <= end; i++) {
            var styleClass = 'ui-paginator-page ui-state-default ui-corner-all',
            ariaLabel = this.cfg.ariaPageLabel.replace('{0}', (i+1));

            if(this.cfg.page == i) {
                styleClass += " ui-state-active";
            }

            this.pagesContainer.append('<a class="' + styleClass + '" aria-label="' + ariaLabel + '" tabindex="0" href="#">' + (i + 1) + '</a>');
        }

        if(focusContainer) {
            focusContainer.children().filter('.ui-state-active').trigger('focus');
        }

        this.bindPageLinkEvents();
    },

```

I understand that this is a kind of optimization regarding network traffic but it makes the idea of replacing pagination elements impossible. And i think it is a conceptual failure that should be fixed.

**Comment by melloware** [comment]
As you said its an optimization to prevent AJAX round trips when rendering.   

Why not just change your paginator JS with a MonkeyPatch that makes the same change you are making server side?  This is why PF/JSF is infinitable pluggable you can change both the renderer and the JS code to meet your need.

@tandraschko I am going to mark this as WorkAround and WontFix because I really doubt this is something the community or PrimeTek will want to change?

**MonkeyPatch...**
```javascript
if (PrimeFaces.widget.DataTable) {
    /**
     * Updates the UI of page link button so that they reflect the current pagination state.
     * @private
     */
    PrimeFaces.widget.DataTable.prototype.updatePageLinks = function() {
        var start, end, delta,
            focusedElement = $(document.activeElement),
            focusContainer;

        if (focusedElement.hasClass('ui-paginator-page')) {
            var pagesContainerIndex = this.pagesContainer.index(focusedElement.parent());
            if (pagesContainerIndex >= 0) {
                focusContainer = this.pagesContainer.eq(pagesContainerIndex);
            }
        }

        //calculate visible page links
        this.cfg.pageCount = Math.ceil(this.cfg.rowCount / this.cfg.rows) || 1;
        var visiblePages = Math.min(this.cfg.pageLinks, this.cfg.pageCount);

        //calculate range, keep current in middle if necessary
        start = Math.max(0, Math.ceil(this.cfg.page - ((visiblePages) / 2)));
        end = Math.min(this.cfg.pageCount - 1, start + visiblePages - 1);

        //check when approaching to last page
        delta = this.cfg.pageLinks - (end - start + 1);
        start = Math.max(0, start - delta);

        //update dom
        this.pagesContainer.children().remove();
        for (var i = start; i <= end; i++) {
            var styleClass = 'ui-paginator-page ui-state-default ui-corner-all',
                ariaLabel = this.cfg.ariaPageLabel.replace('{0}', (i + 1));

            if (this.cfg.page == i) {
                styleClass += " ui-state-active";
            }

            this.pagesContainer.append('<a class="' + styleClass + '" aria-label="' + ariaLabel + '" tabindex="0" href="#">' + (i + 1) + '</a>');
        }

        if (focusContainer) {
            focusContainer.children().filter('.ui-state-active').trigger('focus');
        }

        this.bindPageLinkEvents();
    }
}
```

**Comment by melloware** [comment]
I can reopen if anyone feels strongly about this...

**Comment by ghost** [comment]
That's not a valid solution because it forces one to change the behaviour in Java and Javascript in the same way.
Currently only the first rendering is produced by the Java renderer and all subsequent page changes are prepared by JS code.

I think it would be more consistent if the ajax request reading the partial update for the next DataTable-page will add the updated page links also. This ajax call is done anyway so there is nothing to optimize regarding server roundtrips.

Therefore the current JS implementation of paginator.js does not fully respect the "paginatorTemplate" definition attribute of the DataTable component. Because in my case the "{PageLinks}" placeholder was removed and paginator.js does render it anyway.

I would be really happy if you think about it again please.

**Comment by melloware** [comment]
Possibly but paginator is used on more than 1 component...

- [ ] DataTable
- [ ] TreeTable
- [ ] DataGrid
- [ ] DataList
- [ ] DataView

So i am not sure why PrimeTek designed it this way but it seems like a major change with lots of retesting.  

PR's are welcome so you are more than welcome to submit a PR if you fix it...

**Comment by melloware** [comment]
@tandraschko would like your opinion on this?

**Comment by ghost** [comment]
I still believe that this is a serious issue. Based on the documentation, you would not expect a completely different representation to be displayed when you turn pages. And it doesn't make sense to implement the function twice in different languages (Java, JS).
By the way, hardly anyone using PrimeFaces will expect to have to implement functionality in JavaScript.

Here is the paginatorTemplate of my datatable :

```
paginatorTemplate="{CurrentPageReport} {PreviousPageLink} {LsgPageLinks} {NextPageLink}"
```

and here is what i did to replace {PageLinks} with my {LsgPageLinks}:

```
DataRenderer.removePaginatorElement("{PageLinks}");
DataRenderer.addPaginatorElement("{LsgPageLinks}", new StyledPageLinksRenderer());
```

Using my attached class [StyledPageLinksRenderer.zip](https://github.com/primefaces/primefaces/files/7184139/StyledPageLinksRenderer.zip) it produces this output:

![grafik](https://user-images.githubusercontent.com/17578066/133753022-ebb609f9-3d18-4298-b72b-40eb52027ccd.png)

If I click on to the next page, this happens:

![grafik](https://user-images.githubusercontent.com/17578066/133753957-1a2eb1e3-d72c-4876-b557-90951e64fc58.png)

As you can see, it switched to the default implementation completely ignoring my customized paginatorTemplate.
You can imagine how surprised I was when I noticed it.

However, a solution might be that if the page is changed, the paginator will also be updated in the Ajax request.
Unfortunately, I do not have enough knowledge to implement the code modifications that would be necessary to change this.

I would ask you to reopen the ticket and seriously consider a fix.

**Comment by melloware** [comment]
@onlytrying I am not trolling you, I am going to be honest with you and make a few points.

- I don't work for PrimeTek I am just an open source contributor.
- This feature is used in 5 components above so I am not sure why PrimeTek designed it this way but I am assuming they had a reason.  So it could be quite an impactful change.
- I have provided a workaround above and there is nothing stopping you from implementing it.

You have 3 options..

1. Create a PR and fix the issue yourself with Integration Tests (you have said above this is not an option)
2. Use your PrimeTek PRO account or Request a Quote and pay PrimeTek to address this issue.
3. Hope the community developers fix it.  Now what I have seen is tickets like this will stay open forever as no one in the community feels strongly about it, and typically the original reporter doesn't want to pay PrimeTek to address it.

That is why I chose to close this ticket.  I can re-open it but I am pretty sure 3 years from now this ticket will still be open and bullet item #3 above will be true.

**Comment by melloware** [comment]
A perfect example is this ticket from 2.5 years ago... https://github.com/primefaces/primefaces/issues/4685

**Comment by ghost** [comment]
@melloware I tried your suggested MonkeyPatch. So far I can see in debugger that "updatePageLinks" function will be updated but it is never reached when I click a paginator button. It still executes the original code. Is there anything i missed?
I'm not too adept at javascript.

**Comment by melloware** [comment]
Hmmm I assumed since that is the client side code you pointed out as overriding your custom server side renderer that that is the code you would need to update.  If you are overriding that method but not seeing it called in the debugger then it sounds like something else is updating your paginator?  Or some other JS code?

**Comment by melloware** [comment]
It looks like to code you want to override is in paginator.js not in datatable.js

See: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js

**Comment by ghost** [comment]
I found out the easy way to solve this problem. Just set <p:dataTable ... partialUpdate="false" ...> and that is it!
This way I always get the result rendered by my custom PageLinksRenderer.
Thank you for your support.

**Comment by melloware** [comment]
HA thanks for posting back!
