### ISSUE TITLE
DataTable: after filtering and changing value during ajax old filtered data is still shown

### ISSUE THREAD

**Issue by neXus1987** [primefaces/primefaces#7845]
**Describe the defect**
When you filter a Datatable and updates the value using ajax, the filtered old value will be still applied even if you set the filteredValue to null

**Reproducer**
 https://github.com/neXus1987/primefaces-datatable-test.git

**Environment:**
 - PF Version: _10.0_
 - JSF + version: Mojarra 2.2.20 
 - Affected browsers: FireFox

**To Reproduce**
Filter for: Data 1
click on button toggle

**Expected behavior**
no records should been shown, because the filter do not match the new data (Data 2 *)

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" lang="de">
<h:head>
</h:head>
<h:body>
	<h:form>
		<p:dataTable value="#{kundenbereichModel.listStringData}" var="d">
			<p:column filterBy="#{d}" filterMatchMode="contains">#{d}</p:column>
		</p:dataTable>
		<p:commandLink update="@form" process="@this"
			actionListener="#{kundebereichTestController.toggleList()}">toggle</p:commandLink>
	</h:form>
</h:body>
</html>
```

**Example Bean**
```java
@ManagedBean
@RequestScoped
public class KundebereichTestController {
	private final static Log logger = LogFactory
			.getLog(KundebereichTestController.class);

	@ManagedProperty("#{kundenbereichModel}")
	private KundenbereichModel kundenbereichModel;

	public void setKundenbereichModel(KundenbereichModel kundenbereichModel) {
		this.kundenbereichModel = kundenbereichModel;
	}
	
	private List<String> getData1() {
		List<String> t = new ArrayList<>();

		t.add("Data 1 1");
		t.add("Data 1 2");
		t.add("Data 1 3");
		t.add("Data 1 4");

		return t;
	}

	private List<String> getData2() {
		List<String> t = new ArrayList<>();

		t.add("Data 2 1");
		t.add("Data 2 2");
		t.add("Data 2 3");
		t.add("Data 2 4");

		return t;
	}

	public void toggleList() {

		if (kundenbereichModel.getViewState() == 0) {
			kundenbereichModel.setListStringData(getData1());
			kundenbereichModel.setViewState(1);
		} else {
			kundenbereichModel.setListStringData(getData2());
			kundenbereichModel.setViewState(0);
		}

	}
}

@ManagedBean
@ViewScoped
public class KundenbereichModel implements Serializable, {

	private List<String> listStringData;

	public List<String> getListStringData() {
		return listStringData;
	}

	public void setListStringData(List<String> listStringData) {
		this.listStringData = listStringData;
	}
	
	private int viewState;
	public int getViewState() {
		return viewState;
	}

	public void setViewState(int viewState) {
		this.viewState = viewState;
	}
}
```

**Comment by christophs78** [comment]
Can you please check this against 11.0.0-Snapshot?
Think some similar issues had been fixed.
https://github.com/primefaces/primefaces/issues/7336

**Comment by melloware** [comment]
This does not work in 11.0.0-SNAPSHOT but it makes sense.  He is just swapping out the data of the data table but not the filtered values.  To me the datatable is doing the expected behavior.

@neXus1987 you have two ways to fix your code

1. By calling filter() but this forces a second AJAX call...
```xml
<p:commandLink update="@form" 
process="@this" 
actionListener="#{testView.toggleList()}" 
oncomplete="PF('dataTable').filter();">toggle</p:commandLink>
```

2. Following this ticket https://github.com/primefaces/primefaces/issues/7336 and using the code provided:

**10.0.0**
```java
DataTable dataTable = (DataTable)FacesContext.getCurrentInstance().getViewRoot().findComponent("form:dt-products");
	FilterFeature filterFeature = (FilterFeature) dataTable.getFeature(DataTableFeatureKey.FILTER);
	filterFeature.filter(FacesContext.getCurrentInstance(), dataTable);
	SortFeature sortFeature = (SortFeature) dataTable.getFeature(DataTableFeatureKey.SORT);
	sortFeature.sort(FacesContext.getCurrentInstance(), dataTable);
```

**11.0.0**
```java
DataTable dataTable = (DataTable) FacesContext.getCurrentInstance().getViewRoot().findComponent("form:datatable");
dataTable.filterAndSort();
```

**Comment by neXus1987** [comment]
i´ve tested it with the Primefaces current Snapshot and it works still as described.  I don´t know how this code exactly works and where the filtered Data is cached, but could it be possible to save the hashvalue of the list and if this is a new one, then the component will reset itself?

In my code we have a master an on the next view the details table and i also tried to set different widgetvar/id to the table, but the filtered value is still cached. it would be possible to do it in backend, but then i have to get all ids in the backend. Just thinking if it would be possible that the datatable component recognized a value change and then will reset itself!?

**Comment by neXus1987** [comment]
If you filter to something which not exists and the table shows no data and then press toggle, it will show the other data. Just if you filter to something exists and press toggle it shows the old filtered data even if I set at backend the filteredValue to null or empty list. So it seems that there is a decision if the filtered value is zero refresh it or so.

**Comment by melloware** [comment]
Yes @neXus1987 once your DataTable.getFiltered() list is filled out its the list until Filter is called again.  which explains why your scenario above works the DataTable.getFiltered() list is empty at the time so it can then fill it.  But its if already filled it doesn't overwrite it.

See my solutions above.

**Comment by neXus1987** [comment]
just as an idea (as i understand the complex DataTable code so far) if overriding the setValue(Object o) from UIData as following:
```

	@Override
		public void setValue(Object value) {

			Object oldValue = super.getValue();
			super.setValue(value);

			if (oldValue != null && oldValue != value) {

				filterAndSort();
			}
		}
```
This should trigger the filter and sort if the value has changed!?

**Comment by melloware** [comment]
Not sure if that would work because `oldValue != newValue` is comparing object references right and if they are proxied CDI beans couldn't it be different every single time?  Thoughts @tandraschko @christophs78

**Comment by christophs78** [comment]
Need to think about this longer and probably test and debug some usecases.
We have infrastructure to detect and unproxy classes. (https://github.com/primefaces/primefaces/blob/9798bcc3fa0ebe5f10d7762ecaf282d92e3b326b/primefaces/src/main/java/org/primefaces/util/LangUtils.java#L321)
But not sure whether we can transfer this to instances. Would require analysis.
Another aspect is where to start and where to stop. Someone may argue he clears a list and adds new entries. This may require a different approach.
And all this without breaking existing usecases.

**Comment by neXus1987** [comment]
And the correct way would be maybe to reset the table (in my use case) instead of applying the current filter against the new data. So maybe it is a better approach to add an instanceKey and put all cached data in context to this instanceKey.

**Comment by neXus1987** [comment]
just an idea:
would it be possible to override the getStateHelper() method within DataTableBase, maybe there is a better idea when to check for current instanceKey, is there some Method which is called initially, so that we can update the instanceKey once in a "render-cycle":

```
	private Map<String, StateHelper> mapStateHelper;

	private ValueExpression valueExpressionInstanceKey;
	private boolean checkedInstanceKey;
	@Override
	protected StateHelper getStateHelper() {

		Object instanceKey = null;
		if (!checkedInstanceKey&&valueExpressionInstanceKey == null) {
			valueExpressionInstanceKey = this
					.getValueExpression(PropertyKeys.instanceKey.toString());
			checkedInstanceKey=true;
		}
		if (valueExpressionInstanceKey != null) {
			instanceKey = valueExpressionInstanceKey
					.getValue(this.getFacesContext().getELContext());
		}
		if (instanceKey != null) {
			StateHelper ret = mapStateHelper.get(instanceKey.toString());
			if (ret == null) {
				ret = getStateHelper(true);
				mapStateHelper.put(instanceKey.toString(), ret);
			}
			return ret;
		}
		return getStateHelper(true);
	}
```

**Comment by neXus1987** [comment]
or one other idea (i have the primefaces Datatable extended for testing):

```
@FacesComponent(value = "datatable", createTag = true, namespace = "http://dummy.de/components")
public class Datatable extends DataTable {
	private final static Log logger = LogFactory.getLog(Datatable.class);

	public Datatable() {
		super();

		logger.debug("init datatable: " + this.hashCode());

	}

	@Override
	public void encodeBegin(FacesContext context) throws IOException {
		
        //before rendering (maybe there is a better method than encodeBegin, i am not completely aware of the JSF lifecycle)
		//get the current hashcode for the optionally new datatable
		int currentValue = System.identityHashCode(getValueExpression("value")
				.getValue(getFacesContext().getELContext()));
		
		//if the both hashcodes are different, this means the original value has changed
		//so the underlying data to the filteredValue has changed, in my case it makes sense to reset the datatable
		if(valueHashcode!=0 && valueHashcode!=currentValue) {
			reset();
		}
		super.encodeBegin(context);
	}

	private int valueHashcode;
	@Override
	public void restoreState(FacesContext context, Object state) {

		// as datatable is new instantiated this is the real object set via xhtml to value
		valueHashcode = System.identityHashCode(getValue());
		super.restoreState(context, state);

	}
}
```

**Comment by neXus1987** [comment]
or instead of checking the value, introducing a new property: instanceKey  and if this changed, than reset.. so we can control the behaviour

**Comment by melloware** [comment]
I will let others weigh in here like @tandraschko

**Comment by tandraschko** [comment]
for me it sounds very related to #7999

we could also fix this with mirroring/copying the value<>filteredValue list but instead remember the filtered rowKeys skip while rendering

**Comment by tandraschko** [comment]
@melloware @christophs78 added a test for it; could you please verify if i test the correct behavior/order like described here?
i think my newest change in #7999 fixes this issue

**Comment by melloware** [comment]
@tandraschko looks good to me from looking at it!

**Comment by neXus1987** [comment]
also tested it, and works as expected. THANKS!!!!!

**Comment by fcorneli** [comment]
Will this be back-ported to 10?

**Comment by tandraschko** [comment]
thats up to @mertsincan 

i suggest to use 11.0 RC2
its _much_ more stable as 10.0 in case of DataTable
