### ISSUE TITLE
Move JS Script To Bottom: JS Error when Primefaces is not used on Page

### ISSUE THREAD

**Issue by neXus1987** [primefaces/primefaces#7846]
**Describe the defect**
When following is activated in web.xml and there is a page without Primefaces:
```
	<context-param>
		<param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
		<param-value>true</param-value>
	</context-param>
```
following will be generated at the end:
if(window.$){$(PrimeFaces.escapeClientId("4ff96bf4-a5ec-4916-9eff-dedb56222daf")).remove();}

is it possible to generate following if:
if(window.PrimeFaces){	
if(window.$){$(PrimeFaces.escapeClientId("4ff96bf4-a5ec-4916-9eff-dedb56222daf")).remove();}
}
or mockup the escapeClientId function!?

**Reproducer**
Page with Move JS Script to bottom, but without Primefaces Component on Page

**Environment:**
 - PF Version: 10.0
 - JSF + version: 2.2.20 
 - Affected browsers: ALL

**To Reproduce**
run page and view error 

**Expected behavior**
js error should not be there

**Comment by tandraschko** [comment]
oh, wrong commit message
see my commit here: https://github.com/primefaces/primefaces/commit/0c2131362881269fcbdb7b6cab812f0d248c1a75

please test again

**Comment by neXus1987** [comment]
thanks!
