### ISSUE TITLE
DataTable: getValue is called, also when not rendered, when lazy attr is not set

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7847]
we can atleast reduce the check to one time or try to get the property type instead of the value itself from EL

**Comment by tandraschko** [comment]
@christophs78 i introduced a ELUtils, which gets the type of ValueExpression
would you like to use this in the calendar/datepicker too?

**Comment by melloware** [comment]
Yes we definitely should. And I believe I already have Integration Tests for DatePicker catching the scenario that broke.

**Comment by melloware** [comment]
@christophs78 I can submit a PR.

**Comment by melloware** [comment]
@tandraschko no we can't use this because you short circuit to `getExpectedType` which is returning a `LocalDate` and not `LocalDateTime` so all the Integration tests fail.  So that is why we do it like we do...
```java
try {
            return ve.getType(context.getELContext());
        }
        catch (PropertyNotFoundException ex) {
            // #7615 return null to make it behave same as Calendar
            return null;
        }
```

**Comment by tandraschko** [comment]
can you point to the method which is marked as LocalDate but just returns a LocalDateTime?

**Comment by melloware** [comment]
Yep its in `UICalendar` here...

```java
/**
     * Only for internal usage within PrimeFaces.
     * @return Type of the value bound via value expression. May return null when no value is bound.
     */
    public Class<?> getTypeFromValueByValueExpression(FacesContext context) {
        ValueExpression ve = getValueExpression("value");
        if (ve == null) {
            return null;
        }

        try {
            return ve.getType(context.getELContext());
        }
        catch (PropertyNotFoundException ex) {
            // #7615 return null to make it behave same as Calendar
            return null;
        }
    }
```

If I change 've.getType()` to `ve.getExpectedType` it returns LocalDate incorrectly and all our Integration Tests fail.  So

**Comment by tandraschko** [comment]
all our tests datapicker tests?
i just wonder in which bean it exactly happens?
when you bind a value to LocalDate, both getType and getExpectedType should return LocalDate, same for LocalDateTime
as method signature and value is the same

if both are different, it could happen that exepectedType is different then type but i think also expected...

**Comment by melloware** [comment]
All the info is in this PR convo: https://github.com/primefaces/primefaces/pull/7619

**Comment by tandraschko** [comment]
commited, looks good for me

**Comment by melloware** [comment]
Nice!  Watching Integration Tests now!
