### ISSUE TITLE
InputNumber - DEL removes zeros

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#7849]
**Describe the defect**
Pressing DEL in p:inputNumber removes zeros.

**Reproducer**
Run attached clone of https://github.com/primefaces/primefaces-test.git with following command:

mvn clean jetty:run -Pmojarra23

**Environment:**
 - PF Version: _10.0_
 - JSF + version: Mojarra 2.3
 - Affected browsers: ALL

**To Reproduce**
1. Run with 'mvn clean jetty:run -Pmojarra23''
2. Enter 'http://localhost:8080/primefaces-test/' in browser
3. Enter 123456,00 in input field 1 and press TAB 
4. Enter 100500,00 in input field 2 and press TAB
5. Place cursor before 4 in input field 1 and press DEL and TAB
6. Place cursor before second zero in input field 2 and press DEL

**Expected behavior**
Value for Input 1 after DEL is 12.356,00 -> OK
Value for Input 2 after DEL should be 10.500,00 but is 100,00 -> FAIL

**Example XHTML**
see test.xthml in attached archive

**Example Bean**
see TestMode.java in attached archi
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7202849/primefaces-test-master.zip)
![ScreenShot_21-09-21_14-08 001](https://user-images.githubusercontent.com/25029017/134167710-2abc822c-1083-4854-8b03-f3bb6208948c.PNG)
![ScreenShot_21-09-21_14-08](https://user-images.githubusercontent.com/25029017/134167713-87d83236-5239-49c0-aca1-ce19bf6a72b2.PNG)
ve

**Comment by melloware** [comment]
I can't reproduce with 11.0.0-SNAPSHOT.

Duplicate of https://github.com/primefaces/primefaces/issues/7271

Can you try the monkeypatch in that ticket and verify its fixed.

**Comment by rho66** [comment]
I added the monkeypatch to my test.js and included it in my test.xhtml but the zeros are still removed!
```
<h:head>
    <title>PrimeFaces Test</title>
    <h:outputScript name="test.js"/>
</h:head>
``
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7209452/primefaces-test-master.zip)

**Comment by melloware** [comment]
Can you try my attached on here:
[pf-7849.zip](https://github.com/primefaces/primefaces/files/7210283/pf-7849.zip)

It is using your example with the MonkeyPatch and when I put the key next to the "." in the second box and press DEL this is what mine does...
![image](https://user-images.githubusercontent.com/4399574/134336431-7f6c7c68-61ee-43ab-a28f-44b0caf03bad.png)

**Comment by rho66** [comment]
1. click into input field for "Betrag 1"  and enter 123456,00
2. press TAB and enter 100500,00 in input field for "Betrag 2"
3. press Shift-TAB to set focus to input field for "Betrag 1", move cursor with keys before 4 and press DEL -> value changes to 12.356,00
4. press TAB so that focus changes to input field of "Betrag 2"
3. IMPORTANT: use cursor keys to place cursor before 2nd zero
4. press DEL and value chanegs to 100,00

![ScreenShot_21-09-22_14-38](https://user-images.githubusercontent.com/25029017/134344986-91168af8-caff-496d-8184-4a233b8202e2.PNG)

**Comment by melloware** [comment]
That was the trick use the cursor keys!

**Comment by melloware** [comment]
I am still researching but I think this might be a bug in the AutoNumeric JS library.

**Comment by rho66** [comment]
Thanks for the update! 
Did you create an issue at (https://github.com/autoNumeric/autoNumeric/issues) ?

**Comment by melloware** [comment]
I did not create an issue because I still can't pinpoint exactly where its going wrong.  Next step might be to create a JSFiddle reproducer and see if I can reproduce it with just AutoNumeric.

**Comment by melloware** [comment]
Still happening with PF 13 SNAPSHOT and latest AutoNumeric.  Feels like an AutoNumeric bug.

**Comment by melloware** [comment]
I think it might be related to these bugs:
https://github.com/autoNumeric/autoNumeric/issues/767

https://github.com/autoNumeric/autoNumeric/issues/582

**Comment by melloware** [comment]
Going to close this as tracked in a third party lib.  Will re-open if those bus are fixed.
