### ISSUE TITLE
SpeedDial: Add keepOpen attribute to keep the menu open when an item is clicked

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7855]
https://www.primefaces.org/showcase-ext/sections/fab/basicUsage.jsf

Created new issue for `p:badge` support. #7898
Created new issue for rotate animation. #7902

**Comment by melloware** [comment]
Love it. I was going to ask what features were missing from FAB but you have it covered.

**Comment by melloware** [comment]
Animation seems to be working for me on the Showcase? https://www.primefaces.org/showcase/ui/button/speedDial.xhtml  Can you confirm?

**Comment by jepsar** [comment]
Ah, I see a slight animation now. I want to look into it in more detail (different icons). Compare the PF showcase to https://www.primefaces.org/showcase-ext/sections/fab/customContent.jsf for example. I'm not sure, but it seems PF is just doing a 45deg rotate, while PFE does a 180deg + cross fade.

**Comment by jepsar** [comment]
By the way, this issue was next on my list after fixing the date picker lazy model events

**Comment by melloware** [comment]
OK assigned to you!

**Comment by tandraschko** [comment]
would be great if someone can restes as RC1 is already out, we should not add much new features and focus in fixes

**Comment by jepsar** [comment]
Alright, then let us keep the other two SpeelDial issues for 12. We will keep FAB in PFE 11 as deprecated anyway.

**Comment by tandraschko** [comment]
if they are small improvements, please create a PR now
just big tickets or refactorings should not be done anymore
