### ISSUE TITLE
Disabled p:commandButton not working properly Microsoft Edge

### ISSUE THREAD

**Issue by playeronee** [primefaces/primefaces#786]
Browser: Microsoft Edge (Windows 10 Pro)

You can repeat bug in Primefaces showcase too:
http://www.primefaces.org/showcase/ui/button/button.xhtml
http://www.primefaces.org/showcase/ui/button/commandButton.xhtml

Flow: Click on the disabled button: Bookmark or Disabled - ajax action is performed. Defect: Click action should be disabled.

**Comment by tandraschko** [comment]
Duplicate #756
