### ISSUE TITLE
Reimplement Galleria

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#7863]
Galleria implementation is legacy and misses practices from our latest widgets, reimplement it from scratch and also consider responsive galleria.
Exp; https://primefaces.org/primereact/showcase/#/galleria

**Comment by melloware** [comment]
I updated 11.0 whatsnew.md and migration_guide.md but we need to update 11.0.0 Galleria MD and Carousel and make sure they represent the new components.

**Comment by mertsincan** [comment]
Thanks a lot, @melloware ;) I'll update galleria.md.
