### ISSUE TITLE
Selenium: org.primefaces.selenium.component.SelectOneMenu#getLabels fails with filter

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7864]
@christophs78 i can see you changed the code for the filter case
i can commit a IT
would you like to check it?

**Comment by tandraschko** [comment]
commited the test, would be great if someone could check it

**Comment by christophs78** [comment]
yes, i´m looking at it.
your i-test is currently green. but it does not call org.primefaces.selenium.component.SelectOneMenu#getLabels yet.

**Comment by christophs78** [comment]
Confirm that org.primefaces.selenium.component.SelectOneMenu#getLabels has an issue togehter with filter.
(Because DOM-structure used by getLabels has not been build yet.)

**Comment by melloware** [comment]
Can this be closed now?
