### ISSUE TITLE
Selenium: Make adapter optional

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7870]
As we now have automatic driver management, we can introduce a baseUrl remote adress config property
so the adapter is only required anymore for local deployments

**Comment by tandraschko** [comment]
i would like to split PrimeSeleniumAdapter into 3 arficats:
- DeploymentAdapter (optional, only required when local deployments are used, otherwise baseUrl will be a required property)
- WebDriverAdapter (optional, per default its managed as currently)
- OnloadScriptAdapter (optinoal, like current PrimeSeleniumAdapter#registerOnloadScripts)

**Comment by christophs78** [comment]
Sound´s good. Maybe we can do this after https://github.com/primefaces/primefaces/pull/7811 is merged. Because both aspect touch the same classes.
