### ISSUE TITLE
Selenium: rework CSP support to remove runtime-module

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7871]
the runtime module is required in the application itself, that makes remote testing unusable with CSP

the runtime module consists of 2 features:
- enable CSP testing support
- disable animations

we can also download lazy the disableanimations.css in selenium core
not sure about CSP

**Comment by tandraschko** [comment]
i think we could add to this to onloadscripts:
document.head.insertAdjacentHTML("beforeend", "*, *:before, *:after { -webkit-transition: none !important; -moz-transition: none !important; -ms-transition: none !important; -o-transition: none !important; transition: none !important; }");

**Comment by tandraschko** [comment]
i commited the animations part, please review
about CSP, we can do it later

**Comment by melloware** [comment]
Looks good so far!

**Comment by melloware** [comment]
Part of this issue when running build...
```
[WARNING] The following dependencies could not be resolved at this point of the build but seem to be part of the reactor:
[WARNING] o org.primefaces:primefaces-selenium-runtime:jar:11.0.0-SNAPSHOT (runtime)
[WARNING] Try running the build up to the lifecycle phase "package"
```

**Comment by christophs78** [comment]
Think i remember why we choose this complicated solution for PF Selenium combined with CSP.
https://github.com/primefaces/primefaces/blob/master/primefaces-selenium/primefaces-selenium-runtime/src/main/resources/META-INF/resources/primefaces_selenium/pfselenium.core.csp.js overrides parts of https://github.com/primefaces/primefaces/blob/add518b8e8a6a5ced47239427ae811442cb6a430/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js#L51. So we need to load it after after PF-core-JS. (also see https://github.com/primefaces-extensions/primefaces-selenium/pull/63)
Is there a better solution to do this?

**Comment by tandraschko** [comment]
I wonder why this is required
couldnt we get the registered events via js/jquery of a element anyway, without storing it in a map?

**Comment by melloware** [comment]
@tandraschko you might be right, we basically need some way of telling if a component is regsitered.  We had discussed fixing PF core to hold this in a JS MAP when registering so we could just inspect the with PrimeFaces.isRegistered(xxx) JS code but I think you were against that because it was holding a memory map in PF JS used only for Selenium testing.  But I think its a good idea because it will help us get rid of this code.

**Comment by christophs78** [comment]
We originally discussed this as part of https://github.com/primefaces-extensions/primefaces-integration-tests/pull/78
Better solution is welcome.

**Comment by tandraschko** [comment]
Couldnt we just use:
`jQuery._data($('#form\\:j_id_4k_input')[0], 'events');` for it?

**Comment by melloware** [comment]
I think we might but I had read somewhere bfore not to rely on Jquery `_data` because its not meant to be used, although I am pretty sure I needed to use it to solve other CSP problems.

**Comment by tandraschko** [comment]
if they remove it someday in the future, we can still rework it again

**Comment by melloware** [comment]
good with me!

**Comment by tandraschko** [comment]
anyone interessted in providing a PR?

**Comment by melloware** [comment]
Let me see if I can fix it.

**Comment by melloware** [comment]
I think I almost have this figured out.  Still testing.
