### ISSUE TITLE
Broken links on primefaces-selenium page

### ISSUE THREAD

**Issue by cybertschunk** [primefaces/primefaces#7883]
On [this page ](https://github.com/primefaces/primefaces/tree/master/primefaces-selenium) about primefaces-selenium are the links to the Javadoc and to the maven repository broken. 

I just wanted to report this here. Have a nice day!

**Comment by tandraschko** [comment]
its because its not released yet

**Comment by cybertschunk** [comment]
Oh, that's interesting. Do you have an idea when this will happen? It sounds like a really interesting feature!

**Comment by tandraschko** [comment]
RC1 is planned this week

**Comment by cybertschunk** [comment]
Thanks for the info. I will test it out.

**Comment by tandraschko** [comment]
Fixed now
