### ISSUE TITLE
Schedule: FullCalendar is already timezone-aware since v5, PrimeFaces.toISOString should not be used

### ISSUE THREAD

**Issue by BalusC** [primefaces/primefaces#7891]
**Describe the defect**
When using `<p:schedule>` with a fixed client time zone as in `<p:schedule clientTimeZone="UTC">` then the lazy load and date select events still send wrong local dates back into the `LazyScheduleModel#loadEvents()` and `SelectEvent<LocalDateTime>` respectively.

**Reproducer**
1. Open https://www.primefaces.org/showcase/ui/data/schedule/configuration.xhtml
2. Adjust `clientTimeZone` option from `local` to a different timezone than your own
3. Click any time slot and in the modal you'll notice that the time is off from what's being selected

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**Cause**
https://github.com/primefaces/primefaces/blob/10.0.0/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js is still using `PrimeFaces#toISOString()` in three places:
- https://github.com/primefaces/primefaces/blob/10.0.0/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L135
- https://github.com/primefaces/primefaces/blob/10.0.0/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L283
- https://github.com/primefaces/primefaces/blob/10.0.0/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L284

**Solution**
Use `info.dateStr` instead of `PrimeFaces.toISOString(info.date)`. FullCalendar has already converted them to the correct ISO string based on the configured `clientTimeZone`. There is no need to have `PrimeFaces#toISOString` to convert them.
```
L135: var currentDate = dateClickInfo.dateStr;
L283: {name: $this.id + '_start', value: fetchInfo.startStr},
L284: {name: $this.id + '_end', value: fetchInfo.endStr}
```

**Comment by melloware** [comment]
CC @christophs78 @blutorange

**Comment by melloware** [comment]
@BalusC thanks for reporting i know this has been a problem in the past with these dates we will investigate and get back to you.

**Comment by melloware** [comment]
These fixes break the Integration Tests with this error...
```
SEVERE: Text '2021-08-29' could not be parsed at index 10
java.time.format.DateTimeParseException: Text '2021-08-29' could not be parsed at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.Instant.parse(Instant.java:395)
	at org.primefaces.util.CalendarUtils.toLocalDateTime(CalendarUtils.java:576)
	at org.primefaces.component.schedule.Schedule.queueEvent(Schedule.java:104)
	at org.primefaces.behavior.ajax.AjaxBehaviorRenderer.decode(AjaxBehaviorRenderer.java:55)
	at javax.faces.component.behavior.ClientBehaviorBase.decode(ClientBehaviorBase.java:63)
```

We are always expecting to PARSE and ISO string for these dates...

```java
Instant instant = Instant.parse(isoDateString);
```

**Comment by melloware** [comment]
@BalusC I simply updated my PR to no do the offset when converting the ISO string.  Can you review? https://github.com/primefaces/primefaces/pull/7892

**Comment by BalusC** [comment]
Yes, that worked equally fine for me. Go ahead :)

**Comment by melloware** [comment]
Going to revert for now.  Too many side effects reported by users.  Sorry!

**Comment by christophs78** [comment]
We need to spend more time reading https://fullcalendar.io/docs/timeZone, debugging and testing different settings.
We already have fullcalendar/moment-timezone included.

**Comment by melloware** [comment]
Agreed.  @tuerker let's use this ticket to track all future conversations and investigations.

**Comment by BalusC** [comment]
Yikes.

Probably only use toISOString when clientTimeZone is unspecified.

**Comment by melloware** [comment]
Yep we are going to take a deeper dive into it for 12.0 and write some more integration tests.
