### ISSUE TITLE
SpeedDial: add Badge support

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#7898]
See https://www.primefaces.org/showcase-ext/sections/fab/customContent.jsf and #7855

**Comment by melloware** [comment]
@mertsincan would like your opinion here on the best way to add Badge support to SpeedDial since we have that functionality in PrimeFaces Extensions FAB.

**Comment by jepsar** [comment]
Let me paste my Discord messages (also involves positioning):

Has anyone tried to use a SpeedDial in their project? I feel it does not play nicely with other components.
Probably because it is not fixed (positioning).
I think it would be useful to have some kind of wrapper. This can help to position the SpeedDial and makes positioning a badge doable.
Badge is a different problem. I don't think you can wrap a SpeedDial in it. Well, you could, but positioning the Badge is terrible / impossible.
Maybe something like:
```xhtml
<pe:floating position="bottom right">
    <p:badge value="1"/>
    <p:speedDial>
        <p:menuitem .../>
    </p:speedDial>
</pe:floating>
```

**Comment by jepsar** [comment]
I think we should introduce a for attribute to badge and position it using JavaScript

**Comment by jepsar** [comment]
Actually JavaScript is also tricky, as the position of the component the badge is linked to can change position due to interaction with other components on the page or zooming. How about this: add a for attribute to badge and check for certain component types in the renderer. If the type is speed dial, badge will not render itself, but speed dial will. The badge can be inserted at a convenient position in the DOM and can be positioned by the speed dial CSS.

**Comment by jepsar** [comment]
A for attribute is no good for delegated rendering. The order of components would matter.

**Comment by mertsincan** [comment]
Hi,

I think we can add a badge attribute to SpeedDial. Exp;
```
<p:speedDial badge="string | BadgeOptions" ... />

1) <p:speedDial badge="5" ... />
2) <p:speedDial badge="#{bean.myBadgeOptions}" ... />

bean;
private BadgeOptions myBadgeOptions;
myBadgeOptions.setValue("5");
myBadgeOptions.setSeverity("info");
...

BadgeOptions;
// all attributes of p:badge

SpeedDialRenderer;
if (speedDial.getBadge() != null) {
    // we can wrap button with the structure of p:badge. BadgeRenderer.encodeEnd 
}
else {
   // current behaviour
}
```

OR

```
<p:speedDial ...>
      <p:badge ... />
      // menuitems
</p:speedDial>
```

Note: the first suggestion is OK for me. The second suggestion might be a bit confusing for the dynamic menu structure.

WDYT?

**Comment by tandraschko** [comment]
if BadgeOptions has only 2 vars, lets better introduce 2 attributes on speedDial

**Comment by mertsincan** [comment]
Currently, the badge has the following attributes and this may increase in the future. Maybe :D
```
public enum PropertyKeys {
        value,
        severity,
        size,
        style,
        styleClass,
        visible
 }
```

**Comment by jepsar** [comment]
We could also let the speeddial render the badge, see https://github.com/primefaces/primefaces/pull/7922

**Comment by jepsar** [comment]
Or create a badge model.
```xhtml
<p:speedDial badge="#{bean.badgeModel}">
  ...
</p:speedDial>
```
or
```xhtml
<p:badge model="#{bean.badgeModel}">
  <p:commandButton .../>
</p:badge>
```

**Comment by jepsar** [comment]
Okay, so I opted to go for a BadgeModel. The only issue left is that we would need a wrapper in order to position the badge. And I think we need to push some classes from the `.ui-speeddial` div to the wrapper.

Apart from that we can use the wrapper to position the badge, it could also be used to optionally position the SpeedButton at a fixed position.

Please have a look at https://github.com/primefaces/primefaces/pull/7922

**Comment by melloware** [comment]
Looking good!

**Comment by jepsar** [comment]
PR is done (except for documentation)

**Comment by AzharMobeen** [comment]
Hi Everyone,

Anyone know how to use Speeddial in datatable ? WRT each row wise some actions. I have tried to use but it's showing blank column.

**Comment by mertsincan** [comment]
Hi @AzharMobeen,

SpeedDial has 'position:absolute'. You should add position: relative to columns' style.

Best Regards,

**Comment by AzharMobeen** [comment]
@mertsincan thanks for your reply.

I tried it's position stil not properly align, after alot of css changes I was able to align in column but still I'm not happy becuase of custom css changes. Ideally when we we want to use in column it should be done by himself as splitbutton is doing.

main css changes for:

- Direction.
- number of menu iteam
- size fo the main button
- ans so on.

**Comment by melloware** [comment]
@AzharMobeen can you post your CSS for others to see who may have the same use case?

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project showing your results would really help!

**Comment by jepsar** [comment]
@AzharMobeen please open a new issue for this

**Comment by AzharMobeen** [comment]
I'm preparing example but meanwhile could you please tell me the process I mean I should create seperate issue or in this chat we can continue ? 
What is the normal flow if I want to discuss any primefaces component ? 
How can I contribute to any component please share guide lines as well.

**Comment by AzharMobeen** [comment]
@jepsar Sure

**Comment by jepsar** [comment]
To discuss use https://forum.primefaces.org/viewforum.php?f=3&sid=4404edb5b273e9174e7c7c70597b3a54 or https://discord.com/channels/787967399105134612/787967662293909524 or simply open a new issue

To contribute see https://github.com/primefaces/primefaces/blob/master/CONTRIBUTING.md

**Comment by AzharMobeen** [comment]
@jepsar Thanks man
I have created [new issue](https://github.com/primefaces/primefaces/issues/8760) with [example project](https://github.com/AzharMobeen/primefaces-test).
