### ISSUE TITLE
SelectManyButton with p:ajax can't deselect options

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#790]
Since 5.2.11 (5.2.10 works fine, with 5.2.11 focus was added to the p:selectManyButton) a p:selectManyButton with an p:ajax which renders itself can't deselect options.
In our case we have to render the selectManyButton, because its required and it should get the 'ui-state-error' StyleClass.
ExampleCode:

``` xml
<h:panelGroup id="testGroup">
  <p:selectManyButton id="selectmanybutton" required="true"
    value="#{exampleBean.selectManyButton}">

    <f:selectItem itemValue="Option 1" itemLabel="Option 1" />
    <f:selectItem itemValue="Option 2" itemLabel="Option 2" />
    <f:selectItem itemValue="Option 3" itemLabel="Option 3" />
    <f:selectItem itemValue="Option 4" itemLabel="Option 4" />
    <f:selectItem itemValue="Option 5" itemLabel="Option 5" />

    <p:ajax event="change" process="@this" update="testGroup" />
  </p:selectManyButton>
  <p:message for="selectmanybutton" />
</h:panelGroup>
<p:commandButton value="Submit" update="testGroup" style="margin-top: 15px;" process="selectmanybutton" />
```

Steps: to reproduce:
1. Select an option
2. Try to deselect the selected Option
=> the Option doesn't get deselected and the component is not invalid.

**Comment by Dsleeper** [comment]
Is this also connected to #771?
