### ISSUE TITLE
ToggleSwitch: On/off icon

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#7901]
Is it possible to add icons like this?

![ToggleSwitch](https://user-images.githubusercontent.com/9448030/135524362-7bfe3ad8-60c3-4bd4-a3ab-3adf5408e0e0.jpg)

**Comment by aripddev** [comment]
I can do that by adding below lines to `toggleswitch.css`, and using primeicons.
But I think this component need to be more customizable like in `BooleanButton`.

```css
.ui-toggleswitch-slider {
  ...
  font-family: 'primeicons' !important;
}

.ui-toggleswitch-slider:before {
  ...
  content: "\e90b" !important;
}

.ui-toggleswitch-checked .ui-toggleswitch-slider:before {
  ...
  content: "\e909" !important;
}

**Comment by melloware** [comment]
I agree this is a nice touch to add.

**Comment by melloware** [comment]
What theme are you in?  I can't get mine to look like yours in the Saga theme...

![image](https://user-images.githubusercontent.com/4399574/146003936-422341f0-9b17-46ad-be7c-08b05b9ae273.png)

**Comment by jepsar** [comment]
This would definitely require theme changes

**Comment by melloware** [comment]
agreed i started to work on this and got stuck needing theme changes

i can submit what i have?

**Comment by jepsar** [comment]
Sure. I'm curious to see how the icon transition is animated. If there is no transition we could do something like https://github.com/primefaces/primefaces/pull/7969

**Comment by aripddev** [comment]
@melloware Sorry, I didn't see your previous message. First image is not from any PF theme. I captured it from GitLab.
And you are right, its look is not good. I tried it with Avalon template.

<img width="673" alt="Screen Shot 2022-01-24 at 22 09 04" src="https://user-images.githubusercontent.com/9448030/150848221-36b67e9d-4930-4f1b-8fd5-451a060ca97d.png">

**Comment by jepsar** [comment]
In general I must say that the circle is too small to contain icons. At normal text size the icon looks cramped. I feel it needs some padding. This could work if something like `size="large"` (like in `Avatar`) would be added.

**Comment by mertsincan** [comment]
I don't think there is a theme issue at this stage. First of all, an infrastructure should be prepared for this in the core. 
Also, other icon libraries should be examined and tested with :before features.

**Comment by jepsar** [comment]
@mertsincan did you see https://github.com/primefaces/primefaces/pull/8322? Isn't that the preparation you are talking about?
