### ISSUE TITLE
FileUpload: Unknown error trying to upload large file

### ISSUE THREAD

**Issue by bryaan** [primefaces/primefaces#7909]
**Describe the defect**
We are trying to use fileupload to upload a large 60Mb file.  It works for most users, but fails for some without any errors being thrown.  It seems the file never makes it to the server as the handleFileUpload method is never called.
Is there any debug options that can be set?

```
         <p:fileUpload id="fileUploadControl" oncomplete="PF('xmlUploadDialog').hide()"
                        listener="#{tankXmlUploadBean.handleFileUpload}" mode="advanced"
                        allowTypes="/(\.|\/)(xml|zip)$/" update=":mainForm:scriptTableId" multiple="true" />
```

**Reproducer**
Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your reproducer here. **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub. Please test with that before reporting a bug that may already be fixed.

**Environment:**
 - PF Version: 10.0.0
 - JSF + version: MyFaces 2.3.9
 - Affected browsers: ALL

**To Reproduce**

**Expected behavior**
A successful upload with handleFileUpload() being called.

**Example XHTML**
```html
<h:form id="frmTest">
            <p:fileUpload id="fileUploadControl" oncomplete="PF('xmlUploadDialog').hide()"
                        listener="#{tankXmlUploadBean.handleFileUpload}" mode="advanced"
                        allowTypes="/(\.|\/)(xml|zip)$/" update=":mainForm:scriptTableId" multiple="true" />
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
      public void handleFileUpload(FileUploadEvent event) throws Exception {
           ....
      }
}
```

**Comment by stolp** [comment]
You are probably hitting a limitation of your application container. The default maximum size Jetty permits is 200000 bytes.

**Comment by bryaan** [comment]
> You are probably hitting a limitation of your application container. The default maximum size Jetty permits is 200000 bytes.

How can I increase it?

It is working for most users so I don't think this is it.

**Comment by melloware** [comment]
What server are you using?  Are you using any kind of proxy in between like nginx or Apache in front too?

**Comment by melloware** [comment]
Will close unless OP returns with more information but most likely this is not a PF bug its a network, server, environment issue.

**Comment by bryaan** [comment]
@melloware 
Yes, we are using things in front of our PF app (Tank).  Browser -> NLB (network load balancer) -> Nginx -> Tomcat9 -> Tank

**Comment by melloware** [comment]
@bryaan then my money is on one ore more of those having an POST size limit on them.

**Comment by bryaan** [comment]
@melloware But it seems hard to say that's it when its only happening to one or two of our users.  We have `client_max_body_size 200m;` set in nginx so it doesn't seem to be the problem.

**Comment by melloware** [comment]
Yep but theirs or your network might be terminating the connection.  Depending on speed and timing.  Could be your load balancer terminating the connection after timeout etc.  So MANY places but I can guarantee you none of them are PrimeFaces that is causing the issue.

**Comment by melloware** [comment]
For example at one of my clients they used a BgIP F5 Loadbalancer and it was severing connections if longer than 60s.  We could never reproduce the problem in house because it was fast enough but some of our customers on slower networks were getting terminated.  We finally figured out the Load Balancer setting and increased it and then all of our customers reported everything was working again.
