### ISSUE TITLE
Primefaces v11.0.0-RC1 p:Carousel question

### ISSUE THREAD

**Issue by ingeniotechnologies** [primefaces/primefaces#7910]
I'm sorry I don't have a sample project, but was hoping to get quick pointers about how to go about using the new version of the Carousel.

I went ahead and downloaded the new version of primefaces by switching from:
    `implementation group: 'org.primefaces', name: 'primefaces', version: '10.0.0'`
to 
    `implementation group: 'org.primefaces', name: 'primefaces', version: '11.0.0-RC1'` in my gradle configuration

I noticed the property changes, so I modified them according to [Carousel example in PrimeFaces Showcase](https://www.primefaces.org/showcase/ui/data/carousel.xhtml?jfwid=4c0d6); but when I went to run the project, none of the image files show. 

I inspected the underlying html and noticed that the visibility property in `ui-carousel-item` is set to `hidden` and it doesn't scroll at all (buttons don't work).

It seems like I'm just missing a component or something simple. Are there any additional components that I need to download or a configuration setting in order to have it working 100%?

I'm using using java version: `1.8.0_291`

Thanks!

**Comment by melloware** [comment]
This is not the forum for help or questions please use Discord channel or the PF forums.

But I would say just follow the working Showcase example: https://www.primefaces.org/showcase/ui/data/carousel.xhtml
