### ISSUE TITLE
InputNumber: Pasting value using German locale causes error

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#7911]
**Describe the defect**
Copy/paste with CTRL+C/CTRL+V a value into a non empty InputNumber with German locale, without selecting the whole input causes the hidden input to get an incorrect number.
![img](https://user-images.githubusercontent.com/6900303/135723951-99c5b084-aaeb-4179-9860-77e56bc8f38a.png)

**Environment:**
 - PF Version: 11.0.0-RC1
 - Affected browsers: ALL

**To Reproduce**
1) Go to PrimeFaces Showcase for InputNumber: https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml
2) Change Locale to German
2.1a) CTRL+C and CTRL+V any number twice to the first field "No Configuration" without selecting the value
2.1b) The hidden value is now "0,00,"
or
2.2a) Copy any number with CTRL+C (for example 99,99 from a text editor)
2.2b) Put the focus into the field "Empty Display - Blank"
2.2c) Select the value with CTRL+A -> the symbol is not selected
2.2c) Paste the number with CTRL+V to the field
2.2c) CTRL+A again -> the hidden value is now "99.99,"

The "," at the end gets removed if blur is triggered, but if there is a keyup event on the field the incorrect value gets transmitted to the backing and causes a NumberFormatException in InputNumberRenderer.

**Expected behavior**
The hidden input field should always have a valid number, otherwise it could cause troubles if it gets transmitted to the backing.

**Comment by melloware** [comment]
Looks like it is this bug in AutoNumeric: https://github.com/autoNumeric/autoNumeric/issues/670

Can you read that ticket and verify if it is your issue?

**Comment by pfumi** [comment]
Yeah it seems to be exactly this issue. Is there a chance the InputNumberRenderer can handle this, maybe correct the invalid number? The line with `new BigDecimal(submittedValue);`  in `InputNumberRender#decode` leads to the error

**Comment by melloware** [comment]
It feels like a hacky workaround to the plugin.  We would have to hack on the JS side or the Java side.  It feels like a better hack on the JS side with a comment to remove when AutoNumeric fixes their issue.  I would also go an upvote that issue as well.

**Comment by melloware** [comment]
Also I am having trouble reproducing the issue with you steps above?  I must be missing something?

**Comment by pfumi** [comment]
Important is to have a locale with , as decimal separator like German. The focus also needs to stay on the field when pasting the value (a blur event removes the ,). A value needs to be preset and not selected. If pasting multiple times the comma is inserted or removed.
I tried in newest Chrome and Firefox.

**Comment by melloware** [comment]
Hmm yeah I did all of those steps. Made sure it was German Locale.  My hidden input always stays correct.  So there must be one piece of information I am missing.

I am trying this...

2.2a) Put the focus into the field "Empty Display - Blank"
2.2b) Select the value with STRG+A -> the symbol is not selected
2.2c) Copy/paste any number to the field
2.2c) STRG+A again -> the hidden value is now "99.99,"

**Comment by pfumi** [comment]
Hmm
You do it probably right, but you change the Locale in the Showcase on the right sight and select there German?
I copied a value I typed in e.g. Notepad for example 123,99 and then pasted into the field with the described steps above. Hmm I can't imagine what I else do special..

**Comment by melloware** [comment]
And when you say STRG+A that is my CTRL+A to select all the text in the box right?  And yes I picked German from the selector on the right.

**Comment by pfumi** [comment]
Yes CTRL+A to select all text.

**Comment by pfumi** [comment]
I updated my reproducer in the issue description. I mentioned also doing copy/paste with CTRL+C & CTRL+V.
Sorry if I didn't describe it precise enough, but it should be now complete.

**Comment by melloware** [comment]
I did your steps exactly and mine is still `99.00` in the hidden and not `99.00,` maybe it has to do with my US Keyboard or OS?

I am on Chome 94.0.4606.61 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/4399574/135761086-d7033b38-d0cf-48f1-b5a0-974946120b47.png)

**Comment by melloware** [comment]
Just to see if it fixes your issue can you try this MonkeyPatch..

```javascript
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.getValue = function() {
        var val = this.autonumeric.getNumericString();
        if (this.autonumeric.getSettings().allowDecimalPadding && val && parseInt(this.cfg.decimalPlaces, 10) > 0) {
            var decimalPlacesToPad;
            if (val.indexOf('.') === -1) {
                decimalPlacesToPad = this.cfg.decimalPlaces;
                val += '.';
            } else {
                var decimalPlacesAlreadyRendered = val.length - val.indexOf('.') - 1;
                decimalPlacesToPad = this.cfg.decimalPlaces - decimalPlacesAlreadyRendered;
            }
            while (decimalPlacesToPad-- > 0) {
                val += '0';
            }
        }
        // GitHub #7911 Autonumeric bug workaround
        if (val && val.endsWith(this.cfg.decimalCharacter)) {
            val = val.substring(0, val.length - 1);
        }
        return val;
    }
}
```

**Comment by pfumi** [comment]
I'm on Chrome Version 94.0.4606.71 (64-Bit), maybe it is the OS or keyboard I don't know why you can't reproduce it...
Your patch at least works. The "value fixed" in the console is your workaround.
![img](https://user-images.githubusercontent.com/6900303/135763175-619f37c0-bc80-4971-89b6-4cf128351bb5.png)

**Comment by melloware** [comment]
Thanks for testing I will submit this fix as a PR for 11.0.0.

**Comment by pfumi** [comment]
Thanks.
One suggestion, maybe make it nullsafe.
```
// GitHub #7911 Autonumeric bug workaround
        if (val && val.endsWith(this.cfg.decimalCharacter)) {
            val = val.substring(0, val.length - 1);
        }
        return val
```

**Comment by melloware** [comment]
Yep I was going to do exactly that!
