### ISSUE TITLE
SelectOneMenu: Selection of not escaped SelectItem shows the html-code

### ISSUE THREAD

**Issue by murphy85** [primefaces/primefaces#7919]
**Describe the defect**
When selecting an item inside a p:selectOneMenu component with a label containing html, the html is escaped, but it shouldn't.

**Environment:**
 - PF Version: 8.0.13
 - JSF + version: joinfaces 4.3.11 / jakarta.faces 2.3.16
 - Affected browsers: ALL

**To Reproduce**
Create a p:selectOneMenu component containing selectItems with html inside label.
Add itemLabelEscaped=false as attribute
Open webpage and select one list item
Same issue: #3466

**Expected behavior**
A selected, not escaped selectItem should be display, formatted, not escaped.

**Example XHTML**
```html
<p:selectOneMenu>
     <f:selectItems value="#{controller.options}" itemLabelEscaped="false" />
</p:selectOneMenu>
```

**Example Bean**
```java
public List<SelectItem> getOptions() {
    List<SelectItem> list = new ArrayList<>();
    list.add(new SelectItem("bold", "<b>bold</b>", null, false, false));
    list.add(new SelectItem("italic", "<i>italic</i>", null, false, false));
    return list;
}
```

**Comment by melloware** [comment]
Have you tried this in 10.0.0 or 11.0.0-RC1 to make sure its not already fixed?

**Comment by melloware** [comment]
Works fine in 11.0.0-RC1.

```java
new SelectItem("Germany", "Germany"),
new SelectItem("Turkey", "<strong>Turkey</strong>", null, false, false),
new SelectItem("Spain", "Spain")
```

![image](https://user-images.githubusercontent.com/4399574/135887170-8b7f9c58-6843-4a1f-9586-a10d9bc3d3f7.png)

**Comment by murphy85** [comment]
I've tested with 8.0.5, 8.0.13 and 10.0.7
On drop down it's working fine, but after selection when it is collapsed, it shows the HTML code. I can test again tomorrow and send some screenshots.

**Comment by melloware** [comment]
Better yet... Provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by murphy85** [comment]
Sure, in about 12-15 hours. Meanwhile, have you tested to select bold Turkey and collapse the dropdown list?

**Comment by murphy85** [comment]
I've tested in my application and in test application. Test application is working, but my application not. I've tested with Primefaces 8.0.13 and 10.0.0
I found out there is a JS part in our scripts, where we extend SelectOneMenu.

I'm sorry for wasting your time.

**Comment by melloware** [comment]
thanks for reporting back.  Yep that is why the PrimeFaces Test reproducer is so critical for us...it helps users get to the root of the problem or non-problem.
