### ISSUE TITLE
primefaces extensions 8.0.4 | PF Elite 8.0.13 | layoutPane Toggler cannot be hidden

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#7924]
pe:layoutPane slider cant deactivated. is by attribute closable="false" slidable="false" always visible and usable.
It works perfectly with Primefaces 7.

**Environment:**
 - PF Version Elite: _8.0.13_
 - PF Extensions: 8.0.4
 - JSF Mojarra 2.1.29-11
 - javaEE: javaee-api 6.0
 - Affected browsers: Firefox, Chrome

**Example XHTML**
```html
        <pe:layout id="chefpanel" fullPage="true" style="padding: 0px;">
            <pe:layoutPane id="one" position="north" resizable="false" closable="false" slidable="false">
            </pe:layoutPane>
         </pe:layout>
</h:form>
```

**Comment by tandraschko** [comment]
please create a PrimeFacesExtensions issue, not PrimeFaces

**Comment by melloware** [comment]
Yes please create an issue here: https://github.com/primefaces-extensions/primefaces-extensions/issues

**Comment by StevenHachel** [comment]
Oh, sorry.

[new issue created](https://github.com/primefaces-extensions/primefaces-extensions/issues/574)
