### ISSUE TITLE
Column: getColumnKey() does not respect javax.faces.SEPARATOR_CHAR

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#7928]
**Describe the defect**
I have set javax.faces.SEPARATOR_CHAR to something different than the colon ":". I notice that the column filter does not work because Column.getColumnKey() doesn't work correctly, because getColumnKey() has the colon hardcoded:

```
public String getColumnKey(UIComponent parent, String rowIndex) {
     return getColumnKey().replace(parent.getId() + ":" + rowIndex + ":", parent.getId() + ":");
}
```

**Environment:**
 - PF Version: 11.0.0-RC1
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: ALL

**To Reproduce**
1. Set javax.faces.SEPARATOR_CHAR to something different than the colon ":".
2. Try column filtering, it won't work

**Expected behavior**
Column filtering works.

**Comment by melloware** [comment]
We should probably search the entire codebase for `:` and replace with this separator.

https://memorynotfound.com/jsf-change-default-separator-character/
