### ISSUE TITLE
SelectOneRadio Focus problem

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#793]
Reported by a PRO user;

if you want to select a radiobox from the oneRadio component with SPACE, the focus gets lost. Selecting with arrow keys is working fine.
The problem (or similar) is described here:
http://forum.primefaces.org/viewtopic.php?f=3&t=42794
You can test it in the oneRadio Showcase:
http://www.primefaces.org/showcase/ui/input/oneRadio.xhtml

**Comment by twinj** [comment]
It seems to me that the issue as described here  [http://forum.primefaces.org/viewtopic.php?f=3&t=42794](http://forum.primefaces.org/viewtopic.php?f=3&t=42794) is not fixed.

The change event is not being fired on SPACE BAR when it has focus and the key is pressed. It does look like it has been selected though.

I am using 5.3.5 and also checked 5.3.8 as an elite user.
