### ISSUE TITLE
GraphicImage: Add clientbehavior support

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#7943]
I noticed that `p:graphicImage` as well as `h:graphicImage` claim to support the following client-side events:
click, dblclick, keydown, keypress, keyup, mousedown, mousemove, mouseout, mouseover, mouseup

But when I try to add one, it does not get triggered.

**Comment by tandraschko** [comment]
Where did you read it?

**Comment by fcorneli** [comment]
This is returned as such by the `getEventNames()` method on the component.

**Comment by melloware** [comment]
When I look in `javax.faces.component.html.HtmlGraphicImage`...

it has:
```
onclick,
        ondblclick,
        onkeydown,
        onkeypress,
        onkeyup,
        onmousedown,
        onmousemove,
        onmouseout,
        onmouseover,
        onmouseup,
```

And we are rendering them on the image with 
```java
public static final List<String> IMG_ATTRS = LangUtils.concat(IMG_ATTRS_WITHOUT_EVENTS, COMMON_EVENTS);

renderPassThruAttributes(context, image, HTML.IMG_ATTRS);
```

So can you see the event rendered in your HTML and its just not being called?

**Comment by melloware** [comment]
I just did this and both events work find for me....

```xml
    <p:graphicImage value="#{graphicImageView.chart}" onclick="alert('test');"/>
    <p:graphicImage value="#{graphicImageView.chartAsByteArray}" onmouseover="alert('test');"/>
```

**Comment by tandraschko** [comment]
He is talking about behaviors like p:ajax
I dont think its really useful and also never implemented like this
I would use remoteCommand

**Comment by fcorneli** [comment]
Indeed, I'm talking about custom `ClientBehavior` tags.
The advantage over direct usage of `onclick="..."` is that you can add 
```java
@ResourceDependency(... your javascript file ...)
```
to the custom `ClientBehavior`, and thus you avoid situations where the developer forgets to put some
```xml
<h:outputScript library="whatever" name="whatever.js" target="head"/>
```
when he/she tries to use some function at `onclick="..."`. While this works for components like `p:commandButton`, it seems like `p:graphicImage` (and `h:graphicImage`) does not support this.

**Comment by fcorneli** [comment]
I find it rather strange that `ClientBehavior` is not more used. You can do ready interesting things with this. For example, instead of doing
```xml
<p:commandButton value="Dismiss" onclick="PF('myDialog').hide()"/>
```
all over the place within your dialogs, you could have:
```xml
<p:commandButton value="Dismiss">
    <p:closeDialog/>
</p:commandButton>
```
with the implementation as follows:
```java
import java.util.Optional;
import javax.faces.component.UIComponent;
import javax.faces.component.behavior.ClientBehaviorBase;
import javax.faces.component.behavior.ClientBehaviorContext;
import javax.faces.component.behavior.FacesBehavior;
import org.apache.commons.lang.StringUtils;
import org.omnifaces.util.Components;
import org.primefaces.component.confirmdialog.ConfirmDialog;
import org.primefaces.component.dialog.Dialog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@FacesBehavior("primefaces.closeDialog")
public class CloseDialogClientBehavior extends ClientBehaviorBase {

    private static final Logger LOGGER = LoggerFactory.getLogger(CloseDialogClientBehavior.class);

    @Override
    public String getScript(ClientBehaviorContext behaviorContext) {
        LOGGER.debug("getScript");
        UIComponent component = behaviorContext.getComponent();
        String dialogWidgetVar;
        Optional<Dialog> dialogOptional = Components.findClosestParent(component, Dialog.class);
        if (!dialogOptional.isPresent()) {
            Optional<ConfirmDialog> confirmDialogOptional = Components.findClosestParent(component, ConfirmDialog.class);
            if (!confirmDialogOptional.isPresent()) {
                LOGGER.warn("no parent p:dialog nor p:confirmDialogfound");
                return null;
            }
            ConfirmDialog confirmDialog = confirmDialogOptional.get();
            dialogWidgetVar = confirmDialog.getWidgetVar();
        } else {
            Dialog dialog = dialogOptional.get();
            dialogWidgetVar = dialog.getWidgetVar();
        }
        if (StringUtils.isEmpty(dialogWidgetVar)) {
            LOGGER.warn("dialog has no widgetVar");
            return null;
        }
        return "PF('" + dialogWidgetVar + "').hide()";
    }
}
```

**Comment by tandraschko** [comment]
i like it more to use JS directly instead of hide js/html more and more:
```<p:button onclick="PF('" + dialogWidgetVar + "').hide()";return false;" />```

**Comment by melloware** [comment]
@fcorneli interested in submitting a PR for this?

**Comment by fcorneli** [comment]
@melloware I've put it on my TODO list. :)

**Comment by melloware** [comment]
OK I assigned the ticket to you.  If you want it to make 12.0.0 I would submit the PR in the new few weeks.
