### ISSUE TITLE
DataTable: Payara IllegalArgumentException when using Array instead of List as selection value

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#7950]
**Describe the defect**
Multiple selection fails with an `IllegalArgumentException` using arrays as selection value for `DataTable`:

```
java.lang.IllegalArgumentException: Cannot convert [Ljava.lang.Object;@1a63f677 of type class [Ljava.lang.Object; to class [L<myClass>;
	at com.sun.el.lang.ELSupport.coerceToType(ELSupport.java:383)
	at com.sun.el.lang.ELSupport.coerceToType(ELSupport.java:339)
	at com.sun.el.parser.AstValue.setValue(AstValue.java:221)
	at com.sun.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:249)
	at org.jboss.weld.module.web.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
	at org.jboss.weld.module.web.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:95)
	at org.primefaces.component.datatable.feature.SelectionFeature.setSelection(SelectionFeature.java:248)
	at org.primefaces.component.datatable.feature.SelectionFeature.decodeMultipleSelection(SelectionFeature.java:153)
	at org.primefaces.component.datatable.feature.SelectionFeature.decodeSelection(SelectionFeature.java:89)
	at org.primefaces.component.datatable.feature.SelectionFeature.decode(SelectionFeature.java:69)
	at org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:74)
	...
```

**Reproducer**
Simply replace `List<Product> selectedProducts` by `Product[] selectedProducts` in the showcase.

**Environment:**
 - PF Version: _11.0.0-RC1_
 - JSF + version: _Mojarra 2.3.14.payara-p2_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to DataTable view with multiple selection enabled that uses an array internally
2. Select a row
3. See error

**Expected behavior**
No exception should be thrown

**Solution**
Undo the changes in file [org.primefaces.component.datatable.feature.SelectionFeature](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/datatable/feature/SelectionFeature.java) at method `setSelection(...)` that have been made since version 10.0:

_PrimeFaces 10.0 (working because `Array.newInstance(clazz.getComponentType(), selected.size()) ` is used which keeps the correct type)_

```
        Object selection = null;
        if (selected.isEmpty()) {
            if (multiple) {
                selection = isArray ? LangUtils.EMPTY_OBJECT_ARRAY : Collections.emptyList();
            }
        }
        else {
            if (multiple) {
                selection = isArray ? Array.newInstance(clazz.getComponentType(), selected.size()) : selected;
            }
            else {
                selection = selected.get(0);
            }
        }
```

_PrimeFaces 11.0.0-RC1 (not working because `selected.toArray()` is used which converts the selection to an array of objects)_

```
        Object selection = null;
        if (selected.isEmpty()) {
            if (multiple) {
                selection = isArray ? LangUtils.EMPTY_OBJECT_ARRAY : Collections.emptyList();
            }
        }
        else {
            if (multiple) {
                selection = isArray ? selected.toArray() : selected;
            }
            else {
                selection = selected.get(0);
            }
        }
```

**Comment by tandraschko** [comment]
@melloware @christophs78 would you like to create a unit test for it?

**Comment by christophs78** [comment]
I´ll create a integration test later this week.

**Comment by ltlBeBoy** [comment]
OK, I found out that there was also an exception when **sorting** the table even without selecting a row (because of `LangUtils.EMPTY_OBJECT_ARRAY`).

So here is an improved version of the method `SelectionFeature#setSelection(...)` that worked for me:

```
protected void setSelection(FacesContext context, DataTable table, boolean multiple, List<Object> selected, Set<String> rowKeys) {
        ValueExpression selectionVE = table.getValueExpression(DataTableBase.PropertyKeys.selection.toString());
        Class<?> clazz = selectionVE == null ? null : selectionVE.getType(context.getELContext());
        boolean isArray = clazz != null && clazz.isArray();

        if (multiple && clazz != null && !isArray && !List.class.isAssignableFrom(clazz)) {
            throw new FacesException("Multiple selection reference must be an Array or a List for DataTable " + table.getClientId());
        }

        Object selection = null;
        if (multiple) {
            if (isArray) {
                Object selectionArray = clazz != null ? Array.newInstance(clazz.getComponentType(), selected.size()) : selected.toArray();
                selection = selected.toArray((Object[]) selectionArray);
            }
            else {
                selection = selected;
            }
        }
        else if (!selected.isEmpty()) {
            selection = selected.get(0);
        }

        table.setSelectedRowKeys(rowKeys);

        if (selectionVE != null) {
            selectionVE.setValue(context.getELContext(), selection);
        }
        else {
            table.setSelection(selection);
        }
    }
```

**Comment by melloware** [comment]
These changes were done by @Rapster in this ticket #6575 "Fix #6575 - Datatable : Clean up selection (#6656)"

**Comment by Rapster** [comment]
I'll have a look, see what I can do

**Comment by melloware** [comment]
@Rapster can you review the above proposed changes?  Thanks!

**Comment by Rapster** [comment]
I'll check the issue first and see the proposal second

**Comment by christophs78** [comment]
See integrationtest - PR https://github.com/primefaces/primefaces/pull/7960
It does not fail.
And i can´t reproduce it by modifying http://localhost:8080/primefaces_showcase_war_exploded/ui/data/datatable/selection.xhtml.
@ltlBeBoy : Do i miss something? Or is there something else special on your side. It look like you use Weld, and we use OWB. (No sure whether this makes the difference.)

**Comment by ltlBeBoy** [comment]
@christophs78 I use Payara Server 5.2021.7. Maybe there is a problem when the selection array is going to be assigned to the typed array of the backing bean. I can try with a different application server, but I'm on vacation starting from tomorrow for two weeks. So it will take some time...

**Comment by melloware** [comment]
Payara is mojarra 2.3.14 so I doubt it's payara specific?

**Comment by tandraschko** [comment]
You can also try primefaces-test, you can start it with payara

**Comment by Rapster** [comment]
I confirm it's Payara specific... Have to figure out why now. My guess is that, coercion in Payara is not able to convert a Object[] to a Product[], so a Product[] has to be explicitely returned

**Comment by tandraschko** [comment]
maybe EL impl specific? you could try it by use glassfish/payara EL impl in primefaces-test
could be that tomcat EL coerces the array into a new array

**Comment by melloware** [comment]
We have our Payara branch of PrimeFaces Test ready to use out of the box: https://github.com/primefaces/primefaces-test/tree/payara

**Comment by tandraschko** [comment]
I know but with just switching the EL impl, we can check how its defined in specs

**Comment by tandraschko** [comment]
yep, glassfish EL doesnt implement array coerce:
https://github.com/javaee/el-spec/blob/master/impl/src/main/java/com/sun/el/lang/ELSupport.java#L380


whereas tomcat does:
https://github.com/apache/tomcat/blob/0827d1ce4200ad030a9c3496349b240fefeb53a7/java/org/apache/el/lang/ELSupport.java#L589

**Comment by tandraschko** [comment]
i added a EL spec issue and commited a fix
can you please try again?

**Comment by ltlBeBoy** [comment]
I tested with 11.0.0-RC2 and can confirm that it works.
