### ISSUE TITLE
DataTable: Sort is lost after data refresh

### ISSUE THREAD

**Issue by metaxmx** [primefaces/primefaces#7951]
**Describe the defect**
When using a DataTable with sortable columns, the sort order is lost after refreshing/replacing the underlying data model (List) in an AJAX request. The header still indicates the sorting in the column, but the data is no longer ordnered.
In PF 8.0 this still worked, but since 10.0 the sorting is no longer kept after the list is recreated.

Sometimes it is necessary to e.g. periodically update the displayed data from DB, but still keep the currently selected sorting.

**Environment:**
 - PF Version: 10.0.7 (also tested the current master 11.0.0-SNAPSHOT with commit 9ea38543)
 - JSF + version: Mojarra 2.3.9
 - Affected browsers: Firefox

**To Reproduce**
1. Display Datatable in a view
2. Sort by clicking a sortable header.
3. The data is correctly sorted by this column. THe column header indicates sorting.
4. Trigger reloading the data for this datatable by AJAX (and alos the update of the datatable), e.g. via a CommandButton
5. Now the table header still indicates that the data is sorted by this column. But the updated data is no longer sorted

**Expected behavior**
Even after a reloading of the data, I would expect the data in the table to be sorted by the column. This was also the behaviour in PrimeFaces 8.0.

**Example XHTML**
```html
<h:form>
    <p:dataTable value="#{dataBean.data}" var="data">
        <p:column headerText="Text" sortBy="#{data.text}">
            <h:outputText value="#{data.text}"/>
        </p:column>
        <p:column headerText="Number" sortBy="#{data.num}">
            <h:outputText value="#{data.num}"/>
        </p:column>
    </p:dataTable>
    <h:panelGroup>
        <p:commandButton value="Refresh" process="@this" update="@form" actionListener="#{dataBean.refresh}" />
    </h:panelGroup>
</h:form>
```

**Example Bean**
```java
@ViewScoped
@Named("dataBean")
public class DataBean implements Serializable {

    public static class Data {

        private final String text;

        private final int num;

        public Data(String text, int num) {
            this.text = text;
            this.num = num;
        }

        public String getText() {
            return text;
        }

        public int getNum() {
            return num;
        }
    }

    private List<Data> data;

    public List<Data> getData() {
        return data;
    }

    @PostConstruct
    public void refresh() {
        List<Data> newData = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            // Generate random letter and number to test sorting
            newData.add(new Data("Data " + ((char) ((int) 'A' + ThreadLocalRandom.current().nextInt(26))),
                    ThreadLocalRandom.current().nextInt(100)));
        }
        this.data = newData;
    }

}
```

**Comment by tandraschko** [comment]
any debugging and solution/ideas would be great
i dont have much time the next weeks

**Comment by melloware** [comment]
@metaxmx can you create a PrimeFaces Test reproducer please?  and then try it with `-Pmyfaces23` as well as `-Pmojarra23` this issue sounds familiar like it has already been identified as a Mojarra issue.

**Comment by melloware** [comment]
@metaxmx can you try this solution: https://github.com/primefaces/primefaces/issues/7845#issuecomment-922533263

**Comment by metaxmx** [comment]
Thank you for your feedback.
I have created a reproducer project: https://github.com/metaxmx/primefaces-reproducer-datatable-sorting
Unfortunately the problem was not specific to a jsf implementation. I tried it with Mojarra 2.2, Mojarra 2,3 and MyFaces 2.3. I've also seen this problem with Mojarra 3.0 in my JakartaEE project.

The "workaround" by additionally triggering `PF('myDataTable').filter()` does work, but obsiously is no feasibly solution as it triggers a new AJAX request and also needs to be added to all UI actions which refresh the datatable.

Another workaround that does work, is by binding the DataTable to a property of the bean, and calling `dataTable.filterAndSort();` whenever the underlying list is changed.
This is better, because it does not require an additional AJAX request, but still has the overhead of tracking all used data tables in the beans (which is a bad structure, as I want to separate the data from the UIComponents that render it).

I would consider this a regression, because the exact same setup works fine when I use PrimeFaces 8 instead of 10 (same setup, same Mojarra and AppServer version).
It seems like the new DataTable implementation loses track of when the data needs to be "re-sorted" (and also re-filtered when I see the linked issue concerning the filterBy attribute).
The re-sorting doesn't even seem to work, if I use `filteredValue="#{myBean.filteredList}"` and set the filteredList to null, when I overwrite the source list (which I believe was possible in the past).

I'd like to help with analysis and pull requests, but I'm not sure that I fully understand the underlying workings of the DataTable Sort- and Filter Feature yet, and I'm not sure that I currently have the time myself to dig into it right now...

**Comment by tandraschko** [comment]
it would a help a lot if you could collect some infos where and when the your changed data was sorted/filtered again

maybe @Rapster and @melloware could have a look too

**Comment by Rapster** [comment]
I see the problem. sort at initial rendering happens only if default sorting is set. Same issue happens with filtering I think

**Comment by Rapster** [comment]
Fixed it. Though, no idea why setRowIndex is called while it's not for filtering.

**Comment by metaxmx** [comment]
Thank you, this is great news!
I can confirm that this patch does fix the reported problem.

However, I was testing the DataTable sort and filter feature in my reproducer example for a bit, and I noticed another glitch:
When I sort by a column and simultaniously filter for a column, then the sorting does not seem to work any more, when I refresh the data.
I believe this happens due to the fact, that in the code the sorting is done first (probably on the `filteredData` list?), and then the filtering is done later, and overwrites the `filteredData` list again.
```java
if (table.isSortingCurrentlyActive()) {
    SortFeature.getInstance().sort(context, table);
    table.setRowIndex(-1); // why?
}

if (table.isFilteringCurrentlyActive()) {
    FilterFeature.getInstance().filter(context, table);
}
```
When I reverse these two actions, then it works as expected. Is there a reason not to do the filtering before the sorting? I believe it might also be more performant to do it this way, because the sorting is done on a smaller list ...

**Comment by metaxmx** [comment]
Another thing I'm not absolutely sure about:
The DataTable has a property `filteredValue`, which seems to behave like a kind of cache for the table filtering.
However, now the filtering (and also sorting) is performed every time the table is rendered, so the `filteredValue` is overwritten every time.
However, when you first set a filter (and by this get the `filteredValue` filled with a non-null value), and then remove the filter again, the `filteredValue` will still contain the stale value and consecutive changes to the underlying `value` list will not be recognized, unless the `filteredValue` is bound via expression binding to a bean, and set to null by hand. In all other cases (if either a filter is active, or never was active) this is not necessary.

So I wonder, if it would be helpfull to set the filteredValue to null, if no filtering is active, e.g.
```
if (table.isFilteringCurrentlyActive()) {
    FilterFeature.getInstance().filter(context, table);
} else {
    table.setFilteredValue(null);
}
```
(I'm not sure of this is the right place).
Or even, if the `filteredValue` is obsolete and should be removed totally, if now the filtering is done on each rendering anyways.

I believe, in the end the optimal workflow should be as follows:
* if no filtering and no sorting is active: use the current `value` list unaltered
* if filtering and/or sorting is active: use the current `value` list, and filter and sort it (topic of the current ticket)
* if filtering and/or sorting is active, and the underlying list did not change: use the previously filtered/sorted value of the list (this would require the use of `filteredValue`, and also requires being able to compare the previously seen `value` to the current value of the ValueExpression for the `value` property - see #7845)

So if we could achieve the third/last bullet point, the usage of the DataTable component would be much easier, because there was no need to declare the `filteredValue` property by hand, because the DataTable would take care of everything.
However, if there is no easy way that the DataTable could track changes of the underlying list, I would still hope that it is possible to use the DataTable and can change the `value` list, without also binding and manipulating the `filteredValue` every time the `value` changes.

**Comment by tandraschko** [comment]
that are some questions for @Rapster, he did the most of the refactoring

**Comment by christophs78** [comment]
You can work-around this issue with

```java
DataTable dataTable = (DataTable) FacesContext.getCurrentInstance().getViewRoot().findComponent("form:datatable");
dataTable.filterAndSort(); //work-around to keep sort-order
```

see https://github.com/primefaces/primefaces/pull/8012/files#diff-9a1a7c83649160d4969b7118145c45d87ee414e2676498299c3b38ef99a32a7fR72-R88

**Comment by tandraschko** [comment]
i will also switch filter/sort now like in @metaxmx comment
please create a new issue about your second big comment

**Comment by tandraschko** [comment]
@Rapster @christophs78 could it be that
`table.setRowIndex(-1); // why?`
is a similar "hack" like 
` setDataModel(null); `
in DataTable#filterAndSort?

**Comment by Rapster** [comment]
Yeah, both does more or less the same thing. But not clear as to when, why and which one to use it... Since this call is quite expensive, we should be careful how we use it. IMO, that setRowIndex should be called in SortFeature just like FilterFeature does

**Comment by jepsar** [comment]
> Seems that this issue came back in PF 12 (we're using 12.0.4). Can someone confirm?

@gunnarschmid This is the issue tracker for the community version of PrimeFaces. We (the community) cannot fix issues in Elite versions of PrimeFaces. Can you please check if this issue is present in version 13?

See also: https://github.com/primefaces/primefaces#community--elite--pro

**Comment by gunnarschmid** [comment]
Ah, right, sorry. I will raise an issue via our subscription.

**Comment by gunnarschmid** [comment]
We ran further tests with PF13 and localized the problem: the sort order is lost when using dynamic columns.
This can be reproduced with the showcase project: in `org.primefaces.showcase.view.data.datatable.ColumnsView.updateColumns()` add this line to recreate the underlying data:
    `customers = service.getCustomers(10);`
Then open the page /showcase/ui/data/datatable/columns.xhtml, sort by one column and hit the Update button, you will notice that the sort order is lost.

**Comment by melloware** [comment]
If I remember @gunnarschmid the issue with that example is every request generates a new random set of Customers with Random ID's?

**Comment by gunnarschmid** [comment]
> If I remember @gunnarschmid the issue with that example is every request generates a new random set of Customers with Random ID's?

Yes. In our real application we have a search form and then display the search results in a datatable. The sort order shall be kept when we execute a new search (so totally different underlying data). This used to work in PF8, and does not work anymore since PF10 - I thought that this issue solved it, but apparently it didn't.

**Comment by melloware** [comment]
if you can provide a PrimeFaces Test reproducer we can investigate.

**Comment by gunnarschmid** [comment]
What do you mean? I described how to reproduce in https://github.com/primefaces/primefaces/issues/7951#issuecomment-1753056480

**Comment by melloware** [comment]
You described it but without a PrimeFaces Test reproducer how can we debug it?  I can't reproduce your issue so that is why I need you to prove the issue with a runnable PrimeFaces Test runner. See https://github.com/primefaces/primefaces-test

**Comment by gunnarschmid** [comment]
Here you go: https://github.com/gunnarschmid/primefaces-test

**Comment by melloware** [comment]
@gunnarschmid thank you!  Can you open a new ticket and include your reproducer and also mention this original ticket please?
