### ISSUE TITLE
DataTable: Table is empty when virtualScroll="true"

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#7954]
**Describe the defect**
`DataTable` is empty when attribute `virtualScroll` is set to `true`.

**Reproducer**
See _[Virtual Scrolling - 20000 Rows](https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml)_ in showcase.

**Environment:**
 - PF Version: _11.0.0-RC1_
 - JSF + version: _Mojarra 2.3.14.payara-p2_
 - Affected browsers: _ALL_

**To Reproduce**
See _[Virtual Scrolling - 20000 Rows](https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml)_ in showcase.

**Comment by tandraschko** [comment]
where is it in our showcase?

**Comment by ltlBeBoy** [comment]
Edit: I added the link to the showcase.

**Comment by melloware** [comment]
Updated PR to fix it correctly.

**Comment by tandraschko** [comment]
Can you also add a simple Test pls?

**Comment by melloware** [comment]
Yep

**Comment by ltlBeBoy** [comment]
I tested with 11.0.0-RC2 and can confirm that it works.
