### ISSUE TITLE
SelectBooleanButton: Labels always are rendered per default

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7963]
**Describe the defect**

I think I have detected a regression in the way the p:selectBooleanButton implementation in 11.0.0-RC1 is handling the onLabel and offLabel attributes.

Previously in version 10.0.0, when adding onIcon and offIcon attributes the onLabel and offLabel attributes default to empty strings and the result is an icon-only button.

In 11.0.0 the default localized labels (On/Off) are always used.

The workaround is to set the onLabel and offLabel attributes explicitly to empty strings to get an icon-only SelectBooleanButton.
This feels awkward.

Is this new behavior the intended one? If yes it probably should be added to the migration notes.

**Reproducer**
Will add if required.

**Environment:**
 - PF Version: _11.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Render a p:selectBooleanButton with onIcon and offIcon attributes and without onLabel and offLabel attributes.

**Expected behavior**
No change in behavior in regard to 10.0.0 is expected.

**Comment by melloware** [comment]
It was fixed with this ticket: https://github.com/primefaces/primefaces/issues/7222

**Comment by melloware** [comment]
You are right Showcase even shows the problem.

https://www.primefaces.org/showcase/ui/input/booleanButton.xhtml?

**Comment by melloware** [comment]
Good catch I added an integration test as well and fixed the issue.  Please review my PR.
