### ISSUE TITLE
DataExporter: Option to globally suppress table header/footer export

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7964]
**Description**
In my application, I like to see footers in some of my UI tables, but never in the corresponding exports (XLSX, PDF and XML).

I'm always frustrated when I have to rewrite my custom exporters for each new major PrimeFaces release as each new version brings a more sophisticated API (Nonetheless I really like the work done there!).

I am aware of the `exportFooterValue` attribute in p:Column, but this is not overly helpful due to the sheer amount of columns in use.

**Describe the solution you would like**
I like to have boolean exportFooter and exportHeader attributes on the DataExporter element which globally disables footer and header export.

It would also be great if defaults are sensible here:

PDF: exportFooter='false' exportHeader='true'
XLSX/XSL: exportFooter='false' exportHeader='true'
XML: exportFooter='false' exportHeader='false'

**Comment by melloware** [comment]
This is a great suggestion but since its a new feature and not a bug this will have to wait for 12.0.0

**Comment by melloware** [comment]
@stolp it looks like the XML Exporter doesn't use header or footer facet at all?  You have it marked above as false but it looks like it never uses them anyway can you confirm what you mean?

**Comment by melloware** [comment]
Ahh i see XML looks like it never uses the footer but it uses the Header if NO `exportHeader` is found on the column so it can render the XML tag correctly.

```xml
protected String getColumnTag(UIColumn column) {
        String headerText = (column.getExportHeaderValue() != null) ? column.getExportHeaderValue() : column.getHeaderText();
        UIComponent facet = column.getFacet("header");
        String columnTag;

        if (headerText != null) {
            columnTag = headerText.toLowerCase();
        }
        else if (ComponentUtils.shouldRenderFacet(facet)) {
            columnTag = exportValue(FacesContext.getCurrentInstance(), facet).toLowerCase();
        }
        else {
            throw new FacesException("No suitable xml tag found for " + column);
        }

        return EscapeUtils.forXmlTag(columnTag);
    }
```

I am hesitant about adding it to XML exporter as you can already override this with the headerText or exportHeaderValue on the column

```
 String headerText = (column.getExportHeaderValue() != null) ? column.getExportHeaderValue() : column.getHeaderText();
```

**Comment by melloware** [comment]
OK please see my PR.  I did not touch XML exporter.

**Comment by stolp** [comment]
Thanks @melloware. I will check this over the weekend.

**Comment by stolp** [comment]
Just for the record to clarify my point regarding XML-Export of tables:

An XML-Format export should typically only consist of the table data and no added header/footer information to allow proper consumption in other tools. It just doesn't make sense to have extra records here.

My apologies, I may have missed that this is no longer the case here, although I have a hunch that is was present in PrimeFaces 8.

From my look at the patch, this should solve the issue just fine, I will validate this again once merged.

The only gripe left I have with XML-Export is the problem described in [https://forum.primefaces.org/viewtopic.php?t=69217](https://forum.primefaces.org/viewtopic.php?t=69217). It is in almost any case confusing to not have a common tag name available here.

Having a closer look at the issue list it seems I omitted to raise a new bug for this. If it is ok, I will do this now.

**Comment by melloware** [comment]
Please do open a new issue!

**Comment by stolp** [comment]
Thanks, I opened #8205 for this.
