### ISSUE TITLE
DataExporter: Option to ignore columns which are hidden via ColumnToggler

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#7966]
**Describe the defect**
**Description**
Data exporters will always export all rendered, exportable columns but not columns excluded via ColumnToggler.
This is confusing for users who may want to tune their table content before exporting.

In the past, I have added checks to my custom exporters for column visibility (isVisible()). I'm always frustrated when I have to rewrite my custom exporters for each new major PrimeFaces release as each new version brings a more sophisticated API (Nonetheless I really like the work done there!).

**Reproducer**
Will follow.

**Environment:**
 - PF Version: _11.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Exclude columns via ColumnToggler
2. Export the table
3. Notice excluded columns appearing in the output

**Expected behavior**
Data exporters should omit columns which are hidden via ColumnToggler.
Perhaps this should be added via an additional attribute to be backwards compatible here.

**Comment by melloware** [comment]
I think this has come up in the past and it seemed like this might be a user choice.  Similar to how we export PageOnly or All rows.  I can see some users who want to hide columns on the UI but want the full data exported.  So i am gonna mark this an enhancement not defect.

**Comment by melloware** [comment]
I decided against option and just made it the sensible default to not export `visible="false"` columns.  It makes sense it should export what's visible on your screen.

**Comment by melloware** [comment]
OK changed my mind again and made a `visibleOnly` option which is `false` by default.

**Comment by stolp** [comment]
I like the solution, as it is backwards compatible and does not surprise users with a different behavior.
