### ISSUE TITLE
CellEdit: DataTable triggers AutoNumeric by mouseover or mouseout

### ISSUE THREAD

**Issue by enricokl** [primefaces/primefaces#7967]
**Describe the defect**
If a InputNumber is in a editable DataTable, then the AutoNumeric was triggered by mouseover or mouseout. A InputNumber without DataTable triggers AutoNumeric only if focus lost (by Tabulator or click mouse out).

**Environment:**
 - PF Version: _8.0_, _10.0_
 - Affected browsers:  Tested in _Firefox 78.15.0esr_, _Microsoft Edge 94.0.992.47_

**To Reproduce**
1. Click on Cell
2. Edit Input Field only with integer value (e.g. 22)
3. Move Mouse out or in input

**Expected behavior**
The InputNumber filles the decimal values only, if the input field loses the focus

**Example XHTML**
```html
<h:form id="frmTest">
  <p:dataTable value="#{modelView.models}"
                     editMode="cell"
                     var="model"
                     editable="true">
            <p:column headerText="InputNumber CellEditor">
                <p:cellEditor>
                    <f:facet name="output"><h:outputText value="#{model.value}"/></f:facet>
                    <f:facet name="input"><p:inputNumber value="#{model.value}"/> </f:facet>
                </p:cellEditor>
            </p:column>
        </p:dataTable>
        <br/>
        <p:inputNumber value="#{modelView.value}"/>
</h:form>
```

**Example Bean**
```java
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;


@ManagedBean
@ViewScoped
public class ModelView {

   private final List<Model> models = new ArrayList<>();
   private       double      value  = 14.14;

   @PostConstruct
   void fill() {
      models.add(new Model(10.00));
   }

   public List<Model> getModels() {
      return models;
   }

   public double getValue() {
      return value;
   }

   public void setValue(final double value) {
      this.value = value;
   }
}

```
```java
public class Model {

   private double value;

   public Model(final double value) {
      this.value = value;
   }

   public double getValue() {
      return value;
   }

   public void setValue(final double value) {
      this.value = value;
   }
}

```

**Comment by melloware** [comment]
I will investigate.

**Comment by melloware** [comment]
I believe this is fixed in 11.0.0-RC1 if you go to the Showcase and edit the Price field: https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

Can you check this issue: https://github.com/primefaces/primefaces/issues/7460

Or this one: https://github.com/primefaces/primefaces/issues/6397

**Comment by ranger88** [comment]
Thank you for your quick response. In the Showcase 11.0.0-RC1 in "Cell Editing with Click and RightClick" is the problem also.
I will check the issues #7460 and #6397 on monday.

**Comment by enricokl** [comment]
Thank you for your quick response. In the Showcase 11.0.0-RC1 in "Cell Editing with Click and RightClick" is the problem also.
I will check the issues #7460 and #6397 on monday.

**Comment by melloware** [comment]
Oh yep I see it now!   My guess is its https://github.com/primefaces/primefaces/issues/7460

**Comment by melloware** [comment]
try adding `emptyValue="empty"` to your InputNumber.  The defalt value is `emptyValue="focus"` which you don't want.

**Comment by melloware** [comment]
Definitely looks like an Autonumeric bug.

**Comment by enricokl** [comment]
I have tried all possible values for emptyValue, but the problem still persists.

**Comment by melloware** [comment]
@enricokl me too, I definitely think its an AutoNumeric bug.  PrimeFaces doesn't even have a mouseout event defined so this is happened inside of AutoNumeric.

**Comment by enricokl** [comment]
@melloware: Do you know a workaround or do you know an "easy" way to override that?

**Comment by melloware** [comment]
I looked but I didn't see anything obvious in the AutoNumeric code and its quite complex.  I also didn't see an open ticket on their GitHub about it so it must be something specific to this example.  Because the Example not using CellEdit Right click it doesn't happen.  So I feel like its some Jquery event added by the Context Menu right click example that is triggerin it?

**Comment by melloware** [comment]
Yep it happens on the Right Click and Double click cell events but not on the top example Row Editing.  So now I am thinking Primefaces is adding some Jquery event to those CellEdit cells that is triggering the AutoNumeric.

I am looking at Chrome at all the events attached and here is the focus:
![image](https://user-images.githubusercontent.com/4399574/137724431-a08d0a58-e371-4add-a83b-79ae3643dbf8.png)

If you click "Remove" on the 4th one down which is from Jquery..everything works the way you expect.  What I can't figure out is where that focus event listener is coming from?

**Comment by melloware** [comment]
I can't reproduce this in the latest showcase.  @enricokl i will re-open if you say its still an issue in 13.0.0 but I can't seem to make it happen.
