### ISSUE TITLE
MenuItem: support passthrough attributes

### ISSUE THREAD

**Issue by torstenwerner** [primefaces/primefaces#7970]
**Describe the defect**

Sample xhtml code with `xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"`:

    <p:menuitem value="Neuer Ordner" update="folderTree" action="#{folderTreeView.addNewNode}"
        oncomplete="openInplace(args)" icon="fa fa-plus"
        onkeydown="test()" pt:onkeydown="test2()" pt:data-test3="test4"/>

The rendered DOM has neither a `onkeydown` event handler defined nor a custom attribute `data-test3`.

    <li class="ui-menuitem ui-widget ui-corner-all" role="none"><a tabindex="-1" role="menuitem"
                                                               class="ui-menuitem-link ui-corner-all" href="#"
                                                               onclick="PrimeFaces.ab({s:&quot;folder-tree:treeform:j_idt17&quot;,f:&quot;folder-tree:treeform&quot;,u:&quot;folder-tree:treeform:folderTree&quot;,onco:function(xhr,status,args,data){openInplace(args);}});return false;"><span
        class="ui-menuitem-icon ui-icon fa fa-plus" aria-hidden="true"></span><span class="ui-menuitem-text">Neuer Ordner</span></a>
    </li>

**Reproducer**

Add the menuitem sample to any application and check the rendered DOM.

**Environment:**
 - PF Version: _10.0.0_
 - JSF + version: _Mojarra 2.3.16_
 - Affected browsers: _ALL_

**To Reproduce**
1. Add the menuitem sample to any application.
2. Check the rendered DOM.

**Expected behavior**
I expected to be able to define custom event handlers and custom attributes as it is possible for other components.

**Comment by tandraschko** [comment]
new feature as not implemented before

**Comment by tandraschko** [comment]
a PR would be great!

**Comment by melloware** [comment]
MenuIten is a UICommand and not a UIComponent so I don't think this feature can be implemented.  I am not sure it's even worth trying to change MenuIten for this.  Going to close for now.

**Comment by melloware** [comment]
Sorry thanks to @Rapster i realized this can be done and quite easily.
