### ISSUE TITLE
DataTable: splitButton not rendered if items are not rendered 

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#7971]
**Describe the defect**
A splitButton is set as paginatorTopLeft facet in a DataTable. This splitButton has no visible children, and due to `ComponentUtils#shouldRenderFacet` impl., splitButton is not rendered.

**Reproducer**
```xml
<p:dataTable var="row" value="#{dtBasicView.products}">
    <f:facet name="paginatorTopLeft">
        <p:splitButton value="Save" action="#{buttonView.save}" update="messages" icon="pi pi-save">
            <p:menuitem value="Update" action="#{buttonView.update}" update="messages" icon="pi pi-refresh" rendered="false" />
        </p:splitButton>
    </f:facet>

    <p:column field="code" headerText="Code" sortable="false" filterable="false" />
    <p:column field="name" headerText="Name" />
    <p:column field="category" headerText="Category" />
    <p:column field="quantity" headerText="Quantity" />
</p:dataTable>
```

**Environment:**
 - PF Version: 11.0
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**Expected behavior**
SplitButton is visible with his only one action. FYI, it could happen with any command kinda component

**Comment by tandraschko** [comment]
hmmm
shouldnt this work anyway?
splitButton is rendered=true, therefore it should NEVER be skipped, indepdent of UICommand or any other component

**Comment by Rapster** [comment]
Nope, the idea of this method is to decide whether or not a UIPanel (used by Mojarra not sure about MyFaces) should be rendered depending its children. But in case of a single component, it returns the component itself (in this case, a splitButton)

**Comment by tandraschko** [comment]
i think then we have to check the initial idea and impl again

AFAIR it should only check:
dont render facet when facet.rendered=false or all children of the facet are rendered=false

**Comment by Rapster** [comment]
I think the addition that I recently made is good enough. The tricky part of this method is that it works on two different levels, a facet can be either a container (then check comp.children.rendered) or a single component (check comp.rendered). Though, in case of a MenuButton, it can make sense to not display it if children are not displayed

**Comment by tandraschko** [comment]
i currently prepare some tests, lets talk again after that

**Comment by tandraschko** [comment]
just put some tests, which my assumptions, how this method should work
one test even fails currently

which are other cases, which should be covered currently?

**Comment by Rapster** [comment]
UIPanel containing at least one component, SplitButton, MenuButton (if you agree that displaying an empty MenuButton is not really useful)

**Comment by tandraschko** [comment]
i dont see that shouldRenderFacet ever checks the children-childs like p:menuitem in your case?

**Comment by tandraschko** [comment]
could it be that the facet param of the method is the SplitButton in your case?
then our handling is complete wrong, it should really only be the facet instance, not a children

**Comment by Rapster** [comment]
> i dont see that shouldRenderFacet ever checks the children-childs like p:menuitem in your case?

It does in shouldRenderChildren method, since p:menuitem is a child

> could it be that the facet param of the method is the SplitButton in your case?

yes

>then our handling is complete wrong, it should really only be the facet instance, not a children

not sure if we understand each other, but as I said, if one component defined then the facet is the component (e.g splitbutton) otherwise it's a UIPanel. That's how JSF impls handle it, facet is not systematically a container of children

**Comment by tandraschko** [comment]
i currently debug it and if the facet is empty, its just null:
```
<f:facet name="paginatorTopLeft">

</f:facet>
```

**Comment by Rapster** [comment]
Yeah makes sense, I didn't mention that one (never happened to me so far)

**Comment by tandraschko** [comment]
IMO the method is currently wrong implemented in general
i will come up with a idea in 10 mins

**Comment by tandraschko** [comment]
```
    public static boolean shouldRenderFacet(UIComponent facet, boolean alwaysRender) {
        // no facet declared at all or facet without any content
        if (facet == null) {
            return false;
        }

        // user wants to always render this facet so it can be updated
        if (alwaysRender) {
            return true;
        }

        // the facet contains multiple childs, so its wrapped inside a UIPanel
        // NOTE: we need a equals check as instanceof would also catch e.g. p:dialog
        if (facet.getClass().equals(UIPanel.class)) {
            // For any future version of JSF where the f:facet gets a rendered attribute
            if (!facet.isRendered()) {
                return false;
            }

            // check all childs - if all of them are rendered=false, we skip rendering of the whole facet
            return shouldRenderChildren(facet);
        }

        // the facet contains only one child now, which means that the facet is the child component
        // we dont want to check children, just if the component is rendered=true
        return facet.isRendered();
    }
```

actually we also switch the first 2 ifs but we need some null checks then in the caller-code

**Comment by Rapster** [comment]
Looks good

**Comment by tandraschko** [comment]
commited, please review and retest your case
