### ISSUE TITLE
DataTable: Dynamic Columns with rendered attribute breaks filter/sort functionality

### ISSUE THREAD

**Issue by BryanV91** [primefaces/primefaces#7986]
**Describe the defect**

Trying to upgrade from PF8 to PF10, but I'm having issues with the rendered attribute in `p:columns`. It shows/hides columns properly, but it breaks the filter/sort functionality.

**Reproducer**

Reproducer attached.

**Environment:**

 - PF Version: _10.0_
 - JSF + version: _Mojarra 2.2.20 and MyFaces 2.3.9_
 - Affected browsers: _Chrome and Firefox_

**To Reproduce**

Navigate to `test.xhtml` and add/remove `rendered="#{column.rendered}"` to check the behaviour.

**Expected behavior**

Filter/Sort functionality should work with rendered attribute.

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7368200/primefaces-test-master.zip)

**Comment by Rapster** [comment]
I provided a fix but don't think it's a really clean solution, but it gives an idea where the problem comes from. @tandraschko should have a good opinion on this

**Comment by tandraschko** [comment]
@melloware @christophs78 anyone interessted or time to create a test for it?

**Comment by melloware** [comment]
Yep I think we can modify an existing Dynamic Columns Test.  Let me see if I can provide.

**Comment by melloware** [comment]
Integration test provided and the rendered attribute break multiple tests currently which is good.
