### ISSUE TITLE
CLI: PrimeFlex migration migrates `p-sr-only`

### ISSUE THREAD

**Issue by Wandmalfarbe** [primefaces/primefaces#7996]
**Describe the defect**

When executing the migration tool for the PrimeFlex migration, the CSS class `p-sr-only` is replaced with the class `sr-only`. This is not correct because `p-sr-only` is a part of PrimeNG and not PrimeFlex.

**Environment:**
 - PF Version (CLI): 11

**To Reproduce**

1. Go into a project with HTML files that have PrimeFlex 2 classes in them.
2. Execute the PrimeFlex migration with `java -cp "primefaces-cli-x.x.x.jar" org.primefaces.cli.migration.primeflex.PrimeFlexMigration c:\projects\myapp -e=html`

**Expected behavior**

When executing a migration, the class `p-sr-only` will stay as it is. It will not be changed to `sr-only`.

---

I create a PR for this issue in #7995

**Comment by melloware** [comment]
Thank you for your issue and PR!
