### ISSUE TITLE
ColorPicker: Incorrect Translation of Inputs

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#7997]
**Describe the defect**

 I have a user complaining that some colors are not selectable and I confirmed even on the showcase : https://www.primefaces.org/showcase/ui/input/colorPicker.xhtml
If you try to input `RGB 0,48,108` or its hex value `00306C` you get `0,49,108` and `00316C`.
Not sure what happens here but I was expecting an input color to input my color without altering it ! 
after digging into colorPicker.js it looks like it always ends up setting values from HSB conversion, no mater where the user is updating value. 

```javascript
if (ev) {
                    fillRGBFields(col, cal.get(0));
                    fillHexFields(col, cal.get(0));
                    fillHSBFields(col, cal.get(0));
                }
```

where col is the HSB version of the selected color

**Comment by melloware** [comment]
Looks like it is this issue: https://github.com/thorst/jQuery-ColorPicker/issues/1

**Comment by melloware** [comment]
Updated to more accurate calculation of conversion functions.

See: https://stackoverflow.com/questions/17242144/javascript-convert-hsb-hsv-color-to-rgb-accurately

![image](https://user-images.githubusercontent.com/4399574/138271892-99b7d778-d32f-4c6a-a9ff-af69208d7bc1.png)

**Comment by jepsar** [comment]
I'd like to see a picker based on https://github.com/mdbassit/Coloris

Add an issue to PFE to add it there?

**Comment by tandraschko** [comment]
which plugin does PrimeNG or Vue use?

**Comment by jepsar** [comment]
Looks like PrimeTek homegrown on PrimeNG as far as I can judge https://github.com/primefaces/primeng/blob/master/src/app/components/colorpicker/colorpicker.ts

**Comment by tandraschko** [comment]
then please create a issue here for PrimeTek, so they can port it for the next releases

**Comment by jepsar** [comment]
Ok. But I'll add a ticket to PFE as well. The keyboard support on Coloris is great!

**Comment by melloware** [comment]
Reverting this as its broken it fixed HSB but broke normal color selection.  Switching to Coloris for PF12 is the way to go. :)
