### ISSUE TITLE
AutoComplete: Paginator Support

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#8]
Enable paginator support for autocomplete to handle huge list of suggestions.

**Comment by shayegh** [comment]
please add this feature to user components.
this is so important feature
thanks

**Comment by dariorios** [comment]
I agree. Is completely needed

**Comment by Rapster** [comment]
`maxResults` and `moreText` should be enough. To handle huge list, well, let's the end user be more accurate, in case of SQL, it'd be bad design to do an autocomplete with the full result set, THEY have to support pagination in their SQL request not autocomplete

**Comment by melloware** [comment]
Agreed with @Rapster and none of the other Prime Libs support this feature.
