### ISSUE TITLE
Option to show all records via rowsPerPage in Paginator

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#80]
Extend the DataTable paginator to allow for an entry in the rows-per-page-list that displays all entries (e.g. "10,50,100,All").

Possible ways to use it:
p:dataTable rowsPerPageTemplate="10,50,100,All" /
p:dataTable rowsPerPageTemplate="10,50,100,*" /
p:dataTable rowsPerPageTemplate="10,50,100" rowsPerPageAllEntry="true" /
or any other good and intuitive syntax.

philipp.keck

**Comment by sudheerj** [comment]
Added a pull request #996 by notifying all records with "*" symbol

**Comment by tandraschko** [comment]
Thanks sudheer, please also create a issue for the documentation
