### ISSUE TITLE
Customized selectCheckboxMenu label

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#800]
Hi all,

I would like that you considere to add one facet to the selectCheckboxMenu component, it will help us to customize the label attribute adding html code, for example:

```
<p:selectCheckboxMenu ...>
  <f:facet name="label">
    <span class="classOne">Properties:</span> #{bean.selectedProperties} 
  </f:facet>
</p:selectCheckboxMenu>
```

I could add the pull request if you accept this issue.

Thanks.

**Comment by cagataycivici** [comment]
Can't we do a labelTemplate="Selected: {value}" as selections are dynamic

**Comment by tandraschko** [comment]
I dont understand the exact requirement. I will close it for now. Please consider to create a new ticket and fill all requested informations in the issue template.
