### ISSUE TITLE
DataTable: All columns are missing in table exports when a "draggable=true" attribute is present

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#8005]
**Describe the defect**
When the data table attribute `draggable=true` is present, a different path through the `TableExporter.getExportableColumns()` method is taken, which is leading to the effect, that no exportable column will be found. 

This is due to the fact, that now columnMeta information is present in the dataTable which columnKey slightly differs from the columnKey of the column in the table.

 In that case meta.getColumnKey() aka columnKey yields something like "table:index:colName" whereas col.getColumnKey() yields "table:columnName".

This is the code in question:
```
            for (ColumnMeta meta : columnMetas) {
                String columnKey = meta.getColumnKey();
                for (UIColumn col : allColumns) {
                    if (col instanceof DynamicColumn) {
                        ((DynamicColumn) col).applyStatelessModel();
                    }
                    if (col.getColumnKey().equals(columnKey)) {
                        if (col.isRendered() && col.isExportable()) {
                            exportcolumns.add(col);
                        }
                        break;
                    }
                }
            }
```

There are several ways to fix this, probably stripping the column index before comparison is the correct one here.
I gladly provide a pull-request once this has been clarified.

**Reproducer**
Clone repository https://github.com/stolp/primefaces-test/tree/PF-8005 in order to reproduce the problem.

**Environment:**
 - PF Version: _11.0_
 - JSF + version: _Mojarra 2.2.20_
 - Affected browsers: _ALL_

**To Reproduce**
1. Open Reproducer
2. Click on any export button
3. Open export file
4. See that column information is missing

**Expected behavior**
Columns should be exported.

**Comment by melloware** [comment]
Hmm I would say stripping the index is the easiest fix here but will defer to @tandraschko @Rapster

**Comment by tandraschko** [comment]
IMO Exporter should use forEachColumn anyway

**Comment by melloware** [comment]
@tandraschko great idea, switched to `forEachColumn`

**Comment by melloware** [comment]
@stolp can you pull this branch and test. I tested it with draggableColumns="True" and it seems to work for me but don't know your exact scenario.

**Comment by tandraschko** [comment]
and about columnKey and rowIndex, please check ColumnAware `String getColumnKey(UIComponent parent, String rowKey);`

**Comment by melloware** [comment]
I am getting very strange results.  With your reproducer the CSV example works fine but XML is printing nothing.  But they all call the same methods which is really strange. Still investigating

**Comment by melloware** [comment]
Great hint @tandraschko . This fixed it `String columnKey = col.getColumnKey((UIComponent) table, ((UIData) table).getRowIndex());` I tested all of the scenarios in this ticket and went back and tested EVERY showcase exporter example and all are working properly.

**Comment by stolp** [comment]
I tested this in my application as well and it is now working as expected. Thanks a lot.
