### ISSUE TITLE
LazyDataModel getRowData and getRowKey make function interfaces difficult

### ISSUE THREAD

**Issue by jamestenglish** [primefaces/primefaces#801]
With Java 8 functional interfaces it would be really nice to put something like this on all my data models:

https://gist.github.com/jamestenglish/995ace320996d3213a3b

However, because getDataRow and getRowKey aren't abstract the functional interface won't override them. Making them abstract or moving them into another class lower on the class hierarchy would help alleviate this issue.

**Comment by cagataycivici** [comment]
@tandraschko What do you think?

**Comment by tandraschko** [comment]
Makes absolutely sense!
If a user extends LazyDataModel, he must actually implement #load, #getRowData and #getRowKey.
Or do i miss a special case?

**Comment by tandraschko** [comment]
@melloware thanks for the reminder in gitter :D
I'm not sure if i understand it corretly. IMO the repoter did it correct and made his own subclass, for his own abstract model?!

**Comment by melloware** [comment]
I am not quite sure either, maybe @jamestenglish will chime in.

**Comment by tandraschko** [comment]
I will close it for now, not sure if someone is still interessted after 4 years :D
we can still reopen
