### ISSUE TITLE
Custom message when file content validation fails on file upload

### ISSUE THREAD

**Issue by lgaspa** [primefaces/primefaces#8016]
**Description**
I have a `FileUpload` with `validateContentType=true` I would like to display a custom message to the client. Currently the upload quietly does nothing. The mode of my file upload is `advanced` but it is the same with `simple` mode. I am working with PF `8.0.0`.

**Describe the solution you would like**
It would be great if you could set a custom message when the file type validation fails, just as with `invalidSizeMessage`.

**Additional context**
```           
if (FileUploadUtils.isValidFile(context, fileUpload, uploadedFile)) {
    fileUpload.setSubmittedValue(new UploadedFileWrapper(uploadedFile));
}
```
This code snippet is from `NativeFileUploadDecoder#decodeAdvanced`. I think somewhere in this vicinity it should be fairly easy to set a custom message to display in the client. Maybe you could also reuse the `validatorMessage`, as this would be good enough and the logic already exists somewhere.

**Comment by melloware** [comment]
@lgaspa isn't this already possible?

Fixed: https://github.com/primefaces/primefaces/issues/5594

The catch adds a FacesContext message...

```java
catch (VirusException | ValidatorException e) {
                setValid(false);
                context.addMessage(getClientId(context), new FacesMessage(FacesMessage.SEVERITY_ERROR, e.getMessage(), null));
            }
```

And depending on your Virus Scanner its customizable with the server property files. For example here is the ITalian translations depending on which virus scanner you are using..

```
primefaces.fileupload.CLAM_AV_FILE = ClamAV ha identificato il file '{0}' come potenzialmente dannoso con messaggio '{1}'
primefaces.fileupload.VIRUS_TOTAL_FILE = Virus Total ha identificato il file '{0}' come potenzialmente dannoso
```

**Comment by lgaspa** [comment]
You are right, this seems to solve my problem. However since I'm stuck with PF `8.0` I think this does not help me. I'll just verify the file type when the uploading is done.
Thanks for your time!
