### ISSUE TITLE
CLI: Migrate alternative justify content classes e.g. `p-justify-end`

### ISSUE THREAD

**Issue by Wandmalfarbe** [primefaces/primefaces#8018]
When executing the migration tool for the PrimeFlex migration, the CSS class `p-justify-end` is not migrated. There are other classes like this that are not migrated:

1. `p-justify-start`
2. `p-justify-end`
3. `p-justify-center`
4. `p-justify-between`
5. `p-justify-around`
6. `p-justify-even`

These classes are strangely undocumented in the [primeflex 2.0.0 documentation](https://primefaces.org/primeng/showcase/#/primeflex/flexbox) but are present in the [primeflex 2.0.0 source code](https://github.com/primefaces/primeflex/blob/44daba597e4c5475e5365e391fb7aa84e0ce0fda/primeflex.css#L691). They are also rarely used in the documentation itself https://github.com/primefaces/primeng/search?q=p-justify-end

These classes are duplicated in primeflex. They are present as `p-justify-end` and `p-jc-end`. Here's a comparison:

**`p-justify-end` in primeflex 2.0.0**

```css
.p-justify-end {
  -webkit-box-pack: end;
  -ms-flex-pack: end;
  justify-content: flex-end;
}
```

**`p-jc-end` in primeflex 2.0.0**

```css
.p-jc-end {
  justify-content: flex-end;
}
```

The only differences are the vendor prefixes. It would be beneficial for a project using `p-justify-end` that the CLI migrates theese justify-content-classes to the new classes like it is already done for `p-jc-end`:

1. `p-justify-start` -> `justify-content-start`
2. `p-justify-end` -> `justify-content-end`
3. `p-justify-center` -> `justify-content-center`
4. `p-justify-between` -> `justify-content-between`
5. `p-justify-around` -> `justify-content-around`
6. `p-justify-even` -> `justify-content-evenly`

**Environment:**

- PF Version (CLI): 11
- PrimeFlex Version: 2.0.0 (migration to 3.1.0)

**To Reproduce**

1. Go into a project with HTML files that have PrimeFlex 2 classes in them.
2. Execute the PrimeFlex migration with `java -cp "primefaces-cli-x.x.x.jar" org.primefaces.cli.migration.primeflex.PrimeFlexMigration c:\projects\myapp -e=html`

**Expected behavior**

When executing a migration, the class `p-justify-end` will be migrated to `justify-content-end`.

---

I have created the pull request #8017 to fix this issue.

**Comment by melloware** [comment]
Excellent description and PR. I will merge once the build completes!
