### ISSUE TITLE
deploy all-themes and other theme artifacts to maven central repository.

### ISSUE THREAD

**Issue by ravshansbox** [primefaces/primefaces#802]
deploy all-themes and other theme artifacts to maven central repository, so we can omit extra repository declaration.

**Comment by tandraschko** [comment]
@melloware why is this invalid? IMO it makes sense.

**Comment by melloware** [comment]
@tandraschko My thought was Primefaces offers all of this in their repo.  Most organizations are using Nexus to front all their repo's so adding another repo is not that big of a deal.   Having it in central would be nice but it has been years since this was requested I figured it was invalid.

**Comment by tandraschko** [comment]
Thats not true for 100%.
We also deploy the primefaces.jar to maven central.

**Comment by melloware** [comment]
Linking to Theme Issue: https://github.com/primefaces/themes/issues/9
