### ISSUE TITLE
ChartJS: With migration to ChartJS 3.0, legend options don't work anymore (because namespace has moved)

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#8028]
**Describe the defect**
With PF 11.0.0-RC1, the pie chart legend position="right" doesn't work anymore, because the namespace for legend has changed.
The ChartJS migration guide (https://www.chartjs.org/docs/latest/getting-started/v3-migration.html) describes this:
- _legend, title and tooltip namespaces were moved from options to options.plugins_

**To Reproduce**
Try:
```
PieChartModel result = new PieChartModel();
Legend legend = new Legend();
legend.setPosition("right");
...
options.setLegend(legend);
```

**Expected behavior**
The legend is shown on the right.

**Actual behavior**
The legend is shown on the top.

**Workaround**
With an extender functions and using the correct namespace (plugins), it can be fixed.
```
options = {
    options: {
	    plugins: {
		    legend: {
			    position: "right"
		    }
	    }
    }
};
```

**Comment by melloware** [comment]
Thank you for reporting.  Fixing it now!

**Comment by joergmattes** [comment]
You're welcome, thanks a lot for fixing.
