### ISSUE TITLE
DataExporter: columnToggler breaks export ordering

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8031]
@melloware In the latest 11.0.0 snapshot (as well as on a snapshot from September 27), the csv datatable export seems to be broken. The exported column order is incorrect. See example:

![Screenshot from 2021-10-30 03-00-44](https://user-images.githubusercontent.com/10051373/139514699-b25f5516-9e62-44fe-91a7-5126edfd2d1f.png)

**Comment by tuerker** [comment]
there is also a problem with exporting datatables that contain grouped columns. the exorted file is always empty. here i need to provide a reproducer since the show case which invokes the exporter with a commandButton outside of the datatable seems to work. in our datatable fragment the export link is paginator template.
```

<p:datatable ...
      paginatorTemplate="{CurrentPageReport} #{(paginatorLinks ne 'none') ? '{JumpToPageInput} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}' : ''} #{(rowsPerPageDropdown ne 'none') ? '{RowsPerPageDropdown}' : ''} #{(exporters == null or exporters) ? '{Exporters}' : ''}"
...
      <f:facet name="{Exporters}">
        <h:panelGroup id="exporters">
            <p:commandLink value="#{messages.exportCSV}">
              <p:dataExporter
                type="csv"
                target="#{tableContext}#{tableType}table"
                fileName="#{tableContext}_#{tableType}#{exportSuffix}" />
             </p:commandLink>
          </h:panelGroup>
      </f:facet>

```

**Comment by melloware** [comment]
Please provide PrimeFaces Test reproducers for both issues.

Also for your second issue `{exporters}` are you sure your issue isn't this: https://github.com/primefaces/primefaces/issues/7060

Using the Showcase I can't reproduce your first issue.  Everything is coming out the proper order.

**Comment by tuerker** [comment]
here is the reproducer for the second issue. 

[p-dataexportercsv-grouped.zip](https://github.com/primefaces/primefaces/files/7447727/p-dataexportercsv-grouped.zip)

it concerns the csv export which requires flattening of the table. instead of

"group1","col2","g11","g12","g13","c2"
"","","1","2","3","4"

it should be something like this:

"g11","g12","g13","c2"
"1","2","3","4"

would be great to have the grouped column headers but i am not aware whether this is even possible in csv.

**Comment by tuerker** [comment]
for the first issue i could not get the reproducer right. 

[p-dataexporter.zip](https://github.com/primefaces/primefaces/files/7447743/p-dataexporter.zip)

the problem occurs when the columnToggler is used within the exporters facet. in my own code the columnsToggler works as expected while the csv export messes up columns and rows. 

in the "reproducer" above, the csv export is correct but the toggler does not work. 

it looks like that it is not intended to use the columnToggler together with the exporters?
maybe you can give me a hint how to solve this issue. many thanks in advance.

**Comment by tuerker** [comment]
below you will an extended reproducer for the second issue with the grouped column export problem.

[p-dataexportercsv-grouped.zip](https://github.com/primefaces/primefaces/files/7448639/p-dataexportercsv-grouped.zip)

it shows that the xls export is also not working as expected.

many thanks in advance.

**Comment by melloware** [comment]
OK so two things both your examples have in common are dynamic columns and `{exporters}`.  So I think the issue is related to that combination.

**Comment by melloware** [comment]
OK it seems both your scenarios work fine if you remove the `facet name="{Exporters}"` and do it with buttons above the table.

So it definitely related to the `{Exporters}`.

**Comment by melloware** [comment]
And to answer your question no I do not think the ColumnToggler should not be used inside the exporters facet.

**Comment by melloware** [comment]
I prefer to put the column toggler in the Table header like this rather than trying to cram it into Exporters....

```xml
<f:facet name="header">
	<p:commandButton id="btnColumnToggle" type="button" value="#{webmsg['label.columns']}"
					style="float:right;" styleClass="column-toggler" icon="fa fa-columns" />
	<p:columnToggler datasource="tblAuditTrail" trigger="btnColumnToggle">
			<p:ajax event="toggle" listener="#{auditTrailDatatable.columnToggle}" />
	</p:columnToggler>
</f:facet>
```

**Comment by tuerker** [comment]
Thanks for looking into. I prefer using the column toggler in the Exporters since this approach has the advantage that one saves the space above the table (in case the table header is not used at all - as in all of our tables).

**Comment by tuerker** [comment]
I have now tested the toggler in the table header. It has exactly the same behavior as in the Extporters.
So the issue occurs when both exporters and toggler are used together in the table.

**Comment by melloware** [comment]
Yep its all related I believe to `{exporters}`.

**Comment by djmj** [comment]
In my observations `<p:columnToggler>` breaks the export just on itself even if the toggler is not in the facet (ours is in the header) or even when the exporter is outside the table and no custom facet is used at all.

I can confirm both behaviors in different tables one not keeping the correct ordering of columns and one not exporting data at all.

**Comment by melloware** [comment]
@djmj @tuerker  I can't reproduce. We use ColumnToggler and Exporters on all our tables in our production app without issue.  Can someone provide me a reproducer for 11.0.0 that shows the problem without the use of `{exporters}`??

**Comment by tuerker** [comment]
@melloware this issue contains actually two issues.

1) there is the problem with the export of the grouped columns: exporting grouped column is definitively NOT working correctly as shown in the reproducer above p-dataexportercsv-grouped.zip. also in this reproducer the export button/link was in the exporters, it also not working when the export button/link is outside of the table:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
  <title>PrimeFaces Test</title>
  <h:outputScript name="test.js" />
</h:head>
<h:body>

  <h1>Test DataExporter</h1>
  <h:form id="form">
    <p:commandButton value="csv" styleClass="p-mr-2 p-mb-2">
      <p:dataExporter
        type="csv"
        target="carTable"
        fileName="carTableExport" />
    </p:commandButton>
    <p:commandButton value="xls" styleClass="p-mr-2 p-mb-2">
      <p:dataExporter
        type="xls"
        target="carTable"
        fileName="carTableExport" />
    </p:commandButton>

    <p:dataTable var="car" value="#{dtLazyView.lazyModel}" paginator="true" rows="10" id="carTable" widgetVar="carsTable"
                 paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}">
      <p:columnGroup type="header">
        <p:row>
          <p:column colspan="3" headerText="group1" />
          <p:column headerText="col2" />
        </p:row>
      </p:columnGroup>

      <p:column headerText="g11">
        <h:outputText value="1" />
      </p:column>
      <p:column headerText="g12">
        <h:outputText value="2" />
      </p:column>
      <p:column headerText="g13">
        <h:outputText value="3" />
      </p:column>
      <p:column headerText="c2">
        <h:outputText value="4" />
      </p:column>
    </p:dataTable>
  </h:form>
</h:body>
</html>
```

2) the second problem was that the exported column order was wrong when the columntoggler was used. see the reproducer p-dataexporter.zip above. 

@melloware i am currently on holidays without the (technical) possibility to provide further reproducers.

**Comment by tuerker** [comment]
@melloware the issue with the grouped column export seems to be fixed with https://github.com/primefaces/primefaces/issues/8241.

for the other issue, i have now prepared another reproducer which hopefully will help to identify the problem. 

[p-dataexporter-2.zip](https://github.com/primefaces/primefaces/files/7854825/p-dataexporter-2.zip)

it is definitively not caused by

facet name="{Exporters}"

the columnToggler is causing the trouble! 

therefore, i would rename this issue. 

many thanks for looking into it again.

**Comment by tuerker** [comment]
add-on: issue based on 12.0.0-snapshot as of yesterday evening.

**Comment by melloware** [comment]
Yep I have noticed it too while I was working on the visible fix.  Its definitely the ColumnToggler.

**Comment by koan00** [comment]
We are also experiencing this issue when migrating from PF 8.0.15 to 11.0.1. 

@melloware are you working on a fix for this? If not, what would be the best way to address this? 

Based on just reading the source, it looks like TableExporter.getExportableColumns might be the culprit: https://github.com/primefaces/primefaces/blob/38c62b7eb8acf8aa5663be43b19e8a14c16f7bae/primefaces/src/main/java/org/primefaces/component/export/TableExporter.java#L100 We want to fall into the "if (columnMetadata == null || columnMetadata.isEmpty()) " branch, but because we have column meta due to the toggler setting column visible meta data, we do have meta data, just not priority meta data. Should an additional check be added here to check to see if there are any columns with priority set?

**Comment by melloware** [comment]
@koan00 sure please submit a PR!

**Comment by koan00** [comment]
@melloware I was going to submit this:  https://github.com/koan00/primefaces/commit/5ba6aa226a3967bb1e569f5f872d085f8d2e69f7 , but I then during more testing I noticed that exporting with displayPriority set was not working (display priority is honored in UI, but not in export). However I just reverted my change and tested further. It looks like exporting with displayPriority was already broken and not a regression from my commit. 

It looks like columnMeta.getDisplayPriority() is always returning null, but the code expects it to be set.

**Comment by melloware** [comment]
hmmm let me look through tickets i thought that was fixed at one point

**Comment by melloware** [comment]
@koan00 i found this: https://github.com/primefaces/primefaces/issues/7324

**Comment by koan00** [comment]
@melloware thanks. After a lot of experimenting and testing, it seems that table.getColumnMeta() is not good to use here. First, it doesn't actually seem to contain any priority information. It's always null. Second, its a map and iterating over it does not iterate over the columns in the same order they are in the markup. So even if you had a mix of priorities (say -1,0,0,0,0,1). The zeroes would be not match the UI presentation. 

Using table.forEach gives us the columns in the order as written in the markup, and allows us to look up the priority reliably. 

I tested with:
- Toggler and no priorities
- Toggler and mix of priorities and no priorities columns
- No Toggler and no priorities
- No Toggler and mix of priorities and no priorities columns

**Comment by melloware** [comment]
Excellent but also test with a mix of exportable=false and visible also to make sure exportable=false always get excluded

**Comment by melloware** [comment]
@koan00 looking good so far but left you a couple of review comments.

**Comment by koan00** [comment]
> Excellent but also test with a mix of exportable=false and visible also to make sure exportable=false always get excluded

exportable=false is working. 

visible=false is partially working, but again it appears to be an issue with the original implementation. If visible=false is set in the xhtml, it is working. However if you use the visibility toggler to change column visibility, the export does not update. column.isVisible always seems to return the initial value. (Note that I do have a p:ajax inside the toggler to make sure the update gets back to the server. Mutli View state does persist the change as expected).

Edit for completeness : also tested column reordering with a <p:ajax event="colReorder"/>. Multi View state does persist the change. Export does not pick up the change.

**Comment by melloware** [comment]
I think its because the Column Toggler is just using JS magic to hide columns not updating the backing bean.  There may be an AJAX event you can use to update the server side?

**Comment by melloware** [comment]
Actually it looks like it only works on MultiViewState?  https://github.com/primefaces/primefaces/issues/2491

**Comment by koan00** [comment]
> I think its because the Column Toggler is just using JS magic to hide columns not updating the backing bean. There may be an AJAX event you can use to update the server side?

Yes, that is why I mentioned in my previous comment that I add a p:ajax under the columnToggler. Toggler is totally client side unless you add it, and multiViewState won't persist the column toggle w/out the nested ajax tag.

```
<p:columnToggler datasource="xxxxDataTable" trigger="toggler">
    <p:ajax />
</p:columnToggler>
```

If multiViewState has the proper table state to persist across views, then I assume it should be available to us to use in the exporter. I am just not familiar enough with the code to see how to access it.

**Comment by koan00** [comment]
@melloware This affects the 11.x branch as well. What is the process to get it back-ported? It's not a direct merge due to the exporter changes to omit non-visible columns.

**Comment by melloware** [comment]
That is up to PrimeTek (I don't work for PrimeTek).  If you have a PRO account you can request this ticket be backported to 11.x

**Comment by koan00** [comment]
Alright, I'm not pro so I just patched it myself. If anyone is interested, here it is: https://github.com/koan00/primefaces/commit/0a7c6489ac733b91ddc3b19b0dba78224e21194b
