### ISSUE TITLE
Tree: dynamic,selection attribute not working

### ISSUE THREAD

**Issue by kronos72it** [primefaces/primefaces#8034]
**Describe the defect**
Using Tree component with dynamic= true prevent to call the method specified via selection attribute 

```xml
             <p:tree id="costTree" value="#{viewComplete.costRoot}" var="node" selectionMode="single"
                                        selection="#{viewComplete.costSelected}" dynamic="true" >
                        <p:ajax event="select" update=":form:costSelValore :form:costSelDescr :form:buttonCost" listener="#{viewComplete.onNodeSelect}" process="@this"/>
                        <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                            <h:outputText value="#{node.value}"/>
                        </p:treeNode> 
                    </p:tree>
```

Then when I select a node in the tree , the method below will be run but with NULL as argument

```java
public void setCostSelected(TreeNode costSelected) {
        this.costSelected = costSelected;
    }
```

**Environment:**
 - PF Version: _10.0.6
 - JSF + version: _e.g. Mojarra 3.0.0
 - Affected browsers:  ALL_

**To Reproduce**
1. Create a simple tree with dynamic = true and a correct dynamic model.set attribute selection= bean.method (all as above reported). Create a method inside the bean  (all as above reported) .
2. Click on a node of tree
3. whatch break point on method 
4. check the TreeNode argument inside method and see it is NULL

**Expected behavior**
the argument on the method must be valrized as the node selected on the page 

**Example XHTML**
```xml
<p:tree id="costTree" value="#{viewComplete.costRoot}" var="node" selectionMode="single"
                                        selection="#{viewComplete.costSelected}" dynamic="true" >
                        <p:ajax event="select" update=":form:costSelValore :form:costSelDescr :form:buttonCost" listener="#{viewComplete.onNodeSelect}" process="@this"/>
                        <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                            <h:outputText value="#{node.value}"/>
                        </p:treeNode> 
                    </p:tree>`
```

**Example Bean**

```java
public void setCostSelected(TreeNode costSelected) {
        this.costSelected = costSelected;
    }
```

**Comment by melloware** [comment]
@FlipWarthog any interest in investigating?

**Comment by FlipWarthog** [comment]
@melloware Can do

**Comment by kronos72it** [comment]
thanks both , if I can help in some way ... 

A detail : I implemented the LazyLoadingTreeNode as reported in PF showcase 

`/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package savino.hb.web.faces;

import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import savino.hb.common.entity.CostType;
import savino.hb.web.controller.CompleteController;

/**
 *
 * @author Administrator
 */
public class LazyCostTreeNode extends DefaultTreeNode {
    Logger logger=LoggerFactory.getLogger(LazyCostTreeNode.class);
    private Function<CostType, List<CostType>> loadFunction;
    private boolean lazyLoaded;

    public LazyCostTreeNode(CostType data, Function<CostType, List<CostType>> loadFunction) {
        super(data);
        this.loadFunction = loadFunction;
        logger.info("NEW NODE : "+data);
    }

    @Override
    public List<TreeNode> getChildren() {
        lazyLoad();

        return super.getChildren();
    }

    @Override
    public int getChildCount() {
        lazyLoad();

        return super.getChildCount();
    }

    @Override
    public boolean isLeaf() {
        lazyLoad();

        return super.isLeaf();
    }

    private void lazyLoad() {
        if (!lazyLoaded) {
            lazyLoaded = true;

            CostType parentId = getData()==null ? null :((CostType) getData());

            List<LazyCostTreeNode> childNodes = loadFunction.apply(parentId).stream()
                    .map(f -> new LazyCostTreeNode(f, loadFunction)).collect(Collectors.toList());
            super.getChildren().addAll(childNodes);
        }
    }
}
`

**Comment by FlipWarthog** [comment]
This might already be fixed. There was a lot of refactoring done to Tree and its related code between v10 and v11.

Here's a primefaces-test proj setup with 11.0.0-RC1 and it doesn't show the behavior described above.
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/7456816/primefaces-test.zip)

@kronos72it Are you able to test your code with 11.0.0-RC1 to see if you're seeing the same.

@melloware, one thing I am noticing is that on page load it does call the `setSelected` method with `null` but all the actual calls have the TreeNode. If I load the test page and click some nodes, this is the output in the console:
```
[INFO] Started Jetty Server
Selected called with null
Selected called with 0
Node is: 0
Selected called with 2
Node is: 2
Selected called with 1
Node is: 1
```

**Comment by melloware** [comment]
interesting so NULL to start must be the initial status of the nodes?

**Comment by kronos72it** [comment]
> 
> 
> interesting so NULL to start must be the initial status of the nodes?

It is one of my fall , you are right this generate a problem.If I use a no NULL value I can get the selected node but no via 
`public void setCostSelected(TreeNode costSelected) {
        this.costSelected = costSelected;
    }`
the argument is still NULL

But now I can see the selected node via:
`public void onNodeSelect(NodeSelectEvent event) {
        this.costSelected= event.getTreeNode();
    }`

**Comment by kronos72it** [comment]
I dont know where my app is differ than your example test . 
Maybe it is in fact I have the tree on dialog ? 
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" 
      template="template.xhtml">
        <ui:define name="center"> 
            <h:form id="form"> 
                <p:dataTable var="data" value="#{viewComplete.listCompleting}" rowKey="#{data.id}" paginator="true" rows="10"
                     paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                     rowsPerPageTemplate="10,20,30" selectionMode="single"
                     selection="#{viewComplete.selected}"
                     id="dataTable"> 
                    <p:ajax event="rowSelect" oncomplete="PF('dialogDetail').show()" update=":form:panelDetail" />
                <p:column headerText="ID" sortBy="#{data.id}" filterBy="#{data.id}">
                    <h:outputText value="#{data.id}" />
                </p:column>
                <p:column headerText="Data Valuta" sortBy="#{data.dataValuta}" filterBy="#{data.dataValuta}">
                    <p:datePicker value="#{data.dataValuta}" readonly="true"/>
                </p:column>
                <p:column headerText="Data Operazione" sortBy="#{data.dataOperazione}" filterBy="#{data.dataOperazione}">
                    <p:datePicker value="#{data.dataOperazione}" readonly="true"/>
                </p:column>
                <p:column headerText="Importo" sortBy="#{data.importo}" filterBy="#{data.importo}">
                    <h:outputText value="#{data.importo}"/>
                </p:column>
                <p:column headerText="Descrizione" sortBy="#{data.descrizione}"
                          filterBy="#{data.descrizione}">
                    <h:outputText style="vertical-align: middle; margin-left: .5rem"
                                  value="#{data.descrizione}"/> 
                </p:column>
                </p:dataTable>
                
                <p:dialog header="Transaction Detail" id="dialogDetail" widgetVar="dialogDetail" modal="true"
                     resizable="false" appendTo="@(body)">
                    
                    
                    <p:panelGrid id="panelDetail" >
                        <p:row>
                            <p:column><h:outputText value="Data Valuta"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.selected.dataValuta}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Data Operazione"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.selected.dataOperazione}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Importo"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.selected.importo}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Descrizione"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.descrNew}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2"><h:outputText value="Centro di Costo"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText  value="Valore"/></p:column>
                            <p:column><h:inputText id="costSelValore" value="#{empty viewComplete.costSelected ? '' : viewComplete.costSelected.data.value}" /></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Descrizione"/></p:column>
                            <p:column><h:inputText id="costSelDescr" value="#{empty viewComplete.costSelected ? '' : viewComplete.costSelected.data.descrizione }" /></p:column>
                        </p:row>
                                
                        
                        <p:row>
                            <p:column colspan="2">
                                <p:commandButton ajax="true"  id="buttonCost" value="Completa" actionListener="#{viewComplete.completeCost}" oncomplete="PF('dialogDetail').close()" update=":form:dataTable"/>
                            </p:column>
                            
                        </p:row>
                    </p:panelGrid>
                    
                    <p:tree id="costTree" value="#{viewComplete.costRoot}" var="node" selectionMode="single" 
                                        selection="#{viewComplete.costSelected}" dynamic="true" >
                        <p:ajax event="select" update=":form:costSelValore :form:costSelDescr :form:buttonCost" listener="#{viewComplete.onNodeSelect}" process="@this"/>
                        <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                            <h:outputText value="#{node.value}"/>
                        </p:treeNode> 
                    </p:tree>
                
                </p:dialog>
            </h:form>
        </ui:define>
    </ui:composition>
    

</html>
`

**Comment by tandraschko** [comment]
@kronos72it please - as always - provide a forked primefaces-test project reproducer, otherwhise you waste our time

**Comment by kronos72it** [comment]
ANother strangeness , if I remove the ajax tag inside tree
`<p:tree id="costTree" value="#{viewComplete.costRoot}" var="node" selectionMode="single" 
                                        selection="#{viewComplete.costSelected}" dynamic="true" >
             
              <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                            <h:outputText value="#{node.value}"/>
               </p:treeNode> 
</p:tree>`

the setter setCostSelected isn't called at all but when I expand a node , debug comes on setCostSelected , very strange

**Comment by melloware** [comment]
@kronos72it  Are you using the primefaces-test.zip reproducer that @FlipWarthog provided?  You should be testing with that not your own code.  To verify its fixed in 11.0.0.RC1.  If not this ticket will be closed.

**Comment by kronos72it** [comment]
GOT IT . 
If I remove the Dialog and leave the tree out of Dialog , the setCostSelectet method will fire with correct argument .
THen , there is a fix for this problem ? I wnat to have the tree on a Dialog

thanks a lot

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" 
      template="template.xhtml">
        <ui:define name="center"> 
            <h:form id="form"> 
                <p:dataTable var="data" value="#{viewComplete.listCompleting}" rowKey="#{data.id}" paginator="true" rows="10"
                     paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                     rowsPerPageTemplate="10,20,30" selectionMode="single"
                     selection="#{viewComplete.selected}"
                     id="dataTable"> 
                    
                <p:column headerText="ID" sortBy="#{data.id}" filterBy="#{data.id}">
                    <h:outputText value="#{data.id}" />
                </p:column>
                <p:column headerText="Data Valuta" sortBy="#{data.dataValuta}" filterBy="#{data.dataValuta}">
                    <p:datePicker value="#{data.dataValuta}" readonly="true"/>
                </p:column>
                <p:column headerText="Data Operazione" sortBy="#{data.dataOperazione}" filterBy="#{data.dataOperazione}">
                    <p:datePicker value="#{data.dataOperazione}" readonly="true"/>
                </p:column>
                <p:column headerText="Importo" sortBy="#{data.importo}" filterBy="#{data.importo}">
                    <h:outputText value="#{data.importo}"/>
                </p:column>
                <p:column headerText="Descrizione" sortBy="#{data.descrizione}"
                          filterBy="#{data.descrizione}">
                    <h:outputText style="vertical-align: middle; margin-left: .5rem"
                                  value="#{data.descrizione}"/> 
                </p:column>
                </p:dataTable>
                
                    
                    <p:panelGrid id="panelDetail" >
                        <p:row>
                            <p:column><h:outputText value="Data Valuta"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.selected.dataValuta}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Data Operazione"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.selected.dataOperazione}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Importo"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.selected.importo}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Descrizione"/></p:column>
                            <p:column><h:outputText value="#{viewComplete.descrNew}"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="2"><h:outputText value="Centro di Costo"/></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText  value="Valore"/></p:column>
                            <p:column><h:inputText id="costSelValore" value="#{empty viewComplete.costSelected ? '' : viewComplete.costSelected.data.value}" /></p:column>
                        </p:row>
                        <p:row>
                            <p:column><h:outputText value="Descrizione"/></p:column>
                            <p:column><h:inputText id="costSelDescr" value="#{empty viewComplete.costSelected ? '' : viewComplete.costSelected.data.descrizione }" /></p:column>
                        </p:row>
                                
                        
                        <p:row>
                            <p:column colspan="2">
                                <p:commandButton ajax="true"  id="buttonCost" value="Completa" actionListener="#{viewComplete.completeCost}" oncomplete="PF('dialogDetail').close()" update=":form:dataTable"/>
                            </p:column>
                            
                        </p:row>
                    </p:panelGrid>
                    
                    <p:tree id="costTree" value="#{viewComplete.costRoot}" var="node" selectionMode="single" 
                                        selection="#{viewComplete.costSelected}" dynamic="true" >
                        <p:ajax event="select" update=":form:costSelValore :form:costSelDescr :form:buttonCost" listener="#{viewComplete.onNodeSelect}" process="@this"/>
                        <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                            <h:outputText value="#{node.value}"/>
                        </p:treeNode> 
                    </p:tree>
                
            </h:form>
        </ui:define>
    </ui:composition>
    

</html>
`

**Comment by FlipWarthog** [comment]
Okay, I was able to get this reproducing with a primefaces-test project. It looks like the `appendTo="@(body)"` on the `p:dialog` is causing the issue. If that's set I'm seeing the `null` get passed into the setter, but if I remove it everything works as expected. @kronos72it Can you try this in your code?

@melloware I haven't tracked down the root of the issue but would this be a Tree bug or a Dialog bug?

**Comment by tandraschko** [comment]
appendTo="@(body)" will move it to a place, where you have NO outer form probably, which is a user error _actually_

**Comment by kronos72it** [comment]
> 
> 
> appendTo="@(body)" will move it to a place, where you have NO outer form probably, which is a user error _actually_

maybe this is true but I put the body parameter because ,whitout it the dialog remain gray ,below the blocking layer .see the attched img
![Cattura](https://user-images.githubusercontent.com/14057059/139910763-eb430e18-45ff-45ef-bcb4-735fc766ab2d.PNG)

**Comment by tandraschko** [comment]
Different issue
Either provide a reproducer for this issue or just put a form inside the dialog or use a better appendTo like @form

**Comment by kronos72it** [comment]
ok thanks to all  i will going to close the issue .
