### ISSUE TITLE
DataTable: filter not shown if column was initially not rendered

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#8051]
**Describe the defect**

Having a column definition that was initially not rendered (where rendered attribute evaluates to false) and another UI interaction toggles this attribute resulting in displaying the column, the filters are not shown.

In this example it only happens if the header is inside a `columnGroup`.

**Reproducer**

Have a `<p:column>` rendered false and make it true on another ajax request.

**Environment:**
 - PF Version: _11.0.0-RC2_
 - JSF + version: _e.g. Mojarra 2.3.8
 - Affected browsers: ALL_

**Expected behavior**

It should render the filter when rendered attribute changes from false to true.

**Example XHTML**

	<h:form>
	
		
		<p:outputLabel for="showColumnBrand" value="Show Brand:"/>
		<p:selectBooleanCheckbox id="showColumnBrand" value="#{testBean.showColumnBrand}">
			<p:ajax update="@form"/>
		</p:selectBooleanCheckbox>

	
		<p:dataTable id="tblCar" var="car" value="#{testBean.cars}">

			<p:columnGroup type="header">
			
				<p:column headerText="Id"/>
				
				<p:column headerText="Brand" filterBy="#{car.brand}" 
			    	rendered="#{testBean.showColumnBrand}"/>
				
			</p:columnGroup>

		    <p:column>
		        <h:outputText value="#{car.id}" />
		    </p:column>

		    <p:column rendered="#{testBean.showColumnBrand}">
		        <h:outputText value="#{car.brand}" />
		    </p:column>
		 

		</p:dataTable>
		
	</h:form>

**Example Bean**

	@ViewScoped
	public class TestBean implements Serializable
	{
		private List<Car> cars;
		private boolean showColumnBrand;
		
		// getters
	}

**Comment by tandraschko** [comment]
please provide a reproducer, not just a skeleton bean/xhtml

**Comment by djmj** [comment]
@tandraschko I can try to do that next week. I made some further observations:

**Observations**

The above example works if we add a _p:row_ suddenly but our application has _p:row_ and it does not work.

From checking the _DataTableRenderer_ maybe its related to the _UITable.initFilterBy_ which by default only initializes the filters only of rendered components.

https://github.com/primefaces/primefaces/blob/cbf34a195fc4fcd166f32945d7a85924b7a41396/primefaces/src/main/java/org/primefaces/component/api/UITable.java#L68

https://github.com/primefaces/primefaces/blob/cbf34a195fc4fcd166f32945d7a85924b7a41396/primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java#L1075

**Workaround**

To force reinitializing of this filter map, after changing rendered value we can use the _DataTable.setFilterByAsMap(null);_ method on ajax updating the table which works for our case, since all filters have server side value bindings (not using FilterMeta). Does not work for the small example without p:row usage though.

**Comment by melloware** [comment]
Closing issue as newer duplicate has a runnable reproducer
