### ISSUE TITLE
Tag: add ValueHolder interface

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#8055]
**Description**
I was adding a converter to a p:tag but I found out I can't because Tag doesn't implement the ValueHolder interface.

**Describe the solution you would like**
Either make Tag implement [ValueHolder](https://docs.oracle.com/javaee/7/api/javax/faces/component/ValueHolder.html) or extend [UIOutput](https://docs.oracle.com/javaee/7/api/javax/faces/component/UIOutput.html)

**Comment by tandraschko** [comment]
please provide a PR
