### ISSUE TITLE
Showcase DataExporter Excel not working

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#8058]
When clicking the excel buttons we see error page:

http://primefaces.org/showcase/ui/data/dataexporter/basic.xhtml?jfwid=8b9bc

Updating to PrimeFaces 11.0.0-RC2 we encounter a strange issue that the ordering of columns do not match the visual ordering when also using columnToggler. So i wanted to check showcase first before open a defect.

**Comment by melloware** [comment]
Error is this: 
```
java.lang.NoClassDefFoundError: org/apache/commons/io/output/UnsynchronizedByteArrayOutputStream
        at org.primefaces.component.datatable.export.DataTableExcelExporter.createWorkBook(DataTableExcelExporter.java:369)
        at org.primefaces.component.datatable.export.DataTableExcelExporter.preExport(DataTableExcelExporter.java:66)
        at org.primefaces.component.datatable.export.DataTableExporter.export(DataTableExporter.java:206)
        at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:159)
```

Have a feeling this is POI 5.1.0 change

**Comment by melloware** [comment]
Also please make sure your issue is not already reported here as an enhancement: https://github.com/primefaces/primefaces/issues/7966

**Comment by tandraschko** [comment]
can you try to rollback to 5.0? if it works, lets just do that and up to 5.1.0 after 11.0 final

**Comment by melloware** [comment]
its OK @tandraschko its just a showcase issue becaue we are using ancient commons IO 2.4  Its overriding POI's default include so I can fix it with just a showcase pom.xml change.

Our main code is fine.

**Comment by tandraschko** [comment]
didnt we shade commons-io? so it IS be a problem

**Comment by melloware** [comment]
we shaded it so ours are under `org.primefaces` but POI is using real Commons IO. The problem was our pom.xml was using the inherited parent version 2.4 which does not even have the class `UnsynchronizedByteArrayOutputStream`.  The Showcase should use its own version.

**Comment by tandraschko** [comment]
yep, i see
