### ISSUE TITLE
LazyDataModel: split in count() and load() clashes with backend methods that do both

### ISSUE THREAD

**Issue by giemes** [primefaces/primefaces#8062]
**Description**
Prior to PF11, the LazyDataModel had a central load() method passing all relevant data for the load-function. This works as expected with backends that, upon a search service call, returned both the count of total results and the current slice/page of the data in one data structure.

With PF11, the loadLazyData() method has changed, calling count() to fetch the total count before loading the data:

```
Map<String, FilterMeta> filterBy = getActiveFilterMeta();
lazyModel.setRowCount(lazyModel.count(filterBy));

// further setup

List<?> data = lazyModel.load(first, rows, getActiveSortMeta(), filterBy);
```

This requires a backend API design that splits the count and retrieval of the slice, which we don't find beneficial, as it requires twice the amount of endpoints and allows for data modifications in between.

Simply moving the data retrieval from load() to count() also doesn't work, as count() is not passed all parameters required for the complete API call including the slice to fetch (sort/first/rows).

**Describe the solution you would like**
The DataModel should support the previous method of load functions that retrieve the count and the slice in one call, i.e. a singular load function for both. Alternatively, pass all information required to retrieve the slice to count(), so that data retrieval can be performed there, and load() then simply returns the cached data.

**Comment by tandraschko** [comment]
the reason: https://github.com/primefaces/primefaces/issues/1921

as you can read in the linked issue, the DataTable itself requires the state of `rowCount for current filters` and `load current page with current filters`, thats how the DataTable itself works and LazyDataModel mirrors this

you can still just `return 0` in the count method but, like in the past, you have to calculate `first` in your `load` method and manually call 'setRowCount'
so i think your approach is still possible and we wont make the load method optional for now

we could either create a specialized LazyDataModel for your usecase or improveme the docs

**Comment by tandraschko** [comment]
yeah, i think about something like this:

```
public class MySingleCallLazyDataModel<T> extends LazyDataModel<T>
{
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return 0;
    }
    
    @Override
    public List<T> load(int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
        List<T> data = null; //callApi...., apply sort and filter

        // setRowCount is required if #count method isnt implemented correctly
        int rowCount = data.size();
        setRowCount(rowCount);

        // fix first, see #1921
        if (rowCount > 0 && first >= rowCount) {
            int numberOfPages = (int) Math.ceil(rowCount * 1d / pageSize);
            first = Math.max((numberOfPages - 1) * pageSize, 0);
        }

        return data.stream()
                .skip(first)
                .limit(pageSize)
                .collect(Collectors.toList());
    }
}
```

i think a good documentation is enough

**Comment by buett** [comment]
Splitting count and load may result in different isolation states. The count could change when loading data and that's why the pagination could be broken too.
In my point of view an API is a little bit clearer if count and data is fetched on same data.

**Comment by tandraschko** [comment]
yeah, 2 different approaches, nothing has been changed
only a additional mehtod has been introduced, which can also be dummy implemented like my sample above

**Comment by tandraschko** [comment]
i adjusted the javadoc and added a recalculateFirst helper method
is anyone interessted in adding a docu or showcase sample for this case?

**Comment by tandraschko** [comment]
```
public class MyApiLazyDataModel<T> extends LazyDataModel<T>
{
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return 0;
    }
    
    @Override
    public List<T> load(int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
        List<T> data = null; //callApi...., apply sort and filter

        int rowCount = data.size();

        // setRowCount and recalculateFirst is required if #count method isnt implemented correctly
        setRowCount(data.size());
        first = recalculateFirst(first, pageSize, rowCount);

        return data.stream()
                .skip(first)
                .limit(pageSize)
                .collect(Collectors.toList());
    }
}
```

**Comment by christophs78** [comment]
IMO not totally clear what´s the perfect solution. What PrimeFaces has to to and what need´s to be done in project-specific-code.

When i think of SpringData - Pageable+Page or Solr it´s simply one API-call to get a page of results. This returns the result-page and the overall amout of hits. So when should we call recalculateFirst?
Maybe there always needs to be some project-specific code. (Handling e.g. we get an empty page because some "rows" have been deleted meanwhile.)

For SpringData you may rework your SpringData-Repos. Split into a count-method and the find-method which returns a List instead of Page.

**Comment by tandraschko** [comment]
i think every detail has already been discussed in #1921
PF DataTable just works without any "hacks" like `recaculcateFirst`, when you correclty implement `#count`

When you dont implement `count`, and just `return 0`, everything is like in PF10 and before

So we now just needs to define/document cases and i think we have 3:
1) the "SQL" like case where you can implement `count` and `load`
    its the clearest way and PF can calculate `first` correctly
2) the "API" like case, where you receive ALL data for ALL pages
    this must use sublist and `recalculateFirst`
3) the "API" like case, where you receive the data for the current page and a rowCount for all pages
    this doesnt use sublist as its already paged by e.g. spring data
    in this case the data can be wrong and we cant use `recalculateFirst` - maybe Spring Data has own code for such cases

**Comment by tandraschko** [comment]
```
public class Case1<T> extends LazyDataModel<T>
{
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return repository.count(filterBy);
    }
    
    @Override
    public List<T> load(int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
        return repository.findPaged(first, pageSize, sortBy, filterBy);
    }
}
```

```
public class Case2<T> extends LazyDataModel<T>
{
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return 0;
    }
    
    @Override
    public List<T> load(int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
        List<T> data = null; //callApi...., apply sort and filter

        int rowCount = data.size();

        // setRowCount and recalculateFirst is required if #count method isnt implemented correctly
        setRowCount(data.size());
        first = recalculateFirst(first, pageSize, rowCount);

        return data.stream()
                .skip(first)
                .limit(pageSize)
                .collect(Collectors.toList());
    }
}
```


```
public class Case3<T> extends LazyDataModel<T>
{
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return 0;
    }
    
    @Override
    public List<T> load(int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
        MyApiResponse response = null; //callApi...., inclusive filter/sort
        setRowCount(response.getCount());
        return response.getPagedData();
    }
}
```

**Comment by Rapster** [comment]
2 cases over 3 shows that count is not mandatory, so maybe it shoudn't be abstract?

**Comment by koan00** [comment]
Adding this note just in case anyone else finds it useful.  With the above implementations, we had an issue with PF14 dataExporter and pageOnly=false. It would return an empty export until the below modification:

Update
```
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return 0;
    }
```
to:

```
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return getCount();
    }
```
