### ISSUE TITLE
Theme: TextEditor buttons look disabled in dark themes Vela and Arya

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8064]
Screenshot was taken from showcase running on 11.0.0-RC2

<img width="478" alt="Screenshot 2021-11-10 at 08 56 50" src="https://user-images.githubusercontent.com/7500178/141073012-3852a1b9-88dc-4837-bfb2-c5f483050747.png">

**Comment by melloware** [comment]
We need to do 2 things.

1. Add the `theme` property to the widget so users can select their theme. Right now its hard coded to `snow`...
```javascript
        this.cfg.theme = 'snow';
```

2. Include more than just the Snow theme with the editor.  At least 1 dark theme option, snow for light theme and the other for dark theme.

**Comment by melloware** [comment]
@tandraschko I can fix this easily but should we do this for 11.0 or mark it for 12.0?

**Comment by tandraschko** [comment]
maybe you can provide a PR and decide then

**Comment by melloware** [comment]
cool will do.

**Comment by melloware** [comment]
Please review my PR.  It was simpler than I thought and this is better for all PF themes include Premium ones.

**Comment by melloware** [comment]
To make this work for legacy themes or if you are using "no theme" you need to add at least 1 CSS variable to your stylesheet.

```css
:root {
    --text-color: #444;
}
```
