### ISSUE TITLE
ChartJS: PieChart breaks when setting legend options

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#8068]
**Describe the defect**
In PF 11.0.0-RC2, setting a legend breaks the pie chart. I get the following console error:
`Uncaught SyntaxError: Unexpected token ','`

When I check the javascript, I see a leading comma before "legend":
`"options":{"animation":{"animateRotate":false,"animateScale":false},"plugins":{,"legend":{"display":true,"position":"right","fullWidth":true,"reverse":false,"rtl":false,"`

It's most probably a side-effect of #8028 resp #8029.

**Reproducer**
Use pie chart with some legend options:
`Legend legend = new Legend();
legend.setPosition("right");
legend.setLabels(legendLabels);
PieChartOptions options = new PieChartOptions();
options.setLegend(legend);`

**Expected behavior**
I see the legend on the right.

**Actual behavior**
The pie chart isn't displayed, and I see the above JS error.

```

**Comment by melloware** [comment]
Thanks for reporting.  Fixing it now.
