### ISSUE TITLE
DataTable: Column header alignment

### ISSUE THREAD

**Issue by haraleib** [primefaces/primefaces#8069]
**Describe the defect**
As shown in the provided screenshot (screenshot of primefaces datatable show case), the components inside the datatable column headers are not aligned in one row.

Screenshot 1 - current behaviour:
![image](https://user-images.githubusercontent.com/19574757/141268932-62c767e4-d367-4c4f-9cd7-dcda76019b71.png)

**Environment:**
 - PF Version: 10.0.7
 - JSF + version: MyFaces  2.3.6
 - Affected browsers: Tested with Chrome

**Expected behavior**
- The filter inputs should be aligned at the same height
- The labels should be aligned at the same height (independent if filters exist or not)
- The sort icon should always be on the same position (left or right position of the label)

Screenshot 2 - expected behaviour:
![image](https://user-images.githubusercontent.com/19574757/141269041-54154f9d-381e-4331-b75f-bbaa6fc0d7ef.png)

**Comment by mertsincan** [comment]
It is very difficult to do this feature automatically with this structure. You can try to do this with custom css. In the future, separating the filter and header fields as in PrimeReact will solve such problems.
https://www.primefaces.org/primereact/datatable/filter/

Best Regards,

**Comment by melloware** [comment]
Replaced By https://github.com/primefaces/primefaces/issues/11251
