### ISSUE TITLE
DataTable: clearFilters doesnt work for complex input widgets like p:selectOneMenu

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#8071]
**Describe the defect**
When using `p:selectOneMenu` in `DataTable` as custom filter, a call to `DataTable#clearFilters()` resets the filter of the `DataTable` but not the displayed value of the `p:selectOneMenu`. It works as expected when using `h:selectOneMenu` instead.

**Reproducer**
See [primefaces-test.zip](https://github.com/primefaces/primefaces/files/7520464/primefaces-test.zip).

**Environment:**
 - PF Version: _11.0.0-RC2_
 - JSF + version: _Mojarra 2.3.14.payara-p2_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start the reproducer.
2. Select 'true' in column _c1_
3. Select 'true' in column _c2_
4. Click the filter reset button.
5. Filter for `DataTable` is reset, value of _c1_ filter is reset, but value of _c2_ filter is still 'true'.

**Expected behavior**
Value of custom filter with `p:selectOneMenu` should be reset too when calling `DataTable#clearFilters()`.

**Referenced issues**
#6669, #6670

**Comment by tandraschko** [comment]
@melloware @Rapster could you check that?

**Comment by melloware** [comment]
Yes I know this to be an issue.  ClearFilters just does this...

```javascript
 this.thead.find('> tr > th.ui-filter-column > .ui-column-filter').val('');
 this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter :input').val('');
$(this.jqId + '\\:globalFilter').val('');
```

Which sets all inputs regular and custom back to `''`.  However `p:selectOneMenu` is more complex than just settings its input to ''.  For SelectOne we would have to call custom widget method `PF('id').selectValue('');` or something like that.   And any other special widgets would need to have the same called like any would need a `clear()` method that can be called but I am not sure how we would determine the widget nuless the filter used a `data` attribute to put the widget ID in there.  So most likely @ltlBeBoy you will have to override `clearFilters` and write a custom clear for this table.  It gets even more complex for thinks like `SelectManyChekbox` etc.

**Comment by tandraschko** [comment]
in theory we can look for `.ui-widget` and check `PF.getWidgetById`

**Comment by melloware** [comment]
Oh slick!  Then we could check InstanceOf widget SelectOne and call its seletcValue or selectManyCheckbox like uncheckAll() wdget method etc!

**Comment by ltlBeBoy** [comment]
OK, I was overriding `DataTable#clearFilters()` like this:

```
const superClearFilters = PrimeFaces.widget.DataTable.prototype.clearFilters;

PrimeFaces.widget.DataTable.prototype.clearFilters = function () {

    this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter > .ui-widget').each(function (idx) {
        var wdgId = $(this).attr('id');
        var wdg = PrimeFaces.getWidgetById(wdgId);
        if (wdg instanceof PrimeFaces.widget.SelectOneMenu) {
            wdg.selectValue('');
        } else if (wdg instanceof PrimeFaces.widget.SelectManyCheckbox) {
            // TODO!
        } else {
            console.log("other");
        }
    });

    superClearFilters.apply(this, arguments);
};
```

It resets `p:selectOneMenu` like expected. But the downside is that calling `SelectOneMenu#selectValue('')` also triggers the filtering event which results in sending that event for each column with a custom filter widget.

A solution could be a common class for input widgets with a `clear()` method that does not trigger an event and which has to be implemented by all input widgets, e.g.:

```
    PrimeFaces.widget.InputWidget=PrimeFaces.widget.BaseWidget.extend({
        init: function(b) {
            this._super(b);
            ...
        },
        
        clear: function() {
            console.log("TODO: Implement!");
        }
    }
```

Then `DataTable#clearFilters()` could look like this:

```
    ...
    this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter > .ui-widget').each(function (idx) {
        var wdgId = $(this).attr('id');
        var wdg = PrimeFaces.getWidgetById(wdgId);
        if (wdg instanceof PrimeFaces.widget.InputWidget) {
            wdg.clear();
        } else {
            console.log("Not supported.");
        }
    });
    ...
```

But I found out that some input widgets are derived `DeferredWidget` instead of from `BaseWidget`...

**Comment by melloware** [comment]
Agreed we will have to come up with some common method and make it easy to call on any widget.

**Comment by tandraschko** [comment]
i think we can also just check if the widget has a "resetValue" method and call this
so we dont need inheritance

**Comment by tandraschko** [comment]
i would do it like:
```
        this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter').each(function(idx) {
            var widgetElement = $(this).find('.ui-widget');
            if (widgetElement.length > 0) {
                var widget = PrimeFaces.getWidgetById(widgetElement .attr('id'));
                if (widget && typeof widget.resetValue === 'function') {
                    widget.resetValue(false);
                }
            }
            else {
                $(this).find(':input').val('');
            }
        });
```

**Comment by tandraschko** [comment]
and each input widget can add:
```
resetValue: function(triggerChangeEvent) {
}
```

so even a user can use it to reset + trigger events

**Comment by tandraschko** [comment]
i just wonder if there are special cases with more widgets inside or a mix between a ui-widget and also a basic filter like h:selectOneMenu (instead of p:selectOneMenu)
maybe something like a container component (ui-widget) and within a h:selectOneMenu

**Comment by melloware** [comment]
Yeah we use p:selectManyCheckbox widget a lot in our filters for things like status where they can pick more than one status to filter on etc.

**Comment by tandraschko** [comment]
p:selectManyCheckbox is still only one widget

i really think about something like:
```
                <f:facet name="filter">
                    <p:someContainerComponentLikeOutputPanel>
                        <h:selectOneMenu onchange="PF('customersTable').filter()" styleClass="custom-filter">
                            <f:selectItem itemLabel="All" itemValue="#{null}" noSelectionOption="true" />
                            <f:selectItems value="#{dtFilterView.representatives}" />
                        </h:selectOneMenu>
                    </p:someContainerComponentLikeOutputPanel>
                </f:facet>
```

in this case, the code above would find a ui-widget (someContainerComponentLikeOutputPanel) and try to reset it instead of reset the :input of h:selectOneMenu

**Comment by melloware** [comment]
Ah I see your point.

**Comment by tandraschko** [comment]
we could also do something like:

```
this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter :input').val(''); // old function for basic inputs
this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter').each(function() { // new function for resetting widgets
    var widgetElements = $(this).find('.ui-widget');
    widgetElements.each(function() {
        var widget = PrimeFaces.getWidgetById(this.attr('id'));
        if (widget && typeof widget.resetValue === 'function') {
            widget.resetValue(false);
        }
    });
});
```

**Comment by tandraschko** [comment]
im just not sure if this would work as you reset all :inputs of e.g. a selectOneRadio and then im not sure if all widgets has a right state to call resetValue

**Comment by tandraschko** [comment]
yep, that doesnt even work for a selectOneMenu
we need somehow decide if we reset basic :input or ui-widgets inside the current column

**Comment by tandraschko** [comment]
i commited something
the producer works fine now
the code looks for a ui-widget in the facet and try to reset, otherwise it resets all :input

**Comment by tandraschko** [comment]
would be great if you could retest - also treetable
we might some other resetValue methods and test

**Comment by melloware** [comment]
this looks great!

**Comment by tandraschko** [comment]
also added selectBooleanCheckbox support now

**Comment by tandraschko** [comment]
@melloware would you like to provide a impl for selectManyCheckbox?

**Comment by melloware** [comment]
Yep let me add SelectManyCheckbox support.

**Comment by melloware** [comment]
I added SelectCheckBoxMenu support as that is actually what we use a lot for filtering at my client and we already had this custom override...

```javascript
clearCheckboxFilter: function(checkboxVar) {
           PF(checkboxVar).show();
           PF(checkboxVar).uncheckAll();
           PF(checkboxVar).hide();
         }
```

**Comment by ltlBeBoy** [comment]
I added the modifications and tested with my software (DataTable + SelectOneMenu). It works like a charm! Thank you so much for that quick fix!

**Comment by melloware** [comment]
Thanks for testing @ltlBeBoy I just updated my PR to add SelectCheckboxMenu support as well.

**Comment by tandraschko** [comment]
AFAICS we have:
selectManyCheckbox
selectBooleanCheckbox
selectOneMenu
selectCheckBoxMenu

should we support more or just close for now?

**Comment by melloware** [comment]
I say we close for now as those are the most popular filters.  And regular InputTexts etc are already handled.  So I say from now on let someone open a new ticket if they want a specific component to have `resetValue`
