### ISSUE TITLE
Avatar: Duplicates first character when no surname

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#8074]
Just try below. `PP` will be appeared instead of `P`.

```xml
<p:avatar label="Primefaces" styleClass="p-mr-2" size="xlarge" />
```

**Comment by aripddev** [comment]
I think below additions is needed in `calculateLabel ` method of `AvatarRenderer` class.

line 136: change from

```java
return initials.charAt(0) + initials.substring(initials.length() - 1);
```

 to

```java
return initials.length() == 1 ? initials : initials.charAt(0) + initials.substring(initials.length() - 1);
```

**Comment by tandraschko** [comment]
it would be great if you can provide a testcase at least: https://github.com/primefaces/primefaces/blob/master/primefaces/src/test/java/org/primefaces/component/avatar/AvatarRendererTest.java

or provide a PR with testcase + codechange :)

**Comment by aripddev** [comment]
next time I will try before creating the issue :). Thank @melloware
