### ISSUE TITLE
Schedule: onDateSelect chooses wrong time

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8076]
The selected time is always one hour less. You can easily verify this using the showcase:

https://www.primefaces.org/showcase/ui/data/schedule/basic.xhtml?jfwid=381ce

Just click on any slot. For instance, clicking on 6am will open the event details panel with starttime 5am.

Many thanks in advance for fixing this bug.

**Comment by melloware** [comment]
See this ticket: https://github.com/primefaces/primefaces/issues/7891

**Comment by melloware** [comment]
Schedule uses the browser timezone and sends the date back in ISO format. The server translates that to your local date.   Either pick UTC or may sure your clientTimeZone matches your server timezone.

**Comment by tuerker** [comment]
Adding clientTimeZone="UTC" works. Many thanks for the hint. Nevertheless, I would have preferred that the default case is the one that does not require a migration.

Would be good to explicitly mention this in the migration guide and also adapt the showcases. Many thanks in advance.

**Comment by melloware** [comment]
PR submitted to update the showcase and migration guide.

**Comment by tuerker** [comment]
@melloware Both show cases 

basic: https://www.primefaces.org/showcase/ui/data/schedule/basic.xhtml?jfwid=08320
configuration: https://www.primefaces.org/showcase/ui/data/schedule/configuration.xhtml?jfwid=08320

show this behavior, where the selectEvent delivers selected time minus one hour.

I have double-checked my code, too. As in the basic show case my p:schedule uses the defaults, i.e., the attributes timeZone and clientTimeZone are not set. In this case, the reported "wrong" behavior is visible. When i set clientTimezone="UTC", then selectEvent has the right time but the other reported issue https://github.com/primefaces/primefaces/issues/8086 occurs.

The following workaround (add one hour to the selectEvent's LocalDateTime) works for me:

```
    public void onDateSelect(SelectEvent<LocalDateTime> selectEvent) {
        LocalDateTime selectedStartDate = selectEvent.getObject();
        selectedStartDate = selectedStartDate.plusHours(1));

```

It looks like the selectEvent needs to be fixed. I had a quick look into the PrimeFaces code: in class Schedule.java following line 101

```
            if ("dateSelect".equals(eventName) || "dateDblSelect".equals(eventName)) {
                String selectedDateStr = params.get(clientId + "_selectedDate");
                ZoneId zoneId = CalendarUtils.calculateZoneId(this.getTimeZone());
                LocalDateTime selectedDate =  CalendarUtils.toLocalDateTime(zoneId, selectedDateStr);
```

either the timeZone must be wrong or the parameter selectedDateStr. Could it be that the parameter selectedDateStr is simply built wrongly such that in total twice the timezone adaptation is done? As usual, many thanks for looking into and fixing the issue.

**Comment by melloware** [comment]
Don't use the showcase
It still has the broken code it does not have the fix from yesterday to revert.  My revert takes it back to how it has been working since PF8

**Comment by tuerker** [comment]
@melloware I don't think that your revert directly affects this problem here. The problem goes back to the migration from Java Date to LocalDateTime. It looks like that the problem is caused by a wrong calculation of the "selected" LocalDateTime. Let us have a look again at the code mentioned above:

```
if ("dateSelect".equals(eventName) || "dateDblSelect".equals(eventName)) {
  String selectedDateStr = params.get(clientId + "_selectedDate");
    
  // selectedDateStr is the selected date according to clientTimeZone. 
  // i assume that this comes from fullcalendar.
    
  ZoneId zoneId = CalendarUtils.calculateZoneId(this.getTimeZone());
  LocalDateTime selectedDate =  CalendarUtils.toLocalDateTime(zoneId, selectedDateStr);

  // if the assumption in the comment above holds, the LocalDateTime selectedDate is always created   
  // based on the timeZone setting while the selectedDateStr might refer to a different (client) time zone. 
  // so actually, here a transformation of selectedDateStr to a string representing the date  
  // according to the targeted time zone is needed. 
```

Is this assumption and argumentation correct?

**Comment by melloware** [comment]
@christophs78 ?See question above.

**Comment by christophs78** [comment]
Good point!
We first have to debug which value is sent from the client to the server
![image](https://user-images.githubusercontent.com/10461942/142404320-78c1da7b-e509-49f8-809e-679db62c11fa.png)
After we checked this is right in all usecases (no timezone defined, differenz timezones defined, ...) we have to adapt the code mentioned by @tuerker  above. I´ll try to look into this later this day.

**Comment by christophs78** [comment]
Some notes... 

We need to keep https://github.com/primefaces/primefaces/issues/5914 and https://github.com/primefaces/primefaces/issues/7891 in mind.

We have 3 factors:
1. timezone of server (default-timezone or set via timezone-attribute of p:schedule)
2. timezone of client (browser-timezone or set via clienttimezone-attribute of p:schedule)
3. daylight saving time (currently we have 18th of november; when i set clientTimeZone to UTC an select a date back in september we have 2 hours offset for onDateSelect)

I need more time. --> I´ll continue this weekend.

My current preliminary (!!!) feeling is we need to
1. remove PrimeFaces.toISOString from 1-schedule.js (as already done with https://github.com/primefaces/primefaces/issues/7891 and rolled back later)
2. look for a (new) server-side solution to convert this "the right way" into LocalDateTime (https://github.com/primefaces/primefaces/issues/5914 reloaded)

**Comment by christophs78** [comment]
Maybe part of the "truth" is, we should use ZonedDateTime instead of LocalDateTime to make things more explicit.

Why?

- e.g. Server-timezone UTC, Client-timezone GMT+1
- user selects e.g. 06:00 (GMT+1), on server LocalDateTime is 05:00 (UTC)
- when we render LocalDateTime 05:00 (UTC) without further treatment and send it to the client this is technically correct but not exactly what our users expects

**Comment by melloware** [comment]
I remeber this being complicated but we ALWAYS need the data in UTC from the browser.

So if clientTimeZone=UTC on the Schedule we can just use the dates as is.  If its not set then we needed to do Browser Offset to get the date into IsoString in UTC format to send to the server  The goal should be ALL dates coming from the Schedule should be in UTC.

**Comment by tandraschko** [comment]
@melloware @christophs78 tests failed this night, can you check?=

**Comment by christophs78** [comment]
`Error:    Schedule001Test.testDateSelect:92 expected: <true> but was: <false>`
...fails on Firefox
