### ISSUE TITLE
Designer: Some Secondary Button Attributes won't work

### ISSUE THREAD

**Issue by elias-jk** [primefaces/primefaces#8083]
**Describe the defect**
Affected Version: Theme Builder 10.0.0

The following attributes have no effect on the secondary button whatsoever: $secondaryButtonActiveBg, $secondaryButtonActiveBorderColor

For all other types of buttons these attributes seem to work flawlessly.

**Environment:**
 - PF Version: _10.0_
 - Designer Version: 10.0.0 _
 - Affected browsers: Firefox, Chrome_

**Comment by tandraschko** [comment]
Please use the forum: https://forum.primefaces.org/viewforum.php?f=84
this issue tracker is only for primefaces (core) itself
