### ISSUE TITLE
Schedule: Slots not correctly drawn anymore

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8086]
With the recent updates regarding the schedule component, the slots of the schedule are not placed fully correctly anymore. See following screenshot where the (red) event starting at 0:00 of the next day is now drawn as starting at the end of the previous day.

![Screenshot from 2021-11-16 17-16-00](https://user-images.githubusercontent.com/10051373/142023701-f9934ca8-ed9e-4d06-bc0a-768ccd9604fc.png)

There must be a tiny change causing this little shift of the slot borders. The snapshot as of 11.0.0-20210927.082139-4 is running correctly.

Thanks in advance for looking into and fixing the issue or at least letting us know what has to adapted to make it working correctly again.

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/issues/8076

And: https://github.com/primefaces/primefaces/issues/7891

**Comment by melloware** [comment]
Isn't that your issue? It looks like its off by an hour.

**Comment by tuerker** [comment]
thanks for the hint. this issue is related but not a duplicate. actually, this problem is now induced by adding

            clientTimeZone="UTC"

to the schedule as adviced. this addition fixes  https://github.com/primefaces/primefaces/issues/8076 but creates this one.

**Comment by tuerker** [comment]
it looks like that fix https://github.com/primefaces/primefaces/issues/7891 has some undesired side effects.

**Comment by melloware** [comment]
Agreed. I am going to revert it for now.

**Comment by tuerker** [comment]
@melloware thanks for the revert which was needed to fix the issue reported here. 

after having investigated a little bit more i have to state that issue https://github.com/primefaces/primefaces/issues/8076 is still an issue and therefore should be reopened again.

my current workaround is just to add one hour to the selectEvent's LocalDateTime:

```
    public void onDateSelect(SelectEvent<LocalDateTime> selectEvent) {
        LocalDateTime selectedStartDate = selectEvent.getObject();
        selectedStartDate = selectedStartDate.plusHours(1));
```

it looks like the selectEvent needs to be fixed.

many thanks again.

**Comment by melloware** [comment]
Can you double check this uses your browser time zone and offsets for utc.  This was reported before being off 1 hour and was fixed.

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/issues/5914
