### ISSUE TITLE
java.lang.NoSuchMethodError: javax.validation.ValidatorFactory.close in PrimeApplicationContext.release()

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#8088]
**Environment:**
 - PF Version: _8.0.13
 - JSF com.sun.faces 2.1.29-11
 - Affected browsers: ALL
 - WebLogic Server 12.1.3.0.0 JavaEE 6, OpenJDK 8

**Expected behavior**
When the application is redeployed, the class method PrimeApplicationContext.release () and validatorFactory.get (). Close () are called.
The ValidationFactoryImpl has no close () method.

Which ValidationFactoryImpl does Primefaces use and can I replace it?

Steven

**Comment by GedMarc** [comment]
So, Off the bat, problem is your EE is way passed EOL. 

No in EE6 there is no .close() method (https://docs.oracle.com/javaee/6/api/javax/validation/ValidatorFactory.html)
Yes in EE7 there is a close() method https://docs.oracle.com/javaee/7/api/javax/validation/ValidatorFactory.html

In EE7 calling the close() method is extremely important, and cannot be skipped
@melloware I'm not sure how far back the backwards compatibility goes, but EE6 EOL'd in **_November 2012_**

So I'm not going to look at this

**Comment by melloware** [comment]
Here is the method in PrimeFaces...

```java
public void release() {
        if (environment != null && environment.isAtLeastBv11()) {
            if (validatorFactory != null && validatorFactory.isInitialized() && validatorFactory.get() != null) {
                validatorFactory.get().close();
            }
        }
    }
```

I think PF's goal is to support JSF 2.1 and EE6 still so this probably needs to be fixed @tandraschko  ?

**Comment by melloware** [comment]
Oh I see it looks like you have Bean Validation 1.1 somewhere in your classpath that it thinks this is OK?

` if (environment != null && environment.isAtLeastBv11()) {`

**Comment by tandraschko** [comment]
If you check PF8, we also had the isBV11 check:
https://github.com/primefaces/primefaces/blob/8.0/src/main/java/org/primefaces/context/PrimeApplicationContext.java#L221

This could mean that you have a BeanValidation 1.1+ API JAR but only a BeanValidation 1.0 Impl JAR

its not a problem of PF

**Comment by StevenHachel** [comment]
Ok, thx for the infos. Yes, JavaEE6 is very old. Sorry. :)

Steven

**Comment by StevenHachel** [comment]
Under Weblogic 12.2.1.4 and JavaEE 7 works without errors.

Unfortunately, I can't migrate to the more recent Weblogic yet, because I get too many JavaScript errors with this combination. Migrations always mean a lot of work. :)

many thanks again to you guys!

**Comment by GedMarc** [comment]
@StevenHachel as @tandraschko pointed out, it's actually an invalid dependency graph, 
Check your libraries being loaded, somewhere you have added bean validation 1.1 imp in your class path.
If you resolve that, I imagine you should be sorted

But yes, especially from a security standpoint, it may be better to run a catchup sprint or two on the tech stack ;)
