### ISSUE TITLE
Charts: Typo, RadialScales setAngelLines and getAngelLines should be setAngleLines and setAngleLines

### ISSUE THREAD

**Issue by FeanorOfValinor** [primefaces/primefaces#8093]
**Describe the defect**
There are typos in RadialScales. setAngelLines and getAngelLines should be setAngleLines and getAngleLines.

**Reproducer**
N/A

**Environment:**
 - PF Version: 11.0.0-RC2
 - JSF + version: N/A
 - Affected browsers: N/A

**To Reproduce**
Look in org.primefaces.model.charts.axes.radial.RadialScales and note the typos.
Refer to ChartJS doc: https://www.chartjs.org/docs/latest/axes/radial/linear.html

**Expected behavior**
RadialScales method names should be setAngleLines and getAngleLines.

**Example XHTML**
N/A

**Example Bean**
N/A

**Comment by melloware** [comment]
Great catch thanks for reporting.  Will be fixed for 11.0.0 final
