### ISSUE TITLE
Default filter for TreeTable

### ISSUE THREAD

**Issue by JensPiegsa** [primefaces/primefaces#8095]
`p:dataTable` has a `filterBy` attribute that can be used to activate a filter by default. Is there any option for `p:treeTable` to achieve the same? Otherwise, I would be immensely happy with any kind of workaround, however wacky it may be.

**Comment by tandraschko** [comment]
Did you check the docs? It has a FilterBy

**Comment by JensPiegsa** [comment]
Ok, I see. The project where I need this is still at PrimeFaces version 8, which unfortunately does not support this feature yet. We are actually quite far from a migration, due to a lot of required CSS corrections.
