### ISSUE TITLE
JQplot Chart: DateAxis tickinterval summer- and wintertime

### ISSUE THREAD

**Issue by ctrue9000** [primefaces/primefaces#810]
when setting a dateaxis for a chart and set min and max date and tickinterval '1 day' or '24 hours' the date when the time changes from summer to wintertime or the other way round, shows twice.
example:
![dateaxisissuepf](https://cloud.githubusercontent.com/assets/8307211/10632270/a032a9be-77e3-11e5-8cab-a7aa698b4332.PNG)

**Comment by melloware** [comment]
Possibly:  https://github.com/jqPlot/jqPlot/issues/116

**Comment by melloware** [comment]
Its this issue: https://github.com/jqPlot/jqPlot/issues/30
