### ISSUE TITLE
Schedule: viewChange-event fires after lazy-loading

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#8100]
Up to PF 8.0 viewChange fired before lazy-loading. So it was possible to load more or less detailed data depending on active view.
Since 10.0.0 lazy-loading is triggered before viewChange.

I´ll try to look at this and provide a PR targeted for 12.0.0.

**Comment by christophs78** [comment]
Maybe this is a won´t fix, because this behaviour is controlled by FullCalendar. viewClassNames (https://fullcalendar.io/docs/view-render-hooks) is fired after events are loaded (https://fullcalendar.io/docs/events-function).

**Comment by melloware** [comment]
Yeah it seems like it if you are limited by what FC offers without hacking it.

**Comment by melloware** [comment]
Should we close this as WontFix?
