### ISSUE TITLE
AutoComplete in multiple mode - read only attribute not fully functional

### ISSUE THREAD

**Issue by MontyZoomer** [primefaces/primefaces#8101]
**Describe the defect**
When the read only attribute of AutoComplete is true, values in the list can still be removed.

**Reproducer**
https://github.com/MontyZoomer/primefaces-test2.
Its not a fully functioning AutoComplete solution but is enough to view the problem.
When set read only you can deselect values.
It would be useful to have read only working because disable=true greys everything out.
If its not supposed to have that attribute it should be removed.
I guess a workaround would be to use disabled and switch css and change opacity.

**Environment:**
 - PF Version: 11.0.0-RC2
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: ALL

**To Reproduce**
1. Go to test.xhtml
2. 2. Press the X on a value in the AutoComplete component that is set read only

**Expected behavior**
The X to not remove values from the list.

**Example XHTML**
```html
<h:form id="frmTest">
            <p:autoComplete id="animal" multiple="true" value="#{testView.animalList}"
                            completeMethod="#{testView.acAnimal}" readonly="true"
                            var="animal" itemLabel="#{animal.type}, #{animal.name}" itemValue="#{animal}"
                            forceSelection="true" scrollHeight="250">
                <p:column>
                    <h:outputText style="vertical-align: middle; margin-left: .5rem" value="#{animal.name}"/>
                </p:column>
            </p:autoComplete>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    
    @PostConstruct
    public void init() {

        string = "Welcome to PrimeFaces!!";

        animalList = Arrays.asList(
                new Animal("Tiger", "Max", "White"),
                new Animal("Elephant", "Nellie", "Pink"),
                new Animal("Bear", "Balloo", "Brown")
        );
    }

    public List<Animal> acAnimal() {
        return new ArrayList<Animal>();
    }

    public List<Animal> getAnimalList() {
        return animalList;
    }

}
```

**Comment by melloware** [comment]
Good catch.  Added a check in the AddItem and RemoveItem methods.  We were checking for disabled but not for ReadOnly!
