### ISSUE TITLE
DataTable: filtering should also handle collections

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#8105]
https://github.com/primefaces/primefaces/blob/83636668d75e5c69e3b2ebbebadb518ed3ebf84b/primefaces/src/main/java/org/primefaces/component/api/UITable.java#L220

This function should also set filterValue to null if filterValue is a collection or an iterable that is empty.

**Comment by tandraschko** [comment]
could you please post a sample or a statement why?
this issue currently is quite incomplete

**Comment by mihaiDumea** [comment]
As the code shows, it only handles String and Array. Why stops there if the filter value can also take a collection?
If filterValue is an empty collection, then no rows will be displayed on the datatable.


[filter.txt](https://github.com/primefaces/primefaces/files/7587742/filter.txt)
[MBean.txt](https://github.com/primefaces/primefaces/files/7587767/MBean.txt)

**Comment by tandraschko** [comment]
please try a snapshot again
