### ISSUE TITLE
FilterMatchMode.IN : allow to filter null values 

### ISSUE THREAD

**Issue by alinatoleeva** [primefaces/primefaces#8106]
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7590646/primefaces-test-master.zip)
**Description of the defect**
filterMatchMode="in" doesn't properly filter value of null. 
This issue is similar to https://github.com/primefaces/primeng/issues/5735 
* Column has empty cells (null cells)
* Filter selectCheckboxMenu has <f:selectItem itemValue="" itemLabel="(Empty)"/>
* If this (Empty) filter item is selected, cells were not reduced to only empty cells.

**Reproducer**
ZIP is attached.

**Environment:**
 - PF Version: _11.0.0-RC2
 - MyFaces 2.3
 - Affected browsers:  Edge

**To Reproduce**
1. Run demo with mvn jetty:run
2. Filter table by column 'Companies' - select '(Empty)' item in selectCheckboxMenu
3. All rows are still there, but there should be only two rows, where company cells are empty

**Expected behavior**
When `<f:selectItem itemValue="" itemLabel="(Empty)"/>` is selected in selectCheckboxMenu filter, empty cells in this column should remain.  

**Example XHTML**
```html
<h:form>
        <p:dataTable var="customer" value="#{dtFilterView.customers1}" widgetVar="customersTable"
                     emptyMessage="No customers found with given criteria"
                     filteredValue="#{dtFilterView.filteredCustomers1}">

            <p:column field="company" headerText="Companies" sortBy="#{customer.company}" filterBy="#{customer.company}"
                      filterMatchMode="in">
                <f:facet name="filter">
                    <p:selectCheckboxMenu onchange="PF('customersTable').filter()"
                                          label="Select"
                                          value="#{dtFilterView.selectedCompanies}" >
                        <f:selectItem itemValue="" itemLabel="(Empty)"/>
                        <f:selectItems value="#{dtFilterView.companies}" />
                    </p:selectCheckboxMenu>
                </f:facet>
            </p:column>

        </p:dataTable>
    </h:form>
```

**Comment by melloware** [comment]
There is a good chance you have...

```xml
    <context-param>
        <param-name>javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
        <param-value>true</param-value>
    </context-param>
```

IN your web.xml which submits it as NULL not "" to the backing bean.  Look at the F12 network traffic and see what is submitted in the AJAX request or debug it on the back end.

**Comment by alinatoleeva** [comment]
Hi @melloware , 
thank you for suggestion. 
Unfortunately I did not find this parameter in my web.xml.
The demo I implemented using repository https://github.com/primefaces/primefaces-test.git and there is also no parameter javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL.

**Comment by melloware** [comment]
First:
![image](https://user-images.githubusercontent.com/4399574/143094213-db03f527-38d7-4ee6-a99a-96c5bf6fab78.png)

Submits this:
![image](https://user-images.githubusercontent.com/4399574/143094359-fcce470c-88de-4c48-aa9d-1d13fc0bacd8.png)


Second with two values:
![image](https://user-images.githubusercontent.com/4399574/143094416-b3fae9dc-ad69-446e-a269-502f736a0b7b.png)

Submits both values to the backing bean:
![image](https://user-images.githubusercontent.com/4399574/143094493-360b7a99-78b5-4af4-b89a-ed0f8ca4f5c4.png)

**Comment by melloware** [comment]
Also I added this to your code...

```java
	public void setSelectedCompanies(String[] selectedCompanies) {
		System.out.println(Arrays.toString(selectedCompanies));
		this.selectedCompanies = selectedCompanies;
	}
```

Here is what it prints out:
```
[Benton, John B Jr]
[, Benton, John B Jr]
```

You can see the second one has two items in the array with one of them being an empty string.

**Comment by alinatoleeva** [comment]
I think the problem is in org.primefaces.model.filter.InFilterConstraint.java

If value (cell value) is null, then it returns false. So the filter contains empty String, but value is null. 
 
```
if (filter == null || value == null) {
            return false;
        }
```

I overridden the method like this and it works as expected:
```
public class InFilterConstraint implements FilterConstraint {

	@Override
	public boolean isMatching(FacesContext ctxt, Object value, Object filter, Locale locale) {
		if (filter == null
//				|| value == null
		)
		{
			return false;
		}

		Collection<?> collection = null;
		if (filter.getClass().isArray()) {
			collection = Arrays.asList((Object[]) filter);
		}
		else if (filter instanceof Collection) {
			collection = (Collection<?>) filter;
		}
		else {
			collection = Collections.singletonList(filter);
		}

		for (Object o : collection) {
			if (Objects.equals(value, o)) {
				return true;
			}
// added additional check
			else if (o.toString().length() == 0 && value == null) return true;
		}

		return false;
	}
}
```

**Comment by melloware** [comment]
Awesome!   Let me try this...

**Comment by melloware** [comment]
Tested and working if you want to review my PR.  Good catch!
