### ISSUE TITLE
Calendar: add clear button in button bar

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#8112]
Can you please add a clear button in the calendar button bar to clear the calendar input ?

**Comment by jepsar** [comment]
Calendar is deprecated and does not have a button bar that I know of. Please be more specific.

**Comment by melloware** [comment]
Duplicate of this ticket: https://github.com/primefaces/primefaces/issues/3325

As you can see DatePicker has a Clear button:

![image](https://user-images.githubusercontent.com/4399574/143429381-7d4b2963-4c26-4e80-b3e3-7d2ce783416e.png)
