### ISSUE TITLE
SelectCheckboxMenu: Order of selected items not kept

### ISSUE THREAD

**Issue by RedRobin84** [primefaces/primefaces#8119]
Greetings,

When using selectCheckboxMenu component (with attribute multiple="true"), after each item selection, the order of selected items in Collection resets exactly to order of the items in collection, thats used as available items to choose (in this case f:selectItems component)

E.g. use collection List<Long> 1,2,3,4, users chooses items in this order 4,3,2, but the result is stored as 2,3,4. I am situation, where I need exactly the order of items that was chosen by the user. Now I need to use workaround with ajax request event="change" and manually sort those elements in viewBean.

Could this be a new feature (new attribute keepOrder or something? Or is it a bug?

Thanks!

![image](https://user-images.githubusercontent.com/33232157/143673784-dfaeef02-14b7-400d-8112-365e329f41dd.png)

**Environment**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. User component selectCheckboxMenu
2. add atribute multiple="true"
3. Select few items and see its stored in different order than displayed

**Expected behavior**
Sequence of the elements user choose should be stored in order, thats displayed on screen.
```

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project. 

It will help me debug the issue

**Comment by melloware** [comment]
Reproducer:
[pf-8119.zip](https://github.com/primefaces/primefaces/files/8582690/pf-8119.zip)

The values are just submitted in the form in the order they are in the DOM currently.

**Comment by melloware** [comment]
cc @ltlBeBoy not sure if you want to look at this one too.

**Comment by ltlBeBoy** [comment]
@melloware Yes, I will take a look at.

**Comment by ltlBeBoy** [comment]
Maybe a hidden input with the selection order would do the job.

**Comment by melloware** [comment]
Yep we need some sort of `Array` holding the order they were pushed into the list and then submit that array order to the backing bean.

**Comment by melloware** [comment]
OK changing the core component was too much of a nightmare and not worth it. So I added `itemSelect` event so now you can do this...

```xml
<p:ajax event="itemSelect" listener="#{checkboxView.onItemSelect}"/>
<p:ajax event="itemUnselect" listener="#{checkboxView.onItemUnselect}"/>
```

So now that you have an itemSelect and unselect you can track the order the items were clicked using AJAX.

```java
    public void onItemSelect(SelectEvent event) {
        FacesMessage msg = new FacesMessage();
        msg.setSummary("Item selected: " + event.getObject().toString());
        msg.setSeverity(FacesMessage.SEVERITY_INFO);

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void onItemUnselect(UnselectEvent event) {
        FacesMessage msg = new FacesMessage();
        msg.setSummary("Item unselected: " + event.getObject().toString());
        msg.setSeverity(FacesMessage.SEVERITY_INFO);

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
```

**Comment by javaone199** [comment]
It would be much better if it is done on client side. Ajax is not necessary.

**Comment by javaone199** [comment]
Hope the issue stays open until it is done on client side.

**Comment by melloware** [comment]
@javaone199 it won't be done.  As mentioned its because the options are just plain HTML `select` options and they are form submitted in the order is normal HTML5 behavior.  So it won't be done on the client side.  The workaround provided is your solution.

**Comment by javaone199** [comment]
To keep the order, a hidden input can be used to store the selected items (separated by a comma)that is syncing with the visible selections, replacing the html select. On server side, the component can convert the input string to a list as submitted value.

**Comment by melloware** [comment]
it could but it seems totally unnecessary to add a second hidden input.  If you want to submit a PR feel free...
