### ISSUE TITLE
AutoComplete: implement inline AJAX status

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8122]
**Description**
The [autoComplete](https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml?jfwid=3a3d0) fetches a list of data from the backend and provides suggestions based on this data. This data can come from different sources (e.g. Rest-Endpoints), so it can take a while when the data is arrived. Actually, for such use cases, we can provide a global [ajax-status](https://www.primefaces.org/showcase/ui/ajax/status.xhtml?jfwid=3a3d0) but another alternative would be to provide a _local status_ for such use cases.

**Describe the solution you would like**
A new property for `autoComplete` called `status`, which represents a delay in milliseconds before displaying the ajax status on the right side (or left side) within the input-text-field. If this `status = null`, then no ajax-status is shown.

The `autoComplete`with its spinner can look like [Right Icon Example](https://www.primefaces.org/showcase/ui/input/inputText.xhtml?jfwid=3a3d0 )

**Comment by melloware** [comment]
@nimo23 I think I get the idea.  Do you want it more like how PrimeReact does it where it shows the spinner icon right inside the input right?

See: https://primefaces.org/primereact/showcase/#/autocomplete

**Comment by nimo23** [comment]
@melloware exactly like that.

**Comment by jepsar** [comment]
I'll have a look at this, as it relates to the work I've been doing on the CommandButton
