### ISSUE TITLE
InputNumber: "minValue>0" shows js warning

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8125]
**Describe the defect**
Using something like this:  

```
<p:inputNumber 
    value="#{bean.value}" 
    decimalPlaces="0" 
    minValue="1" 
    maxValue="20"/>
```

shows the following warning in the javascript console:

> Warning: You've set a `minimumValue` or a `maximumValue` excluding the value `0`. AutoNumeric will force the users to always have a valid value in the input, hence preventing them to clear the field. If you want to allow for temporary invalid values (ie. out-of-range), you should use the 'invalid' option for the 'overrideMinMaxLimits' setting.

Looking in https://github.com/autoNumeric/autoNumeric/issues/543#issuecomment-619542552, there is indeed the option. In my opinion, this should be the default (so that the warning disappears), if PF detects a "minValue > 0"

**Environment:**
 - PF Version: _11.00 RC2_
 - JSF + version: _e.g. Mojarra 2.2.20_
 - Affected browsers: ALL_

**To Reproduce**
1. Use `p:inputNumber` with minValue="1" (or greater than 0)
2. Click on javascript console (e.g. firefox) and the warning shows up

**Expected behavior**
No warning and if PF detects a "minValue > 0" in `p:inputNumber`, then it should use the the `invalid` option for the `overrideMinMaxLimits` setting for this.

**Comment by melloware** [comment]
Can you try this MonkeyPatch by just adding this script to your JS file that loads after PF.

```javascript
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        this.cfg = cfg;
        this.input = $(this.jqId + '_input');
        this.hiddenInput = $(this.jqId + '_hinput');
        this.plugOptArray = cfg.pluginOptions;
        this.valueToRender = cfg.valueToRender;
        this.disabled = cfg.disabled;
        this.cfg.modifyValueOnWheel = false;
        this.cfg.overrideMinMaxLimits = 'invalid';

        //bind events if not disabled
        if (this.disabled) {
            this.input.attr("disabled", "disabled");
            this.input.addClass("ui-state-disabled");
            this.hiddenInput.attr("disabled", "disabled");
        }

        //Visual effects
        PrimeFaces.skinInput(this.input);

        this.wrapEvents();
        this.bindInputEvents();

        this.autonumeric = new AutoNumeric(this.jqId + '_input', this.cfg);

        if (this.valueToRender !== "") {
            //set the value to the input the plugin will format it.
            this.autonumeric.set(this.valueToRender);
            // GitHub #6940 blur firing too many change events
            this.autonumeric.rawValueOnFocus = this.valueToRender;
        }

        this.copyValueToHiddenInput();

        //pfs metadata
        this.input.data(PrimeFaces.CLIENT_ID_DATA, this.id);
        this.hiddenInput.data(PrimeFaces.CLIENT_ID_DATA, this.id);
    }
};
```

Just finding out if this does give the behavior you want?

**Comment by melloware** [comment]
@nimo23 when I have this

```xml
 <p:inputNumber id="input9" value="#{inputNumberView.input9}" minValue="1" />
```

With this new `this.cfg.overrideMinMaxLimits = 'invalid';` it prevents me from entering a negative number but i can enter `0.50`

![image](https://user-images.githubusercontent.com/4399574/144048031-125f9cee-52ae-4610-aad4-fa3892697ad3.png)

**Comment by nimo23** [comment]
Try to use `decimalPlaces="0"` to avoid `0.5`.

I think, when PF detects `p:inputNumber` with minValue>0, then it should set this `invalid` property so that no javascript warning is shown.

**Comment by melloware** [comment]
I do agree with you the current default has been complained about in the past.

**Comment by fanste** [comment]
This provided fix doesn't seem to be feature complete. You now always need `update="@this"` if the value is e.g. sent to the server using `blur` event.

Before this change:
- enter a number, it had to be > `0`
- ajax fires, everything is fine
- clearing the input was not possible (too bad), and therefore you never sent something invalid to the server (by ajax)

After this change:
 - enter a number, it could be `0`
 - ajax fires, serverside coerces the value to the minimum value (=`1`)
 - model contains value `1`, but the frontend still shows `0`

I don't know if this could be fixed easily or if this is just something you have to see and fix yourself by using `update="@this"`

**Comment by melloware** [comment]
Good point not sure this could be fixed easily to fit all use cases.

**Comment by NicolaIsotta** [comment]
inputNumber is still broken if minValue is a decimal between 0 and 1, just try this to see:
```xhtml
<p:inputNumber minValue="0.01"/>
```
I think that here:
https://github.com/primefaces/primefaces/blob/e8d3e2968dac710b725a9f2e761178c22063f0d0/primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js#L42-L45
the if condition should be:
```js
if (this.cfg.minimumValue > 0 || this.cfg.maximumValue < 0)
```
WDYT @melloware ?

**Comment by melloware** [comment]
@NicolaIsotta my first commit had it the way you suggest and Integration Tests fail I believe. Submit a PR and we can watch them run if you want!

**Comment by NicolaIsotta** [comment]
I'll open a new issue and a PR later

**Comment by melloware** [comment]
I submitted the fix so I can watch the Integration Tests run.
