### ISSUE TITLE
VisitTree - Datatable does not skip "unrendered" content into an inactive tab of dynamic parent

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#813]
I have 3 `<datatable>`, each into a `<tab>` of `<tabView>`. Each lazyModel of datatable is register on bean when the datatable is rendered.

On the page load,  the second tab is active. Only my second datatable is register.

When i click on a row, an event onRowSelect is fire with a `@this` process and the problem come here. When fire, the first tab is visit (and his content) but isn't rendered (tabView is dynamic here).
The visit on the datatable cause the register of my component in the bean.

When a component parent & content is not rendered because of dynamic parameter. This should be like a rendered false. We don't want to evaluate the value here, because the context can cause initialization problem.

Here I only have one datatable, but if I have the last tab of the tabView active on page load and like 10 tab with each a datatable. The process cause 9 register on the event. That a big problem for us.

edit: missing if

**Comment by tandraschko** [comment]
Please provide a example.

**Comment by kukel** [comment]
no response in almost 3 months... close?

**Comment by Julienng** [comment]
Sorry guys, I forgot to respond to this. I'm not able to reproduce the issue with the current release (5.3) and I don't know with one I use when I test this...
