### ISSUE TITLE
SelectOneMenu: Style Items

### ISSUE THREAD

**Issue by seinecle** [primefaces/primefaces#8135]
**Description**
Making it easier to add extra space between selectItem options in a selectOneMenu (and similar inputs)

**Describe the solution you would like**
Either:
- a better documentation on how to customize css for selectItems
- adding a new, dedicated attribute to selectOneMenu to adjust this space

**Additional context**
By default, the choice options in a selectOneMenu are really narrowly spaced. See screenshot for illustration
![image](https://user-images.githubusercontent.com/1244100/144121525-3c35b84d-8cfe-498d-a44f-f8fca633af4f.png)

**Example XHTML**
This example shows how a new attribute called "spacing" could introduced, here with a value of 10 which would end up defining the space between the selectItems:

```xml
                    <p:selectOneMenu id="annotator1" value="#{labellingBean.taskId}"  styleClass="menu" spacing="10">
                        <f:selectItem itemLabel="Select One" itemValue=""/>
                        <f:selectItems value="#{labellingBean.tasksIdsOfTheDesigner}"/>
                        <p:ajax event="change" listener="#{labellingBean.taskId}" />
                    </p:selectOneMenu>```

Thank you!

**Comment by melloware** [comment]
I don't see a selectOne in your screenshot?

And how to customize is documented right here: https://primefaces.github.io/primefaces/10_0_0/#/components/selectonemenu?id=skinning

You simply need to modify the CSS for `.ui-selectonemenu-items`

**Comment by tandraschko** [comment]
yeah
either you modify the theme or you add some style classes
CSS over compontent attributes
