### ISSUE TITLE
Faces 4.0 compatibility

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8137]
https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html

we should check if we can support 4.0 in the same codebase
4.0 hasnt introduced much breaking changes that we use in PF (e.g. JSP, ManagedBeans, ...)

**Comment by tandraschko** [comment]
first tests looks fine

**Comment by schlagges** [comment]
the link is broken, it's: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html
