### ISSUE TITLE
Tree: Drag and Drop does not work

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#8138]
**Describe the defect**
The drag and drop tree example in the showcase does not work.

**Reproducer**
Go to 
https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml 
and drag/drop any node

**Environment:**
 - PF Version: _11.0.0-RC2_
 - JSF + version: 
 - Affected browsers: _hrome, Firefox

**Comment by melloware** [comment]
Related to this maybe: https://github.com/primefaces/primefaces/issues/7613

cc @FlipWarthog

**Comment by tandraschko** [comment]
does it work in trunk?

**Comment by melloware** [comment]
What I don't understand is it has `dragdropScope="demo"` but I don't see demo anywhere in that example?  I assumed dragdropScope would be an ID of an element of what can be dragged and dropped onto?

**Comment by tandraschko** [comment]
no idea TBH, never used drag&drop

**Comment by melloware** [comment]
me neither 😄

**Comment by tandraschko** [comment]
sounds like just a context name: https://www.pureexample.com/jquery-ui/draggable-options-scope.html

**Comment by omerogrek** [comment]
Describe the defect
The drag and drop tree example in the showcase still does not work completely. 

Reproducer
Go to
https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml
and drag/drop any node on top of other node. Nodes cannot be dropped to other nodes.

Environment:

    PF Version: 11.0.0
    JSF + version:
    Affected browsers: Firefox

**Comment by melloware** [comment]
@omerogrek please open a new ticket.
