### ISSUE TITLE
Poll: support Number instead of Integer

### ISSUE THREAD

**Issue by schaeferm** [primefaces/primefaces#8142]
**Description**
With Polls interval I have noticed that EL may return a Double after a division was done. It would be nice when all parameters that currently accept Integer would be changed so that they accept Number.

**Describe the solution you would like**
Change all Integer parameters to Number parameters.

**Additional context**
Currently application devs would have to call the integer conversions in the EL expressions. This may look like the following: `#{(session.maxInactiveInterval / 10).intValue()}`

**Comment by schaeferm** [comment]
Just as a clarification: I used the Poll component as an example. I think that it would be a general improvement throughout the entire project. And when I think this further this wouldn't be actually limited to integer parameters but rather to all parameters that accept numbers. I don't know whether the documentation should be updated to reflect this change, as surly not in all cases floating point numbers are required/desirable.

**Comment by tandraschko** [comment]
if you have other cases or suggestions, feel free to create a list here
otherwise we limit it to poll currently

**Comment by schaeferm** [comment]
I have not done a detailed review of the current situation, but as this is related to how EL handles arithmetic operations and they can be used anywhere I thought it may be wise to review how numbers are processed/handled throughout the provided components.
