### ISSUE TITLE
TabView: Unexpected BoxShadow

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#8146]
**Describe the defect**
When Tab is clicked outside the label or icon, but still in the tab area (e.g. red dot below), that tab gains disturbing BoxShadow.
![image](https://user-images.githubusercontent.com/3907898/144752794-50d4540c-cd62-4a1d-bf2f-759490e5a4c4.png)

**Environment:**
 - PF Version: _10.0.0_ but also _v11.0.0-RC2_
 - JSF + version: _Mojarra 2.2.20_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to https://www.primefaces.org/showcase/ui/panel/tabView.xhtml
2. Click somewhere near the red dot in the above image
3. That light-blue box shadow is shown

**Expected behavior**
No shadow box.

**Workaround**
Add this style to your JSF page:
`body .ui-tabs .ui-tabs-nav li.ui-tabs-header.ui-tabs-outline {box-shadow: none}`

**Comment by tandraschko** [comment]
@mertsincan can you check this?

**Comment by mertsincan** [comment]
Hi,
The box-shadow/outline is required to show keyboard support. But, I made some minor fixes. Please check our Prime* library. Exp;
https://www.primefaces.org/primereact/tabview/

**Comment by jan-tosovsky-cz** [comment]
TBH I don't like showing that disturbing outline all the time. It could be optional or like in other libs diminishing after while or shown only on TAB keydown.
