### ISSUE TITLE
Problem with Datatable filter and sort display multiple empty rowsComponent: Title

### ISSUE THREAD

**Issue by tomtibbetts** [primefaces/primefaces#8148]
PrimeFaces 11.0.0-RC1
Wildfly 25 final
Harmony 3.0.1
Java 11

The data loads just fine in the table.  I can sort either of the columns multiple times and everything works.  The issue is if I filter a column then apply a sort.  The data in the table goes away leaving empty rows.  The number of the empty rows matches the number of rows that are rendered when filtered.  I basically copied this code from code for PrimeFaces circa 6.0.2, I think. And, it all works fine in that environment.  I welcome any feedback and help.  I've been stumped for days on this issue.

Thank you.

xhtml:
[code]<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">
                
    <ui:define name="title">My Dashboard</ui:define>
    <ui:define name="viewname">
        <li>Pages</li>
        <li>/</li>
        <li><p:link outcome="/empty">My Dashboard</p:link></li>
    </ui:define>

    <ui:define name="content">
        
				<div class="card">
			      <h:form id="reg">
					<h2>Member Registration</h2>
					
		      		<p:dataTable id="memberRegistrationTableId" var="memberRegistration" 
		      			value="#{testController.tests}" 
		      			editable="false" 
		      			rowIndexVar="rowIndex"
		      			class=".ui-datatable-striped"
		      			filteredValue="#{testController.filteredValues}"
		      			reflow="true" 
		      			showGridlines="true">
		      			
		      			<p:column headerText="Id" style="width: 35%;" sortBy="#{memberRegistration.testId}">
		      				<h:outputText value="#{memberRegistration.testId}"/>
		      			</p:column>

		      			<p:column headerText="Name" style="width: 35%;" sortBy="#{memberRegistration.name}" filterBy="#{memberRegistration.name}" filterMatchMode="contains">
		      				<h:outputText value="#{memberRegistration.name}"/>
		      			</p:column>

		      		</p:dataTable>
			      </h:form>
				</div>
				
            
    </ui:define>

</ui:composition>[/code]

Bean:
[code]@Named
@ViewScoped
public class TestController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private BSHIService bshiService;
	
	private List<Test> tests;
	
	private List<Test> filteredValues;
	
	@PostConstruct
	public void postConstruct() {
		tests = bshiService.getServiceName();
	}
	
	public List<Test> getTests() {
		return tests;
	}
	
	public List<Test> getFilteredValues() {
		return filteredValues;
	}

	public void setFilteredValues(List<Test> filteredValues) {
		this.filteredValues = filteredValues;
	}
}
[/code]
POJO
[code]public class Test {

    private Long testId;
	
	private String name;

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getTestId() {
		return testId;
	}

	public void setTestId(Long testId) {
		this.testId = testId;
	}

    @Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, testId);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Test other = (Test) obj;
		return Objects.equals(name, other.name) && Objects.equals(testId, other.testId);
	}
}[/code]

**Comment by tandraschko** [comment]
Try 11.0.0-RC2 and read the Migration guide If it still doesnt work

**Comment by tandraschko** [comment]
also the issue is invalid without reproducer - so either provide a running primefaces-test or check our current showcase

**Comment by tomtibbetts** [comment]
I’m not sure what you mean by reproducer.  Is there a specific format you’re looking for?  And, from what I understand, the current showcase is not at 10.0.0.  But I don’t know how to verify that.

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces-test

**Comment by tandraschko** [comment]
The current showcase is 11.0, which you also use 😄

**Comment by tomtibbetts** [comment]
Thank you, Thomas, for all your help!  I do have my issue resolved.

 

I apologize, but there is so much to learn and so much information, it feels overwhelming.
