### ISSUE TITLE
SelectManyMenu: add property `dropdown`

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8150]
**Description**
The menu items of a [SelectManyMenu](https://www.primefaces.org/showcase/ui/input/manyMenu.xhtml?jfwid=b2650) are always visible. 

**Describe the solution you would like**
Would be nice to add a property `dropdown` (with true and false) to `SelectManyMenu` to show a **dropdown** like 
[SelectOneMenu](https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml?jfwid=b2650).

**Comment by tandraschko** [comment]
Use SelectCheckboxMenu
