### ISSUE TITLE
InputNumber: add documentation how to handle percentages / custom converters

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8151]
**Description**
`p:inputNumber` cannot work with `f:convertNumber`. I have the value "0.001" which represents a **percentage format**. Using this, works as usual:

```
// prints 0.10 % for a value of 0.001
<h:inputText value="#{bean.myPercentValue}">
	<f:convertNumber type="percent" minFractionDigits="2"/>
</h:inputText>
```

Unfortunately, with `p:inputNumber`, I cannot handle `myPercentValue` :

```
// should print 0.10 % for a value of 0.001, but throws "javax.servlet.ServletException: Error converting  [0,10 %] to a decimal value;"
<p:inputNumber value="#{bean.myPercentValue}" symbol=" %" symbolPosition="s" decimalPlaces="2">
      <f:convertNumber type="percent" minFractionDigits="2"/>		
</p:inputNumber>
```

**Describe the solution you would like**
Maybe a property `type` can be provided for `p:inputNumber` where type can be `number` (standard) or `percent`:

```
// prints 0.10 % for a value of 0.001
<p:inputNumber value="#{bean.myPercentValue}" type="percent"/>
```

**Additional context**
[Similar](https://github.com/primefaces/primefaces/issues/1752)

**Comment by tandraschko** [comment]
Works fine for me, we use it similar in our apps with a custom converter

**Comment by nimo23** [comment]
@tandraschko yes, with a **custom converter**..but without a custom converter, it does not, because this

```
<p:inputNumber value="#{bean.myPercentValue}" symbol=" %" symbolPosition="s" decimalPlaces="2">
      <f:convertNumber type="percent" minFractionDigits="2"/>		
</p:inputNumber>
```

throws "javax.servlet.ServletException: Error converting  [0,10 %] to a decimal value;".

The reproducer is simple: 

Use this:

```
<p:inputNumber value="#{bean.myPercentValue}" symbol=" %" symbolPosition="s" decimalPlaces="2">
      <!-- use this converter-->
      <f:convertNumber type="percent" minFractionDigits="2"/>		
</p:inputNumber>
```

with `myPercentValue = 0.001 `(which represents 0.1%) (without a custom converter) and you see the error.

**Comment by tandraschko** [comment]
f:convertNumber is not a custom converter and wont work as InputNumber works with Numbers only, not string

**Comment by nimo23** [comment]
yes, this is why I recommend the following:

Maybe a property `inputType` can be provided for `p:inputNumber` where `inputType` can be `number` (standard) or `percent`:

```
// prints 0.10 % for a value of 0.001
<p:inputNumber value="#{bean.myPercentValue}" type="percent"/>
```

**Comment by tandraschko** [comment]
IMO a custom converter is enough and already supported

**Comment by nimo23** [comment]
JSF `f:convertNumber `provides the 3 common `types` :

> Specifies how the number string will be formatted and parsed. Valid values are "number", "currency", and "percent". Default value is "number".

I think, `p:inputNumber` could also provide these common types out of the box (without needing to write a custom converter). 

However, you can close this issue if you think.

**Comment by nimo23** [comment]
@tandraschko I created a custom percentConverter as you suggested:

```
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.ConverterException;
import javax.faces.convert.FacesConverter;

@FacesConverter("percentConverter")
public class PercentConverter implements Converter<Number> {

	@Override
	public Number getAsObject(FacesContext context, UIComponent component, String value) {
		if (context == null || value == null || value.trim().isBlank()) return null;
		Locale locale = context.getViewRoot().getLocale();
		NumberFormat percentFormat = NumberFormat.getPercentInstance(locale);
		Number number;
		try {
			number = percentFormat.parse(value);
		} catch (ParseException e) {
			throw new ConverterException(String.format("Cannot convert %s to Number", value));
		}
		return number;
	}

	@Override
	public String getAsString(FacesContext context, UIComponent component, Number value) {
		if (context == null || value == null) return null;
		Locale locale = context.getViewRoot().getLocale();
		NumberFormat percentFormat = NumberFormat.getPercentInstance(locale);
		percentFormat.setMinimumFractionDigits(3);
		return percentFormat.format(value);
	}

}
```

Using the converter in `h:inputText` works:

`<h:inputText value="#{bean.myPercentValue}" converter="percentConverter"/>`

However, when I  use the converter in `p:inputNumber`, it does not work:


```
<p:inputNumber id="exitProfitMin" value="#{bean.myPercentValue}"
					converter="percentConverter"
					symbol=" %"
					symbolPosition="s"
					decimalPlaces="4"
					minValue="0"
					maxValue="1"
					/>
```

 I get this error:

```
javax.servlet.ServletException: Error converting  [0,100 %] to a decimal value;
	at javax.faces.api@3.0.0.SP04//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:725)
	at javax.faces.api@3.0.0.SP04//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at 
..
Caused by: java.lang.NumberFormatException: Character , is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:518)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:401)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834)
	at deployment.test.war//org.primefaces.component.inputnumber.InputNumberRenderer.encodeEnd(InputNumberRenderer.java:114)
	... 90 more
```

Why does `p:inputNumber` not accept my `percentConverter`?

**Comment by nimo23** [comment]
The reason why the above did not work, is that `p:inputNumber` cannot accept my `getAsString()`-value coming from my `percentConverter`, because `org.primefaces.component.inputnumber.InputNumberRenderer.encodeEnd(InputNumberRenderer.java:114)`tries to encode a value like "0.1 %" to a `BigDecimal` which fails:

```
// from InputNumberRenderer.encodeEnd(InputNumberRenderer.java:114)
 try {
                decimalToRender = new BigDecimal(valueToRender);
        }
        catch (Exception e) {
                throw new IllegalArgumentException("Error converting  [" + valueToRender + "] to a decimal value;", e);
            }
```

Or is there another solution? One more reason why `p:inputNumber` should have a percent-converter out of the box:

```
// prints 0.10 % for a value of 0.001
<p:inputNumber value="#{bean.myPercentValue}" type="percent"/>
```

**Comment by tandraschko** [comment]
You have to return a number string, without %
As i said InputNumber works only with numbers

**Comment by nimo23** [comment]
It works with this solution:

```
@Override
public Double getAsObject(FacesContext context, UIComponent component, String value) {
    if (context == null || value == null || value.trim().isBlank()) return null;
    Double number;
    try {
        number = Double.valueOf(value) / 100;
    } catch (Exception e) {
    throw new ConverterException(String.format("Cannot convert %s to Number", value), e);
    }
    return number;
}

@Override
public String getAsString(FacesContext context, UIComponent component, Double value) {
     // cannot use NumberFormat and localized strings..
    if (context == null || value == null) return null;
        return String.valueOf(value * 100);
    }
```

>As i said InputNumber works only with **numbers**

It was irritating for me, that `p:inputNumber` cannot handle all those java **numbers** including `NumberFormat` (with localized strings) even if we put a jsf converter in it. Maybe `p:InputNumber` can be extended in future to accept jsf `f:convertNumber` with its NumberConverter.java.

**Comment by tandraschko** [comment]
i dont think we can support this easily as NumberFormat isnt public accessible in f:convertNumber.
also, as i already said, inputNumber is designed to work with numbers only
the formattings and symbols are applied on clientside and only numbers are posted/rendered between client<>server

maybe its better that you use a `p:inputText type=number` or something

**Comment by tandraschko** [comment]
i will change this ticket to a documentation ticket, so we can add your current converter and a small description

**Comment by djmj** [comment]
@nimo23 

Have a look at OmniFaces _ImplicitNumberConverter_ which can convert percentage or currency values without symbol. Maybe it is a fit for _p:inputNumber_?

- https://showcase.omnifaces.org/converters/ImplicitNumberConverter
- https://github.com/omnifaces/omnifaces/issues/387
