### ISSUE TITLE
SelectCheckboxMenu: showHeader="false" does not work

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8154]
**Describe the defect**
The property `showHeader` means the header of the panel where the search box is? If so, then `showHeader=false` has no effect, the header is always visible. 

I use this:

```
<p:selectCheckboxMenu  ..
   label="Select .."
   showHeader="false">
```

and expect that the header (with the search box and the "select all"-button) is not shown when the component is rendered. However, it is shown.

**Environment:**
 - PF Version: _11.0.0_RC2
 - JSF + version: Mojarra 2.2.20 
 - Affected browsers: ALL_

**To Reproduce**
1. Use any `p:selectCheckboxMenu`  with the following properties:
label="Select .."
showHeader="false"
2. Header is shown (instead of hidden)

**Expected behavior**
The panel header should be removed if `showHeader="false"`

**Comment by tandraschko** [comment]
please test

**Comment by tandraschko** [comment]
the change looks much more as it is, i only added some `if (this.cfg.showHeader)` around code blocks
