### ISSUE TITLE
DataTable filterBy/sortBy breaks when column ordering changes

### ISSUE THREAD

**Issue by markpalermo** [primefaces/primefaces#8159]
**Describe the defect**
When the column ordering has been changed on a DataTable, searching and filtering no longer function.
It would appear that the search/filter column name passed to the backing bean is no longer correct, likely using the column index to lookup the column name based on the initial ordering, rather than the updated ordering.

**Environment:**
Primefaces Showcase v11.0.0 RC2

**To Reproduce**
Reproducible in the Primefaces Showcase  DataTable Dynamic Columns page:
https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml

1. Go to https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml
2. Try filtering by "activity", filtering works.
3. Clear the "activity" filtering.
4. Move the "activity" column to be the first column, and click "Update" to refresh the table.
5. Try filtering or sorting any column
6. Note that neither filtering nor sorting function properly.

**Expected behavior**
Search and Sort should work after column ordering has changed

**Example XHTML**
```<div class="card">
    Available columns are <b>name</b>, <b>country</b>, <b>date</b>, <b>status</b> and <b>activity</b>.

    <h:form id="form">
        <div class="p-mt-3 p-mb-5">
            <p:inputText id="template" value="#{dtColumnsView.columnTemplate}" size="50" styleClass="p-mr-2"/>
            <p:commandButton update="customers" action="#{dtColumnsView.updateColumns}" value="Update"
                             process="@parent" icon="pi pi-refresh"
                             oncomplete="PF('customersTable').clearFilters()"/>
        </div>

        <p:dataTable id="customers" var="customer" value="#{dtColumnsView.customers}" widgetVar="customersTable"
                     filteredValue="#{dtColumnsView.filteredCustomers}">

            <p:columns value="#{dtColumnsView.columns}" var="column" headerText="#{column.header}" field="#{column.property}">
                <f:facet name="filter">
                    <p:datePicker selectionMode="range" onchange="PF('customersTable').filter()" rendered="#{column.type eq 'date'}"/>
                    <p:selectOneMenu onchange="PF('customersTable').filter()" rendered="#{column.type eq 'enum'}">
                        <f:selectItem itemValue="#{null}" itemLabel=""/>
                        <f:selectItems value="#{column.klazz.enumConstants}" />
                    </p:selectOneMenu>
                </f:facet>
            </p:columns>

        </p:dataTable>
    </h:form>
</div>
```

**Example Bean**
```@Named("dtColumnsView")
@ViewScoped
public class ColumnsView implements Serializable {

    private String columnTemplate = "name country date status activity";
    private List<ColumnModel> columns;
    private List<Customer> customers;
    private List<Customer> filteredCustomers;
    private Map<String, Class> validColumns;

    @Inject
    private CustomerService service;

    @PostConstruct
    public void init() {
        customers = service.getCustomers(10);

        validColumns = Stream.of(Customer.class.getDeclaredFields()).collect(Collectors.toMap(Field::getName, Field::getType));
        createDynamicColumns();
    }

    public void setColumns(List<ColumnModel> columns) {
        this.columns = columns;
    }

    public List<Customer> getCustomers() {
        return customers;
    }

    public void setCustomers(List<Customer> customers) {
        this.customers = customers;
    }

    public List<Customer> getFilteredCustomers() {
        return filteredCustomers;
    }

    public void setFilteredCustomers(List<Customer> filteredCustomers) {
        this.filteredCustomers = filteredCustomers;
    }

    public CustomerService getService() {
        return service;
    }

    public void setService(CustomerService service) {
        this.service = service;
    }

    public String getColumnTemplate() {
        return columnTemplate;
    }

    public void setColumnTemplate(String columnTemplate) {
        this.columnTemplate = columnTemplate;
    }

    public List<ColumnModel> getColumns() {
        return columns;
    }

    private void createDynamicColumns() {
        String[] columnKeys = columnTemplate.split(" ");
        columns = new ArrayList<>();

        for (String columnKey : columnKeys) {
            String key = columnKey.trim();

            if (validColumns.containsKey(key)) {
                columns.add(new ColumnModel(columnKey.toUpperCase(), columnKey, validColumns.get(key)));
            }
        }
    }

    public void updateColumns() {
        //reset table state
        UIComponent table = FacesContext.getCurrentInstance().getViewRoot().findComponent(":form:customers");
        table.setValueExpression("sortBy", null);

        //update columns
        createDynamicColumns();
    }

    public static class ColumnModel implements Serializable {

        private String header;
        private String property;
        private String type;
        private Class<?> klazz;

        public ColumnModel(String header, String property, Class klazz) {
            this.header = header;
            this.property = property;
            this.klazz = klazz;
            initType();
        }

        public String getHeader() {
            return header;
        }

        public String getProperty() {
            return property;
        }

        public String getType() {
            return type;
        }

        public Class<?> getKlazz() {
            return klazz;
        }

        private void initType() {
            if (Temporal.class.isAssignableFrom(klazz)) {
                type = "date";
            }
            else if (klazz.isEnum()) {
                type = "enum";
            }
        }
    }
}
```

```
@Named
@ApplicationScoped
public class CustomerService {

    private List<Customer> customers;
    private Country[] countries;
    private Representative[] representatives;
    private String[] names;
    private String[] companies;

    @PostConstruct
    public void init() {
        customers = new ArrayList<>();

        countries = new Country[]{
            new Country(0, "Argentina", "ar"),
            new Country(1, "Australia", "au"),
            new Country(2, "Brazil", "br"),
            new Country(3, "Canada", "ca"),
            new Country(4, "Germany", "de"),
            new Country(5, "France", "fr"),
            new Country(6, "India", "in"),
            new Country(7, "Italy", "it"),
            new Country(8, "Japan", "jp"),
            new Country(9, "Russia", "ru"),
            new Country(10, "Spain", "es"),
            new Country(11, "United Kingdom", "gb")};

        companies = new String[]{"Benton, John B Jr", "Chanay, Jeffrey A Esq", "Chemel, James L Cpa", "Feltz Printing Service",
            "Printing Dimensions", "Chapman, Ross E Esq", "Morlong Associates", "Commercial Press", "Truhlar And Truhlar Attys",
            "King, Christopher A Esq", "Dorl, James J Esq", "Rangoni Of Florence", "Feiner Bros", "Buckley Miller Wright",
            "Rousseaux, Michael Esq"};

        representatives = new Representative[]{
            new Representative("Amy Elsner", "amyelsner.png"),
            new Representative("Anna Fali", "annafali.png"),
            new Representative("Asiya Javayant", "asiyajavayant.png"),
            new Representative("Bernardo Dominic", "bernardodominic.png"),
            new Representative("Elwin Sharvill", "elwinsharvill.png"),
            new Representative("Ioni Bowcher", "ionibowcher.png"),
            new Representative("Ivan Magalhaes", "ivanmagalhaes.png"),
            new Representative("Onyama Limba", "onyamalimba.png"),
            new Representative("Stephen Shaw", "stephenshaw.png"),
            new Representative("Xuxue Feng", "xuxuefeng.png")};

        names = new String[]{"James Butt", "David Darakjy", "Jeanfrancois Venere", "Ivar Paprocki", "Tony Foller",
            "Adams Morasca", "Claire Tollner", "Costa Dilliard", "Juan Wieser", "Maria Marrier", "Jennifer Amigon",
            "Stacey Maclead", "Leja Caldarera", "Morrow Ruta", "Arvin Albares", "Darci Poquette", "Izzy Garufi",
            "Ricardo Gaucho", "Clifford Rim", "Emily Whobrey", "Kadeem Flosi", "Mujtaba Nicka", "Aika Inouye",
            "Mayumi Kolmetz", "Misaki Royster", "Silvio Slusarski", "Nicolas Iturbide", "Antonio Caudy",
            "Deepesh Chui", "Aditya Kusko", "Aruna Figeroa", "Jones Vocelka", "Julie Stenseth", "Smith Glick",
            "Johnson Sergi", "Francesco Shinko", "Salvatore Stockham", "Kaitlin Ostrosky", "Faith Gillian",
            "Maisha Rulapaugh", "Jefferson Schemmer", "Leon Oldroyd", "Rodrigues Campain", "Alejandro Perin",
            "Munro Ferencz", "Cody Saylors", "Chavez Briddick", "Sinclair Waycott", "Isabel Bowley", "Octavia Malet",
            "Murillo Malet", "Greenwood Bolognia", "Wickens Nestle", "Ashley Doe"};
    }

    public List<Customer> getCustomers(int number) {
        List<Customer> customers = new ArrayList<>();
        for (int i = 0; i < number; i++) {
            customers.add(
                    new Customer(i + 1000, getName(), getCompany(), getCountry(), getDate(),
                            CustomerStatus.random(), getActivity(), getRepresentative()));
        }
        return customers;
    }

    public List<Country> getCountries() {
        return Arrays.asList(countries);
    }

    public CustomerStatus[] getCustomerStatus() {
        return CustomerStatus.values();
    }

    public List<Representative> getRepresentatives() {
        return Arrays.asList(representatives);
    }

    private String getName() {
        return names[(int) (Math.random() * names.length)];
    }

    private Country getCountry() {
        return countries[(int) (Math.random() * countries.length)];
    }

    private String getCompany() {
        return companies[(int) (Math.random() * companies.length)];
    }

    private LocalDate getDate() {
        LocalDate now = LocalDate.now();
        long randomDay = ThreadLocalRandom.current().nextLong(now.minusDays(30).toEpochDay(), now.toEpochDay());
        return LocalDate.ofEpochDay(randomDay);
    }

    private int getActivity() {
        return (int) (Math.random() * 100);
    }

    private Representative getRepresentative() {
        return representatives[(int) (Math.random() * representatives.length)];
    }
}
```

**Comment by tandraschko** [comment]
anyone interessted in creating a test?

**Comment by newk5** [comment]
Just ran into this issue today aswell on our apps. Been looking at the code to try to understand why its failing but I've failed so far. I'm leaving my observations here maybe someone can figure it out:

- When a new column is added to the datatable, if the column is added somewhere in the middle or start, this issue happens ( it doesn't happen if the column is added last)
- After the column is added,  when you try to filter by that column,  ```DataTable#getFiltersByAsMap()``` returns a map with an additional entry for the new column, but this new entry seems to have duplicated the ```FilterMeta``` of the last column in the table for some reason.
- If we filter the map by active filters, it seems to point to the correct column (in my case column with id ```j_id_j:12```) but the entry inside  ```DataTable#getFiltersByAsMap()``` which points to that column still has a FilterMeta where .```field``` points to the old  ```j_id_j:12``` column.
- ```DataTable#getFiltersByAsMap()``` does not contain any entry with a FilterMeta.field that matches the newly added column

So the culprit seems to be  ```DataTable#getFiltersByAsMap()``` returning incorrect data, but I dont understand how

**Comment by fcjm** [comment]
I think I found the solution. My problem was that if you add a new column nothing works at all. You can also see it in the mentioned showcase (Dynamic Columns) when you add a new column (e.g. "representative").

After some time debugging I noticed that the functions isColumnSortable() / isColumnFilterable() from UITable are always called from within the encodeColumnHeader function of the DataTableRenderer. In PF10 it was here, where the sortByAsMap property was newly set.

For some reason though a line was dropped from PF10 to PF11 which resets the value. Please see below:

Primefaces 10

    default boolean isColumnSortable(FacesContext context, UIColumn column) {
        Map<String, SortMeta> sortBy = getSortByAsMap();
        if (sortBy.containsKey(column.getColumnKey())) {
            return true;
        }

        SortMeta s = SortMeta.of(context, getVar(), column);
        if (s == null) {
            return false;
        }

        // unlikely to happen, in case columns change between two ajax requests
        sortBy.put(s.getColumnKey(), s);
        setSortByAsMap(sortBy);
        return true;
    }

Primefaces 11

    default boolean isColumnSortable(FacesContext context, UIColumn column) {
        Map<String, SortMeta> sortBy = getSortByAsMap();
        if (sortBy.containsKey(column.getColumnKey())) {
            return true;
        }

        // lazy init - happens in cases where the column is initially not rendered
        SortMeta s = SortMeta.of(context, getVar(), column);
        if (s != null) {
            sortBy.put(s.getColumnKey(), s);
        }
        // setSortByAsMap(sortBy); is missing here

        return s != null;
    }

Although isColumnFilterable looks different to isColumnSortable in PF10, in PF11 they almost look identical. Adding a setFilterByAsMap(filterBy) at the same position as above fixed the filtering for me as well.

**Comment by tandraschko** [comment]
@fcjm can you please create a new issue + reproducer? i think its a bit different as this issue, i currently create a integration tests around the initial issue here

**Comment by tandraschko** [comment]
works fine when change your method to:

```
    public void updateColumns() {
        //reset table state
        DataTable table = (DataTable) FacesContext.getCurrentInstance().getViewRoot().findComponent(":form:customers");
        table.setSortByAsMap(null);
        table.setFilterByAsMap(null);

        //update columns
        createDynamicColumns();
    }
```

**Comment by newk5** [comment]
Sorry maybe I missunderstood, but I just pulled the PF12 snapshot today and tested this and noticed the issue still happens. Was a fix applied internally or do we just have to  manually do: 
``` 
 table.setSortByAsMap(null);
 table.setFilterByAsMap(null);
````
Every time we add/remove columns?

**Comment by tandraschko** [comment]
in theory only when you change the order or remove, new columns (added at the end) should be handled automatically

**Comment by newk5** [comment]
Yea columns added at the end always worked even before this fix. In my case I had 4 columns and I removed column 2, and filtering on column 3 stoped working, I thought since the issue was closed that meant the issue was fixed, it wasn't clear to me that the final solution to issue was to null the filter and sort map, I thought that was just a temporary workaround.

**Comment by tandraschko** [comment]
the reset code was always in the showcase for this example

**Comment by newk5** [comment]
I didn't notice that, thanks for clarifying 👍

**Comment by tandraschko** [comment]
also see: https://github.com/primefaces/primefaces/issues/8368
we introduced a helper method

**Comment by newk5** [comment]
Nice, I'll make sure to use that instead.

**Comment by danteCarvalho** [comment]
Was this fixed? anyway this use case was working for me in primefaces 10:
i have 6 buttons, they all change the columns on my Products table, and some have a custom filter p:selectOneMenu for boolean and p:selectOneMenu for entity/object.
Example: Button 1 show main columns, button 2 show price columns, button 3 show stock, button 4 expiration date, button 5 tax, 6 medicine. Related video: https://imgur.com/a/4hkZwHD or https://i.imgur.com/PIZOeqW.mp4
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8151466/primefaces-test.zip)

 I use ui:include to change the columns when the user clicks a button. I have a lazy p:dataTable , when i change the columns if you try to type anything on the filter, the request is sent, the count method is called, but the (Map<String, FilterMeta> filterBy) param never changes and is empty {}.

But if i change the columns to the initial columns everything goes back to normal, its like it only works with the initial values.

**Comment by tandraschko** [comment]
if you check the showcase, you need to reset the datatable after adding/removing/modifying columns/order:
https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml?jfwid=a632f

See ColumnsView.java / ln78

however, since 11.0 you need to use this code, like mentioned above in this ticket:
```
        DataTable table = (DataTable) FacesContext.getCurrentInstance().getViewRoot().findComponent(":form:customers");
        table.setSortByAsMap(null);
        table.setFilterByAsMap(null);
```

in 12.0, the following is enouhg:
```
        DataTable table = (DataTable) FacesContext.getCurrentInstance().getViewRoot().findComponent(":form:customers");
        table.resetColumns();
```

**Comment by danteCarvalho** [comment]
Ok its working now, thanks!!

**Comment by hodlonaut** [comment]
Hi, 

I am using primefaces version 12.0.0 - as a part of column re-ordering listener (invoked via <p:ajax event="colReorder" listener="#{myBean.onAjaxColReorder}"/> implementation I am calling the table.resetColumns() and table.resetDynamicColumns() on the table that's returned by the event.getSource().

However, subsequently whenever I try to performing column sorting on this table, the DataTable.loadLazyScrollData method is invoking my LazyDataModel implementation's "load" method with sortBy parameter referencing incorrect column - i.e. the key doesn't match the column whose heading I clicked to initiate a sort. Do you have any suggestions on how to resolve this?

**Comment by melloware** [comment]
Have you tried version 13.0.2 to see if this is already fixed or still an issue?

**Comment by hodlonaut** [comment]
I've just rebuilt our web app with 13.0.2 primefaces version and the issue is still happening as far as I can tell. I've confirmed that after the .resetColumns() call I am reconstructing a column list in correct order in my column manager class. Also if I perform export of the data to csv, the resulting csv also seems to have columns in the correct new order.

**Comment by hodlonaut** [comment]
I had a look in debugger. 

Looks like after I drag-n-drop a column (e.g. from 6th spot in the table to 2nd), the inspection of web page elements shows that the second column on screen now has id similar to myForm:myResultsTabs:myResultTable:myResultColumns:5), but when i later click on its heading to force a sort operation, the DataTable::initSortBy (which needs to re-initialize things, after my earlier resetColumns() call), goes through each column and invokes SortMeta.of - as a part of this code, the UI column with key myForm:myResultsTabs:myResultTable:myResultColumns:1 resolves to the field/sort property of the column I previously moved.. not the UI column with key myForm:myResultsTabs:myResultTable:myResultColumns:5.

I'm guessing this discrepancy is what causes incorrect sorting, the question is how to address it. Is there something extra I need to do as a part of my ajax listener implementation or as a part of ajax event handler definition itself?

as I mentioned earlier the xhtml has

<p:ajax event="colReorder" listener="#{myBean.onAjaxColReorder}" />

while the onAjaxColReorder java method does DataTable table = (DataTable) event.getSource(); followed by table.resetColumns();  followed by my reconstruction of a column list in my column manager implementation, with the order of columns being a new post-ordering one.

Any assistance would be much appreciated. @melloware @tandraschko

**Comment by melloware** [comment]
Ok can you create a PrimeFaces Test reproducer and open a new ticket against 13.0.2 please.

**Comment by danteCarvalho** [comment]
weird i had this problem last year and fixed using table.setSortByAsMap(null); but now its working without it.
