### ISSUE TITLE
Data components may cause infinite loop on exception

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#816]
When an exception occurs, PrimeExceptionHandler looks for an exception handler using visitTree which might break Data components and cause infinite loop.

**Comment by tandraschko** [comment]
Thats also possible with other components, not only with Data components.

Chaning PrimeExceptionHandler from
context.getViewRoot().visitTree(VisitContext.createVisitContext(context), visitCallback);
to
context.getViewRoot().visitTree(VisitContext.createVisitContext(context, null, ComponentUtils.VISIT_HINTS_SKIP_UNRENDERED), visitCallback);

should do the trick and is absolulety ok.

**Comment by cagataycivici** [comment]
What is the relation with unrendered components? Which line are you referring to @tandraschko ?

**Comment by tandraschko** [comment]
I thought it might be the same issue as #798.
