### ISSUE TITLE
DataTable: row selection via icon does not work anymore

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#8169]
**Describe the defect**
Before PrimeFaces 10.0.0 it was possible to select rows via clicking on an icon within p:dataTable instead of clicking on a table row itself. This was possible by deactivating row selection via disabledSelection="true" so normal row selection wouldn't be triggered but at the same time using data binding via the "selection" attribute to select a row by clicking an icon. Since PrimeFaces 10.0.0 the mechanism still works but the selected row is not highlighted. I guess, the problem is with the method encodeRow() from DataTableRenderer.java which says

`.add(selected && !disabled, "ui-state-highlight")` but has to be
`.add(selected, "ui-state-highlight")`

**Environment:**
 - PF Version: _10.0_

**Expected behavior**
The selected row should be highlighted after the respective icon was clicked.

**Comment by melloware** [comment]
I have a feeling this behavior change was intentional as it was fixed with this ticket: https://github.com/primefaces/primefaces/issues/6575

**Comment by melloware** [comment]
To me this is the correct behavior in that if selection is disabled then nothing should happen.  It seems to me you were previously using a "hole" in the code to design your solution and that hole has been closed.

I would like @Rapster @christophs78 @tandraschko thoughts on this...

**Comment by miedrl** [comment]
@melloware Thank you, this sounds reasonable. However, I would also like to hear the other ones thoughts on this :)

**Comment by tandraschko** [comment]
the new behavior sounds also correct for me

**Comment by Rapster** [comment]
Same here, new behavior sounds good

**Comment by melloware** [comment]
Sorry @miedrl going to close this. If your goal is selection only on certain elements that is possible with the "rowSelector" property where you can give it a jquery selector of what you want to cause selection such as a type or CSS class

**Comment by miedrl** [comment]
@melloware No problem. I will try out your solution with the "rowSelector" property though, sounds promisingly.

**Comment by melloware** [comment]
Let us know how it goes!
