### ISSUE TITLE
newTargetEndPoint isn't resolved in 'connectionChange' event (diagram)

### ISSUE THREAD

**Issue by brinkmac** [primefaces/primefaces#817]
When a ConnectionChangeEvent is fired, the new target endpoint is null. I assume, that the problem is Diagram.java line 181 (v5.3):
<code>
EndPoint newTargetEndPoint = model.findEndPoint(newTargetElement, params.get(clientId + "_targetEndPointId"));
</code>
The key should be "_newTargetEndPointId" .

**Comment by melloware** [comment]
Fixed with PR:  https://github.com/primefaces/primefaces/pull/4368
