### ISSUE TITLE
InputMask: InputMask does not clear mask symbols when autoClear=false

### ISSUE THREAD

**Issue by arnis87** [primefaces/primefaces#8177]
**Describe the defect**
`p:inputMask autoClear="false"` behaviour differs from how it worked in PrimeFaces 8 for empty field

**Environment:**
 - PF Version: _11.0_

**To Reproduce**
1. Create page with `inputMask autoClear="false"`
2. Observe the empty field behaviour compared to PF8

**Expected behavior**
When nothing is entered the mask should not be visible. 

***Example: PF8 vs PF11***
For mask: `FI99 9999 9999 9999 99`
- PF8
For invalid input the content is visible and mask is shown - this is expected

<img width="131" alt="image" src="https://user-images.githubusercontent.com/611617/146551248-5f99cfff-333f-4142-81c2-bf0f624a35a2.png">

 When empty the mask is not shown
<img width="133" alt="image" src="https://user-images.githubusercontent.com/611617/146551319-45da014f-7545-4417-9eb9-abf2afbb8d99.png">

- PF11
This is how empty field looks like
<img width="132" alt="image" src="https://user-images.githubusercontent.com/611617/146551068-358500c0-2e41-4de2-851b-1788691951f2.png">

**Comment by melloware** [comment]
We switched to this component which fixed so many bugs: https://github.com/RobinHerbots/Inputmask

I am using the property `clearIncomplete`... https://github.com/RobinHerbots/Inputmask#clearincomplete

 `.attr("clearIncomplete", inputMask.isAutoClear(), false);`

But I am wondering if it should be `clearMaskOnLostFocus` https://github.com/RobinHerbots/Inputmask#clearmaskonlostfocus

**Comment by arnis87** [comment]
Yes I think you are correct. To me it also seems based on the documentation they provide that `clearMaskOnLostFocus` is how it might have worked at least conceptually in PF8.

> Remove the empty mask on blur or when not empty remove the optional trailing part Default: true

**Comment by melloware** [comment]
Can you try this MonkeyPatch.  Just add this code to any JS file in your app that loads after PF.

```javascript
if (PrimeFaces.widget.InputMask) {
    PrimeFaces.widget.InputMask.prototype.applyMask = function() {
        this.cfg.clearMaskOnLostFocus = true;
        if (this.cfg.mask && !this.jq.is('[readonly]') && !this.jq.is(':disabled')) {
            this.jq.inputmask('remove').inputmask(this.cfg);
        }
    }
}
```

**Comment by arnis87** [comment]
Yes, this patch works

**Comment by melloware** [comment]
Fantastic! Thank for testing.

**Comment by melloware** [comment]
OK PR submitted. Thanks for reporting this.

**Comment by arnis87** [comment]
Will this be fixed in 11 elite patch as well?

**Comment by melloware** [comment]
That's up to @mertsincan
