### ISSUE TITLE
columnToggler doesn't hide when I use it with   <p:ajax and  update a component!

### ISSUE THREAD

**Issue by farzanehhazrati** [primefaces/primefaces#818]
I use primefaces5.3, I have  dataTable with 2 rows header,so I use columnGroup ,I put columnToggler for the second row of header and manually with a listener fix the colspan of  first row of header. so I should update the table with ajax.
when I put update at ajax (for columntoggler) , every thing is ok , but the check box of columntoggler doesn't hide when click out.
this is my html code:

```
<p:columnToggler  icon="ui-icon-extlink" datasource="tbl" trigger="zemanatToggler" id="zct"   >
                <p:ajax event="toggle" listener="#{dtBasicView.OnToggle}"     update=":#p:component('tbl')}"     />
            </p:columnToggler>
```

what can i do?
thanks.

**Comment by tandraschko** [comment]
use the forum for questions first.
