### ISSUE TITLE
OutputLabel: Duplicate onclick attribute rendered

### ISSUE THREAD

**Issue by dziobek** [primefaces/primefaces#8186]
**Describe the defect**

Problem looks like https://github.com/primefaces/primefaces/issues/6650

outputLabel  -OutputLabelRenderer->  "Duplicate attribute onclick."

First attr. onclick written after exec.:
 renderPassThruAttributes(context, label, HTML.LABEL_ATTRS);

... another is generated by:
 renderDomEvents(context, label, HTML.LABEL_EVENTS);

Please verify lines 155 and 156:
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java
https://github.com/primefaces/primefaces/blob/11.0.0/primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java

... or lines 144 and 145:
https://github.com/primefaces/primefaces/blob/10.0.0/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java

Please, consider adding/using a hashamp field in CoreRenderer to block out duplicate attributes

**Environment:**
 - PF Version: 11.0.0 (also 10.0.0)
 - JSF  Mojarra 2.2.20
 - Affected browsers: ALL

**To Reproduce**

Clone https://github.com/primefaces/primefaces-test.git 

Test with example code.

**Expected behavior**
onclick attribute should be rendered only once.

Rendered HTML should not fail this test: 
https://validator.w3.org/#validate_by_input

**Example XHTML**
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
        <h:outputScript name="test.js" />
    </h:head>
    <h:body>

        <h1>#{testView.string}</h1>
        <h:form id="frmTest">

            <p:outputLabel value="lbl test" onclick="console.log('attlblonclick')" />

        </h:form>

    </h:body>
</html>

```

**Rendered HTML**
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head id="j_idt2"><link type="text/css" rel="stylesheet" href="/primefaces_test_war_exploded/javax.faces.resource/theme.css.xhtml?ln=primefaces-saga&amp;v=10.0.0" /><link type="text/css" rel="stylesheet" href="/primefaces_test_war_exploded/javax.faces.resource/primeicons/primeicons.css.xhtml?ln=primefaces&amp;v=10.0.0" /><script type="text/javascript">if(window.PrimeFaces){PrimeFaces.settings.locale='pl_PL';PrimeFaces.settings.viewId='/test.xhtml';PrimeFaces.settings.contextPath='/primefaces_test_war_exploded';PrimeFaces.settings.cookiesSecure=false;}</script>
        <title>PrimeFaces Test</title><script type="text/javascript" src="/primefaces_test_war_exploded/javax.faces.resource/test.js.xhtml"></script></head><body>

        <h1>Welcome to PrimeFaces!!!</h1>
<form id="frmTest" name="frmTest" method="post" action="/primefaces_test_war_exploded/test.xhtml" enctype="application/x-www-form-urlencoded">
<input type="hidden" name="frmTest" value="frmTest" />
<label id="frmTest:j_idt7" class="ui-outputlabel ui-widget" onclick="console.log('attlblonclick')" onclick="console.log('attlblonclick')">lbl test</label><input type="hidden" name="javax.faces.ViewState" id="j_id1:javax.faces.ViewState:0" value="5129850080539613983:3475356256800619125" autocomplete="off" />
</form></body>
</html>
```

**Comment by melloware** [comment]
Thanks for the report PR submitted.
