### ISSUE TITLE
DefaultCommand: TextEditor contents is not ignored

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8190]
**Describe the defect**
Form with both TextEditor and DefaultCommand makes you not being able to use enter in the editor as it submits the form.

**Reproducer**
```xhtml
    <h:form>
        <h5 class="p-mt-0">Basic</h5>
        <p:textEditor widgetVar="editor1" value="#{editorView.text}" height="300"  />

        <h3 class="first">Custom Toolbar</h3>
        <p:textEditor widgetVar="editor2" value="#{editorView.text2}" height="300" placeholder="Enter your content">
            <f:facet name="toolbar">
             <span class="ql-formats">
                <button class="ql-bold"></button>
                <button class="ql-italic"></button>
                <button class="ql-underline"></button>
                <button class="ql-strike"></button>
            </span>
                <span class="ql-formats">
                <select class="ql-font"></select>
                <select class="ql-size"></select>
            </span>
            </f:facet>
        </p:textEditor>

        <p:commandButton id="fh" value="gj" update="@form"/>
        <p:defaultCommand target="fh"/>
    </h:form>
```

**Environment:**
 - PF Version: 12.0.0-SNAPSHOT
 - JSF + version: Mojarra 2.3
 - Affected browsers: Chrome

**Comment by jepsar** [comment]
Possible duplicate of #4984 but that was tagged 8.0 RC1

**Comment by jepsar** [comment]
I just tried with the showcase on 12 and was able to reproduce this.

**Comment by melloware** [comment]
Something must have changed with a refactoring.

**Comment by jepsar** [comment]
No, it is no regression. The prevention is

https://github.com/primefaces/primefaces/blob/147af695f4435dc92c3319e723687cd0e28afcd3/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js#L47-L50

but the TextEditor contents is a node tree in `div class="ql-editor"`, so we should exclude enters from any node in the editor.

Can be assigned to me.
