### ISSUE TITLE
Schedule : event backgroundColor attribute setting not being honored

### ISSUE THREAD

**Issue by tarwork** [primefaces/primefaces#8193]
The p:schedule component is not honoring the backgroundColor attribute being set to events.

 - PF Version: 10.0.7 and 11.0.0
 - JSF + version: Mojarra 2.2.20
 - Java version : 1.8
 - Affected browsers: Chrome, Firefox and Edge on Windows

**Example XHTML**
```html
<p:schedule id="schedule" value="#{bean.eventModel}" widgetVar="myschedule" minTime="06:30:00" maxTime="18:30:00" allDaySlot="false" view="timeGridWeek" slotDuration="00:15:00" />
```

**Example Bean**
```java
ScheduleModel eventModel = new DefaultScheduleModel();
DefaultScheduleEvent<?> event = DefaultScheduleEvent.builder()
                                    .title("test event")
                                    .startDate(LocalDateTime.now())
                                    .endDate(LocalDateTime.now().plusHours(1))
                                    .description("event description")
                                    .backgroundColor("pink")
                                    .textColor("black")
                                    .build();
                             eventModel.addEvent(event);
```
**Observed Behavior**
The event shows up with the default blue color with black text. So text color is being honored since the default is white but the background color is not being honored.

**Expected Behavior**
The event shows up with pink background color with black text.

**Comment by melloware** [comment]
@tarwork this is not a bug this is as designed in FullCalendar.  If you go to the Showcase here: http://primefaces.org/showcase/ui/data/schedule/basic.xhtml

Click on Week view and you will see the background color of green.  IT only appears in DAILY or WEEKLY mode but not in Monthly Mode

![image](https://user-images.githubusercontent.com/4399574/147265719-59c4a968-9323-49ba-9a67-c71f7baffaba.png)

**Comment by tarwork** [comment]
@melloware 

Hmmm, thank you for pointing that out. I should have mentioned for this particular app I am using the week view as my default. But my week view shows only blue events...

<p:schedule id="schedule" value="#{bean.eventModel}" widgetVar="myschedule" minTime="06:30:00" maxTime="18:30:00" allDaySlot="false" **view="timeGridWeek"** slotDuration="00:15:00" />

Looks like I need to investigate further to see why the color change is not being honored on my local installation where as the showcase is fine.

Here is what I am seeing:

![image](https://user-images.githubusercontent.com/67923229/147266559-b9ca56ea-924e-497a-84dd-877ae9b446de.png)

**Comment by melloware** [comment]
Yep then compare what you are doing to the Showcase.  The showcase is setting background color to green and its working properly.
