### ISSUE TITLE
Class annotated by @PushEndpoint is not discovered in web-fragments

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#82]
I have an issue with new Primefaces 5.0 Push API. 

I've annotated a class with @PushEndpoint which was located in web-fragment project. It wasn't discovered during push servlet initialization.

When I moved this class to my main web application project (which depends on web-fragment project), and thus it was deployed in WEB-INF/classes, the class was successfully discovered.

Clearly it is a bug, that web-fragment JARs on classpath are not searched for @PushEndpoint. My project is constructed from couple of web-fragments and every independent web-fragment should be able to define its own @PushEndpoints.

This issue blocks migration of my project from PF4 to PF5.

tomiak.marcin

**Comment by indracrg** [comment]
Hello, we have the same problem with PF 5.2.8 and Atmosphere 2.3.4-SNAPSHOT and we were wondering if there are any news about this. We actually didn't had @PushEndpoints in web-fragment and it worked just fine, but now we need it and found this problem. 

Thanks.

**Comment by jcetkov** [comment]
+1

**Comment by jovan-fernandes** [comment]
+1

**Comment by tandraschko** [comment]
Could anyone provide a very very small sample app with maven+jetty?

**Comment by melloware** [comment]
This is an Atmosphere issue I just reported here:  https://github.com/Atmosphere/atmosphere/issues/2289

**Comment by tandraschko** [comment]
Thanks for your help!
