### ISSUE TITLE
{RowsPerPageDropdown} is not validated.

### ISSUE THREAD

**Issue by luisalves00** [primefaces/primefaces#821]
The {RowsPerPageDropdown} is not checked on the server side, so it can be modified:

<select autocomplete="off" class="ui-paginator-rpp-options ui-widget ui-state-default ui-corner-left" name="j_idt88:j_idt89_rppDD" id="j_idt88:j_idt89_rppDD"><option value="5">5</option><option selected="selected" value="10">10</option><option value="15">15</option></select>

we can add the following option:

<option value="15">100000000000</option>

and call the server, which will cause a lot of load on the DB. 

We can do a validation on the load method, but a validation or fallback to 10 if the values are different from the allowed ones would be appreciated.

**Comment by kukel** [comment]
@cagataycivici: should it be checked against all the allowed values shall I create a PR?

**Comment by tandraschko** [comment]
@kukel Would you like to demonstrate how you would fix the problem?

**Comment by tandraschko** [comment]
Duplicate: https://github.com/primefaces/primefaces/issues/3519
