### ISSUE TITLE
Diagram: elements event click

### ISSUE THREAD

**Issue by tecbea** [primefaces/primefaces#822]
Hi,
element/link click event behavior , on diagram is a must have, since after a element is created, name cannot be renamed

best,
tecbea

**Comment by jepsar** [comment]
What library is used here? https://github.com/jsplumb/jsplumb ?

**Comment by melloware** [comment]
Yep currently it is jsPlumb 2.1.0.  We really should break the widget out into two files right now it has the compressed JSPlumb right in the widget.js.

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primefaces/issues/2667 so closing this ticket since the other one is more detailed on what events are missing besides just click.
