### ISSUE TITLE
Tooltip: multiple elements for target selector

### ISSUE THREAD

**Issue by rds76** [primefaces/primefaces#8226]
**Describe the defect**
Tooltip is showed on first element always

**Environment:**
 - PF Version: _ALL_
 - JSF + version: _Mojarra 2.2_
 - Affected browsers: _ALL_

**Expected behavior**
Tooltip should follow mouse pointer

**Example XHTML**
```html
<p:tooltip for="@(.anyClass)"/>
<a href="..." class="anyClass"></a>
<a href="..." class="anyClass"></a>
```

**Comment by tandraschko** [comment]
p:tooltip doesnt even have a `target` attribute

**Comment by rds76** [comment]
sorry my fault, correct is `for`, updated...

**Comment by rds76** [comment]
btw, same problem happens with `delagate` option and even worst, it delagates event to only first element for selector and only in case it has ID attribute.

**Comment by melloware** [comment]
@rds76 in your case don't you want a global tooltip? https://primefaces.github.io/primefaces/11_0_0/#/components/tooltip?id=global-selector

```xml
<p:tooltip globalSelector="a" />
```

That would do all anchor elements on the page?   What you have reported is still an issue but just from looking at your use case above it seems like globalSelector was what you wanted?

**Comment by rds76** [comment]
global tooltip is not proper here, I need to use same description (html) for multiple page button, so repeating same text in `title` for each element unnecessarily enlarge source code so single tooltip is better here

**Comment by melloware** [comment]
OK a PR would be welcome!
