### ISSUE TITLE
DonutChartOptions: cutout should be used instead cutoutPercentage

### ISSUE THREAD

**Issue by RegiK123** [primefaces/primefaces#8228]
After migration form PF10 to PF11  donutChartOptions.setCutoutPercentage stop working it is every time default 50% as i check in the PF code in the class responsible for setting this pram is still old "cutoutPercentage " insted of "cutout"
see: https://www.chartjs.org/docs/latest/getting-started/v3-migration.html
See also the package org.primefaces.component.donutchart; 
method encodeOptions(FacesContext context, String type, Object options) 

- [TODO: update cutoutPercentage to cutout ]

**Comment by RegiK123** [comment]
@melloware we need this fix for PF11

**Comment by tandraschko** [comment]
If you have PrimeFaces Elite, its up to @mertsincan to merge it to this branch
otherwise you can go PrimeFaces PRO

**Comment by melloware** [comment]
@ReginaGialbas I have tagged it Elite but like Thomas said its up to PrimeTek to decide what goes in an Elite release.  If you have PRO support you can request it.

**Comment by RegiK123** [comment]
@melloware you still have bug in yours solution, if it is a string ended with % in js you need to also put it as a String (in '')

**Comment by melloware** [comment]
@ReginaGialbas can you review this PR: https://github.com/primefaces/primefaces/pull/8263

**Comment by RegiK123** [comment]
@melloware ok so still it is a problem in this PR, 
the best option is check if you have this "%" and if yes
 writer.write(",cutout:" + "'" + donutOptions.getCutout() + "'");
and if not 
 writer.write(",cutout:" + donutOptions.getCutout());

https://www.chartjs.org/docs/3.3.1/charts/doughnut.html
"The portion of the chart that is cut out of the middle. If string and ending with '%', percentage of the chart radius. number is considered to be pixels." number|string

**Comment by melloware** [comment]
OK check again I actually fixed it the correct way switching it to `Object` and then our Chart `writeValue` method detects whether its a `Number` or `String` and adds the quotes appropriately.
