### ISSUE TITLE
Chips: Chips broken after migration to PF11

### ISSUE THREAD

**Issue by RegiK123** [primefaces/primefaces#8229]
**Describe the defect**
Chips broken after migration to PF11, chip area size, multi line chips.

**Environment:**
 - PF Version: 11.00
 **To Reproduce**
1.Open http://www.primefaces.org:8080/showcase/ui/input/chips.xhtml?jfwid=c7ef3
2. add many chips
3. modify the element area like this 
![image](https://user-images.githubusercontent.com/26834946/148062680-e782464b-4e4c-4328-81f8-4169acc37ae7.png)
**Expected behavior**
Old behavior:
![image](https://user-images.githubusercontent.com/26834946/148061343-3f5ea3b0-ab8c-4142-af3e-eb6ba7cb0928.png)
New behavior:
![image](https://user-images.githubusercontent.com/26834946/148061367-a4e87fb4-0e85-4e07-975f-779c39b15226.png)
also when I need bigger area and I change the size instead of changing size of the area it also change the size of the chips .... 
![image](https://user-images.githubusercontent.com/26834946/148061533-e330e15b-35eb-469c-b54c-193b1a833910.png)

**Comment by tandraschko** [comment]
please follow the issue template

**Comment by RegiK123** [comment]
> please follow the issue template

updated
