### ISSUE TITLE
Chips: Chips size and behavior broken

### ISSUE THREAD

**Issue by RegiK123** [primefaces/primefaces#8231]
**Describe the defect**
In version PF10 i can change the size of tags area and have multiple tags in multiple lines. In PF 11 when i change the size of chip area from one line to multiline , the the tags are as big as this area. Also when we have many tags in more the one line it start to cover each other. Bug is also visible on primefaces page 
https://www.primefaces.org/showcase/ui/input/chips.xhtml?jfwid=e54ee
see also how it work on previous version 
https://www.primefaces.org/showcase-v8/ui/input/chips.xhtml

**Reproducer**
https://www.primefaces.org/showcase/ui/input/chips.xhtml?jfwid=e54ee

**Environment:**
 - PF Version: 11.00

**To Reproduce**
1. Go to '[...](https://www.primefaces.org/showcase/ui/input/chips.xhtml?jfwid=e54ee
)'
2. Add multiple chips
3.
![image](https://user-images.githubusercontent.com/26834946/148072048-440a7005-9f13-4b69-9baf-960581b66a1d.png)
Chips cover each other
3. Open chrome dev tool
4. select element
![image](https://user-images.githubusercontent.com/26834946/148072271-f8308f70-504e-43f9-945a-84b5acba0d40.png)
add style height:500px
![image](https://user-images.githubusercontent.com/26834946/148072626-5483c356-8a90-4f51-84f5-2d72f3d453cc.png)
No only chip area was change but also every single chip as on picture

**Expected behavior**
I should be able to change chip area without changing chips size. In multiple chips should have space between.

**Example XHTML**
```html
<div class="card ui-fluid">
    <h5>Basic</h5>
    <p:chips style="height: 500px;" />
</div>
```

**Comment by jepsar** [comment]
PR requires a fix in the themes as well. See PR for details.

**Comment by irieill** [comment]
I would like to extent this issue.
```html
<div class="ui-fluid">
  ...
  <div class="ui-inputgroup">
    ...
    <p:chips />
  </div>
</div>
```
Chips is not stretched to full container size. I think this could be fixed alongside.
