### ISSUE TITLE
Printer: CSS styles are no longer working

### ISSUE THREAD

**Issue by tschia** [primefaces/primefaces#8232]
**Describe the defect**
The Printer component in PrimeFaces 11 appears to no longer support CSS styles. 

In previous versions of PrimeFaces including 6.2, 8, and 10 this was a supported feature. 

I suspect this is due to the migration/upgrade to Print.js described here:
https://github.com/primefaces/primefaces/issues/7288 

Print.js does support passing CSS Styles as a configuration to the JQuery function as documented here, but it appears PrimeFaces is not making use of this capability.
https://printjs.crabbly.com/

**Reproducer**
There are 3 PF projects here with Payara Micro that can found here.
https://github.com/tschia/primefaces-printer-demo

6.2 and 10 are provided to show that this behavior used to work. 11 is provided to show that the expected behavior no longer works.

Instructions to run the projects are included in the Project README file. 

**Environment:**
 - PF Version: _11.0_
 - JSF + version: _Mojarra 2.3.14.payara-p3_
 - Affected browsers: _Tested in Chrome and FireFox_

**To Reproduce**
1. Follow the README instructions to run the application
2. Open the application in a browser (see README for URL path)
3. Click the **Print All Records** button

**Expected behavior**
1. The "Don't Show this Button" button should not appear in the print preview
2. The "This text is blue but should print red" text should be red in the print preview

**Example XHTML**
```html
    <h:outputStylesheet name="styles.css" />

    <p:commandButton value="Print All Records" type="button" >
        <p:printer target="thingsToPrint" />
    </p:commandButton>
    <br/><br/>

    <h:panelGroup id="thingsToPrint">
        <span class="blue-text print-red-text">This text is blue but should print red </span>
        <br/>
        <p:commandButton value="Don't Show This Button on Print" styleClass="hide-on-print" />
    </h:panelGroup>
```

**Example CSS**
```java
.blue-text {
    color: blue
}

@media print{
    .hide-on-print {
        display: none !important;
    }
    #thingsToPrint .print-red-text {
        color: red;
    }
}
```

**Comment by melloware** [comment]
@tschia I don't see in the PrintJS settings where you can tell it what CSS classes to respect?  The only reference to CSS I see is styling the header.

**Comment by melloware** [comment]
Oh is it `targetStyles` ???

**Comment by melloware** [comment]
Added a new property so you can pass any JSON options to `configuration` on Printer so it future proofs it for PrintJS.

**Comment by tschia** [comment]
Sorry wasn't able to get back to you for your questions. Looks like you found it, appreciate the quick response!

**Comment by melloware** [comment]
Now that jQuery Print has fixed the canvas issue I am going to revert back to using it so it makes it more backward compatible for older PF users!

**Comment by AzharMobeen** [comment]
Dear @melloware 
I think I'm also facing the same issue while printing it's not keeping the page formating:
[Please check your official link](https://www.primefaces.org/harmony/invoice.xhtml)

I'm using PF 11 and Harmony 4.1.0. I have checked all the themes have the same issue could you advise.

**I have also tested with primefaces version 10 and it's working fine** but I don't want to downgrade PF version please fix this and let me know if any further clearification required or if you want me to create seperate issue.

**Comment by melloware** [comment]
@AzharMobeen this has been fixed for 12.0.0.  The best workaround you can do for 11.0.0 is to create your own PrinterBehavior and copy the code from PF.

See: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/behavior/printer/PrinterBehavior.java

**Comment by AzharMobeen** [comment]
@melloware Thanks for your reply. Actually I never did this bofore. Could you please tell me how I need to do use this or simply copy this class **PrinterBehavior.java** into my source code will it work out ?

**Comment by melloware** [comment]
1. Copy the class to lets say `com.yourproj.PrinterBehavior`.

2. Change this line...
```java
@ResourceDependency(library = "primefaces", name = "printer/printer.js")
```
to your downloaded version in your WAR of  `jquery.Print` version 1.6.2

3. in your `faces-config.xml`

```xml
    <behavior>
        <behavior-id>org.primefaces.component.PrinterBehavior</behavior-id>
        <behavior-class>com.yourproj.PrinterBehavior</behavior-class>
    </behavior>

**Comment by AzharMobeen** [comment]
I tried to add <behavior> tag in faces-config.xml but it's giving error:
**Element behavior not allowed here**

It would be great if you could share some example.

**Comment by melloware** [comment]
When in doubt reference PrimeFaces: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/faces-config.xml

That faces-config.xml has it correctly

**Comment by melloware** [comment]
Here is a fully working sample project:
[printer-override.zip](https://github.com/primefaces/primefaces/files/8605392/printer-override.zip)


Just unzip it and run `mvn clean jetty:run` and go to localhost:8080/primeface-test to see it in action

**Comment by AzharMobeen** [comment]
Thanks @melloware I did all above changes and it's working fine. Is there any tentative date for PF 12 ?

**Comment by melloware** [comment]
no date that I know of its when PrimeTek feels like releasing.  They mentioned trying to release every 6 months which would make June the target.

**Comment by AzharMobeen** [comment]
Okay @melloware, Thanks for your quick help.

**Comment by pawkli95** [comment]
> ```
>  <behavior>
>         <behavior-id>org.primefaces.component.PrinterBehavior</behavior-id>
>         <behavior-class>com.yourproj.PrinterBehavior</behavior-class>
>     </behavior>
> ```

Hi, I have some problems understanding step nr 2, could you show some example
Best regards,
Pawel

**Comment by melloware** [comment]
Just download this file it has everything you need to see it working: https://github.com/primefaces/primefaces/files/8605392/printer-override.zip

**Comment by pawkli95** [comment]
> 1. Copy the class to lets say `com.yourproj.PrinterBehavior`.
> 
>     2. Change this line...
> 
> 
> ```java
> @ResourceDependency(library = "primefaces", name = "printer/printer.js")
> ```
> 
> to your downloaded version in your WAR of `jquery.Print` version 1.6.2
> 
>     3. in your `faces-config.xml`
> 
> 
> ```
>     <behavior>
>         <behavior-id>org.primefaces.component.PrinterBehavior</behavior-id>
>         <behavior-class>com.yourproj.PrinterBehavior</behavior-class>
>     </behavior>
> ```



> Just download this file it has everything you need to see it working: https://github.com/primefaces/primefaces/files/8605392/printer-override.zip

Thanks for quick response. In this repo in class PrintBehaviour there is no @ResourceDependency pointing to jQuery.printer.js. That's why I am confused.

**Comment by melloware** [comment]
Oh yeah in that demo I cheated and put...

```xml
	<h:head>
		<title>PrimeFaces Test</title>
		<h:outputScript name="test.js" />
		<h:outputScript name="printer/printer.js" />
	</h:head>
```

I just included in on the page manually.

**Comment by pawkli95** [comment]
Thanks for your help :) @melloware
