### ISSUE TITLE
LinkButton: Enable/Disable via JS does not work correctly

### ISSUE THREAD

**Issue by iki-hacon** [primefaces/primefaces#8233]
**Describe the defect**

**Defect 1 (disable => enable):**

Create p:linkButton
`<p:linkButton id="btn" widgetVar="btn" disabled="true" value="test"/>`

Try to enable the button later with Javascript:
`PF('btn').enable()`

Expected behavior: Button works, Link is clickable
Actual behaviour: Button does not work, no clickable link

**Defect 2 (enable=> disable):**

Create p:linkButton
`<p:linkButton id="btn" widgetVar="btn" disabled="false" value="test"/>`

Try to disable the button later with Javascript:
`PF('btn').disable()`

Expected behavior: Button deactivated, no interaction possible
Actual behavior: Button does not respond to mouse (correct), but link can still be accessed by "tab" and activated by "enter/return"

**Environment:**
 - PF Version: _10.0_
 - Affected browsers: _ALL_

**Comment by melloware** [comment]
Works fine for me on the Showcase:

1. Go here https://www.primefaces.org/showcase/ui/button/linkButton.xhtml

2. Press F12 to bring up the developer Console.

3. Enter `PrimeFaces.widgets.widget_j_idt319.enable();`

4. Enter `PrimeFaces.widgets.widget_j_idt319.disable();`

**Comment by iki-hacon** [comment]
@melloware no it does not - only on the first glance

1. Go here https://www.primefaces.org/showcase/ui/button/linkButton.xhtml
2. Press F12 to bring up the developer Console.
3. Enter `PrimeFaces.widgets.widget_j_idt319.enable();` => It looks enabled, but there is no link to click
4. Enter `PrimeFaces.widgets.widget_j_idt313.disable();` (please note, this is the second button "new tab"!) => Looks disabled. But you can reach the link by pressing "Tab / Shift+Tab" and activate it by pressing enter/return. A new tab opens, even if the linkButton is disabled.

Tested in both FF and Chrome

**Comment by iki-hacon** [comment]
Some additional remarks:

regarding step 3: this only happens, if the linkButton was disabled at the first rendering. It works if the button was not disabled first and only disabled by javascript later.

There is a difference between the disable()(endable() by Javascript and the disabled/enabled rendering when updating the component the usual JSF way.

**Comment by melloware** [comment]
Got it.  I see. Its the `disabled="true"` is rendering the component in a way it can't ever be enabled.

**Comment by iki-hacon** [comment]
We have a workaround for the `widget.disable()`:

`$(PF('button').link[0]).attr('tabindex', '-1').attr('aria-disabled', 'true');`
This removes the link from the tab order and completely disables the button.

Later, when we do `widget.enable()`, we do the reverse:
`$(PF('button').link[0]).removeAttr('tabindex').removeAttr('aria-disabled');`

But we still can not enable a button, which has initially been rendered disabled.

**Comment by jepsar** [comment]
Fix probably will look a lot like https://github.com/primefaces/primefaces/commit/15bb18c75886269f8bc94f48e038b8a9f98d94e2 / https://github.com/primefaces/primefaces/pull/8219

We might be able to DRY some of the JavaScript

**Comment by melloware** [comment]
@jepsar yep similar but even easier since it already had a widget. I just had to render the button as normal instead of a custom SPAN if it was disabled.
