### ISSUE TITLE
Default behaviour for keypress enter in dialogs

### ISSUE THREAD

**Issue by julianaiglsdorfer** [primefaces/primefaces#8237]
Primefaces Version 10.0

I'm developing a Java EE Business Application with PF 10 and would like to know what is the current default behaviour of Primefaces when keypress Enter inside a Dialog? Could it be that there are differences between keypress Enter when an input Element is active inside an Dialog?

I would like to achieve that on enter always the last button (which is the submit button in my application) within the dialog is executed. Is there a good way to override/extend the behaviour without overriding another behaviour or losing functionality?

Many thanks in advance.

**Comment by melloware** [comment]
Isn't this what you want: https://www.primefaces.org/showcase/ui/misc/defaultcommand/basic.xhtml
