### ISSUE TITLE
InputNumber: maxlength not respected

### ISSUE THREAD

**Issue by Teutron-flo** [primefaces/primefaces#8238]
**Describe the defect**
It looks like the maxlenght value for InputNumbers didn't work.

**Reproducer**
In showcase V11:

https://www.primefaces.org/showcase/ui/input/inputText.xhtml

Add to the Basic field:

`<input id="j_idt311" name="j_idt311" type="text" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-filled" role="textbox" aria-readonly="false" aria-disabled="false" **maxlength="3"**>`

You are only able to put in 3 chars.

https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml

Add to the No Configuration field:

`<input id="j_idt311:input1_input" name="j_idt311:input1_input" type="text" autocomplete="off" value="0.0" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-filled" aria-labelledby="j_idt311:j_idt313" inputmode="decimal" data-p-label="No Configuration" data-p-con="javax.faces.Double" data-p-hl="inputnumber" role="textbox" aria-readonly="false" aria-disabled="false" **maxlength="3"**>`

You can type in as much as you want.

In my local project, I tested it with: 

					<p:inputNumber maxlength="3"  />
					
					<p:inputText maxlength="3"/>
Result:

![image](https://user-images.githubusercontent.com/80260448/148255010-f47c305d-392a-4524-8d43-0372bbf36b62.png)

```
<span id="loginForm:j_idt46" class="ui-inputnumber ui-widget ui-inputwrapper-filled"><input id="loginForm:j_idt46_input" name="loginForm:j_idt46_input" type="text" autocomplete="off" value="" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-filled" maxlength="3" inputmode="decimal" role="textbox" aria-readonly="false" aria-disabled="false"><input id="loginForm:j_idt46_hinput" name="loginForm:j_idt46_hinput" type="hidden" autocomplete="off" value="123122312323.00"></span>

<input id="loginForm:j_idt47" name="loginForm:j_idt47" type="text" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-filled" maxlength="3" role="textbox" aria-readonly="false" aria-disabled="false">
```

**Environment:**
 - PF Version: 11.0.0
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: tested only in Chrome

**Expected behavior**
The InputNumber field should have the same behavior as InputText here.

**Comment by melloware** [comment]
@Teutron-flo that has been discussed and covered here by AutoNumeric the plugin that powers InputNumber:

https://github.com/autoNumeric/autoNumeric/issues/599

Its marked as "WontFix".

> This is the intended behavior.
> If the dev wants to limit the number of digits, it needs to set maximumValue, minimumValue and/or decimalPlaces accordingly.

**Comment by Teutron-flo** [comment]
@melloware, ok with the minValue / maxValue i can get a similar behavior. Thanks for the information.

But wouldn't it good to writte such a known thing into the documenation?
I spend yesterday a couple of hours on it, because I thought the issue is on my side.

**Comment by melloware** [comment]
OK PR submitted to update the documentation and taglib definition for maxLength on InputNumber to say `DO NOT USE! To limit the number of digits...set maximumValue, minimumValue and/or decimalPlaces accordingly.`

**Comment by Teutron-flo** [comment]
Thank you for your create support here! I realy love your (and of all other team member) work for primefaces!
It makes so much fun to work with it in our applications.
