### ISSUE TITLE
DataExporter and ColumnGroup not working on Showcase

### ISSUE THREAD

**Issue by GregLBrand** [primefaces/primefaces#8241]
The Showcase shows the problem very well.  Access the Showcase link below and then click the XLSX button on the top right.  The exported data is not showing the column headers and data properly.
https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml?jfwid=bcf7b

**Environment:**
 - PF Version:  11.0.0

![image](https://user-images.githubusercontent.com/45044006/148286756-1254af0c-b761-4736-8a36-4737af736100.png)

**Comment by melloware** [comment]
Ahhh this was working before so something changed.

**Comment by melloware** [comment]
It was working as of this ticket: https://github.com/primefaces/primefaces/issues/7163

**Comment by GregLBrand** [comment]
Workaround is to use the 'exportable="false"' on the ColumnGroup columns and then add the "display:none;" to the data columns. Yuck, but works.

<p:columnGroup type="header" exportable="false">
     <p:row>
          <p:column rowspan="2" headerText="Something"exportable="false"/>
            :
</p:columnGroup>

:
<p:column>
    <f:facet name="header"><h:outputText value="Something" style="display: none;"/></f:facet>

**Comment by melloware** [comment]
I think I see the problem.  Working on a fix tomorrow

**Comment by melloware** [comment]
Much better now.  The fix was to use the overloaded method to exclude column groups when asking for exportable columns.

![image](https://user-images.githubusercontent.com/4399574/148386065-b0e09e76-52ab-4db4-8f50-7d7f3bc8d9a1.png)
