### ISSUE TITLE
DataTable: Filter + Input component with ajax processing that row and the next one

### ISSUE THREAD

**Issue by BryanV91** [primefaces/primefaces#8245]
**Describe the defect**
Whenever I set a filter value in the column that has an input component (like selectBooleanCheckbox, datePicker, inputText, etc.) and then I proceed to change that value by ajax, the table gets updated and it shows the affected values for the row that I clicked and the next one. This doens't happen when I don't set any filters.

**Reproducer**
Project attached: [primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7821915/primefaces-test-master.zip)

**Environment:**
 - PF Version: _11.0_
 - JSF + version: _Mojarra 2.3_
 - Affected browsers: _Chrome and FireFox_

**To Reproduce**
1. Go to 'test.xhtml'
2. Set filter value 'Yes' for 'Status column'
3. Click the first checkbox
![image](https://user-images.githubusercontent.com/26931796/148386500-a5ba6f97-2726-42ef-961a-4135c1d5f0ab.png)
![image](https://user-images.githubusercontent.com/26931796/148386510-61b21a87-ba67-412d-b106-aab9354e12d7.png)
5. Set filter value 'null' for 'Status column'
6. Changes where applied to clicked row and the next one
![image](https://user-images.githubusercontent.com/26931796/148386519-99bafabb-f78d-45cc-b39b-0832d3108a50.png)

**Expected behavior**
Only the first row should be changed.

**Example XHTML**
```html
<p:dataTable id="dta-tbl" widgetVar="dta-tbl" var="object" value="#{testView.testList}" paginator="true"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			currentPageReportTemplate="Total: {totalRecords}" paginatorPosition="bottom" rowsPerPageTemplate="5,10,15" rows="5"
			pageLinks="3">
	<f:facet name="header">
		My table
	</f:facet>
	<p:column id="id-col" styleClass="" filterBy="#{object[0]}" headerText="Id.">
		#{object[0]}
	</p:column>
	<p:column id="status-col" styleClass="" filterBy="#{object[1]}" headerText="Status">
		<f:facet name="filter">
			<h:selectOneMenu id="status-sel" onchange="PF('dta-tbl').filter()">
				<f:selectItem itemLabel="" itemValue="#{null}" noSelectionOption="true" />
				<f:selectItem itemLabel="Yes" itemValue="#{true}" />
				<f:selectItem itemLabel="No" itemValue="#{false}" />
			</h:selectOneMenu>
		</f:facet>
		<p:selectBooleanCheckbox id="status-in" value="#{object[1]}">
			<p:ajax process="@this" partialSubmit="true" listener="#{testView.updateStatus(object[0], object[1])}"
				update="@none" oncomplete="PF('dta-tbl').filter()" />
		</p:selectBooleanCheckbox>
	</p:column>
</p:dataTable>
```

**Example Bean**
```java
@Data
@Named
@ViewScoped
public class TestView implements Serializable {

	private String string;
	private List<Object[]> testList;

	@PostConstruct
	public void init() {
		string = "Welcome to PrimeFaces!!!";

		testList = new ArrayList<>();
		Object[] tmp = null;
		for (int idx = 0; idx < 5; idx++) {
			tmp = new Object[] { idx, true };
			testList.add(tmp);
		}

	}

	public void updateStatus(Integer idx, Boolean value) {

		System.out.println(!value);

	}

}
```

**Comment by BryanV91** [comment]
Ok. This a weird one. Problem gets solved after adding this to the bean:

`private List<Object[]> testFilteredList;`

And this attribute to the page:

`filteredValue="#{testView.testFilteredList}"`

Any thoughts?

**Comment by melloware** [comment]
As discussed on Discord I thought not having `filterdValue` used to throw a FacesException that this was not used if filtering was attempted.  @tandraschko maybe we should add this exception??

**Comment by FlipWarthog** [comment]
@melloware I think it might also relate to #7999, specifically I'm seeing this doc you wrote around what appears to be related to the issue. When debugging both with and without `filteredValues` set, `FilterFeature.filter` is called only once when when I click a checkbox and `filteredValues` set, but it's called 3 times when `filteredValues` is not set. And the call stack can be traced back here.
 https://github.com/primefaces/primefaces/blob/1c6e2938936c8e1c9de3e81a0603de7dd418b6b8/primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java#L295-L309

**Comment by melloware** [comment]
Yep in that ticket Thomas explains the problem exactly. So in the case above without a filtered values it's just recreating the list every time with copies of the object and not the original references

**Comment by melloware** [comment]
My solution is to simply log a warning in this scenario:

```java
LOGGER.log(Level.WARNING, "DataTable with filtering should also set the 'filteredValue' attribute. ClientId: " + getClientId());
```

**Comment by tandraschko** [comment]
for me the behavior is actually correct
you actually filter the datatable in the checkbox-ajax request but you dont update the datatable, which creates a different state on server and client side
and then you send a second AJAX request via JS 'filter'

i changed it to 
```
<p:selectBooleanCheckbox id="status-in" value="#{object[1]}">
	<p:ajax process="@this" partialSubmit="true" listener="#{testView.updateStatus(object[0], object[1])}"
		update="dta-tbl" />
</p:selectBooleanCheckbox>
```

and it works fine


a workaround for your case would be, as you already metioned, the filteredValue binding to a bean
