### ISSUE TITLE
Datatable: filter on Integer uses String comparison

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces/primefaces#8246]
g.percelen is an Integer

The following xhtml:

```
<p:column headerText="#percelen" sortBy="#{g.percelen}" filterBy="#{g.percelen}" filterMatchMode="gt">
  #{g.percelen}
</p:column>
```
results in String comparison for gt instead of numeric comparison

**Environment:**
 - PF Version: _10.0.8
 - JSF + version: Mojarra on payara 5.2021.9
 - Affected browsers: firefox 95.0.1 linux

**To Reproduce**
Create a pojo with an Integer field percelen
Create a Datatable for it with a list of these objects in a controler
values for percelen to be in the list: 5 54 6 100
Create a xhtml page with the snippet above in it
Run the app
when entering filter value 54, 6 will be shown

**Expected behavior**
when entering filter value 54, 6 will not be shown

**Comment by melloware** [comment]
Have you tried this on 11.0 as well?

**Comment by eduarddrenth** [comment]
not yet, I will

**Comment by eduarddrenth** [comment]
still there:

![image](https://user-images.githubusercontent.com/10200360/148414985-c7603e17-c6ef-4b7b-8c1f-9625a27f3b92.png)

**Comment by melloware** [comment]
thanks for checking!

**Comment by melloware** [comment]
@jepsar can you comment on this ticket so I can assign it to you.

**Comment by jepsar** [comment]
Ah, is it not possible if you don't?

**Comment by melloware** [comment]
Nope!  It only lets me choose people on the ticket or PF Committers

**Comment by eduarddrenth** [comment]
Great!

**Comment by jepsar** [comment]
@eduarddrenth You should convert your filter value to integer:
```xhtml
<p:column headerText="#percelen" sortBy="#{g.percelen}" filterBy="#{g.percelen}" filterMatchMode="gt">
    <f:facet name="filter">
        <p:inputText onkeyup="PF('yourTable').filter()" styleClass="ui-column-filter">
            <f:converter converterId="javax.faces.Integer" />
        </p:inputText>
    </f:facet>
    #{g.percelen}
</p:column>
```

**Comment by eduarddrenth** [comment]
Thanks, this is needed until the fix is released I assume?

**Comment by jepsar** [comment]
No, I changed the fix to avoid having to convert the value for each row. With the new fix the value is converted (to the correct type) just once. See PR #8367

**Comment by jepsar** [comment]
@eduarddrenth See also #8369 which should make life easier
