### ISSUE TITLE
Jakarta EE9.1: Support primefaces

### ISSUE THREAD

**Issue by jreyes256** [primefaces/primefaces#8249]
Greetings, I am working with Jakarta EE 9.1 but when implementing the library I get that I am missing components such as jakarta.faces

**Comment by christophs78** [comment]
Please have a look at https://github.com/primefaces/primefaces-test/tree/jakarta.

**Comment by jreyes256** [comment]
I have tried in some ways, which server they recommend me to use with payara gives me that problem

**Comment by christophs78** [comment]
Please write down....

- which server (+version) you use exactly
- which components in which versions
- which exact error(s) you get

**Comment by jreyes256** [comment]
Server: Payara Server 5.2021.10

In the Pom.xml I add the Jakarta EE 9.1 library and there it compiles the project for me, but it added the primefaces library with the Jakarta classifier and it gives me the error Jakarta Faces not found, which server do you recommend me to use

**Comment by christophs78** [comment]
Maybe you run into https://github.com/payara/Payara/issues/5425
IMO it´s not a PrimeFaces issue. PrimeFaces Test show´s PrimeFaces works on Jakarta-ified Jetty.
I personally will not give suggestions regarding application-server because this IMO has way more implications.

**Comment by tandraschko** [comment]
+1 christoph
