### ISSUE TITLE
SplitButton: filter input field lacks left and right margin and icon

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8251]
Screenshot of SplitButton with filter (PF12):

<img width="213" alt="Screenshot 2022-01-08 at 10 18 23" src="https://user-images.githubusercontent.com/7500178/148638989-47bf6f00-9679-4aaa-98d3-8779e22f9ce3.png">

compared to a screenshot of a SelectOneMenu with filter:

<img width="371" alt="Screenshot 2022-01-08 at 10 18 57" src="https://user-images.githubusercontent.com/7500178/148639002-21d43bd6-6314-44ec-a776-f917c107fbad.png">

**Comment by melloware** [comment]
Added theme label as I am sure there is some theme work involved too?

**Comment by jepsar** [comment]
The only thing that needs to be done to the components CSS is removing `padding-right: 15px;` from the rule `.ui-splitbuttonmenu .ui-splitbuttonmenu-filter`. All the rest is theme related.
