### ISSUE TITLE
Timeline: rework according to Schedule-component

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#8257]
see https://github.com/primefaces/primefaces/issues/8076, https://github.com/primefaces/primefaces/pull/8090

Currently it´s essentially broken due to the changes we did with https://github.com/primefaces/primefaces/pull/8090. (Broken means server- and client-time are out of sync.)

- [x] adapt Timeline-component to be in sync with https://github.com/primefaces/primefaces/pull/8090
- [x] adapt Showcase
- [x] provide integration-tests (like Schedule001Test)

**Comment by melloware** [comment]
Great idea!  Good catch.
