### ISSUE TITLE
SelectOneListbox XSS vulnerability

### ISSUE THREAD

**Issue by ChristopherSc** [primefaces/primefaces#826]
Primefaces version 5.3 (and earlier)

``` xhtml
<p:selectOneListbox>
        <f:selectItems value="..." itemLabel="${item.label}" itemLabelEscaped="true"/>
</p:selectOneListbox>
```

When itemLabelEscaped = true (the default value since 5.3), the label is not being escaped in the option tag.

SelectOneListboxRenderer::encodeItem

``` java
            if(option.isEscape()) {
                writer.writeText(option.getLabel(), null);
            } else {
                writer.write(option.getLabel());
            }
```

The encodeItem function is doing it properly, while the encodeOption functionality is not:

SelectOneListboxRenderer::encodeOption

``` java
            writer.write(option.getLabel());
```

so when the label contains javascript, it's being written to the html without being escaped and thus leads to XSS capabilities.

A test value for the label could be:

``` javascript
<script type="text/javascript">alert('i am an annoying alert popup');</script>
```

**Comment by mertsincan** [comment]
Thanks for the detailed explanation :+1:

**Comment by akoshpinter** [comment]
Hello,

This same vulnerability (and fix) applies to SelectManyMenu as well, should we create a new bug report? (PrimeFaces 6.0 and earlier)
