### ISSUE TITLE
Dialog: Fixed Position Not Working

### ISSUE THREAD

**Issue by afd0174** [primefaces/primefaces#8261]
Hi,

I've encountered an issue upgrading to PrimeFaces 11 with the p:dialog component. 

https://forum.primefaces.org/viewtopic.php?f=3&t=70508

1. Expected behavior:  When I specify a value for the position attribute, I expect the dialog to hold its position in the viewport as the page is scrolled. 
2. Observed behavior: The dialog scrolls with the page rather than holding its position fixed within the viewport. 
3. Steps to reproduce: I've attached a modified version of the prime faces-test project (as a *.tar.gz file).  Build and run this project, show the dialog via the "Show" button, and then scroll the page and observe the dialog scroll along with the rest of the viewport.
[primefaces-test-pdialog-scrolls.tar.gz](https://github.com/primefaces/primefaces/files/7835977/primefaces-test-pdialog-scrolls.tar.gz)

Please let me know if I can provide any additional information.

Thanks,

-Andy

**Comment by melloware** [comment]
@afd0174 I believe this was done in purpose by PrimeTek to align it with all their other libaries behavior like PrimeNG and PrimeReact.  See this ticket:  https://github.com/primefaces/primefaces/issues/6978

**Comment by afd0174** [comment]
@melloware Thank you for the background.  Just to say it, via the reproducer project, if you eliminate the position attribute on the p:dialog, the dialog remains fixed when the viewport is scrolled, which seems consistent with the behavior advertised by the server-side API documentation, given the default value of "fixed" for the positionType attribute.

**Comment by melloware** [comment]
@afd0174 so what do you recommend we do?  Do we need to update docs or is there something that needs to be fixed or addressed?

**Comment by afd0174** [comment]
I would recommend addressing the issue in the code so that you can achieve a dialog with a fixed position type regardless of whether or not an initial position is specified via the position attribute (consistent with the default value of "fixed" for the positionType attribute).  This is the behavior that exists in PrimeFaces 8.0 and 10.0.  As it sits in PrimeFaces 11.0, you get a fixed position type dialog when no position attribute is supplied and a non-fixed position type when you do provide a position attribute (which is at odds with the fact that the positionType attribute should default to "fixed" when not provided).

**Comment by melloware** [comment]
actually I think it was introduced with this ticket: https://github.com/primefaces/primefaces/issues/2062

**Comment by melloware** [comment]
OK @afd0174 got to the bottom of the issue.  Its this issue: https://github.com/primefaces/primefaces/issues/6931

Dialog was made `responsive="true"` by default which respects scrolling and browser size.  This is a smart default in today's modern webapps.  You simply have to change your dialog to `responsive="false"` and it works the way you expected it to and how it did in 8.0.

[pf-8261.zip](https://github.com/primefaces/primefaces/files/7865671/pf-8261.zip)

**Comment by afd0174** [comment]
@melloware Thank you for your help in running this to ground!  Just a minor thought - it might be worth updating the server-side API documentation for the responsive attribute, as its current description is "In responsive mode, dialog adjusts itself based on screen width" which I don't think tells the whole story:

[https://primefaces.github.io/primefaces/11_0_0/#/components/dialog](url)

Thanks again!

**Comment by melloware** [comment]
Agreed fixing it now!

the good news is it was in the migration guide but you are right the responsive prop doesn't tell the whole story!  https://primefaces.github.io/primefaces/11_0_0/#/../migrationguide/11_0_0

**Comment by melloware** [comment]
New text will read: "In responsive mode the dialog adjusts itself based on screen width, browser resizing, and scrolling of the document."
