### ISSUE TITLE
Carousel: Strange behavior when loading less items that the allocated slots in carousel

### ISSUE THREAD

**Issue by ingeniotechnologies** [primefaces/primefaces#8265]
**Describe the defect**
Let's say, I set numVisible="4" numScroll="1" in carousel attributes, but only load 1 item, the ui-carousel-items-container gets set with possible offending inline style="transform: translate3d(75%, 0px, 0px);"; which causes item to be shifted to the far right.

Then if I load 2 items, even stranger behavior takes place. The second item disappears and first item shifts towards the right, but not quite all the way. Also, inline style for ui-carousel-items-container gets set to transform: translate3d(50%, 0px, 0px);

Then, when loading 3 items, they kinda look ok, but the 4th slot is partially taken up by the 3 items shown.

In carousels with 1 and 2 loaded items, the scroll buttons get messed up. The left one becomes enabled and when clicked, the items disappears to the right, and right scroll button gets enabled, but when clicked, item does not come back, it stays hidden.

**Reproducer**
I've attached previously downloaded primefaces-test-master.zip project with a few modified lines of code from existing carousel-related sample files here: https://github.com/eframsergio/tests/raw/main/primefaces-test-master.zip

**Environment:**
 - PF Version: 11.0.0
 - Affected browsers: Seemingly all

**To Reproduce**
1. On previously downloaded primefaces-test-master.zip project, I modified pom.xml to use primefaces version 11.0.0 instead of 10
2. Added Carousel-related files (entities, service and view) from Primefaces Showcase sources.
3. I then modified CarouselView.java to have products1, products2 and products3 properties and load 1, 2 and 3 products accordingly (eg. products1 = service.getProducts(1);, products2 = service.getProducts(2);, etc.)
4. Then in test.xhtml, I copied/pasted 3 times the "Basic" carousel snippet from carousel.xhtml (from Primefaces Showcase) and modified properties accordingly to each snippet (value="#{carouselView.products1}", value="#{carouselView.products2}", etc)
5. Then Run project in browser
6. The resulting page shows how the items inside the carousel are incorrectly aligned.

Any suggestions as to how to fix this on my end? 

Thanks!

**Comment by ingeniotechnologies** [comment]
I think I found that the offending style is when "ui-carousel-item" element is set to grow with "flex-grow"; so my workaround for now is to set to "flex-grow: 0;"

**Comment by melloware** [comment]
That must be coming from the THEME CSS and not PF core carousel.css.  SO I am going to mark this as theme related.

**Comment by mertsincan** [comment]
This issue is not related to a theme. @melloware, could you please check it? It might work fine in PrimeReact.

**Comment by melloware** [comment]
Yep I will check this.

**Comment by melloware** [comment]
Yep the problem is in the JS idget code here...

```js
var innerHTML = 'div[id*="' + this.id + '"] .ui-carousel-item {flex: 1 0 ' + (100/ this.numVisible) + '%}';

        if (this.cfg.responsiveOptions) {
            var _responsiveOptions = this.cfg.responsiveOptions;
            _responsiveOptions.sort(function (data1, data2) {
                var value1 = data1.breakpoint;
                var value2 = data2.breakpoint;
                var result = null;

                if (value1 == null && value2 != null)
                    result = -1;
                else if (value1 != null && value2 == null)
                    result = 1;
                else if (value1 == null && value2 == null)
                    result = 0;
                else if (typeof value1 === 'string' && typeof value2 === 'string')
                    result = value1.localeCompare(value2, undefined, { numeric: true });
                else
                    result = (value1 < value2) ? -1 : (value1 > value2) ? 1 : 0;

                return -1 * result;
            });

            for (var i = 0; i < _responsiveOptions.length; i++) {
                var res = _responsiveOptions[i];

                innerHTML += '@media screen and (max-width: ' + res.breakpoint + ') '
                    + '{div[id*="' + this.id + '"] .ui-carousel-item '
                    + '{flex: 1 0 ' + (100/ res.numVisible) + '%}}'
            }
        }
```

**Comment by melloware** [comment]
OK fixed it with this MonkeyPatch:

```js
if (PrimeFaces.widget.Carousel) {
    PrimeFaces.widget.Carousel.prototype.getTotalIndicators = function() {
        return Math.max(Math.ceil((this.itemsCount - this.numVisible) / this.numScroll) + 1, 0);
    };
};
```

**Comment by Anuja-More-HFN** [comment]
I am getting some what same issue when set numVisible=1 on first load all the items it carousal get visible on first slide itself <div   class="p-carousel-items-container"
 data-pc-section="itemscontainer"
 style="transform: translate3d(0%, 0px, 0px) /> this inline styles are getting added when i click on next icon inline style becomes this style="transform: translate3d(-100%, 0px, 0px)

**Comment by 4hmedk** [comment]
> I am getting some what same issue when set numVisible=1 on first load all the items it carousal get visible on first slide itself 

Yeah I am facing the same issue. Did anybody find a workaround?

**Comment by melloware** [comment]
@4hmedk can you demonstrate the issue with a PF Test reproducer? 

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
