### ISSUE TITLE
InputNumber : Widget class 'InputNumber' not found!

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#8266]
I am using Primefaces 11, and I am adding the components from the backend to a panelgrid as follows:

1- xhtml page 

`<p:panelGrid id="inputs" layout="grid" columnClasses="ui-grid-col-2,ui-grid-col-5" styleClass="ui-panelgrid-blank"columns="2" binding="#{myBean.myPanelGrid}"></p:panelGrid>`

2- backend code 

```
InputNumber inputNumber = new InputNumber();
inputNumber.setThousandSeparator("");
inputNumber.setMaxlength(15);
myPanelGrid.getChildren().add(inputNumber);
```

---------------

when I open the page the input number is not working and i can see in the console the following error 

Widget class 'InputNumber' not found!

and under the component I can see a generated script as follows 

`<script id="genericSearchForm:tabs:myInputNumber" type="text/javascript">$(function(){PrimeFaces.cw("InputNumber","widget_genericSearchForm_tabs_myInputNumber",{id:"genericSearchForm:tabs:myInputNumber",disabled:false,valueToRender:"",digitGroupSeparator:"",minimumValue:"0",maximumValue:"999999999999999",decimalPlaces:"2",leadingZero:"allow",selectOnFocus:false,showWarnings:false});});</script>`

The workaround to work : 

in the xhtml page i add static inputNumber as follows:

`<p:inputNumber style="display:none" thousandSeparator=""/> `

when i do that the first code works !

**Comment by tandraschko** [comment]
never use the constructor of a component, use JSF #createComponent API
