### ISSUE TITLE
AutoComplete: multiple=true: disallow selecting the same item multiple times

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#8274]
**Description**
AutoComplete with multiple=true currently allows to select the same item multiple times. This does not fit for every usecase.
![image](https://user-images.githubusercontent.com/10461942/149331596-f51bf3dd-8aaf-491a-b706-f140442b591e.png)

**Describe the solution you would like**
- ~~add an additional parameter (eg `unique=true`) to disallow selecting the same item multiple times~~ (already impemented) OR
- pass already selected items to the comleteMethod (so server-side-code can decide which items are offered) OR
- ???

**Example XHTML**
http://primefaces.org/showcase/ui/input/autoComplete.xhtml

**Comment by melloware** [comment]
I think in Chips we have the `unique` attribute which does this?

-- | -- | -- | --
unique | false | Boolean | Prevent duplicate entries from being added. Default false.

**Comment by christophs78** [comment]
Yep - `unique` does for Chips what this feature request suggest for AutoComplete used together with multiple=true.

https://github.com/primefaces/primefaces/blob/de7dfe05be653879fbdc7ec10f98a0b2af45cf62/primefaces/src/main/resources/META-INF/resources/primefaces/chips/chips.js#L130-L142

**Comment by christophs78** [comment]
Oh. We already have a `unique`-attribute for `AutoComplete`. (and it does what´s expected)

**Comment by melloware** [comment]
HA I thought I implemented it in more than one place but couldn't remember :)

**Comment by melloware** [comment]
@christophs78 can this be closed?
