### ISSUE TITLE
DataTable: clarify how to disable selection on row basis

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8279]
Currently selection can be enabled via `selectionMode` on `p:dataTable` or on `p:column`.
The problem is that the `selectionMode` attribute on `p:column` can be disabled/enabled via the current row state.
See this example:

```
            <p:dataTable id="datatable" value="#{dataTable032.model}"
                         var="lang"
                         selection="#{dataTable032.selection}"
                         rowKey="#{lang.id}"
                         paginator="true"
                         rows="4"
                         multiViewState="true">
                
                <p:ajax event="rowSelectRadio" listener="#{dataTable032.onRowSelect}" />

                <p:column headerText="" selectionMode="single" rendered="#{lang.selectable}"/>
                <p:column headerText="" rendered="#{!lang.selectable}"/>
                
                <p:column headerText="ID" sortBy="#{lang.id}">
                    <h:outputText value="#{lang.id}"/>
                </p:column>

                <p:column headerText="Name">
                    <h:outputText value="#{lang.name}"/>
                </p:column>

                <p:column headerText="First appeared">
                    <h:outputText value="#{lang.firstAppeared}"/>
                </p:column>
                
                <p:column headerText="Selectable">
                    <p:toggleSwitch value="#{lang.selectable}">
                        <p:ajax process="@this" update="@form" />
                    </p:toggleSwitch>
                </p:column>
            </p:dataTable>
```

and our `#getColumnSelectionMode` resolves this without the current rowState and also checks the rendered attribute

**Comment by tandraschko** [comment]
So we have 2 solutions:

1) a user must define `selectionMode` on p:dataTable in this case
2) we ignore #isRendered in #getColumnSelectionMode

WDYT @Rapster ?

**Comment by tandraschko** [comment]
i implemented 2) now
will add another issue and provide a integration test

**Comment by Rapster** [comment]
Not sure if it makes a lot of sense to have rendered attribute based on var (e.g lang). Should `DataTable#disableSelection` be used in such scenario?

**Comment by tandraschko** [comment]
We dont have a #disableSelection method?

Also its really based on row, not each row should be selectable in our case

**Comment by Rapster** [comment]
> disabledSelection: Disables row selection when true. Overrides p:column's disabledSelection attr. Example: var="xxx" disabledSelection="#{xxx.year > 1960}"

**Comment by tandraschko** [comment]
both cases are working now
disableSelection was the intended way to go, thanks but should we consider the case above? The benefit is, that it doesnt even render a radio

**Comment by tandraschko** [comment]
lets stick with disabledSelection for now, i changed the tests and issue title
