### ISSUE TITLE
Slider + Spinner: slider breaks after entering a value

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8298]
Confirmed with 12. Go to http://localhost:8080/showcase/ui/input/slider.xhtml, enter a value in the Spinner Slider demo and then try to drag the slider.

<img width="559" alt="Screenshot 2022-01-18 at 08 42 39" src="https://user-images.githubusercontent.com/7500178/149892835-4902949b-4ee7-4a92-a8cc-5d82f2b8062e.png">

See also https://stackoverflow.com/questions/70746810/how-to-bind-spinner-input-value-with-a-slider-in-primefaces

I can have a look at this.

**Comment by melloware** [comment]
We definitely had a similar issue in the past with slider + inputnumber

**Comment by jepsar** [comment]
I've been debugging this, and it seems that this is not something we can fix from within the widget code. The issue seems to be with jQuery UI:

https://github.com/jquery/jquery-ui/blob/0c5becce0e395b89de0f526e857e7ca2717d4ab2/ui/widget.js#L575

**Comment by melloware** [comment]
ughhh with Jquery UI 1.13.0 upgrade probably.

**Comment by melloware** [comment]
jQuery 1.13.1 does not fix this issue

**Comment by melloware** [comment]
@jepsar my PR attached to this ticket seems to fix this issue along  with #8630 .  I can't get the error above to happen anymore.
