### ISSUE TITLE
<p:ajax event/> triggers <p:ajaxStatus/> too often

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#8299]
**Environment:**
 - PF Version: 8.0.14
 - PrimeFaces Extensions 8.0.5
 - JSF version: 2.3.9
 - OmniFaces version: 2.7.14
 - JavaEE vesion: 8.0.1
 - WebLogic 14.1.1.0.0
 - Affected browsers: Chrome, Firefox

p:ajax event="click" calls the ajaxStatus too many times when I click the button. This leads to problems in some cases, for example if in which <p:ajaxStatus/> the "onstart" and "oncomplete" methods, other JavaScript functions and so on are executed. 

An example of what works correctly:
```
            <p:commandButton id="one" value="close test"
                             process="@this" update="@none" immediate="true"/>

            <p:commandButton id="three" value="close test">
                <f:ajax event="click" execute="@this" render="@none" immediate="true"/>
            </p:commandButton>
```
The output for this:
```
 ajaxStatus onstart
 ajaxStatus oncomplete 
```

An example of what doesn't work correctly:
```
            <p:commandButton id="two" value="close test">
                <p:ajax event="click" process="@this" update="@none" immediate="true"/>
            </p:commandButton>
```
The output for this:
```
 ajaxStatus onstart
 ajaxStatus oncomplete 
 ajaxStatus onstart
 ajaxStatus oncomplete 
```
This double call can lead to problems, which can then lead to the <p:AjaxStus/> status "oncomplete" no longer being called. But this "oncomplete" call is important.

With JavaEE6 and JSF 2.1 this is not a problem. Just migrating from this version.

Steven

**Comment by tandraschko** [comment]
Never attach p/f:Ajax to a p:commandButton, its already ajaxified

**Comment by melloware** [comment]
@StevenHachel the correct PF way to write what you are doing above is this...

```xml
 <p:commandButton id="three" value="close test" process="@this" update="@none" immediate="true" />
```

**Comment by StevenHachel** [comment]
oh ok I got used to that from back then (plain JSF). Good to know that it is no longer needed in PF. 
Thank you and sorry for the request.

steven
