### ISSUE TITLE
DataExporter: ColumnGroup breaks exported table

### ISSUE THREAD

**Issue by FerranPC** [primefaces/primefaces#8300]
**Describe the defect**
Exported XLSX documents with columnGroup elements have shifted columns. 
I think the pattern that follows is that it draws the row of data starting from the last column with title plus the number of columnGroups used.

**Reproducer**
When exporting a table with the DataExporer, if the table contains columnGroup cells, the data rows are not drawn in the appropriate column.

**Environment:**
 - PF Version: _11.0_

**To Reproduce**
1. Go to https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml?jfwid=36a68
2. Click on XLSX export button
3. Open the file to see the data rows are on the wrong columns

**Comment by melloware** [comment]
Duplicate of: https://github.com/primefaces/primefaces/issues/8241
