### ISSUE TITLE
CommandButton: add inline Ajax status indicator

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8301]
The icon or text can be temporarily replaced with a spinner while an Ajax request is in progress.

![commandbutton](https://user-images.githubusercontent.com/7500178/150289234-254e1753-9f6b-4d0a-86c9-bd83a58b7d4b.gif)

Note that the speed of the GIF is slower than real time (don't want to spend time on getting the GIF right).

```xhtml
<h5>Ajax Disabling and Status Icon</h5>
<p:commandButton value="Disable" action="#{buttonBasicView.sleep()}" />
<p:commandButton value="Status" disableOnAjax="false" action="#{buttonBasicView.sleep()}" />
<p:commandButton value="Both + Icon" icon="pi pi-check" action="#{buttonBasicView.sleep()}" />
```

**Comment by Rapster** [comment]
I like the idea. Do you have a gif to share to see what it look like?

**Comment by klaros-testmanagement** [comment]
Great idea, I really like this too!
