### ISSUE TITLE
CommandButton: Ajax requests should toggle a CSS class allowing style overriding

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8303]
I'm thinking to disable the button as we do now, but additionally have a CSS class while the Ajax request is in progress and based on that not set the opacity (will require a theme change). Not sure if this should be optional.

**Comment by jepsar** [comment]
Hmm.. while submitting this issue, I noticed the 'Comment' being disabled and it did not bother me that much. If we would add this feature, it should be optional I think.

**Comment by melloware** [comment]
I personally think if something is disabled it should be visually different.  Your current GIF's show me exactly the behavior I want.

**Comment by jepsar** [comment]
Okay, I think I'll just add the class, so it's up to the user to override the style.

**Comment by melloware** [comment]
That sounds good!

**Comment by jepsar** [comment]
I was planning to call it `ui-state-loading`. WDYT? FYI PrimeVue uses `p-button-loading`.

**Comment by melloware** [comment]
That name is ok with me.
