### ISSUE TITLE
Core: jQuery UI 1.13.1

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8304]
**Description**
jQuery UI 1.13.1 is released: https://github.com/jquery/jquery-ui/releases/tag/1.13.1

**Comment by kguelzau** [comment]
1.13.2 contains another xss fix https://github.com/jquery/jquery-ui/security/advisories/GHSA-h6gj-6jjq-h8g9

**Comment by melloware** [comment]
We don't use that feature but it can't hurt to upgrade it. I will work on that now.
