### ISSUE TITLE
SelectOneMenu: Default command not working

### ISSUE THREAD

**Issue by pradipt1505** [primefaces/primefaces#8308]
Hi,

We are upgrading from PF 7 to PF 11. During our upgrade we observed that default command (enter key) is not working on the pages where focus is on selectOneMenu. It works fine for the pages which have input text.

The above behavior is working in PF 7. Also just for information we are using PF11 on top of JSF2.3.14 (com.sun).

Can you please suggest how to resolve this issue?

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
Actually this was fixed on purpose for this ticket: https://github.com/primefaces/primefaces/issues/5889

**Comment by melloware** [comment]
Can you try and add this script to your JS file that loads anytime after PrimeFaces...

```javascript
PrimeFaces.widget.SelectOneMenu.prototype.handleEnterKey = function(event) {
    if (this.panel.is(':visible')) {
        this.selectItem(this.getActiveItem());
        event.stopPropagation();
    }

    event.preventDefault();
};
```

**Comment by melloware** [comment]
Reproducer proving the fix:
[pf-8308.zip](https://github.com/primefaces/primefaces/files/7907309/pf-8308.zip)

**Comment by pradipt1505** [comment]
> Can you try and add this script to your JS file that loads anytime after PrimeFaces...
> 
> ```js
> PrimeFaces.widget.SelectOneMenu.prototype.handleEnterKey = function(event) {
>     if (this.panel.is(':visible')) {
>         this.selectItem(this.getActiveItem());
>         event.stopPropagation();
>     }
> 
>     event.preventDefault();
> };
> ```

This JS Function is working. Thank you for the quick response. However, this does feel like a workaround. Will there be any fix on the community version anytime soon?

**Comment by melloware** [comment]
yes I submitted a PR so it will be in PF 12.0.0

**Comment by pradipt1505** [comment]
When will PF 12.0.0 be available?

**Comment by melloware** [comment]
That is up to PrimeTek but 11.0.0 just came out so probably in 6 months.   You are fine to use the MonkeyPatch above and just put a comment in your code to "Remove in 12.0.0"

**Comment by pradipt1505** [comment]
OK. Thanks for quick help.
