### ISSUE TITLE
Autocomplete Paste issue

### ISSUE THREAD

**Issue by absantanna** [primefaces/primefaces#831]
I've a issue with autocomplete component, I'm using primefaces 5.2.14.

When a user paste something with the mouse using right click, in the first time the page is loaded, autocomplete is not showing the results.

Steps to reproduce;

Using Primefaces Showcase page: http://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

In the Simple Input, type an "a", it shows the results, copy the letter, erease it, paste with ctrl-v it shows the results, erease again, copy with mouse right click, it shows the results.

Now press F5, copy the letter with mouse right click, there is no results.

Tested it with Firefox, Chrome and Edge, all lasta versions.

**Comment by sudheerj** [comment]
In autocomplete.js file the paste event is prevented by below code snippet.

`if($this.suppressInput) {
            e.preventDefault();
            return;
        }
`
Do we really need this code block?

**Comment by tristann9** [comment]
Our application uses PrimeFaces 6.0 on Mojarra-2.0 and we see the same issue there.  Using absantanna's steps, I'm also able to reproduce the issue on PrimeFaces Showcase running on PrimeFaces-6.1-SNAPSHOT on Mojarra-2.2.8.
