### ISSUE TITLE
DatePicker: Templates make the styling look broken

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8313]
Also with PF 12.

https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml

<img width="419" alt="Screenshot 2022-01-21 at 16 33 37" src="https://user-images.githubusercontent.com/7500178/150554950-57463f3c-be69-4c03-b216-74eca4aad548.png">

Caused by the injected span of the template.

IMO we should deprecate `dateTemplate` in favor of metadata.

**Comment by melloware** [comment]
hmmm not sure if we should deprecate or fix this just in case other Prime Libs support this functionality i am hesitant to pull it out?

**Comment by jepsar** [comment]
If this needs to be fixed it's a theme issue

**Comment by melloware** [comment]
marked it as theme and assigned to @mertsincan

**Comment by mertsincan** [comment]
This issue is related to the demo. Fixed in https://github.com/primefaces/primefaces/commit/36207603ef9066ea30a73c996de0085109203209
