### ISSUE TITLE
PrimeFaces CLI: PrimeFlex 2 -> PrimeFlex 3 migration issues

### ISSUE THREAD

**Issue by ThoSap** [primefaces/primefaces#8314]
**Describe the defect**
The [PrimeFaces CLI 11.0.0](https://mvnrepository.com/artifact/org.primefaces/primefaces-cli/11.0.0) does not migrate the following _PrimeFlex 2_ to **PrimeFlex 3 CSS classes**:
```css
/* Flexbox - Flex Direction */
p-dir-col     -> flex-column
p-dir-col-rev -> flex-column-reverse
p-dir-row     -> flex-row
p-dir-rev     -> flex-row-reverse

/* Flexbox - Align Items */
p-align-start    -> align-items-start
p-align-end      -> align-items-end
p-align-center   -> align-items-center
p-align-baseline -> align-items-baseline
p-align-stretch  -> align-items-stretch

/* Flexbox - Align Self */
p-col-align-start    -> align-self-start
p-col-align-end      -> align-self-end
p-col-align-center   -> align-self-center
p-col-align-baseline -> align-self-baseline
p-col-align-stretch  -> align-self-stretch

/* Grid - Grid System */
p-offset-[0-12] -> col-offset-[0-12]

/* Typography - Whitespace */
p-text-nowrap -> white-space-nowrap
```

Also, it is accidentally migrating the following PrimeNG component selectors, **which do not exist in PrimeNG**
```html
<p-colorPicker></p-colorPicker>
<!-- is migrated into wrong selector  -->
<colorPicker></colorPicker>

<p-fieldset></p-fieldset>
<!-- is migrated into wrong selector -->
<fieldset></fieldset>

<p-columnFilter></p-columnFilter>
<!-- is migrated into wrong selector -->
<columnFilter><columnFilter>
```

**Environment:**
 - Angular version: _13.1.3_
 - PrimeNG version: _13.1.0_
 -  PrimeFaces CLI: _11.0.0_
 - Affected browsers: _ALL_

**To Reproduce**
Download Freya PrimeNG Layout **freya-ng-13.0.0.zip** at https://www.primefaces.org/store/templates.xhtml
and run
```powershell
Invoke-WebRequest -Uri https://repo1.maven.org/maven2/org/primefaces/primefaces-cli/11.0.0/primefaces-cli-11.0.0.jar -OutFile pfcli.jar
java -cp "pfcli.jar" org.primefaces.cli.migration.primeflex.PrimeFlexMigration .\src\app -e="scss,css,html,ts"
```
https://github.com/primefaces/primefaces/blob/11.0.0/primefaces-cli/README.md

**Expected behavior**
The PrimeFaces CLI 11.0.0: PrimeFlex 2 -> PrimeFlex 3 migration should migrate the above-listed PrimeFlex 2 CSS classes to PrimeFlex 3 and should not migrate the listed PrimeNG component selectors.

**Comment by melloware** [comment]
Excellent report let me add some unit tests.

**Comment by melloware** [comment]
OK I wrote some unit tests proving your issue then fixed it.  Also added all the missing classes you mentioned above.

**Comment by ThoSap** [comment]
Hi, definitely add the following test:
```css
border-top-color
```
The css property **[border-top-color](https://www.w3schools.com/cssref/pr_border-top_color.asp)** is converted to **border-tocolor** with Primefaces CLI 11.0.0

Additional you _could_ add tests for the follwing for PrimeNG component classes, but I think your regex change got this covered:
```css
p-colorpicker-color-handle
p-colorpicker-hue-handle
p-colorpicker-overlay-panel
p-colorpicker-preview
p-column-filter-add-rule
p-column-filter-buttonbar
p-column-filter-clear-button
p-column-filter-constraint
p-column-filter-matchmode-dropdown
p-column-filter-menu-button
p-column-filter-menu-button-open
p-column-filter-operator
p-column-filter-overlay
p-column-filter-overlay-menu
p-column-filter-remove-button
p-column-filter-row
p-column-filter-row-item
p-column-filter-row-items
p-column-filter-separator
p-column-resizer-helper
p-column-title
p-fieldset
p-fieldset-content
p-fieldset-legend
p-fieldset-toggleable
p-fieldset-toggler
```

**Comment by ThoSap** [comment]
Please check, the following **deprecated** PrimeFlex 2.0.0 Grid CSS classes _could_ also be missing in the `replaceRegex` HashMap:
https://github.com/primefaces/primeflex/blob/2.0.0/src/_grid_deprecated.scss#L130-L511

**Comment by melloware** [comment]
Let me check those out and add that test case.

**Comment by melloware** [comment]
`border-top-color` was fixed with my previous fix.  Unit test proving its fixed:
```java
    @Test
    void primeNgBug8314_borderTopColor() {
        String source = "<div class=\"border-top-color\"></div>";
        String result = MIGRATION.migrateSource(source);
        Assertions.assertEquals("<div class=\"border-top-color\"></div>", result);
    }
```

Yes those deprecated `p-col-order` are missing i think we assumed since they were already deprecated in a 2.0 release we didn't need to convert them.  What should they be converted to?

**Comment by ThoSap** [comment]
@melloware they should be changed to
https://www.primefaces.org/primeflex/order

As in total  **15x** deprecated _PrimeFlex 2.0.0_ `p-col-order` variants exist (excluding the responsive variants) and in _PrimeFlex 3.X.X_ only **7x** order variants exist, the migrations must be done the same way as it was done for elevation/shadow:
https://github.com/primefaces/primefaces/blob/11.0.0/primefaces-cli/src/main/java/org/primefaces/cli/migration/primeflex/PrimeFlexMigration.java#L168-L176

**2.0.0**
https://github.com/primefaces/primeflex/blob/2.0.0/src/_grid_deprecated.scss#L140-L510

**3.X.X**
https://github.com/primefaces/primeflex/blob/3.1.2/_sass/lib/src/_flexbox.scss#L49-L57

**Comment by ThoSap** [comment]
I think [PrimeFlexMigration.java#L92](https://github.com/primefaces/primefaces/blob/11.0.0/primefaces-cli/src/main/java/org/primefaces/cli/migration/primeflex/PrimeFlexMigration.java#L92) should be
```java
replaceRegex.put("p-order-([0-6])", "flex-order-$1");
```
instead of
```java
replaceRegex.put("p-order-([0-9])", "flex-order-$1");
```
as both in PrimeFlex [2.0.0](https://github.com/primefaces/primeflex/blob/2.0.0/src/flexbox/_order.scss#L1-L27) and [3.X.X](https://github.com/primefaces/primeflex/blob/3.1.2/_sass/lib/src/_flexbox.scss#L49-L57) only **0-6** order levels exited (not considering the above deprecated ones).
<br/>
[PrimeFlexMigration.java#L94](https://github.com/primefaces/primefaces/blob/11.0.0/primefaces-cli/src/main/java/org/primefaces/cli/migration/primeflex/PrimeFlexMigration.java#L94) should be
```java
replaceRegex.put("p-order-(xl|lg|md|sm)-([0-6])", "$1:flex-order-$2");
```
instead of (missing `-[level]`)
```java
replaceRegex.put("p-order-(xl|lg|md|sm)-([0-6])", "$1:flex-order");
```

**Comment by melloware** [comment]
Great let me fix it.

**Comment by melloware** [comment]
All changes made if you want to do one final review?

Also not sure if you built the 12.0.0-SNAPSHOT jar to test this, if not I can build you one if you need it to test against your PrimeNG project?

**Comment by ThoSap** [comment]
> @melloware they should be changed to
> https://www.primefaces.org/primeflex/order
> 
> As in total  **15x** deprecated _PrimeFlex 2.0.0_ `p-col-order` variants exist (excluding the size variants) and in _PrimeFlex 3.X.X_ only **7x** order variants exist, the migrations must be done the same way as it was done for elevation/shadow:
> https://github.com/primefaces/primefaces/blob/11.0.0/primefaces-cli/src/main/java/org/primefaces/cli/migration/primeflex/PrimeFlexMigration.java#L168-L176
> 
> **2.0.0**
> https://github.com/primefaces/primeflex/blob/2.0.0/src/_grid_deprecated.scss#L140-L510
> 
> **3.X.X**
> https://github.com/primefaces/primeflex/blob/3.1.2/_sass/lib/src/_flexbox.scss#L49-L57

The last missing change is the deprecated
`p-col-order-*` to `flex-order-*` migration.

```java
replaceRegex.put("p-col-order-(first|0)", "flex-order-0");
replaceRegex.put("p-col-order-(1|2)", "flex-order-1");
replaceRegex.put("p-col-order-(3|4)", "flex-order-2");
replaceRegex.put("p-col-order-(5|6)", "flex-order-3");
replaceRegex.put("p-col-order-(7|8)", "flex-order-4");
replaceRegex.put("p-col-order-(9|10)", "flex-order-5");
replaceRegex.put("p-col-order-(11|12|last)", "flex-order-6");

replaceRegex.put("p-(xl|lg|md|sm)-order-(first|0)", "$1:flex-order-0");
replaceRegex.put("p-(xl|lg|md|sm)-order-(1|2)", "$1:flex-order-1");
replaceRegex.put("p-(xl|lg|md|sm)-order-(3|4)", "$1:flex-order-2");
replaceRegex.put("p-(xl|lg|md|sm)-order-(5|6)", "$1:flex-order-3");
replaceRegex.put("p-(xl|lg|md|sm)-order-(7|8)", "$1:flex-order-4");
replaceRegex.put("p-(xl|lg|md|sm)-order-(9|10)", "$1:flex-order-5");
replaceRegex.put("p-(xl|lg|md|sm)-order-(11|12|last)", "$1:flex-order-6");
```

Everything else looks good ☺️
Would be great if you could provide a build then I test it against my project.

**Comment by melloware** [comment]
Ok will get you a build today.

**Comment by melloware** [comment]
OK I zipped up the JAR so I could attach it here.  Give it a shot and let me know how it goes!
[pf-cli-beta.zip](https://github.com/primefaces/primefaces/files/7920821/pf-cli-beta.zip)

**Comment by melloware** [comment]
OK try this JAR:
[pfcli-beta.zip](https://github.com/primefaces/primefaces/files/7920834/pfcli-beta.zip)

It has all your latest changes including the `col-order` and moved both look aheads to the bottom of the list. I also did a little clean up refactoring.

**Comment by ThoSap** [comment]
The only thing missing now (I promise) are the responsive deprecated `p-(xl|lg|md|sm)-order-(first|0)` to `flex-order-0` replace regexes, see my updated comment above ;)

**Comment by melloware** [comment]
OK just committed.  Take a look.

**Comment by ThoSap** [comment]
LGTM

**Comment by melloware** [comment]
OK then this new JAR should do it...
[pf-cli-beta.zip](https://github.com/primefaces/primefaces/files/7920843/pf-cli-beta.zip)

**Comment by ThoSap** [comment]
I just tested your last PrimeFaces CLI beta zip against my PrimeNG project (FreyaNG 13.0.0 based on _PrimeFlex 2.0.0_) and migrated successfully to **PrimeFlex 3.1.2** without a single issue (validated every single line manually) 😋
Thanks for your productive collaboration 👍🏼

@melloware would it make sense to update the [PrimeFaces CLI README.md](https://github.com/primefaces/primefaces/blob/11.0.0/primefaces-cli/README.md) in your PR by mentioning these fixes and providing this beta zip in the readme or even make a new PrimeFaces CLI 11.0.1 release @ MVN Repository?

**Comment by melloware** [comment]
Unfortunately I don't work for PrimeTek I am just an open source committer so I can't generate a Maven Central release but what I can do is add a link to this BETA on the README.MD!

Thanks for your testing and collaboration!

**Comment by melloware** [comment]
OK added this blurb to the README.MD

**12.0.0 BETA:**

Download: https://github.com/primefaces/primefaces/files/7920843/pf-cli-beta.zip

This BETA has many fixes found while converting a PrimeNG project using the CLI.  Thanks to @ThoSap.
To read about the changes: https://github.com/primefaces/primefaces/issues/8314

**Comment by ThoSap** [comment]
> Unfortunately I don't work for PrimeTek I am just an open source committer so I can't generate a Maven Central release but what I can do is add a link to this BETA on the README.MD!
> 
> Thanks for your testing and collaboration!

You're welcome 🔥

**Comment by daborg69** [comment]
Worked like a charm.

**Comment by melloware** [comment]
@daborg69 thanks for reporting in. You guys were a huge help
