### ISSUE TITLE
clientValidator: log warning when CSV is disabled

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#8318]
**Environment:**
 - PF Version: 8.0.14
 - PrimeFaces Extensions 8.0.5
 - JSF version: 2.3.9
 - OmniFaces version: 2.7.14
 - JavaEE vesion: 8.0.1
 - WebLogic 14.1.1.0.0
 - Affected browsers: Chrome, Firefox

Hello, the following JavaScript exception is thrown when I use this constellation.

```
Uncaught TypeError: PrimeFaces.vi is not a function
    onchange http://localhost:8080/primefaces-test/:1
```

This problem does not occur under JavaEE6 and JSF 2.1. I am currently migrating my application to JavaEE8 and Weblogic 14.1.

[pfe-693.zip](https://github.com/primefaces/primefaces/files/7924201/pfe-693.zip)

**Comment by tandraschko** [comment]
Please try PF11, elite releases are not maintained by the community here

**Comment by StevenHachel** [comment]
@tandraschko 
I cannot migrate to version 11 in the short term. Migrating to JavaEE8 is tedious enough.
Who do I contact if not here? Is there an elite issue board? I use and pay extra for elite to fix bugs in the next versions. Always being referred to the next version is a bit too easy.

**Comment by tandraschko** [comment]
I explained it many times here and its really annoying for us, who are working on the community version
I dont work for PrimeTek, neither other commiters like melloware does.

short version: elite releases are managed by PrimeTek, they decide what fixes will be done. We can just ping @mertsincan here, that this is an elite issue. PrimeFaces PRO users has a own issue board, which will be fixed for elite releases for sure.

So thats all i can do and i would close the this issue report here.
If this issue still persists in 11.0, we must check it and fix in trunk. Therefore i ask.

**Comment by tandraschko** [comment]
i will now trigger a discussion with PrimeTek, how this should be handled in the future

**Comment by melloware** [comment]
@tandraschko i think this still happens on 12.0 Snapshot.  The issue seems to be around using client validation on "key up" behavior. 

<p:inputText id="integer" value="#{validationView.integer}">
                                <p:clientValidator event="keyup"/>
                            </p:inputText>

**Comment by tandraschko** [comment]
primefaces.CLIENT_SIDE_VALIDATION is missing in web.xml

**Comment by StevenHachel** [comment]
@tandraschko thx!

Final question: The community version would then be version 8.0/10.0/11.0/... ?
This means that if I report bug fixes for these versions, the fixes would not be included in the respective version, e.g. 8.0, but only fixed in the following version 10.0 or 11.0?

**Comment by melloware** [comment]
Yep you have it right. Unless you have PRO support then you have a direct channel to PrimeTek and can get issues resolved in Elite releases.

**Comment by tandraschko** [comment]
i will add a warning when rendering `p:clientValidator` and disabled CSV

**Comment by melloware** [comment]
I think a warning or console.error would be great when its not configured right.
