### ISSUE TITLE
Datepicker: Change event is not called when pasting date and using mask="true"

### ISSUE THREAD

**Issue by mn-qualitasag** [primefaces/primefaces#8319]
**Describe the defect**
Additional issue in the datepicker like in issue #7176, where the change event is not fired when mask="true" and the date is **entered**, the change event is also not fired when mask="true" and a date is **pasted**. So when one pastes a date an leave the Datepicker input field (blur), the date is cleared. Also the date is not selected in the popout.

**Environment:**
 - PF Version: 10.0 and 11.0
 - JSF + version: MyFaces 2.2.12
 - Affected browsers: At least Firefox and Chrome

**To Reproduce**
1. Copy a correct formatted date (eg. in de _01.01.2022_) from somewhere to clipboard
2. Paste this content from clipboard into a datepicker with mask="true"
3. See that date is not selected in popout of the datepicker
4. Blur datepicker
5. See that pasted content was cleared

**Expected behavior**
When a correct formatted date is pasted into datepicker input field with mask="true", date is selected in the popout and pasted date stays when datepicker looses focus.

**Example XHTML**
```html
<h:form id="frmTest">
    <div class="p-grid" style="max-width:30em">
        <div class="p-col-6">
            Field for enter and copy something
        </div>
        <div class="p-col-6">
            <p:inputText />
        </div>
        <div class="p-col-6">
            Datepicker without masking
        </div>
        <div class="p-col-6">
            <p:datePicker mask="false" />
        </div>
        <div class="p-col-6">
            Datepicker with masking
        </div>
        <div class="p-col-6">
            <p:datePicker mask="true" />
        </div>
    </div>
</h:form>
```
[Datepicker.zip](https://github.com/primefaces/primefaces/files/7926628/Datepicker.zip)

**Comment by melloware** [comment]
i wonder if because pasting needs `input`.  Pasting is always sort of special.  It does work if you manually type the date and not paste it?

**Comment by mn-qualitasag** [comment]
Yes, it works when I manually type the date. This was fixed in #7176.

I also think, that pasting is sort of special. In the firefox dev tools I can see, that the datepicker inputfield has registered events for "paste". So I guess it is handled over this events?

**Comment by melloware** [comment]
yeah it might be something InputMask plugin is doing under the covers

**Comment by mn-qualitasag** [comment]
Okay. And is here on primefaces side a solution possible?

**Comment by melloware** [comment]
looks like its possibly a bug in InputMask: https://github.com/RobinHerbots/Inputmask/issues/2431

**Comment by melloware** [comment]
Got it!  Try this MonkeyPatch: 

```javascript
/* Place any Javascript here you want loaded in test.xhtml */
if (PrimeFaces.widget.DatePicker) {
    PrimeFaces.widget.DatePicker.prototype.applyMask = function() {
        if (this.cfg.inline || this.input.is('[readonly]') || this.input.is(':disabled')) {
            return;
        }
        var $this = this;
        if (this.cfg.mask) {
            var maskCfg = {
                placeholder: this.cfg.maskSlotChar || '_',
                clearMaskOnLostFocus: this.cfg.maskAutoClear || true,
                clearIncomplete: this.cfg.maskAutoClear || true,
                autoUnmask: false,
                onBeforePaste: function(pastedValue, opts) {
                    setTimeout(() => $this.input.trigger("input"), 20);
                    return pastedValue;
                }
            };
            var pattern = new RegExp("m|d|y|h|s", 'i');
            var isAlias = pattern.test(this.cfg.mask);
            if (isAlias) {
                maskCfg.alias = 'datetime';
                maskCfg.inputFormat = this.cfg.mask;
            } else {
                maskCfg.mask = this.cfg.mask;
            }
            this.input.inputmask('remove').inputmask(maskCfg);
        }
    }
}
```

**Comment by mn-qualitasag** [comment]
Okay thank you very much! We'll try that MonkeyPatch with our PF 10.0.6. Perhaps this can also marked for ELITE?

**Comment by melloware** [comment]
Try the MonkeyPatch and confirm it works.  It should work.  I will tag this Elite but there is no guarantee it will be put into an Elite release unless you have PRO support.

**Comment by mn-qualitasag** [comment]
Hi melloware

Can confirm, the patch works. I tested with the example code and in our applications.

Thank you again.
