### ISSUE TITLE
Core: default values with properties file

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#8325]
**Description**
As of today, it's possible to set default value using https://primefaces.github.io/primefaces/11_0_0/#/core/globalattributes
What about making this as built-in feature in PF using properties file?

**Describe the solution you would like**
My proposal looks like this:
- `PrimeApplication` is automatically registered using `faces-config.xml` file
- Property entry looks like this: `org.primefaces.component.calendar.Calendar#pattern=dd/MM/yyyy`

Users just need to declare a `primefaces.properties` file and that's it

WDYT?

**Comment by tandraschko** [comment]
IMO something for JSF specs

**Comment by Rapster** [comment]
Sure, but what about current users running in older JSF versions?

**Comment by tandraschko** [comment]
then he can still use ApplicationWrapper like in our docs
i really dont see that PF should always backport features to older JSF versions

**Comment by tandraschko** [comment]
lets close this in favor of the spec issue
as i said there, it should be directly in the StateHelper, otherwise it blows up viewstate

we can still enhance our sample https://primefaces.github.io/primefaces/11_0_0/#/core/globalattributes, which reads a properties file
