### ISSUE TITLE
InputGroup: Command Button onkeypress not working

### ISSUE THREAD

**Issue by nixonyeung** [primefaces/primefaces#8333]
I have an InputGroup contains InputText and CommandButton and it is located on a dialog.  

If the dialog configured modal="true", onkeypress will not be triggered when key press on the CommandButton.  But when modal="false" the onkeypress is triggered.  Please take a look.

Attached is reproducer run mvn clean jetty:run and navigate to http://localhost:8080/primefaces-test/

[pf-test.zip](https://github.com/primefaces/primefaces/files/7939485/pf-test.zip)

modal="false" -> alert message shown
![image](https://user-images.githubusercontent.com/41794209/151119466-af1b574a-50c5-46ed-96b2-c9d8edff0e54.png)

modal="true" -> nothing happened
![image](https://user-images.githubusercontent.com/41794209/151119561-5e45e819-abe3-4dea-be5e-b9fa62a05815.png)

PF Version: 11.0
JSF + version: _JAVAServer Face 2.2
Affected browsers: ALL

**Comment by jepsar** [comment]
Zip content:
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
        <h:outputScript name="test.js" />
    </h:head>
    <h:body>
		<h1>Input Group Command Button</h1>
		<p:dialog modal="true" visible="true">
			<h:form>
				<div class="ui-inputgroup">
					<p:inputText  />
					<p:commandButton icon="pi pi-clone" onkeypress="alert();"/>
				</div>
			</h:form>
		</p:dialog>
    </h:body>
</html>
```

**Comment by melloware** [comment]
`onkeypress` only works if the button has focus right?  So in the non modal case does the button have focus and in the modal case it doesn't?

**Comment by nixonyeung** [comment]
Both cases the command buttons are on focus(i.e. with blue border) see the screen capture

**Comment by melloware** [comment]
In Modal mode there are two `keypress` events registered

![image](https://user-images.githubusercontent.com/4399574/151170211-e82f37b0-ecf2-4d12-9664-0ad49c7bae10.png)

The document one is `PrimeFaces.utils.preventTabbing(id, zIndex, tabbablesCallback);` if I remove that one then the keypress on the buttons works.  So the preventTabbing is doing an `event.preventDefault()` that is eating the keypress.  That is where the bug is.

**Comment by melloware** [comment]
In fact the lines causing the problem in `preventTabbing` are these lines in the else clause...

```javascript
else if(!target.is(document.body) && (target.zIndex() < zIndex)) {
                    event.preventDefault();
}
```

so the button's zindex must be less than the dialog's zIndex.  We might have to make this smarter somehow.

**Comment by melloware** [comment]
OK so if you remove `<div class="ui-inputgroup">` it works because 

with inputGroup : `target.zIndex() === 1` **incorrect**

without inputGroup: `target.zIndex() === 1004` **correct**

So the jQuery `zIndex()` function is not properly calculating the zIndex for the button.

**Comment by jepsar** [comment]
Don't you need to check if the (indirect) parent of the target is the dialog?

**Comment by melloware** [comment]
i think since its used generically in overlays including Spotlight you have to check whether its up its parent chain is an overlay but i don't think that is quite clear how to do it generically.

**Comment by melloware** [comment]
@nixonyeung here is a workaround that works by adding zIndex to the button...

```xml
<p:commandButton icon="pi pi-clone" onkeypress="alert();" style="z-index: 9999"/>
```
