### ISSUE TITLE
Captcha: Make theme / prefers dark aware

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8335]
<img width="400" alt="Screenshot 2022-01-26 at 15 26 54" src="https://user-images.githubusercontent.com/7500178/151181149-1af7123c-fc9f-43f1-b951-0b275daf0987.png">

https://github.com/primefaces/primefaces/blob/18ae753d683fb3cc4c4dc45ecb5aaccce2ea8b79/primefaces/src/main/java/org/primefaces/component/captcha/CaptchaRenderer.java#L92

**Comment by melloware** [comment]
@jepsar What do you think of this?   Also if this is accepted we can modify LightSwitch for 12.0.0 to use `PrimeFaces.env`.
