### ISSUE TITLE
Tree: Improve node focus styling

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8337]
Select the Saga theme both in PrimeFaces and PrimeVue:

https://www.primefaces.org/showcase/ui/data/tree/selection.xhtml
https://primefaces.org/primevue/showcase/#/tree/selection

The PrimeVue node focus styling is much clearer:

<img width="382" alt="Screenshot 2022-01-26 at 17 20 04" src="https://user-images.githubusercontent.com/7500178/151203226-ad3ed729-3ba3-46aa-a629-05fb39709ac5.png">

vs PrimeFaces:

<img width="298" alt="Screenshot 2022-01-26 at 17 23 48" src="https://user-images.githubusercontent.com/7500178/151203537-761a93f5-61cb-4a3c-b842-2262c4d813d1.png">

**Comment by mertsincan** [comment]
Hi @jepsar,

I have added the necessary styles related to the theme. For a behavior like Primevue, it is necessary to make changes in the core. Even with this change, the theme will add proper styles.

**Comment by jepsar** [comment]
Hi @mertsincan,

That's why I've created this PR https://github.com/primefaces/primefaces/pull/8350
