### ISSUE TITLE
DataTable: Sticky Header is broken on small screens and within layout

### ISSUE THREAD

**Issue by ova2** [primefaces/primefaces#834]
PrimeFaces 5.3

Go to the http://www.primefaces.org/showcase/ui/data/datatable/sticky.xhtml and make the browser window smaller. The sticky header is broken - sometimes displaced, sometimes duplicated, etc.

It is broken within p:layout or pe:layout as well. Header is duplicated by some reason. Here is an image ![Here is an image](http://i.imgur.com/Pv3DlRA.png?1)

**Comment by ova2** [comment]
When this issue can be addressed? It is still brocken, see the showcase.

The header gets also duplicated as I mentioned bevor (see the screen).

**Comment by jwgmeligmeyling** [comment]
Seems that the [left value](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2925) for the sticky header container is not updated after the menu disappears.

**Comment by NarutoTI** [comment]
is there a work around this issue ?

**Comment by tandraschko** [comment]
Sample:

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
        </h:head>

        <h:body>
            <p:layout fullPage="true">
                <p:layoutUnit position="north" size="100" header="Top" resizable="true" closable="true" collapsible="true">
                    <h:outputText value="North unit content." />
                </p:layoutUnit>
                <p:layoutUnit position="center">
                    This layout consists of five different layoutUnits which are resizable and closable by default.

                    <p:dataTable var="car" value="#{dtStickyView.cars}" stickyHeader="true">
                        <p:column headerText="Id">
                            <h:outputText value="#{car.id}" />
                        </p:column>
                        <p:column headerText="Year">
                            <h:outputText value="#{car.year}" />
                        </p:column>
                        <p:column headerText="Brand">
                            <h:outputText value="#{car.brand}" />
                        </p:column>
                        <p:column headerText="Color">
                            <h:outputText value="#{car.color}" />
                        </p:column>
                    </p:dataTable>

                    <div style="margin-bottom: 800px;"></div>
                </p:layoutUnit>
            </p:layout>

        </h:body>
    </f:view>

</html>

`
