### ISSUE TITLE
UICalender: Transformation of @Past/@Future not fully align with the Java EE Bean Validation

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#8344]
**Describe the defect**
With enabled `primefaces.TRANSFORM_METADATA` in `web.xml` the constraint `@Past` on a java field is transformed into the Calendar's maxdate field.

The PrimeFaces transformation sets NOW - 1 DAY, if there is no time (time is considered by the Calendar's pattern)
See code here https://github.com/primefaces/primefaces/blob/fc76cdf76b8ba4f31833de176b0c2bb5106081f3/primefaces/src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java#L173
**-> Date TODAY is invalid**

The `@Past` Java EE implementation (https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/Past.html) always considers time, if the type of field has time information.
**-> Date TODAY is valid**

**Reproducer**
[reproducer.zip](https://github.com/primefaces/primefaces/files/7973811/reproducer.zip)

**Environment:**
 - PF Version: 11.0.0
 - PF Theme: -
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: ALL

**To Reproduce**

Case1: WITH PrimeFaces MetaData Transformation

1. mvn clean jetty:run and start http://localhost:8080/primefaces-test/ in browser
2. Datepicker is prefilled with TODAY
3. Press "Submit"
4. Validation error appears, the input is NOT valid

Case2: WITHOUT PrimeFaces MetaData Transformation

1. Remove
```
<context-param>
	<param-name>primefaces.TRANSFORM_METADATA</param-name>
	<param-value>true</param-value>
</context-param>
```
from web.xml
1. mvn clean jetty:run and start http://localhost:8080/primefaces-test/ in browser
2. Datepicker is prefilled with TODAY
3. Press "Submit"
4. Validation passes, input is valid

**Expected behavior**
The type of field should be considered, when setting maxdate.
java.time.LocalDate -> NOW - 1 DAY
java.time.YearMonth -> NOW - 1 MONTH
Other dates -> NOW

**Comment by melloware** [comment]
@pfumi I am having trouble reproducing your issue with your reproducer above.

So today is Jan 29.  When I run with `primefaces.TRANSFORM_METADATA=true` it makes today unselectable and defaults my date to Jan 28th which is the first valid day in the PAST?

And it makes TODAY the 29th greyed out as not selectable since its NOT in the Past.

![image](https://user-images.githubusercontent.com/4399574/151665093-8d7a4d1f-6b64-4ac3-8154-4be8854d3d6a.png)

So I am not able to reproduce the problem you are stating with your steps above?

**Comment by pfumi** [comment]
If you take today 29 Jan as
java.util.Date, that is: 2022-01-29 00:00.000000 

1) With `primefaces.TRANSFORM_METADATA=true` maxdate is validated on submit as follow: 
2022-01-29 00:00.000000 < 2022-01-28

2) With `primefaces.TRANSFORM_METADATA=false` the `@Past` constraint is validated on submit as follow:
2022-01-29 00:00.000000 < 2022-01-29 18:01.000000 (time NOW)

For 1) today as date is invalid, for 2) it is valid.

The validation in 1) should be the same as the validation of 2)
My suggestion, consider for 1) the type of the field, not the calendar pattern, see also the part "Expected behavior" in my first post.

**Comment by melloware** [comment]
But why can't reproduce it with your sample?  I run your example and follow your instructions exactly and it all works for me with no errors?

**Comment by pfumi** [comment]
I think the cases in the description were swapped, can you please try again, sorry for that, I updated the description!

I tried it myself again with reproducer in the description, and I have two different behaviors with CASE 1 and CASE 2

**Comment by pfumi** [comment]
The only thing which is important, that in both cases 2022-01-29 is filled in, and with submit there are different results with the validation

**Comment by melloware** [comment]
Weird in your one case it won't let me fill in 01-29 it defaults to 01-28 like in my screenshot as the first valid day allowed.

**Comment by pfumi** [comment]
Hmm I can fill in 2022-01-29, it doesn't get changed to 2022-01-28, is this a locale thing? I'm on DE locale, you are on EN_US right? I try tomorrow again..

**Comment by melloware** [comment]
Yes I am on en_US. I am wondering if that is it.

**Comment by melloware** [comment]
Same result today. It is Jan 30th but the DatePicker is smart enough to default to Jan 29th and not allow the 30th to be selectable.

![image](https://user-images.githubusercontent.com/4399574/151706729-771cd928-1df8-467f-bc77-795489ec5fbb.png)

**Comment by melloware** [comment]
Another thing to consider is how it is calculating NOW...

```java
/**
     * Calculates NOW based on the calendar's current timezone or will default to system timezone if none set.
     * It will return a LocalDateTime if time units needed else just a LocalDate if no time is needed.
     *
     * @param uicalendar the base calendar to calculate NOW for
     * @return a Temporal representing either a Date or DateTime
     */
    public static Temporal now(UICalendar uicalendar) {
        boolean timeOnly = uicalendar.isTimeOnly();
        ZoneId zone = calculateZoneId(uicalendar.getTimeZone());
        if (timeOnly) {
            return LocalTime.now(zone);
        }
        boolean hasTime = uicalendar.hasTime();
        return hasTime ? LocalDateTime.now(zone) : LocalDate.now(zone);
    }
```

**Comment by pfumi** [comment]
@melloware 
I think the result of `org.primefaces.util.CalendarUtils#now` doesn't matter, because in line `DatePicker:213/214` min-/maxdate is always converted to `LocalDate`.

I again tested everything, and now I can tell you this (I hope it's now better reproducable)

The timezone was wrong in the example, this caused this weird problems, now it's the system timzone sorry for that.
_**I updated the reproducer in the description!**_

I debugged a bit into the code, and first the BeanValidator validates the input.

CASE 1 & CASE 2
* The input TODAY+1 throws a ValidatorException (see line `DatePicker:121` and then `UIInput:1186`)
  ![pic1](https://user-images.githubusercontent.com/6900303/151860417-0f51d892-cfcd-43e2-87aa-634c8ae19041.png)
  **-> CORRECT**

CASE 1
* The input TODAY passes the validation on line `DatePicker:121`.
  Next PrimeFaces validates on line `DatePicker:124`, and the validation fails. (This is because of the wrong maxdate)
  ![pic2](https://user-images.githubusercontent.com/6900303/151860521-30a3934a-0c01-4dbc-9fc0-4a30eb5e5241.png)
  **-> WRONG**

CASE 2
* The input TODAY passes the validation on line `DatePicker:121`.
  Next Primefaces validates, and validation passes, because no maxdate is set (`primefaces.TRANSFORM_METADATA=false`)
![pic3](https://user-images.githubusercontent.com/6900303/151861080-e68ba63b-9aaa-4fb6-bcb8-d6b563360976.png)
  **-> CORRECT**

**Comment by melloware** [comment]
Ahh I think you are right the real bug is when using `java.util.Date` its converting it to `LocalDate`.

**Comment by melloware** [comment]
The problem is here:
```java
else if (value instanceof Date) {
            if (isShowTime()) {
                ZoneId zoneId = CalendarUtils.calculateZoneId(getTimeZone());
                validationResult = validateDateValue(context, CalendarUtils.convertDate2LocalDate((Date) value, zoneId),
                        CalendarUtils.convertDate2LocalTime((Date) value, zoneId));
            }
            else {
                validationResult = validateDateValue(context, CalendarUtils.convertDate2LocalDate((Date) value, CalendarUtils.calculateZoneId(getTimeZone())));
            }
        }
```

To fix your issue above change your DatePicker to `showTime="true"`..

```xml
<p:datePicker value="#{testView.date}" pattern="yyyy-MM-dd" showTime="true"/>
```

Since for a Date it has no idea what you want but without a TIME it has to assume you want a true local date.

**Comment by pfumi** [comment]
I think the problem is still here https://github.com/primefaces/primefaces/blob/fc76cdf76b8ba4f31833de176b0c2bb5106081f3/primefaces/src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java#L173

`java.util.Date`, `java.time.LocalDateTime`, `java.time.LocalTime` have time information per default of the data type, also used with `showTime="false"`, it's still in the backing with time 00:00
`java.time.LocalDate`, `java.time.YearMonth` have truly no time

If I want to use a field with time (based on the datatype), but dont show the time (with `showTime="false"`) then the
conversion `@Past` into `maxdate` is just incorrect.

I think converting `@Past` into `maxdate` is only correct, if you consider the datatype of the field.

I would suggest to replace this line https://github.com/primefaces/primefaces/blob/fc76cdf76b8ba4f31833de176b0c2bb5106081f3/primefaces/src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java#L173
with
```
Class<?> dataType = uicalendar.getValueType();
if (dataType != null) {
  if (LocalDate.class.isAssignableFrom(dataType)) {
      uicalendar.setMaxdate(now.minus(1, ChronoUnit.DAYS));
  } else if (YearMonth.class.isAssignableFrom(dataType)) {
      uicalendar.setMaxdate(now.minus(1, ChronoUnit.MONTHS));
  } else {
     uicalendar.setMaxdate(now);
  }
} else {
    uicalendar.setMaxdate(now);
}
```

**Comment by melloware** [comment]
I assume we would have to do the same for `minDate` or `@Future` ?

**Comment by pfumi** [comment]
For `@Future` I think the logic is correct, because for example if you have a `java.util.Date` with TODAY, this would set `mindate` to NOW+1 day.
That means, it validates
2022-02-01 00:00.000000 (TODAY) >= 2022-02-02 (TODAY + 1 DAY)
Just `@Future` would validate
2022-02-01 00:00.000000 (TODAY) > 2022-02-01 21:21.000000 (TIME NOW)

So both are correct, if `showTime="false"`, then the time part is 00:00.000000, and then it has to be at least TOMORROW for a valid input.

The only thing I could imagine, `java.time.YearMonth` has to be NOW + 1 Month, not + 1 Day.

**Comment by melloware** [comment]
OK I simplified your logic a little bit.  Please review my PR and thanks for the help!

**Comment by pfumi** [comment]
One suggestion

You could write this code
```
Object minDate = now.plus(1, ChronoUnit.DAYS);
Class<?> dataType = uicalendar.getValueType();
if (dataType != null && YearMonth.class.isAssignableFrom(dataType)) {
    minDate = now.plus(1, ChronoUnit.MONTHS);
}
uicalendar.setMindate(hasTime ? now : minDate);
```
also this way
```
Object minDate = now;
if (!hasTime) {
    Class<?> dataType = uicalendar.getValueType();
    if (dataType != null && YearMonth.class.isAssignableFrom(dataType)) {
        minDate = now.plus(1, ChronoUnit.MONTHS);
    } else {
        minDate = now.plus(1, ChronoUnit.DAYS);
    }
}
uicalendar.setMindate(minDate);
```

The rest looks great. Thanks for your time and effort!

**Comment by melloware** [comment]
Done!  good teamwork!

**Comment by pfumi** [comment]
@melloware Don't forget to merge it into master 😉

**Comment by melloware** [comment]
Never 😁
