### ISSUE TITLE
Inputtextarea: overflows container

### ISSUE THREAD

**Issue by seinecle** [primefaces/primefaces#8349]
PF 10.0.0

A wide `InputTextArea` will not resize to the proper width when needed : when displayed on a mobile screen for example. 

An example is visible from the showcase itself: the last example on the page overflows its container when displayed on a mobile phone in portrait mode:

https://www.primefaces.org/showcase/ui/input/inputTextarea.xhtml?jfwid=ece10

**Comment by jepsar** [comment]
The rendered `textarea` has no width set, it only has a `cols` attribute, so the behavior is expected. If you want it to scale to the available width, wrap it in `<div class="ui-fluid">...</div>`.

**Comment by seinecle** [comment]
Thank you!
