### ISSUE TITLE
primefaces5.3.jar boken p<menuitem>

### ISSUE THREAD

**Issue by merlcrepsjr** [primefaces/primefaces#835]
When viewing in Chrome browser the <p:submenu> with multiple submenu items does not display properly.  primefaces5.1 jar displays correctly.

The 5.3jar does overlays the submenu items directly on top of the menuitems.  This prevents a clean view.  If needed i can supply the xhtml file

**Comment by cagataycivici** [comment]
Please provide xhtml markup.

**Comment by andyfinch** [comment]
I had a similar issue with a panelMenu.  Some of my menuItems contained anchors and I believe that a change to render anchors for menuItems left me with anchors in anchors.  I had to refactor and handle the links with javascript.

**Comment by tandraschko** [comment]
no example -> invalid
