### ISSUE TITLE
OverlayPanel: The panel does not close when the user is tabbing out of it

### ISSUE THREAD

**Issue by marw1tt** [primefaces/primefaces#8352]
**Describe the defect**
If the content of the overlay panel is accessed through tabbing to the next control, it should close if the tab focus leaves the overlay panel contents.

**Reproducer**
The defect can be reproduced within the [primefaces showcases](https://www.primefaces.org/showcase/ui/overlay/overlayPanel.xhtml?jfwid=1a87e)

**Environment:**
 - PF Version: _10.0.0_
 - PF Theme: _Diamond_
 - MyFaces _2.3.8_
 - Browser: _ALL_

**To Reproduce**
Go to the overlayPanel showcase and open the overlay panel with the keyboard by pressing space. After that, tab through the overlay panel contents and when the tab focus jumps to the next control outside the panel, the panel stays open, which is bad for accessibility.

**Expected behavior**
If you leave the overlay panel with the tab focus through tabbing to the next control, the overlay panel must close itself. 

**Example XHTML**
provided by the linked showcase

**Comment by melloware** [comment]
Yep right now its looking for mousedown outside the panel.

```javascript
 //hide overlay when mousedown is at outside of overlay
        if (this.cfg.dismissable && !this.cfg.modal) {
            this.hideOverlayHandler = PrimeFaces.utils.registerHideOverlayHandler(this, 'mousedown.' + this.id + '_hide', this.jq,
                function() { return $this.target; },
                function(e, eventTarget) {
                    if (!($this.jq.is(eventTarget) || $this.jq.has(eventTarget).length > 0 || eventTarget.closest('.ui-input-overlay').length > 0)) {
                        $this.hide();
                    }
                });
        }
```

**Comment by melloware** [comment]
Here is a MonkeyPatch for PF10 that fixes the issue it checks for either mousedown or keyup to see if you have tabbed out of the overlaypanel.

```javascript
if (PrimeFaces.widget.OverlayPanel) {
    PrimeFaces.widget.OverlayPanel.prototype.bindPanelEvents = function() {
        var $this = this;

        //hide overlay when mousedown is at outside of overlay
        if (this.cfg.dismissable && !this.cfg.modal) {
            var eventNamespace = 'keyup.' + this.id + '_hide mousedown.' + this.id + '_hide';
            this.hideOverlayHandler = PrimeFaces.utils.registerHideOverlayHandler(this, eventNamespace, this.jq,
                function() {
                    return $this.target;
                },
                function(e, eventTarget) {
                    if (!($this.jq.is(eventTarget) || $this.jq.has(eventTarget).length > 0 || eventTarget.closest('.ui-input-overlay').length > 0)) {
                        $this.hide();
                    }
                });
        }

        this.resizeHandler = PrimeFaces.utils.registerResizeHandler(this, 'resize.' + this.id + '_hide', this.jq, function() {
            $this.hide();
        });

        this.scrollHandler = PrimeFaces.utils.registerConnectedOverlayScrollHandler(this, 'scroll.' + this.id + '_hide', this.target, function() {
            $this.hide();
        });
    }
};
```

**Comment by melloware** [comment]
@miedrl since you have a good handle on accessibility do you agree with this change?  Personally I feel like this is the correct change to make for accessibility.
