### ISSUE TITLE
FileUpload: Tilde as first character in filename causes StringIndexOutOfBoundsException on Windows

### ISSUE THREAD

**Issue by jrajsky** [primefaces/primefaces#8359]
**Describe the defect**
When component p:fileUpload is used to upload a file with name starting with tilde character (ie: _~myfile.txt_), application crashes on 
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at org.primefaces.util.FileUploadUtils.getValidFilename(FileUploadUtils.java:66)
```

The issue lies in method _FileUploadUtils:getValidFilename()_ - 
on line 66: String[] parts = filename.substring(FilenameUtils.getPrefixLength(filename)).split(Pattern.quote(File.separator));
FilenameUtils.getPrefixLength(filename) returns filename.lenght() + 1 which causes filename.substring(...) to crash
variable filename in my case contains only the filename (without path): _~myfile.txt_

**Environment:**
 - PF Version: _10.0.7_
 - PF Theme: default
 - JSF + version: JoinFaces 4.5.8
 - Affected browsers: Windows, ALL

**To Reproduce**
1. Select a file using fileUpload
2. Upload is about to start
3. See error

**Expected behavior**
File is uploaded and handleFileUpload() on associated bean is called.

**Example XHTML**
```html
<h:form id="idForm" enctype="multipart/form-data" prependId="false">
<p:fileUpload id="idDlgDownloadLocalFile" label="Upload" previewWidth="40" mode="advanced" auto="true" process="@this" listener="#{testView.handleFileDownload}" fileLimit="1" sequential="true" update="idForm" sizeLimit="2147483647" />
<p:messages id="idMsgDownloadLocalFile" showDetail="true" />
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
  public void handleFileDownload(FileUploadEvent event) {
    // doesn't matter, the code is not executed
  }
}
```

**Comment by melloware** [comment]
I will investigate.

**Comment by jepsar** [comment]
@melloware let me know if I need to test on macOS

**Comment by melloware** [comment]
OK PR Submitted.  Confirmed it was definitely broken on Windows.  Added unit test so it should run on all OS's.
