### ISSUE TITLE
Enhance captcha to allow secure token

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#836]
Sinve v2 recaptcha global keys are not supported anymore and one must add each domain to the domain list of the key in recaptcha administration tool.

This is not required if the secure token is used:

https://developers.google.com/recaptcha/docs/secure_token

Giving this option to primefaces users would be great.

_Java example:_
https://github.com/google/recaptcha-java/tree/master/appengine

**Comment by melloware** [comment]
Google removed support for secure token on May 18, 2016.  See: https://github.com/ambethia/recaptcha/issues/179

Closing this ticket.
