### ISSUE TITLE
FilterConstraint: Don't convert values for each row

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8363]
Now values are converted for each row, examples:

https://github.com/primefaces/primefaces/blob/a910479dd4febb60d99123f100265c5647b02ef7/primefaces/src/main/java/org/primefaces/model/filter/ComparableFilterConstraint.java#L42

https://github.com/primefaces/primefaces/blob/a910479dd4febb60d99123f100265c5647b02ef7/primefaces/src/main/java/org/primefaces/model/filter/StringFilterConstraint.java#L39

with the id we can cache converted values as a request attribute

**Comment by tandraschko** [comment]
i dont like caching at all
IMO if someone needs high performance, its better to use LazyDataModel

maybe there is a better way to compare numbers without creating BigDecimal

**Comment by jepsar** [comment]
I agree lazy model is the best option for performance.

BigDecimal is a generic way to compare different number types and it is easy to parse based on a locale.

**Comment by tandraschko** [comment]
how do non-lazy table work with paging?
lets assume 10 pages, 10 rows each page
what happens when e.g. 10 rows are "full" when filtering 30 rows; do we still filter the next 70 values?

**Comment by jepsar** [comment]
I assume we do. The paginator need to be updated.

**Comment by Rapster** [comment]
-1 for having a cache

I just had a look, and indeed, converting for every row the very same value is not ideal... Unfortunately, I don't think there is a way to deduce the binded type from FilterMeta#filterBy VE (or is it?) so we could reuse it later for the conversion to apply. Conversion ideally should be done in `UITable#updateFilterByValuesWithFilterRequest` when filterValue is actually set...

**Comment by jepsar** [comment]
It turned out to be simple. A converter must be added to the filter. I added an exception if it was forgotten by the user.

**Comment by Rapster** [comment]
Should we close this then and focus on #8369 ?

**Comment by jepsar** [comment]
I don't think we need to do one of both, this should be fixed any way, and #8369 can follow as an enhanced convenience feature.

**Comment by Rapster** [comment]
Ok I think I get it, I got confused 😅
