### ISSUE TITLE
Calendar: Problem with Spanish time format AM/PM

### ISSUE THREAD

**Issue by BryanGarro25** [primefaces/primefaces#8365]
The component shows the hour like this: 8:15 p. m. instead of 8:15 PM (this just happens in spanish), when I change the date, it changes the format from p. m. to PM, and it fails throwing the next error message:
Error ' 8:15 PM' no se ha podido reconocer como hora. Ejemplo:  8:15 p. m.

I need the format to stay PM no matter the language.

In database is stored like this: 20:15:00

 - PF Version: 10.0.0
 - PF Theme: babylon

```html

  <p:calendar readonlyInput="true" showButtonPanel="true" navigator="true" id="arrivalTime" value="20:15:00" pattern="h:mm aa" timeOnly="true" />

```

locale
```js
PrimeFaces.locales["es"] = {
    closeText: "Cerrar",
    prevText: "Anterior",
    nextText: "Siguiente",
    monthNames: ["Enero","Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    monthNamesShort: ["Ene.", "Feb.", "Mar.", "Abr.", "May.", "Jun.", "Jul.", "Ago.", "Sep.", "Oct.", "Nov.", "Dic."],
    dayNames: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    dayNamesShort: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
    dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
    weekHeader: "Semana",
    firstDay: 0,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: "",
    timeOnlyTitle: "Solo hora",
    timeText: "Tiempo",
    hourText: "Hora",
    minuteText: "Minuto",
    secondText: "Segundo",
    currentText: "Fecha actual",
    ampm: false,
    month: "Mes",
    week: "Semana",
    day: "Día",
    allDayText : "Todo el día"
};
```

To change the locale:
```java
public void changeLanguage(String language) {
//language could be "es" or "en"
     FacesContext.getCurrentInstance().getViewRoot().setLocale( new Locale(language));
}
```

**Comment by melloware** [comment]
I will investigate I hope it's just bad data.

**Comment by melloware** [comment]
Calendar is deprecated you should be using `DatePicker` instead.    Can you confirm the issue happens with DatePicker as well?

**Comment by melloware** [comment]
Please  provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by BryanGarro25** [comment]
> Calendar is deprecated you should be using `DatePicker` instead. Can you confirm the issue happens with DatePicker as well?

yes, I tried with date picker too and the problem persists

**Comment by melloware** [comment]
The bug is in the Java Local for Time/Date for `es`.

ES = a. m., p. m. : https://www.localeplanet.com/java/es-ES/index.html

EN = AM/PM : https://www.localeplanet.com/java/en-US/index.html

And I believe we are deferring to the JDK to do the `java.time` formatting.

**Comment by melloware** [comment]
@BryanGarro25 can you put together a PrimeFaces test reproducer for me please? 
 [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.

**Comment by melloware** [comment]
@BryanGarro25 going to close this ticket until you provide a reproducer so we can debug the issue.
