### ISSUE TITLE
Component: "p.column headerText" does not support EL

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#8366]
**Description**
Please provide support detection of EL within `<p.colum headerText=""/>` , if possible.

**Describe the solution you would like**
I would like that PR renders something like this  `<p.colum headerText="#{bean.title}"/>`

**Comment by Rapster** [comment]
Based on what you would like, and the little description you're giving, this shoud be already working

**Comment by nimo23** [comment]
> this shoud be already working

I also supposed this, however, if so, then it seems to be **bug** because it does **not** work:


This works, as I do not use EL within `headerText`:

```
<p:dataTable ..>
<!-- the headerText is rendered successfuly -->
<p:column headerText="myTitleText">
<!-- the el is evaluated successfully: -->
<div>{bean.title}"</div>
</p:column>
```


This does NOT work, as I use EL within `headerText`:

```
<p:dataTable ..>
<!-- the el within the headerText is not evaluated, thus the header text is NOT rendered-->
<p:column headerText="{bean.title}">
<!-- the el is evaluated successfully: -->
<div>{bean.title}</div>
</p:column>
```

I use current jsf version with current PF version.

**Comment by Rapster** [comment]
Oh yeah, no that can't work. There is ONE headerText per column for all rows. bean = row, and when column#headerText is encoded, bean is not available yet  (and will be whenever rows have to be encoded)

**Comment by nimo23** [comment]
Yes, I supposed that. Feel free to close this issue if it cannot be resolved.

**Comment by Rapster** [comment]
It can't be resolved, you should have a second look on what you're trying to do 😉
