### ISSUE TITLE
DataTable: Dynamically rendered columns are not filterable/sortable

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#8368]
**Describe the defect**
In our application we have cases where columns are added/removed dynamically by switching the "rendered"-attribute of each column. The column gets added but sorting and filtering is not working. This worked in previous versions of Primefaces. You can see the issue in the showcase "DataTable - Dynamic Columns" when adding a new column "representative". I have also added a reproducer which showcases this problem in smaller size.

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/7977071/primefaces-test.zip)
https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml?jfwid=87ffd

**Environment:**
 - PF Version: _11.0.0_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start Reproducer
2. Test Sorting/Filtering functionality on the initial column -> works
3. Press Button "Show Column"
4. Test Sorting/Filtering functionality on the 2nd column -> does not work

**Expected behavior**
Same behaviour as in Primefaces 10 (working).

**Further Info**
I am quite sure that the underlying problem is similar to #8159, that being, that the sortByAsMap/filterByAsMap values are not updated and therefore the newly added column having nothing to go by when sorting/filtering. I have opened a PR #8358 which I believe contains the fix to the problem.

#8159 was closed with the suggestion to reset the values of sortByAsMap/filterByAsMap to null, which **would also work** for this reproducer and our application. However, in my opinion this is might not be the best solution, since every application using this feature has to be migrated in order to work. If we decide to use this approach, we should leave a hint in the migration guide and update the showcase for PF11, where it is currently used.

The fix I was proposing in my PR adds two lines which were previously there in PF10 and got lost in transition to PF11. Adding those back fixes the problem. With that solution it wouldn't be necessary to update the showcase as well.  But I am open for other ideas or arguments against my approach.

**Excerpt from my comment under #8159**
After some time debugging I noticed that the functions isColumnSortable() / isColumnFilterable() from UITable are always called from within the encodeColumnHeader function of the DataTableRenderer. In PF10 it was here, where the sortByAsMap property was newly set.

For some reason though a line was dropped from PF10 to PF11 which resets the value. Please see below:

Primefaces 10

    default boolean isColumnSortable(FacesContext context, UIColumn column) {
        Map<String, SortMeta> sortBy = getSortByAsMap();
        if (sortBy.containsKey(column.getColumnKey())) {
            return true;
        }

        SortMeta s = SortMeta.of(context, getVar(), column);
        if (s == null) {
            return false;
        }

        // unlikely to happen, in case columns change between two ajax requests
        sortBy.put(s.getColumnKey(), s);
        setSortByAsMap(sortBy);
        return true;
    }

Primefaces 11

    default boolean isColumnSortable(FacesContext context, UIColumn column) {
        Map<String, SortMeta> sortBy = getSortByAsMap();
        if (sortBy.containsKey(column.getColumnKey())) {
            return true;
        }

        // lazy init - happens in cases where the column is initially not rendered
        SortMeta s = SortMeta.of(context, getVar(), column);
        if (s != null) {
            sortBy.put(s.getColumnKey(), s);
        }
        // setSortByAsMap(sortBy); is missing here

        return s != null;
    }

Although isColumnFilterable looks different to isColumnSortable in PF10, in PF11 they almost look identical. Adding a setFilterByAsMap(filterBy) at the same position as above fixed the filtering for me as well.

**Comment by tandraschko** [comment]
in general, without checking your case now, your fix might work if you add a new column
also this case should currently work as we add the new column to the sortBy reference, not sure why it doesnt work

but your fix wont work if column order will change as the columnKey contains the count and you MUST reset sortBy/filterBy and so on
we might provide a helper method here

**Comment by tandraschko** [comment]
```
    /**
     * Resets all column related state after adding/removing/moving columns.
     */
    default void resetColumns() {
        resetDynamicColumns();
        setColumns(null);
        setSortByAsMap(null);
        setFilterByAsMap(null);
        setColumnMeta(null);
    }
```

i would add something like this to UITable. WDYT @Rapster ?

**Comment by Rapster** [comment]
I remember facing that issue when I refactored DataTable... I remember I had to call setSortByAsMap/setFilterByAsMap after modifying metas. If you call getSortByAsMap/getFilterByAsMap after adding the value, I don't think it will return the updated map,  maybe something to do with view state and serialization?

**Comment by tandraschko** [comment]
it should actually work but i think it doesnt hurt to add those 2 statements back

however, this will just fix if you add a new column to the end
we need such a method like mentioned above anyway

**Comment by Rapster** [comment]
I have nothing against adding this method, but as long as Column#columnKey is based on clientId, we'll be facing this sort of issues

**Comment by jepsar** [comment]
I just fell into this pit. Resetting columns is not fully fixing the issue for me. If I've filtered on a column that will be removed in the update it fails, so I probably need to reset the sortBy and filterBy as well.

**Comment by jepsar** [comment]
Hmm.. filter input values are saved though, but not applied. I can hack my way out if it by `oncomplete="PF('dataTable').filter()`, but it's not very nice.

<img width="1153" alt="Screenshot 2022-03-02 at 17 47 14" src="https://user-images.githubusercontent.com/7500178/156408649-41d9b343-510f-412e-80bb-f98c297bf579.png">

<img width="1157" alt="Screenshot 2022-03-02 at 17 47 30" src="https://user-images.githubusercontent.com/7500178/156408672-133a3fe7-33b9-4393-9722-74a2abce93c7.png">

**Comment by jepsar** [comment]
I gave my columns a fixed `id` and added this to my bean:
```java
  private List<SortMeta> sortBy; // can be initialized
  private List<FilterMeta> filterBy; // can be initialized

  public void onColumnRenderedChange(final String clientId) {
    final DataTable dataTable = (DataTable) Components.findComponent(clientId);
    dataTable.resetDynamicColumns();
    dataTable.setColumns(null);
    dataTable.setSortByAsMap(null);
    dataTable.setFilterByAsMap(null);
    dataTable.setColumnMeta(null);
    final List<String> columnKeys = new ArrayList<>();
    dataTable.forEachColumn(column -> columnKeys.add(column.getColumnKey()));
    filterBy.removeIf(filterMeta -> !columnKeys.contains(filterMeta.getColumnKey()));
    sortBy.removeIf(sortMeta -> !columnKeys.contains(sortMeta.getColumnKey()));
  }
```
this eliminates my need to do `oncomplete="PF('dataTable').filter()`

**Comment by tandraschko** [comment]
in 12.0 you can even use:

```
  public void onColumnRenderedChange(final String clientId) {
    final DataTable dataTable = (DataTable) Components.findComponent(clientId);
    dataTable.resetColumns();
    final List<String> columnKeys = new ArrayList<>();
    dataTable.forEachColumn(column -> columnKeys.add(column.getColumnKey()));
    filterBy.removeIf(filterMeta -> !columnKeys.contains(filterMeta.getColumnKey()));
    sortBy.removeIf(sortMeta -> !columnKeys.contains(sortMeta.getColumnKey()));
  }
```
