### ISSUE TITLE
Column: Add converter attribute for filter and short notation

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8369]
So you can do
```xhtml
<p:column headerText="ID lt" field="id" filterMatchMode="lt" converter="javax.faces.Integer"/>
```
instead of
```xhtml
<p:column headerText="ID lt" field="id" filterMatchMode="lt">
    <f:facet name="filter">
         <p:inputText onkeyup="PF('wgtTable').filter()">
              <f:converter converterId="javax.faces.Integer" />
          </p:inputText>
     </f:facet>
</p:column>
```

**Comment by Rapster** [comment]
What about this instead of adding a new attr?

```xml
<p:column headerText="ID lt" field="id" filterMatchMode="lt">
    <f:converter converterId="javax.faces.Integer" />
</p:column>
```

or
 ```xml
<p:column headerText="ID lt" field="id" filterMatchMode="lt" converter="javax.faces.Integer" />
```
That way, it's not only limited to filtering, it could be quite convenient using shorthand notation (e.g `<p:column field="xxx" />`)

Maybe not possible as it requires to implement ValueHolder if I remember correctly?

**Comment by tandraschko** [comment]
+1 to improve improve #8363 / example

i wonder in your example @Rapster, can we support p:columns when attaching f:converter?
you know, f:converter has some disadvantages in dynamic tags like ui:repeat - not sure about this case

**Comment by eduarddrenth** [comment]
Great!

**Comment by Rapster** [comment]
Since `f:converter` is resolved at build time, it wouldn't work straight away, you'll have to define a converter that resolve the proper converter at render time. The thing with supporting this is like I said, `UIColumn` will have to implement `ValueHolder` and I don't know how smart this is...

I would call the attribute `converter` since it could be used not only for filtering. Just to be sure, this new attribute would only makes sense for short notation and input filter (not anything else)?

**Comment by tandraschko** [comment]
+1 for converter attr for now

**Comment by tandraschko** [comment]
@jepsar will you work on it soon? would like to see it

**Comment by jepsar** [comment]
Yeah. I want to do the inline Ajax status of split and menu button, and then I'll have a look at this.

**Comment by Rapster** [comment]
@jepsar Can these lines 
https://github.com/primefaces/primefaces/blob/cc237b345bf728ba90e7c4d22d05f840916871d5/primefaces/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java#L152-L161

be moved in `UITable#updateFilterByValuesWithFilterRequest` ? I think it is a more appropriate place to be

**Comment by jepsar** [comment]
I think they can be moved. Let me check on the exception. I guess it's to prevent the table from breaking on invalid input / while typing.

**Comment by Rapster** [comment]
Ok I'll give it a try, I'll apply also this on <p:columns />, and also once #10776 is merged, I want to make converter optional for this use case, since we can guess field type with the new cache properties, and deduce which converter to use
