### ISSUE TITLE
SortMeta Constructor should be public

### ISSUE THREAD

**Issue by handschriftenportal-dev** [primefaces/primefaces#8370]
https://github.com/primefaces/primefaces/blob/d8acc5196925c234c69c143036b02619a72d0eb9/src/main/java/org/primefaces/model/SortMeta.java#L63

Field columnKey can´t be set due to package private Contructor and field not present in Builder.

**Comment by Rapster** [comment]
Please follow issue template or will be closed as invalid. The reason it's not exposed, is because columnKey is based on clientId which is anondeterministic value

**Comment by melloware** [comment]
Going to close as invalid for now unless OP comes back with a good reason why it needs to be exposed. @handschriftenportal-dev let us know why you need this as Rapster pointed out this is a calculated value.
