### ISSUE TITLE
Datatable: ContextMenu is duplicated by the native one when contextMenu behavior is present

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#8376]
onRowRightClick (https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2451) should return a value, as is expected by https://github.com/primefaces/primefaces/blob/97b0180f488e109b3dc898b9920fe8cca661df88/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L1276
The return value might be this.hasBehavior('contextMenu')

**Environment:**
 - PF Version: _11.0.0_
 - Affected browsers: ALL_

**Expected behavior**
Only the component context menu should be shown, not also the browser native one.

**Comment by melloware** [comment]
Can you try this MonkeyPatch?

```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.onRowRightClick = function(event, rowElement, cmSelMode, fnShowMenu) {
        var row = $(rowElement),
            rowMeta = this.getRowMeta(row),
            selected = row.hasClass('ui-state-highlight');

        this.assignFocusedRow(row);

        if (cmSelMode === 'single' || !selected) {
            this.unselectAllRows();
        }

        this.selectRow(row, true);

        this.fireRowSelectEvent(rowMeta.key, 'contextMenu', fnShowMenu);

        if (this.cfg.disabledTextSelection) {
            PrimeFaces.clearSelection();
        }

        return this.hasBehavior('contextMenu');
    }
}
```

**Comment by mihaiDumea** [comment]
Yes, is working. As I already tested it.
`PrimeFaces.widget.DataTable.prototype._onRowRightClick = PrimeFaces.widget.DataTable.prototype.onRowRightClick;
PrimeFaces.widget.DataTable.prototype.onRowRightClick = function (event, rowElement, cmSelMode, fnShowMenu) {
    this._onRowRightClick(event, rowElement, cmSelMode, fnShowMenu);
    return this.hasBehavior('contextMenu');
}`

**Comment by melloware** [comment]
Ok I will fix!  Thanks for reporting.

**Comment by melloware** [comment]
Please review the PR I just submitted.

**Comment by markusg80** [comment]
This Bug is still present on PF 11.0.6. Workaround with Monkeypatch works. When you plan to merge this to 11 version?

**Comment by melloware** [comment]
@markusg80 no plans unless you have PRO support?  See https://github.com/primefaces/primefaces#community--elite--pro
