### ISSUE TITLE
Chart.js: CartesianLinearTicks.beginAtZero is ignored

### ISSUE THREAD

**Issue by maruTA-bis5** [primefaces/primefaces#8389]
**Describe the defect**
Chart axes always begin at zero even if set false to `CartesianLinearTicks.beginAtZero`.

**Reproducer**
https://github.com/maruTA-bis5/primefaces-test/tree/chart-ticks

**Environment:**
 - PF Version: _11.0.0, master(1a0b83b5819d5097278ea4924dd60bbe3dcf4804)_
 - PF Theme: _Saga_
 - JSF + version: _MyFaces 2.3.9_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to 'http://127.0.0.1:8080/primefaces-test/test.xhtml'
    - Y-axes begins zero though `CartesianLinearTicks.beginAtZero` is false.

**Expected behavior**
Axes begin at zero when `CartesianLinearTicks.beginAtZero` is true. Otherwise, the beginning of the axes should be adjusted automatically.

**Example XHTML**
```html
<h:form id="frmTest">
            <p:barChart widgetVar="chart" model="#{testView.barModel}" style="width: 100%; height: 500px;" />

            <div style="display:flex; justify-content: center;">
                <p:outputLabel for="@next" value="beginAtZero(Y-axes)" />
                <p:toggleSwitch value="#{testView.beginAtZero}"/>
                <p:commandButton value="Refresh" action="#{testView.init}" process="@this @previous" update="@form" />
            </div>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private boolean beginAtZero;

    @PostConstruct
    public void init() {
        createBarModel();
        barModel.setExtender("window.chartExtender");
    }

    private BarChartModel barModel;

    private void createBarModel() {
        // same as showcase except ticks.setBeginAtZero(this.beginAtZero)
    }
}
```

**Comment by melloware** [comment]
can you check whether this is a ChartsJS bug or this property name might have changed in a newer ChartsJS?

**Comment by melloware** [comment]
looks like it might have changed in ChartsJS 3 from 2 see: https://stackoverflow.com/a/68037674/502366

**Comment by maruTA-bis5** [comment]
Yes, the `beginAtZero` property location changed in ChartJS 3.

When setup `org.primefaces.model.charts.axes.cartesian.CartesianScales` such like this,
```java
        CartesianScales scales = new CartesianScales();
        CartesianLinearAxes axes = new CartesianLinearAxes();
        CartesianLinearTicks ticks = new CartesianLinearTicks();
        ticks.setBeginAtZero(true);
        axes.setTicks(ticks);
        scales.addXAxesData(axes);
```
`ChartRenderer#encodeScales` writes `scales`option these format:
```
"scales":{"x":{"offset":false,"stacked":false,"ticks":{"autoSkip":true,"mirror":false,"beginAtZero":true}}}
```
(I used [this code](https://github.com/maruTA-bis5/primefaces-test/blob/chart-ticks/src/test/java/org/primefaces/CartesianLinearAxesEncodeTest.java) to check the written scales option.)

`beginAtZero` must put onto under `scales.x` for ChartJS 3, but on `scales.x.ticks` now.

**Comment by melloware** [comment]
Will fix!

**Comment by melloware** [comment]
Thanks for reporting please review my PR!
