### ISSUE TITLE
DataTable: add reflection based LazyDataModel, similar to JpaLazyDataModel

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8395]
Currently we have 2 possible solutions (and maybe more?) to use a DataTable:
1) value binding to a `List<MyPojo>`
2) value binding to a `LazyDataModel`

in 1) sorting and filtering is done via our SortFeature+FilterFeature, whereas in 2) its done in the LazyDataModel itself

There are some benefits with a LazyDataModel, compared to the old/non-lazy way:
- the model handels filter/sort like in LazyDataModel (1 place to filter/sort, doesnt matter if lazy or not)
- it allows to apply filters via lambda
- it "forces" to uses a lamba to get the list of data, which will be filtered afterwards. This could to lead to better practice, where the user doesnt store the list of data in a ViewScoped bean
- its a performance boost as done via reflection instead of restoring states, rowindex, loop components, create/apply EL

What we need to discuss in future is:
Should we force people to use a LazyDataModel when filtering and sorting is activated?
Using Jpa or ReflectionLazyDataModel definitily leads to a better performance (anyonse interessted in creating a small benchamark?) and big lists will be avoided in ViewState.

**Comment by tandraschko** [comment]
WDYT about @Rapster? should we provide something or even replace our current Sort/FilterFeature with something like this? DataTable must wrap a value-binding with a `List<MyPojo>` with this new model of course.

In theory the code MUST be faster and cleaner with this. We just need a good place to cache the PropertyDescirptors.

**Comment by tandraschko** [comment]
cc @christophs78 @melloware

**Comment by melloware** [comment]
I like where you are going with it!

**Comment by Rapster** [comment]
> WDYT about @Rapster? should we provide something or even replace our current Sort/FilterFeature with something like this? DataTable must wrap a value-binding with a List<MyPojo> with this new model of course

I think it definitely worth to try and see how far you can go with this 😉 Please make a PR so we can follow your progress

**Comment by christophs78** [comment]
Sound´s interresting.
This would make `filteredValue` obsolet? 

Thinking about implications of this:
- no more issues issues because `filteredValue` is not updated correct (good)
- people currently using `filteredValue` will need to rework (neutral, probably minor usage)
- we´ll aply filter/sort on each pagination-event (negativ performance-impact for datasources with a larger amount of datasets?)

**Comment by jepsar** [comment]
I use a property for a global filter (search query string) in my lazy model, as well as a two maps of properties of columns of which I need a **sum** or a **count**. Support in the lazy model for a certain operation on certain columns would be a nice addition (maybe needs a different ticket).

**Comment by tandraschko** [comment]
@christophs78 no, that would not change `filteredValue` behavior at all but we have to rework it in general
currently `filteredValue` is only used when !lazy - and its currently also optional, its just a store, where the user can receive the filtered list, which will also be used to restore it; maybe we should use it write-only anyway
and it should also work for lazy

**Comment by tandraschko** [comment]
so in best case, we filter once per request, for each request the datatable must be rendered 
and this will be faster with this model-based-approach
the current filter and sort-feature always loops the DataTable, do some state changes like setRowIndex, evaluate EL expression and so on

**Comment by christophs78** [comment]
@tandraschko  - i agree to you.
we just should avoid a 10.0.0 like mess. but we are in a better position this time.
i also agree to @Rapster this should be done via PR.

**Comment by Rapster** [comment]
`PropertyUtilsBean` and `DefaultResolver` from beanutils could be a good source of inspiration for handling propertydescriptors.

**Comment by fcorneli** [comment]
Why not go _all the way_ with the reflection? :)
https://github.com/e-Contract/jsf-crud

**Comment by tandraschko** [comment]
update the code now
the PD cache should propably go into PrimeApplication
i wont invest time for now to try to replace the SortFeature/FilterFeature but i think its a good idea for the future

**Comment by djmj** [comment]
@Rapster 

> `PropertyUtilsBean` and `DefaultResolver` from beanutils could be a good source of inspiration for handling propertydescriptors.

Yes _PropertyUtils.getPropertyType(...)_  and _PropertyUtils.getProperty(...)_ also support nested properties. Depending on context also JSF _ValueExpression.getType(...)_ is a possibility.

@tandraschko 

I like the idea to reduce HTML markup and i was using something similar in a generic _ByPropertyConverter_ to use for local autocomplete where data was eagerly loaded in bean so for 95% we use this converter and a "remote lazy" version for autocompletes. 

The JSF built in _coerceToType(...)_ method is great to convert to selected target types. In the clean function i was checking conversion options like _ignoreCase_ or _normalizeSpace_. In my _Converter_ simple _equals_ is enough but using and casting to generic _Comparable_ to support _BigDecimal_ (where equal does not works) with respect to _SortMeta / FilterMeta_ could also be an idea.

We are using  _coerceToType(...)_ for remote _LazyDataModels_ to convert the submitted _String_ from _FilterMeta_ to the target type to further use in a generic Hibernate Criteria. This covers 95% of our use cases generic and we never need to cast a submitted _String_ to its target type manually or use custom filter facet with converter.

	@Override
	public T getAsChangedObject(final FacesContext context, final UIComponent component, final String value)
	{
		T result = null;

		if (StringUtils.isNotBlank(value))
		{
			Class<?> propertyType = null;
			Object typedValue = null;

			try
			{
				final ExpressionFactory expFactory = context.getApplication().getExpressionFactory();

				// iterate data entities
				for (final T entity : this.entities)
				{
					// retrieve type of property
					if (propertyType == null)
					{
						propertyType = PropertyUtils.getPropertyType(entity, this.propertyName);

						// coerce only necessary if not assignable
						if (!propertyType.isAssignableFrom(value.getClass()))
							typedValue = expFactory.coerceToType(value, propertyType);
						else
							typedValue = value;

						// clean value for comparison
						typedValue = this.cleanValue(typedValue);
					}

					// get property from entity
					Object entityValue = PropertyUtils.getProperty(entity, this.propertyName);

					// clean value for comparison
					entityValue = this.cleanValue(entityValue);

					// compare
					if (typedValue.equals(entityValue))
					{
						result = entity;
						break;
					}
				}
			}
			catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException e)
			{
				FacesMessageUtils.addMessage(context, e);
			}
		}

		return result;
	}

**Wildcard %**

Maybe consider allowing a wildcard placeholder '%' for _String_ comparison like in SQL also in memory local. 
With our generic lazy Hibernate Criteria builder we always search with operator _STARTS_WITH_ which converts to a _LIKE_ in SQL and the user can simply decide if he wants to select _contains_ by entering queries such as '%foo' or 'foo%bar%test'.

Right now our users are sometimes confused when its not supported cause we are not using a _LazyDataModel_.

**Comment by tandraschko** [comment]
Actually i would like to contribute this type of LazyDataModel to PF and also write a example + doc
i just wonder, what is a perfect example for it and if we should support it?

i mean, the benefits are clear:
- the model handels filter/sort like in LazyDataModel
- it allows to apply filters via lambda
- it "forces" to uses a lamba to get the list of data, which will be filtered afterwards. This could to lead to better practice, where the user doesnt store the list of data in a ViewScoped bean
- its a performance boost as done via reflection instead of restoring states, rowindex, loop components, create/apply EL 

but we provide another way of using the DataTable
maybe its to much if we dont plan to remove FilterFeature/SortFeature in future

**Comment by melloware** [comment]
I like it you could call it ReflectionLazyDataModel and add it ?  

Can you add it without disturbing the Sort/FilterFeature.

**Comment by christophs78** [comment]
Needs to be done one a feature-branch + PR.
Curious to see whether it works out.

**Comment by tandraschko** [comment]
Commited the ReflectionDataModel now as we use it in some projects already, also added some tests
will provide a small docu enhancement tomorrow + move the cache to PrimeApplication

**Comment by Rapster** [comment]
I'd like to review this but I need to know if you're done with it? If I remember well, the whole idea is to replace `SortFeature` & `FilterFeature` with the ReflectionDataModel, so I suppose what you already committed is an initial step to this whole idea or i'm missing something? Will people want to use this new DataModel? The way I understood, was this new model will be used internally in PF for practical reasons

**Comment by tandraschko** [comment]
yep, i'm roughly done with it
Currently it's just the brother of JpaLazyDataModel. Our usecases are webservices, which doesnt support filtering or sorting. So we need to call the webservice, filter/sort via reflection. 

We dont need to replace anything, it's just an idea for the future and has some benefits.

**Comment by tandraschko** [comment]
JFYI, simple case normal list vs ReflectionLazyDataModel sorting 10000 entries:
1) simple list: ~320ms response time
2) reflectionLazyDataModel: ~230ms response time

not used a profiler but it seems saving not only a few CPU

**Comment by melloware** [comment]
This sounds good to me!

**Comment by tandraschko** [comment]
added docs; closing it for now

**Comment by tandraschko** [comment]
even reworked the getting started a bit and added new `data binding` section

**Comment by tandraschko** [comment]
@melloware @Rapster please review

**Comment by melloware** [comment]
LGTM.  And you are probably right about this could be done in a lot more places.

**Comment by Rapster** [comment]
I'm currently reviewing/refactoring/polishing the new lazy models, I'll submit a draft PR soon and would like to see it for 14
