### ISSUE TITLE
Spinner Wrong aria-attribute

### ISSUE THREAD

**Issue by csalmhof** [primefaces/primefaces#8398]
**Describe the defect**
Due to the change from https://github.com/primefaces/primefaces/issues/8396 the role of spinner is now `spinbutton`. In spinner also the aria-property `aria-multiline` is added, which is not supported by the role `spinbutton`. (See https://www.w3.org/TR/wai-aria-1.1/#spinbutton or https://www.w3.org/TR/wai-aria-1.2/#spinbutton)

**Reproducer**
Problem is appearing everytime spinner is used with the actual snapshot (due to the fix from https://github.com/primefaces/primefaces/issues/8396)

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme: _ALL_
 - Affected browsers: _ALL

**To Reproduce**
1. Using a spinner anywhere

**Expected behavior**
The aria-property 'aria-multiline should not be added

**Example XHTML**
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
        <h:outputScript name="test.js" />
    </h:head>
    <h:body>

        <p:spinner/>

    </h:body>
</html>
```

**Example Bean**
```java
not needed
```

**Comment by melloware** [comment]
Thanks for the report and the PR!
