### ISSUE TITLE
DataTable: RequestScoped LazyDataModel does not process inputs

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8404]

**Comment by tandraschko** [comment]
@melloware @christophs78 could you do me a favor and check why this test throws a org.openqa.selenium.StaleElementReferenceException? i tried it 30 min now to understand but already to late for today

**Comment by melloware** [comment]
Yep will see if I can try it today

**Comment by melloware** [comment]
OK I am a little stumped on this one as well.  It calls the `clear` successfully but right after that the input is stale when calling `sendKeys`.
