### ISSUE TITLE
DataTable: manual assigning selection attr does not set internal selection state in DataTable component

### ISSUE THREAD

**Issue by marw1tt** [primefaces/primefaces#8406]
**Describe the defect**
If I use a DataTable with "multiViewState=true", I can not set the selection using a Command Component like it is described within the Primefaces documentation (see [here](https://primefaces.github.io/primefaces/10_0_0/#/components/datatable?id=single-selection-with-a-command-component)). 

If I set the selection like that, the value in the data model is updated but not populated to the DataTableState. So when "DataTable.restoreMultiViewState()" is called afterwards the old selection is set, highlighted and overrides also the value within the data model. 

This does not happen if the selection is set by clicking the target row because then the "SelectionFeature.decode(FacesContext context, DataTable table)" is called which updates the DataTableState too. 

**Reproducer**
This can be reproduced by creating the case like it is in the linked showcase (see description) but you need to set the "multiViewState" attribute to "true", the "selectionMode" to "single" and the  "disabledSelection" to "false".  It can be reproduced with prime faces 10 and 11. 

This would look like that:

`<p:dataTable var="car" value="#{carBean.cars}" selectionMode="single" multiViewState="true" disabledSelection="false">
    <p:column>
        <p:commandButton value="Select">
            <f:setPropertyActionListener value="#{car}" target="#{carBean.selectedCar}" />
        </p:commandButton>
    </p:column>
    ...columns
</p:dataTable>`

**Environment:**
 - PF Version: _11.0.1_
 - PF Theme: _Diamond_
 - JSF + version: _MyFaces 2.3.8_
 - Affected browsers: _ALL_

**Expected behavior**
My expected behavior would be like that, it does not matter if I select the row by button or by clicking on the target row itself.

**Comment by Rapster** [comment]
> Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your reproducer here. **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub. Please test with that before reporting a bug that may already be fixed.

**Comment by marw1tt** [comment]
I made a simple example where the error can be reproduced. First select the second row (Entry_2) by clicking on the row itself, then switch the page with the paginator and then switch back. Now select Entry_3 by clicking the "Select" button. It does not work. This works fine if I set the "multiViewState" attribute to "false". The example is based on your repo "https://github.com/primefaces/primefaces-test.git". If I use your current master-SNAPSHOT then I got errors because of duplicate fragment names. 

[pf_test_1.zip](https://github.com/primefaces/primefaces/files/8024963/pf_test_1.zip)

**Comment by tandraschko** [comment]
i switched to enhancement as i think its a bit different then the normal selection.
if you use the normal selection, the selection state itself is handled inside the DataTable state and multiViewState. in this case, you just set the POJO selected in the backend.

**Comment by marw1tt** [comment]
Indeed, is there a way  to make this work again (worked with PF 8)? I have seen this mechanic on the documentation page from PrimeFaces for the dataTable component.

**Comment by tandraschko** [comment]
could you create a primefaces-test project with PF8, which shows that it worked?
also you can maybe debug a bit, when its added to the multiviewstate exactly

**Comment by marw1tt** [comment]
I will do that, but I guess it will take some time before I find time to do this. But beside from that, do you agree that it is reasonable  that there is a way to select a row in the table programmatically and not only by clicking?

**Comment by tandraschko** [comment]
yep, there already is: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java#L1155

**Comment by marw1tt** [comment]
How can I access this if I want to trigger that from a button? Is there somewhere a documentation for that case or anything? Sorry I didn't find something for that and I am gonna debug that case tomorrow I guess.

**Comment by tandraschko** [comment]
you can use findComponent API to get the DataTable instance

**Comment by marw1tt** [comment]
I found the difference. It worked with PF 8 because there is a difference how the selection within the DataTableState is updated. 
If PF 8 within the SelectionFeature class is the method "public void decode(FacesContext context, DataTable table) ". There is a code block that updates the selection of the DataTableState. 

`
 if (table.isMultiViewState()) {
            DataTableState ts = table.getMultiViewState(true);
            table.findSelectedRowKeys();
            ts.setRowKeys(table.getSelectedRowKeys());
       }
`
To restore the selection the Method "table.findSelectedRowKeys()" is called. That method updates the table selection where the value of "getStateHelper().eval(PropertyKeys.selection, null)" is used with highest prio. Which returns the correct selection. 

In PF 11 the code within the SelectionFeature looks like follow:
`
if (table.isMultiViewState()) {
            DataTableState ts = table.getMultiViewState(true);
            ts.setSelectedRowKeys(table.getSelectedRowKeys());
        }
`

That returns the value of "ComponentUtils.eval(getStateHelper(), InternalPropertyKeys.selectedRowKeys, Collections::emptySet);" and set it as selected row keys within the DataTableState. At this point the current "real" selection should be retrieved like it was within the method "table.findSelectedRowKeys();" where the "real" selection is used if available and the value of "table.getSelectedRowKeys()" is only used as fallback.

**Comment by tandraschko** [comment]
@Rapster can you check this pls?

**Comment by Rapster** [comment]
I'll have a look this week-end

**Comment by marw1tt** [comment]
That was my finding regarding the initial selection by clicking the selection button. It seems that there is more to it, because if you want to change the selection afterwards there is also the problem that the old (wrong) selection is set when DataTable.restoreMultiViewState() is called. Here should be used also the "real" selection prior to the selectedRowKeys from the DataTableState. I hope you find a solution to this. Thank you very much.

**Comment by marw1tt** [comment]
Are there any news to this? I thought about it and my conclusion is, that the selection should be restored using the following priority:

1. Use Value from Model (value binding for the selection)
2. Use current selection, if there is any
3. Restore selection from DataTableState

**Comment by marw1tt** [comment]
Are there any news on this topic?

**Comment by Rapster** [comment]
Sorry I was supposed to look at it, but got busy and don't have time right now to investigate

**Comment by tandraschko** [comment]
verified, here is a cleaner sample:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
    </h:head>
    <h:body>
        <h:form id="form">

            <p:dataTable id="dt" value="#{dtBasicView.cars}" var="car"
                         multiViewState="true" rows="4" paginator="true"
                         rowKey="#{car.number}" selection="#{dtBasicView.selectedCar}"
                         selectionMode="single" lazy="false">

                <p:ajax event="rowSelect" process="@this" />
                
                <p:column headerText="Number">
                    #{car.number}
                    <p:commandButton value="Select" process="@this" update="@form">
                        <f:setPropertyActionListener value="#{car}" target="#{dtBasicView.selectedCar}" />
                    </p:commandButton>
                </p:column>

                <p:column headerText="Car Name">
                    #{car.name}
                </p:column>

            </p:dataTable>

        </h:form>
    </h:body>
</html>
```


```package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;

@Named("dtBasicView")
@ViewScoped
@Getter
@Setter
public class TestView implements Serializable {

    private List<Car> cars;
    private Car selectedCar;

    @PostConstruct
    public void init() {
        cars = new ArrayList<>();
        cars.add(new Car(1, "Entry_1"));
        cars.add(new Car(2, "Entry_2"));
        cars.add(new Car(3, "Entry_3"));
        cars.add(new Car(4, "Entry_4"));
        cars.add(new Car(5, "Entry_5"));
        cars.add(new Car(6, "Entry_6"));
        cars.add(new Car(7, "Entry_7"));
        cars.add(new Car(8, "Entry_8"));
        cars.add(new Car(9, "Entry_9"));
    }

    @Getter
    @Setter
    public static class Car implements Serializable {

        private Integer number;
        private String name;

        public Car() {
        }

        public Car(Integer number , String name ) {
            this.number = number;
            this.name = name;
        }
    }
}

```

**Comment by marw1tt** [comment]
Hi there, are here any new to this problem?

**Comment by tandraschko** [comment]
nope, but i added a integration test for you now, so you can work on a PR to fix this issue

you can run it via `mvn verify -Pintegration-tests,parallel-execution,mojarra-2.3 -Dit.test=DataTable035Test` after removing the `@Disabled`

**Comment by tandraschko** [comment]
i found the reason why this happens
in 8.0 the `selection` attr in the bean is not set from MultiViewState
we introduced this later, cant find a ticket now (DataTable#updateSelectionWithMVS)

so what happens now:
- `setPropertyActionListener` / `setSelectedCar` is invoked with the right instance from the button
- `DataTable#preRender` invokes `restoreMultiViewState` and therefore `setSelectedCar` is called with the old selection
- later `DataTable#preRender` also invokes `SelectionFeature#decodeSelectionRowKeys`, which saves the selection from the bean into the internal state and MVS

so in theory it should work when `SelectionFeature#decodeSelectionRowKey` is called before restoreMultiViewState, too
but not sure if this breaks another case

the question is: should MVS even restore the `selection` in the bean? Can anyone try to find the issue on github?

**Comment by tandraschko** [comment]
also related to #8275

**Comment by melloware** [comment]
The only thing I can find is https://github.com/primefaces/primefaces/issues/6575 which is where this original major refactoring occurred

**Comment by tandraschko** [comment]
i think selection from MVS should not be restored into the bean when selection is already set in the bean, right?

**Comment by melloware** [comment]
yes i don't think so either

**Comment by Rapster** [comment]
Same, though we have to make it clear it's no longer supported since I think that's how MVS was originally introduced

**Comment by tandraschko** [comment]
for now, i will just skip restore MVS on postback for selection
in general it should be skipped for all MVS but i dont like to break something now

**Comment by tandraschko** [comment]
will leave it as it is for now, we dont have enough tests for MVS

**Comment by marw1tt** [comment]
Hi, I want to test the solution for this bug with PrimeFaces 12. Can you tell me when the PrimeFaces Test Project will be updated, so it can be run with PrimeFaces 12?

**Comment by melloware** [comment]
You can do it now just run "mvn clean install" on PF to build 12.0.0-SNAPSHOT then change the PF Test project Pom.xml to point to 12.0.0-SNAPSHOT

**Comment by marw1tt** [comment]
OK, thank you!

**Comment by gbrinkmann** [comment]
Just stumbled upon this thread while having problems setting a selection object programmatically and not seeing it selected in the dataTable in PF 11.x (must use an 11 version because of Liferay Faces).

My solution is

`<p:commandButton ... oncomplete="PF('myDataTableWidgetVar').selectRow(0, false)" ...`

My commandButton resides outside of the dataTable.
The 0 is the row index, so if you have your row index for a row button this might work.

https://primefaces.github.io/primefaces/11_0_0/#/components/datatable?id=datatable

Hint came from a 12 years old PF forum post https://forum.primefaces.org/viewtopic.php?t=23031

Sorry if this is not helpful spam, have a nice day :-)
