### ISSUE TITLE
Dialog Framework: Flash is empty on opened dialog

### ISSUE THREAD

**Issue by macbl** [primefaces/primefaces#8409]
The dialog framework's flash examples are not working in Tomee (8.0.9), JDK 17. Flash is empty on the loaded dialog. I don't get any error messages or other log output. Debugging shows that valueFromFlash is empty on the DFLevel1View bean.

**Comment by melloware** [comment]
Please provide a Reproducer. we can't debug your issue without one.

**Comment by macbl** [comment]
The reproducer would be the primefaces showcases at:
[https://github.com/primefaces/primefaces/blob/bbd83b581704a0d59476765c6f7d4f9a77bf7f50/primefaces-showcase/src/main/webapp/ui/df/data.xhtml](https://github.com/primefaces/primefaces/blob/master/primefaces-showcase/src/main/java/org/primefaces/showcase/view/df/DFLevel1View.java )
with the corresponding XHTML files:
[https://github.com/primefaces/primefaces/blob/bbd83b581704a0d59476765c6f7d4f9a77bf7f50/primefaces-showcase/src/main/webapp/ui/df/data.xhtml](https://github.com/primefaces/primefaces/blob/bbd83b581704a0d59476765c6f7d4f9a77bf7f50/primefaces-showcase/src/main/webapp/ui/df/data.xhtml)

Anyhow, I just found a side [note in the Dialog Framework Docs](https://primefaces.github.io/primefaces/11_0_0/#/core/dialogframework) that flash is supported from Mojarra 2.3.17 upwards. However, TomEE 8.0.9 PLUME is running with 2.3.15. So this would be the explanation.

**Comment by melloware** [comment]
@macbl thanks for reporting back.  I guess its good it was documented 😄
