### ISSUE TITLE
DataTable: clarify / rename selection attributes

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8416]
Currently we have following attributes to define selection and modes:

**p:dataTable**
`selectionMode=single | multiple` - defines the selection mode, without rendering checkbox/radiobuttons
`rowSelectMode=new | add | checkbox` - defines how selection should work when clicking on the row itself; new = unselect all rows before; add = just add the new to the selection; checkbox = disables selection on the row itself
`disabledSelection=EL` - disables the current row for selection

**p:column**
`selectionMode=single | multiple` - defines the selection mode, with rendering a checkbox or radiobuttion; rows are still selectable
`selectRow=true | false` - disables the selection in content of the current column

**Comment by tandraschko** [comment]
to also disallow row-selection when p:column has `selectionMode=single`, i would rename `rowSelectMode` `checkbox` to `none`: https://github.com/primefaces/primefaces/issues/8417

**Comment by melloware** [comment]
cc @FlipWarthog as he just dealt with this on his project :smile:

**Comment by tandraschko** [comment]
what about `disabledSelection` and `selectRow`? should we give them better names?
also should we rename `rowSelectMode` to `rowSelectionMode`, to better align it with `selectionMode`?

**Comment by melloware** [comment]
Yep I think we can rename some of these personally i like when all related props start with the same word like `selection` so I don't have to go fishing for properties.  so `selectionMode`, `selectionRowMode`, `selectionDisabled` etc?

**Comment by FlipWarthog** [comment]
I think I agree with the naming consistency but I definitely need to look at my tables where I dealt with this so I can remember what pain-points I had. I think there's definitely room for improvement with the props that attributes that relate to clicking the row itself. Also how these relate to meta keys, e.g. holding Ctrl and clicking rows.

**Comment by FlipWarthog** [comment]
@melloware I remember my main issue: `rowSelector`. That's what I used to disable row selection by clicking the row. But I had to dive through the .js to see how it's used and reverse engineer my way to `rowSelector="ui-selection-column"`

From the docs:
> "Client side check if rowclick triggered row click event not a clickable element in row content."

**Comment by Rapster** [comment]
+1 for the prefix, and since I like to keep things short and sweet, I would personnally  go with `select` prefix

I always miss something when I have to set up this feature since selection can be configured whether on DataTable or Column. I remember taking few notes long time back when I started refactoring DataTable, but as I lost them... Here are the thoughts that come on top my head:
- `DataTable#selectMode`: `single`, multiple`
- `Column#selection`: `true`|`false`, just there to identify the selection column

That way, it's pretty easy and straightforward to configure selection since essentially everything is on `DataTable`. Am I missing something?

**Comment by stolp** [comment]
As always I like to first raise my voice for keeping backwards compatibility as high as possible.

Then again, I do see the merits of a consistent naming strategy for attributes here.

My first hunch was thinking it may make sense to use the 'select' prefix for attributes related to the selection process and a 'selection' prefix for attributes related to the selected items themselves. Just an idea that came to mind.

Whatever you decide, *please* choose a renaming scheme where a search/replace approach is simple and unique for users who like to update to PF 12.

**Comment by tandraschko** [comment]
@Rapster what does `meta` mean?

i general we have 4 modes: single selection via row click (p:dataTable), single selection via radio (p:column), multi via row (p:dataTable), multi via checkbox (p:column)

**Comment by Rapster** [comment]
Meta as in metaKey (just reused keyword from documentation). Actually, can't we simply remove Column#selectionMode? The presence of a flag like Column#selection as a Boolean and DataTable#selectionMode to decide whether it's a radio button or a checkbox should be good enough no?

**Comment by tandraschko** [comment]
so you mean
dataTable#selectionMode=multiple is selectable via row click
if you add
column selection=true, a checkbox shows in this column?

and rowSelectMode=none could then disable row click?

**Comment by Rapster** [comment]
Yes and btw, is here any difference between DataTable#rowSelectMode none and Column#selectRow?

**Comment by mertsincan** [comment]
Maybe selectionMode could be like in primereact
https://www.primefaces.org/primereact/datatable/selection/
```
selectionMode= single | multiple | checkbox | radiobutton
```

**Comment by Rapster** [comment]
IMO, it should look like this:

DataTable
- `selection `(all good)
- `selectionMode`: single, multiple (automatically detects it like `DataTable#lazy`)
- `selectionRowMode`=new, add (ex rowSelectMode) There is no `none`, use `DataTable#selectionDisabled` then
- `selectionDisabled` (ex `disabledSelection`) or maybe: selectionRowDisabled as it's per row
- `selectionTextDisabled `(ex `disabledTextSelection`)
- `selectionPageOnly `(all good)

Column
- `selectionRow`: ex `selectRow`
- `selection`: true, false (ex `selectionMode `, we have already that info on DataTable, just need a flag to identify the column that will contain the checkbox/radiobutton)

**Comment by Rapster** [comment]
@tandraschko I can take a look at this one, just need feedbacks from @primefaces/primefaces-committers   about the last attribute I mentionned (e.g `selectionBox`, name can be discussed)

**Comment by FlipWarthog** [comment]
@Rapster Would it be silly to match the pattern of `rowToggler` for what you've got as the `selectionBox` attribute of `Column`? E.g.

```xml
<p:column style="width:2rem">
    <p:rowSelector />
</p:column>
```

**Comment by Rapster** [comment]
It would be overkill to use a new component, just to know whether or not the column is the selection column. If the "select all" column had his own bunch of attributes (like row toggler), having a new component could make sense, but here not so much

**Comment by tandraschko** [comment]
in general +1, just need to go through the comments next week again

**Comment by FlipWarthog** [comment]
> It would be overkill to use a new component, just to know whether or not the column is the selection column. If the "select all" column had his own bunch of attributes (like row toggler), having a new component could make sense, but here not so much

I see what you're saying from an impl standpoint, I'm thinking from a usability standpoint and having similar concepts be used similarly. For the attributes point, are you mixing rowToggler with something else like columnToggler? Looks like rowToggler just kinda exists with not much else to it: https://primefaces.github.io/primefaces/12_0_0/#/components/rowtoggler

**Comment by Rapster** [comment]
I see what you mean, the example you have in mind is actually `<p:autoUpdate />` (attr autoUpdate became a component). `RowToggler` has his own set of attributes, the doc just doesn't show them unfortunately. Back to selection, I still don't see what we would gain by having something like your example, maybe you can elaborate 😉

**Comment by melloware** [comment]
Sounds like we need to update the docs to have the RowToggler props.

**Comment by FlipWarthog** [comment]
@Rapster Honestly, the initial driver was avoiding trying to come up with a better name than `selectionBox`. 😅  I should have a live table in one of my applications that uses both selection and expansion, so I think that's where I'm coming from re: consistent usage (which may be way off base).

I.e. I have a checkbox column for selecting rows and an expansion column for expanding, I would have something like:
```xml
<p:column>
    <p:rowSelector />
</p:column>

<p:column>
    <p:rowToggler />
</p:column>

<p:rowExpansion>
  <!-- Content -->
</p:rowExpansion>
```
vs. 
```xml
<p:column selectionBox="true" />

<p:column>
    <p:rowToggler />
</p:column>

<p:rowExpansion>
  <!-- Content -->
</p:rowExpansion>
```
But in the end, I don't really mind either way and can understand if implementing this is overkill for what I'm describing. Hopefully that makes sense?

**Comment by Rapster** [comment]
I hear you, but so far simply renaming the attribute is good enough (and yet still a breaking change, but not that hard to fix). Besides the reasons I already gave you, having a new component requires an extra traversal of the "column node", which is obviously not expensive, but if you save all this cheap extra traversal you save a lot at the end of the day (just like money 😅 )

**Comment by Rapster** [comment]
Should we make this backward compatible? 😅
