### ISSUE TITLE
ArrayIndexOutOfBoundsException when use PF datatable exporter programmatically

### ISSUE THREAD

**Issue by TEAMS-HRM** [primefaces/primefaces#8419]
Hi, 
Our system is generating the pages programmatically, we used to use datatable exporter in PFExt, but when we upgraded the versions we moved to use the one in PF, and now we got the below exception.

Mojarra JSF 2.3.14 (Specification 2.3)
Primefaces 11.0.0
Weblogic 14.1.1.0.0
Java 1.8

I have attached a very simple project which generate datatable and exporter, when we tried to use the exporter we got the below exception. Thanks

```html

<h:form id="mainForm" enctype="multipart/form-data">
<pe:layout id="mainLayout" fullPage="true" widgetVar="mainLayout">
	<pe:layoutPane id="otbo-main" resizable="false" position="center" >
		<h:panelGroup id="applicationRoot" binding="#{rootBean.rootApp}" />
	</pe:layoutPane>
</pe:layout>
</h:form>

```

```java
//create dataTable
	private void initDataTable() {
		DataTable dataTable = (DataTable) getApplication().createComponent( DataTable.COMPONENT_TYPE);
		dataTable.setId("myDataTable");
		
		dataTable.setVar( "row" );
		dataTable.setLazy( false );
		dataTable.setResizableColumns( true );
		dataTable.setReflow( true );
		
		dataTable.setRowKey("name");
		
		createExporters( dataTable );
		
		addColumn("Name", "name", dataTable);
		addColumn("City", "city", dataTable);
		addColumn("Age", "age", dataTable);
		
		dataTable.setValueExpression( "value", createValueExpression( "#{rootBean.data}", List.class ));
		
		addChild(rootApp, dataTable);
		
		
	}
	
	//create exporter
	private void createExporters( DataTable dataTable ) {
		CommandLink link = createComponent( CommandLink.COMPONENT_TYPE );
		link.setValue("Export table");
		
		DataExporter exporter = new DataExporter( createValueExpression( dataTable.getId(), String.class ),
				createValueExpression( "xlsx", String.class ), createValueExpression( "excelOut", String.class ), 
				null, null,	null, null, null, null, null);
		link.addActionListener( exporter );

		HtmlPanelGroup group = createComponent( HtmlPanelGroup.COMPONENT_TYPE );
		addChild( group, link );

		addChild(rootApp, group);
	}

```

<09-Feb-2022 11:21:26,012 o'clock GMT> <Error> <javax.enterprise.resource.webcontainer.jsf.context> <BEA-000000> <java.lang.ArrayIndexOutOfBoundsException: 10
	at javax.faces.component.UIComponentBase.restoreChildState(UIComponentBase.java:3418)
	at javax.faces.component.UIComponentBase.processRestoreState(UIComponentBase.java:1026)
	at javax.faces.component.UIComponentBase.restoreFacetsState(UIComponentBase.java:3445)
	at javax.faces.component.UIComponentBase.processRestoreState(UIComponentBase.java:1029)
	at javax.faces.component.UIViewRoot.processRestoreState(UIViewRoot.java:932)

[PrimefacesTester.zip](https://github.com/primefaces/primefaces/files/8032430/PrimefacesTester.zip)

**Comment by melloware** [comment]
Your reproducer is not runnable.  

Please  provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
And just as a note your error looks an awful lot like this Mojarra error: https://github.com/eclipse-ee4j/mojarra/issues/4936

**Comment by TEAMS-HRM** [comment]
Please find the executable example running on Jetty, also I found that the exception is only come when I have the below  param in web.xml

<context-param>
    <param-name>javax.faces.PARTIAL_STATE_SAVING</param-name>
    <param-value>false</param-value>
</context-param>

[PrimefacesTester.zip](https://github.com/primefaces/primefaces/files/8041071/PrimefacesTester.zip)

**Comment by melloware** [comment]
When I run `mvn clean jetty:run` it won't start.

**Comment by melloware** [comment]
[pf-8419.zip](https://github.com/primefaces/primefaces/files/8041228/pf-8419.zip)

OK finally got your reproducer working.  Confirmed your bug is Mojarra Bug found here: https://github.com/eclipse-ee4j/mojarra/issues/4936

Not a PrimeFaces issue it was fixed in Mojarr 2.3.17.

**Comment by TEAMS-HRM** [comment]
thanks. I update the JSF implementation to higher version and it worked 

               <dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.faces</artifactId>
			<version>2.3.3.102</version>
		</dependency>

**Comment by melloware** [comment]
Cool I added the workaround label to this ticket thanks for reporting back!
