### ISSUE TITLE
Tooltip: show and hide methods should not execute concurrently

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#8421]
If you move your mouse pointer fast enough, you can end up with no tooltip showing on an element that has one. It's easier to replicate when an element(e.g. CommandButton) with a tooltip has children, and the show and hide events fires for each of them.

It's harder to replicate when you set a hideDelay="10", so that show method manages to cancel the hide timeout.
At least, a check(if the show method is in progress) may be added here: https://github.com/primefaces/primefaces/blob/2e79cbc628fa98885cad4688813fc7e82f6f3a97/primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js#L396

 - PF Version: _11.0.0_
 - Affected browsers: _e.g. ALL_

**Comment by melloware** [comment]
Hmmm its already doing ` if(this.isVisible()) {` so it was visible when it started but this kind of stuff with asynchronous events is tough.    A proposed PR would be welcome.

**Comment by mihaiDumea** [comment]
The actual function that does the work is executed after `this.cfg.hideEffectDuration`.

**Comment by melloware** [comment]
If you have a proposed fix please submit a PR or post it here

**Comment by mihaiDumea** [comment]
I will try to find one. Meanwhile, using hideDelay="10" can be used as an workaround.

**Comment by mihaiDumea** [comment]
Default events name should be changed from mouseover/mouseout to mouseenter/mouseleave, to properly handle elements that have descendants. There is no need for tooltip events to be fired for each descendant.

The requirement of concurrent execution of events, may not be required, as I can't find a reasonable use case for reproducing the issue. If it's not the case, we shouldn't complicate the code.

I'm satisfied with this fix, if it doesn't break anything.

**Comment by mihaiDumea** [comment]
https://github.com/primefaces/primefaces/blob/2e79cbc628fa98885cad4688813fc7e82f6f3a97/primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js#L213
Here, the appended event namespace might be redundant(duplicated).

**Comment by melloware** [comment]
OK post your code here or submit a PR?

**Comment by mihaiDumea** [comment]
```js
this.cfg.showEvent = this.cfg.showEvent ? this.cfg.showEvent + '.tooltip' : 'mouseenter.tooltip';
this.cfg.hideEvent = this.cfg.hideEvent ? this.cfg.hideEvent + '.tooltip' : 'mouseleave.tooltip';
```

**Comment by melloware** [comment]
OK review my PR i made your fixes I agree with them.

**Comment by fcorneli** [comment]
Could this be back-ported to 10? I also noticed this several times within our app.

**Comment by melloware** [comment]
When I get to the office I will put a monkey patch here you can start using today.

**Comment by melloware** [comment]
MonekyPatch 10.0:

```js
if (PrimeFaces.widget.Tooltip) {
    PrimeFaces.widget.Tooltip.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);

        this.cfg.showEvent = this.cfg.showEvent ? this.cfg.showEvent + '.tooltip' : 'mouseenter.tooltip';
        this.cfg.hideEvent = this.cfg.hideEvent ? this.cfg.hideEvent + '.tooltip' : 'mouseleave.tooltip';
        this.cfg.showEffect = this.cfg.showEffect ? this.cfg.showEffect : 'fade';
        this.cfg.hideEffect = this.cfg.hideEffect ? this.cfg.hideEffect : 'fade';
        this.cfg.showDelay = this.cfg.showDelay || 150;
        this.cfg.hideDelay = this.cfg.hideDelay || 0;
        this.cfg.hideEffectDuration = this.cfg.target ? 250 : 1;
        this.cfg.position = this.cfg.position || 'right';
        this.cfg.escape = (this.cfg.escape === undefined) ? true : this.cfg.escape;

        if (this.cfg.target)
            this.bindTarget();
        else
            this.bindGlobal();
    }
};
```
