### ISSUE TITLE
DatePicker: with inline=true in Dialog causes position to be fixed

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8423]
```xhtml
<p:dialog widgetVar="myDialog">
    <p:datePicker inline="true"/>
</p:dialog>
<p:button value="Open" onclick="PF('myDialog').show();return false"/>
```

<img width="479" alt="Screenshot 2022-02-10 at 17 34 18" src="https://user-images.githubusercontent.com/7500178/153452934-95e49434-27d1-4ef6-89c1-473e5cc7c89c.png">

**Comment by jepsar** [comment]
Added here:

https://github.com/primefaces/primefaces/blob/ecebd5073bc80606aa0f067ed262a8417e218246/primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js#L253

https://github.com/primefaces/primefaces/blob/2ef14a099794b94c4ec45fd8baf1f7175d914719/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js#L25

**Comment by jepsar** [comment]
@melloware I've found the cause, but I would not know how to correctly fix this. I don't want to touch the core utils, and resetting fixed after line 253 feels too much as a hack. Do you have any ideas?

**Comment by melloware** [comment]
let me look

**Comment by melloware** [comment]
Ahh so leave the core alone but on line 254 i think you need to add something like...

```js
if (datepicker.isInline) {
   overlay.css('position', 'fixed'); 
}
```

Basically if this is an inline DatePicker we need to treat it special.
