### ISSUE TITLE
5.3 Autocomplete not selecting on mouseSelect in IE 8

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#843]
## Observation in IE 11 developer emulation

This IE 8 issue is a big problem since many companies have intranet restrictions and use Internet Explorer 8.

_Document type / user-agent_

_Edge / MSIE 8_

No suggestions are shown. Error is also visible in showcase.
Video to show it in showcase: https://www.youtube.com/watch?v=a3sTqVzYnOE

_8 / MSIE 8_

Showcase is working. 
In my application selection only works with arrow and enter keys. Mouse is not working.
## Environment

Glassfish 4.1
Mojarra: 2.2.9
PF: 5.3
## Similar

https://code.google.com/p/primefaces/issues/detail?id=7781
https://github.com/primefaces/primefaces/issues/335

In PF 5.2 i just needed a global simple dummy ajax request:
http://forum.primefaces.org/viewtopic.php?f=3&t=42030
## Workaround

Explicitly set compatibility header `X-UA-Compatible` to `IE=8` if user agent is `MSIE 8`.
Update the autocomplete once using dummy ajax request.

In my registration form I update the autocomplete after user inputs his street name (for IE 8 user-agent only).

**Comment by tandraschko** [comment]
Will close it as we dropped support for IE8. See: https://www.primefaces.org/primefaces-6-1-1-released/
