### ISSUE TITLE
DataTable: make lazy attribute optional when value is null

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8436]
With the recent PF 12-Snapshots,  I am getting the following error on some screens that were working for many years:

```
Unable to automatically determine the `lazy` attribute. 
Either define the `lazy` attribute on the component or make sure the `value` attribute doesn't resolve to `null`. clientId: ...
```

Could you please revise the semantics such that no migration is required here:

if no lazy attribute is determined, it is by default lazy="false". finally, if the datatable value is null or an empty collection, the datatable should show nothing.

Thanks in advance.

**Comment by tandraschko** [comment]
Its a warning, not a error and by design
But we should just log it and not throw a exception

**Comment by tuerker** [comment]
The exception causes that the mentioned screens are not working anymore. Thanks.

**Comment by tuerker** [comment]
Dear @tandraschko could please remove the warning which is neither needed nor helpful since the printed clientid is even not the page. I would suggest to replace

```
 if (type == null) {
                LOGGER.warning("Unable to automatically determine the `lazy` attribute, fallback to false. "
                        + "Either define the `lazy` attribute on the component or make sure the `value` attribute doesn't resolve to `null`. "
                        + "clientId: " + this.getClientId());
            }
            else {
                lazy = LazyDataModel.class.isAssignableFrom(type);
            }
```

by 

```
 if (type != null) {
                lazy = LazyDataModel.class.isAssignableFrom(type);
            }
```

This would clearly implement the documented optional attribute semantics where the default is lazy=false.

Many thanks in advance.
