### ISSUE TITLE
Menubar/menu: might execute wrong (not clicked) items

### ISSUE THREAD

**Issue by rabiter** [primefaces/primefaces#8443]
**Describe the defect**
Clicking menu items while the ajax request is still in progress might lead to unexpected results. This might be exactly the case either in slow environment or if the user acts rapidly clicking fast. Please check the attached primefaces-test zip reproducing the problem, it explains the problem in details.

**Reproducer**
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/8064098/primefaces-test-master.zip)

**Environment:**
 - PF Version: any
 - PF Theme: any
 - JSF + version: any
 - Affected browsers: any

**To Reproduce**
There are two examples in the attached app, just follow the instructions.

**Expected behavior**
I'd expect the menu behaving similar to the button component (the reproducer app includes the demonstration with buttons as well)

**The app screenshot giving a short overview**
![image](https://user-images.githubusercontent.com/218450/153948823-679de98b-cd1b-4766-8023-8c500da9e447.png)

**Comment by rabiter** [comment]
Why do not use some random unique ids for menu items? Currently the id looks like "0_1_3", "0_2" etc. In fact such id reflects the item position in the menu hierarchy. And when decoded, this might happen that a wrong item is put to the MenuActionEvent just because occasionally this item replaces the old item in the hierarchy. Like in example 3 above: I click **Close + Refresh**, but get **Close + Edit** because Edit replaced Refresh after executing "close"

**Comment by melloware** [comment]
See this issue: https://github.com/primefaces/primefaces/issues/7072

**Comment by rabiter** [comment]
ok I checked the issue, but still see no problem in using random Ids. I've attached a small patch (3 classes changed, master branch 12.0.0-SNAPSHOT). Would appreciate if somebody have a chance to check it. At least it solves my issue and the problem is not reproducible anymore. I didn't run integration tests though.
[patch.txt](https://github.com/primefaces/primefaces/files/8074448/patch.txt)

**Comment by melloware** [comment]
let me check it out

**Comment by melloware** [comment]
I submitted your patch as a PR for people to review.

**Comment by melloware** [comment]
One of the side effects of this patch I am seeing is that the `DefaultMenuModel` must be stored in a ViewScoped/SessionScoped/ApplicationScoped bean basically anything but RequestScoped.  This is due to the fact in RequestScoped the ID's are lost.

Which is probably why it was doing that weird "positional" lookup in the past which never seemed right to me.
