### ISSUE TITLE
ClientValidation: p:clientValidator / PrimeFaces.validateInstant does not highlight invalid input

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#8445]
**Describe the defect**
Usually the CSS class `ui-state-error` is added to the target element on validation errors after form / partial submit. This is not the case when using client side validation.

**Reproducer**
See [Client Side Validation - Event](https://www.primefaces.org/showcase/ui/csv/event.xhtml) at showcase.

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme: _ALL_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to [Client Side Validation - Event](https://www.primefaces.org/showcase/ui/csv/event.xhtml) at showcase
2. Click on 'Integer: (Keyup)' input field.
3. Enter a letter.
4. The message icon appears, but the input field is not outlined.

**Expected behavior**
The message icon appears and the input field is outlined red because of the added CSS class `ui-state-error`.

I could not find the source code to take a close look and propose a bugfix.

**Comment by tandraschko** [comment]
@maruTA-bis5 interessted in fixing this? :)

**Comment by ltlBeBoy** [comment]
I think I found the reason...Function `PrimeFaces.validation.validateInstant` in [validation.common.js](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js) should have a parameter `highlight` that can be handed over when calling `PrimeFaces.validation.validateInput(element);` at row 281. But then function `PrimeFaces.vi` needs that parameter too...
