### ISSUE TITLE
LazyDataModel: load: Map<String, SortMeta> sorting

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#8450]
This should not be a map, but a list?
At the JPA level you have,
```java
CriteriaBuilder criteriaBuilder = this.entityManager.getCriteriaBuilder();
List<Order> orderlist = ...;
criteriaQuery.orderBy(orderList);
```
hence the order of the order list (hehe) is relevant, no?

**Comment by tandraschko** [comment]
i cant follow. Why not just do map.values() if you need a list? you can also sort by #priority

**Comment by fcorneli** [comment]
ach... I didn't notice getPriority()
I expected something already ordered by priority, as this makes sense towards the JPA layer.

**Comment by tandraschko** [comment]
You can simple do this in a 1liner via streams
I will Close this for now

**Comment by fcorneli** [comment]
Okidoki. Thanks.
