### ISSUE TITLE
Tooltip: 0 in attribute showDelay has no effect

### ISSUE THREAD

**Issue by flange-ipb** [primefaces/primefaces#8458]
I'd like to achieve a show delay of 0 milliseconds for the tooltip component, i.e. `<p:tooltip for="someId" value="text" showDelay="0" />`. The tooltip still renders with 150 milliseconds delay. This is due to [tooltip.js:69](https://github.com/primefaces/primefaces/blob/c98a9857c1c3c695ef6112532418e50fff9001f3/primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js#L69), i.e. 0||150 equals 150.

**Comment by melloware** [comment]
Yep bit by Javascript "truthiness" where 0 = false.
```js
this.cfg.showDelay = this.cfg.showDelay||150;
```

For now set `showDelay="1"` to 1 millisecond to have it work for you.

**Comment by flange-ipb** [comment]
Yep, that's what I also tried as workaround after noticing that showDelay="0" has no effect.
Anyways: Aren't such short-circuit evaluations [considered bad practice](https://stackoverflow.com/a/34707750)?

**Comment by melloware** [comment]
PR Submitted.  You have to remember this code base started in 2008 before things like that were considered bad practice :)

**Comment by flange-ipb** [comment]
Completely unrelated, but maybe helpful:
I stumbled over this because I'm writing automated browser tests using Selenide and couldn't extract the text from the tooltip. Introduction of a sleep delay may help, but this can make tests flaky. I just figured out a CSS selector that selects the tooltip div when the tooltip text is finally visible: `div.ui-tooltip[style*='display: block']:not([style*='opacity'])`

**Comment by melloware** [comment]
Good to know!  Let us know if you find anything else whacky while writing your integration tests.
