### ISSUE TITLE
Core: HTML5 and script types

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8472]
**Description**
JSF 4.0 will no longer use 'type="text/JavaScript"'.  Therefore in the PF code base anywhere type is being used we should detect 4.0 and conditionally print it out or not.

**Comment by tandraschko** [comment]
it will be used actually but not when HTML5 doctype is recognized

**Comment by melloware** [comment]
I am actually moving this ticket under: https://github.com/primefaces/primefaces/issues/7813

**Comment by melloware** [comment]
I need to look at how to check the DocType....
