### ISSUE TITLE
SelectBooleanCheckbox: ARIA Issues

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8478]
**Describe the defect**
2 issues running the W3c Validator:

- [x] Attribute autocomplete is only allowed when the input type is color, date, datetime-local, email, hidden, month, number, password, range, search, tel, text, time, url, or week.
- [x] The aria-checked attribute should not be used on an input element which has a type attribute whose value is checkbox.

![image](https://user-images.githubusercontent.com/4399574/155141678-b7c2eced-803d-471c-b2a2-211a904475f8.png)

**Comment by tandraschko** [comment]
not sure about autocomplete: https://stackoverflow.com/questions/299811/why-does-the-checkbox-stay-checked-when-reloading-the-page

can you check IE11 and FF? 
it reads like it is ok, atleast for FF: https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing

**Comment by melloware** [comment]
yep let me try IE11. I always use Firefox and Chrome

**Comment by melloware** [comment]
Tested on IE11 and it seems to work just fine.
