### ISSUE TITLE
Datepicker: Panel overlaps input field on small screens

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#8485]
**Describe the defect**
If the space below the datepicker input field is too small, the datepicker panel is displayed above the input field ínstead. The problem is that if the space above the input field is also too small to show the full panel, the panel is shifted so that it overlaps the input field. It is still possible to type into the input field but the user can not see what they are typing in (see Screenshot below).

![Screenshot_overlapping_datepicker](https://user-images.githubusercontent.com/77431692/155556110-14b2c203-1757-42ae-bd69-ac68206c9714.png)

**Environment:**
 - PF Version: _10.0.0_

**To Reproduce**
1. Go to the PrimeFaces datepicker showcase http://primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml?jfwid=83ca3.
2. Change to a small screen height e.g. 600px.
3. Click into an input field in the middle of the screen so that the space below and above the input field is too small for the datepicker panel.
4. See error > The datepicker panel overlaps the input field which you clicked in.

**Expected behavior**
The datepicker panel should not overlap the focused input field so that the user is always able to see what he typed into it. I would suggest to always show the datepicker panel below the input field and if it is too big the user can scroll down to see the full panel.

**Comment by jepsar** [comment]
Isn't this basically #8381?

**Comment by melloware** [comment]
To me this is exactly #8381 you want the Touch UI interface once the screen is below a certain size.

**Comment by miedrl** [comment]
@jepsar @melloware Okay, I did'nt know if these were two separate problems. So it will be fixed with https://github.com/primefaces/primefaces/issues/8381?

**Comment by melloware** [comment]
i would think so we just need to figure out the best way to do that.

**Comment by melloware** [comment]
I will close this as a duplicate for now

**Comment by melloware** [comment]
This is what your example above looks like in TouchUI

![image](https://user-images.githubusercontent.com/4399574/155591898-e5fd5bc7-a857-4e26-9c19-bc73b3d4129b.png)
