### ISSUE TITLE
SelectCheckBoxMenu: ARIA and DRY

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8486]
**Describe the defect**
Add ARIA compliance to the SelectCheckboxMenu and refactor the JS code to add some DRY methods for `toggleSelection` and `togglePanel` and `toggleItem`.

**Comment by melloware** [comment]
@fcjm do you mind pulling my branch and testing it to make sure I didn't break your changes?

**Comment by fcjm** [comment]
Sure, I will do that.
