### ISSUE TITLE
Dialog: Dialogs can open outside of visible screen area

### ISSUE THREAD

**Issue by fcjm** [primefaces/primefaces#8487]
**Describe the defect**
We are using absolute positioned dialogs in our application. When such a dialog is initially opened everything works as expected. However when scrolling down the page and opening another dialog, the new dialog is opened at the location of the first dialog - which at that point can be off-screen. That is bad in two ways, since the user might not be aware that a dialog has opened and if he is aware then he needs to scroll up the entire page in order to see its contents.

**Reproducer**
[reproducer.zip](https://github.com/primefaces/primefaces/files/8133749/reproducer.zip)

**Environment:**
 - PF Version: _11.0.0_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start the reproducer
2. Click the button 'Show'
3. Close the dialog
4. Scroll down to the end of the page
5. Click the button 'Show'
6. Dialog opens outside of screen

**Expected behavior**
The position of the dialog should take scrolling into account.

**Further Info**
The root cause for this problem lies probably within the _show() function of dialog.js. There the position should be adjusted by the following code:

`
this.jq.css('top', String(parseFloat(this.jq.css('top')) + (winScrollTop - this.lastScrollTop)));
`

However nothing happens because the value set to 'top' is a String without the necessary unit 'px'. Just adding that to the statement fixes the problem. 

I believe a similar problem was handled in https://github.com/primefaces/primefaces/pull/6207:

I can provide a PR for this.

**Comment by melloware** [comment]
Please provide a PR!
