### ISSUE TITLE
AccordionPanel: Add support for actions, options and/or footer facets of Tab children like it is done for Panel

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#8491]
**Description**
We use dynamic `AccordionPanel` to group related preferences of our system in some configuration view. Some of the groups have some integrated test to verify the configured values as a whole. We are looking for a nice and easy accessible way to navigate to the corresponding test page from a group context. 

Our use case is just exemplary but could be generalized.

Currently we make usage of some custom flex style class for the `Tab`s in combination with a customized _title_ via `facet` containing a `LinkButton` to emulate  the accustomed _options/actions_ `facet`s of `Panel`.

**Describe the solution you would like**
It would be nice to have _options_ and/or _actions_ (and maybe _footer_) `facet` of `Tab` implemented for `AccordionPanel` like it is done for `Panel` for maximum overall consistency and user experience.

**Additional context**
[Existing _actions_ `facet` for `Tab`](https://github.com/primefaces/primefaces/issues/2666)
[Requested _footer_ `facet` for `Tab`](https://github.com/primefaces/primefaces/issues/3204)

**Example XHTML**

Current
```xml
<p:accordionPanel
  value="#{preferencesController.preferenceGroups}"
  var="group"
  varStatus="groupStatus"
  dynamic="true"
  multiple="true"
  activeIndex="#{preferencesController.preferenceGroups.size() eq 1 ? '0' : ''}"
>
  <p:tab
    title="#{preferences[group]}"
    titleStyleClass="custom-flex-style-class"
  >
    <f:facet name="title">
      <h:outputText value="#{preferences[group]}"></h:outputText>
      <p:linkButton
        id="testButton"
        icon="pi pi-cog"
        onclick="event.stopPropagation();"
        styleClass="rounded-button ml-auto"
        outcome="#{group.test.get()}"
        rendered="#{group.test.present}"
      >
        <f:param
          name="token"
          value="#{tokenProvider.getTestToken(group)}"
        ></f:param>
      </p:linkButton>
    </f:facet>
    ...
  </p:tab>
</p:accordionPanel
```
![current](https://user-images.githubusercontent.com/21124034/155740640-0ae869e1-1c85-43e4-9770-8e7bbd19cab0.png)

Wish
![wish](https://user-images.githubusercontent.com/21124034/155740682-06d972dd-c74f-4095-bd92-209d91d68e49.png)

**Comment by tandraschko** [comment]
would you like to work on a PR?

**Comment by irieill** [comment]
> would you like to work on a PR?

i will give it a try
