### ISSUE TITLE
Printer: not working with css "@media print" anymore

### ISSUE THREAD

**Issue by danteCarvalho** [primefaces/primefaces#8492]
**Describe the defect**
With primefaces 10 p:printer was working to print elements that should only appear when there is a print. But  its not working on primefaces 11.

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8146193/primefaces-test.zip)

**Environment:**
 - PF Version: _11.0.0_

**To Reproduce**
1 Create a css class and media like this:

.printMe {
	display: none;
}
@media print {
	.noPrint{
		display: none !important;
	}
	.printMe{
		display: inline !important;
	}
}

2 put the printMe class on any html element

3 try to print it with p:printer

**Expected behavior**
The html element that has the printMe should appear on the print.

**Example XHTML**
```html
<h:form id="frmTest">
		<p:commandButton value="print">
			<p:printer target="frmTest">
			</p:printer>
		</p:commandButton>
		<h:outputText
			styleClass="printMe"
			value="TEXT THAT SHOULD PRINT"
		>
		</h:outputText>
		<h:outputText
			styleClass="noPrint"
			value="Text that should not print"
		>
		</h:outputText>
	</h:form>
```

**Comment by melloware** [comment]
Can you check I think your issue is actually this one https://github.com/primefaces/primefaces/issues/8232 and its been fixed for 12.0.0.

**Comment by melloware** [comment]
This will be fixed properly in 12.0.0

**Comment by danteCarvalho** [comment]
Woah, thanks for being soo quick. As a workaround for now i am hiding everything else on the page and only print what i need with the window.print() method (i use it to print a hidden image on the page).

**Comment by melloware** [comment]
Runnable workaround:
[printer-override.zip](https://github.com/primefaces/primefaces/files/8605468/printer-override.zip)

Just run `mvn clean jetty:run`
