### ISSUE TITLE
DataTable: filterBy is not called after AJAX update

### ISSUE THREAD

**Issue by ElliotBu** [primefaces/primefaces#8496]
**Description**
DataTable is not calling the filterBy properties after ajax Update. The code was working in PF10 Community.

**Environment:**
 - PF Version: 11.0.1
 - PF Theme: Poseidon 4.1.0
 - JSF 2.3 GlassFish 5.1
 - Firefox and Chrome

**Expected behavior**
function stated in p:dataTable filterBy is called by respecting the value from variable "showDeleted". When the page is called the value for "showDeleted" is false. If the user set the value from Checkbox to true, the datatable should update and call the filterby Property again showDeleted is now true and the data should switch the fillter. In PF10 it works perfectly. In PF11 the function "objectController.getDefaultFilterMeta" is not called.

**Example XHTML**
```html
<h:form id="frmInternalContact">
    <p:remoteCommand name="refresh" update="dtaInternalContact" complete="PF('widInternalContact').filter()" />

    <p:selectBooleanCheckbox id="sbcShowDeleted" value="#{iNCOController.showDeleted}" onchange="refresh()">
        <p:ajax process="@this"  />
    </p:selectBooleanCheckbox>

    <p:dataTable 
	id="dtaInternalContact"  
	value="#{iNCOController.items}" 
	var="row"
	widgetVar="widInternalContact" 
	selectionMode="multiple"
	liveScroll="false"
	scrollable="true"
	scrollHeight="630"
	selection="#{iNCOController.selectedItems}"
	filteredValue="#{iNCOController.filteredItems}"
	filterBy="#{iNCOController.showDeleted ? objectController.getDefaultFilterMeta('defaultDeleted') : 
                         objectController.getDefaultFilterMeta('dtaInternalContact')}"
	sortBy="#{objectController.getDefaultSortMeta('dtaInternalContact')}"
	sortMode="multiple"
	allowUnsorting="true" 
	paginator="true" 
	paginatorPosition="bottom"
	paginatorAlwaysVisible="true"
	paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} 
                                         {RowsPerPageDropdown}"
	currentPageReportTemplate="{totalRecords} record(s)"
	rows="100"
	rowsPerPageTemplate="100,200,300,400,500"  
	rowKey="#{row.internalContactPk}"
	resizableColumns="true" 
	liveResize="true" 
	draggableColumns="true"
	reflow="true"
	showGridlines="true"
	rowStyleClass="#{row.deleted ? 'row_deleted' : !row.activeFlag ? 'row_inactive' : null}"
	styleClass="ui-datatable-striped ui-datatable-sm">

	    <p:columns value="#{iNCOController.mainTableColumns}"
		               var="column" 
			       headerText="#{column.header}"
			       field="#{column.property}"
			       styleClass="#{column.adjust}"
			       style="width:#{column.width}" 
			       visible="#{column.visible}" 
			       filterable="#{column.filterable}"
			       filterMatchMode="#{column.type eq 'boolean' ? 'equals' : 'contains'}"
			       sortable="#{column.sortable}">
                <f:facet name="filter">
			<p:selectOneMenu onchange="PF('widInternalContact').filter()" rendered="#{column.type eq 'boolean'}">
				<f:converter converterId="javax.faces.Boolean" />
				<f:selectItem itemLabel="All" itemValue="" />
				<f:selectItem itemLabel="True" itemValue="true" />
				<f:selectItem itemLabel="False" itemValue="false" />
			</p:selectOneMenu>
			<p:selectOneMenu onchange="PF('widInternalContact').filter()" rendered="#{column.type eq 'state'}">
				<f:converter converterId="javax.faces.Boolean" />
				<f:selectItem itemLabel="All" itemValue="" />
				<f:selectItem itemLabel="Contact" itemValue="false" />
				<f:selectItem itemLabel="List" itemValue="true" />
				</p:selectOneMenu>		
			</f:facet>
		<h:outputText  rendered="#{column.type eq 'string'}"   value="#{row[column.property]}" />
		<h:outputText  rendered="#{column.type eq 'datetime'}" value="#{row[column.property]}">
                      <f:convertDateTime locale="#{parameterSessionController.localeCode}" type="localDateTime" dateStyle="medium"
                                                     timeStyle="short"/>
                </h:outputText>
		<p:outputLabel rendered="#{column.type eq 'boolean' and row[column.property]}">
                     <i class="pi pi-check-circle" />
                </p:outputLabel>
		<p:outputLabel rendered="#{column.type eq 'state' and row[column.property] eq true}">
                     <i class="pi pi-list" />
                </p:outputLabel>
		<p:outputLabel rendered="#{column.type eq 'state' and row[column.property] eq false}">
                    <i class="pi pi-user" />
                </p:outputLabel>
            </p:columns>
    </p:dataTable>
</h:form>
```

**Example Bean**
```Java
@Named
@SessionScoped
public class ObjectController implements Serializable {
	private static final long serialVersionUID = 1L;
	
	private Map<String,List<SortMeta>>	sortMap    = new HashMap<String,List<SortMeta>>();
	private Map<String,List<FilterMeta>>	filterMap   = new HashMap<String,List<FilterMeta>>();
	
	/* CONTROLLER CREATION DEFINITIONS */
	public ObjectController () {
		createDefaultSortMeta();
		createDefaultFilterMeta();
	}

	public List<SortMeta> getDefaultSortMeta(String table) {
		return sortMap.get(table);
	}
	
	public List<FilterMeta> getDefaultFilterMeta(String table) {
		return filterMap.get(table);
	}
	private void createDefaultSortMeta() {
		sm = new ArrayList<SortMeta>();
		sm.add(SortMeta.builder().field("distributionList").order(SortOrder.ASCENDING).priority(1).build());
		sortMap.put("dtaInternalContact", sm);
	}

	private void createDefaultFilterMeta() {
		List<FilterMeta> fm = new ArrayList<FilterMeta>();
		fm.add(FilterMeta.builder().field("deleted").filterValue(true).matchMode(MatchMode.EQUALS).build());
		filterMap.put("defaultDeletedwoActive", fm);

		fm = new ArrayList<FilterMeta>();
		fm.add(FilterMeta.builder().field("activeFlag").filterValue(true).matchMode(MatchMode.EQUALS).build());
		fm.add(FilterMeta.builder().field("deleted").filterValue(false).matchMode(MatchMode.EQUALS).build());
		filterMap.put("dtaInternalContact", fm);
	}
}
```

**Comment by tandraschko** [comment]
Please provide a primefaces-test reproducer, otherwise we cant reproduce that complex xhtml

**Comment by tandraschko** [comment]
And please also try a trunk build, might be fixed already

**Comment by ElliotBu** [comment]
edited

**Comment by danteCarvalho** [comment]
Same problem, in primefaces 10 its was working. I use ui:include to change the columns when the user clicks a button. I have a lazy p:dataTable , when i change the columns if you try to type anything on the filter, the request is sent, the count method is called, but the (Map<String, FilterMeta> filterBy) param never changes and is empty {}.

**Comment by tandraschko** [comment]
@ElliotBu in general we need you to fork our [primefaces-test](https://github.com/primefaces/primefaces-test) repo
also i removed your link as it contains licensed poseidon code, please delete your repo

**Comment by tandraschko** [comment]
your sample also cant work
you store the "showDeleted" in a RequestScoped bean and your filtering currently throws 3 AJAX request, so it will never be used anyway
not with PF10, not with 11

anyway, i see your point of view
our internal DT filterBy is constructed once per ViewScope, so if you change the filterBy in your bean, we wont receive it a second time
in PF10 we rebuilt it every time propably (DT#getFilterByAsMap)

@Rapster do we want to support that? in general i think the globalFilterFunction is the better choice for this kind of a global filter

**Comment by tandraschko** [comment]
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/8151981/primefaces-test-master.zip)

**Comment by danteCarvalho** [comment]
Globalfilter wont work for me, i have 6 buttons, they all change the columns on my Products table, and some have a custom filter p:selectOneMenu for boolean and p:selectOneMenu for entity/object.
Button 1 show main columns, button 2 show price columns, button 3  show stock, button 4 expiration date, button 5 tax, 6 medicine.  Related video: https://imgur.com/a/4hkZwHD or https://i.imgur.com/PIZOeqW.mp4

**Comment by tandraschko** [comment]
@danteCarvalho please dont use this issue to talk about your issue, its quite different. Better see: https://github.com/primefaces/primefaces/issues/8159

**Comment by tandraschko** [comment]
I think you really should use global filters here, but thats a valid workaround for now:
```
        DataTable table = (DataTable) FacesContext.getCurrentInstance().getViewRoot().findComponent(":form:customers");
        table.setSortByAsMap(null);
```

lets wait for @Rapster response

**Comment by ElliotBu** [comment]
> your sample also cant work you store the "showDeleted" in a RequestScoped bean and your filtering currently throws 3 AJAX request, so it will never be used anyway not with PF10, not with 11
> 
> anyway, i see your point of view our internal DT filterBy is constructed once per ViewScope, so if you change the filterBy in your bean, we wont receive it a second time in PF10 we rebuilt it every time propably (DT#getFilterByAsMap)
> 
> @Rapster do we want to support that? in general i think the globalFilterFunction is the better choice for this kind of a global filter

I usally use VIEWSCOPED from Omnifaces for my pages and in this regards It was working in PF10. I will delete the Repo. Are you going to have a look why the funtion is only called once when the page is open and not again on Ajax update?

Thank you

**Comment by tandraschko** [comment]
As i said, we will discuss it but you should actually use global filters for your case

**Comment by Rapster** [comment]
It would be easier for me if I had a reproducer

**Comment by tandraschko** [comment]
I attached one

**Comment by tandraschko** [comment]
@Rapster any feedback if we should support his? IMO the current behavior is fine 
We have a workaround that such modification can be done when calling #resetColumns

**Comment by Rapster** [comment]
current behavior is fine
