### ISSUE TITLE
PickList: Column Header support

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#85]
Display column headers inside PickList using either headerText or header facet.

**Comment by B-R-Bender** [comment]
this would be nice. right now this would be very useful to me)
[picklist](http://puu.sh/vD5gQ/f7312c73dc.png)

**Comment by melloware** [comment]
You can already do this with facets.

```xml
<f:facet name="sourceCaption">Available</f:facet>
<f:facet name="targetCaption">Starting</f:facet>
```

![image](https://github.com/primefaces/primefaces/assets/4399574/e153ab02-8472-4315-98c7-11931e96c7e1)
