### ISSUE TITLE
RowExpressionResolver with datatable columns

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#850]
`RowExpressionResolver` doesn't handle Columns children of Datatable. So the update row doesn't work with dynamic columns.

**Comment by tandraschko** [comment]
Would be great if you could provide a patch. I have likely not time for such tasks the next months.

**Comment by Julienng** [comment]
I try to work on it but i'm stuck. Did you have any suggestion to handle this?

**Comment by Julienng** [comment]
Ok i've got it. Just need to test with more complex datatable and I come back to you

**Comment by tandraschko** [comment]
any news? ;)

**Comment by Julienng** [comment]
hi,
sorry for the time to provide the patch. I've got some work before. I will
do it next week

**Comment by tandraschko** [comment]
applied and refactored - please give it a try.

**Comment by tandraschko** [comment]
And thanks for the patch of course!
