### ISSUE TITLE
Column: Automatic sort if groupRow is set

### ISSUE THREAD

**Issue by fabermundi** [primefaces/primefaces#8502]
**Describe the defect**
When having a column that has the property "groupRow" set to "true" and the "sortBy" property is set then this column is automatically sorted.

**Environment:**
 - PF Version: 11.0.1
 - JSF + version: JSF 2.3
 - Affected browsers: Firefox and Chrome

**Expected behavior**
A column where "sortOrder" is not set should not be sorted by default. At the example below the column is sorted automatically.

**Example XHTML**
```html
<h:form>
    <p:dataTable value="#{groupRow.data}" var="data">
        <p:column sortBy="#{data}" filterBy="#{data}" groupRow="true">
            <h:outputText value="#{data}" />
        </p:column>
    </p:dataTable>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class GroupRow implements Serializable {
    private static final long serialVersionUID = 4485167715842515932L;

    private List<Integer> data = null;

    public List<Integer> getData() {
        if (data == null) {
            data = new ArrayList<>();
            for (int i = 10; i >= 1; i--)
                data.add(i);
        }
        return data;
    }
}
```

**Comment by tandraschko** [comment]
I get:
Caused by: javax.faces.FacesException: Data type should be java.util.List or javax.faces.model.ListDataModel instance to be sortable.

and thats by design

**Comment by fabermundi** [comment]
Thanky ou for the reply.

Sorry I copied an old version of the code.

This is the right one:

@Named
@ViewScoped
public class GroupRow implements Serializable {
    private static final long serialVersionUID = 4485167715842515932L;

    private List<Integer> data = null;

    public List<Integer> getData() {
        if (data == null) {
            data = new ArrayList<>();
            for (int i = 10; i >= 1; i--)
                data.add(i);
        }
        return data;
    }
}

Should I edit my report or create a new issue?

**Comment by tandraschko** [comment]
i will reopen, please edit
and next time try your sample before creating a issue, thats wasting our time.

**Comment by fabermundi** [comment]
Thank you and sorry again.

**Comment by tandraschko** [comment]
Currently this is by design:
https://github.com/primefaces/primefaces/blob/fc76cdf76b8ba4f31833de176b0c2bb5106081f3/primefaces/src/main/java/org/primefaces/model/SortMeta.java#L97-L100

but it was NOT in 8.0 codebase

**Comment by tandraschko** [comment]
See: https://github.com/primefaces/primefaces/issues/6742

@Rapster should we just close this issue, as its by design?
8.0 was indeed unsorted - no idea why we introduced it TBH

**Comment by Rapster** [comment]
To make "group" feature happens, sorting was and still is the default strategy. See 8.0: 

```java
        ValueExpression groupByVE = null;
        ValueExpression tableSortByVE = table.getValueExpression(DataTable.PropertyKeys.sortBy.toString());
        if (tableSortByVE != null) {
            groupByVE = tableSortByVE;
        }
        else {
            groupByVE = (table.getSortBy() == null || table.isMultiSort())
                        ? null
                        : context.getApplication().getExpressionFactory().createValueExpression(
                                eLContext, "#{" + table.getVar() + "." + table.getSortBy() + "}", Object.class);
        }
```

At a glance, I can't see how it was working without previously sorting if you look how the whole thing was/is implemented _(it's an iterative process, so n + 1 item better be sorted otherwise you'll end up most likely having group of 1 element)_.

You can have a look also at PrimeNG, seems like they're doing the same

**Comment by tandraschko** [comment]
i just tried it with 8.0 and it wasnt sorted, but not idea if it was working

so lets close it as "works as expected"?

**Comment by melloware** [comment]
I say we close it as works as expected

**Comment by halisyilboga** [comment]
Aslinda grup satir yapmak ile sort yapmak arasinda fark var. Grup satirlamanin siralama olmadanda calisabilmesi gerekmektedir. We add newly added rows at the top of the table and this feature broke that. Also we make inplace edit and automatik sorting is also broke that feature. Last but not least default sorted column seems ugly and irritating. We can get the order from db or backend why I soppose to sort in filter. 
When I investigate SordOrder Enum I saw that it has a propertyv UNSORTED. But this feature is also does not work correct with grouprowing. This is definetly a bug.

**Comment by jepsar** [comment]
@halisyilboga please open a new issue which includes a reproducer and references this issue.
