### ISSUE TITLE
Chart.js: Cartesian(Linear)Axes properties are ignored

### ISSUE THREAD

**Issue by viiez** [primefaces/primefaces#8504]
**Describe the defect**
CartesianAxes.scaleLabel and CartesianLinearTicks.suggested[Min/Max] are not encoded correctly due to renamings in Chart.js 3.x.

According to https://www.chartjs.org/docs/latest/getting-started/v3-migration.html:

> - scales.[x/y]Axes.scaleLabel.labelString was renamed to scales[id].title.text
> - scales.[x/y]Axes.ticks.suggestedMax was renamed to scales[id].suggestedMax
> - scales.[x/y]Axes.ticks.suggestedMin was renamed to scales[id].suggestedMin

**Reproducer**
https://github.com/viiez/primefaces-test/tree/chartjs-migration

**Environment:**
 - PF Version: 11.0.0
 - PF Theme: N/A
 - JSF + version: Mojarra 2.2.x
 - Affected browsers: ALL

**To Reproduce**
1. Run the Reproducer
2. Visit http://localhost:8080/primefaces-test

**Expected behavior**
Cartesian(Linear)Axes properties are encoded correctly.

**Example XHTML**
See https://github.com/viiez/primefaces-test/blob/chartjs-migration/src/main/webapp/test.xhtml

**Example Bean**
See https://github.com/viiez/primefaces-test/blob/chartjs-migration/src/main/java/org/primefaces/test/TestView.java

**Comment by melloware** [comment]
I will fix this. thanks for reporting.

**Comment by melloware** [comment]
Please review my PR.  This affected RadialScales as well as its similar to CartesianScales.
