### ISSUE TITLE
DataTable: Add helper method to resolve value of p:columns and nested field expression like var.user.name

### ISSUE THREAD

**Issue by ElliotBu** [primefaces/primefaces#8509]
**Describe the defect**
I have a DataTable which shows the value from the function "Object.toString". If I'm trying to filter the column an SQLServerException appears. It looks that the class cannot resolve the column name from the referenced table properly "WHERE ( LIKE ? AND ...". 
The Data Column shows the value from property createUser from Entity Class InternalContact which is defined in MappedSuperclass

![image](https://user-images.githubusercontent.com/100536591/156437377-966baf95-826a-45f4-bf02-9d4ad2a422d8.png)

```text
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.4.v20190115-ad5b7c6b2a): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'LIKE'.
Error Code: 156
Call: SELECT COUNT(t0.INTERNAL_CONTACT_PK) FROM T_INTERNAL_CONTACT t0, T_SECURITY_USER t1 WHERE ( LIKE ? AND (t1.USER_PK = t0.CREATE_USER))
	bind => [1 parameter bound]
Query: ReportQuery(referenceClass=InternalContact sql="SELECT COUNT(t0.INTERNAL_CONTACT_PK) FROM T_INTERNAL_CONTACT t0, T_SECURITY_USER t1 WHERE ( LIKE ? AND (t1.USER_PK = t0.CREATE_USER))")
```

**Reproducer**
there is no chance to provide an reproducer, because the Database is located in a VPN and the issue only occurs if the JPALazyDataModel is feeding the table.

**Environment:**
 - PF Version: 11.0.1
 - JSF 2.3 GlassFish 5.1
 - Firefox and Chrome

**Expected behavior**
Filtering without exception

**Example XHTML**
```html
<h:form id="frmInternalContact">
    <p:dataTable 
        id="dtaInternalContact"  
        value="#{iNCOController.items}" 
        var="row"
        widgetVar="widInternalContact" 
        selectionMode="multiple"
        liveScroll="false"
        scrollable="true"
        scrollHeight="630"
        selection="#{iNCOController.selectedItems}"
        filteredValue="#{iNCOController.filteredItems}"
        sortBy="#{objectController.getDefaultSortMeta('dtaInternalContact')}"
        sortMode="multiple"
        allowUnsorting="true" 
        paginator="true" 
        paginatorPosition="bottom"
        paginatorAlwaysVisible="true"
        paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
        currentPageReportTemplate="{totalRecords} record(s)"
        rows="100"
        rowsPerPageTemplate="100,200,300,400,500"  
        rowKey="#{row.internalContactPk}"
        resizableColumns="true" 
        liveResize="true" 
        draggableColumns="true"
        reflow="true"
        showGridlines="true"
        rowStyleClass="#{row.activeFlag ? '' : 'row_inactive'}"
        styleClass="ui-datatable-striped ui-datatable-sm">
					
        <f:facet name="header">
            <div class="table-header">
                <span class="table-header-pagename">#{iNCOController.viewCaption}</span>
                <span class="ui-input-icon-left filter-container">
                    <i class="pi pi-search"></i>
                    <p:inputText id="globalFilter" onkeyup="PF('widInternalContact').filter()" placeholder="Search"/>
                </span>
            </div>
        </f:facet>

        <p:ajax event="rowSelect"    update=":frmInternalContact:tbToolbar" />
        <p:ajax event="rowUnselect"  update=":frmInternalContact:tbToolbar" />
        <p:ajax event="rowDblselect" oncomplete="editInternalContact()" />

        <p:columns value="#{iNCOController.mainTableColumns}"
                           var="column" 
                           headerText="#{column.header}"
                           field="#{column.property}"
                           styleClass="#{column.adjust}"
                           style="width:#{column.width}" 
                           visible="#{column.visible}" 
                           filterable="#{column.filterable}"
                           filterMatchMode="#{column.type eq 'boolean' or column.type eq 'deleted' or column.type eq 'state' ? 'equals' : 'contains'}"
                           sortable="#{column.sortable}">
            <f:facet name="filter">
                <p:selectOneMenu onchange="PF('widInternalContact').filter()" rendered="#{column.type eq 'boolean'}">
                    <f:converter converterId="javax.faces.Boolean" />
                    <f:selectItem itemLabel="All" itemValue="" />
                    <f:selectItem itemLabel="True" itemValue="true" />
                    <f:selectItem itemLabel="False" itemValue="false" />
                    </p:selectOneMenu>
                <p:selectOneMenu onchange="PF('widInternalContact').filter()" rendered="#{column.type eq 'state'}">
                    <f:converter converterId="javax.faces.Boolean" />
                    <f:selectItem itemLabel="All" itemValue="" />
                    <f:selectItem itemLabel="Contact" itemValue="false" />
                    <f:selectItem itemLabel="List" itemValue="true" />
                </p:selectOneMenu>		
            </f:facet>
            <h:outputText  rendered="#{column.type eq 'string'}"   value="#{row[column.property]}" />
            <h:outputText  rendered="#{column.type eq 'datetime'}" value="#{row[column.property]}"><f:convertDateTime locale="#{parameterSessionController.localeCode}" type="localDateTime" dateStyle="medium" timeStyle="short"/></h:outputText>
            <p:outputLabel rendered="#{column.type eq 'boolean' and row[column.property]}"><i class="pi pi-check-circle" /></p:outputLabel>
            <p:outputLabel rendered="#{column.type eq 'state' and row[column.property] eq true}"><i class="pi pi-list" /></p:outputLabel>
            <p:outputLabel rendered="#{column.type eq 'state' and row[column.property] eq false}"><i class="pi pi-user" /></p:outputLabel>
        </p:columns>
    </p:dataTable>
</h:form>
```

**Internal Contact Entity**
```java
@Entity
@Table(name="T_INTERNAL_CONTACT")
public class InternalContact extends FWActivatableEntity implements Comparable<InternalContact>, Serializable {
	private static final long serialVersionUID = 1L;

	@Override
	public int compareTo(InternalContact a) {
		return this.toString().compareToIgnoreCase(a.toString());
	}

	@Id
	@SequenceGenerator(name="INTERNAL_CONTACT_GEN", sequenceName="SEQ_T_INTERNAL_CONTACT", allocationSize = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="INTERNAL_CONTACT_GEN")
	@Column(name="INTERNAL_CONTACT_PK", unique=true, nullable=false, precision=12)
	@JsonSerialize(using = PKSerializer.class)
	private long internalContactPk;

	@Column(name="DEPARTMENT", nullable = true, length = 50)
	private String department;

	@Column(name="FIRST_NAME", nullable = true, length = 50)
	private String firstName;

	@Column(name="LAST_NAME", nullable = true, length = 50)
	private String lastName;

	@Column(name="MAIL_ADDRESS", nullable = false, length = 50)
	private String mailAddress;

	@Column(name="MOBILE_PHONE", nullable = true, length = 25)
	private String mobilePhone;

	@Column(name="PHONE", nullable = true, length = 25)
	private String phone;
	
	@Column(name="DISTRIBUTION_LIST", nullable = false)
	private Boolean distributionList;
	
	@Column(name="DISTRIBUTION_LIST_NAME", nullable = true, length = 50)
	private String distributionListName;
}
```

**Mapped Superclass Entity which resolve the reference to the User Table**
```java
@MappedSuperclass
public class FWActivatableEntity implements Serializable {
	private static final long serialVersionUID = 1L;

	@Column(name = "ACTIVE_FLAG")
	private Boolean activeFlag;
	
	@Column(name = "CREATE_DATETIME")
	@JsonSerialize(using = LocalDateTimeSerializer.class)
	private LocalDateTime createDatetime;
	
	@Column(name = "UPDATE_DATETIME")
	@JsonSerialize(using = LocalDateTimeSerializer.class)
	private LocalDateTime updateDatetime;
	
	@Column(name = "DELETE_DATETIME")
	@JsonSerialize(using = LocalDateTimeSerializer.class)
	private LocalDateTime deleteDatetime;
	
	@ManyToOne
	@JoinColumn(name="CREATE_USER")
	@JsonSerialize(using = UserSerializer.class)
	private User createUser;

	@ManyToOne
	@JoinColumn(name="UPDATE_USER")
	@JsonSerialize(using = UserSerializer.class)
	private User updateUser;
		
	@ManyToOne
	@JoinColumn(name="DELETE_USER")
	@JsonSerialize(using = UserSerializer.class)
	private User deleteUser;

	@Transient
	@JsonIgnore
	private Boolean deleted;
	
	@Transient
	@JsonIgnore
	private Boolean changed;
	
	@Transient
	@JsonIgnore
	private String action;
	
	@Transient
	@JsonIgnore
	private String objectName;
}

Thank you and Regards
Christian

**Comment by tandraschko** [comment]
I wont work on it without reproducer.
So either create one with hsqldb or you provide a PR with a fix

**Comment by melloware** [comment]
Agree with Thomas this is a complex scenario that is impossible to debug without a reproducer and it takes way too much effort for us to try and reproduce your issue.

**Comment by ElliotBu** [comment]
I’m on it to create a reproducer.

**Comment by ElliotBu** [comment]
Please find Reproducer here: https://github.com/ElliotBu/PF-TEST.git

I was using a MySQL Database and you can find a script which create schema, tables and sample data in Folder WebContent.

Cheers
Christian

**Comment by tandraschko** [comment]
can you please fork [primefaces-test](https://github.com/primefaces/primefaces-test)? it allows us to run via mvn and jetty easily.

**Comment by ElliotBu** [comment]
> can you please fork [primefaces-test](https://github.com/primefaces/primefaces-test)? it allows us to run via mvn and jetty easily.

I don't know how it works. I have a lack of knowlegde in this regards.

**Comment by tandraschko** [comment]
everything is explained here, its just a sample project: https://github.com/primefaces/primefaces-test

**Comment by ElliotBu** [comment]
Please find the new reproducer here https://github.com/ElliotBu/primefaces-test.git

**Comment by ElliotBu** [comment]
An additional question I have just added an CustomConverter to the Reproducer. This converter is defined for the 4th column of the datatable, but your code from class JpaLazyDataModel 

**Function**
```Java
convertToType(String value, Class<V> valueType)" 
```
**LINE**
```Java
Converter<V> converter = context.getApplication().createConverter(valueType); 
```
is not calling the JSF Converter. The value for "converter" results in NULL.

Thank you
Christian

**Comment by jepsar** [comment]
You should not include elite releases in your test. Please use 12.0.0-SNAPSHOT.

**Comment by tandraschko** [comment]
converters are not supported like this in the JPADataModel
you can create a feature request but i dont have time to work on it.

**Comment by ElliotBu** [comment]
> 

So overriding "convertToType" is the only way to deal with data types other than String.

**Comment by tandraschko** [comment]
> > 
> 
> So overriding "convertToType" is the only way to deal with data types other than String.

in theory every primitive should work - POJO are not supposed to work in general (use field=user.name instead of field=user)
but as i said -> new feature request

**Comment by ElliotBu** [comment]
> You should not include elite releases in your test. Please use 12.0.0-SNAPSHOT.

I only fork primefaces-test and added the reproducer objects. I don't see anything with 12.00.0-SNAPSHOT.

**Comment by ElliotBu** [comment]
> > > 
> > 
> > 
> > So overriding "convertToType" is the only way to deal with data types other than String.
> 
> in theory every primitive should work - POJO are not supposed to work in general (use field=user.name instead of field=user) but as i said -> new feature request

I doesn't work with field="User.username" > Exception Entity does not have the property 'User.username'.

```Java
model.add(new ColumnModel("Created by","User.username","left","5%","user",true,true,true));
```

I guess Feature Request and wait is the only solution.
Cheers

**Comment by tandraschko** [comment]
its actually supposed to work like this, i think your exception is also because of that
you need "createUser.firstName" like in EL

**Comment by ElliotBu** [comment]
> its actually supposed to work like this, i think your exception is also because of that you need "createUser.firstName" like in EL

```Java
model.add(new ColumnModel("Created by","createUser.username","left","5%","user",true,true,true));
```
Unfortunately Not > The class 'main.java.org.primefaces.test.InternalContact' does not have the property 'createUser.username'.

**Comment by tandraschko** [comment]
then i still need a working reproducer
did you try your reproducer via mvn jetty:run? i just wonder as WebContent is a IDE directory, not maven

**Comment by ElliotBu** [comment]
> then i still need a working reproducer did you try your reproducer via mvn jetty:run? i just wonder as WebContent is a IDE directory, not maven

I work with Eclipse and I don't use Maven. Never worked with Maven.

**Comment by tandraschko** [comment]
I never worked with Eclipse projects
Did you try 12.0 Snapshot?

**Comment by ElliotBu** [comment]
Will try to do it with Maven. Let you once it's done

**Comment by ElliotBu** [comment]
I have uploaded now a next reproducer 12.0.0-SNAPSHOT. https://github.com/ElliotBu/primefaces-test-1.git
The only thing is that I'm not able to create in Jetty a JDBC Connection Pool. All the configs are in and script with data for a MySQL Database is in the ContextRoot.

Christian

**Comment by tandraschko** [comment]
last time recreating a example ;) it doesnt even compile as packages are wrong.
[primefaces-test-1-master.zip](https://github.com/primefaces/primefaces/files/8184921/primefaces-test-1-master.zip)

**Comment by tandraschko** [comment]
@melloware would you like to create a DB example/reproducer-test-project or something from this project?

**Comment by tandraschko** [comment]
in general our JpaLazyDataModel works fine as you can see in this example.
Our JpaLazyDataModel requires "createUser.username" to join correctly and this works fine - but EL fails in your case as the array acessor `#{row[column.property]}` doesnt work with nested objects. So changing to:

```
<h:outputText rendered="#{column.type eq 'user'}" value="#{row['createUser']}">
```

works

**Comment by tandraschko** [comment]
We could either allow:
`field="createUser" filterBy="createUser.username"`

or we could also provide a helper method/util to receive the value, as the problem is just the the array acessor doesnt support `#{row['obj.obj']}`, just `#{row['obj']}`
and the array acessor is only required with `p:columns`

WDYT @Rapster ?

**Comment by tandraschko** [comment]
we could also provide a helper method/util, the problem is just the the array acessor doesnt support `#{row['obj.obj]'}`, just ``#{row['obj]'}

**Comment by melloware** [comment]
@tandraschko i was talking about that with @FlipWarthog yesterday creating a DB enabled reproducer.  Will put it in the backlog for now and may try and get to it!

**Comment by ElliotBu** [comment]
Thank guys for the support and clarifications. Looking forward that `p:columns` will accept `#{row['obj.obj']}`,

Cheers
Christian

**Comment by tandraschko** [comment]
p:columns wont accept that, EL doesnt allow it

**Comment by ElliotBu** [comment]
than I'm looking forward to the helper method/util which can do the magic.

**Comment by tandraschko** [comment]
That works:

```
    public String getValue(String var, String field)
    {
        FacesContext context = FacesContext.getCurrentInstance();
        ValueExpression ve = context.getApplication().getExpressionFactory()
                .createValueExpression(context.getELContext(), "#{" + var + "." + field + "}", String.class);
        return (String) ve.getValue(context.getELContext());
    }
```
```
value="#{pfController.getValue('row', column.property)}"
```


----- OR ------


```
    public String getColumnValue(UIComponent component)
    {
        UIColumn column = ComponentTraversalUtils.closest(UIColumn.class, component);
        DataTable table = ComponentTraversalUtils.closest(DataTable.class, component);
        return table.getConvertedFieldValue(FacesContext.getCurrentInstance(), column);
    }
```

```
value="#{pfController.getColumnValue(component)}"
```

**Comment by tandraschko** [comment]
i would like to hear from @Rapster, whats the cleanest way to add something as helper
the second way would even invoke converters

**Comment by ElliotBu** [comment]
I was testing the first option already and it works! Will try the second in combination with a converter especially LocalDateTime later on.

Thanks a lot for assistance.

Christian

**Comment by Rapster** [comment]
Why don't you simply init field with "createUser.username"? Nested syntax worked in the past

**Comment by tandraschko** [comment]
Thats what i did - see my example; EL throws a exception with this: '{row[createUser.username]}'
Everything else like filter and sort works, just not display it with this EL above

**Comment by tandraschko** [comment]
Implemented it a small EL function:

```html
<h:outputText rendered="#{column.type eq 'string'}"   value="#{p:dynamicColumnValueAsString(component)}" />
<h:outputText  rendered="#{column.type eq 'datetime'}" value="#{p:dynamicColumnValueAsString(component)}">
    <f:convertDateTime type="localDateTime" dateStyle="medium" timeStyle="short"/>
</h:outputText>
<p:outputLabel rendered="#{column.type eq 'boolean' and p:dynamicColumnValue(component)}">
     <i class="pi pi-check-circle" />
</p:outputLabel>
```
