### ISSUE TITLE
Component: Chat component

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#8516]
**Description**
It would be great if we can have a chat component to use with WebSocket.

**Comment by melloware** [comment]
Couldn't you do this already with the [Terminal ](https://www.primefaces.org/showcase/ui/misc/terminal/basic.xhtml)component and Websocket?

And you can put it inside the [PrimeFaces Extensions  SlideOut](https://www.primefaces.org/showcase-ext/views/slideOut.jsf) component if you want it to be like a customer service like chat tab like many websites have.

**Comment by anuragnz** [comment]
Thanks @melloware .
I will give it a try.

**Comment by jepsar** [comment]
See also https://github.com/primefaces-extensions/primefaces-extensions/issues/127

**Comment by melloware** [comment]
Yes going to close this for now since its already an open issue on PFE
