### ISSUE TITLE
Update Java EE XML Schema Resources

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#8517]
The following Java EE 6 XML schema resources appear in different PrimeFaces XML files.
```
web-app_3_0.xsd
web-fragment_3_0.xsd
web-facelettaglibrary_2_0.xsd
web-facesconfig_2_0.xsd
```
They could be updated to at least Java EE7 (since Java EE7 is the minimum version for Java 8, and PF12 supports at least Java 8)
````
web-app_3_1.xsd
web-fragment_3_1.xsd
web-facelettaglibrary_2_2.xsd
web-facesconfig_2_2.xsd
````

See here http://xmlns.jcp.org/xml/ns/javaee#7

**Comment by tandraschko** [comment]
PF works fine from EE5.0 to 10, no neee to upgrade anything for now
