### ISSUE TITLE
<p:socket> does not support rendered property

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#852]
Hi, it would be useful to have a rendered property in p:socket as i have a case where the websocket should not be used in certain circumstances 

```
<c:if test="#{useWebsocket}">
    <p:socket .... />
</c:if>
```

nicer:

```
 <p:socket ....rendered="#{useWebsocket}" />     
```

**Comment by tandraschko** [comment]
Are you sure that it isn't supported? rendered is a default attribute which should work on every component.

**Comment by cnsgithub** [comment]
Sorry - it seems to be working now with 5.3.1 , don't know what was wrong before
