### ISSUE TITLE
CSP: Report only

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#8520]
In large web applications it might be difficult to introduce Content Security Policy directly. Instead there might be the requirement that remaining CSP violations should be reported to an adequate endpoint as a start. Then the production system will show up problems regarding CSP even in the last corner of the webapp, driven by the users.

Unfortunately, PrimeFaces does not support the header `Content-Security-Policy-Report-Only` yet.

It would be nice to have additional context params to configure reporting, e.g. `primefaces.CSP_REPORT_ONLY` and primefaces.CSP_REPORT_ENDPOINT'.

**Comment by tandraschko** [comment]
as discussed in the PR, please provide a new PR when you have time.

We should have 4 possible modes:

- CSP off (CSP=false)
- CSP on (CSP=true)
- CSP on with reporting (CSP=true, CSP_POLICY="report-uri /csp-violation-report-endpoint/")
- CSP off but reporting only

so the 4) is the only new mode now
and i think CSP="reportOnly" and CSP_REPORT_ONLY_POLICY="report-uri /csp-violation-report-endpoint/" is fine

**Comment by melloware** [comment]
OK submitted PR basically handling the 4th case ` CSP="reportOnly" and CSP_REPORT_ONLY_POLICY="report-uri /csp-violation-report-endpoint/"`
