### ISSUE TITLE
Chip: XSS through label attribute

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#8527]
First of all: It had been a long time since I was active and contributed some things like OWASP encoder to achieve better XSS mitigation. Now I'm a bit disappointed, the OWASP encoder is still in place, but it's not used consistently in new components. This issue describes the third XSS vulnerability I've identified in just a few minutes. :-(

**Describe the defect**
The attribute `label` of `p:chip` is subject to XSS.

**Environment:**
 - PF Version: _12.0.0_

**To Reproduce**
Set the label of `p:chip` like this (e.g. in chip.xhtml of showcase)

`<p:chip label="Apple&lt;script&gt;alert('foo');&lt;/script&gt;" icon="pi pi-apple" styleClass="p-mr-2"/>`

**Expected behavior**
The value should be escaped properly with `EscapeUtils.forHtml` or `ResponseWriter.writeText`

```

**Comment by melloware** [comment]
I agree with you these were written offline and just committed without a chance for much peer review by the community.  I will fix all these.

**Comment by fcorneli** [comment]
Now that these XSS are "out in the open", could these fixed be back ported to 11 please?

**Comment by tandraschko** [comment]
thats up to PrimeTek (cc @mertsincan), thats all we can do
however, you can let it port via PrimeFaces PRO
