### ISSUE TITLE
Stack: XSS through menuItem value

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#8528]
Another one...

**Describe the defect**
The attribute `value` of `p:menuItem` inside `p:stack` is subject to XSS.

**Environment:**
 - PF Version: _12.0.0_

**To Reproduce**
Use `p:stack` like this (e.g. in stack.xhtml of showcase)

```
<p:stack icon="/resources/demo/images/dock/stack.png" expanded="true">
    <p:menuitem value="Home&lt;script&gt;alert('foo');&lt;/script&gt;" icon="/resources/demo/images/dock/home.png"/>
    <p:menuitem value="Music" icon="/resources/demo/images/dock/music.png"/>
    <p:menuitem value="Video" icon="/resources/demo/images/dock/video.png"/>
    <p:menuitem value="Email" icon="/resources/demo/images/dock/email.png"/>
    <p:menuitem value="Portfolio" icon="/resources/demo/images/dock/portfolio.png"/>
</p:stack>
```

**Expected behavior**
The value should be escaped properly in `StackRenderer` with `EscapeUtils.forHtml` or `ResponseWriter.writeText`

**Comment by ravihariharan** [comment]
@mertsincan can this fix also be applied to to Elite 7.0.27 ? 

Issue ID :  sonatype-2022-1518
