### ISSUE TITLE
DataTable: Sorting/Filtering/Paginator etc. not work anymore after updating PF extension from 11.0.0 to 11.0.2

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8539]
It looks that PF-Extensions Version > 11.0.0 breaks the datatable functionality of the PF snapshot. Would be great if somebody could have a look at this. 

Side-note: I am using Payara 5.2021.8. 

Many thanks in advance.

**Comment by tandraschko** [comment]
Please create a Extensions issue then

**Comment by tuerker** [comment]
sorry. by default i was here. will place a PF extensions issue.

**Comment by melloware** [comment]
I can't imagine what in PFE would cause your Datatable to break so please create a PF Test Reproducer.

**Comment by tuerker** [comment]
linkage to the PF extension issue https://github.com/primefaces-extensions/primefaces-extensions/issues/750 to avoid similar future questions
