### ISSUE TITLE
SelectOneMenu: XSS-Vulnerable

### ISSUE THREAD

**Issue by ohlsen3000** [primefaces/primefaces#8547]
The Attribute `data-label` of Items within the SelectOneMenu is not escaped correctly and thus makes XSS possible.

**Environment:**
 - PF Version: 10.0.0
 - JSF + version: Mojarra 2.2.20 
 - Affected browsers: ALL

**To Reproduce**
1. Create a SelectOneMenu with the following items: 
2. `"<script>alert(\"XSS\")</script>"`
3. `" \" onmouseover=\"alert(document.domain) "`
4. `"<img src=0 onerror=alert(document.domain)>"`
5. Open select
6. Hover items
7. Script content is executed

**Expected behavior**
Labels and attributes within component are escaped correctly

**Example XHTML**
```html
 <h3>Standard:</h3>
    <p:selectOneMenu value="#{testBean.classOption}">
        <f:selectItems value="#{testBean.list}" var="class" itemValue="#{class}"/>
    </p:selectOneMenu>
    <pre>no itemLabel, itemLabelEscaped</pre>
    <em>mouseover-Item cause XSS!</em>

    <h3>Own Escaping:</h3>
    <p:selectOneMenu value="#{testBean.classOption}">
        <f:selectItems value="#{testBean.list}" var="class" itemValue="#{class}"
                       itemLabelEscaped="false"
                       itemLabel="#{escapeUtils.forHtml(class)}"/>
    </p:selectOneMenu>
    <pre>itemLabelEscaped="false" itemLabel="escapeUtils.forHtml(class)"</pre>
    <em>alert-Item cause XSS!</em>

    <h3>Double Escaping:</h3>
    <p:selectOneMenu value="#{testBean.classOption}">
        <f:selectItems value="#{testBean.list}" var="class" itemValue="#{class}"
                       itemLabelEscaped="true"
                       itemLabel="#{escapeUtils.forHtml(class)}"/>
    </p:selectOneMenu>
    <pre>itemLabelEscaped="true" itemLabel="escapeUtils.forHtml(class)"</pre>

    <h3>Experimental:</h3>
    <p:selectOneMenu value="#{testBean.classOption}">
        <f:selectItems value="#{testBean.list}" var="class" itemValue="#{class}"
                       itemLabelEscaped="true"
                       itemLabel="#{escapeUtils.forHtmlAttribute(class)}"/>
    </p:selectOneMenu>
    <pre>itemLabelEscaped="true" itemLabel="escapeUtils.forHtmlAttribute(class)}"</pre>
```

**Example Bean**
```java
@Component
@ViewScoped
public class TestBean {

    private List<String> list;

    private String classOption;

    public List<String> getList() {
        list = new ArrayList<>();
        list.add("boring");
        list.add("<script>alert(\"XSS\")</script>");
        list.add(" \" onmouseover=\"alert(document.domain) ");
        list.add("<img src=0 onerror=alert(document.domain)>");
        return list;
    }

    public void setList(List<String> list) {
        this.list = list;
    }

    public String getClassOption() {
        return classOption;
    }

    public void setClassOption(String classOption) {
        this.classOption = classOption;
    }
}
```

**Comment by fcorneli** [comment]
Guess this one was already fixed within 10.0.9. See also:
https://github.com/primefaces/primefaces/issues/7878
https://github.com/primefaces/primefaces/issues?q=label%3A10.0.9+is%3Aclosed

**Comment by tandraschko** [comment]
before creating a issue, please always try the newest version
might already be fixed.

**Comment by melloware** [comment]
Runnable reproducer its still an issue on PF11:
[pf-8547.zip](https://github.com/primefaces/primefaces/files/8223375/pf-8547.zip)

**Comment by melloware** [comment]
OK its not an issue the test case that is alerting is his section #2 which is `itemLabelEscaped="false"` but that is because he is instructing it to be false.   

As mentioned this is already fixed in 10.0.9 and 11.0.0.

**Comment by arnis87** [comment]
Could this be a a reason why `&nbsp;` is shown in the label for `SelectOneMenu` when there is number formatter involved that uses grouping separator of `NBSP` or char 160 instead of regular space to make sure the renderer does not break between grouping in numbers?
One of such locales is nb-NO where 1000 becomes formatted as "1[NBSP]000" but this `PrimeFaces.escapeHTML` seems to replace the NBSP character with &nbsp; resulting in 1&nbsp;000 being rendered on the page for the select label

**Comment by arnis87** [comment]
> See #9336 for a monkey patch to fix your issue

Yes, the patch seems to work for now. Thanks
