### ISSUE TITLE
BlockUI: refactor + root element should not be moved in DOM

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8548]
Currently the BlockUI script is a bit weird as it moves the root element to the target. Sometimes its also cloned, which should not be required.

I think it needs a bit of refactoring, also the code itself reads weird as it covers multiple block targets but the code is hard do unterstand.

This example shows the weird behavior:
```
        <h1>BLOCK UI Null Widget</h1>
        <h:form id="frmTest">
            <h:panelGroup id="panel">
                Panel
            </h:panelGroup>
            <p:blockUI widgetVar="blockPanel" block="panel" blocked="true"/>
            <p:commandButton value="Unblock"
                             update="panel"
                             oncomplete="PF('blockPanel').hide()"/>
        </h:form>
```

BlockUI is actually on the same level as commandButton and panelGroup but our BlockUI script moves the conent into the panel.
How does this work with multiple block target? It will probably duplicate the root element, which means we have multiple DIVs with the same ID, which is also wrong

- [x] Format code for readability
- [x] When using multiple targets prevent duplicate ID's in the DOM
- [x] Do not put the DOM element inside the Target (fixed NULL widget issue)
- [x] Test with showcase and reproducers

**Comment by tandraschko** [comment]
anyone interessted in doing this?

**Comment by melloware** [comment]
I can take a shot at it and you can review it and help me make it correct.  I totally agree with your  assessments of the problems!

**Comment by melloware** [comment]
OK @jepsar and others I know when this issue was introduced: https://github.com/primefaces/primefaces/issues/5787

Previously it wasn't ever calling `super` in the constructor so it was never registering itself for the `remove` event which is probably why this is happening now and wasn't always happening.

**Comment by melloware** [comment]
Confirmed that by using `target="panel1 panel2"` where you have two targets @tandraschko is correct it was duplicating ID's.

![image](https://user-images.githubusercontent.com/4399574/157736899-3e6d91ab-8cde-415b-a898-154d4e09e912.png)

**Comment by melloware** [comment]
OK got all of it working properly!
