### ISSUE TITLE
Primefaces: Datatable / ColumnToggler Problems

### ISSUE THREAD

**Issue by tvhdev** [primefaces/primefaces#8551]
**Describe the defect**

In our portlet we're using Primefaces' datatable widget to display a simple list of records. The column toggler is configured so the user is able to customize the visibility of the columns. 
![column toggler fields1](https://user-images.githubusercontent.com/29280823/157732904-1c6b18fe-2e9e-4c74-9fe2-3a21262b8b0a.png)
After the user within the organizational site /group/companyname clicks on a simple link to return to the user's private page /group/guest, somehow the column toggler fields are shown in the top left corner.
![column toggler fields2](https://user-images.githubusercontent.com/29280823/157732908-d291d9fb-3e83-4e85-bace-c310aac03f8e.png)

**Reproducer**
Create a liferay private page /group/guest and an organizational site /group/companyname with one page. The organizational site's page contains the primefaces portlet. The Link "Zurück" in the organizational site redirects to the user's private page /group/guest

**Environment:**
 - PF Version: 11.0.0
 - PF Theme: Default
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: All
 - Liferay 7.4-ga13

**To Reproduce**
1. Configure a liferay 7.4-ga13 environment
2. Create a Primefaces Portlet using the https://faces.liferay.dev/ toolbox
3. Create a liferay "private page" and an "organizational" site with one page and a "Zurück" Link
4. Insert the Primefaces Portlet into the organizational site's "first" page.
5. Klick on "Zurück"
6. See error

If you remove the column toggler, no problems occur at all. The column togglers code as follows

`      				    
...
<p:columnToggler datasource="schutzrechte" trigger="toggler">
		                    	<p:ajax event="toggle" listener="#{schutzrechteHelper.onColumnToggle}" update=":form:msgs"/>
		                    </p:columnToggler>		                    
...
`

**Expected behavior**
No residues of the column togglers entries are shown.

**Comment by tandraschko** [comment]
Can you replicate in our primefaces-test Project using Jetty?
I think nobody will help you with liferay here, maybe better use payed support

**Comment by tvhdev** [comment]
Hello, you're probably right that it could be a liferay related problem, maybe the "faces bridge" is buggy, i will open a ticket in liferay's JIRA tracker then. I will try the primefaces-test Project using my portlet and i will get back to you.

**Comment by melloware** [comment]
OK also there was a LifeRay problem reported on the forums and the user responded back that "LifeRay has not updated for PF11 yet"

See: https://forum.primefaces.org/viewtopic.php?f=3&t=71443
