### ISSUE TITLE
selectOneMenu: Does not show selectItems if var attribute is used

### ISSUE THREAD

**Issue by r-mueller** [primefaces/primefaces#8553]
**Describe the defect**
After moving from Primefaces 6 to Primefaces 11 selectOneMenu stopped showing selectItems if attribute var is set.

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8233425/primefaces-test.zip)

**Environment:**
 - PF Version: 11.0.0 and current master
 - PF Theme: See reproducer
 - JSF + version: See reproducer
 - Affected browsers: Edge 98.0.1108.62 (64-Bit) and Firefox 96.0.2 (64-Bit)

**To Reproduce**
See reproducer.

**Example XHTML**
```html
<h:form id="frmTest">
    <p:selectOneMenu id="novar"
                    value="#{testView.item}">
        <f:selectItem itemLabel="Select" itemValue=""/>
        <f:selectItems id="novaritems" value="#{testView.items}"
                       var="novaritem" 
                       itemLabel="#{novaritem}" 
                       itemValue="#{novaritem}"/>
    </p:selectOneMenu>

    <p:selectOneMenu id="withvar"
                    value="#{testView.item}"
                    var="it">
        <f:selectItem itemLabel="Select" itemValue=""/>
        <f:selectItems id="varitems" value="#{testView.items}"
                       var="varitem" 
                       itemLabel="#{varitem}" 
                       itemValue="#{varitem}"/>
    </p:selectOneMenu>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    
    private String string;
    private String item;
    private Integer integer;
    private BigDecimal decimal;
    private LocalDateTime localDateTime;
    
    @PostConstruct  
    public void init() {
        string = "Welcome to PrimeFaces!!!";
    }

    public List<String> getItems() {
        return Arrays.asList("A","B","C","D","E");
    }
}
```

**Comment by jepsar** [comment]
Shouldn't it be like this?
```xhtml
        <f:selectItems id="novaritems" value="#{testView.items}"
                       var="novaritem" 
                       itemLabel="#{novaritem}" 
                       itemValue="#{novaritem}"/>
```

**Comment by r-mueller** [comment]
@jepsar  You are right. Correcting it does not change behaviour though. I update code snippets. Attached corrected reproducer zip.

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8233410/primefaces-test.zip)
.

**Comment by tandraschko** [comment]
var is build for custom content - and you dont have custom content in your example; check the showcase

**Comment by r-mueller** [comment]
@tandraschko Sure then it was wrong usage in our app. We had var attribute defined but in fact did not use it. Closing issue again. Thanks.
