### ISSUE TITLE
Datatable update and cellEdit not working

### ISSUE THREAD

**Issue by vogl91** [primefaces/primefaces#857]
if some rows in a dataTable are calculated and some can be edited update does not work correctly on cellEdit event. If focus remains on table update is broken. (can be archieved by using tab key to focus next column or by click on next column)

Example:
https://github.com/HerrDesSchwachsinns/SO-Table

**Comment by melloware** [comment]
I can't reproduce.  If you still feel it is an issue please test with 9.0-SNAPSHOT and I can reopen the ticket.
