### ISSUE TITLE
Timeline: TimelineModel update() defect

### ISSUE THREAD

**Issue by kneringerjohann** [primefaces/primefaces#8577]
**Describe the defect**
update() function in TimelineModel does not work any more.
The component updates the UI, but the events in the model (model.getEvents()) are not being changed.
This did work in PF 8.

Looking into sourcecode of PF 8, the update method looks like this:

    
    public void update(TimelineEvent<E> event, TimelineUpdater timelineUpdater) {
        int index = getIndex(event);
        if (index >= 0) {
            events.set(index, event);

            if (timelineUpdater != null) {
                // update UI
                timelineUpdater.update(event);
            }
        }
    }

In Primefaces 10 this method was adjusted like this:

    public void update(TimelineEvent<E> event, TimelineUpdater timelineUpdater) {
        if (timelineUpdater != null) {
            // update UI
            timelineUpdater.update(event);
        }
    }

So the events of the model are not getting adjusted any more....Why is this?

I can get the correct behaviour by calling model.delete and model.add instead of model.update.

**Environment:**
 - PF Version: _10.0.0_ , _11.0.0_
 - JSF + version: _e.g. Mojarra 2.3
 - Affected browsers: ALL_

**Comment by melloware** [comment]
It was done with this ticket: https://github.com/primefaces/primefaces/issues/6841

Not sure why I think everyone assumed it was deprecated?

**Comment by kneringerjohann** [comment]
so could we bring the functionality back?

we could do something like this:


    public void update(TimelineEvent<E> event, TimelineUpdater timelineUpdater) {
        int index = IntStream.range(0, events.size())
                .filter(i -> event.equals(events.get(i)))
                .findFirst().orElse(-1);

        if (index >= 0) {
            events.set(index, event);

            if (timelineUpdater != null) {
                // update UI
                timelineUpdater.update(event);
            }
        }
    }

What do you think?

**Comment by melloware** [comment]
Sure do you want to submit a PR?

**Comment by kneringerjohann** [comment]
done
https://github.com/primefaces/primefaces/pull/8578

**Comment by melloware** [comment]
Thanks for the report and the PR its merged.
