### ISSUE TITLE
Gmap: add text label

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#8579]
With PrimeFaces gmap overlays we are able to draw polygons and markers but no text labels.
We would like to draw a text label on top of a polygon.

**Marker with Label**

This active google repo _MarkerWithLabel_ class could be used by just hiding the Marker icon like in this jsfiddle the  so we just have a label: http://jsfiddle.net/amgqn0Lv/

https://github.com/googlemaps/js-markerwithlabel

**MapLabel**

In google archive there is also just a "MapLabel" class but "MarkerWithLabel" seems superior.

https://github.com/googlearchive/js-map-label

https://cdn.jsdelivr.net/gh/geocodezip/v3-utility-library@master/archive/maplabel/src/maplabel-compiled.js
https://cdn.jsdelivr.net/gh/geocodezip/v3-utility-library@master/archive/maplabel/src/maplabel.js

*Example*: https://stackoverflow.com/questions/27338998/how-to-add-text-label-in-google-map-api

**Comment by melloware** [comment]
Marked as needs investigation as waiting to hear back from @djmj

**Comment by melloware** [comment]
Going to close for now. Will re-open if OP reports back

**Comment by erickdeoliveiraleal** [comment]
I tried using it but it didn't work. It didn't appear as text labels. Is there something else that needs to be done? It would be great if there was a working example in the showcase. @djmj

**Comment by erickdeoliveiraleal** [comment]
@melloware can you reopen? I can't make it work

**Comment by melloware** [comment]
Yep I think i can fix this for 15.0.16

**Comment by djmj** [comment]
Thank you and looking forward to test it in a new release.
