### ISSUE TITLE
Tree: Submitting two selection tree´s inside a form leads to losing selection on the second tree and wrong selection on the first tree

### ISSUE THREAD

**Issue by arditsaliji** [primefaces/primefaces#8581]
**Describe the defect**
I have two selection tree´s inside a ui:repeat in a form. When i submit the form and the tree´s get processed, the selection of the second tree moves to the selection of the first tree and the selection of the second tree is set to null. The id-attribute of the tree is the same as it is inside a ui:repeat, but the client-id´s are different.

**Environment:**
PF Version: any
PF Theme: any
JSF + version: any
Affected browsers: any

**To Reproduce**
1. Just create multiple selection tree´s inside an ui:repeat and give an id to the tree inside the ui:repeat. The ui:repeat in turn should be inside a form, as I want to submit the form and process the form with the selection of the tree´s
2. Select an item for the first tree
3. Select an item for the second tree

**Expected behavior**
The expected behaviour should be, that every tree has set the right selected node. But as mentioned, the first tree get´s the selection of the second tree und the selected node of the second tree gets null.

**Example XHTML**
```html
<h:form id="testform">
            <ui:repeat id="trees" value="#{treeSelectionView.trees}" var="tree">
                <p:tree id="MY_TREE" value="#{tree.root}" var="doc"
                        selectionMode="single"
                        selection="#{tree.selectedNode}">
                    <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                        <h:outputText value="#{doc.name}"/>
                    </p:treeNode>
                    <p:treeNode type="app" icon="pi pi-save">
                        <h:outputText value="#{doc.name}"/>
                    </p:treeNode>
                    <p:treeNode type="document" icon="pi pi-file">
                        <h:outputText value="#{doc.name}"/>
                    </p:treeNode>
                    <p:treeNode type="excel" icon="pi pi-file-excel">
                        <h:outputText value="#{doc.name}"/>
                    </p:treeNode>
                    <p:treeNode type="travel" icon="pi pi-file-pdf">
                        <h:outputText value="#{doc.name}"/>
                    </p:treeNode>
                    <p:treeNode type="picture" icon="pi pi-image">
                        <h:outputText value="#{doc.name}"/>
                    </p:treeNode>
                    <p:treeNode type="video" icon="pi pi-video">
                        <h:outputText value="#{doc.name}"/>
                    </p:treeNode>
                </p:tree>
            </ui:repeat>
        </h:form>


        <p:commandButton id="submitTreesButton" widgetVar="submitTreesButtonVar"
                         value="Submit"
                         process="testform"
                         actionListener="#{treeSelectionView.saveTrees()}"
                         partialSubmit="true"
        />
```

**Example Bean**
```java
@Named
@ViewScoped
public class TreeSelectionView implements Serializable {

    @Inject
    private TreeSelectionService treeSelectionService;

    private List<DocumentTreeSelectionModel> trees = new ArrayList<>();

    @PostConstruct
    public void init() {
        DocumentTreeSelectionModel tree1 = new DocumentTreeSelectionModel(treeSelectionService.createDocuments());
        DocumentTreeSelectionModel tree2 = new DocumentTreeSelectionModel(treeSelectionService.createCheckboxDocuments());
        trees.add(tree1);
        trees.add(tree2);
    }

    public List<DocumentTreeSelectionModel> getTrees() {
        return trees;
    }

    public void saveTrees() {
        TreeNode selectedTreeNode1 = trees.get(0).getSelectedNode();
        TreeNode selectedTreeNode2 = trees.get(1).getSelectedNode();
        // NOW HERE IS WRONG DATA INSIDE THE SELECTED TREE NODES FOR EACH TREE
    }
}
```

**DocumentTreeSelectionModel which is used in my example bean**
```java
public class DocumentTreeSelectionModel {

    private TreeNode selectedNode;
    private TreeNode root;

    public DocumentTreeSelectionModel(TreeNode root) {
        this.root = root;
    }

    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }

    public TreeNode getRoot() {
        return root;
    }
}
```

Document.java and DocumentService.java are used from https://www.primefaces.org/showcase/ui/data/tree/selection.xhtml?jfwid=c7d3f

**Comment by melloware** [comment]
@FlipWarthog care to look at this one?  Have a feeling the JS selectors are not specific enough?

**Comment by jepsar** [comment]
Please note that we'll have to migrate changes to https://github.com/primefaces/primefaces/pull/8350

I thought PrimeTek was going to review the open PRs some Mondays ago.

**Comment by FlipWarthog** [comment]
@melloware Sure, I can take a look.

@jepsar I'll keep that in mind if I track down the issue. Does your PR affect behavior at all, or is it safe to assume if it's broke in 12.0.0-SNAPSHOT it's broke in your PR branch as well?

**Comment by jepsar** [comment]
There is no functional change, I only moved style classes

**Comment by FlipWarthog** [comment]
@arditsaliji Can you give a little more information about which JSF implementation you're using? I noticed you listed "JSF + version: any" but I am not able to see the same behavior you're describing. I am, however, seeing different invalid behavior in both MyFaces and Mojarra running the primefaces-test reproducer.

@melloware in case you have any input, what I'm seeing is `updateSelection` in `UITree` being called a couple times, first with valid/expected results immediately followed by calls with null values here:
```java
selectionVE.setValue(context.getELContext(), selection);
```

I threw in some additional logging in both the `init()` and `saveTrees()` methods of `TreeSelectionView` and `init()`, which is PostConstruct, is being called more times than I'd expect.

**Comment by melloware** [comment]
Can you attach your reproducer ZIP file without the `target` directory in it please?

**Comment by FlipWarthog** [comment]
It's currently configured to use 12.0.0-SNAPSHOT rather than 11.0.0 release.
[primefaces-test-8581.zip](https://github.com/primefaces/primefaces/files/8352036/primefaces-test-8581.zip)

**Comment by lagar84** [comment]
Is this maybe related to #3812 ?

**Comment by FlipWarthog** [comment]
@lagar84 I think you're absolutely right. Rapster even mentioned that the issue existed with Tree at the time. I'll do a dive through that chain and the workaround mentioned in light of this ticket and see what I come up with. Thanks!

**Comment by FlipWarthog** [comment]
Okay, after realizing I had the wrong ViewScoped on my bean and correcting that, I was able to reference #3812 and can confirm that the following does work:
```xml
    <h:form id="testform">
        <c:forEach id="trees" items="#{treeSelectionView.trees}" var="tree" varStatus="loop">
            <p:tree id="MY_TREE-#{loop.index}" value="#{tree.root}" var="doc" selectionMode="single" selection="#{tree.selectedNode}">
                <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                    <h:outputText value="#{doc.name}" />
                </p:treeNode>
                <p:treeNode type="app" icon="pi pi-save">
                    <h:outputText value="#{doc.name}" />
                </p:treeNode>
                <p:treeNode type="document" icon="pi pi-file">
                    <h:outputText value="#{doc.name}" />
                </p:treeNode>
                <p:treeNode type="excel" icon="pi pi-file-excel">
                    <h:outputText value="#{doc.name}" />
                </p:treeNode>
                <p:treeNode type="travel" icon="pi pi-file-pdf">
                    <h:outputText value="#{doc.name}" />
                </p:treeNode>
                <p:treeNode type="picture" icon="pi pi-image">
                    <h:outputText value="#{doc.name}" />
                </p:treeNode>
                <p:treeNode type="video" icon="pi pi-video">
                    <h:outputText value="#{doc.name}" />
                </p:treeNode>
            </p:tree>
        </c:forEach>
        <p:commandButton id="submitTreesButton" value="Submit" process="@form"
            actionListener="#{treeSelectionView.saveTrees()}" />
    </h:form>
```

cc @melloware in case there's more digging to do.

**Comment by melloware** [comment]
Marking the ticket as workaround and closing it as the same reason PrimeTek gave before...

From PrimeTek: _"We cannot use such repeating components with *:repeat. This requires massive changes in components. That's why JSTL forEach is the ideal solution for this kind of work"_
