### ISSUE TITLE
AutoComplete: Empty items within panel have unnessary space

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#8582]
When typing within an autocomplete field with empty message and no results are returning, the autocomplete items have an unnecessary space.

**Environment:**
 - PF Version: 12.x.x, 11.0.2
 - Affected browsers: ALL

**To Reproduce**
1. Go to [AutoComplete Showcase](https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml)
2. Click within the field "Empty message"
3. Type "a"
4. The empty message shows up with an empty item container below with padding 

**Expected behavior**
An empty item container for autocomplete items should have no padding.

**Comment by pfumi** [comment]
Could be solved this way
```
body .ui-autocomplete-panel .ui-autocomplete-items:empty {
   padding: 0;
}
```

**Comment by melloware** [comment]
Yep your second one is more specific so it's much better

**Comment by melloware** [comment]
I assigned @mertsincan to review in case he wants to update the themes as well.
