### ISSUE TITLE
DataTable: Sorting columns in reflow is wrong

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#8583]
**Describe the defect**
Selecting a column from the sorting menu on mobile screens for a datatable with `reflow=true`, sorts an other column instead of the selected column.

**Environment:**
 - PF Version: 12.x.x, 11.0.2
 - Affected browsers: ALL

**To Reproduce**
1. Go to [DataTable Crud](https://www.primefaces.org/showcase/ui/data/datatable/crud.xhtml)
2. Make the browser small enough, so the table shows responsive
3. Select from the sorting menu the entry "Code Ascending"
4. In the sorting menu the entry "Category Ascending" is shown, and the table is sorted by it

**Expected behavior**
Selecting a column to sort for should sort that column.

**Comment by pfumi** [comment]
I believe the problem is here
https://github.com/primefaces/primefaces/blob/1684d67555ec9fa7c825c3da3c85b14b63217e96/primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java#L1673
The returned map is a `HashMap`, so the order of the column headers is messed up.
If you look deeper into the method, you can see the initial map is here https://github.com/primefaces/primefaces/blob/1684d67555ec9fa7c825c3da3c85b14b63217e96/primefaces/src/main/java/org/primefaces/component/api/UITable.java#L277
The method `getSortableColumnHeaders` should return a `LinkedHashMap`, with the columns in the order they show up on the regular table.

**Comment by melloware** [comment]
Agreed want to submit a PR?

**Comment by pfumi** [comment]
I have not the time right now, I can provide a PR probably in the coming days. 
Feel free to fix it if you want :)

**Comment by melloware** [comment]
I will take care of it!

**Comment by pfumi** [comment]
I think we have to do more, the map from `table.getSortByAsMap()` returns allready the columns not in there real order.
I see two options
Sort the SortMeta values in `getSortableColumnHeaders`, see my commits here
https://github.com/pfumi/primefaces/commit/b247b0b5e075af015b9b003c9d5c9297b6c6cb22
https://github.com/pfumi/primefaces/commit/07c291ab7fd80e2cbe2138a5ffcbd59395fc11b7
OR
Use also a `LinkedHashMap` where the map is originally initialized, see my commits here
https://github.com/pfumi/primefaces/commit/0df8afc368253e714d2064a8aef17552db19f7d8
I think it also makes sense to do this for `initFilterBy`

@melloware What do you think?

**Comment by melloware** [comment]
PR submitted going to let the automation tests run.

**Comment by pfumi** [comment]
Perfect, thanks for your fast respond 👍
