### ISSUE TITLE
Tech Debt: Shading Commons IO

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8589]
**Description**
We originally shaded Commons IO classes so that way as Apache released new versions we would automatically get the bug fixes.

However because of major changes in the library new versions require us to shade more and more code to make it work so we have frozen our version in the pom.xml at 2.4.  Well if we are going to freeze the version there is no point in shading it anymore we should just bring in the shaded classes to the JAR.

It is only these 5 classes.

```
-rwxrwx---    1 Administ UsersGrp     11778 Jun 12  2012 FilenameUtils.class
-rwxrwx---    1 Administ UsersGrp     24168 Jun 12  2012 IOUtils.class
-rwxrwx---    1 Administ UsersGrp      2555 Jun 12  2012 BoundedInputStream.class
-rwxrwx---    1 Administ UsersGrp      5404 Jun 12  2012 ByteArrayOutputStream.class
-rwxrwx---    1 Administ UsersGrp      2649 Jun 12  2012 StringBuilderWriter.class
```

**Comment by tandraschko** [comment]
your first statement isnt completely true -> in general we shade to avoid dependencies for the user or copy classes

**Comment by melloware** [comment]
Agreed.  But for this one I think its time to unshade it and just copy and hide the classes.

**Comment by tandraschko** [comment]
As long we dont need a special fix, -1

**Comment by tandraschko** [comment]
i think even our current setup is broken in some cases
I will upgrade it now and in general we only need FilenameUtils to shade and this dependencies. I dont like to copy it, we would loose dependency-bot and we would also need to copy tests

I will also leave BoundedInputStream for now as it doesnt use any other class

**Comment by melloware** [comment]
Yep I was going to say While researching this we have a bug anyway.  It looks like we are using `import org.apache.commons.io.FileCleaningTracker;` in FileUploadFilter.java but not shading it.

**Comment by tandraschko** [comment]
thats ok as you need to add commons-fileupload, which has a dependency to commons-io

**Comment by melloware** [comment]
Ahhh that makes sense!
