### ISSUE TITLE
[process] selectOneMenu and selectBooleanCheckbox process every times into Datatable

### ISSUE THREAD

**Issue by Julienng** [primefaces/primefaces#859]
I have a Datatable with rowSelect and rowUnselect with something like:

``` html
<p:ajax event="rowSelect" global="false" async="true"
    process="@this"
    listener="#{ctrl.lc[ctrlKey].onRowSelect}" />
```

When I click on a row, the row is correctly selected but:
-  a process `@this` gonna process all the datatable & his children. Or I just want the `event.getObject()` of the `SelectEvent`

my solution here is to use the `partialSubmitFilter` to block every type of children component. I don't want to process them here, I just want to flag my selected row.

My SelectOneMenu and SelectBooleanCheckbox is always process with the table when I can exclude `InputText` and `Autocomplete`.

I try a lot of way to block them, like this:

```
partialSubmitFilter="#{'#'.concat(id)} > :not(:input) :not(.ui-selectonemenu .ui-widget) :not(.ui-chkbox .ui-widget)"

OR

partialSubmitFilter=":button"
to process only buttons of my datatable and exclude others.
```

but it still have no effect on the process of selectOneMenu and selectBooleanCheckbox.

---

My ideal solution for the rowSelect is to fire the event with a `@none` process because the event catch the selected row, so I don't need any process of component here. But this solution doesn't follow the MyFaces spec. But why? That seems legit to want to limit my process when I don't need any process because event handle everything for me.

**Comment by tandraschko** [comment]
You can add skipChildren=true on p:ajax.
