### ISSUE TITLE
DataExporter ExcelOptions are not applied

### ISSUE THREAD

**Issue by hink084** [primefaces/primefaces#8597]
The ExcelOptions are not applied to the XLSX spreadsheet when utilizing the DataExporter component.  

This can also be seen in the PrimeFaces ShowCase example: https://www.primefaces.org/showcase/ui/data/dataexporter/customizedDocuments.xhtml

**Reproducer**
primefaces-test.zip

**Environment:**
 - PF Version: 11.0.0
 - JSF: Mojarra 2.2.20
 - Affected browsers: ALL

**To Reproduce**
1. Build / Run attached Project
2. Click on 'Export'

**Expected behavior**
Excel cells to reflect the defined Excel Options - Italic, Red, Size 25 font

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8327988/primefaces-test.zip)

**Comment by melloware** [comment]
OK found and fixed the issue.  It was a POI change.  Somewhere along the lines POI changed from returning NULL to returning the default Font/Cellstyle

```java
        if (cell.getCellStyle() != null) {
            // don't apply style if cell already has one
            return cell;
        }
        ```

**Comment by hink084** [comment]
I apologize for the delayed response as I went on vacation right after I created this issue. I tested your changes with the submitted example project and can confirm they resolve the issue.  Thanks for all your work on this project!
