### ISSUE TITLE
Default SortOrder is ignored in DataTable at first click

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#86]
Details are available at;

Forum Post URL: http://forum.primefaces.org/viewtopic.php?f=3&t=25695

**Comment by sudheerj** [comment]
I can't replicate the issue on latest showcase.The first clicks changes the sort order when default sort order is applied on the datatable.

**Comment by cagataycivici** [comment]
Ok, closing then. Thanks.
