### ISSUE TITLE
Barcode: SVG not rendered correctly under Firefox

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#8603]
Showcase Barcode not displayed properly in ubuntu 20 firefox 98, woks fine in chrome

![image](https://user-images.githubusercontent.com/9069988/160546479-c107a9a2-0c7f-491c-a5f0-0c7558b31ab4.png)

(https://www.primefaces.org/showcase/ui/multimedia/barcode.xhtml?jfwid=a2e0e)

**Comment by melloware** [comment]
Its because of this issue: http://barcode4j.sourceforge.net/changes.html#version_2.1

You can fix it by adding this to your pom.xml

```xml
    <repositories>
        <repository>
            <id>primefaces</id>
            <name>PrimeFaces Maven Repository</name>
            <url>https://repository.primefaces.org</url>
            <layout>default</layout>
        </repository>
    </repositories>
```

then change your dependency to this:

```xml
<dependency>
            <groupId>net.sf.barcode4j</groupId>
            <artifactId>barcode4j-light</artifactId>
            <version>2.1</version>
</dependency>
```

cc @FlipWarthog as this came up on Discord forums as well.

**Comment by melloware** [comment]
You can also use this GitHub fork which is on 2.3 but its not in Maven Central.

https://github.com/metanorma/barcode4j/packages/169266

**Comment by tandraschko** [comment]
should we look for another dependency?

**Comment by melloware** [comment]
probably or I thought about publishing the latest one with all the bugfixes under PFE or my Melloware Maven Central account.  Thoughts?  Seems like this library is pretty specific and does what it does well just had 1 or two bugs in it that have been fixed.

**Comment by melloware** [comment]
Or switching to `zxing` according to this article: https://www.baeldung.com/java-generating-barcodes-qr-codes
