### ISSUE TITLE
Gmap: Marker allow label styling to use FA / prime icons

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#8609]
With javascript we can do something like this which gives great flexibility to render icons.

	 	 var label = marker.getLabel();
	 	 label.fontFamily = 'Fontawesome';
		 label.fontSize = '1.4em';
		 label.fontWeight = 'normal';

It would be great if this "label" is accessible from the java _Marker_ class.

**Comment by melloware** [comment]
Please review the PR.

**Comment by melloware** [comment]
Doesn't this also fix your other issue: https://github.com/primefaces/primefaces/issues/8579 because you can now set `getMarker().setText("primefaces");` to set the label.

**Comment by djmj** [comment]
Much thanks for your quick reply. We hope to check this next week and will also check if it works for #8579

**Comment by melloware** [comment]
Yes definitely let me know!

**Comment by djmj** [comment]
Already forgot about this. But i guess it does not work in v15 cause in:

`GMapRenderer.encodeMarker(...)` the new _MarkerLabel_ is not encoded in the javascript / json markup described here: 

https://github.com/googlemaps/js-markerwithlabel

On client side it will need the developer to add the js library of google like described there.


https://github.com/primefaces/primefaces/blob/4e941bd8af39e8515874de84cbfdda4b0d140606/primefaces/src/main/java/org/primefaces/component/gmap/GMapRenderer.java#L208

**Comment by melloware** [comment]
we probably need to update the docs to show a Marker With Label example and what JS you need to add to the page: https://primefaces.github.io/primefaces/15_0_0/#/components/gmap?id=gmap

**Comment by djmj** [comment]
That would be nice.

Currently it can already be done using _Marker.setIcon(String imageURL)_. I used this with custom PNG files instead of font-awesome which was enough for us.

I am not even sure if a separate js library is needed then for a simple label.

https://developers.google.com/maps/documentation/javascript/reference/marker?hl=de#MarkerOptions.label

Further `Marker` is marked as deprecated since 2024 for `AdvancedMarkerElement` which allows `children` property. Presumabely to render custom content.

https://developers.google.com/maps/documentation/javascript/reference/advanced-markers?hl=de#AdvancedMarkerElement.content
