### ISSUE TITLE
p:columnToggler hidden columns reappear after filtering in lazy tables

### ISSUE THREAD

**Issue by jplette** [primefaces/primefaces#861]
When I use the columnToggler in a lazy loaded table, the hidden columns reappear when filtering the data.
Only the th are set to ui-helper-hidden class and not the td fields
This happens in Version 5.2 and 5.3

**Comment by melloware** [comment]
@tandraschko you can close this bug as it is explained by Optimus Prime in this blog post...

https://www.primefaces.org/stateful-column-toggler/

**Comment by jxmai** [comment]
Duplicate as #1678, #1548, #217, #96

**Comment by tandraschko** [comment]
Thanks!
