### ISSUE TITLE
InputNumber: onblur triggers internally onchange, also without changing the input

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8610]
- focus val2
- change the value, focus val1 via shift-tab
- val2 will send a AJAX request and update `@form` (thats all correct!)
- now val1 already has the focus
- leave focus of val1
- val1 sends AJAX request - but the value hasn been changed; trigger is autonumeric.js ln 6004

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

    <h:form id="form">
        <p:inputNumber id="val1" value="#{testController.val1}">
            <p:ajax process="@this" update="@none" />
        </p:inputNumber>
        <p:inputNumber id="val2" value="#{testController.val2}">
            <p:ajax process="@this" update="@form" />
        </p:inputNumber>
    </h:form>

</h:body>
</html>
```

```
package org.primefaces.showcase.convert;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestController implements Serializable {

    private Double val1;
    private Double val2;

    @PostConstruct
    public void init() {
        val1 = 30000d;
        val2 = 30000d;
    }

    public Double getVal1() {
        return val1;
    }

    public void setVal1(Double val1) {
        this.val1 = val1;
    }

    public Double getVal2() {
        return val2;
    }

    public void setVal2(Double val2) {
        this.val2 = val2;
    }
}

```

**Comment by melloware** [comment]
So should we fix the core component here to make it smarter?

```js
      if (this.rawValue !== this.rawValueOnFocus) {
        this._triggerEvent(AutoNumeric.events["native"].change, e.target);
      }
```

**Comment by tandraschko** [comment]
Thats the question!
Currently it seems that this bug only ocurs when updating the widget
so maybe we also can just somehow init/refresh the autonumeric state

or we switch back to update the hiddenInput via onchange and check old<>newValue in this listener, before even throw a onchange to the visible input
But it think using keypress to copy the value was by design

**Comment by melloware** [comment]
ok let me look and see if I we can do something without touching AutoNumeric like initialize that rawValueOnFocus on refresh.

**Comment by melloware** [comment]
I submitted AutoNumeric PR: https://github.com/autoNumeric/autoNumeric/pull/735

But I am looking for a fix we can do in just PF code for now.

**Comment by melloware** [comment]
I had made a similar fix in the past in PF: https://github.com/primefaces/primefaces/issues/6940

**Comment by tandraschko** [comment]
Looks good, thank you!
