### ISSUE TITLE
DataTable: Not displayed when utilizing Reflow

### ISSUE THREAD

**Issue by hink084** [primefaces/primefaces#8614]
**Description:**
DataTables with "reflow=true" are not shown when nested within an element that contains "style=display: none;".   When attempting to show the hidden element, the style attribute on the DataTable is set to: _**null;visibility:hidden;**_

@melloware, I believe this bug was introduced while attempting to resolve Issue: #7050, #7038 with Commit: 52071270f5f710b0add34fdd4748ac1174b66a4d 

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8384042/primefaces-test.zip)

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme: _Saga_
 - JSF + version: _Mojarra 2.2.20_
 - Affected browsers: _ALL_

**To Reproduce**
1. Build / Run the attached project.
2. Click on 'Show Section'
3. See bug

**Expected behavior**
I'd expect both the DataTable with "reflow=true" and without "reflow" to be shown.

**Actual behavior**
Only the table without "reflow=true" is shown.

**Example XHTML**
```html
<p:commandButton onclick="$('#section').show();" type="button" value="Show Section"/>
<div id="section" style="display: none;">
    <h1>Reflow:</h1>
    <p:dataTable reflow="true" ...>
    ...
    </p:dataTable>

    <h1>No Reflow:</h1>
    <p:dataTable ...>
    ...              
    </p:dataTable>
</div>
```
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8384042/primefaces-test.zip)

**Comment by melloware** [comment]
Workaround attached:
[pf-8614.zip](https://github.com/primefaces/primefaces/files/8389165/pf-8614.zip)

Just do this ` onclick="PF('tblReflow').jq.css('visibility', 'visible');$('#section').show();"`

However @tandraschko I think there is a bigger issue here I don't quite get. The Datatable `_render` method is NEVER called so there is actually a bigger bug here than just this.   Basially nothing in the `_render` method gets called so this means in the scenario above where it starts `display:none` none of the setup code for sticky, scrolling etc would ever get set up.

I have a breakpoint in `_render` and it never gets called because in `renderDeferred` the `jq.is(":visible")` is of course false.

**Comment by hink084** [comment]
I've created another reproducer to highlight the bigger issue @melloware mentions above and to better show what I describe below.

**Reproducer 2**
[pf-8614-test-2.zip](https://github.com/primefaces/primefaces/files/8395469/pf-8614-test-2.zip)

It appears that the PrimeFaces `renderDeferred()` function within `core.widget.js` will only defer rendering for components that are wrapped with an element containing the `.ui-hidden-container` CSS class. This CSS class is defined within components that utilize a container element such as the AccordionPanel, ConfirmDialog, TabView, etc.  

In other words, it doesn't appear the `renderDeferred()` function is expecting the developer to manually wrap a component with an HTML element and set `display:none`.  If that were to occur, as in [primefaces-test.zip](https://github.com/primefaces/primefaces/files/8384042/primefaces-test.zip), then the `renderDeferred()` function will not call `_render()` because `this.jq.is(':visible')` is `false`.  But it will never call `_render()` because it does not defer rendering since there is no parent element containing the `.ui-hidden-container` class.  

If you were to add the `.ui-hidden-container` CSS class to a parent DIV element with `display:none` to simulate a hidden container for the component then there also needs to be an event that triggers the deferred rendering.  For an example, the `accordion.js` file has a function, `postTabShow()`, that calls `PrimeFaces.invokeDeferredRenders(this.id)` --> `render()` --> `_render()` on all of the visible child components of the accordion container.

There are a few of options that would work for a temporary workaround:

1. Call `PrimeFaces.invokeDeferredRenders('containerId')` after calling `$('#containerId').show()` - the container element must contain the `.ui-hidden-container` CSS class.
2. Call `PF('widgetVar').init(PF('widgetVar').cfg)` after calling `$('#containerId').show()`
3. Call `PF('widgetVar').render()` after calling `$('#containerId').show()`

**Comment by melloware** [comment]
Excellent summary. I am wondering if we can do something clever like if you added on your DIV a class like `ui-deferred`.

Then in our code code we could add something along these lines of subsribe all `ui-deferred` elements like...

```js
$('.ui-deferred').on('show', function () { invokeDeferredRenderers()}));
```

Something like that.  Long discussion on Stack Oveflow how to subscribe to the "show" event https://stackoverflow.com/questions/1225102/jquery-event-to-trigger-action-when-a-div-is-made-visible

**Comment by hink084** [comment]
I believe something like that would work as long-term solution.  I know components like the `p:confirmDialog` have use cases where a CSS class must be explicitly defined. If that solution were to be added, I wonder how that feature would be documented to the developer since it's not tied to a specific component.  

I was attempting to think of other ways to solve this issue and pondered if it were possible to extend the deferred loading functionality of the `p:outputPanel` - if it would make sense to do so - which would appended the CSS class automatically for the developer.  Or maybe change the logic of the `renderDeferred()` function to somehow defer rendering without having to depend on a specific CSS class.

I would think this issue would be fairly common, but the fact that it hasn't come up before makes me wonder if it is correct to wrap a PrimeFaces component in a `display:none` HTML element. I think that's a valid use-case though...especially when utilizing Bootstrap Modals.  I should be able to show/hide components or sections on a page via a basic JavaScript call. Otherwise, I could control the rendering via the rendered attributes or the JSF core conditionals, but that would require an AJAX call to alter the value.

**Comment by melloware** [comment]
I can't believe this hasn't come up before either but I think its because most people are not loading their components to the page with `display:none`....they are doing an `update="section"` on the DIV around the table and basically letting AJAX load it lazily when you click the Show button.  You are preloading yours into the DOM only to then try and show it.  so my guess its not a common use case because its not quite the "JSF way" of doing things.

**Comment by hink084** [comment]
That might just be the answer then...."don't preload it" haha.

**Comment by melloware** [comment]
I think I will close this for now as its an uncommon use case, we have multiple workarounds and the solution to really solve it would be a little messy and obscure for developers to find.
