### ISSUE TITLE
DataTable: filter not working when using custom converter

### ISSUE THREAD

**Issue by seinecle** [primefaces/primefaces#8615]
**Describe the defect**
Filtering on dataTable returns zero values when using a custom converter

**Reproducer**
The dataTable displays the items correctly, as modified by the converter. However when I select any value from the dropdown menu in the filter, the table is blank (no result returned).

The dataTable:

<p:dataTable
    id ="resultsTable"
    var="item" 
    value="#{umigonBean.results}" 
    filteredValue="#{umigonBean.filteredDocuments}" 
    rowIndexVar="rowId">

    <p:column field="sentiment" headerText="sentiment" filterMatchMode="exact">
        <f:facet name="filter">
            <p:selectOneMenu onchange="PF('resultsTableWidgetVar').filter()" styleClass="custom-filter">
                <f:selectItem itemLabel="all" itemValue="#{null}" noSelectionOption="true" />
                <f:selectItems value="#{umigonBean.sentiments}"/>
            </p:selectOneMenu>
        </f:facet>
        
        <h:outputText value="#{item}"/>
        
    </p:column>

</p:dataTable>
The converter:

@FacesConverter(forClass = Document.class, managed=true)
public class DocumentConverter implements Converter<Document> {

    @Override
    public Document getAsObject(FacesContext context, UIComponent component, String value) {
        throw new UnsupportedOperationException("Not supported yet.");
        // I am not sure what this method is supposed to do
    }

    @Override
    public String getAsString(FacesContext context, UIComponent component, Document document) {
        if (document == null) {
            return "";
        }
        if (document.getSentiment().equals(Category._11)) {
          return "sentiment_positive";
        }
        if (document.getSentiment().equals(Category._12)) {
           return "sentiment_negative";
        }
        else if (document.getSentiment().equals(Category._10)) {
           return sentiment_neutral";
        }
      return "";
    }
The UmigonBean:

@Named
@SessionScoped

public class UmigonBean implements Serializable {

    private List<Document> results; // + getters and setters
    private String[] sentiments = new String[]{"sentiment_positive", "sentiment_negative", "sentiment_neutral"}; // + getters and setters
    private List<Document> filteredDocuments; // + getters and setters
The Document class:

public class Document implements Serializable {

private Category sentiment; // + getters and setters

}

**Comment by tandraschko** [comment]
Please provide a primefaces-test reproducer

Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
Going to close for now.  Will re-open if OP provides a reproducer.
