### ISSUE TITLE
DataExporter: Doesn't work with monitor status

### ISSUE THREAD

**Issue by olexd** [primefaces/primefaces#8617]
**Describe the defect**
In the documentation of the DataExporter component (section [Monitor Status](https://github.com/primefaces/primefaces/blob/master/docs/10_0_0/components/dataexporter.md#monitor-status)) is indicated:
DataExport is a non-ajax process so ajaxStatus component cannot apply. See FileDownload Monitor Status section to find out how monitor export process. **Same solution applies to data export as well.** 

However status monitor doesn't work with p:dataExporter as described. Starting from Primefaces version 10.x, the behaviour of status monitor was updated. Instead of using cookie _primefaces.download_ the cookie _primefaces.download+viewId_ suffix is used:

                var cookieName = 'primefaces.download' + PrimeFaces.settings.viewId.replace(/\//g, '_');

 FileDownload component was updated ands works as expected, however DataExported seems to have remained unchanged. DataExporter class still sends the old response cookie _primefaces.download_:

    protected void addResponseCookie(FacesContext context) {
        ResourceUtils.addResponseCookie(context, Constants.DOWNLOAD_COOKIE, "true", null);
    }

    public static final String DOWNLOAD_COOKIE = "primefaces.download";

**Environment:**
 - PF Version: _10.0.x_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**Comment by tandraschko** [comment]
the code looks already good in trunk

please also see https://github.com/primefaces/primefaces#community--elite--pro

**Comment by melloware** [comment]
Yes please try 11.0.0 it looks like it is already fixed.

**Comment by olexd** [comment]
Nice to hear it! Unfortunately using of 11 version is not an option in our project at the moment. We plan to migrate in some of the future releases, but still have to use 10.x. Is it planned to transfer the correct solution to 10 too?

**Comment by tandraschko** [comment]
we dont know; please see my link
