### ISSUE TITLE
DataTable: should not load data when visiting component with SKIP_ITERATION

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8618]

**Comment by fanste** [comment]
By looking through the datatable commits to find the change that fixes one of my problems, I came across this fix.

Just a side note:
``` && !ComponentUtils.isSkipIteration(context, context.getFacesContext())```
might be simplified to
``` && visitRows```

`visitRows` is defined in `UIData#visitTree` with
```boolean visitRows = !ComponentUtils.isSkipIteration(context, facesContext);```
