### ISSUE TITLE
Slider: Issues with Step configuration (calculation)

### ISSUE THREAD

**Issue by Teutron-flo** [primefaces/primefaces#8619]
**Describe the defect**
As I already wrote in the forum (https://forum.primefaces.org/viewtopic.php?f=3&t=71799)
I think there is a little bug in the step configuration or calculation of the slider element.

For my point of view the calculation of the steps is done based on the min value instead of zero base.
If you have a min value of 800 the next step is 1300 (800+500), I would expect 1000 (0 + 500 + 500).
Also when the max value isn't a value of the min value, you can not reach it.
My example here is 15000 end value of the Slider with it is 14800.

**Reproducer**
Reproducer is attached to the ticket, code sniped:
```java
@PostConstruct  
public void init() {
    integer = 3000;
}
```
```xhtml
<h:form id="frmTest">
    <h:panelGrid columns="1" style="margin-bottom: 10px">
         <p:inputText id="number" value="#{testView.integer}" />
         <p:slider for="number" minValue="800" maxValue="15000" step="500" />
    </h:panelGrid>
</h:form>
```

**Environment:**
 - PF Version: 11.0.0
 - JSF + version: _e.g. Mojarra 2.2.20
 - Affected browsers: my test is based on Chrome, but I think all

**Expected behavior**
My expected behavior is, that the calculation is based on zero and the first and the last point are calculated individual.

**Comment by Teutron-flo** [comment]
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/8395535/primefaces-test-master.zip)

**Comment by melloware** [comment]
OK I added code to test.js of your reproducer to MonkeyPatch the JQUERY UI Slider function.  Its not perfect it needs a little more work if you don't mind debugging.  Like I have it rounding to nearest 500 now but its quirky and still stops at 14800.

Can you mess with it and see if you can get it working properly?
[pf-8619.zip](https://github.com/primefaces/primefaces/files/8397617/pf-8619.zip)

**Comment by melloware** [comment]
OK I think I got it all working can you replace whats in test.js file with this and do some testing...

```js
(function() {
    $.ui.slider.prototype._trimAlignValue = function(val) {
        if (val <= this._valueMin()) {
            return this._valueMin();
        }
        if (val >= this._valueMax()) {
            return this._valueMax();
        }
        var step = (this.options.step > 0) ? this.options.step : 1,
            valModStep = (val - this._valueMin()) % step;

        var alignValue = (valModStep > 0) ? Math.floor(val / step) * step : Math.ceil(val / step) * step;

        if (alignValue <= this._valueMin()) {
            return this._valueMin();
        }
        if (alignValue >= this._valueMax()) {
            return this._valueMax();
        }
        return parseFloat(alignValue.toFixed(5));
    };

    $.ui.slider.prototype._calculateNewMax = function() {
        var max = this.options.max;
        this.max = parseFloat(max.toFixed(this._precision()));
    };
})();
```

**Comment by Teutron-flo** [comment]
Thanks for the fix. I will take a look into it on Monday. Over the Weekend i have no time for it, sorry.

**Comment by Teutron-flo** [comment]
@melloware, I'm right now on it to perform a couple of tests.
During that, I notice that you fix with it, also an issue in the showcase.

https://www.primefaces.org/showcase/ui/input/slider.xhtml

InputText Slider with Decimal Value -> Range defined from 0.2 -> 7.1
In the showcase application 7.1 is not reachable.

I added it to pf-8619 and it works:
![image](https://user-images.githubusercontent.com/80260448/161724574-675c82fa-39fd-4bf2-9b00-e6ac88d204fc.png)

**Comment by Teutron-flo** [comment]
@melloware, I found a mismatch now between Slider / Spinner.

```xhtml
			<h:panelGrid columns="1" style="margin-bottom: 10px">
				<p:spinner id="spinner1" value="#{testView.number3}" min="800"
					max="15000" stepFactor="500" suffix=" €">
				</p:spinner>
			</h:panelGrid>
```

The Spinner still works like 800 / 1300 / 1800 / ... / 14 800 but is then able to switch to 15000.
But backwards the behavior for the Spinner is 15000 / 14500 / 1400 / ... / 1000 / 800.

One additional thing, I have seen (also in the Showcase), that the Spinner doesn't update the Slider position.
Like it is when you enter in something in the input field.

Apart from that, I haven't seen any strange behavior.

**Comment by Teutron-flo** [comment]
[pf-8619-test.zip](https://github.com/primefaces/primefaces/files/8417654/pf-8619-test.zip)

**Comment by melloware** [comment]
You should open a new ticket about Spinner
