### ISSUE TITLE
Datatable: Selection does not work correctly when frozen rows are being used

### ISSUE THREAD

**Issue by ihsanyapicioglu** [primefaces/primefaces#8620]
**Describe the defect**
When frozen rows are being used in the datatable, radio / checkbox become unselectable in selection mode.

**Reproducer**
Reproducer has been attached as ZIP file.

[primefaces-frozen.zip](https://github.com/primefaces/primefaces/files/8397342/primefaces-frozen.zip)

**Environment:**
 - PF Version: 11.0.1 Jakarta
 - PF Theme: _e.g. Saga, Arya, etc_
 - JSF + version: Jakarta Faces 3.0.2

**To Reproduce**
1. Enable selection for the datatable. 
2. add frozenRows attribute. (i.e. 2)
3. on the page, try to select radio/checkbox in frozen rows or press select all field at the top
4. frozen rows' radio/checkbox are not being selected as result.

**Expected behavior**
When the radio/checkbox fields of frozen rows are clicked, they should also be selected like other rows.

**Example XHTML**
```html
<h:form id="frmTest">
  <p:dataTable var="product" value="#{testView.products1}" scrollable="true" scrollHeight="250"
               frozenRows="2" rowKey="#{product.name}">
    <p:column selectionMode="multiple" style="width:16px;text-align:center"/>
    <p:column headerText="Name" footerText="Name">
        <h:outputText value="#{product.name}"/>
    </p:column>
    <p:column headerText="Code" footerText="Code">
        <h:outputText value="#{product.code}"/>
    </p:column>
  </p:dataTable>
</h:form>
```

**Comment by ihsanyapicioglu** [comment]
fixed for 11.0.3

**Comment by melloware** [comment]
I tagged and labeled it for 11.0.3 and 12.0.0.

**Comment by vonnai** [comment]
Hi everybody, I don't think the fix that has been done is correct. The removal of ```>``` from this.rowSelector has really bad effect. It causes, that the datatable binds all events from the inner datatables that can be present in an expanded row content. The fix is totally wrong, I think.

**Comment by melloware** [comment]
I think its causing this too: https://github.com/primefaces/primefaces/issues/9895

**Comment by melloware** [comment]
@vonnai can you submit a PR showing your fix so then we can test it against other scenarios
