### ISSUE TITLE
InputTextArea: Various ajax events mentioned in the documentation aren't supported

### ISSUE THREAD

**Issue by bobsbrain** [primefaces/primefaces#8625]
When adding an ajax event to an InputTextArea component, various events mentioned in the documentation return following error.
`<p:ajax> Event:input is not supported.`
The site stays white. 

**To Reproduce**
Add an ajax event to an InputTextArea.
Currently non supported events which are mentioned in the [documentation](https://primefaces.github.io/primefaces/11_0_0/#/components/inputtextarea?id=ajax-behavior-events) nevertheless:
`wheel, cut, copy, paste, contextmenu, input, invalid, reset, search, drag, dragend, dragenter, dragleave, dragover, dragstart, drop, scroll`

**Expected behavior**
The event gets called correctly.

**Example XHTML**
```
<p:inputTextarea value="#{value}">
	<p:ajax event="input" global="false"/>
</p:inputTextarea>
```

**Comment by melloware** [comment]
Showcase was broken.  Submitted PR to fix the issue
