### ISSUE TITLE
Spinner / Slider: Values are not synchronized

### ISSUE THREAD

**Issue by Teutron-flo** [primefaces/primefaces#8630]
**Describe the defect**
Currently when you change the value of a input field with a spinner, the corresponding slider position is not updated. 
The same behavior is already in the showcase visible:
https://www.primefaces.org/showcase/ui/input/slider.xhtml

But direct changes in the input field are reflected by the slider.

**Reproducer**
Reproducer is attached to the ticket, code sniped:
```html
        <h:panelGrid columns="1" style="margin-bottom: 10px">
            <p:spinner id="spinner1" value="#{sliderView.number3}" min="0" max="1000" stepFactor="50"
                       suffix=" €" valueChangeListener="#{sliderView.onInputChanged}">
                <p:ajax process="@this" update="growl"/>
            </p:spinner>
            <p:slider for="spinner1" minValue="0" maxValue="1000" step="50"/>
        </h:panelGrid>
```
**Environment:**
 - PF Version: 11.0.0
 - JSF + version: Mojarra 2.2.20

**Expected behavior**
When I change a value with the Spinner the Slider position should be also updated, like it is, when you change the value in the input field.

**Comment by Teutron-flo** [comment]
[pf-8630-Reproducer.zip](https://github.com/primefaces/primefaces/files/8419003/pf-8630-Reproducer.zip)

**Comment by melloware** [comment]
Relates to: https://github.com/primefaces/primefaces/issues/8298
