### ISSUE TITLE
Spinner: Issues with Step calculation

### ISSUE THREAD

**Issue by Teutron-flo** [primefaces/primefaces#8631]
**Describe the defect**
In Issue https://github.com/primefaces/primefaces/issues/8619, I descprided and issue with the Slider Step calculation.
For the Spinner is a simliar behavior in place:

```html
        <h:panelGrid columns="1" style="margin-bottom: 10px">
            <p:spinner id="spinner1" value="#{sliderView.number3}" min="0" max="1000" stepFactor="50"
                       suffix=" €" valueChangeListener="#{sliderView.onInputChanged}">
                <p:ajax process="@this" update="growl"/>
            </p:spinner>
            <p:slider for="spinner1" minValue="0" maxValue="1000" step="50"/>
        </h:panelGrid>
```

If you start with 800 and go up, the steps are the following:
800 / 1300 / 1800 / 2300 / ... / 14800 / 15000

If you go down from 15000 you have the following sequence:
15000 / 14500 / 14000 / ... / 1000 / 800

For my point of view, the start value should make now difference in the step calculation.
It should be always based on zero and the first and the last point are calculated individual.

Means in that case:
800 / 1000 / 1500 / ... / 14500 / 15000
15000 / 14500 / 14000 / ... / 1000 / 800

**Reproducer**
Reproducer is attached to the ticket

**Environment**
PF Version: 11.0.0
JSF + version: Mojarra 2.2.20

Expected behavior
My expected behavior is, that the calculation is based on zero and the first and the last point are calculated individual.

**Comment by Teutron-flo** [comment]
[pf-8630-Reproducer.zip](https://github.com/primefaces/primefaces/files/8419124/pf-8630-Reproducer.zip)

**Comment by melloware** [comment]
MonkeyPatch: 

```js
if (PrimeFaces.widget.Spinner) {
    PrimeFaces.widget.Spinner.prototype.spin = function(dir) {
        var step = this.cfg.step * dir,
            currentValue = this.value ? this.value : 0,
            newValue = this.parseValue(currentValue + step);

        newValue = (dir > 0) ? Math.floor(newValue / step) * step : Math.ceil(newValue / step) * step;
        newValue = this.parseValue(newValue);

        if (this.cfg.maxlength !== undefined && newValue.toString().length > this.cfg.maxlength) {
            newValue = currentValue;
        }

        this.value = newValue;
        this.format();
        this.input.attr('aria-valuenow', this.getValue());
    };
};
```
