### ISSUE TITLE
DataTable : using the reflow="true" attribute adds the first column's header text to the beginning of the contents of an expansion row

### ISSUE THREAD

**Issue by tarwork** [primefaces/primefaces#8636]
----------------------------------------------------
----------------------------------------------------
# Before creating a issue, please carefully read: https://github.com/primefaces/primefaces/blob/master/README.md#community--elite--pro
----------------------------------------------------
----------------------------------------------------

**Describe the defect**
When using a p:datatable with p:column and p:rowExpansion a funny thing happens. If the p:datatable has the attribute reflow="true" then the header text of the first column is added to the beginning of the data of the expansion row output.

**Reproducer**
i have attached a primefaces test folder.

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme: _e.g. Saga, Arya, etc_
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
please run simple primefaces test project

**Expected behavior**
The header text for the first column should not be included in the out put of the expansion row.
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/8421667/primefaces-test-master.zip)

**Comment by melloware** [comment]
confirmed this issue.  looking into it.

**Comment by melloware** [comment]
OK add this CSS to your page:

```css
body .ui-datatable-reflow .ui-expanded-row-content td .ui-column-title   {
  display: none;
}
```

**Comment by tarwork** [comment]
work around confirmed. thank you!

**Comment by melloware** [comment]
No problem thanks for the report!
