### ISSUE TITLE
DataTable: log warning when paginator=true i used with rows=0

### ISSUE THREAD

**Issue by ozziej** [primefaces/primefaces#8639]
**Describe the defect**
When using a lazy loaded table, with a lazy data mode and pagination if you do not add the **rows="10"** to the dataTable declaration, it will not show ANY data. (the value of the number of rows must ALWAYS be greater than 0) This is a problem, because the DEFAULT behaviour / value is 0, and this will cause there NOT to be any data displayed, and no error is produced.

**Environment:**
 - PF Version: _10.0.7_
 - PF Theme: Any (done with luna)
 - JSF + version: 2.3, WildFly 25
 - Affected browsers: All

**To Reproduce**
Exclude the rows="10" or similar value > 0 in the dataTable creation in XHTML.

**Expected behavior**
It should show ALL rows (or change the default value to be a non-zero value, I would suggest 10)

This is the default getRows() method, it will set the returned value to 0 by default (this is the problem)
primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java#L180

In DataTable.java
primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java#L482

I would suggest changing line 482 from:
int rows = getRows();
to
int rows = getRows() == 0 ? 10 : getRows();

P.S. Small fix, correct Line 486 from:
 first = Integer.parseInt(params.get(getClientId(context) + "_first")) + **getRows**();
to
 first = Integer.parseInt(params.get(getClientId(context) + "_first")) + **rows**;

**Example XHTML**
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Other Users</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <f:metadata>
        <f:viewAction action="#{userController.findAllUsersList}"/>
    </f:metadata>
    <h:form id="userListForm">
        <p:dataTable  id="userDataTable" var="userData" value="#{userController.users}" 
                     paginator="true" paginatorTemplate="{FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                     selection="#{userController.selectedUser}" selectionMode="single" widgetVar="userTable" lazy="true"
                     rowKey="#{userData.userId}" paginatorPosition="top" reflow="true">
            <p:column headerText="Surname" sortBy="#{userData.surname}" filterBy="#{userData.surname}" filterMatchMode="contains">
                <h:outputText value="#{userData.firstName} #{userData.surname}"/>
            </p:column>
            <p:column headerText="Email Address" sortBy="#{userData.emailAddress}" filterBy="#{userData.emailAddress}" filterMatchMode="contains">
                <h:outputText value="#{userData.emailAddress}"/>
            </p:column>            
        </p:dataTable>
    </h:form>
</html>
```

**Example Bean**
```java

private LazyDataModel<Users> users;
private Users selectedUser;

@Named
@ViewScoped
public class UserController implements Serializable {

public void findAllUsersList() {
        users = new LazyDataModel<Users>() {
            private static final long serialVersionUID = 1L;

            @Override
            public List<Users> load(int first, int pageSize, Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {
                List<Users> userList = usersBean.findAllUsers(first, pageSize, sortBy, filterBy);
                Long rowCount = usersBean.countAllUsers(filterBy);
                users.setRowCount(rowCount.intValue());
                return userList;
            }

            @Override
            public Users getRowData(String rowKey) {
                for (Users user : users.getWrappedData()) {
                    if (user.getUserId().equals(Integer.parseInt(rowKey))) {
                        return user;
                    }
                }
                return null;
            }

            @Override
            public String getRowKey(Users user) {
                return user.getUserId().toString();
            }
        };
    }
}

public LazyDataModel<Users> getUsers() {
        return users;
    }
```

**Comment by tandraschko** [comment]
If we change this, a non-lazy DT would not Show all rows anymore per Default?

**Comment by tandraschko** [comment]
If this issue is still reproduceable, i think we should just log a warning that paginator requires rows to be set

**Comment by ozziej** [comment]
Thats why I suggested only changing the default behaviour of lazy loaded tables... 
But, yes, perhaps an easier solution would be the warning... Ill leave it up to you.

**Comment by ozziej** [comment]
Actually thinking about it, I think the warning is better. Rather just always show a warning about the rows attribute being required if pagination is enabled. (paginator="true")

**Comment by tandraschko** [comment]
added a default value now, was a bit easier

**Comment by tandraschko** [comment]
Tests are failing, will replace it with a logging later

**Comment by melloware** [comment]
I reverted it for now to get tests to pass.

**Comment by tandraschko** [comment]
checked it with the current showcase and i think the current behavior isnt bad
if you dont send rows, it will display a paginator with 1 page but shows all data
so the default 0 doesnt resolve to "show zero rows", its just "display all rows"

**Comment by tandraschko** [comment]
nevertheless, i added a smal hint log

**Comment by ozziej** [comment]
> checked it with the current showcase and i think the current behavior isnt bad
> if you dont send rows, it will display a paginator with 1 page but shows all data
> so the default 0 doesnt resolve to "show zero rows", its just "display all rows"

This is a specific case where if you're using a paginator component and lazy loading, if you do not include the "rows" attribute it breaks. It doesn't show a warning, it doesn't say "no records found" it just shows the paginator, with the correct number of pages and NO data. This confused me for a few hours as I couldn't understand why I was getting some indication that it was getting the correct data, but it was not showing the data.

> nevertheless, i added a smal hint log

That's cool, thanks. It does need some kind of warning / hint.
