### ISSUE TITLE
Tree: Selected ui-tree-nodes are not always classed correctly

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8650]
PF 11 and 12

Selected `ui-tree-node` with `selectionMode="checkbox"` has the class `ui-treenode-selected` which is correct:

<img width="755" alt="Screenshot 2022-04-08 at 20 12 05" src="https://user-images.githubusercontent.com/7500178/162498371-f330bf6e-a2ce-47a7-9e42-1ab219e2bd1b.png">

with `selectionMode="single"` or `multiple`, selected nodes are classed `ui-treenode-unselected` which is wrong:

<img width="748" alt="Screenshot 2022-04-08 at 20 15 36" src="https://user-images.githubusercontent.com/7500178/162498758-36b2e967-9732-467f-8b57-cb7d7e817c25.png">

Relates to #8649

**Comment by melloware** [comment]
@FlipWarthog any interest in this one?

**Comment by FlipWarthog** [comment]
Sure, but I won't be able to look at it until next week. If it's still open then I'll see what's up.

**Comment by jepsar** [comment]
I can have a look as well, not sure when I can find some time though.

**Comment by FlipWarthog** [comment]
I did a quick look and I believe swapping those classes is just missing from `selectNode`|`unselectNode` in tree.vertical.js. The js that handles checkbox selection/unselection is, unfortunately, separate and does have the proper handling.

https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js#L490-L518

**Comment by melloware** [comment]
PR coming?

**Comment by FlipWarthog** [comment]
If I can get the showcase running locally ;)

**Comment by melloware** [comment]
Done

**Comment by melloware** [comment]
Showcase should work locally now...
