### ISSUE TITLE
Schedule: BackgroundColor/styleClass/borderColor disappears when event lasts more than 1 day

### ISSUE THREAD

**Issue by newk5** [primefaces/primefaces#8652]
**Describe the defect**
When creating a DefaultScheduleEvent, if you set a custom color using .backgroundColor() or .borderColor() or even setting a custom style class with .styleClass(), that will be ignored if the event lasts more than 1 day.

**Reproducer**
The primefaces showcase can be used as a reproducer.

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme:  ANY
 - JSF + version: ANY
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to  https://www.primefaces.org/showcase/ui/data/schedule/configuration.xhtml?jfwid=d54ca
2. Change to "Month" view
3. Click on the "Birthday party" event
4. Change the "To" date to the next day

Before:
![image](https://user-images.githubusercontent.com/32560510/162541871-ef2d41d1-b6f8-4e2b-9aa2-395d20252ece.png)
After:
![image](https://user-images.githubusercontent.com/32560510/162541923-bb83be83-65c3-411e-91c8-4b5c864444e5.png)
**Expected behavior**
Custom set colors/Css should not be lost when events last more than 1 day

**Comment by melloware** [comment]
I think this might be happening in FullCalendar.io.   When I watch the DOM when you switch from single day to a multiday even fullCalendar generates a completely different DOM for the event.

**Comment by melloware** [comment]
I think we might have to mark this wont fix.  It seems the native FullCalendar this is the expected behavior see their demo for v 5.11 here: https://fullcalendar.io/docs/month-view-demo

It does the same thing so its a "feature" of FullCalendar.

**Comment by melloware** [comment]
Also see this about background color: https://github.com/primefaces/primefaces/issues/8193  Also expected behavior

**Comment by newk5** [comment]
Ah I see, so its an issue with the FullCalendar library, nothing we can do about it then, thanks for looking into it.

About having an actual background as color I found a workaround which I'm using, I'll leave it here in case someone is interested.
Add the following CSS:
```css
.body .fc .fc-event, body .fc .fc-event .fc-event-main{
        background: inherit;
 }
```
Then create a class with your background color like: 
```css
.red {
background: red !important;
}
```
And when you are creating your event use .setStyleClass("red"). This will work for all events (month, day, week) and for multiple day events too.
