### ISSUE TITLE
TabView/AccordionPanel: error indication

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#8659]
When you have a `TabView` with multiple tabs on which validation can fail, it is really handy that the tabs on which errors occur, get an error highlighting.
For this, we use the following Javascript within our project:
```javascript
function markInvalidTabs(id) {
    id = PrimeFaces.escapeClientId(id);
    let c = $(id + '>ul>li');
    c.each(function () {
        let d = $('a', this);
        let tid = d.attr('href').substring(1);
        tid = PrimeFaces.escapeClientId(tid);
        let uiStateErrorElements = $(tid + ' .ui-state-error');
        let uiMessageErrorDetailElements = $(tid + ' .ui-message-error-detail');
        if (uiStateErrorElements.length + uiMessageErrorDetailElements.length > 0) {
            $(this).addClass('ui-state-error');
        } else {
            $(this).removeClass('ui-state-error');
        }
    });
}
```
and hence we call this method after an AJAX update, with `id` the `TabView` identifier.
It would be cool if this would be the default behavior of `TabView`.

**Comment by melloware** [comment]
This could probably be hooked into the `refresh` method of the widget.

**Comment by melloware** [comment]
Can you try this MonkeyPatch?

```js
if (PrimeFaces.widget.TabView) {
    PrimeFaces.widget.TabView = PrimeFaces.widget.TabView.extend({
        refresh: function(cfg) {
            this._super(cfg);
            $(this.jqId + '>ul>li').each(function() {
                var tid = $('a', this).attr('href').substring(1);
                tid = PrimeFaces.escapeClientId(tid);
                var uiStateErrorElements = $(tid + ' .ui-state-error');
                var uiMessageErrorDetailElements = $(tid + ' .ui-message-error-detail');
                if (uiStateErrorElements.length + uiMessageErrorDetailElements.length > 0) {
                    $(this).addClass('ui-state-error');
                } else {
                    $(this).removeClass('ui-state-error');
                }
            });
        }
    });
};
```

**Comment by fcorneli** [comment]
Works as expected. Thanks. I'm definitely in favor of seeing this included in PF itself.

**Comment by melloware** [comment]
Yep I will submit a PR

**Comment by tandraschko** [comment]
i dont think we should scan for messages
better scan for invalid inputs

**Comment by jepsar** [comment]
We can do the same for accordion

**Comment by fcorneli** [comment]
Maybe make this configurable? `indicateErrors="true/false"` and default to `false`. Rationale: maybe some developers already use the tab header color (same remark for accordion) to indicate some state. Defaulting to this behavior would light up their christmas tree too much.

**Comment by melloware** [comment]
Agreed we should fix both components.  Anyone have a preference on the property name?  I am looking to see if we have any similar functionality on other components so we can keep the property name the same?

**Comment by tandraschko** [comment]
really not sure if we should make it configurable for each component, maybe just global
even that might be to much

maybe we just a styleclass to the tab and user can overwrite it instead of the 1001 component attr

**Comment by melloware** [comment]
Good idea. I will submit a PR with what I come up with.

**Comment by melloware** [comment]
PR Submitted.  Right now it just adds `ui-state-error` but since the themes don't respect it there is no UI change without adding...

```css
body .ui-tabs.ui-tabs-top > .ui-tabs-nav li.ui-tabs-header.ui-state-error {
  border-color: red;
}

body .ui-accordion .ui-accordion-header.ui-state-error {
    border-color: red;
    background: lightpink;
    color: red;
}
```

I will open a follow up `theme` labeled ticket.

**Comment by fcorneli** [comment]
Tested out 12.0.0-SNAPSHOT against our app. Tab error indications work as expected.

**Comment by fcorneli** [comment]
Just noticed that a tab containing a required `p:tree` (within a `p:scrollPanel`) does not show up in red.
I even have a `<p:message for="categories"/>` on this tab, but the tab "title" does not color red in case of a missing value.
Using PF 12.0.0-RC2 here.

**Comment by melloware** [comment]
@fcorneli create a PF Test reproducer so I can see the issue.

**Comment by fcorneli** [comment]
@melloware See attachment for a demonstrator.

[8659-tree.zip](https://github.com/primefaces/primefaces/files/9232573/8659-tree.zip)

**Comment by melloware** [comment]
@fcorneli its because Tree is not an InputComponent so it doesn't have a "isValid" nor does it add "ui-state-error" to the root class when its invalid thus its not being picked up by the Tab JS code as "in error".

I bet this is why your original code was looking for `let uiMessageErrorDetailElements = $(tid + ' .ui-message-error-detail');` that I couldn't figure out why you needed to do that.

**Comment by fcorneli** [comment]
@melloware Indeed, that's one of the reasons why I had `ui-message-error-detail` in the original code. Maybe this could be added again? Won't hurt I guess...

**Comment by fcorneli** [comment]
@melloware Was thinking a bit about this, a nice feature for `tabView` could be `jumpToErrorTab=true/false`.

**Comment by melloware** [comment]
I would open a new ticket and call the property `focusOnError`

**Comment by fcorneli** [comment]
@melloware Created ticket #9054 for the `focusOnError` feature.

**Comment by fcorneli** [comment]
@melloware I've tried this feature on 13.0.0-SNAPSHOT and unfortunately it no longer works.
I noticed that `tabview.js` received some refactoring.
Within `PrimeFaces.widget.TabView.bindRefreshListener`: if I move up the code within the `addRefreshListener` directly under `bindRefreshListener`, the error indication kicks in again.
So the code under `addRefreshListener` is indeed doing its thing, but I guess on the "old" tab.

**Comment by melloware** [comment]
@fcorneli I think this issue broke it: https://github.com/primefaces/primefaces/issues/9517

**Comment by melloware** [comment]
@fcorneli I am looking through the commits and the addRefreshListener has been there for over a year.

**Comment by melloware** [comment]
Fixed with: https://github.com/primefaces/primefaces/pull/10142
