### ISSUE TITLE
PrimeFlex 3-Support for PanelGrid

### ISSUE THREAD

**Issue by commodis** [primefaces/primefaces#8662]
**Description**
Primefaces has the [PanelGrid](https://primefaces.github.io/primefaces/12_0_0/#/components/panelgrid)-component which offers a `layout`-attribute. The currently documented options are:

* `tabular` layout, 
* `grid` layout or 
* `flex` layout

We are using [PrimeFlex 3](https://www.primefaces.org/primeflex/) as our CSS layout engine.
No particular layout option works well with PrimeFlex 3.

* `tabular` generates `table`, `tr` and `td`,
* `grid` generates the deprecated `ui-g` classes and
* `flex` generates the previous major version of PrimeFlex 2 classes (`p-grid`)

**Describe the solution you would like**
An intermediate solution would be to support an option like `flex3` which would generate PrimeFlex 3 classes (like `grid`, `col`, etc.)
or probably a more scalable solution to let the developer inject his own classes like `layout="none"`.

**Example XHTML**
```xml
<h:form id="frmTest">
    <p:panelGrid
        layout="none"
        styleClass="grid"
        columns="2"
        columnClasses="col-9, col-3"
    >
        <div>left content</div>
        <div>right content</div>
</h:form>
```

**Comment by melloware** [comment]
This was already fixed for 12.0.0 with this PR: https://github.com/primefaces/primefaces/issues

12.0.0 showcase and components have fully switched to PrimeFlex 3.
