### ISSUE TITLE
Should we add a CharacterEncodingFilter?

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8673]
i always copy the class around my projects - even its used in themedesigner or showcase
actually we should also use it primefaces-test or integration tests

@melloware @christophs78 ?

**Comment by jepsar** [comment]
Although it's present in OmniFaces, I think it's a good idea. I would add overwriting the `X-Powered-By` and `Server` headers to it. It once came out of a pentest, and we have been overriding them since.

**Comment by melloware** [comment]
Yes I have noticed this is copied everywhere it is a simple filter we should include it with PF so it can be reused in PF Test, Integration Tests etc!

**Comment by melloware** [comment]
Do you want me to take care of this?

**Comment by tandraschko** [comment]
Will do it later
