### ISSUE TITLE
Add a NoCacheFilter

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#8674]
JSF per default sets cache headers correclty to resources, however it DOES not set no-cache headers on views
therefore i always have such a filter in my projects

should we add it too?

I ask because we currently introduce a new shared framework inside my company i look for stuff, which is actually more related to PrimeFaces.

**Comment by tandraschko** [comment]
basically the same as BalusC posted here: https://stackoverflow.com/questions/10305718/avoid-back-button-on-jsf-web-application

**Comment by melloware** [comment]
Yep I have been using OmniFaces `NoCacheFilter` for years.   So having something in core PF would be good for users that don't like introducing extra libs like OMniFaces.

**Comment by stolp** [comment]
I welcome this as a user who have stumbled upon this in the path.

**Comment by pizzi80** [comment]
You should consider to push this to JSF (mojarra/myfaces) 
because a lot of people use jsf + omnifaces + primefaces ... 

As I said many times in mojarra's and omnifaces' repo, 
JSF it's a mature project now and developers expect somenthing that works out of the box ;)
