### ISSUE TITLE
Datatable Selection Mode Multiple with Array in Backing Bean

### ISSUE THREAD

**Issue by ipersoftware** [primefaces/primefaces#8675]
Tested on PrimeFaces 10.0.0
If I set selectionMode = 'multiple' in some column, and in BackingBean I've an array, this will produce an empty selection. The problem is in the SelectionFeature.setSelection 
```java
selection = isArray ? Array.newInstance(clazz.getComponentType(), selected.size()) : selected;
```

solved changing Array to List.

SelectionFeature

```java
 protected void setSelection(FacesContext context, DataTable table, boolean multiple, List<Object> selected, Set<String> rowKeys) {
        ValueExpression selectionVE = table.getValueExpression(DataTableBase.PropertyKeys.selection.toString());
        Class<?> clazz = selectionVE == null ? null : selectionVE.getType(context.getELContext());
        boolean isArray = clazz != null && clazz.isArray();

        if (multiple && clazz != null && !isArray && !List.class.isAssignableFrom(clazz)) {
            throw new FacesException("Multiple selection reference must be an Array or a List for datatable " + table.getClientId());
        }

        Object selection = null;
        if (selected.isEmpty()) {
            if (multiple) {
                selection = isArray ? LangUtils.EMPTY_OBJECT_ARRAY : Collections.emptyList();
            }
        }
        else {
            if (multiple) {
                selection = isArray ? Array.newInstance(clazz.getComponentType(), selected.size()) : selected;
            }
            else {
                selection = selected.get(0);
            }
        }

        table.setSelectedRowKeys(rowKeys);

        if (selectionVE != null) {
            selectionVE.setValue(context.getELContext(), selection);
        }
        else {
            table.setSelection(selection);
        }
    }
```
----------------------------------------------------
----------------------------------------------------
# Before creating a issue, please carefully read: https://github.com/primefaces/primefaces/blob/master/README.md#community--elite--pro
----------------------------------------------------
----------------------------------------------------

**Describe the defect**
A clear and concise description of what the defect is.

**Reproducer**
Clone repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution and attach the GitHub Link or zip file of your reproducer here. **NOTE:** PrimeFaces test can easily be set to use the latest `master-SNAPSHOT` of what is in GitHub. Please test with that before reporting a bug that may already be fixed.

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme: _e.g. Saga, Arya, etc_
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**

**Expected behavior**

**Example XHTML**
```html
<h:form id="frmTest">
  ..
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

}
```

**Comment by jepsar** [comment]
Please use the issue template and try with PrimeFaces 12 first.

**Comment by melloware** [comment]
I will close this for now until a reproducer is provided. 

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
