### ISSUE TITLE
PrimeFaces Selenium: configuration

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#8679]
When trying to use `primefaces-selenium` within our project to improve QA, we stumbled upon some funny configuration aspects.
Maybe this feedback can be useful.

We had to go back to Selenium version 3.141.59 instead of version 4.1.3 since they changed some API calls.
Since we want to configure as much as possible from within Java, I had to use the following construct:
```java
ChromeDriver driver = new ChromeDriver();
WebDriverProvider.set(new EventFiringWebDriver(driver));
```
in order to make,
```java
PrimeSelenium.createFragment(CommandButton.class, By.id("addForm:addButton"));
```
to work.

We also had to add a minimal `primefaces-selenium/config.properties` containing,
```
deployment.baseUrl=https://localhost/our-web-app-context
```
to make things work. Would be handy if one could heh... configure the `ConfigProvider` entirely from within Java.

**Comment by tandraschko** [comment]
You would need a config file anyway
If we would provide some init handler, we would propably use Serviceloader
So -1 to create some new config stuff

**Comment by christophs78** [comment]
@fcorneli Which PrimeFaces-version do you use? 11.0.x uses Selenium 3.x, 12.0.x(-SNAPSHOT) uses Selenium 4.x.

**Comment by fcorneli** [comment]
I'm using the 11.0.0 release of primefaces-selenium. Noticed indeed that PF 12 is using Selenium 4.
I'm also not extending the PF PageObject thingy, but directly using `PrimeSelenium.createFragment`.

**Comment by christophs78** [comment]
Ok. 11.0.0 explains why you need to stick with Selenium 3.x.
Which application server / container do you use for your integration tests / ui tests?

**Comment by tandraschko** [comment]
Please try 12.0 for the manual WebDriverProvider.set issue
the code looks like it should work

and for the minimal config file, we can improvide the doc a bit

**Comment by tandraschko** [comment]
adjusted the docs: https://github.com/primefaces/primefaces/tree/master/primefaces-selenium

i think you just miss: `webdriver.browser = chrome` but if you still need to manually set WebDriverProvider.set, please create a new issue with a sample application, how you use it.
It should not be necessary
