### ISSUE TITLE
DatePicker: mask="true" does not work with selection mode 'range'

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8687]
```xhtml
      <p:datePicker pattern="yyyy-MM-dd"
                    selectionMode="range"
                    rangeSeparator="-"
                    mask="true"/>
```

Currently shows: `____-__-__`

Expected: `____-__-__ - ____-__-__`

**Comment by melloware** [comment]
I am not sure we are going to get range and mask to work together properly.  I wonder if we should just log a console error that these two features can't be used together?

**Comment by jepsar** [comment]
Is was wondering if this was going to be hard or not. Log is fine with me.

**Comment by jepsar** [comment]
I'll have a look tonight. Would be awesome if we could support mask with range.

**Comment by melloware** [comment]
Ok let me know. We can always fall back to just logging an error if you can't make it work.
