### ISSUE TITLE
Chart.js: Grid line configuration not working

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#8689]
### 1) Environment

PrimeFaces version: primeFaces-11.0.0
JSF version: mojarra-2.3.17

### 2) Describe the defect

Grid line configuration is not working due to renamings in Chart.js 3.x.

According to https://www.chartjs.org/docs/latest/getting-started/v3-migration.html:
- options.gridLines was renamed to options.grid
- options.gridLines.offsetGridLines was renamed to options.grid.offset.
- options.gridLines.tickMarkLength was renamed to options.grid.tickLength.

The renaming is also done in the scales object. See https://www.chartjs.org/docs/latest/samples/scale-options/grid.html

### 3) Actual generated json data

(see primefaces-test-gridlines)

    "options": {
      "gridLines": {
        "offsetGridLines": true
      }

      "scales": {
        "A": {
          "gridLines": {
            "display": false,
            "drawBorder": true,
            "drawOnChartArea": true,
            "drawTicks": true,
            "offsetGridLines": false
          }
        },
        "B": {
          "gridLines": {
            "display": false,
            "drawBorder": true,
            "drawOnChartArea": true,
            "drawTicks": true,
            "offsetGridLines": false
          }
        }
      }

### 4) Expected generated json data for Chart.js 3.x.

    "options": {
      "grid": {
        "offset": true
      }

      "scales": {
        "A": {
          "grid": {
            "display": false,
            "drawBorder": true,
            "drawOnChartArea": true,
            "drawTicks": true,
            "offset": false
          }
        },
        "B": {
          "grid": {
            "display": false,
            "drawBorder": true,
            "drawOnChartArea": true,
            "drawTicks": true,
            "offset": false
          }
        }
      }

### 5) Reproducer

[primefaces-test-gridlines.zip](https://github.com/primefaces/primefaces/files/8512889/primefaces-test-gridlines.zip)

Run:
mvn clean jetty:run -Pmojarra23

Primefaces 10 with Chart.js 2.x.
![gridlines_pf10](https://user-images.githubusercontent.com/62264053/164001562-4ded4809-c29c-4b87-89dd-d8415f41575f.png)

Primefaces 11 with Chart.js 3.x.
![gridlines_pf11](https://user-images.githubusercontent.com/62264053/164001597-90c6e964-568e-4e99-8857-4d9296252439.png)

**Comment by melloware** [comment]
Excellent catch, reproducer and report!
