### ISSUE TITLE
Tree: wrong order at server side after drag&drop

### ISSUE THREAD

**Issue by stonewoodman** [primefaces/primefaces#8693]
**Describe the defect**
If you move (drag&drop) an item in tree downwards, then the frontend shows it correctly but the model at server side has wrong order.

**Environment:**
 - PF Version: _12.0.0 (current dev version)_
 - PF Theme: _nova-light_
 - JSF + version: _MyFaces 2.3.9_
 - Affected browsers: _ALL_

**To Reproduce**
Initial order
```
Node 1
Node 2
Node 3
Node 4
Node 5
```
move an item
```
Node 2
<-- Node 1
Node 3
Node 4
Node 5
```
order at server side (vs client side)
```
Node 2 (Node 2)
Node 3 (Node 1)
Node 1 (Node 3)
Node 4 (Node 4)
Node 5 (Node 5)
```

I have already created a bugfix and pull request #8692

**Expected behavior**
The order of model at server side is correct

**Example XHTML**
```html
<f:metadata>
    <f:viewAction action="#{indexController.init()}"/>
</f:metadata>

<p:tree id="testTree" value="#{indexController.root}" var="node" draggable="true" droppable="true">
    <p:treeNode>
        <h:outputText value="#{node}"/>
    </p:treeNode>
</p:tree>

<p:commandButton process="@this" update="testTree" value="Update"/>
```
The update button can be used to show the server side data

**Example Bean**
```java
@Named
@ViewScoped
public class IndexController implements Serializable
{
    private TreeNode<String> root;

    public void init() {
        root = new DefaultTreeNode<>();
        new DefaultTreeNode<>("Test 1", root);
        new DefaultTreeNode<>("Test 2", root);
        new DefaultTreeNode<>("Test 3", root);
        new DefaultTreeNode<>("Test 4", root);
        new DefaultTreeNode<>("Test 5", root);
    }

    public TreeNode<String> getRoot()
    {
        return root;
    }

    public void setRoot(TreeNode<String> root)
    {
        this.root = root;
    }
}
```

**Comment by melloware** [comment]
Thank for for documenting!

**Comment by melloware** [comment]
@stonewoodman this has been reverted.  Please see the other ticket.

**Comment by tandraschko** [comment]
@melloware shouldnt we reopen then?

**Comment by melloware** [comment]
Yep Re-opened and I am waiting to hear from @stonewoodman on this issue which @OBreidenbach thinks is not an issue anyway.

**Comment by jepsar** [comment]
Reopening a closed issue is not great when it has been fixed on a released milestone IMO. I linked the old PR to 12.0.0-RC1 and will remove the milestone from this issue.

**Comment by melloware** [comment]
If @stonewoodman does not respond I will close this ticket again.

**Comment by stonewoodman** [comment]
I will check this issue

**Comment by stonewoodman** [comment]
@melloware It's not working.

Initial list
```
Node 0
Node 1
Node 2
Node 3
Node 4
```

Moving 0 between 2 and 3
```
Node 1
Node 2
Node 0
Node 3
Node 4
```

Client side is correct, if i use the update button, then i have on the server side the following order
```
Node 1
Node 0
Node 2
Node 3
Node 4
```

Items that i moving upwards, works fine

**Comment by melloware** [comment]
Cc @OBreidenbach thoughts?

**Comment by OBreidenbach** [comment]
@stonewoodman do you use the reproducer from above?
IMHO for the tree a 
<p:ajax event="dragdrop" update="@form"/>
is missing.

Actual I do not understand that the reproducer is changing anything on the server side without the ajax event.
The update button does only process="@this".

Add 
<p:ajax event="dragdrop" update="@form"/>
to the reproducer and everything will work as expected. 

If you think it should work without the ajax event make sure that your fix does not break the usecase with the ajax event!

**Comment by tandraschko** [comment]
i dont think a update to the Tree should be required when the trigger is the same tree itself
so the dragdrop request is just a additional request to sync the state to the server - not sure if tree does it automatically without adding p:ajax

**Comment by OBreidenbach** [comment]
I am confused. 
@stonewoodman against which version of primefaces did you test?

The ticket said, that on moving down the node is moved on node to far.
The fix was to reduce the index on the server side by one.
No @stonewoodman finds that the node is moved to short.

So I think @stonewoodman tested against release 12.0 and found the regression he introduced?

@tandraschko Yea, I think you are write.

**Comment by stonewoodman** [comment]
Code for reproducing

```
    <f:metadata>
        <f:viewAction action="#{indexController.init()}"/>
    </f:metadata>

    <ui:define name="content">
        <h:form id="form">
            <p:tree id="testTree" value="#{indexController.root}" var="node" draggable="true" droppable="true">
                <p:treeNode>
                    <h:outputText value="#{node}"/>
                </p:treeNode>
            </p:tree>

            <p:commandButton process="@this" update="testTree" value="Update"/>
        </h:form>
    </ui:define>
```

```
@Named
@ViewScoped
public class IndexController implements Serializable
{
    private TreeNode<String> root;

    public void init() {
        root = new DefaultTreeNode<>();
        new DefaultTreeNode<>("Test 0", root);
        new DefaultTreeNode<>("Test 1", root);
        new DefaultTreeNode<>("Test 2", root);
        new DefaultTreeNode<>("Test 3", root);
        new DefaultTreeNode<>("Test 4", root);
    }

    public TreeNode<String> getRoot()
    {
        return root;
    }

    public void setRoot(TreeNode<String> root)
    {
        this.root = root;
    }
}
```

without p:ajax there is a ajax-call in the background. 
if i change in the button to process="testTree" -> same wrong behavior.
if i add p:ajax dragdrop event -> same wrong bahavior

**Comment by stonewoodman** [comment]
I made a screen recording with the code above

https://1drv.ms/v/s!AhlKkUEgkqIdlKJHqMAlRkPbpNlsSg?e=OcWuei

**Comment by melloware** [comment]
Here is a runnable reproducer: 
[pf-8693.zip](https://github.com/primefaces/primefaces/files/10383377/pf-8693.zip)

@stonewoodman that reproducer is using 12.0.0 and I see your issue however if I use 13.0.0-SNAPSHOT which reverts your fix it looks like it is working fine?

Run `mvn clean jetty:run` and navigate to localhost:8080/primfaces-test  If I use 13.0.0-SNAPSHOT everything appears to be working fine can you please test?

**Comment by stonewoodman** [comment]
arrgh, my fault. Sorry.
I thought, i tested with current 13.0.0-SNAPSHOT version, but it was an older snapshot version.
It works fine with current snapshot version. Thanks.
