### ISSUE TITLE
Breadcrumb: Allow items to be dropdowns

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8699]
I ran into this demo https://gui-challenges.web.app/breadcrumbs/dist/ where breadcrumb items can be dropdowns. I think that's an interesting feature. Should we look in to this?

<img width="534" alt="Screenshot 2022-04-21 at 09 34 38" src="https://user-images.githubusercontent.com/7500178/164403188-e972fb92-a206-4de6-bf30-5533e821de46.png">

**Comment by melloware** [comment]
Hmmm its interesting but not sure how I feel about it. Its both a breadcrumb and a menu.

**Comment by jepsar** [comment]
I don't have an immediate use case for it myself. The amount of items which should be part of the dropdown could be very large in our applications.

**Comment by melloware** [comment]
Isn't this a duplicate of: https://github.com/primefaces/primefaces/issues/3380

**Comment by jepsar** [comment]
> Isn't this a duplicate of: #3380

No, I don't think so. The other issue is not about have dropdowns as items.

**Comment by melloware** [comment]
i think its about having any custom markup you want in breadcrumbs and then you can easily do a Menu Overlay like in the example here on the Showcase where you trigger the overlay Menu on the breadcrumb: https://www.primefaces.org/showcase/ui/menu/menu.xhtml

![image](https://user-images.githubusercontent.com/4399574/164744074-ef7c9ca1-93ae-4558-8856-b48d2a7e89bb.png)

**Comment by jepsar** [comment]
I didn't understand the issue like that. Sound similar to how the tree works (nodes per type).
