### ISSUE TITLE
SelectOneListbox: Update Documentation

### ISSUE THREAD

**Issue by zicheee** [primefaces/primefaces#8711]
**Description**
Today I tried to use the SelectOneListbox and auto-update my view when selecting an element. When going to the documentation (https://primefaces.github.io/primefaces/11_0_0/#/components/selectonelistbox) there is no information about the ajax events. 

I tried serveral events until I found out which ones worked for me. 

**Describe the solution you would like**
An updated documentation like the SelectOneMenu (https://primefaces.github.io/primefaces/11_0_0/#/components/selectonemenu?id=ajax-behavior-events) would be great to list the events possible.

**Comment by melloware** [comment]
Thanks for reporting.  I will fix!
