### ISSUE TITLE
Overlays: Close on scroll of window

### ISSUE THREAD

**Issue by felixoi** [primefaces/primefaces#8726]
**Describe the defect**
Dropdowns (used in MenuButton, SelectChecboxMenu, ...) stay open on scroll and overlay the topbar on the showcase for example.

![image](https://user-images.githubusercontent.com/14966472/165751863-2aaa1e08-cfb1-43dd-a405-a628be420789.png)

**Reproducer**
https://github.com/primefaces/primefaces/tree/master/primefaces-showcase

**Environment:**
 - PF Version: 11.0.0
 - PF Theme:  Saga
 - JSF + version:  MyFaces 2.3.9
 - Affected browsers: All

**To Reproduce**
1. Go to 'https://www.primefaces.org/showcase/ui/menu/menuButton.xhtml'
2. Click on one of the menu buttons
3. Scroll down until the dropdown overlays the topbar

**Expected behavior**
Either the dropdown should be closed on scroll or the showcase needs some z-index fixes. 

**Example XHTML**
Take a look at the showcase sourcecode.

**Comment by melloware** [comment]
I had fixed this before to close the dropdown upon browser scroll as requested by PrimeTek but it was reverted with this fix: https://github.com/primefaces/primefaces/issues/6978

I will fix it again
