### ISSUE TITLE
OverlayPanel dismissable not working ad expected - should be dismissible

### ISSUE THREAD

**Issue by bInTheSwamp** [primefaces/primefaces#874]
from 5.3 

init: function(a) {
        this._super(a);
        this.cfg.showEvent = this.cfg.showEvent || "click.overlaypanel";
        this.cfg.hideEvent = this.cfg.hideEvent || "click.overlaypanel";
        this.cfg.target = this.cfg.targetId ? $(PrimeFaces.escapeClientId(this.cfg.targetId)) : null ;
        this.jq.panel({
            position: this.cfg.at,
            display: this.cfg.showEffect,
            dismissible: this.cfg.dismissable
        });
        if (this.cfg.dynamic) {
            this.jq.append('<div class="ui-panel-inner"></div>');
            this.content = this.jq.children("div.ui-panel-inner")
        }
        this.bindEvents()
    },

by changing:
 dismissable: this.cfg.dismissable

to:
dismissible: this.cfg.dismissable

this option works as expected

**Comment by tandraschko** [comment]
Outdated, the code regarding dismissable already has been changed.
