### ISSUE TITLE
Core: FullAjaxExceptionHandler does not show error page when exception is thrown during ajax request

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8743]
**Describe the defect**
Original report on OmniFaces: https://github.com/omnifaces/omnifaces/issues/686

**Reproducer:**
[pf-8743.zip](https://github.com/primefaces/primefaces/files/8597485/pf-8743.zip)

Run `mvn clean jetty:run` and click "Send AJAX Error".

**Environment:**
 - PF Version: _11.0.0_

Analysis done by @BalusC in that ticket should be implemented.

**Comment by melloware** [comment]
I think this issue BalusC is referring to is here:

```js
                // used by @all
                else if (id === PrimeFaces.VIEW_ROOT) {

                    // backup our utils, we reset it soon
                    var ajaxUtils = PrimeFaces.ajax.Utils;

                    // reset PrimeFaces JS state because the view is completely replaced with a new one
                    window.PrimeFaces = null;

                    ajaxUtils.updateHead(content);
                    ajaxUtils.updateBody(content);
                }
```

**Comment by tandraschko** [comment]
Need to check it
It should not fail and ist there since years

**Comment by melloware** [comment]
Yep i created a reproducer for you to check it out.

**Comment by pizzi80** [comment]
Please release also in v11 elite ... it's a frustrating bug and the workaround it's not clear

**Comment by pizzi80** [comment]
using the workaround of  BalusC 

I got the following JS error:

```
Uncaught TypeError: PrimeFaces.error is not a function
    at Object.<anonymous> (core.js?ln=primefaces&v=11.0.4:formatted:1435:36)
    at c (jquery.js?ln=primefaces&v=11.0.4:2:28327)
    at Object.fireWith [as resolveWith] (jquery.js?ln=primefaces&v=11.0.4:2:29072)
    at l (jquery.js?ln=primefaces&v=11.0.4:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.js?ln=primefaces&v=11.0.4:2:82355)
(anonymous) @ core.js?ln=primefaces&v=11.0.4:formatted:1435
c @ jquery.js?ln=primefaces&v=11.0.4:2
fireWith @ jquery.js?ln=primefaces&v=11.0.4:2
l @ jquery.js?ln=primefaces&v=11.0.4:2
(anonymous) @ jquery.js?ln=primefaces&v=11.0.4:2
```

**Comment by melloware** [comment]
I don't think BalusC thoroughly tested his workaround and it was assuming your 500.xhtml had not much in it.

His workaround was for that very specific error the user was reporting but not a comprehensive fix for all scenarios depending on what code you have in your 500.xhtml.

**Comment by melloware** [comment]
@pizzi80 if you update my reproducer above to show your issue I can see if I can make it work or MonkeyPatch it for you.

**Comment by pizzi80** [comment]
> I don't think BalusC thoroughly tested his workaround and it was assuming your 500.xhtml had not much in it.
> 
> His workaround was for that very specific error the user was reporting but not a comprehensive fix for all scenarios depending on what code you have in your 500.xhtml.

ok!  ... I didn't understand ... ;) 

> @pizzi80 if you update my reproducer above to show your issue I can see if I can make it work or MonkeyPatch it for you.

no worries I'll wait for the next release 

only a funny note on the reproducer ... 

it's funny that you use Eclipse Jetty with Apache MyFaces 

while I use Apache Tomcat with (now) Eclipse's Mojarra LOL  
... maybe it's time to unify all these projects :D

**Comment by melloware** [comment]
@pizzi80 its also possible you are running into a slightly different issue than the original reported.  Which is why I was hoping you could reproduce it so I can check whether this fix actually fixes it or not.

**Comment by commodis** [comment]
Will this still be targeted for Elite? I ask because it still has the `elite` tag, but also the `12.0.0` milestone

**Comment by melloware** [comment]
@commodis that is up to @mertsincan to put in Elite unless you have a PRO account to request it

**Comment by commodis** [comment]
Thanks for clarification how the process works - I understand.

**Comment by tandraschko** [comment]
JFYI about the process: https://github.com/primefaces/primefaces#community--elite--pro

**Comment by agoetze** [comment]
For all users still being on PrimeFaces 8: We had to revert to v8.0.16 to get rid of this problem. In all later versions (latest version right now is 8.0.19) the OmniFaces FullAjaxExceptionHandler does not work in conjunction with PrimeFaces. One just gets a broken page with some faulty CSS but not the expected error page.
