### ISSUE TITLE
ToggleSwitch: Theme change for icon support

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8744]
**Description**
Mert we implemented: https://github.com/primefaces/primefaces/issues/7901

PR: https://github.com/primefaces/primefaces/pull/8322

I have a showcase example already built for you to make the necessary theme changes...

![image](https://user-images.githubusercontent.com/4399574/166110429-5599638e-d3e0-4cd2-86c0-a7c9e4e65ceb.png)

Some suggested CSS changes will be required like...

- After adding `line-height: 1.4em; text-align: center;` it's looking somewhat better. 
- Obviously the text color needs to be changed in the theme and `content: ""` needs to be removed. 
- But in general I must say that the circle is too small to contain icons. At normal text size the icon looks cramped. I feel it needs some padding.

**Comment by mertsincan** [comment]
@melloware Could you please check it? Thanks a lot!

**Comment by melloware** [comment]
Will do!

**Comment by melloware** [comment]
@mertsincan alsmost there but maybe adding `line-height: 1.4;` it centers the icon better.

Before:
![image](https://user-images.githubusercontent.com/4399574/178754928-24b14f45-1024-49a7-93e3-02eadd03eaa5.png)

After:
![image](https://user-images.githubusercontent.com/4399574/178755001-536bb36f-2966-446a-8610-0ff988aa4577.png)

**Comment by mertsincan** [comment]
@melloware, Interesting! Which browser are you using? Also, could you please check the following CSS code in the browser's inspector?
```
.ui-toggleswitch-handler {
    ...
    display: flex;
    align-items: center;
    justify-content: center;
}
```
<img width="82" alt="Screen Shot 2022-07-13 at 15 41 12" src="https://user-images.githubusercontent.com/11868120/178761825-74acb9eb-14a6-4bdd-a0df-d7f7a0fb87d6.png">

**Comment by jepsar** [comment]
Maybe this should be a new issue, but can we do a same animation as we have with speed dial?

https://www.primefaces.org/showcase/ui/button/speedDial.xhtml

See Transition Duration and Icon

**Comment by melloware** [comment]
I  am using latest Chrome:

![image](https://user-images.githubusercontent.com/4399574/178776059-0f32d761-e91c-4322-a71e-ba83d7bd8cf8.png)

**Comment by mertsincan** [comment]
If I add `line-height: 1.4`, icon alignment is broken in my browser(Chrome Version 103.0.5060.114 (Official Build) (x86_64)). 

@jepsar I'm not sure. Maybe you can try to apply speedDial's icon animation and then we can decide accordingly.

**Comment by melloware** [comment]
Hmmm maybe its my resolution then!

**Comment by mertsincan** [comment]
@melloware could you please try `line-height: 1.25rem;`?

**Comment by melloware** [comment]
that looks great!

**Comment by mertsincan** [comment]
Thanks a lot, @melloware ;)

**Comment by jepsar** [comment]
To animate the icon I need to change the way the icons are swapped. Will open a new issue.
