### ISSUE TITLE
TreeTable: MultiViewState Support (MVS)

### ISSUE THREAD

**Issue by tetzla** [primefaces/primefaces#8756]
**Description**
Please add MultiViewState support to component TreeTable. It's currently quite cumbersome and inconsistent to store the tree state explicitly within the view bean.

**Describe the solution you would like**
see https://primefaces.github.io/primefaces/12_0_0/#/core/multiviewstate

**Tasks**

- [ ] Selection
- [ ] Expansion
- [x] Sorting
- [x] Filtering
- [x] Column (resize, display, order)

**Comment by tandraschko** [comment]
It would be great If you can sponsor it via PrimeFaces PRO or provide a PR

**Comment by melloware** [comment]
Updated this ticket with Task list of what is completed and what is not complete for TreeTable MVS.

**Comment by melloware** [comment]
Replaced by https://github.com/primefaces/primefaces/issues/11250
