### ISSUE TITLE
SpeedDial: Not working properly in DataTable column

### ISSUE THREAD

**Issue by AzharMobeen** [primefaces/primefaces#8760]
**Describe the defect**
When we try to use SpeedDial in Datatable column it's having display and alignment issue

**Reproduced**
I have created fork repository on top of [primefaces-test](https://github.com/primefaces/primefaces-test.git). Please clone [my fork](https://github.com/AzharMobeen/primefaces-test) that and run as per primefaces-test README.

**Environment:**
 Same as [primefaces-test](https://github.com/primefaces/primefaces-test.git)

**To Reproduce**
Please clone [my fork repository](https://github.com/AzharMobeen/primefaces-test) and just run you can see the issue

**Expected behavior**
Ideally It should be display and align as per DataTable column and behave as expacted.

![image](https://user-images.githubusercontent.com/4399574/166699351-cdebdcb9-501a-4dd3-ba21-9d2e8cfe6d64.png)

**Comment by melloware** [comment]
Can you include your CSS here that you used to fix your issue locally.

**Comment by AzharMobeen** [comment]
I have change SpeedDial diraction to left and added below css, It could be temporary solution :
```
<style>
  body .ui-speeddial-button.ui-button.ui-button-icon-only {
     width: 2rem;
     height: 2rem;
     top: -15px;
  }

  .ui-speeddial-direction-up {
     flex-direction: colum
  }
</style>
```
```
 <p:speedDial direction="left" transitionDelay="80" showIcon="pi pi-bars" hideIcon="pi pi-times"
      buttonStyleClass="ui-button-outlined">
      <p:menuitem icon="pi pi-pencil" action="#{testView.add}" update=":frmTest:messages"/>
      <p:menuitem icon="pi pi-refresh" action="#{testView.update}" update=":frmTest:messages"/>
      <p:menuitem icon="pi pi-trash" action="#{testView.delete}" update=":frmTest:messages"/>
      <p:menuitem icon="pi pi-upload" outcome="/test"/>
      <p:menuitem icon="pi pi-external-link" url="https://www.primefaces.org"/>
  </p:speedDial>
```
<img width="875" alt="image" src="https://user-images.githubusercontent.com/18392008/166731415-0a246bbd-f812-4add-a221-02ce38b0f602.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/18392008/166732028-7413f578-97e4-478a-a6f8-409557d1ee40.png">

**Comment by melloware** [comment]
I am going to close this as a good workaround has been provided and using a speed dial in a datatable is not a standard use case for the speed dial.  Thanks for your workaround!
