### ISSUE TITLE
DataTable: Nested Table in RowExpansion with Splitbutton issue

### ISSUE THREAD

**Issue by ingeniotechnologies** [primefaces/primefaces#8764]
### Describe the bug

To reproduce, add a main datatable and in its rowexpansion tag, add another datatable with selectionMode='single'.

```
<h:form>
    <p:dataTable var="item" 
                 value="#{bean.items}">
        <p:column>
            <p:rowToggler/>
        </p:column>
        <p:column headerText="Item Name">
            <h:outputText value="#{item.name}"/>
        </p:column>
        <p:rowExpansion>
            <p:dataTable var="subitem" 
                         value="#{item.subitems}"
                         selectionMode="single"
                         selection="#{bean.selectedSubitem}"
                         rowKey="#{subitem.id}">
                <p:column headerText="Subitem Name">
                    <h:outputText value="#{subitem.name}" />
                </p:column>
                <p:column>
                    <p:splitButton value="Save" action="#{bean.save}">
                        <p:menuitem value="Update" action="#{bean.update}"/>
                        <p:menuitem value="Delete" action="#{bean.delete}"/>
                    </p:splitButton>
                </p:column>
            </p:dataTable>
        </p:rowExpansion>
    </p:dataTable>
</h:form>

```
the testing methods in the bean are just

```
    public void save() {
        System.out.println("Saved subitem");
    }

    public void update() {
       System.out.println("Updated subitem");
    }

    public void delete() {
        System.out.println("Deleted subitem");
    }
```

The first issue has to do with the selection of the subitem row when clicking or entering slplitbutton. If I click on the center of the dropdown button of the splitbutton, the subitem row gets correctly selected. If I click the default button, no selection is made. Additionally, if I click the bottom-right corner (the space outside the icon) of the dropdown button, no row selection takes place either.

The second issue has to do with bean methods not being executed when more than 2 items are loaded. If only a single item and its subitems are loaded, splitbutton menuitem link buttons work fine. Bean methods are properly called when clicking menuitem links buttons.

But as soon as I load 2 or more items and their subitems, everything looks visually correct, but the commands in splitbutton menuitem link buttons no longer reach bean.

I've added this workaround to make sure the subitem row correctly selected when cliking a few parts of the splitbutton:
```
            jQuery( document).delegate( ".ui-splitbutton .ui-button", "click", 
                function(e){
                    var parentTd = $(this).closest("td");
                    //send click event to parent td element
                    $(parentTd).click();
                }
            );
```

I also added this workaround to fire off the bean methods based on the split button menuitem text (which is the unique key in my table) by mapping a js function to my bean method:
`<p:remoteCommand name="splitButtonMenuitemClicked" actionListener="#{bean.save}" style="display: none;" />`

and here's the code that always catches the click event on the splititem menuitem link buttons.:

```
            jQuery( document).delegate( ".ui-splitbuttonmenu .ui-menuitem-link", "click", 
                function(e){
                    var menuitemText = $(this).find("span.ui-menuitem-text");
                    var wishlistName = $(menuitemText).text();
                    splitButtonMenuitemClicked([{ name: "wishlistName", value: wishlistName }])
                    //console.info("'"+wishlistName+"' Was Clicked");
                }
            );
```

### Expected behavior

1) datatable row should select when clicking any part of splitbutton
2) splitbutton menuitem link buttons should always fire off command from nested datatabkes inside another datatable.

### PrimeFaces edition

Community

### PrimeFaces version

11.0

### Theme

None

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

Firefox

**Comment by ingeniotechnologies** [comment]
I spoke too soon, I still don't have the woraround working 100%. I have some issues with the subitem row selection; which is critical to take action from the split botton on the correct subitem. Still working on making it work...

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by ingeniotechnologies** [comment]
I would also be nice if primefaces added this as an example in showcase. It seems to be a pretty common thing developer want to do. And this way, primefaces would notice any issues.

**Comment by melloware** [comment]
i think nested datatable is an uncommon thing and I never recommend it as a UI practice.  That is just me personally.  

Also PrimeTek has stopped advertising `SubTable` as well even though the code is still in there you won't find any showcase examples.

**Comment by ingeniotechnologies** [comment]
I think this is what "DataTable Row Group" tries to address. If you look at that example in showcase, that data would come from two tables, a representatives table and a customers? table. Except in that example, data comes from possibly two join tables... In my opinion, there should be a subtable there that should be populated with representative.customers.

**Comment by melloware** [comment]
But that is RowGrouping which is a perfectly understandable use case.    Why not just create the POJO representing your rows in your backing bean to have the data from your two tables and represent it in Row Grouping if that is all your are trying to do?

it looks like the only value you need to repeat is the `#{item.name}` and make that the Row Grouping to give you that Nested table look?

Your example above is talking about nesting a complex Datatable the most complex component in the suite...inside the RowExpander of an outer Datatable correct?

**Comment by ingeniotechnologies** [comment]
I thought about doing just that, but I need to be able to execute some actions on row header and other set of actions on subitems. I'll give that a try, looking at the example again, looks like I can place my action buttons in row header and other action buttons in the subitems... Thanks!

**Comment by melloware** [comment]
Yep you should totally be able to do that. Let me know how it goes!

**Comment by ingeniotechnologies** [comment]
hi @melloware hmm, I just got the project back to working using just a single datatable with header row, but the weirdest thing is happening. So I load a single item from dataset and it properly creates the expandable header row with its action buttons and a simulated subrow with its other set of action buttons. The issue arises when I then add new row and try to display the table. It then gives a strange error saying: javax.el.PropertyNotFoundException: The class '...ItemsReadonly' does not have the property 'item'. Can't figure out what's going on! I set the datatable var to "item", but can't understand why it will display one item, but not 2 of more... I know I'm not giving much detail, but is there something different between loading 1 item or >2 that would cause an error like this?

**Comment by melloware** [comment]
Wait you are calling "AddRow" ?   Also check your "rowKey" and your objects equals() and hashcode() are correct?  Maybe its having trouble distinguishing your second row for uniqueness?

**Comment by ingeniotechnologies** [comment]
yup, that makes sense, I'll check it out

**Comment by melloware** [comment]
Maybe also make sure its Serializable object.

**Comment by ingeniotechnologies** [comment]
thanks! it was a typo, I entered p:headerRow field="item.name" instead of just p:headerRow field="name"

**Comment by ingeniotechnologies** [comment]
Ok, so far so good. I still have to figure out a few things. for instance, the action buttons in header rows still need to 'know' which header buttons are being clicked since it appears these headers are not selectable. once I figure that out, I think this would work.

**Comment by melloware** [comment]
And I actually think this is a much cleaner much less heavy solution than nested tables.

**Comment by ingeniotechnologies** [comment]
Absolutely, thanks a lot!

**Comment by ingeniotechnologies** [comment]
Hi again @melloware, something related to this whole thing. my splitbutton  is located as follows `h:form->p:tabView->p:tab->p:panel->p:dataTable->p:column->p:splitButton`. I believe menuitem link commands are not being executed because splitbutton   is buried too deep. is there a way to overcome this?

**Comment by melloware** [comment]
No I feel like it might be a bug. That should be ok.  Let me put together a little test case and see. I will post back here what I find out.

**Comment by ingeniotechnologies** [comment]
@melloware I started removing and rearranging html code. what seemed to be causing the issues were a bunch of p:dialog and p:confirmDialog code I had. I then removed the global form and added a separate form inside each p:tab as follows: `p:tabView->p:tab->p:panel->h:form->p:dataTable` and while the p:dialog and p:confirmDialog resided inside this form, the p:splitButton menu actions would not work. after I placed these dialogs outside the form, the p:splitButton menuitem actions started working... what a heck!

**Comment by melloware** [comment]
I wonder if there was just too much in the `<h:form>` and something was colliding.  As a general rule I always put my dialogs in their own `<h:form>`.   Plus if you hve dialog inside table rows that HTML gets repeated OVER and OVER in the DOM rather than 1 dialog outside your table that you just update before showing with the row data.

So do you have it all working now?

**Comment by melloware** [comment]
I am going to close this ticket for now since it seems you have solved your issues.

**Comment by ingeniotechnologies** [comment]
Thanks for everything!

**Comment by ingeniotechnologies** [comment]
hi @melloware, everything is looking good, I would just like to ask one last question. since with this implementation, I'm using a read-only entity because it comes from joined tables and/or subtables, actual data changes to both database and sets are made to original item/subitem updatable entities and don't reflect back to the read-only entity. is there a way to force reloading data on datatable from entity manager? or how would you approach it?

**Comment by melloware** [comment]
@eframsergio so I am not sure exactly your use case but you can use case but if you want changes to your UI without user interaction you have 2 options.

1. Poller https://www.primefaces.org/showcase/ui/ajax/poll.xhtml?jfwid=cc511

2. Socket Push - https://showcase.omnifaces.org/push/socket

Once you deetct your data has changes in your poller you `update=` your table or if you know it happens in server side code without an HTTP request you can do a Socket push to notify the UI to update.

**Comment by ingeniotechnologies** [comment]
Awesome, thank you!
