### ISSUE TITLE
Charts (jqPlot): Remove

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8773]
The jqPlot charts are deprecated since 10. So they should be removed at some point. That will also take care of duplicate class names (making importing easier).

**Comment by tandraschko** [comment]
lets also do it in 13.0, where lightbox and IE support will be removed
12.0 should be soon, so it doesnt hurt to remove it after 12.0

**Comment by melloware** [comment]
OK that sounds good to me too.
