### ISSUE TITLE
DataTable Group dataExporter problem

### ISSUE THREAD

**Issue by tsotzolas** [primefaces/primefaces#8774]
### In Datatable Group dataExporter  is not working properly. 

And this happens and in Primefaces Showcases    
https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml?jfwid=ab914   

<img width="774" alt="image" src="https://user-images.githubusercontent.com/3863689/167430246-35f84b55-5a92-44c8-9fe0-499b93840b36.png">

I check and in primefaces 11.0.4 and a similar problem is exists and in this version
In version 11.0.4 is not display at all the content of the table.

### PrimeFaces version

11.0.0

### JSF version

2.3

### Browser(s)

Firefox

**Comment by melloware** [comment]
Fixed for 12.0.0: https://github.com/primefaces/primefaces/issues/8241
