### ISSUE TITLE
Chips: stops processing input on the first non-unique pair

### ISSUE THREAD

**Issue by stefan-dan** [primefaces/primefaces#8780]
### Describe the bug

Chips component with `unique="true"`, does not process the whole input, but stops at the first non-unique pair.

### Reproducer

1. Go to https://www.primefaces.org/showcase/ui/input/chips.xhtml
2. Click on **Unique** input
3. Write `aaa,aaa,bbb`
4. Press `Enter`
5. See error, `bbb` was not processed

### Expected behavior

The whole input must be processed, regardless of the duplicates.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

All

### JSF implementation

All

### JSF version

2.3

### Browser(s)

All

**Comment by melloware** [comment]
Confirmed. Working on a fix.

**Comment by melloware** [comment]
MonkeyPatch: 
```js
if (PrimeFaces.widget.Chips) {
    PrimeFaces.widget.Chips.prototype.addItem = function(value, refocus) {
        var $this = this;

        if (!value || !value.trim().length) {
            return;
        }

        var tokens = value.split(this.cfg.separator);
        for (var i = 0; i < tokens.length; i++) {
            var token = tokens[i];
            if (token && token.trim().length && (!this.cfg.max || this.cfg.max > this.hinput.children('option').length)) {
                var escapedValue = PrimeFaces.escapeHTML(token);

                if (this.cfg.unique) {
                    var duplicateFound = false;
                    this.hinput.children('option').each(function() {
                        if (this.value === escapedValue) {
                            duplicateFound = true;
                            return false; // breaks
                        }
                    });
                    if (duplicateFound) {
                        $this.refocus(refocus);
                        continue;
                    }
                }

                var itemDisplayMarkup = '<li class="ui-chips-token ui-state-active ui-corner-all">';
                itemDisplayMarkup += '<span class="ui-chips-token-icon ui-icon ui-icon-close"></span>';
                itemDisplayMarkup += '<span class="ui-chips-token-label">' + escapedValue + '</span></li>';

                this.inputContainer.before(itemDisplayMarkup);
                this.refocus(refocus);

                this.hinput.append('<option value="' + escapedValue + '" selected="selected"></option>');
                this.invokeItemSelectBehavior(escapedValue);
            }
        }
        $this.updateFloatLabel();
    }
};
```

**Comment by stefan-dan** [comment]
Thanks for the fast reply. I tried the MonkeyPatch, and it works for standard input, but it breaks the `addOnPaste="true"` feature.
![image](https://user-images.githubusercontent.com/52972263/167880347-fe3fccf8-6e90-4de9-a9bb-a6ec945b9db6.png)

**Comment by melloware** [comment]
I can't reproduce.  without `addOnPaste` it lets you paste but when you press ENTER those would be removed as unique.  And `addOnPaste="true"` it doesn't even let me paste that.

But if I do `aaa,bbb,cccc` only `cccc` is properly added above.

**Comment by stefan-dan** [comment]
With `addOnPaste="true"`, when you paste something it processes it correctly, but the initial input remains in the input field, like in the image above, and you have to press `Enter` once again to get rid of it.
You can check the original behavior of `addOnPaste="true"` in the showcase.

**Comment by melloware** [comment]
hmm i am running 12.0-snaphot locally and not seeing that behavior. its working as I would expect.
