### ISSUE TITLE
DataExporter: Does not support ColumnGroup

### ISSUE THREAD

**Issue by bsanders1979** [primefaces/primefaces#8782]
### Describe the bug

When exporting datatables that use <p:columnGroup>, the data does not line up with the headers

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/8673062/primefaces-test.zip)

* Open localhost:8080
* Click Export
* View File Contents

### Expected behavior

The data and headers should line up

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

**Comment by melloware** [comment]
Fixed for 12.0.0: https://github.com/primefaces/primefaces/issues/8241
