### ISSUE TITLE
DataExporter: Does not work correctly when columnGroup is used

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8784]
### Describe the Bug

The dataexporter does not create the desired output for both csv as well as for xls when columnGroup is used. In case of csv, the header is missing while the content is there. In case of xls, the header is correct but the content is missing.

The following little example demonstrates it (see also the attached reproducer):

![Screenshot from 2022-05-12 11-35-53](https://user-images.githubusercontent.com/10051373/168044951-3ce6e46b-90f5-4609-bb41-780474000b59.png)

Export to xls delivers:

![Screenshot from 2022-05-12 11-52-27](https://user-images.githubusercontent.com/10051373/168045389-00b9c58f-6736-4b64-8d22-bafdbad36769.png)

Export to csv delivers:

![Screenshot from 2022-05-12 11-53-07](https://user-images.githubusercontent.com/10051373/168045443-06853ccc-1a43-4f50-828a-3921d9a93485.png)

Many thanks in advance for checking and fixing the issue.

### Reproducer

Here is the reproducer:

[p-dataexportercsv-grouped.zip](https://github.com/primefaces/primefaces/files/8677087/p-dataexportercsv-grouped.zip)

### Expected behavior

The exports should look the same content-wise as the printed datatable.

In case of csv, it should look as follows as least:

![Screenshot from 2022-05-12 12-40-09](https://user-images.githubusercontent.com/10051373/168052975-44edb842-1140-4720-984e-17d534cd1cef.png)

### PrimeFaces version

12.0.0-SNAPSHOT

**Comment by melloware** [comment]
Column Groups only work for XLSX and CSV.  By making a Column Group work for CSV would violate [RFC-4810](https://datatracker.ietf.org/doc/html/rfc4180) which defines what makes a valid CSV.

It is also why on the Column Group showcase page https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml?jfwid=4e242  We only provide XSLX and PDF download buttons.

**Comment by tuerker** [comment]
yes but the XLSX export even on the showcase is not working correctly!

![Screenshot from 2022-05-12 14-17-48](https://user-images.githubusercontent.com/10051373/168072969-461ee589-1fd9-424f-8a78-373ecce70032.png)

XLSX export delivers:

![Screenshot from 2022-05-12 14-17-28](https://user-images.githubusercontent.com/10051373/168073018-19c041a1-2f67-48a7-90ff-5f530354d1f8.png)

**Comment by melloware** [comment]
Yes if you look its already fixed in 12.0_SNAPSHOT see: https://github.com/primefaces/primefaces/issues/8241

![image](https://user-images.githubusercontent.com/4399574/168073212-31e04958-9c7c-4b87-abbc-8049dd1d3365.png)

**Comment by tuerker** [comment]
i see that the fix of the XLSX exporter issue is quite new. many thanks. cheers.
