### ISSUE TITLE
DataTable: Row alignment issue with scrollable and frozen columns

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#8791]
### Describe the bug

When using a DataTable with scrollable and frozen columns there are two alignment issues.

1) If a text in the frozen column or scrollable column wraps, then the row alignment breaks.
See here
![frozen_column_rows](https://user-images.githubusercontent.com/6900303/168447722-524b740c-d795-4437-8a20-7e0bac8091d8.png)

2) If there is a footer with just horizontal scrolling, then the row alignment is not right.
See here
![frozen_column_footer](https://user-images.githubusercontent.com/6900303/168447757-2a77f1c4-7d3d-4b26-9c23-cb611cf1d375.png)

### Reproducer

[reproducer.zip](https://github.com/primefaces/primefaces/files/8693842/reproducer.zip)

### Expected behavior

The row height should be updated initially, also when resizing the table.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

saga

### JSF implementation

All

### JSF version

2.3

**Comment by pfumi** [comment]
Attempt to fix it #8792

**Comment by melloware** [comment]
Nice work.  I wonder if it also fixes this issue? https://github.com/primefaces/primefaces/issues/2388

**Comment by pfumi** [comment]
I think the issue in https://github.com/primefaces/primefaces/issues/2388 still persists, I think we need also to fix the height when updating, let me look...
