### ISSUE TITLE
Property "$primevue" was accessed during render but is not defined on instance. in nuxt 3

### ISSUE THREAD

**Issue by shahensaifullah** [primefaces/primefaces#8793]
### Describe the bug

In nuxt 3 i've made a dropdown. but the dropdown menu does not work. 
My Settings:
```
nuxt.config.ts
css: [
        'primevue/resources/themes/saga-blue/theme.css',
        'primevue/resources/primevue.css',
        'primeicons/primeicons.css'
    ]
```
```
<template>
  <div>
    hello world
    <Dropdown v-model="selectedCity" :options="cities" optionLabel="name" placeholder="Select a City" />
  </div>
</template>

<script>
import Dropdown from 'primevue/dropdown';
export default {
  components: {
    Dropdown
  },
  data() {
    return {
      selectedCity: null,
      cities: [
        {name: 'New York', code: 'NY'},
        {name: 'Rome', code: 'RM'},
        {name: 'London', code: 'LDN'},
        {name: 'Istanbul', code: 'IST'},
        {name: 'Paris', code: 'PRS'}
      ]
    }
  }

}
</script>
```

but all CSS are working well like button but vue code is not working.
In nuxt 2 i need to make plugins but in the documentation, i did not see any plugins to add in nuxt 3.

### Expected behavior

In dropdown, in general, when i click dropdown menu, all menus are visible through dropdown but when I click dropdown, it shows  in console 
` [Vue warn]: Property "$primevue" was accessed during render but is not defined on instance. `

### PrimeFaces edition

Community

### PrimeFaces version

5.0.0

### Theme

Saga

**Comment by melloware** [comment]
This is JSF you want PrimeVue repo
