### ISSUE TITLE
Accesibility problem with pagination of datatables and datalist

### ISSUE THREAD

**Issue by dariorios** [primefaces/primefaces#880]
The pagination of the datatable is not accessible. 
This is due to a few problems as listed below:

The first issue is that the pagination is automatically placed within a header and then i also have headers associated with each column.
This means that when the screen reader reads out the column headers it also reads out all of the pagination header twice.

Could the pagination just read one time in the header?

Second:

When a screenReader pass for a the pagination buttons, it says: one, two, three, etc. For the other buttons if just says p. There could a way to change the text of the links, similar with an attribute that change this buttons labels?

**Comment by mertsincan** [comment]
I couldn't replicate this issue with JAWS15-16. For second issue, please try with; https://github.com/primefaces/primefaces/issues/764

What PF-version are you using?

**Comment by dariorios** [comment]
5.3

**Comment by mertsincan** [comment]
Please try with 5.3.x or 5.4.
