### ISSUE TITLE
DataExporter: Ignores ColumnToggler

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8804]
When columns are excluded with the columnToggler, the data exporter still exports the "hidden" columns.

Expected Behavior: The exporter does not export the "hidden" columns.

Many thanks in advance for fixing this issue.

PS: I am using a quite recent snapshot: 12.0.0-20220512.142926

**Comment by melloware** [comment]
Isn't that this comment: https://github.com/primefaces/primefaces/issues/8031#issuecomment-1070994570 ???

**Comment by melloware** [comment]
Also do you have `visibleOnly="true"` set on your Exporter?  https://github.com/primefaces/primefaces/issues/7966

**Comment by tuerker** [comment]
> Isn't that this comment: [#8031 (comment)](https://github.com/primefaces/primefaces/issues/8031#issuecomment-1070994570) ???

no. this issue https://github.com/primefaces/primefaces/issues/8031#issuecomment-1070994570 was about the wrong ordering of the columns. this problem was fixed some time ago.

**Comment by tuerker** [comment]
> Also do you have `visibleOnly="true"` set on your Exporter? #7966

thanks for the hints. i tried it out now. no change. the deselected columns are still exported.

**Comment by melloware** [comment]
You are right.  I fixed it.  Though you defeinitely need `p:ajax` on ColumnToggler for it to work as ColumnToggler is UI only without it.

```xml
<p:columnToggler datasource="products" trigger="toggler">
        <p:ajax />
</p:columnToggler>
```

**Comment by tuerker** [comment]
This did not helped, too.

**Comment by tuerker** [comment]
By the way, while using visibleOnly="true", i detected another problem. then, some "visible" columns are not exported anymore.

**Comment by melloware** [comment]
I have a fix in PR: https://github.com/primefaces/primefaces/pull/8806

Included a showcase example...

**Comment by melloware** [comment]
OK its merged feel free to try the latest 12.0.0-SNAPSHOT.

**Comment by tuerker** [comment]
great will do it.

**Comment by tuerker** [comment]
the problem is fixed with this new snapshot. as you stated, visibleOnly="true" must be set on the exporter and  <p:ajax /> on the toggler. 

many thanks again.

**Comment by melloware** [comment]
Great news!  Thanks for testing.
