### ISSUE TITLE
p:layoutUnit needs a collapsable title

### ISSUE THREAD

**Issue by dariorios** [primefaces/primefaces#881]
I have noticed that the button that appears in the p:layoutUnit, if I use a screen reader, if just say 
"link". I would like to change this title with a custom title. 

This solution can be achieve if you have any attribute that change the title, or you can use the same collapsabletitle from the p:layout. This line is the one I figured that should add a possible title inside the span.

 togglerContent_closed: <a href="javascript:void(0)" class="ui-layout-unit-expand-icon ui-state-default ui-corner-all"><span class="ui-icon ui-icon-arrow-4-diag"></span></a>

**Comment by melloware** [comment]
Also for those of you that use Layout I got this note from OptimusPrime...

> Cagatay Civici added a comment - 13/Mar/18 8:14 AM
> Note that Layout component is deprecated in 6.2.x in favor of css driven modern layouts.

So it looks like Layout will be removed in 6.3 so you may want to start switching your projects over to using PrimeFaces Extensions version of Layout which will remain supported.

**Comment by melloware** [comment]
@tandraschko @Rapster  safe to close this enhancement ticket since Layout is deprecated.

**Comment by Rapster** [comment]
Agreed
