### ISSUE TITLE
selectOneButton: Loosing value when same button is clicked twice in succession

### ISSUE THREAD

**Issue by KimGabrielsen** [primefaces/primefaces#8811]
### Describe the bug

I have a number of selectitems under a selectOneButton.
each selectitem has a distinct value.
When I click the same button twice the value in the backing bean is reset on click no 2. If I click the same button again yhe value in the backing bean will have the correct value.

### Reproducer

[pf-8811.zip](https://github.com/primefaces/primefaces/files/8749541/pf-8811.zip)

I have the following view and controller:

```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>Products</title>
        <style type="text/css">
            html {
                font-size: 14px;
            }
        </style>
    </h:head>

    <h:body>
        <h:form id="mainForm"  enctype="multipart/form-data" >
            <p:selectOneButton id="whatToShow" value="#{testController2.view}"   >
                <p:ajax  listener="#{testController2.changeDataView}"  
                          />
                <f:selectItem itemLabel="Value 0" itemValue="0" />
                <f:selectItem itemLabel="Value 1" itemValue="1"/>
                <f:selectItem itemLabel="Value 2" itemValue="2"/>
                <f:selectItem itemLabel="Value 3" itemValue="3"/>
            </p:selectOneButton>
        </h:form>
    </h:body>
</html>
```

and controller:

```java
@Data
@Named
@ViewScoped
public class TestController2 implements Serializable{

    int view = 0;

    public void changeDataView(AjaxBehaviorEvent aview) {
        System.out.println("View =" + view);
        switch (view) {
            case 0 -> {
                System.out.println("Value 0");
            }
            case 1 -> {
                System.out.println("Value 1");
            }
            case 2 -> {
                System.out.println("Value 2");
            }
            case 3 -> {
                   System.out.println("Value 3");
            }
        }
    }
}
```

if you click the buttons strating from 0 to 3 you get:

INFO:   View =1
INFO:   Value 1
INFO:   View =2
INFO:   Value 2
INFO:   View =3
INFO:   Value 3

which is correct.

If you click button 3 again the output is

INFO:   View =0
INFO:   Value 0

which is wrong (i guess) since the value should be 
INFO:   View =3
INFO:   Value 3

again

### Expected behavior

I would expect the output to be

INFO:   View =3
INFO:   Value 3
INFO:   View =3
INFO:   Value 3
INFO:   View =3
INFO:   Value 3
INFO:   View =3
INFO:   Value 3

No matter how many times i click button no 3.

### PrimeFaces edition

Community

### PrimeFaces version

11.0

### Theme

Serenity

### JSF implementation

MyFaces

### JSF version

2.3

**Comment by melloware** [comment]
Confirmed with reproducer:
[pf-8811.zip](https://github.com/primefaces/primefaces/files/8749541/pf-8811.zip)

**Comment by melloware** [comment]
OK this is not an issue.  By default SelectOneButton is a "toggle" type button so the same thing happens even with Button 2

```
View =2
Value 2
View =0
Value 0
View =2
Value 2
View =0
Value 0
```

You can see each time a click it it `checks` and then `unchecks` the button which is why it goes back to 0.  If you don't want this behavior simply set `unselectable="false"` on the component that way it no longer toggle at least 1 button will always remain active.

https://primefaces.github.io/primefaces/11_0_0/#/components/selectonebutton?id=selectonebutton

Can you try that and see if it fixes your behavior?

**Comment by KimGabrielsen** [comment]
Yes it works... :-)
Sorry, my bad. I did not know about that flag.

Thanks.
