### ISSUE TITLE
Charts: Merge all components into one component

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#8819]
### Description

Merge all chartJS components into one component.

<p:barChart>
<p:lineChart>
....

One chartJS component:

<p:chartJS  type="bar" model="#{bean.model}">

The benefit is that: only one chart component is needed to render all different charts for an iterating container component.

### Describe the solution you would like

One chartJS component:

<p:chartJS  type="bar" model="#{bean.model}">

The benefit is that: only one chart component is needed to render all different charts for an iterating container component.

**Comment by melloware** [comment]
I think PrimeTek did this as a conscious decision to speparate from the old JQuery Charts which did something similar to the above.

Some recommendations:

1. It should be `<p:charts` all lowercase and not call out the technology "chartsJS" in it.
2. It can be in addition to the existing renderers to make it backwards compatible with the existing code. It would just be adding ANOTHER additional renderer for convenience.

**Comment by Rapster** [comment]
I've mentionned that "problem" when chartjs for PF has been released, see here https://github.com/primefaces/primefaces/issues/4011#issuecomment-418752368. It'd be a lot easier to have one component instead of n number of chartjs component. Also, there is no need AFAIR to have multiple renderers. Simply serialize your input model in JSON, give it to chartjs and it's done ;)

**Comment by melloware** [comment]
Yeah I just didn't want to break backward compatibility of people already using the existing renderers throughout their apps?

**Comment by Rapster** [comment]
And you won't, the idea is to create a new component `p:chartjs` which won't reuse existing renderers. AFAIR, my solution is really dependant on a "good" json serializer, I used gson in the past, and I don't know how much you can do with json.org though

**Comment by melloware** [comment]
OHHH you want a whole new component that doesn't use our JSON object model just pass it JSON.  THat is similar to how PrimeReact does it.

**Comment by Rapster** [comment]
I would still use java object, not plain json as input (but we could simply introduce an extender if necessary). I still have this PR that showed how I've done it https://github.com/primefaces/primefaces/pull/4031/files

**Comment by Rapster** [comment]
Closing it in favor of #10870
