### ISSUE TITLE
Client Localization Links in Doc are pointing to wrong place / primefaces/docs/11_0_0/core/localization.md

### ISSUE THREAD

**Issue by horstLei** [primefaces/primefaces#8827]
hi all
at the moment the link to the localization is pointing to https://github.com/primefaces/primefaces/tree/master/src/main/resources/META-INF/resources/primefaces/locales this link ends in 404
it should be
https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales
master/**primefaces**/src... the difference
it seems all links pointing to the master have a problem next example same problem
GitHub Server Message Bundle Files: (https://github.com/primefaces/primefaces/tree/master/src/main/resources/org/primefaces)

I'm not sure if this is generated therefore I don't offer a fix..
br horst

**Comment by melloware** [comment]
Thanks for reporting this has been fixed. I am merging now but it may take a few minutes before the DocGen site reflects the changes
