### ISSUE TITLE
all day event in schedule change the event visualization

### ISSUE THREAD

**Issue by dariorios** [primefaces/primefaces#883]
When we choose the schedule and we add an event, for example we choose  from date 11-11-2015 00:00 to 13-11-2015 23:59 without all day checked, it works well. But when we check the all day button, it shows in the graphic schedule only dates from 11-11-2015 to  12-11-2015.

You can try this in the primefaces showcase.

**Comment by OBreidenbach** [comment]
This is a duplicate of #1164.
