### ISSUE TITLE
AccordionPanel: Wrong style when using single tab.

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#8833]
### Describe the bug

The tabs of an accordionPanel are styled depending on whether it's the first, last or any other tab of the accordionPanel. This way, the first tab gets rounded top borders and the last tab gets rounded bottom borders (see code). When I use an accordionPanel with only one tab, I expect the tab to have rounded top and bottom borders as it's the first and last tab at the same time but it only gets the styles of ".ui-accordion-header-last".

```
.ui-accordion {
    .ui-accordion-header {
        &:first-child {
            border-top-right-radius: $borderRadius;
            border-top-left-radius: $borderRadius;
        }
        &.ui-accordion-header-last {
            border-bottom-right-radius: $borderRadius;
            border-bottom-left-radius: $borderRadius;
        }
    }
}
```

### Expected behavior

When I use an accordionPanel with only one tab, I expect the tab to have rounded top and bottom borders.

### PrimeFaces version

10.0.0

### Theme

Diamond

**Comment by jepsar** [comment]
Can you please try if you can replicate this with the latest master?

**Comment by miedrl** [comment]
I tried it with the latest master SNAPSHOT and it works, thank you. Is there a fix release date for version 12.0.0?

**Comment by jepsar** [comment]
You can expect a RC soon (coming weeks). I don't have a specific date for you.

**Comment by melloware** [comment]
I think June they are shooting for 12.0

**Comment by miedrl** [comment]
Thank you both :)
