### ISSUE TITLE
TabView: add global actions facet

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8835]
### Description

Currently an `actions` facet exists, but there are issues:

1. There is no way of adding a global (all tabs) facet.
2. The name is not in line with the `p:panel` facet `options` (see https://www.primefaces.org/showcase/ui/panel/panel.xhtml)
3. The outputted HTML could be better. Now the facets are rendered as additional list items in the `ul` containing the tabs.
4. Documentation, integration tests and showcase are lacking.

Introduced with https://github.com/primefaces/primefaces/issues/2666

### Describe the solution you would like

1. Introduce a global facet (on `tabView`).
2. Rename facet to `options`.
3. Render a separate element with the options.
4. Add.

**Comment by zsuiqiang** [comment]
Very useful features

**Comment by anuragnz** [comment]
Please add this feature. At the moment we are adding action facets to every tab which is repetitive.
