### ISSUE TITLE
Selenium test framework: TimeoutException using CommandLink with p:confirm

### ISSUE THREAD

**Issue by nettozahler** [primefaces/primefaces#8836]
### Describe the bug

Running a Selenium test on Firefox using CommandLink with p:confirm fails with TimeoutException.

### Reproducer

Will provide a pull request with an appropriate integration test producing the error.

### Expected behavior

Selenium test runs fine without TimeoutException.

### PrimeFaces edition

Community

### PrimeFaces version

11

### Theme

Any

### JSF implementation

MyFaces

### JSF version

2.2

### Browser(s)

Firefox 100

**Comment by melloware** [comment]
Interesting.  You mentioned Firefox but it looks like its failing on all browsers.

**Comment by melloware** [comment]
Thanks for the tests I fixe the underlying problem and they are all passing now.

**Comment by nettozahler** [comment]
Great. Big thanks for the quick solution.
