### ISSUE TITLE
TabView: Dynamic tabs causes ajax listeners to stop working with deferred outputPanel

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#8838]
### Describe the bug

p:tabView with dynamic="true", that has a tab with a p:outputPanel with deferred="true", will cause issues with other tabs if they are opened before the deferred loading is complete.

In our code, we have a first tab that has about a dozen different deferred output panels that enable the page to load immediately while the data in the background flows in. We want the user to be able to switch over to one of the other dozen or so tabs at any time. Because there is so much data on the other tabs too, we set the tabView to dynamic.

What we noticed was that while the deferred loading was happening on the first tab, if the user switched over to the second tab, some functionality would just not work. Datatables loaded correctly but command buttons wouldn't work.

I've recreated this is a very simple example using primefaces-test.

We are using Primefaces 10.0.6 at work, I recreated it in 10.0.12. I don't have the bandwidth right now to upgrade our system to 11.x, but the primefaces-test is using 11.0.0 and that is experiencing the same issue. I also tried primefaces-test with 10.0.12 and confirmed it's the same. If this could possibly be fixed for 10.x that would be awesome.

### Reproducer

https://github.com/firsthour/primefaces-test

There are two tabs in this scenario in a tabView where dynamic="true".

The first tab has an outputPanel where deferred="true". It's simply wrapping a getter that returns a String, but there is a five second sleep inside.

The second tab is simply a commandButton that increments a counter when pressed, and updates itself to indicate how many times it has been clicked.

When I wait the full five seconds on the first tab, the second tab functions as expected.

When I switch to the second tab before the first tab completes its deferment, the button functions properly until the first tab completes. Then it stops responding.

### Expected behavior

The commandButton on the second tab should respond properly no matter the state of the first tab.

### PrimeFaces version

11.0.0

**Comment by melloware** [comment]
Excellent reproducer.  Confirmed.

**Comment by tandraschko** [comment]
@melloware do we really need a confirmed label? we already have "cant replicate" as opposite

**Comment by jepsar** [comment]
We had the same discussion on Discord. I think removing the new "needs triage" will have the same effect and leaves us with less tags in the end.

**Comment by tandraschko** [comment]
we even have "needs investigation" - feels all much to much now

**Comment by melloware** [comment]
Yep my original idea was "confirmed" once a core dev actually confirmed it was a real issue but now we add "Needs Triage" on new tickets and we simply remove that label once a core dev has looked at or verified a ticket.

**Comment by tandraschko** [comment]
for me it doesnt matter if we do it that or the other way, we just should not have 4 labels with the same meaning

**Comment by tandraschko** [comment]
process=@this on the button fixes it

**Comment by tandraschko** [comment]
also the problem is related to async=true default on deffered outputPanel

i wont invest time here, maybe not resolveable or i costs me many many time

feel free to dig deeper by yourself or sponsor a fix

**Comment by firsthour** [comment]
That's disappointing but I understand. Our pages are too complex to add process=@this to every susceptible element but I will see if we can cover the worst cases.

I will also look into sponsorship.

**Comment by melloware** [comment]
I agree @tandraschko this is a complex use case and issue and not worth the time to try and spend hacking a fix for.  I am going to mark it as such and since a workaround has been provided i think that is the best we can do.
