### ISSUE TITLE
Schedule: Tooltips are transparent and lack padding

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8839]
### Describe the bug

Tooltips are transparent and lack padding.

<img width="333" alt="Screenshot 2022-06-02 at 09 22 21" src="https://user-images.githubusercontent.com/7500178/171576915-1d2a7891-6ec0-442a-b330-e7c3412c9875.png">

<img width="338" alt="Screenshot 2022-06-02 at 09 22 34" src="https://user-images.githubusercontent.com/7500178/171576921-7ab2b1ca-f939-4a38-ae14-68be87e992e6.png">

<img width="181" alt="Screenshot 2022-06-02 at 09 26 51" src="https://user-images.githubusercontent.com/7500178/171576925-117cff34-b903-4b9b-a2d1-1af1b6fd1950.png">

### Reproducer

https://www.primefaces.org/showcase/ui/data/schedule/configuration.xhtml

Mouse over events.

### Expected behavior

Tooltips have a background matching the theme and some reasonable amount of padding.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0, 12.0.0-SNAPSHOT

**Comment by melloware** [comment]
This has been reported before. This is how it is in raw FullCalendar too.  I have no idea why.  Most examples show it using custom tooltips with Popover and Bootstrap but we don't want to do that.

**Comment by jepsar** [comment]
The least we can do is set the theme background. Like this it is not usable. Especially in week view.

**Comment by melloware** [comment]
Yep have you found the proper CSS style to set?

**Comment by jepsar** [comment]
Yes, well, I can do a default padding and use the CSS background var. It would have been ideal if we had more CSS variables like space sizes 😄

**Comment by melloware** [comment]
I would submit a PR if you can or post here what CSS they need to add to the themes if possible so Mert doesn't have to try and figure it out.

**Comment by jepsar** [comment]
Sure, will do!
