### ISSUE TITLE
Selenium test framework: TimeoutException when downloading a (text) file

### ISSUE THREAD

**Issue by nettozahler** [primefaces/primefaces#8840]
### Describe the bug

Running a Selenium test on Firefox featuring the download of a (text) file fails with TimeoutException.

Remark: I have also seen UnsupportedOperationException during file download (maybe with HTMLUnitDriver which is not yet supported by PF Selenium test framework) when the onload.js sees an "empty" http response.

### Reproducer

Will provide a pull request with an appropriate integration test producing the error.

### Expected behavior

Selenium test runs fine without TimeoutException.

### PrimeFaces edition

Community

### PrimeFaces version

11

### Theme

Any

### JSF implementation

MyFaces

### JSF version

2.2, 2.3

### Browser(s)

Firefox 100, maybe all browsers

**Comment by melloware** [comment]
Maybe I am wrong but we don't have tests for any Downloads as most selenium drivers as far as I know don't support capturing the downloaded file so there is nothing you can verify?

**Comment by melloware** [comment]
Its timing out because it is guarding an AJAX link even though AJAX=False but I am still not sure what would happen as this response. Meaning how would you capture that the file was actually downloaded?

**Comment by nettozahler** [comment]
I can speak for Firefox and HTMLUnitDriver (although the latter is not supported by PF Selenium framework). With HTMLUnitDriver the downloaded binary (or text) content is available as page via driver.getPageSource(). In Firefox there is indeed no way (known to me) to capture the downloaded file.

But anyhow my application offers various downloads of Excel and PDF documents, and I must verify these parts continuously with my Selenium tests. So testing downloads should at least throw no exceptions inside PF Selenium framework.

And I want to see in my code coverage tool that the source code creating Excel and PDF documents as well as the download part was executed during the test suite.

A hack to (partly) verify the download could be to set a cookie for the download response and check its existence in Selenium by using webDriver.manage().getCookieNamed(String). This does not verify the downloaded content but it shows that one has received the expected HTTP response.

**Comment by melloware** [comment]
OK i understand. Also curious why you are doing your FileDownload that way and not the PF way?

```xml
<p:commandButton value="Download" ajax="false">
            <p:fileDownload value="#{fileDownloadView.file}"/>
</p:commandButton>
```

???

**Comment by tandraschko** [comment]
not sure if selenium supports something but in theory we could try to check the PF downlook cookie if p:fileDownload is used

**Comment by melloware** [comment]
Agreed. The other issue is right now with `ajax=false` it is guarding it for HTTP even though this is a download and that is the Timeout.

I can't see any attribute in the DOM on the button that we can check for so we can click this button unguarded when its a download. 

```java
public void click() {
        WebElement button = getRoot();
        PrimeSelenium.waitGui().until(PrimeExpectedConditions.visibleAndAnimationComplete(button));
        PrimeSelenium.waitGui().until(ExpectedConditions.elementToBeClickable(button));

        if (button.getAttribute("data-pfconfirmcommand") != null) {
            // Confirm Dialog/Popup we don't want to guard for AJAX
        }
        else if (isAjaxified("onclick")) {
            button = PrimeSelenium.guardAjax(button);
        }
        else if ("submit".equals(button.getAttribute("type"))) {
            button = PrimeSelenium.guardHttp(button);
        }

        button.click();
    }
```

**Comment by jepsar** [comment]
You can download with<del>out</del> Ajax since 10

**Comment by melloware** [comment]
Yep but if you look at his IT test he isn't using `p:filedownload` is he is sending the file to the browser manually.

**Comment by melloware** [comment]
OK I got his branch working but since there is asbolutely no way to tell it not to guard for HTTP as a `submit` button I added an overloaded `clickUnguarded()` method to the button and link.

https://github.com/primefaces/primefaces/pull/8847

**Comment by nettozahler** [comment]
Until now I was not aware that there is a special PF way of doing file downloads :) therefore I was using the legacy way. If the PF way with p:fileDownload solves my problem and is working with Selenium I could also use this.

Does p:fileDownload also offer response header settings like this;

        ```
setResponseHeader("Content-Disposition", header);
setResponseHeader("Cache-Control", "no-store, no-cache, must-revalidate");
setResponseHeader("Pragma", "public, no-cache"); // For HTTP 1.0
```

**Comment by melloware** [comment]
@nettozahler if you use the example: https://www.primefaces.org/showcase/ui/file/download.xhtml?jfwid=f8de4

The DefaultStreamContent adds the headers for you...

![image](https://user-images.githubusercontent.com/4399574/171665952-3ce3a54b-81fc-492d-acea-4dfefe646e82.png)

As for Cache Control I highly recommend OmniFaces CacheControlFilter: https://showcase.omnifaces.org/filters/CacheControlFilter

**Comment by melloware** [comment]
Also welcome @nettozahler you are the first person in a while reporting PrimeSelenium issues and tests and we appreciate the feedback and suggestions!

**Comment by nettozahler** [comment]
Regarding the testability of file downloads I would like to add that it is possible to configure Firefox (not sure for other browsers) so that it downloads files of certain types (e. g. PDF) to the download folder without prompting (no "Save as..." dialog). With such a configuration it should be quite easy to write an integration test for file downloads even with verification of the downloaded content.

**Comment by melloware** [comment]
If you want to take a crack at it a `p:filedownload` Integration Test would be very welcome in our suite!

**Comment by seinecle** [comment]
Follow up: in Selenium, Chrome has a headless mode which [allows to retrieve the downloaded file](https://stackoverflow.com/questions/45631715/downloading-with-chrome-headless-and-selenium).

I just tested it on [this PF download button](https://github.com/seinecle/nocodefunctions-web-app/blob/349a181d1f3660b013046a015a2907e0fd29aec0/src/main/webapp/umigon/results.xhtml#L59) and it saves indeed the file on my local disk.
