### ISSUE TITLE
DatePicker: Month-Picker with manual input throws JS error

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#8843]
### Describe the bug

A manually entered year-month in the Month-Picker will produce JS error while typing:

![image](https://user-images.githubusercontent.com/3531183/171596245-fc738e11-00a1-4957-863b-812833312b39.png)

### Reproducer

Showcase: https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml?jfwid=3145d

Open the web console.

Start typing in the input for `Month Picker (java.time.YearMonth)`. The expected format is `MM/YYYY`.
As long as the month is not "fully" entered, each key press will produce a JS error.

### Expected behavior

No JS error should be thrown

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.1.19

### Browser(s)

Chrome Edge 101.0.1210.53

**Comment by tandraschko** [comment]
Did you try on master? i remember a similar issue

**Comment by fanste** [comment]
A possible fix could be to add `this.isDate(this.value)` in line https://github.com/primefaces/primefaces/blob/e16f2fddf1e4f0a0af5ebfc6381874d0b32b6d24/primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js#L515

**Comment by melloware** [comment]
I have confirmed the issue is in 12.0 and the fix works as suggested

**Comment by fanste** [comment]
> I have confirmed the issue is in 12.0 and the fix works as suggested

Thanks for the fix.

I was not able to load the SNAPSHOT from Jitpack, as our company proxy is really picky...
A custom build was planned for tomorrow.

**Comment by melloware** [comment]
Thanks for reporting i will merge this today.
