### ISSUE TITLE
FileUpload: Shrink Large Image Before Upload to Server

### ISSUE THREAD

**Issue by mafaul** [primefaces/primefaces#8844]
### Description

Files are uploaded from users, sometimes over expensive or slow mobile networks.
Resizing (make smaller) images before upload would be amazing.

### Describe the solution you would like

Add a property on p:fileUpload called 'maxUploadImageWidth' that will reduce the image size (keeping proportions) if the uploaded file is an image, and if it exceeds the maximum width (in pixels).

One option is to use the canvas to do the resize:
https://imagekit.io/blog/how-to-resize-image-in-javascript/

### Additional context

https://forum.primefaces.org/viewtopic.php?t=31421

**Comment by melloware** [comment]
Can you do this yourself already with `onupload` method?

> Advanced Mode Only. Callback to execute before the files are sent. If this callback returns false, the file upload request is not started

You could shrink the file with JavaScript yourself before sending it to the the server?

**Comment by melloware** [comment]
Actually I think you would have to override some JS code of the uploader to inject this ability to shrink files.

**Comment by jepsar** [comment]
> Actually I think you would have to override some JS code of the uploader to inject this ability to shrink files.

Yeah, think so too. I'm not sure if I correctly remember this, but aren't there plans to rewrite the upload widget code at PrimeTek?

**Comment by melloware** [comment]
I don't know if they talked about a new Uploader since the other 3 libs PrimeVue/React/Ng are all client side and not sure they have all the features we are currently using from BlueImp.

**Comment by melloware** [comment]
I think I am going to close this for now as I don't think its something we should add to core.  @mafaul if you do get it working with custom Javascript please post your solution here so we can have it for others!
