### ISSUE TITLE
There is no Modal 

### ISSUE THREAD

**Issue by oguzhannkayaa** [primefaces/primefaces#8845]
### Description

How it does not have modal? I can't find in Ultima react. Also in primefaces.

### Describe the solution you would like

Feature add

**Comment by jepsar** [comment]
This is not the PrimeReact issue tracker

**Comment by melloware** [comment]
This is PrimeFaces you want PrimeReact.  You can see modal here: https://primefaces.org/primereact/dialog/

You are missing this CSS
```css
:root {
    --maskbg: rgba(0, 0, 0, 0.4);
}
```
