### ISSUE TITLE
Discussion: PrimeSelenium support for HTMLUnitDriver?

### ISSUE THREAD

**Issue by nettozahler** [primefaces/primefaces#8850]
### Description

Currently PrimeSelenium test framework is supporting Chrome, Firefox and Safari. Even the HEADLESS mode is available (not for Safari). This is all fine.

My integration tests are running with PrimeSelenium on a bigger build server landscape with various build nodes. These build nodes are behind firewalls so opening http(s) connections to the outer world are impossible. Even DNS resolution for public servers e. g. github.com does not work on the build nodes. Therefore I assume stuff like io.github.bonigarcia.wdm.WebDriverManager cannot be used.

Moreover, I do not have admin access to these build nodes so installing any software like browsers (e. g. geckodriver) is impossible.

To deal with these limitations I am using PrimeSelenium with HTMLUnitDriver so far because this driver can be bundled with my application EAR in TEST scope and runs HEADLESSly without any local installation. This works with some quirks, but the problem is that HTMLUnitDriver is currently not supported by PrimeSelenium.

Are there any alternatives for my build node scenario or would it be possible to add support for HTMLUnitDriver in PrimeSelenium?

### Describe the solution you would like

Support for HTMLUnitDriver in PrimeSelenium like for other browsers.

**Comment by melloware** [comment]
I have never worked with the HTMLUnitDriver but i would think it would be possible to add it to this class: https://github.com/primefaces/primefaces/blob/master/primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/DefaultWebDriverAdapter.java

**Comment by melloware** [comment]
Actually this might be a question for @tandraschko but you might be able to plug it in with the SPI.

`import org.primefaces.selenium.spi.WebDriverAdapter;` looks like the interface the DefaultDriverManagerFactory implements but you could easily implement an HtmlUnit version.

**Comment by nettozahler** [comment]
While these can be the first steps to integrate HTMLUnitDriver, I must admit that there is more to do, maybe even in core PF code. For example when testing my application I have learned that p:fileupload with mode="advanced" and dragDropSupport="true" does not work at all with HTMLUnitDriver throwing weired exceptions I could not solve. So for testing I had to fall back on mode="simple", skinSimple="false" and dragDropSupport="false".

What I want to say is that supporting HTMLUnitDriver means that you have one more platform to take care of either by adapting PF core classes to work on it or by filing bug reports against HTMLUnitDriver to be fixed. It should be discussed first if it is worth the effort.

**Comment by melloware** [comment]
so i will say I can guarantee we won't fix PF core classes to support an integration testing driver.  That would violate everything I believe in software development that touching production code to "fix" testing is an absolute no no.    

I thought you were saying it all works with HtmlUnitDriver...what you are stating is we would need to start fixing (aka hacking) core PF components to make it work with HtmlUnitDriver and that I know PrimeTek will not allow.  

Sorry I misunderstood your original request!

**Comment by tandraschko** [comment]
+1 melloware
