### ISSUE TITLE
DataExporter: columns with visible="false" are not exported anymore

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#8856]
### Describe the bug

It looks like that recently the DataExporter must have been changed fundamentally such that columns with attribute visable="false" are not exported anymore! 

I have a many code fragments using the following patterns where the GUI and the exported files have different outputs:

```
<p:column exportable="false" field="x" headerText="x">
   ... visible but non-exportable column of the field with potentially some complex things to be printed only in then GUI but not (intented to be) exportable ...
</p:column>
<p:column visible="false" field="x" headerText="x">
   ... invisible column of the same field used only for export purposes ...
</p:column>
```

Would be great if the original semantics would still work as it was all the years.

Many thanks in advance.

### PrimeFaces version

12.0.0 snapshot as of last week

**Comment by melloware** [comment]
It was fixed in the defect you reported? https://github.com/primefaces/primefaces/issues/8804  you can't have it both ways... either visible exports or it doesn't export with exporter `visibleOnly="true"` flag?  You can set that to `false` to restore the original behavior.

**Comment by tuerker** [comment]
@melloware many thanks for hint. i had this revision not anymore on the radar. i will then set visibleOnly="false" for the exporter such that i have the old semantics.
