### ISSUE TITLE
Menu: Using RequestScoped model is broken

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8867]
### Describe the bug

Using a `@RequestScoped` model breaks in 12.0.0 due to #8443

### Reproducer

[pf-8443.zip](https://github.com/primefaces/primefaces/files/8863936/pf-8443.zip)

Use the reproducer in `@ViewScoped` and everything works and with `@RequestScoped` everything fails.

### Expected behavior

MenuModel should be backwards compatible with previous PF while fixing bugs

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-SNAPSHOT

### Theme

ALL

### JSF implementation

All

### JSF version

ALL

### Browser(s)

ALL

**Comment by melloware** [comment]
cc @stolp 

**PF < 11:**
menuid was coordinates of menu like `2_1`

**PF 12 Update/ Elite 11.0.5:**
menuid was made a UUID `561231c6-354a-4842-8086-81d00531fde3` however this does not work for RequestScoped beans as the menu id is lost.

**PF 12 With this fix:**
menuid is now`UUID|Coords` like `561231c6-354a-4842-8086-81d00531fde3|0_3` where it will try and use the ID and if the ID cannot be matched it falls back to the Coords check using `0_3` in the example above

**Comment by mertsincan** [comment]
Thanks a lot, @melloware!
