### ISSUE TITLE
Printer : component does not display contents properly under certain circumstances.

### ISSUE THREAD

**Issue by tarwork** [primefaces/primefaces#8869]
### Describe the bug

I am using the p:printer component to help the user only print the contents of my page so the header and footer of app is not also printed. What is happening however is the printer components' results seem to be dependent on whether the browser is in full screen or not full screen. In full screen the target text is painted on top of each other. When the browser window is much smaller than full screen the text is displayed with no overlap.

attached files:
1. primefaces test reproducer
2. screenshot of browser at full screen results
3. screenshot of browser at half 
4. PDF file results of full screen
5. PDF file results of half screen

![full screen](https://user-images.githubusercontent.com/67923229/172709080-cc0b0978-ab68-4f95-bbbe-839635c9567d.jpg)

![half screen](https://user-images.githubusercontent.com/67923229/172709082-e3046125-0da5-40db-9007-22b6ea2b15c6.jpg)

[full screen.pdf](https://github.com/primefaces/primefaces/files/8864800/full.screen.pdf)

[half screen.pdf](https://github.com/primefaces/primefaces/files/8864803/half.screen.pdf)

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/8864784/primefaces-test-master.zip)

### Expected behavior

expected behavior is that regardless of browser screen size the contents of the page should not overlap itself in the printer component.

### PrimeFaces edition

Community

### PrimeFaces version

11.x.x

### JSF implementation

Mojarra

**Comment by melloware** [comment]
Tested with 12.0.0 and its working fine.  See this ticket for a workaround: https://github.com/primefaces/primefaces/issues/8232

![image](https://user-images.githubusercontent.com/4399574/172839789-f74db1b8-8e58-4b3d-86bf-0d8c1d82f9f6.png)
