### ISSUE TITLE
picklist buttons text attributes

### ISSUE THREAD

**Issue by dariorios** [primefaces/primefaces#887]
Just like the implementations of addLabel, addAllLabel, removeLabel, removeAllLabel to show a title for the button of the picklist. It is necessary to have attributes for the text of the buttons. At this moment the value for this span button is "ui-button"

**Comment by mertsincan** [comment]
Fixed for 5.2.16, 5.3.3 and 5.4. 
Issue; https://github.com/primefaces/primefaces/issues/907

**Comment by borchvm** [comment]
hello, I posted on stackoverflow.com an alternative to add text to the PickList of primefaces using css style sheet 

[https://stackoverflow.com/questions/70086529/customize-the-text-of-the-picklist-buttons-of-primefaces/70086727#70086727](url)

![picklist changed2](https://user-images.githubusercontent.com/54710757/143092877-42b3fbec-a847-4892-b5da-6c1ab36ddb16.png)

I hope it can serve you until it is implemented

**Comment by jepsar** [comment]
This issue is closed and it about the **titles**. We could open a new issue to render text on the buttons and use the title values for it. Happy to provide a PR for such a feature.

**Comment by jepsar** [comment]
This issue is about the tooltip labels. To render them as text on the buttons instead of tooltips, use `labelDisplay="inline"`.
