### ISSUE TITLE
Diagram: not working properly when MaxConnections = 1

### ISSUE THREAD

**Issue by antonioalveslopes** [primefaces/primefaces#8876]
### Describe the bug

Endpoint's Diagram is not working when maxConnections equals 1.
Checking the source code of DiagramRender.java, I checked that at method encodeEndpoint:
```
if (maxConnections != 1) {
            wb.append(",maxConnections:").append(maxConnections);
        }
```
If I change that condition to 
```
if (maxConnections != 0) {
            wb.append(",maxConnections:").append(maxConnections);
        }
```

Then it'll work normally.

I also check on canvas object on JS side, that when maxConnection is set to 1, because of that piece of code, the maxConnections is not present, which makes the connection not work properly.

### Reproducer

1 - Create a diagram with no maxConnections set;
2 - Create a target endpoint with maxConnections = 1;
3 - Create a source endpoint with maxConnections = -1;

Try to connect both elements and it'll not work.

### Expected behavior

The source and target be able to connect

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF version

2.3

### Browser(s)

Chrome

**Comment by melloware** [comment]
Thanks for the report. I actually think it should be `if (maxConnections > 0) {` ??? Basically any positive number but 0 and negative numbers ignored.

**Comment by antonioalveslopes** [comment]
> Thanks for the report. I actually think it should be `if (maxConnections > 0) {` ??? Basically any positive number but 0 and negative numbers ignored.

Hi!!
But it has to accept "-1" for represent inifinity connections. isn't it?

**Comment by melloware** [comment]
Oh OK i was looking in the JSPlumb docs and couldn't find the definition for MaxConnections and what its possible values are.  I will change it back to your suggestion `!= 0`.

**Comment by melloware** [comment]
Ahh found it "A value of -1 means no upper limit." https://www.art2dec.co/jslab/jas/jsplumb/dist/apidocs/classes/Endpoint.html
