### ISSUE TITLE
InputTextRenderer encodeScript can end in a Nullpointer

### ISSUE THREAD

**Issue by horstLei** [primefaces/primefaces#8880]
### Describe the bug

the code part 
`protected void encodeScript(FacesContext context, InputText inputText) throws IOException {
        String counter = inputText.getCounter();
        WidgetBuilder wb = getWidgetBuilder(context);
        wb.init("InputText", inputText)
                .attr("maxlength", inputText.getMaxlength(), Integer.MIN_VALUE);
       if (counter != null) {
            UIComponent counterComponent = SearchExpressionFacade.resolveComponent(context, inputText, counter);

            wb.attr("counter", counterComponent.getClientId(context))
                    .attr("counterTemplate", inputText.getCounterTemplate(), null)
                    .attr("countBytesAsChars", inputText.getCountBytesAsChars());
        }

        wb.finish();
    }`

has one problem `if (counter != null)`if counter is empty => you go inside the if and then the counterComponent IS NULL

`Caused by: java.lang.NullPointerException
	at org.primefaces.component.inputtext.InputTextRenderer.encodeScript(InputTextRenderer.java:72)
	at org.primefaces.component.inputtext.InputTextRenderer.encodeEnd(InputTextRenderer.java:60)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)`

problem occurred if I wrap the inputText element inside a CC and transmit ALL attributes no matter if filled or not...
this would be a improvement for being more stable

### Reproducer

add a 
<p:inputText id="counterTestIT" counter=""/>

### Expected behavior

either the check on if(counter != null) checks more:
VAR1) !StringUtils.isEmpty(counter)

or inside the if the counterComponent  will be checked if found 
VAR2) counterComponent != null 
before going on to work on widget builder

### PrimeFaces edition

Community

### PrimeFaces version

10.0.x, 11.0.x

**Comment by tandraschko** [comment]
@mertsincan elite candidate
