### ISSUE TITLE
DatePicker: DateTimeConverter for custom date type no longer working with Primefaces 11 

### ISSUE THREAD

**Issue by weissreto** [primefaces/primefaces#8883]
### Describe the bug

In our product we have our own Date, Time and DateTime classes. These classes has nothing to do with java.util.Date or the java.time.* classes. To support our own classes we have implemented own DateTimeConverters for them. These converters have worked fine in Primefaces 7 but do no longer with Primefaces 11.

The problem is located in the org.primefaces.util.CalendarUtils class in method getValue line 289. Here the type of the value are compared with the type that the converter provides. This is completely wrong as the type of the value is a Java class and the type the converter provides is not a Java class but a String that is either "date", "time" or "both".

The issue was introduced by https://github.com/primefaces/primefaces/pull/5925 and later modified by https://github.com/primefaces/primefaces/pull/6015.

The changes were made to fix a problem with the standard DateTimeConverter that is not able to handle java.time.* classes correctly. However the fix prevents that anybody can use their own DateTimeConverter for their own classes.

### Expected behavior

Our own DateTimeConverter should be called and not be ignored.

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.2

### Theme

Freya

### JSF implementation

MyFaces

### JSF version

2.2.13

**Comment by weissreto** [comment]
See also https://pro.primefaces.org/browse/AXONIVY-42

**Comment by jepsar** [comment]
Can you please try with `DatePicker` in PF 12? Conversion has been touched there. `Calendar` is no longer supported by the community.

**Comment by weissreto** [comment]
Yes, I know `Calendar` is no longer supported. I have the problem also with `DatePicker `in PF11. Can try to reproduce it with PF12 also. But I'm pretty sure it has the same behavior as the code I change to fix the issue has not changed in PF12. See my PR:
https://github.com/primefaces/primefaces/pull/8884

**Comment by christophs78** [comment]
> See also https://pro.primefaces.org/browse/AXONIVY-42

Can you please paste your converter into this issue? (I´m a commiter but do not have a Pro-account.) 
I probably have some idea what you are doing but would help to see your code too.

**Comment by tandraschko** [comment]
TBH i dont think this is an good change
A ConverterException says that the current value is not convertable -> e.g. a bad input on the UI and a error message will be shown the user
we now ignore the converter forever

either we introduce a own exception type or look for a nice and correct fix

user applied converters, doesnt matter if via annotation or component attr should be respected first

**Comment by tandraschko** [comment]
can anyone provide a simple primefaces-test, what works in 11 and fails in 12?

**Comment by melloware** [comment]
Yes give me a couple of minutes...

**Comment by melloware** [comment]
Reproducer: [pf-8883.zip](https://github.com/primefaces/primefaces/files/8933619/pf-8883.zip)

Works in 8.0 but if you switch the pom.xml to 11.0.0 you will then see the error.

**Comment by tandraschko** [comment]
yeah
there is no reason that our own converters should be used over the attached one
the PR is just a weird hack around that

**Comment by tandraschko** [comment]
how can i replicate the issue exactly after reverting the change?

**Comment by christophs78** [comment]
> how can i replicate the issue exactly after reverting the change?

DatePicker014Test?

**Comment by melloware** [comment]
My reproducer above is based exactly on his DatePicker014 Integration test which was the use case that was failing?  

If you revert the changes I would expect my reproducer would fail with 12.0.0-SNAPSHOT.

**Comment by weissreto** [comment]
Hi 

I agree that my PR is some kind of hack. Note, that I only catch ConverterException in case of converting object to string and not the other way round, string to object, that is called to parse user input. So the exception there is shown on the UI as always. 

For me the whole CalendarUtil is also a kind of hack. Why not just implement your own DateTimeConverter that covers java.time.* classes correctly? I think that would be more the way JSF works. 

Seeing forward for a better solution for this issue. Thanks for working on that.

Regards

**Comment by tandraschko** [comment]
i partly reverted the PR on my machine and still all tests are running fine

i will commit this partly revert now
