### ISSUE TITLE
DataTable: Enable row selection per button even if disabledSelection="true"

### ISSUE THREAD

**Issue by marw1tt** [primefaces/primefaces#8887]
### Description

When we worked with PrimeFaces 8.0 it was possible to set disabledSelection="true" on a p:dataTable so that the selection of a row was only possible by clicking on a designated button. With PrimeFaces 10.0 this was not possible anymore because if disabledSelection="true" was set, no rows were highlighted anymore, despite the current selection. So we could use that feature only with a nasty workaround. 

### Describe the solution you would like

I think the use case for this is still valid, and maybe it can be re-enabled. I will attach a PR. Let me know what you think about it. 

### Additional context

For example, I use the dataTable as follow: 
`
<p:dataTable var="car"
           value="#{dtBasicView.cars}"
           multiViewState="true" 
           rowKey="#{car.number}"
           selection="#{dtBasicView.selectedCar}"
           selectionMode="single" 
           disabledSelection="true"
           rows="60" paginator="true"
           lazy="false"
`

Important is disabledSelection="true" so that the user can not select rows per click on a row or cell. It should only be possible with a click on a button that is included in every row. 

That is made with a column that include a button like this:
` 
<p:column
            headerText="Action"
            width="80">
            <p:commandButton value="Select"
                  update="@all"
                  process="@this">
               <f:setPropertyActionListener value="#{car}" target="#{dtBasicView.selectedCar}" />
            </p:commandButton>
       </p:column>
`

That is like an example which is shown in the PrimeFaces documentation. So with PrimeFaces 10 I can select the row with that button, but the selected row is **not** highlighted as it should, which worked with PrimeFaces 8 (I also checked PF11 and the latest code base). 

So my changes make that in that case the selected row is now highlighted.

I hope this will help to understand why I need that change. If you need more information, I will be happy to provide some.

**Comment by melloware** [comment]
OK we can review your PR when you submit.

**Comment by marw1tt** [comment]
PR: [8887](https://github.com/primefaces/primefaces/pull/8888)

**Comment by Rapster** [comment]
Why don't you use an EL like disabledSelection="#{item.selected}" ?

**Comment by tandraschko** [comment]
+1 rapster

**Comment by melloware** [comment]
I updated the Additional Context with the exact use case trying to accomplish.

**Comment by marw1tt** [comment]
Hello Rapster, unfortunately disabledSelection="#{item.selected}" doesn't work for us because it is necessary for our workflow that the selection is strictly only possible with the click on the button within a row and as soon as disabledSelection=true, no row highlighting is available.

**Comment by Rapster** [comment]
Do you mind creating a reproducer with primefaces-test, so I could get a better grasp of what you want to achieve plz?

**Comment by marw1tt** [comment]
Yes, of course, I will provide one.

**Comment by marw1tt** [comment]
Here is a reproducer. If you select a row by clicking on a button, then no row selection highlighting is visible. If you use my changes, then the row selection highlighting is visible.
[primefaces-test-master_#8887.zip](https://github.com/primefaces/primefaces/files/8928980/primefaces-test-master_.8887.zip)

**Comment by Rapster** [comment]
Do this instead:

```xml
        <p:dataTable var="car" value="#{dtBasicView.cars}"
                     rows="60" paginator="true"
                     rowKey="#{car.number}" selection="#{dtBasicView.selectedCar}"
                     selectionMode="single" disabledSelection="#{!car.selected}">

            <p:column headerText="Action" width="80">
                <p:commandButton value="Select" update="@form" process="@form" action="#{dtBasicView.setSelected(car)}"/>
            </p:column>

            <p:column field="number"/>

            <p:column field="name"/>

        </p:dataTable>
```

And add this method in your bean:
```java
public void setSelected(Car car) {
        selectedCar = car;
        car.setSelected(true);
       // reset selected for others
}
```

I wonder if you really need to enable selection feature, maybe you should stick to your custom selection and forget what PF can do for you. It's most probably simpler that way

Out of scope, but avoid `@all` unless it's really really necessary

**Comment by melloware** [comment]
I agree with @Rapster you aren't really using PrimeFaces Selection at all so you should do as he recommended and use your custom selection.  Rather than try and use multiple flags to accomplish what you want which wouldn't be clear to most users anyway.

@marw1tt let me know what you think and I can close this ticket and PR if you agree.

**Comment by marw1tt** [comment]
I can check it on monday, till then I have no access. I will send a reply as soon as I verified that approach.

**Comment by marw1tt** [comment]
I checked that approach and it works. But it feels more like a workaround than my approach, and resetting the "selected" flag for all other entries seems a bit laborious. I could do this, if it were only just one table where I have to adjust that, but it is not. We have many other projects that depend on our framework, so we need a solution that can be done at one place.

A little bit background story to my use case, because it is not that uncommon. Years ago, we used the tomahawk data tables (t:dataTable) from Apache whose selection mechanic worked like my use case and the selection was made by a button within the corresponding row. Later we provided a component based on PrimeFaces dataTable, and we had to stay consistent to the existing tomahawk table, so that's why we had to use the same selection mechanic.

Apart from that, in my opinion the table should be able to highlight their selection, but it should not care where that selection comes from. So, disabling the ability to select a row within the table should not affect the table's ability to highlight the selection. Those two things should be separated from each other. Please let me hear your thoughts.

Short: disabledSelection != disabledHighlighting

**Comment by Rapster** [comment]
Like I said, you don't need PF selection feature. Mixing up your custom selection with PF selection will only make things harder IMO. All you need is your `selectedCar`, and to highlight row, see rowStyleClass attribute. You'll see that your final solution will be pretty straightforward and a lot more simple

**Comment by marw1tt** [comment]
```html
<p:dataTable var="car" value="#{carBean.cars}">
    <p:column>
        <p:commandButton value="Select">
            <f:setPropertyActionListener value="#{car}" target="#{carBean.selectedCar}" />
        </p:commandButton>
    </p:column>
    ...columns
</p:dataTable>
```
That example is given within the PF dataTable [documentation](https://primefaces.github.io/primefaces/10_0_0/#/components/datatable). Why is that example there? Is it outdated and that form of selection is not intended anymore? Because why should somebody implement that if the row can be selected by a click on the specific row? 

But despite from that, what is your opinion about "disabledSelection != disabledHighlighting"? I am interested in what you think.

**Comment by tandraschko** [comment]
in general this way of selection was always supported in the past, also see: https://github.com/primefaces/primefaces/issues/8406

so +0.5 from just merging your PR but we need to make sure that nothing else breaks

**Comment by melloware** [comment]
+1 from me only because it used to work and we removed functionality that was meeting a valid use case.

**Comment by Rapster** [comment]
> That example is given within the PF dataTable [documentation](https://primefaces.github.io/primefaces/10_0_0/#/components/datatable). Why is that example there? Is it outdated and that form of selection is not intended anymore? 

I don't know the whole history of this, but my guess is PF team probably wanted to show how to implement very basic selection before they could implement their own selection features

> Because why should somebody implement that if the row can be selected by a click on the specific row?

No idea, I wouldn't go that route for sure, knowing PF do the job pretty well

> So, disabling the ability to select a row within the table should not affect the table's ability to highlight the selection.

Ok, so I assume this is your "real" problem. I guess that could be considered as valid use case yes but we'll have to check if there are no other use cases that counter this :D

**Comment by marw1tt** [comment]
> Ok, so I assume this is your "real" problem. I guess that could be considered as valid use case yes but we'll have to check if there are no other use cases that counter this :D

Indeed, that is my problem. :-)

Let me know if I can support you somehow or if you need additional information etc.

**Comment by marw1tt** [comment]
Hi there, I just wanted to let you know, that I am on holiday for three weeks starting this weekend. There I have almost no internet access, so if you need something from me, I can only take care of it afterwards. So do not wonder if I do not reply to anything.

**Comment by melloware** [comment]
@Rapster I have tested this and in my scenarios I don't see anything broken and all of our Integration tests are passing.  If we do find any scenarios this doesn't work for we can re-open and address.

**Comment by Rapster** [comment]
Ok I think this https://github.com/primefaces/primefaces/issues/6682 could be a problem now

**Comment by christophs78** [comment]
For every DataTable-related change Integration-Tests should be provided too. This is the only way to avoid fixing one thing and breaking another one.
You may use https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable004Test.java as a template.

**Comment by melloware** [comment]
Yep it looks like we already had 4 different Selection based IT's.

**Comment by christophs78** [comment]
`disabledSelection` of `p:dataTable` is not yet covered by IT´s.
