### ISSUE TITLE
BlockUI: multiple hide/show conflicts

### ISSUE THREAD

**Issue by gatschet** [primefaces/primefaces#889]
I'm using PrimeFaces 5.1, OmniFaces version 1.7 on Mojarra 2.1.7-jbossorg-1.

What I want is a p:ajaxStatus with a loader.gif and a grayed content while some ajax request are running.

Here is my code in my template.xhtml page for ajaxStatus and the blockUI:

```
<p:ajaxStatus
    style="width:55px;height:55px;position:absolute; top: 0%; left: 50%; margin-left: -27px; margin-top: 25px; z-index: 100;"
    id="loadingRefresh" onstart="PF('bui').show();" oncomplete="PF('bui').hide();" onerror="PF('bui').hide();"
    onsuccess="PF('bui').hide()">
    <f:facet name="start">
        <h:graphicImage id="loading" library="images" name="ajax-loader.gif" />
    </f:facet>
    <f:facet name="complete">
        <h:outputText value="" />
    </f:facet>
    <f:facet name="error">
        <h:outputText value="" />
    </f:facet>
    <f:facet name="suceess">
        <h:outputText value="" />
    </f:facet>
</p:ajaxStatus>
<p:blockUI block="-content" widgetVar="bui" />
```

Here is my code on my test page test.xhtml

```
<ui:define name="content">

    <h:form id="testForm">

        <p:commandLink value="testLinkToOpenDialogBox" update="test"
            actionListener="#{myBean.doSomething()}" oncomplete="PF('testDialog').show()">
            <f:param name="aggregationDataId" value="5" />
        </p:commandLink>

        <p:dialog widgetVar="testDialog" header="test" >                
            <p:commandButton id="test" action="#{myBean.doSomething()}"></p:commandButton>
        </p:dialog>

    </h:form>

</ui:define>
```

If I click on my testLink to open the dialog box and when I click the test Button in the dialog box the loader.gif is displayed for a very short time and the  testLink is grayed for about 500ms.

The problem is now, when I click the test button for about 20 times very fast (and close the dialog box immediately), the testLink will be grayed out and is blocked for about 10 seconds. It seams, that the fade in and fade out time from p:blockUI is too long!
How can I avoid this problem? Is it possible to set the fade time to a smaller value?

I already tried "setTimeout($.unblockUI, 0);" but with no effect...

**Comment by melloware** [comment]
From the documentation simply set `animate=false` to fix this.
https://primefaces.github.io/primefaces/8_0/#/components/blockui?id=blockui
