### ISSUE TITLE
TreeTable: propagateSelectionUp="false" and propagateSelectionDown="false" is not working

### ISSUE THREAD

**Issue by mahi-ro** [primefaces/primefaces#8891]
### Describe the bug

`propagateSelectionUp = "false"` and `propagateSelectionDown = "false"` is not working.
Node selection is propagated.

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/8925642/primefaces-test-master.zip)

### Expected behavior

Node selection does not propagate.
Selecting a root node does not select a leaf node, and selecting a leaf node does not select a root node.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

Saga

### JSF implementation

All

### JSF version

2.3

**Comment by melloware** [comment]
Thanks for reporting I have verified your issue.

**Comment by melloware** [comment]
Its weird it was in the docs and in the TagLib.xml just never actually implemented.  Fixed for 12.0.0
