### ISSUE TITLE
Migration guide: InputMask change not mentioned in 6.2->7.0 migration guide

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#8892]
### Describe the bug

I'm migrating from PF 6.2 to 7.0. I'm following the migration guide at:
https://primefaces.github.io/primefaces/11_0_0/#/../migrationguide/7_0

However, I see no mention of the fact that `p:inputMask` does not accept an empty mask (empty string) any more.
In previous PF 6.2 I may want an `p:inputMask` substantially behave like a plain `p:inputText` in certain conditions, like this:

```xml
<p:inputMask value="#{myBean.postalCode}"
  mask="#{myBean.country == 'ITALY'? '99999': ''}" />
```

This causes an exception with PF 7.0:

```
16/06/2022 17:01:46  INFO [ajp-nio-192.168.240.75-8011-exec-6] (javax.enterprise.resource.webcontainer.jsf.context) - javax.faces.FacesException: InputMask requires a value for the 'mask' attribute.
javax.faces.FacesException: InputMask requires a value for the 'mask' attribute.
        at org.primefaces.component.inputmask.InputMaskRenderer.translateMaskIntoRegex(InputMaskRenderer.java:83)
        at org.primefaces.component.inputmask.InputMaskRenderer.decode(InputMaskRenderer.java:57)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:832)
        at javax.faces.component.UIInput.decode(UIInput.java:773)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1227)
        at javax.faces.component.UIInput.processDecodes(UIInput.java:678)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:574)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
[...]
```

I think this should be useful to know by people upgrading from an old version.
Also, a workaround would be appreciated. I now changed the mask definition with:

```
mask="#{myBean.country == 'ITALY'? '99999': '*?****'}"
```

but I know this is not perfectly equivalent. If you have any further suggestion on how I should set the mask to accept anything it will be appreciated.

### Reproducer

```xml
<p:inputMask value="#{myBean.postalCode}"
  mask="#{myBean.country == 'ITALY'? '99999': ''}" />
```

### Expected behavior

With an empty string, the `p:InputMask` should just accept any input and behave like a `p:inputText`. This is how it worked until PF 6.2.

### PrimeFaces edition

Community

### PrimeFaces version

7.0

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

Firefox

**Comment by jepsar** [comment]
Try `#{myBean.country == 'ITALY'? '99999': null}`

**Comment by melloware** [comment]
@mauromol the workaround I would use is to use the right component for the right job. I feel like what you were doing before doesn't make sense to me to use a Mask component without a mask.  I get it that it makes it convenient but it would be like saying "I want to use InputNumber but if not Italy I don't want it to be a number I want it to be a string".

I would do this..

```xml
<p:inputMask value="#{myBean.postalCode}"  mask="99999" rendered="#{myBean.country == 'ITALY'}" />
<p:inputText value="#{myBean.postalCode}"  rendered="#{myBean.country != 'ITALY'}" />
```

**Comment by melloware** [comment]
Migration Guide for 7.0 updated thanks!

**Comment by mauromol** [comment]
> @mauromol the workaround I would use is to use the right component for the right job. I feel like what you were doing before doesn't make sense to me to use a Mask component without a mask. I get it that it makes it convenient but it would be like saying "I want to use InputNumber but if not Italy I don't want it to be a number I want it to be a string".
> 
> I would do this..
> 
> ```
> <p:inputMask value="#{myBean.postalCode}"  mask="99999" rendered="#{myBean.country == 'ITALY'}" />
> <p:inputText value="#{myBean.postalCode}"  rendered="#{myBean.country != 'ITALY'}" />
> ```

This of course is an alternative. It's just more work. After all, I think that it shouldn't hurt in any way if a `p:inputMask` had no mask... it's just a special case of inputMask where I don't require any special mask to be proposed and validated.

Any way, the issue here was to let people know about the change. I saw the updated guide, which now states that "`mask` attribute is now required", but I would also add "and must not be empty". Indeed, my `mask` attribute was specified, but could be set to empty string in some cases and this triggers the problem all the same.

**Comment by melloware** [comment]
Actually looking at the Source code I don't see this exception so somewhere in PF 8.0, 10.0, 11.0 this requirement was removed,  Can you try a higher version?

**Comment by melloware** [comment]
Ahh here it is in 7.0.8 and 8.0: https://github.com/primefaces/primefaces/issues/5105  added a `validateMask="true"` or false property whether you want the mask validated on the server side.
