### ISSUE TITLE
GMap: DefaultMapModel: Warn when set ID is overwritten

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#8893]
### Describe the bug

If you have set ID on overlays and add them to the model, the IDs are overwritten.

https://github.com/primefaces/primefaces/blob/97c493fcce6f2e777929b41ea7034070557872f8/primefaces/src/main/java/org/primefaces/model/map/DefaultMapModel.java#L83-L104

Side effect is that `findOverlay` cannot work properly, as it expects generated IDs.

https://github.com/primefaces/primefaces/blob/97c493fcce6f2e777929b41ea7034070557872f8/primefaces/src/main/java/org/primefaces/model/map/DefaultMapModel.java#L108-L131

See also

https://github.com/primefaces/primefaces/blob/97c493fcce6f2e777929b41ea7034070557872f8/primefaces/src/main/java/org/primefaces/component/gmap/GMap.java#L89-L97

### Expected behavior

IDs should not be changed. Documentation should encourage to set your own ID.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-SNAPSHOT

**Comment by jepsar** [comment]
I think at least a warning should be logged when the ID is not null.

**Comment by melloware** [comment]
You mean log a warning if ID is not null and its not found as an overlay in `findOverlay` ?  I would be OK with that.

**Comment by jepsar** [comment]
Yes, I already added that to my next PR (in progress)
