### ISSUE TITLE
primefaces-showcase : crudView. create new product twice "failed"

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces#8898]
### Describe the bug

In crud.xhtml :

- hit "new" button
- cancel dialog
- hit again "new" button : the method crudView.openNew is not called and the "name" box appears in red.

How to fix it ?

### Expected behavior

The method crudview.openNew should be called even if the user has cancelled the previous creation.

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

**Comment by melloware** [comment]
Fixed it with this PR:  https://github.com/primefaces/primefaces/pull/8903

I broke the form into 2 forms and change the cancel button to `type="button"`.
