### ISSUE TITLE
DataTable filter input clear icon on IE10 doesn't trigger filtering

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#89]
With internet explorer 10 in each input field a "X" is drawn at the end of the field to clear the content. This is also drawn in the input fields for the column filters of a datatable. If I type something in the filter input field, the datatable contents will be filter after a delay. If I clear the content with backspace, delete or similar, all content will be displayed like before. If I clear the fields content with the "X", the filtered content remains.

**Comment by nchal** [comment]
As a workaround, you could don't display this 'X'.

``` css
input::-ms-clear {
    display: none;
}
```

More information here : http://stackoverflow.com/a/15467776
