### ISSUE TITLE
active p:menuitem in p:submenu

### ISSUE THREAD

**Issue by Gabrielcuadrosnavarro** [primefaces/primefaces#8907]
![imagen](https://user-images.githubusercontent.com/96390264/174507217-256effe5-02fa-4659-86ea-76ff142f6e2d.png)

i try this
<po:menu widgetVar="PoseidonMenuWidget">
<p:submenu label="Requests">
<p:menuitem value="test" outcome="/welcome"/>
<p:menuitem value="test2" outcome="/welcome_1"/>
</p:submenu>
</po:menu>

<po:menu widgetVar="PoseidonMenuWidget">
<p:submenu id="om_components" label="#{bundle.label_menu}" icon="pi pi-star-fill">
<p:menuitem id="om_dashboard" value="#{bundle.label_dashboard}" icon="pi pi-home" outcome="#{bundle.ruta_url_dashboard}"/>
<p:menuitem id="om_useradmin" value="#{bundle.label_gestion_usuario}" icon="pi pi-users" rendered="#{appMenu.menuBarAdministracion}" outcome="#{bundle.ruta_url_gestion_usuario}"/>

<p:submenu id="om_balances" label="#{bundle.label_balance}" rendered="#{appMenu.menuBarAdministracion}" icon="pi pi-chart-line">
<p:menuitem id="om_bl_libro_inventario" value="#{bundle.label_balance_libro_inventario}" rendered="#{appMenu.menuBarAdministracion}" icon="pi pi-cog" outcome="#{bundle.ruta_url_libro_inventario}" />
</p:submenu>

......

They appear active to me, because this happens if I have the pro and extended version.
Top

**Comment by melloware** [comment]
You are using a custom Poseidon Theme and this looks like a custom Poseidon issue.  Make sure you have the latest download of Poseidon to match the PF version you are using.

**Comment by tandraschko** [comment]
please use the poseidon forum, this issue tracker is for PF core only
