### ISSUE TITLE
DatePicker: Initial view with maxdate in the past/mindate in the future

### ISSUE THREAD

**Issue by jacekzwroclawia** [primefaces/primefaces#8912]
### Describe the bug

Because calendar widget is deprecated - I want to migrate to datePicker component, however I encoutered problems:

**TC 1.** When maxdate attribute is in the past and value is empty (not selected yet)

`<p:datePicker yearRange="1900:2021" maxdate="31-12-2021" pattern="dd-MM-yyyy" />`

When I open datePicker it shows current month with empty year filter, but I don't want this because our maxdate is in the past:

![image](https://user-images.githubusercontent.com/941706/174780519-430d56cb-1d47-489e-8ae8-6ece0c4c1568.png)

With deprecated `<p:calendar .. />` it works as expected - in that situation it shows last month from maxdate, not current month:

![image](https://user-images.githubusercontent.com/941706/174779923-af3b0fd5-c488-4a34-a237-f5991cf0336d.png)

**TC 2.** When mindate is in the future

W don't use that case in our system, but it doesn't work properly on both p:calendar and p:datePicker.

### Expected behavior

Opened month in datePicker should take into accunt maxdate and mindate attributes values.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

Chrome 102

**Comment by melloware** [comment]
For Issue 1 what happens if you set the `yearRange="1900:2022"` ??? does it work then?

**Comment by melloware** [comment]
Attached is reproducer: 
[pf-8912.zip](https://github.com/primefaces/primefaces/files/8949307/pf-8912.zip)

**Comment by melloware** [comment]
This was originally fixed with https://github.com/primefaces/primefaces/issues/5334 but only for `Time Only` mode so now it does it for all modes respecting the min and max date so it works just like the old Calendar.
