### ISSUE TITLE
Tree: Mojarra looses UITreeNode server side generated

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#8916]
### Describe the bug

After generating a Tree component server side, with its UITreeNode childrens. The tree is well-generated.
But when I update the Tree bounded in @RequestScoped bean, it loses UITreeNode childrens previously created for Tree.

When update Tree, It breaks with exception : 

> GRAVE: javax.faces.FacesException: Unsupported tree node type:type1

This issue is only present in Mojarra implementation.
Tested with MyFaces which keep UITreeNode childrens on update.

### Reproducer

[primefaces-mojarra-tree.zip](https://github.com/primefaces/primefaces/files/8957219/primefaces-mojarra-tree.zip)

With Mojarra, only click on "Update" button to break the Tree and generate error "Unsupported tree node".

If you use MyFaces, click on "Update" will not break the Tree.

### Expected behavior

Mojarra doesn't loose UITreeNode childrens when updating Tree. (Like MyFaces)

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.5 and 12.0.0-SNAPSHOT

### JSF implementation

Mojarra

**Comment by melloware** [comment]
@brivalin i would report this on Mojarra https://github.com/eclipse-ee4j/mojarra/issues and include your reproducer.

I reported a similar issue that doesn't happen on MyFaces and you can see my example ticket here: https://github.com/eclipse-ee4j/mojarra/issues/5117

**Comment by brivalin** [comment]
Ok thank you.

What is the chance to have this Mojarra issue resolved for next Primefaces release ?

**Comment by melloware** [comment]
Well Mojarra is not related to PrimeFaces at all so there timelines have nothing to do with each other...

**Comment by jepsar** [comment]
I upvoted the linked issue. Not sure if that will help though 😁

**Comment by brivalin** [comment]
#eclipse-ee4j/mojarra/issues/5148

**Comment by brivalin** [comment]
This issue already happens using last Mojarra release 4.0.4.
The newly created ticket is available here : [eclipse-ee4j/mojarra/issues/5317](url)

**Comment by melloware** [comment]
Thanks!  I had to open a new one for 4.0.4 as well as they closed all 2.3 tickets which I guess I don't blame them 😄
