### ISSUE TITLE
SelectOneMenu: Include SelectItemGroup in filter

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#8917]
### Description

Currently the filter only searches SelectItems but no SelectItemGroups

### Describe the solution you would like

It would be nice, if you could also filter for SelectItemGroups and it shows all items for that group.

### Additional context

A possible solution could be something like 

https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L1300-L1303

```javascript
if(this.filterMatcher(itemLabel, filterValue)) {
     show.push(item);
}
else if(!item.is('.ui-selectonemenu-item-group-children')) { // TODO configurable? this.cfg.filterIncludesGroup && ...
    hide.push(item);
}
else {
    itemLabel = this.cfg.caseSensitive ? option.parent().attr('label') : option.parent().attr('label').toLowerCase();
    if (this.filterMatcher(itemLabel, filterValue)) {
        show.push(item);
    }
    else {
        hide.push(item);
    }
}
```

This solution is quite simple and not the most performant. And maybe this should be configurable?

**Comment by tandraschko** [comment]
i would not make it configurable, just add it :D

**Comment by melloware** [comment]
I was just writing the same thing @tandraschko !

**Comment by fanste** [comment]
PR #8918
