### ISSUE TITLE
growl: sticky broken?

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces/primefaces#8934]
### Describe the bug

Using the following xhtml in pf 11.0.5:
```xml
            <p:growl id="growl" keepAlive="true" life="1000" severity="info" widgetVar="growl">
                <p:autoUpdate/>
            </p:growl>

            <p:growl id="growlerror" keepAlive="true" life="10000" severity="error" widgetVar="growlerror" sticky="false">
                <p:autoUpdate/>
            </p:growl>
```
info messages nicely disappear after 1 second, error messages don't disappear

### Expected behavior

error messages disappear after 10 seconds

### PrimeFaces edition

Community

### PrimeFaces version

11.0.5

### Theme

saga

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

ff 101.0.1 (64-bit)

**Comment by tandraschko** [comment]
Please provide a reproducer

**Comment by melloware** [comment]
Sticky is `false` by default so i would expect use case 1 and 2 to be identical?

```java
public boolean isSticky() {
        return (Boolean) getStateHelper().eval(PropertyKeys.sticky, false);
    }
```

**Comment by eduarddrenth** [comment]
> Please provide a reproducer

I'll see what I can do

**Comment by eduarddrenth** [comment]
> Sticky is `false` by default so i would expect use case 1 and 2 to be identical?
> 
> ```java
> public boolean isSticky() {
>         return (Boolean) getStateHelper().eval(PropertyKeys.sticky, false);
>     }
> ```

absolutely, but I see it behave differently

**Comment by eduarddrenth** [comment]
unable to reproduce, still see this issue in our production running on payara

**Comment by melloware** [comment]
I wonder if it's a but with 11.0.5

**Comment by eduarddrenth** [comment]
no, tested that

**Comment by eduarddrenth** [comment]
but yes, somewhere, something goes wrong... I suspect perhaps jsf implementation of payara has to do with it, but I don't know where this hooks into primfaces sticky

**Comment by melloware** [comment]
also make sure you don't have any overridden JS you have forgotten about that might be overriding the default JS behavior of Growl?

**Comment by eduarddrenth** [comment]
In my latest build on test env i don't see this anymore, thanks
