### ISSUE TITLE
Keyboard: CSP prevents inline-style 

### ISSUE THREAD

**Issue by mscelectit** [primefaces/primefaces#8939]
### Describe the bug

With enabled CSP we get the following console error:

`jquery.js.xhtml?ln=primefaces&loc=&e=10.0.7:2`

`Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

Is there a chance to prevent this error without relaxing the CSP rules?

### Reproducer

[pfcsp.zip](https://github.com/primefaces/primefaces/files/9021163/pfcsp.zip)

### PrimeFaces edition

Elite

### PrimeFaces version

10.0.13

### Theme

custom

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

chrome

**Comment by tandraschko** [comment]
please provide a reproducer

**Comment by melloware** [comment]
Yes and we have integration tests that run nightly that test with CSP turned on for Chrome and do not get this error.

**Comment by melloware** [comment]
Oh this looks like you are saying its PrimeFaces Extensions related?  what PFE component are you using I know for a fact that CSP does not work with CKEditor.  See: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/748

**Comment by mscelectit** [comment]
Sorry for not providing a reproducer yet. It seems to be the "keyboard" component not the "CKeditor".

**Comment by melloware** [comment]
Ahh you mean this component? https://www.primefaces.org/showcase/ui/input/keyboard.xhtml

**Comment by melloware** [comment]
so far I am not able to reproduce it with CSP enabled so yes a reproducer would help.

**Comment by mscelectit** [comment]
Sample/simple maven project to reproduce the problem:
[pfcsp.zip](https://github.com/primefaces/primefaces/files/9021163/pfcsp.zip)

(I use Wildfly as application server)

**Comment by mscelectit** [comment]
...there is no console message if I replace "p:keyboard" with "p:inputText"

**Comment by melloware** [comment]
Can't reproduce:
[pf-8939.zip](https://github.com/primefaces/primefaces/files/9021251/pf-8939.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

Works fine with CSP enabled using PF10.0.0 

**Edit:** I also use Wildfly as a server in production with CSP enabled using PF 10 and PF 11 without issue.

**Comment by mscelectit** [comment]
Ok, my web.xml includes the following context-param:

`<context-param>`
`        <param-name>primefaces.CSP_POLICY</param-name>`
`        <param-value>default-src 'self'; img-src 'self' data:; base-uri 'self'; frame-ancestors 'self'; block-all-mixed-content; script-src 'self'</param-value>`
`</context-param>`

which - when added to your sample code - causes the problem. Is this CSP_POLICY to strict or is this a problem of the keyboard component?

**Comment by melloware** [comment]
Ahhh yes that explains it.  Inline CSS cannot be prevented because so many Jquery components use inline CSS and we can't update all of PF and every jQuery component as this existed long before CSP was even an idea.  The best you can do is this...

```xml
<context-param>
	<param-name>primefaces.CSP_POLICY</param-name>
	<param-value>img-src 'self' data:; base-uri 'self'; frame-ancestors 'self'; block-all-mixed-content; script-src 'strict-dynamic'</param-value>
</context-param>
```
