### ISSUE TITLE
Support for client side script to turn on edit mode for RowEditor

### ISSUE THREAD

**Issue by kannextic** [primefaces/primefaces#894]
Hi,

I'm working on something with DataTable, where I would like to click a table row to enter the edit mode instead of having to click on the pencil icon. 

As far as I know, PrimeFaces currently doesn't support this behavior. I have to use jquery to find the pencil and dispatch a click event, is that right?

**Comment by kukel** [comment]
use the forum for questions like this. @cagataycivici: please close

**Comment by kannextic** [comment]
@kukel I'm sorry, but that wasn't (really) a question. It's still a feature request.

**Comment by arunvc1** [comment]
Something like showRowEditor() would be a nice feature to have

or you can use

 oncomplete="jQuery('.ui-datatable-data tr').last().find('span.ui-icon-pencil').each(function(){jQuery(this).click()});

http://stackoverflow.com/questions/13821750/trigger-activate-the-roweditor-from-bean-for-a-primefaces-in-cell-editing-enable

**Comment by melloware** [comment]
You can do this with showRowEditors(row); method.
```javascript
var row = $('.ui-datatable-data tr').first();
PF('myDatatableWidget').showRowEditors(row);
```
