### ISSUE TITLE
FileUpload: allow absolute path in native mode

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#8941]
Because the [javadoc of Part.write method in Servlet 4.0 spec](https://javadoc.io/static/javax.servlet/javax.servlet-api/4.0.0/javax/servlet/http/Part.html#write-java.lang.String-) says:

fileName - The location into which the uploaded part should be stored. The value may be a file name or a path. The actual location of the file in the filesystem is relative to MultipartConfigElement.getLocation(). Absolute paths are used as provided and are relative to getLocation(). Note: that this is a system dependent string and URI notation may not be acceptable on all systems. For portability, this string should be generated with the File or Path APIs.

So Part.write should support a path or an absolute path. Wildfly jakartaee 8 implementation supports what the specs says.

**Comment by melloware** [comment]
Original ticket: #4752

**Comment by jasonex7** [comment]
I also want to add support for directory paths not only a file paths. This would be great when using `UploadedFiles.write` (check the 's') method because Part.write only support file paths.

**Comment by melloware** [comment]
Sure I would submit a different PR for that.
