### ISSUE TITLE
Lifecycle: Different performance between JSF and PF commands

### ISSUE THREAD

**Issue by AngeloRubens** [primefaces/primefaces#8951]
### Describe the bug

When in https://www.primefaces.org/showcase/ui/misc/lifecycle.xhtml, execute Dummy Ajax request(p:commandButton) the execution time is every more expensive, in some case the exec time is over 50ms differ to Dummy Ajax request(h:commandButton) is every under 20ms. Can you verify this?

### Reproducer

https://www.primefaces.org/showcase/ui/misc/lifecycle.xhtml

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

**Comment by melloware** [comment]
If you change the code so they both process `@form` you will see much closer results.

```xml
<p:commandButton value="Dummy Ajax Request" update="@none" process="@form" styleClass="mr-2" />
<h:commandButton value="Dummy Ajax Request">
                <f:ajax render="@none" execute="@form" />
</h:commandButton>
```

See this BalusC post: https://stackoverflow.com/a/15548755/502366

Note that the subtle difference with the PrimeFaces equivalent is that PrimeFaces defaults to `@form` in the process/execute, while the `<f:ajax>` one defaults to `@this`, so you might need to explicitly specify `execute="@form"`.


Note: Results also may differ between `Apache MyFaces` and `Mojarra` JSF implementations.

**Comment by AngeloRubens** [comment]
Ok thanks. But can you change a showcase page https://www.primefaces.org/showcase/ui/misc/lifecycle.xhtml for obtain the same execution time result with p:commandbutton and h:commandButton?

like this
```
<p:commandButton value="Dummy Ajax Request" update="@none" process="@form" styleClass="mr-2" />
<h:commandButton value="Dummy Ajax Request">
                <f:ajax render="@none" execute="@form" />
</h:commandButton>
```
or like this:
```
<p:commandButton value="Dummy Ajax Request" update="@none" process="@this" styleClass="mr-2" />
<h:commandButton value="Dummy Ajax Request">
                <f:ajax render="@none" execute="@this" />
</h:commandButton>
```

**Comment by melloware** [comment]
I just submitted a PR to update the showcase demo to both use `@form`.   Also of note the Showcase on the web uses Mojarra when I run locally I run with MyFaces.  However I just ran with Mojarra 2.3.18 and got similar results.  the JSF native is only a few MS faster than the PF one.

**Comment by melloware** [comment]
My local results with both using @form.  I pressed it 3 times each

**PF CommandButton:**
![image](https://user-images.githubusercontent.com/4399574/177157901-55387a88-f807-425d-ac9a-ecc78ed5346d.png)
![image](https://user-images.githubusercontent.com/4399574/177157965-a1699926-be6e-4bfb-93a0-63c60484b7fd.png)
![image](https://user-images.githubusercontent.com/4399574/177158020-f71f661b-4164-4f8d-99b0-b033f0b27528.png)

**JSF Button:**
![image](https://user-images.githubusercontent.com/4399574/177158131-bbb111b1-8525-47f5-8da1-86285da37048.png)
![image](https://user-images.githubusercontent.com/4399574/177158192-7c3f10a1-2c0f-4976-b49d-052ecb48cbdd.png)
![image](https://user-images.githubusercontent.com/4399574/177158242-f501a2d7-c0ec-4f09-a88b-19c040b8a388.png)

**Comment by melloware** [comment]
The latest has been deployed so you can see the closer results now.

https://www.primefaces.org/showcase/ui/misc/lifecycle.xhtml
