### ISSUE TITLE
DataTable: responsive rows attribute

### ISSUE THREAD

**Issue by haraleib** [primefaces/primefaces#8955]
### Description

Currently it is very hard to determine a good amount of rows with the `rows` attribute that the dataTable should displays for different screen resolutions.

### Describe the solution you would like

To provide very good UX it would be nice if there is an additional possible input for `p:dataTable` `rows` attribute with something like `dynamic` or `responsive` so that the dataTable displays as many rows as possible, (maybe) for the enclosing container. This would be a very cool solution for different screen resolutions.

**Comment by melloware** [comment]
This could be difficult because rows is determined server side and renders that many rows to the browser.....where screen resolution is a client side determination after the rows have already been sent to the client.

**Comment by tandraschko** [comment]
yup

**Comment by melloware** [comment]
Going to mark this WontFix for now as this would be an extremely difficult/impossible to implement.   The only workaround you have now is to detect the browser resolution with JavaScript and dynamically change the `rows` .  However this will force an AJAX call for it to hit the server and re-render the rows.
