### ISSUE TITLE
TreeTable: NullPointerException #visitTree with NULL value

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#8956]
### Describe the bug

I have dynamically added components in my view. Once the view is restored and the dynamic actions are reapplied, a "static" `p:treeTable`, also contained in the view, throws a `NullPointerException` during `UITree#visitTree` due to a value of `null`.

![image](https://user-images.githubusercontent.com/3531183/177428848-59596818-2293-4e78-a0a2-e40693de1c28.png)

`visitNodes`: `root.get()` -> `getValue()` -> `null` from EL -> `shouldVisitNode`: `(node.isExpanded() || node.getParent() == null)` -> no NULL check for `node`

The set of hints is empty and so even `rendered` expression won't solve the problem.

### Reproducer

Currently not available. I will provide one if really required.

### Expected behavior

No `NullPointerException`

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.2.19

### Browser(s)

ALL

**Comment by fanste** [comment]
Two possible solutions, the first one was tested locally, the second one is pure theory.

1. https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/api/UITree.java#L970 
    ```java
    if (root != null && root.get() != null) {
    ```
2. https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/api/UITree.java#L1094
    ```java
    return (node != null && (node.isExpanded() || node.getParent() == null));
    ```

**Comment by tandraschko** [comment]
does it occur in 12.0?

If you check https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/api/UITree.java#L994
the NPE should not occur anymore in master; your 2. solution is already implemented there

**Comment by tandraschko** [comment]
see https://github.com/primefaces/primefaces/issues/8210

**Comment by fanste** [comment]
Sorry for the false-positive.

I tested it with PF12, but I did not recognize, that the update of my checked-out copy failed :/
So i built and tested it with a too old PF12.
