### ISSUE TITLE
Gmap: Attributes 'streetView' and 'navigationControl' not working

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#8957]
### Describe the bug

I am using p:gmap and am trying to use the attributes `streetView` and `navigationControl` but neither of them seem to work.

### Reproducer

[reproducer.zip](https://github.com/primefaces/primefaces/files/9055048/reproducer.zip)

### PrimeFaces version

10.0.0

### Theme

Diamond

**Comment by melloware** [comment]
@jepsar you have been using GMap recently want to investigate this one?

Looks like we have the right parameters: https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions

**Comment by jepsar** [comment]
I can have a look, but my first guess is that these are now paid features which should be enabled in the Google Maps API.

@miedrl can you please check if your API key is allowed to use the features?

**Comment by miedrl** [comment]
@jepsar How can I check if my API key is allowed to use the features? Google Maps Platform API checker showed the following:

![grafik](https://user-images.githubusercontent.com/77431692/177974749-c4b8e540-5367-4599-981b-624bf828452b.png)

**Comment by jepsar** [comment]
See https://developers.google.com/maps/documentation/streetview/overview and https://developers.google.com/maps/documentation/directions/overview

**Comment by miedrl** [comment]
Sorry, but the two links you provided didn't help me.
The street view seems to work but when I set streetView=false, it is still visible and usable. [Your showcase](https://www.primefaces.org/showcase/ui/data/gmap/street.xhtml?jfwid=e775d) is not helpful as I can only see this

![grafik](https://user-images.githubusercontent.com/77431692/178220189-1c787368-af25-4f1a-9531-c722507ef27d.png)

The attribute navigationControl does not work at all and there is no showcase to test it.

**Comment by jepsar** [comment]
> Sorry, but the two links you provided didn't help me.

They contain links to setting up your API key. Please use them to verify if streetview is enabled in your API key. 

> The street view seems to work but when I set streetView=false, it is still visible and usable. [Your showcase](https://www.primefaces.org/showcase/ui/data/gmap/street.xhtml?jfwid=e775d) is not helpful as I can only see this
> 
> The attribute navigationControl does not work at all and there is no showcase to test it.

An API key where this paid service is enabled is required. That's not the case on the showcase. That's why I labeled this issue "documentation". There should be a huge warning on the showcase about the API key IMO.

**Comment by melloware** [comment]
I agree this is a documentation issue.  It sounds like your Google Maps API is not set up propertly as I have verified the configurations are correct for Google Maps.

**Comment by melloware** [comment]
It is sorta documented here about making sure you have your API key? https://primefaces.github.io/primefaces/11_0_0/#/components/gmap?id=getting-started-with-gmap

**Comment by melloware** [comment]
From what I understand `streetView="false"` is just supposed to disable the UI menu option? 

From their docs:

> The initial enabled/disabled state of the Street View Pegman control. This control is part of the default UI, and should be set to false when displaying a map type on which the Street View road overlay should not appear (e.g. a non-Earth map type).

I don't think this disables Street View it just disables the control?

**Comment by jepsar** [comment]
Yeah, but I suspect they check your API key. For the record we don't have a key with these services enabled, so it is hard to check.

**Comment by melloware** [comment]
any update on this or can we close it?

**Comment by jepsar** [comment]
Not from my side. I'll add a warning to the showcase. I've asked for help to test on Discord, but didn't get a response.
