### ISSUE TITLE
Spinner: pressing tab or other special buttons have no effect

### ISSUE THREAD

**Issue by raphisuter** [primefaces/primefaces#8958]
### Describe the bug

When using a spinner component and click inside it, it's impossible to tab to next element or click other special button combinations like ctrl+s or ctrl+p etc. (tested on 10.0.6 and 10.0.13)

### Reproducer

1. create spinner component`<p:spinner id="somId" />`
2. Click inside spinner component
3. Click tab or ctrl+s
4. still focus inside spinner, no error visible

### Expected behavior

It sould be possible to tab out the spinner and also to do all sorts of button combinations, open developer console in browser etc.

### PrimeFaces edition

Elite

### PrimeFaces version

10.0.6 / 10.0.13

### JSF implementation

MyFaces

### JSF version

2.2

**Comment by jepsar** [comment]
Works for me. https://primefaces.org/diamond/input.xhtml

**Comment by melloware** [comment]
Yep I can TAB and SHIFT+TAB on the showcase: https://www.primefaces.org/showcase/ui/input/spinner.xhtml

**Comment by jepsar** [comment]
@raphisuter are you using Safari by any chance? Not everything is focusable by default there.

**Comment by raphisuter** [comment]
@jepsar  I tested it on multiple browsers like latest chrome, latest firefox and edge and in all of them it's not working. To test I created a plain page with only a spinner element in the page and it's still the same. no error in dev console of the browsers as well and present in PF 10.0.6 and also PF 10.0.13.

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>

<html>
<ui:composition template="/template/client_int.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets">

  <ui:define name="contentTitle">
    #{msg.menu_top_account} - #{msg.menu_sub_account}
  </ui:define>

  <ui:define name="content">
      <p:spinner id="spnTravelTime" />
  </ui:define>
</ui:composition>
</html>
```

**Comment by jepsar** [comment]
@raphisuter please provide a reproducer using https://github.com/primefaces/primefaces-test and test with the latest snapshot

**Comment by raphisuter** [comment]
@jepsar I ran the project using `mvn clean jetty:run -Pmyfaces22` . In this configuration I still can't open dev console of chrome (F12) or open print dialog (ctrl+p) while focus is on the spinner or press other combinations or tabbing out. I found a pattern, seems like pressing ctrl+Character is not working whilest ctrl+Number works. My guess goes towards jQuery. I checked and PF 10.0.13 uses jQuery v.3.51 while PF 11 in the primefaces-test uses  jQuery v.3.6.0. jQuery UI is equal since PF 10.0.11. 

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/9062863/primefaces-test.zip)

**Comment by melloware** [comment]
Its because of these lines in `spinner.js`

```js
            if (!isNumber && !(isNegative || isDecimalSeparator || isThousandsSeparator)) {
                e.preventDefault();
                return;
            }
```

Any non numeric is prevented due to these tickets:

Original Issue: https://github.com/primefaces/primefaces/issues/5579

Tabbing was fixed in 11.0.0: https://github.com/primefaces/primefaces/issues/7378

**Comment by melloware** [comment]
see my PR I have fixed it allowing F12 and F1 keypress etc.  CTRL+P is still blocked though.

**Comment by raphisuter** [comment]
@melloware is it possible to add this to 10.0.14?

**Comment by jepsar** [comment]
It's already labeled "Elite". It's up to PrimeTek to select which issues make it to the elite builds. See https://github.com/primefaces/primefaces#community--elite--pro

You can probably monkey patch the spinner widget. See https://stackoverflow.com/questions/36594082/monkeypatching-primefaces-widgets-extend-override

**Comment by melloware** [comment]
Here is a MonkeyPatch you should just add to your application JS file which will override the spinner behavior.

```js
if (PrimeFaces.widget.Spinner) {
    PrimeFaces.widget.Spinner.prototype.bindEvents = function() {
        var $this = this;

        this.jq.children('.ui-spinner-button')
            .on('mouseover.spinner', function() {
                $(this).addClass('ui-state-hover');
            })
            .on('mouseout.spinner', function() {
                $(this).removeClass('ui-state-hover ui-state-active');

                if ($this.timer) {
                    clearInterval($this.timer);
                }
            })
            .on('mouseup.spinner', function() {
                clearInterval($this.timer);
                $(this).removeClass('ui-state-active').addClass('ui-state-hover');
                $this.input.trigger('change');
            })
            .on('mousedown.spinner', function(e) {
                // only act on left click
                if (e.which !== 1) {
                    return;
                }
                var element = $(this),
                    dir = element.hasClass('ui-spinner-up') ? 1 : -1;

                element.removeClass('ui-state-hover').addClass('ui-state-active');

                if ($this.input.is(':not(:focus)')) {
                    $this.input.trigger('focus');
                }

                $this.repeat(null, dir);

                //keep focused
                e.preventDefault();
            });

        this.input.on('keydown.spinner', function(e) {
                var keyCode = $.ui.keyCode;

                switch (e.which) {
                    case keyCode.UP:
                        $this.spin(1);
                        break;

                    case keyCode.DOWN:
                        $this.spin(-1);
                        break;

                    case keyCode.ENTER:
                        $this.updateValue();
                        $this.format();
                        break;

                    default:
                        //do nothing
                        break;
                }

                // #8958 allow TAB, F1, F12 etc
                var isPrintableKey = e.key.length === 1 || e.key === 'Unidentified';
                if (!isPrintableKey) {
                    return;
                }

                /* Github #1964 do not allow minus */
                var isNegative = event.key === '-';
                if ($this.cfg.min >= 0 && isNegative) {
                    e.preventDefault();
                    return;
                }

                /* GitHub #5579 do not allow decimal separator for integers */
                var isDecimalSeparator = event.key === $this.cfg.decimalSeparator;
                if (isDecimalSeparator && $this.cfg.precision === 0) {
                    e.preventDefault();
                    return;
                }

                /* GitHub #5579 prevent non numeric characters and duplicate separators */
                var value = $(this).val();
                var isNumber = isFinite(event.key);
                var isThousandsSeparator = event.key === $this.cfg.thousandSeparator;
                if ((isNegative && value.indexOf('-') != -1) ||
                    (isDecimalSeparator && value.indexOf($this.cfg.decimalSeparator) != -1) ||
                    (isThousandsSeparator && value.indexOf($this.cfg.thousandSeparator) != -1)) {
                    e.preventDefault();
                    return;
                }

                if (!isNumber && !(isNegative || isDecimalSeparator || isThousandsSeparator)) {
                    e.preventDefault();
                    return;
                }
            })
            .on('keyup.spinner', function(e) {
                $this.updateValue();

                var keyCode = $.ui.keyCode;

                /* Github #2636 */
                var checkForIE = (PrimeFaces.env.isIE(11) || PrimeFaces.env.isLtIE(11)) && (e.which === keyCode.ENTER);

                if (e.which === keyCode.UP || e.which === keyCode.DOWN || checkForIE) {
                    $this.input.trigger('change');
                    $this.format();
                }
            })
            .on('blur.spinner', function(e) {
                $this.format();
            })
            .on('mousewheel.spinner', function(event, delta) {
                if ($this.cfg.modifyValueOnWheel && $this.input.is(':focus')) {
                    if (delta > 0)
                        $this.spin(1);
                    else
                        $this.spin(-1);

                    $this.input.trigger('change');

                    return false;
                }
            });
    }
};
```

**Comment by raphisuter** [comment]
Hi @melloware 
Thank you kindly for the MonkeyPatch. There is a typo in line 2 PrimeFaces.widget.Spinner.**prototyoe**.bindEvents 
I tested the MonkeyPatch and it works good. Seems like ctrl+s or ctrl+p are not working with this MoneyPatck. The most important features for us, tabbing out and opening the dev colsone of the browser (F12) are working perfectly.

**Comment by melloware** [comment]
Fixed my patch above.  Yeah ` var isPrintableKey = e.key.length === 1 || e.key === 'Unidentified';` is saying CTRL+P is a printable key.

If you really need that just change this line

```js
if (!isPrintableKey || e.ctrlKey) {
```

**Comment by raphisuter** [comment]
tested it and works, thank you
