### ISSUE TITLE
DataExporter: Styles error on xls, xlsx and xlsxtream when using custom locale

### ISSUE THREAD

**Issue by jasonex7** [primefaces/primefaces#8959]
### Describe the bug

When using a custom locale like 'es_US', the DataExporter component export an Excel file which has errors in styles reported by Microsoft Excel. 

![image](https://user-images.githubusercontent.com/16229253/177599453-883de111-5728-4903-a241-bb79bacba6a5.png)

The problem seems related to currency style setting in DataTableExcelExporter which doesn't escape currency symbols prior to pass to POI library.

https://github.com/primefaces/primefaces/blob/f543dcc85fc0e46becfcd2359db4222b5675ea78/primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java#L451-L453

### Reproducer

[primefaces-test-dataexporter.zip](https://github.com/primefaces/primefaces/files/9056574/primefaces-test-dataexporter.zip)

### Expected behavior

The file generated by DataExporter doesn't have styles errors reported by Microsoft Excel.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

**Comment by melloware** [comment]
Are you providing a PR?

**Comment by melloware** [comment]
I updated the CurrencyValidator unit test...

```java
    @Test
    public void testPatterns() {
        CurrencyValidator validator = CurrencyValidator.getInstance();

        assertEquals(usDollar + "#,##0.00", validator.getPattern(Locale.US), "US");
        assertEquals(ukPound + "#,##0.00", validator.getPattern(Locale.UK), "UK");
        assertEquals("US$#,##0.00", validator.getPattern(new Locale("es", "US")), "Custom");
    }
```

It looks like `US$#,##0.00` is the pattern for es_US so I am wondering if that is not a valid excel pattern?

**Comment by jasonex7** [comment]
> Are you providing a PR?

Yes, I'm providing a PR, please check if that would be OK.

**Comment by melloware** [comment]
That looks OK to me so it looks like POI needs it wrapped in quotes?

**Comment by jasonex7** [comment]
> That looks OK to me so it looks like POI needs it wrapped in quotes?

No, it is a Microsoft Excel requirement (reference: https://support.microsoft.com/en-us/office/review-guidelines-for-customizing-a-number-format-c0a1d1fa-d3f4-4018-96b7-9c9354dd99f5)

![image](https://user-images.githubusercontent.com/16229253/177607726-cce987ac-df8f-4f03-9bd8-afaf09e133bc.png)

**Comment by melloware** [comment]
Thanks!
