### ISSUE TITLE
inputmask add underscores

### ISSUE THREAD

**Issue by gastonschabas** [primefaces/primefaces#896]
Hi everyone. I've migrated from primefaces 4 to 5. I'm using the inputMask tag and experience an issue. When the the cursor is focused in the input, adds underscores to show how many chars I can add. No problem with that. The issue is when I use javascript to hook some events like "onchange". In the backing bean, I've debugged the value, and it has underscores. Thanks in advanced

**Comment by mertsincan** [comment]
Can you please try with 5.3.x or 5.2.x? (Issue; https://github.com/primefaces/primefaces/issues/812)

**Comment by sudheerj** [comment]
I can't replicate the issue on latest versions.Please try with latest versions.If it is still replicated then please provide sample example.

**Comment by tandraschko** [comment]
no feedback/example -> invalid
