### ISSUE TITLE
DataExporter: Permit using custom DecimalFormat in ExcelOptions

### ISSUE THREAD

**Issue by jasonex7** [primefaces/primefaces#8961]
### Description

It would be nice to allow a custom DecimalFormat to be used only in Excel files and not directly related to the locale used in JSF.

### Describe the solution you would like

Add a new property in `ExcelOptions` called `decimalFormat` of type java.text.DecimalFormat which should be used when exporting to Excel files (xls, xlsx, xlsxstream)

**Comment by melloware** [comment]
I think you could inject it right here:

```java
            if (LangUtils.isNumeric(value)) {
                cell.setCellValue(Double.parseDouble(value));
                printed = true;
            }
```

Make it...

```java
            if (LangUtils.isNumeric(value)) {
                cell.setCellValue(Double.parseDouble(value));
                cell.setCellStyle(decimalStyle);
                printed = true;
            }
```

**Comment by jasonex7** [comment]
I was referring to using a custom `java.text.DecimalFormat` to format currency values, but it could be also used to create a new "decimalStyle" of type `CellStyle` for formatting numeric values that was not currency. So that DecimalFormat would be used to format currency and numbers

```java
        ExcelOptions excelOpt = new ExcelOptions();
        // more settings...
        excelOpt.setDecimalFormat(DecimalFormat.getCurrencyInstance(new Locale("es", "US")));
```

**Comment by melloware** [comment]
Yep we have two different types regular numbers and currency are treated differently.

**Comment by wbss1** [comment]
Hello, I am using PF 12.0.0-RC3 with this locale 
```
<locale-config>
    <default-locale>it</default-locale>
</locale-config>
```
on file faces-config.xml and a dataExporter 
```
<p:commandLink ajax="false">
    <p:graphicImage value="/images/excel.png" />
    <p:dataExporter type="xlsxstream" target="tbl" fileName="Uscite"/>  
</p:commandLink>
```
on a table with BigDecimal field
```
<h:outputText value = "#{item.daPagare}">
    <f:convertNumber currencySymbol = "€" type = "currency" />
</h:outputText>
```
but the dataExporter creates an excel file with the fields formatted as text with € and not as a currency. There is a way to make this work without setting a custom function every time that does
```
excelOpt.setNumberFormat (new DecimalFormat ("#,##0.00"));
excelOpt.setCurrencyFormat ((DecimalFormat) DecimalFormat.getCurrencyInstance (new Locale ("it", "IT")));
```
Here there is a PF test [primefaces-test.zip](https://github.com/primefaces/primefaces/files/9424214/primefaces-test.zip)

**Comment by melloware** [comment]
@jasonex7 can you look at his example its just formatting the currency in plain text in Excel instead of as a currency cell.

**Comment by jasonex7** [comment]
Hi @wbss1. Setting a custom currency symbol per cell basis is not supported and is out of scope of this issue. Currently, DataExporter currency detection feature only considers the property "CurrencyFormat" in ExcelOptions or, if it's not defined, `<locale-config>` in faces-config.xml. 

I think that you're setting "currencySymbol" property property because you're using "it" locale without the country part and "it" locale doesn't establish a specific currency symbol. I recommend to use a locale with country part, e.g. "it_IT", "it_US" or similar.

**Comment by wbss1** [comment]
Hi @jasonex7. Setting
```
<locale-config>
    <default-locale>it_IT</default-locale>
</locale-config>
```
fix my problem.

Thank you for your answer.
