### ISSUE TITLE
Dialog: Copying Text with ctrl+c doesn't work

### ISSUE THREAD

**Issue by DaniEll-AT** [primefaces/primefaces#8965]
### Describe the bug

Copying text out of a modal Dialog doesn't work, when there is an element with tabindex in the DOM-Hierarchy.
Due to _PrimeFaces.utils.preventTabbing_ the Event gets cancelled.

Example:
```
[...]
<div tabindex="1">
<pf:dialog modal="true">
[...]
</pf:dialog>
</div>
[...]
```

### Reproducer

- Open PrimeFaces Showcase [https://www.primefaces.org/showcase/ui/overlay/dialog.xhtml](https://www.primefaces.org/showcase/ui/overlay/dialog.xhtml)
- add `tabindex="7"` to `<div class="content-section implementation">`
- open Modal Dialog with "show"
- try to copy text from the dialog with ctrl+c

### Expected behavior

Copying Text should work.

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.5

### Theme

none

### JSF implementation

MyFaces

### JSF version

2.2

**Comment by melloware** [comment]
Thanks for the report will be fixed in the upcoming 12.0.0

**Comment by DaniEll-AT** [comment]
Could you please release this in v11 elite too?

**Comment by melloware** [comment]
I tagged it `elite` but its up to @mertsincan to decide what goes in V11.
