### ISSUE TITLE
When DataTable is updated via ajax event, the value of the selectAll checkbox changes

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#8974]
Reported By PRO User;
> When all items within the table are selected but some are removed afterwards, those that were removed are not acknowledged.
listForm:tableList_selection: "@all" -> not affected by unchecking
Updating the table on rowUnselectCheckbox event changes "@all" into a list of row ids that are checked which is ultimately a wanted behaviour, but updating the table is not a viable solution.

**Comment by melloware** [comment]
I am investigating the failing Integration tests which were testing this ticket: https://github.com/primefaces/primefaces/issues/6730

**Comment by melloware** [comment]
OK I updated the tests to reflect this new change I believe the previous test was actually proving the BUG you just fixed.

**Comment by mertsincan** [comment]
Thanks a lot, @melloware! I noticed that there was a mistake in the test. I was going to ask you about it :)

**Comment by mertsincan** [comment]
With this fix, users can create a structure like;
```
//ManagedBean.java
...
     public void onToggleSelect(ToggleSelectEvent e) {
        if (e.isSelected()) {
            this.selectedData = this.data; /* All data */
        }
        else {
            this.selectedData = new ArrayList<>();
        }
    }
...

//xhtml
<h:form prependId="false">
    <p:dataTable id="testData" var="obj" value="#{ManagedBean.data}"  selection="#{ManagedBean.selectedData}" rowKey="#{obj}" scrollRows="10" scrollable="true" scrollHeight="250"
              liveScroll="true" selectionPageOnly="false">

        <p:ajax event="toggleSelect" listener="#{ManagedBean.onToggleSelect}" update="testData" />
        <p:ajax event="rowSelectCheckbox" />
        <p:ajax event="rowUnselectCheckbox" />

        <p:column selectionMode="multiple"/>

        <p:column headerText="Code">
            <h:outputText value="#{obj}"/>
        </p:column>
    </p:dataTable>
</h:form>
```
