### ISSUE TITLE
Datatable: FilterEvent misses the filterBy value

### ISSUE THREAD

**Issue by rabiter** [primefaces/primefaces#8976]
### Describe the bug

The FilterEvent event misses the filterBy value (FilterEvent.getFilterBy() is empty). This only happens when the filter is shown via ajax request (refreshing the whole page fixes the issue). Please find the example in attached reproducer (it has comments on a page)

### Reproducer

[pftest.zip](https://github.com/primefaces/primefaces/files/9072840/pftest.zip)

1. Click the FILTER button (the datatable filter will appear)
2. Enter some filter value and press ENTER

The alert message will show FilterEvent.getFilterBy().size() = 0
meaning that the FilterEvent is empty

This is only reproducible on mojarra 2.3 (but worked fine with primefaces 8.0.0 with mojarra 2.3). So basically I found this issue when was migrating from PF 8.0.0 to PF 11.0.0

### Expected behavior

Expected the FilterEvent.getFilterBy() is not empty

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

not relevant

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

not relevant

**Comment by melloware** [comment]
Confirmed its a Mojarra 2.3 issue only...

`mvn clean jetty:run-exploded -Pmojarra22` **(passes)**

`mvn clean jetty:run-exploded -Pmojarra23` **(FAILS)**

`mvn clean jetty:run-exploded --Pmyfaces22` **(passes)**

`mvn clean jetty:run-exploded --Pmyfaces23`  **(passes)**

I bumped your pom.xml to use all the latest Mojarra and MyFaces versions as well and its still an issue on Mojarra 2.3.18.
[pf-8976.zip](https://github.com/primefaces/primefaces/files/9073127/pf-8976.zip)

**Comment by melloware** [comment]
Ahh I just tried it with 12.0.0-SNAPSHOT with `mvn clean jetty:run -Pmojarra23` and its working.  So it looks like it is already fixed.

**Comment by rabiter** [comment]
oookay, thank you! :-)

**Comment by rabiter** [comment]
@melloware is there a chance that the fix will be backported to primefaces 11?

**Comment by jepsar** [comment]
Please read https://github.com/primefaces/primefaces#community--elite--pro

**Comment by melloware** [comment]
@rabiter also I am not quite sure which of the 300 bugs fixed between 11 and 12 actually fixed this issue.

**Comment by rabiter** [comment]
Looks like the issue is fixed in PrimeFaces 11.0.6

**Comment by melloware** [comment]
Must have been this issue then: https://github.com/primefaces/primefaces/issues/8159
