### ISSUE TITLE
DataExporter: Numbers greater than 1000 are formatted as currency in excel exporter with numberConverter

### ISSUE THREAD

**Issue by jasonex7** [primefaces/primefaces#8977]
### Describe the bug

When using `<f:numberConverter>` with type "number" and exporting with any excel format, the numbers are exported as currency when they are numbers.

![image](https://user-images.githubusercontent.com/16229253/178027169-c8c1ef87-fac9-4498-a106-62792b66555a.png)

### Reproducer

```xhtml
<p:dataTable id="table" var="r" value="#{testView.records}">
    <p:column headerText="Text Value">
        <h:outputText value="#{r.textValue}" />
    </p:column>
    <p:column headerText="Int Value">
        <h:outputText value="#{r.intValue}">
            <f:convertNumber type="number" />
        </h:outputText>
    </p:column>
    <p:column headerText="Long Value">
        <h:outputText value="#{r.longValue}">
            <f:convertNumber type="number" />
        </h:outputText>
    </p:column>
    <p:column headerText="Double Value">
        <h:outputText value="#{r.doubleValue}">
            <f:convertNumber type="number" />
        </h:outputText>
    </p:column>
    <p:column headerText="Currency Value">
        <h:outputText value="#{r.currencyValue}">
            <f:convertNumber type="currency" />
        </h:outputText>
    </p:column>
    <f:facet name="footer">
        <h:commandLink immediate="true">
            <h:outputText value="xls" />
            <p:dataExporter type="xls" target="@parent:@parent" fileName="test" />
        </h:commandLink>,
        <h:commandLink immediate="true">
            <h:outputText value="xlsx" />
            <p:dataExporter type="xlsx" target="@parent:@parent" fileName="test" />
        </h:commandLink>,
        <h:commandLink immediate="true">
            <h:outputText value="xlsxstream" />
            <p:dataExporter type="xlsxstream" target="@parent:@parent" fileName="test" />
        </h:commandLink>
    </f:facet>
</p:dataTable>
```

### Expected behavior

It should be formatted as numbers in excel at least or could be formatted with provided DecimalFormat of ExcelOptions if was set.

![image](https://user-images.githubusercontent.com/16229253/178027568-e301aac5-1e00-43a6-851d-e1dbcbcc1c03.png)

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0, 12.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

**Comment by melloware** [comment]
Yep this is what I was saying `currency` is different than regulars numbers.  Previously i have a section that is just `Double.ParseDouble` to print the values of non-currency numbers.

**Comment by jasonex7** [comment]
@melloware do you think I could create a BigDecimalValidator class from apache commons validator? Similar to what you did with CurrencyValidator

**Comment by melloware** [comment]
yep!
