### ISSUE TITLE
Column: FilterValue Mutator Not Called

### ISSUE THREAD

**Issue by hink084** [primefaces/primefaces#8992]
### Describe the bug

The defined Column filterValue within a DataTable does not store the value within the backing bean when processed - the mutator method is not called.  This behavior changed when migrating from PrimeFaces v8 to PrimeFaces v10. As of 7/12/2022 this issue is still present within the PrimeFaces 12.0-SNAPSHOT.

There is a workaround which is to manually define the filter utilizing the filter facet.  You can also bind the DataTable and access the filterValues via the DataTable API but that method is not shown here.

```
<h:form id="frmTest">
    <h2>1) Filter the Animal and Sound columns: {dog, woof}</h2>
    <p:dataTable id="dt_test" value="#{testView.items}" var="item" widgetVar="wgt_test">
        <!-- Broken FilterValue -->
        <p:column filterBy="#{item.animal}"
                  filterValue="#{testView.animalFilter}"
                  headerText="Animal"
                  id="col_animal">
            #{item.animal}
        </p:column>

        <!-- Workaround Filter -->
        <p:column filterBy="#{item.sound}"
                  headerText="Sound"
                  id="col_sound">

            <f:facet name="filter">
                <p:inputText value="#{testView.soundFilter}" onkeyup="PF('wgt_test').filter();"/>
            </f:facet>

            #{item.sound}
        </p:column>
   </p:dataTable>
   <br/><br/>

   <h2>2) Click the Button</h2>
   <p:commandButton id="btn_show"
                    partialSubmit="true"
                    process="@this, dt_test"
                    update="animalFilter, soundFilter"
                    value="Show Filter Values"/>
    <br/><br/>

    <h2>3) Observe Values</h2>
    Animal Filter Value: <h:outputText id="animalFilter"
                                       value="#{not empty testView.animalFilter ? testView.animalFilter : '- Empty -'}"/>
    <br/>
    Sound Filter Value: <h:outputText id="soundFilter"
                                      value="#{not empty testView.soundFilter ? testView.soundFilter : '- Empty -'}"/>
    <br/><br/>

    <h4>Column filterValue mutator was called in PrimeFaces v8 but not in PrimeFaces v10+</h4>
</h:form>
```

### Reproducer

1. Clean/Build the attached reproducer
2. Filter the DataTable Columns (Observe the console for which mutators are called during filtering)
3. Click the CommandButton (Observe the console for which mutators are called during processing)
4. Observe the Filter Values display on the screen
5. Change the PrimeFaces version to 8.0.0 within the POM to see the previous behavior.

### Attached PrimeFaces-Test Reproducer
[column-filtervalue.zip](https://github.com/primefaces/primefaces/files/9095943/column-filtervalue.zip)

### Expected behavior

I'd expect the filterValue to be accessible/stored in the backing bean.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

bootstrap

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

All

**Comment by melloware** [comment]
I think this might be related to this whole thread? https://github.com/primefaces/primefaces/issues/8159

**Comment by hink084** [comment]
@melloware I don't think so.  I don't believe this has anything to do with dynamic columns or column ordering.  Also the dataTable.getFilterByAsMap() contains FilterMeta objects with the correct filtered values.  

The problem here is that the filter value is not stored in the backing bean property defined within the filterValue attribute of the p:column component.

`filterValue="#{testView.animalFilter}"`

#8976 was somewhat similar but again the filterEvent.getFilterBy() contains FilterMeta objects with the correct filtered values. 

Adding the following to the reproducer:

`<p:ajax event="filter" listener="#{testView.MyFilter}"/>`

```
public void MyFilter(FilterEvent event){
    event.getFilterBy()
         .values()
         .stream()
         .filter(filterMeta -> filterMeta.getFilterValue() != null)
         .forEach(filterMeta -> System.out.println(filterMeta.getColumnKey() + " " + filterMeta.getFilterValue().toString()));
}
```

demonstrates that the Animal Filter Mutator is never called, but the FilterMeta object is correct when typing out d-o-g and w-o-o-f in the filters.

```
frmTest:dt_test:col_animal d
Sound Filter Mutator Called
frmTest:dt_test:col_animal do
Sound Filter Mutator Called
frmTest:dt_test:col_animal dog
Sound Filter Mutator Called
frmTest:dt_test:col_animal dog
frmTest:dt_test:col_sound w
Sound Filter Mutator Called
frmTest:dt_test:col_animal dog
frmTest:dt_test:col_sound wo
Sound Filter Mutator Called
frmTest:dt_test:col_animal dog
frmTest:dt_test:col_sound woo
Sound Filter Mutator Called
frmTest:dt_test:col_animal dog
frmTest:dt_test:col_sound woof
Sound Filter Mutator Called
```


I tested on both MyFaces and Mojarra with the same result.  This issue is also still unresolved in the 12.0.0-SNAPSHOT.

**Comment by melloware** [comment]
excellent research!  Let me see if I see anything obvious.

**Comment by melloware** [comment]
This was removed in 10.0 refatoring of datatable but its necessary just to set this filter value mutator.

https://github.com/primefaces/primefaces/blob/cd4fbdf1d9d4ae054da19b9a84001d0c34d142eb/src/main/java/org/primefaces/component/datatable/DataTable.java#L291-L328

**Comment by melloware** [comment]
OK submitted a fix.

**Comment by hink084** [comment]
Wow, that's a great find!  Thanks for submitting a fix!!

**Comment by melloware** [comment]
i would never have found this without your reproducer so thanks!
