### ISSUE TITLE
TabView: tab not rendered correctly in a particular situation

### ISSUE THREAD

**Issue by Sun8642** [primefaces/primefaces#8994]
### Describe the bug

When using a tabView with the attribute dymanic="true", if we try to display a particular tab which was not loaded (by clicking on it) and an update of the tabView occurs before the tab is fully loaded, the tab is set as active tab but not rendered.

### Reproducer

1. Go to the home page http://localhost:8080/primefaces-test/
2. Click on the second tab before the update from the remoteCommand is done (you have 2 sec to click on it or increase the duration of the Thread.sleep in the TestView.loadData() method to test it)

Reproducer:
[primefaces-test-tab-view.zip](https://github.com/primefaces/primefaces/files/9111496/primefaces-test-tab-view.zip)
 

### Expected behavior

The tab which we clicked on must be rendered

### PrimeFaces edition

Community

### PrimeFaces version

11.0

### Theme

All

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

All

**Comment by melloware** [comment]
Can you try this MonkeyPatch by adding it to `test.js` of your reproducer.

```js
if (PrimeFaces.widget.TabView) {
    PrimeFaces.widget.TabView.prototype.loadDynamicTab = function(newPanel) {
        var $this = this,
            index = newPanel.data('index');
        options = {
            source: this.id,
            process: this.id,
            update: this.id,
            params: [{
                    name: this.id + '_contentLoad',
                    value: true
                },
                {
                    name: this.id + '_newTab',
                    value: newPanel.attr('id')
                },
                {
                    name: this.id + '_tabindex',
                    value: index
                }
            ],
            onsuccess: function(responseXML, status, xhr) {
                PrimeFaces.ajax.Response.handle(responseXML, status, xhr, {
                    widget: $this,
                    handle: function(content) {
                        // hide first
                        // otherwise it will already be displayed after replacing the content with .html()
                        var updatedPanel = $this.panelContainer.children().eq(index);
                        if ($this.cfg.effect) {
                            updatedPanel.hide();
                        }
                        updatedPanel.html(content);

                        if ($this.cfg.cache) {
                            $this.markAsLoaded(updatedPanel);
                        }
                    }
                });

                return true;
            },
            oncomplete: function() {
                var updatedPanel = $this.panelContainer.children().eq(index);
                $this.show(updatedPanel);
            }
        };

        if (this.hasBehavior('tabChange')) {
            this.callBehavior('tabChange', options);
        } else {
            PrimeFaces.ajax.Request.handle(options);
        }
    }
};
```

**Comment by Sun8642** [comment]
It doesn't work, it doesn't change the behavior at all

**Comment by melloware** [comment]
Its working for me:
[pf-8994.zip](https://github.com/primefaces/primefaces/files/9112847/pf-8994.zip)

Can you try mine and make sure you open an incognito window or press CTRL+F5 so it loads the fresh JS correctly.

**Comment by Sun8642** [comment]
My bad, CTRL + F5 did the job, it's working like a charm, thank you !
