### ISSUE TITLE
CSP: Body onload not working

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#9002]
### Describe the bug

Forum Post: https://forum.primefaces.org/viewtopic.php?f=3&t=73590

When using...

```xml
<h:body onload="alert('loaded!')">
```

The script will not execute when using CSP enabled.   This appears due to some jQuery issues: https://stackoverflow.com/a/55282859 with the load events

It generates this CSP script.

```js
PrimeFaces.csp.register('body','onload',function(event){alert('loaded!')});
```

### Reproducer
[pf-9002.zip](https://github.com/primefaces/primefaces/files/9133728/pf-9002.zip)

### Expected behavior

The `onload` method should execute when using CSP.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

**Comment by GedMarc** [comment]
does the csp have script:inline enabled?

**Comment by melloware** [comment]
@GedMarc we rewrite inline scripts from DOM events to `Jquery` events like this...

```js
PrimeFaces.csp.register('body','onload',function(event){alert('loaded!')});
```

So we take an inline script and make it a body script wrappering it with `jquery`.   OTher events work it seems like
