### ISSUE TITLE
SelectOneMenu not working under <p:tabView>

### ISSUE THREAD

**Issue by cidylong** [primefaces/primefaces#9005]
### Describe the bug

Component selectonemenu not work under <p:tabView>, very easy to reproduce it, Just create a <p:tabView> and insert a selectonemenu into. Try it, you will see what happen.

Ajax event and listener not work as well.

### PrimeFaces edition

Community

### PrimeFaces version

10.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

safari and chrome all not works

**Comment by jepsar** [comment]
Works for me with 11. Please try with 12.0.0-RC1 and provide a reproducer.

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by cidylong** [comment]
Thank you for your advice. I update primefaces to 11.0.0. It works fine.

Thank you again.
