### ISSUE TITLE
DataTable expandedRow : no state change after update

### ISSUE THREAD

**Issue by Vicca2707** [primefaces/primefaces#9007]
### Describe the bug

after my upgrade from 10 to 11 my dataTable wont collapse my row after a update. Im using a method to expand/collapse the rows and using expandedrow to know withone i need to collapse and with one should be expanded. At the end is a button to clear my list with is tracking the expanded row and update the table.
After the clearing all rows was collapsed in PF10 but in PF11 the expanded rows just lost the checkboxes and was still expanded. Debuging showed me that my tracking list is empty, so it should be collapsed. I think there is missing a update somewhere inside the datatable.

### Reproducer

1. click on some checkboxes, row will expand
2. click button for clear selection inside bean
3. wait datatable refresh
4. error : rows wont change to collapsed

Reproducer:
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/9141073/primefaces-test-master.zip)

### Expected behavior

After clearing my list inside the bean and update the table, all rows should be collapsed.

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.4

### Theme

Ultima

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

Firefox / Chrome

**Comment by tandraschko** [comment]
please try 12.0.0-RC1, which was released today

**Comment by melloware** [comment]
Your reproducer is not valid for me it didn't run at first and when I got it running I don't see any expandable rows.

**Comment by melloware** [comment]
Going to mark as invalid unless a proper reproducer is provided

**Comment by Vicca2707** [comment]
New reproducer:
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/9161788/primefaces-test-master.zip)

![grafik](https://user-images.githubusercontent.com/2725515/180286256-6abc892d-b8ab-4f91-8e0e-894ee2882045.png)
click on first checkbox : 
![grafik](https://user-images.githubusercontent.com/2725515/180286377-2d3694bc-43b1-4fd8-a24b-c2d121645a3f.png)
click on clear+update button: 
![grafik](https://user-images.githubusercontent.com/2725515/180286522-3ccbd18b-d939-4584-9806-759ef97d7b5a.png)

**Comment by melloware** [comment]
Nope `java.lang.ClassNotFoundException: org.apache.catalina.filters.FailedRequestFilter` ??

**Comment by melloware** [comment]
Are you running `mvn clean jetty:run` and actually testing this first?

**Comment by Vicca2707** [comment]
My bad, there was a change inside web.xml. 
This one is running `mvn clean jetty:run`. my old test was on tomcat 8
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/9162130/primefaces-test-master.zip)

**Comment by melloware** [comment]
OK its because when you click your button its submitting the form and the datatable is sending its `rowExpansionState` to the server for evaluation.

![image](https://user-images.githubusercontent.com/4399574/180302924-ca0f5402-192f-488a-a3e7-d0c3f1c34820.png)

To fix this just change your command button to the following.

```xml
<p:commandButton action="#{testView.clearList()}" update="@form" value="clear" process="@this" onclick="PF('kktable').expansionHolder.val('');"  />
```
