### ISSUE TITLE
Core: version 12.0.0-RC1 cannot download from Maven Central

### ISSUE THREAD

**Issue by LouisCollet** [primefaces/primefaces#9011]
### Describe the bug

I get this error when attemptin to user the latest release :
----------------------------< lc:GolfWfly >-----------------------------
Building GolfWfly 1.0-SNAPSHOT
--------------------------------[ war ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/primefaces/primefaces-parent/12.0.0-RC1/primefaces-parent-12.0.0-RC1.pom
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  1.453 s
Finished at: 2022-07-20T12:15:16+02:00
------------------------------------------------------------------------
Failed to execute goal on project GolfWfly: Could not resolve dependencies for project lc:GolfWfly:war:1.0-SNAPSHOT: Failed to collect dependencies at org.primefaces:primefaces:jar:12.0.0-RC1: Failed to read artifact descriptor for org.primefaces:primefaces:jar:12.0.0-RC1: Could not find artifact org.primefaces:primefaces-parent:pom:12.0.0-RC1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

### PrimeFaces version

12.0.0-RC1

### JSF implementation

Mojarra

### JSF version

2.3

**Comment by melloware** [comment]
Yep we have notified PrimeTek.

**Comment by jepsar** [comment]
https://github.com/primefaces/primefaces/releases/tag/12.0.0-RC2

... might take a while to end up at Maven central

**Comment by LouisCollet** [comment]
Thanks to everybody for the rapid reactions !
