### ISSUE TITLE
DataExporter: thousand separator in view, comma in Excel

### ISSUE THREAD

**Issue by dmainardi** [primefaces/primefaces#9019]
### Describe the bug

Numeric values exported in Excel are divided by 1000.
I think this is because thousand separator is "," in English speaking country and "." in, for example, Italy or France.

![dataExporter](https://user-images.githubusercontent.com/14050486/180472208-17928a1a-318c-47c8-8872-0b102b8b081d.png)

### Reproducer

Go to https://github.com/dmainardi/primefaces-test and follow instructions

### Expected behavior

Same mileage values in view and in Excel sheet.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0 and 12.0.0-RC2

### Theme

Saga

### JSF implementation

All

### JSF version

2.2 and 2.3

### Browser(s)

Firefox

**Comment by melloware** [comment]
OK I updated your reproducer using `12.0.0-RC2`:
[pf-9019.zip](https://github.com/primefaces/primefaces/files/9169309/pf-9019.zip)

I set in `faces-config.xml` to Italy like this.
```xml
        <locale-config>
            <default-locale>it</default-locale>
        </locale-config>
```

My number comes out `7.462` on the UI and in `Excel` ?

![image](https://user-images.githubusercontent.com/4399574/180483294-88bd3cff-e3be-4471-aeea-b4a961ec0455.png)

![image](https://user-images.githubusercontent.com/4399574/180483386-6c6100a4-8756-415b-8d8f-93504b272b68.png)

 cc @jasonex7 

Also check in Excel when you click "Format Cell" on that cell what country does it say?

![image](https://user-images.githubusercontent.com/4399574/180485342-d5d9bd33-5803-47d3-8660-8f3465252bbe.png)

**Comment by jasonex7** [comment]
In order to solve this, I think it should be first validated with the NumberFormat of current Locale. I'm going to create a PR.

**Comment by jasonex7** [comment]
Using the proposed change the Excel file goes like this (I'm opening the Excel file with EC locale of my OS):

![image](https://user-images.githubusercontent.com/16229253/180491943-2e18bba7-ffba-49b2-8920-0fc523238120.png)

The html view using the reproducer with locale "it" is like this:
![image](https://user-images.githubusercontent.com/16229253/180492039-7dc35d05-3d2c-4a52-b2b8-650888b58bab.png)

**Comment by melloware** [comment]
But isn't that still wrong though?   7.162 in italy is not 7,162 in Excel right?  also in your screenshot YEAR is now messed up as 1,997 instead of 1997.

I guess we need @dmainardi to say what he expects Excel to look like in his scenario?

`7.162` in italy is Seven Thousand (7000)
`7,162` in US is Seven Thousand(7000) but in Italy that is just Seven (7)

**Comment by jasonex7** [comment]
> But isn't that still wrong though? 7.162 in italy is not 7,162 in Excel right? 

If the Excel file would be opened with "it" locale, then the thousand separator should be updated accordingly. I attach the excel file: [cars.xls](https://github.com/primefaces/primefaces/files/9169642/cars.xls)


> also in your screenshot YEAR is now messed up as 1,997 instead of 1997.

I think that is a style problem, I update the PR to "detect" if value had thousand separator originally to decide if the number should also have it or not. The excel file [cars.xlsx](https://github.com/primefaces/primefaces/files/9169872/cars.xlsx) now has this aspect with my current "EC" locale.

![image](https://user-images.githubusercontent.com/16229253/180500329-d9dc439d-c048-409e-80fa-ae9baf30637b.png)

**Comment by dmainardi** [comment]
Hello,
I updated the test in order to easily check difference between view and Excel.
In Italy the comma "," is decimal separator while the dot "." is thousand separator. So "1.000" values one thousand and "1,000" values one.
I tried to test with master-SNAPSHOT but I failed, so I will wait for RC3.
Thanks to you all.

**Comment by melloware** [comment]
OK with 12.0.0-RC2 I get this:
![image](https://user-images.githubusercontent.com/4399574/180772142-5c2db0ef-f72b-4385-9671-a4134257289c.png)

With 12.0.0-SNAPSHOT I get this:
![image](https://user-images.githubusercontent.com/4399574/180772218-6694b398-482b-41fe-a750-91885d1be296.png)

The SNAPSHOT I think is doing it correctly because my Excel is US English?

**Comment by dmainardi** [comment]
I think the SNAPSHOT version gives correct values, even if is in US English.

**Comment by melloware** [comment]
OK excellent so this will be in 12.0.0-RC3. or 12.0.0 final if we skip an RC3

**Comment by RalfScania** [comment]
Is this really fixed? I still have this problem with locale de and pf 12.0.2

**Comment by RalfScania** [comment]
> > Is this really fixed? I still have this problem with locale de and pf 12.0.2
> 
> @RalfScania have you tried the numberFormat and currencyFormat? https://primefaces.github.io/primefaces/12_0_0/#/components/dataexporter?id=customization

Yes, I did, even using a postProcessor.
I fixed this by removing the field option from the column (field="margin").
This seems quite strange to me.

```
<p:column
                        exportable="#{userSettings.salesModule[26]}"
                        visible="#{userSettings.salesModule[26]}"
                        styleClass="#{style.global_tableColumnRight}"
                        sortBy="#{data.margin}"
                        field="margin"
                        filterable="false"
                        headerText="#{msg.salesTool_margin}">
                    <f:facet name="header">
                        <h:outputText value="#{msg.salesTool_margin}"/>
                    </f:facet>
                    <h:outputText value="#{data.margin}">
                        <f:convertNumber pattern="#{msg.global_numberPattern}"/>
                    </h:outputText>
</p:column>
```

**Comment by melloware** [comment]
@RalfScania I am not sure I understand what fixed your issue?  Are you saying removing `field="margin"` make everything work?

**Comment by RalfScania** [comment]
> @RalfScania I am not sure I understand what fixed your issue? Are you saying removing `field="margin"` make everything work?

Yes. 
The screen shows, how it looked before the change.

![image](https://user-images.githubusercontent.com/54022311/217040795-16c549de-fc34-436c-9c74-c4985d299eed.png)
