### ISSUE TITLE
ColorPicker: support passthrough attributes

### ISSUE THREAD

**Issue by liefke** [primefaces/primefaces#9032]
**Reproducer:**
[pf-9032.zip](https://github.com/primefaces/primefaces/files/9198813/pf-9032.zip)

**Steps to reproduce**

Use the following JSF snippet:

    <ui:composition ... xmlns:pf="http://primefaces.org/ui" xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
      ...
      <pf:colorPicker value="#{bean.color}" widgetVar="colorPicker1" pt:data-example="value" />
      ...
    </ui:composition>

*Expected / pre 10.0.0 behavior*

The created HTML looks like this:

    <input id="..." name="..." type="hidden" autocomplete="off" data-example="value" value="FF0000">

*Actual behavior*

The created HTML looks like this:

    <input id="..." name="..." type="hidden" autocomplete="off" value="FF0000">

(the pass-through attribute is missing)

*Analysis*

Apparently #5980 changed the call of `renderPassThruAttributes(context, colorPicker, null)` to `renderPassThruAttributes(context, colorPicker)` ([ColorPickerRenderer.java](https://github.com/primefaces/primefaces/commit/f3a4d56aa8a5b30b17c805043f919e0c365c8127#diff-622c2c96c13183a6cd26df7619183a195b4d908afcaf500c114c53235566dbc8L114))

This is is a no op, because in CoreRenderer the implementation looks like this:

        protected final void renderPassThruAttributes(FacesContext context, UIComponent component, List<String>... attrs) throws IOException {
          if (attrs == null) {
              renderDynamicPassThruAttributes(context, component);
              return;
          }

          for (List<String> a : attrs) {
              renderPassThruAttributes(context, component, a);
          }
      }

(attrs is `[]`, an array of zero elements, and not `null`)

I would provide a pull request, but I can only guess the intention of the change, so from my point of view there are two possible fixes. Either change the call of `renderPassThroughAttributes` to `renderDynamicPassThruAttributes` or change the implementation of `renderPassThruAttributes` to `if (attrs == null || attrs.length == 0)`

The same problem applies to the dock in [DockRenderer.java](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/dock/DockRenderer.java#L70) and all callers of [CoreRenderer.renderDummyMarkup](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java#L842), which are the Draggable, Droppable and Poll components.

**Comment by melloware** [comment]
Let me look it might have been "unintentional"

**Comment by melloware** [comment]
I have confirmed your fix is the correct one as right above it in the overloadded it does this...

```java
if (attrs != null && !attrs.isEmpty()) {
```

Thanks for your report I have submitted a PR this will be fixed in 12.0.0-RC3
