### ISSUE TITLE
Dialog Framework: make dialogs more responsive

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#9033]
### Description

Dialog Framework - dialog should be responsive

1. adapt their own size to available screenspace
2. should allow to use PrimeFlex inside the dialog 

https://github.com/primefaces/primefaces/issues/723 only seem´s to be part of the truth.
(e.g. https://forum.primefaces.org/viewtopic.php?t=52907)

### Describe the solution you would like

- [ ] add best-practice-showcase-example
- [ ] document already exisiting option 'styleClass'
- [ ] add option 'iframeStyleClass' (which may be set to max-w-screen provided by PrimeFlex)
- [ ] add DialogFrameworkOptions-class with builder as convenient way to build options-map

```java
Map<String, Object> options = new HashMap();
options.put("modal", true);
options.put("responsive", true);
// options.put("width", "auto");
options.put("contentWidth", "900");
// wichtig um responsive zu sein
options.put("styleClass", "max-w-screen");
```

**Comment by melloware** [comment]
I like this idea!
