### ISSUE TITLE
CommandButton: add opacity to theme transition

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#9036]
Buttons are now disabled by default during Ajax requests. This looks okay on request which take a little while. On fast requests the short disablement makes the button flicker. See for example:

https://www.primefaces.org/showcase/ui/ajax/basic.xhtml

Flickering can be reduced by added something like `opacity .2s` to 
```css
body .ui-button { transition: ... }
```

**Comment by melloware** [comment]
@jepsar can't we just add this to forms.css right in core and not in the theme?

**Comment by mertsincan** [comment]
I think the current behavior can be like in https://www.primefaces.org/primereact/button
Loading -> 'Submit' with default icon or only 'Submit' text

**Comment by mertsincan** [comment]
Or https://www.primefaces.org/showcase/ui/button/commandButton.xhtml?jfwid=49dd7

**Comment by jepsar** [comment]
> @jepsar can't we just add this to forms.css right in core and not in the theme?

I tried yesterday, but it will be overruled by theme CSS. I could use a more specific selector, but that would break other theme transitions.

**Comment by jepsar** [comment]
> I think the current behavior can be like in https://www.primefaces.org/primereact/button Loading -> 'Submit' with default icon or only 'Submit' text

That's what we have currently. This looks great when the request takes over half a second or so. With short requests it will flicker because the opacity is not transitioned. See https://www.primefaces.org/showcase/ui/ajax/basic.xhtml and click the button. Adding opacity to the transition will reduce the flickering a lot.

You will probably see the same flickering with React if you disable the button for .1 or .05 seconds.

**Comment by jepsar** [comment]
> Or https://www.primefaces.org/showcase/ui/button/commandButton.xhtml?jfwid=49dd7

For demo reasons these actions have a second of sleep added to them, so flickering is not visible here.

**Comment by mertsincan** [comment]
@jepsar, Thanks a lot for your update! Fixed now. Could you please check it?

**Comment by jepsar** [comment]
Thanks! Looking much better IMO
