### ISSUE TITLE
Widget refresh logic does not support widgets with the same id during ajax update

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#9037]
### Describe the bug

Widget refresh logic does not support widgets with the same id during ajax update. The new element (refreshed widget) with the same id will be removed from DOM. Should check if the old widget element is already detached from DOM. do not remove element by id.

Similarly, newly created overlay  (e.g., ContextMenu) will be destroyed if it has the same id as old overlay during ajax update.

### PrimeFaces version

11.0.0

**Comment by javaone199** [comment]
local storage can be used to restore widget states if any.  Widget refresh adds complexity. It is simpler to remove everything related to old widgets and create new widgets.

**Comment by tandraschko** [comment]
Please provide a sample and better description.
