### ISSUE TITLE
UICommand: reenabled after disableOnAjax when disabled on server side in request

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#9038]
### Describe the bug

When a command button action willingly sets the disabled state of the button, the visual state of the button is still enabled. After another page update, this is reflected properly.

### Reproducer

Please clone: https://github.com/stolp/primefaces-test/tree/PF-9038

Form:
```xhtml
<h:form id="frmTest">

 <p>It is expected, that the first button disables itself after its action, but it doesn't.</p>
 <p>The second button only refreshes the form to prove that the disabled setting is indeed present.</p>

 <p:commandButton disabled="#{testView.isDisabled()}"
   value="Button Action disables this button" action="#{testView.sleep()}" partialSubmit="true" update="@form" />

 <p:commandButton
   value="Button Action updates the page" action="#{testView.refresh()}" partialSubmit="true" update="@form" />
</h:form>
```

### Expected behavior

The button state should be disabled after the action finishes.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC2

### Theme

any

### JSF implementation

All

### JSF version

2.3

**Comment by jepsar** [comment]
I thought you had an issue even when `disableOnAjax="false"` was set. Disabling `disableOnAjax` should prevent the issue you've described.

**Comment by stolp** [comment]
Indeed it works in the reproducer when I add `disableOnAjax="false"`. In my application it didn't help.

Still, since `disableOnAjax="true"` is now the default setting, it will break working implementations which the reproducer proves.

IMHO, sadly this is a regression and it should either be fixed or the default should be inverted.

**Comment by jepsar** [comment]
We had a long discussion on this default in the original issue. I would like to keep it like it is now (@melloware WDYT?). However, we should add a note in the migration guide. If one does not want to use this feature, it can be disabled globally using https://primefaces.github.io/primefaces/12_0_0/#/core/globalattributes

**Comment by stolp** [comment]
To make that clear, I also would prefer that this is kept as the default. It's a very valuable addition when working correctly.

In any case, I think it is hard to sell to users that the `disabled` attribute is not working correctly in conjunction with `disableOnAjax`.

Is there any technical reason that they cannot coexist?

**Comment by jepsar** [comment]
As a reference, the original PR with discussion: https://github.com/primefaces/primefaces/pull/8302

I will see if we can support server side disabling (not sure if that will work without having to resort to cookies though).

**Comment by tandraschko** [comment]
if i see that example above, it looks like a bug, not like something to discuss
whats the exact problem?

**Comment by jepsar** [comment]
I'll have a look if I can fix the issue where the button becomes disabled at the server side.

The discussion is whether or not to have `disableOnAjax="true"` as the default.

Actually this should be split into two issues...

**Comment by jepsar** [comment]
Opened a new issue to discuss the default value: #9044

**Comment by jepsar** [comment]
Okay, this was an easy fix actually. PR incoming.

**Comment by stolp** [comment]
Thanks for fixing!

**Comment by jepsar** [comment]
Added another PR. This should of course be fixed for all UI commands that support `disableOnAjax`.

**Comment by stolp** [comment]
I think that `org.primefaces.extensions.renderer.CommandButtonSingleClickRenderer` shows the same behavior. Should I open an issue there as well?

**Comment by jepsar** [comment]
No, that's not needed, it is deprecated now.
