### ISSUE TITLE
Draggable: Allow drop in one or more scope

### ISSUE THREAD

**Issue by gasparbarancelli** [primefaces/primefaces#904]
Componente draggable allow drop in one or more scope.
Today is allowed in only one scope.
Ex: 

```
<p:droppable for="panel-x" scope="droppable-a"/>
<p:droppable for="panel-y" scope="droppable-b"/>
<p:draggable helper="clone" scope="droppable-a, droppable-b" for="panel-drag" />
```

**Comment by cagataycivici** [comment]
Is it possible with plan jQuery UI draggable?

**Comment by gasparbarancelli** [comment]
see 
http://respostas.guj.com.br/6408-componente-primefaces-drag-and-drop-com-mais-de-um-scopetarget
http://stackoverflow.com/questions/11066497/jquery-ui-drag-droppable-with-multiple-scopes

**Comment by melloware** [comment]
Mutliple scopes is not natively supported by JQuery UI and would have to be hacked to make work.  Since no upvotes in 5 years not worth trying to hack this feature in.
