### ISSUE TITLE
Schedule: displayEventEnd does not work on 24h event

### ISSUE THREAD

**Issue by matthijsvisser** [primefaces/primefaces#9041]
### Describe the bug

After upgrading to Primefaces 8.0 from Primefaces 7.0 events that have an start and end time of 0:00 (i.e. 26-7-22 00:00 - 27-7-22 00:00) don't have an end time displayed in the week and day view. The "displayEventEnd" parameter doesn't seem to work for those events. 

I don't want to use the "all-day" events or it's timeslot.

### Reproducer

Reproducable on the Primefaces 12.0 -SNAPSHOT showcase:
http://primefaces.org/showcase/ui/data/schedule/configuration.xhtml
timeFormat: HH:mm
displayEventEnd: true

### Expected behavior

I expect a "HH:mm - HH:mm" time format on the event. 

### PrimeFaces edition

Community

### PrimeFaces version

8.0

**Comment by melloware** [comment]
works fine on the showcase:
![image](https://user-images.githubusercontent.com/4399574/181573656-d2424dab-9934-4329-b69e-77ec5d0f4bb1.png)

However if the event leaks into the "next" day FullCalendar won't show it.  So on your end date you might have to make it  `26-7-22 00:00 - 26-7-22 23:59`

**Comment by matthijsvisser** [comment]
With the following events:

 ```
24-7-22 05:00 - 25-7-22 06:00
26-7-22 00:00 - 27-7-22 00:00
```

I would expect the same time format on event 2 (0:00 - 0:00) as on event 1 05:00 - 0:00 and 0:00 - 06:00. In Primefaces 7.0 the time format was the same for each event

![afbeelding](https://user-images.githubusercontent.com/45653450/181601917-e9b98b63-cb23-4417-84cd-4e3b2581efb6.png)

**Comment by melloware** [comment]
I think this might be a FullCalendar bug. From what I can tell all the data is correct.

**Comment by melloware** [comment]
Yep looks like a FullCalendar bug I would report there.  If I do `00:00-23:59` it displays:
![image](https://user-images.githubusercontent.com/4399574/181750050-3cc49112-c488-4e0b-a467-5230bbe8d22d.png)

If I do `00:00-00:00` it does this:
![image](https://user-images.githubusercontent.com/4399574/181750171-ec8e7c70-cf04-48c1-ab76-44c741372e56.png)

In the old Full Calendar did it display it as `00:00-00:00`?  Because that is sort of weird to display something as having no time.

**Comment by melloware** [comment]
Ok looking at the fullcalendar docs, I can see now that they dont consider this a bug but a feature. Even in v6, end dates are exclusive by default and it seems like there is no (official) way to change them to be inclusive: 
![image](https://user-images.githubusercontent.com/32560510/218076824-038148f4-8040-4c7d-9cdc-9e650f0ec524.png)
