### ISSUE TITLE
Showcase doesnt work per default on TomEE because of EHCache version conflict

### ISSUE THREAD

**Issue by dglb** [primefaces/primefaces#9042]
### Describe the bug

using TomEE+ 8.0.12, I deploy PrimeFaces showcase (tag 11.0.0)
almost every components don't work: I get "Page Not Found".
In TomEE log, I see
28-Jul-2022 15:04:00.791 SEVERE [http-nio-8080-exec-29] org.primefaces.application.exceptionhandler.PrimeExceptionHandler.logException org.ehcache.core.spi.service.ServiceFactory: org.ehcache.core.statistics.DefaultStatisticsServiceFactory not a subtype

So I change, in pom.xml, the version of Ehcache and it's working.

According to
https://github.com/ehcache/ehcache3/issues/2951
it's seems that a change between 3.9.0 and latter introduce a "big" changement.

Could you investigate that so that PrimeFaces showcase work with Ehcache 3.9.7 (at least with TomEE, I don't know other EE application server)

thank you

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

MyFaces

### JSF version

2.3; the one with TomEE+ (EE 8)

### Browser(s)

Firefox 103.0

**Comment by tandraschko** [comment]
can you try to build from source and test 12.x?

**Comment by tandraschko** [comment]
i will close this as won't fix
TomEE delivers ehcache 3.8.x, our code uses 3.9.9

it does not make sense to downgrade our dependency
so make sure set scope=provided in your application (or the showcase in this situation) or the same version as in TomEE , to avoid conflicts

also i dont know why TomEE comes with ehcache

**Comment by dglb** [comment]
> can you try to build from source and test 12.x?

done with tag 12.0.0-RC2: same issue

**Comment by rzo1** [comment]
> also i dont know why TomEE comes with ehcache

It should not. We missed to backport the exclusion for org.ehcache while upgrading cxf. It got fixed on master for 9.x (jakarta / ee9.1) but wasn't backported for 8.x (javax / ee8). It is tracked with TOMEE-4021 and will be fixed in the next release (8.0.13).

For now, users can simply remove ehcache from the libs folder of TomEE.
