### ISSUE TITLE
DataTable Paginator: Selected item of rows per page options not marked correctly

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#9043]
### Describe the bug

The dataTable paginator allows displaying a drop-down list with the rowsPerPage options (e.g. show 5 or 10 rows per page). When selecting one of the options, the option should get the attribute _selected="selected"_ as follows

```
<select class="ui-paginator-rpp-options">
	<option value="5">5</option>
	<option value="10" selected="selected">10</option>
	<option value="*">All</option>
</select>
```

**Bug**: The attribute 'selected' is set when rendering the page but when changing the option (e.g. from 10 to 5 rows per page) it does not change. The previously selected option still has the 'selected' attribute while the currently selected option doesn't.

### Reproducer

1. Go to https://www.primefaces.org/showcase/ui/data/datatable/paginator.xhtml?jfwid=886a0
2. Inspect the HTML code of the drop-down list within the dataTable paginator (attribute 'selected' is set on the second option)
![grafik](https://user-images.githubusercontent.com/77431692/181533902-0eba2b41-1197-4d55-b38c-4701c636fa46.png)
3. Select a different option of the drop-down list.
4. Inspect the HTML code again --> the attribute is still on the previously selected option.

### Expected behavior

The 'selected' attribute should be added or removed dynamically when changing the drop-down list's option. This improves the accessibility among other things.

### PrimeFaces version

10.0.0

### Theme

Diamond

**Comment by jepsar** [comment]
Can you please try with 12 RC2?

**Comment by tandraschko** [comment]
@jepsar the linke abov uses 12.0.0-SNAPSHOT

**Comment by melloware** [comment]
Confirmed thanks for the report fixing for RC3
