### ISSUE TITLE
CommandButton: change disableOnAjax default to false?

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#9044]
As a reference, the original PR with discussion: https://github.com/primefaces/primefaces/pull/8302

**Comment by tandraschko** [comment]
As i said: i dont see any reason to NOT make it default

**Comment by melloware** [comment]
Me too I prefer it is the default and it can always be changed with: https://primefaces.github.io/primefaces/11_0_0/#/core/globalattributes?id=global-attributes

**Comment by jepsar** [comment]
I'm also in camp `true`, so -1 on this from me.

**Comment by stolp** [comment]
I am also happy if this is the (working) default.

**Comment by jepsar** [comment]
> I am also happy if this is the (working) default.

I'm confused by "also". You mean if it would be changed to to `false`, right? The others (so far) would like to keep it `true`.

**Comment by stolp** [comment]
I would like to keep it to `true` like all others. Probably should have used 'likewise' instead of 'also' here to make that clear, sorry.
