### ISSUE TITLE
DataTable: empty message and colspan with toggleable columns or visible="false"

### ISSUE THREAD

**Issue by hades646** [primefaces/primefaces#905]
As it was already discussed in #387, the calculation of the appropriate value for the `colspan` attribute of the empty message cell is more difficult than one might think.

In this case, I'm reporting an issue that is happening when using toggleable columns or columns with `visible="false"`.

Since the empty message cell is located on the first column of the table, if you hide the first column with the toggler, you lose the empty table message. Also, the `colspan` attribute of the empty table message cell is not taking into account if columns are visible or not (`visible="false"`). This problem is particularly annoying if the table layout is `fixed`, since the message occupies more columns than the ones in the header, thus leaving a blank space on top of the table. 

In #387, @cagataycivici said that he would change the code so the empty table message would be rendered in a DIV and not in a table cell, but finally this change was not made. Probably using a DIV or fixing the  `org.primefaces.component.datatable.DataTable.getColumnsCountWithSpan()` method so it takes into account the visibility of the columns and modifying the toggler so it does not hide cells from the rows with the `ui-datatable-empty-message` class (but it recalculates the `colspan`) would be suitable solutions.

This could be two different issues (toggler and empty table message's `colspan`), but I think they should be fixed together, since they are closely related.

Thank you very much.

**Comment by melloware** [comment]
This is fixed as of PF 8.0 and can be tested with the attached reproducer: 
[pf-905.zip](https://github.com/primefaces/primefaces/files/4411168/pf-905.zip)
