### ISSUE TITLE
DatePicker: Month navigator fails when maximum date is set to the first day of month

### ISSUE THREAD

**Issue by oliverdiaz8** [primefaces/primefaces#9052]
### Describe the bug
In DatePicker, the navigation button is disabled when trying to access the month of the maximum date, only if the max date is the first day of month.

### Reproducer
- In datepicker, set the max date to the first date of moth (date object or String).
- Open pop-up datepicker and press the previous month button.
- Now press the next month button to reach the max date month.

```
<p:datePicker
    id="dpk" pattern="dd/MM/yyyy" locale="es" value="#{bean.date}" readonlyInput="true" maxdate="01/08/2022">
    <p:ajax event="dateSelect" update="@this @next"/>
</p:datePicker>
```

![datepicker](https://user-images.githubusercontent.com/74875331/182235470-e3968f9a-7000-41be-89e0-58ac1194f12d.gif)

### Environment
- Primefaces v11
- Web browsers test: Chrome, Firefox, Edge

**Comment by melloware** [comment]
Can you try this MonkeyPatch:

```js
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.navBackward = function(event) {
        if (this.options.disabled) {
            event.preventDefault();
            event.stopPropagation();
            return;
        }

        var newViewDate = new Date(this.viewDate.getTime());

        if (this.options.view === 'date') {
            if (newViewDate.getMonth() === 0) {
                newViewDate.setMonth(11, 1);
                newViewDate.setFullYear(newViewDate.getFullYear() - 1);
            } else {
                newViewDate.setMonth(newViewDate.getMonth() - 1, 1);
            }

            // previous (check first day of month at 00:00:00)
            newViewDate.setHours(0);
            newViewDate.setMinutes(0);
            newViewDate.setSeconds(0);

            // #5967 check if month can be navigated to by checking last day in month
            var testDate = new Date(newViewDate.getTime()),
                minDate = this.options.minDate;
            testDate.setMonth(testDate.getMonth() + 1);
            testDate.setHours(-1);
            if (minDate && minDate > testDate) {
                this.setNavigationState(newViewDate);
                event.preventDefault();
                event.stopPropagation();
                return;
            }

            if (this.options.onMonthChange) {
                this.options.onMonthChange.call(this, newViewDate.getMonth() + 1, newViewDate.getFullYear());
            }
        } else if (this.options.view === 'month') {
            var currentYear = newViewDate.getFullYear(),
                newYear = currentYear - 1;

            if (this.options.yearNavigator) {
                var minYear = parseInt(this.options.yearRange.split(':')[0], 10);

                if (newYear < minYear) {
                    newYear = minYear;
                }
            }

            newViewDate.setFullYear(newYear);

            if (this.options.onYearChange) {
                this.options.onYearChange.call(this, newViewDate.getMonth(), newViewDate.getFullYear());
            }
        }

        this.updateViewDate(event, newViewDate);

        event.preventDefault();
        event.stopPropagation();
    }
};
```

**Comment by oliverdiaz8** [comment]
> Can you try this MonkeyPatch:
> 
> ```js
> if (PrimeFaces.widget.DatePicker) {
>     $.prime.datePicker.prototype.navBackward = function(event) {
>         if (this.options.disabled) {
>             event.preventDefault();
>             event.stopPropagation();
>             return;
>         }
> 
>         var newViewDate = new Date(this.viewDate.getTime());
> 
>         if (this.options.view === 'date') {
>             if (newViewDate.getMonth() === 0) {
>                 newViewDate.setMonth(11, 1);
>                 newViewDate.setFullYear(newViewDate.getFullYear() - 1);
>             } else {
>                 newViewDate.setMonth(newViewDate.getMonth() - 1, 1);
>             }
> 
>             // previous (check first day of month at 00:00:00)
>             newViewDate.setHours(0);
>             newViewDate.setMinutes(0);
>             newViewDate.setSeconds(0);
> 
>             // #5967 check if month can be navigated to by checking last day in month
>             var testDate = new Date(newViewDate.getTime()),
>                 minDate = this.options.minDate;
>             testDate.setMonth(testDate.getMonth() + 1);
>             testDate.setHours(-1);
>             if (minDate && minDate > testDate) {
>                 this.setNavigationState(newViewDate);
>                 event.preventDefault();
>                 event.stopPropagation();
>                 return;
>             }
> 
>             if (this.options.onMonthChange) {
>                 this.options.onMonthChange.call(this, newViewDate.getMonth() + 1, newViewDate.getFullYear());
>             }
>         } else if (this.options.view === 'month') {
>             var currentYear = newViewDate.getFullYear(),
>                 newYear = currentYear - 1;
> 
>             if (this.options.yearNavigator) {
>                 var minYear = parseInt(this.options.yearRange.split(':')[0], 10);
> 
>                 if (newYear < minYear) {
>                     newYear = minYear;
>                 }
>             }
> 
>             newViewDate.setFullYear(newYear);
> 
>             if (this.options.onYearChange) {
>                 this.options.onYearChange.call(this, newViewDate.getMonth(), newViewDate.getFullYear());
>             }
>         }
> 
>         this.updateViewDate(event, newViewDate);
> 
>         event.preventDefault();
>         event.stopPropagation();
>     }
> };
> ```

It works like a charm
