### ISSUE TITLE
OutputPanel: deffered uses async=true per default, which leads to bad state in some situations

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9055]
### Describe the bug

In the example here:
https://github.com/primefaces/primefaces/issues/7953
https://github.com/primefaces/primefaces/issues/8838

the outputPanel posts without viewState id, which leads to that all JS script files are reloaded

we could default to async=false to avoid such usages errors

### PrimeFaces version

x

**Comment by firsthour** [comment]
This change now seems to stack up multiple deferred outputPanels one after another.

So if I have two deferments:

```
<p:outputPanel deferred="true">
	#{testView.sleepString}
</p:outputPanel>
<p:outputPanel deferred="true">
	#{testView.sleepString}
</p:outputPanel>
```

and the view:

```
public String getSleepString() throws InterruptedException {
	Thread.sleep(5000);
	return "awake";
}
```

The second outputPanel won't even start its sleep until the first finishes.

**Comment by tandraschko** [comment]
yeah, sure
you need to set async=false if you would like this to work

**Comment by StevenHachel** [comment]
> yeah, sure you need to set async=false if you would like this to work

This means that the outputPanel element will no longer do what it was designed to do, which is to load pages/areas asynchronously. Each page will not be able to be fully displayed until all areas have been fully rendered and once what it the feature I loved PrimeFaces for. It still seems to work under Mojara 2.2. As of Mojarra 2.3 it no longer does. If it does, there are some javascript errors on another page that are not reproducible.
But you all know the tickets from me. :)

Translated with www.DeepL.com/Translator (free version)

Steven
