### ISSUE TITLE
BlockUI: Custom content not displayed

### ISSUE THREAD

**Issue by mlribes** [primefaces/primefaces#9073]
### Describe the bug

When BlockUI is triggered custom content doesn't appear in it.

### Reproducer

Access PrimeFaces Showcase - BlockUI.
Go to "Custom Content" item.
Click in the paginator.

### Expected behavior

Spinner must be shown because of "pi pi-spin pi-spinner" inside blockUI

### PrimeFaces edition

Community

### PrimeFaces version

v12.0.0-SNAPSHOT

**Comment by jepsar** [comment]
BlockUI has been modified recently (like yesterday or so). Did you test with 12.0.0-SNAPSHOT, or just with the showcase?

**Comment by mlribes** [comment]
Only with showcase and previus versions.

**Comment by jepsar** [comment]
Not saying it has been fix, but please test with the most recent version.

**Comment by melloware** [comment]
i will take a look it looks like it is still not working as of today.
