### ISSUE TITLE
CommandButton: on click event added manually in JS doesn't work in PF 12

### ISSUE THREAD

**Issue by jacekzwroclawia** [primefaces/primefaces#9074]
### Describe the bug

I put below two problems in one issue, because I think that they may be connected.

1. In CommandButton on click event added manually in JS doesn't work.
Problem doesn't exist in PF 11. I reproduced it in PF 12.0.0-RC2.

I have code:

```
<script>
jQuery(document).on('click', 'button', function() {
    alert('test');
});
</script>
<h:form>
    <p:commandButton action="back" value="Back" />
</h:form>
```

2. What's more - I **don't have** enabled option `disableOnAjax="true"` nor `inlineAjaxStatus="true"` (added in PF 12 #8301), but when I run below code 

```
<script>
    window.onbeforeunload = function() {
        return "Your data will be lost.";
    };
</script>
<h:form>
    <p:commandButton action="back" value="Back" />
</h:form>
```
My button changes from:

![image](https://user-images.githubusercontent.com/941706/183102801-22c062cc-96b2-4619-9ee2-b4058470ec34.png)

to

![image](https://user-images.githubusercontent.com/941706/183102597-c58dcd37-69af-4170-b12c-350b7b51c6ca.png)

I don't want this spinner/loading to show on my button when I don't add any of the option from #8301.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC2

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

Chrome 103

**Comment by jepsar** [comment]
Ad `disableOnAjax`: this is `true` by default. You can disable it globally by using https://primefaces.github.io/primefaces/12_0_0/#/core/globalattributes 

Ad `inlineAjaxStatus`: there is no such attribute. You can add custom CSS to suppress the loading indicator. See https://www.primefaces.org/showcase/ui/button/commandButton.xhtml for a custom CSS example and the discussion at https://github.com/primefaces/primefaces/pull/8302

**Comment by jacekzwroclawia** [comment]
OK, thank you for response.
When I set `disableOnAjax=false`, event added manualy in JQuery in our projects work correctly. I think it is important in general (not only for our project) so manual added events for buttons work correctly.

**Comment by jepsar** [comment]
I was about to come back on the added listener. That indeed works if you keep the button enabled.

In general it is safer to do:
```xhtml
<p:commandButton action="back" value="Back"
                 onstart="alert('onstart')" oncomplete="alert('oncomplete')"/>
```

**Comment by jacekzwroclawia** [comment]
In our project we have over 150 commandButtons, and couple of different functions in different JS files that are executed on event button click. It is really comfortable to use JS events instead of onstart or oncomplete on every button with the same functions everywhere.

Is there any option to globally set default value of `disableOnAjax="true"` to `false` ?

**Comment by jepsar** [comment]
☝🏻 https://primefaces.github.io/primefaces/12_0_0/#/core/globalattributes

**Comment by tandraschko** [comment]
@jepsar i wonder why the attached listener isnt called anymore? cant we suppor that?

**Comment by jepsar** [comment]
It seems impossible due to the disabled state. Some tests:
```xhtml
<script>
    jQuery(document).on('click', 'button', function () {
        alert('test');
    });
</script>
<p:commandButton action="back" value="Back" disableOnAjax="false" />
<button>Test</button>
<button onclick="this.disabled=true">Test</button>
<button onclick="this.disabled=true;$(this).trigger('click')">Test</button>
<button onclick="$(this).trigger('click');this.disabled=true">Test</button>
```
