### ISSUE TITLE
Locale: Missing translations for the french locale

### ISSUE THREAD

**Issue by Sun8642** [primefaces/primefaces#9078]
### Describe the bug

There are some missing translations for the french locale.

Here is the file with all the translations (I didn't check the aria and the messages part)
[locale-fr.zip](https://github.com/primefaces/primefaces/files/9280251/locale-fr.zip)

### PrimeFaces edition

Community

### PrimeFaces version

11.0

**Comment by tandraschko** [comment]
Thanks!
