### ISSUE TITLE
Float Label: Date Picker

### ISSUE THREAD

**Issue by KCampos-GandG** [primefaces/primefaces#9084]
### Describe the bug

![image](https://user-images.githubusercontent.com/74632368/183677910-14e9b3e2-d35b-4106-935c-2e3228d86666.png)

### Reproducer

Go to http://primefaces.org/showcase/ui/misc/floatLabel.xhtml
Click on DatePicker and select any date
Float label won't stay up

### PrimeFaces version

v12.0.0-SNAPSHOT

**Comment by melloware** [comment]
Confirmed i will look into this.
