### ISSUE TITLE
Incomplete error message from PF/ajax layer

### ISSUE THREAD

**Issue by arnieHouston** [primefaces/primefaces#9085]
### Describe the bug

I'm getting the following errors in the Tomcat console:

Aug 09, 2022 2:30:16 PM org.primefaces.PrimeFaces$Ajax update
WARNING: PrimeFaces.current().ajax().update() called but component cant be resolved! Expression will just be added to the renderIds: {0}

This message is not only not complete, its missing the component name. Should be something like:

PrimeFaces.current().ajax().update() called but component ({0)}) cannot be resolved! Expression will just be added to the renderIds: {1}

Where {0} is the missing component name, and {1} is the final list of renderIds.

Makes it very difficult to find the error.

### Expected behavior

The error message should be complete.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

Custom

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

Chrome and Edge

**Comment by tandraschko** [comment]
we dont have more infos, just see:
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/PrimeFaces.java#L338

**Comment by arnieHouston** [comment]
Bummer, but the {0} shouldn't be showing up. AFAIK, when logging, one uses {}, not {0}, {1}, etc.

**Comment by tandraschko** [comment]
maybe related to your environment? we use this everywhere

**Comment by tandraschko** [comment]
also see: https://stackoverflow.com/questions/15880629/logging-with-multiple-parameters

**Comment by arnieHouston** [comment]
Maybe. What logger are ya'll using? In the WAR we have log4j2 (api,core,slf4j-impl, web, and 1.2-api), and SLF4J (api,impl,ext). Do I need to add one for PF?

**Comment by tandraschko** [comment]
primefaces uses default java utils logging
you may google how to configure JUL to log4j or slf4j or something, in your container

**Comment by arnieHouston** [comment]
Tried multiple things such as the various jars that route from JUL to SLF4J (but I use Log4j), the log4 interceptor, etc. None of them worked. :(
