### ISSUE TITLE
Widget postConstruct lifecycle callback is invoked with non-fully constructed widget instance

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#9092]
### Describe the bug

Client-side widget lifecycle callbacks were added I believe in PF 9, which are super useful for various purposes. I was just using the `postConstruct` callback, when I noticed a minor issue with it: Currently, `postConstruct` [is called during the init method of the BaseWidget](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js#L335-L337). But the init method is called by the individual widget during the `super` call (e.g. [see here for spitButton](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js#L55)). So at this point, the widget was not fully initialized yet, and thus lacks e.g. [various properties that are set only during the `init` method](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js#L57).

This isn't a major issue and can be worked around e.g. by using `setTimeout` or promises, but perhaps the callback could be invoked a bit later after the widget was initialized?

For example, the following code to add a `aria-label` attribute to the more button of the split button (for accessibility) does not work like this (this should probably be fixed on its own right, but that's just one example): 

```xml
<p:splitButton>
  <f:attribute name="widgetPostConstruct" value="this.menuButton.attr("aria-label", "Show all items")" />
</p:splitButton>
```

To make it work, we need to delay:

```xml
<p:splitButton>
  <f:attribute name="widgetPostConstruct" value="Promise.resolve().then(() => this.menuButton.attr("aria-label", "Show all items"))" />
</p:splitButton>
```

### PrimeFaces version

11

**Comment by tandraschko** [comment]
I think PrimeFaces.createWidget in core.js should call postConstruct after init
also postRefresh

would you like to create a PR?

**Comment by blutorange** [comment]
> I think PrimeFaces.createWidget in core.js should call postConstruct after init also postRefresh
> 
> would you like to create a PR?

I wasn't sure where best to call the postConstruct callback, but that sounds like a good idea. Sure, I can make a PR for this

**Comment by melloware** [comment]
@blutorange @tandraschko can you review my PR i think I captured what you both wanted
