### ISSUE TITLE
Confirm Popup: css variable not minified correctly

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#9099]
### Describe the bug

The [confirmpopup.css](https://github.com/primefaces/primefaces/blob/12.0.0-RC2/primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.css) file is using a css variable that is not minified correctly and break the applied style.

Apparently, the plugin **resources-optimizer-maven-plugin** doesn't support css variables used in the calc function.

### Reproducer

The result using 12.0.0-RC2 is:
```css
left: calc(var(- - overlayArrowLeft, 0)+1.25rem);
```

### Expected behavior

The minified css should be:
```css
left:calc(var(--overlayArrowLeft, 0) + 1.25rem);
```

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC2

**Comment by melloware** [comment]
Great catch. I know the issue will fix!
