### ISSUE TITLE
Tree: Drag&Drop between trees does not work if one is not droppable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#91]
With PF Elite 3.5.13 and 3.5.14, Drag & Drop between two p:tree components works fine... Unless one of these has droppable="false" set.

In my scenario, the first tree is the "source" for D&Ds and provides the items which can be dragged to the second one. The first tree has droppable="false", second one has droppable="true".

On dropping an item at the second one, I get this JQuery error message (in browser JavaScript error window):

Error: cannot call methods on droppable prior to initialization; attempted to call method 'destroy'

A workaround is to set droppable="true", and on dropping items to the first component, generate a Faces error message (and update the trees to reflect the previous item state).

You can easily reproduce this with the D&D demo from the showcase; just set one of the two trees to droppable="false".

**Comment by melloware** [comment]
This ticket was fixed for a while as there are separate properties for draggable and droppable. So you can set the source tree to draggable="true" and the dest tree to droppable="true" and it would solve this issue without forcing the first tree to be droppable. Closing the ticket
