### ISSUE TITLE
DatePicker: maskAutoClear="false" not working

### ISSUE THREAD

**Issue by tfassbender** [primefaces/primefaces#9102]
### Describe the bug

When using a <p:calendar> component I use the parameter **mask** to add an input mask to the component. The inputmask itself is working, but the option **maskAutoClear** cannot be turned off (the default value is true).

The feature seems to be working in the **InputMask** component, so I assume the bug is in the **Calendar** component. 
I debugged through the class **CalendarRenderer**. There the parameter seems to be set correctly, so it might be in the javascript code.

### Expected behavior

When configuring a <p:calendar> with **maskAutoClear="false"** the input should not be cleared when leaving the input while it's not completed.

### PrimeFaces edition

Elite

### PrimeFaces version

10.0.7

### JSF implementation

Mojarra

### JSF version

2.2

**Comment by jepsar** [comment]
Calendar is deprecated. Please use DatePicker instead.

**Comment by melloware** [comment]
Reopening this I see the issue and DatePicker will have the same one.
