### ISSUE TITLE
Calendar doesn't support date pattern with ww (week in year) or EE (day in week)

### ISSUE THREAD

**Issue by dasago87** [primefaces/primefaces#911]
When the pattern is set to 'ww' or 'EE' then the jquery datetime picker fails for "wrong time format". This seems to be an jquery javascript issue. the first time when I load the page it is displayed well. After I select a new date with the date picker in calendar the input displays 'ww' instead of the right value. If I have a pattern like 'yyyy' it works fine.

SimpleDateFormat: http://docs.oracle.com/javase/tutorial/i18n/format/simpleDateFormat.html

primefaces:: 5.2.0
mojarra 2.1.23

**Comment by mauritz-lovgren** [comment]
This bug exists with PrimeFaces 6.x as well.

We have worked around this by using a standard p:inputText instead of the p:calendar input in the situations were we need the week to be displayed in the input field like this:

```
<style>
     /* Hide the calendar input, it does not handle pattern="'Week' w, yyyy" very well...
    This hack can be removed once PrimeFaces calendar behaves better... */
    .hiddenCalendarInput input {
        display: none !important;
    }
</style>

<p:inputText value="#{timeEntryEditClient.selectedDate}" size="12" readonly="true">
    <f:convertDateTime pattern="'Week' w, yyyy"/>
</p:inputText>
<p:calendar id="weekSelector" value="#{timeEntryEditClient.selectedDate}"
    showWeek="true" showTodayButton="true" showButtonPanel="true" navigator="true"
    showOn="button" readonlyInput="true"
    styleClass="hiddenCalendarInput">
</p:calendar>

```

primefaces: 6.0.2
mojarra: 2.2.12-jbossorg-2

**Comment by alberto-stage** [comment]
This problem seems to be still present on Primefaces 6.1

**Comment by melloware** [comment]
I don't believe this is a bug with PF it appears that Java supports ww and EE but the Jquery UI Javascript calendar does not...

http://api.jqueryui.com/datepicker/#utility-formatDate

**Comment by melloware** [comment]
Did you include the correct locale? Including the appropriate script from https://code.google.com/p/primefaces/wiki/PrimeFacesLocales like mentioned in the documentation might solve the issue with the "EE" date pattern
