### ISSUE TITLE
Skeleton: borderRadius attribute doesn't work

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#9110]
### Describe the bug

borderRadius attribute is not rendered correctly, the html code looks like:
```css
borderRadius: 16px;
```

The line code:
https://github.com/primefaces/primefaces/blob/12.0.0-RC2/primefaces/src/main/java/org/primefaces/component/skeleton/SkeletonRenderer.java#L54

### Reproducer

In the showcase the examples (Rectangle and Rounded) are similar:

https://www.primefaces.org/showcase/ui/misc/skeleton.xhtml

### Expected behavior

The css style should be:
```css
border-radius: 16px;
```

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC2

**Comment by melloware** [comment]
Good catch!
