### ISSUE TITLE
Editor: Quill not defined

### ISSUE THREAD

**Issue by Yaswanthbabu12** [primefaces/primefaces#9116]
### Describe the bug

ERROR in ./node_modules/primereact/editor/editor.esm.js 72:6-21
Module not found: Error: Can't resolve 'quill' in '/home/yaswanth/eDistrictFrontEnd/node_modules/primereact/editor'

Getting this issue in prime react editor.

### PrimeFaces version

8.3.0

**Comment by melloware** [comment]
This is PrimeFaces JSF please open this ticket in PrimeReact GitHub

**Comment by jepsar** [comment]
Should we make the JSF version a required field to prevent this?

**Comment by tandraschko** [comment]
+ java version

**Comment by melloware** [comment]
Also @Yaswanthbabu12 i think you are missing the Quill dependency in your `package.json`

```json
    "quill": "1.3.7",
```

**Comment by Yaswanthbabu12** [comment]
Yeah, thank you so much. Working now.

**Comment by jepsar** [comment]
Updated the issue template.

**Comment by Yaswanthbabu12** [comment]
const ComponenetTest=()=>{
	const [serviceDetailsArray,setServiceDetailsArray]=useState<any>([])
	const onInstructionChange = (e: any, key: string, index: number) => {
		let details = [...serviceDetailsArray]
		details[index][key] = e.target.value;
		setServiceDetailsArray(details)
	
	  }
return serviceDetailsArray.map((obj: any, ind: any) => {
	return (
	  <div className="mt-2 row" key={ind}>
		<div className="col-2">{obj.language}</div>
		<div className="col-10">
		  <Editor
			value={obj.instruction}
			onTextChange={(e: any) => onInstructionChange(e, 'instruction', ind)}
		  />
		</div>
	  </div>
	);
  })}
  
  

Let us say I have this kind of code in my application. In the loop, there are multiple editors rendered. when I enter a value in one editor all the remaining objects in the corresponding array are removed. In the same code, I replaced the editor with a text area, it is working fine. But why the editor is behaving in that manner?

**Comment by jepsar** [comment]
@Yaswanthbabu12 this is the JSF repo, not the React repo
