### ISSUE TITLE
Bad content height in DialogFramework when maximized: PF 5.3

### ISSUE THREAD

**Issue by Selaron** [primefaces/primefaces#912]
When using the "maximizable" feature implemented through issue #296 to maximize the dialog, the dialog content suddenly shrinks dramatically to e.g. 1/4 of available size, eventually hiding iFrame content.

The behavior depends on browser:
Chrome and Opera instantly shrink the content.
Firefox first maximizes correctly. As the user resizes the (by default) resizable dialog when in maximized state, content suddenly shrinks in Firefox too.

A notable difference in maximized vs. non maximized state which might cause the issue are the css width/height attributes for div.ui-df-content:
maximized: height = width = 'auto'
non maximized: height and width have some numeric pixel values.

One condition for this to happen may be setting options contentHeight/-Width to some percentage value just like "100%".

Environment:
Apache Tomcat 8.0.26
Mojarra 2.2.12
Java 8u60 64bit
Windows 7

**Comment by Selaron** [comment]
Fixed in 6.0.RC3 (Firefox, Chrome, Opera)

**Comment by tandraschko** [comment]
thanks for retesting ;)
