### ISSUE TITLE
OutputLabel: required indicator placement with PrimeFlex can be hidden

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#9129]
### Describe the bug

Due to the PrimeFlex CSS rule `.field.grid>label { display: flex; ... }` labels do not overflow. This can push the required indicator behind the input if the label is too long.

<img width="341" alt="Screenshot 2022-08-23 at 15 47 40" src="https://user-images.githubusercontent.com/7500178/186174956-710ce469-8a06-4f82-b580-d094a1705ee7.png">

### Reproducer

See for example https://primefaces.org/diamond/formlayout.xhtml

Inspect a label of the horizontal example and make it too long + add a required indicator `<span class="ui-outputlabel-rfi">*</span>` within the `label` element.

You will end up with something like
```html
<div class="card ui-fluid">
    <h5>Horizontal</h5>
    <div class="field grid"><label id="j_idt87" class="ui-outputlabel ui-widget col-12 mb-2 md:col-2 mb-md-0" for="name3">Namewichiswaytoolong<span class="ui-outputlabel-rfi">*</span></label>
        <div class="col-12 md:col-10"><input id="name3" name="name3" type="text" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all" role="textbox" aria-readonly="false" aria-disabled="false">
        </div>
    </div>
    ...
</div>
```

### Expected behavior

The required indicator should always be visible.

Possible solution:

Make the label position relative and `.ui-outputlabel-rfi` absolute with right = 0 (might bite RTL).

### PrimeFaces version

11

### Theme

Diamond

### JSF implementation

All

### JSF version

2.3

### Java version

17

### Browser(s)

Chrome latest macOS

**Comment by melloware** [comment]
@jepsar need some help on this one would like to get this fixed.

**Comment by jepsar** [comment]
A solution could be to override
```css
.field.grid>label {
    display: flex;
    align-items: center;
}
```
to
```css
body .field.grid>label {
    display: block;
}
```
which results in

<img width="219" alt="Screenshot 2023-05-24 at 16 42 03" src="https://github.com/primefaces/primefaces/assets/7500178/6c9c0d31-f6ca-43e0-910f-53b61900fafc">

But I don't like the idea to override PrimeFlex styles.

I think I would like to throw in an extra CSS class when the label is required, so you can apply custom styling to the label. While we are at it, we could also wrap the label text in a span as well, which would allow us to do better styling on both the text and the required indicator.
