### ISSUE TITLE
File upload multi file selection not working in IE11 in compatibility mode

### ISSUE THREAD

**Issue by mohanraok** [primefaces/primefaces#913]
I tried implementing multi file upload using primefaces5.2 +JSF2.1.9, but I am unable to select multiple files at once. I tested my code on chrome browser and multi file selection working on chrome, where as same code is not working in IE11 & IE10 as well.

**Comment by mertsincan** [comment]
Can you please try with 5.3 or 5.3.x?

**Comment by cagataycivici** [comment]
Compatibility mode is not supported in PF, always suggested to run in standards mode. Only IE11+ suppprts multi anyway.
