### ISSUE TITLE
Dialog: Focus is not within dialog after opening

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#9131]
### Describe the bug

After opening a p:dialog the focus is not within the dialog but still on the content outside of the dialog. This is especially bad for modal dialogs.

### Reproducer

1. Go to [PrimeFaces Showcase Dialog](https://www.primefaces.org/showcase/ui/overlay/dialog.xhtml?jfwid=fd14f)
2. Click on any of the show buttons.
3. Click the TAB key to see where the focus is.
4. See error --> focus is still on the clicked button instead of within the dialog and jumps to the next button by pressing TAB.

### Expected behavior

After opening a p:dialog the focus should be within the dialog so the dialog can be accessed quicker and to guarantee accessibility. 

### PrimeFaces version

12.0.0

### Theme

Saga

### JSF implementation

All

### JSF version

-

### Java version

-

**Comment by jepsar** [comment]
There is a focus attribute: "Defines which component to apply focus by search expression". Did you try that?

**Comment by tandraschko** [comment]
even if not defined, we should focus the first input in the dialog propably

AFAIR we had such code in dialog.js

**Comment by miedrl** [comment]
@jepsar I've tried using the focus attribute but it does not seem to work. In my opinion, the focus should automatically be set to the first focusable component within the dialog when the dialog opens. This should not be done by setting the focus attribute.

**Comment by melloware** [comment]
We do have code that focuses however it has some very specific requirements.  It has to be an input field and not hidden.  In the showcase example it's just a P paragraph which is not an input component nor is it focusable.

**Comment by melloware** [comment]
From my Forum Post explaining the issue: https://forum.primefaces.org/viewtopic.php?f=3&t=72264&p=200672&hilit=dialog+focus#p200672

That is because the Focus function to focus the first element on the dialog uses this selector...

```js
focus: function(id, context) {
            var selector = ':not(:submit):not(:button):input:visible:enabled[name]';
```

But I found a solution that works by using styleClass="ui-helper-hidden-accessible"....

```xml
<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
				closable="false" resizable="false" showHeader="false" >
	<p:graphicImage value="/resources/images/progress.gif" />
	<p:inputText styleClass="ui-helper-hidden-accessible"/>
</p:dialog>
```

Try that its working for me!
