### ISSUE TITLE
SelectOneRadio: Labels and index are incorrect in custom layout

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#9137]
### Describe the bug

Since PF 12.0.0-RC3 selectOneRadio with custom layout has issues with the labels if the item index is not straight.

Take for instance the showcase example with custom layout and change some <p:radioButton> order, labels will be broken.

This used to work in 11.0.0.

I'm not really sure about what commit broke this, if you can point me in some direction I can try to put up a PR.

### Reproducer
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<h:body>
    <h:form id="frmTest">
        <h5>Custom Layout</h5>
        <p:selectOneRadio id="customRadio" layout="custom">
            <f:selectItem itemLabel="Red" itemValue="Red"/>
            <f:selectItem itemLabel="Green" itemValue="Green"/>
            <f:selectItem itemLabel="Blue" itemValue="Blue"/>
        </p:selectOneRadio>
        <span class="field-radiobutton" role="radio">
            <p:radioButton id="facet2" for="customRadio" itemIndex="1"/>
            <p:outputLabel for="facet2">
                Green
            </p:outputLabel>
        </span>

        <span class="field-radiobutton" role="radio">
            <p:radioButton id="facet1" for="customRadio" itemIndex="0"/>
            <p:outputLabel for="facet1">
                Red
            </p:outputLabel>
        </span>

        <span class="field-radiobutton" role="radio">
            <p:radioButton id="facet3" for="customRadio" itemIndex="2"/>
            <p:outputLabel for="facet3">
                Blue
            </p:outputLabel>
        </span>
    </h:form>

</h:body>
</html>


```
### Expected behavior

Labels should point to the correct radio button

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC-3

### JSF implementation

MyFaces

### JSF version

2.3-NEXT-M6

### Java version

18.0.2

**Comment by melloware** [comment]
Cc @jepsar

**Comment by jepsar** [comment]
Can you please provide more information about what "broken" means in this case? The only thing I can notice is that keyboard navigation is not working, but this should have been fixed between RC2 and RC3 (I think RC2 is still online).

**Comment by jepsar** [comment]
Also, this could not have worked with 11, as the custom facet was introduced in 12. https://github.com/primefaces/primefaces/pull/8194

**Comment by cocorossello** [comment]
Hi, label for attributes are broken.

The facet was just a reproducer in v12. I have cloned the repo and added an example without the facet, you can see the problem in https://github.com/cocorossello/primefaces-test.git

Click on the labels, you can see they don't work. Change version to 11.0.0 and labels work fine.

I'm not sure if it broke in RC2 or RC3, it probably broke in RC2

**Comment by christophs78** [comment]
@cocorossello does not use <f:facet name="custom"> introduced with https://github.com/primefaces/primefaces/pull/8194.
He uses layout="custom".

We generate different HTML-code. (Left PF12, right PF11)
![image](https://user-images.githubusercontent.com/10461942/186659814-3a3a35bc-ebaa-416e-82d9-a4a4943e13d7.png)

**Comment by jepsar** [comment]
@christophs78 Yes, after the edit it is gone... I'll have a look

**Comment by jepsar** [comment]
@cocorossello please have a look at the PR

**Comment by cocorossello** [comment]
Tested, works fine.
Thanks!

**Comment by jepsar** [comment]
Thanks for reporting and testing!
