### ISSUE TITLE
Configuration: primefaces.HIDE_RESOURCE_VERSION and updating PrimeFaces

### ISSUE THREAD

**Issue by jacekzwroclawia** [primefaces/primefaces#9138]
### Description

#8752 -this is a nice feature, because it is bad practice to have that much visible library version for everyone, but it is problematic when you update Primeface and people have cached version of old scripts. 

### Describe the solution you would like

Maybe instead of boolean, there can be configuration that could accept custom String, for example:

```
<context-param>
    <param-name>primefaces.RESOURCE_VERSION</param-name>
    <param-value></param-value>
</context-param>

<context-param>
    <param-name>primefaces.RESOURCE_VERSION</param-name>
    <param-value>49827659</param-value>
</context-param>
```

**Comment by jepsar** [comment]
https://security.stackexchange.com/questions/215205/is-it-really-security-misconfiguration-to-show-a-version-number/215212#215212

**Comment by melloware** [comment]
I totally understand when Pen Testers and security teams bring this stuff up but I am in agreement with @jepsar .  However the change suggested above is a good compromise to keep Security people at bay...

**Comment by tandraschko** [comment]
everyone can simple overwrite the ResourceHandler and append such a UID
i wouldnt add this to PF.

**Comment by tandraschko** [comment]
can anyone update the docu with this information and maybe a example?

**Comment by melloware** [comment]
Yep I will add an example in the docu how to override and set this yourself.  I am changing this ticket to `documentation`.

**Comment by majkers** [comment]
Regarding https://github.com/melloware/primefaces/commit/c6eb081564d0f7667ef366a0d98b8e6a65d2ca91 First of all as far as I can see the property is called 
`HIDE_RESOURCE_VERSION`
and not
`RESOURCE_VERSION`
So one can read here: https://primefaces.github.io/primefaces/12_0_0/#/gettingstarted/configuration
Secondly. You can't overwrite resource handler but simply add your own. So this could lead to weird links like:
`/fa/font-awesome.css.jsf?ln=primefaces&v=xxx&v=7.0.28`
with `HIDE_RESOURCE_VERSION` disabled and `xxx `as your own postfix
And more over. Now, enabling `HIDE_RESOURCE_VERSION` leads to 404 error from fontawesome no being loaded properly

**Comment by tandraschko** [comment]
the config is HIDE_RESOURCE_VERSION with true/false, which doesnt render the PF version anymore

the normal link:
`/fa/font-awesome.css.jsf?ln=primefaces&v=7.0.28`

the link with HIDE_RESOURCE_VERSION:
`/fa/font-awesome.css.jsf?ln=primefaces`

and like mentioned in our docu, you can add a own paramter with a custom resourceHandler

**Comment by majkers** [comment]
So read this and line 56
https://github.com/melloware/primefaces/commit/c6eb081564d0f7667ef366a0d98b8e6a65d2ca91

**Comment by majkers** [comment]
And hide resource version leads to this:

![image](https://user-images.githubusercontent.com/21099773/189315620-005f0094-d649-4ef1-9340-12a9eaec57f6.png)

and later on console to 404 error. 
`.../javax.faces.resource/fa/fontawesome-webfont.woff.jsf?ln=primefaces?v=4.7.0
`
As you cas see font_awesome version is added to libraryName

**Comment by melloware** [comment]
I need to change the doc to HIDE_RESOURCE_VERSION and true.

**Comment by tandraschko** [comment]
why do you watch old commits instead of the current docs?
looks fine: https://primefaces.github.io/primefaces/12_0_0/#/core/misc?id=cache-busting-resource-handler

**Comment by majkers** [comment]
I was simply looking for a error I mentioned above. Docs are really weak. Eg. I am using version 7 and in docs there is no word of HIDE_RESOURCE...
https://primefaces.github.io/primefaces/7_0/#/gettingstarted/configuration
even though it was introdused in 7.0.27 I think

**Comment by tandraschko** [comment]
the docs are in general for the community versions, i dont think primetek updates it for elite releases
Also see: https://github.com/primefaces/primefaces#community--elite--pro

**Comment by majkers** [comment]
Anyway I submitted a bug report https://github.com/primefaces/primefaces/issues/9189 Thanks
