### ISSUE TITLE
TextEditor looses font size when changing other formatting

### ISSUE THREAD

**Issue by zaibatsu92** [primefaces/primefaces#9139]
### Describe the bug

When editing and saving a formatted text it is not correctly saved and the text looses it's size where other formattings are applied.

### Reproducer

Go to a page with a textEditor and type
`example text`
Mark the whole text and set the font size to large.
Then mark the word "text" only and set it to bold (strong).
Save.
The outcome is:
`<p><span class="ql-size-large">example </span><strong>text</strong></p>`
So "example" is still large, but "text" is only bold, but not large.

### Expected behavior

The whole text should have the font size large.

### PrimeFaces edition

Community

### PrimeFaces version

10.0.7

### JSF implementation

Mojarra

### JSF version

2.3.9

### Java version

jdk-8.0.332.9

**Comment by melloware** [comment]
you are on 10.0.7 have you tried it with 11.0.0 or 12.0.0-RC3?

**Comment by zaibatsu92** [comment]
I was a bit confused with the versions. On the website download section ( https://www.primefaces.org/downloads/ ) it seems 10.0.15 is the latest version so I thought I have a recent one. V12 doesn't seem to have that problem.

**Comment by melloware** [comment]
Yep then its fixed in 11.0.0. or 12.0.0-RC3.
