### ISSUE TITLE
Problem with showing lines at chart after zooming a chart

### ISSUE THREAD

**Issue by cogero** [primefaces/primefaces#914]
Hey there, i've found another issue:

Way to reproduce:
1 : hide 1 of x lines at charts (there can be only 1 line)
2 : zoom chart in
3 : try to show line hided before.

Problem : line is not showing. Only zoom out or refreshing page works.

**Comment by cagataycivici** [comment]
Can you replicate with plain jqplot?

**Comment by tandraschko** [comment]
No example, no screenshot, as there are other issues with a similar description -> will close it as invalid.
You can still create a new issue with all requested informations.
