### ISSUE TITLE
PanelMenu: Javascript exception if stateful enabled

### ISSUE THREAD

**Issue by aissous** [primefaces/primefaces#9143]
### Describe the bug

panelMenu with **statful enabled** throws javascript exception : "Uncaught Error: Syntax error, unrecognized expression: #mainMenuForm\:mainMenu__a5fe785f-4a15-4b4e-9443-66b3ac0c42d2|3".

The reason is that the menu items ids contains pipe "|" character.
In menu.panelmenu.js, the pipe character must be escaped : var element = $(PrimeFaces.escapeClientId(this.expandedNodes[i]));

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC3

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

1.8.0_291

### Browser(s)

Chrome

**Comment by melloware** [comment]
Can you explain more I am already seeing that line of code escaped?

https://github.com/primefaces/primefaces/blob/2f75f6512eb4a8d88c24576bf0e1a81ce094e0c0/primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.panelmenu.js#L462

**Comment by aissous** [comment]
In PF 12.0.0 the menu items ids contains a pipe character. Example of Id : **mainMenuForm:mainMenu__a5fe785f-4a15-4b4e-9443-66b3ac0c42d2|3**.
PrimeFaces.escapeClientId returns **#mainMenuForm\:mainMenu__a9034044-665b-4b4f-8055-930d26c8cad6|1** which is not accepted by jquery selector because of "|" character.
Changing this line as below works for me:
`var element = $(PrimeFaces.escapeClientId(this.expandedNodes[i]).replace(/\|/g,"\\|"));` 

PF tag example :
`<p:panelMenu model="#{menuView.model}" id="mainMenu" multiple="false" statefulGlobal="true"/>`

**Comment by melloware** [comment]
Understood. That makes more sense.

**Comment by blatra** [comment]
I'm using the harmony theme (3.0.1) and have exactly the same issue with harmony menu since I updated from Primefaces 11.0.4 to 11.0.6. The issue also appears with Primefaces 11.0.8.
It seems that Primfaces 11 from version 11.0.6 onwards is also affected by this bug.
