### ISSUE TITLE
Calendar: Uncaught TypeError: $this._base_updateDatepicker is not a function

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#9144]
### Describe the bug

Within `2-jquery.ui.pfextensions.js` line 156 `_base_updateDatepicker` gets invoked, but this function does not exist.
```javascript
$this._base_updateDatepicker(inst);
```

### PrimeFaces version

12.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3.14.SP04

### Java version

1.8.0_333

**Comment by melloware** [comment]
Hmm all I did in this ticket https://github.com/primefaces/primefaces/pull/8914 was move the code to the calendar itself.  So its weird you are seeing this error. It also works for me on the Showcase?

**Comment by melloware** [comment]
OK I submitted a PR but I have no idea how this code ever worked.  That line was not even there in the code I moved.

**Comment by fcorneli** [comment]
@melloware for somehow reason I cannot replicate the issue here myself anymore... it's like Monday-fun...

**Comment by melloware** [comment]
ok yeah and my PR failed.  Let me know if you see anything else weird.

**Comment by melloware** [comment]
Got to the bottom of it and fixed it!

**Comment by fcorneli** [comment]
nice... so I didn't see ghosts after all :)

**Comment by fcorneli** [comment]
OK, found the reason why I saw ghosts. If I run a local deploy via:
```
mvn clean install
mvn javadoc:jar deploy -DaltDeploymentRepository=release-repo::default::scp://192.168.100.6/home/maven-releases/maven-releases
```
I get these funny JS errors.
If I run a local deploy via:
```
mvn clean javadoc:jar deploy -DaltDeploymentRepository=release-repo::default::scp://192.168.100.6/home/maven-releases/maven-releases
```
everything is OK.

Hence you always need do run a `clean` build I guess...
