### ISSUE TITLE
SelectOneMenu: SelectItemGroup combination defect

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#9146]
### Describe the bug

The SelectOneMenu does not properly render the checked/unchecked items. The items are only rendered correctly if I use either just the SelectItems (without grouping) or a list of objects.

Everything worked perfectly under PF 8, so I now have to adjust everything so that the clerks can work properly with it again.

[pfe-select_item_issue.zip](https://github.com/primefaces/primefaces/files/9443113/pfe-select_item_issue.zip)

### PrimeFaces edition

Community

### PrimeFaces version

11

### JSF implementation

Mojarra

### JSF version

2.2,x 2.3.x

### Java version

8

### Browser(s)

FF and Google Chrome

**Defect**:
![grafik](https://user-images.githubusercontent.com/29144366/187163020-eea13594-cb05-4db9-b246-b1fec0cb34f9.png)

**Correct**:
![grafik](https://user-images.githubusercontent.com/29144366/187163178-b724d663-afb5-437e-9517-17ec2332567a.png)
![grafik](https://user-images.githubusercontent.com/29144366/187163260-cafbff0c-60eb-42ee-a165-bf714c0f8f9e.png)

**Comment by tandraschko** [comment]
When rendering lazy the selectItems when opening the panel on client side, the server side renders it correclty without disabled/state-disabled and afterwards the JS loops all opt/groups.
Even then initially its not disabled here: https://github.com/primefaces/primefaces/blob/0f7479695550e779645f3afd0192bc1c39d0b730/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L1566

some other code somehows renders ui-state-disabled

@melloware do you have some time to check it?

**Comment by melloware** [comment]
I will take a look

**Comment by melloware** [comment]
@StevenHachel can you try this MonkeyPatch?  I have updated your example to use the MonkeyPatch and it seems to work.

[pf-9146-patched.zip](https://github.com/primefaces/primefaces/files/9452553/pf-9146-patched.zip)


```js
if (PrimeFaces.widget.SelectOneMenu) {
    PrimeFaces.widget.SelectOneMenu.prototype.initContents = function() {
        this.itemsContainer = this.itemsWrapper.children('.ui-selectonemenu-items');
        this.items = this.itemsContainer.find('.ui-selectonemenu-item');
        this.optGroupsSize = this.itemsContainer.children('li.ui-selectonemenu-item-group').length;

        var $this = this,
            selectedOption = this.options.filter(':selected'),
            highlightedItem = this.items.eq(this.options.index(selectedOption));

        //disable options
        $this.items.filter('[disabled]').addClass('ui-state-disabled');

        //activate selected
        if (this.cfg.editable) {
            var customInputVal = this.label.val();

            //predefined input
            if (customInputVal === selectedOption.text()) {
                this.highlightItem(highlightedItem);
            }
            //custom input
            else {
                this.items.eq(0).addClass('ui-state-highlight');
                this.customInput = true;
                this.customInputVal = customInputVal;
            }
        } else {
            this.highlightItem(highlightedItem);
        }

        if (this.cfg.syncTooltip) {
            this.syncTitle(selectedOption);
        }

        // ARIA
        for (var i = 0; i < this.items.length; i++) {
            this.items.eq(i).attr('id', this.id + '_' + i);
        }

        var highlightedItemId = highlightedItem.attr('id'),
            itemsContainerId = this.itemsContainer.attr('id');
        this.jq.attr('aria-owns', itemsContainerId);
        this.focusInput.attr('aria-autocomplete', 'list')
            .attr('aria-owns', itemsContainerId)
            .attr('aria-activedescendant', highlightedItemId)
            .attr('aria-describedby', highlightedItemId)
            .attr('aria-disabled', this.disabled);
        this.itemsContainer.attr('aria-activedescendant', highlightedItemId);
    }
};
```

**Comment by StevenHachel** [comment]
> @StevenHachel can you try this MonkeyPatch? I have updated your example to use the MonkeyPatch and it seems to work.
> 
> [pf-9146-patched.zip](https://github.com/primefaces/primefaces/files/9452553/pf-9146-patched.zip)
> 
> ```js
> if (PrimeFaces.widget.SelectOneMenu) {
>     PrimeFaces.widget.SelectOneMenu.prototype.initContents = function() {
>         this.itemsContainer = this.itemsWrapper.children('.ui-selectonemenu-items');
>         this.items = this.itemsContainer.find('.ui-selectonemenu-item');
>         this.optGroupsSize = this.itemsContainer.children('li.ui-selectonemenu-item-group').length;
> 
>.....
>
> ```

Hello @melloware, I will test it. Thanks for the workaround.

**Comment by StevenHachel** [comment]
> ```js
> if (PrimeFaces.widget.SelectOneMenu) {
>     PrimeFaces.widget.SelectOneMenu.prototype.initContents = function() {
>         this.itemsContainer = this.itemsWrapper.children('.ui-selectonemenu-items');
>         this.items = this.itemsContainer.find('.ui-selectonemenu-item');
>         this.optGroupsSize = this.itemsContainer.children('li.ui-selectonemenu-item-group').length;
> 
>         var $this = this,
>             selectedOption = this.options.filter(':selected'),
>             highlightedItem = this.items.eq(this.options.index(selectedOption));
> 
>         //disable options
>         $this.items.filter('[disabled]').addClass('ui-state-disabled');
> 
>         //activate selected
>         if (this.cfg.editable) {
>             var customInputVal = this.label.val();
> 
>             //predefined input
>             if (customInputVal === selectedOption.text()) {
>                 this.highlightItem(highlightedItem);
>             }
>             //custom input
>             else {
>                 this.items.eq(0).addClass('ui-state-highlight');
>                 this.customInput = true;
>                 this.customInputVal = customInputVal;
>             }
>         } else {
>             this.highlightItem(highlightedItem);
>         }
> 
>         if (this.cfg.syncTooltip) {
>             this.syncTitle(selectedOption);
>         }
> 
>         // ARIA
>         for (var i = 0; i < this.items.length; i++) {
>             this.items.eq(i).attr('id', this.id + '_' + i);
>         }
> 
>         var highlightedItemId = highlightedItem.attr('id'),
>             itemsContainerId = this.itemsContainer.attr('id');
>         this.jq.attr('aria-owns', itemsContainerId);
>         this.focusInput.attr('aria-autocomplete', 'list')
>             .attr('aria-owns', itemsContainerId)
>             .attr('aria-activedescendant', highlightedItemId)
>             .attr('aria-describedby', highlightedItemId)
>             .attr('aria-disabled', this.disabled);
>         this.itemsContainer.attr('aria-activedescendant', highlightedItemId);
>     }
> };
> ```

It works, thx! :-)

Steven

**Comment by StevenHachel** [comment]
Addition:

Likewise, if the group is disabled, the SelectItem elements are all disabled, regardless of the disabled flag.
If the group is enabled, then the elements including the "disabled" value will be rendered correctly.

**Group disabled="true"**
![grafik](https://user-images.githubusercontent.com/29144366/187900597-1b5b1840-c61f-4420-a37a-e2383b11c3aa.png)

**Group disabled="false"**
![grafik](https://user-images.githubusercontent.com/29144366/187900706-66f22935-793f-4f21-8af6-b091a609f693.png)

Steven

[pfe-select_item_issue.zip](https://github.com/primefaces/primefaces/files/9469326/pfe-select_item_issue.zip)

**Comment by melloware** [comment]
I believe that is intentional.  If the group is disabled all of its underlying elements should be disabled.

**Comment by StevenHachel** [comment]
I found another bug.
If I define the "var" attribute in the selectOneMenu and make my outputs in a separate column element, the itemDisabled status doesn't work either.

![grafik](https://user-images.githubusercontent.com/29144366/189302556-d8e6ce61-0ad7-47f0-8bdd-f0c9124187a7.png)
[pf-9146-pfe-select_item_issue.with_patched.zip](https://github.com/primefaces/primefaces/files/9533537/pf-9146-pfe-select_item_issue.with_patched.zip)

Steven

**Comment by melloware** [comment]
I would open a new ticket please.
