### ISSUE TITLE
DataTable: lazy+editable throws ClassCastException when using a plain List instead of LazyDataModel

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#9147]
### Describe the bug

It doesn't work anymore since version 11.

If I set the attribute lazy="true" in the "DataTable" element, then click on edit and want to confirm the change, an exception is thrown.

```
<p:dataTable id="products1" var="product" value="#{dtEditView.products1}" editable="true" lazy="true" ....
```

Primefaces 7/8 does not have this problem.

I saw that the DataTable class has been adjusted...
```
else if ("rowEdit".equals(eventName) || "rowEditCancel".equals(eventName) || "rowEditInit".equals(eventName)) {
      loadLazyDataIfRequired(); <-- was added
```

new is in DataTable:
```
public void loadLazyDataIfRequired() {
    if (isLazy() && ((LazyDataModel) getValue()).getWrappedData() == null) {
        loadLazyData();
    }
}
```

However, getValue() returns a ArrayList and not the LazyDataModel.
[pfe-datatable_bug.zip](https://github.com/primefaces/primefaces/files/9443777/pfe-datatable_bug.zip)

Is there a workaround for this so I don't have to reset our production system back to PF8?

Steven

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.2.x, 2.3.x

### Java version

8

### Browser(s)

FF and Chrome

**Comment by StevenHachel** [comment]
what does that mean now? 
How can I deal with this, other than pointing back to the next higher version?

Steven

**Comment by tandraschko** [comment]
we fixed it for the next/upcoming version in some weeks
