### ISSUE TITLE
SelectOneListbox: wrong height?

### ISSUE THREAD

**Issue by matsandreassen** [primefaces/primefaces#9148]
### Describe the bug

Wrong CSS height attribute set for SelectOneListbox in Advanced mode?

### Reproducer

It is apparent in the [showcase](https://www.primefaces.org/showcase/ui/input/listbox.xhtml) by inspecting the children inside the listbox.

When using the component in _Advanced_ mode, the height of the _ui-selectlistbox-listcontainer_ is set to _200px_.

### Expected behavior

I expected it to scale to fit the parent. When in _Basic_ mode, the height is set to _auto_ as I expected. Is this intentional?

### PrimeFaces edition

Community

### PrimeFaces version

8.0.19, 12.0.0

### Theme

N/A

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by jepsar** [comment]
Relates to #3070 and #2847

It looks intentional to me:

https://github.com/primefaces/primefaces/blob/abf5177e34a935463662c194800f48ad4edf04d8/primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java#L318-L329

**Comment by jepsar** [comment]
You can easily work around this by applying the following CSS:
```css
.ui-selectlistbox-listcontainer {
    height: auto !important;
}
```
If you only this on certain instances, throw in a style class.
