### ISSUE TITLE
[Feature] p:menuItems or allow ui:repeat within Menu

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#915]
_p:menubar_ does not seem to allow _ui:repeat_as child and I don't want to generate markup by generating MenuItem's programmatically within JavaBean.

This introduces much boilerplate Java Code where many markup related data must be provided. (Converters and names of view parameters). 

**Support _ui:repeat_ or provide the tag _p:menuitems_.**
# Simple use case

I had following static menu where i try to insert dynamic items. Now try to imagine the boilerplate Java code I need to recreate this menu:

```
<p:menubar>
    <p:menuitem value="Home" icon="ui-icon-home" outcome="#{view.viewId}">
        <o:param name="foo" value="#{bean.foo}" converter="#{bean.fooConverter}"/>
        <o:param name="bar" value="#{bean.bar}" converter="#{barConverter}"/>
    </p:menuitem>
    <ui:repeat var="varWebPage" value="#{bean.webPages}">
        <p:menuitem value="#{varWebPage.name}" outcome="#{view.viewId}" icon="ui-icon-triangle-1-e">
            <o:param name="foo" value="#{bean.foo}" converter="#{bean.fooConverter}"/>
            <o:param name="bar" value="#{bean.bar}" converter="#{barConverter}"/>
            <o:param name="webPage" value="#{varWebPage}" converter="#{beanwebPageConverter}"/>
        </p:menuitem>
    </ui:repeat>
    <p:menuitem value="Contact us" icon="ui-icon-triangle-1-e"
        onclick="#{p:widgetVar('dlgContact')}.show(); return false;"/>
</p:menubar>
```
## Workarounds
- Create model in bean - to much work passing all data and bean is not responsible of markup
- Recreate menubar css and items using h:link (only suitable if no hierarchy needed).

**Comment by kukel** [comment]
tried using a `c:foreach`?

**Comment by djmj** [comment]
Yes tried it with `c:foreach`.
Is either ignored or an error is thrown that it is not supported.

`com.sun.faces.facelets.compiler.UIInstructions cannot be cast to org.primefaces.model.menu.MenuElement`

And aren't there cornercases where JSTL should not be mixed up with JSF?

**Comment by cagataycivici** [comment]
We've added MenuModel for cases like these. Menuitem has no renderer so ui:repeat is not a possibility.

**Comment by djmj** [comment]
This is true but a tag like `p:menuitems` would make it easier in my opinion.

**Comment by djmj** [comment]
Is it the same reasony why Menu's do not support composite:renderFacet as child? I wanted to add certain items using a composite and facet definition.

**Comment by kukel** [comment]
Yes it is...

**Comment by djmj** [comment]
@cagataycivici Why the favor for complex MenuModel if it would be much easier and flexible to define the items in markup using `p:menuitems`. Why put the "markup" into the java code if not necessary?

Another example use case is a simple state changing context menu. This is just too hard to create in java code using MenuModel. And if this is created in java it is not flexible since it is bound to a specific view or composite component since all attributes are hardcoded. JSF is about component's being **reusable**. 

I prefer building my own menu in markup then using MenuModel for such a case. In my opinion the only use case of MenuModel are recursive menues or if depth is unknown. Defining a breadcrumb could be so simple using `p:menuitems`.
    
    <p:contextMenu for="tableFoos">

        
        <p:menuitem value="Edit" outcome="/sites/edit.xhtml" ajax="false">
            <o:param name="foo" value="#{cc.attrs.logic.foo}" converter="fooConverter"/>
        </p:menuitem>

        
        <p:submenu label="Change state">
            <p:menuitems var="varState" value="#{cc.attrs.logic.stateSuccessors}">

                
                <p:menuitem value="#{varState.name}" action="#{cc.attrs.logic.changeState(varState)}" rendered="#{varState.simple"}/>

                
                <p:menuitem value="#{varState.name}" onclick="PF('#{confDlgStateChangeWidgetVar}').show();" rendered="#{not varState.simple"}/>

            </p:menuitems>
        </p:submenu>

        
        <p:menuitem value="Delete" action="#{cc.attrs.logic.delete()}" update=":#{cc.clientId}:tableFoos"/>
    </p:contextmenu>
