### ISSUE TITLE
Carousel: Reverse swipe direction on mobile

### ISSUE THREAD

**Issue by oliverdiaz8** [primefaces/primefaces#9154]
### Describe the bug

The actual swipe direction for "next" or "right" (slide right to left) swipes to previous item (if any), and vice versa. This behavior also applies to vertical orientation. Swipe directions works fine in v8.  

### Reproducer

1. Use a carousel with more than one item.
2. Slide from right to left (forwards).
3. Carousel will slide to the previous item, if any.

### Expected behavior

When you swipe from right to left, the next item should be displayed. This applies from the other direction and also vertical orientation.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

11

**Comment by melloware** [comment]
Agreed these are backwards.  Fixing them.
