### ISSUE TITLE
BlockUI: Doesn't work with dynamic content

### ISSUE THREAD

**Issue by wsaca** [primefaces/primefaces#9155]
### Describe the bug

When is used with dynamic content it's not working, with previous versions it worked because it was rendered inside the blocked component.

### Reproducer

I include an example [primefaces-test-blockui.zip](https://github.com/primefaces/primefaces/files/9446549/primefaces-test-blockui.zip)

Run it `mvn jetty:run` and go to `http://localhost:8082/primefaces-test/`

### Expected behavior

p:blockUI should fit the blocked component, even if an ajax event updates it.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Confirmed. Thanks for the reproducer.

**Comment by wsaca** [comment]
@melloware the showcase example "Client Side API" doesn't work either, I think this issue won't fix it. should be resolved in another issue?

https://www.primefaces.org/showcase/ui/misc/blockUI.xhtml

**Comment by melloware** [comment]
Can you update your reproducer to show me?  I have your current reproducer working.

**Comment by wsaca** [comment]
@melloware I have changed the example to include 2 cases:
1. First press the "Process" button and then press the "Block Panel" button. 
2. Click "Header II" tab and then press the "Block Panel" button.

[primefaces-test-blockui.zip](https://github.com/primefaces/primefaces/files/9456904/primefaces-test-blockui.zip)

**Comment by melloware** [comment]
Thanks for the updates I will take a look.

**Comment by melloware** [comment]
Thanks for all your great test cases I was able to fix them all and make the component more efficient on resizing!

**Comment by crocimi** [comment]
Thank you for the quick reply! I have tested it integrating the changes directly in my primefaces-custom.js and the issue seems to be fixed! The performance is constant and I see only one "alignOverlay" event for each blockUI, even after multiple updates.

Thx :-)
