### ISSUE TITLE
Datatable currentPageReportTemplate value containing apostrophe ' breaks javascript

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#916]
Hi everyone,

I'm using Datatable from Primefaces 5.2, and the problem I have looks similar to this one: https://goo.gl/GMc3nF. I defined currentPageReportTemplate attribute containg an apostrophe and it breaks javascript code in Chrome.

**Comment by tandraschko** [comment]
Feel free to provide a PR here
