### ISSUE TITLE
InputNumber: wrong value shown

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#9166]
### Describe the bug

If a inputNumber has a minValue, and the value to show is lower, minValue is displayed instead, even if the component is disabled.
Same happens with maxValue.

### Reproducer

```xhtml
<p:inputNumber value="0" disabled="true" minValue="1" decimalPlaces="0"/>
<p:inputNumber value="100" disabled="true" maxValue="99" decimalPlaces="0"/>
```

### Expected behavior

The provided value should be displayed, even if it is lower then minValue or greater then maxValue.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC3

### JSF implementation

All

### JSF version

all

### Java version

11

### Browser(s)

all

**Comment by tandraschko** [comment]
why not just remove min/maxValue from a disabled input?

**Comment by NicolaIsotta** [comment]
Well my use case is a little more complex:
- data comes from a java class where numeric fields have validation annotations (eg Min,Max,DecimalMin...)
- primefaces.TRANSFORM_METADATA is enabled -> validation metadata are added also for disabled inputs
- java class is used for both data editing (fields enabled) and visualization (fields disabled)

Aside from that, I think that the value coming from the bean should always be displayed, even for enabled inputs.

**Comment by melloware** [comment]
@NicolaIsotta i think your issue is from autoNumeric: https://github.com/autoNumeric/autoNumeric/issues/543

**Comment by melloware** [comment]
Yeah if you are past the min or max I do NOT think the value should be displayed its invalid.

**Comment by NicolaIsotta** [comment]
Seems like coercion has been added to avoid problems in AutoNumeric:
https://github.com/primefaces/primefaces/blob/f9ec9fe023a4fc2c9da41e04f1a8dfd84bc88522/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java#L108-L109
Guess I'll have to find a different solution. Is it possible to disable validation metadata passthrough for disabled/readonly inputs?

**Comment by NicolaIsotta** [comment]
Seems like coercion has been added to avoid problems in AutoNumeric:
https://github.com/primefaces/primefaces/blob/f9ec9fe023a4fc2c9da41e04f1a8dfd84bc88522/primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java#L108-L109
Guess I'll have to find a different solution. Is it possible to disable validation metadata passthrough for disabled/readonly inputs?
