### ISSUE TITLE
Touchable not deactivateable on component level

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9178]
p:dataTable touchable=false does nothing

See; https://github.com/primefaces/primefaces/blob/2b1384a3c6464c995e029757eeebd8cb6144f4d9/primefaces/src/main/java/org/primefaces/util/ComponentUtils.java#L269

If either local or global is enabled -> touchable true

i think thts wrong
default local and global should be true
but if one of both is false, it should be touchable false

same applies to RTL and flex, too?

@melloware WDYT?

**Comment by melloware** [comment]
I went back and forth on this the idea was...

Local flag should always override the global so if Global = False but you want to turn one component on for touchable and add `touchable=true` to just 1 datatable that should enable it.

However if local="false" and global="true" its turning it on which is your scenario.   So we need to basically check if `undefined` on local before checking the global value.

**Comment by tandraschko** [comment]
so we need to change TouchAware#isTouchable to object and default to false
then we can do:

```
    public static boolean isTouchable(FacesContext context, TouchAware component) {
        Boolean local = component.isTouchable();
        if (local != null) {
           return local;
        }
        return PrimeRequestContext.getCurrentInstance(context).isTouchable();
    }

```

right?

**Comment by melloware** [comment]
That look right to me!

**Comment by melloware** [comment]
And probably the same for flex and rtl ?

**Comment by tandraschko** [comment]
yep
please review, commited for touchable now
will continue with flex+rtl

**Comment by tandraschko** [comment]
looks like flex has better behavior as the global and local default is false
will leave this for now

**Comment by melloware** [comment]
Thank you. Looks good to me!
