### ISSUE TITLE
Galleria: add hide to JS API

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#9180]
### Description

Hi, 

I´m looking for an option to hide the **p:gallery** in fullscreen with pressing ESC....

I cannot find a JS function to hide it (only show())
https://primefaces.github.io/primefaces/jsdocs/classes/src_PrimeFaces.PrimeFaces.widget.Galleria.html

I´ve tried also something like:
`	<p:hotkey bind="esc"
				handler="PF('myWidget').refresh()" />`

But it´s also not working

Can this be implemented?

### Describe the solution you would like

Fullscreen will be closed after press ESC (as you know from p:dialog)

**Comment by jepsar** [comment]
Workaround: `PF('myWidget').primeGalleriaWidget.hide()`

**Comment by rider87** [comment]
Great, that workaround is working... Thanks
