### ISSUE TITLE
SelectOneMenu: itemEscaped doesn't work anymore for selected items

### ISSUE THREAD

**Issue by Mockabear** [primefaces/primefaces#9184]
# 1) Environment
PrimeFaces version: 11.0.7. ELITE
Application server + version: Tomcat 9.0.45
Affected browsers: Chrome, Firefox, ..

# 2) Expected behavior
A selected selectItem with reseverd HTML chars should be displayed, formatted, not escaped. 

# 3) Actual behavior
Some reseverd HTML characters of a selected selectItem are shown escaped. - Regardless of selectitems 'escape' property settigns.
![image](https://user-images.githubusercontent.com/99366998/188832287-dcb28c33-448e-487e-8280-70bfec96403b.png)

# 4) Steps to reproduce
Use attached testcase / webapp  "pf11quot.zip" (or following xhtml page) and select Items with up / down arrows..

[pf11quot.zip](https://github.com/primefaces/primefaces/files/9504283/pf11quot.zip)

# 5) Sample XHTML
```
<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

	<h:head>   
		<title>PrimeFaces Test</title>
	</h:head>
	<h:body>
		<h:form id="contentForm">
			<p:selectOneMenu>
				<f:selectItem itemLabel="&gt; greater fails" />
				<f:selectItem itemLabel="&gt; although escape = false"  escape="false"/>
				<f:selectItem itemLabel="&lt; less fails" />
				<f:selectItem itemLabel="&amp; Ampersand fails" />
				<f:selectItem itemLabel="&quot;Quoting works&quot;" />
			</p:selectOneMenu>
		</h:form>
	</h:body>
</html>
```

**Comment by tandraschko** [comment]
There is no "escape" attribute, its called [itemEscaped](https://javaee.github.io/glassfish/doc/5.0/vdldoc/f/selectItem.html#itemEscaped)

but its always escaped, right

**Comment by tandraschko** [comment]
it looks like it was broken/changed due: https://github.com/primefaces/primefaces/issues/6418

@christophs78 can you check?

**Comment by christophs78** [comment]
I can check this on Saturday.

**Comment by christophs78** [comment]
We have an integrationtest for something very similar:
![image](https://user-images.githubusercontent.com/10461942/189429954-226b5ad7-8ad2-4887-b255-edbb5ff47331.png)

https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/selectonemenu/SelectOneMenu002.java, https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectonemenu/SelectOneMenu002Test.java

At least it's not totally broken.

**Comment by christophs78** [comment]
![image](https://user-images.githubusercontent.com/10461942/189432705-248b918e-3ad2-42e9-b068-ff3f419cca3d.png)

PR add´s an additional integrationtest and shows itemEscaped is working.

**Comment by Mockabear** [comment]
Thanks for taking a look, but I don’t understand the testcases: The pics from the test don‘t reflect the error situation. The items with special chars are **not** selected. The error occurs **only** on selection. See picture from point 3) above.

**Comment by Mockabear** [comment]
.. and just for clarification: Why is this issue „invalid“?

**Comment by melloware** [comment]
@SLAPNet-dev I have marked it "needs investigation" it sounds like more work is needed on our end.

**Comment by christophs78** [comment]
Are you able to reproduce this with 12.0.0-SNAPSHOT? (or 12.0.0-RC3)

**Comment by Mockabear** [comment]
Yes. Same behaviour under 12.0.0-RC3.

**Comment by christophs78** [comment]
@SLAPNet-dev : You break this by walking through the options with cursor-up and cursor-down? (Your example has no itemValues so it does not work when you click on items with the mouse.)

After switching to itemEscaped it work´s IMO as @tandraschko suggested earlier:
```
<h:form id="contentForm">
    <p:selectOneMenu>
        <f:selectItem itemLabel="&gt; greater fails" itemValue="1" />
        <f:selectItem itemLabel="&gt; although escape = false" itemEscaped="false" itemValue="2"/>
        <f:selectItem itemLabel="&lt; less fails" itemValue="3" />
        <f:selectItem itemLabel="&amp; Ampersand fails" itemValue="4" />
        <f:selectItem itemLabel="&quot;Quoting works&quot;" itemValue="5" />
    </p:selectOneMenu>
</h:form>
```

**Comment by Mockabear** [comment]
Sorry for the trouble. Seems like erverything works like expected! 
We've had an issue with dynamic created selectitems during a migrating from PF 8/JSF 2.2 to PF11/JSF2.3.  We had to clear the escape-flag on the selectitem to fix it. 
During further investigation we build this wrong example with the help from IntelliJ..
![image](https://user-images.githubusercontent.com/99366998/189488434-fc9c5276-3ee9-40a0-ad13-c09626b1fc4b.png)

**Comment by melloware** [comment]
This has me thinking either Mojarra or Myfaces taglib is wrong here is what Eclipse shows me for the tablib for `f:selectItem`

![image](https://user-images.githubusercontent.com/4399574/193843363-4f79d0a6-3639-47d4-bf15-76a4bd32f105.png)

**Comment by Mockabear** [comment]
Mmhh.. Mojarra's taglib looks fine:
![image](https://user-images.githubusercontent.com/99366998/193918166-c096fbcd-0944-4da6-8c7c-037109d1e0f3.png)
It seems as if the wrong properties (in IntelliJ) are generated by the JSF-Plugin:
![image](https://user-images.githubusercontent.com/99366998/193919222-1c1452f1-6377-481e-b050-3ccef9cf2000.png)
Regarding to it's header it's a 2.0 TLD Version. [In the 2.0 Specs](https://docs.oracle.com/javaee/6/javaserverfaces/2.0/docs/pdldocs/facelets/f/selectItem.html) the property is indeed simply called 'escape'
![image](https://user-images.githubusercontent.com/99366998/193919559-704b1d1e-a013-4eba-9855-57297e8e159f.png)

**Comment by melloware** [comment]
ah yes that is definitely wrong.  It is `itemEscaped`.  I guess that is why it has caused confusion!
