### ISSUE TITLE
BreadCrumb: Two home icons rendered if first menuitem includes a FontAwesome icon

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#9188]
### Describe the bug

A breadcrumb component renders two icons  in first link (the default one + icon from menuitem) if first menuitem contains an "icon" attribute with a FontAwesome value like : icon="fal fa-house".

![image](https://user-images.githubusercontent.com/26894018/189176569-ffbf52c7-3fff-4c2d-b33e-18a5acd7fc7e.png)

### Reproducer

`<p:breadCrumb>
    <p:menuitem icon="fal fa-house" value="Home" />
</p:breadCrumb>`

### Expected behavior

I think there are 2 possible solutions : 
 - Have a "homeIcon" parameter in breadcrumb to let the dev choose its own icon
 - Use the icon of first menuitem if exists or else use default prime home icon if not

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.5 and 12.0.0-SNAPSHOT

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

All

**Comment by melloware** [comment]
I think `homeIcon` at a minimum would be a good attribute.
