### ISSUE TITLE
When primefaces.HIDE_RESOURCE_VERSION and primefaces.FONT_AWESOME set to true, there is 404 on js console

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#9189]
### Describe the bug

When enabling :

```
<context-param>
      <param-name>primefaces.HIDE_RESOURCE_VERSION</param-name>
      <param-value>true</param-value>
  </context-param>
  <context-param>
      <param-name>primefaces.FONT_AWESOME</param-name>
      <param-value>true</param-value>
  </context-param>
```

in web.xml

I get an error 404 NOT FOUND on js console:

`.../javax.faces.resource/fa/fontawesome-webfont.woff.jsf?ln=primefaces?v=4.7.0`

beacuse in PrimeResourceHandler font awesome version number is appended as libraryName to primefaces:

![image](https://user-images.githubusercontent.com/21099773/189320231-950ee997-cf3f-48e8-8935-8f6d1ffefbdd.png)

### Reproducer

1. Enable font awesome and hide reourece version in web.xml
2. start an apllication
3. go to js console and see the 404 error

### Expected behavior

Font awesome to load properly

### PrimeFaces edition

Elite

### PrimeFaces version

7.0.28

### Theme

Aristo

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

All

**Comment by tandraschko** [comment]
in general we cant help you as mentioned here: https://github.com/primefaces/primefaces#community--elite--pro

but please debug where libraryName=primefaces?v=4.7.0 comes from
normally a library doesnt contain any versions or params

**Comment by majkers** [comment]
I think it comses from font-awesome.css
```
 @font-face {
    font-family: 'FontAwesome';
    font-display: auto;
    src: url("#{resource['primefaces:fa/fontawesome-webfont.eot']}?v=4.7.0");
    src: url("#{resource['primefaces:fa/fontawesome-webfont.eot']}&#iefix&v=4.7.0") format('embedded-opentype'), 
      url("#{resource['primefaces:fa/fontawesome-webfont.woff2']}?v=4.7.0") format('woff2'), 
      url("#{resource['primefaces:fa/fontawesome-webfont.woff']}?v=4.7.0") format('woff'), 
      url("#{resource['primefaces:fa/fontawesome-webfont.ttf']}?v=4.7.0") format('truetype'), 
      url("#{resource['primefaces:fa/fontawesome-webfont.svg']}?v=4.7.0#fontawesomeregular") format('svg');
    font-weight: normal;
    font-style: normal;
}
```

**Comment by majkers** [comment]
I know I have an elite version but I am sure it won't work in community versions as well

**Comment by tandraschko** [comment]
community doesnt have the built-in font_awesome anymore
so if you can provide a reproducer in community, i can check
otherwise i can not really help, i can just ping @mertsincan or you can go PrimeFaces PRO

**Comment by majkers** [comment]
I can't simply migrate to community version and going PRO is also not the case...If you could ping Primetek team I would be graceful :)

**Comment by tandraschko** [comment]
all right, i will ping him in our team channel and will close the issue for now

**Comment by majkers** [comment]
ok Thanks!

**Comment by majkers** [comment]
> community doesnt have the built-in font_awesome anymore so if you can provide a reproducer in community, i can check otherwise i can not really help, i can just ping @mertsincan or you can go PrimeFaces PRO

I' ve just downloaded 10 and 8 sources of community version. They DO have font-awesome in it!!!

![image](https://user-images.githubusercontent.com/21099773/189325418-38827b79-e452-4842-a2ab-d1ca7e47fc3b.png)

**Comment by tandraschko** [comment]
but 10.0.0 doesnt have HIDE_RESOURCE_VERSION, which i could debug
and even then i could not fix it in 7.0.x

**Comment by majkers** [comment]
ok I see :(

**Comment by melloware** [comment]
@majkers i know you said our documentation is "weak" but why even use the built in PF FontAwesome??? you should be using the external FontAwesome then you can use any version of FA you want and won't have this issue with `v=` see our EXCELLENT docs: https://primefaces.github.io/primefaces/11_0_0/#/core/fonticons?id=fontawesome

**Comment by majkers** [comment]
@melloware yeah you are right. I just did it and with font awesome beining used from external lib, there is no related bug... But I am not so sure about fa version. Here https://primefaces.github.io/primefaces/12_0_0/#/core/fonticons it is said that 4.x and 5.x version are supproted so no word about 6.x

**Comment by melloware** [comment]
6.x is I am using it in production.

**Comment by melloware** [comment]
I just updated the docs to add 6.x as supported.

**Comment by majkers** [comment]
ok thanks
