### ISSUE TITLE
SelectOneMenu: itemDisabled attribute with "var" attribute + custom columns

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#9190]
### Describe the bug

If I define the "var" attribute in the selectOneMenu and make my outputs in a separate column element, the itemDisabled status doesn't work either.

![grafik](https://user-images.githubusercontent.com/29144366/189364226-6b08239c-30b0-4281-9ec1-b73b7a867f5d.png)
[pf-9146-pfe-select_item_issue.with_patched.zip](https://github.com/primefaces/primefaces/files/9535896/pf-9146-pfe-select_item_issue.with_patched.zip)

### PrimeFaces version

11

### JSF implementation

Mojarra

### JSF version

2.2.x, 2.3.x

### Java version

8/11

### Browser(s)

FF and Google Chrome

**Comment by melloware** [comment]
Related to: https://github.com/primefaces/primefaces/issues/9184 ???

**Comment by StevenHachel** [comment]
It's not related. I can only reduce the example project to this error if it would be better.

**Comment by melloware** [comment]
This is not a bug.  When you control the rendering you need to control the state rendering.  I changed your example to this..

```xml
<h:outputLabel value="#{item.label}" style="font-size: 12px;" styleClass="#{item.usable ? 'ui-state-disabled' : ''}"/>
```

**Comment by StevenHachel** [comment]
Okay, if this isn't supposed to be a bug, why was it working on PF5/6/7/8 before? Shouldn't this feature change appear in the migration document?

**Comment by melloware** [comment]
To me it was a bug before and was fixed.

 When you render with your own `<p:column>` you should be in complete control of the rendering.  For example say you want to render with a `strikethrough` or render it in RED when disabled or whatever you want.  That is the whole point of the custom `<p:column>` rendering...that you take complete control of how items are rendered.

**Comment by StevenHachel** [comment]
Okay, if it stays that way, that's a very good thing. :-)
