### ISSUE TITLE
Growl: support simultaneous display of sticky and non sticky of different growl components

### ISSUE THREAD

**Issue by shelcomite** [primefaces/primefaces#9201]
### Description

If you add 2 p:growl elements to your page (e.g. one sticky="false" and one sticky="true") and you add a message to each p:growl you can only see one of the messages. The other message is hidden by the other.
=> Same position different z-index.

See Showcase: https://www.primefaces.org/showcase/ui/message/growl.xhtml
(Click on "Info"/"Warn" Button and the "Sticky" Button)

### Describe the solution you would like

It would be nice to have a growl container component to support simultaneous display of sticky and non sticky growl messages without them overlapping (and maybe only one aria-live="polite" on the same page).

**Comment by melloware** [comment]
This is a difficult one because both growls have no idea about each other.

**Comment by jepsar** [comment]
How about extending FacesMessage and add a sticky attribute?

**Comment by Sungray** [comment]
> How about extending FacesMessage and add a sticky attribute?

That would be a very good solution. I'm currently stuck on this one too.

**Comment by melloware** [comment]
With this fix it simply adds a style `ui-growl-sticky` to the container allowing you to control sticky from non sticky separately with CSS like...

```css
body .ui-growl.ui-growl-sticky {
  top: 85px;
}

body .ui-growl {
  top: 170px;
}
```

Results in having them not stacked:
![image](https://github.com/primefaces/primefaces/assets/4399574/943b8d32-176d-4c91-99b7-a2cba4763912)
