### ISSUE TITLE
inputNumber component and minValue attribute

### ISSUE THREAD

**Issue by ojekanmi** [primefaces/primefaces#921]
The inputNumber declaration below will not accept any input, however when I removed the minValue attribute, it accept input. What am not doing wrong here? Also, the input will go beyond the maxlength attribute specified.

<pe:inputNumber id="codeKat" value="#{myMB.codeK}" minValue="3000"   decimalSeparator=""  thousandSeparator=""    required="true" maxlength="6" decimalPlaces="0"/>

**Comment by cagataycivici** [comment]
Please use forum for questions like these. Also there is no code in your post.

**Comment by ojekanmi** [comment]
Hi,

I asked in the forum. I was requested to open a ticket. See below. 
The code is
          pe:inputNumber id="codeKat" value="#{myMB.codeK}" minValue="3000"   decimalSeparator=""  thousandSeparator=""    required="true" maxlength="6" decimalPlaces="0"/>

"The problem is currently that the vmin is applied before the value is applied to the input. Therefore the validation of the JS fails before we even set the value.
Please create a ticket in the PrimeFaces issue tracker, as the component was already moved to PrimeFaces."  - Thomas Andraschko
