### ISSUE TITLE
DatePicker: Closing Itself Immediately

### ISSUE THREAD

**Issue by seeker105** [primefaces/primefaces#9213]
I'm using a DatePicker in a Primefaces dialog. The code for the field is 
```
        <p:datePicker id="date"
                      mask="true"
                      selectOtherMonths="true"
                      monthNavigator="true"
                      yearNavigator="true"
                      showButtonBar="true"
                      placeholder="mm/dd/yyyy"
                      pattern="MM/dd/yyyy"
                      value="#{beanName.property">
            <f:convertDateTime type="date" pattern="MM/dd/yyyy" />
            <f:validateBean for="date" validationGroups="group.package.and.name"/>
        </p:datePicker>
```

When the user clicks on the field it opens the datePicker, showing the current month and the dates. But the datePicker disappears when the mouse button is released. As long as the button is held down, the datePicker is visible. But it disappears as soon as the button is released. 
If the user clicks on the field a second time the datePicker will open and stay open. But they have to click twice every time.

I'm looking for a solution that will cause the datePicker to only need one click. It works normally on other pages in the same application and I haven't been able to identify any differences between this field and others. Can anyone offer a suggestion?

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
Will close until a PF Test reproducer is provided.

**Comment by melloware** [comment]
@jirkis I can't reproduce in Firefox or Chrome with PF 12 or 13 using your reproducer.

Here is mine attached:
[pf-9213.zip](https://github.com/primefaces/primefaces/files/11415368/pf-9213.zip)

Run `mvn clean jetty:run`

**Comment by jirkis** [comment]
@melloware  Hello, thanks for the update. I updated your pom to use PF version 12.0.0. (13.0.0-SNAPSHOT couldnt be downloaded). Anyway, I reproduced it with newest Chrome with disabled extensions and in incognito mode. 

Please see attached video:
https://drive.google.com/file/d/1C1gVUZ5wyrKtuJ8-qd8G3pchVdjCcv2K/view?usp=sharing

**Comment by melloware** [comment]
Hmm it must be a browser size or monitor issue your behavior does not happen for me with 12.0.0.

**Comment by jepsar** [comment]
Works for me in both the latest Chrome and Firefox on macOS.

**Comment by melloware** [comment]
OK I think I see the trick to it from your video.  The Popup has to open exactly with the TimePicker text both underneath the mouse so the onClick probably needs to stopPropagation

**Comment by melloware** [comment]
@jirkis can you try this.

In that reproducer edit the `test.js` file and add this MonkeyPatch

```js
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.onInputClick: function(event) {
        event.preventDefault();
        event.stopPropagation();

        if (this.documentClickListener) {
            this.datepickerClick = true;
        }

        if (this.options.showOnFocus && !this.isPanelVisible()) {
            this.showOverlay();
        }
    };
};
```

Then restart the reproducer and make sure to press CTRL+F5 to reload the Javascript when you hit the page. See if that fixes the issue?

**Comment by jirkis** [comment]
@melloware  I am afraid this patch did not fix the issue. I think the main problem is when the cursor is hovering over the overlay when it pops up. But when it is not hovering over the overlay, the overlay stays opened. Maybe it has something to do with mouseup/down listeners? 

Please see the video: 
https://drive.google.com/file/d/1C9ch3T5XHJNTI3vBcSe0b2uFYiOrOxWT/view?usp=sharing

**Comment by melloware** [comment]
Ok yeah it has to be either click or mouse event on the input bubbling up to the overlay when it's over it. 

I have tried everything to reproduce your issue locally and it doesn't happen for me.

**Comment by jirkis** [comment]
I have just confirmed, that the behaviour happens only when using laptop touchpad. When I plugin the USB mouse, everything works fine. 
So I tried to enable datepicker attribute touchUI="true" but nothing changed...
Could you try to reproduce?

**Comment by melloware** [comment]
Ahh that helps because I am using a real mouse and I cannot reproduce the issue on `Version 112.0.5615.138 (Official Build) (64-bit)`

**Comment by jepsar** [comment]
It's also working for me using a touchpad (macOS)

**Comment by melloware** [comment]
I have a Lenovo Thinkpad and I can make it happen.   So the touchpad behavior is somehow different than the mouse on Windows.

**Comment by melloware** [comment]
@jirkis can you try this this works for me.

```js
if (PrimeFaces.widget.DatePicker) {
    $.prime.datePicker.prototype.showOverlay = function () {
            if (!this.options.inline && !this.isPanelVisible() && this.transition) {
                var $this = this;

                this.transition.show({
                    onEnter: function() {
                        if ($this.options.onBeforeShow) {
                            $this.options.onBeforeShow.call($this);
                        }

                        $this.alignPanel();
                    },
                    onEntered: function() {
                        if (!$this.options.touchUI) {
                            $this.datepickerClick = true;
                            setTimeout(function () {$this.datepickerClick = false;}, 200);
                            $this.bindDocumentClickListener();
                            $this.bindWindowResizeListener();

                            if (!$this.options.inline) {
                                $this.bindScrollListener();
                            }
                        }

                        if (($this.options.showTime || $this.options.timeOnly) && $this.options.timeInput) {
                            $this.panel.find('.ui-hour-picker input').trigger('focus');
                        }
                    }
                });
            }
        };
};
```

**Comment by melloware** [comment]
Yeah you just need to make sure this patch loads after other JS code and it should work fine globally.  Then just put a TODO in there to remove in PF13.
