### ISSUE TITLE
TreeTable: Strict CSP shows always expand icon 

### ISSUE THREAD

**Issue by enricokl** [primefaces/primefaces#9214]
### Describe the bug

If you are use primefaces.CSP true with default-src: 'self' or style-src: 'self' in primefaces.CSP_POLICY in web.xml, then in treetable the expand icon are always shown, even on an leaf.

### Reproducer

Set in web.xml the param primefaces.CSP to true and set the param primefaces.CSP_POLICY to default-src: 'self' or style-src: 'self'.

The TreeTable shows the expand icon always, even on a leaf.

### Expected behavior

Expand icon should hide, if the node is a leaf.

### PrimeFaces edition

Elite

### PrimeFaces version

10.0.*, 11.0.*

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

### Browser(s)

Firefox, Edge, Chrome not tested

**Comment by enricokl** [comment]
I have found the problem. The style of a node in TreeTableRenderer was set to 'visibility:hidden', when the node is a leaf. But the CSP "style-src: 'self'" delete the style attribute.

**Comment by melloware** [comment]
Yep you can't only use `Script-src` with PrimeFaces CSP.  There are too many inline styles as this project is 12+ years old and would need a major overhaul.  So only `script-src:` is supported.
