### ISSUE TITLE
Does PrimeFaces Dialog frameworks support inputText Ajax event and Listener?

### ISSUE THREAD

**Issue by cidylong** [primefaces/primefaces#9226]
### Describe the bug

I'm trying popup a dialog from backbean by using:

PrimeFaces.current().dialog().openDynamic(CONTRACTITEM_EDIT_DIA, buildDiaOptions(), null);

dialog is showing well, but when I put some inputText fields work with 

<p:ajax event="keyup" process="@this" update="@all" listener="#{contractitemSWController.onWeeklyRateChange()}" />

There is no response at all. 

It works fine in regular JSF view context.

### Expected behavior

when field value popup or change, ajax event will trigger backbean action.

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11.0.13

### Browser(s)

Safari 16.0 on Mac Mini

**Comment by tandraschko** [comment]
please provide a primefaces-test reproducer

maybe you just did not understand that the dialog-framework is a new view in a iframe and update `@all` will only update the content in the iframe

**Comment by melloware** [comment]
Will close until a PF Test reproducer is provided.
