### ISSUE TITLE
print all  p:datatable scrollable="true"

### ISSUE THREAD

**Issue by pfdeveloper** [primefaces/primefaces#923]
printer p:datatable  scrollable="true" print only what showing in screen ?? i want to print all datatable ..thank you

**Comment by sudheerj** [comment]
I think this behavior is as expected or designed for scrollable table,datatable with pagination etc.It prints what available in the page.You can follow the workarounds as mentioned below.

[(http://forum.primefaces.org/viewtopic.php?f=3&t=34395)](url)
[http://stackoverflow.com/questions/30120514/pdatatable-with-paginator-how-to-use-pprinter-to-print-all-rows-without-pagin](url)
