### ISSUE TITLE
DatePicker: Validation error "INVALID_RANGE_DATES_SEQUENTIAL" when dates are the same

### ISSUE THREAD

**Issue by newk5** [primefaces/primefaces#9231]
### Describe the bug

If you have a datepicker using selectionMode="range" and select the same date for the starting date and end date, you get an error saying that the start date is greater than the end date, which is incorrect. I tracked down the issue to this line: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/datepicker/DatePicker.java#L178

I changed it in my local copy of primefaces from:
```java
 if (isValid() && startDate.compareTo(endDate) > -1) {
         setValid(false);
         validationResult = ValidationResult.INVALID_RANGE_DATES_SEQUENTIAL;
 }
````
to:
```java
 if (isValid() && startDate.compareTo(endDate) > 0) {
         setValid(false);
         validationResult = ValidationResult.INVALID_RANGE_DATES_SEQUENTIAL;
 }
````
Which fixed the issue

### Expected behavior

No validation error should occur when the dates are the same.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC3

### JSF implementation

All

### JSF version

Any

### Java version

Any

### Browser(s)

Any

**Comment by melloware** [comment]
PR Submitted letting the integration tests run now

**Comment by jepsar** [comment]
Let me check if this is really what we want

**Comment by jepsar** [comment]
@newk5 what is the type of object you are using? With a `LocalDateTime` or `Date` for example, end dates are set to the very end of the day. Also, what's missing in the report is that you are using `view="month"`. It might very well be that we should fix this issue by setting the end date to the very end of the month instead of simply adjusting the check.

**Comment by newk5** [comment]
@jepsar  Yea I'm using view="month", and pattern="MM-yyyy" here's a screenshot of my debugger on that specific line on DatePicker.java
![image](https://user-images.githubusercontent.com/32560510/191901499-46135194-5816-45b1-b40e-74583fe0b098.png)

You can see they are both exactly the same, I think it's just that the comparator check that is incorrect. In this specific case it will return 0 which means the dates are the same so I think we shouldn't throw an error saying the start date is greater.

**Comment by newk5** [comment]
Also as I said above I chose the same exact month for both the start and end date so those values there on the debugger are correct.
