### ISSUE TITLE
PrimeIcons: Migrate to 6.0.1

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#9244]

**Comment by jepsar** [comment]
Should be like https://github.com/primefaces/primefaces/commit/b1273b0be841d5ebc7ea23c9e1570933114b2b5d + showcase

**Comment by melloware** [comment]
@jepsar want to submit a PR and we can see if it just works.  I am pretty sure its backwards compatible with current icons.

**Comment by jepsar** [comment]
Yes, just posted on Discord. Should be straight forward.
