### ISSUE TITLE
BlockUI: If there's an ajax call on the button, the blockUI vanishes before finishing the ajax

### ISSUE THREAD

**Issue by SirError** [primefaces/primefaces#9251]
### Describe the bug

If the button that triggers the blockUI has an ajax call 

```
<p:commandButton id="btn" update="@form" value="Submit" action="#{testView.doNothing()}">
	<p:ajax oncomplete="console.log('a');"/>
</p:commandButton>
```

the blockUI will be called and then disappears before the whole ajax is completed.

This works on Prime 7

### Reproducer
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/9674905/primefaces-test-master.zip)

Click the Open button,  then click Submit.

### Expected behavior

BlockUI should be visible until the end of the process.

### PrimeFaces edition

Community

### PrimeFaces version

12-RC3

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
You are using CommandButton incorrectly and if you watch F12 Network tab you will see you are firing two AJAX requests every time you press the Submit Button.

It works if you use CommandButton properly like this.

```xml
<p:commandButton id="btn" 
     update="@form"
     value="Submit" 
     action="#{testView.doNothing()}" 
     oncomplete="console.log('a');">
</p:commandButton>
```
