### ISSUE TITLE
InputNumber: The value of the component is different from the submitted value

### ISSUE THREAD

**Issue by SirError** [primefaces/primefaces#9257]
### Describe the bug

If some action updates the inputNumber from the backing bean the value showed might be different from the value that will be submitted.

Example: 
the backing bean sends the value 18.0000
and the component will show 18.00

once you submit it, the server will receive 18.0000 instead of 18.00
this might cause some trouble with the validation @Digits

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/9698336/primefaces-test-master.zip)

### Expected behavior

Click on "Set Wrong Value"
The inputnumber will receive 18.00
Click on Submit 
the field should submit 18.00, however it will submit 18.0000 and fail on the validation.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC3

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

11

**Comment by melloware** [comment]
OK this will only happen with padded 0's.  

But it is interesting why you are setting a known invalid value and having the UI format it?  To me you should never count on the UI component formatting a value.

We only copy to the hidden input if the numbers are not the same but "18.00" and "18.0000" are the same number.

```js
/**
     * Wraps the events on the external (visible) input to copy the value to the hidden input.
     * @private
     * @return {number} The original value of the hidden input.
     */
    copyValueToHiddenInput: function() {
        var oldVal = this.hiddenInput.val();
        var newVal = this.getValue();

        if (((oldVal === '') ^ (newVal === '')) || Number(oldVal) !== Number(newVal)) {
            this.setValueToHiddenInput(newVal);
        }

        return oldVal;
    },
```

**Comment by melloware** [comment]
OK fixed submitted the initial value must always be formatted to match what the UI is displaying.

**Comment by SirError** [comment]
Thanks, @melloware , I know the example is a bit weird, but I had to simplify it as much as possible to create an "easy to show" reproducer.

thanks again!
