### ISSUE TITLE
p:steps readonly="false" not working

### ISSUE THREAD

**Issue by khazz** [primefaces/primefaces#926]
I updated the PrimeFaces lib of my project from 5.2 to 5.3 and now I can't navigate between steps by just clicking them. It was working just fine in 5.2.

**Comment by cagataycivici** [comment]
This is expected as due to a UX change, items equal or bigger than activeIndex are not clickable since user has not finished the previous step. In demo, first step (index 0) is clickable as activeIndex="1".
