### ISSUE TITLE
DatePicker: onchange event called twice using touchUI="true"

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#9260]
### Describe the bug

When editing a cell with a datepicker in it, `currentCell` property returns null only on an iPhone
This is due to on `onchange` event being called twice and resetting `currentCell` to null

This can also be reproduced on Safari (Mac/Desktop) Developer Tools by impersonating iPhone
actual iPhone is not necessary.

### Reproducer

See https://github.com/lprimak/apps/blob/f3afa201abe1250d543cdbe6ab2faaeb17566fa1/emailmanager/hope-website/testdatefield.xhtml#L37

### Workaround:
```
onchange="var bt = PF('birthdayTable');
                    if (bt.currentCell) bt.saveCell(bt.currentCell)"
```

### Expected behavior

`onchange` event would be called only once
*or*
`currentCell` would be non-null the second time on both iPhone and other browsers

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0RC3, 12.0.0

### Theme

Default

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8 through 19

### Browser(s)

Safari on iPhone

**Comment by jepsar** [comment]
@lprimak Can you please create a https://github.com/primefaces/primefaces-test which we can use to debug?

And do you have a suggestion how to fix this? Seems like a 3rd party issue to me.

**Comment by lprimak** [comment]
Hi, @jepsar 
Reproducer is here: https://github.com/flowlogix/widget-currentcell-reproducer

Looks like the bug has something to do with a different screen size on the phone that makes
CSS/JS not work correctly for `currentCell`

Thank you!

**Comment by lprimak** [comment]
Hi, @jepsar I also made a screencast of the bug here:
https://youtu.be/40k3JGlkQRs

**Comment by lprimak** [comment]
Are you able to reproduce this? thank you!

**Comment by jepsar** [comment]
It's not on iPhone, but when you use touchUI="true" on the datePicker (which is implicit on iPhone / mobile)

@melloware any idea how this can affect the dataTable?

**Comment by lprimak** [comment]
yay! hope you found the screencast useful :)

**Comment by melloware** [comment]
i have an idea let me look.

**Comment by melloware** [comment]
I think the issue is in `datatable.js` which has special handling for Calendar/DatePicker and a few others when editing cells.  Something is clearly different when using TouchUI.

This is the code in `datatable.js`:
```js
// save/cancel on mouseup to queue the event request before whatever was clicked reacts
            $(document).off('mouseup.datatable-cell-blur' + this.id)
                        .on('mouseup.datatable-cell-blur' + this.id, function(e) {
                            // ignore if not editing
                            if(!$this.currentCell)
                                return;

                            var currentCell = $($this.currentCell);
                            var target = $(e.target);

                            // ignore clicks inside edited cell
                            if(currentCell.is(target) || currentCell.has(target).length)
                                return;

                            // ignore clicks inside input overlays like calendar popups etc
                            var ignoredOverlay = '.ui-input-overlay, .ui-editor-popup, #keypad-div, .ui-colorpicker-container';
                            // and menus - in case smth like menubutton is inside the table
                            ignoredOverlay += ', .ui-datepicker-buttonpane, .ui-menuitem, .ui-menuitem-link';
                            // and blockers
                            ignoredOverlay += ', .ui-blockui, .blockUI';
                            if(target.is(ignoredOverlay) || target.closest(ignoredOverlay).length)
                                return;

                            if($.datepicker && ($.datepicker._datepickerShowing || $('.p-datepicker-panel:visible').length))
                                return;

                            if($this.cfg.saveOnCellBlur)
                                $this.saveCell($this.currentCell);
                            else
                                $this.doCellEditCancelRequest($this.currentCell);
                        });
```

**Comment by melloware** [comment]
Or somehow this selector is not finding it when it Touch? `find('td:has(.ui-cell-editor-input:visible)')` ???

**Comment by lprimak** [comment]
hmmm... when using the workaround in the description the above JS (`find()`) works...

**Comment by melloware** [comment]
@lprimak which workaround?

**Comment by lprimak** [comment]
https://github.com/primefaces/primefaces/issues/9260#issue-1395808775
```
onchange="var birthdayTable = PF('birthdayTable');
                                              var currentCell = birthdayTable.jq.find('td:has(.ui-cell-editor-input:visible)');
                                              if (currentCell.length) birthdayTable.saveCell(currentCell)"
```

**Comment by melloware** [comment]
oh i see you are using the workaround.  It doesn't work out of the box so my thought is its related to the JS code I posted in the `datatable.js`

**Comment by lprimak** [comment]
Debugging JavaScript is not my forte :)

**Comment by melloware** [comment]
i will see if I can figure it out

**Comment by melloware** [comment]
@lprimak Here is my updated reproducer: 
[pf-9260.zip](https://github.com/primefaces/primefaces/files/9814681/pf-9260.zip)

It just works for me I removed your line `onchange="var bt = PF('birthdayTable'); bt.saveCell(bt.currentCell)"` you don't need that the CellEditor already does that.  SO what is happening is `saveCell` is being called twice once from the Datatable and then you call it again and its already null.

Not sure why you have that `onChange` to begin with?

**Comment by lprimak** [comment]
Ah, please look at the screencast (youtube link in the description).
Without the `onchange=` bit, The "default" behavior requires an additional click outside the date by the user.
to make the change "take" which is not the behavior I want.

**Comment by lprimak** [comment]
See my original question regarding this topic on discord: https://discord.com/channels/787967399105134612/787967662293909524/1025160751347941396

**Comment by melloware** [comment]
OK I got it working.  Just change this line...

```js
onchange="var bt = PF('birthdayTable'); if (bt.currentCell) bt.saveCell(bt.currentCell);"
```

`onChange` fires twice in TouchUI mode once that calls `SaveCell` and that nulls out `bt.currentCell` the second call is then NULL.

**Comment by lprimak** [comment]
thanks!
So now question becomes, is this a bug that the event is fired twice?
Or, if the argument is null, should `saveCell()` just do nothing?

**Comment by melloware** [comment]
i think there are two fixes.  One `saveCell` should gracefully ignore if you pass a NULL cell.  2) figure out why TouchUI DatePicker fires the change twice.

**Comment by lprimak** [comment]
ok, cool, then I'll leave this issue open.

**Comment by jepsar** [comment]
> i think there are two fixes. One `saveCell` should gracefully ignore if you pass a NULL cell. 2) figure out why TouchUI DatePicker fires the change twice.

It is called twice because of the onchange in the reproducer. The manual call passes null.

**Comment by lprimak** [comment]
I think I understand... in `touchUI="true"` case, the behavior is what I want (just one click to change the date),
without the `onchange=` line, however in the desktop case it isn't - requires two clicks

Am I understanding this correctly?

In that case, the fix is to simply ignore the null parameter in the `saveCell()` call and not have it fail

**Comment by lprimak** [comment]
> It is called twice because of the onchange in the reproducer. The manual call passes null.

Not sure I understand. When I remove the onchange line, the `touchUI` case still requires two clicks by the user to change the date

**Comment by melloware** [comment]
I have narrowed the bug down to this.  When it switched from regular to touchUI mode the click events get registered twice.

```js
updateResponsiveness: function() {
            if (this.options.autoDetectDisplay && this.options.responsiveBreakpoint && !this.options.inline) {
                var currentUI = this.options.touchUI;
                var newUi = PrimeFaces.env.mobile || PrimeFaces.env.isScreenSizeLessThan(this.options.responsiveBreakpoint);
                if (currentUI !== newUi) {
                    this.options.touchUI = newUi;
                    this._render();
                }
            }
        },
```

if I comment out this line they are only registered once but the wrong thing is happening.

```js
 this._render();
```

So even though I am calling `off` before rebinding events the delegated click is still being registered.

```js
 this.panel.off('click.datePicker-date', dateSelector).on('click.datePicker-date', dateSelector, null, function (event) {
```

**Comment by melloware** [comment]
I fixed the NULL check in `saveCell` but still haven't found a solution for the double mapping of `click` events.

**Comment by lprimak** [comment]
Any brainstorms on why there is double-mapping of click events?

**Comment by melloware** [comment]
I need to take another look with fresh eyes on this issue.

**Comment by lprimak** [comment]
Not a big deal, just wanted to ping :)

**Comment by lprimak** [comment]
That….is…awesome!
Thank you. 
I don’t even have to remove any workarounds
