### ISSUE TITLE
Simple FileUpload: selecting no file in chrome throws JS error

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9262]
https://forum.primefaces.org/viewtopic.php?f=3&t=76511

**Comment by melloware** [comment]
I reverted this line `if ($this.cfg.auto && files.length > 0) {` because its breaking Integration Tests

**Comment by tandraschko** [comment]
IMO integrationstests are wrong, not the code
already pinged @christophs78 to have a look

**Comment by melloware** [comment]
Cool!

**Comment by christophs78** [comment]
My current best bet point´s me to some issue with guard.

org.openqa.selenium.TimeoutException: Timeout while waiting for AJAX complete!
	at org.primefaces.selenium.internal.Guard.lambda$ajax$2(Guard.java:150)
	at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$mHJEqBNh.run(Unknown Source)
	at org.primefaces.selenium.component.FileUpload.setValue(FileUpload.java:89)
	at org.primefaces.integrationtests.fileupload.FileUpload003Test.testBasicAutoSingleUploadAllowTypes(FileUpload003Test.java:118)

https://github.com/primefaces/primefaces/blob/master/primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/FileUpload.java#L89

Can´t reproduce it local like Thomas. (Windows 11, tested with Chrome 106 and FF; with and without headless; Github Actions currently uses Chrome 105; but sound pretty minor)

**Comment by melloware** [comment]
OK I am going to reinstate the fix maybe we should just comment out the tests for now before 12 release?

**Comment by christophs78** [comment]
Opened a draft-PR to run our IT´s with some additional debug-output. Wait a bit and see.

**Comment by christophs78** [comment]
After a clean-install on my local machine it get´s evident what´s happening...
![image](https://user-images.githubusercontent.com/10461942/193936645-492e3865-57d4-44c6-8c99-c19b7450e869.png)

Our guard run´s into nowhere because no file get´s uploaded.

**Comment by melloware** [comment]
OK @christophs78 so what is the rememdy?

**Comment by christophs78** [comment]
Using assertThrows and expect org.openqa.selenium.TimeoutException for the affectes IT´s. (We expect this exception because there´s nothing to guard.) - I can look at this in the evening.
Doing it totally clean and only apply the guard when we realy expect a upload in a generic way seems to be more complicated.

**Comment by melloware** [comment]
Thank you!
