### ISSUE TITLE
ProgressBar: not yielding to poll for long running process

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#9272]
### Describe the bug

A page contains both a poll and progressBar. 
On page load, poll works as expected.
When a long server process is started, progress bar shows the progression, but the polling stops.

### Reproducer

https://github.com/mores/primefaces-test/tree/progressBarYield

### Expected behavior

I expect the polling to continue to poll while the progressBar is progressing.

### PrimeFaces edition

Elite

### PrimeFaces version

7.0.29

### JSF implementation

Mojarra

### JSF version

2.3.9

### Java version

1.8

**Comment by melloware** [comment]
I noticed you reported this on 7.0.29?  This is not an Elite tracker this is for community issues so unless its an issue on PrimeFaces 11 or 12 still it most likely will not be looked at by the community.

See: https://github.com/primefaces/primefaces#community--elite--pro

**Comment by mores** [comment]
This looks to be an issue on all versions, I tested with
7.0.29
8.0.21
10.0.16
12.0.0

**Comment by melloware** [comment]
Ok will check it.

**Comment by melloware** [comment]
OK not an issue.  I just fixed your example by adding `async="true"` to the poller and it works fine.

```xml
<p:poll interval="2" listener="#{PollView.increment}" update="txt_count" async="true"/>
```

The poller is intentionally blocking by default.
