### ISSUE TITLE
HorizontalBarChartModel: NullPointerException when calling getOptions

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primefaces#9274]
Starting with PrimeFaces 11, some use cases of `HorizontalBarChartModel` are broken. When calling `HorizontalBarChartModel.getOptions`, a `NullPointerException` is thrown instead of returning `null` as expected if there were no options set before. Also a constructor that takes `ChartData` and `BarChartOptions` is missing. This behaves differently from other `ChartModel` implementations, probably because it is the only derived chart model.

See https://github.com/primefaces/primefaces/blob/29bcad595a39164bffda039fb4b927004e031f29/primefaces/src/main/java/org/primefaces/model/charts/hbar/HorizontalBarChartModel.java#L43

**Comment by melloware** [comment]
@cnsgithub were you going to submit a PR?

**Comment by cnsgithub** [comment]
Oops, forgot to do that, here it is: https://github.com/primefaces/primefaces/pull/9275
