### ISSUE TITLE
FlowChart: add designer

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#9278]
### Description

Could we have an editable flowchart that can be used for designing workflows.

### Describe the solution you would like

If we can display pointers and just connect them as a flow with drag/drop.

**Comment by jepsar** [comment]
I'm not expecting the community to add this. I would contact PrimeTek and ask for a quote.

**Comment by melloware** [comment]
+1 to what @jepsar said.

**Comment by anuragnz** [comment]
Hello @melloware  , how do we get this as a new component?

**Comment by melloware** [comment]
@anuragnz you have a few choices.

1. Ask PrimeTek for a 1 time quote of what it will cost to build this component Go here https://www.primefaces.org/support/ and click on "Case get a quote".

2. Build the component yourself and donate it to the community for others to use.

3. Hope someone else in the community also has this need and decides to build and donate a component. (not likely)
