### ISSUE TITLE
Using datatable within ui:repeat breaks selection

### ISSUE THREAD

**Issue by shubforall** [primefaces/primefaces#929]
I am using DataTable inside ui:repeat. Datatable is with multiple selectionMode. The selection is not working and only the selection from last datatable is considered. 

The same issue is present if datatable is used inside p:rowExpansion or p:AccordianPanel (with model)

Version Tested: 5.2, 5.3
Forum discussion and proposed solution : http://forum.primefaces.org/viewtopic.php?f=3&t=36494&p=137360#p137360

**Comment by shubforall** [comment]
After debugging found out that the root cause is there is only one instance of DataTable. And Columns are not initialized again at the time of rendering. 

org.primefaces.component.datatable.DataTable.getColumns()

The column remains the same if the table is iterating at rendering time if within ui:repeat or any repeat model. 

This results in same columns. 

Wondering nobody noticed it. But its a very important to fix as many people needs DataTable p:columns inside ui:repeat.

**Comment by kukel** [comment]
Many people noticed, there are many similar posts and partial solutions... PrimeFaces does not really seem to recognize this as a usecase

**Comment by cagataycivici** [comment]
I'll review as soon as I can.

**Comment by shubforall** [comment]
Thanks @cagataycivici.

**Comment by kukel** [comment]
related to all the repeating issues like  https://github.com/primefaces/primefaces/issues/720? https://github.com/primefaces/primefaces/issues/523 but the other wat around, so more like the original https://github.com/primefaces/primefaces/issues/88? Is the fix from the latter still needed if switching to the new p:repeat fixes it?

**Comment by kukel** [comment]
There are already 6.0 RC's out... Has this been incorporated? If not, please change the milestone. RC's should not include major changes like this.

**Comment by cagataycivici** [comment]
Should be fixed via p:repeat.

**Comment by wsaca** [comment]
PF 6: datatable doesn't work inside an ui:repeat or p:repeat. When you use ajax is working, but if you try to process the form that is containing the datatable with a commandButton then the values are always set to null.

**Comment by fattanasio** [comment]
Hi,
I have same problem. I have a datatable with row expansion and into expansion there is a selectionable datatable with checkbox.
On all expansion there is a command button
Selection is always null.

How fix this ?
Thank you
![Senza titolo-1](https://user-images.githubusercontent.com/24672070/58479968-a6adef00-8159-11e9-9e42-ae1bbb935f11.jpg)

**Comment by melloware** [comment]
From PrimeTek: _"We cannot use such repeating components with *:repeat. This requires massive changes in components. That's why JSTL forEach is the ideal solution for this kind of work"_

The recommendation for `c:forEach` and the working example is attached here:
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/5391339/primefaces-test.zip)

```xml
<c:forEach var="par" items="#{testView.parents}">
   //datatable
</c:forEach>
```

```xml
<p:tabView>
   <c:forEach var="par" items="#{testView.parents}">
      <p:tab title="Parent - #{par.id}">
         //datatable
      </p:tab>
   </c:forEach>
</p:tabView>
```

**Comment by tandraschko** [comment]
hmpf
im not happy with this answer :D everything else works fine, so i think it should be possible to make it work in repeat actually

**Comment by melloware** [comment]
That's from PrimeTek through the PRO account. Basically saying don't do this.  So I am leaving my custom "hack" in my client's overridden DataTable for now.

**Comment by tandraschko** [comment]
can you do me favor and test the whole datatable, if all other features are working fine inside a repeat tag?

**Comment by melloware** [comment]
OK it does look like Sorting and Filtering is also broken.  If you sort table 1 then table 2 is also sorted.
