### ISSUE TITLE
Sticky: Overlapping due to changing z-index

### ISSUE THREAD

**Issue by l-uuz** [primefaces/primefaces#9295]
### Describe the bug

The z-index of elements made sticky with `p:sticky` changes when scrolling. As a result, sticky elements overlap modal dialogs and blockUI.

blockUI:
![grafik](https://user-images.githubusercontent.com/56924246/194822376-91270066-ad84-4874-8d93-a5b3b3d63260.png)

After scrolling down:
![grafik](https://user-images.githubusercontent.com/56924246/194822412-e6950170-e154-41e4-9f5c-d2f252109626.png)

The same applies to modal dialogs:
![grafik](https://user-images.githubusercontent.com/56924246/194822549-288cafdb-6e48-4e06-886b-fa334198b5e5.png)

### Reproducer

Reproducer: [primefaces-sticky-elements.zip](https://github.com/primefaces/primefaces/files/9744219/primefaces-sticky-elements.zip)

1. Go to http://localhost:8080/primefaces-test/
2. Click on "Block" or "Open Dialog"
3. Scroll down

### Expected behavior

The sticky toolbar should not overlap the background.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
Fixed reproducer: 
[pf-9295.zip](https://github.com/primefaces/primefaces/files/9792064/pf-9295.zip)

Here is a MonkeyPatch to fix the issue: 
```js
if (PrimeFaces.widget.Sticky) {
    PrimeFaces.widget.Sticky.prototype.fix = function(force) {
        if (!this.fixed || force) {
            var win = $(window),
                winScrollTop = win.scrollTop();

            // GitHub #9295 look for overlays and make sure sticky is not higher
            var overlays = $('.ui-widget-overlay');
            var zIndex = PrimeFaces.nextZindex();
            if (overlays.length) {
                overlays.each(function() {
                    var currentZIndex = $(this).zIndex() - 1;
                    zIndex = currentZIndex < zIndex ? currentZIndex : zIndex;
                });
            }

            this.target.css({
                    'position': 'fixed',
                    'top': this.cfg.margin + 'px',
                    'z-index': zIndex
                })
                .addClass('ui-shadow ui-sticky');

            this.ghost = $('<div class="ui-sticky-ghost"></div>').height(this.target.outerHeight()).insertBefore(this.target);
            this.target.width(this.ghost.outerWidth() - (this.target.outerWidth() - this.target.width()));
            this.fixed = true;
            win.scrollTop(winScrollTop);
        }
    };
}
```
