### ISSUE TITLE
Schedule: BackgroundColor is not being displayed

### ISSUE THREAD

**Issue by mores** [primefaces/primefaces#9297]
### Describe the bug

I create two different DefaultScheduleEvent, each one has a different BackgroundColor set.
When viewed in the browser, they have the same color.

### Reproducer

https://github.com/mores/primefaces-test/tree/eventColors

### Expected behavior

I expect the colors to be different....

Actual 
![image](https://user-images.githubusercontent.com/1318377/194938710-b599c26d-d0a1-46fc-83a1-7e6e5de3ac31.png)

Expected
![image](https://user-images.githubusercontent.com/1318377/194938776-ca83a1e8-c419-4ac3-9089-1267f82185db.png)

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

11.0.16.1

**Comment by mores** [comment]
This has also been an issue in 10.x and 11.x

**Comment by melloware** [comment]
@mores isn't this your issue: https://github.com/primefaces/primefaces/issues/8193

I think its a misunderstanding of "backgroundColor" means to FullCalendar.

**Comment by mores** [comment]
Fullcalendar documentation: https://fullcalendar.io/docs/event-parsing

![image](https://user-images.githubusercontent.com/1318377/194949785-70a3980f-ec74-48ff-9176-611c78da4970.png)

Their example:  week-numbers.html

![image](https://user-images.githubusercontent.com/1318377/194949900-8db304d8-15d9-4c07-a2df-2595aac8172a.png)
![image](https://user-images.githubusercontent.com/1318377/194949940-a12229f9-b867-4371-94e3-50f91fbb30e8.png)

Fullcalendar allows it.

**Comment by melloware** [comment]
Looks like we are setting it:

https://github.com/primefaces/primefaces/blob/6ec3c4a455e0d03d2e449bd36d5d4f185faf9817/primefaces/src/main/java/org/primefaces/component/schedule/ScheduleRenderer.java#L139-L141

**Comment by melloware** [comment]
And we are setting it inthe SHowcase example: https://www.primefaces.org/showcase/ui/data/schedule/basic.xhtml?jfwid=bec67

```java
 event = DefaultScheduleEvent.builder()
                .startDate(referenceDate.minusDays(6))
                .endDate(referenceDate.minusDays(3))
                .overlapAllowed(true)
                .editable(false)
                .resizable(false)
                .display(ScheduleDisplayMode.BACKGROUND)
                .backgroundColor("lightgreen")
                .build();
        eventModel.addEvent(event);
```

Which displays...

![image](https://user-images.githubusercontent.com/4399574/194952307-f43463b1-2a53-40cd-98b0-1eff3a9badf3.png)

**Comment by melloware** [comment]
There is also this ticket: https://github.com/fullcalendar/fullcalendar/issues/5533

**Comment by melloware** [comment]
OK got your example working:  
[pf-9297.zip](https://github.com/primefaces/primefaces/files/9749342/pf-9297.zip)

![image](https://user-images.githubusercontent.com/4399574/194954237-3242e8d7-1486-46fb-9cb2-e0d430e9956e.png)

```java
day.setDisplay( org.primefaces.model.ScheduleDisplayMode.BLOCK );
```

```css
body .fc .fc-event, body .fc .fc-event .fc-event-main {
  background: inherit;
}
```

**Comment by mores** [comment]
> Looks like we are setting it:
> 
> https://github.com/primefaces/primefaces/blob/6ec3c4a455e0d03d2e449bd36d5d4f185faf9817/primefaces/src/main/java/org/primefaces/component/schedule/ScheduleRenderer.java#L139-L141

It is being set, but then the value is getting overridden by fc-event-main

![image](https://user-images.githubusercontent.com/1318377/194954293-01ebacf9-408f-400d-be08-3398d9b86a78.png)

**Comment by melloware** [comment]
Yep see above

**Comment by melloware** [comment]
@mertsincan I think we need to update the themes to change `background` to `background-color` so the Schedule event coloring works without an override.

So this:
```css
body .fc .fc-event, body .fc .fc-event .fc-event-main {
  background: #0d89ec;
}
```

Should be:
```css
body .fc .fc-event, body .fc .fc-event .fc-event-main {
  background-color: #0d89ec;
}
```

**Comment by pfumi** [comment]
I think the correct solution in the theme stylings is to have it like this

```
body .fc .fc-event {
  background: <color>;
  border: <border>;
}
body .fc .fc-event .fc-event-main {
  color: <color>;
}
```

This is my event, 
```
DefaultScheduleEvent.builder()
	.title("Title")
	.startDate(LocalDateTime.of(LocalDate.now(), LocalTime.of(8, 0)))
	.endDate(LocalDateTime.of(LocalDate.now(), LocalTime.of(10, 30)))
    .backgroundColor("red")
    .textColor("darkblue")
    .borderColor("white")
    .build()
```

and the resulting HTML see here:

![image1](https://user-images.githubusercontent.com/6900303/197199450-c1021739-9026-4650-bb2a-17cbd5ce72b4.png)
![image2](https://user-images.githubusercontent.com/6900303/197199456-4441907d-eda1-43cc-88f6-e183038f6a1d.png)

Display:

![image3](https://user-images.githubusercontent.com/6900303/197200751-c1cef2f1-420c-460e-bf5d-2a0afe2fd638.png)
