### ISSUE TITLE
PrimeFaces Extensions Migration: Timer

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#93]
Could be useful to have a countdown component with client or server mode time, the component could show the remaining time or the time that has passed.

This component is very useful when you want to construct something like an online examen or survey that can have a timer for answer it.

The component could have a listener when the time is rise it.

Examples

http://codecanyon.net/item/jbmarket-circular-countdown/full_screen_preview/3100472

OR

http://codecanyon.net/item/jcountdown-mega-package/full_screen_preview/3443480

OR

http://codecanyon.net/item/count-it-round-standalone/full_screen_preview/4802487

Thanks. I hope this can be accepted.

@maxtorzito

**Comment by ova2** [comment]
I think we have this component in Extensions http://www.primefaces.org/showcase-ext/views/timer.jsf It has a listener, client API, can count down forward and backward, output format is customizable, etc.

**Comment by cagataycivici** [comment]
@ova2 So would you like to move it into core?

**Comment by ova2** [comment]
I'm not the author of this component and it doesn't matter for me where the component is. I doesn't use it. I will ping the author of this component, so that he can give a feedback.

**Comment by francesco-strazzullo** [comment]
Hi @cagataycivici! I'm the author of the countdown component. It's ok with me to move the component to the primefaces core. I can start working on a pull request during next week.

**Comment by cagataycivici** [comment]
Thanks, let me review it first and then we'll decide. It will be a good exercise to create it from scratch for interns as well.

**Comment by melloware** [comment]
@tandraschko The Extensions component only uses moment.js which PF already includes for p:schedule.  I think this component would be a useful addition to PF core without adding any additional JS libraries.  

I am willing to help in any way if you want help migrating this component to PF.

**Comment by tandraschko** [comment]
if the code is cleanuped and fine, i have no problem of adding it. Must just discuss this with Cagatay.
I just wonder if we can improve the UI? It's really basic.

**Comment by melloware** [comment]
I will take a shot at this.  Maybe @mertsincan and his UI team can help us make it pretty?   Right now it definitely respects the PF themes so that is good and is stylable with "ui-timer" class.  But you are right maybe we could make it look better.

**Comment by tandraschko** [comment]
Lets close it for now until someone provides a cool UI
