### ISSUE TITLE
SelectOneMenu: lack of validation on server side

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#9300]
### Describe the bug

SelectOneRenderer does not correctly validate user submitted value.
If e.g. the ajax request is tampered with a value which is not in the available select items, the invalid value is decoded and submitted anyway.

### Reproducer

To reproduce:

- create a simple page with a selectOneMenu and a commandButton
- click the button and submit the form
- use Firefox developer tools to copy the ajax request
- edit the request by changing the value, then submit the tampered request
- verify the submitted value

### PrimeFaces edition

Community

### PrimeFaces version

latest

### JSF implementation

Mojarra

### JSF version

3.0.2

### Java version

11

**Comment by NicolaIsotta** [comment]
I'm debugging right now. Seems like the problem lies here:
https://github.com/primefaces/primefaces/blob/75b0c093287b74c2ab5170b7afa4d8293b65c8df/primefaces/src/main/java/org/primefaces/renderkit/SelectOneRenderer.java#L50-L54
I think that, if validSubmittedValues is empty, no value should be submitted

**Comment by melloware** [comment]
Hmmm i feel like that might have addressed a previous issue.  If we fix we should definitely add an integration test.

**Comment by NicolaIsotta** [comment]
I actually found out this is not PrimeFaces' fault.
SelectOne* validation is delegated to jsf impl ( `UISelectOne.validateValue` )
Basically it works, but I found a corner case:

- p:selectOneMenu value is an integer
- there's a f:selectItem with itemValue="" (empty string) but without noSelectionOption="true"
- if the user tampers the request by setting the submitted value to 0, mojarra accepts it because it coerces the empty f:selectItem to 0

I'll try to test myFaces now, but I confirm that PrimeFaces behaves correctly.
