### ISSUE TITLE
BreadCrumb: Home icon not shown when using lastItemDisabled="true"

### ISSUE THREAD

**Issue by brivalin** [primefaces/primefaces#9302]
### Describe the bug

When using the breadcrumb configured with only lastItemDisabled="true" and one menuitem corresponding to the home link, the home icon is not shown.

### Reproducer

`<p:breadCrumb lastItemDisabled="true">
    <p:menuitem value="Home" />
 </p:breadCrumb>`

### Expected behavior

The home icon should be shown disabled, because it's the last item.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.0

### Theme

Saga

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

All

**Comment by brivalin** [comment]
Thank you for looking at the problem. 
Testing the fix in 13.0.0-SNAPSHOT it seems that it doesn't fix the initial problem that the icon doesn't appear in this case.

Could you have a look on this reproducer : 
[pf-9302.zip](https://github.com/primefaces/primefaces/files/9763333/pf-9302.zip)

You should see something like this : 
![breadcrumb_home](https://user-images.githubusercontent.com/26894018/195302365-4257dd1a-3ca1-4260-8c9d-89adff05ce8d.png)


I think the problem is on the HTML markup generated. 
A `<span>` markup is generated and no icon content is attached to it. In all other examples in the reproducer, a `<a>` markup is generated with icon content and specific CSS.

**Comment by melloware** [comment]
OK I got it this time if you want to retry.  Thanks for your reproducer.

**Comment by brivalin** [comment]
I tried it and it's works well. Thank you !
