### ISSUE TITLE
Component: DataExporter

### ISSUE THREAD

**Issue by aissous** [primefaces/primefaces#9305]
### Describe the bug

The DataTable header is no more exported using DataExporter. This issue is visible in showcase.

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by jepsar** [comment]
Please add a reproducer

**Comment by melloware** [comment]
@tandraschko that is why I pinned this issue: https://github.com/primefaces/primefaces/issues/9290

Others are going to be constantly re-reporting it for a while.
