### ISSUE TITLE
DataTable: filterFunction isn't working with global filter

### ISSUE THREAD

**Issue by jabrware** [primefaces/primefaces#932]
global Filter algorithm should takes into account the filterFunction attribute.

**Comment by jepsar** [comment]
Is this issue (still) valid? I had a look at the [filter code](https://github.com/primefaces/primefaces/blob/821f990b49b09022fd2fa9b38962f8c611bc742c/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java#L186) when fixing #4513 and it was looking good to me. I think I've even tested this issue's scenario, but I can double check that tonight.

**Comment by melloware** [comment]
I agree. @tandraschko I think this one is safe to close as fixed.
