### ISSUE TITLE
Exporter: Do not require POI OOXML

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#9321]
### Describe the bug

Since PF 12.0.0 poi-ooxml dependency is always required for simple xls export. Before https://github.com/primefaces/primefaces/pull/8971 only poi dependency was required.

The problem is that ExcelStylesManager (used in both DataTableExcelExporter and DataTableExcelXExporter) imports classes from that library, even if they are not used

### Reproducer

The same exporter showcase, but exclude poi-ooxml dependency ( https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml?jfwid=d9a80 )

### Expected behavior

poi-ooxml should not be required for simple xls export

### PrimeFaces version

12.0.0

### JSF implementation

MyFaces

### JSF version

2.3-NEXT-M6

### Java version

18.0.2

**Comment by cocorossello** [comment]
I have made a PR with a possible working solution

**Comment by melloware** [comment]
I see your PR but let me try something first...
