### ISSUE TITLE
inputMask: doesn't work if created programmatically

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#9329]
### Describe the bug

I have an application that's built on **primefaces 12** to generate dynamic pages based on backend database, and I create InputMask as follows :

```
 Application application = FacesContext.getCurrentInstance().getApplication();
    InputMask inputNumber = (InputMask) application.createComponent(InputMask.COMPONENT_TYPE);
    inputNumber.setMask("999999999999999"); 
    inputNumber.setSlotChar("");
    inputNumber.setAutoClear(false);
    inputNumber.setValidateMask(false);
    inputNumber.setId(property.getSymbolicName());
    inputNumber.setMaxlength(15);
    myPanelGrid().getChildren().add(inputNumber);
```

Issue : the mask doesn't work in my xhtml page and I get error in console :

> Widget class 'InputMask' not found!

So I tried manually to import the inputMask script as follows :

```
<h:outputScript library="primefaces" name="inputmask/inputmask.js" target="head" />
    <h:outputScript library="primefaces" name="validation/validation.js" target="head" />
```

But it didn't work also
The only working workaround was to manually add in page a hidden inputMask component as follows :
```
<p:inputMask style="display:none"/>
````

Question : How to make the inputMask works fine without this workaround ?

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3.9

### Java version

1.8

**Comment by jepsar** [comment]
Please provide a reproducer https://github.com/primefaces/primefaces-test

**Comment by Rapster** [comment]
If you're open to an alternative, you might be also interested in this: https://www.primefaces.org/showcase-ext/sections/dynaform/basicUsage.jsf

**Comment by melloware** [comment]
Weird the component has these dependencies declared which look right to me:

```java
@ResourceDependency(library = "primefaces", name = "components.css")
@ResourceDependency(library = "primefaces", name = "jquery/jquery.js")
@ResourceDependency(library = "primefaces", name = "core.js")
@ResourceDependency(library = "primefaces", name = "components.js")
@ResourceDependency(library = "primefaces", name = "inputmask/inputmask.js")
public class InputMask extends InputMaskBase {
```

**Comment by melloware** [comment]
Works just fine: 
[pf-9329.zip](https://github.com/primefaces/primefaces/files/9820507/pf-9329.zip)

Unzip and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

**Comment by jepsar** [comment]
That's why I've asked for a reproducer. I was expecting problems elsewhere.

**Comment by jepsar** [comment]
@melloware FYI you can also close issues as "Not planned" by using the arrow at the close button. Not sure how new this is in GitHub.

**Comment by melloware** [comment]
Hey i noticed your do that where is the "not planned" button?

**Comment by jepsar** [comment]
> Hey i noticed your do that where is the "not planned" button?

Just did an edit to clarify. There is an dropdown arrow at the close button. This will give cleaner change logs.

**Comment by melloware** [comment]
Nevermind I see it now: 
![image](https://user-images.githubusercontent.com/4399574/196702728-ae85b79b-20b5-43a4-8f4f-78bfff539e6f.png)
