### ISSUE TITLE
UIColumn: remove filterOptions

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#9331]
### Description

You can do the same using dynamic filters introduced in https://github.com/primefaces/primefaces/issues/7469

### Describe the solution you would like

Delete it

### Additional context

I realized that filterOptions was used to cover this point, see doc:

> If you’d like to use a dropdown instead of an input field to only allow
predefined filter values use _filterOptions_ attribute and a collection/array of selectitems as value.

But you can achieve the same by using facet filter no? Am I missing something?

**Comment by melloware** [comment]
True not sure how popular the filterOptions method is I know I have used it in the past for simple lists.

**Comment by Rapster** [comment]
Yeah, I feel the same way about his popularity... I think we can make it clear that input is the default filter, and if user want something else then use facet filter, simple as that (I honestly think that's what users already do, and are probably not aware of that option)

**Comment by melloware** [comment]
Yep and as long as we provide an example usage in the docs or the showcase probably already does this feels safe to do.

**Comment by Rapster** [comment]
I'll make a PR, and let me know what you think

**Comment by ikitzmann** [comment]
@melloware @tandraschko 
Is there an easier way of migration (PF12->PF13) than adding more than 100 times a facet filter to all of our xhtml files? We used filterOptions on most of our tables because for simple filters the facet was unneeded boilerplate code.

**Comment by melloware** [comment]
Unfortunately no. My company went through the same thing.
