### ISSUE TITLE
SelectOneMenu with dynamic=true load lazily the items to optimize the performance

### ISSUE THREAD

**Issue by X452-625** [primefaces/primefaces#9337]
Hello,
Here is the code example : 
`<p:selectOneMenu value="#{form.selectedItem}" dynamic="true">
        <f:selectItem itemValue="" itemLabel="Select one" />
        <f:selectItems value="#{form.items}" />
      </p:selectOneMenu>`

The SelectOneMenu offers the option "dynamic" to render lazily the overlay but it still calls the getter of `form.items` and even more times if I use a converter when loading even if it's not show.
I want to ask if it's possible to not call the getter for `f:selectItems` and only use the first item when loading ? 
Very often, the menu only use the first option so it can help to optimize the performance a lot if it does not try to get all the items when not needed on server side. 

Thank you

**Comment by melloware** [comment]
`dynamic="true"` doesn't mean the `form.items` won't be called it just means the DOM won't contain the overlay until you click on it.  So it doesn't bloat the HTML.

Also you should expect `form.items` to be called multiple times that is how JSF works....never put business logic in your `getters`.  See this under "Performance tips": https://primefaces.github.io/primefaces/12_0_0/#/core/performance?id=patterns

**Comment by melloware** [comment]
It sounds like what you really want is AutoComplete with the REST Service example for truly lazy selection: https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

**Comment by X452-625** [comment]
The thing is that in order to load the list of items, it takes a lot of time, and when I have multiple selectOneMenu in the same page, it takes a lot of times to load even though I don't use these menus yet. 
As for AutoComplete, the visual is not exactly what I need, I'll look more into it, it might work.
 
Thanks a lot.

**Comment by melloware** [comment]
Yeah I definitely see the issue.  Even though the code with `dynamic=true` in the renderer its loading the items to make a bunch of decisions.  It would take significant refactoring to make this not check the SelectItems before rendering the component:

https://github.com/primefaces/primefaces/blob/d450cb7f12fe92cb3912ee9b678945bc540a7e46/primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L113

**Comment by X452-625** [comment]
I'm testing with AutoComplete, it seems quite promising. 
I just have a bit of blockage with the width of the input. 

With SelectOneMenu, the width can auto adjust if I select an item with a label longer than the initial size of the menu. 
However, the AutoComplete doesn't change its width at all. Do you have any idea how to ? 

Thanks

**Comment by melloware** [comment]
there is no autosizing of the AutoComplete. I suggest you use `ui-fluid` style class similar to how the Showcase does it: https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

**Comment by X452-625** [comment]
I think I can make it work with AutoComplete however as for the lazy loading of SelectOneMenu, do you think if it's possible to make it happen ? Should I create a ticket or something?

In another approach as work around for lazy loading with SelectOneMenu, I tried to initialize the items list in `onchange="#{page.initItems()}"` but strangely, this method is always called once when loading the menu even though I haven't clicked on it yet. Do you knnow if it's normal? Should I create a bug ticket for that? 

Thanks a lot

**Comment by melloware** [comment]
This ticket I have left open for lazy loading.  As for the onchange I think it's a client side JS call.  It should get called whenever the select one is set to a value so are you setting the value in the component?

**Comment by melloware** [comment]
Also how many items are in your dropdown that you need this kind of performance?? A dropdown should have less than 50 items else it's not the right UX component thus the autocomplete is a better choice which has true lazy loading.

**Comment by X452-625** [comment]
I just added the option onchange to the code example before actually, I leave the default value to the first element and nothing else but it still call for the method in `onchange` when loading (same issue with `onkeydown`)
```
<p:selectOneMenu value="#{form.selectedItem}" dynamic="true" onchange="#{page.initItems()}">
    <f:selectItem itemValue="" itemLabel="Select one" /> 
    <f:selectItems value="#{form.items}" /> 
</p:selectOneMenu>
```

The issue I have with my page is not that I have too many items in the list but I need to put many filters (dropdown) and the loadingof all these differents items from database and processing them are a bit complexe and time consuming. Thus it slows down the loading time of the page. 
I'm looking more into the autocomplete and its options, it's a very good choice, I'm checking to see if the visual change can be acceptable in my project, also it doesn't seems to be able to select the first item by default like SelectOneMenu
Many thanks

**Comment by melloware** [comment]
As discussed in this ticket it's working by design and if performance is a concern the SelectOne should not be used but an AutoComplete should.
