### ISSUE TITLE
Filtering mode of SelectOneMenu doesn't react on uppercase characters

### ISSUE THREAD

**Issue by rdebusscher** [primefaces/primefaces#934]
This is what we use in our page 

&lt;p:selectOneMenu filter="true" filterMatchMode="contains" .. /&gt;

When we type a character in the filter box, the select items are filtered correctly, even case insensitive.  But when we use uppercase characters, nothing happen.

I suspect the meta-key (Shift) inhibits the JavaScript event processing.

Verified on Chrome and FireFox on Mac.

Any reason why this is not working because a lot of end users tries the filter with uppercases. (even when it is documented in the tutorial not to do :) )

**Comment by rdebusscher** [comment]
See
META-INF/resources/primefaces/forms/forms.js:905

# 

```
                var metaKey = e.metaKey||e.ctrlKey;

                if(!metaKey) {
                    $this.filter($(this).val());
                }
```

#

**Comment by rdebusscher** [comment]
Anyway, with PF 5.3 this behaviour is corrected.

**Comment by aysegulP** [comment]
I upgreade 5.3. But the result is same. How can you resolve it with 5.3?

**Comment by rdebusscher** [comment]
You don't have to do anything, just use the new PF dependency.

Any chance that you have a cache of the old code in your browser?

**Comment by aysegulP** [comment]
Actually my string is "TIRSAN".It is turkish word.
When I search with **lowercase ı** no result. **Lowercase ı** is turkish character.
But it works with **lowercase i**

**Comment by rdebusscher** [comment]
Best is that you open a new issue for the _special_ characters.

Maybe there is an issue with them?

**Comment by aysegulP** [comment]
Ok. Thank you for your attention
