### ISSUE TITLE
AjaxStatus: Start-Facade is displayed after all ajax request are finished

### ISSUE THREAD

**Issue by deichhuhn** [primefaces/primefaces#9351]
### Describe the bug

The "start"-facet of the ajaxStatus is still displayed even after all global ajax requests are finished. This error only happens when there is a delay configured in the ajaxStatus and multiple ajax-calls are chained (through oncomplete-listeners pointing to a remoteCommand).

Maybe the error is in FileUpload-Component because this component calls the "oncomplete"-listener before the "pfAjaxComplete"-event is issued. This is the reason why ajaxStatus creates a new timeout without stopping the old timeout and therefore the reference to the old timeout is lost.

### Reproducer

1. Start attached demo
2. Open http://localhost:8080/primefaces-test/
3. Upload any file(s)
4. After upload of files(s) you can see the text 'Active ajax request' which is part of the "start"-facet of the ajaxStatus and therefore should not be visible

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/9879938/primefaces-test.zip)

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.7

### Theme

-

### JSF implementation

All

### JSF version

2.3.18

### Java version

11.0.7

### Browser(s)

Firefox

**Comment by melloware** [comment]
Thanks for the excellent reproducer!

I am going to fix it but an easy workaround right now is this: 
```js
oncomplete="$(document).trigger('pfAjaxComplete');postProcess()"
```
