### ISSUE TITLE
commandButton: Issues with partialSubmit and actionListener

### ISSUE THREAD

**Issue by ybendek** [primefaces/primefaces#9366]
### Describe the bug

I'm in the middle of an upgrade for our application developed some years ago with Primefaces 6.2, and changing all the infrastructure to support now Primefaces 11.

However in this migration I found a weird behaviour that it works before without issues with our old components, but now with Primefaces 11 and upgrade in our infrastructure is not working.

The following it's a simple example to use partialSubmit with a commandButton component

`<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            
        </h:head>
        <h:body >
            <h:form id="testForm">
                <p:log />
                <p:commandButton value="Test Button" 
                                 partialSubmit="true" 
                                 process="panelData" 
                                 actionListener="#{testMngBean.saveAction}"/>

                <p:panelGrid id="panelData" columns="2" 
                             columnClasses="ui-grid-col-3,ui-grid-col-9" 
                             layout="grid" >
                    <p:outputLabel value="Field 1" for="inField1"/>  
                    <p:inputText id="inField1" value="#{testMngBean.field1}" maxlength="100"/>
                </p:panelGrid>
            </h:form>
        </h:body>
    </f:view>
</html>`

And here is the backing bean

`import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;

@Named
@SessionScoped
public class TestMngBean implements Serializable {

    private static final Logger log = Logger.getLogger(TestMngBean.class.getName());

    private String field1;

    public TestMngBean() {
    }

    public String getField1() {
        return field1;
    }

    public void setField1(String field1) {
        this.field1 = field1;
    }

    public void saveAction() {
        log.log(Level.INFO, "Data stored");
    }

}`

### Reproducer

This is a reproducer I made with Apache Netbeans IDE 13.

To execute this example I'm using Payara Server 5.2022.3, as soon is launched you will see the only page included with the code described before.

1) Fill the input field
2) Click the button "Test Button"
3) The method in the backing bean named "saveAction" is never called

[reproducerIssue.zip](https://github.com/primefaces/primefaces/files/9906736/reproducerIssue.zip)

### Expected behavior

The method "saveAction" referenced in the backing bean should it be called.

In the same code if you change the line

`process="panelData" `
to for example
`process="testForm" `

The method is successfully called. However the expected behavior is that the method linked with the "actionListener" should it be called in both cases, even if a specific component like a panelGrid is listed in the "process" attribute.

 

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.9

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

JDK 11 - AWS Correto

**Comment by melloware** [comment]
Change your button to `process="@this panelData"` and it all works.  The Button itself `@this` needs to be processed or else it won't run the ActionListener.

**Comment by melloware** [comment]
I don't see it anywhere in the release notes but you are saying it worked before on 6.2 i think because CommandButton was adding `@this` implicitly.

**Comment by ybendek** [comment]
Yes, now it works. makes complete sense, especially if the button is outside the container I want to process.

And yes, it works before with PF 6.2, I try to find anything related in the releases notes between 6.2 and 11 with no luck, that's why I decide to create this issue :) 

Thank you for the clarification.
