### ISSUE TITLE
CSP: Inline event handlers are not triggered

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#9368]
### Describe the bug

With CSP enabled. In same request, components that are updated and their inline event handlers triggered via `PrimeFaces.current( ).executeScript("$('selector').click()")` will not be able to be executed.
In the eval section of the partial response, scripts added for execution in invoke application phase will come before scripts added by CSP in render response phase, but I expect that CSP generated script to come before, not after. This sequence: `update(events removed) -> trigger events-> events added` is wrongly generated.

The same list is used by [executeScript](https://github.com/primefaces/primefaces/blob/2b1384a3c6464c995e029757eeebd8cb6144f4d9/primefaces/src/main/java/org/primefaces/PrimeFaces.java#L133) and by [writeJavascriptHandlers](https://github.com/primefaces/primefaces/blob/2b1384a3c6464c995e029757eeebd8cb6144f4d9/primefaces/src/main/java/org/primefaces/csp/CspPartialResponseWriter.java#L199).

### Reproducer

```
<p:commandLink id="cl" value="link" onclick="alert()">
<p:commandButton value="press me" action="#{mb.press}" update="cl" />
```
```
public void press( )
{
    PrimeFaces.current( ).executeScript( "$('#cl').click()" );
}
```

### Expected behavior

Re-add events in the update section or reorder the eval section so as the CSP generated scripts came first. To have events attached before triggering them.

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

1.8

**Comment by melloware** [comment]
Confirmed with reproducer: 
[pf-9368.zip](https://github.com/primefaces/primefaces/files/9910357/pf-9368.zip)


```xml
<eval><![CDATA[if(window.PrimeFaces){PrimeFaces.csp.init('OTk5ZTYwMzMtOGIzYi00Njg1LThiOGMtMmUyNmZlY2QxZWMz');};;
$('#cl').click();
PrimeFaces.csp.register('cl','onclick',function(event){alert(); return false;;PrimeFaces.ab({s:"cl"});return false;});;]]>
</eval>
```
