### ISSUE TITLE
GraphicImage: ismap attribute not working as expected

### ISSUE THREAD

**Issue by mafaul** [primefaces/primefaces#9369]
### Describe the bug

Primefaces renders ismap="false" attribute on img tags, instead, it should not be rendered at all.

According to javax.faces.component.html.HtmlGraphicImage -> isIsmap():
> A value of false causes no attribute to be rendered, while a value of true causes the attribute to be rendered as ismap="ismap".

Issue was first introduced by https://github.com/primefaces/primefaces/pull/8772.

### Reproducer

`<h:form>
            <h:outputLink value="https://google.com" target="_blank">
                <p:graphicImage url="https://www.farmersalmanac.com/wp-content/uploads/2021/04/forget-me-not-flower-as309740666.jpeg" />
            </h:outputLink>
        </h:form>`

### Expected behavior

When clicking the image, I expect to be navigated to https://google.com.
Instead, I am being navigated to https://www.google.com/?322,465=

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by mafaul** [comment]
This bug causes the browser to just add the coordinates that were clicked on to the URL. 
If there are f:param elements too, it messes them up.
For example: https://www.google.com/search?q=Primefaces?315,338=
Instead of https://www.google.com/search?q=Primefaces

**Comment by melloware** [comment]
Confirmed.  Submitted a fix now letting integration tests run
