### ISSUE TITLE
Scrollable DataTable duplicates header elements' id's and names

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#937]
PrimeFaces 5.3.

Scrollable DataTable clones its head. This leads to issues.
1. Cloned header elements have duplicate id's.
2. Cloned header inputs have duplicate names, so their empty values get submitted as well, along with the original inputs' values. This seems not to be a problem in practice with single valued components such as p:inputText, at least with Mojarra 2.2.8, which uses the first submitted value if there are multiple. But this is a problem with multiple valued components, such as p:selectCheckboxMenu.

```
<h:form id="zorm">
    <p:dataTable id="zable" value="#{[1,2]}" var="row" scrollable="true">
        <p:column>
            <f:facet name="header">
                <p:inputText id="zinput" value="#{dataTableBean.value}" />
            </f:facet>

            row #{row}
        </p:column>
    </p:dataTable>
    <p:commandButton value="submit" process="@form" />
</h:form>
```

Observe id and name "zorm:zable:zinput" appear twice in the DOM.

**Comment by melloware** [comment]
This was fixed in 6.2.18 and 7.0 with this ticket: https://github.com/primefaces/primefaces/issues/4624

It now added "_clone" to each id.
