### ISSUE TITLE
CSP: Dialog return ajax behavior event is not executed in the root window context

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#9377]
### Describe the bug

With CSP enabled. Have widgets defined in root window, lookup them within onstart attribute of a dialogReturn ajax behavior event. The referenced widgets are not found because they are looked up in the dialog iframe window.
`$.globalEval` is used instead of `rootWindow.$.globalEval`.

### Reproducer

```
<p:button value="Primary" widgetVar="btn" />
<p:commandLink value="Open dialog" action="#{mb.openDialog}">
    <p:ajax event="dialogReturn" onstart="PF('btn').click()" />
</p:commandLink>
```

### Expected behavior

Same as without CSP enabled.
Pass and use windowContext at [closeDialog](https://github.com/primefaces/primefaces/blob/a5918b6e7f39af25d085ff33b458b12911840ebb/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.dialog.js#L363).

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

1.8

**Comment by melloware** [comment]
Have you tried this?  $.globalEval is a Jquery function it doesn't allow you to call it within a context?  https://api.jquery.com/jquery.globaleval/

**Comment by melloware** [comment]
Can you review my PR please?

**Comment by mihaiDumea** [comment]
See the comment on the commit. `evalResult` needs to be changed also.

**Comment by mihaiDumea** [comment]
sry

**Comment by mihaiDumea** [comment]
See the comment on the commit. evalResult needs to be changed also.

**Comment by melloware** [comment]
I will take a look

**Comment by melloware** [comment]
OK updated my PR please have a look now.

**Comment by melloware** [comment]
OK PR updated again. I chose to always use the rootWindow when in dialog.js

**Comment by mihaiDumea** [comment]
All good now
