### ISSUE TITLE
ImageCropper is rendered as a static image in Google Chrome

### ISSUE THREAD

**Issue by hfluz** [primefaces/primefaces#938]
I found a intermitent bug that happens to ImageCropper in Google Chrome.
Sometimes the image cropper is not loaded (just a static image is rendered).
I spent a few days trying to track the issue, but I wasn't able to.

My solution was to override the encodeScript method of ImageCropperRenderer, but I guess someone should look into it.

I have more details in this [post](http://hfluz-jr.blogspot.com.br/2015/12/primefaces-imagecropper-is-rendered-as.html) of my blog.

**Comment by tandraschko** [comment]
Sorry but can't replicate and your blog post doesn't help currently.
If you have a sample, please come back.
