### ISSUE TITLE
SplitButton: Style being applied to default button instead of parent div

### ISSUE THREAD

**Issue by newk5** [primefaces/primefaces#9381]
### Describe the bug

If you apply a css style to a p:splitButton, its styling is being applied to the the splitbutton default button instead of only the div that wraps it. This is a problem in some cases, for example if you apply a margin-right that will break the presentation of the splitbutton since it will create a distance betweent he default button and the second button: 

![image](https://user-images.githubusercontent.com/32560510/200153326-a0102907-bead-42e6-901d-1280cdf77f72.png)

### Reproducer

Just open the test.xhtml page and you'll see the same as the screenshot above
[primefaces_test.7z](https://github.com/primefaces/primefaces/files/9945121/primefaces_test.zip)

### Expected behavior

The styling should only apply to the div that is wrapping the whole p:splitButton component so as to not break the splitButton presentation

Adding:
```java
writer.writeAttribute("style", "","style");
```
To:  https://github.com/primefaces/primefaces/blob/d5873d9dd69dc459712f3e354ddbe167293e4608/primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java#L125

Fixes it. Whether that should be the solution to apply or not is up for debate.

### PrimeFaces edition

Community

### PrimeFaces version

12

### Theme

All

### JSF implementation

All

### JSF version

Any

### Java version

Any

### Browser(s)

Any

**Comment by melloware** [comment]
I chose a slightly different way to fix it.
