### ISSUE TITLE
CommandLink: Invalid HTML when disabled

### ISSUE THREAD

**Issue by Bukama** [primefaces/primefaces#9384]
### Describe the bug

Since Primefaces 12 (Issue: #8218 / PR: #8219) disabled [CommandLinks](https://www.primefaces.org/showcase/ui/button/commandLink.xhtml?jfwid=d4529) are rendered with invalid HTML, because an attribute `disabled=true` is renderend. But this in not allowed on anker-tag (`<a>`).

> Attribute disabled not allowed on element a at this point.
> r Post</a><a id="j_idt343:disabled" href="#" class="ui-commandlink ui-widget ui-state-disabled" tabindex="-1" …meFaces.ab({s:&quot;j_idt343:disabled&quot;,f:&quot;j_idt343&quot;});return false;" disabled="true">Disab

![pf_commandlink](https://user-images.githubusercontent.com/4354359/200528420-5ffde1b3-4240-4994-a9fb-6f5e474c98c3.PNG)

### Reproducer

See showcase

### Expected behavior

Valid HTML is rendered.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.2

### Java version

1.8

**Comment by melloware** [comment]
I think I already fixed this but will confirm

**Comment by melloware** [comment]
I am pretty sure I fixed this with this PR: https://github.com/primefaces/primefaces/pull/9374

**Comment by jepsar** [comment]
I don't think so. There is no such attribute. And it seems that CSS is required.

https://stackoverflow.com/questions/10276133/how-to-disable-html-links

I'll have a look at it this evening (CET).

**Comment by melloware** [comment]
Oh its saying disabled is not allowed at all on the element.  My fix makes it render as `disabled="disabled"` like other components.

**Comment by melloware** [comment]
OK maybe similar to this fix I made where you have to exclude certain props before passing the list: https://github.com/primefaces/primefaces/pull/9382

**Comment by jepsar** [comment]
@Bukama what's your take on https://github.com/primefaces/primefaces/pull/9388#pullrequestreview-1172752853 ?

**Comment by Bukama** [comment]
> @Bukama what's your take on [#9388 (review)](https://github.com/primefaces/primefaces/pull/9388#pullrequestreview-1172752853) ?

Sorry was very busy the last days. Just did my review.
