### ISSUE TITLE
DatePicker: change event not triggered when [Enter] is used with `mask`

### ISSUE THREAD

**Issue by PaulWasilewski** [primefaces/primefaces#9389]
### Describe the bug

When the user press Enter in a `<p:datePicker>` component the `valueChange / change event `is not fired (works for tab, mouse click). Works with other input fields like `<p:input>`. 

### Expected behavior

valueChange event is fired when user is pressing Enter and value changed

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

jdk8

**Comment by melloware** [comment]
Can you provide a PrimeFaces Test reproducer?  I am hitting ENTER key and its firing the `change` event.

```xml
<p:datePicker id="basic" value="#{calendarView.date}">
	<p:ajax event="change" update="msgs"/>
</p:datePicker>
```

IF I edit the date "11/08/2022" and hit ENTER the change event is fired.

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by PaulWasilewski** [comment]
Hi Thanks for the quick response.

It seems to be related to the combination of mask and time. For me it works removing the mask feature.  

But I don't have time to provide a running example within the test project. Here is a simple reproducer I used for finding a solution. 

However, thanks for the support and great work. 

```
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<f:view>
	<h:head id="head">
		<script>
		//<![CDATA[
		$(function() {
		$('#form').keydown(function(e) {
			if (e.keyCode == 13) {
				var inputs = $("#form").find("input")
				var index = inputs.index(e.target);			
				if (inputs[index + 1] != null) {
					inputs[index + 1].focus();
				}
				e.preventDefault();
				return false;
			}
		});
		})
	   	//]]>
		</script>
	</h:head>
	<h:body>
		<h:form id="form" autocomplete="off" style="height:100%;"
			onsubmit="if (event.keyCode == 13) { return false; }">
			<p:datePicker value="22-01-30 22:22" pattern="yy-MM-dd"
				showTime="true" mask="99-99-99 99:99" maskSlotChar="_"
				maskAutoClear="true">
				<p:ajax event="valueChange"
					onstart="console.log('NO CHANGE EVENT ON ENTER/BLUR :()')"
					partialSubmit="true" />
			</p:datePicker>
			<p:datePicker value="22-01-30 22:22" pattern="yy-MM-dd"
				showTime="true">
				<p:ajax event="valueChange"
					onstart="console.log('CHANGE EVENT ON ENTER/BLUR :)')"
					partialSubmit="true" />
			</p:datePicker>
			<p:inputText />
		</h:form>
	</h:body>
</f:view>
</h:html> 
```

**Comment by melloware** [comment]
Related to: https://github.com/primefaces/primefaces/issues/9259

Its all Mask related as the InputMask registers its own events that intercept the DatePicker events

**Comment by melloware** [comment]
Reported: https://github.com/RobinHerbots/Inputmask/issues/2672

**Comment by majkers** [comment]
I think label 12.0.7 is incorrect because I dont see this change in 12.0.7 sources....
