### ISSUE TITLE
Spotlight: z-index problem with growl

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#9391]
### Describe the bug

![Schermata del 2022-11-09 11-05-39](https://user-images.githubusercontent.com/17908214/200802132-0cbcb8ed-ff40-46ee-a60f-874d189ab0d1.png)

### Reproducer

https://www.primefaces.org/showcase/ui/misc/spotlight.xhtml?jfwid=d45d6

Click Save button

### PrimeFaces version

12 showcase

### JSF implementation

All

### JSF version

n/a

### Java version

n/a

### Browser(s)

Chrome 107 | FF 106

**Comment by jepsar** [comment]
Seems that the z-index is calculated. Order might be wrong. I would need to look into it further.

**Comment by jepsar** [comment]
Also, one could debate whether this is a bug or not..

**Comment by pizzi80** [comment]
> Also, one could debate whether this is a bug or not..

Yes, it's a strange situation... it's questionable which is more important, the growl(s) or the spotlight ...

**Comment by melloware** [comment]
To me the Spotlight is the most important thus its called "Spotlight" :)  I think this was all intentional.

**Comment by melloware** [comment]
I think i will close this as as designed.  @pizzi80 you might be able to monkeypatch the Growl code to do something different for your specific use case.
