### ISSUE TITLE
Resizing issue with Dialog Positioning

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#94]
- Using PF 4.0.10
- At the bottom of a very long page add a button that open a dialog.
- Click button. Dialog will open.
- Resize dialog, dialog will disappear.

In fact, the dialog does not disappear, it change the coordinates with strange "top" value (like -2224 for example). 

I can even reproduce it in Showcase by changing a component height before button that open dialog. You have to scoll to reach the button to reproduce the problem.

**Comment by arend-von-reinersdorff** [comment]
I just tested the problem in my project again:
- The problem appears with Primefaces 5.0
- The problem no longer appears with Primefaces 5.1 and 5.2

Also, I cannot reproduce it in the current showcase anymore.

Looks like the problem is fixed?

**Comment by tandraschko** [comment]
Not replicateable anymore: #2369
