### ISSUE TITLE
Button: Button href atribute rendering  can be wrong when generate  window.open 

### ISSUE THREAD

**Issue by salviof** [primefaces/primefaces#9401]
### Describe the bug

When set href on button component like: <p:button href="http://primefaces.com/teste">  they render this:
...
onclick="window.open('http:\\/\\/primefaces.com\\/test','_parent')"
..
Thats not a problem in modern browser because they can handle it, but in a webview on a a flutter app, thats return a http error code -6
Maybe EscapeUtils.forJavaScript can be removed when targetURL != null
thanks

### PrimeFaces version

12.0.1

### Theme

saga

### JSF implementation

Mojarra

### JSF version

2.4.8.Final

### Java version

1.8

### Browser(s)

webview on flutter

**Comment by melloware** [comment]
This is interesting let me look into it.

**Comment by salviof** [comment]
ok, you can close this insue, this is not the reason for the problem, my problem is linked to p:photoCam component permissions, with the flutter system, sorry, thanks for response.
