### ISSUE TITLE
TriStateCheckbox: Item label not aligned with checkbox

### ISSUE THREAD

**Issue by hfluz** [primefaces/primefaces#9412]
### Describe the bug

The item label is not aligned with the checkbox.

It was correct on Primefaces 8 (tested on older version of primefaces-test), but it isn't from Primefaces 10 to 12 (latest primefaces-test). It's just 1 line to reproduce, so I didn't upload the reproducer, but I can if needed.

How it's displayed:

![image](https://user-images.githubusercontent.com/832674/202267618-d40c1f27-8313-4a49-af2b-ebf06588a4ed.png)

### Reproducer

Code: 
`<p:triStateCheckbox itemLabel="Year"/>`

### Expected behavior

![image](https://user-images.githubusercontent.com/832674/202267946-5231510d-2326-4ff2-ba93-15724e54cc2c.png)

### PrimeFaces edition

Community

### PrimeFaces version

10-12

### Theme

Any

### JSF implementation

Mojarra

### JSF version

2.2.x

### Java version

11

### Browser(s)

Any

**Comment by jepsar** [comment]
Workaround:

```css
html body .ui-chkbox {
    display: inline-flex;
    align-items: center;
    width: auto;
    height: auto;
}
```

Tested with:

```xml
<p:triStateCheckbox itemLabel="Label"/>
<br/>
<br/>
<p:selectBooleanCheckbox itemLabel="Label"/>
```
