### ISSUE TITLE
TreeTable: Add SelectAll Checkbox header

### ISSUE THREAD

**Issue by RegiK123** [primefaces/primefaces#9413]
### Describe the bug

Select all not working for the tree table. (<p:column selectionMode="multiple" />)

### Reproducer

Run the code. The checkbox on the header not works and does not display. 

```
 <p:treeTable value="#{ttSelectionView.root3}" var="document" selectionMode="checkbox"
                     selection="#{ttSelectionView.selectedNodes2}">
<p:column selectionMode="multiple" />    
 <p:column headerText="Name">
                <h:outputText value="#{document.name}"/>
            </p:column>
            <p:column headerText="Size">
                <h:outputText value="#{document.size}"/>
            </p:column>
            <p:column headerText="Type">
                <h:outputText value="#{document.type}"/>
            </p:column>
        </p:treeTable>
```
code based on the https://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml?jfwid=74ff1

### Expected behavior

The selectAll checkbox should work for the tree table in the same way as for the basic table. 

### PrimeFaces version

12.0.0

### Theme

all

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

all

**Comment by melloware** [comment]
@RegiK123 I don't see a "Select All" in the checkbox header on the showcase: https://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml?jfwid=0eef8  Am I missing something?

**Comment by RegiK123** [comment]
@melloware  "SellectAll" - I mean the checkbox in the header that should be used to select all nodes in the tree table. And yes even if you add this line <p:column selectionMode="multiple" />    the column is displayed, but the checkbox is not :(

This should work in the same way, as it works for table -> I refer to the http://www.primefaces.org:8080/showcase/ui/data/datatable/selection.xhtml?jfwid=9b885 Checkbox example.

**Comment by melloware** [comment]
OK marked as enhancement as not all Datatable features are available in TreeTable as its quite different.

**Comment by melloware** [comment]
Replaced by https://github.com/primefaces/primefaces/issues/11250
