### ISSUE TITLE
TextEditor formating is not working with sanitizer on PF8

### ISSUE THREAD

**Issue by lbroker** [primefaces/primefaces#9414]
### Describe the bug

Component p:textEditor is used with sanitizer, means attribute secure=true
When some text is formatted, for example center in the row, when while text is saved and loaded next time, formatting is not visible.
If try to use without sanitizer (secure=false) then text formatting is visible correctly.

Code which shows issue:
<h:form id="frmTest">
    <h4>With sanitizer (sequre=true)</h4>
    <p:textEditor widgetVar="editor" value="#{testView.value}"   height="100"  secure="true" />
    <p:commandButton value="Save" action="#{testView.save}" update="@form" icon="pi pi-check"/> 
    <h4>Without sanitizer (sequre=false)</h4>			
    <p:textEditor widgetVar="editor2" value="#{testView.value}" height="100"  secure="false" />
</h:form>

Value from testView bean is:
 value="<p class=\"ql-align-center\">Centered text</p><p>Left aligned text</p>";

### Reproducer

See attached file with project where case reproduced on Primefaces-test 8.0

[primefaces-textEditor.zip](https://github.com/primefaces/primefaces/files/10030285/primefaces-textEditor.zip)

### Expected behavior

Test formatting should be loaded textEditor compoent the same way if sanitizer is loaded or not

### PrimeFaces edition

Community

### PrimeFaces version

8.0.22

### JSF implementation

All

### JSF version

2.3

### Java version

1.8.0_152

**Comment by tandraschko** [comment]
so it works fine on newer versions?

**Comment by lbroker** [comment]
Yes, it works with PF10. 
And see that PF8 still gets updates. And I think PF8 is still widely used.

**Comment by tandraschko** [comment]
please read carefully: https://github.com/primefaces/primefaces#community--elite--pro

the only thing we can do here is to ping @mertsincan

**Comment by melloware** [comment]
@lbroker as others have stated we can't fix 8 issues but you might want to check two things.  1. You are using the latest OWASP Sanitzer. 

That you decompile the code of 8.0.22 or look at the sources JAR and make sure the sanitizer lines look like this...

```java
    private static final PolicyFactory HTML_STYLES_SANITIZER = Sanitizers.STYLES
            .and(new HtmlPolicyBuilder()
            .allowElements("span", "li", "p")
            .allowAttributes("class")
            .onElements("span", "li", "p")
            .toFactory());
```

**Comment by lbroker** [comment]
Thanks @melloware, your recommendation regarding HTML_STYLES_SANITIZER update in PF 8.0.22 solved issue.
At least have checked text alignment what was important to me. Thanks :)
