### ISSUE TITLE
Speedial: Button accessibility tooltip and aria-label

### ISSUE THREAD

**Issue by liefke** [primefaces/primefaces#9421]
To accomplish accessibility guidelines I need to set some description attributes to the speed dial button, like "title" or "aria-describedby".

But the speed dial component does neither support a title attribute, nor does it render pass through attributes correctly.

_Steps to reproduce_

Use a JSF page like this:

```
<ui:composition ... xmlns:pf="http://primefaces.org/ui" xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    ...
    <pf:speedDial pt:aria-description="Add new element">
        <pf:menuitem value="Usertype 1" id="addPortalUser" title="Type 1" pt:aria-description="Add element of type 1" />
        ...
    </pf:speedDial>
    ...
</ui:composition>
```

The result looks like this:

```
<div ... aria-description="Add new element">
    <button ... aria-description="Add new element">...</button>
    <ul ... aria-description="Add new element">
        <li>
            <a ... data-tooltip="Type 1">...</a>
        </li>
        ....
    </ul>
```

As you can see, the passthrough attribute of the speed dial is added to three HTML elements instead of one and the passthrough attribute of the menu item is not rendered at all.

_Expected result_

The passthough attributes of the speed dial are only added to the button and the passthrough attributes of the menu item are added to the link. 

```
<div>
    <button ... aria-description="Add new element">...</button>
    <ul>
        <li>
            <a ... title="Type 1" aria-description="Add element of type 1">...</a>
        </li>
        ....
    </ul>
```

_Analysis_

For each component should `responseWriter.startElement("...", component)` be called once (all other times `responseWriter.startElement("...", null)` is to be used), to ensure, that the passthrough attributes are added to the correct HTML element, but [SpeedDialRenderer](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/speeddial/SpeedDialRenderer.java) uses them three times for the speeddial and never for the menu element.

I can provide a pull request, if that helps understanding the issue. But that would include a title attribute for the speed dial then, too.

**Comment by melloware** [comment]
Great suggestion.  One comment though for `menuItem` doesn't the value already describe it so you don't need an `aria-description` on the menu item just on the Button to trigger the speed dial right?

**Comment by melloware** [comment]
MenuItem is a duplicate of: https://github.com/primefaces/primefaces/issues/7970

**Comment by liefke** [comment]
It depends on the length of the value you choose. The value is optional, the menu item could be just an icon (like the examples here: https://primefaces.org/primeng/speeddial). In that case you would need something as accessibility text, and apparently the data-tooltip element wouldn't be sufficient because unknown to any accessibility tool.

And from an implementation point of view: Apparently for #7970 one hast to change all positions where a menu item is rendered somehow. I only had the speed dial renderer in mind when offering a PR.

**Comment by melloware** [comment]
i am thinking the following without getting crazy.

1. new prop on speedDial `ariaLabel` that goes on the `<button ... aria-label="Add new element">...</button>`

2. new prop on the MenuItem `ariaLabel` that we can just render on any MenuItem see: https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA8

**Comment by liefke** [comment]
I would focus on the passthrough attributes first, as there are enough other cases were you could use them.

But the ariaLabel prop could be an additional feature.

**Comment by melloware** [comment]
the `ariaLabel` prop is the easiest. Passthrough attributes in JSF are quite tricky as you have seen above.  And MenuItem doesn't support them at all and its a significant effort to implement which is why its not done.  Getting stuff to be ARIA compliant is always the first goal.

**Comment by melloware** [comment]
This component:
```xml
<p:speedDial direction="up" ariaLabel="SpeedDial Up">
        <p:menuitem icon="pi pi-pencil" action="#{speedDialView.add}" update="messages" ariaLabel="Edit"/>
</p:speedDial>
```

Now renders this correctly:
```xml
<div id="speedDialForm:j_id_94">
	<div class="ui-speeddial ui-widget ui-speeddial-linear ui-speeddial-direction-up ui-speeddial-opened">
		<button type="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-speeddial-button rounded-button ui-speeddial-rotate" aria-label="SpeedDial Up">
			<span class="ui-button-icon-left ui-icon ui-c pi pi-plus"></span>
			<span class="ui-button-text ui-c">ui-button</span>
		</button>
		<ul class="ui-speeddial-list" role="menu">
			<li role="none" class="ui-speeddial-item" style="transition-delay: 0ms;">
				<a tabindex="-1" role="menuitem" class="ui-speeddial-action" aria-label="Edit" href="#" onclick="PrimeFaces.ab({s:&quot;speedDialForm:j_id_95&quot;,f:&quot;speedDialForm&quot;,u:&quot;speedDialForm:messages&quot;});return false;">
					<span class="ui-speeddial-action-icon pi pi-pencil" aria-hidden="true"></span>
					<span class="ui-menuitem-text"></span>
				</a>
			</li>
```

**Comment by liefke** [comment]
As far as I can see, you would just need to change all `writer.startElement("div", speedDial)` to `writer.startElement("div", null)` and `writer.startElement("a", null)` to `writer.startElement("a", element)`. The rendering of passthrough arguments is done in the writer.

**Comment by melloware** [comment]
yeah but that still won't give you explicit control of setting the label on the button itself. I think passthrough elements we always want on the outmost control the DIV.

**Comment by melloware** [comment]
I removed the passthrough attributes on everything except for the container DIV element now.

**Comment by melloware** [comment]
i think there should also be a `title` attribute on speed dial that gets put on the button?  Right now there doesn't seem to be any way to add a tooltip to the button right?

**Comment by melloware** [comment]
Also `writer.startElement("a", element)` won't work because MenuItem is not a `UIComponent`.

**Comment by liefke** [comment]
My bad, I didn't notice that `MenuItem` isn't a UIComponent. That you added the passthrough elements to the button is imho the best solution.

Thanks for the quick fix.
