### ISSUE TITLE
CSP: Unintended form submit at CommandButton click

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#9424]
### Describe the bug

With CSP enabled, form submit event gets triggered after a commandButton is triggered. Two HTTP requests are generated instead of one.
[jsWrapper](https://github.com/primefaces/primefaces/blob/18892c0860c5da0f3b2cc278392d7d64fcc7fe73/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js#L66) does not manage to cancel the default action of the event. Maybe the `event.cancelable` property should be checked only if available, like `typeof event.cancelable !== 'boolean' || event.cancelable`.

### Reproducer

```
 <h:form>
    <p:commandButton id="cb" action="#{mb.action}" />
    <p:commandButton id="cb2" value="cb2" onclick="$('#cb').click();return false;" type="button" />
 </h:form>
```
Click on the cb2.

### Expected behavior

Generate only one HTTP request(for commandButton).

### PrimeFaces version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

1.8

### Browser(s)

Especially on Chrome

**Comment by melloware** [comment]
Have you tested a fix?

**Comment by mihaiDumea** [comment]
Yes I had

**Comment by mihaiDumea** [comment]
From here I got the inspiration: https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelable

**Comment by melloware** [comment]
OK check out my PR I think it makes sense.

**Comment by mihaiDumea** [comment]
Indeed. Without CSP would have an inline event handler `onclick="PrimeFaces.ab({...});return false;"` and returning false is enough to prevent the default action, either generating the event by the browser and having the `event.cancelable` defined, or triggering it via JQuery and having `event.cancelable` undefined.

**Comment by melloware** [comment]
Thanks for the report and the fix!
