### ISSUE TITLE
DataTable: filterMinLength

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primefaces#9426]
### Description

Please add filterMinLength to allow filter to work if minimum number of characters were entered, I know this can be accomplished with a custom filter function, but it's nice to have this built in attribute. 

### Describe the solution you would like

Please add filterMinLength to allow filter to work if minimum number of characters were entered, I know this can be accomplished with a custom filter function, but it's nice to have this built in attribute.

**Comment by melloware** [comment]
I know what you want but like you mentioned this can be accomplished other ways and I hesitate adding yet another filter property on the column.  Just my two cents.

**Comment by melloware** [comment]
Going to close this for now as it has 3 votes in the NO.
