### ISSUE TITLE
DatePicker: add inputmask.js dependency only if mask is enabled

### ISSUE THREAD

**Issue by pizzi80** [primefaces/primefaces#9428]
### Description

Actually the datepicker has a dependency on inputmask even 
if the mask option is not enabled.

Actually the default value for the mask option is false ...

### Describe the solution you would like

If it's possible add inputmask.js dependency only if mask is enabled

**Comment by tandraschko** [comment]
We dont have optional resources and it offen makes problems
Feel free to come with a PR
Otherwise i would not Invest time here

**Comment by melloware** [comment]
Agreed this is not worth investing time in for a very small network size performance gain.  My vote is -1.

```java
@ResourceDependency(library = "primefaces", name = "components.css")
@ResourceDependency(library = "primefaces", name = "jquery/jquery.js")
@ResourceDependency(library = "primefaces", name = "jquery/jquery-plugins.js")
@ResourceDependency(library = "primefaces", name = "core.js")
@ResourceDependency(library = "primefaces", name = "components.js")
@ResourceDependency(library = "primefaces", name = "inputmask/inputmask.js")
@ResourceDependency(library = "primefaces", name = "datepicker/datepicker.js")
public class DatePicker extends DatePickerBase {
```

**Comment by melloware** [comment]
Going to close this for now.  PR would be welcome if you really want to fix it but as I said these feels like a lot of work for a small improvement!
