### ISSUE TITLE
Blockui: resetPositionCallback is not executed if the duration is undefined

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#9431]
### Describe the bug

The resetPositionCallback is not executed in "hide" call if the duration is undefined. It really does nothing (master, blockui.js)
```
this.content.hide(duration, resetPositionCallback);
```
Fadeout works fine.

### Reproducer

1. open Primefaces demo
2. [go to blockui page](https://www.primefaces.org/showcase/ui/misc/blockUI.xhtml)
3. execute this code in console ``` PF('buiDatatable').cfg.animate = false;  ```
4. put the breakpoint to resetPositionCallback (components.js)
5. Change a page in the Custom content table.
6. never catched

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Chromium 106.0.5249.119

**Comment by melloware** [comment]
You are right it looks like jQueryUI `hide` method will not call the callback if no duration is defined.

MonkeyPatch:

```js
if (PrimeFaces.widget.BlockUI) {
    PrimeFaces.widget.BlockUI.prototype.hide = function(duration) {
        if (!this.isBlocking()) {
            return;
        }
        var $this = this;
        var animated = this.cfg.animate;
        var hasContent = this.hasContent();
        var callback = function() {
            if (!hasContent) {
                resetPositionCallback();
            }
        };
        var resetPositionCallback = function() {
            for (var i = 0; i < $this.target.length; i++) {
                $($this.target[i]).css('position', '');
            }
        };

        if (animated)
            this.blocker.fadeOut(duration, callback);
        else
            this.blocker.hide(duration || 0, callback);

        if (hasContent) {
            if (animated)
                this.content.fadeOut(duration, resetPositionCallback);
            else
                this.content.hide(duration || 0, resetPositionCallback);
        }

        this.target.attr('aria-busy', false);
    }
}
```

**Comment by vonnai** [comment]
I don't think your fix is right. The duration should be set to default only if the animated is false. Jquery default duration is 400 for fadeIn, fadeOut. Your fix will change the default behavior for each primefaces user. I think nobody uses the duration value in calling the hide func on the blockui widget.

**Comment by melloware** [comment]
No its right it sets the duration to `1 millisecond` ONLY if duration is `undefined, 0, or null`

**Comment by melloware** [comment]
The callback will never be called in fadeout or in hide without the duration set to a positive value.

**Comment by vonnai** [comment]
fadeOut works well with undefined duration, it uses the 400 by default and the callback will be called, just you can try it.The problem is only for hide.

**Comment by melloware** [comment]
OK updated my PR and monkeyPatch to only apply it to hide.

**Comment by vonnai** [comment]
thanks, it looks much better. I would change the default to 0, because if animated is false, why the hide action should take 1 millisecond?

**Comment by melloware** [comment]
let me try 0 but in JS falsy is `undefined, null or 0`.  So if they are treating undefined as don't call the callback I assume 0 will also be ignored.

**Comment by vonnai** [comment]
0 works well, I have tried it.

**Comment by melloware** [comment]
OK i just tested it too it is working. Odd that they aren't using `falsy` behvior and looking for undefined explicitly.
