### ISSUE TITLE
FileDownload: Encoding not working for inline download

### ISSUE THREAD

**Issue by miedrl** [primefaces/primefaces#9436]
### Describe the bug

I've got a text with special characters (e.g. the German umlauts ä,ö, and ü) which I want to download with contentDisposition="inline", the encoding fails. If I download the same text with contentDisposition="attachment", it works just fine.

### Reproducer

[reproducer.zip](https://github.com/primefaces/primefaces/files/10073276/reproducer.zip)

### Expected behavior

The encoding of special characters should be kept when downloading inline.

### PrimeFaces version

11.0.0

### Theme

Diamond

### JSF implementation

MyFaces

### JSF version

x.x

### Java version

x.x

**Comment by melloware** [comment]
I don't think this is PF issue. If you press F12 and watch the network traffic the server responded with the correct encoding.

![image](https://user-images.githubusercontent.com/4399574/203563165-836f4fb4-4173-4988-a756-521540952cae.png)

Its how the browser rendered it in plain text on the screen that is failing.

**Comment by miedrl** [comment]
Okay, thanks for the hint :)

**Comment by melloware** [comment]
will close for now!
