### ISSUE TITLE
Spinner: doenst increase because of rounding / math.floor error

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9442]
### Describe the bug

see spinner.js #spin:

`newValue = (dir > 0) ? Math.floor(newValue / step) * step : Math.ceil(newValue / step) * step;`

in my case step is 0.1 and newValue 0.6, which means that `newValue / step` is `5.999999999` and Math.floor results in 5 instead of 6

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

All

### JSF version

all

### Java version

11

### Browser(s)

FF

**Comment by tandraschko** [comment]
@melloware can you check? you introduced this because of #8631

**Comment by melloware** [comment]
yep will check.  I think I even added integration tests.

**Comment by melloware** [comment]
MonkeyPatch:

```js
if (PrimeFaces.widget.Spinner) {
        PrimeFaces.widget.Spinner.prototype.spin = function(dir) {
        var step = this.cfg.step * dir,
        currentValue = this.value ? this.value : 0,
        newValue = currentValue + step;
        
        if (Number.isSafeInteger(step)) {
            newValue = (dir > 0) ? Math.floor(newValue / step) * step : Math.ceil(newValue / step) * step;
        }
        
        newValue = this.parseValue(newValue);

        if(this.cfg.maxlength !== undefined && newValue.toString().length > this.cfg.maxlength) {
            newValue = currentValue;
        }

        this.value = newValue;
        this.format();
        this.input.attr('aria-valuenow', this.getValue());
    };
};
```

**Comment by tandraschko** [comment]
my case now works but not sure if it fix all possible rounding errors

**Comment by melloware** [comment]
I just updated the integration tests and the original ticket i fixed and this new ticket are both working!
