### ISSUE TITLE
SelectOneRadio: problem with accessibility on Custom Layout (Facet)

### ISSUE THREAD

**Issue by wbss1** [primefaces/primefaces#9446]
### Describe the bug

The extension Accessibility Insights for Web (https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni) report a problem of accessibility WCAG 4.1.2 on SelectOneRadio Custom Layout (Facet)
```
<span class="field-radiobutton" role="radio" aria-checked="false">
    <div id="j_idt344:facet1" class="ui-radiobutton ui-widget">
        <div class="ui-helper-hidden-accessible">
            <input id="j_idt344:customRadio:0_clone" name="j_idt344:customRadio_clone" type="radio" class="ui-radio-clone" 
                data-itemindex="0" value="Red">
        </div>
        <div class="ui-radiobutton-box ui-widget ui-corner-all ui-state-default">
            <span class="ui-radiobutton-icon ui-icon ui-icon-blank ui-c"></span>
        </div>
    </div>
    <label id="j_idt344:j_idt358" class="ui-outputlabel ui-widget" for="j_idt344:customRadio:0_clone">
        <span class="legend" style="background:red"></span> Red
    </label>
</span>
```
![Screenshot_1](https://user-images.githubusercontent.com/100421074/203835040-78ec6a86-b65b-45e5-9ec6-0c0f68660789.png)

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

Chrome 107.0.5304.107

**Comment by melloware** [comment]
Related to: https://github.com/primefaces/primefaces/issues/9282
