### ISSUE TITLE
ResourceUtils: does not recognize resource URLs on Jakarta EE

### ISSUE THREAD

**Issue by andrejkolontai** [primefaces/primefaces#9452]
### Describe the bug

`org.primefaces.util.ResourceUtils.getResourceURL(FacesContext, String)` doesn't recognize resource URLs on Jakarta EE. This caueses the ImageCropper to break when resource are used, i.e. `#{resource['requestPhotosEdit:9752-66110-07_3']}` used in the `image` attribute.

These URLs resolve into something like `/admin-ui/jakarta.faces.resource/9752-66110-07_3.jsf?ln=requestPhotosEdit` . But in the rendered HTML code they become something like `/admin-ui//admin-ui/jakarta.faces.resource/9752-66110-07_3.jsf?ln=requestPhotosEdit` (the context path gets prepended another time). 

I hunted this down to `org.primefaces.util.ResourceUtils.getResourceURL(FacesContext, String)`:

```java
        else if (value.contains(ResourceHandler.RESOURCE_IDENTIFIER)) {
            return value;
        }
````

In the case of a resource URL, the value should be returned unmodified. Instead, the `else` branch is taken (I guess):

```java
        else {
            String url = context.getApplication().getViewHandler().getResourceURL(context, value);

            return context.getExternalContext().encodeResourceURL(url);
        }
```

To me it seems that it simply does not recognize that this is a resource URL because it's still stuck in the `javax` namespace (despite `ResourceHandler.RESOURCE_IDENTIFIER` actually having the correct value).

### Reproducer

I have forked the `jakarta` branch of the primefaces-test project:

https://github.com/andrejkolontai/primefaces-test/tree/jakarta

To reproduce, clone my repo, check out the `jakarta` branch and run

```
mvn clean jetty:run
```

Open http://localhost:8080/primefaces-test/ in some browser.

You will see:
* the original URL from my project (in `jakarta` namespace)
* the same URL in `javax` namespace
* the `jakarta` URL after `ResourceUtils.getResourceURL` which is modified
* the `javax` URL after `ResourceUtils.getResourceURL` (which is not modified, but I don't really care it's just to prove that the old namespace is still beeing used).

![image](https://user-images.githubusercontent.com/20208057/204097874-dfb1a74a-b7c5-4ad6-a4a9-c02a9d545a2c.png)

### Expected behavior

`jakarta` resource URL should be returned unmodified. 

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

11

### Browser(s)

Chrome(ium)

**Comment by melloware** [comment]
Thanks for the excellent report!

**Comment by tandraschko** [comment]
shouldnt RESOURCE_IDENTIFIER be shaded to jakarta?
i will check it now

**Comment by tandraschko** [comment]
really weird
it also fails on MyFaces 4.0.0-SNAPSHOT, where you can clearly see:
`public static final String RESOURCE_IDENTIFIER = "/jakarta.faces.resource";`

`else if (value.contains(ResourceHandler.RESOURCE_IDENTIFIER)) {`
evaluates to false
where as `else if (value.contains("/jakarta.faces.resource")) {`
evaluates to true

maybe someone else can debug further
dependencies are looking fine
no idea

**Comment by NicolaIsotta** [comment]
I decompiled the jakarta jar, this is the method:
```java
    public static String getResourceURL(final FacesContext context, final String value) {
        if (LangUtils.isBlank(value)) {
            return "";
        }
        if (value.contains("/javax.faces.resource")) {
            return value;
        }
        final String url = context.getApplication().getViewHandler().getResourceURL(context, value);
        return context.getExternalContext().encodeResourceURL(url);
    }
```
Seems like the compiler, knowing that `RESOURCE_IDENTIFIER` is a constant (static and final), replaces the string reference with the value.

**Comment by tandraschko** [comment]
puuuh, okay
we have to check how to manage this with shade plugin
this will propably also hit us for other constants

**Comment by melloware** [comment]
Nice fix!
