### ISSUE TITLE
CommandButton: CommandButton loses focus when 'clicked' with enter button in a modal

### ISSUE THREAD

**Issue by SirError** [primefaces/primefaces#9457]
### Describe the bug

Hi everyone, this bug is kind weird.

if I have a modal dialog, with a commandButton and I use the enter button to "click" it instead of using mouse click, it loses focus when the ajax request ends.

This happens in Chrome, but not in Firefox;

I added a reproducer to better show the problem

### Reproducer

1 - It only happens in Chrome,  so open it in Chrome http://localhost:8080/primefaces-test/
2 - Click on "Test", the Dialog will show up
3 - Use tab to focus the button "with disable"
4 - press Enter on your keyboard, 
After that if you tab again the focus will go to the close button of the dialog, instead of the next button.

I noticed this only happens when disableOnAjax is true. 
To show that there's the next button called "Without Disable", if you focus it, and then press Enter, it will keep the focus.
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10125827/primefaces-test-master.zip)

### Expected behavior

After pressing Enter, the commandButton should keep the focus once the ajax request is completed.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

Any

### Java version

11

### Browser(s)

Chrome

**Comment by jepsar** [comment]
Does it work without the dialog?

**Comment by SirError** [comment]
> Does it work without the dialog?

<EDIT> Yes, it works without dialog </Edit>,

 it only happens on Dialog, and only when the Dialog is modal

**Comment by melloware** [comment]
That sure is weird and it is only in Chrome.  Not sure if its a Chrome bug or a Jquery but here is a workaround to make sure it always works.

```js
<p:commandButton process="@this"
				action="#{testView.changeNumber}"
				value="With Disable"
				ajax="true"
				update="value" 
				widgetVar="wgtDisable"
				oncomplete="setTimeout(function () {PF('wgtDisable').jq.focus();}, 100)"
 />
 ```
