### ISSUE TITLE
InputNumber: wrong selection after ajax

### ISSUE THREAD

**Issue by SirError** [primefaces/primefaces#9458]
### Describe the bug

If the inputNumber is updated by an ajax call before getting focus, and the value is bigger than the old value,
 just part of the new value is selected 

This image shows what happens
![image](https://user-images.githubusercontent.com/6018700/204878241-960640e0-550a-444f-8c9c-6296854e599e.png)

This other shows what shoul happen
![image](https://user-images.githubusercontent.com/6018700/204879039-05a6987b-6dac-4848-a525-a13a6cd54fae.png)

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10126169/primefaces-test-master.zip)

1 - open http://localhost:8080/primefaces-test/
2 - type 10 on first inputNumber
3 - tab and type 1000 on the second inputNumber
4 - tab again, the third input will receive the value 10000.00 but only the first three digits will be selected instead of the whole value.

### Expected behavior

the whole value should be selected.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

any

### Java version

11

### Browser(s)

any

**Comment by melloware** [comment]
Not sure I want to fix this because this is a race between your AJAX update and the tab key and AutoNumeric but here is a nice little workaround using AJAX `oncomplete`

```xml
<h:form>
	<p:inputNumber id="value" value="#{testView.number}">
		<p:ajax update="value3" listener="#{testView.calc()}"/>
	</p:inputNumber>
	<p:inputNumber id="value2" value="#{testView.number2}">
		<p:ajax update="value3" listener="#{testView.calc()}" oncomplete="PF('wgtValue3').input.select();"/>
	</p:inputNumber>
	<p:inputNumber id="value3" widgetVar="wgtValue3" value="#{testView.number3}"/>
</h:form>
```

**Comment by melloware** [comment]
I marked this 3rd party as I actually believe its AutoNumeric that automatically selects all the text when you tab in. so its selecting the range of 3 then your AJAX update wipes it out and its still only has the range select of 3

**Comment by SirError** [comment]
Hi @melloware , is there some way of inject some autonumeric configuration through Primefaces or some JS file?
reading autonumeric's docs, I think I could solve it globally with these options:

```
{
    caretPositionOnFocus: AutoNumeric.options.caretPositionOnFocus.start,
    selectOnFocus: AutoNumeric.options.selectOnFocus.doNotSelect
}
```

**Comment by melloware** [comment]
Let me take a look I think I can give you something!

**Comment by melloware** [comment]
OK here is a working project I added this monkeyPatch to `test.js`.
[pf-9458.zip](https://github.com/primefaces/primefaces/files/10132470/pf-9458.zip)

```js
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        this.input = $(this.jqId + '_input');
        this.hiddenInput = $(this.jqId + '_hinput');
        this.plugOptArray = cfg.pluginOptions;
        this.valueToRender = cfg.valueToRender;
        this.disabled = cfg.disabled;

        // GitHub #8125 minValue>0 shows js warning and quirky behavior
        if (this.cfg.minimumValue > 0.0000001 || this.cfg.maximumValue < 0) {
            this.cfg.overrideMinMaxLimits = 'invalid';
        }

        //bind events if not disabled
        if (this.disabled) {
            this.input.attr("disabled", "disabled");
            this.input.addClass("ui-state-disabled");
            this.hiddenInput.attr("disabled", "disabled");
        }

        //Visual effects
        PrimeFaces.skinInput(this.input);

        this.wrapEvents();
        this.bindInputEvents();

        this.cfg.caretPositionOnFocus = AutoNumeric.options.caretPositionOnFocus.start;
        this.cfg.selectOnFocus = AutoNumeric.options.selectOnFocus.doNotSelect;

        this.autonumeric = new AutoNumeric(this.jqId + '_input', this.cfg);

        if (this.valueToRender !== "") {
            //set the value to the input the plugin will format it.
            this.autonumeric.set(this.valueToRender);
            // GitHub #6940 blur firing too many change events
            this.autonumeric.rawValueOnFocus = this.valueToRender;
        }

        this.setValueToHiddenInput(this.getValue());

        //pfs metadata
        this.input.data(PrimeFaces.CLIENT_ID_DATA, this.id);
        this.hiddenInput.data(PrimeFaces.CLIENT_ID_DATA, this.id);
    }
}
```

**Comment by melloware** [comment]
I think I need to add these two props to the component for the future if someone else wants to set these.

**Comment by melloware** [comment]
in 13.0 you will be able to do this `selectOnFocus="false" caretPositionOnFocus="start"`
