### ISSUE TITLE
Avatar: Error rendering label with only numbers

### ISSUE THREAD

**Issue by ybendek** [primefaces/primefaces#9459]
### Describe the bug

I have an issue where the value passed to the attribute label is only numbers or anything different as letters, the current version throws an exception with the message 

`java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.primefaces.component.avatar.AvatarRenderer.calculateLabel(AvatarRenderer.java:128)
	at org.primefaces.component.avatar.AvatarRenderer.encodeEnd(AvatarRenderer.java:58)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:152)`

Reviewing the source code of the avatar component I found that the component is assuming that only letters are included in the label if not, the call of the following method throws the exception

```java
protected String calculateLabel(FacesContext context, Avatar avatar)  {

        String value = avatar.getLabel();

        if (value == null || value.length() <= 2) {
            return value;
        }
        Matcher m = LETTER_PATTTERN.matcher(value);
        StringBuilder sb = SharedStringBuilder.get(context, SB_AVATAR);
        while (m.find()) {
            sb.append(m.group());
        }
        String initials = sb.toString();
        return initials.length() == 1 ? initials : initials.charAt(0) + initials.substring(initials.length() - 1);
    }
```

### Expected behavior

The label should be taken as an string of characters no matters if its only numbers and not letters on it.

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.9

### Theme

Rain

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

11

### Browser(s)

Chrome

**Comment by melloware** [comment]
Can you paste your exact XML snippet. We definitely assumed it was names that would be in there.

**Comment by melloware** [comment]
Verified it and added 3 more unit tests.

```java
Arguments.of("6", "6"),
Arguments.of("67", "67"),
Arguments.of("8675309", "8"),
```

**Comment by ybendek** [comment]
> Can you paste your exact XML snippet. We definitely assumed it was names that would be in there.

Sure, I found that not for only numbers, in some cases fails with letters

`
<p:avatar label="41235 5asdd"  shape="circle" dynamicColor="true"  size="large" saturation="60" icon="pi pi-user"/>

<p:avatar label="1234"  shape="circle" dynamicColor="true"  size="large" saturation="60" icon="pi pi-user"/>

<p:avatar label="888 7666"  shape="circle" dynamicColor="true"  size="large" saturation="60" icon="pi pi-user"/>
`

**Comment by melloware** [comment]
Great let me add your use case to the unit tests.

**Comment by melloware** [comment]
OK with my latest fix your labels would come out like this...

```java
                   Arguments.of("41235 5asdd", "4"),
                    Arguments.of("1234", "1"),
                    Arguments.of("888 7666", "8"),
```
