### ISSUE TITLE
Javascript error with dynamically loaded p:carousel

### ISSUE THREAD

**Issue by benjes** [primefaces/primefaces#946]
Hi

I am getting a Javascript error:

```
Uncaught TypeError: this.itemsContainer.swipe is not a function
PrimeFaces.widget.Carousel.PrimeFaces.widget.DeferredWidget.extend.bindEvents @ primefaces.js.seam?ln=primefaces&v=5.3:12
PrimeFaces.widget.Carousel.PrimeFaces.widget.DeferredWidget.extend._render @ primefaces.js.seam?ln=primefaces&v=5.3:12
PrimeFaces.widget.DeferredWidget.PrimeFaces.widget.BaseWidget.extend.renderDeferred @ primefaces.js.seam?ln=primefaces&v=5.3:5
PrimeFaces.widget.Carousel.PrimeFaces.widget.DeferredWidget.extend.init @ primefaces.js.seam?ln=primefaces&v=5.3:12
e.(anonymous function) @ primefaces.js.seam?ln=primefaces&v=5.3:5c @ primefaces.js.seam?ln=primefaces&v=5.3:5
b.createWidget @ primefaces.js.seam?ln=primefaces&v=5.3:1b.cw @ primefaces.js.seam?ln=primefaces&v=5.3:1
```

when using a p:carousel inside a page that loads other pages dynamically via a ui:include.

So lets say you have a page main.xhtml which has:

```
<ui:include page="#{backingBean.currentPage}"/>
```

Initially the main page loads with the include 'include1.xhtml'.
Now via ajax the included page changes to 'include2.xhtml' which includes a p:carousel. At this point do you get the javascript error.

It seems that some javascript functions aren't loaded when Primefaces does not see a carousel initially. But when the carousel is added dynamically the javascript error occurs. 

If I add a dummy 

```
<p:carousel rendered="false"/> to the main page it works without problems.
```

IMHO this is a valid use case (using ui:include to load parts dynamically).

I have been using PF 5.3.

**Comment by tandraschko** [comment]
Please try again with the upcoming 6.1-RC1 next week. We fixed some problems regarding dynamic resource loading. Otherwise please reopen.
