### ISSUE TITLE
HTTP-Header Content-Security-Policy Nonce can be overwritten by client for Ajax requests

### ISSUE THREAD

**Issue by Hurled4505** [primefaces/primefaces#9461]
### Describe the bug

A content security policy with a secure directive is used. However, it is possible to influence the script-src directive and thus bypass the protection of the CSP header. The nonce value is set by the client-side parameter primefaces.nonce. This allows the **nonce value** in **POST requests to be determined by the user**, bypassing the protection of the header. 

--> The nonce value should be randomly generated on the server side for each request/response. The user must not be able to influence the nonce value.

### Sample Request:

**Header:**
POST https://localhost:8444/testTab.jsf HTTP/1.1
Host: localhost:8444
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Accept: application/xml, text/xml, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Faces-Request: partial/ajax
X-Requested-With: XMLHttpRequest
Content-Length: 963
...

**Body:**
javax.faces.partial.ajax=true&javax.faces.source=quick-filters%3AquickFilter-form%3AselectOneMenuTestDropdown&javax.faces.partial.execute=quick-filters%3AquickFilter-form%3AselectOneMenuTestDropdown&javax.faces.partial.render=testTable-form&javax.faces.behavior.event=change&javax.faces.partial.event=change&quick-filters%3AquickFilter-form=quick-filters%3AquickFilter-form&javax.faces.ViewState=499211688213529577%3A-8085365838550146838&**primefaces.nonce=testscript1234**

### Response:

**Header:**
HTTP/1.1 200 OK
Content-Type: text/xml;charset=utf-8
Content-Security-Policy: default-src 'none'; base-uri 'self'; frame-ancestors 'none'; connect-src 'self'; img-src 'self'; font-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'strict-dynamic' **'nonce-testscript1234'**
Pragma: no-cache
...

**Body:**
```
<xml version='1.0' encoding='utf-8'?>
<partial-response id="j_id1"><changes><update id="quick-filters:quickFilter-form-messages">
<![CDATA[<div id="quick-filters:quickFilter-form-messages" class="ui-messages ui-widget" aria-live="polite"</div>]]>/update>
<update id="testTable-form:testTable"><![CDATA[<tr data-ri="32660" class="ui-widget-content ui-datatable-even" role="row"><td role="gridcell" class=""><span class=" ">*******</span></td>
<td role="gridcell" class=""></td><td role="gridcell" class="">*******</td>
<td role="gridcell" class=""><span class=" ">*******</span></td>
<td role="gridcell" class="pre-wrap break-word"><span class=" "></span></td>
<td role="gridcell" class="">*******</td>
<td role="gridcell" class="">*******</td>
<td role="gridcell" class="">*******</td>
<td role="gridcell" class="column-ac-tion"><button id="testTable-form:testTable:32660:view-button" name="testTable-%form:test-Table:32660:view-button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only secondary-%button" type="submit"><span class="ui-button-icon-left ui-icon ui-c ui-icon-pa-per"></span><span class="ui-button-text %ui-c">ui-button</span></button>
```
**<script id="testTable-form:testTable:32660:view-button_s" type="text/javascript" %nonce="testscript1234">** 
```
PrimeFaces.cw("CommandButton","widget_testTable_form_test-Table_32660_view_button",{id:"testTable-form:testTable:32660:view-button"});</script></td></tr>
```

### Expected behavior

The nonce value should be randomly generated on the server side for each request/response. The user must not be able to influence the nonce value.

### PrimeFaces version

10.0.10

### Theme

Bootstrap

### JSF implementation

All

### JSF version

2.2.20

### Java version

17.0.3

### Browser(s)

Firefox 106.0.5 (64-bit)

**Comment by NicolaIsotta** [comment]
Already talked about this with @melloware in the forums: https://forum.primefaces.org/viewtopic.php?f=3&t=77769
I've tested the fix right now and it seems to work, I will submit a PR for review soon

**Comment by jepsar** [comment]
@NicolaIsotta there wasn't already an issue for this yet then?

**Comment by NicolaIsotta** [comment]
> @NicolaIsotta there wasn't already an issue for this yet then?

Nope, was going to create it together with the PR
