### ISSUE TITLE
Chips: Unique on server side

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#9463]
### Describe the bug

The ChipsRenderer doesn't make the unique set if the unique attribute is true.

### Reproducer

1. Put the first value into chips and press enter
2. the Chips component contains the one boxed value
3. Enter the second value, but don't press the enter key
it look like this:

```
 _____________________________________________________
|  _____________________                              |
| | the first value | x |  the second value           | 
|  ----------------------                             |
 -----------------------------------------------------
```

4. Submit the form
5. Check the ChipsRenderer.java, the hinput + input values are concatenated. The duplicate value is not removed.

### Expected behavior

The unique attribute works well, the value is changed in the ChipsRenderer.java.
Maybe like this:

```
if (submittedValues.length > 0) {
    
    /*fix*/    if (chips.isUnique()) {
    /*fix*/        submittedValues = Arrays.stream(submittedValues).distinct().toArray(String[]::new);
    /*fix*/     }
    
    chips.setSubmittedValue(submittedValues);
}
else {
     chips.setSubmittedValue("");
}
if (chips.isUnique()) {
    submittedValues = Arrays.stream(submittedValues).distinct().toArray(String[]::new);
}
```

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Chromium 106.0.5249.119

**Comment by melloware** [comment]
Thanks for the report!  Please review my PR.

**Comment by vonnai** [comment]
thanks for the fix.
