### ISSUE TITLE
SEO - p:link being styled as p:button

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#947]
Often the styling of p:button is needed for nicer looking interfaces while SEO friendly GET links are required. 

p:button performs get requests either but via javascript. This is not SEO friendly as p:link is.
### Workaround

use PrimeUI to style this button. This is overkill in case PrimeUI is not used anyway since PrimeUI and PrimeFaces CSS differ and thus many resources need to be included and styles being synchronized just for achieving the same styling as a p:button.

**Comment by kukel** [comment]
Please add the css that achieves this to the issue. It increase the chance of the request getting applied. Better yet, file a pull request.

**Comment by tandraschko** [comment]
@melloware Why is this invalid?

**Comment by melloware** [comment]
@tandraschko You are right this really is an enhancement or new component.

**Comment by eversnarf** [comment]
Would be quite useful indeed!

**Comment by tandraschko** [comment]
see #3613
