### ISSUE TITLE
SelectCheckboxMenu: dynamic=false and ajax-toggleSelect, component height wrong after selectAll

### ISSUE THREAD

**Issue by rhirt23** [primefaces/primefaces#9475]
### Describe the bug

Basic Example from showcase with dynamic=false and ajax-toggleSelect-tag causes height change of component when selecting/deselecting all.
With dynamic=true the error does not occur.

### Reproducer

Basic Example from showcase with dynamic=false and ajax-toggleSelect
```
<h5 class="mt-0">Basic</h5>
<p:selectCheckboxMenu id="menu" widgetVar="menuWV" value="#{checkboxView.selectedCities}" label="Cities"  style="width: 15rem"
                        panelStyle="width: 15rem" scrollHeight="250" >
    <f:selectItems value="#{checkboxView.cities}" />
    <p:ajax event="toggleSelect" update="@this" /> 
</p:selectCheckboxMenu>

```	 

### Expected behavior

Dont change height of component when selecting or deselecting all.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.0

### JSF implementation

MyFaces

### JSF version

2.3.9

### Java version

1.8.0_191

### Browser(s)

Firefox

**Comment by jepsar** [comment]
Makes me think of https://github.com/primefaces/primefaces/issues/9148

**Comment by melloware** [comment]
I wonder if we should fix this 200px hard coding?

**Comment by jepsar** [comment]
In the other issue I think you can just set the `scrollHeight` attribute to `"auto"`. I did not check this issue yet, but the same workaround might be used.

**Comment by rhirt23** [comment]
Seems to be an issue with our old custom theme.css using saga like in the showcase, the effect does not occur.

**Comment by rhirt23** [comment]
Showcase works fine with saga theme, therefore I close the issue.
With the old theme.css I could prevent the effect by adding this rule:
``` 
.ui-selectcheckboxmenu .ui-selectcheckboxmenu-label-container {
	display:block;
} 
```
