### ISSUE TITLE
Datatable: add cellWrap to disable word-wraps

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9482]
### Description

Currently, https://primefaces.github.io/primefaces/12_0_0/#/components/datatable breaks white-spaces for both header text and column content.

### Describe the solution you would like

Please add a property (e.g. `cellWrap="false|true"`  (with default `true`) in https://primefaces.github.io/primefaces/12_0_0/#/components/datatable to disable white wrapping content. If `cellWrap="false"`, then the cell content does not break on white spaces but the cell width increases to fit its content.

```
/** the following css snippet does not fully work, 
because the content (of the cell) overflows abroad the cell 
instead of resizing the cell to prevent line-breaks */

.ui-datatable table th, .ui-datatable table td{
	white-space: nowrap;
	width: 100%;
}
```

**Comment by melloware** [comment]
If I remember this has been discussed in the passed and autosizing the table base on cell contents PrimeTek has always stated as too expensive to reculaculate the whole table and its column sizes.

If you create a [PrimeFaces Test](https://github.com/primefaces/primefaces-test)  reproducer I think I can give you some JS code that will solve your problem the way you want the table to be.

**Comment by nimo23** [comment]
@melloware thanks for your help! I did manage it by myself by giving some cells a specific width.
