### ISSUE TITLE
dataTable: given column width not used when having frozenColumns

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9483]
### Describe the bug

I have a fixed column but the fixed column does not consider the given column width of 120px. Instead of the given column width of 120px, it uses a width of 50% of parent container:

```
<p:dataTable scrollable="true" scrollHeight="640" scrollWidth="500" frozenColumns="1" ..>

<!-- width is not 120px but 50% of parent container >
<p:column width="120px">
..
</p:column>

</p:dataTable>
```

Looking at the pf `components.css`:

```
.ui-datatable table {
  border-collapse: collapse;
  width: 100%;
  table-layout: fixed;
}
```

changing to 

```
.ui-datatable table {
  border-collapse: collapse;
  width: auto;
  table-layout: fixed;
}
```

will consider the given width of 120px but then when scrolling to the right, the column header does not start and begin with its column content.

### Expected behavior

Given `p:column width` must be considered.

### PrimeFaces edition

None

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

jdk 17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
I have this working in my app so if you create a PrimeFaces Test reproducer I can probably show you how to fix it.

**Comment by nimo23** [comment]
@melloware I also find a workaround by setting the width in the pf class:

```
.ui-datatable-frozenlayout-left{
  width: 120px;
}
```

However, why should I use a workaround for this? This is a bug and should be resolved. Using `<p:column width="120px">` should be also considered when having a given `scrollWidth` and `frozenColumns`. Actually, this is not done as we can easily see this in the resulting css above.

**Comment by melloware** [comment]
Your CSS has always been the recommendation of PrimeTek: https://github.com/primefaces/primefaces/issues/708

Trying to make freeze, scrollable, auto layout all working together is no easy task.  Your solution is exactly what I do.

**Comment by nimo23** [comment]
Then this should be stated at least into the documentation of https://primefaces.github.io/primefaces/12_0_0/#/components/datatable. Otherwise, users could not know about this fix.

**Comment by melloware** [comment]
Agreed.  Care to submit a PR?

**Comment by nimo23** [comment]
I don't know if it's better to fix this or to only provide the information about the workaround in the following section: https://primefaces.github.io/primefaces/12_0_0/#/components/datatable?id=frozen-columns ?

If only documentation is needed, we can use the following text:

The column's `width` property is ignored when using it with`frozenColumns`. In order to use `frozenColumns` in combination with a column `width`, you must set the `width` of the column within the css class `.ui-datatable-frozenlayout-left`, For example, 

```
.ui-datatable-frozenlayout-left{
  width: 40px;
}
```

**Comment by melloware** [comment]
Hmmm I am looking at a project I have and I am using frozen columns without the above CSS and its all working for me.

```xml
<p:dataTable id="tblEntity" table="#{reportDataTable}"
		skipChildren="false" paginatorAlwaysVisible="true" resizableColumns="true" frozenColumns="3" scrollable="true"
		scrollWidth="100%">
		<p:column id="colId" styleClass="col-right" width="50">
			<h:outputText value="#{row.id}" />
		</p:column>

		<p:column id="colName"  styleClass="col-left"width="400">
			<h:outputText value="#{row.name}" />
		</p:column>

		<p:column id="colOrg" width="50">
			<h:outputText value="#{row.org}" />
		</p:column>
```

**Comment by melloware** [comment]
In fact here is a reproducer; 
[pf-9483.zip](https://github.com/primefaces/primefaces/files/10202875/pf-9483.zip)

Just unzip and run `mvn clean jetty:run` and you will see my frozen column has width="200".  Then change it to "300" and you will see it.

**Comment by nimo23** [comment]
Oh, thanks. Yes, it works. One question though. You give `scrollWidth="100%"` as percentage. Is this allowed? According to doc, we can only use an integer value without the unit:



`scrollWidth | null | Integer | Scroll viewport width.`

Are the following declarations allowed by PF?
- scrollWidth="100%" or 
- scrollWidth="100px" or 
- scrollWidth="100" (which is the same as scrollWidth="100px")

**Comment by nimo23** [comment]
Yes, we can give the unit indeed. This is something which I did not know. When giving the unit as **percentage** the above case works without using setting width in `.ui-datatable-frozenlayout-left`. So I will close this issue. @melloware Thanks!

**Comment by melloware** [comment]
Yep a lot of them across PF allow you to use "100px" or "100%" or "100vw".  Whatever is typically available as CSS!
