### ISSUE TITLE
Datatable: sortBy with sortByClient="true|false"

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9484]
### Description

Actually, `p:dataTable sortBy` only works for ajax. However, if the datatable has `lazy="false"`, then all data is already on the client. Thus, it would make sense to sort (and filter?) only by clientSide (without the need for ajax-request) if `<p:dataTable sortByClient= "true" ..`.

### Describe the solution you would like

If `sortByClient="true"`, then sorting should only be done by client side (without ajax).

### Additional context

Maybe, add also`filterByClient="true"`: If true, then filtering should only be done on client side (without ajax) by filtering the data already available on the client.

**Comment by tandraschko** [comment]
Yes it would make sense but 95% of the datatables are lazy+paging
So IMO its not worth to work on it
If you would like to work on a PR, we can discuss it
Also things like multisort or global filtering makes it quite complex and duplicates code

**Comment by nimo23** [comment]
>Also things like multisort or global filtering makes it quite complex and duplicates code

Maybe we could add a 3rd party lib like https://listjs.com/ or https://www.tablefilter.com/. But I don't know if this would make much sense as you said that "95% of the datatables are lazy+paging".

**Comment by melloware** [comment]
Agreed on this one.  It would be complicated to implement in JS only with very few use cases.
