### ISSUE TITLE
DefaultStreamedContent.contentLength is Integer

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#9485]
I think Long would be better for bigger files.

**Comment by tandraschko** [comment]
see ExternalContext:

`public void setResponseContentLength(int length) {`

**Comment by morvael** [comment]
I have a 5GB file to push through it, and it gets cut off at 2GB. What can be done?

**Comment by morvael** [comment]
See

  | setContentLengthLong
-- | --


[setContentLengthLong](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletResponse.html#setContentLengthLong-long-)

**Comment by morvael** [comment]
ExternalContext says it must push it through ServletResponse and ServletResponse now has the correct method for longs.

**Comment by morvael** [comment]
Seems like a fckp of the ExternalContext  guys.

**Comment by morvael** [comment]
Can you get to ServletResponse bypassing ExternalContext?

**Comment by tandraschko** [comment]
https://docs.oracle.com/javaee/7/api/javax/faces/context/ExternalContext.html#setResponseContentLength-int-

**Comment by tandraschko** [comment]
I think you should create a faces specification issue first
we rely on faces api and try to avoid direct servlet calls as we also need to care about porlets

**Comment by morvael** [comment]
Yes: "Servlet: This must be performed by calling the javax.servlet.http.HttpServletResponse setContentLength method."
but ServletResponse has now new method for Long length.

**Comment by morvael** [comment]
> I think you should create a faces specification issue first we rely on faces api and try to avoid direct servlet calls as we also need to care about porlets

And wait a few years? I think I need a hack around your code and ExternalContext as well for today (business reality). Do you have an idea how?

**Comment by tandraschko** [comment]
Faces 4.0 is on the track, might be a good chance currently to get it in

**Comment by tandraschko** [comment]
i would copy StreamedContentHandler in your project in the same package, so yours is used

**Comment by morvael** [comment]
Somehow I guess I need to be able to override FileDownloadActionListener.regularDownload and plug my implementation if that's possible?

**Comment by morvael** [comment]
> i would copy StreamedContentHandler in your project in the same package, so yours is used

Clever. What about the other place I saw StreamedContent.getContentLength used?

**Comment by morvael** [comment]
I hope this will be enough:
https://github.com/jakartaee/faces/issues/1764

**Comment by melloware** [comment]
From BalusC: FYI: work around: `ec.setResponseHeader("Content-Length", String.valueOf(contentLengthLong))`. Has been in among others `OmniFaces Faces#sendFile()` for ages.

**Comment by morvael** [comment]
Not very helpful if all I have to work with p:fileDownload and StreamedContent is Integer contentLength. That part of PF API needs enchancement too, in anticipation of JSF API enchancement. Basically the workaround is only for PF internal classes, not for someone using PF API.

**Comment by morvael** [comment]
1) you change StreamedContent from Integer to Long
2) temporarily you use setResponseHeader workaround in FileDownloadActionListener and StreamedContentHandler 
3) once JSF API 4.0 is ready you switch from workaround to new Long methods in same classes, without affecting PF users

That seems like a good plan for me :)

**Comment by melloware** [comment]
agreed care to submit a PR?

**Comment by morvael** [comment]
Lol, now I'll become a laughingstock for not knowing how you submit a PR. As for code modification, I can do it. Plus there's a decision to make whether keep old methods in StreamedContent and add Long ones, or just change existing ones to Long.

**Comment by morvael** [comment]
Quickly, I can provide only this (changed files in zip):
[primefaces.zip](https://github.com/primefaces/primefaces/files/10209474/primefaces.zip)

Issues:
- DefaultStreamedContent serialized form changes
- classes extending DefaultStreamedContent may not work correctly without overriding getContentLengthLong (wondered about default implementation in StreamedContent, but don't remember what is your lowest supported Java version, plus it doesn't help when extending DefaultStreamedContent which has its own implementation).

**Comment by melloware** [comment]
@morvael i will take a look.

**Comment by melloware** [comment]
PR submitted using OmniFaces trick.

**Comment by melloware** [comment]
Looks like BalusC just submitted this to Mojarra: https://github.com/eclipse-ee4j/mojarra/pull/5187

**Comment by tandraschko** [comment]
@melloware will you take of this in MF?

**Comment by melloware** [comment]
Yep it looks like he submitted that for Mojarra 4.1 but we don't have a 4.1 can I just put it in 4.0.RC3?

**Comment by tandraschko** [comment]
oh then lets wait till we have a 4.1 branch
