### ISSUE TITLE
Overlapping Chart Axis when Zoom is enabled

### ISSUE THREAD

**Issue by ftbalagt** [primefaces/primefaces#949]
Hi,
I would just like to ask if anyone has a solution to the problem of having overlapping axis depending on the zoom level for charts. See screenshot:
![overlappingaxis](https://cloud.githubusercontent.com/assets/16207609/11655760/963c2096-9db0-11e5-9815-1f88ca5442c2.PNG)

Thanks in advance!

**Comment by cagataycivici** [comment]
Please use forum for questions like these.

Also can you replicate at;

http://www.jqplot.com/deploy/dist/examples/rotatedTickLabelsZoom.html

**Comment by melloware** [comment]
@Rapster can you close this ticket as invalid. It's really a question for forums not a bug.
