### ISSUE TITLE
SelectOneMenu: computed inline style of width is 2px too much

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9502]
### Describe the bug

The `p:selectOneMenu` computes inline styles for the class `.ui-input-overlay`:

`<div class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay ui-connected-overlay-exit-done" style="display: none; width: 815px; left: 447px; top: 123.1px; transform-origin: center top 0px;">..</div>`

The **width** (in this case: `815px`) is always 2 px too much. Please correct the calculation by substracting exactly `2px` while calculating the inline style.

### Reproducer

1. Use any p:selectOneMenu
2. Add the following css class to make the difference of 2px more visible:

```
body .ui-selectonemenu-panel {
  box-shadow: none;
  border-radius: 0;
  border: 1px solid blue;
}
```
3. Then you see somehing like this:

![2px-too-much](https://user-images.githubusercontent.com/3045549/207397999-90e8fa2b-bf2f-4b00-bc33-1bb4a75e2e58.png)

4. Look at the inline styles of `ui-selectonemenu-panel `computed by PF and edit its width by substracting 2px. Then the width will be correctly aligned to its upper input-field and looks like this:

![2px-less](https://user-images.githubusercontent.com/3045549/207399689-bca8309d-ea9d-4d30-bb58-bc438a2853b5.png)

### Expected behavior

Correct inline width calculation of `p:selectOneMenu`. As the user cannot correct this issue by css (because its a calculated inline style of PF), it would be good if PF calculates its inline `width` correctly by substracting `2px` within its calculation.

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
Which theme are you using?

**Comment by melloware** [comment]
I am not seeing this issue on the showcase: https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

**Comment by nimo23** [comment]
@melloware I use the same (**default**) theme as https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml.

You will **not** see this issue at https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml. You will see this issue if you follow my reproducer (described above). Use the following css-snippet in your css file and reload the page with the `p:selectOneMenu`:

```
body .ui-selectonemenu-panel {
	border-radius: 0;
	border: 1px solid black;
	box-shadow: none;
}
```

Then you see what I mean. If I remove the box-shadow without adding a border, then no issue is visible, but if I "**remove the box-shadow"** AND "**add the border"**, then the issue occurs.

**Comment by melloware** [comment]
but that leads to my question why are you using this CSS if the themes render the SelectOne fine?

**Comment by nimo23** [comment]
I don't want the box-shadow and I want to use a border instead. It should be eligable to change the default theme by css. What's the problem if the user wants to change a `box-shadow` to a `border`? The default PF theme should consider such flexibility..

How can this issue be solved would be the right question:)

**Comment by nimo23** [comment]
I think PF calculates the inline style by javascript..thus it does take into account the `box-shadow` within its calculation..maybe we can enhance it so that it does not use the `box-shadow` only to calculate the `width`.. I don't know if this is the right approach..

**Comment by melloware** [comment]
I will post a patch you can just use locally tomorrow.

**Comment by melloware** [comment]
Here is a MonkeyPatch just add this to your code and you should be able to tweak it however your want.  That is the power of PrimeFaces!

```js
if (PrimeFaces.widget.SelectOneMenu) {
    PrimeFaces.widget.SelectOneMenu.prototype.alignPanelWidth = function() {
        //align panel and container
        if (!this.panelWidthAdjusted) {
            var jqWidth = this.jq.outerWidth();
            if (this.panel.outerWidth() < jqWidth) {
                this.panel.width(jqWidth);
            } else {
                this.panel.width(this.panel.width());
            }

            this.panelWidthAdjusted = true;
        }
    };
}
```

**Comment by nimo23** [comment]
Thanks @melloware. It works with the following script:

```
(function() {

	// TODO https://github.com/primefaces/primefaces/issues/9502#issuecomment-1351405351
	if (PrimeFaces.widget.SelectOneMenu) {
		console.log(PrimeFaces.widget.SelectOneMenu);
		PrimeFaces.widget.SelectOneMenu.prototype.alignPanelWidth = function() {
			//align panel and container
			if (!this.panelWidthAdjusted) {
				var jqWidth = this.jq.outerWidth();
				if (this.panel.outerWidth() < jqWidth) {
					this.panel.width(jqWidth - 2);
				} else {
					this.panel.width(this.panel.width());
				}

				this.panelWidthAdjusted = true;
			}
		};
	}
}());
```

Would it be possible to add this fix to PF so that users don't need to stumble to this workaround? Or maybe another more generic solution can be found. I am wondering why the width must be substracted by 2 even if your snippet already takes the width from the outer container. 

Maybe it is really css issue of PF: As it's exactly 2px (1px left and 1px right?) which is missing, the css could be adjusted? (e.g. box-sizing: content-box). I have tried it solely with css but cannot find a solution.

A simple solution would be to add a general css class to PF: `.pf-no-box-shadow`, so that PF uses only border-lines instead of box-shadows when this class is applied to components.

**Comment by melloware** [comment]
I am not sure but I hesitate to randomly subtract 2px when all of the PrimeTek themes are working for me the way I want.   

It feels like a hack to subtract 2px.  But the above workaround should meet your use case just fine.

**Comment by nimo23** [comment]
>I am not sure but I hesitate to randomly subtract 2px when all of the PrimeTek themes are working for me the way I want.

Yes, it's a hack because the problem why `2px` must be substracted is currently unknown..

**Comment by melloware** [comment]
> Yes, it's a hack because the problem why `2px` must be substracted is currently unknown..

That is the mystery!  Something the way jQuery computes the width.

**Comment by melloware** [comment]
Workaround provided
