### ISSUE TITLE
InputNumber: fields not changed when using a ranged slider

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9509]
### Describe the bug

If we have the following 

```
 <p:inputNumber
        id="input1" 
        value="#{bean.min}" 
        decimalPlaces="2" 
        minValue="0" 
        maxValue="100" />
  <p:inputNumber 
        id="input2"
        value="#{bean.max}" 
        decimalPlaces="2"
        minValue="0" 
        maxValue="100" />
  <p:slider 
        for="input1,input2" 
        range="true" 
        step="0.01"
        animate="false" />
```

then `p:slider` is not capable to update the two other input fields according to its slided values. (I know, I can use` p:slider display` with two hidden inputs, but this is not what I need. I need the two input fields be visible.)

### Reproducer
[pf-9509.zip](https://github.com/primefaces/primefaces/files/10230384/pf-9509.zip)

Use something like this:

```
 <p:inputNumber
        id="input1" 
        value="#{bean.min}" 
        decimalPlaces="2" 
        minValue="0" 
        maxValue="100" />
  <p:inputNumber 
        id="input2"
        value="#{bean.max}" 
        decimalPlaces="2"
        minValue="0" 
        maxValue="100" />
  <p:slider 
        for="input1,input2" 
        range="true" 
        step="0.01"
        animate="false" />
```

and use the slider. You will see that the input fields (bound to `p:slider`) are not changed.

### Expected behavior

The input fields (bound to `p:slider`) must be changed when the slider changes.

### PrimeFaces edition

None

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
I think this is an enhancement it was never designed for the ranged slider with multiple input numbers. We have an integration test but it's for a single input number

**Comment by nimo23** [comment]
> We have an integration test but it's for a single input number

I think it would make sense to have it also for multiple "input numbers", because the `p:slider` can be `ranged`, thus it has to take care of all its bound input fields.

**Comment by melloware** [comment]
Yep probbaly it was just never implemented.  PR is welcome you can probably follow what the current single value slider is doing.

**Comment by nimo23** [comment]
Ok, I fixed this in https://github.com/primefaces/primefaces/pull/9511/files.

**Comment by melloware** [comment]
Just tested your fix and its working great.   Here is a MonkeyPatch for others reading this ticket:

```js
if (PrimeFaces.widget.Slider) {
    PrimeFaces.widget.Slider.prototype.setInputValue = function(input, inputValue) {
        if (input.parent().hasClass('ui-inputnumber') || (this.cfg.range === true && input.hasClass('ui-inputnumber'))) {
            var inputNumberId = input.closest('.ui-inputnumber').attr('id');
            var inputNumberWidget = PrimeFaces.getWidgetById(inputNumberId);
            inputNumberWidget.autonumeric.set(inputValue);
        } else if (input.hasClass('ui-spinner-input')) {
            var spinnerId = input.closest('.ui-spinner').attr('id');
            var spinnerWidget = PrimeFaces.getWidgetById(spinnerId);
            spinnerWidget.setValue(inputValue);
        } else {
            input.val(inputValue);
        }
    }
}
```
