### ISSUE TITLE
5.3 p:selectBooleanCheckbox using keyboard

### ISSUE THREAD

**Issue by TinusJackson** [primefaces/primefaces#951]
Using keyboard to check the box doesn't show it is checked visually but are checked when re rendering the page / using submit.( Actual value is checked but not displayed visually) 

Using prime faces 5.3
On 5.1 it is working

**Comment by cagataycivici** [comment]
I can't replicate, can you replicate at;

http://www.primefaces.org/showcase/ui/input/booleanCheckbox.xhtml

If so what are the steps?
