### ISSUE TITLE
InputNumber: Slider cannot be used after typing value

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9513]
### Describe the bug

I have something like this:

```
<p:inputNumber 
		id="input1" 
		value="#{bean.value}" 
		decimalPlaces="2"
		minValue="0"
		maxValue="100" />
<p:slider for="input1" step="0.01" maxValue="100"/>
```

I get the following error when **typing** a value within `inputNumber` and using the `slider` afterwards to change the input number:

```
Uncaught TypeError: a.element is undefined
    jQuery 9
jquery-plugins.js.html:19:256
```

### Reproducer

Use something like this:

```
<p:inputNumber 
		id="input1" 
		value="#{bean.value}" 
		decimalPlaces="2"
		minValue="0"
		maxValue="100" />
<p:slider for="input1" step="0.01" maxValue="100"/>
```

1. Move the slider to the right to change the value.
2. Then edit the changed value manually by typing another value with the keyboard (do NOT slide the value but type the value by keyboard).
3. Then use the slider to change the input value. The value cannot be changed and the following error happens:

```
Uncaught TypeError: a.element is undefined
    jQuery 9
jquery-plugins.js.html:19:256
```

### Expected behavior

The value should be changable by the slider after it was set manually with the keyboard.

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
Please  provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by nimo23** [comment]
I have listed the **Reproducer** above. It's nothing special, a typcial `p:inputNumber`. You cannot reproduce the error (even with a template) if you don't follow the following steps manually:

Use something like this:

```
<p:inputNumber 
		id="input1" 
		value="#{bean.value}" 
		decimalPlaces="2"
		minValue="0"
		maxValue="100" />
<p:slider for="input1" step="0.01" maxValue="100"/>
```


1. Move the slider to the right to change the value.
2. Then edit the changed value manually by typing another value with the keyboard (do NOT slide the value but type the value by keyboard).
3. Then use the slider to change the input value. The value cannot be changed and the following error happens:

```
Uncaught TypeError: a.element is undefined
    jQuery 9
jquery-plugins.js.html:19:256
```

**Comment by melloware** [comment]
But its not runnable.  So you are wasting my time creating the reproducer when you could just provide it for me to download.  We are all volunteers here so you need to respect our time.  If not your tickets will be most likely ignored.

**Comment by nimo23** [comment]
No problem. I wanted to make clear that the reproducer **needs to be read at least** . Only using a `p:slider `within a site does not show the error.. I think putting a `p:slider` by the PF-Team in  a site is a _matter of seconds_ but reading  (and writing and creating this issue **takes longer** - I do also spend time to inform about this bug and give PrimeFaces the chance to improve its lib). So my time is also spend.. 

> If not your tickets will be most likely ignored.

As I said, if PF is not willing or does not care about the quality of its product then PF-Team can ignore or close this issue. I have also spend much time to investigate and write those issues..if PF does not care, feel free to close this issue.

**Comment by jepsar** [comment]
@nimo23 please read https://github.com/primefaces/primefaces#community--elite--pro

By the way, your time is greatly appreciated

**Comment by melloware** [comment]
@nimo23 what you are saying is **your time** is more important than **our time**.  

I think you should re-read https://github.com/primefaces/primefaces#community--elite--pro and consider a PRO account.

**Comment by nimo23** [comment]
>what you are saying is your time is more important than our time.

No, I did not say that. I also appreciate your time. However, I did not want to spend my useless time only to demonstrate such trivial things. The reproducer **in this case** is a matter of seconds because it is nothing special.  A p:slider behaves wrong in some circumstances. No business logic from myself is needed to look at such things. PRO users could also suffer from this bug (or any bug I reported)..or is the PRO version free from this bug?

**Comment by nimo23** [comment]
Btw, @melloware as you are a community member (like me), feel free to ignore this issue and wait for the response of the PF Team. If PF Team decides to resolve this bug, fine. If not, then PF Team should close this issue and leave the bug as it is.

**Comment by melloware** [comment]
@nimo23 I can't reproduce.  Followed your instructions exactly but its working fine.  Here is a reproducer: 
[pf-9513.zip](https://github.com/primefaces/primefaces/files/10241316/pf-9513.zip)

Can you run it and verify?   Maybe I am missing something with your instructions?

**Comment by nimo23** [comment]
@melloware you are right. There is no bug. It was my fault. I had working for the fix of https://github.com/primefaces/primefaces/issues/9509 and forgot to remove the dev code from my page. Works fine.
