### ISSUE TITLE
InputNumber: add property "rotate" (to allow up/down key)

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9514]
### Description

Actually, we can use the mouse wheel or touchpad (up, down) to change the value of the `p:inputNumber.` However, it changes _too fast_ so that the user must adjust the value by typing with the keyboard. It would be reasonable to allow the **up and down key** of the keyboard to change the value of the inputNumber with increments (like a [stepper](https://www.primefaces.org/showcase/ui/input/spinner.xhtml?jfwid=469e8)).

Would be nice to provide the following property for `p:inputNumber`

`rotate` (allows up/down key to change the value) 

### Describe the solution you would like

I want to have something like this:

<p:inputNumber rotate="true"..>

**Comment by melloware** [comment]
Autnumeric handles Up and Down arrow as take you to beginning of field and end of field.  See their docs: http://autonumeric.org/guide

**Comment by nimo23** [comment]
Going to beginning of field and end of field can also be achived by clicking within the position of the input field. Would it make more sense to remap the up/down for changing the values (as this would require more typing than changing the position within the inputField).

**Comment by melloware** [comment]
I suggest you go upvote this issue at AutoNumeric: https://github.com/autoNumeric/autoNumeric/issues/719

**Comment by melloware** [comment]
I have marked this ticket as tracked in a third party library so closing.

**Comment by melloware** [comment]
Fixed with 4.7.0: https://github.com/autoNumeric/autoNumeric/releases/tag/v4.7.0
