### ISSUE TITLE
TabView:  add restoreTabIndex to restore last active tab index

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9517]
### Description

Would be nice to include a property `tabView.restoreTabIndex` which restores the active tab index when `tabView` is rerendered. Actually, users must bind a property and add a listener (with a form enclosed to tabView) (on server side) which is very roundabout. Besides, it is not always appropriate to have a form around the `tabView` when there are also forms within the tabs itself (nested forms are bad..).

### Describe the solution you would like

It would be better to restore the `tabIndex` on **client side** by storing the actual index internally with `onTabChange` and activating this tab (by the stored index) after the `tabView` reInitialized. 

`<p:tabView restoreTabIndex="true" ..>`

**Comment by nimo23** [comment]
I found out that even after the `p:tabView` is rerendered after ajax call, the  `PF('widget_my_tabs').cfg.selected` points **correctly** to the last recently opened tab. However, PF does not use this information even if it's there. I tried it also with binding `onsuccess` to the responding component (which causes the rerendering of the `tabView`) to explicitly call `component.refresh` but it does not help (the internally correctly stored `tabIndex` differs from the `tabIndex` of the component view)

```
restoreTabIndex: function() {
	console.log("this.activeTab = " + this.activeTab);
	var w = PF('widget_my_tabs');
	console.log(w.cfg);
        // not really needed because it already points to the last activated tab index
	w.cfg.selected = this.activeTab; // this.activeTab points to an outer scoped variable which stores the right tab index by `p.tabView.onTabChange`
	console.log(w.cfg); // the cfg has the right index
        w.tabindex = this.activeTab;
        // does NOT refresh the component (the real opened tab differs from activeTabIndex stored in js object
	PF('widget_my_tabs').refresh(w.cfg);
        // does also not enable the right tab, even if this.activeTab points to the right tab index
        w.enable(this.activeTab);
       // does also not help: tab is not updated visually 
	var selected = w.select(this.activeTab);
        console.log(selected); // returns true but tab is not updated visually 
}
```

According to pf documentation, the `tabsWidget.select(this.activeTab);` should be sufficient to switch to the activeTab, but it does not update the visual component in html.

**Comment by melloware** [comment]
Interesting. If I go to the showcase: https://www.primefaces.org/showcase/ui/panel/tabView.xhtml

Open the F12 Console and type `PrimeFaces.widgets.widget_form_j_idt343.select(1);` it selects the 2nd tab correctly.  So I wonder if it a timing issue.  Have you tried this in your code above...

```js
setTimeout(() => {
 w.select(this.activeTab)
}, 500);
```

basically wait 500ms and then select the tab?

**Comment by nimo23** [comment]
>wait 500ms and then select the tab

Indeed, if I use a setTimeout, then it works. 

I also find out that I only need the `setTimeout` if I use the `"onsuccess="restoreTabIndex()"`.

If I use `"oncomplete="restoreTabIndex()"`, then no timeout is needed.

However,one thing that disturbs (regardless if I use `onsuccess` or `oncomplete`), is the visual latency of how the tab is switched: It is visually not fine because the user sees that the tab jumps from index 0 to saved index (of `this.activeTab`).

**Comment by melloware** [comment]
No great but maybe use BlockUI until its all done and you can set he opacity very dark so the tabview updates and switched in the background with the BlockUI blocking it?

https://www.primefaces.org/showcase/ui/misc/blockUI.xhtml

**Comment by nimo23** [comment]
Yes, that would be a workaround..

I am wondering why I cannot use `"onsuccess="restoreTabIndex()"` with the following method:

```
restoreTabIndex: function() {
	var w = PF('widget_my_tabs');
	w.cfg.selected = this.activeTab;
	w.tabindex = this.activeTab;
       // according to PF API, this should refresh the widget with the new index, 
       // however, visually it does not restore the tab 
	w.refresh(w.cfg);
}
```

The `onsuccess` would be ideal, because I can all things before dom update. So changing the cfg of the widget with the new index, should be enough, but it does not work. Or do I misunderstand the use of `widged.refresh(cfg)`?

If we can find a good solution to this, it would be cool to resolve this issue by new PR..

**Comment by melloware** [comment]
Well without debugging it the original Widget UPdate is running through AJAX response cycle and is also calling `onSuccess`. So you are trying to intercept what is already happening in the AJAX response lifecycle which is also calling `refresh`. Just a guess though.

**Comment by nimo23** [comment]
Ok, I think the only solution which works so far is this:

```
restoreTabIndex: function() {
	var w = PF('id_TabView');
		setTimeout(() => {
		w.select(this.activeTab);
	}, 0); // yes, a timeout of 0 is sufficient
```

An ideal PR would be the following:

If user enables `restoreTabIndex`: 

`<p:tabView id="id_TabView" restoreTabIndex="true" ..>`

then the TabView stores the (last enabled) `lastTabIndex` in the `widget.stateHolder.tabIndex` (or an outer scope?) accessing this `lastTabIndex` by a map (`key=id_TabView, value=lastTabIndex`). Then, when PF inits a `TabView`, it looks into the map if its key is stored (referenced by widget-id). If yes, then it sets the `lastTabIndex` from the value of the key. Maybe the `setTimeout` is not needed, when PF handles these things internally. That's it.

**Comment by melloware** [comment]
I am not a fan of storing state outside of the widget so if its going to be fixed the solution should be contained entirely in the `tabView.js`

**Comment by melloware** [comment]
Also have you seen #9054 we do something similar and focus the tab that has an error.

**Comment by nimo23** [comment]
Looking into the code of https://github.com/primefaces/primefaces/issues/9054#issuecomment-1202583279, where is the `focusIndex` (which indicates the tab that has an error) stored? 

Where should we store our `focusIndex`(which in our case indicates the tab that was last activated)? I guess, we cannot use something like `PrimeFaces.widget.TabView.lastFocusIndex`, because PrimeFaces.widget can be re-initialized and all states are then lost. So I can only see a solution to keep the `lastFocusIndex` in an outer scope (e.g. `PrimeFaces.storage.TabView.lastFocusIndex`). Does PrimeFaces maintains a global storage in js?

**Comment by melloware** [comment]
It's in the PR it looks for the first tab with errors on it and makes that focusIndex

**Comment by melloware** [comment]
@nimo23 i thought you mentioned above the `this.activeTab` does have the correct index even after an update?

**Comment by melloware** [comment]
I will investigate this as I think most of the pieces are already there.

**Comment by nimo23** [comment]
>I will investigate this as I think most of the pieces are already there.

@melloware Thanks. I also planned to create a PR. Please consider the following suggestions when fixing this issue:

- add `focusOnLastActiveTab` (or `focusOnActiveTab`) with a default value of "`true`"  (`true`, because if the end-user activates a tab "x" and then afterwards PF (automatically) switches to another tab (due to an ajax response), then this could be classified as a bug by the end-user because the end-user doesn't know, why its explicitly selected tab is no longer selected.)

- if `focusOnError && hasErrors()`, then `focusOnError` should take precedence and `focusOnLastActiveTab` should be ignored

**Comment by melloware** [comment]
I like it.  I will wait for your PR but I agree if focus on error then the error tab should take precedence.
