### ISSUE TITLE
FacesWrapper implementations should push the wrapped instance to the constructor

### ISSUE THREAD

**Issue by BalusC** [primefaces/primefaces#9518]
### Describe the bug

Since JSF 2.3 the default constructor of `FacesWrapper` subclasses has been deprecated in order to force implementors to instead use the constructor taking the wrapped instance (and to raise their awareness), so that logically the inherited `getWrapped()` method will be used throughout the implementation instead of the local `wrapped` variable. This will ensure that the correct implementation is returned and correct behavior is performed might the `FacesWrapper` implementation itself being wrapped by yet another `FacesWrapper` implementation further down the chain. Because, when the `FacesWrapper` implementation incorrectly/accidentally uses the local `wrapped` variable instead of the `getWrapped()` method, then that other `FacesWrapper` implementation will basically be completely ignored, hereby breaking the decorator pattern.

For example, the `PrimeExceptionHandler` of 12.0.0 is implemented as follows:

```
    private final ExceptionHandler wrapped;
    private final Lazy<PrimeConfiguration> config;

    @SuppressWarnings("deprecation") // the default constructor is deprecated in JSF 2.3
    public PrimeExceptionHandler(ExceptionHandler wrapped) {
        this.wrapped = wrapped;
        this.config = new Lazy(() -> PrimeApplicationContext.getCurrentInstance(FacesContext.getCurrentInstance()).getConfig());
    }

    @Override
    public ExceptionHandler getWrapped() {
        return wrapped;
    }
```

This is not entirely correct. It should have been implemented as follows:

```
    private final Lazy<PrimeConfiguration> config;

    public PrimeExceptionHandler(ExceptionHandler wrapped) {
        super(wrapped);
        this.config = new Lazy(() -> PrimeApplicationContext.getCurrentInstance(FacesContext.getCurrentInstance()).getConfig());
    }
```

And wherever the local `wrapped` variable was referenced within the same class, it has to be replaced by `getWrapped()`.

And all other `FacesWrapper` implementations throughout the PrimeFaces library, if any, should follow the same pattern.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
Thank for the feedback @BalusC I will submit a PR for @tandraschko to review.

**Comment by melloware** [comment]
OK all integration tests are passing on Mojarra but failing on MyFaces.

**Comment by BalusC** [comment]
Then MyFaces is somewhere using local wrapped variabele instead of getWrapped(). Now I say this, I remember there's a work around in OmniFaces for this. PartialResponseWriter IIRC.

**Comment by melloware** [comment]
Ok let me look into it thanks for the hint!

**Comment by BalusC** [comment]
It's not the PartialResponseWriter btw, I checked and found it's already fixed in https://github.com/apache/myfaces/commit/9faf5888a6522fa69b0b6cac557b6fb4e0194720. So I can remove that work around in OmniFaces as well.

**Comment by melloware** [comment]
Yep I am debugging this one PF class at a time to see what the cause is.  Will let you know what I find out.

**Comment by melloware** [comment]
Found it. It looks like MyFaces only made those fixes to 2.3-next and to 4.0 branches but not to 2.3.X branch which is what our Integration Tests run on.

https://github.com/apache/myfaces/blob/2.3.x/api/src/main/java/javax/faces/context/ResponseWriterWrapper.java

**Comment by BalusC** [comment]
Ah ok. You might need to maintain same work around in PrimeFaces' PartialResponseWriter. 

It could be removed in the jakartified version.

**Comment by melloware** [comment]
For now I left PartialResponseWriter alone here but all the other changes are now implemented.

**Comment by melloware** [comment]
Reopening this as I need to test with JSF 2.2

**Comment by tandraschko** [comment]
Why no Integration Test? We run on each Spec level

**Comment by tandraschko** [comment]
Why no Integration Test? We run on each Spec level

**Comment by melloware** [comment]
It looks like our nightly Integration Test only runs again 2.3 and 2.3-next for Mojarra and MyFaces.  Nothing against 2.2.

**Comment by tandraschko** [comment]
Then pls add at least 2.2

**Comment by melloware** [comment]
Yep will do.

**Comment by melloware** [comment]
Had to revert. This is all being done to support JSF 2.2 and 2.3 simultanously. The only way we can do this is if we do like OmniFaces  and have 2.x, 3.x, and 4.x branches of primefaces.

We have discussed this in the past: https://github.com/primefaces/primefaces/issues/7813

**Comment by pizzi80** [comment]
@BalusC is this the reason why Primefaces 12 + OmniFaces 4 with `FullAjaxExceptionHandler` does not work correctly?

I have problem with the error page after an error occurred in ajax requests ... 

This behaviour were discussed in another ticket here and it's not completely clear what happens

https://github.com/primefaces/primefaces/issues/8743

**Comment by tandraschko** [comment]
@pizzi80 please create a omnifaces issue, this is not the topic here

**Comment by melloware** [comment]
@tandraschko fixed this today with this commit: https://github.com/primefaces/primefaces/commit/bb36d2329b229168148921b843c359b8737b03ec
