### ISSUE TITLE
p:messages: Add role="alert" 

### ISSUE THREAD

**Issue by TinusJackson** [primefaces/primefaces#952]
Enhancement for accessibility on 5.3 for messages to be reviewed .
Option to add role="alert"  and aria-atomic="true" ?

**Comment by tandraschko** [comment]
Can't this be done with passtrough attributes?

**Comment by TinusJackson** [comment]
No, have tried it but only solution was to insert the attributes using java script. It has multiple divs when rendered. Also tried too wrap it in a div with the attributes didn't work. NB.I am still a beginner and might have done it wrong

**Comment by cagataycivici** [comment]
Should we set these at outmost div? Or for each li element containing message?

**Comment by TinusJackson** [comment]
We fixed this by adding it to the error-message li . Is it possible to add to all li elements for message?

**Comment by melloware** [comment]
@TinusJackson Did you want aria-atomic="true" on all messages regardless of severity?  So INFO, WARN, ERROR, FATAL.  Same with role="alert" or did you want that only on ERROR and FATAL?

**Comment by tandraschko** [comment]
Not sure if the changes are correct.
W3 says:
A message with important, and usually time-sensitive, information. 

i'm not sure if info messages are important.

**Comment by melloware** [comment]
I was wondering whether this should only be for ERROR/FATAL messages and not applied for INFO/WARN.  I can make that change.  Thoughts?

**Comment by tandraschko** [comment]
No idea.
WDYT @cagataycivici / @mertsincan? You are the ARIA pro's :D

**Comment by mertsincan** [comment]
I think we can add the aria-atomic="true" and role="alert" to all messages.
Details;
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
http://webaim.org/techniques/aria/ (Please see Form Validation Example)
