### ISSUE TITLE
FileDownload: Cookie name violates OWASP Rule 941130

### ISSUE THREAD

**Issue by Thomas-Schindler** [primefaces/primefaces#9521]
### Description

Hello,

we are developing an JSF Web Application with PrimeFaces as component library for several customer. One of our new customers uses a Web Application Firewall (WAF) and has now a problem with the generated cookie for the file download. This is set when downloading a file using the <p:fileDownload> component:

`primefaces.download_ui_file_download.xhtml=true; Path=/showcase`

The customer compolains, that the cookie name does not follow his security requirements and hence the request is blocked by the WAF.

Our Customer is using the following regular expression for filtering the cookies:

```
(?i)[\s\S]((?:x(?:link:href|html|mlns)|!ENTITY.?SYSTEM|data:text\\/html|formaction|\\@import|base64)\b|pattern
b.?=)
```
Link to regex tester:  https://regex101.com/r/y4UsMt/1

### Describe the solution you would like

For our customer obviously, the solution would be to use a cookiename not matching the regular expression. But we do not know of course, which other patterns may be used in the world. :-) 

So maybe it would be better to use a UUID or random string generator for generating the cookie name.

**Comment by melloware** [comment]
This is OWASP Rule 941130 and here is the linked WAF test case: https://github.com/fastly/waf_testbed/blob/8bfc406551f3045e418cbaad7596cff8da331dfc/templates/default/REQUEST-941-APPLICATION-ATTACK-XSS.conf.erb#L137-L166

**Comment by Thomas-Schindler** [comment]
Is there already a planned release date for PrimeFaces 13 ?

**Comment by melloware** [comment]
@Thomas-Schindler 13.0 will be a while but I asked for this to be added in 11.0 and 12.0 Elite releases if you are an Elite member.

**Comment by jepsar** [comment]
Shouldn't this be tagged as elite then?

**Comment by Thomas-Schindler** [comment]
@melloware Yes, we are an Elite member, so it would be great for us, if that can be added at least to the next 12.0 Elite release. I planned the switch to 12.0.1 already, but if that issue gets added, I would wait for the 12.0.X Elite release, containing this fix.

**Comment by melloware** [comment]
@jepsar i only tag it as Elite if its related specificlaly to an Elite release I reported this issue through a PRO account and asked for it to be added to 12 and 11.
