### ISSUE TITLE
Table - Resizing column affects other column's width.

### ISSUE THREAD

**Issue by aleckulikouski** [primefaces/primefaces#9522]
### Describe the bug

While using 'Expand Mode' for resizbleColumns resizing one column results in width change column to the left.

### Reproducer

https://www.primefaces.org/primeng/table/colresize

Check 'Expand Mode' table.

### Expected behavior

Only selected column is affected.

### PrimeFaces edition

None

### PrimeFaces version

14.1.2

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by tandraschko** [comment]
This issuetracker is for PrimeFaces, not PrimeNG
