### ISSUE TITLE
PrimeFaces.current().dialog().showMessageDynamic still uses javax. FacesMessage parameter instead of jakarta.

### ISSUE THREAD

**Issue by martingLab** [primefaces/primefaces#9524]
### Describe the bug

The use of 
`PrimeFaces.current().dialog().showMessageDynamic(facesMessage);`
is not possible in Jakarta EE 10 environments as the method showMessageDynamic still refers to the class `javax.faces.application.FacesMessage` instead of `jakarta.faces.application.FacesMessage`

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
When I decompile the JAR the PrimeFaces class is using `jakarta.faces.application.FacesMessage`

![image](https://user-images.githubusercontent.com/4399574/208478165-231e8312-7ca4-4124-92e5-487acddc3674.png)

**Comment by melloware** [comment]
Are you sure your don't have 2 primefaces jars in your classpath?  Sure you are using the `jakarta` version of the Primefaces JAR?

**Comment by martingLab** [comment]
There is only the PF 12.0 jar in the dependencies / libs. Compiling throws the error "class file for javax.faces.application.FacesMessage not found" on the method mentioned.

Is there a separate jakarta version of PF? If so, what are the maven coordinates?

**Comment by melloware** [comment]
Yes, See right on our README.md: https://github.com/primefaces/primefaces#maven
