### ISSUE TITLE
p:column: support title property

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9526]
### Description

`p:column` does actually not support the html standard `title` property

`<p:column title="the column title"../>`

### Describe the solution you would like

Please support the `title` property on `p:column`.

**Comment by jepsar** [comment]
Is it possible to passthrough a title?

**Comment by nimo23** [comment]
Yes, it is possible (`pt:title=""`). But I think, it should be also possible without `pt` as the `title` is a pretty common property..
