### ISSUE TITLE
InputNumber: Ajax-Change-Event not triggered

### ISSUE THREAD

**Issue by stonewoodman** [primefaces/primefaces#9531]
### Describe the bug

If the InputNumber is empty and you type 0 in the field, then no ajax-change-event is fired

```
<ui:composition template="/WEB-INF/template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <f:metadata>
        <f:viewAction action="#{indexController.init()}"/>
    </f:metadata>

    <ui:define name="content">

        <h:form id="form">
            <p:inputNumber id="inputnumber" value="#{indexController.value}">
                <p:ajax process="@this" partialSubmit="true" update="currentValue"/>
            </p:inputNumber>

            <br/>
            Current Value:<br/>
            <h:outputText id="currentValue" value="#{not empty indexController.value ? indexController.value : 'empty'}"/>
        </h:form>

    </ui:define>

</ui:composition>
```

```
@Named
@ViewScoped
public class IndexController implements Serializable
{
    private Double value;

    public void init() {

    }

    public Double getValue()
    {
        return value;
    }

    public void setValue(Double value)
    {
        this.value = value;
    }
}
```

### Reproducer

type 0 and click anywhere
the output label shows empty instead of 0.0

type 5 and click anywhere
the output label shows 5.0

type 0 and click anywhere
label shows 0.0 (correct)

remove the value and click anywhere
label shows empty

if you type 0 again and click anywhere
the output label shows empty instead of 0.0

### Expected behavior

If the input number field is empty and you type 0 then the ajax-change-event is triggered.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11+

**Comment by melloware** [comment]
Might be related to: http://autonumeric.org/guide#emptyInputBehavior

**Comment by stonewoodman** [comment]
No, it is not a display problem.
In backend is the value null and the field is empty. This is correct.
But when I type 0 in the empty field, then no event is triggered.
If I type another number in this empty field, then the ajax event is triggered.
If I type 0 again (with an value in the field), the event is also triggered.
There is only a problem if the value is null and I want to input zero.

**Comment by melloware** [comment]
Reproducer: 
[pf-9531.zip](https://github.com/primefaces/primefaces/files/10270641/pf-9531.zip)

**Comment by melloware** [comment]
I think this might be an AutoNumeric issue or some kind of timing issue when it specifically 0 and empty.  I debugged it but didn't figure out much

**Comment by melloware** [comment]
Here is a workaround for you for now:
```xml
<p:inputNumber 
id="inputnumber" 
widgetVar="wgtInputNumber" 
value="#{testView.decimal}" 
onblur="PF('wgtInputNumber').input.trigger('change');">
```

**Comment by stonewoodman** [comment]
This workaround works.

A little hint:
PF11 works fine. PF12 doesn't anymore.

**Comment by melloware** [comment]
@stonewoodman i think its related to this fix for PF12: https://github.com/primefaces/primefaces/issues/8610

**Comment by melloware** [comment]
MonkeyPatch thanks to @stonewoodman 

```js
if (PrimeFaces.widget.InputNumber) {
    PrimeFaces.widget.InputNumber.prototype.bindInputEvents = function() {
        var $this = this;

        // GitHub #6447: browser auto fill fix
        this.input.off('blur.inputnumber').on('blur.inputnumber', function(e) {
            var element = AutoNumeric.getAutoNumericElement(this);
            if (element && this.value && this.value.length > 0) {
                var newValue = this.value.trim();
                if ($this.cfg.digitGroupSeparator) {
                    newValue = newValue.replaceAll($this.cfg.digitGroupSeparator, '');
                }
                element.set(newValue, null, true);

                // GitHub #8610: reset the raw values so we don't fire change event if 1.0 == 1.00
                if (element.rawValueOnFocus !== '' && Number(element.rawValue) === Number(element.rawValueOnFocus)) {
                    element.rawValueOnFocus = element.rawValue;
                }
            }
            $this.copyValueToHiddenInput();
        });
    }
}
```
