### ISSUE TITLE
DataView: Pagination fills grid except for last page

### ISSUE THREAD

**Issue by dstutz** [primefaces/primefaces#9535]
### Describe the bug

The DataView grid appears to have a mind of its own as far as evenly filling the grid.

Go to https://www.primefaces.org/showcase/ui/data/dataview/lazy.xhtml

The dropdown to select # of items is populated with 6,12 and 16.  6 and 12 appear to work fine because they are evenly divisible by 3 but choosing 16 shows one aspect of what I'm seeing.  If you choose 16 you actually end up with 6 full rows of 3 which is 18 items.   

I noticed if I had a non-lazy DataView grid with 20 total items with rows="10" then it will "steal" 2 more items from the total dataset and display 1-12 even though I've asked for 10, the next page correctly shows just 10 with the last "row" only having a single griditem.

In another example in my application, I have a lazy data model where it's pulling just the required information from the data source then I've noticed it does similar thing on first page and where I have 13 total items and set rows="10" then the LazyDataModel is correctly passing first=0 and maxResults=10 to my load method, and the data source is ONLY returning 10 items but the DataView is displaying 12 grid items.  It ends up repeating the "last" 2 grid items again to fill out the 4th row.

So it's either stealing extra items from the data set(if available) or duplicating ones it has access to to fill the grid on the first page (and probably each one in between?) but the last page correctly shows the remaining 1 or 2 if it's not a full row. 

So I'm not sure if this is intended behavior and we should enforce multiples of 3 for rows in the paging template or this is a defect.

In the documentation for the DataView: https://primefaces.github.io/primefaces/12_0_0/#/components/dataview
* The Ajax Pagination section suggests rowsPerPageTemplate="6,12,16"
* Then just below it in Paginator Template section it has rowsPerPageTemplate="9,12,15" as suggested options.

In any case, the DataView in list view appears to correctly show 10 items as asked.

### Reproducer

https://www.primefaces.org/showcase/ui/data/dataview/lazy.xhtml
choose 16 items per page
End up with 18 items per page

### Expected behavior

Only display 16 items as long as there are 16 or more.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

MyFaces

### JSF version

2.3 (MyFaces 2.3.9)

### Java version

17.0.5-8

**Comment by melloware** [comment]
I just tested the Lazy page and when I pick 16 items per page only 16 appear?  Am I missing something?

**Comment by dstutz** [comment]
Gotta be in grid view?  I count 18.

![image](https://user-images.githubusercontent.com/6010885/209441839-ac07d8be-e5f1-4c40-bfb4-42799827ad1b.png)

**Comment by melloware** [comment]
Got it i was not in Grid view.

**Comment by melloware** [comment]
It looks like it always just keeps an even number...

```java
 int itemsToRender = rows != 0 ? rows : dataview.getRowCount();
int numberOfRowsToRender = (itemsToRender + columns - 1) / columns;
```

int numberOfRowsToRender = (16 + 3 - 1) / 3; // 6 rows

**Comment by dstutz** [comment]
While that might make a certain amount of sense for a datasource that has all the elements available and it can "look ahead" (thought still strange if someone actually counts) such as the showcase example here.  It duplicates items for me with a LazyDataModel backed by a database as described in the initial report since only a single page's worth of items (the number of which is specified by the # of "rows" in the dropdown) is retrieved and that's all that's available at one time in the model.  In that case, the DataView copies 1 or 2 items to "fill in the blanks" and even out the row. 

Here's an example, I have 10 as the row/item count, it's showing 12 items, 2 of which (circled in red) shouldn't be there and are just duplicates of the first 2 in the grid:
![image](https://user-images.githubusercontent.com/6010885/209442731-45a8d983-3558-497d-8ea4-4a181d36e612.png)

I get this is a bit hairy and if the answer is "make your rows multiples of 3", that's fine,  Some sort of documentation update to make that requirement specified/obvious would be helpful in that case.

**Comment by melloware** [comment]
I fixed it.

**Comment by dstutz** [comment]
Thank you very much.
