### ISSUE TITLE
Inplace: does not consider masked text of Password

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9538]
### Description

Currently, the `p:inplace` does not consider to leave the text from an embeeded `p:password` masked (if enabled).

```
<p:inplace>
	<p:password value="#{user.password}" match="pw2" toggleMask="true" redisplay="true" />
</p:inplace>
```

The password is shown by `p:inplace` unmasked even if the `p:password` masks it.

### Describe the solution you would like

If the user has something like this:

```
<p:inplace>
	<p:password value="#{user.password}" match="pw2" toggleMask="true" redisplay="true" />
</p:inplace>
```

Then `p:inplace` should leave the password text masked (in input and output mode). Only when the user toggles the mask by `p:password`, then the password should be unmasked.

**Comment by melloware** [comment]
Yikes that is bad.  Have you tried it without `toggleMask="true" redisplay="true"` to see if one of those two properties is the culprit?

**Comment by nimo23** [comment]
Using this:

```
<p:inplace>
	<p:password value="#{user.password}" match="pw2" toggleMask="false" redisplay="false" />
</p:inplace>
```
or that


```
<p:inplace>
	<p:password value="#{user.password}" match="pw2"  />
</p:inplace>
```
does not help.

The masked text is always unmasked (regardless of the settings of `p:password`) when embedded in `p:inplace`. I think because `p:inplace` just extracts the text from the input field without considering if this is an input field of `type` password.

I think, to resolve this issue, `p:inplace` must look if its embeeded input field is of `type` password or if the component is a `p:password` - if so then it should be masked (if `p:password` sets it to masked), otherwise to unmasked (if `p:password `sets it to unmasked).

**Comment by melloware** [comment]
Agreed.  I will take a look.

**Comment by melloware** [comment]
Reproducer: 
[pf-9538.zip](https://github.com/primefaces/primefaces/files/10279322/pf-9538.zip)

**Comment by melloware** [comment]
I just chose to mask it with "*********" regardless of length of the password.  Unfrotunately the toggleMask is a JS client side property and the InPlacerenderer is a server side component so it has to always be masked.
