### ISSUE TITLE
Schedule Not schowing in SPI Architecture Since PF 5.2

### ISSUE THREAD

**Issue by lucpolak** [primefaces/primefaces#954]
Hello,
I use SPI (Single Page Architecture) in my application. 
http://www.theserverside.com/tutorial/Creating-a-single-page-inteface-SPI-with-JSF-Facelets-Ajax-and-HTML5

I have an issue since i've ugraded to PF 5.2 or 5.3.
The schedule component isn's showing correctly and seems to broke other components when it is loaded using ui:include and AJAX update.
I've read lot of forums saying that fullcalendar/schedule doesn't like AJAX but it works in PF 5.1 and i need to have SPI Architecture.

To reproduce the problem, you can create that simpliest SPI application. I've attached source code.

There are just one bean (MyBean) that manages Navigation and schedule Model.
There are template.xhtml file (facelets template) and main.xhtml file (main page)
Then, there are 2 pages page1.xhtml : just a button to go to page 2
page2.xhtml : the schedule page

To reproduce, create the project and go to /faces/main.jsf page
Click on the Go Schedule button
then , a blank page is rendered. With no JS errors, nothing.
Hit F5 and then only, the schedule is rendered correctly...

Thanks you for support.

**Comment by lucpolak** [comment]
I don't know why but i cannot attach the source code (ZIPfile)
So you can found it via We Transfer : http://we.tl/KEGK8qPxV5

**Comment by lucpolak** [comment]
The source code of the example is attached here : 
[SPI.ZIP](https://github.com/primefaces/primefaces/files/144516/SPI.ZIP)

**Comment by tandraschko** [comment]
Please try with the upcoming 6.1-RC1 next week. If it still doesn't work, please reopen or create a new issue.
