### ISSUE TITLE
AutoComplete: unique=true still displaying item after AJAX update

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9542]
### Description

I have some issues with `p:autoComplete` which are more or less related. 

I use `p:autoComplete` where its visible `selections` should be maintained by custom view and not by `autoComplete.itemLabel`. Thus I nested the `p:autoComplete` within the `facet=header` of a a `p:dataTable`.  

To demonstrate the issue, do the following:
- Type and select "user_1" from the autoComplete box. 
- Then type again and select "user_1" from the autoComplete box.
- As we enabled `autoComplete.unique = true`, only one "user_1" is viewed within the autoComplete-box and the datatable.
- Remove "user_1" from the list by clicking the "X"-button provided within the "dataTable" (Do NOT use the "X" button within the "autoComplete"-box).
- The "user_1" is unselected, however a new null-entry (?) is added and is visible within the "autoComplete"-box (This entry cannot be removed by the user when clicking X within the autoComplete-Box. See image below.). Maybe because PF adds null values into the list?

![Screenshot at Dec 22 22-26-25 23 26 33](https://user-images.githubusercontent.com/3045549/209312283-c1823578-05f1-4049-a03e-057ff019cdde.png)

### Describe the solution you would like

1) Please check why does PF adds a null entry for each duplicate. PF should not add null values into a list. 

2) It would be cool if we can use `p:autoComplete` like this:

```
<p:autoComplete ..

<f:facet name="selectables">
.. custom content for selectables..
Already possible: however it would be cleaner to embeed the custom content within this facet.
</f:facet>

<f:facet name="selections">
.. custom content for selections..
Actually not possible: we can only use "autoComplete.itemLabel". 
The facet "selections" would be an alternative for "autoComplete.itemLabel".
</f:facet>

</p:autoComplete>
```

### Additional context

Reproducer (Version 2):

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10293909/primefaces-test.zip)

**Comment by jepsar** [comment]
Regarding 1: how should the string values of the found items be encoded? I'm pretty sure the converter is needed there.

**Comment by nimo23** [comment]
Regarding 1:

>how should the string values of the found items be encoded?

So `autoComplete` calls at first `public List<User> autocompleteUsers(String query){..}` and then it calls the `converter` to convert _User-to-String_ (i.e.: `UserConverter. getAsString(FacesContext fc, UIComponent uic, User user)`). Or? 

If so, then why is `UserConverter.getAsObject(FacesContext fc, UIComponent uic, String value) ` is called on each keystroke? I cannot see a reason why _String->Object_-conversion is done on each keystroke. I have thought that _String->Object_-conversion is only required when the item is **selected** (or deselected).

**Comment by nimo23** [comment]
Regarding 1:

> how should the string values of the found items be encoded?

Oh, now I understand. The found items which is shown within the autocomplete box as **selectables**. Yes, this makes sense, so `UserConverter.getAsObject(FacesContext fc, UIComponent uic, String value)` is indeed needed on each keystroke to be able to convert the selectables.

"Issue 1" can then be ignored.

**Comment by tandraschko** [comment]
you can just edit the issue and hide the last posts

**Comment by nimo23** [comment]
Ok, I removed _Issue 1_ from this topic and updated the `reproducer.zip`.

**Comment by melloware** [comment]
I think I know what is going on with #2 will investigate.

**Comment by melloware** [comment]
This one is tricky. I can see in the network request after clicking the "X" the server side is sending back the AutoComplete with token 1 still selected.

Also @nimo23 you need to add `java.io.Serializable` to your User class since you are using SessionScoped and then its no longer ":1" you will see the whole "1:user_1".

**Comment by melloware** [comment]
I took a deeper look at this.  You were not doing things the proper "Faces" way and thus by submitting your testView you were causing it to hold onto the values.

Here is a reproducer except  I fixed your `@FacesConverter` to be a CDI converter and injected the Users.

[pf-9542.zip](https://github.com/primefaces/primefaces/files/10325944/pf-9542.zip)

**Comment by nimo23** [comment]
@melloware your reproducer works. So the converter in this case needs to be a "CDI"-managed converter. Good to know. Thanks. 

The original topic of this issue was "_AutoComplete: Provide facets for selectables and selections_", to support something like this:


```
<p:autoComplete ..

<f:facet name="selectables">
.. custom content for selectables..
Already possible: however it would be cleaner to embeed the custom content within this facet.
</f:facet>

<f:facet name="selections">
.. custom content for selections..
Actually not possible: we can only use "autoComplete.itemLabel". 
The facet "selections" would be an alternative for "autoComplete.itemLabel".
</f:facet>

</p:autoComplete>
```

Should I create a new feature request for that or would it be better to reopen and rename this issue again? Would it be even possible to provide those facets for `p:autoComplete `?

**Comment by nimo23** [comment]
@melloware Btw, another (not so clean) solution would be the following:


```
<p:commandButton 
    onsuccess="PF('widget_search_users').removeItem('#{user.id}')"
    icon="pi pi-times" 
    process="@this" 
    update="@form" 
    partialSubmit="true" 
    action="#{testView.removeUser(user)}"/>
```

By using `onsuccess`, we can use a common non cdi managed jsf converter. Well, it's not so clean like your solution, but it also works.

**Comment by melloware** [comment]
I re read it and I am still confused by the need.  You can accomplish everything you want already with columns?   I don't understand the need for facets.

**Comment by melloware** [comment]
Do you have a specific example of what you are trying to accomplish?

**Comment by nimo23** [comment]
I want to have that what is visible in the reproducer but without the need to embeed the autoComplete within a common dataTable.

Actually, it's only possible to visualize the suggestions (=selectables) of p:autoComplete, but it's currently not possible to visualize the selections. We can only use `itemLabel="#{user.id}: #{user.name}"` to visualize the output of the selections. The facet "selections" would be an alternative for "autoComplete.itemLabel" were we also can use columns for the selections. Something like this would be ideal:


```
<p:autoComplete .. 

<f:facet name="selectables">
.. custom content for selectables..
Already possible: however it would be cleaner to embeed the custom content within this facet.
</f:facet>

<f:facet name="selections">
.. custom content for selections..
Actually not possible: we can only use "autoComplete.itemLabel". 
The facet "selections" would be an alternative for "autoComplete.itemLabel".
</f:facet>

</p:autoComplete>
```

**Comment by melloware** [comment]
Ok I think what you are describing is a duplicate of #1903 which has been open for 5+years. Can you confirm?

**Comment by nimo23** [comment]
Oh yes! Open for 5+ years :) This is exactly what is missing in `p:autoComplete`. Look at the following example how nice it would fit:

```
<p:autoComplete 
    placeholder="Select users" 
    id="search_users" 
    scrollHeight="300" multiple="true" unique="true" 
    value="#{testView.selectedUsers}" 
    completeMethod="#{testView.autocompleteUsers}" 
    var="user" itemValue="#{user}" converter="#{userConverter}"
    forceSelection="true" emptyMessage="No users found.">

<!-- set the selectables neatly in a facet ->
 <f:facet name="selectables"> 
	<p:column width="80px">
	    <span>#{user.id}</span>
	</p:column>
	<p:column width="80px">
	    <span>#{user.name}</span>
	</p:column>
</f:facet>

<!-- should be used instead of autoComplete.itemLabel -->
 <f:facet name="selections"> 
	<p:column width="80px">
	    <span>#{user.id}</span>
	</p:column>
	<p:column width="80px">
	    <span>#{user.name}</span>
	</p:column>
       <p:column width="80px">
	    <span>#{user.age}</span>
	</p:column>
</f:facet>

</p:autoComplete>
```

**Comment by nimo23** [comment]
The content of `<f:facet name="selections">`  can be any html which is put below the autoComplete-Box, i.e. in contrast to https://github.com/primefaces/primefaces/issues/1903, the selections is presented below the autoComplete-InputField and NOT within the autoComplete-InputField.

**Comment by melloware** [comment]
Yep instead of opening a new ticket just go upvote that existing issue.
