### ISSUE TITLE
Tree: DragDrop between trees get NPE in TabView DataModel

### ISSUE THREAD

**Issue by lih13800** [primefaces/primefaces#9543]
### Describe the bug

In the TabView with dynamic number of tabs  (DataModel in the showcase http://www.primefaces.org:8080/showcase/ui/panel/tabView.xhtml?jfwid=e3889), drag-drop event between trigger a NullPointerException in **TreeRenderer.java**

```
SEVERE: java.lang.NullPointerException
	at org.primefaces.component.tree.TreeRenderer.decodeDragDrop(TreeRenderer.java:163)
	at org.primefaces.component.tree.TreeRenderer.decode(TreeRenderer.java:67)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:514)
	at org.primefaces.component.tree.Tree.processDecodes(Tree.java:270)
```

```java
Tree otherTree = (Tree) tree.findComponent(separator + dragSource);
otherTree.setRowKey(otherTree.getValue(), rowKey);

```
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java#L162-L163
In the code of **TreeRenderer.java**, "dragSource" is the id of the tree. 
- The TabView with static  tab number provides the correct component path, like this pattern **:staticTabView:testTabForm:tree1**. 
- But TabView with dynamic tab number provides the component path with tab index like this **dynamicTabView:0:testTabForm:tree1** (0  is tab index). 
 
This might be the reason cause the findComponent() method return null value.

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10291469/primefaces-test-master.zip)

### Reproducer

1. Go the lower TabView and select a tab
2. Drag the nodes from one tree to the other one
3. See error 
```
SEVERE: java.lang.NullPointerException
	at org.primefaces.component.tree.TreeRenderer.decodeDragDrop(TreeRenderer.java:163)
	at org.primefaces.component.tree.TreeRenderer.decode(TreeRenderer.java:67)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:514)
	at org.primefaces.component.tree.Tree.processDecodes(Tree.java:270)
```

### Expected behavior

There should be no NPE problem. The expected Result should the same as upper TabView.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

JavaSE-1.8

**Comment by jepsar** [comment]
I don't see a tree and I don't understand what to drag from where to where.

**Comment by melloware** [comment]
@jepsar i was able to reproduce the NPE.

**Comment by melloware** [comment]
Bug is definitely right here:

```java
String separator = Character.toString(UINamingContainer.getSeparatorChar(context));
Tree otherTree = (Tree) tree.findComponent(separator + dragSource);
```
