### ISSUE TITLE
TabView: not rendering anything other than first tab after an ajax update

### ISSUE THREAD

**Issue by unkle-jb** [primefaces/primefaces#9544]
### Describe the bug

In a page with two panels, one with a list and this other with a tabview which is updated after a selection in the list, I cannot get anything besides the first tab in the tabView, as soon as an ajax update for the tabView is triggered (meaning when you first land on the page, everything is fine). 

Looking at the JS console, I do get an error as soon as I click on the list (not clicking on the tab, but on the event updating the tabView):
`Uncaught TypeError: Cannot read properties of undefined (reading 'slice')`

It comes (after some debug), as far as I can tell, from the new behavior in PF12 which sets up some UI of tabs that do have an error (ie the bindRefreshListener method in the tabView.js). 

I overloaded the js in our application with everything besides the call to this function, and it works perfectly (obviously missing the new stuff...). 

### Expected behavior

To be able to render tabs after the first one. 

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### Theme

Barcelona

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

### Browser(s)

Chrome

**Comment by jepsar** [comment]
Please add a reproducer. https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment]
We have a Jakarta EE10 version of PF TEst here already set for Mojarra 4.0: https://github.com/primefaces/primefaces-test/tree/jakarta

**Comment by melloware** [comment]
will close for now @unkle-jb I will re-open when a reproducer is provided...

**Comment by unkle-jb** [comment]
@melloware will do.
For now the reproducer... is not reproducing, so there is somehting I did not get (yet).

**Comment by melloware** [comment]
@unkle-jb that is the great part about the reproducer a lot of times if you can't reproduce it by itself it means there is something else going on with your code!  Let us know what you find out.
