### ISSUE TITLE
Diagram: Inherit UIData

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#9551]
### Describe the bug

It seems the p:diagram does not generate a iterator (uniqueId). 
Therefore all element / components inside a <f:facet name="element"> // MyComponent has the same id.

```xml
<h:form id="automationFlowChartForm">
	<p:diagram id="automationDiagram"
				value="#{myController.model}"
				var="diagramElement">
		<p:ajax event="positionChange"
					listener="#{automationFlowChartView.doSavePosition()}" />
		<f:facet name="element">
			<f:attribute name="element" value="#{diagramElement}" />
			<p:panel id="triggerPanel" >
				<f:facet name="header">
					<h:outputText styleClass="#{diagramElement.icon} Fs11" />
					<h:outputText value="#{diagramElement.name}"
				styleClass="FontBold Fs11" style="margin-left: 10px;" />
				</f:facet>
				<h:outputText id="triggerText" value="TEST" />
			</p:panel>
		</f:facet>
	</p:diagram>
</h:form>
```

This means also a normal actionListener for a element is also not working and I will always get only the first element from p:diagram.
`<p:commandButton actionListener="#{myController.openDialogClicked(element)}" icon="fa fa-edit" />`

<f:facet name="element"> has a unique ID, but all components inside has the same ID.
I would assume a iterator, like in the p:datatable etc.

So for the component inside the `<f:facet name="element">` you have than something like:
`automationFlowChartForm:0:triggerPanel`, for the next panel `automationFlowChartForm:1:triggerPanel`, but currently for all panels you will have:
`automationFlowChartForm:triggerPanel`.
This means also for buttons etc.: if you hover on a button, it will change the color for each button with this ID, because all components are not unique...

I can see this also in the HTML console:
![image](https://user-images.githubusercontent.com/9787533/209464895-a4422715-f88f-4eec-8583-29f3f895868e.png)

Green is the var="diagramElement", but you can see the ID from the panel is always the same.

Can this be fixed?

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.4

### Java version

11

### Browser(s)

Chrome

**Comment by melloware** [comment]
Related to: https://github.com/primefaces/primefaces/issues/8765

And especially: https://github.com/primefaces/primefaces/issues/3781

**Comment by rider87** [comment]
thanks... any plans to fix this?

**Comment by melloware** [comment]
I added this ticket in #8765 so we can track it there.  But to fix this if I had to guess would involve extending `UIData` instead of `UIComponent` or something along those lines which is not a simple fix.

**Comment by jepsar** [comment]
@rider87 please read https://github.com/primefaces/primefaces#community--elite--pro

**Comment by melloware** [comment]
I am going to close this one. @rider87 please subscribe to #8765

**Comment by melloware** [comment]
Re-opened but this likely won't be fixed unless the component is completely re-written.

**Comment by melloware** [comment]
Same as #10762
