### ISSUE TITLE
DataTable: selectionPageOnly='false' with disabledSelection is selecting disabled rows also

### ISSUE THREAD

**Issue by nikolica666** [primefaces/primefaces#9552]
### Describe the bug

When using `p:dataTable` with attributes `selectionPageOnly="false"` and `disabledSelection` when request is submitted on serverside every element from `value` is set to `selection` (both disabled and enabled).

You can observer that in `selection`'s setter already.

This does not happen if `selectionPageOnly="true"`

Edit: I forgot to say this is specific to "select all" checkbox that is generated in header in `<p:column selectionMode="multiple" />`, if enabled rows are clicked "one-by-one" it is working fine ofcourse.

### Reproducer

ViewScoped bean:

```
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class MyBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private List<String> all = Arrays.asList("string1","string2","string3","string4","string5");
	private List<String> selected;
	
	public void doSomething() {
		System.out.println("Size of selected rows is " + selected.size());
	}
	public List<String> getAll() {
		return all;
	}
	public List<String> getSelected() {
		return selected;
	}
	public void setSelected(List<String> selected) {
		this.selected = selected;
	}
}
```

XHTML:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui">
<h:head />	  
<h:body>
	<h:form>
		<p:dataTable value="#{myBean.all}" var="s" selection="#{myBean.selected}" 
			disabledSelection="#{true}" selectionPageOnly="false"
			rowKey="#{s}">
			<p:column>#{s}</p:column>
			<p:column selectionMode="multiple"></p:column>
		</p:dataTable>
		<p:commandButton value="Process" action="#{myBean.doSomething}" process="@form" update="@form" />
	</h:form>
</h:body>	  
</html>
```

### Expected behavior

Only enabled rows to be selected.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Saga

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

1.8

**Comment by melloware** [comment]
I think this is your issue: https://github.com/primefaces/primefaces/issues/9357

It was fixed in 12.0.2 Elite release

**Comment by jepsar** [comment]
@melloware you might also want to answer https://stackoverflow.com/questions/74908888/primefaces-12-0-0-datatable-disabledselection-behaviour

**Comment by melloware** [comment]
OK nope here is a reproducer its still happening on 13.0: 
[pf-9552.zip](https://github.com/primefaces/primefaces/files/10303443/pf-9552.zip)

**Comment by melloware** [comment]
OK it was similar to #9357 but in a different spot
