### ISSUE TITLE
Timeline class method not found in Primefaces8

### ISSUE THREAD

**Issue by vinayadhikari** [primefaces/primefaces#9554]
### Describe the bug

Hi,

We are migrating our Primefaces application from version 6.0 to 8.0 and in the 6.0 version we are using org.primefaces.component.timeline.Timeline class
After upgrading the project version to 8.0 few methods of the Timeline class are not found, below is the list of methods not found:
- getDragAreaWidth()
- isUnselectable()
- isGroupsOnRight()
- getGroupMinHeight()
- getGroupsWidth()
- isShowButtonNew()
- isShowNavigation()
- isAnimate()
- isAnimateZoom()

### PrimeFaces edition

Community

### PrimeFaces version

8.0

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

8

**Comment by tandraschko** [comment]
I think the forum, discord or discussion is the better place for this
we have a migration guide here for different versions: https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/migrationguide

see especially: https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/8_0?id=timeline

**Comment by melloware** [comment]
@vinayadhikari especially this on Timeline: https://primefaces.github.io/primefaces/12_0_0/#/../migrationguide/8_0?id=timeline
