### ISSUE TITLE
DataTable: disabledSelection is not working properly

### ISSUE THREAD

**Issue by ngrbinh** [primefaces/primefaces#9555]
### Describe the bug

There are two problems:
1. Before (Primefaces 8), selection-disabled rows will have their checkbox disabled and "grey" like this:

![image](https://user-images.githubusercontent.com/43273921/209656401-1677b3ac-2420-4496-bfbf-03717e4e09b2.png)

But now (Primefaces 12), the check box is disabled but not grey anymore:

![image](https://user-images.githubusercontent.com/43273921/209656583-41a6559b-1164-428e-862d-6f39a38daba1.png)

Please note that the row selection is disabled (checkbox cannot be checked), just the UI look wrong. The problem seems to be because of the class "ui-state-disabled" is now missing in disabled row's checkbox

2. When I have some selection-disabled row in my table, if I select all other non-disabled row, the header checkbox is not automatically checked

### Reproducer

1. Run the attached projects
2. Go to http://localhost:8080/primefaces-test/
3. Bug#1: You can see that the checkbox with age >=35 is disabled, however in the UI they look the same.
4. Bug#2: Check all available checkbox, see that the checkbox in header is not auto achecked.
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10307693/primefaces-test.zip)

### Expected behavior

1. The checkbox should be grey when it's disabled.
2. If all non-disabled checkbox was checked, the header checkbox should be check too.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

1.8

**Comment by jepsar** [comment]
Can you please test with 13? Please see #9552

**Comment by melloware** [comment]
I can confirm both issues are fixed in 13.0.

#9552 and #9429
