### ISSUE TITLE
DatePicker: time selector with 12 hour format only working in english locale

### ISSUE THREAD

**Issue by ybendek** [primefaces/primefaces#9559]
### Describe the bug

I'm trying to use the datePicker component with the time selector enable for an app that is supporting multiple locales. The problem arise when the datepicker is using the attribute hourFormat="12" to have the option to select  AM/PM. 

If you have a locale in english it works without a problem, however as soon as you have another locale (like 'es' or 'de') the following error is showed in the browser's console and the component is broken and not able to select date or time date.

![image](https://user-images.githubusercontent.com/13785120/209755284-c14e5293-f49f-4cf4-a36e-8167a55af5b2.png)

### Reproducer

As soon as you execute this small project you have the webpage with 4 datepicker examples, the first two fails because both has the hourFormat="12" and a locale in spanish or german.

The other 2 works but because has the locale in english or has not included the hourFormat="12" 

[pf-9559.zip](https://github.com/primefaces/primefaces/files/10314933/pf-9559.zip)

### Expected behavior

All the locales should support AM/PM or 12 hour time selector.

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.9

### Theme

RAIN

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

JDK 11 - AWS Correto

**Comment by jepsar** [comment]
Can you please try with 13 SNAPSHOT?

**Comment by melloware** [comment]
All 4 work fine for me using PF 11 or 12.

[pf-9559.zip](https://github.com/primefaces/primefaces/files/10314399/pf-9559.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

**Comment by ybendek** [comment]
> All 4 work fine for me using PF 11 or 12.
> 
> [pf-9559.zip](https://github.com/primefaces/primefaces/files/10314399/pf-9559.zip)
> 
> Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

I'm sorry, but how is your example supposed to work if

The xhtml file has a reference to a bean not registered in the package?
![image](https://user-images.githubusercontent.com/13785120/209833951-cc0ec745-a1bb-438a-af85-a7bf365c8fdb.png)

![image](https://user-images.githubusercontent.com/13785120/209834111-e766d7b0-f026-4e7a-baa3-3f947a078635.png)

BTW, I was trying to find an example in the primefaces showcase hoping that with the locale selector included could I test my issue. However none of the examples for time pickers include a 12 hour format to select AM/PM

**Comment by melloware** [comment]
I updated my example.   I copied and pasted from your non working non runnable example.
[pf-9559.zip](https://github.com/primefaces/primefaces/files/10314933/pf-9559.zip)

Next time please use PrimeFaces Test like I did...

**Comment by melloware** [comment]
Looks similar to this issue: https://github.com/primefaces/primefaces/issues/8365

**Comment by melloware** [comment]
The server side language translation for `java.time` is making the AM PM localized values but the client side JS code is looking for AM/PM.

Java Local for Time/Date for `es`.

ES = a. m., p. m. : https://www.localeplanet.com/java/es-ES/index.html

EN = AM/PM : https://www.localeplanet.com/java/en-US/index.html

And I believe we are deferring to the JDK to do the `java.time` formatting. 

On the client side the JavaScript is doing this....
```js
populateTime: function (value, timeString, ampm) {
    if (this.options.hourFormat === '12' && (ampm !== 'PM' && ampm !== 'AM')) {
        throw new Error('Invalid Time');
    }
```

**Comment by ybendek** [comment]
> The server side language translation for `java.time` is making the AM PM localized values but the client side JS code is looking for AM/PM.
> 
> Java Local for Time/Date for `es`.
> 
> ES = a. m., p. m. : https://www.localeplanet.com/java/es-ES/index.html
> 
> EN = AM/PM : https://www.localeplanet.com/java/en-US/index.html
> 
> And I believe we are deferring to the JDK to do the `java.time` formatting.
> 
> On the client side the JavaScript is doing this....
> 
> ```js
> populateTime: function (value, timeString, ampm) {
>     if (this.options.hourFormat === '12' && (ampm !== 'PM' && ampm !== 'AM')) {
>         throw new Error('Invalid Time');
>     }
> ```

Yeap, that is exactly the same Exception I have, it looks that the client side assumes that always receives AM/PM. But if you have a different locale like spanish or german, you will receive another value

**Comment by ybendek** [comment]
As workaround the only way I found is to just hardcode in the locale of the datePicker component the "en", but Obviouslly with that I will lose the translations of labels :(

**Comment by melloware** [comment]
@jepsar  i am almost thinking we need two more locale.js labels for AM and PM since they are different per locale and thus cause the above issue. or we need to pass the AM PM from the Java Locale through the widget?  I am thinking the second option is better as it always has to match what the client will be using?

**Comment by jepsar** [comment]
We are already using a JS locale file, right? I would use that to keep things uniform.

**Comment by melloware** [comment]
Let me submit a PR for you to review.
