### ISSUE TITLE
Make similar UI components for native android and iOS

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#9560]
### Description

Make similar UI components for native android and iOS.
Android lacks rich UI components such as tree-like menu, accordion, etc.

### Describe the solution you would like

Android native UI project.
iOS native UI project.

These UI components for native mobile apps.

**Comment by tandraschko** [comment]
this is out of scope of PrimeFaces as OpenSource project here - i would contact PrimeTek directly via mail
