### ISSUE TITLE
Title Column Re-sizer blue line is appearing even after the mouse click is released in Table

### ISSUE THREAD

**Issue by Charmi-webosmotic** [primefaces/primefaces#9565]
### Describe the bug

Title Column Re-sizer blue line is appearing even after the mouse click is released in Table

Click on the column expansion line by using both the mouse(right & left) clicks and drag the mouse. Then release the mouse clicks. The blue highlighter line is still present and not disappearing in prime ng p-table component.

https://www.loom.com/share/70303831c08d4068b36cfa6798d803d1

### PrimeFaces edition

Community

### PrimeFaces version

"primeicons": "^5.0.0", "primeng": "^13.1.0",

### Browser(s)

Chrome (mac)

**Comment by jepsar** [comment]
Wrong repo. This is PrimeFaces.
