### ISSUE TITLE
Alignment and formatting problems in Primefaces extension exporter

### ISSUE THREAD

**Issue by ron221683** [primefaces/primefaces#957]
I have implemented Export functionality for a table having subtable, grouping and customized format using primefaces Extension Exporter. I have followed the demo provided on following link:

http://www.primefaces.org/showcase-ext/sections/exporter/customizedFormatTable.jsf

1) On exporting excel, the Sheet shows header background in one extra column of right. It happens for only those headers which implemented using f:facet. It also seems in exported sheet of demo as well.

2) I tried the header column alignment using the following demo:

http://www.primefaces.org/showcase-ext/sections/exporter/columnAlignments.jsf

It works good for column having h:outputText. However for header columns using p:columnGroup, its not aligning as expected for excel and PDF.

Please provide solutions for the above scenarios.

**Comment by tandraschko** [comment]
please use the primefaces-extensions github issue tracker.
