### ISSUE TITLE
Column: filter facet of frozen not working

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9571]
### Describe the bug

facet type "filter" of a column is not working 
when this column is a **frozen** column.

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10329129/primefaces-test.zip)

### Expected behavior

filter should work.

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
Once again a misconfiguration. When a table has "frozen" columns it must be `scrollable="true"` else there is no point in freezing columns.

Once you set `scrollable="true"` your demo works fine.

**Comment by melloware** [comment]
I am adding a backend exception so no one else runs into this in the future.
