### ISSUE TITLE
DataTable: support headerRow in combination with frozenColumns

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9572]
### Describe the bug

 This reproducer demonstrates the following issues when `dataTable` has `frozenColumns` in combination with `headerRow`:

- The dataTable has two headerRows.
- The toggle toggles the frozen and unfrozen part separately.

### Reproducer

[primefaces-test-jakarta.zip](https://github.com/primefaces/primefaces/files/12352674/primefaces-test-jakarta.zip)

### Expected behavior

- The dataTable should have only one headerRow (if activated).
- The toggle should toggle the whole rows (belonging to the group) 

### PrimeFaces edition

Community

### PrimeFaces version

13

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

Firefox 115

**Comment by melloware** [comment]
I am pretty sure this is not allowed.  Frozen columns was not designed for this use case it was meant for a very specific case.  

PrimeTek's answer this in the past has been "not all features of the datatable are designed to work together" and I think this is the case here.  

@tandraschko @Rapster can chime in here but I don't this would be addressed by the community and only through PRO support request to PrimeTek.

**Comment by nimo23** [comment]
@melloware Can you reopen this issue?

I looked briefly into the html code how PF constructs its fixed columns. It seems it duplicates the rows (which needs to be frozen=sticky) and appends thows rows to the origin table. Maybe we can find a solutions solely with css `position: sticky;` so that all columns which needs to be frozen adds a css class "column-sticky". However, I don't know if such simple solution is sufficient as PF dataTable can have other requirements why it duplicates its (frozen) columns..

If we can replace the PF implementation of `frozenColumns` by `position: sticky;` instead of adding duplicate rows (to imitate sticky columns), then this issue can be resolved more easily (because we do not have two headerRows afterwards and can also use `position: sticky;` for the headerRow..

**Comment by melloware** [comment]
`position:sticky` won't work.  See: https://github.com/primefaces/primefaces/issues/6410

There is too much dynamic JS code involved and position sticky requires a static `top` value.

**Comment by nimo23** [comment]
>position sticky requires a static top value.

But the static top can be calculated within css, or? Maybe adding inline style to the dedicated component by js with something like:

```
postion: sticky;
top: calc(0 + 140px);
```

**Comment by melloware** [comment]
You can try it!

**Comment by melloware** [comment]
@nimo23 its been months since our last conversation on this ticket and I see you made no progress. For now I will mark as not supported but will be happy to re-open if you provide a PR.
