### ISSUE TITLE
Calendar: pattern="MMM yyyy" and with maxdate  and mindate attributes are not working together

### ISSUE THREAD

**Issue by vineethkuthyala** [primefaces/primefaces#9574]
### Describe the bug

Calendar with **pattern="MMM yyyy"**  along with mindate and maxdate attribute 
unable to select date between max-date and min-date

### Reproducer

```
<p:calendar maxlength="280" size="50" id="month"
								value="#{inventoryBean.expDate}" pattern="dd MMM yyyy"
								`mindate="#{util.getCurrentDate()}"`
								maxdate="#{inventoryBean.expMaxDate}" navigator="true">
	</p:calendar>
```

### PrimeFaces edition

None

### PrimeFaces version

8.0

### JSF implementation

Mojarra

### JSF version

5.0

### Java version

17

**Comment by tandraschko** [comment]
some notes here:
1) please test with the newest version, everything else is not supported here: https://github.com/primefaces/primefaces#community--elite--pro
2) What is JSF 5.0?
3) we need a reproducer

**Comment by melloware** [comment]
Will close until a reproducer is provided
