### ISSUE TITLE
Tree: Wrong node order because of #8693

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces/primefaces#9575]
### Describe the bug

The change in #8693 breaks the drag and drop of items in the same list. 

For a reproduces take the showcase:
In src/main/webapp/ui/data/tree/dragdrop.xhtml
change the update from ":form:msgs" to ":form".

Drag Node0 between Node1 and Node2. Node0 stays for a short while there. 
With the update coming back the Node0 is moved one Node up.

IMHO the changes done because of #8693 must be reverted. 

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
@OBreidenbach i think @stonewoodman original issue is still valid so reverting it would cause that not to work I just think the fix needs to be more comprehensive no?

**Comment by OBreidenbach** [comment]
I used @stonewoodman reproducer and added an 
<p:ajax event="dragdrop" update="@form"/> and see the same wrong behavior I described above for the altered showcase.
In our project we are using the tree at least for 5 years. It worked all the time. Now with PF 12 it is broken.

On client side, the the new index figured out, after the node is removed from the previous position. So the right index is already transfered with the request. No need to do any after math on the server side. 

I do not understand what @stonewoodman problem was, but I am pretty sure that the change must be reverted.
May be @stonewoodman can have a second look at his reproducer.

**Comment by melloware** [comment]
@OBreidenbach submit a PR reverting that change and I will approve it.

**Comment by OBreidenbach** [comment]
Okay, will do. Are you interested in keeping those added test methods in TreeNodeChildrenTest?

**Comment by melloware** [comment]
I would say remove what you have to but leave it if you don't need to remove
