### ISSUE TITLE
Timeline: cancelAdd() not always working

### ISSUE THREAD

**Issue by HKM-CIA** [primefaces/primefaces#9576]
### Describe the bug

cancelAdd() does not suppress item creation if select event is additionally bound and doubleclick is on existing item

### Reproducer

doubleclick inside timeline to add an item whose creation should be suppressed by 'cancelAdd()'
if doubleclick is in free area cancelAdd is called and item is not created
if doubleclick is on existing item cancelAdd is called but item is nevertheless created 

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10332062/primefaces-test.zip)

### Expected behavior

cancelAdd should always suppress item creation

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

**Comment by melloware** [comment]
You are right. I am stepping through the debugger and I can see it calls the Cancel in the one scenario but on clicking on an item it runs the OnAdd first then calls your CancelAdd but its too late.  Must be some ordering of the events in the timeline.

**Comment by melloware** [comment]
I do think I have a workaround for you to try.  Can you try adding `async="true"` to the onAdd.

```xml
<p:ajax event="add" onstart="PF('timelineWidget').cancelAdd();" async="true" />
<p:ajax event="select" async="false"/>
```

**Comment by HKM-CIA** [comment]
Thx for your quick reply!
This changes the event ordering and solves my problem.

**Comment by melloware** [comment]
I am not sure we can possibly fix it better than that since its some kind of timing issue inside the timeline itself so I am going to close this ticket as a workaround has been provided!
