### ISSUE TITLE
SelectManyButton ItemValue lost its value once the form is submitted and refreshed

### ISSUE THREAD

**Issue by X452-625** [primefaces/primefaces#9578]
### Describe the bug

I have a form with a dataTable which contains a selectManyButton in the header with value set with `f:selectItem`
 `<input type="checkbox" value="value1" checked="checked">`
I click to the link href, the form is submitted and page is refreshed. 
However the value of all inputs corresponding to the selectItems doesn't have any value anymore
 `<input type="checkbox" value checked="checked">`

### Reproducer

```xml
<h:form id="loginForm">
    <p:dataTable>
        <p:column>
            <p:selectManyButton value="#{form.selectedValue}">
                <f:selectItem itemValue="value1" />
                <f:selectItem itemValue="value2" />
            </p:selectManyButton>
            <p:outputLabel ..../>
        </p:column>
    </p:dataTable>
    <a href="#" onclick="document.forms['loginForm'].submit(); return false;">Click</a>
</h:form>
```

### Expected behavior

Value need to be set properly after the form is submitted

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.2

### JSF implementation

MyFaces

### JSF version

3.0.0

### Java version

11.0.15

**Comment by tandraschko** [comment]
Please provide a primefaces-test reproducer

**Comment by Rapster** [comment]
Looks like more of a forum/stackoverflow issue... I don't see how `javax.faces.partial.execute` post param will be sent to the server this way. ` <a href="#" onclick="document.forms['loginForm'].submit(); return false;">Click</a>` is not really the way to do in JSF

PS: Learn how to format code on github please :wink:

**Comment by melloware** [comment]
Agree with @Rapster   this is NOT how you do a JSF login form.

**Comment by X452-625** [comment]
My mistake, the code `<a href....` is the code generated. The actual code is : 
```
<h:form id="loginForm">
    <p:dataTable>
        <p:column>
            <p:selectManyButton value="#{form.selectedValue}">
                <f:selectItem itemValue="value1" />
                <f:selectItem itemValue="value2" />
            </p:selectManyButton>
            <p:outputLabel ..../>
        </p:column>
    </p:dataTable>
    <h:commandLink action="#{...}" id="actionSave"  />
</h:form>
```

However I do think it's an issue since PF 12 since I didn't have this behavior prior to this version.

**Comment by jepsar** [comment]
Reason all the more to create a minimal reproducer using https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment]
@X452-625 without a PrimeFaces Test reproducer its impossible for us to debug your exact issue if we can't see it.
