### ISSUE TITLE
TreeTable: Add frozenColumns

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9579]
### Description

It would be nice to support `frozenColumns` on `TreeTable` to have something like this:

```
<p:treeTable 
    scrollable="true" 
    scrollWidth="350" 
    frozenColumns="1">
..
</p:treeTable>
```

Currently, the navigation part (= the toggle from the first column) cannot be fixed when scrolling horizontally, which can lead to the navigation part disappearing and only becoming visible again by scrolling back. It would be perfectly sufficient if at least the first column (= the toggle part) could be fixed.

### Describe the solution you would like

Provide `frozenColumns` for `p:treeTable`.

### Additional context

I tried to bypass this issue by using a `p:dataTable` with `frozenColumns` and `headerRow`. However, as described in https://github.com/primefaces/primefaces/issues/9572, `p:dataTable` does not support the combination of `frozenColumns` and `headerRow`.

**Comment by tandraschko** [comment]
I dont think that will happen without sponsoring

**Comment by melloware** [comment]
I agree with Thomas. Frozen is very complex and not likely to be donated by a community member

**Comment by nimo23** [comment]
It would be nice to add a new tag called "**Sponsoring required**" for issues like that. It has the following benefits:

- We (and the PF core team) can find and track all issues where sponsoring is required.
- You, as a community member, does not need to explain it over and over again to another community member why this issue is unlikely to be solved by a community member.
- Issues can be kept open with a **“Sponsoring Required”** label instead of closing it silently. For example, the issue https://github.com/primefaces/primefaces/issues/9572 is in fact a limitation (which is also not well documented in the official documentation). Users may also have this issue in the future. But if you close this issue, the issue is gone and nobody can contribute (or sponsor) if they want to. So it's better to leave such issues open with a tag **“Sponsoring Required”**. Don't you think so?

**Comment by tandraschko** [comment]
done

**Comment by melloware** [comment]
Replaced by https://github.com/primefaces/primefaces/issues/11250
