### ISSUE TITLE
DataTable: improve empty space handling of scrollable DataTable

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primefaces#958]
Hi,

```
When we have less number of records in vertical scrollable table then it has empty space between content and footer section.This can be replicated on showcase with less number of records as below.
```

![image](https://cloud.githubusercontent.com/assets/3127317/11838657/7991f164-a40e-11e5-883b-86b98d019c98.png)

Regards,

**Comment by sudheerj** [comment]
Ofcourse the workaround is conditionally declare scrollheight based on number of records.

**Comment by kukel** [comment]
And how **should** it behave? Shrink? Or populate the free space with zebra-striped empty and non-selectable rows? The latter is not that difficult (I did it once). And it would even be easier if PF used css odd/even selectors with (either via real css or applying via jquery
) instead of applying odd/even in the renderer

**Comment by mtbadi39** [comment]
_populate the free space with zebra-striped empty and non-selectable rows_ :) **I agree**

**Comment by sudheerj** [comment]
In that case it shoudn't show any empty space.In my opinion when there are no records why we need free space with zebra-striped empty and non-selectable rows.

**Comment by kukel** [comment]
Because it is 'good practice' In UX. It creates a less 'jumpy'/'flashy' userinterface. Things stay at the same place  (e.g. datatable footers ,column footers, paginator at the bottom etc...)

**Comment by mtbadi39** [comment]
@kukel : +1
May be in non-responsives pages, it is preferable that dataTable to occupy all available space with no care for the number of records.

**Comment by mauromol** [comment]
I think there are cases in which the useless wasted space is unwanted, even if it may produce a "jumpy" UI (the web is full of such kind of things, anyway...).
Having an option to either fill the empty space with empty rows or rather shrink the table would be a useful feature for me. For both dataTable and treeTable.
Here is my CSS workaround to make the table shrink:
http://forum.primefaces.org/viewtopic.php?f=3&t=42088&p=150132#p150132

**Comment by kukel** [comment]
I still have a client-side jquery based 'patch' for this. I'll look for it and try to create a PR. Most of the complexity is in the usage of the `odd-row` and `even-row` classes that PF (or rather jquery) uses. Using nth-child selectors would have made it easier. Not sure if jquery 3 still uses these but it might be the right time for PF to switch.

**Comment by melloware** [comment]
@tandraschko @kukel I believe this issue was fixed with this ticket:  https://github.com/primefaces/primefaces/issues/4357  It can be marked for 6.3
