### ISSUE TITLE
TreeTable:  selectionMode="multiple" and NO selection="" atribute results in error after upgrade 

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#9584]
### Describe the bug

Before upgrade PF from 10.0.X  to 11 or 12,  ` <p:treeTable>`   with  `selectionMode="multiple` and without  `selection="" ` atribute  works fine.... but now return an error because  of `org.primefaces.component.treetable.feature.SelectionFeature ` Class: 
```
  @Override
    public void decode(FacesContext context, TreeTable table) {
        boolean multiple = table.isMultipleSelectionMode();
        Class<?> selectionType = table.getSelectionType();  //  <<< IS NULL HERE
        TreeNode root = table.getValue();

        if (multiple && !selectionType.isArray()    // <<<<<      NPE HERE
          ...            
```

I was using this just for user view experience  like  click & mark background in each row selected... without any server rules based on that selections...  Should  this behaviour be restored?  

_I'm using 12.0.2 elite version, but problem appears after upgrade to 11.0.0 or above._

### Expected behavior

Still allowing multipleSelect="multiple" even when no selection="" attribute is specified.

### PrimeFaces edition

Community

### PrimeFaces version

>= 11.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

**Comment by melloware** [comment]
OK so I fixed the NPE but you will still get an error.  I made it match what Datatable is doing in SelectionFeature.

```java
if (multiple && selectionType != null && !isArray && !List.class.isAssignableFrom(selectionType)) {
      throw new FacesException("Multiple selection reference must be an Array or a List for TreeTable " + table.getClientId());
}
```

So now you will get the above error message if `selectionType=""`.  Just because this worked in previous versions of PrimeFaces was actually a "bug" or a "loophole" that has been closed.  So you should use an empty List at the very least.

**Comment by edudoda** [comment]
Thanks fot this,  with this correction now I hope not see any errors at all (as well as in Datatable),  because in fact I'm not even specifying   `selection=` attribute in both cases,  when I said NO  selection="" I wasn't mention an empty one, just that they are not even mentioned.

**Comment by melloware** [comment]
I have a feeling you will still get an error but I haven't tried it you will just get a "good error" telling you whats wrong.  You can try it with datatable now in 12.0.2 and see what happens.
