### ISSUE TITLE
Schedule: add eventDblSelect

### ISSUE THREAD

**Issue by ron-hoppe** [primefaces/primefaces#9586]
### Description

I implemented to delete button from the Schedule Extender like shown in the Showcase. No I have the problem, that I open a p:dialog on the ajax eventSelect event which will also be called when I try to delete the event. In order to delete the event without my dialog being opend it would be nice, to only open my dialog on a double click of the event. So far I could not find any implementation of the double click on the event. 

The solution could be very simular to the dateDblSelect like shown here https://github.com/primefaces/primefaces/commit/8ce2a2c5c6de5f464bc90c2ca834fb1e583dce5c)

### Describe the solution you would like

Probably it could be a new feature.
It would be excellent if the <p:schedule...> would support something like "eventDblSelect". It would increase the user experience.

**Comment by melloware** [comment]
Yep it would need that exact same kind of double click logic.
