### ISSUE TITLE
BlockUI: incorrect overlay position for block with padding

### ISSUE THREAD

**Issue by chisogch** [primefaces/primefaces#9588]
### Describe the bug

When a blocked element uses padding, the overlay is displayed incorrectly. The size is correct but the position should be shifted.
The behavior is correct when the padding is 0.

### Reproducer

The issue can be reproduced with the showcase of PrimeFaces 12:

1. Open the blockUI showcase (PrimeFaces 12): https://www.primefaces.org/showcase/ui/misc/blockUI.xhtml
2. Open developer tools to update the CSS (add padding on the blocked elements)
3. Example CSS for Basic: `body .ui-panel { padding: 20px; }`
4. Example CSS for Custom Content: `div.ui-datatable { padding: 20px; }`
5. Check if the Basic overlay covers the panel (Save button).
6. Actual result: Basic overlay size is OK but position should move (to bottom right)
7. Check if the Custom Content overlay covers the table (row navigation buttons)
8. Actual result: Custom Content overlay size is OK but position should move (to bottom right)

### Expected behavior

In both cases (Basic or Custom Content):

- The overlay should cover the blocked element (panel or table)
- The overlay position should take the padding into account (using outerWidth/Height rather than width/height)

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

Chrome 108.0.5359.125

**Comment by chisogch** [comment]
The related function is alignOverlay() in blockui.js

Here's the current code for PrimeFaces 12:

> var height = currentTarget.height(),
	width = currentTarget.width(),
	offset = currentTarget.offset();

The following workaround seems to do the trick (using the outer witdth/height instead):

> height = currentTarget.outerHeight();
width = currentTarget.outerWidth();

**Comment by jepsar** [comment]
BlockUI was touched in 13, see #9496.

Can you please see if this issue is still there with 13 (SNAPSHOT)?

**Comment by melloware** [comment]
Thanks for the report here is a MonkeyPatch you can use:

```js
if (PrimeFaces.widget.BlockUI) {
    PrimeFaces.widget.BlockUI.prototype.alignOverlay = function() {
        this.target = PrimeFaces.expressions.SearchExpressionFacade.resolveComponentsAsSelector(this.cfg.block);
        if (this.blocker) {
            this.blocker.css('z-index', PrimeFaces.nextZindex());
        }

        //center position of content
        for (var i = 0; i < this.target.length; i++) {
            var currentTarget = $(this.target[i]),
                blocker = $(this.blocker[i]),
                content = $(this.content[i]);

            // configure the target positioning
            var position = currentTarget.css("position");
            if (position !== "fixed" && position !== "absolute") {
                currentTarget.css('position', 'relative');
            }

            // set the size and position to match the target
            var height = currentTarget.outerHeight(),
                width = currentTarget.outerWidth(),
                offset = currentTarget.offset();
            var sizeAndPosition = {
                'height': height + 'px',
                'width': width + 'px',
                'left': offset.left + 'px',
                'top': offset.top + 'px'
            };
            blocker.css(sizeAndPosition);

            var contentHeight = content.outerHeight();
            var contentWidth = content.outerWidth();
            // #9496 if display:none then we need to clone to get its dimensions
            if (contentHeight === 0) {
                var currentWidth = this.content[i].getBoundingClientRect().width;
                var clone = this.content[i].cloneNode(true);
                clone.style.cssText = 'position: fixed; top: 0; left: 0; overflow: auto; visibility: hidden; pointer-events: none; height: unset; max-height: unset; width: ' + currentWidth + 'px';
                document.body.append(clone);
                var jqClone = $(clone);
                contentHeight = jqClone.outerHeight();
                contentWidth = jqClone.outerWidth();
                jqClone.remove();
            }

            content.css({
                'left': ((blocker.width() - contentWidth) / 2) + 'px',
                'top': ((blocker.height() - contentHeight) / 2) + 'px',
                'z-index': PrimeFaces.nextZindex()
            });
        }
    }
};
```

**Comment by chisogch** [comment]
> BlockUI was touched in 13, see #9496

That issue is another one. It's related to the size of the content (not the target/overlay), when the parent is not displayed. The underlying issue is that JQuery .outerHeigh() may return 0 in that case, leading to bad computation of content size 
 (and block content not centered). See https://api.jquery.com/outerheight/#entry-longdesc
The [related commit](https://github.com/primefaces/primefaces/commit/259db449d60b0667e86796286bea45074ffea27f) ajdusts the size (height, width) of the content:

https://github.com/primefaces/primefaces/blob/259db449d60b0667e86796286bea45074ffea27f/primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js#L290-L308

This issue is about the size of currentTarget/overlay, not size of the content, computed a few lines higher:

https://github.com/primefaces/primefaces/blob/259db449d60b0667e86796286bea45074ffea27f/primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js#L278-L287

> Can you please see if this issue is still there with 13 (SNAPSHOT)?

The issue is still present in 13.0.0-SNAPSHOT, as tested on the master branch build. https://github.com/primefaces/primefaces/tree/master/primefaces-showcase

**Comment by melloware** [comment]
Yep just posted a monkeypatch above your post!  We posted at the same time
