### ISSUE TITLE
p:panelGrid problem with composite as child will not be rendered and no error msg is thrown

### ISSUE THREAD

**Issue by Dr4gon** [primefaces/primefaces#959]
Hi,

here's the complete info regarding the bug I found in PrimeFaces: 

http://stackoverflow.com/questions/34003868/jsf-primefaces-composite-component-with-nested-composite-component/34310031#34310031

Best regards
Dr4gon

**Comment by kukel** [comment]
and what **is** the issue? Please improve at least the title

**Comment by Rapster** [comment]
> Somehow the panelGrid doesn't accept a nested component and just swallows it without an error or warning. Replacing the prime faces panelGrid with a JSF one solves this problem:

I guess with simple words, the child component _(which is a composite)_ of p:panelGrid is not displayed

**Comment by Dr4gon** [comment]
Hi @kukel ,

I'm very sorry about not replying - I didn't get any notifications about that.

I edited the title accordingly. 

Yeah @Rapster is correct. The child component won't be shown when it's a composite. Details in the stackoverflow post.

Best regards

**Comment by tandraschko** [comment]
Could be the same as: https://github.com/primefaces/primefaces/issues/3355

**Comment by melloware** [comment]
Duplicate of #3355
