### ISSUE TITLE
DataTable: JpaLazyDataModel.convertToType throws FacesException for java.util.Date

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces/primefaces#9594]
### Describe the bug

When using `p:datePicker` in a column filter facet of a `p:dataTable` backed by a `JpaLazyDataModel`, filtering fails with a `FacesException` thrown by `JpaLazyDataModel` stating:

```
SEVERE: javax.faces.FacesException: Can not convert 2023-01-04 to type class java.util.Date; please create a JSF Converter for it or overwrite Object convertToType(String value, Class<?> valueType)!
        at org.primefaces.model.JpaLazyDataModel.convertToType(JpaLazyDataModel.java:337)
        at org.primefaces.model.JpaLazyDataModel.applyFilters(JpaLazyDataModel.java:163)
        at org.primefaces.model.JpaLazyDataModel.count(JpaLazyDataModel.java:120)
```

### Reproducer

The existing primefaces-test jpa branch shows this: https://github.com/primefaces/primefaces-test/tree/jpa

After starting the app, filter by the Date Col and you will see the exception in the terminal.

### Expected behavior

Date filters should work with the `JpaLazyDataModel`.

`filter.getFilterValue()` should contain the correct object already and not need conversion at all. I may be missing the need for `convertToType`, but I'm wondering if it should just default to the original value if it can't convert it.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

All

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

Chrome latest

**Comment by melloware** [comment]
@tandraschko looking for your thoughts here?

**Comment by FlipWarthog** [comment]
I'll put in a draft PR of what I'm thinking tomorrow. I'd love a review and, potentially, correction on what I'm thinking.
