### ISSUE TITLE
SelectBooleanCheckbox: provide stateTrueIcon and stateFalseIcon

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9599]
### Description

The `p:triStateCheckbox` can use custom icons:

`<p:triStateCheckbox value="#{triStateCheckboxView.value3}" stateTwoIcon="pi pi-plus" stateThreeIcon="pi pi-minus"/>`

### Describe the solution you would like

Would be nice to provide the ability to add custom icons also for `p:selectBooleanCheckbox`:

`<p:selectBooleanCheckbox value="#{selectBooleanView.value1}" itemLabel="Basic" stateTrueIcon="pi pi-plus" stateFalseIcon="pi pi-minus" />`

**Comment by melloware** [comment]
@nimo23 if you want to provide a PR that would be great you can probably just look at how TriState is doing it and model it after that!

**Comment by tandraschko** [comment]
We should really think about it, its possible with CSS too

**Comment by nimo23** [comment]
Yes, it's possible by using only css. 

I think, we can close this issue.

**Comment by nimo23** [comment]
With css only:

```
/** for false value (there is no "ui-icon-uncheck" class)  */
.ui-chkbox-icon ui-icon ui-icon-blank ui-c:before{

}

/** for true value, we can use "ui-icon-check" */
body .ui-chkbox .ui-chkbox-box .ui-chkbox-icon.ui-icon-check::before{
..
}

```
in compare to:

`<p:selectBooleanCheckbox ..stateTrueIcon="pi pi-plus" stateFalseIcon="pi pi-minus" />`

Another advantage of using `stateTrueIcon`/`stateFalseIcon` over using (undocumented) CSS classes is that if PF changes its CSS classes in one of the next releases, the deprecated CSS will not work..

**Comment by tandraschko** [comment]
IMO icons are changed for the whole application, not just for one single component
Therefore CSS is actually the better way

**Comment by nimo23** [comment]
Ok,
