### ISSUE TITLE
SelectOneButton: should be unselectable by default as SelectOneRadio

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#9600]
### Description

I would prefer that the SelectOne input widgets work with the same defaults.

The SelectOneButton 

https://www.primefaces.org/showcase/ui/input/oneButton.xhtml?jfwid=1e4f3

allows unselecting by default while the SelectOneRadio as well as SelectOneListBox

https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml?jfwid=1e4f3

do not. The latter way is preferable, especially in the presence of a NotNull annotation, since otherwise unselecting triggers validations in case of p:jax.

Wdyt? Many thanks in advance.

### Describe the solution you would like

Revise p:selectOneButton such that unselection is only supported explicitly as in the case of p:selectOneRadio, where the attribute 

`unselectable="true"`

is used to allow unselecting.

**Comment by melloware** [comment]
I think that seems reasonable for consistency I just worry about backwards compatibility of people expecting the current behavior?

**Comment by tuerker** [comment]
I fully see your point. I could image that i am not the only one who was not aware of the fact that selectOneButton is unselectable by default. I unintentionally pressed twice on a "NotNullable" selectOneButton, which is connected to an ajax update, and was surprised to get a validation error. I know that i can use o:skipValidators but then this raises much more trouble with NPE handling. 

To make it backward compatible, the solution would be to add the attribute "unselectable" to p:selectOneButton with the default value true. Then, one could easily circumvent the problem i mentioned by just using 

`unselectable="false"`

Wdyt?

**Comment by melloware** [comment]
i like the idea.

**Comment by tuerker** [comment]
the documentation of selectOneButton states

`unselectable | true | Boolean | Whether selection can be cleared.`

so, this way is already implemented. i wonder why intellij did not show that attribute. so, then i will close this issue.

thanks for your feedback.

**Comment by melloware** [comment]
let me make sure its in the taglib.xml which is what IntelliJ reads.  it looks like it was missing a description so I just added it.  I wonder if IntelliJ ignored props without descriptions?

```xml
        <attribute>
            <description>
                <![CDATA[]]>
            </description>
            <name>unselectable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
        </attribute>
```

**Comment by tuerker** [comment]
great. thanks.
