### ISSUE TITLE
BlockUI: provide delay (before displaying the blockUI)

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9604]
### Description

p:ajaxStatus has a delay property:

> Delay in milliseconds before displaying the ajax status. Default is 0 meaning immediate.

`<p:ajaxStatus  delay="0"..>`

### Describe the solution you would like

Please provide the delay property also for `p:blockUI`:

> Delay in milliseconds before displaying the blockUI. Default is 0 meaning immediate.

`<p:blockUI  delay="1200"..>`

**Comment by melloware** [comment]
Hmmm i would be interested in your use case on why you would want to delaying blocking?  Do you have an example?

**Comment by nimo23** [comment]
> i would be interested in your use case on why you would want to delaying blocking

The same use case as why someone would add a delay in `p:ajaxStatus`:

Don't distract the user until it's needed, e.g. show the "blocking" only after 300ms - before 300ms, it's not worth to show the `p:blockUI`.

**Comment by melloware** [comment]
But BlockUi is usually triggered by an Ajax request so wouldn't the delay on the ajax request just apply and it wouldn't start?  So once again I don't understand your use case?

**Comment by nimo23** [comment]
>But BlockUi is usually triggered by an Ajax request so wouldn't the delay on the ajax request just apply and it wouldn't start?

But `p:ajaxStatus` is independent from `p:blockUI`. When using `p:ajaxStatus  delay="200"`, then it only delays the p:ajaxStatus (so the spinner is only shown if the ajax request did not complete before 200ms). 

I want that `p:blockUI` is only shown if the ajax request **did not complete after 300ms**. I do **NOT** want to delay the ajax request but I want to delay the **visibility** of the blockUI - if the ajax request completed before 300ms, then no blockUI should be shown. Nothing else.

**Comment by melloware** [comment]
That makes sense I had no idea ajax status had that feature we should make them consistent.
