### ISSUE TITLE
Menuitem: title (or tooltip) is not shown

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9605]
### Describe the bug

Using something like this:

```
<p:speedDial direction="up" visible="true">
		<p:menuitem 
			pt:title="Delete"
			title="Delete" 
			..
			icon="pi pi-trash" />
</p:speedDial>
```

should display the "title"-property (when hovering). However, no `title` attribute is shown. Looking at the generated code, PF only generates a `data-tooltip="Delete"`. However, the tooltip is also not shown. 

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10366134/primefaces-test.zip)

### Expected behavior

tooltip should be shown (at least the title, but better to show tooltip).

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by melloware** [comment]
Yep just add `<p:tooltip />` on your page and the data-tooltips get displays as styled PF tooltips see screenshot 

![image](https://user-images.githubusercontent.com/4399574/211151070-9436fcfc-d2fc-4e00-935c-f5f96191b829.png)
