### ISSUE TITLE
Captcha: Allow for custom URL

### ISSUE THREAD

**Issue by wish79** [primefaces/primefaces#9606]
### Description

we open this ticket https://forum.primefaces.org/viewtopic.php?p=206830#p206830

we need primefaces captcha tag to give us the ability to change the google url, because in some country the google url blocked so google provide another url which is accessible in theses countries

read this doc from google can-i-use-recaptcha-globally [https://developers.google.com/recaptcha ... -globally](https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally),

so our request how can i change the google captcha url in primefaces 

### Describe the solution you would like

in captcha give us the src as tag parameter to pass another google url in case the out of the box url is blocked in some countries

**Comment by melloware** [comment]
I just fixed this for PrimeReact too: https://github.com/primefaces/primereact/issues/3921

Should be no problem.

**Comment by melloware** [comment]
OK so in PF 13 there will be a new `srcUrl` attribute for you to overrwrite.  But if you need a MonkeyPatch right now just add this block of code to your application and change the URL to whatever you want...

```js
if (PrimeFaces.widget.Captcha) {
    PrimeFaces.widget.Captcha.prototype.init = function(cfg) {
        PrimeFaces.widget.BaseWidget.prototype.init.call(this, cfg);
        this.cfg.language = this.cfg.language || 'en';
        this.cfg.theme = this.cfg.theme || PrimeFaces.env.getThemeContrast();

        var $this = this;

        window[this.getInitCallbackName()] = function() {
            $this.render();
        };

        var nonce = '';
        if (PrimeFaces.csp.NONCE_VALUE) {
            nonce = 'nonce="' + PrimeFaces.csp.NONCE_VALUE + '"';
        }

        $(document.body).append('<script src="https://www.google.com/recaptcha/api.js?onload=' + this.getInitCallbackName() + '&render=explicit&hl=' +
            this.cfg.language + '" async defer ' + nonce + '>');

    }
};
```

**Comment by wish79** [comment]
Thanks @melloware  for your quick reply, we open another one in primereact do you have MonkeyPatch  as well for Primereact till official release

**Comment by melloware** [comment]
Sorry react is not "MonkeyPatchable" that I am aware of.  It may be possible but I am not sure how.
