### ISSUE TITLE
Change the default value of separator property on Chips

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primefaces#9615]
Since the chips component always sets the separator value, it cannot be used without a separator.

**Comment by jepsar** [comment]
Added this to the migration guide:

https://github.com/primefaces/primefaces/commit/bf0e2f768e1d36f5289e581db8f84df1681e4363

**Comment by melloware** [comment]
Yep can you add it @jepsar ?

**Comment by jepsar** [comment]
@melloware done already 👍🏻. I modified the comment an hour ago.
