### ISSUE TITLE
Watermark: remove

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9616]
since JSF 2.2 we have passthrough attributes and HTML placeholder is supported in all newer browsers

so the question is: when should we remove p:watermark for JSF2.0 and 2.1 users?

**Comment by jepsar** [comment]
Now / 13? I don't think we still have a lot users of the current version of PrimeFaces running JSF below 2.3. And it is easy to do with just some vanilla Javascript.

https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/watermark/watermark.js

**Comment by melloware** [comment]
I agree let's remove it now.

**Comment by melloware** [comment]
Submitted a PR for review

**Comment by tandraschko** [comment]
@mertsincan WDYT about this?

**Comment by jepsar** [comment]
.. maybe deprecate first and remove in 14?

**Comment by tandraschko** [comment]
yeah, deprecate first is always a good idea

**Comment by melloware** [comment]
OK I made this Milestone 14.0.0.  Will create another one to deprecate it in 13.0.0

**Comment by Bukama** [comment]
> Now / 13? I don't think we still have a lot users of the current version of PrimeFaces running JSF below 2.3. 

I promise you: You have a lot in big firms like banks and (as mine company) government 🙈🤷‍♂️

**Comment by tandraschko** [comment]
JSF 2.2 is 10 years old
when companies upgrading PF, it should be no problem updating a application server each ~10 years ;)

**Comment by Bukama** [comment]
Don’t get me wrong, I’m totally on your side and I’m convinced that the devs of those comps do want to change/upgrade (at least is what I know from devs at my and the comps I spoke with), but often they can‘t decide. And I‘m absolutely fine with deprecating and removing this stuff. Just wanted to make everyone aware that, especially on such grown frameworks like PF, there will always be people who will get problems (see https://www.hyrumslaw.com/ ) and that this knowledge was taken into account for the decision. In my open source project (JUnit Pioneer, an extension library for JUnit Jupiter) we also decided to upgrade to minimum Java version 11, knowing 4 of 5 maintainers and many users won‘t be able to use the next major version. But we choose to do so in the end. I don’t expect my little OSS project to be THE cause why people then decide to upgrade, but PF can the such a cause - knowing that some projects at my work are still on PF 6 (yes six) and are now forced to upgrade by security board. To come to an end: If everyone (in the whole world) would be aware of others situations, communication and acceptance for decisions (like deprecating/removing things) would be a lot smarter/kinder (not sure what the right english word is). 
And I know (e.g. from Discord) that @melloware and @jepsar are people who care about that ❤️
