### ISSUE TITLE
DataExporter - exportAll from lazy table does not restore the page size

### ISSUE THREAD

**Issue by nmnemonic** [primefaces/primefaces#962]
When exporting all from a lazy-loaded datatable, the page size is set to the total number of rows in the dataset to avoid downloading the data page-by-page.  When restoring the table, the pagesize is not restored before reloading the table.  This causes the entire dataset to be reloaded  from the database, instead of just the few lines needed to populate the current page.

[patch.txt](https://github.com/primefaces/primefaces/files/65347/patch.txt)

**Comment by kukel** [comment]
PF version?

**Comment by nmnemonic** [comment]
5.3.3.

**Comment by melloware** [comment]
This was fixed a while back. See the current code:
https://github.com/primefaces/primefaces/blob/7bf566bb2dd9d2970333a0fd9ec49cdd147848ff/src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java#L209-L242
