### ISSUE TITLE
Datatable row number is wrong using dataexporter with 'selectionOnly=true'

### ISSUE THREAD

**Issue by mustafa-sevim** [primefaces/primefaces#9626]
### Describe the bug

![image_2](https://user-images.githubusercontent.com/62053632/211564633-d84ba5da-35e8-45de-999f-0810760194b8.png)

This is the expected output when datatable is exported to a XLS file. I used dataExporter like that:

` <p:dataExporter type="pdf" 
                             target="#{targetTableId}"
	    		     fileName="#{muesUtil.unaccent(title)}"
									preProcessor="#{dataExporterController.preProcessPDF}"
									selectionOnly="#{not empty isSelectionOnly and not empty bean.selectionList}"
									encoding="CP1254" visibleOnly="true" exportHeader="true"/>`

When no row is selected or selectionOnly is not given to dataExporter, it exports the rows as it is shown above. But when some of the rows are selected, output file's row numbers are all same which is 1. It is shown below:

![image_1](https://user-images.githubusercontent.com/62053632/211565746-9c53a6ce-1c77-40d8-ac50-be029cd8197f.png)

When printing the row number inside the datatable, it always prints 1 instead of increasing values.

`
<p:column  headerText="No">
        <h:outputText value="#{row + 1}"  style="word-break: break-all"/>
</p:column>
`

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10390228/primefaces-test.zip)

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.0

### Java version

11

**Comment by melloware** [comment]
Please  provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by mustafa-sevim** [comment]
Reproducer is added. 
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10390232/primefaces-test.zip)

**Comment by melloware** [comment]
@mustafa-sevim your example is working fine for me and Row Numbers are being printed correctly?

[pf-9626.zip](https://github.com/primefaces/primefaces/files/10392500/pf-9626.zip)


![image](https://user-images.githubusercontent.com/4399574/211811168-f4ffedb2-9ab7-45ea-891b-6c80e25a2871.png)

**Comment by melloware** [comment]
I noticed above you mentioned you are using JSF 2.0 is that correct?

**Comment by melloware** [comment]
Closing until the issue can be replicated by the OP.
