### ISSUE TITLE
Timeline: Add item type background

### ISSUE THREAD

**Issue by amittel** [primefaces/primefaces#9634]
### Description

Right now PF12 has the following item types

- box
- point
- range

But looking at the vis-timeline [documentation ](https://visjs.github.io/vis-timeline/docs/timeline/#items)there is another item type called **background**.

### Describe the solution you would like

With adding the item type **background**, there would be parity between PF and vis-timeline.

**Comment by melloware** [comment]
Thanks!  I updated the documentation and I added in `TimelineEvent.java` a new `type` field so now you can set types per event.  Please review the PR.
