### ISSUE TITLE
Timeline: Add more AJAX events

### ISSUE THREAD

**Issue by amittel** [primefaces/primefaces#9635]
### Description

The timeline documentation shows some [Ajax Behavior Events](https://primefaces.github.io/primefaces/12_0_0/#/components/timeline?id=ajax-behavior-events). But there are more events available looking at the vis-timeline [documentation](https://visjs.github.io/vis-timeline/docs/timeline/#Events)

### Describe the solution you would like

Add more events to the timeline. Maybe all to have a parity.

**Comment by melloware** [comment]
In the past we have added behavior events that make sense. For example `mouseOver` and `mouseMove` make very poor AJAX events as they are too "chatty".

It would be great if you could update this ticket by looking at what is available and what is missing and put a list together of exactly the events you think would be useful AJAX events!

**Comment by melloware** [comment]
@amittel will close for now.  If you come back with exact events you think are missing I will re-open
