### ISSUE TITLE
p:spinner or p:selectOneMenu inside an editable p:datatable row

### ISSUE THREAD

**Issue by benoitbb** [primefaces/primefaces#964]
When I want to use an editable p:datatable with a p:spinner or a p:selectOneMenu in the edited row, css are not correct. You see "highlight" css images on these components (arrow upo and down). In the showcase, you bypass the problem by using a h:selectOneMenu (http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml)
Can you please have a look ? Or do you have a css that will permit me to see the correct ui-icons_.....png image (not the "highlighted" one) ?

**Comment by kukel** [comment]
PF Version?

**Comment by benoitbb** [comment]
5.3

2016-01-11 16:58 GMT+01:00 Ronald van Kuijk notifications@github.com:

**Comment by melloware** [comment]
This is only an issue on the old Jquery ThemeRoller themes.  All of the modern Premium Themes and included free `Nova` and `Luna` themes do not have this issue.   So if anything this should be reported on the legacy Themes issue site: https://github.com/primefaces/themes/issues
