### ISSUE TITLE
Confirm: provide facet "message"

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9645]
### Description

Actually, we can only use plain text for `message` within `p:confirm`:

`<p:confirm header="Confirmation" message="This is a plain text.">`

There is no possiblity to provide custom html content within `p.confirm`.

### Describe the solution you would like

Provide the facet `message` to support custom html content within `p:confirm`:

```
<p:confirm header="Confirmation">
<f:facet name="message">
    <div>This is <b>plain</b> <span style="color: blue;">text</span>.</div>
    <br/>
    <div>Example..</div>
</facet>

</p:confirm>
```

If possible, also add a `facet` for the `header`:

```
<p:confirm>
<f:facet name="header">
    <div>My <b>custom</b> <span style="color: blue;">header</span></div>
</facet>

</p:confirm>
```

**Comment by melloware** [comment]
@nimo23 interested in submitting a PR?  I think this would be a good change.

**Comment by nimo23** [comment]
I will look into the source..I'll see if I can do that..

**Comment by melloware** [comment]
Hopefully it should be fairly simple if you just look how other facets are done in other components.

**Comment by nimo23** [comment]
I looked into

https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/dialog/DialogRenderer.java#L136

which also provides a facet for "header" to understand how to register facets into the `p:dialog`.

However, looking into https://github.com/primefaces/primefaces/blob/9d1151b79a10b1b09f644244881443f30a9764aa/primefaces/src/main/java/org/primefaces/component/confirmdialog/ConfirmDialogRenderer.java#L98 and

https://github.com/primefaces/primefaces/blob/9d1151b79a10b1b09f644244881443f30a9764aa/primefaces/src/main/java/org/primefaces/component/confirmdialog/ConfirmDialogRenderer.java#L140

it seems that these facets "header" and "message" are already registered. Also for https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/java/org/primefaces/component/confirmpopup.

However, using something like 


```
<p:confirm>
<f:facet name="header">
    ..
</facet>
<f:facet name="message">
    ..
</facet>
</p:confirm>
```

does not work.

I don't know where to register these facets elsewhere. 

I would only have made the changes in these packets:

- https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/java/org/primefaces/component/confirmdialog.
- https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/java/org/primefaces/component/confirmpopup.

But the facets seems already there but not registered.. I don't know how to do it.

**Comment by tandraschko** [comment]
confirm is a behavior, i dont think it support facets

**Comment by nimo23** [comment]
I think `p:confirm` is an extension of `p:dialog` conisting of 3 parts:

- `header`: could be any html -> therefore provide `<facet name="header">`
- `message`: could be any html > therefore provide `<facet name="message">`
- `footer`: this should not be changable by the user, as it contains the "Yes/No"-dialog.

So I see no reason why `p:confirm` could not allow facets for `header` and `message`.

**Comment by tandraschko** [comment]
because confirm is behavior, confimDialog and confirmPopup are components
ClientBehaviorBase doesnt have a getFacet method like UIComponent have

**Comment by melloware** [comment]
I am marking this as WontFix since its not fixable due to technical limitations of Behavior.
