### ISSUE TITLE
Bug in pe:inputNumber

### ISSUE THREAD

**Issue by ojekanmi** [primefaces/primefaces#965]
The inputNumber declaration below will not accept any input except you remove the minValue attribute, Also, the input will go beyond the maxlength attribute specified.
          pe:inputNumber id="codeKat" value="#{myMB.codeK}" minValue="3000"   decimalSeparator=""  thousandSeparator=""    required="true" maxlength="6" decimalPlaces="0"/>

comment by - Thomas Andraschko
"The problem is currently that the vmin is applied before the value is applied to the input. Therefore the validation of the JS fails before we even set the value.
Please create a ticket in the PrimeFaces issue tracker, as the component was already moved to PrimeFaces."

**Comment by tandraschko** [comment]
I fixed it but the vmin might not meet your expectations.
There is currently an discussions about it here: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/364
