### ISSUE TITLE
Dialog: cache="false" does not update its header/footer

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#9652]
### Describe the bug

The `p:dialog` with `dynamic="true"` has the following issues:

1. `p:dialog` does not update its `header` and `footer` content before showing the dialog. It only updates its middle content.

### Reproducer

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10405078/primefaces-test.zip)

### Expected behavior

If `dynamic="true"`, then `p:dialog` (also `header` and `footer` facets) must update its content before showing.

### PrimeFaces edition

Community

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Firefox 107

**Comment by nimo23** [comment]
Ok, for `p:overlayPanel,` it seems actually right, according to doc https://primefaces.github.io/primefaces/12_0_0/#/components/dialog:


> [Dynamic Mode](https://primefaces.github.io/primefaces/12_0_0/#/components/overlaypanel?id=dynamic-mode)
> 
> Dynamic mode enables lazy loading of the content, in this mode content of the panel is not rendered on page load and loaded just before panel is shown. Also content is cached so consecutive displays do not load the content again. This feature is useful to reduce the page size and reduce page load time.

For this case, I will create a feature request, so `p:overlayPanel` should also have the property "cache" like p:dialog:

> cache: Only relevant for dynamic="true": Defines if activating the dialog should load the contents from server again. For cache="true" (default) the dialog content is only loaded once.

**Comment by melloware** [comment]
Looks like this was a purposeful design decision to only load the `content`.

**Comment by nimo23** [comment]
If the user sets `cache=false` for the component `p:dialog`, then the user assumes that the `p:dialog` is _uncached_ and not only a part of it. So I think, it would be better to uncache the whole `p:dialog`. If not, then rename the `cache`-property to `cacheContent` and add another property called `cache`, which updates the whole component in compare to `cacheContent`.

**Use cases:**

Imagine a button within the `footer`-facet which should only be `rendered` if `x` is `true`. With `cache=false`, the `footer`-facet should also get the updated `x`.

If this would not be the case, then the variable `x` (= any EL-value) within the `content` can be different than the `x` of its `footer` or `header`. This would be treated as a bug in the eye of the viewer (= the user), because he sees current values ​​in the `content`, but not in the `footer`. Or to describe it otherwise: the user does not know which value is the more current one, since the value of the same variable `x` put in the `content` and the `footer` (or `header`) is different.

**Comment by melloware** [comment]
Yep I am just pointing out it has been like this since 2013 and it should be researched if it was intentional or there is some bug that was caused updating header and footer!

**Comment by melloware** [comment]
@nimo23 you interested in investigating this.  It looks like it just called `renderChildren` and not the entire `encodeMarkup` again not sure if it is that simple to call `encodeMarkup` again something tells me it might not be.

```java
    public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
        Dialog dialog = (Dialog) component;

        if (dialog.isContentLoadRequest(context)) {
            renderChildren(context, component);
        }
        else {
            encodeMarkup(context, dialog);
            encodeScript(context, dialog);
        }
    }
```

**Comment by nimo23** [comment]
hmm..I am not involved in this..

Maybe there was a reason why something like this:

```
if (dialog.isContentLoadRequest(context)) {
            encodeMarkup(context, dialog);
            // renderChildren(context, component);
        }
        else {
            encodeMarkup(context, dialog);
            encodeScript(context, dialog);
        }
```

was not implemented. The `renderChildren(context, component);` seems to have a purpose. I may be wrong, but it seemed that there were problems updating within facets? That would explain why `renderChildren(context, component);` was choosen over `encodeMarkup(context, dialog);` 

Well, I can do a PR by only replacing `renderChildren(context, component);` with `encodeMarkup(context, dialog);`, but I don't know about side effects..

**Comment by melloware** [comment]
Yeah was hoping you could try that change and test it.

**Comment by nimo23** [comment]
Ok I try.

**Comment by nimo23** [comment]
Using:

```
if (dialog.isContentLoadRequest(context)) {
            encodeMarkup(context, dialog);
}
else {
            encodeMarkup(context, dialog);
            encodeScript(context, dialog);
}
```

results in NOT render the content of `p:dialog`, i.e. only `header` and `footer` are rendered. However, the facets does also not update its content.

This:

```
public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
        Dialog dialog = (Dialog) component;
        encodeMarkup(context, dialog);
        encodeScript(context, dialog);
}
```

will result in not rendering header, footer and content.

This:

```
@Override
    public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
        Dialog dialog = (Dialog) component;

        if (dialog.isContentLoadRequest(context)) {
        	  encodeHeader(context, dialog);
        	  encodeFooter(context, dialog);
                  renderChildren(context, component);
        }
        else {
            encodeMarkup(context, dialog);
            encodeScript(context, dialog);
        }
    }
```
results in rendering the header and footer twice, however one header and one footer (and the content) gets the updated values. The other header and footer (which is visible) does not get the updated values.

**Comment by melloware** [comment]
The cache property absolutely works in the other ticket. It just doesn't render facets.

**Comment by nimo23** [comment]
It seems, that it only encodes its markup (html-tags) and uses the previous values without updating it. I don't know how to tell PF to also update its content (i.e. not the markup, but the values), something like:

```
if (dialog.isContentLoadRequest(context)) {
        	 updateContent(context, component); // does not exists..
                 renderChildren(context, component);
        }
        else {
            encodeMarkup(context, dialog);
            encodeScript(context, dialog);
        }
```

**Comment by nimo23** [comment]
>The cache property absolutely works in the other ticket. It just doesn't render facets.

Yes, sorry. https://github.com/primefaces/primefaces/pull/9656 works. I did not refresh my browser cache and it used the old pf js. It definitly works.

**Comment by melloware** [comment]
As I assumed this is likely some limitation and the reason it has been like this for 10 years.  If you really need to re-render the whole dialog including header and footer you should just add `update="dialog"` to your button opening your dialog so it re-renders entirely before opening.  You can still use `dynamic="true" cache="true"` to not render it the first time on page load to save page load time.

```xml
<p:commandButton value="Show" update="dialog4" oncomplete="PF('dlg4').show()"/>
```

**Comment by nimo23** [comment]
>As I assumed this is likely some limitation

What is the name of this limitation? Is this a PF or JSF limitation? 

Nevertheless, it should be documented in 

https://primefaces.github.io/primefaces/12_0_0/#/components/dialog

for the user that the facets `header` and `footer` will never be updated even if `"cache=false" and dynamic="true"`. Otherwise, the user expects that facets will be updated because the facets are only a part within the `p:dialog`. The user should know this limitation.

**Comment by nimo23** [comment]
Another workardound is: 

to never use the facets  (header, footer) when "cache=false" and dynamic="true" and use only the `content`-section.

**Comment by nimo23** [comment]
This can be added to https://primefaces.github.io/primefaces/12_0_0/#/components/dialog:

> 
> "Restrictions when using "cache=false" and dynamic="true":
> 
> Due to a limitation of PF, the facets `header` and `footer` cannot be updated even if `cache="false"` and `dynamic="true"`. For this cases, we recommend to use only the content-section. Or update the whole dialog-component by ajax-rerendering.

**Comment by melloware** [comment]
I think it is JSF related not PF related but not positive. Just know there is a reason the dynamic works this way without facets. Someone who knows more about core JSF may be able to answer that...
