### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by abdalrzzaqa** [primefaces/primefaces#9658]
### Describe the bug

i'm using primefaces 12 i have problem ,, could you help with solve it 

Widget class 'DatePicker' not found!

### PrimeFaces edition

None

### PrimeFaces version

12

### JSF implementation

All

### JSF version

2.2.20

### Java version

1.8

### Browser(s)

all

**Comment by tandraschko** [comment]
please use the forum or discord
a valid issue contains a reproducer, forked primefaces-test

we cant help you with this informations
