### ISSUE TITLE
Slider: javax.faces.FacesException: No converter available for: class java.lang.String

### ISSUE THREAD

**Issue by 1pinus** [primefaces/primefaces#9661]
### Describe the bug

```
javax.faces.FacesException: No converter available for: class java.lang.String
    at org.primefaces.component.slider.Slider.getValueAsStringOfAttachedInput(Slider.java:192) ~[primefaces-12.0.0.jar:12.0.0]
```
The method should return a string and already got one.

```
diff --git a/primefaces/src/main/java/org/primefaces/component/slider/Slider.java b/primefaces/src/main/java/org/primefaces/component/slider/Slider.java
index 2e8a538d8..7b483e2d2 100644
--- a/primefaces/src/main/java/org/primefaces/component/slider/Slider.java
+++ b/primefaces/src/main/java/org/primefaces/component/slider/Slider.java
@@ -184,6 +184,9 @@ public class Slider extends SliderBase {
             Object value = input.getValue();
 
             if (value != null) {
+                if (value instanceof String) {
+                    return (String) value;
+                }
                 Converter converter = ComponentUtils.getConverter(context, input);
                 if (converter != null) {
                     return converter.getAsString(context, this, value);

```

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.x

### Java version

11

**Comment by melloware** [comment]
> This fix is not part of 12.0.3, which is pretty bad since i convinced my company to sign a support contract.

@1pinus if you have a PRO contract you simply log into your PRO JIRA and request it as part of the next Elite release.  That is what my clients do.

If you just have an Elite subscription it does not entitle you to anything other than Elite releases not what goes into an Elite release.

Please read: https://github.com/primefaces/primefaces#community--elite--pro
