### ISSUE TITLE
Define build matrix

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9671]
today i added some basic integration tests for our Jakarta Shading

our CI is basically really really to fat, i would suggest to:
- Run 2.2 MyFaces + Mojarra only on Java 8
- Run 2.3 MyFaces + Mojarra only on Java 8 and Java19 (basically oldest and currently most recent version)
- Run 4.0 MyFaces + Mojarra only on Java 11 and Java19 (EE10 builds on Java 11)

**Comment by tandraschko** [comment]
cc @melloware @christophs78

**Comment by christophs78** [comment]
+1
May be a bit more work because github actions matrix is a bit inflexibel.
May require kind of
if: matrix.java == 8
stuff.

**Comment by tandraschko** [comment]
i would do it like this:
https://gist.github.com/tandraschko/2e471292c86aa2b89a952d12899124b1

splitup into 3 jobs: build, javax integration, jakarta integration

for all integration tests, we can even skip all that stuff like unittests,checkstyle,javadoc,etc.

**Comment by tandraschko** [comment]
and is there any reason why we dont run with -T1 C?

**Comment by melloware** [comment]
No reason that I know of and we can always do 3 separate build scripts right?  I think that is what you are suggesting.  They can all be set to run on PR as well.

**Comment by tandraschko** [comment]
in theory we could split them up yes but as all of them are CI, i would leave it in 1 file

**Comment by tandraschko** [comment]
should we run security-checks on each CI? i mean, the team only updates dependencies... no idea

**Comment by tandraschko** [comment]
About jakarta... MyFaces RC3 fails because of the NPE you fixed @melloware whcih is not yet released, Mojarra doesnt even start

should we use snapshots?

**Comment by tandraschko** [comment]
just one fact i dont like is that we need to exclude via mvn -pl the jakarta integration tests when building with Java8 for now

**Comment by melloware** [comment]
I am OK with using SNAPSHOTS until we are out of RC with MyFaces

**Comment by tandraschko** [comment]
created a issue in Mojarra: https://github.com/eclipse-ee4j/mojarra/issues/5198

**Comment by tandraschko** [comment]
and we have real failes in Mojarra2.2 :/ @melloware would like to check it? :D i will go sleep now

**Comment by tandraschko** [comment]
sounds very similar to the exception in MyFaces 4.0 :D
`java.lang.NullPointerException
	at com.sun.faces.application.view.ViewScopeContextManager.destroyBeans(ViewScopeContextManager.java:169)`
	
maybe should remove Mojarra 2.2 because its enough to test one impl on spec lvl 2.2?

**Comment by melloware** [comment]
Yep I saw all those Mojarra 2.2 failures and was wondering how much time to invest in Mojarra when not too many people are using 2.2 anymore?   That is why I only enabled MyFaces for 2.2 :)

**Comment by melloware** [comment]
Looks like the nightly.yml also has to be fixed based on these latest changes.

**Comment by melloware** [comment]
Looks like everything is building properly now!  Nice job
