### ISSUE TITLE
primefaces.MOVE_SCRIPTS_TO_BOTTOM = true  causes Javascript Error when <ui:include/> is present

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#9673]
### Describe the bug

Set web.xml with:
```
<context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```
Causes JS error when using **<ui:include  />** in pages that have Primefaces components  like `<p:selectOneMenu/> or <p:calendar/> `(<h:selectOneMenu/> are not affected for example).  

![image](https://user-images.githubusercontent.com/1834036/212437778-acfe186a-89f9-497d-9ea0-fb7c33ed8135.png)

### Reproducer

https://github.com/edudoda/primefaces-test-cases

### Expected behavior

Components like `<p:selectOneMenu/> or <p:calendar/> ` should work fine.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.2

### Java version

8

**Comment by melloware** [comment]
Thanks for the reproducer I will take a look

**Comment by jepsar** [comment]
HTTP ERROR 500 java.io.FileNotFoundException: /template/commonLayout.xhtml Not Found in ExternalContext as a Resource

**Comment by melloware** [comment]
@edudoda Yes you are referencing ` <ui:composition template="/template/commonLayout.xhtml"> ` which does not exist.  If you can get your reproducer in working order please that would help.

**Comment by edudoda** [comment]
Sorry about that, just missed to include that in git. Could you try it now?

**Comment by melloware** [comment]
@edudoda now I know why it doesn't work your code is ALL wrong.   You are not allowed  to have multiple `<html>` or `<body>` elements in the same HTML document it violates the spec. See: https://stackoverflow.com/a/2035627/502366

It explains why the MOVE_SCRIPTS_TO_BOTTOM broke your page because its invalid HTML thus invalid SCRIPTS.

**Comment by edudoda** [comment]
Got it!  In fact in many included pages redundant `<html>` and `<body>` were just ignored  by Facelets, but in some `<ui:composition>` was missing and resulting in that invalid pages.  Strange that I never had any problems or errors related to that before... again thank you very much for your assistance  @melloware

**Comment by melloware** [comment]
Yep i can't believe you didn't have problems before.  And once you fix it all MOVE_SCRIPTS_TO_BOTTOM will work fine.
