### ISSUE TITLE
SelectOneMenu: Option can't be disabled

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#9677]
### Describe the bug

If you want to disable an option on SelectOneMenu, the option is not correctly disabled when using SelectOneMenu with a table.

### Reproducer

[reproducer.zip](https://github.com/primefaces/primefaces/files/10420658/reproducer.zip)

1) Open the menu from Example 2
2) Click on the option "Option disabled"
3) The option "Option disabled" is selected

### Expected behavior

An option which is disabled with itemDisabled="true" on f:selectItem should not be selectable.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.2

### JSF implementation

All

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
I will take this one

**Comment by tandraschko** [comment]
didnt we already fix some similar bugs the last months?
can we add some integration tests?

**Comment by melloware** [comment]
I think so I will research and fix today and add IT if it's not fixed already.
