### ISSUE TITLE
InputNumber: Pass Through Attributes are incorrectly placed

### ISSUE THREAD

**Issue by pfumi** [primefaces/primefaces#9678]
### Describe the bug

A pass through attribute on InputNumber is not placed on the input.
![image](https://user-images.githubusercontent.com/6900303/212555720-146d6bc1-5bf5-4795-b68b-04237082eb5f.png)

### Reproducer

[reproducer.zip](https://github.com/primefaces/primefaces/files/10420741/reproducer.zip)

### Expected behavior

Pass through attributes on InputNumber should be placed on the input.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

8

**Comment by tandraschko** [comment]
Passthrough are always applied on root, thats by design

**Comment by pfumi** [comment]
Can't confirm that, for autocomplete for example it's placed on the input.
See here: ![image2](https://user-images.githubusercontent.com/6900303/212557193-3f3248be-d631-4988-8968-135e4da753dc.png)

I just noticed it on InputNumber because I used pt:inputmode on PF version < 12.x, and there was no <span> there, so it got placed on the input.

**Comment by pfumi** [comment]
Oh ok I now get it, if the attribute allready exists, then pass through attributes just do nothing.
Like pt:id or pt:inputmode do not overwrite the existing the attributes.

Here pt:foo is just placed correctly on root and input.
![image3](https://user-images.githubusercontent.com/6900303/212558011-9ce2a144-c749-4371-b809-a8ae3b2c4746.png)

Closing the issue.
