### ISSUE TITLE
[Documentation] Add header facet to p:dialog

### ISSUE THREAD

**Issue by kito99** [primefaces/primefaces#968]
Right now the header for <p:dialog> must be text (it's impossible to embed markup, as it was in earlier versions). So it'd be nice to have a header facet:

``` xml
<p:dialog  ...>
<f:facet name="header>
  <div>My custom header</div>
</f:facet>
....
</p:dialog>
```

**Comment by cagataycivici** [comment]
There is header facet available already. What is your version?

**Comment by kito99** [comment]
Yeah, I realized that after I filed the issue. It isn't documented, though,
in the showcase or use guide.

**Comment by sudheerj** [comment]
Issue title can be change to '[Documentation]Add header facet to p:dialog'

**Comment by cagataycivici** [comment]
Done.
