### ISSUE TITLE
DataTableExcelExporter: Number detection is not locale specific. Always checks for . as decimal separator

### ISSUE THREAD

**Issue by arnis87** [primefaces/primefaces#9681]
### Describe the bug

When exporting datatable into Excel it does not export numbers correctly when numbers are converted using different decimal separator than "."

Instead is uses `LangUtils` to detect numbers but this should somehow become Locale dependent and check for decimal separator similar to this:
`new DecimalFormatSymbols(Locale.FRANCE).getDecimalSeparator()` which results in ',' rather than '.'

`DatatableExporter` should allow for setting explicit locale instead of always relying on `LocaleUtils.getCurrentLocale()` and this locale should be used to convert numbers into text inside the `DataTableExcelExporter` and also when detecting whether there are numbers used.

Since PF and JSF in general depend on currentLocale to resolve its error Messages there is a use case where locale in viewRoot will not match the one used to format numbers and dates - application is shown in some other language than formatting locale, e.g application is in English but dates and numbers formatted in France locale. There should be proper ways to bypass currentLocale in such use case

Currently only workaround I see is to implement either export post process or create separate export columns with US locale based number converter. Since we have many such tables more generic approach would be needed as workaround

### Reproducer

Set current locale to FRANCE in `ViewRoot` and try to export table that contains decimal numbers formatted using FRANCE locale as well. Examine outcoming excel. Numbers get messed up

### Expected behavior

Such decimal numbers get exported as proper decimal numbers in excel. 
Correct data format in excel would also be appreciated, eg number of decimals preserved and padded with 0s where needed.

### PrimeFaces edition

None

### PrimeFaces version

11

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
@arnis87 this is already fixed.

See: https://primefaces.github.io/primefaces/12_0_0/#/components/dataexporter?id=customization

```java
excelOpt.setNumberFormat(new DecimalFormat("#,##0.00"));
excelOpt.setCurrencyFormat(DecimalFormat.getCurrencyInstance(new Locale("es", "US")));
```
