### ISSUE TITLE
Client Side Validation: no shading of i18n locale messages

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#9687]
### Describe the bug

I was testing CSV in my app and I noticed client side error messages are not translated.
Seems like there's no javax -> jakarta shading of the [javascript locales](https://github.com/primefaces/primefaces/tree/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales)

### Reproducer

check the jakarta jar, folder META-INF/resources/primefaces/locales

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0.0

### Java version

jdk-11.0.13

**Comment by NicolaIsotta** [comment]
Nevermind, duplicate of #9660

**Comment by melloware** [comment]
Yep fixed in 13.0.0-SNAPSHOT
