### ISSUE TITLE
SelectCheckboxMenu: Multiple select - list of selections not cleaned up for filters 

### ISSUE THREAD

**Issue by reginakupczak** [primefaces/primefaces#9691]
### Describe the bug

Multiple select - list of selections not cleaned up for filters.

### Reproducer

1. Go to ['...'](http://www.primefaces.org:8080/showcase/ui/input/checkboxMenu.xhtml?jfwid=3e371)
2. Click on Multiple
![image](https://user-images.githubusercontent.com/97100687/212873014-5831346e-b529-45cb-95d7-66d54c3485c2.png)
3. Select all
![image](https://user-images.githubusercontent.com/97100687/212873113-33ce3cb4-3ba9-42e7-b58d-5fe431e697f9.png)
4. Filter Miami
![image](https://user-images.githubusercontent.com/97100687/212873370-002f65d6-ffac-48da-86ef-28d3c5182f06.png)
5. Use Checkbox next to the filter bar 
![image](https://user-images.githubusercontent.com/97100687/212873733-6c3ae7dc-a95d-4df6-95df-85d645d8db78.png)
6. Remove text from filters with the keyboard
![image](https://user-images.githubusercontent.com/97100687/212874234-dc82ce40-8af1-4a3b-9fb1-4ef0989ebda4.png)

See defect:
on the list are selected elements but on the input, you don't have anything 
![image](https://user-images.githubusercontent.com/97100687/212874564-35c235bc-72d5-4317-a7c5-f24ea4bd386d.png)

### Expected behavior

input and list should be consistent

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### Theme

all

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

Chrome

**Comment by melloware** [comment]
I have NO idea why it cared about unselecting only visible items that makes no sense to me. Here is a MonkeyPatch: 

```js
if (PrimeFaces.widget.SelectCheckboxMenu) {
    PrimeFaces.widget.SelectCheckboxMenu.prototype.uncheckAll = function(silent) {
        if (!this.isLoaded()) {
            this._renderPanel();
        }
        for (var i = 0; i < this.items.length; i++) {
            var el = this.items.eq(i);
            var input = this.inputs.eq(i);
            var inputNative = input[0];

            if (!inputNative.disabled) {
                this.inputs.eq(i).prop('checked', false);
                this.uncheck(el.children('.ui-chkbox').children('.ui-chkbox-box'));
            }
        }

        if (this.cfg.multiple) {
            this.multiItemContainer.children().remove();
        }

        this.uncheck(this.togglerBox);

        if (!silent) {
            var togglerInput = this.togglerBox.prev().children('input');
            if (this.cfg.onChange) {
                this.cfg.onChange.call(this);
            }

            if (!this.togglerBox.hasClass('ui-state-disabled')) {
                togglerInput.trigger('focus.selectCheckboxMenu');
            }

            if (this.cfg.multiple) {
                this.alignPanel();
            }

            this.fireToggleSelectEvent(false);
        }

        this.renderLabel();
    }
};
```

**Comment by ltlBeBoy** [comment]
@melloware It has to be the opposite! When you filter the items and unselect the toggler, then only the filtered items have to be removed from the labels and list (just "Miami" in this case). All other (non filtered items) still have to be selected.

**Comment by melloware** [comment]
So i was reading their request as the opposite when you say "unselect all" they want everything unselected?   You think its just the values that are displayed?  So basically this is the bug

```js
        if (this.cfg.multiple) {
            this.multiItemContainer.children().remove();
        }
```

Its always removing all chips whenever uncheckAll is called.

**Comment by melloware** [comment]
Updated monkeypatch the bug was this...

```js
                    if (this.cfg.multiple) {
                        this.multiItemContainer.children('[data-item-value="'+el.text()+'"]').remove();
                    }
```

needed to just remove the token matching the item

**Comment by ltlBeBoy** [comment]
@melloware DRY, please use following code instead:
```
                    if (this.cfg.multiple) {
                        this.removeMultipleItem(el);
                    }
```

**Comment by melloware** [comment]
Fixed! Thanks,
