### ISSUE TITLE
SelectCheckboxMenu: Multiple Validation update clean input 

### ISSUE THREAD

**Issue by reginakupczak** [primefaces/primefaces#9693]
### Describe the bug

Multiple Validation update clean input 

### Reproducer
```xml
 <p:selectCheckboxMenu id="roleEdit" value="#{checkboxView.selectedCities2}"
                                      multiple="true" 
                                      filter="true" required="true" 
                                       requiredMessage="Can't unselect Miami"
                                      filterMatchMode="startsWith" 
                                       validator="#{checkboxView.validate}">
                    <f:selectItems value="#{checkboxView.cities}" />
                    <p:ajax event="change" update="roleEdit"/>
                </p:selectCheckboxMenu>
                <p:message id="roleEditMsg" for="roleEdit" display="text"/>
```

```java
     @Override
        public void validate(final FacesContext context, final UIComponent component, final List value) throws ValidatorException {
            if (value.stream().noneMatch(v -> v.equals("Miami"))){
                throw new ValidatorException("Miami should be selcted");
            }
        }
```

1. add all to selectCheckboxMenu
2. remove Miami to run validation
3. All elements are removed from the input, validation message is shown.
4. Open the list
5. All elements on the list are still selected

See error
Validation shouldn't clean correct values, List and input should show the same values
![image](https://user-images.githubusercontent.com/97100687/212882397-558cbcd1-9d46-4346-8778-3dc3dcba62d3.png)

### Expected behavior

The list and input should show the same values

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### Theme

all

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

Chrome

**Comment by melloware** [comment]
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment]
cc @ltlBeBoy

**Comment by reginakupczak** [comment]
@melloware  code is based on the http://www.primefaces.org:8080/showcase/ui/input/checkboxMenu.xhtml?jfwid=b4694
`@Named
@RequestScoped
public class CheckboxView {

    private String[] selectedOptions;
    private String[] selectedOptions2;
    private String[] selectedCities;
    private String[] selectedCities2;
    private List<String> cities;
    private List<SelectItem> countries;
    private String[] selectedCountries;

    @PostConstruct
    public void init() {
        cities = new ArrayList<>();
        cities.add("Miami");
        cities.add("London");
        cities.add("Paris");
        cities.add("Istanbul");
        cities.add("Berlin");
        cities.add("Barcelona");
        cities.add("Rome");
        cities.add("Brasilia");
        cities.add("Amsterdam");

        countries = new ArrayList<>();
        SelectItemGroup europeCountries = new SelectItemGroup("European Countries");
        europeCountries.setSelectItems(new SelectItem[]{
            new SelectItem("Germany", "Germany"),
            new SelectItem("Turkey", "Turkey"),
            new SelectItem("Spain", "Spain")
        });

        SelectItemGroup americaCountries = new SelectItemGroup("American Countries");
        americaCountries.setSelectItems(new SelectItem[]{
            new SelectItem("United States", "United States"),
            new SelectItem("Brazil", "Brazil"),
            new SelectItem("Mexico", "Mexico")
        });

        countries.add(europeCountries);
        countries.add(americaCountries);
    }

    public String[] getSelectedOptions() {
        return selectedOptions;
    }

    public void setSelectedOptions(String[] selectedOptions) {
        this.selectedOptions = selectedOptions;
    }

    public String[] getSelectedOptions2() {
        return selectedOptions2;
    }

    public void setSelectedOptions2(String[] selectedOptions2) {
        this.selectedOptions2 = selectedOptions2;
    }

    public String[] getSelectedCities() {
        return selectedCities;
    }

    public void setSelectedCities(String[] selectedCities) {
        this.selectedCities = selectedCities;
    }

    public String[] getSelectedCities2() {
        return selectedCities2;
    }

    public void setSelectedCities2(String[] selectedCities2) {
        this.selectedCities2 = selectedCities2;
    }

    public List<String> getCities() {
        return cities;
    }

    public void setCities(List<String> cities) {
        this.cities = cities;
    }

    public List<SelectItem> getCountries() {
        return countries;
    }

    public void setCountries(List<SelectItem> countries) {
        this.countries = countries;
    }

    public String[] getSelectedCountries() {
        return selectedCountries;
    }

    public void setSelectedCountries(String[] selectedCountries) {
        this.selectedCountries = selectedCountries;
    }

    public void onItemUnselect(UnselectEvent event) {
        FacesMessage msg = new FacesMessage();
        msg.setSummary("Item unselected: " + event.getObject().toString());
        msg.setSeverity(FacesMessage.SEVERITY_INFO);

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void selectedOptionsChanged() {
        String message = "selectedOptions changed to: ";
        if (selectedOptions != null) {
            for (int i = 0; i < selectedOptions.length; i++) {
                if (i > 0) {
                    message += ", ";
                }
                message += selectedOptions[i];
            }
        }

        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    public void selectedOptions2Changed() {
        String message = "selectedOptions2 changed to: ";
        if (selectedOptions2 != null) {
            for (int i = 0; i < selectedOptions2.length; i++) {
                if (i > 0) {
                    message += ", ";
                }
                message += selectedOptions2[i];
            }
        }

        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    public void validate(final FacesContext context, final UIComponent component, final List value) throws ValidatorException {
            if (value.stream().noneMatch(v -> v.equals("Miami"))){
                throw new ValidatorException("Miami should be selcted");
            }
        }
}`

**Comment by jepsar** [comment]
Most of the developers are working on PrimeFaces in their spare time. Creating a runnable reproducer will be very helpful and will save us time to spend on other issues. Please see https://github.com/primefaces/primefaces#community--elite--pro

**Comment by melloware** [comment]
Two issues with your non-reproducer.

1. There is no Constructor that takes a String `throw new ValidatorException("Miami should be selcted");` ??? I had to make it...

```java
throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_INFO, "Miami should be selcted", null));
```

2. I am getting this error...

```
javax.el.MethodNotFoundException: Method not found: org.primefaces.showcase.view.input.CheckboxView@167461a9.validate(javax.faces.context.FacesContext, javax.faces.component.UIComponent, java.lang.Object)
        at org.apache.el.util.ReflectionUtil.getMethod(ReflectionUtil.java:297)
        at org.apache.el.parser.AstValue.invoke(AstValue.java:239)
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:266)

```

Trying to use your exact example:

```java
    public void validate(final FacesContext context, final UIComponent component, final List value) throws ValidatorException {
        if (value.stream().noneMatch(v -> v.equals("Miami"))) {
            throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_INFO, "Miami should be selcted", null));
        }
    }
```

So please provide an actual reproducer that works...

**Comment by melloware** [comment]
Will close this for now. Will re-open if @reginakupczak can provide a working reproducer.

**Comment by reginakupczak** [comment]
<p:selectCheckboxMenu id="roleEdit" value="#{checkboxView.selectedCities2}"
                          multiple="true"
                          filter="true" required="true"
                          requiredMessage="Can't unselect Miami"
                          filterMatchMode="startsWith"
                          validator="#{checkboxValidator.validate}">        
<f:selectItems value="#{checkboxView.cities}" />    </p:selectCheckboxMenu>    
<p:message id="roleEditMsg" for="roleEdit" display="text"/>    
<p:commandButton id="SaveBtn" update="roleEdit,roleEditMsg"/>

package com.dn.vs.server.framework.users.validator;
import org.springframework.stereotype.Component;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.Validator;
import javax.faces.validator.ValidatorException;
import javax.faces.view.ViewScoped;
import java.io.Serializable;
@Component
@ViewScoped
public class CheckboxValidator implements Validator, Serializable {
    @Override
    public void validate(FacesContext context, UIComponent component, Object value) throws ValidatorException {
        String values = value.toString();
        if (!values.contains("Miami")) {
            FacesMessage msg = new FacesMessage("Miami should be selected");
            msg.setSeverity(FacesMessage.SEVERITY_ERROR);
            throw new ValidatorException(msg);
        }
    }
}
package com.dn.vs.server.framework.data;
import org.primefaces.event.UnselectEvent;
import org.springframework.stereotype.Component;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.model.SelectItemGroup;
import javax.faces.validator.ValidatorException;
import java.util.ArrayList;
import java.util.List;
@Component
public class CheckboxView {
    private String[] selectedOptions;
    private String[] selectedOptions2;
    private String[] selectedCities;
    private String[] selectedCities2;
    private List<String> cities;
    private List<SelectItem> countries;
    private String[] selectedCountries;
    @PostConstruct
    public void init() {
        cities = new ArrayList<>();
        cities.add("Miami");
        cities.add("London");
        cities.add("Paris");
        cities.add("Istanbul");
        cities.add("Berlin");
        cities.add("Barcelona");
        cities.add("Rome");
        cities.add("Brasilia");
        cities.add("Amsterdam");
        countries = new ArrayList<>();
        SelectItemGroup europeCountries = new SelectItemGroup("European Countries");
        europeCountries.setSelectItems(new SelectItem[]{
                new SelectItem("Germany", "Germany"),
                new SelectItem("Turkey", "Turkey"),
                new SelectItem("Spain", "Spain")
        });
        SelectItemGroup americaCountries = new SelectItemGroup("American Countries");
        americaCountries.setSelectItems(new SelectItem[]{
                new SelectItem("United States", "United States"),
                new SelectItem("Brazil", "Brazil"),
                new SelectItem("Mexico", "Mexico")
        });
        countries.add(europeCountries);
        countries.add(americaCountries);
    }
    public String[] getSelectedOptions() {
        return selectedOptions;
    }
    public void setSelectedOptions(String[] selectedOptions) {
        this.selectedOptions = selectedOptions;
    }
    public String[] getSelectedOptions2() {
        return selectedOptions2;
    }
    public void setSelectedOptions2(String[] selectedOptions2) {
        this.selectedOptions2 = selectedOptions2;
    }
    public String[] getSelectedCities() {
        return selectedCities;
    }
    public void setSelectedCities(String[] selectedCities) {
        this.selectedCities = selectedCities;
    }
    public String[] getSelectedCities2() {
        return selectedCities2;
    }
    public void setSelectedCities2(String[] selectedCities2) {
        this.selectedCities2 = selectedCities2;
    }
    public List<String> getCities() {
        return cities;
    }
    public void setCities(List<String> cities) {
        this.cities = cities;
    }
    public List<SelectItem> getCountries() {
        return countries;
    }
    public void setCountries(List<SelectItem> countries) {
        this.countries = countries;
    }
    public String[] getSelectedCountries() {
        return selectedCountries;
    }
    public void setSelectedCountries(String[] selectedCountries) {
        this.selectedCountries = selectedCountries;
    }
    public void onItemUnselect(UnselectEvent event) {
        FacesMessage msg = new FacesMessage();
        msg.setSummary("Item unselected: " + event.getObject().toString());
        msg.setSeverity(FacesMessage.SEVERITY_INFO);
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
    public void selectedOptionsChanged() {
        String message = "selectedOptions changed to: ";
        if (selectedOptions != null) {
            for (int i = 0; i < selectedOptions.length; i++) {
                if (i > 0) {
                    message += ", ";
                }
                message += selectedOptions[i];
            }
        }
        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }
    public void selectedOptions2Changed() {
        String message = "selectedOptions2 changed to: ";
        if (selectedOptions2 != null) {
            for (int i = 0; i < selectedOptions2.length; i++) {
                if (i > 0) {
                    message += ", ";
                }
                message += selectedOptions2[i];
            }
        }
        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }
}

It looks like it is working now, @melloware please close the ticket.
