### ISSUE TITLE
Global Attributes: Cannot overwrite a global attribute value from backing bean

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#9694]
## 1) Environment
PrimeFaces version: PrimeFaces-12.0
Application server: Jetty 9.4.50.v20221201
JSF version: mojarra 2.3.18

### 2) Describe the defect

Global component attribute configuration can be done by using: https://primefaces.github.io/primefaces/12_0_0/#/core/globalattributes?id=application-wrapper

The problem with this solution is that overwriting a component global attribute based on a backing bean value is not working (the global attribute value is always returned). Using a hardcoded attribute value to overwrite works however fine. This reduces the usefulness of global component attributes.

### 3) Reproducer
See:
[primefaces-test-global.zip](https://github.com/primefaces/primefaces/files/10435218/primefaces-test-global.zip)

Run:
mvn clean jetty:run -Pmojarra23

Example inputs
field1 => no maxlength, global default is assumed
field2 => hardcoded maxlength="10"
field3 => maxlength 20 from backing bean [NOT WORKING]

Press button "show maxlength" to see the generated html maxlength values.

**Comment by tandraschko** [comment]
globalattributes is not a feature or anything of PF, we cant fix something here. We just showed up that there is a way with the JSF spec to create something similar to global attributes.

We plan to create something for 4.1: https://github.com/jakartaee/faces/issues/1602

**Comment by tandraschko** [comment]
but feel free to optimize the docs here ;)

**Comment by melloware** [comment]
Agreed @tandraschko this was just a way of showing how to globally set and attribute you DON'T want to change anywhere for consistency in your app like a date `pattern` you want to the same throughout your app.

**Comment by DazzlingBob** [comment]
Thanks for the comments and updating the documentation. Have another one for the documentation, am not sure how to change this (and it is only valid for JSF 2.3). To prevent deprecation warnings the global attributes can also be written as follows. See https://github.com/primefaces/primefaces/issues/9518.

```
import javax.faces.application.Application;
import javax.faces.application.ApplicationWrapper;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

import org.primefaces.component.api.UICalendar;

public class DemoApplication extends ApplicationWrapper {

	public DemoApplication(Application wrapped) {
		super(wrapped);
	}

	@Override
	public UIComponent createComponent(FacesContext context, String componentType, String rendererType) {
		UIComponent component = super.createComponent(context, componentType, rendererType);

		// set a global date pattern by default
		if (component instanceof UICalendar) {
			UICalendar calendar = (UICalendar) component;
			calendar.setPattern("dd-MMM-yyyy");	
		}
		
		return component;
	}

}

```

```
import javax.faces.application.Application;
import javax.faces.application.ApplicationFactory;

public class DemoApplicationFactory extends ApplicationFactory {

	public DemoApplicationFactory(ApplicationFactory wrapped) {
		super(wrapped);
	}

	@Override
	public Application getApplication() {
		return new DemoApplication(getWrapped().getApplication());
	}

	@Override
	public void setApplication(Application application) {
		getWrapped().setApplication(application);
	}

}

```

**Comment by melloware** [comment]
You are right I will update he docs for 2.3 since that is what 90% of people are using now anyway.
