### ISSUE TITLE
DataView not working properly with Dialog / ContextMenu

### ISSUE THREAD

**Issue by xLevision** [primefaces/primefaces#9697]
### Describe the bug

The p:dataView always sends the last value of it´s var if there is a <p:dialog> or <p:contextMenu> inside.

### Reproducer

The last element of list is sent if you use a contextMenu:

```
<p:dataView var=test" value="#{dummyBean.list}">
    <p:contextMenu>
        <p:commandButton action="#{dummyBean.setSelected(test)" />
    </p:contextMenu>
</p:dataView>
```

or if you use a dialog:

```
<p:dataView var=test" value="#{dummyBean.list}">
    <p:dialog>
        <p:outputLabel action="#{test.field)" />
    </p:dialog>
</p:dataView>
```

### Expected behavior

The right value is sent to bean or shown in dialog.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.X

### Java version

17

**Comment by melloware** [comment]
This might be a stupid question but why does your dataview contain either one of these things?  Shouldn't they both live outside the DataView?

**Comment by Interlogy** [comment]
> This might be a stupid question but why does your dataview contain either one of these things? Shouldn't they both live outside the DataView?

For the same reason why you need a dialog or a context menu for dataTable. :)

Dialog could live outside, but you cant show any data regarding to the DataView, as always the last item value is sent to backend.

**Comment by Interlogy** [comment]
> Hmm but the same answer goes for datatable I render my dialogs and context menu outside the datatable ??

Yes sure, but if you want to show a field of the Object, then you have to save it to the bean. But this is not working as the last Object of the list is used always.

**Comment by Interlogy** [comment]
> This might be a stupid question but why does your dataview contain either one of these things? Shouldn't they both live outside the DataView?

Indeed its working when i move the dialog outside the dataView. 
I think this issue can be closed.

**Comment by melloware** [comment]
It's better practice too you don't want the dialog rernedrrjnt in the dataview duplicating it's html per dataview cell. You want 1 dialog on the whole page you just update. Your page is now "more correct"
