### ISSUE TITLE
DataExporter: ignores f:convertNumber 

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#9701]
### Describe the bug

In case of datatable columns of the following kind

```
      <p:column field="x" headerText="x">
        <h:outputText value="#{entity.x}">
          <f:convertNumber pattern="0.00" />
        </h:outputText>
      </p:column>

```
it seems to be that the f:convertNumber converted values are not used by the data exporter. see example below. exporting

![Screenshot from 2023-01-18 14-01-43](https://user-images.githubusercontent.com/10051373/213180400-efaac175-9f0f-4103-8737-c65a61f3d8ec.png)

delivers

![Screenshot from 2023-01-18 14-02-48](https://user-images.githubusercontent.com/10051373/213180559-6e5cc672-f2bf-4f08-bebb-e26af08ffcc6.png)

Many thanks in advance for looking into this issue.

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

**Comment by melloware** [comment]
Same answer as this one: https://github.com/primefaces/primefaces/issues/9699

**Comment by tuerker** [comment]
I had the feeling that this could be an easily fixable issue but then you would have done this already. thanks for your quick response.
