### ISSUE TITLE
Scrollable datatable with vertical scroll feature only

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primefaces#971]
Even if we won't define the horizontal scroll(scrollWidth property) feature dataTable displayed with horizontal scroll when it contains more number of columns.In this case datatable should be displayed  with page level scroll instead of component level scroll.

The issue is replicated in showcase by just adding around 15 columns with some width property values as below.

![image](https://cloud.githubusercontent.com/assets/3127317/11930934/3a4ef516-a80e-11e5-99d8-da0b44830b5f.png)

**Comment by kukel** [comment]
Are you sure this is not cause by some other css thing?

**Comment by mtbadi39** [comment]
Another but related issue :
with : scrollable="true" scrollHeight="150"
without :  scrollWidth
**Header** and **Content** are not correctly aligned  !
![p](https://cloud.githubusercontent.com/assets/8750684/12377124/4c610546-bd12-11e5-89db-60f846022818.png)

**Comment by kukel** [comment]
@mtbadi39: Please post your PF  version... always...

**Comment by sudheerj** [comment]
Yes it is not caused by any other CSS styles.As mentioned earlier It can be replicated in showcase as well.

**Comment by cagataycivici** [comment]
Can you post the datatable code please?

**Comment by joerowe** [comment]
I actually experience the same issue which also prevents priority column functionality - that is to say, when scrollable is set true and a scrollHeight given, the automatic application of scrollwidth prevents columns marked as priority from disappearing. 

My datatable header code is shown below:

<p:dataTable id="searchDataTable" widgetVar="searchDataTable"
		draggableColumns="true"
		value="...<<REMOVED>>...."
		var="listItemVO" sortMode="multiple" reflow="true" rows="20"
		paginator="true" scrollable="true" scrollHeight="590">

I have also tried this by removing all properties from the table except the value, var, and scrollable/scrollheight/rows combination and get the same behaviour.
