### ISSUE TITLE
SelectOneMenu in datatable within a scrollPanel causes a scroll to the left

### ISSUE THREAD

**Issue by aibarria** [primefaces/primefaces#9718]
### Describe the bug

When I have a selectOneMenu in a dataTable and this dataTable is inside a scroll panel (mode="native") when moving the scroll to the right and clicking in selectOneMenu a scroll left is done.

https://user-images.githubusercontent.com/78151180/214001941-5750f637-fdfa-4b37-8aa5-fdae15e45d5b.mp4

### Reproducer

It can be reproduced with this xhtml code, the data for the table is indifferent.

`<p:scrollPanel id="scrollpanel" mode="native" style="width:600px;border:none;" >
          <p:dataTable id="conditionsTable"
			value="#{testHandler.data}"
			rowIndexVar="rowIndex"
			var="row" style="width:1000px" >
		<p:column id="prioCol" headerText="Col">
				<h:outputText value="#{rowIndex + 1}" />
		</p:column>
		<p:column id="prioCol" headerText="Col">
			<h:outputText value="test" />
		</p:column>
		<p:column id="prioCol" headerText="Col">
			<h:outputText value="test" />
		</p:column>
		<p:column id="prioCol" headerText="Col">
			<h:outputText value="test" />
		</p:column>
		<p:column id="prioCol" headerText="Col">
			<h:outputText value="test" />
		</p:column>
		<p:column id="prioCol" headerText="Col">
			<h:outputText value="test" />
		</p:column>						
		<p:column id="country1" headerText="Country1">
			<p:inputText value="#{row.code1}">
		</p:inputText>
		</p:column>
		<p:column id="country2" headerText="Country2">
			<p:selectOneMenu id="code2" value="#{row.code2}" >
				<f:selectItem itemValue="#{null}" itemLabel="" />
				<f:selectItem itemValue="es" itemLabel="Spain" />
				<f:selectItem itemValue="de" itemLabel="Germany" />
				<f:selectItem itemValue="en" itemLabel="England" />
			</p:selectOneMenu>
		</p:column>
		<p:column id="country3" headerText="Country3">
			<p:selectOneMenu id="code3" value="#{row.code3}" >
				<f:selectItem itemValue="#{null}" itemLabel="" />
				<f:selectItem itemValue="es" itemLabel="Spain" />
				<f:selectItem itemValue="de" itemLabel="Germany" />
				<f:selectItem itemValue="en" itemLabel="England" />
			</p:selectOneMenu>
		</p:column>
	</p:dataTable>
</p:scrollPanel>`

### Expected behavior

When I click in selectOneMenu don´t change the scroll

### PrimeFaces edition

Community

### PrimeFaces version

11.0.0

### Theme

Aristo

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment]
We need the testHandler or a whole primefaces-test
also please try on 13.0.0-SNAPSHOT, we dont support older versions here: https://github.com/primefaces/primefaces#community--elite--pro

**Comment by aibarria** [comment]
Whole primefaces-test

[Primefaces-Test-master.zip](https://github.com/primefaces/primefaces/files/10478828/Primefaces-Test-master.zip)

**Comment by melloware** [comment]
Working fine for me in both Chrome and Firefox on PF 12.0.0.  

Proper 12.0.0 reproducer here:
[pf-9718.zip](https://github.com/primefaces/primefaces/files/10480999/pf-9718.zip)

**Comment by aibarria** [comment]
I have seen the problem doesn´t occur with the saga theme but does with the aristo theme which is the one we are using. 
`        <dependency>
			<groupId>org.primefaces.themes</groupId>
			<artifactId>aristo</artifactId>
			<version>1.0.1</version>
		</dependency>`

**Comment by tandraschko** [comment]
aristo and other legacy themes are not supported anymore

**Comment by melloware** [comment]
As Thomas said those legacy ThemeRoller themes aren't even supported really by jQuery UI anymore so they have been dropped entirely after PF10.  I highly recommend you switch to a PrimeTek supported theme like Saga.

See ticket about Aristo and ThemeRoller: https://github.com/primefaces/primefaces/issues/6002
