### ISSUE TITLE
InputNumber: Does not respect @Max/@DecimalMax annotation

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#9732]
### Describe the bug

When the following min/max annotations are placed (as for instance on the showcase):

```
    @DecimalMin("10")
    @DecimalMax("100")
    private Double input1;

    @Min(10)
    @Max(100)
    private Double input2;
```

then the corresponding p:inputNumber components do not respect these max values and apply different handling for min and max.

My expectation was that p:inputNumber does not allow at least entering values beyond the max value. Note that i am running with these context-params:

```
  <context-param>
    <param-name>jakarta.faces.validator.ENABLE_VALIDATE_WHOLE_BEAN</param-name>
    <param-value>true</param-value>
  </context-param>
  <context-param>
    <param-name>primefaces.TRANSFORM_METADATA</param-name>
    <param-value>true</param-value>
  </context-param>
```

Actually entering value larger than the max value are stored as max value, e.g. entering 234 is stored as 100.
In contrast, in case of the min value, entering 5 which is lower than the min value 10 leads to a validation error, which is reasonable.

Many thanks in advance for looking into this issue.

### Expected behavior

The values specified in the min/max annotations should be enforced by p:inputNumber.

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
Have you inspected the DOM in the browser to see what values are being passed to the widget from the server side?    This might be an AutoNumeric issue. Does the same thing happen when you just enter a min and max right in the XHTML instead of the annotations?

**Comment by tuerker** [comment]
using 

```
<p:inputNumber ... minValue="10" maxValue="100" ...
```

has the same effect on the max value. value beyond the max are set to max. in case of min, it is exactly the same behavior, entering 5 is set to 10.

**Comment by melloware** [comment]
Ok then I think this is an issue with AutoNumeric  and not with PF if that is the behavior.  

What are you expecting the behavior to do?   You thought it would throw an error and not just constrain you to the min or max?

**Comment by tuerker** [comment]
ideally, i constrains the entering such that i cannot enter values larger than max. in case of min, it is a little bit trickier since you have to know when the entering is done. then, there are three different possible behavior:

1) set to the min value but drop a message 
2) clear value and drop a message
3) do nothing and wait for the valiation error in case of @min/@decimalmin annotations.

**Comment by tuerker** [comment]
in any case, the minimum behavior would be to throw a validation error whenever the constraints are not satisfied.

**Comment by tuerker** [comment]
good night.

**Comment by melloware** [comment]
I think this is just how AutoNumeric works. Nothing PF can do about it. You might be able to research AutoNumeic to see if they have settings that do what you want or open tickets at Autonumeric.

**Comment by tuerker** [comment]
i know that autonumeric has some more unexpected behavior. will place an issue there. thanks and good night.

**Comment by tuerker** [comment]
maybe it is worth to mention this behavior in the PF documentation.

**Comment by melloware** [comment]
Yeah you can test it here to see what raw Autonumeric does: http://autonumeric.org/examples

**Comment by tuerker** [comment]
thanks for the hint. playing with this playing confuses me now. when i use the following restrictions, it works as desired:

```
{
    decimalPlaces: 0,
    maximumValue: "100",
    minimumValue: "1"
}
```

it allows only integers between 1 and 100.

so this raises the question how the min/max-annotations are considered when mapping to inputNumber to autonumeric?

**Comment by tuerker** [comment]
or more general how the p:inputNumber minValue and maxValue attributes are mapped to autonumeric maximumValue and minimumValue?

**Comment by tuerker** [comment]
just a naive question: could it be that the mapping is not taken since the attributes are differently named in PF and autonumeric:

maxValue vs. maximumValue?

**Comment by tuerker** [comment]
it is actually a PF mapping issue. will do a PR.

**Comment by tuerker** [comment]
one could come to the conclusion that the inputNumber attributes minValue as well as maxValue are ignored whenever minValue > 0 or maxValue < 0. 

I did the following adaptations of the showcase to infer this:

```
<div class="field col-12 md:col-4">
  <p:outputLabel for="input3w" value="Min-Max minValue=1 maxValue=100"/>
  <p:inputNumber id="input3w" value="#{inputNumberView.input3}" minValue="1" maxValue="100" decimalPlaces="0" />
</div>

<div class="field col-12 md:col-4">
  <p:outputLabel for="input3x" value="Min-Max minValue=-100 maxValue=-1"/>
  <p:inputNumber id="input3x" value="#{inputNumberView.input3}" minValue="-100" maxValue="-1" decimalPlaces="0" />
</div>

<div class="field col-12 md:col-4">
  <p:outputLabel for="input3y" value="Min-Max minValue=-100 maxValue=0"/>
  <p:inputNumber id="input3y" value="#{inputNumberView.input3}" minValue="-100" maxValue="0" decimalPlaces="0" />
</div>

<div class="field col-12 md:col-4">
  <p:outputLabel for="input3z" value="Min-Max  minValue=0 maxValue=100"/>
  <p:inputNumber id="input3z" value="#{inputNumberView.input3}" minValue="0" maxValue="100" decimalPlaces="0" />
</div>
```

See outcome in the following screentshot:

![Screenshot from 2023-01-26 12-20-16](https://user-images.githubusercontent.com/10051373/214824388-84439425-dcf2-474e-954d-9a9ae2cda747.png)

It seems to be an autonumeric issue and actually it is definitely not directly caused by the min/max annotations.

I did several tests on http://autonumeric.org/examples:

While the following (minValue=1 maxValue=100) worked here as it should be but not via the PF showcase:

![Screenshot from 2023-01-26 12-29-21](https://user-images.githubusercontent.com/10051373/214825799-c27ba9ef-71aa-4964-8977-b8d279ef53e4.png)

The following (minValue=-100 maxValue=-1") did not work analogously to the PF showcase above:

![Screenshot from 2023-01-26 12-30-44](https://user-images.githubusercontent.com/10051373/214825801-cdf1c438-6174-4703-bf8f-db912ac4794b.png)

The following two worked as in the PF showcase, too:

![Screenshot from 2023-01-26 12-41-10](https://user-images.githubusercontent.com/10051373/214827345-5d5d3089-d948-4b62-8131-5a6f6c5c1fb6.png)

![Screenshot from 2023-01-26 12-42-57](https://user-images.githubusercontent.com/10051373/214827346-2b10de80-78c3-47de-8394-95949661b0d7.png)

The following one (minValue=10 maxValue=120) which similar to the first example in constrast did not work.

![Screenshot from 2023-01-26 12-31-50](https://user-images.githubusercontent.com/10051373/214825755-caf8dc3c-76a2-461a-9766-22378742d823.png)

I am totally confused by the observations above.

@melloware can you verify this behavior?

**Comment by tuerker** [comment]
placed an issue on autonumeric: https://github.com/autoNumeric/autoNumeric/issues/759

**Comment by melloware** [comment]
I think its explained in PF by this...

```js
        // GitHub #8125 minValue>0 shows js warning and quirky behavior
        if (this.cfg.minimumValue > 0.0000001 || this.cfg.maximumValue < 0) {
            this.cfg.overrideMinMaxLimits = 'invalid';
        }
```
See: #8125
See: #9328

Then read this about `overrideMinMaxLimits` https://github.com/autoNumeric/autoNumeric/issues/543
