### ISSUE TITLE
DataTable: no headers and footers in export in Primefaces 12 / in Primefaces 11.0 all headers and footers are in export

### ISSUE THREAD

**Issue by slauf82** [primefaces/primefaces#9735]
### Describe the bug

You forgot to export the headers and footers in Primefaces 12.0 with your new version of DataTable. In the Version before, Primefaces 11.0 all was good and all headers and footers are in the export. Please fix this.

### Expected behavior

Only in Primefaces 12.0, not in 11.0 and before all headers and footers will not be exported with DataExporter only the main table will be successfully exported to XSLX, XSL, CSV, PDF (that's all tested) and all other formats have the same issues, i think, but that's untested.

### PrimeFaces edition

Community

### PrimeFaces version

12.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

11.0

**Comment by melloware** [comment]
Fixed in 12.0.1 if you are an Elite subscriber.
