### ISSUE TITLE
DataExporter: Footer Text ignoring `exportable="false"`

### ISSUE THREAD

**Issue by arifakkas** [primefaces/primefaces#9746]
### Describe the bug

Description:
I'm using columnGroup with footerText at the bottom to provide sum of the column values as shown in the use case. In order to handle the alignment I put some empty columns before the actual footerText columns. I have a column with exportable=false on datatable, so I assigned one of the empty columns' exportable value as false. PDF export works without a problem but xls exporter doesn't recognize this exportable=false footerText column and this leads to an alignment issue on excel file.

In a nutshell, excel exporter doesn't recognize the exportable=false value on footerText column values.

This exports are from the same page, as you can see there is one column more on excel, which is the exportable=false column.
![p1](https://user-images.githubusercontent.com/45760828/215775063-2e27563f-9d72-494e-bc12-2c7dcabee986.jpg)
![p2](https://user-images.githubusercontent.com/45760828/215775093-0711bf49-47b8-41e8-9e28-e5bb7e7b2b08.jpg)

### Reproducer
This project contains the scenario that I mentioned.
[test.zip](https://github.com/primefaces/primefaces/files/10547524/test.zip)

### Expected behavior

The exportable=false value on footerText column should affect the excel export.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Sentinel

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

11

**Comment by melloware** [comment]
Can you create a reproducr executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  

Looking at the code PDF and Excel both as for `getExportableColumns` which handles only including columns with exportable="true" on them.

**Comment by arifakkas** [comment]
I provided the sample project on reproducer part.

**Comment by melloware** [comment]
Thanks didn't see it.  Looking now.

**Comment by melloware** [comment]
I see this was already fixed in Elite 12.0.1 and 13.0.0-SNAPSHOT.

See: https://github.com/primefaces/primefaces/issues/9290

**Comment by arifakkas** [comment]
Thank you, I didn't see it, with my best regards.
