### ISSUE TITLE
Galleria: Responsive mode

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#975]
Add an option to Galleria to make it responsive

**Comment by grburgos** [comment]
Any updates on this feature?

**Comment by wsaca** [comment]
If this feature were implemented some day, I would like to see an improved galleria like this one: https://galleria.io/

**Comment by melloware** [comment]
PrimeReact has implemented a galleria from scratch with tons of features and built in responsiveness.

https://www.primefaces.org/primereact/showcase/#/galleria

The PF component should be updated to match

**Comment by melloware** [comment]
According to this announcement Galleria and Carousel are being completely updated to match their equivalent in PrimeVue/React so closing this ticket.
See: https://www.youtube.com/watch?v=SqeoPsPQwOw
