### ISSUE TITLE
Treetable: Default filtering

### ISSUE THREAD

**Issue by Vraken** [primefaces/primefaces#9757]
### Describe the bug

PF Version : 12

In Treetable component, default filter on a column does not work.

I highly suspect that the problem comes from `TreeTableRenderer.encodeEnd()` specially from the test : 
` if (tt.isDefaultFilter()) ` which never returns true

As a workaround, I replaced the previous test by :
`if (tt.isFilteringCurrentlyActive()`

### Reproducer

For example : 
Sample XHTML  
```
<p:treeTable value="#{controller.items}" var="item" >
        <p:column  filterable="true"  filterBy="#{item.status}" filterValue="#{controller.statusValue}">
            <h:outputText value="#{item.name}"/>
        </p:column>
</p:treeTable>
```

Sample bean
```
@Named
@RequestScoped
public class MyController implements Serializable {

   private List<Item> items;
   private Status status;
   
    @PostConstruct
    public void init() {
        setStatus(Status.READY);
    }

    public Status getStatusValue() {
        return statusValue;
    }

   public void setStatus(Status status) {
        statusValue =status;
    }
...
}
```

Column is filterable on click, but there is no filter by default.

### Expected behavior

Column should be sorted on first Treetable loading if a default filter is specified

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

**Comment by melloware** [comment]
@Vraken feel free to submit a PR!

Also I wonder if its related to this issue: https://github.com/primefaces/primefaces/issues/9254

**Comment by melloware** [comment]
Actually i think there are two problems here. Let me submit a PR for review.

**Comment by Rapster** [comment]
I recently faced that issue, makes me wonder how come `UITable#isDefaultFilter` returns false...?
