### ISSUE TITLE
Filter Constraints: move to a separate class

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#9767]
### Description

Filter constraints are defined in `FilterFeature` of `DataTable` while it's actually used in 2 other components. 3 Components use this so far, and each of them duplicate the definition of `FILTER_CONSTRAINTS`:
- DataTable
- TreeTable _(use filter constraints through `FilterFeature` of `DataTable`)_
- Tree

### Describe the solution you would like

Move these into a single class

**Comment by Rapster** [comment]
@newk5 Do you have a sample or a reproducer to show please? The error you mentionned in #9775 shows that `Column#getFilterMatchMode` returns null, while the default value is `startsWith`.

**Comment by newk5** [comment]
Sorry I dont have a reproducer, it happened only in some pages in my app, not all, so I dont know what triggered the issue, maybe something in my code, but I can say with 100% certainty, that null match modes were allowed previous to this commit.

If it helps, I can say I'm using lazy datatables with dynamic columns and they were nested inside a composite component.

**Comment by Rapster** [comment]
Yes having a match mode null was allowed, but I don't know if it makes a lot of sense... How do you know how to filter on that column then? Because `FilterMeta#matchMode` would be null so far in your use case

**Comment by newk5** [comment]
There's some cases on some of our LazyDataModels where we are not even looking at the match mode, we just know by field name, how to filter/query the db so it doesn't matter if match mode is null.

**Comment by Rapster** [comment]
That's what I thought, so basically you configure 75% of your FilterMeta on one side, and the other 25% in the `LazyDataModel#load` method, that's not a very clean approach... I'll let @melloware and @tandraschko share their thoughts, and bring some defensive code 🤮 if required

**Comment by newk5** [comment]
In a perfect world sure, one would have a single source of truth, being the match mode specified on the FilterMeta, but I dont think this is the case in many real world applications, especially legacy stuff. I know some of our more recent applications work just off the FilterMeta match mode, but some of our older applications that were migrated from previous PF versions, dont work like that.

Overall I think the FilterMeta match mode is a good hint to have, but when working with Lazy DataModels I think it should be just that, a hint. Not something to be strictly enforced. Just my opinion anyway.

**Comment by melloware** [comment]
I see what you both are saying.     I am kinda torn by this as a FilterMeta without a Match Mode does seem odd to me.

the only compromise i could see is instead of `orElseThrow` would be to `orElse(Filter.EQUALS)` basically say if we can't determine the filter match mode it defaults to EQUALS???

**Comment by Rapster** [comment]
Yup there are different angles to attack this issue... 

In static mode: matchMode and filter constraints are mandatory
In lazy mode: you can do without it, since you can do whatever you want in `LazyDataModel#load`
With dynamic columns: on one hand it's dynamic (def of your columns) and the other it's hard coded in your lazy method (whether it's legacy or not, doesn't sound great)

My first thought to fix this was to change `MatchMode#of` impl. and return `STARTS_WITH` by default (if blank), or throw exception if  MatchMode.of("tagada") called

Btw:
```java
        public FilterMeta build() {
            if (filterBy.matchMode != null) {
                filterBy.constraint = FilterConstraints.of(filterBy.matchMode);
            }
            Objects.requireNonNull(filterBy.constraint, "Filter constraint is required");
            Objects.requireNonNull(filterBy.field, "Field is required");
            return filterBy;
        }
```

I think the requireNonNull on constraint is too strict here (since not used in lazy mode)

**Comment by newk5** [comment]
> I see what you both are saying. I am kinda torn by this as a FilterMeta without a Match Mode does seem odd to me.
> 
> the only compromise i could see is instead of `orElseThrow` would be to `orElse(Filter.EQUALS)` basically say if we can't determine the filter match mode it defaults to EQUALS???

Yea I think having a default match mode is probably best. It would result in less breaking changes for people upgrading from PF12. I dont think we gain anything on being too strict here, unless I'm missing something, I'm not fully aware of primefaces internals. 

I'd suggest when the match mode is null assume a default and when an invalid match mode is passed by string assume the default aswell but log a warning, maybe forcing a FacesException exception is too strict?
