### ISSUE TITLE
p:commandButton in p:selectOneMenu and p:autoComplete

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primefaces#977]
Possibility of putting p:commandButton in p:selectOneMenu and p:autoComplete, facilitating put the new option. 
Like the image below.
![console fw](https://cloud.githubusercontent.com/assets/5193643/11953038/28eb4a56-a884-11e5-9cf5-bbe6f24477a5.png)

**Comment by sudheerj** [comment]
We can implement footer facet for selectonemenu and autocomplete.The facet footer for onemenu is requested already here https://github.com/primefaces/primefaces/issues/97

**Comment by timonohe** [comment]
Hey, is this just planned or is there another way to set a footer into an <p:autocomplete>-Component?

**Comment by Rapster** [comment]
Use footer facet
