### ISSUE TITLE
SONAR: code quality for 13 release

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#9772]
### Description

The codebase might need some attention since last time we focused on this, on this day:
- 131 critical
- 87 major

More details here: https://sonarcloud.io/project/issues?resolved=false&id=org.primefaces%3Aprimefaces

I see a lot of `Make "XXX" transient or serializable"` kind of errors, and I think it'd be great to know once and for all what to do with these warnings?

The rest should be quite easy to fix. If you have any questions, suggestions, feel free to share 😉  

### Describe the solution you would like

See how we can split the work (it's redundant work and not so fun 😅 )

### Additional context

Also I see we have some singletons for DT/TT features, I'm planning to remove those for many reasons (essentially it's an anti-pattern, and we don't need to define them as singleton)

**Comment by melloware** [comment]
I will let Thomas answer the "transient" question but I am all for helping split the work and fixing the others!

**Comment by tandraschko** [comment]
TBH i would propably just ignore (remove the rule) the "make XXX transient or serializable"
why?
We cant make it "serializable"; e.g. UIComponents are not serializable, so we have to make it transient; same for other fields

Also JSF itself doesnt serializable the event but the user might - and it might even just works for the most cases, when the user itself e.g. serialize NodeCollapseEvent and the user applied a serializable TreeNode
if serialization fails, then he need just to implement serializeable in its own TreeNode

if we make it transient, the user will never have the coiche to serialize it

**Comment by Rapster** [comment]
16 critical and 66 Major left. I'm having a look at ImageCropperRenderer. We have a lot of [Remove usage of generic wildcard type.](https://sonarcloud.io/project/issues) not sure yet how to deal with those

**Comment by tandraschko** [comment]
i would disable this rule until a user comes up with a related problem someday; we never had any problems

**Comment by tandraschko** [comment]
i also wonder about java:S2160
we would need to overwrite equals/hashcode and just delegate to the parent (e.g. DotEndPoint)
i dont like that TBH, i would also ignore it

i think this are rules for "normal projects", not for OS frameworks which gets reviews from X people

**Comment by melloware** [comment]
I agree about the Generics warning I think we should just disable it.

**Comment by tandraschko** [comment]
will also fix some java:S1181 and deactivate the rule
its by design to catch Throwable

**Comment by Rapster** [comment]
S2160 makes sense (maybe less relevant in DotEndPoint and co.) but in general I would definitely keep it (specially when it comes to POJOs)

S1452: maybe exclude that rule for org.primefaces.component package (trying to solve that squid can result into ugly stuff, I didn't try, but looking at a component like DataTable, quickly can have a snowball effect)

S1181: how is it by design?

**Comment by tandraschko** [comment]
S2160: we can add it back but how can we exclude this for this specific classes? i dont like to add something like //CHECKSTYLE:OFF
            currently i dont see any case where we should really do it
            
S1181: we have currently 2 cases only and this can throw a LinkageError/NoClassDefFound

**Comment by jepsar** [comment]
This change will break premium templates. They (or at least Diamond) come with a custom menu component. In the renderer they do:

```java
        WidgetBuilder wb = getWidgetBuilder(context);
        wb.init("Diamond", menu.resolveWidgetVar(), clientId)
                .attr("statefulScroll", menu.isStatefulScroll());
        wb.finish();
```

Which no longer works, because `init` is now private:

https://github.com/primefaces/primefaces/blame/cdd2511c9c786f2fedcec4fa784e625d8f8718e3/primefaces/src/main/java/org/primefaces/util/WidgetBuilder.java#L85

**Comment by jepsar** [comment]
I was about to write that 👍🏻. I'll update the forum thread.

**Comment by tandraschko** [comment]
did we remove it during 13? 
if yes, we can also deprecate first to make migration easier
