### ISSUE TITLE
Datepicker: CSS classes missing

### ISSUE THREAD

**Issue by amittel** [primefaces/primefaces#9773]
### Describe the bug

[Server API](https://primefaces.github.io/primefaces/12_0_0/#/components/datepicker?id=skinning) lists css classes, which are not found on a rendered datepicker.

For example `.ui-datepicker-week-end` is listed at the API, but not found an the actual component.

The problem is also present in the [showcase datepicker](https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml)

### PrimeFaces edition

Community

### PrimeFaces version

Master Snapshot

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by melloware** [comment]
@jepsar this is definitely in the docs and has been but I don't see any `.ui-datepicker-week-end` styles used in the code?

**Comment by jepsar** [comment]
I think the docs were copied from `Calendar` and that the classes were never implemented in the new `DatePicker`.

**Comment by melloware** [comment]
I am looking in Primereact I don't see those styles in that Calendar either?

**Comment by jepsar** [comment]
It is present in the PrimeFaces `Calendar`. Might be added after the port.

**Comment by amittel** [comment]
Thank you for implementing.
But I think the css class should also be set in `thead` -> `th`. 
In my usecase I can hide the days but not the column completely with `.ui-datepicker-week-end {display: none;}`

**Comment by jepsar** [comment]
That's kind of a hack. You could workaround your issue by using something like https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child
