### ISSUE TITLE
Menu: add filter functionality

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primefaces#978]
Like:
![menuuu fw](https://cloud.githubusercontent.com/assets/5193643/11953658/118f74e0-a889-11e5-8fc1-fe1d59d9b454.png)

**Comment by sudheerj** [comment]
Normally the number of items in menu component is limited.Hence in the web design we did't find filter facility for menu options anywhere.

**Comment by melloware** [comment]
Going to close this as most menus that should be filterable are already filterable. Filtering a regular menu makes no sense from a UX perspective.
