### ISSUE TITLE
SelectOneMenu: itemLabel attribute is not honored when using SelectItem as data type

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#9784]
### Describe the bug

The component should render the itemLabel as instructed by the provided EL, even if the backed data type is SelectItem. The default rendering should only be done when the attribute is missing.

Maybe the [getSelectItems](https://github.com/primefaces/primefaces/blob/816651f3837649ad25b2595689e3b5db45684011/primefaces/src/main/java/org/primefaces/renderkit/SelectRenderer.java#L123) should also test if itemLabel is missing.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2.19

### Java version

11

**Comment by tandraschko** [comment]
@melloware can you please create a Faces issue and discuss it? we are currently aligned with the specs and we should decide of spec level if we should allow this or not

**Comment by melloware** [comment]
OK reported on Faces here: https://github.com/jakartaee/faces/issues/1791

**Comment by melloware** [comment]
Attached is an updated example that also adds `<h:selectOne>` on there to compare to PF SelectOne and what Mojarra and MyFaces do.

[spec-1791.zip](https://github.com/user-attachments/files/24532338/spec-1791.zip)

<img width="657" height="562" alt="Image" src="https://github.com/user-attachments/assets/0c959b5f-8159-46c5-adaf-bbf5bff90f04" />
