### ISSUE TITLE
DataTable: add refresh button

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primefaces#979]
Refresh button in the DataTable.
![tabelaaa fw](https://cloud.githubusercontent.com/assets/5193643/11953792/2efb73a2-a88a-11e5-91fb-41eb3e74c106.png)

**Comment by sudheerj** [comment]
What functionality you are expecting from this refresh button? Resetting the dataTable to initial state? You can use custom paginator feature to add this button.

**Comment by djmj** [comment]
In lazy mode it could invoke the load method.

**Comment by melloware** [comment]
To me this feature was requested in 2015 and seems pretty useless as anyone can add their own custom button and refresh method to call.  Only one upvote in 4 years.
