### ISSUE TITLE
TabView: Update causes Javascript errors if action facet is used

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#9794]
### Describe the bug

If an action facet with a link is added to a tab, then Javascript errors occur after updating the tab view.

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10725963/primefaces-test-master.zip)

1. Start the reproducer and open the Javascript console.
2. A click on the "Update!" button causes the errors.

### Expected behavior

No errors.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by ltlBeBoy** [comment]
During my research I found out that the changes made for #8659 cause the problems. Within the function `bindRefreshListener` the tab IDs are searched in the following way:

```
    $(this.jqId + '>ul>li').each(function() {
        var tabId = $('a', this).attr('href').slice(1);
```

The problem with that is that the search for `li` is not exact enough because for the action facet an `li` is added too (with class `ui-tabs-actions`)! So I would recommend to use the existing variable `headerContainer` instead which already references the tab headers:

```
    this.headerContainer.each(function () {
        var tabId = $('a', this).attr('href').slice(1);
```

**Comment by ltlBeBoy** [comment]
Eventually related to #9544.

**Comment by ltlBeBoy** [comment]
Yes, it happens with the snapshot, too.

**Comment by melloware** [comment]
ahhh OK submit a PR if you think you can fix it nicely and I can review.

**Comment by ltlBeBoy** [comment]
OK.

**Comment by melloware** [comment]
@fcorneli I re-opened this issue since it caused the regression with #8659

**Comment by melloware** [comment]
I think this fix needs Jquery to re-evaluate the tabs because of AJAX and just use a more specific selector than it was using before to not pick up facets?

Something like..

```js
$(this.jqId + '>ul>li.ui-tabs-header').each(function() {
```
??

**Comment by ltlBeBoy** [comment]
That means that the `headerContainer` gets outdated?

**Comment by melloware** [comment]
I think the headers container variable at that point is still the "old" headers in bindRefreshListener and eventually gets updated the variable at that point in time is the old tabs.  something like `$(this.jqId + '>ul>li.ui-tabs-header').each(function() {` makes Jquery use the current values in the DOM.

**Comment by melloware** [comment]
I have confirmed that this fixes both scenarios.  PR submitted.

**Comment by fcorneli** [comment]
@melloware Tested you change here, it works.

**Comment by melloware** [comment]
Glad we got this in right before 13.0.0
