### ISSUE TITLE
CellEdit : rowKey not set without selectionMode

### ISSUE THREAD

**Issue by sebsoftware** [primefaces/primefaces#9798]
### Describe the bug

if selectionMode isn't set, rowKey is null in the celledit event. rowKey attribute is set in dataTable tag.

### Reproducer

add a cellEditor with an inputText to a dateable without selectionMode and without a selection checkbox Column. Editor shows up, cellEdit is called with newValue and oldValue, but rowKey is null. 

### Expected behavior

rowKey with correct value, i.E. #{ entry.id }

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by Rapster** [comment]
Can't you call the same thing as you do in your EL e.g `<p:dataTable rowKey="#{car.id}" />` ?

**Comment by Rapster** [comment]
Instead of doing `String rowkey = event.getRowKey();` do this `String rowkey = event.getId()`; Am I missing something?

**Comment by sebsoftware** [comment]
CellEditEvent does not have a getId() method.

**Comment by Rapster** [comment]
updated my answer, Take advantage of generics here in your `onCellEdit` method: `CellEditEvent<DemoEntity>`, that whay no need to cast and you can get your rowkey (which is your id)

**Comment by sebsoftware** [comment]
That doesn't work.

oldValue and newValue is a string object, from the p:inputText, holding only the field (user) value.  So correct is CellEditEvent<String>, but this is also a problem, if you have different editable kinds of values in the row cells i.E. date, number, string, and cellEdit is handled globally for the row. but that's another story.

There is no reference to the row object as far as I can see.

**Comment by melloware** [comment]
Can you wrap your code up into the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is a big help to developers over code snippets.

**Comment by Rapster** [comment]
Ok I see, my bad I had in mind oldValue and new Value were the row objects... I would mark rowKey as deprecated and instead pass row object. This way we could remove `CellEditEevent#resolveValue`, unless there is a very good reason to have rowKey in this event? @melloware @tandraschko @christophs78

**Comment by melloware** [comment]
I never use Cell Editing so I have no opinion 😄

**Comment by Rapster** [comment]
@sebsoftware I'm still gonna a look at this to fix your issue 😉

**Comment by Rapster** [comment]
I need feedback from users using this feature, because so far rowIndex is used to retrieve the rowObject and rowKey is used for UITree. At first glance, I don't think is really necessary for this

**Comment by sebsoftware** [comment]
Attached a PrimeFaces-test-project
[primefaces-test-celleditevent.zip](https://github.com/primefaces/primefaces/files/10760828/primefaces-test-celleditevent.zip)

**Comment by ltlBeBoy** [comment]
When I do cell editing, then I get the edited object the following way:

```
public void onCellEdit(CellEditEvent event) {
    DataTable dataTable = (DataTable) event.getComponent();
    Entity entity = (Entity) dataTable.getRowData();
}
```
See [https://stackoverflow.com/a/32082362](https://stackoverflow.com/a/32082362)

**Comment by Rapster** [comment]
Nice! I think it's a nice workaround, as it's not a straightforward way of retrieving the info (not complicated yes, but not obvious either) @ltlBeBoy Did you have to set a rowKey for this?

**Comment by ltlBeBoy** [comment]
@Rapster No, I don't set `rowKey` because I use a `LazyDataModel` in such views.

**Comment by melloware** [comment]
@sebsoftware @ltlBeBoy please review my PR.  I applied what you are doing to the CellEditEvent so you can access `event.getRowData()` right on their to get the DataTable Row edited or TreeTable TreeNode edited.
