### ISSUE TITLE
GMap not visible on an invisible page of Mobile

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#98]
If gmap is placed inside a view that is not the first of a mobile page, then it can't be displayed.

**Comment by gregor2005** [comment]
I have a similar or the same defect when I put a gmap inside a tabView when the gmap is not in the first tab.

**Comment by tandraschko** [comment]
PrimeFaces Mobile will be deprecated  in 6.2 and removed in 6.3 ( see https://www.primefaces.org/primefaces-6-2-roadmap/)
Therefor i will close this issue as won't fix. If you will provide a PR to fix this issue until 6.2 RC1, i can merge it.
