### ISSUE TITLE
Unable to open Dialog from MenuItem

### ISSUE THREAD

**Issue by raschik** [primefaces/primefaces#980]
In our application we are having a dynamically build menubar, which entries direct us to a new DialogFramework. Since the number and content of the menuItems varies from user to user, we built a MenuModel in the bean, which is then called by the xhtml. When we switched from Resin 4.0 to Tomcat v7.0, the DialogFramework is not popping up anymore. With Resin 4.0 it is working perfectly fine. Calling a new page simply via the URL is no problem. We are using Mojarra 2.1.24 and tried it with Primefaces 5.2.10 and 5.3.3.

We could reproduce the problem in a simple example (see http://forum.primefaces.org/viewtopic.php?f=3&t=44062). If you click Start->first actually the DialogFramework should pop up but nothing happens instead. The subMenu and the menuItems are part of the MenuModel set in the bean.

However, if you go on Start2->first the desired page pops up. This menubar is set in the xhtml.

**Comment by albfan** [comment]
If you have older version of primefaces, you only need to return something from your method to get your dialog open

Tested on primefaces 5.2
