### ISSUE TITLE
jQuery Charts: Text distortion in graphs on Chrome

### ISSUE THREAD

**Issue by xtsoler** [primefaces/primefaces#9800]
As described here:
https://stackoverflow.com/questions/73224635/text-distortion-in-primefaces-chart

Some of the text in graphs has distortion in Google Chrome even in the showcase.
If I disable "Accelerated 2D canvas" the problem goes away.
It might have to do with the use of many small canvases, I read somewhere that for small canvases Chrome behaves differently but I'm not sure at all if that is the root cause.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

openjdk version "11.0.18"

### Browser(s)

Chrome Version 109.0.5414.122

**Comment by melloware** [comment]
The old Jquery charts are deprecated in 12.0.0 and going to be removed in 13.0.0. See: https://github.com/primefaces/primefaces/issues/8773

I highly recommend switching over to the much more modern and supports ChartsJS version of charts.

**Comment by xtsoler** [comment]
> o be removed in 13

Thank you so much for pointing that out, I recently migrated from PF7 to PF12 so I didn't know anything about ChartJS.
Could you please let me know how I would switch to ChartJS and disable the old jqPlot?

**Comment by melloware** [comment]
What I would do is convert 1 chart at a time.   For instance your horizontal bar chart in your screenshot here is  the BAR chart demo and code.

https://www.primefaces.org/showcase/ui/chartjs/bar/bar.xhtml?jfwid=094f9

It shouldn't be too hard to switch over but you will have to make some code changes.

**Comment by xtsoler** [comment]
Okay I think my starting point is to move from
import org.primefaces.model.chart.LineChartModel;
to
import org.primefaces.model.charts.line.LineChartModel;

Again many thanks

**Comment by melloware** [comment]
Yep exactly.  the new charts will look much differnet to your users but they are so much nice AND still supported and look great and are responsive.
