### ISSUE TITLE
DataExporter: Attribute 'visibleOnly' not documented

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#9808]
### Describe the bug

The [online documentation](https://primefaces.github.io/primefaces/12_0_0/#/components/dataexporter) of component DataExporter has no description for attribute 'visibleOnly'.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by jepsar** [comment]
There are more attributes missing in fact. I'll fix it this evening.

**Comment by rho66** [comment]
Thank you!
