### ISSUE TITLE
DataTable: custom paginator content not updated

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#981]
Datatable custom paginator content is not updated after filtering.

In custom paginator content i display total number of items floated left using `LazyDataModel#rowCount` property.
This is not updated when user filters table which is irritating.

**Comment by sudheerj** [comment]
I think this is an expected behavior .DataTable ajax behaviors won't update the header and footer part but only the body section.You might use remoteCommand to update them.

**Comment by kukel** [comment]
It is obviously not the **expected** behaviour by all, but it is 'certainly' as designed. So it is not a bug but a feature request

**Comment by melloware** [comment]
dupicate of https://github.com/primefaces/primefaces/issues/988
