### ISSUE TITLE
Paginator: Clicking on a p:commandLink inside a top paginator scrolls to bottom paginator

### ISSUE THREAD

**Issue by fed-dessi** [primefaces/primefaces#9813]
Hello,
while working on a work project I've noticed that if I have a p:dataTable with a custom facet added to the paginator template that contains a p:commandLink which updates the table it self the page will scroll to the bottom paginator of the table if it's out of view at the end of the AJAX call.

Steps to reproduce:

```
1. Have a dataTable which has enough content so that the top paginator is in the browser view but the bottom paginator isn't
2. Add a p:commandLink in the paginator that updates the same table 
3. When clicking the top update link button the page will scroll towards the bottom paginator update link at the end of the ajax call
```

Intended behaviour:

- The page shouldn't scroll down when clicking the commandLink

As a workaround we can use a p:commandButton, which doesn't produce the same effect, but in case we have any Exceptions thrown the table view will break. (I couldn't reproduce this on the test project so it's most likely something implemented on our end)

Attached is a very simple test project which shows the issue.
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10783110/primefaces-test-master.zip)

**Comment by melloware** [comment]
I actually think the issue might be similar to this exact issue: https://github.com/primefaces/primefaces/issues/9793

If you look in the DOM both Paginator links have the exact same HTML ID.

**Comment by fed-dessi** [comment]
Is there any way to assign different ids to the two links then? I had a quick look at the docs but couldn't see any options there to do that.

**Comment by melloware** [comment]
I think its a bug related to that issue where JSF is not giving it uniqueness and causing issues.  I think it has to be fixed at the JSF level.  I would say for now use a button or use a link only one top or bottom?

**Comment by melloware** [comment]
Going to close this as "third-party" since I think it needs to be addressed in that JSF fix.

**Comment by mihaiDumea** [comment]
You may use different facets[(paginatorTopRight)](https://github.com/primefaces/primefaces/blob/c3bd2e70266a517c253461986bccdb04ce5fdb22/primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java#L80) instead of one that will be rendered twice.
Maybe the bug is that facets are rendered more than once.
You can also try to skip the focus [handleReFocus](https://github.com/primefaces/primefaces/blob/16a92d5b299da1baf7d0e9baab64492657d4a263/primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js#L1251).
