### ISSUE TITLE
SelectOneMenu: disable autoWidth when placed inside ui-fluid?

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9814]
Currently, if you use ui-fluid and a grid, you have to add autoWidth=false to each selectOneMenu.
I wonder if we should automatically detect a parent with ui-fluid and skip autoWidth.

WDYT @mertsincan?

**Comment by tandraschko** [comment]
you will see the behavior here:
http://www.primefaces.org:8080/showcase/ui/input/oneMenu.xhtml?jfwid=cb75b

it works fine in ui-fluid as long as the items are smaller as the columns
if you resize the window to a smaller size, some selectOneMenus will overflow over the column

**Comment by melloware** [comment]
I like the idea.  For me anything to reduce user confusion and expected behavior.

**Comment by tandraschko** [comment]
even a simpler fix and propably faster as looping parents for ui-fluid:
.ui-fluid .ui-selectonemenu {
   min-width: unset !important; 
}

**Comment by tandraschko** [comment]
i just dont like !important

maybe the best way is to change to JS to set width (isntead of min-width) and set max-width with our css:

```
.ui-fluid .ui-selectonemenu {
    max-width: 100%;
}
```

will try this now

**Comment by tandraschko** [comment]
i think we need to introduce a JS check for a parent ui-fluid and change autoWidth to String (instead of boolean) with following options:
auto, true, false
