### ISSUE TITLE
PanelGrid: not responsive when there are 5 columns

### ISSUE THREAD

**Issue by bachtrong43** [primefaces/primefaces#9817]
### Describe the bug

5 columns does not responsive, other values is ok. when columns attribute is 5 output html is:
`<div class="ui-panelgrid-cell null"><span class="font-bold" style="color:rgb(255, 99, 132);">1</span></div>`
class is null, expected value is ui-md-3

### Reproducer

<p:panelGrid columns="5" styleClass="showcase-text-align-center" layout="grid">
<h:outputText value="1" class="font-bold"/>
<h:outputText value="2" class="font-bold"/>
<h:outputText value="3" class="font-bold"/>
<h:outputText value="4" class="font-bold"/>
<h:outputText value="5" class="font-bold"/>
<h:outputText value="6" class="font-bold"/>
<h:outputText value="7" class="font-bold"/>
<h:outputText value="8" class="font-bold"/>
<h:outputText value="9" class="font-bold"/>
<h:outputText value="10" class="font-bold"/>
</p:panelGrid>

### PrimeFaces edition

None

### PrimeFaces version

11.0.0, 12.0.0

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

8

**Comment by melloware** [comment]
Hmmm but I thought when using `columns` it had to be divisible by 12.  5 is not so how would it know what to make the `col-` to make it 5 columns?  If it makes it `col-3` that would be 15 and it would put the 5th item on a new row?

**Comment by melloware** [comment]
I wonder if its a gap in the docs:https://primefaces.github.io/primefaces/12_0_0/#/components/panelgrid?id=panelgrid

It should probably mention it has to be divisible by 12 column grid when using grid or flex mode?

**Comment by melloware** [comment]
@christophs78 @jepsar would like your thoughts here?  I am thinking maybe its a documentation update and a LOG.WARN at ProjectStage = DEVELOPMENT?

**Comment by jepsar** [comment]
I think we should throw an exception if `12 % columns != 0`

**Comment by melloware** [comment]
```java
 throw new FacesException("Columns of PanelGrid \"" + clientId + "\" must be a value of 1, 2, 3, 4, 6 or 12 in responsive layout.");
```
