### ISSUE TITLE
InputMask: onchange broken with PF12

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#9819]
### Describe the bug

inputMask in PF12 started to generate onchange events even if the value does not change. All that is enough is to click the component (focus gained) and click somewhere else (focus lost). This kills logic in my application which relies on reliably getting information if anything actually changes (inputMask used as filter with onchange script causing PF('dataTable').filter()).

12.0.3:
![Screenshot 2023-02-21 at 15-06-33 PrimeFaces Test](https://user-images.githubusercontent.com/1133953/220369037-631412f2-29fc-4941-b8c8-1e3aa1bf84a7.png)

11.0.9:
![Screenshot 2023-02-21 at 15-07-25 PrimeFaces Test](https://user-images.githubusercontent.com/1133953/220369116-be88d81a-ff63-4fad-a9e9-9004ca5e43b0.png)

### Reproducer

```
    <h:body>
        <p:log id="log" />
        <h:form id="frmTest" prependId="false">
            <p:inputMask id="testMask" widgetVar="testMask" value="#{testView.value}" mask="9999[ 9999]" onchange="PrimeFaces.info(jQuery('#testMask').val())"/>

        </h:form>
    </h:body>
```
Reproducer:
[primefaces-test-inputmask.zip](https://github.com/primefaces/primefaces/files/10794345/primefaces-test-inputmask.zip)

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.3

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

11

**Comment by melloware** [comment]
I think its similar to this issue: https://github.com/primefaces/primefaces/issues/9259

**Comment by morvael** [comment]
Yes, but I see there was a different component, so maybe this needs a separate fix based on the first one.

**Comment by morvael** [comment]
Or maybe not as DatePicker maybe uses InputMask inside. Can this be pushed in 12.0.4?

**Comment by melloware** [comment]
Yes they both use: https://github.com/RobinHerbots/Inputmask

**Comment by melloware** [comment]
No I need to make a fix for InputMask as well.

**Comment by morvael** [comment]
Unpacking the two js files into reproducer didn't help me.

**Comment by melloware** [comment]
No it won't that was for DatePicker.

The bug is right here in jQuery InputMask: https://github.com/RobinHerbots/Inputmask/blob/5.x/lib/eventhandlers.js#L456

They fire the `change` event on `blur` no matter if the value has changed or not...so that explains why everytime you leave the focus of the field it fires `change`.

**Comment by melloware** [comment]
Reported here: https://github.com/RobinHerbots/Inputmask/issues/2691

**Comment by morvael** [comment]
Since this didn't happen before is it possible to use older version of Inputmask in PF12 like the one used in PF11?

**Comment by melloware** [comment]
You should be able to extract the one from PF11 and just overwrite it by placing it in the same location in your WAR like `resources\primefaces\inputmask\inputmask.js` and it will take precedence over the one in PF12.

**Comment by morvael** [comment]
It seems using one from 11.0.10 works, though it behaves a bit different. The newer one was clearing the value if it didn't match required part of mask, the old one isn't. Don't remember if this was really its original behavior. Shall I replace datepicker.js as well, if I use it with mask as well?

**Comment by melloware** [comment]
Yeah probably something else fixed. Let me work on fixing this and providing a monkeypatch.

**Comment by melloware** [comment]
Here is a MonkeyPatched version if you want to try it...

[pf-9819.zip](https://github.com/primefaces/primefaces/files/10806042/pf-9819.zip)

**Comment by morvael** [comment]
Thanks, will test monkeypatch immediately. Will this be eventually backported to PF12?

**Comment by jepsar** [comment]
@morvael this is the Community version of PrimeFaces. We cannot backport to PrimeFaces Elite. See https://github.com/primefaces/primefaces#community--elite--pro

**Comment by morvael** [comment]
I mean in 12.0.4, as I see this tagged as 13.0.0. I have reported this as Elite issue (see first post), as I'm Elite user.

**Comment by melloware** [comment]
@morvael as mentioned in https://github.com/primefaces/primefaces#community--elite--pro this is the community tracker. If you want the ability to determine what goes in an Elite release you need a PRO support account.  Then you can reqeuest what goes in Elite.

**Comment by morvael** [comment]
I don't get it fully, seems like Elite not-PRO I have neither a bug tracker nor voting rights what goes into release. So worse than Community :)

**Comment by jepsar** [comment]
@morvael please contact PrimeTek. We, as the community, cannot help you with that.

**Comment by melloware** [comment]
Elite subscription only gives you the access to download Elite releases.  PRO subscribption gets you a private channel to report issues you want included in release @morvael to me its all very clearly described here https://www.primefaces.org/showcase/support.xhtml?jfwid=f854a

![image](https://user-images.githubusercontent.com/4399574/220916313-06d3d422-30f9-49b7-8157-eac6a5148107.png)

if you want PRO support, you need to purchase PRO support....

**Comment by morvael** [comment]
I'll patiently wait for something to happen. I have long since stopped trying to understand relation between PrimeTek and this community :) All I know is that bugs previously reported on this site somehow made into next patch version. Peace.

**Comment by morvael** [comment]
I just want to be able to report bugs as elite user. I can only see it possible using this site.

**Comment by morvael** [comment]
Why would there be these fields otherwise:
![Screenshot 2023-02-23 at 14-15-52 InputMask onchange broken with PF12 · Issue #9819 · primefaces_primefaces](https://user-images.githubusercontent.com/1133953/220917236-0b885f9c-5108-45ab-a91f-552085bebc50.png)

**Comment by jepsar** [comment]
Those are part of the triage process

**Comment by melloware** [comment]
Yes they are to help us Open Source volunteeers have as much info as possible to determine when and where a bug occurred.  I am sure your bug is in 12.0.0 community as well so its not broken in 12.0.3 its probably broken in 12.0.0 community.

**Comment by morvael** [comment]
Cool, I'll continue reporting bugs found working with Elite version on this site, then.
