### ISSUE TITLE
fileUpload accepts types not specified in allowTypes  

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#982]
When the following regex is specified: allowTypes="/(.|\/)(xml)$/" it accepts XSLT files with xsl extension as well (PF 5.3).

The same issue was discussed already in the past http://stackoverflow.com/questions/24760699/pfileupload-allowtypes-regex

Any chance to restrict it solely to accept XML files only?

**Comment by melloware** [comment]
Similarto #2441

**Comment by tandraschko** [comment]
Duplicate
