### ISSUE TITLE
AutoComplete: disabled cursor is pointer

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#9825]
### Describe the bug

If the autocomplete is disabled, the wrong cursor is applied. I think there should be cursor default, not pointer. It's caused by this css class in [autcomplete.css](https://github.com/primefaces/primefaces/blob/24822d875d0eb8f658438dc4c74c56045b5d9faf/primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.css):
```
.ui-autocomplete {
    cursor: pointer;
}
```
I think this cursor: pointer property can be changed to default.

### Reproducer

1. Go to your autocomplete showcase
2. set class ui-state-disabled to Simple autocomplete's input element
3. mouse over

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0.

### JSF implementation

Mojarra

### JSF version

2.3.18

### Java version

11

### Browser(s)

Chrome 110.0.5481.100

**Comment by melloware** [comment]
When I add `ui-state-disabled` in the showcase it looks fine because of this...

```css
.ui-state-disabled {
    cursor: default !important;
    pointer-events: none;
}
```

The cursor is overriden back to default cursor?

**Comment by vonnai** [comment]
.ui-state-disabled class affects the input element only. By the way the pointer-events:none cancels the cursor:default !important setting. In the developer tools it looks like the cursor:default !important really overrides the cursor:pointer setting, but not. So the cursor: pointer from the ui-autocomplete class has the highest priority.

**Comment by melloware** [comment]
intesting I put ui-state-disabled on the DIV element of and not the Input itself that could explain why I was not seeing it. Anyway @jepsar is investigating thanks for reporting!
