### ISSUE TITLE
Showcase: Barcode4J switch to Maven Central version

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#9828]
Current showcase uses a custom Barcode4J 2.1 from PrimeFaces repository not available in Maven Central.  The last version in Maven Central is 2.0 and it has a pretty significant Firefox bug.

So I have created a new fork that is Maven friendly so it can be reached on Maven Central without the need to use PrimeFaces repo.

https://github.com/primefaces-extensions/barcode4j-lite

It also removes the `xml-apis` dependency which is no longer necessary and was causing Qaurkus issues.

**Comment by tandraschko** [comment]
isnt there any other lib which does the same?

**Comment by melloware** [comment]
I don't think so.  We switched over our QRCodes to use a newer lib but Postal Barcodes etc everyone seems to use this Barcode4J lib.
