### ISSUE TITLE
Incorrect XHR encoding when fileUpload combined with another control in the same form

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [primefaces/primefaces#984]
When fileUpload control is standalone in the form, all individual file upload XHR requests specify UTF-8 encoding. But if another control is placed to the given form, the encoding is switched (unexpectedly) to ISO-8859-1. If components even in other form are updated after uploading is complete, their special characters are displayed incorrectly.

For sample code, see discussion
http://forum.primefaces.org/viewtopic.php?f=3&t=44116&sid=b60c40a9b37fd4034cb4ca9d73b6dd93

PF 5.3

**Comment by tandraschko** [comment]
As stated in the forum, it's better to place fileupload in a own form as it requires another enctype at the form.
