### ISSUE TITLE
inputSwitch rendering and behaviour bug inside dialog

### ISSUE THREAD

**Issue by spauny** [primefaces/primefaces#985]
Using primefaces 5.3, inputSwitch is rendered twice as wide in a dialog, when you open it for the first time and the value is not being set. Instead the switch resets itself immediately. Made a tiny video of this behaviour: 

http://tinypic.com/r/2uj04et/9

And here it's how it looks after I close the dialog and re open it. The dialog is NOT dynamic. Also there's a small problem with the Yes label's background... 

http://tinypic.com/r/5zmh4n/9

Will investigate more myself these days. Just wanted to check if there's a quick fix...

**Comment by mertsincan** [comment]
This is a Spark Theme issue. Please try with;

```
.ui-accordion .mySwitch .ui-state-hover, 
.ui-accordion .mySwitch .ui-state-active {
      background-color: transparent;
      color: transparent;
}

<p:inputSwitch styleClass="mySwitch"  .../>
```

OR

```
.mySwitch.ui-inputswitch .ui-inputswitch-on{
    height: 24px;
    top: 1px;
    left: 1px;
} 

.mySwitch.ui-inputswitch .ui-inputswitch-on {
    border-bottom-left-radius: 5px;
    border-top-left-radius: 5px;
}

.mySwitch.ui-inputswitch .ui-inputswitch-on span{
    color: white;
}

<p:inputSwitch styleClass="mySwitch"  .../>
```

**Comment by deoxyseia** [comment]
I have the same problem, using Primefaces 5.3 and default theme. Your solutions don't works for me, maybe because is only for Spark theme.

**Comment by dani-easydevel** [comment]
Hi,
Did someone find the solution ? I have the same issue and tried some css tests, but not working...
Its a problem on rendering the inputswitch, sure.

And I want to avoid the `dynamic="true"` solution.

Thanks in advance
