### ISSUE TITLE
DatePicker: datepicker panel covers up the input field

### ISSUE THREAD

**Issue by AKrupaa** [primefaces/primefaces#9855]
### Describe the bug

When clicking on <p:datePicker mode="popup" /> the datePicker_panel is shown. The panel obscures the data entry field so that it is impossible to enter the date manually.

### Reproducer

  <h5 class="mt-0">Popup</h5>
  <div class="ui-fluid grid formgrid">
      <div class="field col-12 md:col-4">
          <p:outputLabel for="basic" value="Basic"/>
          <p:datePicker id="basic" value="#{calendarView.date}" mode="popup"/>
      </div>
  </div>

@Named
@ViewScoped
public class CalendarView implements Serializable {
private Date date;
    public Date getDate() {
        return new Date();
    }
}

Can be reproduced from: http://primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml?jfwid=197f4

For smaller window, click on datePicker field - covers the input field.
![image](https://user-images.githubusercontent.com/33357370/222083070-4a0a3baa-3a03-4ab4-b8ea-d9a500b1a90e.png)

### Expected behavior

DatePicker is shown below the input field like this:
![image](https://user-images.githubusercontent.com/33357370/222084852-a5df8975-2b15-4691-aed9-686459319e7f.png)

### PrimeFaces edition

None

### PrimeFaces version

11.0.0

### Theme

sapphire-theme

### JSF implementation

Mojarra

### JSF version

2.2.20

### Java version

openjdk 17.0.1 2021-10-19

### Browser(s)

Vivaldi 5.6.2867.50 (Stable channel) stable (64-bit); Firefox 110.0 (64-bit); Chrome 109.0.5414.74 (Official Build) (64-bit)

**Comment by jepsar** [comment]
I'd say that's by design. Try with `touchUI="true"`.

**Comment by melloware** [comment]
I agree this is by design.
