### ISSUE TITLE
SelectOneRadio: `plain` is not working

### ISSUE THREAD

**Issue by bjornerikolsen** [primefaces/primefaces#9857]
### Describe the bug

I'm using selectOneRadio with two radioButtons with custom layout (referenced). This is working in PF 10 and 11, but not in PF 12. When clicking the radioButtons the events are not sent. I see in the Chrome devtools that the id/name for the selectOneRadio is appearing twice. One with just the name specified and one with "_clone" added to it, e.g. radioOptions and radioOptions_clone. When I remove the "_clone" in devtools its working fine. In PF 11 the name does not have the "_clone" added. 

If I set plain="false" in selectOneRadio it seems to work. I guess plain="false" is default. But the id for the selectOneRadio is still appearing twice, but now both get updated. One with just the id/name specified and one with "_clone"
But setting plain="true" the value for the selectOneRadio is not updated. Just the value for the "_clone" is updated.

Not sure if  "_clone" is supposed to be added or some configuration is needed.

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/10861261/primefaces-test.zip)

### Reproducer

Go to devtools and see the name is ="frmTest:customRadio_clone"

### Expected behavior

selectOneRadio is working as in PF 11, "_clone" is not added to the selectOneRadio name.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by jepsar** [comment]
Does it work with facet? Referenced will be deprecated or removed at some point. Apart from that, I'll have a look at this.

**Comment by bjornerikolsen** [comment]
Tried with facet, but having the same issue.

**Comment by jepsar** [comment]
For the record. Introduced in https://github.com/primefaces/primefaces/pull/8378

**Comment by jepsar** [comment]
@bjornerikolsen can you please provide more details on what is not working exactly? For me it's working (both in 12 and 13):

<img width="506" alt="Screenshot 2023-03-01 at 16 58 19" src="https://user-images.githubusercontent.com/7500178/222193672-82998394-78b1-4b05-b41e-cd6602630610.png">

**Comment by bjornerikolsen** [comment]
PF 12 _clone added:
![Screenshot (973)](https://user-images.githubusercontent.com/110525383/222359972-900f578a-f45b-42d5-9cfc-4257d346bdf7.png)

PF 11:
![Screenshot (974)](https://user-images.githubusercontent.com/110525383/222360021-6c5a09d2-fd6d-4879-b8cd-f3d405aee396.png)

**Comment by jepsar** [comment]
I know. It was intentional. And it works for me. @melloware are you able to reproduce it?

**Comment by bjornerikolsen** [comment]
If I remove the _clone from the name in devtools the radiobutton works. I can see if I can improve the reproducer.

**Comment by melloware** [comment]
Currently the above reproducer seems to be working fine for me in Chrome and Firefox.

**Comment by melloware** [comment]
@bjornerikolsen i will re-open once you provide the reproducer.

**Comment by melloware** [comment]
Can you provide a PrimeFaces Test reproducer?

**Comment by jepsar** [comment]
I'll have a look this evening.

**Comment by bhai81** [comment]
Here is a reproducer.
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/11736017/primefaces-test.zip)

**Comment by jepsar** [comment]
@melloware any idea why we have the `plain` attribute? Apart from this bug, I don't get why we have this future. It takes more work to support the component and we don't have this attribute on other components (didn't check them all).

**Comment by jepsar** [comment]
I don't understand how plain ever worked okay. I did fix it, but IMO we should remove plain support ASAP. See also https://github.com/primefaces/primefaces/issues/10227
