### ISSUE TITLE
Add support for lZero property to InputNumber

### ISSUE THREAD

**Issue by kito99** [primefaces/primefaces#986]
Here's the description of lZero from the Autonumeric site: 

lZero: "deny" - allows only one leading zero (same behavior as versions 1.7.0 to 1.7.4.

lZero: "allow" - allows leading zeros to be entered. Removes leading zeros on the focusout event.

lZero: "keep" - allows leading zeros to be entered. Keeps leading zeros on the focusout event.

It would probably help to add some of the other missing parameters as well: http://www.decorplanit.com/plugin/

**Comment by tandraschko** [comment]
A PR would be great!

**Comment by kito99** [comment]
I will if I have time, but I may not. We had to customize autoNumeric.js, so we're not using the default version anyway :-).

**Comment by melloware** [comment]
Fixed in #2400
