### ISSUE TITLE
ContextMenu: cannot be conditionally toggled with ajax

### ISSUE THREAD

**Issue by NicolaIsotta** [primefaces/primefaces#9863]
### Describe the bug

If a context menu renderd value evaluates to false, it shouldn't be displayed even if it was displayed before.

### Reproducer

```xhtml
<h:form>
    <p:commandButton value="Toggle context menu" action="#{testView.toggleContextMenu()}" update="@form" />

    <p:outputLabel id="text" value="Context menu enabled: #{testView.enableContextMenu}"/>

    <p:contextMenu id="contextMenu2" for="text" rendered="#{testView.enableContextMenu}">
        <p:menuitem value="Homepage" url="https://www.primefaces.org" icon="pi pi-home"/>
    </p:contextMenu>
</h:form>
```

```java
@Data
@Named
@ViewScoped
public class TestView implements Serializable {

    private boolean enableContextMenu;

    @PostConstruct  
    public void init() {
        enableContextMenu = true;
    }

    public void toggleContextMenu() {
        enableContextMenu = !enableContextMenu;
    }

}
```
To reproduce: open the page, press the button and right click the text: the context menu appears even if it shouldn't.

### Expected behavior

if rendered evaluates to false, context menu shouldn't be displayed

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

jdk-11.0.13

**Comment by NicolaIsotta** [comment]
If `update="@form"` is replaced by `ajax="false"`, the behavior is correct.
Replacing `update="@form"` with `update="contextMenu2"` instead does not fix the issue.

**Comment by jepsar** [comment]
`ajax="false"` will re-initialize all Javascript objects as you do a full reload of the page. `update="contextMenu2"` is not valid, see https://stackoverflow.com/questions/14790014/ajax-update-render-does-not-work-on-a-component-which-has-rendered-attribute

**Comment by melloware** [comment]
I think I know the issue. Let me try something.

**Comment by melloware** [comment]
@NicolaIsotta working workaround for you!
[pf-9863.zip](https://github.com/primefaces/primefaces/files/10882878/pf-9863.zip)

```js
if (PrimeFaces.widget.ContextMenu) {

    PrimeFaces.widget.ContextMenu.prototype._cleanup = function() {
        if (this.cfg.target === undefined) {
            var event = 'contextmenu.' + this.id + '_contextmenu';
            $(document).off(event);
            if (PrimeFaces.env.isTouchable(this.cfg)) {
                $(document).swipe().destroy();
            }
        }
        else {
            var event = this.cfg.event + '.' + this.id + '_contextmenu';
            $(document).off(event, this.jqTargetId);
            if (PrimeFaces.env.isTouchable(this.cfg)) {
                this.jqTarget.swipe().destroy();
            }
        }
    }
}
```

```xml
<p:commandButton 
value="Toggle context menu" 
action="#{testView.toggleContextMenu()}" 
update="@form" 
onstart="PF('cm')._cleanup();" />
```

**Comment by melloware** [comment]
Because this is a special case and it can't tell the widget is being updated in 13.0.0 you will just have to call `onstart="PF('cm').destroy();"` to destroy the widget before the AJAX request is sent and when it responds it will rebuild the widget based on the rendered flag.
