### ISSUE TITLE
TreeTable: globalFilterFunction doesn't work 

### ISSUE THREAD

**Issue by lehmser** [primefaces/primefaces#9864]
### Describe the bug

If i try to impement globalFilterFunction for p:treeTable, then i get an error 

```
globalFilterFunction="#{ttScrollableView.globalFilterFunction}": The class 'com.my.treetableExample.ScrollableView' does not have the property 'globalFilterFunction'.
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:75)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:170)
	at org.primefaces.component.treetable.TreeTableBase.getGlobalFilterFunction(TreeTableBase.java:441)
```
I test it on the shocase-example: 

                <p:treeTable widgetVar="treeTable" value="#{ttScrollableView.root1}" var="document"
                             style="margin-top:0" globalFilterFunction="#{ttScrollableView.globalFilterFunction}">
                    <f:facet name="header">
                        <div class="flex align-items-center justify-content-between">
                            <span>Vertical</span>
                            <p:inputText id="globalFilter" onkeyup="PF('treeTable').filter()" style="width:10rem" placeholder="Enter keyword" />
                        </div>
                    </f:facet>
                    <p:column headerText="Name" filterBy="#{document.name}" filterMatchMode="contains">
                        <h:outputText value="#{document.name}"/>
                    </p:column>
                    <p:column headerText="Size">
                        <h:outputText value="#{document.size}"/>
                    </p:column>
               </p:treeTable>
....

The methode globalFilterFunction exists in ScrollableView:

```
    public boolean globalFilterFunction(Object value, Object filter, Locale locale) {
        if (filter == null) {
            return true;
        }
        String filterText = filter.toString().toLowerCase().trim();
        System.out.println(" *****  " + filterText);
        return true;
    }
```

If i try to use globalFilterFunction on the same way in dataTable - it works fine.

I'm using Payara 5.2020.5

### Reproducer

                <p:treeTable widgetVar="treeTable" value="#{ttScrollableView.root1}" var="document"
                             style="margin-top:0" globalFilterFunction="#{ttScrollableView.globalFilterFunction}">
                    <f:facet name="header">
                        <div class="flex align-items-center justify-content-between">
                            <span>Vertical</span>
                            <p:inputText id="globalFilter" onkeyup="PF('treeTable').filter()" style="width:10rem" placeholder="Enter keyword" />
                        </div>
                    </f:facet>
                    <p:column headerText="Name" filterBy="#{document.name}" filterMatchMode="contains">
                        <h:outputText value="#{document.name}"/>
                    </p:column>
                    <p:column headerText="Size">
                        <h:outputText value="#{document.size}"/>
                    </p:column>
               </p:treeTable>

### PrimeFaces edition

Community

### PrimeFaces version

11.0.2

### Theme

Serenity

### JSF implementation

Mojarra

### JSF version

2.3.14.payara-p2

### Java version

8

### Browser(s)

Edge

**Comment by tandraschko** [comment]
does it work on 13.0-SNAPSHOT?

**Comment by lehmser** [comment]
> does it work on 13.0-SNAPSHOT?

Yes, it seems now to work in 13.0-SNAPSHOT
