### ISSUE TITLE
Tree: pfAjaxComplete and pfAjaxStart not working when filter a tree

### ISSUE THREAD

**Issue by l-uuz** [primefaces/primefaces#9873]
### Describe the bug

When a Tree is filtered, an Ajax call is performed (see browser console), but event handlers for `pfAjaxStart` `pfAjaxComplete` don't react.

### Reproducer

[primefaces-ajax-trigger-missing.zip](https://github.com/primefaces/primefaces/files/10897430/primefaces-ajax-trigger-missing.zip)

```xhtml
<p:tree value="#{testView.root}" var="node" filterBy="#{node}">
  <p:treeNode>
    <h:outputText value="#{node}" />
  </p:treeNode>
</p:tree>
<script>
  $(document).on('pfAjaxStart',()=>console.info('Test'))
</script>
```

Also reproducable in PrimeFaces Showcase (type `$(document).on('pfAjaxStart',()=>console.info('Test'))` in the browser console and look for messages. Compare [Tree](https://www.primefaces.org/showcase/ui/data/tree/filter.xhtml) with [Data Table](https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml).

### Expected behavior

`pfAjaxStart` and `pfAjaxComplete` should be called.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

**Comment by tandraschko** [comment]
Currently by design: https://github.com/primefaces/primefaces/blob/2b619c9c30589b700adea84d82eff48a5c9ea606/primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js#L1428

You can however add p:ajax event=filter global=true

**Comment by l-uuz** [comment]
Thanks!
