### ISSUE TITLE
SplitButton: with filter is auto closing in Chrome on Android

### ISSUE THREAD

**Issue by MPiresIndentar** [primefaces/primefaces#9875]
### Describe the bug

Is closing menu items in split button with filter in mobile.

https://user-images.githubusercontent.com/80966572/223216717-6e9cd4e6-c8c5-4600-9811-1b4055175bad.mp4

### PrimeFaces edition

Community

### PrimeFaces version

12

### Theme

Show Case

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

Chrome 110.0.5481.178

**Comment by MPiresIndentar** [comment]
In select check box menu, working.... maybe,if  do the same

https://user-images.githubusercontent.com/80966572/223228577-15b2d600-9cba-40ac-8c63-ced6167596e6.mp4

**Comment by melloware** [comment]
It looks like that is different the selectCheckbox isn't getting focus right away. You have to click on the filter to focus it? So it looks different.

**Comment by melloware** [comment]
Actually that even looks like an oversight i think the SelectCheckBoxMenu should be focusing the filter immediately.

**Comment by melloware** [comment]
Can you go here and click on the Advanced Example of SelectOne: https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml?jfwid=bc095

I would expect it does what SplitButton is doing?

**Comment by MPiresIndentar** [comment]
Is working too 
https://user-images.githubusercontent.com/80966572/223232980-a1250689-2109-4cbb-a65b-ee8e85a469c3.mp4

**Comment by melloware** [comment]
I just compared SelectOne Filter and SplitButton filter and the code is identical.

**Comment by MPiresIndentar** [comment]
wouldn't it be some javascript code that may be closing?

**Comment by melloware** [comment]
Yep that is what I compared the JS code and the filter events on both.  Feel free to compare the two components and look for differences.

**Comment by MPiresIndentar** [comment]
I'm doing

**Comment by filipe1238** [comment]
Same issue here, it seens that split button menu insta closes whenever it activates the focus.
But, the same doesn't happen on the select one menu, weird.
Tested in a few different browsers, same thing happened as well

**Comment by melloware** [comment]
As I said the code is identical as far as I can see so feel free to research and provide a PR. 

I have an iPhone and it does not happen so it seems to be isolated to Chrome on Android.  Have your tried another browser on your Android?

**Comment by MPiresIndentar** [comment]
in opera it was the same

**Comment by melloware** [comment]
Chrome and Safari on IOS both work fine.

**Comment by melloware** [comment]
OK I wonder if we need a new property similar to I added to PrimeReact called "filterAutoFocus=false".

See: https://github.com/primefaces/primereact/issues/2679

**Comment by filipe1238** [comment]
that would be a amazing indeed (would be nice if the default was true though, since it already is)

**Comment by melloware** [comment]
Yea it would be true and you would have to opt out of it.

**Comment by melloware** [comment]
PR Submitted
