### ISSUE TITLE
Dialog: resizing horizontally causes a gap between scrollbar and dialog right border

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#9882]
Resizing dialog horizontally causes a gap between scrollbar and dialog right border.

http://www.primefaces.org:8080/showcase/ui/overlay/dialog.xhtml

Steps to reproduce:
1. Show Model dialog (or others)
2. Resize dialog height to make vertical scroll show.
3. Then resize the dialog horizontally, a gap between the scroll and dialog right border will show.

**Comment by melloware** [comment]
OK yep that is definitely wrong.

**Comment by jepsar** [comment]
@javaone199 please use the issue next time. It will automatically tag the issue with the correct labels.

**Comment by melloware** [comment]
MonkeyPatch:

```js
if (PrimeFaces.widget.Dialog) {
    PrimeFaces.widget.Dialog.prototype.saveState = function() {
        this.state = {
            width: this.jq.width(),
            height: this.jq.height(),
            contentWidth: parseInt(this.content[0].style.width) || this.content.width(),
            contentHeight: this.content.height()
        };

        var win = $(window);
        this.state.offset = this.jq.offset();
        this.state.windowScrollLeft = win.scrollLeft();
        this.state.windowScrollTop = win.scrollTop();
    }
}
```
