### ISSUE TITLE
Build: Different names for release and debug artifacts

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#9883]
### Description

mvn clean install
mvn clean install -Pminify

For debugging js and testing release,  need to rebuild for release and debug which will override each other with the same artifact name.

### Describe the solution you would like

Different names for release and debug artifacts.

If -Pminify is not specified, add a suffix (e.g., -debug) to artifact name.

**Comment by tandraschko** [comment]
TBH we do this since years and i use PF builds daily, i would not change our already complex build for such a feature

**Comment by melloware** [comment]
I chose a different route just adding a new `-Pdebug` profile so you can choose when its debug or not.

This allows you to say `mvn clean install -Pdebug` to give the JAR a "-debug" extension.  So you can combine it with other profiles like...

`mvn clean package -Pquick,debug` to do the quick profile and rename it debug.
