### ISSUE TITLE
Dialog Framework: Dragging problem

### ISSUE THREAD

**Issue by pmaloneyits** [primefaces/primefaces#989]
I am seeing an issue when dragging dialogs created through the Dialog Framework. `<p:dialog>` does not have this problem. This issue can be demonstrated in the Showcase on the PrimeFaces web site:
1. Go to Showcase, pick Dialog Framework, and then pick 'Basic'.
2. Click on the 'View' button.
3. When the dialog appears, move your cursor to the title bar and left click. Hold the left mouse button down for the remaining steps.
4. Drag the window to the top of the screen. Then, rapidly drag it down. You will notice that, when the cursor dips into the content area, the dragging stops.
5. Move the cursor outside the content area. The dialog will snap to that location.

Another issue that occurs is, if you release the left mouse button while your cursor is in the content area (during step 4), the dialog is left in an odd state because, if you then move the cursor over the title bar, it still thinks it's in drag mode and will move the dialog.

This happens in IE, Firefox, and Safari, so it doesn't appear browser related.

As I said above, this does not happen with `<p:dialog>`.  It looks like the `<iframe>` in the dynamic dialog (which is not present in the `<p:dialog>`) is the problem.  Using Firefox's inspector, if I set 'display: none' on the `<iframe>`, the issue does not occur. If I set it back to 'display: block', it occurs again.

I came up with a work-around of sorts in core.dialog.js. See the block of new code in the middle below (surrounded by comments):

``` javascript
PrimeFaces.dialog.DialogHandler = {

    openDialog: function(cfg) {
        var dialogId = cfg.sourceComponentId + '_dlg';
        if(document.getElementById(dialogId)) {
                return;
        }

        var dialogWidgetVar = cfg.sourceComponentId.replace(/:/g, '_') + '_dlgwidget',
        dialogDOM = $('<div id="' + dialogId + '" class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-hidden-container ui-overlay-hidden"' + 
                ' data-pfdlgcid="' + cfg.pfdlgcid + '" data-widgetvar="' + dialogWidgetVar + '"></div>')
                .append('<div class="ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-corner-top"><span class="ui-dialog-title"></span></div>');

        /* START OF NEW CODE - WORK-AROUND */        
        if (cfg.options.draggable !== false) {
                dialogDOM.find(".ui-dialog-titlebar").on("mousedown", function() {
                        var ifr = dialogDOM.find("iframe");
                        ifr.hide();
                });
                dialogDOM.on("mouseup", function() {
                        var ifr = dialogDOM.find("iframe");
                        ifr.show();
                });
        }
        /* END OF NEW CODE - WORK-AROUND */        

        var titlebar = dialogDOM.children('.ui-dialog-titlebar');
        if(cfg.options.closable !== false) {
                titlebar.append('<a class="ui-dialog-titlebar-icon ui-dialog-titlebar-close ui-corner-all" href="#" role="button"><span class="ui-icon ui-icon-closethick"></span></a>');
        }
```

When you click on the title bar, it hides the `<iframe>`. On mouseup, it shows it again.  This particular code isn't perfect. From what I've read, the mouseup should go on the outer-most document. But, I'm barely a jQuery novice, so I don't know how to do that here.

There still are some quirks with this where you'll move and end up with a blank window. Clicking anywhere on the dialog makes the content reappear. Not perfect, but better than it was for me.

**Comment by melloware** [comment]
I can't reproduce this in the latest showcase 7.1.  Maybe its been fixed over the years by the Jquery upgrades we have done.
