### ISSUE TITLE
p:printer broken with Rain layout

### ISSUE THREAD

**Issue by ybendek** [primefaces/primefaces#9890]
### Describe the bug

I'm trying to use the p:printer component but it looks broken if I use the Rain Theme and Layout in my app, basically the page to be printed is in blank and nothing is included, only the basic headers and footers. 

### Reproducer

This is a simple example including the RAIN template in the page 
![image](https://user-images.githubusercontent.com/13785120/224113859-103ef6e1-12ba-4a68-b939-ca1640e6f7b7.png)

In this case when the "print" button is pressed a web printer component is displayed but th page is blank, the text "This is a try to print data" inside of panel "panelToPrint" is not included.

![image](https://user-images.githubusercontent.com/13785120/224115011-d90ca758-383a-456c-8456-0586bd7ab509.png)

However, if I made the same example but not using the RAIN theme/layout
![image](https://user-images.githubusercontent.com/13785120/224114707-dde61223-e8b6-466a-968d-6b843f7f8801.png)

The page is rendered as expected
![image](https://user-images.githubusercontent.com/13785120/224115232-f0dc0e3d-9e8a-4608-a037-26d58b67ab52.png)

### Expected behavior

The p:printer component should print the "target" component and all the contents

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.3

### Theme

Rain 4.1.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

11

### Browser(s)

Chrome

**Comment by melloware** [comment]
Already reported in RAIN forum this is the community tracker so there is nothing for us to fix.  https://forum.primefaces.org/viewtopic.php?f=138&t=79526

**Comment by ybendek** [comment]
Yes the solution is just to comment  this line

` body * {
    visibility: hidden;
  }`

**Comment by rho66** [comment]
I have the same problem with printer and Rain - but the link results in a 404 Not Found!

Where should i comment  `body * { visibility: hidden; }` ?

**Comment by rho66** [comment]
I found this line in _invoice.scss and commenting it makes printer working!

**Comment by melloware** [comment]
Yep that line was messing up the Printer and its only used in the Rain invoice example so it can absolutely be removed.
