### ISSUE TITLE
RowExpansion: Ajax call under RowExpansion triggers datatable ajax too

### ISSUE THREAD

**Issue by omerogrek** [primefaces/primefaces#9895]
### Describe the bug

When we trigger the row select under the rowExpansion, it triggers the ajax function first, then triggers the datatable ajax rowSelect outside of the rowExpansion. We just upgraded the project from Primefaces 7 to Primefaces 12.0.3. In Primefaces 7, when we click the row under the rowExpansion, it only triggers rowSelect under the rowExpansion which we expect it to work.  

### Reproducer

	<p:dataTable id="listOfLoadItems" var="loadItem"
		widgetVar="loadItemsWidget"
		value="#{flightEngineBean.loadItemBulksULDs}"
		rowKey="#{loadItem}" rowIndexVar="rowIndex"
		emptyMessage="#{messageMap['NO_RECORDS_FOUND']}"
		selection="#{flightEngineBean.selectedItems}"
		expandedRow="#{flightEngineBean.isULDRowExpandedOnce(loadItem)}"
		update="display">

		<p:ajax event="rowSelect" onstart="saveScrollPos()"
			update=":flightEngineForm, :formUpdateLoadItem, :formAddLoadItem,:formDialogDivideMoveLoad:display1, :growl"
			listener="#{flightEngineBean.rowSelection(false)}"
			oncomplete="getScrollPos()" />
		<p:ajax event="toggleSelect" onstart="saveScrollPos()"
			update=":flightEngineForm, :formUpdateLoadItem, :formAddLoadItem,:formDialogDivideMoveLoad:display1, :growl"
			listener="#{flightEngineBean.toggleSelection(false)}"
			oncomplete="getScrollPos()" />
		<p:ajax event="rowToggle"
			update=":growl,:flightEngineForm:listOfLoadItems:listOfLoadItemsInsideULD"
			listener="#{flightEngineBean.rowToggling(loadItem)}"
			oncomplete="getScrollPos()" />

		<p:column headerText="#{messageMap['TYPE']}"
			sortBy="#{loadItem.type}" filterBy="#{loadItem.type}"
			filterMatchMethod="contains" width="60">
			<h:outputText value="#{loadItem.type}" />
		</p:column>

		<p:rowExpansion>

			<p:dataTable id="listOfLoadItemsInsideULD"
				value="#{flightEngineBean.loadItemULDsAndItemsInsideThem.get(loadItem)}"
				var="loadItemInsideULD" rowKey="#{loadItemInsideULD}"
				emptyMessage="#{messageMap['NO_RECORDS_FOUND']}"
				selection="#{flightEngineBean.selectedItems}"
				style="text-align: center; font-style: italic; margin-left: 3%"
				rowStyleClass="rowForItemInsideULD">

				<p:ajax event="rowSelect"
					update=":flightEngineForm, :formUpdateLoadItem, :formAddLoadItem, :growl"
					listener="#{flightEngineBean.rowSelection(false)}" />

				<p:column width="70">
				<h:outputText
					value="#{loadItemInsideULD.fromPortCode}-#{loadItemInsideULD.toPortCode}" />
				</p:column>

				<p:column width="60">
					<h:outputText value="#{loadItemInsideULD.type}" />
				</p:column>

			</p:dataTable>

		</p:rowExpansion>

	</p:dataTable>

### Expected behavior

When we clicked a row under rowExpansion datatable, it only triggers ajax call inside the rowExpansion datatable. 

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.3

### JSF implementation

All

### JSF version

2.2.11

### Java version

8

**Comment by omerogrek** [comment]
[rowExpansion.zip](https://github.com/primefaces/primefaces/files/10967623/rowExpansion.zip)

I modified the primefaces test project. When you click the row expansion and click the datatable inside the row expansion, in console you can see that first enters the row expansion ajax calls, then datatable outside of the rowexpansion calls.

**Comment by melloware** [comment]
Most likely the jQuery selector isn't specific enough so its finding both.

**Comment by omerogrek** [comment]
Is this something i can fix? It was working properly on primefaces 7.

**Comment by melloware** [comment]
I think its related to this: https://github.com/primefaces/primefaces/pull/9026 and this issue: https://github.com/primefaces/primefaces/issues/8620

cc @vonnai

**Comment by melloware** [comment]
MonkeyPatch:

```js
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.setupSelection = function() {
        this.selectionHolder = this.jqId + '_selection';
        this.cfg.rowSelectMode = this.cfg.rowSelectMode || 'new';
        this.rowSelector = '> tr.ui-widget-content.ui-datatable-selectable';
        this.cfg.disabledTextSelection = this.cfg.disabledTextSelection === false ? false : true;
        this.cfg.selectionPageOnly = this.cfg.selectionPageOnly !== false;
        this.rowSelectorForRowClick = this.cfg.rowSelector || 'td:not(.ui-column-unselectable):not(.ui-grouped-column),span:not(.ui-c)';

        var preselection = $(this.selectionHolder).val();
        this.selection = !preselection ? [] : preselection.split(',');

        //shift key based range selection
        this.originRowIndex = null;
        this.cursorIndex = null;

        this.bindSelectionEvents();
    }
}
```
