### ISSUE TITLE
DataTable RowExpansion: missing headerText

### ISSUE THREAD

**Issue by aripddev** [primefaces/primefaces#9896]
### Describe the bug

When creating a sub `DataTable` under `RowExpansion` headerText is missing if the parent DataTable has `reflow="true"` parameter. When set `reflow="false"`, headerText appears.

### Reproducer

You can find the output as screen shot and sample codes inside issureport.zip

[issuereport.zip](https://github.com/primefaces/primefaces/files/10949170/issuereport.zip)

<img width="656" alt="Screenshot 2023-03-11 at 19 17 30" src="https://user-images.githubusercontent.com/9448030/224505521-0bbb243f-fd94-4d24-ad1a-276d4fdaf9df.png">

### Expected behavior

headerText must be shown

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

11

### Browser(s)

Safari

**Comment by melloware** [comment]
I am pretty sure reflow was not meant to be used with a lot of other features as it's almost impossible to make them all work together!

**Comment by aripddev** [comment]
You could be right. I noticed this error while working on it and wanted to report it. BTW, I just realized that footerText works as expected.

**Comment by aripddev** [comment]
I think that I found the reason. In datatable.css file at line 298, class name should be change to `.ui-expanded-row` instead of `.ui-expanded-row-content`

https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css#L298

**Comment by melloware** [comment]
Feel free to submit a PR for us to review!

**Comment by aripddev** [comment]
@melloware I took some more time to review. The change affects other components as well (ColumnToggler and TreeTable). So I decided to keep it as is and to use `reflow="false"`. Please cancel my issue. Thanks.

[issuereport.zip](https://github.com/primefaces/primefaces/files/10950436/issuereport.zip)
