### ISSUE TITLE
Poll: wrong attribute 'action' in start / stop example

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#9897]
### Describe the bug

In the documentation example of poll component for start / stop there is the attribute 'action' used - but this is not documented! I assume it should be 'listener' instead.

### Reproducer

https://primefaces.github.io/primefaces/12_0_0/#/components/poll

### Expected behavior

Now:
<p:poll interval="5" action="#{counterBean.increment}" update="txt_count" widgetVar="myPoll" autoStart="false" />

Expected:
<p:poll interval="5" listener="#{counterBean.increment}" update="txt_count" widgetVar="myPoll" autoStart="false" />

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Thanks for reporting!
