### ISSUE TITLE
DataTable: columnIndexVar for dynamic columns not working with ID attribute

### ISSUE THREAD

**Issue by l-uuz** [primefaces/primefaces#9899]
### Describe the bug

Inside `p:columns` you cannot use a declared `columnIndexVar` in the ID attribute.
If you use it e.g. in the ID of an Inplace, the Inplace is broken.

### Reproducer

[primefaces-inplace-in-table-header.zip](https://github.com/primefaces/primefaces/files/10955511/primefaces-inplace-in-table-header.zip)

The important part:

```xml
<p:dataTable id="datatable" var="str" value="#{testView.list}">
  <p:columns id="columns" value="#{testView.columns}" var="column" columnIndexVar="index">
    <f:facet name="header">
      <h:outputText value="Header #{index}"/>
      <!-- #{index} is not replaced in the IDs. this may be the cause why the inplaces are not working -->
      <p:inplace id="inplace_#{index}" editor="true" emptyLabel="Header Text">
        <p:inputText id="inplace_#{index}_Editor" value="#{column.title}"/>
      </p:inplace>
    </f:facet>
    <!-- #{index} is also not replaced. ID is e.g. "frmTest:datatable:1:columns:0:text_" -->
    <h:outputText id="text_#{index}" value="#{str} in #{column.content}"/>
  </p:columns>
</p:dataTable>
```

The Inplace elements in the header are broken, they don't save their value. When you remove the IDs, it works.

### Expected behavior

`columnIndexVar` should be working and the Inplace elements should work.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

**Comment by tandraschko** [comment]
i dont think we can fix it easily, maybe someone would like to give it a try

**Comment by melloware** [comment]
I thought I saw a post somewhere too to never use EL expressions in `id` field. I am looking for it.  I feel like BalusC explained why you don't want to do that.
