### ISSUE TITLE
Provide build-in converter in p:calendar for JSR 310 (LocalDate, LocalDateTime, ...)

### ISSUE THREAD

**Issue by juergenzimmermann** [primefaces/primefaces#990]
It would be nice, if not only the "old-fashioned" java.util.Date and java.util.Calendar would be supported, but also the the classes in the java.time package like e.g. LocalDate and LocalDateTime.

**Comment by tandraschko** [comment]
We be nice if you could provide a PR, which is still compatible with java7.

**Comment by juergenzimmermann** [comment]
Sorry, providing a PR is beyond my capacity.
Maybe the use of http://www.threeten.org/ could help your for Java 7.

**Comment by tandraschko** [comment]
It should already work if you use a own converter - we maybe provide build in functionality in the future.

**Comment by sudheerj** [comment]
By the way JSF 2.3 supported Java8 Date Time API through f:convertDateTime tag in m4 milestone

**Comment by tandraschko** [comment]
Sure - but some user will use java8 without JSF 2.3 ;)
It's just a feature request, the easiest way is to provide a own converter.

**Comment by tandraschko** [comment]
converters are full supported in the calendar now - will close this feature request for now as this can easily be done with a converter

**Comment by ghost** [comment]
Please add an optional `converterType` attribute so it passes it through in JSF 2.3 to the converter.
