### ISSUE TITLE
FileDownload: Download file with ajax success, but the file only 1KB

### ISSUE THREAD

**Issue by buleseli** [primefaces/primefaces#9900]
### Describe the bug

my xhtml file:

        <p:commandButton value="download" icon="pi pi-arrow-down" styleClass="ui-button-outlined"
        update=":base_form:txtCaptchaId" actionListener="#{lkmToolBean.doDownload}">
        <p:fileDownload value="#{lkmToolBean.downFile}"/>
        </p:commandButton>

my backing bean:

        @ManagedBean
        @ViewScoped
        public class LkmToolBean implements Serializable {
        
           private StreamedContent downFile;
           .........
            public void doDownload(ActionEvent actionEvent) {
              if (StringUtils.isBlank(captchaText)) {
                     PrimeFaces.current().dialog().showMessageDynamic(new FacesMessage("please input captcha"));
              } else {
                    String imgC =(String) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("CAPTCHA");
                    if (captchaText.equals(imgC)) {
                        //i download the file from ftp server first
                       downFile = DefaultStreamedContent.builder().name(selected.getFile()).contentType("application/pdf")
                                           .stream(() -> { return new ByteArrayInputStream(ftp.getFileByte("pdf/" + selected.getFile())); }).build();
            
                       PrimeFaces.current().executeScript("PF('dlg4').hide();");
                    } else {
                     PrimeFaces.current().dialog().showMessageDynamic(new FacesMessage("code invalid"));
                    }
                   this.captchaText = "";
              }
            }

### Reproducer

1.change commandButton ajax="true"
2.click download

### Expected behavior

download file must normally!

### PrimeFaces edition

None

### PrimeFaces version

11.0.0

### Theme

saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

openjdk 11.0.15.1

**Comment by NicolaIsotta** [comment]
You cannot use `ajax=true` with `@ViewScoped` beans. See: https://primefaces.github.io/primefaces/12_0_0/#/core/dynamiccontent?id=viewscoped-support

**Comment by buleseli** [comment]
> You cannot use `ajax=true` with `@ViewScoped` beans. See: https://primefaces.github.io/primefaces/12_0_0/#/core/dynamiccontent?id=viewscoped-support

the same question when i change the backing bean to RequestView!

the browse console show "404"--Failed to load resource: the server responded with a status of 404 (Not Found)!

**Comment by jepsar** [comment]
Please provide a reproducer.

**Comment by buleseli** [comment]
> Please provide a reproducer.

**Does the dynamiccontent don't support RequestScope at all?**
 i bind a StreamedContent to p:graphicImage and p:fileDownload; **the image disappear,when i click download button,1KB file i got!**
But if i change Backing bean to @SessionScoped,all thing work file--include image and filedownload!

please see the demo:

1. delopy the web project to tomcatee or weblogic
2. click the "ShowDownloadDialog" button
3. after dialog show,input the CAPTCHA,then click "Download"


[demo1.zip](https://github.com/primefaces/primefaces/files/10967082/demo1.zip)

**Comment by buleseli** [comment]
i have change reproduce to primefaces-test.please see the newest attacement ,tks!

1.  mvn clean jetty:run -Pmojarra23
2.  visit http://localhost:8080/primefaces-test/demo.xhtml
3. click the "ShowDownloadDialog" button
4. after dialog show, the image disappear,when i click download button,the browse will download the image --1KB file i got!
5. if i change backing bean "CaptchaView" from @RequestScoped to SessionScoped,all thing work fine!

**Comment by buleseli** [comment]
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10975025/primefaces-test-master.zip)

**Comment by jepsar** [comment]
Two things:

1. Start from the working primefaces-test repo instead of dropping in classes from external projects and make changes step by step to figure out where things go wrong.
2. You are using deprecated beans:

```java
@javax.faces.bean.ManagedBean
@javax.faces.bean.ViewScoped
```
If I change them to

```java
@javax.inject.Named
@javax.enterprise.context.RequestScoped
```

it works.

**Comment by buleseli** [comment]
> Two things:
> 
> 1. Start from the working primefaces-test repo instead of dropping in classes from external projects and make changes step by step to figure out where things go wrong.
> 2. You are using deprecated bean annotations:
> 
> ```java
> @javax.faces.bean.ManagedBean
> @javax.faces.bean.RequestScoped
> ```
> 
> If I change them to
> 
> ```java
> @javax.inject.Named
> @javax.enterprise.context.RequestScoped
> ```
> 
> it works.
  thanks jepsar!
  it is helpful for me to  give some advises about provide primefaces-test .i will remeber it!

  my project must use deprecated bean annotations,maybe use CDI in few years later! 
   so,it's meaning that i cann't use javax.faces.bean.RequestScoped if i want to use primefaces dynamiccontent feature?

**Comment by jepsar** [comment]
I'm not sure. Even if it is, I don't think anything can or will be done about it. CC @melloware @tandraschko

**Comment by melloware** [comment]
Not sure I haven't used anything but CDI my whole JSF lifespan
