### ISSUE TITLE
Galleria: getEventNames() returns null

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#9912]
### Describe the bug

Component `org.primefaces.component.Galleria` returns `null` on `getEventNames()`.
According to Faces specs, this should be a non-null collection.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.1

### Java version

8

**Comment by jepsar** [comment]
That's done by a third party https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/jakarta/faces/component/UIComponentBase.java#L1597
