### ISSUE TITLE
SelectBooleanCheckbox: It is deformed if it has with large itemLabel

### ISSUE THREAD

**Issue by raul810y** [primefaces/primefaces#9918]
### Describe the bug

SelectBooleanCheckbox is deformed if it has large itemLabel and with small resolutions.

In demo page is possible to reproduce the issue:
<img width="798" alt="Captura de Pantalla 2023-03-14 a la(s) 22 50 16" src="https://user-images.githubusercontent.com/30551904/225210370-ceeca6e7-cb15-4230-baff-a04f7b252b05.png">

### Reproducer

<div class="card">
    <h:form>

        <h5 class="mt-0">Basic</h5>
        <p:selectBooleanCheckbox value="#{selectBooleanView.value1}" itemLabel="Basic text too large Basic text too large  Basic text too large Basic text too large Basic text too large Basic text too large "/>
    </h:form>
</div>

### Expected behavior

The checkbox square should keep its shape instead of becoming a rectangle

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

4.0

### Java version

8 and later

### Browser(s)

Chrome Versión 111.0.5563.64 (Build oficial) (x86_64) macOS

**Comment by melloware** [comment]
CSS workaround:
```css
body .ui-chkbox .ui-chkbox-box {
   min-width: 1.5rem;
}
```
