### ISSUE TITLE
textEditor: bind toolbar to bean variable

### ISSUE THREAD

**Issue by javaone199** [primefaces/primefaces#9919]
### Description

textEditor toolbar is hardcoded as followings:

https://www.primefaces.org/showcase/ui/input/textEditor.xhtml
 
       <h3 class="first">Custom Toolbar</h3>
        <p:textEditor widgetVar="editor2" value="#{editorView.text2}" height="300" placeholder="Enter your content" required="true">
            <f:facet name="toolbar">
             <span class="ql-formats">
                <button class="ql-bold"></button>
                <button class="ql-italic"></button>
                <button class="ql-underline"></button>
                <button class="ql-strike"></button>
            </span>
                <span class="ql-formats">
                <select class="ql-font"></select>
                <select class="ql-size"></select>
            </span>
            </f:facet>
        </p:textEditor>

It is more flexible to bind the toolbar  to variable.
Use case: initially a small number of buttons, user can expand the toolbar if needed.

### Describe the solution you would like

<p:textEditor toolbar="ql-bold,ql-italic,ql-underline,ql-strike,ql-font,ql-size" />
<p:textEditor toolbar="#{bean.toolbar}" />

**Comment by melloware** [comment]
I think you can do this now?

Have you tried `<h:outputText value="#{yourBeanToolbar}" escape="false" />` ???

**Comment by melloware** [comment]
Will close for now.  I didn't test that solution but I can't imagine why it wouldn't work but let us know if it does not work...

**Comment by jepsar** [comment]
I think I'm doing something like that in an application. It should work.
