### ISSUE TITLE
Remove JSF 2.0 and JSF 2.1 support

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#9921]
we cant even run our integration tests on this versions

**Comment by jepsar** [comment]
I think we should already announce this in the 13 migration guide.

**Comment by melloware** [comment]
Agreed and dont forget we have this old ticket: https://github.com/primefaces/primefaces/issues/6773

**Comment by Rapster** [comment]
@jepsar Also, it's important to remind what are the minimal requirements then: servlet 3.0. CDI 1.1 etc.
