### ISSUE TITLE
AutoComplete: uses hardcoded, english text in widget

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#9922]
https://github.com/primefaces/primefaces/blob/43f22012f9f2bb58ede5bbed83e8652e5b167fbf/primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js#L124-L125

**Comment by stolp** [comment]
German:

```
this.cfg.resultsMessage = this.cfg.resultsMessage || ' Ergebnisse sind verfügbar, verwenden Sie die Pfeiltasten nach oben und unten zum Navigieren'; 
 this.cfg.ariaEmptyMessage = this.cfg.emptyMessage || 'Es sind keine Suchergebnisse verfügbar.'; 
```

**Comment by erickdeoliveiraleal** [comment]
In pt BR "Resultados estão disponíveis, use as teclas baixo e cima para navegar" / "Nenhum resultado da busca disponível"
