### ISSUE TITLE
dialogReturn event doesn't get fired after removing the active datatable element

### ISSUE THREAD

**Issue by Harwkx** [primefaces/primefaces#994]
# Summary

I have the reproduceable problem, that a `dialogReturn` event does not trigger, if the current passed object is removed from a datatable.
## Example

In this example, i want to generate a message in the `SelectEvent` listener:

``` xml
...
<p:growl id="growl" showDetail="true" sticky="true" />
<p:datatable id="tblData" value="#{ctrlBean.colData}" var="recData">
  <p:column>
    <p:commandButton value="test" actionListener="#{ctrlBean.doStage1(recData)}">
      <p:ajax event="dialogReturn" listener="#{ctrlBean.reactStage}" update=":form:growl,tblData" />
    </p:commandButton>
  </p:column>
</p:dataTable>
...
```
## Problem

The key problem is, that a message passed to the `SelectEvent` is properly proccessed, if `recData` doesn't get removed from the displayed list (`ctrlBean.colData`). If the element gets removed, the table actually updates itself, but the ajax listener function doesn't get called.
## Testing

This is tested with primefaces-5.3 and primefaces-5.2 on myfaces-2.2.8.

**Comment by tandraschko** [comment]
I will close the issue for now as it doesn't have a runnable sample (bean+xhtml).
If you can provide both - or a forked primefaces-test project - please create a new issue and i will have a look. We fixed some dialogReturn stuff the last months.
