### ISSUE TITLE
SelectOneMenu: title attribute of options is not escaped

### ISSUE THREAD

**Issue by blutorange** [primefaces/primefaces#9943]
### Describe the bug

The title attribute for the options of the SelectOneMenu component is not escaped. When user input is put into the title attribute, the generated HTML is invalid and the options do not display correctly. HTML or script tags in the user input might also be executed. 

Cause is here, where an HTML string is created without any escaping. I don't think there is a reason not to escape, HTML is not allowed in the `title` attribute anyways as far as I know:

https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L1536

It works properly when I replace the line above with

```js
            content += ' title="' + PrimeFaces.escapeHTML(title) + '"';
```

As a simple example (adapted from a real-world example where a user of our application had some HTML in the title). In this particular example, only the first two options are shown to the user, because the HTML is broken.

```xml
<p:selectOneMenu value="#{bean.value}">
  <f:selectItems value="#{bean.options}">
</p:selectOneMenu>
```

```java
class Bean {
  private String value;
  public String getValue() {return value;}
  public void setValue(String value) {this.value=value;}
  public List<SelectItem> getOptions() {
    return List.of(
      new SelectItem("value1", "label1", "desc1"),
      new SelectItem("value2", "label2", "<script language=\"javascript\" type=\"text/javascript\"> <!-- window.setTimeout('window.location = \"https://example.com/foobar/\",10000); // –> </script>"),
      new SelectItem("value3", "label2", "desc3")
    );
  }
}
```

Without escaping, the list of options suddenly ends:
![image](https://user-images.githubusercontent.com/2456413/226695881-6d9d50eb-db5d-41b4-b76d-1e39798cac6d.png)

With escaping, all options are present and the title attribute is shown correctly:
![image](https://user-images.githubusercontent.com/2456413/226695718-6a91af55-bd79-46fa-aa54-c931f9fb358d.png)

### PrimeFaces edition

None

### PrimeFaces version

11.0.10

### JSF implementation

Mojarra

### JSF version

2.3.16

### Java version

17

**Comment by fcorneli** [comment]
Backport to 12.0.4 maybe since it's a XSS vulnerability?

**Comment by melloware** [comment]
@fcorneli @blutorange done! requested this for 12.0.5
