### ISSUE TITLE
Keyboard "Back" Behavior in Chromium

### ISSUE THREAD

**Issue by mrcasio** [primefaces/primefaces#9946]
### Describe the bug

In the keyboard showcase, the Back Button is just working correctly on the first click. After the first "Back" Click, the focus on the input field is missing, and you can't reuse the back button.

The Libary http://keith-wood.name/keypad.html is fixing this error in version 2.1.1

https://github.com/kbwood/keypad/commit/5f25ad8beac6cb1f9a66582853b715d7689050e9 

With just adding:
`inst._input.focus();`

### Reproducer

Go to https://www.primefaces.org/showcase/ui/input/keyboard.xhtml
Click on Default Layout and click on two characters
Click on Back, and the last character will remove
Click on Back, and nothing happened

### Expected behavior

Go to https://www.primefaces.org/showcase/ui/input/keyboard.xhtml
Click on Default Layout and click on two characters
Click on Back, and the last character will remove
Click on Back, and the last character will remove

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Java version

Jakartar 11 

### Browser(s)

Chrome 111.0.5563.65

**Comment by melloware** [comment]
Thanks for reporting, indeed it is fixed in 2.1.1
