### ISSUE TITLE
License and Bundle Plugin Warnings

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces#9967]
Haven't looked in a while but I like to keep our Maven builds as warning free as possible.

- [x] License Plugin:
```
[WARNING] Parameter 'legacyConfigExcludes' (user property 'license.excludes') is deprecated: use LicenseSet.excludes
[WARNING] Parameter 'legacyConfigHeader' (user property 'license.header') is deprecated: use LicenseSet.header
[WARNING] Parameter 'legacyConfigIncludes' (user property 'license.includes') is deprecated: use LicenseSet.includes
```

- [ ] Bundle Plugin
```
[WARNING] Manifest org.primefaces:primefaces:jar:13.0.0-SNAPSHOT : 
Unused Import-Package instructions: [javax.faces.component.search.*, javax.inject.*, javax.enterprise.*] 
```

**Comment by melloware** [comment]
@stiemannkj1 Can you make sure this Felix bundle plugin issue above is a false positive.  It looks like you explicitly added these `*` optional resolutions?

**Comment by stiemannkj1** [comment]
I believe these are false-positives and that PrimeFaces needs the `optional` packages to work in OSGi and in Liferay as an OSGi bundle. Does PrimeFaces use those packages only via reflection? I'd bet that's why the plugin thinks they're unused. I can try to dig deeper tomorrow if I have time. @ngriffin7a, you might also want to take a look.

**Comment by ngriffin7a** [comment]
@melloware Is there a -SNAPSHOT version of PrimeFaces 13 that I can try in Liferay to see if there is a problem? Thanks.

**Comment by melloware** [comment]
You can try 13.0.0-SNAPSHOT here if you want.

```xml
<!-- Java EE / javax.* / JSF 2.0 - JSF 2.3 -->
<dependency>
    <groupId>com.github.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>master-SNAPSHOT</version>
</dependency>

<!-- Jakarta EE / jakarta.* / Faces 3.0 - Faces 4.0  -->
<dependency>
    <groupId>com.github.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>master-SNAPSHOT</version>
    <classifier>jakarta</classifier>
</dependency>

<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

But I didn't make this change it currently has everything 12.0.0 does so I would expect it to work.
