### ISSUE TITLE
Core: Refactor Exporter - Part 2

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#9969]
### Description

Lot of duplication and code is starting to be really messy

### Describe the solution you would like

Cleaner code, less duplication in general but also  between Table/TreeTable exporter

### Additional context

#5053

**Comment by melloware** [comment]
Agreed we have refactored it multiple times but another pass is probably a good idea.

**Comment by Rapster** [comment]
I'm thinking of getting rid of `DataExporter#exporter` attribute, never liked it... Registering through SPI should be the way of doing it, that gives way more possibility than an attribute.

I should be able to keep things backward compatible even though I don't think it's necessary 😅 

Adding @ravihariharan in CC  I remember you introduced that attr?

**Comment by Rapster** [comment]
Is txt exporter supposed to look like this:

```
datatable
	langs
		idid
		typetype
		namename
		first_appearedfirst_appeared
	langs
	langs
		idid
		typetype
		namename
		first_appearedfirst_appeared
	langs
	langs
		idid
		typetype
		namename
		first_appearedfirst_appeared
	langs
	langs
		idid
		typetype
		namename
		first_appearedfirst_appeared
	langs
	langs
		idid
		typetype
		namename
		first_appearedfirst_appeared
	langs
datatable
```

On showcase, it shows something different also... I'm gonna change the whole example so it doesn't look too much as XML

**Comment by melloware** [comment]
Yeah that doesn't look right for TXT.

**Comment by tandraschko** [comment]
what is the migration for the exporter attribute?

it looks like its a simple way to create a very custom exporter per on component level, where its really required
i dont see any problem having this as small addition to the SPI / global register for a datatype

**Comment by stolp** [comment]
I like to add a vote for keeping the possibility of custom exporters per datatable.

Not that we use it at the moment, yet I think this could be a required option for us in the future.

**Comment by Rapster** [comment]
You still can with `DataExporters#register`, in your specific case you just need to specify a type that will match your custom exporter.

Let's say you same 10 yml exporters, you register 10 yml exporters (yml1, yml2 and so on), you just have to specify in `DataExporter#type` the one that you want to use

**Comment by tandraschko** [comment]
i'm +0.5 for leaving this attribute as special option
it doesnt hurt and i dont like to remove features just because of a refactor, we usually also deprecate first and then remove later

**Comment by Rapster** [comment]
I don't like having x ways for doing the same thing, also it's not due to the refactor, I could have easily make this as a new feature (for the same reason as said before)

Also, it's deprecated, not removed
