### ISSUE TITLE
MenuBar/TieredMenu: add `hideDelay` timeout for hiding menu

### ISSUE THREAD

**Issue by buleseli** [primefaces/primefaces#9970]
### Description

menuBar/tieredMenu: subMenu should hide automatically after some seconds on mouse out.
But it stays until clicking somewhere outside the subMenu.

![iEkFEP8IcQ](https://user-images.githubusercontent.com/16559627/228143042-0497cd15-6998-40cb-95bf-83c287a561c4.png)

### Describe the solution you would like

menuBar/tieredMenu: subMenu **should hide automatically** after some seconds **on mouse out**.if do that ,it will give users more friendly UI.

**Comment by jepsar** [comment]
IMO that won't improve accessibility

**Comment by melloware** [comment]
What he means is once a submenu gets focus the only way to close it is by clicking outside the menu.  Personally I agree with @jepsar that this is the correct UI behavior and provides the user with the element of least surprise.

**Comment by tandraschko** [comment]
AFAICS its default that menu overlays opens on hover and closes on mouseout actually
just check some pages

**Comment by jepsar** [comment]
Yeah, I've seen it done like that as well. I just don't like it. If we would add it it should be configurable somehow.

**Comment by melloware** [comment]
Yep it should be some type of `closeEvent="mouseout"` and defaults to "click" or something like that?

**Comment by tandraschko** [comment]
maybe just add something like "closeDelay"
0 = no auto close
x = auto hide after x ms

**Comment by melloware** [comment]
I like that even better!

**Comment by buleseli** [comment]
@tandraschko @jepsar @melloware 
    thanks for follow this issue! 
    can you give some advises to fix this?my boss want me to resolve this problem because she hard to accept this behavior!

**Comment by jepsar** [comment]
@buleseli If you really "need" this, you could provide a pull request yourself or consider PRO support. Please read https://github.com/primefaces/primefaces#community--elite--pro

Again, I don't like this feature. macOS (to give you an example) does not auto close its menus.

**Comment by melloware** [comment]
@buleseli you can fix this yourself with JS code.  I don't have the time to provide a MonkeyPatch for you unless your boss wants to pay me to provide it...

**Comment by buleseli** [comment]
> @buleseli you can fix this yourself with JS code. I don't have the time to provide a MonkeyPatch for you unless your boss wants to pay me to provide it...
 
 ok,i will try to fix it by myself first! thanks for helping .

**Comment by melloware** [comment]
I actually think this feature is similar or same request as this one: https://github.com/primefaces/primefaces/issues/3209

**Comment by melloware** [comment]
I decided to call it `hideDelay` so its consistent with other components.  if its 0 the current behavior of having to click out to close it remains so this is a backwards compatible change
