### ISSUE TITLE
CSP: report-uri deprecated

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#9972]
According to the docs at:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri

The use of report-uri is no longer recommended and is replaced by the report-to rule and a new Report-To header.
The new Report-To header is used in conjunction with the report-to directive. It provides a JSON object
that defines a named reporting group consisting of multiple endpoints where reports can be sent. 

For browser compatibility it is recommended to provide both report-uri and report-to.
For example:

```
Content-Security-Policy: default-src 'self'; report-uri https://[LOCATION]/my-csp-reports; report-to csp-endpoint
Report-To: {"group":"csp-endpoint", "max_age":10886400, "endpoints":[{"url":"https://[LOCATION]/my-csp-reports"}]}
```

The current web.xml report-uri configuration for primefaces is as follows:

```
	<context-param>
		<param-name>primefaces.CSP</param-name>
		<param-value>reportOnly</param-value>
	</context-param>
	<context-param>
		<param-name>primefaces.CSP_REPORT_ONLY_POLICY</param-name>
		<param-value>report-uri /my-csp-reports</param-value>
	</context-param>
```

Not sure how to define the new report-to directive in a logical way.
Also the question is if multiple endpoints must be supported.

Minium could be:
```
	<context-param>
		<param-name>primefaces.CSP_REPORT_ONLY_ADD_REPORT_TO</param-name>
		<param-value>true</param-value>
	</context-param>
```

Which adds the Report-To json header based on the report-uri and appends "report-to" to the Content-Security-Policy header.
But this feels like a hack.

**Comment by DazzlingBob** [comment]
Please label this as new feature/enhancement.

**Comment by melloware** [comment]
cc @cnsgithub  who added this in https://github.com/primefaces/primefaces/issues/8520

**Comment by melloware** [comment]
@DazzlingBob we are not using the deprecated report_uri we are using the proper `Content-Security-Policy-Report-Only`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only

This is NOT deprecated and still supported by all browser.
