### ISSUE TITLE
Repeating Accordion and TabView loses state when having a data component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#998]
When an repeating accordion or tabview contains a data component to repeat, state is lost.

``` xml
<p:accordionPanel value="#{bean.items}" var="item">
  <p:tab title="#{item.title}">
    <p:dataTable value="#{item.data}" var="d">
      <p:column>
        <p:inputText value="#{d.field}" />
     </p:column>
   </p:dataTable>
  </p:tab>
</p:accordionPanel>
```

Only the last tab's values are saved and restored, tabs before cannot keep state and inputs of datatable for those tabs are rendered blank.

**Comment by kukel** [comment]
what about a datatable in a datatable? or tabs is a datatable?
And is this all caused by switching to a custom UIData some versions ago?

**Comment by cagataycivici** [comment]
Those cases should work now I believe.

**Comment by kukel** [comment]
ok, I'll try to create some interesting combinations of components for testing with different versions of (in my case) Mojarra 2.0, 2.1 and 2.2 (all latest versions).
