### ISSUE TITLE
Calendar: Change event not fired after change when pattern and mask is applied

### ISSUE THREAD

**Issue by jungm** [primefaces/primefaces#9997]
### Describe the bug

A p:calendar with a pattern and mask doesn't fire a change event when leaving the input after changing it. Related to #9953 as reverting the fix for it fixes this issue

### Reproducer

See this test (add it to Calendar002Test):

```java
    @Test
    @Order(2)
    @DisplayName("Calendar: AJAX on leaving input after changes")
    public void testLeaveInputWithChange(Page page) {
        // Arrange
        Calendar datePicker = page.datePicker;
        WebElement outside = page.outside;
        Messages messages = page.messages;

        // Act
        datePicker.getInput().click();
        datePicker.getInput().sendKeys(Keys.chord(PrimeSelenium.isSafari() ? Keys.COMMAND : Keys.CONTROL, "a"));
        datePicker.getInput().sendKeys("01/01/2023");
        PrimeSelenium.guardAjax(outside).click();

        // Assert
        assertDisplayed(messages);
    }
```

### Expected behavior

Change event is fired again when the input is changed

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment]
Thanks for the reproducer I will look at this.

**Comment by melloware** [comment]
Please see my PR.  Don't use mask="99/99/9999" we construct the proper mask from your `pattern` with `mask="true"`.
